### ISSUE TITLE
libtxt: Implement line height algorithm

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#10014]
We should document how we compute line heights, either in the wiki or in dartdoc somewhere.

**Comment by Hixie** [comment]
Each span of text added with the ParagraphBuilder has a box with the font family, size, weight, and style of the applicable TextStyle. Each span also has an alignment text baseline and a line height (given as a factor of the font size). Spans of text can be nested.

Each span is laid out, determining line breaks, such that each line now consists of a hierarchy of spans, with the line at the top of the hierarchy.

Spans can end up having text in multiple font families, with different metrics. All of the glyphs within a span must be aligned such that the baseline identified by the alignment text baseline of the span (alphabetic, hanging, ideographic, etc) is in the same relative vertical position for each glyph in the span.

Each line has a font family, size, weight, and style of the ParagraphStyle, and a line height (given as a factor of the font size).

The ostensible font family, size, weight, and style of each span (not of each glyph in each span) and of each line, defines the relative positions of all the kinds of baselines, for that span or line.

Each span on each line is aligned so that its alignment text baseline is at the same relative position as that same baseline for its parent's span or line.

This results in a series of lines, within which are many boxes that have positions relative to the line. Each box has the size of its font size, regardless of what glyphs are actually used in the box. (It's possible for a box with a single character to specify a particular font, but for the glyph to come from another font. The glyph in that case is aligned with the relevant baseline of the box's font, as described above, and thereafter the glyph's metrics are not used.)

For each line box and each span box within each line box, determine the "margin top" and "margin bottom" as follows.  

Let absolute line height be the font size times the line height.
Let half-leading be the absolute line height minus the font size, divided by two. (This can be negative.)
The margin top is the top of the box plus the half-leading, going up.
The margin bottom is the bottom of the box plus the half-leading, going down.

For each line, find the highest margin top and the lowest margin bottom. The line's height is the difference between these.

Lines are stacked so that the bottom margin of the previous line abuts the top margin of the next line. The top margin of the first line is at position zero. The bottom margin of the last line is the intrinsic height of the box.

**Comment by abarth** [comment]
Thanks!

**Comment by Hixie** [comment]
cc @jason-simmons Hey, look, I already wrote this.

**Comment by Hixie** [comment]
keyword: libtxt

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/3495

**Comment by GaryQian** [comment]
This is sufficiently implemented that I will close this. More specific work can be specified in dedicated issues.
