### ISSUE TITLE
iOS channel ,signal SIGABRT somewhere

### ISSUE THREAD

**Issue by butterflyXX** [flutter/flutter#100189]
iOS ,
```
Runner(33809,0x16dfcb000) malloc: Heap corruption detected, free list is damaged at 0x281b76a00
*** Incorrect guard value: 5866050001116939122
Runner(33809,0x16dfcb000) malloc: *** set a breakpoint in malloc_error_break to debug
```
![F650B14585C320F74C4D5C6377CD45C7](https://user-images.githubusercontent.com/24794442/158517231-3ec87650-88b3-4a18-85de-3473457b1947.png)
![15059709DAC252E937AD4DE4E80E9DF2](https://user-images.githubusercontent.com/24794442/158517249-9d6f125f-fd95-4129-89cd-82fdca49c69f.png)
![DFAD8B93C66A6002AEF5B8A7F9E4DB2B](https://user-images.githubusercontent.com/24794442/158517259-2ad7031a-196b-463a-8e64-4d9e2221019a.png)

I can't find the problem

**Comment by darshankawar** [comment]
@butterflyXX 
Please don't post screenshots as they are not much helpful when it comes to looking at the logs.

Also as a note, please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details in it so that we'll have enough details to work with.

Currently the info you provided isn't much to properly address this issue.
Please provide your `flutter doctor -v`, iOS version on which you are seeing this behavior, complete verbose log in properly formatted text that we can take a look and steps to replicate along with a minimal code sample if possible, that throws the error you are reporting.
