### ISSUE TITLE
[macOS] TextField lost input event after composing text deleted

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter#100272]
Noticed that https://github.com/flutter/flutter/issues/78061 has been fixed, but there seems to be a small problem here.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. type Chinese by PinYin input method. 
    for example: type nihao
<img width="503" alt="image" src="https://user-images.githubusercontent.com/17426470/158724743-3689fce1-f2f2-489a-a8ee-ee6b6c49f32b.png">

3. press `backspace` to delete all composing text in floating view.
4. when all composing text be deleted, this `TextField` can not input number, character any more.

**Expected results:** 

**Actual results:** 

https://user-images.githubusercontent.com/17426470/158725518-88716487-8ec2-4e61-bf42-59604a736d67.mov

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue
      ),
      home: const _HomePage(),
    );
  }
}


class _HomePage extends StatelessWidget {
  const _HomePage({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body:  Center(
        child: TextField(),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
➜  my_app flutter --version
Flutter 2.13.0-0.0.pre.114 • channel master •
https://github.com/flutter/flutter.git
Framework • revision b4040c867b (15 minutes ago) • 2022-03-17 10:15:13 +0800
Engine • revision 46c2ccae24
Tools • Dart 2.17.0 (build 2.17.0-202.0.dev) • DevTools 2.11.4
```

</details>

**Comment by cbracken** [comment]
This also reproduces with macOS _Japanese - Romaji_ input method.

To be very slightly more specific with the repro steps:
1. Input and commit some text into a textfield. A simple option would be the text 'hello'.
2. Switch the system input method to Pinyin or Japanese.
3. Begin typing some composing text but do not commit. e.g. 'nihao'
4. Press backspace until the composing region is empty.
5. While remaining in Pinyin or Japanese mode, type a character such as 'n'. Note that backspace works as expected here; input characters do not.

Expected behaviour: composing region now contains the character typed (e.g. 'n')
Actual behaviour: composing region contains nothing, IME candidate menu pops up at screen position (0,0).

I haven't tried debugging this, but I suspect that we've got an off-by-one error in how we set the composing state. In other words, we're leaving TextInputModel in composing mode after the last character is deleted, or we're failing to begin composing and activate the IME once the first new character is typed after deleting all text in the composing range.

One more hint at what's going on here: the IME candidates menu position is the combination of two inputs. I'm going from memory here, so we'll want to double-check this, but one is the composing rect in window co-ordinates, the other is a coordinate transform matrix. I suspect we only apply/update the position in screen co-ordinates when we're composing, which would be further evidence that we're not in composing mode when we type that first character after deleting all text in the composing range.

**Comment by LongCatIsLooong** [comment]
The `NSTextInputContext` we use in the text input plugin seems to be deactivating itself whenever the composing region is deleted, without even calling `NSTextInputContext.deactive`. There's a [`NSTextInputContext.isActive`](https://github.com/hughbe/macOS-iOS-headers/blob/a7c89732a3e78c50370880677a06518ddfc0bcba/macOS/Frameworks/AppKit.framework/NSTextInputContext.h#L151) private method that can be used to confirm this.

The right fix seems to be properly incorporate `FlutterTextInputPlugin` into the responder chain (or view hierarchy), and make it the primary focus when it's supposed to be taking input. But I think the change is going to be substantial. Calling `[_textInputContext activate]` before `[_textInputContext handleEvent:]` also seems to work but it's quite hacky.

**Comment by cbracken** [comment]
This was resolved in https://github.com/flutter/engine/pull/32117.

**Comment by LongCatIsLooong** [comment]
@cbracken I was planning to repurpose this issue for properly setting up the responder chain on macOS for text input. Should I create a new issue instead?

**Comment by LongCatIsLooong** [comment]
Created https://github.com/flutter/flutter/issues/100590

**Comment by cbracken** [comment]
Ah thanks; this was listed on the stable blockers dashboard and had moved it to done. Thanks for creating a new issue for the proper strategic fix for this!
