### ISSUE TITLE
Remove Primary Scroll Controller for Flutter Desktop apps

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#100264]
Common desktop error: `The provided ScrollController is currently attached to more than one ScrollPosition.`

From medium article: https://andrewzuo.com/flutter-for-desktop-apps-isnt-ready-yet-663664262dde

For context, desktop apps frequently have multiple vertical scroll areas, e.g. [`desktop_photo_search`](https://github.com/flutter/samples/tree/master/desktop_photo_search) has a sidebar and mainn content area, both of which scroll vertically.

This combination results in a runtime error from a cranky primary scroll controller, as mentioned above. Work around is manually instantiate a scroll controller, e.g. https://github.com/flutter/samples/blob/master/desktop_photo_search/material/lib/src/widgets/unsplash_search_content.dart#L23

**Comment by Piinks** [comment]
Unfortunately I do not think this will be ass straightforward as I had hoped. Couple of findings:

1. The PrimaryScrollController is also used in the NestedScrollView in order to have the inner scroll view inherit the scroll controller that it manipulates to keep the 2 positions in sync.
  - So we would have to find a way around this or it would break the NestedScrollView for desktop applications.
2. Default keyboard scroll actions on desktop actually rely on the PrimaryScrollController to work. A PSC is created for each route, and when the user taps the arrow keys, if the current focus is not enclosed by a scrollable, it looks up the PSC as a fallback to automatically have keyboard scrolling shortcuts work.
  - In this case, I think the same `more than one position attached...` issue actually applies to scroll actions too, if not I do not think the user would want multiple scroll views to move in response to a key stroke. If we disable the automatic attachment of PSC completely, the user would have to specify which scrollview they want to be the default for scroll actions by setting ScrollView.primary to true. I think this would be an ok trade-off but it is still one to consider carefully.

⭐ ➡️  I think for now, the best workaround is to set `primary: false` on ScrollViews that should not connect to the PSC. I think it is better than setting an individual scroll controller for each.

If anyone has thoughts on this, please do share. I am still investigating a few more options here.
