### ISSUE TITLE
SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64)

### ISSUE THREAD

**Issue by imrikim** [flutter/flutter#100288]
I am trying to connect to an IoT device that has no connection and then doing some http requests. but the device doesn't recognise the method get, and I got the error on the title, any ideas what is happening here ?

**Comment by darshankawar** [comment]
@imrikim 
`IoT device that has no connection` since the device you are targeting has no connection, the error being thrown seems to be correct as it says `Machine is not on the network,`.
You can try to ask this on support channels like Stackoverflow to get solutions. Closing from here. If you disagree or think this is a Flutter issue, write in comments and I'll reopen it.

**Comment by imrikim** [comment]
Okay 👍 
let's close the issue then since the error is correct and nothing weird here.
