### ISSUE TITLE
The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by dd9913762113** [flutter/flutter#100367]
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has
read/write permissions for the current user.

flutter doctor -v

<img width="911" alt="截屏2022-03-18 20 25 11" src="https://user-images.githubusercontent.com/85228967/159002995-e87aef58-018e-4250-9c46-0eea697398df.png">

**Comment by dd9913762113** [comment]
can you tell me which  the file or directory ?

**Comment by darshankawar** [comment]
@dd9913762113 
As the error indicates, that flutter tool cannot access the sdk because the location or path at which you have it doesn't have read or write permission for flutter tool to access it. Make sure the directory has read/write permissions, if not change location to the directory that has these permissions.
Closing as the tool is throwing correct error as it is unable to access the sdk.
