### ISSUE TITLE
url_launcher fails with complex mailto argument on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10032]
Found while testing https://github.com/flutter/plugins/pull/15, looks like `mailto` arguments fail on iOS if they have a `body` part, e.g. `launch('mailto:smith@example.org?subject=Help&body=I need help!');` fails with:

```
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
PlatformException(Error, Error while launching (null), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:518:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:140:18)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:18:19)
#3      _MyHomePageState._incrementCounter.<anonymous closure> (/Users/mit/tmp/mailto/lib/main.dart:61:7)
#4      State.setState (package:flutter/src/widgets/framework.dart:922:30)
#5      _MyHomePageState._incrementCounter (/Users/mit/tmp/mailto/lib/main.dart:53:5)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:194:14)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:65:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:9)
#9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:119:27)
#11     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:126:20)
#12     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
#13     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
#14     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
#15     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
#16     _dispatchPointerDataPacket (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:73)
```

**Comment by mit-mit** [comment]
Would be good to investigate if this is just a limitation on iOS or if it's an issue in our framework or plugin implementation.

**Comment by szakarias** [comment]
This fails because of the space in 'mailto:smith@example.org?subject=Help&body=I need help!'. It should be 'mailto:smith@example.org?subject=Help&body=I%20need%20help!' and then it works just fine.

**Comment by mit-mit** [comment]
Just tested again, and here is what I'm seeing with `await launch('mailto:smith@example.org?subject=News&body=New%20%Flutter%plugin');`:

1. Android: it works, but the `%20` part is included in the actually email, and is not changed to a space

1. iOS: it throws a platform exception

@szakarias, what am I doing wrong?

**Comment by szakarias** [comment]
1) The string is malformed. It has  "%" after the first "%20" and no "20" after the second "%". Change it to 'mailto:smith@example.org?subject=News&body=New%20Flutter%20plugin' and it should work. :-)

2) Are you using the simulator? Remember that the simulator cannot handle mailto because the mail application is not available.  If you use `canLaunch` before calling `launch` you will get more info.

**Comment by dark-chocolate** [comment]
@szakarias , let's say I have a string that I am going to use for body. 
`String string = "This is a long string that may contain words up to length 500"`

 So, for android I don't need anything like `%20` for showing space, but for iOS I need that. 

How do I add `%20` for every space, your team should have done that work behind the scenes to make developer life more easy, otherwise we developer have to play with the string, like

```
if (iOS){ // we can also remove this check as Android is a good boy, you give it space or `%20` he doesn't mind that. 
string = string.replace(" ", "%20"); // but this is something we need to do. 
}
```

**Comment by zoechi** [comment]
@dark-chocolate better to use `Uri.encodeFull(urlString)` or `Uri.encodeComponent(urlString)` instead of replacing `' '` by `'%20'` "manually"

**Comment by dark-chocolate** [comment]
@zoechi Now that's why I put my limited knowledge of replacing string as a solution, I knew this might not be the best and someone would suggest a better solution, and here comes the champ. Thank you buddy. Really appreciate your suggestion. I will use it.

**Comment by dark-chocolate** [comment]
@zoechi Thanks for the solution but it didn't work the way I supposing. For instance i have 

`String string = "Nice day"
`
And I use it in below code like this:

```
String uri = 'mailto:hello@domain.com?subject=${subject}&body=${Uri.encodeComponent(string)}';
    if (await canLaunch(uri)) {
      await launch(uri);
    } else {
      print("CoolTag: No email client found");
    }
```

It opens the mail app and message body looks like
`Nice%20day`

And replacing string works fine (my old solution).

**Comment by zoechi** [comment]
I don't see why your last example wouldn't work because `Uri.encodeComponent('Nice day')` results in the same result as your `string.replace(" ", "%20")` approach but covers more scenarios.

If you have a full URL just use

```dart
String uri = Uri.encodeFull('mailto:hello@domain.com?subject=${subject}&body=${string}';
```

**Comment by dark-chocolate** [comment]
@zoechi  My blunder. I forgot to delete my 

  `string = string.replace(" ", "%20"); `

And after this line I had 

`Uri.encodeComponent(string)`

So it again added the %20, sorry it was really a blunder from my end. I really appreciate the way you help people like me. Thank you Günter :)

**Comment by da7om85** [comment]
same issue when using Arabic language
even when I use one word.
I got this error
Runner[4552:1068461] [VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
Could not launch mailto:test@gmail.com?subject=سلم

please fix this issue

**Comment by zoechi** [comment]
@da7om85 did you use `Uri.encodeFull(...)`?

**Comment by stuartmorgan** [comment]
Since the comments above were referenced elsewhere as a solution, I want to point out that `encodeFull` is not a robust solution. In particular, if one of the strings contains an & the query string will not be as intended.

The right approach is to encode each URL component with the API intended for that purpose.

**Comment by CoreyCole** [comment]
In my opinion, first party plugins should do their best effort to make the API as-consistent-as-possible across all platforms. A developer should not use a plugin develop something that works on android, and then later find out that the same API use is incompatible on iOS.

As @stuartmorgan mentioned in #42279, it is impossible to correctly encode an arbitrary string without knowledge of its intended use. So instead of taking an arbitrary string, could we create new `launch()`/`canLaunch()` methods that accept an object as a parameter instead of an arbitrary string?
```dart
final MailtoLaunchParams launchParams = {
  email: 'smith@example.org',
  subject: 'Example Subject & Symbols are allowed!',  
};
// ...
canLaunch(launchParams);
launch(launchParams);
```
This way, url_launcher can have an easy-to-use API that doesn't require the beginner-unfriendly use of the static Uri helper methods.

**Comment by stuartmorgan** [comment]
url_launcher can launch arbitrary URL types, not just mailto. http, tel, and sms as noted in the readme, but also any arbitrary third-party-registered scheme.

As for consistency across platforms: the API takes URLs, and it will consistently accept valid URLs across platforms. The inconsistency only comes when using the API incorrectly and passing invalid URLs.

**Comment by CoreyCole** [comment]
Yes, I understand we can launch other url types besides mailto. It was not a complete proposal, just an example to get the conversation started.

I understand url_launcher handles properly encoded urls. That is great and it should continue doing that. My only point is that it is not beginner friendly, especially with the current state of the documentation/examples.

Either the API or the documentation can be improved, or both! Its bad practice in tech to blame your users for not understanding how to use your product, the same principle applies to APIs for developers :)

**Comment by stuartmorgan** [comment]
But my point is that because it can launch arbitrary URLs, you need a generic URL construction mechanism; you can't special case each possible scheme because the set of schemes is unbounded. And there already is a usable, generic way of constructing arbitrary URLs from structured data: the `Url` constructor. You can pass the query parameters as a map of unescaped values and it will do the right thing, for instance. Using the static methods and string concatenation is not required as you asserted above.

I'm certainly not arguing that the documentation couldn't be improved. Showing an example that does mailto using the `Url` constructor seems like a good idea to me (although to be clear, it's not my call since I am not a maintainer for that plugin).

**Comment by CoreyCole** [comment]
Yes, the potential schemes are unbounded. But, I still think it would be a good idea to make beginner-friendly wrapper methods around the most common use cases, such as mailto. We will always have the default arbitrary string launcher as a fallback if the wrappers don't meet the developer's use case, or the developer is comfortable encoding URLs manually.

As for improving the documentation for the current behavior, I'm assuming you're talking about the [Uri constructor](https://api.dartlang.org/stable/2.5.2/dart-core/Uri/Uri.html)?
```dart
final mailToUri = Uri({
  scheme: 'mailto',
  userInfo: 'smith',
  host: 'example.com',
  queryParameters: {
    subject: 'Example Subject & Symbols are allowed!',
  }
});
final mailToLaunchString = mailToUri.toString();
// ...
canLaunch(mailToLaunchString);
launch(mailToLaunchString);
```
(warning I haven't tested the above code, I'm just guessing at how it might be used)

**Comment by stuartmorgan** [comment]
> But, I still think it would be a good idea to make beginner-friendly wrapper methods around the most common use cases, such as mailto.

If your the core issue here is that you find the existing Dart URI construction APIs too hard to use for common URI types, it seems like a good solution would be to make a package that provided special-case construction for whatever specific schemes you are interested in, and then people who don't like the existing APIs could use your package to make URIs instead.

`mailto` URLs aren't specific to `url_launcher`, after all, so it's not clear to me how building it into url_launcher make sense. That would add complexity for those who are fine with the existing APIs, while at the same time making it impossible for people to use it in other contexts where they might want `mailto`—or whatever other scheme—URLs

> As for improving the documentation for the current behavior, I'm assuming you're talking about the [Uri constructor](https://api.dartlang.org/stable/2.5.2/dart-core/Uri/Uri.html)?

Yes, sorry. Fixed the `Url`->`Uri` mistake in my comment above so it's less confusing.

**Comment by CarlosIvanHuerta** [comment]
Hello, my solution:

```
final Uri _emailLaunchUri = Uri(
    scheme: 'mailto',
    path: 'demo@demo.com',
    queryParameters: {
      'subject': 'Solicitud de información.',
      'body': 'A quien corresponda:'
    }
);

String a =  _emailLaunchUri.toString().replaceAll("+", "%20").replaceAll("%2520", "%20");
launch(a);
```
