### ISSUE TITLE
 test "Mac beta verify_binaries_codesigned" failing for release branch

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100306]
while running post submit checks for release branch flutter-2.12-candidate.4, Mac beta verify_binaries_codesigned testing consistently fail, relevant build logs are: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20beta%20verify_binaries_codesigned/411/overview

based on reasoning from @godofredoc it is because the test is trying to checkout the release hash from master branch instead of the correct branch. Related similar failures are seen in https://github.com/flutter/flutter/issues/100266.

**Comment by christopherfujino** [comment]
```
Exception on command "checkout 680962aa75a3c0ea8a55c57adc98944f5558bafd": Command "git checkout 680962aa75a3c0ea8a55c57adc98944f5558bafd" failed in directory "/opt/s/w/ir/x/w/flutter_conductor_checkouts/framework" to checkout ref. Git exited with error code 128.
stderr from git:
18:28:09.783895 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /opt/s/w/ir/cipd_bin_packages/bin/git
18:28:09.784473 exec-cmd.c:238          trace: resolved executable dir: /opt/s/w/ir/cipd_bin_packages/bin
18:28:09.785084 git.c:458               trace: built-in: git checkout 680962aa75a3c0ea8a55c57adc98944f5558bafd
fatal: reference is not a tree: 680962aa75a3c0ea8a55c57adc98944f5558bafd

#0      Git._reportFailureAndExit (package:conductor_core/src/git.dart:77:5)
#1      Git.run (package:conductor_core/src/git.dart:43:7)
<asynchronous suspension>
#2      Repository.checkout (package:conductor_core/src/repository.dart:247:5)
<asynchronous suspension>
#3      FrameworkRepository.checkout (package:conductor_core/src/repository.dart:601:5)
<asynchronous suspension>
#4      CodesignCommand.run (package:conductor_core/src/codesign.dart:121:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///opt/s/w/ir/x/w/flutter%20sdk/dev/conductor/core/bin/cli.dart:78:5)
<asynchronous suspension>
```

I think I can fix this.

I think the problem is that when we're verifying the engine binaries, I wanted to save time by not cloning the framework under test from github: https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/codesign.dart#L76

By using `FrameworkRepository.localRepoAsUpstream`, we clone a new framework based on the local Flutter repo that the LUCI recipes have set up. It looks like this:

`(1) Upstream flutter/flutter ---clones to--> (2) LUCI recipe managed flutter ---clones to--> (3) conductor-managed flutter`

I believe that the problem is Flutter #3 is trying to checkout a commit hash that Flutter #2 doesn't know about. If we cut out the middle repo, flutter #1 is the source of truth that should know about every commit hash, regardless of the branch.

**Comment by christopherfujino** [comment]
I'm re-opening this as my fix was wrong (less wrong than before, but still wrong).

This post-submit build failed: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8819041554961337905/+/u/Verify_binaries_codesigned/verify_binaries_codesigned/test_stderr. It's because it's cloning from ssh, with git@github.com:flutter/flutter.git, which the LUCI build does not have credentials to do. As this test never needs to push to the remote, it should use the https protocol to clone the repo, which does not require authentication.
