### ISSUE TITLE
difficulty installing Flutter

### ISSUE THREAD

**Issue by cnaez** [flutter/flutter#100378]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by christopherfujino** [comment]
@cnaez Thank you for contributing. However, you did not fill out the template, and this issue is not actionable. I am going to close this. Feel free to file a new issue, providing:

1. a clear description of the problem you are experiencing installing Flutter
2. the steps that you tried
3. any log output or error message that you received
