### ISSUE TITLE
please ensure that the sdk and/or project is installed in a location that has read/write permissions for the current user.

### ISSUE THREAD

**Issue by DoaaNwe** [flutter/flutter#100452]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@DoaaNwe 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. 

Looking at the error you mentioned, `please ensure that the sdk and/or project is installed in a location that has read/write permissions for the current user`, it seems wherever your current sdk location is, it isn't accessible to flutter tool and hence it rightly is throwing the message which should indicate what need to be done at your end. Have your sdk at a location or path and make sure it has proper read write permissions.

Closing from here.
