### ISSUE TITLE
Flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value #94412

### ISSUE THREAD

**Issue by waleedtarbosh** [flutter/flutter#100413]
![image](https://user-images.githubusercontent.com/72128950/159117827-9d77ee98-c5e1-4afd-8c96-a83d238c751a.png)

**Comment by hamdikahloun** [comment]
Hi @waleedtarbosh 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

**Comment by darshankawar** [comment]
@waleedtarbosh 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough info to work with. Currently there's not enough details to make this actionable. Also please don't post screenshots that shows the error which isn't much helpful for us.
Closing as not enough details provided to proceed further. Please use new issue template to make the issue actionable.
