### ISSUE TITLE
My APK size it's greater than 150mb

### ISSUE THREAD

**Issue by rrrovalle** [flutter/flutter#100579]
Hi guys, i'm having some problems while compiling my flutter app for Android.. I've only 3 assets and a couple packages added, but when I try to compile, I got this:

`√  Built build\app\outputs\flutter-apk\app-release.apk (158.3MB).`

Any idea? 

**Flutter build log (running flutter build apk)**

PS C:\Users\Admin\Desktop\Fictix\Don't Touch This\app\dtt_app> flutter build apk
 Building with sound null safety 

```
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Formato de par�metros incorreto -
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-11.2.11\android\src\main\java\io\flutter\plugins\firebase\messaging\JobIntentService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound_lite-8.5.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSound.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.2.4\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.11\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleRelease'...       
```

**Comment by jonahwilliams** [comment]
The minimum APK size for a single ABI on Android is around 4.5 MB last time I checked. If your APK is significantly larger than that, you should check the file sizes of your assets either by using your local file explorer or using flutter's tooling: https://docs.flutter.dev/perf/app-size

Without any of this information or access to your APK, we can't provide any guidance

**Comment by cwangfr** [comment]
i have same problem, some day before, i create apk was 40mk, but today, the same project apk size has great to 105m 

`❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale zh-Hans)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale zh-Hans)
    • Flutter version 2.10.3 at /Users/changwang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/changwang/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • SM T500 (mobile) • R9AR90JRS1W • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

`

**Comment by Splokhande** [comment]
As @cwangfr said this might be due to due to some packages, can you share the list of packages you are using? 
Also, are you using firebase analytics and related dependency?
Sometimes firebase related dependency might also result in a size increase.

**Comment by NedimKaravdic** [comment]
### Assets and unused materials
In order to reduce your app size please check the size of imported assets.
According to official Flutter documentation it's advised to compress any PNG and JPEG files.
You should also minimize amount of imported sources from libraries.

### Build options
While building your release version please consider using "--split-debug-info" tag, since it can reduce  your app size a lot.
If you are building your app for Android device make sure you run "flutter build appbundle" instead of api since it is recommended by Google for publishing your Android app on Play Store with less size.

### Breaking down the app size
Size analysis tool was introduced to 1.22 version of Flutter in order to help developers understand the breakdown of the release build. You can use this tool by passing "--analyze-size" tag in build command.
This tool compiles Dart in a way that records code size usage of Dart packages and it leaves "*-code-size-analysis_*.json" file for more detailed analysis in DevTools.
With DevTools you can go even deeper but I advise you to start here [`](https://docs.flutter.dev/development/tools/devtools/app-size)

**Comment by NedimKaravdic** [comment]
Assets and unused materials

In order to reduce your app size please check the size of imported assets.
According to official Flutter documentation it's advised to compress any PNG and JPEG files.
You should also minimize amount of imported sources from libraries.

Build options

While building your release version please consider using "--split-debug-info" tag, since it can reduce your app size a lot.
If you are building your app for Android device make sure you run "flutter build appbundle" instead of api since it is recommended by Google for publishing your Android app on Play Store with less size.

Breaking down the app size

Size analysis tool was introduced to 1.22 version of Flutter in order to help developers understand the breakdown of the release build. You can use this tool by passing "--analyze-size" tag in build command.
This tool compiles Dart in a way that records code size usage of Dart packages and it leaves "-code-size-analysis_.json" file for more detailed analysis in DevTools.
With DevTools you can go even deeper but I advise you to start here [DevTools documentation](https://docs.flutter.dev/development/tools/devtools/app-size)
