### ISSUE TITLE
[linux desktop] GSLS:7 error:

### ISSUE THREAD

**Issue by ydddx** [flutter/flutter#100600]
run app in linux failed

![image](https://user-images.githubusercontent.com/58802847/159637807-92e110ca-a939-4e5e-a5c8-2dc9e51d9c5e.png)

this is an flutter example  app
code from flutter example

![image](https://user-images.githubusercontent.com/58802847/159649675-39fc8975-a1b9-4905-b967-493c1bc40ef8.png)

command:
flutter run -v

logs:
![image](https://user-images.githubusercontent.com/58802847/159649191-6eb58a1b-6825-4dc0-be2e-e02333d1757e.png)

**Comment by maheshmnj** [comment]
Hi @yddx, 
When opening an issue, please try to provide all or some of the information requested in the issue template so that the issue is actionable. In order to investigate this issue further please update the issue description with the steps to reproduce the issue along with a minimal and complete code sample.

Thank you.

**Comment by ydddx** [comment]
> Hi @yddx, When opening an issue, please try to provide all or some of the information requested in the issue template so that the issue is actionable. In order to investigate this issue further please update the issue description with the steps to reproduce the issue along with a minimal and complete code sample.
> 
> Thank you.

Hi @maheshmnj 
I update the  issues.

Thank you.

**Comment by ydddx** [comment]
I solved the problem
Because of my graphics driver doesn't support opengl 3.2

Thank you.
