### ISSUE TITLE
Support: standard text editor widget

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#100675]
To extend the web and desktop, it must support the Flutter standard text editor widget. 
Some solutions posted on Pub.dev are not good alternatives.
Let me know if you have any plans

.

**Comment by maheshmnj** [comment]
Hi @Patrick386, Adding a TextEditor widget to the framework is not possible because there are already few community-driven solutions such as https://pub.dev/packages/super_editor. Also, The flutter provides the freedom to build a texteditor on top of the existing apis.
Closing the issue as invalid, Incase you disagree feel free to write in the comments and we will roepen it.

Thank you.
