### ISSUE TITLE
[DevTool]Unable to connect to VM service 

### ISSUE THREAD

**Issue by coldstar96** [flutter/flutter#100730]
## Steps to Reproduce

I'm seeing **Unable to connect to VM service** when selecting image using image_picker
<img width="299" alt="Screen Shot 2022-03-24 at 7 20 27 PM" src="https://user-images.githubusercontent.com/3282437/160029248-0c23ef70-7dc1-4081-aa87-26b3cab9c0cd.png">

Flutter doctor
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability<details>

1. Clone https://github.com/coldstar96/image_picker_simulator
2. Run the app on Android
3. Follow steps from the video
<video width="299" src="https://user-images.githubusercontent.com/3282437/160028922-11b25441-d5f7-480e-b37a-951eb59003b5.mov" />

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@coldstar96 
`WebSocketChannelException: WebSocket connection failed` indicates that call to connect to websocket didn't occur.
Is there any firewall or proxy that might be prohibiting the emulator to connect to `127.0.0.1` ?

Can you try the same using command line and see if it works or gives you same error, instead of running from your IDE ?

**Comment by coldstar96** [comment]
Seems to be working again. Not sure what was happening before
