### ISSUE TITLE
Crash in arm64 AOT Dart code

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#100865]
b/226647006

Culprits are https://dart-review.googlesource.com/c/sdk/+/237520 or https://dart-review.googlesource.com/c/sdk/+/233881

237520 rolled into the Engine at https://github.com/flutter/engine/commit/560243c4aec13c54ffee3d444f3bd2087fce01ef

We may need to cherry-pick a revert of that Dart roll in the Engine on the branch for the current g3 roll.

@rmacnak-google @a-siva

**Comment by zanderso** [comment]
cc @CaseyHillers @angjieli @renyou @jiahaog

**Comment by mraleph** [comment]
Regarding [cl/237520](https://dart-review.googlesource.com/c/sdk/+/237520): According to ARMv8-A reference manual `LDP` with SIMD/FP registers will check `SP` alignment (if used with `SP` register and these checks are enabled). I wonder if this is related. /cc @rmacnak-google

**Comment by rmacnak-google** [comment]
I think we always generate these loads and stores against DSP/R15, not CSP/R31, so the alignment restriction would not apply.

Just looking at the Fuchsia-specific disassembly for the entry stub, I see a mismatch between the save and restore code, so this is likely fixed by https://dart-review.googlesource.com/c/sdk/+/239160

**Comment by akbiggs** [comment]
Marking as fixed because the fix was rolled in.
