### ISSUE TITLE
flutter create: record Dart SDK location in non-IDEA-specific config file?

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#10096]
We currently record the Dart SDK's location in `.idea/libraries/Dart_SDK.xml`. This file isn't easily readable by other editors or IDE's.

For example, [this just happened to me with VS Code](https://github.com/Dart-Code/Dart-Code/issues/294). (However, it is a corner case. VS Code looks in the user's PATH for the `flutter` command, which should work for users who follow the official instructions, but fails for weird people like me who use a bash alias instead.)

We might want to consider putting either the Flutter SDK or the Dart SDK's location somewhere else? Perhaps in a `ide_settings.json` file? If `flutter create` creates it and the Flutter plugin updates it, the user can switch between VS Code and IDEA and everything will work, even if the user switches Flutter SDK's in the IDE.

One possible design might be to stop generating the .idea folder in `flutter create` and instead have the Flutter plugin get its settings from an `.ide_settings.json` file. This would make the flutter SDK less tied to a specific IDE, and avoid clutter for other situations, such as [creating a new module in an existings IDE project](https://github.com/flutter/flutter-intellij/issues/1014).

**Comment by skybrian** [comment]
Sorry, meant to mention instead: @devoncarew @pq

**Comment by DanTup** [comment]
It would be best for me (Dart Code) if this file contained the Flutter SDK path than the Dart one, since I'll need to be able to execute `flutter` too. I presume Dart is always in the same subfolder (bin/cache/dart?).

ide_settings.json sound sightly strange to me since although this is for the IDE it's not logically and IDE setting.

Any reason flutter uses `sdk: flutter` in pubspec and not a path there like when you reference projects from other locations?

**Comment by skybrian** [comment]
One difference is that the location of the Flutter SDK is often machine-specific, unlike everything in pubspec.yaml. (But I'll admit we aren't handling that cleanly.)

**Comment by skybrian** [comment]
Perhaps name it something like `local.json` which contains local settings? (Similar to Gradle's `local.properties`.)

**Comment by DanTup** [comment]
With no experience with Flutter, I don't really have a well-founded opinion on this. Something generic like that sounds better to me, though I don't want to encourage cluttering a project root with more settings files if there may already be lots of others (pubspec, analysisoptions, etc.!).

I have no idea about how `flutter: sdk: flutter` came to be so this might be stupid, but if pubspec.yaml is already somewhat flutter-aware, is that not a good place (though it's not really pub-related)? Using env variables could fix the multi-OS problem (`sdk: %FLUTTER_HOME%` or something).

I thought it weird that `sdk: flutter` sometimes appears multiple times in a `pubspec.yaml`, when it seems like something that is effectively a global switch, moving everything to the flutter-dart-sdk and changing all the commands you'd use?

**Comment by pq** [comment]
@Hixie: care to chime in on the `flutter: sdk` history (or tap someone else?)

**Comment by skybrian** [comment]
Path variables [1] make it harder, though. IDEA automatically adds them to its config files using rules that are unclear to me. I worry that it won't work reliably (corner cases and bad error reporting, resulting in confused users).

[1] https://www.jetbrains.com/help/idea/2017.1/path-variables.html

**Comment by Hixie** [comment]
The Dart SDK location is effectively stored in the `.packages` file once you've run `pub get` once, which the flutter tool does for you when you run `flutter create`. The location is in a fixed position relative to the `flutter` package's location stored in that file. It's possible for that file to get deleted, but all you have to do is run `flutter packages get` and you'll have it again.

Actually, if you can run the `flutter` tool then you already know the Dart SDK's location, since it's location is fixed relative to the location of the `flutter` tool.

**Comment by skybrian** [comment]
Looking in the .packages file sounds like a good way to do it. The use case is where a different process ran `flutter create` and the IDE wants to pick up the same one they used.

**Comment by skybrian** [comment]
(This comes up when the user has a terminal and editor open, and is partially working from the command line, partially in the editor.)

**Comment by skybrian** [comment]
It looks like either the `flutter:` or `sky_engine:` entries would work, after removing a suffix.

**Comment by DanTup** [comment]
> Having the sdk location in .idea/libraries/Dart_SDK.xml helps the IntelliJ use-case. I'd prefer not to write too many meta-data files into the project if we can avoid. 

I agree you shouldn't write any more, but I'd also argue you shouldn't write this one!) As a user, I would be confused when a `.idea` folder gets created when I create a new flutter app if I don't use (or even have) IntelliJ! (it's not a big deal though; I'd likely just immediately delete it!).

> It looks like either the flutter: or sky_engine: entries would work, after removing a suffix.

Sounds like a reasonable plan. I'll look at adding these to an upcoming version of Dart Code; I'm going to check them in this order (please shout if you think I can do better!):

- Current folder (eg. check for `./bin/flutter(.bat)` and `./bin/cache/dart-sdk/bin/dart(.bat)`) 
- `.packages` file; `flutter:` or `sky_engine:`
- `.idea/libraries/Dart_SDK.xml` (if parseable)
- `FLUTTER_ROOT` env variable
- All folders in `PATH`, in order

In all cases I'll only consider it a match if I find a binary for flutter and dart in the expected locations. The reason for "current folder" is to support the flutter repo (it doesn't have either `.packages` or `Dart_SDK.xml` in the repo) and the others are just trying anything we can. I've given preference to the ones inside the project itself because that seems more flexible if you want to override more global settings (like `PATH`) for the odd projects (or testing).

Sound reasonable?

**Comment by DanTup** [comment]
> Also, regarding looking at the current Folder, the only case I think that covers is editing FLUTTER_ROOT itself?

I believe so (@abarth raised https://github.com/Dart-Code/Dart-Code/issues/275 so I figured at least one person had tried!). I don't think it causes any false positives if I'm checking their are both Flutter and Dart binaries.

> Since you're assuming the user is familiar with the command line, you could probably skip looking at `.idea/libraries/Dart_SDK.xml` and ask the user to run flutter packages get to create the .packages file. 

But if I know where `flutter` is, rather than tell them to run it, I can give a button that just does it for them, so anything I can do to make sure I know where `flutter` is seems worthwhile :-)

> You might want to consider looking at ancestor folders to see if the directory is part of the Flutter SDK, for example if the user opens $FLUTTER_ROOT/examples/flutter_gallery

Sounds like a good idea :-)

**Comment by DanTup** [comment]
> It looks like either the `flutter:` or sky_engine: entries would work, after removing a suffix.

Is anyone able to confirm what this line looks like for Mac/Linux? On Windows it's:

> flutter:file:///M:/Coding/Applications/flutter/packages/flutter/lib/

I need to manipulate that a little for Windows (we want `M:\Coding\Applications\flutter`) so I need to make sure I still end up with the correct thing on Linux/Mac.

**Comment by DanTup** [comment]
FWIW, the path in the .idea file is a bit mangled on Windows so I'm gonna skip it for now (since `flutter create` already resulted in a `.packages` file.

```xml
<root url="file://M:\Coding\Applications\flutter&#x2F;bin&#x2F;cache&#x2F;dart-sdk/lib/async" />
```

**Comment by pq** [comment]
Just jumping in here, @DanTup : do you just want a sample `.packages` file on the mac?

**Comment by DanTup** [comment]
@pq Yep, that's perfect. I think it'll work as expected in the version I just shipped :)

Well, except for the relative path.. I didn't consider that. I might extend it to support that in future.

**Comment by DanTup** [comment]
VS Code is currently looking in the `.packages` file and also on `PATH` for the SDK. I think have any strong wish for this so unless we think there may be other tools that don't want to look in those places, probably we can close this?
