### ISSUE TITLE
Just run pub get it! it worked for me since I copy pasted the code from elsewhere and forgot to do a pub get. Rookie mistake

### ISSUE THREAD

**Issue by Ankjha12** [flutter/flutter#100954]
Just run pub get it! it worked for me since I copy pasted the code from elsewhere and forgot to do a pub get. Rookie mistake

_Originally posted by @Achudh in https://github.com/flutter/flutter/issues/18257#issuecomment-858540632_

I just Run all the Commands for importing the intl.dart file but it always throws an error while importing i added it in dependencies also installed it from the command but nothing happen it always throws error while importing.

**Comment by darshankawar** [comment]
@Ankjha12 
Please don't open issues using comments from others. That doesn't give us any idea as what exactly the issue could be.
Please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with.
Closing for now, as there's not much details provided.

**Comment by Achudh** [comment]
> Just run pub get it! it worked for me since I copy pasted the code from elsewhere and forgot to do a pub get. Rookie mistake
> 
> 
> 
> _Originally posted by @Achudh in https://github.com/flutter/flutter/issues/18257#issuecomment-858540632_
> 
> 
> 
> I just Run all the Commands for importing the intl.dart file but it always throws an error while importing i added it in dependencies also installed it from the command but nothing happen it always throws error while importing. 

Can you brief your steps of what you did ?
