### ISSUE TITLE
Error submitting command buffer: Invalid Resource (00000009:kIOAccelCommandBufferCallbackErrorInvalidResource)

### ISSUE THREAD

**Issue by ideateam** [flutter/flutter#101039]
I use it to save image ,but It sometimes works,sometimes not 
screenshot: ^1.2.3

  ```
Future resizeImageWithUint8ListData(Uint8List data,
      {required int width, required int height}) async {
    final codec = await skia.instantiateImageCodec(data,
        targetWidth: width, targetHeight: height);
    final frame = await codec.getNextFrame();
    skia.Image img = frame.image;
    
    var imgData = await img.toByteData(format: ui.ImageByteFormat.png);
    Uint8List? finalImage = imgData?.buffer.asUint8List();
    String fName = '${DateTime.now().microsecondsSinceEpoch}.png';
    _saveFile(fName, finalImage!);
  }

```
it  run cause this problem

`Error submitting command buffer: Invalid Resource (00000009:kIOAccelCommandBufferCallbackErrorInvalidResource)`

**Comment by darshankawar** [comment]
> screenshot: ^1.2.3

This is a third party plugin. Using it if you are getting error, then please report it in dedicated repo.

Also, its not clear what exactly are you trying to do, so please provide `flutter doctor -v`, clear and complete runnable code sample with expected  vs actual result.

Also for future reference, when you open an issue, please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with.
