### ISSUE TITLE
API is not valid Please API set valid 

### ISSUE THREAD

**Issue by DanishGujjar91** [flutter/flutter#101115]
Exception has occurred.
FirebaseAuthException ([firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ API key not valid. Please pass a valid API key. ])

**Comment by darshankawar** [comment]
@DanishGujjar91 
As the exception indicates, the api key you are trying to pass may not be valid. The tool detects it and throws the correct error. You'll need to check if the api key is valid before you use it.
Also, since this is firebase related issue, you'll need to raise it in dedicated repo. Closing from here.

https://github.com/firebase/flutterfire/issues
