### ISSUE TITLE
in my app when I run 'release apk' , UI is distorted in second page of the application

### ISSUE THREAD

**Issue by olisaemekaejiofor** [flutter/flutter#101135]
in my app when I run 'release apk' , UI is distorted in second page of the application

_Originally posted by @vendz in https://github.com/flutter/flutter/issues/20342#issuecomment-844141370_

**Comment by darshankawar** [comment]
@olisaemekaejiofor 
Please don't open issues using issue comment from other linked issues. Please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with.
I am going ahead and closing this as currently it is not actionable as no details are provided.
