### ISSUE TITLE
Support XCUITest for running integration tests on iOS devices

### ISSUE THREAD

**Issue by mofogasy** [flutter/flutter#101278]
## Use case
According to the documentation (https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing), an `XCTest` needs to be created for running Flutter integration tests on iOS devices. However, some test infrastructure providers such as BrowserStack don't offer an API for running `XCTest` suites.
This makes it impossible for running Flutter integration tests on iOS devices on those platforms.

## Proposal
Please consider adding support for `XCUITest` for iOS device testing.

**Comment by mofogasy** [comment]
Related to https://github.com/flutter/flutter/issues/65217

**Comment by jmagman** [comment]
`integration_test` and `XCTest` are for unit/integration testing, you can mock out different layers of your app and interact with the classes and state directly.  `XCUITest` is black-box testing that only allows you to interact with an app as a user would via accessibility (pressing buttons, typing text, confirming something is on the screen).  You can easily create `XCUITest` black box tests for your Flutter app the same way you can with any iOS or macOS app.

Examples: 
https://github.com/flutter/flutter/blob/7428ab66b4e79b695ffc03a6e15a2d18b019aa7f/dev/integration_tests/ios_host_app/FlutterUITests/FlutterUITests.m
https://github.com/flutter/plugins/blob/main/packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromLimitedGalleryUITests.m
https://github.com/flutter/plugins/blob/4ebfcb53b93144cbe4a7e848c992fb394a697641/packages/video_player/video_player_avfoundation/example/ios/RunnerUITests/VideoPlayerUITests.m
https://github.com/flutter/plugins/blob/411f09e3d8b13cb51eb14d2e05bab8583622dcaa/packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerUITests/FLTWebViewUITests.m

We could add some documentation for this somewhere, but not in `integration_test` since that would never be appropriate for black-box testing.

**Comment by mofogasy** [comment]
Thank you @jmagman for your reply and the example links you provided. Probably my initial explanation was not very clear. What we would like to achieve is to use our existing Flutter integration tests and run them on real iOS devices, instead of writing XCUITests directly.

### Example
```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('some test', (WidgetTester tester) async {
    runApp(const MyApp());

    tester.tap(...); // interact with the app

    expect(find.byType(...), findsOneWidget);  // some expectation
  });
}
```

With `flutter drive` and `flutter test` we are able to run these tests on iOS simulator and Android emulator respectively.

We were able to set up and run **the same** integration tests on real Android devices by following the documentation: https://github.com/flutter/flutter/tree/master/packages/integration_test#android-device-testing

For running Flutter integration tests on real iOS devices, the documentation (https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing) states to create an `XCTest` containing only the following lines of code:
```
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```
This works fine on test infrastructure platforms like Firebase Test Lab which support `XCTest`. On other platforms like BrowserStack, however, this approach does not work, because only `XCUITest` are supported.

### Proposal
I think what we need is some `INTEGRATION_TEST_IOS_RUNNER` for `XCUITest`.

Thanks for your support,

Matthias

**Comment by jmagman** [comment]
Thank for the follow-up, so to recap you want a framework that maps the dart API to `XCUIApplication` interactions, which are really running as XCUITests and not as dart tests running in the VM where the results are only communicated back to the native test tooling.
FYI this is how it works now:
https://github.com/flutter/flutter/blob/88327e3b72a5c4e45c71c816dd4d44ba0a5163c2/packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m#L27

**Comment by mofogasy** [comment]
Thank you @jmagman for your reply. Actually what I had in mind was an additional test runner that could be invoked from within an `XCUITest`. From my understanding, the integration tests would still be run in the VM as dart tests, so no sort of mapping would be necessary. The test runner just acts as "bridge" between dart tests and native test tooling to communicate back the test results.
But I am not an iOS developer, so I don't know if this is technically possible and might be mistaken in my assumptions.
Anyway, thank you very much for your help, it's highly appreciated!

**Comment by jmagman** [comment]
> The test runner just acts as "bridge" between dart tests and native test tooling to communicate back the test results.

Hm I don't think that would work with `XCUITest`, the app is a total black box so you can't access any internal bits of the app, like the messaging that would need to happen between the native test and the dart code.  You only get "this is an app, it has buttons and text fields, you can tap and swipe on them".

I suggest writing your `XCUITest`s with this black-box in mind, otherwise use `XCTests` if you need to access anything other than the pixels on the device.

> What we would like to achieve is to use our existing Flutter integration tests and run them on real iOS devices, instead of writing XCUITests directly.

Reading this again, there's no reason you can't run `XCTests` with `INTEGRATION_TEST_IOS_RUNNER` on real devices.  That doesn't have anything to do with `XCUITest`, so maybe that's the source of the confusion?  I just did so on a physical iPhone in the example app:

```
$ cd flutter/packages/integration_test/example
$ flutter build ios --config-only integration_test/extended_test.dart
$ open ios/Runner.xcworkspace
```
Then set a signing team for `Runner` and `RunnerTest`, I targeted the iPhone, and the tests ran and passed on the phone.
![Screen Shot 2022-04-07 at 1 14 11 PM](https://user-images.githubusercontent.com/682784/162288320-8e1f1f97-4dff-4abc-8c5f-173006f23f47.png)

**Comment by mofogasy** [comment]
Thank you @jmagman for your reply. Yes, you can run the integration tests as `XCTests` on real devices. Unfortunately, not all test infrastructure providers support running `XCTests` on their devices.
As you explained, it doesn't seem to be technically possible to make Flutter integration tests work with `XCUITest` the way we would require it.
So I'll close this issue, hoping that `XCTest` will be supported by our test infrastructure provider soon.
Thanks again for your help

**Comment by jmagman** [comment]
Gotcha.  Then you'll have to write `XCUITests` tests explicitly against your app without relying on the dart side doing any work.

If you wanted to be too clever you could have your "tests" run in your app as a different endpoint and display something in the UI that says whether they passed or failed.  Then use `XCUITests` to read that result.  I don't think it's a great idea, but may be a workaround.
