### ISSUE TITLE
[Fonts] Icon request: network_wifi_[X]_bar

### ISSUE THREAD

**Issue by FabrizioBilleciUNICT** [flutter/flutter#101299]
Hi
I've noticed some icons are missing in the current Flutter codebase. 
In my app I need to show a Wifis' list with the power/closeness specified by ad icon, as the OS does.

Although I should be able to set the desired icons, I'm here to notify.
Icons not present:
- signal_wifi_1_bar
- signal_wifi_2_bar
- signal_wifi_3_bar

While 0 (min) and 4 (max) are present.

I've tried to use the web's code point but they point to other icons.
I.e.: Network Wifi 3 Bar in [Google Fonts](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Anetwork_wifi_3_bar%3A) points to the printer icon in the Flutter code.

Can I help in any way? 
Thanks.

**Comment by danagbemava-nc** [comment]
Hi @FabrizioBilleciUNICT, thanks for the report. We're trying to consolidate all the missing icons into one issue so that it's easier to track. If you do find any more missing icons, kindly leave a comment in https://github.com/flutter/flutter/issues/99973. 

> I've tried to use the web's code point but they point to other icons.
I.e.: Network Wifi 3 Bar in [Google Fonts](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Anetwork_wifi_3_bar%3A) points to the printer icon in the Flutter code.

See https://github.com/flutter/flutter/issues/75633 for why this may not be a good idea.

Closing from here as duplicate. 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @FabrizioBilleciUNICT, see https://github.com/flutter/flutter/issues/99973#issuecomment-1088400026
