### ISSUE TITLE
[autosubmit]Cannot get actual author association

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#101394]
Currently, when we query for the author association, the value we got is not the real one if the author set himself/herself as private.
For example, here godofredo should be the OWNER of the flutter/cocoon, but since he set to be private, the author association we got for him is shown as CONTRIBUTOR.
The same error happens to other repo members.
![Screen Shot 2022-04-05 at 4 09 08 PM](https://user-images.githubusercontent.com/98613535/161865561-a18fbf8b-5ff8-4825-ac44-52a2fe674f10.png)

Since we currently use github app token instead of OAuth token, we are wondering if this issue is caused by the app token not having sufficient permissions.

**Comment by keyonghan** [comment]
@godofredoc Do you have any insight re the token issue here? [`keyonghan`](https://github.com/orgs/flutter/people?query=keyong) "incorrectly" returns as `CONTRIBUTOR` due to `Private` setting, whereas [`jmagman`](https://github.com/orgs/flutter/people?query=jmagman) returns as `Member` due to `Public` setting. Sounds some permission scope issue with the current token, which follows the same way as in `app_dart` by [authenticating as a GitHub App](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-a-github-app).

@dnfield Do you still remember how the `GitHubPRToken` was generated? It was first implemented [here](https://github.com/flutter/cocoon/blob/751acd8ddbcc6a07b85a476b1836a6a8de2a2df0/app_dart/lib/src/datastore/cocoon_config.dart#L19). Seems we are still using this token to authenticate GraphQL client, which returns the correct `author_association`.

**Comment by godofredoc** [comment]
Can you please point me to the location where a token is being used? this is a github application and it should be using oauth.

**Comment by keyonghan** [comment]
This is where the auto submit bot creates the [token](https://cs.opensource.google/flutter/cocoon/+/main:auto_submit/lib/service/config.dart;l=78), and it is referenced https://cs.opensource.google/flutter/cocoon/+/main:auto_submit/lib/requests/check_pull_request.dart;l=108-109. Both the github Rest API and GraphQL returns the `contributor` if marked as `private`.

However, the token used in [app_dart](https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/config.dart;l=157) returns the correct author_association, which is currently used in our check pull request merge logic.

**Comment by godofredoc** [comment]
This is an oauth token using the application credentials. You can take a look at the github docs to see if there is a github app permission that will impact this.

**Comment by dnfield** [comment]
The token was created by me when I was first working on this. I believe I selected repo:admin but I can't recall exactly. 

You likely need to have a token with higher priviledges.

**Comment by keyonghan** [comment]
this is fixed by granting organization - member read only permission (b/228371589)
