### ISSUE TITLE
Anything that uses matrix getScaleX and getScaleY is broken 

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10144]

**Comment by apwilson** [comment]
@abarth

**Comment by abarth** [comment]
When we pick a buffer size to raster a PictureLayer into, we use getScaleX and getScaleY on the SkMatrix for the ctm.  That works fine unless the matrix doesn't have any perspective.  If the matrix does have perspective, we need to divide by the perspective components to get reasonable values.  (Today, we get astronomically large values that cause us to allocate a huge buffer.)

When there is perspective in the matrix, there is no single scale value that will cause all the pixels in the picture to line up with the screen pixels because the pixels closer in the Z directly will be larger on screen.  What we probably want to do something simple like take the center of the bounding box of the picture and use the scale at that location.

The other tricky aspect is if the matrix is changing (e.g., if the picture is rotating along the Y axis), we might get a different scale for every frame of the animation.  Given that we're not going to get the scale perfectly anyway, we might want to have some fuzzy threshold for matching in the cache before we re-raster at a new scale.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
I am fixing this by decomposing a non-degenerate transformation matrix into the sequence of operations that created it (translation, scale, shear, perspective, rotation). We can then safely pick the scale from that decomposition. If case the matrix is singular, we can just bail and not consider that entry for rasterization.

From the ticket, it is not clear if any component other than the raster cache is affected by this use of the scale from the matrix. @apwilson, @abarth: By "Anything", you just meant the raster cache correct?

With regards to the matrix changing, we only care about the scale (in the decomposition). So we just do the same decomposition on the other matrix and check.

Does this plan of action sound right?

**Comment by abarth** [comment]
That will work close to the origin, but if we're far from the origin, the rotation and other components of the matrix can have a big effect on the ratio between a rasterized pixel and a screen pixel.  To get an accurate answer, we need to consider what rect inside the transformed coordinate system is being rasterized.

If you want to use the decomposition approach, you could concatenate a transform that moved the rect being rasterized to be centered at the origin.  Then the scale component would give you something reasonable.

**Comment by chinmaygarde** [comment]
> the rotation and other components of the matrix can have a big effect on the ratio between a rasterized pixel and a screen pixel.

That is what the decomposition is meant to isolate (shear, rotation, etc.) and eliminate. You are right that we could do a better job in detecting the case where the rect within the transformed coordinate system places it in a spot where we could get away with rasterizing at a lower scale, but that is an optimization. We should at least never blindly decided the scale based on the 1st and 5th items in the matrix like we do now.

**Comment by chinmaygarde** [comment]
@Hixie, this is not Fuchsia specific. We can keep it in "Customer Blockers".

**Comment by Hixie** [comment]
"Customer Blockers: Fuchsia" just means that the reason we are looking at fixing this soon is because it is blocking fuchsia. If it's not blocking a customer, then we'd have to find another reason to care about it in may/june. :-)

**Comment by chinmaygarde** [comment]
Update: https://github.com/flutter/engine/pull/3717 addresses this issue. Unfortunately, I am still dealing with the edge cases.

**Comment by chinmaygarde** [comment]
The fix for this has landed in https://github.com/flutter/engine/pull/3717. There are some edge cases that are still not handled. A description of these edge cases and a test bench is described in https://github.com/flutter/flutter/issues/10513.
