### ISSUE TITLE
Allow Dismissible widget to slide and shrink(resize) before awaiting confirmDismiss callback

### ISSUE THREAD

**Issue by petermusembi69** [flutter/flutter#101490]
## Use case

"What probably makes sense if for us to have a new callback that fires just before we start shrinking, and that callback can return true or false based on whether it wants the dismissible to shrink or not."

_Originally posted by @Hixie in https://github.com/flutter/flutter/issues/11825#issuecomment-325819861_

## Proposal

I have this analogy that having the dismissible widget shrink before awaiting the confirmDismiss callback would better communicate that the item has been deleted and the action can be later undone or not.

If undo is selected, the dismissible widget would reverse the shrink action for the content and not the background, similar to how Gmail does it.

https://user-images.githubusercontent.com/29660093/162162204-7798976e-9881-4c77-8c25-a496f32e671b.mp4

https://user-images.githubusercontent.com/29660093/162162212-6e34d260-3eae-4c63-82d3-e9cc4d57f7cb.mp4

**Comment by darshankawar** [comment]
Looks like a valid proposal to me. Labeling.

**Comment by goderbauer** [comment]
cc @nate-thegrate

**Comment by nate-thegrate** [comment]
I believe this behavior can be achieved by using [**onDismissed**](https://main-api.flutter.dev/flutter/widgets/Dismissible/onDismissed.html) instead of [**confirmDismiss**](https://main-api.flutter.dev/flutter/widgets/Dismissible/confirmDismiss.html), and setting up the snack bar's "undo" button to add the item back in.

@petermusembi69 in my opinion this is working as intended, but let me know if you disagree!
