### ISSUE TITLE
Type cast issue in image_picker method_channel_image_picker.dart

### ISSUE THREAD

**Issue by neelansh-creatorstack** [flutter/flutter#101670]
Facing an issue while trying to pick a video.
Public Crash logs along with the device details here: https://sentry.io/share/issue/eb0617d1455447eb801d87f77c3440d7/
  
  <summary>Logs</summary>

```
type '_List<Object?>' is not a subtype of type 'String?' in type cast
```

**Comment by darshankawar** [comment]
@neelansh-creatorstack 
I would check the code implementation in `fan_submission_bottom_sheet.dart in _FanSubmissionBottomSheetState._getMediaAttachmentWidget.<fn> at line 640 within challenge_app` and see if you are properly passing / casting or not.

Most of the times, this error triggers due to incorrect casting while parsing any data. So I suggest you to check your code implementation.

**Comment by neelansh-creatorstack** [comment]
No, i haven't added any type casting from my end. In the platform channel method itself, the response expected is type casted as String. But the native method returned List<Object>. That's where the issue is popping up.

**Comment by darshankawar** [comment]
> Facing an issue while trying to pick a video.

Can you provide `flutter doctor -v`, plugin version you are using along with platform this is happening on ? (ex: Android or iOS) along with a minimal code sample or a pattern if possible that'll help to debug this further.
