### ISSUE TITLE
zlib needs to be updated to include security fix patches

### ISSUE THREAD

**Issue by aam** [flutter/flutter#101709]
In context of https://github.com/dart-lang/sdk/issues/48725 flutter seems to have its own copy of the zlib, which is different from what dart is using(which dart recently updated). Is flutter's own copy really needed, can this dependency pulled from dart sdk, automatically updated if dart sdk rolls its dependency?

* https://github.com/flutter/flutter/issues/39532 where flutter zlib was moved from source code to flutter.googlesource.com, https://github.com/flutter/engine/pull/30298 where buildroot was bumped.
* https://github.com/flutter/engine/blob/main/DEPS#L414 is where flutter engine points to flutter.googlesource.com copy of zlib
* https://github.com/dart-lang/sdk/blob/main/DEPS#L260 is where dart sdk points to chromium copy of zlib(which was updated to include security fix).

@cbracken @chinmaygarde @zanderso

**Comment by zanderso** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
Flutter has its own mirror of zlib because the `BUILD.gn` in Chromium's zlib repository is incompatible with Flutter's buildroot.

I noticed that Dart's build scripts contain some workarounds that add the configurations expected by Chromium's `zlib/BUILD.gn`.  I can do the same in Flutter's buildroot and switch Flutter's `DEPS` to use the Chromium repository.
