### ISSUE TITLE
Grid view leaves unwanted spaces between items (vertically and horizontally)

### ISSUE THREAD

**Issue by egeysn** [flutter/flutter#101889]
### Description
In my application, I set crossAxis count = 7 using GridView, but I see that it draws white lines while drawing boxes on the screen. I tried many methods but could not solve this problem.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** No white spaces between boxes

**Actual results:** Unwanted white lines

<details>
<summary> 
Code Sample
</summary>

```dart
 GridView.count(
      crossAxisCount: 7,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      padding: EdgeInsets.zero,
      children: List.generate(150, (index) {
       return Container(color:Colors.black, child: Center(child: Text("text",style:TextStyle(color: Colors.white))),);
      }),
    );
```
</details>

<details>

  <summary>Screenshots</summary>

![Screenshot_20220414-114640](https://user-images.githubusercontent.com/44908368/163349686-eecbac3e-d47b-421b-a11e-27910608eba6.jpg)

</details>

**Comment by danagbemava-nc** [comment]
Hi @egeysn, this looks like an antialiasing problem. The problem occurs because of the mapping from logical pixels to device pixels. There's an open issue for a documentation fix: https://github.com/flutter/flutter/issues/14288

More info about the problem can be found here:
https://github.com/flutter/flutter/issues/25009
https://github.com/flutter/flutter/issues/17084 
https://github.com/flutter/flutter/issues/15035

Kindly follow up in #14288 for updates. 

Closing from here as duplicate. Thank you
