### ISSUE TITLE
No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider

### ISSUE THREAD

**Issue by emphaticsite** [flutter/flutter#101892]

**Comment by darshankawar** [comment]
@emphaticsite 
When opening an issue, please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with. Please don't directly use error as issue title to open new issue.

Looking at the error you provided, you seem to be hitting https://github.com/flutter/flutter/issues/99155 and see this issue comment for solution. You'll need to be on latest master to make the fix work.

Closing for now as duplicate. If you disagree or think this issue is different than linked one, write in comments and I"ll reopen it.
