### ISSUE TITLE
Use `pubspec_overrides.yaml` in flutter/plugins

### ISSUE THREAD

**Issue by blaugold** [flutter/flutter#101817]
While working on a PR in flutter/plugins, it seemed to me like adopting `pubspec_overrides.yaml` could remove the need for some brittle manual work for wiring up dependencies for development.

`pubspec_overrides.yaml` is a new file that `pub` considers when resolving dependencies. Support for it landed in Dart SDK `2.17.0-266.0.dev` and in the Flutter master channel.

If `pubspec_overrides.yaml` exists at the root of the package for which `pub get` is executed, `dependency_overrides` in it are used to resolve packages. If `pubspec_overrides.yaml` exists in a dependency, it has no effect. Packages can be published even if a `pubspec_overrides.yaml` file exists, as opposed to if `pubspec.yaml` contains `dependency_overrides`.

One motivation for this feature were repositories like flutter/plugins, where multiple interdependent packages are developed together. `pubspec_overrides.yaml` allows you to override dependencies for development without having to change `pubspec.yaml`.

**Comment by stuartmorgan** [comment]
It sounds like this could slightly simplify the `make-deps-path-based` repo tooling command. I'm not sure what you mean by "brittle manual work" though.

**Comment by blaugold** [comment]
Ah, I missed the `make-deps-path-based` command and changed the dependencies by hand 🙈 .

> I'm not sure what you mean by "brittle manual work" though.

I meant that changing the dependencies manually is a bit tedious and if they need to be check in temporarily for CI they also have to be reverted again. Besides that, it adds some churn to the git history of the `pubspec.yaml` files.

For reference, the `flutterfire` repository has adopted the approach to override all dependencies on local packages with path dependencies, in all development environments, per default, instead of turning path dependencies on and off for individual dependencies. They have their own tooling for monorepo development called [Melos](https://pub.dev/packages/melos).

**Comment by stuartmorgan** [comment]
> Ah, I missed the `make-deps-path-based` command and changed the dependencies by hand 🙈 .

That's actually my fault; it didn't occur to me to update https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages when I added `make-deps-path-based`. I've updated the page now.

> I meant that changing the dependencies manually is a bit tedious and if they need to be check in temporarily for CI they also have to be reverted again.

That would be true of `pubspec_overrides.yaml` as well, because it's dangerous to leave CI in a state where it is testing unpublished configurations.

> Besides that, it adds some churn to the git history of the `pubspec.yaml` files.

Offhand I can't think of any case other than initial federation of a previously unfederated plugin where checking in an override is desirable though, and that's a very rare case. Can you provide examples of the churn you are talking about?

> For reference, the `flutterfire` repository has adopted the approach to override all dependencies on local packages with path dependencies, in all development environments, per default

I'm aware of that approach. I find it very dangerous—and we therefore deliberately do not use it—because it means CI is never testing what customers are actually running. In particular, it makes it trivial to make multi-package breaking changes that aren't correctly versioned.

> They have their own tooling for monorepo development called [Melos](https://pub.dev/packages/melos).

We've evaluated Melos, and didn't find that it would be viable for our development process.

**Comment by blaugold** [comment]
> Offhand I can't think of any case other than initial federation of a previously unfederated plugin where checking in an override is desirable though, and that's a very rare case. Can you provide examples of the churn you are talking about?

Another example is breaking changes in platform interfaces, though those should be rare too. My perception might be skewed because I was looking at those files a bunch of times when federated plugins were first introduced and saw those overrides.

Thanks for the explanation. With the specific development process of flutter/plugins there really does not seem to be a big 
opportunity for improvement here.

**Comment by stuartmorgan** [comment]
> Another example is breaking changes in platform interfaces, though those should be rare too.

I don't follow; why would this be the case?

**Comment by stuartmorgan** [comment]
> > Another example is breaking changes in platform interfaces
> 
> I don't follow; why would this be the case?
