### ISSUE TITLE
There is no development team setup by default in Xcode

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#10195]
When trying to setup the Developer Team team in xcode, it's confusing for a new comer. You have to setup a developer team to start with, then you do some Googling how do I do that. Instead, I would recommend adjusting `make sure development team is selected` is not explicit and could be your user account as well. But this means, in order to do that, you would have to enroll in the Apple Developer program which costs $99. So then the question is, do I have to pay $99 to be able to complete the settings to debug on iOS. I suspect not, but this is the process for either creating then selecting a development team. I would prefer to select my self, and provide alternate directions for teams, or delegate to the Apple guides. 

## Steps to Reproduce
1. create plugin
2. cd into example
3. run `flutter build ios`
4. Follow directions at the end of the execution. 

![screen shot 2017-05-18 at 9 42 15 pm](https://cloud.githubusercontent.com/assets/1326504/26233582/4bcdd25e-3c13-11e7-9b6d-f249ad970ada.png)

## Logs

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision d94943a9ac (3 hours ago), 2017-05-18 18:47:57 -0700
    • Engine revision 82815836eb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • None
```

**Comment by branflake2267** [comment]
Here is the error in XCode, related to selecting my account. I'm not enrolled yet. 

![screen shot 2017-05-18 at 9 59 25 pm](https://cloud.githubusercontent.com/assets/1326504/26233871/57c15f02-3c15-11e7-9a51-822fa0358d11.png)

**Comment by eseidelGoogle** [comment]
@xster has been working on auto-provisioning recently.

**Comment by xster** [comment]
Hi,

There's indeed a non-trivial amount of initial busywork required for developers who has never developed any iOS software and/or doesn't have an Apple developer account and/or is using a physical device never used for testing. That's the area our current automated flows and documentation is lacking the most as well (#10135, #7839).

The semi-good news is that all of these requirements from Apple only applies to running physical phones so you can test now without doing any of this on a simulator (see the simulator section in https://flutter.io/setup-macos/#ios-setup).

For testing on a physical device, you do unfortunately need to go through the steps of creating an Apple developer account, register the device you want to use for testing's UDID with the account, download the certificates that would be generated for you via Xcode first. We'll do a better job of documenting it with less jargon on the website and in the command line tools. 

Regarding your membership program question, you do need to purchase the Apple membership to be able to ship anything either to the App Store or in any packaged way. Though since late 2015, Apple did allow testing on a single physical device for development purposes (looking at your screenshot, you're halfway through that process. You're missing the part where you need to go to https://developer.apple.com/account/ios/certificate/ and register the device you want to use. We'll document that better). Although I haven't tested that mechanism myself yet.

**Comment by branflake2267** [comment]
Thanks for the info. That helps.

**Comment by xster** [comment]
Going to dupe this into #10446 for concrete additions to the documentation.

In your case, the good news is that you're already 99% of the way there. The free account is totally a thing and all you got to do is plug in a phone and click try again in your screenshot. 

You'll have to trust the new certificate on your phone via Settings > General > Device Management. Also you might get an error if someone already registered an app with the ID 'com.yourcompany.myplugin14Example'
