### ISSUE TITLE
[webview_flutter][ios]: proposal to return JSON string instead of message.body for `stringWithFormat` for javascript channel

### ISSUE THREAD

**Issue by gdier** [flutter/flutter#102145]
Our javascript code using map for message body

for example: 
```
{
    data = 1;
    type = "global";
}
```

then JavascriptChannel received string like this:

```
"{
    data = 1;
    type = \"global\";
}"
```

It is not a valid JSON string for dart to unserialize. So I read the code of plugin and found the following code here -> https://github.com/flutter/plugins/blob/webview_flutter-v3.0.2/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/JavaScriptChannelHandler.m#L31

```objc
  NSDictionary *arguments = @{
    @"channel" : _javaScriptChannelName,
    @"message" : [NSString stringWithFormat:@"%@", message.body]
  };
```

stringWithFormat returns message.body.description but not a JSON string.
For more flexible, maybe using JSON serialize is better? Users may use  jsonDecode convert back to Map object.

best wishes

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as a proposal to change the value returned by `stringWithFormat` from `message.body` to JSON string.

**Comment by stuartmorgan** [comment]
This would be a breaking change. There's also no way we could do JSON encoding any more easily or efficiently than the plugin client (since the channels are running in the web context), so there's no advantage to us forcing a particular encoding scheme.

If your use case requires JSON strings, you should just return a `JSON.stringify()`'d object, instead of the object itself.
