### ISSUE TITLE
[image_picker_windows] The Windows implementation of the image_picker should support ImageSource.camera.

### ISSUE THREAD

**Issue by azchohfi** [flutter/flutter#102115]
## Use case
The existing PR that is adding Windows support for the image_picker (https://github.com/flutter/plugins/pull/4863) only supports `ImageSource.gallery`, throwing `UnimplementedError` if `ImageSource.camera` is used.

## Proposal
A future PR should add support for `ImageSource.camera`, leveraging the existing camera_windows package.

**Comment by ramanjitsingh-hub** [comment]
would like to work on this, any tips to I can add the support for `ImageSource.gallery`

**Comment by azchohfi** [comment]
There are multiple ways that we can solve this issue.
Unfortunately, Windows 10 doesn't support asking the native camera app to take a picture and return it, like Android does, so we would need to implement something probably using the camera_windows plugin, in a new widget, something like this https://docs.flutter.dev/cookbook/plugins/picture-using-camera, and then navigate to it and get the results back. It should look similar to what we have on other platforms today, as it should map all the properties that exist today in the image_picker plugin, like supporting multiple cameras, etc.

**Comment by ramanjitsingh-hub** [comment]
So basically we have to implement `ImageSource.camera`  in the getImage function. And for implementing it we have to do it the same way as it is mentioned in https://docs.flutter.dev/cookbook/plugins/picture-using-camera. Please tell me if I got right.

**Comment by azchohfi** [comment]
Pretty much. @stuartmorgan, would you do it in a different way?

**Comment by stuartmorgan** [comment]
Having thought about this some more, I'm not sure we should actually implement this (at least not directly):
- We generally focus our plugins on providing access to platform functionality, without wrapping UI, since plugin clients should generally control any non-system-provided UI.
- Adding a direct dependency would mean anyone using `image_picker` on Windows just to use the gallery source would get thousands of lines of unnecessary camera code built into their application.

I can see two options that would provide more flexibility:
1. Just leave it unimplemented, reflecting the lack of OS support for it.
2. Add a field called something like `cameraImplementation` or `cameraDelegate` to `ImagePickerWindows`, which would be an object implementing an interface we define there (a subset of `ImagePickerPlatform methods`), which, when set, would be called for `camera` source calls to `ImagePickerWindows`.

The main advantage of 2 is that it would handle indirect uses (e.g., I use a package that internally uses `image_picker`, and I want it to work on Windows) as well as direct uses.

Either way we would document it in the README, and encourage the community to create packages providing this functionality on Windows. People could pick among different options depending on what UI they preferred.

**Comment by cbracken** [comment]
Generally agree on this approach. I think approach 2 with a default of some form of null implementation seems reasonable.
