### ISSUE TITLE
flutter mobile can use log in with google_signin facebook_signin.... . so how about telegram_signin? Will flutter team create plugin for sign in or register with telegram? Thanks. 

### ISSUE THREAD

**Issue by Seu07** [flutter/flutter#102124]

**Comment by darshankawar** [comment]
@Seu07 
Please check on [pub.dev](https://pub.dev) if there's already a community plugin that offers this feature. As far as Flutter team creating a plugin is concerned, I don't think that is a feasible request because it isn't a standard login like Google, Facebook or Apple. So I am going ahead and closing this as not feasible.  You can raise this question on flutter reddit or stackoverflow to get existing solution if any.
