### ISSUE TITLE
[Proposal]Make rust the default language for Linux

### ISSUE THREAD

**Issue by lattice0** [flutter/flutter#102348]
## Proposal

GTK is very unsafe, and you have to remember to free lots of stuff, not to mention verify nullity of pointers. Would be much nicer to use a rust gtk binding for the linux version, much less crashes and memory vulnerabilities

**Comment by maheshmnj** [comment]
Hi @lattice0, Thanks for filing the issue. Leaving this issue open for the team to decide.

**Comment by gspencergoog** [comment]
We use the C bindings for GTK because it allows us to connect directly to the GTK library APIs without having a wrapper interface.  It gives us maximum flexibility for portability as well.

There is a Rust embedder implementation called [NativeShell](https://github.com/nativeshell/nativeshell) that can free you (pun intended :-) ) from having to do so much in the way of memory management.

Since we want our embedder implementation to be as tiny as possible, and bringing in Rust would make it ever so slightly larger, and significantly increase the complexity of our build toolchain. It is unlikely that would pursue this request at this time, so I'm going to close this. 
(Desktop Triage)

**Comment by lattice0** [comment]
@gspencergoog understood and agree, bringing rust would make building harder (more stuff to install, etc).

Could you consider a more high level gtk C++ binding then? This one is too error prone, having to free every single thing and etc, and also having to manually cast voids to other stuff. Using extremely modern C++ features it could be made safer and with less probability of memory leaks and undefined behavior. 

I had to write an external texture example and it was really painful and crashy. 

By the way, thanks!

**Comment by stuartmorgan** [comment]
> Could you consider a more high level gtk C++ binding then?

Anyone could write a re-usable adapter layer to C++ if there's sufficient community interest in this; there's no reason it necessarily needs to be shipped with `Flutter'.

The current API was specifically designed to be consistent with GTK code, as it's a GTK-based embedder.

> This one is too error prone, having to free every single thing

This sounds likely to have been an issue in the way you were using the API; correct use of `g_autoptr` should mean you are rarely if ever manually freeing things.
