### ISSUE TITLE
Unable to reload the web app in release mode using browser button

### ISSUE THREAD

**Issue by vishalvishvakarma1111** [flutter/flutter#102352]
Developing an app on web and mobile  which working fine but getting 404 error when reloading the web page on browser and 
also to encrypt the query parameter of web url just like php laravel

**Comment by darshankawar** [comment]
@vishalvishvakarma1111 
Its not clear what your issue is as you haven't provided any error logs or code sample to debug further. When you open an issue, use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with.
Closing this as it is not actionable currently due to lack of details.

**Comment by vishalvishvakarma1111** [comment]
Issue is very clear and i dont need to provide any error log 
if you want to reproduce it just follow simple steps 
create a project with two ,three screens and perform navigation routing with param (i am using getx named route)
after going to 2nd page just hit reload button of browser you will see it shows 404 error (try this in release mode ,not in debug mode )
