### ISSUE TITLE
[autosubmit] Latter PRs are ignored when earlier PR merge hit exception

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102317]
Existing logics is (https://github.com/flutter/cocoon/blob/main/auto_submit/lib/requests/check_pull_request.dart):
1) Check the PR list in the pubsub queue
2) Collect mergeable PRs and acknowledge the PR message from pubsub
3) Iterate the above mergeable PR list, and merge accordingly.

If any merge hit exception, the whole loop terminates and we are losing context of these PRs (as we have acknowledged them).

We need to either handle the exception appropriately, or change the logic to acknowledge PR only when successfully merging the PR.

**Comment by codebird** [comment]
Is it possible for an external contributor to work on this? Or I don't tire myself?

**Comment by codebird** [comment]
@keyonghan @CaseyHillers I think this was fixed in this pull request:

https://github.com/flutter/cocoon/pull/1802

Precisely here:

https://github.com/flutter/cocoon/pull/1802/files#diff-d83157127181dc0f91c081038db48158dc735e35c5479d06a4afbf4a82eb32eeL144

and here:

https://github.com/flutter/cocoon/pull/1802/files#diff-d83157127181dc0f91c081038db48158dc735e35c5479d06a4afbf4a82eb32eeR87

**Comment by CaseyHillers** [comment]
I think it's still open (i've noticed the issue still happening).

In https://cs.opensource.google/flutter/cocoon/+/main:auto_submit/lib/requests/check_pull_request.dart;l=122 we need to a try/catch to ensure errors don't break the merge loop.

We do something similar in the older bot in https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart;l=44

**Comment by codebird** [comment]
Thanks guys. This needs closing
