### ISSUE TITLE
Unable to run in iOS after my flutter upgrade & its in a new project

### ISSUE THREAD

**Issue by MuthuHere** [flutter/flutter#102462]
In android and web working fine. But when i am trying to run in simulator I am getting this error.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/18752533/164972759-8ef158a6-8cf8-476f-b184-ad275e61b502.png">

```flutter doctor```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!

Xcode Version:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/18752533/164972957-01612468-e6e1-4db5-b959-fce7f76e62d3.png">

**Comment by darshankawar** [comment]
@MuthuHere 
You are on old version of the framework. Current one is 2.10.5. So I suggest you to upgrade to latest so that other tools such as XCode which you are using the latest version I presume would be able to support the framework properly.
Also, see [this](https://github.com/flutter/flutter/issues/102478#issuecomment-1108119864) similar issue and solution and check if it works for you.
