### ISSUE TITLE
Is it possible that enumerates the currently available FontFamilys

### ISSUE THREAD

**Issue by youmu129** [flutter/flutter#102496]
## Use case

I want to make users can choose fonts by themselves. But i didn't find any way to enumerate fonts available in flutter engine.

## Proposal

Will a feature to do it? Or i should do it myself in native plugin

**Comment by maheshmnj** [comment]
Hi @youmu129, Thanks for filing the issue. Flutter doesn't provide any such list of available fonts, However, you can always  maintain the list of font names since they are basically a  List<String> and then apply the desired font globally as below


```dart
 Theme.of(context).textTheme.apply(
          fontFamily: 'myfontfamily',
        );
``` 

Closing as this is neither  a bug nor a feature request.
