### ISSUE TITLE
[in_app_purchase] any plans for web implementation?

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#102452]
Given this package https://pub.dev/packages/in_app_purchase are there any plans for Web support?

**Comment by darshankawar** [comment]
Treating this as a proposal for web support.

**Comment by stuartmorgan** [comment]
@giorgio79 Can you clarify what you expect web support to do, exactly? `in_app_purchase` wraps the platform-provided store APIs. What store do you envision a web implementation wrapping?

**Comment by giorgio79** [comment]
It would be nice to use the Google Pay feature on the web as that seems to be available for Android and web as well
https://developers.google.com/pay/api/web/overview
Or that should be a separate pub package?

**Comment by yjbanov** [comment]
The web doesn't have in app purchases. You can use any payment provider you like. Since we cannot support all providers in the work in the plugin, I suggest that this should be a pub package that abstracts over other payment systems.

**Comment by stuartmorgan** [comment]
Since it seems like this is something we would actively not take a PR for (given that there's no clear provider option), I'm just going to close it. We generally don't leave issues open any more for packages that we definitely wouldn't own.

> I suggest that this should be a pub package that abstracts over other payment systems.

For anyone interested in making a third-party implementation, the federated plugin design means that it's possible for someone to use `in_app_purchase` as the abstraction, and make an unendorsed provider-specific implementation package that clients could add to their project.
