### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by HG9558** [flutter/flutter#102557]
The project does not work, please help me, thank you

![image](https://user-images.githubusercontent.com/22909991/165248933-94eee6fd-6071-4059-80e5-63987e118beb.png)

**Comment by danagbemava-nc** [comment]
Hi @HG9558, please provide the full log of `flutter run -v` or `flutter build apk -v` depending on which command you're experiencing this issue with. The output will likely be huge, so kindly put it into a .txt file and attach it here. Please provide the output of `flutter doctor -v` as well.

Also, your issue appears to be coming from the `tencent_im_sdk`, you may need to upgrade to the latest version and try again.

Thank you

**Comment by HG9558** [comment]
Hi, @danagbemava-nc  Thank you very much for your help
![image](https://user-images.githubusercontent.com/22909991/165301938-bc25d4ab-813c-4028-aa03-dc2864dc75da.png)

There will be compatibility errors after upgrading the version
![image](https://user-images.githubusercontent.com/22909991/165302709-d2a777b2-61ec-4d1c-8cb6-6e1e066d9704.png)

**Comment by danagbemava-nc** [comment]
Hi @HG9558, you'll need to update your dependencies to their latest versions. 

You can use `flutter pub outdated` to see which versions of your dependencies are out of date and the suggested command to upgrade to the latest version. 

Please refrain from posting screenshots of logs, it is always better to just copy and paste them here in properly formatted text.

**Comment by HG9558** [comment]
Hi, @danagbemava-nc  I have upgraded all dependencies to the latest version, but other errors are reported when running, the error log is in the following file, thank you very much.
[error_logs.txt](https://github.com/flutter/flutter/files/8563786/error_logs.txt)

[flutter-doctor.txt](https://github.com/flutter/flutter/files/8563799/flutter-doctor.txt)

**Comment by danagbemava-nc** [comment]
Hi @HG9558, it looks like the errors you're seeing now are due to the fact that some of your dependencies have changed the way certain methods are called. You'll need to update your code to match the new ways that those methods are used. You should be able to see the errors in your `Problems` console if you use `VSCode`/`Android Studio`. 

Alternatively, you can run `flutter analyze` in your command line and it will show where the errors are.

**Comment by HG9558** [comment]
Hi. @danagbemava-nc   When this project cannot change the method in the code, it is a collaborative development of the team. I returned the problem to the problem I encountered at the beginning. I put the error log in the following file. I need your help, thank you

[error_logs.txt](https://github.com/flutter/flutter/files/8563912/error_logs.txt)

**Comment by danagbemava-nc** [comment]
Hi @HG9558, the issue you're facing is from a third-party plugin/package which happens to be out of date. Unfortunately, there isn't anything we can do on our end since we do not have control over that plugin/package. The only thing you can do to fix it is to update your dependencies or report it to the maintainers of the plugin/package to see if they have a workaround. 

You'll need to discuss it with your team what you want to do, but the solution is to upgrade your dependencies. You cannot be using older version of your plugins in perpetuity. You'll eventually need to update.

I'm going to have to close this issue as all the issues are related to your dependencies and not related to flutter directly. 

Thank you

**Comment by HG9558** [comment]
Hi @danagbemava-nc  ok thanks a lot for your help
