### ISSUE TITLE
Can not run multiple videos in Android device.

### ISSUE THREAD

**Issue by md-siam** [flutter/flutter#102596]
## Steps to Reproduce

1. I have a dashboard where multiple videos will be played simultaneously. 
2. It works smoothly on iOS devices. 
3. But on an Android device, only one video plays at a time. If I start another video, then the previous video that was playing stops. 

## Screenshot
![ezgif com-gif-maker](https://user-images.githubusercontent.com/21225918/165368558-6315299a-cf59-4bab-aaa9-715a9b7c9d70.gif)

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@md-siam 
Please note that when you open an issue, try to use new issue template and fill out requested details so that we'll have enough details to work with.
You haven't shared a code sample so we don't know how are you rendering videos. Are you using `video_player` plugin ?

Please provide minimal code sample and `flutter doctor -v` too.

**Comment by darshankawar** [comment]
Closing this as resolved.
