### ISSUE TITLE
Taking Video Multiple times it is showing ''Could not start media Recording'' in some devices

### ISSUE THREAD

**Issue by raza7867** [flutter/flutter#102621]
When we start video recording( PickVideo through Camera) getting this message 'Could not start media Recording', The devices which we observed this issue is 'Samsung Galaxy A70s' OS 11 version and in Oreo 28, Please Suggest something to resolve this issue, Thanks in Advance.

**Comment by darshankawar** [comment]
@raza7867 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough details to work with.
Here you haven't provided any code sample, plugin version and `flutter doctor -v` and then asking to suggest a fix, which isn't possible.
Please provide above requested details to make this issue actionable.
