### ISSUE TITLE
Persistent confusion about "what can flutter do?"

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10281]
Our Gitter is a constant stream of folks appearing and asking if flutter can do X?

Commonly things like "camera" or "login" or "maps".

I think we should consider addressing this on our front page.  Currently we have:

"Platform interop and native code"

Maybe we should have:

"Lets you do anything the phone can do" or similar.  And explain about our intentional choice not to put you in a box, and how to get from Dart out to other languages.  We could also caveat here that there are some *inline* view limitations, but that there are no limitations as to what you can do above/below/beside flutter content.

Thoughts @sethladd @wmleler

**Comment by sethladd** [comment]
I'd like to chat with @mit-mit about plans here too. I have some ideas how
to make this better.

**Comment by wmleler** [comment]
I really like this idea. It emphasizes the fact that Flutter is generating native code.

We do need to be a little careful in our wording, because some things (as you mention, like inline video) are still impossible. How about saying that "your app can call out to native code, and so can access any native service". And also probably mention that they should look to see if there are any plugins that access that service.

Does it make sense that anyone wanting to access a native service should write it as a plugin?  (I guess my question is how much effort does it take to write a plugin instead of just putting in the code to access some native service). If we could encourage people to write plugins, and then submit them so that others can use and improve them, that would be the best.

**Comment by mit-mit** [comment]
I'm all for updating the flutter.io frontpage to say a bit more here.

But I don't think that will make all the questions go away; my read is that
many are really asking "does Flutter have an existing plugin for x" rather
than "can I write a plugin for x". So we need more work on the pub site
also.

**Comment by sethladd** [comment]
> So we need more work on the pub site also.

That's my instinct, too. It won't matter what we put on the homepage. We need a nice link that lists all the plugins, and THEN we link to that from the homepage :)

**Comment by sethladd** [comment]
We tweaked the language on the front page, but I think the "here's a list of all the packages (plugins) that you can use with Flutter" is a great canonical answer to this general question. I believe that request is already open, so I'm going to close this. Once we have that canonical link, we could and should add to homepage.
