### ISSUE TITLE
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.

### ISSUE THREAD

**Issue by ElsayedDev** [flutter/flutter#102820]
When I used `TextField` widget with [`flutter_portal`](https://pub.dev/packages/flutter_portal) package 

the following error occurred 
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
package:flutter/…/rendering/layer.dart:1
Failed assertion: line 2502 pos 7: 'leader._lastOffset != null'

**Comment by darshankawar** [comment]
@ElsayedDev 
Can you provide entire error log in properly formatted text ?  
Also provide `flutter doctor -v`.  If you are on stable version, according to [this](https://github.com/fzyzcjy/flutter_portal/issues/76#issuecomment-1113267786) comment, this might have been fixed in 2.13, which is beta and master. So try switching to latest beta or master and see if you still get same error or not.

`flutter channel master`
`flutter upgrade`
