### ISSUE TITLE
Default App Crashes on Relaunch

### ISSUE THREAD

**Issue by crawford-jake** [flutter/flutter#102826]
## Description
We have been experiencing crash reports on iOS 15. We have been unable to identify specifically what is going on, but believe it is related to this issue: when a user quickly reopens an app (in release mode) it crashes with no report.

## Steps to reproduce
1. Run the following commands to create a clean flutter project on the latest master branch (the same thing happens on the stable branch).
```
flutter channel master
flutter upgrade
flutter create crash_example
cd crash_example
flutter pub get
flutter run --release
```

2. Once the app builds to your physical device (running iOS 15) close the app and quickly reopen. This will cause the app to crash if you do it fast enough. It seems to work as expected if you wait at least one second. 

3. To resolve this issue close ALL background apps so the "recent apps" are empty. When you do this, the problem in step 2 does not happen. To "re-activate" the crash, open 5 to 10 apps and put them in the background.

## Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

## Example
https://user-images.githubusercontent.com/82613137/165972308-4d13783b-def6-4888-a85c-389a3042c421.MP4

**Comment by darshankawar** [comment]
@crawford-jake 
Thanks for the report. Can you run `flutter run --release -v` and see if verbose log gives you any errors ?

**Comment by crawford-jake** [comment]
@darshankawar I tried but nothing showed in the logs. I also filed a report with Apple because it is happening on all iOS 15 apps. We found in several of our packages that rely on native features, they do not initialize correctly after moving from the background to foreground several times. 

[https://developer.apple.com/forums/thread/705246](https://developer.apple.com/forums/thread/705246)

**Comment by darshankawar** [comment]
@crawford-jake 
Thanks for the update and raising the ticket in Apple forum. I actually tried the scenario on iPhone 6s running OS 15.3.1 on a sample app, but didn't see the behavior you reported.


https://user-images.githubusercontent.com/67046386/166409771-2647fa31-de5b-4a3a-806f-a6b716768014.MP4


<img width="617" alt="Screenshot 2022-05-03 at 11 21 44 AM" src="https://user-images.githubusercontent.com/67046386/166409793-dd1670aa-b2be-4e9f-a92d-0b793b1a1e00.png">

Does the crash occur consistently every time ? Is this only happening in release mode ? or in `profile` mode too ? In debug mode probably we can't replicate that since terminating the app, we can't open it again.
