### ISSUE TITLE
Several tests/benchmarks appear to be running on only every 3d commit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#102946]
I'm not sure when this started, but it looks like some number of tests are only running on every third commit. Is this behavior intentional?

<img width="967" alt="Screen Shot 2022-05-02 at 2 52 56 PM" src="https://user-images.githubusercontent.com/6343103/166333672-fc3e34ef-1d22-4420-956f-92a8481937e6.png">

**Comment by zanderso** [comment]
@CaseyHillers I'm seeing changes in the cocoon commit log related to backfilling. Is this related?

**Comment by zanderso** [comment]
This is continuing to happen. We are losing benchmark data due to this, so I am increasing the priority to P2.

**Comment by yusuf-goog** [comment]
@CaseyHillers some of these do seems fairly regularly running every 3rd time. Could this be an issue with the scheduling?

Some examples:

[Mac_arm64_android integration_test_test](https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_android%20integration_test_test)
[Linux_android gradient_dynamic_perf__e2e_summary](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20gradient_dynamic_perf__e2e_summary)
[Mac_ios flutter_view_ios__start_up](https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_view_ios__start_up)
[Mac_arm64_android hello_world_android__compile](https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_android%20hello_world_android__compile)

**Comment by CaseyHillers** [comment]
Copying from the engprod chat room:

I think the backfilling bug is because it's loading 100 last builds from Cocoon's datastore, and when we do the swap over some tasks can be stuck in yellow. But I need to set some time aside after the Flutter 3 release to look at it

I landed https://github.com/flutter/flutter/pull/103048 to revert all but one back to LUCI until I have time to investigate this more.
