### ISSUE TITLE
Create a gallery demo demonstrating iOS navigation patterns

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10304]
Have a demo that uses #9926 and #7508 to create a sample app that behaves like the iOS App Store with multiple parallel Navigator stacks. 

Potentially create a CupertinoScaffold equivalent to the UINavigationController to handle positioning, back gestures etc to make it easy to use.

**Comment by renefloor** [comment]
I just saw that the CupertinoTabBar already exists for quite some time, but didn't know that because it is missing in the widget section on the website: https://flutter.io/widgets/cupertino/
I would also be nice to have a tutorial how to best make two native looking apps, so this probably will mean switching between CupertinoScaffold and MaterialScaffold and different navigation patterns. Maybe also an overview of views which have both a material and a cupertino variant, such as switches, buttons and loading indicators.

**Comment by xster** [comment]
Hi @renefloor. Really appreciate your feedback. 

Your comment is multi-part:
- The website is a total omission. Thanks for catching. Adding now.
- Making 2 native looking apps (which I assume you mean only on a superficial UI level with most of the structure and business logic shared) will be covered in #12805. Please let me know if it addresses what you're looking for. 
- Widgets with Material and Cupertino variants are currently all in the gallery app which you can build and install at [flutter root]/examples/flutter_gallery.

**Comment by renefloor** [comment]
Yes, I think #12805 is exactly what I meant. Thanks for adding it on the website.

**Comment by xster** [comment]
Done now, but #4630 is still a big annoyance.
