### ISSUE TITLE
SingleChildScrollView height is wrong in 2.10.5

### ISSUE THREAD

**Issue by ninetowns** [flutter/flutter#103301]
after i update flutter to 2.10.5, SingleChildScrollView can't scroll to content bottom, it is right in 2.10.4

**Comment by darshankawar** [comment]
@ninetowns 
When you open a new issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Only providing a one liner issue will not help to make it actionable, so please provide a complete minimal reproducible code sample along with actual vs expected behavior.
