### ISSUE TITLE
app crash after use multidex

### ISSUE THREAD

**Issue by oeng-hok-leng** [flutter/flutter#103416]
my app got crash for both android real device and emulator when I use multitdex, 

> D/EGL_emulation( 6124): eglCreateContext: 0xec520060: maj 3 min 0 rcv 3
D/EGL_emulation( 6124): eglCreateContext: 0xec5201b0: maj 3 min 0 rcv 3
D/HostConnection( 6124): HostConnection::get() New Host Connection established 0xec5181f0, tid 6223
D/HostConnection( 6124): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 6124): eglMakeCurrent: 0xec5201b0: ver 3 0 (tinfo 0xec879c50) (first time)
D/PathProviderPlugin( 6124): Use TaskQueues.
D/HostConnection( 6124): HostConnection::get() New Host Connection established 0xec520ae0, tid 6222
D/HostConnection( 6124): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 6124): eglMakeCurrent: 0xec520060: ver 3 0 (tinfo 0xb8e24e70) (first time)
D/EGL_emulation( 6124): eglCreateContext: 0xec5212c0: maj 3 min 0 rcv 3

this is what I got when I try to open my app in the emulator.

**Comment by darshankawar** [comment]
@oeng-hok-leng 
There's not enough details to conclude why is it crashing. When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Simply providing log doesn't help much.

The log you shared doesn't seem to have any flutter related frames / entries so it's hard to know if the issue is related to Flutter at all. What's the flutter version you are on ? What's the emulator version and OS you are on ?
If you are using an older emulator and OS version, it would have some caveats using multidex, so I suggest you to ask this question on support channels like StackOverflow.
If you think this is a genuine issue in flutter, use new issue template as requested above, fill out all details so that we can address it accordingly.
