### ISSUE TITLE
Google testing status in Presubmit disappeared

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#103553]
The google testing run for https://github.com/flutter/flutter/pull/102687 seems to have disappeared from the frob ui.

**Comment by keyonghan** [comment]
This is happening again /cc @CaseyHillers

**Comment by jonahwilliams** [comment]
I could squash into a new PR but I'd rather not lose the review history

**Comment by keyonghan** [comment]
@CaseyHillers has this been resolved? Didn't see this issue recently.

**Comment by CaseyHillers** [comment]
We're still working on this. @XilaiZhang is working on migrating this to the Checks API and adding monitoring.

**Comment by Piinks** [comment]
I've noticed a lot more PRs without the Google testing check, is it currently not working? Here is one: https://github.com/flutter/flutter/pull/109817

**Comment by bernaferrari** [comment]
I think you can close this.

**Comment by CaseyHillers** [comment]
I'm marking this as fixed. For Googlers, the most common reason they couldn't find the PRs internally was they were marked in the "DELETED" state. This indicated the CI system had tested them, and after several hours of inactivity were cleaned up. I've since added those to the frontend for tracking purposes, which still allows Googlers to interact with the test results.
