### ISSUE TITLE
ScrollView.keyboardDismissBehavior doesn't unfocus the keyboard properly

### ISSUE THREAD

**Issue by Shawn-sudo** [flutter/flutter#103544]
## Steps to Reproduce

1. Put `keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag` in a `SingleChildScrollView`, which has `TextField` among the children.
2. Tap on the `TextField` to focus on it.
3. ***Dismiss the keyboard by scrolling the page***
4. Open the drawer

**Expected results:** 
When the drawer is opened, keyboard stays there

**Actual results:** 
Keyboard pops out

https://user-images.githubusercontent.com/60294318/167961451-991ad0e1-58fc-462a-9413-9eaab8521e80.mp4

**Similar Issue**
#54277: This gives the solution to dismiss the keyboard properly, and I think the proper way of dismissing it is not applied on `SingleChildScrollView`'s `.onDrag` code.

<details>
<summary>Code sample</summary>

```
    return Scaffold(
      appBar: AppBar(),
      drawer: Drawer(),
      body: SingleChildScrollView(
        keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
        child: SafeArea(
          child: Column(
            children: [
              TextFormField(),
            ],
          ),
        ),
      ),
    );
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Shawn-sudo 
Thanks for the report. Running your code sample on latest stable (3.0), I observed that when textfield is in focus, the keyboard opens as below:

<img width="328" alt="Screenshot 2022-05-12 at 6 09 42 PM" src="https://user-images.githubusercontent.com/67046386/168076901-b2606c62-d35f-40ad-b474-d62748199e7f.png">

And when we open drawer, the textfield becomes inactive as you can see in the background, it has greyed out and hence the keyboard closes.

<img width="356" alt="Screenshot 2022-05-12 at 6 09 53 PM" src="https://user-images.githubusercontent.com/67046386/168077012-0a607e08-a9cd-4398-951a-2df6220b201b.png">

which I think is an expected behavior.  What exactly should be the expected result from your end ? Does the same occur in native iOS app if you could check and confirm ?

**Comment by Shawn-sudo** [comment]
@darshankawar Oh did you scroll the page before opening the drawer? Cause it happened to me only when I 1. open the keyboard ***2. close the keyboard by scrolling the `SingleChildScrollView`*** (which has `keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag`) 3. And then open the drawer

**Comment by darshankawar** [comment]
I can't scroll using the code sample you provided. Please provide complete code sample that shows the behavior.

**Comment by Shawn-sudo** [comment]
Umm Just put `Column` under the `SingleChildScrollView` add a bunch of `SizedBox(height: 10000)` under the `Column`.

**Comment by darshankawar** [comment]
See if this issue is similar to your case https://github.com/flutter/flutter/issues/57609

**Comment by Shawn-sudo** [comment]
I think https://github.com/flutter/flutter/issues/57609 is different from what I'm talking about, but I think it would solve this issue in a broad way. Thx
