### ISSUE TITLE
Add Support for mac and ios safari extension project support with the apps projects

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#103788]
Actually i want to create safari extension browser extension with the mac and ios apps because xcode create the safari extension project with the default app project flutter create only the app project add support to select safari extension with the project or default app project

**Comment by darshankawar** [comment]
@alihassan143 
Can you elaborate on your use case by providing a practical example as why would you want to have those safari extensions to the default projects ?

**Comment by alihassan143** [comment]
Wen we create flutter default project it create the mac os project by default i want an option to be able to select an option to create mac os and ios multiplatform project in which xcode create project for the apps also for the safari browser extension in which we can create the safari extension using the project and when we build the project for deployment xcode create archive  for the ios and mac and also for the safari extension with the apps and that can be deployed in the appstore we  appstore automatically detect that project also contains the safari extension with the app and user can use extension in safari browser

**Comment by darshankawar** [comment]
@alihassan143 
I am not sure if this is a feasible proposal because per your description, you seem to be expecting the app to create lot of things which would increase the boilerplate code and add-up to performance while trying to build the created app.

I am going ahead and closing this as not a feasible option to be added to the framework. If you disagree, write in comments and I'll reopen to consider.
