### ISSUE TITLE
Flutter 3.0.0 bugs

### ISSUE THREAD

**Issue by ubaidillahSriyudi** [flutter/flutter#103796]
after upgrading to the latest version 3.0.0 then some various bugs appear in some of my projects that run well before

1. qr_code_scanner:compileRelaseKotlin ![Screenshot 2022-05-14 at 10 55 06](https://user-images.githubusercontent.com/41310314/168421920-e3c66b26-0150-4bd2-8a00-ba2307afaa6f.png)
2. Duplicate GlobalKey detected in widget tree
<img width="573" alt="  " src="https://user-images.githubusercontent.com/41310314/168421943-188da020-dba3-485d-9fca-bafca3a2e626.png">

3. warning: Operand of null-aware operation '??' has type 'String' which excludes null. 
<img width="693" alt="Screenshot 2022-05-14 at 16 48 18" src="https://user-images.githubusercontent.com/41310314/168421961-2424f1ae-30b6-49d9-9517-b0011f5d64ef.png">

i have tried some ways

1. Flutter clean then pub get again
2. delete pubspec.lockockdelete pubspec.lock
3. clean the .pub-cache
4. upgrade gradle to 7.4
5. upgrade ext.kotlin_version to '1.6.10'
6. change android -> build.gradle -> buildscript & allprojects jcenter() to mavenCentral()
7. upgrade Android Gradle Build version to the latest "classpath 'com.android.tools.build:gradle:7.1.3'"

for information flutter doctor
<img width="703" alt="Screenshot 2022-05-14 at 17 23 30" src="https://user-images.githubusercontent.com/41310314/168422020-2cf6e321-1c0a-4cbd-838e-b40b3844b20a.png">

**Comment by SebghatYusuf** [comment]
Got compilation issues of many packages for android, as it was running fine on iOS, 
for example `pay_android:compileDebugKotlin` had to downgrade back to `2.10.5` and continue developing the app.

**Comment by cedvdb** [comment]
please find a better title, issues are useful for googling and people that look at the current issues to get a glimpse on what's wrong for example before migrating to flutter 3.

**Comment by asashour** [comment]
Also, please copy the text of the errors instead of the images.

**Comment by darshankawar** [comment]
@ubaidillahSriyudi 
Warnings / errors related to third party plugins like you mentioned above `qr_code_scanner` need to be fixed in the plugin code itself.

`Duplicate GlobalKey detected in widget tree`, you'll need to fix the same in your code implementation. Check similar issues on stackoverflow for solutions.

`warning: Operand of null-aware operation '??' has type 'String' which excludes null.` check this https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings link for various solutions and possibly follow-up in https://github.com/flutter/flutter/issues/103561 for further updates.

Closing from here.

**Comment by ubaidillahSriyudi** [comment]
> Also, please copy the text of the errors instead of the images.

take a look back on the description i have include error text above the images

**Comment by ubaidillahSriyudi** [comment]
> please find a better title, issues are useful for googling and people that look at the current issues to get a glimpse on what's wrong for example before migrating to flutter 3.
> 
> "Bug" is not descriptive

explain three bug on the title would be a bad title, i have some bugs so it's better make it simple title then people can click and see more detailed bugs

**Comment by ubaidillahSriyudi** [comment]
> Also, please copy the text of the errors instead of the images.

you can copy the text error that i placed above the images

**Comment by cedvdb** [comment]
> explain three bug on the title would be a bad title
 
 Three bugs in the same ticket is a bad ticket.

**Comment by cedvdb** [comment]
I'm not here for debating but to explain to you that tickets are also used by other people to find resolutions to their issue. This is a common etiquette on every repository and even stackoverflow. This should not be treated as a support but a place where people can come and quickly find a solution to their problem and help the dev recreating issues relative to the repository in question.

If you do not agree with this philosophy let's leave it at that. I'm unsubbing here because I've more meaningful things to do.
