### ISSUE TITLE
flutter 3 upgrade resulting in error

### ISSUE THREAD

**Issue by VighneshNS2008** [flutter/flutter#103717]
hello
i was making my app in flutter
and then when i upgraded to flutter 3 it started showing this errores
`
* What went wrong:
Execution failed for task ':firebase_core:compileDebugJavaWithJavac'.
> Failed to calculate the value of task ':firebase_core:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'.
   > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /home/vighneshnausoshetye/Documents/app/electricallinefaultdetectionsystemapp/build/firebase_core/generated/ap_generated_sources/debug/out))) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@35357c52) before task ':firebase_core:compileDebugJavaWithJavac' has completed is not supported
`

**Comment by wzslr321** [comment]
Did you also upgrade your packages along with flutter? 
If so, did you try to run `flutter clean`?

**Comment by christopherfujino** [comment]
@VighneshNS2008 thank you for filing an issue. However, this issue is not actionable in its current version. You appear to have deleted the issue template when you created this issue; however, it contains instructions for providing the information that we need to triage your issue. Please refer to https://docs.flutter.dev/resources/bug-reports.

Most importantly, we need:
1. Minimal reproducible code sample
2. The output of `flutter doctor --verbose`
3. The output of the command you ran, in verbose mode
