### ISSUE TITLE
Flutter Integration Test - Facing issue trying to read PDF

### ISSUE THREAD

**Issue by D33pak0508** [flutter/flutter#103887]
Facing issue when trying to read pdf using 'pdf_render'. Getting below error

"**flutter/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.1.0/lib/src/interfaces/pdf_render.dart:3:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;**"

1. Can we not use dart:ui for testing?
2. Can you please suggest any plugin or any way to read content from pdf from a testing perspective? I am using FlutterGherkin for my testing

**Comment by darshankawar** [comment]
@D33pak0508 
If your tests depends on flutter and not on `dart:ui`, you'll need to import  `'package:flutter_test/flutter_test.dart';`, because `dart:ui` is not supported by integration_tests.

Closing as this is not an issue and also the fact that in your integration test file, you can't have an import that directly or indirectly refers to material.dart.

For your second question, please use stackoverflow for solution.
