### ISSUE TITLE
After upgrading to the new flutter version 3.0.0 reorderable list gesture not working

### ISSUE THREAD

**Issue by MohibBhojani** [flutter/flutter#103958]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@MohibBhojani 
This seems to be similar to https://github.com/flutter/flutter/issues/103804#issuecomment-1127415480 which has been fixed and pushed to master https://github.com/flutter/flutter/issues/103804#issuecomment-1127415480
I suggest you to switch to latest master and try again to see it working properly.

`flutter channel master`
`flutter upgrade`

Closing this as fixed since the fix is available on master. If the behavior you are reporting still persist on latest master, write in comments and I'll reopen it.
