### ISSUE TITLE
I want to apply dynamic farmulla using query string for Map<dynamic, dynamic>

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#103950]
i want to add calculation on Map dynamically using query string. like below
-- i will define variable
Map<dynamic, dynamic> content_data = new Map();
content_data["qty"] = 12;
content_data["price"] = 18;

--i want to write just like a string query like below
string  query_string = "content_data["amount"] = content_data["qty"]*content_data["price"]";
i want to execute this query_string and it return Map values which i will add to content_data map.
it is possible in flutter.

**Comment by darshankawar** [comment]
@abdulrehmananwar 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use appropriate new issue template and fill out requested details so that we can address this issue properly.

Closing for now.
