### ISSUE TITLE
Can't share a Flutter project on multiple machines, because hard-coded absolute paths

### ISSUE THREAD

**Issue by leddy231** [flutter/flutter#10394]
I'm building a Flutter app, and I'm using two machines. One macbook at school, and one windows machine at home. Both flutter installations are flawless, except for one thing. When I create a flutter project it hardcodes the paths to different things, like packages and the android SDK. Which leads to the other machine not finding said files since they are in a different location. Packages can be fixed by running "flutter packages upgrade", but the SDK (and possibly more things i havent noticed) are nor fixed. Since flutter can easily find them when creating a project, it should be easy to have it recreate the paths.

**Comment by eseidelGoogle** [comment]
If you have specific files in question, that could help.  See also https://github.com/flutter/flutter/issues/9827 and https://github.com/flutter/flutter/issues/9502.

**Comment by sethladd** [comment]
Great question, thanks for the feedback! Sounds like we do want to have "portable" Flutter projects, as much as possible.

**Comment by xster** [comment]
Hi @leddy231 I think we can deduce the files you are referring to but just to be sure, which operations/files are causing you trouble? 

Also, are you sharing a Flutter project (created by `flutter create`) between machines or are you sharing the Flutter framework (git cloned from flutter/flutter) between machines? 

Sharing projects between machines that have different framework paths should work out of the box if you're using git and haven't modified the initial .gitignore files in the project. Are you perhaps using Mercurial?

**Comment by leddy231** [comment]
Im sharing a flutter project, and im using dropbox to do it. Its usually way easier for me to do use dropbox, and not git. It has worked in the past with regular android studio project (opening the project makes the studio re-find the SDK). 

Just ran `flutter create windowsvsmactest` on both machines and compared all file.
The Dart SDKs seams to be hardcoded in several different files. 
`.idea/libraries/Dart_SDK.xml`
`.idea/libraries/Flutter_for_android.xml`
`android/app/build.graddle`
`.packages`
Just to name a few.

I know dropbox is not the most professional syncing tool out there, but for a student with different machines that likes to just jump in and jump out of coding sessions, its does the task of keeping everything synced.

**Comment by mit-mit** [comment]
Hi @leddy231

`android/app/build.graddle` shouldn't have any hardcoded paths, but rather should have relative paths like `apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"`

The `.idea` and `.packages` files do indeed contain local paths. Typically those would be ignored by source control as controlled by the `.gitignore` file. I'm afraid we don't have good support for "recalculating" them if you open a project on a machine where they are different.

**Comment by mit-mit** [comment]
Note that you can always delete the `.packages` file, and then regenerate it locally by running `flutter packages get`.

**Comment by zoechi** [comment]
The `pubspec.lock` also contains local paths

![image](https://user-images.githubusercontent.com/405837/31775095-e5ec28fc-b4e7-11e7-82f2-2a7a927cb787.png)

but it definitely makes sense to check this file in.

**Comment by zoechi** [comment]
Local paths in `pubspec.lock` were removed a while ago.
Excluding files and directories listed in `.gitignore` should be enough to avoid this problem.
Are there plans to do more work?

**Comment by tedchuang** [comment]
I have the same issue. Flutter is installed on each machine independently, and the source code is created on a cloud drive such as Dropbox folder. For this project, I started on a Windows machine and wish to continue working on a Mac. The code starts off with:

`import 'package:flutter/material.dart`

As I shifted work on a Mac, I get this error message:

`Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/dev/Dropbox/Flutter/inventory/lib/main.dart
...refers, in an import, to the following library:
  /C:/src/flutter/packages/flutter/lib/material.dart
Unfortunately, that library does not appear to exist on your file system.
Exited (sigterm)`

Does anyone have a workaround?

**Comment by zoechi** [comment]
> the source code is created on a cloud drive such as Dropbox folder

If you'd use Git this would be a non-issue. Why are you using DropBox?

See also https://github.com/flutter/flutter/issues/10394#issuecomment-450390544

**Comment by tedchuang** [comment]
Very new to this... I'll look up how to use Git. Thank you.

**Comment by tedchuang** [comment]
> > the source code is created on a cloud drive such as Dropbox folder
> 
> If you'd use Git this would be a non-issue. Why are you using DropBox?
> 
> See also [#10394 (comment)](https://github.com/flutter/flutter/issues/10394#issuecomment-450390544)

Works like a champ. Thank you for the pointer!

**Comment by neiljaywarner** [comment]
for iOS; In the podfile there is a local path right? under flutter_application_path. Note: I have not yet tried relative path like './childdirectory' or '../siblingdirectory' but the docs make it seem like an absolute path...

**Comment by jitheshkramesh** [comment]
If we are using Git, the confidential details we can't upload.
If we are uploading, Google will block our app.
So please share a better solution to work multiple persons want to work on the same project.

**Comment by neiljaywarner** [comment]
Relative path works

**Comment by NJITman** [comment]
> Note that you can always delete the `.packages` file, and then regenerate it locally by running `flutter packages get`.

This worked for me.  Although I agree that some files will have to be added to .gitignore to make the app (accessed from a repo) portable across platform IDEs.  I was cross developing on a mac and windows laptop.  But this is a good workaround for now.

**Comment by jitheshkramesh** [comment]
**.gitignore** is an option. But we can't share those details with our team through the repository.
For share those confidential details, we have to find another solution.
I am thinking about a single solution, which will run on a local server and through the server, we can share the repositories. Anybody have more information, kindly share.

**Comment by NJITman** [comment]
I migrated an app two ways, one via git repo and one via direct file transfer.
1. git repo
- create /android/local.properties with correct references in **sdk.dir** and **flutter.sdk**
- create /android/key.properties with correct reference in **storeFile**
The fact that the **.packages** file is missing is not really a large issue, as the app won't compile and it should be clear that you need to run `flutter packages get` .  This would be a compiler issue to notice that .packages is missing.
2. direct file transfer
- delete **.packages** and run `flutter packages get` to rebuild
- same issues as above, plus
- build artifacts in **/build** directory prevents app from compiling, just deleting the contents of debug and release folders to remove some **.d** files, these files had hard coded references to the location of sources, which prevented a successful compile, this issue was confusing to me since I expected the build artifacts to be removed on a new compile.  May be a VS Code issue.

So transfer via git repo and definitely the way to go, since the build artifacts will be ignored.  However, the three files still pose an issue.
1. **local.properties** is referenced in **/android/app/build.gradle** and should force a compile error if it is missing, this would give you a prompt to go create it, again this is a compiler issue.
2. **key.properties** is referenced in **/android/app/build.gradle** and should force a compile error if it is missing, this would give you a prompt to go create it, again this is a compiler issue.

**Comment by downlz** [comment]
I found a simple solution to this using andriod studio. You need to put the .idea file in gitignore. This way this file is not shared. Once you clone your repo open the project in andriod studio and it will create all necessary files in based on current OS. 
Pull flutter packages and run the application. It will work

**Comment by jonahwilliams** [comment]
The flutter gitignore template contains many files that cannot be shared across different machines. If there are specific files that are not in the gitignore that should otherwise be, then please file a new specific issue for that item.
