### ISSUE TITLE
Move text.dart from the dart/ directory to the text/ directory

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1040]
It's weird that we have the definition of the ParagraphBuilder stuff split across two directories by language. We don't do that for the painting classes.

**Comment by abarth** [comment]
My plan here is to centralize all the Dart code for dart:ui into a directory structure that matches what `pub` expects.  That way we can remove all the build system machinery for copying files into the out directory and rearranging them.

**Comment by Hixie** [comment]
Aren't we moving away from pub? I don't really understand how all these files get slurped in by the embedder/VM at runtime, I must admit.

FWIW, I've found it very helpful to have the dart files and C++ files right next to each other (with the same names). I think it'd be sad to lose that. I agree that there's a good win to be had if we can simplify the build, though.

**Comment by abarth** [comment]
> Aren't we moving away from pub? 

Maybe it's more precise to say that I was going to arrange them in the source tree in the way the analyzer expects to find them.

> I don't really understand how all these files get slurped in by the embedder/VM at runtime, I must admit.

When we build the engine, we create a snapshot of the Dart code that gets linked into the engine.  We do that by passing a command line argument to the `gen_snapshot` tool that points to snapshot.dart, which imports all the built-in libraries.  One of the built-in libraries is dart:ui, which we tell `gen_snapshot` where to find in the file system.  The dart_ui.dart file then uses `part` to load in all the various dart files.

Currently, there's a build step that copies these dart files to the `out` directory (and renames them).  That step no longer provides any value when building the engine.  We can remove it even if we leave the dart files in their current locations in the source tree (or move them to any other arbitrary locations).

In order to support end-developers using the analyzer, we produce a Dart package that contains all the Dart code for dart:ui.  There are more constraints on how we arrange the files for that:

1. We need to put them in a directory named `sdk_ext` that's a peer to a `lib` directory that contains a `_sdkext` file.
2. Ideally we wouldn't have a bunch of extra stuff in that directory because end-developers will need a copy of it on their system.

Currently we generate that structure in the `out` directory using the build system.  I was thinking it would be better to not have the build system involved and just have the structure we need in the source tree directly.

**Comment by Hixie** [comment]
Ah, interesting. How does the analyzer get the files for dart:io and company?

**Comment by abarth** [comment]
Deeper magic.  Roughly, they're included in the SDK tarball you download from dartlang.org.  The dart folks are working on letting us specify them using a yaml file in a Dart package, but that work isn't complete yet.  (That's the so-called embedder.yaml file).

**Comment by Hixie** [comment]
The key though is that they still end up packaged somewhere as actual .dart files (as opposed to being in some sort of compiled form that we could reuse for dart:ui). I guess if we're stuck with having to repackage the files anyway, then yeah, we should just lay out our source tree in the final desired shape.

Ah well.

Maybe an alternative that would still make this slightly easier would be to have comments before each Dart class that corresponds to a C++ class (i.e. each Dart class that extends NativeFieldWrapperClass2) giving the path to the corresponding C++ file (and vice-versa, I guess). It's more work to get from one to the other then but at least it's discoverable (which was the big win of having the Dart and C++ files next to each other).

**Comment by abarth** [comment]
We could structure the source in the final desired form but include the `.cc` and `.h` files for the implementations next to the Dart files.  When we package it up for release, we can just grab a whitelist of files and/or all the `.dart` files.  The layout of the C++ files would be slightly unconventional, but one of the two layouts needs to be unconventional if you want the files next to each other.

**Comment by Hixie** [comment]
Interesting idea. We could take this as an opportunity to rearrange the code to simplify what's going on (e.g. see #1038). Probably best to wait until we've cut out lots of the remaining bits that need removing, though, so that we can tell what we really have left.

**Comment by Hixie** [comment]
Closing issue since it's WONTFIX based on comments above.
