### ISSUE TITLE
Expose SkPathMeasure

### ISSUE THREAD

**Issue by fabiomsr** [flutter/flutter#10428]
I'm currently writing a library and I saw that Flutter doesn't expose the SkPathMeasure
class.

Do you have any plans to expose that class?

Despite PathMeasure class will be used by specific users, I think it is an useful class if complex effects are going to be implemented.

E.g. https://github.com/search?l=Java&q=PathMeasure&type=Code&utf8=%E2%9C%93

**Comment by eseidelGoogle** [comment]
The library is https://github.com/fabiomsr/lottie-flutter.

**Comment by dnfield** [comment]
So I'm interested in this as well - looking through the engine code, it seems like the right way to do this would be as follows:

1. Create path_measure.cc and path_measure.h to wrap SkPathMeasure in https://github.com/flutter/engine/tree/master/lib/ui/painting
1. Create PathMeasure class in https://github.com/flutter/engine/tree/master/lib/ui/natives.dart
1. Create unit tests for this, presumably in https://github.com/flutter/flutter/tree/master/packages/flutter/test/painting

It seems fairly straightforward to me, but am I missing anything here? I was thrown off at one point by some of the classes in the /sky/ folder in engine, but it looks like it'd . be preferable to just implement it as I'm suggesting above rather than attempting to do anything in sky...

**Comment by dnfield** [comment]
Got a working implementation, will create a PR sometime soon (having connectivity issues from where I am right now).

**Comment by dnfield** [comment]
This was added (as `PathMetrics`) in flutter/engine#4957
