### ISSUE TITLE
Please solve this pleaseeeee

### ISSUE THREAD

**Issue by Harshhverma** [flutter/flutter#104204]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Androidstudio\Projects\facebook\android\app\build.gradle' line: 8

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method android() for arguments [build_4f52fbu9hb93egnftut4i5qsr$_run_closure2@1d046072] on project ':app' of type org.gradle.api.Project.    

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleRelease'...                           10.1s
Gradle task assembleRelease failed with exit code 1
PS C:\Androidstudio\Projects\facebook>

**Comment by darshankawar** [comment]
@Harshhverma 
Did you try to search for solutions on other platforms ? You could simply use the error `Could not find method android() for arguments` and try to look for similar links. One such is https://stackoverflow.com/questions/37250493/could-not-find-method-android-for-arguments, so check the same and see if it helps to resolve the issue.

Closing from here, since this should be asked on support channels like StackOverflow.
