### ISSUE TITLE
Flutter-win-4 requires to hard reset the phone

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#104432]
[flutter-win-4](https://chromium-swarm.appspot.com/bot?id=flutter-win-4)

The phone is auto disabling the developer options.

@keyonghan is there anything on device doctor that can cause this behavior?

**Comment by keyonghan** [comment]
Not that I am aware of. Device doctor only reads/checks the `developer mode` and does not update: https://github.com/flutter/cocoon/blob/main/device_doctor/lib/src/android_device.dart#L241

**Comment by keyonghan** [comment]
The current status shows `Device healthcheck failed: attached_device: No device is available;`, not simply related to the developer mode.

**Comment by godofredoc** [comment]
I went to the lab last Thursday. The phone is physically connected but developer mode was disabled. I enabled developer mode manually and the phone disappear again. I'm wondering if there is something in device doctor causing this behavior

**Comment by keyonghan** [comment]
That's weird. From device doctor side, the only `write` actions are `kill top running process if existing` and `reboot`. Neither is expected to switch developer mode off.

When you manually enabled the developer mode on, have you validated the phone successfully showed up in the luci bot page? Based on history of https://chromium-swarm.appspot.com/bot?id=flutter-win-4, the bot has not been able to see the phone since last Wed.

**Comment by godofredoc** [comment]
yes, it went green and I was able to adb

**Comment by yusuf-goog** [comment]
Phone looks like it was reset. Enabled usb debugging and stay awake. Phone is now back online.

Closing. If this happens again, we should determine if something external/internal is resetting the phone.
