### ISSUE TITLE
[google_maps_flutter][Android] Polylines not automatically reflecting on Flutter 3.0.0

### ISSUE THREAD

**Issue by zopagaduanjr** [flutter/flutter#104419]
### issue
updating the polylines of GoogleMap widget is not reflecting immediately in Flutter 3.0.0.

### steps to reproduce

1. clone test repo https://github.com/zopagaduanjr/polyline_delay
2. add api key
3. build using flutter 3.0.0
4. tap on the _toggle polylines_ button to see behavior
5. build using flutter 2.10.3
6. tap on the _toggle polylines_ button to see behavior

demo: https://www.youtube.com/watch?v=3s0e6NQg10Q

### version
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (2 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

**Comment by stuartmorgan** [comment]
@blasten Looks like it's not just markers.

**Comment by blasten** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/103686. I will update the issue title.

This issue was fixed by just triggering the invalidate for  the `marker#update` method call in https://github.com/flutter/plugins/pull/5787, but I realized that a lot of operations are triggering markers update. I added a change in https://github.com/flutter/plugins/pull/5787 to ensure that all operations that trigger update receive an invalidation.
