### ISSUE TITLE
Flutter's GCS bucket should have audit logs enabled

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#104449]
This will allow the Flutter team to keep track of all entities uploading or modifying release binaries, as well diagnose regressions such as https://github.com/flutter/flutter/issues/104387

**Comment by godofredoc** [comment]
@drewroengoogle were we able to enable logging in the flutter-infra buckets?

**Comment by drewroengoogle** [comment]
I think at one point I thought this was blocked because flutter-infra is not onboarding to latchkey correctly, so we weren't able to update the buckets. However, it seems that roles have been able to be updated in flutter-infra, so maybe that's not true - I'll try to enable logging in these buckets again.

**Comment by godofredoc** [comment]
@drewroengoogle I believe we can close this one too.
