### ISSUE TITLE
Clean checkbox colors so they use the material 3 palette

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#104446]
https://github.com/flutter/flutter/issues/91605#issuecomment-1134981254

 > The checkbox is still using the M2 defaults (there isn't an updated M3 spec for it yet). Please file a separate issue for this and we will look into at least cleaning up the defaults here.

![image](https://user-images.githubusercontent.com/22280985/169900310-56d99d0b-e2e5-4f80-9316-4421875dd4b8.png)

Even if the specs are not out yet, the defaults could be more sensible in regards to the m3 generated colors. This looks out of place currently. The contrast looks incorrect too.

**Comment by rydmike** [comment]
To make the old (current ones) Switch, CheckBox and Radio more M3 compatible, my approach to them is to in their component themes define their main color to be `colorScheme.primary` instead of `secondary`, in a `ThemeData` that has `useMaterial3` set to true. Plus, as long as `ThemeData.toggleableActiveColor` exists you also have to set it to `colorScheme.primary` when `useMaterial3` is true.

This because when setting `useMaterial3` to true, it is also very likely that `ThemeData` has an M3 `ColorScheme` that follows its color system design. In this color design, the `secondary` color is a very poor color choice for the toggles. This is also reflected in the totally new M3 Switch that uses `primary`, `primaryContainer`, `surfaceVariant` and `outline` for its colors. (https://m3.material.io/components/switch/specs)

I'm guessing there might be new M3 designs coming for `CheckBox` and `Radio` too, perhaps they do not need completely new widgets like the Switch will do (big redesign anyway), but at least new color guidance that considers the M3 color system correctly.

I don't think it would be bad choice to if the old Switch, CheckBox, Radio - especially if they remain and are replaced by new M3 variants - to set their color to `primary` by default, when using `useMaterial3` set to true. I have used this in current state of lack of other color guidance on them when using M3 color system, and it works quite well and the old switch will then large also match the color style of the new one. But sure, I'm guessing we will see proper specs for the CheckBox and Radio soon too.

**Comment by guidezpl** [comment]
Todo when the spec comes outs
- [ ] Add support for error state
- [ ] Add support for MaterialStateProperty<BorderSide>
