### ISSUE TITLE
Flutter application White screen in release mode when run only on Samsung Galaxy S21 Ultra

### ISSUE THREAD

**Issue by dk3030** [flutter/flutter#104687]
## Steps to Reproduce

1. After Upgrading Flutter 3 Hot-fix Release I Have Facing This Issue Only In Samsung Galaxy S21 Ultra Phone It Show White Screen While Running Flutter Application On Client Phone Can You Please Guide Me I'm Getting Stuck In That Case.

## Logs

Logs Will Not Get

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web

</details>

**Comment by huycozy** [comment]
Hi @dk3030
Have you tried on other platforms or devices? 

We can't confirm the issue with such meager information. Please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to investigate this issue further.

Thanks!

**Comment by dk3030** [comment]
Hello @huycozy

I Have Tried In All Other Platforms It Was Worked Proper But While I'm Testing Application In Client Phone It Shows White Screen I Cant Have Log Of This Error Can You Please Guide Me What Stuff Will Do To Resolve This Issue.

Thank You

**Comment by huycozy** [comment]
Hi, we cannot conclude anything with the information you have given.
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Btw, there was an old issue that is relevant to what you provided: #70558. Hope this may help you. 

Also please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
