### ISSUE TITLE
Inconsistent divider color during animation in ExpansionTile

### ISSUE THREAD

**Issue by weisong0** [flutter/flutter#10464]
Below is the code to reproduce this issue (copied from two level list demo):
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new TwoLevelListDemo());
}

class TwoLevelListDemo extends StatelessWidget {
  static const String routeName = '/material/two-level-list';

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        theme: new ThemeData(
          dividerColor: Colors.grey[200],
        ),
        home: new Scaffold(
            appBar:
                new AppBar(title: const Text('Expand/collapse list control')),
            body: new ListView(children: <Widget>[
              const ListTile(title: const Text('Top')),
              new ExpansionTile(
                  title: const Text('Sublist'),
                  backgroundColor:
                      Theme.of(context).accentColor.withOpacity(0.025),
                  children: <Widget>[
                    const ListTile(title: const Text('One')),
                    const ListTile(title: const Text('Two')),
                    // https://en.wikipedia.org/wiki/Free_Four
                    const ListTile(title: const Text('Free')),
                    const ListTile(title: const Text('Four'))
                  ]),
              const ListTile(title: const Text('Bottom'))
            ])));
  }
}
```
I use a lighter color as the divider color. When you open the sub list, you will see a black divider line and then the color is changed to the actual divider color after animation is completed.

**Comment by weisong0** [comment]
Here is a video to reproduce:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1171990/28090567-944281a8-6641-11e7-96bf-2dea38d2ba9a.gif)

**Comment by mehmetf** [comment]
I started looking into this. Border color is a ColorTween that starts with "Transparent" and ends with "DividerColor".

Transparent is not doing its job. If I set it explicitly to white (or whatever background color), it works. I am guessing it is somehow punching a whole to the underlying scaffold/app color? I need to verify.

**Comment by mehmetf** [comment]
It is not transparent that's not doing its job. This bug is actually interesting.

I believe it is the ColorTween that's problematic. When values start to differ from 0x00000000 to something else the intermediate values become non-transparent and very dark.

The right solution is probably to have an opacity tween here from fully transparent border to fully opaque (to divider color).

**Comment by mehmetf** [comment]
OK. Verified that if ColorTween is constructed with no args, it correctly animates from transparent to the selected color.

The problem is here: https://github.com/flutter/engine/blob/master/lib/ui/painting.dart#L237 . Color.tween should handle a color being explicitly transparent. Will send out a proposed fix.
