### ISSUE TITLE
Add infinite scrolling code sample

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#104706]
now , there is only a Pull down refresh demo, but the load more function is more useful

**Comment by filiph** [comment]
Hmm, I may have forgotten the full context, but here's my infinite list sample from May 2020:

- https://github.com/flutter/samples/tree/main/infinite_list

I'm closing this, because that sample is younger than the latest human-made comment here. I might have forgotten to close this back then.

On the other hand, I see that this is marked as `team-framework`. So maybe the request was to have the sample in the API docs? In that case, feel free to re-open.
