### ISSUE TITLE
[google_maps_flutter] Pointer events not handled correctly when in a stack

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#104812]
# Issue
When the map widget is placed in a stack, with other widgets above it, the map is still being interacted with hits on those widgets

# Repro

 - https://github.com/cedvdb/flutter_repros/tree/google_map_clicks (google_map_clicks branch)
 - change google maps api key in index.html
 - run in chrome
 - mouse over around the top left button you'll see that the mouse cursor is incorrect
 - click on said button
 - a dialog just opened, double click on the dialog button
 - try dragging the map from the dialog

You will see that the map reacts to pointer events of widgets above it, the mouse cursor is also wrong.

**Comment by danagbemava-nc** [comment]
Hi @cedvdb, this is an issue with the platform-views on the web which is being tracked in https://github.com/flutter/flutter/issues/93887

You'd normally be able to mitigate this by wrapping the Dialogs and other widgets that you need to display above platform-views with a `PointerInterceptor`, however, it seems like there's a bug in the `PointerInterceptor` when you're using canvaskit which is being tracked in #100775. 

Also, the reason the cursor is wrong is because the Map is still receiving the events from the mouse. 

If you're using the `html` renderer you should be able to use the `PointerInterceptor` widget just fine

Closing from here as duplicate. 

Thank you
