### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by syedmuhammadwaqas** [flutter/flutter#104964]
<img width="679" alt="Screen Shot 2022-05-30 at 4 49 20 PM" src="https://user-images.githubusercontent.com/12509364/170986736-0faec580-c1fa-42b0-8331-23ecd1bd2071.png">
<img width="697" alt="Screen Shot 2022-05-30 at 4 49 32 PM" src="https://user-images.githubusercontent.com/12509364/170986751-f4a3d3d1-b429-49ab-a3c5-421997299293.png">
<img width="243" alt="Screen Shot 2022-05-30 at 4 51 51 PM" src="https://user-images.githubusercontent.com/12509364/170986786-34936aff-e047-4385-82e3-e93c4687a8af.png">

**Comment by darshankawar** [comment]
@syedmuhammadwaqas 
As mentioned previously, please provide more details as requested in the issue template that'll help us to debug further.
Only screenshot of the error won't help. We need your `flutter doctor -v` and `flutter run -v` logs to know more about the issue. Current info you provided isn't helpful at all, so we have to close this issue because it is not actionable.
