### ISSUE TITLE
Exception: Build process failed.

### ISSUE THREAD

**Issue by ChristianGodoyInformatico** [flutter/flutter#104974]
Starting the app crashes as a result of the following error that appears in the console.

```
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/src/io_client.dart(26,30): error G54CF1E69: A non-null value must be returned since the return type 'IOStreamedResponse' doesn't allow null. [C:\wamp64\www\ERP-APP\escamet-erp-app\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: Compilación personalizada de "C:\wamp64\www\ERP-APP\escamet-erp-app\build\windows\CMakeFiles\128a543f16bc6c7257558b1f9fc0e070\flutter_windows.dll.rule;C:\wamp64\www\ERP-APP\escamet-erp-app\build\windows\CMakeFiles\0d0db72735d346d8441f4ddf73f1d93f\flutter_assemble.rule" terminada con el código 1. [C:\wamp64\www\ERP-APP\escamet-erp-app\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```
-----------------------

it seems that the error comes from the http package.

when applying flutter doctor no problem appears.
but when I insert the following command
'flutter run -d windows -v'
shows the following errors.

![Captura de pantalla 2022-05-30 111029](https://user-images.githubusercontent.com/72088741/171020543-199e25f9-f61f-4f27-b0c2-723f7ca4b698.png)

![Captura de pantalla 2022-05-30 111109](https://user-images.githubusercontent.com/72088741/171020642-24cd18fc-9657-42bb-b19b-51146eaa98cc.png)

what flutter doctor shows:

![Captura de pantalla 2022-05-30 111201](https://user-images.githubusercontent.com/72088741/171020777-0bef9296-361b-4913-9c47-7241b04fb85e.png)

**Comment by darshankawar** [comment]
@ChristianGodoyInformatico 
Thanks for the report. From the error you shared, `pub.dartlang.org/http-0.13.4/lib/src/io_client.dart(26,30): error G54CF1E69: A non-null value must be returned since the return type 'IOStreamedResponse' doesn't allow null.` indicating `IOStreamedResponse` is suppose to return a value but it is returning a `null` which isn't allowed.

What's the dart version / constraint you are using ? Can you also upgrade to latest stable and try again to see if issue still persists ?
