### ISSUE TITLE
Divider widget's line width does not match Material design guidelines

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#10490]
## Steps to Reproduce

Create a Divider widget and observe how it's rendered. Here is a screenshot from iOS simulator running iPhone 7 in front of Material design documentation page on Dividers:

![image](https://cloud.githubusercontent.com/assets/441756/26757745/33b7d55a-487c-11e7-9892-09502bdf71fc.png)

Setting divider height to < 1.0 seems to be restricted by assertion.

The same behavior can be observed in `ListTile.divideTiles` which uses `DecoratedBox` with border decoration of 1.0 width.

I did some experimentation and was able to get _better_ rendering by implementing custom `divideTiles` method and setting border width to 0.5. Result:

![image](https://cloud.githubusercontent.com/assets/441756/26757767/051f08f2-487d-11e7-8ed0-96c862878187.png)

## Logs

N/A

## Flutter Doctor

N/A

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by pulyaevskiy** [comment]
I'd be happy to work on a PR if I can get some hints around what would be a good solution or where to look to start with.

Yesterday I noticed that this also affects user account drawer header. It seems like this may be an issue of underlying rendering engine?

**Comment by Hixie** [comment]
It looks like the bug is just that we misread the Material specification. :-)

The core fix is to change this line:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/divider.dart#L71
...to specify that the border width is 0.0 (which is always painted as one device pixel).

The problem is then trying to figure out what the right behaviour is beyond that. For example, we should probably change how the rest of that build function applies the height so that it's applied on the outside and then the line is drawn automatically centered (SizedBox -> Center -> DecoratedBox or some such). We should probably also remove the restriction on the height so that it can be less than 1.0 (though not less than 0.0) and update all the documentation and then add a test.

**Comment by pulyaevskiy** [comment]
Sounds like something I can take on.

Any objections if I also cover `ListTile.divideTiles` and potentially `UserAccountDrawerHeader` dividers?

**Comment by Hixie** [comment]
Not at all, please go ahead!
