### ISSUE TITLE
[Windows] Use FML_DISALLOW_COPY_AND_ASSIGN to prevent copying, and remove boilerplate in Windows shell.

### ISSUE THREAD

**Issue by moko256** [flutter/flutter#104993]
The FML has FML_DISALLOW_COPY_AND_ASSIGN macro (https://github.com/flutter/engine/blob/main/fml/macros.h).
We can replace some deleted constructors which is used in Windows shell with this and improve readable.

**Comment by stuartmorgan** [comment]
The Windows code deliberately doesn't use a macro, because the code is newer than the change to the C++ style guide that [explicitly bans macros as parts of interface declarations](https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros). Variants of this macro used to be very common in a lot of Google code, but is no longer allowed in new code.

Deleting the constructors explicitly with a comment is the style-recommended way to do this now. See https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types

**Comment by moko256** [comment]
Sorry, I missed it. I'll close this.
