### ISSUE TITLE
Text Editing Toolbar is displayed in the wrong position for single line editable text when EditableText is overflown

### ISSUE THREAD

**Issue by RockXeng** [flutter/flutter#104945]
## Steps to Reproduce

1. enter the long text in textField at least > 80
2. long press text and click Select All 
3. the toolbar is displayed in the left position

**Comment by RockXeng** [comment]
![IMG_0519](https://user-images.githubusercontent.com/23146173/170920387-2df5d9aa-ac91-4355-8ebd-03f8f861dad3.PNG)

**Comment by takassh** [comment]
@huycozy 
my pr is not related to this issue and does not resolve this issue, but it is similar.

**Comment by huycozy** [comment]
> @huycozy my pr is not related to this issue and does not resolve this issue, but it is similar.

Thank for confirming.

**Comment by antholeole** [comment]
Also, it seems like "Select all" scrolls the text area until the very end. This doesn't seem consistent with native. The previous makes solving this bug impossible, since even if we get the toolbar in the right place, the text field jumps anyway. 

![Flutter_Text_field_jump](https://user-images.githubusercontent.com/48811365/172933198-4aed8242-3da4-4366-b4b6-f4a3ae283cfb.gif)

![native_select_all](https://user-images.githubusercontent.com/48811365/172933065-ef0a267a-f5fe-4f8a-a37d-7001ceb6fc11.gif)

**Comment by huycozy** [comment]
> @huycozy is this behavior you saw too? Or am I triaging this incorrectly? Thanks! If you find this behavior too, I'll probably just do one PR that squashes both since they're pretty related.
https://github.com/flutter/flutter/issues/105731

@antholeole Yes, I see the same behavior on my side. I provide comparison with native app on the below demo videos.

| Android | iOS |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/172985039-6a518914-952e-46a3-ac98-edad32e5c5fc.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/172985116-5e72b77f-676b-4218-b437-891574938e69.mov"/>

**Comment by antholeole** [comment]
Awesome - it also seems like whenever you've selecting text and neither of the text selection handles are in view, the toolbar disappears. 

I'll get all 3 of these since they're all related / tangentially related to "select all".

**Comment by antholeole** [comment]
I'm going to close this issue in favor of https://github.com/flutter/flutter/issues/105804, because that issue is just a more specific version of this one. Thanks for the report!
