### ISSUE TITLE
Get X package

### ISSUE THREAD

**Issue by alasriaj** [flutter/flutter#104949]
Please add the getx package to favourite https://pub.dev/packages/get

**Comment by iapicca** [comment]
there has been some drama due to [false claims ](https://github.com/flutter/website/pull/4981) and providing [questionable benchmarks](https://github.com/jonataslaw/getx/issues/789)

Let alone that there are several valid [reason not to use getx](https://www.reddit.com/r/FlutterDev/comments/s4uymg/why_shouldnt_i_use_getx/) 
I'd be very careful before "validating" it with a [flutter favorite](https://docs.flutter.dev/development/packages-and-plugins/favorites) status if these fails claims aren't clarified

(I'm surprised that somehow [getx](https://pub.dev/packages/get) made it to the [list of state management options](https://docs.flutter.dev/development/data-and-backend/state-mgmt/options))

**Comment by stuartmorgan** [comment]
See https://docs.flutter.dev/development/packages-and-plugins/favorites#flutter-ecosystem--committee for the nomination process.

Closing as this process isn't managed via the issue tracker.
