### ISSUE TITLE
On the click of cancel fallback to passcode

### ISSUE THREAD

**Issue by iamkunalpitale** [flutter/flutter#105119]
I had tried if i click on cancel than its fallback to passcode but it is not working
```
Future<bool?> _authenticateUser() async {
bool isAuthenticated = false;

    try {
      isAuthenticated = await _localAuthentication.authenticate(
        localizedReason: "Please authenticate to login",
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: false,
        ),
      );

      isAuthenticated
          ? print('User is authenticated!')
          : print('User is not authenticated.');

      return isAuthenticated;
    } on PlatformException catch (e) {
       _authenticateUser();
      print(e);
      return null;
    }
  }
```

**Comment by danagbemava-nc** [comment]
Hi @iamkunalpitale, I'm not sure entirely sure what your issue is. 

Kindly update your initial post to provide more description as to what exactly the issue is and the steps required to reproduce it. 

Please also provide the output of `flutter doctor -v`. 

If you are seeking help with your own code, kindly see https://www.flutter.dev/community for places where you can ask questions. Stack overflow is also somewhere you can post your questions and someone from the community will help, if they can.

Thank you
