### ISSUE TITLE
Pointers compression in iOS makes apps more easily to OOM in production.

### ISSUE THREAD

**Issue by Yeatse** [flutter/flutter#105183]
Recently we upgraded our app to latest stable version of flutter, and encountered much more crashes in production. Most of the crashes are unrelated to flutter itself, but they are all memory issues.

## Steps to Reproduce

1. `flutter create bug`, then replace `ios/main.swift` as below
2. Run this sample in iPhone 7 (or other low-end iOS devices, physical devices are required), and wait for 3 seconds.

**Expected results:** 

There should not be any issue allocating the memory, because iPhone 7 has 2GB RAM.

**Actual results:** 

`malloc` returned nil even though the memory footprint is low.

In practical situations I would never allocate a huge chunk of memory by myself, but in my app there are many features which will cost a lot of memory, like map views, web views, or editing a large photo, and after upgrading they are much more fragile than before.

<details>
<summary>Code sample</summary>

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) {
      let ptr = malloc(1024 * 1024 * 1024) // 1GB
      print("memory allocated: \(String(describing: ptr))")
    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.1 at /Users/yeatse/Developer/Repo/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (13 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/yeatse/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (3 available)
    • CC's iPhone 7 (mobile) • ff750f59fe91f87eed8aff9c32219c2cf7e2d23c • ios            • iOS 15.2.1 19C63
    • macOS (desktop)        • macos                                    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                                   • web-javascript • Microsoft Edge 102.0.1245.30
    ! Error: CC’s iPhone 12 Pro is not connected. Xcode will continue when CC’s iPhone 12 Pro is connected. (code -13)
    ! Error: CC's iPhone 7 is busy: Fetching debug symbols for CC's iPhone 7. Xcode will continue when CC's iPhone 7 is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

## Question

After bisecting I believe that the problem comes from flutter/engine#30333, as when I revert it in my local build of flutter, or switch flutter to the commit before #95364, the problem disappears. But I really want the pointer compression feature in my app, so what should I do?

From comment by @rmacnak-google in https://github.com/flutter/flutter/issues/95482#issuecomment-1007749971

> madvise(DONTNEED) is lazy on macOS/iOS: the pages are not immediately released and RSS does not immediately decrease as on Linux/Android, but the pages will be released once there is memory pressure.

Is lazy releasing of pages causing this issue?

**Comment by darshankawar** [comment]
Thanks for the report. I verified this behavior on stable 2.5.3, 2.8.1, 2.10.5 and latest 3.0.1 and below are the results:

1. Stable 2.5.3:  `memory allocated: Optional(0x0000000112000000)`
2. Stable 2.8.1: `memory allocated: nil`
3. Stable 2.10.5: `memory allocated: nil`
4. Stable 3.0.1: `memory allocated: nil`

I am not sure if this is a regression or expected behavior, but based on the above result and additional context below, I'll label it as reproducible and for further insights from the team.

> After bisecting I believe that the problem comes from [flutter/engine#30333](https://github.com/flutter/engine/pull/30333), as when I revert it in my local build of flutter, or switch flutter to the commit before #95364, the problem disappears. But I really want the pointer compression feature in my app, so what should I do?

<details>
<summary> previous stable flutter doctor </summary>

```

[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.62.0)
[✓] Connected device (4 available)

[✓] Flutter (Channel unknown, 2.8.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.62.0)
[✓] Connected device (4 available)


[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.62.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability


```

</details>


<details>
<summary> latest stable flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (13 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 3BD8F2FF-FDB5-4074-8C91-54F99C79156D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by jmagman** [comment]
@a-siva @zanderso @rmacnak-google

**Comment by zanderso** [comment]
This sounds related to how the Dart VM reserves parts of the address space to implement compressed pointers. I have a suspicion that it might only be an issue when allocating huge buffers like the 1GB one in the example. I wonder what will happen if instead of one giant 1GB allocation, several smaller allocations are done, like ten 100MB allocations, or one hundred 10MB allocations.

**Comment by Yeatse** [comment]
> This sounds related to how the Dart VM reserves parts of the address space to implement compressed pointers. I have a suspicion that it might only be an issue when allocating huge buffers like the 1GB one in the example. I wonder what will happen if instead of one giant 1GB allocation, several smaller allocations are done, like ten 100MB allocations, or one hundred 10MB allocations.

To dive into it I did more tests and got some interesting results. The code:

```swift
var buffer = [UnsafeMutableRawPointer]()
let chunkSize = 10 * 1024 * 1024
while true {
    if let ptr = malloc(chunkSize) {
        buffer.append(ptr)
    } else {
        break
    }
}
print("allocated \(buffer.count) chunks")
```

and result on my iPhone 7 and iPhone XR:
| chunk size | result on 5d3720625725244345539ea980c9e8599f8e38b1 | result on 1de200596be62f0b487e8dfa742e930d6f13bd1f |
| --- | --- | --- |
| 1 MB | 2752 chunks | 1710 chunks |
| 10 MB | 271 chunks | 176 chunks |
| 100 MB | 26 chunks | 15 chunks |
| 500 MB | 4 chunks | 2 chunks |
| 1000 MB | 1 chunks | 0 chunks |

It seems this only affects the code which needs a lot of virtual memory, as when I call `memset` after malloc'ing them, both two versions behaves the same.

**Comment by a-siva** [comment]
@Yeatse could you alaborate on what you mean by " as when I call memset after malloc'ing them, both two versions behaves the same."

**Comment by Yeatse** [comment]
@zanderso Yes. I created an example project to better describe the use case in my app. 

https://github.com/Yeatse/flutter_map_test

From the template project created by `flutter create bug`, I added one [NSCache](https://developer.apple.com/documentation/foundation/nscache), which should be freed once the system triggers a memory warning, and one ViewController containing a [MKMapView](https://developer.apple.com/documentation/mapkit/mkmapview), where much of the crashes in my app come from.

When I open the map page and navigate to some large cities like Tokyo, the memory used will grow up to 1.1GB before this app suddenly crashes, even without receiving a memory warning. But after I switched to flutter 2.8.1, the memory used can grow up to 1.6GB, then the system will trigger a memory warning for both `NSCache` and `MKMapView` to clean up the cached data.

This can be more easily reproduced on 3GB iOS devices, like iPhone XR and iPhone 8 Plus.

https://user-images.githubusercontent.com/6036532/171924262-3af8cc93-4067-4da9-aa89-ab4bee07945b.mp4

**Comment by Yeatse** [comment]
@a-siva I mean when I change my sample code like this:

```
if let ptr = malloc(chunkSize) {
  memset(ptr, 1, chunkSize)
  buffer.append(ptr)
} else {
  break
}
```

test result will be the same in both 2.8 and 3.0

**Comment by rmacnak-google** [comment]
The compressed heap wants to allocate an aligned 4GB region of address space at startup without also allocating 4GB of memory. Unfortunately, iOS does not respect the MAP_NORESERVE flag to mmap, and we have not found any alternative way to allocate address space without reserving memory. At startup, the compressed heap will allocate the largest power-of-2 that succeeds, and woe be to malloc if it would like to grow by more than what is leftover because iOS will count the whole compressed heap region against the process, including pages that have never been touched.

The alternatives are not good: we can avoid trying to reserve anything up front and hope that subsequent allocations end up in the same aligned 4GB region. This happens to work today because iOS seems to allocate from increasing addresses in the 2nd 4GB region, but if iOS fixes its allocator to do proper randomization, this would break every app using compressed pointers.

If an application's memory is nearly all in the Dart heap, the status quo is a good trade off. But if not, the saving in the Dart heap may be less than the memory made effectively unusable by the compressed heap region.

**Comment by chejdj** [comment]
Me too. When we upgrade the Flutter to 2.10.5.  Much OOM errors.
@Yeatse  Can I ask you how to fix this ?  build flutter engine local or switch flutter to the commit before https://github.com/flutter/flutter/pull/95364 or another solutions.

**Comment by chejdj** [comment]
@rmacnak-google Hello, can you provide some better ways to solve this problem.

**Comment by chejdj** [comment]
@rmacnak-google  Hello, our project is using the Flutter 2.10.5,  so I want to close the pointers compression, so I just revert the Flutter engine  'ecb5b20a453bcd09219ed7bdc338ced699f96793'. Have any problems ?

**Comment by Yeatse** [comment]
@chejdj We reverted https://github.com/flutter/engine/pull/30333 in our internal fork of flutter engine and problem disappeared.

**Comment by chinmaygarde** [comment]
Compressed pointers are being disabled on iOS due to this issue.

**Comment by a-siva** [comment]
I presume this bug is still open to account for the cherry pick to stable, it should be labelled for cherry pick I presume.

**Comment by zanderso** [comment]
This issue is closed, and the CP is approved and should go out in an upcoming 3.0 hotfix release.

**Comment by fzyzcjy** [comment]
Hi, will we one day get compressed pointers again on iOS in the future? It is saving memory so is quite useful to a lot of apps which does not have heavy native memory usage.

**Comment by chinmaygarde** [comment]
Bit of a tricky situation on iOS here. Based on further investigation by @rmacnak-google, a solution to this was introduced in iOS 14 via an additional application entitlement in [`Extended Virtual Addressing`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_extended-virtual-addressing?language=objc). Since Flutter supports iOS versions all the way back to iOS 10, this in itself is a non-starter.

Even if this weren't an issue, we could not enable the entitlement without a paid developer account. The "Extended Virtual Addressing" option was absent and could not be manually added till we setup the right team profile. This is perhaps a non-issue and a user error on our part during our investigation.

Unfortunately, compressed pointers isn't a runtime option and requires a specifically compiled Dart VM. So we can't detect whether to use compressed pointers using a runtime check to see if we can allocate the required virtual address space.

Another (albeit minor and automate-able) issue is that we would require all applications (include to Add2App) scenarios to migrate to adding the entitlement.

We could consider asking applications that make heavy use of native memory to add this entitlement. But if these apps also need to target iOS < 14.0, there is effectively no way to support them and breaks Flutters minimum version guarantees.

To your question of whether we could get compressed pointes in the future again in the default iOS engine, given what we know today, I think we could revisit this till the minimum iOS version supported by Flutter is bumped up to iOS 14.0.
