### ISSUE TITLE
Cupertinopicker alternate style / CupertinoMenuPicker

### ISSUE THREAD

**Issue by Vito0912** [flutter/flutter#105149]
## Use case

Selecting something.

## Proposal
A widget for IOS/Cupertino Widget Picker. At the moment - as far as I have seen - there is no alternative style for the Cupertino Picker. There is currently only the scrolling wheel variant. In several apps in IOS and in some apps on the Ipad this variant of the picker is used. Especially for a few options, this is more appealing to the user.
Since I personally don't own an Iphone, I can't say exactly where this is used. On the Ipad mostly this variant (picture) or a completely new page is used.

![IMG_0466](https://user-images.githubusercontent.com/86927734/171458788-d6ea7571-d89b-4c3c-8a91-c11e70a34d4a.jpg)
App: Goodnotes 5

**Comment by huycozy** [comment]
Hi @Vito0912,
I'm not sure what style you expect to look like. But based on the screenshot you provide, it looks like a dropdown list.
See https://api.flutter.dev/flutter/material/DropdownButton-class.html
Try using dropdown and see if it is what you expected. If it's not, please provide some picker styles so that we'll have enough details to conclude on the issue.

Thanks!

**Comment by Vito0912** [comment]
It would be possible to get the widget close to the desired result. 
However, I would see it as an advantage if it is included in the Cupertino Widget family. 
The Cupertino button is also just a normal button with some style. But it saves work.

Thank you for helping

**Comment by huycozy** [comment]
I think that's why we have `pub.dev` in which developers can create various open-source packages / plugins. You can find there the Cupertino Picker styles that you expected. 

Please also see https://flutter.dev/community for resources and ask questions like this. You may also get some help if you post it on StackOverflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.

I'm closing this issue with above explanation. If you disagree, please write in the comments and I will reopen it.
Thank you
