### ISSUE TITLE
Lab missing instruction

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#105107]
Lab missing instruction

https://codelabs.developers.google.com/codelabs/flutter-github-client?hl=en#5

Does not have a instructions to extend or change the interface nor channel or test dart files.

Thus beginners could get frustrated.

(Also I am not sure about the window to front platform specific code, but i have not tested on all platforms, maybe it is just right)

__Originally posted by @derKosi in https://github.com/flutter/codelabs/pull/897#issuecomment-1143258509__

**Comment by domesticmouse** [comment]
@Derkosi could you expand on what's missing in the plug-in creation step of the desktop codelab? 

For context I created these three plugins on macOS, Linux and Windows, but it has been a year or so since I tested the instructions as written.

**Comment by derKosi** [comment]
I am pretty new to flutter, or dart, but it seems to me that the 
flutter plugin generator creates different structures now then it had a year ago.

So now one has to extend the interface, or it's abstract class window_to_front_platform_interface.dart with a method 'activate' ,
well, maybe we can omit that if we just do excactly what the codelab says...

Nope, the include on the header file is not in the include subdirectory. so this should fail.

Well I cannot say this is the base issue, because I have not a full c++ setup here, so I am not sure why the
example app won't build (can't find the sctivate method for the win dll ),

Regardles, your code (github) is fine and works, but the Labs Code is quite different, and one has to modify not only the few classes described in the lab, but also some other files.

the plugins for mac, win and linux seem fine, the other generated files seem not quite right.

**Comment by domesticmouse** [comment]
I think I have fixed this in the latest iteration of the GitHub client codelab. I'll have another pass at it on Windows and Linux to make sure everything works as advertised.
