### ISSUE TITLE
[web][url_launcher] MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher) 

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#105372]
In debug mode it works fine, if I compile the web and deploy it to Firebase, the plugin no longer works. 

You can check this out by visiting https://min2go-hr.web.app, on the bottom of the page there are Play and App Store links which can't be opened because of the error. 

Flutter doctor: 

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.854, on macOS 12.0.1 21A559
    darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] VS Code (version 1.68.0-insider)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by huycozy** [comment]
Hi @ljmatan,
I tried opening https://min2go-hr.web.app on both desktop and mobile, it worked as expected.

<details>
<summary>Demo</summary>

- Desktop (macOS, Chrome):

https://user-images.githubusercontent.com/104349824/172114913-3dc9fb7f-6618-473b-8ff8-8ba85b8adfa7.mp4

- Mobile (Android):

https://user-images.githubusercontent.com/104349824/172114940-18f6e7a6-db81-46b9-9888-410e4d3d1b62.mp4

</details>

Which specific environment did you try?
Please also provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Thank you

**Comment by ljmatan** [comment]
This and another package issue were somehow caused by building off of an external SSD on Mac.
