### ISSUE TITLE
A picker that includes both Date picker and Time picker.

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#105304]
## Use case
For when you wanna create a DateTime object from a picker that includes the time as well. It would be very useful for web.
## Proposal
Just have both of the current pickers side by side as a new type of picker

**Comment by mtc-jed** [comment]
I use CupertinoDatePicker with `mode = CupertinoDatePickerMode.dateAndTime`.

**Comment by exaby73** [comment]
Hello @glaceon2000. Currently, the material design specification, which you can read more on material.io, does not support a hybrid date and time picker such as iOS. So this does not seem like a feasible feature request.

You can use the [`CupertinoDatePicker`][1] as @mtc-jed has suggested. Or you can use a third-party library like [date_time_picker][2].

I'm closing this issue due to above mentioned reasons.

[1]: https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html
[2]: https://pub.dev/packages/date_time_picker

**Comment by glaceon2000** [comment]
Yea these solutions are OK for Mobile but not good on web. It's incovenient and unintuitive to have time separated into another picker when DateTime object itself can store time. The date_time_picker package is still not the best as it forces people to pick a time

**Comment by exaby73** [comment]
You can implement your own function to handle this type of behavior. You can search StackOverflow for how to do this. Unfortunately, this type of behavior is not present in the Material spec so we cannot really consider this feature :)
