### ISSUE TITLE
Heating issue in iOS 

### ISSUE THREAD

**Issue by pranavo72bex** [flutter/flutter#105420]
My iPhone facing heating problem in flutter application but working completely normal in android .
 
Target Device : iPhone XS 

[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by darshankawar** [comment]
@pranavo72bex 
This issue isn't actionable without providing any performance profiling the app which is showing the behavior you are reporting. See https://flutter.dev/docs/perf/rendering/ui-performance and https://flutter.dev/docs/development/tools/devtools  also, see [this](https://github.com/flutter/flutter/issues/74833#issue-795394794) to know what are the things are required for us to debug performance related issues better, so please try to provide the same.

Closing for now, since no details are provided. Just mentioning `my iphone is facing heating problem` is very vague and isn't helpful. We would need details as mentioned in above links as well as the details mentioned in new issue template.
