### ISSUE TITLE
Java taking too much memory and multiple instances of java are being launched while building application 

### ISSUE THREAD

**Issue by tiklup11** [flutter/flutter#105570]
Issue : Every time I start to build my application, a new  java instance is launched and memory usage of every instance is too much, causing my system to crash every-time. Crashing of system may be OS related issue but launching multiple java instances is concerning me. 
Every instance is taking more than 1gb ram and it's increasing with time.Then it reaches to a point where total ram usage goes to ~99% and the system crashes. I have to hard reboot every-time. I don't know if more than 1gb is normal or too much for a single instance. I got 8gb ram and I don't run emulator.

Please refer attached screenshot.

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on Manjaro Linux 5.15.41-1-MANJARO, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
![Screenshot from 2022-06-07 15-26-13](https://user-images.githubusercontent.com/57872422/172528140-b42575cd-80c4-44a3-b6ed-89d740db78ea.png)

**Comment by huycozy** [comment]
Hi @tiklup11,
As I can see from your `flutter doctor -v`, you're using the old Flutter SDK, the latest version is stable `3.0.1` and master `3.1.0-0.0.pre.1160`.
Can you try upgrading your SDK to the latest and retry?
If the issue still persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and reproduction steps so that we may verify this. 
Thank you!
