### ISSUE TITLE
[pigeon] Expose the toMap method in the ObjC header

### ISSUE THREAD

**Issue by Lyokone** [flutter/flutter#105786]
## Use case

I'm using Pigeon for my plugin and since it does not support EventChannel yet, I have manually set up one.

Since the EventChannel is using the same data as one of the methods, I wanted to use the `toMap` method to transform it automatically in my Swift Code.

But the header message is missing 
```
- (NSDictionary *)toMap;
```

## Proposal

Expose the `toMap`. 

If such a change can be considered I would be happy to do the PR.

**Comment by stuartmorgan** [comment]
/cc @gaaclarke 

I think this is probably not something we should do. `toMap` is an implementation detail of the Pigeon method channel, and the pigeon method channel is subject to change at any time as it's an implementation detail of Pigeon itself. E.g., we could potentially make data class serialization array-based instead of dictionary-based for efficiency of transfer.

Presumably you are writing hand-written Dart code that would consume this map, which would be broken if Pigeon's format changed?

**Comment by Lyokone** [comment]
Thanks for your answer!

Not at all, I'm using the method `.decode` generated by Pigeon since it's the exact same object so any breaking change would be fine.

**Comment by electricbolt** [comment]
@Lyokone you could just expose the toMap method to be public in a Objective-C class extension method in your own project, without needing to do a PR:

```objc
@interface WhatEverYourPigeonClassIsCalled (Map)
- (NSDictionary *)toMap;
@end
```

Don't forget to include the .h file into your bridging header to expose it to Swift. The toMap method will then be available to Swift.
