### ISSUE TITLE
Cannot write unit test for kIsWeb

### ISSUE THREAD

**Issue by acccrop** [flutter/flutter#105855]
I have a code as follows that uses kIsWeb , I am unable to write a unit test so that both the paths are covered.

`class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    if (kIsWeb) {
      return Text("I'm web");
    } else {
      return Text("I'm not web");
    }
  }
}`

**Comment by huycozy** [comment]
Hi. It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

Please see this StackOverflow answer for more details: https://stackoverflow.com/questions/60334121/testing-kisweb-constant-in-flutter

Closing as this is neither a bug nor a feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
