### ISSUE TITLE
No tests should not exit with code 1

### ISSUE THREAD

**Issue by r-dev-limited** [flutter/flutter#105873]
Related to https://github.com/flutter/flutter/issues/17760

When using:

```
--total-shards
--shard-index
```

There is a chance that with low number of tests, some shard will not have enough tests to run.

Which inevitably ends with return error code 1, which ends up as failed job in CI.

That should be suppressed always OR at least when using sharded tests

**Comment by huycozy** [comment]
Hi @r-dev-limited
I don't see return code anymore when executing `flutter test` on the project without `test` dir.

```bash
➜  no_test_dir flutter test
Test directory "test" not found.
➜  no_test_dir 
```
Which Flutter version are you trying?

> There is a chance that with low number of tests, some shard will not have enough tests to run.
Which inevitably ends with return error code 1, which ends up as failed job in CI.

Can you provide some specified cases for this?

**Comment by r-dev-limited** [comment]
thats not the same thing...create 2 test files, and set shards to 10, then those shards without tests will end up with return code 1

**Comment by huycozy** [comment]
@r-dev-limited 
I still can not reproduce the issue. I was adding `--total-shards` to 10 whilst there are two test files in the project but the result is shown as below without return code 1.

```bash
➜  no_test_dir flutter test --total-shards 10 --shard-index 1
No tests ran.                                                                                                                                                   
No tests were found.
➜  no_test_dir flutter test
00:07 +1: All tests passed!  
```

Please provide more detailed reproduction steps so that we can verify this issue. 
It would be better if you can provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by williamhjcho** [comment]
Hi 👋 
this is a bit of a tangent to the original issue, but in case the exit code persists, would it also be possible to change the value to something else (similar to what the dart team did in https://github.com/dart-lang/test/issues/1418)?
