### ISSUE TITLE
ThemeExtension  triggers multiple rebuilds

### ISSUE THREAD

**Issue by miaosun009** [flutter/flutter#105883]
Run the example theme_extension.1
Print content in build of the Home page. Triggering ThemeMode changes will cause Home to repeat rebuild

![image](https://user-images.githubusercontent.com/17589354/173322635-2e4a9592-b4e7-4383-a5be-8d1a9370d484.png)

https://user-images.githubusercontent.com/17589354/173322707-3b28c8f3-fb44-4f54-b443-b50597625f35.mov

**Comment by HansMuller** [comment]
Theme changes are animated, which is why you see multiple rebuilds. The [Theme API doc](https://api.flutter.dev/flutter/material/Theme-class.html) doesn't appear to mention this, so perhaps we've got a doc bug.

**Comment by miaosun009** [comment]
> Theme changes are animated, which is why you see multiple rebuilds. The [Theme API doc](https://api.flutter.dev/flutter/material/Theme-class.html) doesn't appear to mention this, so perhaps we've got a doc bug.

Yes, I looked at the source code for The MaterialApp yesterday because of the AnimatedTheme, but I think adding a parameter to turn off the theme animation in the MaterialAp is a necessary feature

**Comment by Mamun361054** [comment]
https://github.com/flutter/flutter/issues/105883#issuecomment-1154738540
I think so because unnecessary rebuild always prohibited

**Comment by maheshmnj** [comment]
Hi @miaosun009,  Could you please share a minimal and complete code sample?

Thanks

**Comment by miaosun009** [comment]
@maheshmnj  Why not hand over theme animation to an external implementation? Most of the time, we need to change the Theme mode without the transition animation, but there's nothing we can do about it now

**Comment by darrenaustin** [comment]
@miaosun009 thanks for the report, as Hans mentioned above this is expected behaviour and has nothing specific to due with ThemeExtensions, but rather that any change in a MaterialApp's theme will be animated. 

That said, we should document this and it might make sense to expose the animation curve and duration as properties of the MaterialApp. That way if don't want the animation, you could just shut it off with a zero duration.

Just curious, but what is the use case where you are changing the theme and it is important for that change to take effect immediately?

**Comment by miaosun009** [comment]
@darrenaustin  
Yes, I agree with you，expose the animation curve and duration as properties of the MaterialApp.
