### ISSUE TITLE
Plugin for recording audio

### ISSUE THREAD

**Issue by stepango** [flutter/flutter#10592]
I'm new into Flutter, want to play around and build simple audio recorder. Is it possible? Is it any ready to use audio recording plugin?

**Comment by mit-mit** [comment]
I don't believe such a plugin is available yet. We'd love to see one contributed! You should be able to do the recording in native code, and then pass back the result to the UI (likely via a file).

**Comment by eseidelGoogle** [comment]
There is at least one shipping app which wrote their own:
https://play.google.com/store/apps/details?id=com.harpsoft.bendometer.ui.android&hl=en
presumably using https://flutter.io/platform-channels/ but without bundling it up into a plugin for redistribution.

**Comment by dweekly** [comment]
FYI - I'd love to see this added.

**Comment by michaelwills** [comment]
New to flutter, just doing a survey of what is available and this was a question of mine as well.

#7482 references an audio playback plugin:

https://github.com/rxlabz/audioplayer

Very instructive. There is a neat project here https://github.com/genedelisa/AVFoundationRecorder that looks helpful for the Swift side, and of course Android mediarecorder example here: https://developer.android.com/guide/topics/media/mediarecorder.html

**Comment by michaelwills** [comment]
So @mit-mit  given that Dart can read/write files in the documents folder, would it need to pass the file back? (I am new to Dart, too.)

@stepango are you initially targeting any platform? iOS/Android?

Given that there is already a player plugin, what kind of API are you thinking of? @dweekly? One plugin would not likely satisfy _all_ needs, of course. But perhaps a `simple_recorder` to hit 75-80% of needs?

* Set a name
* Choose the settings (with platform overrides?)
* handlers for start, stop, starting again could overwrite or perhaps resume?
* handler for volume levels?
* File management would _not_ be needed

The plugin development workflow for Flutter looks better than any of the others when I looked at them in the past.

I can't say I will write it, but I may take a _slow_ stab at it as I have time.

**Comment by michaelwills** [comment]
@eseidelGoogle is there any way to allow plugins to share a reference to a native platform object? The idea being low-level plugins could be composed together to make more complex plugins.

**Comment by mit-mit** [comment]
Cc @mravn-google

**Comment by mit-mit** [comment]
> So @mit-mit given that Dart can read/write files in the documents folder, would it need to pass the file back? (I am new to Dart, too.)

No; I meant to say "pass the file-name" back, not the actual file itself.

**Comment by mravn-google** [comment]
@michaelwills Yes, you can do anything native platform code allows you to do, including e.g. declaring and accessing plugin as singletons. The only caveat is that plugin registration order is not under your control. So probably you want the code that introduces your plugins to each other to be executed after all plugins have been registered. One way to accomplish that is to place such code after your call to super in `onCreate`/`[super application:didFinishLaunchingWithOptions:]` -- or let it be invoked from the Dart side using a dedicated method channel.

**Comment by michaelwills** [comment]
Ah, good to know @mravn-google. Many thanks. That's me thinking further down the line a bit essentially enabling plugins to act as middleware.

**Comment by ZaraclaJ** [comment]
I published a flutter plugin to record audio ! Reviews are welcome : https://github.com/ZaraclaJ/audio_recorder/blob/master/README.md

**Comment by Wahooney** [comment]
@ZaraclaJ I'm using your plugin and so far it's working, is there a way to change the recording frequency?

Side note: I'm new to flutter, I had a look at your code and see that the recorder works through MethodChannel, where do you find the references to the strings you use? ie. "audio_recorder", "start", "path", "extension", etc.?

Thanks.

**Comment by ZaraclaJ** [comment]
Hello, 
the method  onMethodCall(MethodCall call, Result result) in audio_recorder/android/src/main/java/com/jordanalcaraz/audiorecorder/audiorecorder/AudioRecorderPlugin.java catch the method sent by the class audio_recorder/lib/audio_recorder.dartaudio_recorder/lib/audio_recorder.dart.
 
For exemple, if you call audio_recorder.start(), 
the dart method invoke method with 'start' : _channel.invokeMethod('start', {"path": path, "extension": extension});
Then the android method onMethodCall() catch it and call the startRecording() method that start the record

i tried to be as clear as possible

Jordan ALCARAZ
 
 
 
> Message du 18/09/18 14:57
> De : "Wahooney" 
> A : "flutter/flutter" 
> Copie à : "Jordan Alcaraz" , "Mention" 
> Objet : Re: [flutter/flutter] Plugin for recording audio (#10592)
> 
>
> @ZaraclaJ I'm using your plugin and so far it's working, is there a way to change the recording frequency?
> Side note: I'm new to flutter, I had a look at your code and see that the recorder works through MethodChannel, where do you find the references to the strings you use? ie. "audio_recorder", "start", "path", "extension", etc.?
> Thanks.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flutter/flutter","title":"flutter/flutter","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/flutter/flutter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Wahooney in #10592: @ZaraclaJ I'm using your plugin and so far it's working, is there a way to change the recording frequency?\r\n\r\nSide note: I'm new to flutter, I had a look at your code and see that the recorder works through MethodChannel, where do you find the references to the strings you use? ie. \"audio_recorder\", \"start\", \"path\", \"extension\", etc.?\r\n\r\nThanks."}],"action":{"name":"View Issue","url":"https://github.com/flutter/flutter/issues/10592#issuecomment-422381675"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/flutter/flutter/issues/10592#issuecomment-422381675", "url": "https://github.com/flutter/flutter/issues/10592#issuecomment-422381675", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [flutter/flutter] Plugin for recording audio (#10592)", "sections": [ { "text": "", "activityTitle": "**Wahooney**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@Wahooney", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"flutter/flutter\",\n\"issueId\": 10592,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"flutter/flutter\",\n\"issueId\": 10592\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/flutter/flutter/issues/10592#issuecomment-422381675" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 231977663\n}" } ], "themeColor": "26292E" } ]

**Comment by acidjazz** [comment]
It would be nice to be able to detect the microphone volume as well.

**Comment by sgon00** [comment]
Hi, I tried all the recording plugins, such as [flutter_sound](https://pub.dartlang.org/packages/flutter_sound), [audio_recorder](https://pub.dartlang.org/packages/audio_recorder), [medcorder_audio](https://pub.dartlang.org/packages/medcorder_audio) and etc..
But all of them give me very low volume sound, compared to what native apps produce. It really doesn't make sense to me. Why do all of them produce the same low volume audio? Do anyone have any ideas why and how to fix it? Thank you very much.

**Comment by PavelPZ** [comment]
Hi, I have the same observation as @sgon00 on Android GO.

**Comment by acidjazz** [comment]
that's a shame to hear @PavelPZ and @sgon00 , @ZaraclaJ any idea?

**Comment by LarsDu** [comment]
Two years later and I have a nice example using `audioplayers` and `audio_recorder` up and working.https://github.com/LarsDu/simple_flutter_audio_recorder

**Comment by junaidShaikh** [comment]
@LarsDu Thanks for the amazing walkthrough.
&& 
@ZaraclaJ I have been beating my head around the neighborhood trying to find an audio recorder that is compatible with Google Speech-to-text cloud API. Sadly none of the formats that are supported in your recorder, qualify for the conversion. 
Ref: https://cloud.google.com/speech-to-text/docs/encoding
some handy additions would be: 
1. FLAC (best case scenario)
2. OGG_OPUS (size efficient + widely used in whatsapp and telegram as well)
3. LINEAR16 (very handy to use)
4. MP3 (lossy yet most widely used globally)

**Comment by nt4f04uNd** [comment]
This package seems to be decent record quality
https://pub.dev/packages/record/

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
