### ISSUE TITLE
Travis in plugin repo sometimes hangs during Xcode build

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10604]
Travis times out after Xcode build hasn't produced an output in over 10 minutes. Usually, a build should be completed in less then 10 minutes, so something is probably hanging.

There are also reports of this happening by other Travis users: https://github.com/travis-ci/travis-ci/issues/5743

Why should try some of the work-arounds listed there.

/cc @mit-mit @tvolkert @mehmetf

**Comment by tvolkert** [comment]
@mehmetf, FYI in case you want to have a look: the Xcode build is triggered here: https://github.com/flutter/plugins/blob/100a3a3949344f0efba650301385b6894cabb5a4/.travis.yml#L107 -- that kicks off flutter_tools, which in turn runs Xcode build

**Comment by mehmetf** [comment]
I am trying to fix a separate issue actually. Builds are taking extremely long for PRs because we are running each project (changed or not) sequentially. I will try to detect changed files using Travis env variables and see if I can fix this. Non-PR travis runs won't be affected by this and the timeout is still possible.

**Comment by iapicca** [comment]
Hi @goderbauer is this issue still meant to be open?

**Comment by goderbauer** [comment]
We don't use travis anymore. Closing.
