### ISSUE TITLE
Uncaught SyntaxError: Duplicate parameter name not allowed in this context

### ISSUE THREAD

**Issue by funyin** [flutter/flutter#106113]
## Steps to Reproduce

1. Create a simple flutter app and include the following code snippet
```dart
enum ProjectType{
  Android("android"),
  Flutter("flutter"),
  Wordpress("wordpress");
 final String name;
 const ProjectType(this.name);
}
```
2. Execute `flutter run -d chrome` 

**Expected results:** 
The flutter web app runs normally

**Actual results:** 
When the code compiles and runs, the blank white screen and progress bar flutter web keeps showing indeterminately.

<details>

No error is shown in the run terminal. 
In the console chrome devtools the following error is shown
```javascript
Uncaught SyntaxError: Duplicate parameter name not allowed in this context
```
Note this issue only occurs in flutter web(debug mode) but works on profile and release, and also on android

</details>

<details>
  <summary>Solution</summary>
  This error occurs because enums already have a property "name". When converted to dart.js the error is thrown because js does not support functions with duplicate argument names.  The solution is to rename the property you created.

</details>

**Comment by danagbemava-nc** [comment]
Hi @funyin, this was previously reported in https://github.com/flutter/flutter/issues/104189 & https://github.com/flutter/flutter/issues/103874 and has since been fixed. I believe the fix is available on the `beta` and `master` channels and should make it to `stable` sometime in the future. 

Closing this as it has already been fixed in newer versions of flutter. 

Thank you
