### ISSUE TITLE
App life cycle state detached, Known this state its inutil

### ISSUE THREAD

**Issue by salva73** [flutter/flutter#106184]
What is the sense of knowing the detached state if we cannot anticipate any action? Once the didChangeLifecycleState function shows us the detached state, nothing can be done, for example save in shared preferences that the user detached the application? In previous versions, this could be done but there is no way, and thanks to 

https://github.com/flutter/flutter/issues/60294#issuecomment-690235251

**Comment by danagbemava-nc** [comment]
Hi @salva73, does https://master-api.flutter.dev/flutter/dart-ui/AppLifecycleState.html#detached help you understand what the `detached` state is for?

**Comment by salva73** [comment]
Hi @danagbemava-nc , yeah sure that help me but, i dont understand why in flutter  v1.22.8 i could stored in didChangeAppLifeCycle function on shared preferences, when the status was detached, for example: user detached the app, if i print the status is next:
- Inactive
- Paused
- Detached
If i do this:

if(status == AppLifecycleState.inactive) { // here yes i can stored the status }

**Comment by danagbemava-nc** [comment]
Hi @salva73, I don't think you were supposed to be doing anything in the `detached` state to begin with. 

> When I dispose controllers inside the dispose function, it never succeeds, with sockets, this is a big problem
> 
> @override
> dispose() {
>    sockets.dispose(); // never success
>    ....
> }

Can you provide a complete minimal reproducible code sample that shows this behavior that you are experiencing so that we can investigate this? See also, the documentation for [dispose](https://api.flutter.dev/flutter/widgets/State/dispose.html)

**Comment by salva73** [comment]
@danagbemava-nc i cant provide the code, its private, but It's not that I suppose I want to do something, it's that I want to do something, for example store the last state of the application, and then make decisions when the application is launched again

thank you

**Comment by danagbemava-nc** [comment]
Hi @salva73, can you help me understand what you need to do with the `detached` state that you cannot achieve with the `inactive` state?

**Comment by danagbemava-nc** [comment]
That is what I'm trying to understand, why would you want to store in your shared preferences that the app was detached?

**Comment by salva73** [comment]
It doesn't matter what I want to do later, I want to use the shared preferences to store the boolean when the user detached the application, in version 1.22.8 I could do it now I can't

**Comment by danagbemava-nc** [comment]
You aren't exactly making an argument for why this should be implemented. 
From the comment in https://github.com/flutter/flutter/issues/60294#issuecomment-690235251, this is working as designed. 

The bug could be that it ever worked in the first place. Just because something worked in previous versions doesn't mean it was always the right thing.

**Comment by danagbemava-nc** [comment]
For the record and for future reference, people's use cases have helped evolve the way flutter works over time. Some decisions may be taken which are later changed due to the use cases that are presented by the community. 

Your use case is what I was interested in but you did not present any. 

However, it turns out that there are reports of issues with the AppLifecycleState.detached that have been reported earlier. You can follow up in https://github.com/flutter/flutter/issues/65538 for updates. It seems like this is similar to the issue you're facing. 

Thank you
