### ISSUE TITLE
[In_app_purchase] [Flutter] [Android] Upgrade/Downgrade Subscription 

### ISSUE THREAD

**Issue by nidhi-concetto** [flutter/flutter#106168]
```dart
 final GooglePlayPurchaseDetails  oldPurchaseDetails = ...;
PurchaseParam purchaseParam = GooglePlayPurchaseParam(
    productDetails: productDetails,
    changeSubscriptionParam: ChangeSubscriptionParam(
        oldPurchaseDetails: oldPurchaseDetails,
        prorationMode: ProrationMode.immediateWithTimeProration));
InAppPurchase.instance
    .buyNonConsumable(purchaseParam: purchaseParam);
```

My Issue is how do I get old purchase details for existing purchase and how do I convert it to GooglePlayPurchaseDetails 

Using in_app_purchase 3.0.6 
and Also I had linkedPurchaseToken, so is there any way to get purchaseDetails from that token?

Thanks in Advance.

**Comment by danagbemava-nc** [comment]
Hi @nidhi-concetto, kindly check out the example of the IAP plugin for how you can do this. 

https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase/example/lib/main.dart

**Comment by nidhi-concetto** [comment]
@danagbemava-nc  Thanks for the comment, I checked that but what I am asking is what if user has purchased one subscription and after few days user is trying to upgrade/downgrade subscription from app, at that time I don.t have purchase details. So how to get pastPurchase details.

**Comment by danagbemava-nc** [comment]
You should be able to retrieve the list of purchases by listening to the purchase stream. See 
https://github.com/flutter/plugins/blob/715593b72d1c882111f164a04edecd3a9c7d6cc6/packages/in_app_purchase/in_app_purchase/example/lib/main.dart?rgh-link-date=2022-06-17T13%3A33%3A40Z#L55

You can also see what is done when the stream is updated in 
https://github.com/flutter/plugins/blob/715593b72d1c882111f164a04edecd3a9c7d6cc6/packages/in_app_purchase/in_app_purchase/example/lib/main.dart?rgh-link-date=2022-06-17T13%3A33%3A40Z#L426-L457

You do, however, need to make sure that you are always keeping track of the purchases on your server, since the information in your app may not be correct. 

Do any of the above links help you?

**Comment by nidhi-concetto** [comment]
ok, in short we need to maintain purchase details at our server. Thanks for the quick response. @danagbemava-nc
