### ISSUE TITLE
TextField isCollapsed isDense Windows Android

### ISSUE THREAD

**Issue by Matix2003** [flutter/flutter#106293]
On Windows, TextField is 8px smaller than on Android, when InputDecoration isCollapsed: true or isDense: true.
Code:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/107851852/174585353-ac043e07-0439-446e-a2b9-15c6bac6ff31.png">
Windows:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/107851852/174585463-5ae3c39e-cf01-4f26-9e0e-13bdd511147a.png">
Android:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/107851852/174586631-4e6f9138-55ba-4294-8057-c18876294591.png">

**Comment by huycozy** [comment]
@Matix2003 
I'm not sure I understand your issue so I would like to confirm again.

> TextField is 8px smaller than on Android

Do you mean 8px is font size? Or what kind of properties?

From what I can see, the outstanding difference is the padding. When you set `contentPadding: EdgeInsets.zero` and `isDense: true`, the padding looks better on Android than on Desktop (tested on Web, MacOS, Windows). Is that your issue?

| Windows | Android |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/174711558-e53a246d-8a68-4379-8565-62d41ec53697.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/174711567-563f21bb-bab6-422e-a9ce-1fc9cb3abe83.png">

When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

Thank you!

**Comment by Matix2003** [comment]
TextField(style: TextStyle(fontSize: 60px, height:1), decoration: InputDecoration(isDense: true, contentPadding: EdgeInsets.zero, border: InputBorder.none))
OR
TextField(style: TextStyle(fontSize: 60px, height:1), decoration: InputDecoration(isCollapsed: true, contentPadding: EdgeInsets.zero, border: InputBorder.none))

I checked in Flutter DevTools:
TextField on Windows is 52px height (is smaller than the fontSize)
TextField on Android is 60px height

Shouldn't the heights be the same?

**Comment by huycozy** [comment]
@Matix2003 

The height on both Android and Windows is the same on my side.

| Android | Windows |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/174795368-4a4db4f8-5cf3-488b-90d5-71fb09a7f061.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/174795370-0d085817-e1d7-4e3d-8d46-4ab300bc5ee0.PNG">

Can you share the screenshots of Flutter DevTools from your side?
And please provide your output of `flutter doctor -v` as well.

**Comment by Matix2003** [comment]
that solved the problem:
MaterialApp(theme: ThemeData(visualDensity: VisualDensity.standard), home: )

**Comment by huycozy** [comment]
@Matix2003 

For more information:
https://github.com/flutter/flutter/blob/61b3b3999b4ea19766208206d005b348895305e1/packages/flutter/lib/src/material/theme_data.dart#L2615-L2631

With `visualDensity` as `VisualDensity.adaptivePlatformDensity`:

```dart
// This makes the visual density adapt to the platform that you run
// the app on. For desktop platforms, the controls will be smaller and
// closer together (more dense) than on mobile platforms.
visualDensity: VisualDensity.adaptivePlatformDensity,
```

Closing the issue since it works as intended. If you disagree, please write in the comments and I will reopen it. 
Thank you!
