### ISSUE TITLE
Future catchError not work well.

### ISSUE THREAD

**Issue by Stitch-Taotao** [flutter/flutter#106239]
Reproduce Code
```
import 'dart:async';

void main(List<String> args) {
  runZonedGuarded(() {
    Future((() {
      return '3';
    })).then((value) {
      print(value);
      throw ("error!!!!!");
    }).catchError((Object error) {
      print('catchError:$error');
    });
  }, ((error, stack) {
    print('unhandle error:$error');
  }));
}
```
You can run it direct in [DartPad : Reproduce Code](https://dartpad.dev/?id=183ab30e1ff4209438f37af0dcb4d011)

I think the unhandle error should be exposed in complile time ，some like `catchError function take a wrong type onError parameter` . Otherwise , catchError make no sense and was confusing!

**Comment by maheshmnj** [comment]
Hi @Stitch-Taotao, Thanks for filing the issue. I believe this issue should be filed in the [language repo under dartlang](https://github.com/dart-lang/language). Closing as this issue is not related to flutter, Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.
