### ISSUE TITLE
[go_router] Allow redirecting to the current location

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#106214]
We should allow redirects to return the current route. For example:

```dart
    redirect: (state) {
      final signedIn = _appState.auth.isSignedIn();
      if (!signedIn && state.location != '/signin') return '/signin';
      return null;
    },
```

Which could be written as:

```dart
    redirect: (state) {
      final signedIn = _appState.auth.isSignedIn();
      if (!signedIn) return '/signin';
      return null;
    },
```

**Comment by johnpryan** [comment]
For example, this test fails:

```dart
    testWidgets('Can redirect to itself', (WidgetTester tester) async {
      final List<GoRoute> routes = <GoRoute>[
        GoRoute(
          path: '/',
          redirect: (_) => '/',
          builder: (BuildContext context, GoRouterState state) =>
              const Page1Screen(),
        ),
      ];

      final GoRouter router = await _router(routes, tester);
      final List<GoRouteMatch> matches = router.routerDelegate.matches;
      log.severe(
          'Exception: ${(router.screenFor(matches.first) as ErrorScreen).ex}');
      expect(router.screenFor(matches.last).runtimeType, Page1Screen);
    });
```

and prints:

```
[SEVERE] GoRouter tests: Exception: Exception: redirect loop detected: / => /
```

**Comment by loic-sharma** [comment]
Overall I like this as it'd cut down on boilerplate. However, I'm concerned that there may be valid scenarios where a user actually does want to do a redirect to the current route. For example, imagine redirecting to the `/signin` route somehow refreshes the user's credentials and updates the app's state. Do you think that's a valid concern? If so, how would we allow the developer to "force" a refresh to the current route?

**Comment by ebelevics** [comment]
I have two scenarios when this is important for me.
1. Drawer. When I press on drawer goNamed button, I want to get redirected to the same page with drawer closed and retriggered screens initState.
2. After some API, app is forced to go to path "/a" and change screen values accordingly . When I'm on different page, everything works fine, but when on the same "/a", the screen doesn't refreshed. 

With Navigator 1.0 I managed to do this with   //Navigator.of(context).pushNamedAndRemoveUntil(someRootScreen, (Route<dynamic> route) => false); but can't do same behaviour with GoRouter, and have no idea how to bypass it

**Comment by ebelevics** [comment]
Ok, I have noticed that you can redirect to same page by using `pageKey: UniqueKey()`. Doesn't seem that there is easy way to set it to all pages, but will try to find out

**Comment by chunhtai** [comment]
> Overall I like this as it'd cut down on boilerplate. However, I'm concerned that there may be valid scenarios where a user actually does want to do a redirect to the current route. For example, imagine redirecting to the `/signin` route somehow refreshes the user's credentials and updates the app's state. Do you think that's a valid concern? If so, how would we allow the developer to "force" a refresh to the current route?

I am not sure if I understand the /signin example. Can you explain the sequence of the urls?

> how would we allow the developer to "force" a refresh to the current route
There are the refreshListenable or the Inheritedwidget once we add the BuildContext to redirect, or they can go with extreme way, use web plugin to programmatically refresh the browser

**Comment by johnpryan** [comment]
This issue is only about how we interpret the result of a redirect. If we want an API to refresh the current screen we should probably file a separate issue for that. It would also be helpful to have a scenario where this is useful. For example, right now you can't easily update the query parameters (https://github.com/flutter/flutter/issues/107279) so you could imagine a refresh() API that essentially calls go() with new parameters.

**Comment by loic-sharma** [comment]
> > Overall I like this as it'd cut down on boilerplate. However, I'm concerned that there may be valid scenarios where a user actually does want to do a redirect to the current route. For example, imagine redirecting to the `/signin` route somehow refreshes the user's credentials and updates the app's state. Do you think that's a valid concern? If so, how would we allow the developer to "force" a refresh to the current route?
> 
> I am not sure if I understand the /signin example. Can you explain the sequence of the urls?

The scenario is one where the app wants to redirect to the current route. Here's an abstract sequence of URLs:

1. My app goes to the `/a` route
2. My app decides it needs to redirect from `/a` to `/a` once
3. Now that the single redirection is over, my app now builds `/a`

Is this a scenario we should support?

**Comment by johnpryan** [comment]
It would be helpful to have a scenario describing why the app needs to navigate from `/a` to `/a`. For example to re-process the redirects, change query parameters, or something like that.

**Comment by chunhtai** [comment]
> My app decides it needs to redirect from /a to /a once
If this is to wait for some async process to finish, we can add support to async redirect

**Comment by loic-sharma** [comment]
My point is that the proposed change to `redirect`'s behavior would prevent a user from redirecting to the current route. We should make sure that's an acceptable loss before moving forward with the proposal. I don't have any concrete examples personally (I'm still a go_router noob! 😅) but these seem like interesting scenarios: https://github.com/flutter/flutter/issues/106214#issuecomment-1161701195

**Comment by cedvdb** [comment]
a `refresh()` helper could be useful here

**Comment by om-ha** [comment]
Sorry to barge in here, but this is the only source online I found discussing keys in go_router.

Since `pageKey` parameter is optional, I have no idea if we should provide it or not.

We are upgrading from [go_router] to [go_router_builder].
- Within [`buildPage`](https://github.com/flutter/packages/blob/be97f92e052da6e5883a243747cc2d4343bc3e27/packages/go_router/lib/src/route_data.dart#L41) when returning [`CustomTransitionPage`](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/pages/custom_transition_page.dart) or [`MaterialPage`](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/pages/material.dart) we have to specify `LocalKey`
- This key is in-turn propagated up to `Page` superclass's property [key](https://api.flutter.dev/flutter/widgets/Page/key.html).
- Previously since we were only using [go_router], we passed the key from [`pageBuilder`](https://github.com/flutter/packages/blob/be97f92e052da6e5883a243747cc2d4343bc3e27/packages/go_router/lib/src/route.dart#L139)'s `GoRouterState` [`state.pageKey`](https://github.com/flutter/packages/blob/be97f92e052da6e5883a243747cc2d4343bc3e27/packages/go_router/lib/src/state.dart#L71).

Question here is, should we provide [`UniqueKey`](https://api.flutter.dev/flutter/foundation/UniqueKey-class.html) or [`ValueKey<String>`](https://api.flutter.dev/flutter/foundation/ValueKey-class.html)?

What should we use and what's the difference between the two? For us `ValueKey` would be a name based on the route itself, but I am hesitant about `ValueKey` as some few pages can be pushed repeatedly on navigation stack (think a Profile Details page opening infinitely, having the same route with same pageKey `"profile_details"`)

**Comment by clragon** [comment]
> After some API, app is forced to go to path "/a" and change screen values accordingly . When I'm on different page, everything works fine, but when on the same "/a", the screen doesn't refreshed.

Personally, I think it is undesirable to use navigation to refresh values. 
Whatever state managment you use should instead trigger a state update and your screens should react accordingly.
Though maybe there is a valid usecase for that nonetheless.

---

On a completely different note, I would also love for this feature to be implemented.

Since my app has a website as backend that has more endpoints than my app supports, I would love to be able to push URLs to the router and, if those URLs are "outside" I would like to open a browser. 

This could be achieved with redirects, except that, for a redirect to count as "redirected", I have to return a new path, because the redirect function doesnt allow marking the call as successfully redirected without that. What path do I return? to not navigate anywhere, I would say it would be easiest to simply return the current path. 

This would only work if we can redirect to the current path (which would be "no redirect but handled" in my ideal scenario).

**Comment by chunhtai** [comment]
> This could be achieved with redirects, except that, for a redirect to count as "redirected", I have to return a new path, because the redirect function doesnt allow marking the call as successfully redirected without that.

Can you talk more about what feature you are looking for? I am not sure if I understand what `redirected` means. If we allow returning the current location, it would be treated the same as return null.

**Comment by clragon** [comment]
I looking for a way of "redirecting" without any redirection taking place, 
basically signaling the router that I have handled the redirect without routing. 

(for example: I push a URL into the router and then a "redirect" would open a browser. this would not return a new route. instead, the user would stay in the current route while other apps take the URL from there. I would imagine changing state instead of redirecting would also be interesting)

**Comment by chunhtai** [comment]
are you talking about the GoRouter.push? Since it will always push a route even if there is no redirection. For Gorouter.go, can you just return null to stay at the same page?
