### ISSUE TITLE
[Idea] Make center/outside stroke more consistent.

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#106362]
> **Note**
> This is specific to RoundedRectangleBorder. BoxBorder already does this via isUniform.

A few weeks ago I opened this issue (https://github.com/flutter/flutter/issues/104201) because I thought it felt better. However, today I was playing with Figma and, not that Flutter has to follow it, Figma has the same StrokeAlign.start as Flutter, which is great. My issue then is closed.

... Except...

When I made the PR for StrokeAlign.center and outside, I made the rectangle rounder (check screenshot) because it is impossible to lerp from 0-1 otherwise. Figma doesn't do this. So... should we have the same behavior of StrokeAlign.start for center and outside, which is the same as Figma, but doesn't lerp 0-1 perfectly (check video)? It is a two or three LOC change and it hasn't landed on stable yet, so it is not a breaking change.

Pro: consistency, same behavior as start, same behavior as Figma.
Cons: lerp from 0.0 to 1.0 will jump. 

![image](https://user-images.githubusercontent.com/351125/174886953-5475aff2-060c-4104-b960-51ff9d7235a1.png)

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
I would say that in the image you have above, the Flutter side is the way it should work, and that Figma is doing the surprising thing, not Flutter. The principle of "least surprise" would say that we should keep doing it the Flutter way.

**Comment by HansMuller** [comment]
If I understand this correctly, the "Flutter way" is surprising: https://github.com/flutter/flutter/issues/104201#issuecomment-1138944444

**Comment by bernaferrari** [comment]
Where I wrote "Flutter", I mean my implementation (that took care of lerp, Figma doesn't). I didn't think about the roudness side effect.

It is very simple. If you apply the `inflate` before the BorderRadius, something happens, after, something else.
And if you use  `drawDRRect`, BorderRadius.zero != square. So you need `if (borderRadius == zero) drawRect`. That's what the PR is doing.

Here you can see how reordering a few lines changes the output:
https://github.com/flutter/flutter/issues/104201#issuecomment-1138997601

**Comment by bernaferrari** [comment]
If you really enjoy the roundess effect (like I did, even opened an issue for it), maybe we could have `isRoundnessInside` and then apply to all StrokeAlign, including Inside. Right now, inside has one behavior and center/outside has a different one (my fault).

**Comment by bernaferrari** [comment]
Friendly ping @gspencergoog. Can we go with the 'correct' behavior? Even your StarBorder lerp does that (what I want, what you still don't).

**Comment by gspencergoog** [comment]
What do you mean when you say that the lerp from 0.0 to 1.0 will jump? It seems to me that it should be possible to lerp from 0.0 to 1.0 smoothly, but I think I'm just not seeing what you mean.

You also said:
> So... should we have the same behavior of StrokeAlign.start for center and outside, which is the same as Figma, but doesn't lerp 0-1 perfectly (check video)?

But I don't see the video you mention.

I think what you're proposing is the same as [what I mentioned in your initial request](https://github.com/flutter/flutter/issues/104201#issuecomment-1138843837), so I'm not really opposed, but the lerp needs to be smooth: we do lots of lerping between borders, and they all need to be smooth.

**Comment by bernaferrari** [comment]
> It seems to me that it should be possible to lerp from 0.0 to 1.0 smoothly, but I think I'm just not seeing what you mean.

Here we go:
 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/351125/180844712-2fa473e3-324a-4571-a3af-5f912534d224.png">

Can you make:

`canvas.drawRRect(RRect.fromLTRBR(0.0, 0.0, 100.0, 40.0, 0.0))`  paint a squared shape? I can't. Due to this DRRect gets wrong and lerping to zero is impossible.

**Comment by gspencergoog** [comment]
Ahh, so the lerping discontinuity comes because of the (proposed) conditional that says if you have a zero radius, draw a rect instead of a rounded rect, right?

This reminds me a lot of the `Paint`'s `strokeJoin` values.  You're basically popping between miter join and rounded join when you leave zero.

Couldn't we just honor the `strokeJoin` values in the Paint? Then you could tell it you wanted it to be rounded at zero with `StrokeJoin.miter`, and rounded with `StrokeJoin.round`. Non-zero radii in that case would get rounded anyhow if you consider the "round" to be approximated by a number of line segments: they wouldn't approach the miter limit. And then even the star borders would be able to control their stroke parameters better. I was considering that anyhow, because if you have a pointy star, but don't want a pointy border, you're out of luck right now.

**Comment by bernaferrari** [comment]
> Ahh, so the lerping discontinuity comes because of the (proposed) conditional that says if you have a zero radius, draw a rect instead of a rounded rect, right?

Yes. You can get 'sharp edge' with `rrect`.

> Couldn't we just honor the strokeJoin values in the Paint?

Maybe we could? But that's not user configurable. So you propose adding StrokeJoin to RoundedRectangleBorder?

I don't understand this:

> Non-zero radii in that case would get rounded anyhow if you consider the "round" to be approximated by a number of line segments: they wouldn't approach the miter limit

For StrokeAlign.miter,
if (radius == 0) rect else rrect (squared inside, default, the 'correct behavior')
For StrokeAlign.round,
always rrect (inside is round, the 'wrong' behavior that I and you love)?

**Comment by gspencergoog** [comment]
What is the scope of what you're proposing: do you want this to happen for all calls to `canvas.drawRRect`? Or just for borders? Because was I was proposing was adding a `strokeJoin` to `BorderSide`, and honoring that for borders.

Also, it looks like in the addition of `strokeAlign` to `BorderSide`, we missed adding that parameter to the `copyWith`, and consideration in the `BorderSide.merge`. And now that I think about it, it would be pretty nice to be able to lerp from one alignment to the other smoothly (i.e. instead of an enum, make it a double from -1 to 1 or something).

For `canvas.drawRRect`, I think it should stay the way it is: it should always draw a rounded rect, since that's what was requested.

**Comment by bernaferrari** [comment]
> What is the scope of what you're proposing

I'm still not entirely sure I understood your idea. But it was supposed to be Borders only (I thought RoundedRectangleBorder initially only, lol). What would be the benefit of this for, say, CircleBorder?

> And now that I think about it, it would be pretty nice to be able to lerp from one alignment to the other smoothly (i.e. instead of an enum, make it a double from -1 to 1 or something).

I have no idea how to implement something like this. We could use the `circularity` concept in lerp, but I don't know how it would be in practice, because there are 6 different possible interpolations.

> For canvas.drawRRect, I think it should stay the way it is: it should always draw a rounded rect, since that's what was requested

Yeah, but what about the RoundedRectangleBorder? Should it have different behavior from StrokeAlign.inside to center/outside? I think we should make everything 'squared' inside, the code will be cleaner, but lerp, well... 

https://user-images.githubusercontent.com/351125/180862352-1b1f378d-c1e0-41c0-acf9-ea0d48dcba23.mov

**Comment by gspencergoog** [comment]
OK, so yeah, let's just focus on borders, since they're higher level primitives than the canvas calls.

> I have no idea how to implement something like this.

It's basically just offsetting the amount that the paths are inflated/deflated, so a value of one (equivalent to StrokeAlign.outside) would mean that the outer path is inflated the full width of the border (while the inner path is not inflated at all), and a value of negative one (equivalent to StrokeAlign.inside) would be deflating the inner path the full width of the border (and the outer path is not deflated at all), and a value of zero (StrokeAlign.center) would inflate the outer path by half of the border width, and deflate the inner path by half the border width.  Values in between would be scaled appropriately.

> Yeah, but what about the RoundedRectangleBorder? 

I think that it should do what deflate does: square corners. If you were to implement the above algorithm, I think it would make the most sense.

**Comment by bernaferrari** [comment]
I like this idea, we can try to see how viable it is. Should I do it first or do you want to do it?

**Comment by bernaferrari** [comment]
enchanced enums won't solve this because we want a custom value.. 😩 ideas?
