### ISSUE TITLE
Regression in stock_build_iteration microbenchmark

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106306]
SkiaPerf is reporting a regression on the commit here https://github.com/flutter/flutter/pull/104958

https://flutter-flutter-perf.skia.org/e/?begin=1654134787&end=1655738052&keys=X7edbc38ce2a20c938aca3e137e0d8e2d&requestType=0&xbaroffset=29472

@HansMuller @LongCatIsLooong @xu-baolin

**Comment by LongCatIsLooong** [comment]
@xu-baolin I think we should revert? Let's try using a global key instead of using a `LayoutBuilder`?

**Comment by xu-baolin** [comment]
> @xu-baolin I think we should revert? Let's try using a global key instead of using a `LayoutBuilder`?

Ok, I will revert that.
Do you know why the `LayoutBuilder` affects the skia performance?

**Comment by zanderso** [comment]
The benchmark has recovered following the revert, so I will close this.

**Comment by LongCatIsLooong** [comment]
A few things I noticed after profiling:

1.  `RenderObject._layoutWithoutResize` calls `markNeedsPaint` so there's also the cost of repainting incurred.
2. The overhead of the additional layout pass seems to be relatively small but it's still something, mostly because in this case the LayoutBuilder isn't a relayout boundary so the entire scaffold actually needs to relayout.

Interestingly the LayoutBuilder change even slightly outperforms the current implementation in `stock_build_iteration` if I expose a `PipelineOwner.scheduleRelayout` method and use that to schedule relayout (instead of `markNeedsLayout`).
