### ISSUE TITLE
No apparent easy way to disable a text field

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10645]
Opening this as a response to https://stackoverflow.com/questions/44490622/disable-a-text-edit-field-in-flutter

Original question: "I need to disable TextFormField occasionally. I couldn't find a flag in the widget, or the controller to simply make it read only or disable. What is the best way to do it?"

**Comment by eseidelGoogle** [comment]
@HansMuller or @Hixie would know. :)

**Comment by abnerh69** [comment]
Hi, any advice about readonly / disable a TextFormField?  Thanks

**Comment by FastNinja** [comment]
Hi guys, this is a very common feature - sometimes you want user to edit fields, sometimes fields are just readonly.
Do you recommend render different Widgets based on whether or not field is editable?

**Comment by BenSower** [comment]
My use-case is a menu with two radio buttons. One is a default option, the other allows the user to define his own data using a textfield. If the user selects the default-option, I want the textfield to be "disabled" to visualize that the other option is active as well as block any input to the textfield.

I tried using a Stack which adds a ModalBarrier() +  a reduced Opacity() on top of the TextField whenever I want it "deactivated" and I also took away the focus from the field using a focusNode, which can work as expected in certain circumstances. Still I didn't use this solution since I had to put the ModalBarrier in a Container/SizedBox for it to only cover the Textfield. For this I needed to know the exact size of the textfield, which can probably be retrieved or defined somehow, which felt somewhat hacky...

In the end I resorted to just using the Opacity as well as automatically "deactivating" the default option and selecting + "activating" the textfield if the user taps into it. Its not a bug...

**Comment by HansMuller** [comment]
This is a bug. Although `InputDecorator` provides a way to render the textfield as if it were disabled (`InputDecoration.enabled = false`), the textfield isn't functionally disabled.

**Comment by BenSower** [comment]
Yeah, I looked into that feature too, but figured that it is literally just a decorator and so it has no direct impact on the actual functionality of the TextField. Still, it should at least "grey-out" the text in the textfield itself.

**Comment by flutterq** [comment]
Step By Step Guide to [How to disable text edit field in flutter ?](https://flutterq.com/wp-admin/post.php?post=243&action=edit)
