### ISSUE TITLE
explicitly set java binary path with flutter config

### ISSUE THREAD

**Issue by animeshxd** [flutter/flutter#106416]
## Use case
I have to work with multiple java version, and flutter uses gradle 6.7 which is not comfortable with latest java versions,
Alternatively, I have to perform changes on every projects `android\gradle.properties` to work with
```
org.gradle.java.home=C:\\Program Files\\Java\\jdk1.8.0_331\\
```

## Proposal
It will be great if we can set java home or executable with flutter config
```
PS C:\Users\MSI> flutter config --java-binary=<path/to/java/executable>
Setting "java-binary" value to "<path/to/java/executable>".

You may need to restart any open editors for them to read new settings.
```

**Comment by gnprice** [comment]
This would be very helpful as a way to deal with https://github.com/flutter/flutter/issues/121501 .

It was also proposed at https://github.com/flutter/flutter/issues/110807#issuecomment-1239036147 . I think it would be a good idea.

One proposed revision to the idea: I would have the setting be the Java base directory, rather than the `java` executable itself. That is, it would be the same value that you might set in `org.gradle.java.home` or in the `JAVA_HOME` environment variable. That convention seems to be what most Java-related software expects when specifying what JDK to use, so following that convention is probably what people will most often expect.

Possible names for the setting include:
* `java-home` (following `org.gradle.java.home` and `JAVA_HOME`)
* `android-jdk` (more descriptive of its role — but perhaps too easily confused with `android-sdk`)
* `gradle-jdk` (again descriptive of its role; and follows the Android Studio UI, which gives [the corresponding setting](https://stackoverflow.com/questions/68120382/how-to-set-java-jdk-path-in-android-studio-arctic-fox-bumblebee-etc/68120383#68120383) the label "Gradle JDK")

**Comment by sebastianhaberey** [comment]
Another advantage of this solution over having to set `JAVA_HOME` (as was proposed in #110807, for example) is that it can make sense to leave `JAVA_HOME` blank. For example a developer involved in various projects might want to choose their JDK on a per-project basis instead of setting a global JDK that is misleading at best.

So in short, yay for this solution!

**Comment by abarke** [comment]
I ran into this today. Real time waster trying to find a solution. Not working as expected IMO.

Is there any easy way to just tell flutter to use JAVA_HOME as it probably should, as that is the default JRE on the machine. 

Any other project that requires a specific JRE version should specify that within the project IMO.

The current hack I use is in the `gradle.properties` which I don't want to check into git as this may vary from machine to machine.
```
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.19.7-hotspot\\
```

**Comment by gnprice** [comment]
@abarke Until this feature is added, here's a workaround that will cause Flutter to use the default JRE on your machine — i.e. to use JAVA_HOME, and fall back to finding `java` in your PATH:

Run the command `flutter config --android-studio-dir=/`. (Or instead of `/` use any other bogus value, so long as it's the path to some actual directory.) This will set the `android-studio-dir` in your local Flutter settings (in your homedir, shared across your various Flutter projects) to a path that doesn't actually have an Android Studio installation.

The reason this works is that Flutter's current logic for finding what JDK to use is:
* the Android Studio bundled JDK, if the Flutter tool has succeeded in finding one;
* JAVA_HOME;
* finding `java` on your PATH, using the command `which java`.

And the latter two steps are exactly the standard concept of "the default JRE on the machine". So if you just defeat the first step by manually pointing Flutter at a bogus Android Studio install, that's what you get.

(This issue calls for inserting a new step at the beginning, namely to consult the new setting named `java-home` or `gradle-jdk` or whatever.)

I believe that the `android-studio-dir` setting has no other effects besides this, though I haven't gone and tracked through the code to 100% confirm that.

**Comment by abarke** [comment]
+1 having issues with the new Android Studio as it defaults to Java 17 now. I need to set 11 as the default as it was before or be able to simply set it in the flutter config as suggested. Would be the most obvious place to configure this. Why it uses Android Studio as the default is beyond me. These are 2 separate tools. One would assume that simply setting JAVA_HOME would resolve this. However should the user want to override this, then it should be possible in the context of the flutter CLI and also on the project level. The easy solution for me so far is to force it in `gradle.properties` using:
```
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.19.7-hotspot\\
```

**Comment by abarke** [comment]
@gnprice thanks for the workaround 👏 this works a treat. Made my day 🍻 
```bash
flutter config --android-studio-dir=/
```

**Comment by reidbaker** [comment]
@rifkyputra the work around intentionally breaks Android Studio config in flutter doctor so that the flutter tool can instead rely on JAVA_HOME. Try setting JAVA_HOME in your path to the jdk version you wish to use for your project.

**Comment by rifkyputra** [comment]
I have found other temporary solution for macos. 

go to 
`/Users/<USERNAME>/Library/Java/JavaVirtualMachines/`

it might have more than 1 jdk here, flutter tool (or maybe Android studio) will set higher version as default.
![image](https://github.com/flutter/flutter/assets/11476083/70a1fb37-e608-4123-9566-a4c68e2489f9)

so, move uneeded jdk to other location 
`mv jdk1 jdk2 ~`

now when i run `fvm flutter doctor -v` it set the correct version (the one remains in /Users/<USERNAME>/Library/Java/JavaVirtualMachines/)
