### ISSUE TITLE
Flutter web poor performnce

### ISSUE THREAD

**Issue by Chasanpro** [flutter/flutter#106573]
https://pagespeed.web.dev/report?url=https%3A%2F%2Fgallery.flutter.dev%2F%23%2F

**Comment by darshankawar** [comment]
Same as https://github.com/flutter/flutter/issues/106572#issuecomment-1166931672. When you open issue and say `web poor performance`, please back it up with description, current behavior, code sample so that we'll have enough details to work with. We can't tell from the link you shared, what exactly are you trying to show / convey.
