### ISSUE TITLE
Update connectivity plugin to degrade gracefully if access_network_state permission is not present on Android

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10659]
On a case-by-case basis, we may want to either make a plugin:

1. Act as a no-op if the app doesn't have the requisite permissions
2. Return a status code to the Dart code to indicate the action wasn't taken
3. Throw

**Comment by Hixie** [comment]
@tvolkert Is this something that's on your radar to do? Did you have specific plugins in mind? We're worried that this is too broad as a single bug to be usefully actionable.

**Comment by mehmetf** [comment]
I will take this over. It came to be from discussions with Android team. So far, connectivity plugin is the only one so far that needs additional permissions. Incoming local_authentication (fingerprint) plugin is going to be the second one.

**Comment by swissonid** [comment]
If it helps, I have a rough draft of a solution [here](https://github.com/swissonid/BarcodeScannerPlugin) for my plugin.  Which is heavily inspired by the [PermissionsDispatcher](https://github.com/hotchemi/PermissionsDispatcher) lib which I usually use on my Android projects.

**Comment by mehmetf** [comment]
ACCESS_NETWORK_STATE is not a dangerous permission as per [Android categorization](https://developer.android.com/guide/topics/permissions/normal-permissions.html). So if we list it in the manifest, it is automatically granted to the app. The same thing applies to local_auth (use_fingerprint is not a dangerous permission). 

We could check for the permission and degrade the functionality of the plugin but I don't really see the point of doing that since plugins manifest requests this permission and is automatically merged to the app manifest.

We will be working on a Contacts plugin soon for Flutter, that's where this will come up since READ_CONTACTS requires asking for permission at runtime.
