### ISSUE TITLE
Text is too light

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#10655]
## Steps to Reproduce

In latest version of Flutter the text and icons are too light. See before and after pictures. Same in the Flutter Gallery. Only tested on iOS.

Before
![img_0692](https://user-images.githubusercontent.com/1539812/27082470-360ca1f2-5045-11e7-9982-2eccb093f909.PNG)

Latest version
![img_0691](https://user-images.githubusercontent.com/1539812/27082475-3a3433da-5045-11e7-9e44-d3dce203ca07.PNG)

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision e38f92df9a (7 hours ago), 2017-06-12 22:48:51 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • Viktor’s iPhone • 0f78a8bf61e64931b13636987dc7597b86ba55a7 • ios • iOS 10.2 (14C92)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@tvolkert did this show up in image diffs?
@xster @cbracken were there iOS-specific text changes?

**Comment by tvolkert** [comment]
If this just started showing up this morning, it was likely caused by https://github.com/flutter/flutter/pull/10651, which picked up https://github.com/flutter/engine/pull/3765, which *did* introduce image diff failures when I tried to roll it internally (see last night's comment in the PR)

**Comment by tvolkert** [comment]
Hmm actually it's very unlikely that that PR is responsible - investigating further.

**Comment by tvolkert** [comment]
Actually, the image diff failures I'm seeing are dividers pushing the layout to be more spaced out than previously, which is likely #10523.  I'm not seeing any text color differences.

**Comment by vlidholt** [comment]
After looking at this a bit more, I think transparency is what's not rendered correctly. Things that are transparent gets more transparent then they should.

**Comment by Hixie** [comment]
@vlidholt Have you been able to pin down when this regressed?

**Comment by vlidholt** [comment]
@Hixie I think sometime in the last week. I'm seeing it in Flutter Gallery too. Are you guys not able to reproduce it? I see it on both Simulator and on a real device.

**Comment by vlidholt** [comment]
@Hixie @cbracken I've done some research, and I'm reasonably sure this is the commit where the problems are starting: https://github.com/flutter/flutter/commit/4bde698ffcd060f5be9e561263f5053127dc14d6

**Comment by vlidholt** [comment]
To be even more precise, this seems to be when it happened: https://github.com/flutter/engine/commit/ffe8181ffe7432b61a67323c80fd8025704e4695

**Comment by cbracken** [comment]
@vlidholt Thanks. Tagging the PR for cross-ref: flutter/engine#3743.

**Comment by cbracken** [comment]
@vlidholt how does colour on iOS compare to the Android release of Newsvoice? I'm assuming closer to the 'Before' screenshot above?

**Comment by eseidelGoogle** [comment]
cc @mattsarett

**Comment by mattsarett** [comment]
This is definitely caused by flutter/engine#3743.

The semi-translucent black text is now being blended correctly onto the white background, making it appear lighter.  Can the app choose to use darker text if that is the desired appearance?

@brianosman

**Comment by vlidholt** [comment]
@mattsarett The alpha is most certainly not rendered correctly. I made a simple test case here: https://github.com/vlidholt/flutter_bug_alpha/blob/master/lib/main.dart

Output of the test below. The boxes on the right and left should match.

![screen shot 2017-06-14 at 10 58 41 am](https://user-images.githubusercontent.com/1539812/27124176-7c21be4c-50f0-11e7-82cd-b76b42472777.png)

**Comment by mattsarett** [comment]
Sorry I should have provided more detail.  The interesting insight is that 8-bit pixel component values are almost never encoded on a linear scale.  They are typically encoded with some sort of exponential transfer function to preserve precision.  In this case, these 32-bit values (which eventually become SkColors) are defined to be sRGB values, which means that the 8-bit components are encoded on the (standard) sRGB transfer function curve.
https://en.wikipedia.org/wiki/SRGB#The_sRGB_transfer_function_.28.22gamma.22.29
https://www.w3.org/Graphics/Color/srgb

Let's take the example of blending 0x80ffffff on to 0xff000000.
(1) First we convert the pixel component values to linear.  This is trivial, since the curve has end points at 0 and 1.  We get [1.0, 1.0, 1.0] and [0.0, 0.0, 0.0].
(2) Now we blend using alpha (alpha is always a linear value).  We get [0.5, 0.5, 0.5].
(3) Finally, convert those values back to sRGB encoded bytes.  We get [0xBC, 0xBC, 0xBC].

The result of blending without taking the transfer function into account is trivially [0x80, 0x80, 0x80].  Note that 0x80 actually corresponds to a linear value of about 0.22.  So if we fail to take the transfer function into account, the result of blending 50% white onto black is an actual screen brightness of only 22%.

FWIW, if the app knows that it wants text at a certain shade of gray, the most straightforward approach is probably to use gray text instead of semi-translucent black.  Then the renderer does not have to perform a blend at all.

I'm sorry to introduce a behavior change, but the new behavior is as intended.  Color correct rendering has a lot of great benefits beyond making semi-translucent text look lighter :).  For more details, here is some documentation.
https://skia.org/user/sample/color

**Comment by mattsarett** [comment]
Beyond the mathematical explanation, I think there is a perceptual question to consider here.  What should 50% gray actually look like?

An interesting approach is to consider walking a long distance away from a black-white dither, letting your eyes do the interpolation.  I've written a small demo that shows various ways of creating 50% gray - dither, scaled dither, blending, hard-coded gray values.  I think it is a compelling way to show that blending linearly gives us the best approximation of how our eyes perceive 50% gray.
https://fiddle.skia.org/c/@50_percent_gray

I would, however, have to agree that the text in the "after" image does look too light.  I think this is something we need to consider with material design.  Is it ok to use opaque colors in the material design spec (here everyone agrees on how they should look)?  If we are using translucent colors, do we need to adjust the values?  Good news is that we will be meeting with material design on Monday.

**Comment by vlidholt** [comment]
@mattsarett Thanks for the explanation. I can understand that the actual alpha representation is not linear (which it is in many frameworks and can cause confusion). However, if it is not, then the built in conversion functions should probably reflect that.

E.g. consider the `withOpacity` function from the Color object.

```
Color withOpacity(double opacity) {
    assert(opacity >= 0.0 && opacity <= 1.0);
    return withAlpha((255.0 * opacity).round());
  }
```

It simply does a linear conversion. If I do a box with 50% gray (128, 128, 128), I would expect that to be roughly the same color as drawing Colors.white.withOpacity(0.5) on a black background. I think most developers would expect that to be the case. This is currently not the case.

If you've changed how opacity is rendered internally, you will most likely also need to change the Color class's methods to reflect that change. Currently the colors displayed in e.g. the gallery does not match the Material design specification (just open the spec to see the differences side by side).

Updated the test with using opacity set to 0.25, 0.5, and 0.75:
![screen shot 2017-06-14 at 7 19 15 pm](https://user-images.githubusercontent.com/1539812/27145558-8ddeaff0-5136-11e7-9a99-1fae73fb8485.png)

**Comment by mattsarett** [comment]
I'm not as familiar with the code at the Dart level.  We do need to be consistent there, and I think I see at least one bug.  `static Color lerp(Color a, Color b, double t)` is not doing a correct linear interpolation.

As far as this example, I think we're almost on the same page, but this still seems to me to be working as intended.

I should have been more clear - the alpha value is always linear, but the red, green, and blue values are typically encoded with a transfer function.  Because the alpha value is always linear, scaling the alpha value linearly makes sense.

The reason that the middle column does not match is that 0xFF808080 is not 50% gray.  Given that the color channels are encoded with a transfer function, 0x80 corresponds to about 22% brightness.

**Comment by Hixie** [comment]
@vlidholt `Color.withOpacity` just sets the opacity to the specified opacity, which seems fine to me. Similarly `Colors.white12` is just white (0xFFFFFFFF) with a 12% opacity applied (0x1FFFFFFFF), it's not "12% gray", which again seems correct to me. The greys are [Colors.grey](https://docs.flutter.io/flutter/material/Colors/grey-constant.html) and they haven't changed with the color correction work as far as I can tell, they're entirely opaque and match the Material design color values.

@mattsarett Please file a separate bug to track the `Color.lerp` issue, documenting how you would like it to work.

**Comment by tvolkert** [comment]
FYI, https://github.com/flutter/engine/commit/ffe8181ffe7432b61a67323c80fd8025704e4695 is being reverted because it's been implicated in iOS crashes and in https://github.com/flutter/flutter/issues/10617 -- so this means the text lightness will revert to its previous behavior *at least temporarily*

**Comment by tvolkert** [comment]
> did this show up in image diffs?

Closing the loop on this - we now have an image diff test in Google's automated test infrastructure that would have alerted us to this UI change.

**Comment by sethladd** [comment]
What's the status of this? Did we revert the change?

**Comment by Hixie** [comment]
My understanding is that the current status is that what we do today is correct.

**Comment by ds84182** [comment]
Shouldn't the text opacities be changed to brightness instead? [The Material Design guidelines gives percentages](https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines), which can be interpreted as opacity values, but can also be interpreted as a coefficient of brightness. Normally, alpha values JustWork(TM), but with the Skia changes they don't JustWork(TM) anymore.

> Let's take the example of blending 0x80ffffff on to 0xff000000.
> (1) First we convert the pixel component values to linear. This is trivial, since the curve has end points at 0 and 1. We get [1.0, 1.0, 1.0] and [0.0, 0.0, 0.0].
> (2) Now we blend using alpha (alpha is always a linear value). We get [0.5, 0.5, 0.5].
> (3) Finally, convert those values back to sRGB encoded bytes. We get [0xBC, 0xBC, 0xBC].
> 
> The result of blending without taking the transfer function into account is trivially [0x80, 0x80, 0x80]. Note that 0x80 actually corresponds to a linear value of about 0.22. So if we fail to take the transfer function into account, the result of blending 50% white onto black is an actual screen brightness of only 22%.

If a blend with an alpha of 0.54 gives 30% screen brightness instead of 54% screen brightness that means that all Material Design Captions and Displays are being render half as dark (or bright, depending on theme). Also a blend with an alpha of 0.87 gives ~60% screen brightness instead of 87% screen brightness.

To fix this, we need something that allows Flutter developers to get an alpha value that darkens or brightens something by screen brightness, ensuring that text rendered on different types of screens maintain the same amount of contrast. Otherwise all text rendered by Flutter will be inconsistent across devices and emulators.

Also, native applications on Android properly use 87% and 54% of screen brightness. Flutter's text is WAY too light compared to them, and they're both supposed to be showing the same values.

**Comment by Tobiaswk** [comment]
Sorry to bump this. So this new color rendition is here to stay? Just want confirmation on what to do... because my apps render very bright compared to what they used to.

**Comment by eseidelGoogle** [comment]
I believe this is as of yet an unresolved discussion with the Skia team.  @cbracken can you pick this up since @chinmaygarde is OOO and discuss with the Skia team when we are next scheduled to meet with them in 2 weeks?

**Comment by Hixie** [comment]
@cbracken Probably we should discuss this with the Material team more than the Skia team, I believe the Skia team's explained the cause sufficiently and it's understood to be intentional (and more "correct").

**Comment by cbracken** [comment]
@Hixie that's also my understanding from the previous discussions. I'll follow up in person on Monday.

**Comment by vlidholt** [comment]
What's the status of this? I'm pretty indifferent to how this is solved, but text is currently still way too light in the bright theme. This includes the Flutter gallery in its latest version. Compare it to some native Android apps, and you'll see a big difference.

**Comment by vlidholt** [comment]
So, this is considered to be more "correct". I don't care too much about the math behind it, and it may very well be. But I can say for sure it's not what users will expect. I made a comparison with Photoshop, HTML, old Flutter, and new Flutter. When users draw 50% opaque black, they are expecting to get roughly a 50% gray. Keep in mind that most designers use programs like Photoshop to design user interfaces and it's a lot easier if things works in a similar fashion when it comes to colors.

This is a visual comparison of different programs and frameworks:
![flutter-colors](https://user-images.githubusercontent.com/1539812/31565747-01140c5a-b036-11e7-8748-8a7933392f85.png)

@Hixie @cbracken @HansMuller

**Comment by eseidelGoogle** [comment]
Thank you @vlidholt we just reached out to the Material team this morning and I expect will know more next week.  @HansMuller is driving this to resolution.

**Comment by HansMuller** [comment]
@vlidholt We're hoping to get some guidance about this from the Material team on Tuesday.

**Comment by brianosman** [comment]
@vlidholt One quick note - Photoshop can be used in this same mode, if you want. 'Edit -> Color Settings...' Then, under 'Advanced Controls', set 'Blend RGB colors Using Gamma: 1.0', and 'Blend Text Color Using Gamma: 1.0'. Sadly, even with these settings, gradients are still interpolated incorrectly. Switching to 32 bits/channel mode does switch to linearly interpolated gradients, though.

**Comment by HansMuller** [comment]
Still no input from the Material team. I suppose if we don't get any guidance in the next couple of days, I will  have to forge ahead. 

We could change the values of the predefined "black with n% opacity"  constants like Colors.black54 so that they appear as they did before (https://github.com/flutter/flutter/issues/10655#issuecomment-308298583)  and leave Color.withOpacity() as it is, since the current definition is at least easily understood.

**Comment by ds84182** [comment]
I think I got a lead in this. The colors we have right now are correct for sRGB but not linear RGB. It all comes down to the blending equation used on GPUs. The standard blending equation is `(colorA * (1.0 - alpha)) + (colorB * alpha)`, where colorA is the color in the frame buffer and colorB is the color being drawn.

However, since sRGB isn't linear, the inverted alpha (1.0 - alpha) isn't equivalent in both color spaces. 26% black is actually supposed to dim a color by ~49%, but when we switched to linear colors 26% black started dimming the color by 26%, making text illegible.

I have a solution for dark text currently [here](https://dartpad.dartlang.org/3faf7797cf18ff6ed84cef974567ae7d). alphaCorrect only works when you're blending the color black onto any other color though.

I can make a PR where I put all the light theme text color constants (and Colors.black<x>) through this function. Text should go back to their pre-color-correct values.

**Comment by eseidelGoogle** [comment]
@chinmaygarde do we know who the right person to engage with this from Skia's side is?

**Comment by brianosman** [comment]
... that would be myself and Mike Klein. The alphaCorrect function linked above does correct for blending black, but the math varies depending on the source color...

**Comment by eseidelGoogle** [comment]
My understanding from our meeting with Skia just now was that @chinmaygarde planned to drive this to resolution in the coming week(s).  Woohoo!

**Comment by Hixie** [comment]
> alphaCorrect only works when you're blending the color black onto any other color though.

That's problematic; there are parts of the Material spec where we only know that we want to apply a particular opacity. Maybe we should move back to sRGB?

**Comment by brianosman** [comment]
Yes. Skia has facilities for doing gamut correction (to account for wide-gamut displays), but still use nonlinear blending. Chrome is now using that functionality, as is Android. This also matches the behavior of other platform APIs and browsers. I'll be preparing a PR that uses Skia in this way (though I'd like to leave an option for apps to select linear blending).

**Comment by toferl** [comment]
The blending update seems to have caused a strange side-effect on iOS. The new blending (higher contrast) seems to be applied only when painting from raster cache, but not otherwise. Since the composer puts pieces in and out of the cache at its own discretion time to time, this results in semi-transparent UI elements blinking lighter and darker, especially when animations happen.

This is easily reproducible on current master head with the demo (tap counter) app:

1. Run the app
2. Note the color of the big “0” (too bright)
3. Long-tap the (+) FAB so that tooltip appears
4. Dismiss the tooltip by tapping anywhere
5. The moment the tooltip is dismissed, “0” becomes darker (the non-linear blending) 

If you enable `checkerboardRasterCacheImages: true`, you can observe that the color switch coincides with the checkerboard appearing on the scaffold’s body.

**Comment by brianosman** [comment]
Is this on a specific device? I've tried to reproduce this on an iPad Air, and on the simulator (iPhone 6), with no luck. I've seen the artifact you're describing while I was making the blending update, but I'd expect (and always observed) that the change to ios_gl_context.mm fixes it.

**Comment by eseidelGoogle** [comment]
@toferl or @brianosman would you be willing to open a new bug?  If true, this sounds like a bad regression we should mark TODAY (blocks further releases) and work to address ASAP.

**Comment by toferl** [comment]
@brianosman I'm reproducing it on Simulator. Don't have an iOS device at hand to check.

For simulator, it's latest Xcode 9.1 (9B55), iOS 11.1 simulator.

Now I'm starting to think it might be related to the specific graphics card I have, since it might be GPU specific (this doesn't happen in Android emulator for me though, and I think it also uses the host's GPU). If it doesn't repro on actual devices, it may be fine to have this glitch in a simulator on a mac.

@eseidelGoogle I'm hesitant to open a bug since I'm not sure if actual devices are affected, or just some development environments.

**Comment by eseidelGoogle** [comment]
@toferl don't ever hesitate to open a bug. :)  We would *much* rather have a bug and close it later, than to never hear about an issue affecting our users.

**Comment by toferl** [comment]
@eseidelGoogle opened #13308

**Comment by brianosman** [comment]
Ok. I'll update my environment on Monday, and see if I can repro. What
video card do you have in your Mac?

On Dec 1, 2017 4:22 PM, "toferl" <notifications@github.com> wrote:

@eseidelGoogle <https://github.com/eseidelgoogle> opened #13308
<https://github.com/flutter/flutter/issues/13308>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/10655#issuecomment-348617530>,
or mute the thread

**Comment by toferl** [comment]
It's a MacBook Pro which has two (one built-in). I'm not sure which one is used by Simulator.

```
  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3```
