### ISSUE TITLE
[Feature Request] Support for more customisation on overlay widgets

### ISSUE THREAD

**Issue by preetshah21699** [flutter/flutter#106634]
Hi all.
I am trying to make an app like [this](https://play.google.com/store/apps/details?id=com.hiruffy.controller) one. 

I tried to use [this](https://pub.dev/packages/system_alert_window)  widget.

But the widget is not customisable and only supports a few options.

I want to add animated widgets.

Is there any alternative or is there any work going on for this?

I am not good enough yet to contribute to it. But I would like to see something like this made.

Thank you.

**Comment by exaby73** [comment]
Hello @preetshah21699. Flutter follows the [Material specification](https://material.io/). Within it, there is no requirement for such a widget or functionality. Unfortunately, you'd need to implement this by yourself. This does not seem like a suitable feature request. 

You can probably start by diving into the source code of the package you are currently using and reverse engineer it. But since this is an invalid feature request, I am closing this issue.

**Comment by preetshah21699** [comment]
Hi Nabeel.

Thank you for the reply. I understand. Do you have any other suggestions apart from this that could help me?

Reverse engineering the package might be an option. But I am not sure if it is viable.

Thank you.

**Comment by exaby73** [comment]
@preetshah21699 I think reverse engineering the package or forking it is your best bet here.
