### ISSUE TITLE
First Where in list problem

### ISSUE THREAD

**Issue by bruzzers** [flutter/flutter#106662]
Hi, i propose to flutter to edit list.firstWhere() function with a nullable return. 

This because as dev i have to create a constructor of the list to use orElse method, and if i forget the orElse the app stop working if can't find the element. 

the implementato will be:

E firstWhere(bool test(E element), {E orElse()?}) {
    for (E element in this) {
      if (test(element)) return element;
    }
    if (orElse != null) return orElse();
    throw IterableElementError.noElement();
  }

E? firstWhere(bool test(E element)) {
    if(element in this){
      if (test(element)) return element;
    }else{
       return null;
    }   
  }

or something like that.

Thank you

**Comment by exaby73** [comment]
Hello @bruzzers. Thanks for filing this feature request. You are expected to use the official [collection](https://pub.dev/packages/collection) package's [`firstWhereOrNull`](https://pub.dev/documentation/collection/latest/collection/IterableExtension/firstWhereOrNull.html) method. Since this is not a valid feature request, I am closing this issue.
