### ISSUE TITLE
[go_router] Passing debugLogDiagnostics: false clears my log listeners

### ISSUE THREAD

**Issue by qoob23** [flutter/flutter#106653]
I register my log listener at startup of my app using package:logging. However when `GoRouter` is created at first build, it clears all listeners including my own.

Such behaviour produces two issues:
1. Setting `debugLogDiagnostics: true` doubles all logs produced by `GoRouter`
2. Setting `debugLogDiagnostics: false` disables my own logs

The only workaround that I found is to instantiate `GoRouter` on top of `main()`, however such behaviour is still confusing.

I think the solution here would be to use `Logger.detached()` for GoRouter

The issue was introduced in #99115

**Comment by exaby73** [comment]
Hi @qoob23 , please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by qoob23** [comment]
Hi @exaby73!
<details>
  <summary>Here's output of `flutter doctor -v`:</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-RU)
    • Flutter version 3.0.2 at /Users/svetozar/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
    • Pub download mirror https://pub.dev/

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/svetozar/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 13F40979-8CA1-4678-9D51-D760C057CE38 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64 • macOS 12.2.1 21D62 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>


<details>
<summary>And here is a minimal, reproducible example:</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:logging/logging.dart';

final _localLogger = Logger('Local');

Future<void> main() async {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen(print);
  runApp(const App());
}

GoRouter createRouter() => GoRouter(
      debugLogDiagnostics: false,
      routes: [
        GoRoute(
          path: '/',
          builder: (context, state) => const HomePage(),
        ),
      ],
    );

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final router = createRouter();
    return MaterialApp.router(
      routeInformationProvider: router.routeInformationProvider,
      routerDelegate: router.routerDelegate,
      routeInformationParser: router.routeInformationParser,
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
    _localLogger.info('initState');
  }

  @override
  Widget build(BuildContext context) {
    _localLogger.info('build');
    return const Scaffold(
      body: Center(child: Text('Hello!')),
    );
  }
}
```
with `debugLogDiagnostics: false` expected output is
```
flutter: [INFO] Local: initState
flutter: [INFO] Local: build
```
but actual output is empty

with `debugLogDiagnostics: true` expected output is
```
[GoRouter] known full paths for routes:
[GoRouter]   => /
[GoRouter] setting initial location null
[GoRouter] MaterialApp found
flutter: [INFO] Local: initState
flutter: [INFO] Local: build
```
but actual output is:
```
flutter: [INFO] GoRouter: known full paths for routes:
[GoRouter] known full paths for routes:
flutter: [INFO] GoRouter:   => /
[GoRouter]   => /
flutter: [INFO] GoRouter: setting initial location null
[GoRouter] setting initial location null
[GoRouter] MaterialApp found
flutter: [INFO] GoRouter: MaterialApp found
flutter: [INFO] Local: initState
[Local] initState
flutter: [INFO] Local: build
[Local] build
```

</details>

In my case it is a Provider from riverpod which creates a router on the first build.

**Comment by exaby73** [comment]
I can reproduce this issue. The issue here is that `go_router` itself uses `logging` under the hood. The constructor calls the `setLogging` method, which called the `log.clearListeners()`. 

https://github.com/flutter/packages/blob/af73d9905e3488d8bb78d749523d51008274e0f6/packages/go_router/lib/src/logging.dart#L10-L21

In the logging package, `clearListeners()` does call `root.clearListeners()` on a certain condition. I believe that is what is causing your listeners to get cleared since you are listening on `Logger.root`

https://github.com/dart-lang/logging/blob/f6979e3bc3b6e1847a08335b7eb6304e18986195/lib/src/logger.dart#L146-L153

I guess the way to combat this for now is to initialize your listeners after `GoRouter` is initialized. Else listen on `_localLogger ` instead or create your own global `root` logger instance.

**Comment by exaby73** [comment]
I agree. You could take it upon yourself and submit a PR if you like. You're most welcomed to :)

**Comment by ycherniavskyi** [comment]
For sure, using `Logger.detached()` is a bad idea because in such a case, `go_router` logging is removed from the logging hierarchy.

What about just deleting this line - https://github.com/flutter/packages/blob/35b000ad28e8ea267be4c95274d98355f2190b16/packages/go_router/lib/src/logging.dart#L19.
I, in fact, can't understand its meaning.

But as for me whole `debugLogDiagnostics` logic (with custom log listener) is redundant. The main thing is that `go_router` uses `logging` library, and the user could configure its output (with or without `hierarchicalLoggingEnabled`) in the way they need it.

For any of my proposals, I could create PR.
