### ISSUE TITLE
A subset of Devicelab Mac/ios testbeds are missing `ideviceinstaller`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106770]
Went through prod pool. Here are the bots that are missing `ideviceinstaller`:

Intel bots: Mac-25, 26

These testbeds may not be connecting correctly with salt.

**Comment by keyonghan** [comment]
This is causing device doctor recovery failure:
```
111 2022-06-28 22:40:55.256 E: device doctor recovery error: b'Unhandled exception:\nideviceinstaller not found.\n#0      fail (package:device_doctor/src/utils.dart:35)\n#1      getMacBinaryPath (package:device_doctor/src/utils.dart:150)\n<asynchronous suspension>\n#2      IosDevice.uninstall_applications (package:device_doctor/src/ios_device.dart:229)\n<asynchronous suspension>\n#3      IosDevice.recover (package:device_doctor/src/ios_device.dart:194)\n<asynchronous suspension>\n#4      IosDeviceDiscovery.recoverDevices (package:device_doctor/src/ios_device.dart:83)\n<asynchronous suspension>\n#5      main (file:///opt/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:73)\n<asynchronous suspension>\n'
```

**Comment by yusuf-goog** [comment]
Looking into these hosts.

**Comment by yusuf-goog** [comment]
mac-25 just applied all states correctly.

**Comment by yusuf-goog** [comment]
mac-26 just applied states correctly, and both still do not have `ideviceinstaller` command showing up.

looking into what installs that.

**Comment by yusuf-goog** [comment]
ideviceinstaller is now installed on mac-25,26.

Ran `brew install ideviceinstaller` and rebooted the machine.

Possibly the state did not get applied, because there is a condition on existence of `idevice_id`, which seems to already be on the machine. Need to check if there is some other state that might be installing `idevice_id` first, or if there was some manual installation that was done earlier to install those separately.
