### ISSUE TITLE
Need a way to use `flutter ios --init` with a custom built flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1067]
Maybe it's as simple as changing one of the .xcconfig files?  Maybe dropping a new Flutter.framework onto your XCode?  Maybe this is just a documentation question?
https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS

This is only needed by those doing flutter framework/engine development.  However since we would like more of our core team to be living on the iOS workflows, this is blocking that.

I would like to completely deprecate the building-apps-via-ninja workflow.

@collinjackson ran into this.

**Comment by chinmaygarde** [comment]
Using the `flutter` tool with a custom built engine may be slightly awkward since the tools depend on the combined artifacts of multiple engine builds (device + simulator and their associated snapshotters). For developers working on the engine, https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS#3-running-your-flutter-project are the currently recommended guidelines.
