### ISSUE TITLE
`Mac native_platform_view_ui_tests_ios` has been failing consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106745]
This test `Mac native_platform_view_ui_tests_ios` was newly added to CI, but has been failing consistently. This is consuming bot resources.

One example build: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20native_platform_view_ui_tests_ios/91/overview

@hellohuanlin Could you help take a look? Shall we disable it for now?

**Comment by jmagman** [comment]
This is failing because the test needs Xcode to be installed, but it's not set up as a dependency.  See conversation at https://github.com/flutter/flutter/pull/105050#discussion_r896097939.

**Comment by zanderso** [comment]
Clicked on this today out curiosity. It is failing with "Task failed: DeviceException: No connected physical iOS devices found." What is the next AI for this test?

**Comment by hellohuanlin** [comment]
@zanderso working on it (with help from @keyonghan)

**Comment by jmagman** [comment]
The issue is that this was set up as a hostonly devicelab test since it's running on a simulator and not a physical device.  However the devicelab test harness requires a tethered device, or the device discovery will fail the test if there isn't a tethered device, or the right kind of tethered device.  

https://github.com/flutter/flutter/pull/108585 was a hacky attempt to set the android_sdk as a dependency in case the tethered device was an Android device, since it just doesn't matter as long as it's running on a Mac. However, that didn't work:
```
Task result:
{
  "success": false,
  "reason": "Task failed: DeviceException: No Android devices detected"
}
```
One of the below should happen for this test:
1. Be changed to run on a physical device
2. Be moved out of devicelab to `flutter_drone` since it doesn't need a tethered device, either to a tools integration test per https://github.com/flutter/flutter/issues/65790 or instead to a shard? Or somewhere else?

**Comment by jmagman** [comment]
> The issue is that this was set up as a hostonly devicelab test since it's running on a simulator and not a physical device.

Well this was totally untrue, I misremembered what this test is doing.  It _is_ trying to run on a physical device, and it's failing because it's set up to check for a tethered Android device.
https://github.com/flutter/flutter/blob/b00bfef3c14dee8b78bf94358fd64e61caf9a3cc/dev/devicelab/bin/tasks/native_platform_view_ui_tests_ios.dart#L36

So ignore everything from the last comment. 🙂 

The `.ci.yaml` entry should become something like
```
  - name: Mac_ios native_platform_view_ui_tests_ios
    bringup: true
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      tags: >
        ["devicelab", "ios", "mac"]
      task_name: native_platform_view_ui_tests_ios
```
Then the top of the test needs 
```
deviceOperatingSystem = DeviceOperatingSystem.ios;
```

**Comment by hellohuanlin** [comment]
This is fixed. Looks like dashboard still shows flaky, but when i go into the log it shows not flaky.
