### ISSUE TITLE
SelectionArea handles swap order on Android

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#106705]
On native Android, it's not possible to drag one selection handle past another.  Flutter seems to get this right in EditableText but not in SelectionArea.  This is the incorrect behavior:

![out](https://user-images.githubusercontent.com/389558/176051550-dbd66c76-600a-41ad-9909-abd789c5ad1a.gif)

This does seem to be the correct behavior on iOS, though.

### Steps to reproduce

  1. Run an app with some Text in a SelectionArea, such as below, on an Android device.
  2. Select some text.
  3. Grab either handle and try to drag it past the other handle, reversing the selection.

Expected: The handle stops before passing the other handle.
Actual: The handles reverse order.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: SelectionArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('Select me and try to drag past a handle'),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by nt4f04uNd** [comment]
> On native Android, it's not possible to drag one selection handle past another. 

It doesn't seem right, I've never seen this behavior. Could it be a case you were using some custom ROM that doesn't allow this?

Here what it looks like in native Android, and it actually seems a bug that EditableText prevents from doing that.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/39104740/183291739-e91a5ff2-3636-4313-b0a5-545e14e89089.mp4

</details>

**Comment by nt4f04uNd** [comment]
The video from above is from Android 11.

Wow, I just checked it on my phone and it doesn't allow swapping. It seems like they changed that for Android 12, but what's even more interesting is that it also allows swapping in selectable text, which makes it consistent with Flutter, haha!

I wonder, if that's a bug, though, because swapping handles is what has always been a feature of Android inputs and selections, and not allowing it seems to make UX a bit worse.

<details>
<summary>Android text video</summary>

https://user-images.githubusercontent.com/39104740/183600904-cc051f4a-a926-432f-befe-085451ecacad.mp4

</details>

<details>
<summary>Android inputs video</summary>

https://user-images.githubusercontent.com/39104740/183600961-eef7fdba-ff1b-4da2-a19b-3323ab51f318.mp4

</details>

**Comment by justinmc** [comment]
Well alright haha.  I guess I'll close this issue, but I'll keep an eye out for this and see if it changes again on native Android.

FYI @chunhtai

**Comment by chunhtai** [comment]
There is different behavior if you select on an editable text or non-editable text in native android. I think the current behavior in Flutter matches the Android behavior
