### ISSUE TITLE
Permission checker on Android side

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#10680]
Some Flutter plugins require adding user permissions to AndroidManifest.xml file. This might cause a issue that some permissions will not be used anymore after a while. For example, when removing some plugins from the app, the permissions may still stay in the manifest.

Can we have a script/tool to check weather there's unused permissions in AndroidManifest.xml file? Or just remove the unused permissions from 'AndroidManifest.xml' file?

**Comment by eseidelGoogle** [comment]
If someone has such a script we could just call out to it. :)  I'm not familiar enough with that detail of Android development to know.

**Comment by swissonid** [comment]
As far I understand you do not need such a script, because of the AndroidManfist.xml merge mechanisms during the building process. So, for example, your plugin need permission to the camera and you defined that permission in the AndroidManifest of your plugin. Wich is at the end an Android Libary. The permission from your lib should get removed from the App AndroidManifest on the next build.

**Comment by jiajiabingcheng** [comment]
The plugin user-permission will be added to the Flutter project's manifest manually with the import of the plugin API. Therefore after the plugin is removed, during the building process, the permission should still be there.

**Comment by Hixie** [comment]
The way we do it now, the plugins specify their permissions and we merge them in, so removing a plugin removes the permission too.

Closing as unnecessary.
