### ISSUE TITLE
Flutter on TV: remote 'enter' button not considered as a tap/press

### ISSUE THREAD

**Issue by neckaros** [flutter/flutter#106817]
## Use case

I embrace the concept of multi platform with Flutter and did a Android TV version. The issue is that main button of the remote control ('enter' button?) is not considered as a tap in flutter.

The fix you can do is have a Shortcuts at the top of your app:
```dart
Shortcuts(
        shortcuts: <LogicalKeySet, Intent>{
          LogicalKeySet(LogicalKeyboardKey.select): const ActivateIntent(),
        },
```
this will trigger the onTap of a focused Button, Inkwell...

1) This is a pain to find when you don't know.
2) It does not allow you to do things like long press to display a popup menu

## Proposal

I would like the 'enter' button of the remote considered as a touch on the focused item

**Comment by maheshmnj** [comment]
Hi @neckaros, Thanks for filing the issue. Labeling this issue as a proposal.

**Comment by maheshmnj** [comment]
cc: @dkwingsmt

**Comment by dkwingsmt** [comment]
I don't think there's a way to trigger a key press to a tap, since they're completely different events and contain different information (for example, taps have locations, whereas key presses don't). I would suggest writing an article sharing your experience on what keys you should expect for certain keys on the remote controller (theoretically this can be part of the Flutter doc or tutorials, but we don't have enough data, and I wonder if all remotes share the same button mapping.)

There are easier ways to experiment the key mapping: call `HardwareKeyboard.instance.addHandler` and you'll receive all key events regardless of focus. Of course, after you figure out all buttons you should still use `Shortcuts` to configure the action, since they offer some checks that you wouldn't normally include in bare key event callbacks.

I agree that long pressing is missing feature and it's technically impossible to simply add based on the current structure of `Shortcuts`. It's on my radar and I'll think about it in the future.

**Comment by dkwingsmt** [comment]
> #43719 also relate to this feature request

That's a good point. I wasn't aware of this. Thank you for pointing out.

**Comment by mossmana** [comment]
@mariamhas Is there a tracking project for Android TV that this could be added to? I'm also trying to find this issue an owner. It's not clear if it should belong on the Flutter Android or Flutter Framework team.

**Comment by dkwingsmt** [comment]
Are there still anything to do for this issue? To confirm:
* Map a key press to a tap event: Not planned.
* Handling long pressing a key: See https://github.com/flutter/flutter/issues/106853
* Including `LogicalKeyboardKey.select` as one of the "OK" keys: We could do, but need more discussion and I recommend discussing in a separate issue.

**Comment by mariamhas** [comment]
We currently don't have a project for Android TV or plans to support the platform officially. If this issue is resolved, but there are still the three remaining issues that @dkwingsmt mentions in the previous comment, we should file new issues for each one

**Comment by mossmana** [comment]
The work being done for https://github.com/flutter/flutter/issues/1670 may address this issue.
