### ISSUE TITLE
flutter build aar no work

### ISSUE THREAD

**Issue by CoderCaiSL** [flutter/flutter#107004]
i create flutter plugn demo  and run build aar , i want to get the aar for my android . but is dont work

![image](https://user-images.githubusercontent.com/19733678/177007915-ce6750fd-73b3-49e7-adb2-e4ce753cdd5a.png)

**Comment by huycozy** [comment]
Hi @CoderCaiSL 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

In particular, please provide reproduction steps, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v` so that we'll have enough details to investigate the issue.

Thank you!

**Comment by CoderCaiSL** [comment]
sorry，i supplementary instructions again
1、i create a flutter plugn project for android studio 
2、then i did not modify any code and build flutter aar 
3、it didn't get my expected result
![image](https://user-images.githubusercontent.com/19733678/177345886-89ca8723-bceb-40c5-b083-ccd6b2d6605b.png)
and this is my environment
![image](https://user-images.githubusercontent.com/19733678/177346647-675429f0-b18d-4c40-b711-f588e4ac91b9.png)

**Comment by huycozy** [comment]
> and my flutter module demo can build aar successfully but flutter plugin build failed

@CoderCaiSL Could you provide detailed reproduction of this failure? (step by step, used commands, etc)

And it will be better if you could provide the log, and sample code in collapsed formatted mode ([instruction here](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)) or represent it as plain text instead of an image/screenshot so that we can directly copy/search information from that.
