### ISSUE TITLE
app is crash when app resumed or screen unlocked 

### ISSUE THREAD

**Issue by AjilAshok** [flutter/flutter#107213]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by AjilAshok** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.0, on Ubuntu 20.04.4 LTS 5.13.0-52-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by huycozy** [comment]
Hi @AjilAshok, 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output logs (stack trace/exception) so that we may verify this. 

Also, I can see from your `flutter doctor` output that you are using the old Flutter version, the latest Flutter stable is `3.0.4` and the master is `3.1.0-0.0.pre.1524`. Please try upgrading them and retry to see if this issue still reproduces.

Thank you!
