### ISSUE TITLE
SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64)

### ISSUE THREAD

**Issue by sitakanta136** [flutter/flutter#107231]
* Login not working even app connected with wifi.
* http.post(),throws Exception SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64).
* When I kill the app and open it again, Login works fine.
*  InternetAddress is IPV4 format 

  Observation:
  InternetAddress is IPV6 format  - not working case.

**Comment by huycozy** [comment]
Hi @sitakanta136 
Please see this StackOverflow answer for more details https://stackoverflow.com/a/60464649/5921933

If the answer doesn't help to solve the issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by huycozy** [comment]
Hi @sitakanta136 
Please see this StackOverflow answer for more details https://stackoverflow.com/a/60464649/5921933

If the answer doesn't help to solve the issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by sitakanta136** [comment]
Hi  huycozy,

Internet permission has already been added to the manifest file.
Check the blow logs.
Connectivity -result = [InternetAddress('2404:6800:4009:80f::200e', IPv6), InternetAddress('142.250.183.206', IPv4)]
[log]  ** Connectivity - internetAddress= 2404:6800:4009:80f::200e
[log]  ** Connectivity - internetAddress changed= 2404:6800:4009:80f::200e
[log]  ** Connectivity - Mobile network - Online

Whenever we try to log in, I am getting the below issue Please refer above code.

 Exception SocketException: Connection failed (OS Error: ### Machine is not on the network, errno = 64).
