### ISSUE TITLE
How to trace errors in methods in .dart files after compiling codes for web environment

### ISSUE THREAD

**Issue by mamaly12** [flutter/flutter#107450]
Hi,
I have a question which is how can I debug my methods defined in dart files after compiling codes and publishing them as a web application to the production server?

for example, I have a private _incrementCounter function:
```
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
```
I want to set a debug pointer in my browser to debug its behavior in my production server. How can I do that? If I understand correctly, .dart files are compiled to .js files for web applications, where do the functions and classes inside the .dart files go and how can they be debugged?

**Comment by exaby73** [comment]
You can use the [`debugger`](https://api.dart.dev/stable/2.17.5/dart-developer/debugger.html) method which compiles to the JS [`debugger`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) statement. 

Since this issue does not describe a bug or feature request in Flutter, I'm closing it. If you have any other questions, you can get better help in communities on Reddit or StackOverflow. Thank you

**Comment by mamaly12** [comment]
Thank you @exaby73
