### ISSUE TITLE
Tear down the GL context when going to background

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#107597]
Flutter holds on to the GL surface and context when going to the background.

This is disadvantageous for add-to-app scenarios where e.g. a fragment is shown briefly and then not shown again for a long time.

**Comment by jason-simmons** [comment]
What resources are we holding onto that can be safely deleted in this situation?

`NotifyDestroyed` will call `eglDestroySurface` for the on-screen surface.  However, the EGL context used for on-screen rendering is part of a share group with the EGL context used by the IO thread.  The resources shared between these contexts will remain active as long as the engine is alive.

The lifecycle of the Skia `GrDirectContext` is complex due to support for groups of engines that share the same `GrDirectContext`.  Dropping the `PlatformViewAndroid`'s reference to its `AndroidContext` at `NotifyDestroyed` time will be unsafe.

Is the `GrDirectContext` holding onto anything that is unnecessary but is not already being freed when the engine calls the `GrDirectContext` purging APIs?

**Comment by dnfield** [comment]
Ahhh ok. That makes sense.

What @xster reported is that even pumping some empty scene and clearing the image cache (and flutter_svg's cache) to try to flush the UI after going to background was retaining graphics memory.

**Comment by xster** [comment]
Correct. Let me know if there's more debugging data I can get besides meminfo. Clearing the widget tree definitely had the biggest impact. But this patch also cleared some additional graphics memory.

**Comment by dnfield** [comment]
As I think about this more, I think we want something less destructive - it'd sitll help if we could get a heap snapshot after the UI goes away to see if there are any graphics retaining Dart objects around (e.g. Picture, Image, Paragraph).

**Comment by xster** [comment]
I can't remember if we had a discussion offline about this before or after the last comment. But a heap dump after looks like this:

![image](https://user-images.githubusercontent.com/156888/188247757-06b8477a-dfc1-4bcf-bc89-81a45ab6ec13.png)

There are no remaining graphics element afaict

**Comment by chinmaygarde** [comment]
Traige: Per Dan, closing this as stale.
