### ISSUE TITLE
Emoji Missing Color on Pixel Phones

### ISSUE THREAD

**Issue by kulture-rob-snider** [flutter/flutter#107538]
## Steps to Reproduce

1. Execute `flutter run` on the code sample using an Pixel emulator and Flutter 3.0.4

**Expected results:**
I would expect the Recycle emoji on the first line to be colored green like the one on the second line. When downgrading to 2.10.5, the emoji renders correctly.

**Actual results:**
On line 1, when by itself, the recycle emoji is black.

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const [
              Text('♻️'),
              Text('🏴󠁧󠁢󠁳󠁣󠁴󠁿♻️'),
            ],
          ),
        ),
      ),
    ),
  );
}
```

</details>

<details>
<summary>Logs</summary>

```
Analyzing untitled1...                                                  
No issues found! (ran in 0.9s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @kulture-rob-snider, thanks for filing the issue.
I can reproduce this issue on the latest stable `3.0.5` channel and the same on `2.10.5` with both Pixel physical and emulator.

<details>
<summary>Demo</summary>

| Pixel 3.0.5 | Pixel 2.10.5 | Samsung | 
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/178911983-a99f2960-749f-41a5-9e91-f2d5c05f9532.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/178912112-3b224b08-2f4a-469e-a1b6-9984ec7cd32b.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/178912217-4e4cbdd3-ec53-4440-9151-01ef639c7f69.png">

</details>

But as your description, the emoji renders correctly on `2.10.5`. Could you please retry one more time and confirm this?
Also, what's your current Android OS version?

**Comment by jason-simmons** [comment]
If the font specified in the `TextStyle` does not handle a particular character, then the Flutter engine needs to search the host system for another font that can render that character.

In this case, multiple fonts on the Android device provide the recycle symbol.  For the string containing only that character Flutter selects the NotoSansSymbols font, which renders it in black.

The second string starts with a character that is not available in NotoSansSymbols. The engine selects NotoColorEmoji for that character.  NotoColorEmoji also includes a color version of the recycle symbol, so that glyph is then used for the recycle character.

If you need control over how these characters look, then embed the desired font into your application and select that font family in the `TextStyle`.
(see https://docs.flutter.dev/cookbook/design/fonts)
