### ISSUE TITLE
Scenario App Integration Tests on  Linux Android Emulator Tests  are flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107667]
Over the past day or two, these tests have become very flaky.

<img width="1484" alt="Screen Shot 2022-07-14 at 12 55 21 PM" src="https://user-images.githubusercontent.com/6343103/179071988-7465030a-e4f9-4337-99d4-969d6cd8026c.png">

Here is an example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Emulator%20Tests/434/overview

I'm having trouble parsing the error out of the logs. Maybe @dnfield can read them? cc @GaryQian this week's engine sheriff.

**Comment by GaryQian** [comment]
Cc @ricardoamador

**Comment by dnfield** [comment]
SurfaceFlinger is crashing when it tries to allocate an absurdly large buffer:

```
 [stdout] 07-14 10:37:21.018  6720  6781 E BufferQueueProducer: [SurfaceTexture-0-6720-15](id:1a400000005d,api:1,p:431,c:6720) dequeueBuffer: BufferQueue has been abandoned
 [stdout] 07-14 10:37:21.018   431   431 E CompositionEngine: ANativeWindow::dequeueBuffer failed for display [flutter-vd] with error: -19
 [stdout] 07-14 10:37:21.018   431   431 W CompositionEngine: Dequeuing buffer for display [flutter-vd] failed, bailing out of client composition for this frame
 [stdout] 07-14 10:37:21.018  6720  6781 E BufferQueueProducer: [SurfaceTexture-0-6720-16](id:1a400000005e,api:1,p:431,c:6720) dequeueBuffer: BufferQueue has been abandoned
 [stdout] 07-14 10:37:21.018   431   431 E CompositionEngine: ANativeWindow::dequeueBuffer failed for display [flutter-vd] with error: -19
 [stdout] 07-14 10:37:21.018   431   431 W CompositionEngine: Dequeuing buffer for display [flutter-vd] failed, bailing out of client composition for this frame
 [stdout] 07-14 10:37:21.019  6720  6781 E BufferQueueProducer: [SurfaceTexture-0-6720-17](id:1a4000000063,api:1,p:431,c:6720) dequeueBuffer: BufferQueue has been abandoned
 [stdout] 07-14 10:37:21.019   431   431 E CompositionEngine: ANativeWindow::dequeueBuffer failed for display [flutter-vd] with error: -19
 [stdout] 07-14 10:37:21.026   431   431 W CompositionEngine: Dequeuing buffer for display [flutter-vd] failed, bailing out of client composition for this frame
 [stdout] 07-14 10:37:21.026  6720  6781 E BufferQueueProducer: [SurfaceTexture-0-6720-18](id:1a4000000068,api:1,p:431,c:6720) dequeueBuffer: BufferQueue has been abandoned
 [stdout] 07-14 10:37:21.027   431   431 E CompositionEngine: ANativeWindow::dequeueBuffer failed for display [flutter-vd] with error: -19
 [stdout] 07-14 10:37:21.027   431   431 W CompositionEngine: Dequeuing buffer for display [flutter-vd] failed, bailing out of client composition for this frame
 [stdout] 07-14 10:37:21.032   367   410 E android.hardware.graphics.allocator@3.0-service: allocateCb:390 failed with 'Error3::NO_RESOURCES'
 [stdout] 07-14 10:37:21.043   431   456 E GraphicBufferAllocator: Failed to allocate (37500 x 150000) layerCount 1 format 1 usage b33: 5
 [stdout] 07-14 10:37:21.044   431   456 F SurfaceFlinger: captureScreenCommon: Buffer failed to allocate: 5
```

That's causing the app to crash. Then, later, the app is failing to uninstall and failing CI.

There are two problems here:

- Sucessful runs also have the app crash. Something is asking surface flinger to acquire a very large buffer, the device can't handle that, and the system crashes.
- Sometimes when the system crashes (and the test does not notice), it asks the system to uninstall the APK. My assumption here is that the flake is because sometimes the system has not recovered enough to actually perform the uninstall. We regard _that_ as a failure and fail the shard at that point.

**Comment by dnfield** [comment]
Ok. I believe I know what's happening here.

The `PlatformViewLargerThanDisplaySize` test was intended to cover new logic that Emmanuel added when relanding the virtual display stuff. That logic was reverted by @cyanglaz and @bparrishMines because it caused regressions. Now we have a test that tickles a hard crasher and messes up CI.

I think for now we need to disable that test.

**Comment by ricardoamador** [comment]
Thanks for taking care of that @dnfield .

**Comment by zanderso** [comment]
This was addressed by https://github.com/flutter/engine/pull/34675
