### ISSUE TITLE
Linux AOT via `flutter build bundle`

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#107762]
Building an application on a Linux machine using `flutter build bundle` is problematic.

1) The debug build will register and run the Linux Dart code.  Stuart Morgan has stated this is definitely a bug.  I'm building the bundle on Linux why would it not include Linux platform specific code?
2) Using the built bundle to create an AOT will drop the Linux Dart code, and the Linux specific Dart code is not executed.

When running `flutter build bundle` on a Linux machine (platform type is literally Linux), why would it not include the Linux specific Dart code?

Given `flutter build linux` is currently not capable of cross compiling, one cannot run `flutter build linux` and use the libapp.so (it's host only).

This is impacting developers targeting AGL Flutter.  We (AGL/Toyota) want support for Linux specific Dart when using `flutter build bundle` for both Debug images and AOT images.

We want `flutter build bundle` and AOT generation to build/run the Linux specific Dart code regardless of the native CMake stuff.

@Hixie @timsneath @cmc5788

**Comment by stuartmorgan** [comment]
> 1. The debug build will register and run the Linux Dart code.  Stuart Morgan has stated this is definitely a bug.  I'm building the bundle on Linux why would it not include Linux platform specific code?

I have answered this at length in both https://github.com/flutter/flutter/issues/103660 and our discussion in Discord. Capturing the core bit from the latter:

>> The thing that is not running is not "the Linux Dart code", it is the 1P-Linux-embedding-defined plugin registration function for the class that is declared in the 1P Linux embedding metadata for that plugin (in its pubspec).

Continuing to conflate "Linux-specific Dart" and "Flutter-1P-Linux-embedding-specific Dart" isn't constructive.

> We (AGL/Toyota) want support for Linux specific Dart

That support already exists; you can write Linux-specific Dart using `Platform.isLinux` checks.

If what you want is the ability to auto-generate Dart plugin registration code for your custom embedding, as I've said before we're happy to review designs for such a system, as part of the custom embedding hook support in the tool.

What you are specifically requesting here though, which is for your embedding to get Flutter-1P-Linux-embedding-specific Dart, is a wontfix.

**Comment by Hixie** [comment]
@jwinarske Thanks for filing the bug. For the record, @stuartmorgan is the TL for this area of the code so he's the one who should make the final call on this.

It sounds like there's an ambiguity in your request. We support several Linux-based platforms, for example Android and GTK. Plugins for different platforms are quite different (for example, plugins on Android are typically in Java, whereas on GTK they are in C!).

The core problem, I think, is that we don't yet have extensible logic in the tool so that you can easily add new platforms. We should definitely work on that. https://github.com/flutter/flutter/issues/25377 is where we're tracking that issue. You can discuss this in #hackers-tool on our Discord. As a heavy user of a custom embedding, you may be interested in getting involved in this work; we haven't really started on it in earnest yet but it is an area we are very interested in.

**Comment by jwinarske** [comment]
@Hixie Thanks for the constructive response, I'll look into the referenced issue and Discord channel.

**Comment by jwinarske** [comment]
Just a heads up.  This was a tooling issue.  Resolved in my AOT generation sequence:
https://github.com/meta-flutter/meta-flutter/blob/kirkstone/conf/include/flutter-app.inc#L228-L326

What I did uncover in my investigation to resolving this was that some apps worked fine with gen_snapshot obfuscation disabled, some did not.  The Flutter Package examples worked, while Gallery and Wonders did not.  Enabling obfuscation enabled Gallery and Wonders to work as expected.  I raised this on the hacker-tools discord channel.
