### ISSUE TITLE
Autosubmit not landing rolls

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107788]
This roll sat for 20 hours https://github.com/flutter/flutter/pull/107754

This engine -> framework roll also appears to be not getting landed. https://github.com/flutter/flutter/pull/107784

**Comment by keyonghan** [comment]
Another PR: https://github.com/flutter/flutter/pull/107835

Adding logs for triage: https://github.com/flutter/cocoon/pull/1987

**Comment by keyonghan** [comment]
The existing logic relies on pub/sub `pull` to process queued PRs.

The gcloud `pull` API does not return all undelivered messages each time.  It promises to return at most `maxMessages`, but it doesn't mean it always return `maxMessages`

I suspect the issue here is a combination of intermittent tree closures + the `pull` cron job missing the PR, but I am not 100% sure if this explains >10 hours waiting.

I updated the cronjob to run every 1 min from every 2 mins. This still needs an ongoing monitoring.

**Comment by zanderso** [comment]
@keyonghan Is it possible to revert back to the old 'waiting for tree to go green' bot while this is investigated?

**Comment by zanderso** [comment]
Bumping priority since Engine rolls are getting backed up on this due to the difficulty of manual monitoring.

**Comment by keyonghan** [comment]
@zanderso I see the bot has been working okay for today:
https://github.com/flutter/flutter/pull/107933
https://github.com/flutter/flutter/pull/107931
https://github.com/flutter/flutter/pull/107927

As for this one (you helped land minutes ago), the latency was due to ToT red.

I would prefer to keep the autosubmit bot for now as I don't see this happens on other PRs (though there shouldn't be any difference between engine roller PRs and any other ones).

I will do a manual monitoring of the engine rollers, and land any if unexpected latency happens.

**Comment by zanderso** [comment]
I had to land https://github.com/flutter/flutter/pull/107940 manually.

**Comment by keyonghan** [comment]
> I had to land #107940 manually.

Yeah, I saw that PR and has been monitoring: that latency is due to our tree red.

**Comment by keyonghan** [comment]
[Latest roll](https://github.com/flutter/flutter/pull/107947) finished all checks at 11:40, and was submitted at 11:42 by the bot.

Will keep monitoring.

**Comment by keyonghan** [comment]
Three more rolls landed <2 mins after tasks finished:
https://github.com/flutter/flutter/pull/107974
https://github.com/flutter/flutter/pull/107966
https://github.com/flutter/flutter/pull/107951

**Comment by zanderso** [comment]
Thanks for verifying. Lowering down to P3 and will help monitor.

**Comment by keyonghan** [comment]
Haven't seen any repros over past three days. Closing as fixed.
Please reopen if seeing this issue again.
