### ISSUE TITLE
[google_maps_flutter_web]Is there have a mothod to remove Symbol,remove line,circle,polygon...

### ISSUE THREAD

**Issue by BearnLee** [flutter/flutter#107898]
Is there hava an mothod to remove Symbol,remove line,circle,polygon...？

**Comment by huycozy** [comment]
Hi @BearnLee. It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
Closing for now.
