### ISSUE TITLE
Switch to ffi maybe caused changes in number of new gen gc collections?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107935]
In the Engine -> Framework roll here https://github.com/flutter/flutter/pull/107894, containing the conversion to FFI: https://github.com/flutter/engine/pull/34700, SkiaPerf is reporting changes in the number of new_gen_gcs that happen, some are up, some are down:

up: https://flutter-flutter-perf.skia.org/e/?begin=1658181964&end=1658237168&keys=X3e38dd551d395e0d59ce40376fca1897&num_commits=50&request_type=1&xbaroffset=29927

down: https://flutter-flutter-perf.skia.org/e/?begin=1658181964&end=1658237168&keys=Xfa3617edfb895f535d7aaf32ac0e1503&xbaroffset=29927 (as well as some build times)

The FFI change is the only one I can eyeball that I'm suspicious of. Are these changes expected? Are there any other changes in that roll that could explain the benchmark changes? @dnfield @jason-simmons

**Comment by dnfield** [comment]
There's a dart roll in there - I'm not sure how to read the diffs on those anymore, is it really just one change in there?

**Comment by dnfield** [comment]
Specifically https://github.com/flutter/engine/pull/34728

**Comment by dnfield** [comment]
@dcharkes do you have any ideas about this?

**Comment by dcharkes** [comment]
> @dcharkes do you have any ideas about this?

That does actually ring a bell in the context of Flutter. When we did measurements of migrating `dart:ui` to `@FfiNative`s from the old dart `native`s, our team observed similar jumps in old/new GC counts ([measurements dump including GC counts](https://docs.google.com/spreadsheets/d/11Zq0UassStHvUXkWhA1bE0nqfbO2epfek7wofuwCy7Q/edit?usp=sharing&resourcekey=0-P63R5aefKqiuOf0JBzX2Pw) see the "conv" tabs). Different benchmarks made both old and new GC jump in both directions.

I believe we did not investigate why the GC counts changed.

Some hypotheses:

* `dart:ffi` allocates more(?) short-lived objects by forcing boxing for `Pointer`s and `double`s because `lookup` and `lookupFunction` return closures and might be invoked as closure calls (which do not support unboxed arguments).
* `dart:ffi` allocates more(?) long-lived objects by having GCs happen during FFI calls promoting the objects to old space.
* Or, `dart:ffi` does a transition to a safe point (when not a leaf-call, for example when using Handles), which creates an opportunity (or many opportunities if many FFI calls) for the GC scheduler to start a GC.

These are just wild guesses. We would need to investigate what is going on.

Because we've seen these jumps in GC behavior before on measurements of an earlier version of the `dart:ui` migration, I'm inclined to think https://github.com/flutter/engine/pull/34700 is indeed the cause.

**Comment by mkustermann** [comment]
The switch from `native` to `@FfiNative` will - as @dcharkes points out - create `Pointer` objects on the callsite that will be immediately unboxed in callee (and become unreachable) before doing the C call. (In old `native`s this was instead done by passing an object to C code - which tonic layer would then unwrap via calling the Dart API to obtain the native field value / pointer)

There are some follow-up optimizations planned - see https://github.com/dart-lang/sdk/issues/43889 - that will end up avoiding these short-lived `Pointer` objects.

Though in general: Those objects are very short lived and therefore basically free to collect. Instead of counting the number of GCs, it would be better to look at the accumulated time spent on GCs. @dnfield Do you see any increase in actual time spent on GC?

To the other points of @dcharkes : Safepoint transitions, double boxing, etc is performed for old `native`s as well - so there's really not much difference (also not to the fact that GC can happen during execution of C code)

**Comment by dnfield** [comment]
I've filed a bug to make sure we're tracking GC timein all our benchmarks - today we're only tracking it in some.

**Comment by chinmaygarde** [comment]
If our existing benchmarks don't notice a change in the total time spent in GC, we should close this. The number of GCs does not matter.

**Comment by dnfield** [comment]
Unfortunately no existing benchmarks were recording GC time. We can fix this as part of https://github.com/flutter/flutter/issues/108049

**Comment by zanderso** [comment]
It looks like there are sufficient issues filed for the actionable parts of this issue, so I'm going to close this one, and we can track the others instead.
