### ISSUE TITLE
Adapt to variable system refresh rates on iOS

### ISSUE THREAD

**Issue by jefrrey017** [flutter/flutter#107902]
Since the users of my app with an iPhone 13 Pro started complaining that the app doesn't feel like 120Hz, I started to realize that my app was getting capped at 60Hz and never gets past it.  I tested whether the app was running on 120Hz after setting the `CADisableMinimumFrameDurationOnPhone` to true on `Info.plist`. But the app didn't run on the highest refresh rate available. So I manually configured my `AppDelegate.swift` like below such that the app always runs at 120Hz.

But this had led to immense battery drain on the devices as iPhones variably control the refresh rates based on the display activity. How can I configure the AppDelegate to adapt to variable system refresh rates?

After some web searches, I found this from Apple's developer documentation,
`displayLink!.preferredFrameRateRange = CAFrameRateRange.default`

Will setting this make my app forced to run at 60Hz again or would adapt to system refresh rates?

(I'm not an iOS developer so any help would be much appreciated)

``` import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  var displayLink :  CADisplayLink?
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
      displayLink = CADisplayLink(target: self, selector: #selector(displayLinkCallback))
      displayLink!.add(to: .current, forMode: .default)
      if #available(iOS 15.0, *) {
          displayLink!.preferredFrameRateRange = CAFrameRateRange(minimum:120, maximum:120, preferred:120)
      }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  @objc func displayLinkCallback(){

  }
}

**Comment by huycozy** [comment]
Hi @jefrrey017 Thanks for filing the issue. 
Can you please attach the timeline trace JSON file? You can find the instructions for it in this issue https://github.com/flutter/flutter/issues/74833

And try to provide as much information as possible: which functionality is affected, how to reproduce the issue, `flutter doctor -v` output, etc. So that, we'll have enough details to conclude on the issue.
Here are some of the filed issues that you can refer to:
- https://github.com/flutter/flutter/issues/90675
- https://github.com/flutter/flutter/issues/99151
- https://github.com/flutter/flutter/issues/101653
