### ISSUE TITLE
[video_player] Cannot play Videos from Application Support directory

### ISSUE THREAD

**Issue by albertkur** [flutter/flutter#107900]
`VideoPlayer.file` cannot play files from Application Support Directory on iOS. It gets stuck in the initialize call. and it will not throw any exception. but it can play videos from Application Documents Directory 

[Reproducable Code Sample](https://github.com/albertkur/video-player-flutter-bug)

change the `_downloadFile` function to use the `applicationDocumentsDirectory` and the video will get initialized

**Comment by danagbemava-nc** [comment]
Hi @albertkur, the issue you're facing is because there's a whitespace in the path name for the application support directory. 
This issue is known as and is being tracked in https://github.com/flutter/flutter/issues/51031. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
