### ISSUE TITLE
Running an Http request sometimes returns errro

### ISSUE THREAD

**Issue by Titanium2099** [flutter/flutter#107988]
## Steps to Reproduce

1. Running a Uri request sometimes returns an error

**Expected results:** getting data and parsing it from server
**Actual results:** http request does not run

<details>
<summary>Code sample</summary>

```dart
import 'dart:convert' as convert;

import 'package:http/http.dart' as http;

void main(List<String> arguments) async {
    var url =
        Uri.https('www.shattr.net', '/search.php', {'q': widget.SearchQuery});
    // Await the http get response, then decode the json-formatted response.
    var response = await http.get(url);
    if (response.statusCode == 200) {
      print(response.body);
      var jsonResponse = convert.jsonDecode(response.body);
      usersData = jsonResponse;
      isLoading = false;

      print(usersData);
    } else {
      print('error');
    } 
}

```

</details>

<details>
  <summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: FormatException: Missing extension byte (at offset 59847)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      Response.body
package:http/src/response.dart:28
#4      _searchState.getData
package:Shattr/Pages/Search.dart:42
<asynchronous suspension>
```

</details>

**Comment by exaby73** [comment]
Hello @Titanium2099. This is happening due to the data you are receiving from this URL not being a properly formatted UTF8 string. See [this stackoverflow thread](https://stackoverflow.com/questions/65762567/unhandled-exception-formatexception-unexpected-extension-byte-at-offset-5) for more information.

Since this is not a problem with Flutter itself, I am closing this issue. If you disagree, please comment and we can reopen it. Thank you
