### ISSUE TITLE
import 'package:Documents.FlutterSDK.flutter.packages.flutter/material.dart';

### ISSUE THREAD

**Issue by freedom6xiaobai** [flutter/flutter#108012]
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at ～/Documents/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Why should this reference be used？？？

**Comment by maheshmnj** [comment]
Hi, @freedom6xiaobai  if you go to `material.dart` in that file all the material components are being exported which are required to build your app. To put it in simple words, All material widgets (ElevatedButton, drawer, AppBar, etc) come from the material library. In order to use them you need to import them. Basically, any custom widgets you build will be on top of the material library so it's mandatory to import material.dart
Closing as this is neither a bug nor a feature request.
