### ISSUE TITLE
FlutterEngineGroup createAndRunEngine spawn but apperars "Could not spawn Shell"

### ISSUE THREAD

**Issue by dream94** [flutter/flutter#108105]
Flutter stable 2.8.1 

[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(177)] Could not spawn Shell

**Comment by maheshmnj** [comment]
Hi @dream94, Thanks for filing the issue. Can you please share the steps to reproduce the issue along with the output of `flutter dotcor -v`? Additionally, I would suggest upgrading to the latest stable 3.0.5 and see if the issue persists.

Thanks

**Comment by dream94** [comment]
We're working on a multi-engine management framework, But we found that creating multiple engines occasionally failed when we called 
FlutterJNI spawnedJNI =
                nativeSpawn(
                        nativeShellHolderId, entrypointFunctionName, pathToEntrypointFunction, initialRoute);

flutter logcat export [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(177)] Could not spawn Shell

**Comment by huycozy** [comment]
Hi @dream94 
I can not reproduce the issue with sample code in [multiple_flutters_android](https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters/multiple_flutters_android)

<details>
<summary>Demo</summary>

![Screen Shot 2022-07-25 at 12 35 35](https://user-images.githubusercontent.com/104349824/180705382-1b74611e-8ea6-4050-a804-59ba55375f4e.png)

</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
As far as I can see, you are using the old Flutter version `2.8.1`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.
Thank you!

**Comment by dream94** [comment]
![image](https://user-images.githubusercontent.com/9131020/180975928-7b7f8662-a517-4fb1-bd8a-9ca72b5a1397.png)
![image](https://user-images.githubusercontent.com/9131020/180975990-840a76ec-9ed5-49aa-a237-c21ff682d59b.png)
I have upgraded the flutter sdk to 3.0.5 but find that the problem is still there

**Comment by dream94** [comment]
We are now using Fragment A as A container to load Flutterfragments,Fragment an onAttach callback to create the page engine
![image](https://user-images.githubusercontent.com/9131020/180982531-e39c6be7-29a2-4a23-b3a1-32c8d405d62e.png)
![image](https://user-images.githubusercontent.com/9131020/180982569-290736be-b03b-4ab8-919f-8f505efbcd0b.png)
![image](https://user-images.githubusercontent.com/9131020/180982610-be08a96d-5d62-4c7a-b671-249dd7c421e2.png)
![image](https://user-images.githubusercontent.com/9131020/180982710-12a9ede9-6814-4379-8376-27ac645c0bb1.png)

**Comment by dream94** [comment]
![image](https://user-images.githubusercontent.com/9131020/181004304-207bbbec-9a53-4bf6-9762-ab1e27ff7045.png)

**Comment by maheshmnj** [comment]
@dream94 It would be great if you can share a minimal and complete sample project as requested above, which we can directly run with minimal or no code changes. (The images shared above do not help us in the triage)

Thanks
