### ISSUE TITLE
Locking the screen orientation per screen in flutter does not work on ipad

### ISSUE THREAD

**Issue by oakstair** [flutter/flutter#108235]
See https://stackoverflow.com/questions/73088824/locking-the-screen-orientation-per-screen-in-flutter-does-not-work-on-ipad

Copied from link above

I am developing an app that locks the screen orientation to portrait or landscape depending on which screen it is. I.e. I have a setup flow that uses portrait mode but when done and starting the "app" I switch over to landscape mode.

Anyhow the per screen locking code (that is recommended when googling) works fine on my iPhone but on my iPad it does not work.

On the iPad the screen rotates and turns black.

The code that locks the setup screen:

```dart
  @override
  void initState() {
    super.initState();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
  }
```

And yes i have done

`WidgetsFlutterBinding.ensureInitialized()`

**Comment by danagbemava-nc** [comment]
Hi @oakstair, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v` and the steps to reproduce so that we can investigate this.

In the future, kindly post the issue description along with your expectations and the actual results in the issue you file. It is better for whoever will eventually work on the issue if everything can be easily found in the issue. 

Thank you

**Comment by oakstair** [comment]
Well I googled some more and it turned out that I had to turn on fullscreen mode in xcode for the app to get screen rotation to work on ipad. So we may close this issue now.
