### ISSUE TITLE
How do I draw with opacity using FragmentProgram API?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#108307]
Given the following snippet, I would expect half opaque red to be drawn by the shader program. However, when running on an Android device I only see fully opaque red.

```glsl
#version 320 es

layout(location = 0) out vec4 fragColor;

void main() {
    fragColor = vec4(1.0, 0.0, 0.0, 0.5);
}
```

![flutter_01](https://user-images.githubusercontent.com/8975114/180842266-4b569f3a-00ec-408e-a48a-0cb88c409edf.png)

The generated shader doesn't have anything odd set on it:

```
   IPLR               ,       // This SkSL shader is autogenerated by spirv-cross.

float4 flutter_FragCoord;

vec4 fragColor;

void __main()
{
    fragColor = vec4(1.0, 0.0, 0.0, 0.5);
}

half4 main(float2 iFragCoord)
{
      flutter_FragCoord = float4(iFragCoord, 0, 0);
      __main();
      return fragColor;
}
      foo_fragment_main   
```

What is the correct method to draw with opacity when using the FragmentProgram API? @zanderso

**Comment by jonahwilliams** [comment]
A minimal program:

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/widgets.dart';
import 'dart:ui';

void main() =>
  runApp(
    Center(
      child:
        CustomPaint(
          painter: Foo(),
          size: Size(500, 500),
        )
      ),
    );


class Foo extends CustomPainter {
  var program = FragmentProgram.fromAsset('shaders/foo.frag');

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(Offset.zero & size, Paint()
      ..blendMode = BlendMode.srcOver
      ..shader = program.shader());
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return oldDelegate != this;
  }
}
```

**Comment by zanderso** [comment]
SkSL requires the alpha to be premultiplied: https://skia.org/docs/user/sksl/#premultiplied-alpha

We can do that when translating to SkSL, but I think we'd want to make sure that is consistent with the requirements of other backends under Impeller. For that, I think we need advice from @bdero and/or @chinmaygarde.

**Comment by bdero** [comment]
This is correct, all pipeline blends in both Impeller and Skia are additive, so colors output by the fragment stage must already be premultiplied. The correct color to output for half transparent red would be `vec4(0.5, 0.0, 0.0, 0.5)`.

```glsl
vec4 IPPremultiply(vec4 color) {
  return vec4(color.rgb * color.a, color.a);
}
```

* If the color gets passed in as a uniform, I'd recommend premultiplying the color on the Dart side before it's passed in (like we do in Impeller).
* If the color is coming from a per-vertex attribute (thus making the color conversion slow on the Dart side is there's a lot of geometry), I'd recommend premultiplying in the vertex shader.
* If the color is coming from a texture, no conversion is necessary because the color should already be premultiplied, because we decode images into a premultiplied state.

**Comment by jonahwilliams** [comment]
Makes sense! I'll close this and merge it into https://github.com/flutter/flutter/issues/107929
