### ISSUE TITLE
RTL caret not working properly in input

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#108406]
I'm not a RTL user, so I'm not 100% sure this is incorrect or due to me not using the arabic alphabet.

In any case

### REPRO

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
                textDirection: TextDirection.rtl,
      child: TextFormField()
      );
  }
}

```
- open above code in dart pad in chrome
- Type "123 456" (with space, in the input above. 
- then try to navigate the caret to the left with the arrow keys in chrome.

# Result
 The caret behavior is that it does not follow the arrows and seemingly heratic.

**Comment by maheshmnj** [comment]
Perhaps you are referring to this issue https://github.com/flutter/flutter/issues/107006#issuecomment-1173658912
which is fixed on master.

**Comment by huycozy** [comment]
Hi @cedvdb. I can reproduce this issue on the latest `stable` and `master` channel. 
But I see there's an open issue addressing the case you described #78660
However, the issue description is only about reversed direction whilst its movement is more complicated. Would you mind updating your findings here on that issue? So that the issues will be handled in one issue for others to easily follow.
Thanks!

<details>
<summary>Demo</summary>

| Stable | Master |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/181192970-0db2ad80-dbe9-4acf-8337-e2550df054a8.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/181192986-1da2e6c0-d8bd-4c72-a0ea-f00527d88e7d.mov"/>

</details>
