### ISSUE TITLE
DlComposeImageFilter calculate bound  issue

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#108433]
```C++
auto inputBounds = SkIRect::MakeLTRB(20, 20, 80, 80);
auto sk_filter1 =  SkImageFilters::Blur(5.0, 6.0, SkTileMode::kRepeat, nullptr);
auto sk_filter2 = SkImageFilters::ColorFilter(SkColorFilters::Blend(SK_ColorRED, SkBlendMode::kSrcOver), nullptr);
auto sk_filter5 = SkImageFilters::Compose(sk_filter1, sk_filter2);

DlBlendColorFilter dl_color_filter(DlColor::kRed(), DlBlendMode::kSrcOver);
auto dl_filter1 = std::make_shared<DlBlurImageFilter>(5.0, 6.0, DlTileMode::kRepeat);
auto dl_filter2 = std::make_shared<DlColorFilterImageFilter>(dl_color_filter.shared());
auto dl_filter5 = std::make_shared<DlComposeImageFilter>(dl_filter1->shared(),  dl_filter2->shared());

auto sk_bounds = sk_filter5->filterBounds(inputBounds, SkMatrix::I(), SkImageFilter::MapDirection::kForward_MapDirection);

SkIRect dl_bounds;
dl_filter5->map_device_bounds(inputBounds, SkMatrix::I(), dl_bounds);

```
The `sk_bounds` is `{fLeft:5, fTop:2, fRight:95, fBottom:98}`
The `dl_bounds` is `{fLeft:20, fTop:20, fRight:80, fBottom:80}`

But we expect that the `sk_bounds` is equal `dl_bounds`.
cc @flar

**Comment by flar** [comment]
Your choice of ColorFilter us unable to process the bounds because it turns transparent pixels non-transparent. In other words, the bounds of the ColorFilter is 'infinity'.

You will have seen a nullptr return value from dlfilter->map_device_bounds to indicate that the operation was impossible and it is specified to return a copy of the input bounds "or a best guess" in the result bounds.

While technically the DL answer is as correct as the SK answer (the operation is unbounded in both cases, but the SK operation has no indicator for that condition as it always has to return an answer), the DL answer could be improved by returning a best guess rather than a copy of the input bounds.

The reason that the DL implementation does not return a "best guess" is that it fails on the first of the 2 filters that it consults and so it immediately returns a nullptr with the "best guess" for only that filter. If we want to match the SK behavior (and it would be nice to return a better guess than we are) then it will need to pass the data through both filters regardless if either returns null, but remember the null condition so it can return its own nullptr at the end. Something along the lines of:

```
  SkIRect* map_device_bounds(const SkIRect& input_bounds,
                             const SkMatrix& ctm,
                             SkIRect& output_bounds) const override {
    SkIRect cur_bounds = input_bounds;
+   SkRect* ret = output_bounds;
    // We set this result in case neither filter is present.
    output_bounds = input_bounds;
    if (inner_) {
      if (!inner_->map_device_bounds(cur_bounds, ctm, output_bounds)) {
=       ret = nullptr;
      }
      cur_bounds = output_bounds;
    }
    if (outer_) {
      if (!outer_->map_device_bounds(cur_bounds, ctm, output_bounds)) {
=       ret = nullptr;
      }
    }
=   return ret;
  }
```

The same "keep going for best guess answer" mentality and implementation would work in all 3 DlIFCF bounds methods.
