### ISSUE TITLE
Flutter should provide access to Mozart's FrameInfo::presentation_time

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#10850]
Flutter should provide access to Mozart's FrameInfo::presentation_time, possibly in BuildContext.

Motown expresses timelines with respect to presentation time so that UI can be synchronized with audio and video. For c++ UI implemented as a subclass of BaseView, this is available through frame_tracker().frame_info().presentation_time. Flutter should provide access as well.

The current need for this is to correctly animate the media player widget's progress bar. The fidl MediaPlayer exposes progress as a set of coefficients that may be used to convert Mozart presentation time into a content-relative media presentation time.

(Report from Dale Sather)

**Comment by Hixie** [comment]
cc @chinmaygarde

**Comment by dalesat** [comment]
I found SchedulerBinding.instance.currentFrameTimestamp. This is close to what I need, but doesn't have a useful epoch. Epoch for FrameInfo::presentation_time is (Fuchsia) system startup.

**Comment by Hixie** [comment]
How do you want to handle time dilation? That is, if the developer says to run time at 0.5x normal speed, what should happen?

**Comment by dalesat** [comment]
I'm not familiar with that feature, but I'm pretty sure the timestamp I'm looking for should not be affected. Hopefully this is true of FrameInfo::presentation_time.

What I'm trying to achieve is to synchronize UI with external events. For example, if I have a progress slider for audio playback, the slider needs to be synchronized with audio playback, which is completely external to flutter. I have a function that will convert FrameInfo::presentation_time to a suitable progress value for the slider.

Video frame selection, which happens in a Mozart child view written in C++, uses FrameInfo::presentation_time and should also be indifferent to dilation.

**Comment by Hixie** [comment]
When does the presentation_time change? from the vsync?

**Comment by Hixie** [comment]
Assuming that is where the presentation_time comes from, I would make the time that you pass from the engine to Dart via onBeginFrame be this presentation time, and I would store it on the SchedulerBinding as something like currentSystemFrameTimeStamp.

**Comment by dalesat** [comment]
I'm not familiar with Mozart internals, but I assume you're correct. presentation_time is available to a view's OnDraw method (at least) via frame_tracker().frame_info().presentation_time. FrameTracker is here: https://github.com/fuchsia-mirror/mozart/blob/master/services/composition/cpp/frame_tracker.h. I access it in my video renderer here: https://github.com/fuchsia-mirror/media/blob/master/src/media_service/video_renderer_impl.cc#L77.

Sorry, I'm unsure from the wording of your comment whether you're suggesting I do something or you're saying what you will do. If it's the former, I'm not sure where mozart and flutter actually meet in fuchsia. I see onBeginFrame in flutter but not in apps/mozart or apps/sysui.

SchedulerBinding.instance.currentFrameTimestamp would be fine if only I knew the offset between its epoch and the epoch of mx_time_get(MX_CLOCK_MONOTONIC), which is widely used in fuchsia.

**Comment by Hixie** [comment]
`SchedulerBinding.instance.currentFrameTimestamp` doesn't have a fixed epoch, it changes whenever the timeDilation changes and at various other times (e.g. on hot reload). I'm suggesting we (you, me, maybe @chinmaygarde) add a `SchedulerBinding.instance.currentSystemFrameTimestamp` that reflects the presentation_time for the currently running frame.

**Comment by dalesat** [comment]
Perfect, thanks

**Comment by zoechi** [comment]
Is there still something to do?

**Comment by dalesat** [comment]
Yes, I still think this is important.

Media players need to synchronize UI animation with media presentation.
'clock monotonic' is the underlying time base used for presentation, both
for media and for scenic.

Regardless of time dilation, presentation_time should reflect that actual
'clock monotonic' time at which the current frame will be presented. If
media presentation is to be dilated as well, this must be handled in the
media pipeline, which will understand the relationship between dilated
presentation time and clock monotonic.

**Comment by iskakaushik** [comment]
@dalesat , I want to make sure that I understand this issue.

The problem we are trying to solve is coordinating UI events based on an external service, in this case it's the media player FIDL service. As the media player uses "clock monotonic" to drive its events, you wish to use the same (exposed via Flutter) to drive the UI events.

Is that correct?

If so, Is there a reason we can not use FIDL to talk to the clock service via dart-fidl bindings, and then use them to drive the UI events?

**Comment by dalesat** [comment]
The flutter application knows the relationship between player's
'presentation time' (distinct from scenic presentation time) and system
time (CLOCK_MONOTONIC). What it doesn't currently know is the system time
at which the view being drawn at the moment will be presented. It needs to
be able to obtain this information synchronously, so that information needs
to be provided in the context of the render (term?) that's currently
happening.

**Comment by goderbauer** [comment]
I believe the framework side of this was done as part of https://github.com/flutter/flutter/issues/33216. I am going to remove the framework label.

**Comment by gaaclarke** [comment]
This is fishy to me.  If you want to synchronize UI events to media playback you should be writing something like this:
```
let player = new Player("foo.mov")
player.AddObserver((mediaTimeMicroSeconds) => _playhead.SetTime(mediaTimeMicroSeconds));
player.play()
```

Flutter just needs to know the current media time of the video/audio and should base all of the drawing off of that information alone.

**Comment by dalesat** [comment]
The player reports progress as a set of coefficients that can be used to
calculate the presentation time from the system monotonic clock. This
design is preferred over one that incurs a lot of IPC traffic to get
presentation time values that are 1) inaccurate due to the transit time of
the IPC response, and 2) not available synchronously when you need them.

**Comment by gaaclarke** [comment]
How bad is the transit time?  It's the same computer isn't it?  A playhead that is 200ms behind isn't really going to miff anyone.  Especially considering that might even leave the playhead on the same pixel anyway.

You can cut down in chattiness by controlling the broadcasting samplerate, 2 x the refresh rate of the screen should be all that's needed.

**Comment by dalesat** [comment]
The current design is better, and the bug represents a reasonable request.
Thanks anyway.

**Comment by gaaclarke** [comment]
Right on.  This is filed as "customer critical" which means you are blocked from shipping.  I merely presented a way forward.  I think this might be better filed as a feature request since we both admit there is an acceptable solution available, we'd just like to make a better solution available.  FWIW I suspect the synchronization problems this request prevents are hypothetical with respect to the discrete nature of the machine and human perception.

**Comment by dalesat** [comment]
Your point is taken. A simpler alternative to having this feature
implemented is to simply use the current time when calculating progress,
current time being a reasonable approximation of the presentation time.

**Comment by Hixie** [comment]
This should be relatively trivial to implement on our side, no? It's just piping data from one API to another, if I'm not mistaken.

**Comment by iskakaushik** [comment]
Once https://github.com/flutter/engine/pull/14318 rolls into the framework, it will make it so that we pass the `frame_target_time` for `window.onBeginFrame`. Which should mean that using `currentSystemFrameTimeStamp` will reflect the time, with the CLOCK_MONOTONIC epoch, for when the frame will likely be presented.

@dalesat you would want to switch usages of `currentFrameTimeStamp` to `currentSystemFrameTimeStamp`.
