### ISSUE TITLE
Non-obvious to implement deep linking with MaterialApp

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#10884]
It takes a bit of guess-work to set up a `MaterialApp` with deep linking.

First, the platform-specific code must call `setInitialRoute` on their `FlutterView`/`FlutterViewController` to ensure a given deep link is made available to Flutter on launch. With the Android `FlutterActivity`, this must be done after execution of [this line](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L136) and before the execution of [this line](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L151). That may imply overwriting `FlutterActivity.createFlutterView()` and re-implementing [a few lines of code](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L140-L143) from `FlutterActivityDelegate` (cc @tvolkert @szakarias). All this comes on top of adding intent filters in the manifest xml. I have not looked at the iOS experience.

When done, the provided route string is available to Dart code via the `Window.defaultRouteName` getter. 

Second,  `MaterialApp` uses `Navigator.defaultRouteName` as the default initial route. This is a constant value that happens to be identical to `Window.defaultRouteName` only when `setInitialRoute` has not been called.

Third, to force `MaterialApp` to use `Window.defaultRouteName`, there seems to be two options:

1. Initialize `MaterialApp.initialRoute` to `null`. This is non-obvious and has implications for satisfying `assert` statements.
1. Initialize `MaterialApp.initialRoute` to `Window.defaultRouteName`. This implies importing the low-level `dart:ui` package.

(cc @Hixie)

We can remedy this situation by providing an example or a self-answered StackOverflow question. Improvements to the API and its documentation may also be possible.

**Comment by mravn-google** [comment]
Sample deep linking Android app available [here](https://gist.github.com/mravn-google/73d813cc0634b9c0639d38c82ef78ad2). Includes the main points of change from the `flutter create` template and a shell command for testing that the app can be launched on an Android device using a deep link.

**Comment by tvolkert** [comment]
Does https://github.com/flutter/engine/pull/3795 address part of this?

**Comment by eseidelGoogle** [comment]
FYI @lukef

**Comment by mravn-google** [comment]
@tvolkert Partially, yes. But not if you want to use your own Intent action (other than `Intent.ACTION_RUN`), URI (which we use for the app bundle path), or extra fields (we use a `route` String extra, but I couldn't find the documentation for that by a quick searching flutter.io).

See e.g. https://github.com/goposse/fluro for a more advanced use case.

Again, this may be resolved by just adding documentation, but I thought I'd run it past you guys, in case you had input to provide a simpler or more flexible API.

**Comment by Hixie** [comment]
I'm fixing the Dart side of this. I have a patch mostly complete.

**Comment by Hixie** [comment]
(Mostly driven from https://github.com/flutter/flutter/issues/618.)

**Comment by tvolkert** [comment]
On the Java side, it looks like adding an API hook [here](https://github.com/flutter/engine/blob/fffe502d437ac7931f08c6cef3e3f71fbd36adaa/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L146) is needed.  @mravn-google do you agree, and would this cover the use cases you've seen, or is more needed?

**Comment by mravn-google** [comment]
Yes, I think that would make sense. I actually immediately tried to override `loadIntent` first, but then found it private.

Just discovered a regression here, I believe: `loadIntent` is also called from `onNewIntent` where we actually want to delegate to `pushRoute`, not `setInitialRoute`.

**Comment by passsy** [comment]
My usecase it an `intent-filter` to open my app instead of a website (example: https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/AndroidManifest.xml#L220).

This requires custom events (`action.VIEW`) forwarded to the flutter side. I'm not sure if mapping a bundle to a Route is always the correct way. Often I don't want to push a Route but handle the new Intent differently.

Another usecase would be scanning of an NFC tag. 
```
<intent-filter>
    <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <data android:mimeType="text/plain" />
</intent-filter>
```

This should be handled with the same API.

## Alternatives:

If both cases doesn't make it into flutter it should be possible to define an `Activity` in the android app (non UI) which has the intent filters registered and forwards the events somehow to the `FlutterView`. AFAIK there is no event channel to pass events from outside into an Activity hosting a `FlutterView`. Maybe one could use a broadcast receiver for this.

**Comment by Hixie** [comment]
For Android: We should probably have FlutterActivityDelegate's loadIntent call some method to let you figure out what to pass to setInitialRoute for the case where the intent isn't "run". Or maybe just make loadIntent overridable, why is it private anyway?

**Comment by Hixie** [comment]
cc @cbracken, @chinmaygarde

**Comment by chinmaygarde** [comment]
From an implementation perspective, I would like to to keep the engine as simple as possible. Currently, wiring up the initial route from the embedder to the Dart isolate requires an extra field on the [engine](https://github.com/flutter/engine/blob/master/shell/common/engine.h#L120). Notice that there are other fields there that the engine does not care about but needs to setup the Flutter library bindings. 

@rmacnak-google pointed me to [`String.fromEnvironment`](https://docs.flutter.io/flutter/dart-core/String/String.fromEnvironment.html) and friends that allow the Dart VM to ask its embedder for such arguments. We can make [`FlutterDartProject`](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Headers/FlutterDartProject.h) and its Android variant take a user specified map of arguments that can be exposed on a per root isolate basis. This map can be initialized by intent data or the dictionary passed to the application delegate when it is launched.

**Comment by Hixie** [comment]
Seems reasonable, although it's a bit weird in that we'd be adding a third way that we communicate from the OEM side to the Dart side (via platform channels, via dart:ui, and now via the environment variables).

I wasn't able to determine what the Android equivalent was from perusing our docs.

**Comment by xster** [comment]
Another bit of complexity is that developer users and user users would expect deep linking to work more or less the same way when the app is already in memory vs cold launches. Therefore, it would be nice to have an API that can discern between but that still addresses both scenarios via the same API. 

Perhaps we should wrap the setInitialRoute functionality with a requestRoute API that users can both call before and after the application launches which either saves a string to be read when first instantiating a MaterialApp or that invokes a default but overridable navigator push behaviour if the application is already running.

**Comment by Hixie** [comment]
My `Router` widget routes initial routes and new routes to the same place. You can see the work in progress at: https://github.com/flutter/flutter/compare/master...Hixie:router
However, that doesn't solve the problem on the OEM side.

**Comment by xster** [comment]
I took a look at the branch in progress. I may not have correctly simulated the logic in the branch but my understanding is that if a window.defaultRouteName is set during the DefaultRouteNameProvider's construction via setInitialRoute, then that path will be resolved via the common flow. Otherwise, a SystemChannels.navigation.didPushRoute will make the common Router flow work as well. 

The only tricky thing though is that the engine will have to guess which API to call (navigation.setInitialRoute or navigation.pushRoute) and run the risk of calling pushRoute before the WidgetsBindingObserver is connected or calling setInitialRoute after DefaultRouteNameProvider is built. Though I may have misunderstood this flow.

If not, how about an API similar to the current defaultRouteName that gets the value from the engine but it continues to be what gets ValueNotifier'ed when it changes? (we might have to do some renaming). This way, the same API can handle engine side requested routes before and after the Router is setup.

**Comment by Hixie** [comment]
The WidgetsBindingObserver for the Router delegates will get connected during the call to `main()`, so that's not an issue. Similarly, you can't call `setInitialRoute` too late and have it do anything at all; you have to call it before `main()` is called, because that's when it's read. The docs for `setInitialRoute` should talk about where to call it (see the corresponding API docs for the Window member that it sets, I know it's documented there at least).

But yes, maybe we should change the engine API here so that there's only one way to pass routes to the Dart code. Currently we have two because we want to only do things via channels, except for when you have to have something ready when `main` is run (before channels are set up), as is the case for the initial route. IIRC @chinmaygarde expressed reservations about making that path more complicated, as would be necessary if we had only one path.

Having said that, it's not clear to me that having two paths is necessarily that much of a problem. Aren't we talking about two paths anyway? When the app is started with an intent, you get a different entry point than when Android notifies you to update the route, no?

**Comment by xster** [comment]
Merging this one into #11607 since it's essentially the same thing.
