### ISSUE TITLE
Make it opt-in to decode images at native size.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#108928]
Flutter can decode images into a smaller size to save texture memory. However, this is is opt-in and images are decoded at native size by default. We should flip this default.

**Comment by chinmaygarde** [comment]
cc @dnfield

**Comment by zanderso** [comment]
This issue raises a number of interesting design questions. Marking P5, new feature.

**Comment by dnfield** [comment]
@jonahwilliams were talking about this today and a rough sketch of a framework-side change may be more tractable:

- By default, use a `ResizeImageProvider` when resolving the image.
- Preferably, move image resolution to the `RenderImage` and make it stateful - it manages the provider rather than the widget state so that it can be informed by the `size` once available.
  - Less preferable alternative, use a `LayoutBuilder`. But don't do this.
- Make sure to detect if the `ImageProvider` already has a `ResizeProvider` in the chain of providers and avoid adding a second one.

**Comment by dnfield** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/132976
