### ISSUE TITLE
My check box is bringing blank screen, 

### ISSUE THREAD

**Issue by Chinecherem20199** [flutter/flutter#108959]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

 [New Recording - 8/4/2022, 11:03:35 AM](https://vimeo.com/736464607/ab1126f13f)

**Comment by danagbemava-nc** [comment]
Your issue is that you have put an `Expanded`, a widget that takes up all available space in a slot in the `ListTile` which is meant to have a finite size. Try to give it a fixed width and height; your issue should disappear. 
Alternatively, since you're using a Checkbox, you can just use a `CheckBoxListTile` widget. 

In the future, kindly provide the information requested in the template when you file an issue. 

Closing this as it is an implementation issue.
