### ISSUE TITLE
Profiling code misbehaving

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#108934]
(Possibly related to https://github.com/flutter/flutter/issues/108812)

```
% flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

iPad version
`iPad Pro (12.9-inch) (5th generation)`

Running my app  with `--profile` produces a blank screen.  The app is running and trying to update it (it is animated) but the screen is not drawing

Using debug (no flag) or --release it works as well as I wrote it

Output of `flutter -v run --profile` attache
[bugrep.txt](https://github.com/flutter/flutter/files/9255656/bugrep.txt)
d

**Comment by huycozy** [comment]
Hi @WorikQCI, 
From your log file:
>[  +57 ms] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Exception: Codec failed to produce an image, possibly due to invalid image data.

The exception log looks similar to the logs which addressing in #79624
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

If your `flutter doctor -v` output is the same as https://github.com/flutter/flutter/issues/108812#issuecomment-1204698449 that you provided, please see my answer in https://github.com/flutter/flutter/issues/108812#issuecomment-1204851842 and give your response here.

Thank you!
