### ISSUE TITLE
Incorrect RegExp in engine/browser_detection.dart

### ISSUE THREAD

**Issue by rakudrama** [flutter/flutter#108999]
[Source code here](https://cs.github.com/flutter/engine/blob/05ff95d4496fa5f4bc1591fdbd06bfb1bcc249fe/lib/web_ui/lib/src/engine/browser_detection.dart#L85)

```dart
/// Detects samsung blink variants.
///
///  Example patterns:
///    Note 2 : GT-N7100
///    Note 3 : SM-N900T
///    Tab 4 : SM-T330NU
///    Galaxy S4: SHV-E330S
///    Galaxy Note2: SHV-E250L
///    Note: SAMSUNG-SGH-I717
///    SPH/SCH are very old Palm models.
bool _isSamsungBrowser(String agent) {
  final RegExp exp = RegExp(
      r'SAMSUNG|SGH-[I|N|T]|GT-[I|N]|SM-[A|N|P|T|Z]|SHV-E|SCH-[I|J|R|S]|SPH-L');
  return exp.hasMatch(agent.toUpperCase());
}
```

`|` in a character classes `[...]` will match the `|` character.
It is likely that `[I|N|T]` should be either `(I|N|T)` or `[INT]`

**Comment by danagbemava-nc** [comment]
Labeling for further insights from the team

**Comment by yjbanov** [comment]
I'm actually concerned that we even have a special case for Samsung browser. Perhaps https://github.com/flutter/flutter/issues/107786 is caused by this. There are a few places that don't consider `BrowserEngine.samsung`, e.g.:

- https://github.com/flutter/engine/blob/1ad699a60678405338a67eee64ca76d4c85976f9/lib/web_ui/lib/src/engine/safe_browser_api.dart#L234
- https://github.com/flutter/engine/blob/1ad699a60678405338a67eee64ca76d4c85976f9/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1830

The engine is blink. If we want special code for Samsung browser, I think it should be a separate dimension. I'll try to clean this up.
