### ISSUE TITLE
[video_player] m3u8 videos are distorted when played on iOS

### ISSUE THREAD

**Issue by aboyo** [flutter/flutter#109116]
When playing a particular m3u8 video, that aspect ratio is wrong, I referred to this commit [[flutter/plugins#5069](https://github.com/flutter/plugins/pull/5069)] and used the latest video player plugin,
this file's aspect ratio of video for mp4 format is correct, but when I convert it to m3u8 and play with the network it seems upside down the width and height, this only affects iOS.

| | |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/21969308/183295336-648ccc04-27e9-4996-9998-f836cf1d86ef.png"> | <img width="400" src="https://user-images.githubusercontent.com/21969308/183295349-30b1395c-3398-4678-9aa6-c108e58fdb9f.png">

the m3u8 content src: https://videodelivery.net/11a75f7cf7314f5a880d49fb8bebaaed/manifest/video.m3u8

**Expected results:** 
the aspect ratio is the same as the mp4 format.

**Actual results:** 
the video seems upside down the width and height.

**$flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2 21D49 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.10.3 at /Users/abo/flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 month ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/abo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 98C54F15-C96B-4757-962F-119E43CEF121 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 103.0.5060.134

```

**Comment by huycozy** [comment]
Hi @aboyo 
Could you please provide the original `.mp4` file?
I tried playing your `.m3u8` remote url and this is the result:

<img width="400" src="https://user-images.githubusercontent.com/104349824/183414158-89a34dfd-d02d-4e99-b187-e76de91393d2.png">

I'm using video_player: `2.4.5`

Also, which `video_player` version are you using now?
As far as I can see, you are using the old Flutter version `2.10.3`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.

**Comment by aboyo** [comment]
> Hi @aboyo Could you please provide the original `.mp4` file? I tried playing your `.m3u8` remote url and this is the result:
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/183414158-89a34dfd-d02d-4e99-b187-e76de91393d2.png">
> 
> I'm using video_player: `2.4.5`
> 
> Also, which `video_player` version are you using now? As far as I can see, you are using the old Flutter version `2.10.3`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.

yes, that is not the correct aspect ratio.
I have uploaded the mp4 file to my github new repository, there is link:
[https://github.com/aboyo/test_mp4](https://github.com/aboyo/test_mp4)

**Comment by huycozy** [comment]
@aboyo Thanks for providing the file. 
This issue is reproducible on the latest `stable` and `master` channels with sample code from [video_player/example](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player/example)

Plugin version: `video_player: 2.4.6`
Url for testing:
   - m3u8: https://videodelivery.net/11a75f7cf7314f5a880d49fb8bebaaed/manifest/video.m3u8
   - mp4: https://user-images.githubusercontent.com/104349824/183575717-d847332b-67bc-4451-a5f3-c6c7eabc853c.mp4

Result:
- iOS m3u8: ❌
- iOS mp4: ✅
- Android m3u8: ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo</summary>

| iOS m3u8 | iOS mp4 | Android m3u8 |
| --------------- | --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/183577033-af0edd46-50ee-4743-a90e-1fe5f53d3701.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/183577111-796ebeba-2f2b-4c25-9cc4-05e30b6d31e4.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/183577122-4420351d-8311-4805-8f8e-18ca806cf51b.mov"/>

</details>

<details>
<summary>Sample code</summary>

```dart

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash

```
</details>

**Comment by huycozy** [comment]
@aboyo Thanks for providing the file. 
This issue is reproducible on the latest `stable` and `master` channels with sample code from [video_player/example](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player/example)

Plugin version: `video_player: 2.4.6`
Url for testing:
   - m3u8: https://videodelivery.net/11a75f7cf7314f5a880d49fb8bebaaed/manifest/video.m3u8
   - mp4: https://user-images.githubusercontent.com/104349824/183575717-d847332b-67bc-4451-a5f3-c6c7eabc853c.mp4

Result:
- iOS m3u8: ❌
- iOS mp4: ✅
- Android m3u8: ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo</summary>

| iOS m3u8 | iOS mp4 | Android m3u8 |
| --------------- | --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/183577033-af0edd46-50ee-4743-a90e-1fe5f53d3701.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/183577111-796ebeba-2f2b-4c25-9cc4-05e30b6d31e4.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/183577122-4420351d-8311-4805-8f8e-18ca806cf51b.mov"/>

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2160, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.2160 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 612e536282 (54 minutes ago), 2022-08-08 22:54:07 -0400
    • Engine revision 6c14fb339f
    • Dart version 2.19.0 (build 2.19.0-75.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by jmagman** [comment]
Copying priority from https://github.com/flutter/flutter/issues/112129#issuecomment-1255614127

**Comment by jmagman** [comment]
@hellohuanlin can you take a look at this?

**Comment by hellohuanlin** [comment]
Update: found some clue. Will put up a PR soon.

**Comment by intsitesdotru** [comment]
We have the same bug, it happening with an m3u8 without an audio track in our app.
I want to ask such a question, if someone answers I will be very grateful. When I put a breakpoint on the line with return in the `Stream<VideoEvent> videoEventsFor(int textureId)` function, then after resuming the app, the sizes are calculated correctly inside the video controller. Why can a breakpoint affect like this? I have already met this behavior, I would like to understand why it can be so?
![Снимок экрана 2022-09-29 в 14 09 08](https://user-images.githubusercontent.com/8538607/193018724-82497d02-71e0-4073-9d79-99b7ce86f0b9.png)

**Comment by hellohuanlin** [comment]
@aboyo Hi I got the fix but need to create a m3u8 file for integration test. Could you share how you created your m3u8? 

I have tried the following and all failed to result in an inverted aspect ratio. 

1. rotate mp4, then convert to m3u8
2. convert mp4 to m3u8, then rotate m3u8
3. rotate mp4, then convert to m3u8, then rotate m3u8
4. use ffmpeg's `master_pl_name` option for 1-3 steps

The rotation command I use is: 
```
ffmpeg -i bee.mp4 -c copy -metadata:s:v:0 rotate=90 rotated_bee.mp4
```
The conversion command I use is: 
```
ffmpeg -i rotated_bee.mp4 -g 60 -hls_time 2 -hls_list_size 0 -hls_segment_size 500000 -master_pl_name rotated_bee_mpl.m3u8 rotated_bee.m3u8
```

**Comment by LarsFanhouse** [comment]
@hellohuanlin thank you so much for your work on this.

on our end, the playlist files are created using the [Google Cloud Transcoder API](https://github.com/googleapis/nodejs-video-transcoder). We do not manually run conversion or rotation commands on the video files ourselves. 

we create a [TranscoderServiceClient](https://cloud.google.com/nodejs/docs/reference/video-transcoder/latest/video-transcoder/v1.transcoderserviceclient) and then [create job](https://cloud.google.com/nodejs/docs/reference/video-transcoder/latest/video-transcoder/v1.transcoderserviceclient#_google_cloud_video_transcoder_v1_TranscoderServiceClient_createJob_member_1_)s that are configured to output the videos as HLS m3u8 streams. I don't want to expose our exact job configuration here, but they are configured similarly to the HLS sections of [this configuration example](https://cloud.google.com/transcoder/docs/concepts/config-examples#multiple-manifests) (ignore the DASH portions).

I know this probably isn't as helpful as giving you exactly what commands are called but I imagine it is a common use-case to combine Google Transcoder with the flutter video player.

**Comment by hellohuanlin** [comment]
@LarsFanhouse Thanks for the info. I am not sure how GCP converts the video and what exactly contributes to the inverted aspect ratio. Is it possible for you to convert [this sample video](https://github.com/flutter/assets-for-api-docs/blob/master/assets/videos/bee.mp4) so i can use it in integration test?

**Comment by LarsFanhouse** [comment]
@hellohuanlin happy to drop a link with that sample video run through our transcoder, but the video you provided doesn't cause the aspect ratio bug on our end, so I'm not sure it will be helpful or at all distinct from the way you've created your m3u8. do you still want it?

**Comment by hellohuanlin** [comment]
@LarsFanhouse 

> I don't know either what the conditions are to make a video cause this bug.

My fix is to leverage Apple's `AVPlayerLayer`, which is a blackbox. So unfortunately I have no idea. 

> but the video you provided doesn't cause the aspect ratio bug on our end

this makes me suspect that it's also related to mp4 format. Can you try [this rotated video](https://github.com/hellohuanlin/temp/tree/931fee4a136ab588c7fd353af6db45aa12b34682/rotated_bee)? 

> do you still want it?

Yes. I'd like to try both the original and rotated ones. Can you send me both? Thanks!

**Comment by LarsFanhouse** [comment]
@hellohuanlin 

hm, that's frustrating. i've converted the two videos you provided using our transcoder config, and attached .zips here. it's not **exactly** what the transcoder would output because I've removed filepath info from all the files to not expose our infra, but should essentially be the same data.

we initialize our video player instances with the generated manifest files.

[bee_portrait.zip](https://github.com/flutter/flutter/files/9687911/bee_portrait.zip)
[bee_landscape.zip](https://github.com/flutter/flutter/files/9687912/bee_landscape.zip)

**Comment by hellohuanlin** [comment]
@LarsFanhouse thanks for the files. Unfortunately nether worked. 

I also inspected both the original nail m3u8 and this portrait bee m3u8 and nothing odd comes up (you can inspect by `ffmpeg -i bee.m3u8`). 

I will investigate further, but please leave comments if anyone has any clue how to generate reproducible videos.

**Comment by hellohuanlin** [comment]
I spent more time today trying to create the reproducible videos with pretty much all possible rotation related `ffmpeg` options and their combinations. All failed to reproduce the problem :(

Here's a complete list of what I have tried for future reference: 

1. apply display matrix metadata (`-metadata:s:v rotate=0`) to mp4, and then convert to m3u8
2. apply rotate filter (`-vf "rotate=PI/2:bilinear=0,format=yuv420p"`) to mp4, and then convert to m3u8
3. convert mp4 to m3u8, then apply display matrix to m3u8
4. convert mp4 to m3u8, then apply rotate filter to m3u8
5. apply display matrix to mp4, then convert to m3u8, then apply another display matrix to m3u8
6. apply display matrix to mp4, then convert to m3u8, then apply rotate filter to m3u8
7. apply rotate filter to mp4, then convert to m3u8, then apply display matrix to m3u8
8. apply rotate filter to mp4, then convert to m3u8, then apply another rotate filter to m3u8
9. apply display matrix to mp4, then convert to m3u8 with `-noautorotate` option (should be equivalent to just converting to m3u8 without any rotation)
10. apply display matrix to mp4, then convert to m3u8 with `-noautorotate` option, then apply another display matrix to m3u8 (should be equivalent to convert to m3u8 first and then apply display matrix, i.e. option 3)
11. apply display matrix to mp4, then convert to m3u8 with `-noautorotate` option, then apply another rotation filter to m3u8 (should be equivalent to convert to m3u8 first and then apply rotation filter, i.e. option 4)
12. A few experiments with transpose filter `-vf "transpose=2,transpose=2,format=yuv420p"`, but similar result. 
13. A few experiments with the combination of transpose filter and display matrix metadata, also similar result

Unfortunately since the fix uses Apple's video player which is a blackbox to us, it's hard to figure out what exactly results in an inverted aspect ratio. 

So as discussed offline, let me land this change as of now, and revisit the test later when we get such videos. 

CC @jmagman @LarsFanhouse
