### ISSUE TITLE
Compatibility with App Slicing

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10914]
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

It's unclear if Flutter apps are currently compatible with App Thinning.  I suspect this may be required for some customers for M3 or M4.

@cbracken

**Comment by cbracken** [comment]
Since we only currently support arm64 iOS devices, we apply app thinning during our own build process and only ship arm64 binaries to App Store.

That said, it looks fairly inevitable that Apple will eventually require bitcode, which we currently don't do. We should definitely investigate our options there.

**Comment by cbracken** [comment]
TestFlight download size of the first universal binary of the Gallery was unimpacted (slightly less, but I suspect for reasons unrelated to app slicing).
