### ISSUE TITLE
Add StrokeCap parameter on CircularProgressIndicator

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#109137]
## Use case
This would allow circular progress indicators to have rounded tips, which is a useful addition in certain designs

## Proposal
The Paint() method already has a StrokeCap property which determinds how the end of drawn lines/arcs look, so I propose the CircularProgressIndicator have a parameter that ultimately passes this down to the paint method inside `_CircularProgressIndicatorPainter`.

**Comment by Hixie** [comment]
Would it make more sense to expose the entire Paint? For example, what if someone wants to adjust the gradient rather than the end cap? Or the stroke width? cc @HansMuller

**Comment by Hari-07** [comment]
That kind of problem exists for most widgets, exposing the paint would allow for a lot more customisation, but afaik every widget takes in a whole lot of parameters like color, gradient, width etc which ultimately end up on its paint, so isn't this the pattern that's used everywhere currently?

And as for gradient, if the color is set to white, we can have a gradient using a Shader mask

**Comment by Hixie** [comment]
Well, generally when we expose a color, gradient, or width we don't do it in a way that directly translates to a paint, but I agree that exposing a paint is a bit weird...

**Comment by bleroux** [comment]
For a determinate `CircularProgressIndicator`, it might be problematic to allow stroke cap customization. For instance, allowing `StrokeCap.square` will make the indicator start with a value that seems to be negative (due to the extension added by drawArc when strokeCap is not `StrokeCap.butt`).

Screenshots of a big `CircularProgressIndicator` with `StrokeCap.square` and `StrokeCap.butt`:
![StrokeCapSquare](https://user-images.githubusercontent.com/840911/183657986-5cf47d15-1bfa-4c68-9357-d7babb7d1b0f.png)
![StrokeCapButt](https://user-images.githubusercontent.com/840911/183658007-3064ac4c-68ea-4993-9f52-d2326eea739c.png)


<details>
<summary>Related code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: StatefulBuilder(
        builder: (context, setState) {
          return Scaffold(
            appBar: AppBar(title: const Text("StrokeCap.butt")),
            body: Stack(
              children: [
                Row(children: [
                  Expanded(child: Container(color: Colors.white)),
                  Container(width: 1, color: Colors.grey),
                  Expanded(child: Container(color: Colors.white)),
                ]),
                const Center(
                  child: SizedBox(
                    width: 300,
                    height: 300,
                    child: CircularProgressIndicator(
                      value: 0.5,
                      strokeWidth: 50.0,
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}

```
</details>

So setting stroke cap should be ignored for a determinate `CircularProgressIndicator` or the starting angle should be computed accordingly (if possible, but it might be difficult to get the right result with `StrokeCap.square`).

**Comment by Hari-07** [comment]
So should I change the default to be `StrokeCap.butt` instead of `StrokeCap.square`

**Comment by bleroux** [comment]
> So should I change the default to be `StrokeCap.butt` instead of `StrokeCap.square`

I think it would be better to keep the current logic which is to use `StrokeCap.butt` for any determinate `CircularProgressIndicator`.

**Comment by Hari-07** [comment]
That certainly does seem easier, but what if you want a circular ended determinate progress indicator

IMO it's a flaw in the design if the type of the end determines where the drawing would end, instead the drawing should be offset as per the the end design

Also is there a way to do custom ends rather than use the inbuilt strokecaps?

**Comment by Piinks** [comment]
Re-opening as this is unresolved.

There are a lot of widgets in the material library that match the material spec, and offer customizations beyond the spec. I think this is a fair feature request.

**Comment by Hari-07** [comment]
I actually had a PR up for this but the CI was failing and wasn't able to figure out why, I can try rebasing it and force push if thats okay

**Comment by Piinks** [comment]
Hey @Hari-07! I was just looking at that and wondering if you would be interested in returning to it. I'd be happy to help and review if you are interested in contributing. Would you like to re-open it in a new PR?

**Comment by Hari-07** [comment]
Yeah sure I'll do it as soon as I can

**Comment by bernaferrari** [comment]
@Hari-07 I only saw the discussion now, I took your PR and fixed it (while keeping your name in the contributor list).

**Comment by bernaferrari** [comment]
There is a frustrating issue I'm going to need your help.

Right now:
```dart
if (indeterminate) strokeCap = square
else strokeCap = butt
```

What is the default value? Butt? I'm going to override it in indeterminate mode, I guess...

**Comment by bernaferrari** [comment]
I don't think StrokeCap works that well for what we are doing. It has 3 options, butt, square and round, but 99% of the time you want two of them, and you never know which two you want. `CircularProgressIndicator` uses square for indeterminate (paints a bit more, so it is always visible, even on 0), butt for determinate (paints exactly). `CircularProgressIndicator` doesn't use it.

Something like `isIndicatorRound` would be better, since all we want is true/false. Do you agree?

**Comment by bleroux** [comment]
> Something like isIndicatorRound would be better, since all we want is true/false. Do you agree?

I too think that it would be better to have such a boolean flag because `StrokeCap.square` is problematic (see https://github.com/flutter/flutter/issues/109137#issuecomment-1209391300).

**Comment by bernaferrari** [comment]
Using boolean now, fell free to review the PR @bleroux. Thanks for the input!
