### ISSUE TITLE
Add copyright/license headers to the template files

### ISSUE THREAD

**Issue by iamsergio** [flutter/flutter#109337]
Running `flutter create foo` creates many C++ files so the application can run on Linux (for instance).
For example:
- linux/main.cc
- linux/my_application.cc   

These files are missing copyright/license headers.
Many companies require that all source files start with the usual copyright headers or use a spdx license tag.

It's also becoming popular to have pre-commit hooks to validate this, like https://github.com/fsfe/reuse-tool .

Please make the files created by `flutter create` have license headers.

**Comment by jonahwilliams** [comment]
What license headers would they have? The flutter tool doesn't currently know how you're licensing your code or whether or not a per-file license is required. This seems like something that could be done by other tools

**Comment by iamsergio** [comment]
I can not chose a license and attribute myself copyright of something I didn't write.
The templates (for example `packages/flutter_tools/templates/app_shared/linux.tmpl/my_application.h`) were written by the flutter team and hosted in the flutter repo, so BSD would make sense, as most all other flutter and dart code

**Comment by jonahwilliams** [comment]
We can't choose a license for folks though...

**Comment by stuartmorgan** [comment]
Retitling as the C++ template code is no different from all of the other template files in this respect.

@Hixie I'm assuming the current state was an explicit choice?

**Comment by Hixie** [comment]
As this is a legal matter it is not something we (as engineers) are qualified to discuss. My understanding based on previous discussions with Google's legal team is that the current state is intentional; that in general you can assume that if you comply with the licenses exposed by https://api.flutter.dev/flutter/material/showLicensePage.html that you are in compliance with all licenses relevant to the SDK; and that we do not consider template code (as generated by `flutter create`) to be meaningfully copyrightable as they are not creative, are automatically generated (not human-authored), are required for interop, and are merely the essential starting point for writing an application with Flutter. However, this is not legal advice, and this paragraph does not constitute a commitment of any kind. I may be completely mistaken in these statements.

I would encourage you to reach out to your own legal counsel for advice. If they would like to communicate further on this matter I would encourage them to reach out to me at ian@hixie.ch; I may be able to forward their comments to Google's legal team.
