### ISSUE TITLE
Dependabot should only update major versions of non-client facing dependencies

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109628]
Use `ignore: update-types: ["version-update:semver-minor"]` in [dependabot.yml](https://github.com/flutter/plugins/blob/main/.github/dependabot.yml) for non-client facing dependencies (gradle, examples, tests) to have dependabot ignore the minor and patch updates.

> `update-types`—use to ignore types of updates, such as semver major, minor, or patch updates on version updates (for example: `version-update:semver-patch` will ignore patch updates). You can combine this with `dependency-name: "*"` to ignore particular update-types for all dependencies. Currently, `version-update:semver-major`, `version-update:semver-minor`, and `version-update:semver-patch` are the only supported options. Security updates are unaffected by this setting.
 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

```diff
updates:
  - package-ecosystem: "gradle"
    directory: "/packages/camera/camera_android/example/android/app"
    commit-message:
      prefix: "[camera]"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
+   ignore:
+     - dependency-name: "*"
+       update-types: ["version-update:semver-minor"]
```

**Comment by camsim99** [comment]
Closing as https://github.com/flutter/plugins/pull/6355 was landed.

**Comment by stuartmorgan** [comment]
> Closing as [flutter/plugins#6355](https://github.com/flutter/plugins/pull/6355) was landed.

FYI if you use the right magic word in your PR description, this will happen automatically: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue. E.g., writing "Fixes https://github.com/flutter/flutter/issues/109628" instead of "Addresses https://github.com/flutter/flutter/issues/109628" would do it. (It seems like Addresses should really be on the list of magic words too, but unfortunately isn't.)
