### ISSUE TITLE
The calculation method for _CriticalSolution seems wrong

### ISSUE THREAD

**Issue by LevisonNN** [flutter/flutter#109675]
## Steps to Reproduce

1. I was reading the source code of Flutter and found a little mistake in spring_simulation.dart.
2. It is in line 185. When calculating the critical damping solution, I got a different result. 
3. My calculation steps are as follows: y = (c1 + c2 * t) * e ^(r * t) get: v = c2 * e^(r * t) + (c1 + c2 * t) * r * e ^ (r * t) .
4. When t = 0, get: y = c1, v = c2 + c1 * r, then c2 = v - c1 * r .
5. So I think this code should be: "final double c2 = velocity - (r * distance);" , but not "final double c2 = velocity / (r * distance );".
6. I calculated many times and tried to make sure every step of my calculation was right, always got this result.
7. Was this a mistake or am I wrong?
8. Thank you. 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by LevisonNN** [comment]
![image](https://user-images.githubusercontent.com/78127587/185089944-3e164453-ce13-40b9-a6f4-1d454ec191d4.png)

**Comment by danagbemava-nc** [comment]
Labeling for further insight from the team. 

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/physics/spring_simulation.dart#L177-L187

**Comment by gnprice** [comment]
I agree this is wrong.

I found it as part of investigating #120338, when I went and audited all the simulations the framework uses for scroll physics to try to confirm that each one was consistent with the scroll protocol's invariant #120341 that requires the scroll physics to make at least a certain kind of sense physically. One consequence of this bug is that it does not satisfy that invariant.

Another salient consequence of this bug is that the simulation's actual initial velocity can be very different from the requested initial velocity `velocity`:
* Specifically, the initial velocity is `c2 + r * distance`.
* With the buggy formula, this is `r * distance + velocity / (r * distance)`.
* This is a very different formula from `velocity`, and depending on the numbers involved it can produce very different results.

I have not yet tried to exercise this behavior in the context of an app. I'm not yet sure exactly what effect it has for users.

**Comment by gnprice** [comment]
Looking closer, I think in fact we never actually use `_CriticalSolution` for any widget in the framework.

As a result, this will not affect any app unless it calls a `SpringDescription` constructor for itself and manages to create a spring description that `_SpringSolution` recognizes as critically damped. That happens only when `damping * damping - 4 * mass * stiffness` is equal to `0.0` — not just within tolerance, but equal as `double`s.

---

There are four `SpringDescription` constructor call sites in the framework.  All are constants.

* The two found in `scroll_physics.dart` are both explicitly overdamped, with `ratio: 1.1` and `ratio: 1.3` respectively.

* The spring in `cupertino/sliding_segmented_control.dart` is very close to critically damped. But because its parameters are written to "only" six significant figures, it ends up with a damping ratio of 1.0000007, very slightly overdamped, and so does not use this code.

* The spring used by default in `AnimationController.fling` is constructed to be critically damped:
  ```dart
  final SpringDescription _kFlingSpringDescription = SpringDescription.withDampingRatio(
    mass: 1.0,
    stiffness: 500.0,
  );
  ```
  It uses that constructor's default damping ratio, which is `double ratio = 1.0`.

  But this means a `SpringDescription.damping` field of `ratio * 2.0 * math.sqrt(mass * stiffness)`, which as a `double` is 44.721359549995796. And plugging that into the above formula gives 2.2737367544323206e-13 ­. Very close to zero, but not equal.

  Instead that value is positive, so the spring is treated as overdamped.

So, left to its own devices, the framework only ever uses `_OverdampedSolution`, even though two of the four springs are overdamped only due to rounding. It never uses `_CriticalSolution`, nor `_UnderdampedSolution`, unless the app creates its own `SpringDescription` for such a spring.

If an app does create a critically-damped `SpringDescription` and try to use it, I expect it would see wildly wrong behavior due to this bug.

I have a fix for this issue. I'll send a PR.
