### ISSUE TITLE
App fails to recompile on Android after upgrading to Flutter 3. Execution failed for task ':app:compileFlutterBuildDevelopmentDebug'.

### ISSUE THREAD

**Issue by Bajerskov** [flutter/flutter#109600]
## The issue
I am currently using flutter to develop a new app  - we have been using flutter 2.10 for a while but wanted to upgrade to version 3 which we did last week. But we have had nothing but problems since in the dev team. 

The app will now run but only if we delete the /build and /android/app/build folders. We cant recompile the app at the moment.
Also the app will randomly crash when developing with fatal crashes and randomly breakpoints used in vscode debug will crash the app.

I can't find any fixes to the current issues and running a new project with flutter create works fine. 

## Steps to Reproduce
I can not provide an example of the code to reproduce- as the code base is massive and i have no clue where to start. I Suspect it has nothing to do with the code anyways - i have instead provided the pubspec.yaml file as it is more likely to come from android compiling and its dependencies. 

## Steps i have already attempted

I have tried deleting the flutter sdk and redownloading it from the website - with no results.
I have tried disabling most dependencies and recompiling while enabling them one after one - but not while also deleting build folder. no errors here. 

I have ran the following commands;
* flutter clean
* flutter pub cache repair
* flutter channel master
* flutter pub upgrade

**Comment by huycozy** [comment]
Hi @Bajerskov 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project,
but to improve flutter reporting bugs or with feature requests.

From your `pubspec.yaml` file, there are many 3rd party plugins that could cause this issue so we are not sure can give you a proper solution for this. But from the logs (`log-compilation-failed.txt`):

> [        ] * What went wrong:
[        ] java.lang.StackOverflowError (no error message)

It looks like this StackOverflow answer can solve the issue: https://stackoverflow.com/a/72514048/5921933.
Let's try it to see if the issue is still reproducible.

**Comment by Bajerskov** [comment]
@huycozy Appologies - I will move to another platform to find an answer.
I appreciate the effort - unfortunatly it had no effect.

**Comment by huycozy** [comment]
Hi @Bajerskov 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! Thanks for your contribution.
