### ISSUE TITLE
Autosubmit keeps failing to merge PR silently without removing label and acking message

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#109754]
github.com/flutter-tests do not have a luci-status and the autosubmit bot keeps checking for it to available.

**Comment by godofredoc** [comment]
The problem is that if merging fails the label is not removed but the message is acked.

**Comment by godofredoc** [comment]
This is the error generating this issue:

```auto_submit: Failed to merge pr#: 144 with OperationException(linkException: null, graphqlErrors: [GraphQLError(message: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information., locations: [ErrorLocation(line: 2, column: 3)], path: [mergePullRequest], extensions: null)])```

**Comment by godofredoc** [comment]
Expected behavior is to either remove the label on failure or do not ack the message.

**Comment by keyonghan** [comment]
> The problem is that if merging fails the label is not removed but the message is acked.

When merging fails, the label will not be removed (expected because this is due to github graphql api error and we should retry without removing the label), and the message will not be acked either. See
https://github.com/flutter/cocoon/blob/main/auto_submit/lib/service/validation_service.dart#L149-L151 (message will only be acked when PR merging succeeds). So I do not see any problem here.

Is the bug `github.com/flutter-tests do not have a luci-status and the autosubmit bot keeps checking for it to available.`? If yes, we should handle the status check in the `ci_successful` validation instead.

**Comment by keyonghan** [comment]
Updated the title to reflect the issue.
