### ISSUE TITLE
iOS scroll fling behaviour doesn't match

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10977]
The following video was recorded by running [the scroll overlay app](https://github.com/flutter/scroll_overlay) on iOS:

[![Click to play video](https://img.youtube.com/vi/vC4nwdyUBto/0.jpg)](https://youtu.be/vC4nwdyUBto)

It shows that Flutter's scroll physics have too much resistance when the user initiates the scroll via a slow swipe.

**Comment by tvolkert** [comment]
FYI @xster @cbracken

**Comment by Hixie** [comment]
Related: https://github.com/flutter/flutter/issues/10977 https://github.com/flutter/flutter/issues/10976 https://github.com/flutter/flutter/issues/10972

**Comment by xster** [comment]
@tvolkert did you have a local fork of that demo app?
https://github.com/flutter/scroll_overlay/blob/master/lib/main.dart is the default template app. 

Just wanted to make sure I tested the exact same thing you did

**Comment by xster** [comment]
Created some tests with https://github.com/flutter/scroll_overlay/pull/5

With some testing, it seems like our physics simulation is fine. It's just the velocity tracker having trouble matching the platform's numbers.

**Comment by xster** [comment]
A big more digging trying to classify the fidelity issues into classes symptoms. 

**Context:**

- 'Muzzle velocity' at the end of the swipe, from testing, correlates 100% with whether the flutter scrollable scrolls at the same rate or faster or slower than the platform scrollable. i.e. the physics simulation works correctly and that velocity is the right goal metric to match.
- The input sampling rates are the same at 60hz between the platform gesture recognizers and the inputs into the velocity tracker. The timestamps and intervals are exactly the same as well.

**Category 1:**

The most common issue type where the flutter app ends up having a slower velocity than the native pan gesture recognizer after a common natural fling motion. 

Looking at the input signals into the velocity tracker on both device and simulator has a common trend. (x axis is time and y axis is position along scrolling axis)

![screen shot 2017-07-12 at 12 26 14 pm](https://user-images.githubusercontent.com/156888/28136110-621cd464-66fd-11e7-8ef5-25fb4ef844a0.png)
![screen shot 2017-07-12 at 12 26 22 pm](https://user-images.githubusercontent.com/156888/28136111-621e3656-66fd-11e7-9a83-fce5a0044287.png)
![screen shot 2017-07-12 at 12 26 29 pm](https://user-images.githubusercontent.com/156888/28136112-6220df82-66fd-11e7-8f1d-0e4636043a94.png)
![screen shot 2017-07-12 at 12 26 39 pm](https://user-images.githubusercontent.com/156888/28136113-6224340c-66fd-11e7-88bf-7abb0bb00c68.png)

The input curves are nearly identical but there's a plateau at the end of the curve where UIGestureRecognizerDelegate sends a last `touchesEnded` one frame after the last `touchesMoved` call with the same position values.  The platform gesture recognizer ignores it in its velocity calculation whereas we're not weighing different attributes of the `PointerEvent` differently in our velocity calculation and our velocity drops between the last `touchesMoved` and the last `touchesEnded` events. 

**Category 2:**

(Blue is native, red is flutter)
![screen shot 2017-07-12 at 12 52 09 pm](https://user-images.githubusercontent.com/156888/28137169-28cd3696-6701-11e7-91f6-88971d089b42.png)
Occasionally the input values differ a bit. 

**Steps:**

- [ ] Solve category 1 first. Use more `PointerEvent` signals.
- [ ] Muzzle velocity ignoring the last event is still different between. Try to match the velocity estimation at every point. Probably machine curve-fit-able.

**Comment by mit-mit** [comment]
Does this also cover https://github.com/flutter/flutter/issues/10401 ?

**Comment by xster** [comment]
Yes, it's the same problem/task.

**Comment by xster** [comment]
Part of the problem here is that our PointerEventConverter has a special filter to change platform's touch up events into a move event to enforce the API contract that we have a move to the exact position of the up event. But we lose the up event in the process since on iOS physical device and simulator, there's a tiny wobble between the last move and the up gesture events. 

Because of the framework-side conversion, we're losing the original platform's semantic signal to deduce whether it's an up event with an iOS minor final position adjustment or a legitimate user slowing down the fling. 

We also have the same issue on Android but Android sends its touch up event at the exact same position as the last move event so we can filter out the noise from the velocity tracker by weighing PointerUpEvent differently.

**Comment by Hixie** [comment]
Do you mean we lose the up event coordinate?

**Comment by xster** [comment]
At https://github.com/flutter/flutter/blame/master/packages/flutter/lib/src/gestures/converter.dart#L242, we lose the fact that it was originally an up event type from the platform. 

I propose adding a new field to PointerEvent that records the exact original platform event type. 

The alternative is to change the tracker algorithm to weigh the last input less rather than weighing 'highly likely redundant' signals like up events less. But that feels looser.

**Comment by Hixie** [comment]
@xster #11571 landed, does that mean this is fixed or is there more to do?

**Comment by xster** [comment]
Will close this one which closes the major difference in feel. Remaining tasks #11592 and #11772.
