### ISSUE TITLE
Bogus data reported to SkiaPerf for complex_layout_win_desktop__start_up

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#109859]
See the timeToFirstFrameMicros metric in: https://flutter-flutter-perf.skia.org/e/?begin=1660685403&end=1660881566&keys=Xfd148d146a2c79cf37902d0d6717aa13&requestType=0&xbaroffset=30558

cc @cbracken

**Comment by cbracken** [comment]
Thanks for reporting; @yaakovschectman can you take a look at what numbers we're collecting and publishing in this test on Windows?

**Comment by yaakovschectman** [comment]
This appears to be a result of the engine startup timeline event firing before the Dart VM is initialized, so its call to `Dart_TimelineGetMicros` returns a wildly different result than when that function is called after the VM is initialized. Without changing the Dart VM itself, the best approach would be to make the engine enter event an instantaneous event fired right after the VM is initialized so that all events are timed the same way, instead of switching from epoch to QPC.

**Comment by yaakovschectman** [comment]
Marking closed due to [flutter/engine#35713](https://github.com/flutter/engine/pull/35713)
