### ISSUE TITLE
[local_auth] - on IOS secure code screen pushed after deny permissions

### ISSUE THREAD

**Issue by Andestrial111** [flutter/flutter#109857]
Hi guys, when you set false parameter to "biometricOnly" on IOS and on first setup deny the permission about using biometric , you'll receive a secure code screen .

**Comment by danagbemava-nc** [comment]
Hi @Andestrial111, please provide a complete description of what the issue is and what you expected the behaviour to be. 
Your description is not clear on what exactly the issue is here. 

Please also provide the output of `flutter doctor -v` as well as the version of `local_auth` you're using. 
Please also provide a minimal complete reproducible code sample as well. 

Thank you

**Comment by Andestrial111** [comment]
Hi @danagbemava-nc 
local_auth: ^2.1.2

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm, locale en-UA)
    • Flutter version 3.0.0 at /Users/andestrial/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/andestrial/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

**Issue:**
[when 'biometricAuth: false'] On IOS device after deny permission about biometric authentication screen with "provide secure code" will popping up 

**Actual result:**
Screen with "provide secure code" will popping up

**Expected result** 
User successful deny permissions and screen with "provide secure code" after deny permissions will not showing.

https://user-images.githubusercontent.com/111578945/185888912-176071e5-ed02-4cdf-b071-361c671ba771.mov

**Comment by danagbemava-nc** [comment]
Hi @Andestrial111, I believe this is working by design.

If you set the `biometricOnly` flag to false, what that means is it should fall back to the device authentication method, which is the PIN that the user has to enter. 
If you don't want the authentication to fallback to the device authentication method, you can set it to true instead. 

Are you requesting to have the option to decide when that screen shows up?
