### ISSUE TITLE
Running update-excerpts command with homebrew installed dart sdk fails

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#109824]
Upon running the command

```$ dart run ./script/tool/bin/flutter_plugin_tools.dart update-excerpts --packages {package name}```

I receive the error

```
============================================================
|| Running for video_player/video_player
============================================================

Running command: "dart pub get" in **/plugins/packages/video_player/video_player/example
Resolving dependencies...
Because video_player_example requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
```

Notes from @stuartmorgan on the issue:

This is likely caused by my previous installation of dart via homebrew.

Usually we're running Dart from the Flutter installation

We should factor out the logic that decides which get to use from a place where it's correct (analyze is one IIRC) and use it everywhere.

In the short term putting your Flutter install location earlier in your path should avoid the bug

**Comment by stuartmorgan** [comment]
> We should factor out the logic that decides which get to use from a place where it's correct (analyze is one IIRC) and use it everywhere.

I forgot that in https://github.com/flutter/plugins/pull/3973 we standardized on just using `flutter pub get`, so we could fix this by just changing `'dart'` to `flutterCommand` anywhere we are doing a `pub get`.

Given that we have several copies of that code though, it's probably worth extracting the analyze command's `_runPubCommand` as a general-purpose utility in `common/`, and updating all the other code to use that.

**Comment by stuartmorgan** [comment]
> In the short term putting your Flutter install location earlier in your path should avoid the bug

To provide a little more context on this: the Flutter SDK "re-exports" `dart` (in that it puts it in the same `bin/` dir as `flutter`), so if your only Dart install is via Flutter, you're automatically running Dart from the Flutter SDK (and since we haven't been hit by this bug before, apparently it automatically knows how to access the Flutter SDK in that case, even if it's called directly and not through `flutter pub`). But if you have a stand-alone Dart install earlier in the path, the that version of Dart won't know about Flutter, thus the error.

The tool code has always been wrong, we just hadn't noticed because this command still pretty new, and everyone who has run it so far (including our CI) is using a Flutter-managed version of Dart.

**Comment by tarrinneal** [comment]
changing the 'dart' pub get to flutterCommand doesn't fix the problem with other dart sdk sources. I'm going to dive a little deeper to see what else I can find

**Comment by tarrinneal** [comment]
To clarify, there are two other non pub dart commands later in the tool that are likely causing this issue

**Comment by tarrinneal** [comment]
The code that is erroring is actually in the build_runner code, which is a dart-lang package, I'm not sure this can be fixed plugin tool side.
