### ISSUE TITLE
[web]: PWA not showing option to install

### ISSUE THREAD

**Issue by Kings-Samuel** [flutter/flutter#109869]
I have launched about 3 Flutter web projects in the past couple of months. I use HTML as my preferred web renderer, but one thing I have noticed is that I no longer see that button on Chrome search bar or on the more menu to install the app to my PC as a PWA. I literally have to save the web page as a shortcut for each of the projects.

**Comment by huycozy** [comment]
Hi @Kings-Samuel, sorry for replying late.
But I can not reproduce the issue on the latest `stable` and `master` channels.
I build Web app with HTML renderer and the can see PWA install button on the Chrome search bar.

<details>
<summary>Demo</summary>

https://reproduceissues.web.app

![Screenshot 2022-08-24 at 13 25 13](https://user-images.githubusercontent.com/104349824/186345979-9fb13121-0052-411c-96f7-523f3ac2b483.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```bash

```
</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
