### ISSUE TITLE
iOS : Vertex Function(vertexMain): argument _anonInterface0[0] from buffer(0) with offset(0) and length(24) has space for 24 bytes, but argument has a length(32).

### ISSUE THREAD

**Issue by ashishazilen** [flutter/flutter#109979]
Hi 

iOS Webview Page showing blank

Error :

validateFunctionArguments:3727: failed assertion `Vertex Function(vertexMain): argument _anonInterface0[0] from buffer(0) with offset(0) and length(24) has space for 24 bytes, but argument has a length(32).'

Can anyone please help?

**Comment by darshankawar** [comment]
@ashishazilen 
When opening an issue, please use new issue template and provide all requested details so that we'll have enough details to work with.


> Can anyone please help?

Please ask this on support channels like StackOverflow.

Closing from here, due to lack of details and maybe a support question. If you think this is a genuine issue in webview_flutter plugin for ios, please fill up template so that we can help you properly.
