### ISSUE TITLE
`flutter pub get` should warn if the target directory does not exist 

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#110027]
## Use case

The names `flutter pub add` and `flutter pub get` are confusing. Incorrectly using the `flutter pub get` command to install a package produces output that appears to be successful.

For example, imagine a user attempts to install `go_router` incorrectly using the `get` subcommand:

```
PS C:\Code\my_project> flutter pub get go_router
Running "flutter pub get" in ....                                  509ms
```

This output misleads the user into thinking `go_router` was installed.

## Proposal

The `get` subcommand should warn if the target directory does not exist. For example:

```
PS C:\Code\my_project> flutter pub get go_router
Warning: Could not find target directory 'go_router'. If you meant to install a package, use 'flutter pub add'.
Running "flutter pub get" in ....                                  509ms
```

/cc @sigurdm @jonasfj @szakarias

**Comment by maheshmnj** [comment]
This seems like a reasonable proposal to avoid confusion, Running the below incorrect command doesn't warn
 or show any incorrect message.

```bash
mahesh@Maheshs-MacBook-Air-M1 sample % flutter pub get go_router
Running "flutter pub get" in ....                                1,988ms
mahesh@Maheshs-MacBook-Air-M1 sample % 
```

**Comment by jonasfj** [comment]
The `flutter pub get` command should not take any arguments.

The `dart pub get` never took any arguments, and this behavior has been making it hard to bring new features like `flutter pub upgrade --major-versions` to flutter users.

We did introduce `dart pub get -C path/to/folder` for people that really need this logic.

IMO, the right choice here is for `flutter pub ...` to mirror `dart pub ...` in terms of arguments / options.

Hence, I would advocate finding a mechanism for removing `flutter pub get/upgrade <folder>` in favor of `flutter pub get/upgrade -C <folder>`.

**Comment by christopherfujino** [comment]
cc @nehalvpatel

**Comment by Jasguerrero** [comment]
If we decide to remove the feature of `flutter pub get` to receive arguments I can file another separate issue and add the propose warning for this issue in the meantime

**Comment by nehalvpatel** [comment]
That sounds good. I imagine this warning can serve as a starting point for nudging the community's understanding of the `get` command.

So, the separate issue's proposal would be to:
- [Similar to `dart pub`](https://dart.dev/tools/pub/cmd#--directorydir-or--c-dir), add `--directory=<dir>` and `-C <dir>` options to `flutter pub`
- Deprecate/remove the argument from `flutter pub get [<target directory>]`

**Comment by Jasguerrero** [comment]
This is a tricky issue to understand what is going, the actual behavior of `flutter pub get <directory>` first tries to find a `pubspec.yaml` in the passed `<directory>` if nothing is found it tries to go to the parent directory of `<directory>` until a `pubspec.yaml` is found. But there is what I believe is a bug in here https://github.com/flutter/flutter/blob/3.3/packages/flutter_tools/lib/src/base/os.dart#L597 what this function is doing in this example is trying to get the parent directory of `go_router` but since it does not found one what is returned is `.` pointing to the current working directory in which I believe @loic-sharma and @maheshmnj have a valid `pubspec.yaml` file (if any of you could confirm this it would be great). If you see the output `Running "flutter pub get" in ....` there is 4 points which is not a typo but actually the first point is the current directory. Additionally if you try `flutter pub get` on a directory that none of its parents has a `pubspec.yaml` there is a `throwToolExit` with a message `Expected to find project root in /directory.`.

The proposed fix is to instead relying on `fileSystem.path.dirname(directory)` we first look if `directory` exists and then iterate over the parent. Let me know what you think @christopherfujino
