### ISSUE TITLE
Address null safety exclusions in flutter/plugins

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#110017]
See https://github.com/flutter/flutter/issues/110016 for context.

- [x] fix `google_sign_in/google_sign_in/example/integration_test/google_sign_in_test.dart:5:// @dart = 2.9`:
https://github.com/flutter/plugins/pull/6302
- [x] fix `google_sign_in/google_sign_in/example/test_driver/integration_test.dart:5:// @dart=2.9`:
https://github.com/flutter/plugins/pull/6302
- [x] fix `quick_actions/quick_actions/example/integration_test/quick_actions_test.dart:5:// @dart = 2.9`:
https://github.com/flutter/plugins/pull/6302
- [x] fix `quick_actions/quick_actions/example/test_driver/integration_test.dart:5:// @dart=2.9`:
https://github.com/flutter/plugins/pull/6302
- [ ] fix `video_player/video_player_platform_interface/pigeons/messages.dart:5:// @dart = 2.9`:
TODO @stuartmorgan

**Comment by stuartmorgan** [comment]
The first four should be trivial; I just sent a PR. I'm not sure why they are still there since I thought we scrubbed those.

The last one I'll need to think about. The problem is that we made the mistake of putting a Pigeon-generated API into the platform interface package, and updating the version of Pigeon (to one supporting NNBD) is therefore a breaking change, and we try to avoid making platform interface breaking changes whenever possible. We well have no choice here though.
