### ISSUE TITLE
[go_router] How can I don't remain history when redirect?

### ISSUE THREAD

**Issue by surnks** [flutter/flutter#110144]
In flutter web,
I want to redirect from '/home/11' to '/' without history (can't move back in browser.)
like location.replace('/').

What kind of ways are there?

  GoRoute(
    path: '/home/:homeid',
    redirect: (state) {
      return '/';
    },
  ),
  GoRoute(
    path: '/',
    pageBuilder: (context, state) {
      return NoTransitionPage(
        key: state.pageKey,
        child: Home(),
      );
    },
  ),

**Comment by darshankawar** [comment]
@surnks 
If you are looking for a solution or other ways to implement redirect without history, I suggest you to ask this question on support channels like StackOverflow. 
If you think this is a bug or a feature request to improve the redirect behavior, please open new issue with appropriate template so that we can address it accordingly.

Closing for now.
