### ISSUE TITLE
Document how to share assets between Dart and OEM-side code

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11019]
If you're creating an app that has native and flutter components there is no way to share images or fonts between flutter and android/ios. This means that assets needed on both sides will have to be included in the binary twice and that could be expensive.

**Comment by collinjackson** [comment]
Posse has identified this as a launch blocker

**Comment by sethladd** [comment]
Another reason to eliminate FLX? https://github.com/flutter/flutter/issues/9900

**Comment by collinjackson** [comment]
@tvolkert volunteered to take this one

**Comment by collinjackson** [comment]
Priority has been adjusted, I removed customer blocker tag. Hopefully the extra breathing room will let us do this in the "right way" even if it takes longer.

**Comment by sethladd** [comment]
I believe this came up again, in this Stack Overflow question: https://stackoverflow.com/questions/45428388/how-to-display-an-html-asset-file?utm_source=dlvr.it&utm_medium=twitter

(there may be different solutions to the problem, but it might be easier if the .html file bundled with the app wasn't stuck inside the FLX?)

**Comment by Hixie** [comment]
yes, we should just get rid of the FLX.

**Comment by Hixie** [comment]
Leaving in current milestone since dropping FLX is on our short-term priority list.

**Comment by Hixie** [comment]
cc @szakarias

**Comment by xster** [comment]
@szakarias, are there new instructions / docs on this? I'm guessing there are some updates since the flx has been removed.

**Comment by szakarias** [comment]
No new instructions. We will be redesigning the asset API fairly soon and hopefully this will be solved.

**Comment by cbracken** [comment]
Related #11892.

@szakarias any updates?

**Comment by tvolkert** [comment]
@szakarias was this fixed by flutter/engine#4742?

**Comment by MichaelSowah** [comment]
@tvolkert https://github.com/flutter/flutter/issues/11019....am getting confused now about this asset issues all over...

**Comment by MichaelSowah** [comment]
am also looking forward to being able to upload bulk images at once and dont need to do it one by one like its currently being handled...

**Comment by tvolkert** [comment]
@szakarias with the asset re-work, we should be moving towards the goal of storing our assets in the locations that the underlying platform would otherwise store them.  e.g. for Android, 

```
res/
    drawable/
    drawable-hdpi/
    drawable-mdpi/
    drawable-xhdpi/
    drawable-xxhdpi/
    drawable-xxxhdpi/
```

There a suites of tools for packing, optimizing, and so forth an app's final bundle that gets distributed through app stores, and they all assume a certain layout of assets.  Our current layout, harking from the days of FLX, doesn't play nicely with these tools.  But now that we've gotten ourselves away from FLX, we should have more flexibility here.

e.g. for Android, they're moving towards a model where you don't upload an APK to the Play Store, but rather upload all the constituent parts of your APK, and when a user installs an app, the store cleverly constructs the thinnest APK it can ship to the user, containing only the assets that make sense for that user's device-pixel-ratio, locale, etc.

Just making sure that that end goal lines up with what this issue is tracking.

**Comment by szakarias** [comment]
With the recent engine changes https://github.com/flutter/engine/pull/4817 and https://github.com/flutter/engine/pull/4785, it is now possible to share assets with native by accessing the Flutter assets through the main bundle on iOS and the AssetManager on Android. Once I document that on our website I will close this issue which is about avoiding asset duplication across platforms.

As a next step it would be great to align even more with the underlying platform, I created #16015 to track this.

**Comment by szakarias** [comment]
Fixed, see the [documentation](https://flutter.io/assets-and-images/#sharing-assets-with-the-underlying-platform).

**Comment by MichaelSowah** [comment]
@szakarias are these fixes and changes in the dev channel yet or I need to be on master channel?

**Comment by szakarias** [comment]
Should be on dev 0.2.7.

**Comment by MichaelSowah** [comment]
@szakarias Thanks
