### ISSUE TITLE
macOS clang roll failing due to missing remove_reference_t

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110140]
Starting with https://github.com/flutter/engine/pull/35653.

```
In file included from ../../third_party/skia/src/core/SkSharedMutex.cpp:8:
In file included from ../../third_party/skia/src/core/SkSharedMutex.h:13:
In file included from ../../third_party/skia/include/private/SkSemaphore.h:14:
In file included from /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:643:
In file included from /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:677:
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tuple:1427:52: error: use of undeclared identifier 'remove_reference_t'
        typename __make_tuple_indices<tuple_size_v<remove_reference_t<_Tuple>>>::type{})
```

**Comment by fzyzcjy** [comment]
Looks like it is P0 - very serious. Is there anything I can help?

**Comment by jason-simmons** [comment]
As of https://github.com/flutter/buildroot/pull/349 some builds are using the standard library headers packaged with Xcode instead of `third_party/libcxx`.

The latest Clang supports the `__has_keyword(__remove_reference)` extension.  With that enabled, the Xcode version of `type_traits` is not defining `std::remove_reference_t`.

I can get this to build by patching Xcode's `type_traits` to move the definition of `remove_reference_t` outside the `#else // __has_keyword(__remove_reference)
` block.  I don't know if there is any version of Xcode that provides a fix like that.

It might make sense to switch to using `third_party/libcxx` on the affected platforms.

@jmagman @chinmaygarde

**Comment by zanderso** [comment]
> It might make sense to switch to using third_party/libcxx on the affected platforms.

@jason-simmons Are you able to give this a shot?

**Comment by jason-simmons** [comment]
Tried switching to `third_party/libcxx` instead of using the Xcode standard library headers on iOS.

With that change, the linker outputs this error when doing a bitcode build with LTO enabled:
```
ld: reference to bitcode symbol '___gxx_personality_v0' which LTO has not compiled in '___gxx_personality_v0' for architecture arm64
```

The only way I've found to get the LTO/bitcode build to complete is changing `___gxx_personality_v0` in `third_party/libcxxabi` to have default visibility.

That can be done by removing the `_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS` define in the libcxxabi build script.  But that will export all symbols in libcxxabi in the resulting `Flutter.framework/Flutter` library, which is undesirable.

Another option would be only exporting the necessary symbol by patching libcxxabi to mark `__gxx_personality_v0` with `__attribute__((visibility("default")))`.  We could also add `__attribute__((weak))` to reduce potential conflicts.

**Comment by jmagman** [comment]
@jason-simmons you went the `_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS` way in https://github.com/flutter/buildroot/pull/606, did exporting all the symbols increase the size of the binary?

**Comment by jmagman** [comment]
Nevermind I see it was reverted https://github.com/flutter/engine/pull/35758

**Comment by chinmaygarde** [comment]
This is pending on the linked buildroot roll. Per Jason, this should be done soon.

**Comment by chinmaygarde** [comment]
This is fixed. Though there hasn't been a roll of clang since then. But everything is unblocked.
