### ISSUE TITLE
Is it normal when valid issue is closed and ignored by one triage team member?

### ISSUE THREAD

**Issue by PashaTurok** [flutter/flutter#110341]
I opened absolutely valid issue [here](https://github.com/flutter/flutter/issues/109983). I gave full code and explanations. 

After that one triage team member gives absolutely different solution and closes my issue marking it as invalid. Is is normal? I just want to understand how Flutter community works so I could know what I should do and what I shouldn't.

**Comment by darshankawar** [comment]
@PashaTurok 
Let's track this in the original issue and it would be great if you could respond to https://github.com/flutter/flutter/issues/109983#issuecomment-1229249249 in that issue, so that we can help you accordingly. 
Also, you may take a look at below links / solutions and see if they help in your case:

https://github.com/flutter/flutter/issues/18108#issuecomment-394745137
https://github.com/flutter/flutter/issues/18108#issuecomment-570626087
https://github.com/flutter/flutter/issues/18108
https://github.com/flutter/flutter/issues/63469#issuecomment-672744097
https://github.com/flutter/flutter/issues/63469#issuecomment-672798305
https://github.com/flutter/flutter/issues/63469#issuecomment-756034626

Closing from here in favor of linked issue.
