### ISSUE TITLE
Flutter web build is broken on master and beta via docker - Target dart2js failed: Exception

### ISSUE THREAD

**Issue by 4F2E4A2E** [flutter/flutter#110462]
Flutter build web is currently broken on the beta and master channel. 
All steps are reproducible via the Dockerfile.

```bash
Compiling lib/main.dart for the Web...
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.

Exception: Failed to compile application for the Web.
```

Dear flutter team, please help me out in fixing this or finding the missing dependency on this. 

<details>
  <summary>Dockerfile</summary>

```bash
FROM ubuntu:22.10

RUN apt-get update
RUN apt-get install -y \
    curl git wget python3 zip unzip \
    apt-transport-https ca-certificates \
    gnupg clang cmake ninja-build pkg-config libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 libgtk-3-dev
RUN apt-get clean

RUN git clone -b master --depth 1 https://github.com/flutter/flutter.git /usr/local/flutter

RUN chmod 755 -R /usr/local/flutter
ENV PATH="${PATH}:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin"

RUN flutter channel master
RUN flutter upgrade
RUN flutter config --enable-web
RUN flutter doctor -v

RUN git config --global --add safe.directory /usr/local/flutter
RUN flutter create web_build_test && cd web_build_test && flutter build web
```
</details>

<details>
  <summary>flutter build web -v</summary>

```bash
   Woah! You appear to be trying to run flutter as root.flutter build web -v
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[  +94 ms] executing: uname -m
[  +45 ms] Exit code 0 from: uname -m
[   +1 ms] x86_64
[   +6 ms] executing: [/usr/local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 281c2b9a6889ce6d2e474ddc9f25d73d111c801a
[        ] executing: [/usr/local/flutter/] git tag --points-at 281c2b9a6889ce6d2e474ddc9f25d73d111c801a
[  +16 ms] Exit code 0 from: git tag --points-at 281c2b9a6889ce6d2e474ddc9f25d73d111c801a
[   +1 ms] executing: [/usr/local/flutter/] git describe --match *.*.* --long --tags 281c2b9a6889ce6d2e474ddc9f25d73d111c801a
[  +65 ms] Exit code 0 from: git describe --match *.*.* --long --tags 281c2b9a6889ce6d2e474ddc9f25d73d111c801a
[        ] 3.0.0-0.0.pre-2539-g281c2b9a68
[  +74 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] Unable to locate an Android SDK.
[   +6 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +185 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +75 ms] Skipping pub get: version match.
[ +216 ms] Generating /home/fluttter_create_sample_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +113 ms] 💪 Building with sound null safety 💪
[  +36 ms] generated_plugin_registrant.dart not found. Skipping.
[   +2 ms] Compiling lib/main.dart for the Web...
[  +14 ms] Initializing file store
[  +51 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /usr/local/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[   +2 ms] Skipping target: gen_localizations
[  +13 ms] web_static_assets: Starting due to {}
[  +95 ms] web_static_assets: Complete
[   +1 ms] web_entrypoint: Complete
[   +8 ms] dart2js: Starting due to {}
[+81111 ms] Persisting file store
[  +10 ms] Done persisting file store
[   +6 ms] Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
           
[  +39 ms] Compiling lib/main.dart for the Web... (completed in 81.3s)
[   +7 ms] "flutter web" took 81,999ms.
[  +17 ms] Exception: Failed to compile application for the Web.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:96:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:117:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +259 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
root@ce61d7a6315a:/home/fluttter_create_sample_project# 
```
</details>

**Comment by 4F2E4A2E** [comment]
Did you see the dockerfile? That's all.

**Comment by exaby73** [comment]
What I am trying is the following:

```
docker build . -t issue_110462
docker run issue_110462
```

This isn't producing logs for me. Sorry I'm not very familiar with Docker. I have also tried building the app on Ubuntu 22.04 LTS, with success.

**Comment by hbbtekademy** [comment]
Getting same issue without docker also. Just create sample project using `flutter create` and then build using `flutter build web`.
My target platform is only web, hence Android Studio/SDK has not been installed.
This would be a build server where I will checkout required version of code and trigger the web build.


Steps:
```bash
flutter create sample_project
Creating project sample_project...
Running "flutter pub get" in sample_project...                      4.9s
Wrote 127 files.

All done!
In order to run your application, type:

  $ cd sample_project
  $ flutter run

Your application code is in sample_project/lib/main.dart.

cd sample_project/
flutter build web -v
```

<details open>
<summary>flutter build web -v</summary>
<br>
<pre>
flutter build web -v
[ +106 ms] executing: uname -m
[  +51 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: [/home/hbb/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [/home/hbb/flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +16 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[  +12 ms] executing: [/home/hbb/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/hbb/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +74 ms] Unable to locate an Android SDK.
[   +6 ms] executing: [/home/hbb/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +84 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +77 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +75 ms] Skipping pub get: version match.
[ +225 ms] Generating /home/hbb/build/flutter/sample_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +99 ms] 💪 Building with sound null safety 💪
[  +78 ms] Compiling lib/main.dart for the Web...
[   +9 ms] Initializing file store
[  +44 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/hbb/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[  +12 ms] web_entrypoint: Complete
[  +20 ms] Skipping target: gen_localizations
[   +1 ms] web_static_assets: Starting due to {}
[ +108 ms] web_static_assets: Complete
[   +1 ms] dart2js: Starting due to {}
[+113817 ms] Persisting file store
[  +32 ms] Done persisting file store
[  +14 ms] Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
[  +75 ms] Compiling lib/main.dart for the Web... (completed in 114.1s)
[   +7 ms] "flutter web" took 114,754ms.
[  +21 ms] Exception: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:81:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:112:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +29 ms] ensureAnalyticsSent: 12ms
[   +2 ms] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
</pre>
</details>

<details open>
<summary>flutter doctor -v</summary>
<br>
<pre>
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04.1 LTS 5.15.0-46-generic, locale C.UTF-8)
    • Flutter version 3.0.5 at /home/hbb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-46-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
</pre>
</details>

**Comment by hbbtekademy** [comment]
The `Target dart2js failed` error is misleading. This is just a warning that is always printed to stdout when the dart2js command is executed.
My web build was failing on a grossly under provisioned VM (1vCPU/1GB RAM). Build was successful after running on larger VM with 2vCPU/4GB RAM).

Output of the dart2js command executed by the `flutter build web` command:
```bash
/home/hbb/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/hbb/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --libraries-spec=/home/hbb/flutter/bin/cache/flutter_web_sdk/libraries.json --native-null-assertions -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true --no-source-maps -o /home/hbb/build/flutter/sample_project/.dart_tool/flutter_build/f25c52552afad38f150965f830922262/app.dill --packages=.packages --cfe-only /home/hbb/build/flutter/sample_project/.dart_tool/flutter_build/f25c52552afad38f150965f830922262/main.dart
Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
```

Hello @4F2E4A2E, please check how much RAM is allocated when you are running the web build and see if increasing the RAM helps. I am suspecting the build crashes due to insufficient resources and the warning is displayed as an Exception.

**Comment by exaby73** [comment]
Hello. Can you still reproduce this issue on Flutter 3.3?

**Comment by PrimeTimeTran** [comment]
I'm also getting this error when running `flutter build web` in a containerized environment(Docker/Netlify). On my local `flutter build web` works great though. 

```sh
flutter --version          
Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4f9d92fbbd (7 days ago) • 2022-09-06 17:54:53 -0700
Engine • revision 3efdf03e73
Tools • Dart 2.18.0 • DevTools 2.15.0
```

**Comment by exaby73** [comment]
Can someone share a Dockerfile or Docker compose file that reproduces this issue? The one in the [OP](https://github.com/flutter/flutter/issues/110462#issue-1353916406) get's stuck on Ubuntu wanting to download something and is asking to enter `yes` which isn't working since it's non-interactive.

**Comment by PrimeTimeTran** [comment]
I discovered the solution in my case. It was incorrect casing on my file names.

I had `import 'package:flutpoke/classes/Round.dart';`

When the file was.

`import 'package:flutpoke/classes/round.dart';`

Remember to case the file name exactly the same in the import as it actually it. 

Thanks for your work team!
