### ISSUE TITLE
Make `onSelectionChanged` of SelectionArea equivalent to that of SelectableText

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#110594]
The `onSelectionChanged` callback was added to `SelectionArea` by #108985, but the callback is only given plain text. It is not equivalent to `onSelectionChanged` of `SelectableText`.

I asked @chunhtai about this in https://github.com/flutter/flutter/issues/108231#issuecomment-1231615901, so please refer to the comments starting from there.

## Use case

An app that has the feature to highlight a selected piece of text.

When a user selects "pick" in "Peter Piper picked a peck of pickled peppers", there is no way to tell which one of the two "pick"s in the sentence should be highlighted, without necessary info on the selection.

The above is of course just an example. There should be more use cases that require detailed text selection information.

## Proposal

The `onSelectionChanged` callback of `SelectableText` receives detailed information regarding text selection, like selection offsets. The arguments with the same name in `SelectionArea` should behave in the same way. It is not because both have the same name, but because I think there must be cases where some functionality that you want to implement in an app cannot be achieved without selection details.

**Comment by chunhtai** [comment]
The challenge here is what format of the return data should be like. Right now all the text is abstract into Selectable which is hard to make sense as a developer facing API. 

According to the original use case:

> An app that has the feature to highlight a selected piece of text.

Can this be solved with provide a way to specify text style of the selected text? For example in DefaultSelectionStyle, we add a field called selectedTextStyle.

To better design the solution, we need more use cases.

**Comment by Dall127** [comment]
@chunhtai here's another use case (was on another issue but rightfully marked as a duplicate): 

In the current implementation of SelectionArea, the callback only returns the selected text. However, for my use case, I need a TextSelection object that starts with an offset of 0 for each SelectionArea. This is important for distinguishing objects based on character offsets. For example, the word "can" at offsets 23-26 should be treated differently from another "can" at offsets 80-83, as they might have distinct contextual meanings. This change would also make the SelectionArea more consistent with SelectableText, which returns a TextSelection that includes the offsets.

I also added a pull request that makes _SelectableFragment -> SelectableFragment. The goal there being, we open up the door to typecast so we can create custom delegates that allow us to do the logic for this in our own code while the framework's design is still up in the air

**Comment by josephelliot-wk** [comment]
@chunhtai We also have a similar use case that we are trying to parse through.

### What we're trying to do

Render a list of paragraphs and let the user select text within and across these paragraphs. For example, given 10 paragraphs of length 100 each, the user may select text from `paragraph 0 offset 50` to `paragraph 3 offset 75`. In this example, they'd partially select `paragraph 0`, all of `paragraph 1 and 2`, and partially `paragraph 3`. They'd then be able to apply a "comment" to the selected regions.

### Data that we have

A list of paragraphs (basically text spans with text formatting on each span).

### What we need from Flutter

A way to render these paragraphs, select text across each paragraph, and get a selection range for each paragraph that is a part of the total selection range.

### Our options right now
1. Use one SelectableText widget and convert the monolithic text selection into a series of paragraph selections. This is complicated because we'd have to internally handle newline characters being injected, as well as parse all prior paragraphs to find the actual selections in each paragraph. Doable, but error prone.
2. Use multiple SelectableText widgets and cut our losses on "cross paragraph" selections.
3. Spin up a custom rendering solution at the render object layer. I'd have to learn more about the render object layer to say whether or not this is feasible.
4. Build a clone of [flutter's example basic text editor](https://github.com/flutter/samples/blob/main/simplistic_editor/lib/basic_text_field.dart) to facilitate our needs

### Ideal solution

Rely on the proposed implementation in https://github.com/flutter/flutter/pull/138041 to provide granular selection offsets on a per-text-widget basis.

**Comment by santiagos01** [comment]
re: @chunhtai 

> > An app that has the feature to highlight a selected piece of text.
> Can this be solved with provide a way to specify text style of the selected text? For example in DefaultSelectionStyle, we add a field called selectedTextStyle.

I think the issue here is not about to style it upon being selected, but also to be able to persist the highlights.

Example use cases: apps like Medium and Kindle, where you can highlight some text and store the highlighted positions so that whenever one opens an article/book/etc. again, the highlight would still be there.

Is there currently a way to do such thing?

**Comment by JeisonSanches** [comment]
@chunhtai 
> The challenge here is what format of the return data should be like. Right now all the text is abstract into Selectable which is hard to make sense as a developer facing API.

I highly recommend taking a look at the solution adopted by @ronjb (btw, thanks so much for that) in his [selectable](https://github.com/ronjb/selectable) package, especially the ability to insert (and later retrieve) tags in the text.
Here is the [TaggedText](https://github.com/ronjb/selectable/blob/main/lib/src/tagged_text.dart) model and the [Selection](https://github.com/ronjb/selectable/blob/main/lib/src/selection.dart) one (which makes use of the previous one).

I believe ronjb's solution could be very useful in defining a public API for this functionality.

> To better design the solution, we need more use cases.

Our usecase is similar to the ones mentioned above: we're making a custom book reader ( where each paragraph is a separate text entity) and we're trying to add multi-paragraph selection highlights, which will be persisted both locally and in the cloud.
