### ISSUE TITLE
Removing persistent frame callback

### ISSUE THREAD

**Issue by Amir-P** [flutter/flutter#110574]
I'm wondering is there any reason behind not providing a way to remove a persistent frame callback on Flutter's `WidgetsBinding`? Cause as far as I checked the code there shouldn't be any problem with removal of a persistent frame callback.

In my use case I need to listen for every frame and check metrics of a widget but I'm not happy with my callback being kept forever.

**Comment by exaby73** [comment]
Hello @Amir-P. Thank you for filing is request.

From the [documentation](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPersistentFrameCallback.html), looks like this is not possible. 

> Persistent frame callbacks cannot be unregistered. Once registered, they are called for every frame for the lifetime of the application.

Anyways, I'll label this issue so that we can get some more insights from the team on this. Thank you.

**Comment by Amir-P** [comment]
Thanks for your reply. Yes, I'm aware of what has been said in the documentation but there isn't any explanation on why this decision has been made. @exaby73
