### ISSUE TITLE
open url in background service when app is in kill state 

### ISSUE THREAD

**Issue by bhagat-techind** [flutter/flutter#110682]
## Use case

I want to open browser when my app is running in background.

**Comment by darshankawar** [comment]
@bhagat-techind 
Your issue / use case is not exactly clear as what are you trying to achieve. I suggest you to ask this question on support channels like StackOverflow. See a similar issue and check if it helps your case: https://stackoverflow.com/questions/64140400/open-a-website-in-the-background-and-access-its-fields-in-a-flutter-app

Also, if you think there's a valid scope in the framework to add such use case, please open a new issue using correct issue template, provide requested details so that we can address it accordingly.

Closing for now.
