### ISSUE TITLE
Flutter Web 滚动性能优化

### ISSUE THREAD

**Issue by app111** [flutter/flutter#110643]
**Target Platform: WEB
**Target OS version/browser:** chrome
**Devices: PC

## Logs

长页面的滚动，浏览器里只要一条 CSS (overflow:scroll) 就可以让元素可滚动，手势的监听以及页面的滚动以及滚动动画都是浏览器原生实现的，不需要与 JS 交互，甚至不需要重新 layout 和 paint，只需要 compositing。在 Flutter 中 Animation 和 Gesture 是用 Dart 实现的，编译过来就是 JS 实现的，浏览器本身并不知道这个元素是否可滚，只是不断派发 touchmove 事件，JS 根据事件属性计算节点偏移，然后运算动画，然后把 transform 或者新的 position 作用到节点上，然后浏览器再来一遍完整的渲染流程……

![image](https://user-images.githubusercontent.com/1449284/187588609-60e27d2b-7a41-46ef-9863-a795ccd5d40f.png)

**Comment by huycozy** [comment]
Hi @app111 
Please provide the information indicated below so that we can verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
