### ISSUE TITLE
How to satisfy "Do not use BuildContexts across async gaps" in a stateless widget with an async callback?

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#110694]
After upgrading flutter I have a bunch of warnings about "Do not use BuildContext across async gaps". While I understand the issue, I'm not seeing an obvious way around in when you have a button in a stateless widget, which shows other UI, waits for the result, and then does something. In a stateless widget we do not have access to `mounted` so the suggestion [in the linter docs](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html) does not work.

Take this for example:
- a back button is stateless
- it shows a dialog "Are you sure" to the user upon pressing
- If they press yes, returns true
- If the cancel or press no, returns false
- Upon pressing yes, we should `pop` and go back

What is the best way to do this right now in a **stateless** widget while satisfying the linting rule?

```
      onTap: () async {
        final userHasConfirmed = await showConfirmationDialog(context));

        if (userHasConfirmed) {
          // linter does not like this
          Navigator.of(context).pop();
        }
      },
```

**Comment by monster555** [comment]
try 
```
  onTap: () async {
    final navigator = Navigator.of(context); // <- Add this
    final userHasConfirmed = await showConfirmationDialog(context));

    if (userHasConfirmed) {
      // linter shouldn't complain now ;)
      navigator.pop(); // Replace Navigator.of(context) with navigator
    }
  },
```

**Comment by MilesAdamson** [comment]
> try
> 
> ```
>   onTap: () async {
>     final navigator = Navigator.of(context); // <- Add this
>     final userHasConfirmed = await showConfirmationDialog(context));
> 
>     if (userHasConfirmed) {
>       // linter shouldn't complain now ;)
>       navigator.pop(); // Replace Navigator.of(context) with navigator
>     }
>   },
> ```

Does this actually change anything about how the `BuildContext` is actually used? This seems like it only tricks the linter

**Comment by monster555** [comment]
Change the `StatelessWidget` to a `StatefulWidget` and check the `mounted` variable before popping. There's no way to check this in a `StatelessWidget`

**Comment by darshankawar** [comment]
@MilesAdamson 
As mentioned above, we cannot check this for a stateless widget, as there's no state / lifecycle for it. You may want to check where in your app / code this is occuring and change it to stateful widget.
You can also checkout [this](https://stackoverflow.com/a/69512692) SO answer for your reference and see if it serves your purpose.

**Comment by MilesAdamson** [comment]
> @MilesAdamson As mentioned above, we cannot check this for a stateless widget, as there's no state / lifecycle for it. You may want to check where in your app / code this is occuring and change it to stateful widget. You can also checkout [this](https://stackoverflow.com/a/69512692) SO answer for your reference and see if it serves your purpose.

Would you consider the approach in the stack overflow, which seems to be the same as what @monster555 suggested, to be a workaround or an actual fix to the problem?

**Comment by darshankawar** [comment]
@MilesAdamson 
It is not an actual fix because but a current solution based on the fact that how stateless widget works and the way it is designed and implemented. If the solution works and is acceptable in your case, you may close this issue or we can take it forward for further insights from the team.

**Comment by MilesAdamson** [comment]
That was a very vague answer. Do you consider what the stack overflow provided to be a best practice? If not, what is the best practice then for showing a dialog, awaiting a result, then navigating based on that?

Or, should this only be done in a stateful widgets, checking if they are still mounted?

**Comment by darshankawar** [comment]
> should this only be done in a stateful widgets, checking if they are still mounted?

Yes, and as also mentioned previously, that this isn't possible with stateless widgets as they have no state and way to check if they are still mounted.

**Comment by MilesAdamson** [comment]
Ok. I will close this if you can show me where this is documented. I have looked in quite a few places as to what to do, since the first place I've heard of this is when the linting rule was added.

The pop method of the navigator just says "dialog returns true"
https://api.flutter.dev/flutter/widgets/Navigator/pop.html
![image](https://user-images.githubusercontent.com/29047682/188192396-7a6bea99-cf63-4067-badc-6a3933dabd0d.png)

Show dialog says "Returns a Future that resolves to the value (if any) that was passed to Navigator.pop when the dialog was closed."
https://api.flutter.dev/flutter/material/showDialog.html

The flutter widget of the week does now show a complete example with `await`
https://www.youtube.com/watch?v=75CsnyRXf5I

**Comment by ricnaaru** [comment]
I guess, for now the best practice is to save the `Navigator.of(context)` before the async process and use it later after the async process is done.

From one perspective that would be acceptable because the reason is Navigator will always be there even though the context is not, because Navigator is included in MaterialApp (and usually this is the top most widget). On the other hand, there's still a small chance that Navigator can be re-created by popping all the screens. However the chance of re-creation is higher for other State or similar method like OverlayState, Localization, or maybe Provider.

I guess for now I can settle with this solution.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for further insights from the team.

**Comment by w1th0utnam3** [comment]
I guess in case of the navigator storing it before the async gap is at least a half-decent solution (although as @ricnaaru mentioned, in some cases it might still get invalid?), but what about other functions that require a `BuildContext` like the `showDialog` functions? Is there a similar workaround for them?

Maybe I should design this completely differently but my use case is the following:
1. There are several buttons or similar widgets that initiate some async action e.g. loading/parsing a file from storage or from the internet.
2. After this async action is done a dialog should open either to show some information on the loaded content or to set some options related to parsing the file.
3. Depending on the return value of the dialog the UI should update.

Of course one way to do this (as recommended on StackOverflow) would be e.g. in the `onPressed` callback of the button to first await the action from step 1, then check `mounted` of the enclosing `StatefulWidget` and then show the dialog from step 2 using the corresponding context. But if I have several widgets that initiate such an action I would usually be tempted to avoid code duplication and extract step 1 and 2 together into a function like `loadFileInteractive(context, file_path)` which both runs the action and then shows a dialog). But this doesn't work in general because I can only check `mounted` inside of a specific `StatefulWidget`. So in the end I have to repeat the steps "do step 1, check mounted, do step 2" (which is probably at least 4 or 5 lines of code) in every stateful widget that wants to do this.

As I said, maybe it's possible do set up this architecture completely differently without this issue. But then it would be nice to have an official guide on how to combine async actions with UIs in a use case that is a bit more complex then the typical documentation example that just shows `onPressed: showDialog(...)`. All I can find related to best practices with async in Flutter is the "checking `mounted` approach" or using a `FutureBuilder` but I think the latter is not really helpful for the problems described in this issue thread.

**Comment by ricnaaru** [comment]
@w1th0utnam3 I usually do the code like you said, to merge the 1st and 2nd step into one method.

I kind of understand what is Flutter's intention by adding this BuildContext synchronous usage linter, because they want to separate the interest of UI and the interest of the logic. Calling API, getting data from the cloud, etc, is one interest, and it doesn't necessarily need to know anything about the UI, and displaying its result is another interest. So every logic must have a UI handler (in this case to check if the BuildContext is mounted).

From my perspective this is kind of good addition, because with this, we can be disciplined enough to separate those two different interests, and properly handle the UI in case there are some errors, and of course for each screen, the error might want to be handled differently.

True, this addition causes the code has to repeat the mounted probably multiple times, but I guess, simple is not always effective.

**Comment by goderbauer** [comment]
See also: https://github.com/flutter/flutter/issues/111488

**Comment by HenryNguyen1905** [comment]
`  Future resetPassword() async {
    try {
      await FirebaseAuth.instance
          .sendPasswordResetEmail(email: _emailController.text.trim());
      showSnackBar(context, 'Reset email link sent');
    } on FirebaseAuthException catch (e) {
      print(e);
      showSnackBar(context, e.message.toString());
    }
  }`

**Comment by HenryNguyen1905** [comment]
I think I might have the same issue with you all, guys.
Could you pls help me with how I can fix that in my circumstance?
`Future resetPassword() async {
    try {
      await FirebaseAuth.instance
          .sendPasswordResetEmail(email: _emailController.text.trim());
      showSnackBar(context, 'Reset email link sent');
    } on FirebaseAuthException catch (e) {
      print(e);
      showSnackBar(context, e.message.toString());
    }
  }`

**Comment by ricnaaru** [comment]
@HenryNguyen1905 you have two choices..
1. use StatefulWidget to check if it's mounted after async operation
2. put `ScaffoldMessenger.of(context)` before the async operation, and use if after async

**Comment by goderbauer** [comment]
On master (and with the next release on stable as well) you can also check `context.mounted`: https://github.com/flutter/flutter/pull/111619.

I am going to close this as this is fixed with https://github.com/flutter/flutter/pull/111619.
