### ISSUE TITLE
The following assertion was thrown while handling a gesture: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4020 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by Ankush15Lakhan** [flutter/flutter#110770]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4020:12)
#3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:4098:20)
#4      CategoriesCarouselItemWidget.build.<anonymous closure> (package:speedy/src/elements/CategoriesCarouselItemWidget.dart:41:33)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)

I am getting this Error  because Code is old

**Comment by darshankawar** [comment]
> I am getting this Error because Code is old

@Ankush15Lakhan This is the indication. I am not sure what version are you on, but the framework has gone through lot of updates and latest version is 3.3.0. So you are bound to see some issues if you are running old / legacy code on new version or still on old version.

Also, there's not enough details you provided to make this issue actionable. Just providing error log won't help much as we also need `flutter doctor -v`, a minimal code sample that throws this error, so when you open an issue, please try to use new issue template and fill out requested details.

Closing for now due to lack of details.
