### ISSUE TITLE
web fullscreen events cannot be monitored

### ISSUE THREAD

**Issue by longgong** [flutter/flutter#110751]
Can't receive events when I press F11 to enter or exit full screen。

```
html.window.addEventListener('fullscreenchange', (event) {
        logger.i('message');
});
```

**Comment by darshankawar** [comment]
@longgong 
When you open a new issue, please use new issue template and try to provide some or all requested details so that we will have enough info to work with.

For now, can you provide `flutter doctor -v`, a complete minimal reproducible code sample along with actual vs expected behavior you are looking for along with platform on which you are seeing this behavior ?

**Comment by longgong** [comment]
Flutter version 2.10.5 at D:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

**Comment by longgong** [comment]
> 

 Flutter version 2.10.5 at D:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

**Comment by darshankawar** [comment]
@longgong 
You are on old version of stable. Please upgrade to latest and try again. Also provide below details as requested earlier:



> a complete minimal reproducible code sample along with actual vs expected behavior you are looking for along with platform on which you are seeing this behavior ?
