### ISSUE TITLE
flutter/packages tree is broken

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#110810]
This commit broke the flutter/packages tree: https://github.com/flutter/packages/commit/fa9b71a3da60129237f257c61a147f7c538ad2d9

@stuartmorgan was saying its some infra issue.

/cc @godofredoc

**Comment by godofredoc** [comment]
\cc @keyonghan 

I'm assuming this was from yesterday. The problem is that packages + plugins used the max amount of allocated cirrus credits for the month.

**Comment by goderbauer** [comment]
I tried to rerun the checks this morning, but they were still failing.

**Comment by jmagman** [comment]
It looks like a status update issue? That PR passed in post submit:
https://cirrus-ci.com/build/5031166657953792
And there are no failures on main:
https://cirrus-ci.com/github/flutter/packages/master

**Comment by godofredoc** [comment]
For some reason we are trying to run them again and hitting the quota: https://cirrus-ci.com/task/5655462837223424

**Comment by keyonghan** [comment]
Filed a cirrus bug: https://github.com/cirruslabs/cirrus-ci-docs/issues/1067

**Comment by fkorotkov** [comment]
Please use [email support](https://cirrus-ci.org/support/) and don't ping me directly for issues likes this. We agreed on this process with @godofredoc and @stuartmorgan.

As for the issue it seems you have a commit with the same SHA to `main` later after the roll: here is the [roll](https://cirrus-ci.com/build/5031166657953792) as you mentioned and here is [another one](https://cirrus-ci.com/build/6311195392081920) a bit later. I found the second build when I clicked on the [check suite for the SHA](https://github.com/flutter/packages/runs/8141284340).

Have you force pushed or modified history?

**Comment by fkorotkov** [comment]
I diged a little more. It seems this PR is the reason for the bad status: https://github.com/flutter/packages/pull/2543

But mainly the reason of the issue is how GitHub is designed:

1. Apparently anyone with read access can create a PR between two branches in the repository. Like in the example above to merge changes from `main` into `go_router_v5`. I'd expect a user with read access could've only create a PR from their fork.
2. GitHub doesn't distinguish between branches. All the status reports are reported by SHAs and combined together for different branches. So from the example above there was a [PR build](https://cirrus-ci.com/build/6311195392081920).

I guess we can prevent weird behaviour like `1` from Cirrus side and just skip such builds.

**Comment by Hixie** [comment]
(Reducing priority since the tree is not red anymore.)

**Comment by ditman** [comment]
> Please use [email support](https://cirrus-ci.org/support/) and don't ping me directly for issues likes this.

Apologies for this, @fkorotkov, I guess old habits die hard. It makes complete sense that this support method is not acceptable (nor scalable for you). I'll ping @stuartmorgan and @godofredoc so they can re-announce that we should be using mail support moving forward.

> I diged a little more.

Thanks for your write-up, Fedor, your explanation makes complete sense: the bad build got triggered because "flutter/packages/main" was being used as the branch for a PR against "flutter/packages/router_blah". That bad build **updated the status of the correct build in main, and turned the tree red** (and explains the error where router_blah is not a "valid branch" that we were seeing in some of [our other checks](https://github.com/flutter/packages/runs/8141283527)).

> Have you force pushed or modified history?

This is not necessary to cause confusion in the Github reports. In the past [we've seen very confusing behavior](https://github.com/flutter/flutter/issues/102801) with multiple rebuilds that never require any force-pushing from a user, for example:

* keeping `master` / `main` branches in sync with an app that would duplicate even the commit hashes across both branches.
* our release process applying a tag after a successful "release" action would update the status of the tagged hash.

Since Github only knows about hashes, Cirrus would send new updates to tasks that were identically named, and GH would update the (formerly passing) checks with the new results (in some cases, they would be failures!).

The only way of catching this on the spot was to see it happen "live" and grab the new links, or to visit the cirrus [status page at the repo level "soon enough"](https://cirrus-ci.com/github/flutter/packages) (it "only" shows the last 200 builds it seems?). In the case above, icons were slightly different, so it was easy to see once you knew what you were looking for, but in **this one is a little bit trickier**.

(This has gotten better with tweaks to our Cirrus config (and the "Debugging Information" button), but for a while it was confusing (like in this case))

> I guess we can prevent weird behaviour like 1 from Cirrus side and just skip such builds.

I think there's two issues that made it hard for me to tell apart what was going on:

1. It's hard to tell apart what triggered [this build](https://cirrus-ci.com/build/6311195392081920) vs [this other build](https://cirrus-ci.com/build/5031166657953792) at a glance, 
2. Even if we have had those links, it'd have been extra hard to notice that both of those builds are testing the same hash.

(Maybe cross-linking those pages the same way that retries of a task are all cross-linked would have helped? This is obviously your call how to "solve" this (if you deem that anything needs to be done, of course))

> I'd expect a user with read access could've only create a PR from their fork.

Indeed, anybody who's read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) Flutter doc, should be creating PRs from their fork. I'm not sure if we can lock this down more with Github/CI config, I'll take a look!

Let's close this, I think that with Fedor's investigation it's clear what happened to the tree. Some action items for us:

* Do not ping Fedor directly, and broadcast this to the team (again). Use email support instead.
* Attempt to lock-down our repos so people don't do funky stuff with `main` and they follow the tree hygiene page. (not sure how doable this can be, but worth taking a look).

Thanks again, Fedor for all your support!
