### ISSUE TITLE
autolabel was removed: "Base branch was modified. Review and try the merge again."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110889]
I applied the `autosubmit` label, but it was removed:

> auto label is removed for flutter/flutter, pr: 101586, Failed to merge pr#: 101586 with OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Base branch was modified. Review and try the merge again., locations: [ErrorLocation(line: 2, column: 3)], path: [mergePullRequest], extensions: null)]).

https://github.com/flutter/flutter/pull/101586#issuecomment-1235879099

It was just rebased onto master.

**Comment by jmagman** [comment]
cc @ricardoamador @keyonghan

**Comment by jmagman** [comment]
Added the label back, let's see if it gets removed again.

**Comment by stuartmorgan** [comment]
I have seen this rl in the last day or two in flutter/plugins when I put the autosubmit label on several PRs at the same time. One lands, then the others immediately fail with this message.

**Comment by keyonghan** [comment]
@ricardoamador Do you mind take a look? Seems the GitHub API is still validating if the PR is mergeable. A retry is recommended: https://github.com/orgs/community/discussions/24462.

**Comment by ricardoamador** [comment]
@keyonghan yes sir. I can take a look at this.

**Comment by ricardoamador** [comment]
We are hitting an internal github issue when attempting to merge the pull requests. 

I added a change recently to autosubmit so that we handle an error when instantiating our GraphQL client. Now that we handle the error we may have  surfaced this problem. I had added a catch on exception that was intended to fix a different error we were seeing with the label not being removed correctly.

Now we are processing a merge to quickly after a previous merge so we are hitting this error:
https://github.com/orgs/community/discussions/24462
