### ISSUE TITLE
[in_app_purchase] GooglePlayPurchaseParam missing in context 

### ISSUE THREAD

**Issue by DenisKen** [flutter/flutter#110832]
I'm working with `in-app-purchase` plugin and making `upgrading/downgrade` of subscriptions in Google.
According to documentation, I should use an `Instance of ChangeSubscriptionParam` and `GooglePlayPurchaseParam` object.

![image](https://user-images.githubusercontent.com/15076521/188048824-19d17592-cf87-4bb8-b5c5-9350a3091af1.png)

But, my editor missing this class
![image](https://user-images.githubusercontent.com/15076521/188048921-f45fa982-f0d3-4381-915d-b4e6ccc05524.png)

I didn't found this class in `in-app-purchase` plugin too.

What am I doing wrong?

**Comment by darshankawar** [comment]
@DenisKen 
I checked this in plugin's official example and do see both classes being working properly. Perhaps you need to completely type both classes in order to see them working.

<img width="458" alt="Screenshot 2022-09-02 at 5 59 02 PM" src="https://user-images.githubusercontent.com/67046386/188143197-d2f0a5f4-1723-4708-b6e2-47e0186e1855.png">
<img width="415" alt="Screenshot 2022-09-02 at 5 59 43 PM" src="https://user-images.githubusercontent.com/67046386/188143204-a1be70d7-900d-4ec2-a6f3-ce9f33fe81cb.png">

plugin version: ^3.0.7

In your case, type entire class name even though it shows in red and once you add required params, it should work.

Closing from here, as the classes are present and working as expected.
