### ISSUE TITLE
windows keyboard key error

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#110841]
```
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#fffae(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 96:17:08.952558)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
```

**Comment by darshankawar** [comment]
@abdulrehmananwar 
A similar issue related to `KeyRepeatEvent` was fixed as part of https://github.com/flutter/flutter/issues/108646, so if you are not on latest master, try to switch to it and see if you still get same error or not.

`flutter channel master`
`flutter upgrade`

**Comment by abdulrehmananwar** [comment]
i am using flutter stable channel. why its not working on flutter stable

**Comment by darshankawar** [comment]
@abdulrehmananwar 
The issue was found and fixed as part of https://github.com/flutter/flutter/issues/108646 which is available on master. Per Flutter's release policy, it will be made available in future stable versions. 
If you have already verified this on master and confirm it is working there, please update here or close. If not, then as suggested earlier, please verify there and confirm.
