### ISSUE TITLE
[in_app_purchase][android]: Add Google Play Offers support

### ISSUE THREAD

**Issue by AlaaEddineCharbib** [flutter/flutter#110909]
Google Play introduced offers to subscriptions. but apparently there is still no support to this feature in the in_app_purchase plugin, or at least this is what I could conclude after going through the GooglePlayProductDetails and SkuDetailsWrapper codes.

For iOS it is possible to get the list of a product discounts using the AppStoreProductDetails' skProduct object.
is it possible to have such a thing for Android too?

**Comment by GaryQian** [comment]
cc @GaryQian

**Comment by antonionicolau** [comment]
Hey @AlaaEddineCharbib It's nice that If your app supports the in-app purchase workflow(described in [Making In-app Billing requests](https://developer.android.com/google/play/billing/billing_integrate.html#billing-requests)), your app automatically supports in-app redemption of promo codes. You'll only need to implement it for IOS, not need for Android

**Comment by jiang1654** [comment]
I set up a free trial in Google Play, but no promotional information is displayed. Why? @antonionicolau

**Comment by erperejildo** [comment]
> Hey @AlaaEddineCharbib It's nice that If your app supports the in-app purchase workflow(described in [Making In-app Billing requests](https://developer.android.com/google/play/billing/billing_integrate.html#billing-requests)), your app automatically supports in-app redemption of promo codes. You'll only need to implement it for IOS, not need for Android

Automatically you mean? It doesn't work for me, only takes one of the plans created:

https://stackoverflow.com/questions/74599781/flutter-get-different-plans-from-subscription

**Comment by erperejildo** [comment]
@danagbemava-nc do we know when will this be supported? Or a roadmap to know exactly how long I can delay my new subscriptions for.

I can also create other subscriptions in my google play console in the meantime and later on, when this is supported create them as plans/offers but I will encounter 2 issues here:
- The original subscriptions can't be removed at all
- The IDs will be different and I will face some problems with users with the original subscriptions 
- If I have new plans/offers this will be confusing having other separate (and active) subscriptions
- Extra logic in my app

I understand we are talking about different departments here (google play console, Flutter, etc.) but this will affect our earnings and TBH all these departments belong to the same company (I'm saying this because I had these problems already in the past with this and other libraries). This issue was created 3 months ago, there are people interested but again, we have an issue without responses from the team. So some extra info will be appreciated please

**Comment by danagbemava-nc** [comment]
> do we know when will this be supported? Or a roadmap to know exactly how long I can delay my new subscriptions for.

@erperejildo, unfortunately, I cannot provide that information

**Comment by seunghwanly** [comment]
It has been almost 6 months trying to get the `Non-renewing Subscription` from Play Store using the `in_app_purchase` plugin.

App Store fetches all the 
1. Auto-renewable Subscriptions
2. Non-renewable Subscriptions
by using the `queryProductDetails( )` method.

But, the Play Store only retrieves `Auto-renewable Subscriptions` none of the `Non-renewable Subscriptions` can be fetched.

Are there any updates on this issue?

**Comment by erperejildo** [comment]
> > do we know when will this be supported? Or a roadmap to know exactly how long I can delay my new subscriptions for.
> 
> @erperejildo, unfortunately, I cannot provide that information

who should I get in contact with? Becase I was trying to create my new subscriptions but instead of creating 3 I'll have to create 6 with extra logic to detect plans within same subscriptions (because all of them will be separate and different subscriptions at the end).

I could wait to see if this is going to be supported but not much since I'm going to lose money. So any way to get more information about this support?

**Comment by papmodern** [comment]
Any update?

**Comment by KaleFoxit** [comment]
半年过去了，还没有支持计划吗?

**Comment by wosika** [comment]
It's been six months, no support plan?😥

**Comment by sandesh-dearreal** [comment]
When should be expect this to be added

**Comment by erperejildo** [comment]
> It's been six months, no support plan?😥



> When should be expect this to be added?

never wait for something like this guys. Specially if it affects your earnings
