### ISSUE TITLE
Autofill service as a (password manager/etc...)

### ISSUE THREAD

**Issue by rustzz** [flutter/flutter#111015]
How to implement an autofill service in an application?
I am rewriting a password manager from another developer to a new version of the SDK. But the libraries he used are not compatible with the new SDK/other libraries.

Does Flutter support the autofill service?
If not, implement or write documentation about integrating this service with Flutter. Because there is only the use of managers, not their implementation.
Please, please help me with this issue. Because there was no answer on Stackoverflow.

I do not edit android / ... files, because I'm just learning.

**Comment by huycozy** [comment]
Hi @rustzz 
Please see https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html for more information.
Also, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on [flutterhelp](https://www.reddit.com/r/flutterhelp/).

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you!
