### ISSUE TITLE
I can't load assets if the filename contains special characters

### ISSUE THREAD

**Issue by Merwan1010** [flutter/flutter#111020]
## Steps to Reproduce

1. Create a file on the assets folder with special characters in the file name (ex : `사진.png`)
2. ONLY import the assets folder in the `pubspec.yaml` file : 
```
  assets:
    - assets/ 
```
3. Try to load/display the file
`Image.asset('assets/사진.png')`

**Expected results:** 
I am expected to see the image being displayed.

**Actual results:** 

I am seeing an error message `"Unable to load asset: assets/사진.png"`

**However**, If I add the filename to the `pubspec.yaml` file like this : 
```
  assets:
    - assets/사진.png
```
The file load correctly. 

This issue only occur with files that contains special characters

<details>
  <summary>Logs</summary>

```
                    ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
                    The following assertion was thrown resolving an image codec:
                    Unable to load asset: assets/사진.png.
                    
                    When the exception was thrown, this was the stack:
                    #0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:272:7)
                    #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
                    #2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
                    #3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
                    #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
                    #5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
                    #6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
                    #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
                    #8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
                    <asynchronous suspension>
                    
                    Image provider: AssetImage(bundle: null, name: "assets/사진.png")
                    Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#b3355(), name: "assets/사진.png", scale:
                      1.0)
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.0.1 21A559 darwin-x64, locale en-JP)
    • Flutter version 3.3.0 on channel stable at /usr/local/Caskroom/flutter/2.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/merwanropers/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = /Users/merwanropers/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/merwanropers/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • 1D803E07-1BCD-43AC-B5A8-7FA1DC5B2477 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @Merwan1010, thanks for filing the issue. 
This issue is reproducible on the latest `stable` and `master` channels. Results vary between platforms.

- Android: ❌
- iOS: ❌
- macOS: ❌
- Web: 
    - Web on MacOS: ❌
    - Web on Windows: ✅
    - Web on Linux: ✅
- Linux: ✅
- Windows: ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo</summary>

**Web**

| Web on MacOS | Web on Windows | Web on Linux |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/188626791-5108c88c-e2e5-4151-8828-75331eb4f7af.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/188630924-aa2046e3-70e9-46cf-918e-0f31c3689091.PNG"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/188632178-a902e5bd-e64f-4213-b6c1-ec62eeb516e3.png">

**Desktop**

| MacOS | Windows | Linux (Ubuntu) |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/188627561-535e6c83-384a-4d33-9d1a-9e624bd071d5.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/188630907-3414af78-b336-4e0a-bf68-126ccd392be5.PNG"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/188632194-8341c531-e524-4d35-870f-3bc6fbe652b3.png">

**Mobile**
| Android | iOS |
| --------------- | --------------- |
<img width="300" src="https://user-images.githubusercontent.com/104349824/188627656-40dde4d8-997d-4b90-aa2f-5ce359d57adf.png"> | <img width="300" src="https://user-images.githubusercontent.com/104349824/188627784-71cccf91-17bd-4cf5-992a-f0cb5f487306.png">


</details>

<details>
<summary>Logs</summary>

```bash
Error while trying to load an asset: Failed to load asset at "assets/assets/%25EC%2582%25AC%25EC%25A7%2584.png" (404)
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/사진.png

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter/src/services/asset_bundle.dart 258:7                         load
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 640:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

Image provider: AssetImage(bundle: null, name: "assets/사진.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#b219b(), name: "assets/사진.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See:
https://flutter.dev/docs/cookbook/design/fonts
```
</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GestureDetector(
        onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times: ',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              Image.asset('assets/사진.png'),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.3.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (28 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.84, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.4.0-19.0.pre.84 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 224ec21c5d (3 hours ago), 2022-09-05 20:03:24 -0400
    • Engine revision d79d26f8dc
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by darshankawar** [comment]
@Merwan1010 
Can you try something like below using `ByteData` and load the asset using `rootBundle` and see if it works ?

`ByteData bytes = await rootBundle.load('assets/사진.png');`

**Comment by Merwan1010** [comment]
@huycozy Thank you for taking the time to check with so many configurations !

> @Merwan1010 Can you try something like below using `ByteData` and load the asset using `rootBundle` and see if it works ?
> 
> `ByteData bytes = await rootBundle.load('assets/사진.png');`

@darshankawar I tried it but I've the same error message.

**Comment by chinmaygarde** [comment]
Is this issue sensitive to the host platform in use?

**Comment by christopherfujino** [comment]
cc @andrewkolos

**Comment by jonahwilliams** [comment]
both @andrewkolos and I looked at this issue and were unable to reproduce it across a variety of host + target platform combinations.

@huycozy can you provide more information on the exact steps that reproduced it on android/ios/macos? including versions, host platforms, system locale, et cetera.

**Comment by andrewkolos** [comment]
Amongst other things, I tried to repro this with https://github.com/andrewkolos/flutter_issue_demos/tree/628a074cdf19efacd9b17570c6afb393e10ccd7f, but I didn't have any luck. Perhaps it may be worth cloning this and running it yourself to see if the issue still happens. If you do, just click the third third link that appears on the home screen.

**Comment by huycozy** [comment]
Hi @jonahwilliams, @andrewkolos 
>@huycozy can you provide more information on the exact steps that reproduced it on android/ios/macos? including versions, host platforms, system locale, et cetera.

### Steps to reproduce
Run sample code from: https://github.com/huycozy/test_assets_special_char_111020

### Platform information

#### Android
- Device 1: Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225
- Device 2: Pixel 3a, Android 12
- Host platforms: macOS 12.5.1 21G83 darwin-x64, locale en-VN 

<details>
<summary>Demo Android</summary>

| Galaxy Tab A7 | Pixel 3a |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/189797279-cc0afb98-9199-46b1-a634-52258c5abc63.jpg"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/189797288-7fa5ddae-ff26-4fba-9baf-ec7690abd51f.png">

</details>

#### iOS
- Device: iPhone 7, iOS 15.5
- Host platforms: macOS 12.5.1 21G83 darwin-x64, locale en-VN 

<details>
<summary>Demo iOS</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/189797512-b4237cdb-159b-459f-9508-68404aff8cd6.png">

</details>

#### macOS
- Device: MacBook Pro (13-inch, 2020)
- Host platforms: macOS 12.5.1 21G83 darwin-x64, locale en-VN 

<details>
<summary>Demo MacOS</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/189797732-50470d40-45b4-4f28-96b5-24660598ff01.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

-----
>Perhaps it may be worth cloning this and running it yourself to see if the issue still happens. If you do, just click the third third link that appears on the home screen.

The weird thing is that it works properly with [Andrew's sample code](https://github.com/andrewkolos/flutter_issue_demos/tree/628a074cdf19efacd9b17570c6afb393e10ccd7f):

<details>
<summary>Demo</summary>

| Android (Pixel 3a) | iOS (iPhone 7)| MacOS (MacBook Pro 2020) |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/189798436-827cab49-9a09-41ed-a10c-4dab23f5ba3a.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/189798581-1404bc30-d2c0-44c0-afeb-740788b8bb90.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/189798621-6d84b2d2-55e8-4e1c-9cd4-42e91ad5a038.png">

</details>

@andrewkolos Could you please try running my sample code to see if the issue is reproducible? https://github.com/huycozy/test_assets_special_char_111020

**Comment by andrewkolos** [comment]
> @andrewkolos Could you please try running my sample code to see if the issue is reproducible? https://github.com/huycozy/test_assets_special_char_111020

Sure thing! I was still unable to reproduce with host MacOS 12.5.1 targeting 1) macos, 2) chrome or 3) a virtual Pixel 6 running Android 33.

<details>
     <summary>Demo (chrome)</summary>

<img width="500" alt="image" src="https://user-images.githubusercontent.com/9027551/189826676-d63f2723-57a9-44a7-b9f5-474c0cebf425.png">

</details>

<details>
     <summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83
    darwin-arm, locale en)
    • Flutter version 3.3.1 on channel stable at
      /Users/andrewkolos/Documents/GitHub/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (6 days ago), 2022-09-06
      17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android
    SDK version 33.0.0)
    • Android SDK at /Users/andrewkolos/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 •
      android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         •
      darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                • chrome        •
      web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

I can only make an uninformed guess--have you tried testing this with a fresh clone of your project?

**Comment by huycozy** [comment]
Hi @andrewkolos 
>I can only make an uninformed guess--have you tried testing this with a fresh clone of your project?

I've just tried cloning my project and running it, it works properly.

<details>
<summary>Demo (Chrome)</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/189856759-06cae018-6630-4b22-a875-90c20e179efe.png">

</details>

I just found a way that maybe you'll be on your side:
1. Clone sample code: https://github.com/huycozy/test_assets_special_char_111020 and download  
[image.zip](https://github.com/flutter/flutter/files/9555404/image.zip) to your machine.
2. Unzip `image.zip` to get new image (actually you can use any images that you have (just rename it so that it contains `사진` in the file name)
3. Replace the new `사진.png` that you downloaded with `test_assets_special_char_111020/assets/사진.png`
4. Run the project to see if the issue is reproducible

**Comment by huycozy** [comment]
Hi @andrewkolos 
>I can only make an uninformed guess--have you tried testing this with a fresh clone of your project?

I've just tried cloning my project and running it, it works properly.

<details>
<summary>Demo (Chrome)</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/189856759-06cae018-6630-4b22-a875-90c20e179efe.png">

</details>


-------
But I just found a way that maybe you can reproduce the issue on your side:
1. Clone sample code: https://github.com/huycozy/test_assets_special_char_111020 and download  
[image.zip](https://github.com/flutter/flutter/files/9555404/image.zip) to your machine.
2. Unzip `image.zip` to get new image (actually you can use any images that you have (just rename it so that it contains `사진` in the file name)
3. Replace the new `사진.png` that you downloaded with `test_assets_special_char_111020/assets/사진.png`
4. Run the project to see if the issue is reproducible

**Comment by andrewkolos** [comment]
I still could not reproduce with these instructions,
<details>
     <summary>demo (chrome)</summary>

![image](https://user-images.githubusercontent.com/9027551/189976318-3578d25c-7de3-477f-8760-29b220e2648e.png)

</details>



However, I was able to get something through simply adding the horse image (the one from image.zip) as `사진_horse.png`,
<details>
     <summary>demo (chrome)</summary>
     
     
![image](https://user-images.githubusercontent.com/9027551/189976747-7b387137-c16a-49c9-a3b6-c94e243804a5.png)

</details>

I don't think anything is inherently problematic with the image, because I can get it to display by deleting the original `사진.png` and renaming `사진_horse.png` to `사진.png`,

<details>
     <summary>demo (chrome)</summary>
     
   
![image](https://user-images.githubusercontent.com/9027551/189977352-7c0673a1-42ac-47fb-b851-04c437798547.png)

</details>

**Comment by jason-simmons** [comment]
The file in image.zip is failing to load because its filename is not identical to the asset name in the source.

The two filenames look equivalent, but the original filename 
contains a composed form and the image.zip filename contains a decomposed form of the Korean characters.

Original:
```
['HANGUL SYLLABLE SA', 'HANGUL SYLLABLE JIN']
```

image.zip:
```
['HANGUL CHOSEONG SIOS', 'HANGUL JUNGSEONG A', 'HANGUL CHOSEONG CIEUC', 'HANGUL JUNGSEONG I', 'HANGUL JONGSEONG NIEUN']
```

Unicode defines a way to normalize a string into a composed or decomposed form.  The Flutter tools could conceivably apply normalization to asset names before packaging them into the app.

However, AFAIK the Dart SDK does not provide an API for Unicode normalization (see https://github.com/dart-lang/sdk/issues/26502).
