### ISSUE TITLE
What is the difference between Touchpad event and Mouse event on MacOS?

### ISSUE THREAD

**Issue by daydreary** [flutter/flutter#111013]
onPointerSignal: (event) {
    event.kind  // On MacOs, mouse and touchpad events have same kind (PointerDeviceKind.mouse)
} 

Is this an issue or a feature? 
Is there any way to distinguish the mouse event and the touchpad event?

<details>
  <summary>Flutter doctor</summary>
  [✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.5 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
</details>

**Comment by huycozy** [comment]
Hi @daydreary 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide the output of `flutter doctor -v` as well.

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
Thank you!
