### ISSUE TITLE
Mac iOS Engine build failing in objc docs on ruby error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111193]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/17997/overview

**Comment by zanderso** [comment]
cc @nehalvpatel

**Comment by jmagman** [comment]
Failing loading `sqlite3`
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803613787121243457/+/u/build_obj-c_doc/stdout

The arm64 version of sqlite3 is incorrectly being installed on an [x64 machine](https://chromium-swarm.appspot.com/bot?id=build814-m9):
```
Successfully installed sqlite3-1.5.0-arm64-darwin
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803613787121243457/+/u/install_jazzy/stdout

**Comment by GaryQian** [comment]
@godofredoc @CaseyHillers

**Comment by nehalvpatel** [comment]
## Context:
The flutter/engine tree is closed and blocked by the `Mac iOS Engine` test.

## Update:
Solutions are being discussed as the test also failed after the revert.

**Comment by jmagman** [comment]
A successful run before this started shows:
```
Successfully installed sqlite3-1.4.4
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803627640858878753/+/u/install_jazzy/stdout

sqlite3 1.5 was released today: https://rubygems.org/gems/sqlite3/versions/1.5.0

**Comment by nehalvpatel** [comment]
Yeah, it looks like `sqlite3-ruby` has new usage guidelines post-`1.5.0`:
* [1.5.0 release notes](https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v1.5.0)
* [Installation: Native Gems (recommended)](https://github.com/sparklemotion/sqlite3-ruby#native-gems-recommended)

**Comment by nehalvpatel** [comment]
A potential fix that temporarily disables Obj-C doc generation is being tested right now.

**Comment by nehalvpatel** [comment]
Instead of the temporary fix, a permanent one that retains Obj-C doc generation is being tested right now.

**Comment by keyonghan** [comment]
Fix recipes https://flutter-review.googlesource.com/c/recipes/+/33681 just landed and got propagated. All failed PRs/Builds are ready for a retry to pass.

**Comment by nehalvpatel** [comment]
There's a slight bug in the fix from above, so we're moving forward with temporarily disabling Obj-C doc gen. It's in testing now.

https://flutter-review.googlesource.com/c/recipes/+/33662

**Comment by nehalvpatel** [comment]
Success! The test is working again and the tree is open now.

**Comment by zanderso** [comment]
We should leave this open until the doc generation is re-enabled. Feel free to close again if it is already re-enabled.

**Comment by nehalvpatel** [comment]
👍 Sounds good.

Working on landing a fix for that:
- #111209
- https://flutter-review.googlesource.com/c/recipes/+/33663

**Comment by zanderso** [comment]
The Engine -> Framework roll is failing because the objc docs are not found: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20docs_test/16877/overview

**Comment by nehalvpatel** [comment]
Docs are re-enabled, but the fix required pre-installing the `sqlite3-ruby` gem, which is one of `jazzy`'s dependencies.

---

## The Problem
[`jazzy`'s Gemfile.lock](https://github.com/realm/jazzy/blob/fadab05d8ec5a0f2e3253366bfb327bf620b7551/Gemfile.lock#L215) specifies `ruby` under its PLATFORMS key. This is not a recent change, and it only became a blocker when the [`sqlite3-ruby` gem released version 1.5.0](https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v1.5.0) two days ago.

When you try to install version 1.5.0 with the `--platform=ruby` argument, the gem CLI now tries to build the `sqlite3` database binary from source. This behavior also happens if `sqlite3-ruby` is a transitive dependency of a gem that specifies `ruby` under its PLATFORMS key in Gemfile.lock. In our case, `jazzy` is such a dependency.

`sqlite3-ruby`'s extconf.rb, which is responsible for building the database binary, [expects and requires the presence of `pkg-config`](https://github.com/sparklemotion/sqlite3-ruby/blob/10f430888348f412992808d1c390936b396c010c/ext/sqlite3/extconf.rb#L70) in the PATH.

Our CI servers don't have `pkg-config` installed by default, so `jazzy` installs started failing, which led to this whole test failing.

## Solutions (for this)

### Install the `sqlite3-ruby` gem without the `--platform=ruby` flag prior to installing `jazzy`
- The version for `sqlite3-ruby` does not actually have to be pinned. Installing `1.5.0` without the flag works fine.
- Runs the risk of our `sqlite3-ruby` version not being in sync with `jazzy`'s version requirements in the future.

### Download `pkg-config` source and build it prior to installing `jazzy`
- I've tried this and it works. After building, the resulting `pkg-config` binary just needs to be in the PATH.
- https://gist.github.com/jl/9e5ebbc9ccf44f3c804e
- https://opensource.ncsa.illinois.edu/confluence/display/DESDM/Installing+pkg-config+from+source+for+OSX

### Pre-build `pkg-config` binary and load it using CIPD
- Reduces risk of supply chain vulnerability.

### Install `pkg-config` using Homebrew
- I'm not sure about the policies for this.

## Solutions (long term)
- Consolidate doc generation tools

**Comment by nehalvpatel** [comment]
The team is looking into the long term solution of switching to a different tool for generating Obj-C docs. Specifically, a tool that is either already being used by the project or one that could be adopted for the majority of the project's doc generation needs.

**Comment by nehalvpatel** [comment]
As a stopgap, I've tried to update the version pin from `1.4.4` to `~> 1.3` like it is in jazzy's Gemfile.lock.

Unfortunately, it looks like the `sqlite3-ruby` gem grabs the arm64 binary for sqlite3 even if the bot running the test is x86 based.

**Comment by keyonghan** [comment]
With https://flutter-review.googlesource.com/c/recipes/+/34040, is this bug okay to close?

**Comment by nehalvpatel** [comment]
Yup, that solution has been working well.
