### ISSUE TITLE
Skip platform-specific tests for federated plugins for different platforms when testing PRs in presubmit

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111211]
For example, https://github.com/flutter/plugins/pull/6369 only made changes to federated the iOS `quick_actions_ios` plugin, but ran the `android-platform_tests` and `web-platform_tests`.

Instead, only run the platform_tests relevant for the federated plugin.

**Comment by jmagman** [comment]
The relevant platforms can't be derived from the name, for example `camera_avfoundation`.  It be easiest to maintain a hardcoded mapping from paths to platforms instead of doing tricky pubspec endorsement parsing.

**Comment by stuartmorgan** [comment]
> but ran the `android-platform_tests` and `web-platform_tests`.

It ran them in that the Cirrus task ran, but the expensive test work was all skipped (you can see that actual test steps took a few seconds total) because:
- presubmit only runs for changed packages, and only `quick_actions_ios` changed, and
- `quick_actions_ios` is skipped on platforms not supported by that plugin.

So we could make this slightly faster, but only by adding complex .cirrus.yaml logic, which I'm not convinced is worth the maintenance.

> instead of doing tricky pubspec endorsement parsing.

We already do the pubspec parsing; it's not all that tricky :) (We don't use endorsement, just the support platforms in the `plugin` section.)

**Comment by jmagman** [comment]
@stuartmorgan if you don't think this will buy us much I'll close this.
