### ISSUE TITLE
i got this error in debugging and my app didn't work.

### ISSUE THREAD

**Issue by iiamElina** [flutter/flutter#111365]
![Screenshot 2022-09-11 160552](https://user-images.githubusercontent.com/113236571/189525360-5e6a817b-573e-4a51-bd9f-339e612e0172.png)

**Comment by sandy088** [comment]
I also got this error while learning the flutter, And after that I  researched a lot and found this solution for this problem https://stackoverflow.com/questions/66004956/setstate-or-markneedsbuild-called-during-build-this-overlay-widget-cannot-b    I think this is the right solution for this problem because this works for me perfectly
