### ISSUE TITLE
Playback error when playing video from android internal storage using contentUri or file but from network video is playing. 

### ISSUE THREAD

**Issue by suyxx** [flutter/flutter#111389]
```
Init 1c0835d [ExoPlayerLib/2.18.0] [generic_x86, Android SDK built for x86, unknown, 30]
E/ExoPlayerImplInternal( 5579): Playback error
E/ExoPlayerImplInternal( 5579):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
E/ExoPlayerImplInternal( 5579):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5579):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 5579):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5579):   Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:121)
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal( 5579):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 5579):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5579):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5579):       at java.lang.Thread.run(Thread.java:923)
E/flutter ( 5579): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter ( 5579): 
I/ExoPlayerImpl( 5579): Release 337aeb1 [ExoPlayerLib/2.18.0] [generic_x86, Android SDK built for x86, unknown, 30] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
```

**Comment by darshankawar** [comment]
@suyxx 
When you open an issue, please try to use new issue template and provide requested details so that we will have enough info to work with. Just posting error won't help to debug much.

The main error seems to be:

`Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)`

For which you can search on stackoverflow and see if you get any leads.  One link is: https://stackoverflow.com/questions/68608353/platformexceptionvideoerror-video-player-had-error-com-google-android-exoplaye See if it helps.

If not, please provide details as mentioned in the template. Closing for now due to lack of details.

**Comment by suyxx** [comment]
@darshankawar  Many people posted same question on stackoverflow but there is not any proper answer.  Instead of figuring out the solution you got into proper format thing. ContentUri means from internal storage link video is not playing. Many other people posted the same thing on stackoverflow but non of them got the reply

**Comment by suyxx** [comment]
"new issue template"  where can I find this template I do not see on github can you share link?

**Comment by darshankawar** [comment]
@suyxx 
We didn't mean to not provide a solution, but in order to do so, we need proper details to analyze the issue better and hence mentioned the same earlier.
Here's the link you can use https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title= and provide requested details so that we can address it properly.
