### ISSUE TITLE
Certain canvas operations should allow physical pixel alignment

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111302]
(With some recently learnings from the breakage I caused in https://github.com/flutter/flutter/issues/111145)

Certain operations on the canvas can look much better if they are aligned to physical pixels, for example drawing an image could be pixel aligned. This is especially noticeable on low DPR devices, though it can be noticed on higher DPR devices with a careful eye.

Flutter uses logical pixels for all drawing operations. Logical pixels convert to physical pixels at a ratio specified by the specific device the Flutter application is running on. For example, my home desktop monitor has a configured DPR of 1.25, meaning for every 4 logical pixels, there are 5 physical pixels. Many mobile devices have device pixel ratios greater than 2.

In framework code, it is possible to convert logical pixels to physical pixels and vice-versa using the windows [devicePixelRatio](https://api.flutter.dev/flutter/dart-ui/FlutterView/devicePixelRatio.html). Additionally, due to the current unconditional presence of the raster cache pixel snapping, we can assume that every picture has an origin which is always aligned to a physical pixel. That is, 0,0 in each picture is guaranteed to fall on a pixel boundary. It seems like it may be possible for user code to manually pixel align, but there are some problems today:

###  Logical to Physical Conversion

All canvas APIs accept logical pixels (except those that refer to samples/dimensions from an Image). In order to align an operation, you would need to convert the requested logical pixels to physical pixels, round, and then convert back to logical pixels:

```dart
var dxx = (dx * devicePixelRatio).round() / devicePixelRatio;
var dxy = (dy * devicePixelRatio).round() / devicePixelRatio
```

However, the rounded out physical pixel does not necessarily correspond to an exact logical pixel. This may leave the ultimately chosen destination at the mercy of floating point math. Consider, we want to draw an image at the logical pixels `(23, 42.5)` with a device pixel ratio of `1.25`.  We convert this to the physical pixels `(28.75, 53.1250)`. This can be rounded to `(29, 53)` which we then convert back to logical pixels of `(23.2, 42.4)`. Everything is good!

But what happens if we have a DPR like `3.33`? For the same X coordinate, we convert, round , and convert back ending up with `23.1231231231`. Hopefully that rounds to a physical pixel, but it might not.

###  Knowledge of Accumulated Transformations

The above conversions only work if the only transform above the current picture is the DPR transform. It is possible for a given widget or render object to compute a "localToGlobal" or "globalToLocal" transform, but there is no guarantee the render object will repaint if this changes. Consider the following widget tree:

```dart
Transform.scale(x, child: RepaintBoundary(child: Widget()))
```

The first time that `Widget` paints, it can compute the total transform and incorporate that to ensure it is still pixel aligned. However if the scaling value changes, then because of the RepaintBounary wrapping Widget, it will *not* be repainted. Thus the pixel alignment will fail.

For other sorts of transformations, animations are common, and pixel alignment may not be important. For example, if you are apply a perspective transform or doing a rotation, then there may be no benefits in pixel alignment.

### Other workarounds

The only 100% guaranteed way to pixel align the origin of a drawing operation is to place it in its own Picture using a RepaintBoundary. However, adding repaint boundaries can also regress performance by adding more layer management.

###  Ideas

Could we delegate pixel alignment to the engine? For example, in the same way we round out the bounds and origin for raster caching. The canvas/display list code could also encode some intent that some operation should be pixel aligned, and use its knowledge of the CTM to compute that exactly. Would this have an impact on raster caching?

**Comment by jonahwilliams** [comment]
FYI @dnfield @goderbauer @Hixie

**Comment by goderbauer** [comment]
There is some discussion related to this in https://github.com/flutter/flutter/issues/59798.

**Comment by jonahwilliams** [comment]
yes definitely related. drawImage might be a case where alignment makes sense to do at the level of an individual draw operation, but pixel aware layout might be required to handle path drawing.

That is similarly not possible today for the same reasons listed here

**Comment by jonahwilliams** [comment]
I think the difference between this issue and those linked issues is that there is almost no reason I can think of where you would want to draw an image at a non-integral location. Paths and things have more caveats

**Comment by dnfield** [comment]
Someone had a patch at some point to try to force images to always render on physical pixel boundaries... it was a non-Google contributor, can't remember who.

**Comment by dnfield** [comment]
(The patch was rejected because it probably didn't do the right thing in a lot of cases and only would have covered some specific code path IIRC)

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/67041

**Comment by jonahwilliams** [comment]
Yeah that won't do the right thing since it isn't aware of the ctm

**Comment by Hixie** [comment]
In general this kind of thing scares me.

It's really easy for this kind of thing to result in hard-to-find bugs whose symptoms are things like vibrating text or twitching borders, or where an animation that does a rotation has a sharp quality drop when rotating past a right angle, or a zoom effect to have frames that seem to jiggle, etc. IMHO it's much better to dead-reckon the layout to end up at pixel boundaries "naturally".

I don't know if we still do it but we used to have some snapping around text. IMHO we should remove all snapping.

**Comment by jonahwilliams** [comment]
I just removed snapping from the engine and it has caused probably one of the worse visual regressions in recent memory 😆

**Comment by Hixie** [comment]
This is the kind of thing that would have been much easier if we'd done it right from the start, certainly. Happy to advise further if there's something concrete I can advise on. :-)

**Comment by dnfield** [comment]
The problem ends up being that we eventually do pixel snapping somewhere, and it gets really confusing when that happens unexpectedly.

If we _don't_ encode pixel snapping higher up in the stack, then we end up with people who write golden tests and assert on exact pixel values and thus encode into their tests that we do pixel snapping somewhere in the stack, they just don't know where (and get surprised when they add or drop it obliquely).

People end up wanting this for text and images specifically. Maybe rather than encoding this for particular DL ops, we'd have some kind of global flag that opts people into physical pixel boundaries for text and image related ops? Something like `Paint.enableDithering`?

**Comment by jonahwilliams** [comment]
There are certain operations where pixel snapping has impact on rendering quality on low DPR, like drawing an image. There are certain operations where you are anti-aliasing anyway, like drawing a diagonal line. Even if I wanted pixel alignment, I'm not sure that I would want them applied uniformly

**Comment by dnfield** [comment]
Right, I mean if that flag is set globally, then all image and text operations (`drawImage, drawImageRect, drawImageNine, drawAtlas, drawParagraph`). would get pixel aligned

**Comment by jonahwilliams** [comment]
Though you can still have rotated/transformed text. Maybe that doesn't matter.

Also if it is correct to pixel snap these values, i'd rather do it consistently (except flutter_tester). if its not correct, or there are better methods, then we shouldn't support this method at all

**Comment by knopp** [comment]
My ideal world:

- Layout widgets are physical pixel aware (i.e. child is always positioned on pixel boundary, and if sized by layout also size is pixel snapped)
- TextPainter `_applyFloatingPointHack` instead rounds to nearest physical pixel boundary (rounding to logical pixel doesn't help much with 150% scaling...)
- BoxDecoration rounds itself to physical pixels, i.e. 1.0 border is painted a 1px in 100-150% scaling, 2px 175%-250% scaling, 3px 275+, etc. Same goes for padding and margin. This way a Text + Padding + BoxDecoration dimensions would always be snapped on physical pixels. 

I think these together would get us quite far on low-dpi devices. Which is a significant amount of Windows PCs.

**Comment by Hixie** [comment]
RenderObjects don't know their context (and can't, for performance reasons). They could be placed inside another RenderObject that applies an arbitrary rotation or perspective transform, say. I'm not sure how we could ever do that ideal world given those constraints.

**Comment by knopp** [comment]
For layers, where pixel snapping makes difference, there will be only one scale transform above them (scale by devicePixelRatio). 

In practice devicePixelRatio value is same for entire window. Each layer could simply snap it's size to devicePixelRatio (i.e. `size.width = (size.width * devicePixelRatio).round() / devicePixelRatio`) as well as snap any translation that applies to children.

As long as all layers play nice, we should end up on pixel perfect coordinates.

Now if there an arbitrary scaling or perspective transform somewhere, then these pixel adjustments will mean that we land slightly different final (sub)pixels. But with arbitrary transforms like these we already gave up pixel alignment so all bets are off. 

This way we would trade sharp physical perfect appearance for possible very mild (hopefully?) distortion when using arbitrary scale/rotate transform.

I think it shouldn't be too difficult to build a prototype for this to see how it behaves in practice and whether my assumptions are right.

**Comment by Hixie** [comment]
Well, that's a different conversation, because that's about layers, not widgets or layout. Layers are always pixel snapped unless someone has applied a transform. Layers could know where they are (it's not free but it's possible, we use it e.g. for the follower layer). But it seems like if we're only concerned with layers that are axis-aligned and don't have unusual transformations applied then the only actual case where they may be off-grid would be during scrolling. We could provide an option that makes layers used in scrolling snap to the nearest physical pixel. I wouldn't want to do that by default, since it would reduce the quality of scrolling on modern systems, but it's possible to do.

**Comment by knopp** [comment]
Sorry, my bad, I actually meant render object. It's too early in the morning I guess :) I edited the comment.

This needs to be done on render object level (where the layout is calculated). Pixel snapping layers themself is too late.

**Comment by Hixie** [comment]
Render objects don't know their context (and can't, for performance reasons). They can't change their size arbitrarily (they have to obey the constraints). We considered doing this very early on in Flutter's design but decided (based on our experience with similar logic on the web) to not do it and the whole design of the rendering layer is predicated (in part) on this not being supported. I suspect (again based on the experience with web) that the results of such snapping in the framework would actually be quite frustrating for developers.

That said, developers that want things to line up with the pixel grid on devices with simple device pixel ratios can do this quite easily, FWIW, by only ever giving sizes in whole-numbered pixels. Things only go off-grid once the layout pushes it off-grid, it's not like the core layout widgets do it of their own accord. :-)

**Comment by knopp** [comment]
Device with simple pixel ratios were never the problem. But a _large_ amount of windows users are using 125%, 150% pixel scaling. Which makes pretty much any Flutter application blurry by default and there is no solution for this.

This is not problem with WPF or electron applications. With 150% pixel scaling 1 logical px box border on web will render as 1 physical pixel. With 175 pixel scaling, 1 logical px box border renders as two physical pixels. At no point it becomes blurry. This is the case for Electron, Web and WPF seems to work same. 

In my previous comment I never suggested layer changing size arbitrarily. Just that whenever layer sizes itself, it snaps the size to pixels (according to devicePixelRatio). This doesn't involve breaking constraints, because the constraints would alrady be pixel snapped.

Ideally this should be completely transparent to developers. Just like it is on web or Electron.

As a developer, if I do box 1px box border, I don't care if it renders as 1 or 2 physical pixels, as long as it stays sharp. But that's not the case right now.

**Comment by Hixie** [comment]
If you want a one-physical-pixel border, set the border width to 0.

**Comment by knopp** [comment]
But I don't want one physical-pixel-border. I want 1 physical pixel border on 100%, 125, 150% scaling, 2 physical border on 175 - 250% pixel scaling, 3 physical pixel border on 275-350% pixel scaling, etc. 

This is what Win UI applications do, as well as web browsers.

**Comment by Hixie** [comment]
Ah, right. That's the behaviour I was describing earlier as something we very explicitly decided not to do in the core of Flutter, because of our experience with this kind of thing on web. It's relatively straightforward to build widgets that do this, though. For example, you could have a "box" widget that takes a border width, and applies math to that border width to make it a round number of devicePixelRatio pixels and then passes it on to a BoxDecoration, or some such.

**Comment by Hixie** [comment]
(One example of the kind of problem you get with low-level snapping is that animating the transform ends up being very janky, e.g. because you suddenly have to change from being snapped half a pixel over from the "natural" position to being rotated by half a degree (which can't snap usefully).)

**Comment by jonahwilliams** [comment]
I no longer think this is a good idea. I'm closing the issue, but if you disagree feel free to reopen
