### ISSUE TITLE
setting up environment wiki pitfall: `gclient config`

### ISSUE THREAD

**Issue by clarkeaa** [flutter/flutter#111588]
The [Setting up the engine development environment wiki](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) mentions that using `gclient config` is an option for setting up a repo, but if you use that it will create a `.gclient` file that differs from the one specified in the wiki (the "managed" and "name" fields differ).  This will cause `gclient sync` to fail, but only after having downloaded 10GB of data and a half hour of processing.

We should make either:
1) Make `gclient config` work.  Maybe depot_tools has a way to read it from the git repository?
1) Update the wiki to give the full `gclient config` command that works
1) Remove the recommendation that `gclient config` can be used and add a warning about its usage
1) Make `gclient sync` fail quickly if the `.gclient` config file is wrong.  Maybe add some sort of validation early in the process.

**Comment by chinmaygarde** [comment]
I removed the section on `gclient config` in Wiki as that seems error prone. We should stick to authoring the `.gclient` file manually. I hesitate to mention `fetch flutter` from depot_tools that also works but that sets the the to upstream instead of your fork. There are obviously many ways of setting up that simple text file. For simplicity, let's just mention the one way we know will work.
