### ISSUE TITLE
Dart fix expect files aren't being analyzed and contain errors

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#111578]
While writing Dart fixes, I noticed that I couldn't get the analyzer (`flutter analyze ...`) to properly report errors for the .expect files. Renaming `material.dart.expect` to `material-expect.dart` and running the analyzer revealed 3768 errors.

e.g. creating a `ThemeData` but not specifying all properties gives you a bunch of errors like:
```
  error • The named parameter 'switchTheme' is required, but there's no corresponding argument • material-expect.dart:945:15 • missing_required_argument
```

We should fix the errors that matter and probably use .dart for all .expect files. cc @Piinks, @bwilkerson any thoughts?

**Comment by Piinks** [comment]
There is no analysis for the expect files because they are expected to have not fully functional code based on the transformation that has been applied.

For example, a transformation may add a parameter `newParameter: ` that is required, but left blank for the user to supply to value.

The expect files test that the transform is executed as expected and leaves it as simple as possible for readability and review.

Another example is all of the theme data migrations. The theme data constructor requires supplying a ton of parameters, which would be a ton of code to write just to validate one parameter changed, and easy to miss or introduce mistakes since other transformations like the first example cannot be subject to analysis.

**Comment by Piinks** [comment]
Also, I think `.expect` is the required format in order for the tests to work.

**Comment by guidezpl** [comment]
I see. I'm trying to minimize the amount of non-runnable code produced. I'll look at creating a more realistic test file (e.g. with multiple deprecated/renamed properties) which only includes fully automatic fixes.

Not being to analyze a file because it doesn't have a Dart extension is a separate issue, I'll look for that in dart-lang. Thanks
