### ISSUE TITLE
LUCI logs should interleave STDOUT and STDERR

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#111682]
This would have helped debugging the P0 https://github.com/flutter/flutter/issues/111482

For example, for this build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/7106/overview

The failing step has two links, one for "test_stdout" and one for "test_stderr":
![Screenshot from 2022-09-15 11-23-52](https://user-images.githubusercontent.com/7856010/190481060-de1205b9-8d20-4dca-b427-bd1579f3b526.png)

**Comment by yusuf-goog** [comment]
We are separating the streams ourselves: https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/test_utils/api.py;l=127

**Comment by yusuf-goog** [comment]
From an offline conversation on this topic:

it looks like it buffers both of these, separately, and then emits them both, separately
it looks like it's trying to process stdout/stderr in some way in order to summarize them somehow

I would usually recommend a wrapper script for this which:
  * runs the subprocess, streaming it's stdout/stderr to it's own stdout/stderr
  * returns any presentation/summary information the recipe needs via a sidechannel (e.g. json file)

(or even have the subprocess in question directly emit summary data to a JSON file)

at least until recipes learn to tee/stream process stdout/stderr themselves

step is almost certainly recipe_engine/step
it doesn't have an interleaved file
the stdout and stderr kwargs there are meant to capture small outputs from programs like git rev-parse HEAD

by default (with no kwargs) the stdout and stderr are logged directly as an interleaved stream to logdog

this output is also displayed in a streaming way, rather than buffered until the step ends
(other steps on this build do it the normal way)
the question is: what is the being done with that stdout/stderr data inside the recipe
presumably it's being buffered and captured for some reason?
actually this seems to be the only step in this build which is doing this 😛

**Comment by keyonghan** [comment]
This should have been supported now. Closing.

**Comment by christopherfujino** [comment]
@keyonghan I don't think it is?

![image](https://github.com/flutter/flutter/assets/7856010/5a12ecc0-2c5b-4dad-b710-cf05f8a6b345)

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/15141/overview

**Comment by keyonghan** [comment]
> @keyonghan I don't think it is?
> 
> ![image](https://private-user-images.githubusercontent.com/7856010/305209007-5a12ecc0-2c5b-4dad-b710-cf05f8a6b345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzM3MzMsIm5iZiI6MTcwODAzMzQzMywicGF0aCI6Ii83ODU2MDEwLzMwNTIwOTAwNy01YTEyZWNjMC0yYzViLTRkYWQtYjcxMC1jZjA1ZjhhNmIzNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMjE0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk4ZTMxNDU1YjI3ZTY2NDVmNGRmYjMxZDA4ZjNjZDE2YzczNWY0ZmY3N2YyNmU2NzQ5NzAxYjBmY2QwOWYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ic-A0YM4N85E7u5IWm0m6F6NxfAgoBGhdZyMW8OZi4E)
> 
> https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/15141/overview

This is a build from release branch, where I guess the recipe change is not cp'ed there yet.
See a most recent build from the tot: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/15142/overview

**Comment by christopherfujino** [comment]
> This is a build from release branch, where I guess the recipe change is not cp'ed there yet. See a most recent build from the tot: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/15142/overview

Oh wow, you're right! Who fixed this?!

**Comment by keyonghan** [comment]
Ha, credit to @godofredoc 
f.y.i. here is the recipe change: https://flutter-review.googlesource.com/c/recipes/+/54763
