### ISSUE TITLE
go_router flutter web intercept browser back button and refresh button

### ISSUE THREAD

**Issue by bobosette** [flutter/flutter#111669]
Hi everybody. Is there a way to intercept browser buttons with go_router?
For example I would like to go always to the home page when I refresh and I would like to display a message when I push the back button.

Thank you

**Comment by huycozy** [comment]
Hi @bobosette 
It looks like you are filing a feature request, right? 
Please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. 

If not so, please see https://flutter.dev/community for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.

Thank you!

**Comment by bobosette** [comment]
Ok thank you

Il giorno ven 16 set 2022 alle ore 09:27 huycozy ***@***.***>
ha scritto:

**Comment by huycozy** [comment]
Closing. Once you update the issue according to the information indicated in the template, please write in the comments and I will reopen it. Thank you!
