### ISSUE TITLE
flutter_markdown: Syntax Highlighting not working for GitHub Web Extension Set

### ISSUE THREAD

**Issue by studanshu** [flutter/flutter#111613]
## Steps to Reproduce
1. Edit the `original_markdown_example_metadata.md` file

I am looking at the example flutter_markdown application to understand how it works. While trying to edit the markdown as follows:
<img width="117" alt="image" src="https://user-images.githubusercontent.com/6619157/190274882-e00effb2-ad9e-4655-8384-79d8509f916f.png">
Syntax highlighting is not working. As per the [gfm](https://github.github.com/gfm/#example-112) this should be working.
**Expected results:** 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/6619157/190275026-58af4f3a-3634-466d-925e-3f44dd0ef186.png">

**Actual results:** 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/6619157/190274819-fe70b348-f747-4449-8426-5e0ce4980f22.png">

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hello @studanshu. This is expected behavior. The developer is expected to supply their own syntax highlighter through the [`syntaxHighlighter`](https://pub.dev/documentation/flutter_markdown/latest/flutter_markdown/MarkdownWidget/syntaxHighlighter.html) property. To see how to do this, see [this StackOverflow answer](https://stackoverflow.com/a/66869983/10845917).

Closing the issue as this is working as expected. Thank you.
