### ISSUE TITLE
[adaptive_scaffold] does not pass static analysis.

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#111638]
The [pub score for `flutter_adaptive_scaffold`](https://pub.dev/packages/flutter_adaptive_scaffold/score) does not pass static analysis. 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/44445638/190313463-09fbb247-a00a-4c94-aff9-0b5af495d714.png">

**Comment by a-wallen** [comment]
cc @stuartmorgan, I'm wondering what the right thing to do here is. It doesn't look like any of the 1p packages have `lints_core` as a dependency, but I'd like to be able to use it before making PRs for this package so that this doesn't happen again.

**Comment by stuartmorgan** [comment]
We've made an explicit choice to use `flutter/flutter` analysis options rather than `lints_core`. In almost, but not entirely, a superset of `lints_core`.

This particular case is something we [deliberately disable](https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L26-L27) because we follow flutter/flutter's policy of continuing to support non-NNBD mode, which means that we keep assertions that are no-ops according to that analysis setting, but actually do something for customers running in mixed mode.

Do you have a compelling reason that this particular package needs to deviate from that policy?

**Comment by a-wallen** [comment]
No, I don't have a compelling reason. I just want to make sure that `flutter analyze` will catch errors like these in the future. I suppose that something isn't set up properly, either on my machine or in the `flutter_adaptive_scaffold` folder.

**Comment by stuartmorgan** [comment]
I think there's some confusion about what pub.dev is reporting here. First, these aren't errors (or even warnings), but info messages, which is [the lowest of the three severity levels](https://dart.dev/guides/language/analysis-options#customizing-analysis-rules). Second, the textual description of `unnecessary_null_comparision` (which is what's showing in your screenshot) is misleading; it only "cannot be null" if the code is running in sound null safety mode. Otherwise it's not *supposed* to be null, but it can be. Checks that this linter option would consider dead code can be useful, and we deliberately still have a number of them in Flutter code for now because we support running in unsound mode.

> I just want to make sure that `flutter analyze` will catch errors like these in the future.

What I was explaining in my previous comment is that it won't, because we explicitly disabled this lint for the entire repository (matching flutter/flutter). We do not consider this to be a bug at this point, but a feature. The fact that pub.dev lowers the score because it's using a different linter configuration is unfortunate, but harmless.

> I suppose that something isn't set up properly, either on my machine or in the `flutter_adaptive_scaffold` folder.

It's not set up improperly, it's just set up differently than the pub.dev scoring analysis configuration, because we currently find that lint counter to our interests.

**Comment by a-wallen** [comment]
I appreciate the clarification @stuartmorgan. 

> We do not consider this to be a bug at this point, but a feature. The fact that pub.dev lowers the score because it's using a different linter configuration is unfortunate, but harmless.

It sounds to me like we don't care about increasing the pub score, should I close https://github.com/flutter/packages/pull/2602 as well as this issue?

**Comment by stuartmorgan** [comment]
Generally the code we have that the lint would flag are asserts, not logic, since passing null is still an API violation. If these specific null checks are just mistakes it's fine to remove them.

**Comment by a-wallen** [comment]
That makes sense.

https://github.com/flutter/packages/blob/c3b436ccf0ff8012de3796144ee995e713cd8046/packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart#L79-L104

I think it should be fine to remove `widget.destinations != null` and `widget.selectedIndex != null` as they will have a value when an `AdaptiveScaffold` is created.
