### ISSUE TITLE
Autocomplete not working since update to Flutter SDK 2.10

### ISSUE THREAD

**Issue by mohbasirudin** [flutter/flutter#111734]
Since i update flutter sdk from 2.3 to 2.10, my autocomplete not working, i was try it using Android Studio and Vs Code. and i was update my flutter sdk to 3, delete and download again from official website, and try to uninstall my windows, but, nothing has changed, i got same problem, my autocomplete not working. why it happen? or that feature was remove from flutter?

and i got same problem in macOs too.

![sdk](https://user-images.githubusercontent.com/46457480/190580783-b6288aea-7098-42f7-9321-e883f047bd4f.png)
![doctor](https://user-images.githubusercontent.com/46457480/190580770-64e8cedd-9ac3-425a-9d00-d659b75904b9.png)

**Comment by darshankawar** [comment]
@mohbasirudin 
This was an issue with Dart analyzer which was being tracked here: https://github.com/dart-lang/sdk/issues/49054 and has since been fixed and released already. https://github.com/flutter/flutter-intellij/issues/6176#issuecomment-1134959662

I verified this using latest master and autocomplete works properly:

<img width="657" alt="Screenshot 2022-09-16 at 5 46 23 PM" src="https://user-images.githubusercontent.com/67046386/190637305-48e7ea1b-dceb-4e1d-8c25-a66a32064a4c.png">


Closing as this is not an issue with flutter. Please upgrade your config / setup and dart sdk version to get the fix.

**Comment by mohbasirudin** [comment]
> @mohbasirudin This was an issue with Dart analyzer which was being tracked here: [dart-lang/sdk#49054](https://github.com/dart-lang/sdk/issues/49054) and has since been fixed and released already. [flutter/flutter-intellij#6176 (comment)](https://github.com/flutter/flutter-intellij/issues/6176#issuecomment-1134959662)
> 
> I verified this using latest master and autocomplete works properly:
> 
> <img alt="Screenshot 2022-09-16 at 5 46 23 PM" width="657" src="https://user-images.githubusercontent.com/67046386/190637305-48e7ea1b-dceb-4e1d-8c25-a66a32064a4c.png">
> 
> Closing as this is not an issue with flutter. Please upgrade your config / setup and dart sdk version to get the fix.

thanks bro, i just update to this version, and working correctly. now, i can show autocomplete like "(context, index) =>" when i click ctrl+space.

I was very confused before, and made me write code very slowly because of that problem. thanks bro 

![done](https://user-images.githubusercontent.com/46457480/190649279-c750fbc6-c352-43ac-a697-80e3163bd1da.png)
![sdk-3-3-2](https://user-images.githubusercontent.com/46457480/190647703-a6ddd8fb-3109-4b70-88de-da0d6927bcd8.png)
