### ISSUE TITLE
[Proposal] Include an iconColor property in OutlinedButtonThemeData

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#111768]
## Use case
I want my `OutlinedButton.icon` to respect the IconTheme. Instead, it uses `foregroundColor`.

## Proposal
Include an `iconColor` property in OutlinedButtonThemeData.

Additional question : Why provide a foreground color that overrides the color of the TextStyle (and other things such as the icon's color) ? Seems simpler to respect the TextTheme and IconTheme and provide arguments to OutlinedButtonThemeData to change them for that button style.

**Comment by huycozy** [comment]
Hi @TheCarpetMerchant, thanks for filing the issue.
But as far as I can see, it seems to be no consensus between the use case and the proposal.

I assume that there will be an `iconColor` property in **OutlinedButtonThemeData** as you proposed. And you will use **OutlinedButtonThemeData**'s `iconColor` instead of **IconThemeData**, right? 
If so, how will this change solve the issue raised in the use case? 

To be more intuitive, I give the sample code and demo below to show that using `iconTheme` and `outlinedButtonTheme` still achieves the expected results without a new `iconColor` property.

- To change `OutlinedButton.icon` color: 
```
iconTheme: IconThemeData(color: Colors.green)
```
- To change `Icon` color: use `iconTheme`:
```
outlinedButtonTheme: OutlinedButtonThemeData(
  style: ButtonStyle(
    foregroundColor: MaterialStateProperty.all(Colors.amber),
  ),
),
```

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        iconTheme: IconThemeData(color: Colors.green),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: ButtonStyle(
            foregroundColor: MaterialStateProperty.all(Colors.amber),
          ),
        ),
      ),
      home: Scaffold(
        body: Container(
          alignment: Alignment.center,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              OutlinedButton.icon(
                onPressed: () {},
                icon: Icon(Icons.add),
                label: Text('Flutter'),
              ),
              Icon(Icons.ac_unit),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo</summary>

<img width="500" alt="Screen Shot 2022-09-19 at 12 36 07" src="https://user-images.githubusercontent.com/104349824/190955238-208ab51e-ab41-436b-9377-afe312a5efa5.png">

</details>

Please describe this proposal in more detail. Thank you!

**Comment by TheCarpetMerchant** [comment]
@huycozy Your example doesn't reflect the issue here : I'm talking about the color used for the icon of OutlinedButton, not icons in general. And as your example shows, there is no way of changing that color using the existing theme info, hence my proposal of adding an iconColor to OutlinedButtonThemeData.

**Comment by huycozy** [comment]
Hi @TheCarpetMerchant 
>I'm talking about the color used for the icon of OutlinedButton, not icons in general. And as your example shows, there is no way of changing that color using the existing theme info

Why can't you change OutlinedButton icon's color with `foregroundColor`? 
The below sample shows that you can change the color of icon as a child for OutlinedButton, it will respect `foregroundColor`:

- Sample code:

```dart
OutlinedButton.icon(
  onPressed: () {},
  icon: Icon(Icons.add),
  label: Text('Flutter'),
),
OutlinedButton(
  onPressed: () {},
  child: Icon(Icons.access_alarm),
),
Icon(Icons.ac_unit),
```

- Result:
<img width="159" alt="Screen Shot 2022-09-20 at 10 20 27" src="https://user-images.githubusercontent.com/104349824/191160100-92d0e312-33b8-4ceb-9940-4fd074c0e21c.png">

Perhaps the issue will be clearer if you show the limitation of using `foregroundColor` or give a more detailed example.

**Comment by TheCarpetMerchant** [comment]
@huycozy Because then it ignores the textStyle. I want to be able to set a color for the icon which will not be used for `child` and its children.

**Comment by huycozy** [comment]
@TheCarpetMerchant Labeling this issue as a proposal for further insights from the team.

**Comment by HansMuller** [comment]
It's now possible to separately specify the iconColor, see https://api.flutter.dev/flutter/material/ButtonStyle/iconColor.html
