### ISSUE TITLE
How to fix red errors in MainActivity.kt?

### ISSUE THREAD

**Issue by NTA-trongpq** [flutter/flutter#111733]
![image](https://user-images.githubusercontent.com/102949116/190581893-27b81cf4-7d22-453b-b6cf-75a526cd3554.png)
I was assigned SDK (File -> Project Structure). 
How to fix it?

**Comment by danagbemava-nc** [comment]
Hi @NTA-trongpq, you have opened an `android` project while a flutter project is active in your editor which is why you're seeing the errors. 

These 2 projects are not compatible. If you open the android folder (you can do this by clicking on "Open for Editing in Android Studio" in the toolbar) the errors should go away. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by NTA-trongpq** [comment]
> 

Thank you for responding. But, I haven't opened an `android` project. I only open flutter project and but not other project.

**Comment by danagbemava-nc** [comment]
The `MainActivity.kt` file belongs to the `android` project(the `android` folder in your root directory). It is an android project file, not a flutter project file. If you open those files for editing, you are essentially opening an android project file in a flutter project. 
That is why the toolbar appears asking you to open for editing in android studio.

**Comment by NTA-trongpq** [comment]
@danagbemava-nc That mean everything that happen is normal?

**Comment by danagbemava-nc** [comment]
It is normal if you try to open an android project file while a flutter project is currently open in Android Studio.
