### ISSUE TITLE
Tool startup benchmarks are queued forever

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111748]
Not sure what they are waiting on or how to debug it. Are we possibly requesting some hardware configuration that does not exist? Clicking view logs gives me a 404

**Comment by keyonghan** [comment]
This is due to ci.yaml roller latency: when a target is first created, it will not get scheduled until the roller lands.
<img width="115" alt="Screen Shot 2022-09-16 at 9 43 34 AM" src="https://user-images.githubusercontent.com/54558023/190688573-d7621949-ac40-47eb-af8f-371b5e184f53.png">

The root fix of this issue is deprecate CI yaml roller, and instead use general single builder.

To workaround, I have updated the task statues to `New`, and they should be picked up by the back filling.

**Comment by keyonghan** [comment]
After back filling picked up these three targets, they still return 404 (the console is not ready).
Taking a further look, there is a race condition: the ci yam was first rolled to https://github.com/flutter/flutter/commit/b7b8b759bc3ab7a80d2576d52f7b05bc1e6e23bd, and then rolled back to earlier: https://github.com/flutter/flutter/commit/19058fd65e218c49d4954d2eeac69560c20b4a7c

The root fix is the same as above mentioned.

To workaround, I will trigger those builds when the roller lands for the latest commit: https://github.com/flutter/flutter/commit/8074811c2f1ec801aff9487e4ba7f49ab540bbd3

**Comment by keyonghan** [comment]
Tasks are being scheduled.

**Comment by keyonghan** [comment]
Tasks are scheduled and went through. Close here and leave the general builder with https://github.com/flutter/flutter/issues/97265
