### ISSUE TITLE
How to disable pop-up view but  programmatically in Samsung phone having this feature?

### ISSUE THREAD

**Issue by pranavo72bex** [flutter/flutter#111726]
I want to disable Pop-up view in Samsung phone which is causing overflow in the app.

![Screen Shot 2022-09-16 at 11 07 37](https://user-images.githubusercontent.com/71395812/190562606-87a76faa-0a01-4ba3-b93e-24c21d644459.png)

```Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.6 21G115 darwin-arm, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability```

**Comment by huycozy** [comment]
Hi @pranavo72bex, 
Please provide the information indicated below so that we may verify the issue properly:
- Reproduction steps, Expected results, Actual results
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Affected device information

Also, you are using the old Flutter version `2.10.5`, the latest Flutter stable is `3.3.2` and the master is `3.4.0`. Please try upgrading them and retry to see if this issue still reproduces.

Thank you!

**Comment by pranavo72bex** [comment]
> Hi @pranavo72bex, Please provide the information indicated below so that we may verify the issue properly:
> 
> * Reproduction steps, Expected results, Actual results
> * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> * The output of `flutter doctor -v`
> * Affected device information
> 
> Also, you are using the old Flutter version `2.10.5`, the latest Flutter stable is `3.3.2` and the master is `3.4.0`. Please try upgrading them and retry to see if this issue still reproduces.
> 
> Thank you!

`I just want to know how can I disable this feature of Pop-up view from flutter ? I do not want this into my app`

**Comment by huycozy** [comment]
>I just want to know how can I disable this feature of Pop-up view from flutter ? I do not want this into my app

Hi @pranavo72bex 
It seems your question is best suited for support channels like StackOverflow (please see this StackOverflow answer if it can help: https://stackoverflow.com/a/33566631/5921933), so please ask the same there for solutions if any. 

You may also get some help on https://flutter.dev/community/ and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.

Closing from here as this is more of a `how-to` question rather than a bug or feature request.

**Comment by pranavo72bex** [comment]
No it didn't work for me  [Link](https://stackoverflow.com/questions/30783758/how-to-make-app-support-samsungs-popup-view/33566631#33566631).
