### ISSUE TITLE
[file_selector] Documentation enhancements

### ISSUE THREAD

**Issue by VanesaOshiro** [flutter/flutter#111753]
## Issue
While exploring the documentation, we noticed that there are changes that can be applied to extend the current documentation.

Documentation: https://github.com/flutter/plugins/blob/main/packages/file_selector/file_selector/README.md

## Proposal
Extend the current documentation by adding:
- Table of contents
- Table of available parameters
- Table of available methods
- The missing GetDirectoryPath method example

**Comment by stuartmorgan** [comment]
> * Table of contents

This is not standard practice for our READMEs, and this README is not very long. Is there a reason you think this would be useful? 

> * Table of available parameters

Fully documenting every parameter is a non-goal for the README, since it duplicates the [API documentation](https://pub.dev/documentation/file_selector/latest/file_selector/file_selector-library.html), and is almost guaranteed to become outdated as the APIs change (unlike the API docs which are co-located with the code that would change).

> * Table of available methods

This seems reasonable (assuming you mean something like https://pub.dev/packages/path_provider#supported-platforms-and-paths that shows supported platforms).

> * The missing GetDirectoryPath method example

This seems reasonable as well.

**Comment by VanesaOshiro** [comment]
Thanks!, we'll follow your suggestions.

**Comment by stuartmorgan** [comment]
This was done in the PR above.
