### ISSUE TITLE
Flutter TextField MaxLenght Emoji Count Fix

### ISSUE THREAD

**Issue by utkudenis** [flutter/flutter#111809]
## Use case
Flutter TextField Widget counts emojis as 1 character. When we check it with the trim() method, it counts as 2 characters.
Can the Flutter TextField Widget count mechanism count emojis as 2 characters?

## Proposal
Counting emojis as 2 characters when using the TextField maxlength field.

**Comment by jonahwilliams** [comment]
We're not going to fix this because it is quite intentional that the text count reflects what users would think of as a single character. 

Consider using https://pub.dev/packages/characters instead to supplement your string operations, or posting a more specific help requests to one of the forums at [flutter.dev](https://flutter.dev/community)
