### ISSUE TITLE
API key for Google Maps is stored insecurely

### ISSUE THREAD

**Issue by vporton** [flutter/flutter#111891]
## An easy to exploit security bug
In https://pub.dev/packages/google_maps_flutter it is told to store API keys for Google Maps in `android/app/src/main/AndroidManifest.xml` and `ios/Runner/AppDelegate.m`.

Storing API keys this way is insecure, because these files are part of the source.

## Proposal
Instead the API key should be passed as environment variables (usually stored in `.env` file that is not meant to be distributed with the source).

**Comment by exaby73** [comment]
Hello @vporton. Please follow the official [Google Maps documentation](https://developers.google.com/maps/api-security-best-practices) to secure your API keys.

There are also resources like [this video](https://www.youtube.com/watch?v=X8lYNW_Or2o) by the official Google Maps YouTube channel for hiding the API key on Android or [this article](https://appunite.com/blog/how-to-securely-use-google-maps-api-key-in-android-i-os-or-flutter-project) that explains how to do it for both Android and iOS.

Since this is not an issue with Flutter or the google maps plugin itself, I am closing this issue. If you disagree, please comment and I can reopen it.
