### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by sgshivamgarg8** [flutter/flutter#111812]
Can we have some good working and officially supported Pre commit / Pre push git hooks package for flutter.
Something just like husky.

I searched online and found no good package or an easy way to add pre commit hooks in flutter. There are some ways using node packages but I dont want to do that because then those packages cant be bound to project itself and everyone in the team needs to set it up manually instead if it is a dart package it can be linked in dev_dependencies itself.

**Comment by exaby73** [comment]
Hello @sgshivamgarg8. This issue does not see feasible. Currently, there are lots of packages that the Flutter team is maintaining, though related to Flutter. What you are suggesting is a pure Dart package. Maybe this is something the Dart team would consider. You can try by raising this issue in [dart-lang/sdk](https://github.com/dart-lang/sdk).

Closing as this issue is not related to Flutter diectly.
