### ISSUE TITLE
Quick Actions Plugin Rendering Greyed Icons

### ISSUE THREAD

**Issue by vjk10** [flutter/flutter#111955]
Quick Action is rendering Drawables properly in one build type when released to the play store, but fails to render when building in type release to the play store. 

The build was generated for both using

`flutter build appbundle --no-shrink`

**Build Type: Profile**

![Screenshot_20220920-151425.png](https://user-images.githubusercontent.com/41936318/191225516-b65003a7-9a1c-4648-9224-1173168ac585.png)

**Build Type: Release**

![Screenshot_20220920-151443.png](https://user-images.githubusercontent.com/41936318/191225593-a1535f0e-3365-4562-ac03-89015c04b238.png)

- The Drawables are generated by Vector Assets for all - build types. 
- keep.xml is generated and resource is added to style.xml as well.
- The issue is not present when running
   `flutter run --release`

Please help me understand why this is happening.

Any help is appreciated. Thanks!

**Comment by vjk10** [comment]
Plugin used quick_actions:1.0.0

**Comment by huycozy** [comment]
Hi @vjk10 
Did you check this note? https://pub.dev/packages/quick_actions#android

> If the drawables used as icons are not referenced other than in your Dart code, you may need to [explicitly mark them to be kept](https://developer.android.com/studio/build/shrink-code#keep-resources) to ensure that they will be available for use in release builds.

**Comment by vjk10** [comment]
Hey @huycozy ,

Yes it was done. And this was only happening in the app bundle uploaded to the play store and only for the release variant. When uploading an app bundle with the profile variant everything works fine.

**Comment by huycozy** [comment]
Hi @vjk10 
I saw your comment in #51455, it looks like you tried all workarounds there (https://github.com/flutter/flutter/issues/51455#issuecomment-593152837 and https://github.com/flutter/flutter/issues/51455#issuecomment-649388878), right?

Also, did you try building to `appbundle` and installing it with [bundletool](https://developer.android.com/studio/command-line/bundletool) to see if the issue can reproduce locally? And which build command have you used?

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by vjk10** [comment]
The issue started appearing after I created multiple build types. I was able to resolve this by clearing shortcuts and re-initializing them. Thanks for the time.
