### ISSUE TITLE
How to Set Maximum Lines Set in Markdown Body?

### ISSUE THREAD

**Issue by DazzlingCVa** [flutter/flutter#111951]
if Any One Know Answer Pls Tell Me @sethladd @gmoothart @sgraham @anaisbetts @ianloic

**Comment by DaymaManish** [comment]
The ideal solution would be to clone the original package and add an extra widget in there so that you can provide overflow/maxLines properties and interrupt/extend the parsing logic when overflow and/or maxLines is set to limit the children that get built.

Working on the assumption that the length of the markdown is minimal for your incoming data, you could just extend MarkdownWidget in your own project instead and hack it in like this (saves you writing your own parser or having to clone another project): @DazzlingCVa 


`import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

class SingleLineMarkdownBody extends MarkdownWidget {
  final TextOverflow overflow;
  final int maxLines;

  const SingleLineMarkdownBody(
      {Key key,
      String data,
      MarkdownStyleSheet styleSheet,
      SyntaxHighlighter syntaxHighlighter,
      MarkdownTapLinkCallback onTapLink,
      Directory imageDirectory,
      this.overflow,
      this.maxLines})
      : super(
          key: key,
          data: data,
          styleSheet: styleSheet,
          syntaxHighlighter: syntaxHighlighter,
          onTapLink: onTapLink,
          imageDirectory: imageDirectory,
        );

  @override
  Widget build(BuildContext context, List<Widget> children) {
    var richText = _findWidgetOfType<RichText>(children.first);
    if (richText != null) {
      return RichText(
        text: richText.text,
        textAlign: richText.textAlign,
        textDirection: richText.textDirection,
        softWrap: richText.softWrap,
        overflow: this.overflow,
        textScaleFactor: richText.textScaleFactor,
        maxLines: this.maxLines,
        locale: richText.locale);
    }

    return children.first;
  }

  T _findWidgetOfType<T>(Widget widget) {
    if (widget is T) {
      return widget as T;
    }

    if (widget is MultiChildRenderObjectWidget) {
      MultiChildRenderObjectWidget multiChild = widget;
      for (var child in multiChild.children) {
        return _findWidgetOfType<T>(child);
      }
    } else if (widget is SingleChildRenderObjectWidget) {
      SingleChildRenderObjectWidget singleChild = widget;
      return _findWidgetOfType<T>(singleChild.child);
    }

    return null;
  }
}`

**Comment by huycozy** [comment]
Hi @DazzlingCVa 
There are some known issues that are tracked: #81739, #81787. Closing this issue as a duplicate, so please follow up on these issues for further updates. 

Note: We have [triage process](https://github.com/flutter/flutter/wiki/Triage) for issues. Next time, please don't mention people randomly.
Thank you!

**Comment by DazzlingCVa** [comment]
Thanks For help Next I Don't Mention People Name
