### ISSUE TITLE
Keep state of Route in ShellRoute like in NestedNaviagtion 4.0 with TabView

### ISSUE THREAD

**Issue by DieGlueckswurst** [flutter/flutter#111991]
## Use case

I just migrated to **5.0** and updated my `Nested Navigation` using the newly introduced `ShellRoute`. The basics are working but it comes with several problems:

**1.** 
The state of each page is lost when changing a Tab. 

**2.**
Since the state is lost, every page is completely rebuild after changing the tab which should not happen.

## Proposal

In **4.0** `NestedNavigation was done with a `TabView`. It was a bit more complicating and more code but because a `TabView` was used, we were able to keep the `state`. 

Another scenario that I would highly appreciate is: 

1. on  ScreenA -> going to a `subroute`
2. navigating to **ScreenB** via the NavBar
3. navigating back to **ScreenA** -> expected Result: still on the subroute without a `rebuild`

**Comment by huycozy** [comment]
Hi @DieGlueckswurst, thanks for filing a detailed issue. 
However, this issue was raised at https://github.com/flutter/flutter/issues/108044#issuecomment-1250262939 and led to #99124.
Closing this issue as a duplicate, so please follow up on #99124 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
