### ISSUE TITLE
GestureDetector is not working with webview

### ISSUE THREAD

**Issue by jg-kod** [flutter/flutter#111945]
I want to detect tap event on webview. Here is my code

`@override
Widget build(BuildContext context) {

  return GestureDetector(
    behavior: HitTestBehavior.translucent,
    onTap: () {
      if (kDebugMode) {
        print("tapped");
      }
    },
    child: WebView(
      initialUrl: "flutter.dev",
    ),
  );
}`

I had also tried HitTestBehavior.opaque property.
Can you help me to solve this problem?

**Comment by huycozy** [comment]
Hi @jg-kod
It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and ask questions like this.
You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. 
Thank you!
