### ISSUE TITLE
Go Router using ":" in deeplink url can't be used

### ISSUE THREAD

**Issue by theobouwman** [flutter/flutter#112079]
When I use a `:` in a deeplink url it get encoded and decoded in the `go_router` `match.dart` file at line 32. I am using `go_router` version `4.4.1`.

This way when a url with a `:` is encoded which becomes `%3A`. This way the assertion fails.

This is the assertion:
`assert(p.value == Uri.encodeComponent(Uri.decodeComponent(p.value)), 'encodedParams[${p.key}] is not encoded properly: "${p.value}"');`

Reproduce:
- `$ xcrun simctl openurl booted scheme://domain.com/portal/54705ed93fc64c3c899a2d1afbe635ad:339bd3547ee943128bf8d5271a9a7eba`
- Error occurs

Workaround is to just not use a `:` in urls.

**Comment by huycozy** [comment]
Hi @theobouwman, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In this case, it may contain native code for deep link so please push the sample code into a GitHub repository and make it public. Thank you!
