### ISSUE TITLE
In-app subscription iOS not working with SandBox testers

### ISSUE THREAD

**Issue by Pratiksha0796** [flutter/flutter#112100]
As I'm working on In-app subscription for iOS, it takes approx. 30 minutes to open Payment options for sandbox testers.
Second issue is whenever I call CompletePurchase method for force purchase it shows "storekit_duplicate_product_object" exception.
I'm using flutter version - 2.0.3
 in_app_purchase: ^0.5.2

Please guide me to implement in-app subscription for iOS.

**Comment by huycozy** [comment]
Hi @Pratiksha0796 

>I'm using flutter version - 2.0.3
in_app_purchase: ^0.5.2

You are using a quite old Flutter SDK and `in_app_purchase` plugin version. The latest Flutter SDK stable is `3.3.2` and `in_app_purchase` plugin is `3.0.7`. So, try upgrading them and retrying to see if the issue is reproducible.

> Please guide me to implement in-app subscription for iOS.

The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project,
but to improve flutter reporting bugs or feature requests. Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by Pratiksha0796** [comment]
Hi @huycozy ,
Thanks for your reply.

Is there any way to solve this issue with my existing flutter version and plugin version.
Because we have more than 5 apps are live on this version and we don't need big change right now.

**Comment by huycozy** [comment]
Hi @Pratiksha0796 
There are many changes through versions of the Flutter SDK as well as the IAP plugin. For the best support, you should update them to the new version and check again. Thanks!
