### ISSUE TITLE
[Impeller] Question about color filter performance

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#112167]
I noticed that both color filter and image filter are inherited from FilterContents, and the output is Snapshot, so I have the following question, I would be very grateful if you guys can reply.

From the code point of view, for the color filter, each filter means executing a corresponding pipeline: reading the value in the texture as the color input, then calculating the result via the fragment shader, and finally writing the result to the texture.

Suppose we concatenate N color filters together (although there may be no such ability now),looks like that means that we have to execute N pipelines, is this performance good? 

I learned that in some other vector renderers, these color filters seem to be executed in the same pipeline, each color filter corresponds to a shader function, and these functions are then chained. It sounds like the performance would be better.

Please let me know if I missed something.

@chinmaygarde @bdero Would you guys mind enlightening me? Thanks again!

**Comment by bdero** [comment]
Great question -- having an uber shader for color filters is something that may become desirable down the road, but since it's not possible for Flutter users to combine color filters right now, such a change wouldn't really have an impact.

Something else to note about color filters is that for a good chunk of cases, using FilterContents at all is extremely overkill! If someone sets a color filter and they just draw a path without any image filter set, the least expensive solution would be to apply the color filter to the single path color on the CPU.

We haven't done stuff like this yet because we've been mostly adopting an approach of profiling against production apps (and reasonably realistic test apps) to direct focus and we haven't run into problems in this area yet.

**Comment by ColdPaleLight** [comment]
> Great question -- having an uber shader for color filters is something that may become desirable down the road, but since it's not possible for Flutter users to combine color filters right now, such a change wouldn't really have an impact.
> 
> Something else to note about color filters is that for a good chunk of cases, using FilterContents at all is extremely overkill! If someone sets a color filter and they just draw a path without any image filter set, the least expensive solution would be to apply the color filter to the single path color on the CPU.
> 
> We haven't done stuff like this yet because we've been mostly adopting an approach of profiling against production apps (and reasonably realistic test apps) to direct focus and we haven't run into problems in this area yet.

Got it, thanks!

**Comment by chinmaygarde** [comment]
Closing this as addressed.
