### ISSUE TITLE
[build/test/archive] Inconsistent naming of artifacts.zip

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#112187]
artifacts.zip content is inconsistent across runtime modes in mac.

* [darwin-x64/artifacts.zip](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8802320213067283889/+/u/Zip_darwin-arm64_artifacts.zip/stdout) contains 11 files
* [darwin-x64-profile](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8802320213067283889/+/u/Zip_darwin-arm64-profile_artifacts.zip/stdout) contains only gen_snapshot

**Comment by godofredoc** [comment]
\cc @jmagman @zanderso

**Comment by zanderso** [comment]
@godofredoc Could you describe a bit more about the issue that you're facing? IIRC, the `darwin-x64` directory contains artifacts that are shared across modes, so it makes sense that it has more files. It probably doesn't have `gen_snapshot` because debug mode doesn't use an AOT compiler. If the `darwin-x64-profile` directory only contains `gen_snapshot` then that would be because that's the only file beyond the ones in `darwin-x64` that profile mode needs.

**Comment by godofredoc** [comment]
Updated the target generating artifacts.zip to only include gen_snapshot for non debug builds and updated the list of files to include the new files added to recipes.

https://github.com/flutter/engine/pull/36358/files

**Comment by godofredoc** [comment]
Closing as this is the intended behavior and https://github.com/flutter/engine/pull/36358 has landed.
