### ISSUE TITLE
get name2 deprecation causing Dart -> Engine roll to fail

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112176]
https://dart.googlesource.com/sdk.git/+/e03170035a3251a8039478dda8396e4381db4d09

Failing in https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/18808/overview

For rolls starting in https://github.com/flutter/engine/pull/36344

cc @scheglov @iskakaushik @a-siva

**Comment by scheglov** [comment]
I don't think there is anything wrong with the analyzer here. We can deprecate APIs, if clients choose to treat this as breaking for them, to always be on the most recent APIs (good), it is up to the clients to update.

**Comment by srawlins** [comment]
I don't think it is documented, what is a breaking change for this roller. Flutter needs to hand down a doc which describes what changes can or cannot be made in the Dart SDK, which would make this roller fail (and equivalently (? I hope?) make the HHH bot turn red). The HHH bot is too slow for us to require it to be run, and pass, on presubmit for every dart-sdk/pkg/analyzer change.

Or rather, we don't even know which code _anywhere_ could cause HHH bot to fail. Maybe a repo somewhere in the flutter GitHub organization depends on `_fe_analyzer_shared` and we don't know about it.

So, one example: it appears that marking an API in the Dart SDK as deprecated is a change which may cause the roll to fail. This is an example of what would appear in that document. In this case, before an engineer deprecates anything in the Dart SDK, they need to either run HHH bot, or grep some set of files for that API. Do we have that list of files? Is there a google3 set of directories we can grep in csearch, or perhaps a set of flutter repositories we should check?

**Comment by a-siva** [comment]
I am really not sure if it is possible to document the set of tests that need to be run or set of files that need to checked to ensure the Flutter tree does not break.

In the VM team we have followed this process
- if we know apriori that a change is going to break Flutter we try and make changes to Flutter tree before landing the breaking change if that is possible or we stop the auto roller and do a manual roll of Dart into Flutter wherein the breaking change and the corresponding Flutter changes are submitted together
- it is not always that we know a change is going to break Flutter and so we always monitor the Dart to engine roller and the Flutter HHH bots actively as part of our gardenning duties, if a breakage is noted we try and revert the Dart change that caused it so that the roller is unblocked and then investigate the breakage and follow the step above to land the change

**Comment by Lsaier** [comment]
I will never break. Try me if u brave!

**Comment by jacob314** [comment]
Perhaps the best path forward is to eliminate all source dependencies on Analyzer package in the Flutter repos and prohibit adding future dependencies. The only dependency we are aware of is
https://github.com/flutter/engine/tree/06a54f48b2256e8758ca761fca0261ede2e937a2/tools/api_check

this utility could be slightly generalized and moved to the dart_sdk so that it is easier for the analyzer team to update it with analyzer pull requests. Fyi @yjbanov who I believe owns the api_check tool.

**Comment by jacob314** [comment]
Fyi @cbracken who wrote this tool.

**Comment by cbracken** [comment]
That seems reasonable. That tool was hacked together pretty quickly after the nth (>5 and probably >10) time that our a11y enums as defined in C++/Dart/Java got out of sync in order to prevent that sort of breakage from happening again. 

It's currently pretty specific to the a11y enums and the C++/Java checking is... well, let's just say I'm not proud of it. If someone wanted to clean this up and generalise, and have it live somewhere else, that works for me.

**Comment by cbracken** [comment]
Just a quick note that the "tests" directory is testing engine APIs, not testing the package itself. This is, unfortunately, how a bunch of tests are written in the engine. You'd probably want the code in the tests directory to remain in the engine repo if the tool were moved out.

I suspect that even the code in the lib dir may make some pretty strong assumptions about the naming of our current enums -- it's been a while since I banged this up.

**Comment by srawlins** [comment]
@cbracken what is the reason for overriding all of the dependencies to pull directly from the local Dart SDK? This would also not have been breaking if they had been pub dependencies.

**Comment by cbracken** [comment]
Someone else might remember the details/history here, but this is standard practice for all Dart tooling in the engine, for example:
* https://github.com/flutter/engine/blob/main/tools/licenses/pubspec.yaml
* https://github.com/flutter/engine/blob/main/tools/const_finder/pubspec.yaml
* https://github.com/flutter/engine/blob/main/tools/clang_tidy/pubspec.yaml

This is the issue decribing the rationale: https://github.com/flutter/flutter/issues/82134

**Comment by cbracken** [comment]
Aside that may be better discussed in a separate meeting or issue:

It sounds like the issue here isn't so much that Flutter is using the analyzer package, or even that we interpret lints as errors -- typically, that would just mean the whoever is engine sheriff is responsible for patching up the roll to move off the deprecated stuff -- but rather, that our lint==error behaviour causes the Dart head-head-head bot goes red and then the committer scrambles to check whether it's a legitimate breakage or just a lint that someone on the engine side will need to patch?

I wonder if there's a broader conversation to be had as to whether we're currently taking the right tooling approach with regards to deprecation.

**Comment by zanderso** [comment]
> This is the issue decribing the rationale: https://github.com/flutter/flutter/issues/82134.

Before https://github.com/flutter/flutter/issues/82134 (and still in one or two places) there was confusion about how/from where dependencies entered the Engine tree. Some dependencies came in through pub, and others came in through the DEPS file. We decided to unify on the DEPS file both because it is the only option that works for everything, and as a follow-up after an outage in which pub.dev wasn't accessible from our Windows machines in CI for an extended period of time.
