### ISSUE TITLE
Framework presubmits failing on git checkout (?)

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112194]
Saw this in https://github.com/flutter/flutter/pull/112193. Marking P0 because this is blocking autorolls.

**Comment by keyonghan** [comment]
Here is one PR with passing cirrus jobs around 2 hours ago: https://github.com/flutter/flutter/pull/112178
The issue started just a while ago.

**Comment by keyonghan** [comment]
Following up with cirrus team via email per https://github.com/flutter/flutter/issues/110810#issuecomment-1234857420. We may expect slow response.

**Comment by keyonghan** [comment]
From Cirrus Team:

> _We've got such reports in the last hour about random failures like this. At this point we believe it's an issue on GitHub side even though their [status page is green](https://www.githubstatus.com/)._

> _We are looking if there is something we can do to workaround the issue..._

Will update here if any workarounds.

**Comment by keyonghan** [comment]
We are seeing this failure in LUCI builds as well: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/42017/overview
```
fatal: couldn't find remote ref refs/pull/112201/head
[W git.go:289] Transient error string identified in STDERR: "fatal: couldn't find remote ref refs/pull/112201/head\n"
[W git.go:300] Retrying after 2s (rc=128): transient error string encountered
```

**Comment by jonahwilliams** [comment]
Seeing it across all of the targets here: https://github.com/flutter/flutter/pull/112191

**Comment by fkorotkov** [comment]
I was very disappointed about GitHub not acknowledging the issue so I dig a bit more in how Actions do clones. Since if GHA would've fail than it would be definitely noticed. It appeared they are using `refs/pull/112201/merge` ref instead of `refs/pull/112201/head` so in order to mitigate the issue we had to switch to the `merge` ref as well. This change has been just deployed and you can re-run your tasks (no need to push new commits). See https://github.com/cirruslabs/cirrus-ci-agent/pull/247 for more details.

**Comment by keyonghan** [comment]
Thanks @fkorotkov for the update.
Seem tasks are resuming https://github.com/flutter/flutter/pull/112218.

**Comment by fkorotkov** [comment]
And FYI GitHub finally acknowledged the issue https://www.githubstatus.com/incidents/2n0tnk7tt6q9?utm_ts=1663875865

**Comment by keyonghan** [comment]
Closing as issue resolved.
