### ISSUE TITLE
Consult the PlatformView implementation for Android

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#112156]
About the implementation of Android PlatformView, I have two questions: 

- Hybrid Composition used ImageReader to render the Flutter page, can we  just replace FlutterImageView with FlutterTextureView directly?  why not?

- TLHC improved platform views performance, does that mean only improved performance on Android < 10 ? How about on Android >= 10?

related issue: https://github.com/flutter/flutter/issues/107313
cc @stuartmorgan

**Comment by exaby73** [comment]
Hello @wangying3426. Thank you for filing this proposal. Labelling for further insights from the team.

**Comment by stuartmorgan** [comment]
> * Hybrid Composition used ImageReader to render the Flutter page, can we  just replace FlutterImageView with FlutterTextureView directly?  why not?

I'm not sure if this is intended as an information question, or as a change proposal. If the former, the issue tracker isn't really the right place for that discussion; Discord would be a better option. If the latter I would suggest a design document explaining in more detail what the motivation is and how it interacts with previous related work (e.g., https://github.com/flutter/flutter/issues/84742).

> * TLHC improved platform views performance, does that mean only improved performance on Android < 10 ? How about on Android >= 10?

I filed https://github.com/flutter/flutter/issues/112208 to track the need to update the existing documentation about platform views; that will include discussion of performance.

Since I don't think there's anything to track in the issue tracker at this point other than the docs update (which are tracked by the referenced issue), I'm going to close this. If I've misunderstood and there's another bug or feature request here please feel free to re-open.
