### ISSUE TITLE
[Impeller] Implement path based text rendering.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#112213]

**Comment by matthew-carroll** [comment]
@chinmaygarde can you describe the scope of this goal?

I've been working with @slightfoot for some time on custom glyph rendering in Flutter because `Paragraph`s were too heavy for us.

We've explored using standard curves to paint individual glyphs. We've explored pre-painting fonts to textures and then drawing glyphs with `drawAtlas()`. And now we're exploring doing our own tessellation and drawing with `drawVertices()`.

If Flutter is going to bring more granular control to text painting, I'd really like for our use-case to make it on the roadmap, and ensure that we can use any such new Flutter APIs.

**Comment by chinmaygarde** [comment]
This issue doesn't track modifying the existing Flutter APIs in any way. It just that Impeller's text rendering today is extremely rudimentary in that it only uses glyph atlases with glyphs in them rendered at-scale. This works in most cases but is slow or takes up more memory than necessary (especially relative to the benchmark) for extremely large glyphs (when they are zoomed in). This issue along with a related on for SDF based rendering rounds out text rendering strategies necessary for ideal text rending support with Impeller.

**Comment by delfme** [comment]
This might also lead to the fix of the infamous emojis rendering issue #28894

**Comment by chinmaygarde** [comment]
@jonahwilliams implemented this in https://github.com/flutter/engine/pull/41402 to get numbers and also did a comparative study of Skias text rendering strategies. The finding was that that this isn't something that is used today for any point size.

While it's good to know that we could use this approach if we needed to, it doesn't have a current use-case. Closing this as wont-fix and putting the patch in the icebox.

**Comment by jonahwilliams** [comment]
Yes, two important points:

* Tessellation of the geometry across various point sizes was often times more expensive than software rendering of the same text. I don't expect compute shader based tessellation approaches to change this as text paths are often concave or self intersecting in ways that defeat common optimizations.

* generally 4x MSAA is not sufficient anti aliasing for text at any point size, though it was harder to tell if the text was particularly heavy.
