### ISSUE TITLE
Investigate hot reload performance benchmark regression with engine roll f56da86

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#11241]
The engine roll in #11219 very significantly regressed hot reload times:
![screen shot 2017-07-14 at 16 39 06](https://user-images.githubusercontent.com/351029/28234294-fad7511e-68b2-11e7-816a-e335ecf83005.png)

Though it improved hot restart benchmarks:
![screen shot 2017-07-14 at 16 39 35](https://user-images.githubusercontent.com/351029/28234311-0b1021a0-68b3-11e7-9e93-cc358ee8c28c.png)

To reproduce:

```sh
cd dev/devicelab
../../bin/cache/dart-sdk/bin/dart bin/run.dart -t bin/tasks/hot_mode_dev_cycle__benchmark.dart
```

@tvolkert @rmacnak-google

**Comment by tvolkert** [comment]
Commits included in that engine roll:

```
8ba522eea Avoid to freeze the system if hot reloading during debug (#3833)
354d90a95 Add missing virtual methods in PlatformView (#3867)
74d6f6055 Enable text autocorrect on Android with a flag to disable it (#3866)
e385c1b45 [Fuchsia] Pass command line arguments for tracing (#3868)
63bf1d282 a11y: Add SemanticsAction "showOnScreen" (#3856)
a64921e38 Hold the TestRunner's platform view through a shared_ptr (#3870)
79d008ffc Fix engine on iOS (#3871)
9f21bfa9b Fix build, OnHandleReady signature change (#3874)
1db18a40d Revert "Reland "Run Flutter on iOS and Android with color correct Skia (#3826)" (#3878)
f56da86f9 Invert the autocorrect flag (#3875)
```

**Comment by tvolkert** [comment]
In that list, `8ba522eea` directly affects hot reload.

/cc @B3rn475

**Comment by tvolkert** [comment]
@yjbanov for running the devicelab tests locally and for how we're collecting the data in the relevant benchmarks.

**Comment by B3rn475** [comment]
A possible difference introduced by https://github.com/flutter/engine/commit/8ba522eeae35d8c70ada3c7b8e200ca2274f4f95 is that https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L142 will potentially return sooner due to the fact that the RPC invoked inside `refreshViews` https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L776 doesn't synchronize anymore with the UI Thread

**Comment by yjbanov** [comment]
Added repro steps to the issue description.

**Comment by tvolkert** [comment]
@B3rn475 it doesn't look like the call to `refreshViews()` is factored into our benchmark data.

Search [run_hot.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart) for `benchmarkMode` to see how to calculate our benchmark data for reload and restart.

**Comment by B3rn475** [comment]
@tvolkert `refreshViews` is not invoked in between __timer start__ and __timer stop__, but it has a different side effect now.

Due to [this change](https://github.com/flutter/engine/commit/8ba522eeae35d8c70ada3c7b8e200ca2274f4f95#diff-a94514bcac1a44f912829825243144d6L272) `refreshViews` is no more waiting for the UI thread to finalize all of its operations.
I can't be sure that this is the actual difference, but before the change `refreshViews` was ensuring that the UI thread (the one where the Dart Isolate leaves) was idle before starting, now it is not, so potentially we are measuring even the time needed for the isolate to idle.

**Comment by tvolkert** [comment]
@B3rn475 I think I just confirmed your theory.  With [an arbitrary delay of 5 seconds](https://gist.github.com/tvolkert/a0cacec2b3ee6bb1945a70ffc3396223) added immediately after the call to `refreshViews()` in between our full restart and hot reload, the reported hot reload time went from 3.5s to 1.2s on my local device.

@yjbanov can you work with @B3rn475 to make the appropriate adjustments to our benchmarking?

**Comment by yjbanov** [comment]
Sure. How can I help? I'm not familiar with what this benchmark does, but I'm familiar with the benchmark infra, so I can help there.
