### ISSUE TITLE
Ink spread on material button can get stuck on iOS

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#11246]
When using a MaterialButton, it's possible for the ink spread to get stuck when the button press triggers the url launcher and switches to Safari in the middle of the ink painting (see video in zip). When you return, the ink painting remains stuck. It doesn't happen every time but it is easily reproducible.

[ink_stuck.zip](https://github.com/flutter/flutter/files/1151393/ink_stuck.zip)

pubspec.yaml (dependencies)
```yaml
dependencies:
  flutter:
    sdk: flutter
  url_launcher: '^0.4.2+1'
```

Sample code:
```dart
class MyHomePage extends StatefulWidget {
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {

  Widget build(BuildContext context) {
    return new Material(
        child: new Center(
          child: new MaterialButton(
            onPressed: () {
              launch('http://www.flutter.io');
            },
            child: new Text(
                'THIS IS A MATERIAL BUTTON WITH LONG TEXT'
            ),
          ),
        ),
    );
  }
}
```

```
☆ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 5756d62931 (2 days ago), 2017-07-14 18:33:20 -0700
    • Engine revision f56da86f98
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • None
```

**Comment by collinjackson** [comment]
@xster might know

**Comment by xster** [comment]
I'll check it out later today

**Comment by xster** [comment]
Can repro on physical device. 
It's peculiar. Even in cases when it happens, there are calls to dispose the InkSplash. The InkSplash's paintFeature is never called again and _RenderInkFeatures is called one more time after with no InkFeatures.

**Comment by xster** [comment]
Not sure what the fix is yet but made some observations. 

Printed the animation state along with the splash to see where it freezes. 
![flutter_01](https://user-images.githubusercontent.com/156888/28347971-2d38fe70-6bef-11e7-9eb7-64825d54976d.png)

There's some differences between the iOS flow and the Android flow. 

iOS:
![fw9jcgyn4x8](https://user-images.githubusercontent.com/156888/28347998-594a6ea4-6bef-11e7-904a-7e6ec5c0e433.png)

Android:
![isxvbdas4l0](https://user-images.githubusercontent.com/156888/28348008-6eb9c99c-6bef-11e7-93de-3cffde59277c.png)

vs the Android flow, the iOS flow:
- iOS's pause lifecycle event is rather delayed and the animation doesn't stop soon after launching the browser. 
- The state it's stuck in is the one frame after the first inactive state. The rest of the canvas draws are lost. 
- The resume event doesn't trigger another frame draw.

**Comment by Hixie** [comment]
cc @cbracken who was looking at this code recently

**Comment by SteveAlexander** [comment]
I'm seeing this issue on an iPhone X when I'm playing with a Material tab bar at the bottom of the screen.

It happens when I'm pressing the tab that is near the "home button line" on an iPhone X. If the app starts to go into the "choose which app I want to have focus" mode while the ink splash effect is painting, it can get stuck.

> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
> [✓] Android Studio (version 2.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [!] VS Code (version 1.24.1)
> [✓] Connected devices (1 available)
> 
> ! Doctor found issues in 1 category.

**Comment by xster** [comment]
cc @HansMuller. Vaguely remember him saying he solved a similar problem in the new gallery app.

**Comment by Hixie** [comment]
Please file new bugs if you still see this. Thanks!
