### ISSUE TITLE
WidgetTester should/could elapse a minimum time span of one frame period when pumping

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1125]

**Comment by abarth** [comment]
You you mean when calling `pump` or when calling `pumpWidget` ?  They both take a duration.  We could change the default duration to 16 milliseconds, for example.

**Comment by apwilson** [comment]
Yeah, I think that's what @Hixie thought would be good/useful.

**Comment by Hixie** [comment]
We should probably advance 1ms (our eventual target frame speed), but have a way to not advance (since many of flutter's own tests expect no advancement).

What I saw when working with Andrew is that he implicitly assumed (reasonably, I think) that calling pump() would advance animations by at least one frame. It was unintuitive that he would have pumped a frame but that nothing would have changed.

**Comment by Hixie** [comment]
This would be an API breaking change at this point. Given that we now have pumpAndSettle which returns the number of frames pumped, it's probably fine to not have this. We could also add a pumpOneFrame callback that does what is described here. Please reopen this bug if you really think this is important.
