### ISSUE TITLE
The team should have consistent access to Firebase Test Lab logs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112566]
For example, when I follow the link to the FTL results in the failure logs of https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/42362/overview, I get a permission denied error.

My understanding is that individuals have been granted access on a case-by-case basis, but this is not scalable.

cc @godofredoc @keyonghan

**Comment by keyonghan** [comment]
I cannot access either. is it expected to be public? If yes, we need to move the bucket to `dash-public` as well.
https://pantheon.corp.google.com/storage/browser/flutter_firebase_testlab_staging;tab=objects?forceOnBucketsSortingFiltering=false&project=flutter-infra-staging&prefix=&forceOnObjectsSortingFiltering=false

**Comment by zanderso** [comment]
Yes, the logs need to at least be visible to the team, and ideally should be public, so that problems surfaced by presubmit failures can be addressed.

**Comment by godofredoc** [comment]
We only host logs and apks built from public sources in that bucket let's migrate it to dash-public. @keyonghan can you please help us sending a PSA?

**Comment by keyonghan** [comment]
> We only host logs and apks built from public sources in that bucket let's migrate it to dash-public. @keyonghan can you please help us sending a PSA?

Sent with a plan at 5:30pm PST today.

**Comment by godofredoc** [comment]
We may also want to enable lifecycle in that bucket to remove old data and speed up the migration.

**Comment by keyonghan** [comment]
Some updates:
1) log is accessible to public
2) firebase console is still hitting permission issue when I tried creating the project `flutter-infra-staging` in firebase. Working with FTL team to triage and fix.

**Comment by keyonghan** [comment]
Now we can view logs via [firebase console](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.f93c781079d437/matrices/6381667296565751891) directly.

The fix is: create the `flutter-infra-staging` project in the firebase console.

Note: [the UI](https://firebase.corp.google.com/) hit permission issue when creating the project, but it went through with[ API explorer](https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects/addFirebase).
More context: b/254529848
