### ISSUE TITLE
Google Maps white screen bug on Android

### ISSUE THREAD

**Issue by mostafa-aziz** [flutter/flutter#112621]
This issue has been driving me crazy. On our app for over a year now, we have had a glitch with google maps on Android. We cannot actively reproduce it, and it happens at completely different and random times, doesn’t matter if the app has been backgrounded or not. The issue is that the whole map sometimes appears as a blank white screen. To fix the issue, you will have to switch between the layers a couple of times and then the map will reappear as normal. We managed to reproduce it with this command once.

`adb shell am send-trim-memory BUNDLEID COMPLETE`

<img width="400" src="https://user-images.githubusercontent.com/58027569/192960268-fb459baa-d13e-472a-aad7-157b578507bd.png">

**Comment by huycozy** [comment]
Hi @mostafa-aziz 
To make the issue clearer, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (on screen that displays the map in order to check if the issue occurs when loading some special element like marker/polyline/circle/map style/etc)
- The output of `flutter doctor -v`
- Which `google_maps_flutter` plugin version are you using? 
- Affected device information if any (model, OS version)

Thank you!

May be related/similar: #64568, #83691
