### ISSUE TITLE
"FBSDKCoreKit-FacebookSDKStrings" requires a development 

### ISSUE THREAD

**Issue by Savdancode** [flutter/flutter#112607]
I got this error when try to open ios folder to run application flutter can anyone help?

**Comment by danagbemava-nc** [comment]
Hi @Savdancode, this was initially reported in https://github.com/flutter/flutter/issues/111475 and has since been fixed. The fix is available on the latest version of flutter stable (3.3.3). 

Kindly upgrade to the latest version of flutter stable and try again. You may need to clear your pub cache. 
You can also use the workaround in https://github.com/flutter/flutter/issues/111475#issuecomment-1249615346

I'll be closing this as this has already been fixed. 

Thank you
