### ISSUE TITLE
Create a reusable widget to let children match height/width of other children

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11270]
Have an easy solution for the equivalent of https://stackoverflow.com/questions/4188859/how-to-get-a-buttons-height-to-match-another-elements-height. 

Possibly create a reusable MultiChildLayoutDelegate wrapper that takes in children wrapped in layout ids from 2 generators, one for children that have opinions about size and one for children that don't have opinions about size. Then do a 2 pass layout, define its own size from children than have sizes then on a second pass, lay out children without sizes to fit in itself.

**Comment by Hixie** [comment]
This would have to be a new RenderBox class like RenderFlex or RenderWrap. Should be relatively easy to do. It's not even two-pass, it's one-pass, just not in tree order.

The question is what should the layout algorithm be, exactly? In particular, what constraints should be passed to the children in the cross axis?

**Comment by xster** [comment]
I think given children tagged with X (wants a size) and Y (match parent's size for one dimension), lay out X with the constraints this container's parent gave it (I imagine that's what row and columns do too). Find the max cross axis length of X, then lay out and position everything left in order giving a specific cross axis min and max length to group Y.

**Comment by Hixie** [comment]
That's not what row and column do at all. :-)

For example, suppose you're in a Center. You're given constraints 0..screen width, 0..screen height.
You have two children that grow to be as large as possible except if that's infinite in which case they grow to be as small as possible (that's a common behaviour for our widgets).
You now put two of these in this new widget we're building.
Where do you put the second one? The first one will have filled all the space.

**Comment by xster** [comment]
Forgot to specify, that thing can only take children that wants to match sibling dimensions on one axis only. That's restriction exists on Android too.

**Comment by Hixie** [comment]
That doesn't affect the problem I described as far as I can tell.

**Comment by matthew-carroll** [comment]
I ran into a specific version of this problem when working on the CupertinoAlertDialog.  What @xster and I discovered from @Hixie is that this child sizing issue can be resolved via composition.  The composition answer is shown below, and I'm going to close the ticket because no new widgets should be necessary for this result.

The composition answer requires 2 adjustments:

- Wrap your Row with an IntrinsicHeight
- Set your Row's CrossAxisAlignment to "stretch"

```dart
new IntrinsicHeight(
  child: new Row(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [
      new Child1(),
      new Child2(),
      ....
    ],
  ),
);
```

The above composition will make all children of the Row the same height as the tallest child in the Row.  This facilitates, for example, a Row of buttons where all buttons are the same height even when text wraps on a given button.

I didn't try this approach with a Column, but I assume it works exactly the same way.

**Comment by joshmatta** [comment]
Hi @marcglasberg,
I have a similar problem where I would want a widget to match the parent's width but the parent itself takes the size of the children
For example, in Android, I could get similar behavior by
```xml
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/textView2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:text="TextViewTextViewTextView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView" />
</android.support.constraint.ConstraintLayout>
```
The constraint layout width takes the size of the first TextView and the second TextView takes the width of its parent and since its length is more than that of the first TextView it wraps.

The example that you mentioned above, the Row or Column will only take the largest child's height or width respectively and the rest of the widgets match to it.

**Comment by zoechi** [comment]
@joshmatta Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by patelkrunal78** [comment]
Similar To [Make buttons in a row have the same width in flutter](https://icetutor.com/question/make-buttons-in-a-row-have-the-same-width-in-flutter)
