### ISSUE TITLE
[go_router] What's the purpose of the `GoRouter.refresh()` method?

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#112772]
## Reproduction steps

This is not really an issue that has reproduction steps. Please read on :)

## The issue

The doc comment of the [GoRouter.refresh()](https://pub.dev/documentation/go_router/latest/go_router/GoRouter/refresh.html) method isn't very helpful. Also, after CTRL+F-ing the `go_router`'s package codebase, I found that `GoRouter.refresh()` it's not called anywhere.

I expected `GoRouter.refresh()` to be called after `refreshListenable` passed to [GoRouter's constructor](https://pub.dev/documentation/go_router/latest/go_router/GoRouter/GoRouter.html) fires, but it's not the case.

**Expected results:**

If the users of the package are expected to override this method, please provide more documentation. Like, refreshes _what_ route?

If we're not expected to override it, make it private or annotate it appropriately.

As a side note, I find the documentation of this package really bad. There was a website some time ago, but it was taken down and the new website doesn't exist yet.

**Comment by chunhtai** [comment]
I think this is a redundant API, it does the same thing of refreshListenable.notifylisteners. I think we should remove this API to avoid confusing.

**Comment by JifScharp** [comment]
I'm a bit confused @chunhtai, since you're suggesting removing this method, but at the same time, [recommending using this rather than refreshListenable](https://github.com/flutter/flutter/issues/116651#issuecomment-1361716448)?

**Comment by RahmiTufanoglu** [comment]
I am confused too. We need more clarification. @chunhtai

**Comment by chunhtai** [comment]
To answer the original question, the refresh causes the current route to be reparse and redirect. it will almost the same as browser refresh.

The original thought is to deprecate one of GoRouter.refresh or refreshlistenable, because they do the same thing. My previous comments were outdated because I wasn't sure which way we should go.

Up on having more experience after taking over the package. I think they both have they usage, so I think we should keep them both.

Closing this issue
