### ISSUE TITLE
Gif not displaying and Google displayed above Modal after enabling Impeller

### ISSUE THREAD

**Issue by anthonyshittu** [flutter/flutter#112791]
After enabling Impeller for IOS, Gif stopped showing up and Google mobile ads after showing up above Modals

 <key>FLTEnableImpeller</key>
  <true/>

-- OR -- 

Users can enable it by passing --enable-impeller to the flutter run tool command

**Comment by huycozy** [comment]
@anthonyshittu please file separate issues one by one so that we may solve them by the corresponding context.
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this and the output of `flutter doctor -v` as well. Thank you!
