### ISSUE TITLE
Disable Third Party Customer Test Temporarily

### ISSUE THREAD

**Issue by sealesj** [flutter/flutter#112819]
Since this utf-8 issue: https://github.com/flutter/flutter/issues/107590 a fix has landed here https://github.com/flutter/engine/commit/6d0f53a33532b1c5a426776fe52afb178f8a58dd, but in third party customer testing there needs to be an update to implement a new method that was added to `TextInputClient`.

In the meantime, it seems like we might want to disable the failing test until this lands in the third party project 
Example failing output: https://chromium-swarm.appspot.com/task?id=5db71198b5072710

Additional context: https://github.com/superlistapp/super_editor/issues/801

**Comment by dnfield** [comment]
I think I'm missing something here.

The link tot he failed test run is showing that the tester is failing to load tests pretty much across the board, not just for the Super Editor suite.

The failed test run also seems to not have any changes to the path getting loaded from, which is what the linked engine PR/commits are about.

If this test run is really the right one, perhaps we've introduced a bug into flutter_tester?

**Comment by sealesj** [comment]
I am not confident this test is really the right one. I see `Á flutter sdk` in the path of the tests and the super editor suite failure which is why I assumed an update in third party customer testing needed to land (also no more ShaderCompilerException), but I am not sure how to identify whether this is a bug or if the changes aren't properly pulled in from that PR

**Comment by dnfield** [comment]
The logs I'm looking at don't have the accent on the A. https://logs.chromium.org/logs/flutter/led/jseales_google.com/8572f3c6303384522324fd8d0f6559c77750de93bc090f423726e1e19f906fbf/+/u/Customer_testing/customer_testing/test_stdout?format=raw

**Comment by dnfield** [comment]
That log is also showing that something is going wrong with every test - it's failing to load the test file completely. I'm also seeing a stderr log saying something about no such branch "master" but I'm not sure for which repo...:

https://logs.chromium.org/logs/flutter/led/jseales_google.com/8572f3c6303384522324fd8d0f6559c77750de93bc090f423726e1e19f906fbf/+/u/Customer_testing/customer_testing/test_stderr

**Comment by sealesj** [comment]
I don't see the accent at the top of the logs, but in the rest of the logs I do see the accent
<img width="561" alt="Screen Shot 2022-10-03 at 8 17 06 PM" src="https://user-images.githubusercontent.com/103135467/193708122-5a655102-3eba-4e51-99cb-5a51f3194ea5.png">

**Comment by dnfield** [comment]
We need the same fix @jason-simmons landed for impeller in flutter_tester. I'll put up a patch.

**Comment by jason-simmons** [comment]
There are two separate issues:
* flutter_tester is not correctly handling non-ASCII command line arguments on Windows.  This will be fixed by https://github.com/flutter/engine/pull/36590.
* The super_editor tests are failing when run on the current framework head

The super_editor test has been failing for a while because the implementation needs to be updated for some breaking changes to the text input APIs.  But the failure was not noticed because the customer test infrastructure is running the super_editor tests through a script that is not returning an error code.

The latest version of the super_editor scripts does the error check (see https://github.com/superlistapp/super_editor/issues/728).  But the customer tests have not yet rolled forward to that version of the script.

So for now the errors logged by the super_editor test can be ignored.

However, it may make sense to disable the super_editor test in https://github.com/flutter/tests/tree/main/registry so that these logs do not become a distraction.  The test should then be rolled forward and reenabled once https://github.com/superlistapp/super_editor/issues/801 is fixed.
