### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed

### ISSUE THREAD

**Issue by huylx0612** [flutter/flutter#112995]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jeansfirefox741** [comment]
flutter

**Comment by darshankawar** [comment]
Based on the issue title, it seems similar to https://github.com/flutter/flutter/issues/108646.

This issue has already been fixed and the fix is available on latest master, beta and hopefully stable.
If you are not on latest versions of either channel, please upgrade and try again to see the change.
Closing.
