### ISSUE TITLE
pub invocations failing in tech debt and package autoroller shards

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112904]
The engine roll here https://github.com/flutter/flutter/pull/112895

Included a Dart roll here: https://github.com/flutter/engine/pull/36601

Which included a pub roll https://dart.googlesource.com/sdk.git/+/4f4f446e228a0fb67195aa384c843dc1cf21e0bb

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20technical_debt__cost/8557/overview

I'm not sure that the pub roll is the issue, but I'm going to try to get the Engine -> Framework roller going again by reverting the Dart rolls into the Engine.

**Comment by zanderso** [comment]
The Engine -> Framework roll succeeded after the Dart rolls above were reverted.

cc @sigurdm @a-siva

**Comment by jason-simmons** [comment]
The failure happens when running `flutter update-packages --transitive-closure`

This can be fixed by patching https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L412 and moving the `temporaryFlutterSdk?.deleteSync` call to the finally clause.

`flutter update-packages` is creating various packages including a simulated Flutter SDK package.  It then deletes the SDK package and runs `dart __deprecated_pub deps`.

For some reason `__deprecated_pub deps` is now expecting the SDK package contents to be available.  Not sure what specifically changed in pub and whether it was intentional.

**Comment by jason-simmons** [comment]
The change in behavior started with https://dart.googlesource.com/pub/+/b0ba5cc63bcc8c93922e3ea0ee9e303c4b279b5e

The `.dart_tool/package_config.json` file generated by earlier parts of `flutter update-packages` contains references to the fake SDK package path.  So it seems reasonable that later invocations of `pub` could assume that the fake SDK directory still exists.
