### ISSUE TITLE
Material 3 cards don't truly follow Material 3 specs

### ISSUE THREAD

**Issue by guplem** [flutter/flutter#112913]
I am using Material 3 ( #91605 ) and I found that the cards do not have "inner padding" as described in the [material 3 specs](https://m3.material.io/components/cards/specs#038b4a49-3a7f-4fce-be8c-89c1155b4c82) even tough in their Material 3 implementation it says that they have been updated to follow Material 3 specs: #99023.

This is how the card looks (with the content inside)
![image](https://user-images.githubusercontent.com/11029629/193985887-2013aa13-3b95-460b-87dc-0e0e7b80808f.png)

This is how I believe it should look (achieved with a padding widget inside the card):
![image](https://user-images.githubusercontent.com/11029629/193985900-c7f9a8ec-1c40-4f6a-a05d-060bd46d3ab6.png)

In seek of consistency and a proper implementation of Material 3 I do believe spacing/paddings/etc. should be implemented into the widgets themselves facilitating a way to override it if needed.

**Comment by exaby73** [comment]
Hello @guplem. If you check the material 2 `Card` there isn't any default padding on there either. I believe this is because you could have an image that is edge to edge as defined in the material specs (see the sample image in the [layout section](https://m3.material.io/components/cards/specs#038b4a49-3a7f-4fce-be8c-89c1155b4c82)). Closing this as this is intentional. If you disagree, please comment and I can reopen the issue. Thank you.

**Comment by guplem** [comment]
> 

I see why it could be intentional.  
In my opinion, the default behavior should be to have the "default padding" stipulated by the material design 3 specs. 
And, if that padding is not desired, a parameter to set the padding should be used instead to remove it.
If not, I believe that the consistency of Material 3 might be harmed.

**Comment by exaby73** [comment]
@darrenaustin Thoughts on this?
