### ISSUE TITLE
[Impeller] Run existing scenario app tests with impeller enabled as well.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#113057]
Related to https://github.com/flutter/flutter/issues/113056

We're already running some simulator tests on iOS simulators. We should run the same with impeller enabled as well.

@jmagman @cyanglaz @chinmaygarde fyi

**Comment by zanderso** [comment]
Assigning myself to take a quick crack at this.

**Comment by jmagman** [comment]
It's run here:
https://github.com/flutter/engine/blob/main/testing/scenario_app/run_ios_tests.sh#L41.

This looks actually pretty tricky to do both, because we need to set [`FLTEnableImpeller` in the Info.plist](https://github.com/flutter/flutter/wiki/Impeller#ios) but unfortunately property lists don't let you pass in a build setting as a boolean value.  
```
xcodebuild -sdk iphonesimulator ENABLE_IMPELLER=YES
xcodebuild -sdk iphonesimulator ENABLE_IMPELLER=NO
```
Meaning there's no version of this:
```
<key>FLTEnableImpeller</key>
<boolean>$(ENABLE_IMPELLER)</boolean>
```
Only:
```
<key>FLTEnableImpeller</key>
<false/>
```
```
<key>FLTEnableImpeller</key>
<true/>
```

**Comment by jmagman** [comment]
Better idea, have 2 `Info.plist` files and swap them out:
```
xcodebuild -sdk iphonesimulator \
  -scheme Scenarios \
  -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 8' \
  clean test \
  FLUTTER_ENGINE="$FLUTTER_ENGINE"
  INFOPLIST_FILE="Scenarios/Info_Impeller.plist"
```
