### ISSUE TITLE
[In_app_purchases] Need to upgrade to Billing Library 4

### ISSUE THREAD

**Issue by gayoung0316** [flutter/flutter#113012]
I need to upgrade the Billing Library to 4 or higher, but the latest update is not possible because the current flutter version of my project is 1.20.4. Is there any way to update Billing Library to 4+ without flutter version update?

**Comment by iapicca** [comment]
In_app_purchases  Billing Library 4 has an open issue https://github.com/flutter/flutter/issues/107370 (see also https://github.com/flutter/flutter/issues/111261)

but [1.20.4](https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_1.20.4-stable.zip) latest compatible In_app_purchases is [0.3.5](https://pub.dev/packages/in_app_purchase/versions/0.3.5+1)

IMHO the choice is 
either fork In_app_purchases pre-null-safety and manually port it to Billing Library 4 
or start porting your app to flutter 3.3.X and wait for the issue to be addressed

**Comment by danagbemava-nc** [comment]
The `in_app_purchase` plugin is already using play billing library 5.0.  #107370 seems to requesting that some fields be used rather than update to play billing 4. 

https://pub.dev/packages/in_app_purchase_android/changelog#023
https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L56

@gayoung0316 as pointed out above, you either need to update your flutter version and your product to the latest version of flutter so you can use the new library or create a fork of the library and do that yourself. 

In light of the above, I'll be closing this as this is not a flutter issue. 

Thank you.
