### ISSUE TITLE
Xcode 14 error build: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by 995996812** [flutter/flutter#113158]
Project opened in xcode14, compilation error.
![1665223934268](https://user-images.githubusercontent.com/16166156/194702586-613ea172-7794-45e0-b902-a018dfa2f0b1.jpg)
flutter doctor -v , check results are as follows
![1665224015088](https://user-images.githubusercontent.com/16166156/194702628-0f8870af-db29-46c9-b98c-91deb57966a6.jpg)

**Comment by globemediaofficial** [comment]
I’m getting the same error.

**Comment by 995996812** [comment]
> I’m getting the same error.

Modify undefined and invalid code for flutter based on compile error messages

**Comment by darshankawar** [comment]
@995996812 
Looking at the logs, it seems to be occuring due to null safety. You are on very old version of stable, 2.0.3. Current version is 3.3.4. I suggest you to upgrade to latest which also contains null safety migration so this error would go away.

Closing for now. Also, when you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with and please avoid posting screenshots, instead use properly formatted text.

**Comment by 995996812** [comment]
Thank you for your reply, I updated it with the latest version and fixed some coding errors. The probelm has been solved.
