### ISSUE TITLE
Flutter Web Hot Reload Error - Service Worker Not Supported

### ISSUE THREAD

**Issue by billyinferno** [flutter/flutter#113145]
## Steps to Reproduce

1. Create flutter project
2. Run as web
3. Perform changes on the source and press save to hot reload

**Expected results:**
1. Web browser reloaded with the updated code

**Actual results:**
1. Web browser keep loading and when press it showed debug
2. Error on console showed as Service Worker Not Supported
3. Tested both on Chrome and Edge

Attached is the example code being used.
[expansion_list.zip](https://github.com/flutter/flutter/files/9738485/expansion_list.zip)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.22000.1042], locale en-SG)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

![service_worker_not_supported](https://user-images.githubusercontent.com/20193342/194690848-9f529365-db23-492d-a97f-8466b8376bb3.png)

**Comment by exaby73** [comment]
Hello @billyinferno. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by exaby73** [comment]
Hello @billyinferno. I cannot reproduce this issue with the code sample you provided. The service worker is being registered properly and hot reload/restart is working as expected. Tested on master. Could you confirm if this issue is still persistent on master?

**Comment by billyinferno** [comment]
I notice on my old project that working fine, the index.html script for the service worker is bit different with the current/new one.

***Old Script***
```
  <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>
```

**New script***
```
  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
```

Now it seems that all is loaded from flutter.js, instead the old one flutter_service_worker.js,

**Comment by exaby73** [comment]
Does using the new script solve your issue? If so, this issue can be closed

**Comment by billyinferno** [comment]
No, the new script is the one who causing error, the old script (create with older version of flutter) is working without any problem.

**Comment by exaby73** [comment]
Can you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in the form of a public repo so that I may verify the issue?

**Comment by billyinferno** [comment]
After checking probably this is due the args put on the launch.json on VS Code, when put args --web-hostname, the error showed, but when remove it load without any problem.

This probably due the Chrome problem that for Service Worker it would need server on HTTPS instead of HTTP except for localhost.

My suggestion you can try to add --web-hostname arguments on the launch.json like below:

``
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "expansion_list",
            "request": "launch",
            "type": "dart",
            "args": [
                //"--web-port=56565",
                "--web-hostname=192.168.1.73"
            ],
        },
        {
            "name": "expansion_list (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile",
            "args": [
                //"--web-port=56565",
                "--web-hostname=192.168.1.73"
            ],
        }
    ]
}
``

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. Adding the `--web-hostname` to your private IP e.g `192.168.0.100` causes this error.

<details>
<summary>Error logs (from Chrome devtools)</summary>

```
flutter.js:282 Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:66:11)
    at FlutterLoader.loadEntrypoint (flutter.js:280:33)
    at (index):46:23
```

</details>

Possibly related issue:

- https://github.com/flutter/flutter/issues/109771

**Comment by ditman** [comment]
I think the core issue here is that:

Workers **require** a Secure Context ([Documentation](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)). TL;DR: the worker will only be available in **`https://...` or `http://localhost`**. Setting the `--web-hostname=192.x.x.x` in the startup arguments _definitely_ sets the server in a non-secure context. The error is thrown [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L77) (because `window.serviceWorker` is probably `null`).

QQ for the thread:

* **Is this issue preventing the Flutter web app from Starting / Hot Restarting (white screen after the reload)?** Or is this just logging a warning to the console? (working [as intended](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L291-L294), looks like the OP is triggering their breakpoint before flutter.js has time to handle the rejected promise?)

**Comment by exaby73** [comment]
@ditman This does not prevent the app from running or hot restarting. Is this expected behavior? Is there a workaround?

**Comment by ditman** [comment]
Final question @exaby73 @billyinferno can you share a screenshot of what you see in your development consoles? If the "error" looks like a `console.warn`, it is intended behavior, surfacing an error coming from the browser, and explaining *why* the service worker couldn't be loaded.

(IIRC, the older version of the code was silently swallowing that error)

**Comment by billyinferno** [comment]
I didn't see the console log, later back home, I'll look and capture the console log.

But the behaviour where browser suddenly in debug mode is makes not clear whether there are bug on the code or else.

Why the new code not also consume the warn just like the old one?

**Comment by billyinferno** [comment]
Hi @ditman,

I tried and when first run the console showed Warning as bellow:
<img src="https://user-images.githubusercontent.com/20193342/197096183-baf15a98-60be-4287-be24-5637408a1848.png" width="600" />

When I do Hot Reload it goes to debug, and as you can see on the top right, it showed Error, instead of Warning.
I think this is the cause of the problem, that it was throwing Error Exception, instead just Warning.
<img src="https://user-images.githubusercontent.com/20193342/197096306-2469723e-39c1-4847-b845-9aafbd6e7bf8.png" width="600" />

**Comment by ditman** [comment]
I tested this, and I can confirm this is expected behavior.

1. You need to enable "Pause on exceptions" on (my) browser for it to stop at the "Rejected promise" stage, when in "Not Secure" mode:

<img width="1312" alt="Screen Shot 2022-10-21 at 2 41 35 PM" src="https://user-images.githubusercontent.com/1255594/197293273-d8b4c506-67ba-4ccf-b221-b71e6e300f74.png">

2. That code is working as expected. Service workers are **not supported** in "Not Secure" mode, so an exception is thrown. That exception is caught a few lines down, and rendered as a warning to the console. This is to let developers know that there's a problem with the Service worker, however the app will continue loading normally.

<img width="1312" alt="Screen Shot 2022-10-21 at 2 41 56 PM" src="https://user-images.githubusercontent.com/1255594/197294008-0e7893e5-1d9f-4976-b60c-0a80112d9ff3.png">

3. I checked your `index.html` ([from here](https://github.com/flutter/flutter/issues/113145#issue-1401831482)), and hot reload should be fine. Note that on Flutter Hot Reload only the `onEntrypointLoaded` method is re-run, and **nothing** that has to do with the service worker is done there (that happens in the `loadEntrypoint` method.)

There was a point in time when Hot Reload was broken when mixing old index.html code with new-ish flutter.js, but that's been fixed. **Make sure your flutter web version contains this commit: https://github.com/flutter/flutter/commit/9cb9f6bca444db15aaa7bf660c7aad5f1f39ada9**
(3.4.0-17.2.pre might be a little old! try the `master` channel, please!)

**Comment by billyinferno** [comment]
Hi @ditman ,
Yes, I can still continue the hot reload if start the pause on debugger.

I'll try master channel and let you know. Thanks.
