### ISSUE TITLE
[Impeller] Implement two-point conical gradient

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#113110]
This is specified in Flutter by providing a focal point argument to the Gradient.radial constructor. Skia has a description for their implementation algorithm here: https://skia.org/docs/dev/design/conical/ 

Right now I think we ignore the focal argument and just draw a radial gradient.

**Comment by chinmaygarde** [comment]
Good catch. For some reason, in go/impeller-whats-left, there is a note saying this wasn't exposed by Flutter.

**Comment by chinmaygarde** [comment]
cc @gaaclarke

**Comment by gaaclarke** [comment]
Reproduction code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class Sky extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final Rect rect = Offset.zero & size;
    const RadialGradient gradient = RadialGradient(
      center: Alignment(0.0, 0.0),
      radius: 0.5,
      colors: <Color>[Color(0xFFFFFF00), Color(0xFF0099FF)],
      focal: Alignment(-0.5, 0),
      focalRadius: 0.0,
    );
    canvas.drawRect(
      rect,
      Paint()..shader = gradient.createShader(rect),
    );
  }
  @override
  bool shouldRepaint(Sky oldDelegate) => false;
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.primary,
        title: const Text('Radial Gradient'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CustomPaint(painter: Sky(), size: const Size(300, 300),),
          ],
        ),
      ),
    );
  }
}
```

Skia:
<img width="303" alt="Screenshot 2023-03-08 at 3 58 15 PM" src="https://user-images.githubusercontent.com/30870216/223880106-950ef904-97f2-4c66-ad7b-c2c63d803cb0.png">

impeller:
<img width="305" alt="Screenshot 2023-03-08 at 3 59 17 PM" src="https://user-images.githubusercontent.com/30870216/223880278-bcb92939-2146-42cf-b8ca-940c7dcf15cf.png">

Here is where the radial gradient is rendered in impeller:
https://github.com/gaaclarke/engine/blob/1d81f77b2bbb79828742a3975351e5488cfb9f1a/impeller/entity/contents/radial_gradient_contents.cc#L48

Here is one of the fragment shaders (there are 2, ssbo and otherwise):
https://github.com/gaaclarke/engine/blob/wide-gamut-ui-image/impeller/entity/shaders/radial_gradient_fill.frag

**Comment by gaaclarke** [comment]
Here is the skia code, they split this out into its own file, which we should probably do, too, to avoid doing the detection of the 2 points inside of the shader: https://skia.googlesource.com/skia.git/+/refs/heads/main/src/shaders/gradients/SkTwoPointConicalGradient.cpp

The document at the top documents the new algorithm that skia is using for the two point conical gradient.  It also mentions a slower version which might be more simple to implement.  I looked through the decade of changes to see if I saw the simple implementation but didn't see it.

**Comment by gaaclarke** [comment]
Here is my first stab at adapting the algorithm from the paper.  My calculation for t always returns 0.0 right now.  I'll start trying to debug it tomorrow: https://gist.github.com/gaaclarke/bd7fd4b95c6cc90a1f9042e17c6e996d

**Comment by gaaclarke** [comment]
I tried to implement what was written in skia's paper but it didn't work.  I looked over the transcription a dozen times and I just suspect there is an error in the paper.  Here is my attempt at transcription: https://www.shadertoy.com/view/msVGW1

Since that didn't work I implemented the naive (slower) solution: https://www.shadertoy.com/view/DdGGDW
