### ISSUE TITLE
Camera flash

### ISSUE THREAD

**Issue by avinashMobile** [flutter/flutter#113149]
## Steps to Reproduce
When device dont have flash specially in case of IOS , Ipad and open camera 

**Actual results:** <CameraException(setFlashModeFailed, Device does not have flash capabilities)>

<details>
<summary>Code sample</summary>

</details>

<details>
  <summary>CameraException(setFlashModeFailed, Device does not have flash capabilities)</summary>

unable to capture image in this scenario and on capture it do nothing just keep showing the camera view 
</details>

**Comment by huycozy** [comment]
@avinashMobile 
Which camera are you testing (front or back camera)? And which device are you having this issue (model, iOS version)? Does flash work well with device's camera app?

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!
