### ISSUE TITLE
Please do something with android-sdk installation issues

### ISSUE THREAD

**Issue by BenceBakos** [flutter/flutter#113175]
## Use case
[arch] [command-line] [NOT android studio]
I would love to do 
```
yay -S flutter
```
And just being abel to use emulators out of the box, but instead, I have to fight errors like
```
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/opt/android-sdk]!
```
```
PANIC: Cannot find AVD system path. Please define ANDROID_SDK_ROOT
```

And similar issues with JAVA_HOME.
Obvious permission and jdk version mess-up on my computer.
But it is a clean installation of flutter, android-sdk, according to the great book.

Countless resources to make the whole setup working...
https://stackoverflow.com/questions/52573901/flutter-command-line-emulator-device-not-found
https://stackoverflow.com/questions/39645178/panic-broken-avd-system-path-check-your-android-sdk-root-value
https://www.rockyourcode.com/how-to-get-flutter-and-android-working-on-arch-linux/
https://gist.github.com/mrk-han/66ac1a724456cadf1c93f4218c6060ae

At lest 30% of my time doing android development is about troubleshooting emulators to be abel to make some screenshots for tablet or being abel to make an apk...

## Proposal

Just include everything to be abel to use flutter as a fully functional tool for android development.
avdmanager, and others cli tools are a pain to use and set up.

## My quick soultion
In the end, I think I will use docker to achive my goals with something like
https://github.com/matsp/docker-flutter
to avoid this hassle all together.

**Comment by exaby73** [comment]
Hello @BenceBakos. Flutter uses the Android SDK (usually installed via Android Studio) for Android development. It's not possible to include all that in an installation of Flutter since if you need to configure anther AVD, you'd do it from Android Studio or to manage the installed SDKs too. If you want to install the command line tools only, you can download that separately from https://developer.android.com/studio.

If you are having troubles getting the installation working, please follow the official guide for [installing on linux](https://docs.flutter.dev/get-started/install/linux). Closing this issue as this is working as expected. Thank you.
