### ISSUE TITLE
FlutterDriver.waitForAbsent() never completing

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11327]
#### Problem

Tried to use this inside Google today, and getting incorrect behavior:

```dart
await driver.waitForAbsent(find.text('foo'), timeout: const Duration(seconds: 20));
```

* If I call that, the future never completes, and the test fails with a timeout exception after 20 seconds.
* If I *first* await a delayed future of 5 seconds to let the Snackbar that holds the text go away, *then* run the `await` above, then the future completes just fine, and the test succeeds.

#### Analysis

The future is never completing because of an error during this call in `extension.dart`:
```dart
await _waitUntilFrame(() => !finder.precache());
```

The error is:
```
'package:flutter_test/src/finders.dart': Failed assertion: line 269: '_cachedResult == null': is not true.
```

It seems weird that it's causing the future to never complete rather than completing with an error...

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by tvolkert** [comment]
I think I have a fix.  `precache()` assumes that it's not called multiple times in a row if it returns true, so we can just change `waitFor()` and `waitForAbsent()` to call `finder.evaluate().is(Not)Empty`

**Comment by Hixie** [comment]
This patch landed around the same time as we changed devices, and it had an odd impact on the numbers, mostly making them much less noisy. I think this makes sense given the fix, but I'd be curious to see if removing this patch also reverts the change, or if it's actually all about the hardware change. I suspect it may be all hardware since little changed on iOS over the same time period.
