### ISSUE TITLE
Impeller failing on iOS simulator

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#113358]
The failure is appearing in the new scenario tests on simulator on intel mac that have Impeller enabled:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/8237/overview

unfortunately, the failure is not causing the tests to fail. That is a separate issue.

Locally, I am also seeing the failure on an iOS simulator running iOS 15.4 on an arm64 mac. The screen is blank and the logs contain several messages like:

```
[VERBOSE-2:validation.cc(27)] Could not create render pipeline: Function solid_fill_fragment_main is using language version 3.0 which is incompatible with this OS.
```

Marking P2 since this will prevent enabling Impeller for `customer: chalk`.

**Comment by dnfield** [comment]
I am not seeing this failure on an iOS simulator using 16.1 on an arm M1.

**Comment by chinmaygarde** [comment]
My hunch is that we are missing a flag to specify the minimum simulator version [like we do on iOS actual](https://github.com/flutter/engine/blob/453a60f06a594834f15281cb4f29632075bb59cc/impeller/tools/build_metal_library.py#L110). Perhaps, it could also be that we need to compile the shaders for Mac when targeting the simulator? I am going to see what Xcode does by default with its examples when targeting the simulator and playing with deployment targets.

Since this issue is susceptible to the host macOS version (due to Metal passthrough), it would also be extremely helpful if anyone who runs into this to also dump their macOS versions.

**Comment by jmagman** [comment]
> My hunch is that we are missing a flag to specify the minimum simulator version [like we do on iOS actual](https://github.com/flutter/engine/blob/453a60f06a594834f15281cb4f29632075bb59cc/impeller/tools/build_metal_library.py#L110). 

If thst's the issue, the sim equivalent would be:
```
'-miphonesimulator-version-min=11.0',
```
`ios-version-min` should also be 11.

**Comment by chinmaygarde** [comment]
I have a patch but I don't have any existing devices with me where this was failing. I'm going to submit a patch anyway. We also don't know how to make this fail on CI yet.

**Comment by zanderso** [comment]
Adding `'-miphonesimulator-version-min=11.0',` fixes the issue for me locally.
