### ISSUE TITLE
Depth map metadata is lost

### ISSUE THREAD

**Issue by jamesleetu** [flutter/flutter#113420]
Hi,

I am using image_picker 0.8.6 right now and requesting full metadata.
Every metadata is shown but depth map information is not showing.

I took a photo with iPhone 12 Pro Max with Portrait mode and there is depth map metadata when I checked with exiftool...
Whenever I use image_picker, only the depth map info is lost.

I really need some help and will be grateful to get help thank you

**Comment by huycozy** [comment]
@jamesleetu, 
Please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!

**Comment by jamesleetu** [comment]
Here is my flutter doctor -v
<img width="1043" alt="스크린샷 2022-10-19 오전 8 56 11" src="https://user-images.githubusercontent.com/67309824/196566415-4a46804f-4b6f-47aa-92f8-5808904e1de8.png">


First Image Contains MP Image data which stands for Depth Information but the second one doesn't
I got the first Image direct from my phone using airdrop and the second one, I got it through the server. (I used the same image as the first one)

First Image

<img width="848" alt="스크린샷 2022-10-19 오전 8 59 57" src="https://user-images.githubusercontent.com/67309824/196566775-a12369f2-1a94-431e-b83f-d03a1d3be9b9.png">


Second Image

<img width="844" alt="스크린샷 2022-10-19 오전 8 58 54" src="https://user-images.githubusercontent.com/67309824/196566660-7d17f88b-d1b4-49d9-9909-ca731beef9a8.png">

**Comment by huycozy** [comment]
@jamesleetu 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample so that we may verify it.

Also, please provide `Reproduction steps` as well. Thanks!

**Comment by jamesleetu** [comment]
```dart
final List<XFile>? images = await _picker.pickMultiImage(
      requestFullMetadata: true,
    );
    if (images != null) {
      setState(() {
        _pickedImgs = images;
      });
    }
```

This is the way I get my image from gallery using image_picker ^0.8.6.
I set the requestedFullMetadata to true but result is above, MP Image (depth map data) is missing.

**Comment by huycozy** [comment]
Hi @jamesleetu 
Please provide `Reproduction steps` in detail so that we may verify this:

- Which `exif` package are you using to check metadata? 
In case you are using an external tool, please provide it (download source, steps to check metadata with tool).

>I got it through the server.
- Can you provide the steps to pick images with source from server?

**Comment by jamesleetu** [comment]
I didn't use exif package.

I used ExifTool Reader in AppStore
[https://apps.apple.com/kr/app/exiftool-reader/id1636199770?mt=12](url)
Dropped Image and checked the metadata.

[imageSource.zip](https://github.com/flutter/flutter/files/9825782/imageSource.zip)

In case, I zipped the original image and result image.

The way I picked my Image

1. Picked Image using `image_picker ^0.8.6`
2. Sent image through `dio ^4.0.4`
3. We are using Spring boot for our backend
4. Downloaded the image that is uploaded in out server

```dart
var response = await dio.post(
        '${Constants.backApiURL}/app/upload/photos',
        data: formData,
        options: Options(
          headers: {
            "Authorization": "Bearer ${Constants.accessToken}",
          },
          responseType: ResponseType.json,
        ),
        onSendProgress: (int sent, int total) {
          if (mounted) {
            setState(() {
              Constants.progress = ((sent / total) * 100).ceil();
              print('progress: ${(Constants.progress)} ($sent/$total)');
              streamController.add(Constants.progress);
            });
          }
        },
      );
```

Sorry for lack information. Thank you

**Comment by huycozy** [comment]
@jamesleetu Thank for providing more information. 

I took a look your images in `imageSource`, they are different as I see (also about the image size)

| sourceImage | result |
| --------------- | --------------- |
<img width="300" src="https://user-images.githubusercontent.com/104349824/196850886-2275de5c-7a87-48f3-a622-71ba005bfcc5.jpg"> | <img width="300" src="https://user-images.githubusercontent.com/104349824/196850865-1c2afad3-58f8-4d8d-8fe4-1fcfe0a6d89b.jpeg">

I'm not sure if you make any changes to the images on the backend side or not (this is an issue outside of Flutter). You may need to check this again from backend. 

Therefore, please provide the reproduction steps only after picking the image and comparing the output/picked image with the original image to see if the metadata is lost.

**Comment by jamesleetu** [comment]
@huycozy Sorry for my mistake :(

My files were unorganized, sorry about that.

Here is the input and output image

[imageSource.zip](https://github.com/flutter/flutter/files/9826318/imageSource.zip)

Again, sorry for the confusion

**Comment by huycozy** [comment]
@jamesleetu No worries about the images. 

As mentioned above at https://github.com/flutter/flutter/issues/113420#issuecomment-1284885354, we can not verify your backend side. So, you need to compare the output/picked image with the original image to see if the metadata is lost.

In case you can confirm the output/picked image's metadata is lost, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify the issue is coming from `image_picker` plugin.
