### ISSUE TITLE
`Linux docs_publish` is timing out after an hour

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113451]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish/7139
Nothing interesting in the logs, not sure why it's so slow:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800313004963416017/+/u/Docs/docs/test_stdout

Looks like it's about to time out again: https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish/7140

Tree is closed.

**Comment by jmagman** [comment]
@drewroengoogle on-call

**Comment by CaseyHillers** [comment]
We should extend the timeout from 60 minutes to 75 minutes. Looking at the historical trends, this builder's duration has crept up as the codebase has increased.

However, https://cs.opensource.google/flutter/recipes/+/6d4a70a92653c57b842c69301873d29be7cc5d7d recently landed which explicitly added a bit more work on CI to make packaging releases quicker.

**Comment by CaseyHillers** [comment]
@gspencergoog would building the docs on a more performant bot help? We could re-use some of the engine vms for this target.

**Comment by drewroengoogle** [comment]
@CaseyHillers Was the timeout already increased? The most recent build ran a built longer and `Linux docs_publish` passed.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/flutter/blob/master/.ci.yaml#L258 is still 60, and I believe https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/adhoc_validation/api.py may need to also be updated to have a longer timeout

**Comment by jmagman** [comment]
Is there any way to shard this?  I believe it's the longest-running builder.

**Comment by drewroengoogle** [comment]
https://flutter-review.googlesource.com/c/recipes/+/34820 may be a temporary fix until a long-term solution is implemented (increasing the timeout to 75 mins).

**Comment by gspencergoog** [comment]
This is docs publish, not building the actual docs, right?  If so, I _think_ that most of the time is spent talking to Firebase to upload/store/configure the docs, and a more performant builder wouldn't help. (I haven't actually benchmarked it though, so I could be wrong about the details here.)

**Comment by gspencergoog** [comment]
Actually, looking at the logs, this isn't just doing publish, it is actually building the docs too (running dartdoc).  In that case, it would probably benefit from more CPUs.  The tool execution for the samples is automatically parallelized to the number of CPUs, which is about 10-20% of the build time in dartdoc.

It can't easily be sharded (which is why it hasn't been), since the steps are dependent upon each other. We can't publish to Firebase or zip up the offline docs without having access to the output of the dartdoc run, for instance.  It is probably possible, but would require having dependent shards, and caching of results between shards, and while each shard's execution might be shorter, the overall time would be the same or more. We could perhaps do the postprocess operations (publishing to Firebase and zipping the offline docs) in parallel then, however.

**Comment by jmagman** [comment]
It passed at 65 minutes, lowering priority.
https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish/7140

**Comment by drewroengoogle** [comment]
Following up on this - Is additional work needed for this issue or can this be closed?

**Comment by CaseyHillers** [comment]
With the timeout increases and the higher CPU machine, the builders are averaging a 58 min runtime (versus the 75 min timeout). https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish

This can be marked as fixed, but we should look into ways to optimize this.

@gspencergoog do you think we could put all the source code on an in memory filesystem, and have dartdoc run against it?

**Comment by gspencergoog** [comment]
We could try that and see how much it helps. I do think that this is probably I/O bound, not CPU bound, for most of its tasks.
