### ISSUE TITLE
[go_router] Option to stack routes onto a ShellRoute

### ISSUE THREAD

**Issue by saibotma** [flutter/flutter#113496]
## Use case

Sometimes it is necessary to display a page based on a `PopupRoute` onto a go_router `ShellRoute`. This is useful for dialogs with a (partly) transparent background, so that the content of the `ShellRoute` below should be visible. For example, in the screenshot below the blue rect is the dialog, and below it is a green “sidebar” with red “nested” content.

![Screenshot 2022-10-16 at 12 33 51](https://user-images.githubusercontent.com/26022902/196030650-aa11c8cd-cec3-4834-9cf5-f041c575f419.png)

As far as I'm concerned, this is not possible with go_router at the moment, because all routes passed to the `routes` parameter of shell route will be passed to the `child` parameter of the `builder` function.

## Proposal

Make it possible to stack routes on `ShellRoute`.

**Comment by chunhtai** [comment]
are you looking at imperative push or declarative route on the shellroute.

For declarative, the subroute under the shellroute will be stack on the shellroute by default.

For imperative push, you can use showDialog(useRootNavigator: false, context: shellRouteNavKey.currentContext!, builder: ...);

I will close this as since there is already a way to do this.

**Comment by saibotma** [comment]
Would be great if you could share an example for the declarative approach.
