### ISSUE TITLE
Xcode warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs

### ISSUE THREAD

**Issue by waleedzakria** [flutter/flutter#113479]
Failed to package /Users/projects.maahey/wependioapp.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from
    project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output
    dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from
    project 'Runner')

Everything is good including flutter doctor. The error is occuring even in new apps.

**Comment by huycozy** [comment]
@waleedzakria 
I see your comment at #113445. It looks like you are archiving ipa file, right? If so, please take a look at this issue https://github.com/flutter/flutter/issues/113260 to see if it can help.

If the issue is not related to obfuscated command, check this SO answers: https://stackoverflow.com/questions/71201656/flutter-failed-to-build-ios-app-archive-failed-encountered-error-while-archi
