### ISSUE TITLE
Window object should list two of physical size, logical size, and device pixel ratio (to avoid rounding errors)

### ISSUE THREAD

**Issue by j9brown** [flutter/flutter#11362]
## Desired Change

Move the conversion between logical to physical coordinates into the Flutter Engine instead of doing it in RenderView.  In particular, let the Flutter Engine be responsible for applying the root transformation based on its awareness of the needed metrics.

In other words, delete RenderView.applyPaintTransform() and similar functions, moving their logic out of Dart code and into the Flutter Engine.

## Background

Window, RenderView, and ViewConfiguration act as the glue between the physical coordinate system of the platform's window system and the logical coordinate system of Flutter's widget tree.

This arrangement is sensible enough.  On most platforms, the window system expects applications such as Flutter to produce content of a specific physical size to fill the window independently of how they model their content internally.  Flutter applies this transformation at the root of the render tree.

However, on Fuchsia with Mozart v2, the window system does not work in physical coordinates anymore.  The world consists of geometric elements (shapes) which can be drawn at any scale with various materials (including textures).  The problem isn't to produce a certain number of pixels but rather to produce geometry which fits a given logical region of space.

So the window's physical size isn't really relevant anymore.  However, we do need to produce textures at a sufficient resolution so they look good, taking into account the display density and the projection matrix of the textured elements.

Mozart v2 supports this via a "Metrics Event" API which informs Flutter about the scale factor which will be applied to its part of the scene.  It's a bit like having a "level of detail" hint.  These metrics are ultimately applied by the Flutter Engine's SceneUpdateContext to determine the resolution of the textures to be rendered.

Unfortunately, Flutter has already pre-scaled its content by the devicePixelRatio by the time this happens, so the Flutter Engine has to undo the transformation layer before applying the metrics.

It would be nice if we hadn't applied this transformation in the first place and just let the Flutter Engine take care of it since it knows best how the metrics will change moment to moment.

## Further Discussion

My current thinking is that devicePixelRatio is a nice hint which applications can use to load their assets at a usable resolution for times when the application is situated at the normal focal plane.

When the application is not in focus, it may be pushed away from the camera and scaled down.  The Mozart metrics provide more accurate information about the minimum resolution at which textures must be rendered for good fidelity.  In particular, we can render fewer pixels which saves bandwidth.

In a Flutter app which contains multiple PhysicalModelLayers it's possible for different metrics to apply to each layer (although this behavior is not supported today).

So all told, I think it would be a good idea to move most of the code which deals with physical units into the Flutter Engine.

Thoughts?

**Comment by eseidelGoogle** [comment]
@abarth would know history if @Hixie doesn't.

**Comment by abarth** [comment]
It's @Hixie 's decision, but we evaluated designs like the one you're proposing when we picked the current approach.

One of the challenges with the design you're proposing is that the engine doesn't have enough information to apply changes to the device pixel ratio without input from the framework.  For example, the framework might select different assets depending on the device pixel ratio (e.g., with the appropriate density of pixels in a image) or might change its rendering entirely based on the device pixel ratio (e.g., a visual design that responsive to the available number of pixels).

I'm quite clear what the problem is with the current design.  It seems like a possible implementation of a "Metrics Event" is to inform the framework of the new device pixel ratio and have it produce a new ui.Scene that conforms to that device pixel ratio.  The framework is already designed to respond to changes in the device pixel ratio in this way.

**Comment by abarth** [comment]
In summary, can you explain a bit more about the problem you're trying to solve?

**Comment by j9brown** [comment]
Everything works already and I am able to feed in dynamic changes to the pixel ratio, etc. just fine.

Really this is just a question of how the responsibility for applying transformations should be factored between the flutter framework and the engine.  Specifically, I propose that the root of the layer tree be represented in logical coordinates instead of being scaled by device pixel ratio as it is today.  The engine can be responsible for applying whatever scaling it needs at rendering time.

Likewise inputs coming from the engine can be scaled before being presented to the framework so that it doesn't have to perform its own conversions.

In the end, it would allow me to delete some redundant conversions.

**Comment by abarth** [comment]
Another issue with communicating with the engine in logical coordinates is that you lose some expressive power.  For example, suppose I want to draw the outline of a rectangle that is exactly one physical pixel wide and inset exactly one physical pixel from the boundary.  If the engine speaks logical pixels in floating point and the device pixel ratio is 1 and 1/3, then there's no way for me to specify this command exactly because the width I desire for the outline cannot be represented exactly in floating point.

**Comment by Hixie** [comment]
This is actually more or less how the system used to work, but to address a number of issues (e.g. accessibility having to work in a different coordinate system than pointer events, etc) we've been progressively moving more and more of this logic into the framework, so that an app that doesn't use the framework works entirely in the coordinate system provided by the OS.

> So the window's physical size isn't really relevant anymore. However, we do need to produce textures at a sufficient resolution so they look good, taking into account the display density and the projection matrix of the textured elements.
>
> Mozart v2 supports this via a "Metrics Event" API which informs Flutter about the scale factor which will be applied to its part of the scene. It's a bit like having a "level of detail" hint. These metrics are ultimately applied by the Flutter Engine's SceneUpdateContext to determine the resolution of the textures to be rendered.

How about pushing the metrics events to the framework, e.g. as a varying device pixel ratio? As you zoom a scene out, its dpr drops from 2.0 to 1.9 to 1.8 to 1.7, etc, all the way down to 0.5 or whatever. We could actually do this pretty efficiently since at the framework level that's just tweaking a transform that's then applied to a bunch of prerecorded display lists (obviously we'd lose the rasterisation cache during the animation but that's all as far as I can tell). We would even automatically step down image assets and so forth as it happens. Then the engine doesn't have to do any scaling at all.

> In a Flutter app which contains multiple PhysicalModelLayers it's possible for different metrics to apply to each layer (although this behavior is not supported today).

Parts of the framework already support the idea of having a different device pixel ratio for a different physical layer, we could definitely push further in that direction. I'm not sure I really understand what this means, though. Aren't all the layers drawn on the same screen?

**Comment by mikejurka** [comment]
A primary motivation for all this is rendering performance, so that if we
have multiple apps in the Armadillo timeline, we don't need to render to
textures bigger than we need

My hesitation was the same as Adam's, namely that apps can make
initialization decisions based on pixel ratio. A question so I understand
properly:
"My current thinking is that devicePixelRatio is a nice hint which
applications can use to load their assets at a usable resolution for times
when the application is situated at the normal focal plane."

Does this mean the devicePixelRatio would be static, or would it change
when the scale factor changes? Apps should have access to some notion of a
static device pixel ratio, even if there is another pixel ratio applied at
a given time to an app.

**Comment by j9brown** [comment]
I'm holding off pushing dynamic changes to the display pixel ratio because doing so also affects the window's physical size (due to rounding) even if the window's logical size remained constant the whole time.  Then when the framework re-derives the logical size from the window's physical size, it observes a change (due to rounding) and so performs an undesirable relayout.

It's this conversion I would like to avoid.

That said, I agree that working in logical space makes it problematic to draw in exact pixel units with pixel perfect alignment.  There's not much we can do about this, although we can partially avoid it by choosing a nominal device pixel ratio that is precisely representable as a power of 2 fraction.  e.g. use 21/16 = 1.3125 instead of 4/3 = 1.333...

**Comment by j9brown** [comment]
> Parts of the framework already support the idea of having a different device pixel ratio for a different physical layer, we could definitely push further in that direction. I'm not sure I really understand what this means, though. Aren't all the layers drawn on the same screen?

Even if the layers are drawn on the same screen they may be transformed differently.  For example, if we applied a perspective transformation to the scene, physical layers further from the camera would appear smaller and thus have different metrics.

In truth, Mozart's current definition of metrics is overly simplistic.  It's just a first stab at expressing level of detail.

**Comment by Hixie** [comment]
Can you elaborate on the issue with the window sizes?

**Comment by j9brown** [comment]
Flutter's ViewportMetrics are currently defined like this:

struct ViewportMetrics {
  float device_pixel_ratio = 1.0;
  int32_t physical_width = 0;
  int32_t physical_height = 0;
  int32_t physical_padding_top = 0;
  int32_t physical_padding_right = 0;
  int32_t physical_padding_bottom = 0;
  int32_t physical_padding_left = 0;
};

The Mozart view manager provides the view's dimensions in logical pixels.  So to work with Flutter, the RuntimeHolder takes the logical dimensions, multiplies them by the device pixel ratio, converts the result to an integer, then assigns the value to the ViewportMetrics.

Subsequently the Flutter framework calculates the logical dimensions by taking the physical dimensions, converting to a float, and dividing by the device pixel ratio.  Due to the integer conversion, the logical dimensions which the Flutter framework determines may be slightly different from the value which the Mozart view manager supplied.

So even if the view's logical dimensions haven't changed, the Flutter framework may perceive that they have due to accumulated rounding errors when the scale factor changes.

**Comment by Hixie** [comment]
We could just make physicalWidth and physicalHeight be doubles.

**Comment by j9brown** [comment]
We could, but that's not particularly physical either.  ;)

**Comment by Hixie** [comment]
how so?

**Comment by abarth** [comment]
@Hixie That won't necessarily cause a different device pixel ratio to arrive at precisely the same logical floating point values because floating point math isn't associative.

**Comment by Hixie** [comment]
If I understand correctly, the concern is that Mozart will have a window of 100x100 physical pixels, on a device with a device pixel ratio of 2.0. So it'll internally think it's a window of 50x50 pixels. Then that window will be shrunk down to 50x50 pixels, so it'll update the device pixel ratio to 1.0, giving a new physical size of 50x50.

Except that actually it'll be a window of 171.5x178.5 physical pixels, on a device with a device pixel ratio of 3.5, internally considered a window of 49x51 pixels, which will then shrink down to 30.38x31.62 pixels, with a device pixel ratio of 2.17, and a reported physical dimension of 106.33x110.67, which, when multiplied by 2.17, will be something like 49.00000001x51 (well, not in this case, but hypothetically anyway), so then we'll trigger a layout that we didn't want to trigger since all we wanted to do was adjust the transform.

**Comment by Hixie** [comment]
One option is that the Window structure in dart:ui could contain any two of logical pixels, physical pixels, and a device pixel ratio, so that on platforms with physical pixels + a device pixel ratio (iOS, Android) we'd use that, and on platforms with logical pixels + a device pixel ratio (Fuchsia), we'd use that. The framework could easily handle that.

**Comment by j9brown** [comment]
That would work.  It's worth noting that we perform similar unnecessary
conversions to / from physical coordinates for input events right now.
Mozart has everything in logical coordinates already.

**Comment by tvolkert** [comment]
@Hixie is the discussion above still representative of the current state?

**Comment by Hixie** [comment]
I'm not aware of anything having changed on our side. @schwa423 may know more.

**Comment by kf6gpe** [comment]
Currently have physical size and the device-to-pixel ratio; closing as obsolete. Feel free to re-open if need be.@hixie, WDYT?
