### ISSUE TITLE
[Impeller] Add support for non-struct uniform names for GLES

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#113715]
Currently, only struct member names are supported. This is needed to support uniform bindings for RuntimeEffect.

**Comment by chinmaygarde** [comment]
I believe the `CreateUnifiormMemberKey` member needs to be patched in `buffer_bindings_gles.cc`. Seems simple enough. We can tackle this when we focus on non-Darwin platforms.

**Comment by jason-simmons** [comment]
Note that the `BufferBindingsGLES::BindUniformBuffer` / `CreateUnifiormMemberKey` code path is currently crashing because `RuntimeEffectContents::Render` is passing a local instance of `ShaderMetadata` to `Command::BindResource`.

`Command::BindResource` then captures a pointer to the `ShaderMetadata` in the `Resource`.  That pointer is then used after the `ShaderMetadata` goes out of scope.

(see https://github.com/flutter/engine/blob/main/impeller/entity/contents/runtime_effect_contents.cc#L160)
