### ISSUE TITLE
The Release versions Wiki has wrong versions

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#113726]
The following wiki is creating a new section for each new patch, so version 3.3.5 is not inside version 3.3, but inside version 3.5, which doesn't exist.

https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by darshankawar** [comment]
The latest hot-fix section 3.3.5 now correctly shows under 3.3 changes as below:

https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#flutter-33-changes

I think when you opened this issue, it might be showing that way, but seem to have been fixed since.

Closing. If you disagree, write in comments and I'll reopen it.
