### ISSUE TITLE
[Impeller] RuntimeEffect: Register the shader function earlier

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#113719]
Right now we register the shader inline in `RuntimeEffectContents` on the first frame. We can schedule the shader compilation to happen sooner after the asset is loaded by `FragmentProgram`.

**Comment by jonahwilliams** [comment]
Draft PR that partially does this here: https://github.com/jonahwilliams/engine/pull/new/early_registration though currently this is blocking on the UI thread.

The registration would need to substantially refactored to move this into a worker thread. That said, even with the blocking change there is a delay in showing the shader (Skia or Impeller).

I suspect that we require a framework change to allow the ink_sparkle to get eagerly registered instead of waiting for first use.

**Comment by jonahwilliams** [comment]
Coming back to this - on Android Vulkan, its taking 12ms for the first variant of the ink sparkle shader to be compiled, subsequent variants are much faster. I suspect that whether or not we block on it, we need to at least kick off the initial compilation to be avoid dropping frames.
