### ISSUE TITLE
how to add back button in LaunchMode.inAppWebView in Android

### ISSUE THREAD

**Issue by balaji101010** [flutter/flutter#113994]
When I launch url in `LaunchMode.inAppWebView`. it occupies full screen. is there any way to add backbutton?

**Comment by huycozy** [comment]
Hi @balaji101010 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
