### ISSUE TITLE
Obfuscating / treeshaking app sources

### ISSUE THREAD

**Issue by emesx** [flutter/flutter#11393]
It seems that stacktraces, even in release mode, are not obfuscated.

Would it be possible to add an option to obfuscate them in release mode (while still being able to deobfruscate them given sourcemaps)? 

One step further is source tree shaking - is it supported? Is it on your radar?

**Comment by Hixie** [comment]
Why would one want to obfuscate a stack trace?

Tree shaking should already be happening. If it's not, please file a bug.

**Comment by sethladd** [comment]
cc @rmacnak-google Do we tree-shake in the AOT compiler?

**Comment by emesx** [comment]
@Hixie "security by obscurity" etc.

**Comment by Hixie** [comment]
I don't understand how obfuscating a stack trace gets you any security.

**Comment by emesx** [comment]
Stacktraces might contain information about the app, unreleased features, experiments etc. I don't want to expose this or make it easy to expose. Does it make sense now?

**Comment by Hixie** [comment]
If you don't want people to have access to unreleased features, don't release them. Obfuscating the stack traces isn't a real solution.

**Comment by emesx** [comment]
A/B testing is a partially "unreleased" feature, isn't it? Our legacy apps do source obfuscation. Anyway, I know my requirements and the rationale behind it.

Now, coming back to the actual question: is it supported? If not, is it on the roadmap? Or is this a job for a 3rd party tool?

**Comment by rmacnak-google** [comment]
The AOT compiler does do tree shaking. Tree shaking is conservative: functions and classes it can prove are not used are removed from the program, but the program may include effectively unused functions that are retained because the compiler is unable to prove they are unused, such as code guarded by a non-const flag. The compiler does not obfuscate the names of any functions or classes that are retained.

**Comment by Hixie** [comment]
A/B testing isn't "unreleased" if you're showing A and B to actual customers, presumably.

I believe you can implement stack trace mangling manually if you just catch all the places where stack traces may be emitted (basically, doing the same thing a crash reporter would do). Though I guess if you're doing that you might as well just silence the stack traces rather than mangling them.

Nothing on the topic of mangling is on our roadmap since we believe that this desire is misplaced.

**Comment by harveynick** [comment]
I've worked on apps at Google where this (stack trace mangling) was a requirement, so I'm curious as to why it's not on the road map. It seems like a relatively easy win in terms of not accidentally exposing class names which imply future functionality, or exposing the existing of non-public APIs.

**Comment by Hixie** [comment]
Relying on obfuscation doesn't solve your problem. It is literally, as @emesx said, security by obscurity, which is an antipattern (Wikipedia: "Security experts have rejected this view as far back as 1851").

IMHO you should always act as if your application is open source, because at the end of the day, if the bits are in the user's hands, they'll be able to do whatever they want with them. All you'll be able to do is slow them down a bit, which gives you a false sense of security.

**Comment by emesx** [comment]
@Hixie, none of us is talking about **solving** the general problem in its most generic form. We're talking about the low hanging fruits that get as far enough.

There are reasons why you use labels like _leafy (g3)_, aren't there?

**Comment by Hixie** [comment]
If it was up to me we wouldn't be using code names. But even the code names aren't the same, because those are specifically about unreleased code. Once the code is released, we can talk about it (and could change the codename to be more transparent).

**Comment by eseidelGoogle** [comment]
My vote would be that we close this bug and have a discussion in person. :)

dart minification has existed in the past:
https://groups.google.com/a/dartlang.org/forum/#!topic/misc/zENLPfyrWj0
and certainly could be resurrected in some form.

I suspect it's a wholly separate topic from Flutter, but one we can assist you towards finding if needed.

If after our discussion we intend to build something along these lines into Flutter, I think we should open a new bug with that resolution.

Sound OK?  Happy to continue having on-bug discussion, but I suspect we'll reach agreement faster over VC.  I also I suspect integrating something like this would be much easier inside a Bazel build system (e.g. google internal) rather than via our `flutter build` (default public build system) and thus may belong in an internal bug.
