### ISSUE TITLE
Specify in .ci.yaml to run in presubmit bot not postsubmit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114085]
Currently, in .ci.yaml, you can set a field `presubmit: false`, which causes a configuration to run only in postsubmit. It would also be useful to be able to run a configuration only in presubmit. This would allow us to better tailor presubmit feedback to the specific change. For example, presubmit clang-tidy can suggest fixes on a failure, but in postsubmit that wouldn't make sense.

cc @keyonghan

**Comment by CaseyHillers** [comment]
@zanderso this is possible today

```
  postsubmit: false
```

I recommend not using `postsubmit: false` as it can create an unknown state for the builder. With the way GitHub PRs are structured, a PR can land without running the builder. To work around this, we run all targets on postsubmit as well.

For clang tidy, it sounds like you're interested in a feature where certain targets can have a neutral status (instead of pass/fail).

**Comment by zanderso** [comment]
Since this is already possible, I'll close this issue.
