### ISSUE TITLE
flutter test command needs better error message

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1141]
If you run `flutter test` on a project that doesn't depend on `flutter_test` or hasn't done a `pub get`, you get the error message below. It would be better to just print an error message that the flutter_test package is missing. It's currently difficult to find the root cause because the error messages below do not refer to any files in the `flutter_test` package. (All paths below have been sanitized.)

```
$ flutter test
00:00 +0: loading /.../test/space_usage_test.dart
00:00 +0 -1: ... /.../test/number_accumulator_test.dart
00:00 +0 -1: loading /.../test/space_usage_test.dart                
  Failed to load "/.../test/space_usage_test.dart":
  Aborted while running: /.../test/space_usage_test.dart

  stderr:
  [0108/093344:ERROR:data_pipe_file_utils.cc(233)] Opening file '/.../test/packages/flutter_tools/src/test/remote_listener.dart' failed in CopyFromFileHandler::OpenFile
  [0108/093344:FATAL:dart_library_provider_files.cc(20)] Failed to load /.../test/packages/flutter_tools/src/test/remote_listener.dart
```

**Comment by Hixie** [comment]
That is a very odd message for that condition. I wounder why it's giving that error.

**Comment by abarth** [comment]
We load code from flutter_test during runtime when running the tests.  If you don't have it in your packages, the import will fail.

**Comment by Hixie** [comment]
Sure, but that's not what the error says.

**Comment by jimbeveridge** [comment]
One problem is that the Dart VM does a poor job of displaying import errors. Seth filed a bug in the Dart VM, but it's possible we could fix this in our version of the VM?
In the interim, is it possible to change the ordering of import statements so that we import something from `flutter_test` *before* we import something from `flutter_tools`?

**Comment by abarth** [comment]
> Seth filed a bug in the Dart VM, but it's possible we could fix this in our version of the VM?

We don't have a separate version of the Dart VM.  We just pull from the DartVM git repo at a specific hash.

> In the interim, is it possible to change the ordering of import statements so that we import something from flutter_test before we import something from flutter_tools?

I don't think so.  The flutter_tools import is part of bootstrapping the process.  The system doesn't know that flutter_test exists until later.

We can have the `flutter test` command validate that you have a dependency on `flutter_tools` before trying to run the tests though.

**Comment by Hixie** [comment]
I'm confused about which package it is that's causing the problem here. Is it `flutter_tools` or `flutter_test`? We can definitely make sure the pubspec.yaml and .packages files have `flutter_tools`, that's easy. Checking whether you need to rerun `pub get` because something's out of date, or checking that you have `flutter_test` there (or any other random dependency), are both things that I don't think are really possible to do in any reasonable amount of time.

**Comment by abarth** [comment]
> Is it flutter_tools or flutter_test?

`flutter_tools` is a required dependency for `flutter test` to run tests because `flutter test` loads some code from `flutter_tools` into your test's isolate.  We tell developers to depend on `flutter_test` which in turn depends on `flutter_tools`.

> Checking whether you need to rerun pub get because something's out of date

That shouldn't be a problem if the `flutter` binary and the `flutter_tools` dependency point to the same git repo on disk.  They'll always have consistent versions.  We can validate that the `flutter_tools` dependency points back to a subdirectory of the flutter root for the `flutter` binary.  flutter flutter flutter flutter.

**Comment by Hixie** [comment]
Sure but what if the test depends on some random other package, and the author hasn't run pub get since adding that dependency. Will it fail in a similarly incomprehensible way?

**Comment by abarth** [comment]
Hopefully it will fail in a more comprehensible way because it will complain about code that the author actually wrote instead of this mysterious code that we inject into the test to run it.

**Comment by abarth** [comment]
Fixed.
