### ISSUE TITLE
InteractiveViewer scaling/zooming behavior change from 3.0.5 to 3.3.x

### ISSUE THREAD

**Issue by TomSwift** [flutter/flutter#114257]
My `macos` app uses an `InteractiveViewer`.    

When built with Flutter `3.0.5` I can zoom/scale the viewer content using the mouse scroll wheel.  Using a trackpad I can zoom with a "2-finger vertical-pan" gesture.

When built with a recent Flutter `3.3.x` version I can no longer zoom the content via the mouse.   If I use a trackpad I can zoom using a pinch gesture.

I suspect this change in behavior is related to https://github.com/flutter/flutter/issues/107005, but not sure.   

Are there docs that I'm not finding that describe this change in behavior?

What I want to know is how to zoom the `InteractiveViewer` using the old behavior, on `macos`.   Do I need to do this by capturing the events and programmatically zooming using a `TransformationController`?

## Steps to Reproduce

1. Install Flutter 3.0.5 (`git checkout 3.0.5`, `flutter doctor`)
2. Execute `flutter run` on the code sample 

**Expected and Actual results:** 

Zooming works using the mouse scroll wheel and trackpad 2-finger vertical-pan gesture.

3. Install current Flutter 3.3.x (`flutter channel stable` `flutter upgrade`)
5. Execute `flutter run` on the code sample 

**Expected results:** 

Able to zoom using the mouse scroll wheel and trackpad 2-finger vertical-pan gesture..

**Actual results:** 

Only able to scroll via trackpad pinch gesture.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: InteractiveViewer(
        boundaryMargin: const EdgeInsets.all(double.infinity),
        minScale: 0.1,
        maxScale: 1.6,
        child: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: <Color>[Colors.orange, Colors.red],
              stops: <double>[0.0, 1.0],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by TomSwift** [comment]
Pretty confident it's related to [this](https://github.com/flutter/flutter/issues/112880#issuecomment-1270504869).   [The handler for scroll wheel zooming inside InteractiveViewer ](https://github.com/flutter/flutter/blob/0b451b6dfd6de73ff89d89081c33d0f971db1872/packages/flutter/lib/src/widgets/interactive_viewer.dart#L953)is never invoked.

**Comment by moffatman** [comment]
I guess you are using the Magic Mouse, right? It basically shows up to the system as a trackpad, that would explain why it's panning around the InteractiveViewer instead of zooming. If you want to go back to the old behaviour, that could be possible by capturing the `onPointerPanZoomUpdate` events in ` Listener`, and using the `panDelta` property to programmatically zoom as you suggest.

But then you will lose the new ability to pan around using the trackpad (which is expected and a desired change in behaviour). It would be nice to have the new behaviour on trackpad, and the old one on the Magic Mouse, but upon some cursory research, it is not simple to tell some scrolling is being done by a trackpad or by a Magic Mouse:

- https://developer.blender.org/T28092#97274
- https://github.com/nanoant/solvespace/commit/3c04016bf85293a888c79ac1ded516898835e496
- https://github.com/solvespace/solvespace/commit/cf4defcd474e0a55cfb5970265b3d1f0e99d16b0

**Comment by TomSwift** [comment]
> I guess you are using the Magic Mouse, right? It basically shows up to the system as a trackpad, 

Yeah, I read that in the issue I linked.   Pretty much any Mac user with a mouse will have a Magic Mouse.  

> But then you will lose the new ability to pan around using the trackpad (which is expected and a desired change in behaviour). 

Not for my app.   The expected behavior is how it used to work.  I have panning disabled for my InteractiveViewer so don't need trackpad panning.  


I can figure out how to work around this - I may even abandon InteractiveViewer.   But I feel it's a bigger issue if core behaviors like this are changing in minor version upticks - and as far as I could tell, not discussed in the release notes.

**Comment by moffatman** [comment]
I did write a [migration guide](https://docs.flutter.dev/release/breaking-changes/trackpad-gestures) but I forgot this use case (InteractiveViewer solely for scroll-zoom). If panEnabled is set to false explicitly, I see no reason not to fallback to the old behaviour.

**Comment by TomSwift** [comment]
> I did write a [migration guide](https://docs.flutter.dev/release/breaking-changes/trackpad-gestures) but I forgot this use case (InteractiveViewer solely for scroll-zoom).

Thanks, that's really helpful.   I hadn't found it on my own.  

Is it not possible to detect Magic Mouse and treat it's events like a scroll wheel?

Similarly, was it considered to parameterize the desired gesture/zooming behaviors such that folks could specify new/old behavior?

**Comment by moffatman** [comment]
In those links above, seems difficult to detect. At best we can guess that if there was no trackpad touch immediately before the gestural scroll, it must be from the magic mouse. But actually in macOS Ventura, I just had some stuff break because the sequence of events changed, the trackpad touch coming later than expected. So I will look into it but no sure solution here for an automatic fix on the magic mouse.

I could update that PR above for the InteractiveViewer to offer a choice instead of as a fallback. Something like `trackpadPanShouldZoom` true/false, so that the old behaviour could be specified.

**Comment by TomSwift** [comment]
@moffatman I have zooming working again on a trackpad/magic-mouse by mapping `Listener` `onPointerPanZoomUpdate` events to `PointerScrollEvent` (make it behave like a scroll wheel).   But what I've lost is zooming with momentum, and I'm not sure how to get that back.   It looks to me as if momentum support in InteractiveViewer only works with panning, now.

That is, before this change, I could zoom in/out on an InteractiveViewer, with momentum, with a trackpad 2-finger vertical swipe (or magic mouse 1-finger vertical swipe).  

Do I need to re-invent InteractiveViewer zooming via GestureDetector pan events to track and animate momentum zooming?

One other thing that is confusing to me is that `Listener` `onPointerPanZoomUpdate` now behaves like a gesture detector.   That is, I thought Listener was only about "pointer events", but now it triggers for trackpad "pinch zooming", which is a gesture.   It seems like we're conflating two different concepts here.

It sure is complicated melding gesture/pointer/input-device behaviors across multiple platforms.   Even the terminology "pan", "drag", etc. have different implications across platforms/devices and are super confusing in code when they have different meanings in different contexts.

**Comment by huycozy** [comment]
This issue is reproducible on the latest `stable` and `master` channels with provided sample code. Adding demo video for better visualization.

<details>
<summary>Demo video</summary>


https://user-images.githubusercontent.com/104349824/198985226-5f1e4517-31c0-4afa-8340-2973ca7bd2c1.mp4


</details>


<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (30 hours ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.166, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-10.0.pre.166 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f3f932a68 (5 hours ago), 2022-10-30 17:44:24 -0400
    • Engine revision f91119f84f
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by moffatman** [comment]
`Listener` is for the pointer events from the platform, before processing by any Flutter/dart code gesture detection. But for trackpad pinch-to-zoom and scrolling, we can't get the raw data at the same low level as for touches, we get it once it's already processed by the operating system and determined to be a zoom/scroll/rotate. GestureRecognizer classes now understand how to combine simple touch input with pre-processed system gestures. Please be assured this solution while quite complex is the "least-bad" of alternatives... I did spend some time on this and considered alternatives. If you want to  read in more detail, you can refer to the [design document](https://docs.google.com/document/d/1oRvebwjpsC3KlxN1gOYnEdxtNpQDYpPtUFAkmTUe-K8/edit?resourcekey=0-pt4_T7uggSTrsq2gWeGsYQ).

I will update InteractiveViewer to have some choice between the old and new behavior, you're correct that momentum will need to reimplemented for zooming, since we no longer use the operating system momentum. But I can cover it, you shouldn't have to do that rewrite due to my breakage.

**Comment by TomSwift** [comment]
Thanks for the design-doc link.   The one I found earlier wasn't publicly accessible.

I think it could be useful to disassociate intent from the specific gestures.   That is, instead of calling out a "zoom" event, make it a "pinch" event.   "Pan", I guess, is more difficult - I don't know what else to call the gesture.   I like how in your document you say "Pan (scroll)", and I think the same could be done for pinch: "Pinch (zoom)", to hint at the "default intent".   Pan might become "Pan (scroll, zoom)".

> I could update that PR above for the InteractiveViewer to offer a choice instead of as a fallback. Something like trackpadPanShouldZoom true/false, so that the old behaviour could be specified.

This is probably sufficient, but it ignores what happens to panning when this is set `true`.   I presume the old behavior would be in play, that is (on desktop) inertial panning works with click+drag.   (This is why the nomenclature is so confusing, because on desktop "trackpad pan" is a 2-finger no-click drag, and GestureDetector "pan" is a "click+drag" operation for mouse and trackpad, yes?)

**Comment by moffatman** [comment]
It's called a PointerPanZoomEvent, because it's on some platforms both the relative distance (zoom) as well as location of centroid (pan) are conveyed in a two finger gesture. So you can have both panning and zooming at once. The original name that came to mind was PointerGestureEvent but that is so confusing in so many ways.

My intention for `trackpadPanShouldZoom` (or whatever the name ends up being) will be exactly what you say, you could click+drag to move the viewport around, dragging two fingers up and down on the trackpad (or one finger up and down on the magic mouse) will zoom the viewport (with inertia), pinching on the trackpad will also zoom the viewport.
