### ISSUE TITLE
The plugin url_launcher_android requires Android SDK version 33

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#114262]
## Summary

When building an app I get this warming:
`Warning: The plugin url_launcher_android requires Android SDK version 33.`

Warning message also includes below suggestion for fixing but my compileSDKVersion is already 33!
```
Fix this issue by adding the following to C:\src\projects\project\android\app\build.grad
android {
  compileSdkVersion 33
  ...
```

## Steps to Reproduce

1. flutter create test
2. flutter build ...

## Logs

```
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\src\projects\project\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}
```
## Flutter Doctor

```
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.19045.2130], locale
    en-US)
    • Flutter version 3.3.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\dejan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\dejan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2130]    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.80
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @under3415, can you share your `android/app/build.gradle` file? 

I attempted to reproduce this issue but I was only able to reproduce it when my compileSdkVersion was set to flutter.compileSdkVersion. When I set it to `33` I did not see the issue.

**Comment by kaboc** [comment]
@danagbemava-nc 
Were there unavoidable reasons why `compileSdkVersion` had to be raised while the stable Flutter SDK currently still defaults to `31`? I don't think it is good that users experience an error because of such a too early change in a popular official plugin and are forced to write a specific number in place of the `flutter.compileSdkVersion` variable in build.gradle.

**Comment by danagbemava-nc** [comment]
Hi @kaboc, I haven't taken a closer look so I'm not sure but my guess is that a dependency of the android implementation required that the compileSdkVersion be changed. However, I do not think this is a big issue since other plugins are already using API 33 and if it wasn't `url_launcher_android` that threw this error, another plugin was going to do it. 

The compile and target SDK values are meant to be changed so if it has to be changed because a plugin requires it, I think it's alright.

**Comment by kaboc** [comment]
@danagbemava-nc 
The change was made in [#6487](https://github.com/flutter/plugins/pull/6487). It looks like it was just because Dependabot suggested to bump the version. I'm not sure if there were other reasons too though.

I think it is acceptable if it was inevitable, but if not so, maybe the change should have been delayed. My point is, it has caused a bad user experience. "Other plugins are already using API 33" is not very convincing. It just makes me uncomfortable to think other plugins have the same issue.

It is obvious that the change would cause the reported error, but only the patch version was incremented in `url_launcher_android`, not giving users a choice but to change `compileSdkVersion` or use `dependency_overrides`. Isn't it against semantic versioning?

**Comment by kaboc** [comment]
Is it safe to change `compileSdkVersion` in the first place? I'd like to avoid experiencing unresolved issues like https://github.com/flutter/flutter/issues/109769. It's not clear to me (due to my lack of knowledge) whether only changing `targetSdkVersion` is risky or changing `compileSdkVersion` is too.

**Comment by danagbemava-nc** [comment]
Hi @kaboc, it is safe to change the `compileSdkVersion`. Certain API features in android are introduced at certain compile and target SDK versions so from time to time, you will need to update those values to take advantage of those features. 
This is what the plugins usually do on your behalf. 

Ideally, your compileSdkVersion and targetSdkVersion should be the same, but you can only change the `compileSdkVersion` and leave the `targetSdkVersion` as is.  https://github.com/flutter/flutter/issues/109769 is unfortunate but it looks like this is due to something in the android framework itself which will need to be worked around until the android team comes up with a fix(if they're aware of it at all). 

> "Other plugins are already using API 33" is not very convincing. It just makes me uncomfortable to think other plugins have the same issue.

There really isn't an issue here. You may run into an issue if you change the sdkVersions, but those issues are generally few and far between. 

See https://proandroiddev.com/compilesdkversion-and-targetsdkversion-what-is-the-difference-b4227c663ba8 for more information on the sdkVersions.

**Comment by kaboc** [comment]
Hi @danagbemava-nc. Wow, easiest-to-understand explanation ever!. Thanks for clarification.

What do you think about https://github.com/flutter/flutter/issues/114262#issuecomment-1298596151?

**Comment by danagbemava-nc** [comment]
> It is obvious that the change would cause the reported error, but only the patch version was incremented in url_launcher_android, not giving users a choice but to change compileSdkVersion or use dependency_overrides. Isn't it against semantic versioning?

I don’t think it's against semantic versioning since, in terms of the plugin, it was a minor change that didn't change anything fundamentally about the plugin. It may have had the unintended consequence of asking you to change the compileSdkVersion but nothing about how the plugin is used has changed. 

Hope that makes sense.

**Comment by kaboc** [comment]
@danagbemava-nc 
I see. It makes sense that it's not against semantic versioning as long as API hasn't changed. But I still think it is kind of breaking that we get the error despite no change on our side. It is sad that there is no way to avoid it. It might be better to have even just a notice in the change log to announce the change. There was no mention of it in there this time.
