### ISSUE TITLE
While startVideoRecording called flashlight toggles

### ISSUE THREAD

**Issue by modimayur3812** [flutter/flutter#114218]
When I used startVideoRecording function flashlight toggle automatically. If flash mode is set to FlashMode.torch then first flash get off and then it changes to torch. Same issue with stopVideoRecording.

**Comment by huycozy** [comment]
Hi @modimayur3812 
It seems you are having this issue with `camera` plugin. Which `camera` plugin version are you using?

And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thanks!
