### ISSUE TITLE
camera_avfoundation iOS crash The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888 

### ISSUE THREAD

**Issue by sunjianios** [flutter/flutter#114410]
camera:
    dependency: transitive
    description:
      name: camera
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.10.0+4"
  camera_android:
    dependency: transitive
    description:
      name: camera_android
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.10.0+4"
  camera_avfoundation:
    dependency: transitive
    description:
      name: camera_avfoundation
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.9.8+6"
  camera_platform_interface:
    dependency: transitive
    description:
      name: camera_platform_interface
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.3.0"
  camera_web:
    dependency: transitive
    description:
      name: camera_web
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.3.0+1"

I running app on iPhone8 device(iOS 12.4.1 ) , when take photos or videos, xcode print "The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888", then crash and xcode show alert which display 'Message from debugger: Terminated due to memory issue'

**Comment by huycozy** [comment]
Hi @sunjianios
Do you face this issue with [camera/example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) sample code? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter run -v` and `flutter doctor -v` as well. Thank you!
