### ISSUE TITLE
Flutter FX

### ISSUE THREAD

**Issue by davidjeba** [flutter/flutter#114613]
Proposing FLUTTER FX

an onscreen interactive animation core package
which can allow the package to use GPU to apply 60fps animations

Flutter FX Marketplace on pub.dev

Just like rive.app a place where creators can create butter smooth animations and list it
eg: [https://jsfiddle.net/f0rs2cjt/](https://jsfiddle.net/f0rs2cjt/)

**Comment by exaby73** [comment]
Hello @davidjeba. This doesn't look like a valid proposal to me. Flutter already provides ways to create smooth animations hitting 60FPS and above. If you need more complex animations, as you mentioned, there is already a place for that using Rive or Lottie. You can also find lots of packages on pub.dev that allow you to simplify animations further. Flutter is built to provide good defaults and expects the developer to build up their app using composition rather than providing full fledged solutions. 

Due to above reasons, I am closing this issue. Thank you.

**Comment by davidjeba** [comment]
i was expecting more native features like flame engine in flutter so that i can build native hyper casual and super responsive 3D games using flutter instead of using phaser/unity etc

you may as why?
If i want to build an app in flutter and that app to have a section for games [integrating webgl/flame etc inside flutter doesnt make sense] rather flutter can better evolve in game direction as well.
the roadmap towards better games in flutter needs a push.
