### ISSUE TITLE
Stuck on observatory when running on Vivo device on android 13

### ISSUE THREAD

**Issue by Nihal2k2** [flutter/flutter#114761]
Launching lib\main.dart on I2202 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (25546): The Dart VM service is listening on ************************************

This is the same as the problem mentioned in #82520
But this time I have a iqoo neo 6 and it was working perfectly till before I upgraded it to android 13.

it shows a black screen on the phone when we run the app from flutter, but when we just open the already-installed app it works fine.

**Comment by danagbemava-nc** [comment]
Hi @Nihal2k2, in #82520, it was determined that this was an issue with Vivo devices and not related to flutter. Given that this worked until you upgraded your OS, I'm more inclined to believe that this is more an issue with vivo rather than flutter. 

You may need to report this to their support team so they can route it to the appropriate team. 

Btw, did you upgrade your flutter version or the only upgrade you made was a change to your device OS?

Please share your flutter doctor -v output as well. 

Thank you
