### ISSUE TITLE
PlatformViews need clipRect.

### ISSUE THREAD

**Issue by endless7** [flutter/flutter#114784]
Hi, when using platformviews, `getLocalClipBounds` should return the bounds of the platformview, not the bounds of the canvas.
```
// SkBigPicture.cpp
const bool useBBH = !canvas->getLocalClipBounds().contains(this->cullRect());
```
When I did `clipRect` as below, it became correct.
```
SkCanvas* overlay_canvas = frame->SkiaCanvas();
overlay_canvas->clipRect(rect);
```

https://github.com/flutter/engine/pull/37107

cc @ColdPaleLight @flar @dnfield

**Comment by flar** [comment]
The description here doesn't really explain the problem at all.

"it became correct". What became correct? That line of Skia code? How does that line of Skia code relate to anything. If that line returns true or false, what impact does that have?

There is no justification for how this is causing problems other than "1 line of code is affected by another line of code".

Please explain what is happening that is undesirable at a Flutter level, not what lines of code relate to what other lines of code.

**Comment by endless7** [comment]
Here is the demo code: https://gist.github.com/endless7/e04822eaa651a86b52fdcf17c1f40455
<img src=https://user-images.githubusercontent.com/33014143/201033184-487b16a1-5e34-4bf7-96f0-cae75682998d.gif width=20% />
In this case, when the color changed, we just need to paint the bounds of the platformview in overlay_canvas, but paint the full canvas. And without clip, canvas->getLocalClipBounds() will always return the bounds of the canvas, this means bbh(rtree) will not be used in skia because it found the paint bounds contains all op. 
<img src=https://user-images.githubusercontent.com/33014143/201034921-88fcee38-e10c-482a-b605-917bff8b9c55.jpg width=20% />
cc @flar @dnfield

**Comment by flar** [comment]
Is this in the case of a partial repaint due to dirty region management?

Supplying a clip will have 2 effects:

- It will limit the pixels being modified, which can have a very large impact if you are only updating a small region of a larger rendering
- Whether or not the picture has BBH enabled, it will allow Skia to quickly reject operations that are outside the clip.

Both of those will provide a benefit whether or not BBH triggers. BBH provides a fast up-front rejection of operations outside of the clip, but that overhead should only be noticeable with hundreds or thousands of rendering operations.

Another question is why the surface is so large? If we control its allocation we should only allocate a smaller surface, the size of the dirty region update. Why was the surface allocated with such a large size? That allocation could be a performance drain as well.

**Comment by flar** [comment]
While investigating an issue with Impeller performance with embedders I discovered why this clip matters.

When we render over/under platform views, we render the scene in multiple pieces. The pieces that are above a platform view are also rendered in 2 different ways - first they are rendered with a hole punched out of them where the platform view takes up space, this is so that they don't "cover" the platform view with rendered content. Then they are rendered again with a small clip that covers just the intersection between their content and the platform view.  When rendering that small clipped section (which happens any time we have a platform view), much of the content of the scene doesn't intersect the rectangle specified, so it can be quickly culled during rendering. Unfortunately, since we never apply the clip to the graphics object, any culling code cannot come into play.

So, this isn't an issue with partial repaints, it is something that happens every time we have a platform view in the frame.

**Comment by endless7** [comment]
> While investigating an issue with Impeller performance with embedders I discovered why this clip matters.
> 
> When we render over/under platform views, we render the scene in multiple pieces. The pieces that are above a platform view are also rendered in 2 different ways - first they are rendered with a hole punched out of them where the platform view takes up space, this is so that they don't "cover" the platform view with rendered content. Then they are rendered again with a small clip that covers just the intersection between their content and the platform view. When rendering that small clipped section (which happens any time we have a platform view), much of the content of the scene doesn't intersect the rectangle specified, so it can be quickly culled during rendering. Unfortunately, since we never apply the clip to the graphics object, any culling code cannot come into play.
> 
> So, this isn't an issue with partial repaints, it is something that happens every time we have a platform view in the frame.

This is what I wanted to say, and I apologize for not adding enough context. Thanks!!
