### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by FelixDubois** [flutter/flutter#114775]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:77:7)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:184:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:162:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:843:9)
<asynchronous suspension>

**Comment by darshankawar** [comment]
@FelixDubois , this issue was initially reported in https://github.com/flutter/flutter/issues/107590 and has since been fixed.

The fix is available on the master and beta channels and it should be available on stable some time in the future.

Per our triage policy, I'll be closing this issue since it has already been fixed.
If you are still seeing this on latest master or beta, write in comments and I'll reopen it.
