### ISSUE TITLE
The parameter 'imageUrl' can't have a value of 'null' because of its type, but the implicit default value is 'null'. Try adding either an explicit non-'null' default value or the 'required' modifier

### ISSUE THREAD

**Issue by grfn13** [flutter/flutter#114822]
I'm fairly new to Flutter and am creating a grocery app using flutter bloc. It's throwing me this error of can't have value of null. I did try doing the quickfix and make the required fields but it complicates my bloc when I do that for my state and event bloc files. I will include screenshots below, thank you in advance for any help

![error1](https://user-images.githubusercontent.com/66144539/200366452-6a2db1da-74e1-4964-8c55-58e54b7c01fb.PNG)
![error2](https://user-images.githubusercontent.com/66144539/200366458-92d5c5b6-e274-4083-ab19-cb1c273657db.PNG)
![error3](https://user-images.githubusercontent.com/66144539/200366462-06c18ecc-6ac5-45fb-b56e-af202120fc2c.PNG)

**Comment by huycozy** [comment]
Hi @grfn13. It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. You can also see this SO answer for more details: https://stackoverflow.com/questions/64560461/the-parameter-cant-have-a-value-of-null-because-of-its-type-in-dart

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
