### ISSUE TITLE
[Impeller] Switch back to nearest sampling when reading glyphs from the glyph atlas

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#115041]
This came up during a discussion [about an unrelated issue](https://github.com/flutter/flutter/issues/114563) related to font rendering. Linear sampling from an atlas shouldn't be necessary as the glyphs in the atlas are rendered at scale and have anti-aliasing applied to them already. @bdero explained that he applied this sampling mode on a hunch and was going to verify that it was indeed required. This issue tracks verifying the need for bilinear sampling and also its correctness.

**Comment by chinmaygarde** [comment]
@bdero: Just filed this to track. Not particularly high priority.

**Comment by bdero** [comment]
I turned on linear sampling to mask a problem where sampled lines are getting repeated, which is probably due to the sampling rectangle winding up slightly smaller than the on-screen geometry rectangle. This might be a precision issue, but I haven't investigated it deeply yet.

In the nearest sampling image below, note that all of the text glyphs are stretched out by one additional pixel in the up/down direction, causing one repeated line in the middle.

Another observation: The Skia text appears to have a less heavy weight than both Impeller screenshots.

**Impeller with nearest sampling:**
![Screen Shot 2022-11-10 at 8 09 15 PM](https://user-images.githubusercontent.com/919017/201262064-de9fe95a-22b2-4aa0-a8ca-750af7254023.png)

**Impeller with linear sampling:**
![Screen Shot 2022-11-10 at 8 15 43 PM](https://user-images.githubusercontent.com/919017/201262109-66182266-3ba1-4a55-a565-4e18e8652e83.png)

**Skia:**
![Screen Shot 2022-11-10 at 8 18 58 PM](https://user-images.githubusercontent.com/919017/201262393-129c995c-ad7a-4bf0-b134-2ea123f1ac08.png)

**Comment by bdero** [comment]
This was resolved with https://github.com/flutter/engine/pull/39104
