### ISSUE TITLE
New Sliver Tools

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#115070]
Can you add new Sliver Tools like multi sliver, Sliver Stack, Sliver Row, Sliver Column. For Example like here https://pub.dev/packages/sliver_tools .
<img width="1710" alt="Screen Shot 2022-11-10 at 4 50 50 PM" src="https://user-images.githubusercontent.com/30003495/201071974-6bcccba1-5362-44a1-929c-1f2e9e6c1ca6.png">

For example how make this UI ? without shrink-wrap ? If you have 100 000 items how use builder ? If we could have Sliver Row, It would be better

**Comment by iapicca** [comment]
@Hellomik2002 
this doesn't seem to be neither a bug nor a feature request

**Comment by darshankawar** [comment]
@Hellomik2002 
As commented above and also based on the description provided, it's not clear what exactly is your ask. If you would like a new widget to be added in the framework, please use new issue template and select feature request, provide relevant details in it so that we'll have clear idea about the issue.

Closing for now.
