### ISSUE TITLE
Inherited Padding, Margin and spacing

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#115090]
## Use case

Flutter is a bit inconsistent with paddings. Some widgets have padding (such as `SingleChildScrollView`, others, don't, such as `CustomScrollView` (although both are for scrolling)).

Also, `Card` is the only component with a `margin` property.

When working with `Column` or `Row` we often use a `const SizedBox()` for spacing, because `Padding` makes a new ident on our code, making it a bit more hard to head. Also, it is also inconsistent (for example, if `Text` accepts a non-named parameter, why not `Padding`? i.e. Why is `Text("string")` instead of `Text(text: "String")` and `Padding(padding: const EdgeInsets.all(16))` instead of `Padding(const EdgeInsets.all(16))` or, better yet, `Padding.all(16, child: ...)`?

## Proposal

To fix some of the issues about padding and margin, it would be nice if the `Widget` class had two properties: `EdgeInsets? margin` and `EdgeInsets? padding`, applying the margins and paddings if they are not null.

For `Column` and `Row` would be nice some extra info about spacing (assuming we want a 16 pixels margin in all sides of a column and each widget inside a column spaced by 16 pixels as well, it's pretty nasty to accomplish that with `Padding` (because of indentation) and a bit messy with extra `SizedBox(height: 16)`, specially if we are talking about responsive layouts.

So, as `Column` and `Row` both inherit from `Flex`, it would be nice such a `double spacing = 0`, specially with `mainAxisSize: MainAxisSize.min`.

Layouts would be a lot cleaner that way.

**Comment by exaby73** [comment]
Hello @JCKodel. I will focus on the margin and padding inheritance you mentioned. I think the proposal for `Flex` to have `spacing` should be it's own issue.

Flutter is a UI toolkit that promotes composition over inheritance. Sure this leads to a bit more verbose code, but it allows for much more control to the developer. For use cases where inheritance makes more sense, Flutter provides an `InheritedWidget`, which allows you to do just that. You can define default margins and paddings in that widget and use them via `InheritedWidget.of(context)` in the widgets below.

Also an issue with changing the way margin and padding work currently, would break a lot of UI that is reliant on these "inconsistent" paddings throughout the framework. This extends to changing the behavior of `Padding` to have a positional argument instead of a named one. Again, with the `Padding.all` feature you mentioned, I think that too should be it's own issue.

Due to inherited padding both being "hidden" from the developer rather than a clear "Padding" widget or "SizedBox" for spacing, which is a common pattern you see in a lot of Flutter code, and the fact that this change would be a major breaking change for most, if not all code out there, I am closing this issue as invalid. If you disagree, please comment and I can reopen it. Thank you.
