### ISSUE TITLE
iOS builds failing due to code signing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#115000]
Maybe isolated to m9?

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_1_4/31077/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20tool_integration_tests_4_4/16905/overview

P0 since this is blocking rolls.

**Comment by godofredoc** [comment]
@keyonghan is this related to the certificates installation in chromium machines?

**Comment by godofredoc** [comment]
@jmagman may have some ideas of why this is happening.

**Comment by keyonghan** [comment]
From log, the command is using --no-codesign flag
```
../../../bin/flutter build ios --no-codesign --release -v
```

**Comment by jmagman** [comment]
@keyonghan can we quarantine m9 while this is investigated, this is causing a lot of flakes.  Here's another: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20post_backdrop_filter_perf_ios__timeline_summary/7705/overview

**Comment by keyonghan** [comment]
The issue seems happening randomly on different bots, not specifically tied to mac-9:
Mac6: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_ios__compile/7832/overview
mac-25: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20color_filter_and_fade_perf_impeller_ios__e2e_summary/1270/overview
Mac-27: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_test_test_ios/7445/overview

**Comment by keyonghan** [comment]
From most of those failures, they are actually with 
```
== Runtimes ==
iOS 16.0 (16.0 - 20A5339d) - com.apple.CoreSimulator.SimRuntime.iOS-16-0
```

**Comment by jmagman** [comment]
Ah yes, those are actually codesigning issues:


> From log, the command is using `--no-codesign` flag

I'm not sure which logs you looked at, I just looked at 

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8797949908087876577/+/u/run_color_filter_and_fade_perf_impeller_ios__e2e_summary/test_stdout

and that to be codesigned because it's running on a physical device, and it's running `flutter drive` without `--no-codesign` 
```
Exception: Error (Xcode): Target release_unpack_ios failed: Exception: Failed to codesign
```

The ones Zach listed seem to be a bad Xcode cache on m9 though?  No idea how or why.

**Comment by keyonghan** [comment]
Summarize a bit, two main issues:
1) Looking for Runtime iOS 16.0 while iOS 15.5 was installed (this is the issue originally posted in this bug) - Mac Host Only testbed
Example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_1_4/31077/overview

This issue seems related to cache as @jmagman mentioned, and these bots have been running tests successfully with the correct iOS16 installed.

New rolls have been landed, and lowering the priority to keep monitoring.

2) Codesign issue with DeviceLab testbeds

This is a real codesign issue, and may be related to recently updated certificate in devicelab. Opened https://github.com/flutter/flutter/issues/115035 to track separately.

**Comment by godofredoc** [comment]
The caches are getting into a bad state after running with xcode:

```
"$flutter/osx_sdk": {
                "sdk_version": "13f17a"
              },
```

When requesting a named cache of `flutter__xcode_14a5294e:cache/xcode`

When that happens the local `xcode_14a5294e` cache is updated with the content of xcode `13f17a` and the next task requesting xcode cache xcode_14a5294e will be running with `13f17a` instead of `14a5294e`

**Comment by keyonghan** [comment]
Which build/task/bot did you see the `13f17a` property? Something from release targets? All our main/master targets are using `14a5294e` now.

**Comment by godofredoc** [comment]
Unfortunately I didn't save the link but you can try with the led runs on failing bots

**Comment by kvedala** [comment]
It seems that on MacOS Ventura, the codesign does not work from from commandline. 
The command: `codesign -s "Apple Development" "Test String"` fails with the error:
`libc++abi: terminating with uncaught exception of type std::runtime_error: Only ad-hoc identities supported, requested: 'Apple Development'`

This also results in the `xcodebuild` command to fail. However, the Xcode App itself compiles the project successfully. While this is ok, debugging an iOS app using Flutter becomes impossible.

Note that the `codesign` command does not give any error on the previous MacOS versions.

**Comment by jmagman** [comment]
@kvedala this issue is specifically tracking a codesigning/keychain issue in Flutter's CI system.  Please file a new issue completely filling out the template describing what you're seeing and we'll take a look.
