### ISSUE TITLE
[in_app_purchase] Google Play Subscription update (May 2022) integration

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#115147]
From [Google's "Understanding subscriptions" article](https://support.google.com/googleplay/android-developer/answer/12154973?)

> In May 2022, we introduced changes in the way subscription products are defined and managed in Play Console.

Subscriptions now can contain several base plans and offers: 

![](https://storage.googleapis.com/support-kms-prod/ZeJItyfT1ipHhboAMxxxiZtmuY2XPdluQTUL)

Relevant article: [Recent changes to subscriptions in Play Console](https://support.google.com/googleplay/android-developer/answer/12124625)

I've had a go setting up a new format subscription, added base plans and offers however I can find no way to query this using the `in_app_purchase` library, the packages changelog suggests that this support hasn't yet been added. Google is now referring to old style subscription as legacy so it would be worth adding support for the new subscription format.

**Comment by darshankawar** [comment]
@jimmyff 
I think since it is related to Google Play now managing Base plans & Offers inside each subscription, most probably implementing this https://github.com/flutter/flutter/issues/107370 would resolve this issue too.
So I suggest you to follow-up in attached link for further updates. If you disagree, write in comments and I'll reopen it.
