### ISSUE TITLE
How to remove space between suffixIcon and input value of TextFormField?

### ISSUE THREAD

**Issue by tal-72** [flutter/flutter#115149]
i have a scenerio. In that scenario i need to add another string may be RichText() right after the value of textFormField.
For example

555 is the value of textformfield and yy need to be added.
so the output should be 555 yy.
I don't want to use suffixText;

this 555 yy should appear in the center of textformfield.
Thanks

**Comment by huycozy** [comment]
Hi @tal-72
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
