### ISSUE TITLE
[Proposal]: DropdownButtonFormField should has enable boolean field

### ISSUE THREAD

**Issue by MuhmdHsn313** [flutter/flutter#115269]
## Use case
Sometimes we need to disable the `DropdownButtonFormField`, maybe we ask the user to select his gender, and after that user is never able to change his gender and we needn't change the UI and use the same UI to preview the data.

## Proposal
If you can provide a boolean field same that exists in `TextField` in the name `enable` to enable or disable the field.

**Comment by exaby73** [comment]
Hello @MuhmdHsn313. This is already possible by passing `null` to [`onChanged`](https://api.flutter.dev/flutter/material/DropdownButtonFormField/onChanged.html) or passing `null` to [`items`](https://api.flutter.dev/flutter/material/DropdownButton/items.html). From [the docs](https://api.flutter.dev/flutter/material/DropdownButtonFormField/onChanged.html):

> If the [onChanged](https://api.flutter.dev/flutter/material/DropdownButtonFormField/onChanged.html) callback is null or the list of [DropdownButton.items](https://api.flutter.dev/flutter/material/DropdownButton/items.html) is null then the dropdown button will be disabled, i.e. its arrow will be displayed in grey and it will not respond to input.

Due to the above reasons, this request is invalid. Closing the issue due to the same reason. Thank you.
