### ISSUE TITLE
Require a consistent App rename command for all platforms

### ISSUE THREAD

**Issue by dbsxdbsx** [flutter/flutter#115264]
## What is the trouble
When an App is initialed, sometimes the App name is needed to change. And out of my expectation, this task is quite difficult for a flutter project, let alone there are various platforms.

At present, I use a package called [rename_app](https://github.com/Syed-Waleed-Shah/rename_app) to somehow alleviate the tedious task. But still, the package is not good enough, so I posted an [issue](https://github.com/Syed-Waleed-Shah/rename_app/issues/2#issuecomment-1313191601) there. And then, I realized that **the concept "App name" is a little unclear**, especially when the App is for different platforms.

For example, the "App name" could not only refer to the name below the App Icon, but also may sometimes refer to the process name(if I am not wrong) shown after tapping "overview" button on an Android mobile phone. In addition, on windows, the "App name" could also refer to the taskbar name, the process name shown in task manager, or even the title on top of the App main window.

You may think that I misunderstood and mixed some concepts. But I would argue that **somehow flutter leads to this misunderstanding**.
For instance, if I want to change the process name in Android:
![fff](https://user-images.githubusercontent.com/17372655/201610298-02796b99-8bcb-44d5-8645-1778afd801a5.png)

What I know is that the code could be like this:
```dart
 MaterialApp(
      title: 'the_title_shown_in_overview',
      ...
    home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
```
Ok, now the name shown after tapping button `overview` is indeed changed----so I am wrong, it is called "title" of the App(though there is another title---the one in attribute `home`), but not "process name", not "App name"; while building it for win10, then the "title"(shown on the top of the main window) of the App is not changed. Then how to change the "title" on win10? Referring here, [a cpp](https://stackoverflow.com/questions/64800455/how-to-change-app-icon-and-app-name-for-flutter-desktop-application#:~:text=To%20change%20application%20icon%3A%20Simply,your%20application%20name%20inside%20window.) file need to change.

## Feature request
You can see that the concept is quite misleading. And usually(if not always), when referring to "App name", users(even developers) may refer to the same things. And for the sake of both using and developing ergonomically, these little different names usually should be the same. Therefore, I hope there is an in-build command to rename App name consistently over all platforms conveniently, like the [rename_app](https://github.com/Syed-Waleed-Shah/rename_app) does so.

(For more details and thoughts, please check the issue link I posted above)

**Comment by stuartmorgan** [comment]
> And then, I realized that **the concept "App name" is a little unclear**

You are grouping together a number of different things and calling them all "app name", which is why it's unclear. For instance, you're conflating window title and application name on Windows, when it's not at all uncommon for Windows applications to have windows whose titles are not the same as the name of the application.

Given this, it's not actually clear what the command you are requesting would be expected to do.

> But I would argue that **somehow flutter leads to this misunderstanding**.

How so? Every distinction you've described is an operating-system-level concept, not something Flutter created.

> And usually(if not always), when referring to "App name", users(even developers) may refer to the same things. And for the sake of both using and developing ergonomically, these little different names usually should be the same.

This depends on the application. The reason that the various operating systems have different ways of specifying each of these elements is that they are not necessarily the same.

The fact that you are looking for a tool that embodies a specific idea of what an "app name" is/includes seems like a strong argument for this being a third-party tool (designed for that specific use case) rather than part of the `flutter` tool.

**Comment by dbsxdbsx** [comment]
Since you said like this, I guess I can only do so with a 3rd package.
