### ISSUE TITLE
[web]: Mutual TLS support for flutter web client

### ISSUE THREAD

**Issue by pranavpsawant** [flutter/flutter#115305]
Hello,

I wanted to use flutter web client to make api calls to a server which requires me to provide client certificates. Although I was able to do the same using securityContext from dart.io package on iOS and Android, there is no option to do the same on web as io package is not supported on web.

Is there a way I can issue http requests with cert on flutter web ? This is blocking me from using flutter on web for my web based projects. Thanks.

**Comment by rexthecoder** [comment]
Hello @pranavpsawant 
Have you tried [universal_io](https://pub.dev/packages/universal_io)? it has the same dart.io APIs, but this time with support for the web.

Let me know if that helps :)

**Comment by pranavpsawant** [comment]
Nah that one doesnt help either. The SecurityContext class there throws notImplemented error. And the clients offered do not take client certs as arguments

**Comment by exaby73** [comment]
Hello @pranavpsawant. Unfortunately, this issue doesn't have anything to do with Flutter. I think what you're looking for is a feature request to either [`dart:html`](https://api.dart.dev/stable/2.18.4/dart-html/dart-html-library.html) to support [`SecurityContext`](https://api.flutter.dev/flutter/dart-io/SecurityContext-class.html) although I am not sure if that's feasible, or to use the [http](https://pub.dev/packages/http) package to make the requests with your custom certs, both of which are maintained by the Dart team, and not the Flutter team. You may have better luck raising this issue in https://github.com/dart-lang/sdk

Alternatively, you can write a Dart wrapper around JS methods and use JS interop to run JS code from Dart. Though, I am not sure if that's possible in JS due to [this answer on StackoverFlow](https://stackoverflow.com/questions/60327664/flutter-web-problem-making-request-to-a-server-with-self-signed-certificate). And if it's not possible in JS, it wouldn't be possible in Flutter/Dart for web as well since ultimately, you are running on a browser.

All in all, this issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pranavpsawant** [comment]
Thanks @exaby73 for the response. Fair point, seems like a dart thing as opposed to flutter.

Coming to JS implementation, I can totally see axis supporting it based off the this link https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate, and thus was wondering what would it take for dart http package to support it as well. 

But as suggested, will post this question in dart http. Thanks again.
