### ISSUE TITLE
The plugins `firebase_auth` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by thaliachitziou99** [flutter/flutter#115436]
I have a problem downloading the plugin. I use `flutter version 3.3.8`. The message that I get when I run `flutter pub get` is this:

**_The plugins "firebase_auth" use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration._**

**Comment by danagbemava-nc** [comment]
Hi @thaliachitziou99, firebase_auth is a third-party plugin. Any issues you face using it should be reported on their repo. 

I'll be closing this as this issue is not related directly to the flutter repo. 

Kindly make sure you're using the latest version of the plugin because as far as I understand, they have migrated to from the v1 embedding for quite some time now.
