### ISSUE TITLE
Text too gray (white) on Android since last alpha upgrade

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#11579]
Today I've updated flutter using the "flutter upgrade" command (alpha channel).
To my surprise, after build, the app didn't feel the same. That's because since the upgrade, some text colors became way too gray (light) and I don't like it. Is it possible to have the same text colors as before? Thank you.

Before
![Before](https://image.ibb.co/iCt2Uv/Screenshot_20170810_133053.png)
After
![After](https://image.ibb.co/naVAGa/Screenshot_20170810_133046.png)

**Comment by eseidelGoogle** [comment]
I suspect this is https://github.com/flutter/flutter/issues/10655.

My understanding of the issue is that although our new behavior is technically color-correct, we may not want to be using the Material Design values as opacity but rather as brightness.  My understanding is @brianosman and other Skia folks were discussing possible changes here.  @Hixie @sethladd

**Comment by Hixie** [comment]
Have we asked the material team for a call on this? @sethladd?

**Comment by reed-at-google** [comment]
An alternate set of material values (for alpha blending) might solve this -- one set for legacy blending and one set for color-correct.

**Comment by Hixie** [comment]
Fixed, see https://github.com/flutter/flutter/issues/10655.
