### ISSUE TITLE
[url_launcher][Android] forced - requires android SDK version 33

### ISSUE THREAD

**Issue by PabloSanMartin** [flutter/flutter#115958]
## Steps to Reproduce

1. Added url_launcher: ^6.1.6 to my yaml
2. Added a button that sends the user to a pdf
3. Trying to compile in a emulated android phone with sdk 31

![image](https://user-images.githubusercontent.com/55806223/203670152-9a0638df-230b-4fd9-9061-5da0ed927e83.png)

**Expected results:** 
https://pub.dev/packages/url_launcher indicates that it should work on sdk 16+

**Actual results:** 
Works only on sdk 33, tested on sdk 33 and works fine, anything else we get an error.

**Comment by stuartmorgan** [comment]
You are conflating `compileSdkVersion` and `minSdkVersion`. The plugin continues to support devices running SDK 16 and higher, your app just has to use a `compileSdkVersion` of 33+ when building. Almost all plugins (and apps) have a higher `compileSdkVersion` than `minSdkVersion`.

Closing as this is the expected behavior.
