### ISSUE TITLE
Mitigate customers pains / allow apps to be shipped

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#115918]
Hello, is there a way for flutter team to try to accelerate on the few yet severe issues which prevent apps from being shipped?

I love flutter and acknowledge its great potential, but after 9months waiting for fixes, and with so many things going on with flutter roadmap, I need to ask for clarification about what to expect in the short term in regard to:
- Performance
- Text / Textfield / Emojis
- Camera
- Platform Fidelity

As of now, I’m forced not to ship app. Criteria is: if I can open app and say: “This is flutter” in less than 5sec, if people open keyboard and see weird animations, if they type emojis and see tiny images with wrong baseline and spacing, if they scroll or change screens or resume from background and see janks, then lets not ship app.

Can you please guys take a moment to discuss how this problem is impacting developers and tell if you can do something for us in the short term? Having some deadlines would also be helpful.

Thx for any help you can provide.

**Comment by stuartmorgan** [comment]
For information about when specific issues will be fixed, you'd need to look at those individual issues; see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed for general information about issue timelines.

For general discussion, you can try one of the resources listed at https://flutter.dev/community#community-grid. The issue tracker is for tracking specific, actionable bugs and feature requests, rather than high level questions or discussion.

**Comment by delfme** [comment]
Thanks Stuart. I appreciate it. But I don’t see where to write this on discord. Channels there are not meant to address such a question.

As for the specific issues, they are well known, but as example, lets us take #28894 which summarizes well the situation. 

We are talking about typical p0-p1 issue for developers, coz it is a missing or buggy “core feature” that prevents app from being shipped.

However, issue is marked p4 and no fix has landed after 3yrs (prolly due to something blocking at low-level). Given that we cannot fix these issues ourselves, what can we do?

Hope you guys at Google can discuss this on your side and see how you can cope with the situation. Because this really needs Google.
