### ISSUE TITLE
Document debugPaintSizeEnabled and debugRepaintRainbow

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#11601]
Hello, a junior working alone on a side project here.

An improvement for the repaint rainbow :
Make one for each stateful widgets, instead of the whole window.

This would help a lot to pin-point what is updating and what's not. 
Also, the current rainbow is polluted if you have any 'permanent animation' such as a clock.

A small example :
![image](https://user-images.githubusercontent.com/20165741/29251722-744e0ed4-805a-11e7-9b23-ab893530c98b.png)

**Comment by Hixie** [comment]
I think what is showing in that screenshot is the debugPaintSizeEnabled mode, not debugRepaintRainbow mode, but I could be wrong.

The repaint rainbow changing a lot when there's an animation is very much intentional, it's showing you what is repainting.

Can you elaborate on the stateful widget thing? I don't really understand what you're trying to debug. Widgets don't paint alone, they paint in groups (you can separate the groups using RepaintBoundary widgets).

**Comment by rrousselGit** [comment]
Oh, repaintBoundary is exactly what I asked for. My bad.
You solved both my confusion and my CPU problem, thanks !

Just in case, what I wanted :
![image](https://user-images.githubusercontent.com/20165741/29252569-7a5e6a3e-806a-11e7-8ab0-1918a0ccea8a.png)


But doesn't that means we need to put repaint boudaries on nearly all animated widgets, or else a small press on a button will cause a huge repaint ?

**Comment by Hixie** [comment]
Repaints are often not that expensive (you can see how bad it is by looking at the timeline in the observatory), but if you find that a particular widget is indeed expensive to draw and you want to wall it off from other things repainting, then yes, putting an animated boundary can be a good idea. It's also a lot more expensive in terms of memory and can actually raise the cost of painting because it introduces a composition phase (we have to keep track of all the subparts that _don't_ repaint, essentially, so that we can put them all together at the end). So it's one of those things you have to benchmark (e.g. by looking at the timeline) and see whether it's beneficial or not. You can also look at the render tree dump (press "t" in the `flutter run` console) and look for the diagnostics for each RenderRepaintBoundary object, it'll tell you if the repaint boundary is proving useful or not.

**Comment by Hixie** [comment]
Leaving this open to better document these flags.

**Comment by pedromassangocode** [comment]
Found this in `1.21.0-1.0.pre`.

https://api.flutter.dev/flutter/rendering/debugRepaintRainbowEnabled.html
https://api.flutter.dev/flutter/rendering/debugPaintSizeEnabled.html

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • iPhone 6s Plus (mobile) • EE37BCBA-E9E7-4411-9C09-7E8E85DB4ADF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)         • macos                                •
      darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)        • web-server                           •
      web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
@rrousselGit Hi,
Can you take a look at  below links and confirm if this issue can be closed or should be kept open ?

https://api.flutter.dev/flutter/rendering/debugRepaintRainbowEnabled.html
https://api.flutter.dev/flutter/rendering/debugPaintSizeEnabled.html
