### ISSUE TITLE
Memory usage regression in `simple_animation_perf_ios`

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#116116]
* sub_result: `90th_percentile_memory_usage, 99th_percentile_memory_usage, average_memory_usage`
* test:	`simple_animation_perf_ios`
* Commit: https://github.com/flutter/flutter/commit/91aeda7bf6f977207d7ac07ca46c26560007a244
* Link: https://flutter-flutter-perf.skia.org/t/?begin=1669137883&end=1669137885&subset=all

**Comment by iskakaushik** [comment]
cc: @flar

**Comment by iskakaushik** [comment]
The commit was reverted right after, there isn't a suspected commit as of now. We are waiting to get more data to determine if this is expected variance in the benchmark.

**Comment by flar** [comment]
Indeed, the immediately following commit is the revert and it was equally high on the benchmark and the high results after that were post-revert. 15 commits later is when the fix was relanded. This graph should highlight the reland (https://github.com/flutter/flutter/commit/0eb2d51ec9919216127f942cf24d3ddd178ff302) where the results look similar to before the first fix landed:

https://flutter-flutter-perf.skia.org/e/?begin=1668813005&end=1669661038&keys=X6e16bcaba472063fc856f12d2ba7ff91&requestType=0&selected=commit%3D32232%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_memory_usage%252Ctest%253Dsimple_animation_perf_ios%252C&xbaroffset=32217

**Comment by iskakaushik** [comment]
This was within variance.
