### ISSUE TITLE
Process flutter finished with non-zero exit value 1

### ISSUE THREAD

**Issue by fabiosc27** [flutter/flutter#116155]
I got this error when I try to generate a signed apk in the android studio of my flutter app - Process 'command 'C:\Users\Computer\Downloads\flutter_windows_3.3.8-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Versi¢n 10.0.19045.2251], locale es-PE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
Any way to fix this?

I could not find any solution and what I have seen is outdated

**Comment by huycozy** [comment]
@fabiosc27 Does the issue happen when running on debug mode? Please provide the output of `flutter run -v` so that we may verify it. Thanks!

**Comment by fabiosc27** [comment]
@huycozy Hi man, yeah the issue is exactly when running on debug mode.
This is the flutter run -v, I get an error in the build gradle:
[flutter run-v.txt](https://github.com/flutter/flutter/files/10116120/flutter.run-v.txt)

**Comment by huycozy** [comment]
@fabiosc27 
>[  +15 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.

Looks like you are running `flutter run` command from a different directory rather than project directory. Try changing the current directory (`cd` to project directory) and retry. 

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
Closing as it's not a Flutter issue. If you disagree, please write in the comments and I will reopen it. Thanks!
