### ISSUE TITLE
Crashy example should have an example of showing a non-fatal event?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11613]
Posse asked if Crashy should have an example of using the non-fatal event APIs from the sentry package.

Thoughts @yjbanov.  This came up in the context of turning some of their Network load failures (which @collinjackson is looking into) into non-fatal/crash events.

**Comment by yjbanov** [comment]
There is a way to log plain events with string messages. Instead of calling `captureError` you can call `capture` and pass an event with arbitrary data ([API](https://github.com/flutter/sentry/blob/56d544a620791c02ed0ce6844be842407bf11093/lib/sentry.dart#L152)).

Example:

```dart
  await client.capture(event: new Event(
    loggerName: 'package.sentry.test',
    message: 'test event',
  ));
```

Wondering if Firebase Analytics API is a good way to track this?

**Comment by bruno-garcia** [comment]
Crashy already has non-fatal events. In fact the current 3 buttons have "handled errors":

<img width="214" alt="image" src="https://user-images.githubusercontent.com/1633368/79083873-2eb3cd80-7d07-11ea-9d2e-814aa1f29479.png">

The app doesn't crash and the stacktrace is visible in Sentry's event page.
- I suggest closing this issue.

**Comment by bruno-garcia** [comment]
Closing since Crashy has non-fatal events working for both iOS and Android
