### ISSUE TITLE
Data fetching from WIFI take extremely large time.

### ISSUE THREAD

**Issue by AyushTripathi28** [flutter/flutter#116258]
## Details
I was building an app that fetch data from Node||MongoDb sever (implement JWT token also). I have notice that when I am running my app in real device using WIFI my data fetching take lot of time but when I switch back to Phone internet (decent 4g network) it work extremely fast.
My wifi speed is good and also when i am using emulator into my system data load faster on same wifi.

**Target Platform:**
Android
**Target OS version/browser:**
Android 12
**Devices:**
Realme Narzo 50 && One plus 7

## Logs
So while checking the issue I encounter one warnging when ever data take more time to laod but didnot understand what make this happen.
![image](https://user-images.githubusercontent.com/37010915/204737549-f6e6e507-70ff-4c0d-9f9d-6b69a6349aca.png)
time difference on wifi vs 4g network is pretty much. on 4g network it take around 100 to 400 milisecond max but on wifi its like 10000 to 12000 millisecond.

**Comment by darshankawar** [comment]
@AyushTripathi28 
The difference could most probably due to ipv4 and ipv6 requests.
See [this](https://github.com/flutter/flutter/issues/112285#issuecomment-1257759717) comment for your reference and make sure your app is using the suitable internet protocol version which should resolve the issue.

With that being said, I am going ahead and closing it. If you disagree, write in comments and I'll reopen it.
