### ISSUE TITLE
Engine Skia Gold is broken

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#116558]
Skia Gold fails to generate golden digests. I'm also told it may be disabled entirely, which means we could be accumulating engine regressions as we speak.

Sample PR: https://github.com/flutter/engine/pull/37916
Sample digest link: https://flutter-engine-gold.skia.org/search?issue=37916&crs=github&patchsets=1&corpus=flutter-engine

Following this link leads to a page that shows no digest, only this error:

<img width="627" alt="Screen Shot 2022-12-05 at 5 35 18 PM" src="https://user-images.githubusercontent.com/211513/205786799-29de4d99-4712-4b93-848d-d14759217a4d.png">

cc @godofredoc @mdebbar @Piinks

**Comment by yjbanov** [comment]
Perhaps related to https://github.com/flutter/flutter/issues/100916, but that issue is talking about disabling just the _comments_. Skia Gold should continue working as normal, especially in normal engine PRs.

**Comment by mdebbar** [comment]
> Following this link leads to a page that shows no digest, only this error:
> 
> <img alt="Screen Shot 2022-12-05 at 5 35 18 PM" width="627" src="https://user-images.githubusercontent.com/211513/205786799-29de4d99-4712-4b93-848d-d14759217a4d.png">

Believe it or not, this error is actually a good thing 😜 It means there's nothing to triage for the given PR. I remember mentioning this to the Gold team a while ago, but I failed to create a bug, so here it is: https://bugs.chromium.org/p/skia/issues/detail?id=13972



> Perhaps related to #100916, but that issue is talking about disabling just the _comments_. Skia Gold should continue working as normal, especially in normal engine PRs.

That's correct. The recent change mentioned in that issue is only about Gold bot comments. AFAIK, there are no recent changes to golden uploads, etc.

**Comment by mdebbar** [comment]
My duplicate PR has successfully generated goldens and uploaded them to Gold: https://flutter-engine-gold.skia.org/cl/github/38099

**Comment by Piinks** [comment]
It also could be that there are several force pushes on that engine PR - that can break gold since it expects sequential patchsets.

**Comment by yjbanov** [comment]
Thank you @mdebbar and @Piinks for looking into the issue. The force pushes were due to my usage of `git rebase` as part of my workflow. It would be nice if that's handled by Skia Gold correctly. It's a popular workflow. I guess it's not a P1 though. A P3 at most maybe.

**Comment by LeandroLovisolo** [comment]
@mdebbar 

> Believe it or not, this error is actually a good thing 😜 It means there's nothing to triage for the given PR. I remember mentioning this to the Gold team a while ago, but I failed to create a bug, so here it is: https://bugs.chromium.org/p/skia/issues/detail?id=13972

Thanks for the bug report. This CL should replace the "Bad network response" error toast with a more intuitive "No results matched your search criteria" message: https://skia-review.googlesource.com/c/buildbot/+/614937.

For context, the original behavior when there are no results was to show the friendly "No results" message. The error toast is due to a coding error on my part. Thanks for bringing this to my attention!

@Piinks 

> I've seen this a few times in flutter/flutter but it all seemed to be working in spite of the pop-up. I think it can be triggered by a number of things, like whether or not you are logged in.
> 
> These all appear related:
> 
> * https://bugs.chromium.org/p/skia/issues/detail?id=13847
> * https://bugs.chromium.org/p/skia/issues/detail?id=13972
> * https://bugs.chromium.org/p/skia/issues/detail?id=9367
> * https://bugs.chromium.org/p/skia/issues/detail?id=13882
> 
> @LeandroLovisolo, can you tell what is happening here?

I think https://bugs.chromium.org/p/skia/issues/detail?id=13972 and https://bugs.chromium.org/p/skia/issues/detail?id=13882 are actually the same issue.

https://bugs.chromium.org/p/skia/issues/detail?id=13847 appears to be a different issue as it involves a different RPC, though the link you commented on that bug is also an instance of https://bugs.chromium.org/p/skia/issues/detail?id=13972.

https://bugs.chromium.org/p/skia/issues/detail?id=9367 is an auth issue that produces the same generic "Bad network response" error toast.

> Filed https://bugs.chromium.org/p/skia/issues/detail?id=13973 to follow up on force push issue in Gold

Thanks for the bug report! I just added a comment with some background information. Please take a look and let me know your thoughts.

**Comment by keyonghan** [comment]
@Piinks Do we want to close this one in favor of https://bugs.chromium.org/p/skia/issues/detail?id=13973?

**Comment by Piinks** [comment]
Sounds good to me!
