### ISSUE TITLE
TextEditingController should explain its expected lifetime

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11659]
I've seen multiple individuals be confused by TextEditingController and end up re-creating one every time build() is called.  The API docs could explain its expected lifetime (e.g. be held off a State, living as long as the TextInput).

**Comment by cohortor** [comment]
Eric, if I may, I would suggest you update the documentation to explain that the Controller should actually 'outlive' the TextInput/TextField, instead of 'living as long as the TextInput'.

E.g. the controller instance could live in the State associated with a Page that builds the Form/TextFields.

The reason being that more often than not, a form's elements will be children of some sort of Scrollable, and will likely get scrolled off screen as the user interacts with the form.

Coming from Android, it never occurred to me that a widget (along with its state) would be disposed of just because it was (temporarily) scrolled off screen. I consider this a very important (&unintuitive) piece of info I had to learn from the source code the hard way.

I would recommend pointing this out in multiple places in the docs. There are several bugreports and SO entries related to this already. Your own Gallery Demo ('Text Fields') has this 'error' as well: try filling out the Name field, then select another field, scroll down, then scroll back up to see the previously entered value in Name gone.

Being a Flutter noob, it is also possible I have misunderstood something, in which case apologies for the comment...

**Comment by eseidelGoogle** [comment]
Much appreciated, thank you for your feedback @cohortor

**Comment by yathit** [comment]
Very helpful advise 

> E.g. the controller instance could live in the State associated with a Page that builds the Form/TextFields.

**Comment by feinstein** [comment]
@cohortor just to be clear, the best way to use a `TextFieldController` is to initialize it in `initState()`?

**Comment by iapicca** [comment]
Hi @eseidelGoogle is this issue still meant to be open?

**Comment by 18487115313** [comment]
> @cohortor只是要清楚一点，使用a的最佳方法`TextFieldController`是在中初始化它`initState()`？

谢谢，解决了我的一个问题【A TextEditingController was used after being disposed.】
