### ISSUE TITLE
BorderRadius.circular constructor should be `const`

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#116642]
Pretty much the title says it all. There is no reason for that constructor to not be const already. I guess it was just overlooked.

**Comment by maRci002** [comment]
It cannot be `const` since `radius` argument will be passed to `Radius.circular` at runtime no at compile time.

```dart
/// Creates a border radius where all radii are [Radius.circular(radius)].
BorderRadius.circular(double radius) : this.all(
  Radius.circular(radius),
);
```

However you can use `const` to achive the same behavior just use `BorderRadius.all` where you can pass your own `const` `Radius`:

```dart
const BorderRadius.all(Radius.circular(20))
```

**Comment by danagbemava-nc** [comment]
Hi @AlexDochioiu, this has come up several times but it hasn't been done because it isn't possible yet. 
See above and see the issues/prs below

https://github.com/flutter/flutter/issues/58595
https://github.com/flutter/flutter/pull/52309
https://github.com/flutter/flutter/pull/54654
https://github.com/flutter/flutter/pull/35705

Closing this as this is not possible at the moment.

Thank you
