### ISSUE TITLE
Regarding issue with url_launcher when opening website :I/UrlLauncher(17669): component name for (url) is null

### ISSUE THREAD

**Issue by mohadel92** [flutter/flutter#116656]
As mentioned in official `url_launcher` `https://pub.dev/packages/url_launcher#android`

```
<!-- Provide required visibility configuration for API level 30 and above -->
 <queries>
   <!-- If your app checks for SMS support -->
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="sms" />
  </intent>
   <!-- If your app checks for call support -->
   <intent>
     <action android:name="android.intent.action.VIEW" />
     <data android:scheme="tel" />
   </intent>
 </queries>
```

the problem is even after pasting the previous  code the url launching method **canLaunchUrl()** will always return false
as a fix for this issue i found that  **https** intent should be added to the previous <queries> tags
so that url_launcher can open urls without any issue or without asking for 
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`
that may cause application to be rejected later on from Play store
so please consider adding 

```
<intent>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="https" />
</intent>
```
to the official docs of `url_launcher`

**Comment by stuartmorgan** [comment]
> As mentioned in official `url_launcher` `https://pub.dev/packages/url_launcher#android`
> 
> ```
> 
>  <queries>
>    
>   <intent>
>     <action android:name="android.intent.action.VIEW" />
>     <data android:scheme="sms" />
>   </intent>
>    
>    <intent>
>      <action android:name="android.intent.action.VIEW" />
>      <data android:scheme="tel" />
>    </intent>
>  </queries>
> ```

This is clearly labelled as an example in the docs, and that section says: "Add any URL schemes passed to canLaunchUrl as <queries> entries in your AndroidManifest.xml"

> the problem is even after pasting the previous code

That code is an illustrative example, not something we intend for people to paste directly into their application. We have no way of knowing what schemes any given client of the plugin is going to use.

> as a fix for this issue i found that **https** intent should be added to the previous tags

This is true only if you are using `canLaunchUrl` with an `https` URL. There is almost no case where this is useful, which is why we don't include it in the example.

> so that url_launcher can open urls without any issue

Opening URLs doesn't require calling `canLaunchUrl`, as [explained in the documentation](https://pub.dev/packages/url_launcher#checking-supported-schemes) and demonstrated in the example.

Closing as we made a deliberate decision not to include this, as we don't think it's a common use case.
