### ISSUE TITLE
[Web][Framework] `isCanvasKit` implementation is not correct

### ISSUE THREAD

**Issue by alanwutang11** [flutter/flutter#116693]
the bool `isCanvasKit` is not correct for the case when the web renderer is auto. 

https://github.com/flutter/flutter/blob/6e5582da99f3c954c1f969c3ae4437bc0804400a/packages/flutter/lib/src/foundation/constants.dart#L74

**Comment by ditman** [comment]
Currently there's no clean way of communicating arbitrary data cleanly across the App and the Engine in the web. All the APIs that exist are completely Flutter-mobile-centric. This could exist either in the PlatformDispatcher or the current View (depending of what we want to do in a multi-view world). The fallback is to define some js-interop config object somewhere that is accessible through JS (or through a `webOnlyBlah` ui method).

However, in this case I think we're lucky, because there's a JS-interop API ready to go: **the CanvasKitRenderer will attempt to load (and write to) `windowFlutterCanvasKit` when it gets `initialize`d**:

* https://github.com/flutter/engine/blob/dbb5284f2c8d87473d60baa21bba0b7ab88c8281/lib/web_ui/lib/src/engine/canvaskit/renderer.dart#L51-L61

That `windowFlutterCanvasKit` is actually a JS-interop getter/setter that is reading/writing to `window.flutterCanvasKit`, here:

* https://github.com/flutter/engine/blob/dbb5284f2c8d87473d60baa21bba0b7ab88c8281/lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart#L39-L40

I think that until we figure out a cleaner alternative on how to cleanly communicate across app and engine (and plugins!), we should use this already existing method:

```
@JS('window.flutterCanvasKit')
external CanvasKit? get windowFlutterCanvasKit;

bool isCanvasKit = windowFlutterCanvasKit != null;
```

_(Of course, with any dynamic change like this, we're losing the `const`ness of `isCanvasKit` (which may affect treeshaking?))_

**Comment by Ghazanfarrajpoot** [comment]
When will this implement
