### ISSUE TITLE
FLUTTER WEB SCROLL ISSUE (Not work smooth scroll)

### ISSUE THREAD

**Issue by insysinfo** [flutter/flutter#116637]
This smooth_scroll_web is not 100% proper solution because if we use it so, we have to set property NeverScrollPhysics() and it's prevent scrolling for touchpad TABLET and LAPTOP (scroll by fingers)
https://pub.dev/documentation/smooth_scroll_web

and also Flutter web app work fine Desktop and laptop's browser, but performance is slow for Mobile Browsers(Chrome/Safari) etc....

why **flutter web build** not work on Mobile's Browser (low perfomance) like others website (like which made by HTML,CSS,React,Bootstrap, JS)

above issue from Flutter SDK or other issue??????

**Comment by iapicca** [comment]
possibly related to
- https://github.com/flutter/flutter/issues/32120
- https://github.com/flutter/flutter/issues/35687
- https://github.com/flutter/flutter/issues/35723
- https://github.com/flutter/flutter/issues/91788

**Comment by danagbemava-nc** [comment]
Hi @insysinfo, the package you're referring to hasn't been updated in over 2 years. You most likely should not be using it in your project. 

If there are any specific issues that you are facing on flutter web, kindly file issues and provide detailed information as to how to reproduce them so that we can fix them. 

There isn't much information here, so I'll be closing this issue. 

Please do not hesitate to file specific issues within the framework that you experience so that we can investigate and fix them. 

Thank you
