### ISSUE TITLE
undefined reference to `FT_Done_MM_Var

### ISSUE THREAD

**Issue by EsmaeilDansi** [flutter/flutter#116726]
flutter ,, linux . build with snapcraft ...undefined reference to `FT_Done_MM_Var !!!!!!!

**Comment by darshankawar** [comment]
This is similar to https://github.com/flutter/flutter/issues/116562, so please follow-up in it for further updates. Please provide the [requested details](https://github.com/flutter/flutter/issues/116562#issuecomment-1339042052) in that issue, so that it can be addressed as applicable.
Closing this as duplicate.
