### ISSUE TITLE
Use { stiffness, damping, mass } as inputs to spring

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#11684]
On [iOS](https://developer.apple.com/documentation/quartzcore/caspringanimation), [Android](https://developer.android.com/topic/libraries/support-library/preview/spring-animation.html), and the [Web](https://github.com/skevy/wobble/blob/bbc0f831e234f2d24fb905f2ec278c134d69ed68/src/index.js#L11-L22), the names of the inputs into a spring are `{ stiffness, damping, mass }`.  It appears that Flutter [calls `stiffness` the `springConstant`](https://github.com/flutter/flutter/blob/cf991a3412ee9e5feb2fc8002791c18f9d02c519/packages/flutter/lib/src/physics/spring_simulation.dart).

Please be consistent with the other platforms and use `stiffness` instead.

cc: @InMatrix @sethladd

**Comment by Hixie** [comment]
Both names appear to be technically correct. I'm reluctant to change the API since that'd be a breaking change. If we change it we should do it soon. We can certainly document that they are the same, too.

**Comment by appsforartists** [comment]
I just ran a few code searches, and it looks like the project is still young enough that the pain of an API change would be relatively minor.

All of GitHub, including Flutter and Mondrian, [has only 30 occurrences of `springConstant`](https://github.com/search?l=Dart&q=springConstant&type=Code&utf8=%E2%9C%93); in fact, other than the 2 occurrences in Mondrian, every result I've found has been either in a Flutter mirror or a codesample by a core team member.

Let's get this changed while it's still painless to do so!

**Comment by Hixie** [comment]
We can certainly consider API changes, but since we declared API stability 6 months ago, we have to be careful. We have a process, defined here: https://flutter.io/design-principles/#handling-breaking-changes

The first step is to file an issue (which you did) and to add the "API break" label, which I did, and the next step is if someone wants to make the change they can write the PR and send the e-mail as described in those steps.
