### ISSUE TITLE
Allow using dart:mirrors

### ISSUE THREAD

**Issue by tomasweigenast** [flutter/flutter#116890]
It's known that reflection is a really good tool but truly increases binary size, but why don't leave that decision to the final developer? 
A similar issue was opened 6 years ago, its time to reopen and propose a serious command line argument to allow using mirrors.
For example, when running build or run commands pass the flag `--allow-mirrors`

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/issues/1150#issuecomment-254056512 for the way to proceed if you are looking to solve a specific use case.

Since this is the same as the initial request that was closed, with no additional information or use case, I'm going to close it as a duplicate. We don't re-open resolved discussions purely because a certain amount of time has elapsed.
