### ISSUE TITLE
my web application with flutter is too Slow and not smooth

### ISSUE THREAD

**Issue by insysinfo** [flutter/flutter#116968]
my web application with flutter is too Slow and not smooth

**Comment by exaby73** [comment]
Hello @insysinfo. Can you elaborate on the issue here? What part of it is slow? Can you provide a code sample so that I may verify it?

**Comment by insysinfo** [comment]
@exaby73 Sorry i have project no code sample. so i was not able to keep here..
but web scroll not smooth like other sites..(which made by react,nextJS, Html,csss, boostrap etc...)

**Comment by insysinfo** [comment]
@exaby73 i'm using mostly **flutter build web --web-renderer canvaskit** then upload to server

**Comment by insysinfo** [comment]
i used smooth_web_scroll packages but it's prevent scroll touch screen laptops...
it's not proper solution

**Comment by exaby73** [comment]
We do not provide support for 3rd party packages. Although Flutter is pretty optimized, it will not come close to the performance of regular websites built with DOM centric frameworks like React. At least not yet. There are features that the team is working on to improve performance, like dart2wasm, but for now, there's not much that can be done. You can maybe try using the HTM L renderer by adding `--web-renderer html` to your build command. But since this is working as expected, I am closing this issue. Thank you
