### ISSUE TITLE
This command does not work in part

### ISSUE THREAD

**Issue by tongzifang** [flutter/flutter#117050]
flutter build aar --no-debug --no-profile --build-number=1.5.001
I used this command to generate the aar file, but it still generated the debug file
![image](https://user-images.githubusercontent.com/18605773/207575570-f2ee36e9-e59c-47b9-b23e-e611fb3e3a83.png)
You can see that it only performs the assembleAarRelease task,but it generates these files.
![image](https://user-images.githubusercontent.com/18605773/207575716-036dc2e1-32aa-4b57-ad83-8c2bf9ae6859.png)

**Comment by tongzifang** [comment]
![image](https://user-images.githubusercontent.com/18605773/207576163-cfbd9acc-8760-4ffd-b736-551cc6a52259.png)

**Comment by huycozy** [comment]
Hi @tongzifang. This is a known issue #108000 that has been fixed recently and is available on the latest master channel. 

I'll be closing this issue since it has already been fixed on the latest master channel. If you still experience this issue on the master channel, kindly leave a comment below and I will reopen this. Thank you!

**Comment by tongzifang** [comment]
I updated to Channel master (3.7.0-13.0.pre.23 )to solve this problem, but there is a new problem, the debug apk path seems to have problems.
![image](https://user-images.githubusercontent.com/18605773/209259706-b1630e75-b2a9-4895-9725-8f59e6356940.png)

**Comment by tongzifang** [comment]
![image](https://user-images.githubusercontent.com/18605773/209259851-84df9af8-39e4-40eb-ab37-7b829df66735.png)
![image](https://user-images.githubusercontent.com/18605773/209259873-7857db2f-428f-420b-aa82-fc380dc69a33.png)
