### ISSUE TITLE
Improve Focus documentation.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11715]
I wanted to get a simple text field to always have focus and I just couldn't.

I think we need to spend some time documenting this better or giving better examples or something.

**Comment by zoechi** [comment]
Perhaps adding to https://flutter.io/docs/cookbook/forms/focus ?

**Comment by andyxiaoxi** [comment]
> Perhaps adding to https://flutter.io/docs/cookbook/forms/focus ?

This is not  i  want , i want to know how focus is passed.

**Comment by markusaksli-nc** [comment]
Closing this due to the abundance of documentation and examples for [Focus](https://api.flutter.dev/flutter/widgets/FocusNode-class.html), [FocusScope](https://api.flutter.dev/flutter/widgets/FocusScope-class.html), and [FocusNode](https://api.flutter.dev/flutter/widgets/FocusNode-class.html) that has been added.
