### ISSUE TITLE
InputDecoration's iconColor, prefixIconColor and suffixIconColor not working in a TextField

### ISSUE THREAD

**Issue by GP4cK** [flutter/flutter#117129]
## Steps to Reproduce

Same as in https://github.com/flutter/flutter/issues/109654

**Expected results:** The colors of the icons should follow their respective color properties values.

**Actual results:** The icons have the incorrect color.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            decoration: InputDecoration(
              icon: Icon(Icons.ac_unit),
              iconColor: Colors.red,
              prefixIcon: Icon(Icons.abc),
              prefixIconColor: Colors.green,
              suffixIcon: Icon(Icons.add),
              suffixIconColor: Colors.blue,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

This was reported in release 3.0. I'm on 3.3.9 and still have the issue. It works fine on the beta channel though. Was there a regression in the meantime?

**Comment by darshankawar** [comment]
@GP4cK The expected behavior works on latest master and beta:

<img width="323" alt="Screenshot 2022-12-15 at 2 09 27 PM" src="https://user-images.githubusercontent.com/67046386/207812642-1d32d753-652e-4bc2-a2f4-69f43791e072.png">




> This was reported in release 3.0. I'm on 3.3.9 and still have the issue.

The version from 3.0 to 3.3.9 most probably had only cherry-picks and that's why this fix has not reached stable yet. You will have to wait till the next major stable release is pushed which should most probably have this fix. The beta changes will be merged into stable.

Closing, as this is already fixed on latest beta and master.
