### ISSUE TITLE
`insetPadding` should be nullable in dialogs

### ISSUE THREAD

**Issue by art926** [flutter/flutter#117125]
The insetPadding should be nullable and use the default value if you pass null.

**Comment by darshankawar** [comment]
@art926 
Can you provide a use case or example where the property should be nullable is required ?

**Comment by goderbauer** [comment]
@darrenaustin This may have been an oversight when you added the property way-back-then. Any objection to making it nullable and applying the default when it is null just like we do for the other properties?

**Comment by hasnentai** [comment]
@darshankawar  any update on this?
Shall I take it up?

**Comment by darshankawar** [comment]
Feel free to take it up @hasnentai :)

**Comment by hasnentai** [comment]
@darshankawar Thanks for the update.

I can only understand that I @art926 want to make `insetPadding` nullable since it's not nullable 
https://github.com/flutter/flutter/blob/bd7bee0f9eb80625a5db1d8ffc35710dd283215f/packages/flutter/lib/src/material/dialog.dart#L383

I don't know if this makes sense.  Do you have any insight on what exactly @art926 is trying to tell/want

**Comment by HansMuller** [comment]
CC @TahaTesser
