### ISSUE TITLE
Please provide better progress information when building android apps.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#117301]
It is quite frustrating watching a "blank" screen with no turn-indicator or progress info on how far a build for android has come:
![image](https://user-images.githubusercontent.com/11217296/208380492-0ad606aa-f033-4b6b-9f97-c6f3e8af4c81.png)

It may stay for several minutes, during this time yoo could give som info that the build actually is running smooth and good and even how many % it has reached just by counting anticipated steps.

This will give the programmer a hunch to do other things when keeping an eye on the progress... ...instead of being suprised by the fact on what you should watch when the app started, just passed you by...

...Merry X Mas !

**Comment by exaby73** [comment]
Hello @RoarGronmo. If you need more information on what Flutter / Android is actually doing, you can add the `-v` flag to `flutter run` and you'll get verbose information about the commands being run, files being downloaded, etc.

**Comment by RoarGronmo** [comment]
Thanx, just wathced around in the settings, and found this 
![image](https://user-images.githubusercontent.com/11217296/208387083-c845be57-8977-4892-8419-b70b9cb1be6f.png)

This helped !

But visually, there should be a form for progressbar....

**Comment by exaby73** [comment]
When build native android apps, you don't really get a progress bar either. It shows you the same verbose output, but just in a nice UI integrated into Android Studio's build tab. Since Flutter is primarily meant to work on a terminal, it makes sense that the verbose output would look like this.

In order to have a progress bar, Flutter would have to pre compute all the build tasks, from all plugins and your application, beforehand and then estimate the time it would take to build those tasks so that it can show a somewhat accurate progress bar. I my opinion, this does not seem feasible at this point.

Therefore, I am taking a decision to close this issue as, other than looking nice, a progress bar doesn't really give much practical value. For practicality, verbose logging is the best choice. If you disagree with my decision, please comment with your reasoning on it and I may reopen the issue. Thank you
