### ISSUE TITLE
Refactor `TestWindow` and `TestWidgetsFlutterBinding.window` for multi-window world

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#117481]
The `SingletonWindow` these are based on is going away as port of the multi window world. Replacements are `FlutterView` and `PlatformDispatcher`. An app can use multiple `FlutterView`s now. You should still be able to write simple widget tests (unit tests) and not care about windows/views at all.

**Comment by goderbauer** [comment]
@pdblasi-google I filed this as a placeholder issue for the work I talked to you about last week. Let's sync up in the new year to figure out the details.

**Comment by pdblasi-google** [comment]
@goderbauer and I went over some of the specifics of this today, here's the summary of the discussion:

### New APIs

#### `TestView`

We need an API similar to the current `TestWindow` that people can change view specific properties (such as size of the view) for testing. For this a new `TestView` which will implement the parts of `TestWindow` that are not currently covered by `TestPlatformDispatcher`.

`TestPlatformDispatcher` will be adjusted so that any views requested by the application return a `TestView` instead of a regular `View`.

#### `TestWidgetsFlutterBinding.view` & `TestWidgetsFlutterBinding.viewOf`

For the likely most common case of a single view, we will add a `view` property to `WidgetTester` that will return the only `view` in `TestPlatformDispatcher`. If there is more than one view, this property will throw an exception.

There will also be a `viewOf` method that takes a finder and returns the nearest `View` in the widget tree above the result of the finder. This is intended to be similar to the `View.of` API for fetching the nearest `View` while in the app.

### Old APIs

`TestPlatformDispatcher` will be adjusted to return `TestView`s when a `View` is requested.

`TestWindow` and the `TestWidgetsFlutterBinding.window` property will be deprecated. Usages of these will be pointed to the `TestWidgetsFlutterBinding.platformDispatcher` and `TestWidgetsFlutterBinding.view` properties.

### Optional Improvements

Since we're deprecating `TestWindow`, we can take this chance to make setup and teardown of modifiable properties (such as view size) easier. Possibly in a few different ways:

1. `TestPlatformDispatcher` could return new `views` per test, meaning that default values would always be reset.
2. `TestPlatformDispatcher` and `TestView` could store and restore their own modifiable values at the beginning and end of each test respectively.

**Comment by pdblasi-google** [comment]
This had to be reverted due to failures of web tests. Reopening.

**Comment by pdblasi-google** [comment]
Reland was reverted due to failures in google tests. Reopening.

**Comment by pdblasi-google** [comment]
Reland (2) was reverted due to failures in google tests. Reopening.
