### ISSUE TITLE
[flutter] how make texture BoxFit.contain in container, when video size change auto to change UI 

### ISSUE THREAD

**Issue by jzhgithub18** [flutter/flutter#117445]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jzhgithub18** [comment]
when andoroid is screen is change, then the video rotates, I need change the view size(Aspect ratio) in frame.

**Comment by huycozy** [comment]
@jzhgithub18 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
Closing from here as this is more of a `how-to` question rather than a bug or feature request.
