### ISSUE TITLE
[video_player] Null check operator used on a null value "VideoPlayerController._updatePosition"

### ISSUE THREAD

**Issue by furkancetintass** [flutter/flutter#117590]
I see an error log from the video player's _updatePosition method in the sentry.

**Flutter Doctor**
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-arm, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

video_player : 2.4.2

test device : iPhone 14,5 / iOS 16.1.2

**Comment by huycozy** [comment]
@furkancetintass please provide a complete crash log so that we may verify this. 

Also, is this issue reproducible locally when running the project with `release` mode? If so, can you please share the output of `flutter run --release -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
