### ISSUE TITLE
Let'add New Sliver tools

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#117534]
Let's add new sliver tools in Flutter from the box
You can have a lot of setState above and another 1001 stuff that can make your application laggy. And it is hard to find balance sometimes balance between the performance and clarity of your code. Maybe new SliverTools would be good for that for example https://pub.dev/packages/sliver_tools

**Comment by darshankawar** [comment]
Thanks for the report @Hellomik2002 
Since not each and every functionality / feature can be a part of the framework itself, hence there are community packages that helps to bridge the gap and that's why we see the package that you shared exists so that the devs can use it to implement per their requirement. I think it would be good to open the issue / proposal in respective package's repo that can help to achieve your case.
Let me know what do you think of this and it is something ok to do.
