### ISSUE TITLE
Deep linking on Desktop

### ISSUE THREAD

**Issue by ihorkozar** [flutter/flutter#117582]
The documentation doesn't say anything about desktop support : https://docs.flutter.dev/development/ui/navigation/deep-linking

Why was this issue closed ?
https://github.com/flutter/flutter/issues/51350

**Comment by exaby73** [comment]
Hello @ihorkozar. I believe what you're looking for is https://github.com/flutter/flutter/issues/32986. As per https://github.com/flutter/flutter/issues/51350#issuecomment-602843929, that issue was closed. Native deep linking would require Registry edits on Windows (see https://github.com/flutter/flutter/issues/51350#issuecomment-590720802) which is not something that Flutter can do.

There is also a community plugin that handles this (https://pub.dev/packages/uni_links_desktop). Since this issue was closed in https://github.com/flutter/flutter/issues/51350 for the reasons mentioned there, I am closing this issue. Thank you
