### ISSUE TITLE
Unhandled Exception: HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by yeahse** [flutter/flutter#117605]
Flutter Verison 3.3.2

I have 2 Android devices and 2 iPhone devices, and actually 1 device is in use. (I use one that don`t need Wifi)

On Android device, http.get works fine. In IOS, I build through a Mac, but whenever I try to http.get, the following error appears. (The funny thing is that sometimes communication happens. Once in 30 times, once in a while. I don't know why)

`Unhandled Exception: HandshakeException: Connection terminated during handshake
`

my site url is and when call this it gets  error  

`var result = await http.get(Uri.parse(https://my-site.net/v1/some));
`
as you can see the above domain site has "https" and I made this with "GCP Cloud Run"
So it is very secured website (When I click the SSL mark on the website, it shows Google Trust Services LLC)

But because of the above error, I  can`t publish the app now. Every devices work fine on LOCALHOST

Seriously I need a help

**Comment by huycozy** [comment]
Hi @yeahse 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project,
but to improve flutter reporting bugs or feature requests.

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide the output of `flutter doctor -v` as well. 
It will be better if you fill out all the information indicated in the [template](https://github.com/flutter/flutter/issues/new/choose) so that we can address this issue properly. 

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Thank you!

**Comment by yeahse** [comment]
> Hi @yeahse The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.
> 
> If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide the output of `flutter doctor -v` as well. It will be better if you fill out all the information indicated in the [template](https://github.com/flutter/flutter/issues/new/choose) so that we can address this issue properly.
> 
> Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).
> 
> Thank you!

I added the code http.get part

**Comment by huycozy** [comment]
@yeahse Your site above is not available, can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? And please provide affected iOS device information as well. Thank you!

**Comment by yeahse** [comment]
> @yeahse Your site above is not available, can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? And please provide affected iOS device information as well. Thank you!

You can test it with "snailo.net" in IOS then you will be not able to http.get  in any way. and this comment will be deleted I can`t share this domain for longtime and please do not write about this url in future comments

**Comment by huycozy** [comment]
@yeahse When opening that site, I can see it's returned `Status Code: 404` from Network tab (Chrome's Developer Tools). It seems your site issue rather than Flutter itself. Please re-check with the site maintainer/team for this. 

Also, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and issue information needs to be public so that others can see the issue and give the support as well. 

Thank you!

**Comment by yeahse** [comment]
> @yeahse When opening that site, I can see it's returned `Status Code: 404` from Network tab (Chrome's Developer Tools). It seems your site issue rather than Flutter itself. Please re-check with the site maintainer/team for this.
> 
> Also, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and issue information needs to be public so that others can see the issue and give the support as well.
> 
> Thank you!

No that is not a problem that is normal. I didn`t set route on representive url. The problem is . http.get(Uri.parse(mysite)) is not working at all because of above exception

**Comment by yeahse** [comment]
> > @yeahse When opening that site, I can see it's returned `Status Code: 404` from Network tab (Chrome's Developer Tools). It seems your site issue rather than Flutter itself. Please re-check with the site maintainer/team for this.
> > Also, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and issue information needs to be public so that others can see the issue and give the support as well.
> > Thank you!
> 
> No that is not a problem that is normal. I didn`t set route on representive url. (I only set in deepside mysite/v1/someapi) The problem is . http.get(Uri.parse(mysite)) is not working at all because of above exception. And my web server is made with Cloud Run and my domain is set with Google Domains.

**Comment by huycozy** [comment]
@yeahse In this case, the setting at the site was unclear so we could investigate the issue. 

Also, this issue is related to `http` plugin. Please open the issue in that [repository](https://github.com/dart-lang/http/issues) for better support.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!
