### ISSUE TITLE
Get AppGroup container path from path_provider

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#117685]
## Use case

When you use an app extension with Flutter iOS apps, you'll likely want to pass information through an [AppGroup](https://developer.apple.com/documentation/xcode/configuring-app-groups). When using an AppGroup, files can be saved to a shared container between the extension and the app itself. However, you currently need to use a method channel to get the path to the container [(with this API call).](https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl) 

## Proposal

It would be great to add this to the path_provider plugin. So you can do something like the following:

`Directory myFilePath = await getContainerPath("my_app_group");`

**Comment by stuartmorgan** [comment]
For this API, we should use the new style of adding platform-specific APIs in the platform package (so, a new public method in `path_provide_ios`/`path_provider_macos`) instead of the legacy approach of adding APIs that are fundamentally platform-specific to the app-facing package.

We probably want to merge `path_provider_ios` and `path_provider_macos` into a shared Swift implementation (which is something we've already discussed doing now that 1P iOS plugins can be Swift-based)  first so we only have to add it in one place.
