### ISSUE TITLE
Fine-tune fling velocity

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11772]
There's a slight difference in velocity reported by iOS's pan gesture recognizer's velocityInView vs our own VelocityTracker. Flutter's calculation is ~20% faster. 

On Android, the velocity tracker is distinct from the gesture callbacks, but our flings are a bit slower. 

Probably better to have a platform agnostic velocity and correct the difference in the friction simulations.

**Comment by Hixie** [comment]
I've tentatively put this at post-1.0 but we can bring this back if people notice.

**Comment by xster** [comment]
Agreed. I think it's lower prio than the last 4 we dealt with so far.

**Comment by eseidelGoogle** [comment]
This came up in a review from an internal team today.  I presume this shows up in:
https://github.com/flutter/scroll_overlay

**Comment by eseidelGoogle** [comment]
@xster do we know if this is still an issue?  Has anyone played with scroll_overlay recently to tune our physics further?

**Comment by xster** [comment]
As of last time I checked in spring, it is still and issue. This and https://github.com/flutter/flutter/issues/13171 are the 2 remaining scrolling related issues I know of.

I left them deprioritized and not slated for [Q3-Q4](https://github.com/flutter/flutter/projects/9) since I don't think they're noticeable enough. Let me know if that should change or if anyone is blocked on it.

**Comment by molon** [comment]
It's still and issue. 
I feel `ListView` has too much friction when deceleration on iOS.
But `https://github.com/xster/flutter-test/tree/master/t95_ios_settings_page` performs well.
Is this my illusion?

I went deep into the source code, and they all used the same `ScrollPhysic`. 
Really don't know why.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/platform_tests contains a project one can use to test ListView against an iOS scroll physics if you'd like to confirm.

**Comment by molon** [comment]
Very useful tests.

Three problems can be clearly seen from the test:
- Flutter scrolls faster
- Flutter does not align with iOS when holding down the drag
- They scroll stop at different times. Flutter stops earlier

As a iOS developer.
Based on my development experience, we hardly need a `Cupertino` UI.
But something is important:
- Standard dimension. eg: NavigationBar with 44.0. Although I can use `AppBar+PreferredSize` to implement it.
- The scroll experience.
- The transaction. Especially pan to swipe back. I have tried it in `t95_ios_settings_page`, It's also a little weird.

Few users like a `Cupertino` UI. Because design should be diverse.
But most users hard to tolerate app with inconsistent interactions.

So I still prefer to use `MaterialApp` and I'm not going to use `CupertinoApp`.
I guess there will be a lot of iOS developers like me.
So I suggest that Flutter should pay more attention to interactions instead of `CupertinoUI`.

**Comment by xster** [comment]
Users building custom designs is indeed our vision though we've recently focused on building an extensive set of Cupertino widgets based on our [quarterly survey results](https://medium.com/flutter-io/how-we-use-user-surveys-to-prioritize-engineering-effort-in-flutter-october-2018-edition-a26e45abf5aa). Note also that the Material/Cupertino interest ratio is also skewed between China and the rest of the market. 

I do agree this is important however. We just haven't fine tuned it because no one noticed so far :) (as mentioned above). It shouldn't be difficult to do and it's in our plans for Q2. You can also send us a PR based on that comparison test.

**Comment by LongCatIsLooong** [comment]
Looked into this (prompted by #59623). `UIPanGestureRecognizer` uses a far smaller sample size to calculate the velocity.
