### ISSUE TITLE
New Data Types

### ISSUE THREAD

**Issue by OSonntag** [flutter/flutter#117704]
## Proposal

Add new data types like phone, domain, address and email into darts type system. I know you can store those in strings and do a lot of validation yourself. But if there where a central authority like the dart/flutter team that would maintain theses types it would erase a lot of hurdle from the developers figuring out to validate those values correclty.
```
String t = 'a string';
Phone x = '+491234234'; // a phone
Phone z = 'csbed'; // throws exception (not a valid phone number)
```

**Comment by stuartmorgan** [comment]
Requests for new classes in the Dart SDK would need to be filed at https://github.com/dart-lang/sdk rather than the Flutter issue tracker.

(I would recommend when filing there to explain why you believe they need to be part of the core SDK itself rather than packages. The reason for a package system is to allow shared code like this without everything having to be built in.)
