### ISSUE TITLE
Documentation request for Stepper Class

### ISSUE THREAD

**Issue by chrislondon** [flutter/flutter#11789]
At the moment I'm blindly making a stepper and experimenting with the settings. Documentation would greatly speed up my efforts.

**Comment by eseidelGoogle** [comment]
It looks like we have some minimal docs:
https://docs.flutter.io/flutter/material/Stepper-class.html

But no Example or sample:
https://flutter.io/catalog/samples/
https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=stepper&type=

It's possible @nisrulz already has one: https://github.com/nisrulz/flutter-examples

**Comment by Hixie** [comment]
@chrislondon If you have specific questions you'd like answered which the docs don't currently answer please list them explicitly here, then when we add docs we'll make sure to explicit answer the specific questions you list here (along with anything else we can think of). It's often really hard to write good docs without a prompt. :-)

**Comment by nisrulz** [comment]
@eseidelGoogle I actually didn't have the example for Stepper. But it was easy to implement, I saw this and update my [flutter-examples repo](https://github.com/nisrulz/flutter-examples)

@chrislondon this example should help you out with managing the state of the Stepper Widget, have a look at code here

https://github.com/nisrulz/flutter-examples/blob/master/using_stepper/lib/main.dart

> I have added comments in there, but if you have any questions please let me know  😺

**Comment by sethladd** [comment]
There are many Steppers defined in https://material.io/guidelines/components/steppers.html, we could specifically document which Stepper(s) is implemented by https://docs.flutter.io/flutter/material/Stepper-class.html 

I'd also love a screenshot for https://docs.flutter.io/flutter/material/Stepper-class.html to help me understand what kind of stepper this is.

For example, do we show dots? Progress bar?

**Comment by nisrulz** [comment]
@sethladd I have working gifs in my example app [here](https://github.com/nisrulz/flutter-examples/tree/master/using_stepper), showing 2 possible ones as of now.

**Comment by sethladd** [comment]
Thanks! Would you be willing to send a PR to update and clarify the API docs for https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/stepper.dart#L128 ?

**Comment by chrislondon** [comment]
I would love the following Material specs to be implemented:
![screenshot from 2017-10-11 15-34-15](https://user-images.githubusercontent.com/889164/31468167-df954f32-ae99-11e7-93c4-8b67d52c4a6d.png)
![screenshot from 2017-10-11 15-34-26](https://user-images.githubusercontent.com/889164/31468168-dfac1604-ae99-11e7-8069-2a8187fa703f.png)
![screenshot from 2017-10-11 15-34-37](https://user-images.githubusercontent.com/889164/31468169-dfc15a46-ae99-11e7-9f72-16fa716031a8.png)

**Comment by sethladd** [comment]
@chrislondon apologies, but would you be willing to comment on https://github.com/flutter/flutter/issues/12500 or open a new issue specifically for "stepper with progress bar" ?

This issue is about updating the API docs in Stepper to better clarify what kinds of steppers we currently implement.

Sorry for the confusion here... we thank you for your feedback!

**Comment by nisrulz** [comment]
@sethladd I could do that sometime towards the EOD. Can't promise though 😅

**Comment by sethladd** [comment]
Today or tomorrow.. either works :) Thanks!!

**Comment by nisrulz** [comment]
@sethladd Just wanted to clarify, the only update I need to be sending as a PR has to be dartdoc comment mentioning the kinds of steppers flutter currently implements, at the line you [earlier linked](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/stepper.dart#L128)?

Since there isn't any example for Stepper, should I add that too [here](https://github.com/flutter/flutter/tree/master/examples)?

Thank you

**Comment by sethladd** [comment]
@nisrulz at a minimum, please update the API docs for the Stepper class to be specific about which kinds of steppers one can use.

A bonus would be a small snippet of code in the API docs for the Stepper class, which shows how to use Stepper class for the various configurations/types.

All this would be in a single PR.

Other PRs can add examples and links, perhaps to our Sample catalog.

Thank you!

**Comment by Shantanu-Kotambkar** [comment]
**_### I was able to implement horizontal mode for stepper, and making it look good after customizing the widget. Here is a screenshot, I added some icons to display stepper state, instead of building circle, or triangle._** 

![screenshot_2018-08-16-15-01-49-093_com example stepper](https://user-images.githubusercontent.com/31074292/44229526-56cfdf80-a166-11e8-99b0-86c0311393a1.png)

**Comment by lukasgit** [comment]
@Shantanu-Kotambkar do you have example code for how you implemented horizontal mode for stepper? Thanks!

**Comment by TahaTesser** [comment]
Looks like Stepper Class documentation exist now https://api.flutter.dev/flutter/material/Stepper-class.html 

There are definitely improvements needed in the doc but it does exist so i am closing this issue and for improvements, please created new issue
