### ISSUE TITLE
App Crashing while using in Android

### ISSUE THREAD

**Issue by akshaynjarangal** [flutter/flutter#117893]
## Details

App Crashing while using , App not exiting , but freezing frame, then terminate and open appeasing 20-30 seconds repeating the issue. App performance report JSON added in the Logs.
**Target Platform:** Android
**Target OS version/browser:** 10,11,12
**Devices:** Moto,POCCO,Mi(Xiaomi ,Redmi)

## Logs

<details>
<summary>Logs</summary>

[dart_devtools_2023_1_3-1672743579230000.json.zip](https://github.com/flutter/flutter/files/10336144/dart_devtools_2023_1_3-1672743579230000.json.zip)

```
```

</details>

**Comment by huycozy** [comment]
@akshaynjarangal Please provide the output of `flutter doctor -v`.

Also, is there any specific log from the console? If so, please provide the output of `flutter run -v` so that we may verify the issue. If the log is too long, please save it into a file and attach it here same as your above devtools JSON file. 

Otherwise, I would suggest you keep an eye on it and find the related screen/module that may cause the issue and  provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Thanks!

**Comment by akshaynjarangal** [comment]
> @akshaynjarangal Please provide the output of `flutter doctor -v`.
> 
> Also, is there any specific log from the console? If so, please provide the output of `flutter run -v` so that we may verify the issue. If the log is too long, please save it into a file and attach it here same as your above devtools JSON file.
> 
> Otherwise, I would suggest you keep an eye on it and find the related screen/module that may cause the issue and provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
> 
> Thanks!

```
flutter doctor -v
```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Users/akshayn/project/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/akshayn/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • moto e32 s (mobile)         • adb-ZD2225YKWK-yUjhsX._adb-tls-connect._tcp. • android-arm64  •
      Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554                                • android-arm64  •
      Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos                                        • darwin-arm64   •
      macOS 13.1 22C65 darwin-arm
    • Chrome (web)                • chrome                                       • web-javascript •
      Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by akshaynjarangal** [comment]
Issue facing in working big project , I can't share the code

**Comment by huycozy** [comment]
@akshaynjarangal 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.

So, please don't share your project code and access [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) for more information.

Also, without additional information, we are unfortunately not sure how to resolve this issue. So please try providing more information as [suggested above](https://github.com/flutter/flutter/issues/117893#issuecomment-1369676197) so that we may verify it. Thanks!

**Comment by akshaynjarangal** [comment]
ok @huycozy , I will give

**Comment by akshaynjarangal** [comment]
Hey @huycozy , are you checked the above output.txt

**Comment by huycozy** [comment]
@akshaynjarangal As I can see, the above log doesn't contain hints/clues that can help to investigate. And we also can not verify the issue with apk file. 

If your app has crash but there is no crash log from the console (Flutter side), you may use `adb logcat` to track it, then let's find and share the crash here. For eg:

```
adb logcat | grep -F "`adb shell ps | grep <your package name here>  | tr -s [:space:] ' ' | cut -d' ' -f2`"
```
