### ISSUE TITLE
IconButton's icon gives wrong color when IconThemeData.color when useMaterial3 is true

### ISSUE THREAD

**Issue by Eimji** [flutter/flutter#117859]
Hello

This issue https://github.com/flutter/flutter/issues/110644 is still in the stable branch.

Could you please merge the fix, as announced in the thread, into the stable branch of Flutter? I need to update my applications and I would like to avoid using the master branch as it often breaks my code (mainly the code related to UI parts).

Thank you in advance.

**Comment by darshankawar** [comment]
> Could you please merge the fix, as announced in the thread, into the stable branch of Flutter? I need to update my applications and I would like to avoid using the master branch as it often breaks my code (mainly the code related to UI parts).

@Eimji It is not actually just about merging the fix in stable straightaway. The team has a set policy which is mentioned in this [document](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#stable). Basically, if issue is fixed in master and beta, then those fixes are most likely to be landed in stable release which happens once in quarter. So please be patient and let's wait for next stable release announcement or build in which this issue most likely will be available.

Closing this for now.
