### ISSUE TITLE
video_player issues on Android, no 4k, crashes with large files @50mbit

### ISSUE THREAD

**Issue by mranderson02005** [flutter/flutter#118148]
I'm trying to recreate my android app in flutter, however the video_player which is based on exoplayer is having major issues with high quality video files.

I have made sure that it is in a mp4 container, and confirmed I am getting 4k playback on an android device running android 9, which is a odroid n2 device. The file is stored locally and accessed the .file in the code instead of asset. I am using the example listed on github. 

When trying to play via the video_player package, the video plays for 5 secs then crashes. In the logs it is trying to do a lot of GC and after several tries it runs out of memory. Also the video is not displayed in 4k but looking rather fuzzy, most likely the entire project is in hd. 

Are there any plans to fix this implementation of exoplayer or perhaps use the standard videoplayer of android? In a native app the performance is stellar.

**Comment by huycozy** [comment]
Hi @mranderson02005 
Please provide the information indicated below so that we may verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). In case you are using video_player sample code, please provide a snippet code which you've updated and also providing the resource files if any.
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- The version of `video_player` plugin

Thank you!
