### ISSUE TITLE
PieChart-ArcRendererConfig

### ISSUE THREAD

**Issue by guobihai** [flutter/flutter#118175]
```
RenderBox was not laid out: RenderSemanticsGestureHandler#a3283 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1927 pos 12: 'hasSize'
```

run
 ```
return charts.PieChart(
      seriesList,
      animate: true,
        defaultRenderer: charts.ArcRendererConfig(
            arcWidth: 5,//这里是弧的宽度，当我们的宽高较小，而这个较大的时候，我们的饼状图就是实心的，否则就是空心的。可以自己设置
            arcRendererDecorators: [
              charts.ArcLabelDecorator(
                labelPosition: charts.ArcLabelPosition.inside,
                insideLabelStyleSpec:
                charts.TextStyleSpec(fontSize:8, color: charts.Color.white),
              )
            ])
    );
```

**Comment by darshankawar** [comment]
@guobihai 
Looking at the code, you seem to be using third party plugin for charts, so ideally you'll need to report this issue in plugin's dedicated repo. Closing for now.

If you are able to replicate the same error `Failed assertion: line 1927 pos 12: 'hasSize'`, without using any third party package and only using the framework code, write in comments with relevant details such as `flutter doctor -v` and minimal code sample so that we can take a look at it.
