### ISSUE TITLE
iOS network device not selected when running/debugging in VSCode

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#118113]
## Steps to Reproduce
Requires this PR https://github.com/flutter/flutter/pull/118104.

1. Setup network device (see https://github.com/flutter/flutter/pull/118104 for instructions)
2. Open any flutter app in VSCode
3. VSCode > Run > Start Debugging or VSCode > Run > Run Without Debugging

**Expected results:** 
Expect it to run flutter on network device.

**Actual results:** 
Runs flutter in a mac application.

**Comment by jmagman** [comment]
Once https://github.com/flutter/flutter/pull/118104 is done I think it should show up in the list?  The IDEs are running `flutter` under the covers (via `flutter daemon`).

**Comment by vashworth** [comment]
I believe the issue is that it times out before it can find it. Assuming [the PR ](https://github.com/flutter/flutter/pull/118104) is merged in, it would still occur. I was able to workaround with the below solution, but I don't think it's a good long-term solution.

Workaround: VSCode > Run > Add/Open Configuration, add `--device-timeout 5` as arg to default configuration (see below)
```
{
   ...
   "configurations": [
      {
          "name": "my_app",
          "request": "launch",
          "type": "dart",
          "args": ["--device-timeout", "5"]
      },
      ...
  ]
}
```

**Comment by vashworth** [comment]
This issue kind of goes hand in hand with this one: https://github.com/flutter/flutter/issues/118109

**Comment by jmagman** [comment]
I think it would eventually show up in the IDE devices list because the `daemon` devices command is calling down into `xcdevice observe --both` which doesn't time out.
https://github.com/flutter/flutter/blob/aba0c4e6f6d26e3363cab778b66875023e15619f/packages/flutter_tools/lib/src/macos/xcdevice.dart#L164-L166
So that means `-d` is passed in, but `flutter run` isn't waiting long enough.  

One idea would be to re-think device discovery during run/drive so when `--device-timeout` isn't passed in, it tries the short `xcdevice list`, then falls back to `xcdevice observe` in the same way until some matching device of any type _is_ found.  And it doesn't time out for say minutes, but does periodically output something like "No matching devices found, did find ..." with the devices output.

**Comment by jmagman** [comment]
> when `--device-timeout` isn't passed in, it tries the short `xcdevice list`,

This would also help run times for the non-wireless case since the default now it 2s but a timeout that long shouldn't be necessary for the USB tethered devices.
