### ISSUE TITLE
[image_picker_web] Proposal to make resizeImageIfNeeded a public function. 

### ISSUE THREAD

**Issue by michalkubizna** [flutter/flutter#118151]
Use case:
I'd like to store multiple copies of the same image in different sizes. Currently, it is only possible to resize a single image (the one I have selected)

**Comment by darshankawar** [comment]
@michalkubizna 
Can you try the `imageQuality` property that gives you the compressed image and see if it serves your purpose?

https://github.com/flutter/plugins/blob/0a0e3d205ca32fdeebe237262e6ac824b3f3d51f/packages/image_picker/image_picker/example/lib/main.dart#L99

**Comment by stuartmorgan** [comment]
> make resizeImage a public function

What is this referring to specifically? There is no `resizeImage` method in `image_picker`.

**Comment by michalkubizna** [comment]
I was referring to the resizeImageIfNeeded function in the image_picker_for_web package.

**Comment by darshankawar** [comment]
https://github.com/flutter/plugins/blob/fb405819ec9524e74f772d48a5945bea0db633bb/packages/image_picker/image_picker_for_web/lib/src/image_resizer.dart#L18

Keeping this issue open and treating as potential proposal.

**Comment by stuartmorgan** [comment]
`image_picker` isn't intended to be a generic image processing tool; `resizeImageIfNeeded` is an internal implementation detail of the functionality needed to support the public API (which includes resizing at all because on some platforms it would be inefficient to do it as a separate step later).

If you want to do your own image processing, you should use code intended to serve that generic use case.
