### ISSUE TITLE
Error: The argument type 'Future<dynamic>' can't be assigned to the parameter type 'void Function()?'

### ISSUE THREAD

**Issue by JdotDEV** [flutter/flutter#118152]
While making Password Reset page, using FireBase Auth.It shows an error:-

Error: The argument type 'Future<dynamic>' can't be assigned to the parameter type 'void Function()?'.
lib/pages/forgot_pw_page.dart:82
 - 'Future' is from 'dart:async'.
                  onPressed: passwordReset(),

Where I am doing wrong??

Code:

(I have trimmed the code, as it was not allowing to post whole)

class ForgotPasswordPage extends StatefulWidget {
  const ForgotPasswordPage({super.key});

  @override
  State<ForgotPasswordPage> createState() => _ForgotPasswordPageState();
}

class _ForgotPasswordPageState extends State<ForgotPasswordPage> {
  final _emailController = TextEditingController();

  @override
  void dispose() {
    _emailController.dispose();
    super.dispose();
  }

  Future passwordReset() async {
    await FirebaseAuth.instance.sendPasswordResetEmail(email: _emailController.text.trim());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[300],
      body: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 25),
                child: MaterialButton(
                  onPressed: passwordReset(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by navaronbracke** [comment]
The `onPressed` argument of the `MaterialButton` widget expects a `void Function()`.
Your `passwordReset()` function returns a Future.
However by doing `onPressed: passwordReset()`, you actually call the function and pass the result, instead of passing in the function itself.

The correct way of doing this would be 
a) If `passwordReset()` returns a `Future<T>` you can use a lambda
```
onPressed: () async {
 await passwordReset();
}
```
b) If `passwordReset()` returns `void` you can use a tear off, i.e. `onPressed: passwordReset,` (no parentheses)

It is also a good practice to define the generic type of `Future<T>` so that you know what it returns when it is `await`ed.
In your case that could be `Future<void> passwordReset() async { ... }`, although I don't know if the function actually returns something else.

Since this is not a problem with Flutter itself, please do ask such help related questions on a dedicated help forum such as Stackoverflow or the `#help` channel on the Flutter Discord in the future.
