### ISSUE TITLE
flutter/plugins should have guidelines for inclusion

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11823]
Currently flutter/plugins is just plugins which have been authored by the Flutter team at Google.

Others may wish to contribute additional plugins, and we should write down some best practices.  For example: https://github.com/flutter/plugins/pull/203

My suspicion is that we should make it very easy for others to maintain their own plugin repositories instead of adding many more plugins to flutter/plugins.

Thoughts @mit-mit @Hixie

**Comment by Hixie** [comment]
I thought the idea was that flutter/plugins is just for first-party plugins.

**Comment by mit-mit** [comment]
Yes, this is intended only for first party.

You should be able to put plugin sources in any GitHub repo. 

I'll update the readme to make this clearer

**Comment by eseidelGoogle** [comment]
sgtm.  Please (kindly) make that clear both in the readme and the outstanding PR for BLE. :)

**Comment by mehmetf** [comment]
@mit-mit 

How do we plan to help people looking to do X in Flutter where X is a *common thing to do*?
What if I search pub for X and turns out there are 4 plugins that do it. How do I know which one to use?

Does it make sense to have a list of Flutter endorsed plugins where we either host them in the flutter/plugins repo? or we expose them in some page on flutter.io?

**Comment by sethladd** [comment]
cc @kevmoo who is working on this :)

**Comment by kevmoo** [comment]
It is on our list!
