### ISSUE TITLE
Customer test CI in flutter/tests is failing in the Cirrus Mac environment

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#118258]
The flutter/tests repository runs CI jobs to verify that the customer tests have not regressed.

The CI job for the Mac platform is running on Cirrus, and the job started failing when Cirrus dropped support for Intel Macs.

I have a proposed PR to move the job to an M1 Mac environment (see https://github.com/flutter/tests/pull/204).  This mostly works, but one of the customer tests (DanTup_tiler) is doing golden image checks that are failing on the M1.

We need to get all the tests working on Cirrus and complete the migration to M1.  Or alternatively move this CI job to LUCI.

**Comment by zanderso** [comment]
cc @DanTup

**Comment by DanTup** [comment]
[geometry_orthogonal_macos.zip](https://github.com/flutter/flutter/files/10392218/geometry_orthogonal_macos.zip)

There seems to be a 2-byte difference in a single golden when I run on an M1. Is this a bug or expected? If it's expected that goldens may vary between Intel and ARM Macs, I'll need to change the tests to use unique filenames for each. This isn't difficult (it may require calling something like `uname -m`) but I'd like to know that's the right way (and this isn't an unexpected bug).

It would probably be really nice if Flutter exposed some "platform name" to be included in golden filenames that matches its expectations for where goldens should be the same. Currently I'm manually using `Platform.operatingSystem` in the filenames (because of differences between OSes) but if Intel/ARM Macs are not guaranteed to be the same it's no longer sufficient (and having all users handle this to make their tests cross-platform seems awkward).

**Comment by DanTup** [comment]
@jason-simmons @zanderso any thoughts on the above?

**Comment by DanTup** [comment]
Sorry, I had misunderstood the output. There is 2-bytes difference in filesize, but it's not only two bytes difference in the files - there are additional differences. I attached both files in a zip file in my comment above.

Comparing the files in GitHub desktop it looks like the red lines are slightly thicker in the M1 version (left part here is Intel, right is M1):


![image](https://user-images.githubusercontent.com/1078012/213239878-1289f508-5517-41aa-90b1-6f2c6ec62e52.png)

**Comment by zanderso** [comment]
@chinmaygarde is it expected that there could be differences in output from the Skia software backend between Intel and M1?

**Comment by chinmaygarde** [comment]
There isn't a guarantee about the pixels being identical.

**Comment by DanTup** [comment]
In that case, is it possible Flutter could provide some utility here? If users want to use goldens and run tests on multiple platforms, they need to know where goldens are expected to be the same. Previously it seemed to be just based on the OS, but now I guess it's a combination of OS and CPU architecture.

It would be really helpful to have some kind of "golden suffix" provided by Flutter that provides a suffix that differs in environments that should have different goldens. Otherwise users will need to do this themselves (and have to understand the rules), which likely means spawning something like `uname -m` on Mac, but presumably Dart/Flutter already know what their architecture is (as far as I can tell, there's no exposed API for Dart to get this?).

**Comment by DanTup** [comment]
I've a PR here that separates M1/Intel goldens on macOS:

https://github.com/flutter/tests/pull/214
