### ISSUE TITLE
stateful widget error, A constant constructor can't call a non-constant super constructor of 'State'.

### ISSUE THREAD

**Issue by CrazyBunnyz** [flutter/flutter#118311]
here is my public git.
https://github.com/CrazyBunnyz/Sociominer_V2/
there are 2 branches on that git.
the main is my original code with stateless for most of the part. the problem comes when I try to integrate my code with ExpansionTile where I need state to detect on onExpansionChanged. i try to implement the example but I keep getting the error below. can anyone please help. you can see both code before and after the error from both branches.
![image](https://user-images.githubusercontent.com/52201618/211786694-4b851440-3949-4051-bdcd-e1dfea57a08f.png)

**Comment by exaby73** [comment]
Hi @CrazyBunnyz
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

PS: this can be fixed by removed `const` before `ChatMember` on line 14. Updated code should look like:

```dart
ChatMember({Key? key, this.deviceScreenType}) : super(key: key);
```

This is working as intended

**Comment by CrazyBunnyz** [comment]
thank you, i already try your suggestion before posting this but it return other error.
![image](https://user-images.githubusercontent.com/52201618/211798772-63584029-3c95-4881-a853-277eeedd550d.png)
on other part after fixing it like this 
![image](https://user-images.githubusercontent.com/52201618/211799258-9306a0c6-7a1a-4cb4-a299-04ea6ccd0637.png)

**Comment by CrazyBunnyz** [comment]
ill try to post it on stackoverflow as well, hope it will be solved soon. thanks

**Comment by exaby73** [comment]
You need to use `MyStatefulWidget` instead of `ChatMember`. `ChatMember` is a `State`, not a `Widget`
