### ISSUE TITLE
Consider adding installation instructions for cocoapods to flutter doctor

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#118389]
Currently, if you don't have cocoapods installed when running `flutter doctor` you get this output:

```
CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
```

However, the linked instructions say to use `sudo gem install cocoapods` - which doesn't seem to work for M1 macbook. I was able to install using homebrew instead, so we might want to incorporate that into flutter doctor output or the installation docs: https://docs.flutter.dev/get-started/install/macos#ios-setup

`brew install cocoapods`

**Comment by jmagman** [comment]
We used to have instructions in the tool, but there was no exactly the right command for every given environment. For example sometimes you want `sudo`, sometimes you don't, `brew` shouldn't be required at all but if the user wants to they can.  Removed in https://github.com/flutter/flutter/pull/68542.  Updated the website at https://github.com/flutter/website/pull/4662.

See https://github.com/flutter/flutter/issues/65131 and https://github.com/flutter/flutter/issues/10122#issuecomment-699034668.

It was really annoying fielding all the "the command doesn't work for me" issues people filed and I don't want to go back to that 🙂.  I prefer "Flutter iOS development requires a Mac, Xcode, and CocoaPods, install them, here's a link to their install pages" instead of us trying to come up with all the corner cases and encode them in the tool.

Did the Apple Silicon instructions in the note https://docs.flutter.dev/get-started/install/macos#deploy-to-ios-devices not work for you?  It did on my machine but again the instructions maybe be different for different environments, emphasizing my point about maybe us not being in the job of giving precise instructions for how to install our dependencies for all cases.
```
  $ sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc
```
<img width="846" alt="Screenshot 2023-01-13 at 1 09 17 PM" src="https://user-images.githubusercontent.com/682784/212419513-ec71d519-a6db-4d4b-a4ea-d6e5fca7e5f3.png">
