### ISSUE TITLE
Contains invalid characters during print - ascii.dart

### ISSUE THREAD

**Issue by gvsakhil** [flutter/flutter#118428]
## Steps to Reproduce

1. We are using the following package for print - https://pub.dev/packages/esc_pos_printer
2. When we print the following words its throwing an error saying - Contains Invalid Characters
3. This is because of following string: Konaseema Paneer Biryani – with Veggies

Description:
1. If you observe the string carefully "-" is very huge in above string
2. Konaseema Paneer Biryani – with Veggies (Original String Present) vs Konaseema Paneer Biryani - with Veggies (String typed by me which has very small "-")
3. This big "-" is causing the issue and breaking the flutter app during print
5. If you ask me how you got the big "-"? Employees in the hotel generally copy paste names from internet (May be this bought us that big "-")

The reason for posting the error in flutter channel instead of esc_pos_printer is - The issue is from ascii.dart which is part of flutter team, so I thought this would be right place for this bug.

![WhatsApp Image 2023-01-12 at 8 11 46 PM](https://user-images.githubusercontent.com/40195211/212227836-ea6ced2c-87be-434a-9a6b-07ff6c6375ce.jpeg)

**Comment by stuartmorgan** [comment]
An `ArgumentError` indicates that the API is being called incorrectly, not that there's a bug in the implementation of the API. In this case you appear to have passed a non-ASCII string to code that expects ASCII; the issue is at whatever layer that is happening (which there's not enough description here to know; it could be your code, or the library you are using), not in `dart:convert`.
