### ISSUE TITLE
IOS component only have .podspec, how to take?

### ISSUE THREAD

**Issue by wumengm** [flutter/flutter#118424]
My IOS Native component want to take The FlutterModule,But Then component only have .podspec。So I am generate FrameWorks，In .podspec write ' s.vendored_frameworks   = 'flutter_boost.xcframework'. But Only component The same use，Submitted Some error What repeat frameworks.I find The frameworks Only deposit at current component directory.

**Comment by darshankawar** [comment]
@wumengm 
We are not sure what exactly is the issue are you reporting because the description you gave is very unclear. When you are opening an issue in flutter repo, please try to use one of the templates and provide requested details so that we will have enough details to work with.
Also, looking at the description, I think your question is better suited for support channels like StackOverflow so please ask the same there. 
If you disagree or have found a bug in the framework, please use new issue template as mentioned above.
Closing for now due to lack of details and unclear description.
