### ISSUE TITLE
[image_picker] Android gets the application list through queryIntentActivities

### ISSUE THREAD

**Issue by mlf2020** [flutter/flutter#118495]
![image](https://user-images.githubusercontent.com/12659293/212459670-d4ca6300-e262-4011-87ac-18dbe6007384.png)
Relevant Chinese laws stipulate that methods related to obtaining the application list cannot be used, please rectify

**Comment by darshankawar** [comment]
@mlf2020 
Can you provide the stacktrace in properly formatted text instead of in screenshot ?

Also, can you elaborate on and provide what should be the expected behavior ?


> Relevant Chinese laws stipulate that methods related to obtaining the application list cannot be used, please rectify

Seems to be coming from https://github.com/flutter/plugins/blob/eda98cddb57f35c1a4f4489942cd40d0f2bd7338/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L418
