### ISSUE TITLE
regression: `text_canvaskit_layout.canvaskit.multi_line.getBoxesForRange.average`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#118460]
The skia roll at https://github.com/flutter/flutter/pull/118432 has caused a regression of 25% in `text_canvaskit_layout.canvaskit.multi_line.getBoxesForRange.average`

## skiaperf

https://flutter-flutter-perf.skia.org/e/?begin=1673574904&end=1673623515&keys=X7134ace58332d04d61af2a8b237fe871&num_commits=50&request_type=1&xbaroffset=32849

**Comment by yjbanov** [comment]
We decided we're going to keep this temporary small regression in exchange for a better designed API that does not rely on monkey patching core JavaScript objects, and for enabling dart2wasm (which does not support monkey-patching). We incur the cost of a wrapper object to attach extra data. This is temporary because once we're running fully in wasm mode, the overall performance will improve based on our early benchmark data (not on Skia perf yet).
