### ISSUE TITLE
SliverAppBar's title color does not match FlexibleSpaceBar title's color.

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [flutter/flutter#118545]
Using the same `Text` widget in the `SliverAppBar` and `FlexibleSpaceBar` yields different results. The `SliverAppBar`'s `title` widget inherits its color from the theme configuration whereas `FlexibleSpaceBar.title` does not.

To demo the issue I've set both the `SliverAppBar.title` and `FlexibleSpaceBar.title`. In practice only one of these would be set.

## Steps to Reproduce

**Expected results:** The color of the `SliverAppBar.title`'s text and `FlexibleSpaceBar.title`'s text should match.

**Actual results:** 
The text colors are different.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/4954611/212600660-9d7b8c9e-51de-45ed-965f-6f57973f1d75.png">

<details>
<summary>Code sample</summary>

```dart
class MyPage extends StatelessWidget {
  const MyPage({super.key});
  @override
  Widget build(BuildContext context) {
    const titleText = Text(
      "heading",
      textAlign: TextAlign.center,
      maxLines: 1,
      overflow: TextOverflow.ellipsis,
    );

    return const CustomScrollView(
      slivers: [
        SliverAppBar(
          title: titleText,
          pinned: true,
          expandedHeight: appBarHeight,
          flexibleSpace: FlexibleSpaceBar(
            title: titleText,
          ),
        ),
      ],
    );
  }
}
```
</details>

**Comment by TahaTesser** [comment]
Hi @Petri-Oosthuizen 
This is an expected behavior. Widgets inside `FlexibleSpaceBar` don't inherit AppBar's default colors like`foregroundColor` while the `SliverAppBar.title` uses default` foregroundColor`. 

Widgets in `FlexibleSpaceBar` have more flexibility when theming. They can contain text, images, or anything else. 

If you wanna the match the text inside `FlexibleSpaceBar` use the same color as the `SliverAppBar.title` color. You can provide `AppBarTheme.of(context).foregroundColor` to the text widget inside `FlexibleSpaceBar`  and set a color in your  `AppBarTheme`.

Closing. Please comment below if you have any further questions.
