### ISSUE TITLE
Errror while using AutomaticKeepAliveClientMixin with the child widgets of listView.builder.

### ISSUE THREAD

**Issue by nileshmsd12345** [flutter/flutter#118506]
## Steps to Reproduce

```
ListView.Builder(
shrinkWrap:true,
builder(_,i)=> GroupChatTile()
)

class GroupChatTile extends StatefulWidget {


  const GroupChatTile({
    Key? key,
  }) : super(key: key);

  @override
  State<GroupChatTile> createState() => _GroupChatTileState();
}

class _GroupChatTileState extends State<GroupChatTile>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    final prefHelper = GetIt.I.get<SharedPreferenceHelper>();
    final currentUserId = prefHelper.userId;
    super.build(context);
    return Container(
  
    );
  }

}

```

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@nileshmsd12345 
Looking at the code sample, you seem to be using third party package `Get`. In order for us to verify this issue is coming from framework itself, we would need complete minimal reproducible code sample without any third party plugins. Also, when you open an issue and are using a template, please try to fill it out completely so that we will have enough information to work with.

Closing for now, as there's lack of details.
