### ISSUE TITLE
Flutter keep eating my hard disk space.

### ISSUE THREAD

**Issue by CrazyBunnyz** [flutter/flutter#118557]
just like the title, i dont mind deleting manually but is there any documentation where they list all the file that can be erased to restore disk space, or maybe changing the directory used for testing ( from C to D ) ? anyone facing the same problem ?

**Comment by ps6067966** [comment]
For Window press =>  window key + r and type %temp% and then okay, delete everything on that folder.

**Comment by huycozy** [comment]
@CrazyBunnyz 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

In this case, please help to clarify the issue by providing information in detail:

Which directories/files in your project are taking up a lot of your disk space? When you observe the disk space increase, which circumstance does it happen in? (when adding packages/plugins or after each build?)

Please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by CrazyBunnyz** [comment]
Step to reproduce : 
1. use flutter normally for development. build several web app for testing.
2. my disk C keep getting bigger.
3. I try to search info on StackOverflow or here, I delete temp folder but it's still not the permanent solution.
`[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.18363.1556], locale en-ID)
    • Flutter version 3.3.10 on channel stable at D:\flutter\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\android_sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at D:\Visual Studio 2022
    • Visual Studio Community 2022 version 17.3.32825.248
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and       
      include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at D:\android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.`

Question 1 :
is it possible to permanently solve this problem ?
Question 2 :
is it possible to move directory disk C to D which have much bigger space in my case so I don't have to delete temp folder that often ?

**Comment by huycozy** [comment]
@CrazyBunnyz Please provide information in more detail.

How much space increase do you consider unusual? Can you provide some screenshots of the folder/file in the project where you see it taking up unusual space? 

Below are some tests I do when creating some new Flutter projects on drive `C:`, and each of them has built web one time:

| before creating Flutter projects | after creating 1 project | after creating 2 project |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/213069210-d0b14ab8-c7da-41b9-803e-cbe456a82d6c.PNG"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/213069206-5bb43a58-9129-4a75-bdd8-9f7e72ef8726.PNG"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/213069203-616a0092-2799-4e56-8c2f-40eb933f00d2.PNG">

As you can see, free space doesn't change too suddenly/much. So, in order to verify the issue, we need thorough tests as well as more information from you.
