### ISSUE TITLE
[android] Hybrid composition mode, why do we need to draw on both background layer and overlay layer?

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#118519]
## Details
On the Android platform, when an Android view is added using Hybrid composition mode, Flutter creates 3 layers to draw the Flutter UI and the native view.
- Background layer: draw the Flutter content behind the native view.
- FlutterMutatorView: contains the native view
- OverlayView: draw the Flutter content above the native view.

![Screenshot 2023-01-15 at 13 47 34](https://user-images.githubusercontent.com/26743089/212527066-0deebcb4-3d3b-4c7e-93ed-e76dc1f75beb.png)

The draw operations on background and overlay are expensive, it takes about 9ms to draw on each layer on my device.
My question is why don't we use only 2 layers:
- FlutterMutatorView: contains the native view
- OverlayView: draw the Flutter content above the native view.

I think this way the performance does not suffer too much since it only requires cutting holes in the original flutter UI so the native view can be visible below and only requires 1 draw operation.

Using a background layer may be useful when the user wants to display a native view with transparent background but it's not always required, for example when displaying a map or video player, the performance should be the first priority.

So can the performance of the Hybrid composition mode be improved this way?
cc @blasten @stuartmorgan 

**Target Platform:** Android

**Comment by delfme** [comment]
That is a nice catch.
With textfield and text view widgets, it is sometimes needed to have a transparent background (ie. text and text typing over an image), but not always. It would be helpful if background layer could be enabled/disabled at need.

**Comment by delfme** [comment]
I’m keeping testing the use of native textfields inside flutter app. This is needed for both providing a native-like experience where this is a key factor (ie. chat and social media apps) and
as a temporary workaround for flutter textfield current issues (ie.   https://github.com/flutter/flutter/issues/115400)

HC seems to be the only composition that works with textfield (with TLHC, magnifier lens is not visible and there is text-bumping when textfield goes multi lines).

Unfortunately, HC takes 1 extra second to load and background layer affects performance with a simple listView, see scrolling janks on vid below. Scrolling is smooth on iOS.


https://user-images.githubusercontent.com/53510751/214247579-711cf30a-0641-46a7-bff8-3f4d91bccd26.MOV

**Comment by delfme** [comment]
This is the screen above without the native textfield, scrolling is smooth.


https://user-images.githubusercontent.com/53510751/214268379-9beb7820-c293-4592-b1a1-ed20bbea5f8c.MOV

**Comment by delfme** [comment]
This is with TLHC. Scrolling is still not smooth, just a bit better than HC.
This hint is interesting because tells us that additional optimization might be required with HC, even in case of disabled background layer.

https://user-images.githubusercontent.com/53510751/214270698-603669f7-195f-482d-84da-5a3fd0ccf882.MP4



**Flutter doctor:**
 [✓] Flutter (Channel master, 3.7.0-15.0.pre.16, on macOS 12.2 21D49 darwin-arm64, locale en-IT) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run path/to/sdkmanager --install "cmdline-tools;latest" See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run flutter doctor --android-licenses to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by XuanTung95** [comment]
This can be implemented as a plugin. I close it.
