### ISSUE TITLE
app crash on iOS emulator right after install

### ISSUE THREAD

**Issue by shaprinskiy** [flutter/flutter#118507]
## Actions order

1. Execute `flutter run` on the App (_the App successfully started on Android emulators and devices_)
2. App successfully builded and installed on iOS simulator, but then crash.

Crash report and output of "flutter doctor" in attachment.

Please help with this problem.
I cannot understand the crash report and accordingly it is not clear how to solve this problem.

[failure.txt](https://github.com/flutter/flutter/files/10418799/failure.txt)
[flutter_doctor.txt](https://github.com/flutter/flutter/files/10418798/flutter_doctor.txt)

**Comment by shaprinskiy** [comment]
@huycozy , good day, 
in attachment. Thanks!
[flutter_run_v.txt](https://github.com/flutter/flutter/files/10424617/flutter_run_v.txt)

**Comment by huycozy** [comment]
@shaprinskiy From your logs, it seems the issue is caused by a runtime error since it was built successfully. 
And I am unfortunately not sure how to resolve this issue. 

So I would suggest you keep an eye on it and debug it step by step in the flow of implementation. Once you find the implementation that causes the issue, please write a comment and we can continue investigating this.

**Comment by shaprinskiy** [comment]
Thanks, I'll try to figure it out..

**Comment by shaprinskiy** [comment]
@huycozy 
the application stopped crashing after removing the flutter_yandex_ads plugin (1.0.0+1)
