### ISSUE TITLE
Is it possible to use typescript develop flutter apps?

### ISSUE THREAD

**Issue by hydra1983** [flutter/flutter#11865]
It's expensive for our team to switch from typescript to dart. Is there any possibility for us to adopt flutter together with typescript?

**Comment by sethladd** [comment]
Thanks for the feedback! Flutter itself is written in Dart, today the best way to code in Flutter is to use Dart. That way, you get to extend and customize the framework, plus all your code and the framework code is compiled into one ARM binary to run on mobile devices.

**Comment by ldornin** [comment]
Angular supports typescript and dart, which lead me to believe that both would be first class languages for Google.

**Comment by pfurini** [comment]
I know this issue is closed, but let me add that Google seems not understanding that TypeScript won long time ago over Dart.
Why not just admit and accept that, instead of trying over and over to push Dart?
flutter is a very very interesting tech stack, but Dart will be (probably) one reason of its (s)low adoption rate in the future.

Just my 2c. based on my personal opinions. (plus, I don't want to criticize the hard and good work put on this project)

**Comment by sandangel** [comment]
This project is very great except that we have to use Dart. I hope we can use Angular Typescript in the future release.

**Comment by darbio** [comment]
I get that you're dog fooding, but I agree. Typescript would be a better choice to ensure greater developer adoption.

**Comment by gimox** [comment]
It s a mistery. Why dart instead angular with typescript!

**Comment by sethladd** [comment]
Thanks for all the comments! We recently published "Why Flutter uses Dart" which we hope explains why Dart is such a good fit for Flutter.

https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf

As we think that article does a good job explaining the thought process and rationale, we're going to lock this conversation here.

We really appreciate your time as you evaluate Flutter, we think you'll really enjoy both the framework _and_ the language because of their high-velocity workflow, expressive capabilities, and compile-to-ARM-code performance.

**Comment by Hixie** [comment]
One thing I would add is that we would be very happy to see people develop similar frameworks in other languages. For example, someone could take TypeScript or Kotlin and develop an equivalent framework using those languages. You could even follow Flutter very closely, with the same class hierarchy, names, etc, copying the documentation, and so forth. If such projects were developed, we would be interested in being involved at a high level in coordinating designs and sharing experiences.

If anyone is interested in doing this and would like to talk about it, please don't hesitate to reach out to me by e-mail: `ian@hixie.ch`
