### ISSUE TITLE
Menu items steal focus, so implementing copy/paste is very hard.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#118731]
The `MenuItemButton` widgets take the input focus when hovered, so when a user clicks on a "Copy" menu item, the thing they were trying to copy no longer has focus until the menu is dismissed, when the menu system puts the focus back where it found it.

It's possible to work around this with delays and/or tracking the context of the widget that had focus, but practically it's nearly impossible to implement cut, copy, and paste because of this.

Some options for fixing the issue include:
1) Implement a "stack" for `primaryFocus`, where opening a menu item pushes the stack, and selecting a menu item pops the stack before executing the action.
2) Rework menus so that the menu items don't use focus to keep track of what is currently highlighted.

Option 2 seems like the least invasive, but it may eliminate some use cases: people wouldn't be able to use just any widget for menu items, since instead of using focus to indicate that they are currently selected, there would have to be another mechanism that they would interface with, making it harder to use "regular" widgets to represent menu items. In a practical sense, the common case is expected to be using the `MenuItemButton` (or at least wrapping their widget in one), so maybe this isn't a huge consideration, but keeping that feature is why we made so many design iterations.

Option 1 could have additional use cases, such as in the case of popup menus, dropdown menus, or to simplify focus handling when modal dialogs or navigation occur. It may complicate the focus model further, however, which would definitely be undesirable, as it's already too complex. This is currently my preferred option, however.

cc @HansMuller @goderbauer

**Comment by gspencergoog** [comment]
cc @franciscojma86

**Comment by gspencergoog** [comment]
Maybe an option 3 would be to have `MenuItemButton`s just defer the invocation of their onPressed until after the previous focus has been restored. This would mean that "plain widget" menu items couldn't invoke actions that require interacting with focus, but would not require any changes outside of the menu code.

**Comment by dkwingsmt** [comment]
> The MenuItemButton widgets take the input focus when hovered

Are you saying "when clicked"? Because hovering shouldn't take focus.

I'm also thinking of a new field `lastFocusedTextInput`. This makes sense because the OS often distinguish between "active focus" and "inactive focus". For example, in the following GIF, when you click the menu, the text input appears focused, but is actually not, and the caret is no longer blinking.
![image](https://user-images.githubusercontent.com/1596656/213294216-993ccf3b-7e57-4480-ab8e-eaf42314b2ae.png)

**Comment by HansMuller** [comment]
Option #1 makes sense to me since the focus would revert to the original owner before the onPressed action ran. I don't think developers should expect to be able to drive the focus around the popped up menu from within an onPressed callback. Crazy idea: deferring the onPressed callback until after the next frame is finished. At that point the menu is down and the focus has moved. Corollaries: menus should not remain visible until the onPressed callback returns, onPressed callbacks can not change the appearance of the popped up menu.

**Comment by gspencergoog** [comment]
@dkwingsmt  It's not just text input focus that matters: it needs to be able to fire an intent, and then have it find the right action, which depends on the focus, even if it's not text.

And no, I don't mean "when clicked".  It takes focus on hover because menus are traversed via hover. That's how the menu system knows which parent menus are open, and how it knows that they are no longer open, and how generic buttons that can be placed in a menu are invoked with the keyboard. It is also how the keyboard navigation can be used to traverse the menu: it uses focus navigation. It is possible to turn it off for non-submenu buttons.

But I agree that it's odd, which is why I suggested option 2, but then the scenario where you point at a menu item and press "enter" to invoke them won't work for regular widgets then, because they won't actually have focus then. I can maybe find a way around that, but it seems likely to be complicated.

@HansMuller Yeah, that's mostly what I was suggesting in https://github.com/flutter/flutter/issues/118731#issuecomment-1396061984 Currently the menu does stay visible while onPressed is called, and disappears right after it is called, but you're right that it should probably be after the menu closes. It still only fixes menu items based on MenuItemButton, though, since that's where close is called on the MenuController. Creators of their own buttons would need to know to do that, but that's documentable.

**Comment by anlumo** [comment]
Doesn't setting [requestFocusOnHover](https://api.flutter.dev/flutter/material/MenuItemButton/requestFocusOnHover.html) to false solve that issue?
