### ISSUE TITLE
`TextField` controller should be `TextEditingController` be default.

### ISSUE THREAD

**Issue by MikiVanousek** [flutter/flutter#118816]
## Use case

I am writing a simple app that is taking user input using the `TextField` widget. By default, the widget has no controller. This seems like an odd choice.

## Proposal
I suggest making the `TextEditingController` the default value of the parameter `controller`.

**Comment by danagbemava-nc** [comment]
Hi @MikiVanousek, as stated in the documentation, if you do not add your own controller, the TextField widget creates one by itself. See https://api.flutter.dev/flutter/material/TextField/controller.html

Is there something else you are requesting?

**Comment by MikiVanousek** [comment]
I agree that is what the docs say. And I think it should happen, but I don't think this is what happens.

Unless you set the controller in the constructor, it will be null. There is no default value for the controller parameter in the `TextFiled` constructor in [the source](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_field.dart)

**Comment by danagbemava-nc** [comment]
Hi @MikiVanousek, it's not in the constructor because it is handled in `_TextFieldState` internally. See the following lines.

`_TextFieldState` is where a lot of the code related to handling the `TextField` state happens so it only makes sense that it is handled there. 

Does this make it clear why there is no value in the constructor?

https://github.com/flutter/flutter/blob/572f0a1a9a652ee890ece20edb37edfeea87d505/packages/flutter/lib/src/material/text_field.dart#L877-L878

https://github.com/flutter/flutter/blob/572f0a1a9a652ee890ece20edb37edfeea87d505/packages/flutter/lib/src/material/text_field.dart#L989-L991

**Comment by MikiVanousek** [comment]
I wonder then why I had to set the controller in the constructor:
```dart
  static final textFiled = TextField(
    controller: TextEditingController(),
  );
```
In order to later access the text:
```dart
    var text = textFiled.controller?.text ?? '';
```

If I don't set the controller, it is null and `text` would be an empty string. I can make a minimal reproduction example if you wish.

**Comment by danagbemava-nc** [comment]
Hi @MikiVanousek, you set the textController to grant you more control over textField. With that control, you need to take of disposing and initializing the controller yourself. You can add listeners to perform certain actions based on whatever condition you want as well.

If all you need is text, you can make use of the `onChanged` or `onSubmitted`  callbacks in the textField. 

I must say, I haven't seen the textfield used in this manner before. You would normally keep the reference to the TextEditingController so you can later dispose of it when it is not being used. 

```
var text = textFiled.controller?.text ?? '';
```

I'm curios, why are you using the textfield in this manner?
