### ISSUE TITLE
[camera] OutOfMemoryError when debugging in Android Studio

### ISSUE THREAD

**Issue by sergiossm** [flutter/flutter#118884]
If the camera is open, the Flutter plugin will crash after a few seconds stopped on a breakpoint when debugging the Java code in Android Studio. It happens both in my app and Google ML Kit's [example app](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example)

```
E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: com.google_mlkit_example, PID: 21139
    java.lang.OutOfMemoryError: Failed to allocate a 921616 byte allocation with 203216 free bytes and 198KB until OOM, target footprint 268435456, growth limit 268435456
        at io.flutter.plugins.camera.Camera.lambda$setImageStreamImageAvailableListener$17$io-flutter-plugins-camera-Camera(Camera.java:1131)
        at io.flutter.plugins.camera.Camera$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:4)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:826)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

<img width="1920" alt="Screenshot 2023-01-20 at 14 32 32" src="https://user-images.githubusercontent.com/26566365/213706698-f174df24-003c-41bb-900f-e2e7f567ecf1.png">

**Comment by darshankawar** [comment]
Thanks for the report @sergiossm 




> It happens both in my app and Google ML Kit's [example app](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example)

this package is third party to Flutter and there was an issue reported with it long time back https://github.com/firebase/flutterfire/issues/5746

Is there a way for you to replicate this crash just using `camera` plugin only ? If yes, please provide the device details on which it crashes, because `OutOfMemory` probably indicates a space crunch or a low end device, but this is just my assumption.
