### ISSUE TITLE
lazy scrollview by default

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#118882]
# lazy scroll view

would be nice to have widgets inside a scroll view, to be lazy by default.
if outside the render view they will not  be instantiated before needing to be rendered, and their height set at the average rendered widget height in the scroll view to compute the scroll bar size.

**Comment by iapicca** [comment]
@renanyoy 
what do you this is missing from [ListView.builder](https://docs.flutter.dev/cookbook/lists/long-lists#interactive-example)?

**Comment by exaby73** [comment]
Hello @renanyoy. As @iapicca mentioned, I am not sure what is missing from `ListView.builder`. If you have a use case that doesn't fit it, please do give a code sample and maybe we can help :)

**Comment by renanyoy** [comment]
any application that don't use listview.builder() . should be nice have them optimized too.

**Comment by renanyoy** [comment]
a lazy scrollview not listview ;)

**Comment by iapicca** [comment]
> a lazy scrollview not listview ;)

I feel that we are splitting hairs:
- firstly [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html)  **is** a [ScrollView](https://api.flutter.dev/flutter/widgets/ScrollView-class.html)

- moreover, of the available `ScrollView`'s

  > [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html), which is a commonly used [ScrollView](https://api.flutter.dev/flutter/widgets/ScrollView-class.html) that displays a scrolling, linear list of child widgets.
  > [PageView](https://api.flutter.dev/flutter/widgets/PageView-class.html), which is a scrolling list of child widgets that are 
  each the size of the viewport.
  > [GridView](https://api.flutter.dev/flutter/widgets/GridView-class.html), which is a [ScrollView](https://api.flutter.dev/flutter/widgets/ScrollView-class.html) that displays a scrolling, 2D array of child widgets.
  > [CustomScrollView](https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html)

  that same I [mentioned](https://github.com/flutter/flutter/issues/118882#issuecomment-1398328248) about `ListView` applies also to `PageView` and `GridView`
  and you can have [CustomScrollView](https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html) with [SliverList](https://api.flutter.dev/flutter/widgets/SliverList-class.html) to have lazy loading

- lastly the only other instance of `ScrollView` that comes to mind is [SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html), 
  but since has by definition a "single child" not sure it matters

@renanyoy 
could you provide a code sample of what you are trying to achieve,
maybe the tool you are looking for already exists

**Comment by exaby73** [comment]
@iapicca I think what OP is suggesting is that most of not all `ScrollView`s like `SingleChildScrollView` are lazy by default. @renanyoy correct me if I am wrong here.

@renanyoy This is not something we can do. There are use cases where as a developer, we don't want laziness in our scrolling. Think about a form on a small screened device. Lazy building form inputs might destroy the attached `TextEditingController` and reset what the user has inputted into that specific field.

Whether a scroll view is lazy or not, is a design decision that is the developer's responsibility, and not Flutter. Flutter merely provided primitives to work with. How you use them, is up to you. If the way you use them causes your app to be rendering hundreds of widgets because you should have been using a `ListView.builder` instead of a `SingleChildScrollView`, then that is an issue with optimizing the app on the developer's end, and not the responsibility of Flutter.

Ultimately, I do not see this issue as a valid one for the above reasons. Of course if I misunderstood your issue, please comment with a code sample and a use case so that I may understand it better. But for now, I am closing this issue. Thank you

**Comment by renanyoy** [comment]
I know all that, I just said that it would be nice to optimize also the default scrollview, for views with a more complex UI.

**Comment by renanyoy** [comment]
near all time I need to set a shrink wrap every where to make it working.. so it breaks all basic optimization, and would to have it at some optimization at the scroll view level too

**Comment by iapicca** [comment]
@renanyoy 
what means "default scrollview" to you?
> [...]  shrink wrap every where to make it working [...]

seems like you are using a `SingleChildScrollView`, can you provide an "unoptimized" example?

**Comment by exaby73** [comment]
@renanyoy Using `shirkWrap` is not performant anyways, see [the docs](https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html):

> Shrink wrapping the content of the scroll view is significantly more expensive than expanding to the maximum allowed size because the content can expand and contract during scrolling, which means the size of the scroll view needs to be recomputed whenever the scroll position changes.

To avoid this, you should put your scroll view into a container with a fixed height. For example, you can add the scroll view in an `Expanded` in a `Column` to automatically set the height to the maximum available space
