### ISSUE TITLE
[Impeller] Float samplers can get re-ordered compared to SkSL

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#118847]
When i looked at this last I thought that this was handled correctly via our uniform mapping, but @zanderso has shared a few places where that isn't the case. Need to investigate what is different about these and whether or not we should revist uniform re-mapping for floats.

**Comment by zanderso** [comment]
I believe there's still a dependence on use order. @jonahwilliams it shows up in the glowing text example in Impeller on Metal that I sent you awhile back. Maybe it's only cropped up after https://github.com/flutter/engine/pull/39147 and https://github.com/flutter/engine/pull/39198 --- I haven't bisected yet.

**Comment by jonahwilliams** [comment]
Those PRs only adjusted sampler use order - are you seeing float re-ordering? I'd expect them to be re-ordered but the mapping data should account for it. We don't correctly handle uniforms getting optimized out yet.

**Comment by zanderso** [comment]
Hmm. Shoot. This isn't repro'ing for me anymore. Sorry for the false alarm. I think I probably wasn't being sufficiently paranoid when swapping among a few different framework and engine versions...

**Comment by zanderso** [comment]
I figured out that this wasn't repro'ing for me earlier today because I was swapping the declaration order of uniforms in the shader, but not swapping the indices used to set the uniforms in the Dart code. That is, the uniforms were set by the Dart code in use-order, and so changing the declaration order in the shader didn't trigger the issue. So, sadly I have to re-open this =(

**Comment by jonahwilliams** [comment]
Fixed for real this time!
