### ISSUE TITLE
APIs to expose low level text run data

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#118998]
## Use case

For any serious printing or PDF export application, the necessary steps involved are similar to text layout / painting:
1) paragraph building
2) splitting text into runs taking direction and scripts into account
3) font matching (family, fallback, features, supported glyphs etc.)
4) code point to glyph lookup
5) text shaping (substitution, positioning)
6) layout
7) font subsetting
8) glyph painting (e.g. on PDF canvas)

Currently Flutter engine's implementation of 1-6 (done with minikin, harfbuzz and Skia text layout engine) cannot be employed as there are no APIs to get the low level information on paragraphs, meaning that they'd need to be implemented in Dart. Besides the high complexity, it'd be very difficult to guarantee the same behaviour / output (e.g. what comes out after font matching or text shaping).

## Proposal

Expose APIs to get complete information on the paragraphs:
- text runs with font data (e.g. font path or id so they can be read and used by the subsetter)
- id, position and size of each glyph within the run

**Comment by chinmaygarde** [comment]
cc @dnfield

**Comment by dnfield** [comment]
Part of your request would be satisfied by https://github.com/flutter/flutter/issues/96617, which would add missing API around drawing text that you've laid out and shaped already.

There's been some discussion and there are probably some issues (but I can't find them at the moment) around exposing lower level shaping and lookup functionality. I don't know of any compelling reason to have Flutter do this as opposed to doing it as some kind of FFI based package though - e.g. an FFI wrapper around harfbuzz or an FFI wrapper around CoreText etc.

I don't think we would expose SkParagraph's text run data, because that's a bit of an implementation detail that can change without notice and would be difficult to maintain. It's also probably the wrong level of abstraction to use for the goals you have.

**Comment by dnfield** [comment]
Closing this in favor of the existing issue. This tracker isn't the right place to track a third-party package for harfbuzz etc.
