### ISSUE TITLE
Integrating multiple flutter modules into an Android application fails

### ISSUE THREAD

**Issue by rushilsingh** [flutter/flutter#118949]
Greetings

We are trying to integrate two different flutter modules into our Android application.

We are integrating the modules as AARs as outlined here:
https://docs.flutter.dev/development/add-to-app/android/project-setup

However, we encounter the following error:
`
Duplicate class com.org1.lib.BuildConfig found in modules jetified-flutter_debug-1.0-runtime (:flutter_module:) and jetified-flutter_debug-1.0-runtime (flutter_module.aar)
Duplicate class io.flutter.plugins.GeneratedPluginRegistrant found in the following modules: jetified-flutter_debug-1.0-runtime (:flutter_module:), jetified-flutter_debug-1.0-runtime (flutter_module.aar) and jetified-flutter_release-1.0-runtime (com.org2.sdk:flutter_release:1.0)
`

I see that there is an existing issue that is related:
https://github.com/flutter/flutter/issues/39707

We tried experimenting with the workarounds suggested. However, none of them worked within our constraint i.e. using AAR files for the flutter modules.

Please help.

Thanks.

**Comment by darshankawar** [comment]
Thanks for the report @rushilsingh 
I think the error you are getting could be due to the fact that Flutter generates dependency aar with version of their parent instead of the version of dependency.

The multiple flutter modules you are using could be using dependencies which could be using conflicting class names somehow and hence throwing the reported error:

`Duplicate class com.org1.lib.BuildConfig found in modules jetified-flutter_debug-1.0-runtime (:flutter_module:) and jetified-flutter_debug-1.0-runtime (flutter_module.aar) Duplicate class io.flutter.plugins.GeneratedPluginRegistrant found in the following modules: jetified-flutter_debug-1.0-runtime (:flutter_module:), jetified-flutter_debug-1.0-runtime (flutter_module.aar) and jetified-flutter_release-1.0-runtime (com.org2.sdk:flutter_release:1.0)`

There's a similar issue open that points to related use case in which you can follow-up for further updates: https://github.com/flutter/flutter/issues/117359
I am closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by rushilsingh** [comment]
Thanks for your response @darshankawar 

The conflicting dependency is flutter itself. 

The conflicting class name GeneratedPluginRegistrant is coming auto-generated code in the .android folder resulting from the 'flutter build aar' command.
