### ISSUE TITLE
[Flutter_tools] 400go of flutter_tools folders

### ISSUE THREAD

**Issue by lordofkawaiii** [flutter/flutter#119073]
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [version 10.0.19044.2486], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.20)
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

I am deleting 400GO of flutter_tools folders
![image](https://user-images.githubusercontent.com/26768828/214350943-87480f94-71d6-4c65-a42e-ea5c1e71caca.png)

https://github.com/flutter/flutter/issues/84094

the issue is marked as solved but i have the last version available

i am using vscode and i usually launch several instance in debug at the same time

**Comment by darshankawar** [comment]
@lordofkawaiii 
The original fix is available in latest stable version released yesterday (3.7.0) and you can see the PR in the release notes:

<img width="938" alt="Screenshot 2023-01-25 at 12 03 45 PM" src="https://user-images.githubusercontent.com/67046386/214496429-2a32f3da-2ac8-4e99-aa1f-cad56eeff6cb.png">

So you'll need to upgrade your version to latest stable to see the fix working.

Closing this issue since the fix is available in latest version.
