### ISSUE TITLE
Decide on opt-in or opt-out of localization

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11900]
Most applications aren't localized. However, we currently automatically localize the Material widgets and the overall directionality if we recognize the user's locale.

This mostly is not a big deal except in the specific case of an app that's written in a left-to-write language, but used in a right-to-left locale by the user. When the app puts the user's RTL name into a string, the whole reading order will be flipped. For example, say they have the string `'hello $username, how are you'`:

An LTR app would with an LTR name would show a left-aligned: "hello fred, how are you?"
An RTL app with an LTR name would should a right-aligned: "hello fred, how are you?"
An LTR app would with an RTL name would show a left-aligned: "hello FRED, how are you?"
An RTL app would with an RTL name would show a right-aligned: "?how are you ,DERF hello"

The last one is wrong.

We should avoid this problem. We can do it in various ways, some of which include:

* we could hard-code the locale in the template app to English, with a comment saying that if you localize your app you should remove that and at a minimum support all the RTL languages we support in the framework.

* we could by default only support English and LTR, and require that the developer opt-in to localized strings from the specific languages they support in their app, if they want to support any.

cc @HansMuller @abarth @yjbanov

**Comment by yjbanov** [comment]
I like the opt-in model where widgets localize automatically based on `Localizations.of` but there's only one switch for the developer to flip to enable localization everywhere. A similar problem that @HansMuller and I discussed is whether we want a global set of supported locales for the app. It wouldn't be a good user experience if their app is only partially localized because one widget supports a different set of locales from another widget in the same app. Here too we probably want one place for the developer to control the set of supported locales.

**Comment by Hixie** [comment]
Hans' patch where there's a defined list of supported locales seems to handle this pretty well.

**Comment by gspencergoog** [comment]
I like the opt-in model too: an explicit list of locales is, well, explicit.  The developer then knows what they will need to localize their text into, and knows that we won't try and display a localization that they're not ready to coexist with.
