### ISSUE TITLE
Add support for editing the arguments that flutter passes to CMAKE

### ISSUE THREAD

**Issue by eladmaimoni** [flutter/flutter#119006]
When building a multi platform application in flutter, users can edit the generated CMakeLists.txt scripts.
This allows a user to add custom C/C++ files, create dynamic libraries which can be loaded from dart as explained [here](https://levelup.gitconnected.com/port-an-existing-c-c-app-to-flutter-with-dart-ffi-8dc401a69fd7).

However, there is no way to control the arguments provided to cmake by flutter. Or at least I could not find a way. Specifically arguments such as:

- toolchain files
- generator used
- compiler used
- general cmake options and variables

The toolchain file option is especially important since tools such as vcpkg for instance rely on it install 3rd party libraries per project. 
This can also address [this issue](https://github.com/flutter/flutter/issues/32719#issuecomment-1399618738).

Ideally, there should be a single root CMakeLists.txt that will add the other CMakeLists.txt as subdirectory, all the arguments to that script should be documented or at least visible so that the user can modify them. One way to achieve this can be to use a CMakePresets.json file that flutter will use and the user can customize.

**Comment by dcharkes** [comment]
Drive by comment:

> When building a multi platform application in flutter, users can edit the generated CMakeLists.txt scripts.
> This allows a user to add custom C/C++ files, create dynamic libraries which can be loaded from dart as explained [here](https://levelup.gitconnected.com/port-an-existing-c-c-app-to-flutter-with-dart-ffi-8dc401a69fd7).

It is preferable to use `plugin_ffi` and an app using the FFI plugin, instead of modifying an app. Your request stands for that approach as well, because the CMake build for that plugin would also not have arguments.

(We're working on a new way of adding native libraries to Flutter and Dart projects https://github.com/dart-lang/sdk/issues/50565. @mkustermann mentioned it would be useful to be able to pass general key-value pairs down to build scripts, [see comments on this prototype](https://dart-review.googlesource.com/c/sdk/+/267340?tab=comments). What you are requesting could be made part of that.)

**Comment by eladmaimoni** [comment]
@dcharkes thanks for your comment, Indeed I investigated the FFI plugin as well. And I could not find a way to control the CMAKE args. I will look into the links.

**Comment by stuartmorgan** [comment]
> However, there is no way to control the arguments provided to cmake by flutter.

In general this is intentional; Flutter isn't intended to support completely arbitrary builds. On every platform there's a tight relationship between the native project template and the `flutter` tool to support `flutter` use cases. To do non-standard things, one generally needs to use the native projects directly.

> * generator used

Why do you need to control this?

> * compiler used

Same question here. In general the ecosystem is not currently set up with the assumption that people will use different compilers, so we don't want to encourage people to do that.

> * general cmake options and variables

What options and variables specifically?

In general we expose specific options for specific use cases in the `flutter` tool, rather than trying to expose every possible configuration.

> The toolchain file option is especially important since tools such as vcpkg for instance rely on it

If we add support for vcpkg it would be explicitly supported with a tool-provided way to locate it, `flutter doctor` support, etc.

> Ideally, there should be a single root CMakeLists.txt that will add the other CMakeLists.txt as subdirectory

This is already the case.

> One way to achieve this can be to use a CMakePresets.json file that flutter will use and the user can customize.

It may make sense to do this, but we should start from a specific goal we want to support, and design from there. "People should be able to drive arbitrary builds with arbitrary options using `flutter` isn't a goal for the tool.

**Comment by eladmaimoni** [comment]
@stuartmorgan I am new to flutter, so my conclusions might be inaccurate.

What I am trying to do is to develop a native C/C++ ffi plugin or simply add a dynamic library to the generated flutter project (as described [here](https://levelup.gitconnected.com/port-an-existing-c-c-app-to-flutter-with-dart-ffi-8dc401a69fd7)).

I would like to integrate vcpkg in order to use 3rd party libraries within the dynamic library. This requires:

- access to the toolchain argument - vcpkg requires that. 
- ability to set cmake 'cache variables'. one example would be VCPKG_TARGET_TRIPLET that tells vcpkg which triplet to use (for example x64-windows-static-md instead of x64-windows-dynamic).

In case I am developing a C++ plugin, my understanding is that this is just a dynamic library that is loaded by dart and deployed in a uniform manner to the target device by the flutter framework. I should be able to compile it however I want (compiler / generator / cmake flags). But maybe I am missing something.


> Ideally, there should be a single root CMakeLists.txt that will add the other CMakeLists.txt as subdirectory

> This is already the case.

If I run:

`flutter create --template=plugin_ffi --platforms=android,ios,windows,linux native_plugin` I get a subdirectory for each platform. where each subdirectory serves as a root directory. vcpkg for usually have the structure like so:

```
CMakelists.txt // root cmake
CMakePresets.json // contains reference to vcpkg toolchain, cmake variables.
vcpkg.json // contains list of 3rd party libs
sub_dir1/
sub_dir2/
```

In the folder hierarchy created by flutter, I should duplicate the vcpkg.json to each of the platform directories. and I don't have a way of providing the vcpkg toolchain.

**Comment by picatostas** [comment]
My issue with not being able to have access to what flutter sends to cmake is for example, these to variables:

- CMAKE_BUILD_TYPE
- CMAKE_VS_PLATFORM_NAME

when you run flutter build --debug, --debug is not passed until the building step:
`cmake --build "build_dir" --config Debug`
 and I don't see the arch parameter sent in either of the generation nor building steps. 
So when one wants to setup output directories to copy external dependencies that may have 
different options between, lets say x86/x64 and Debug/Realease, you have to play with copy post build events and $CONFIG variable instead of just having a:
`
set(MY_LIBRARY "${MY_LIB_DIR}/${CMAKE_VS_PLATFORM_NAME}/${CMAKE_BUILD_TYPE}/my_lib.dll")

install(FILES "${SPARKLE_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_LIB_DIR}" COMPONENT Runtime)

`
instead of having:
`
add_custom_command_if(
    TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMANDS
    COMMAND $<CONFIG:Debug> xcopy /y /i $<SHELL_PATH:$<TARGET_FILE:${PROJECT_NAME}>> $<SHELL_PATH:${CMAKE_SOURCE_DIR}/>..\\build\\windows\\runner\\Debug\\
    COMMAND $<CONFIG:Release> xcopy /y /i $<SHELL_PATH:$<TARGET_FILE:${PROJECT_NAME}>> $<SHELL_PATH:${CMAKE_SOURCE_DIR}/>..\\build\\windows\\runner\\Release\\
)
`
. If `flutter build` is going to both generate and build the cmake files, why not pass those build and arch arguments in the generation step as well? In my opinion it makes the cmake files a bit too intricate.

If I am missing something here, please let me know.

**Comment by stuartmorgan** [comment]
> My issue with not being able to have access to what flutter sends to cmake

@picatostas Please file a new issue; this issue is about developers being able to change the invocation itself, not accessing information within the script.

> when you run flutter build --debug, --debug is not passed until the building step

That's because Visual Studio is a multi-configuration generator; the build configuration does not exist at generation time.

**Comment by stuartmorgan** [comment]
Looking over this again, I'm going to close it; individual application developers changing their CMake invocations isn't a viable solution to plugin-level behaviors, since plugin authors won't be able to control this.

There may be other use cases for which this might have benefit, but those should be filed as new issues, driven by use case rather than proposed solution, so that they can be evaluated. (E.g., most other case I can imagine would almost certainly be better served by add-to-app support.)
