### ISSUE TITLE
flutter-3.7-candidate.1 release infra is blocked due to migration to iPhone 11's in DeviceLab

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#119014]
See https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=flutter&branch=flutter-3.7-candidate.1

The necessary bots cannot be found, which is preventing us from CP'ing changes into the releases.

**Comment by CaseyHillers** [comment]
\cc @godofredoc @zanderso @XilaiZhang @itsjustkevin @jmagman

**Comment by CaseyHillers** [comment]
I see two paths forward:

1. Revert the lab change (put a few iPhone 6's back in the lab so there are bots)
2. CP a change forward to upgrade the release to use the new iPhones

I'm hesitant on 2 as it's a large, last minute CP.

**Comment by yusuf-goog** [comment]
We had a CL to execute 2. on the weekend. That would have at the least given us the necessary pass/fail data for the roll forward.

As per others, if the tests pass, they do not anticipate an issue with rolling forward.

I will add some Iphone 6s's back in to continue for now, since there is a time sensitive release, and to alleviate risk. But we should get the change in to verify test results.

**Comment by jmagman** [comment]
From my perspective it's preferred if devicelab tests on release branches is rolled forward to iOS 16, since this ideally should have been done months ago to verify Flutter tests on the release branches work on the latest major iOS version. Plus that means more capacity to run tests on all branches.

However, do what you need to do to unblock the release, adding the old phones, etc.

**Comment by jmagman** [comment]
> As per others, if the tests pass, they do not anticipate an issue with rolling forward.

@yusuf-goog has anyone actually run the devicelab tests on that release branch on iOS 16?

**Comment by yusuf-goog** [comment]
mac-24, mac-25 and mac-41 (M1) are being swapped to iphone 6s.

**Comment by CaseyHillers** [comment]
Thank you @yusuf-goog! Copying from our release team meeting:

After this is resolved, we should formalize a lab deprecation policy that accounts for releases. We need to find a balance between maximizing the lab effectiveness and the integrity of our releases. In the future, a RFC should be sent to the team about future lab deprecations that collects feedback from all the stakeholders.

**Comment by ricardoamador** [comment]
@CaseyHillers @yusuf-goog is this still a P0?

**Comment by CaseyHillers** [comment]
> @CaseyHillers @yusuf-goog is this still a P0?

Yes. I'm waiting on https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=flutter&branch=flutter-3.7-candidate.1 to verify the infra is working as expected. Once that's done (ETA next hour) I'll close this out.

**Comment by ricardoamador** [comment]
Perfect. Thank you. Let me know if I can help.

**Comment by yusuf-goog** [comment]
All ios tests have passed for the build.

**Comment by XilaiZhang** [comment]
> All ios tests have passed for the build.

great, continuing with release
