### ISSUE TITLE
Lazy load children in PostGrid

### ISSUE THREAD

**Issue by kaiceyd** [flutter/flutter#119136]
> The PostGrid should never contain more than a handful of children 

Is that asserted somewhere? What if the user provides hundreds of items? Or tweaks the code for their own use case and find themselves with a performance issue? I understand users of the toolkit are expected to use this code hands on and make changes.

I am just pointing this out for consideration since performance issues are very difficult for users to debug when the code is already provided to them.

_Originally posted by @Piinks in https://github.com/flutter/news_toolkit/pull/746#discussion_r1086230008_

**Comment by zoeyfan** [comment]
@kaiceyd would you please provide an update on the status of this issue? Should we assign it to another engineer?

**Comment by kaiceyd** [comment]
Hi @zoeyfan! I've added @valentinallavayol as an issue owner. She's currently working to address this and I'll keep this issue updated as development progresses. Thanks!

**Comment by kaiceyd** [comment]
@valentinallavayol is working to address this yet. Progress has been made in the refactor, but a larger block refactor is still in development before all changes are merged.

**Comment by Piinks** [comment]
From what I understand, any of these sound fine. Including the sliver_tools package.

However, my first thought reading this

> So the current PostGrid widget (without slivers) is constructed by a Column that contains a PostLarge header, and then the Grid filled with PostMedium widgets. 

was that you could extend the `SliverGrid[which ever one you are using for the medium post grid)Delegate` to just handle the first child differently, giving it all the space it needs, and then resuming the normal layout after it.

**Comment by Piinks** [comment]
Oh! One other thought, SliverToBoxAdaptor is not a lazy loading widget FYI. It just lays out its child without concern for whether or not it is visible.

**Comment by Piinks** [comment]
> could we end up having any unwanted consequences by using this widget on the feed and it not lazy loading?

I am not sure, I am not familiar with all of the components of the app. Lazily loading scrolling children is always best for optimal performance. I would recommend using profilers to determine if there is any performance issues when loading the feed with many many complicated widgets.

**Comment by valentinallavayol** [comment]
@Piinks Just wanted to leave here that the idea of extending the delegate of the SliverGrid to treat the first child different from the rest seems to be working fine, thanks so much for the idea!

We ran into another matter of discussion with this refactor and wanted your opinion on the best way to handle this.  
`CategoryFeedItem` is the widget that receives a block of a certain type and returns the specific widget that builds that block's UI. 

Since now the widget for the PostGrid is a SliverGrid, we need to refactor `CategoryFeedItem` to return sliver widgets, so that the `CategoryFeed` (widget that shows the feed) can have a `CustomScrollView` and be more performant when showing the feed.

But, the `CategoryFeedItem` widget is also used on other places (such as the **search page** and the **related stories** of an article).
We thought of two options to solve this.  First one would be to change those screens lists to accept slivers too (meaning a little bigger of a refactor, but cleaner code and performant scrolling on those pages too).

The other option would be to keep the `CategoryFeedItem`  file as is, and have a `SliverCategoryFeedItem` to use on the feed . That way we wouldn’t have to modify the search page and the related stories.

We do believe that having slivers on this screens is definitely cleaner, but since these changes were not initially discussed when coming up with the solution for this issue (since it only involved the PostGrid), so we thought would be best to get your perspective on it.

**Comment by felangel** [comment]
Can this be closed now since #864 was merged and released in v1.0.4?

**Comment by kaiceyd** [comment]
Yes, closing now!
