### ISSUE TITLE
Context Menu on the Web Platform

### ISSUE THREAD

**Issue by anlumo** [flutter/flutter#119184]
## Steps to Reproduce

* Open the [contextMenuBuilder](https://master-api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html) documentation.
* Try to use any of the examples in their iframe.

**Expected results:**

The context menu from the example when right-clicking or long-clicking.

**Actual results:**

The browser's standard context menu when right-clicking, nothing when long-clicking.

I've tried Chromium and Firefox on Linux, Firefox on Windows and Safari on iOS, none of them show any non-standard context menu.

**Comment by navaronbracke** [comment]
That is because on the web, we defer to the browser to handle the context menu.

**Comment by anlumo** [comment]
But there's no way to add custom items to the browser's context menu!

**Comment by darshankawar** [comment]
Apologies for coming back late on this issue.

@anlumo When I ran the code sample on web, right clicking gave me below menu:

![Screenshot 2023-02-02 at 12 03 49 PM](https://user-images.githubusercontent.com/67046386/216249946-2f8bd065-a108-476d-a1c4-80ebe0487285.png)

And long pressing gave me:

![Screenshot 2023-02-02 at 12 03 38 PM](https://user-images.githubusercontent.com/67046386/216250004-2472b6be-616f-4bf2-9ad1-d48b23408d2f.png)

Instead of these, per the code sample, it should show `AdaptiveTextSelectionToolbar`. Is this a correct interpretation of the issue you raised ?

**Comment by anlumo** [comment]
Yes, that is correct.

**Comment by darshankawar** [comment]
Thanks for the update @anlumo. I see that the custom context menu works on mobile (iOS):

<img width="367" alt="Screenshot 2023-02-03 at 10 55 13 AM" src="https://user-images.githubusercontent.com/67046386/216519848-b7f496c7-b003-4684-8189-07e68a28c78f.png">

But I am not sure if it is intended to work on web. Please see [this](https://github.com/flutter/flutter/pull/107193) related PR for your reference.

**Comment by navaronbracke** [comment]
Maybe this can help? https://github.com/flutter/flutter/pull/118194 Its _very_ recent however. @anlumo Could you switch to master and see if using `await BrowserContextMenu.disableContextMenu();` works for you?

**Comment by anlumo** [comment]
I can confirm that adding that line on master flutter fixes it!

Long pressing still doesn't open the context menu, but that's also not the case on desktop and actually what I want (since long-pressing is not a thing on desktop and web usually). So this is more a documentation issue than a problem in the code.

**Comment by navaronbracke** [comment]
@justinmc Perhaps we should add a doc link to the `BrowserContextMenu` API for the web in `editable_text.dart` (and their Cupertino / Material equivalent)? Currently, it is never mentioned in any of the documentation in those widgets.

Personally, I only knew about the API because I saw the linked PR show up on Github one day.

**Comment by justinmc** [comment]
Thanks everyone for pointing this out!  I forgot that I can make these examples work on web now.  I'll fix them by using `disableContextMenu` and also add some links so that API is more discoverable.

**Comment by justinmc** [comment]
Confirmed that the examples in the master docs seem to work on web now.
https://master-api.flutter.dev/flutter/widgets/EditableText/contextMenuBuilder.html
