### ISSUE TITLE
Expose `--enforce-lockfile` for `flutter pub get`

### ISSUE THREAD

**Issue by Pante** [flutter/flutter#119226]
Dart introduced [`--enforce-lockfile`](https://dart.dev/tools/pub/cmd/pub-get#--enforce-lockfile) in 2.19. However, it seems that the flag isn't exposed in Flutter 3.7.

Executing `flutter pub get --enforce-lockfile` returns the following error,
```plaintext
Could not find an option named "enforce-lockfile".
```

It'll be great if the option is exposed.

**Comment by exaby73** [comment]
Hello @Pante. Looks like this option exists in the master channel. If you want to request a cherry-pick to the stable channel, you can look at filling the CP request template [here](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#requesting-a-cherry-pick). But since this already exists in master, I am closing this issue. Thank you

**Comment by fkirc** [comment]
I am also running into this issue.
Is there any specific timeline when this gets resolved, or can we expect that the "master channel" will be automatically included in the next major Flutter-release (perhaps 3.8)?
