### ISSUE TITLE
[video_player] why don't you use XFile for controller creation?

### ISSUE THREAD

**Issue by AlexanderShniperson** [flutter/flutter#119336]
Hi

Package: [VideoPlayer](https://pub.dev/packages/video_player)

The problem:
I see that `VideoPlayerController.file(...)` uses `File` from `dart:io` package, it's impossible to use controller for Flutter Web.

Any explanation why don't you use [cross_file](https://pub.dev/packages/cross_file) for controller?

**Comment by exaby73** [comment]
Hello @AlexanderShniperson. Since the web does not support accessing the file system, it doesn't support `VideoPlayerController.file`. It will throw an `UnimplementedError`. See https://pub.dev/packages/video_player#web

This is intended, and therefore, we don't use `cross_file` as it has no uses for the Web. I am closing this issue because of this, but if you disagree, please comment your reasoning and I can reopen the issue. Thank you
