### ISSUE TITLE
FormatException (FormatException: Неожиданный символ (в символе 1) ‰PNG ^ )

### ISSUE THREAD

**Issue by ravanmusayev2020** [flutter/flutter#119459]
I bought the fluxstore program, connects via API to the Wordpress site. The program works, but on the emulator it gives such an error.

FormatException (FormatException: Unexpected character (at character 1) ‰PNG ^ )

I deleted the entire image on the site but it didn't help. Deleted the flutter project and reopened it. There are many solutions on the Internet, but I could not change my code in any way, I'm afraid to break the whole application. The program works on the web, but when I open it on the emulator, it gives the following error.

I deleted the entire image on the site but it didn't help. Deleted the flutter project and reopened it. There are many solutions on the Internet, but I could not change my code in any way, I'm afraid to break the whole application. The program works on the web, but when I open it on the emulator, it gives the following error

**Comment by huycozy** [comment]
@ravanmusayev2020 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve Flutter framework/ Flutter 1st plugin/package reporting bugs or feature requests.

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
