### ISSUE TITLE
[webview_flutter] loadRequest not work.

### ISSUE THREAD

**Issue by JosephNK** [flutter/flutter#119488]
The part about loadRequest in @bparrishMines' answer to that issue doesn't work in release mode. #108801 
however, it seems to work in Flutter 3.7.0.
but I wonder why it doesn't work in Flutter 3.3.0.

Isn't it a plugin issue? Is this a flutter problem?

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.1 22C65 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by mozaddedalfeshani** [comment]
Is it worked with past update, on your machine?

**Comment by JosephNK** [comment]
@mozaddedalfeshani 

The code below doesn't work when in release mode.

```
WidgetsBinding.instance.addPostFrameCallback((_) async {
   _webViewController.loadRequest(Uri.parse('https://flutter.dev'));
});
```

**Comment by darshankawar** [comment]
@JosephNK 
Thanks for the report. [This](https://github.com/flutter/flutter/issues/108801#issuecomment-1405246606) comment from the linked issue explains where exactly the problem was and since seem to have been fixed.
Can you try using the latest version of https://pub.dev/packages/webview_flutter_android/changelog#321 and try your use case again in release mode (using real device) to see if the behavior you are seeing persists or works as expected ?
