### ISSUE TITLE
[androidx-migration]

### ISSUE THREAD

**Issue by AbdulazizAlshami** [flutter/flutter#119442]
Migrate to AndroidX
No usage found in the project

**Comment by darshankawar** [comment]
@AbdulazizAlshami 
`No usage found in project` indicates your project is already migrated to v2, but since you seem to be getting the error in console to follow the link to migrate, you don't seem to be on latest master or stable on which the error message that has the link has been fixed already: https://github.com/flutter/flutter/pull/107456

Check [this](https://github.com/flutter/flutter/issues/118231) issue and underlying comments. I don't know which flutter version you are on, but per the linked issue comment, the error message should be fixed on latest master and stable. Based on the explaination in that issue, I am going ahead and closing this. If you disagree, write in comments and I'll reopen it.
