### ISSUE TITLE
Add factory constructors for filled and outlined cards

### ISSUE THREAD

**Issue by guplem** [flutter/flutter#119401]
## Use case

Being able to create [all types of M3 cards](https://m3.material.io/components/cards/overview) with a simple constructor.

## Proposal

A constructor/factory like Card.outlined and Card.filled should exist apart from the default Card constructor (which should probably be the elevated card).

This should be part of the [M3 implementation](https://github.com/flutter/flutter/issues/91605#issuecomment-1406843465) in flutter

**Comment by guplem** [comment]
> @guplem This issue was covered here #113564

I see, but it has been closed and I don't think a proper explanation was made.

Other widgets such as IconButton variants can also be achieved by customizing the parameters of the default version. However they have opted for creating factories for each type (filled, final outlined, ...).

Why is IconButton getting factories for each variant and Card isn't?

**Comment by TekExplorer** [comment]
i think that it doesnt really make sense to have that inconsistency.
factory constructors also make it easier to discover and use M3 variants without having to actively look for them.
Not having them make for a worse DX, when I want a certain thing and don't realize it exists.
I ended up having to wrap the Card class because i wanted to be able to quickly swap between variants (or even just see what options i have at a glance)

plus, its not like they would be breaking anything...

**Comment by exaby73** [comment]
@guplem In 3.7, the factory constructors do not exist in 3.x for `IconButton`. The APIs seem to already be consistent, and the variants are documented on https://api.flutter.dev.  (https://api.flutter.dev/flutter/material/Card-class.html#material.Card.3)

Adding factory constructors makes it harder to maintain the APIs, since we would need to duplicate all the constructor arguments from the default constructor, into all the factory constructors. The removal of the `IconButton` factory constructors indicates that this is an intentional change and therefore, this is working as expected.

Due to the above reasons, I am closing this issue. Thank you

**Comment by guplem** [comment]
> @guplem In 3.7, the factory constructors do not exist in 3.x for `IconButton`. The APIs seem to already be consistent, and the variants are documented on https://api.flutter.dev. (https://api.flutter.dev/flutter/material/Card-class.html#material.Card.3)

I know, but I've seen this discussion arise many times.

Also, there is an issue related to the same topic for IconButton [here](https://github.com/flutter/flutter/issues/111800).

**Comment by exaby73** [comment]
Hey @guplem. Thanks for that catch :) I'll reopen and label this issue as per https://github.com/flutter/flutter/issues/91605#issuecomment-1406843465

**Comment by rydmike** [comment]
A few more things to perhaps consider if this implemented:

- The default vanilla/raw `Card` getting elevation tint on any supplied color, by default in M3 mode, when a widget color is provided, is confusing for many users. Example https://github.com/flutter/flutter/issues/122177
- The M3 spec also calls state changes on `hovered`, `focused`, `pressed`, `dragged` and `disabled`, it even varies a bit per Card variant, see https://m3.material.io/components/cards/specs.
- Maybe consider changing vanilla `Card` to not get elevation tint by default in M3, or at least not if a widget level `color` is provided.
- Introduce own variants for:
  - `Card.elevated` (replaces current behavior now represented by `Card`)
  - `Card.filled`
  - `Card.outlined``

These variant `Cards` should then have the correct tints and material state responses.

See related issue and discussion here: https://github.com/flutter/flutter/issues/122177#issuecomment-1460659409

**Comment by realitymolder** [comment]
Hello, I'm here to raise a concern.
Currently, in stable flutter (3.7.12) this issue for buttons got solved by their own widgets. 
It will make sense to make a factory constructor. But, with that said, there is a consistency issue while using different widgets in buttons. But with cards, there will be factory constructors?
