### ISSUE TITLE
Build a library AAR instead of APK

### ISSUE THREAD

**Issue by gdomingues** [flutter/flutter#11958]
Hi all,

I'd love adding Flutter to an existing app in the form of an Android library added to the existing project, but apparently that's not possible at this moment.

I skimmed through the docs and examples and couldn't find anything in that direction.

It it possible to do that, or is there at least something in sight for the near term future?

Thanks a lot for your hard work

**Comment by Nimrodda** [comment]
I guess what you're looking for is this: https://github.com/flutter/flutter/tree/master/examples/flutter_view
I haven't tried it, but you can most likely can convert it to produce an Android library (applying the android library gradle plugin, instead of the android app plugin) and use the generated AAR library wherever you want. You can go even fancier and publish the AAR to a maven repository and include it as a Gradle dependency.

**Comment by gdomingues** [comment]
There was no documentation explaining how to generate an Android library instead of an APK when I created this issue.

It seems there are an initiative going on that direction https://github.com/flutter/flutter/issues/14821 

I'll close this issue as the progress on this subject can be tracked over there.
