### ISSUE TITLE
[Desktop] add `.gitignore`s for generated plugin files

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#119544]
- [ ] Update flutter/flutter (app templates, examples, tests, etc..)
- [ ] Update gallery
- [ ] Update samples
- [ ] Do a pass to see if I missed anything

**Comment by loic-sharma** [comment]
@stuartmorgan Ah gotcha, thanks for the link! Do you think updating the templates' `.gitignore` is a worthwhile intermediary step until these files have been moved to the ephemeral directory?

**Comment by stuartmorgan** [comment]
That doesn't help anyone with an existing project though. The whole point of the `ephemeral` design in the desktop structure was to avoid the problem that I had seen happen a number of times on mobile where changes to `.gitignore` didn't help the majority of our users. The intent is that "should not be checked in" and "in ephemeral/" are identical concepts for those platforms.

I don't see why a behavior that we've had literally since the creation of the desktop tooling needs an intermediate step that violates the intended design of the folder structure. If we want to change to having the file be ephemeral, we should do so correctly.

**Comment by loic-sharma** [comment]
There's no urgency, I'm trying to better understand why desktop's `.gitignore`s are inconsistent with other app templates' and repos' `.gitignore`s:

https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/.gitignore#L103-L118

https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/packages/flutter_tools/templates/app_shared/ios.tmpl/.gitignore#L28

https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/packages/flutter_tools/templates/app_shared/android.tmpl/.gitignore#L7

https://github.com/flutter/samples/blob/f088262e2eb4dd1f4846846c89af50a03a5f6973/.gitignore#L31-L65

I completely agree that the `ephemeral` solution is correct long-term solution. I'll close this off since this is tracked by https://github.com/flutter/flutter/issues/76726

**Comment by stuartmorgan** [comment]
> I'm trying to better understand why desktop's `.gitignore`s are inconsistent with other app templates' and repos' `.gitignore`s:

> https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/.gitignore#L103-L118

Most likely someone decided that as long as it passed CI, it was fine in the context of flutter/flutter.

> https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/packages/flutter_tools/templates/app_shared/ios.tmpl/.gitignore#L28

> https://github.com/flutter/flutter/blob/edaeec8ed50beb2297ce85d5e61f0a8350995322/packages/flutter_tools/templates/app_shared/android.tmpl/.gitignore#L7

iOS and Android predate the `ephemeral` folder construct; I created it as part of setting up desktop in response to problems I had seen on those platforms, where everything was a one-off ignore, and then tooling would add a new file and suddenly everyone with an existing project would have a non-ignored file because changing the template's `gitignore` didn't help them.

(There is, I discovered unfortunately too late, a *totally different thing* called "ephemeral" for Android and iOS, which is for add-to-app and not for this.)

> https://github.com/flutter/samples/blob/f088262e2eb4dd1f4846846c89af50a03a5f6973/.gitignore#L31-L65

My guess is that this has a similar history to the flutter/plugin root `.gitignore`, which is that it's trying to do a repo-level correction for the problem I described above. If a new file is added by tooling, instead of updating N different examples to each ignore the new file, you just change one file in the repo.

Desktop platforms don't need that workaround because they don't have the problem in the first place.
