### ISSUE TITLE
How to modify CFBundleVersion

### ISSUE THREAD

**Issue by dd9913762113** [flutter/flutter#119779]
How to modify CFBundleVersion ？ 

<img width="614" alt="截屏2023-02-02 上午11 03 22" src="https://user-images.githubusercontent.com/85228967/216221327-3566be99-8d1c-43b1-985c-2ceff5e42ebc.png">

```
Bundle version string (short)  =>  $(FLUTTER_BUILD_NAME)
Bundle version  =>  $(FLUTTER_BUILD_NUMBER)

How to modify   $(FLUTTER_BUILD_NAME)  and   $(FLUTTER_BUILD_NUMBER)
```

```
ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. 
Rebuild your app using the current public (GM version of Xcode and resubmit it.

The App Store Team
```

**Comment by huycozy** [comment]
@dd9913762113 
Please check answers in these SO questions: 

https://stackoverflow.com/questions/57450618/user-defined-value-flutter-build-name-flutter-build-number-not-inherit-fro
https://stackoverflow.com/questions/54357468/how-to-set-build-and-version-number-of-flutter-app

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
