### ISSUE TITLE
Missing `errorText` and `helperText` parameters in M3 `DropdownMenu` 

### ISSUE THREAD

**Issue by gabrielbertollo** [flutter/flutter#119743]
## Steps to Reproduce

1. Add a DropdownMenu widget
2. Try to add errorText and helperText

**Expected results:** 
Show an error message and supporting text, similar to the DropdownButton.

**Actual results:**
The parameters for error and helper style are inside the InputDecorationTheme class, but not the parameters for the texts.

**Comment by exaby73** [comment]
## Triage report

Since dropdown menus can come in [_Text Field_ configuration](https://m3.material.io/components/menus/specs#15cc3423-ab1f-4d1c-8ce4-e5c9ae95f19f) according to the M3 specs, and a [Text Field can have supporting text](https://m3.material.io/components/text-fields/specs), I see this as a valid proposal. Labeling for further insights from the team
