### ISSUE TITLE
[Impeller] Rect blur has hard edge compared to Skia on artifacts discovery screen / wonderous.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#119974]
## Impeller

![flutter_01](https://user-images.githubusercontent.com/8975114/216732286-da93d1f0-8ba7-4c8a-ae64-d4cf110c9aa0.png)

## Skia

![flutter_02](https://user-images.githubusercontent.com/8975114/216732288-df24d731-7b67-4218-86b6-9d1c2438e351.png)

**Comment by gaaclarke** [comment]
This seems like a coverage bug where the calculated coverage is smaller than necessary so the subpass isn't the right size to capture the whole gradient.

**Comment by jonahwilliams** [comment]
I don't think this is a gradient though, its a box shadow that should be going through the RRect fast path here: https://github.com/flutter/engine/blob/main/impeller/entity/shaders/rrect_blur.frag

**Comment by gaaclarke** [comment]
I verified that this issue still exists at the following and that it can be reproduced on the simulator.

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.16.0-12.0.pre.76, on macOS 13.6 22G120
    darwin-arm64, locale en)
    • Flutter version 3.16.0-12.0.pre.76 on channel main at
      /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c03dac9a74 (25 hours ago), 2023-10-16 13:58:19 -0700
    • Engine revision c24f30343c
    • Dart version 3.3.0 (build 3.3.0-28.0.dev)
    • DevTools version 2.28.1
```

**Comment by gaaclarke** [comment]
The failure is happening as a result of `RRect Shadow`.  There doesn't appear to be a wrong sized texture, it is just the math inside of `rrect_blur_fragment_main` is not in sync with the geometry of the rect being drawn.
<img width="1614" alt="Screenshot 2023-10-19 at 3 21 45 PM" src="https://github.com/flutter/flutter/assets/30870216/0059f87f-6f72-47fb-bf77-e6b016303965">

**Comment by gaaclarke** [comment]
This can easily be reproduced with the following code:
```c++
TEST_P(AiksTest, Blur) {
  Canvas canvas;
  canvas.Scale(GetContentScale());
  canvas.DrawPaint({});
  Paint blur = {
      .color = Color::Green(),
      .mask_blur_descriptor =
          Paint::MaskBlurDescriptor{
              .style = FilterContents::BlurStyle::kNormal,
              .sigma = Sigma(47.6),
          },
  };
  canvas.DrawRect(Rect{100, 100, 200, 200}, blur);
  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```
<img width="707" alt="Screenshot 2023-10-20 at 11 17 25 AM" src="https://github.com/flutter/flutter/assets/30870216/a2f4294b-c101-4ae2-9861-9e5a645ec544">

**Comment by gaaclarke** [comment]
I audited the cpu work that is setting up the draw.  That seems correct to me.  I think the problem is in the math in the shader.  You can see that this blur splats out wider than the skia one in the x direction.  In the shader we are using `IPVec2FastGaussianIntegral`, I tried switching to `IPVec2GaussianIntegral` to make sure it isn't an error from our approximation.  The hard edge is still visible there.

We can hack a fix by adding a fudge number when calculating the geometry.  I'd rather see if we can fix the blur fragment shader though.

**Comment by gaaclarke** [comment]
Looks like Skia fudged for big sigmas too: https://skia.googlesource.com/skia/+/cf2131f85d57f938472e50b6643c3c2348709a55/gm/blurrect.cpp#484

**Comment by bdero** [comment]
Thanks! I think this is great for now, but I suspect that doubling the radius (which more than doubles the cost) is probably not going to be acceptable performance-wise for rrect shadows in the long run (we'll see what people say after the next g3 roll... there are a couple of apps that are known sensitive to this rrect blur path).

Another possible solution to this would be to attenuate the edges of the shader to 0 as we approach the edge. I've suggested this a few times during the Impeller meets and during our fidelity rundown, but never ended up writing it down here, sorry!

If you're interested in taking a look at improving the performance of this, lemme know and we can talk more. It's kind of a fun signal processing problem that I think you would enjoy @gaaclarke. :) Note that our rrect blur is visibly higher quality than Skia's here for these larger kernels (aside from the cutoff, of course), so there are some other levers we could pull to improve performance here as well if needed.

Also, we might need to increase the DL computed bounds for mask blurs if we roll with this solution, lest partial repaint could still cause weird cutoffs (perhaps @flar would know?).

**Comment by gaaclarke** [comment]
@bdero I thought about this a bit over the weekend.  I believe 4x is a good factor for the math as it stands since the sigma value is used for the standard deviation of the gaussian distribution.   95% of data falls within 2 standard deviations in a normal distribution, 99.99% falls within 4 standard deviations.

The reason this usually didn't show with 2x is because depending on the "sharpness" of the normal distribution; that last 5% may be below the sample rate.

One easy fix we could do to make this perform better is to modulate the padding based on the sigma.  Something like:
```c++
Scalar PaddingForSigma(Scalar sigma) {
  return sigma / kMaxSigma * 2.0 + 2.0;
}
```

I saw there is already a max sigma constant somewhere, we'd probably want to make that function exponential too, but you get the idea.

Related to the blur math we have another discussion about what to do with discrepancies with Skia's math.  I know we've said pixel perfect duplication isn't our goal but we have another issue where users are tweaking the skia math to the edge of just being visible, then they are invisible with impeller.  I'll raise the question in chat.

**Comment by gaaclarke** [comment]
I played around with this a lot this morning.  I first tried to solve the guassian distribution for a given sigma for the value 1/2^10 as a scalar on sigma, thinking that would be the limits of our rendering.  Turns out that was wrong and should probably be related to the area under the curve.

That became very difficult so I decided to eyeball it knowing we want some range between 2x and 4x.  I used polynomial regression to come up with a curve that looks like what we want and used the following test to look for hard edges
```c++
TEST_P(AiksTest, BlurHasNoEdge) {
  double fps = 60.0;
  double freq = 1.0/20.0;
  int64_t count = 0;
  double min_val = 1;
  double max_val = 250;
  double range = max_val - min_val;
  auto callback = [&](AiksContext& renderer) -> std::optional<Picture> {
    Canvas canvas;
    canvas.Scale(GetContentScale());
    canvas.DrawPaint({});
    double sigma = 0.5 * range * (sinf( (count++ * freq * 2.0 * 3.1415) / fps ) + 1.0);
    Paint blur = {
        .color = Color::Green(),
        .mask_blur_descriptor =
            Paint::MaskBlurDescriptor{
                .style = FilterContents::BlurStyle::kNormal,
                .sigma = Sigma(sigma),
            },
    };
    canvas.DrawRect(Rect{300, 300, 200, 200}, blur);
    return canvas.EndRecordingAsPicture();
  };
  ASSERT_TRUE(OpenPlaygroundHere(callback));
}
```

What I found is that our previous value of 2x has a hard edge even for small sigmas.  It's a poor value that we can't duplicate for performance without visual artifacts.  Every curve I tried still had some artifacts if you looked closely, 4x really is necessary given the current math.

**Comment by jonahwilliams** [comment]
If the concern is performance impact, we should be able to measure any regressions in GPU performance using the gpu_frame_time stats and an appropriate benchmark.
