### ISSUE TITLE
Error Failed to notify a WebView

### ISSUE THREAD

**Issue by abdulrojakdev** [flutter/flutter#120054]
D/EgretLoader(26934): EgretLoader(Context context)
D/EgretLoader(26934): The context is not activity
W/cr_media(26934): Requires BLUETOOTH permission
I/PlatformViewsController(26934): Hosting view in view hierarchy for platform view: 0
W/ContentCatcher(26934): Failed to notify a WebView
W/VideoCapabilities(26934): Unsupported mime video/divx
W/VideoCapabilities(26934): Unsupported mime video/divx311
W/VideoCapabilities(26934): Unsupported mime video/divx4
W/VideoCapabilities(26934): Unrecognized profile 4 for video/hevc
W/VideoCapabilities(26934): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(26934): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(26934): Unsupported profile 4 for video/mp4v-es
W/Utils   (26934): could not parse long range '175-174'

I do not know what is problem. Do you know how to solve this problem?

**Comment by huycozy** [comment]
Hi @abdulrojakdev 
Please try to provide all or some of the information indicated below so that we can address this issue properly.

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v` and the complete exception log
- Reproduction steps, Expected results, Actual results
- Which environment did this issue happen in? (Android/iOS)

Thank you!
