### ISSUE TITLE
[go_router] route inside a simple widget?

### ISSUE THREAD

**Issue by cavator** [flutter/flutter#120078]
why can't i just do
 ```dart
 Container(
  child: Router(
    route A,
    route B,
    route C,
   ),
)
 ```
 look at 
 https://reactnavigation.org/docs/getting-started/
 i can put a route anywhere i want, why in flutter is so confuse and hard do routes?
 why isn't simple as i supposed here, why put a route inside a MaterialApp, and create a giant route scheme, and more sometimes or most of the time the route isn't a Scaffold, why is so hard do it?

**Comment by huycozy** [comment]
Hi @cavator 
This looks like a proposal for a simpler router usage but it seems that it is not quite clear. Can you elaborate on this by specifying all information indicated in the template so that we can address this issue properly?

<details>
<summary>Issue Template (Proposal)</summary>

```
<!-- Thank you for using Flutter!

     If you are looking for support, please check out our documentation
     or consider asking a question on Stack Overflow:
      * https://flutter.dev/
      * https://api.flutter.dev/
      * https://stackoverflow.com/questions/tagged/flutter?sort=frequent

     If you have found a bug or if our documentation doesn't have an answer
     to what you're looking for, then fill out the template below. Please read
     our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
-->

## Use case

<!--
     Please tell us the problem you are running into that led to you wanting
     a new feature.

     Is your feature request related to a problem? Please give a clear and
     concise description of what the problem is.

     Describe the alternative solutions you've considered. Is there a package
     on pub.dev/flutter that already solves this?
-->

## Proposal

<!--
     Briefly but precisely describe what you would like Flutter to be able to do.

     Consider attaching something showing what you are imagining:
      * images
      * videos
      * code samples

     Does this have to be provided by Flutter directly, or can it be provided
     by a package on pub.dev/flutter? If so, maybe consider implementing and
     publishing such a package rather than filing a bug.
-->

```
</details>

Also, have you tried using [Navigator](https://api.flutter.dev/flutter/widgets/Navigator-class.html)? You may want to take a look at [Router design doc](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit) in case you haven't seen it.
