### ISSUE TITLE
App Crash While Selecting Image From gallery using Image_picker package.

### ISSUE THREAD

**Issue by arshad-dqot** [flutter/flutter#120157]
Code ->
`_imgFromGallery() async {
    final XFile? pickedFile = await _picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 150,
      maxHeight: 150,
      imageQuality: 30,
    );
    setState(() {
      _setImageFileListFromFile(pickedFile);
    });`

 Error ->
`W/OOMEventManagerFK(32746): Failed to mkdir /data/mqsas/hprof/
D/TransportRuntime.SQLiteEventStore(32746): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(32746): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-1978126517 in 1000ms(Backend next call timestamp 0). Attempt 1
I/Process (32746): Sending signal. PID: 32746 SIG: 9
Lost connection to device.`

**Comment by huycozy** [comment]
Hi @arshad-dqot 
Which `image_picker` plugin version are you using? 

Also, does the issue happen when reproducing this with [plugin sample code](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example)? If so, please provide the complete output of `flutter run -v` so that we may verify it. Thanks!
