### ISSUE TITLE
[camera] Need to set camera minZoomLevel less than 1

### ISSUE THREAD

**Issue by AshotKhachatryan1995** [flutter/flutter#120174]
Need to set camera min zoom level less than 1, Now minimum zoom level is 1.0.

**Comment by huycozy** [comment]
Hi @AshotKhachatryan1995 
I'm not sure which platform and OS version you are trying but it depends on the device and OS version as I can see. You can take a look at the plugin source code (Android for eg, you can figure out others as well):

- https://github.com/flutter/plugins/blob/6f985d57b04b268d7e99e579e486042991bf2a8c/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/features/zoomlevel/ZoomLevelFeature.java#L37-L48

- https://github.com/flutter/plugins/blob/6f985d57b04b268d7e99e579e486042991bf2a8c/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/CameraProperties.java#L348-L352

- https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#CONTROL_ZOOM_RATIO_RANGE

In case there is still an issue for this, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

Thank you!

**Comment by AshotKhachatryan1995** [comment]
Hi @huycozy.
Thanks for response, I found that my question is bit more other. 

My question is how can I use wide camera of device, but I found that it is an open issue. So I will close this one. Thanks.
