### ISSUE TITLE
running flutter application after upgrading to flutter 3.7.1 observing error Unable to create FlutterView; no MTLDevice or MTLCommandQueue available. macos

### ISSUE THREAD

**Issue by gopiKrishnaPuligundla** [flutter/flutter#120154]
I am observing below error if i run flutter desktop app after upgrade to flutter 3.7.1

Launching lib/main.dart on macOS in debug mode...
Building macOS application...
2023-02-07 10:23:17.492 rms[13634:109825] Could not acquire Metal device.
2023-02-07 10:23:17.501 rms[13634:109825] Unable to create FlutterView; no MTLDevice or MTLCommandQueue available.

please help

**Comment by darshankawar** [comment]
@gopiKrishnaPuligundla 
There's similar open issue describing your case https://github.com/flutter/flutter/issues/119994, so please follow-up in it for further updates. You may share your findings in that issue and also upvote the original one for team's attention.

Closing this as a duplicate.

**Comment by gopiKrishnaPuligundla** [comment]
hi darshankawar, 

I am facing its in physical device MacBook Air of early 2015 , and os it is running is Ventura 13.2.1 ,
 below is the flutter doctor output
bash-3.2$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening for further investigation.

**Comment by darshankawar** [comment]
@gopiKrishnaPuligundla 
I tried on my personal Macbook Air running on Mac OS X 10.15.2. Created a new flutter project using latest stable version (3.7.3) which worked fine without the reported error.
If you create a new project on 3.7.3 and run `flutter run -d macos`, do you still get the same error ? or it occurs only if you create a project in earlier versions, upgrade and then run same project which throws the error ?

**Comment by gopiKrishnaPuligundla** [comment]
Hi darshankawar,
please find output for flutter run -d macOS

bash-3.2$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                              7.6s
Building macOS application...                                           
2023-02-15 12:15:27.963 rms[2044:22983] Could not acquire Metal device.
2023-02-15 12:15:27.972 rms[2044:22983] Unable to create FlutterView; no MTLDevice or MTLCommandQueue available.

just wondering if an vm related flags are enabled , which is causing above issue, is there some debug command that I can run to root cause above issue ?

**Comment by darshankawar** [comment]
I am unable to replicate this on Macbook air running on Catalina per my [earlier verification](https://github.com/flutter/flutter/issues/120154#issuecomment-1430792005), so keeping this issue open and labeling for team's insights.

**Comment by cbracken** [comment]
@gopiKrishnaPuligundla quick question, is this happening on newly-created projects as well? 

Can you open the _System Information_ app, select the _Graphics_ item and paste the output here?

**Comment by gopiKrishnaPuligundla** [comment]
Hi cbracken,
Please find info 
graphics info :

Display:

  Type:	GPU
  Bus:	Built-In
  VRAM (Total):	5 MB
  VRAM (Dynamic, Max):	
  Vendor:	Intel
  Device ID:	0x1626
  Revision ID:	0x0009
  Kernel Extension Info:	No Kext Loaded
  Displays:
Unknown Display:
  Resolution:	1440x900 (Widescreen eXtended Graphics Array Plus)
  UI Looks like:	1440 x 900
  Framebuffer Depth:	24-Bit Colour (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes

**Comment by brokercl** [comment]
same issue

**Comment by cbracken** [comment]
@darshankawar you mentioned you've got a 2015 MacBook Air as well, on which this is working without issue. Would you mind also opening the _System Information_ app, selecting the _Graphics_ item and pasting the output here, for comparison with the output @gopiKrishnaPuligundla added?

And just to be 100% clear, @gopiKrishnaPuligundla you are running directly on your MacBook Air and not within a virtualised environment like VirtualBox or Parallels on the Mac?

**Comment by cbracken** [comment]
Hi folks,
Please avoid commenting [“me too”, “+1”, or similar](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs) on issues. Instead, please add a thumbs-up reaction to the issue. The team uses thumbs-up reactions as part of our issue prioritization process, so this will help get your issue addressed quicker. If you’d like to receive updates, click the subscribe button in the right-hand column.

@brokercl if you're running into this issue, can you provide the same information I requested above? Specifically:
* Open the System Information app, select the Graphics item and paste the output here.
* Paste the output of `flutter doctor` here.
* Confirm that you're not running in a virtualised environment like VirtualBox/Parallels.
* Report which exact Mac model you're running on.

**Comment by darshankawar** [comment]
> @darshankawar you mentioned you've got a 2015 MacBook Air as well, on which this is working without issue.
> 
> * Would you mind also opening the _System Information_ app, selecting the _Graphics_ item and pasting the output here, for comparison with the output @gopiKrishnaPuligundla added?

@cbracken Sure. Attached is the requested information.

<img width="694" alt="Screenshot 2023-03-06 at 5 26 40 PM" src="https://user-images.githubusercontent.com/67046386/223104052-e774ba4a-b9ca-42f2-b484-e8c5c6854c47.png">

**Comment by cbracken** [comment]
Thanks! @gopiKrishnaPuligundla would you mind replying with the same info?

**Comment by hillelcoren** [comment]
This error was also reported by one of our users, here are their graphics details.

![image](https://user-images.githubusercontent.com/4629496/223554840-87ca533b-75f3-49d5-9a4e-755acaf4056c.png)

**Comment by cbracken** [comment]
@hillelcoren can you verify they're running macOS 10.14, the [minimum supported macOS version](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms) and what Mac hardware they're running on?

It looks like the AMD Radeon HD 6750M shipped with the late-2011 15-inch MacBook Pro, which is unfortunately on Apple's [obsolete hardware](https://support.apple.com/en-us/HT201624) list and unsupported by Flutter, which requires macOS 10.14 and hence a Metal-capable GPU.

Flutter 3.7 should automatically have upgraded existing projects to set the minimum macOS deployment version to macOS 10.14 or, in cases where it was unable to, emit a warning message to the command-line. Can you verify your app's minimum deployment version is set to 10.14? You should be able to verify this in your project settings:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/351029/223575653-c019921c-dc33-4289-8529-af9ff7ae5bd1.png">

**Comment by hillelcoren** [comment]
The minimum macOS deployment version is set to 10.15.

Here's the hardware info they sent us.

![image](https://user-images.githubusercontent.com/4629496/223626908-8c147df5-2afb-4a4a-9953-b21ba72c1b1b.png)

Note: this uuser had previously installed the app and ran into the issue when upgrading to the latest version we released.

**Comment by khomin** [comment]
I have the same problem
Build in Monterey, i have to support Catalina because many users are still using it

`Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (6 weeks ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1`
<img width="654" alt="image" src="https://user-images.githubusercontent.com/7860640/225942226-69e7f2c7-5725-4b26-aa16-b5ece4a6bfb2.png">

**Comment by YarostheLaunchpadder** [comment]
Is there any fix for this, 3.3.10 works on Hackintosh but not 3.7.0 and above!!

**Comment by cbracken** [comment]
I'm going to de-duplicate this against https://github.com/flutter/flutter/issues/118469 which was files a little earlier. Please follow that issue.

@YarostheLaunchpadder Unfortunately, running macOS in a VM on non-macOS hardware isn't a scenario that we intend to support, since the terms of the macOS licence agreement require that macOS only be run on Apple-labelled computers. VMWare maintains a page on [Virtualizing Apple Mac OS X](https://kb.vmware.com/s/article/1000131) which states the same. I'm sympathetic, but we don't have bandwidth to support Hackintoshes. We'll gladly take any clean patches from the community that get things working for you though. 

OpenGL has been deprecated by Apple for over half a decade now (since WWDC 2018) and they have been very clear that Metal is how developers are expected to interact with the GPU. For the past few years, Flutter has retained OpenGL support on iOS/macOS devices to aid with backward compatibility for old devices, but doing so has been a huge amount of additional work and complexity in the embedders to support a very small fraction of the user base.

It is entirely possible to support Metal in a virtualised environment, and for those running VMWare Fusion 12.0 or Parallels Desktop 15 or later on Apple physical hardware, Metal support is built in, and everything should just work. It appears that on VMs supplied via GitHub Actions (perhaps among other CI providers) `MTLCreateSystemDefaultDevice` returns nil and therefore they don't support direct rendering using Metal - details at https://github.com/actions/runner-images/issues/1779. I'm not aware of the rationale behind this decision, although I expect it has to do with load-sharing among VMs running on the same physical host. Some related issues I see:
* https://github.com/maplibre/maplibre-gl-native/issues/78
* https://github.com/bluefireteam/audioplayers/issues/1405
* https://github.com/flutter/flutter/issues/118469

For these use-cases, supporting a CPU-rendering fallback seems like the most likely candidate for a workaround for CI systems that don't support Metal.
