### ISSUE TITLE
[linux] flutter doctor: ✗ Unable to find bundled Java version. (WORKAROUND)

### ISSUE THREAD

**Issue by ameuret** [flutter/flutter#120266]
## Steps to Reproduce

1. `sudo snap install flutter --classic`
2. Download android-studio-2022.1.1.20-linux.tar.gz
3. `tar xzf ~/Downloads/android-studio-2022.1.1.20-linux.tar.gz`
4. `cd android-studio/`
5. `bin/studio.sh`
6. More Actions -> SDK Manager
7. SDK Tools
8. Check box next to Android SDK Command-line Tools (Latest)
9. Press OK
10. Quit Android Studio
11. Make sure that `JAVA_HOME` refers to the `jbr` directory in `./android-studio`
12. Make sure that `java` is resolved in `./android-studio/jbr/bin`
13. `flutter doctor`

## Cause

The Android Studio 2022.1.1.20 package bundles the JRE in the `jbr` directory, flutter (stable) code path **for LINUX** looks for it in `jre`.

https://github.com/flutter/flutter/blob/7048ed95a5ad3e43d697e0c397464193991fc230/packages/flutter_tools/lib/src/android/android_studio.dart#L451

## Workaround

Create a symlink from `jbr` to `jre`:

```
ln -s jbr/ jre
```

**Comment by danagbemava-nc** [comment]
Hi @ameuret, this was initially reported in https://github.com/flutter/flutter/issues/106674 and has since been fixed on the master channel. See https://github.com/flutter/flutter/pull/120107

I'll be closing this since this has been fixed on the `master` channel. 

If you do experience this issue on the `master` channel, kindly leave a comment below and I will reopen this. 

Thank you
