### ISSUE TITLE
[impeller] Shader source debugging is hard to setup in Xcode frame debugger.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120326]
Xcode claims that the sources are missing. It otherwise works for Skia debugging though

**Comment by chinmaygarde** [comment]
Skia builds shader libraries from MSL source at runtime while Impeller compiles them to AIR metallibs. We need to embed the sources explicitly in perhaps the profile mode using `-fembed-sources`. If not, Xcode has no way to map the operations to source code.

**Comment by jonahwilliams** [comment]
Breadcrumbs: https://developer.apple.com/documentation/metal/shader_libraries/generating_and_loading_a_metal_library_symbol_file?language=objc

This seems to suggest that we can build a separate file with debugging info and then load that into xcode, because the embedded sources get stripped out anyway. Haven't tried yet, but will in the next day or so.

**Comment by chinmaygarde** [comment]
While shader source debugging is still not a turnkey operation due to versioning issues, https://github.com/flutter/engine/pull/39532 should make it possible to debug shader sources and access line by line profiling information.

I'm keeping this issue open because there is probably still more that we can do. But at this point, it is not clear what.

**Comment by chinmaygarde** [comment]
This is done but needs to be documented as the Xcode setup is a bit esoteric.
