### ISSUE TITLE
onNavigationRequest not working Reactjs

### ISSUE THREAD

**Issue by Baker-Koussa** [flutter/flutter#120437]
onNavigationRequest & onPageStarted isn't working on  the listener is not detecting Reactjs navigate(`/product/${productId}`); is there something wrong I am doing.

Reactjs side:

const navigate = useNavigate()

navigate(`/product/${productId}`);

flutter side:

onNavigationRequest: (request) {
print(request.url);//not printing on all listeners
}

**Comment by darshankawar** [comment]
@Baker-Koussa 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with. Simply saying `is there something wrong I am doing` indicates this issue is better suited for support channels like StackOverflow, so I suggest you to ask this question there.
If you think there's a genuine bug,  please provide all requested details using the template so that we can make the issue actionable.
Closing for now.
