### ISSUE TITLE
Flickering when adding a fully transparent spinner to a grid view

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#120455]
Forked from https://github.com/flutter/flutter/issues/100522#issuecomment-1425742347

The flickering looks a little different from the rest of that bug, and reproduces on both Android and iOS (although it is not entirely consistently reproduced on either). It seems to be raster cache related - @jason-simmons says disabling the raster cache made it go away on his Pixel 3. I reproduced it on an iPhone 11 and am still building an engine to see if it reproduces without the raster cache there. /cc @flar who might know what's up with that.

Sample app:

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: TestScreen()));
}

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.black,
        child: Stack(
          children: [
            Padding(
              padding: const EdgeInsets.only(top: 200),
              child: Stack(
                children: [_grid()],
              ),
            ),
            const Opacity(
              opacity: 0,
              child: CircularProgressIndicator(strokeWidth: 5, color: Colors.blue),
            ),
          ],
        ),
      ),
    );
  }

  Widget _grid() {
    return Align(
      alignment: Alignment.topCenter,
      child: Container(
        color: Colors.grey[200],
        child: GridView.count(
          crossAxisCount: 3,
          padding: const EdgeInsets.all(8),
          childAspectRatio: 1.2,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          children: _gridChildren(),
        ),
      ),
    );
  }

  List<Widget> _gridChildren() {
    List<Widget> list = [];
    for (int i = 1; i <= 12; i++) {
      list.add(
        Opacity(
          opacity: 0.3,
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: const Color(0xff002255).withOpacity(0.20),
                  blurRadius: 12,
                  spreadRadius: -1,
                  offset: const Offset(0, 3),
                )
              ],
            ),
            child: Center(
              child: Text(i.toString()),
            ),
          ),
        ),
      );
    }
    return list;
  }
}
```

Video:

https://user-images.githubusercontent.com/8620741/218159839-3b48dea4-1aff-4295-b551-66a89d1829ce.mp4

**Comment by jonahwilliams** [comment]
I'm not sure if the fully transparent spinner is actually having an impact here. I think the setup is roughly:

1. You have a grid view, each item is in its own layer due to automatic repaint boundaries.
2. You have an animated spinner, which has no impact on the rendering but causes each child to be marked dirty when it repaints.

Then you get some combination of some squares repainting and some not repainting. Could check with the checkerboard raster cache image feature.

**Comment by jonahwilliams** [comment]
and because of the partially opaque shadows, the rendering is different depending on if something is raster cached or not?

**Comment by dnfield** [comment]
I verified with a local engine on iOS that disabling the raster cache make this not reproduce.

**Comment by SixSheeppp** [comment]
I can reproduce this on my Android11 device. I found if put the app's  state to `AppLifecycleState.paused`, then bring it back to `AppLifecycleState.resumed` will make this issue reproduce easier.

**Comment by flar** [comment]
Bisected to https://github.com/flutter/flutter/pull/107403 which is an Engine roll with only a single PR: https://github.com/flutter/engine/pull/34562

**Comment by flar** [comment]
Note that this happens whether or not the Opacity is 0 or 1. This is interesting because the spinner child doesn't appear in the scene when opacity is 0 and yet it continues to cause repaints. The isRepaintBoundary field of RenderOpacity might need to be rethought. If the child is invisible due to lack of visibility, then that shouldn't make it transparent to repaints...?

**Comment by flar** [comment]
This is a bad interaction between caching and partial damage repaints. The cache isn't updated because the grid does not intersect the animated spinner, but it should also not be repainted at all, so that's a mystery...

**Comment by flar** [comment]
Hmmm, I'm not so sure that the indicated commit was the inception of the problem. I think it was more "the first commit where it reliably happened on startup". I've been testing with that same commit and simply adding logging info to the engine can cause it to repro or fail to repro.

One thing I noticed is that when it fails to repro, the repaint cycle stops. We seem to have something in there where even though the spinner is not visible, it still causes repaints to happen, but sometimes it stops triggering repaints. I was then able to get it to repro by launching the Performance Overlay which also causes constant repaints.

My current hypothesis is that we are getting damaged frame buffers and the partial repaint code is not noticing this so what is really happening is that we are cycling between a fully rendered frame buffer and one which was blank. As I said, still a hypothesis.

**Comment by flar** [comment]
OK, I've found the culprit. This problem should have happened from the earlier PR https://github.com/flutter/engine/pull/31892 but didn't manifest until https://github.com/flutter/engine/pull/34562 fixed a bug in it.

Basically, the problem is this line: https://github.com/flutter/engine/blob/4a90fbcd69011f8dd593840a0e901d2cede5398b/flow/layers/display_list_raster_cache_item.cc#L112

The logic there is "I am finally going to cache myself, and when I'm cached I can handle inherited opacity, so I will declare my layer as being able to inherit opacity". Unfortunately, even ignoring the fact that rasterization might fail (very unlikely) there is the very real possibility that one remaining test which isn't performed until we populate the cache - that we're only allowed 3 new cache entries per frame - could fail and thus lead to a case where we aren't actually going to be cached despite our best intentions as of the time that line is executed. As proof of concept, I fixed the bug in one of 2 disruptive ways - If I remove that line then the problem doesn't happen, but that means that we can't do opacity peephole optimizations for cached DLLayers - or if I change the per-frame caching threshold to a much larger number such that these layers aren't rejected during the population phase - in both cases the flashing goes away.

So, for a more responsible fix, we can either make that flag conditional on "and I already have a cache entry rendered" instead of just "hoping" that we will be cached - this will delay the opacity inheritance by a frame in a common case or several cases if there are a lot of DLs to cache. Or we can put protection in DLLayer::Paint such that if it ever reaches the manual paint code with an outstanding opacity and the DL isn't compatible with distributing the opacity - then it will perform its own protective saveLayer there.

@JsouLiang

**Comment by flar** [comment]
The problem described in the previous comment was verified by adding this debug assert and it did fail quite often in this example:

```
diff --git a/flow/layers/display_list_layer.cc b/flow/layers/display_list_layer.cc
index 7ba4feb727..d2e7b46cfd 100644
--- a/flow/layers/display_list_layer.cc
+++ b/flow/layers/display_list_layer.cc
@@ -162,6 +162,7 @@ void DisplayListLayer::Paint(PaintContext& context) const {
     auto restore = context.state_stack.applyState(display_list->bounds(), 0);
     context.builder->drawDisplayList(display_list);
   } else {
+    FML_DCHECK(opacity >= SK_Scalar1 || display_list()->can_apply_group_opacity());
     display_list()->RenderTo(context.canvas, opacity);
   }
 }
```
