### ISSUE TITLE
iOS Integration Test on Firebase Test Lab should fail

### ISSUE THREAD

**Issue by chengboonrong** [flutter/flutter#120422]
Hi there, I have been confused about this iOS integration testing result on Firebase Test Lab. As you can see the test result from Xcode test build was actually failed. 

<img width="1552" alt="截圖 2023-02-10 下午1 47 29" src="https://user-images.githubusercontent.com/21172662/218015176-78dabe57-a1b0-481b-8031-f533f6441692.png">

But when I using this command to build the XCTest file,

`xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/Runner_iphoneos16.2-arm64.xctestrun" -destination id=XXXXXXXX-XXXXXXXXXXXXXXXX`

and submit the product zip file which contains the `Release-iphoneos` folder and the `Runner_iphoneos16.2-arm64.xctestrun` file  to the Firebase Test Lab, the test result was success.

<img width="1158" alt="截圖 2023-02-10 下午1 50 34" src="https://user-images.githubusercontent.com/21172662/218011819-e52e77a8-3076-43ea-9eda-ff45b06919b5.png">

**EXPECTED RESULT ON FIREBASE TEST LAB : 
Should be failed as well, and showing the same error messages in Xcode test build.**

May I know what could be the possible condition that this will happen? Thanks in advance!

**Comment by darshankawar** [comment]
@chengboonrong 
As I understand from the description, the issue seems to be that FTL is reporting a false test result, so I suggest you to raise this issue at Firebase support : https://firebase.google.com/support/troubleshooter/contact?visit_id=638116203389306942-1573874866&rd=1 for further resolution, because FTL is a test lab for Flutter to run tests and may not have control over how tests executed there are controlled or handled. 
If you get directed here again claiming that this is an issue with Flutter iOS integration test, write in comments and I'll reopen it.
Closing for now.
