### ISSUE TITLE
Allow built-in EdgeDraggingAutoScroller of ReorderableList/SliverReorderableList to be configured

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#120479]
ReorderableList and SliverReorderableList contain an EdgeDraggingAutoScroller that advances the scroll position when dragging an item at the edge of the viewport. 

A customer has requested to be able to configure this behavior, specifically to adjust the speed. I think this would be the EdgeDraggingAutoScroller.velocityScalar. This could be added as a property that is provided to the internal EdgeDraggingAutoScroller

**Comment by shogohida** [comment]
Hi @Piinks, can I work on this?

> I think this would be the EdgeDraggingAutoScroller.velocityScalar. This could be added as a property that is provided to the internal EdgeDraggingAutoScroller

Is this part what you mentioned above?
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L999

**Comment by Piinks** [comment]
Hey @shogohida! Sure, you are more than welcome to work on it, thanks for contributing! :)

> Is this part what you mentioned above?

I think so, I have not dug too deeply on this. I think allowing a way to set the velocityScalar here might do it: 

https://github.com/flutter/flutter/blob/7c2d5b9c29d3f77ac6cc13577780fe77243889df/packages/flutter/lib/src/widgets/reorderable_list.dart#L611

Right now it looks like there isn't a way for folks to customize it.

**Comment by shogohida** [comment]
Thanks for your comment! I created a PR so please check it.

https://github.com/flutter/flutter/pull/120639

**Comment by gabrielgarciagava** [comment]
@shogohida are you implementing the tests requested on your PR? If not, could I pick this task?

**Comment by shogohida** [comment]
@gabrielgarciagava 
It's taking time but I'm trying to implement the tests

**Comment by gabrielgarciagava** [comment]
No problem then :)

**Comment by gabrielgarciagava** [comment]
Of course, @Piinks. I will try to address it during this weekend. Thank you.

**Comment by gabrielgarciagava** [comment]
@Piinks I have a question about the tests. Should I write tests that test the whole auto scroll functionality, or should I somehow inject `EdgeDraggingAutoScroller` and just check that it is being constructed and used properly?

I am not sure how you usually write the widget tests. Also, I'm not seeing any test testing `EdgeDraggingAutoScroller` itself, which I think is missing, so option 1 looks better in that sense.

Anyway, the solution is done (it is really simple indeed :P). For the tests, I will try following with option 1 meanwhile.

**Comment by gabrielgarciagava** [comment]
Writing the test is being a headache, but after some hours I finally find my way out, it should be done soon.

The biggest issue I was facing was that one item of the list (that was previously offstage) was reporting as onstage right after I started dragging one item. It took me a lot of time to debug but now I understand why. The reorderable list reduces the size of the dragged item to 0, and compensate everything with a matrix transform. So some items now think they are onstage, even though they are not because they were transformed out of it.

The test finder rely on it, basically. To be more specific, it relies on `debugVisitOnstageChildren`, who is not aware of the Transform matrix (AFAIK it only affects painting time, so it makes sense)

Anyway, sorry for the wall of text, but I will need to add some comments in the middle of the test to explain some of those things.

**Comment by Piinks** [comment]
Hey @gabrielgarciagava thanks for the updates! Happy to help with tests, I'll check out the PR. :)
