### ISSUE TITLE
Path.lerp

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12043]
There are a number of effects that would be substantially easier if it was possible to lerp between two Paths.

cc @abarth

**Comment by abarth** [comment]
You decided against this?  It sounded like a cool feature.

**Comment by dnfield** [comment]
I, too, would like to lerp paths.  

But doing so will require access to the underlying points/verbs in the path, and so would all have to be in the C++/Engine side.  It also involves some non-trivial algorithms.  @Hixie - this could be used to make icon animations, and there's a decent implementation in typescript [here](https://github.com/alexjlockwood/ShapeShifter/tree/master/src/app/scripts/algorithms) assuming you're only dealing with straight lines and cubic beziers.  I got here by looking at adding some shape or form of Flutter support to that application - implementing `Path.lerp` would make it trivial (and enable a lot of really nice effects/animations with something like `Tween<Path>`).

Mainly looking to ask: was this closed because of some architectural/performance issue?

**Comment by dnfield** [comment]
Actually, it should be possible by just exposing `SkPath::interpolate`...

**Comment by Hixie** [comment]
It's not at all clear what it means to lerp between some paths.

e.g. how do you lerp between a path that consists of moveTo, lineTo, moveTo, lineTo, to a path that consists of a single closed circle?

The other problem is that Path is mutable, but all our lerping infrastructure (e.g. Tween) assumes that begin and end points are immutable.

At the end of the day, all the use cases I had considered ended up being easier to do with hard-coded logic.

**Comment by dnfield** [comment]
Perhaps it'd be nice to have a simple path object can have the following properties:

1. Immutability
2. lerp-ability
3. Can be drawn on a canvas (perhaps through conversion to a path)

**Comment by creativecreatorormaybenot** [comment]
This would be such a useful feature and I agree with what @dnfield said. I think that for most effects the way the path was created does not matter, but what really matters is that all the points along the curves of the two paths are interpolated.

**Comment by jamesblasco** [comment]
I am working on a pseudo 3D library and I am using an immutable path object. It is an array of path commands. After I transform every point I  convert it to a path and paint it in the canvas.

I found this issue because I am interested in also implement lerp in the path. I would like to help implementing this. 

@creativecreatorormaybenot  But I wonder how I can interpolate paths with different amount of ref points. Maybe I could add the missing points at the beginning of the path but I think would look weird in some cases
