### ISSUE TITLE
Minified address bar is still an issue on web 

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#120496]
See #100046, not sure why it was closed

**Comment by iapicca** [comment]
the issue you are referring was closed because not enough information were provided
as for this [comment](https://github.com/flutter/flutter/issues/100046#issuecomment-1066774125) 

> Hi ShamshadSani, Thanks for filing the issue. If I understand it right when you launch https://werfie.com/minified:os in browser it throws 404 is that correct? if so please check this https://github.com/flutter/flutter/issues/89763#issuecomment-925040018
> If that is not the case then please update the issue description which clearly describes the issue.

also offers a possible solution from this [comment](https://github.com/flutter/flutter/issues/89763#issuecomment-925040018), did it work for you?

**Comment by darshankawar** [comment]
@cyberpwnn 
Apart from above comment, please provide all requested details present in the issue template so that we can address the issue properly.
