### ISSUE TITLE
Facing difficulties with the package video_player

### ISSUE THREAD

**Issue by MohamadAlahmad** [flutter/flutter#120550]
Hello,
I am developing an application with IPTV service.
I receive links from the backend for channels that will be shown as Stream or Live in the application, and the link for any channel is UDP.
I included the video_player package , and the application worked, but there are difficulties when playing for a list of channels, as this package does not support playlists , that is, there are no ready-made classes for that, as in some packages such as better_player, and there are few functions that can be called on the controller.
Also, **the main problem**, which I suffer from a lot, and because of it I write all of this, is the lack of provision for functions to deal with caches and buffers, as when changing between channels, I get a very slow playing of the channels. and when a new channel is opened, the image of the video either freezes and does not move, or it runs very slowly, which causes great inconvenience to the spectator.
Is there anyone who can tell me how is the best way to develop such applications through the use of this package or better than it?
Or are there improvements to these package with the additions that you mentioned, because I see that the video's colors when playing the video are very good in it … thanks for all

**Comment by a-ibrkh** [comment]
Hello! I understand your problem, because I was working on similar project and neither video_player nor better_player were a good decision for us, that's why I suggest that you do this feature using method channel and opening native video player, if you feel that these packages do not provide all necessary functionality for your requirements

**Comment by MohamadAlahmad** [comment]
> Hello! I understand your problem, because I was working on similar project and neither video_player nor better_player were a good decision for us, that's why I suggest that you do this feature using method channel and opening native video player, if you feel that these packages do not provide all necessary functionality for your requirements

thank you for replying …
Do you have a useful reference or a link to a specific explainer video or whatever, that can help me with that, because I consider myself something of a beginner at that.

**Comment by stuartmorgan** [comment]
> Is there anyone who can tell me how is the best way to develop such applications through the use of this package or better than it?

For advise on your own project, consider trying one of the resources listed at https://flutter.dev/community#community-grid. The issue tracker is specifically for feature requests and bug reports for Flutter, rather than advice or discussion.

Closing as this does not correspond to a specific feature request or bug report. (If you want to request specific features related to this topic, please file new issues for each feature request, filling out the feature request issue template.)
