### ISSUE TITLE
TextFormField missing magnifierConfiguration property

### ISSUE THREAD

**Issue by eyesoffish** [flutter/flutter#120655]
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (5 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

**Comment by danagbemava-nc** [comment]
Hi @eyesoffish, this was initially reported in https://github.com/flutter/flutter/issues/118029 and has since been fixed by
https://github.com/flutter/flutter/pull/118270. This feature is currently available on the `master` channel and should make it to `stable` sometime in the future. 

Closing this as this has already been fixed.

Thank you
