### ISSUE TITLE
flutter animation not smooth when dio http request

### ISSUE THREAD

**Issue by jsw-davidhuang** [flutter/flutter#120677]
as above,
when i do some http request in the void initState() function, then i test like: go in and out very quick, the page animation will get stuck some time , can i get any suggestions?

**Comment by huycozy** [comment]
Hi @jsw-davidhuang 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
