### ISSUE TITLE
After upgrade to 3.7:  Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }

### ISSUE THREAD

**Issue by vidinli2** [flutter/flutter#120749]
## Steps to Reproduce
I am not sure if you can reproduce this, but, my code was working with flutter 3.3.10, now, following problem occurs when tried to run on IntelliJ idea:
This is a page that displays a pdf using pdf library. (was previously working with same code)

Upon first run, following error:
Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }
require.js 168:17                                                                 makeError
require.js 1254:36                                                                intakeDefines
require.js 1446:21                                                                localRequire
require.js 1797:24                                                                requirejs
require.js 1805:16                                                                config
dart-sdk/lib/_internal/js_dev_runtime/patch/js_patch.dart 144:53                  callMethod
packages/printing/printing_web.dart 73:16                                         _initPlugin
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 558:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1587:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37367:58                              <fn>

Then, I just hit "hot restart", then, it shows pdf as expected.
I guess this is some kind of new bug in web renderer. I updated just now my IntelliJ idea Flutter plugin to have latest: "Flutter plugin for Android Studio 72.1"

my versions:
IntelliJ IDEA 2022.3.2 (Community Edition)
Build #IC-223.8617.56, built on January 26, 2023

Runtime version: 17.0.5+1-b653.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

$ >flutter --version
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (6 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

I cannot provide sample code, as it is long and unrelated. I gave error, in case anybody else live same situation and we may find a workaround. I will provide feedback when solved again.. 

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
flutter run --verbose  output related part: (actually same as normal debug output)

[ +465 ms] Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }
                    require.js 168:17                                                                 makeError
                    require.js 1254:36                                                                intakeDefines
                    require.js 1446:21                                                                localRequire
                    require.js 1797:24                                                                requirejs
                    require.js 1805:16                                                                config
                    dart-sdk/lib/_internal/js_dev_runtime/patch/js_patch.dart 144:53                  callMethod
                    packages/printing/printing_web.dart 73:16                                         _initPlugin
                    dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
                    dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
                    dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
                    dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
                    dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
                    dart-sdk/lib/async/future_impl.dart 558:7                                         [_complete]
                    dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
                    dart-sdk/lib/async/stream.dart 1587:7                                             <fn>
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
                    dart-sdk/lib/html/dart2js/html_dart2js.dart 37367:58                              <fn>



```

```
...
```

```
$ >flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.5.1 21G83 darwin-x64, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.4)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.


My issue is nothing to do with "doctor" issues, bc I was running code before upgrade. (I can still run if I downgrade).

```

</details>

**Comment by huycozy** [comment]
Hi @vidinli2 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Thank you!

**Comment by vidinli2** [comment]
"goal of this Github repo is not to give assistance on personal code" => exactly that's why, I did not provide code, and I am not expecting personal assistance.

I just wanted to give you (and community) some feedback about a possible problem, by providing you the error that I have seen. 

Maybe somebody living similar situation may write something and may help everybody.

The situation related to Flutter core is this, as I said:
the code does not work at start, but works after hot-restart. This, I think/guess, theoretically should be impossible. 
Just for your Info...

**Comment by huycozy** [comment]
Hi @vidinli2 
In this case, you described the error that is caused when you use the pdf library. In order to check if the issue belongs to the library or not, try removing the library and running it again. If the error doesn't appear anymore, it could be a library issue and you need a new issue file in that library's repository.

**Comment by antonio1612** [comment]
I'm having a very similar issue that's driving me crazy, I'm working with flutter web and I don't really know what made it happen but if I have my vscode debugger breakpoints set to All exceptions:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/42083801/221474897-74e48f2b-0454-42e4-9028-46149f3961ef.png">
Every time i save the file it vscode, the page won't update it would stay blank like this: 
![image](https://user-images.githubusercontent.com/42083801/221475108-7323b36b-69f6-4fa6-9c13-8485bb3ef928.png)
And the message about the hot restart would stay like this:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/42083801/221475180-4b73dcd8-bff2-4f11-907c-0a1194dbc104.png">
After trying to find why would it stay like this, I found its because chrome was stopping the debug or something that had never happened before:
![image](https://user-images.githubusercontent.com/42083801/221475427-4e434530-8eeb-4e60-a790-cda5201eaeee.png)
If I click the resume button on the chrome debugger it would continue and show my page like something never happened.
![image](https://user-images.githubusercontent.com/42083801/221476261-db247191-5820-4869-b3d0-d60ae1cdb808.png)
The chrome console won't show any errors and the debug console on vscode won't either 
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/42083801/221476318-bcecb292-ee08-4edf-94a8-1e8db4c934ea.png">


I've tested my code on a different pc and the same behavior happens both on Mac OS and windows 11.

At first I thought that maybe it was my code or something but, I tried creating a fresh flutter project and the same behavior happened, I tested it using the master branch for flutter.

I really hope the fix can be found soon because Its really tiring when I'm trying to debug my code.

Thank you guys in advance.
