### ISSUE TITLE
GestureDetector onScaleEnd ScaleEndDetails should report scaleVelocity

### ISSUE THREAD

**Issue by dantechguy** [flutter/flutter#120792]
## Use case

When using `GestureDetector`'s scale callbacks, you may want to see the current scaling velocity (similar to how you can see the velocity of the `onPanEnd` callback). A use case would be to animate a smooth zoom to rest (using `FrictionSimulation` or otherwise) rather than an immediate stop in zooming when the user lifts their fingers up.

## Proposal

Add a `scaleVelocity` property to `ScaleUpdateDetails` and `ScaleEndDetails`.

**Comment by moffatman** [comment]
I added it here already: https://github.com/flutter/flutter/pull/114280. It's only in the `master` channel at the moment.

**Comment by darshankawar** [comment]
@dantechguy 
Per above comment, since the property you proposed is already present in master, I am going ahead and closing this. You'll need to switch to latest master in order to see this fix.

`flutter channel master`
`flutter upgrade`

If you have any other comments on this issue, please reply and I'll reopen if required.
