### ISSUE TITLE
AssetImage should load an image appropriate for the device pixel ratio

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#1208]
Currently, we always load the same resolution PNG regardless of the current device pixel ratio.  Instead, we should use a MediaQuery to watch the device pixel ratio and then select an asset from the bundle that's appropriate to the current device pixel ratio.

**Comment by sethladd** [comment]
cc @FaisalAbid

**Comment by krisgiesing** [comment]
It looks like the relevant logic is in material's Icon class right now. Are you suggesting the logic be moved a layer down?

**Comment by krisgiesing** [comment]
Draft implementation of second strategy: https://github.com/flutter/flutter/pull/1209

**Comment by krisgiesing** [comment]
https://github.com/flutter/flutter/pull/1295/ includes most of the work to support resolution-appropriate image load.

Still to do: adjust the scaling on automatically selected images when the dimensions are not specified to the AssetImage.

**Comment by krisgiesing** [comment]
Addressed with #1295 and #1505.

We now establish an AssetVendor at the top of the tree that understands how to map a logical requested asset onto one that most closely matches the current device pixel ratio.  In order for this mapping to work, assets should be arranged according to a particular directory structure:

.../image.png
.../Mx/image.png
.../Nx/image.png
...etc.

where M and N are numeric identifiers that correspond to the nominal resolution of the images contained within.  The main asset is assumed to correspond to a resolution of 1.0.  For example, consider the following asset layout for an image named "my_icon.png":

.../my_icon.png
.../2.0x/my_icon.png
.../3.0x/my_icon.png

On devices with a device pixel ratio of 1.8, the asset ".../2.0x/my_icon.png" would be chosen.  For a device pixel ratio of 2.7, the asset ".../3.0x/my_icon.png" would be chosen.

If the width and height of the rendered image are not specified, the nominal resolution is used to scale the asset so that it will occupy the same amount of screen space as the main asset would have, just with a higher resolution.  That is, if ".../my_icon.png" is 72px by 72px, then ".../3.0x/my_icon.png" should be 216px by 216px; but they both will render into 72px by 72px (in logical pixels) if width and height are not specified.

**Comment by FaisalAbid** [comment]
I love this! Thanks @krisgiesing @sethladd

**Comment by duzenko** [comment]
How do I use this system when I only have one hi-dpi version (2.0x)?
In XCode assets I can only provide a 2x or 3x version and it will downscale automatically on 1x screens.
I don't like the prospect of manually resizing each and every icon I ever add to the app in the future.

**Comment by v7lin** [comment]
> How do I use this system when I only have one hi-dpi version (2.0x)?
> In XCode assets I can only provide a 2x or 3x version and it will downscale automatically on 1x screens.
> I don't like the prospect of manually resizing each and every icon I ever add to the app in the future.

i have same question.

**Comment by duzenko** [comment]
> 
> 
> > How do I use this system when I only have one hi-dpi version (2.0x)?
> > In XCode assets I can only provide a 2x or 3x version and it will downscale automatically on 1x screens.
> > I don't like the prospect of manually resizing each and every icon I ever add to the app in the future.
> 
> i have same question.

Use `scale` argument for the `Image.asset()` function
