### ISSUE TITLE
Fix slow post-submit tests due to Dashing

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120901]
The [Dashing](https://github.com/technosophos/dashing) docs builds caused timeout issues as they exceeded 60 minutes. As a short-term workaround, we increased the timeouts to 90 minutes (https://github.com/flutter/flutter/pull/120718, https://github.com/flutter/flutter/pull/120899).

Long-term solutions:

1. Make `Linux docs_test` not generate the docset in post-submit. This is redundant with `Linux docs_publish`.
2. Additionally, consider...
    1. Contribute performance improvements to Dashing
    2. Determine if offline docset is needed. If not, remove Dashing from `Linux docs_test` and `Linux docs_publish`
    3. Move docs build to GitHub Actions (similar to the coverage build)
    4. Marking docs build targets as `bringup`

Related: https://github.com/flutter/flutter/issues/115945

**Comment by Hixie** [comment]
It's not clear exactly what this shard does (it just says "name: Linux docs_publish", "recipe: flutter/flutter", but I don't know what to do with that; when I followed the breadcrumbs I got to https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/flutter/flutter.py which does not mention docs at all).

Could we get more information on how this is configured and so forth so that whoever wants to debug this problem knows where to start?

**Comment by Hixie** [comment]
Looking at the Flutter dashboard, it looks like these shards now take <30 minutes, FWIW. Maybe this is a non-issue now?

**Comment by goderbauer** [comment]
Closing this since it continues to not be an issue anymore.

**Comment by keyonghan** [comment]
F.Y.I. the docs tests execution time has been ~20mins: https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux%20docs_publishv
