### ISSUE TITLE
[web:canvaskit] excessive text layout in the web engine on material 3 demo

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#120921]
Switching between light and dark modes in the material 3 sample on the web is super janky. I haven't looked at HTML, but it does happen in CanvasKit mode. Profiling the app I see way too much text layout. Theoretically, there shouldn't be any layout at all, since only colors are changing. So even the framework shouldn't be laying out text.

But let's allow the framework re-layout text for some reason. The second problem is that the web engine re-lays out text during the _paint_ phase. I'm suspecting that something broke the heuristic that attempts to save memory by proactively deleting paragraphs and then restoring them on repaint.

![text-layout-on-paint](https://user-images.githubusercontent.com/211513/219496688-febbc2cb-dd40-4f19-a1d0-ae9a9745f7b4.png)

This is not right. We should fix this.

## Reproduction

1. `git clone git@github.com:flutter/samples.git`
2. `cd samples/material_3_demo`
3. `flutter run -d chrome --profile`
4. Toggle the "Brightness" switch and observe janky transition
5. Use Chrome DevTools' "Performance" tab to record a profile
6. Observe a lot of text layout present in the profile (similar to the picture above)

## Revisions

Flutter: `9a721c456d4a6418c60f2512cbb54ee420b9c69b`
Samples: `3e9bb78aec619065bbb29cfb1d20a80026c63818`

**Comment by Piinks** [comment]
I think this would benefit greatly from https://github.com/flutter/samples/issues/1694

In the components screen, the component sections are not being built lazily. Each section is one child of the list view, so a lot of text that is off screen is being laid out.

**Comment by HansMuller** [comment]
Making each component category card a SliverList per https://github.com/flutter/samples/issues/1694 is a good idea and would certainly reduce the number of widgets that get built and laid out. Unfortunately, at the moment it would be rather difficult to create the current demo visuals using Slivers. We'll need [SliverDecoration ](https://github.com/flutter/flutter/issues/107498) to create something like the Cards for each component category. 

The source of the performance problem here isn't just the cost of overbuilding etc widgets. Animation performance is still poor even when size of the window is reduced enough so that only one card from each column is visible.

**Comment by rydmike** [comment]
Based on experience with **much** more involved/complex theming apps than the Material 3 demo, I don't think it has any issue that needs much fixing. I noticed it contains what might be considered an unusual amount of RepaintBoundaries that one might not normally have felt the need to insert. Reading the discussion above I'm guessing some of them where added to try to fix the poor SKIA web build performance and its theme transitions.

The same very poor performance can be seen in other web apps too built with SKIA, plus larger SKIA web builds just crashes after a while now, where VM builds and web HTML builds remain stable.

This issue https://github.com/flutter/flutter/issues/122189 seems to be on the right track concerning the root cause.

**Comment by yjbanov** [comment]
Quick update: the "excessive text layout" in the engine that I claimed above is only partially responsible for the slow down. I have a PoC where I removed the old caching heuristic and shut-off unnecessary re-layouts, but that brought the worst frames (the brightness switch in the demo) from 150ms down to only 90ms on my M1 laptop. An improvement, but far from ideal (we should be able to layout way more text than what's on the UI in 90ms). The frame continues to be dominated by the _necessary_ text layout though (see comments by @HansMuller above).

I think the full fix for this will be what @jason-simmons is doing for https://github.com/flutter/flutter/issues/122189 (i.e. I agree with @rydmike's hypothesis).

In addition to the engine side, framework-side optimizations such as those suggested by @Piinks above could help even more.

**Comment by rydmike** [comment]
This SKIA PR https://github.com/TheRakeshPurohit/skia/commit/c5fd6f7497d9bea72d17965bb9f0cf818378c941 mentions the issue https://github.com/flutter/flutter/issues/122189 as a fix for it. Anyone has some insights on when we might see it in the engine in master? Would love to try it out, sounded promising.

**Comment by yjbanov** [comment]
Not sure about the timeline, but @jason-simmons is working on it

**Comment by HansMuller** [comment]
Unfortunately https://github.com/flutter/engine/pull/40617 doesn't appear to have had an effect on the light/dark animation's rendering performance.
