### ISSUE TITLE
[go_router] Url Path Strategy reloads the app when manually changing routes in the browser address bar

### ISSUE THREAD

**Issue by matheus-kirchesch-btor** [flutter/flutter#121063]
## How to reproduce
* In the go_router examples just run the main.dart after adding the `url_strategy` package and this line of code before runApp `setPathUrlStrategy();`
* After this you can run the application and change routes with the buttons, you will see it works normally, now change the address bar on the browser you will see the app reloading

## How to prove this is not expected behaviour
* Just run the app without the `url_strategy` addition and try to change routes in the browser address bar

The reason I included the `How to prove...` section is because I saw there is a closed issue where the issuer said that his logic was wrong, and someone else said changing the address bar should actually reload the app which is wrong

**Comment by exaby73** [comment]
Hello @matheus-kirchesch-btor. Unfortunately this is a limitation of the browser. For the browser, you are accessing a new page and the browser triggers a full reload. With the hash strategy, in the view of the browser, you are on the same page so it doesn't trigger a reload, and the routing is then handled by `go_router`.

Since this is not an issue with Flutter or `go_router` itself, and is working as expected, I will close this issue. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you
