### ISSUE TITLE
Flutter 3.7.4 version, when using Apple Pencil to slide the list, first set off the scribble function of Apple Penccil

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#121187]
Problem Demonstration Video :  https://github.com/zhoushuangjian001/pub_images/blob/master/apple_pencil_scribble.mp4

flutter doctor :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.4, on macOS 12.5 21G72 darwin-x64,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
    ! Error: iPad001 is busy: Fetching debug symbols for iPad001. Xcode will continue when iPad001 is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!
``` 

flutter --version:
```
Flutter 3.7.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b4bce91dd0 (25 hours ago) • 2023-02-21 09:50:50 +0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```

**Comment by huycozy** [comment]
Hi @zhoushuangjian001 
There is a patch fix for this issue recently for a [similar issue](https://github.com/flutter/flutter/issues/119180). Please try switching to the master channel and confirm if it's fixed or not. Thanks!

```
flutter channel master
flutter upgrade
```

**Comment by zhoushuangjian001** [comment]
@huycozy Our company requires development on stable, and we still hope that a certain version of stable can solve this problem

**Comment by huycozy** [comment]
@zhoushuangjian001 You can read more about the build release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels. And also take a look at these documents for more information:

- https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release
- https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

I'll be closing this issue since it has already been fixed on the latest master channel. If you still experience this issue on the latest master channel, kindly leave a comment below and I will reopen this. Thank you!
