### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter.

### ISSUE THREAD

**Issue by krmeiirbek** [flutter/flutter#121398]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

======== Exception caught by services library ====================================================== The following assertion was thrown during a platform message callback: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#cc584(physicalKey: PhysicalKeyboardKey#c222c(usbHidUsage: "0x0007001d", debugName: "Key Z"), logicalKey: LogicalKeyboardKey#5989a(keyId: "0x0000007a", keyLabel: "Z", debugName: "Key Z"), character: null, timeStamp: 22:47:21.519077) 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

</details>

**Comment by huycozy** [comment]
I updated the title and moved it to Logs for better readability. Next time, when opening the issue, please try to provide the information in the correct fields so that others who are also facing the issue can see it better.

To be more precise, please provide the information indicated below:
- Reproduction steps
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`, `flutter run -v`
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

Thank you!
