### ISSUE TITLE
In duration class I am unable to add months for the date

### ISSUE THREAD

**Issue by vuppalasivakumar** [flutter/flutter#12141]
I want add 10months after current date but we have only provision upto dates can any one add months  provision also 

```dart
 _toDate = today.add(new Duration(days: 10));
 const Duration(
      {int days: 0,
      int hours: 0,
      int minutes: 0,
      int seconds: 0,
      int milliseconds: 0,
      int microseconds: 0})
      : this._microseconds(MICROSECONDS_PER_DAY * days +
            MICROSECONDS_PER_HOUR * hours +
            MICROSECONDS_PER_MINUTE * minutes +
            MICROSECONDS_PER_SECOND * seconds +
            MICROSECONDS_PER_MILLISECOND * milliseconds +
            microseconds);
```

**Comment by Hixie** [comment]
How many seconds does a month last?

**Comment by eseidelGoogle** [comment]
This has come up before.  There is some other way to do calendar math in Dart iirc.  I just don't recall what it is.  @kevmoo would know.

**Comment by floitschG** [comment]
Durations don't have months, because a duration is independent of the location and moment-in-time. However, the length of a month is dependent on exactly that (adding a month in february is shorter than adding one in January. Similarly, adding a month while there is a leap-year or daylight saving change makes a difference).

There is currently no easy way to add one month to a specific date. It's one of the big changes to the core libraries for dart 2.0.

In the meantime the safest is to build a new DateTime with all the arguments passed in, but adding 1 to the month: `new DateTime(other.year, other.month + 1, other.day, other.hour, ...)`.
Even then you still need to pay attention, though: what should it mean to add a month to the 31st of March? With the simple approach above, you would end up at `May 1st`.
If that's not what you want, you have to clamp the months. That requires a bit more code (including knowing when there are leap years).

**Comment by Hixie** [comment]
The last comment above pretty much covers everything there is to say about this, I think.

**Comment by cosinus84** [comment]
Yes it says all and that Dart should add new methods to date and time. Moment js did a pretty good job with date&time
