### ISSUE TITLE
Migrate packages repo to use flutter.compileSdkVersion

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#121425]
flutter.compileSdkVersion is defined in the flutter project and helps migrate all examples to the compile sdk version that is defined by flutter instead of the one hardcoded during project creation. The `flutter create` tool has already been updated but any previously defined examples used hardcoded values. 

Updating compileSdkVersion is expected to have no runtime modifications to code and generally should be set to the highest version published by android.

**Comment by stuartmorgan** [comment]
Something that just occurred to me: the combination of this and https://github.com/flutter/packages/pull/3293 will mean that updating `flutter.compileSdkVersion` in flutter/flutter will potentially break the flutter/flutter->flutter/packages roller because it can introduce new deprecation warnings.

I don't think it's a problem, just something we should have a plan for dealing with. (E.g., when it happens we temporarily change affected plugins to a hard-coded version with a TODO to change it back, referencing an issue, so that the roller gets unblocked and the deprecation warnings can be fixed as a follow-up.)

**Comment by jmagman** [comment]
> The `flutter create` tool has already been updated but any previously defined examples used hardcoded values.

Consider adding a migrator for this so developers on older Flutter created projects don't need to change it manually:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/lib/src/ios/migrations
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/lib/src/migrations

**Comment by reidbaker** [comment]
> > The `flutter create` tool has already been updated but any previously defined examples used hardcoded values.
> 
> Consider adding a migrator for this so developers on older Flutter created projects don't need to change it manually: https://github.com/flutter/flutter/tree/master/packages/flutter_tools/lib/src/ios/migrations https://github.com/flutter/flutter/tree/master/packages/flutter_tools/lib/src/migrations

Filed and issue #121824 to track building a migrator. Closing this issue as resolved for the packages repository.
