### ISSUE TITLE
[Impeller] Document how to debug generated Metal shaders.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#121430]
Today, you have to tell Xcode where to find the symbol file for generated shader libraries. It's a file with the `.metalsym` extension in the out directory. However, this isn't documented. Also, there are version restrictions on the iOS/macOS platforms that can actually do line by line shader debugging and profiling. These nuances must be documented as well.

**Comment by bdero** [comment]
I've come back around to try and get shader compilation to work a few times so that we can get a working configuration documented, but unfortunately I've never gotten this to work on iOS (I did have it working [on the macOS playground](https://github.com/flutter/engine/pull/39532#issuecomment-1425312697) at one point, but I haven't been able to replicate it for a few attempts over the past couple of months).

Original issue to make shader debugging easier is https://github.com/flutter/flutter/issues/120326.

**Comment by bdero** [comment]
Three recent debugging sessions where I attempted to invoke the shader debugger on iOS:
* https://github.com/flutter/engine/pull/41391
* https://github.com/flutter/engine/pull/42069
* https://github.com/flutter/engine/pull/42386

**Comment by knopp** [comment]
The "Invalid UUID" message with wrong minimum iOS version is great. Two hours well spent.

**Comment by chinmaygarde** [comment]
I documented the workaround in https://github.com/flutter/engine/pull/44195 but I'm afraid it might not be the most discoverable doc. Did you find it? Where did you look? How can be surface this better?
