### ISSUE TITLE
Add a method to NavigationState for adding routes below

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12146]
Based on https://stackoverflow.com/questions/46259751/how-to-push-multiple-routes-with-flutter-navigator

## Steps to Reproduce

Import `package:flutter/scheduler.dart` and set `timeDilation = 100;`

Push two routes one right after the other:

```dart
    Navigator.push(
      context,
      new MaterialPageRoute(
        builder: (BuildContext context) {
          return new Scaffold();
        },
      ),
    );
    Navigator.push(
      context,
      new MaterialPageRoute(
        builder: (BuildContext context) {
          return new Scaffold(
            appBar: new AppBar(
              title: new Text('42'),
            ),
          );
        },
      ),
```

You'll see the white blank route transitions faster than the route with the app bar, on iOS.

![untitled](https://user-images.githubusercontent.com/394889/30556796-eee2480a-9c60-11e7-9c80-e3085e14a195.gif)

Instead we should provide a way to insert routes underneath the current one, once the animation completes. (`ModalRoute` provides an `animation` property that we might be able to use to delay the insertion until the initial route's transition is complete.)

**Comment by Hixie** [comment]
Should be relatively straight-forward, basically a mix of how we do `replace` and `push` today.

**Comment by sroddy** [comment]
While attempting to fix this in #14490 I've discovered that there is actually something less trivial than I though in order to properly support this feature.

1) OverlayState does not currently support inserting layers at arbitrary indexes.
in order to fully deal with precise timing with animations we need callbacks or events that can be listened to, when push/pop animations complete (e.g. a didPush void callback argument in the push() method);
2) It appears that calling route.didReplace(null) is not enough to actually insert a route properly, I still see some visual glitches when popping a route with a previously inserted route using this method and I also hit some failed asserts in some specific setups;
3) In order to fully deal with precise timing with animations we need callbacks or events that can be listened to, when push/pop animations complete (e.g. a didPush void callback argument in the push() method);
4) In general I'm not really convinced about the current API of the Navigator. I think that a declarative approach may be better. In other words, be able to provide/modify the stack of the desired routes by directly placing them where desired (a bit like what is already being done when building Widgets tree), and have the Navigator automatically deal with that by inserting/replacing/removing/pushing/popping them in its overlay. I understand that this approach would cause some problems in the way results are currently returned during push/pop, but these could be tackled in other ways, and I think it would also be much more coherent to the way things are actually built with Flutter, which I like a lot.

**Comment by lukaspili** [comment]
Agree with @sroddy on 4). 
Navigation is such an important part of application development and in my opinion, current mobile framework (flutter, cocoa and especially android sdk) failed to provide a simple but flexible API.

I would be delighted to see Flutter offer a small revolution here.

**Comment by jsroest** [comment]
I had some discussion with @mehmetf and would like to add my thoughts on this issue.

1. I need to recreate the navigation stack on program start. That means I will have to push multiple screens to the stack at once.

1. If a page is about to be shown on screen (pushed or popped), I would like to be able to push/pop other pages. This improves separation of concerns, because the business logic of the page knows possibly the best if it has to be skipped or not.

Both points have a relation with the original issue which will become clear in my explanation here below.

**Explanation point 1**
Assume I will give all my routes a name, the same name as my pages, and I might have a widget tree like this:

- S100 Main menu
  - S200 Order pick
    - S210 Select order
      - S220 Confirm pick location
        - S230 Pick nr of pieces
          - S240 Report shortage 

So S240 is now the screen that the user sees.

Suppose the app is killed and restarted. I can navigate right away to my named route S240 but then my widget tree will look like this:

- S240 Report shortage

The problem is that when I press back, it will close the program. The whole navigation stack/widget tree is not rebuild on application start.

**Explanation point 2**
Sometimes the best place to make decisions about navigation, is in the page that is about to be shown. For example, if 'S210 Select order' is about to be shown, the page may query the number of lines available and do some logic:

- **Number of rows == 0**
there is no need to show the list as there are no items, show message 'No orders available' and then pop screen of stack

- **Number of rows == 1**
there is no need to show the list as there is only 1 item available, push S220 on the stack

- **Number of rows > 1**
do not change navigation stack anymore, let the user select an order from this page

Of course both options (point 1/ point 2) have to be possible without showing navigation glitches. We need a solution that is not based on 'precise timings'.  Therefore we need a point in time when it is absolutely sure that a navigation has to be performed from one screen to another screen.

Something similar is the .commit function in Android.
https://developer.android.com/reference/android/support/v4/app/FragmentTransaction#commit

Only that function is 'static', the route may not change along the way.

I suggest another implementation. I have a similar solution in C# (Xamarin), served my navigation needs for years. The interface for that implementation is shown here below.

```
/// Fired when the screen is on top of the stack. Can be used to skip screens
/// </summary>
/// <param name="stackChange">Describes how it came on top (PushedOnTop/ReturnedFromScreen)</param>
/// <param name="previousScreen">A reference to the previous screen</param>
Task ScreenOnTop(DalNavigation.StackChangeEnum stackChange, View previousScreen);

/// <summary>
/// Fired when the screen is actually about to be shown. No changes to the ScreenStack are allowed anymore
/// </summary>
Task ScreenIsShown();

/// <summary>
/// Fired when the screen is about to be popped. Prevent popping by returning false, otherwise return true
/// </summary>
/// <returns></returns>
Task<bool> ScreenIsPopping();
```

If someone is interested, I could post the actual implementation in C# also.

**Comment by mehmetf** [comment]
@jsroest Thanks for the explanation. Your first point is squarely related to this issue but the second point is not. Your second point is suggesting a different way of implementing navigation which requires discussion. I have a couple of suggestions that you can try out. I suggest editing the comment above and leaving only point 1 and opening a new issue for point 2. We can discuss my suggestions on the new issue.

**Comment by tedhenry100** [comment]
I'm new to Flutter. The first experiment I'm trying to see if I can/will rewrite my production app with Flutter involves recreating the stack on app launch as @jsroest described. Is there a workaround that can be used now?

**Comment by jsroest** [comment]
@tedhenry100 I am working on something, i think it will be ready as proof of concept in a week or two.

**Comment by sir-boformer** [comment]
I'm supporting this. It would also be nice if there were more ways to access and modify the history.

**Comment by ThinkDigitalSoftware** [comment]
@jsoref I would be interested in seeing this. I'm looking for a way to access the Navigator details directly. Like what's on the stack and where? Is it currently transitioning? etc

**Comment by jsoref** [comment]
@ThinkDigitalSoftware I think you meant @jsroest

**Comment by gapspt** [comment]
Is there any progress going on on thins feature?

**Comment by HofmannZ** [comment]
@Hixie This is kinda blocking our development right now. Any updates, or anything I can do to help?

**Comment by chunhtai** [comment]
This will be supported with Navigator 2.0 See https://github.com/flutter/flutter/issues/45938

**Comment by orestesgaolin** [comment]
It's possible right now with [Navigator.pages](https://api.flutter.dev/flutter/widgets/Navigator/pages.html)

**Comment by orestesgaolin** [comment]
Just to clarify how this can be achieved with `Navigator.pages` [here's the DartPad sample](https://dartpad.dartlang.org/89a4da6822fb642692096a7ff8036a68) with usage of setState. It could be much more convenient with some kind of common class for handling the navigation, but for simplicity let's just pass callback to update list of pages. The key is to notify `Navigator` that the list of pages has changed, that's why list is recreated via `List.unmodifiable()` or `List.of()`.

![CleanShot 2020-09-04 at 10 07 40](https://user-images.githubusercontent.com/16854239/92216395-890c2100-ee96-11ea-809d-3e1dd55263d7.gif)

And the same with `timeDilation = 20`:

![CleanShot 2020-09-04 at 10 10 23](https://user-images.githubusercontent.com/16854239/92216668-e3a57d00-ee96-11ea-9cdf-e722da737ec5.gif)

**Comment by johnpryan** [comment]
That's a great example @orestesgaolin. 

I think this can be closed, since this works in the master channel. Please reply if you think this is still an issue.
