### ISSUE TITLE
Raster cache downsamples sometimes?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12148]
My understanding from @abarth and @jamesr is that we should fix bugs like https://github.com/flutter/flutter/issues/12091 by changing our raster cache to either render directly to physical pixels (currently it converts back to logical when rendering cached layers) or by saving the logical coordinates in their expanded integer form?

This is mostly a note for @chinmaygarde when he returns to discuss with @abarth

**Comment by eseidelGoogle** [comment]
Where cached layers are created:
https://github.com/flutter/engine/blob/master/flow/raster_cache.cc#L71

Where they are played back:
https://github.com/flutter/engine/blob/master/flow/layers/picture_layer.cc#L34

**Comment by abarth** [comment]
The idea we discussed at lunch:

Rather than trying to use drawImageRect to undo the scales that's already pushed onto the transform stack, we could:

1) Read the current matrix of the canvas.
2) Set the matrix of the canvas to have the appropriate translation/rotation/etc but without the scale.
3) Draw from the cached texture without any scaling.
4) Restore the matrix read in step (1).

This will prevent us from trying to cancel out one scale with an inverse scale, which is numerically dubious.

**Comment by chinmaygarde** [comment]
Just catching up on the issues I missed when I was away. Is there a reduced test case for this? I saw a fix related to this in https://github.com/flutter/engine/pull/4116. But, I am not convinced that fixes https://github.com/flutter/flutter/issues/12091. If it does (and that issue is already closed), can we close this too?

**Comment by eseidelGoogle** [comment]
This was opened based on my understanding from talking to @abarth and @jamesr that the fix we made for #12091 is just papering over a lower issue. I recommend chatting with @abarth

**Comment by Hixie** [comment]
cc @liyuqian — this may be relevant to your current interests

**Comment by liyuqian** [comment]
This should be fixed by https://github.com/flutter/engine/pull/5315
