### ISSUE TITLE
Touch pointer move a lot. The moving distance of X is:22.0, limit is:50The moving distance of Y is:53.875, limit is:50

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#121496]
This problem is a problem that occurs on Huawei's tablet after repeating gestures many times。

flutter --version:
Flutter 3.7.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c07f788888 (4 days ago) • 2023-02-22 17:52:33 -0600
Engine • revision 0f359063c4
Tools • Dart 2.19.2 • DevTools 2.20.1

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)

**Comment by danagbemava-nc** [comment]
Hi @zhoushuangjian001,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

A recording/screenshot or any log that captures the issue would also be appreciated.  

Thank you
