### ISSUE TITLE
Improve error message when Directionality widget is missing in scope

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#12152]
## Steps to Reproduce

This happens while running the tests for the flutter_markdown library against the current version of Flutter.

## Logs
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MarkdownBody(state: _MarkdownWidgetState#8b946):
A RichText was created with no textDirection and no ambient Directionality widget.
'package:flutter/src/widgets/basic.dart': Failed assertion: line 3796 pos 12: 'direction != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:3796:12)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4170:28)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900:14)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4643:32)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900:14)
#7      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4643:32)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2703:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674:22)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2703:12)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:759:16)
#18     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:737:5)
#19     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:751:7)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2261:33)
#22     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:589:18)
#23     BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194:5)
#24     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
#25     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
#26     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:558:9)
#29     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#30     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:546:27)
#31     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:22)
#34     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#35     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:186:27)
#36     main.<anonymous closure> (///usr/local/google/home/djshuckerow/Open/github.com/DaveShuckerow/flutter_markdown/test/flutter_markdown_test.dart:102:18)
<asynchronous suspension>
#37     testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:58:25)
#38     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:457:19)
<asynchronous suspension>
#41     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:444:14)
#42     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:625:24)
#48     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:623:16)
#49     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:57:24)
#50     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:139:19)
<asynchronous suspension>
#51     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:206:15)
<asynchronous suspension>
#55     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:203:5)
#56     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:137:29)
<asynchronous suspension>
#57     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:351:23)
<asynchronous suspension>
#72     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:367)
#73     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:401)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
(elided 30 frames from class _AssertionError, class _FakeAsync, package dart:async, package
dart:async-patch, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at ...
    • Framework revision 88cd043d01 (32 minutes ago), 2017-09-18 13:42:06 -0700
    • Engine revision 82fb559566
    • Tools Dart version 1.25.0-dev.11.0
...
```

**Comment by DaveShuckerow** [comment]
It looks like the introduction of Directionality and allowing it to be null is breaking the ability to pump a text widget that isn't wrapped in a Theme.

This can potentially make testing very complicated.  I think the best fix is to adjust WidgetTester to provide a default directionality when pumping widgets under tests, and tests can provide a different direction if need be.

**Comment by mehmetf** [comment]
It might be worth enhancing the WidgetTester platform to provide a default "parent" for the widgets to be tested. Leafy does this today manually by transforming every single `tester.pumpWidget(widget)` call to `tester.pumpWidget(new MaterialApp(home: widget))`.

This makes sense to me because you _should_ be testing the widget in the environment that it is normally found in (potentially with the theme and other app specific properties).

**Comment by Hixie** [comment]
The problem is that you can't just use MaterialApp or whatever -- because you're going to want to test the widget in LTR and RTL, in various localizations, with different MediaQuerys, etc.

BTW the message above says you need a `Directionality`, not `Theme`.

**Comment by mehmetf** [comment]
I am trying to understand this.
- Is it still necessary to test all that in a non-translated app?
- Why would the API force me to specify Directionality but not Locale or MediaQuery?

**Comment by Hixie** [comment]
> Is it still necessary to test all that in a non-translated app? 

If you're building an app, then you should test whatever your app supports. Your app probably uses MaterialApp, so I would make sure your test does too.

If you're building a reusable widget, then you should test whatever environments it might be used in.

> Why would the API force me to specify Directionality but not Locale or MediaQuery?

Depends an which API you mean. If you're asking about `RichText` specifically, it needs a Directionality to know what direction to draw the text (e.g. if the text is "english1 hebrew english2", does the "english1" part appear on the left or the right of the hebrew part?). It doesn't need a MediaQuery because it isn't affected by the pixel density or the padding or whatnot. There are other widgets that want a MediaQuery and not a Directionality.

In due course, I expect RichText will in fact care about a Locale, because we'll need to do locale-sensitive font selection for proper rendering of CJK glyphs. But we haven't implemented that yet.

**Comment by mehmetf** [comment]
> If you're building an app, then you should test whatever your app supports. Your app probably uses MaterialApp, so I would make sure your test does too.

Exactly. So I am asking: Should we help people write tests that default to whatever their app supports?

If my app/widget uses Locale, MediaQuery or Directionality, then it is reasonable to expect that my tests do too. However, if none of the app code that I write ever mentions any of these things, I don't understand why my tests need to.

That's why I was proposing that WidgetTester is a bit more versatile in letting test writers specify the "environment" the widget should be placed in (ideally the same environment as the app provides).

**Comment by Hixie** [comment]
> If my app/widget uses Locale, MediaQuery or Directionality, then it is reasonable to expect that my tests do too. However, if none of the app code that I write ever mentions any of these things, I don't understand why my tests need to.

Presumably one's app uses - and mentions - MaterialApp, and therefore it is reasonable that the tests would too.

I'm certainly fine with making the API more flexible, but I don't really know what we could do to make it more flexible than what we have now (which accepts anything at all).

**Comment by mehmetf** [comment]
I will send you what Leafy does so you can see if a pattern can be extracted to the Flutter test library.

**Comment by mehmetf** [comment]
We expose a function like this in our common test utility:

```dart
Future<Null> pumpWithMaterial(WidgetTester tester, Widget widget) async {
  await tester.pumpWidget(new MaterialApp(home: new Material(child: widget)));
}
```

and then use this throughout:

```dart
await pumpWithMaterial(tester, widget);
```

What we found is that even with a small number of developers (5), it gets tricky to decide when to use pumpWithMaterial vs pumpWidget. So we have a blanket requirement to always use pumpWithMaterial to avoid potential issues when underlying widget changes. Stuff still falls through the cracks because the API is just so easy to use. `tester` gets passed in and naturally people want to do:

`tester.<autocomplete>pumpWidget(...)`

I have caught it many times and the recent Directionality break forced us to find all the rest.

My rough idea is to be able to configure the WidgetTester with a function that is called before pumping the widget. Something like:

```dart
/// widget_tester.dart
/// Default implementation
Widget onPumpWidget(Widget child) => child;

pumpWidget(Widget widget) {
  var pumpedWidget = onPumpWidget(widget);
  ...
}
```

Then I can override it in my test env:

```dart
WidgetTester.onPumpWidget = ...
```

(Similar to .onError handler)

Honestly, I don't like this solution. I dislike the fact that I am setting static state in tests and hiding the fact that we are wrapping the widget.  I am not sure how else to ensure a pattern like this. A need for MaterialApp might come from the requirement of setting Locale or Theme or Navigator etc. Developers typically discover this by trial-and-error (since we don't fully understand the implementations of flutter widgets). So, coming up with a pattern to help developers use the same `App` object in their tests seems like a reasonable thing to do.

**Comment by mehmetf** [comment]
> ...but what if you need to test your app in a different locale? Different Theme? Different platform? (Do you not have iOS tests?)

We don't have iOS tests using WidgetTester because our code does not do anything w.r.t. platform (or theme or locale) so we expect widgets to behave the same. We will have screen-diffing tests when they are available on iOS just as a sanity check. Having Widget tests for iOS just as a sanity check is way too expensive to maintain.

> What we tend to do in our tests is have a per-file boilerplate function that does the wrapping, and always include that in the pumpWidget call... except when we don't because we need different boilerplate. There just isn't that clear cut a pattern IMHO.

You are probably right but the experience isn't pleasant. Right now I see that something called: `pumpWithDirectionality` has cropped up in our codebase to deal with this particular issue. When do I use this vs pumpWithMaterial vs pumpWidget? Not exactly clear. I am now going to have to delete it and migrate everything using it to pumpWithMaterial.

I always like to optimize for the common case. I can see why in the platform code and tests having a default widget wrapper is not a good idea because a lot of widgets deal with theme, platform, directionality, locale so you need these custom `boilerplate`s. In a run-of-the-mill application code, dealing with these are rare. There's typically one theme, one design, one locale that it is designed for. Widget tests therefore default to this configuration 95% of the time (in Leafy's case 100% of the time).

What do you think of an extension of the `onPumpWidget` idea with the following improvements:
- onPumpWidget is called `defaultWidgetWrapper`
- You can only set it once. That ensures that it is an environment configuration rather than something you can keep overriding (which leads to people shooting themselves on the foot).
- You can pass in an optional parameter noDefaultWrap:true to skip using the default boilerplate.

**Comment by Hixie** [comment]
> In a run-of-the-mill application code, dealing with these are rare. 

I'm not sure that's true. Apps differ from each other a lot. A lot of our customers want very specifically different behaviour on iOS and Android. Some support Arabic. Many will support multiple locales. Some want to test what happens on an iPhone X with the crazy notch (i.e. have a custom MediaQuery). It's not at all clear to me that there's a common pattern that's come out yet.

We could have a defaultWidgetWrapper argument to `testWidgets`, but I'm not sure that would really be that helpful -- many testWidgets sections only have one call to pumpWidgets anyway. We couldn't really do it at a higher level (across a whole test file) because tests aren't supposed to interfere with each other.

**Comment by mehmetf** [comment]
OK; I think most of those things (such as custom notch), we will expect the framework to handle it but I am not going to spend time on this anymore :).

If the issue comes up again, we can revisit. For now, we can say every app is responsible for maintaining its test widget boilerplates.

Going back to the original issue, I think the error message, when you dissect it, is clear:

"""A RichText was created with no textDirection and no ambient Directionality widget."""

However, it isn't clear what the app developer can do about it (since we very rarely deal with Directionality directly).

Most apps OTOH will have some sort of boilerplate pattern when testing widgets and this error will most likely appear when that boilerplate is wrong or broken. May be we can extend this message by saying:

"Perhaps the widget needs to be wrapped with one that provides Directionality such as MaterialApp?"

**Comment by Hixie** [comment]
Yup, we should definitely make that message clearer.

**Comment by yduman** [comment]
I can reproduce this error with a simple HelloWorld provided from your docs.

**OS:** Windows 10
**Steps:**
1) created flutter project through Android Studio
2) deleted test folder and rewrote main.dart to HelloWorld example

**main.dart**

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Center(
      child: new Text(
          'Hello World!'
      ),
    ),
  );
}
```

**Error:**
I/flutter ( 3728): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3728): The following assertion was thrown building Text("Hello World!"):
I/flutter ( 3728): No Directionality widget found.
I/flutter ( 3728): RichText widgets require a Directionality widget ancestor.
I/flutter ( 3728): The specific widget that could not find a Directionality ancestor was:
I/flutter ( 3728):   RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Hello World!")
I/flutter ( 3728): The ownership chain for the affected widget is:
I/flutter ( 3728):   RichText ← Text ← Center ← [root]
I/flutter ( 3728): Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
I/flutter ( 3728): top of your application widget tree. It determines the ambient reading direction and is used, for
I/flutter ( 3728): example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
I/flutter ( 3728): EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
I/flutter ( 3728): 
I/flutter ( 3728): When the exception was thrown, this was the stack:
I/flutter ( 3728): #0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:223:7)
I/flutter ( 3728): #1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:239:4)
I/flutter ( 3728): #2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:4123:37)
I/flutter ( 3728): #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4158:28)
I/flutter ( 3728): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter ( 3728): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter ( 3728): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter ( 3728): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter ( 3728): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
I/flutter ( 3728): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
I/flutter ( 3728): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter ( 3728): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter ( 3728): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
I/flutter ( 3728): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter ( 3728): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter ( 3728): #15     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:840:16)
I/flutter ( 3728): #16     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:811:5)
I/flutter ( 3728): #17     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:757:17)
I/flutter ( 3728): #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2173:19)
I/flutter ( 3728): #19     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:756:13)
I/flutter ( 3728): #20     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:647:7)
I/flutter ( 3728): #21     runApp (package:flutter/src/widgets/binding.dart:689:7)
I/flutter ( 3728): #22     main (/data/user/0/com.yduman.iwanttoeat.iwanttoeat/cache/i_want_to_eatFAKRZN/i_want_to_eat/lib/main.dart:4:3)
I/flutter ( 3728): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
I/flutter ( 3728): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter ( 3728): ════════════════════════════════════════════════════════════════════════════════════════════════════


**flutter doctor:**
[√] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale de-DE, channel alpha)
    • Flutter at C:\Users\YadullahD\flutter
    • Framework revision 8f65fec5f5 (12 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\YadullahD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[√] Connected devices
    • ONEPLUS A3003 • 5805f706 • android-arm • Android 8.0.0 (API 26)

**Comment by zoechi** [comment]
> Yup, we should definitely make that message clearer.

For the message there is also #13013

**Comment by patelkrunal78** [comment]
Similar issue to No [Directionality widget found](https://icetutor.com/question/no-directionality-widget-found)

**Comment by Piinks** [comment]
I think this has been resolved, reviewing the discussion and checking several widgets, there is a nice helpful message now: 
![Screen Shot 2020-06-26 at 4 37 45 PM](https://user-images.githubusercontent.com/16964204/85908786-7bb62480-b7cb-11ea-86ea-07ca3c478433.png)
