### ISSUE TITLE
`TextField` with a lot of text (10k+ characters) is freezing the app on iPad

### ISSUE THREAD

**Issue by campovski** [flutter/flutter#121683]
## Details

`TextField` with a lot of text (10k+ lines) is freezing the app for couple of seconds. Freezing happens if you start typing after pasted long text, or if you try and scroll.

Here is the minimal reproducible example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: const Padding(
        padding: EdgeInsets.all(20),
        child: TextField(
          maxLines: null,
        ),
      ),
    );
  }
}
```
![Screenshot 2023-03-01 at 12 27 48](https://user-images.githubusercontent.com/13218644/222126783-9214d0a3-7249-43b7-9b9a-f27b3a01d5af.png)

**Target Platform:** iOS
**Target OS version/browser:** iPadOS 15.4
**Devices:** iPad Air 5th Gen, iPad Pro

Works smoothly on android and ios phones.

**Comment by huycozy** [comment]
Hi @campovski 
I'm going to close this issue in favor of https://github.com/flutter/flutter/issues/90063 because it already has the "P3" label (high priority) (please see https://github.com/flutter/flutter/issues/90063#issuecomment-1296495185).

So please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
