### ISSUE TITLE
Hot reload changes not permanently applied to on-device APK

### ISSUE THREAD

**Issue by tiwiz** [flutter/flutter#12174]
## Issue
When you run hot reload and then start the application again, the changes are reverted.

I think that the behaviour could be misleading if you come from Instant Run or JRebel for Android... I know this is the actual intended behaviour, but I'm afraid is not clear to all the potential users.

## Steps to Reproduce
Please check [this video](https://drive.google.com/file/d/0B77uAjKpun_RRTR1WW9WbW1iWnc/view?usp=sharing) on steps to reproduce

**Comment by Hixie** [comment]
What happens is that hot reload just does in-memory updates, it doesn't affect the APK. When you restart the app you are starting from the old APK. So this is as expected.

Not sure what we can do to convey this to the user? Maybe leave a file on disk so that after an apk-restart after a hot reload we can show a toast or dialog explaining this?

I don't know how common this confusion is.

cxc @InMatrix @filiph @zanderso @rmacnak-google

**Comment by Hixie** [comment]
When you launch from the device we don't necessarily have a connection to the host anymore. We don't currently store the data on the device. We could, I guess.

**Comment by jonahwilliams** [comment]
It's not feasible to update the APK/IPA on the host for security reasons, nor do we necessarily have permission to store/launch from storage on the device. I'm closing this issue because it is not actionable and is not an idea we're pursuing.
