### ISSUE TITLE
Multi-threaded Rasterization

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#121792]
Now when we traverse the Layer tree, when we reach the leaf node DisplayListLayer, we Dispatch the operation recorded in DisplayList via DisplayListDispatcher. Can we design a strategy to Dispatch DisplayList in parallel?
<img width="500" alt="截屏2023-03-02 20 13 09" src="https://user-images.githubusercontent.com/10297030/222425641-ad5ca094-72ea-4756-b1d0-6a12172c5336.png">

In this scenario we have 4 DisplayListLayers, now we are using depth-first traversal to do Dispatch so that they are executed in the order DL1, DL2, DL3, DL4. If we know that the complexity cost of DL1 is 1, DL2 is 4, DL3 is 5, and DL4 is 6, in this case, we can try to split into two threads, thread one to do DL1 and DL4 Dispatch, thread two to do DL3 and DL2 Dispatch.
Does that make sense to you? @flar

**Comment by flar** [comment]
In the case of Skia, we have to "play back" the DL into the SkCanvas and there is no way to tell them "give us a pointer here and we'll deliver the data asynchronously". We have to dump it all in right there. If they parallelize the work, that is internal to Skia.

With Impeller, currently we are creating one big DL that has `DrawDisplayListOp` records in it so the code in the picture layer objects isn't actually doing any work (just adding a record to a buffer). At the end of the `LayerTree::Paint()` we dump the aggregate DL into Impeller in one dispatch operation. Impeller could receive each recursive `DrawDisplayListOp` operation and try to parallelize their work within the [Impeller Dispatcher](https://github.com/flutter/engine/blob/a0785fde360111a3459befcd9b6593b7b2d7e689/impeller/display_list/display_list_dispatcher.cc) if it makes sense for their work flow. As to parallelizing the work on the GPU, that depends on the library being used to render and whether it supports parallel operations.

**Comment by dnfield** [comment]
It'd help to see if there's a trace where this is causing problems - IOW something specifically showing that dispatch is taking a significant amount of time. In my own look at traces around this, I don't recall seeing one where dispatch was a dominating factor on CPU time.

Most of the dispatch is just munging memory around. I suspect it's much more IO intensive than CPU. Parallelizing that could make things worse (e.g. by increasing memory contention, or by spending more time waiting on a mutex than we would have spent to just do all the work in serial).

I expect we'd have better luck looking at ways to reduce the amount of work we're doing here (e.g. avoiding copies when we can) rather than to parallelize.

**Comment by ajihyf** [comment]
Regarding Impeller parallelization, is this the issue https://github.com/flutter/flutter/issues/106519?
I am a little curious why parallelization is not done at LayerTree level, but by Impeller after generating big DL. Different subtrees of LayerTree should have been separated into unrelated task groups, and it seems easier to find tasks that can be parallelized. It seems more difficult to find unrelated slice in big DL array?
