### ISSUE TITLE
Regression in platform_views_scroll_perf_non_intersecting_impeller_ios__timeline_summary average CPU/GPU usage

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#121833]
The SkiaPerf dashboard reported a regression in the average_cpu_usage and average_gpu_usage metrics of the platform_views_scroll_perf_non_intersecting_impeller_ios__timeline_summary benchmark

See https://flutter-flutter-perf.skia.org/e/?begin=1677084908&end=1677120377&keys=X504324cfea1ed70f17cf1a91c0bcccd1&num_commits=50&request_type=1&xbaroffset=33474

Traced this to a recent change related to platform views on iOS: https://github.com/flutter/engine/pull/39527

**Comment by hellohuanlin** [comment]
To share a few update

1. i was able to verify it's indeed https://github.com/flutter/engine/pull/39527 that caused the regression using A/B testing metrics
2. I also found a clue which is quite promising - the `BringLayersIntoView` function is call every frame, even if there's no change to the view hierarchy of the platform views. It used to be fine since we are just setting the zPosition to the same value, but after my PR it performs a bringSubviewToFront for every subview (e.g. `[1, 2, 3, 4] -> [4, 1, 2, 3] -> [3, 4, 1, 2] -> [2, 3, 4, 1] -> [1, 2, 3, 4]` (back to the same!). 
3. So we want to check for this no-op scenario and avoid doing unnecessary manipulation (WIP). This should address the regression (or at least to some degree, if not the whole regression). Will post here when I get the numbers.
