### ISSUE TITLE
 flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by LevenAnny** [flutter/flutter#12182]
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = clients2.google.com, port = 443

**Comment by Mybrc91** [comment]
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 64139

**Comment by codertrack** [comment]
Downloading Gradle Wrapper...                             

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = clients2.google.com, port = 443
Crash report written to /Users/wukai/Downloads/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by eseidelGoogle** [comment]
This is https://github.com/flutter/flutter/issues/11681.  The original crash is failing to reach the gradel server, the second crash is failing to reach the crash reporting server.

**Comment by samzy500** [comment]
i ran "flutter doctor  -v"   and it solve my own error
