### ISSUE TITLE
Is there any chance to use typescript with flutter through ts2dart transpiler?

### ISSUE THREAD

**Issue by hydra1983** [flutter/flutter#12192]
Angular team built a tool [ts2dart](https://github.com/angular/ts2dart) for their own purpose. Seems it would be a solution for flutter dev with typescript.

**Comment by zoechi** [comment]
Support for ts2dart was dropped long ago and only supported a limited set of TS that was used to build Angular which caused quite some pain for the Angular team.
Since Angular for Dart is developed individually there was no use for it anymore.
It could be a community effort of course.

**Comment by Hixie** [comment]
We have no objection to the community creating a TypeScript to Dart tool to use TypeScript with Flutter, but this is not something we're going to support directly ourselves, so I'm going to close this issue.

Please don't hesitate to file more feature requests though! Thanks!

**Comment by paul-go** [comment]
For anyone reading this: my company is currently exploring the possibility of investing in the development of a TypeScript => Dart compiler specifically for use with Flutter. For anyone interested in contributing, please email paul (at) getblank (dot) com.

(Apologies for the solicitation on your thread)

**Comment by zoechi** [comment]
@paul-go https://github.com/dart-archive/ts2dart might be a good starting point.

**Comment by Bessonov** [comment]
@paul-go 
Unfortunately, I don't think that it is a good investment. From my point of view, the best investment is to implement compiler from ts to native like this was done for dart, if flutter team would accept it. I don't see any other significant advantage for dart [here](https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf), really.

Even I don't think that dart is bad on it's own, but I don't see any benefit for google to push dart further, except because it's google baby. [TypeScript just eating the world](https://trends.google.de/trends/explore?date=today%205-y&q=%2Fm%2F0n50hxv,%2Fm%2F0hjc5m0,%2Fm%2F0h52xr1).

But ping here, if you decide to write a ts -> dart compiler or enhance existing.

**Comment by paul-go** [comment]
@Bessonov We're exploring various options. I think the trick is to be able to:

a) Leverage the (significant) investments our company has already made in TypeScript
b) Take advantage of Flutter's otherwise great architecture

Flutter is very promising from a UI library standpoint, but IMO Google dropped the ball by choosing to serve their own interests (forcing an esoteric + internally developed language on the masses), rather than the interests of the market (allowing companies, or at least some companies, to leverage their existing investments). Of course Dart isn't a difficult language to learn, but I'm looking at the situation as a CTO rather than as an independent developer.

I'm not familiar with the internals of Flutter, but presumably if the Dart language is compiled to some well-documented byte code, and the UI machinery sits below this, then TypeScript could theoretically be made to compile to the same target and leverage that same machinery. This seems very high-risk, especially because non-public system internals tend to be much more of a moving target than publicly exposed APIs. I've managed these types of hack-the-compiler projects in the past, this strategy smells like something that wouldn't end well. 

Because Dart and TypeScript are fairly close, a language-to-language translator theoretically shouldn't be that difficult. The questions there are more around high-level library questions, such as "Do we re-implement ECMA's Map and Set and Array functions in Dart? Or do we write TypeScript .d.ts files that allow us to use the Dart-Native libraries here?" These are easier questions to deal with than chainsawing through some bytecode.

**Comment by luanwulin** [comment]
@paul-go have you got any progresses in TypeScript => Dart compiler?

**Comment by JosefJezek** [comment]
Why Flutter Uses Dart https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf

**Comment by derolf** [comment]
I love TypeScript, it has the most advanced type system. Dart is lightyears behind — they are still debating if they want to introduce non-nullable-types 🙄

Anyway, Flutter is awesome. So, I would love to see a serious ts2dart compiler!

**Comment by lukepighetti** [comment]
@paul-go Did you guys end up investing in this? We're running into an issue where there are tons of excellent first party packages written in TypeScript and many of them are obfuscated (see SendGrid) so rewriting them by hand is not possible. But being able to compile it over to Dart would be fantastic.

**Comment by ferso** [comment]
Why TS is horrible

**Comment by devinrhode2** [comment]
Flutter/Dart stands in a pretty interesting position. I'm not sure how many java devs are out there, but I know that javascript is currently more popular that java, and that is very unlikely to change. Any serious frontend/client side work these days is done mostly in javascript, since java applets never really took off.

IMO it would be best to take the learnings from dart, and try to get them into the ECMAScript standard.

For example, there is a proposal for optional static typing in ECMAScript, the Dart should make sure to influence these proposals so that they are compatible with how Dart uses types. In the hope that one day, we can use "Typed JavaScript" with flutter in addition to Dart.

Of course, there are a lot of "warts" in javascript. These have been getting fixed/burried/hidden, and we want to keep fixing them.

Imagine a large js app/project wants to convert using Dart+Flutter. I know Dart+Flutter are best for greenfield projects, but we need a story for how existing projects can convert, otherwise Dart+Flutter will never reach massive adoption, imagine if Dart was as popular as TypeScript is or React for that matter - the ecosystem would be incredibly rich.

A JS/TS project that wants to convert is probably going to first want some sort of ESLint rule set. Booleans might be the hardest thing. For this, we might want a Dart function, "isTruthy", which simply checks if a value is any falsey javascript value. (Of course, most projects might prefer a `isDefined` function, which explicitly checks for undefined/null, or something in the middle that also checks for empty string (plus undefined/null)

These ESLint/TSLint rules would have value on their own. Being more explicitly about truthiness should benefit any JS/TS project. I could see Airbnb adopting these rules, which then means a very sizeable amount of js code will have better boolean checks in a year or two, making Dart more of a reality.

The battle I don't think ~DART~ _**Flutter**_ will really win is when it comes to OOP. Dart VM will never get baked into browsers, so Dart doesn't have an unfair advantage against languages like ML family of languages like Reason, Elm, Purescript, Clojurescript, etc.

=====

The ts2dart transpiler should not go unmaintained, it should be an actively advertised aspect of the project, it's a shame that the last commit within the network graph (https://github.com/dart-archive/ts2dart/network) was November 29th, 2016

**Comment by devinrhode2** [comment]
If anyone wants to fiddle around with ts2dart, obviously https://github.com/dart-archive/ts2dart is not a bad version to play around with.

@jumperchen's fork `keikai` has a few extra changes that may be of interest: https://github.com/jumperchen/ts2dart/tree/keikai

**Comment by devinrhode2** [comment]
Can anyone link the last good version of angular core that used ts2dart? I'm curious what that TS looks like
