### ISSUE TITLE
`ListView` when displayed via `showGeneralDialog` shows gap at list start

### ISSUE THREAD

**Issue by flikkr** [flutter/flutter#121971]
Using `showGeneralDialog` in the sample code provided causes there to be a large gap before the first element and after the last element of the list. Using `showDialog` on displays the dialog as expected without any gaps. When running the sample app on desktop, the dialog is shown as expected without any gap.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Click on show dialog button

**Expected results:** The dialog should look identical to the one displayed in the `MyHomePage` widget

**Actual results:** The listview in the dialog has a large gap before the first element and after the last element

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample screen'),
      ),
      body: SampleDialog(),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          // uncomment to see the expected behaviour
          // showDialog(
          //   context: context,
          //   barrierDismissible: true,
          //   barrierLabel: "tests",
          //   builder: (context) {
          //     return SampleDialog();
          //   },
          // );
          showGeneralDialog(
            context: context,
            barrierDismissible: true,
            barrierLabel: "tests",
            pageBuilder: (context, animation, secondaryAnimation) {
              return SampleDialog();
            },
          );
        },
        label: const Text('Show dialog'),
      ),
    );
  }
}

class SampleDialog extends StatelessWidget {
  const SampleDialog({super.key});

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: SizedBox(
        height: 300,
        child: ListView(
          children: List.generate(
            30,
            (index) => Text(
              'test $index',
              style: Theme.of(context).textTheme.titleLarge,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

![image](https://user-images.githubusercontent.com/32480176/222970029-680aa905-bfa4-44ce-824a-e6bac17541bf.png)
![image](https://user-images.githubusercontent.com/32480176/222970351-17f75a24-26f6-4b9f-b137-e4ccca5e4502.png)
![image](https://user-images.githubusercontent.com/32480176/222970306-f435ce57-b8df-4aee-806c-7f6f677061a6.png)

**Comment by darshankawar** [comment]
Thanks for the report @flikkr 
Looking at the code implementation, since you have `ListView` inside the dialog, it adds padding by default. See the [documentation](https://api.flutter.dev/flutter/widgets/ListView-class.html):

`By default, [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) will automatically pad the list's scrollable extremities to avoid partial obstructions indicated by [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html)'s padding. To avoid this behavior, override with a zero [padding](https://api.flutter.dev/flutter/widgets/BoxScrollView/padding.html) property.`

So, in order to resolve the issue, you'll need to pass `padding` inside `ListView` as below which shows the expected result:

```
child: ListView(
          padding: const EdgeInsets.all(0),
```

<img width="294" alt="Screenshot 2023-03-06 at 4 05 46 PM" src="https://user-images.githubusercontent.com/67046386/223086876-47e24dcc-b7b3-4b3b-8a04-731a3bd8f026.png">

Closing, as this is not an issue.
