### ISSUE TITLE
Can the Flutter team make a function that converts String to IconData?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#121980]
## Use case

I have a list of strings of icons. Here's an example string from the list:

`local_dining`

However, I can't use it in the `Icon` widget because it is a `String`.

## Proposal

I hope that the Flutter team will make a `String` to `IconData` function.

**Comment by exaby73** [comment]
Hello @mycar98765. The `Icons` class is a convenience class for `const` properties of `IconData`. For example: `Icons.local_dining` is equivalent to `IconData(0xe390, fontFamily: 'MaterialIcons')`. There isn't a feasible way to encode strings here as the `IconData` relies on hex numbers and not strings. You can encode a `Map<String, IconData>` in your app like this:

```dart
const icons = {
  'local_dining': Icons.local_dining,
  // ...
};
```

And access them dynamically like this:

```dart
const String aString = 'local_dining'; // Some dynamic string
final IconData? icon = icons[aString];
```

Since this doesn't seem feasible as this causes redundancy in the code base maintaining this large map of ~8800 icons as of 3.7.6, I don't think this is a valid proposal. Therefore I am closing it. Thank you
