### ISSUE TITLE
Pigeon pub.dev score is not 100%

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#122029]
The pub.dev score for pigeon is currently 100/140: https://pub.dev/packages/pigeon/score

The docstring error and the static analysis errors should be easy to fix.  I'm not sure about the platform support analysis though.  Pub.dev has always been confused about what Pigeon is.  We might have to reach to to the pub.dev team to figure out how it get it classified better.

**Comment by stuartmorgan** [comment]
IIRC we only added a `flutter` constraint to `pigeon` because we didn't used to have CI tooling to skip analyzing it on older versions based on just the Dart constraint (which is no longer the case). If that was the only reason, then we can just remove it, which I believe will resolve the platform issue.

**Comment by stuartmorgan** [comment]
Now 140/140.
