### ISSUE TITLE
[web] Option to set relative path (base href) of sourcemaps source files

### ISSUE THREAD

**Issue by jmandawg** [flutter/flutter#122020]
## Use case

When deploying flutter web to our web server with sourcemaps for debugging on the server, the source maps file has paths that link to the local machines souce code relative to the build/web folder, the server will not have these files in these locations, and we usually deploy the source maps to the the base-href of the application.  it would be nice to have an option for this.

## Proposal
An option such as --sourcemaps-base-href to specify the base href of source maps.  Or some other. way to specify sourcemaps relative paths when building for web.

**Comment by annagrin** [comment]
This would need 

**Flutter tools**
- adding a flag (of reading the base from the index file?) in flutter tools and passing it to the frontend server
  @christopherfujino FYI

**SDK**
- adding a flag to the frontend server
- passing the flag to https://github.com/dart-lang/sdk/blob/12f0711a5bf67a732c65c5787fe4a5f327a326c6/pkg/frontend_server/lib/src/javascript_bundle.dart#L230


Created an issue for the second part on the SDK repo: https://github.com/dart-lang/sdk/issues/51691

**Comment by yjbanov** [comment]
@annagrin Is the structure of sourmap URLs specified anywhere? One issue I expect us to hit is resolving three categories of sources that a single application build is dealing with:

1. The application sources.
2. Sources of packages the app depends on through `pubspec.yaml`.
3. Dart SDK sources.

If the local server is responsible for resolving sourcemaps, how does it know where to look for each of these three categories?

My current intuition is that there should be a written specification because not all deployments of compiled code will involve any of the Dart or Flutter tooling. For example, one might want to use a nginx server, Apache httpd, Tomcat, etc, and they would need to know how to resolve Dart sourcemaps.

**Comment by annagrin** [comment]
1 and 2) The source maps paths are generated by ddc relative to the `packageConfig.resolve(moduleUri))!.path` path currently, per module. 

To allow resolving source maps, we would need to describe some other directory structure, for example, a `<source-map-base>/<package-name>`, or give it as a map to read from the frontend server.

3) Source maps for dart sdk (`dart_sdk.js.map`) is an artifact in flutter tools that is generated during the sdk build... So I am not sure what do to with those.

**Comment by jmandawg** [comment]
We ended up post processing the maps file with sed.  I will close the issue unless you guys want to continue to create a proper solution.
