### ISSUE TITLE
Rename ImageProvider subclasses to end in ImageProvider, rather than Image

### ISSUE THREAD

**Issue by harveynick** [flutter/flutter#12200]
It's a naming conflict with the Image Widget.

**Comment by Hixie** [comment]
Yeah, that's probably reasonable. Unfortunately it would be a breaking API change, and we're really trying to avoid doing those now...

**Comment by Hixie** [comment]
I'm going to close this without fixing it, because even though I agree with the original request, I really think it's too late to make that kind of change. It would break a lot of people's apps and the improvement is not that substantial (in some ways it might even be bad, since it would make the class names quite long).
