### ISSUE TITLE
TextField active paste request for Clipboard access

### ISSUE THREAD

**Issue by neilwangweili** [flutter/flutter#122360]
https://github.com/flutter/flutter/blob/6ec444506375cfa94535a45c2320e01094c295e0/packages/flutter/lib/src/widgets/editable_text.dart#L2282
When using TextField, iOS will request paste permission when the user initiates the paste. But it seems that active pasting shouldn't need to request Clipboard permissions, it's a user action. I hope it will has a field in TextField to control it.

**Comment by gaoshanyu** [comment]
I have the same problem, the Flutter iOS app always ask for Paste Permission (iOS 16.2 with Simulator).


1. Flutter iOS app always ask for Paste Permission ([the sample project source code](https://github.com/gaoshanyu/shopping-mall)):

https://user-images.githubusercontent.com/10546774/224204834-085e3ad1-8dd8-45a9-a3d2-c88ad50ba562.mov


2. Native (SwiftUI) iOS app not ask for Paste Permission([the sample project source code](https://github.com/gaoshanyu/pie)):

https://user-images.githubusercontent.com/10546774/224205488-7d24407a-686e-41d1-a36e-58ece00495fb.mov

**Comment by danagbemava-nc** [comment]
Hi @neilwangweili, @gaoshanyu, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/103163. 

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank you

PS: The reason the SwiftUI Textfield does not ask for permissions is that the Textfield does not use the clipboard for copy-paste. If you try to access the clipboard in the SwiftUI app, you'll experience the same thing as the flutter app.
