### ISSUE TITLE
flutter 3.3.10 occasional crashing on android 8 vivo mobiles 

### ISSUE THREAD

**Issue by BuildAndRelease** [flutter/flutter#122399]
Here is crash stack:
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/5510595/224332645-aa80f8d7-1660-446e-96fe-dc4c036b1d88.png">

This graph is for the major crash models and Android versions:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/5510595/224332965-6c56dbcf-6334-4196-a548-81350f4a478d.png">

Here is the flutter doctor:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/5510595/224333566-c03969c1-108a-4e08-a7ba-6e8c2ca49e98.png">

**Comment by huycozy** [comment]
Hi @BuildAndRelease 
Please provide the information in text format instead of a screenshot for better readability and investigation. You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description.

Also, is this issue reproducible locally in `release` mode? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? And please also try on the latest stable/master channel to see if the issue still persists or not.
