### ISSUE TITLE
Widget Test fails for ListView when using ListTiles

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#122482]
If the items in the ListView are Cards containing Text, my test works.
If the items in the ListView are Cards containing a ListTile with a Text title, my test fails.
This is a bug, or can it be explained ?

The flutter project is in public repo: biancashouse/listview_tester

**Comment by exaby73** [comment]
Hello @biancashouse. This is happening because the `ListTile` has a height that is causing some items to go off screen. You can confirm this by using a `SizedBox` with a height of say `100` for example. The default window sized when testing is 800x600 I believe. Check https://stackoverflow.com/questions/54651878/how-to-find-off-screen-listview-child-in-widget-tests for more information on how to test `off stage` widgets. Closing as this is working as intended.

**Comment by biancashouse** [comment]
Aha, a default screen size. That would explain it.
IMHO shouldn't it be using the CURRENT screen size rather some default, or is there a way to explicitly tell the widgettester about the current size ?
Anyway, feedback is much appreciated. Many thanks.

**Comment by biancashouse** [comment]
There are a number of workarounds, but this one I found works for me. w and h will be your desired screen size:

  setUp(() {
    WidgetsFlutterBinding.ensureInitialized();
    WidgetsBinding.instance.renderView.configuration =  new TestViewConfiguration(size: const Size(w, h));
  });
