### ISSUE TITLE
[Impeller] Investigate increased measured memory footprint.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122406]
https://flutter-flutter-perf.skia.org/e/?begin=1678400491&end=1678463408&keys=Xc43d1114ec654ef02512bd95bd746cc1&selected=commit%3D33736%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_memory_usage%252Ctest%253Dnew_gallery_ios__transition_perf%252C&xbaroffset=33736

**Comment by jonahwilliams** [comment]
From my investigation: the resolve textures still use memory! because we don't recycle these at all, we're actually just churning through memory for any application that has more than a few subpasses. i have some experiments locally that demonstrate this, but no hard numbers yet.

**Comment by jonahwilliams** [comment]
Latest results: numbers are back down to a reasonable level: https://flutter-flutter-perf.skia.org/e/?queries=test%3Dnew_gallery_impeller_ios__transition_perf&selected=commit%3D33924%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_memory_usage%252Ctest%253Dnew_gallery_impeller_ios__transition_perf%252C

At least part of this is an accounting change. We should investigate measuring memory differently so that we can capture all allocations
