### ISSUE TITLE
[Impeller] Investigate backdrop filter performance.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122408]
https://flutter-flutter-perf.skia.org/e/?begin=1678400491&end=1678463408&keys=X12c0192934b0ecc79bb42a39d31d4821&selected=commit%3D33736%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=33736

**Comment by jonahwilliams** [comment]
I think backdrop filter performance is explained by existing issues. This app creates a large number of backdrop filters so:

1. Inefficiency of subpasses due to blocking on GPU work:  https://github.com/flutter/flutter/issues/120399
2. Inefficiency of full screen texture fills due to lack of blits.
3. Potentially bad allocation patterns for offscreen MSAA: https://github.com/flutter/flutter/issues/120398

We could also be smarter about cases where there are multiple backdrop filters in the same scene, but I don' necessarily think that is going to be a very general optimization

**Comment by bdero** [comment]
A couple of other issue to add to the mix here:

* https://github.com/flutter/flutter/issues/122657
* https://github.com/flutter/flutter/issues/122658

**Comment by chinmaygarde** [comment]
This isn't a preview-exit blocker and all the more granular issues with this are understood and cross-referenced. Closing this.
