### ISSUE TITLE
flutter 3.3.10 occasional crashing on android 9 vivo mobiles

### ISSUE THREAD

**Issue by BuildAndRelease** [flutter/flutter#122400]
Here is crash stack:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/5510595/224335513-e70b69bb-0803-492f-8fd1-56faee3956fb.png">

This graph is for the major crash models and Android versions:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/5510595/224335591-27178755-ca86-4d5f-a6c3-24c0c697e189.png">

Here is the flutter doctor:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/5510595/224335608-3bc2851e-472d-469f-8413-29cd19d13982.png">

**Comment by huycozy** [comment]
Hi @BuildAndRelease 
Please provide the information in text format instead of a screenshot for better readability and investigation. You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description.

Also, is this issue reproducible locally in `release` mode? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? And please also try on the latest stable/master channel to see if the issue still persists or not.
