### ISSUE TITLE
[path_provider] Remove flutter dependency to support non flutter use cases

### ISSUE THREAD

**Issue by Jordan-Nelson** [flutter/flutter#122529]
## Use case

I would like to use the path_provider plugin, and/or some of the platform specific endorsed packages such as path_provider_windows, in non flutter applications. In particular, non-flutter desktop applications (Linux, MacOS, Windows). As dart expands in popularity, and becomes more common in server side use cases, this package could have value in non-flutter use cases if it were supported.

#### Option 1a: Remove flutter dependency from endorsed packages that don't use method channels, pigeon, or anything else that depends on flutter.

path_provider_windows uses FFI to call native APIs, not platforms channels. The only transitive dependency on flutter is path_provider_platform_interface. The dependency on Flutter could be removed to allow for this package to be used in non flutter applications. I believe this is the case for path_provider_linux as well. 

#### Option 1b: Remove flutter dependencies from all endorsed packages for desktop.

path_provider_foundation (macOS, iOS) uses platform channels via pigeon, which do not work outside of flutter applications. However, it is likely that the platform APIs could be accessed via FFI. If flutter can be removed as a dependency from path_provider_foundation (in addition to the proposal in 1a), it would allow for all desktop endorsed packages to run in non-flutter apps.

#### Option 1c: Remove flutter as a dependency in all packages

In addition to the above, it may be possible to remove the use of method channels in path_provider_android in place of JNI. I don't think this would be as useful as there are probably few use cases for non-flutter dart apps on Android.

**Comment by stuartmorgan** [comment]
> In particular, non-flutter desktop applications (Linux, MacOS, Windows). As dart expands in popularity, and becomes more common in server side use cases, this package could have value in non-flutter use cases if it were supported.

I'm not clear on what you are describing here. `path_provider` is intended to run in the context of an end-user application; much of its functionally doesn't make sense outside of that context, and a non-UI, server-side process isn't an application. (I'm also not clear on how your use case is both a desktop application and server-side at the same time.)

> The only transitive dependency on flutter is path_provider_platform_interface. The dependency on Flutter could be removed

How do you propose removing the dependency on the platform interface?

> to allow for this package to be used in non flutter applications

I'm still not clear what the use case is here where it's important to use `path_provider` instead of the `win32` calls it wraps. Could you provide a concrete example?

> I believe this is the case for path_provider_linux as well.

Which is a thin wrapper around `xdg_directories` to align with the `path_provider` API structure. What's the use case where a server-side Linux Dart service (which for some reason wants to use a desktop directory spec for storage?) wouldn't just use that directly?

> If flutter can be removed as a dependency from path_provider_foundation

And the use case that rewriting it would allow for is a service, written in Dart, running on a macOS server, needing access to application-level storage? That seems *extremely* niche. Can you provide a real-world example, or is this theoretical?

**Comment by Jordan-Nelson** [comment]
> I'm not clear on what you are describing here. path_provider is intended to run in the context of an end-user application; much of its functionally doesn't make sense outside of that context, and a non-UI, server-side process isn't an application.

"server side" was probably a bad example. A CLI app would be a better example. It seems that the Dart and Flutter CLIs make use of some of these directories for example (see screenshot below).

![Screen Shot 2023-03-14 at 10 03 20 AM](https://user-images.githubusercontent.com/20613561/225026634-4795d520-99eb-4a84-ac0c-773a49039132.png)

> How do you propose removing the dependency on the platform interface?

I believe Flutter could be removed as a dependency from `PathProviderPlatform` without too much trouble. `PathProviderPlatform` does two things. It provides the interface for each impl, and it sets `MethodChannelPathProvider` as the default instance. `MethodChannelPathProvider` depends on Flutter. I don't think `MethodChannelPathProvider` is actually used anymore. I believe it has been replaced by pigeon, and that code lives in `PathProviderAndroid` and `PathProviderFoundation`. `MethodChannelPathProvider` could likely be replaced with a stub or a late initializer assuming it is unused. If I it is still used, it could likely be moved to `PathProviderAndroid` / `PathProviderFoundation`.

> I'm still not clear what the use case is here where it's important to use path_provider instead of the win32 calls it wraps. Could you provide a concrete example?

You could of course use the lower level APIs directly. path_provider provides a convenient way to access common directories. The logic to find those directories is non trivial using win32 directly.

> Which is a thin wrapper around xdg_directories to align with the path_provider API structure. What's the use case where a server-side Linux Dart service (which for some reason wants to use a desktop directory spec for storage?) wouldn't just use that directly?

Again, server side was probably a bad example. Let's assume the use case is a CLI app that I want to run on Windows, Linux, and MacOS.

**Comment by stuartmorgan** [comment]
> Let's assume the use case is a CLI app that I want to run on Windows, Linux, and MacOS.

I would much rather we discuss an actual, concrete use case than a hypothetical use case; as demonstrated above, proposing hypothetical use cases that aren't actually relevant to the problem at hand confuses the discussion. See also https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#solve-real-problems-by-literally-solving-a-real-problem

What is the actual use case you have?

> I don't think `MethodChannelPathProvider` is actually used anymore.

It's not used by the latest version of the 1P implementations, which isn't the same thing. Removing the default implementation would be a breaking change for real code that already exists.

> The logic to find those directories is non trivial using win32 directly.

To make sure we're talking about the same thing, is the logic you are referring to this?
https://github.com/flutter/plugins/blob/557d3284ac9dda32a1106bb75be8a23bdccd2f96/packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart#L144-L173

(Finding the directory you've shown a screenshot of above is a one-line call to that method.)

Getting back to the use case, assuming this is a real case:
> Let's assume the use case is a CLI app that I want to run on Windows, Linux, and MacOS.

What `path_provider` methods, specifically, do you want to call? On macOS there's no such thing as a "CLI app", because applications and CLI tools are distinct things. The latter aren't bundles, which means one of the methods of `path_provider_macos`—the only one that isn't a direct passthrough to an OS call—would crash. In `path_provider_linux` the only non-trivial logic is the part for getting a `GApplication` app identifier, which presumably your CLI tool doesn't have.

It doesn't seem like most of the code in any of the `path_provider` implementations is actually relevant to this case.
