### ISSUE TITLE
The supplied javaHome seems to be invalid. I cannot find the java executable

### ISSUE THREAD

**Issue by 1173859245** [flutter/flutter#122594]
The prompt "Unable to find bundled Java version" is displayed when installing Flutter under Windows system After trying to copy the jre directory of jdk to the local androidstudio directory, we still haven't decided what to do

**Comment by huycozy** [comment]
Hi @1173859245 
There were two similar issues #106674 and #118502 that have been fixed on the master channel recently. 

I'll be closing this since this has been fixed on the master channel. If you still experience this issue on the master channel, kindly leave a comment below and I will reopen this. Thank you!

**Comment by under3415** [comment]
Hi, 
This issue is not really fixed.
Flutter doctor is no longer complaining, but when you try to actually run the app in an emulator or build it then it fails with below error:

```
Exception: Found syntax errors.
Launching lib\main.dart on Android SDK built for x86 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Android\Android Studio\jre\bin\java.exe
```

In Windows environment configuration `JAVA_HOME` is set to `jbr`, so not sure why is flutter still looking in `jre`.

To resolve the problem I reverted to the old workaround of making a symbolic link from `jre` to `jbr` folder (same thing that used to work for flutter doctor issue).

My flutter doctor output is:
```
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.76.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by huycozy** [comment]
I re-open for further discussion. 

Can you share the output of `java --version`? Please check this [Gradle issue](https://github.com/gradle/gradle/issues/20624) if it's applicable for your case.

**Comment by under3415** [comment]
Running `java -version` in Windows command prompt returns the following:

```
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
```

Not sure if it is relevant, but my `build.gradle` uses these versions:
```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

```

**Comment by huycozy** [comment]
@under3415 Does you have the original issue or the issue mentioned at https://github.com/flutter/flutter/issues/122594#issuecomment-1469284867? Please provide the complete output of `flutter doctor -v` and `flutter run -v` so that we may verify the issue. Thanks!
