### ISSUE TITLE
[flutter_lints] prefer_final_locals quick fix

### ISSUE THREAD

**Issue by Punt13140** [flutter/flutter#122517]
Hi, 

I don't know if it's related to IDE's extension or to flutter_lints, but since a few days, my IDE (IntelliJ) does not provide a quick fix (which is just adding the `final` keyword) for `prefer_final_locals` rule.

I've tried with Visual Code, and I'm having the same problem.

**Comment by Punt13140** [comment]
Hello @exaby73.

It's this rule : https://dart-lang.github.io/linter/lints/prefer_final_locals.html

Should I create an issue in dart-lang/lints ?

I didn't know where to create my issue, if it was flutter-related, if it's IDE's plugin related...

**Comment by exaby73** [comment]
The `flutter_lints` package is maintained by the Flutter team. This would be the correct place for a proposal. I'll take this as a proposal to add this lint, as `prefer_const_declarations` is also there, makes sense that `prefer_final_locals` might also be added.

**Comment by stuartmorgan** [comment]
> I'll take this as a proposal to add this lint

Is that actually what this is about, or is the issue that @Punt13140 has enabled that lint in their project and quick-fix just isn't working (in which case this has nothing to do with `flutter_lints`)?

**Comment by goderbauer** [comment]
> IMO this should be a recommended rule.

We discussed this during the latest review of lints and decided against putting this in any of the sets because it would add too much noice without clear benefits. It is not guarding against any errors. Developers, who like the style, can enable it for their project, though.

> I'm also going to create an issue in dart-lang/sdk for the quick fix not working.

Please do! In the meantime, I am going to close the issue here as there isn't anything actionable left to do.
