### ISSUE TITLE
error in Flutter 3.7.7  file windows/runner/win32_window.cpp 

### ISSUE THREAD

**Issue by amr-lounis** [flutter/flutter#122520]
windows/runner/win32_window.cpp ?????
after splite the function CreateAndShow() to Create() + Show()
The app no longer works on Windows most time
->
the app create process but not show window
After closing and opening app several times several times
In older versions it was more stable

im test add this code but exist peoblem
---------
// add this function above CreateAndShow 
bool CheckOneInstance()
{
    HANDLE  m_hStartEvent = CreateEventW( NULL, FALSE, FALSE, L"Global\\yourpackage" );
    if(m_hStartEvent == NULL)
    {
        CloseHandle( m_hStartEvent );
        return false;
    }
    if (GetLastError() == ERROR_ALREADY_EXISTS) {
        CloseHandle( m_hStartEvent );
        m_hStartEvent = NULL;
        // already exist
        // send message from here to existing copy of the application
        return false;
    }
    // the only instance, start in a usual way
    return true;
}

bool Win32Window::Create(const std::wstring& title,
                                const Point& origin,
                                const Size& size) {
  //Add the check
  if( !CheckOneInstance()){
    return false;
  }
  Destroy();
.......

**Comment by oSethoum** [comment]
@amr-lounis thank you for submitting this issue, I can confirm the same thing is happening for me, any work around this issue?

**Comment by huycozy** [comment]
@amr-lounis It seems you have modified the Windows platform source code. 

Could you confirm the issue only happens after this modification? If so, please point out the changes and the [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. And you should take a look at the console and check if there is any exception/stack trace if any. 

Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by oSethoum** [comment]
Hi @huycozy, I can confirm this issue to reproduce:
1- Since this issue occurred on `Windows 10` try be on the same system. 
2- Start new flutter app and make sure to use routing (I tried routing with `go_router`, `beamer` ,and `Getx` all same issue), the fastest way is to use [`get_cli`](https://pub.dev/packages/get_cli) the bootstrapped app has the issue. 
3- make sure to run it on release mode as the debug mode doesn't have this issue. 

`flutter doctor -v` command output
```terminal
$ flutter doctor -v
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19044.1288], locale en-US)
    • Flutter version 3.7.7 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (6 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Coder\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.23)     
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter       
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.1)
    • VS Code at C:\Users\Coder\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.180
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
@oSethoum I checked this with [go_router example](https://github.com/flutter/packages/tree/main/packages/go_router/example) but didn't see this issue. Can you please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? (It's recommended you use `go_router` as it's Flutter 1st package which is in the Flutter's package system). Thank you!

**Comment by jzhgithub18** [comment]
I meet the same problem, in release mode `flutter_controller_->engine()->SetNextFrameCallback([&]() {
        this->Show();
    });`
show() will not be callback, and i add code this-> Show() after the code window can be show;

**Comment by amr-lounis** [comment]
temporary solution

Run the application from the console

I think the problem is in the threads, where collisions occur sometimes

The problem does not appear when the spacing between periods of operation and when running the application from the console

**Comment by huycozy** [comment]
@amr-lounis In order to address the issue properly, please provide a sample code so that we may verify this. Thanks!

**Comment by amr-lounis** [comment]
example :
using console or power shell
..\app\build\windows\runner\Release> .\app.exe
It works after many attempts without problems
----------------------------------------------------------------
if running using Explorer after the open close  open close open close open many times
the process create without window  in Task manager

**Comment by huycozy** [comment]
@amr-lounis I tried above steps on a default Flutter project but can't see the issue. 
Have you modified `win32_window.cpp` file? Can you share the file content?
