### ISSUE TITLE
Rasterizer regression with latest Skia roll

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12250]
https://github.com/flutter/engine/pull/4131 regressed some of our rasterizer benchmarks, namely:
* complex_layout_scroll_perf__timeline_summary/frames missed_frame_rasterizer_budget_count
* complex_layout_scroll_perf__timeline_summary/average_frame_rasterizer_time_millis
* futter_gallery__transition_perf/worst_frame_rasterizer_time_millis

/cc @jason-simmons @chinmaygarde

**Comment by jason-simmons** [comment]
Some changes in this engine that may have affected rasterizer performance:
  * Using the "low" SkFilterQuality instead of the default "none" when drawing raster cache images (https://github.com/flutter/engine/commit/191a2fab399cc88ead046a4ed93491967f13c140)
  * The GrTextureOp implementation of SkGpuDevice::drawImage in Skia.
    * The first version of this caused significant regressions on some benchmarks.  It's been modified for improved performance on certain GPUs (e.g. https://github.com/google/skia/commit/4127456bd631e79f1755fe974de90dd6c42e767f) but might still impact performance on mobile.

**Comment by chinmaygarde** [comment]
I am having a tough time trying to reproduce the numbers in the benchmarks. I have tried to collect traces and measure the time spent in `GPURasterizer::Draw` both before and after the roll. Two devices were use for this, the Nexus 5 (Adreno 330) and the Moto G4 (Adreno 405). The scene was the complex layout demo where I scrolled down and then back up. On both devices, the new numbers are faster.

[New-MotoG4-ShouldBeSlower.json.zip](https://github.com/flutter/flutter/files/1335192/New-MotoG4-ShouldBeSlower.json.zip)
[New-Nexus5-ShouldBeSlower.json.zip](https://github.com/flutter/flutter/files/1335191/New-Nexus5-ShouldBeSlower.json.zip)
[Old-MotoG4-ShouldBeFaster.json.zip](https://github.com/flutter/flutter/files/1335193/Old-MotoG4-ShouldBeFaster.json.zip)
[Old-Nexus5-ShouldBeFaster.json.zip](https://github.com/flutter/flutter/files/1335194/Old-Nexus5-ShouldBeFaster.json.zip)

**Comment by Hixie** [comment]
@chinmaygarde I recommend running the devicelab test directly on your workstation.

**Comment by jason-simmons** [comment]
I can reproduce this by running the devicelab complex_layout_scroll_perf__timeline_summary benchmark with a local build of the engine on a Moto G4.

The issue seems to be that the new GrTextureOp implementation of drawImageRect is slow on some GPUs.  Most of the performance difference disappears on the G4 if I replace SkGpuDevice::drawImageRect with the version from https://github.com/google/skia/commit/a184ac7e0cdb26919369151f606c194358c94ff5 that calls drawTextureProducer.

The performance is sensitive to the specific GPU.  I didn't see a performance difference on a Pixel XL (with an Adreno 530)

**Comment by jason-simmons** [comment]
I'm also seeing a decrease in benchmark performance with the new SkGpuDevice::drawImageRect implementation on a Samsung device with a Mali-T760 GPU

@bsalomon

**Comment by Hixie** [comment]
Given that this is GPU-specific, maybe we should send that feedback to Skia and remove the TODAY milestone (meaning we don't think this is critical for us), and rebaseline the relevant metrics.

**Comment by bsalomon** [comment]
I was able to get my hands on a G4 and reproduce this. I am seeing ~6.25 ms with the old code path and ~8.25 with the new code path. The code path also takes tends to have 1 more missed frame.

**Comment by bsalomon** [comment]
If I take the new code path (GrTextureOp) but disallow batching ops with more than 2 different images then I am able to recover the performance.

**Comment by bsalomon** [comment]
Correction, the performance is only recovered if there is no batching of multiple textures. Interestingly, a Skia mircobenchmark that draws images shows a 2x improvement by batching different textures on the same device. I'm investigating why this disparity exists.

**Comment by bsalomon** [comment]
It turns out that the size of the rendered rectangles (not the image) determines whether batching multiple images into a single draw is a performance win or not. It's a win for smaller rectangles and a loss for larger. In this flutter benchmark the cached raster content that is being composited exceeds the crossover point on the Adreno 405. I'm gathering data across a wide range of GPUs using an updated Skia benchmark in order to determine how to move forward.

**Comment by chinmaygarde** [comment]
Based on our conversation, the conclusion here is that the changes in Skia cause performance improvements on some devices while minor regressions in others. The way in which batching affects performance also seems to differ between different members of the same processor family. @bsalomon is working on fine tuning the heuristics further and those changes will land in the upcoming days and weeks. The baseline has been updated for this benchmark for now and there are no more actionable items to be taken on this front in Flutter.
