### ISSUE TITLE
Flutter web: when use flutter run -d chrome --web-renderer html, the Text rendering incorrectly with having TextStyle 

### ISSUE THREAD

**Issue by fujianlian** [flutter/flutter#122665]
# Environment
~~~ bash
Flutter (Channel stable, 3.7.7, on macOS 13.0.1 22A400 darwin-arm64, locale zh-Hans-CN)
~~~

# Issue

While the child of a Container is Text,  adding TextStyle,  Text rendering incorrectly when fontSize smaller than 12, the rest is noramal.

fontSize < 12 ❌ |  fontSize >= 12  ✅
-- | --
![截屏2023-03-15 11 54 21](https://user-images.githubusercontent.com/12555302/225202271-765c3e62-4426-4dd3-a2ae-aae8ea8717e2.png) |  ![截屏2023-03-15 11 54 05](https://user-images.githubusercontent.com/12555302/225202277-eafd6b39-0a16-41b7-9354-7ef35d427e5a.png)

# Code snippet
~~~dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          width: 80,
          height: 20,
          color: Colors.red,
          child: const Text(
            'Christina',
            textAlign: TextAlign.end,
            style: TextStyle(fontSize: 12, color: Colors.blue),
          ),
        ),
      ),
    );
  }
~~~

**Comment by darshankawar** [comment]
@fujianlian 
I tried the code sample using latest stable and master versions using html renderer but unable to replicate the reported behavior.

<img width="590" alt="Screenshot 2023-03-15 at 1 48 34 PM" src="https://user-images.githubusercontent.com/67046386/225250273-8c4babfa-d43e-4007-80b5-9f7411f97d5a.png">
<img width="664" alt="Screenshot 2023-03-15 at 1 51 57 PM" src="https://user-images.githubusercontent.com/67046386/225250284-ef7b2697-7745-4eb0-a2e7-66c896b9f200.png">

One of the reasons I see why you may be seeing the issue is the language set at your end `locale zh-Hans-CN`. Can you maybe try with US English and see if you still get the same behavior or not ? I have `locale
    en-GB`


Also, could be related to https://github.com/flutter/flutter/issues/118485
