### ISSUE TITLE
Problem after upgrading to a new Flutter version

### ISSUE THREAD

**Issue by zalekbloom** [flutter/flutter#122653]
I am not sure if this this is a FLutter version problem or package problem: after issuing few days ago command: "flutter upgrade", when I try to debug my app I am getting:
C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/simple_url_preview-3.0.1/lib/simple_url_preview.dart:174:54: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.

flutter version:
Flutter 3.9.0-7.0.pre.31 • channel master • https://github.com/flutter/flutter.git
Framework • revision a599c08c32 (14 minutes ago) • 2023-03-14 17:34:34 -0700
Engine • revision e80266b78e
Tools • Dart 3.0.0 (build 3.0.0-322.0.dev) • DevTools 2.22.2

Please advice,

Thanks,

zb

**Comment by danagbemava-nc** [comment]
Hi @zalekbloom, this is not a flutter issue. `accentColor` is deprecated on current stable and so should not be used. It has been removed on the `master` channel which is the channel you're on which is why you have that issue with the `simple_url_preview` package. 

You'll need to report this on their repo so that they can prepare for the newer versions of flutter. 

Closing as this is an issue with the package.
