### ISSUE TITLE
[Impeller] Consider removing SkiaGPUObject usage for Impeller backend

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#122634]
This object can be used to schedule deletion on a particular thread, which is required for Skia backends. We run a task to clean up thse objects every N seconds.

For the Impeller backend, most/all objects don't need to be deleted on a particular thread. We should consider just deleting these objects when we're done with them. IIRC this includes display lists and images.

**Comment by jonahwilliams** [comment]
Here is an example of how this can go wrong, we drop a frame due to the unref queue (at least it appears that way)

![image](https://user-images.githubusercontent.com/8975114/231001164-b3635b37-5181-4e4f-8cd8-e6b10bb724ce.png)

**Comment by chinmaygarde** [comment]
I am not sure why the drain would be this expensive. Perhaps it is the allocators? In any case, it might be good to file a separate issue to verify if we should move all deallocations to a separate thread? I was looking at Vulkan traces and surprised at how expensive VMA access was (~2-3ms in some cases). It happened to be on another thread since there was a fence waiter.

But not having a separate queue at all on Impeller makes sense either way.

**Comment by jonahwilliams** [comment]
With Impeller on we're only deallocating display lists, about 40-50 of them at a time.

**Comment by flar** [comment]
DisplayLists should not be held in a ref queue under any circumstances since it itself contains no objects that have GPU resources. Some of the objects it contains themselves hold GPU resources, but rather than manage those destruction activities on their own, they hold the GPU resources in an unprotected state which then passes their individual burden on to the enclosing classes. For example, DlImageSkia has a resource that needs GPU destruction. But, rather than hold it in a GPU-safe wrapper, it just holds a raw reference thereby transmitting its GPU burden on to objects that want to use it.

Instead of wasting time creating an Impeller exception for objects, bury the GPU queue into the DlImageSkia object which is naturally not used on Impeller in any case. And, even when we aren't using Impeller, we stop burdening non-Skia DlImage objects and DisplayList objects with queue overhead.
