### ISSUE TITLE
For Drawer, does manually dragging and closing the drawer behaves different from fling?

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#12278]
If I drag the Drawer and close it, the Scaffold will not rebuild. But if I fling it, the scaffold will rebuild after the Drawer is dismissed. Is there a difference between manually dragging to dismiss the drawer and fling it to let it close by itself?

If I call `close()` before this return statement (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/drawer.dart#L232), manually dragging will behave the same as fling.

Thanks!

**Comment by mehmetf** [comment]
@Hixie @abarth 

The use case here is that we have a custom AppBar icon solution that shows both back button and menu button. Basically the build function of our Scaffold providing widget sets the leading icons as follows:

```dart
ModalRoute.of(context)?.canPop == true
        ? [new BackButton(), new DrawerButton()]
        : [new DrawerButton()];
```

That causes the back button to show when drawer is opened (understandably). The problem is that when the drawer is dragged to a close slowly (such that no fling is executed), the backbutton remains since Scaffold is not rebuilt.

To me, this is a framework bug because there should not be any behavioral difference between dragging drawer to close vs flinging to close. However, I would also be happy if we can treat "drawer" as a special case and never show back button (perhaps by accessing "drawerIsOpen" state?). That seems to be the behavior for normal scaffold.

**Comment by mehmetf** [comment]
It seems that Drawer is using the local history handling instead of actual navigator history. If this is a contract (and not an internal implementation detail), we can solve this by:

```dart
  ModalRoute.of(context).isFirst ? [new DrawerButton()] : [new BackButton(), new DrawerButton()];
```

What do you think?

**Comment by eseidelGoogle** [comment]
This reminds me some of https://github.com/flutter/flutter/issues/12691

**Comment by Hixie** [comment]
That's weird. Using `canPop` in this way should register you to be notified when the drawer closes. There must be a bug with the way we trigger that.

**Comment by Hixie** [comment]
I had a look at the code and I don't see any obvious reasons why this wouldn't work already. Do you have a reduced test case I can start from to debug this?

**Comment by Hixie** [comment]
Without a reduced test case there isn't much we can do here. I'm going to close the bug. Please don't hesitate to reopen if you have more information for us to act on. Thanks!
