### ISSUE TITLE
Console continuous print 'ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2'

### ISSUE THREAD

**Issue by huahua8893** [flutter/flutter#122778]
Hi all, I'm using Flutter3.7.7 and since I upgraded my Android device to Android13, run my app and console continuous print 'ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2', looks like this:
![image](https://user-images.githubusercontent.com/10332761/225512424-dd642848-418e-4ca5-8733-581da17fcf5b.png)

I do the search but have no clue, and don't know what's going on, I have to use ios simulator to test my app instead of real device,  can anybody help me out? Thank you.

**Comment by darshankawar** [comment]
> since I upgraded my Android device to Android13

@huahua8893 
Is your Android device Vivo or Oppo ? If so, this could be an issue specific to make of the devices and upgrading to 13 might be related to it.

**Comment by huahua8893** [comment]
@darshankawar yes sir, so true, my device is OnePlus PGZ110, which one of oppo's sub-brand, is there anything I can do to deal with this issue?

**Comment by darshankawar** [comment]
I think Oppo + Android 13 could be the reason why you are getting the issue and may not be specific to Flutter. It may occur on native Android as well. You can search for similar error on StackOverflow. Since this may not be actionable from Flutter, I'll go ahead and close. If you disagree, write in comments and I'll reopen it.
