### ISSUE TITLE
[in_app_purchase] Problem with IAPConnection.instance.queryProductDetails

### ISSUE THREAD

**Issue by sgondhi** [flutter/flutter#122883]
Hi, in my flutter app, IAPConnection.instance.queryProductDetails is returning In-App Purchases but not subscriptions. I have an active subscription in google play console with one active base plan. Please help.

**Comment by huycozy** [comment]
Hi @sgondhi 
Which `in_app_purchase` plugin version are you using? 

Please try running [plugin sample code](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) to see if it works without this issue. If the issue doesn't happen, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!
