### ISSUE TITLE
Google Maps uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by jonbhanson** [flutter/flutter#122804]
When I build my app for Android, I recieve the following warning:

`Note: /Users/jonhanson/.pub-cache/hosted/pub.dev/google_maps_flutter_android-2.4.3/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java uses or overrides a deprecated API.`

As a side note, I'm not sure why `pub get` is pulling version 2.4.3 of `google_maps_flutter_android` since I'm using the latest version (2.2.5) of `google_maps_flutter`.

**Comment by stuartmorgan** [comment]
Warnings were addressed in `google_maps_flutter_android` 2.4.8; closing as obsolete.

> As a side note, I'm not sure why pub get is pulling version 2.4.3 of google_maps_flutter_android

It will use whatever is in your pubspec.lock file unless you `flutter pub upgrade`.

> since I'm using the latest version (2.2.5) of google_maps_flutter.

`google_maps_flutter` 2.2.5 has a `google_maps_flutter_android` constraint of `^2.1.10`, so that's not surprising. Packages do not generally force everyone to use the absolute latest version of all of their transitive dependencies.

**Comment by jonbhanson** [comment]
Thanks, @stuartmorgan!
