### ISSUE TITLE
  End-of-central-directory signature not found.  Either this file is not

### ISSUE THREAD

**Issue by Velek** [flutter/flutter#122961]
flutter upgrade --force
Downloading Darwin x64 Dart SDK from Flutter engine 1837b5be5f0f1376a1ccf383950e83a80177fb4e...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    338      0 --:--:-- --:--:-- --:--:--   342
[/Users/ek/dev/flutter/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/ek/dev/flutter/bin/cache/dart-sdk-darwin-x64.zip or
        /Users/ek/dev/flutter/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /Users/ek/dev/flutter/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=1_activation.md

**Comment by huycozy** [comment]
Hi @Velek 
I see this issue could be caused by some reasons. For eg:

- by environment variable settings: https://github.com/flutter/flutter/issues/54175#issuecomment-610213239
- by network issue due to the downloaded file was not incomplete: https://github.com/flutter/flutter/issues/99890#issuecomment-1068623077

So, I would suggest you check these answers and try applying them if they work for you. Also, there's a similar open issue describing your case https://github.com/flutter/flutter/issues/66243.
