### ISSUE TITLE
[shared_preferences] Consider making async accessors, with optional caching layer

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#123078]
Based on discussion while adding prefix support to `shared_preferences`, and previous discussion in https://github.com/flutter/flutter/issues/101691, we should consider deprecating the current API and building a new API with the cache outside the public API instead of inside its implementation.

This version could consist of two different public API layers:
1. Setters and getters that are all async, and are direct passthroughs to the underlying storage. Prefixing would be fully optional.
    - We could either make it not part of this layer at all, leaving it entirely to clients of this API layer, or we could allow creating arbitrary instances with optional prefixes. (Since there is no singleton+cache at this layer, we would not have to worry about cache consistency issues.)
2. A separate cache object, with an API more like the current API, built on the underlying async API. We could:
    - have no "shared instance" logic at all (leaving it entirely to clients to manage their cache instances), or
    - build in something more flexible than the current singleton. E.g., maybe allow something like a global ID-keyed map, where you would ask for an instance with certain properties (such as key prefix) and you'd get a key back that you could use to access that same shared instance in the future. In this version we'd need to make it very clear that the caches would be distinct, and strongly discourage overlapping caches (e.g., a no-prefix cache and a prefixed cache) to avoid synchronization issues.

We'd want to fully evaluate all the flexibility we'd need to meet open requests (different storage files/domains, etc.) before designing the new API so we could incorporate all of it up front in at least layer 1.

(@tarrinneal just capturing based on recent thoughts and discussions while it's fresh in our minds; not something we need to do in the short term.)

**Comment by gslender** [comment]
Would it be possible to also offer a fully blocking mode where calls are synchornous and wait for the underlying I/O to return results before returning?? - as its not always convenient to have aync methods that don't return results until a future completes.

**Comment by stuartmorgan** [comment]
> Would it be possible to also offer a fully blocking mode where calls are synchornous and wait for the underlying I/O to return results before returning?

No; platform channels are inherently asynchronous.

> its not always convenient to have aync methods that don't return results until a future completes.

That's why the cache exists.

**Comment by gslender** [comment]
Yes, but isn't this post / issue suggesting that the cache is inherrently unreliable because it might be updated and not fresh? I guess I'm struggling to see the value in a sharedpreference solution that can't be reliably used accross isolates that might be accessing the same underlying persistent store. Making the enitre package async in almost everyway negates the value of having a shared store that can be relied on if you're constantly having to consider async updates that are not in sync with the cache.

**Comment by gslender** [comment]
@stuartmorgan I'm seeing cases now (more and more regularly) on iOS where the cache is missing entries, and as per #95013 I'm wondering if there is some condition that is causing this to occur more and more now since some change in this package or flutter core - any clues as to where to look. I'm still trying to build a repeatable case, but so far, its popping up regularly in the last 2 months
