### ISSUE TITLE
Chrome Extensions: Content-Security-Policy Flutter applies deprecated directives.

### ISSUE THREAD

**Issue by coppermight** [flutter/flutter#123097]
From here: https://github.com/Dart-Code/Dart-Code/blob/bca09132c5f8afd58c740f652edf8c0ef3b8fc79/src/extension/sdk/dev_tools/embedded_view.ts

`this.panel.webview.html = `
			<html>
			<head>
			<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'nonce-${scriptNonce}' 'nonce-${cssNonce}' http://${vs.Uri.parse(devToolsUri).authority};">
			<script nonce="${scriptNonce}">${pageScript}</script>
			<style nonce="${cssNonce}">#devToolsFrame { ${frameCss} }</style>
			</head>
			<body><iframe id="devToolsFrame" src="about:blank" frameborder="0"></iframe></body>
			</html>
			`;`

the line:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'nonce-${scriptNonce}' 'nonce-${cssNonce}' http://${vs.Uri.parse(devToolsUri).authority};">`

For Chrome Extensions this is not allowed and flutter is creating non CSP compliant pages. More details on [manifest V3 ](https://developer.chrome.com/docs/extensions/mv3/intro/)

This means that flutter currently cant be used to make chrome extensions.

Please fix

**Comment by huycozy** [comment]
Hi @coppermight 
I'm not sure I can understand this right. If it's an issue with Dart Code, I would recommend filing an issue in its repository for better support. 

If you are looking for a solution to make a Chrome extension, you may check [this tutorial](https://blog.codemagic.io/how-to-build-a-chrome-extension-with-flutter-web/) for reference. You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://flutter.dev/community or https://www.reddit.com/r/flutterhelp for resources.


Closing for now. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. Thank you!
