### ISSUE TITLE
Building app for different devices (same platform) using special build commands or pubspec.yaml or variables in pubspec.yaml

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#123022]
## Story
I am developing a mobile application with flutter which uses platform specific code integration (android/iOS)
let's take example of android
I am using .jar from third party provider (which follows interface A) and adding it to the project using gradle
and writing method channels / event channels for integration with flutter app
Now, I add this plugin as a dependency in main application (pubspec.yaml) and I am able to build/run on android (and integration is also done correctly)

However, there is another .jar file from third party provider (which also follows interface A) which is also made to obtain same results, but in some different (special) android device (the android device is integrated with IoT device) and both .jar is conflicting (because the class names are same) and cannot be merged into same project

so there can be multiple reasons of .jar file conflicting 
for eg. native binaries has same class name (which we cannot control as its not developed by us)

So I am looking for some solution where even if I need to maintain 2 plugin project, I should be able to add both in pubspec.yaml and select which one to use during build/debugging time
so If I am running on normal android device I can build with first .jar file
if I am running on special android device then I can build with another .jar file 

## Proposal
May be extending features of pubspec.yaml & build commands might help

**Comment by darshankawar** [comment]
@Pr47h4m 


> May be extending features of pubspec.yaml & build commands might help

Do you have a concrete proposal on how to handle the use case described ? For example, what exactly would be the changes required in pubspec or build commands that would help resolve the case ?



> So I am looking for some solution where even if I need to maintain 2 plugin project, I should be able to add both in pubspec.yaml and select which one to use during build/debugging time

If you are looking for an existing solution, maybe StackOverflow is a good place for it wherein you can get solutions on how to overcome the case you described, because looking at the use case, it seems very specific to your requirement so proposing a change for it in framework may be not feasible. 
There might be community packages already that might be offering the solution already so you can try to look for such and another bet would be to look / ask on SO.
