### ISSUE TITLE
Issue on Text Display with RTL, Its adding padding on top.

### ISSUE THREAD

**Issue by Usama1Ace** [flutter/flutter#123198]
## Steps to Reproduce

This issue raises with Arabic and Urdu Language. 
Its adding Padding almost every Text Widget and even in TextField.

I am using Flutter Version 3.3.11

![IMG_0631](https://user-images.githubusercontent.com/107171472/226838124-fdb26d4b-a2fe-4efd-9a14-7019eac43565.jpg)
![IMG_0630](https://user-images.githubusercontent.com/107171472/226838132-dde3371f-0abc-4109-9f9a-bb9e040539b0.jpg)
![IMG_0629](https://user-images.githubusercontent.com/107171472/226838139-f53cbc0e-6c55-4425-9377-18ef32d184b5.jpg)
![IMG_0623](https://user-images.githubusercontent.com/107171472/226838142-69624166-14c3-4230-bfbb-21b0de5d646f.PNG)

![IMG_0632](https://user-images.githubusercontent.com/107171472/226838100-1ffd9430-1d01-4610-95a0-11e51f648a01.jpg)

<img width="826" alt="Screenshot 2023-03-22 at 1 08 03 PM" src="https://user-images.githubusercontent.com/107171472/226838779-eae25495-7cac-4114-ba04-22bd3bc84887.png">

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

Sample Code for Textfield :
<img width="900" alt="Screenshot 2023-03-22 at 1 10 29 PM" src="https://user-images.githubusercontent.com/107171472/226839326-c737df81-fe79-436b-86ca-0f69ef58639f.png">

**Comment by huycozy** [comment]
Hi @Usama1Ace 
I don't see this issue on the latest master channel with a simple TextField. 

<details>
<summary>Demo</summary>

![IMG_4506](https://user-images.githubusercontent.com/104349824/226871533-76bc2d75-9549-46e8-af5d-56ad87687f1b.png)

</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this (It should be in code block format instead of a screenshot, see [Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)).

And please also retry on the latest stable/master channel to check if the issue still persists or not.

**Comment by Usama1Ace** [comment]
## Steps to Reproduce


Textfield Label is disturbed. added Padding on top . And When start writing in text field words are going outside the textfield.

Description: 
 - Issues of RTL langauge in App only appears when you have any RTL language exists in your phone.
  Like in my case i have added Urdu language from phone language settings.
  Then open the app It disturbed the UI . Same like seen in images...
  
  This issue raised on multiple device and same.
  Devices Name:
 -  Iphone 7+
 -  Iphone XR
 -  Infinix  Android 12
 -  Emulator Android 12 and Android 13.


**Expected results:** 

Result Fine. When no  RTL languages exist in Phone Language Settings. So This result appears.
Here bottom Bar it looks like this .... Words are Perfectly Aligned.

![IMG_0633](https://user-images.githubusercontent.com/46489315/226891477-1b33dd29-fa45-4f37-b15b-60853740591f.jpg)



**Actual results:** 

Result When i have selected RTL language like Urdu in phone Language setting exist.
Even in bottom Bar it looks like this .... Words are outside the bottom bar..


![IMG_0635](https://user-images.githubusercontent.com/46489315/226891827-30ac3c8f-e194-466b-96f7-861688151bd0.jpg)





<details>
<summary>Code sample</summary>
TextFormField(
              // key: UniqueKey(),

              focusNode: searchController.myFocusNode,
              // readOnly: this.isLoadingSearchResults,
              // enabled: !this.isLoadingSearchResults,
              onEditingComplete: () {
                debugPrint(
                    'On Editing Completed ..... ${searchController.textEditingController.text}');
              },
              onSaved: (newvalue) {
                debugPrint(
                    'On Saved Completed ..... ${searchController.textEditingController.text}');
              },

              onChanged: (newText) async {
                searchController.debouncer.run(() async {
                  debugPrint('Item Clicked ....');
                  searchController.setrootWord = "";

                  if (searchController.hasSpeech) {
                    return;
                  }
                  // setState(() {
                  if (newText == '') {
                    searchController.alignText = TextAlign.left;
                  }
                  // slideAnimationController.reverse();
                  bool isOtherLang =
                      searchController.checkTranslation(newText.trim());
                  if (isOtherLang) {
                    searchController.alignText = TextAlign.right;
                  } else {
                    searchController.alignText = TextAlign.left;
                  }
                  // });

                  debugPrint('Search Term   ${newText.trim()}');

                  searchController.searchAfterTimeout(newText.trim());

                  print(newText);
                  //perform search here
                });
              },
              controller: searchController.textEditingController,
              textAlign: searchController.alignText,
              // autofocus: false,
              style: TextStyle(
                fontSize: 18,
              ),
              textInputAction: TextInputAction.unspecified,

              cursorColor: Constants.colors.secondaryColor,
              decoration: InputDecoration(
                  isDense: true,
                  contentPadding: EdgeInsets.zero,
                  border: InputBorder.none,
                  hintText: getTranslated(context, 'search_with_dots'),
                  hintStyle:
                      TextStyle(fontSize: 18, fontWeight: FontWeight.w300)),
            ),





Replace the Keys for gettranslated with belows.


XML Language for Urdu,Arabic keys :  

<string name="search_with_dots">تلاش کریں…</string>

<string name="search_with_dots">بحث…</string>

**Comment by huycozy** [comment]
I switched device language to Arabic or Urdu but still can not reproduce this issue:

| Arabic | Urdu |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/227101455-14d7821a-78bf-4e25-8354-b639d1afd4a7.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/227101469-66db5fe9-c3af-457b-9aaf-241a99702db5.png">

Your sample code is incomplete due to undefined variables/components. Please try to create a minimal and complete sample code in a `main.dart` file, so that we can just copy and run it to verify the issue.

And please also retry on the latest **stable/master** channel to check if the issue still persists or not.
