### ISSUE TITLE
ImageShader objects can't be eagerly disposed in canvaskit backend

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123271]
```diff
diff --git a/packages/flutter/lib/src/painting/decoration_image.dart b/packages/flutter/lib/src/painting/decoration_image.dart
index 2b119963a8..a310e354a6 100644
--- a/packages/flutter/lib/src/painting/decoration_image.dart
+++ b/packages/flutter/lib/src/painting/decoration_image.dart
@@ -705,6 +705,7 @@ void paintImage({
         rect,
         paint..shader = shader
       );
+      shader.dispose();
     }
   } else {
     canvas.scale(1 / scale);
     ```
     
     
  ```dart
  void main() {
    runApp(Image.network(..., repeat: ImageRepeat.repeat);
  }
```

This code works as expected in mobile/desktop and crashes on the web. @yjbanov

**Comment by yjbanov** [comment]
Looks like that framework-side code was reverted. However, I recently changed how shader memory is managed in https://github.com/flutter/engine/pull/41172. We have [a couple of tests](https://github.com/flutter/engine/blob/e914b03070fc9135a1103fc5252fb6adbc209ae7/lib/web_ui/test/canvaskit/shader_test.dart#L63) that test explicit disposal of image shaders. So hopefully this problem is gone now.

**Comment by jonahwilliams** [comment]
Woo hoo!
