### ISSUE TITLE
Google testing fails to report status to GitHub

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#123289]
I've seen several PRs in the past few weeks where the "Google testing" check starts, then stays in "Pending" status indefinitely, for a day or more.

A recent example is #122225. After updating the PR Monday morning, the check stayed pending all day. After a bit over 24 hours I updated the PR again to restart the check; it's still pending now, another 24 hours after that.

In the case of that PR, I asked in #hackers-infra and learned that the second check (at least) did run, and reported some results internally; the status just never made it back to GitHub. (I'm not sure whether the tests ran all the way to completion.)

The workaround I know of is to update the PR so that the check starts again. As in the case of #122225, this doesn't always work; the retry might get stuck too. In any case, because "Google testing" results [can take up to 2 hours](https://github.com/flutter/flutter/wiki/Understanding-google-testing) even when all's well, this adds at least 2 hours of turnaround time for each retry.

Possible related issues:
* frob can be missing the status too: #119767
  * and #103553
* While the status is pending, the autosubmit bot doesn't wait for it: #122543
* The check is "flaky" but I'm not sure what that means (presumably the Google-internal bug says more): #116357

**Comment by XilaiZhang** [comment]
https://github.com/flutter/flutter/pull/122225 was triaged yesterday, and my understanding is that it comes from the approver's relationship with the flutter/flutter github repository.

Currently, we parses the "author_association" field returned from github api, to determine the approver's relationship with flutter/flutter. The approval is considered valid as long as one of the approvers has the association "MEMBER"

in the case of 122225, the Github sends back information through https://api.github.com/repos/flutter/flutter/pulls/122225/reviews ,  and the two approvers' "author_association" with flutter/flutter are "CONTRIBUTOR", it was pending because it was missing an approver with "MEMBER" association.

An example of approver with "MEMBER" association would look something like https://api.github.com/repos/flutter/flutter/pulls/123262/reviews.

**Comment by gnprice** [comment]
Thanks for the investigation.

On #122225 the check did eventually complete, after I gave the PR another update yesterday. The two approvals are still with "author_association" of "CONTRIBUTOR". So it seems like that on its own doesn't explain which PRs do and don't get affected.

IIRC the same PR also had the check complete a couple of weeks ago. I believe when this comment was written: https://github.com/flutter/flutter/pull/122225#issuecomment-1476660501 , the status was "failed" (like it is now), not "pending".

**Comment by gnprice** [comment]
If the difference between an association of CONTRIBUTOR and an association of MEMBER is having an effect on the behavior of Google testing, then that seems like a bug to be fixed. Both of the approvers on #122225, with association CONTRIBUTOR, are in the flutter-hackers group (and one is a Googler).

Another PR that appears to be affected by the issue just today is #122480: the PR branch was last updated about 4.5 hours ago, so Google testing should have completed by now, but the status shows that it's started and is still pending. In https://api.github.com/repos/flutter/flutter/pulls/122480/reviews there are entries from three different people, all of them in flutter-hackers, and all with association CONTRIBUTOR.

**Comment by gnprice** [comment]
Conversely, #123129 has an approval with association MEMBER (per https://api.github.com/repos/flutter/flutter/pulls/123129/reviews), but nevertheless appears to be another example of the issue: that approval came a bit over 6 hours ago, but the status is still pending.
![image](https://user-images.githubusercontent.com/28173/227690259-c4e686d1-b054-4ad2-b3b1-b0e523fa2e12.png)

**Comment by XilaiZhang** [comment]
I created an internal cl (cl/519428514) to include Approvals from "CONTRIBUTOR" association. It is likely going to be reviewed on Monday. 

After the new cl lands both "MEMBER" and "CONTRIBUTOR" should have the ability to trigger google testing, which should cover the case of 122225 and 122480 . https://github.com/flutter/flutter/pull/123129 has a status right now. The case of 123129 was a bit complicated: it involved some manual testings and hitting wrong buttons before the approval was given. (only know this because Micheal sits next to me :)

**Comment by gnprice** [comment]
Fascinating, thanks for your help. Hopefully that resolves the issue.

That's still a bit puzzling as a diagnosis, because both #122225 and #122480 have eventually gotten a status from Google testing, even though all the approvers have association CONTRIBUTOR. In particular in the case of #122225, it had a status by yesterday morning (at https://github.com/flutter/flutter/pull/122225#issuecomment-1483257247); and it seems like the only thing that had changed since it was lacking a status the evening before (at https://github.com/flutter/flutter/pull/122225#issuecomment-1482298197) would have been that I updated the PR and caused checks to restart. But possibly someone intervened behind the scenes on both of those PRs.

**Comment by XilaiZhang** [comment]
I agree, it's unclear what is being sent to update github status. I created another internal cl (cl/519461225) to log the content of the message we send to github (looking at the log history of 12225, we only know we send updates to github, but we didn't log the contents of the message). This change list is likely to be reviewed on Monday as well.

After this one lands we would probably have a clearer idea on what is sent from us, and can then proceed to compare with what is received by github.

**Comment by gnprice** [comment]
Looks like #123294 is another case of this: PR was updated just under 9 hours ago, and the status is still pending.

Has your CL for more logging gotten landed and deployed, so as to find out more about what might be the cause?

**Comment by XilaiZhang** [comment]
Right haven't got cycles to work on it. I worked on it for the past hour and here is the update:

I updated the internal cl (cl/519428514) to use the [https://api.github.com/orgs/flutter/members](https://www.google.com/url?sa=D&q=https%3A%2F%2Fapi.github.com%2Forgs%2Fflutter%2Fmembers) api to retrieve flutter members list, and compare the list with the reviewers list to find if there is at least a member. We removed the usage of the author association field from the reviews api, because it is unclear why we are seeing "CONTRIBUTOR" values marked for googlers. I think using the members api will help us get rid of such ambiguity. This new revision is likely going to be reviewed tomorrow.
