### ISSUE TITLE
Change MockPlatformInterfaceMixin to be a mixin

### ISSUE THREAD

**Issue by gabrielgarciagava** [flutter/flutter#123241]
## Use case

When writing Plugin tests, MockPlatformInterfaceMixin is provided to be able to mock PlatformInterface.
However, MockPlatformInterfaceMixin is defined as a class, which conflicts with linter rule `prefer_mixin` (https://dart-lang.github.io/linter/lints/prefer_mixin.html)

## Proposal

Change MockPlatformInterfaceMixin from class to mixin

```
mixin MockPlatformInterfaceMixin implements PlatformInterface {}
```

**Comment by oprypin** [comment]
I also think it should be changed to `mixin`, otherwise it will stop working with Dart language version 3.0. For that reason I think this should be prioritized.

Alternatively maybe it can be changed to `mixin class`, because it is possible that someone was using this not in a `with` clause. In google3 all the usages I found *were* compliant with `mixin`, though.

https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/lib/plugin_platform_interface.dart#L129

https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/test/plugin_platform_interface_test.dart#L97

cc @xster

**Comment by gabrielgarciagava** [comment]
I was indeed afraid of the backward compatibility problem. The plugin template creates the test file using the `with` word properly, but it is not weird to imagine people using it differently.

What do you mean by `mixin class`?

**Comment by oprypin** [comment]
`mixin class` will be new syntax in Dart 3.0 that will mean what `class` currently means but without triggering the `prefer_mixin` lint.
https://github.com/dart-lang/language/blob/2a3a253ca81d3cf0b78ad88e34aaaf6e185b5345/accepted/future-releases/class-modifiers/feature-specification.md#mixin-classes
But you need to add `// @dart=3.0` into the file, and it's not released yet, so not an immediately viable option.

**Comment by stuartmorgan** [comment]
> I also think it should be changed to `mixin`, otherwise it will stop working with Dart language version 3.0

Could you elaborate on this? Why wouldn't our tests already be broken on `master` if this were the case?

**Comment by oprypin** [comment]
> Why wouldn't our tests already be broken on `master`

I don't know how your tests are set up or whether they use Dart 3.0 at all.

Elaboration:

Something that isn't a mixin:
https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/lib/plugin_platform_interface.dart#L129

Is being used in a `with` clause:
https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/test/plugin_platform_interface_test.dart#L31

-that's an error in Dart language version 3.0

**Comment by stuartmorgan** [comment]
> I don't know how your tests are set up or whether they use Dart 3.0 at all.

We run all of them, pretty much constantly, on both Flutter `stable` and Flutter `master`.



> Something that isn't a mixin: https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/lib/plugin_platform_interface.dart#L129
> 
> Is being used in a `with` clause: https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/test/plugin_platform_interface_test.dart#L31

So for instance, this test:
https://cirrus-ci.com/task/5427622834864128?logs=unit_test#L620-L631

> -that's an error in Dart language version 3.0

On this version of Dart?
https://cirrus-ci.com/task/5427622834864128?logs=upgrade_flutter#L749

(It doesn't jump to the highlighted lines for some reason, but you can scroll until you see the highlight.)

**Comment by iinozemtsev** [comment]
I think language version is determined by a minimal sdk version constraint, so probably plugin_platform_interface uses language version 2.17: https://github.com/flutter/packages/blob/789f6795730f3fbdb9344a877d19ed0aa631f4d8/packages/plugin_platform_interface/pubspec.yaml#L21, that's why there's no error yet
