### ISSUE TITLE
Flutter DropdownButtonFormField relocates on zooming on web

### ISSUE THREAD

**Issue by gauria24** [flutter/flutter#123399]
Flutter DropdownButtonFormField relocates on zooming on web. Attached the screen shot of flutter gallery app.

Steps to reproduce:

1. Launch https://gallery.flutter.dev/#/ in a browser
2. Go to Categories section. Under Material type choose Menu
3. Select ContextMenu from options. Click on kebab menu icon
4. Keep the list open
5.Zoom screen up to 100% to 500%
6. Observe the relocation of the list.

flutter doctor command output is as below.
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
![Screenshot 2023-03-24 at 6 33 59 PM](https://user-images.githubusercontent.com/97582254/227528906-f5555236-2203-400d-8d87-5d4d3f2c6fba.png)
![Screenshot 2023-03-24 at 6 34 55 PM](https://user-images.githubusercontent.com/97582254/227528911-2ebceb1e-dfd7-4d31-92e7-6454b9d64849.png)

**Comment by exaby73** [comment]
Hello @gauria24. In the Gallery app, when zooming in, the UI switches to a mobile friendly view, changing the position of everything on the page. When a menu is shown, it uses an `Overlay`. This `Overlay` is attached to a specific position on the screen, and not attached to the position of the button. So when the button moves, the menu stays in a relative position on the screen rather than following the button around. This is expected behavior. Therefore, I am closing this issue. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you
