### ISSUE TITLE
flutter upgrade crash

### ISSUE THREAD

**Issue by Asmerom-yohannes** [flutter/flutter#123389]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i try to upgrade flutter and run " flutter pub upgrade"

### Actual results

Unable to 'pub upgrade' flutter tool. Retrying in five seconds...  i recieve this message multiple time and non stopped

### Logs

<details>
<summary>Logs</summary>

```console

flutter pub upgrade
flutter upgrade
```

</details>

### Flutter Doctor output

<details>
<summary>Logs</summary>

```console

The system cannot find the path specified.
Error (3): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left) 
Running pub upgrade... 

```

</details>

**Comment by huycozy** [comment]
This issue seems related to your network, please ensure you have a working internet connection.
There is a checklist you can use for this:

- [ ]  Is the network stable and fast?
- [ ]  Do you use any proxy server?
- [ ]  Are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?
- [ ]  It may be useful for troubleshooting the issue: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

You can also check some answers that may be helpful:

- https://github.com/flutter/flutter/issues/59669#issuecomment-645362291
- https://stackoverflow.com/questions/49497109/error-unable-to-pub-upgrade-flutter-tool-retrying-in-five-seconds

**Comment by Asmerom-yohannes** [comment]
yap my connection stable and fast am not using a proxy or VPN

**Comment by huycozy** [comment]
Can you confirm that you have checked all resources above? (also solutions from SO answers as well)

**Comment by Asmerom-yohannes** [comment]
yea I resolve the issue with uninstall and install the flutter. thank you

**Comment by Asmerom-yohannes** [comment]
@huycozy thank you for participate and answer my question

**Comment by huycozy** [comment]
You're welcome. This may cause by something corrupted at the first time when sdk downloading. Closing the issue as solved. Thanks!
