### ISSUE TITLE
[Impeller] Investigate pipeline depth issue performance problems

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123480]
From local experiments, this seems to reduce the issue were we get massively behind and stay that way. Needs more investigation though.

**Comment by chinmaygarde** [comment]
That this isn't working great is understandable but I don't think reducing the pipeline depth to 1 is the solution. We should model what happens when both the framework and UI thread workloads are more than half a frame interval. There is also the suggestion that we start the UI thread workload immediately.

**Comment by jonahwilliams** [comment]
From experimentation, as we increase the time the UI thread takes for a given workload we fail to take advantage of the UI/Raster thread running concurrently - so everything slows way down.

Perhaps instead we should try applying the raster thread backpressure (waitForNextDrawable) to the UI thread workload? That won't slow down cases were the Ui thread is slow. But may stop us from feeding the engine too much

**Comment by jonahwilliams** [comment]
The solution was to set presentsWIthTransaction to true, always

**Comment by raulmabe-labhouse** [comment]
Hi @jonahwilliams, excuse me if this isn't the most suitable place to post this, but I don't know where I can find more information about this issue.

![Screenshot 2023-05-26 at 13 01 11](https://github.com/flutter/flutter/assets/114908263/e13f9de6-5f98-4550-a256-4fd1ae51286b)


We are experiencing excessive memory usage and overheating on phones when using our app, and I'm trying to trace its source. I have attempted to switch rendering engines (skia/impeller), but encountered the same issue in the Timeline Events. I'm unsure how to identify the core problem or where to find more information about it.

Even when the app is in standby mode and shouldn't consume excessive memory, this graph indicates that the raster thread is taking too much time for each frame, with half of it being wasted on waiting. This is something I don't understand.

**Comment by ahmdaeyz** [comment]
@raulmabe-labhouse Hello, were you able to find anything? We are having a similar issue and are investigating causes.

**Comment by raulmabe-labhouse** [comment]
@ahmdaeyz We are not sure if what we found is really the cause of these spikes, but it definitely helped us reduce them significantly.

Firstly, this screenshot was taken on an app running Flutter 3.10. When we updated to Flutter 3.11.0-0.1.pre, these times became faster.

Secondly, we identified that our app was consuming up to 2GB of memory, since iOS terminates apps that consume more than 2GB. We discovered that displaying GIFs and network images on certain pages caused a memory leak on iOS (#57549), even though they were disposed of...
