### ISSUE TITLE
[Impeller] Investigate using Metal Performance Shaders for specific use-cases.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#123472]
This is purely exploratory and a followup to https://github.com/flutter/flutter/issues/122657. Some things to explore:
* Is it possible?
* If this is backend specific, is the performance going to be worth it or should we use a portable solution?
* Does it cover all our use-cases? i.e. sampling options/radius configuration.
  * If a subset of the use-cases are easier to support performantly, can we update the API to reflect this?
* Does it treat color spaces similar to existing Impeller shaders?

**Comment by jonahwilliams** [comment]
I hacked together a quick patch which uses a MPSImageGaussianBlur kernel for applying gaussians. At least on first glance, this appears to be slower than what we're doing today. At least part of the overhead must be due to the fact that this appears to convert to a 16bit float format internally before applying the kernel. I'm not exactly sure why its doing that...

![image](https://user-images.githubusercontent.com/8975114/235782530-6c56703b-2bd3-495c-8af1-ef4ca4b266fa.png)



https://github.com/jonahwilliams/engine/pull/new/perf_kernel
