### ISSUE TITLE
macos_ui customer test failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123669]
This is blocking all framework PRs, essentially closing the tree.

An example is on https://github.com/flutter/flutter/pull/123651 with https://cirrus-ci.com/task/5410168087773184

```
| 00:58 +35: /tmp/flutter_customer_testing.macos_ui.GCFGWO/tests/test/selectors/date_picker_test.dart: MacosDatePicker tests Can change the month by clicking the left and right calendar view controls
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: <2>
|   Actual: <3>
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure>.<anonymous closure> (file:///tmp/flutter_customer_testing.macos_ui.GCFGWO/tests/test/selectors/date_picker_test.dart:292:11)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
|
| This was caught by the test expectation on the following line:
|   file:///tmp/flutter_customer_testing.macos_ui.GCFGWO/tests/test/selectors/date_picker_test.dart line 292
| The test description was:
|   Can change the month by clicking the left and right calendar view controls
| ════════════════════════════════════════════════════════════════════════════════════════════════════
|
| 00:58 +35 -1: /tmp/flutter_customer_testing.macos_ui.GCFGWO/tests/test/selectors/date_picker_test.dart: MacosDatePicker tests Can change the month by clicking the left and right calendar view controls [E]
|   Test failed. See exception logs above.
|   The test description was: Can change the month by clicking the left and right calendar view controls
|
|
| To run this test again: /tmp/flutter sdk/bin/cache/dart-sdk/bin/dart test /tmp/flutter_customer_testing.macos_ui.GCFGWO/tests/test/selectors/date_picker_test.dart -p vm --plain-name 'MacosDatePicker tests Can change the month by clicking the left and right calendar view controls'
```

**Comment by zanderso** [comment]
Failing check is here: https://github.com/macosui/macos_ui/blob/dev/test/selectors/date_picker_test.dart#L292

**Comment by zanderso** [comment]
A bit of a shot in the dark, but looking through engine and framework commits, I see recent commits from @Piinks and @loic-sharma that could maybe be related?

**Comment by zanderso** [comment]
This is now failing on Flutter CI. Given the delay, and the fact that the test is using DateTime.now(), I wonder if the delay is due to a time zone difference, and there is a bug in the test on the last day of the month.

**Comment by zanderso** [comment]
@GroovinChip

**Comment by eliasyishak** [comment]
After some investigation, I believe the issue is being caused by passing "incorrect" dates to Dart's `DateTime(...)` constructor on the customer widget side.

When you press the back button in `MacosDatePicker`, it will assume that the previous date is just the current date minus one on the month value. For most days out of the year this should be fine, but if you use today, `March 29, 2023`; it will try to subtract 1 from the month value and create a new `DateTime` object in Dart.

On the dart side it receives the following `DateTime(2023, 2, 29)` which is an invalid date and it tries to fix this for you by going 1 day over into March. However, your test won't like this because it is expecting a date month value of `2` but the constructor is returning `3` because of the invalid 29th day on Feb on a non-leap year day.

There are two solutions I can think of:
1. Don't use `DateTime.now()` in your test to get your `today` variable, instead using something like `package:clock` that will allow you to see the current datetime so your tests behave the same every day
2. Use the proper DateTime utility to subtract a month from the current DateTime object instead of decrementing just the month integer value and reconstructing a new DateTime (this may be the preferred since your widget uses the current date for its initialization)

```dart
MacosIconButton(
  icon: MacosIcon(
    CupertinoIcons.arrowtriangle_left_fill,
    size: 10.0,
    color: datePickerTheme.monthViewControlsColor,
  ),
  backgroundColor: MacosColors.transparent,
  borderRadius: BorderRadius.zero,
  padding: EdgeInsets.zero,
  boxConstraints: const BoxConstraints(
    maxWidth: 12.0,
  ),
  onPressed: () {
    if (_selectedMonth - 1 < 1) {
      setState(() {
        _selectedYear--;
        _selectedMonth = 12;
      });
    } else {
      setState(() => _selectedMonth--);
    }
    widget.onDateChanged.call(_formatAsDateTime());  // This passes your current state variables shown below
  },                                                                                         
),
```

```dart
// In this case, you are passing 2023, 2, 29
// for today's date of 2023, 3, 29
DateTime _formatAsDateTime() {
  return DateTime(_selectedYear, _selectedMonth, _selectedDay);
}
```

**Comment by GroovinChip** [comment]
Commenting to acknowledge awareness of this; can't do much right now unfortunately, will try and get on it asap tho

**Comment by goderbauer** [comment]
The test has been disabled. Rerunning the failing checks should make them green now.
