### ISSUE TITLE
Cocoon cloud deployment fails due to SLSA verification failure

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#123657]
Cocoon cloud deployment has been stuck since last week. The app_dart deploy succeeds, but the following step (Google Cloud Storage) failed:

```
2023-03-28 08:05:36.839 PDT
Step #1: FAILED: SLSA verification failed: source used to generate the binary does not match provenance: expected 'https://git+https://github.com/flutter/cocoon', got 'https://github.com/flutter/cocoon'
```

**Comment by keyonghan** [comment]
@drewroengoogle Could you help take a look?

**Comment by drewroengoogle** [comment]
@keyonghan Good catch! From the looks of it, the issue is that there was a recent change to cloud build that added `git+` to the source uri. However, it doesn't seem like it is completely rolled out, so it sometimes is not adding `git+` to the uri in the provenance every time. I think the change we need to make temporarily is to check for either both source uris, and if one of them passes, then we are good to deploy. Once the change is rolled out completely on their end, we can start to just check for `git+`.

Additionally, I can look into creating an alert when the cocoon deployment fails. I didn't realize it has been failing for this long.

**Comment by drewroengoogle** [comment]
Manually triggered the deployment pipeline for the latest version of cocoon with success. Doing the same for autosubmit. I will keep this open and ensure that tomorrow's automatic deployment goes smooth.

**Comment by drewroengoogle** [comment]
The builds passed this morning. I also added a new log metric and alert to our GCP project that sends an email for any failed builds. Closing this
