### ISSUE TITLE
Connecting to multiple FlutterDrivers

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#12381]
The current version of `FlutterDriver.connect()` only connects to a single Flutter view on a specified device. We need a new version of `connect()` method which connects to a set of Flutter views (e.g. by returning `Future<List<FlutterView>>`).

**Comment by yjbanov** [comment]
The use-case is that in Fuchsia a FlutterView may be running in an isolate rather than a separate VM instance. Currently FlutterDriver assumes one FlutterView per VM instance (it calls [vm.isolates.first](https://github.com/flutter/flutter/blob/efb45ea7881891b895a5a3538be24de7f25f42c3/packages/flutter_driver/lib/src/driver.dart#L165)). This bug is about removing this assumption, instead providing a way to list all available FlutterViews.

**Comment by Hixie** [comment]
@awdavies Am I write to understand that you are working on this?

**Comment by awdavies** [comment]
Yes.  It is currently possible, just not through flutter driver alone.  The `fuchsia_remote_debug_protocol` is able to connect to a flutter view by its isolate name, and can then take that isolate info and drive any arbitrary number of views simultaneously via flutter driver's `connect()` function.  The implementation is just that you need multiple instances of the flutter driver instead of one.

**Comment by Hixie** [comment]
@awdavies What's the status of your work on this? Is it done? Should we close the bug?

**Comment by awdavies** [comment]
I think I'd consider it done.  If there are more bugs they'd be a bit more specific than this.
