### ISSUE TITLE
How to return a custom MaterialPageRoute in GoRouter?

### ISSUE THREAD

**Issue by slice-mohit** [flutter/flutter#123931]
I'm trying using this [package](). It uses a custom MaterialPageRoute for animation named `MaterialWithModalsPageRoute`. Is there a way to return `MaterialWithModalsPageRoute` from GoRoute or some other way to implement it?

**Comment by huycozy** [comment]
Hi @slice-mohit 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve Flutter/Flutter's 1st party packages reporting bugs or feature requests.

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
