### ISSUE TITLE
[Impeller] Reason about flakiness in testing rendering results from Impeller pixel tests.

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#123954]
This web-only revert - https://github.com/flutter/engine/pull/40861 - triggered this impeller Gold digest - https://flutter-engine-gold.skia.org/search?issue=40861&crs=github&patchsets=1&corpus=flutter-engine. It shouldn't have as none of the code involved can affect impeller rendering. I suspect impeller screenshots are flaky.

Here's a snapshot of the digest, in case it gets lost:

<img width="796" alt="Screenshot 2023-04-01 at 6 52 26 PM" src="https://user-images.githubusercontent.com/211513/229326748-499148d0-78c9-41fc-977e-0e49755cabde.png">

**Comment by zanderso** [comment]
@gaaclarke @chinmaygarde Do we already have an issue filed to turn on fuzzy matching?

**Comment by chinmaygarde** [comment]
I linked the meeting notes in Impeller chat that discussed the recommendations of the Skia GPU team on how to do pixel tests when we don't control the client rendering API (i.e, are using and can't control GPU results).

The gist of it is that there is no way to guarantee pixel perfect rendering and there is also no good way to globally configure a fuzzy matcher.

The recommendation was that gold results not be in the critical path for rollers. This is accompanied with an out-of-band triage process that checks for results tripped by gold. The gold instance must be configured to accept multiple valid results (to account for GPU specific differences) for an output test and the triage process would eyeball if a newly detected variant was "close enough". The process is always expected to be semi-manual with the reliance on pixel tests for correctness intentionally kept minimal (as possible).

The expectation was that each test having multiple valid output variants was already how Gold worked today. If so, we should triage these variants as acceptable (they look it to me).

If this issue is that the screenshot tests are not pixel perfect, we can close this as WAI. But we should validate the following:
* Screenshot tests are not in the critical path for auto-rollers.
* Screenshot tests have the feature where there are multiple valid outputs for a specific test.
* There is an out-of-band triage process setup to eyeball the results of the screenshot test to spot regressions.

Either way, we do NOT want fuzzy matching and don't want to get into the business of configuring a fuzzy matcher. Updated the title.

**Comment by zanderso** [comment]
I filed https://github.com/flutter/flutter/issues/123979 to track making the gold checks non-blocking for rolls into the engine.

**Comment by gaaclarke** [comment]
> @gaaclarke @chinmaygarde Do we already have an issue filed to turn on fuzzy matching?

We have a PR here: https://github.com/flutter/engine/pull/40824. No issue.

**Comment by chinmaygarde** [comment]
Closing as followup items have been filed.

**Comment by yjbanov** [comment]
FWIW we use fuzzy matching on the web, and what we found is that a very conservative matching strategy that allows only [a handful of pixels to deviate by a tiny bit](https://github.com/flutter/flutter/blob/f9857df6b3168bd93b68806eeff9313eff373b78/packages/flutter_goldens_client/lib/skia_client.dart#L372) is good enough to eliminate most of the flakes and catch bugs at the same time.

**Comment by chinmaygarde** [comment]
@gaaclarke [added a global threshold](https://github.com/flutter/engine/pull/40824) which I'm hoping is conservative enough. But yeah, gating rollers on results from non-guarantees isn't something I want to deal with. The expectation is that we'll still need a semi manual process to reason about things that escape and I'm setting that up. We'll re-evaluate how that is working from time to time.

**Comment by yjbanov** [comment]
Here's another flake from a PR <1 hour ago: https://flutter-engine-gold.skia.org/search?issue=40937&crs=github&patchsets=1&corpus=flutter-engine

**Comment by gaaclarke** [comment]
> Here's another flake from a PR <1 hour ago: https://flutter-engine-gold.skia.org/search?issue=40937&crs=github&patchsets=1&corpus=flutter-engine

Hey @yjbanov, why does that golden get flagged when the number of different pixels is 6 but `fuzzy_max_different_pixels = 7864` and `fuzzy_pixel_delta_threshold = 8`?
