### ISSUE TITLE
i cant use flutter upgrade in terminal ubuntu

### ISSUE THREAD

**Issue by milad-seify** [flutter/flutter#124149]
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/..../.../flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/.../.../flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/.../.../flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=1_activation.md

**Comment by huycozy** [comment]
Hi @milad-seify 
It could be due to the network you are using that causes the download process was not completed successfully. Please try using another IP or switching to VPN or other settings and see if it helps.

In case you are still facing this issue, you can try [this workaround](https://github.com/flutter/flutter/issues/99890#issuecomment-1068623077):

```
rm -rf /home/<your-username>/flutter/bin/cache
/home/<your-username>/flutter/bin/flutter --version
```
