### ISSUE TITLE
Dynamic Links Doesn't open in Android 13 

### ISSUE THREAD

**Issue by AqsaShaikh1** [flutter/flutter#124110]
When trying to launch the link generated using firebase_dynamic_link plugin, the app doesn't launch in android version 13. It shows circular progress and stops.

**Comment by exaby73** [comment]
Hello @AqsaShaikh1. Since you have a problem with the `firebase_dynamic_links` plugin, you should raise the issue on https://github.com/firebase/flutterfire instead of Flutter. Since this is not an issue with Flutter itself, I will close the issue. If you disagree with my decision, please comment with your reasoning and I can reopen the issue. Thank you
