### ISSUE TITLE
[Impeller] Image loading error after suspending an iOS app that renders a large animated image

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#124269]
* Create a default app and add an `Image.network` with the URL of a large animated image
* Run the app with Impeller on iOS
* Return to the iOS home screen and then resume the app.  After a few cycles of this the app throws an exception:

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: Codec failed to produce an image, possibly due to invalid image data.
```

**Comment by jason-simmons** [comment]
See internal bug b/276833384

**Comment by dnfield** [comment]
There are two places to look at: `ImageDecoderImpeller::Decode` and `MultiFrameCodec::State::GetNextFrameImage`. Both have problems right now, but slightly different ones.

Both will need some `DlImageImpeller` that holds raster data instead of a device allocated texture.

But both takes lightly different paths to get to the point where they upload the texture.
