### ISSUE TITLE
Consider bumping minSdkVersion to 19

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12439]
From the mailing list: " Increase Android minsdkversion to 19 (92.2% of all devices) from 16 (98.8% of all devices). This API level requires ARMv7-A or above and most of these processors do support NEON instructions. This will help focus the effort on future, rather than the past. It may help with the previous point. And by the time Flutter hits v1, <19 would be irrelevant. Finally, only 19<= are receiving monthly AOSP security patches."

**Comment by eseidelGoogle** [comment]
Was also discussed in https://github.com/flutter/flutter/issues/9310 which was closed for unclear reasons.  I support moving us to v19 but would like someone to make a more concrete proposal (@cbracken).

**Comment by Hixie** [comment]
Last time I chatted with customers about this the conclusion was that they'd like us to support v15.
I don't think it is reasonable for us to cut off over 6% of devices (upwards of 100 million users).

**Comment by Brahmasmi** [comment]
Thanks Seth for opening the issue.

In #9310, @dbacinski makes a very important point. Most Flutter projects are greenfield projects. In fact, it would interesting if an external team decides to ditch their existing Android/iOS codebase to adopt an alpha platform like Flutter for their bread and butter work. Within Google, you volks know better. And this goes back to the question of the target audience of Flutter, which is also raised in that comment.

**Security**
@eseidelGoogle @Hixie , if you don't mind, would it be possible to understand from these customers the reason to support users on <19. Yes, there are 120+ million users (6.6% of 2+ billion). However, these devices are also not being patched by AOSP since Jan 2016 [1] [2] and hence are open to security compromises [3] [4]. Given this backdrop, it would be informative to understand why these customers are willing to run the risk of compromised user agents on user devices, for a greenfield project.

One rationale could be this - there are customers who do not authenticate users/perform secure transactions, and there are those who do. The former would like to support 7 if they could, while the latter would look at the security posture.

**Performance**
Flutter regularly has janks on recent devices #9562, #11861, #12250. Extrapolating this to - "Janks on X", (X == older, lower spec devices on API 16+) and then trying to resolve on a per device basis would be a support nightmare, for very little ROI. Further, the minimum ARMv7-A (with optional NEON on most) on API level 19 puts a floor on the CPU expectation [5].

Interestingly, the current low end target - Moto G4 ran Android 6.0.1 (23) on launch, and will remain at Android 7.0 (24). Not sure whether Flutter is being tested against any real world API level 16 device.

[1] - https://source.android.com/security/bulletin/2017-10-01 , lowest patched version is 4.4.4 (19).
[2] - https://source.android.com/security/bulletin/2016-01-01 , lowest patched version is 4.4.4 (19).
[3] - https://arstechnica.com/information-technology/2017/09/bluetooth-bugs-open-billions-of-devices-to-attacks-no-clicking-required/
[4] - Actually, in the real world, AOSP patching does not translate into OEM's rolling out patches. Except a few honourable OEMs, rest just don't bother. But that is a different discussion altogether.
[5] - Although CPU and GPU are two different things, hope OEMs do resist pairing good CPUs with bad GPUs.

**Comment by Hixie** [comment]
@Brahmasmi Many apps don't have anything to compromise. For example, if your app is just a menu for a restaurant, it really doesn't matter if it gets compromised. Also, even beyond that, not everyone cares. They just don't want to exclude millions of potential users. Sure, performance on older phones will be worse. But so what?

**Comment by Brahmasmi** [comment]
@Hixie valid points. The restaurant app would have basic navigation, menu of whats on offer, probably some daily/monthly specials and the contact co-ordinates - most likely the phone number and the physical address. It would be of little relevance to the dev agency of the greenfield app whether the app does 60fps on older devices and/or whether the user agent may be compromised.

The way I see it, it goes back to the question raised earlier - who are the primary customers of Flutter?

It is completely ok for the team to choose who it wishes to target as customers. And going wide is natural for early lifecycle projects. In fact, one could argue that supporting 16+ automatically covers 19+, and that one could simply change the gradle build to achieve the desired effect.

Would it be possible for the project to document the following:
1) The Android API level at which Flutter will strive to achieve 60 fps. API levels below this could be on best-effort basis, but no guarantees. API levels are not mandatory - it could be any other Play-Store-settable criteria. This will help Flutter adopters who wish to provide top-quality UX to their customers.
2) The mechanism/process/parameters/consultation/poll by which Flutter will change the minsdkversion for Android. May not be binding, but a broad arc. This is so that evaluators can determine whether the project priorities align with their own. For reference, API level 10 was released 7 years ago and still has 12+ million devices (0.6% of 2+ billion). But most, if not all, teams tend to not target it.

**Comment by Hixie** [comment]
API levels below 16 are missing some of the low-level APIs we need for pretty much core stuff in the engine, if I recall correctly. That's why we only go back as far as v16. If we could do so reasonably, I'd recommend we target even further back, but as I understand it the effort required for supporting v15 and before is disproportionate to the number of users on those platforms.

Our primary customers on the long term is "everyone who wants to write an app". But that's on the long run. On the short run we're primarily intending to address the needs of agencies writing brand-centric applications, since we believe that their use cases are the more difficult ones to meet and we want to make sure that we can deliver high-quality applications (otherwise, what's the point).

@sethladd can speak to precisely what devices we are targeting for 60fps, 30fps, or 120fps by 1.0, but basically that comes down to what hardware the devices have.

**Comment by sethladd** [comment]
Thanks for all the feedback everyone. We're going to stay with minSdkVersion 16 for now, deferring the decision to change minSdkVersion. We need more data here before we can take another look, but the feedback and insights provided in the comments here are helpful.

**Comment by joshuadeguzman** [comment]
Hi @sethladd, 

I am curious who are we going to change the `minSdkVersion` of flutter module projects? Flutter module generates `.android` dir. Updating it will just be disregarded. Let me know your thoughts.

I filed an issue at [36185](https://github.com/flutter/flutter/issues/36185).
