### ISSUE TITLE
[Impeller] Improve performance of morph filters.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#124416]
Like the gaussian blur, we split the morphology filter into two directional passes. However, we don't appear to perform the texture shrinking trick, nor the linear interoplation to reduce sample count tricks. As a result, the morph filter can be extraordinarily expensive.

**Comment by jonahwilliams** [comment]
maybe we can't exactly do the same shrinking trick, but we could probably do other ones

**Comment by bdero** [comment]
The shrinking trick works really well with blurs because the gaussian blur is a pure low pass filter (removes high frequency detail, like sharp lines). Doing these tricks in the morphology filter would result in extreme quality loss because the output of the morphology filter has sharp lines (high frequency detail).

The "linear sample + mid-sampling" optimization is not mathematically applicable to morphology because it doesn't weight all of the colors together -- it just does simple min-maxing.

**Comment by jonahwilliams** [comment]
Thanks @bdero , I've retitled the issue to be less specific. I'll look at what Skia does here to see if there are any other approaches

**Comment by jonahwilliams** [comment]
Oops, forgot to turn of raster caching for this comparison. We're actually neck and neck with Skia here, though we have a bit more juice we can squeeze by removing the extra texture read/write.

This is an example of where the raster cache does make a huge difference when the child is stable, since it drops the GPU workload from 40ms down to about 7ms.
