### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by venki2009** [flutter/flutter#124498]
## Command
```
flutter drive --driver=test_driver/in

**Comment by venki2009** [comment]
Oops; flutter has exited unexpectedly: "WebDriverException (404): Error parsing response body: <empty response>".

**Comment by huycozy** [comment]
@venki2009 Please provide the information indicated below so that we can address this issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- The complete output when running test with verbose (-v)
- Reproduction steps (the complete test command should be included)
- Which target platform does this issue happen in? 

Thanks!

**Comment by christopherfujino** [comment]
Thank you for filing an issue! However, unfortunately this issue is not currently actionable by our team. Feel free to open a new issue **filling out the template**, including steps to reproduce, relevant logs, and the output of flutter doctor --verbose.
