### ISSUE TITLE
cocoon 503 and 502 from api/public/build-status & api/public/get-status

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#124613]
On the build dashboard:

![Screenshot from 2023-04-11 11-27-07](https://user-images.githubusercontent.com/7856010/231256766-db2bd551-d30c-478e-854b-f86b7a48bc14.png)

It seemed to be transient, and I can still see tree status and individual builds.

**Comment by ricardoamador** [comment]
Will take a look in a bit. Can you please link a pull request or sha where you saw this if that is possible?

**Comment by christopherfujino** [comment]
this was from the build dashboard: https://flutter-dashboard.appspot.com/#/build

**Comment by christopherfujino** [comment]
> Looks like there was a transient error with access to redis:
> 
> ```
> "Bad state: StreamSink is bound to a stream
> #0      _StreamSinkImpl.close (dart:io/io_sink.dart:182:7)
> #1      _Socket.close (dart:io-patch/socket_patch.dart:2243:27)
> #2      RespClient.close (package:neat_cache/src/providers/resp.dart:224:21)

From looking at this line: https://github.com/google/dart-neats/blob/master/neat_cache/lib/src/providers/resp.dart#L224 I think there's a bug that we're not actually catching this error. I'm guessing from reading the code the intention is that callers should never see this kind of error.

**Comment by ricardoamador** [comment]
Okay I added to this open issue for the same problem here: https://github.com/google/dart-neats/issues/153. I see the following options moving forward:

1. We can add a retry when getting the value from the cache in order to recover from this issue. 
2. We can use the getOrCreateWithLocking method to prevent a possible issue with multiple callers/threads getting encountering this situation.
3. We can catch the error and log it and wait for the next call to the status.
4. Or a combination of the above.

This issue has been open with neat-cache since 2021 so it appears that no one is in any hurry to fix it. 
Or we can leave this open to track the problem to see how often it occurs.

**Comment by ricardoamador** [comment]
Did some digging in the logs and it looks like it happens frequently enough that we can see it happen up to a few times a day. So far the most in recent history is 4 times on 04/11/23. I will add call to the locking cache methods first to see this will help to alleviate the issue.

**Comment by ricardoamador** [comment]
Deployed a build with locking on the cache to see if has an effect on traffic.

**Comment by ricardoamador** [comment]
Closing as fixed. Please reopen if encountered again.
