### ISSUE TITLE
The following assertion was thrown during a scheduler callback:

### ISSUE THREAD

**Issue by wasimk1501** [flutter/flutter#124857]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by huycozy** [comment]
As my understanding, you are proposing a better error message so that you can find the cause quickly and fix it. But there are many such proposals (see this [filter](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+error+message%22+label%3Aproposal)) and each issue there will represent different cases.

So I would recommend you take a look at that filter and try to find the similar issue. In case you can't find it, please try to provide all or some of the information indicated below so that we can address this issue properly.

- Reproduction steps
- The complete output of `flutter run -v`
- The output of `flutter doctor -v`

Thank you!
