### ISSUE TITLE
Do not Macmini 7,1 (Intel Iris 5100) to run engine tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#124877]
Please remove these from engine infra configs.

@ricardoamador @yusuf-goog  as infra oncall

These bots are failing engine related tests, and we're finding we have to implement a bunch of work arounds in the infra config to try to avoid using them. There are only a few. 

https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=gpu%3A8086%3A0a2e&f=pool%3Aluci.flutter.staging&k=pool&s=id and https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=gpu%3A8086%3A0a2e&f=pool%3Aluci.flutter.try&k=pool&s=id are the lists. None of these bots should run engine tests at all. They are fine for framework tests.

@zanderso @chinmaygarde fyi

**Comment by godofredoc** [comment]
The execution of unit tests is deeply embedded in the builds. I believe people from engine with a better understanding of the builds is better equipped to make these changes in .ci.yaml or build configurations.

An alternative is to provide a list of builds that  should not use `Macmini 7,1` so that infra can help with the change.

**Comment by jmagman** [comment]
Note the way to work around this probably shouldn't be to specify `mac_model=Macmini8,1` since that's forcing us to use  Intel `Macmini8,1` instead of giving the flexibility to run on either those bots or arm `Macmini9,1` bots, but not `Macmini7,1`.

**Comment by zanderso** [comment]
I think what @dnfield means is that  `Macmini 7,1` should not be used by engine CI (try, staging, prod) for anything. Our assumption is that there is a global infra setting or configuration that can accomplish that rather than going over every sub-build individually.

**Comment by jmagman** [comment]
> I think what @dnfield means is that `Macmini 7,1` should not be used by engine CI (try, staging, prod) for anything. Our assumption is that there is a global infra setting or configuration that can accomplish that rather than going over every sub-build individually.

Definitely, I agree, would be good to remove them from the pool.  I meant that our workarounds like #41203 and #41159 locking to `Macmini8,1` are preventing us from running those builds on either arm or Intel as capacity allows, and removing `Macmini7,1` from the pool would solve that problem.

**Comment by godofredoc** [comment]
This can be achieved by adding a dimensions property here https://cs.opensource.google/flutter/engine/+/main:.ci.yaml;l=57. Dimensions are lists of values merged by `or` in the swarming service.

Please let us know if the functionality does not work out of the box.

**Comment by zanderso** [comment]
@godofredoc I can't see any documentation for what you're suggesting in the docs linked at the top of the ci.yaml here: https://github.com/flutter/cocoon/blob/main/CI_YAML.md.

Can you please like to documentation for what you're describing, or an example of something similar being done in another configuration? If neither of those exist, I would suggest that this issue is correctly on the infra ticket queue, and we need help from the infra gardener in order to get this done.

**Comment by ricardoamador** [comment]
@zanderso https://github.com/flutter/flutter/blob/master/.ci.yaml#L1452 that target uses dimensions.

**Comment by zanderso** [comment]
@ricardoamador Thanks! I'm having trouble reconciling that example with what @godofredoc said above: "Dimensions are lists of values merged by or in the swarming service." In the example, `dimensions` appears to be a map, but @godofredoc said it is a list, so I'm still not sure how to accomplish what this issue is asking for.

**Comment by ricardoamador** [comment]
Hmm, maybe he mistyped? They should be a map. You will need to specify the key and the value.

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/41219 <- ptal

**Comment by ricardoamador** [comment]
I think you might need to unindent the dimensions. The dimensions do not go under properties.

**Comment by dnfield** [comment]
Could we move these bots to a separate pool and then not include that pool in engine builds/tests?

**Comment by dnfield** [comment]
The main problem with the configuration file updates is there are a lot of places that end up needing this, and some of those places don't allow comments, and no one seems to have a good way to make sure we're covering all of them short of watching for a new failure to pop up.

**Comment by godofredoc** [comment]
We can ask chromium to  remove them but we will be getting rid of ~10% of the try mac intel capacity. If we are ok with that we can follow up with a chromium bug but just to set expectation the queue time in try will increase considerably.

**Comment by dnfield** [comment]
> We can ask chromium to remove them but we will be getting rid of ~10% of the try mac intel capacity. If we are ok with that we can follow up with a chromium bug but just to set expectations, the queue time in try will increase considerably.

We don't need them to be removed completely, we just need to make sure they're not used for engine builds.
