### ISSUE TITLE
Flutter Web Release mode, how to get and restore the compressed type name?

### ISSUE THREAD

**Issue by xdd666t** [flutter/flutter#124915]
### Some problems encountered so far

- known
  - I can get an object instance, such as `Test ()` , and I can also get all the code text content through `AssetManifest.json`
  - but the instance and code text content cannot determine the correspondence, I need to make a match between them
- Current
  - I can get the instance name (`Test`)  through `runtimeType.toString`, then scan all the code text, do regular matching on it, and can determine the correspondence between the instance and a certain code text
  - However, in Flutter Web Release mode, dart2js will compress the type name, and the instance name of `Test` may become `minified: Ah`, which cannot match the corresponding code text

### I thought of some workarounds

- Restore the compressed type `minified: Ah`  to `Test`
- Turn the obtained `Test` string into `minified: Ah` with the same compression algorithm.

Both of the above methods can solve the current problem. Is there a way to implement the above solution?

**Comment by darshankawar** [comment]
Thanks for the report @xdd666t 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the current behavior vs expected result you are looking for ? That way it'll help us to properly address the issue.

**Comment by darshankawar** [comment]
> and a minimal complete reproducible code sample that shows the current behavior vs expected result you are looking for ? That way it'll help us to properly address the issue.

@xdd666t Also this is required in order to analyze and make this issue actionable, so please provide this.

**Comment by xdd666t** [comment]
> @xdd666t Also this is required in order to analyze and make this issue actionable, so please provide this.

In the previous reply, I completed the supplementary information, you can check it out

**Comment by darshankawar** [comment]
Thanks for the update.
To answer your question, on how to get and restore compressed type name, take a look at [this](https://github.com/flutter/flutter/issues/78041) issue and underlying comments and see if it helps in your case or not.

**Comment by xdd666t** [comment]
> ### I thought of some workarounds
> * Restore the compressed type  to `minified: Ah``Test`
> * Turn the obtained  string into  with the same compression algorithm.`Test``minified: Ah`
> 
> Both of the above methods can solve the current problem. Is there a way to implement the above solution?

I've seen this issue, it doesn't really help me

### I thought of some workarounds

- Restore the compressed type `minified: ya` to `MyHomePage `
- Turn the obtained `MyHomePage` string into `minified: ya` with the same compression algorithm.

Both of the above methods can solve the current problem. Is there a way to implement the above solution?

**Comment by xdd666t** [comment]
@maRci002 Thanks for your help, using this command, you can indeed adjust the level of flutter web packaging, but the `o1` compression level has an impact on the volume that exceeds my imagination

```dart
# main.dart.js: 7.379MB
flutter build web --dart2js-optimization O0 
# main.dart.js: 5.073MB
flutter build web --dart2js-optimization O1
# main.dart.js: 1.776MB
flutter build web --dart2js-optimization O2
# main.dart.js: 1.716MB
flutter build web --dart2js-optimization O3
# main.dart.js: 1.687MB
flutter build web --dart2js-optimization O4
```

**Do you know the following two ideas and related implementation methods?**
- Restore the compressed type `minified: ya` to `MyHomePage`
- Turn the obtained `MyHomePage` string into `minified: ya` with the same compression algorithm.

**Comment by maRci002** [comment]
When JavaScript code is compressed, the original method names are usually replaced with shorter names or random characters, making it difficult to retrieve the original method names from the minified code.

However, if a source map is generated during the minification process, it is possible to use it to map the compressed code back to its original form, including method names. For example, you can generate a source map using the command `flutter build web --release --source-maps`.

Note: this mapping information is not available at runtime. This means that you cannot access the original method names dynamically in your code during runtime. The mapping information is usually used during debugging and development to help developers understand the code, rather than in production.

To view the source map file in Chrome, follow these steps:

1. Open your web app in Chrome.
2. Open the Chrome DevTools by pressing F12 or right-clicking anywhere on the page and selecting "Inspect".
3. In the DevTools, go to the "Sources" tab.
4. Look for the `main.dart.js` file in the list of sources on the left-hand side.
5. Expand the `main.dart.js` file to reveal its contents.
6. If a source map was generated during the build process, you should see a reference to the source map file, `main.dart.js.map`, in the bottom right corner of the expanded file.
7. Click on the reference to the source map file to open it in the DevTools.

Once you have opened the source map file, you can use it to map the compressed code back to its original form, including method names, as well as set breakpoints and debug your code.
