### ISSUE TITLE
 Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by Li-00** [flutter/flutter#124958]
Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.

`return Stack(children: viewContent);`

**Comment by huycozy** [comment]
Hi @Li-00 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that can reproduce this issue
- The complete stack trace
- The output of `flutter doctor -v`
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

May be similar: https://github.com/flutter/flutter/issues/84241
