### ISSUE TITLE
Can `FlutterEngineGroup` cache a `FlutterEngine` in advance?

### ISSUE THREAD

**Issue by Dboy233** [flutter/flutter#124941]
Use FlutterEngine, I can cache an engine in advance so that the Flutter interface opens faster when I use it.    
 But using FlutterEngineGroup cannot cache one in advance 。

 why？if can。how to do。

**Comment by Dboy233** [comment]
> Hi @Dboy233 Can you be more specific on the issue? Are you implementing [multiple Flutters](https://docs.flutter.dev/development/add-to-app/multiple-flutters)?

@huycozy 
Business:
app UI1 button click->open Flutter UI1 and click button -> open appUI2 and button click -> open Flutter UI2

When using FlutterEngineGroup. Only when opening the first FlutterUI, the Flutter is delayed opening due to the creation of the first Flutter Engine within the Group. Open the Flutter page again because sharing resources creates a new engine very quickly.
So I want to make a FlutterEngine when I initialize FlutterEngineGroup, like I've cached a global engine.

**Comment by huycozy** [comment]
It seems this issue only happens in debug mode, it's faster in release mode, please see [this](https://github.com/flutter/samples/issues/779#issuecomment-848604003).

Also, this is a known issue at https://github.com/flutter/flutter/issues/86231 (is filed from https://github.com/flutter/samples/issues/779) but can not reproduce it. It would be great if you could leave there your case with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that others can take a look at it. 

I will close this issue in favor of https://github.com/flutter/flutter/issues/86231, so please follow up on it for further updates. Thank you!
