### ISSUE TITLE
It is SUGGESTED that the project use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#125013]
Examples of mechanisms to detect memory safety problems include [Address Sanitizer (ASAN)](https://github.com/google/sanitizers/wiki/AddressSanitizer) (available in GCC and LLVM), [Memory Sanitizer](https://clang.llvm.org/docs/MemorySanitizer.html), and [valgrind](http://valgrind.org/). Other potentially-used tools include [thread sanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html) and [undefined behavior sanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html). Widespread assertions would also work.

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by godofredoc** [comment]
This best practice applies to the flutter engine repository which is build on c/c++. This best practice is covered by testing with assertions enabled for the multiple supported platforms.

**Comment by godofredoc** [comment]
Initial version: https://github.com/flutter/flutter/wiki/security

**Comment by zanderso** [comment]
> Initial version: https://github.com/flutter/flutter/wiki/security

Can we do this in a google doc first? I can't make comments on the wiki page. Alternately you can propose wiki edits in a pull request, but I don't know the specifics of doing that.

**Comment by zanderso** [comment]
Unopt builds only turn on assertions for the engine. They do not turn on assertions for Skia or the Dart VM. For Skia and Dart, tests run with assertions on their respective CIs.

We currently only run asan and lsan builds on Linux: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine_unopt.py#157.

We are not running asan on macOS or Windows due to resource constraints, and because it would not increase coverage very much.

Instructions for building the engine with sanitizers is here: https://github.com/flutter/flutter/wiki/Using-Sanitizers-with-the-Flutter-Engine

**Comment by godofredoc** [comment]
Here is the doc: go/flutter-best-practice-sec-docs, also if you prefer please feel free to update the doc or wiki directly.

**Comment by godofredoc** [comment]
https://github.com/flutter/flutter/wiki/security#Best-practices
