### ISSUE TITLE
The `mac_unopt` ios_debug_sim test fails with xcode 14c18

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125216]
Hit the failure when updating xcode to 14c18: https://github.com/flutter/engine/pull/41370

Example build: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_unopt/199/overview

```

Command run successfully in 0.17 seconds: xcrun simctl delete IosUnitTestsSimulator
Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1229, in <module>
    sys.exit(main())
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1212, in main
    run_objc_tests(args.ios_variant, args.objc_filter)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 745, in run_objc_tests
    run_cmd(test_command, cwd=ios_unit_test_dir, shell=True)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 113, in run_cmd
    raise Exception(
Exception: Command "xcodebuild -sdk iphonesimulator -scheme IosUnitTests -destination name='IosUnitTestsSimulator' test FLUTTER_ENGINE=ios_debug_sim" exited with code 70.
```

/cc @jmagman @zanderso

**Comment by jmagman** [comment]
`mac_unopt` needs the latest simulator runtime for the `Tests for ios_debug_sim_arm64` step:
```
Ineligible destinations for the "IosUnitTests" scheme:
...
error:iOS 16.2 is not installed. To use with Xcode, first download and install the platform }
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783283434209877409/+/u/test:_Tests_for_ios_debug_sim_arm64/stdout

And it also needs iOS 16.0 for the scenario tests. That's hardcoded because it corresponds to particular golden screenshots that often change with an OS version bump so need to be regenerated.
https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L51
and 
https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L61

So in that PR should the runtimes be:
```
                    "runtime_versions": [
                        "ios-16-2_14c18",
                        "ios-16-0_14a5294e"
                    ],
```

cc @vashworth @cyanglaz

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/125227 to use 16.2 default simulator for the golden tests.
