### ISSUE TITLE
Flutter google map on release mode not work but in debug work !!

### ISSUE THREAD

**Issue by mayed123502** [flutter/flutter#125382]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter google map on release mode not work but in debug work !!

### Expected results

Flutter google map on release mode not work but in debug work !!

### Actual results

Flutter google map on release mode not work but in debug work !!

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
Flutter google map on release mode not work but in debug work !!

**Comment by huycozy** [comment]
I run a sample code with `google_maps_flutter: ^2.2.5` plugin and see it works well in release mode. Verified on Android.

Please try to provide all or some of the information indicated in the template so that we can address this issue properly. 
More specifically:
- Does it happen when running with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example)? If it doesn't happen, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- What is the current `google_maps_flutter` plugin version
- How does it not "work"?
- Which environment did this issue happen in? (Android/iOS)
