### ISSUE TITLE
SENSORS

### ISSUE THREAD

**Issue by DavidVyhmeister** [flutter/flutter#125309]
Hi.
i'm trying to add
sensors: ^0.8.4+2 on dependencies:
but i got this error.
[proyecto_crumbs] flutter pub get
Resolving dependencies...
Git error. Command: `git clone --mirror git://github.com/fluttercommunity/sensors.git C:\Users\David\AppData\Local\Pub\Cache\git\cache\sensors-167e421677789dfea279f6c88fc48349cb69039c`
stdout: 
stderr: Cloning into bare repository 'C:\Users\David\AppData\Local\Pub\Cache\git\cache\sensors-167e421677789dfea279f6c88fc48349cb69039c'...
remote: Repository not found.
fatal: repository 'https://github.com/fluttercommunity/sensors.git/' not found
exit code: 128
exit code 69

where can i found this library?
thanks

**Comment by iapicca** [comment]
@DavidVyhmeister 
[sensor](https://pub.dev/packages/sensor) plugin is [deprecated](https://pub.dev/packages/sensors#deprecation-notice) you can use [sensors_plus](https://pub.dev/packages/sensors_plus)
if you have any issue with the latter please open an issue in the [plus_plugins](https://github.com/fluttercommunity/plus_plugins/issues)

**Comment by huycozy** [comment]
@DavidVyhmeister Please try adding `sensors_plus` as suggested above. I also would recommend you file a new issue on [plus_plugins](https://github.com/fluttercommunity/plus_plugins/issues) if you have a specific issue with these plugins.

Since this doesn't look like a Flutter framework issue, I will close the issue from here. If you still have this issue when adding any other packages, please write in the comments and I will reopen this for further investigation. Thank you!
