### ISSUE TITLE
FLutter web does not select the environment that I indicate

### ISSUE THREAD

**Issue by RichardM20** [flutter/flutter#125563]
I recently had to work with environments in flutter and define the environment my project goes to at project build time, everything works fine when it comes to running the project with the command **flutter run -d chrome --dart-define=ENVIRONMENT= .env.stg**, since when viewing the content of my index.html it changes as it should depending on the environment that I indicate.
The problem is when I build the project, for some reason, no matter how much I define the environment, it does not change to the one I indicate, I know because the validations that I have do not occur in my index and a different content is displayed than it should depending on of the environment
**flutter build web --dart-define=ENVIRONMENT=.env.stg**

Do you have any idea what could be the problem?

**Comment by callmephil** [comment]
Have you tried to pass the absolute path of .env.stg ?

You may know already but instead of an .env file you could use [flavors](https://docs.flutter.dev/deployment/flavors)

**Comment by huycozy** [comment]
@RichardM20 Please try to provide all or some of the information indicated in the template so that we can address this issue properly.

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Does the issue only happen on Web? Have you checked it on other platforms?

And please also check if this issue (https://github.com/flutter/flutter/issues/65982) is similar to your case (flutter driver on web). Thank you!
