### ISSUE TITLE
Autoroller bot seems to incorrectly closer PRs if tasks have been rerun?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#125594]
See https://github.com/flutter/flutter/pull/125592

A shard flaked (It was a skia gold check), the bot removed the autosubmit label. I clicked rerun on the shard and then re-added the auto submit label. After all the tests passed, the PR was still closed by the autoroll bot.

**Comment by jonahwilliams** [comment]
If the bot is going to closer the PR after a single task runs regardless of the rerun status, then it should probably _immediately_ closer the PR on getting a failed check rather than using more resources.

**Comment by godofredoc** [comment]
@rmistry is there a skia autoroller config that we can update to prevent closing the PRs if tasks are retried?

**Comment by rmistry** [comment]
@erock2112 (borenet@) is the new primary for the Flutter autoroller.
I would have expected the roller to see that the autosubmit label is still around and not abandon. So I am not sure why it closed the PR.

**Comment by erock2112** [comment]
Looks like the label was removed at 8:06 pm EDT.  The roller noticed the removal within a minute and entered the failure-throttled state.  In that state, the roller waits up to an hour before retrying the commit queue.  If new commits become available to roll during that time, the roller will close the PR and create a new one.  At 8:45 pm, https://github.com/flutter/engine/commit/d4ca5240da52c0385a778d55803aa9cf93ec1c43 became available to roll (there's some amount of delay due to filtering on successful buildbucket builds), so the roller closed the PR and moved on.

Given the complexity of the autoroller operation, it's difficult to predict when and how to react to human intervention, but I think I have an idea of how to recognize this situation and react appropriately.

**Comment by erock2112** [comment]
https://skia-review.googlesource.com/c/buildbot/+/684536 landed last week and is live on the autorollers.  I believe that should fix this particular flow.

**Comment by jonahwilliams** [comment]
Awesome, thank you!
