### ISSUE TITLE
Add the ability to pass in java jdk as part of flutter build/run

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#125652]
This would take precedence over the android studio java searching logic. 

This is especially important when trying to work on old flutter apps on a machine that has the Flamingo version of Android Studio.

**Comment by andrewkolos** [comment]
Related issue: https://github.com/flutter/flutter/issues/106416

**Comment by andrewkolos** [comment]
Closing as un-planned since the new `flutter config` option provided by https://github.com/flutter/flutter/pull/128264 might be sufficient.

If anyone desires the ability to set the JDK at the command level (`flutter build` or `flutter run`), they can comment on this issue, and we can reopen it.

**Comment by KristijanZic** [comment]
Please, it's impossible to use flutter sdk on Linux since jdk got renamed to jbr. If I point to android-studio directory it doesn't find java anymore. Please enable the option to specify jdk/jbr.

**Comment by andrewkolos** [comment]
> Please, it's impossible to use flutter sdk on Linux since jdk got renamed to jbr. If I point to android-studio directory it doesn't find java anymore. Please enable the option to specify jdk/jbr.

This ability should be coming with the next minor version of Flutter. See [my previous comment](https://github.com/flutter/flutter/issues/125652#issuecomment-1581235109), which I have since edited for better clarity. 

More importantly, this option should only be needed if you have multiple flutter projects of varying age that require different versions of the JDK. If all your Flutter projects are fairly up-to-date and you have a fairly up-to-date installation of Android Studio, then you shouldn't have a problem. If you still have this problem, please open a new issue, and feel free to mention me in it.
