### ISSUE TITLE
[pigeon] codegen test setup using expected files

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#125847]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In current setup, we checkin 1-2 generated files (out of 10~ files), and manually write unit test to verify if a code section is generated ([example](https://github.com/flutter/packages/blob/main/packages/pigeon/test/swift_generator_test.dart#L451-L456)). 

This makes the unit test a bit tedious to do, and code review is not complete. 

### Proposal

We can checkin all expected files (under test dir), and do not checkin generated files. When running tests, we can generate files under temp dir, then simply run a diff between expected vs generated files. 

Benefits: 
1. Once this is setup, the codegen test is much easier to write - most of the time we simply update the codegen, then fix the expected files, without actually touching test logic. 
2. It's also very easy to fix the expected files. We can simply run a command based on the diff result, without manual change. 
3. It also makes code review much easier. Whenever behavior is changed, the expected files will also be changed and will be included in the PR. 

The auto-formatter may be a concern - with our current structure, it's very hard to respect the formatter, so for now we may need an extra step of formatting generated files before doing the diff (so that the checked-in expected files are well formatted for code review). However, [this proposal](https://github.com/flutter/flutter/issues/125843) may address the format issue. 

CC @stuartmorgan @tarrinneal

**Comment by stuartmorgan** [comment]
> we checkin 1-2 generated files (out of 10~ files)

That's a legacy of the previous, more ad-hoc test structure, that we just haven't finished standardizing. See https://github.com/flutter/flutter/issues/115168. It's already significantly better than it was.

> This makes the unit test a bit tedious to do

In general the focus now is on integration tests; unit test are primarily for things that we can't meaningfully cover with integration tests.

> and code review is not complete.

When we finish consolidating, it will be.

> We can checkin all expected files (under test dir), and do not checkin generated files. When running tests, we can generate files under temp dir, then simply run a diff between expected vs generated files.

The current situation is that we check in generated files and CI validates that regenerating them doesn't create any changes. If we are enforcing that there are no changes, then "checkin all expected files (under test dir), and do not checkin generated files" and "check in generated files" are identical in the steady state.

> 1. Once this is setup, the codegen test is much easier to write - most of the time we simply update the codegen, then fix the expected files, without actually touching test logic.

I'm not clear on how updating every single instance of a single pattern in a golden file is less work than updating a single instance in a unit test file.

> 2\. It's also very easy to fix the expected files. We can simply run a command based on the diff result, without manual change.

The current situation is that the files are updated automatically simply by running generation, so this sounds like slightly more work than the current setup, not less.

> 3\. It also makes code review much easier. Whenever behavior is changed, the expected files will also be changed and will be included in the PR.

That's exactly why everything is being consolidated into the checked-in file. See https://github.com/flutter/flutter/issues/99926

> The auto-formatter may be a concern - with our current structure, it's very hard to respect the formatter, so for now we may need an extra step of formatting generated files before doing the diff

This is already implemented in Pigeon tests that are run in CI.

I suspect that this issue is largely a reaction to https://github.com/flutter/flutter/issues/115168 not being completed (PRs welcome to continue that work) rather than something that would meaningfully improve over the target state that we are already working toward.

**Comment by hellohuanlin** [comment]
Gotcha. The ongoing effort should achieve the same goal. We can close this.
