### ISSUE TITLE
How can I force a rebuild for every run ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#126083]
If you don't change any files in between 2 runs, Flutter won't rebuild the app. I don't want this behavior, I'd like the app to be rebuilt on every run no matter what. How can I achieve this ?

**Comment by darshankawar** [comment]
@TheCarpetMerchant 
I think your question is better suited for support channels like StackOverflow, or can reach out in flutter reddit help page or on discord for existing solutions. If you are looking to propose new changes in existing behavior as how it rebuilds the app currently, please use relevant template and fill out requested details so that we can address it as applicable.
I'll close it for now.
