### ISSUE TITLE
Could not start Dart VM service HTTP server

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [flutter/flutter#126065]
Issue:
![image](https://user-images.githubusercontent.com/67002144/236230142-1063ebbe-169b-4927-b69b-41edeb909aae.png)

- My application throws this error when I try running it on a physical android device however... It works on the emulator.
- Also I'd like to add I saw a few solutions online about adding the internet permission in AndroidManifest.xml file.. I tried that but with no luck

Steps to reproduce:
- I don't know.. It just won't work

**Comment by darshankawar** [comment]
@VaibhavKukreti-Kathud 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
Can you provide `flutter doctor -v` and run `flutter run -v`, provide the complete verbose log in properly formatted text or in a file ?
Also, if you create a new Flutter project and run on same device, do you still get the same error ?

**Comment by VaibhavKukreti-Kathud** [comment]
Sorry for not providing the required info.. I am new to opening issues and all..
well here's the flutter doctor
![image](https://user-images.githubusercontent.com/67002144/236610138-56c100d6-31dc-448d-a204-1de8b9972c58.png)
The "flutter run -v" is incredibly large though.. I'll provide it in a later comment in this thread.. 
and yes if I try running another project on my phone it works perfectly fine and i am able to debug correctly

**Comment by darshankawar** [comment]
I believe you are hitting https://github.com/flutter/flutter/issues/115921, so please follow-up in that issue for further updates. You may also upvote the original issue to get team's attention and priority.
Closing this as a duplicate.
