### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by Lite-os15** [flutter/flutter#126055]
RenderBox was not laid out: RenderAnimatedOpacity#fe276 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2009 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

**Comment by huycozy** [comment]
Hi @Lite-os15 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
