### ISSUE TITLE
Kotlin dist downloading failed

### ISSUE THREAD

**Issue by maurovanetti** [flutter/flutter#126248]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade to _Android Studio Flamingo | 2022.2.1 Patch 1_.
2. Open a Flutter project.

### Expected results

I expect the project to open with no exceptions.

### Actual results

I get this exception, twice, in the notifications:

> Failed to download Kotlin Compiler Maven artifact (org.jetbrains.kotlin:kotlin-dist-for-jps-meta:1.8.0-release). The search was performed in the following repos: https://repo1.maven.org/maven2 https://repository.jboss.org/nexus/content/repositories/public/ You can use Kotlin compiler which is bundled into your IDE. Select 'Bundled' version in 'File | Settings | Build, Execution, Deployment | Compiler | Kotlin Compiler | Kotlin Compiler version'

(By the way, there is no _Kotlin Compiler_ submenu in _File | Settings | Build, Execution, Deployment | Compiler_…)

### Code sample

My code is likely not involved, this happens at project opening, and with all my Flutter projects.

### Screenshots or Video

<details>
<summary>Screenshot</summary>

![Screenshot 2023-05-08 08-10-20](https://user-images.githubusercontent.com/402070/236747438-ce4fad34-b447-42f8-b641-51aecbf5a686.png)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.10.0-1.5.pre, on Ubuntu 22.04.2 LTS 5.15.0-71-generic, locale it_IT.UTF-8)
    • Flutter version 3.10.0-1.5.pre on channel beta at /home/mauro/Codice/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b1c77b7ed3 (5 giorni fa), 2023-05-02 21:11:36 -0600
    • Engine revision 50e509c2bd
    • Dart version 3.0.0 (build 3.0.0-417.4.beta)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/mauro/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio-2022.2.1/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio-2022.2.1/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4560
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-71-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.165

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
After upgrading to that Android Studio version, I also see the same notification, but the Flutter project still can run normally. 

Also, this issue is only happening on some old Flutter projects (not all). When opening the newly created Flutter project (stable/beta/master), the issue doesn't happen. 

When searching this, I see it's mentioned on [Failed to download Maven artifact](https://youtrack.jetbrains.com/issue/KTIJ-22047/Improve-Failed-to-download-Maven-artifact). 

And then after comparing `.idea/kotlinc.xml` between affected old Flutter project and new one, there is no `kotlinc.xml` file on new Flutter project (I have no idea why it's there, maybe by adding some plugin?).

- Affected project (has issue):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="KotlinJpsPluginSettings">
    <option name="version" value="1.8.0-release" />
  </component>
</project>
```

- New project (has no issue): no such file

Okay, now I copy `kotlinc.xml` file from affected project to new project, the issue appears!

Next, I also check [intellij-community/blob/master/.idea/kotlinc.xml](https://github.com/JetBrains/intellij-community/blob/master/.idea/kotlinc.xml), I guess `1.8.0-release` is not available. So after changing the version to `1.8.0`, the issue doesn't happen anymore.

So I think it's an intellij issue rather than Flutter issue. I would suggest following up on above linked issue for further updates. Closing the issue from here. Meanwhile, you can try using `1.8.0` as workaround for this. Thanks!

**Comment by zerowaitstate** [comment]
Thanks, this post helped me a lot.  I had the same issue.

**Comment by Sun3** [comment]
Yep, that works great.
