### ISSUE TITLE
Mysterious `fuchsia/sdk/core.tar.gz` showing up in `Linux linux_license` runs

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126475]
In https://github.com/flutter/flutter/issues/126441 it was noted that the license checker was failing against `.rom` files inside of the `fuchsia/sdk/core.tar.gz` file.  @aam mentioned that those files shouldn't even be there.

https://github.com/flutter/engine/pull/41900 made it so that those files aren't erroneously read as utf8 files, but for performance reasons we should identify where `core.tar.gz` is coming from.

**Comment by gaaclarke** [comment]
Looking at the DEPS file, gclient doesn't appear to put anything directly in `fuchsia/sdk`.  There is code to fill in `fuchsia/sdk/mac` and `fuchsia/sdk/linux`.  https://github.com/flutter/engine/blob/7ad6470717e61938cfe57b56deb168ef7fae2abe/DEPS#L880

**Comment by aam** [comment]
Could it be coming from https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/femu_test.py#998 ?
Hypothesis is that the buildbot that gets license script task had this femu script run at some point in the past, which polluted fuchsia sdk folder with this core.tar.gz file.

Running this license task with clobbering enabled might solve this too.

**Comment by gaaclarke** [comment]
Sounds plausible, looking at the history of that bot that failed, it does have some executions of fuchsia tests: https://chromium-swarm.appspot.com/bot?id=flutter-try-ubuntu-us-central1-a-41-nglc

**Comment by gaaclarke** [comment]
@aam note that you are pointing to the recipe for the old engine.  The failing check was on an engine_v2 run.  The way we determine to clobber files with engine_v2 is a bit different.

**Comment by godofredoc** [comment]
Found the root cause(s):

@aam is correct, fuchsia femu test is leaving behind `<cache>/builder/src/fuchsia` and engine_v2 optimizes the clobber logic to only delete `<cache>/src/out`. E.g. https://ci.chromium.org/p/flutter/builders/prod/Linux%20linux_license/20

The second issue is related to web_engine builds wich generate files inside `<cache>/src/flutter`. E.g. https://ci.chromium.org/p/flutter/builders/prod/Linux%20linux_license/16

We have two different options:

* Clobber the entire <cache>/builder as in the legacy builder
* Optimize the workflows placing the fuchsia artifacts inside `<cache>/builder/src/out`. Deleting  `<cache>/builder/src/out` is the first step on every build and will ensure the fuchsia folder does not impact any other builder. In addition to that we'll need to run a hard reset to ensure all the web_engine artifacts are removed. An optimization will be to generate the engine artifacts in out.
