### ISSUE TITLE
Many Android build tests flaking on reading debug keystore

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126557]
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20plugin_dependencies_test/20412/overview

```
com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/home/chrome-bot/.android/debug.keystore": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
```

Marking P1 because this is causing many tests to flake, and blocking autorollers on flaking presubmit checks.

**Comment by zanderso** [comment]
Here's another example from framework CI: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20build_tests_2_3/3054/overview

**Comment by zanderso** [comment]
I filed this feature request for the autosubmit bot in response to these flakes: https://github.com/flutter/flutter/issues/126556. This would allow the autorollers to keep moving while we triage the flakes out-of-band.

**Comment by godofredoc** [comment]
This  does not seem to be an infra/hardware problem.

@reidbaker can you please take a look? is this related to updates in jdk versions?

**Comment by zanderso** [comment]
Sorry, I assumed this was infra-related because the tests are looking in `/home/chrome-bot/.android/debug.keystore`, which the name would imply is an infra managed file system location?

**Comment by gmackall** [comment]
Looks like there are some previous examples of this error mentioned here: https://github.com/flutter/flutter/issues/126267

**Comment by godofredoc** [comment]
This is the home directory of the user running the bot, maybe gradle, jdk or the test itself are trying to write state?

**Comment by gmackall** [comment]
Spent some time investigating this with @camsim99, short version of long update is that it seems likely to us that this was caused by this change https://github.com/flutter/flutter/pull/125323

Long version: It looks like these failures were first reported in [this issue ](https://github.com/flutter/flutter/issues/125885)filed by @reidbaker a week ago, where the linked failures in that issue came from builds kicked off by these prs (that among other things) changed some test recipes to use java 17: https://github.com/flutter/flutter/pull/125825, https://github.com/flutter/flutter/pull/125323. 

The second of the two PRs linked above was merged 3 days ago, and after that we started seeing the same failures in presubmits on other PRs (reported here https://github.com/flutter/flutter/issues/126267, with the linked PRs being these:https://github.com/flutter/flutter/pull/126352, https://github.com/flutter/engine/pull/39391). 

Based on what I understand about the error itself, it can be caused by trying to build with one version of java, while using signing keys that were generated with another version of java (see [this stack overflow post](https://stackoverflow.com/questions/67631927/error-building-aab-flutter-android-integrity-check-failed-java-security-n/67632064#67632064)). The particular debug signing keys that are called out in the failures seem to be [generated on installation of the android sdk](https://stackoverflow.com/a/2197293).

I'm not super knowledgable on particulars of how the tests get run on our ci, so feel free to correct if any of the following is off, but one possible theory would be that these tests are being run in a group on the same machine and are somehow sharing state (as it seems this directory is the home directory of the user running the bot?). In the case that the [particular tests that were modified to use jdk 17](https://github.com/flutter/flutter/blob/fa117aad283ba930a7a79b472843b19e52f543bd/.ci.yaml#L260) run first, on setup they generate a debug signing key using jdk 17, and then the future tests that are running with jdk 11 (all the failures so far are using jdk 11) try to load this key but are unable to because it was generated using an algorithm that isn't included in the jdk 11 we are using. 

So it would flake only if the tests that ran first were the jdk 17 tests. I don't know if the ordering of the tests is deterministic, but if it isn't that would be a potential reason this would flake (vs always failing).

**Comment by godofredoc** [comment]
In general tests should not leave/depend on state outside of the build sandbox. Is it possible to instruct the test to generate and look for the keystore within the sandbox? maybe controlling it with an env variable or similar mechanism?

For reference jdk is setup/removed on every build execution https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=124

**Comment by gmackall** [comment]
> In general tests should not leave/depend on state outside of the build sandbox. Is it possible to instruct the test to generate and look for the keystore within the sandbox? maybe controlling it with an env variable or similar mechanism?
> 
> For reference jdk is setup/removed on every build execution https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=124

It looks like for the [corresponding android sdk setup](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=124), we only set `ANDROID_SDK_ROOT`, `ANDROID_HOME`, and `ANDROID_NDK_PATH`, and none of these control the location of the `.android` directory which contains these keys (among some other configuration).

I think if we changed it to also set [`ANDROID_USER_HOME`](https://developer.android.com/tools/variables), we could keep these keys within the sandbox.

**Comment by godofredoc** [comment]
Nice! replicated using:

`led get-build 8781351241182211249 | led edit -d id=flutter-prod-windows-us-central1-c-13-w8rm | led edit-system -p 20 | led launch -modernize`

* https://chromium-swarm.appspot.com/task?id=62265fa3f2b79210

**Comment by godofredoc** [comment]
`led get-build 8781351241182211249 | led edit -d id=flutter-prod-windows-us-central1-c-13-w8rm | led edit-recipe-bundle| led edit-system -p 20 | led launch -modernize`

https://chromium-swarm.appspot.com/task?id=6226b2d5a8987c10

Applying the patch fixes the problem

**Comment by godofredoc** [comment]
Add env variable to android dep:

https://flutter-review.googlesource.com/c/recipes/+/44380

**Comment by godofredoc** [comment]
@camsim99 @gmackall to add you as reviewers you'll need to click on the CL link to get your user names added to the GoB server.

**Comment by gmackall** [comment]
Added review approving the parts I understand and a couple questions on the parts I don't, haven't reviewed changes to these recipes before!

**Comment by camsim99** [comment]
Not sure I'm a reviewer but I agree with @gmackall's review. The change looks good to me!

**Comment by zanderso** [comment]
Awesome. Thanks, everyone!

**Comment by zanderso** [comment]
Still seeing this https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/15717/overview

**Comment by gmackall** [comment]
> Still seeing this https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/15717/overview

Interesting, I confirmed with local testing on mac and windows, using the same version of gradle from the tests, that setting the `ANDROID_USER_HOME` changed where my debug signing key was getting pulled from (as expected). The test seems to still be pulling from the same `C:\Users\chrome-bot\.android\debug.keystore` as before though, indicating this variable either isn't getting set properly or isn't impacting the test for some other reason.

It is possible that we need to also set `ANDROID_SDK_HOME`. From the [earlier link](https://developer.android.com/tools/variables) about android sdk tool environment variables, 

> Some older tools, such as Android Studio 4.3 and earlier, do not read ANDROID_USER_HOME. To override the user preferences location for those older tools, set ANDROID_SDK_HOME to the parent directory you would like the .android directory to be created under.

Still trying to see if there is anything else that would be causing this.

**Comment by gmackall** [comment]
I believe this is an issue with AGP (android gradle plugin) 4.1.3, the version used for that test. Neither ANDROID_USER_HOME nor ANDROID_SDK_HOME seem to be respected by AGP 4.1.3 from my local testing.

**Comment by gmackall** [comment]
Keeping this updated as its a p1, I'm still looking into the cases where this is still failing since the merge of the change to set ANDROID_USER_HOME - particularly trying to determine if the remaining failures are cases where the version of gradle or AGP doesn't respect the environment variable, such as the case of the test using AGP 4.1.3.

If anyone runs into more recent examples of this failure please feel free to link here!

**Comment by gmackall** [comment]
This is another failure that happened since the merge of the first fix:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20Emulator%20Tests/7593/overview
It fails for the same reason, where we are trying to pull the debug signing key from `"/home/chrome-bot/.android/debug.keystore"`. However, unlike the case mentioned above, from what I can tell it is using gradle 7.0.2 and AGP 7.0.0, which don't have an issue with respecting `ANDROID_USER_HOME`.

However, from the build failure page we can see it is running [with this recipe](https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/scenarios.py;l=110?q=file:recipes%2Fengine%2Fscenarios.py), which seems to be setting its own android-related environment variables. 

This seems to be an engine test, so question for @godofredoc if you happen to know - does this engine test share the same setup as the one done in the file we already changed (api.py), in which case this is just redundant setting of environment variables, does it use entirely separate recipes and we need to make the same change that we did before here? Sorry if you're not the right person to ask about engine recipes!

**Comment by godofredoc** [comment]
Nice catch @gmackall, this test is not sharing the logic where we updated the env variable and it is not being set in this build. You can see the current env variables clicking on the execution details.

![image](https://github.com/flutter/flutter/assets/54371434/0206fd13-875d-4bbf-932d-6568c76760bb)

Let me take a quick look to see if I can refactor the recipe to use the shared logic.

**Comment by gmackall** [comment]
Update on the above engine test that is failing, from the build failure page:
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_2_3/42157/overview
Under the "input properties" we can see the dependencies, 
```
"dependencies": [
    {
      "dependency": "open_jdk",
      "version": "version:11"
    },
    {
      "dependency": "gradle_cache",
      "version": "none"
    },
    {
      "dependency": "android_virtual_device",
      "version": "31"
    },
    {
      "dependency": "goldctl",
      "version": "git_revision:3a77d0b12c697a840ca0c7705208e8622dc94603"
    }
  ],
```

Notably, the `android_sdk` that is present in the input to other recipes is missing, because this engine test uses a version of the [android sdk in the `third_party` directory in the engine repo](https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/scenarios.py;l=109?q=file:recipes%2Fengine%2Fscenarios.py). But because `android_sdk` isn't in the dependencies, when we [start the setup](https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/scenarios.py;l=116?q=file:recipes%2Fengine%2Fscenarios.py) that we changed above in api.py, we never call the modified android_sdk that sets the `ANDROID_USER_HOME` because we are [looping over the dependencies](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=104) from the input, and we aren't passing in android_sdk. 

So while some of the setup is shared, we aren't sharing the important piece of the setup that we modified, and it seems like we need to modify this engine recipe to make a temp directory that we can use for `ANDROID_USER_HOME`, and set it to that. At least that is my understanding, if anyone has better knowledge of how these recipes work and sees an issue please chime in!

**Comment by gmackall** [comment]
From the failures on https://github.com/flutter/flutter/pull/126548, it looks like we may also need to update the tests that use the [devicelab/devicelab_drone recipe too](https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone.py?q=file:recipes%2Fdevicelab%2Fdevicelab_drone.py)

**Comment by XilaiZhang** [comment]
just as FYI https://github.com/flutter/flutter/pull/126548 was run on a release branch so it might have been using a recipe version that is different from the recipe on the master branch (looks like there were a 3 line difference in [flutter/android_views](https://cs.opensource.google/search/?q=file%3Arecipes%2Fflutter%2Fandroid_views.py)

**Comment by godofredoc** [comment]
We have two different problems here. I'll send a CP to the fix in recipes, it will cover most of the flutter/flutter issues

**Comment by gmackall** [comment]
After some more testing I believe we can solve this failure in all places with only environment variable changes, which is to say I was mistaken in this past comment: 

> I believe this is an issue with AGP (android gradle plugin) 4.1.3, the version used for that test. Neither ANDROID_USER_HOME nor ANDROID_SDK_HOME seem to be respected by AGP 4.1.3 from my local testing.

The short version is that AGP 4.1.3 does in fact respect `ANDROID_SDK_HOME` (but not `ANDROID_USER_HOME`, which is what we started setting in the initial fix). The important thing is that if you are setting both of these environment variables, they need to be set in such a way that 
1. `ANDROID_SDK_HOME=<some_path>` and 
2. `ANDROID_USER_HOME=<some_path>/.android` where some_path is the same as above
or else they will be detected as in conflict.

Tested with AGP 4.1.3 and also newer versions of gradle/AGP, and with both of these environment variables set we always pull the signing keys from the proper place.

Making this change should fix failures such as this one
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/15717/overview
where we can see that the [code to modify environment variables](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=316) is getting invoked properly, while the refactoring that @godofredoc mentioned regarding how the recipes share setup logic should fix the other cases.

@godofredoc, if you are currently working on that refactoring, can you include the change to set `ANDROID_SDK_HOME` as mentioned above?

**Comment by gmackall** [comment]
Note from android triage: @godofredoc is the refactoring something you are still working on? If so no worries, but if you are too busy we can try to re-route.

**Comment by godofredoc** [comment]
I haven't had the time to do the refactoring. We can probably land the fix without the refactoring. I'll send a CL after my next meeting.

**Comment by godofredoc** [comment]
Scenarios recipe migration: https://flutter-review.googlesource.com/c/recipes/+/44735

Turns out that recipe does not need the android dependency.

**Comment by godofredoc** [comment]
Here is the fix to set the env variables consistently in the modules used by engine and framework:

https://flutter-review.googlesource.com/c/recipes/+/44782

**Comment by godofredoc** [comment]
Seems like everything has been working properly. Please reopen if we find more failures related to this issue.
