### ISSUE TITLE
Failing autoroller presubmit checks should be auto-retried one time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126556]
While the framework tree can stay open with flaky tests by retrying them up to three times, the engine -> framework roll can get very backed up when any presubmit check flakes only a single time. Additionally, the `.ci.yaml` check and the new "Pull Request Labeler" can also fail in flaky ways, which I've seen block rolls several times over the past couple days.

Given this situation, it would save the engine sheriff a lot of manual work if some automation could retry failing presubmit checks one time on autoroller PRs.

cc @ricardoamador @godofredoc

**Comment by zanderso** [comment]
> * Exponential retry logic separated in multiple places, so far we have test level auto-retries(recipes)+ scheduler level auto-retries(cocoon scheduler) + skia autoroller retries(skia autoroller service).

The recipe auto-retries are not running for many framework presubmit checks, and even if they were, they would easily hit job-level timeouts. Running one time for many tests just barely fits under timeouts.

The cocoon scheduler does not do retries on presubmit tests, AFAIK, so it's not relevant here.

The skia autoroller retries by failing an entire roll and redoing all of the presubmit checks. In practice, some other test will flake, and the roller gets very backed up.

So none of the above retry logic will solve the problem this request will solve.

> * For .ci.yaml check problems auto-retries won't help, in most cases the failure is caused by the .ci.yaml file in the roll PR getting outdated with respect to main

This is not what I see in practice. In practice, `ci.yaml` check fails and is fixed by clicking the retry link in many instances. I've shared some of these with @CaseyHillers.

> * Hiding issues rather than fixing the root causes, this approach will most likely accumulate a lot of technical debt in the medium and long terms.

Flaky tests are already caught and triaged by the flaky bot and flaky triage process. Blocking up rollers only creates additional work for the sheriff/gardner, and doesn't provide any additional visibility.

> Why not autosubmit?
> 
> * Autosubmit was designed to validate and submit PRs as fast and efficient as possible. It only knows how to read state from github, add comments to PRs and submit pending PRs.
> * Autosubmit does not know about LUCI, github actions or any of the underlying systems running builds/tests, required for triggering tests.

Fair enough. Just saw the email about the autosubmit bot, and it sounded like that's where the team was investing.

> @zanderso do you have an example roll PR where the labeler action failed to take a look?

There's a list in https://github.com/flutter/flutter/actions/workflows/labeler.yml?query=is%3Afailure. It looks like entries from that list go away when someone manually retries, and the manual retry succeeds.

**Comment by godofredoc** [comment]
> > * Exponential retry logic separated in multiple places, so far we have test level auto-retries(recipes)+ scheduler level auto-retries(cocoon scheduler) + skia autoroller retries(skia autoroller service).
> 
> The recipe auto-retries are not running for many framework presubmit checks, and even if they were, they would easily hit job-level timeouts. Running one time for many tests just barely fits under timeouts.

Adding retries at this level is preferred and more efficient, e.g. doubling the timeout and retrying once will take less time and use less resources than triggering a new build, wait for resources to be available and run to completion.

Timeouts from the infra point of view are configurable from .ci.yaml. If we are missing documentation for making the update of timeouts a self service we will be happy to add it. In addition to that we can make the retries property public in a way that test owners can configure the # of retries directly from .ci.yaml.

Also related to timeouts we have a bigger problem, most of the tests in the framework are lengthy 45+ mins, they are flaky and fixes are not scalable as they need to be applied test by test. We really need to define test/test frameworks ownership and a plan to approach the issue with something different than retries or adding capacity. Note that I'm not implying we should not apply retries as short term workaround but I'd really like to see some work to address the root causes rather than patching it.

One thing to be aware of is: adding retries, increasing timeouts may have a toll in queue time and capacity usage. 

> 
> The cocoon scheduler does not do retries on presubmit tests, AFAIK, so it's not relevant here.
> 

The functionality is there just not being used. I'll still have concerns about the additional capacity use and the potential increase in queue times but if we decide to to take the risk this is something that requires low investment.

> The skia autoroller retries by failing an entire roll and redoing all of the presubmit checks. In practice, some other test will flake, and the roller gets very backed up.

Let's reach out to the skia autoroll team, github apis have a retry failed tasks api that can potentially be called from the autoroller before closing the PR.
  
> 
> So none of the above retry logic will solve the problem this request will solve.
> 
> > * For .ci.yaml check problems auto-retries won't help, in most cases the failure is caused by the .ci.yaml file in the roll PR getting outdated with respect to main
> 
> This is not what I see in practice. In practice, `ci.yaml` check fails and is fixed by clicking the retry link in many instances. I've shared some of these with @CaseyHillers.
> 

Are these recent observations? several issues with the .ci.yaml check were fixed in the last couple of months, the remaining one is the branch update related one that I haven't seen very frequently.

> > * Hiding issues rather than fixing the root causes, this approach will most likely accumulate a lot of technical debt in the medium and long terms.
> 
> Flaky tests are already caught and triaged by the flaky bot and flaky triage process. Blocking up rollers only creates additional work for the sheriff/gardner, and doesn't provide any additional visibility.

The flakiness workflows do not cover presubmit.

> > Why not autosubmit?
> > 
> > * Autosubmit was designed to validate and submit PRs as fast and efficient as possible. It only knows how to read state from github, add comments to PRs and submit pending PRs.
> > * Autosubmit does not know about LUCI, github actions or any of the underlying systems running builds/tests, required for triggering tests.
> 
> Fair enough. Just saw the email about the autosubmit bot, and it sounded like that's where the team was investing.
> 
> > @zanderso do you have an example roll PR where the labeler action failed to take a look?
> 
> There's a list in https://github.com/flutter/flutter/actions/workflows/labeler.yml?query=is%3Afailure. It looks like entries from that list go away when someone manually retries, and the manual retry succeeds.

Thanks, will follow up with the skia autoroll team, my expectation was that cirrus, actions will be de-flaked automatically.

**Comment by erock2112** [comment]
The autoroller uses the Go client for GitHub: https://pkg.go.dev/github.com/google/go-github/v29@v29.0.3/github#Client

Creating a CL:
client.GetReference
client.CreateReference
client.CreatePullRequest
client.AddLabel

After the CL is created:
client.PullRequests.Get
client.Checks.ListCheckRunsForRef
client.Repositories.GetCombinedStatus

Generally speaking, we want the roller to be operating at a level above a "commit queue" which handles all of the checks.  We load results for the checks so that we can evaluate dry run success or failure and to present them to the user on the UI to avoid a couple of clicks.  We really don't want to involve the roller in lower-level decisions like when and how to retry individual checks.  The roller does have mechanisms for retrying the CQ completely, and if the CQ itself decides that only a subset of checks need to be re-run at that point, the roller would have no problem with it.

**Comment by keyonghan** [comment]
We can add a retry field from ci.yaml and re-use the retry logic from recipe module. At the same time we can collect the flakiness data for post-submit.

**Comment by zanderso** [comment]
An example where this would have helped: https://github.com/flutter/flutter/pull/130426

**Comment by zanderso** [comment]
Especially since issues like https://github.com/flutter/flutter/issues/132654 are nowhere near being solved. I'd really like to see this issue prioritized more highly so that the burden on the Engine sheriff can be lowered.

**Comment by zanderso** [comment]
@godofredoc Can you point me at the code where I can implement this myself?

**Comment by godofredoc** [comment]
There are multiple places, let me find the locations and I'll update the bug with the links.

**Comment by godofredoc** [comment]
The target message in the scheduler proto will need a new property. e.g max_retries:

https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/model/proto/internal/scheduler.proto;l=31

Somewhere here we need to check if the build update is a failure and retry:

https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart;l=70

Something similar to this is required to retry a build:
https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/scheduler.dart;l=467?q=rerun&ss=flutter%2Fcocoon

There are a few challenges:

* How do we get the github pull request.
* Update the initial build to include max_retries, retry_count and the check_run_id to be able to get enough information to identify the right build and enough info to update its status in the github ui.

**Comment by keyonghan** [comment]
We have been collecting the `pr/checkrun` info in the build `tags`, which could be retrieved when processing the build status. What I can think of for the `max_retries` is add it as another tag, say `attempt: <number>`, and update the to-be-scheduled `attempt` based on the last build's tag.

![Screenshot 2023-08-28 at 4 52 18 PM](https://github.com/flutter/flutter/assets/54558023/a2392a99-ff65-49a7-8722-cf6eb61b1318)

**Comment by godofredoc** [comment]
Changes to the proto file are still missing.

**Comment by godofredoc** [comment]
We are still missing the protos required for the integration.

**Comment by keyonghan** [comment]
> We are still missing the protos required for the integration.

The logic is supported via a property, so no proto change is needed.

@zanderso The [rerun logic](https://github.com/flutter/cocoon/pull/3059) is in prod now. Could you give it a try referring to the doc: [presubmit_max_attempts](https://github.com/flutter/cocoon/blob/main/CI_YAML.md#properties)? You can add this property to the potential flaky targets that may cause rolls breakage. For a one-time auto retry, set `presubmit_max_attempts: "2"`.

**Comment by keyonghan** [comment]
With https://github.com/flutter/flutter/issues/134560 fixed, the logic works as expected now.

Example: https://github.com/flutter/flutter/pull/134744/commits/2558380542afcc4624c2b94ea87e24f1abab3ce4
First failure: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_test/33240/overview
Second auto retry: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_test/33241/overview
<img width="545" alt="Screenshot 2023-09-14 at 9 22 52 AM" src="https://github.com/flutter/flutter/assets/54558023/bd2b8ccd-36ca-4364-aa17-f63a2e3173a5">

**Comment by godofredoc** [comment]
@keyonghan the backend was having an extremely high 500 error rate yesterday night, was that fixed?

The error was caused by an exception when processing user_data on retries.

**Comment by keyonghan** [comment]
> @keyonghan the backend was having an extremely high 500 error rate yesterday night, was that fixed?
> 
> The error was caused by an exception when processing user_data on retries.

I believe it's https://github.com/flutter/flutter/issues/134560, which has been resolved in today's new deployment. I do not see any 500 from presubmit-luci-subscription.

**Comment by zanderso** [comment]
This appears to be working: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_canvaskit_tests_1/36817/overview

Thanks!
