### ISSUE TITLE
Network resources (the doctor check crashed)

### ISSUE THREAD

**Issue by Muddassar087** [flutter/flutter#126800]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter upgrade to 3.10.0

flutter doctor

### Actual results

<img width="1310" alt="Screenshot 2023-05-15 at 10 27 46 AM" src="https://github.com/flutter/flutter/assets/69845990/bf1af4f4-734d-4402-9cf1-3ce589ec1005">

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
This issue seems related to your network, please ensure you have a working internet connection.
There is a checklist you can use for this:

- [ ]  Is the network stable and fast?
- [ ]  Do you use any proxy server?
- [ ]  It may be useful for troubleshooting the issue: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall
