### ISSUE TITLE
"Polyfill" AV1 Decoding Support across platforms

### ISSUE THREAD

**Issue by zacharypuulsedev** [flutter/flutter#126858]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case - Video Decoding (video_player)
Facilitate convenient use of modern video codecs (AV1) in flutter applications. Video playback is a cornerstone of many mobile/web applications. Given the ever increasing demands of video storage, transmission, and quality, having a high-performance codec that is unified across platforms enables back-end infrastructure to optimize towards AV1. (More in background below)

Having universal flutter video playback of this codec would allow optimizing video content to AV1 on the server for all clients.  

This implementation seems like a parallel effort to implementation of AVIF for image decoding. [Flutter Avif Support](https://github.com/flutter/flutter/issues/61229)

#### Background
AV1 by Open Media, is an excellent modern codec that offers industry-leading performance **without royalties/licensing issues**. (Open Media (AOMedia), whose members include Amazon, AMD, Apple, Cisco, Google, Hulu, IBM, LG, Meta, Microsoft, Netflix, Nvidia, Intel, IBM, Samsung, and many other leading players.). Vp9 support is hindered by Apple, and AV1 shows bitrate reductions of 30%-40% compared to HEVC/H.265 and 60%-70% relative to AVC/H.264.

 This format is highly desirable for encoding, storing, and transmitting video data; especially in cases of low bandwidth (important in developing and rural regions with worse connectivity or when dealing with massive amounts of data). 

#### Alternatives (Not Great)
- Vp9 (poor support on Apple devices; iOS Safari/iOS)
- H.265 (royalties/licenses - relevant for server processing; significantly larger file size - see above)

##### Web
On web, video playback is limited to codecs supported by browsers, which means this currently omits Safari (iOS & macOS). 
- https://pub.dev/packages/video_player
- https://pub.dev/packages/video_player_web
https://caniuse.com/#feat=av1
<img width="796" alt="image" src="https://github.com/flutter/flutter/assets/123405522/318b2e0c-fbaf-4f81-9837-02c623639845">
 
##### iOS
Not supported natively.
 
##### Android
Video decoding is provided by ExoPlayer, which can leverage [3rd party codecs](https://developer.android.com/guide/topics/media/exoplayer/supported-formats) if included by applications.

Support is varied, with binaries potentially needing to ship the codec on anything less than Android 14. 
Android 10+ | [The decoder is optional.](
https://developer.android.com/guide/topics/media/media-formats#core)

Related:
(Flutter Avif Support)[https://github.com/flutter/flutter/issues/61229]

References:
- https://bitmovin.com/av1-playback-support/
- https://videocardz.com/newz/apple-safari-16-4-beta-browser-gets-av1-codec-support
- https://github.com/GoogleChromeLabs/wasm-av1/tree/master
- https://www.red5pro.com/blog/av1-webrtc-streaming/

### Proposal
Introduce support for AV1 decoding in flutter across both mobile and web platforms; eventually all platforms. Currently, bundling support for AV1 seems most difficult for a user in the web, whereas on mobile or desktop, bundling native code is significantly easier, albeit still an arduous task.

##### Web
As recently as Safari 16.4 beta, initial support is in the works. In the case of Safari, consider compiling `libaom` to a wasm module as part of migrating flutter web to wasm.
 
 ##### Android
- Android 10+<14 - Include the av1 codec so exoplayer is capable of playback on Android 10 and up. 
- Android <10 - consider compiling `libaom` into the video_player plugin as a video decoder. This is likely relevant for the next 2..4 years as low-cost devices don't release on the latest Android versions.

 ##### iOS
 - iOS - consider compiling `libaom` into the video_player plugin as a video decoder. This is likely relevant for the next ~3...4y (depending on when Apple actually releases support).

Alternatives:
Opt-in to this feature could be used to prevent unnecessary bundle size increase, if tree-shaking cannot determine if the codec is required.

References:
- https://aomedia.googlesource.com/aom/

**Comment by stuartmorgan** [comment]
> Introduce support for AV1 in flutter

In what context, exactly? It's not clear how a codec support request applies to Flutter.

**Comment by stuartmorgan** [comment]
In the future, it would be helpful to reply to questions in comments; nobody gets notifications when you just edit previous posts.

Responding to the updated version:

> Use case - Video Decoding (video_player)

As a general framework for my comments below: the goal of `video_player` is not to solve all possible video use cases, it's to provide Flutter developers access to the underlying video playback support present in the platforms. In cases where the system-provided support is not well suited to a developer's needs, the solution is going to be a third-party library, just as it would be for a non-Flutter developer.

And because `video_player` uses the federated plugin design, anyone can build alternate implementations for specific platforms, ship them separately, and allow clients to opt into using them with the `video_player` API surface, so it doesn't even require clients to change their code.

> In the case of Safari, consider compiling `libaom` to a wasm module as part of migrating flutter web to wasm.

It is not clear to me what you are proposing here in practice; what would this module do? Flutter for web has no mechanism for rendering video from scratch, it uses `<video>`.

If there is a method for injecting codec support into `<video>` via wasm modules, then you can do that separately and `video_player_web` should just work; if not, then we can't do it either. If you are proposing writing a custom video pipeline from scratch that's not `<video>`-based, someone could certainly do that and release it as an alternate web implementation package, but it would be entirely different than the current implementation, and thus makes far more sense as a different package.

> * Android 10+<14 - Include the av1 codec so exoplayer is capable of playback on Android 10 and up.

Shipping ExoPlayer extension codecs is out of scope for `video_player`; it substantially complicates distribution, as well as the build process for plugin clients. Someone could certainly publish a fork that includes it if supporting a specific new codec on old Android devices is an important use case for them.

> * Android <10 - consider compiling `libaom` into the video_player plugin as a video decoder.

How? The comments for web apply here as well; if you are suggesting a completely different implementation of `video_player` that doesn't use ExoPlayer at all, then there is no overlap with what `video_player_android` currently is at all, and should definitely be a different package.

> * iOS - consider compiling `libaom` into the video_player plugin as a video decoder.

How? `AVPlayer` does not allow pluggable code support as far as I am aware; see comments above.

> Opt-in to this feature could be used to prevent unnecessary bundle size increase

How? What mechanism, other than it being a separate plugin, would allow for opt-in by plugin clients?

> if tree-shaking cannot determine if the codec is required.

Tree-shaking is a Dart feature, and thus not applicable to native code.

If someone wants to write a plugin for video playback that wraps libaom, they are certainly welcome to do so, just as others have done with `libvlc`. And if they want to make it conform to `video_player_platform_interface`, or if some other developers want to make adapters that do so, such that the plugin could be used as an alternate backend with the `video_player` plugin, they are again welcome to do so. That's not something that the Flutter team will be taking on however, so closing as out of scope.

**Comment by zacharypuulsedev** [comment]
@stuartmorgan 
Thank-you for the additional context on the difficulty of implementing this feature. While desirable for unifying codec support and optimizing size, practically, it seems like using just this format is a few years away.

For Posterity - Video Decoding Codecs on Flutter 
==

Option 1 - AV1
It seems like a custom `video_player_platform_interface` that wraps `libaom` is the most ideal way of bringing in a consistent, albeit software rendered, AV1 playback experience. However supporting this on mobile and especially web is going to be too much of an endeavour for our relatively small team to accomplish.

Option 2 - Multiple Codecs 
Transcode media to multiple formats (H.265 & AV1) 

Apple (iOS/Safari)-> H.265
Chrome/Firefox -> AV1 or Vp9

Android 4.4+ -> Vp9
Android 5.0+ -> H.265
Android 14.0+ -> AV1

Option 3 - Use H.264 
It might be 19 years old, but at least it should be supported everywhere.
