### ISSUE TITLE
 White Container Appears at the Bottom of the Screen on Flutter Master - google_maps_flutter 2.2.6

### ISSUE THREAD

**Issue by Alecia1997** [flutter/flutter#126912]
**Issue Description:**
After updating to google_maps_flutter version 2.2.6 and running the application on Flutter Master, a white container unexpectedly appears at the bottom of the screen when using the Google Maps widget. This container covers a portion of the map and disrupts the intended user interface.

**Reproduction Steps:**
To replicate the issue, follow these steps:

Update google_maps_flutter dependency to version 2.2.6 in the pubspec.yaml file.
Ensure you are running the latest Flutter Master branch.
Build and run the application on a device or emulator.

**Expected Behavior:**
The Google Maps widget should be displayed without any additional white containers at the bottom of the screen. The map should cover the entire visible area, and the user interface elements should not be obscured.

**Actual Behavior:**
Upon running the application, a white container appears at the bottom of the screen, covering a portion of the map. This container disrupts the user interface and reduces the visibility and usability of the map widget.

**Comment by huycozy** [comment]
Hi @Alecia1997 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!
