### ISSUE TITLE
[Pigeon] Add the ability to specify Message Channel name prefix

### ISSUE THREAD

**Issue by danijel-tolj** [flutter/flutter#127022]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

@gaaclarke  Currently the message channel prefix is hardcoded to `dev.flutter.pigeon` in 

[](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/generator_tools.dart)

However, it would be nice if there was a `messageChannelPrefix' parameter` we could pass into `PigeonOptions` for consistency sake.

Thanks in advance.

### Proposal

Add a parameter `messageChannelPrefix` to PigeonOptions instead of having to use hardcoded  `dev.flutter.pigeon` prefix that is hardcoded in the generator_tools.dart

**Comment by stuartmorgan** [comment]
> For example, if I want to log all of the message channel calls in tests and validate the output

Why would you want to write your tests in such a way that they would all break if internal details of Pigeon's communication system changed? Client code should be tested against the API surface (e.g., with a mock of the generated API), not against Pigeon implementation details.

> or override certain BasicMessageChannels

In what scenario would you be overriding internals of Pigeon?

**Comment by danijel-tolj** [comment]
Can't think of a specific scenario off the top of my head but not to make it TLDR, I would prefer having the ability to specify message channel, to me it seems like a convenient option to have.  

If you don't agree I can understand that and we can close this thread

**Comment by stuartmorgan** [comment]
> Can't think of a specific scenario off the top of my head but not to make it TLDR, I would prefer having the ability to specify message channel, to me it seems like a convenient option to have.

The specifics are important to evaluating a proposal. For instance, the one specific use case you've described above is an anti-pattern (making tests rely on the internals of code outside of your control), and adding complexity to *encourage* anti-patterns is definitely not something we would do.

> If you don't agree I can understand that and we can close this thread

We can't fully evaluate it to agree or disagree without specifics. If the example above is the only use case, then we would close this, but it's possible there are use cases you haven't presented yet that would result in a different decision.

**Comment by danijel-tolj** [comment]
Okay @stuartmorgan here are a couple of examples.

- At our project we use a lot of analytics, with lots of predefined filters including message channel names. Migrating to pigeons would make it very tedious to edit the prefixes to match the new message channel names.

- All of the native plugins we have written are documented in detail, including their respective message channel names. We would also have to make sure all of them are properly renamed in documentation. 

-Third use case, which is the most serious one is an objective possibility that there will be a conflict between the dependencies that use pigeons and native plugins written in the project itself.
For example, if I have my own ImagePicker plugin which uses pigeons, and want to slowly migrate to the flutter.dev `image_picker` plugin, there is a possibility that `HostApi` or `FlutterApi` classes will have same signatures and methods, and that will crash the app because of the conflict. For this I created an example using `ImagePickerApi` and `pickImages` method to demonstrate the possibility of creating a conflict which could easily be avoided by having the ability to specify a channel name prefix.
Steps to reproduce are in the README.md 

https://github.com/danijel-tolj/flutter_pigeons_conflict

**Comment by stuartmorgan** [comment]
> * At our project we use a lot of analytics, with lots of predefined filters including message channel names. Migrating to pigeons would make it very tedious to edit the prefixes to match the new message channel names.

I'm not clear on how channel names are part of your metrics (are you intercepting every message at the service layer?), but regardless: do you really want important metrics bound to internal implementation details of a package you don't control? What is your plan for if Pigeon fundamentally changes the way channels are named in the future? Or even structured (e.g., if it moved to something more like method channels, with fewer individual channels)?

If you have so many channels that changing this once would be hard, why would you want to create a structure where you could have to continue to change it again any time Pigeon internals changed?

> * All of the native plugins we have written are documented in detail, including their respective message channel names. We would also have to make sure all of them are properly renamed in documentation.

See above. If you are going to document the internals in detail, including the internals of Pigeon—which you don't control—then what is your plan long term for maintaining this documentation across changes to Pigeon? And as above: do you really want to tightly bind your own docs to the internal implementation details of a package you don't control? To what end?

> -Third use case, which is the most serious one is an objective possibility that there will be a conflict between the dependencies that use pigeons and native plugins written in the project itself. For example, if I have my own ImagePicker plugin which uses pigeons, and want to slowly migrate to the flutter.dev `image_picker` plugin, there is a possibility that `HostApi` or `FlutterApi` classes will have same signatures and methods, and that will crash the app because of the conflict. For this I created an example using `ImagePickerApi` and `pickImages` method to demonstrate the possibility of creating a conflict which could easily be avoided by having the ability to specify a channel name prefix.

This is definitely an issue, thanks for flagging it. Rather than requiring every single Pigeon client to opt into a solution (and know that they need to do so in the first place), we should just change the channel name generation. I've filed https://github.com/flutter/flutter/issues/127106 for that.

(Illustrating, in fact, the fact that this naming is an internal implementation detail that can change at any time.)
