### ISSUE TITLE
ci_yaml autoroller should not be backfilled

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#127063]
The Linux ci_yaml flutter_roller target on the framework (and probably other repos too) is not guaranteed to run in the order commits appear in the tree, and will be backfilled. This can cause older commits to overwrite the build config of newer commits, leading to hard to debug one-off build failures.

We should either avoid backfilling, or even better, ensure we never push an older config over a newer one.

**Comment by keyonghan** [comment]
Actually I guess we should do both. Avoiding backfilling makes sure we always run newer commits. Rebase to TOT guarantees always rolling latest config (related issue: https://github.com/flutter/flutter/issues/112127)

**Comment by CaseyHillers** [comment]
FYI it seems like backfilling is disabled, but we don't run new builds. My expectation in the chart below is the top should be green.

Instead of backfilling, we want a greedy policy where we always run the tip of tree (whenever nothing else is running)

![image](https://github.com/flutter/flutter/assets/2148558/6f5dbfc0-8f8a-4d96-8628-b5af632d9cd7)

**Comment by ricardoamador** [comment]
@CaseyHillers That is a good point which we have outlined here: https://github.com/flutter/flutter/issues/131501#issuecomment-1665946645. This issue is specifically for the backfill and the issue you mentioned is already tracked here: https://github.com/flutter/flutter/issues/112127.
