### ISSUE TITLE
[go_router_builder] Add go_router StatefulShellRoute support to go_router_builder

### ISSUE THREAD

**Issue by hawkkiller** [flutter/flutter#127371]
go_router_builder should support the StatefulShellRoute and StatefulShellBranch APIs from v7.1

**Comment by hawkkiller** [comment]
@chunhtai

**Comment by roscadalexandru** [comment]
I don't get the routes generated and I am not sure if I actually did something wrong or it is because it basically doesn't work. This is the code I've written

`part of 'router.dart';

@TypedStatefulShellRoute<HomeShellRoute>(
  branches: [
    TypedStatefulShellBranch<HomeBranch>(
      routes: <TypedGoRoute<GoRouteData>>[
        TypedGoRoute<HomeRoute>(path: '/home', name: 'home', routes: [
          TypedGoRoute<ApplicationsRoute>(
              path: '/applications', name: 'applications'),
        ]),
      ],
    ),
    TypedStatefulShellBranch<SettingsBranch>(
      routes: <TypedGoRoute<GoRouteData>>[
        TypedGoRoute<SettingsRoute>(
          path: '/settings',
        ),
      ],
    ),
  ],
)
class HomeShellRoute extends StatefulShellRouteData {
  const HomeShellRoute();

  static final GlobalKey<NavigatorState> $navigatorKey =
      SenoRouter.shellNavigatorKey;

  @override
  Widget builder(BuildContext context, GoRouterState state,
      StatefulNavigationShell navigationShell) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Nested Home'),
      ),
      body: navigationShell,
    );
  }
}

class HomeBranch extends StatefulShellBranchData {
  const HomeBranch();

  static final GlobalKey<NavigatorState> $navigatorKey =
      SenoRouter.shellNavigatorKey;
}

class SettingsBranch extends StatefulShellBranchData {
  const SettingsBranch();

  static final GlobalKey<NavigatorState> $navigatorKey =
      SenoRouter.shellNavigatorKey;
}

class HomeRoute extends GoRouteData {
  const HomeRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) => Container(
        alignment: Alignment.center,
        child: const Text('Home'),
      );
}

class SettingsRoute extends GoRouteData {
  const SettingsRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) => Container(
        alignment: Alignment.center,
        child: const Text('Settings'),
      );
}

class ApplicationsRoute extends GoRouteData {
  const ApplicationsRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) => Container(
        alignment: Alignment.center,
        child: const Text('Applications'),
      );
}
`

**Comment by hangyujin** [comment]
Hi Ales, @roscadalexandru  
please wait for this PR to merge: https://github.com/flutter/packages/pull/4238
