### ISSUE TITLE
* Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 3m 1s Exception: Gradle task assembleDebug failed with exit code 1 Exited (sigterm)

### ISSUE THREAD

**Issue by ahadameen** [flutter/flutter#127311]

**Comment by huycozy** [comment]
Hi @ahadameen 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly. (See [Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) template)

Closing this issue, since no information has been provided.
