### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lessikal** [flutter/flutter#127437]
'package:flutter/src/painting/gradient.dart': Failed assertion: line 173 pos 15: 'colors != null': is not true.

**Comment by huycozy** [comment]
Hi @Lessikal 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
