### ISSUE TITLE
[camera] CameraX unit tests are flaky

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#127661]
I've seen this flake several times; it's not clear from the logs what exactly is failing, or why. Example failing run:
https://api.cirrus-ci.com/v1/task/4968839016873984/logs/unit_test.log

Enabling `unawaited_futures` for this package might turn up something in a test that's not being awaited, as that's been a source of unit test flake in the past.

/cc @camsim99

**Comment by camsim99** [comment]
Ah this should be due to not mocking the `InstanceManager` in tests. That run indicates that it is not done in [`image_capture_test.dart`](https://github.com/flutter/packages/blob/main/packages/camera/camera_android_camerax/test/image_capture_test.dart), so I can put out a PR to fix this one, but should be the case for any more errors we see like this, too.

**Comment by camsim99** [comment]
On second thought, I will go through and add it where it is missing in the PR linked above in an attempt to fix this issue completely.
