### ISSUE TITLE
Xcode Archive builds should automatically build in release mode

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12774]
As of #12773, running Archive from Xcode will exit immediately with a useful error message if `flutter build ios --release` hasn't been executed. When building Archive releases from Xcode, we should automatically build in release mode.

This requires at least the following:
1. Update `Generated.xcconfig` to a release mode build.
1. Run `pod install` to update the `Podfile.lock` to use the release-mode framework

Ideally, Xcode builds wouldn't rely on Generated.xcconfig for build-mode related settings, but would determine build mode from Xcode's own Debug vs Release configuration.

**Comment by iapicca** [comment]
Hi @cbracken is this issue still meant to be open?

**Comment by jmagman** [comment]
I think this was fixed with a combination of https://github.com/flutter/flutter/pull/23387 and https://github.com/flutter/flutter/pull/42029.  The build configuration from Xcode is used to decide what build_mode to use, and that version of the engine is re-copied in, regardless of whether you ran `flutter build ios --release` on the command line.

However I think it's nice to keep that message in xcode_backend in case we ever regress this logic.

Can we close this, @cbracken?

**Comment by cbracken** [comment]
Sounds closeable (and agreed on keeping the message in just in case).
