### ISSUE TITLE
Unable to adjust the color for "Cancel" and "Ok" button in datePicker dialog

### ISSUE THREAD

**Issue by muhammadmateen027** [flutter/flutter#127739]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have default date picker and I can see, there are number of params I can pass but there is an issue related to the color scheme for "Ok" and "Cancel" button.
I can't see anywhere to pass the button theme. Always it is taking the same style that have been provided for default TextButton. 
For example, I am changing the theme for TextButton, and would like to have a different color for both buttons in DatePicker, I am not able to do that because it is using the same theme from TextButton. 

<img width="375" alt="image" src="https://github.com/flutter/flutter/assets/24449076/5b1ea6d5-2183-4d2a-85f8-ecfe000ef403">

In below example:  if I am changing the theme for TextButton, I can see the buttons looks quite weird. 

```dart
import 'package:flutter/material.dart';
void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        textButtonTheme: TextButtonThemeData(
          style: ButtonStyle(
            backgroundColor: MaterialStateProperty.resolveWith((states) => Colors.red)
          )
        ),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() {
    showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1995),
      lastDate: DateTime(2050),
    );
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'DatePicker',
        child: const Icon(Icons.date_range_rounded),
      ),
    );
  }
}
```

<img width="372" alt="image" src="https://github.com/flutter/flutter/assets/24449076/6bc3994b-b2e5-4059-8a3a-6d76b25a38f5">

it totally looks weird. 

### Proposal

I would like to propose and contribute(Open a pull request) in improving the theme for datePicker and here are 2 approaches:

1. Provide the separate color material property in `DatePickerThemeData`, where user can adjust the theme for the dialog's action buttons
2. Where user can pass the `cancelText` in `Future<DateTime?> showDatePicker();`, user should be allowed to pass the respective color for text and background

**Comment by bernaferrari** [comment]
@TahaTesser might be able to help, he knows everything about date picker

**Comment by TahaTesser** [comment]
Hi @muhammadmateen027 
This looks like a valid issue however your proposals would more properties to `DatePickerThemeData` and be inconsistent with how nested components are themed in the framework. 

Some widget themes are a `InheritedTheme`, instead of `InheritedWidget`. This allows capturing themes from previous route to the next route e.g new page or a dialog. `InheritedTheme.capture` or `InheritedTheme.captureAll` are used to capture themes from the widgets in a new route then `InheritedTheme.wrap` is used to pass captured themes to a particular widget. 

For instance, it'll be quite to pass local theme to a new page, using `InheritedTheme` you can pass all the local themes from page one to the next pages. Likewise, widget likes popup and menu bar uses captured themes to style scrollbar for instance or any other widget.

You can see `DatePickerTheme` is a already a `InheritedTheme`. 
https://github.com/flutter/flutter/blob/9cd3d0d9ff05768afa249e036acc66e8abe93bff/packages/flutter/lib/src/material/date_picker_theme.dart#L527

Instead of using global `ThemeData.textButtonTheme` to customise date picker text buttons aka action buttons. We should be able be to wrap `TextButtonTheme` to the widget opens date picker, in your FAB. However this is not currently working since the date picker doesn't used captured themes.

To fix this you will need to look into how `PopupMenu` and `MenuBar` currently use captured themes to customise its nested widget like scrollbar and implement the same in the `date_picker.dart`. 

Here is an example where a local `ScrollbarTheme` is inherited by `PopupMenu` and `MenuBar` and I also added `DatePicker` to showcase this problem. 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

enum SampleItem { itemOne, itemTwo, itemThree }

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        scrollbarTheme: const ScrollbarThemeData(
          thumbColor: MaterialStatePropertyAll<Color?>(Colors.red),
        ),
        textButtonTheme: const TextButtonThemeData(
          style: ButtonStyle(
            backgroundColor: MaterialStatePropertyAll<Color?>(Colors.red),
          ),
        ),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Nested component themes sample'),
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            const SizedBox(height: 20),
            ScrollbarTheme(
              data: const ScrollbarThemeData(
                thumbColor: MaterialStatePropertyAll<Color?>(Colors.green),
              ),
              child: MenuBar(
                children: <Widget>[
                  SubmenuButton(
                    menuStyle: const MenuStyle(
                      maximumSize: MaterialStatePropertyAll<Size?>(
                        Size.fromHeight(
                          600,
                        ),
                      ),
                    ),
                    menuChildren: <Widget>[
                      for (int i = 0; i < 10; i++)
                        MenuItemButton(
                          style: const ButtonStyle(
                            minimumSize: MaterialStatePropertyAll<Size>(
                                Size.fromHeight(200)),
                          ),
                          onPressed: () => print('pressed item $i'),
                          child: Text(
                            'MenuBar Item $i',
                          ),
                        ),
                    ],
                    child: const Text(
                      'MenuBar',
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            ScrollbarTheme(
              data: const ScrollbarThemeData(
                thumbColor: MaterialStatePropertyAll<Color?>(Colors.green),
              ),
              child: PopupMenuButton<SampleItem>(
                child: const Text('Show PopupMenu'),
                onSelected: (SampleItem item) {},
                itemBuilder: (BuildContext context) =>
                    <PopupMenuEntry<SampleItem>>[
                  for (int i = 0; i < 10; i++)
                    PopupMenuItem<SampleItem>(
                      height: 200,
                      value: SampleItem.itemOne,
                      child: Text('Popup Item $i'),
                    ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            TextButtonTheme(
              data: const TextButtonThemeData(
                style: ButtonStyle(
                  backgroundColor: MaterialStatePropertyAll<Color?>(Colors.green),
                ),
              ),
              child: FilledButton(
                onPressed: () {
                  showDatePicker(
                    context: context,
                    initialDate: DateTime.now(),
                    firstDate: DateTime(1995),
                    lastDate: DateTime(2050),
                  );
                },
                child: const Text('Date Picker'),
              ),
            ),
          ],
        ),
      ),
      bottomSheet: BottomAppBar(
          child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          // RichText Widget with "Expected Results:" in black and "Green Scrollbar" in green.
          RichText(
            text: const TextSpan(
              text: 'Expected Results: ',
              style: TextStyle(color: Colors.black),
              children: <TextSpan>[
                TextSpan(
                  text: 'Green',
                  style: TextStyle(color: Colors.green),
                ),
              ],
            ),
          ),
          // RichText Widget with "Expected Results:" in black and "Red Scrollbar" in red.
          RichText(
            text: const TextSpan(
              text: 'Actual Results: ',
              style: TextStyle(color: Colors.black),
              children: <TextSpan>[
                TextSpan(
                  text: 'Red',
                  style: TextStyle(color: Colors.red),
                ),
              ],
            ),
          ),
        ],
      )),
    );
  }
}
``` 
	
</details>


If it is too complicated for you, let me know.

**Comment by rydmike** [comment]
@TahaTesser and @bernaferrari, while this works, it forces you to wrap widgets with a local `Theme` that is different from the overall ambient app theme.

To me, the entire point with theming, is to be able to define a global theme for your app and not have to touch widget styling any further in your app, unless it needs a one off different style.

Wrapping a part of the widget tree, with a `Theme` where certain UI components gets another theme, just to be able to style it to match the global desired style, is a bit of kludge and workaround for a deficiency in component (UI widget) theming and (component property) styling.

I agree with @muhammadmateen027, this is a another theming and styling feature gap in the `DatePicker`. 

If you are making a one off styled version of component, that needs to be different (for whatever reasons) from your already globally themed styled in your app, then this pattern is correct and should be used, otherwise it is just a kludge. If I have 10 date pickers in my app, I need to do this for every one of them. Naturally I would then create a wrapper widget that does it, but still a kludge to fix a feature gap, and it is not true theming in my book.

This said, `DatePicker` is not the only case that suffers from similar theming feature gaps. We still have many variant widgets that cannot be themed without breaking their style and not being able to customize them, like eg these:

- https://github.com/flutter/flutter/issues/123829
- https://github.com/flutter/flutter/issues/118063
- https://github.com/flutter/flutter/issues/107946
- https://github.com/flutter/flutter/issues/108539
- https://github.com/flutter/flutter/issues/115827

**Comment by TahaTesser** [comment]
> @TahaTesser and @bernaferrari, while this works, it forces you to wrap widgets with a local Theme that is different from the overall ambient app theme.

Widgets like popup menu and date picker are much fewer than regular widget like buttons or chips 
You can also use re-use a widget a with local theme. I think using local theme for such widgets is cleaner than adding more properties to style nested widgets to an already big date picker theme.

IMO variant themes is a bit different than styling nested widgets like TextButtons in a date picker or a dialog or scrollbar in a popup menu. More complex widgets we get, that use other widgets inside them, global theming for every nested widget would get more complex and verbose.  Local themes are nice way to style such complex widgets instead of making global theme bigger and cover styling nested widgets in each of them.

Solution I suggested https://github.com/flutter/flutter/issues/127739#issuecomment-1566802619 just uses the already `InheritedTheme` type `DatePickerTheme`.  Without adding more properties to style nested widgets to date picker theme.

With that being said, i also understand  the appeal to style entire app from global themes.

**Comment by rydmike** [comment]
Yes @TahaTesser, the solution is fine as quick fix workaround.

However, as soon as you are forced to wrap built-in components with local themes (be it a component theme or `Theme`) to get them to follow a desired global style, you end up in a mixed bag situation. Which then makes you contemplate that maybe I should not theme my app at all, since I cannot do it with a global theme anyway. 

Enough such cases will trigger walking the path of building custom wrappers to style needed components, based on whatever way you come up with to control that (colors might still be global theme/extension derived).

This is sadly a very common approach for "custom" design languages in used by dev shops and teams. Sometimes because of theming limitations, and sometimes because they have not even bothered to try to reach their design goals via theming.

I have written about why these kind of wrappers are also a bad idea. Yes it works, but it requires that everybody working on the app knows about them and knows when to use those wrappers in a project using a "custom design language", based on custom styled wrappers. You can no longer just drop in SDK widgets and get the desired themed design.

Local theme wrapping for the global style, kind of defeats the purpose of having a theme.

---

Yes the linked variant issues are a bit different, but it is another example of where you need wrappers to be able to style them, because their theming breaks down their intended styling. In some cases you can get away with using widget properties, but you would probably make "styled" wrappers anyway for convenience.

**Comment by TahaTesser** [comment]
Hi everyone!

Turns out `showDatePicker` (and `showTiemPicker`) already support `Inherited.wrap` but the local theme didn't work because of the context. You can use either of these functions in a `Builder` and a local theme to customize `TextButton`s.

This is applicable to any other widgets that push to a new route like `PopUpMenuButton`. As explained in https://github.com/flutter/flutter/issues/127739#issuecomment-1566802619

### Here you can see I CAN  adjust the colors of the `Cancel` and `Ok` buttons in the date picker dialog. 

| Preview | 
| --------------- | 
| <img src="https://github.com/flutter/flutter/assets/48603081/f92b5d09-f477-44cb-80a3-fee832ecb15e" height="450" />	|




### Code sample

<details> 
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Center(
        child: TextButtonTheme(
          data: TextButtonThemeData(
            style: TextButton.styleFrom(
              foregroundColor: Colors.amber[700],
              textStyle: const TextStyle(
                fontWeight: FontWeight.bold,
                fontStyle: FontStyle.italic,
              ),
            ),
          ),
          child: Builder(builder: (BuildContext context) {
            return FilledButton(
              onPressed: () async {
                final Future<DateTime?> selectedDate = showDatePicker(
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime(2018),
                  lastDate: DateTime(2030),
                );

                print(selectedDate);
              },
              child: const Text('Open DatePicker'),
            );
          }),
        ),
      ),
    );
  }
}

``` 
	
</details>

This should solve this issue and you can customize the both `Cancel` and `Ok` buttons just for the date picker.


Coming to the discussion in https://github.com/flutter/flutter/issues/127739#issuecomment-1568286467, this proposal will need a separate issue as it applies to multiple widgets and is wider in scope. Not effects this issue as it is solved in the code sample above.

**Comment by TahaTesser** [comment]
I just found action style properties exist in the time picker theme but they were not working so i fixed them in https://github.com/flutter/flutter/pull/132843
I think it's reasonable to add them to the date picker theme for consistency and easy of use.

I also plan to fix [InheritedTheme](https://github.com/flutter/flutter/issues/127739#issuecomment-1566802619) issues in a separate issue in the coming weeks.
