### ISSUE TITLE
Flutter new update text field cause issue 

### ISSUE THREAD

**Issue by abdullahjavaid09** [flutter/flutter#127735]
https://github.com/flutter/flutter/assets/113422445/ba1a98a7-f09e-459f-adaa-9cb6cb1e1beb

also i used bottom inset true

**Comment by huycozy** [comment]
Hi @abdullahjavaid09 
When opening an issue, please try to provide all or some of the information indicated in the [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) so that we can address this issue properly.

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) which doesn't contain usage of 3rd party plugins/packages.
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
