### ISSUE TITLE
Pageview with expand effect

### ISSUE THREAD

**Issue by egler321** [flutter/flutter#127806]
I would like to know if it is possible to do something similar to what is done in this video using flutter and pageview (or another widget), when you click on the item the page expands.

https://github.com/flutter/flutter/assets/19750616/e0cdcd4a-e586-4679-8b39-e3a4d141daf9

**Comment by huycozy** [comment]
Hi @egler321 
The goal of this Github repo is not to give assistance on personal code/implementation but to improve Flutter framework reporting bugs or feature requests.

Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Closing as this isn't Flutter issue itself. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. Thanks!
