### ISSUE TITLE
Consider enabling `crossOriginIsolated` in `flutter run`

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#127902]
We may want to consider some way to serve the app's HTML with `Cross-Origin-Opener-Policy: same-origin` and `Cross-Origin-Embedder-Policy: require-corp` to enable `crossOriginIsolated`. Since this could potentially break clients, we at least need an opt-out, or perhaps it should be opt-in, or based on your configuration. We will at least need this for skwasm, since it depends on a `crossOriginIsolated` browser context to use multi-threaded wasm.

**Comment by aran** [comment]
This would be great.

Currently, tools such as https://github.com/fzyzcjy/flutter_rust_bridge/ provide their own web servers to allow development while interoperating with wasm files. These tools require sacrificing debugging, hot reload and the other nice features of `flutter run`.

I tested a simple case with https://github.com/aran/automerge-flutter/blob/main/flutters/web/cross_origin_proxy.dart — the three headers in that file are sufficient to have a basic flutter app work at least in release mode. Flutter's built-in Google CDNs already transmit the right headers so that nothing breaks.

`Since this could potentially break clients`—what failure modes are possible and how would they appear? 

1. An app would break in development if it had loose usage of cross-site resources, and those resources did not provide modern headers for cross-site usage. This would show up in the developer console.
2. An app could work in 'flutter run' but stop working in production if it depended on the headers but was served from a vanilla CDN/nginx/storage bucket 

Is there anything else?

**Comment by kevmoo** [comment]
We did this, for `flutter run --wasm`, right @eyebrowsoffire ?

**Comment by eyebrowsoffire** [comment]
Yes. I think we can close this.
