### ISSUE TITLE
Drop IconThemeData since it is essentially an elaborate boolean

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1279]
Right now IconThemeData does nothing but wrap an IconThemeColor which is a two-value enum.

cc @collinjackson who I think originally designed this - do you recall what else you'd planned to put in it?

**Comment by Hixie** [comment]
Even better would be to make it accept arbitrary colors, and to make `Icon` use a color filter if necessary but use the prebuilt icons for black and white.

**Comment by collinjackson** [comment]
I'm not particularly attached to the current design. I was trying to make it consistent with Theme so that developers who were familiar with that class would find it more familiar, but that's a pretty weak reason, and since we can't seem to think of anything else to put there I would support removing it.
