### ISSUE TITLE
Scrollable Widget

### ISSUE THREAD

**Issue by KattlerJoe** [flutter/flutter#128041]
Got the custom scroll view example from flutter website.
Played a little bit and (maybe) found a bug. 

When I comment Silverlist (Top) out, everything works. But when I try to do it the other way round, the app crashes with an internal error. 

Error:
>
![grafik](https://github.com/flutter/flutter/assets/55744793/f92a49d4-2bc5-4658-a1db-be9802481c72)

> 
![grafik](https://github.com/flutter/flutter/assets/55744793/c8d54182-2a86-4994-878c-92d97d926d92)
>
![grafik](https://github.com/flutter/flutter/assets/55744793/a5a71e4d-a42f-4ff6-a837-ab173bfa4228)

Code:
>
![grafik](https://github.com/flutter/flutter/assets/55744793/c3d20d2e-746b-497c-baec-526561cef4ac)
>
![grafik](https://github.com/flutter/flutter/assets/55744793/53091af7-fc12-4ed9-80d8-7680b260a2f8)
>
![grafik](https://github.com/flutter/flutter/assets/55744793/5753710d-992d-435d-b729-4082a5c2a691)

**Comment by moffatman** [comment]
If you pass `center: centerKey` to the `CustomScrollView`, it is an error not to actually include a child with that `key: centerKey`.

**Comment by huycozy** [comment]
@KattlerJoe Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this? Also, please provide the output of `flutter doctor -v` as well. Thanks!
