### ISSUE TITLE
Getting a gesture library error

### ISSUE THREAD

**Issue by ctemkar** [flutter/flutter#128130]
Apparently this a bug in the Flutter framework, because it isn't referring to any of my files

======== Exception caught by gestures library ======================================================
The following _TypeError was thrown while handling a pointer data packet:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:733:26)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#2      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#3      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#4      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3634:31)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#8      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#10     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#12     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#13     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)

**Comment by huycozy** [comment]
Hi @ctemkar 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Regarding the issue, it could be caused by implementation that leads to framework error as above. You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a single `main.dart` file that can be run independently. If the issue's still reproducible, please provide that `main.dart` file so that we can verify the issue properly. Thanks!
