### ISSUE TITLE
Issue with Migrate to AndroidX: No usage Found in the project

### ISSUE THREAD

**Issue by Actalwar** [flutter/flutter#128227]
I am trying to run the project from following  [git](https://github.com/londonappbrewery/Clima-Flutter.git) hub but I received error stating, I need to migrate it to AndroidX. I tried the steps explained in following URL : [Flutter doc](https://docs.flutter.dev/release/breaking-changes/androidx-migration) but recived error message shown below.
<img width="280" alt="image" src="https://github.com/flutter/flutter/assets/121123119/5c9b5846-ce6b-4b49-b3bb-1693eaf8695e">

I am new to flutter. Please help. 

Thanks
Akash

**Comment by huycozy** [comment]
Hi @Actalwar 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and ask questions like this.

You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.

Closing since it looks like an issue with the provided project. If you disagree, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. Thanks!
