### ISSUE TITLE
Need mechanism for scheduling `setState` to run as soon as possible when idle

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#128384]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am trying to find a reliable way to always run a function in Flutter, either immediately, if no build/layout/painting is being performed, or as soon as the current frame ends. I don't know if there is a "right" way to do that using the current API (or maybe I am just confused).

I have a reactive widget based on a listenable model. When the model changes, I want to trigger the reactive widget to be rebuilt by calling `setState()`. The problem is that the model can be changed from anywhere, including inside a `build` method.

I discovered that `setState()` is not supposed to be called while `build` is running on the widget tree. Therefore, if the model changes while the layout is taking place, the running of `setState()` should be deferred until after the end of the frame, using `WidgetsBinding.instance.addPostFrameCallback`.

This is what I have:

The `setState()` call:

```dart
// Mark the ReactiveWidget as needing to be rebuilt.
  void _updateReactiveWidget() {
    // Widget may no longer be mounted, if dispose() was called after build()
    if (mounted) {
      setState(() => _cachedWidget = null);
    }
  }
```

The listener (original):

```dart

```dart
  void _listener() {
    WidgetsBinding.instance
        .addPostFrameCallback((_) => _updateReactiveWidget());
  }
}
```

I tried this, however I found that if there was no rendering or animation going on, calling `WidgetsBinding.instance.addPostFrameCallback` did nothing until the user interacted with the UI, triggering the next frame. Therefore I changed the code to this:

```dart
  // Add a listener to call setState when the ReactiveValue value changes
  void _listener() {
    if (SchedulerBinding.instance.schedulerPhase == SchedulerPhase.idle) {
      // Set state immediately if scheduler is idle
      _updateReactiveWidget();
    } else {
      // Need to defer calling setState until after `build` has completed:
      // https://stackoverflow.com/a/59478165/3950982
      WidgetsBinding.instance
          .addPostFrameCallback((_) => _updateReactiveWidget());
    }
  }
}
```

This solves the problem of trying to update the UI when the scheduler is idle. However, the documentation for `addPostFrameCallback` makes me think this is not a complete solution:

```dart
  /// This callback is run during a frame, just after the persistent
  /// frame callbacks (which is when the main rendering pipeline has
  /// been flushed). If a frame is in progress and post-frame
  /// callbacks haven't been executed yet, then the registered
  /// callback is still executed during the frame. Otherwise, the
  /// registered callback is executed during the next frame.
```

If this is the *last* frame that currently needs drawing (so the scheduler is about to go idle), and the callback is scheduled to be executed in the next frame (when there is no next frame), won't the UI fail to update again until the user interacts with the UI, the same as the original `_listener` code?

So my questions are as follows: (I don't know if this is a feature request for a better way to do this in Flutter, or if I'm just misunderstanding the current situation):

1. Do I need to do anything special with other values of `SchedulerPhase`, other than `idle`?
2. If not idle, can `addPostFrameCallback` end up scheduling an update for a frame that may not be drawn for a while, if the current frame is the last frame that currently needs drawing?

### Proposal

Shouldn't there be a simpler way to do this, e.g. a single call `SchedulerBinding.doWhenIdle(() {...})` that takes care of any special cases depending on scheduler state, and ensures that the code runs once, as soon as possible, but not during build/layout/rendering, and that it runs whether or not there is any additional frame currently scheduled to be rendered?

**Comment by Hixie** [comment]
I strongly recommend designing your model so that build is entirely side-effect free. Nothing in a build method should ever compute new state or cause anything to change.  That is the "right" way to do this.

That said, if for some reason that's not an option, you can check `SchedulerBinding.instance.schedulerPhase`; if it's set to `persistentCallbacks` then you're in the phase of a frame where you should not call `setState`, and you can call `registerPostFrameCallback`; in any other case, use `setState`.

But I must emphasize again that that's fighting the system; the correct approach is to make sure that your build is unidirectional and side-effect free.

**Comment by lukehutch** [comment]
@Hixie Oh I know :-) The problem is I'm building a library, and I can't control what my callers are going to do with the library, including and not limited to utilizing build methods with side effects (I already had two bugs reported for reasons related to this). So I need the library to be maximally robust.

OK, so I was only calling `setState` when `SchedulerBinding.instance.schedulerPhase` was set to `idle`, as I showed in the code, otherwise I called `registerPostFrameCallback` for all other states. I will change this to the logic that you suggested. (Why is `persistentCallbacks` special? Are non-persistent callbacks only added by user code, or similar?)

Since reasoning through all this is complex, I still suggest that `SchedulerBinding` have a method added that runs this check, and guarantees it will run code as soon as possible, after any persistent callbacks, regardless of whether there are more frames to render.

**Comment by Hixie** [comment]
In theory the answers to your questions are at:
 - https://master-api.flutter.dev/flutter/scheduler/SchedulerBinding-mixin.html
 - https://master-api.flutter.dev/flutter/scheduler/SchedulerPhase.html

...but please let me know if that doesn't in fact answer your questions.

Personally I recommend putting `assert(SchedulerBinding.instance.schedulerPhase != SchedulerPhrase.persistentCallbacks, 'Do not mutate state during a build method.');` in your API. Or alternatively, `assert(!WidgetsBinding.instance.buildOwner.debugBuilding)`. Libraries should not enable bad patterns, they should discourage them.

Indeed, we don't want to add the API you propose because it would encourage incorrect use of the API. There are any number of issues that fall out of the kind of design that has build methods causing side-effects, such as animations that are off by one frame, or in particularly egregious cases, dataloss due to the unclear ownership models that lead to this kind of twisted design.

**Comment by lukehutch** [comment]
Your reasoning makes sense, but then anything that blocks or has side effects needs to be scheduled to run in a post-frame callback, lest it be run intentionally or inadvertently while `build` is running. The problem I ran into is that the post-frame callback is never called if there are no more frames to be rendered.

So even if you could modify the `registerPostFrameCallback` method so that it is always guaranteed to run as soon as possible after persisent callbacks, even if no more frames need to be rendered at this time, then I would be happy using it personally :-)

Would `SchedulerBinding.endOfFrame.then(() {...})` work for this?

**Comment by lukehutch** [comment]
While I have your attention, how can I get a reference to the widget whose `build` method is currently running? Is that available through `WidgetsBinding.instance`? For my library, I need to be able to determine this, regardless of how many stack frames deep the code is, beyond the `build` method stack frame. (Currently I subclass `StatefulWidget` and then set a static/global reference to the current widget in `build`, but this is a horrible solution...)

**Comment by huycozy** [comment]
Labeling the issue for further insights. Also, I wonder if this issue is somehow related to https://github.com/flutter/flutter/issues/111628?

**Comment by Hixie** [comment]
> Your reasoning makes sense, but then anything that blocks or has side effects needs to be scheduled to run in a post-frame callback, lest it be run intentionally or inadvertently while `build` is running.

Nothing can accidentally run while build is running, the build code is single-threaded and synchronous.

You can run code directly when you get an event notification, asynchronous callback, or whatever other notification reports that work is ready to be executed. You could also use `SchedulerBinding.instance.scheduleTask` which will run the work as soon as possible without getting in the way of the frame workload (to minimize the impact on performance, it's best to do this work in millisecond increments). Or alternatively do the work in a background isolate and just transmit the information to the main isolate when the model needs updating.

> Related: if `setState` is being called from a delayed future, or from a stream (in this case, triggered by a value-changed listener), then in theory `setState` could be run anytime including (possibly) while a build method is running.

No tasks or microtasks are able to run while the build is happening, so it is safe from such reentrant calls.

> Is there any chance a user's async code may be executed while post-frame callbacks are being run, interleaved with the execution of persistent callbacks? Or is there no async context switch allowed during the persistent callbacks phase?

Post-frame callbacks are also run single-threaded and synchronously, and in the same task as the build/layout logic, so nothing can come between build and a post-frame callback and certainly nothing in the main thread can ever collide with it (and since we don't have cross-thread shared memory, that means nothing can collide with it in general).

> While I have your attention, how can I get a reference to the widget whose `build` method is currently running? It looks like `WidgetsBinding.instance.buildOwner._debugCurrentBuildTarget` is not exposed. For my library, I need to be able to determine the current build target, which is defined in the user's code, not my library code. (Currently I subclass `StatefulWidget` and then set a static/global reference to the current widget in `build`, but this is a horrible solution...)

I don't believe this information is exposed. In release builds we don't track this information (because doing so would be expensive), and in debug builds we only use it to track error messages. In general I would be very skeptical of any code that needs to rely on that information, but maybe if you file a new issue with the use case that's driving you to asking that question we may find a better solution.

**Comment by lukehutch** [comment]
@Hixie OK, thank you for taking the time to explain all of that. It's all a lot clearer now.

> maybe if you file a new issue with the use case that's driving you to asking that question we may find a better solution.

I filed #128461. Thanks!

I'll close this since I think you answered all my questions. I made the `assert` changes you suggested, to prevent side effects in `build`.
