### ISSUE TITLE
Unable to use DefaultMaterialLocalizations from a test using flutter_driver

### ISSUE THREAD

**Issue by johnfesa** [flutter/flutter#12831]
Project Mulligan is affected by this issue.

## Steps to Reproduce

Using flutter_driver, attempt to find a Widget by its Material tooltip. Implement this by declaring a dependency upon DefaultMaterialLocalizations and using one of the tooltip strings it defines.

Observe that 'flutter/src/material/material_localizations.dart' depends on 'flutter/src/material/time.dart', which depends on 'dart:ui', which prevents usage in the stand-alone VM.

Using these strings directly to drive the UI from tests is important because it prevents duplication of Flutter string literals within test sources. If string literals were instead used within test sources, automated tests would break if a localizable string in Flutter's Material implementation were to change.

## Logs

Unable to spawn isolate: The built-in library 'dart:ui' is not available on the stand-alone VM.
'package:flutter/src/material/time.dart': error: line 5 pos 1: library handler failed
import 'dart:ui' show hashValues;
^

**Comment by eseidelGoogle** [comment]
@tvolkert or @mehmetf are probably the right people to ask here.

**Comment by eseidelGoogle** [comment]
Actually, never mind.  If this occurs in straight up `flutter drive` with out any Google-specific stuff, then @yjbanov is the right person.

**Comment by tvolkert** [comment]
Discussed this with @yjbanov.  We purposely run the code that remotely drives the app in a standalone embedder (not `flutter_tester`) so as to not confuse the user as to which type of test they're running.  e.g. if they were running in `flutter_tester`, they could end up inadvertently writing a unit test that doesn't actually drive the app as they intended.  The would also have access to finders that don't work in `flutter_driver`.

However, this use case seems valid.  @yjbanov suggests perhaps setting a key on the widget and finding by key instead of finding by text.  @johnfesa is that an option in your tests?

**Comment by yjbanov** [comment]
@johnfesa Curious, what is it you are testing i18n-wise that lead you to a FlutterDriver test rather than a widget test? FlutterDriver is good mostly for two things: performance testing and interactions with native code (Java, Obj-C, etc).

**Comment by tvolkert** [comment]
Internally, they're also used extensively for screenshot (golden image) testing.  However, there's no inherent reason that we can't use `flutter_tester` (unit) tests for that as well.  We need https://github.com/flutter/flutter/issues/11648 to unlock that feature (associated screen diffing wiring tracked internally in b/64849174)

**Comment by alanrussian** [comment]
mulligan will probably continue to want to do driver tests for screendiff testing to some extent in order to have full integration tests of our app.

However, screendiff testing at the widget testing layer sounds awesome and very useful.

**Comment by johnfesa** [comment]
@tvolkert Many of the Widgets we'd like to use to navigate the interface for a screendiff test are created by Material components on our behalf; things like the Back button in the AppBar. So we're not explicitly constructing them, and thus it's not clear to me how we'd easily provide a Key.

In general it would be nice to avoid having testing-specific code to set Keys on Widgets that don't otherwise need them; I'd view that as a workaround to this problem rather than a solution.

**Comment by yjbanov** [comment]
Can you use [FlutterDriver.requestData](https://docs.flutter.io/flutter/flutter_driver/FlutterDriver/requestData.html) to translate strings needed by the test script?

The `Locale` and specific implementation of `MaterialLocalizations` depends on a widget's location in the widget hierarchy. So even if you were able to use `DefaultMaterialLocalizations` in the driver script, you would need to make sure that it translates correctly, which requires that you synchronize your app with your test script. For example, when the app stops using `DefaultMaterialLocalizations` and switches to, say, `GlobalMaterialLocalizations`, your test may continue working for a while - even if the test uses a different implementation - as long as the two implementations _happen_ to translate identically. However, that seems very brittle. I think `requestData` is a more reliable method to do this, because it would be using the same implementation of `MaterialLocalizations`.

**Comment by tvolkert** [comment]
@yjbanov do you know the current status of this?

**Comment by yjbanov** [comment]
@tvolkert, @tvolkert told me a couple of days back that we might add support for taking screenshots from within `flutter_tester` soon 😉 Not much to report beyond that.

(`requestData` should still be a workable solution, although I have not seen any reports of success or failure with it)

**Comment by supergarotinho** [comment]
I think that is not the same but it is a related issue: At the driver test case, i want to know few things like which locale where used within the app or the screen size that is being tested (Consider that i run the same set of tests on several combinations of phones and locales).

I can use this informations to test some behaviors that should happen depending on the screen size or locale. Sometimes, you want to be sure that some localized info is being displayed on the screen. Or some behavior should happen depending on the locale.

**Comment by supergarotinho** [comment]
Related issue: #31609

**Comment by dnfield** [comment]
I'm going to close this as resolved - we don't plan to make MaterialLocalizations directly work outside of `dart:ui` at this time, and it sounds like the need was resolved with golden testing that we now support.
