### ISSUE TITLE
he following assertion was thrown during paint(): RenderBox was not laid out: RenderRepaintBoundary#3c66c NEEDS-LAYOUT NEEDS-PAINT 'package:flutter/src/rendering/box.dart': Failed assertion: line 1966 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by vrushabh007** [flutter/flutter#128494]
while i create a TextField in Row then problem is shown in console

**Comment by huycozy** [comment]
Hi @vrushabh007 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
