### ISSUE TITLE
MediaQuery.of(context).accessibleNavigation return true even talkback disabled since flutter 3.7

### ISSUE THREAD

**Issue by agacemi** [flutter/flutter#128409]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We observed this behavior since Flutter 3.7. I note that it is in case of an application launched with the Appium automation tools which uses UiAutomator v2. If the application is launched manually, no problem is noticed.

Steps to reproduce:
- Use the application built using flutter 3.7 (or flutter 3.10, the problem is also present on the current stable version)
- run an sample scenario using Appium (with uiAutomator v2) - Before download Appium Desktop (https://github.com/appium/appium-desktop)
- MediaQuery.of(context).accessibleNavigation will be true

The same scenario with flutter 3.3 (with the same app code), MediaQuery.of(context).accessibleNavigation still false with talkback disabled

Please find below samples to reproduce the issue:
- sample automation project with appiulm that can be used to launch the app: https://github.com/agacemi/AccessibleNavigationSwitchDemo. In this sample, three Intellij lauchers, each one for flutter version.
- Sample Flutter app used to build a tested app using Flutter 3.3, Flutter 3.7 and Flutter 3.10 https://github.com/agacemi/AccessibleNavigationSampleFlutterApp

### Expected results

MediaQuery.of(context).accessibleNavigation return false as flutter 3.3 when talkback is disabled

### Actual results

MediaQuery.of(context).accessibleNavigation return true when talkback is disabled

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by bleroux** [comment]
@agacemi Thanks for the detailed report.

Since Flutter 3.7, a change was introduced on the engine side, see https://github.com/flutter/engine/pull/35478, to fix https://github.com/flutter/flutter/issues/109521.

As described in the PR and in the following comment,
https://github.com/flutter/flutter/issues/109521#issuecomment-1217082360, there is no easy solution to detect specific assistive feature activation.

Since this fix landed, `MediaQuery.of(context).accessibleNavigation` returns true not only when TalkBack is activated but also when any accessible services are used (see https://github.com/flutter/flutter/issues/119094#issuecomment-1426067817 where it was reported with BitWarden) and it is probably the case with Appium.

The advice is to not rely on this flag if the need is to detect solely when TalkBack is activated.
And unfortunately, there are no known workaround, see https://github.com/flutter/flutter/issues/109521#issuecomment-1218465190.

**Comment by agacemi** [comment]
Ok it's clear. Thank you for response
