### ISSUE TITLE
Flutter3.7.3 fails to compile 'flutter build web' on linux

### ISSUE THREAD

**Issue by HSCOO** [flutter/flutter#128481]
I compile flutter web in linux, it works when **flutter3.0.1**, when I upgrade to **3.7.3** it doesn't work. I noticed that `dart2js` does not work after **dart2.18.0**, is it related to this? https://dart.dev/tools/dart2js.

<img width="969" alt="image" src="https://github.com/flutter/flutter/assets/7268774/a3ca9d18-4a80-4dfe-b42b-463c64004152">

I try to use `dart compile js -O2 -o out/main.js web/main.dart`, but I get a lot of errors.

<img width="762" alt="image" src="https://github.com/flutter/flutter/assets/7268774/b7233a32-3131-4add-bc5e-6b2a5309743b">
<img width="614" alt="image" src="https://github.com/flutter/flutter/assets/7268774/356bcc31-9eab-486b-9303-e589665faba9">

I also didn't find an answer for `dart:ui` for the web, anyone have any suggestions, thanks！

**Comment by huycozy** [comment]
Hi @HSCOO 
I don't see the issue with `flutter build web` command on the latest Flutter stable channel. Can you share the complete output of `flutter build web -v`? (Please provide the the output in text format instead of a screenshot for better readability and investigation)

Also, please retry on the latest stable and master channels to see if the issue still persists or not.
