### ISSUE TITLE
M3 tabs spec issues

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#128696]
Spec

![image](https://github.com/flutter/flutter/assets/6655696/a952866d-d1ad-40c2-8ea1-882b2ecd799d)

Flutter

![image](https://github.com/flutter/flutter/assets/6655696/ed224aaa-e639-4638-be23-4230d7ecaf99)

Layout
- [ ] The text style does not seem to match spec (it's possible this is because I'm on a mac and San Francisco is used on web)
- [x] The height of the primary tabs component with icons is described as 64dp.  In Flutter it appears to be 74dp. The distance between the text and tab bottom is too large (https://github.com/flutter/flutter/pull/140698)

Motion
- [ ] Tab indicator does not stretch when different tab is selected, as seen in spec
    https://github.com/flutter/flutter/assets/6655696/a194ea91-5d34-4e08-b69e-4ce5234ae2f2 (https://github.com/flutter/flutter/pull/141954)

**Comment by Piinks** [comment]
I agree, the changes in #125974 have been very challenging to land with minor changes like this affecting thousands of screenshot tests. Let's land that first before tackling this. And when we do tackle this, it will be immensely easier to just make singular atomic changes at a time. That way the any affected screenshot is easy to debug since we are only lookin for one change at a time.

**Comment by guidezpl** [comment]
Thank you! This is one of the more heavily used components for sure.

**Comment by TahaTesser** [comment]
I'll make progress on this issue right after my vacation.

**Comment by TahaTesser** [comment]
>  The height of the primary tabs component with icons is described as 64dp. In Flutter it appears to be 74dp.

While the web specs say 64dp, actual TabLayout size is[ 72dp in Android implementation](https://github.com/material-components/material-components-android/blob/78cc54b8c39da437732ff3d7c96de8f345e09348/lib/java/com/google/android/material/tabs/TabLayout.java#L189C28-L189C57). Maybe the web specs are wrong?


>  The text style does not seem to match spec (it's possible this is because I'm on a mac and San Francisco is used on web)
>  The distance between the text and tab bottom is too large

These are two are relatedd to height and web specs for the height don't match the actual implementation.

**Comment by davidmartos96** [comment]
@TahaTesser I've looked into the Jetpack compose source and it also uses 72 ([jetpack compose Tab source](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/Tab.kt#432)) although the design tokens in the source use the 64 from the spec ([tokens in jetpack compose](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/PrimaryNavigationTabTokens.kt#37))

Strangely enough they use the value from the design tokens for the `SmallTabHeight` (no label)" ([source](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/Tab.kt#431)) but not for the `LargeTabHeight` (icon+label) where the 72 is hardcoded.

Maybe it's an issue in the Android implementation? The 72 in the Material 3 Jetpack Compose implementation originates from a duplication of the original M2 implementation (https://android-review.googlesource.com/c/platform/frameworks/support/+/1947012), and hasn't been modified since. So maybe it's a small slip-up.

**Comment by davidmartos96** [comment]
@guidezpl Hello! The 3rd checkbox in the issue description could be checked off, as it has been fixed in https://github.com/flutter/flutter/pull/140698

The last checkbox about the stretch animation is being worked in https://github.com/flutter/flutter/pull/141954
