### ISSUE TITLE
Some MTL APIs used in flutter/engine are deprecated. 

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#128729]
**Steps to reproduce the warnings:**

1. Go to local build root folder, typically located one level up of the engine directory. Then change the `ios_deployment_target` to 17.0: https://github.com/flutter/buildroot/blob/master/build/config/ios/ios_sdk.gni#L19 
1. Add -Wdeprecated-declarations and -Wdeprecated-implementations in flutter_clags_objc https://github.com/flutter/engine/blob/main/common/config.gni#L60 
1. Build the local engine like you normally would.

**Below are the list of the APIs that are deprecated in iOS 16.**

'MTLFeatureSet_iOS_GPUFamily2_v1' is deprecated: first deprecated in iOS 16.0 - Use MTLGPUFamily instead [-Werror,-Wdeprecated-declarations]

'MTLFeatureSet_iOS_GPUFamily4_v1' is deprecated: first deprecated in iOS 16.0 - Use MTLGPUFamily instead [-Werror,-Wdeprecated-declarations]

 'MTLFeatureSet_iOS_GPUFamily3_v1' is deprecated: first deprecated in iOS 16.0 - Use MTLGPUFamily instead [-Werror,-Wdeprecated-declarations]

 'supportsFeatureSet:' is deprecated: first deprecated in iOS 16.0 - Use supportsFamily instead [-Werror,-Wdeprecated-declarations]
 'supportsFeatureSet:' is deprecated: first deprecated in iOS 16.0 - Use supportsFamily instead [-Werror,-Wdeprecated-declarations]

 'MTLGPUFamilyMacCatalyst1' is deprecated: first deprecated in iOS 16.0 [-Werror,-Wdeprecated-declarations]

 'MTLGPUFamilyMac1' is deprecated: first deprecated in iOS 16.0 [-Werror,-Wdeprecated-declarations]

'newLibraryWithFile:error:' is deprecated: first deprecated in iOS 16.0 - Use -newLibraryWithURL:error: instead [-Werror,-Wdeprecated-declarations]

**Comment by jmagman** [comment]
These are using proper `@availability` fallbacks.  
https://github.com/flutter/engine/blob/d184e0f765631ced70bfeaaddf49cb24db1ae0a9/impeller/renderer/backend/metal/allocator_mtl.mm#L19-L26


```
if (@available(ios 13.0, tvos 13.0, macos 10.15, *)) {
```
I believe you're seeing this because of the weird and unexpected behavior of `@availability` (which bites me every year) where these are deprecated in iOS 16, and you're targeting a higher version than iOS 16, so it's showing the deprecation error even in the fallback.  When we target iOS 13 we'll remove this availability fallback well before we target iOS 16, so this won't ever be seen in production. 

If your goal is to find APIs deprecated in iOS 17 that _aren't_ guarded by availability checks, you can skip updating `ios_deployment_target` and just add the  `-Wdeprecated` flags.
