### ISSUE TITLE
[Impeller] VALIDATION_LOG should print something in Flutter debug runtime mode

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#128808]
Right now we set VALIDATION_LOGS to not be fatal and they don't print anything out.

This means that when a developer submits an "Impeller renders this wrong/renders nothing," there's no log output from potential validation issues.

Having these validation issues could be helpful in tracking down what's going on and deduplicating bugs more quickly.

**Comment by gaaclarke** [comment]
I've ran into this too since a lot of the time the validation errors are fatal indirectly, so not printing something out and getting an unrelated stacktrace slows things down.  For example, when a context is invalid because we are trying to load an extension that doesn't exist, there is a crash when deleting the invalid context.
