### ISSUE TITLE
this is the new error which error when the keybord is open

### ISSUE THREAD

**Issue by khubabcreation** [flutter/flutter#128815]
unimplement error see also : http //flutter .dev.docs/ testing/errors

**Comment by huycozy** [comment]
Hi @khubabcreation 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
