### ISSUE TITLE
[pigeon] Recursively create output target files

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128820]
At least the Dart generation, and probably all of the language generation, doesn't create the output file recursively. That leads to confusing flows like the following, which has bitten me several times:

1. Set up Pigeon for the first time in a plugin that was simple enough to only have a `lib/plugin_name.dart` file with all of the implementation.
2. Configure the Dart to output to `lib/src/messages.g.dart`.
3. Run Pigeon generation.
4. Get an error about `lib/src/messages.g.dart` not existing. (The actual problem is that `lib/src/` doesn't exist, so it can't make the file).

We should do a `create(recursive: true)` on the target File before trying to write to it.

**Comment by abdlrhmanshehatamoussa** [comment]
Hey @stuartmorgan 👋 
I can take this one, if no one is working on it 🙏

**Comment by Nitin-Poojary** [comment]
I identified that the issue was caused by the file.openWrite() function in the openSink() method within pigeon_lib.dart. To resolve this, I modified the code by converting the openSink() method and the shouldGenerate() method in the GeneratorAdapter abstract class to return Futures. Then I added the await file.create(recursive: true) before file.openWrite().

Is this approach right? Is there any better approach?

**Comment by stuartmorgan** [comment]
@Nitin-Poojary That seems like a discussion that would be easier to have in a code review on a PR where people could look at the details of the change in context.

**Comment by ValentinVignal** [comment]
Should this be closed as https://github.com/flutter/packages/pull/4458 got merged?

**Comment by stuartmorgan** [comment]
Yes, thanks!
