### ISSUE TITLE
Flutter  scroll physics  junk 

### ISSUE THREAD

**Issue by daddasoft** [flutter/flutter#128888]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When add a list view or a scrolable widget when i reach the top or the end the text start moving from it place and animation become slow 

### Expected results

Animation should  le smother and text shouldn't  move down

### Actual results

Animation  junk

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by 0x4ym4n** [comment]
I wonder how did you tick this one:
"I have read the guide to filing a bug"

**Comment by huycozy** [comment]
@daddasoft 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

Since this is a performance issue, please try to clarify some information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- More details `step by step` to reproduce this
- Which environment did this issue happen in? (Android/iOS/..)
- Please attach the timeline trace JSON file when running the sample code in [profile](https://docs.flutter.dev/testing/build-modes#profile) mode. You can find the instructions for it in this issue https://github.com/flutter/flutter/issues/74833.

Please also check [known issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+animation%22+label%3A%22f%3A+scrolling%22+label%3A%22severe%3A+performance%22) if they are similar to your case as well.
