### ISSUE TITLE
[Impeller] Investigate gallery worst frame time regression when switching to Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128919]
I suspect this is triggered during the navigation to the first sample app. A large number of textures are decoded and the glyph atlas populates heavily.

![image](https://github.com/flutter/flutter/assets/8975114/b0a40392-3108-4c22-a8ee-fc4cb9ace268)

**Comment by jonahwilliams** [comment]
Some potential issues: 

* The VkQueues are mutex guarded and I think that has the potential to let a worker thread stall the main thread.
* We end up creating a new pipeline variant (why?) and that is stalling the main thread too...

**Comment by jonahwilliams** [comment]
We actually seem to be creating about 7 new PSO variants in the frame workload. Unfortunately this appears to be much, much slower than on metal so we're going to need to be smarter here

**Comment by jonahwilliams** [comment]
(about 10ms per variant 😢 )

**Comment by chinmaygarde** [comment]
Some comments:

* We moved to a world where the concurrent message loop is shared between IO tasks as well as the Vulkan concurrent worker pool. The Vulkan pool is used to create pipeline derivatives. In the trace above, construction of the derivative within a frame workload is waiting past texture decompression. This is because there is no QoS specification on the tasks today. Either we split the pool or have QoS task specifications.
* We don't do pipeline derivatives by specifying base pipeline handles. [But it doesn't seem to do much on the targets we care about anyway](https://stackoverflow.com/a/59312390). There is some doubt on that thread about this guidance though. We could set it up just in case. See the guidance about `VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT`.
* Through dynamic states, we probably need to create way fewer derivatives than Metal. We should see how many we can move to be dynamic. Perhaps enough to create these eagerly. I just setup what was easiest.
* I was under the (likely mistaken) assumption that derivatives creation would be faster if obtained from the same PSO cache. But perhaps that is not the case?

**Comment by chinmaygarde** [comment]
Thinking about it some more, QoS specifications on tasks on the worker pool is probably not a great idea since the thread itself has a lower priority. So there is going to be priority inversion anyway. We probably just need a separate pool.

**Comment by jonahwilliams** [comment]
QoS issues make sense, though I wonder if moving PSO creation to a worker thread is a net win if we're going to be blocking frame construction on their completion anyway?

**Comment by jonahwilliams** [comment]
Yeah makes sense. I'm going to take a look at what actually differs with these variants first.

**Comment by dnfield** [comment]
Can we defer decompressing images until we have no pending PSO variants?

**Comment by chinmaygarde** [comment]
From the horses mouth, [the derivatives won't help](https://developer.arm.com/documentation/101897/0301/CPU-overheads/Pipeline-creation-in-Vulkan). I think we should audit every single option in `ContentContextOptions` to see if we have a dynamic state.

**Comment by dnfield** [comment]
> Vulkan pipelines have similar compile requirements to OpenGL ES shaders.

...can/should we be pre-caching pipelines?

**Comment by chinmaygarde** [comment]
We are pre-caching pipeline. Just not their derivatives. See ContentContextOptions.

**Comment by jonahwilliams** [comment]
Closing in favor of the two specific issues I've filled above.

**Comment by jonahwilliams** [comment]
Actually, not there are still more issues in here such as the extremely expensive glyph atlas upload.

**Comment by chinmaygarde** [comment]
Are there really no traces from Impeller under SurfaceFrame::Submit? Or are we just not capturing them somehow?

**Comment by jonahwilliams** [comment]
If I'm guessing we're blocking on SubmitKHR but we don't have any more traces there.

**Comment by chinmaygarde** [comment]
IIRC, we have already filed issues for allocator stalls, fence waiter stalls, lazy texture support, etc.. from the findings of this investigation. Closing this umbrella bug but please re-open if this is still in progress.
