### ISSUE TITLE
[web] Add embedding examples for more web frameworks, like React.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#128980]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

(Splitting from https://github.com/flutter/flutter/issues/128832, on behalf of @ctsstc)

>
> I would also love to see an example with React, as well as how to have typing in TypeScript if such is available.
> 
> [...]
>
> Hopefully someone else who needs this information finds this issue later and it provides them with some relevant help. For now it might be nice to have additional documentation around this, as well as additional examples besides just Angular via: https://github.com/flutter/samples/tree/main/web_embedding

### Proposal

Extend the current samples/documentation to cover embedding with more frameworks in addition to Angular, like React.

Samples repo: https://github.com/flutter/samples/tree/main/web_embedding
Documentation: https://docs.flutter.dev/deployment/web#embedding-a-flutter-app-into-an-html-page

**Comment by isaturk66** [comment]
Please please provide a react example,

I have been trying to achieve to web-embed a flutter app into a reactjs app following this guide,  https://github.com/flutter/flutter/issues/123940.

It mostly worked fine however, when I open the react app, it just reroutes to the flutter web app instead of embedding it as a div.

So if anyone could provide a sample code that achieves this, it should be a great addition to the documentation and benefit the community

**Comment by ditman** [comment]
@isaturk66 can you share your example? I can help with the embedding part, but setting up react is pretty time-consuming for me. (Have you seen the Angular example that already exists?)

**Comment by the-kool-sk** [comment]
I am also looking for sample, where flutter is embedded in reactjs using flutter embedding. 
This is very much required when you what to slowly migrate your existing react web app to flutter web. 
If someone could just provide a simple sample how to achieve this it will be very useful. 
Thank you. 🙏

**Comment by ditman** [comment]
@the-kool-sk if you provide a base react app, like the Angular one here: https://github.com/flutter/samples/tree/main/web_embedding/ng-flutter I can help write the glue code.

**Comment by p-mazhnik** [comment]
I have an example where Flutter is embedded into a React Native Web app (android, ios, web), which, in the web part, is no different from embedding it into a regular React app: https://github.com/p-mazhnik/rn-package-flutter

The repository also contains an example of embedding into a regular React app created with `create-react-app`.
<br>

On web, embedding is implemented using both `iframe` and `hostElement` methods. The first method can be used to render multiple Flutter views on the page because this is currently not supported in web with custom elements.
<br>

These samples served a specific purpose: showcasing the integration of a Flutter module into a React Native Web app as an npm package. As a result, they might be a bit overcomplicated for the scope of this particular issue. However, I can create simplified versions in the `flutter/samples` repository once I implement the code for communication between Flutter and React.

**Comment by the-kool-sk** [comment]
Thank you this seems to be good to start. Still will be waiting for a sample using flutter embedding. Because passing data from react side to flutter has more practical applications than just adding it as a npm package. Thank you though ☺️

**Comment by p-mazhnik** [comment]
> passing data from react side to flutter has more practical applications

Yes, but this flow is no different from the existing Angular sample.  

Anyway, I've created a draft PR with a sample React app: https://github.com/flutter/samples/pull/1945
 It's a "look-alike" of an existing Angular sample.

**Comment by ditman** [comment]
Thanks @p-mazhnik for your **ReactJS** and **React Native** examples!

They've been linked in the samples repo README, here:

https://github.com/flutter/samples/tree/main/web_embedding#community-contributions

I'm going to close this issue as completed, as anybody who wants to contribute any other example (Vue.js? Svelte? jQuery? Mootools?) is welcome to do so! Remember to create a PR in the `flutter/samples` repo so we can link it from the `community-contributions` list!
