### ISSUE TITLE
Global setting for `--no-version-check`

### ISSUE THREAD

**Issue by christian-heusel** [flutter/flutter#129143]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am currently working on [guidance](https://wiki.archlinux.org/title/User:Gromit/Flutter_package_guidelines) on how to package flutter applications in ArchLinux.

Currently flutter seems to assume that it lives somewhere in a user-owned directory and that it has read & write permission on its files. This is of course a problem when flutter is shipped as a system package, since packages installed by the system package manager are usually assumed to be only modified by the package manager itself.

Having flutter available via package manager would be a good thing so it can be used a build dependency for linux applications, for which the number is currently growing rapidly.

So one of the things that needs to be done in order to make flutter more easily packageable is to disable the automatic version checking and delegate this responsibility to the packager/package manager.

Currently this can be done only by specifying `--no-version-check` for every command.

### Proposal

Introduce a new option `--disable-version-checking` to `flutter config` which disables version checks globally.

---
Edit: Extended Use Case / Rationale

**Comment by andrewkolos** [comment]
Thanks for the feature request!

> Currently flutter seems to assume that it lives somewhere in a user-owned directory and that it has read & write permission on its files.

This is correct. To my knowledge, Flutter needs write access to its own directory for a few different reasons, which makes it challenging to have it installed and managed by package managers. I will be discussing this with @christopherfujino shortly.

**Comment by christopherfujino** [comment]
@christian-heusel I'm active on the AUR page for Flutter: https://aur.archlinux.org/packages/flutter and the tech lead for Flutter's CLI tool. I used to provide support there, but I now am of the opinion that developers should NOT use the AUR package. I think for now, the recommendation for packaging Flutter apps for Arch Linux would be to use the official open source workflow (download a [tarball](https://docs.flutter.dev/release/archive?tab=linux) from the website or `git clone https://github.com:flutter/flutter` to a user-owned directory).

Longer term, there is an open issue to refactor the CLI tool to support read-only installations: https://github.com/flutter/flutter/issues/91318. Note, NixOS maintains [custom patches](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/flutter/patches/flutter3) on the Flutter tool, but I suspect these will break with every new Stable release branch.

**Comment by PolarianDev** [comment]
@andrewkolos surely it is bad design for an application to write to its own installation directory in the first place, and also it is not following the ideology of least privileges then.

Also that would therefore mean that packaging flutter properly is impossible, and will need to be dumped in /opt with full read and write permissions to any user, which could potentially leave it vulnerable. So this situation is worst than I thought, and I am not certain that the work arounds I suggested to the aur maintainers and to @christian-heusel are going to work in light of this information.

@christopherfujino I assume you are `cfujino`?

I agree users shouldn't use the AUR package, but not because of I am against packaging, its because of its current state. It clones the repository, pulls dependencies (dart runtime) and then dumps the entire bundle into `/opt` and it doesn't even work (without manual intervention), and I have documented these issues (I have cited the comments where the solution was found):

https://wiki.archlinux.org/title/User:Gromit/Flutter_package_guidelines#Known_issues

Also no offense, but what kind of compiler do you have to install along side each package, and remember that is almost 1GB to be pulled every time a user wants to build a flutter package. Also it does not provide reproducibility, how are we meant to fix issues in the package if the compiler version changes automatically, and if its out of date self destructs which is why the update to https://aur.archlinux.org/packages/saber has been delayed, because the flutter package was not updated for a week or two, and flutter stops working. Also while we are here if you attempt to build a flutter app with an old version of flutter using `--no-version-check` you get a return code of `66` which when I did some research into it, is fixed by updating flutter, this leads to the fact flutter has a kill switch in it only allowing the latest version to work, is this true or is this just a coincidence?

There is no choice other than to package flutter, it is depended on by flutter applications, and giving up packaging flutter applications would be a shame

> NixOS maintains [custom patches](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/flutter/patches/flutter3) on the Flutter tool, but I suspect these will break with every new Stable release branch.

Well unfortunately we are not NixOS and these patches seem to only fix minor problems, but I am not a nix user so I can't verify this. It does seem like the packaging of flutter will be a very patch intensive task, and that is after getting the package to actually function.

I am only a contributor, @christian-heusel is the important one :P however I have invested a lot of time into trying to get flutter to work, into researching possible fixes, and also dealing with flutter rust native issues, because flutter appears to look for the `rustup` binary, but the `rust` package which is used does not contain said installer, because rust is managed by pacman, which breaks flutter builds, I do not know if this was due to flutter itself looking for rustup, or a build script of some sort.

Also I would like to say thank you @christopherfujino for helping out arch users on the AUR 😄

Have a good night,
Polarian

**Comment by Hixie** [comment]
After some discussion, we're concluded this is not a use case we wish to support, so I'm going to close this issue.
