### ISSUE TITLE
[flutter_tools] "OS Error: The handle is invalid" while trying to set echo mode on STDIN

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#129198]
On `beta/3.12.0` on Windows

```
StdinException: Error setting terminal echo mode, OS Error: The handle is invalid., errno = 6
at Stdin.echoMode=(stdio_patch.dart:85)
at AnsiTerminal.singleCharMode=(terminal.dart:309)
at TerminalHandler.setupTerminal(resident_runner.dart:1678)
at RunCommand.runCommand.<anonymous closure>(run.dart:748)
at _rootRunUnary(zone.dart:1407)
at _CustomZone.runUnary(zone.dart:1308)
at <asynchronous gap>(async)
```

Even though we check if stdinHasTerminal right before this

**Comment by christopherfujino** [comment]
cc @andrewkolos

**Comment by andrewkolos** [comment]
It appears `The handle is invalid., errno = 6` is all the information we are getting from Windows here. From a cursory Google search, it appears _one_ way this can happen is if a process tries to interact with a handle when it is invalid (e.g. already closed).

This issue has appeared before. See this issue query: https://github.com/flutter/flutter/issues?q=%22OS+Error%3A+The+handle+is+invalid%22

Due to the lack of repro of repro steps and relatively low number of users affected at this time, I won't be prioritizing this issue.

**Comment by christopherfujino** [comment]
> From a cursory Google search, it appears _one_ way this can happen is if a process tries to interact with a handle when it is invalid (e.g. already closed).

Not sure if the reports we're getting from real users if STDIN could possibly be closed, since their terminal session was still active (and they saw the github issue link coming from STDOUT from the tool)
