### ISSUE TITLE
[web]: <PWA custom font not working correctly >

### ISSUE THREAD

**Issue by ManasPanasa** [flutter/flutter#129341]
PWA custom font not working correctly while running in ios and android devices.
As i have given a custom font to my flutter PWA , but while i run it in various mobile devices its showing difference.
Not only the text but also for the text fields and all the alignments, structuring and size are getting distorted while running in android or ios devices.

**Comment by dam-ease** [comment]
Hi @ManasPanasa.
Please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps
- Actual vs Expected results

Thank you.
