### ISSUE TITLE
[integration_test] Flutter web integration test gets stuck in chrome browser but shows "All test passed" in terminal

### ISSUE THREAD

**Issue by Sourabh0991** [flutter/flutter#129349]
![image](https://github.com/flutter/flutter/assets/109236369/6e616c62-f55b-4daf-84d1-3c67272dd357)

This is happening since past 2 days.
In this case, there is no "Tear Down All" message and not even an exception.

![image](https://github.com/flutter/flutter/assets/109236369/e78faa9a-2ae7-4c31-b999-fd8f9a14c4b5)

**Comment by huycozy** [comment]
Hi @Sourabh0991 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly ([Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)). 

_Please provide the information in text format instead of a screenshot for better readability and investigation. You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description. Thank you!_
