### ISSUE TITLE
Keyboard Bug

### ISSUE THREAD

**Issue by DavidNazareno** [flutter/flutter#129364]
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#39642(physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 13:46:12.238000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 434 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by huycozy** [comment]
Hi @DavidNazareno 
There are also known issues in the database but I'm not sure which one is similar to this. So please try to provide all or some of the information indicated in the template so that we can address this issue properly ([Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

And you should also look through filed issues in this repository (see [flutter/issues](https://github.com/flutter/flutter/issues)) to see if there are any similar issues (reproducibility steps, target environment, stack trace, etc). Once you found it, please close this issue and follow it. Thanks!
