### ISSUE TITLE
"Constructors for public widgets should have a named 'key' parameter" warning

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#129424]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
import 'package:flutter/material.dart';

abstract class Parent extends StatefulWidget {
  Parent() : super(key: GlobalKey());
}

class Child extends Parent {
  Child();

  @override
  State<StatefulWidget> createState() {
    return ChildState();
  }
}

class ChildState extends State<Child> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

### Expected results

No warning

### Actual results

Shows this warning:

![imagen](https://github.com/flutter/flutter/assets/73592852/d7938a84-b81e-4727-b418-7d9131cc38dc)

### Code sample

See Steps to Reproduce

### Flutter Doctor output

No needed

**Comment by darshankawar** [comment]
@busslina 
It seems to be expected behavior. See the documentation which suggests the same:

https://dart-lang.github.io/linter/lints/use_key_in_widget_constructors.html

<img width="637" alt="Screenshot 2023-06-26 at 12 03 20 PM" src="https://github.com/flutter/flutter/assets/67046386/2e2dbda9-72af-4115-a189-76f673061cea">

So it seems to WAI and I'll close as such. If you disagree, write in comments and I'll reopen it.

**Comment by busslina** [comment]
@darshankawar Did you see the example code? As yo can see, the parent class provide the key parameter, so no need to provide it in child class. There is more, using VSCode, it suggest you a solution for this waning, and if you apply that patch then an error came in, because the parent class is not exposing a key parameter (it is providing it by itself).

I think you only read the issue title...
