### ISSUE TITLE
build dashboard "rerun" button greyed out after build finished with a failure

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#129644]
Two tests are currently making the tree red, and neither will allow me to reschedule:

![Screenshot from 2023-06-27 10-26-43](https://github.com/flutter/flutter/assets/7856010/8aec1637-f2a8-414b-9ad0-ffbb799249b3)

**Comment by christopherfujino** [comment]
nvm, I wasn't signed in lol

**Comment by ditman** [comment]
@christopherfujino the build dashboard doesn't "poll" to see if your session is valid, so you're NOT going crazy, you might have been able to click "Rerun" after your credentials expired, but then that action would have failed and signed you out from the dashboard. I changed it [here](https://github.com/flutter/cocoon/pull/2646).

On the web we cannot have custom "sign in" buttons anymore, but something that we could do is to modify that greyed-out button so it says: "PLEASE SIGN IN" or similar (or make the button do a full-page reload, so the auto-sign in works its magic :P).

I don't have a good solution for that UX, short of managing user sessions ourselves and giving you tokens that expire after 100h, rather than 1h :)
