### ISSUE TITLE
Revise message codecs for Dart 2.0 fixed-size integers

### ISSUE THREAD

**Issue by alexmarkov** [flutter/flutter#12976]
In Dart 2.0, int type is going to be a fixed-size 64-bit integer. See https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md for details.

Flutter message codecs support sending/receiving large integers, so we might consider revising this API to better fit fixed-size integers (either drop support for large integers, or use the new Dart [BigInt class](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md#bigints--migration)).

[This change](https://github.com/flutter/flutter/pull/12951/commits/9bb0067ba443e651765e16d6fc72062b84de05db) updates message codecs test to stop using large integer literals (which are illegal in Dart 2.0)

/cc @mravn-google @cbracken @floitschG

**Comment by mravn-google** [comment]
I suggest we drop support for large integers in the codec, as it was included there only because Dart's `int` wasn't fixed size.

What is the timeline for this change to Dart? Is there any real risk that we'll have to back out of it? (I'm trying to understand when it would be a good time to remove the codec's large int support. I want to do it ASAP so that few users will come to depend upon it -- unless we have reason to doubt that the Dart change is going to happen within a reasonable time frame.)

**Comment by alexmarkov** [comment]
Fixed-size integers landed in Flutter: 54052048f2edadb8ca15fdcf778c5f8a3e99e4c6.

Please go ahead with cleaning up the message codec. If you would like to retain the large integers support, you can use Dart [BigInt class](https://github.com/dart-lang/sdk/blob/master/runtime/lib/bigint.dart).

**Comment by Hixie** [comment]
What's the status of this?

**Comment by mravn-google** [comment]
Remaining work is #14069 (making a now deprecated API unavailable).
