### ISSUE TITLE
Removing `presubmit: true` from a CI step in a PR does not launch a job in presubmit

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#129736]
Steps to Reproduce:
* Remove `presubmit: true` from the `Linux web_benchmarks_canvaskit` entry in `.ci.yaml` in the flutter/flutter repo
* Open a PR with this change

Expected Results:
A run of that task should occur on presubmit for the PR

Actual Results:
Task does not run

It seems like the `presubmit: false` might actually need to be committed to master for it to start to run on presubmit. It would be very useful to be able to get tasks to run on a PR in presubmit, even if they are marked as `presubmit: false` on the master branch.

**Comment by keyonghan** [comment]
Presubmit targets are calculated:
1) collect all presubmit: true targets from the current PR/commit
2) collect all presubmit: true targets from TOT commit
3) filter out current commit's targets based on TOT commit's targets.

The purpose above is to exclude TOT `deleted` targets from the current commit, as the corresponding target configs do not exist anymore for deleted targets.

However, the above logic hits the corner case here, where TOT is with `presubmit: false`, whereas the current commit is with `presubmit: true`. This causes the newly enabled target missed in 1), and then missed in 3) for sure.

Instead, we should filter out deleted targets based on TOT's **ALL** targets, rather than the `presubmit: true` targets. This way, we are sure the corresponding configs exist, and at the same time enable the functionality to trigger newly enabled presubmit target.
