### ISSUE TITLE
[palette_generator] Tests only run in vm

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#129839]
Currently the Dart unit tests all use `dart:io` to load test image, which means we need to opt this package out of the new browser mode tests that I'm bringing up in flutter/packages. Since the package itself supports web, the tests should be reworked to not load test files directly from disk.

Once that's done, we can remove the `dart_tests.yaml` from the package, so tests will run on CI.

**Comment by stuartmorgan** [comment]
@ditman Is there a standard way of handling this kind of thing for web tests?

**Comment by ditman** [comment]
> Since the package itself supports web, the tests should be reworked to not load test files directly from disk.

How about replacing this bit:

* https://github.com/flutter/packages/blob/03c73a628bc94c84e98d6221301df2de7b3bcc05/packages/palette_generator/test/palette_generator_test.dart#L45-L49

by reading the image data from its base64 representation, rather than an actual image file? Accessing external assets on the web requires user interaction, so not great for CI. (We can keep two files on the repo so it's very clear that "whatever_image.dart" is the base-64 representation of "whatever_image.png")
