### ISSUE TITLE
Cannot interpolate between finite constraints and unbounded constraints.

### ISSUE THREAD

**Issue by nmahmud19** [flutter/flutter#129998]
Failed assertion: line 482 pos 12: '(a.minWidth.isFinite && b.minWidth.isFinite) || (a.minWidth == double.infinity && b.minWidth == double.infinity)'

**Comment by darshankawar** [comment]
@nmahmud19 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with. Just stating the error message isn't helpful to properly address the issue.

Closing for now. If you have concrete reproducible code sample, please file new issue using template so that we can take a look at it properly.
