### ISSUE TITLE
Animation controller Exception

### ISSUE THREAD

**Issue by Tyga76** [flutter/flutter#129912]
═════════════════════════════════Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
animation_controller.dart:822
2

**Comment by huycozy** [comment]
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See bug template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
