### ISSUE TITLE
[ Can't DownLoad or UpLoad files/attachements ]

### ISSUE THREAD

**Issue by Gobmichet** [flutter/flutter#129943]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just display an URL where a user can DL/UL a file or attachement like a mail client.
click on the link as you would normally do, a mail attachment for exemple.

Just nothing happens :s

### Expected results

expect a Download to start

### Actual results

Nothing at all

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@Gobmichet Thanks for the report, but I am unclear as what exactly the issue is. Are you reporting this against `url_launcher` package ? 
Can you provide us complete minimal reproducible code sample along with `flutter doctor -v` and platform on which you are seeing this behavior, so that we can properly address the reported behavior.
