### ISSUE TITLE
Unable to resubscribe the cancelled plan before it expire - Google play

### ISSUE THREAD

**Issue by Shashwatjxl** [flutter/flutter#130057]
Trying to resubscribe to a cancelled plan before it expires using the same product id, but the google payment gives an error `User is not eligible for this purchase`

### Steps to Reproduce

1. Purchased a new subscription plan using `in_app_purchase` package of flutter
2. Cancelled the active subscription purchased in Step 1.
3. Tried to re-subscribe to the same plan (product ID) before it expires as  described in google [documentation](https://developer.android.com/google/play/billing/subscriptions#before-in-app) for re-subscription. This results in the error `User is not eligible for purchase`.

![Screenshot_20230706-134514_Google Play Store](https://github.com/flutter/flutter/assets/119654455/34e47a8b-c337-42f3-a044-853e74d02587)

**Comment by darshankawar** [comment]
@Shashwatjxl 
This may not be specific to Flutter's in_app_purchase package specifically. 
See [this](https://stackoverflow.com/questions/13747736/user-is-not-eligible-for-this-purchase-in-app-billing#:~:text=The%20actual%20reason%20for%20this,the%20changes%20in%20app%20store.) and check if it helps in your case or not.

Also, see if [this](https://groups.google.com/g/android-developers/c/nPcObpoDM2Q?pli=1) helps.

Closing as the error you are seeing doesn't seem to be due to plugin, but could from google play end. I suggest you to reach out to Google Play support for further resolution.
