### ISSUE TITLE
registerActivityForResult unresolved if MainActivity extends FlutterActivity

### ISSUE THREAD

**Issue by DjordjeMancic97** [flutter/flutter#130044]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Inside MainActivity.kt make MainActivity extend FlutterActivity (there is no problem if it extends FlutterFragmentActivity)
2. Try using "registerActivityForResult"
3. Run the project

### Expected results

I would expect "registerActivityForResult" to work with "FlutterActivity"

### Actual results

Error happens: Unresolved reference: registerForActivityResult

### Code sample

Throws "Unresolved reference: registerForActivityResult"
```
class MainActivity : FlutterActivity() {
    private val mPermissionResult = registerForActivityResult(
        RequestPermission()
    ) { isGranted ->
        println(isGranted.toString())
    }
}
```

Works
```
class MainActivity : FlutterFragmentActivity() {
    private val mPermissionResult = registerForActivityResult(
        RequestPermission()
    ) { isGranted ->
        println(isGranted.toString())
    }
}
```

### Logs

MainActivity.kt: (46, 37): Unresolved reference: registerForActivityResult

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3 22E252 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by huycozy** [comment]
Hi @DjordjeMancic97 
This is intentional because [FlutterActivity](https://cs.opensource.google/flutter/engine/+/master:shell/platform/android/io/flutter/embedding/android/FlutterActivity.java) is being `extends` [Activity](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/Activity.java), not [FragmentActivity](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/fragment/fragment/src/main/java/androidx/fragment/app/FragmentActivity.java). And you can see `registerForActivityResult` is only available with `FragmentActivity` from Android native code.

Closing the issue as above explanation.
