### ISSUE TITLE
Failed assertion: line 1192 pos 7: 'tileWidth != trailingSize.width || tileWidth == 0.0'

### ISSUE THREAD

**Issue by TushalKaklottar** [flutter/flutter#130016]

**Comment by huycozy** [comment]
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion.
