### ISSUE TITLE
 Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not tru

### ISSUE THREAD

**Issue by basm1610** [flutter/flutter#130145]

**Comment by huycozy** [comment]
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion.
