### ISSUE TITLE
Support for flex shrink and flex grow

### ISSUE THREAD

**Issue by 123qws** [flutter/flutter#13022]
Background: I are experimenting server side rendering with Flutter. Basically, The server will return the response in Flexbox spec. Then the response will be translated to Flutter Widgets.

In Flutter, we can specify flex factor via Flexible widget. However, It seems like it just distributes all the *available* space. Does Flutter support specify flex shrink and flex grow factor so we can use different flex factor depends on whether negative or  positive *free* space is distributed?

Thanks!

**Comment by Hixie** [comment]
Can you elaborate on the use case? What effect are you trying to achieve and how do you want to express it?

**Comment by mehmetf** [comment]
@DaveShuckerow could you provide @Hixie with some examples? This is not a particular use case in a single app since we are doing framework -> framework translation here. My guess is that the internal server side rendering framework has a directive that is trying to setup a flex-shrink or flex-grow layout type and we are unable to express that in Flutter.

**Comment by DaveShuckerow** [comment]
This issue is opened on behalf of red, a g3 customer doing a 20% project to explore rendering Flutter UIs from a cross-platform server-side UI protocol.  

From speaking with the red team, their needs for flex_grow are handled properly by `Expanded` in Flutter.

They use flex_shrink primarily to collapse a container to fit to its content.  My understanding of Flutter's Flex implementation is that this is equivalent to MainAxisSize.min.

The ultimate goal on the project is to be able to send protos over the wire describing FlexBox layouts that are equivalent to the Web implementations and be able to render them to widgets both in a web browser and in a mobile app.

**Comment by weisong0** [comment]
Please this [table](https://docs.google.com/document/d/17GoAGcjEQJC4Ak6mptJaK67_qouFzTNqEQHd9NyB6ok/edit#bookmark=id.kfv4r0oqmakg) for details. Basically, red team want flex-basis, flex grow, flex shrink that are similar to the [ones](https://facebook.github.io/react-native/docs/layout-props.html#flexbasis) in react native.

**Comment by mehmetf** [comment]
This is still a potential request from customer: truth.

Their team is investigating using Yoga as a layout engine for Flutter which will solve this problem. However, if we would like them to abandon Yoga for any reason, they will need support for flex shrink and flex grow.

**Comment by eseidelGoogle** [comment]
My understanding is customer: truth has a working prototype with yoga and this is no longer a blocker, is that correct?

**Comment by mehmetf** [comment]
Correct. It is correctly marked as a non-blocker (i.e. no tag).

They are still interested in this in case the Yoga prototype does not pan out so let's keep it open.

**Comment by mehmetf** [comment]
@Hixie We need your opinion/official statement about this. Is supporting Flex layout something that Flutter team will eventually do? If so, is there a timeline? If not, why not?

**Comment by Hixie** [comment]
Supporting CSS specifically is not something we have any plans on doing, because we're not a Web browser, in the same way that we have no plans to support Android layout or iOS layout or Win32 layout etc. We implement Flutter layout.

If there's specific use cases (e.g. "here's a screen that we would like to implement"), then we are definitely open to introducing new layout primitives.

Regarding `Row` and `Column` specifically, we shouldn't add any features to those widgets. They are already too complicated and testing them has become intractable, which is exactly the problem that we set out to avoid with our approach of small reusable composable components (and in explicit contrast to the way the Web layout models work).

That said, it is definitely possible for us to create new widgets that support specific layouts that may be similar to what `Row` and `Column` do, or similar to some feature in CSS or Android layout or whatever. We make those decisions based on concrete use cases (ideally with mockups).

**Comment by matheusribeirozup** [comment]
Hi guys, sorry for the two years delay 😅. Today I published [yoga_engine](https://pub.dev/packages/yoga_engine), a package that uses Yoga to implement Flexbox in Flutter. I hope it's an alternative to your problem. Any questions, suggestions for improvement or bugs found, let me know.

**Comment by Hixie** [comment]
I'm going to close this issue given the low overall interest and high potential cost of adding more features to the Flex widget. However, please don't hesitate to file a new issue if there are specific use cases that can't be implemented today that you would like us to support!
