### ISSUE TITLE
Keyboard Exception Thrown when backspace button is pressed to delete character

### ISSUE THREAD

**Issue by sheby460** [flutter/flutter#130258]
it happens when i press the backspace button to delete some character

**Comment by dam-ease** [comment]
Hi @sheby460 
 
There are also known issues in the database but I'm not sure which one is similar to this. So please try to provide all or some of the information indicated in the template so that we can address this issue properly ([Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

And you should also look through filed issues in this repository (see [flutter/issues](https://github.com/flutter/flutter/issues)) to see if there are any similar issues (reproducibility steps, target environment, stack trace, etc). Once you found it, please close this issue and follow it. Thanks!
