### ISSUE TITLE
Flutter app not running on ios 17 beta

### ISSUE THREAD

**Issue by heshesh2010** [flutter/flutter#130214]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have installed ios 17 beta on real device and upgraded my macos to beta and installed xcode 15 beta 

The app works when run on xcode , but inside vs code it gives me error when build run 

### Actual results

Got error not found device support 

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by Snowden1996** [comment]
When working with beta versions of operating systems, Xcode, and other development tools, it's important to note that there may be compatibility issues and unexpected errors. Here are a few suggestions to help you troubleshoot the issue you're facing when building and running your app in VS Code:

Verify Environment Setup: Double-check that you have properly configured your development environment in VS Code. Ensure you have the necessary extensions and dependencies installed for iOS development, such as the Dart and Flutter extensions.

Update VS Code and Extensions: Make sure you have the latest version of VS Code installed. Additionally, update any installed extensions related to Flutter or iOS development to their latest versions to ensure compatibility with the beta versions of iOS and Xcode.

Check Project Configuration: Review your project's configuration files, such as pubspec.yaml and Info.plist, to ensure they are correctly set up for the beta versions of iOS and Xcode. Verify that the necessary dependencies and settings are properly specified.

Rebuild Dependencies: Try removing your project's pubspec.lock file and the ios/Pods directory, then run flutter pub get and flutter build ios again to rebuild the dependencies. This can help resolve any potential dependency issues that may arise due to the beta environment.

Check Build Settings: Compare the build settings and configurations in Xcode and VS Code to identify any discrepancies. Ensure that the same build settings, provisioning profiles, and code signing identities are used in both environments.

Debugging: Utilize the debugging capabilities of VS Code to gain insights into the error message and understand the specific issue causing the build failure. Check the output and logs provided by the Flutter and iOS build processes to identify any error messages or stack traces.

Community Support: Seek help from the Flutter community and relevant forums or discussion groups. Other developers using the beta versions of iOS and Xcode may have encountered similar issues and may provide insights or workarounds.

Remember, beta versions of software can have unexpected bugs and compatibility issues, which can affect the development experience. It is generally recommended to use stable versions of development tools and operating systems for production projects to minimize such issues.

**Comment by bibaswan-bhawal** [comment]
Great advice in general, but with ios 17 and xcode 15 flutter is actually broken and can only be run from xcode. The new XCode beta changed somethings and moved files that packages flutter uses to build for ios depend on so for the time being until they are fixed only way to run flutter apps on IOS 17 is by running it from xcode and then attaching flutter with ```flutter attach```. 

There is an issue following the resolution of this bug #128531

**Comment by stuartmorgan** [comment]
Closing as a duplicate.
