### ISSUE TITLE
dart-internal engine drones should not show in build dashboard

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#130347]
https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-3.13-candidate.0

Drone builds can have several duplicate results, and are irrelevant to the CI status. For example, the release branch should be completely red, but these give a false positive by showing green.

**Comment by drewroengoogle** [comment]
@CaseyHillers Security has been working on functionality so that dart-internal drone builds appear in the dashboard, instead of having to check two places (flutter-dashboard and the luci console), so it's intended that they are there. Could you clarify what you mean by "False positive"? It seems like those dart-internal builds did succeed.

I'm currently investigating the issue with the duplicate drone builds not showing up in different columns like they should.

**Comment by CaseyHillers** [comment]
>  Could you clarify what you mean by "False positive"?

No build should have successfully ran on these branches as the recipe bundle didn't exist. I filed https://github.com/flutter/flutter/issues/new for tracking that as a separate issue.

Regardless, the drones aren't the final state. A drone build can be retried several times by the parent build, and showing that in the build dashboard will create noise.

Lastly, in the engine v2 world, a given commit will have ~100 drone builds, and showing that all in 3 columns is misleading.

**Comment by drewroengoogle** [comment]
> Regardless, the drones aren't the final state. A drone build can be retried several times by the parent build, and showing that in the build dashboard will create noise.
Is there a frontend change we can make to make it clear that these builds are dart-internal, to avoid the noise? I created https://github.com/flutter/flutter/issues/124632 a while ago but have not determined a good way to do so.

> Lastly, in the engine v2 world, a given commit will have ~100 drone builds, and showing that all in 3 columns is misleading.
This is an issue I'm looking into right now, and is unintended. Each build should have its own column.

**Comment by drewroengoogle** [comment]
@CaseyHillers I thought about it a bit and realized that I don't understand the context around why we decided to publish results on the drones instead of their parent. With that being said, I'm not seeing a reason we couldn't instead publish results after the `release_builder` recipe instead, which is the parent of the entire set. That would also significantly reduce noise, as there would only be 3 results, one for each platform.

**Comment by drewroengoogle** [comment]
The issues that brought about this bug are also related to https://github.com/flutter/flutter/issues/130516, so I will close this in lieu of that issue.
