### ISSUE TITLE
More 32 core Linux VM capacity

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#130362]
Today, I noticed jobs on Engine CI getting cancelled due to queuing while waiting for 32 core Linux machines. Currently, it looks like we have 49 32 core VMs available assigned as follows:

prod: 15
staging: 4
try: 30
total: 49

Would it be possible to increase this to 70 VMs allocated like:

prod: 25
staging: 5
try: 40
total: 70

So 21 more 32 core VMs.

cc @yusuf-goog

**Comment by keyonghan** [comment]
F.Y.I.: there are 20 new 32-core targets enabled in try and 26 new 32-core targets enabled in prod in these weeks (from packages repo). They seem to start affecting the queue time now.

/cc @stuartmorgan I somehow remember you mention something to improve, like sharding? Also wondering how many more 32-core targets we are expecting on the way?

**Comment by yusuf-goog** [comment]
Added in: go/cirgs/6152279

**Comment by yusuf-goog** [comment]
@keyonghan I just increased the capacity. @stuartmorgan can you please take a look and see if we can optimize capacity usage. Do you want me to create a issue tracker for that?

**Comment by stuartmorgan** [comment]
> @stuartmorgan I somehow remember you mention something to improve, like sharding?

I won't be able to evaluate the sharding of the android_platform_test task until the blockers for moving Android unit and integration tests from Cirrus to LUCI are resolved.

> Also wondering how many more 32-core targets we are expecting on the way?

No new ones are planned (modulo the above), but runtime on the 12(?) android_platform_test tasks will increase when unit and integration tests migrate.

> @stuartmorgan can you please take a look and see if we can optimize capacity usage

As I mentioned earlier, I would need someone to point me to tools for understanding the machine utilization. For Cirrus it was very easy to figure out when we needed to move tasks between light and heavy machine configs because every run has CPU and memory utilization graphs ([example](https://cirrus-ci.com/task/5492525805338624)). What's the equivalent for LUCI that would let me evaluate the current setup?

**Comment by keyonghan** [comment]
Thanks @stuartmorgan for the clarification. Considering we had only <10 targets needing 32-core bots before, I am not sure if the proposed capacity increase here is enough. I will need more data to confirm. Before that, let's land the capacity CL to unblock the engine tree. At the same time, let's keep monitoring a bit.

**Comment by yusuf-goog** [comment]
New hosts are deployed

**Comment by stuartmorgan** [comment]
FYI I ran some timing tests over the weekend, and I don't see any evidence that the use of 32-core machines in flutter/packages is actually making a meaningful difference in run times, so I am converting all of the flutter/packages configurations to 8-core.

**Comment by keyonghan** [comment]
> FYI I ran some timing tests over the weekend, and I don't see any evidence that the use of 32-core machines in flutter/packages is actually making a meaningful difference in run times, so I am converting all of the flutter/packages configurations to 8-core.

Thanks for the heads up @stuartmorgan . This is good to know, and surely will help with the 32-core queue time.
