### ISSUE TITLE
about onGenerateRoute, when using pushNamedAndRemoveUntil & ModalRoute.withName

### ISSUE THREAD

**Issue by ahmeddarafat** [flutter/flutter#130356]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The problem is that if you use onGenerateRoute to create named routes you won't be able to get the name of that route from RouteSettings object in your page.
so methods like 
1. pushNamedAndRemoveUntil
2. popUntil
doesn't work with onGenerateRoute because It needs the name of the page

### Expected results

no need

### Actual results

no need

### Code sample

no need

### Flutter Doctor output

no need

**Comment by huycozy** [comment]
Hi @ahmeddarafat 
When opening an issue, please try to provide all or as much information as possible indicated in the template so that we can address this issue properly. 

In this case, please provide:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Expected results, Actual results

Thank you!
