### ISSUE TITLE
MacOs impeller-jank

### ISSUE THREAD

**Issue by mendoxe** [flutter/flutter#130439]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am experiencing junk mainly when working with a data table with approximately 10-20 columns and 20-30 rows. 

The UI is more complex, with a side panel and a simple appbar, but it is the data table that is making the performance graph spike. The cells are texts and change to a text field when clicked on.

I am working on an
14" MacBook Pro
M2 Max
32 GB Ram
MacOS 13.4.1

### Expected results

I was experiencing similar junk without the impeller enabled as well, but it seems to be slightly worse with impeller.

### Actual results

The UI is responsive most of the time, but the dev tools show junk, and the data table is expected to be a lot larger.

### Code sample

Unfortunately I cannot share the code.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.13.0-3.0.pre.7, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by jonahwilliams** [comment]
We need either examples of the code that is slow, timeline traces saved from devtools, screenshots/videos, et cetera.

A vague description of what the UI is doing isn't actionable.

**Comment by leighajarett** [comment]
I have the devtools trace, will email you! @jonahwilliams

**Comment by mendoxe** [comment]
I am working with Leigha Jarett. Sorry for the incompleteness, as I only have measurements from dev tools and was unable to upload them into the issue. Just sent them by email.

**Comment by jonahwilliams** [comment]
FYI you can upload a timeline to github by zipping it up.

**Comment by jonahwilliams** [comment]
I'm looking through the timeline trace and I don't see a single frame missed due to raster time, are you sure this is the correct timeline?

**Comment by mendoxe** [comment]
I am sending a few measurements I have made. As I mentioned the app does not freeze or anything extreme, but the timeline showed a lot of 'Red Columns', which I expected to symbolize something might be wrong.

[Archive.zip](https://github.com/flutter/flutter/files/12033039/Archive.zip)

**Comment by dnfield** [comment]
@mendoxe - the trace in there seems to have some issues (for example there is an event in there that seems to be taking a minute or more for dispatch pointer data packet which has a lot of nested frame events and would indicate some kind of corruption in the file).

It looks like you have a lot of UI thread jank there, which is not specific to impeller - you may just be doing too much work on the UI thread (some frames are taking 26 or more ms for example to run the Dart code on the UI thread). 

One possible cause of this is if you're running devtools while you are interacting with the app - it will periodically request more timeline data which can itself cause jank in the app. 

Since this is not an impeller specific bug I'm going to close it. If you have something more to share about getting 25ms+ UI frames on macOS it may be worth filing another issue for that.
