### ISSUE TITLE
[ WEBVIEW_WEB ], detect navigation on on the iframe 

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#130487]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.  add any submit button that will navigate the user to a page on the web
we want to detect where it will redirect the user and other it will redirect or not 

this is the issue 
Another exception was thrown: UnimplementedError: createPlatformNavigationDelegate is not implemented on the current platform.

### Expected results

to show a button that an action has been completed by URL or show pop up message, or even renavigate the user to a place 

### Actual results

Another exception was thrown: UnimplementedError: createPlatformNavigationDelegate is not implemented on the current platform.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @nimr77. Thanks for filing this issue. please can you try to provide some more information indicated in the template so that we can address this issue properly.

More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps
- If possible/ applicable, screenshots/video

Thank you!
