### ISSUE TITLE
SelectionArea doesn't allow user to select the first TextSpan

### ISSUE THREAD

**Issue by daohoangson** [flutter/flutter#130427]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample code in dartpad.dev
2. Drag over `Lorem` to select it

### Expected results

- The word is selected

### Actual results

- It is not selected.

### Code sample

https://dartpad.dev/?id=76db6a5a5629b306b0d00fcf8c773f81

### Screenshots or Video

<details>
<summary>Screenshot</summary>

<img width="1436" alt="Screen Shot 2023-07-13 at 01 24 21" src="https://github.com/flutter/flutter/assets/239336/ce40b19f-6105-4389-bf9f-3d844ba4dc66">

</details>

### Logs

No logs.

### Flutter Doctor output

No doctor output.

**Comment by darshankawar** [comment]
Thanks for the report @daohoangson 
I verified this using latest master and stable and observed that on web and desktop, the reported behavior occurs but only on stable. If you run the scenario on latest master on both platforms, you'll notice that it works as expected.

<img width="434" alt="Screenshot 2023-07-13 at 12 05 51 PM" src="https://github.com/flutter/flutter/assets/67046386/322fb36d-bd51-4231-9d1f-96be1279db5b">

Since it works properly on latest master, I'll consider this as fixed already and will close.
