### ISSUE TITLE
exception with the cloud_firestore plugin when trying to read a `timestamp` field type

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#13043]
When trying to read a field from a firebase database having the type `timestamp`, I see the following exception:

```
E/AndroidRuntime( 7430): java.lang.IllegalArgumentException: Unsupported value: Tue Jan 23 10:40:00 PST 2018
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:250)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:239)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:31)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
E/AndroidRuntime( 7430): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:69)
E/AndroidRuntime( 7430): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:162)
E/AndroidRuntime( 7430): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:113)
E/AndroidRuntime( 7430): 	at com.google.firebase.firestore.zzi.onEvent(Unknown Source)
```

**Comment by devoncarew** [comment]
Also, this exception seems to crash the app completely (at least on Android emulators). We may want some want to catch exceptions from the plugin side and give the flutter code a chance to deal with them?

/cc @collinjackson re: the issue deserializing `timestamp` fields

**Comment by devoncarew** [comment]
And, /cc @mravn-google re: the plugin exception crashing the app

**Comment by Skylled** [comment]
Related: #12437, #12468, #12784, #12989

**Comment by mravn-google** [comment]
Attempting to encode an unsupported value constitutes a programming error, no different from dereferencing `null`. The result is also the same: a `RuntimeException` being thrown. It is not at all clear what the Flutter side should do in that case, or why it should be involved.

If the plugin's event observer cannot survive a runtime exception, and also cannot guarantee that all values to be encoded are supported, then I think it should contain the necessary logic to avoid or catch that exception.

**Comment by Skylled** [comment]
@pauldemarco had [begun work](https://github.com/pauldemarco/plugins) on a solution that involved designing an extended version of the [FlutterMethodCodec](https://github.com/pauldemarco/plugins/blob/fed3f1201583e122144f65e0a2da017e2f120fde/packages/firebase_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FirestoreMessageCodec.java).

**Comment by arcas0803** [comment]
Same error.
The real problem is that i have change my database to remove timestamp values and the error still fires.
`E/AndroidRuntime(11043): FATAL EXCEPTION: main
E/AndroidRuntime(11043): Process: com.irri.irri, PID: 11043
E/AndroidRuntime(11043): java.lang.IllegalArgumentException: Unsupported value: Tue Nov 21 12:45:00 GMT+01:00 2017
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:250)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:239)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:239)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:31)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
E/AndroidRuntime(11043): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:69)
E/AndroidRuntime(11043): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:162)
E/AndroidRuntime(11043): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:113)
E/AndroidRuntime(11043): 	at com.google.firebase.firestore.zzi.onEvent(Unknown Source)
E/AndroidRuntime(11043): 	at com.google.android.gms.internal.zzejz.zza(Unknown Source)
E/AndroidRuntime(11043): 	at com.google.android.gms.internal.zzeka.run(Unknown Source)
E/AndroidRuntime(11043): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(11043): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(11043): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(11043): 	at android.app.ActivityThread.main(ActivityThread.java:6126)
E/AndroidRuntime(11043): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11043): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(11043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
I/Process (11043): Sending signal. PID: 11043 SIG: 9`

**Comment by arcas0803** [comment]
Any progress?

**Comment by varunvairavan** [comment]
Just hit the timestamp serialisation issue. Is the pull request for android ready to be used?

**Comment by Purus** [comment]
Friendly ping :)

**Comment by lucamtudor** [comment]
any progress?

**Comment by kenticus** [comment]
Same here. Currently a blocker for me.

**Comment by lucamtudor** [comment]
@sethladd do you guys have this on the roadmap? timestamps are a blocker right now... thanks!

**Comment by arrowoliver** [comment]
i hope this is going to be fixed soon

**Comment by kroikie** [comment]
@devoncarew

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/940. Any further collaboration will be done there.
