### ISSUE TITLE
dart-internal builds are not running on RC branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#130516]
See https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-3.13-candidate.3

Most of the release builders are not showing, which prevents us from shipping releases to Google.

**Comment by CaseyHillers** [comment]
Temporarily assigning to myself while I find an owner. This seems related to recent dart-internal changes (\cc @keyonghan @drewroengoogle @sealesj )

**Comment by CaseyHillers** [comment]
One change seems to be that everything is nested under a parent builder, `Linux|Windows|Mac engine_release_builder`, but they do not show on the build dashboard until they pass. It looks like failed runs may not show at all.

A few possible AIs:

* Unnest this builder in the build dashboard (show the sub builds)
* Update the release + roll playbooks and send PSA to the team about the changes
* Use pubsub to show the dart-internal builds at every stage, instead of only completed

**Comment by drewroengoogle** [comment]
@CaseyHillers I'll assign it to myself. We switched over this morning from publishing at the drone level to the release_builder level. It looks like it is only publishing for successful builds like you mentioned above.

I think those are good action items that you've provided. A couple of changes are needed to both the recipes and cocoon to address those action items:
* For recipes, publish the build when it starts, and also publish even if it fails
* For recipes, publish at the drone level for builds that are responsible for orchestrating the build drones. Since all of these are called `Linux|Windows|Mac Production Engine Drone`, we will need to pass an additional parameter with a custom build name from the build properties so that it is clear what each drone is responsible for. For cocoon, update the pubsub endpoint to handle a custom build name being passed, and then update the logic on the dashboard frontend to still navigate to the correct build.
* For cocoon, the initial simplest goal to reach was to only report completed builds, so the logic will need to be updated so that we report regardless of if it is in progress or not.

**Comment by CaseyHillers** [comment]
To clarify the P0 status here, I was able to submit https://github.com/flutter/flutter/pull/130518 and I'm not radically blocked. However, in the next week we should have a solution that is clear to people running releases.

I'm still adapting to the new [triage process](https://flutter.dev/go/triage-2023-rfc) but I think that means P0.

**Comment by drewroengoogle** [comment]
I'm lowering the priority to P1 to align with the triage process, because these builds are still accessible via the dart-internal consoles, but this is being actively worked on.

**Comment by XilaiZhang** [comment]
from triage: what's left to be done?

**Comment by drewroengoogle** [comment]
It looks like builds are processing correctly now, so this can be closed! I just wanted to keep it open to watch some commits, which have all been successful.
