### ISSUE TITLE
crash when press back button at splash screen on Android

### ISSUE THREAD

**Issue by jinguoliang** [flutter/flutter#130564]
Os System：Android 8.1，Pixel C
Futter Version：3.10.5
the log：

A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#b63f8(physicalKey: PhysicalKeyboardKey#3b725(usbHidUsage: "0x1100000004", debugName: "Key with ID 0x1100000004"), logicalKey: LogicalKeyboardKey#5dfc4(keyId: "0x100001005", keyLabel: "Go Back", debugName: "Go Back"), character: null, timeStamp: 0:00:05.471360)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 434 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by huycozy** [comment]
Hi @jinguoliang 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

With regard to this issue, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. It would be appreciated if you can provide it in a GitHub repository.
- The output of `flutter run -v`
- Reproduction steps

Thank you!
