### ISSUE TITLE
ImageProvider hierarchy has very confused documentation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#130524]
`DecoderCallback` has API docs saying to use `ImageProvider.loadBuffer` but the deprecated annotation says to use `ImageProvider.loadImage`. `ImageProvider.load` has API docs saying to `loadBuffer` is preferred but an annotation that says to use `loadImage`. `loadBuffer` is itself deprecated and says to use `loadImage`. On the other hand, `AssetBundleImageProvider` implements all three. The documentation for ImageProvider itself says that we use `loadBuffer`.

cc @tvolkert @jonahwilliams

**Comment by jonahwilliams** [comment]
Uhh, so this is what happened. I deprecated load to use loadBuffer, as that avoids some extra copies. But then before that deprecation period was elapsed @tvolkert added a new image load API that in theory depercates both load and loadBuffer.

The fix is to point all deprecation messages at the new implementation. I'll take a look at fixing this.
