### ISSUE TITLE
FR: Provide access to Material Responsive UI breakpoints

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter#13055]
https://material.io/guidelines/layout/responsive-ui.html outlines layout guidelines for various screen sizes.

Flutter should provide access to this data based on the screen size provided by MediaQueryData. One possible design could be

```dart
enum MobileDeviceType {handset, tablet}
enum MobileDeviceSize {small, medium, large}

class MaterialResponsiveUiData {
  static MaterialResponsiveUiData of(BuildContext context) {
     // calls MediaQuery.of(context) and computes various fields, or stores MediaQueryData
     // and computes on demand
  }
  MobileDeviceType deviceType;
  MobileDeviceSize deviceSize;
  int columns;
  double gutter;
}
```

Our project could us the gutter definition, as well as MobileDeviceType to implement different behavior depending on whether the device is regarded as a handset or a tablet.

I would be contribute PR to implement this.

**Comment by Levi-Lesches** [comment]
In case anyone stumbles upon this, there's the [`adaptive_breakpoints`](https://pub.dev/packages/adaptive_breakpoints) package by the Material Design team that does exactly this.

**Comment by youssef-attia** [comment]
Similar behavior is added in a package referenced in this [PR](https://github.com/flutter/packages/pull/2377). The package offered by material mentioned earlier seems to also provide this functionality. I don't believe there are currently any plans to add this functionality directly to the framework due to the opinionated nature so I'm closing this issue for now. If anyone else has further input, feel free to reopen.
