### ISSUE TITLE
ElementLifecycle.defunct

### ISSUE THREAD

**Issue by Polibuzz** [flutter/flutter#130659]
I'm getting the following error when running my Flutter app, and it said to report it as a bug.

The following assertion was thrown while finalizing the widget tree:
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4622 pos 12: '_lifecycleState
flutter: != _ElementLifecycle.defunct': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:

**Comment by danagbemava-nc** [comment]
Hi @Polibuzz, please provide a complete minimal reproducible code sample so that we can investigate this. 
Please also provide the output of `flutter doctor -v`.

This error usually indicates that you're calling setState after a widget has been disposed. You'll need to check if the widget is mounted before you can call setState in that case by doing something like

```
if(mounted) {
	setState(() {});
}
```
