### ISSUE TITLE
Rotation on iOS issue

### ISSUE THREAD

**Issue by MariuzM** [flutter/flutter#130655]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

This is related to:
https://github.com/flutter/flutter/issues/16322
https://github.com/flutter/flutter/issues/108360

I'm still getting this same issue on latest `3.10.5` `flutter create <APP_NAME>`. Is Flutter team looking into this? Those other threads have been closed and no info from Flutter team about this.... ? 

### Proposal

Fix the issue?

**Comment by danagbemava-nc** [comment]
HI @MariuzM, #16322 was closed because a fix is on the `master/main` channel. In the flutter repo, issues are closed when they are fixed on the `master/main` channel not when it lands in `stable`. 

Can you check on the `master` channel to see if the bug still persists? If it does, please provide the version of the `master/main` channel that you tested on. 

Thank you

**Comment by MariuzM** [comment]
> HI @MariuzM, #16322 was closed because a fix is on the `master/main` channel. In the flutter repo, issues are closed when they are fixed on the `master/main` channel not when it lands in `stable`.
> 
> Can you check on the `master` channel to see if the bug still persists? If it does, please provide the version of the `master/main` channel that you tested on.
> 
> Thank you

Oh nice, sorry i missed this part, could you let me know when will this lands in stable?

**Comment by danagbemava-nc** [comment]
Kindly see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels our release process. There's a chance that this fix will be available in the next stable release. 
The current "fix" is based on how we presume apple implements the rotation so there's a chance that it may or may not match your expectations. We would appreciate it if you could test this out on the master/beta channels and file any bugs with the appearance so that we can get it closer to the native feel. 

For now, I will be closing this issue since the reason for filing the issue has been satisfied.
