### ISSUE TITLE
Confusing Flutter error message when Xcode installation is incomplete

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#13063]
## Steps to Reproduce

Reported on Gitter: During installation of Flutter on a new MacBook, install Xcode, but skip the step of launching the iOS Simulator. Then `simctl` doesn't work, and `flutter doctor` reports e.g.

```text
[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1
```
but then
```text
Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found
```
From this error message, it is not very clear that the solution is to launch the Simulator to force the installation of the missing components.

The error message also seems to appear, if iOS tooling isn't set up at all, see https://github.com/flutter/flutter/issues/13030

**Comment by mravn-google** [comment]
cc @xster

**Comment by xster** [comment]
Didn't even know we had a step to have people open the simulator for the first time :)

**Comment by hanifibadur** [comment]
I just switching to my new macbook and I can confirm that this problem happened on me. I was thinking to reinstall the xcode because of that error message until I found in this issue page how to resolve it by just opening the xcode (no need to open simulator, just open the xcode and let it download additional package).

**Comment by xster** [comment]
Minor caveat: this error only shows if xcode is installed and not run and flutter is installed but not homebrew. Since homebrew forces the installation of Xcode command line tools via `/usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ High\ Sierra\ version\ 10.13)\ for\ Xcode-9.2` which solves this, I think the better solution is to just move the check for homebrew earlier. 

This also solves the need for `sudo DevToolsSecurity -enable` which homebrew does as well

**Comment by xster** [comment]
Otherwise, we shouldn't try to list devices until the Xcode installation is complete (and that determination should include installing homebrew)

**Comment by cbracken** [comment]
Discussing with @xster, we think it makes sense to do two things here:
1. Better message when simctl doesn't work.
2. Review steps to get simctl to run in `flutter doctor` since this tooling has changed a bit with Xcode 9.

**Comment by jonahwilliams** [comment]
@xster If you're not currently looking at this I can work on it today

**Comment by xster** [comment]
@jonahwilliams ah cool, I'm likely not getting to in within a week.

From a quick check last time, I think the check we used to make to assert that Xcode's additional components are installed are no longer valid in 10.13 / Xcode 9.2. We should also stop attempting to simctl and find out how many iOS devices are connected when Xcode isn't completely installed.

**Comment by jonahwilliams** [comment]
It looks like there isn't a good way to verify that simctl will work without just running it and looking for an error.
