### ISSUE TITLE
For Windows

### ISSUE THREAD

**Issue by SofhiaziziCool** [flutter/flutter#130664]
Mine it appeared "Access is denied", may I know to counter this ?

 For Windows 
Go To android studio directory (Default C:\Program Files\Android\Android Studio)
remove jre folder
run cmd as administrator

```
cd C:\Program Files\Android\Android Studio
mklink /D "jre" "jbr"

```
Now all is working again.

_Originally posted by @mstfkhazaal in https://github.com/flutter/flutter/issues/106674#issuecomment-1381685888_

**Comment by mstfkhazaal** [comment]
> Mine it appeared "Access is denied", may I know to counter this ?
> 
> For Windows Go To android studio directory (Default C:\Program Files\Android\Android Studio) remove jre folder run cmd as administrator
> 
> ```
> cd C:\Program Files\Android\Android Studio
> mklink /D "jre" "jbr"
> ```
> 
> Now all is working again.
> 
> _Originally posted by @mstfkhazaal in [#106674 (comment)](https://github.com/flutter/flutter/issues/106674#issuecomment-1381685888)_

Are you sure to run cmd as administrator?

**Comment by huycozy** [comment]
Hi @SofhiaziziCool 
When opening a new issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See [bug report template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

More specifically on this case, please provide the complete output of `flutter doctor -v`.

**Comment by SofhiaziziCool** [comment]
Greetings,

Thank you for your reply, thankfully the issue has been resolved.
