### ISSUE TITLE
unregistered_view_type

### ISSUE THREAD

**Issue by SauravSCC** [flutter/flutter#131054]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

unregistered_view_type, A HtmlElementView widget is trying to create a platform view with an unregistered type: <osm_web_plugin_0>., If you are the author of the PlatformView, make sure `registerViewFactory` is invoked., null

### Actual results

unregistered_view_type, A HtmlElementView widget is trying to create a platform view with an unregistered type: <osm_web_plugin_0>., If you are the author of the PlatformView, make sure `registerViewFactory` is invoked., null

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SauravSCC, the error seems to be from a third-party plugin. You should report this on their repo. 

If you are using the `flutter_osm_plugin`, a similar issue has already been filed on their repo. 

Closing as this is not related to any of the plugins on this repo. 

If you disagree, kindly leave the code sample you're experiencing the issue with without any third-party plugins so that we can investigate this issue. 

Thank you
