### ISSUE TITLE
How to change the `minSdkVersion `  when creating a module

### ISSUE THREAD

**Issue by joker-fu** [flutter/flutter#131039]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I already modify like this, but after doing `flutter get`, the `minSdkVersion `  is still 16. 

![image](https://github.com/flutter/flutter/assets/20105457/e25b887a-0dce-4dc9-95af-ad014599fffc)

![image](https://github.com/flutter/flutter/assets/20105457/45144a06-ad58-4cf9-97d9-4a36aaf74196)

### Actual results

I don't want to modify the module file "build.gradle.tmpl".

![image](https://github.com/flutter/flutter/assets/20105457/09a2691e-c139-4121-9c56-06ee298df877)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [版本 10.0.22621.1992], locale zh-CN)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

**Comment by maRci002** [comment]
When you modify `flutter\packages\flutter_tools\lib\src\android\gradle_utils.dart`, you need to remove `flutter\bin\cache\flutter_tools.stamp` and then run `flutter doctor` to rebuild `flutter_tools` with your modifications.
Source: https://stackoverflow.com/a/66879350/4609658

Anyway, you shouldn't modify `flutter_tools` because when you upgrade your Flutter, you will have to repeat the above steps. Instead, you should do something like this in your project's `build.gradle` file:
`minSdkVersion Math.max(21, flutter.minSdkVersion)`

**Comment by joker-fu** [comment]
@maRci002  

Thanks for your answer, it works well now. 

I know the problems when upgrading Flutter.  I wonder why it didn't take effect, it's fine now.
