### ISSUE TITLE
After update flutter version in_app_purchase does not return price, only return "Free" word only for android below version 12. But ios working fine and return price properly.

### ISSUE THREAD

**Issue by gitcoder-23** [flutter/flutter#131146]
After update flutter version in_app_purchase does not return price, only return "Free" word only for android below version 12. But ios working fine and return price properly.
In Android version 11, 10 and below android version only return "Free" when i am using data of ProductDetails and using price.

Price must be displayed here not free.
I am using

in_app_purchase: 3.0.8 (same issue happened)
When update to - in_app_purchase: 3.1.7 (same issue happened)

Till i am not getting any solution. It happens only in Android not ios device. Please anybody help.

![free_wise_android](https://github.com/flutter/flutter/assets/68274519/be91a057-7a88-4677-9e94-ab5c53dc0668)

**Comment by gitcoder-23** [comment]
When i am using "rawPrice" instead "price" displayed 0.0 price , price not displayed properly in below Android version 12.
I mean in Android 11, 10, 9 and below Android version. But Android version 12 and upper in_app_purchase is working fine. Price properly displayed. Please help me by reply. And help me to provide solutions.



![row_price_wise](https://github.com/flutter/flutter/assets/68274519/568ce68a-60fa-4391-a5a4-1d85e0e845c6)

**Comment by darshankawar** [comment]
@gitcoder-23 

When you say that the package is returning only free data for Android version below 12, I don't see any [changes](https://pub.dev/packages/in_app_purchase/changelog) related to the package itself that'll differentiate between Android 12 and below, so you may need to check from Android release notes perspective to see if there's any changes made from OS version level that could be affecting the behavior you are reporting.

Also, since this repo is used to track bugs and feature requests, asking for help with providing screenshots won't help much without providing details such as code sample, so provide us complete minimal reproducible code sample that shows the reported behavior.
