### ISSUE TITLE
lib/news_data.dart   (Inverted Commas Missed)

### ISSUE THREAD

**Issue by dev-aliawan** [flutter/flutter#131262]
class NewsArticle {
  final String title;
  final String description;
  final String? articleText;

  NewsArticle({
    required this.title,
    required this.description,
    this.articleText = "loremIpsum",                    // here you missed to insert inverted commas
  });

**Comment by dam-ease** [comment]
Hi @dev-aliawan 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Please update the issue with these information and write in the comments for further discussion. 
Thanks!

**Comment by dam-ease** [comment]
Hi @dev-aliawan. Are you making reference to `News Toolkit`?? If yes, I can't seem to find an exact file with the path `lib/news_data.dart`. Please when filing an issue, kindly try to provide complete and all information needed for the issue to be workable.
