### ISSUE TITLE
i have try to navigate screen then show me this error??

### ISSUE THREAD

**Issue by afaqnoor** [flutter/flutter#131252]
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5235 pos 12: '_history.isNotEmpty': is not true.

**Comment by dam-ease** [comment]
Hi @afaqnoor 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Also, from the line of error provided, this issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and ask questions like this, you may also get some help if you post it on Stack Overflow.

I am closing this issue since little or no information has been provided. If you disagree, kindly update issue with more information, also please write in the comments and I will re-open this for further discussion. Thanks!
