### ISSUE TITLE
Plugin url_launcher shows blank page on dismiss

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#13123]
## Steps to Reproduce
Android:
1. Launch this [url](https://twitter.com/DrDisRespect/status/932278565822906368) with forceWebView: true
2. Click the back button to return to app
3. Observe it exit to a blank white page
4. Click the back button again to finally return to app

I've only tested on Android (Samsung S6).

**Comment by sethladd** [comment]
Thanks for the report! How critical (or not) is this for you?

**Comment by pauldemarco** [comment]
Not too critical, I've just had some user's express that they'd like all links to launch in-app.  External launching will do just fine in the meantime.

**Comment by mit-mit** [comment]
cc @mehmetf

**Comment by Hixie** [comment]
(Removing "critical" label per @pauldemarco's last comment; ping me if that was wrong.)

**Comment by mehmetf** [comment]
The reason for this is that the URL is redirecting to a different page which actually opens in browser (rather than webview). So when user taps back, the browser closes but webview is not displaying any page (so it is blank).

To fix this, we need to open links in the webview as well as handling the history. On it.

**Comment by w4mxl** [comment]
**url_launcher: ^5.0.2**
I have encountered the same issue as @pauldemarco.
I tested several URLs，The result is the same.
