### ISSUE TITLE
i dont know.. what happend here.. i only create class appbar and this eror show up.. help me sir

### ISSUE THREAD

**Issue by lutfiseptian** [flutter/flutter#131456]
```
'package:flutter/src/widgets/app.dart':
Failed assertion: line 376 pos 10: '(home != null ||
          routes.isNotEmpty ||
          onGenerateRoute != null ||
          onUnknownRoute != null)
         ||
         (builder != null &&
          navigatorKey == null &&
          initialRoute == null &&
          navigatorObservers.isEmpty)'
```

**Comment by darshankawar** [comment]
@lutfiseptian 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough info to work with. Only providing error log won't help much.
Closing for now due to lack of details. If you have concrete steps to replicate along with minimal code sample that throws this error, open new issue so that we can address it properly.
