### ISSUE TITLE
[Impeller] Parts of application flickering with blur present on main.

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#131490]
We have parts of application flickering with blur present when tested on main. Though it's possible that the blur causes the issue indirectly by making the rasterisation taking longer.

https://github.com/flutter/flutter/assets/96958/27c2318c-0438-4a70-b8a5-0b6b1b96e885

Bistected down to https://github.com/flutter/engine/commit/8e6497fa9bd20339cb452e0e2899368d373ff468. 
When reenabling the wait for command buffer the issue resolves.

The commit also causes another problem - when application goes to background while scrolling it crashes with
```
-[MTLDebugCommandBuffer dealloc]:136: failed assertion `MTLCommandBuffer is in an invalid status when being destroyed; is it being over-released?'
```
This doesn't happens when waiting until the command buffer gets schedule. cc @jonahwilliams

_Originally posted by @knopp in https://github.com/flutter/flutter/issues/127173#issuecomment-1655837933_

**Comment by knopp** [comment]
For reference, this is on iPhone 13 Pro.

**Comment by jonahwilliams** [comment]
Can you share some details of the application? We really need to be able to reproduce this so we can figure out where the problem is occuring.

My read of how presentation works on iOS supports the current strategy we're using and I none of us have seen this issue, even on applications which have much longer CPU or GPU frame times. It could be that there is some other timing issue, and the waitUntilScheduled is acting like a sleep and causing us to win the race.

**Comment by knopp** [comment]
I'll try to isolate this. One thing I noticed - there are two blurs in the application. I disabled all paths (to rule out tesselator) but the performance is still problematic with impeller (fine with Skia)

I noticed quite a few allocations when rendering offscreen. This is for one second:

<img width="713" alt="Screenshot 2023-07-28 at 18 48 08" src="https://github.com/flutter/flutter/assets/96958/50570020-e8d7-4596-a4da-0fd0fa20733e">

For every frame there is one 12MB ImpellerOnScreen Stencil Texture allocated/deallocated and a number of EntityPass Color textures (1.8MB each).

Is this expected behavior? These per-frame allocations don't happen with Skia. I assume it caches the textures used for offscreen rendering.

**Comment by bdero** [comment]
When blurs are applied as backdrop filters specifically, we currently need to end the current render pass in order to read from the backdrop in order to blur it into a smaller offscreen texture. This requires us to also store the multisample stencil in-between passes in order to retain the clip state after the blur has been drawn.

The best way forward would be to share a reproduction that demonstrates clearly worse performance than Skia (in a new issue) so that we can take a closer look. There are still potential optimization tricks on the table for backdrop blurs that we could explore depending on how the app is using blurs.

**Comment by bdero** [comment]
It sounds like you're hitting a worst case scenario with the backdrop filter and we're allocating/storing the fullscreen multisample stencil buffer every frame. I think we can obviously do better there, but it would be best to have a repro of your app to make sure that's the primary pathology of your perf issue.

**Comment by knopp** [comment]
I understand the need for these textures, just expected them to be reused across frames. I'll try to put together minimal reproducible example.

**Comment by knopp** [comment]
The following code can reproduce (iPhone 13 Pro, profile mode, current main) both the flickering and degraded performance  compared to skia:

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class _Blur extends StatelessWidget {
  const _Blur();

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      child: BackdropFilter(
        blendMode: BlendMode.srcIn,
        filter: ImageFilter.blur(
          sigmaX: Shadow.convertRadiusToSigma(80),
          sigmaY: Shadow.convertRadiusToSigma(80),
        ),
        child: Container(
          color: Colors.red.withAlpha(30),
          child: const Text('Blur'),
        ),
      ),
    );
  }
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            ListView.builder(
                itemBuilder: (context, index) {
                  return Container(
                    padding: const EdgeInsets.all(10),
                    child: Text('Item $index'),
                  );
                },
                itemCount: 1000),
            for (var i = 0; i < 4; ++i)
              Positioned(
                left: 0,
                right: 0,
                top: i * 200,
                height: 100,
                child: const _Blur(),
              ),
          ],
        ),
      ),
    );
  }
}
```


https://github.com/flutter/flutter/assets/96958/405f174f-d58e-40b6-a0a1-a1017745f40a

**Comment by jonahwilliams** [comment]
Thanks! I have a few ideas here. Worst comes to worst we can just add back the waitUntilScheduled but I think we should be able to retain having more frames in flight for applications that aren't bottlenecked elsewhere.
