### ISSUE TITLE
20% hot reload benchmarks regression on Dart roll 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131446]
https://flutter-flutter-perf.skia.org/e/?begin=1690415288&end=1690495744&keys=X6959ede456befbb073f0c12a7fe63d78&selected=commit%3D35993%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DhotReloadMillisecondsToFrameAfterChange%252Ctest%253Dhot_mode_dev_cycle__benchmark%252C&xbaroffset=35993

Seems like across the board there was a 20% regression. This happened on the manual dart roll here:

https://github.com/flutter/flutter/pull/131371

**Comment by a-siva** [comment]
The Dart changes that went in during this time are https://dart.googlesource.com/sdk.git/+log/b1e82e2e55b2..b5710782b91c

The one change that probably caused this is
6ef967f [vm, reload] Delay enum forwarding until after instance morphing. by Ryan Macnak · 2 days ago
(https://dart-review.googlesource.com/c/sdk/+/316041, this change was reverted and reapplied at https://dart-review.googlesource.com/c/sdk/+/316501)

This was a correctness fix and would have impact on reloads done with shape changes

The trade off here is crashes during hot reloading Vs this regression because of the additional pass

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by rmacnak-google** [comment]
Yes, the correctness fix involves an extra O(heap) step, so 20% isn't surprising.

**Comment by alexmarkov** [comment]
@rmacnak-google Can we avoid this extra heap iteration? Maybe we can special case canonicalization of enum constants to avoid depending on the contents of instances, and still forward them along with other objects.

**Comment by zanderso** [comment]
Re-opening for the question from @alexmarkov

**Comment by rmacnak-google** [comment]
There was such a special case before the "enhanced enums" changes: enums had only name/String and index/Smi fields that could not involve a shape change. But merely running the constant evaluator is unsafe with a pending shape change now since that runs canonicalization for each intermediate object, possibly one with a shape change.

In the absence of a shape change, or a shape change with no live instances, the become operation for the shape change should be a no-op and the enum forwarding should already be folded into the same become operation as class/library forwarding.

**Comment by alexmarkov** [comment]
During hot reload, can we create placeholder empty objects for new enum values (only initializing index and maybe name), migrate old -> new objects on the heap and then fill in those empty objects with real contents by reading it from kernel?

**Comment by jonahwilliams** [comment]
I'm not sure what constitutes a state change. The benchmarks measure three different source code changes:


1. https://github.com/flutter/flutter/blob/master/dev/integration_tests/flutter_gallery/lib/gallery/app.dart#L148 The string is changed from 'Flutter Gallery' to 'Updated Flutter gallery'

2. https://github.com/flutter/flutter/blob/master/dev/integration_tests/flutter_gallery/lib/demo/calculator/home.dart#L258 The line is replaced with "fontSize: (orientation == Orientation.portrait) ? 34.0 : 24.0" 

3. A newline is added to the end of https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart

**Comment by jonahwilliams** [comment]
Looking through the numbers, it looks like only 1) and 2) regressed

**Comment by rmacnak-google** [comment]
A shape change is the adding or removing of instance fields. In such cases, instances need to be reallocated to their new size. None of these scenarios involve shape changes.

**Comment by rmacnak-google** [comment]
@alexmarkov Maybe. Filling in the values in the right order to prevent canonicalization from seeing uninitialized instances (Enum -> non-enum constant -> Enum) seems like it would require a whole parallel implementation of constant reading and canonicalization.

**Comment by rmacnak-google** [comment]
Golem reports its reload benchmark back to before the forwarding fix. So performance is as before for reloads without shape changes, but reload with shape changes will still incur the extra heap walk.
