### ISSUE TITLE
[Impeller] Implement pooling of render target textures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131515]
This is primarily necessary for Vulkan but may help Metal too. Xcode does warn of late texture creation even though it is fairly fast. On Vulkan, even memory-less (lazily allocated device-transient textures) take a long time to allocate. This may possibly be because the virtual address space for the texture still needs to be reserved.

**Comment by chinmaygarde** [comment]
The pooling mechanism should probably be tacked on to the resource manager. Currently, the resource manager is a Vulkan thing that we can move to the platform agnostic HAL.

**Comment by bdero** [comment]
I sorta have mixed feelings about this. Being able to _declare_ your textures as if you're re-allocating them each frame, but having them get automagically reused under the hood would be convenient for `EntityPass` in particular. OTOH, I'm having trouble conceptualizing how this behavior fits into Impeller's design.

Extending the lifetime of buffers under the HAL seems like it would be difficult to get right on any backend. What would mark the end of the extended lifetime? Since frames aren't really sensible concept under the HAL, we could try tying resource lifetime extensions to `impeller::Surface` flips... but what if the application doesn't render to a surface?

There's also a lighter concern around predictability. We'd be transitioning to a world where sometimes allocating a RT texture is free and sometimes it's expensive, with little feedback as to why. However, I don't think this is that big of a deal, since the vast majority of renderers that use offscreen RT textures would wind up needing a short application-level cache for RT textures anyhow.

**Comment by jonahwilliams** [comment]
> We'd be transitioning to a world where sometimes allocating a RT texture is free and sometimes it's expensive,

This is sort of already the case though. if you allocate too much, or having concurrent work doing allocation you will stall on Vulkan.

**Comment by jonahwilliams** [comment]
I'm not sure if we should necessarily expose this via the allocator, or if this should only be an optimization for render target textures. For decoded images this is unlikely to help.

**Comment by bdero** [comment]
> > We'd be transitioning to a world where sometimes allocating a RT texture is free and sometimes it's expensive,
> 
> This is sort of already the case though. if you allocate too much, or having concurrent work doing allocation you will stall on Vulkan.

This is sort of a minor concern, but what I mean is that by adding an opaque caching mechanism that varies between backends, renderers may begin relying on free reuse of RT textures between frames, and then run into steep unexpected turbulence as a result. Whereas they would have been better off in all cases on all backends if they'd just managed RT texture reuse more explicitly to begin with.

**Comment by jonahwilliams** [comment]
Yeah I think that makes a lot of sense!

> Whereas they would have been better off in all cases on all backends if they'd just managed RT texture reuse more explicitly to begin with.

This is going to be tricky though. At least in Flutter today, applications are unable to manage the allocations as they are all abstracted in the renderer - so its our responsibility to make sure we're being efficient.

Allowing users to manage this themselves for flutter_gpu sounds like a good idea. We should take note of the information we need in order to implement render target pooling in the backend and ensure it is exposed in a reasonable way in the HAL. For example, if we need the fence waiter signals for texture reuse on Vulkan, then we'll need to find a way to expose that.

**Comment by bdero** [comment]
> This is going to be tricky though. At least in Flutter today, applications are unable to manage the allocations as they are all abstracted in the renderer - so its our responsibility to make sure we're being efficient.

By "application" I meant "renderer above the HAL"; in Flutter's case, the Entity Framework. I don't think it would be appropriate for Flutter apps to manage RT texture lifetimes. 😛 

> We should take note of the information we need in order to implement render target pooling in the backend and ensure it is exposed in a reasonable way in the HAL. For example, if we need the fence waiter signals for texture reuse on Vulkan, then we'll need to find a way to expose that.

Is reusing an offscreen RT texture on contiguous frames not currently safe on the Vulkan backend? Mind giving a rundown on why that's the case? 🤔 Since `EntityPass::OnRender` is restricted to one thread, this seems like something we should be able to make safe without incurring performance penalties, unless we're allowing multiple frames' encoding jobs to smash into each other.

**Comment by jonahwilliams** [comment]
Safe is definitely the wrong word. I think Safety only comes into play if we were aliasing the texture allocations. What I am worried about is performance - but without any prototypes to evaluate this yet perhaps I'm worried about nothing. Here is the quandary:

Lets assume that we have more than one frame in flight - that is we could be encoding one frame while the GPU is still working on the previous frame.

While encoding frame one, we create a glyph atlas texture at some size NxN. We transition to a copy src, We upload data to it, and then encode a transition from a copy src to sample texture (forget the exact layout transition terminology).

While encoding frame two, while the GPU is still working on frame one. We decide we need a new MxM glyph atlas texture (where M < N), and so we recycle the texture from frame one. First we transition the texture to a copy src... what happens?

1. The command along with the data to copy gets queued up and executed after frame one is finished?
2. The layout transition blocks until the previous frame is finished?

I don't really have any idea. If we build a quick experiment to just recycle if we can from frame N - 1 we should be able to see if we block in the layout transitions

**Comment by bdero** [comment]
Oh, we're talking about two different things here. The glyph atlas isn't a render target texture; it's written by the host and transferred each frame.

It wouldn't be possible for us to at least block the write/transfer on the previous frame's sampling of the atlas on the GPU. So for that, I suspect we'd be better off spending extra memory to flip between 2 textures (or more, depending on the frame constraints).

But for offscreen color RT textures (as well as any non-transient depth-stencil textures on Metal/Vulkan), these should be possible to reuse across contiguous frames without limiting performance.

**Comment by jonahwilliams** [comment]
Right, I'm using the glyph atlas as an example but we need to do a layout transition any time a render target is sampled by the parent pass. My concern isn't specific to upload data but more about the semantics of layout transitions.

**Comment by jonahwilliams** [comment]
I wanted to build a prototype to evaluate my concerns above, its fairly simple: https://github.com/flutter/engine/pull/44519

This does not attempt to do anything other than match the exact size of render targets, but it seems to have a good number of cache hits per frame.  that said, I seem to run into two issues:

1. Advanced blends in flutter wonderous app are causing the validation error below. i don't know if that is due to the slow performance leading to the textures being "in use" longer (essentially confirming that we need to wait until the fencewaiter fires?)

```
E/flutter (21811): -----------------------------------------------------------------
E/flutter (21811): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (21811): --- Vulkan Debug Report  ----------------------------------------
E/flutter (21811): |                Severity: Error
E/flutter (21811): |                    Type: { Validation }
E/flutter (21811): |                 ID Name: VUID-VkWriteDescriptorSet-descriptorType-00337
E/flutter (21811): |               ID Number: -1779207809
E/flutter (21811): |       Queue Breadcrumbs: [NONE]
E/flutter (21811): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (21811): |         Related Objects: DescriptorSet [23520752741405584] [UNNAMED]
E/flutter (21811): |                 Trigger: Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00337 ] Object 0: handle = 0x53900000005390, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x95f3717f | vkUpdateDescriptorSets() pDescriptorWrites[1] failed write update validation for VkDescriptorSet 0x53900000005390[] with error: Write update to VkDescriptorSet 0x53900000005390[] allocated with VkDescriptorSetLayout 0x45140000004514[Descriptor Set Layout TextureFill Pipeline V#2] binding #64 failed with error message: Attempted write update to combined image sampler descriptor failed due to: ImageView (VkImageView 0x4f000000004f[ImpellerOnscreenResolve]) with usage mask 0x12 being used for a descriptor update of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER does not have VK_IMAGE_USAGE_SAMPLED_BIT set.. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, the imageView member of each element of pImageInfo must have been created with VK_IMAGE_USAGE_SAMPLED_BIT set (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00337)
E/flutter (21811): -----------------------------------------------------------------
E/flutter (21811): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (21811): --- Vulkan Debug Report  ----------------------------------------
E/flutter (21811): |                Severity: Error
E/flutter (21811): |                    Type: { Validation }
E/flutter (21811): |                 ID Name: VUID-VkImageMemoryBarrier-oldLayout-01211
E/flutter (21811): |               ID Number: 1049834979
E/flutter (21811): |       Queue Breadcrumbs: [NONE]
E/flutter (21811): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (21811): |         Related Objects: Image [80264348827721] [ImpellerOnscreenResolve]
E/flutter (21811): |                 Trigger: Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01211 ] Object 0: handle = 0x490000000049, name = ImpellerOnscreenResolve, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x3e9335e3 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].oldLayout Image barrier Layout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is not compatible with VkImage 0x490000000049[ImpellerOnscreenResolve] usage flags 0x12. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL then image must have been created with VK_IMAGE_USAGE_SAMPLED_BIT or VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01211)

```

2. This doesn't work unless the sizes match exactly, because we need to either alias the memory or re-create some parts of the texture. This would also imply that we need to wait for the fencewaiter to fire.

**Comment by bdero** [comment]
> Right, I'm using the glyph atlas as an example but we need to do a layout transition any time a render target is sampled by the parent pass. My concern isn't specific to upload data but more about the semantics of layout transitions.

Assuming we're talking about reusing textures between contiguous frames and not within the same frame, I think the additional image barrier we'd need to insert shouldn't block on anything unless the previous frame is already way too slow to be under budget.

As long as we're properly setting up barriers in-between each use of the image resource, that should be all that's needed to gate usage of the resource across frames. It shouldn't be necessary to e.g. wait for all work of the previous frame to complete -- especially not host-side.

> Advanced blends in flutter wonderous app are causing the validation error below. i don't know if that is due to the slow performance leading to the textures being "in use" longer (essentially confirming that we need to wait until the fencewaiter fires?)

I think those validation errors are indicating that the layout transition is invalid because the texture is not allocated with the correct usage flags to be compatible with the destination layout. We'd need to also include the usage bitmask in the hash when reusing textures (probably the whole `TextureDescriptor`).

**Comment by jonahwilliams** [comment]
I think the errors I hit were unrelated, updating and rebuilding seems to have removed them!

**Comment by jonahwilliams** [comment]
Less hacky version with no validation errors: https://github.com/flutter/engine/pull/44527

Unfortunately this still renders incorrectly on the advanced blends in wonderous, parts of the texture seem to be missing actually. Might try tracking via the fence waiter too

![Screenshot_20230808-203025](https://github.com/flutter/flutter/assets/8975114/f983d353-cdd2-4f2b-8aea-c3d6ae16e75b)

**Comment by jonahwilliams** [comment]
As a note for the issue above, and for precision in terminology, we're not pooling in the Vulkan implemenation. Vulkan requires that lazily allocated ( aka memoryless ) textures receive dedicated allocations, and may require dedicated allocations for textures based on their size.

**Comment by jonahwilliams** [comment]
This change improved worst frame time on the new gallery:

https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DSM-G973U1%26test%3Dnew_gallery_impeller__transition_perf&selected=commit%3D36334%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C

On the advanced blend benchmark (which has significant usage of large offscreen textures), the numbers improved dramatically:

https://flutter-flutter-perf.skia.org/e/?queries=test%3Danimated_advanced_blend_perf__timeline_summary&selected=commit%3D36338%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C
