### ISSUE TITLE
I am having this same issue please how do i resolve

### ISSUE THREAD

**Issue by Dsoji** [flutter/flutter#131606]
the issue was resolved

_Originally posted by @Arsh-78 in https://github.com/flutter/flutter/issues/109538#issuecomment-1218123904_

**Comment by dam-ease** [comment]
Hi @Dsoji. Please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:


- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Also please try this https://github.com/flutter/flutter/issues/109538#issuecomment-1216257819 to confirm the issue persists.
Thank you!
