### ISSUE TITLE
ios_debug_sim_arm64 flakes on run_tests.py startup?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#131899]
It looks like `out/ios_debug_sim_arm64/libFlutter.dylib` is getting clobbered?

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/113216/overview

```
Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1286, in <module>
    sys.exit(main())
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1269, in main
    run_objc_tests(args.ios_variant, args.objc_filter)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 721, in run_objc_tests
    ensure_ios_tests_are_built(ios_out_dir)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 625, in ensure_ios_tests_are_built
    assert flutter_dylib_time <= ios_test_lib_time, final_message
AssertionError: /Volumes/Work/s/w/ir/cache/builder/src/out/ios_debug_sim_arm64/libios_test_flutter.dylib is older than /Volumes/Work/s/w/ir/cache/builder/src/out/ios_debug_sim_arm64/libFlutter.dylib. Please run the following commands: 
gn --ios --unoptimized --runtime-mode=debug --no-lto --simulator
ninja -C /Volumes/Work/s/w/ir/cache/builder/src/out/ios_debug_sim_arm64 ios_test_flutter
```

**Comment by godofredoc** [comment]
Actually the problem is that we are getting getmtime of the two files and we are asserting that libFlutter.dylib was written to disk before libios_test_flutter.dylib. https://cs.opensource.google/flutter/engine/+/master:testing/run_tests.py;l=625?q=testing%2Frun_tests.py&ss=flutter

Running this check locally on my machine with clean out folder and no goma gives me ~7milliseconds difference

```
flutter/tools/gn --ios --runtime-mode debug --simulator --no-lto --force-mac-arm64 --simulator-cpu arm64 --no-goma
ninja -C out/ios_debug_sim_arm64 flutter/testing/scenario_app flutter/shell/platform/darwin/ios:ios_test_flutter

>>> os.path.getmtime('libios_test_flutter.dylib')
1691802200.5605488
>>> os.path.getmtime('libFlutter.dylib')
1691802192.2549846
>>> 
```

I'm assuming that given that distributed nature of goma and the speed of it the files may be written out of order by a fraction of millisecond.

Maybe the script should be updated to use only up to milliseconds?

**Comment by chinmaygarde** [comment]
Triage: @dnfield @gaaclarke, this check was added to ensure that the dylib built was up to date. But, since then, I believe we have resorted to building the engine as part of building the test (or something). I think we can back out this check to make this more consistent?
