### ISSUE TITLE
[infra] engine release builders do not automatically run on release branches

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#131819]
example: https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-3.13-candidate.0

when new commits are pushed to the release branch, engine release builders (linux/mac/windows) do not get automatically scheduled, their corresponding build block is empty on dashboard, and the task isn't scheduled or queued in the builders page. However, if using the mpa request to manually schedule the builds, they will show up on dashboard and also get queued.

**Comment by drewroengoogle** [comment]
Additional context: It seems that some builds were automatically deploying, while others failed to do so. I am looking into the scheduling policy to see if there's a reason this might be occurring.

**Comment by drewroengoogle** [comment]
Here's my current theory: We are currently scheduling builds using greedy batching and a default max_concurrent_invocations of 1. This means that only 1 build of each builder can run at a time (for example, only 1 Mac engine_release_builder job can run). Any other scheduled requests go into a queue to be run after the currently running one is finished. The way greedy batching works is that instead of running the next build in the queue, it lumps all the builds in the queue together and only triggers the most recent request.

I think the issue here is that we are committing to two candidate branches, so when we committed to both beta and stable, it only actually ran the most recent one and effectively ignored the others, so for example it may have only run the most recent beta, and the most recent stable got ignored due to greedy batching.

One solution would be to change the scheduling policy to run on every single commit, with the downside that we would no longer get the latest commit triggered right away.

**Comment by yusuf-goog** [comment]
anything to be done here?

**Comment by drewroengoogle** [comment]
This can be closed now!
