### ISSUE TITLE
Add Flutter CLI flag(s) to use artifacts from a presubmit Engine PR.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#131862]
The overall goal is to have any easy way to run framework CI tests on presubmit flutter/engine PRs.

Following the migration to the engine_v2 recipes, engine artifacts from presubmit builds populate the `flutter_archives_v2` bucket as opposed to the `flutter_infra_release` bucket.

Conveniently, the `flutter_archives_v2` bucket has the same layout as the `flutter_infra_release` bucket such that the postsubmit artifact URLs are of the form:

https://storage.googleapis.com/flutter_infra_release/flutter/e589d597c317f8ec549fe486ab8ce6e2590bf7d9/android-arm64-release/artifacts.zip

and the presubmit artifact URLs are of the form:

https://storage.googleapis.com/flutter_archives_v2/flutter_infra_release/flutter/55f04c84286500a7b2c032a3ac53f3b03317b0a2/android-arm64-release/artifacts.zip

The commit hash for the presubmit artifacts can be pulled from the GitHub PR UI or from the LUCI step that uploads to the bucket.

So, a Flutter CLI flag could cause the storage base URL to be https://storage.googleapis.com/flutter_archives_v2 instead of the default https://storage.googleapis.com, here:

https://github.com/flutter/flutter/blob/4df8d23e976ada28bfbbc9f92e9a0dee0c44d648/packages/flutter_tools/lib/src/cache.dart#L464

As the comment there says, a separate change would be needed for the Flutter Web and Fuchsia artifacts in CIPD. I haven't worked out what the change there would be yet.

A flutter/flutter PR that toggles the value of the flag, and supplies the commit hash for the Engine PR as https://github.com/flutter/flutter/blob/master/bin/internal/engine.version, would then run the framework CI presubmits against the Engine PR.

**Comment by eyebrowsoffire** [comment]
A flutter tool CLI flag would be useful to *locally* run tests, benchmarks, etc. against a presubmit version of the engine. However, since CI steps themselves are what invoke the flutter tool, it seems like having CLI flag would not make it super straightforward to run the full framework CI against a presubmit of the engine. I think for the framework CI case, I think it makes the most sense to express the bucket override as part of the same system that specifies the engine hash itself: the `engine.version` file. Perhaps it could also contain a "realm" line that can override whether we are pointing at the try bucket or the prod bucket. That way, you can just make a change to that file specifically, and all of the framework CI will run against the desired bucket.

**Comment by zanderso** [comment]
Yeah, good point. A separate `engine.realm` file might be easier to get working since otherwise the autoroller logic has to be updated for a new format for the `engine.version` file.

**Comment by zanderso** [comment]
I think the linked PR addresses this, with documentation in https://github.com/flutter/flutter/wiki/Testing-presubmit-Engine-PRs-with-the-Flutter-framework
