### ISSUE TITLE
[Impeller] Determine how to support leaf layer tracing

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#131941]
Today in the Skia backend, you can do leaf layer tracing from devtools to collect raster stats about each layer of your application.

This sort of works in Impeller but it may be misleading - texture creation and allocation will happen for it that otherwise would not, for example. We should determine whether and how we can provide more meaningful numbers to users.

**Comment by jonahwilliams** [comment]
There is a coarseness to this tracing which is probably not desirable. A single flow picture may end having that majority of the complexity from a given scene - but from that particular it may only be a particular drawing comand.

Likewise, large but otherwise simple layers will be over stated - especally if there were otherwise rendered in the swapchain texture.

**Comment by jonahwilliams** [comment]
Fixed by not supporting this feature
