### ISSUE TITLE
调试状态调用摄像头正常  打包会调用摄像头会出现闪退barcode_scan2

### ISSUE THREAD

**Issue by bosslizhiyong** [flutter/flutter#132186]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

调试状态调用摄像头正常  打包会调用摄像头会出现闪退barcode_scan2

### Actual results

调试状态调用摄像头正常  打包会调用摄像头会出现闪退barcode_scan2

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by fanchou** [comment]
不相关。添加混淆规则就好了

**Comment by huycozy** [comment]
Hi @bosslizhiyong 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml))

Closing this issue, since not much information is provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. I would recommend describing the issue in English for better understanding. Thanks!
