### ISSUE TITLE
[packages] codeql test failing due to no ruby found

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#132263]
https://github.com/flutter/packages/actions/runs/5814339809/job/15763812059 

flutter/packages tree is currently stuck due to a codeql test failure. Hoping someone can take a look at this.

**Comment by keyonghan** [comment]
The tree is open now. 
<img width="1721" alt="Screenshot 2023-08-09 at 5 03 04 PM" src="https://github.com/flutter/flutter/assets/54558023/929755fa-9031-4872-ace2-dec949795446">

Do you have a link to the failed build?

**Comment by tarrinneal** [comment]
https://github.com/flutter/packages

**Comment by keyonghan** [comment]
This doesn't sound an infra issue. @stuartmorgan Do you have any insight?

**Comment by tarrinneal** [comment]
> This doesn't sound an infra issue. @stuartmorgan Do you have any insight?

Ah, sorry then. Wasn't sure if it was or wasn't.

**Comment by stuartmorgan** [comment]
> The tree is open now. <img alt="Screenshot 2023-08-09 at 5 03 04 PM" width="1721" src="https://user-images.githubusercontent.com/54558023/259578497-929755fa-9031-4872-ace2-dec949795446.png">

That's the Flutter console, which only shows LUCI tasks. CodeQL isn't LUCI, so doesn't show up there, but it still closes our tree (because https://github.com/flutter/flutter/issues/128954 hasn't been addressed yet).

> This doesn't sound an infra issue. @stuartmorgan Do you have any insight?

I do not; the ecosystem team had no involvement in, or awareness of, the addition of CodeQL tasks to the repository. I assume it is related to the recent announcement about more tasks being enforced on Google-owned repositories (or that it was an infra-team-driven rollout if not).

There is literally nobody on the ecosystem team who can do anything about the configuration of this as far as I can tell. Nothing landed in the repo, so I assume a repo admin will need to fix this. We cannot have a task running on flutter/packages that fails if there is no Ruby code—because we do not have any, and have no plans to—and the ecosystem team can't fix it because we don't have that level of control over the repository. If the infrastructure team doesn't either, then that needs to be escalated, because not being able to stop always-failing jobs from running in the repository is absolutely an infrastructure problem.

**Comment by tarrinneal** [comment]
It seems like this may have been a bug of some sort, I landed a pr on red and it isn't happening again.

The pr WAS a roll for codeql, so it may have been addressed with the update, I'm not sure...

**Comment by tarrinneal** [comment]
Seems to be resolved with latest pr
