### ISSUE TITLE
URL Protocol (deeplink) callback on Linux

### ISSUE THREAD

**Issue by LucasXu0** [flutter/flutter#132298]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Is there an API or package that should be used for listening to URL protocol (deeplink) callbacks on Linux?

My app launches a website to verify user information, and then I use xdg-open to initiate the app on Linux. However, I'm unsure about how to capture and listen to the callback, including the parameters, from it.

### Proposal

No

**Comment by huycozy** [comment]
Hi @LucasXu0 
It seems you are asking for assistance rather than proposing a specific request for Flutter. Please also see https://flutter.dev/community for resources and ask questions like this. 

You can take a look at the known issue https://github.com/flutter/flutter/issues/51350 and discussion there for details and hints.

Closing the issue. Once you provide more information, please write in the comments and I will re-open this for further discussion. Thanks!
