### ISSUE TITLE
Since upgrading to iOS 16.6 or 17+ the apps not loaded, and freeze on splash screen.

### ISSUE THREAD

**Issue by Aminadav** [flutter/flutter#132378]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just install the app in release mode, or from the App Store.
It not only me many of the users are complaining.

### Expected results

That app should work

### Actual results

It's freeze on Splash scren.

### Code sample

I cannot provide the full code sample because it is all the app. 

### Logs

There are no relevenat logs.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IL)   
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @Aminadav 
The goal of this Github repo is to improve flutter reporting bugs or feature requests, but not to give assistance on personal code or the whole package/plugin project.

If you encounter behavior that you believe could be a bug, please provide a reproduction case/sample code that represents the problem. You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the issue into a sample that can be run independently and provide it so that we can verify the issue properly. 

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

**Comment by KingOfPeru** [comment]
same here our app freezes on splash

**Comment by Aminadav** [comment]
The issue is not relevant ot my code on 3rd party dependency. Everything was working great, until the last upgrade to iOS, so something deprecated in Flutter that I didn't discovered what.

I have a big app, and can't discovered what exactly made this happen.

It is working when running in debug mode, so I can't see any logs, and don't know how to debug the isssue and collect more information.

**Comment by huycozy** [comment]
@Aminadav Unfortunately, we were unable to verify the issue with such meager information. Code implementation is on your side. As I suggested above, you should dig deeper in your code to find where the issue is actually causing. You can try running it in `release` mode to see if can find any different logs: `flutter run --release -v`.

**Comment by rpungin** [comment]
@Aminadav , I had the same problem. For me this was because in `main.dart` I had some async/await initialization code that called a plugin that had an error in native code and never returned. So runApp() never got called. For me the plugins misbehaved only in iOS 17 causing this issue to happen.

So if you have some async/await method calls in main.dart, put some breakpoints after each call and see if it returns.

**Comment by jomaalv** [comment]
same issue... i solve this addiging a name: 'yourappname' on properties on this

Before:

 await Firebase.initializeApp(name: 'Contlity', options: DefaultFirebaseOptions.currentPlatform);

After: 

 await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
