### ISSUE TITLE
422status code for post request api for android and iOS simulator

### ISSUE THREAD

**Issue by AhkamKhalaaf** [flutter/flutter#132310]
After updating flutter to 3.10.6
Android emulator and iOS simulator 
Gives 422 status code when send post request api 
But request works fine with real device android and iOS 
Any help about this??!

**Comment by huycozy** [comment]
Per [422 Unprocessable Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422):

>The HyperText Transfer Protocol (HTTP) 422 Unprocessable Content response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.

You should fix the post request or server side so that server can process it. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing for now.
