### ISSUE TITLE
Failed assertion: line 5243 pos 12: '_history.isNotEmpty': is not true

### ISSUE THREAD

**Issue by NZhlebinkov** [flutter/flutter#132380]
I get this bug when I call `FirebaseAuth.instance.signOut()` even though I don't get such an error a few commits back.

```
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#448d3](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope, _FocusTraversalGroupMarker], state: NavigatorState#088a1(tickers: tracking 3 tickers)):
'package:flutter

/src/widgets/navigator.dart

': Failed assertion: line 5243 pos 12: '_history.isNotEmpty': is not true.

navigator.dart:5243

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

The relevant error-causing widget was
MaterialApp
main.dart:254
When the exception was thrown, this was the stack
#2      NavigatorState.build
navigator.dart:5243
#3      StatefulElement.build
framework.dart:5080
#4      ComponentElement.performRebuild
framework.dart:4968
#5      StatefulElement.performRebuild
framework.dart:5133
#6      Element.rebuild
framework.dart:4690
#7      BuildOwner.buildScope
framework.dart:2743
#8      WidgetsBinding.drawFrame
binding.dart:863
#9      SchedulerBinding._invokeFrameCallback
binding.dart:1289
#10     SchedulerBinding.handleDrawFrame
binding.dart:1218
(elided 2 frames from class _AssertionError)
```

**Comment by dam-ease** [comment]
Hi @NZhlebinkov. Thanks for filing this. From the logs, the issue seems to be with your navigation after signOut and might not be describing a bug or a feature request. Please see https://flutter.dev/community for resources and ask questions like this, you may also get some help if you post it on Stack Overflow
Closing, as this isn't an issue with Flutter itself. If you disagree, please provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Also, write in the comments and I will reopen it.
Thank you
