### ISSUE TITLE
display same jpg, flutter need six times memory size bigger than iOS Native

### ISSUE THREAD

**Issue by chaokongzwp** [flutter/flutter#13242]
## Steps to Reproduce

I write a  demo for  display 51 image widget in ListView  Widget, the image resource are from  CDN server,  after all the images are showing, the application use  360+M memory,   see the picture down there
<img width="1177" alt="memory-flutter" src="https://user-images.githubusercontent.com/23513781/33362827-ee4c640c-d518-11e7-9811-0aed5bed9a39.png">

all the images's size are only 200+ KB far less than 1MB,  the image resource urls is in the file ImagesSource.dart.txt
[ImagesSource.dart.txt](https://github.com/flutter/flutter/files/1512844/ImagesSource.dart.txt)

and  my flutter project code in main.dart.txt
[main.dart.txt](https://github.com/flutter/flutter/files/1512852/main.dart.txt)

Also I write a compare demo by iOS native  display the same image resources ,  iOS native just use 70M memory, why the flutter use much bigger memory than iOS native?

and, there also anther problem, in my flutter demo,  when click the image widget, the home page will rebuild by calling the setState() function, and the page State build() return a Text Widget instead the ListView widget before,  I think the memory will diminish， but the memory keep the same, I try force gc but no effect,  how the dart gc work?

## Logs

![flutterrun](https://user-images.githubusercontent.com/23513781/33365028-ce63bd6c-d521-11e7-81d3-0403788bcfaa.png)

![memoryobseray](https://user-images.githubusercontent.com/23513781/33365061-ee3f6154-d521-11e7-8b29-d1b464a129ed.png)

## Flutter Doctor
/Users/chaokong/flutterSDK/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale zh-Hans-CN, channel master)
    • Flutter at /Users/chaokong/flutterSDK
    • Framework revision bdbe53be01 (4 days ago), 2017-11-24 19:13:18 -0800
    • Engine revision 93b2179597
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/chaokong/Library/Android/sdk
    • Unable to locate Android NDK.
      
    • Unable to locate compiler in Android NDK.
      
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.1.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • 张伟平的 iPhone • fb87fda18a77f01197d25047bed12a782b21e01f • ios • iOS 11.1
    • iPhone X    • C598742A-2903-4BE8-A6FF-4168FC8DD581     • ios • iOS 11.1 (simulator)

Process finished with exit code 0

**Comment by Skylled** [comment]
You could likely reduce the memory load by using a `ListView.builder` instead.

**Comment by rrousselGit** [comment]
And here I tought I was the one doing something wrong !

I have the same problem (as stated here : https://stackoverflow.com/questions/47513991/preload-an-image-asset-in-flutter)

I have 100-130mo of png which consume 700mo of ram in an app that does nothing but load them all.
Which is far too much for a 2Go ram device

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew for user journey around memory usage and potential optimization

**Comment by eseidelGoogle** [comment]
@cbracken: I'd like you to take ownership of investigating here.  (Possibly with @yjbanov, @xster or @chinmaygarde's help)  We've gotten now two memory-related requests from customer: gold and I'd like to at least start to understand what's going on.  Thanks.

**Comment by jason-simmons** [comment]
Each image is consuming texture memory proportional to the size of the bitmap, and I did not see any unintended leaks.

Memory usage continues to increase because we hold images in the [ImageCache](https://docs.flutter.io/flutter/services/ImageCache-class.html) and do not evict items from the cache until it exceeds a maximum size (which defaults to 1000).  The app can set imageCache.maximumSize to limit cache size (at the expense of repeatedly retrieving and decoding images).

Images are cached at full size, not the size they are rendered at if the app scales them down.  Also, replacing the image widgets and doing a GC will not affect image memory consumption because the image cache remains populated.

The native app may be using a different strategy to load and cache images.

**Comment by yjbanov** [comment]
I think a slightly smarter cache can have big effect here:

- Cache large images encoded.
- Cache small images decoded.
- Set cache size based on total memory occupied by images, not based on the number of images.

Maybe?

**Comment by rrousselGit** [comment]
@yjbanov +1

Also :
 - Ability to override the default behaviour based on both key and ImageInfo

This would allow to exclude an asset folder from cache or always cache network images.

**Comment by yjbanov** [comment]
@rrousselGit if you are blocked by this issue, you can bring your own cache today by implementing your own `ImageProvider`, until we figure out what the out-of-the-box solution should be provided by the framework.

**Comment by petrucci34** [comment]
@jason-simmons thanks for the clarification. Regarding your comment `Memory usage continues to increase because we hold images in the ImageCache and do not evict items from the cache until it exceeds a maximum size (which defaults to 1000). ` could you clarify if the cache could ignore duplicate images? Is determining if an image is duplicate a non-trivial task?

**Comment by jason-simmons** [comment]
Cache entries are identified by a key that is specific to the image provider and typically includes the path to the image along with the image's scale.  See [ImageProvider.obtainKey](https://docs.flutter.io/flutter/services/ImageProvider/obtainKey.html).

The cache may contain images with different keys that have duplicate content.

**Comment by eseidelGoogle** [comment]
I've asked @cbracken to replicate the comparison locally.

**Comment by mjohnsullivan** [comment]
The Flutter ImageCache appears to utilize more memory than expected. In an experiment, there were 50 images, each image 500x300 px (about 600K per bitmap), so the total expected size should be about 30M, but Flutter on iOS was 200M.

**Comment by cbracken** [comment]
A quick update here. I'm still working on drilling down into understanding what's going on here in detail, and will report back with the analysis once I've got something more concrete.

In the meantime, I think one thing that's quite clear from the discussion on this bug is that it would be useful for Flutter to provide finer-grained control over image caching. I've opened #13493 so we can carry on discussion of those features independently of the memory consumption issue in this bug. I'd encourage anyone with an interest to add their thoughts there, and thumbs-up the ideas they like to see most.

**Comment by cbracken** [comment]
Thanks for your patience on this, everyone. I've created a repo at [cbracken/ImageMemory](https://github.com/cbracken/ImageMemory) with a simple app that displays a scroll view with 40 network-loaded images, so we've got a common set of Flutter/UIKit code to discuss.

The repo includes two roughly equivalent implementations: one in Flutter, and the other a plain UIKit app. There are zip files of allocation profiles I collected for each as well as instructions to reproduce those allocation profiles.

A couple important points:
1. Benchmarks were collected from a release-mode build. Flutter generates *very* different code in debug mode, so a profile or release mode build should be used for collecting native allocation profiles. The ARM code we generate in debug mode is designed to make hot-reload fast and convenient, but the allocation profiles it produces will be very different from the AOT code we generate for profile/release builds.
2. Benchmarks were collected on a physical device. Simulator builds use a software graphics stack, which will result in very different allocation profiles to what users will get in the release build on the app store.

Key results:
* Total persistent allocations: 9.59 MiB on Flutter vs 45.51 MiB for the UIKit app.
* Total allocations: 367.54 MiB on Flutter vs 293.5 MiB for the UIKit app.
* I see exactly 40 images allocated in the bitmap cache in the Flutter app, as expected. If I manually inspect the Dart heap using a profile build, I also see 40 `ui.Image` instances allocated there.
* Each [image](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Googleplex-Patio-Aug-2014.JPG/640px-Googleplex-Patio-Aug-2014.JPG) consumes the same amount of memory in the Flutter app as in the UIKit implementation: `width * height * 4` bytes. In this case, `640 * 480 * 4`, or `1,228,800` bytes.

Based on the screenshots in the original report, it looks like the original profiles may have been collected in debug mode, which could explain a lot of the difference you're seeing. I've filed #13503 for us to write a *Profiling Flutter Apps* page. Our current default of *debug* builds make it very easy to accidentally generate profiles that are very different from the builds that will eventually ship to end-users.

@chaokongzwp can you verify what your app's allocation profile and heap size look like when run in Instruments in profile or release mode, and let me know if things look any better?

**Comment by sethladd** [comment]
@cbracken thanks for the analysis!

**Comment by petrucci34** [comment]
Thanks @cbracken for the comprehensive analysis! In my earlier post, I ran my profiler tests in release mode and noticed redundant memory allocation/deallocation when I scrolled the same list of images up and down. Have you had a chance to perform the same use-case and notice unusual memory allocation behaviors?

**Comment by cbracken** [comment]
@petrucci34 I assume you're referring to #12542 -- I'll take a look and follow up on that bug. Thanks for reporting.

**Comment by petrucci34** [comment]
@cbracken yes exactly. Thank you!

**Comment by chaokongzwp** [comment]
@cbracken thanks for the analysis! 
I also do the tests as you described above, and the result is the same. 
Flutter image cache is bitmap, native no cache bitmap, which I did not find before, this is the main reason for the large difference in memory size.

**Comment by cbracken** [comment]
@chaokongzwp thanks for confirming!

**Comment by rrousselGit** [comment]
In my case --profile/release or debug, the result is the same : Approximately 700-800 MO of ram consumed only with images (and I'm not even loading them all).

This may be the "correct" ammount of memory once they are converted in bitmap. But I can't ship it this way.

The problem is that `imageCache` is final and can't be changed. But at the same time, you can't specify in `Image`  whether to cache the image compressed or decompressed. 
The solution, as said @yjbanov would be to create a custom `ImageProvider` . But then, using `new Image.asset` implicitly set a `AssetBundleImageProvider` which will _always_ cache it decompressed. So I'd have to create a custom `Image` class as well.
This would also means I'd have to go through all my `Image.asset`, and decide whether or not to replace it by my custom implementation. Considering I have more then a hundred of them it's cumbersome.

**Comment by cbracken** [comment]
@rrousselGit your case is a slightly different scenario to the original issue -- I've filed #13503. As discussed, we cache the decompressed bitmaps in our image cache, which will consume ~ `width * height * 4` bytes each. Depending on the images ~700MB sounds entirely feasible. Since this is currently the expected behaviour, it's a slightly different issue -- I've filed #13493 to track. 

If you've got specific behaviour/configurability you'd like to see from the image cache in addition to the current `ImageCache.maximumSize`, definitely please add them on that bug. Thanks again for your feedback!

**Comment by sethladd** [comment]
I've asked https://stackoverflow.com/questions/47836539/how-do-i-change-or-replace-the-imagecache-in-flutter with the hopes we can provide a small snippet and example. cc @Hixie who might be able to answer this :)
