### ISSUE TITLE
Let scrollbars avoid obstructing slivers and media query paddings

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13253]
Internal: b/144318472

Consider a CustomScrollView with a SliverAppBar and a SliverList and the user wants a scrollbar showing the position inside the SliverList's contents only. 

Let the SliverAppBar report SliverGeometry describing its obstructing and max obstructing extends. Let that get aggregated by the scrollable and bubbled up with a scroll notification so the scrollbar can start below the obstructing area.

**Comment by xster** [comment]
Also avoid media query partial obstructions

**Comment by xster** [comment]
This issue isn't closed yet is it? Since there's still the sliver half of it.

**Comment by LongCatIsLooong** [comment]
It was closed because I put __partially fixes__ in my PR.

**Comment by spkersten** [comment]
We've also run into this problem. We are using a PersistenHeader for our app bar, so it would be good if a solution would not just work with SliverAppBar but can also be used for custom headers.

**Comment by LongCatIsLooong** [comment]
For future reference: we decided to implement a `SliverScrollbar` because it's hard to retrieve some metrics from outside of the viewport. For example if there's a persistent header sliver, detecting the amount of scroll extent it is blocking (which may change as the viewport scrolls) is tricky from outside.
A `SliverScrollbar` that takes a single sliver child should be able to get its own `maxPaintExtent` and `paintExtent` etc. easily. 

One thing that makes the `SliverScrollbar` not as useful as it could be currently is that we do not have a "multi sliver adaptor sliver" kind of thing available in the framework right now. For example, putting a `CupertinoSliverRefreshControl` and a `SliverMultiboxAdaptor` in a `SliverScrollbar` would be impossible because it can't take more than one child. /cc @Piinks

**Comment by edwardez** [comment]
SO cross-link:
https://stackoverflow.com/questions/56640482/how-to-show-scrollbar-in-sliverlist

I'm wondering is there a workaround for this issue(maybe even in some hacky way)?

**Comment by adeolaex** [comment]
Any update on this ?

**Comment by xster** [comment]
@LongCatIsLooong I remember you started working on the sliver part. Did you have a draft PR or notes from your previous try?

**Comment by LongCatIsLooong** [comment]
@xster no unfortunately.

**Comment by kirill-21** [comment]
Any progress?

**Comment by goderbauer** [comment]
Also somewhat relevant for https://github.com/flutter/flutter/issues/87370 to avoid drawing the scrollbar on top of pinned header rows, for example.

**Comment by CavalcanteLeo** [comment]
any progress?

**Comment by Piinks** [comment]
I have a proposal for this that should be up for review this week.
I just noticed this is also something the MaterialBanner would want to support. Currently it would overlap a SliverAppBar, just like a Scrollbar does. I need to test this new use case to make sure it works too before pushing the changes.
I'll probably land the ability to surface this information to these widgets, and then update each widget in a separate follow up change.

**Comment by Piinks** [comment]
Closing this to consolidate in https://github.com/flutter/flutter/issues/107322
In researching a solution, I found a pattern of the same issue across multiple widgets in the framework. There is a full list in that tracking issue, including scrollbars. 

I have a proposed solution in https://github.com/flutter/flutter/pull/107182 that will fix this consistently across all affected parts of the framework. That PR will be split up into multiple PRs to address each widget that needs this fix, just finishing the many test cases now. Please continue to follow in #107322, I expect all of thees changes to be landing soon.
