### ISSUE TITLE
Clarify ColorScheme fromSwatch/fromSeed usage

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#132584]
From https://github.com/flutter/website/pull/9183#discussion_r1294291872

Currently the API docs does not distinguish which constructor should be used in what context.
The linked comment says:

> We don't recommend using fromSwatch (M1/M2 concept) but rather fromSeed (M3+)

but the docs for `fromSwatch` say

> This constructor is used by [ThemeData](https://api.flutter.dev/flutter/material/ThemeData-class.html) to create its default color scheme.
- https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSwatch.html

`fromSeed` is a bit clearer, but it isn't clear to me as a Flutter developer which I should use and how they differ in the context of M1/2 versus M3

> Using the seedColor as a starting point, a set of tonal palettes are constructed. These tonal palettes are based on the Material 3 Color system and provide all the needed colors for a [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html). These colors are designed to work well together and meet contrast requirements for accessibility.
- https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSeed.html

While we're at it, the other constructors should be checked for the same clarity for M1/2/3:
- dark
- light
- highContrastDark
- highContrastLight

**Comment by TahaTesser** [comment]
I see lot of people using `fromSwatch` in Material 3 code samples.

**Comment by rydmike** [comment]
Finally, and yes the `fromSwatch` should basically **never** be used, it creates awful color themes, especially in dark mode. It predates even correct M2 based ColorScheme based themes and makes horrid gray looking dark themes. I have written volumes about this https://docs.flexcolorscheme.com/theming_roads#swatch-based-themedata

When `useMaterial3: false` is used all `ThemeData` factories **except** `ThemeData.from` create Material 2 swatch based themes, but even if the swatch color concept is M2 based, the dark theme it makes is not, since this `ThemeData` dark mode predates the M2 dark mode guide and spec. A M2 mode correct dark mode is only obtained if using a `ColorScheme` made with `ColorScheme.light/dark(...)` and `ThemeData.from(...)` factory that was added to make correct M2 based themes.

You can do correct M2 based themes with `ThemeData(colorScheme: , ...)` too, but then you have to do same color assignments manually that the `ThemeData.from(...)` factory does with the provided `colorScheme`. This is actually worth it if you are going to do a lot of other custom component themes too, since you can avoid an extra `copyWith`.

Hopefully all these confusing old factories goes away soon, but yes first step getting the docs up to date is **super** welcome and will help new Flutter developers, well maybe even old ones that never learned the newer ways 😄
