### ISSUE TITLE
Support Vertex Shaders for Custom Paint

### ISSUE THREAD

**Issue by ehsanonline** [flutter/flutter#132691]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter supports [fragment shaders](https://github.com/flutter/flutter/issues/30763) via custom paint but not vertex shaders yet. as [doc ](https://docs.flutter.dev/ui/design/graphics/fragment-shaders#authoring-shaders) mentioned they would be called `.vert` files. since I couldn't find any issue for that, I opened this. I hope with Impeller we could use the full capacity of shaders. thanks. 

### Proposal

it's very low-level so I don't think that would be possible to for third-party packages.

**Comment by jonahwilliams** [comment]
Supporting arbitrary vertex shaders with the current canvas API is infeasible. The Flutter engine needs to be aware of the vertex instructions in order to correctly position geometry in the canvas and compute actual bounds to ensure compositing effects are correct.

For more control over rendering, you'll need something like flutter GPU: https://github.com/flutter/flutter/issues/130921
