### ISSUE TITLE
Support hover on ChromeOS

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13265]
Native Android apps installed on ChromeOS support hover. When mouse is over a field that you can interact with, it gains focus. Flutter apps should behave the same.

Bonus points if we can give the apps the ability to customize the pointer (such as turn it into a hand).

**Comment by mehmetf** [comment]
This needs to be fixed by August 15, 2018. Please assign to the appropriate milestone.

**Comment by tvolkert** [comment]
Clarification: widgets shouldn't automatically gain _focus_ on mouse hover.  Here's a strawman of what we'd probably like to have:
* `onMouseEnter`
* `onMouseExit`
* show a widget's tooltip if the cursor pauses within a tooltip-enabled widget for some period of time

However, there are some devils in those details:
1. For the tooltip, do we reset the timer if they move the cursor within the widget, so that we only count time when the cursor isn't moving?  We need UX guidance on this.
1. Hit testing is expensive, so we really don't want to be doing it unless we have to.

**Comment by mehmetf** [comment]
I think this should be split into at least 3 issues:
- Support for `onMouseEnter` and `onMouseExit`.
- Support for "highlight" on hover. This involves modifying the core Material elements to go into "base hover" state.  It should not focus the element. You can see the effect of this by hovering the mouse over Github buttons. (This is an L1 requirement).
- Support for showing tooltip on hover (This is an L2 requirement).

**Comment by tvolkert** [comment]
Sounds good - closing this as overloaded.

Filed separately: https://github.com/flutter/flutter/issues/22815, https://github.com/flutter/flutter/issues/22816, https://github.com/flutter/flutter/issues/22817
