### ISSUE TITLE
[Impeller] Investigate remaining Flutter gallery performance issues on Vulkan/GLES.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#132690]
There are three kinds of slow frames I can see from looking at the devicelab benchmarks:

### (Vulkan) Blocking on FenceWaiter::AddFence

![image](https://github.com/flutter/flutter/assets/8975114/84c04d7b-0033-49e1-b2be-486ac939fc65)

### (Vulkan/GLES) slow atlas population

![image](https://github.com/flutter/flutter/assets/8975114/3da31270-dcd5-4cd3-9c82-7e94741bd450)

### (Vulkan) Slow command encoding

![image](https://github.com/flutter/flutter/assets/8975114/cfaf4524-231c-46e2-af04-1b0d4b9834de)

**Comment by jonahwilliams** [comment]
The slow render pass encoding reproduces on a Pixel 7 as well. Here is a highly annotated trace:

![image](https://github.com/flutter/flutter/assets/8975114/2f481eee-b30e-4aaa-a4a0-4b1630a82fcc)


In this case, GARBO2 is a trace event I added in the command pool recycler:

```
void CommandPoolVK::GarbageCollectBuffersIfAble() {
    TRACE_EVENT0("impeller", "CommandPoolVK::GARBO2");
  if (std::this_thread::get_id() != owner_id_) {
    return;
  }
  buffers_to_collect_.clear();
}

```

So I suspect the issue may be destroying command pools is stalling on the raster thread. We should re-arrange this code to use the resource manager if possible.

**Comment by gaaclarke** [comment]
We noted this offline too, but just creating and deleting CommandPoolVK and command buffers may be faster than the synchronization that was added to try to cache them.  Also it seems like maybe CommandPoolVK is built on the assumption that the command buffers need to be deleted on the raster thread which shouldn't be the case.  Since the tracked objects is trying to delete it on the resource tracker thread, we should be able to delete them safely there.

**Comment by jonahwilliams** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/135443
