### ISSUE TITLE
Drag and Drop Design Document

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#132758]
### Document Link

https://flutter.dev/go/external-drag-and-drop

### What problem are you solving?

Currently, Flutter developers can only implement drag and drop interfaces within Flutter applications that do not involve files or other objects that originate from, or are destined for, the platform the application is running on. For example, you can drag items around in a UI, but you cannot drag an image file from the filesystem into an app and have it load the image. This feature is the [#2 upvoted desktop feature](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+desktop%22+sort%3Areactions-%2B1-desc+-label%3A%22severe%3A+new+feature%22) in the Flutter issue database.

This proposed design is solving that shortfall by proposing an API for receiving and generating drag and drop requests in cooperation with the underlying platform.

**Comment by knopp** [comment]
I've read through the proposal. Some parts of it remind me of assumptions that I've made initially that have backed me into a corner. Such as assuming that the app is in charge of initiating the drag (not true on iOS) or that the data is readily available on drop. Or using single widget for dragging multiple items (doesn't map well to platforms with separate drag items where each is expected to have custom image and target location).

It also seems like a missed opportunity to cover clipboard access since there is an conceptual overlap between clipboard and drag & drop and often the platform API is same (i.e. IDataObject used both for clipboard access and as drag & drop payload).

I've made a short document regarding the API design of super_drag_and_drop, mostly to provide a bit of perspective. Hopefully it will be of some use.

https://docs.google.com/document/d/1gPhYbzRjzJ6OgPEgey0axPETgYyJ_8Ohgh2KljYd-SI/edit?usp=sharing
