### ISSUE TITLE
[Impeller] After enabling Impeller on the ios side, there is a problem with screen rendering.

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#132849]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.

### Expected results

After enabling Impeller on the ios side, the screen rendering is normal.

### Actual results

After enabling Impeller on the ios side, there is a problem with screen rendering.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

Impeller enabled
<img src="https://github.com/flutter/flutter/assets/47768002/4dba0422-faac-4473-b063-164e3e3d2762" width=320>
</img>

Impeller disabled

<img src="https://github.com/flutter/flutter/assets/47768002/29eda83f-7532-42c0-8e1e-ff1ef6e9ac0a" width=320>
</img>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.0 on channel stable at /Users/ying/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • Kimmy's iPhone (mobile)    • 00008020-000A1D110A32002E            • ios            • iOS 16.6 20G75
    • iPhone 14 Pro Max (mobile) • 45E8411D-922C-49C0-813D-E8070B8F8352 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by jonahwilliams** [comment]
We need a code sample to diagnose the issue.

**Comment by kjxbyz** [comment]
https://github.com/kjxbyz/darkness_dungeon

**Comment by jonahwilliams** [comment]
Can you perhaps point out how the light sources are rendered in the codebase?

**Comment by kjxbyz** [comment]
The code to control the display of the light source is as follows

https://github.com/kjxbyz/darkness_dungeon/blob/9938b8f432628326f6cc2e56cde5380171dfb4ba/lib/decoration/torch.dart#L14

https://github.com/kjxbyz/darkness_dungeon/blob/9938b8f432628326f6cc2e56cde5380171dfb4ba/lib/player/knight.dart#L42

**Comment by darshankawar** [comment]
I cloned the repo to replicate the issue reported, but been getting below compile time error while trying to run the app:

<img width="867" alt="Screenshot 2023-08-21 at 12 34 47 PM" src="https://github.com/flutter/flutter/assets/67046386/4ed76178-f9e0-48aa-a5c2-a1d4559792a7">

I'll try to look into fixing those a bit later, but for now based on the report, labeling for tracking.

**Comment by kjxbyz** [comment]
I run the app without any problem. You can try to run the following command

```bash
flutter clean

cd ios && rm -rf .symlinks Pods && cd ..

flutter pub get

cd ios && pod install && cd ..
```

**Comment by kjxbyz** [comment]
After enabling Impeller on the Android side, I have the same problem.

**Comment by jason-simmons** [comment]
The lighting effect is drawing a circle with a `Paint` that sets `BlendMode.clear` and a `MaskFilter.blur`.

Impeller is producing the results above because it is calling `entity.SetBlendMode(BlendMode::kClear)` based on the paint's blend mode.  Later, `ContentContextOptions::ApplyToPipelineDescriptor` sets the color attachment's blend factors based on `kClear`.  The entire area of the blur filter region is then cleared.

I can get output that looks correct by patching the app to use `BlendMode.dstOut` instead of `BlendMode.clear`.

@jonahwilliams @bdero What is expected behavior for this case?

Is the app expected to use a different blend mode when applying a filter?  Or should Impeller configure the pipeline differently for the combination of `BlendMode::kClear` and a filter?

**Comment by jonahwilliams** [comment]
Hmm, this one is odd. In general, we should be behaving like Skia does, but it looks like in this case we're treating the supplied BlendMode as the blend to apply the filtered contents to the canvas, whereas perhaps Skia is applying the filtered contents to the canvas with srcOver?

**Comment by bdero** [comment]
This app aborts on a DCHECK in the layer tree at engine head for me. https://github.com/flutter/engine/blob/8417a45b2f9588a478161008e903f0b9650727e7/flow/layers/opacity_layer.cc#L39

**Comment by gaaclarke** [comment]
I tried this at HEAD (6e1f41ff591ddf02de9e197805ac7e8926078f31) and this crashes for me on device as @bdero ran into.  It runs on simulator though.

**Comment by gaaclarke** [comment]
Here is the frame capture that is apparently drawing incorrectly.

<img width="1129" alt="Screenshot 2023-09-21 at 9 55 46 AM" src="https://github.com/flutter/flutter/assets/30870216/763f34d1-2409-4777-be53-a615de729d7c">

Here is the texture that is being drawn

![light](https://github.com/flutter/flutter/assets/30870216/dd897915-e2f8-4922-abf3-bf3f9caea1c3)

notes:

1) The texture doesn't look correct to begin with
1) The hard line is happening when the colors go from (0,0,0,0) to (0,0,0,0.6)

Here is the first draw call when generating that lighting texture that appears wrong:

<img width="1547" alt="Screenshot 2023-09-21 at 10 06 39 AM" src="https://github.com/flutter/flutter/assets/30870216/a2af7a0b-88f9-4c9c-a336-667f80445390">

I would have expected the lighting to be blended (max or multiply or add?) instead of source over.  I'm not even sure why a black rect is being drawn at all.  I haven't dove into the reproduction code to know if this is a renderer error or an error in how the texture is being generated (I'm guessing renderer).

**Comment by gaaclarke** [comment]
Here is the lighting texture as generated from skia:
![light_skia](https://github.com/flutter/flutter/assets/30870216/c159eff8-2c7c-4db0-8a6c-cc220c2466c3)
notes:
1) The color at the left side of the image is (0,0,0,0.6) just as it is in impeller

So there are 2 potential problems:
1) The code generating the lighting texture is wrong
1) The code blending the lighting texture is wrong

We can't know if 2 is an issue until we fix 1.

**Comment by gaaclarke** [comment]
Here is impellers blend settings versus skia's blend settings for the first draw that clears out the region:
impeller
<img width="920" alt="Screenshot 2023-09-21 at 10 30 57 AM" src="https://github.com/flutter/flutter/assets/30870216/78d946db-a71c-4dbd-8cff-af472d1ce0e6">

skia
<img width="827" alt="Screenshot 2023-09-21 at 10 33 27 AM" src="https://github.com/flutter/flutter/assets/30870216/cfe4b884-df89-46ff-9c67-ad8738d45a5f">

I don't know if the skia blend settings are what we want, but the impeller ones clearly seem wrong since they will just obliterate whatever is there.

**Comment by jonahwilliams** [comment]
The Impeller settings are for BlendMode::Clear, these are being used because the draw itself uses blend mode clear, but skia doesn't seem to be applying that in the same way (or at all)

**Comment by bdero** [comment]
Clear is supposed to completely clear the color, and all blends should be modulated by the geometry mask. I suspect this is a case where we're not handling mask blurs correctly.

The mask of the source object needs to modulate the blend. The alpha of the color source should be irrelevant with the Clear blend.

**Comment by gaaclarke** [comment]
I believe I've created a minimal reproduction:
## impeller

<img src="https://github.com/flutter/flutter/assets/30870216/fecb831e-0348-4080-9623-1703251eebf7" width=100>

## skia

<img src="https://github.com/flutter/flutter/assets/30870216/2bb4083a-daf6-4306-8e59-2cafb205e3bd" width=100>

## code

<details>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class LightingConfig {
  final double radius;
  final Color color;
  final bool withPulse;
  final bool useComponentAngle;
  final double pulseVariation;
  final double pulseSpeed;
  final Curve pulseCurve;
  final double blurBorder;
  double _blurSigma = 0;

  double valuePulse = 0;

  LightingConfig({
    required this.radius,
    required this.color,
    this.withPulse = false,
    this.useComponentAngle = false,
    this.pulseCurve = Curves.decelerate,
    this.pulseVariation = 0.1,
    this.pulseSpeed = 1,
    this.blurBorder = 20,
  }) {
    _blurSigma = _convertRadiusToSigma(blurBorder);
  }

  double get blurSigma => _blurSigma;

  static double _convertRadiusToSigma(double radius) {
    return radius * 0.57735 + 0.5;
  }
}

final Paint _paintFocus = Paint()..blendMode = BlendMode.clear;
final Paint _paintLighting = Paint();
final Paint _paintFocusArc = Paint()..blendMode = BlendMode.clear;
final Paint _paintLightingArc = Paint();

void _drawCircle(Canvas canvas, Offset offset, LightingConfig config) {
  final maskFilter = MaskFilter.blur(
    BlurStyle.normal,
    config.blurSigma,
  );
  canvas.drawCircle(
    offset,
    config.radius *
        (config.withPulse
            ? (1 - config.valuePulse * config.pulseVariation)
            : 1),
    _paintFocus..maskFilter = maskFilter,
  );

  _paintLighting
    ..color = config.color
    ..maskFilter = maskFilter;
  canvas.drawCircle(
    offset,
    config.radius *
        (config.withPulse
            ? (1 - config.valuePulse * config.pulseVariation)
            : 1),
    _paintLighting,
  );
}

class Sky extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    LightingConfig config =
        LightingConfig(radius: 100, color: Color.fromARGB(179, 245, 217, 118));
    _drawCircle(canvas, Offset(100, 100), config);
    _drawCircle(canvas, Offset(150, 150), config);
  }

  @override
  bool shouldRepaint(Sky oldDelegate) => false;
  @override
  bool shouldRebuildSemantics(Sky oldDelegate) => false;
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CustomPaint(
              painter: Sky(),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by gaaclarke** [comment]
Using Skia's blend settings for clear (https://github.com/flutter/engine/pull/46167) gets us closer, the colors are still slightly off compared to skia though:

## reporter's app
![IMG_6664](https://github.com/flutter/flutter/assets/30870216/18773e4a-ddf1-46ad-b323-f5804c14b293)

## test app
<img src="https://github.com/flutter/flutter/assets/30870216/e5a33aa4-713a-48b2-98aa-104169d40bbe" width=320></img>

**Comment by jonahwilliams** [comment]
Blurs might look off for unrelated reasons to the clear color issue.

**Comment by bdero** [comment]
modulating the effect by the source alpha works for this specific case, but if you draw an image with transparent parts using kClear, are the transparent parts of the image supposed to not clear the backdrop?

**Comment by gaaclarke** [comment]
I didn't have much time to look into this today, but briefly the reason the colors are washed out is because in skia the clear circle leaves everything in black-clear (0, 0, 0, 0), but in impeller the clear circle leaves everything in white-clear (1, 1, 1, 0) despite them having the same blend factors:

## impeller

<img width="987" alt="Screenshot 2023-09-22 at 4 30 08 PM" src="https://github.com/flutter/flutter/assets/30870216/315d0d05-cff9-4bc5-b368-7e7eb6459b8a">


## skia

<img width="1173" alt="Screenshot 2023-09-22 at 4 28 00 PM" src="https://github.com/flutter/flutter/assets/30870216/fdbf67df-2489-4a3d-b74e-97eeea9a0bb6">

Hopefully that white color is just something hardcoded somewhere in impeller that wasn't important until we switched to this definition of clear.

> Modulating the output color by the source alpha works for this specific case, but if you draw a ui.Image with alpha channel transparency using kClear, the transparent parts of the image will not clear the backdrop. Is that correct behavior?

It appears to be the correct behavior as defined by skia.  The visual results seem reasonable too.  I won't land this without accompanying golden tests so we can make sure.

**Comment by gaaclarke** [comment]
The following change makes the render correct in impeller:

```diff
-final Paint _paintFocus = Paint()..blendMode = BlendMode.clear;
+final Paint _paintFocus = Paint()..blendMode = BlendMode.clear..color = Colors.white;
```
