### ISSUE TITLE
Image.toByteData() too slow

### ISSUE THREAD

**Issue by ishivrajvala** [flutter/flutter#132932]
ByteData? rgba = await image.toByteData(format: ImageByteFormat.png);

I want to convert ui.Image to File and it's too slow in android and ios both

**Comment by huycozy** [comment]
Hi @ishivrajvala 
There was a similar issue (https://github.com/flutter/flutter/issues/106773) but it was fixed a year ago. I'm not sure which Flutter version you are using, please provide information below so that we can verify the issue properly:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- A timeline trace JSON when running app in profile mode. You can find the instructions for it at https://github.com/flutter/flutter/issues/74833#issue-795394794.

**Comment by alexlopatka** [comment]
the problem has been around for a long time (thread priorities), still very slow (Channel stable, 3.13.3)
https://github.com/flutter/flutter/issues/106773
