### ISSUE TITLE
[missing Docs] in-complete docs, on why and when is `services:SystemChannels.keyboard::getKeyboardState` needed

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#132938]
hi

I was checking out the docs of [`services:SystemChannels.keyboard::getKeyboardState`](https://master-api.flutter.dev/flutter/services/SystemChannels/keyboard-constant.html), 

but had a hard time finding, anything besides, its usage; especially the crucial info like, when and where is this function needed, is missing; this problem is further complicated by the fact, that `SystemChannels` class, also has a `keyEvent` symbol, so both seem similar

thanks

**Comment by justinmc** [comment]
I agree, after a quick look through the docs and code, it's not obvious what getKeyboardState is used for.

**Comment by bleroux** [comment]
`getKeyboardState` is a somewhat recent addition I filed on https://github.com/flutter/flutter/pull/122885.

Because both the framework and the engine maintain a state of the current pressed keys, there are edge cases where the framework need to get the keyboard state from the engine. Those edge cases a related to startup and restart where the framework pressed keys state might not be accurate.

For reference, here is the comment which led to this PR: https://github.com/flutter/flutter/issues/87391#issuecomment-1228975571

I will be happy to file a PR to improve the documentation and I very welcome any suggestions on which information I could add.

**Comment by gintominto5329** [comment]
> What's your reason for looking into this?

Learning the internals of flutter, and their working.

thanks

**Comment by gintominto5329** [comment]
@bleroux 

> When the engine `KeyboardManager` is created (and starts listening to system events) and when `GestureBinding` is initialized (and starts listening to engine messages.) This is an extremely short period of time but not zero

_Originally posted by @dkwingsmt in https://github.com/flutter/flutter/issues/87391#issuecomment-1228975571_

Does this mean, that after the `GestureBinding` initialization, `getKeyboardState`'s work is finished?

thanks

**Comment by bleroux** [comment]
Yes, the work described in the issue is finished:
>To resolve this issue, we should create a new method channel API so that the framework can query the keyboard state from the engine, such as:
> - Framework asks: "getKeyboardState"
> - Engine responds: { 0x00070039 : 0x00100000104 } (which is { PhysicalKeyboardKey.capsLock : LogicalKeyboardKey.capsLock })"

It is implemented on both the framework and engine.
