### ISSUE TITLE
[Engine] There are 2+ ways that DisplayList* results in `SkPaint` (which is confusing)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#132994]
While attempting to pair down how `setDither(...)` works (e.g. https://github.com/flutter/engine/pull/44912), I was constantly getting confused on how many places in the engine are `SkPaint` instances created by code within `display_list/**`. For example, consider `DlSkCanvasDispatcher` and `DlSkCanvasAdapter`:

## [`DlSkCanvasDispatcher`](https://github.com/flutter/engine/blob/e5f690b829e5f2d5407a79cb99ee035957b52682/display_list/skia/dl_sk_dispatcher.h#L16-L23)

```h
//------------------------------------------------------------------------------
/// Can be fed to the dispatch() method of a DisplayList to feed the resulting
/// rendering operations to an SkCanvas instance.
///
/// Receives all methods on Dispatcher and sends them to an SkCanvas
///
class DlSkCanvasDispatcher : public virtual DlOpReceiver,
                             public DlSkPaintDispatchHelper { /* ... */ }
```

## [`DlSkCanvasAdapter`](https://github.com/flutter/engine/blob/e5f690b829e5f2d5407a79cb99ee035957b52682/display_list/skia/dl_sk_canvas.h#L13-L15)

```h
// An adapter to receive DlCanvas calls and dispatch them into
// an SkCanvas.
class DlSkCanvasAdapter final : public virtual DlCanvas
```

... which in turn uses `ToSk` to convert from `DlPaint` to `SkPaint`:

```cc
void DlSkCanvasAdapter::DrawPaint(const DlPaint& paint) {
  delegate_->drawPaint(ToSk(paint));
}
```

---

I can maintain code in both branches, but I'm actually just curious (and wasn't able to easily determine) why there are multiple ways for `display_list/**` to write to `SkPaint`, and whether this is intentional (if so, it might be nice to add a bit more commenting to both of the above classes explain the intended use-cases) or some sort of intermediate state that's non-obvious (which also could deserve a few comments).

Of the two, `DlSkCanvasAdapter` appears to be used in many more places, fwiw.

/cc @flar, would you be able to help me understand a bit? I'm happy to volunteer PRs to improve the documentation.

**Comment by flar** [comment]
One manages translations for the DlCanvas interface. The other manages translations for the DlOpReceiver interface.

DlCanvas is developer-facing and is stateless.
DlOpReceiver is internal implementation details for the DL package and the rendering code and is stateful.

This is all intentional, but may be revisited in the future.

**Comment by flar** [comment]
Independently, while implementing the recent https://github.com/flutter/engine/pull/44718 PR that involved redesigning the way that the DL buffer is constructed, I came to the conclusion that the stateful DlOpReceiver class should be eliminated in favor of a more straightforward and stateless DlCanvas::Method <-> DlOp::Record mapping. See my last comment on https://github.com/flutter/flutter/issues/108303 for more analysis and information.

**Comment by matanlurey** [comment]
Thanks for the explanation! I'm re-opening just to update the docs, and will self-assign.

**Comment by flar** [comment]
I will continue my analysis of whether we can do something to reduce the pain of `DlOpReceiver` in the issue linked above (https://github.com/flutter/flutter/issues/108303). It all depends on reanalyzing how much the attribute state affected the changes that I've been making to DL over the years since it was created, and potentially whether we can control the level at which it is exposed (eg. hiding it inside the DisplayList and Builder/Recorder classes and deliver `DlCanvas` calls when asked to play the sequence back).
