### ISSUE TITLE
Compatibility of deploying flutter windows with windows server

### ISSUE THREAD

**Issue by EwertonDutra** [flutter/flutter#132954]
Hello,
I'm looking for flutter deploy compatibility for windows and windows server
But seeing the deploy page
https://docs.flutter.dev/deployment/windows
I didn't see anything related to whether or not it is compatible with servers (even if it is, what is the minimum version)

I'm seeing this possibility, because I already develop with flutter and dart and thought about using it in a new project. Or if it would be better to go to C# itself.
The application is simple, it will have an api consumption from time to time, sending a file.

Regards for helping with this doubt.

**Comment by darshankawar** [comment]
Thanks for the report @EwertonDutra 
I am not sure if deploying with windows server is supported yet or not because I couldn't find any existing issue or documentation around it. One option could be to use VM that has supported windows OS and then you could run your app on it. Can you check if that's a feasible option for you ?

**Comment by EwertonDutra** [comment]
I ended up doing it with C# anyway
In case testing for me would take even longer
Thanks

**Comment by darshankawar** [comment]
Does that mean the issue can be considered as resolved and can be closed ?

**Comment by EwertonDutra** [comment]
Yes, thanks @darshankawar
