### ISSUE TITLE
[go_router] ShellRoute example is incomplete

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#133235]
### Document Link

https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/shell_route.dart

### What's the problem?

The example states that 

> // This example demonstrates how to display a route within a ShellRoute and also
// push a screen using a different navigator (such as the root Navigator) by
// providing a `parentNavigatorKey`.

However, I didn't find any use of `_rootNavigatorKey` and `_shellNavigatorKey` in the example. Additionally, I believe the example should use `push` instead of `go` in the method below, so that the back button (on Android) operates as anticipated.

```dart
  void _onItemTapped(int index, BuildContext context) {
    switch (index) {
      case 0:
        GoRouter.of(context).go('/a');
        break;
      case 1:
        GoRouter.of(context).go('/b');
        break;
      case 2:
        GoRouter.of(context).go('/c');
        break;
    }
  }
```

Ideally, the example should illustrate how the behavior of "popping" differs when invoked from the new navigator (introduced by the `ShellRoute`) compared to when it's executed using the root navigator. I believe that's likely the main intent behind this example.

**Comment by c0pp1ce** [comment]
1. Look at line 74: ``parentNavigatorKey: _rootNavigatorKey,`` - The use case is covered by the example.
2. Using push would not work since it does not change the location "within" the shell widget. It should also be noted that the behaviour of the Android back button for bottom navigation is not defined. Some "native" apps (like the gallery) will close the app instead of returning to a previous tab.

The main use case of a ``ShellRoute`` is to have a common shell/container widget shared by multiple widgets. I do think this is properly displayed in the example. I am unsure what you mean with the differing popping behavior since that does not generally change. Anyway you can compare this already as well. Popping from ``/b/details`` uses the root navigator, while popping from ``/a/details`` uses the shell navigator.

**Comment by iLoveDocs** [comment]
@c0pp1ce 

1. Yes, `_rootNavigatorKey` is indeed assigned to the `parentNavigatorKey`, but it was **not used**. For example, if I do 
```dart
final GlobalKey<FormState> _formKey = GlobalKey(); // Declared

// somewhere in build()...
Form(
  key: _formKey, // Assigned
  ...
);
```

But if I never use `_formKey`, then there's no point in defining and assigning it in the first place. This is what I am seeing in the example that the keys were **defined, assigned but never used**. 

2. Thanks for clearing that up. 

Coming to the last part:

> Popping from /b/details uses the root navigator, while popping from /a/details uses the shell navigator.

This was my point. How will you differentiate if you were popped from the root navigator or the  shell navigator? Doing `Navigator.of(context).pop()` works the same for both. This is where the key should have come into picture. 
That means, if we use `push` to navigate and then use `_shellNavigatorKey.currentState!.pop()`, we know that it was the shell navigator navigation and the app will not exit (close), but if we do `Navigator.of(context).pop()`, it will exit (close).

**Comment by c0pp1ce** [comment]
1. It assigns the ``_rootNavigatorKey`` to a ``parentNavigatorKey`` attribute. That is different from the default ``key``. It changes the behavior of the ``/b`` route in the way that it does not use the shell widget.

I do not think that this is how popping pages is working. It does not matter which router is used to display the current page of the stack, only the stack of pages is important. That means that popping from ``/b/details`` will always return you to ``/b`` since there is a page configured for it. Accordingly popping from ``/b`` will exit since there is no page left in the stack below it.
