### ISSUE TITLE
Flutter Module Data Communication Issue on M1 MacBook

### ISSUE THREAD

**Issue by Terriermon** [flutter/flutter#133221]
I recently integrated a Flutter module into our iOS project and employed channels for data communication between native and Flutter components. While it functions seamlessly on MacBook models with Intel chips, I encountered issues when running it on an M1-powered MacBook, where it fails to operate as intended.

**Comment by danagbemava-nc** [comment]
Hi @Terriermon,

Please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Please also provide details on how it fails to operate as intended. 

Thank you
