### ISSUE TITLE
Adding Objective-C Delegate Protocol to Plugin swift class causes SDK modules to not be found

### ISSUE THREAD

**Issue by tianxcode** [flutter/flutter#133226]
I try to implement a delegate written in Objective C. Adding Objective-C Delegate Protocol to Plugin swift class causes SDK modules to not be found.
Flutter (Channel stable, 3.7.11, on macOS 13.4.1 22F770820d darwin-arm64,
    locale zh-Hans-CN)

**Comment by tianxcode** [comment]
[delegate_test.zip](https://github.com/flutter/flutter/files/12425107/delegate_test.zip)
this is the Demo

**Comment by darshankawar** [comment]
@tianxcode 
Please don't use comments from other issues to file a new issue. Try to use new issue template, fill out requested details so that we'll have enough info to work with.
Please provide us steps to replicate, complete runnable code sample (native and dart) that can be readily used along with error log and `flutter doctor -v` so that we can properly address the issue.

**Comment by tianxcode** [comment]
> @tianxcode Please don't use comments from other issues to file a new issue. Try to use new issue template, fill out requested details so that we'll have enough info to work with. Please provide us steps to replicate, complete runnable code sample (native and dart) that can be readily used along with error log and `flutter doctor -v` so that we can properly address the issue.

Flutter (Channel stable, 3.7.11, on macOS 13.4.1 22F770820d darwin-arm64,
    locale zh-Hans-CN)

**Comment by darshankawar** [comment]
@tianxcode 
Thanks for the update. Can you also provide what exactly the error you get ? Please also provide exact steps to replicate that we need to follow to in order to properly replicate the reported behavior.

Also, since you are not on latest stable, I suggest you to upgrade and run your scenario again to check if the reported behavior persists in latest version as well or not.

**Comment by tianxcode** [comment]
@darshankawar  when i run on ios simulator, i get the error 'Lexical or Preprocessor Issue (Xcode): 'delegate_test/delegate_test.h' file not found' even i use up to date flutter 3.13.1.

**Comment by tianxcode** [comment]
when i add delegate_test.h at Classes, it works!

**Comment by tianxcode** [comment]
@darshankawar thanks
