### ISSUE TITLE
How to merge platform_strong.dill and /private/var/folders/cp/**/T/flutter_tools.hhArJI/flutter_tool.NcNwhU/app.dill

### ISSUE THREAD

**Issue by AbeiOS** [flutter/flutter#133227]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

![image](https://github.com/flutter/flutter/assets/12441461/683af820-d0f4-49ed-bd39-c187ba473f0a)

### Proposal

![image](https://github.com/flutter/flutter/assets/12441461/b4500254-f5b3-4107-a8f6-9d144cc682f5)

**Comment by AbeiOS** [comment]
I want to merge these two dills to modify syntax tree nodes.

**Comment by huycozy** [comment]
Hi @AbeiOS 

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please see flutter's [community](https://flutter.dev/community) for resources as well. 

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
