### ISSUE TITLE
CI failure: "Newer commit available" (buildbucket?)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133578]
What am I supposed to when I encounter:

```
Infra Failure: Step('collect builds.collect.wait') (canceled) (retcode: -15) Newer commit available
```

I did a re-run but then got the same error.
https://github.com/flutter/engine/pull/45134/checks?check_run_id=16317271997

/cc @ricardoamador who was helping me out on Discord:

> This is coming from buildbucket but I am still trying to trackdown why.

**Comment by ricardoamador** [comment]
This is not currently blocking as the checks on the PR have succeeded. This did coincide with a github degredation on events but I don't know if that has played a part here as the build was started and the recipe code kicked out he infra failure. Still investigating.

The error seems to have come from the bb script that is run on the bot as part of the buildbucket module we use in the engine_v2 recipes.

**Comment by matanlurey** [comment]
It was blocking initially (at least, the check was reported as a failure, maybe that's not always blocking?)

**Comment by ricardoamador** [comment]
How many times did you trigger the rerun button? We currently are waiting out a github webhook service outage. And if you trigger the rerun we cancel the existing build so it makes sense that with the degradation in the webhook service you could have seen this issue as we did not the get the event from github for some time.

**Comment by matanlurey** [comment]
> How many times did you trigger the rerun button?

Just once IIRC.

**Comment by godofredoc** [comment]
`Infra Failure: Step('collect builds.collect.wait') (canceled) (retcode: -15) Newer commit available` means the scheduler intentionally canceled builds because there was a new commit. In most cases this happens very fast and the github ui is updated almost immediately with the links to the builds associated with the most recent commit. However in this particular case the error happened when the github services were degraded and most likely the events were delivered to cocoon scheduler with an unexpected long latency making the error visible.
