### ISSUE TITLE
[go_router]I want to route from the shell to redirect to the login, but I can't return. What should I do?

### ISSUE THREAD

**Issue by noahge** [flutter/flutter#133566]
![CleanShot 2023-08-30 at 00 22 07@2x](https://github.com/flutter/flutter/assets/25917176/a3c94c06-a878-4e7a-9da5-12d7c274a5b2)

After I navigate to the login, I can't go back to the previous route. What should I do?

**Comment by darshankawar** [comment]
@noahge I think your question is better suited for support channels like StackOverflow where you can get a solution.
If you think there's a bug you found in the package, please use appropriate new issue template, fill out requested details so that we can properly address the issue.
Closing for now, as this seems more like a support question.
