### ISSUE TITLE
Don't pass MultiFrameCodec across threads

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#13359]
The `MultiFrameCodec::getNextFrame` which is running on the UI thread is passing "this" as part of a closure to the IO thread.
This is unsafe, as it is possible for posted task to run on the IO thread after the dart isolate quit and cleared  the object.

@chinmaygarde

**Comment by Hixie** [comment]
cc @chinmaygarde did we ever fix this? :-)

**Comment by chinmaygarde** [comment]
Just took a look at it, and, no. It's pretty hairy. We should prioritize a fix for this ASAP.

**Comment by Hixie** [comment]
@chinmaygarde Who would be the best person to look at it?

**Comment by Hixie** [comment]
cc @dnfield

**Comment by chinmaygarde** [comment]
This isn’t particularly difficult. Anyone with spare cycles to cleanup the callback spaghetti and add tests now that we have harness for it could take a stab at this. Is this showing up in a customer issue?

**Comment by dnfield** [comment]
Put up a patch for this.  It's definitely good to fix it, since this would bite someone hard if they tripped on it - but AFAICT the only way to trip on it would be to deallocate the engine while playing an animated image and getting unlucky in having the UI thread finish collecting garbage before the IO thread finished decoding the current frame.
