### ISSUE TITLE
Create a wiki page for how to diagnose/report website inaccessibility

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#133780]
Currently if one or more of the sites are down (`flutter.dev`, `docs.flutter.dev`, `api.flutter.dev`, etc.) are down or inaccessible, users may not know how to escalate this issue. This is especially the case for new users which would be directed to the appropriate location through those sites, but no longer are. As a result, some users may report to incorrect/inefficient locations, ignore the issue, or assume it's on their end.

To help reduce the chance of the Flutter team not knowing of these issues for extended periods of time, we should create a document which outlines how to best diagnose and/or report these issues. The Flutter GitHub wiki would be a good location as it is hosted on a separate infrastructure from the rest of the Flutter sites, GitHub. I've noticed GitHub is also less frequently blocked by countries than Firebase's IPs. With proper naming and description, this could show up in search engines when searching "Flutter site down", "Can't access Flutter site", "Flutter docs not working", etc. 

I'm not sure what the preferred escalation route to suggest would be. GitHub issues could work but that may not be noticed right away and requires a GitHub account. Discord could work but that requires a Discord account. A dedicated email could work as well, as users generally have email accounts, but has the downside of likely(?) being only accessible to Googlers. Any or all of the previous would be fine and could still be helpful, so I don't have a preference.

\cc @Hixie 

**Edit:** This page should consider first mentioning common issues on the user said causing inaccessibility and how to resolve those.

**Comment by Hixie** [comment]
I considered this a bunch when writing <https://github.com/flutter/flutter/wiki/Postmortem%3A-flutter.dev-outage-on-August-26-2023>.

There's a few issues, the prime one being that any documentation (e.g. a page on the wiki) would be unlikely to be known to people seeing the problem. For the `flutter.dev` outage last weekend, I found two people mentioning it on Twitter, and two on Discord. I'm sure none of them would have know of a wiki page. One of them knew to ping me, which by luck worked since I was up at the time.

Regarding channels: We do now have an `@emergency` role on the Discord that people can message (and anyone can opt into), as well as an #incident-response channel which people can set to "always notify". People could ping that, if they knew about it. However, I fear that telling people how to reach us will only result in lots of inappropriate pings. We can also create aliases on flutter.dev; we have security@, press@, and conduct@ which can all be configured to be reachable by non-Googlers (e.g. my non-work account is on security@). We could add a fourth. I worry that adding too many channels just dilutes the solution and makes it less effective.

**Comment by parlough** [comment]
> There's a few issues, the prime one being that any documentation (e.g. a page on the wiki) would be unlikely to be known to people seeing the problem. For the flutter.dev outage last weekend, I found two people mentioning it on Twitter, and two on Discord. I'm sure none of them would have know of a wiki page. One of them knew to ping me, which by luck worked since I was up at the time.

I guess my hope here is that we could get it showing up when searching "Flutter site down". I have no analytics to back it up, but perhaps users searched that first. It only takes one user finding the page to learn how to report it.

> Regarding channels: We do now have an `@emergency` role on the Discord that people can message (and anyone can opt into), as well as an #incident-response channel which people can set to "always notify". People could ping that, if they knew about it. However, I fear that telling people how to reach us will only result in lots of inappropriate pings.

I like the idea of using the `@emergency` role, but as you said the potentially for inappropriate/inaccurate pings is there, same goes for the email. Perhaps it being behind the other Discord welcome/rule agreements is sufficient to avoid most of those. And documenting some diagnostic first-steps to try on the wiki page before mentioning the reporting steps would help too. If it ends up being too much, we can always step back and switch reporting to opening an issue.

**Comment by Hixie** [comment]
I've created a page: https://github.com/flutter/flutter/wiki/In-case-of-emergency
Please don't hesitate to add more content, keywords, or whatever.
