### ISSUE TITLE
DisplayList drawVertices feels like a foot gun.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133797]
The DisplayList API for drawVertices has an overload for accepting a raw ptr, and an overload for accepting a shared_ptr. The shared_ptr version immediately calls vertices.get() and does not hold onto the refcount of the shared_ptr.

This caused the first version of the dl performance overlay to crash (https://github.com/flutter/engine/pull/45341) as we weren't keeping the refcount of the vertices alive long enough.

I'm not sure how we're keeping DLVertices alive in general, but surely having the display list actually hold the shared ptr would be safer?

@matanlurey @flar

**Comment by flar** [comment]
It feels like the compiler shouldn't get rid of the shared_ptr reference until the internal method returns.

**Comment by flar** [comment]
Perhaps if the method call took a shared_ptr reference instead of the shared_ptr itself, it would leave the destruction of the shared_ptr to the caller and the problem would be fixed. This is generally good practice in any case as it avoids object wrapper churn. I've been changing these managed pointer arguments to const references wherever I encounter them.

**Comment by jonahwilliams** [comment]
> It feels like the compiler shouldn't get rid of the shared_ptr reference until the internal method returns.

Even then you are now putting some fairly restrictive threading restrictions on this API. Either the backend needs to copy all data or it must be entirely synchronous. It seems more effective to let the current storage format store the refcount too?

**Comment by flar** [comment]
> > It feels like the compiler shouldn't get rid of the shared_ptr reference until the internal method returns.
> 
> Even then you are now putting some fairly restrictive threading restrictions on this API. Either the backend needs to copy all data or it must be entirely synchronous. It seems more effective to let the current storage format store the refcount too?

Huh? The backend does copy all of the data. If it did then a lot of apps wouldn't run.

**Comment by flar** [comment]
Adding an `&` to this line (and the implementations thereof if anyone overrides it) should fix the problem:

https://github.com/flutter/engine/blob/20865fb79e7b67196892e87b8b1da8582ea4356a/display_list/dl_canvas.h#L155

**Comment by jason-simmons** [comment]
`DlVerticesGeometry` in Impeller's DL dispatcher is holding a raw pointer to the `DlVertices`:
https://github.com/flutter/engine/blob/main/impeller/display_list/dl_vertices_geometry.h#L64

Does `DlVerticesGeometry` also need to copy the vertex data?

**Comment by flar** [comment]
Oh, yes, it got a raw pointer from DL, it shouldn't assume that that data will outlive the DL.

In the case of AiksCanvas, it should not assume this either.

**Comment by flar** [comment]
This line of code is a bug. Never save a raw pointer unless you have an explicit contract with the caller:

https://github.com/flutter/engine/blob/df619c6a5237c2f82fd48806be2cfaf621024759/impeller/display_list/dl_vertices_geometry.cc#L68

**Comment by jonahwilliams** [comment]
Can we make the display list hold and vend a shared_ptr to the dl vertices object? We can go back to copying the data out of display list, but this means that draw vertices would require 3 full copies of its data:

1. Dart -> Native Copy (Display List)
2. Display List -> Impeller Host Buffer
3. Impeller Host Buffer -> GPU Device buffer.

Alternatively, maybe the DLVertices should have backend specific implementations so we can copy the data into the impeller host buffer eagerly.

**Comment by matanlurey** [comment]
> This line of code is a bug. Never save a raw pointer unless you have an explicit contract with the caller

Is there a lint we can enable to catch this kind of stuff? I swear this is blocked in google3?

**Comment by flar** [comment]
> Can we make the display list hold and vend a shared_ptr to the dl vertices object?

I was just talking with @chinmaygarde about this. I'm thinking it might be time for DL v2.

Keep in mind that the data in DL was originally considered to be a reference copy, not the copy that the backends would keep. In most every other case, I hand you a DlSomething and Impeller immediately creates some completely unrelated Impeller objects out of it. The fact that I'm passing a pointer to the data is actually an optimization in that case. If you don't need it to be shared because you aren't going to keep the original around, then the overhead of passing a shared_ptr (and the overhead of having managed pointers in the buffer) are wasted time.

So, it appears that DlVertices turns out to be an "OK thing" for Impeller to just use as it is. That's great and so maybe we should consider creating, keeping, and transferring this data by shared_ptr instead of doing the inlining.

Can we start doing this with more of the objects? Can we migrate the DlFoo objects so that they pretty much say what Impeller wants them to say (while also being reasonably easy to translate into the vocabulary of Skia for the Skia backend) to avoid having to do any translation from DL -> Impeller? Any object we can do that to is one more object that it makes sense to have only 1 copy ever.

**Comment by jonahwilliams** [comment]
I think that instead of a DLV2, we should move towards AiksCanvas as the public API for future impeller only builds and leave the exisitng DL interface for the Skia backends.

**Comment by flar** [comment]
> I think that instead of a DLV2, we should move towards AiksCanvas as the public API for future impeller only builds and leave the exisitng DL interface for the Skia backends.

That puts a burden on the Skia backend for no advantage. DL exists so that there is one communication path regardless of backend and one place to implement optimizations. Having 2 paths means we should never have bothered with DL in the first place.

**Comment by flar** [comment]
Why have AiksCanvas? There is already an Impeller::Canvas - why not just talk directly to that?

**Comment by jonahwilliams** [comment]
Sorry, that is what I meant - the impeller canvas (in the aiks library). Long term there will only be one backend though. And that long term is quickly approaching.

> That puts a burden on the Skia backend for no advantage

This wouldn't change a thing about the Skia backend?

**Comment by flar** [comment]
> > That puts a burden on the Skia backend for no advantage
> 
> This wouldn't change a thing about the Skia backend?

The Skia backend was changed 2 years ago when we went from talking directly to it to instead talking through the abstraction layer of DL.

If Impeller does an end run around DL then DL is no longer an abstraction layer, it's just an obstacle compared to how we used to talk directly to it.

**Comment by jonahwilliams** [comment]
I'm not sure that I understand the point you are making. I don't think DL is currently an obstacle to shipping Impeller, but I don't think I would invest substantial time reworking it to work better for impeller. Ultimately its an internal API surface, and with one renderer I don't see any distinction between having dart:ui speak DL or impeller::Canvas?

**Comment by flar** [comment]
> I'm not sure that I understand the point you are making. I don't think DL is currently an obstacle to shipping Impeller, but I don't think I would invest substantial time reworking it to work better for impeller. Ultimately its an internal API surface, and with one renderer I don't see any distinction between having dart:ui speak DL or impeller::Canvas?

I never said it was an obstacle to shipping Impeller. I'm saying that it is an overhead to the pathways that still use Skia.

**Comment by jonahwilliams** [comment]
Closing as we've worked around this issue.

**Comment by jonahwilliams** [comment]
Or rather, the issue was elsewhere 😆
