### ISSUE TITLE
[pigeon] Add support for collections of enums

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#133728]
As of https://github.com/flutter/packages/pull/4580 pigeon supports enums as primitives across all platforms. 

It still does not support collections of enums though.

`List<Enum>` is a fairly common type even in our own packages (ie. local_auth_ios), as such should be supported by pigeon.

`Map<Enum>` would is also needed.

**Comment by mohachouch** [comment]
Hello,

Any news for this issue

**Comment by Marchuck** [comment]
I guess it's still not working.
However, I figured out the following workaround by wrapping enum to the class, so it's a bit better type-safety than 
`List<int?>` (collection of ordinals) or `List<String?>` (collection of enum names):

let's say we have following enum:

```dart
enum Pet{CAT, DOG, FISH; }
```
instead of 

```dart
@FlutterApi()
abstract class PetsApi {
    List<Pet?> getPets();
}

```

do the following:
```dart
class PetResponse{
    Pet? pet; //Pet.CAT
    String? key; //"cat"
}
```
The flutter api would look the following(you can map/filter nulls on native side)
```dart
@FlutterApi()
abstract class PetsApi {
    List<PetResponse?> getPets();
}
```
