### ISSUE TITLE
[Impeller] Make Vulkan validation on Android for end users self-serve.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#133794]
In the last Impeller weekly, it was discussed how we could make gather Vulkan validation errors from end users easier during the Android Vulkan Preview period (and beyond).

The action item was to package and enable Vulkan validation layers in debug runtime mode builds. The validation layer libraries are already in the source tree.

If there are issue enabling validation in debug builds, we could at least write a wiki page guiding users on how to sideload the layers themselves while submitting bug reports.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams

**Comment by gaaclarke** [comment]
Update from https://github.com/flutter/engine/pull/45350: This isn't possible to implement with our current build system unfortunately.  In order to build validation layers the android api has to be `>= 23`, the engine supports android 22 and GN isn't flexible enough to build with multiple apis.  It's not a problem at runtime because we can selectively load the dynamic library only on operating systems that support it.  See PR for more context.

**Comment by chinmaygarde** [comment]
Let's document how to manually sideload validation layers and take this up after preview then?

**Comment by gaaclarke** [comment]
> Let's document how to manually sideload validation layers and take this up after preview then?

Zach said he wants to take a stab and tweaking GN so we'll wait on that.  I think we can even make a script that automatically injects and turns on the layers for an apk.
