### ISSUE TITLE
Xcode Could not build module 'shared_preferences_foundation'

### ISSUE THREAD

**Issue by Zqiang12345** [flutter/flutter#133970]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

shared_preferences: ^2.2.1

### Actual results

Parse Issue (Xcode): Umbrella header 'shared_preferences_foundation-umbrella.h'  not found
Parse Issue (Xcode): Could not build module 'shared_preferences_foundation'

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

Parse Issue (Xcode): Umbrella header 'shared_preferences_foundation-umbrella.h'  not found
Parse Issue (Xcode): Could not build module 'shared_preferences_foundation'

</details>

**Comment by dam-ease** [comment]
Hi @Zqiang12345. Thanks for filing this. I tried reproducing this by creating a new flutter project, added `shared_preferences: ^2.2.1` to dependencies and ran the sample code provided in https://pub.dev/packages/shared_preferences/example and couldn't reproduce this error on the latest versions of flutter. Can you try these as well to see if the issue still reproduces? Also, from the error shared, this might not be an issue with flutter as I see possible solutions in this [thread](https://developer.apple.com/forums/thread/7528), you might want to check this out as well.

If after trying these, you can still reproduce, please try to provide all or some of the information indicated in the template so that we can address this issue further.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Thank you!

**Comment by Zqiang12345** [comment]
After upgrading the macOS version, the problem was resolved


Damilola Alimi ***@***.***>于2023年9月4日 周一21:16写道：
