### ISSUE TITLE
Flutter - Android Studio - Cocoapods not installed error

### ISSUE THREAD

**Issue by Superuser77SU** [flutter/flutter#133992]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run Android Studio project

### Actual results

Hi all,
I keep getting the following error in Android studio while building a flutter project. I'm working on a mac...
Any help would be much appreciated...

```console
**Launching lib/main.dart on iPhone 14 in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.**

**CocoaPods not installed or not in valid state.
Error launching application on iPhone 14.**
```

I Tried
```console
sudo gem uninstall cocoapods && sudo gem install cocoapods'
```

I ran flutter doctor and get the following message...
```console
Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-x64, locale
en-GB)
Android toolchain - develop for Android devices (Android SDK version 34.0.0)
Xcode - develop for iOS and macOS (Xcode 14.3.1)
CocoaPods not installed.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin
code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To install see
https://guides.cocoapods.org/using/getting-started.html#installation for
instructions.
Chrome - develop for the web
Android Studio (version 2022.3)
VS Code (version 1.81.1)
Connected device (3 available)
Network resources

Doctor found issues in 1 category.
```
### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @Superuser77SU 
Have you tried restarting Android Studio and then retrying? Please check answers from this [SO thread](https://stackoverflow.com/questions/62593939/cocoapods-not-installed-or-not-in-valid-state) to see if there is any solution fit to yours.

**Comment by rekire** [comment]
Highjacking this bug. I have quiet often randomly the same error `CocoaPods not installed or not in valid state.` when I try to run my Flutter app as MacOS App. I always have to restart Android Studio. This is anoying as hell. Please fix this. I have this error since at least 6 month (always with the latest version)

**Comment by huycozy** [comment]
@rekire Could you share the output of `flutter doctor -v`? We need more detailed information to reproduce and verify the issue. Thanks!

**Comment by rekire** [comment]
Right now I do not have the problem, but here is my current output:
```
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale de-DE)
    • Flutter version 3.13.4 on channel stable at /Users/rekire/dev/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (vor 9 Tagen), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rekire/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/rekire/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/rekire/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

I will rerun it the next time it happens, but I guess the result should be the same,

**Comment by BenardCharles** [comment]
I had similar trouble running `flutter doctor -v` and installing `cocoapods` using `sudo gem install cocoapods`.

![Screenshot 2023-09-25 at 23 23 09](https://github.com/flutter/flutter/assets/34279355/94501f9f-80f6-4863-8ef4-1e8355bb281e)


I solved it using these steps:

1. **Install Ruby with Homebrew**: Start by installing Ruby using Homebrew. Run `brew install ruby` in your terminal.

3. **Update Your PATH**: Add the newly installed Ruby to your system's PATH so that it's recognized. Run `export PATH="/usr/local/opt/ruby/bin:$PATH"`.

4. **Install CocoaPods**: Now, you should be able to install CocoaPods successfully with `sudo gem install cocoapods`.
![Screenshot 2023-09-25 at 23 23 16](https://github.com/flutter/flutter/assets/34279355/ba8433b2-563b-4a7e-845b-0a7195902b2f)



5. **Link CocoaPods (if needed)**: In some cases, you might need to link CocoaPods with Homebrew. You can do this by running either `brew link cocoapods` or `brew link --overwrite cocoapods`.

6. **Re-run flutter doctor -v**: Finally, re-run `flutter doctor -v` in your terminal to make sure everything is working correctly.
