### ISSUE TITLE
[Impeller] Gaussian blur: Re-implement the BlurStyles for the 2-pass blur.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#134178]
We've removed the in-shader mask implementations of the blur styles (https://github.com/flutter/flutter/issues/122658).

After https://github.com/flutter/flutter/issues/122657 is done, we can re-implement BlurStyle.[inner/outer] using the stencil (possibly will need a mask compositing fallback).

**Comment by jonahwilliams** [comment]
I deduped two newly reported issues about this not working. We should fix this after @gaaclarke 's blur patch lands.

**Comment by mariapapag** [comment]
Is there an update regarding the re-implementation BlurStyle?

**Comment by rydmike** [comment]
@mariapapag I'm wondering the same. 

I was just hit **hard** by the lack of `BlurStyle` support when testing our design on iOS. It surprised me that it did not look at all as intended on iOS with Impeller.

Took a while to figure it was the usage of `MaskFilter.blur(BlurStyle.outer, 10)` that caused the difference in the results.

The waves are drawn and animated behind a `BackdropFilter` with `ImageFilter.blur`

```dart
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 6.5, sigmaY: 6.5),
          child: Container(
            height: 300,
            width: double.infinity,
            decoration: BoxDecoration(
              color:
                  Theme.of(context).colorScheme.surfaceVariant.withOpacity(0.5),
            ),
          ),
        ),
```

Thought that was the culprit first, but it was not. When I tried to make repro case, the simpler case was fine. Figured it must be in how the waves are painted behind the blur.  

They are using a custom painter to draw the animated waves, that on the animated wave sine lines uses `MaskFilter.blur(BlurStyle.outer, 10),` in a `Layer`, to give the fuzzy edge on wave line styles. Searching for `MaskFilter` in issues got me here.

Below the diff is shown. It is VERY big, making impeller unusable to us for this design.

In order: **Web** (cancvaskit), **macOS** (Skia), **iOS** (Impeller) and **Android** (Skia).

Tested on Flutter master 3.20.0-10.0.pre.40. 

https://github.com/flutter/flutter/assets/39990307/e133a74a-62a6-4a9a-9728-d2b6653b2ce4

**Comment by gaaclarke** [comment]
For reference, here are the different blur styles rendered with skia:

## normal

<img width="193" alt="normal" src="https://github.com/flutter/flutter/assets/30870216/e353c195-0938-4751-b1ed-f0bc05ec1d73">

## inner
<img width="180" alt="inner" src="https://github.com/flutter/flutter/assets/30870216/cfd4b5fb-0725-464d-8f1d-fd3e765bdc03">

## outer

<img width="182" alt="outer" src="https://github.com/flutter/flutter/assets/30870216/b76df4f8-c262-49ea-8cb5-515a5bf6936e">

## solid

<img width="180" alt="solid" src="https://github.com/flutter/flutter/assets/30870216/7ebbd340-f582-4879-b54b-9513fea9e5e4">

## reproduction code
```dart
void _paint(Canvas canvas, Size size) {
  var maskFilter = const MaskFilter.blur(BlurStyle.solid, 20.0);
  var blurPaint = Paint()
    ..maskFilter = maskFilter
    ..color = Colors.red;
  canvas.drawRect(const Rect.fromLTWH(50, 50, 100, 100), blurPaint);
}
```

**Comment by gaaclarke** [comment]
Here's my recommendation on how these can be implemented:

1) Solid - we already have the input snapshot and the blur snapshot in `GaussianBlurFilterContents`.  Typically we just return the blur snapshot from `GaussianBlurFilterContents::RenderFilter`.  If we could return an entity that draws both of those snapshots we'd have that implemented.
1) Inner - there is already a fragment shader that is reading a subsection of a texture that is calculated from `Snapshot::transform`.  We should be able to adjust the texcoord/vertices in order to get that.  In fact I probably was doing it by accident in the early days of the new blur.
1) Outer - This one is the trickiest.  I'm not sure if it will be easier to draw with a fragment shader that cuts out the section when we draw the snapshot, or if we should use the stencil buffer.  My intuition is leaning towards it being easier to implement with a fragment shader since you can describe the shape with vectors instead of the necessary rasterized cutout that would be required with the stencil buffer.

`Solid` and `Inner` should be pretty easy to implement.

**Comment by rydmike** [comment]
And I of course had to go and implement a design that requires `BlurStyle.outer`, the trickiest one, ouch. But see how pretty the waves look with it though! 😂 💙

**Comment by gaaclarke** [comment]
Oh, on later thought I think `inner` and `outer` will probably have to use the stencil buffer to account for weird shaped objects.  The squares above are a simple case.  Imagine all of those example blurring a cutout of Italy.
