### ISSUE TITLE
Building on mac and linux

### ISSUE THREAD

**Issue by bahmaster1** [flutter/flutter#134207]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Build happens on mac
2. flutter build web --web-renderer html
3. flutter run -d chrome
styles match what's in the code

1. Build happens on linux (ci/cd)
2. flutter build web --web-renderer html
3. flutter run -d chrome
styles are different than when building in mac

### Expected results

when building on linux, the styles match the build on mac

### Actual results

styles are different

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @bahmaster1 
In order to address issue properly, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v` (of both mac and linux environments)
- Screenshots or videos of each environments

Thank you!
