### ISSUE TITLE
Provide a property to determine if a separator should be included after the last element

### ISSUE THREAD

**Issue by yukisakai1225** [flutter/flutter#134272]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There is a situation where I want to display a separator after the last item in ListView.separated. Currently, the separator is only displayed in the gap between the items. I would like to be able to control whether or not the separator is displayed after the last item.

### Proposal

BAD
```Dart
Column(
  children: [
    ListView.separated(
      shrinkWrap: true,
      itemCount: 25,
      separatorBuilder: (BuildContext context, int index) => const Divider(),
      itemBuilder: (BuildContext context, int index) {
        return ListTile(
          title: Text('item $index'),
        );
      },
    ),
    const Divider(),
  ],
);
```

GOOD
```Dart
ListView.separated(
  includeLast: true
  itemCount: 25,
  separatorBuilder: (BuildContext context, int index) => const Divider(),
  itemBuilder: (BuildContext context, int index) {
    return ListTile(
      title: Text('item $index'),
    );
  },
);
```

**Comment by dam-ease** [comment]
Hi @yukisakai1225. Thanks for filing this. From the documentation and the idea of separator:

> Separators only appear between list items: separator 0 appears after item 0 and the last separator appears before the last item.

Separators should be between items but in order to add a divider at the end of the list of items, you might want to check out this as it should suit your use case well:

```dart
ListView.separated(
      shrinkWrap: true,
      itemCount: 25,
      separatorBuilder: (BuildContext context, int index) => const Divider(),
      itemBuilder: (BuildContext context, int index) {
        return Column(
          children: [
            ListTile(
              title: Text('item $index'),
            ),
            index == 24 ? const Divider() : const SizedBox()
          ],
        );
      },
    )
``` 

Closing this as this seems to be working as expected, If you disagree, kindly comment and I'll reopen this.
Thank you!

**Comment by afrish** [comment]
@dam-ease This question is so important that people are trying to find the answers for many years, e.g.:

https://codewithandrea.com/tips/list-view-separated-top-bottom/

https://stackoverflow.com/questions/60826670/flutter-how-to-add-first-top-and-last-bottom-list-with-divider-on-listview-s

In fact, I think most of the people would prefer having the last divider than not having it. Anyway, since it so popular, I think it deserves an official solution, rather than all the nasty hacks that we're trying to use in our projects

**Comment by yukisakai1225** [comment]
Hi @dam-ease , @afrish !

I agree that the method suggested by dam-ease is redundant.
There are two bad points in that code.
- The itemCount needs to be an extra +1
- The last element has to be a Container

Especially the second point creates an extra branch and causes bugs.

The addition of one property solves these problems and will save a lot of people if the formula is addressed.

Sorry for the hard to read English.

**Comment by dam-ease** [comment]
Hi @yukisakai1225 @afrish. Thanks for your responses. I'd reopen and label this for more insights

**Comment by piedcipher** [comment]
We can close this issue as per this 

https://github.com/flutter/flutter/pull/138672#discussion_r1401363002
