### ISSUE TITLE
Generate and check-in pubspec.lock files for most packages in `flutter update-packages --force-upgrade`

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#13428]
...instead of pinning dependencies in pubspec.yaml

This will greatly improve analysis of package usage.

CC @Hixie @mit-mit

**Comment by Hixie** [comment]
Specifically we want to do this for any package in the Flutter repo that represents an app (e.g. the examples, device lab tests, the flutter_tools package). The `flutter`, `flutter_test`, and `flutter_driver` packages in particular will not be affected.

The idea here is to update this script:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart
...so that for these app packages, we don't list the transitive dependencies in the pubspec.yaml, we instead list them in the pubspec.lock and then check that file in.

**Comment by mit-mit** [comment]
Should we also do it for our app template? Looks like we .gitignore it?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/.gitignore.tmpl

**Comment by Hixie** [comment]
I don't think there's much point doing it for the app template. The things we care about will be pinned transitively through `flutter` already.

**Comment by mit-mit** [comment]
Sure, but .gitignoring the lock file is against the pub recommendation for apps:
https://www.dartlang.org/tools/pub/get-started#upgrading-a-dependency

Is there a reason why our app template is setup like that?

**Comment by Hixie** [comment]
Oh, we probably shouldn't `.gitignore` it, no. That's a separate problem than what this issue is tracking though.

**Comment by mit-mit** [comment]
Got it, tracking in https://github.com/flutter/flutter/issues/13559

**Comment by jonahwilliams** [comment]
From more recent bugs, we pin our dependencies because the pubspec.lock does not effect how our users version solving works

**Comment by mit-mit** [comment]
@jonahwilliams can you elaborate? I thought the ideas was to do it for things that are essentially apps, as discussed in https://github.com/flutter/flutter/issues/13428#issuecomment-350102553 ?

**Comment by kevmoo** [comment]
What @mit-mit said ☝️

**Comment by zanderso** [comment]
Is there some motivation for this beyond improving analysis of package usage? Also, I'm curious about how this change would affect analyzing package usage.
