### ISSUE TITLE
flutter build web fail in wayland archlinux

### ISSUE THREAD

**Issue by Silentdoer** [flutter/flutter#134210]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

like title

### Expected results

build success

### Actual results

exception

### Code sample

<details><summary>Code sample</summary>

```dart
just init code
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @Silentdoer 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly. 

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further investigation. Thanks!
