### ISSUE TITLE
[ go_router ] StatefulShellRoute pushed page appears only after hot reload

### ISSUE THREAD

**Issue by eikebartels** [flutter/flutter#134275]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  go_router:
    dependency: transitive
    description:
      name: go_router
      sha256: "5668e6d3dbcb2d0dfa25f7567554b88c57e1e3f3c440b672b24d4a9477017d5b"
      url: "https://pub.dev"
    source: hosted
    version: "10.1.2"
```

</details>

### Steps to reproduce

1. Make use of `StatefulShellRoute` on iOS 
2. Create multiple `StatefulShellRoute`
3. Add some sub pages is `/catalog/page1/`
4. Use `context.push("/catalog/page1/")` to push to the sub page 
 

### Expected results

The page with the path `/catalog/page1/` should get pushed to the navigation stack. 

### Actual results

The page with the path `/catalog/page1/` does not get get pushed to the navigation stack. Only after hot reload the new page is visible. 

The navigation observers are observing the right behaviour, means they think its pushed where in fact it is not

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @eikebartels 
I checked this issue with [stateful_shell_route](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/stateful_shell_route.dart) example, use `context.push(detailsPath)` instead of `GoRouter.of(context).go(detailsPath)` but I can navigate to nested pages normally (similar route like: `/a/details`).

<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/6d2f358c-8171-45a6-b052-8d5d28227a47


</details>

Can you also try this sample code and confirm? If your implementation is different, please provide a minimal sample code. Thanks!

**Comment by eikebartels** [comment]
Hey @huycozy thanks for checking it out. The issue appears using CupertinoTabScaffold. I'll provide an reproducible example
