### ISSUE TITLE
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 644 pos 12: 

### ISSUE THREAD

**Issue by mohammadtabatabaei98** [flutter/flutter#134367]
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 644 pos 12: '() {
      final Animation<double> initial = initialManifest.animation;
      final HeroFlightDirection type = initialManifest.type;
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.

**Comment by huycozy** [comment]
Hi @mohammadtabatabaei98. When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See bug template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
