### ISSUE TITLE
Text.rich's TextSpan text showing ellipsis in the middle of text

### ISSUE THREAD

**Issue by shahbazhashmi** [flutter/flutter#134649]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a Text.rich() with multiple TextSpan as child. Change language of phone to a RTL language but pass English Text to TextSpan.

### Expected results

It should show ellipsis like this `'abc def ghi jkl mno pq...'`

### Actual results

But it is showing

![actual](https://github.com/flutter/flutter/assets/12233332/cb24703d-ff1a-47ae-8eea-70d41ed8f586)

### Code sample

<details><summary>Code sample</summary>

```dart
class MyHomePage extends HookWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    const textStr = 'abc def ghi jkl mno pqr stu';
    const textStyle = TextStyle(color: Colors.black, fontSize: 24);
    const direction = TextDirection.rtl;

    return Scaffold(
      body: Center(
        child: Container(
          color: Colors.orange,
          width: 200,
          height: 100,
          padding: const EdgeInsets.symmetric(horizontal: 10),
          // use Directionality if do not want to change phone language
          child: Directionality(
            textDirection: direction,
            child: Text.rich(
              TextSpan(children: <InlineSpan>[
                WidgetSpan(
                    child: Container(
                  height: 40,
                  width: 54.5,
                  color: Colors.green,
                )),
                const TextSpan(text: ' ', style: textStyle),
                const TextSpan(text: textStr, style: textStyle),
              ]),
              overflow: TextOverflow.ellipsis,
              maxLines: 2,
              softWrap: true,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.20.1)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @shahbazhashmi. Thanks for filing this. This seems to be the expected behaviour, from the documentation of `TextDirection.rtl`, it is for cases in which `The text flows from right to left (e.g. Arabic, Hebrew).` Hence why the ellipsis gets attached to the left which is the end of the text in those cases, testing with those languages, the ellipsis seems to work very fine. Can you give a use case in which you would like to make use of English language with `TextDirection.rtl`?

**Comment by Renzo-Olivares** [comment]
cc @LongCatIsLooong from triage.

**Comment by LongCatIsLooong** [comment]
This is the expected behavior to some degree. The ellipsis is `U+2026` which has a neutral bidi direction, so it's placed on the left side of the line, because the writing direction of the paragraph is set to RTL. Currently the writing direction of the paragraph has to be explicitly specified: https://github.com/flutter/flutter/issues/91738
