### ISSUE TITLE
Hot reloading no working

### ISSUE THREAD

**Issue by dhrubrawat66** [flutter/flutter#134726]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have flutter version -> Flutter 3.13.4 • channel stable
operating system is -> Window

### Actual results

The hot reloading not working on android studio but dart analyzer working properly.
if i run same code on vs code the dart analyzer and hot reloading not working. 

### Flutter Doctor output

![one](https://github.com/flutter/flutter/assets/85351405/1143da8a-7558-4805-a965-3fead1531265)
![one](https://github.com/flutter/flutter/assets/85351405/ab6d9974-4451-4f94-ab60-c46b7b5f6706)

**Comment by huycozy** [comment]
Hi @dhrubrawat66 
I checked this on my Windows host, run app on Android target from Android Studio but can't see the issue; Hot reload works normally.

Do you see this issue on a newly created Flutter project? If it only occurs with specific case, please provide a minimal sample code so that we may verify this. 

Do you notice any error/waring from the output console? If you can observe any, please share it as well (the output of `flutter run -v`)

**Comment by dhrubrawat66** [comment]
![Uploading Screenshot 2023-09-15 164411.png…]()

**Comment by dhrubrawat66** [comment]
i checked it with simple counter app.

**Comment by huycozy** [comment]
>Do you notice any error/waring from the output console? If you can observe any, please share it as well (the output of flutter run -v)

Could you also check this as well? It would be appreciated if you could provide a recorded video to see what happened as well.
