### ISSUE TITLE
IntelliJ missing comma causes code below it to be marked as dead instead of warning about missing comma

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#13485]
Some other unexpected behavior from IntelliJ. One would expect it to warn about a missing comma, the same way we're warned about a missing ; ] or }. However, instead of that, it just marks all code below that point as "dead code" and turns it gray. As you know, dead code also has tips disabled, which doesn't help matters.

Since I was getting warnings for missing ; ] and } I assumed that I wasn't missing anything since I wasn't getting a similar warning. Therefore, I chased my tail for hours trying to figure out what was wrong with other things in the code. Here is an example of code that this actually happened on, with the text changed for simplicity:

```
body: new Container(
        child: new Center(
          child: new Column(
            children: <Widget>[
              new Text("Placeholder Text") //Missed a comma here, 
                                            //all code below here
                                           // is gray "dead code"
              new RaisedButton(child: new Text("Press me!"))
            ],
          ),
        ),
      ),
```

**Comment by sethladd** [comment]
cc @devoncarew @mit-mit

**Comment by devoncarew** [comment]
I do see analysis error in your sample, but they're too subtle in this case. They're associated with a 1-char missing location where the the `;` / `]` / `)` might be.

<img width="408" alt="screen shot 2017-12-12 at 1 14 59 pm" src="https://user-images.githubusercontent.com/1269969/33908929-d27b4312-df3e-11e7-8f5d-11dfbb4e078f.png">

<img width="379" alt="screen shot 2017-12-12 at 1 14 39 pm" src="https://user-images.githubusercontent.com/1269969/33908946-dc14d28a-df3e-11e7-9179-a57fc7741f26.png">

In order to improve this, we'll either need to associate the error with a larger range of text (an enclosing expression?), or improve the in-line error display in IntelliJ. I think the 2nd one may be the right choice here.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#31617

**Comment by ScottS2017** [comment]
Ok, I am able to replicate this pretty consistently so if you're not, please let me know and I can toss together a main.dart file that's about 50 lines and post it here.

Sorry for adding things like this almost daily because I know it can take you all away from more core things but I do believe it's better for me to be a pest now than a thousand people hitting your inboxes about the same things in about 9 months.

If there's anything you think I can help with, please let me know.

**Comment by devoncarew** [comment]
> I am able to replicate this pretty consistently

So, you see the dead code warnings but not the errors? I assumed this was just an information presentation issue.

If you don't see analysis errors, please do post the test file - that'll let us make sure we're seeing the same thing (and it you could post to the moved issue, that'd be great).
