### ISSUE TITLE
[Impeller] Unstable frame rates on high frame rate iOS devices post 16.6.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#134959]
## Background

The frame rate jumps around constantly and the app experience is quite jittery. Annecdotally, this was filled as a regression but we don't actually have a way to confirm that this is due to a behavioral change in iOS.

![image](https://github.com/flutter/flutter/assets/8975114/d754150b-cf0c-4ff4-8ad0-7ea49490a9b4)

### Why are we blocking on waitForNextDrawable.

Assuming  "CPU to Display Latency"  is "Time from present drawable to system being done with drawable", then right now we have times bouncing between ~21 ms and 26ms. Some math: if we finish frame 0 at ~8.3 ms, then the best case scenario that drawable isn't ready until ~29ms, but we started waiting for it at 25ms. That is 4ms of waitForNextDrawable. In the worst case, we actually just miss the frame completely.

![image](https://github.com/flutter/flutter/assets/8975114/eb72bed9-a59f-4a3b-bde3-61b431274a32)

Turning on presentsWithTransaction from a background thead doesn't seem to change the presentation times much, though the appear much more stable and seemingly cause our rendering code to not block on waitForNextDrawable at all. Its unclear how this works, but from running metal system trace there were no additional clues. presentsWithTransaction from the main thread had no such effect.

### Why is the display latency so high?

Interestingly if I test on a non high frame rate iOS device, the display latency is comparable. but with 16ms frames we have a lot more leeway. Searching apple forums for info on this turns up nothing. Interestingly, if I follow the advice in the profile above and set the `CAMetalLayer.opaque` property to `YES`, then presentation delay drops to 13ms. This may be an option for "regular" flutter apps but not add2app, but I haven't measured this.

![image](https://github.com/flutter/flutter/assets/8975114/b34f5064-6ac0-483c-94f9-2b0168d5ddee)

### How can we work around blocking on waitForNextDrawable?

Generally the advice I've seen on Apple docs/forums is that `CAMetalLayer.nextDrawable` should be one of the _last_ things we do in frame. That is, rather than use the metal drawable texture as the resolve for our onscreen rendering, we should actually create our own swapchain and then blit into the drawable at the end of the frame. In the example, above where we waited for the next drawable for ~4ms, means that on average we have **half** as much time to complete the frame.

### Note on our vsync

Something odd I've noticed is that regardless of whether metal system traces says that it presented a drawable for 8, 16 ms, the CADisplayLink is always firing at 8ms. Even the previous timestamp doesn't seem to represent when we actually presented our drawable, just the last system vsync.

I'm not sure if this is working as expected, but we don't have any backpressure on this system beyond the pipeline count until we hit the raster thread, so its very possible for the UI thread to run ahead. In fact, this is very much a goal of the UI thread - except that I suspect we're making things worse but not dropping frames earlier in the pipeline. I've tried to make changes to this but it is difficult. I think ideally the vsync implementations would have some awareness of the last time that flutter actually presented so that it could smooth things out. i.e. if the last frame duration was 16ms then assume the next one will take 16ms. Its possible we can make applications that are already janky better by adjusting this logic.

### Dead ends

I had preveiously investigated unconditional thread merging, as this allowed presentsWithTransaction uncontionally. On further investigation, I found that this didn't actually help the frame stability, instead it triggered code in the vsync waiter to throttle our frame rate to 80.

## Short-term Options

* Cap device frame rate at 80. This seems to gauarantee that we dont have terribly unstable frames but is defiitely a "feels bad man" solution.

* Apply opaque=YES to CAMetalLayer. I'm not sure if its possible to create a "transparent" flutter view on iOS. By default we clear the screen to solid black, but I think you applications could punch through this. We could always give an opt out.

* PresentWithTransaction = YES and give apps a Plist Opt out. Despite the fact that we don't know how/why this works, and the fact that it breaks add2app and certain plugins, it definitely does fix the rendering jankiness. Last resort.

## Longer-term options

* Rewrite iOS rendering to acquire metal drawable later, including partial repaint. This will require a substantial reworking of partial repaint. Porting this change to Skia may be difficult without removing partial repaint entirely.

**Comment by jonahwilliams** [comment]
Opaque was set to NO in https://github.com/flutter/engine/pull/30664 

Can we revisit this decision?

**Comment by dnfield** [comment]
Sorry, I linked you the wrong PR - it was reverted in https://github.com/flutter/engine/pull/31710

**Comment by jonahwilliams** [comment]
Ahh got it. Makes sense then , I'll keep digging on this.

**Comment by jonahwilliams** [comment]
After updating to iOS 17, I do not see presentation times jumpting above 22ms, which means we generally always have enough time to render simple applications. We should still try to fix the above issues, but they may be less critical.

**Comment by jonahwilliams** [comment]
Proposed solution is documented in https://github.com/flutter/flutter/issues/138490

**Comment by knopp** [comment]
Looking at the system trace for the opaque layer - it has 'Direct to Display' set to yes, which I assume would mean it it skips the compositor. That would explain lower latency. Though I was under the assumption this can only happens when there are no other layers (which would include the status bar). Maybe that's not the case?

**Comment by knopp** [comment]
I'm wondering if the CPU to Display Latency is a red herring. I just ran some metalkit examples on macOS at 120hz, in some the CPU to display latency is over 32ms, and yet the average frame time is consistent 8.33ms.

**Comment by knopp** [comment]
I think I have a pretty good idea what is going on. I documented it [here](https://github.com/flutter/engine/pull/48141#issuecomment-1817446598), but just in case, I'll put a quick summary here.

`waitForNextDrawable` is a symptom, not the cause. The difference between `presentsWithTransaction` on and off is what happens when iOS does not manage to present the requested frame in time:

- With `presentsWithTransaction` enabled, this frame will simply be replaced by next frame (you can verify this by checking the `presentedTime` on drawable. It will never be displayed by the compositor.

- With `presentsWithTransaction` disabled, the frame will be displayed as soon as possible and for full duration. Because this increases the presentation latency, `waitForNextDrawable` will now block almost for duration of entire frame. And it will keep blocking, until it slows down the raster thread enough so that metal layer can keep up. After things get bad enough on raster thread where it skips entire frame, `waitForNextDrawable` will not block anymore. This is what you can see this being a continuous pattern. It starts with a CAMetalLayer missing deadline (`[layer nextDrawable]` will begin blocking) and ends withs with raster thread skipping a frame, which lets the CAMetalLayer keep up.

I have a [quick prototype branch](https://github.com/knopp/engine/commits/implement_frame_dropping) that attempts to drop the frame when CAMetalLayer can't keep up, trying to emulate the behavior of `presentsWithTransaction` to a degree.

Circular progress indicator from flutter gallery with [frame dropping](https://github.com/knopp/engine/commits/implement_frame_dropping):

<img width="969" alt="progress-indicator-frame-drop" src="https://github.com/flutter/engine/assets/96958/dd30a803-a0f8-4aea-be84-d2d147df4c89">

Same thing on main:

<img width="965" alt="progress-indicator-main" src="https://github.com/flutter/engine/assets/96958/3daff764-6031-4c0a-b8f7-d038d5be8671">

In this example, only one frame gets dropped at the beginning of transition from gallery menu to example. That is enough to remove the delay from `[layer nextDrawable]`.

**Comment by jonahwilliams** [comment]
> waitForNextDrawable is a symptom, not the cause.

FWIW we know its not the cause, I documented the cause in https://github.com/flutter/flutter/issues/138490 . iOS takes too long to present, sometimes consistently, sometimes not. in 16.6 it was very inconsistent.

If iOS 120hz isn't actually able to sustain consistent 120hz then we need to merge the threads and present with transaction.

**Comment by knopp** [comment]
> > waitForNextDrawable is a symptom, not the cause.
> 
> FWIW we know its not the cause, I documented the cause in #138490 . iOS takes too long to present, sometimes consistently, sometimes not. in 16.6 it was very inconsistent.
> 
> If iOS 120hz isn't actually able to sustain consistent 120hz then we need to merge the threads and present with transaction.

The frame delays are quite rare, and may depend on other factors (i.e. have work on ui thread), unfortunately one "untreated" frame delay is enough for things to go south on raster thread.

**Comment by knopp** [comment]
Just a heads-up - this should be improved by https://github.com/flutter/engine/pull/48226 - I'd suggest trying current master with 
```
<key>FLTUseFlutterMetalLayer</key>
<true/>
```
added into Info.plist.

**Comment by jonahwilliams** [comment]
We've made the FlutterMetalLayer the default with https://github.com/flutter/engine/pull/54121
