### ISSUE TITLE
Devicelab test running for 53 years #2

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#134951]
I'm getting another instance of https://github.com/flutter/flutter/issues/134828 which is a manifestation of https://github.com/flutter/flutter/issues/131501.  This is the same test but I had to move it to a new device which caused it to get stuck again.

cc @drewroengoogle (gardener)

**Comment by drewroengoogle** [comment]
I took a look at some tasks that are showing an unreasonably long run time, and the tasks for those have all been scheduled but are currently pending due to all of the bots being in use. It probably would be clearer if the dashboard showed something like "Pending" over the unreasonably long build time, though. This is only occurring on builds that are scheduled but have to wait to start.

@ricardoamador Is it expected that builds are scheduled to start before there is capacity for them? Every build that has an unreasonably long run time also has an associated build that is pending like this: ![Screenshot 2023-09-18 at 12 06 22 PM](https://github.com/flutter/flutter/assets/102626803/e33863e6-db99-46b8-aba6-6558e3330a2b)

**Comment by drewroengoogle** [comment]
I should also note that once these pending builds start, the tile on the dashboard looks normal

**Comment by ricardoamador** [comment]
@drewroengoogle @gaaclarke there have been pretty recent changes to this, I think less than a month or two old that might affect this. I can check the logic again. But I believe they should be put to pending as that is the state when the task is waiting for the bot. I will take a look.

**Comment by ricardoamador** [comment]
@gaaclarke is it showing queueing for 53 years? We should have an open issue for that. We see that from time to time.

**Comment by ricardoamador** [comment]
Oh, I see another issue here. Some of the tasks that are skipped like the yaml rollers have a pending clock that just keeps running even though the tasks will never get scheduled.

**Comment by gaaclarke** [comment]
The big problem isn't the reporting of the 53 years so much as the fact that the devicelab test seems stuck and the last 20 or so runs are just grey boxes.  The original tasks appear to be stuck in the 53 years positions.

**Comment by drewroengoogle** [comment]
The hello_world target seems to be running again.

My theory is that it looks like the initial target from a couple of weeks ago was triggered during a LUCI outage, and perhaps our datastore marked it as in progress, but the LUCI build never actually started as a result. This may have caused cocoon to constantly be waiting for the "in progress" build to finish even though it was never going to. After rerunning the latest build and the previously in progress ones, the builder is starting to backfill the old targets.

Perhaps a feature to be filed to automatically reset any tasks that are clearly over the timeout period that is defined in ci.yaml?

**Comment by ricardoamador** [comment]
Okay @drewroengoogle @gaaclarke , I was able to dig some more and found the culprit. It appears that someone tried to reset the tasks twice which lead to two instances of the task being stuck in the "In Progress" state. When the request is made we (the scheduler) sets the status to "In Progress" before sending the request to LUCI. 

As found in the log:
![image](https://github.com/flutter/flutter/assets/32242716/7a23a7ac-47f6-49a8-a06a-270af992586f)

And as seen in the dashboard:
![image](https://github.com/flutter/flutter/assets/32242716/da19d704-bb11-4040-a872-80a8a796b42d)

Since LUCI had an outage it was not scheduling anything and we can see errors in the logs for the tasks that we were trying to schedule:

![image](https://github.com/flutter/flutter/assets/32242716/f010da28-498b-477e-94db-d33406bee856)

This LUCI outage coupled with the two tasks stuck in "In Progress" means that the scheduler will not schedule more than one at a time for a given column in Flutter resulting in the deadlock here. This also means that the backfiller could schedule newer tasks.

So yeah just a perfect storm of circumstances.

**Comment by drewroengoogle** [comment]
Thank you @ricardoamador!

Are there any issues that need to created from this do you think?

**Comment by drewroengoogle** [comment]
Marking this as "Fixed" in the queue, since the original issue has been mitigated.

**Comment by ricardoamador** [comment]
We should probably open an issue for reseting stuck tasks as you said. Though we can currently do this with reset prod task. But I can open an issue for Infra to follow up on this and see what can be done.

**Comment by drewroengoogle** [comment]
Does reset prod task automatically run, or is that only triggered manually?

**Comment by ricardoamador** [comment]
You would need to automatically trigger it currently.
