### ISSUE TITLE
didChangeMetrics  在某些机型不生效 特别是鸿蒙

### ISSUE THREAD

**Issue by luozhouliang** [flutter/flutter#134915]
![3dcb21d1017c290b5b48437ceec103d(1)](https://github.com/flutter/flutter/assets/21219963/f5463546-f925-4da2-90ea-b535526ae4ff)
它不会进入到此方法，我在另外的机型上能正确运行

**Comment by huycozy** [comment]
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since there is not enough information to verify the issue. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
