### ISSUE TITLE
Add `ScrollViewKeyboardDismissBehavior.onVerticalDrag` and `onHorizontalDrag`

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#134907]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a search screen with a `SingleChildScrollView` which has `ScrollViewKeyboardDismissBehavior.onDrag`
As the first child, I have a horizontal `ListView` for recent searches.
The second child is a vertical `ListView` composed of the search results which has `shrinkWrap = true` and `NeverScrollablePhysics`
When the screen is dragged vertically, the keyboard gets dismissed.
When the horizontal ListView is scrolled, the keyboard gets dismissed.

And I want the keyboard to dismiss when the screen is dragged only vertically. When user scrolls the recent searches, the keyboard should remain since we don't need extra real estate to see the rest of the results.

### Proposal

If we had 2 more enum values for `ScrollViewKeyboardDismissBehavior` like;

- onVerticalDrag
- onHozrizontalDrag

we would have more flexibility to dismiss the keyboard.

**Comment by Piinks** [comment]
Hi @aytunch you should set the horizontal ListView.keyboardDismissBehavior to ScrollViewKeyboardDismissBehavior.manual to prevent horizontal drags from dismissing the keyboard. 

Since a ScrollView (or also ListView) only scrolls in one direction, the proposed onVerticalDrag and onHorizontalDrag would not work for a single ScrollView. In the nested case you described above, there are multiple ScrollViews and they do not know about each other or have an effect on each other's behavior.
