### ISSUE TITLE
Linux Fuchsia precache is failing on engine to framework rolls

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#135189]
https://github.com/flutter/flutter/pull/135184/checks?check_run_id=16984358790

Are these artifacts not getting built? Was there a change to the recipes?

**Comment by jonahwilliams** [comment]
Looks like there is no tagged artifact: https://chrome-infra-packages.appspot.com/dl/flutter/fuchsia-debug-symbols-x64/+/git_revision:991f529c64841a4821971862964ca216f1889a6d

**Comment by godofredoc** [comment]
Failing task:
https://ci.chromium.org/p/flutter/builders/try/Linux%20fuchsia_precache/63865?

**Comment by godofredoc** [comment]
Revoked staging account permissions to write to cipd.

**Comment by drewroengoogle** [comment]
> Revoked staging account permissions to write to cipd.

@godofredoc For my understanding, can you explain how the staging account write permissions are related to this issue?

**Comment by godofredoc** [comment]
Moving to P2 as the issue was mitigated and we need to land a few changes to make the old and new fuchsia build coexist.

**Comment by godofredoc** [comment]
This is the full description of what happened:

* Both "Linux Fuchsia"(old build) and "Linux linux_fuchsia"(v2 build) are running. One in staging and the other one in prod.
* In preparation to move "Linux Fuchsia" to staging I had to grant the staging service account permissions to write to CIPD
*  "Linux linux_fuchsia" is faster and won the race to write the flutter/fuchsia cipd package but because it is missing the "--upload" flags on the debug symbols it didn't upload those.
* The scripts handle that state correctly but there is extra logic in the engine.py recipe to identify if the should upload the debug symbols that instead of checking its own package e.g. `flutter/fuchsia-debug-symbols-x64` it checks whether `flutter/fuchsia` exists which in this case it did exist.

Next steps to prevent this from happening:

* `--upload` needs to be added to the `Linux linux_fuchsia` configuration for debug_symbols upload.
* the logic to prevent packages from being uploaded needs to be removed from the engine.py recipe as it is already handled correctly by the python scripts.
* `Linux linux_fuchsia` is also missing the upload of the debug symbols to the fuchsia gcs bucket.

**Comment by godofredoc** [comment]
The missing piece to close the loop in this bug is to upload the debug symbols from subbuilds

**Comment by godofredoc** [comment]
A script needs to be created for https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/engine.py;l=1040?q=Upload%20to%20Symbol%20Server%20for%20arch&ss=flutter%2Frecipes
