### ISSUE TITLE
[web] drawRect benchmark regressed for Skwasm

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#135167]
Reported by Skia Perf: https://flutter-flutter-perf.skia.org/e/?keys=Xed2eff54443a26af4263ce51cdfc1509&selected=commit%3D36940%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Ddraw_rect_variable_paint.skwasm.drawFrameDuration.average%252Ctest%253Dweb_benchmarks_skwasm%252C&xbaroffset=36940

<img width="1545" alt="Screenshot 2023-09-20 at 11 42 12 AM" src="https://github.com/flutter/flutter/assets/211513/1e62c398-6fa0-4619-847b-9bfd21264a57">

Happened on this engine roll: https://github.com/flutter/flutter/commit/07e70a40867ca9abb276c832e362a7e051d45576

**Comment by eyebrowsoffire** [comment]
This is probably expected actually, with https://github.com/flutter/engine/pull/46061. I think we might have been cheating the numbers a bit since the platform view changes went in, because what ended up happening is that when the web worker was backed up, we just dropped frames which looks really fast on the UI thread.

If you zoom out a bit on the graph, you can see that it's just returning to the same level that it was before the platform views change.

I really do need to add some measurements to the benchmarks for dropped frames and for total end-to-end render time.
