### ISSUE TITLE
[Shaders] runtime compilation of shaders from strings, w/o asset bundle

### ISSUE THREAD

**Issue by chipweinberger** [flutter/flutter#135340]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use cases

* **User Uploaded Shaders (our use case).** Our app renders midi music.  We want to support custom "themes".  i.e. fully custom shaders uploaded by the user as text strings. 
* **Runtime shaders.** Some shaders are easier to make at runtime, based on dynamic properties. 
* **Single file shader examples.** If the shader can be a Dart string, simple shader examples can be single files. 

### Proposal

AFIACT, shaders must be provided at compilation time. **See Docs**: https://docs.flutter.dev/ui/design/graphics/fragment-shaders

```
flutter:
  shaders:
    - shaders/myshader.frag

FragmentProgram.fromAsset('shaders/myshader.frag');
```

**Proposal**: implement runtime compilation, i.e.`FragmentProgram.fromString('shaders/myshader.frag');`

**Comment by jonahwilliams** [comment]
We're not going to add support for this, as we don't plan to ship multi-megabyte shader compilers by default with the engine. There has been some discussion about providing a specification for the format the engine accepts so that developers can choose to bundle a shader compiler if they are willing to pay the code size cost, but this is blocked by us stabilizing the asset format after we ship Impeller on Android.

**Comment by chipweinberger** [comment]
Thanks for the very quick response. 

Glad to see this is on your radar. Is there an issue for tracking this work? I looked for one but did not find it.

**Comment by jonahwilliams** [comment]
Ahh yes, my bad: https://github.com/flutter/flutter/issues/124759

**Comment by chipweinberger** [comment]
thanks. I'll close this issue in favor of that one!
