### ISSUE TITLE
title=%5Btool_crash%5D+_TypeError%3A+%28%230++++++AndroidApk.fromAndroidProject+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fapplication_package.dart%3A122%3A61%29%29

### ISSUE THREAD

**Issue by alanlance** [flutter/flutter#135342]

**Comment by huycozy** [comment]
Hi @alanlance 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
