### ISSUE TITLE
[Impeller] Expensive IO/Worker tasks can slow down raster thread work.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#135443]
Even after https://github.com/flutter/flutter/issues/134452 , sufficiently complex background work can slow down the raster thread work. For some reason, this is actually worse on Vulkan than on GLES. I've deduped a number of other bugs into this instance. While the immediate fix is to use appropriately sized images, I'm filling this as a long term issue to better understand our options here:

<img src="https://user-images.githubusercontent.com/8975114/267133353-715982dd-92c5-4fd2-aeda-681dc280049e.png"/>

**Comment by delfme** [comment]
Hello @jonahwilliams please find attached below a video which showcase this issue in our app with latest master. On iOS it performs smooth. We also shared a simplified sample + timeline here https://github.com/flutter/flutter/issues/139447#issuecomment-1869718632. It was closed to refer to this issue only. Given it is P3, we shouldnt expect any significant progress on this anytime soon, but issue is so severe that we cannot ship app on android.

https://github.com/flutter/flutter/assets/53510751/0fcd6bed-941b-4cab-aa20-aa676a7c7bf3

**Comment by delfme** [comment]
> which showcases this issue in our app with latest master (release mode, device Xiaomi mi lite 11 5g, display refresh rate 90Hz, android 13, vulcan engine). 

Added device specs.

**Comment by delfme** [comment]
Was wondering, are we sure that issue is related to IO/Worker tasks? Coz the images in the grid are loaded to cache, I mean the janks occur while scrolling images already loaded.

**Comment by delfme** [comment]
Issue was caused by 
```
override fun getRenderMode(): RenderMode {
        return RenderMode.texture
}
```
Info here on why we added it to MainActivity.kt:
https://github.com/flutter/flutter/issues/139354#issuecomment-1915355355

After we understood that `getRenderMode()` was causing the glitch/lags during screen animation and we removed it, we tested the GridView scrolling as well, and issue is gone 👍 @johnmccutchan adding this also here coz it was thought that the janky scrolling could be related to this issue. Also, in case you guys gonna add  `getRenderMode()` for TLHC-related purposes, it is good to know that it could generate some side-effects.

https://github.com/flutter/flutter/assets/53510751/47ecf7d5-829d-43d3-967d-96990cb99638
