### ISSUE TITLE
[Google Tests] Make rebase tips more clear

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#135543]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Google Tests.

### What is happening?

Typos with Google Tests rebase tips: *Please rebase your PR to tip of tree. Your PR is out of date*.

### Steps to reproduce

https://github.com/flutter/flutter/pull/135401/checks?check_run_id=17119088156

### Expected results

Please rebase your PR to the top of the tree. Your PR is out of date

**Comment by christopherfujino** [comment]
I think "branch tip" is a commonly used phrase? https://stackoverflow.com/questions/16080342/what-is-a-branch-tip-in-git

**Comment by christopherfujino** [comment]
However, if this is not clear, perhaps we should use HEAD instead?

**Comment by AlexV525** [comment]
Oh TIL, maybe we can use *rebase to the most recent commit of the tree*? That would also help the translator to produce a more friendly translation. :)

**Comment by christopherfujino** [comment]
> Oh TIL, maybe we can use _rebase to the most recent commit of the tree_? That would also help the translator to produce a more friendly translation. :)

Ahh, good idea!

**Comment by CaseyHillers** [comment]
I sent a few internal CLs that delete this logic which will roll out in a few hours.

The issue was it was failing every PR on merge issues if they were older than what's in Google. Occasionally, Google is only behind by a few commits, which would result in every PR being marked as failing. Instead, it should try to merge the PR into Google to get the merge signal.
