### ISSUE TITLE
Flutter with Integrated Unity fails to execute.

### ISSUE THREAD

**Issue by likwifi** [flutter/flutter#135598]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What target platforms are you seeing this bug on?

iOS

### Problem description
<summary>Flutter with Integrated Unity fails to execute.</summary>
I'm using flutter with Unity build integration.
After recent upgrade to IOS 17 and Xcode 15.
I'm failing to run my application.
One of the solutions that was mentioned at github was to open xcode and run in profile mode.
However as Unity requires physical device only for running I'm getting error that says Unityframework.h is required.

**Comment by huycozy** [comment]
Hi @likwifi 
The goal of this Github repo is not to give assistance on personal code, but to improve flutter reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

Thank you!

**Comment by likwifi** [comment]
Thanks for the update,
My issue was fixed by upgrading flutter and cocopods to latest version.
