### ISSUE TITLE
Error of android

### ISSUE THREAD

**Issue by WinikeCuamba** [flutter/flutter#135663]
erro de flutter " unexpected lock protocol found in lock file expected 1, found 0"

This erro is in my flutter app when a run and build in Android

**Comment by huycozy** [comment]
Hi @WinikeCuamba 
Please see [this](https://stackoverflow.com/questions/31743942/errorunexpected-lock-protocol-found-in-lock-file-expected-3-found-0) StackOverflow if it helps. 

This looks like an issue with Gradle rather than Flutter itself. Closing as this is neither a Flutter framework bug nor a feature request. Next time when open an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).
