### ISSUE TITLE
CircleAvatar with border

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#13566]
Is it possible to set a border to CircleAvatar?

How can i do ?

Thanks

**Comment by sethladd** [comment]
Hi! would you be willing to ask this question on Stack Overflow? There's a higher chance to get an answer there, as many more of our helpful community is there.

**Comment by Hixie** [comment]
Not currently, but we can take this as a feature request.

**Comment by bontris** [comment]
My hack to get done was wrap the CircleAvatar inside a Container like this:

new Container(
  child: new CircleAvatar(
    child: const Text('C'),
    foregroundColor: Colors.white,
    backgroundColor: const Colors.blue 
  ),
  width: 32.0,
  height: 32.0,
  padding: const EdgeInsets.all(2.0), // borde width
  decoration: new BoxDecoration(
    color: const Color(0xFFFFFFFF), // border color
    shape: BoxShape.circle,
  )
)

**Comment by lcecliff** [comment]
I'd also like elevation with shadow

**Comment by matthew-carroll** [comment]
Talked with @Hixie and it sounds like we should leave `CircleAvatar` as-is so that it continues to match the material spec.  

If something similar to `CircleAvatar` is required then it can be built as a custom `StatelessWidget` without much trouble.  `Container` can be shaped as a circle and it includes border and shadow decorations, and also allows you to set an explicit width/height, which corresponds to the diameter of the circle. From there you can set whatever `child` you'd like.  You can display an avatar image, or display initials, or anything else.

Example:
```dart
new Container(
  width: diameter,
  height: diameter,
  decoration: new BoxDecoration(
    // Circle shape
    shape: BoxShape.circle,
    color: backgroundColor,
    // The border you want
    border: new Border.all(
      width: 2.0,
      color: Colors.white,
    ),
    // The shadow you want
    shadow: [
      new BoxShadow(
        color: Colors.black.withOpacity(0.2),
        blurRadius: 5.0,
      ),
   ]
  ),
  child: contentInCircle,
);
```

If you're not sure what the existing `CircleAvatar` is doing under the hood, here is the implementation:
https://github.com/flutter/flutter/blob/b83eb465fd51fedd9fabb1d2494e66e8621dc1d7/packages/flutter/lib/src/material/circle_avatar.dart 

I'm going to close the ticket.  @Hixie please re-open if the decision is made to alter `CircleAvatar` to support a border and or shadows.

**Comment by naveenyadav15** [comment]
We can just do this: 
```
CircleAvatar(
                  radius: 35,
                  child: CircleAvatar(
                    radius: 34,
                    backgroundColor: Colors.white,
                    foregroundColor: Colors.black,
                    child: Icon(
                      Icons.forward,
                    ),
                  ),
                ),
```

**Comment by AbhishekAOne** [comment]
I used this to create a bordered circular image.

 CircleAvatar(
                backgroundColor: Colors.amberAccent,
                radius: 50.0,
                child: CircleAvatar(
                  radius: 48.0,
                  backgroundImage: AssetImage('assets/thumb.jpg'),
                ),
              ),

**Comment by chitgoks** [comment]
I hope this gains traction. would be a neat option compared to having to add more widgets just to show a border.

**Comment by chriswiesner** [comment]
I'd like to only have the border. That's currently not possible bc. you cannot specify a transparent background color - it's falling back to the primary color then.

**Comment by akram-95** [comment]
> I'd also like elevation with shadow

Hello
