### ISSUE TITLE
[Impeller] Create a dart:ui fixtures based native test harness that renders talks to Skia Gold directly.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#135693]
Discussed during the last Impeller Weekly, this test harness will allow exercising dart:ui APIs to render content using either the Impeller or legacy rendering backend using SwiftShader (likely OpenGL ES or Vulkan).

### Requirements

* Allows Dart fixtures to be written that use `dart:ui` APIs.
  * An existing harness that looks the closest to this today is `embedder_unittests`. Though, rendering is not its primary focus and the few pixel tests it has are mac guyver'd crudely.
* Allows exercising the Impeller rendering backend using SwiftShader.
  * Likely just Vulkan to begin with.
* The harness talks to the Flutter Engines instance of Skia Gold directly.
  * Should be doable since we already have a Dart isolate running during test execution.

This should also be the sole test harness in the engine that talks to Skia Gold and the one way of doing pixel tests. One this harness exists, existing tests can be migrated to use it (https://github.com/flutter/flutter/issues/135695).

**Comment by chinmaygarde** [comment]
cc @dnfield @gaaclarke @matanlurey @flar @zanderso. Took a stab at summarizing what we discussed yesterday.

**Comment by matanlurey** [comment]
Summary SGTM.

> this test harness will allow exercising dart:ui APIs to render content using either the Impeller or legacy rendering backend using SwiftShader

Just for sake of prioritization, I would consider getting this working for the Impeller backend e2e higher priority than the Skia backend (if only because the Skia backend is already well-tested through framework tests and existing infrastructure). It would be nice eventually to be able to run the same tests in both environments and visually diff them (not as a pixel test).

**Comment by dnfield** [comment]
I'm starting with making `flutter_tester --enable-impeller` work with Swiftshader/Vulkan.

I have a local patch that is pretty close to working. Finding a few test failures that are either real or related to slight rendering differences.

**Comment by chinmaygarde** [comment]
Hmm, `flutter_tester` is a bit different from what I was expecting with the Dart fixtures targeting `dart:ui`. But making it work with SwiftShader/Vulkan seems like there would be some overlap.

I setup embedder_unittests harness and have some context on how to do something similar here. Happy to divvy up the work. I have no idea how to talk to Gold from Dart though.

**Comment by dnfield** [comment]
There are already embedder/shell based tests that target impeller, although I'm not sure if they're set up to render pixels.

The advantage of flutter_tester is that we could also make it work with framework tests that have lots of existing golden tests we could look at.

**Comment by dnfield** [comment]
Part of why I pursued https://github.com/flutter/engine/pull/46389 is because we _already_ have shell/embedder unittests running impeller. Grep for `settings.enable_impeller = true` in `*unittests.cc`.

I don't think that any of them are currently wired up to use swiftshader, but that shouldn't be too hard if we really need it.

**Comment by dnfield** [comment]
I'm going to close this as completed - `flutter_tester --enable-impeller` now works and there are tests in `canvas_test.dart` that use it to talk to Skia Gold.
