### ISSUE TITLE
Flutter ExpansionPanelList Widget now working both in the flutter example and in my app where I've already implemented it and was working fine few months ago.

### ISSUE THREAD

**Issue by SAnetwork2020** [flutter/flutter#135895]
https://github.com/flutter/flutter/blob/ead455963c12b453cdb2358cad34969c76daf180/packages/flutter/lib/src/material/expansion_panel.dart#L160
This code is not working in the current flutter version. I implemented this several month on my app and it's working fine but upon revision of my code and upgrade to the new flutter version, it's not working both the example code and the one in my app which was working perfectly before is no more expand as it should. Please can some help me out here??

**Comment by SAnetwork2020** [comment]
I just got it fixed by changing the bool expression in the expansioncallback like this

      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = isExpanded;
        });
      },
instead of this, which was what is on the flutter sample and was working the last time I worked on it:
expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },

**Comment by dam-ease** [comment]
Hi @SAnetwork2020. Thanks for filing this. As for the issue with the example in the doc, it has been fixed by per https://github.com/flutter/flutter/commit/af79b4c7a3a425814eabc8df32708b1426643f5c. You can check out https://master-api.flutter.dev/flutter/material/ExpansionPanelList-class.html for the updated example.
Thanks!
