### ISSUE TITLE
This was fixed by https://github.com/dart-lang/sdk/issues/39848 and rolled into Flutter at 1.13.6-pre.29. Is anyone still seeing this on a newer version of `master` than that?

### ISSUE THREAD

**Issue by inaamflutterdev** [flutter/flutter#136053]
This was fixed by https://github.com/dart-lang/sdk/issues/39848 and rolled into Flutter at 1.13.6-pre.29. Is anyone still seeing this on a newer version of `master` than that?

_Originally posted by @DanTup in https://github.com/flutter/flutter/issues/47438#issuecomment-574386820_

**Comment by inaamflutterdev** [comment]
yes I am facing this issue whenever I import new package it said isn't a dependency of the importing Package. 
On the other hand we are using it in the code. And if we remove the import line he code does not worked.

**Comment by dam-ease** [comment]
Hi @inaamflutterdev. Please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Thank you!

**Comment by inaamflutterdev** [comment]
Thanks for contacting me. But I have to tell you that I have solved the
problems. There were some minor mistakes made by me.
