### ISSUE TITLE
[path_provider] if download folder is not present , getExternalStorageDirectory doesn't return storage folder

### ISSUE THREAD

**Issue by braver90** [flutter/flutter#136064]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Delete download folder
2. use getExternalStorageDirectory to retrieve storage folder

### Expected results

1. Delete download folder
2. use getExternalStorageDirectory to retrieve storage folder
3. the root storaged folder is returned

### Actual results

if download folder is absent getExternalStorageDirectory method  returns app local storage folder. To be clear it returns "/storage/emulated/0/Android/data/com.example.app/files"

### Code sample

<details><summary>Code sample</summary>

```dart
Future<void> saveBase64File(required String rawBase64,
    required String fileName,) async{
String _androidDownloadPath = "/storage/emulated/0/Download";
 if (!await Directory(storagePath).exists()) {
          storagePath = (await getExternalStorageDirectory())?.absolute.path;
        }
 String fullPath = savePath + "/" + fileName;
Uint8List bytes = base64.decode(rawBase64).buffer.asUint8List();
 File file = await File(fullPath).create();
        await file.writeAsBytes(bytes);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @braver90. Thanks for filing this issue. I am able to reproduce this on my end as well but this seems to be the expected behaviour reading through the [doc](https://pub.dev/packages/path_provider#supported-platforms-and-paths), can you provide more information on what you have without deleting the Download folder?

<img height=500 src="https://github.com/flutter/flutter/assets/53122008/828cfe7a-5c46-48a9-bf60-e0fd8e4655a1">

[Code Sample Used](https://pub.dev/packages/path_provider/example)

**Comment by braver90** [comment]
The expected behavior is that the method returns “/storage/emulated/0/”,it should be the storage dir,which allows to create the download folder in the right folder. In Fact as you can see in my example, saving a file in the “/storage/emulated/0/Android/data/com.example.app/files” makes it really difficult for a user to retrieve it.

**Comment by dam-ease** [comment]
Thanks for your response. From the documentation, the supported directories on each platform are attached https://pub.dev/packages/path_provider#supported-platforms-and-paths. So the expected behaviour is what you currently observe. Are you proposing that this directory be added?  You might want to file a detailed proposal.
