### ISSUE TITLE
imageCache API doc improvements

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13616]
Here's inspiration for what we should add to the API docs (which I put on StackOverflow):
>Create a class that inherits from WidgetsFlutterBinding. Override createImageCache on that class to return the ImageCache implementation of your choice. Call the constructor on that class before you call runApp.
>
>There's one binding per application. The first binding (subclass of BindingBase) that is created gets to be that binding. Calling runApp() instantiates the WidgetsFlutterBinding binding, which is usually what you want. One of the classes that WidgetsFlutterBinding mixes in, the ServiceBinding, introduces createImageCache as a way to let you override the image cache. It calls that method, and sets the global imageCache to whatever that method returns.

Something should be added to ImageCache, createImageCache, imageCache, ServicesBinding.imageCache.

**Comment by rrousselGit** [comment]
> One of the classes that WidgetsFlutterBinding mixes in, the ServiceBinding, introduces createImageCache as a way to let you override the image cache.

Based on the last alpha version, this logic is in `PaintingBinding` not `ServicesBinding`.

**Comment by mattylase** [comment]
Regarding docs on the whole, it would be really helpful if there was a passing mention of `ImageCache` existing at the top level `Image` widget documentation. I just found out this existed after a few days of being confused as to why my widget wasn't updating when deleting and re-saving over a file loaded by `Image.file`.

**Comment by alectogeek** [comment]
Is there any news?

**Comment by markusaksli-nc** [comment]
Closing as this seems fixed with the addition of the sample in [ImageCache](https://api.flutter.dev/flutter/painting/ImageCache-class.html) and crossreferencing in [createImageCache](https://api.flutter.dev/flutter/painting/PaintingBinding/createImageCache.html), [imageCache](https://api.flutter.dev/flutter/painting/imageCache.html), and [PaintingBinding.imageCache](https://api.flutter.dev/flutter/painting/PaintingBinding/imageCache.html).
