### ISSUE TITLE
Xcode 15 launch failure with iOS 17 physical device in debug mode "Could not call ptrace(PT_TRACE_ME): Operation not permitted. Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode."

### ISSUE THREAD

**Issue by NM4ik** [flutter/flutter#136197]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- flutter channel master
- flutter upgrade
- ios -> pod install --repo-update
- flutter clean
- flutter pub get
- flutter run (--debug)

### Actual results

**After updating iOS 17 and xCode 15, I can’t launch debug mode on a physical Apple device.**

- flutter channel master (Flutter 3.16.0-6.0.pre.45 • channel master)
- flutter upgrade
- ios -> pod install --repo-update
- flutter clean
- flutter pub get
- flutter run (--debug)

and im running debug from vs code command-line and xcode

![image](https://github.com/flutter/flutter/assets/78036389/767ca5a5-7f7a-476d-8355-0b3a191c7865)
![image](https://github.com/flutter/flutter/assets/78036389/4ddda282-269c-45b7-8666-1da9aa1e39a6)
![image](https://github.com/flutter/flutter/assets/78036389/f96faadf-6696-4a8c-b287-4cf0b4ac7615)
![image](https://github.com/flutter/flutter/assets/78036389/ee4f74a2-260d-476f-9038-98d851021042)

and sometime i got this notification
![image](https://github.com/flutter/flutter/assets/78036389/28680ab9-2bbb-4413-b749-b76af6249a99)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

nikitamihajlov@Mac-mini-Nikita ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.16.0-6.0.pre.45, on macOS 14.0 23A344 darwin-arm64)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by Ivan981508** [comment]
I have the same problem. Please help me!!!

**Comment by Sgooll** [comment]
same issue :(

**Comment by berkaykurkcu** [comment]
I have the same issue. When I try to run with VS Code 's "Start Debugging" option, Debug Console outputs
```
[VERBOSE-2:ptrace_check.cc(75)] Could not call ptrace(PT_TRACE_ME): Operation not permitted
Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode.
```

Only way I could launch the app on my Physical Device is by running "flutter run --profile" but that doesn't seem to completely work as well. It's getting stuck at "Installing and launching..." section, but the app is running on my device.

**Comment by likwifi** [comment]
Same issue.

Upgraded to Flutter 3.15.0-15.2.pre issue still persists.
Log

>Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
DVTErrorCreationDateKey = "2023-10-09 14:14:27 +0000";
IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
NSURL = "file:///Users/likwifi/Library/Developer/Xcode/DerivedData/Runner-aimksvjhaenqhlcpaqcnleveyoif/Build/Products/Debug-iphoneos/Runner.app";
}
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
"device_isCoreDevice" = 1;
"device_model" = "iPhone14,3";
"device_osBuild" = "17.0.2 (21A351)";
"device_platform" = "com.apple.platform.iphoneos";
"dvt_coredevice_version" = "348.1";
"dvt_mobiledevice_version" = "1643.2.4";
"launchSession_schemeCommand" = Run;
"launchSession_state" = 1;
"launchSession_targetArch" = arm64;
"operation_duration_ms" = 113;
"operation_errorCode" = 260;
"operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
"operation_errorWorker" = IDEInstallCoreDeviceWorker;
"operation_name" = IDERunOperationWorkerGroup;
"param_debugger_attachToExtensions" = 0;
"param_debugger_attachToXPC" = 1;
"param_debugger_type" = 1;
"param_destination_isProxy" = 0;
"param_destination_platform" = "com.apple.platform.iphoneos";
"param_diag_MainThreadChecker_stopOnIssue" = 0;
"param_diag_MallocStackLogging_enableDuringAttach" = 0;
"param_diag_MallocStackLogging_enableForXPC" = 1;
"param_diag_allowLocationSimulation" = 1;
"param_diag_checker_tpc_enable" = 1;
"param_diag_gpu_frameCapture_enable" = 0;
"param_diag_gpu_shaderValidation_enable" = 0;
"param_diag_gpu_validation_enable" = 0;
"param_diag_memoryGraphOnResourceException" = 0;
"param_diag_queueDebugging_enable" = 1;
"param_diag_runtimeProfile_generate" = 0;
"param_diag_sanitizer_asan_enable" = 0;
"param_diag_sanitizer_tsan_enable" = 0;
"param_diag_sanitizer_tsan_stopOnIssue" = 0;
"param_diag_sanitizer_ubsan_stopOnIssue" = 0;
"param_diag_showNonLocalizedStrings" = 0;
"param_diag_viewDebugging_enabled" = 1;
"param_diag_viewDebugging_insertDylibOnLaunch" = 1;
"param_install_style" = 0;
"param_launcher_UID" = 2;
"param_launcher_allowDeviceSensorReplayData" = 0;
"param_launcher_kind" = 0;
"param_launcher_style" = 0;
"param_launcher_substyle" = 8192;
"param_runnable_appExtensionHostRunMode" = 0;
"param_runnable_productType" = "com.apple.product-type.application";
"param_structuredConsoleMode" = 1;
"param_testing_launchedForTesting" = 0;
"param_testing_suppressSimulatorApp" = 0;
"param_testing_usingCLI" = 0;
"sdk_canonicalName" = "iphoneos17.0";
"sdk_osVersion" = "17.0";
"sdk_variant" = iphoneos;
}
System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-10-09T18:14:27+04:00

**Comment by vashworth** [comment]
Seems like the check we use to determine if the app was launched from Xcode appears to be failing occasionally.

https://github.com/flutter/engine/blob/22ce5c6a45e2898b4ce348c514b5fa42ca25bc88/runtime/ptrace_check.cc#L56-L71

I believe this is causing it to try enabling manual tracing, which would cause the "Could not call ptrace" and "Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode" error.

**Comment by vashworth** [comment]
@NM4ik When you get the "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data." Xcode error, could you click the "Show Details" button and include the logs from it?

**Comment by acoutts** [comment]
I find clearing data in xcode (cmd + k) and then exiting xcode, then re-running from vscode usually works. But it's quite annoying having to do this several times a day now.

**Comment by NM4ik** [comment]
@vashworth 

Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-10-09 16:08:41 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///Users/nikitamihajlov/Library/Developer/Xcode/DerivedData/Runner-bexkhqcfxyilzveetcvtdrehaiyy/Build/Products/Debug-iphoneos/Runner.app";
}
--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone11,8";
    "device_osBuild" = "17.0.3 (21A360)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 3;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 1;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-10-09T19:08:41+03:00



**My Note: The app runs on iPadOS 16, I think if I upgrade to 17 I'll get the same error**

**Comment by NM4ik** [comment]
> I find clearing data in xcode (cmd + k) and then exiting xcode, then re-running from vscode usually works. But it's quite annoying having to do this several times a day now.

not working for me :d

**Comment by acoutts** [comment]
Sorry it's cmd + shift + k to clean the build folder (derived data).

**Comment by vashworth** [comment]
@NM4ik When can you use `flutter run -v` and also include the verbose Flutter logs when you get the "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data." error?

**Comment by vashworth** [comment]
@NM4ik You can do `flutter run -v > flutter_log.txt`, which will put the output into a txt file. You can then upload the txt file to this Github issue.

**Comment by likwifi** [comment]
@vashworth since my issue was identical to one mentioned by @NM4ik I've uploaded log file.
After the command failed also terminal printed following message

[+59996 ms] The Dart VM Service was not discovered after 60 seconds. This is taking much longer than expected...
[   +7 ms] Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.

Hope this will help.
[log.txt](https://github.com/flutter/flutter/files/12854406/log.txt)

**Comment by NM4ik** [comment]
@vashworth 
Hello! Sorry for the late response, I am attaching a log with the error "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data."
[flutter_log_2.txt](https://github.com/flutter/flutter/files/12855094/flutter_log_2.txt)

They sent me another log, but as I understand it, there is a slightly different exception, which also happens to me

**Comment by vashworth** [comment]
@NM4ik @likwifi Thank you for the logs, that helps. So for the "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data." error, looks like your versions of Flutter are missing the fix (https://github.com/flutter/flutter/pull/135444). You can try latest master, wait for the next stable release, or cherrypick it.
FYI I was able to determine that because the fix added a verbose logs that starts with `CONFIGURATION_BUILD_DIR: ` and neither of your logs contained it.

For the "Could not call ptrace" and "Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode" error, that's something else and still needs to be investigated.

**Comment by fabiototh** [comment]
I have the same issue. 
Xcode 15.
Flutter stable
Macos: Sonoma.
![adfa22](https://github.com/flutter/flutter/assets/93399977/5cb7f0cf-53ec-49e5-97b9-a8899c943f36)

**Comment by josiahtmorgan** [comment]
My issue may be slightly different than where this thread began, but it is identical to the issue @fabiototh is experiencing.

<img width="499" alt="xcode15error" src="https://github.com/flutter/flutter/assets/6875019/a2bb3816-6274-4505-a8c4-c682834fb022">

Flutter (Channel beta, 3.16.0-0.1.pre, on macOS 14.0 23A344 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)

If I pre-build the app, then I can run it on the physical device if I run it directly from Xcode. I cannot run it from VS Code nor directly from a terminal.

**Comment by fabiototh** [comment]
@josiahtmorgan what's your physical device version? 
Adjusts -> General -> About. Here is 17.0.3. I think this can be the problem.
I run in the version 17.0.1 (the last version xcode simulator), works perfectly.

**Comment by josiahtmorgan** [comment]
@fabiototh Good thought but I've had this issue since 17.0.0 and every increment since then. I've just had to stick with a simulator instead of a physical device.

**Comment by fabiototh** [comment]
@vashworth Do you have any idea what's going on?

**Comment by vashworth** [comment]
@fabiototh @josiahtmorgan The issue you're getting is different than this issue. Please file a new issue so we can effectively triage it.

**Comment by vashworth** [comment]
@NM4ik How often do you get the `Could not call ptrace(PT_TRACE_ME): Operation not permitted. Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode.` error? Does it happen regularly? 

Do you still get the error if you run it from Xcode directly?

**Comment by NM4ik** [comment]
@vashworth 
Hi! my main project does not run on a physical device at all. Is there a chance that this is due to some dependencies in pubspec.yaml? I don't know what to think about anymore..🫡.

**Comment by vashworth** [comment]
> @vashworth Hi! my main project does not run on a physical device at all. Is there a chance that this is due to some dependencies in pubspec.yaml? I don't know what to think about anymore..🫡.

So you're always get the `Could not call ptrace(PT_TRACE_ME): Operation not permitted.` error? Does it work if you open your project (your_project/ios/your_project.xcworkspace) in Xcode and do Product > Run?

**Comment by NM4ik** [comment]
@vashworth 
Yeap
I can't launch it from nowhere, very strange. My colleagues also can't from the other two devices.

**Comment by vashworth** [comment]
@NM4ik So I'm unable to recreate the `Could not call ptrace(PT_TRACE_ME): Operation not permitted.` issue, so it's difficult for me to debug. Would you be willing to try something?

Could you try changing the following lines in your local flutter repo:
https://github.com/flutter/flutter/blob/9c791f465e184e32a007893e474f21402accaac3/packages/flutter_tools/lib/src/device.dart#L1179-L1182

Change to:
```dart
      if (debuggingEnabled) ...<String>[
        '--enable-checked-mode',
        '--verify-entry-points',
      ],
```

And then delete the `flutter/bin/cache/flutter_tools.snapshot` file.

Then try `flutter run` again

**Comment by ardasovvadim** [comment]
@NM4ik I've got the same problem. I spent a couple of hours trying to find a solution. I tried to build/run via XCode and then attach via "flutter attach" but it didn't help I even thought to roll back to XCode 14 or macOS Ventura. But I've fixed this problem by removing the app from the phone, restarting mac and phone, and then trying to run and debug the app again.

**Comment by NM4ik** [comment]
@vashworth 
[✓] Flutter (Channel master, 3.16.0-11.0.pre.71, on macOS 14.0 23A344 darwin-arm64)


terminal stacktrace: [flutter_log.txt](https://github.com/flutter/flutter/files/12914990/flutter_log.txt)
![image](https://github.com/flutter/flutter/assets/78036389/d4cf3cb4-a2b7-4397-ae8e-ecbf0da85df6)

**Comment by vashworth** [comment]
Okay so the log provided in https://github.com/flutter/flutter/issues/136197#issuecomment-1764154254, shows that it crashed

```
=== Crash occurred when compiling unknown function in unoptimized JIT mode in unknown pass
```

Which I believe happens when you try to run a debug-mode version of the app, bypass the [`EnableTracingIfNecessaryOnce` check](https://github.com/flutter/engine/blob/22ce5c6a45e2898b4ce348c514b5fa42ca25bc88/runtime/ptrace_check.cc#L56-L71) (have it return true), and there's not a debugserver running.

However, if you're running it from Xcode or the Flutter CLI, there should be a debugserver running.

**Comment by vashworth** [comment]
@NM4ik Can you open your project in Xcode (e.g. `your_project/ios/your_project.xcworkspace`) and do "Product > Run". This should trigger Xcode to build and launch your application, then in the Report Navigator, right-click on the Build step and click "Show in Finder". 

![Screenshot 2023-10-16 at 3 56 09 PM](https://github.com/flutter/flutter/assets/15619084/cf9ebc9d-b2e6-49d3-9644-083632e9d692)

This should open Finder to a `xcresult` file. Then can you right-click on the `xcresult` file and compress it and upload the zip file to this issue?
![Screenshot 2023-10-16 at 4 05 44 PM](https://github.com/flutter/flutter/assets/15619084/686a01b2-777b-4376-9068-d84c5eb26cf0)

**Comment by NM4ik** [comment]
@vashworth 
[Run-Runner-2023.10.17_11-32-01-+0300.xcresult.zip](https://github.com/flutter/flutter/files/12926360/Run-Runner-2023.10.17_11-32-01-%2B0300.xcresult.zip)

**Comment by vashworth** [comment]
@NM4ik Okay now it's making sense. So looks like your project is not launching a debugger, which would cause this issue. In Xcode, try going to "Product > Scheme > Edit Scheme" and under Run and Info make sure "Executable" is set to the default Runner.app and "Debug executable" is checked.

Here's an example of what the correct settings should look like:

![Screenshot 2023-10-17 at 9 39 02 AM](https://github.com/flutter/flutter/assets/15619084/a82e4f5c-1fa9-4a96-982a-c86668f561eb)

Then try running again and see if it works. In Report Navigator, for the Launch step, there should be a "Debug Runner" section if the debugger was launched.

**Comment by NM4ik** [comment]
![image](https://github.com/flutter/flutter/assets/78036389/6e208d37-d92d-4f90-a840-4875e17b33d8)
There were such settings before updating xCode

It works! Thank you :D

I did: 
unable Debug executable checkbox
flutter channel stable (because master didnt work)
flutter clean
flutter pub get
pod install --repo-update
flutter run

**Comment by vashworth** [comment]
@NM4ik Excellent! Thank you for your assistance in figuring this out!

**Comment by vashworth** [comment]
I'm going to keep this issue open. I think actionable work for Flutter can be: we can try parsing the scheme settings and checking to ensure these settings are set as expected and if they're not, we can provide messaging to guide users to fix.

**Comment by NM4ik** [comment]
@vashworth 
Got u ! :D
Is there anything else required from me?

**Comment by vashworth** [comment]
> @vashworth Got u ! :D Is there anything else required from me?

Nope, I think I have all the information I need. Thanks!

**Comment by likwifi** [comment]
@vashworth after couple times of successful launches with the Debug executable checked,
I'm experiencing same issue again on stable branch.
I've also attached xcresult.
Not sure whats reason for this.
[Run-Runner-2023.10.18_19-55-54-+0400.xcresult.zip](https://github.com/flutter/flutter/files/13030879/Run-Runner-2023.10.18_19-55-54-%2B0400.xcresult.zip)

**Comment by likwifi** [comment]
after upgrade to flutter version 3.13.7 it works again 🤷‍♂️

**Comment by berkaykurkcu** [comment]
Seems like the issue still persists and workarounds are not reliable. 
Applying @vashworth  's suggestion and running directly from XCode https://github.com/flutter/flutter/issues/136197#issuecomment-1766566185 
yields "Build Failed" with two issues.
```
- Framework 'Pods_Runner' not found
- Linker command failed with exit code 1
```

```
Trying to launch from VS Code however yields a very different result.

The item at Runner.app is not a valid bundle.
Domain: com.apple.dt.CoreDeviceError
Code: 3000
Failure Reason: The path to the provided bundle's main executable could not be determined.
```
However, after launching from VS Code and receiving the error above, navigating to XCode and taking a look inside the Runner's Frameworks folder, I see 'Pods_Runner' written in red. 
Simply deleting it and running from XCode again somehow succesfully launched the app.
