### ISSUE TITLE
Differences between GitHub and LUCI queue/run times

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#136203]
GitHub says that a particular presubmit check was started >50 minutes ago

<img width="910" alt="Screenshot 2023-10-09 at 07 58 45" src="https://github.com/flutter/flutter/assets/6343103/b2c989ea-15c5-4c8f-9491-e4519552c5f6">

But LUCI shows that the job was only started ~10 minutes ago

<img width="1046" alt="Screenshot 2023-10-09 at 07 59 46" src="https://github.com/flutter/flutter/assets/6343103/f0d1762b-9e34-4237-a17e-c8eb6b1e3a8b">

The developer experience and the time it actually takes to validate is likely driven by the first number, so I'm wondering if this difference could cause a problem when e.g. gather stats for SLOs, etc.

cc @keyonghan

**Comment by keyonghan** [comment]
First good catch!

The "culprit" is the presubmit auto rerun. The captured build is the second attempt of an earlier failed build:
2nd: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_long_running_tests_1_5/47172/overview
1st: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_long_running_tests_1_5/47170/overview

The first number mentioned in the bug (`52m 25s`) was based on the first attempt, which is intended since both attempts share the same check run id ([17529975183](https://github.com/flutter/flutter/pull/136201/checks?check_run_id=17529975183)). Though intended behavior, the number (based on `check run`'s starting time) would be confusing for devs who focus on the latest build of the check run.

To clear the confusion, one thing we can do is append a note message in the Summary for the auto-rerun'ed case, mentioning that the time above is per check run id, which is based on the first attempt.

BTW: from SLO side, we track the metrics on build level and they should not be affected by this combined number.
