### ISSUE TITLE
%5Btool_crash%5D ProcessException%3A Process exited abnormally%3A%0Axcrun%3A error%3A unable to find utility %22xcodebuild%22%2C not a developer tool or in PATH Command%3A xcrun%2C OS error code%3A 72

### ISSUE THREAD

**Issue by AjaxCao** [flutter/flutter#136326]
%23%23 Command%0A%60%60%60%0Aflutter build macos%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AProcessException%3A Process exited abnormally%3A%0Axcrun%3A error%3A unable to find utility %22xcodebuild%22%2C not a developer tool or in PATH Command%3A xcrun%2C OS error code%3A 72%0A%60%60%60%0A%230      RunResult.throwException %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A125%3A5%29%0A%231      _DefaultProcessUtils.run %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A278%3A19%29%0A%3Casynchronous suspension%3E%0A%232      XcodeProjectInterpreter.getInfo %28package%3Aflutter_tools%2Fsrc%2Fios%2Fxcodeproj.dart%3A324%3A30%29%0A%3Casynchronous suspension%3E%0A%233      buildMacOS %28package%3Aflutter_tools%2Fsrc%2Fmacos%2Fbuild_macos.dart%3A96%3A41%29%0A%3Casynchronous suspension%3E%0A%234      BuildMacosCommand.runCommand %28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fbuild_macos.dart%3A62%3A5%29%0A%3Casynchronous suspension%3E%0A%235      FlutterCommand.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1297%3A27%29%0A%3Casynchronous suspension%3E%0A%236      AppContext.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous suspension%3E%0A%237      CommandRunner.runCommand %28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous suspension%3E%0A%238      FlutterCommandRunner.runCommand.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%

**Comment by huycozy** [comment]
Hi @AjaxCao 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

I decode the issue title string to:

```console
[tool_crash] ProcessException: Process exited abnormally:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: xcrun, OS error code: 72
```

Looks like you have not completed XCode installation. Please check [this](https://stackoverflow.com/a/41536029/5921933) if it helps. 

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing for now.

**Comment by Kastrcn** [comment]
test

**Comment by Kastrcn** [comment]
test
