### ISSUE TITLE
Horizontal border with BorderSide.strokeAlignOutside vanishing on overscroll

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#136387]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Under specific circumstances, a left/right border with `BorderSide.strokeAlignOutside` vanishes. Check the code example for recreating the behavior.

### Expected results

Border visibility is consistent.

### Actual results

Border visibility depends on app state.

### Code sample

This code produces the behavior both on iOS and Android during overscrolling (both directions on Android, just when scrolling down in iOS - videos attached):

https://dartpad.dev/?id=b9b24118d1d5cea4bde8887194f87942

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

iOS:
https://github.com/flutter/flutter/assets/39827040/3318b739-fc36-4e87-9d5b-d0efa88dc42f

Android:
https://github.com/flutter/flutter/assets/39827040/58afb4e7-6fae-4894-9503-91ecd1d50df5

</details>

### Flutter Doctor output

<details><summary>Doctor output - this branch only varies from official stable in `RichText` related files</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.7-0.0.pre.1, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
    ! Flutter version 3.13.7-0.0.pre.1 on channel [user-branch] at /Users/davidschneider/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository https://github.com/Lootwig/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/Lootwig/flutter.git to dismiss this error.
    • Framework revision 57f4df897f (9 days ago), 2023-10-02 19:25:09 +0200
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/davidschneider/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/davidschneider/.Trash/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/davidschneider/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] VS Code (version 1.79.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @Lootwig 
This is WAI as `ScrollView` has clipping by default: `clipBehavior = Clip.hardEdge`. Changing it to `Clip.none` will make it work. Another solution is applying Padding for ListView child instead of outside (this is not really nice, though).


<details>
<summary>Demo with Clip.none</summary>

https://github.com/flutter/flutter/assets/104349824/a4aab378-72b8-412a-ae80-d2676fb901c0
</details>

Closing the issue. If you disagree, please write in the comments and I will reopen it.

**Comment by Lootwig** [comment]
I see, but isn't this still a bug then - just in reverse of what I described?

The clip isn't being applied other than _during_ scrolling, when it should be clipped at all times if I understand correctly

**Comment by TahaTesser** [comment]
@Lootwig 
`ListView` has a `Clip.hardEdge` clip behavior as mentioned by @huycozy. 

What's happening is when you scroll and item is partially out of the view clip behavior is applied to the ListView bounds. sSnce the provide border is right on edge and the provided `Padding` is outside the list view. The clipping behavior is trying clip anything that's outside the list view bounds including the outside order, resulting in this weird behavior. 


To showcase this issue more clearly i added a SizedBox of 100 pixels to the Text widget.


https://github.com/flutter/flutter/assets/48603081/e25a41b6-9d03-47be-a7a0-767f0ef750cc


In order the clipping behavior to safely clip the list view bounds without trying to clip outside border you should provide the padding to the `ListView` itself, instead of wrapping `ListView` with a `Padding` widget.



https://github.com/flutter/flutter/assets/48603081/a424aa26-d297-433e-8b55-23be00caedf8

Hope this makes it clear. Feel free to comment below if this doesn't  work for you.
