### ISSUE TITLE
Add images and examples to Align

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13637]
## Steps to Reproduce

https://docs.flutter.io/flutter/widgets/Align-class.html just one of many:
Its would be helpful in general if those widget description have some small reusable snippets in them and a Picture how it would look like. If I don't find here, I search through the examples to get a overview but that is time consuming and cumbersome.

## Logs

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision 8f65fec5f5 (4 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by InMatrix** [comment]
Thank you for your request. We understand the importance of examples and images in API docs, as we learned from earlier UX studies (see #9331). We even added these requirements in [Flutter repo's style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#provide-sample-code). There are simply too many classes to document fully. We have some ideas (#10416) about encouraging the community to add examples and images to Flutter's API docs, but we haven't exercised those ideas yet. 

At the moment, the best way anyone who cares about this issue is to 1) file issues against specific classes that you believe are in need of examples and images, or 2) go ahead and add examples and/or images to the under-documented classes. If you can help us and other developers with 2), please take a look at [the style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#provide-sample-code) for requirements. 

Cc: @filiph @Hixie

**Comment by goderbauer** [comment]
I probably makes more sense to file issues for specific elements that are lacking examples and images in the docs. Let's make this one about the Align example that you pointed out and I'm inviting everybody to file more specific issues about where the docs are lacking.

**Comment by Piinks** [comment]
Looks like there is already a sample snippet for this class [here](https://docs.flutter.io/flutter/widgets/Align-class.html), unless more examples would be helpful.

If that be the case then we are just missing some visual representation of this widget.

**Comment by goderbauer** [comment]
The snippet that's there is kinda complex. Would probably be good to show some simple examples of just aligning something in the center or top-right or some such and then maybe add illustrating images to show what that would look like.

**Comment by Piinks** [comment]
- [ ] Update sample code : #29442 
- [ ] Generate diagrams in [flutter/assets-for-api-docs](https://github.com/flutter/assets-for-api-docs)
- [ ] Embed diagrams in API documentation
