### ISSUE TITLE
`Mac impeller-cmake-example` starts failing since 10/03

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#136393]
After bisecting, the culprit seems https://github.com/flutter/engine/commit/d29369f87df48c7997df0e98a00d25ec8b1a5fa0.

<img width="320" alt="Screenshot 2023-10-11 at 11 53 47 AM" src="https://github.com/flutter/flutter/assets/54558023/4c7b9262-a36d-4809-ada2-6921d0e3009a">

/cc @matanlurey @zanderso

**Comment by bdero** [comment]
This one should already fixed by https://github.com/flutter/engine/pull/46747.

We had a number breakages of impeller-cmake-example over the past week that I'm working on fixing (I think starting with https://github.com/flutter/engine/pull/46764). The target should start succeeding again once all the patches below are landed:

* https://github.com/flutter/engine/pull/46747
* https://github.com/flutter/engine/pull/46758
* https://github.com/bdero/impeller-cmake/pull/18
* https://github.com/bdero/impeller-cmake/pull/19
* https://github.com/flutter/engine/pull/46764

**Comment by bdero** [comment]
The impeller-cmake-example CI build is successful again.
