### ISSUE TITLE
When setting up InputDecoration contentPadding, you must set isDense or it won't work

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#136436]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
super(
          decoration: decoration != null
              ? decoration.copyWith(contentPadding: _contentPadding(size), )
              : InputDecoration(contentPadding: _contentPadding(size),),
        );

  static EdgeInsetsGeometry? _contentPadding(CustomTextFormFieldSize size) {
    switch (size) {
      case CustomTextFormFieldSize.small:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 6);
      case CustomTextFormFieldSize.middle:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 12);
      case CustomTextFormFieldSize.large:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 20);
    }
  }
```

When set to CustomTextFormFieldSize. Small, contentPadding cannot change, you must specify isDense will only take effect, when CustomTextFormFieldSize. Large when it is normal

### Expected results

When set to CustomTextFormFieldSize. Small, contentPadding cannot change, you must specify isDense will only take effect, when CustomTextFormFieldSize. Large when it is normal

### Actual results

When set to CustomTextFormFieldSize. Small, contentPadding cannot change, you must specify isDense will only take effect, when CustomTextFormFieldSize. Large when it is normal

### Code sample

```
super(
          decoration: decoration != null
              ? decoration.copyWith(contentPadding: _contentPadding(size), )
              : InputDecoration(contentPadding: _contentPadding(size),),
        );

  static EdgeInsetsGeometry? _contentPadding(CustomTextFormFieldSize size) {
    switch (size) {
      case CustomTextFormFieldSize.small:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 6);
      case CustomTextFormFieldSize.middle:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 12);
      case CustomTextFormFieldSize.large:
        return const EdgeInsets.symmetric(horizontal: 12, vertical: 20);
    }
  }
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @laterdayi 
Looks like you are asking for assistance on your project. The goal of this Github repo is to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide appropriate information in the issue template so that we may verify this properly (You are duplicating information there).

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

**Comment by laterdayi** [comment]
@huycozy  Thank you for your reply, I think this is a mistake, no matter how much padding is, it should be effective, instead of relying on isDense

**Comment by huycozy** [comment]
Please provide information indicated in my comment above so that we have enough information to verify this. More specifically:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
