### ISSUE TITLE
Machine mac-41 is Quarantined state due to error.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#136550]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Machine mac-41 is Quarantined state due to error.
<img width="1592" alt="Screenshot 2023-10-13 at 11 07 04 AM" src="https://github.com/flutter/flutter/assets/120754754/1ea82c1d-0e00-459b-99cc-40e9e447fd90">

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by PuzzleTakX** [comment]
It looks like you're dealing with an issue related to a machine named "mac-41" in your infrastructure environment, which is in a Quarantined state due to an error in the device doctor tool. Specifically, the error message mentions "Unhandled exception: device_id not found."

To find information or report this issue, you should check your internal documentation, issue tracking system, or communicate with your infrastructure or devops team. If you've already searched for existing issues, and there isn't one addressing this specific problem, you may want to create a new issue for it and provide all the relevant details, including the error message, steps to reproduce, and any relevant system information. This will help your team investigate and resolve the issue effectively.

**Comment by vashworth** [comment]
FYI: `flutter-devicelab-mac-45` is having same issue: https://github.com/flutter/flutter/issues/136549

**Comment by kentnguyen99** [comment]
@keyonghan  Hi Keyong,  Can you take a look machine mac-41? It's in Quarantined state with error "Quarantined: Device doctor tool error: b'Unhandled exception:\nidevice_id not found". Everything is running fine from machine side. 
Thanks so much.

**Comment by godofredoc** [comment]
I'll get this one this is probably caused by the reinstallation of homebrew.

**Comment by kentnguyen99** [comment]
@godofredoc Same error is starting on machine mac-4 as well.
<img width="1594" alt="Screenshot 2023-10-16 at 3 22 23 PM" src="https://github.com/flutter/flutter/assets/120754754/f45046ab-52cd-42f7-a491-d90d7c15880a">

**Comment by vashworth** [comment]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-5 is having same issue

**Comment by kentnguyen99** [comment]
Machine mac-5 is getting same error.
<img width="1592" alt="Screenshot 2023-10-17 at 9 45 58 AM" src="https://github.com/flutter/flutter/assets/120754754/4359f24a-1bf1-44e9-bf50-9aeef06fa7fb">

**Comment by kentnguyen99** [comment]
Adding mac-2 to the listing.
<img width="1586" alt="Screenshot 2023-10-17 at 1 25 13 PM" src="https://github.com/flutter/flutter/assets/120754754/6d310ab4-d93c-4c1a-bf3e-519b2f75e8eb">

**Comment by kentnguyen99** [comment]
Adding mac-6 to the listing.
<img width="1465" alt="Screenshot 2023-10-17 at 3 20 16 PM" src="https://github.com/flutter/flutter/assets/120754754/67f1a170-7fc2-4ec6-a626-c31924c3b81d">

**Comment by kentnguyen99** [comment]
Adding mac-39 to the listing.
<img width="1560" alt="Screenshot 2023-10-18 at 4 13 03 PM" src="https://github.com/flutter/flutter/assets/120754754/87458c53-f794-4256-b8a7-73d491cbe58a">

**Comment by godofredoc** [comment]
Fixed adding the arm64 brew path to the swarming service path configuration file.
