### ISSUE TITLE
[integration_test] Simulating a long press not working anymore after displaying a bottom sheet

### ISSUE THREAD

**Issue by jeromecaudoux** [flutter/flutter#136542]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I reproduce the bug on Android with the following steps (I have not tried on iOS): 
1. Create an app that uses a GestureDectector to open a bottom sheet when onLongPress is used.
2. In the integration test, do a longpress on the GestureDectector: the bottom sheet gets displayed
3. Close the bottom sheet
4. Do another longpress on the GestureDectector to open the bottom sheet again
5. It fails

### Expected results

The long press should work again even after displaying a bottom sheet.

### Actual results

There is no log while doing the second long press, the pointer can be seen on the screen at the right location and for right duration.
The second long press is not doing anything which makes the test fail in the following instructions.

### Code sample

<details><summary>Code sample</summary>

lib/main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: GestureDetector(
          onLongPress: _showBottomSheet,
          child: Container(
            color: Colors.red,
            child: const Text('Show BottomSheet'),
          ),
        )
      ),
    );
  }

  void _showBottomSheet() {
    showModalBottomSheet(
      context: context,
      builder: (context) => SizedBox(
        height: 200,
        child: Column(
          children: [
            const Text('Modal BottomSheet'),
            ElevatedButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Close'),
            )
          ],
        ),
      ),
    );
  }
}

```

integration_test/integration_test.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sample_issue/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Longpress and bottomsheet', (tester) async {
    // Launch the app
    await tester.pumpWidget(const MyApp());
    await tester.pumpAndSettle();

    // Display the bottom sheet by long pressing the button
    await tester.longPress(find.byType(GestureDetector));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 2)); // I wait 2 seconds to be sure that the bottom sheet is open, pumpAndSettle is not waiting enough
    expect(find.text('Modal BottomSheet'), findsOneWidget);

    // Close the bottom sheet
    await tester.tap(find.byType(ElevatedButton));
    await tester.pumpAndSettle();

    // Re-Display the bottom sheet by long pressing the button again
    await tester.longPress(find.byType(GestureDetector));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 2)); // I wait 2 seconds to be sure that the bottom sheet is open, pumpAndSettle is not waiting enough
    expect(find.text('Modal BottomSheet'), findsOneWidget);
  });
}

```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Screen_recording_20231013_180842.webm](https://github.com/flutter/flutter/assets/5968007/e54a1ebd-7608-414d-b362-c6e122ff707a)

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter --no-color test --machine --start-paused --name "Longpress and bottomsheet(\s*\(variant: .*\))?$" -d emulator-5554 integration_test/integration_test.dart
Testing started at 18:04 ...
Running Gradle task 'assembleDebug'...                             10.8s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...          630ms

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "Modal BottomSheet" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/jerome/Documents/projets/sample_issue/integration_test/integration_test.dart:28:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/jerome/Documents/projets/sample_issue/integration_test/integration_test.dart line 28
The test description was:
  Longpress and bottomsheet
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.2 LTS 6.2.0-34-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by PuzzleTakX** [comment]
It seems like you're encountering an issue with your Flutter app where the second long press on the GestureDetector doesn't open the bottom sheet as expected. Here are some steps to troubleshoot and potentially fix the issue:

1. **Verify Dependencies:** Ensure that your Flutter and integration_test dependencies are up to date. Run `flutter pub get` to make sure you have the latest packages installed.

2. **Widget Key:** Add a `GlobalKey` to the `GestureDetector` in your test to make sure you are interacting with the correct widget.

   ```dart
   final gestureDetectorKey = GlobalKey();

   // In the test:
   await tester.longPress(find.byKey(gestureDetectorKey));
   ```

3. **Wait for Widgets to Appear:** You can use the `await tester.pumpAndSettle()` to wait for widgets to appear instead of using arbitrary time delays.

4. **Widget Rebuilding:** Ensure that the widget tree is being rebuilt correctly after closing the bottom sheet. You may need to call `tester.pumpAndSettle()` after closing the bottom sheet to make sure the widget tree is updated.

5. **Debugging:** You can add debug print statements to your test to check if the long press is being recognized and if the widget tree is updating correctly.

6. **Check for Multiple Widgets:** Make sure that there is only one `GestureDetector` widget in the widget tree. If there are multiple, the tester might not be interacting with the one you expect.

7. **Flutter Hot Reload:** Sometimes, the Flutter hot reload can resolve widget tree issues. Try running your app and test with `flutter run` and `flutter test` to see if the issue persists.

These steps should help you diagnose and potentially fix the issue with the second long press not opening the bottom sheet.

**Comment by jeromecaudoux** [comment]
@PuzzleTakX I carefully checked every points that you mentioned, but I still have the issue :/
2. I tried and got the same result, also there is only one GestureDetector in my sample.
4. In my sample I use `tester.pumpAndSettle()` I added a pump because pumpAndSettle is for some reason not always waiting the bottom sheet animation.

**Comment by PuzzleTakX** [comment]
I understand that you've carefully checked the points mentioned and are still facing the issue. Debugging these types of problems can be quite challenging. If `tester.pumpAndSettle()` is not consistently waiting for the bottom sheet animation, you might need to experiment with alternative approaches to work around the issue:

1. **Explicit Delays:** Although not ideal, you can use `Future.delayed` to explicitly wait for a certain amount of time after opening or closing the bottom sheet. While not recommended for production tests, it can help identify whether the issue is related to timing.

2. **Custom Wait Logic:** Implement your custom waiting logic. For example, you can periodically check if the desired element (e.g., text) has appeared on the screen after triggering the bottom sheet and use a loop to wait until it's found.

3. **Check Flutter's GitHub Repository:** Given that `pumpAndSettle` is supposed to handle waiting for animations to complete, you might want to check the Flutter GitHub repository for any open issues related to `pumpAndSettle`. There might be specific scenarios or edge cases that haven't been handled correctly.

4. **Engage with the Flutter Community:** Post your issue on the [Flutter community forums](https://flutter.dev/community) or on Stack Overflow. Other Flutter developers may have encountered similar issues and can provide more insights or possible workarounds.

5. **Test on Different Devices/Emulators:** Sometimes, specific devices or emulators can exhibit unusual behavior. Try running your test on a different device or emulator to see if the issue persists.

6. **Create a Minimal Reproduction:** Create a minimal reproduction of the issue in a new Flutter project. This can help you narrow down the problem and make it easier to identify the root cause.

While these workarounds may help you make progress, it's important to remember that they are temporary solutions. Ideally, Flutter tests should work consistently with `pumpAndSettle`, and if it's not functioning as expected, it might be indicative of a framework issue that should be reported to the Flutter community or Flutter's GitHub repository for investigation and resolution.

**Comment by huycozy** [comment]
Thanks for your report @jeromecaudoux 
I see there's an open issue addressing the similar case you described https://github.com/flutter/flutter/issues/98804. Even though it's with Dialog instead, I think these issues have the same cause as they are `PopupRoute` internally.


Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
