### ISSUE TITLE
Flutter inspector code redirect not working in flutter latest version (3.13.5)

### ISSUE THREAD

**Issue by sindhavbharat** [flutter/flutter#136511]
`Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (3 weeks ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0
`

- Flutter inspector code redirect working on old flutter version but not working on latest version 3.13.5

**Comment by huycozy** [comment]
Hi @sindhavbharat 
Which IDE does the issue occur on? If you are on Android Studio, it could be similar to some issues [here](https://github.com/flutter/flutter-intellij/issues?q=is%3Aissue+is%3Aopen+Flutter+inspector) at [Flutter Plugin for IntelliJ](https://github.com/flutter/flutter-intellij) repository. And you should follow them for updates.

Otherwise, please more information on `Steps to reproduce` in detail will help us to verify this.

**Comment by sindhavbharat** [comment]
I checked that video but still not worked on latest Android studio Android Studio Giraffe | 2022.3.1.

**Comment by huycozy** [comment]
I'm not sure which video you are mentioning but if the issue only occurs on Android Studio (not also on VSCode), it could be Flutter Plugin for IntelliJ issue and you should report there for better support. Otherwise, please provide more information as I mentioned above so that we may verify this. Thanks!
