### ISSUE TITLE
Expansion Panel don't expand when pressed

### ISSUE THREAD

**Issue by cory-brown** [flutter/flutter#136914]
### Page URL

https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html

### Describe the problem

When I tapping on each panel, the expected behaviour is for it to expand, but does nothing.

### Expected fix

On line 67, you need to remove the not operator. 

e.g.

**_data[index].isExpanded = isExpanded;**

**Comment by huycozy** [comment]
Hi @cory-brown 
This is a known [issue](https://github.com/flutter/flutter/issues/132759) and has been fixed by https://github.com/flutter/flutter/pull/132837. You can check it on master API docs: https://master-api.flutter.dev/flutter/material/ExpansionPanelList-class.html.

Closing as fixed on master. The fix should be landed to stable API docs soon.
