### ISSUE TITLE
Pass build type (Debug/Release) and arch type (x86, x64 , etc) in cmake generation

### ISSUE THREAD

**Issue by picatostas** [flutter/flutter#137070]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When you run `flutter build windows --debug`, --debug is not passed in the generation step as when building for linux, only in the building step:

`cmake --build "build_dir" --config Debug`

This means that the cmake variables

- CMAKE_BUILD_TYPE
- CMAKE_VS_PLATFORM_NAME

are not set from the beginning and required extra logic to set them properly. 

So when one wants to setup output directories to copy external dependencies that may have 
different options between, lets say x86/x64 and Debug/Release, you have to play with copy post build events and $CONFIG variable instead of just having a:
```
set(MY_LIBRARY "${MY_LIB_DIR}/${CMAKE_VS_PLATFORM_NAME}/${CMAKE_BUILD_TYPE}/my_lib.dll")

install(FILES "${MY_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_LIB_DIR}" COMPONENT Runtime)
```

instead of having:
```
add_custom_command_if(
    TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMANDS
    COMMAND $<CONFIG:Debug> xcopy /y /i $<SHELL_PATH:$<TARGET_FILE:${PROJECT_NAME}>> $<SHELL_PATH:${CMAKE_SOURCE_DIR}/>..\\build\\windows\\runner\\Debug\\
    COMMAND $<CONFIG:Release> xcopy /y /i $<SHELL_PATH:$<TARGET_FILE:${PROJECT_NAME}>> $<SHELL_PATH:${CMAKE_SOURCE_DIR}/>..\\build\\windows\\runner\\Release\\
)
```
If `flutter build` is going to both generate and build the cmake files, why not pass those build and arch arguments in the generation step as well? 

As it has been mentioned, this is because Visual Studio is a multi-configuration generator; the build configuration does not exist at generation time.
From the user perspective, generation and build steps are not split into 2 steps when one runs `flutter build windows --debug`.

### Proposal

If --debug and arch type parameters are past to the cmake generation also in windows so the variables CMAKE_BUILD_TYPE and CMAKE_VS_PLATFORM_NAME are known from the start the cmake files become way simpler.

**Comment by stuartmorgan** [comment]
Carrying my response over from the other issue and expanding slightly:

> When you run `flutter build windows --debug`, --debug is not passed in the generation step as when building for linux, only in the building step

This is the correct behavior; Windows uses a multi-config generator (Visual Studio), whereas Linux uses a single-config generator (ninja).

> This means that the cmake variables
> 
> * CMAKE_BUILD_TYPE
> * CMAKE_VS_PLATFORM_NAME
> 
> are not set from the beginning and required extra logic to set them properly.

`CMAKE_BUILD_TYPE` doesn't apply to multi-config generators, [per documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html); it cannot be set, due to the nature of multi-config generators. It's not correct to say that they are not being set "properly", since they simply don't apply here.

You are correct that this means that you must use `CONFIG` expressions rather than `CMAKE_BUILD_TYPE` (as covered in CMake documentation on generator types).

> As it has been mentioned, this is because Visual Studio is a multi-configuration generator; the build configuration does not exist at generation time.

Yes, that's correct.

> From the user perspective, generation and build steps are not split into 2 steps when one runs `flutter build windows --debug`.

However, if a user runs `flutter build windows` once (eventually with `--config-only` once that's supported), and then they does their building from within the generated Visual Studio project, it *is* split into two steps. And this is, intentionally, a supported configuration.

> If --debug and arch type parameters are past to the cmake generation also in windows so the variables CMAKE_BUILD_TYPE and CMAKE_VS_PLATFORM_NAME are known from the start the cmake files become way simpler.

Flutter has deliberately chosen to support using standard native development tools (e.g., Visual Studio for Windows) for each target platform. Changing the generator for Windows would break those workflows (and also breaking any plugin that expects the current generator behavior).

Closing, as architecture was added in https://github.com/flutter/flutter/pull/131843, and there are no plans to change generators (without which the other part of this request cannot be implemented).
