### ISSUE TITLE
Can't build ios

### ISSUE THREAD

**Issue by pstefani89** [flutter/flutter#137256]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Install macOS Sonomwa 14.0
Install Xcode Version 15.0.1 (15A507)
After this my working project stopped working

```
Running Xcode build...                                          
Xcode build done.                                            1,9s
Failed to build iOS app
Could not build the precompiled application for the device.
Uncategorized (Xcode): Exited with status code 1


```
### Expected results

Application should run on my iphone

### Actual results

```
Running Xcode build...                                          
Xcode build done.                                            1,9s
Failed to build iOS app
Could not build the precompiled application for the device.
Uncategorized (Xcode): Exited with status code 1
```

**Result of fvm fluttr build ios -v**

[pplik.txt](https://github.com/flutter/flutter/files/13167576/pplik.txt)

</details>

### Flutter Doctor output

<details><summary>Doctor summary (to see all details, run flutter doctor -v):

</summary>

```console
[!] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale pl-PL)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.16.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/piotrstefani/fvm/versions/3.13.8. Consider adding /Users/piotrstefani/fvm/versions/3.13.8/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @pstefani89 
I see this error message from your build output log:

>The following build commands failed:
Run custom shell script 'Run Script'
eyJ0eXBlIjp7IndvcmtzcGFjZSI6e319fQ==
(2 failures)

Did you add any shell script to `Run Script` in Build Phases? Do this issue happen on a new Flutter project?

**Comment by pstefani89** [comment]
Hi @huycozy in run script i have only this what you can see on image below. Other of mine project works fine.
![Zrzut ekranu 2023-10-26 o 09 36 39](https://github.com/flutter/flutter/assets/90765795/4c5433f1-bf29-426e-a252-d93984ba2f75)

**Comment by huycozy** [comment]
It looks normal. Does the issue only appear with `build` command? Does it run normally? If not so, please also share the entire output of `flutter run -v`.

**Comment by pstefani89** [comment]
@huycozy same return in any action(build, run or even when i do clean build folder in xcode)

**Comment by huycozy** [comment]
This issue only occurs on your project, but not on a newly created project, right? Could you share the entire output of `flutter run -v`?

**Comment by pstefani89** [comment]
@huycozy output of flutter run -v:

[ios.txt](https://github.com/flutter/flutter/files/13203057/ios.txt)

**Comment by huycozy** [comment]
>[   +4 ms] Error: Browsing on the local area network for iPad (Piotr). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
           The device must be opted into Developer Mode to connect wirelessly. (code -27)

Thanks. I only noticed this error from your run output. Does it work if you unlock device and retry? Please make sure your device is listed on `flutter doctor -v` output.

Also, the above log seems to be from your project and not a simple project, right? Is this issue reproducible on a simple Flutter project? 

If the issue only appears on your project, it could be caused by project configuration or integrated plugin that we need more information for further investigation. You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a single `main.dart` file that can be run independently. If the issue's still reproducible, please provide that `main.dart` file so that we can verify the issue properly. Thanks!

**Comment by pstefani89** [comment]
Yes, phone is listed on this output. 

Yes the project is quite big. Main problem is that there was no changes in project it self, the only thing that has change is version of iOS, macO and xcode(all updated to newest version). Before those updates everything was working perfect.

**Comment by huycozy** [comment]
Unfortunately, this is not easy to verify if it only happens at your project. The issue can be caused by incompatibility between multiple components (plugins/configuration) or it could also be a framework bug. Overall, there should be clear steps to reproduce so we can work it out. So please try to follow the suggestion above.
