### ISSUE TITLE
Error when loading Lottie Asset, and precacheImage on initState

### ISSUE THREAD

**Issue by gabriel-R-Lemes** [flutter/flutter#137361]
So, i'm building my own wedding app, the issue i'm having is this:
The login page has an image as background,  a lottie animation (GIF), and a widget that calls a Rive animation.
The first time the login page loads , it calls an error in the framework:
![image](https://github.com/flutter/flutter/assets/108953357/bca97fcc-dd2e-4076-bc8e-a60742e16355)

but i did not called those two methods mentioned in the error
My loginPage is this:

```dart
class LoginPage extends StatefulWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  bool isTextOn = false;
  late final LottieComposition composition;
  final GlobalStore globalStore = Modular.get<GlobalStore>();
  final AuthStore authStore = Modular.get<AuthStore>();

  Future<void> _loadResources() async {
    final imageSize = MediaQuery.of(context).size;

    // await precacheImage(
    //   const AssetImage('assets/images/bgNew3.jpg'),
    //   context,
    // );

    AssetLottie('assets/lottie_animations/noivoscinza.json')
        .load()
        .then((value) => composition = value);
    // You can preload other resources like animations here
  }

  @override
  void initState() {
    super.initState();
    _loadResources();
  }

  @override
  Widget build(BuildContext context) {
    globalStore.setBuildContext(context);
    return Observer(builder: (context) {
      return Scaffold(
        body: SingleChildScrollView(
          child: Stack(
            alignment: Alignment.topCenter,
            children: [
              FutureBuilder(
                  future: _loadResources(),
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return const Center(
                        child: CircularProgressIndicator(
                          color: Colors.black,
                        ),
                      );
                    } else {
                      return Container()...
```  

I know that if i deactivate the Uncaught Exceptions the application won't stop in debug. THe problem is that when the page is load, there's a noticeable delay in both lottie and rive animations.
How do i solve this?

**Comment by huycozy** [comment]
Hi @gabriel-R-Lemes 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

Instead, if the issue only appears with Lottie, please open a new issue on its [repository](https://github.com/xvrh/lottie-flutter/issues) first. Once its developers verify that the issue comes from Flutter framework, please comeback here with more information that will help us verify this issue.

Thank you!
