### ISSUE TITLE
Android TV: No support for getting the focused widget's coordinate

### ISSUE THREAD

**Issue by coderJohnZhang** [flutter/flutter#13749]
As we know, tv apps use remote control's direction key to move focus from one widget to another. User needs to know which widget has got the current focus, so we may provider a focus animation effect, just draw a light widget floating on the focus widget. This light focus indicator widget will move from the previous focus widget to the current focus widget, we need calculate the move offset by the focused widget's coordinate minus the previous focus widget's coordinate. But I can't find any interface to get the widget's coordinate.

**Comment by InMatrix** [comment]
There might be an easier way to achieve the effect you want in Flutter, but to answer your specific question about getting a widget's coordinates, you can use a widget's [RenderBox](https://docs.flutter.io/flutter/rendering/RenderBox-class.html)'s `localToGlobal` method to get the widget's coordinates.

Assuming `myWidgetKey` is a [GlobalKey](https://docs.flutter.io/flutter/widgets/GlobalKey-class.html) you assigned to your widget when it is added to the build function. You can get a reference of its RenderBox as follows:

`final RenderBox myRenderBox = myWidgetKey.currentContext.findRenderObject();`

Once you have `myRenderBox`, you can get its global coordinates using the `localToGlobal` method:

`final Offset coordinates = myRenderBox.localToGlobal(Offset.zero);`

By the way, this type of question is better suited for Stack Overflow than the issue tracker.

**Comment by athornz** [comment]
What would the easier way be?

**Comment by coderJohnZhang** [comment]
I'm interested in the easier way, too. Most of the time, I needn't have to appoint nextFocusDown, nextFocusUp, nextFocusLeft, nextFocusRight for a widget if I use native android to develop tv apps. I guess flutter have to do this work so far. This increase the development difficulty，not easy for use.

**Comment by Hixie** [comment]
Flutter is currently focused on the phone form factor, so we haven't tried to address this with a high-quality solution yet.

I'm not quite sure I understand the issue though. Can you elaborate more? What's the high-level problem? Is it just showing the focus outline on TVs? Is it defining the focus order for directional focus navigation?

**Comment by athornz** [comment]
I think there are three main issues that I've seen so far:

- Easily receiving input events from a remote or controller
- Showing a focus state for widgets 
- Defining the next focus order

**Comment by coderJohnZhang** [comment]
I have submitted my tv app simple build with flutter to my [github](https://github.com/coderJohnZhang/flutter_tv). And it has many bugs, just mock what I want to realize.

**Comment by Hixie** [comment]
Got it, thanks. Input events can probably be done as a plugin; that isn't on the team's near-term priority list. Showing focus state can be done using some custom widgets, though again it's not something we're likely to work on any time soon. Defining next focus order is something we're likely to work on this year as it impacts device form factors that we're likely to target before TVs.

**Comment by coderJohnZhang** [comment]
I have used true coordinates to refactor my code and improve my demo. See [https://github.com/coderJohnZhang/flutter_tv](https://github.com/coderJohnZhang/flutter_tv), but when I scroll pages several times, ui doesn't respond my operation any more, also no print in console.

**Comment by FullstackJack** [comment]
@hixie The problem the community is trying to describe here is called spacial navigation and it's a fairly well documented topic of computer science. What we need is for the Flutter team to add this to the Roadmap because solving it requires deep integration with the Base Widgets and Input processors of Flutters core. There are many papers and resources written about the issue that can be found by a quick web search. I'm on a phone and not really able to collect them at the moment otherwise I would be more helpful.

Don't get me wrong, I'm not trying to downplay the complexity of the solution though, in reading Mozilla's article about thier several implementions and final solution, it became abundantly clear the need to diagram and define the next focus algorithm upfront before really diving in on the code because ordering the widgets based on a set of rules is one of the most important steps to solving the problem.

I would argue that if the community and/or the team were to focus on this feature for 2019, it would catapult Flutter forward as the dominant cross platform solution since this is one area where React Native currently has a leg up on the competition.

This missing feature is the only reason I cannot recommend Flutter to my employer and instead have to lean on React Native.

**Comment by NBTX** [comment]
@InMatrix could you possibly five us some insight into what the easier way could be?

And is there any update on this - especially from the Flutter team?

**Comment by InMatrix** [comment]
@NBTX My original reply was addressing the question about getting absolute coordinates of a widget a runtime, and you can do that by getting the widget's RenderBox using a GlobalKey. The RenderBox interface gives you access to its coordinates. However, I think that's only a small part of the issue described above. 

Cc: @gspencergoog Is this issue related to your ongoing work about the new keyboard focus API?

**Comment by gspencergoog** [comment]
Yes, my work would help with both focus highlighting and focus navigation.  It's not ready for prime time yet (I'm now trying to shoehorn the new API into the old API as much as possible to minimize the breaking changes of existing code).

The directional traversal algorithm we arrived at is similar to the Mozilla algorithm (which I wasn't aware of before, so thanks for the reference), but it doesn't take into account diagonal directions, because we were only interested keyboard navigation.  The API allows easy customization of the focus traversal policy, however, both for next/previous navigation (e.g. TAB order), and for directional navigation, so it wouldn't be hard to incorporate once we have key input events for TV remotes.

Here's a [WIP PR](https://github.com/flutter/flutter/pull/29622) to peruse, but be aware that a lot of the names/structure will still change there as I integrate it into the old API.

**Comment by NBTX** [comment]
@InMatrix - my apologies I misunderstood your message.

**Comment by changxiangzhong** [comment]
@Hixie Please consider add Android TV support to the road map. I'm pretty much in the same position as @FullstackJack . I have the intention to introduce it to my Employer as well.

**Comment by kf6gpe** [comment]
@gspencergoog Greg, with the work you've finished for desktop, how much left is there to do here?

**Comment by gspencergoog** [comment]
Nothing else is needed here, AFAICT.  Each focus node has a valid context associated with it.  Accessing `FocusManager.instance.primaryFocus.context` will give you the context for the currently focused item.

Also, take a look at the `FocusTraversalPolicy`: that is specifically designed to handle spatial navigation, and I could see someone using that to gather information for floating focus highlights.

You'll probably have the regular challenges having to do with build and layout order, but no more than for any other effect.
