### ISSUE TITLE
The user screen is tiny (Conquest f2).

### ISSUE THREAD

**Issue by mi3van** [flutter/flutter#137481]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The user wrote that he could not sign-in because the phone screen was small and the screen did not scroll - he could not select his account. His device: Conquest f2.
I tried it on a virtual device (emulating the size of a Conquest f2) and was able to select an account.
Please comment if a real device might display differently?
Thank you in advance!

### Expected results

Succesfull sign-in.

### Actual results

No sign-in.

### Code sample

<details>
<summary>Code sample</summary>
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

</details>

**Comment by huycozy** [comment]
Hi @mi3van 
I would like to know if you are reporting this issue for [google_sign_in](https://pub.dev/packages/google_sign_in) or your own sign-in screen on your app.

If the issue is about `google_sign_in` package, please provide all information indicated in [1P issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml). I recommend you close this issue and open a new issue.

In case this's about your own sign-in screen, the issue could be caused by your implementation (adaptive screen layout) and it is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

**Comment by mi3van** [comment]
Thank you, @huycozy!
I wanted to report a sign-in screen issue for [google_sign_in](https://pub.dev/packages/google_sign_in).

Okay, I'll close this issue and open a new one with a more detailed description.

All the best.
