### ISSUE TITLE
[flutter_webview] Make NavigationDelegate mandatory

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#137576]
We received the following security report:

> **Issue:** `flutter_webview` allows navigation (within a WebView) by default, instead of relying on the ActivityManager to handle links. This means that if a user is tricked into clicking a malicious link (e.g. a phishing site), the user has no way to identify the active page and may become a victim of a phishing attack. Android's default behavior for WebView is to delegate to ActivityManager, so by default HTTP(S) links are opened with Chrome. This makes it clear to the user that (a) they've left the current page (and are no longer in the application), and (b) they can use the address bar to determine whether what they're seeing is still a legitimate page or a phishing attack.
>
> **Mitigation**: We suggest making NavigationDelegate mandatory and adding a security warning that not setting a `NavigationDelegate` can lead to phishing attacks. Otherwise, since `flutter_webview` provides more of a browser than just a view, it might also make sense to provide a minimal user interface (cf. Instagram's in-app browser).

**Comment by stuartmorgan** [comment]
> This means that if a user is tricked into clicking a malicious link (e.g. a phishing site), the user has no way to identify the active page and may become a victim of a phishing attack

Whether to display information about the active page, and whether to allow following links, is a decision left to the plugin client; it is true that it's possible to construct applications with this property using the plugin, but that's not an inherent issue in the plugin.

> We suggest making NavigationDelegate mandatory

This is not a direction we plan to go with the plugin.

> and adding a security warning that not setting a `NavigationDelegate` can lead to phishing attacks

Documenting the full scope of what is and is not safe when displaying web content in an application is out of scope of the plugin documentation, as it's a very large and complex topic, and involves not just the webview settings but the entire application context.

> Otherwise, since `flutter_webview` provides more of a browser than just a view, it might also make sense to provide a minimal user interface (cf. Instagram's in-app browser).

`flutter_webview` does not provide a browser, it only provides a web view (precisely because it does not have a user interface). Clients who want a browser-like experience based on `flutter_webview` are welcome to build their own UI around the plugin which meets their specific needs.
