### ISSUE TITLE
[webview_flutter] should use WebViewClient.shouldOverrideUrlLoading

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#137578]
We received the following security report:

> **Issue:** `flutter_webview` implements a NavigationDelegate to limit the web pages a WebView can navigate to. However, the `NavigationDelegate` uses the `WebViewClient.onPageStarted` callback instead of the 
 `WebViewClient.shouldOverrideUrlLoading` for this functionality. According to the Android API, unlike `WebViewClient.shouldOverrideUrlLoading` the `WebViewClient.onPageStarted` callback is only called for top-level navigation. As a result, navigation restrictions can easily be circumvented by using iframes.
>
> **Mitigation**: We suggest using `WebViewClient.shouldOverrideUrlLoading` for the `NavigationDelegate`.

**Comment by stuartmorgan** [comment]
> However, the `NavigationDelegate` uses the `WebViewClient.onPageStarted` callback instead of the
> `WebViewClient.shouldOverrideUrlLoading` for this functionality.

This statement [is not correct](https://github.com/flutter/packages/blob/b236d83c4a0ad839f7c2cc4ca7d643e80cecf431/packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewClientHostApiImpl.java#L77-L82); closing, since that's the premise of the issue.

(Even if that were the case though, I would disagree with this statement:

> As a result, navigation restrictions can easily be circumvented by using iframes.

If a Flutter developer chose to load a page in a webview that contained nothing but a full-page iframe that itself loaded arbitrary untrusted content, they would not receive top-level navigation callbacks, but they would have to go out of their way to do this.)
