### ISSUE TITLE
YouTube plugin

### ISSUE THREAD

**Issue by csbenjamin** [flutter/flutter#13756]
It would be awesome if flutter had support for the YouTube api. Right now I am using a webview to show the player in an iframe. Is it possible to implement a flutter plugin for YouTube api? I never developed for Android and iOS, just web development. Also I am new to flutter.

**Comment by xster** [comment]
FWIW, it seems like YouTube's public gdata no longer exposes the stream url. We'd have to create something like https://developers.google.com/youtube/android/player

**Comment by Xsmael** [comment]
+1

**Comment by Xsmael** [comment]
the Youtube Api V3 provides a nice API controlled by an API key, so that if you have your youtube channel you can request the videos you want...

**Comment by AkshatGiri** [comment]
+1

**Comment by zoechi** [comment]
please use "add reaction" instead of `+1`. `+1` is spammy

**Comment by nitishk72** [comment]
👍

**Comment by nitishk72** [comment]
Yesterday, I this and started wondering that **Can make this Plugin ?**.
After thinking sometimes, I tried and I had built that Now.

Here is Package Link to **Youtube API Plugin** : https://pub.dartlang.org/packages/youtube_api


Here is Github Link to **Youtube API Plugin** : https://github.com/nitishk72/youtube_api

Currently this plugin can search video, you just YOUTUBE API Key for that and you will get response
like this.

```
{
        "kind": "video",
        "id": "9vzd289Eedk",
        "channelTitle": "Java",
        "title": "WEBINAR - Programmatic Trading in Indian Markets using Python with Kite Connect API",
         "description": "For traders today, Python is the most preferred programming language for trading, as it provides great flexibility in terms of building and executing strategies.",
        "publishedAt":"2016-10-18T14:41:14.000Z",
        "channelId": "UC8kXgHG13XdgsigIPRmrIyA",
        "thumbnails": {
             "default": {
              "url": "https://i.ytimg.com/vi/9vzd289Eedk/default.jpg",
              "width": 120,
              "height": 90
             },
             "medium": {
              "url": "https://i.ytimg.com/vi/9vzd289Eedk/mqdefault.jpg",
              "width": 320,
              "height": 180
             },
             "high": {
              "url": "https://i.ytimg.com/vi/9vzd289Eedk/hqdefault.jpg",
              "width": 480,
              "height": 360
             }
        },
        "channelurl":"https://www.youtube.com/channel/UC8kXgHG13XdgsigIPRmrIyA",
        "url":"https://www.youtube.com/watch?v=9vzd289Eedk"
    },
```
Please do contribute and make my code more standard. So that other can read and understand it easily.

A big **Thanks** to issue if it was not here I could not never though that I can make plugin also

**Comment by hoanglm4** [comment]
I noticed that Flutter published preview version. Does this mean that the first release will not include YouTube plugin?

**Comment by charafau** [comment]
@hoanglm4 why do you want youtube plugin in standard flutter package? plugins are independent from main framework and you can write youtube plugin yourself.

**Comment by hoanglm4** [comment]
@charafau Currently, Flutter is difficult when create plugin for existed custom view. Example in Android:

I want add YoutubePlayerView or WebView:
FramLayout parent = (FrameLayout) registrar.view().getParent();
parent.addView(CustomView, layoutParams);

CustomView on top of Flutter's view. This unfortunately won't properly composite with the rest of the Flutter widgets.

**Comment by romatroskin** [comment]
any updates inlining YouTube player?

**Comment by mtcliatt** [comment]
Why was this issue closed?

**Comment by zoechi** [comment]
@mtcliatt is is not. You probably saw the closed label of a referred issue.25351

![image](https://user-images.githubusercontent.com/405837/50953496-e4182580-14b3-11e9-9bf4-946c54723d7a.png)

vs 

![image](https://user-images.githubusercontent.com/405837/50953503-eaa69d00-14b3-11e9-8a65-2dfa0b6acefc.png)

**Comment by alex01000101** [comment]
Made an attempt at an inline youtube plugin. Got the video in (eventually) but it wont play as it is "obscured" by io.flutter.plugin.platform.SingleViewPresentation$FakeWindowViewGroup.

Also has to copy in the flutter activity to the app and have it extend the YoutubeBaseActivity instead of activity.

Proving quite hard to use google with my google

**Comment by ScriptyMind** [comment]
I found this plugin not perfect but the the work.
link : https://github.com/PonnamKarthik/FlutterYoutube

**Comment by hoanglm4** [comment]
@ScriptyMind You can using https://github.com/hoanglm4/flutter_youtube_view. This lib support well for customize youtube player

**Comment by mayurdhurpate** [comment]
I think currently, some major youtube plugins are breaking Youtube Terms of Service, so not sure which one to choose and which might be the best way to proceed. I require an embedded Youtube player to trigger some functions on Video end/pause by the user.

[flutter_youtube](https://pub.dartlang.org/packages/flutter_youtube): This plugin uses [XCDYouTubeKit](https://github.com/0xced/XCDYouTubeKit)  on iOS, which contains the following warning in its readme: XCDYouTubeKit is against the YouTube Terms of Service. 

[youtube_player](https://pub.dartlang.org/packages/youtube_player): A flutter plugin to play Youtube Videos "inline" without API Key. This plugin is a fork of video_player, developed by Flutter Team, so probably uses Youtube stream url which is [not supported too](https://github.com/flutter/flutter/issues/13756#issuecomment-354130994).

[flutube](https://pub.dartlang.org/packages/flutube): This plugin also embeds Youtube videos in your flutter apps just by passing in the video URL. Embedding copyrighted videos is actually not possible. This plugin uses an in-built API so the official YT API is not used here and therefore don't need any API keys. Not so sure about this one.

[youtube_api](https://pub.dartlang.org/packages/youtube_api): A Flutter plugin for fetching interacting with Youtube Server to fetch data using API. Supports iOS and Android. Can currently Search Video, Playlist, Channel on youtube. Plugin page says 'Play Youtube Video' feature is Coming Soon.

Not sure how to proceed further.

**Comment by dblokhin** [comment]
So, what's the best solution to embed youtube video ?

**Comment by gstaykov** [comment]
> So, what's the best solution to embed youtube video ?


Currently I'm using this webview plugin https://github.com/fluttercommunity/flutter_webview_plugin.
Go to the video you want to display, share button, then click embed and copy the url from the src property of inframe tag. After that use this url in WebviewScaffold widget to show the video:

```
Container(
    margin: EdgeInsets.only(top: appBar.preferredSize.height + 8),
    width: 200,
    height: 200,
    child: WebviewScaffold(
        url: "https://www.youtube.com/embed/1CR0QmCaMTs",
    ),
),
```

This is not the best solution for sure but it is the only one I get working so far.

**Comment by AdamSHurwitz** [comment]
The best solution would be to build out a Flutter package that bridges to
the native Android and iOS YouTube Player API
<https://developers.google.com/youtube/> libraries.

**Comment by d-silveira** [comment]
youtube is owned by google, flutter is under google governance, and being pushed by google, so why doesn't google just add support for the video player plugin to play youtube videos or just release an official youtube player plugin!?

**Comment by Ricardokanitz** [comment]
I was able to use youtube plugin and API with the [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter), it worked fine on both Andoid real device and IOS simulator, but after uploading it to the play store when I download the app it doesn't load the videos anymore. What could be causing it?

**Comment by ahmedz502** [comment]
> I was able to use youtube plugin and API with the [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter), it worked fine on both Andoid real device and IOS simulator, but after uploading it to the play store when I download the app it doesn't load the videos anymore. What could be causing it?

Happened the same thing to me

**Comment by whispers16** [comment]
@Ricardokanitz @ahmedz502 did you find any solution?

**Comment by YazeedAlKhalaf** [comment]
@timsneath 

I hope you can take a look at this issue

**Comment by YazeedAlKhalaf** [comment]
## Use case



I think Flutter needs to support YouTube Player API officially, such as a collaboration between the youtube team and the flutter team. It would be great if that is done, plus I think it would be a little bit easier since it is the same company, Google.

## Proposal




It is a package request, but I did not find a better place for requesting better than here. I think that having an official package for the YouTube Player API would be great.

By official I mean by the flutter.dev team and even collaboration from the community but mainly by the flutter team.

There are some packages that claim to be the Youtube Player API but they are not that great 🙃.

Hope you got the idea 💡

**Comment by YazeedAlKhalaf** [comment]
Any Updates?? @timsneath

**Comment by timsneath** [comment]
Just to be clear, my user ID is not a password that can be added to any issue to increase its priority :)

We know this is of interest to many. Right now, our own plug-in work is prioritizing things that we are uniquely placed to focus on: monetization capabilities like ads and in-app purchases, and plug-ins those like webview that require complex coordination across framework, engine and underlying OS. There is an unending list of plug-ins that we _could_ focus on, and it's always tough to say 'no'; but we could double our ecosystem team size and we would still not be able to cover anywhere near everything. So our focus is on enabling an ecosystem to flourish, rather than building everything ourselves.

**Comment by dblokhin** [comment]
>  like ads and in-app purchases

But the there is #12114, #35081,  https://github.com/FirebaseExtended/flutterfire/issues/1175 stucking for years...

**Comment by kilroyroboto** [comment]
I'm also perplexed as to why Google (they *own* Flutter, right??) would leave this to *languish* as some sort of "unimportant" task better left to "the community" especially when I see a list of existing plugins that [apparently] ALL violate terms of service!? It's preposterous. The YouTube mobile app works great. Why not share that knowledge with the community??

So Google *doesn't* want the community to develop apps that pull in YouTube content?? The current plugins *SUCK*!! This makes zero sense.

**Comment by RaitonGG** [comment]
we're literally robbing youtube and youtubers, as current solutions don't support ads. how is this accepted by google/flutter?

**Comment by aibor-nongkynrih** [comment]
so any plans for an official youtube plugin , dev team?

**Comment by stuartmorgan** [comment]
The current situation is that there are at least two popular plugins wrapping the official iframe-based API. That appears to be the only API available on any platform other than Android, so if were to make a plugin it would just be duplicating work the community has already done, or it would differ only in Android-specific features, and require significant investment of resources to get those single-platform features.

Given that there's no path for us to significantly improve over the existing plugins here in a general way, we don't expect to invest resources here in the foreseeable future.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement (per my comment just above).
