### ISSUE TITLE
[flutter_webview] enables JavaScriptCanOpenWindowsAutomatically by default

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#137579]
We received the following security report:

> **Issue:** `flutter_webview` has `JavaScriptCanOpenWindowsAutomatically` enabled by default. This allowed the attacks described by Yang et al. [1] in 2019 in the past.
>
> **Mitigation**: We suggest to change the default setting to match Android's default.
>
> [1] G. Yang, J. Huang, and G. Gu, “Iframes/Popups Are Dangerous in Mobile WebView: Studying and Mitigating Differential Context Vulnerabilities,” in _28th USENIX Security Symposium (USENIX Security 19)_, Santa Clara, CA: USENIX Association, Aug. 2019, pp. 977–994. Accessed: Mar. 29, 2023. [Online]. Available: https://www.usenix.org/conference/usenixsecurity19/presentation/yang-guangliang

**Comment by stuartmorgan** [comment]
This was an intentional change; see https://github.com/flutter/plugins/pull/2500 and the associated issue. Clients that are concerned about undesired top-level navigation can prevent it via the navigation delegate.

If there is a use case that requires controlling this functionality that isn't addressed by navigation delegates, please file a new issue with details.
