### ISSUE TITLE
[docs] Incorrect decoration implementation shown

### ISSUE THREAD

**Issue by IljaDaderko** [flutter/flutter#13785]
I was browsing through [HTML/CSS patterns](https://flutter.io/web-analogs/) section of documentation and noticed one thing under `Setting Background Color` section, document has following notes

> In Flutter, you set background color in a Container’s `decoration` property.

and shows this implementation

```dart
var container = new Container( // grey box
    child: new Text(
      "Lorem ipsum",
      style: bold24Roboto,
    ),
    width: 320.0,
    height: 240.0,
    color: Colors.grey[300],
  );
```

From what I've seen, don't `width`, `height` and `color` need to go under decoration?

```dart
decoration: new BoxDecoration(
    width: 320.0,
    height: 240.0,
    color: Colors.grey[300],
)
```

**Comment by Hixie** [comment]
The height and width definitely always go under Container.
The color can go under either. If you specify the color property on the Container, it's a short-hand for specifying a BoxDecoration with only a color property.

**Comment by Hixie** [comment]
Maybe we should explain that on that Web page.

**Comment by IljaDaderko** [comment]
Could be a good call, in general (personal opinion) it would be good to keep documentation using one style either with or without shorthands like this across whole pages, otherwise it brings this JavaScripty vibe to the table where one thing can be done in many ways, not necessarily bad, but I find it harder to learn flutter / dart this way.

I think there should be separate advanced section showing all of these shorthands latter on after docs perhaps? Or as you said, at least a mention on the same page.

This answers my question, feel free to close the issue if its no longer needed :)

**Comment by Hixie** [comment]
I'm leaving this open because we definitely need to explain this better.

I'm usually of the opinion that we should show all the ways to do something when there are shorthands, so that people reading the docs are prepared to read code using all the various styles. I agree that being able to do things many ways tends to lead to confusion, though in these cases since each shorthand way is clearly defined in terms of the long-hand way I hope it'll be less confusing than with the Web tech stack... (I mean, for example, this `color` shorthand is literally just expanded to a BoxDecoration in the constructor.)

**Comment by pedromassangocode** [comment]
Found in the current documentation. The [section mentioned](https://flutter.dev/docs/get-started/flutter-for/web-devs#setting-background-color) still vague.

**Comment by TheBiirb** [comment]
@Hixie My [PR](https://github.com/flutter/website/pull/4533) was just merged. Perhaps we can close this now?

**Comment by pedromassangocode** [comment]
Hi @TheBiirb 
Thank you for confirming that is was fixed.

Closing as fixed.
