### ISSUE TITLE
[Impeller] Drawing lines does not add round cap

### ISSUE THREAD

**Issue by joebImagine** [flutter/flutter#137956]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Copy and paste this code from[DartPad](https://dartpad.dev/?id=04db824d5045cc3c8caf1805f2149f33) into a flutter applications main.dart file
2. Fire up an iOS Simulator utilizing an IPAD 12.9 inch
3. Draw a straight line from right to left then go back to right
4. You will see that the end line (on the left) does not cap and is instead a sharp rectangle.

### Expected results

I would expect the line to have a rounded cap when going from right to left as it does on Android simulator, and web.  This only occurs on IOS devices

### Actual results

The end of the line when going right to left and back to left does not cap the end of the line on the left.

### Code sample

[DartPad](https://dartpad.dev/?id=04db824d5045cc3c8caf1805f2149f33) 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="717" alt="image" src="https://github.com/flutter/flutter/assets/28791015/80150fa9-0466-407c-a5a9-f60cadc3b47b">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.84.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by jason-simmons** [comment]
Reproduced this on Impeller with a simplified example:

```
import 'package:flutter/material.dart';

void main() {
  runApp(Center(child: CustomPaint(painter: TestPainter())));
}

class TestPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = Paint()
      ..color = Colors.white
      ..strokeWidth = 50
      ..strokeCap = StrokeCap.round
      ..strokeJoin = StrokeJoin.round
      ..style = PaintingStyle.stroke;

    Path path = Path();
    path.moveTo(100, 100);
    path.quadraticBezierTo(102.36, 160.545, 101.905, 160.545);
    path.quadraticBezierTo(60.545, 164.905, 60.36, 164.905);
    path.quadraticBezierTo(60.18, 164.905, 60.09, 164.905);
    path.quadraticBezierTo(60.545, 164.905, 60.815, 164.905);
    path.quadraticBezierTo(71.09, 164.36, 71.45, 164.27);

    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```

**Comment by jason-simmons** [comment]
Some of these paths seem to render correctly if I invert the return value of `StrokePathGeometry::CreateBevelAndGetDirection` at the point where the path changes direction.

@bdero

**Comment by chinmaygarde** [comment]
I was able to reproduce that at ToT today.

**Comment by bdero** [comment]
Without having looked too closely at the particular reproduction, I suspect this issue doesn't have anything to do with caps.

Quadratic/cubic components are effectively constructed out of drawing bevel joins along a polyline. If a curve component has a particularly sharp change in direction (up to the point of being pretty much discontinuous), we don't end up filling out the body of the line at the discontinuity (which should always appear round).

The polyline only encodes positions rather than angles, which means we can't solve all cases by increasing the volume of points on the polyline. One possible solution would be to detect when the angle between two polyline segments is too large and effectively insert a round join prior to the final bevel.

**Comment by bdero** [comment]
My suspicion is correct. In the reproduction, the flat edge is part of a curve component that flips 180 degrees between two of the curve's polyline segments.

https://github.com/flutter/flutter/assets/919017/25d4ba26-cd1b-464b-878e-389d9078b11f

Specifically, this quadratic bezier, which leaves all points falling on the same 2D line:
Endpoint 1: 60.36, 164.905
Midpoint: 60.18, 164.905
Endpoint 2: 60.09, 164.905

**Comment by bdero** [comment]
Reproducing this can be hit-or-miss when working with really small values, but a reliable way to reproduce this problem is by just drawing a cubic where the two endpoints are the same and the control point is anything else:
```dart
    Path path = Path();
    path.moveTo(100, 100);
    path.quadraticBezierTo(0, 0, 100, 100);
    canvas.drawPath(path, paint);
```
<img width="237" alt="image" src="https://github.com/flutter/flutter/assets/919017/e5ad74ae-f725-46ab-b28d-b56b23526733">

Here's another example where floating point imprecision leads us to drawing one of the polyline segments at a partial angle:
```dart
    Path path = Path();
    path.moveTo(60, 100);
    path.quadraticBezierTo(50, 100, 60, 100);
    canvas.drawPath(path, paint);
```
<img width="237" alt="image" src="https://github.com/flutter/flutter/assets/919017/f1c1c35c-1b17-4f2e-94b4-d215ffad2638">
