### ISSUE TITLE
Error (Xcode): project not found when archiving

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#138088]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I tried to build my app with 
```
flutter build ipa --release --flavor driver_production_store -t lib/main-driver_production_store.dart --obfuscate --split-debug-info=build/symbols --no-tree-shake-icons
```

### Expected results

The archive is succesful

### Actual results

The build fails with `Error (Xcode): project not found `
Building an archive in Xcode does work, only through the Flutter command line it fails.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Logs

<details><summary>Logs</summary>

```console
Automatically signing iOS for device deployment using specified development team in Xcode project: {redacted}
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        21.6s
Xcode archive done.                                         135.4s
Failed to build iOS app
Error (Xcode): project not found


Uncategorized (Xcode): Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure


Encountered error while archiving for device.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console


[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale en-GB)
    • Flutter version 3.13.9 on channel stable at /Users/glennruysschaert/development/flutter
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/glennruysschaert/development/flutter. Consider adding
      /Users/glennruysschaert/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/glennruysschaert/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Glenn’s iPhone (mobile) • 00008130-0005148E1061401C • ios            • iOS 17.0.3 21A360
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64 (Rosetta)
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @vixez 
I tried a sample flavors app and used below command to build ipa which was successful.

`flutter build ipa --release --flavor dev lib/main_prod.dart --obfuscate --split-debug-info=build/symbols --no-tree-shake-icons`

I verified this using latest stable but on iOS 15.3 version and lesser macOS version. I suspect if this is another case of macOS sonoma + iOS 17 combination issue, but in order to properly investigate, can you run your command in verbose mode and provide the entire log ? 

Also, try without `--obfuscate --split-debug-info=build/symbols --no-tree-shake-icons` flag, just to see if it works without passing these flags or not.

**Comment by darshankawar** [comment]
Thanks for the report @vixez 
I tried a sample flavors app and used below command to build ipa which was successful.

`flutter build ipa --release --flavor dev lib/main_prod.dart --obfuscate --split-debug-info=build/symbols --no-tree-shake-icons`

I verified this using latest stable but on iOS 15.3 version and lesser macOS version. I suspect if this is another case of macOS sonoma + iOS 17 combination issue, but in order to properly investigate, can you run your command in verbose mode and provide the entire log ? 

Also, try without `--obfuscate --split-debug-info=build/symbols --no-tree-shake-icons` flag, just to see if it works without passing these flags or not.

**Comment by vixez** [comment]
Hello @darshankawar ,
I have added the output of `flutter build ipa --release --flavor driver_production_store -t lib/main-driver_production_store.dart --verbose` here.
[output.txt](https://github.com/flutter/flutter/files/13306886/output.txt)

**Comment by darshankawar** [comment]
Thanks for the logs. I was hoping to see if there are any other log entries indicating why the error could be occuring, but couldn't find such.
Since you are on Sonoma, can you check if all your project files are stored within iCloud Drive ?
Also, I see that you are on cocoapods version 1.12.1. There was a recent fix made by them affecting Xcode version, so maybe worth trying to upgrade cocoapod to latest version and run your scenario again.
Moreover, in order to narrow down the issue, can you also try to run only `flutter build ipa` and `flutter build ipa --release` to know if these commands works properly or also throws same error ?

**Comment by vixez** [comment]
@darshankawar 
I found this is a Sentry related issue. So I will close this as it does not have anything to do with Flutter.
