### ISSUE TITLE
Engine tree closed on Linux host_debug_impeller_vulkan

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#138028]
Starting with https://github.com/flutter/engine/pull/47678, all post submit CI runs for Linux host_debug_impeller_vulkan are failing.

Runs fail consistently somewhere between 8.5m to 10m during seemingly random Vulkan playgrounds. gtest always exits with -6. No additional output indicating a problem.

![image](https://github.com/flutter/flutter/assets/919017/ba566743-7149-4a14-80d5-4bc86ae07c9e)

Sample:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8765060191207742689/+/u/test:_Host_Tests_for_host_debug_impeller_vulkan/stdout
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/455462/overview

**Comment by bdero** [comment]
@jonahwilliams speculatively reverted https://github.com/flutter/engine/pull/47678

**Comment by bdero** [comment]
The tree is open

**Comment by jason-simmons** [comment]
This test suite was failing because of a resource leak in libcxx that happens each time the test process loads and unloads SwiftShader.

Each time an Impeller Vulkan playground test case runs, it creates an `impeller::ContextVK` that owns a Vulkan instance.  The `ContextVK` and its Vulkan instance are deleted when the test case completes.

The SwiftShader library will be loaded on demand when the first Vulkan instance in the process is created.  If the test destroys the Vulkan instance and no other instances exist, then the SwiftShader library will be unloaded.

The SwiftShader library contains a static instance of `marl::Scheduler`.  When the test creates a Vulkan device, the `Scheduler` is lazily initialized.  Doing this apparently obtains a thread-local storage key.  But it appears that libcxx is not deleting this key when the library is unloaded and the library's statics are cleaned up.
(see https://flutter.googlesource.com/third_party/libcxx/+/bc553e116d25590f97f545486b5739e3aea2cf7d/include/thread#187)

So a TLS key is being leaked each time a test case runs and does an load/unload cycle of SwiftShader.  If enough test cases run within the suite, then the process will reach the `PTHREAD_KEYS_MAX` limit (1024 in this Linux environment) and fail.
