### ISSUE TITLE
please add  contextMenuBuilder for markdown

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#138291]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

rt

### Proposal

rt

**Comment by huycozy** [comment]
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
