### ISSUE TITLE
[Impeller] Linux_pixel_7pro animated_advanced_blend_perf__timeline_summary is very flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138385]
The runs on 2/3d's of the past 100 commits have flaked: https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Linux_pixel_7pro%20animated_advanced_blend_perf__timeline_summary

It appears to be crashing in the GL driver, but this benchmarks should not be using the GL backend, so I'm guessing something is going wrong with the logic or cleanup in https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L1309.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
On Arm Mali libgles.so is both the opengl and vulkan driver

**Comment by zanderso** [comment]
Ah, okay. My theory is probably wrong then.

**Comment by jonahwilliams** [comment]
So the first commit where it started crashing was:

https://flutter.googlesource.com/mirrors/flutter/+/1333e16a4a1237fcc026dac844a29e4566368fa8 

So that is probably "stencil buffer record/replay instead of MSAA storage". We should check if we can repro locally. The big change from that commit is the benchmark is running a lot faster, which in theory could trigger other bugs - but it could also have to do with the transient stencil changes too.

**Comment by jonahwilliams** [comment]
This test is no longer flaky. I suspect when @jason-simmons  rolled the vulkan deps and fixed the queue submit validation error this problem went away, the timing seems approximately correct
