### ISSUE TITLE
flutter_tools analytics is still reporting bots

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#13843]
`flutter test` was our most popular "screen" (reported by Google analytics) just before holiday break.  @tvolkert made some changes to our internal Google test running which appear to have helped reduce that.  It's now fourth most popular at 9% of total screen views.

30% of "test" screens come without city location information, with Princeton being the number 2:
<img width="579" alt="screen shot 2018-01-02 at 10 06 07 am" src="https://user-images.githubusercontent.com/11857803/34494287-a73ded64-efa4-11e7-8291-6695bc9d84df.png">

I don't know why 16% of all test events are in Princeton, NJ, presumably there is a data center there?

<img width="582" alt="screen shot 2018-01-02 at 10 07 10 am" src="https://user-images.githubusercontent.com/11857803/34494311-c22b9bee-efa4-11e7-91cd-41cba238465c.png">

googleusercontent.com accounts for 24% of all test events, presumably that's Google Compute Engine?

<img width="550" alt="screen shot 2018-01-02 at 10 07 57 am" src="https://user-images.githubusercontent.com/11857803/34494333-e2981f56-efa4-11e7-91c2-5c57098aab74.png">

I'm happy to provide analytics access to someone wanting to dive into this further.

**Comment by eseidelGoogle** [comment]
Note these numbers are from last week (while many of our users were on holiday vacation) so likely have some funny skew.  Happy to do new tables in a week.

**Comment by cbracken** [comment]
Not sure how we do the disabling now, but if we've got a single function that pushes stats to the reporting endpoint, seems like something as simple as driving it by environment variable `FLUTTER_ANALYTICS_ENABLE=0` should work.

**Comment by tvolkert** [comment]
Right now we support a `--suppress-analytics` flag, so this may be as simple as adding that flag to our Chromium tests as well.

**Comment by Hixie** [comment]
The `flutter` script tries to detect that it's on a bot and turns off analytics in that case.

**Comment by Hixie** [comment]
see e.g. https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=BOT&type=

**Comment by eseidelGoogle** [comment]
I'm told @jcollins-g is interested in investigating this.

I checked this evening and the "test" screen had returned to the top of the rankings (now that folks are back from vacation).  I'm not sure if that means bots or not:

<img width="196" alt="screen shot 2018-01-02 at 6 55 47 pm" src="https://user-images.githubusercontent.com/11857803/34507832-c5cffa7a-efee-11e7-87b3-c017afce933e.png">

**Comment by jcollins-g** [comment]
Have been digging into this; the bot detection is overridden if the user opts in to analytics by running `flutter config --analytics` (or `~/.flutter` contains: `"enabled": "true"`), because of this code here:  https://github.com/flutter/flutter/blob/b56295aac17f0a9bf195ceae4c6b456689db9485/packages/flutter_tools/lib/src/usage.dart#L48

If we're running on bots, this seems likely to be the reason why.  The reason we didn't notice this before appears to be that the bot detection does work if the user hasn't explicitly given consent to analytics.

My proposed solution is to disable analytics completely, regardless of opt-in status, if a bot is detected.

**Comment by jcollins-g** [comment]
I'll note though that this is at least in part a shot in the dark -- AFAIK we still don't have direct evidence that we're sending data from bots.  The proposed fix would just make it a lot harder to do that by accident.

**Comment by eseidelGoogle** [comment]
The per-city breakdown of `flutter test` usage as well as the correlation with `flutter test` moving to the top spot on screen usage the first workday after the holiday break suggests to me that we're collecting analytics from bots.

What's unclear to me is what % of our numbers the bots account for, or how we're we could be getting them in our numbers in the first place.  Looking at a breakdown of `test` screens by existing vs. new user it seems many of them come from existing users, which surprises me, as I would expect most bots to show up as new users every run?

**Comment by jcollins-g** [comment]
The AWS hits could be someone using AWS CodeBuild -- those environment variables aren't in our detection list.  Same with Jenkins.

Some CI systems allow caching of some data, or pre-initialization with a snapshot for config files (possibly including our ~/.flutter).  Users themselves might set up situations like that as well even if the CI doesn't.  Either situation would create persistent "users" to the view of our analytics.

Still looking at this.

**Comment by jcollins-g** [comment]
Running dev/bots/test.dart indirectly enables analytics for you in the persistent config file `~/.flutter`.   Probably a test is leaking.  Flutter's own bots could easily be generating a pile of this data as a result of that combined with [this](https://github.com/flutter/flutter/issues/13843#issuecomment-355120336), since dev/bots/test.dart creates a series of flutter test runs.

**Comment by jcollins-g** [comment]
To be clear, the combination of bugs only impacts people running flutter repo tests.  Users would still have to be doing something to create the situation themselves for flutter packages.

**Comment by jcollins-g** [comment]
Narrowed down the leakage of writing to .flutter to the analytics tests themselves.  There's a valiant effort to prevent exactly this from happening that doesn't seem to matter, for some reason.  Still investigating.

**Comment by jcollins-g** [comment]
So.  I've learned exactly why the writing of .flutter happens in test.  The explanation is somewhat involved, but here are the highlights.

Flutter's Usage class creates an AnalyticsIO instance here.
https://github.com/flutter/flutter/blob/96942bc797959bd687b71323227047775f62f327/packages/flutter_tools/lib/src/usage.dart#L26

This AnalyticsIO instance is built by a third-party library in the pub package, "usage".  It creates an instance of IOPersistentProperties based on the app name and an optional Directory instance passed in.
https://github.com/dart-lang/usage/blob/413a189e20a365796c836f1762a4be399f7f9980/lib/src/usage_impl_io.dart#L30

And it is this class that writes out the file, like this.
https://github.com/dart-lang/usage/blob/cfe879bc018b3571008355c7f0235a4b18b9ad9b/lib/src/usage_impl_io.dart#L147

A Directory needs to be passed in to the AnalyticsIO constructor to prevent this, but none of the code intended to isolate the filesystem during tests covers this case.

**Comment by Hixie** [comment]
Nice!

**Comment by jcollins-g** [comment]
Merged the fix.   If some of our assumptions and our diagnosis is correct, we should start to see some immediate changes in analytics as our primary generator of flutter test 'screens' is likely Flutter's own Travis.  No guarantees here though, of course -- while these were real problems, the degree to which they impacted the analytics is still an assumption.  There could be unknown factors somehow triggering analytics on bots despite all this.

**Comment by jcollins-g** [comment]
`flutter test` has disappeared from the top 20 screen lists in the realtime view; it used to consistently be in the top 10.  Additionally, the number of test screens added today has slowed to a bare trickle after landing #13915.

**Comment by jcollins-g** [comment]
I think we can declare at least a partial victory: stats for the test screen are way down today and Friday from typical.

However, there may still be more to do.  The user explorer suggests there are individual users that are exhibiting very bot-like behavior (for example, doing nothing but flutter upgrade and precache over and over every day since the beginning of analytics), and #13915 hasn't seemed to stop them right away.

![screenshot from 2018-01-08 13 35 52](https://user-images.githubusercontent.com/14116827/34693690-86ab6598-f479-11e7-808b-d6c6fba3636e.png)

However, it might not be possible to know whether those fixes will squish these out until the alpha includes it.

**Comment by cbracken** [comment]
@jcollins-g this is in my command history (and I expect @a-siva did the same too):
```
while true; do rm -f .packages pubspec.lock; flutter packages get; done
```

We were trying to locally repro a segfault we'd been seeing on one of the mac build bots.

**Comment by jcollins-g** [comment]
Analytics are looking really good at the end of the week to my eyes, though I'm no expert at the dashboard.

**Comment by Hixie** [comment]
Closing as done.
