### ISSUE TITLE
i keep having this error from dart framework: Failed assertion: line 4809 pos 16: 'owner!._debugCurrentBuildTarget == true': is not true.

### ISSUE THREAD

**Issue by Zomazu** [flutter/flutter#138484]

**Comment by opxdelwin** [comment]
@Zomazu Please create a new issue along with filling out necessary details available in issue template. We cannot help anyone without necessary data or context.

**Comment by huycozy** [comment]
@Zomazu When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
