### ISSUE TITLE
[docs] Automated release notes do not respect release.yml changes

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#138620]
Automated release notes do not respect release.yml changes

When attempting to generate release notes for Flutter 3.17 beta, it was discovered that there was a missing `labels` parameter in [release.yml](https://github.com/flutter/flutter/blob/master/.github/release.yml#L56).  Though, with changes the automated release notes do not account for the the structure determined by release.yml.

**Comment by CaseyHillers** [comment]
> Will pushing new tags kick off any CI changes? @godofredoc

Yes. It'll run the entire devicelab suite, so ideally we'd want to land these CPs outside 10 AM - 4 PM PST.

> Are there concerns with this approach? @CaseyHillers

I don't have large concerns. This might be the easiest path forward, and I suspect in a few months the release.yml will have stabilized.

I do wonder if there's a way we can explicitly tell it to use the release.yml from HEAD instead of the tag.

**Comment by itsjustkevin** [comment]
Update:  Release configuration is generated at the end tag, not the beginning tag.

new tag name for the 3.17 beta notes is `3.17.0-0.1.pre-rev2`
