### ISSUE TITLE
Concerns Regarding the Removal of `--dart-define-from-file` Feature

### ISSUE THREAD

**Issue by blendthink** [flutter/flutter#138793]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm writing to express my concerns regarding a recent change introduced in the following pull request: #136865 . This update seems to have altered the behavior of the `--dart-define-from-file` feature, preventing entries specified in the file from being written into Gradle configuration values or environment variables during the build process.

As outlined in this article (https://zenn.dev/altiveinc/articles/separating-environments-in-flutter), many projects relying on `--dart-define-from-file` for environment separation now face the necessity of revising their processes. While I understand that Flutter's official documentation (https://docs.flutter.dev/deployment/flavors) recommends setting environments separately for iOS and Android, this approach can significantly increase the number of files and configurations, leading to higher costs.

Although solutions like the Flutter Flavorizr package (https://pub.dev/packages/flutter_flavorizr) can reduce these costs, they often obfuscate various processes, potentially complicating maintenance. The introduction of `--dart-define-from-file` was a response to a community need, as seen in this issue: #107810 , and its implementation was intended to directly utilize project variables in Android's build.gradle and environment variables in iOS.

### Proposal

In light of the current situation, I believe it would be more appropriate to document the `--dart-define-from-file` feature rather than removing it. Even if it was introduced unintentionally, considering that it has been added and potentially utilized by many users, it would be prudent to provide some form of alternative solution.

**Comment by blendthink** [comment]
@christopherfujino 
I have created an issue regarding the matter we discussed on Discord. I thought it might not be appropriate to label it as a bug, so I submitted it as a feature request. Thank you for your attention to this matter.

**Comment by TatsuUkraine** [comment]
I'm also curious why passing env variables from the file into native was marked as bug and removed? this feature was awesome for CI/CD configuration

**Comment by andrewkolos** [comment]
Hello, I'm the author of #136865, the PR that removed this functionality. First of all, thanks for the high-quality issue, and thanks to those that have added 👍 reactions to indicate that this has affected them. Before I get to my opinion on what should be done to resolve this issue, I'll summarize the story of this functionality for those that aren't already familiar with it:

1. As helpfully pointed out by @blendthink, `--dart-define-from-file` was proposed in https://github.com/flutter/flutter/issues/107810. To summarize, `--dart-define-from-file` is similar in purpose to `--dart-define`. Specifically, it allows the user to provide a file containing multiple definitions. **However, definitions from `--dart-define-from-file` are not only available in the user's dart code (at compilation time), but also during the native build process that takes place as part of `flutter run`/`flutter build`.** For iOS, macOS, Linux, and Windows, [the definitions are available in the system environment](https://github.com/flutter/flutter/commit/cbfe5a52264d3c7151d084972fff15ba962c7f28#diff-d03da464534929df8e6ddaa8005035584b44c23ffde008d3eca230d3dec7bdedR267). For Android, [these are available in Gradle as properties.](https://github.com/flutter/flutter/commit/cbfe5a52264d3c7151d084972fff15ba962c7f28#diff-d03da464534929df8e6ddaa8005035584b44c23ffde008d3eca230d3dec7bdedR344)
2. Later on, https://github.com/flutter/flutter/issues/136444 is filed with the title "dart-define not working with info.plist variables". This issue pointed out the difference in behavior between `--dart-define` and `--dart-define-from-file` that I mentioned earlier. **I then triaged the issue and concluded that definitions from  `--dart-define` (and thus `--dart-define-from-file`) are only meant to be available in the user's dart code at compilation time[^1]**. I then file and merge the PR (#136865) that removes the extra functionality unique to (`--dart-defines-from-file`), hence this issue.

I still believe that `--dart-define-from-file` entries should have never been available outside of application dart code at compilation time. Also, according to [Flutter's policy on breaking changes](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change), the removal of this functionality is not considered a breaking change (though I admit this change should have been announced). **However**, I recognize that 1) this functionality was plainly explained in the original feature request, 2) it was approved during twice during PR review, and 3) several users have come to depend on it.

I don't have a firm opinion here. I propose that we do one of the following:
1. Keeping this functionality removed from `--dart-define-from-file` and instead moving it to a new `flutter` cli option (such as `--build-define-from-file`).
2. Restoring this functionality, but also adding it to `--dart-define`, which would bring `--dart-define` closer to parity with `--dart-define-from-file`.[^2]

I'm happy to clarify anything here, and I'm open to other's thoughts.

Anyway, I'm prioritizing this as P1 (at least for now) since 1) the functionality was removed without announcement, 2) this is in stable, and 3) there is, to my knowledge, no easy work around for users targeting Android.

[^1]: https://github.com/flutter/flutter/issues/136444#issuecomment-1767319501
[^2]: This could theoretically result in breakages as users of `--dart-define` as those entries could overwrite existing properties in Gradle and/or the system environment, but users would be able to workaround this change fairly easily.

**Comment by Kurogoma4D** [comment]
I also agree this issue and think 2nd proposal (restore this function) from @andrewkolos is better.
When building a Flutter app, it is very natural to create the same environment classification as Dart on the platform side.
Flutter's strength is its ability to run on multiple platforms with a single code base, and it wouldn't be surprising if that were an environment variable.

**Comment by TatsuUkraine** [comment]
There might be third option, which could be a little bit safer:
1. Restore removed functionality by reverting changes (option 2)
2. Add new key to the cli (option 1) and revert changes made in first step

In that way flutter can rollout patch (if this feature already removed in stable) and do safe transition to a new functionality.

I do think that moving "native and dart available" env variables into own key may be beneficial since I personally faced with some scenarios when some variables were intent to be dart code only, where is other ones - native. Such as public keys for Android/iOS SDKs that are needed exclusively for native SDKs init and never used in dart code. I also faced with packages that require init in that dart code, where this public key is passed into the native layer by the package itself.

And also there might be cases when variable is needed everywhere to keep app functioning in all layers the same

P.S I don't have strong opinion on either proposed solution as long as we have an ability to easy define compile time variables for the native layer during the build)

**Comment by bartekpacia** [comment]
> Restore removed functionality by reverting changes (option 2)

I'm against doing that. To me, `--dart-define` and `--dart-define-from-file` sound like they should be behaving exactly the same, but they were not. That's why I filed #130599 and was happy to see this "feature" go away.

I'll present a different perspective here. I'm the author of a tool (`patrol_cli`) that wraps the `flutter` CLI. At some point we wanted to expose `--dart-define-from-file` in our CLI and forward it to Flutter, but because of its strange behavior and inconsistency with plain `--dart-define`, we decided not to.

On a side note, I think the following case is not documented sufficiently: passing both `--dart-define`s and `--dart-define-from-file`s with the same keys – how does overwriting of values work in this case? Do later keys override the earlier, or vice versa? I'd expect it to be explained by the help message in e.g. `flutter build apk --help`. Anyway, this topic probably deserves its own issue.

**Comment by TatsuUkraine** [comment]
> I'm against doing that. To me, --dart-define and --dart-define-from-file sound like they should be behaving exactly the same, but they were not. That's why I filed #130599 and was happy to see this "feature" go away.

Sorry, maybe I didn't describe it clear enough. I described steps, not options. I can imagine removed functionality will affect quite a lot of users. So my proposal is to tmp restore original behavior as a short term solution to prevent breaking changes and patch it (if these changes already in stable). And the next step - or add this functionality to dart-defines, or add separate key to cli to pass compile time variables to native. Basically or option 1 or 2 from [this message](https://github.com/flutter/flutter/issues/138793#issuecomment-1821923832)

**Comment by bartekpacia** [comment]
> so my proposal is to tmp restore original behavior

Users may already be depending on `--dart-define-from-file` *not* passing values to native build systems. Somebody might have a define called `TARGET` (that was previously only bound to Dart). Bringing back this change will cause the `TARGET` to overwrite `TARGET` that is automatically passed to `xcodebuild` and `gradle`, possibly breaking workflows.

**Comment by TatsuUkraine** [comment]
If devs already had these key in 3.13, prior to this revert, nothing changes for them. If they didn't - nothing changes for them too

**Comment by TatsuUkraine** [comment]
Since these feature existed since 3.7 release, and was working fine in past few stable releases

**Comment by bartekpacia** [comment]
> If devs already had these key in 3.13 for any weird reason), prior to this revert, nothing changes for them. If they didn't - nothing changes for them too

And if they had these keys in 3.16, something will break.

**Comment by TatsuUkraine** [comment]
> And if they had these keys in 3.16, something will break.

Removal of this feature already broke working build processes for existing projects)

long story short, I proposed a variant to restore functionality that was originally passed reviews and discussions. In general I don't have strong preference one over another (original 2 options, or third one that combines both), as long as we can get this feature back in short term perspective and don't wait for the next stable release before working feature, which simplified a lot of ci/cd questions, will be brought back

**Comment by TatsuUkraine** [comment]
> Removal of this feature already broke working build processes for existing projects)

For instance now I can't simply bump flutter version in a few of my projects before I figure a workaround for build processes in bitrise and codemagic. And I know quite a few people who will have exactly the same problem

**Comment by TatsuUkraine** [comment]
And one more important point to note. After this feature was removed it seems there is no way at all to get access to these variables in native. Unlike dart-defines which are included in both iOS and Android as base64 encoded string.

 Which brings devs to quite tricky situation - they will need either stick to prev stable release untill this feature will be wrought back (in one or another way) or revert all their build workflows back to approach from flutter 2.2

**Comment by andrewkolos** [comment]
Hello. Sorry for the lengthy silence on this one—I wanted to give myself a proper amount of time to consider this issue.

I stand by my prior decision to keep `--dart-define-from-file` definitions from being injected into the build environment. While it is unfortunate that this aspect of the `--dart-define-from-file` slipped through review when the feature was proposed and implemented, it ultimately doesn't match the intent of the `--dart-define` option, and it doesn't match the intent of the `--dart-define-from-file` option as understood by those who reviewed and accepted it. Again, I apologize for not going through the [announcement process](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change) when removing this aspect of `--dart-define-from-file`. At that time, I hadn't realized that the original proposal included injecting definitions into the native build environment.

I imagine that users that relied on this functionality can workaround the issue by writing their own wrapper scripts that set environment definitions before invoking `flutter run` or `flutter build`. 

Lastly, I'd still be willing to review a proposal or PR for a new command line option that reintroduces the functionality, but I don't believe this is something we would cherry-pick into the stable channel. See [Flutter's cherrypick policy on the wiki](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#goal).

Everyone here has my thanks for contributing their concerns.

I will be closing this issue as a "won't fix". However, I will keep following this issue until it's locked.

Other notes:

> On a side note, I think the following case is not documented sufficiently: passing both `--dart-define`s and `--dart-define-from-file`s with the same keys – how does overwriting of values work in this case? Do later keys override the earlier, or vice versa? I'd expect it to be explained by the help message in e.g. `flutter build apk --help`. Anyway, this topic probably deserves its own issue.

While this wasn't always the case, entries from `--dart-define` now override entries with identical keys that come from `--dart-define-from-file`. This is [documented in the help text](https://github.com/flutter/flutter/commit/30692ee4b787998ac5cd0babaccb8b85b7cfcdfa#diff-bddc4f9aed1d00d6a61dc771206640bfd19866f63a77d5d343d6a473c5f00c10R650).

> And one more important point to note. After this feature was removed it seems there is no way at all to get access to these variables in native. Unlike dart-defines which are included in both iOS and Android as base64 encoded string.

This sounds like an internal implementation detail of Flutter, not a supported feature. Per the name of the option and the help text, entries from `--dart-define` are only meant to be accessed by the user through Dart code in their Flutter app. While I personally don't foresee us changing this implementation detail anytime soon, it could theoretically change at any time without notice.

**Comment by TatsuUkraine** [comment]
@andrewkolos is there any way we can get some variant of "native-define" or anything like that?) Catch here that flavors is overcomplicated way of providing build time variables for native. And functionality of dart-defines (including file) was very convenient for CI/CD configuration.

> I imagine that users that relied on this functionality can workaround the issue by writing their own wrapper scripts that set environment definitions before invoking flutter run or flutter build.

Problem with this that there is no normal way to do this when it comes to IDE plugins

**Comment by andrewkolos** [comment]
> @andrewkolos is there any way we can get some variant of "native-define" or anything like that?) Catch here that flavors is overcomplicated way of providing build time variables for native. And functionality of dart-defines (including file) was very convenient for CI/CD configuration.
> 
> > I imagine that users that relied on this functionality can workaround the issue by writing their own wrapper scripts that set environment definitions before invoking flutter run or flutter build.
> 
> Problem with this that there is no normal way to do this when it comes to IDE plugins

Anyone is welcome to write an issue that proposes such a CLI option, and anyone is welcome to write a PR that implements it. I would be happy to review. I'm hesitant to commit myself to implementing it personally, as I'm working on other high priority work at this time.

**Comment by pio-sakai** [comment]
@andrewkolos 
Does this problem occur with the 3.17 stable board?
(Is the problem limited to the 3.17 beta?)

**Comment by erf** [comment]
@andrewkolos  Could you keep us up to date regarding when this change will be in stable? I have a couple of production apps using `dart-define-from-file` in the build step.

**Comment by TatsuUkraine** [comment]
As far as I know this feature still available in 3.16 (at least they were last time I checked). So I can assume, since these changes already merged, they will be rolled out in next big stable release

**Comment by christopherfujino** [comment]
The tracking issue for re-implementing this functionality is at https://github.com/flutter/flutter/issues/139289, please follow there for the latest updates.
