### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by progmaksudur** [flutter/flutter#138720]
## Command
```
flutter build apk --analyze-size --target-platform=android-arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base

**Comment by dam-ease** [comment]
Hi @progmaksudur. This has been fixed in the latest version of flutter stable. See https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3134-september-13-2023.

Closing from here. If you still face this issue on the latest version of flutter stable (3.16.0), kindly leave a comment below and I will reopen this.

See https://github.com/flutter/flutter/issues/132695 for the original issue.

Thank you

**Comment by progmaksudur** [comment]
Thank you
