### ISSUE TITLE
Create an external Committee to represent the community 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#138961]
Unfortunately we have had many prominent figures leave the Flutter development team in the recent years. Almost all founding fathers like @Hixie, @abarth, @eseidel have left (sorry if I am forgetting others), also @timsneath left and he's working for a very prominent player in the mobile apps sector.

We also have many industry leaders using Flutter right now, which means any change in the Framework will affect their budget for better or worse.

Flutter is an open source project, with lots of its parts driven by the community. During @timsneath time Flutter pushed for more openness, releasing regularly its long term goals and strategies.

I believe, and would like to ask for others opinions and views on this, that right now Flutter also needs a Committee, of independent actors, that can influence and represent the general community. Many open-source projects have Committees, this shows maturity, stability, openness and support, which are values we like about Flutter.

Thereby, I think it would be very positive for Google to allow the creation of an independent Committee, that could serve as advisors for vision, strategy and to raise concerns.

I would ask, if possible, to add into the Committee the prominent people that left the project, since they have the strategic and technical visions we need in Flutter. I imagine most of them departed in good terms and would be welcomed back in an independent position like this.

________

I know this is not a technical issue, but please don't close this, since github isses are the main/open/documented communication channel for Flutter.

**Comment by jonahwilliams** [comment]
Anyone should be able to participate in Flutter, regardless of their employer (a fact that @Hixie will certainly put to the test in the coming months). The discord is open to contributors and the process for sponsorship does not require Googles consent 

It's not clear to me what specific problems an "external committee" would solve. I would also like to push back against the framing as being "external" to Google mattering. Anyone can be a part of Flutter. If you want to be part of the decision making process, the first step is to roll up your sleeves and get to work.

**Comment by feinstein** [comment]
@jonahwilliams how's the process for putting up documents like https://flutter.dev/go/strategy-2023? Are devs in the discord channel asked about their opinions? I know the general day-to-day work can be scrutinized, but the long term strategy and roadmap I imagined was more a "closed doors" process, since this usually have to align with Google's internal customers/projects, which are private.

I remember the first time Tim released such a document, he said he couldn't reveal everything, since there were internal matters that couldn't be disclosed, and I think this is very reasonable, so a Commitee could help in a situation like this, representing the community in private matters.

My main concern is how Flutter will evolve in the next 3 years, and having a known and respected committee could influence the decision making inside of Google, to invest more resources in Flutter, or to question why we are going in a specific direction.

**Comment by Hixie** [comment]
@feinstein  https://flutter.dev/go/strategy-2023 is _Google's_ strategy for what they want to do with Flutter. The Flutter project's roadmap is on the wiki, <https://github.com/flutter/flutter/wiki/Roadmap>. I plan to update this for 2024 in the coming couple of months. That's the project-wide summary of what everyone who contributes to Flutter expects to do.

So what ends up on the roadmap is whatever people indicate they will be working on. For example, Google surely has a 2024 strategy for Flutter, and will be letting me know what they will be doing that should be added to the roadmap to represent their efforts. Similarly, I'll be adding the things I plan to work on to the roadmap. If you have something you are planning on doing, then I will be more than happy to learn all about it and add it to the roadmap as well. Conversations about this will be happening on the Discord (see <https://github.com/flutter/flutter/wiki/Chat>), probably near the end of the year, start of next year.

Let me know if that answers your questions!

**Comment by feinstein** [comment]
Thanks @Hixie this helps a lot.

Since you left many people reached me, concerned about the future of Flutter. What I am telling them is that I don't Flutter will die, I am just afraid we might lose focus and not be as great we can be.

I have never been inside any decision making for Flutter, so in my naive view, a Committee would serve as "glue" between Google's strategy and the Community strategy, when those don't align. I have also seen some signals that Google's higher management might not be as connected with Flutter's future and roadmap, so a Committee could also be a mechanism to convey with them, nudging them into the right direction, with no worries of being fired. And if it doesn't work, the Committee can expose what's happening to the community in general, so we all can apply some pressure.

Many open source projects have Committees, so I wonder why Flutter wouldn't benefit from this. Am I missing something?

**Comment by Hixie** [comment]
I guess I don't understand what problem we're trying to solve. I'm not aware of any time where we've had a situation where two contributors or groups (companies) of contributors have had conflicting strategies. Overall the Flutter project's strategy is pretty simple: make it possible to write apps on any platform ("Flutter on every screen").

If the problem you want to solve is "convincing Google management to spend money a particular way", then that's not a problem to solve at the level of the Flutter open source project, it's something to take up with Google directly. If the problem you want to solve is one of transparency, then a committee isn't a good solution, a better solution would be creating a e-zine/blog about the project. That would be really useful in general, I think. A lot of our users as well as many of our contributors (including me!) would benefit from being more informed about what the team as a whole is doing! If you need help starting something like that, please don't hesitate to reach out on the Discord, I'd be more than happy to give guidance or find resources to support starting something like that (e.g. hosting a web site, buying a domain name, or whatever you need).

In general, committees are the worst way to solve any problem (there's a reason the 1944 OSS [Simple Sabotage Field Manual](https://www.cia.gov/static/5c875f3ec660e092cf893f60b4a288df/SimpleSabotage.pdf) literally suggests creating committees, see page 28). Lots of open source projects do things in ways that aren't a good idea. I don't think we should do things just because they're popular, we should do them because they are good ideas that solve real problems.

**Comment by feinstein** [comment]
@Hixie thank you for your insights, it's refreshing to see senior members not worried about the future and direction of Flutter, this might be a feeling we on the outside have.

I have just moved from Brazil to Australia, so it has been pretty hard for me to have any personal projects right now, but when things settle, I will try to be more active on Discord, I am feeling a lot is happening there and I am missing.

I will close this issue then, since it now appears to me that a Committee won't help, given Flutter's current organizational model.
