### ISSUE TITLE
One exception will do, what is the problem?

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#138943]
https://gist.github.com/cyberpwnn/bdfc09ef1d48702ae30b40c9604d2af6

How am I supposed to read this? What box constraints are being talked about? I see that my navigator key is involved but I dont know how. More information is not helpful if its useless information in exceptions.

**Comment by iapicca** [comment]
@cyberpwnn you don't need to pay to much attention to the whole stack
the first part tells you already what went wrong (you forgot to put size in a widget in a list)
and where (`myguide_navigation_bar.dart` line 118)

```console
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite width.

These invalid constraints were provided to RenderPadding's layout() function by the following function, which probably computed the invalid constraints in question:
  _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:1273:9)
The offending constraints were: BoxConstraints(w=Infinity, 0.0<=h<=Infinity)
The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#7bbbe] Navigator:file:///C:/Users/cyberpwn/Documents/development/workspace/MyGuide/myguide/lib/features/root/screen/myguide_navigation_bar.dart:118:15
When the exception was thrown, this was the stack: 
/// # bla bla bla
```

also you are getting multiple exception because a bunch of objects in the list are throwing

**Comment by dam-ease** [comment]
Thanks for your input @iapicca.
@cyberpwnn As said [here](https://github.com/flutter/flutter/issues/138943#issuecomment-1824538622), the first part already points to what the issue is and where the issue lies in your project. 

This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and ask questions like this, you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
