### ISSUE TITLE
Unclear assertion message

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1390]
'packages/flutter/src/rendering/object.dart': Failed assertion: line 650: 'constraints.isNormalized' is not true.

**Comment by abarth** [comment]
I'm not sure how to take action on this bug.  I would be useful to know what you were trying to do when you hit this assert.  Was the problem a bug in the framework (that we should fix) or a bug in your code (that we should have a better error message to explain)?  If its the latter, it would be help to know wha the problem was in your code so we know what to guide you to.  :)

**Comment by apwilson** [comment]
I don't really remember.  I'll close this.
