### ISSUE TITLE
The supplied phased action failed with an exception. Could not create task ':path_provider_android:compileDebugUnitTestSources'. this and base files have different roots: D:\flutter\flutter_application_1\build\path_provider_android and C:\Users\kanch\AppData\Local\Pub\Cache\hosted\pub.dev\path_provider_android-2.2.1\android.

### ISSUE THREAD

**Issue by VENKATSAI643** [flutter/flutter#139010]
I have tried all the possible ways to solve it but it is not getting solved....

**Comment by darshankawar** [comment]
@VENKATSAI643 
In order to properly address the issue, please try to use new issue [template](https://github.com/flutter/flutter/issues/new/choose) and fill out requested details so that we'll have enough info to analyze the issue. Just providing error message in issue title isn't enough for us to make it actionable.
Closing for now due to lack of details.
