### ISSUE TITLE
[Impeller] EntityTest.BezierCircleScaled executed multiple times per run

### ISSUE THREAD

**Issue by flar** [flutter/flutter#139090]
Recently this one unit test is starting to be executed multiple times per unit test run. It used to run once (on 3 platforms potentially) and now it is run 4 times (each on 3 platforms).

https://github.com/flutter/engine/blob/112cb24d9eb2c9582f2e958184751130a2a762d8/impeller/entity/entity_unittests.cc#L921

**Comment by chinmaygarde** [comment]
I am not quite sure what you mean. Can you point to a CI run where this is happening? Or is this locally?

**Comment by chinmaygarde** [comment]
I see that EntityTest.BezierCircleScaled is parameterized to the backend. And it should run once per backend. I see,

```
Play/EntityTest.BezierCircleScaled/OpenGLES
Play/EntityTest.BezierCircleScaled/Metal
Play/EntityTest.BezierCircleScaled/Vulkan
```

I think that is expected. You could apply a filter like so `*Circle*/Metal` perhaps to just restrict to one backend.

But that is still three times per test. Not sure how you got 4.

**Comment by chinmaygarde** [comment]
Yeah, I can reproduce it now. So odd.

**Comment by chinmaygarde** [comment]
I tried to see how we instantiated the test suite and I cannot see anything off. Tracing into gtest to see why it decides to run these tests multiple times and I'm at a bit of loss unfortunately.

**Comment by jason-simmons** [comment]
This is caused by the calls to `INSTANTIATE_PLAYGROUND_SUITE(EntityTest)` that were recently added to:
* entity/contents/checkerboard_contents_unittests.cc
* entity/contents/tiled_texture_contents_unittests.cc
* entity/contents/vertices_contents_unittests.cc

@jonahwilliams Is there a configuration where these additional `INSTANTIATE_PLAYGROUND_SUITE` calls are required?

There is already a call to `INSTANTIATE_PLAYGROUND_SUITE(EntityTest)` in `entity/entity_unittests.cc`.  When I build `impeller_unittests` that call seems to be sufficient.

**Comment by jonahwilliams** [comment]
That is ... interesting. lets remove those calls.

**Comment by chinmaygarde** [comment]
Wow, I didn't know that was illegal. We should make it and remove the duplicate ones. One easy way to prevent this in the future would be to add  `[[maybe_unused]] const char* kYouInstantiated##playground##MultipleTimes = "";` to the macro expansion of `INSTANTIATE_PLAYGROUND_SUITE`. That way, the linker will tell you that that "YouInstantiatedEntityTestMultipleTimes" has multiple definitions.
