### ISSUE TITLE
[Impeller] New gaussian blur has gap.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#139165]
This is a flaw in the new gaussian blur that isn't turned on by default.

cc @jonahwilliams 

## reproduction

```diff
--- a/impeller/entity/contents/filters/filter_contents.cc
+++ b/impeller/entity/contents/filters/filter_contents.cc
@@ -50,6 +50,8 @@ std::shared_ptr<FilterContents> FilterContents::MakeDirectionalGaussianBlur(
   return blur;
 }
 
+#define IMPELLER_ENABLE_NEW_GAUSSIAN_FILTER 1
+
```

```dart
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';

final _random = Random();

void main() => runApp(const BackdropFilterDemo());

class BackdropFilterDemo extends StatelessWidget {
  const BackdropFilterDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Stack(
          children: [
            ListView.separated(
              separatorBuilder: (_, __) => const SizedBox(height: 8),
              itemBuilder: (context, index) => BlurEffect(
                child: Container(
                  height: 50,
                  color: Colors.primaries[_random.nextInt(17)].shade300,
                  child: Center(
                    child: Text(index.toString()),
                  ),
                ),
              ),
              itemCount: 200,
            ),
            Positioned.fill(
              bottom: null,
              child: BlurEffect(
                child: Padding(
                  padding: EdgeInsets.only(
                    top: MediaQuery.of(context).viewPadding.top,
                  ),
                  child: const SizedBox(height: 45),
                ),
              ),
            ),
            Positioned.fill(
              top: null,
              child: BlurEffect(
                child: Padding(
                  padding: EdgeInsets.only(
                    top: MediaQuery.of(context).viewPadding.bottom,
                  ),
                  child: const SizedBox(height: 50),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class BlurEffect extends StatelessWidget {
  final Widget child;

  const BlurEffect({
    required this.child,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(
          sigmaX: 28,
          sigmaY: 28,
          tileMode: TileMode.mirror,
        ),
        child: DecoratedBox(
          decoration: BoxDecoration(color: Colors.black.withOpacity(.65)),
          child: child,
        ),
      ),
    );
  }
}
```
## screenshot

![IMG_6750](https://github.com/flutter/flutter/assets/30870216/f312e6b2-f390-4a76-8e3e-e7c5a7fc3dcb)

**Comment by jonahwilliams** [comment]
I don't think the existing blur is doing anything that intricate. I'd make sure that your examples are configuring the sampling options for the input sample correctly (i.e. repeat, clamp, decal).

**Comment by gaaclarke** [comment]
Here is the blurred texture with the halo, which is expected and correct (maybe in the future we could optimize that away if we know it will be offscreen?)

<img width="534" alt="Screenshot 2023-11-28 at 2 29 44 PM" src="https://github.com/flutter/flutter/assets/30870216/ec964f59-20ca-4c19-80ae-57d5ce45a5e9">

Here is drawing the texture, notice the gap is present.  If the green rect for the drawing is to be believed, that is incorrect.  The frame of the draw should be outside of the target texture, thus cropping the halo.

<img width="551" alt="Screenshot 2023-11-28 at 2 30 05 PM" src="https://github.com/flutter/flutter/assets/30870216/eda99bc8-df7d-4853-b22d-0f396dd14f44">

If the draw rect was somehow getting clamped to fit within the target texture that could explain the gap.

**Comment by gaaclarke** [comment]
I'm guessing this SetCoverageHint is doing the squashing: 
```c++
bool Entity::Render(const ContentContext& renderer,
                    RenderPass& parent_pass) const {
  if (!contents_) {
    return true;
  }

  if (!contents_->GetCoverageHint().has_value()) {
    contents_->SetCoverageHint(
        Rect::MakeSize(parent_pass.GetRenderTargetSize()));
  }

  return contents_->Render(renderer, *this, parent_pass);
}
```

**Comment by gaaclarke** [comment]
I think if the new blur starts handling the clip coverage correctly this gap will go away.  That's a better solution than trying to make the textures we are generating now render correctly since they are suboptimal.

**Comment by gaaclarke** [comment]
The following patch fixes the `AiksTest.CanRenderClipBlurred`, but doesn't fix this issue.  It does this by instead of scaling down the vertices in the downsample pass, scales up the UVs so that the gutter isn't empty.  The fact that it doesn't fix this shows that eliminating the gutter in the resulting texture when it is cut off by the clip coverage is what we want.

```diff
--- a/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
+++ b/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
@@ -68,19 +68,19 @@ std::shared_ptr<Texture> MakeDownsampleSubpass(
         // Insert transparent gutter around the downsampled image so the blur
         // creates a halo effect.
         Vector2 texture_size = Vector2(input_texture->GetSize());
-        Quad vertices =
+        Quad guttered_uvs =
             MakeAnchorScale({0.5, 0.5},
-                            texture_size / (texture_size + padding * 2))
-                .Transform(
-                    {Point(0, 0), Point(1, 0), Point(0, 1), Point(1, 1)});
-
-        BindVertices<TextureFillVertexShader>(cmd, host_buffer,
-                                              {
-                                                  {vertices[0], uvs[0]},
-                                                  {vertices[1], uvs[1]},
-                                                  {vertices[2], uvs[2]},
-                                                  {vertices[3], uvs[3]},
-                                              });
+                            (texture_size + padding * 2) / texture_size)
+                .Transform(uvs);
+
+        BindVertices<TextureFillVertexShader>(
+            cmd, host_buffer,
+            {
+                {Point(0, 0), guttered_uvs[0]},
+                {Point(1, 0), guttered_uvs[1]},
+                {Point(0, 1), guttered_uvs[2]},
+                {Point(1, 1), guttered_uvs[3]},
+            });
 
         SamplerDescriptor linear_sampler_descriptor = sampler_descriptor;
```

**Comment by gaaclarke** [comment]
I think the solution is going to be something like this:

```c++
// Calculate the UV rect in local coordinates.
Rect source_uvs = Rect::Make(0, 0, snapshot.texture.width, snapshot.texture.height);
Quad local_uvs =  snapshot.transform * source_uvs;
std::optional<Rect> local_uv_rect = local_uvs.ToRect();
// I think this has to be true for snapshots.
assert(local_uv_rect.has_value());

// Calculate the vertices in local coordinates.
Quad coverage_quad = 
  snapshot.transform * 
  Matrix::MakeTranslate(-padding) * 
  source_uvs.Expand(padding);
std::optional<Rect> coverage_rect = coverage_quad.ToRect();
assert(coverage_rect.has_value());

// Apply the clip in local space
Rect uv_union = clip_rect.Union(local_uv_rect.value());
Rect coverage_union = clip_rect.Union(coverage_rect.value());

// Create a subpass that matches our desired clip size exactly
Size subpass_size = coverage_union.size;
Matrix normalizer = Matrix::MakeScale(1 / subpass_size.width, 1 / subpass_size.height);
Matrix offset = Matrix::MakeTranslate(-coverage_union.TopLeft());
Quad vertices = offset * normalizer * coverage_union
Quad uvs = offset * normalizer * uv_union;

AddSubpass(subpass_size, snapshot.texture, vertices, uvs);
```

**Comment by gaaclarke** [comment]
The above assumptions aren't correct, the snapshots in local space are not axis-aligned.

When looking at `Snapshot::GetUVTransform` we can see that the matrix I'm setting on the snapshot is actually being interpreted as UV coordinates.  So that means that even though our texture sizes are suboptimal, we can probably implement the clip by just tweaking that transform.  I had thought that transform was being interpreted as an entity transform.

**Comment by gaaclarke** [comment]
I also misspoke, the patch in https://github.com/flutter/flutter/issues/139165#issuecomment-1830988554 does fix this issue and the golden image test.  It does not render correctly though in all cases since it can result in UV's outside of 0..1.  A seemingly simple fix would be to clamp the uvs to 0..1 and adjust the vertices accordingly.  It's not as clear as the solution I was proposing in the code above but could get let us live to fight another day.

**Comment by gaaclarke** [comment]
I'm getting closer to a solution here.  We need to incorporate the padding into the GetSnapshot's `coverage_limit`.  That will give us a larger texture to work with that includes the padding we want, full of actual content.  However there is a caveat where the coverage of the result of `GetSnapshot` may vary from what is actually requested.  So, that needs to be accounted for in the downsample pass.

For example, you may be asking for a snapshot that incorporates the halo blur gutter, but we'll get a texture that is more cropped to  what is rendered:
<img src="https://github.com/flutter/flutter/assets/30870216/09bef9aa-235d-4178-946d-58e6d891527e" width=300><img>

That means we need to recreate that halo blur gutter on the top and left side of that texture in the downsampling phase.  The most simple first step would be to add the halo blur on all sides and ignore the calculation to figure out which side actually needs it.

Complicating this a bit is the fact that the coverage limit passed into the filter may be way off from what the coverage we actually get from the snapshot.  So, if you incorporate the blur halo into the coverage limit and work from that, you'll end up with suboptimal performance.  It's best to throw away that calculation and recalculate the blur halo based off of the snapshot result.

The result of the downsample pass should look like this, taking the above cropped texture as input.  Notice the halo gutter around everything we want to blur.
<img src="https://github.com/flutter/flutter/assets/30870216/a2e87d60-6c07-480a-9495-d0ff4cef8005" width=300><img>

**Comment by jonahwilliams** [comment]
Assigning this to @gaaclarke based on my understanding that you are working on it.

**Comment by gaaclarke** [comment]
I've looked at this a bit more.  So the `Snapshot` transform from the blur is correct.  If you take the `Snapshot`s from the gaussian blur's output it has the coverage we'd expect that is slightly offscreen.  I've recreated the issue in a unit test so I can see it clearly.  I can also verify that the texture being generated is how I'd expect it.

Here I've fixed the downsampler to 2.0.  This is the result of the last blur phase.  Notice that the texture in fact has buffer inside of it.
<img width="634" alt="Screenshot 2023-12-04 at 5 05 39 PM" src="https://github.com/flutter/flutter/assets/30870216/d7d56a34-e7be-4ecd-9b07-6a2ac19ae665">

Later it gets rendered squished down to 2048 outside of the gaussian blur in an unnamed Texture Fill step:
<img width="1898" alt="Screenshot 2023-12-04 at 5 09 14 PM" src="https://github.com/flutter/flutter/assets/30870216/397676b4-2ab4-450a-b102-0b6be0d9152a">

It's possible that even if this rendered in the correct space that there would still be the gap.  I'm not sure if the gap is the result of my texture getting swished down to fit on the screen, or if it's from clamping.  See, in my implementation the gutter is requested in the clip coverage hint, and also as a transparent gutter added to the downsample phase.  If we asked for extra clip coverage area and there was none you'll get transparency.  The cap could be just sampling from there.

This is how the fix above works by expanding uvs up instead of scaling vertices down to create the transparent gutter.  The fix above can create rendering flaws in interactive tests.  I'm not 100% certain those flaws can't manifest in production.  I think the rendering is different enough that it may not be a problem.

Here are some potential paths forwards:
1) Just use the fix above and ignore the artifacts in tests
2) Use the fix above but find a way to clamp the texture coordinates to 0..1 by moving the vertices around -- I looked into this in the past and it was a bit hard to do because of the use of different normalized coordinates.
3) Use the fix above but find some way to clip out samples outside of 0..1 in the first blur pass?

**Comment by gaaclarke** [comment]
I wrote the following test which seems to prove that the problem isn't squishing of my rect that's off the screen, it's sampling transparency from off the screen.  The following test shimmers a lot so it's hard to see but as the sigma increases the gap appears and signal from Boston appears to be in the same place.  It doesn't seem to be getting squished (it's hard to tell with the blur).

```c++
TEST_P(AiksTest, GaussianBlurAtPeripheryHorizontal) {
  auto callback = [&](AiksContext& renderer) -> std::optional<Picture> {
    Canvas canvas;

    canvas.Scale(GetContentScale());
    std::shared_ptr<Texture> boston = CreateTextureForFixture("boston.jpg");
    canvas.DrawImageRect(
        std::make_shared<Image>(boston),
        Rect::MakeXYWH(0, 0, boston->GetSize().width, boston->GetSize().height),
        Rect::MakeLTRB(0, 0, GetWindowSize().width, 100), Paint{});
    canvas.DrawImageRect(
        std::make_shared<Image>(boston),
        Rect::MakeXYWH(0, 0, boston->GetSize().width, boston->GetSize().height),
        Rect::MakeLTRB(0, 110, GetWindowSize().width, 210), Paint{});
    canvas.ClipRect(Rect::MakeLTRB(0, 50, GetWindowSize().width, 150));
    static int64_t i = 0;
    Scalar sigma = sin(i++ * 2.0 * 3.1415 * 0.1 / 60.0) * 10.0 + 10;
    canvas.SaveLayer({.blend_mode = BlendMode::kSource}, std::nullopt,
                     ImageFilter::MakeBlur(Sigma(sigma), Sigma(sigma),
                                           FilterContents::BlurStyle::kNormal,
                                           Entity::TileMode::kClamp));
    canvas.Restore();
    return canvas.EndRecordingAsPicture();
  };
  ASSERT_TRUE(OpenPlaygroundHere(callback));
}
```

**Comment by gaaclarke** [comment]
Here is a drawing of where the gap comes from:
![723491165 764328](https://github.com/flutter/flutter/assets/30870216/54d4f101-8de9-42f8-83e5-a4c28926c528)

**Comment by gaaclarke** [comment]
The solution at https://github.com/flutter/flutter/issues/139165#issuecomment-1830988554 works because at step 5 we get clamping. 
![IMG_6762](https://github.com/flutter/flutter/assets/30870216/ac756460-f294-4882-913b-028df95ac890)

This will not work however if the snapshot is completely flush with expanded clip region.

**Comment by gaaclarke** [comment]
So for the 3 tests listed, here's what the downsampled texture output should look like:

![IMG_6764](https://github.com/flutter/flutter/assets/30870216/8c96a0fb-9544-4894-8eeb-9ec8aef0ee3e)

1) In this test the snapshot is flush with the limits being drawn.  The downsample stage creates a transparent gutter which gets drawn to the screen.
2) In this test we are clipping a drawn shape, but we are hitting the top left bounds of that image.  So in the right and down directions we expand the input so that the snapshot has more content to sample from.  In the top left we have clamped content that will just get cropped out in the final draw.  Today I believe this isn't working correctly since we will be sampling from transparency in the up and left directions instead of clamping.
3) Here we expand the snapshot and get content in the up and down direction, but we are hitting the boundaries of the image we are filtering.  Today we are sampling from transparency, here you'll see we need the edges to be clamped.

Here are what they look like today, the 1 case is omitted because it is generating what we want:
![IMG_6765](https://github.com/flutter/flutter/assets/30870216/ace536b0-130a-4133-9348-f79318b22482)

**Comment by bdero** [comment]
I'll try to reframe the approach in order to reveal the unaddressed pieces.

It's important to note that with the approach you're taking, hardware sampling is out the window after this first downsample pass. We can no longer reliably use the tiling configuration to sample from the original, intact texture -- and that's fine.

What you're effectively doing is creating a texture that contains all of the information we'll need to sample from by baking in the tiling upfront.

Say we start with this checkerboard texture:

![47559826dddc237a0cd4bccf0798273c_gpu](https://github.com/flutter/flutter/assets/919017/5bc59ba6-6ab0-4414-a29d-90ad506fb9d3)

Drawn with the kDecal tiling mode, it's supposed to look like this:

![d95c76168defaa7b41c1c45a1432215d_gpu](https://github.com/flutter/flutter/assets/919017/eff3f24e-c136-47a2-a1a3-57177d220d30)

This is what the kMirror tiling mode is supposed to look like (kClamp happens to render exactly the same in this case due to the nature of the texture):

![d98e41a89862c424ecbfb3121223a7c7_gpu](https://github.com/flutter/flutter/assets/919017/147d601a-2a96-490b-9600-5a14d205b424)

So the whole halo actually gets filled in with solid blurred content for all of the non-decal tile modes. Now check out what happens when increasing the blur sigma a little bit here:

![bf3a0b90c9f4f6ae17ad3a4b2ce60e3f_gpu](https://github.com/flutter/flutter/assets/919017/5932c205-954c-46cd-8a7b-140cffe700f3)

The sampler works consistently near the border of the expanded "halo". You can see the edges of the next color transition bleeding in because the blur is sampling content "outside" the original expanded "halo" area in accordance with the tiling mode.

So if we apply the tiling mode during the downsample pass, we actually need to double-expand the sampling area in all directions to account for this, baking in all the information we'll need. Once for the "halo", and again so that we can properly sample the halo's edges during the blur passes (technically this is only necessary if the tiling mode is not kDecal).

![image](https://github.com/flutter/flutter/assets/919017/7a1611cc-4f4f-4696-b271-5d117277c7f3)

- The inner ring ("Halo" area) is the area that the filter's returned Entity should draw to the parent pass once the blurred texture is produced.
- The outer ring (Outer halo sampling area), which is both expansions combined, is the safe size to use for all three subpasses, allowing for reuse of the render target texture between the downsample pass (first pass of the filter) and second directional blur pass (third pass of the filter).

## Example walkthrough

So first, grab the filter's Entity and separate the transform into two different matrices: One for scale and another containing everything else.

When getting the snapshot, pass in the scale-only transform. Don't worry about passing in a coverage hint right now. Passing the coverage hint when taking a snapshot is a no-op for our trouble cases like backdrop blurs.

Compute the inner and outer expansion rings as mentioned above.

![image](https://github.com/flutter/flutter/assets/919017/c1014d3a-2a5e-4b6d-a71d-dd333fb9b21d)

Project the UV space of the original texture as the inner square of the render target. The top/left coordinates should be less than zero and the bottom/right coordinates should be greater than one. This is where we apply the filter's TileMode. In this case, I'm using kMirror for clarity of the example.

![image](https://github.com/flutter/flutter/assets/919017/8f194beb-bbcf-480c-ac31-9eb76500e6f8)

Not to scale, of course. :^)

Now, create a second texture of the same size. Line up the UVs 1-1 and perform the horizontal blur pass. To optimize, we can actually avoid rendering the vertical edges in the outer ring, because we don't need to sample from them during the second pass.

The tiling mode does not matter for the blur passes. No sampling needs to be done outside the confines of the input texture for either of the blur passes.

![image](https://github.com/flutter/flutter/assets/919017/84f0f525-5117-4b88-8b72-93fee0a7eed6)

Reuse the downsample texture to perform the vertical pass. Similar to the first directional blur pass, we can avoid rendering the horizontal portions of the outer ring area.

![image](https://github.com/flutter/flutter/assets/919017/8b39a655-9813-4af6-a403-4063f2d51973)

For the returned blur Entity, create a new TiledTextureContents: Set the source rect to the "halo" area/inner ring rectangle. Scale the Entity's transform up to account for the downscale and apply the non-scale parts of the original transform of the Entity passed into the blur.

![image](https://github.com/flutter/flutter/assets/919017/a7d7cfc9-fb4f-404e-b5c9-064ecb58a5f1)

## Coverage hint

So what about applying the coverage hint?

Well, this is easy to just tack on after everything else is working. The coverage hint is in the EntityPass/screen space, so we first need to convert it to the same space we're using throughout the blur above by removing the non-scale aspects of the original entity transform.

```cpp
// This is the conservative bounding box of the coverage hint in the more local space we're
// operating in throughout the blur.
auto local_coverage_hint = coverage_hint.TransformBounds(everything_else_transform.Invert());
```

Then, simply intersect the local coverage hint with the original texture area.

![image](https://github.com/flutter/flutter/assets/919017/c9be91df-212e-406f-8f0f-dacbd5f81662)

This is the new inner source rectangle. Compute the expanded halo rect and outer sampling rect based on this new rectangle and let everything else play out in exactly the same way as described in the example walkthrough above.

![image](https://github.com/flutter/flutter/assets/919017/e84475b8-cb86-4846-8e12-4324ffc29b7f)
