### ISSUE TITLE
My Google map Showing blank Screen on IOS

### ISSUE THREAD

**Issue by RahimUllahAxlic** [flutter/flutter#139283]
I am working with Google Maps, it's working fine in Android but only blank screen in iOS. 
![WhatsApp Image 2023-11-29 at 23 21 52_4955e9c3](https://github.com/flutter/flutter/assets/149462629/89706e49-5e77-428d-8e91-207c4df256a9)
<img width="295" alt="map" src="https://github.com/flutter/flutter/assets/149462629/061eb28c-f471-49cf-854b-34d73074dd9e">
<img width="261" alt="pub" src="https://github.com/flutter/flutter/assets/149462629/bee6052c-d204-4274-915a-298b41fded5a">

**Comment by huycozy** [comment]
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug Flutter's first-party packages issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)). 

Please provide the crash log in text format instead of a screenshot for better readability as well.
