### ISSUE TITLE
can not render flutter page on ios 17

### ISSUE THREAD

**Issue by belin11** [flutter/flutter#139220]
The ios project integrates flutter with pod. flutter white screen on ios17, how do I fix this problem

**Comment by darshankawar** [comment]
@belin11 
When opening an issue, please try to use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) and fill out requested details so that we'll have enough info to work with.
So for now, please provide us a minimal reproducible code sample or a sample repo that we can clone along with `flutter doctor -v` and any error log you see when you get a white screen, so that we can properly address the reported behavior.

**Comment by darshankawar** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/139229
