### ISSUE TITLE
Beta release 3.17.0-0.1.pre wrong tagging

### ISSUE THREAD

**Issue by Jasguerrero** [flutter/flutter#139311]
After releasing 3.17.0-0.1.pre beta, despite putting the new tag as 0.1.pre in the sdk archive it shows as 3.17.0-0.0.pre and now we have 2 betas with the same tag.

The issue appears to be today's tagging step instead of tagging at the HEAD, tagged at the base commit before branching which was https://github.com/flutter/flutter/commit/0b591f2c82e9f59276ed68c7d4cbd63196f7c865. Packaging seems to have done the right thing which is get the first tag for that commit.

**Comment by CaseyHillers** [comment]
The culprit builder is https://luci-milo.appspot.com/ui/p/dart-internal/builders/flutter/Linux%20flutter_release/51/overview

The interesting aspect is the parameters for tagging appear to be correct:

```
  RELEASE_CHANNEL: beta
  REL_HASH: 12b47270b7a705f4dc7fe7a899acc2f7b5fdb63b
```

```
##### TAGGING #####
fatal: tag '3.17.0-0.1.pre' already exists
Everything up-to-date
```

It looks like we wanted to ship `3.17.0-0.2.pre` instead of `.1`. The larger bug is it shipped the entire Flutter RC branch to beta instead of the tagged part.

I sent https://flutter-review.googlesource.com/c/recipes/+/52800 which should fix the issue. This should have stopped the release at the failed tagging command.
