### ISSUE TITLE
Add neutral Material themes

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#139338]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Often times, developers use Material widgets as a starting point for creating their own UI library that follows a custom design system. This means they turn off things like inkwell splashes, indicator colors, tints, etc. We should create a neutral Material theme that developers can use when trying to build their own custom design systems. 

We can also create one specific to iOS - making widgets look like default iOS themes. This requires a bit of investigation to come up with the theme property values and make a decision on how many "neutral" or iOS themes there should be. 

### Proposal

Ideally we use the Material demo to play around with theme properties until we get the best theme for different use cases. This requires some work on the Material demo, as mentioned here: https://github.com/flutter/flutter/issues/138274

**Comment by navaronbracke** [comment]
I think this is also in relation to the recent switch to the Material 3 default.

In the application mentioned above (deriving custom widgets from Material ones), if you switch to Material 3 as the default,
you might see subtle differences if you left theming at the defaults. For example, the Material Switch or the background color of bottom sheets.

Having a neutral theme could be an alternative when `useMaterial3: false` is no longer an option, due to the flag being removed from the framework.

**Comment by bernaferrari** [comment]
Someone should make Radix for Flutter. I'm going to make it (but might take a while). I still wish it were native.

**Comment by britannio** [comment]
Is this design doc relevant?
https://flutter.dev/go/blankcanvas

**Comment by Ehesp** [comment]
An alternative to Radix for more inspiration: https://react-spectrum.adobe.com/react-aria/index.html

**Comment by bernaferrari** [comment]
A few more alternatives:
My favorite UI framework is shadcn/ui: https://ui.shadcn.com/docs/components/card
This website is very good at theming: https://www.skeleton.dev/
This is very nice how bold and playful it is: https://melt-ui.com/

But personally, nothing wins Radix website/documentation + Radix components, and it has been winning 2023. A lot of libraries are using it as the base.

**Comment by mateusfccp** [comment]
I personally disagree with the idea. The problem, in general, exists, but instead of making a "neutral" Material, we should decouple completely from Material.

Blank Canvas is a good idea and IMO should be part of the core Flutter, while Material and Cupertino should be separated into packages built upon Blank Canvas.

**Comment by benthillerkus** [comment]
Mateus is, right - Material is supposed to be Material Design. Shoehorning in some more options will not help anyone trying to make custom UI, while at the same time adding more (maintenance) burden to the behemoth that Material already is.
Material should be a showcase for a good Flutter ui library, meant for developers who want to build native feeling Android apps, not a kitchen sink failing to please anyone

**Comment by ivangalkindeveloper** [comment]
It seems to me that developers should create their own theming classes, based on which they understand what color contract is involved in the application
This is also useful, since the developer ultimately owns polymorphism over this theme object

If the idea is to have one theme contract on top that already delegates its properties to material and Cupertino (so as not to write everything separately), then the idea is good

I long ago made the following theme contract for my package of platform components:
https://github.com/ivangalkindeveloper/flutter_platform_component/blob/master/lib/src/core/domain/entity/theme/fpc_theme.dart

**Comment by rydmike** [comment]
This is a very interesting proposal. I also see an opportunity to combine it with 
* https://github.com/flutter/flutter/issues/143499   

Which in its [design document](https://docs.google.com/document/d/1REsg982YG2MlspsMOiNLpu8OIWkyehRRQUXHMU3tAAM/edit) introduces `LegacyThemeData` as a package called `legacy_material`. In the design doc a question is also raised about how it should work when eventually M3 is replaced with M4?

I think the design could also consider such future need, as well as the above proposal. It could thus in its design include the possibility to add more designs than just one legacy version. Maybe also consider naming it `TemplateThemeData` and e.g. `template_material` package.

We could then add as many different template material styles to the package as needed. Some examples:

* `TemplateThemeData.m2` - Legacy M2 themed Material Design widgets.
* `TemplateThemeData.neutral` - Neutral platform agnostic themed Material Design widgets.
* `TemplateThemeData.iOS` - iOS like themed Material Design Widgets.
 
The idea of the `TemplateThemeData.iOS` would **not** be to make Material widgets work and look exactly like the high fidelity Cupertino widgets, only to make them fit better design wise, out of the box, on the iOS platform. They are often used by Flutter devs on iOS and have to be styled to fit better. For full fidelity you would still need to use Cupertino or platform adaptive widgets. But even if you use Cupertino, if and when you include some Material widgets, they fit better.

One could also argue that `neutral`, could be designed to fit on iOS already. The Apple HIG is pretty neutral. The proposal above does not yet define exactly what the "neutral" spec should be. It could of course "by coincidence" be the border radius and opacity based press/focus/highlight style used on iOS, as it is pretty "neutral" already. However, some might disagree and want an even more "neutral" starting point option.

Another consideration could be to also allow 3rd parties to deliver and maintain theme configurations for `TemplateThemeData`. We could e.g. get things like:

* `TemplateThemeData.windows` - Windows themed Material Design widgets
* `TemplateThemeData.macOS` - macOS themed Material Design widgets
* `TemplateThemeData.shadcn` - [Shadcn](https://ui.shadcn.com/) themed Material Design widgets

Again, those themes would not be high-fidelity platform designs, like e.g. packages [fluent_ui](https://pub.dev/packages/fluent_ui) and [macos_ui](https://pub.dev/packages/macos_ui). They would only be intended to make Material widgets look less alien when used on mentioned platforms or together with other 3rd party designed widgets, like the mentioned packages.
  
Since all this is just `ThemeData` we can also easily use these themes to let multi-platform Flutter apps get platform adaptive `ThemeData`. Only check platform and setup the correct `TemplateThemeData` for the platform. It will not be exact platform components, but the app would look much more at home on each platform, with minimal effort. Once reasonable themes for all platforms exists, a convenience `TemplateThemeData.adaptive` constructor could also be added.

I have already used this platform adaptive theme design idea manually, and to some extent also via my package [flex_color_scheme](https://pub.dev/packages/flex_color_scheme) that offers some platform adaptive theme styling options out of the box. 

It works well and helps with removing things from Material Design widgets (especially M3 defaults, that is very opinionated) that look very out of place on none Android platforms. It is not perfect, but it really can make your app look more at home on other platforms. Plus you  get all this with no effort needed on Material widget styling and custom widget wrapper or platform adaptive widgets. It is all done via theming, yes I kind of like that 😄 

And of course later, when someday M4 arrives, and M3 becomes obsolete we can add:

* `TemplateThemeData.m3` - Legacy M3 themed Material Design widgets.

Anyway, this was just some rough ideas around this concept 😄 💙 

Thoughts?

**Comment by QuncCccccc** [comment]
I'm closing this because #144273 and https://github.com/flutter/flutter/pull/144805 have landed to support neutral themes. A neutral theme can be created by:

```dart
ColorScheme.fromSeed(
  colorSeed: // Any seed color,
  dynamicSchemeVariant: DynamicSchemeVariant.monochrome,
)
```
or 
```dart
ColorScheme.fromSeed(
  colorSeed: // a black or white color,
  dynamicSchemeVariant: DynamicSchemeVariant.fidelity, // or DynamicSchemeVariant.content
)
```

**Comment by rydmike** [comment]
@QuncCccccc if you check the proposal you can see that this issue had a much broader intent than just getting less tinted surface and less pastel like color schemes, which is all the referenced PRs really addresses.

But I did not create the issue and have a package that allows users to do things asked for here, so I am OK with not going deeper into this. I just wanted to highlight that most customers that had big expectations from this issue might be disappointed by this not moving forward and actually delivering on the original intent.
