### ISSUE TITLE
[in_app_purchase] Android purchases not sent to Google Analytics

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#139628]
I have Google Analytics on my project, and every event is collected normally, included in app purchases coming from iOS. But there is 0 trace of the in app purchases made on Android ; what can I do to understand what's wrong ?

**Comment by darshankawar** [comment]
@TheCarpetMerchant 
I think it sounds more like an issue with GA rather than with Flutter. You can reach out using below links for further resolution:

[GA4 - Filter Events](https://support.google.com/analytics/answer/10104470?hl=en)

[Analytics Academy](https://analytics.google.com/analytics/academy/)

reference: https://stackoverflow.com/a/74763148

**Comment by darshankawar** [comment]
@TheCarpetMerchant I am not sure. If the data is being sent to GA but somehow it is not being received there, could be related to server side. Do you already have specific filters in place or could be related to the Google play account you have that you can check ?

**Comment by darshankawar** [comment]
Thanks for the update. Can you try the plugin example and check if using it you still get the same behavior or not ?
