### ISSUE TITLE
ios obfuscation is not working?

### ISSUE THREAD

**Issue by makinghappen** [flutter/flutter#139793]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try building an IOS package with obfuscation:
1. flutter build ipa  --obfuscate --split-debug-info=./build/split-debug-info

### Expected results

I expect that 
Flutter/flutter_export_environment.sh

would contain a line enabling obfuscation:
export "DART_OBFUSCATION=true"

### Actual results

But actually it does not:

#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/user/flutterapp"
export "FLUTTER_APPLICATION_PATH=/Users/user/flutterapp"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.dart_tool/package_config.json"

### Code sample

n/a

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.3, on macOS 13.6.1 22G313 darwin-arm64, locale
    en-US)
    ! The flutter binary is not on your path. Consider adding
      /Users/user244775/Documents/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding
      /Users/user244775/Documents/flutter/bin to your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories
```

</details>

**Comment by makinghappen** [comment]
@darshankawar no, it didn't help, also variables from --dart-define and --dart-define-from-file are not added to  Flutter/flutter_export_environment.sh and Flutter/Generated.xcconfig

**Comment by darshankawar** [comment]
@makinghappen 
After running the command you provided, if you go to `ios/Flutter/Generated.xcconfig`, does it show the flag as true ?

**Comment by makinghappen** [comment]
@darshankawar no, DART_OBFUSCATION=false

**Comment by darshankawar** [comment]
Thanks for the update @makinghappen 
I also see the same flag, ie, `false` for `DART_OBFUSCATION`, but I think this would be WAI (working as intended).

<img width="415" alt="Screenshot 2024-01-03 at 11 17 36 AM" src="https://github.com/flutter/flutter/assets/67046386/f4ab8919-f26e-4cb5-bdff-b2b76aae2cac">


> expect that Flutter/flutter_export_environment.sh
> 
> would contain a line enabling obfuscation: export "DART_OBFUSCATION=true"

I haven't seen any prior issue claiming that it should be `true` so I would like to know about your claim that it should be true because I can't find any documentation around the flag claiming it should be true.

**Comment by makinghappen** [comment]
@darshankawar because for android it is set to true, so I assume this variable sets if dart code is obfuscated or not

**Comment by darshankawar** [comment]
Thanks for the update @makinghappen 
I cross-verified with my colleague and he was able to see the expected behavior, ie, the flag is shown as true upon running the original command you mentioned, ie:

`ios/Flutter/Generated.xcconfig` file and `flutter_export_environment.sh` also contained export `"DART_OBFUSCATION=true"`

Maybe you can run the command in verbose mode and see if it gives any clue on why the flag might be showing up as false at your end.

**Comment by darshankawar** [comment]
The same version as you were on, 3.16.3
