### ISSUE TITLE
> Hi @mz-myfc Your expected result is reversed, please update it.

### ISSUE THREAD

**Issue by lalayiersan** [flutter/flutter#139888]
> Hi @mz-myfc Your expected result is reversed, please update it.
> 
> I checked this issue on my device `Realme 6, Android 11` and saw the obscureText TextField still can get focus with only one tap/click. What is your device (OS, model)? Could you provide a recorded video for this?

Thanks for the reply. I have tried other phones without this problem. It is a problem with my device. My device is vivox50.

_Originally posted by @mz-myfc in https://github.com/flutter/flutter/issues/137830#issuecomment-1794190525_

**Comment by huycozy** [comment]
Hi @lalayiersan,
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since there is not enough information to verify. Once you updated the issue with more information, please write in the comments and I will re-open this for further investigation. Thanks!
