### ISSUE TITLE
Flutter Web  And HTML 5

### ISSUE THREAD

**Issue by CooolWolf** [flutter/flutter#140023]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am currently using a comprehensive framework, one set of HTML5 code, one set of flutter web code, I want to take the data in HTML5, such as maybe a js object, can I pass it to my flutter web, how should I pass it, how should I receive it? I have read that there is officially a dart: js, but I was wondering if they support data communication between them

### Proposal

I am currently using a comprehensive framework, one set of HTML5 code, one set of flutter web code, I want to take the data in HTML5, such as maybe a js object, can I pass it to my flutter web, how should I pass it, how should I receive it? I have read that there is officially a dart: js, but I was wondering if they support data communication between them

**Comment by CooolWolf** [comment]
what should i do

**Comment by dam-ease** [comment]
Hi @CooolWolf.
Can you check out https://liewjuntung.medium.com/use-javascript-in-flutter-web-a6eed3efb9a0 to see if it helps?

**Comment by CooolWolf** [comment]
> Hi @CooolWolf. Can you check out https://liewjuntung.medium.com/use-javascript-in-flutter-web-a6eed3efb9a0 to see if it helps?

I know this approach, but what worries me more is, how should my flutter web project be integrated into H5, like npm way? flutter web bundling as a native file? Or another way, currently I start two web services, one H5, one Flutter web, and then I import Flutter web from H5 via iframe, which is essentially two services, can they become one service, or can I make H5 depend on my Flutter Web

**Comment by dam-ease** [comment]
Thanks for your response.

It seems your question is best suited for support channels like StackOverflow, please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources as well and asking questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Thank you!
