### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by donuthappy** [flutter/flutter#140158]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter web release mode issue

Occurs sometimes when I use beamer package.

### Expected results

If user click the button, modal should be opened.

### Actual results

If user click the button at first, modal should not be opened.
after the first, modal can open the modal.

### Code sample

context.beamToNamed('/home/search', popToNamed: '/home');

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at main.dart.js_70.part.js:264:3

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

**Comment by huycozy** [comment]
Hi @donuthappy 
If the issue only occurs when using beamer package, please open issue on [its repository](https://github.com/slovnicki/beamer) for better support. 

In case you think this is a Flutter framework issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code along with `Steps to reproduce` so that we may verify this. Thank you!
