### ISSUE TITLE
Why do I not see the first word when I enter Chinese into a textfield on iPadOS?

### ISSUE THREAD

**Issue by axplus** [flutter/flutter#140150]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. place any kind of textfield in ui
2. run in ipados
3. type chinese

### Expected results

the first candidate  is visible

### Actual results

i cannot see the first candidate.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<img width="966" alt="image" src="https://github.com/flutter/flutter/assets/1296434/958b65d6-878f-465b-82a0-af9de1474638">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @axplus 
I tried [this](https://docs.flutter.dev/cookbook/forms/text-input?gclid=Cj0KCQiA7OqrBhD9ARIsAK3UXh2q1FsQnWBVT5HUNqDex8zeMnLvPwJbhI_WbbmokT-8pu76s40d5d8aAlFXEALw_wcB&gclsrc=aw.ds#interactive-example) code sample on iPad simulator as shown below which shows the first candidate properly.

<img width="431" alt="Screenshot 2023-12-15 at 11 31 10 AM" src="https://github.com/flutter/flutter/assets/67046386/ef3cfad6-3a41-4681-9f3f-f8d05a6841df">


If above doesn't represent the case you are reporting, please provide more details like flutter doctor -v, and exact steps to replicate so that we can properly address the issue.
I verified above on latest master.

**Comment by axplus** [comment]
Sorry for my negligence, the issue appeared in the latest iOS 17 version.
it ok in ios 15.2
<img width="779" alt="image" src="https://github.com/flutter/flutter/assets/1296434/c7603bb9-1f97-4df5-9639-02ac686c8833">

but bug in ios 17
<img width="938" alt="image" src="https://github.com/flutter/flutter/assets/1296434/f202cb51-7c91-4575-9594-0dc88ade7653">

**Comment by darshankawar** [comment]
Thanks for the update. What flutter version are you on which shows this behavior ?
Can you try on latest master and confirm if this persists ?

**Comment by axplus** [comment]
@darshankawar  


Thanks a lot! it's fine in the master channel.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.18.0-11.0.pre.96, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
```

But still bugs in stable channel:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
```




Hopefully this patch will be released to the stable channel soon. Or is there any way to add this patch mansually?

**Comment by darshankawar** [comment]
Good to know. The fix should roll out in next stable release. I'll close this since it is working as expected on master.
