### ISSUE TITLE
[web]: Is there a way to run flutter PWA's locally? 

### ISSUE THREAD

**Issue by sdkdeepa** [flutter/flutter#140126]
Without building the flutter web app how can I make sure I can run light house report for a flutter web app locally. Do I have to always build and host it to make it as a PWA. 

Is there a 3rd party package? or any package that flutter provides for this.

**Comment by huycozy** [comment]
Hi @sdkdeepa 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this. 

Closing from here as this is more of a `how-to` question rather than a bug or feature request.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
