### ISSUE TITLE
Flutter FFMPEG support for windows desktop

### ISSUE THREAD

**Issue by ctippur** [flutter/flutter#140305]
### Use case

Use Case 
Looking to stream video from Serial port on a Windows desktop and display the stream on a screen. The source of the video is a UVC camera.
I was hoping to use FFMPEG library to capture the video stream. Looks like this library has been deprecated.

### Proposal

I am looking for alternatives to achieve the same outcome.

Looking forward to a swift response.

Shekar

**Comment by dam-ease** [comment]
Thanks for filing this @ctippur 

> I was hoping to use FFMPEG library to capture the video stream. Looks like this library has been deprecated.

Which library are you referring to here?

I see https://pub.dev/packages/ffmpeg_kit_flutter only Android, iOS and macos but this is a third party package and proposals and issues related to this package should be filed https://github.com/arthenica/ffmpeg-kit/issues/

Also, there is a similar proposal there https://github.com/arthenica/ffmpeg-kit/issues/855, you might want to comment, upvote and follow up on this for updates.

Questions like these are also best suited for support channels like StackOverflow,  please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.
Closing from here as this is more of a how-to question rather than a bug or feature request.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
