### ISSUE TITLE
I have issue related Dropdown Menu Flutter Windows Application.

### ISSUE THREAD

**Issue by mrparthpatelz** [flutter/flutter#140374]
I have facing an issue that when I press tab on dropdown menu it is selecting menu entries in background without opening dropdown menu how can I stop it?

**Comment by dam-ease** [comment]
Hi @mrparthpatelz 

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
