### ISSUE TITLE
Bug with centerSlice on impeller

### ISSUE THREAD

**Issue by soyangel** [flutter/flutter#140393]
### Steps to reproduce

Using centerSlice with impeller shows different result compared to Skia (tested on Android).

```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (hace 8 días) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

Use this asset for the example (button_bg.png):

![button_bg](https://github.com/flutter/flutter/assets/95073/dee383ce-bf80-4fa0-a406-1b52101d8194)

### Expected results

Got this result without impeller on Android (flutter run --release)

<img src="https://github.com/flutter/flutter/assets/95073/f466e352-eeb8-4051-8f6a-061c4d6dd949" width="300"/>

### Actual results

Got this result with impeller enabled on Android (flutter run --release --enable-impeller)

<img src="https://github.com/flutter/flutter/assets/95073/a2fb1392-8b32-4733-ace9-f572b08e58cc" width="300"/>

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: Colors.black,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 180,
          height: 70,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: AssetImage('assets/button_bg.png'),
              centerSlice: Rect.fromLTWH(14, 14, 1, 1),
              fit: BoxFit.fill,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.4, on Ubuntu 23.10 6.5.0-14-generic, locale es_ES.UTF-8)
    • Flutter version 3.16.4 on channel stable at /home/angel/flutter/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (hace 8 días), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/angel/android/soft/sdk/
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /home/angel/android/soft/sdk/
    • ANDROID_SDK_ROOT = /home/angel/android/soft/sdk/
    • Java binary at: /home/angel/android/soft/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/angel/android/soft/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Pixel 7a (mobile) • 2C081JEHN04046 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)   • linux          • linux-x64      • Ubuntu 23.10 6.5.0-14-generic
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample provided above. 

This reproduces with impeller on both android and iOS but not with skia. 

<details>
<summary>screenshots</summary>

### iOS

| impeller | skia | 
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/88313112/4c368969-d31c-4fb6-b397-e3dec9a66af2" width="300"/> | <img src="https://github.com/flutter/flutter/assets/88313112/312c24d2-6ce8-4c38-bb91-b63b0b0fb02f" width="300"/> |

### Android

| impeller | skia | 
| -- | -- |
<img src="https://github.com/flutter/flutter/assets/88313112/4258d22f-448a-43cf-b230-c3a5677e4a83" width="300"/> | <img src="https://github.com/flutter/flutter/assets/88313112/db0f9faa-e1d0-45f6-9574-44a3f0294963" width="300"/> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.4 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (8 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2 21C62
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.18.0-14.0.pre.31, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-14.0.pre.31 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62d699961f (4 hours ago), 2023-12-19 20:59:27 -0800
    • Engine revision c70f0a495a
    • Dart version 3.3.0 (build 3.3.0-244.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2 21C62
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jonahwilliams** [comment]
This might be a problem with how we compute the nine-patch coordinates in Impeller. This is handled here:

https://github.com/flutter/engine/blob/main/impeller/display_list/nine_patch_converter.h

**Comment by jason-simmons** [comment]
I was able to get this to render correctly by:
* removing the `Expand(0.5)` applied to the `texture_coords` in `TextureContents::Render`
* changing the `min_filter`/`mag_filter` to `kNearest` instead of `kLinear`

The patch coordinates computed by `NinePatchConverter::DrawNinePatch` appear to be correct.

But in this image some of the patches have source rectangles with a width or height of one pixel.  The `TextureContents` seems to be sampling outside that region of the source image when executing the `DrawImageRect`.

**Comment by jason-simmons** [comment]
Skia has `kStrict_SrcRectConstraint` and `kFast_SrcRectConstraint` modes in `SkCanvas::drawImageRect`.  It uses `kStrict_SrcRectConstraint` when calling `drawImageRect` to render parts of a nine-patch image.

Skia's docs say:
```
If kStrict is set, then extra code is used to ensure it never samples
outside of the src-rect. kStrict_SrcRectConstraint disables the use
of mipmaps and anisotropic filtering.
```

Does Impeller need a similar option?

**Comment by bdero** [comment]
The intent of the `Expand(0.5)` is to align the texture coordinates with the geometry correctly. If you draw a rect with RTLB 0,0,2,2, the geometry is such that the top left corner of the geometry is the top left corner of the 0,0 pixel, and the bottom right corner is at the bottom right corner of pixel 2,2.

If you sample from a texture with a texture coordinate of 0,0, you're sampling from the "center" of the top left texel, 0,0. And when you sample with 1,1, you're sampling from the "center" of the bottom right texel 2,2. So in order to align them correctly (so that the "center" of the texels align with the center of the pixels, we need to either shrink the geometry or make the texture coordinates reach half a texel farther (that's what the Expand() does).

One implication of this choice is that, if the sampler is set to kLinear and the TileMode is kDecal, then you'll actually see the texture fade to transparent a bit on the edge. I did this a long long time ago and this may or may not exactly match Skia's behavior.

Reading the description of `kStrict_SrcRectConstraint` pasted above, it sounds like this is how Skia behaves as well for DrawImageRect by with `kFast_SrcRectConstraint`.

Bad solutions:
* Removing `Expand(0.5)` will result in issues with kLinear. When the source/destination rects are well aligned with the pixel grid, images will appear to become slightly blurry as they get closer to the edges of the rect. If you have a tiny image that's extremely zoomed in, images will appear much more stretched out than they should be as the area of the edge texels become more significant.
* Shrink the geometry with `Expand(-0.5)` instead. If zooming into the tiles, this will cause visible gaps in-between the tiles to appear.

So when drawing from a packed atlas with no spacing between tiles, we need a solution that works well with linear sampling and:
1. Doesn't smear.
2. Doesn't create gaps between the tiles.

What I would recommend is basically adding the `kStrict_SrcRectConstraint` mode. This can be done with a new version of the shader that clamps the texture coordinates to the source rect in UV space to prevent adjacent pixels from bleeding in on the edges (basically, we emulate clamp sampling). So the way we compute texture coordinates/geometry remains exactly the same, but we bind a new uniform rect that's used to clamp the texture coordinates before we sample from the texture in the shader.

The UV limit can just be bound as a uniform vec4. Computing it is the same as the texture coordinates, except without the `Expand(0.5)`:
```cpp
Rect::MakeSize(texture_->GetSize())
          .Project(capture.AddRect("Source rect", source_rect_)
```

All of the same issues with kLinear apply for DrawAtlas as well, by the way. But solving it there is a bit more annoying since everything is done as one draw call (as it should be -- and so should DrawAtlasNine eventually), but we can get it done should it come up.

**Comment by bdero** [comment]
It turns out I got the spaces backwards again -- 0, 0 is the center of a pixel in screen space and 0, 0 is in-between texels. So we actually need the Expand(-0.5) for the clamp rect and no expansion for the normal UVs.

I believe the `kStrict_SrcRectConstraint` mode is still necessary for all of the same reasons though.

**Comment by bdero** [comment]
> 0, 0 is the center of a pixel in screen space

Oops, that's wrong too! @flar said he thinks the extents of both spaces map to pixel edges. And then I realized this must be the case...

Specifically, I'm talking about the conversion from normalized device coordinates (LTRB=[-1, 1, 1, -1] in Impeller) to framebuffer/viewport coordinates. Given our current ortho projection, if NDC -1, -1 were mapped to the center of a pixel on the framebuffer, then we'd see integer aligned filled rect edges smearing across pixels with MSAA, which we definitely don't.

My confusion stems from a [d3d9 doc](https://learn.microsoft.com/en-us/windows/win32/direct3d9/directly-mapping-texels-to-pixels) that I read at some point, not realizing that this is a d3d9-specific quirk.
