### ISSUE TITLE
which use case will generate renderViews

### ISSUE THREAD

**Issue by xcrazy** [flutter/flutter#140361]
void drawFrame() {
    rootPipelineOwner.flushLayout();
    rootPipelineOwner.flushCompositingBits();
    rootPipelineOwner.flushPaint();
    if (sendFramesToEngine) {
      for (final RenderView renderView in renderViews) {
        renderView.compositeFrame(); // this sends the bits to the GPU
      }
      rootPipelineOwner.flushSemantics(); // this sends the semantics to the OS.
      _firstFrameSent = true;
    }
  }

above function(src/rendering/binding.dart,  but I always see there is only one RenderView. I am wondering when and how to generate more renderview inside RenderViews?

**Comment by dam-ease** [comment]
Hi @xcrazy 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change or reporting a bug, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
