### ISSUE TITLE
[Impeller] Rect::Contains has floating point errors

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#140464]
With the following data Rect::Contains returns false:
```
*this
  {...}
  origin:
  {...}
  x:
  472.599945
  y:
  440.999969
  size:
  {...}
  width:
  1102.80005
  height:
  654.000061
o
  0x000000012f8faf30
  origin:
  {...}
  x:
  724
  y:
  618
  size:
  {...}
  width:
  600
  height:
  300
```

Here is why it fails:
```
Union(o).size
  {...}
  width:
  1102.80005
  height:
  654
size
  {...}
  width:
  1102.80005
  height:
  654.000061
```

**Comment by gaaclarke** [comment]
Here is my proposed fix:
```c++
  constexpr bool Contains(const TRect& o) const {
    return o.GetLeft() >= GetLeft() && o.GetTop() >= GetTop() &&
           o.GetRight() <= GetRight() && o.GetBottom() <= GetBottom();
  }
```

**Comment by flar** [comment]
A better fix would be to not use GetL/R/T/B because of their auto-sorting properties and instead calculate the values directly. This will all get fixed in the rework to LTRB fields, but the following would be more correct:

```
return !IsEmpty() && !o.IsEmpty() &&
    o.origin.x >= this->x &&
    o.origin.y >= this->y &&
    o.origin.x + o.size.width <= this->origin.x + this->size.width &&
    o.origin.y + o.size.height <= this->origin.y + this->size.height;
```

As soon as I write some tests that verify that we auto-sort **only** in those specific cases that are intended to be auto-sorting (mainly drawRect/Oval and clipRect), I was going to change all of the Get methods to be non-sorting and so the proposed fix would be correct except for the empty tests.

**Comment by flar** [comment]
You can see the implementation in the now-abandoned PR to add some DL-specific geometry classes here:

https://github.com/flar/engine/blob/f391c31b882278603f42b725b3587fc94dddc0ab/display_list/geometry/dl_rect.h#L553

That branch is abandoned because we decided to instead update the Impeller geometry classes with these details and then to use them as the raw geometry of the DisplayList rather than introduce another geometry package.
