### ISSUE TITLE
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation couldn’t be completed. (CoreMediaErrorDomain error -12865.), null, null)

### ISSUE THREAD

**Issue by sthakrishnakumar** [flutter/flutter#140448]
### Steps to reproduce

Download the chunk files of HLS Video along with .m3u8 file
Then play the .m3u8 file.

### Expected results

Should play the video offline smoothly as it played in android without any issue.

### Actual results

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation couldn’t be completed. (CoreMediaErrorDomain error -12865.), null, null)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

![Screenshot 2023-12-20 at 6 16 08 PM](https://github.com/flutter/flutter/assets/60802660/90cd1623-a6f2-41b7-9c96-461662139cc8)

**Comment by danagbemava-nc** [comment]
Hi @sthakrishnakumar, you are using an older version of flutter kindly upgrade to the latest version of flutter stable (3.16.5) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`. 

Please also provide the version of `video_player` and `video_player_avfoundation` you're using along with a complete minimal reproducible code sample so that we can investigate this. 

Thank you
