### ISSUE TITLE
Phone does not give storage permission on old version of flutter

### ISSUE THREAD

**Issue by oooophelia** [flutter/flutter#140524]
My flutter application has an image selection function. Before Android 13, everything works fine, but on version 13, no library gives access. This is most likely due to the fact that the project uses Flutter 1.22.6. with version Dart 2.10 (before null safety). I have already added to the manifest the necessary permissions.

 AndroidManifest.xml
 
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    android:maxSdkVersion="32"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
    android:maxSdkVersion="32" />

<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
```

But apparently due to the fact that the libraries are old, it does not see that accesses are allowed (I turn them on manually on the phone). MultiImagePicker.pickImages was originally used, which threw an exception Permission denied. Next, I tried the image_picker package, there, when calling the method, it throws the following error:

`Unhandled Exception: PlatformException(photo_access_denied, The user did not allow photo access., null, null)`

Switching to a later version of flutter is a rather time-consuming task, is it possible to somehow do without it? Maybe someone already had experience? I'm sure that the point is that the old versions of these libraries are not yet designed to work with Android 13

Thank you!

 

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 1.22.6, on macOS 13.5.2 22G91 darwin-arm, locale en-UM) 
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) 
[✓] Xcode - develop for iOS and macOS (Xcode 14.2) 
[!] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (1 available)
```

**Comment by danagbemava-nc** [comment]
Hi @oooophelia, can you try a minimal project using the latest version of flutter to see if this is still happening? You can use a tool like fvm to manage your flutter versions so you do not switch your project from the current version of flutter it is using. If this still happens with the latest version of flutter and image_picker, kindly provide a complete minimal reproducible code sample so that we can investigate it. Otherwise you will have to upgrade to the latest version of flutter. 

On another note you should upgrade to the latest version of flutter. 1.22.6 is far too old.

Thank you
