### ISSUE TITLE
Container -> BoxDecoration -> BorderSide

### ISSUE THREAD

**Issue by LoveBabyForeve** [flutter/flutter#140597]
### Use case

Use BorderSide to draw dotted lines in the Container component

### Proposal

like： 
```
Container(
  decoration: BoxDecoration( 
  borderRadius: BorderRadius.circular(8),
  border: Border.all( width: 1.0.r, color: Colors.black, **style: BorderStyle.dashed**), 
), 
child: Text('Container with dashed border'),
)
```

**Comment by dam-ease** [comment]
Thanks for filing this. 
Some packages could be used to achieve this such as https://pub.dev/packages/dotted_border.

Your question seems to be best suited for support channels like StackOverflow, please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
