### ISSUE TITLE
Animated webp controller for Image widget

### ISSUE THREAD

**Issue by amrgetment** [flutter/flutter#140577]
### Use case

Control the animation of an animated webp or apng formats for logos in splash screen or any other cases

### Proposal

I used an animated webp image but I can't control its animation and no package to control it
I wonder if Image widget could add a controller to animated webp or apng formats 
Or adding a new child called AnimatedImage that support controlling the animation for images.

**Comment by dam-ease** [comment]
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.
Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

**Comment by amrgetment** [comment]
@dam-ease I opened a question here 
https://www.reddit.com/r/flutterhelp/comments/18rxwqh/control_animated_webp_or_apng_in_flutter/
However that I still think that their should be a package by Flutter or a solution for this case

**Comment by amrgetment** [comment]
@dam-ease it is duplicated
https://github.com/flutter/flutter/issues/111150
https://github.com/flutter/flutter/issues/59605
