### ISSUE TITLE
Fixed size Scaffold body fails (annoyance)

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1406]
Every couple of weeks I still make the following mistake. Often in a more complex context, but it's the same mistake.

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Fail extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Scaffold(
      toolBar: new ToolBar(center: new Text('Not a 100x100 Green Box')),
      body: new SizedBox(
        height: 100.0,
        width: 100.0,
        child: new Container(
          decoration: new BoxDecoration(backgroundColor: const Color(0xFF00FF00))
        )
      )
    );
  }
}

void main() {
  runApp(new MaterialApp(
    title: 'FAIL',
    routes: <String, RouteBuilder>{
      '/': (RouteArguments args) => new Fail(),
    }
  ));
}
```

Despite the 100x100 width,height constraints specified for the Scaffold's body, it ends up filling all of the available space.  Generally speaking, Flutter widgets abide the size constraints they're given. In this case they don't and that can be confusing.

Maybe a console message would help.

**Comment by Hixie** [comment]
RenderConstrainedBox could print something in checked mode when the additionalConstraints don't fit the incoming constraints. It might happen enough that it's just noise in the console, though. I mean, it's not a violation of the contract or anything like that.

It happens here because the Scaffold is of the opinion that the child must fill the body area. The other option would be for us to have a different opinion, for example, we could have the opinion that the Scaffold will always be filled by a canvas material, and that whatever you pass as the 'body' is then centered within that.

**Comment by HansMuller** [comment]
It may be that I'm the only one who keeps bumping into this :-).

If it turns out that new developers find this case confusing, perhaps we could issue a console message just for this case.

**Comment by abarth** [comment]
Yeah, we might want to pick a layout model for the body of the scaffold.  Center is probably a reasonable choice.

**Comment by abarth** [comment]
Fixed.  It's now aligned to the top left.
