### ISSUE TITLE
[FATAL:flutter/shell/common/shell.cc(428)] Check failed: !settings.enable_software_rendering || !settings.enable_impeller. Software rendering is incompatible with Impeller.

### ISSUE THREAD

**Issue by gyyxiaogao** [flutter/flutter#140718]
### Steps to reproduce

ios emulator crashes when booting

### Expected results

ios emulator crashes when booting

### Actual results

ios emulator crashes when booting

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
ios emulator crashes when booting

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment]
Impeller does not support simulators that aren't running on devices with GPU passthrough, such as some cloud providers. In the past this wouldn't fail at startup, but would boot into a mode where parts of the engine used Skia and parts used Impeller, which lead to crashes. This behavior was changed so that the app exits in unsupported configurations instead.

if you need to run Flutter on software only simulators, you need to explicitly opt out of Impeller.
