### ISSUE TITLE
Flutter can't decode this image

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#14077]
Flutter can't decode this image: http://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/AusGeo/2014/02/12/38296/dugong.jpg

I put the above url in a new Image.network and get the following error:

01-12 12:22:20.423 10690 10707 E flutter : [ERROR:flutter/lib/ui/painting/codec.cc(91)] DecodeImage failed

**Comment by apwilson** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
This image is rejected by Skia's GrBackendTextureImageGenerator::Make because its color space returns false for both gammaCloseToSRGB() and gammaIsLinear()

https://github.com/google/skia/blob/master/src/gpu/GrBackendTextureImageGenerator.cpp#L36

The image does decode if the engine uses SkImage::MakeFromEncoded instead of SkImage::MakeCrossContextFromEncoded.  I suppose we could fall back to MakeFromEncoded in cases where MakeCrossContextFromEncoded returns null (although that will hurt performance)

@chinmaygarde @brianosman

**Comment by brianosman** [comment]
That check is overly restrictive, and can be relaxed. I've got a CL up to do so: https://skia-review.googlesource.com/c/skia/+/94782

**Comment by brianosman** [comment]
The Skia fix has been merged into Flutter's engine repo - it should work with the latest engine.
