### ISSUE TITLE
No implementation found for method setAccelerationSamplingPeriod on channel dev.fluttercommunity.plus/sensors/method

### ISSUE THREAD

**Issue by luvthence** [flutter/flutter#140853]
### Steps to reproduce

I'm not using any sensor plugin still I'm getting this error in my debug console... and also this report in Firebase crash analytics. This is not impacting in app.but still reporting in crashlytics. 

I tried flutter clean, pub get, restart, uninstall, reinstall everything. but still not able to fix this.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setAccelerationSamplingPeriod on channel dev.fluttercommunity.plus/sensors/method) E/flutter (20167): #0
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)

### Expected results

This warning should not come in debug console as It's reported every time when user open app in firebase crashalytics.

### Actual results

this warning should not come in debug console as It's reported every time when user open app in firebase crashalytics.

### Code sample

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setAccelerationSamplingPeriod on channel dev.fluttercommunity.plus/sensors/method) E/flutter (20167): #0
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @luvthence, are any of your dependencies using the sensors_plus package? Flutter itself does not require the plugin so this is likely due to one of your dependencies if you are not using it directly in your project. 

You should check which of your dependencies relies on that package and report the issue to the appropriate repository so that it can be properly investigated. 

Closing from here as this is not a flutter issue. 

Thank you

PS: You can check if the sensors plugin is used in your project by checking your pubspec.lock. You can also run `flutter pub deps -- --style=compact` to see your dependencies and their dependencies.
