### ISSUE TITLE
[pigeon] Fix style of Kotlin enums

### ISSUE THREAD

**Issue by yuukiw00w** [flutter/flutter#140938]
### Use case

I am currently working with the Pigeon package in Flutter, where I use enums to define common data types across Swift, Kotlin, and Dart. However, I have encountered an issue with the naming convention for enum cases. Specifically, when using lower camel case for enum cases, Android generates uppercase concatenated strings. As a result, Pigeon currently supports only single-word enum cases.

```dart
enum SampleEnum {
  sampleVersion,
  sampleTest,
}
```
```kotlin
enum class SampleEnum(val raw: Int) {
  SAMPLEVERSION(0),
  SAMPLETEST(1);

  companion object {
    fun ofRaw(raw: Int): SampleEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
```

### Proposal

I propose implementing a feature in the Pigeon package that supports defining enum cases in lower camel case, resulting in lower camel case conversion for Swift(maintaining the current behavior) and screaming snake case conversion for Kotlin.

In Kotlin, the corresponding generated code should adopt screaming snake case for enum cases.
```kotlin
enum class SampleEnum(val raw: Int) {
  SAMPLE_VERSION(0),
  SAMPLE_TEST(1);

  companion object {
    fun ofRaw(raw: Int): SampleEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
```

**Comment by stuartmorgan** [comment]
Retitling; the current title is asking for a policy that we translate names to the appropriate style for each language, which is already the policy for Pigeon. The current Kotlin enum behavior is just a bug.

https://developer.android.com/kotlin/style-guide doesn't appear to say anything about enums specifically, so we can fall back to https://kotlinlang.org/docs/coding-conventions.html#property-names. That allows for either screaming snake case or upper camel case, so we should just pick one; screaming snake as requested here seems fine (and will require fewer changes to existing code for pigeon clients, since only multi-word enum values will change).

**Comment by stuartmorgan** [comment]
This just requires a trivial change [here](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/kotlin_generator.dart#L130), and appropriate Dart unit tests.
