### ISSUE TITLE
URL doesn't exist

### ISSUE THREAD

**Issue by marycanonce** [flutter/flutter#141276]
vs code is error because of this:

Target of URI doesn't exist: 'package:flutter/material.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.

need help plzzz...

**Comment by dam-ease** [comment]
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.
Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
