### ISSUE TITLE
[video_player] How to create reusable video controllers with feeds app

### ISSUE THREAD

**Issue by heshesh2010** [flutter/flutter#141441]
### Use case

Hi , I'm developing new app like instagram , so I have timeline has listview of videos , so in android I want to create only 3 instances of video controller and use them again to void android memory leak . 

also I'm using visibility_detector to play / pause video when video player not in current view . 

but I got many problems such as I can't create new instances without setting network or file parameter to video controller class . 

do anyone has full example achieve this 

### Proposal

video list example app

**Comment by betacoder7** [comment]
It does not belongs to issues category

**Comment by dam-ease** [comment]
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.
Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
