### ISSUE TITLE
initState() async improvements

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#14152]
I made a StackOverflow question :
https://stackoverflow.com/questions/48286488/flutter-how-to-read-preferences-at-widget-startup

It had me stumped for quite some time. I feel like there is scope for improvement to this problem.
I am still confused why the original is not valid (ignoring the missing setState()).

Wrapping the Preference call inside an anonymous async no longer gave a runtime error, but did not work either, e.g :

    @override
    initState() {
      super.initState();
      _name = "";
      (() async {
        SharedPreferences prefs = await SharedPreferences.getInstance();
        _name = prefs.getString("name");
        setState(() {
          _controller = new TextEditingController(text: _name);
        });
      });
    }

Improvement ideas I thought of :
1. Dont allow async on initState() during compile.
OR
2. Throw a better runtime exception such as async not allowed on initState()
OR
3. Fix initState() to allow async.

**Comment by rmtmckenzie** [comment]
I agree that it's too easy to make an initState async - I did without thinking about it and had some strange behavior as a result. But for your particular case, I think it's not working because you're not calling the anonymous async but rather just defining it.  You'll want to do this:

    (() async {
      ...
    })();

Another option would be to just define a different function (I've called it asyncInitState personally) and call it from initState.

**Comment by Hixie** [comment]
We've updated the framework to catch cases of making `initState` itself async. Not sure we can really catch the other cases easily. With @rmtmckenzie's suggested change, and use of `mounted` to make sure that you don't run code after `dispose`, your example should work.
