### ISSUE TITLE
Expose `scrollbars` in `ScrollBehavior`

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#141508]
### Use case

In the super_editor package we add a modified `Scrollbar` in the widget tree and some developers want to prevent that `Scrollbar` from being added.

We'd like to let users wrap the editor with a `ScrollConfiguration` like in the following sample and then query this information to decide whether or not we want to include the `Scrollbar` in the widget tree:

```dart
ScrollConfiguration(
 behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
 child: SuperEditor(...),
)
```

However, we can't query `scrollbars` because the `ScrollBehavior` itself doesn't have a `scrollbars` property. When we call `copyWith` it returns a `_WrappedScrollBehavior`, which is the class that holds `scrollbars` property.

### Proposal

Provide a way to query this information.

**Comment by nikkivirtuoso** [comment]
I think we can do this by making custom inheritedWidget class in that we can define 3 parameters like required this.scrollBar and required widget child and key after this we can check whether the scrollBar value is false or true by using the @override updateshouldnotify so that we can reconstruct the widget if the old widget and the new widget scrollBar value is different and then we can assign this value to the ancestor widget i.e. the old widget

**Comment by goderbauer** [comment]
cc @Piinks

**Comment by nikkivirtuoso** [comment]
@Piinks ma'am, please have a look

**Comment by Piinks** [comment]
@nikkivirtuoso respectfully, please do not spam pings. Thank you.

**Comment by nikkivirtuoso** [comment]
Then why this issue is open if users are able to do so
