### ISSUE TITLE
[RFW] Include more core, material and cupertino widgets in the rfw libraries.

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#141668]
### Problems

1. `core` and `material` existing RFW libraries are out of sync with the available core and material widgets in flutter. E.g. We don't have `ExpansionTile` in neither of those.
2. We don't have the `cupertino`  RFW counterpart.

**Comment by Hixie** [comment]
Anyone is welcome to submit PRs to add widgets or new core libraries. If anyone needs an issue to track that work they are welcome to use this one or file a new one; unless anyone wants to do that work though I don't think there's much value in having this issue open, because we will literally never be fully in sync, those libraries are continually evolving.

**Comment by Hixie** [comment]
Sounds good.

(And yes, widgets grow the binary size.)

**Comment by Hixie** [comment]
I'm going to close this issue since it's not tracking a specific problem. We'll always be "behind", but we're always open to new PRs to add more support.
