### ISSUE TITLE
I am facing issue in gradle version

### ISSUE THREAD

**Issue by harish18092002** [flutter/flutter#141702]
### My error

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Dell\Desktop\LastMinute.-last_minute\LastMinute.-last_minute\source\last_minute\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 7.5. Current version is 7.4.2. If using the gradle wrapper, try editing the distributionUrl in C:\Users\Dell\Desktop\LastMinute.-last_minute\LastMinute.-last_minute\source\last_minute\android\gradle\wrapper\gradle-wrapper.properties to gradle-7.5-all.zip

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Running Gradle task 'assembleDebug'...                             25.2s
Exception: Gradle task assembleDebug failed with exit code 1

### My build.gradle file

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-all.zip

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.22631.3007], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2023.1)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
 -->

```

</details>

**Comment by huycozy** [comment]
Hi @harish18092002 
The error message is quite clear that it's a Gradle version issue. You should try using a newer version as suggested. You can check such a fix [here](https://stackoverflow.com/a/73333119/5921933) (it does not match Gradle versions but will indicate where to fix it).

Since this is a Gradle version issue, it doesn't look like a bug on Flutter framework, I'm going to close this. 
Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).
