### ISSUE TITLE
How to wrap the SafeArea widget with another Expanded?

### ISSUE THREAD

**Issue by CarolinaMD** [flutter/flutter#141707]
Hi everybody!

I'm new in Flutter and my level of technology is 0. I came here for a friend's suggestion because I need to create an app...

So, during the session Your first Flutter app, in section 7: Add navigation rail, I get stacked in "If you want to get a better feel of the role of this widget, try wrapping the SafeArea widget with another Expanded." I don't know how to do it, I tried a lot of ways but they didn't work.

If you have any idea, please, let me know.

Thanks,
Carolina

**Comment by CarolinaMD** [comment]
I guess I got it,
Thanks anyway ;)

**Comment by huycozy** [comment]
It seems you solved the issue. Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
