### ISSUE TITLE
Suspecting an error in `calculateCacheOffset`

### ISSUE THREAD

**Issue by yangyuanxx** [flutter/flutter#141767]
Hi there! 
I was a little confused when reading the source code, not sure if I misunderstood it or there is a missing part in the code. As the code shown below, is the variable `b` missing a `+ constraints.cacheOrigin`? Otherwise, to my understanding, the cacheOrigin distance will be calculated twice, which make the `b` bigger than expect.

https://github.com/flutter/flutter/blob/a5da3a2217eb73f000aee6043e50b33dfaf0268f/packages/flutter/lib/src/rendering/sliver.dart#L1491-L1497

**Comment by huycozy** [comment]
Hi @yangyuanxx 
The goal of this Github is to improve flutter reporting bugs or feature requests. So if you encounter behavior that you believe could be a Flutter framework bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Also, please provide the output of `flutter doctor -v` as well. 

Otherwise, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. Thanks!
