### ISSUE TITLE
favorites page

### ISSUE THREAD

**Issue by CarolinaMD** [flutter/flutter#141722]
Hi!
I did what was required to implement the favorites page in Your first Flutter app but the favorites page doesn't appear in the flutter app. Can anybody have an idea how to figure it out, please?
Thanks,

**Comment by dam-ease** [comment]
Hello @CarolinaMD.
Are you referring to following the steps in this codelab https://codelabs.developers.google.com/codelabs/flutter-codelab-first#0.
Kindly share your code sample and what issues you are facing.
In summary, please provide all information as indicated in the issue template

**Comment by CarolinaMD** [comment]
Hello @dam-ease,
Thanks for your comment. I'm pretty new in this world of code and technology. I didn't even know how to do a repository and I've got it! https://github.com/CarolinaMD/My-first-app/blob/trunk/lib/main.dart
Well, Yes, I was referring to this codelab. I went through the whole process again in order to figure out what step I got wrong, but I couldn't. I ended up with the same error, the Place Holder is still there, instead of the Favorites screen. I finally tried to replace the whole of my code in lib/main.dart for the one in the codelab repo https://github.com/flutter/codelabs/tree/main/namer/step_08 and the problem was solved. However, still unknown why "my codelab" didn't work.
Thanks for your patient!

**Comment by dam-ease** [comment]
Hey @CarolinaMD. This seems to be an issue with your code implementation or you probably missed out on some things in the steps, you could try a code comparison to that in the code labs.
Also, your question is best suited for support channels like StackOverflow, so please ask more questions there if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
