### ISSUE TITLE
[RFW] RFW beyond `rfwtxt`

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#141948]
RFW is an amazing and very promising technology; but one entry barrier is the fact that writing RFW today is only possible by using `rfwtxt` and using a new language (even one as simple as `rfwtxt`) is always a challenge.  Even though RFW ships rfwtxt as the official language, and provides tooling to deal with it, it is a very well designed layered system which means the community can easily come up with  alternatives to `rfwtxt` (and ofc as long as they produce the rfw binary code they should work out of the box). 

The intention of this thread is to gather feedback (from anyone) around generating RFW compatible binaries using conventional/existing languages and frameworks. Given the well designed, layered system RFW is, I personally think libraries can be built in mainstream programming languages like Dart and Kotlin. One important thing to mention is that RFW ui is by definition closer to server so exploring how to write it using server programming languages is very appealing. 

Just to be extra clear, I'm not in any way suggesting there is something wrong with rftxt or that it should be replaced with something else. `rfwtxt` is amazing and fills certain use cases. Instead I just think these libraries, DSLs ... whatever should be yet another way to write rfw UIs.

**Comment by tugorez** [comment]
I hacked a library that resembles Flutter's widget system https://github.com/tugorez/rfw_random_ideas but instead of producing a widget tree that flutter understands, the library compiles it to a `rfwtxt`. Please keep in mind that the reason it produces `rfwtxt` is merely practical (hope is easy to see going from rfwtxt to the rfw binary code should be straightforward). The main goal of this experiment was to explore how expressing RFW UIs would look like in Dart rather than achieving feature parity with RFWTXT (In other words, it doesn't support, yet, all the things rfwtxt does).  For a side by side comparison between this dart implementation vs `rfwtxt` please take a look at this commit view https://github.com/tugorez/rfw_random_ideas/commit/c429388724b8d4d4a24346cc709cd6cb87d1b1d7#diff-dc6f106a9cca252d9e436444e0bbc34823cd32dbcc5d18a0111393e095fbf6eb

It is a flutter app so feel free to clone it and run it. It should show a simple `hello world` screen.

**Comment by tugorez** [comment]
Left some ideas in https://github.com/tugorez/rfw_random_ideas/commit/c429388724b8d4d4a24346cc709cd6cb87d1b1d7#diff-dc6f106a9cca252d9e436444e0bbc34823cd32dbcc5d18a0111393e095fbf6eb

**Comment by Hixie** [comment]
If you generate actual RFW model objects, you should be able to trivially encode to either the binary or text formats directly. (That's how the compiler works, it parses the rfwtxt to model objects and then encodes the model back to the binary format.)

(I forget if the text format has an encoder actually. Maybe it doesn't? It'd be relatively straightforward to add one if needed.)

**Comment by munificent** [comment]
> For a side by side comparison between this dart implementation vs `rfwtxt` please take a look at this commit view [tugorez/rfw_random_ideas@c429388#diff-dc6f106a9cca252d9e436444e0bbc34823cd32dbcc5d18a0111393e095fbf6eb](https://github.com/tugorez/rfw_random_ideas/commit/c429388724b8d4d4a24346cc709cd6cb87d1b1d7#diff-dc6f106a9cca252d9e436444e0bbc34823cd32dbcc5d18a0111393e095fbf6eb)

I strongly support the idea of using an API in Dart to define widgets. Making a new language is a ton of work if you want to provide a decent user experience: parsing, good error recovery in the parser, good syntax error messages, documentation, syntax highlighters, auto-complete, etc. Everyone underestimates this.

That being said, the API you sketch out here is pretty verbose and it would be nice to get something closer to the brevity of rfwtxt. I got [nerd sniped](https://xkcd.com/356/) into spending my morning playing around with some ideas. [Here's what I got to](https://gist.github.com/munificent/90687877e5bf711bfcfce132ed4e5551):

```dart
widgets.Main = widgets.CenteredAndBlue(
  text: 'Hello world!',
);

widgets.CenteredAndBlue = widgets.BlueContainer(
  child: widgets.CenteredText(text: args.text),
);

widgets.BlueContainer = widgets.Container(
  color: 0xFF78909C,
  child: args.child,
);

widgets.CenteredText = widgets.Center(
  child: widgets.Text(text: args.text),
);

print(generateRfwTxt(widgets.Main));
```

It leans heavily on `dynamic` and `noSuchMethod` because RFW is itself dynamically typed. But the above is perfectly valid Dart code and when run with the given prototype library generates almost exactly the same rfwtxt output. (Almost because I guess `Invocation` doesn't guarantee key order for named arguments so the map keys are shuffled.)

Is this API a good? I have no idea. But it might be interesting food for thought. :)

**Comment by jacobsimionato** [comment]
I had a couple of related product thoughts:

### Performant support for dynamic server-generated templates 

Our initial RFW customer inside Google is looking at generating *some* of their remote widgets as .rfwtxt dynamically on the server. We can bundle the .rfwtxt -> .rfw compiler in Dart, or reimplement it in Java/Kotlin, but for this specific (and unusual) use case, we probably don't want to add a step of compiling and running Dart code to the request path. Bundling the Dart compiler in the server is probably a hassle, and the whole process sounds slow. But this is an unusual case that only applies to some of this customer's remote widgets. There are other hand-written remote widgets where Dart-based authoring could be very helpful.

So overall, for our immediate project, we have a specific interest in maintaining .rfwtxt or something like it that can compiled and sent to the client without sending it through a complex tool chain. I just want to explain why we may seem so fixated on .rfwtxt at the moment!

### Code pushable apps

Ian and others have previously discussed the future idea of a React-native ish "code pushable" Flutter architecture where you have pushable application logic running as a Flutter Web app compiled to JS or wasm and running in v8 etc on a phone. The JS/wasm logic communicates with the engine + framework with is AOT compiled and not pushable. I think Ian brought up the idea of the .rfw binary format (or something similar) potentially being the protocol that is used for communication.

Could there be overlap between this idea and the Dart RFW authoring API? They're a bit different because in the code push case, you'd want to allow event handlers with arbitrary Dart logic, which are then somehow triggered when the relevant events occur on the AOT side. While in the template authoring use case, there can be no arbitrary logic like this. But maybe we could keep this in mind when designing the Dart API here, and eventually share the same API for both use cases? If you try to call `generateRfwTxt` (or `generateRfwBinaryFormat` as Ian suggested) on the tree, it could just fail if it uses features like arbitrary event handlers that cannot be serialized. 

Not sure if this makes any sense, but curious if people have thoughts!

**Comment by Hixie** [comment]
If there's a specific other ecosystem/language that would benefit from an rfwtxt->rfwbin converter, please do file a bug on that, maybe we can provide a canonical one.

Regarding _code_ push (as opposed to UI push), it's very much the intent that package:rfw never support this directly, because we want to make sure that rfw usage is never a valid signal that an app uses code push (because some stores ban code push but not UI push). For code push I would point people to shorebird.dev (cc @eseidel).

**Comment by johnmccutchan** [comment]
Replying to [jacobsimionato](https://github.com/jacobsimionato)@

> So overall, for our immediate project, we have a specific interest in maintaining .rfwtxt or something like it that can compiled and sent to the client without sending it through a complex tool chain.

This jumped out to me as well, [rfwpg](https://github.com/johnmccutchan/rfwpg) would be made much more complex by having to run a toolchain that involves executing arbitrary Dart programs just to produce the rfwtxt/rfw needed to render the UI. In addition to code complexity of this solution the round-trip time would be significantly increased.

**Comment by johnmccutchan** [comment]
> If there's a specific other ecosystem/language that would benefit from an rfwtxt->rfwbin converter, please do file a bug on that, maybe we can provide a canonical one.

+1 to this, assuming the server is C++ or Java we should just implement this converter natively.

**Comment by Hixie** [comment]
@tugorez What are the next steps here?
