### ISSUE TITLE
======== Exception caught by rendering library ===================================================== The following assertion was thrown during performLayout(): RenderBox was not laid out: RenderPadding#1b70c relayoutBoundary=up21 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE 'package:flutter/src/rendering/box.dart': Failed assertion: line 1966 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by RanaKirtan-bit** [flutter/flutter#142064]

**Comment by huycozy** [comment]
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further investigation.
