### ISSUE TITLE
[Impeller] unexpected performance regression on introduction of depth buffer

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142019]
See https://flutter-flutter-perf.skia.org/e/?keys=X810e39ca0159f4aa5b45558cbd203945&selected=commit%3D38896%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=38896

I think this might be the device that doesn't have device transient texture support? We should confirm with profiles, but if so the extra time might be allocation.

FYI @bdero

**Comment by bdero** [comment]
99% definitely smells like allocation on first frame. Not sure this matters unless we see bad regressions like this (p90+25%) on more devices.

**Comment by jonahwilliams** [comment]
Average also regressed. We need to understand why it regressed.

**Comment by bdero** [comment]
I expect devices which don't support transient textures are going to flush to textures a lot.

**Comment by bdero** [comment]
I agree we should try profile to see if that theory actually shapes up.

**Comment by jonahwilliams** [comment]
Actually the A02 is running GLES

**Comment by bdero** [comment]
I haven't managed to get the benchmark running locally at head due to [build failures](https://gist.github.com/bdero/9411162d834b10605439190c58056858), but here's what I've found so far:

- All the [GLES raster time](https://flutter-flutter-perf.skia.org/e/?begin=1706424061&end=1706510461&queries=device_type%3DMoto_G__4_%26device_type%3DSM-A025V%26device_type%3DSM-G973U1%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_impeller__transition_perf&selected=commit%3D38896%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=38896) benchmarks for `new_gallery_impeller__transition_perf` are affected. Both SMA02V and Moto G4.
- Only `new_gallery_impeller__transition_perf` is affected. `platform_views_scroll_perf_impeller` and `list_text_layout_impeller_perf` are not. The difference is most likely the presence of offscreen render targets.
- Although if we were using texture storage for the stencil we'd always fallback to D24S8, we're definitely using renderbuffer storage for the multisample depth+stencil on offscreen targets (which is the right things to do). And the format for the depth+stencil was changed from `GL_STENCIL_INDEX8` to `GL_DEPTH24_STENCIL8`.
- Both devices support [`GL_EXT_discard_framebuffer`](https://opengles.gpuinfo.org/listreports.php?extension=GL_EXT_discard_framebuffer). The way we're using `glDiscardFramebufferEXT` looks correct to me, renderbuffers or not. It's just a hint at the end of the day, though.
- I noticed that the packed depth+stencil we've been using even for S8 textures (`GL_UNSIGNED_INT_24_8`) is GLES 3 only and requires  [OES_packed_depth_stencil](https://registry.khronos.org/OpenGL/extensions/OES/OES_packed_depth_stencil.txt). But that's a problem for another day...

**Comment by jonahwilliams** [comment]
Tentatively assigning to @bdero

**Comment by bdero** [comment]
I'm putting this investigation on hold while I build the rest of the StC solution.

**Comment by jonahwilliams** [comment]
Turns out this device is using Vulkan now!
