### ISSUE TITLE
This is probably fixed by adding `shrinkWrap: true,` to the scrollable widget

### ISSUE THREAD

**Issue by MarcSoft54** [flutter/flutter#142174]
This is probably fixed by adding `shrinkWrap: true,` to the scrollable widget

_Originally posted by @Zazo032 in https://github.com/flutter/flutter/issues/65677#issuecomment-691518456_
            

i did it,
but is not scrolling agains

**Comment by MarcSoft54** [comment]
how can do to solve this problem

**Comment by huycozy** [comment]
Hi @MarcSoft54 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further investigation. Thanks!
