### ISSUE TITLE
after an app restores from the background, existing images no longer render

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#14228]
See discussion here: https://github.com/dart-lang/conference_app/pull/43#issuecomment-359641858

- run the app
- switch to another application
- switch back to the app; images in the schedule that were previously loaded now won't render (but the space where they should be will be sized properly); scrolling down will load in previously un-loaded images

This occurs on the head version of flutter, but not for previous versions. /cc @rock3r

**Comment by rock3r** [comment]
I have solved the issue for now on the app by doing a rollback of Flutter to the 0.0.20 tag:

```bash
$ cd flutter
$ git checkout "0.0.20"
$ cd ../flutter-conference-app/
$ flutter packages get
```

And then (after [fixing the build](https://github.com/rock3r/conference_app/commit/d8ea31bc4d3985bc185128c6ede0eedc774f7d1d)) I re-built the app. That works, so the issue seems to be localised in somewhere between 0.0.20 and the HEAD indeed.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/14194

This should be fixed on the latest engine.  Do you still see it if you upgrade to the tip of tree?

**Comment by rock3r** [comment]
It happened after I ran `flutter upgrade` last night (UK time), so I imagine yes

**Comment by csbenjamin** [comment]
I was with this issue too. I just did a flutter upgrade using the master branch and the issue is gone.

**Comment by devoncarew** [comment]
I suspect that this issue was for a range of commits on master, and is now addressed.
