### ISSUE TITLE
Dart SDK -> Engine roller blocked on `const_finder` analysis errors

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#142253]
Roll failures started here: https://github.com/flutter/engine/pull/50050

The analyzer error looks like this:   info - const_finder/test/fixtures/lib/box.dart:11:7 - Missing documentation for a public member. Try adding documentation for the member. - public_member_api_docs
My initial suspicion is this Dart CL: https://dart-review.googlesource.com/c/sdk/+/345346 My theory is that somehow the hierarchy of analysis_options.yaml or something isn't being respected.

**Comment by eyebrowsoffire** [comment]
In general, I wouldn't expect `public_member_api_docs` to happen in test files. I confirmed that the issue is resolved with a revert of the aforementioned Dart CL. I created a revert CL here: https://dart-review.googlesource.com/c/sdk/+/348364

**Comment by keertip** [comment]
@eyebrowsoffire , can you add a link to the build bot failures. Would like to test this locally and fix the issue. Thanks!

**Comment by eyebrowsoffire** [comment]
@keertip Here you go! https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1890013/overview

**Comment by eyebrowsoffire** [comment]
The revert was merged a while ago, so this is not longer blocking the roller. Closing.

**Comment by whesse** [comment]
This was not found on the Dart CI flutter_analyze builder, because this only analyzes the single library lib/web_ui in flutter/engine, not the large set of directories analyzed by Flutter CI's https://github.com/flutter/engine/blob/main/ci/analyze.sh

It does include the fatal-infos flag, though.  It seems likely we should expand the set of directories analyzed by our CI.
