### ISSUE TITLE
Issues on initiating Flutter at VSCode Android version

### ISSUE THREAD

**Issue by kdr2738** [flutter/flutter#142433]
![Screenshot_20240113_232021_VScode](https://github.com/flutter/flutter/assets/158033967/8d87e75f-9bef-45c6-ac4d-392555efcabe)
![Screenshot_20240113_234618_VScode](https://github.com/flutter/flutter/assets/158033967/f49b30dd-691a-4583-a288-8934683031a7)

I've procured VS Code for Anrdoid to make code Dart & Flutter through my mobile, however, I found some errors like attached.
Is there any solution to proceed?

Thank you in advance.

**Comment by dam-ease** [comment]
Hello @kdr2738 
Can you please share the output of your `flutter doctor -v`?

**Comment by kdr2738** [comment]
Thanks for quick response.
Since I'm very beginner of either Flutter or VS Code, I have no idea how to check "output of flutter doctor in Android".
Would you please share the information of checking "output of flutter doctor" in Android?

**Comment by dam-ease** [comment]
Hello @kdr2738.
Please run `flutter doctor -v` from your command prompt (if Windows) or terminal (if Mac) and try to resolve all issues in the output. You may see support channels like Stack Overflow for help on how to resolve them.
Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
