### ISSUE TITLE
Update API docs to include example of how to get current Route

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14243]
Add a Route<> current() or a bool isCurrent(Route) API to NavigatorState

**Comment by xqwzts** [comment]
@xster I picked this up, it seemed a simple enough solution to expose NavigatorState's `_history.last` property with a getter. Did you have something else in mind?

**Comment by xster** [comment]
@Hixie may have some existing mental picture of what he wants to do

**Comment by Hixie** [comment]
Can you elaborate on the use case here? Why is `ModalRoute.of(context).isCurrent` sufficient, for instance?

**Comment by xster** [comment]
I think it is. Might just be a matter of documentation and convenience.

**Comment by sroddy** [comment]
What if the route is not a ModalRoute and the widget can be added in different routes?

**Comment by Hixie** [comment]
Can you give an example?

How would you use the new API? (e.g. how would you be notified if the current route changed, or if the current widget was moved to another route?)

**Comment by vmwsree** [comment]
Hi In my Case in a chat app , the user should get a notification for all the messages on the screen except the active chat, So I have to check if the current route is equal to the notification I received, if so ignore else show.

**Comment by dspoonia7** [comment]
Need this as well, as I also have exactly the same use case as @vmwsree has mentioned above. 
But in addition to not show notification for the active chat, I also want to cancel all the notification if chat-app home screen (list of all chat) widget is visible in the viewport.
@xster @zoechi

**Comment by vmwsree** [comment]
Rather than title saying Document how to get current Route, I don't think there is a feature to fetch the current route or its type, this is a framework requirement

**Comment by Ikxyz** [comment]
To get the exact route name eg */home* use  

` ModalRoute.of(context).settings.name`

**Comment by vmwsree** [comment]
> `import 'package:path/path.dart';`

Thanks, is there a way if its Constuctor based route..

**Comment by prijindal** [comment]
@Ikxyz This method does not seem to work when using with GlobalKey<NavigatorState>

**Comment by Ikxyz** [comment]
@prijindal  It should work if you pass the context

**Comment by gagaJay** [comment]
ModalRoute.of(context) doesn’t work in my case. It is a bit complicated. I have a parent widget that contains a nested navigator, and to prevent android hardware back key to dismiss the nested navigator I used a WillPopScope to wrap up the nested navigator. So inside the onWillPop, in my rare case, I want complete control and to decide the flow base on which route that I’m on. In this case, ModalRoute.of(context) does not return the real current route of the nested navigator since the context actually comes from the parent widget(willpopscope sits in parent widget’s build method). It can only see routes from the root navigator. So the only workable solution for me is to expose the NavigatorState's _history.last which I believe is quite simple to implement. Thanks

**Comment by prijindal** [comment]
@Ikxyz I have tried it with ModalRoute.of(navigatorKey.currentContext) where navigatorKey is GlobalKey<NavigatorState> binded to a Navigator Widget and it does not seem to be working

**Comment by hanxu317317** [comment]
```
void initState() {
    super.initState();
    print("ModalRoute.of(context) ${ModalRoute.of(context)}");
```
it's wrong, MoudalRoute can't be used in initState.

**Comment by ThinkDigitalSoftware** [comment]
> ```
> void initState() {
>     super.initState();
>     print("ModalRoute.of(context) ${ModalRoute.of(context)}");
> ```
> 
> it's wrong, MoudalRoute can't be used in initState.

Don't you mean **context** can't be used in initState?

**Comment by ThinkDigitalSoftware** [comment]
I'm implementing the same feature (chat and I want to notify the user of messages if they are not in a particular conversation. I do believe there are no issues with simply making the route history public and accessible for whatever we would like to do with it. Do you have a reason not to expose it, @Hixie?

**Comment by CedricGrothues** [comment]
@prijindal I am running into a similar issue. Could you elaborate on your solution, please?

**Comment by prijindal** [comment]
@CedricGrothues Everytime i am pushing something in the route, i am pushing it in an array and i am just getting the last element of that history. This is a very bad solution since in my use case, i only care about the top most route(i.e i don't care about the route if somebody is pushing a modal on top of it and then popping out of it).
The best solution would be for them to expose this simple function.

**Comment by jaumard** [comment]
Same here, using nested navigators to do desktop/tablet/web UI in master/details and `ModalRoute.of(context)` doesn't work as I need to check the route outside the Navigator child from it's state, so exposing `_history.last ` on NavigatorState like @xqwzts is proposing would fix the issue here.

**Comment by jaumard** [comment]
I end up doing a NavigatorObserver to manage myself the navigator history

**Comment by karmazinkd** [comment]
Hey guys, when working with named routes you might want to consider the issue [ModalRoute.of(context).settings returns RouteSettings("null", null) when using onGenerateRoute #50192](https://github.com/flutter/flutter/issues/50192)  

The problem here is that if you use `onGenerateRoute` instead of `routes` you wouldn't be able to get the name by calling `ModalRoute.of(context).settings.name`, it will be always **null**.

**Comment by xsahil03x** [comment]
> Hey guys, when working with named routes you might want to consider the issue [ModalRoute.of(context).settings returns RouteSettings("null", null) when using onGenerateRoute #50192](https://github.com/flutter/flutter/issues/50192)
> 
> The problem here is that if you use `onGenerateRoute` instead of `routes` you wouldn't be able to get the name by calling `ModalRoute.of(context).settings.name`, it will be always **null**.

@karmazinkd it will work, you just need to set the name too while creating the `Route`
```dart
MaterialPageRoute(
     settings: RouteSettings(name: 'DataLoading'),
     builder: (_) => DataLoadingScreen()
);
```

**Comment by theochampion** [comment]
I'm using navigation via GeneratedRoutes and i'm having issue getting the current GLOBAL route in view. I have to screen: home screen at route `/` and chat screen at route `/chat`

I'm trying to acces the current route in view from the home screen via 
```dart
    final sets = ModalRoute.of(context).settings;
    print(sets.name);
```

but in the home screen, this always prints `/` even when the chat screen is the one in view.

If I run this code in the chat screen, it prints `/chat` as expected.

Is there a way to get the current global route in view?

**Comment by chunhtai** [comment]
what if there are multiple route that are currently visible? for example a modal route with bunch of popup? will the expectation when trying to get the current route?

**Comment by aponty** [comment]
+1 for this, same use case of trying to decide how to respond to receiving a push notification (chat app). 

If anyone is stuck waiting on a fix for this, try making a "globals" library file with a currentRoute variable, and then in your onGenerateRoute or MyApp.routes (whichever you're using) update that currentRoute with every push/pop. Then you can import that file wherever you need and read the currentRoute from it. Not ideal, but at least it's only across two files instead of every time you try and navigate.

**Comment by pedromassangocode** [comment]
Since this is labelled as `api docs` I'm wondering where this should be documented? 😕

**Comment by alibt** [comment]
> > Hey guys, when working with named routes you might want to consider the issue [ModalRoute.of(context).settings returns RouteSettings("null", null) when using onGenerateRoute #50192](https://github.com/flutter/flutter/issues/50192)
> > The problem here is that if you use `onGenerateRoute` instead of `routes` you wouldn't be able to get the name by calling `ModalRoute.of(context).settings.name`, it will be always **null**.
> 
> @karmazinkd it will work, you just need to set the name too while creating the `Route`
> 
> ```dart
> MaterialPageRoute(
>      settings: RouteSettings(name: 'DataLoading'),
>      builder: (_) => DataLoadingScreen()
> );
> ```

RouteSettings(name : "") worked and solved my issue. thanks!

**Comment by s3ppo** [comment]
hi, are there any news on this? i think i have a similar problem.. i use firebase_messaging and subscribe to onMessage.. i now only want to show the local_notification if i am not actually in the current chat.

i tried to get out the route of the navigatorkey.. but it seems this is not possible by:
```
      //Listen for incoming notifications in foreground
      FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        var route = ModalRoute.of(NavigationService().navigationKey.currentContext).settings.name;
        print(route);
      });
```

**Comment by Abacaxi-Nelson** [comment]
Same usecase he @s3ppo 
Did you try Get.current_route ?

**Comment by lailai0715** [comment]
@s3ppo Faced the same prob here

**Comment by Wian-TMC** [comment]
> hi, are there any news on this? i think i have a similar problem.. i use firebase_messaging and subscribe to onMessage.. i now only want to show the local_notification if i am not actually in the current chat.
> 
> i tried to get out the route of the navigatorkey.. but it seems this is not possible by:
> 
> ```
>       //Listen for incoming notifications in foreground
>       FirebaseMessaging.onMessage.listen((RemoteMessage message) {
>         var route = ModalRoute.of(NavigationService().navigationKey.currentContext).settings.name;
>         print(route);
>       });
> ```

This is the perfect scenario where this would be useful, but unfortunately still doesn't work in Flutter 2.2.3

**Comment by byshy** [comment]
In my case I would like to get the parent route name, and I can't do that with the ModalRoute, so exposing _history as @xqwzts suggested would be perfect.

to elaborate, I need to update a boolean on dispose, this boolean indicates if the chat screen is open or not after closing call screen, because the user can receive a call from anywhere in the app, and only in the chat screen I want to disable in app notifications, I came up with this workaround but I would like to have easier way to achieve this, it was inspired by [this SO answer](https://stackoverflow.com/a/68703480/10731757)

<img width="496" alt="Screen Shot 2021-09-28 at 11 29 11 AM" src="https://user-images.githubusercontent.com/33957976/135051975-bb76cdc1-c69a-42ff-9534-6f3d8691370d.png">

**Comment by eliasjtg** [comment]
Same issue

**Comment by byshy** [comment]
I think [this](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html) might be helpful, this is the documentation of route observer inn flutter, and I guess it fixes the issue.
I'm yet to use it, but the docs pretty much say what I was looking for.

**Comment by nkulic** [comment]
Having same issue when using context of navigatorKey 
** Usage** (i purposely used context of Navigator's state global key)
```dart
@override
Widget build(BuildContext context) {
  debugPrint("Widget's context: ${ModalRoute.of(Keys.navKey.currentContext!)?.settings}"); // Widget's context: null
```
** Definition**
```dart
     child: MaterialApp(
        navigatorKey: Keys.navKey, // static final navKey = GlobalKey<NavigatorState>();
        //...
        onGenerateRoute: (RouteSettings settings) {
          print("settings $settings"); //settings: RouteSettings("/tab-navigation", null)
          print("navKey ${ModalRoute.of(Keys.navKey.currentContext!)}"); // navKey: null
```

**Comment by chunhtai** [comment]
@nkulic navigator is above ModalRoute, you need to use context under the modal route, basically any widget under the route you returned from onGenerateRoute

**Comment by nkulic** [comment]
@chunhtai But in that case I cannot get current route name outside widget context? For example in global state, api services or similar middlewares?

**Comment by chunhtai** [comment]
@nkulic no you can't in Navigator API. Can you listen to route name change in ongenerateroute?

**Comment by kamithL** [comment]
Same issue hear , 
when i use using onGenerateRoute    always ModalRoute.of(context).settings returns RouteSettings("null", null)

**Comment by asafhayoun** [comment]
> ```
> void initState() {
>     super.initState();
>     print("ModalRoute.of(context) ${ModalRoute.of(context)}");
> ```
> 
> it's wrong, MoudalRoute can't be used in initState.
I have found a way that works in initState and doesn't require it to be a ModalRoute:

```dart
late Route oldRoute;
      Navigator.of(context).popUntil((route) { oldRoute = route; return true; });
```

**Comment by asa767** [comment]
Any proper resolution?

**Comment by cybex-dev** [comment]
+4 years later with (seemingly no resolution), I guess it is safe to say one should adopt alternatives.

**Comment by Saad29** [comment]
#14277 was such a great solution to this problem I believe, any considerations to reopen it?

**Comment by tmushayahama** [comment]
November 2022 and 4 years later no resolution to this. I thought this was a common functionality in most frameworks,

**Comment by Hixie** [comment]
@tmushayahama This issue is just about updating the API docs. If you have a use case that is not currently handled, I encourage you to file a new bug. If you would like to help us, then you are welcome to do so; Flutter is an open source project.

@Saad29 That's a PR for a different issue (it doesn't change the documentation), and it looks like Victor decided not to follow it up. You are, however, welcome to file a bug that describes the use case you want to address and then you are welcome to use that PR as the start of a patch to address your use case.
