### ISSUE TITLE
Speed up flutter web initial load

### ISSUE THREAD

**Issue by MohammadeMBi** [flutter/flutter#142402]
I have created a web app in flutter and when I try to run it on server it takes too long to load the app the first time but it doesn't have that problem after caching

what are some ways to reduce the initial load time

**Comment by stoneLee81** [comment]
1 use deferred
2 use cdn to speed up 
3 use gzip to reduce the size

**Comment by huycozy** [comment]
Hi @MohammadeMBi 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further investigation. Thanks!
