### ISSUE TITLE
Multiple tooltips are displayed at once

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#142468]
### Steps to reproduce

Use Tooltip to add tooltips to items, move your mouse across multiple items.

### Expected results

Only one tooltip is displayed at a time

### Actual results

Multiple tooltips are displayed at the same time. This is not how tooltips should ever work. Check the tooltips in any OS or app you like to use and they won't do this.

### Code sample

n/a

### Flutter Doctor output

n/a

**Comment by darshankawar** [comment]
@jezell 
I think your issue is similar to https://github.com/flutter/flutter/issues/132333 that you can follow-up in.
A [workaround](https://github.com/flutter/flutter/issues/132333#issuecomment-1682750599) is mentioned that you can try and see if it helps to resolve your case. 
Closing in favor of it. If you disagree, write in comments and I'll reopen it.
