### ISSUE TITLE
Make `dart:ui` `Image` disposed state public

### ISSUE THREAD

**Issue by iazel** [flutter/flutter#142403]
### Use case

I'm trying to develop an alternative image rendering widget for my app, which also includes an ImageCache.

It is up to ImageCache to properly dispose images whenever appropriate, therefore it is important for my widget to know when an Image has been disposed.

Right now I'm just wrapping `Image` in another class where I can keep track of `disposed` state, but this is wasteful in terms of resources given that `Image` already keep tracks of it.

### Proposal

Make `dart:ui` `Image` disposed state public

**Comment by matanlurey** [comment]
Can you explain why you need access to the `disposed` flag in release builds, perhaps sharing some of the surrounding code (or using `debugDisposed` as a placeholder to make it compile)

There might be a better way of doing what you want without exposing this state that appears intentionally hidden.

**Comment by Hixie** [comment]
In general `dispose` means "This object is the equivalent of null now" so any time you would access an object that is marked disposed it's equivalent to a null deref and you should pretend your app is crashing. :-)

The usual way to handle this is to make the actual act of disposing the resource be the end result of having determined that the resource is no longer used by anyone, not the other way around. In the case of images, there is a `clone` method so that at any time you can make sure that each `Image` only has a single owner, and that owner is responsible for disposing it, and once it is disposed there's no other object that would ever be referencing it. If you ever want to share an `Image` with another part of the code, you first `clone` it and then that part of the code has its own entirely owned object that it can dispose and so on.

**Comment by iazel** [comment]
Thanks for your explanation, before further describing my issue, I'd like to know, how expensive is cloning an image? Will it double the amount of memory used or is it more about cloning some pointers, and thus has a negligible memory footprint?

If it's the latter, that would be indeed a much cleaner approach :)

**Comment by Hixie** [comment]
It's negligible in the common case (just creates a new wrapper around the same backend data, which the engine manages). That said, I would always recommend measuring costs directly when worrying about performance, because it's very common for our intuition about costs to be incorrect.

**Comment by iazel** [comment]
Yes, `clone` is exactly what I needed, thank you very much! I'll close this issue and the PR
