### ISSUE TITLE
[Impeller] the `Plus` blend gives incorrect results when wide gamut is enabled

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142549]
On the macrobenchmarks app:

Skia

![flutter_01](https://github.com/flutter/flutter/assets/8975114/0a0f5e6f-1747-43a2-88ad-80ab7f5baa7f)

Impeller

![flutter_02](https://github.com/flutter/flutter/assets/8975114/257d9fda-8b1d-408e-9872-530d5e3e227a)

**Comment by jonahwilliams** [comment]
We're setting the wrong paint blend mode.

**Comment by jonahwilliams** [comment]
No wait, this doesn't have anything to do with the paint blend mode.

**Comment by jonahwilliams** [comment]
I haven't had time to look at this recently so I'm unassigning, but it is fairly easy to reproduce.

**Comment by jason-simmons** [comment]
This issue is only visible when wide gamut is enabled.

The app is doing a `drawVertices` with `BlendMode.plus`.

Looked at this in the Xcode debugger and noticed that the output texture for the drawVertices operation contains pixels with RGB values that sometimes exceed 1 and an alpha value of 2.

When this is blended with the content in the next layer, the results contain pixels with negative RGB values that apparently map to unintended colors in the wide gamut.

`ContentContextOptions::ApplyToPipelineDescriptor` maps `BlendMode::kPlus` to `BlendOperation::kAdd` with source and destination color/alpha blend factors of `BlendFactor::kOne`.

Is something supposed to be clamping the results of this add operation to the [0, 1] range?

**Comment by gaaclarke** [comment]
Notes from chat:

> Is something supposed to be clamping the results of this add operation to the [0, 1] range?

Everything is in extended srgb when wide gamut is enabled so colors with components outside of [0, 1] are valid colors.  Clipping may have been happening when the gamuts were set to srgb.

> and an alpha value of 2.

That doesn't sound right, wide gamut *shouldn't* be effecting valid alpha values.  Maybe we need a different alpha blend function?

---

Naively the plus blend can give different results depending if the color is represented in DisplayP3 or extended sRGB.  For example DisplayP3(0.5, 0, 0) is sRGB(0.5490, -0.0933, -0.0529).  If it is blended with itself in displayp3 we get DisplayP3(1, 0, 0), if it is blended with itself in sRGB we get sRGB(1.098, -0.0933, -0.0529).  
```
sRGB(1.098, -0.0933, -0.0529) = DisplayP3(1.0, 0.1977, 0.1365) != DisplayP3(1.0, 0, 0)
```

I wonder if that is what's happening.

**Comment by gaaclarke** [comment]
Here is the texture:
<img width="1402" alt="Screenshot 2024-03-14 at 5 39 20 PM" src="https://github.com/flutter/flutter/assets/30870216/1cd0b5c2-1d10-43b7-bd26-130bb03a8a3d">
here is the resolve:
<img width="1122" alt="Screenshot 2024-03-14 at 5 50 47 PM" src="https://github.com/flutter/flutter/assets/30870216/029caf35-f00b-4be2-8e14-10512814e15e">

Neither the source or the destination are negative numbers, but the results are.  I suspect the problem is more likely related to the alpha = 2 than anything related to wide gamut colors.  (Albeit wide gamut's float16 pixel format may be allowing us to get alpha = 2 when we couldn't before).

**Comment by gaaclarke** [comment]
the gputrace:
[PlusBlend.gputrace.zip](https://github.com/flutter/flutter/files/14609318/PlusBlend.gputrace.zip)

**Comment by gaaclarke** [comment]
Found the fix, the blend mode for the alpha was wrong:

```diff
--- a/impeller/entity/contents/content_context.cc
+++ b/impeller/entity/contents/content_context.cc
@@ -124,7 +124,7 @@ void ContentContextOptions::ApplyToPipelineDescriptor(
       color0.src_color_blend_factor = BlendFactor::kOneMinusDestinationAlpha;
       break;
     case BlendMode::kPlus:
-      color0.dst_alpha_blend_factor = BlendFactor::kOne;
+      color0.dst_alpha_blend_factor = BlendFactor::kOneMinusSourceAlpha;
       color0.dst_color_blend_factor = BlendFactor::kOne;
       color0.src_alpha_blend_factor = BlendFactor::kOne;
       color0.src_color_blend_factor = BlendFactor::kOne;
```
![IMG_6872](https://github.com/flutter/flutter/assets/30870216/4886c616-8df1-4175-a347-7844c1baf118)

**Comment by jason-simmons** [comment]
Does that match the definition of this blend mode?

Skia defines `SkBlendMode::kPlus` as `r = min(s + d, 1)`.  IIUC they are adding all of the source and destination components (including alpha) and then clamping to 1.
(see https://skia.googlesource.com/skia/+/refs/heads/main/include/core/SkBlendMode.h#51)

Or see the W3C spec at https://www.w3.org/TR/compositing-1/#porterduffcompositingoperators_plus, which is adding the source and destination alpha.

**Comment by gaaclarke** [comment]
kOneMinusSourceAlpha is essentially a clamp to one.  There's no reason to have an alpha value over 1 (here at least, maybe never?).  The alpha math listed in W3C has an implicit clamp in it.

I don't think clamping the color components would be the right call either since it would essentially be throwing out wide gamut colors prematurely.  There is already appropriate clamping happening when displaying to the device extended colors sRGB that can't be rendered.

**Comment by jason-simmons** [comment]
Consider this example:

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(CustomPaint(
      size: const Size(300, 300),
      painter: TestPainter(),
  ));
}

class TestPainter extends CustomPainter {
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(Rect.fromLTRB(0, 0, 300, 300),
                    Paint()..color = Color.fromARGB(255, 255, 0, 0));
    canvas.saveLayer(Rect.fromLTRB(0, 0, 300, 300),
                     Paint()..blendMode = BlendMode.srcOver);
    for (int i = 0; i < 20; i++) {
      canvas.drawRect(Rect.fromLTRB(0, 0, 150, 300),
                      Paint()..color = Color.fromARGB(10, 0, 0, 255)..blendMode = BlendMode.plus);
    }
    canvas.drawRect(Rect.fromLTRB(150, 0, 300, 300),
                    Paint()..color = Color.fromARGB(200, 0, 0, 255)..blendMode = BlendMode.plus);
    canvas.restore();
  }

  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```

| With Skia or `dst_alpha_blend_factor = BlendFactor::kOne` | With `dst_alpha_blend_factor = BlendFactor::kOneMinusSourceAlpha` |
| - | - |
| <img src="https://github.com/flutter/flutter/assets/14226037/6870124e-6b38-40f3-b0d9-4650d623e2e6" width="40%" height="40%"> | <img src="https://github.com/flutter/flutter/assets/14226037/8063244b-c626-4aa9-a9c6-876b0923846f" width="30%" height="30%"> |

The 20 calls to `drawRect` using `BlendMode.plus` with `alpha = 10` should repeatedly add the source alpha to the destination alpha and accumulate an alpha output that is equal to the `drawRect` with `alpha = 200`.
But if each call adds the source alpha to a destination alpha that is multiplied by (1 - src_alpha) instead of 1, then the output does not match.

**Comment by gaaclarke** [comment]
Thanks Jason, so what we know now is that the cause isn't wide gamut colors per se, but the alpha blend calculation for the `Plus` blend when the pixel format isn't clamped to 1.  Auditing the blends, `Plus` is the only one that can mathematically result in alpha values greater than one.  That would also explain why no users have reported this, I suspect `Plus` is rarely used.

I think the easiest solution would be to convert `Plus` to an advanced blend so we can do:

```glsl
out = color1 + color2;
out.a = min(out.a, 1.0);
```

I don't think the standard pipeline can do that math.

Other options
1) use a 32bpp offscreen buffer if we detect `Plus`
1) accepting `Plus` can be wrong when alpha != 1 with overlapping items

I'll see what it would take to convert it to an advanced blend.

**Comment by jonahwilliams** [comment]
Plus is used by the framework to do color lerps in decoration images:

https://github.com/flutter/flutter/blob/1c153c38d2fca7e9a74a02d2971feda1620dcc88/packages/flutter/lib/src/painting/decoration_image.dart#L750

**Comment by gaaclarke** [comment]
> Plus is used by the framework to do color lerps in decoration images:
> 
> https://github.com/flutter/flutter/blob/1c153c38d2fca7e9a74a02d2971feda1620dcc88/packages/flutter/lib/src/painting/decoration_image.dart#L750

Because the usage is blend with `plus` then restore I think the `kOneMinusSourceAlpha` would cover that usage.  The error in that blend is from the accumulation of multiple plus's where alpha < 1.0, no?  We probably still want the advanced blend.

```dart
  @override
  void paint(Canvas canvas, Rect rect, Path? clipPath, ImageConfiguration configuration, { double blend = 1.0, BlendMode blendMode = BlendMode.srcOver }) {
    canvas.saveLayer(null, Paint());
    a?.paint(canvas, rect, clipPath, configuration, blend: blend * (1.0 - t), blendMode: blendMode);
    b?.paint(canvas, rect, clipPath, configuration, blend: blend * t, blendMode: a != null ? BlendMode.plus : blendMode);
    canvas.restore();
  }
```

**Comment by jonahwilliams** [comment]
If plus is the only blend mode that is broken ... I think we're doing OK. Making plus an advanced blend is unfortunate but otherwise fixable.

**Comment by gaaclarke** [comment]
So, switching plus's alpha blend function makes the results 8x more accurate and is correct for alpha = 1 or 0.  I think we should make this an advanced blend but I wonder if we should also land the change to the alpha blend since it is super low risk if we want to cherry-pick that until the advanced blend is implemented.  We need to decide if this bug raises to the bar of wanting to cherry-pick.  I'll bring it up at the next meeting.

**Comment by jonahwilliams** [comment]
This is fixed!
