### ISSUE TITLE
BUG CORS FLUTTER WEB

### ISSUE THREAD

**Issue by eduardohr-muniz** [flutter/flutter#142668]
Resolv

**Comment by moffatman** [comment]
This CORS error is because your API endpoint requires all request to come from a HTTPS website. I don't think it's possible to easily run with `flutter` tool with local HTTPS. Maybe you can deploy it to a web server and serve over HTTPS.

By the way, not sure it is in good practice to use the API key this way from a flutter app. It should be only used in a server side context, as it's possible someone can extract it from your front-end app. Also, you posted it here in plain text, so anyone can now steal it and use it. I hope this API does not have any financial implication :eyes:

**Comment by eduardohr-muniz** [comment]
You're right, this API I used is a sandbox environment so I don't think it will cause me much trouble but I'll remove it, thanks for letting me know.

**Comment by eduardohr-muniz** [comment]
You're right, this API I used is a sandbox environment so I don't think it will cause me much trouble but I'll remove it, thanks for letting me know.
