### ISSUE TITLE
[local_auth] Unable to detect the biometric change

### ISSUE THREAD

**Issue by KKChong** [flutter/flutter#142788]
### Use case

Is there any way that local_auth is able to detect events of biometrics on the device that have changed?
This can be done in android native. 
https://stackoverflow.com/questions/44515668/android-fingerprint-detect-new-finger-added

### Proposal

Im working on banking app that need this kind of the detection, hopefully it can be done in local_auth too.

**Comment by Kijacode** [comment]
Hello @KKChong , please followup with the following discussion,

https://stackoverflow.com/questions/77463974/how-to-detect-new-fingerprint-is-added-in-phone-with-flutter/77464375?noredirect=1#comment136565855_77464375,


I am available to assit you on this please ping me : kijadanford@gmail.com

**Comment by dam-ease** [comment]
Hello @KKChong 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.
Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

**Comment by KKChong** [comment]
Hi @dam-ease, this is not proposing a change, is feature request.

**Comment by dam-ease** [comment]
Hello @KKChong.
Does the solution shared in https://stackoverflow.com/questions/77463974/how-to-detect-new-fingerprint-is-added-in-phone-with-flutter/77464375?noredirect=1#comment136565855_77464375 not suit your use case?
I also saw this issue and per comment from team member https://github.com/flutter/flutter/issues/88848#issuecomment-906724327, hence why this was closed
