### ISSUE TITLE
[iOS] Ad example app spends a significant amount of time performing software rasterization.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142813]
Run the example from https://github.com/lucalooz/flutter_ads_list_perf , I added more ads so that there were at least two on screen at one time. Then I used the package https://github.com/Kelvenbit/FlameGraphs-Instruments to capture a flame graph from an instruments trace.

While most frames are pretty fast occassionally, we get some slow ones. It might look something like this:

![image](https://github.com/flutter/flutter/assets/8975114/25325ce2-b38d-4f86-9a53-38fbd5a6e47d)

This extra time is (according to the flame graph) spent in CATransactionCommit. We can see that a large portion of this time is spent in software routines that look like they are doing software rasterization. This is highly suspicious - software rasterization is slow. This also doesn't appear to be done because of Flutter's rendering or the webview rendering.

![image](https://github.com/flutter/flutter/assets/8975114/730efa44-4a4e-4bd4-9a46-5a2d2b1b7066)

On a whim, I disabled the [mutators stack](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L460-L579) and this part of the trace complete disappeared. I suspect that the way we are using MaskViews, or something in the mutators is triggering this code. Unfortunately due to the nature of CATransactions, we can't really follow the callstack directly to see what was triggering it.

I would investigate if a particular mutator is triggering this software rasterization path, and/if this operation is even necessary. After all, these views don't appear to be clipped.

**Comment by jonahwilliams** [comment]
The only mutators being applied are the transform mutator and the cliprect mutator. Visually, it doesn't look like the view is being clipped. Perhaps we have some "just to be safe" clips that need to be removed? or potentially the clip logic is incorrect.

**Comment by jonahwilliams** [comment]
This is coming from the FlutterMaskView:

https://github.com/flutter/engine/blob/266d5d0b5588c1458b7870a14a1f2ccc46a5d931/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm#L292-L304

**Comment by jmagman** [comment]
I'm working on this one.
cc @hellohuanlin

**Comment by jmagman** [comment]
Here's an example of the [mutator stack](https://github.com/flutter/engine/blob/6f8044436eb366b8e5a055a4c4bf22b0642c0b64/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L480) when it's scrolling off the bottom of the screen, and therefore shouldn't be clipped.  [`ClipRectContainsPlatformViewBoundingRect`](https://github.com/flutter/engine/blob/6f8044436eb366b8e5a055a4c4bf22b0642c0b64/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L44) shortcut in this case should be true, and clipping should not happen.  The bounding platform view container in this example is 
```
(const SkRect &) 0x00000002822b53f0 (fLeft = 135, fTop = 1877.05518, fRight = 1035, fBottom = 2627.05518)
```

1. Scale 3x (fTypeMask 18 = scale)
```
(SkMatrix) {
  fMat = ([0] = 3, [1] = 0, [2] = 0, [3] = 0, [4] = 3, [5] = 0, [6] = 0, [7] = 0, [8] = 1)
  fTypeMask = 18
}
```
2. Translate vertically 309 (fTypeMask 19 = translate + scale)
```
(SkMatrix) {
  fMat = ([0] = 3, [1] = 0, [2] = 0, [3] = 0, [4] = 3, [5] = 309, [6] = 0, [7] = 0, [8] = 1)
  fTypeMask = 19
}
```
3. Then clip right and bottom:
```
(const SkRect &) 0x00000002827c9de0 (fLeft = 0, fTop = 0, fRight = 390, fBottom = 741)
```
However at this point `ClipRectContainsPlatformViewBoundingRect` will return false because `(fLeft = 0, fTop = 0, fRight = 390, fBottom = 741)` is not inside the boundary `(fLeft = 135, fTop = 1877.05518, fRight = 1035, fBottom = 2627.05518)`.  So `drawRect` happens.

4. Translate vertically again to 1877.05518
```
(SkMatrix) {
  fMat = ([0] = 3, [1] = 0, [2] = 0, [3] = 0, [4] = 3, [5] = 1877.05518, [6] = 0, [7] = 0, [8] = 1)
  fTypeMask = 19
}
```

5. Translate horizontally 135

```
(SkMatrix) {
  fMat = ([0] = 3, [1] = 0, [2] = 135, [3] = 0, [4] = 3, [5] = 1877.05518, [6] = 0, [7] = 0, [8] = 1)
  fTypeMask = 19
}
```
(End of example).

If instead, the translations were processed all together and then clipped:

1. Concatenated translation of the above scaling and translates:
```
(SkMatrix) {
  fMat = ([0] = 3, [1] = 0, [2] = 135, [3] = 0, [4] = 3, [5] = 1877.05518, [6] = 0, [7] = 0, [8] = 1)
  fTypeMask = 19
}
```
2. Same clip:
```
(const SkRect &) 0x00000002827c9de0 (fLeft = 0, fTop = 0, fRight = 390, fBottom = 741)
```

That would compare the translated platform view rect clip:
```
(SkRect) (fLeft = 135, fTop = 1877.05518, fRight = 1305 ((390 * 3) + 135), fBottom = 4100.05518 ((741 * 3) + 1877.05518))
```
to the bounding platform view container:
```
(const SkRect &) 0x00000002822b53f0 (fLeft = 135, fTop = 1877.05518, fRight = 1035, fBottom = 2627.05518)
```
(for the clip rect to contain the platform view, left and top must be <= and right and bottom must be >=)

And it is inside!  Correctly, no actually clipping happens, and no drawRect.

So if I apply https://github.com/flutter/engine/pull/50386 and https://github.com/flutter/engine/pull/50387 (since I also saw some floating point comparison issues) `drawRect` doesn't happen when the platform view is scrolled off the screen.


To reproduce this:
1. Clone https://github.com/lucalooz/flutter_ads_list_perf.
2. Run app in Xcode.
3. Put a breakpoint in [`FlutterPlatformViews_Internal.mm` `-drawRect`](https://github.com/flutter/engine/blob/eb255c561b1d9f4c40c0c709e8aa03f9cc787e15/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm#L293)
4. Scroll an ad view off the bottom of the screen. 
5. The breakpoint hits.

To reproduce the "fix" of applying all the transforms first:
1. Check out https://github.com/flutter/engine/pull/50386 and https://github.com/flutter/engine/pull/50387
2. Build local engine
3. Run app with local engine, with same `-drawRect` breakpoint
4. Scroll an ad view off the bottom of the screen. 
5. The breakpoint does not hit.

@flar since this is related to the layer state stack, do you know why the mutator stack would look like `scale, translate v, clip, translate v, translate h` when scrolling vertically?  I imagine "process all the transforms first" as I have in https://github.com/flutter/engine/pull/50386 isn't a good idea but I'm not sure what else to try here...

**Comment by flar** [comment]
There is a lot of bad math in those ClipFooContainsPVBounds methods.

transform.mapRect(rect) is conservative which means it may expand the bounds as it transforms them. By that, I don't mean that it can scale the rect, I mean that transforming it produces a new rect that is more than the sum of the original contents transformed. So, it might contain the PV bounds even though the clip doesn't include all of the PV. You have to be more sophisticated in that math.

Second, the way that an RRect is being compared to a rect in different coordinate spaces is very spotty. You can't just transform the bounds of the RRect for the same reasons as I just stated for a Rect and then transforming the corners and attempting to apply them as the corners of the transformed RRect just gets really messy and inaccurate.

That isn't to say that there isn't also a problem with the way that the transform is accumulated, but mapRect is a "padding" operation and you cannot use the "contains" method on its result and assume anything about the original geometries.

**Comment by flar** [comment]
The easiest way to fix the ClipFooContains methods is to do the operation in reverse and by points. This is pseud-code, look up the methods involved and see how they indicate potential problems, like if the inverse fails.

```
  inverse = transform.inverse();
  if inverse fails we can't do the operation, return the conservative answer - false?
  for each corner of the PVBounds:
    mapped_corner = inverse.transform(pv_corner)
    if (rrect or rect does not contain mapped_corner) return false
  done
  return true
```

**Comment by flar** [comment]
Ah, the problem with the ordering is that the clip is installed after a couple of the transform entries, but the PV appears after a few more have been encountered. You need to process the two on the difference of the transforms from where the PV appears and where the clip appears.

So, you have:

transformSetA
clip
transformSetB
PV

It would appear that you have the transformed bounds of the PV that includes both SetA and SetB which is a problem. You can't transform a rect into a rect with any accuracy - the result is conservative. In the case of having transformed PV by both sets, the conservative extra area included in it would at least result in a conservative answer - it might fail to detect the inclusion when it might actually be included. So, you fail to optimize.

Trying to transform the clip means you end up with a rectangle that might think it contains the transformed bounds of PV when it doesn't causing the result to make you optimize when you shouldn't optimize.

The simplest way to fix this would be to take the untransformed PV bounds, the untransformed clip, and then use only SetB in the way that I described above for the ClipFooContains. Unfortunately, if you have multiple sets of transforms and multiple clips, the bookkeeping on that can get tricky.

Another way would be to always keep quads in the destination coordinate space. You start with the PV_transformed_quad which is 4 points. Then each time you encounter a clip you compute its clip_transformed_quad and then test if each PV_quad point is inside the clip_quad points. I don't know if Skia has a "point in quad" method, but it is not hard to write - you can assume that the quads are convex hulls because they came from squares and I don't think there is any way to get our transforms to break that convexity. Then you do "point in convex hull" tests to see if each PV corner is inside the clip quad.

**Comment by flar** [comment]
Hang on, the code is testing if the PV is entirely contained within the clip - which it isn't, so isn't it doing its job. The right answer is "No" as far as this method is concerned.

The case you are looking at is a case where the PV is not even visible on the screen. Of course it isn't "contained" in the clip. But clipping shouldn't happen for a different reason - the PV is gone.

Consider that there are multiple clipping situations:

- object is wholly inside the clip - you can just draw it without a clip
- object is partially inside the clip - you need to use clipping to draw it
- object is completely outside the clip - just don't draw it, no clip is needed if you don't draw it.

You are only checking if the PV is entirely inside the clip and trying to come up with a single true/false answer. You should be returning a tri-state result that the PV bounds are fully visible, partially visible, not visible and compute all 3 answers.

**Comment by jmagman** [comment]
> it's scrolling off the bottom of the screen
> The case you are looking at is a case where the PV is not even visible on the screen. 

I should have been clearer, the platform view is visible on the screen at this point, the bottom of the view is just touching the bottom of the screen, or scrolling beyond it (arrow pointing to bottom of PV)

<img width=400 src="https://github.com/flutter/flutter/assets/682784/c67bfa9f-77f8-431c-a33e-c86f3f2358b1">

> Another way would be to always keep quads in the destination coordinate space. You start with the PV_transformed_quad which is 4 points. Then each time you encounter a clip you compute its clip_transformed_quad and then test if each PV_quad point is inside the clip_quad points. 

Is that another way of saying if `ClipFooContains` was updated to do the inverse by points per your psuedo code instead of `mapRect`, then concatenating the transforms first and using it to process both the PV and clip would be in the destination coordinate space per https://github.com/flutter/engine/pull/50386?

transformSetA
transformSetB
clip
transformSetC
transformSetD

becomes
transformSetA
transformSetB
transformSetC
transformSetD
clip

**Comment by flar** [comment]
> Is that another way of saying if `ClipFooContains` was updated to do the inverse by points per your psuedo code instead of `mapRect`, then concatenating the transforms first and using it to process both the PV and clip would be in the destination coordinate space per [flutter/engine#50386](https://github.com/flutter/engine/pull/50386)?
> 
> transformSetA transformSetB clip transformSetC transformSetD
> 
> becomes transformSetA transformSetB transformSetC transformSetD clip (check against combined transforms for optimized fast path)

C,D are the only transforms that differ between the PV and the clip.

How is the PV bounds specified here? Is it in the device space at the bottom of all of the ABCD? Or is it the raw, untransformed bounds?

Same with the clip? It appears to be the original values handed to canvas.clipRect(), not the transformed version of them.

If, as I suspect, the PV bounds are the device bounds of it, and the clip values are the values that were supplied to the canvas method call, then you must compare the PV device bounds to clip*B*A.

**Comment by flar** [comment]
Think of it this way, C and D are applied after the clip was applied and so they do not affect it. You don't change the clip if you transform after it. You do change how new operations interact with the clip, but the clip is still the same pixels on the screen.

**Comment by flar** [comment]
> 5\. Clip right and bottom:
> 
> ```
> (const SkRect &) 0x00000002827c9de0 (fLeft = 0, fTop = 0, fRight = 390, fBottom = 741)
> ```
> 
> However at this point `ClipRectContainsPlatformViewBoundingRect` will return false because `(fLeft = 0, fTop = 0, fRight = 390, fBottom = 741)` is not inside the boundary `(fLeft = 135, fTop = 1877.05518, fRight = 1035, fBottom = 2627.05518)`. So `drawRect` happens.

The analysis here should be to compare the transformed clip which is
fLeft = 0 * 3 + 0 == 0
fTop = 0 * 3 + 309 == 309
fRight = 390 * 3 + 0 == 1170
fBottom = 741 * 3 + 309 == 2223 + 309 == 2532

So the PV device bounds of (135, 1877, 1035, 2627) are being tested to see if they are inside the device bounds of the clip at (0, 309, 1170, 2532).

PV left is inside clip left - contained
PV top is below clip top - contained
PV right is inside clip right - contained
PV bottom is below clip bottom - NOT contained

The problem is probably that the clip ends at the bottom of the screen(?), but the PV has been translated down to hang off the edge below that. When the PV is partially off the screen, it would not be contained within a clip that I think is likely computed to be within the bounds of the screen. (Note: Need to double check where this clip is coming from to confirm my suspicion that it is clipped to the bounds of the screen)
