### ISSUE TITLE
[RFW] Allow RFW local and remote widgets to declare their own library membership

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#142898]
Curious about your thoughts on this proposal, @Hixie , and how you arrived at the existing design. I'm sure there are downsides to the below that I haven't thought of! I'm hoping to find some strategies for my actual problem (trying to build a robust RFW ecosystem with multiple apps and shared widgets) that work elegantly with RFW as-is.

## Background

RFW widgets are identified in the Runtime by the name of the widget, and the name of the library that they are a member of. The name of the widget is declared in the .rfwtxt file for remote widgets, and in the binding code for local widgets. This means that the dependency of a remote widget on a local widget, or another remote widgets, is formed by both the widget definitions/bindings themselves, and then `Runtime.update(libraryName, library)` calls.

I want to build an ecosystem of local widgets, remote widgets and apps (e.g. Runtime configurations) checked into the same repository, which have fixed dependency relationships between each other. By fixed, I mean that when a Remote Widget definition imports and uses another widget (remote or local), there is no ambiguity about which widget definition in the repo it is referring to. I think having these clear relationships has a few benefits, e.g.:

- Avoid inconsistent configuration of Runtimes between apps, which affects the ability to share remote widgets. E.g. app A registers a shared remote widget `Foo` in library `some.library` while app B registers it as `another.library`. Then app A implements `Bar` which depends on `Foo` and references it as `some.library.Foo`. Now app B wants to start using `Foo` also, but it doesn't work without updating the configuration, because in app B, `Foo` is registered in the `another.library` library.

- You can test a remote widget with all its dependencies, and be reasonably certain that all uses of this widget in different apps with different Runtime configurations, will at least provide the same dependency implementations. For example, if `Foo` remote widget depends on `Bar` remote widget implemented in `bar.rfwtxt` and is tested with it, we know apps will always use the same `Bar` implementation in `bar.rfwtxt`, not the alternative one in `bar_2.rfwtxt`. Of course, this kind of guarantee also requires certain build and deployment infrastructure, and there's a limited ability to prevent incompatibilities between remote and local widgets, seeing as each remote widget will certainly be working with slightly different local widget libraries and implementations across different app versions. But having very clearly defined dependency relationship helps with this issue.

I'd prefer to think of the dependency relationships on the granularity of widgets rather than libraries, because that's the most flexible structure, and it means that developers don't need think about how to group widgets into libraries based on unknown future use cases.

One way of achieving all of this with the existing structure of RFW is to think of every widget as being in its own library, and keeping shared library registration code alongside each widget definition, or code generating it based on build system information. E.g. something like:

```dart
void updateRuntimeForFoo(Runtime runtime) {
        runtime.update(
          _runtime.update(LibraryName(<String>['some.library.foo']), await fetchFooWidget());
        );
}
```

Though this is a little messy because now we need to add this code for each widget, and to depend on a widget, you still need to consult the widget binding and library update code.

## Proposal

With this approach to managing widget dependencies, it seems like it would be simpler for each widget definition or binding to declare its library membership as part of the definition.

### Remote Widgets

For remote widgets we could follow Dart's library declaration approach and add support for `library` declarations:

```dart
library my.library;

import core.widgets;

widget Foo = ...
```

This could be made backwards compatible (though awkwardly) by allowing the library name to defined either in the source *or* when loading the library. Using neither or both approaches would be an error.

The remote widget approach could be built as an extension by making the library declaration a code comment in .rfwtxt sources that is only read by some codegen build infrastructure. But this is more confusing than making it part of the language.

### Local Widgets

For local widgets, we can require the fully scoped name to be declared at registration time:

```dart
Map<String, LocalWidgetBuilder> get widgets => <String, LocalWidgetBuilder> {
  ScopedWidgetName('Foo', ['my', 'library']): (BuildContext context, DataSource source) {
    return Foo(
      children: source.childList(['children']),    
        );
  },
}

runtime.updateLibraries(librariesFromLocalWidgets(widgets))
```

I think the above local widget registration API could be built completely as a wrapper to RFW that groups a flat list of bindings into libraries.

**Comment by Hixie** [comment]
The design of RFW assumes a single runtime (RFW host app) is targeted by any particular RFW content. That runtime defines the structure of the data (including host-provided data and the root keys for any remote-provided data), the available local libraries, any conventions regarding event handling, any integration with code push solutions (like integration with a Wasm or JS runtime), and the mechanism for obtaining the remote widget and remote data descriptions. Essentially, RFW is a rendering engine to be used to create a runtime, not a runtime environment itself.

Given those assumptions, there's not much benefit to having the remote libraries give their own names (because any such mechanism can just as easily be a convention provided by the host, e.g. having the host receive the RFW binary data in a packet whose header gives the library name), and there's no benefit to the local libraries having their own fully-qualified names (because that's essentially indistinguishable from the current mechanism).

That's how we ended up at the current design.

I think if we want a world where remote flutter widget libraries target multiple runtimes, we're going to have to do a lot more than make the libraries have consistent names. For example, we'd have to define a standard data structure in which the local data (like the time, screen size, username, etc) would be provided; we'd have to define the precise set of local widgets that are to be made available, we'd have to define how event handlers are set up, etc. That's all fine, but I think it is a layer above RFW, not RFW itself.

If you think about this by analogy to JavaScript (or other scripting environments), there's the core runtime, and then there's the set of available system functions. Browsers implement one environment. Node.JS implements another. Game engines provide yet another. The JavaScript runtime itself doesn't have to know about all these environments, it just provides the core JS runtime. RFW is similarly just that core runtime.

Let me know if I misunderstood the problem being described.

**Comment by stuartmorgan** [comment]
@Hixie Do you want to triage this with a priority?

**Comment by jacobsimionato** [comment]
Thanks for the consideration of this problem and the thoughtful response, Hixie.

I agree this is a question of layering and what is RFW's responsibility vs other layers on top. It's true that conventions / structures / checks around library naming can be handled by a layer on top of RFW and the name can be conveyed from server to client by a separate header etc.

I think the responsibility of the .rfwtxt language in a layered system is to provide a simple way to express remote widget layouts. Expressing dependencies between remote widgets defined in different files falls within that responsibility. Allowing .rfwtxt files to declare their own library membership is more intuitive when working with components implemented across multiple files, because it is more consistent with other languages, and it means the developer only has to look at the dependency .rfwtxt to understand how to refer to it in another file, rather than also looking in a second place (the RFW Runtime configuration in Dart code).

That said, this is just an argument about ergonomics, and it doesn't seem very clean to add this feature to RFW in a backwards compatible way, so maybe this bug can be considered a feature request for any future alternative RFW format (.rfwdart?) etc. What do you think?

Re the shared remote widget library use case: Based on the ecosystem that exists around other server-driven UI frameworks at Google, I don't think it's necessarily an obscure use case, and many of the concerns that you mentioned can be alleviated by only depending on an older version of the core and material widgets and accepting data and event handlers as arguments only, rather than hard-coded references to the data model. A surprising amount can be achieved with the core and material widgets that are already available, and it's desirable to build new shared components as remote widgets instead of local widgets wherever possible so they can be shipped to older client versions and don't contribute to the inevitable variation in client capabilities.

**Comment by Hixie** [comment]
It would be relatively straightforward to wrap RFW with a very thin shim layer that essentially pulls the name out of the file when passing it to the RFW runtime. That is, instead of:

```dart
_runtime.update(const LibraryName(['main']), decodeLibraryBlob(await currentFile.readAsBytes()));
```

...you could do something like:

```dart
var bytes = await currentFile.readAsBytes();
var length = bytes[0];
var name = utf8.decode(bytes.skip(1).take(length));
_runtime.update(LibraryName([name]), decodeLibraryBlob(bytes.sublist(length + 1)));
```

(A production version would use a more efficient approach and might support dotted names or whatever.)

Or you could subclass `Runtime` to create a new method that calls `update` but takes just the bytes and pulls out the name itself, or something. I think it would be reasonable to create a package that does exactly that.

You wouldn't want package:rfw to do this automatically because that would force certain semantics in a way that would be harmful for certain use cases. For example, a client that was handling untrusted RFW input would need to be able to quarantine the libraries it imports and would not want any confusion about whether an RFW file is allowed to provide the name itself. Similarly, environments that have filesystems may want to take the library's name from the file's name rather than trusting whatever is in the file.

All of which is to say, I think this isn't a feature we should add to RFW, but I think the existing package easily supports adding this feature on top in a reusable way for those ecosystems that want to go down this route.

**Comment by jacobsimionato** [comment]
This all makes sense - thanks for the discussion and advice. We can add this behavior as a layer on top of RFW if it is worthwhile to us.
