### ISSUE TITLE
Provide a simple way of removing scroll effects

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#142883]
### Use case

I don't what my ListView to stretch the content on Android.

### Proposal

Right now to achieve this, I need to wrap the ListView in a ScrollConfiguration, and provide a custom override class to change the behavior.

This is way too much clutter for a "configuration" of a very basic behavior. I shouldn't have to create descendants classes of the child of a configuration class to just change the behavior of a ListView.

Please provide a much simpler alternative to the following code :

```dart
class NormalScrollBehavior extends ScrollBehavior {
  @override
  Widget buildOverscrollIndicator(BuildContext context, Widget child, ScrollableDetails details) => child;
}

class MyListView extends StatelessWidget {
  const MyListView({super.key});

  @override
  Widget build(BuildContext context) {
    return ScrollConfiguration(
      behavior: NormalScrollBehavior(),
      child: ListView(
        children: [
          // children
        ],
      ),
    );
  }
}
```

Why not have something as simple as the `physics` argument to the ListView constructor ? This makes things infinitely more readable.

```dart
class MyListView extends StatelessWidget {
  const MyListView({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      behavior: NormalScrollBehavior(),
      children: [
        // children
      ],
    );
  }
}
```

Edit : NestedScrollView already has this.

**Comment by Piinks** [comment]
Hi @TheCarpetMerchant you do not need to create a subclass `NormalScrollBehavior`, `ScrollBehavior` and its subclasses `MaterialScrollBehavior` and `CupertinoScrollBehavior` already have a convenience method for disabling different effects. You can also set the scroll behavior for the entire app rather than adding ScrollConfigurations above individual Scrollables.

```dart
class MyListView extends StatelessWidget {
  const MyListView({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      behavior: MaterialScrollBehavior().copyWith(overscroll: false),
      home: ListView(
        children: [
          // children
        ],
      ),
    );
  }
}
```

> Edit : NestedScrollView already has this.

This is because NestedScrollView overrides some aspects of the inherited ScrollBehavior by default internally, so it is exposed on NestedScrollView to give users control that would not be possible with ScrollConfiguration. ListView and others do not override the behavior internally so do not have it exposed.
