### ISSUE TITLE
SkiaPerf movement related to submitting multiple command buffers

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142992]
On https://github.com/flutter/flutter/commit/1f573e022e0f255bf43e0526713b69d0901b083a, there is some movement in a number of benchmarks. The commit in that roll that looks related to me is https://github.com/flutter/engine/pull/50180, which caused similar movement on a prior land/revert.

@jonahwilliams Could you take a look?

https://flutter-flutter-perf.skia.org/e/?begin=1705570686&end=1707234104&keys=X943ef1874c8228e3dda788af549925c0&requestType=0&xbaroffset=39074

https://flutter-flutter-perf.skia.org/e/?begin=1706648107&end=1706673690&keys=Xde34077be0c0ea195a5027b0f4d8c823&num_commits=50&request_type=1&xbaroffset=39083

https://flutter-flutter-perf.skia.org/e/?begin=1705608310&end=1707234104&keys=X091502ff91dd7b6844699fade37466dc&requestType=0&xbaroffset=39083

**Comment by jonahwilliams** [comment]
Thanks @zanderso 

The frame_request_pending_latency was added to test https://github.com/flutter/engine/pull/43711 and its not clear to me that it is a meaningful number to target for Impeller. I think conceptually we want this number to be less. Because the animated advanced blend benchmark is submitting a lot of cmd buffers, it might be the cast that we should not batch as heavily and submit throughout the frame. That said, I don't really want to add heurstics here unless we have a better example than a micro benchmarks.

The second shows a slight increase in build time. That might be due to more work getting scheduled towards the end of the frame, and perhaps that is slightly overlapping with ui work? it seems small.

The last one shows a nice drop in an app that is submitting multiple command buffers.

**Comment by zanderso** [comment]
Thanks for looking! Feel free to close if there's nothing actionable here.

**Comment by jonahwilliams** [comment]
ack ack!
