### ISSUE TITLE
The initialLocation propert nolonger accepts  _previousRoute.location

### ISSUE THREAD

**Issue by Trv6775** [flutter/flutter#142902]
I am not sure what the "root widget" in your setup means @lucavenir, but here you go: **https://dartpad.dev/0a77fd6105aeee44858b794e17e83ffc**  
This is a full setup using my `riverpod` + `go_router` approach.

Here is an in-depth showcase 💯  Here we have (sound on 🔈)..

https://user-images.githubusercontent.com/19204050/194175676-3c4b94b6-fad8-4999-a94a-7a54701211fb.mp4

Note that the `MaterialApp` itself also does not rebuild internally because it does not change. So it is mainly the `App.build` call, which is very cheap.

_Originally posted by @creativecreatorormaybenot in https://github.com/flutter/flutter/issues/112915#issuecomment-1269053217_

**Comment by creativecreatorormaybenot** [comment]
I am not sure what this issue is trying to accomplish - as is, it is a copy-paste of my comment (as linked). What I describe in my comment, however, is a solution rather than an issue.

**Comment by danagbemava-nc** [comment]
Hi @Trv6775, when filing an issue, please provide all the information required so that the issue can be properly investigated. Do not file issues with comments from other issues without any context. 

Closing since no information has been provided. 

Please file a new issue and provide all the relevant information required to investigate it.

Thank you
