### ISSUE TITLE
Flutter Google Map not showing country based content in IOS devices.

### ISSUE THREAD

**Issue by salman0017** [flutter/flutter#142908]
### Steps to reproduce

1. Set the application locale to Morocco (ar_MA, fr_MA).

2. Observe that Google Maps displays the Western Sahara region, contrary to the official Google Maps that excludes this region.

3. Note that there is no option available in the Google Maps widget to set the locale and region

This issue indicates a discrepancy between the localized version of the app in Morocco and the official Google Maps, where the Western Sahara region is incorrectly displayed. Additionally, the absence of an option in the Google Maps widget to adjust the locale and region exacerbates the problem.

### Expected results

I want to present a Google Map based on Morocco to the user, where Morocco and Western Sahara are not depicted as separate regions.

### Actual results

Google Maps displays Morocco and Western Sahara with distinct boundaries.

### Code sample

<details open><summary>Code sample</summary>

```dart
return GetMaterialApp(
  // theme: ThemeData(
  //     useMaterial3: true, colorSchemeSeed: const Color(0xff6750a4)),
  initialBinding: CommonBinding(),
  supportedLocales: [
    Locale('en', 'US'),
    Locale('en', 'MA'),
    Locale('ar', 'MA'),
    Locale('fr', 'MA'),
    Locale("he", "IL"),
    Locale("ar", 'IL'),
    Locale("hi", 'IN'),
    Locale("kn", 'IN'),
    Locale("es", 'PR'),
    Locale('fr', 'FR'),
  ],
  localizationsDelegates: [
    CountryLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ],
  builder: (context, child) => MediaQuery(
      data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
      child: child!),
  translations: LocaleString(),
  locale: AppUtil.appLocale,
  debugShowCheckedModeBanner: false,
  title: AppString().appName,
  theme: AppTheme.lightTheme,
  home: Home(),
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/97174419/80ce6c8a-dcde-4042-9f0d-33b83324af1e)
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
> 1. Set the application locale to Morocco (ar_MA, fr_MA).

Flutter locales do not have any effect on native content in platform views, such as Google Maps. See https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#localizing-for-ios-updating-the-ios-app-bundle for information about localizing native content.

**Comment by huycozy** [comment]
@salman0017 I compared your screenshot with [Google Maps](https://www.google.com/maps/place/Morocco/@27.8515386,-2.8573303,5.11z/data=!4m6!3m5!1s0xd0b88619651c58d:0xd9d39381c42cffc3!8m2!3d31.791702!4d-7.09262!16zL20vMDR3Z2g?entry=ttu) but they looks similar:

![Screenshot 2024-02-06 at 15 33 42](https://github.com/flutter/flutter/assets/104349824/a76c0ac0-4f83-4d46-b272-560d7624e9bf)

Could you share Google Maps result on your end? And could you also highlight distinct boundaries?

**Comment by stuartmorgan** [comment]
> 3\. Note that there is no option available in the Google Maps widget to set the locale and region
> 
> [...]
> I want to present a Google Map based on Morocco to the user, where Morocco and Western Sahara are not depicted as separate regions.

The plugin on iOS is just wrapping [the Google Maps iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/overview). Could you provide a link to the specific API options there that you want access to in the plugin?

**Comment by nextsimo** [comment]
Hi Same here 
I'm developing a Flutter app targeting users in Morocco and have integrated the Google Maps SDK for iOS using the google_maps_flutter package (version ^2.5.3). Recently, I've noticed that the map displays geopolitical boundaries that incorrectly segment Western Sahara from Morocco, which does not align with the official Moroccan representation of its national territory.

This issue is crucial for my user base in Morocco and potentially impacts the app's reception and usability. The problem appears specifically on iOS, whereas for web implementations, I can use the region=ma parameter to address similar concerns.

Is there a known workaround or setting within the Google Maps SDK for iOS that allows for the adjustment of geopolitical boundaries displayed, similar to the region parameter for web? Any guidance or suggestions on how to ensure the map reflects the full territorial integrity of Morocco as recognized by its government would be greatly appreciated
