### ISSUE TITLE
Can i change crop selection color?

### ISSUE THREAD

**Issue by Hrmndeepvirk** [flutter/flutter#143065]
how to change crop box color from white to black while cropping the image?  cropFrameColor and cropGridColor doesn`t work in my case.

**Comment by dam-ease** [comment]
Hello @Hrmndeepvirk 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.

If you are proposing a change, this seems to be related to the `image_cropper` package, please use the appropriate new issue template in the repo and fill out the requested details.
