### ISSUE TITLE
[Feature] Simpler Alternative to Federated Plugins, based on Platform Channels

### ISSUE THREAD

**Issue by chipweinberger** [flutter/flutter#143095]
### Use case

The same use case as Federated Plugins. Allow 3rd party plugins to add support for additional platforms to the original plugin.

----

Federated plugins have some drawbacks: 
1. parent project must be proactively organized in a very specific way, overhauling project structure
2. it introduces additional levels of abstraction, more filesystem depth, a "platform interface"

These slight drawbacks cause some packages to choose to forgo federated plugins, making them impossible to extend without forking.

### Proposal

Platform Channels already offer a very convenient api boundary to add additional platform support. 

There should be a way to leverage Platform Channels to add support for new platforms, without requiring federated plugin structure.

**Admittedly, my proposal might not be the best one to solve the use case. But here it goes:** 

users would add additional platforms like so:

**pubspec.yaml (end user's app)**
```
dependencies:
  flutter_blue_plus: 1.31.7
  flutter_blue_plus_windows: 1.0.0
```

**pubspec.yaml (in flutter_blue_plus_windows)**
```
extends: flutter_blue_plus ^1.3.7
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterBluePlusPlugin
```

In this case, `flutter_blue_plus_windows` contains a `/windows` directory that will be copied into `flutter_blue_plus`. If `flutter_blue_plus` already contains the same files, the files will be overwritten. `flutter_blue_plus_windows` can be thought of as a "patch".

The platform channel will forward messages to the windows code, as expected.

**Comment by stuartmorgan** [comment]
What you have put under "Use Case" is a complaint about a current implementation, not a use case, and what you've put under "Proposal" is essentially a use case. What is the actual proposal here?

> parent project must be organized in a more annoying way, with more levels of abstraction

The abstraction exists to allow alternate implementations.

> There should be a way to augment a project with more code, to add support for more platforms.

This is the use case that led to the design and deployment of the federated plugin model.

> The parent project can be setup in any way.

Please describe a system that allows adding implementation logic into a project that has arbitrary design, including describing how it would handle changes to the arbitrary design of the parent project without breaking all implementations.

>     merge: flutter_blue_plus
>     conflicts: overwrite

Please provide a detailed explanation, with example code, of what this syntax would actually do.

**Comment by chipweinberger** [comment]
Thanks for the reply @stuartmorgan ! 

I've added additional comments and revised my original post for clarity.

**Comment by chipweinberger** [comment]
> To what end? 

The goal is to add support for windows to a package that chooses not to support federated plugins. 

> At this point, you have flutter_blue_plus with an inert windows/ directory.

Right. `flutter_blue_plus_windows` would need to specify which platforms it adds support for in its `pubspec.yaml`

----

Without going too far down the details @stuartmorgan , can you share your thoughts on the use case?

**Comment by stuartmorgan** [comment]
> > To what end?
> 
> The goal is to add support for windows to a package that chooses not to support federated plugins.

I understand your goal; I am asking how your proposal of copying a `windows/` directory into another package achieves that goal. By itself, a `windows/` directory doesn't do anything.

> > At this point, you have flutter_blue_plus with an inert windows/ directory.
> 
> Right. `flutter_blue_plus_windows` would need to specify which platforms it adds support for in its `pubspec.yaml`

Okay, but then what? What is the mechanism by which someone calling a public method of `flutter_blue_plus` ends up running code from the `windows/` directory of `flutter_blue_plus_windows`? Not in terms of your proposed syntax for pubspec or the like, but the actual *implementation* of that calling.

> Without going too far down the details @stuartmorgan , can you share your thoughts on the use case?

Assuming you mean the current, updated iteration of the use case, which I will quote here since having the things I am referring back to constantly changing after the fact makes following any kind of discussion here quite difficult:

>> Augment existing packages that choose not to support federated plugins.

That's now a combination of use case and specific proposal, in that you are saying you want to address a use case (adding support for new platforms to someone else's plugin) while adding the implementation caveat that the solution must not use *the solution that was designed for that exact use case*.

At the point where you are saying you want to start from the same premise, but get a different result, I don't see how we can do anything other than focus on the details. The details are all that would distinguish your proposal from what we already built.

The next step here would be [a design document](https://github.com/flutter/flutter/wiki/Design-Documents) that clearly describes your proposal, with specific details that address the questions raised so far about how this would work, so that the proposal can be discussed and evaluated in a format that's better for that kind of discussion than a linear thread.

**Comment by chipweinberger** [comment]
> That's now a combination of use case and specific proposal, in that you are saying you want to address a use case (adding support for new platforms to someone else's plugin) while adding the implementation caveat that the solution must not use the solution that was designed for that exact use case.

Sure. Thats reasonable. In the end it is the same use case. 

Federated Plugins require too much project structure overhaul to solve that use case, I'd argue. Or perhaps this is all mostly semantics.

> The next step here would be [a design document](https://github.com/flutter/flutter/wiki/Design-Documents) that clearly describes your proposal

Thanks for the link. I'm familiar. Wanted to brainstorm with the community first =) 

Thanks for the discussion.

**Comment by chipweinberger** [comment]
Maybe there is actually no need for this.

Platform channels already have names. 

A 3rd party plugin could just initiate the platform channel with a name that "is not theirs".

For example, **flutter_blue_plus_android** could implement the `flutter_blue_plus/methods` platform channel.
```
    @Override
    public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding)
    {
        methodChannel = new MethodChannel(flutterPluginBinding.getBinaryMessenger(), "flutter_blue_plus/methods");
        methodChannel.setMethodCallHandler(this);
    }
```

I think this would "just work".

**Comment by stuartmorgan** [comment]
> I think this would "just work".

Only to the extent that the author of the new platform support didn't care:

- that their implementation would be subject to breakage without warning in *any* release of the main plugin, and they would thus need to both instruct all of their clients to pin an *exact* version of the main plugin, and manually validate every single PR to the main plugin before updating that suggested pin (at which point they are doing basically the same work as would be involved in a fork, but also exposing all of their clients to more complexity than a fork would), and
- is willing to write their entire implementation entirely in the host language; notably, [the actual implementation of your example case of `flutter_blue_plus_windows`](https://pub.dev/packages/flutter_blue_plus_windows) is written entirely in Dart, and doesn't even have a `windows/` folder, so this proposal would not have worked for the only actual example of someone trying to do the thing that presumably prompted the filing of this issue.

> I've never seen anyone do this however.

There are examples of third-party embedding authors doing this, but even in their more constrained use case (e.g., their implementations aren't distributed on pub.dev, so it's easier to set different expectations on the limitations) it's very fragile. Many of the ones I'm aware of have been broken at various times.

**Comment by chipweinberger** [comment]
Yes, those would be the restrictions. In `flutter_blue_plus_windows`'s `pubspec.yaml` they would specify the _exact_ `flutter_blue_plus` version it is compatible with.

**Comment by stuartmorgan** [comment]
> To prevent breakage, `flutter_blue_plus_windows`'s author should specify the _exact_ `flutter_blue_plus` versions their code is compatible with in their `pubspec.yaml`
> 
> ```
> name: flutter_blue_plus_for_windows
> description: windows support for FlutterBluePlus
> version: 1.0.0
> 
> dependencies:
>   flutter_blue_plus: ">=1.29.0 <1.40.0"
> ```
> 
> It's worth noting that FBP is pretty stable at this point.

[This commit](https://github.com/boskokg/flutter_blue_plus/commit/b306e48a2710a82a366c9e7dfb8372b2e141798f#diff-c26955b39758f44a74e03cfff368d1b9e40f737763283adfcf613fd8737e2ba7L289) is in the range you gave, and would at best break anyone using the system you are describing, and more likely crash. And yes, you could edit the comment to a different range that's correct, but this has already demonstrated a serious problem with this approach: you, as the person with the most context, still got this wrong *immediately*. The chances that other people with less context would get it right constantly, in perpetuity, is extremely low.

And this is only one of the problems. The inability to use Dart discussed above is another, version lock is another, increased volatility of the API surface is another, and there are more. All of which received a lot of thought and discussion by people with significant expertise in the package ecosystem, and the result is the platform interface model. I would encourage you to apply the principle of Cherston's Fence as here; federation isn't set up in what you describe as "a more annoying way, with more levels of abstraction" because the Flutter team wanted to add annoyance and abstraction for no reason.

**Comment by chipweinberger** [comment]
that specific range was just made up randomly...
