### ISSUE TITLE
Automatically add up-to-date screen shots to the dartdocs for widgets

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1433]
_From @sethladd on November 6, 2015 17:11_
- [ ] on the homepage
- [ ] in the widget gallery
- [ ] in the tutorial, showing what each snippet should look like

_Copied from original issue: flutter/website#53_

**Comment by FlutterIssues** [comment]
_From @HansMuller on November 6, 2015 18:8_

Yes! To the widget gallery http://flutter.io/widgets/

For many of the basic widgets, diagrams would be helpful.

**Comment by eseidelGoogle** [comment]
Pretty simple on Android:
http://blog.shvetsov.com/2013/02/grab-android-screenshot-to-computer-via.html

I've considered adding a `flutter screenshot` command to make this even easier.

The flutter tools depend on the imobiledevice library already, which includes `idevicescreenshot` to make it possible to pull screenshots from an iOS device as well.

**Comment by eseidelGoogle** [comment]
Do we plan to complete this for next Tues?

**Comment by Hixie** [comment]
Here's a proposal:
- [ ] Write an application that showcases each widget with a simple code snippet, a description, and an o-screen representation.
- [ ] Make that application display each such showcase in turn, and with each one output to the console a marker.
- [ ] Have a script watch the console, and call `adb screenshot` each time the marker is seen, saving the screenshot in a predictable way.
- [ ] Have a script bring together the code snippets, descriptions, and images and output a markdown file that contains the whole shebang.
- [ ] Upload that to the Web site.
- [ ] Once we have a way to run automated tests on the bots, have this whole thing play out with each change, so that the screenshots are always up to date.

**Comment by Hixie** [comment]
cc @qchong 

This is the bug I was thinking of that talked about having bots automatically generate screen shots and uploading them so that the documentation could have continually-updated pictures of the widgets.

**Comment by tvolkert** [comment]
FYI, now that https://github.com/flutter/flutter/issues/6774 is done, this should be much more feasible.

**Comment by Hixie** [comment]
@HansMuller Is this something you could hook up to your screenshotting script?

**Comment by Hixie** [comment]
Work on this continues. I'll leave the bug open so we can celebrate once it's done, but we have no specific ETA.

**Comment by Hixie** [comment]
cc @gspencergoog

**Comment by Hixie** [comment]
Going to close this now that we have live previews which is even better.
