### ISSUE TITLE
Connected device (the doctor check crashed) error

### ISSUE THREAD

**Issue by rusiruerandaka** [flutter/flutter#143456]
### Steps to reproduce

when i enter flutter doctor command there is an error like this " Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe"
      
      How can i fix it?

### Actual results

There is an error when i enter flutter doctor command
![WhatsApp Image 2024-02-14 at 21 20 32_e4a73be0](https://github.com/flutter/flutter/assets/124586352/4d0b070d-3b27-4924-8e9e-e4bf0f28adf7)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @rusiruerandaka, it looks like your `ANDROID_SDK_ROOT` environment variable points to your adb executable. Can you fix it to point to the `platform-tools` directory instead of the `adb` executable and try again to see if you still get the issue? ie
your `ANDROID_SDK_ROOT` environment variable should point to `C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools` instead of `C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe`
