### ISSUE TITLE
Create a backwards compatible solution for M2

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#143499]
### Document Link

[Design doc](https://docs.google.com/document/d/1REsg982YG2MlspsMOiNLpu8OIWkyehRRQUXHMU3tAAM/edit?usp=sharing) (flutter.dev/go link pending)

### What problem are you solving?

Material Design has been through several iterations, and will continue to evolve. Flutter aims to support the latest spec, but does not want developers depending on prior versions to be left behind.

This is proposing the `legacy_material` package to support these developers, clearing the way to better maintain the material library, and allowing it to continue to evolve.

_TODO(me): Expand this into an umbrella issue listing all components we need to support so we can track their status._

**Comment by rydmike** [comment]
Thanks @Piinks for this proposal. I like this idea as lot. I also see an opportunity to combine it with: 

* https://github.com/flutter/flutter/issues/139338

I also think the prerequisites for it, with exposing the needed props in `ThemeData` to be able to deliver this package, is also very important. I commented more on that and why in the design document.  

The [design document](https://docs.google.com/document/d/1REsg982YG2MlspsMOiNLpu8OIWkyehRRQUXHMU3tAAM/edit) introduces `LegacyThemeData` as a package called `legacy_material`. In the design doc a question is also raised about how it should work when eventually M3 is replaced with M4?

I think the design could also consider such future needs, as well as the neutral Material theme  proposal. There is an opportunity here to in its design include the possibility to add more designs, than just one legacy version. Maybe then also consider naming it `TemplateThemeData` and e.g. `template_material` package.

We could then add as many different template material styles to the package as needed over time. Some examples:

* `TemplateThemeData.m2` - Legacy M2 themed Material Design widgets.
* `TemplateThemeData.neutral` - Neutral platform agnostic themed Material Design widgets.
* `TemplateThemeData.iOS` - iOS like themed Material Design Widgets.
 
The idea of the `TemplateThemeData.iOS` would **not** be to make Material widgets work and look exactly like the high fidelity Cupertino widgets. Only to make them fit better design wise, out of the box, on the iOS platform. They are often used by Flutter devs on iOS and always have to be styled to fit better. For full fidelity you would still need to use Cupertino or platform adaptive widgets. But even if you use Cupertino, if and when you include some Material widgets, they would fit better with the theme applied.

One could also argue that `neutral`, could be designed to fit on iOS. The Apple HIG is pretty neutral. The proposal above does not yet define exactly what the "neutral" spec should be. It could of course "by coincidence" be the border radius and opacity based press/focus/highlight style used on iOS, as it is pretty "neutral" already. However, some might disagree and want an even more "neutral" starting point option.

Another consideration could be to also allow 3rd parties to deliver and maintain theme configurations for `TemplateThemeData`. We could e.g. get things like:

* `TemplateThemeData.windows` - Windows themed Material Design widgets
* `TemplateThemeData.macOS` - macOS themed Material Design widgets
* `TemplateThemeData.shadcn` - [Shadcn](https://ui.shadcn.com/) themed Material Design widgets

Again, those themes would not be high-fidelity platform designs, like e.g. packages [fluent_ui](https://pub.dev/packages/fluent_ui) and [macos_ui](https://pub.dev/packages/macos_ui). They would only be intended to make Material widgets look less alien when used on mentioned platforms or together with other 3rd party designed widgets, like the mentioned packages.
  
Since all this is just `ThemeData` we can also easily use these themes to let multi-platform Flutter apps get platform adaptive `ThemeData`. Only check platform and setup the correct `TemplateThemeData` for the platform. It will not be exact platform components, but the app would look much more at home on each platform, with minimal effort. Once reasonable themes for all platforms exists, a convenience `TemplateThemeData.adaptive` constructor could also be added.

I have already used this platform adaptive theme design idea manually, and to some extent also via my package [flex_color_scheme](https://pub.dev/packages/flex_color_scheme) that offers some platform adaptive theme styling options out of the box. 

It works well and helps with removing things from Material Design widgets (especially M3 defaults, that is very opinionated) that look very out of place on none Android platforms. It is not perfect, but it can really make your app look more at home on other platforms. Plus you  get all this with no effort needed on Material widget styling and custom widget wrapper or platform adaptive widgets. It is all done via theming, yes I kind of like that 😄 

And of course later, when someday M4 arrives and M3 becomes obsolete we can add:

* `TemplateThemeData.m3` - Legacy M3 themed Material Design widgets.

Anyway, this was just some rough ideas around this concept 😄 💙 

Thoughts?

**Comment by bernaferrari** [comment]
Interesting, but I would name the Theme like LegacyMaterial2, because eventually Material 3 will be legacy too.

**Comment by rydmike** [comment]
Yes, the naming can of course be whatever is desired. In the above concept idea you can just as well call it:

* `TemplateThemeData.legacyM2`

and later add

* `TemplateThemeData.legacyM3`

When the default one in the SDK uses **M4**.

I just think it would be a missed opportunity to not also consider the usefulness of using a solution and package like this, for other high quality and generally useful `ThemeData` templates as well.

**Comment by benthillerkus** [comment]
At that point why not move material entirely into a separate package and have M2 as 2.x.x releases and M3 as 3.x.x releases?

**Comment by rydmike** [comment]
@benthillerkus, moving the entire Material library out of the Flutter SDK is an almost hopeless ask and task at this stage. Much bigger than just having a package with some nice useful predefined `ThemeData` constructors for different styles, be it `legacyM2` or `neutral` or whatever that might be considered for inclusion. 

Having Material and Cupertino as external libraries has been discussed and suggested many times, but it is not on any current roadmap.

### Side benefits of `legacyM2` as `ThemeData`

To be able to support `legacyM2` design as just `ThemeData`, also requires a bit of work. It is not possible to only make the **M2** component theme defaults. Those already exist already and can be copied, but it will only get you "close" but exactly there. Of course the needed fidelity level can also be discussed. Does it need to be exact? What is close enough?

Why is it not enough for an exact match? Because many of the needed props do not exist on theme level, only on widget level. Some of the needed styling props are even internal to the widgets' and not exposed at all. These must be  added as theming props, and also widget props if not there already, to keep parity between theme and widget prop styling capabilities. 

All this is touched upon in the design doc as well. Many widgets hide some implementation details and behavior in the Widget, that cannot be replicated with only theming. Some of them can with Widget props, but some some hide details on widget level too. 

The `Switch` is a good example of this:

- https://github.com/flutter/flutter/issues/131478

Here are some more examples of where you cannot drive things with themes only, since using a theme for some properties either kills some variant widget styles. Theming the variants is not supported by themes, but styling them is supported by widget props:

- https://github.com/flutter/flutter/issues/131690
- https://github.com/flutter/flutter/issues/123829
- https://github.com/flutter/flutter/issues/118063
- https://github.com/flutter/flutter/issues/107946

Supporting variant styles either requires separate themes for each variant or a solution along the discussion here https://github.com/flutter/flutter/issues/107946#issuecomment-1193422262

This was just some examples of theming that needs to be improved to support `legacyM2` as just `ThemeData`. It is worth noting that fixing these theming limitations, would also fix many other issues and limitations in theming and Flutter widget styling, that are frequent complaints and pain points.

In my opinion, every time a Material widget has widget props that include styling we cannot replicate with its component theme, we diminish the usefulness of Flutter's theming. Many devs then feel that since some props cannot be changed with themes, they might as well just as use widget style wrappers for everything.

And when widgets have internal styling features not exposed at all, the complaint is. Why not expose these props? So we can use the already existing widget, instead of making our own version to fix/access a needed property.

This work may actually bring some nice benefits in increased configuration and flexibility of existing Material widgets as well. The addition of Material3 support to Flutter's Material widgets already did this to some extent. The widgets and themes are now much more flexible and configurable than they were originally, when only M2 was supported.

**Comment by Piinks** [comment]
Based on testing, the legacy_material package is not a feasible solution, so I am going to close this issue. Flutter is currently M2 backwards compatible as M2 lives in the framework. If we look into relocating it again, we will file a new issue.

**Comment by rydmike** [comment]
@Piinks Agreed, Flutter is currently M2 backwards compatible in the framework, but it is stated that this will be deprecated and removed:

https://github.com/flutter/flutter/blob/4a1e3eaaa2efee9c8449739dad469ae1fa9807d6/packages/flutter/lib/src/material/theme_data.dart#L1013-L1015

Is this still in the pipe? Any schedule for it? It might be good to communicate it more clearly in this case, so those that needs this can consider it in their plans.

When/if M2 is removed from the framework, having the capability to use M2 like theme might be useful. Depends on how far in the future M2 is planned to be deprecated in Flutter. If far enough, it might not be in demand anymore. 

Anyway, I'm providing settings for FlexColorScheme users via Themes Playground that as far as currently possible with theming will make M3 look more like M2, not exact, but closer. :)
