### ISSUE TITLE
I do the same as you say but still same issue

### ISSUE THREAD

**Issue by Darshan-Bhuva** [flutter/flutter#143433]
In case you are keeping it in your app folder the path would be 
storeFile=app/storefile.jks

Doing this should do the task for you

_Originally posted by @pr-1 in https://github.com/flutter/flutter/issues/63681#issuecomment-674102661_

**Comment by danagbemava-nc** [comment]
When filing an issue please provide all the relevant information within the issue. Do not file an issue with a comment from another issue without any context. 

Closing this issue since no information has been provided. 

Please file a new issue with all the relevant information so that this can be properly investigated. 

Thank you
