### ISSUE TITLE
Save screenshots from Android `scenario_app` in `FLUTTER_LOGS_DIR`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143586]
This would significantly help with debugging, because we've seen issues where Skia Gold doesn't always get uploaded artifacts, and also because some emulator versions (cough v28) have been difficult to get working locally but appear to work fine on CI.

@vashworth mentioned to me on Discord:

> We do this in the framework - we'll take a screenshot of the device if the test fails: https://github.com/flutter/flutter/blob/d7867ca7d635c025d8acbcc5cbcff4ca8ea35ab6/dev/devicelab/lib/framework/utils.dart#L591-L624

See https://github.com/flutter/flutter/blob/d7867ca7d635c025d8acbcc5cbcff4ca8ea35ab6/dev/devicelab/lib/framework/host_agent.dart#L22-L33 as well.

I did ask the infra team if there is any inherent problem (i.e. space/capacity). If it ends up being _yes_, perhaps we could only do it on failure, or some other conditional flag for debugging.

**Comment by vashworth** [comment]
Also, I just remembered, we do something similar in the engine (we upload a zip rather than screenshot though), but again only on failure:
https://github.com/flutter/engine/blob/414b867600d72a7343ead5b2efb560467cb5b11f/testing/run_tests.py#L781-L791

fyi I don't think there's a difference between `FLUTTER_TEST_OUTPUTS_DIR` and `FLUTTER_LOGS_DIR`

Example in action: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/713829/overview
