### ISSUE TITLE
Engine's Skia Gold has 100+ untriaged results every day

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143591]
_🚫 Blocking https://github.com/flutter/cocoon/pull/3487, which is why this is P1 (border-line P0, IMO)._

I have a requested _outcome_, but I'm not prescriptive about getting there: **the screenshots emitted by web tests on Skia Gold on the engine tree should not be unstable day-to-day, and should not block the tree** (https://github.com/flutter/flutter/issues/143352).

@yjbanov and @mdebbar [seem to think it's an infra issue](https://discord.com/channels/608014603317936148/1207381900096831592), though @yjbanov later wrote:

> I'd be OK with any of the following quick fixes:
>
> - Tweak matching algorithms specifically for Safari
> - Enforce a specific drone type on LUCI (no flipping between x86 and Arm, for example)
> - Disable Safari + HTML golden tests
>
> While the last option is my least favorite, but if this is blocking the tree and other options are not helping or too costly, then maybe that's the way to go. We already get decent coverage for the HTML renderer from other browsers.

Any of these would be OK for me, assuming they fix the instability.

---

## Background

Most days, I open up `flutter-engine` on Skia gold, and see something like the following:

![image](https://github.com/flutter/flutter/assets/168174/260b5890-3e8d-4750-86cf-77f3f5a5b9e5)

These are all (AFAICT), (1) Web tests, and (2) Safari tests. For example:

![image](https://github.com/flutter/flutter/assets/168174/7b1bb355-69a9-4407-a89e-33011a76ee59)

**Comment by zanderso** [comment]
Assigning to @yjbanov. Please help @matanlurey get unblocked.

**Comment by mdebbar** [comment]
What we know so far:

1. **_[Temporary]_** [Increasing](https://github.com/flutter/engine/pull/50655) the thresholds for Safari doesn't help much.
2. **_[Infra]_** Images produced on Safari are bimodal (i.e. 2 image variants that keep alternating). The current theory here is that CI on Mac is alternating between 2 architectures (Arm and x86?), and each architecture is producing a different result. (This needs more investigation, I'll file an issue soon with details and findings).
3. **_[Skia]_** Gold's fuzzy matching isn't working as "we" expect it. For some reason, when it sees a new Safari image, it decides to compare it to the previous Chrome image instead of the previous Safari image (see [issue](https://github.com/flutter/flutter/issues/143475) for more details). This causes the diff to big enough and exceeds our fuzzy matching thresholds.

Right now, we had to [stop](https://github.com/flutter/engine/pull/50724) Safari tests from uploading goldens.

**Comment by matanlurey** [comment]
Ping @yjbanov and @mdebbar, I'm still seeing almost 150+ untriaged goldens as of Tuesday February 20th:
https://flutter-engine-gold.skia.org/

**Comment by yjbanov** [comment]
I don't see untriaged goldens. Can we close this?
