### ISSUE TITLE
[iOS] What is the point of the transform mutators?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#143566]
I was experimenting with the impact of mutators on platform view performance. I decided to completely disable them to see what happens:

https://github.com/flutter/engine/pull/50711

Funny enough, the ads example app still renders correctly. I had assumed that the transform mutatoirs were positioning the platform views, but they appear to be correctly positioned without the transform applied. are we essentially double positioning the platform views, or did I misunderstand this?

I maintain that this is actually improving (though not entirely fixing) performance locally.

**Comment by jonahwilliams** [comment]
FYI @jmagman @hellohuanlin

**Comment by jmagman** [comment]
Maybe some of the clipping needs to be removed post- https://github.com/flutter/engine/pull/43301 and https://flutter.dev/go/optimized-platform-view-layers ?

**Comment by jmagman** [comment]
By the way with https://github.com/flutter/engine/pull/50386 and https://github.com/flutter/engine/pull/50387 `drawRect:` is never called in the ad scrolling example app.

**Comment by jonahwilliams** [comment]
Its not the clipping specifically, there are mutators that transform the posiiton of the platform view - but they don't appear to do anything. I need to investigate more, but its possible that we're positioning the platform view twice.

**Comment by hellohuanlin** [comment]
@jonahwilliams Doesn't look like it's double positioned. 

The position of the platform view is set at https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L623

The transform mutators are concat'ed and applied to the clipping path: https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm#L450

I think a potential improvement can be to avoid this `ApplyMutators` (or `FlutterClippingMaskView` manipulation within `ApplyMutators`, since a few matrix computation itself is unlikely too costly), if there's no clipping happening.

**Comment by jonahwilliams** [comment]
I'm not worried that the matrix computation is costly - we can see from the CPU profiles that it isn't. What I'm worried about is changes to UIView properties unnecessarily invalidating the WebView.

**Comment by hellohuanlin** [comment]
CC @hellohuanlin
