### ISSUE TITLE
FlutterView.physicalGeometry removed without deprecation warning

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#143692]
### Steps to reproduce

Try `View.of(context).physicalGeometry`
on `3.16` and `3.19`.

It is available without deprecation warning in `3.16` and not available at all in `3.19`.

Also compare:

In `3.16`, the getter below `devicePixelRatio` is `physicalGeometry`
https://github.com/flutter/engine/blob/2181043e7ae33e160744d5ee4e268d7b7ee7b199/lib/ui/window.dart#L139

In `3.19` no such getter exists in `FlutterView`
https://github.com/flutter/engine/blob/8e7df85f7d11ff52712a826ada16e928321a1e1a/lib/ui/window.dart#L139

I dont think this is mentioned in the change log:
https://docs.flutter.dev/release/breaking-changes#released-in-flutter-319

Also note the top one result on google for "physicalGeometry flutter" leads to a 404 now:
https://api.flutter.dev/flutter/dart-ui/FlutterView/physicalGeometry.html

Also applies for `TestFlutterView`

### Expected results

Deprecation warnings before removal

### Actual results

Removal without deprecation warning

**Comment by huycozy** [comment]
Thanks for the report. I only found it on [`Flutter 3.19.0 release notes`](https://docs.flutter.dev/release/release-notes/release-notes-3.19.0). Related PR: https://github.com/flutter/flutter/pull/138103

**Comment by jonahwilliams** [comment]
This was removed here: https://github.com/flutter/engine/pull/47825

FYI @goderbauer

**Comment by goderbauer** [comment]
Hallo, I apologize for the issues that this may have caused. Our breaking change policy is documented here: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes. According to this policy, this change wasn't considered a breaking one because it did not break any of the "contributed tests". To avoid being affected by changes like this in the future I recommend contributing tests to https://github.com/flutter/tests. Thank you.
