### ISSUE TITLE
videoplayer enables deprecated TLS 1.1

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#143649]
We received the following security vulnerability report:

> A bit of context – we use Veracode to scan both our applications as well as the associated libraries.  Veracode has raised a vulnerability in the videoplayer package and in particular in the CustomSSLSocketFactory.java class at line 72 (also at line 21, I believe the two are related).  The flaw it is raising against it is CWE ID 757.  When looking at line 72, it shows that the enabled protocols are TLS v1.1 as well as TLS v1.2.
>
> I believe that TLS v1.1 has been deprecated (March 2021) and that TLS v1.2 is the minimum version.  Is there consideration to update the class to look for TLS v1.2 or higher? Or is there a way to override the check and enforce TLS v1.2?

**Comment by stuartmorgan** [comment]
Context on that code https://github.com/flutter/flutter/issues/62748

It's only used on API 19 (KitKat), and its effect is to enable the two newest versions available on that version of Android, which would otherwise not be enabled (leading to support only of even older versions).

> Is there consideration to update the class to look for TLS v1.2 or higher? Or is there a way to override the check and enforce TLS v1.2?

To make sure I understand the use case: is the scenario that you are making an application that is loading videos from sources you don't control (and where you therefore can't just control the version from the server side), and you want it to fail to load videos from sources that don't support 1.2+?

**Comment by stuartmorgan** [comment]
Capturing from Discord discussion: Ian pointed out that even if the server is controlled, disallowing older protocol versions on the client side mitigates MITM attacks.

We would have to make this opt-in, since the internet being the internet, there are bound to be a bunch of servers out there still using 1.1, and we shouldn't unilaterally break them. (Or we could do opt out, and then people who really need compat could turn it back on.)

I'm not sure if we should consider this in scope for the plugin though. Maintaining custom protocol management in the plugin forever to make the security more strict than the OS default (which we may or may not be able to do for other platforms) is not a core use case.

**Comment by passif** [comment]
Our application plays videos that are under our control - how this was identified is Veracode is flagging the library code as a potential flaw (I have to stress potential - the words 'could' and 'may' are used in their descriptions which does not help to indicate the actual likelyhood of it being a vulnerability. I understand the comment on it not being core functionality, I can take it back to our security officer and we can see if we can handle it as an 'acceptable risk' option or not.

**Comment by stuartmorgan** [comment]
> how this was identified is Veracode is flagging the library code as a potential flaw [...] I can take it back to our security officer and we can see if we can handle it as an 'acceptable risk' option or not.

For your use case, is the problem the behavior, or is the problem just the report itself?

If we were to drop Android 19 support, then this file would cease to exist, and then presumably Veracode would not flag anything because there's no project-level SSL code to analyze. But the behavior on all other Android versions would not change from the current behavior: [Android's default](https://developer.android.com/reference/javax/net/ssl/SSLSocket) is to enable TLSv1, v1.1, v1.2, and v1.3; only SSLv3 has been disabled by default at the system level.

**Comment by passif** [comment]
I understand what you are saying - in all honesty it is more the report itself (there are some internal 'challenges' and we as a company are using TLS v1.2 at a minimum in any case).  I think we need to look at our overall security posture and not stare blindly at Veracode's scan results.
