### ISSUE TITLE
Video Player  dispose

### ISSUE THREAD

**Issue by alialdwahy** [flutter/flutter#143706]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A VideoPlayerController was used after being disposed.
Once you have called dispose() on a VideoPlayerController, it can no longer be used.

**Comment by waliseddiqi** [comment]
As mentioned in [documentation](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerController-class.html):


[dispose](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerController/dispose.html)() → [Future](https://api.flutter.dev/flutter/dart-async/Future-class.html)<void>
Discards any resources used by the object. After this is called, the object is not in a usable state and should be discarded (calls to [addListener](https://api.flutter.dev/flutter/foundation/ChangeNotifier/addListener.html) will throw after the object is disposed).

That is the normal behaviour of dispose method that gets rid of all resources,
In order to use VideoPlayerController again maybe you can create a new instance of the controller

**Comment by darshankawar** [comment]
This looks more of a code implementation issue and also based on above explaination.
Closing as such. @alialdwahy You may search on support channels like StackOverflow for solution, as the error you are getting isn't a bug.
