### ISSUE TITLE
[ios]device lab perf test should support running multiple times and aggregate the result for non-A/B test too

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#143770]
### Use case

For device lab tests, if we run A/B test, we can pass in `--ab=10`, which runs the test 10X2 times and accumulates the results. 

Sometimes I just want to compare the performance of several local engine branches (e.g. local main, branch1, branch2, branch3), I don't want to know how they perform compared to non-local engine (which is the A/B test)

### Proposal

Option 1: 
Upgrade the A/B tests to allow a flag that takes a list of local branch names. e.g. instead of doing `--ab=10`, we do `--count=10 branches=main,branch1,branch2,branch3...`

Option 2: 
Just allow non-A/B tests to run multiple times and accumulate the result. (e.g. `--count=10`). It should accumulate the result, and I will compare different branches manually.

**Comment by jmagman** [comment]
Option 1 will be very tricky since you'd have to teach the framework test runner how to check out different engine branches (it doesn't know where the engine repo is) and rebuild the engine between checkouts.  However altering A/B to skip the A (default engine) and just summarize B (local-engine) 10x times sounds simple enough.

**Comment by hellohuanlin** [comment]
Note from our discussion: 

Can just comment out https://github.com/flutter/flutter/blob/9d5380889d39e2ce4549b6957d44464087280ee2/dev/devicelab/bin/run.dart#L158-L173


i will continue with this. still helpful to officially support this via a flag tho
