### ISSUE TITLE
Framework Smoke Tests failing due to tests reporting "did not complete"

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143797]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Framework%20Smoke%20Tests/17197/overview

**Comment by zanderso** [comment]
cc @dnfield @flar

**Comment by dnfield** [comment]
@kjlubick  added an SkASSERT to skia a few hours ago that is getting tripped on the failure:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755535558073360593/+/u/Framework_test/test:_Framework_test/stdout#L284146_0 (see actually the line above that), which I can't seem to get a link to).

I don't know why this only started happening in the latest engine change instead of when that rolled into skia. Perhaps it is flaky. The patch it started on was an Impeller only change in a code path that doesn't get touched by flutter_tester in this configuration, but we are running an unopt build of flutter tester on the engine CI and an opt build on Flutter framework CI.

/cc @goderbauer

**Comment by dnfield** [comment]
https://skia-review.googlesource.com/c/skia/+/815937 is where Skia changed, although several smoke tests passed after that landed in the engine.

**Comment by dnfield** [comment]
@LongCatIsLooong probably caused in part by https://github.com/flutter/flutter/pull/143281

**Comment by dnfield** [comment]
> @LongCatIsLooong probably caused in part by #143281

You should be able to reproduce this by running the editable text tests with an unopt build of the engine. I think the solution or path forward is to figure out if this assertion is real and meaningful and thus needs to be guarded better in dart-based code, or if it is overly aggressive and needs to be removed from skia.

**Comment by kjlubick** [comment]
My change turned a `SkAssertResult` into an `SkASSERT`. The former was almost certainly an oversight, but I wonder if the previous behavior had the compiler sometimes optimize out the check?

**Comment by LongCatIsLooong** [comment]
The framework PR is reverted. That test adds a `Size.zero` widget span to the text I suspect that cause the crash.

**Comment by flar** [comment]
@zanderso thanks for spotting that assert. I had looked at the logs and couldn't find where the errors were coming into play.

**Comment by flar** [comment]
We shouldn't be failing an assert due to a Size.zero widget, though.

**Comment by dnfield** [comment]
@LongCatIsLooong is also the author of the original asserts in https://skia-review.googlesource.com/c/skia/+/753079

**Comment by dnfield** [comment]
> My change turned `SkAssertResult`s into `SkASSERT`s. The former was almost certainly an oversight, but I wonder if the previous behavior had the compiler sometimes optimize out the check?

Yes, sorry about that - the checks are getting triggered because the engine variant is running using an unopt build with asserts enabled, and the framework is not.

**Comment by LongCatIsLooong** [comment]
The assert should be removed from SkParagraph now (on a side note the skia roller is blocked on untriaged goldens). I'm planning to reland the framework PR later. 

Should this be closed?

**Comment by kjlubick** [comment]
Thanks for removing the asserts in https://github.com/google/skia/commit/e15e58a63b70f2450c67287cfee679f62de870bb

**Comment by zanderso** [comment]
Closing this as the builder has been retired.
