### ISSUE TITLE
How to handle promotional offer for android in flutter using in_app_purchase package?

### ISSUE THREAD

**Issue by atulproject99** [flutter/flutter#143742]
I am working on a project so there is required to give promotional offer.I am using in_app_purchase package so for ios it is very easy to handle promotional offers but for android i didn't anything.please explain with sample code or give any resource reference.

**Comment by dam-ease** [comment]
Hello @atulproject99.
Can you check out these to see if it helps:
https://developer.android.com/google/play/billing/promo and
https://medium.com/@antonio.tioypedro1234/flutter-uncomplicating-in-app-purchases-c863042aee15

As regards examples being added to the package to make it easier, I see there is an open proposal for this https://github.com/flutter/flutter/issues/51757, you can comment, upvote and follow up on this issue for updates. 

You can also see support channels like StackOverflow to ask more questions on this for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources.

Closing from here as this is more of a how-to question rather than a bug or feature request.
