### ISSUE TITLE
Alignment doesn't work when there is formatting within a short String with `MarkdownBody`.

### ISSUE THREAD

**Issue by tonyrbf96** [flutter/flutter#143752]
Alignment doesn't seem to work when there is formatting within a short String with `MarkdownBody`. Working fine with `Markdown`. 

```
MarkdownBody(
  data:
    'Aliqua ut et cillum **velit non**.',
  styleSheet:
      MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
    textAlign: WrapAlignment.center,
  ),
)
```
Flutter Channel stable, Version 3.19.0
flutter_markdown ^0.6.19

_Originally posted by @nsendhavdq in https://github.com/flutter/flutter/issues/112058#issuecomment-1257760240_

**Comment by huycozy** [comment]
Hi @tonyrbf96 
This is working as expected because the default values of `shrinkWrap` and `fitContent` are true. You can set these values to false to see if it works as expected. If you take a look at Markdown widget code, `shrinkWrap` is false by default.

Also, they are built by different root widgets. Markdown is a ListView while MarkdownBody is a Column. 

Closing this as it's not a `flutter_markdown` package's issue.
