### ISSUE TITLE
skwasm: allocating memory until we crash!

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#143800]
See https://vote-dart.web.app/

```
Flutter 3.20.0-10.0.pre.58 • channel master • git@github.com:flutter/flutter.git
Framework • revision 718c81704f (6 hours ago) • 2024-02-20 13:07:59 -0500
Engine • revision e16a260265
Tools • Dart 3.4.0 (build 3.4.0-157.0.dev) • DevTools 2.33.0-dev.6
```

**Comment by kevmoo** [comment]
![image](https://github.com/flutter/flutter/assets/17034/4f609581-615a-4303-915e-79dfa200b0f3)

**Comment by jonahwilliams** [comment]
For me this is:

```
Uncaught (in promise) DOMException: Failed to execute 'createImageBitmap' on 'WorkerGlobalScope': The source image height is 0.
    at Gc (https://www.gstatic.com/flutter-canvaskit/e16a260265ade2ed0240784db86144f808fec01a/skwasm.js:62:319)
    at https://www.gstatic.com/flutter-canvaskit/e16a260265ade2ed0240784db86144f808fec01a/skwasm.wasm:wasm-function[7994]:0x1e40c0
    at w._surface_renderPictureOnWorker (https://www.gstatic.com/flutter-canvaskit/e16a260265ade2ed0240784db86144f808fec01a/skwasm.js:128:374)
    at e (https://www.gstatic.com/flutter-canvaskit/e16a260265ade2ed0240784db86144f808fec01a/skwasm.js:61:236)
    ```

**Comment by eyebrowsoffire** [comment]
I don't think this is a memory leak thing. In my repro of it, it happens immediately on the first frame, and it's trying to create an image bitmap 20 billion pixels tall, so I think that is the issue.

**Comment by eyebrowsoffire** [comment]
I have a fix out for review for this, but it has merge conflicts because it was built on top of https://github.com/flutter/flutter/issues/140429, which had to be reverted. Relanding that is dependent on a dart issue that is being worked on. Rather than rewrite this twice, once for the old way the rendering worked and once for the new way, I'm going to wait until the Skwasm frame timing callbacks PR relands before I merge this.
