### ISSUE TITLE
Confusing instructions about updating the Gradle plugin

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#14386]
https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1#upgrading-a-flutter-app-project

> In android/gradle/wrapper/gradle-wrapper.properties, replace 3.3 with 4.1 in the last line.

The file is gitignored. Should just deleting the file also work?

I changed the file and missed that it is not checked in and my coworker got a weird error message about `google()` not being recognized.

What is the correct way to handle this?

**Comment by asaarnak** [comment]
The /gradle was removed from gitignore when they switched to use gradle wrapper instead of gradle bundled by android studio.
```
/gradle
/gradlew
/gradlew.bat
```
Commit:
https://github.com/flutter/flutter/commit/c5999c74c06cf33d69c55cf23e0c952144632178#diff-ef7959f4a917f696ebe78db8663454e7
Latest create template /android folder gitignore:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/android.tmpl/.gitignore

**Comment by zoechi** [comment]
Thanks.
Isn't this worth being mentioned in the Gradle plugin update instructions?

**Comment by asaarnak** [comment]
Propably should note that it only affects older projects that didn't have gradle wrapper.

**Comment by zoechi** [comment]
I assume this is no longer relevant
