### ISSUE TITLE
I want to turn the engine tree red on untriaged goldens. How should I proceed?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143872]
Infra team, could you do a first-triage and let me know _how_/_where_ this should be implemented?

I'm happy to own landing the change and making changes to the engine repo as needed.

_(Marking P1 as it's part of our own P1 test infra improvements for Impeller and the engine repo)_

/cc @Piinks @mdebbar @zanderso 

## Background

On a [Discord discussion](https://discord.com/channels/608014603317936148/608021234516754444/1209932633212059779) we noted that it's possible to call a relatively cheap (cached) API endpoint to determine if there are untriaged goldens for a given tree:

> If all you care about is how many there are, /json/v2/trstatus is a cheap (cached ) endpoint

This seems fine for our needs.

However, how/where do I add this test?

For example in https://github.com/flutter/flutter/issues/143863#issuecomment-1957707800, @CaseyHillers notes:

> I'd like to see us set up flutter-gold as a dedicated target in ci.yaml, and plumb through custom scheduling logic for it. This would allow it to benefit from some of the existing code for pushing LUCI checks to GitHub, and reduce the amount of custom code it implements.
>
> https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests

At the same time https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests notes:

> By default, these should not block the tree but act as FYI to the gardeners.

... which is not what we're going for.

**Comment by Piinks** [comment]
I don't know that an additional check is necessary since if a commit generates an image that is untriaged in postsubmit, we turn the tree red in flutter/flutter (and soon flutter/engine).

**Comment by Piinks** [comment]
Also, chatting with @jonahwilliams, this would make it harder to de-flake golden images like he is doing now.
The impeller test shards are marked bringup, so golden file images generated from that shard are not tree-breaking. This proposed new check would break the tree right now because there is a flaky impeller golden file test.

The endpoint we were told we could use ,` /json/v2/trstatus`, only says how many untriaged images there are, not what images they actually are or from what test shard. If we implement this, we would need to find a way to account for images that were generated by shards that are marked bringup, and not break the tree then.

**Comment by Piinks** [comment]
Based on the above comment, I feel comfortable that the current break-the-tree strategy is sufficient, and will be better once flutter/engine adopts it.

**Comment by jonahwilliams** [comment]
In theory the current Impeller shard should be stable soon. That said, we'll need to account for the process of bringing up new goldens/backends.

**Comment by jonahwilliams** [comment]
soon (tm)

**Comment by CaseyHillers** [comment]
> By default, these should not block the tree but act as FYI to the gardeners.

Emphasis on "by default." For Flutter owned services, they should block the tree.

**Comment by yjbanov** [comment]
Acknowledged

**Comment by jonahwilliams** [comment]
This one is resolved, closing
