### ISSUE TITLE
Document adding a new golden file test suite/task

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143863]
### Type of Request

bug

### Infrastructure Environment

Cocoon

### What is happening?

New golden file tests are being added, at least in `flutter/engine`, with no knowledge that GitHub checks are not updated.

### Steps to reproduce

See https://github.com/flutter/cocoon/blob/67c2c0399e7af9fc2ca3f76fdbcde7f527218a84/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L125-L127.

This file is very far and in a separate repo from where golden tests are actually configured. It would be much better if any builder that has `goldctl` active would trigger this flag.

**Comment by zanderso** [comment]
@CaseyHillers @keyonghan Can this be configured in ci.yaml instead of being hardcoded in cocoon source?

**Comment by Piinks** [comment]
With untriaged images at tip of tree turning it red, this won't slip easily. 

Referring to https://github.com/flutter/cocoon/pull/3508, the framework side only checks for `framework` and `misc` test shards. See here: https://github.com/flutter/cocoon/pull/3508/files#r1498071829

However, we have a bunch of `[...]web[...]` shards that also execute golden file image tests in the framework.  CI is configured though that any time we are running a `framework` shard, we are also running those `web` shards, so it does not really matter, the flutter-gold check applies anyway. 

For example:
- https://github.com/flutter/flutter/blob/bfeaf5a7f2c67d9efdde58874a452da46e722a45/.ci.yaml#L636
  - `framework` test shard triggered by change to `packages/`
- https://github.com/flutter/flutter/blob/bfeaf5a7f2c67d9efdde58874a452da46e722a45/.ci.yaml#L1265
  - `[...]web[...]` test shard also triggered by change to `packages/`

Since we use the `--passfail` flag in the framework, in postsubmit when an image is generated by a test and sent to Gold, if it is not an approved image the tree will go red. So if we do drift and the flutter-gold check is missed on a golden file generating change, it will make the tree red once it lands.

**Comment by Piinks** [comment]
This has not been the case in flutter/engine, but with https://github.com/flutter/engine/pull/50826, the engine should be safer from these drifts going forward.

**Comment by keyonghan** [comment]
> @CaseyHillers @keyonghan Can this be configured in ci.yaml instead of being hardcoded in cocoon source?

Just to confirm, is this fully determined/controlled on the target level? If yes, then we can add a property, say `checkGoldenStatus: true` to help the api.

**Comment by matanlurey** [comment]
Ideally it would use the same mechanism that makes GOLDCTL available today. For example I already have to add:

- https://github.com/flutter/engine/blob/5e1202ba99b09a3d305299d677b6194cc02155ba/.ci.yaml#L59
- https://github.com/flutter/engine/blob/5e1202ba99b09a3d305299d677b6194cc02155ba/ci/builders/linux_android_emulator.json#L129

**Comment by Piinks** [comment]
.ci.yaml is full of shards that are configured to set up goldctl, but don't actually use it. I asked someone about this recently, and they said it was better to just apply-all then only add the dependency to shards where needed. So if we were to use .ci.yaml to trigger to flutter-gold check, there would be a lot of unrelated PRs affected, which in the past contributors have been very unhappy with. If a PR has nothing to do with golden file images, contributors don't want to wait for the flutter-gold check to clear.

**Comment by matanlurey** [comment]
> .ci.yaml is full of shards that are configured to set up goldctl, but don't actually use it

Could we fix that instead? :P

**Comment by CaseyHillers** [comment]
I'd like to see us set up `flutter-gold` as a dedicated target in ci.yaml, and plumb through custom scheduling logic for it. This would allow it to benefit from some of the existing code for pushing LUCI checks to GitHub, and reduce the amount of custom code it implements.

https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests

**Comment by Piinks** [comment]
I support that!

I think Gold has suffered as an outcast in Flutter's infra system. It has no clear owner and is not maintained by the infra team. It breaks regularly, often due to changes that are made in or around infra without considering it. It has largely lived in maintenance mode for years while being a huge part of our testing. There are considerable deviations in how it works in flutter/flutter versus how it works in flutter/engine.

I think it would be worth examining how we can better support such a critical part of our infrastructure.

**Comment by keyonghan** [comment]
Moving the creating logic closer to codes (.ci.yaml) will help awareness , but this will trigger nontrivial changes in different locations:
1) the gold status doesn't fit the existing .ci.yaml format
1.1) we need a new logic to skip target from post-submit scheduling
1.2) we need a new logic to skip rolling to LUCI's infra/config
1.3) we need a new entry from .ci.yaml target to handle the dependencies
2) we need a specific scheduling logic for gold status (different from any other existing targets)
3) auto submit logic needs to updated accordingly to switch logic from checkstatus to checkrun
4) the gold status push api needs adjustment as well.

The pain point here is invisible gold status scheduling logic from the `repo/.ci.yaml` side. Instead of spending days/weeks of effort to fit into .ci.yaml, a doc on the top will help (linking to the location of `gold-status` logic).

> It breaks regularly, often due to changes that are made in or around infra without considering it.

I would be curious to learn a bit more here. Is it mainly the goldctl dependencies? We have been improving the CI_YAML.md: https://github.com/flutter/flutter/issues/143671, we can add related docs there if needed.

**Comment by matanlurey** [comment]
The outcome I'm looking for here is "it's not possible to setup new golden tests that won't be checked on GH".

I don't really care how, but I suspect documenting `.ci.yaml` is insufficient.

**Comment by keyonghan** [comment]
Back to the earlier [property proposal](https://github.com/flutter/flutter/issues/143863#issuecomment-1957663161): `checkGoldStatus: true`

Regarding the [concern](https://github.com/flutter/flutter/issues/143863#issuecomment-1957677304) (/cc @Piinks ) that PRs will run `gold-status` when not needed, I would not expect it to incur the problem. The property should do the same as what the current API does, but giving the control to developers.

- [**Current logic**](https://github.com/flutter/cocoon/blob/67c2c0399e7af9fc2ca3f76fdbcde7f527218a84/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L125-L127.) will create gold-status when scheduled targets contain pre-hardcoded keywords `framework/web engine/misc`.

- **Proposed logic**:
  1. adds the property `checkGoldStatus: true` to the targets which contain keywords `framework/web engine/misc`.
  2. from gold status API: change the logic to query that property instead of hard coded keywords.
  3. for future new targets that add new gold tests, people only need to add the property `checkGoldenStatus: true` to trigger `gold-status` check: the backend logic will auto pick up the new tests.

Instead, we can simply rely on the dependency `goldctl` (without introducing the new property) after a thorough clean up ([as suggested](https://github.com/flutter/flutter/issues/143863#issuecomment-1957678820) by @matanlurey ), whenever the dependency is only setup for targets that use it.

**Comment by matanlurey** [comment]
I ran into this again

I am putting this back into the infra queue - if [this is accepted](https://github.com/flutter/flutter/issues/143863#issuecomment-1957678820) I would be happy to work on it next week.

**Comment by christopherfujino** [comment]
> I ran into this again
> 
> I am putting this back into the infra queue - if [this is accepted](https://github.com/flutter/flutter/issues/143863#issuecomment-1957678820) I would be happy to work on it next week.

this sounds reasonable to me.

**Comment by matanlurey** [comment]
Self-admittedly this is not trivial - there is code that fetches `.ci.yaml` and does checks on it in cocoon request handlers, but since we're relying on very loose JSON stringy checks today making this change without breaking us will be hard.

I will likely roll this out slowly where there is redundancy in how we push the status.

**Comment by matanlurey** [comment]
@jonahwilliams paired with me for a few minutes. tl;dr: I don't think this is worth doing:

The current way this works is on a cron (?), the `PushGoldStatusToGitHubService`:

- Fetches all open PRs for both `flutter/flutter` and `flutter/engine`
- Checks if any of them ran tasks that include a small-list of hard-coded allowlist substrings
- If they do, and some other conditions are true, the `flutter-gold` status is updated

The behavior we don't like is that it's easy for a new _task_ to be added that has a dependency on GOLDCTL, but `PushGoldStatusToGithub` doesn't know about it - therefore it's possible for no checks to be triggered, and the PR to merge (i.e. with `auto-submit`), to just break the tree on post-submit due to untriaged goldens.

A solution we had considered is deriving this list from `.ci.yaml`, that is, where the following is set:
```yaml
  - name: Linux framework_tests_misc
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "goldctl", "version": "git_revision:2387d6fff449587eecbb7e45b2692ca0710b63b9"},
```

... we'd _derive_ that `Linux framework_tests_misc` needs a status update.

A few options were considered

1. Fetch the `{slug}/main/.ci.yaml` and use it as a source of truth

    🚫 New tasks would still break on post-submit, as we'd reference a stale `.ci.yaml`
    ✅ No manual updates to `PushGoldStatusToGithubService` would be required
    ✅ Performance of the service would be in the same ballpark (we'd fetch/process ~2 files)
    🟡 A reasonable amount of non-trivial code will need to be added and maintained

2. Fetch the `{slug}/{pr}/.ci.yaml` _per_-PR

    ✅ New tasks would correctly signal on pre-submit
    ✅ No manual updates to `PushGoldStatusToGithubService` would be required
    🚫 Performance of the service would significantly degrade, requiring fetching 100s of files
    🚫 Code added would be significantly complex, and working around performance even more so

3. Make depending on `GOLDCTL` follow an explicit process that requires a cocoon update

    🟡 New tasks would correctly signal on pre-submit _or_ refuse the GOLDCTL dependency
    🚫 Manual updates to the service continue to be required
    ✅ No performance changes
    🟡 Allow-list code itself would have to be written and maintained

4. Do none of these, and just write addendums to the [documentation we have today](https://github.com/flutter/flutter/blob/309ae21448521b18a4cc90e3db435089a6dbc3cb/docs/contributing/testing/Writing-a-golden-file-test-for-package-flutter.md#flutter-gold-check)

    🚫 New tasks would still break on post-submit, as we'd reference a stale `.ci.yaml`
    🚫 Manual updates to the service continue to be required
    ✅ No performance changes
    ✅ No code has to be written

Given the under-maintained nature of this infrastructure and significant cost to doing something about it, I'm reluctantly thinking about changing this issue to pursue option (4), that is, update our docs and let the next person worry about it 😢

**Comment by christopherfujino** [comment]
> Given the under-maintained nature of this infrastructure and significant cost to doing something about it, I'm reluctantly thinking about changing this issue to pursue option (4), that is, update our docs and let the next person worry about it 😢

This SGTM
