### ISSUE TITLE
Configure enableIMEPersonalizedLearning for a scope

### ISSUE THREAD

**Issue by clragon** [flutter/flutter#144093]
### Use case

Users have requested that I allow using the incogito keyboard for my application.

However, my application contains _many_ `TextField` and `TextFormField`.
It would therefore be a lot of work to change the [`enableIMEPersonalizedLearning`](https://api.flutter.dev/flutter/material/TextField/enableIMEPersonalizedLearning.html) value for all my test fields.

### Proposal

Allow configuring the `enableIMEPersonalizedLearning` for a scope (through `BuildContext` and some `InheritedWidget`).

I have thought about where specifically this value would go and `InputDecoration` comes to mind. This would easily allow configuring this value for a larger area of `TextField`. However, I am not sure if `InputDecoration` is the correct place.
If not, I am not sure where exactly this value would live.
Other values like [`enableInteractiveSelection`](https://api.flutter.dev/flutter/material/TextField/enableInteractiveSelection.html) are also not available on `InputDecoration`, so maybe this is not the right place.

This functionality can technically be added from the outside but would require a wrapper around every single `TextField` in the app, making this not a real solution to the aforementioned problem.

**Comment by justinmc** [comment]
I hear you on this, but I think that your proposal here is a specific solution for a general problem. We could add a one-off way to set enableIMEPersonalizedLearning for some widget tree, but the same problem still exists for nearly every other widget parameter in Flutter. Adding one-off things like this could lead to a confusing API.

### One option for today
You could create a wrapper for TextField that hardcodes this parameter.

```dart
class MyTextField extends StatelessWidget {
  const MyTextField({super.key});

  @override
  Widget build(BuildContext context) {
    return const TextField(
      enableIMEPersonalizedLearning: false,
    );
  }
}
```

Then use MyTextField everywhere instead of TextField. The downside is that you'll have to manually pipe through all of the constructor parameters that you care about.

### An upcoming solution: static metaprogramming
It looks to me like this new Dart feature will solve the problem of the wrapper widget ([spec](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md)). It seems like you could pipe through all of the constructor parameters automatically, so you wouldn't have to worry about new parameters being added to TextField, etc. Or you might even be able to come up with other solutions to your original problem with this.

**Comment by clragon** [comment]
Thank you for your reply.

I was aware of wrapper classes, but unfortunately, they do not solve my problem.
Whether I use a wrapper class, or adjust all textfields manually, I will have to make many changes across my entire app, just to support this feature.

The macro approach, which yet not available, suffers the very same problem as manual widget wrapping.

I dont think that there should be an `InheritedWidget` just for this single parameter, but I do think it would be useful to have one that either sets this and other parameters, e.g. `enableInteractiveSelection`, or include this in the Theme (though, again, I am unsure which parameters truly belong into a Theme object, and which don't. I haven't spotted a pattern in other Theme objects).

While it is true that technically each and every parameter might be useful to be configurable across the entire app, I do believe [`enableIMEPersonalizedLearning`](https://api.flutter.dev/flutter/material/TextField/enableIMEPersonalizedLearning.html) is an important one for all kinds of apps that may work with sensitive personal data.

**Comment by clragon** [comment]
Assuming this issue to probably not be important enough to get an implementation, 
I consider this to be discussed sufficiently and will close it now. 

I will solve this problem the manual way in my app. However, I do believe an option like this would be valuable, even in the future.
