### ISSUE TITLE
DropDownButtonFormfield documentation references 'initialValue', but it doesn't exist.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#144135]
When trying to reference `initialValue` for `DropDownButtomFormfield` as described in documentation

https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html

it does not exist.

![image](https://github.com/flutter/flutter/assets/11217296/c63acdbb-8219-4129-a4ce-0c056cba460e)

Can you please update documentation to use `value` instead.

**Comment by matanlurey** [comment]
Huh? It [exists right here](https://api.flutter.dev/flutter/widgets/FormField/initialValue.html):

![Screenshot 2024-02-29 at 3 28 40 PM](https://github.com/flutter/flutter/assets/168174/aa6ac9f9-8d8d-4fd1-aa3e-c38b930a31d4)

I think what you're trying to say is that `value` is not the same identifier as `initialValue`, and I agree that's confusing. I don't know the style guide for material widgets well, but perhaps `value` should be deprecated and another named argument `initialValue` should be introduced for consistency?

**Comment by Hixie** [comment]
I would probably put a comment on the docs for FormField.value that says that the DropdownButtonFormField subclass constructor calls it "value" instead of "initialValue" for consistency with "DropdownButton", and on the DropdownButtonFormField constructor docs to say that "value" maps to the "initialValue" property.

Migrating from "value" to "initialValue" would also make sense (though honestly this whole class is legacy at this point since DropdownMenu is the new way to do dropdowns).

**Comment by QuncCccccc** [comment]
Oh thanks for all the suggestions @matanlurey @Hixie! 

> I would probably put a comment on the docs for FormField.value that says that the DropdownButtonFormField subclass constructor calls it "value" instead of "initialValue" for consistency with "DropdownButton", and on the DropdownButtonFormField constructor docs to say that "value" maps to the "initialValue" property.

I think adding docs to `FormField.initialValue` and `DropdownButtonFormField` constructor sounds good to me! Updating.
