### ISSUE TITLE
Enable Runtime Reflection(mirror) for specific code/declaration 

### ISSUE THREAD

**Issue by TRohit20** [flutter/flutter#144142]
### Use case

The lack of Dart’s runtime reflection(mirrors) in Flutter is an issue which makes porting parts of existing codebase difficult. I understand the feature seems to be disabled to facilitate tree shaking during compilation to reduce binary size.

I figure, we can enable reflection for specific declarations or classes/code using conditional compiler annotation, thereby, runtime reflection essentially only kicks in for specific parts of the code and doesn't interfere or create ambiguity or introduce uncertainty with code usability of any sorts.

### Proposal

Given the feature is already existing in Dart, the underlying programming language, it is a feature that is best extended by Flutter with abstract implementation.

**Comment by huycozy** [comment]
Hi @TRohit20 

>Given the feature is already existing in Dart

As far as I can see, it's experimental and continue discussing at https://github.com/dart-lang/sdk/issues/44489. A related Flutter issue: https://github.com/flutter/flutter/issues/1150 which proposed `--allow-mirrors`.

>it is a feature that is best extended by Flutter with abstract implementation.

Could you give an example for this?

**Comment by TRohit20** [comment]
My proposal is similar, the primary reason as to why flutter has reflections disabled is due to the uncertainty it introduces to code usability thereby resulting in large binary sizes(which we would like to avoid). But since we currently have it enabled in Dart, we can extend the feature in Flutter through a conditional compiler annotation or command line flag. Thereby, the user will get to choose whether or not a certain piece of code needs runtime reflection and will be executed only for that part. 

Eg, Serialisers need runtime reflection as they need to perform dynamic inspection of the data.

**Comment by mraleph** [comment]
This is the wrong place to ask for this feature because Flutter can't just magically enable mirrors - the decision to exclude mirrors support from AOT was made at the Dart toolchain level. 

A variation of what you are proposing has been tried long time ago in the context of `dart2js`: developers had to use [`@MirrorsUsed`](https://api.dart.dev/stable/2.14.4/dart-mirrors/MirrorsUsed-class.html) to inform compiler which symbols are reflectively accessed. The UX of this was very bad. 

Consider for example:

```dart
@mirrorable
class A {
  final B field;

  C foo(D v) {
  }
}
```

What does `@mirrorable` do, what capabilities does it guarantee? Do these capabilities apply transitively to all types referenced by `A` (e.g. `B` and `D`)? If they don't apply transitively how one enables reflection on `B` if it resides in the third-party library? If they do apply transitively - then how to prevent them affecting too much code. 

You would need a sophisticated capability system akin to [`package:reflectable`](https://pub.dev/packages/reflectable) - to express these things. It gets really complicated and confusing to use. 

I think with the current direction of the language it is very unlikely that we will ever go the same route. Currently code generation (which is effectively a compile time reflection) is thought to be the UX friendly and  AOT friendly replacement for runtime reflection.
