### ISSUE TITLE
【RenderThread】 avc: denied   Frame rate is very low.

### ISSUE THREAD

**Issue by hellozhangyaoke** [flutter/flutter#144122]
### Steps to reproduce

W/RenderThread(13325): type=1400 audit(0.0:124173): avc: denied { read } for name="boot_mode" dev="sysfs" ino=3243 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0

### Code sample

https://github.com/flutter/samples/tree/main/animations

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

..

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

V7.1.1
ARMv7a

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

N/A

### Logs

W/RenderThread(13325): type=1400 audit(0.0:124173): avc: denied { read } for name="boot_mode" dev="sysfs" ino=3243 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0

### Flutter Doctor output

Flutter Doctor is no error.

**Comment by huycozy** [comment]
Hi @hellozhangyaoke 
I tried the first example `AnimatedContainer` on `Realme 6, Android 11` in profile mode, but don't see the warning appears in the output console. What is the specific animation example in the project to reproduce the issue? 

Based on `avc: denied { read }` warning, it may be related/similar to https://github.com/flutter/flutter/issues/51401. Please check if it's a similar case to yours. If it's not a case, please provide device information (OS, model). And please also share the output of `flutter doctor -v` so that we can know which flutter version you are on. 

Moreover, it would be helpful if you can provide a recorded video to demonstrate the issue. Thanks!

**Comment by huycozy** [comment]
Please also help to provide the remaining information above so that we can verify the issue. Thanks!
