### ISSUE TITLE
[BUG]: In `absorbImpact` of stretch overscroll

### ISSUE THREAD

**Issue by T-Dynamos** [flutter/flutter#144304]
I have a question regarding this `absorbImpact` function:
> File: ./packages/flutter/lib/src/widgets/overscroll_indicator.dart
```dart
  /// Handle a fling to the edge of the viewport at a particular velocity.
  ///
  /// The velocity must be positive.
  void absorbImpact(double velocity, double totalOverscroll) {
    assert(velocity >= 0.0);
    velocity = clampDouble(velocity, 1, 10000);
    _stretchSizeTween.begin = _stretchSize.value;
    _stretchSizeTween.end = math.min(_stretchIntensity + (_flingFriction / velocity), 1.0);
    _stretchController.duration = Duration(milliseconds: (velocity * 0.02).round());
    _stretchController.forward(from: 0.0);
    _state = _StretchState.absorb;
    _stretchDirection = totalOverscroll > 0 ? _StretchDirection.trailing : _StretchDirection.leading;
  }
```

In this part:
```dart
math.min(_stretchIntensity + (_flingFriction / velocity), 1.0)
```
As the scroll velocity increases, this value must get small compared to when the velocity is very low. Then we would experience a large stretch animation in a small scroll, but this does not happen. Why?

Edit: IT DOES REALLY HAPPENS!

**Comment by huycozy** [comment]
Hi @T-Dynamos 
The goal of this Github repo is to improve Flutter framework reporting bugs or feature requests. Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

If you encounter behavior that you believe could be a Flutter framework bug, please update or open a new issue and fill all information indicated in the issue template that will help us verify the issue. 

Closing from here as this is a question rather than a bug or feature request.

**Comment by T-Dynamos** [comment]
@huycozy Please reopen, it's a bug.

I was wrong here it really happens.
> , but this does not happen

Proof:

https://github.com/flutter/flutter/assets/68729523/1e6f1b29-7853-443d-8d3c-e4b56c01d6c4


When scroll velocity is much it stretches less, but when it's low it stretches much. Which is totally different from Android.

**Comment by huycozy** [comment]
Re-opening. Please provide the following information so that we can verify this properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Which device are you checking on? (OS, model)

**Comment by T-Dynamos** [comment]
@huycozy Sorry I am not a flutter user. And I was just having a look at src and found this bug and confirmed this bug when actually tested it.
