### ISSUE TITLE
path_provider_win/linux should support Dart-only use cases

### ISSUE THREAD

**Issue by dnys1** [flutter/flutter#144400]
### Use case

`path_provider_windows` and `path_provider_linux` both use FFI bindings and Dart-only code for determining the locations of relevant paths. However, they both take a dependency on Flutter, which prevents these packages from being used in a Dart-only context (e.g. in a Dart CLI).

Currently, I've just copy/pasted the code into my CLI and removed the Flutter dependency bits. But it would be great if these packages did not depend on Flutter so that they could be used directly in these cases.

### Proposal

Currently, `path_provider_linux` and `path_provider_windows` only use the Flutter SDK for `@visibleForTesting`, which could be consumed from `package:meta` instead. Transitively, though, they both depend on Flutter via `path_provider_platform_interface` which holds the `MethodChannel` implementation.

However, since the Android and iOS implementations have been migrated to Pigeon, it seems like this interface is no longer needed, and even `path_provider_platform_interface` could be migrated to no longer take a dependency on the Flutter SDK.

**Comment by stuartmorgan** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/122529; since that was closed due to lack of response, we can discuss the use case further here.

> which prevents these packages from being used in a Dart-only context (e.g. in a Dart CLI).

What are the specific methods you want to use in a CLI context? As noted in the other issue, not all methods are relevant in a non-application context.

And repeating the question from the other issue: what is the actual concrete use case here? You've described an abstract case; what's a concrete example of a non-Flutter program that needs to run just on Windows and Linux and needs access to those specific paths?

> Currently, I've just copy/pasted the code into my CLI and removed the Flutter dependency bits.

What specific code did you need to duplicate?

> `path_provider_platform_interface` could be migrated to no longer take a dependency on the Flutter SDK.

This is true, but only as a breaking change.

**Comment by dnys1** [comment]
Hi @stuartmorgan, the CLI I'm building needs a safe place to store configuration files, a SQLite db, and some global file locks. This must be a location that many instances of the CLI can share together, and ideally a spot in keeping with the OS heuristics. For this, I use the `getApplicationCachePath` and `getApplicationSupportPath` methods.

> What specific code did you need to duplicate?

The following files were copied into my CLI:
- https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_windows/lib/src/folders.dart
- https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
- https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/lib/src/get_application_id_real.dart
- https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/lib/src/path_provider_linux.dart

> This is true, but only as a breaking change.

Makes sense

**Comment by stuartmorgan** [comment]
> * https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_windows/lib/src/folders.dart

Is there a reason you need this file, rather than using the relevant `win32` constant directly?

> * https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart

How much of this file are you actually using in practice? Is there a reason you aren't just hard-coding the subdirectory name you want to use?

> * https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/lib/src/get_application_id_real.dart

How are you using this code in a command-line application? Is it registering itself as if it were a GTK application for some reason?

> * https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/lib/src/path_provider_linux.dart

Is there a reason you aren't using `xdg_directories`, which this file is a very minimal wrapper around, and which already has no Flutter requirement?

I'd like to understand how much of the ~700 lines of code you've referenced above you are actually getting value out of; it seems like this use case would only need a very small amount of code wrapping the (non-Flutter) libraries these are built on.
