### ISSUE TITLE
[split_config.arm64_v8a.apk] SIGSEGV

### ISSUE THREAD

**Issue by AhmedElhenidy** [flutter/flutter#144538]
### Steps to reproduce

upload an AAB to play store.

### Expected results

No ANR or Crashes.

### Actual results

I got  [split_config.arm64_v8a.apk] Crash.
<img width="1353" alt="image" src="https://github.com/flutter/flutter/assets/47220941/97054318-8597-4ca1-84f2-e08922d66d7a">
 
when I get into the crash details I see most of the devices are Huawei devices
<img width="1668" alt="image" src="https://github.com/flutter/flutter/assets/47220941/1d7fcf99-9f24-408d-a90b-38f47965c364">

also the most affected users has Android 10 (SDK 29)
<img width="1006" alt="image" src="https://github.com/flutter/flutter/assets/47220941/52a7d0fe-5e09-444f-8037-b15b99b6ee47">

### Code sample

<details open><summary>Code sample</summary>

```dart
[pid: 0, tid: 22094 >>> packageId <<<

backtrace:
  #00  pc 0x0000000002198fd0  /vendor/lib64/egl/libGLES_mali.so
  #01  pc 0x000000000219a924  /vendor/lib64/egl/libGLES_mali.so
  #02  pc 0x00000000021b1300  /vendor/lib64/egl/libGLES_mali.so
  #03  pc 0x00000000021b0094  /vendor/lib64/egl/libGLES_mali.so
  #04  pc 0x0000000000022718  /system/lib64/libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int)+348)
  #05  pc 0x000000000001f008  /system/lib64/libEGL.so (eglSwapBuffers+84)
  #06  pc 0x0000000000019d2c  /data/app/packageId-ndlFJOmsk53irjCNyFdBGQ==/split_config.arm64_v8a.apk]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
]
```

</details>

**Comment by darshankawar** [comment]
@AhmedElhenidy 
Is there a way for you to provide a reproducible code sample that triggers this crash ?
There have been similar issues reported but we had to close them without any action due to lack of replicable code.

https://github.com/flutter/flutter/issues/117950
https://github.com/flutter/flutter/issues/138701

**Comment by AhmedElhenidy** [comment]
@darshankawar if you want a way to reproduce just upload an AAB to play store. this crash happens only after uploading to store. I'm using Crashlytics  and this issue doesn't appear there.

**Comment by darshankawar** [comment]
@AhmedElhenidy 
Does simply building `aab` and uploading to store gives this behavior ? I am sure the `aab` you are building and releasing contains full fledged app code with lot of custom implementation and third party packages. But in order to isolate the issue to framework, can you try by simply building aab for default counter app and upload to store and check if it gives you same error not ?
That way we will know if any other implementation is causing the issue or not.
