### ISSUE TITLE
Button colors generated from ColorScheme.fromSeed changed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#144649]
The following demo app used to render like this:

<img width="387" alt="A bright purple button." src="https://github.com/flutter/flutter/assets/551196/795a1252-9ebe-4771-9aba-2d0afff12cef">

As of https://github.com/flutter/flutter/pull/144273 (cc @QuncCccccc), it renders like this:

<img width="387" alt="Desaturated purple button." src="https://github.com/flutter/flutter/assets/551196/5e32a1cc-e43d-44e1-9a26-5b07162f6961">

There doesn't seem to be any way to get the old rendering anymore.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(255, 101, 89, 245)),
      ),
      title: 'Button Color Test',
      home: FilledButton(
        onPressed: () {},
        child: const Text(
          'Hello World',
        ),
      ),
    );
  }
}
```

**Comment by Hixie** [comment]
Ah, ok, cool. What should we tell folks whose apps just got more desaturated if they want the erstwhile brighter colors for their apps? (Assuming they don't know anything about material schemes and SchemeFidelity and all that.)

**Comment by QuncCccccc** [comment]
> Ah, ok, cool. What should we tell folks whose apps just got more desaturated if they want the erstwhile brighter colors for their apps? (Assuming they don't know anything about material schemes and SchemeFidelity and all that.)

Currently, material color utilities package supports [several variants](https://github.com/material-foundation/material-color-utilities/tree/main/dart/lib/scheme)(except the scheme.dart) for `DynamicScheme`. I'm thinking, since `ColorScheme.fromSeed` has migrated to use the updated `SchemeTonalSpot` which is also one of the variants, we can add an optional parameter(like a enum `schemeVariant`) to this method for different variants. So if users do need to keep the "fidelity" of the ColorScheme, then we suggest them to change the default variant from `SchemeTonalSpot` to `SchemeContent` or `SchemeFidelity`:)

For now, since we haven't added the support yet, a temp workaround would be directly use the `DynamicScheme` from material color utility package to build a `ColorScheme`. For example:

<details><summary>Build a ColorScheme by SchemeFidelity</summary>

```dart
    ColorScheme buildColorSchemeBySchemeFidelity(Color seedColor, Brightness brightness) {
      // SchemeFidelity can be changed to other variants.
      final SchemeFidelity scheme;
      switch (brightness) {
        case Brightness.light:
          scheme = SchemeFidelity(sourceColorHct: Hct.fromInt(seedColor.value), isDark: false, contrastLevel: 0.0);
        case Brightness.dark:
          scheme = SchemeFidelity(sourceColorHct: Hct.fromInt(seedColor.value), isDark: true, contrastLevel: 0.0);
      }

      return ColorScheme(
        primary: Color(MaterialDynamicColors.primary.getArgb(scheme)),
        onPrimary: Color(MaterialDynamicColors.onPrimary.getArgb(scheme)),
        primaryContainer: Color(MaterialDynamicColors.primaryContainer.getArgb(scheme)),
        onPrimaryContainer: Color(MaterialDynamicColors.onPrimaryContainer.getArgb(scheme)),
        primaryFixed: Color(MaterialDynamicColors.primaryFixed.getArgb(scheme)),
        primaryFixedDim: Color(MaterialDynamicColors.primaryFixedDim.getArgb(scheme)),
        onPrimaryFixed: Color(MaterialDynamicColors.onPrimaryFixed.getArgb(scheme)),
        onPrimaryFixedVariant: Color(MaterialDynamicColors.onPrimaryFixedVariant.getArgb(scheme)),
        secondary: Color(MaterialDynamicColors.secondary.getArgb(scheme)),
        onSecondary: Color(MaterialDynamicColors.onSecondary.getArgb(scheme)),
        secondaryContainer: Color(MaterialDynamicColors.secondaryContainer.getArgb(scheme)),
        onSecondaryContainer: Color(MaterialDynamicColors.onSecondaryContainer.getArgb(scheme)),
        secondaryFixed: Color(MaterialDynamicColors.secondaryFixed.getArgb(scheme)),
        secondaryFixedDim: Color(MaterialDynamicColors.secondaryFixedDim.getArgb(scheme)),
        onSecondaryFixed: Color(MaterialDynamicColors.onSecondaryFixed.getArgb(scheme)),
        onSecondaryFixedVariant: Color(MaterialDynamicColors.onSecondaryFixedVariant.getArgb(scheme)),
        tertiary: Color(MaterialDynamicColors.tertiary.getArgb(scheme)),
        onTertiary: Color(MaterialDynamicColors.onTertiary.getArgb(scheme)),
        tertiaryContainer: Color(MaterialDynamicColors.tertiaryContainer.getArgb(scheme)),
        onTertiaryContainer: Color(MaterialDynamicColors.onTertiaryContainer.getArgb(scheme)),
        tertiaryFixed: Color(MaterialDynamicColors.tertiaryFixed.getArgb(scheme)),
        tertiaryFixedDim: Color(MaterialDynamicColors.tertiaryFixedDim.getArgb(scheme)),
        onTertiaryFixed: Color(MaterialDynamicColors.onTertiaryFixed.getArgb(scheme)),
        onTertiaryFixedVariant: Color(MaterialDynamicColors.onTertiaryFixedVariant.getArgb(scheme)),
        error: Color(MaterialDynamicColors.error.getArgb(scheme)),
        onError: Color(MaterialDynamicColors.onError.getArgb(scheme)),
        errorContainer: Color(MaterialDynamicColors.errorContainer.getArgb(scheme)),
        onErrorContainer: Color(MaterialDynamicColors.onErrorContainer.getArgb(scheme)),
        outline: Color(MaterialDynamicColors.outline.getArgb(scheme)),
        outlineVariant: Color(MaterialDynamicColors.outlineVariant.getArgb(scheme)),
        surface: Color(MaterialDynamicColors.surface.getArgb(scheme)),
        surfaceDim: Color(MaterialDynamicColors.surfaceDim.getArgb(scheme)),
        surfaceBright: Color(MaterialDynamicColors.surfaceBright.getArgb(scheme)),
        surfaceContainerLowest: Color(MaterialDynamicColors.surfaceContainerLowest.getArgb(scheme)),
        surfaceContainerLow: Color(MaterialDynamicColors.surfaceContainerLow.getArgb(scheme)),
        surfaceContainer: Color(MaterialDynamicColors.surfaceContainer.getArgb(scheme)),
        surfaceContainerHigh: Color(MaterialDynamicColors.surfaceContainerHigh.getArgb(scheme)),
        surfaceContainerHighest: Color(MaterialDynamicColors.surfaceContainerHighest.getArgb(scheme)),
        onSurface: Color(MaterialDynamicColors.onSurface.getArgb(scheme)),
        onSurfaceVariant: Color(MaterialDynamicColors.onSurfaceVariant.getArgb(scheme)),
        inverseSurface: Color(MaterialDynamicColors.inverseSurface.getArgb(scheme)),
        onInverseSurface: Color(MaterialDynamicColors.inverseOnSurface.getArgb(scheme)),
        inversePrimary: Color(MaterialDynamicColors.inversePrimary.getArgb(scheme)),
        shadow: Color(MaterialDynamicColors.shadow.getArgb(scheme)),
        scrim: Color(MaterialDynamicColors.scrim.getArgb(scheme)),
        surfaceTint: Color(MaterialDynamicColors.primary.getArgb(scheme)),
        brightness: brightness,
        // DEPRECATED (newest deprecations at the bottom)
        background: Color(MaterialDynamicColors.background.getArgb(scheme)),
        onBackground: Color(MaterialDynamicColors.onBackground.getArgb(scheme)),
        surfaceVariant: Color(MaterialDynamicColors.surfaceVariant.getArgb(scheme)),
      );
    }
```

**Comment by Hixie** [comment]
I've been reading the material-color-utilities code for a while and I still have no clue what all these words (schemes, tonal spots, fidelities) mean in this context. Without using Material terminology, can you describe what the difference between today's "ColorScheme.fromSeed" and the "buildColorSchemeBySchemeFidelity" function (or the old "ColorScheme.fromSeed" constructor) is? (I'm trying to figure out what to name "buildColorSchemeBySchemeFidelity" in a way that our developers will understand what it does that's different than "fromSeed".)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/144805 introduces a new constructor that has behaviour more like the old one for people who want brighter color schemes.

**Comment by QuncCccccc** [comment]
Ah yes, after the migration, the new `ColorScheme.fromSeed()` might prevent colors from appearing as intended, an example is the lighter blue color(`Color.fromARGB(255, 101, 89, 245)`) in this issue, the output is adjusted from the lighter version to a darker version. I think the change of the migration is just to prevent a too vibrant palette. If we do want to respect the input color as much as possible, `SchemeFidelity` is a good choice! It generate a ColorScheme whose primary color can be better matched to the input color(seed), and make sure the visual contrast at the same time:)

For other variants, I still need to talk with people on Material team about their use cases because currently I don't see other variants are mentioned on the [Material Design](https://m3.material.io/styles/color/system/overview) website. If it's not worth to support all variants, we can just use a flag to enable or disable the fidelity feature(enabling color fidelity means we just want the result to be similar to the input color, even if we provide a super light color).
