### ISSUE TITLE
IOS auto scrolling issue with sliver app bar.

### ISSUE THREAD

**Issue by Aadesh1803** [flutter/flutter#144672]
I have created one project in which i am having sliverappbar and at the bottom of it i am having horizonal and vertical listview. when i try to click horizontal listview the vertical listview scrolls automatically. 

Note :- It is working fine in android

Please revert asap. waiting for your positive response.

below is my code and screen recording for issue. 

Url of demo code :- https://github.com/Aadesh1803/ios-demo

https://github.com/flutter/flutter/assets/131435534/2bdebc8d-0dd0-4fa9-9094-80f6e498a900

**Comment by huycozy** [comment]
Hi @Aadesh1803 
The goal of this Github repo is not to assist in personal code or the whole project but to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please update the issue's description with all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

**Comment by Aadesh1803** [comment]
@huycozy , I have tried all possible way in latest flutter version and all other ways. but facing same issue for IOS. can anyone help me to solve this issue.

**Comment by huycozy** [comment]
Please provide the following information so that we can verify the issue properly:
- Your code above is a whole complex project. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
