### ISSUE TITLE
Drop in vsync transitions missed metric after multi view change

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144885]
On the engine roll here https://github.com/flutter/flutter/pull/144747

containing the multi-view PR here https://github.com/flutter/engine/pull/51186

SkiaPerf reports a drop in vsync transitions missed:

https://flutter-flutter-perf.skia.org/e/?begin=1707869484&end=1709988985&keys=X135820acb66a212a4462010930f7d7ea&requestType=0&selected=commit%3D39665%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_vsync_transitions_missed%252Ctest%253Dcomplex_layout_scroll_perf__timeline_summary%252C&xbaroffset=39700

Is this a problem?

**Comment by jonahwilliams** [comment]
Possibly something has broken with the SceneDisplayLag timeline event:

https://github.com/flutter/flutter/blob/b7b1857ca4b65ca207b9b19c542ace431c2d1281/packages/flutter_driver/lib/src/driver/scene_display_lag_summarizer.dart#L13-L33

**Comment by dkwingsmt** [comment]
I'm taking a look. Thanks for pointing out the event name. The event is dispatched at the end of `Rasterizer`, which is indeed touched by the PR.
https://github.com/flutter/engine/blob/bbe58763793a70de9a2a8927d028f41cacffa12c/shell/common/rasterizer.cc#L484

**Comment by goderbauer** [comment]
I've been looking at some traces the benchmark uploaded on luci before and after the change in question. In the trace it looks like the metrics on the SceneDisplayLag event are calculated correctly for all frames that have a lag (about 5 or 6 in the benchmark), _except_ for the lag of the warmup-frame. In the trace I looked at, the warm-up frame misses over 200 vsync transitions (from the first vsync request the engine ever sees until the warm-up frame is finally rendered on screen as the first frame), but is reported as just missing 2 or 3 transitions.

Based on this, @dkwingsmt was speculating that with the change the metric recorder may be resetting the target frame time for the warm-up frame at some point instead of recording the target frame time of the very first vsync for it. He's investigating it further.

Here's a trace I looked at from before the change. It reports the SceneDisplayLag of the warm-up frame as 200+ missed transitions: https://storage.googleapis.com/flutter_logs/flutter/95bf597afe60993f947b1e44371d1ba1f9ed86c0/windows_home_scroll_perf__timeline_summary/54ecfcc4-2aca-4e09-b956-e8367bc09dff/home_scroll_perf.timeline.json

Here's a trace from after the change. It reports the SceneDisplayLag of the warm-up frame as 2: https://storage.googleapis.com/flutter_logs/flutter/8ade81fb201ae556b31dd6ab6a0b8cdcbf72b99b/windows_home_scroll_perf__timeline_summary/11ea0d0c-f98f-40a3-b398-1b239b452e21/home_scroll_perf.timeline.json

For best results load the traces into chrome://tracing and look for the first `SceneDisplayLag`.

**Comment by jonahwilliams** [comment]
I think we probably don't care about SceneDisplayLag for the warmup frame right?

**Comment by dkwingsmt** [comment]
> I think we probably don't care about SceneDisplayLag for the warmup frame right?

I don't think we should. And if the number drops by so much with the warm up frame excluded, then the warm-up frame's this metric is definitely impeding our ability to monitor that of the regular frames.

To further illustrate how this works, https://github.com/flutter/engine/pull/51347 is a PR that will revert the metric drop. See the PR body for explanation. My local test shows that `99th_percentile_vsync_transitions_missed` rises from 4.5 to 131.0 with this PR.

If necessary, we can merge this PR (after I productionize it) to verify that the multi-view work has not impacted this metric and then revert the PR to make this metric really usable. However, I doubt if it makes any difference since the metric does not show the frame miss of regular frames before and today. We've never monitored it.

The only way to show that the multi-view work has not impacted the frame miss _for regular frames_ is to revert the multi-view pipeline change (again) and eliminate the warm-up frame from the metric, and reland the multi-view pipeline change, which I, obviously, hope we don't choose.

**Comment by goderbauer** [comment]
What is the SceneDisplayLag for the warm-up frame now measuring? Is it the lag from when the framework requested the frame until the frame was displayed on the screen?

As long as we understand what the SceneDisplayLag is now measuring for the warm-up frame and it is something sensible I'd be ok with just leaving this as-is. The previous way of how we reported SceneDisplayLag for the warm-up frame didn't make much sense.

FWIW, I spot checked the SceneDisplayLag in 2 traces before and after the pipeline change landed. For non-warm-up-frames it is not showing any difference. So, I don't think we need to revert that change.

**Comment by jonahwilliams** [comment]
It sounds like this is working as expected and is a net improvement, thanks!

**Comment by dkwingsmt** [comment]
Thank you!
