### ISSUE TITLE
[cross_file] Add `create` in XFile

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#144877]
### Use case

Like [`File.create`](https://api.flutter.dev/flutter/dart-io/File/create.html), a `create` function is needed to create a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).

### Proposal

n/a

**Comment by stuartmorgan** [comment]
> ### Use case
> Like [`File.create`](https://api.flutter.dev/flutter/dart-io/File/create.html), a `create` function is needed to create a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).

This is a proposal; what is the use case?

**Comment by mbfakourii** [comment]
> > ### Use case
> > Like [`File.create`](https://api.flutter.dev/flutter/dart-io/File/create.html), a `create` function is needed to create a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).
> 
> This is a proposal; what is the use case?

In some cases, you need to create a file. This function is available in `File`, so I suggest adding it to cross_file.

**Comment by stuartmorgan** [comment]
> In some cases, we need to create a file.

Please give a specific example of a use case for creating a new file via `XFile`, and what precisely you would expect it to do on each platform. Given that the purpose of `XFile` is to provide an abstraction around a variety of file-like operations for different backends, not all of which are things that would normally be thought of as files, it's not clear to me what the expected behavior of `create` would even be (or what its arguments would be).

> This function is available in `File`, so I suggest adding it to cross_file.

`XFile` and `File` are different things, with distinct semantics, which is why `XFile` exists in the first place; if it were conceptually identical to `File`, we would just use `File`.
