### ISSUE TITLE
Youtube video is playing in the background despite the user moving to the next section . 

### ISSUE THREAD

**Issue by 2707sukesh** [flutter/flutter#144868]
### Steps to reproduce

1 . on the your first react app page . select the 1st step which is introduction . 
2 . under this section there is a youtube video 
3 . play the youtube video and move to the next step
4. the video is still playing despite the user moving to the next section . in the background

### Expected results

the video should be stopped if the user moves to the next section . and only play as long as its erlevant to the section the user is seeing.

### Actual results

the video is played in the background

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @2707sukesh 
Please try to provide all information indicated in the template so that we can address the issue properly. More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
