### ISSUE TITLE
module_test_ios failing on AppAuth 1.7.0 update

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144860]
Failures [like this](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20module_test_ios/10761/overview):

```
ARC Semantic Issue (Xcode): No visible @interface for 'OIDTokenRequest' declares the selector 'initWithConfiguration:grantType:authorizationCode:redirectURL:clientID:clientSecret:scope:refreshToken:codeVerifier:additionalParameters:'     /opt/s/w/ir/x/t/flutter_module_test.2qv8Dg/hello/.ios/Pods/GTMAppAuth/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility.m:136:31
```

started happening following the release of AppAuth version 1.7.0: https://github.com/openid/AppAuth-iOS/releases/tag/1.7.0

This version is picked up by the dependency specified by the squiggle arrow here:

https://github.com/google/GoogleSignIn-iOS/blob/aa71a74f10f7d5fe0241c7ff661a60cf78ccc338/GoogleSignIn.podspec#L36.

By way of the version specified by the google_sign_in plugin here:

https://github.com/flutter/packages/blob/d489d84c359b5ad6849ece9b97c75e1925ed762d/packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec#L18

From the pubspec.yaml of the module test app here:

https://github.com/flutter/flutter/blob/0432a6941da2b5fc028f107c4cd012188bd618b4/dev/devicelab/bin/tasks/module_test_ios.dart#L202

Updating to a newer version of the google_sign_in pub package does not resolve the issue.

cc @stuartmorgan @jason-simmons @jmagman @vashworth
cc @QuncCccccc the framework gardener.

**Comment by zanderso** [comment]
Moving this test to `bringup: true` in https://github.com/flutter/flutter/pull/144861

**Comment by stuartmorgan** [comment]
https://github.com/openid/AppAuth-iOS/pull/825

Looks like this should be fixed now, modulo any CDN propagation delay.

**Comment by marcellocamara** [comment]
Same problema here

![Captura de Tela 2024-03-09 às 00 41 37](https://github.com/flutter/flutter/assets/18273071/b0de883e-de71-41ab-aa68-5f2967342eea)

I've temporary fixed it with this line at pubspec.yaml:
```
dependency_overrides:
  webview_flutter_wkwebview: 3.5.0
```
If you gonna try it, remember to clean project and ios/pods, podfile.lock and .symlinks

**Comment by stuartmorgan** [comment]
> modulo any CDN propagation delay

There may also be machine-level caching issues. I've never been quite clear when Cocoapods will use a (potentially stale) machine-level cache of pods instead of fetching an updated list. flutter/packages is still seeing occasional failures due to this.

**Comment by stuartmorgan** [comment]
Downgrading since this is basically fixed.

There's nothing to do from the ecosystem side here; we wouldn't pin 3rd-order transitive dependencies that we have no direct use of, as that would be very confusing, especially since this is not Flutter-specific.

If the framework team wants to insulate the test against the possibility of this happening again, someone could do exact pinning in the dependencies within the test, where it wouldn't affect package clients.

**Comment by goderbauer** [comment]
@jmagman You're listed as the TESTOWNER for this test. Can you take a look and see if we should do what is suggested above?

**Comment by jmagman** [comment]
> > modulo any CDN propagation delay
> 
> There may also be machine-level caching issues. I've never been quite clear when Cocoapods will use a (potentially stale) machine-level cache of pods instead of fetching an updated list. flutter/packages is still seeing occasional failures due to this.

This test already runs `pod repo update` because I, too, was tired of dealing with stale caches.

https://github.com/flutter/flutter/blob/4dc2ea3e3593ca304b9b78aca7091dbc8133c32f/dev/devicelab/bin/tasks/module_test_ios.dart#L20-L24




> If the framework team wants to insulate the test against the possibility of this happening again, someone could do exact pinning in the dependencies within the test, where it wouldn't affect package clients.

This is possible, but would be kind of tricky since it's happening in Podfiles that are being generated programmatically, and if `google_sign_in_ios` _did_ at some point to pin the 3rd party transitive dependency (as sometimes happens) then this test would fail again and the pinning in the framework would also need to be updated.

I'm going to close this as resolved and unmark the test as flaky. I haven't seen this kind of issue happen too often, where we wouldn't want to also pin in the plugin.
