### ISSUE TITLE
[web] flutter_js assets not being copied in some engine tests.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#144969]
### Type of Request

bug

### Infrastructure Environment

`felt` tests (flutter/engine tests on the web platform)

### What is happening?

It seems that some `felt` test suites are not re-generating the `flutter_js` asset as needed. This makes them order-dependent with other bits of the testing infrastructure of the repo (and seemingly random when validating locally). For example:

* `test/fallbacks/fallbacks_test.dart`

### Steps to reproduce

On a flutter/engine checkout:

1. Remove `src/out/web_tests` to remove all the test-related stuff
2. Attempt to run the test above: `felt test test/fallbacks/fallbacks_test.dart`
   * The test will time-out after 12 minutes.
3. ... Alternatively, for more output: `felt test --debug --start-paused test/fallbacks/fallbacks_test.dart`
   * Look at the network panel, and you'll see that the `fluter_js/flutter.js` is a 404 error.
4. Also check how: `src/out/web_tests/artifacts/flutter_js` doesn't exist.

To recover from this, you may run other suite:

1. Run: `felt test test/engine/canvas_test.dart`
2. Check `src/out/web_tests/artifacts/flutter_js` now.

### Expected results

I'd expect to be able to run `test/fallbacks/fallbacks_test.dart` without needing side effects from other tests existing first.

**Comment by eyebrowsoffire** [comment]
I am not reproducing this issue. I did the following steps.
* `git pull` on the main engine branch
* `gclient sync -D`
* `felt build`
* `felt test test/fallbacks/fallbacks_test.dart`

`flutter.js` seems to copy over to `out/web_tests` without issue for me, and the tests run and pass on all browsers.

I should note that you need to run `felt build` in order to actually build `flutter.js` itself, and if you do `felt test --debug` that means "use the `wasm_debug_unopt` build artifacts". If you haven't run `felt build --debug` then `felt test --debug` will fail.

**Comment by ditman** [comment]
You're right, I cannot reproduce anymore, must have been the `--debug` flag without having done a `flutter build --debug` first.

Not sure how I managed to get to the 12 minute timeout, must have been some of my changes in the flutter.js file itself :/
