### ISSUE TITLE
[shared_preferences]Privacy Manifests support timing

### ISSUE THREAD

**Issue by vfjhanashima** [flutter/flutter#145063]
Apple has announced that it will reject apps that do not support Privacy Manifests from May 1.

Reference URL
https://developer.apple.com/news/?id=3d8a9yyh

When will [shared_preferences] release a new version with Privacy Manifests support?

**Comment by danagbemava-nc** [comment]
shared_preferences already includes privacy manifest. This was added in shared_preferences_foundation 2.3.5. You should run `flutter pub upgrade` if you aren't already on this version. 

If you do run into an issue with the latest version of shared_preferences & `shared_preferences_foundation`, please file a new issue and provide the relevant details. 

I'll be closing this since privacy manifests have already been added to the plugin. 

Thank you

https://pub.dev/packages/shared_preferences_foundation/changelog#235
https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences_foundation/darwin/Resources/PrivacyInfo.xcprivacy

**Comment by vfjhanashima** [comment]
[thank you for the reply](https://ejje.weblio.jp/content/thank+you+for+the+reply)
