### ISSUE TITLE
j'ai fais toutes les mises a jours mais cette erreur persiste meme quand je change de version

### ISSUE THREAD

**Issue by 93cory** [flutter/flutter#145188]
Resolving dependencies...
The current Dart SDK version is 3.3.1.

Because biodiv requires SDK version >=3.21.0 <4.0.0, version solving failed.
Process finished with exit code 1

**Comment by huycozy** [comment]
Hi @93cory, 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

More specifically:
- Please provide the output of `flutter doctor -v`
- Could you share your `pubspec.yaml` file content?
