### ISSUE TITLE
flutter devices --machine prints upgrade banner breaking machine parsing

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#145158]
Running 'et run' failed with the following error. When flutter is invoked with --machine we shouldn't print out the human upgrade banner.

```
[2024-03-14 09:06:20.309447] ERROR: Failed to parse flutter devices output: FormatException: Unexpected character (at line 2, character 1)
┌─────────────────────────────────────────────────────────┐
^



┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[
  {
    "name": "sdk gphone64 arm64",
    "id": "emulator-5554",
    "isSupported": true,
    "targetPlatform": "android-arm64",
    "emulator": true,
    "sdk": "Android 14 (API 34)",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": true,
      "flutterExit": true,
      "hardwareRendering": true,
      "startPaused": true
    }
  },
  {
    "name": "macOS",
    "id": "macos",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4 23E214 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Mac Designed for iPad",
    "id": "mac-designed-for-ipad",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4 23E214 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Chrome",
    "id": "chrome",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Google Chrome 123.0.6312.46",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  }
]
```

**Comment by zanderso** [comment]
@christopherfujino Does the tool have a flag to suppress the upgrade check?

**Comment by christopherfujino** [comment]
Hmm, looks like the intention is to skip the check if we're in machine mode: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L326

Must be a bug.

**Comment by bartekpacia** [comment]
I worked around this in a CLI tool I wrote by running `flutter --no-version-check devices --machine`. But yeah, would be great if it was fixed.

**Comment by zanderso** [comment]
I wonder if this could happen on the first run of the tool after checking out or updating the framework repo from git when the tool is compiled to the app-jit snapshot here: https://github.com/flutter/flutter/blob/master/bin/internal/shared.sh#L171.

It seems dubious though since the output is redirected to `/dev/null` ...

**Comment by zanderso** [comment]
The tool defines the `--machine` flag twice =(

There's a top-level flag, which is what is checked by:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L326

Then the `devices` command defines its own version of the flag:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/devices.dart#L17

The logic that decides to skip the version check in the presence of the `--machine` flag is looking for the flag at the `top-level`, and isn't aware if/when the `--machine` flag is passed to the `devices` command.

Ideally, instead of defining its own `--machine` flag, the `devices` command should just look for the top-level flag. Unfortunately, that would be a breaking change since it would change the location on the command line where the `--machine` flag goes. To do a soft breaking change, as an intermediate step, the logic in `flutter_command_runner.dart` should look to see if `--machine` has been passed *anywhere* on the command line, and not just as a top-level flag.

**Comment by matanlurey** [comment]
I _thought_ `package: args` was relaxed about flag location, I need to double check.

I can volunteer in either case to get the bug fixed at the tools level.

**Comment by matanlurey** [comment]
I paired with @jonahwilliams for a few minutes, and I'm out of 🧠 power to fix this today, but tl;dr there are [_multiple_ different commands that support `--machine`](https://github.com/search?q=repo%3Aflutter%2Fflutter+path%3A%2F%5Epackages%5C%2Fflutter_tools%5C%2F%2F+%2F%27machine%27%2F&type=code) today, so it's likely non-viable (without a much bigger undertaking) to deprecate and refactor down. I can file a bug, but can't commit to fixing it

To fix this _specific_ problem we'd modify the [check for machine](https://github.com/flutter/flutter/blob/4c35ab5879d4de61d12bec227f9fe5ae2e6a807d/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L325) to, as @zanderso mentioned, look for `--machine` being present _anywhere_ in the command-line arguments, not just the root command.

**Comment by johnmccutchan** [comment]
Would running the following work:

`flutter --machine devices --machine` 

?
