### ISSUE TITLE
Direct Navigation to Add Home Widget Screen on iOS

### ISSUE THREAD

**Issue by ssorrychoi** [flutter/flutter#145209]
### Use case

Hello,

I'm currently working on a Flutter app for iOS, and I was wondering if there's an existing function similar to openAppSettings(), which redirects users directly to the iPhone's settings screen. Specifically, I'm interested in a Flutter function that could directly navigate users to the screen for adding home screen widgets on iOS.

The openAppSettings() function is incredibly useful for guiding users to enable or adjust necessary permissions for the app directly within the iPhone's settings. Similarly, it would be beneficial to have a straightforward way to lead users to the "Add Widget" screen, enhancing user experience by simplifying the process of adding widgets related to our app.

Is there currently any function or workaround available in Flutter that supports this feature? If not, could this be considered for future development? This functionality would significantly help in promoting user engagement with app widgets by making them more accessible and easier to add.

Thank you for considering this feature request.

### Proposal

The openAppSettings() function is incredibly useful for guiding users to enable or adjust necessary permissions for the app directly within the iPhone's settings. Similarly, it would be beneficial to have a straightforward way to lead users to the "Add Widget" screen, enhancing user experience by simplifying the process of adding widgets related to our app.

Thank you for considering this feature request.

**Comment by PauloAlves311** [comment]
This package seems to do the work: https://pub.dev/packages/app_settings

Not sure if it works for your case.

**Comment by huycozy** [comment]
Hi @ssorrychoi 
I see there are two different proposals: `openAppSettings` and `Add Home Widget`. For further proposals/issues, please file separate issues for better tracking.

For `openAppSettings`, please check `app_settings` as @PauloAlves311 shared above. For `Add Home Widget`, please check [home_widget](https://pub.dev/packages/home_widget) package.

Since not every functionality/feature can be a part of the framework itself, hence there are community packages that help to bridge the gap. If you still believe these functionalities should be a part of Flutter framework, please file separate issues for each one. One each issue, please try to clarify all things requested in the [proposal template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml). Thanks!
