### ISSUE TITLE
a11y: send less TYPE_WINDOW_CONTENT_CHANGED events

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#14534]
TYPE_WINDOW_CONTENT_CHANGED should only be called for the root node of a subtree that has changed (NOT for every changed node in the subtree). Doing the latter causes a11y to become sluggish and unresponsive as Android processes the flood of events.

We are currently firing the event for every single changed node, which on big updates (e.g. scrolling through a list with lots of nodes) causes unresponsiveness.

**Comment by goderbauer** [comment]
As a work around, I am only firing the event once for the root node. That resolves the unresponsiveness due to the flood of events. This can be optimized in the future by figuring out specific subtrees and firing the event only for those.

**Comment by cbracken** [comment]
@goderbauer is it worth keeping this issue open? My understanding from our discussion on Friday was that after discussion with Android folks about the alternative of sending one event per modified subtree rather than just one for the root node, was that the additional overhead of firing multiple events and small additional complexity of the code made it not worthwhile.

**Comment by goderbauer** [comment]
Closing this sounds good.
