### ISSUE TITLE
Flutter Web: Embind reports leak of Typeface with CanvasKit

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#145352]
### Steps to reproduce

Turn on -sSAFE_HEAP and -sASSERTIONS on the Canvaskit wasm build and do something that loads a font and renders text (I used google fonts package) with the wasm build selected as the local engine.

### Expected results

Typeface doesn't leak

### Actual results

Typeface leaks:

```dart

canvaskit.js:129 Embind found a leaked C++ instance Typeface <0x00227930>.
We'll free it automatically in this case, but this functionality is not reliable across various environments.
Make sure to invoke .delete() manually once you're done with the instance instead.
Originally allocated
    at Function._MakeTypefaceFromData (http://localhost:10803/canvaskit/chromium/canvaskit.js:141:227)
    at a.Typeface.MakeTypefaceFromData (http://localhost:10803/canvaskit/chromium/canvaskit.js:82:299)
    at g.TypefaceFontProvider.registerFont (http://localhost:10803/canvaskit/chromium/canvaskit.js:71:455)
    at Object.TypefaceFontProviderExtension$124registerFont [as TypefaceFontProviderExtension|registerFont] (http://localhost:10803/dart_sdk.js:202827:18)
    at [_registerWithFontProvider] (http://localhost:10803/dart_sdk.js:151213:64)
    at _engine.SkiaFontCollection.new.registerDownloadedFonts (http://localhost:10803/dart_sdk.js:151328:38)
    at _engine.SkiaFontCollection.new.loadAssetFonts (http://localhost:10803/dart_sdk.js:151304:14)
    at loadAssetFonts.next (<anonymous>)
    at http://localhost:10803/dart_sdk.js:48832:33
    at _RootZone.runUnary (http://localhost:10803/dart_sdk.js:48689:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:10803/dart_sdk.js:44085:29)
    at handleValueCallback (http://localhost:10803/dart_sdk.js:44689:49)
    at _Future._propagateToListeners (http://localhost:10803/dart_sdk.js:44727:17)
    at [_completeWithValue] (http://localhost:10803/dart_sdk.js:44568:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:10803/dart_sdk.js:44602:35)
    at Object._microtaskLoop (http://localhost:10803/dart_sdk.js:49145:13)
    at _startMicrotaskLoop (http://localhost:10803/dart_sdk.js:49151:13)
    at http://localhost:10803/dart_sdk.js:44951:9
    
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
> -sSAFE_HEAP and -sASSERTIONS on the Canvaskit wasm build

Could you please elaborate on this? 

I assume that this error can be reproduced with a simple text using the google fonts package as shown below. If not, please share a minimal sample code. Thanks!

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Text(
            'This is Google Fonts',
            style: GoogleFonts.lato(),
          ),
        ),
      ),
    ),
  );
}

```

**Comment by jezell** [comment]
@huycozy this is a compiler option that can be used when compiling the engine which prints out when memory leaks happen. It can be turned on here in a custom canvaskit build:

https://github.com/flutter/engine/blob/main/skia/modules/canvaskit/BUILD.gn#L162

I enabled this setting to help track down some memory leaks and bugs we were seeing in our apps, and it is reporting a memory leak is happening. I believe that code sample should be sufficient, but to get the debug build you need to turn on those options in the .gn file and then use felt to rebuild the engine and run your sample against the local engine.

**Comment by huycozy** [comment]
Thanks for the update. Unfortunately, I have my issue with Python 12 when building local engine (it was working before), so I can't replicate this right now, but I will give it a try later. 

In the meantime, I will label the issue for other's thoughts. Could you please also share the `engine hash` you are building at, along with the output of `flutter doctor -v` that may help others looking at this issue can have more information to investigate further?

**Comment by johnmccutchan** [comment]
@jezell hey, I just wanted to provide some more context as why we can't enable or exceptions and why trying to recover from a malloc failure is a bad idea:

*) Every professional C++ project I have worked on has explicitly disabled C++ exceptions. The [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#Exceptions) has some context as to why we've made this choice

*) Recovering from a malloc failure is not feasible in a large software project. Imagine if every place we called malloc() we had some code that handles the NULL case and tries to recover. This code wouldn't be well tested because we can't easily make specific malloc() calls fail, so we would end up with a really complicated code base with error handling code that _never_ actually runs -- and thus is guaranteed to contain bugs. 

The Flutter project will never enable C++ exceptions and we simply cannot litter our codebase with attempts to recover from memory allocation failures. 

My 2c is that the WASM runtime is bugged if a call to abort() doesn't terminate the program.

I strongly recommend that you do not compile the engine with C++ exceptions enabled or other changes discussed in this bug because we simply can't support those builds.
