### ISSUE TITLE
Edge-To-Edge not working after immediate app relaunch

### ISSUE THREAD

**Issue by yadavmanishraj** [flutter/flutter#145642]
### Steps to reproduce

1. Open App that uses edge to edge and transparent navigation bar and status bar
2. Close and reopen immediately 

### Opening App and closing app using back button and then opening app immediately

![Screenshot_2024-03-24-00-05-00-630_com quantumbyte melodia](https://github.com/flutter/flutter/assets/113776481/4c109184-1d66-483a-bc70-d5882d16fa3b)

###  The status bar has a shadow, and the gesture bar is black.
![Screenshot_2024-03-23-23-49-22-384_com quantumbyte melodia](https://github.com/flutter/flutter/assets/113776481/28510097-b841-45e4-81e0-008c458681c9)

**Comment by huycozy** [comment]
Hi @yadavmanishraj 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)). More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- The affected device info (OS, model)
