### ISSUE TITLE
[google_sign_in] Update GoogleSignIn iOS pod version to use one with a privacy manifest

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#145777]
Update google_sign_in podspec to [`s.dependency 'GoogleSignIn', '~> 7.1'`](https://github.com/flutter/packages/blob/01d16a467d9e2f8d759f15bcf4b0c856113cd705/packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec#L18), which is the first version that has a [privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).  This will prevent developers from getting warnings on iOS App Store submission.

https://github.com/google/GoogleSignIn-iOS/releases/tag/7.1.0

> Add Privacy Manifest (https://github.com/google/GoogleSignIn-iOS/pull/382)

7.1 minimum version is [iOS 10 and macOS 10.15](https://github.com/CocoaPods/Specs/blob/e28d539fe4e87f391a4098f4bd2e044894208622/Specs/d/4/0/GoogleSignIn/7.1.0/GoogleSignIn.podspec.json#L17-L19) which is <= to the [existing google_sign_in versions,](https://github.com/flutter/packages/blob/01d16a467d9e2f8d759f15bcf4b0c856113cd705/packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec#L22-L23) so that won't be an issue.

See also https://github.com/flutter/flutter/issues/137140

**Comment by stuartmorgan** [comment]
Recording here since I always forget what exactly `~>` does and have to look it up: `~> 7.0` is compatible with 7.1, so this is similar to https://github.com/flutter/packages/pull/6355 in that it makes it easier to get more people updated faster (since just editing `pubspec.yaml` to get the latest `google_sign_in` would then pull in 7.1 of the pod), but we aren't currently *blocking* anyone from getting the version with a manifest.
