### ISSUE TITLE
[Material ModalBottomSheet] Add customization for the animation curve to the ModalBottomSheet

### ISSUE THREAD

**Issue by matiasilveiro** [flutter/flutter#145704]
### Use case

As a Flutter developer, I want to be able to customize the transition animation when using the _showModalBottomSheet_ method. 
Currently, the default animation lacks customization options. By adding a "curve" parameter to the method, developers can choose a smooth or bouncy curve, enhancing the visual appeal of bottom sheets in Flutter.

### Proposal

I propose adding a "_curve_" parameter to the _showModalBottomSheet_ method in Flutter. This optional parameter would allow developers to customize the transition animation curve, providing a range of predefined curves or the ability to create custom ones using the Curve class. This would improve the user experience by enabling more visually appealing transitions.

**Comment by danagbemava-nc** [comment]
Hi @matiasilveiro, this has been fixed on the master channel. An animationStyle property has been added which will allow you to customize the animation of the bottom sheet. See https://main-api.flutter.dev/flutter/material/showModalBottomSheet.html

I'll be closing this since it has already been added on the master channel. It will make to stable some time in the future. 

Thank you
