### ISSUE TITLE
[Impeller] Start setup on Vulkan context earlier.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#145843]
Today, we depend on knowing the format of the root surface on Android till we can create the content context. Content context creation seeds the PSO libraries and they need a pixel format.

But, on Android, the surface format is always going to be R8G8B8A8. We can depend on this constant and begin parallel setup of the PSO libraries earlier.

**Comment by gaaclarke** [comment]
@jiahaog did some testing and noticed 1.7s dedicated to this on startup time and was wondering if we could move this earlier:
![AmXWrBgAjW6h2Ez](https://github.com/flutter/flutter/assets/30870216/b32eb270-7bf3-4e0e-bc85-a21f945a0b83)

**Comment by gaaclarke** [comment]
In lieu of starting the pipeline creation process earlier, we could unlatch its completion with the UI thread, instead synchronizing at the point where someone uses a pipeline.  That may incur a small overhead every time the pipeline is used but have much faster startup time.

**Comment by gaaclarke** [comment]
It looks like creating the PipelineVK's (PipelineVK::Create) is already decoupled in the sense that `PipelineLibraryVK::GetPipeline` already returns a future.  However `ContentContext::ContentContext` will launch all of those async operations then immediate synchronize on a subset of them because of `ContentContext::InitializeCommonlyUsedShadersIfNeeded`.

If we want to keep `ContentContext::InitializeCommonlyUsedShadersIfNeeded`, one optimization would be to make sure those commonly used shaders were the one that are at the top of the worker threads queue.  `ContentContext::InitializeCommonlyUsedShadersIfNeeded` may be a deoptimization itself.

**Comment by jonahwilliams** [comment]
This was done in https://github.com/flutter/engine/pull/52590
