### ISSUE TITLE
[in_app_purchase] Is there any way to handle promocode in flutter?

### ISSUE THREAD

**Issue by sumitagadhvi** [flutter/flutter#145820]
### Steps to reproduce

i have implemented subscription through [in_app_purchase](https://pub.dev/packages/in_app_purchase) in my flutter application. and i want to add feature of promo code in that so i have created promo code for Non Consumable in app product from google play console and i tried to buy the product through that promo code but its not working as it should work. i tried to find the proper documentation but got no Luck.

### Expected results

when we buy the product through promo code it should give order id for that transaction and it should reflect in Order Management.

### Actual results

I am not able to get the order id for that transaction and there is no history in Order Management of that purchase through Promo code. and i need order id to store the data and handle subscription in my application.

### Code sample

<details open><summary>Code sample</summary>

```dart
 late PurchaseParam purchaseParam;
    if (Platform.isAndroid) {
      final Map<String, PurchaseDetails> purchases =
          Map<String, PurchaseDetails>.fromEntries(
              _purchases.map((PurchaseDetails purchase) {
        if (purchase.pendingCompletePurchase) {
          _inAppPurchase.completePurchase(purchase);
        }
        return MapEntry<String, PurchaseDetails>(purchase.productID, purchase);
      }));
      final GooglePlayPurchaseDetails? oldSubscription =
          _getOldSubscription(productDetails, purchases);
      final uuid = Uuid();
      var userId = uuid.v4();
      purchaseParam = GooglePlayPurchaseParam(
          productDetails: productDetails,
          applicationUserName: userId,
          changeSubscriptionParam: (oldSubscription != null)
              ? ChangeSubscriptionParam(
                  oldPurchaseDetails: oldSubscription,
                  prorationMode: ProrationMode.immediateWithTimeProration,
                )
              : null);
    } else {
      purchaseParam = PurchaseParam(
        productDetails: productDetails,
      );
    }
    if (productDetails.title == subscriptionMonthly) {
      _inAppPurchase.buyConsumable(purchaseParam: purchaseParam);
    } else {
      _inAppPurchase
          .buyNonConsumable(purchaseParam: purchaseParam)
          .then((value) {});
    }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 12.7.1 21G920 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@sumitagadhvi 
Check [this](https://github.com/flutter/flutter/issues/91872) issue and underlying comments to see if they help in your case or not.
Also, you may follow-up in [this](https://github.com/flutter/flutter/issues/51757) issue for further updates.

**Comment by sumitagadhvi** [comment]
@darshankawar thank you so much for your quick reply. i have checked the first one issue and its underlying comments but this is what i already  have done for in app product and subscription purchase and its working fine in normal subscription scenario. i think this is not the solution for promo code issue. please if there is any another reference or documentation for this, it will help.

**Comment by darshankawar** [comment]
> its working fine in normal subscription scenario. i think this is not the solution for promo code issue.

Yes, that's what is mentioned / explained in [this](https://github.com/flutter/flutter/issues/91872#issuecomment-952885092) comment if you see the promo code vs normal subscription payment json.

Since you are not getting the `orderId`, the below comment explains it well as why is it happening:

`The above means that the Google Play Console never supplies the plugin with the order ID which means the in_app_purchase plugin is also not able to give it to you. Unfortunately I am unable to find any documentation on why this is the case for purchases using a promotion code. However in your question you mention you need the purchaseId to handle the validation of the purchase. Normally you would do this using the productId and the purchaseToken. A detailed explanation on how to set this up can be found in step 8 of the [In-App Purchase codelab](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#8).`

I suggest you to follow the codelab as listed in above comment and see if it helps in your case or not.
