### ISSUE TITLE
[pigeon] Allow a way to make generated swift classes be public

### ISSUE THREAD

**Issue by LouiseHsu** [flutter/flutter#146150]
When testing, usually the testing file it outside package/module. To reference functions that return the generated pigeon types, the types need to be public too.

**Comment by stuartmorgan** [comment]
Does importing with `@testable import` resolve this? That's what we've done in other cases instead.

**Comment by LouiseHsu** [comment]
Im trying to call them from an ObjC test file for some context

**Comment by stuartmorgan** [comment]
Hm, I would have though that just being internal wouldn't be an issue for Obj-C, since it generally doesn't enforce access restrictions.

What's the exact code you are trying to test, and the error you get trying to use it?

**Comment by LouiseHsu** [comment]
So I could be wrong, but to expose a swift func to ObjC you usually have to annotate it with `@ObjC`, like:
```
@objc
public func storefront() throws -> SKStorefrontMessage? {
///
}
```

However, I get the error "Method cannot be declared public because its result uses an internal type"

**Comment by stuartmorgan** [comment]
That's unfortunate. Could we instead convert the tests from Obj-C to Swift before the Swift conversion, so the order of migration is flipped?

The issue is that we really don't want people to be in the habit of publicly exposing Pigeon-generated code because we still make breaking changes to it relatively often. Exposing to tests isn't a big deal, but if we add the feature I'm sure people would use it for non-test cases (as we've had explicit requests for that, and have deliberately not added it).

**Comment by stuartmorgan** [comment]
@LouiseHsu Is this still blocking, or did you revisit the test conversion?
