### ISSUE TITLE
[Web] Able to retain browser session even after stopping the program

### ISSUE THREAD

**Issue by ztayluh** [flutter/flutter#146170]
### Use case

I may have other tabs open for research while working through my app.. If I decide I want to stop my app flutter closes EVERYTHING running on Chrome without any warning. This is a huge annoyance, especially if I am in the middle of writing something. It would be great to not to have to keep multiple different browsers open as a workaround for this. 

### Proposal

Only close the active tab that is running my app, or do nothing at all and I can close it on my own. Much better than losing work.

**Comment by iapicca** [comment]
I totally agree with @ztayluh 
I'd like to have an option to close or not the app on a closed tab
rather than the current behavior

I found myself to run the app with [dhttpd](https://pub.dev/packages/dhttpd)
to test the behavior of the tab closing and re-opening 
(eg: am I still logged-in, is my lang preference saved, etc)

**Comment by yjbanov** [comment]
The recommended way to do this is to use `-d web-server`. This will allow you to use your existing browser instance to test the app. You will lose hot restart, but that seems acceptable since you mean to exit the `flutter` tool anyway, which kills hot restart. `flutter run` opens the browser with a debug connection, which is essentially a backdoor into your browser. I strongly recommend against using the same debug browser instance for web browsing outside the app under test.
