### ISSUE TITLE
make different Texstyle in TimePickerThemeData

### ISSUE THREAD

**Issue by yousefak007** [flutter/flutter#146388]
hi, can you help me how to make different styles for hourMinuteTextStyle, I need to change the line height in the input filed

![image](https://github.com/flutter/flutter/assets/46021584/357326c1-afee-479e-bd57-9fa1f351336f)

![image](https://github.com/flutter/flutter/assets/46021584/b698166c-6ece-4fd9-b3ec-daad61048bdf)

without line height, this is the result:

![image](https://github.com/flutter/flutter/assets/46021584/85cb0b0d-9c98-472f-95cd-2caea4d373aa)

![image](https://github.com/flutter/flutter/assets/46021584/5469fe07-85b4-4900-bf54-8d14ce3aeba1)

_Originally posted by @yousefak007 in https://github.com/flutter/flutter/issues/131247#issuecomment-2041111359_

**Comment by iapicca** [comment]
@yousefak007 
this is probably the wrong channel for this request, you can find the link when you [open an issue](https://github.com/flutter/flutter/issues/new/choose) at the bottom

<img width="705" alt="image" src="https://github.com/flutter/flutter/assets/45637986/f9d0ecff-c6ee-4aa3-ab26-ecae048891f1">

**Comment by yousefak007** [comment]
hi @iapicca, I think this is an issue because TimePickerThemeData doesn't allow you to make different styles for different input modes, you just have `hourMinuteTextStyle` to make the TextStyle, and as you see in the images above, you can't manage the height of the line in input filed.

i need to make different line heights for hourMinuteTextStyle based on different input mode 

```dart
timePickerTheme: TimePickerThemeData(
             ...
              hourMinuteTextStyle:
                  FontTheme.r38.copyWith(height: 2),
            ..
),
```

**Comment by huycozy** [comment]
@yousefak007 I see the `height` still can be applied as the demo below (on Flutter 3.19.5):

<details>
<summary>Demo</summary>

![Screenshot 2024-04-08 at 15 57 02](https://github.com/flutter/flutter/assets/104349824/0cd3075e-ebed-45f5-933d-59f2a3be5415)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          timePickerTheme: const TimePickerThemeData(
        hourMinuteTextStyle: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, height: 3.0),
      )),
      home: const NewWidget(),
    ),
  );
}

class NewWidget extends StatelessWidget {
  const NewWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: const Text('Show'),
          onPressed: () {
            showTimePicker(context: context, initialTime: TimeOfDay.now());
          },
        ),
      ),
    );
  }
}

```
</details>

What is your current Flutter version? If your Flutter version is not the latest one, please try upgrading and retry. Otherwise, please provide all information indicated in the issue template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))
