### ISSUE TITLE
Flutter Project Hitting libc++_shared.so not found on Windows 11 Home

### ISSUE THREAD

**Issue by andrewooi99** [flutter/flutter#146503]
I am facing this "java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found" when i run logcat to capture the error happened as the app crashes during Android Emulator launching the app from Visual studio code. Tried multiple suggestions from online sources (stackoverflow, github issues) yet none resolved the problem. Sharing my `flutter doctor -v` result and part of build.gradle and Android Emulator combination that i had tried on.

Suggestion tried (but not solving the issue) : 

1. [stackoverflow https://stackoverflow.com/questions/60700169/enabling-libc-shared-so-to-be-enabled-in-the-opencv-android-application](https://stackoverflow.com/a/66404844/2926759)
2. https://github.com/flutter/flutter/issues/73943#issuecomment-1996576538
3. https://github.com/flutter/flutter/issues/73943

Part of my build.gradle

```
android {
       defaultConfig {
            ndk {
                 abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64', 'x86'
            }
            .
            externalNativeBuild {
                  cmake {
                          arguments "-DANDROID_STL=c++_shared"
                   }
            }
       }
       .       
       packagingOptions {
            pickFirst 'lib/x86/libc++_shared.so'
            pickFirst 'lib/x86_64/libc++_shared.so'
            pickFirst 'lib/armeabi-v7a/libc++_shared.so'
            pickFirst 'lib/arm64-v8a/libc++_shared.so'
            pickFirst 'lib/x86/libflutter.so'
            pickFirst 'lib/x86_64/libflutter.so'
            pickFirst 'lib/armeabi-v7a/libflutter.so'
            pickFirst 'lib/arm64-v8a/libflutter.so'
    }
}
```
![FlutterDoctor](https://github.com/flutter/flutter/assets/13635131/1a300bc5-4bf7-4b4e-aaa8-e99d6fddd399)

![AndroidEmulatorVersion](https://github.com/flutter/flutter/assets/13635131/f477010a-4f94-427b-a39d-daf200cb2b6a)

![image](https://github.com/flutter/flutter/assets/13635131/22bfbdd5-e654-4082-ab91-421c45bcd22e)

**Comment by huycozy** [comment]
Hi @andrewooi99 
Does the issue happen if you run on a physical Android device? Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so I can try reproducing it on my end?

_(Please provide info in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text).)_
