### ISSUE TITLE
Request for a Transaction example in the Cloud Firestore README

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#14655]
Hi! Can we add an example of transactions to https://pub.dartlang.org/packages/cloud_firestore ?

Here would be good: https://github.com/flutter/plugins/tree/master/packages/cloud_firestore

Thanks!

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by dac3971** [comment]
@sethladd any luck on finding an example of how to perform a simple transaction?

**Comment by dac3971** [comment]
can anyone tell me if this is the proper way to perform a transaction?  I'm getting this error "PlatformException(Error performing Transaction#get, Transaction has already completed., null)"

`Firestore.instance.runTransaction((Transaction tran){
        tran.get(postRef).then((DocumentSnapshot snap){
          if(snap.exists)
          tran.update(postRef, <String,dynamic>{"likesCount": snap.data['likesCount']+1});
          else
            print('nah son');
        });
      });`

**Comment by kroikie** [comment]
Hi @dac3971 you would need to pass in a `TransactionHandler` to `runTransaction`. Eg:

```
final TransactionHandler transactionHandler = (Transaction tran) {
  tran.get(postRef).then((DocumentSnapshot snap) {
    if (snap.exists) {
      tran.update(postRef, <String, dynamic>{'likesCount': snap.data['likesCount'] + 1});
    }
  });
};
Firestore.instance.runTransaction(transactionHandler);
```

**Comment by dac3971** [comment]
@kroikie hmm ..wouldn't that essentially be the same thing?  i'm still getting a "task is already complete" error...

**Comment by kroikie** [comment]
Ah you are right @dac3971 let me look deeper.

**Comment by kroikie** [comment]
@dac3971 are you seeing this issue on Android/iOS or both?

**Comment by dac3971** [comment]
@kroikie Android.

**Comment by dac3971** [comment]
@kroikie is this working for you yet? i'm now getting a different error:
`
E/AndroidRuntime(14446): Caused by: java.lang.IllegalArgumentException: Provided document reference is from a different Firestore instance.`

**Comment by zoechi** [comment]
See also the related SO question https://stackoverflow.com/questions/50280256/flutter-cloud-firestore-plugin-transactions-on-android

**Comment by zoechi** [comment]
@dac3971 I'd suggest to create a new issue for this error message

**Comment by jezer07** [comment]
any updates on this?

**Comment by varundroid** [comment]
I am still confused about what's the best way to know if the transaction was successful?

**Comment by dark-chocolate** [comment]
The issue was closed by @collinjackson but I can't see any solution yet. Am I missing something?

**Comment by iamjavademon** [comment]
So after banging my head on the wall, i decided to update my flutter and its fine now.

**Comment by DeepStyles** [comment]
Future _updateFavorite() async {
    Firestore.instance.runTransaction((Transaction transaction) async {
      await messages.where("location", isEqualTo: _location).snapshots().listen(
          (data) => data.documents.forEach((doc) async =>
              await transaction.update(doc.reference, {"isFavorited": false})));
    });
    setState(() {
      _isfavorite = !_isfavorite;
    });
    print("Updated fav => $_isfavorite");
  }

Error: 
Caused by: java.lang.IllegalArgumentException: Provided document reference is from a different Firestore instance.
E/AndroidRuntime(16311): 	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.1.1:384)
E/AndroidRuntime(16311): 	at com.google.firebase.firestore.Transaction.zza(com.google.firebase:firebase-firestore@@17.1.1:203)
E/AndroidRuntime(16311): 	at com.google.firebase.firestore.Transaction.update(com.google.firebase:firebase-firestore@@17.1.1:145)
E/AndroidRuntime(16311): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:360)
E/AndroidRuntime(16311): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:354)
E/AndroidRuntime(16311): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(16311): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(16311): 	... 4 more
I/Process (16311): Sending signal. PID: 16311 SIG: 9
Application finished.

Ok so the fix isnt available yet, and is anyone solved above exception??????

**Comment by dark-chocolate** [comment]
@DeepStyles  your error doesn't prove any bug, it is better suited to ask this question on Stackoverflow.

**Comment by baeharam** [comment]
@DeepStyles Did you solve that problem?

**Comment by PandaGeek1024** [comment]
`Transaction has already completed.`

Im also getting this issue. The firestore plugin is really buggy to be honest.

**Comment by TheHemantKaushik** [comment]
I was also getting the same issue. I changed document reference from
`var chatRef = _firestore.collection(TABLE_SITES).document(siteId).collection(TABLE_CHATS).document(chatId);` to `var chatRef = _firestore.document('$TABLE_SITES/$siteId/$TABLE_CHATS/$chatId');` and the problem is fixed.

**Dependencies versions:**
`firebase_core: ^0.4.0+6`
`firebase_auth: 0.11.1+7`
`cloud_firestore: 0.12.5+2`
`firebase_storage: ^3.0.2`
`firebase_messaging: ^5.0.4`
`firebase_crashlytics: ^0.0.4+8`

**Comment by TheHemantKaushik** [comment]
> ```dart
> Future _updateFavorite() async {
>     Firestore.instance.runTransaction((Transaction transaction) async {
>       await messages.where("location", isEqualTo: _location).snapshots().listen(
>           (data) => data.documents.forEach((doc) async =>
>               await transaction.update(doc.reference, {"isFavorited": false})));
>     });
>     setState(() {
>       _isfavorite = !_isfavorite;
>     });
>     print("Updated fav => $_isfavorite");
>   }
> 
> Error: 
> Caused by: java.lang.IllegalArgumentException: Provided document reference is from a different Firestore instance.
> E/AndroidRuntime(16311): 	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.1.1:384)
> E/AndroidRuntime(16311): 	at com.google.firebase.firestore.Transaction.zza(com.google.firebase:firebase-firestore@@17.1.1:203)
> E/AndroidRuntime(16311): 	at com.google.firebase.firestore.Transaction.update(com.google.firebase:firebase-firestore@@17.1.1:145)
> E/AndroidRuntime(16311): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:360)
> E/AndroidRuntime(16311): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:354)
> E/AndroidRuntime(16311): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
> E/AndroidRuntime(16311): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/AndroidRuntime(16311): 	... 4 more
> I/Process (16311): Sending signal. PID: 16311 SIG: 9
> Application finished.
> ```
> 
> Ok so the fix isnt available yet, and is anyone solved above exception??????

I found the cause of this issue. My app is working fine and transaction is running successfully on fresh install. It is happening only when I hot reload/restart app.

Can you please check and confirm if same is happening with you?

**Comment by TheHemantKaushik** [comment]
> @DeepStyles your error doesn't prove any bug, it is better suited to ask this question on Stackoverflow.

I'm sure this is a bug. This is only happening when we reload/restart app.

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/904. Any further collaboration will be done there.
