### ISSUE TITLE
[google_sign_in_macOS] Implement Webkit Login for Google Sign-In on MacOS

### ISSUE THREAD

**Issue by isaacadariku** [flutter/flutter#146655]
On our recent submission to the Apple App Store, we received feedback that the current Google Sign-In (version 6.2.1) behaviour on MacOS is not user-friendly - 

> The user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.

We need to implement the updated webkit login for Google Sign-In to provide a seamless user experience on MacOS. 

I am creating this issue to ask if there is a way to implement the updated webkit login for Google Sign-In on MacOS using the Google Sign-In plugin for Flutter. As our next update is required to provide a solution to this issue or a timeline for implementation, we would appreciate any guidance or assistance on how to achieve this.

Here is a screenshot of the feedback from Apple:

<img width="1091" alt="Screenshot 2024-04-11 at 21 05 28" src="https://github.com/flutter/flutter/assets/46024202/37168b9f-0c1d-4c60-b89c-2d4fe02fdc23">

**Comment by stuartmorgan** [comment]
This behavior is controlled by the underlying SDK, not the plugin; you can follow https://github.com/google/GoogleSignIn-iOS/issues/388 for discussion and updates.

(As noted there, the rejection is inconsistent with Apple's documentation about the correct way to do authentication on macOS; while you wait for an update you could point the reviewers to that thread and/or to https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession which states: "Use an ASWebAuthenticationSession instance to authenticate a user through a web service, including one run by a third party. [...] In macOS, the system opens the user’s default browser if it supports web authentication sessions, or Safari otherwise.)

Closing as this is not within the scope of what the plugin, which is just a wrapper, controls.
