### ISSUE TITLE
how to find the slow frame

### ISSUE THREAD

**Issue by WuMingke** [flutter/flutter#146981]
![image](https://github.com/flutter/flutter/assets/22768714/a03e04e4-8d45-4744-903b-b5b7d608996f)

![image](https://github.com/flutter/flutter/assets/22768714/5d6e9a47-27b0-429f-9860-bfdc4a437403)

![image](https://github.com/flutter/flutter/assets/22768714/b83e72fc-956c-44f3-b1b6-843ba0100f09)

![image](https://github.com/flutter/flutter/assets/22768714/a906817e-1d6a-4159-9097-8612fa8d7608)

i mean,i want to find the widget which caused slow frame

**Comment by darshankawar** [comment]
@WuMingke 
I don't think you can exactly find which widget could be causing slow frame. Please read https://docs.flutter.dev/tools/devtools/performance#jank-slow-frame and [related links from the topic](https://docs.flutter.dev/perf/ui-performance) that shows how to identify slow frames.

Closing for now, as this issue is more of a `how to` question. You may also ask the same in support channels like StackOverflow or Flutter's reddit help page or on discord.
