### ISSUE TITLE
Have more varieties of flutter create templates

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14719]
- Completely blank app
- App with material scaffold and no code comments
- App with cupertino scaffold and no code comments

**Comment by Hixie** [comment]
Completely blank app is three keystrokes away from what we have now (^A, backspace).
I'm not sure how I feel about the other two... the comments have been very helpful. Maybe our IDEs should have a way to remove all comments?

I agree that it'd be nice to have a template for cupertino apps.

**Comment by zoechi** [comment]
Similar to #13611

**Comment by ansarizafar** [comment]
@Hixie The current Flutter template has support for all supported platform. If I want to create a web app then I don't need support for any other platform. Flutter create command should create a blank app initially and we should have "Add Platform" command to add support for required platforms.
````
flutter create MyApp      //Minimum flutter app
flutter add-platform web  //Add support for web platform
````

**Comment by Hixie** [comment]
@ansarizafar That's orthogonal to what this bug is asking for. Please file a new bug for new feature requests. Thanks!

For the original request in this bug, I'm going to close this issue because the cupertino thing is tracked by #18819 and the other things listed here are things we're not going to do.
