### ISSUE TITLE
Google Maps Issues- Flutter

### ISSUE THREAD

**Issue by GloRaj** [flutter/flutter#147216]
Before uploading to Playstore in production Sha1 only Google Maps are working after upload its not working

**Comment by huycozy** [comment]
Hi @GloRaj 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See Flutter's first-party package issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)).

Closing this issue, since no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further investigation. Thanks!

**Comment by GloRaj** [comment]
GOOGLE MAPS ARE WORKING RELEAE APK, BUT SAME APK IF WE UPLOAD INTO PLAYSTORE GOOGLE MAPS ARE NOT [WORKING](![Uploading WhatsApp Image 2024-04-23 at 15.45.23 (1).jpeg…]())
