### ISSUE TITLE
”dev.flutter.flutter-gradle-plugin“ can't be downloaded

### ISSUE THREAD

**Issue by ChenZeFengHi** [flutter/flutter#147313]
### Steps to reproduce

When creating a flutter project on Android Studio Iguana | 2023.2.1, the plugin "dev.flutter.flutter-plugin-loader" could not be found at runtime

It seems to have all failed to download, which has been bothering me for a long time

https://plugins.gradle.org/m2/dev/flutter/flutter-gradle-plugin/dev.flutter.flutter-gradle-plugin.gradle.plugin/1.0.0/dev.flutter.flutter-gradle-plugin.gradle.plugin-1.0.0.pom
This link is invalid

### Actual results

![image](https://github.com/flutter/flutter/assets/20348442/39fe79a7-cb56-4888-82d3-a003bd6c9cea)
![image](https://github.com/flutter/flutter/assets/20348442/81d5873b-563b-48e0-9c8e-6149ff90e347)

**Comment by huycozy** [comment]
Hi @ChenZeFengHi 
This issue seems related to your network, please ensure you have a working internet connection. There is a checklist you can use for this:

- [ ]  Is the network stable and fast?
- [ ]  Do you use any proxy server?
- [ ]  Are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?
- [ ]  It may be useful for troubleshooting the issue: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

**Comment by huycozy** [comment]
Could you share the error trace in text file that will help to investigate further? Also, which Flutter version are you using? (please provide the output of `flutter doctor -v`)

**Comment by ChenZeFengHi** [comment]
<img width="880" alt="image" src="https://github.com/flutter/flutter/assets/20348442/0728de67-66c2-44bc-827a-7bf33030d6d5">

[flutter_android_log.log](https://github.com/flutter/flutter/files/15108930/flutter_android_log.log)
@huycozy  This is the error log～

**Comment by huycozy** [comment]
A snippet of logs above: 

>* What went wrong:
Plugin [id: 'dev.flutter.flutter-gradle-plugin', version: '1.0.0', apply: false] was not found in any of the following sources:
>- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
>- Plugin Repositories (could not resolve plugin artifact 'dev.flutter.flutter-gradle-plugin:dev.flutter.flutter-gradle-plugin.gradle.plugin:1.0.0')

Could you check if the issue appears on a newly created Flutter project? If it's only on your project, could you share your gradle files below or a minimal sample project so that I can try it on my end?

- android/settings.gradle
- /android/build.gradle
- /android/gradle/wrapper/gradle-wrapper.properties
- /android/app/build.gradle

>2.With the use of VPN, access to google, gradle plug-ins are normal.Turning off the VPN also fails to download the plugin properly

Does that mean the issue will not occur if you enable VPN?

**Comment by ChenZeFengHi** [comment]
The newly created flutter project will also have problems.

[new_flutter_project.zip](https://github.com/flutter/flutter/files/15125005/meat_meat.zip)
This is my newly created project.


Start the VPN can visit "https://plugins.gradle.org,But cannot download "dev.flutter.flutter-gradle-plugin".
@huycozy

**Comment by huycozy** [comment]
I can run your project normally. I still doubt this is a network issue. I would recommend you switch to another network and retry.

**Comment by ChenZeFengHi** [comment]
Other colleagues can also run my projec, Changing your phone's hotspot won't work either... ah～

**Comment by huycozy** [comment]
Thanks for checking. I will label the issue for other's input.

**Comment by yaakovschectman** [comment]
From triage: `dev.flutter.flutter-gradle-plugin` is not part of `plugins.gradle.org`; it is hosted as part of Flutter. Please try updating your Flutter version.

**Comment by ChenZeFengHi** [comment]
@yaakovschectman The Flutter version is already up to date 
<img width="710" alt="image" src="https://github.com/flutter/flutter/assets/20348442/272558fb-f645-480c-a0ed-117e2e2c2acc">

**Comment by kerneltea** [comment]
I encountered a similar issue. Later, I found that the corresponding operations in the flutter directory had been updated. It seems like some IDE suggestions automatically modified them. You should navigate to the flutter directory, run git reset --hard HEAD, and then try compiling again. It should work.
