### ISSUE TITLE
ClientException with SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54),

### ISSUE THREAD

**Issue by rifay-next99** [flutter/flutter#147506]
`Unhandled Exception: ClientException with SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = ***.next99.com, port = 62634, `uri=https://***.next99.com/api/v1/coach_request
`
```
#0      IOClient.send (package:http/src/io_client.dart:154:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:167:12)
<asynchronous suspension>
#3      ApiServices.previousRequest (package:fitish_app/services/api_services.dart:269:15)
<asynchronous suspension>
#4      CoachSearchController.alreadyRequest (package:fitish_app/controller/coach_controller/coach_search_controller.dart:56:21)
<asynchronous suspension>
#5      CoachSearchController.onInit (package:fitish_app/controller/coach_controller/coach_search_controller.dart:18:5)
<asynchronous suspension>`

```

When i call multiple api in flutter app the error will thow and the null value produce why

**Comment by darshankawar** [comment]
@rifay-next99 
Your issue / question is best suited for support channels like Stackoverflow because this seems to be code implementation issue while using multiple apis as you mentioned rather than a bug in framework. So please ask the same there.
If you think this is a bug in framework, please use new issue template, fill out requested details so that we can properly address the issue.
Closing for now due to lack of details.
