### ISSUE TITLE
Support updatable configuration file after build

### ISSUE THREAD

**Issue by javaone199** [flutter/flutter#147613]
### Use case

A way to add a configuration file for flutter app.

Use case as following:

A software vendor developed a client/server application. client is flutter app. Release is binary code, not flutter package.

CompanyA deployed it with domain company-a.com. companyB deployed it with domain company-b.com.

```
  flutter_app -------- Sever1
                      company-a.com

  flutter_app -------- Sever2
                      company-b.com
```
The flutter client needs to know the domain to connect to the right server.

When an end user downloads the flutter app from AppStore and GooglePlay, the app must have the domain already configured.

Does the domain need to be hard-coded in flutter app? If so, the flutter client app must be re-built for every deployment. That is, the flutter app can not be pre-built for download.

### Proposal

For example,

```
server.properties
------------------
server.domain = my.example.com
server.port = 8080
```

A software deployer can run a command/tool to update the configuration. For example, update a configuration inside APK for android before going alive on GooglePlay. Same idea for iOS and other platforms.

**Comment by huycozy** [comment]
Hi @javaone199 
I think you can use a 3rd service like [Firebase Remote Config](https://firebase.google.com/docs/remote-config) for this case. You can define all server configurations there and fetch them on your Flutter app before doing network API calls.

This is more like a question for solutions with your app rather than a specific proposal for Flutter. Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

Closing the issue as explained.
