### ISSUE TITLE
[google_maps_flutter] Add `onLongTap` callback for `Marker`

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#147632]
### Use case

Simple use case:
1. Single tap on marker shows the info window for this marker.
2. Long tap on marker switches to specific screen with details of this marker.

**Comment by darshankawar** [comment]
@bambinoua `OnLongTap` and double tap probably are different events.
Have you tried wrapping marker with `GestureDetector` and see if it helps in your case or not ?

**Comment by bambinoua** [comment]
@darshankawar yes my mistake. I've fixed the request.

> Have you tried wrapping marker with GestureDetector and see if it helps in your case or not ?
`Marker` is not a widget but just a class which is passed to `GoogleMap` widget. The `Marker` class contains `onTap` method which can be handle, for example to activate some info window. But it would be good to have an alternative press callback.

**Comment by stuartmorgan** [comment]
I looked at the APIs for the underlying SDKs on iOS and Android, and unfortunately there is no long-press event for markers in those SDKs. Given that, this is not something that we would implement in the plugin, since the plugin's goal is to wrap the underlying functionality.

The next step here would be to request this functionality in the Google Maps SDK itself. If it's added in the future, this could then be requested for the plugin.

Closing as this is currently out of scope given the SDK capabilities.
