### ISSUE TITLE
Is it possible to render a Fragment Shader asynchronously?

### ISSUE THREAD

**Issue by andy98725** [flutter/flutter#147850]
### Steps to reproduce

I have an expensive fragmentShader for a background, which calls a 4D Perlin Noise implementation 6 times per px. My higher-end setup can handle this, but my lower-end laptop profiles a 100ms+ render time on the raster thread for it. The lag & battery drainage caused by it are my app's most common complaint in bad reviews right now.

The fragment shader code is at [this gist](https://gist.github.com/andy98725/c2562ebf9df722bd7222a40ee2085035). I don't think I can optimize it much anymore, I did the changes suggested [here](https://github.com/flutter/engine/blob/main/impeller/docs/shader_optimization.md) and it didn't impact performance.

So now I'm looking for alternative solutions. The first thing I tried is limiting the framerate of the background through the `ShaderPainter.shouldRepaint` method, but due to the high render time this had negligible impact.

Is it possible to use the shader to generate an image in an async thread? What are the best practices for large shaders like this?

### Code sample

<details open><summary>Code sample</summary>
Painter:

```dart

class ShaderPainter extends CustomPainter {
  final double framerate, iTime, brightness;
  final List<Color> cols;
  final List<double> amts;
  final int images;
  final bool imageMovement, pulseMovement;

  const ShaderPainter(this.framerate, this.iTime, this.cols, this.amts,
      this.images, this.brightness, this.imageMovement, this.pulseMovement);

  static const amtChangeTime = Duration(seconds: 10);
  // static Stopwatch time = Stopwatch()..start();
  static int lastPaint = 0;

  @override
  void paint(Canvas canvas, Size size) {
    // print(1000000 / time.elapsed.inMicroseconds);
    // time.reset();

    final paint = Paint()
      ..shader = PerlinShader.getShader(
        spaceScale: 0.025,
        timeScale: 0.05,
        gradient: 1.0,
        amtScale: 0.4,
        imgScale: 0.015,
        brightness: 0.2 * brightness,
        waviness: 0.2,
        useImgs: true,
        pulseScale: pulseMovement ? 1 : 0,
        imgMoveSpd: imageMovement ? 0.5 : 0,
        // Less configurable
        time: iTime,
        cols: cols,
        amts: amts,
        imgCount: images,
      );

    canvas.drawRect(Offset.zero & size, paint);
    lastPaint = DateTime.now().millisecondsSinceEpoch;
  }

  @override
  bool shouldRepaint(ShaderPainter oldDelegate) {
    return DateTime.now().millisecondsSinceEpoch - 1000 / framerate > lastPaint;
  }
}

```

Glsl Fragment Shader [here](https://gist.github.com/andy98725/c2562ebf9df722bd7222a40ee2085035)

</details>
I can provide more info if needed.

### What target platforms are you seeing this bug on?

Android, Web, Windows

### OS/Browser name and version | Device information

Windows 11 w/ Intel Core i78-8750h CPU, UHD Graphics 630
Chrome 124.0.6367.119

Android A71 5G

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.22.0-0.3.pre, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.89.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
The fragment shader execution is already "asynchronous" in that it runs on the GPU timeline, whereas the UI and raster threads are on the CPU timeline. however, if the execution of the shader workload is expensive enough you will find that it will essentially hog the GPU preventing the raster thread from being able to submit workloads, which in turn prevents the raster workload from finishing. This is the limit of splitting up work across threads: you can't increase access of shared resources like disk, network, GPU, et cetera.

Its also possible that certain laptops are falling back to Skia software rendering due to lack of hardware support. I couldn't tell you if this is the case from the information here, but if it was there would be little we could do.

> So now I'm looking for alternative solutions. The first thing I tried is limiting the framerate of the background through the ShaderPainter.shouldRepaint method, but due to the high render time this had negligible impact.

That isn't what that method does. It only controls if the paint method is called. If that shader is used in a scene that is included in any part of a frame, whether or not the painter painted or the widgets rebuilt, it gets executed. The only way to limit how often it runs is to cache the rendered results to a texture (see SnapshotWidget for an example of how to do that).


In general, I would recommend designing your application to support the target hardware you want to support. If older laptops are important, then your app/game/et cetera needs to cut costs. You can do that by simplifying the shader, or reducing the amount of work done by reducing the size of the painter. Or find a mechanism to detect older hardware (Android API level?) and substitute a reduced quality effect.

**Comment by jonahwilliams** [comment]
Oh, if you're running with Skia - you're probably getting some of the SnapshotWidget behavior automatically via raster caching. But that will only get you so far, as once you have to repaint you'll drop the frame again (one of the reasons automatic raster caching is a bad idea)

**Comment by andy98725** [comment]
This was informative. Thank you!
