### ISSUE TITLE
Card page doc have redundent prats

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#147820]
### Page URL

https://api.flutter.dev/flutter/material/Card-class.html

### Describe the problem

This page contains the comment 
```dart
        // clipBehavior is necessary because, without it, the InkWell's animation
        // will extend beyond the rounded edges of the [Card] (see https://github.com/flutter/flutter/issues/109776)
        // This comes with a small performance cost, and you should not set [clipBehavior]
        // unless you need it.
```
but  #109776 is closed so I guess it can be deleted

### Expected fix

The comment can get deleted from the card dock page

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by danagbemava-nc** [comment]
Hi @guyluz11, that comment was added to explain the bug in #109776. It serves as a way prevent people from facing the same issue in #109776 without knowing why it happens. 

As such, that comment should still remain. #109776 was not closed as a bug but it was closed as a documentation issue.

Closing since there's no further action to take on this issue. 

Thank you
