### ISSUE TITLE
DropdownMenuItem widget is wider than the Dropdown itself

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#14785]
## Steps to Reproduce
Copied from https://stackoverflow.com/questions/48895195/how-can-we-change-the-width-padding-of-a-flutter-dropdownmenuitem-in-a-dropdown

In Flutter, I can build a Dropdown with DropdownMenuItems, like this:
[![enter image description here][1]][1]

The DropdownMenuItems I add are always wider than the dropdown itself:

[![enter image description here][2]][2]

How do you adjust the width of the DropdownMenuItem, or remove the extra horizontal padding?

My DropdownMenuItem widget looks like this:

    DropdownMenuItem(
        value: unit.name,
        child: Text('hey'),
    );

while my Dropdown widget looks like this:

    return Container(
        width: 300.0,
        child: DropdownButtonHideUnderline(
          child: DropdownButton(
            value: name,
            items: listOfDropdownMenuItems,
            onChanged: onChanged,
            style: Theme.of(context).textTheme.title,
          ),
        ),
    );

  [1]: https://i.stack.imgur.com/GnwfL.png
  [2]: https://i.stack.imgur.com/D5LI1.png

Goal is to just have the same width between the Dropdown and the DropdownMenuItems; we don't need to make the width actually adjustable.

**Comment by HansMuller** [comment]
The [Material spec](https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons) doesn't provide a precise definition for mobile dropdown button geometry, but the implication of the illustration below is that the menu is wider than the dropdown button itself. That's assuming that the dropdown button's underline defines the button's width.

![dropdown](https://user-images.githubusercontent.com/1377460/36570595-9b9bcaec-17e7-11e8-86c6-9a9335a23e38.png)

I created a version of DropdownButton that enabled changing the default geometry of the button, menu and menu items. The new `padding` and `menuMargin` properties could be configured so that the menu's width matched the dropdown button and the menu items' layout matched the drop down button:

```dart
new DropdownButton(
  padding: const EdgeInsets.Directional(start: 16.0),
  menuMargin: EdgeInsets.zero,
  ...
)
```

In this case padding is applied to the dropdown button and all of the menu items, margin is applied to the menu itself.

An alternative would be to incompatibly change button layout to pad by default.

**Comment by maryx** [comment]
Is there a PR that has this version of the DropdownButton?

**Comment by HansMuller** [comment]
Sorry, not yet, I'm still trying to decide if there's a better way
