### ISSUE TITLE
First time setup of framework repository doesn't work

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#148000]
@turnidge and I were following our official directions:

https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment

and after doing everything on the page we tried to do a simple 'flutter create' and it ended up with:

```
turnidge@mumak workspace % flutter create honorfarm
Creating project honorfarm...
Resolving dependencies in `honorfarm`... 
Note: leak_tracker_flutter_testing is pinned to version 3.0.5 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.
The current Flutter SDK version is 0.0.0-unknown.
Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because honorfarm depends on flutter_test from sdk, version solving failed.
turnidge@mumak workspace %   
```

My questions:

1) How did we get into this state and precisely how do we exit it?
  - We ended up switching git branches (between upstream/main and origin/main) didn't help.
  - We ran 'flutter channel main' and that ended up downloading hundreds of mbs of stuff that we don't actually need and didn't have enough time to see if this would have resolved the problem.
2) What is missing from our "Setting up the Framework development environment?"
3) How are we testing this on-boarding flow?

But, even if 'flutter channel main' fixes the issue this experience has been absolutely terrible and without my guidance Todd would have just given up and moved on with his life.

**Comment by goderbauer** [comment]
Can you post the output of `flutter doctor -v`?

**Comment by goderbauer** [comment]
> How are we testing this on-boarding flow?

They are not tested. Any suggestions for how to test this documentation?

I followed these instructions about a month ago to set up my new mac, though.

> that ended up downloading hundreds of mbs

At some point during the setup these dependencies have to be downloaded, otherwise Flutter will not work. Usually, this happens when you run `flutter update-packages` from the instructions. Did that happen and go through?

> How did we get into this state and precisely how do we exit it?

From the information given in the bug its not clear what state you're in (the output of `flutter doctor -v` could help).

**Comment by turnidge** [comment]
Here's the current output. Let me know if you want me to scroll up and get the output from earlier in the session.

```% flutter doctor -v
[!] Flutter (Channel [user-branch], 3.22.0-27.0.pre.20, on macOS 13.6.6 22G630 darwin-arm64, locale en-US)
    ! Flutter version 3.22.0-27.0.pre.20 on channel [user-branch] at /Users/turnidge/workspace/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 1c7e6a401e (8 hours ago), 2024-05-08 12:59:10 -0400
    • Engine revision f3ce5a59c2
    • Dart version 3.5.0 (build 3.5.0-131.0.dev)
    • DevTools version 2.35.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/turnidge/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.```

**Comment by johnmccutchan** [comment]
Todd and I started looking at this issue again today. 

We tried blowing away the `flutter/flutter` checkout and cloning again but the issue persisted.

Eventually we found https://github.com/flutter/flutter/issues/98020, which suggested we do the following:

`git remote set-url upstream https://github.com/flutter/flutter.git`

Running that command got the flutter tool out of the bad state and the `flutter channel` started to correctly report master/main instead of `[user-branch]`

I couldn't reproduce this in my usual environment, so, I created a new GitHub account that wasn't part of the organization.

Doing a fresh clone of the repository gave me the following output from `flutter doctor`:

```
[!] Flutter (Channel master, 3.22.0-35.0.pre.11, on macOS 14.4.1 23E224 darwin-arm64, locale en)
    ! Upstream repository git@github.com:cutchtemp/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:cutchtemp/flutter.git to dismiss this error.
```

So it seems related to using ssh:/ GitHub URLs when we aren't part of the Flutter organization.

**Comment by johnmccutchan** [comment]
```
❯ flutter create honor
Downloading Darwin arm64 Dart SDK from Flutter engine bf1c6da0dd31273405ae4107ba7225238686140b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  201M  100  201M    0     0  50.4M      0  0:00:03  0:00:03 --:--:-- 50.4M
Building flutter tool...
Resolving dependencies...
Downloading packages...
Got dependencies.
Downloading Material fonts...                                      238ms
Downloading Gradle Wrapper...                                       27ms
Downloading package sky_engine...                                   87ms
Downloading flutter_patched_sdk tools...                           115ms
Downloading flutter_patched_sdk_product tools...                   110ms
Downloading darwin-arm64 tools...                                1,462ms
Downloading libimobiledevice...                                     31ms
Downloading usbmuxd...                                              21ms
Downloading libplist...                                             31ms
Downloading openssl...                                              71ms
Downloading ios-deploy...                                           40ms
Downloading darwin-arm64/font-subset tools...                      108ms
Creating project honor...
Resolving dependencies in `honor`...
Note: leak_tracker_flutter_testing is pinned to version 3.0.5 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

The current Flutter SDK version is 0.0.0-unknown.

Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because honor depends on flutter_test from sdk, version solving failed.
```

```
❯ flutter run
Downloading android-arm-profile/darwin-x64 tools...                324ms
Downloading android-arm-release/darwin-x64 tools...                130ms
Downloading android-arm64-profile/darwin-x64 tools...              159ms
Downloading android-arm64-release/darwin-x64 tools...              138ms
Downloading android-x64-profile/darwin-x64 tools...                127ms
Downloading android-x64-release/darwin-x64 tools...                136ms
Downloading Web SDK...                                           1,180ms
Downloading darwin-x64/framework tools...                          809ms
Downloading darwin-x64/gen_snapshot tools...                       243ms
Downloading darwin-x64-profile/framework tools...                  496ms
Downloading darwin-x64-profile tools...                            123ms
Downloading darwin-x64-profile/gen_snapshot tools...               242ms
Downloading darwin-x64-release/framework tools...                  348ms
Downloading darwin-x64-release tools...                            118ms
Downloading darwin-x64-release/gen_snapshot tools...               208ms
Resolving dependencies...
Note: leak_tracker_flutter_testing is pinned to version 3.0.5 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

The current Flutter SDK version is 0.0.0-unknown.

Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because honor depends on flutter_test from sdk, version solving failed.
```

**Comment by johnmccutchan** [comment]
To reproduce this issue do the following:

1. Create a GitHub account that isn't part of the Flutter organization.
2. Add an ssh-key to this account.
3. Fork flutter/flutter
4. Clone your fork via ssh://git@github.com/... URL
5. `flutter create test_app; cd test_app`
6. `flutter run`

**Comment by goderbauer** [comment]
Thanks for digging into that. I've updated the [instructions](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment) for now to tell people about potential issues with SSH. Will have to do some digging why SSH vs HTTPS matters here and why there's a difference between in-org and out-of-org accounts.

**Comment by goderbauer** [comment]
I had some time to dig into this. There are a couple of things at play here, so bear with me while I lay them all out.

The protocol (SSH vs HTTPS) and whether or not an account is part of the Flutter organization are red herrings.

The provided repro steps will always fail because they are missing crucial steps that were outlined on the setup wiki page before I just updated it: Namely, adding the upstream repository (`git remote add upstream git@github.com:flutter/flutter.git`), fetching tags (`git fetch upstream`), and updating dependencies (`flutter update-packages`). Without these, `flutter run` is never gonna work.

However (and I suspect this is were things originally went off the rails during the initial setup here), even if you followed those instructions to the letter there are some pitfalls that I discovered while debugging this:

* `flutter update-packages` can fail silently, which is easy to miss because in certain situations it literally doesn't print any failure message. If it fails, `flutter run` will then also fail in mysterious ways. My suspicion is that you may have unknowingly run into that issue here. I've filed https://github.com/flutter/flutter/issues/148569 with the tools team to track and fix this.
* Furthermore, even when you recognize that it is failing silently because of missing tags, fetch the tags, and then run `update-packages` again it may operate on outdated data and hence fail again. I've filed https://github.com/flutter/flutter/issues/148571 for that issue with more details.

Having said all that, I also just re-wrote the [setup instructions](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment#set-up-your-environment) in a way that removes both of these pitfalls from the critical path so the chances of success are much higher. Please take a look and let me know if something is unclear or not working (I appreciate it if you'd include full console logs with commands executed and their output in any issue report. That makes these kind of bugs much more actionable. Often, it is also helpful to get the verbose output with `-v` of these commands as that may contain additional hints of what's going wrong.)

Anyways, again sorry for the trouble and hopefully you'll have a good time with Flutter now.

**Comment by johnmccutchan** [comment]
Thanks for the updated documentation!
