### ISSUE TITLE
[image_picker]: option to adjust the framerate when selecting ImageSource.camera.

### ISSUE THREAD

**Issue by vzdorrr** [flutter/flutter#148048]
### Use case

Very necessary option to adjust the framerate when selecting ImageSource.camera.

### Proposal

Very necessary option to adjust the framerate when selecting ImageSource.camera.

**Comment by stuartmorgan** [comment]
The system-provided image picker controls that `image_picker` provides access to do not provide APIs to control details of camera behavior. Applications that need to specifically configure image capture behavior would need to use `camera` or a similar plugin that interacts directly with camera APIs, and build their own UI, instead of using a the system-provided picker UI.

**Comment by iqsites** [comment]
> The system-provided image picker controls that `image_picker` provides access to do not provide APIs to control details of camera behavior. Applications that need to specifically configure image capture behavior would need to use `camera` or a similar plugin that interacts directly with camera APIs, and build their own UI, instead of using a the system-provided picker UI.

Camera - same problem. No any options for changing framerate
