### ISSUE TITLE
camera capturing video upload to server but frames is not save correctly in flutter camera

### ISSUE THREAD

**Issue by krupalieBizTrait** [flutter/flutter#148054]
### Steps to reproduce

camera capturing video upload to server but frames is not save correctly in flutter camera

### Expected results

Frames saved correctly

### Actual results

Frames saved correctly

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
 Flutter (Channel stable, 3.16.5, on macOS 14.3.1 23D60 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
</details>

**Comment by huycozy** [comment]
Hi @krupalieBizTrait 
Please try to provide all the appropriate information indicated in the template so that we can address the issue properly. More specifically, please provide the additional information:

- step-by-step reproduction for the issue
- a more specific description of the actual result (how incorrect it is)
- a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code
- the affected target platform
- the current package version (from pubspec.lock)
