### ISSUE TITLE
About "SystemUiOverlayStyle"

### ISSUE THREAD

**Issue by LinHaoLove** [flutter/flutter#148199]
### Use case

(Vritual Device(Android 12.0) From Latest Android Studio)

![statusBar](https://github.com/flutter/flutter/assets/14291213/a0184325-94f0-4eac-b335-7877be078747)

I have configured the both "theme" and "darkTheme" of the themeData.
In some cases,"appbar" of "Scaffold" is null in the some page.

Question 1: 
StatusBarColor is not work when appbar is null.
Question 2: 
The first page has no appBar.
When I push the second page, the second page has appbar, and pop the second page, the first page will keep second page's statusBarColor.

Expect:
The page's status bar uses the style from the theme data or individually custom style, whether the page has appbar or not.

### Proposal

The status bar style should belongs to page(Scaffold),whether the page has appbar or not.
![statusBar1](https://github.com/flutter/flutter/assets/14291213/975c0e1f-9313-44f6-95b6-6558d9e15c72)

**Comment by darshankawar** [comment]
@LinHaoLove 
Thanks for the report, but it seems you have clubbed more than one issue / behavior in entire issue description. Also, please don't post code screenshots, instead post formatted code sample in text so that we can directly use it for further analysis.

Also, check https://github.com/flutter/flutter/issues/100027 for further reference and see if it helps in your case or not.

**Comment by LinHaoLove** [comment]
Thank you for your reply. I will avoid these issues in the future.
This discussion can solve my problem, but it doesn't seem like the best solution. 
Biased towards this friend's comment [#100027#issuecomment-1077697819](https://github.com/flutter/flutter/issues/100027#issuecomment-1077697819)

I closed it,Thank you.
