### ISSUE TITLE
Flutter drive  with --preview-dart-2

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#14828]
Flutter drive is missing the --preview-dart-2 option, so cannot exercise the driver tests with dart 2.

**Comment by keertip** [comment]
@aam

**Comment by keertip** [comment]
@tvolkert

**Comment by yjbanov** [comment]
I started looking into it. It seems we only support `--preview-dart-2` in hot reload mode? `ColdRunner` has the `previewDart2` flag but it's not used. I'll keep digging.

**Comment by yjbanov** [comment]
Ok, so turns out `--preview-dart-2` option is passed as a field in `BuildInfo` supplied as part of `DebuggingOptions`. This already works in `flutter drive`. That said, `flutter drive --preview-dart-2` will fail due to actual Dart 2 issues (see for example https://github.com/flutter/flutter/pull/14897). The option itself exists.

I'm closing this bug, but feel free to reopen if I missed anything.
