### ISSUE TITLE
[google_maps_flutter] Move code from main package to platform_interface

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#148210]
### Use case

I'm currently working on improving `platform_maps_flutter`, a 3rd party library published on pub.dev.
1 big issue with platform maps is that even though it's using Apple maps on iOS, it is still including the native iOS dependencies from Google Maps. I'm currently rewriting that, so it only includes Android code. By doing that I cannot depend on the main package of google_maps_flutter, but I can easily switch that by using `google_maps_flutter_android` and `google_maps_flutter_platform_interface`. However, there are 2 files in the main `google_maps_flutter` package that I need to copy paste in that case, which are these 2: https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/lib/src

The PR I'm working on can be seen here: https://github.com/albert-heijn-technology/platform_maps_flutter/pull/67

### Proposal

`google_maps_flutter` already exposes a lot of files from `google_maps_flutter_platform_interface` as you can see here: https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter/lib/google_maps_flutter.dart#L16-L47

My proposal would be to move the `controller.dart` and `google_map.dart` files to the platform interface package and just expose them in `google_maps_flutter`. That way the main package becomes only responsible for linking the interface and the native implementations and any other package can take the platform interface and the native implementations it needs, without depending on the main package and all its dependencies.

If you agree with this proposal I'm willing to make a PR for that. I expect this to be a `minor` version change for `google_maps_flutter_platform_interface` and a `patch` version for the main package, as it doesn't change anything for the consumers of the main package and also doesn't change the interface that needs to be implemented by the platforms.

**Comment by stuartmorgan** [comment]
Having all of the code for a plugin be in the platform interface is a non-goal; the intent of the design is that the client-facing API that is above the platform interface lives in the app-facing package. Given that, this is not something we would do.

> `google_maps_flutter` already exposes a lot of files from `google_maps_flutter_platform_interface` as you can see here

These are data classes that are part of the platform interface, which is why they are there. (Exposing them directly, rather than wrapping them with similar structures for the other API layer would probably have been an better idea.)

The way to support a use case like the one described here would be to implement https://github.com/flutter/flutter/issues/81650.
