### ISSUE TITLE
flutter web can not work in iphone QQ app / iphone QQ程序内打开flutter web页面白屏、无法运行

### ISSUE THREAD

**Issue by starqiqi77** [flutter/flutter#148377]
### Steps to reproduce

1, In Iphone, download and install "QQ"/"QQ browser" from appStore.
2, Send a flutter web link to your friend, click the link and open it by QQ app`s internal browser
    Or, open the link in QQ browser
4, Flutter web only display blank, can not work

Tried in 3.16.x and lastest version 3.22.0

### Expected results

can display flutter web content

### Actual results

Just blank, and redirect to local debug, can get the log of error in dart_sdk.js

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Uncaught (in promise)  {"name": "Error", "message": "TypeError: null: type 'Null' is not a subtype of type 'JavaScriptObject'", "stack": 
"DartError                       @dart_sdk.js:13159:12
throw_                           @dart_sdk.js:11994:29
_failedAsCheck                   @dart_sdk.js:22922:15
_generalAsCheckImplementation    @dart_sdk.js:22908:28
read                             @dart_sdk.js:157565:41
runBody                          @dart_sdk.js:47100:38
_async                           @dart_sdk.js:47136:14
fetchFontManifest                @dart_sdk.js:204357:55
                                 @dart_sdk.js:47081:37
handleValueCallback              @dart_sdk.js:42938:60
_propagateToListeners            @dart_sdk.js:42976:36
                                 @dart_sdk.js:42817:44
                                 @dart_sdk.js:42851:35
_startMicrotaskLoop              @dart_sdk.js:47394:21
_startMicrotaskLoop              @dart_sdk.js:47400:27
                                 @dart_sdk.js:43200:17
"}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by starqiqi77** [comment]
QQ app and QQ浏览器/QQ browser can not display.

**Comment by darshankawar** [comment]
@starqiqi77 
This document shows supported web browsers by Flutter https://docs.flutter.dev/platform-integration/web/faq#which-web-browsers-are-supported-by-flutter
Since you mentioned, we need to install a third party browser, which may not have proper support by Flutter and hence you could be seeing the reported behavior.
Have you checked if it works properly with native Android or iOS ?

I don't think this will be actionable from Flutter as the browser you mentioned isn't in the supported list. 
Closing from here. If you disagree, write in comments and I'll reopen it.
