### ISSUE TITLE
SpaceKey is not working on flutter web but if I use shift + space key then I can see space in TextFormField

### ISSUE THREAD

**Issue by jaydeepkaria-mi** [flutter/flutter#148301]
### Steps to reproduce

...

### Expected results

...

### Actual results

...

### Code sample

...

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@jaydeepkaria-mi 
You haven't provided any code sample, flutter version and details around the issue, so we can't properly address it without such details. Please provide a runnable code sample, flutter doctor -v, actual vs expected behavior so that we can verify this further. 
Also, please note, whenever opening an issue, please try to provide requested details in the issue template. Just providing the issue title without any details won't help us much.
