### ISSUE TITLE
Make it easy to use `clangd` (i.e. an IDE) with the engine (especially post-RBE)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#148519]
It was and still is possible to use `clangd` (i.e. with the [VSCode clangd plugin](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd)) while working in the engine.

For example, here is an excerpt of my workspace settings (JSON):

```json
"clangd.path": "${workspaceFolder}/buildtools/mac-arm64/clang/bin/clangd",
"clangd.arguments": [
  "--compile-commands-dir=${workspaceFolder}/../out/host_debug_unopt_arm64"
],
"clang-format.executable": "${workspaceRoot}/buildtools/mac-arm64/clang/bin/clang-format",
```

Even before RBE, this required manual configuration, and requires re-configuration as you change platforms (for example, editing C++ code that uses Android-only dependencies requires the `--compile-commands-dir` to point to a `../out/android_*` target).

Post RBE, the default `--compile-commands-dir` for Google employees uses flags (wrappers) unrecognized by `clangd`:

![image](https://github.com/flutter/flutter/assets/168174/705008f5-7cf5-40d5-904a-826f31ce74c6)

One workaround is to intentionally create and use a target output that opts out of RBE:

```shell
./tools/gn --unopt --mac-cpu=arm64 --target-dir=host_debug_unopt_arm64_ide --no-rbe
```

Problems to address (outside of having to do all this manually):

1. By default, this produces many broken links as a result of (mostly Impeller?) generators that need to run. One such example:

    ```shell
    # There are about ~3 sets of targets that need to be built so that clangd finds all generated files.
    ninja -C ../out/host_debug_unopt_arm64_ide shader_fixtures
    ```

2. Because this target is not actually _used_, it will frequently get out of date. That is, you will need to need to `gclient sync -D`
and reset GN arguments for both the target you're _actually_ working on (i.e. `host_debug_unopt_arm64`, using RBE), _and_ this stub target (`host_debug_unopt_arm64_ide`).

I'm opening this issue to solicit ideas for addressing this. Incremental is good, automated is good, tested is better.

**Comment by bc-lee** [comment]
In my opinion, consuming raw `compile_commands.json` generated by gn isn't feasible for tools like clangd, since gn dumps raw commands with all the flags used to build the target. I don't work at Google and therefore don't use Goma or RBE, but I encountered the same issue a long time ago and developed a solution to parse `compile_commands.json` and filter out flags unnecessary for consuming tools.

You can find my script here: https://gist.github.com/bc-lee/8707d1e62d14f8bb6bd30ef6e67f1625

The script modifies the `compile_commands.json` file by removing flags that clangd doesn't need. It's not perfect, but it works for me. At least it's much easier than maintaining a separate output folder to avoid using unnecessary flags with clangd.

Example usage:
`$ gn gen --export-compile-commands out/out_dir && parse-compile-commands out/out_dir`

**Comment by matanlurey** [comment]
Thanks @bc-lee, that certainly is an option, maybe even the best one.

I'll let the rest of the engine team weigh, but I appreciate the contribution!
