### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by Mashi-91** [flutter/flutter#148627]
### Steps to reproduce

Not Working On Windows

### Expected results

Working...

### Actual results

UnimplementedError: init() has not been implemented

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Closing this since no information has been provided. 

When you file an issue please provide as much information as possible to help us investigate the issue ; the flutter version you're using, what you did you when you experience the issue, the code sample you used, etc, are some information that would help us act on the issue (all requested in the issue template). "Not working on windows" is not enough information for us to act on. 

Thank you
