### ISSUE TITLE
[iOS] Hot restart fails with native assets

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#148687]
Reproducible with the example from FFI plugin (`flutter create -t package_ffi ffi_x`) on iOS device

Exception after hot restart with the example application
```
Invalid argument(s): Couldn't resolve native function 'sum' in
           'package:ffi_x/ffi_x_bindings_generated.dart' : Failed to load dynamic library
           'ffi_x1.framework/ffi_x1': Failed to load dynamic library 'ffi_x1.framework/ffi_x1':
           dlopen(ffi_x1.framework/ffi_x1, 0x0001): tried:
           '/Library/Developer/CoreSimulator/Volumes/iOS_20E247/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS
           16.4.simruntime/Contents/Resources/RuntimeRootffi_x1.framework/ffi_x1' (no such file),
           '/Library/Developer/CoreSimulator/Volumes/iOS_20E247/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS
           16.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/ffi_x1.framework/ffi_x1' (no such
           file), '/usr/lib/swift/ffi_x1.framework/ffi_x1' (no such file, not in dyld cache),
```

The problem seems to be multiple assets paths generated during dry run in `_assetTargetLocations`:
https://github.com/flutter/flutter/blob/02a6c91e4d37d28f42c8f8e4d4335b0defed41c1/packages/flutter_tools/lib/src/isolated/native_assets/ios/native_assets.dart#L162-L169

Here the code generates different path for each architecture even if assetId is same. Probably requires similar treatment as https://github.com/flutter/flutter/pull/144688/files. 

Fixing this fixes the hot reload, though TBH I don't know why during hot reaload the path from second native asset is used. Still, they are lipeod in reality so behavior of the function as it is now seems wrong and it shouldn't produce three different paths for same asssetId.

/cc @dcharkes

**Comment by dcharkes** [comment]
> Still, they are lipeod in reality so behavior of the function as it is now seems wrong and it shouldn't produce three different paths for same asssetId.

> Here the code generates different path for each architecture even if assetId is same. Probably requires similar treatment as https://github.com/flutter/flutter/pull/144688/files.

You're right. The same asset id with different archs is in the same framework/dylib, so they should have the same path.

Some background. When doing `flutter run`, there are a bunch of process invocations.

* `flutter run` compiles native assets in dry run has the kernel file with a native assets mapping sitting around unused until the first hot restart. (The native assets mapping is coming from a dry run, it doesn't build the actual assets.)
   which invokes
  * `xcodebuild` which invokes
    *  `flutter assemble` which compiles Dart to kernel with a native assets mapping and pushes it to the device. This kernel file with native assets mapping is used for hot reloads until the first hot restart. (This native assets mapping is coming from a normal run and will build the native assets.)

Because we want to support building a flutter app from the xcode project, the native assets mapping is needed in `flutter assemble`.
Because we want to support hot restart, the native assets mapping is also needed in `flutter run`.

In the end both kernel mappings should come from packages/flutter_tools/lib/src/isolated/native_assets/macos/native_assets.dart. However, their sources of truth are slightly different. The dry run doesn't report architectures, so the native assets builder expands the architectures for the OS. While for the non-dry-run, the native assets build is invoked for each target architecture and then combined. It might have been that the resulting order of architectures in the file was different, which then leads to different renaming.

As you pointed out, the same asset for different architectures should have the same path.

If you would be so kind, please provide a PR. 😃 

Could you maybe take a look as well as why our integration test didn't catch this?

`cd <...>/flutter/packages/flutter_tools/ && flutter test test/integration.shard/
isolated/native_assets_test.dart`

The integration test does a hot reload, hot restart, hot reload on both MacOS and iOS when run on a MacOS host, and it's succeeding just fine.

https://github.com/flutter/flutter/blob/d02292dbc40952a59dd1231ca2fb5ca86b39344c/packages/flutter_tools/test/integration.shard/isolated/native_assets_test.dart#L83-L161

**Comment by knopp** [comment]
The integration tests only run on flutter tester and host. It doesn't run on iOS device. If I manually add a simulator deviceId to the `devices` list the test fails. I'm not sure what assumptions the test can make about presence of iOS simulators?

**Comment by dcharkes** [comment]
> The integration tests only run on flutter tester and host. It doesn't run on iOS device. If I manually add a simulator deviceId to the `devices` list the test fails. I'm not sure what assumptions the test can make about presence of iOS simulators?

Oh, that's a bit worrisome! We should definitely add iOS hot reload and hot restart coverage. Let's try to add the simulator and see what happens on the Flutter CI.

**Comment by knopp** [comment]
First attempt is here: https://github.com/flutter/flutter/pull/148752. Let's see what happens.

**Comment by dcharkes** [comment]
> First attempt is here: #148752. Let's see what happens.

```
09:29 +69 -1: loading test/integration.shard/isolated/native_assets_test.dart [E]
  Failed to load "test/integration.shard/isolated/native_assets_test.dart": No running iOS simulator found
  test/integration.shard/isolated/native_assets_test.dart 112:7  main
```

No simulator on the integration shard.

I remember now, we run the tests on the device lab:

https://github.com/flutter/flutter/blob/d02292dbc40952a59dd1231ca2fb5ca86b39344c/dev/devicelab/lib/tasks/native_assets_test.dart#L59-L101

`$ cd <...>/flutter/dev/devicelab && dart bin/test_runner.dart test -t native_assets_ios_simulator`

**Comment by knopp** [comment]
I modified the test to create a simulator just for the test and delete it after. Hopefully I can get it to fail the expected way :)

**Comment by knopp** [comment]
@dcharkes, it seems to work. The macOS integration test [fails on simulator](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8747338159977184145/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/stdout?format=raw) with 

```
'Invalid argument(s): Couldn\'t resolve native function \'sum\''
```

The test creates simulator and destroys it in `tearDownAll`. I think this could be the way to go here.

Linux and Windows integration tests seem to fail too, but for unrelated reasons. Not sure what is going on there.

**Comment by jmagman** [comment]
@dcharkes it would be helpful to have a real hot integration test with the native assets, like:
https://github.com/flutter/flutter/blob/e6fa8655819e9b92740911b49e8215efc6e52dab/dev/devicelab/bin/tasks/hot_mode_dev_cycle__benchmark.dart#L9
https://github.com/flutter/flutter/blob/e6fa8655819e9b92740911b49e8215efc6e52dab/dev/devicelab/lib/tasks/hot_mode_tests.dart#L23

**Comment by dcharkes** [comment]
> @dcharkes it would be helpful to have a real hot integration test with the native assets, like:
> 
> https://github.com/flutter/flutter/blob/e6fa8655819e9b92740911b49e8215efc6e52dab/dev/devicelab/bin/tasks/hot_mode_dev_cycle__benchmark.dart#L9
> 
> 
> https://github.com/flutter/flutter/blob/e6fa8655819e9b92740911b49e8215efc6e52dab/dev/devicelab/lib/tasks/hot_mode_tests.dart#L23

I believe that is exactly what I was referring to that we already have. Using the stdin and stdout to trigger and observe hot reload and hot restart:

https://github.com/flutter/flutter/blob/e6fa8655819e9b92740911b49e8215efc6e52dab/dev/devicelab/lib/tasks/native_assets_test.dart#L77-L81

**Comment by jmagman** [comment]
> I remember now, we run the tests on the device lab:

Sorry, I should have read closer. 🙂
