### ISSUE TITLE
flutter build ios default has changed to device. Should be simulator. 

### ISSUE THREAD

**Issue by tomnewton** [flutter/flutter#14883]
It looks like the default may have changed for the: `flutter build ios` command.

Following the instructions on https://flutter.io/developing-packages/#dart no longer works because: 

`flutter build ios` doesn't build if you don't have a provision profile because the default seems to have changed to build for device. This used to work.

 You must run `flutter build ios --simulator` to generate the project files for xcode properly.

**Comment by tomnewton** [comment]
Actually this just seems to be completely broken - the resulting .xcworkspace doesn't run.

**Comment by xster** [comment]
Seems like `flutter build ios` defaulted to a physical device build since it was created https://github.com/flutter/flutter/commit/3f9dcfe144a769597099755b17281d622aab8775. 

https://flutter.io/developing-packages/#dart should definitely be edited to recommend `flutter build ios --simulator` or `flutter build ios --no-codesign` or something to avoid these issues.
