### ISSUE TITLE
Beta release is older than stable release

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#148952]
### Type of Request

bug

### Infrastructure Environment

Github

### What is happening?

Beta is even older than stable version (by approx 4 weeks)

### Expected results

Beta should be between main and stable, but right now it is sitting completely outdated even before stable version

**Comment by MominRaza** [comment]
> Beta is even older than stable version (by approx 4 weeks)

No beta is not behind stable release. But stable release received two hot fixes.

![image](https://github.com/flutter/flutter/assets/42776853/1f5c778d-864b-40cd-9ff2-f4a74a5a72f7)
![image](https://github.com/flutter/flutter/assets/42776853/83c403b4-4bf1-4b40-bf92-45d7867ed55a)
![image](https://github.com/flutter/flutter/assets/42776853/2bef2fce-751f-4a07-b3a8-3e7e137eba27)

Both beta and stable branches are based on 3.22-candidate.0 which is 896 commits behind master. But recently stable/3.22-candidate.0 received two hot fixes.

**Comment by MohiuddinM** [comment]
Learn to look things up before dropping random comments:
stable: [3.22.0](https://github.com/flutter/flutter/releases/tag/3.22.0) released on May 9
beta: [3.22.0-0.3](https://github.com/flutter/flutter/releases/tag/3.22.0-0.3.pre) released on Apr 24

**Comment by MominRaza** [comment]
Please read the [github code of conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct) while commenting.

That being said, now I come to your actual issue, ie. stable is 4 weeks ahead of beta which is not correct.

Release date doesn't mean that it contains the latest code.

As I shared screenshots in the last comment, that both beta and stable are 896 commits behind the master which means both stable 3.22.0 and beta are the same.
Only there is a difference of two hot fixes which come in 3.22.1.

### Now the question is why both stable and beta are the same. Beta has to be ahead of stable

Because stable release is nothing but every 3rd beta release. Which means the 3rd beta release becomes stable. And in the release month both beta and stable become the same.

Let me explain to you with examples of last releases

3.16 beta -> 3.16 stable
3.17 beta
3.18 beta
3.19 beta -> 3.19 stable
3.20 beta
3.21 beta
3.22 beta -> 3.22 stable

Currently we are in the release month.
3.22 beta released on 23 Apr so we are very close to getting 3.23 beta.

### Where stable hotfix release fix in this

As stable release only happens quarterly. Some highly critical issues directly get fixed in the stable release even before beta sometimes.

**Comment by MohiuddinM** [comment]
According to SemVer that pubspec uses `3.4.0-282.3.beta` is older than `3.4.1` (or even `3.4.0`). It does not matter whether both have the same features it results in an error. Now, the only solution is to wait for a new beta release that has 3.5.0-xyz or switch to another branch. Hope you understand the problem that even if both branches have the same features, the build system can fail simply because the version is different.

**Comment by MohiuddinM** [comment]
It's been 4 days and my build is still broken? Is there an update on it?

**Comment by MohiuddinM** [comment]
ping @goderbauer

**Comment by christopherfujino** [comment]
This has been resolved with newer releases.
