### ISSUE TITLE
Delete dynamic_layouts from the packages repo

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#148979]
The [dynamic_layouts](https://github.com/flutter/packages/tree/main/packages/dynamic_layouts) package is unpublished, and its core feature set has not been updated in years.  

Though it's not high-traffic, all packages in that repo require maintenance for Flutter versions, gradle bumps, and project migrations.

See initial commit and design links at https://github.com/flutter/packages/pull/2488.

We should have a plan to make it usable https://github.com/flutter/flutter/issues/127157#issuecomment-1555088165 and publish it, or we should delete it and let the community pick it up, if needed.

cc @Piinks @goderbauer @stuartmorgan

**Comment by Piinks** [comment]
I agree it should be moved since it was not published. There was an outstanding garbage collection issue that was not resolved. 

Could we put it in a separate repo? Maybe one that is archived? It is likely part of the portfolios of the folks that worked on it.

Have we turned down packages before? Maybe where ever they went is a place this one could go.

**Comment by huycozy** [comment]
From the first triage: If we discontinue or move this package into a separate repository, we also need to remove it from `Flutter's first-party packages` issue template.

**Comment by Piinks** [comment]
Filed https://github.com/flutter/packages/pull/6830 and https://github.com/flutter/flutter/pull/149252 to make it so.
