### ISSUE TITLE
X Unable to locate Android SDK

### ISSUE THREAD

**Issue by RaghunathAndroid** [flutter/flutter#14911]
## Logs
![image](https://user-images.githubusercontent.com/25322981/36720701-d205ef28-1bce-11e8-92c0-4b314db8ecf8.png)

**Comment by cbracken** [comment]
Based on your screenshot, it looks like you've got Android Studio installed. What path is your Android SDK installed to? The `flutter` tool looks in the most likely default install locations, specifically C:\Users\Your.name\AppData\Local\Android\Sdk or at the path specified by `%ANDROID_HOME%`.

Setting the `%ANDROID_HOME%` environment variable should allow flutter to locate the SDK.

**Comment by RaghunathAndroid** [comment]
@cbracken  Thanks for your reply 
if I set ANDROID_HOME <sdkpath> and flutter doctor is running perfectly, but if i close the cmd prompt and reopen and  run flutter doctor I face the same issue

**Comment by cbracken** [comment]
@RaghunathAndroid to set environment variables that persist across sessions, you'll need to set them in the Control Panel. You can find details in this StackOverflow article:
https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them

Closing since that should get you unblocked. Let us know if not!
