### ISSUE TITLE
Support numberDecimal and numberSigned keyboard type

### ISSUE THREAD

**Issue by mikelward** [flutter/flutter#14916]
Following on from #14554, TextInputType does not appear to support explicitly requesting numberDecimal, numberSigned, or a combination of those.

Without this, it's not possible to show a numeric soft keyboard that allows only number, decimal, and minus (negative).

**Comment by sbaranov** [comment]
Android documentation seems to imply that InputType.number only includes digits, and you can combine it with numberDecimal and/or numberSigned if you also want additional symbols: https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType

However, this behavior doesn't seem to be enforced by some firmwares, as some devices show additional symbols even if only InputType.number is specified without additional flags. I tested this on Nexus 5X (7.1.1) and Nexus 6P (6.0), and both of them show additional symbols that can't be disabled.

So we have a couple of options for Flutter's TextInputType:
1) (Preferred) Keep TextInputType.number mapped to InputType.number as it is today, and add new enum values TextInputType.numberDecimal and numberSigned, to allow your app to explicitly enforce additional symbols on the keyboard if needed.

2) Translate TextInputType.number to combination InputType.number|numberDecimal|numberSymbol. This way, you will lose device specific behavior, and Flutter will always enforce all numeric symbols to appear on the keyboard (which is why this might not be such a great idea). At least on some devices, this will be a breaking change, although probably not a huge one.

In either option, you won't be able to reliably *disable* extra symbols no matter what, since Android API doesn't seem to allow this, at least on some devices.

I'm leaning towards 1), but thoughts are welcome.

**Comment by mikelward** [comment]
1) Does not appear to allow numberDecimal and numberSigned simultaneously, unless you're thinking of making the enum values bitfields?  Note also there are other flag bits, e.g. textAutoCorrect/TYPE_TEXT_FLAG_AUTO_CORRECT
https://developer.android.com/training/keyboard-input/style.html#Spelling
https://developer.android.com/reference/android/text/InputType.html

2) Seems fine to me.

**Comment by sbaranov** [comment]
I see a comment on top of TextInputType:
/// On Android, behavior may vary across device and keyboard provider.

This seems to imply that option 1 was assumed in the original design, but I'll get opinions from the team to narrow down our options.

JFYI, Flutter supports autocorrect flag as separate parameter in widget constructor (not a bit field).

**Comment by sbaranov** [comment]
For option 1, we would probably introduce a full set of enum values in TextInputType (number, numberDecimal, numberSigned, numberSignedDecimal).

For option 2, we would simply always enforce number|numberDecimal|numberSigned on Android, in TextInputPlugin.inputTypeFromTextInputType().

**Comment by tvolkert** [comment]
Option 1 sounds more versatile.  /cc @jason-simmons

**Comment by Hixie** [comment]
I prefer #1, but adding `numberSignedDecimal` is a red flag to me. What if Android adds another flag, like `TYPE_NUMBER_FLAG_HEX` ? Do we now add another 4 enum types? And when they add `TYPE_NUMBER_FLAG_INFINITY` we add another 8? This doesn't scale...

Here's a crazy idea for an option 3:

```dart
class TextInputType {
  const TextInputType(this.index) : negative = null, symbols = null;
  const TextInputType.numeric({ this.negative: false, this.symbols: false }) : index = 2;

  final int index;
  final bool negative;
  final bool symbols;

  static const TextInputType text = const TextInputType._(0);
  static const TextInputType multiline = const TextInputType._(1);
  static const TextInputType number = const TextInputType.numeric();
  static const TextInputType phone = const TextInputType._(3);
  static const TextInputType datetime = const TextInputType._(4);
  static const TextInputType emailAddress = const TextInputType._(5);
  static const TextInputType url = const TextInputType._(6);

  static const List<TextInputType> values = const <TextInputType>[
    text, multiline, number, phone, datetime, emailAddress, url,
  ];

  operator == (dynamic other) { ... } // compares all the fields
  int get hashCode => ...; // handles all the fields
}
```

**Comment by escamoteur** [comment]
Just came about this when trying to set just `TextInputType.number` on my emulator of a Pixel2 I still get  ',' '.' and can add as many '-' or spaces

**Comment by sbaranov** [comment]
You're getting the minimal possible keyboard provided by the underlying
device & OS that still has numeric features, which could mean that it might
have more than what was requested.

**Comment by faridg18** [comment]
Add this property to your text field 

     keyboardType: TextInputType.numberWithOptions(decimal: true,),
