### ISSUE TITLE
dragHandleSize can't be larger than 48

### ISSUE THREAD

**Issue by xVemu** [flutter/flutter#149170]
This code makes it impossible to make the drag handle larger than 48x48.

https://github.com/flutter/flutter/blob/a1a33e63b911bfe0b58dc1b2710f6eddb2cb6e4e/packages/flutter/lib/src/material/bottom_sheet.dart#L459-L462

**Comment by huycozy** [comment]
Hi @xVemu 
Are you proposing to be able to set a specific larger size (a fixed size) or a dynamic size for the drag handle? Per M3 specs [Touch and pointer target sizes](https://m3.material.io/foundations/designing/structure#b421e522-35a6-47cd-bfc6-bf94cbacf7bb):

>Touch targets are the parts of the screen that respond to user input, extending beyond the visual bounds of an element. For example, an icon may appear to be 24 x 24dp, but the padding surrounding it comprises the full 48 x 48dp touch target.

>For most platforms, consider making touch targets at least 48 x 48dp. A touch target this size results in a physical size of about 9mm, regardless of screen size. The recommended target size for touchscreen elements is 7-10mm. It may be appropriate to use larger touch targets to accommodate a larger spectrum of users.

Does this make sense?

**Comment by xVemu** [comment]
> Hi @xVemu Are you proposing to be able to set a specific larger size (a fixed size) or a dynamic size for the drag handle?

I'm talking about fixed size.

> Does this make sense?

It makes sense, but I still think there should be an option to make it larger, if someone don't want to stick to M3 specs.

**Comment by huycozy** [comment]
If it's a fixed size, what size are you proposing? It would be clearer if you could also share your use case.

**Comment by xVemu** [comment]
By _fixed size_, I mean that the programmer can set the size using `dragHandleSize`. Currently, this only works if the width is set to a value smaller than 48. If you try to set it to, for example, 64, it remains at 48.

Basically, I want to do this:
![image](https://github.com/flutter/flutter/assets/38427679/38f7b0db-cf24-40d8-8329-07734f815c5b)

Instead of this:
![image](https://github.com/flutter/flutter/assets/38427679/b2b5006c-15c6-44e7-aabd-c340899c265b)

**Comment by huycozy** [comment]
>I mean that the programmer can set the size using dragHandleSize. 

Currently, `dragHandleSize` is not exposed to `showModalBottomSheet`; it only resides on `BottomSheet` widget underlying. But we can set it through `bottomSheetTheme`:

https://github.com/flutter/flutter/blob/35ae5191402bccbe573bb780c03f832dff0687ed/packages/flutter/lib/src/material/bottom_sheet.dart#L450

### Example of setting dragHandleSize
```dart
bottomSheetTheme: const BottomSheetThemeData(
    dragHandleSize: Size(96, 12)
),
```

<img width="500" src="https://github.com/flutter/flutter/assets/104349824/53089e67-311e-4d15-ad30-ac2b85b1da06">


Despite that, it's limited by an ancestor widget with fixed size `kMinInteractiveDimension` as you mentioned originally:

https://github.com/flutter/flutter/blob/35ae5191402bccbe573bb780c03f832dff0687ed/packages/flutter/lib/src/material/bottom_sheet.dart#L459-L466

Marking this as a proposal. Since this change is made by https://github.com/flutter/flutter/pull/122445, cc @hangyujin for thoughts.
