### ISSUE TITLE
[Feature Request] Have a new TextInputType to show numbers keyboard first, with the possibility to switch back to text keyboard

### ISSUE THREAD

**Issue by giordy16** [flutter/flutter#149166]
### Use case

On my app I have a `TextField` and I need that once it's clicked, a keyboard with access to numbers is shown. 

### Proposal

Since on iOS is not possible to have a keyboard with numbers on the top (https://github.com/flutter/flutter/issues/131756), and on Android is not possible to show numbers and symbols keyboard by default (https://stackoverflow.com/questions/72665124/how-to-show-keyboard-with-numbers-and-symbols-by-default-ionic), I would like to have a new TextInputType that has 2 different behaviors on the platform, but resolves the problem.
On android, it would behave like TextField.visiblePassword, so the numbers are shown on the top of the keyboard.
On iOS, `UIKeyboardType.numbersAndPunctuation` would be called (which I don't think it's called at the moment by any `TextField` type),  to show numbers and symbols keyboard by default.

In both cases, I have first access to numbers, and then I can access easily to text characters.

**Comment by huycozy** [comment]
>I have first access to numbers, and then I can access easily to text characters.

Could you share any apps which is feasible to do this? It will be easier to imagine if you have a demo of this feature on apps you have seen.

**Comment by giordy16** [comment]
On my app I have several `TextField` where the user can enter a text which has the format "<numbers><text>", where the size of <numbers> and <text> is not fixed, so would be practical to have a quick access to numbers and letters on the keyboard.

This would be my desired output

<img width="1512" alt="Screenshot 2024-05-29 at 12 05 44" src="https://github.com/flutter/flutter/assets/112980257/0c0b3b2d-4f45-49a5-9e81-a99098c943b0">

But on iOS this kind of keyboard is not supported. For this reason, the best option on iOS would be to create the `TextField` with `UIKeyboardType.numbersAndPunctuation`, which shows this kind of keyboard

![Simulator Screenshot - iPhone 15 - 2024-05-29 at 12 10 16](https://github.com/flutter/flutter/assets/112980257/b617cc16-e3ab-4b35-83fa-be2396ac167a)

**Comment by huycozy** [comment]
`numbersAndPunctuation` has been added by https://github.com/flutter/engine/pull/18202. And the keyboard with numbers can be shown with `TextInputType.datetime` or `TextInputType.number` in Flutter: https://github.com/flutter/engine/blob/19707e811b608b2ecf8633f26d534f7896b87c52/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L110-L125

For the such keyboard from above screenshot, it can be displayed with `keyboardType: TextInputType.datetime`. 

Since this is already supported, I will close this issue as solved. If you disagree, please write in the comments and I will reopen it.
