### ISSUE TITLE
Publish an Article on how to integrate with 3rd party views.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14927]
The topic of integrating with 3rd party iOS or Android Views is a subtle one and probably deserves its own article or medium post.

Putting an arbitrary iOS or Android view, below, above or next to a FlutterView is easy today and there are some examples here:
https://github.com/flutter/flutter/tree/master/examples/flutter_view
https://github.com/flutter/flutter/tree/master/examples/platform_view
And others who have built plugins in similar veins:
https://pub.dartlang.org/packages/flutter_webview_plugin

There is work in progress to play nice with CALayers and allow integration with arbitrary views *inline* with other Flutter Widgets on iOS.  @mravn-google is leading that.

Android is a bit more difficult (I'm not aware of a CALayer equivalent), but we have some possibilities in mind which we're exploring as part of https://github.com/flutter/flutter/issues/73

Of course its always possible to integrate with 3rd party Widgets written in Flutter (there are lots of Flutter packages on pub.dartlang.org which provide visual elements).

It's also possible to integrate arbitrary foreign GL textures with:
https://docs.flutter.io/flutter/widgets/Texture-class.html
Which is how things like:
https://github.com/flutter/plugins/tree/master/packages/camera
https://github.com/flutter/plugins/tree/master/packages/video_player
work.

The challenges lie around integrating 3rd-party visual elements which are *only* made available as Android Views, but we're working on solutions and once we have a clear story there we should document it.

**Comment by mravn-google** [comment]
Update: The inline CALayer approach has been paused due to software complexity and performance impact of the thread hopping necessary in the Flutter engine to have our compositor interact with CALayers and/or UIViews. It is presently unclear whether and when we'll take up that line of thought again.

So at least for the time being, the solution available to integrating third-party views is via the Texture widget and the underlying flutter/engine support ([TextureRegistry](https://docs.flutter.io/javadoc/io/flutter/view/TextureRegistry.html)/[FlutterTextureRegistry](https://docs.flutter.io/objcdoc/Protocols/FlutterTextureRegistry.html)). Documentation in flutter/engine is patchy, but you'll find example uses in the video and camera plugins referenced above as well as in German Saprykin's excellent [medium.com post](https://medium.com/@germansaprykin/opengl-with-texture-widget-f919743d25d9) showing how to use OpenGL with Flutter's Texture widget in general.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2064](https://github.com/flutter/website/issues/2064) via [**ZenHub**](https://www.zenhub.com/)
