### ISSUE TITLE
Push the solution of 'Pixel align subpass textures' to stable

### ISSUE THREAD

**Issue by Schefferbird** [flutter/flutter#149302]
### Use case

there have to be many flutter devs who can't use Flutter 3.22.1 due to the following status of issues.

============
[Impeller] Distorted text in Cupertino dialog #148588
which is related to:
[Impeller] Pixel align subpass textures. #52973

The solution for the issue above is pushed into
Flutter 3.22.0-43.0.pre.3 

Which also contains the error of:
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

Which also exist in the latest master:
Flutter 3.23.0-12.0.pre

============

### Proposal

Yes, this has to be provided by Flutter. It's more or less a push request.

**Comment by darshankawar** [comment]
> [Impeller] Distorted text in Cupertino dialog #148588

@Schefferbird This is fixed and should be available in master version.



> [Impeller] Pixel align subpass textures. #52973

This is very old issue so not sure if it is relevant.


> Which also contains the error of:
> [ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

This is duplicate of https://github.com/flutter/flutter/issues/148851 in which I see you have already commented. Please follow-up in the linked issue for further updates. I'll close this issue as duplicate. If you disagree, write in comments and I'll reopen it.

If your ask is to push the fixes to stable, then please read about https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md

If the fix in master is a low-risk then it is hotfixed to stable, otherwise they all get in stable in quarterly releases.

**Comment by Schefferbird** [comment]
The relevance is that I can't use 3.22.0-1 due to the issue [Impeller] Distorted text in Cupertino dialog (https://github.com/flutter/flutter/issues/148588). And even if there is a solution in Flutter 3.22.0-43.0.pre.3 I cant use that because of [Impeller][regression] image.toByteData fails to convert raster image to PNG (https://github.com/flutter/flutter/issues/148851) is not solved. The app totally breaks down due to this issue. And to wait a quarter for as an important issue as dialog text is not displayed correctly is quite a drawback.
