### ISSUE TITLE
[go_router] ability to have a default pop to

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#149359]
### Use case

When accessing root routes directly (EG: By pressing F5 in the browser) that are meant to be pushed like `/about`, `/changelog` and the likes `Scaffold` won't have a `BackButton` because it has no route to pop to. It would be handy to support the ability to add a route behind on the stack so that instead of being: `[ '/changelog' ]` it would be `[ '/' , '/changelog' ]`.

### Proposal

```dart
GoRoute(
  path: '/changelog',
  defaultPopTo: '/', // will pop to '/' if the navigator cannot pop
)
```

Behind the scene this would add the `/` page to the page stack so the `BackButton` appears in scaffolds

**Comment by ValentinVignal** [comment]
@cedvdb How are you accessing those routes?
- If you access them via a push, you should have `BackButton` since your stack contains your previous route.
- If you access them via a `go` or from a deep link, maybe you should nest those routes inside the one you expect to be the _"default route to pop"_ :

```dart
GoRoute(
  path: '/',
  routes: [
    GoRoute(path: 'about'),
    GoRoute(path: 'changelog'),
  ]
)
```

That should match your expectations

**Comment by cedvdb** [comment]
@ValentinVignal 

Here is a more detailed explanation:

In our app we have `/account-dashboard-seller` and `/account-dashboard-customer`. The user can switch between the seller or customer mode. On both account-dashboard page , when we press the 'about' the `/about` page is pushed. 

While this did work with only one account dashboard:

```
GoRoute(
  path: '/account-dashboard',
  routes: [
    GoRoute(path: 'about'),
  ]
)
```

we now have 

```
GoRoute(
  path: '/account-dashboard-seller',
  routes: [
    GoRoute(path: 'about'),
  ]
)
//
GoRoute(
  path: '/account-dashboard-customer',
  routes: [
    GoRoute(path: 'about'),
  ]
)
```

While this isn't so bad, we have lots of those pages and having a default pop to was a mechanism I thought could resolve some of the duplication which increase the possible error surface and the tests that have to be written. For this reason, we didn't use the method above but simply put the `/about` and the likes at the top level with `BackButton` added and manually handled, which has benefits for our use cases.

So while we made it work today, an option to handle this use case another way would be handy.

**Comment by ValentinVignal** [comment]
When you are saying _"when we press the 'about' the /about page is pushed."_, are you using the `GoRouter.go` method or the `GoRouter.push` ? 

Because if you do use `GoRouter.push`, then this configuration should work:

```dart
[
  GoRoute(path: '/account-dashboard-seller'),
  GoRoute(path: '/account-dashboard-customer'),
  GoRoute(path: '/about'),
]
```

For example, when you are on `/account-dashboard-seller`, the history stack looks something like `[...,  /account-dashboard-seller]`. If you use `GoRouter.push("/about")` from this page, the history stack should change to `[...,  /account-dashboard-seller, /about]`. And when you use `GoRouter.pop()`, it should come back to `[...,  /account-dashboard-seller]`.
Same scenario with `[...,  /account-dashboard-customer]`.

Is there an issue with this approach?

**Comment by cedvdb** [comment]
@ValentinVignal it doesn't matter which method we are using. The issue is when you refresh the page, not after navigation.

**Comment by cedvdb** [comment]
Reopening because going back to it, I still believe this would be helpful

**Comment by chunhtai** [comment]
> So the /about page is meant to be pushed, but nothing stops an user from pressing F5 and being stuck on /about. Therefor a back button must be manually added.

Are you sure pressing F5 will not be able to go Back? The current logic will store entire route stack, even if they are imperative pushed, into the browser history.

**Comment by cedvdb** [comment]
@chunhtai 

On the web the user can type an url and access it directly for the first time. Therefor anything "stored" is irrelevant here.

 > Also, I think you can implement your own backButton that will call context.go('/') instead

This is what this issue is about. Maintaining those button is not that annoying but it still could be easier with a default pop to. This issue is to gauge the interest in such a feature and to see if such an API would be acceptable.
