### ISSUE TITLE
Error C3646 when building Flutter app for Windows，D:\Windows Kits\10\Include\10.0.22621.0\um\shellapi.h(524,20): error C3646: “lpStartupInfo”: 未知重写说明符

### ISSUE THREAD

**Issue by xwdiy520** [flutter/flutter#149570]
### Steps to reproduce

Run flutter create demo
Navigate to the project directory: cd demo
Attempt to build for Windows: flutter build windows

### Expected results

run ok

### Actual results

D:\Windows Kits\10\Include\10.0.22621.0\um\shellapi.h(524,20): error C3646: “lpStartupInfo”: 未知重写说明符 [D:\demo\flutter_demo\build\windows\flutter\flutter_wrapper_app.vcxproj]
![image](https://github.com/flutter/flutter/assets/17025438/1bc6bca5-97db-46c2-85b4-a23e7abe6912)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by xwdiy520** [comment]
Operating System: Windows 10
Flutter Version: 3.19.0
Steps to Reproduce

**Comment by huycozy** [comment]
Could you provide the entire output of `flutter run -v`?  (Please provide the output log in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text))

Please provide the output of `flutter doctor -v` as well.
