### ISSUE TITLE
Dart -> Engine roll failing on dart2wasm compilation failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#149600]
Starting in https://github.com/flutter/engine/pull/53168

In https://dart.googlesource.com/sdk.git/+log/53c41325c29f..411ddd5acfab there are a few dart2wasm commits from @osa1 and @mkustermann 

Unfortunately the logs don't have much info: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8746163314286567409/+/u/compile_bundle_dart2wasm-skwasm-ui/stdout

FYI @eyebrowsoffire

**Comment by eyebrowsoffire** [comment]
It turns out the issue is this: https://dart-review.googlesource.com/c/sdk/+/369020

In development, the web engine is a package (`package:ui`) and we run the unit tests against that package. Disallowing the `wasm:import` and `wasm:export` pragmas in user code therefore breaks all our engine unit tests. We probably need to have `package:ui` be allowlisted to use these. Or maybe introduce a flag we can use that allows user code to use these pragmas.

**Comment by a-siva** [comment]
A revert ( https://dart-review.googlesource.com/c/sdk/+/369500 ) has been submitted.

**Comment by eyebrowsoffire** [comment]
The revert unblocked the roller. Closing.
