### ISSUE TITLE
Simplify usage of iOS-11-style large titles

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#149625]
The large title styles that were introduced with iOS 11 and are commonly used in iOS apps. Creating this kind of common effect should be easy to achieve within Flutter. However, currently implementing them requires knowledge of slivers, which are a somewhat advanced topic that may seem scary to some developers. We should see if we can provide some kind of a simpler wrapper widget to make this effect more approachable.

This is the code that developers currently have to write to get the desired effect:

```dart
class SliverNavBarExample extends StatelessWidget {
  const SliverNavBarExample({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: CustomScrollView(
        slivers: <Widget>[
          const CupertinoSliverNavigationBar(
            largeTitle: Text('Contacts'),
            trailing: Icon(CupertinoIcons.add_circled),
          ),
          SliverList.builder(
            itemCount: 5,
            itemBuilder: (BuildContext context, int index) {
              return CupertinoListSection(
                header: Text(['S1', 'S2', 'S3', 'S4', 'S5'][index % 5]),
                children: const [
                  Text('C1'),
                  Text('C2'),
                  Text('C3'),
                  Text('C4'),
                  Text('C5'),
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}
```

It should also be noted that `CupertinoPageScaffold` with its `CupertinoPageScaffold.navigationBar` property sends developers down the wrong path. Setting up the navigation bar that way will not give you the large titles style.

Unrelated-related: The `CupertinoListSection` could also be more efficient by allowing for lazily built children (see https://github.com/flutter/flutter/issues/119558).

**Comment by goderbauer** [comment]
cc @mit-mit

**Comment by navaronbracke** [comment]
It seems you weren't the first for the second point :)

See https://github.com/flutter/flutter/issues/119558

**Comment by kerberjg** [comment]
I second this. AFAIK Flutter doesn't support iOS versions < 11 anymore, so being able to implement titles in a straightforward way is a requirement for our apps to appear credible

**Comment by victorsanni** [comment]
My understanding of this request is to have a parallel of ListView (wrapping a scroll view with a SliverList) that can be used without having to set up CustomScrollView?

**Comment by victorsanni** [comment]
> My understanding of this request is to have a parallel of ListView (wrapping a scroll view with a SliverList) that can be used without having to set up CustomScrollView?

Or is this just asking for a static persistent pinned large title that's always shown on the page?

**Comment by Piinks** [comment]
> Or is this just asking for a static persistent pinned large title that's always shown on the page?

Perhaps a bit of both?

I have a PR out now that adds support for the large layout in the static CupertinoNavigationBar, which does not scroll, but it should be able to reflect both layout options, since Apple supports that as well for static navigation bars. I consider CupertinoNavigationBar and CupertinoSliverNavigationBar similar to AppBar and SliverAppBar in the material library. One is a static box widget, the other scrolls and dynamically changes layout in response.

> My understanding of this request is to have a parallel of ListView (wrapping a scroll view with a SliverList) that can be used without having to set up CustomScrollView?

This is something you would use the NestedScrollView for to insert a SliverAppBar or a CupertinoSliverNavigationBar above a ListView or GridView in the body.
Over the years there have been some ideas for scrolling widgets that have headers like SliverAppBar built-in, but since NestedScrollView does that already, it hasn't been a high priority to add yet another way to do it.

**Comment by mit-mit** [comment]
Hi @Piinks can you elaborate on the _"but it should be able to reflect both layout options, since Apple supports that as well for static navigation bars."_ part? Does that mean that you do indeed plan on a follow-up PR to make it easy to create a scaffold with a large title that animates to small on scroll? I think that would be nice to make easy.
