### ISSUE TITLE
C++ static lib and framebuffer / event low level exposure

### ISSUE THREAD

**Issue by codethinki** [flutter/flutter#149795]
### Use case

OS: windows
Language: c++

I'd like to use flutter embedded into my own rendering app as "Ui engine". 
The problem is that i dont know if that is even possible and if yes i would love it if i could receive some help regarding where to find stuff.

1. Build flutter & dart into a static lib
- which file handles the build config?
- where is the dart vm communication happening in flutter?
2. edit the even handling file to pull events from a custom sharepoint instead of pulling it directly from the win
- which files handle this job?
3. edit the engine to not create its own window and export the framebuffer
- where do i find the flutter engine and the framebuffer handling?

I'd would be great if somebody could help me with these questions.

Also if you know anything that i forgot which i could depend on please tell me

### Proposal

no real proposal as this is probably not a use case that is requested by many people

**Comment by huycozy** [comment]
Hi @codethinki 
Please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow and [flutterhelp](https://www.reddit.com/r/flutterhelp/).

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
