### ISSUE TITLE
Display list clip culling doesn't seem effective during material page transition with an image filter.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149782]
Using the following sample application, run on an Android device with the additional flags specified here:

`flutter run  --enable-impeller --dart-define=flutter.benchmarks.force_disable_snapshot=true`

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: ExampleApp()));
}

class ExampleApp extends StatefulWidget {
  const ExampleApp({super.key});

  @override
  State<ExampleApp> createState() => _ExampleAppState();
}

class _ExampleAppState extends State<ExampleApp> {
  @override
  Widget build(BuildContext context) {
  return ClipRect(
    child: Scaffold(
      body: Center(
        child: TextButton(onPressed: () {
          Navigator.of(context).push(MaterialPageRoute<void>(
            builder: (BuildContext context) {
              return Scaffold(
                body: Center(
                  child: TextButton(
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                    child: const Text('Back'),
                  )
                )
              );
            }
          ));
        }, child: const Text('Click me')),
      ),
    ),
  );
  }
}

```

I would expect that the ClipRect would always be culled. To double check this, I added a few print statements to the impeller canvas:

```diff
diff --git a/impeller/aiks/canvas.cc b/impeller/aiks/canvas.cc
index bc8d1af742..12babc11d9 100644
--- a/impeller/aiks/canvas.cc
+++ b/impeller/aiks/canvas.cc
@@ -603,7 +603,10 @@ void Canvas::ClipRect(const Rect& rect, Entity::ClipOperation clip_op) {
       cull_rect.has_value() &&                                             //
       geometry->CoversArea(transform_stack_.back().transform, *cull_rect)  //
   ) {
+    FML_LOG(ERROR) << "Cull Rect Geometry: " << rect;
     return;  // This clip will do nothing, so skip it.
+  } else {
+    FML_LOG(ERROR) << "Apply Rect Geometry: " << rect;
   }
 ```
 
While navigating, we first successfully cull the rect then on subsequent frames of the navigation fail to cull:

```
I/flutter (11001): [IMPORTANT:flutter/shell/platform/android/android_context_vulkan_impeller.cc(67)] Using the Impeller rendering backend (Vulkan).
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(606)] Cull Rect Geometry: ((0, 0), (411.429, 867.429))
D/VRI[FlutterActivity](11001): Draw frame after cancel
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(606)] Cull Rect Geometry: ((0, 0), (411.429, 867.429))
Syncing files to device Pixel 7 Pro...                              44ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Pixel 7 Pro is available at: http://127.0.0.1:59456/UXNfOEjVydA=/
The Flutter DevTools debugger and profiler on Pixel 7 Pro is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:59456/UXNfOEjVydA=/
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(606)] Cull Rect Geometry: ((0, 0), (411.429, 867.429))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (78.8586, 40))
W/WindowOnBackDispatcher(11001): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(11001): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (411.429, 867.429))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (78.8586, 40))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (411.429, 867.429))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (78.8586, 40))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (78.8586, 40))
E/flutter (11001): [ERROR:flutter/impeller/aiks/canvas.cc(609)] Apply Rect Geometry: ((0, 0), (411.429, 867.429))
```

The larger rect is the clip rect, the smaller one is from the button and should be ignore.

I'd expect that if DL was doing the culling it wouldn't reach the impeller canvas. I _think_ we should be able to cull this clip, but right now we disable the impeller cull rect tracking when there are image filters: 

https://github.com/flutter/engine/blob/main/impeller/aiks/canvas.cc#L858-L865

FYI @flar

**Comment by jonahwilliams** [comment]
From a discussion offline with @flar , when using the experimental canvas - we have the size of the render target. Lets use that to determine if the clip is irrelevant.

**Comment by flar** [comment]
I think the first one can be culled in the DisplayList, but we'd need more information. The conservative assumption that the DLBuilder is currently making is "I can trust the current clip only if it came from another call to clipRect/RRect that was recorded by me". The initial cull rect comes from the constructor and we sometimes get a rect there that isn't necessarily trustable. On the other hand, Impeller always knows the actual size of the drawable into which they can render, so they can cull this rectangle so it is easy for them to trust the information there.

But, when we prepare a DLBuilder to record the layer tree, that instance is created by the SurfaceFrame, it is created with the actual size of the drawable for the frame. So, if SurfaceFrame could identify "here is your initial cull rect *and* that cull rect is not an estimate, you can trust it" then we could cull that first large clipRect call.

An area where DLBuilder can't do it early is when we are creating a layer (i.e. saveLayer), for a couple of reasons. First, DLBuilder is responsible for vetting the bounds of the saveLayer. If the saveLayer call didn't have any bounds, then there is nothing to compare against. And if the saveLayer call had bounds, we still compute the full bounds of the content so that we can see if they are being clipped. On top of that, if the DL is being rendered in a rotated/skewed coordinate system, then the clip call might have impact even if it is a superset of the bounds provided by the caller - because those bounds are used to create a layer in Impeller - one that might be larger than the actual bounds due to rotation/skewing and which might include pixels outside of those bounds. So, the layer is being culled to the bounds of the saveLayer, however they turn out in the calculations inside of Impeller. In order for DLBuilder to be able to make an assumption there, we'd have to commit to always clipping to the bounds of the saveLayer in Impeller so that the Builder would have an accurate and reliable idea of what the culling bounds would be.

**Comment by flar** [comment]
Ugh, it turns out that in cases like the above, the entire DL is recorded from Dart using a ui.PictureRecorder and they hand in +/-1e9 as the bounds for the frame in that case. So, the DLBuilder will likely never reliably see an accurate frame size...

**Comment by jonahwilliams** [comment]
Rather than change DLBuilder, should we udate the transform render object to provide save layer bounds:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L2571

Am I understanding you correctly that providing the correct bounds here would allow a clipRect that is the same size as these bounds to be culled?

**Comment by flar** [comment]
Right now Builder::saveLayer always doubts its bounds (as Impeller had been doing) and recomputes them on the fly - which creates a chicken/egg condition on trying to cull the bounds there. This isn't necessarily just "providing bounds" on the saveLayers, but being able to assert that the bounds are authoritative rather than just a hint.

I'll also re-iterate that saveLayer bounds, even coming from a trusted source and computed fairly rigorously are not enough to cull clips against them because we don't guarantee the clips at the backend level (neither Skia nor Impeller guarantee that the rendering will be clipped to the bounds, they just use it as an estimate to allocate the layer - which could be rotated and not restricted by the drawable bounds). So, it's more complicated than "can we trust the caller".

But, to the end of creating a path of trust for saveLayer bounds...

I'm not sure about the RenderObjects as I don't know how well they know what bounds they will be rendering, but the native engine layers should be pretty authoritative on the bounds of their layers since we use those bounds for layer culling (see https://github.com/flutter/engine/blob/1a51d5e82001d135a461426cfa6a699359e22655/flow/layers/layer.h#L244). Those native bounds are computed during Preroll from the actual data to be rendered, so if that native layer renders a saveLayer we could possibly mark it as "trusted". There may be other internal places where we can be certain of the bounds which could make use of that, but bounds coming from Dart I would find suspect without further information. Note that a widget/RO only uses a native layer if there is compositing in the children.

**Comment by jonahwilliams** [comment]
I don't think there is much to do here. Instead I'm counting on us updating to the M3 page transition
