### ISSUE TITLE
Presubmit engine builds not uploading properly to `flutter_archives_v2` GCS bucket

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#149780]
It appears that presubmit builds are no longer uploading to a stable location in GCS, therefore making the instructions https://github.com/flutter/flutter/blob/master/docs/engine/Testing-presubmit-Engine-PRs-with-the-Flutter-framework.md invalid. The GCS bucket seems to namespace the artifacts by build bucket ID now. We suspect this started with this change: https://flutter-review.googlesource.com/c/recipes/+/57140

**Comment by christopherfujino** [comment]
For reference, see this engine try build that uploaded artifacts: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2389413/infra

**Comment by zanderso** [comment]
The breakage is due to the recipe change [here](https://flutter.googlesource.com/recipes/+/7a21186796e7e164dd2179d992dca8fa592adc97), which was a partial migration to a new way of uploading the artifacts from presubmit.

I believe that commit (and two follow-on fixes [here](https://flutter.googlesource.com/recipes/+/d3de063a41ec83848b5a94f1fd1ee176093d00a6) and [here](https://flutter.googlesource.com/recipes/+/b7f3b09438dbda61a5fae06dfb6d6a28c040ffd1)) can be safely backed out to restore the previous behavior. There's some risk that there were also compensating changes in the monorepo recipes that would also have to be reverted, as well, but I'm less familiar. @aam may remember.

**Comment by christopherfujino** [comment]
cc @athomas

**Comment by eyebrowsoffire** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/58220
