### ISSUE TITLE
The hello world app is blank after I switch apps or open it again

### ISSUE THREAD

**Issue by luan-cestari** [flutter/flutter#1499]
Hi,

I was trying to use flutter on my smartphone (samsung s5 SM-G900M) and after I swith to another app and come back to the demo or if I try to open the app I get an blank screen. There doesn't any erros in the logs except for this:

`android: W/ActivityManager: getTasks: caller does not hold GET_TASKS; limiting output`

So I tried changing the android manifest to include: 

`<uses-permission android:name="android.permission.GET_TASKS"/>`

but it didn't work. Do you guys have any clue what I can do find out what is happening please?

Thank you in advance.

Kind regards,
Luan

**Comment by abarth** [comment]
@jason-simmons was mentioning something related to this today.  We might be forgetting to invalidate some GPU resources when we lose the GL context.

**Comment by sethladd** [comment]
Thanks for the feedback! Could you do us a favor and paste in the output from `flutter --version` ?

**Comment by jason-simmons** [comment]
I have a fix in progress for an issue where SkyShell segfaults if you suspend and resume the application.  This is due to the Flow raster cache holding images that are associated with a GrContext that has been destroyed.

After applying this fix I'm now seeing a bug that matches this report.  If you suspend an app while repainting is in progress (e.g. while scrolling the list in the Stocks home page) the app renders a black screen after resuming.
I'll take a look at this today.

**Comment by luan-cestari** [comment]
Thanks guys =D Let me know if I can help with anything.

The output requested:
```
flutter --version                
Flutter
Repository: https://github.com/flutter/flutter.git
Branch: alpha
Revision: 1b75de1b164a3c5f668933a7603aa9094c181aae (4 days ago)
```

**Comment by jason-simmons** [comment]
fixed
