### ISSUE TITLE
Decide fate of Address Book

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1501]
What is it showing? Who is keeping it updated? What say we?

**Comment by sethladd** [comment]
cc @eseidel

**Comment by eseidelGoogle** [comment]
@abarth has been using it during text input work.  We never plan to use it as a sales demo, but it has been useful for development.  If it's no longer useful to Adam or @Hixie feel free to kill it.  Otherwise we can keep it for now, eventually add unittests or kill it.  If it's not tested it will rot and die.  I plan to add at least launch-testing to all examples/ as part of bringing up the new infrastructure.

**Comment by sethladd** [comment]
thanks for the clarification!
