### ISSUE TITLE
get-started page linting mistake

### ISSUE THREAD

**Issue by hyunstyle** [flutter/flutter#15048]
![image](https://user-images.githubusercontent.com/25246960/36880830-2651a996-1e0e-11e8-9248-a15d87e844ff.png)

Good afternoon, I'm just trying to follow flutter's beautiful [GET-STARTED example](https://flutter.io/get-started/codelab/), and as captured above, I find a trivial linting error. I'm worried about this is so trivial that it might not be an issue, but i don't have an idea how to report something like that in a better way. As a result I'm writing this in issue pages. If those pages not deal with such a trivial one, sorry about my fault.

And thanks always, as one of the person using your wonderful project, hopefully things will get better!

**Comment by DanTup** [comment]
Is it the indenting you're referring to? It looks like this was fixed in https://github.com/flutter/website/pull/864

![screen shot 2018-05-30 at 9 44 18 am](https://user-images.githubusercontent.com/1078012/40709485-15effece-63ee-11e8-9151-79762456bce7.png)

Let me know if this was the problem you meant; if so we can close this.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
