### ISSUE TITLE
ram comsumtion is to high after flutter update in linux

### ISSUE THREAD

**Issue by renggadiansa** [flutter/flutter#150500]
after I upgraded flutter when compiling the application the ram consumption became swelled and even full which made the emulator and code editor force me to close before I had never experienced something like this in the previous version

**Comment by huycozy** [comment]
Hi @renggadiansa 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See non-speed performance issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=from%3A+performance+template&projects=&template=4_performance_others.yml))

More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- What is Flutter version before upgrading?

And also relevant information related to memory issue you observed.
