### ISSUE TITLE
[pigeon] Make generated Swift classes and protocols optionally public for framework integration

### ISSUE THREAD

**Issue by kmaschke85** [flutter/flutter#150691]
### Use case

For my Add-to-app scenario I started to use Pigeon to generate Dart, Swift and Kotlin code for the method channels.
To include the generated Swift files into my app I am using Cocoapods, where the generated code is part of a development Pod. With that I can easily integrate the files, update them via Cocoapods and don't need to copy any files between projects. But when using this approach I can't use the Swift files that have been generated by Pigeon, because they are declared as `internal` (default when not using any other access modifier). In order for Swift classes and protocols to be used from outside a framework (which is the case for me when using via Cocoapods) they need to be declared as `public` or `open`.

### Proposal

Add an option `public` to `SwiftOptions` that when set would add the `public` access modifier to all protocols and classes.

**Comment by stuartmorgan** [comment]
Restricting class visibility is an intentional choice, since the details of generated classes are subject to change, and thus should not be used as public interfaces.

Could you elaborate on the use case here? How are you managing the generated Dart files in this model to ensure that all of the generated code remains consistent?

**Comment by kmaschke85** [comment]
The Kotlin, Swift and Dart files are all generated within the same Flutter project. Two things I want to avoid:
- copying the generated Swift file from the Flutter project to the host iOS project
- establish any references between the host iOS project and the Flutter project that is not managed by Cocoapods
Means I would like to keep it cleanly separate between the host iOS project and the Flutter project, except for the Cocoapod pod usage.
I created a podspec just for the via Pigeon generated iOS files. My first attempt was to try to find a way to also include the Pigeon generated files into the Pod that Flutter generates, but couldn't find any.
So this separate podspec is installed just like any other development pod into the host iOS project. Because Cocoapods dependencies are handled via frameworks, the Pod with the generated Pigeon files is also now a framework dependency inside the host iOS project. 
But because the Pigeon generated files are in a different framework target than the host iOS project, the classes and protocols will need to be public or open in order to be "exposed" to outside the framework.

**Comment by stuartmorgan** [comment]
> I created a podspec just for the via Pigeon generated iOS files. My first attempt was to try to find a way to also include the Pigeon generated files into the Pod that Flutter generates, but couldn't find any.
> So this separate podspec is installed just like any other development pod into the host iOS project. Because Cocoapods dependencies are handled via frameworks, the Pod with the generated Pigeon files is also now a framework dependency inside the host iOS project.

How are you guaranteeing usage of compatible versions of these two different pods? The communication protocol Pigeon uses is an internal implementation detail, subject to change at any time (and not considered a breaking change). That means that if a project uses Swift files and Dart files that were not generated with *exactly* the same version of Pigeon, arbitrary issues, including crashes, may result.

> Means I would like to keep it cleanly separate between the host iOS project and the Flutter project, except for the Cocoapod pod usage.

If the goal is a clean separation layer, then our recommendation would be wrap your use of Pigeon in an API you control, so that clients of the pod are not subject to changes in implementation details of Pigeon-generated code. Is there a reason that wouldn't work with your use case?

**Comment by kmaschke85** [comment]
> How are you guaranteeing usage of compatible versions of these two different pods? 
The Flutter pod and the "Pigeon generated code pod" are both in the same project. They will always be in sync (expect of course when not letting pigeon re-generate code after an update, but that can always happen).

> If the goal is a clean separation layer, then our recommendation would be wrap your use of Pigeon in an API you control, [...]

Adding an additional layer would work in my case.

I just tested the Objective C code generation and the Objective C headers are in fact public, which is different from the generated Swift code. So there is a difference between Objective C and Swift generated code though. Maybe behavior should be the same?

If adding public access modifiers to the Swift code is not an option, then I would have two options:
1. use the generated Objective C code
2. add a wrapper layer to the Swift framework to expose it publicly

**Comment by stuartmorgan** [comment]
> I just tested the Objective C code generation and the Objective C headers are in fact public, which is different from the generated Swift code. So there is a difference between Objective C and Swift generated code though. Maybe behavior should be the same?

What do you mean specifically when you say the Objective-C headers are public? Access control isn't a concept in Objective-C.

**Comment by kmaschke85** [comment]
I can just easily add the generated *.h files to the Cocoapods header definitions (s.public_header_files = '*.h') which exposes the Objective C headers to be available outside of the framework.
This doesn't work for Swift, since the Swift classes would just need to be public or open to be available outside the framework.

**Comment by stuartmorgan** [comment]
> I can just easily add the generated _.h files to the Cocoapods header definitions (s.public_header_files = '_.h') which exposes the Objective C headers to be available outside of the framework.

This is because there's no way to make that *not* be true in Objective-C; the only way to make all languages consistent here would be a least-common-denominator approach that never used features from newer languages, which is a non-goal for Pigeon.

Closing since creating a wrapper is our recommended solution; we deliberately don't want to encourage use of Pigeon-generated code in public API surfaces.
