### ISSUE TITLE
AndroidView touch event issue

### ISSUE THREAD

**Issue by lucers** [flutter/flutter#150655]
When I use AndroidView in my Flutter project. On the android module, I try to do something when my finger touches, but ACTION_DOWN has no event trigger when my finger is pressed until I move or lift my finger.

**Comment by lucers** [comment]
![image](https://github.com/flutter/flutter/assets/20353542/df4b6093-884b-40cb-84dd-b169ff5d973f)

**Comment by huycozy** [comment]
Hi @lucers 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml), I would recommend you open a new issue and fill all information with this template). 

Closing this issue, since there is not enough information for further actions. Once you update the issue with more information, please write in the comments and I will re-open this. Thanks!

**Comment by lucers** [comment]
Thanks, I found a solution. When I configure PlatformView, I use EagerGestureRecognizer in the gesture processing, and Native handles the gesture events completely, which can solve my problem.
