### ISSUE TITLE
iOS Flutter release app crashing intermittently.

### ISSUE THREAD

**Issue by chtnsngh** [flutter/flutter#150718]
### Steps to reproduce

1. On release iOS build, app is crashing sometimes intermittently.
2. Flutter version used is 3.10.6.
3. Crash reported through testflight.
4. Stack trace pointing to an issue in Flutter framework.

<img width="1308" alt="Screenshot 2024-06-25 at 12 40 32 AM" src="https://github.com/flutter/flutter/assets/70207147/f48bce56-79bd-4244-bd87-968d53ad8936">

### Expected results

 App should not crash

### Actual results

On release iOS build, app is crashing sometimes intermittently.

### Code sample

/* Sample Flutter app */

### Screenshots or Video

/* Sample Flutter app */

### Logs

/* Sample Flutter app */

### Flutter Doctor output

Flutter version - 3.10.6

**Comment by danagbemava-nc** [comment]
Hi @chtnsngh, you are using an older version of flutter. 

Kindly upgrade to the latest version of flutter stable to see if you still experience this issue. If you do, please provide the update output of `flutter doctor -v` along with the updated crash log so that we can properly investigate this issue. 

Thank you
