### ISSUE TITLE
[image_picker] cannot select images downloaded by Safari on iOS

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#150890]
### Use case

`image_picker` cannot see images downloaded by Safari or Chrome on iOS.

I tried these entitlements

```xml
        <key>com.apple.security.files.downloads.read-write</key>
        <true/>
        <key>com.apple.security.files.user-selected.read-only</key>
        <true/>
```

and these permissions

```
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Allow access to photo library, for posting photos</string>
	<key>NSDownloadsFolderUsageDescription</key>
	<string>Allow access to downloads folder, for posting downloaded photos</string>
```

but to no avail.

### Proposal

The Downloads folder should be supported by `image_picker`.

The `downloadsfolder` package may be a good starting point, by the looks of it:

https://pub.dev/packages/downloadsfolder

I understand that apps like Chrome have to make their downloads folder available to the `Files` app via a permission and an entitlement. I don't see a way to use `Files` to pick a file from a Flutter app though -- and also `Files` does not show the Safari download folder.

(I'm not an iOS guy, so sorry if this is a n00b question, but how are downloads even usable in Safari if they can't be seen even in `Files`?)

Is it possible at a minimum for `image_picker` to do something like what `Files` does, to pick a photo from the Chrome download folder?

**Comment by lukehutch** [comment]
For reference, I found that the `flutter_document_picker` package can pick files from the Safari downloads folder (but not the Chrome downloads folder).

**Comment by danagbemava-nc** [comment]
Hi @lukehutch, I think either `file_selector` or `file_picker` with a filter for only images might be best suited for this case. From what I understand this is a limitation of the native `PHPickerViewController`/`UIImagePickerController` which the plugin wraps around.

**Comment by lukehutch** [comment]
@danagbemava-nc `file_picker` doesn't find anything other than the camera roll images. `flutter_document_picker` can find images downloaded by Safari, but not images downloaded by Chrome (even though the Files app can find images downloaded by Chrome). I hadn't tried `file_selector` previously, but I can confirm that it works exactly the same as `flutter_document_picker`.

What I don't get is why `image_picker` doesn't strive to find images using all available mechanisms. It's a pain as an app author to have to use multiple different libraries to find images. Currently I have to use `image_picker` to pick photos from the camera or gallery, `file_picker` to pick from Google Photos on Android, and `flutter_document_picker` or `file_selector` to pick from Safari downloads on iOS. This also means I have to offer the user multiple buttons, asking them where they want to pick files from. It would be much better to have all this integrated into `image_picker`.

**Comment by stuartmorgan** [comment]
Just as on Android, the UI you see in `image_picker` and the behavior of that UI are entirely OS-provided; as noted above if that UI can't see certain images thre, that's a limitation of the OS-provided control. Bug reports or feature requests about that UI control would need to be directed to Apple, as the Flutter team cannot control it.

> What I don't get is why `image_picker` doesn't strive to find images using all available mechanisms.

Because the goal of `image_picker` is to provide Flutter applications easy access to the standard OS mechanism of selecting images, so anything else is out of scope. Just as if someone writing a non-Flutter app wanted different behavior than `PHPickerViewController`/`UIImagePickerController` they would need to write their own image selection logic and UI, someone who wants different behavior in a Flutter app would need to do the same.

> Currently I have to use `image_picker` to pick photos from the camera or gallery, `file_picker` to pick from Google Photos on Android, and `flutter_document_picker` or `file_selector` to pick from Safari downloads on iOS. This also means I have to offer the user multiple buttons, asking them where they want to pick files from. It would be much better to have all this integrated into `image_picker`.

Anyone in the community is welcome to make a wrapper plugin that offers users multiple buttons, each of which launches a different plugin, but that is not something we will be doing in `image_picker`. If you mean that `image_picker` should provide one UI that has all the functionality of the iOS image picker and the iOS document picker combined into one, even if we considered building an entire custom UI from scratch in scope for the plugin, it is impossible due to the restrictions iOS imposes on access outside of the app sandbox; you would need to file a feature request with Apple for such a control.
