### ISSUE TITLE
Provide a command line arg in engine tool to tell RBE to do a local build

### ISSUE THREAD

**Issue by flar** [flutter/flutter#150877]
The engine tool (et) already has a way to configure the build scripts for local builds, but sometimes you have a small change to compile and you just want that specific incremental build to be done locally. RBE has a flag for doing that, but it requires knowing the environment variable that they use for that. The engine tool could make that process more user friendly.

**Comment by matanlurey** [comment]
Tiny quality of life feature that will help the engine team adopt using `et` more often.

**Comment by johnmccutchan** [comment]
Unless I'm misunderstanding this feature request, I believe the `--rbe` flag already allows you to disable rbe for one off builds by passing `--no-rbe` to `et run` or `et build`.

**Comment by johnmccutchan** [comment]
or do we want to use `rbe` as a cache and only build locally?

**Comment by zanderso** [comment]
Passing a different `--rbe`/`--no-rbe` will modify the GN configuration, which will invalidate any part of the build that's already been done, triggering a full rebuild.

What this issue is about is changing the RBE "exec strategy". The idea would be that the GN configuration would stay the same, and not invalidate anything that's already been built. So for example, you can do a full build using RBE with remote workers, and then later do an incremental build after making some local changes that only runs locally.

The options to do this exists in the build runner library, but they haven't been plumbed up to `et` yet. Here are some pointers.

`et` instantiates `BuildRunner`s [here](https://github.com/flutter/engine/blob/main/tools/engine_tool/lib/src/build_utils.dart#L137).

The `BuildRunner` constructor takes an `RbeConfig` [here](https://github.com/flutter/engine/blob/main/tools/pkg/engine_build_configs/lib/src/build_config_runner.dart#L275).

`RbeConfig` is defined a bit further up in that file [here](https://github.com/flutter/engine/blob/main/tools/pkg/engine_build_configs/lib/src/build_config_runner.dart#L152).

So the thing to do for this is to define new `et` command line flags for `build`, `run`, etc. that result in an `RbeConfig` being passed to the `BuildRunner` constructors in `build_utils.dart`.

**Comment by flar** [comment]
Another use case is that you have a fully built engine repo and then move to a work location that has spotty network connectivity (like public wifi) and want to do some minor work. You can't do any incremental builds while out of decent wifi connectivity so you must choose to either reconfigure for non-rbe or just not doing any build/testing until you get back to "civilization"...

**Comment by johnmccutchan** [comment]
https://github.com/flutter/engine/pull/55635

**Comment by matanlurey** [comment]
Yes, this is intentional/required, as we'd like to use a remote cache (if able).

One thing this doesn't address is Jim's request of:

> Another use case is that you have a fully built engine repo and then move to a work location that has spotty network connectivity (like public wifi) and want to do some minor work. You can't do any incremental rbe builds while out of decent wifi connectivity (they are slower than local) so you must choose to either reconfigure for non-rbe or just not doing any build/testing until you get back to "civilization"...

... as RBE cache will still be used.

We could have a hypothetical `--build-strategy=local` and `--build-strategy=local-with-rbe-cache`, but I am not sure it is worth the complexity.

**Comment by matanlurey** [comment]
Asking @johnmccutchan whether this is WAI before closing.

**Comment by matanlurey** [comment]
I ended up doing this on accident in another refactor.

We will now have `--build-strategy=local`, which _only_ uses RBE Builds.

**Comment by flar** [comment]
> We will now have `--build-strategy=local`, which _only_ uses RBE Builds.

Huh? Isn't that backwards? `local` to me implies no RBE.

**Comment by matanlurey** [comment]
Mistype, I meant to write _never_ not _only_.
