### ISSUE TITLE
Move `ScrollablePositionedList` to flutter/packages

### ISSUE THREAD

**Issue by yakagami** [flutter/flutter#150963]
[ScrollablePositionedList](https://pub.dev/packages/scrollable_positioned_list) is a package that lets developers create a scrollable list that can jump to arbitrary indexes of it's children. It was created to solve this issue: https://github.com/flutter/flutter/issues/12319 however it is not currently maintained. There are currently 28 open PRs for ScrollablePositionedList (out of 43 total in flutter.widgets). Of these, 7 are about exposing `ScrollablePositionedList`s `ScrollController` (or its `ScrollPosition`). Many of the others are nits or outdated, for example migrating to null safety(which has simce been completed im a different PR). I included a table bellow of open PRs.

<details>
<summary>open PRs</summary>

|PR|package                 |solvedByExposingScrollController|
|----|------------------------|--------------------------------|
|535 |ScrollablePositionedList|TRUE                            |
|532 |ScrollablePositionedList|FALSE                           |
|523 |other                   |FALSE                           |
|521 |ScrollablePositionedList|FALSE                           |
|512 |ScrollablePositionedList|FALSE                           |
|506 |ScrollablePositionedList|TRUE                            |
|496 |ScrollablePositionedList|FALSE                           |
|487 |ScrollablePositionedList|TRUE                            |
|486 |ScrollablePositionedList|FALSE                           |
|484 |ScrollablePositionedList|FALSE                           |
|483 |ScrollablePositionedList|TRUE                            |
|482 |ScrollablePositionedList|FALSE                           |
|476 |ScrollablePositionedList|FALSE                           |
|459 |ScrollablePositionedList|FALSE                           |
|453 |ScrollablePositionedList|FALSE                           |
|451 |other                   |FALSE                           |
|445 |ScrollablePositionedList|TRUE                            |
|431 |other                   |FALSE                           |
|427 |other                   |FALSE                           |
|426 |ScrollablePositionedList|FALSE                           |
|421 |ScrollablePositionedList|FALSE                           |
|399 |ScrollablePositionedList|FALSE                           |
|398 |other                   |FALSE                           |
|396 |ScrollablePositionedList|FALSE                           |
|393 |other                   |FALSE                           |
|389 |ScrollablePositionedList|FALSE                           |
|388 |ScrollablePositionedList|TRUE                            |
|370 |other                   |FALSE                           |
|346 |ScrollablePositionedList|FALSE                           |
|335 |other                   |FALSE                           |
|319 |ScrollablePositionedList|FALSE                           |
|317 |ScrollablePositionedList|FALSE                           |
|316 |other                   |FALSE                           |
|306 |other                   |FALSE                           |
|305 |ScrollablePositionedList|TRUE                            |
|304 |other                   |FALSE                           |
|277 |ScrollablePositionedList|FALSE                           |
|265 |ScrollablePositionedList|FALSE                           |
|260 |other                   |FALSE                           |
|256 |other                   |FALSE                           |
|245 |other                   |FALSE                           |
|180 |ScrollablePositionedList|FALSE                           |
|176 |other                   |FALSE                           |

</details>

My proposal is that we move/copy this package to flutter/packages. This package is basically the official solution to the jumoToIndex problem not just because it is from Google, but because it is the one mentioned in the jumpToIndex issue and the first result for "flutter jump to index" on Google search (via the top answer at https://stackoverflow.com/questions/54039684/flutter-listview-scroll-to-index-not-available). The solution itself is good and works well but it is missing one or two features, the main one being lack of developer control over the `ScrollPoisition` (more detail in https://github.com/google/flutter.widgets/pull/535). Since the package is essentially feature complete already, it should not be too much of a burden to add it to flutter/packages.

**Comment by stuartmorgan** [comment]
Routing to `team-framework` since while this would live in flutter/packages, this would need one or more framework folks to be the owners, so whether this is sufficiently core to warrant ongoing investment by the Flutter team, and whether this particular solution is the one we think is the right one to address that use case, is primarily a framework team question.

Some general notes from an ecosystem team standpoint:
- The current pub popularity is currently 99%, which means it's roughly in the range of 500th to 1000th in the usage ordering of all packages. In the context of my recent evaluation of packages we are maintaining, I would consider 99% right on the borderline.
- > Since the package is essentially feature complete already, it should not be too much of a burden to add it to flutter/packages.
  Every package has some ongoing, permanent maintenance cost. "Too much" is a highly subjective evaluation; if the Flutter team takes ownership of that package, that *will* come a cost in terms of other work that is not done by the Flutter team. (Some of that would fall on the identified owners, and some would fall on the ecosystem team in the context of things like roller failures, example app native code bitrot, etc.)
- There are other solutions to the problem of a relatively popular package not being as actively maintained as the community would like, most notably, one or more community members could work together to fork the package and maintain it. Both issues and Stack Overflow posts can have information added to them, so the fact that they currently point people to the existing package is resolvable.

**Comment by goderbauer** [comment]
I don't think we currently have the capacity to take this on.

**Comment by stuartmorgan** [comment]
@goderbauer Do we expect that to change in the foreseeable future? If not we should probably close this per https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#closing-issues

> it is a feature request that we are unlikely to ever address, and if we did address it, it would not be part of the core SDK (e.g. it would be in a package). (For example, anything in the [would be a good package P3](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22would+be+a+good+package%22+label%3AP3) list is a good candidate for closing without fixing.)

**Comment by goderbauer** [comment]
Sounds good.
