### ISSUE TITLE
Update espresso plugin to newest androidx dependencies 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#151188]
When updating android sample projects I discovered that we do not support the latest expresso versions with the espresso plugin. https://github.com/flutter/samples/pull/2347

**Comment by stuartmorgan** [comment]
Potentially useful info: since `espresso` should always be a dev dependency, breaking version changes should be extremely low cost (as there's no plausible risk of ecosystem lock), so if anything you need to do as part of updating is breaking, or even breaking-ish as some deps updates are on Android, feel free to just do a breaking semver version change (minor version since it's pre-1.0).

**Comment by gmackall** [comment]
This was fixed in https://github.com/flutter/packages/pull/7048, right?

**Comment by reidbaker** [comment]
@gmackall yes
