### ISSUE TITLE
`google_sign_in` needs fallback to OAuth2 if Google Play Services is not available

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#151276]
### Use case

The `google_sign_in` Flutter package fails if Google Play Services is not installed (and it cannot be installed on some devices).

There needs to be a fallback to a simple OAuth2 login when Google Play Services is not available.

### Proposal

Currently I have to guard against this in my app by removing the Sign In With Google button when Google Play Services is not available.

However, it would be much better if the user could still log in using the Web OAuth2 interface, even if all the fancy Google login machinery is not present on the device.

**Comment by stuartmorgan** [comment]
Supporting devices without Google Play Services is out of scope for this plugin. The community is welcome to make wrapper packages with fallback options, and/or, since it's a federated plugin, unendorsed OAuth2-based implementation packages for it (assuming there is sufficient alignment between the API surfaces) that can be conditionally set by clients who want that behavior.
