### ISSUE TITLE
Using vanilla javascript

### ISSUE THREAD

**Issue by aissa-bouguern** [flutter/flutter#15128]
Hi,
I just need to know if we can use vanilla javascript with this framework ? because learning Dart is a bad requirement for newcomers, i think.

**Comment by mraleph** [comment]
You might be under the impression that Dart is just a compile to JavaScript language, like for example CoffeeScript or TypeScript. This is not the case. Flutter is using _native_ Dart implementation, that runs Dart directly on the hardware - without any compilation to JavaScript. This is what allows Flutter to deliver high fidelity development experience and also provide fast native binaries when you deploy your application.

See FAQ entry ["Why Flutter choose Dart"](https://flutter.io/faq/#why-did-flutter-choose-to-use-dart) and this [blog post](https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf) for more background.

So the short answer to your question is *no* - you can't use vanilla JavaScript with Flutter because there is no JavaScript involved anywhere in the Flutter stack.

Give Dart a try - the UX studies show that it is very easy to pick up no matter which programming language background you are coming from.

**Comment by aissa-bouguern** [comment]
I got you,
Thanks for your fast feedback :)

**Comment by sopedro** [comment]
Learn Dart. It's easy. If you are confortable with other languages in some hours you are ready to go in dart.
