### ISSUE TITLE
[MACOS ]: LateError (LateInitializationError: Local 'macBundleId' has already been initialized.)

### ISSUE THREAD

**Issue by moshOntong-IT** [flutter/flutter#151335]
### Steps to reproduce

1. Flutter run mac os
2. Then I got that error

### Expected results

It must run through all my code

### Actual results

It stuck on that error
<img width="1927" alt="Screenshot 2024-07-05 at 5 06 51 PM" src="https://github.com/flutter/flutter/assets/57244338/6e9ff18f-e42b-43b1-951c-2e081117fbe5">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@moshOntong-IT 
Please read about `LateInitializationError` https://api.dart.dev/stable/2.7.2/dart-core/LateInitializationError-class.html to see why and how it is triggered. 
It is likely in your case that it is throwing due to code implementation error or any third party package. I suggest you to raise this in support channels like Stackoverflow.
Closing from here.
