### ISSUE TITLE
My flutter apk's size increases when created on windows

### ISSUE THREAD

**Issue by thomaspaulitinker** [flutter/flutter#151642]
Hi,
I am having an issue when running this command

`flutter build apk`

When I create my release app's apk on macos using this command, the output apk is of around 79.6 mb.
But when I try to generate apk on windows, the apk's size increases to 121 mb.

I have update the build.gradle to only include my release config. I have tried doing flutter clean and build the apk again but it still generates the apk with size 121 mb.

**Comment by huycozy** [comment]
Hi @thomaspaulitinker 
This reminds me https://github.com/flutter/flutter/issues/137990 but that issue is about building app on different machines. 

I checked this issue on a newly created Flutter project but I see the output APKs size is equivalent:
- Build from macOS machine: `✓ Built build/app/outputs/flutter-apk/app-release.apk (18.5MB)`
- Build from Windows machine: `√ Built build\app\outputs\flutter-apk\app-release.apk (17.6MB)`

Can you also confirm this on a newly created Flutter project? 

If it only happens on your project, it could be related to project configuration (on Gradle, AGP version), dependencies you use, etc. You should narrow it down until you find the possible factors that can cause this.

And perhaps the different Java/JDK versions on machines as well so you should check them and make sure all settings are similar on machines.

**Comment by thomaspaulitinker** [comment]
Hi @huycozy ,
I tried using the solutions you suggested. Setup a new windows machine and did all the setup as an exact replica to my mac os machine. Didn't work.

I then unzipped the files and found the assets directory is present within the apk twice thus increasing my app size on windows. Just update the path separator to '/' rather than '\' in windows and the size issue got resolved.

**Comment by huycozy** [comment]
>I then unzipped the files and found the assets directory is present within the apk twice thus increasing my app size on windows. Just update the path separator to '/' rather than '' in windows and the size issue got resolved.

It seems to need a specific case with assets. Can you share a reproduction example in detail? And please be more specific on your solution that might be helpful as well (which path are you referring to?).
