### ISSUE TITLE
Update CLI args for `--web-renderer` to explain new default and clarify "skwasm"

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#151786]
- Skwasm is not experimental (any longer)
- It's the only renderer used when compiled to wasm

We should explain this!

```
--web-renderer          The renderer implementation to use when building for the web.

   [auto]            Use the HTML renderer on mobile devices, and CanvasKit on desktop devices.
   [canvaskit]       Always use the CanvasKit renderer. This renderer uses WebGL and WebAssembly to render graphics.
   [html]            Always use the HTML renderer. This renderer uses a combination of HTML, CSS, SVG, 2D Canvas, and WebGL.
   [skwasm]          Always use the experimental skwasm renderer.
```

**Comment by yjbanov** [comment]
We should also remove `html` and `auto` from the docs. They can stay hidden for some time to give people enough time to migrate.

**Comment by yjbanov** [comment]
Based on a discussion at the triage we concluded that we should just hide this option entirely. The reason is because the defaults already pick the correct compiler+renderer combo, and any other combination is unsupported, is deprecated, or just doesn't work:

- `flutter build web` builds in CanvasKit mode with dart2js, which is the new default and fully supported mode. There's no need to also add `--web-renderer=canvaskit`.
- `flutter build web --wasm` builds in Skwasm mode with dart2wasm, which is also a fully supported mode. There's no need to also add `--web-renderer=skwasm`.

Picking `html` or `auto` is no longer supported for new apps, and existing apps are already aware of the `--web-renderer` option and choose accordingly. They don't need the docs.

Picking `canvaskit` in dart2wasm mode is not supported. The tool will _try_ to build it. We use it for ad hoc debugging sometimes. But there are no guarantees that it will work. We will not accept issues that affect this mode alone.

Picking `skwasm` in dart2js mode simply doesn't work.
