### ISSUE TITLE
It most likely is similar to https://github.com/flutter/flutter/issues/115253, so please follow-up in that issue for further updates.

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#151749]
It most likely is similar to https://github.com/flutter/flutter/issues/115253, so please follow-up in that issue for further updates.
Closing this as a duplicate.

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/131161#issuecomment-1651019131_

-------------------------------
I think the two cases you mentioned are not the same problem, the crash stacks are different。

in case https://github.com/flutter/flutter/issues/131161 , crash stack is : 
<img width="548" alt="image" src="https://github.com/user-attachments/assets/0cc4eb8d-0e30-45f8-88ca-6f2acda208d0">

which is similar as case in case https://github.com/flutter/flutter/issues/122957, 
[chinmaygarde](https://github.com/chinmaygarde) said it has been fixed (Bisected this to https://github.com/flutter/engine/commit/97e246cb5d78f037f3e585261dc4b5a6045a02f2
This may have been fixed by https://dart.googlesource.com/sdk/+/e3e355e16a8b67ba6a1d7a83f837e8e69cf71534)

but we found the crash was also exist in flutter 3.7.10

            
but in case https://github.com/flutter/flutter/issues/115253， the crash stack is: 

<img width="800" alt="image" src="https://github.com/user-attachments/assets/f8113ef2-294e-44dd-8429-fde4a2f66a8e">

**Comment by darshankawar** [comment]
@zjrwdl 
Please don't use comments from other issues to file a new issue. Please use issue template, fill out requested details in proper format so that we can address it properly.

From the details you provided, it seems the issues linked are not similar, but it is not a recent issue, filed last year. If you are facing same issue / crash using latest stable, please comment in that issue or open a new one as suggested earlier.
Closing for now.

**Comment by darshankawar** [comment]
> but we found the crash was also exist in flutter 3.7.10

This is also old version. Please check if the same occurs in latest stable, then we can make it actionable.
