### ISSUE TITLE
Keyboard pushing screen

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [flutter/flutter#151950]
### Steps to reproduce

1. In scaffold for body add Stack
2. For the first child of stack add image to bottom of screen
3. For the second child add some textfields, so that when keyboard appears, it should not fit

### Expected results

Only first child(in stack) with textfield should move to up, not first child(which is just background image)

### Actual results

Textfield moves both child to up. See image below

<img width="373" alt="image" src="https://github.com/user-attachments/assets/607fac5a-2b9c-403f-848e-9b3bf734f760">

And this image below is showing when keyboard not opened

<img width="370" alt="image" src="https://github.com/user-attachments/assets/685bbf08-84cb-4d6a-a02a-340b9cfaaef3">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@tologonkudaiberdiuulu 
Without looking at the code, we can't address the issue. This case is often reported and also asked in support channels like StackOverflow where you should take a look first to see if this is occuring due to code implementation or missing any.
Check below for example:

https://github.com/flutter/flutter/issues/53489
https://stackoverflow.com/questions/49840074/keyboard-pushes-the-content-up-resizes-the-screen
