### ISSUE TITLE
In the iOS version, the method of buying an item does not work

### ISSUE THREAD

**Issue by AmourSonFromEast** [flutter/flutter#151953]
### Use case

On an android device, everything works perfectly, meanwhile, on the IOS version, after purchasing an item in the terminal, it gives this error "Thread 1: "Cannot finish a purchasing transaction" and the application freezes, after restarting the application, it is not possible to buy this item, and you can not touch it.

### Proposal

so that customers can buy my items

**Comment by darshankawar** [comment]
@AmourSonFromEast 
The issue template you selected to file the issue isn't correct, as it looks like you are facing an issue and not proposing a change.
Looking at the description you provided, it seems to be related to `in_app_purchase` plugin on ios and getting error `Cannot finish a purchasing transaction`. In order to address issue correctly, please provide complete error log in properly formatted text along with `flutter doctor -v`, minimal reproducible code sample that triggers the said error.
