### ISSUE TITLE
FileSystemException: FileSystemException: Exists failed, path = '/Users/geezer./Applications/Visual Studio Code.app/Contents' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by archer-ff** [flutter/flutter#15198]
## Steps to Reproduce

flutter --no-color run --machine --device-id=emulator-5554 lib/main.dart

## Logs
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

FileSystemException: FileSystemException: Exists failed, path = '/Users/geezer./Applications/Visual Studio Code.app/Contents' (OS Error: Permission denied, errno = 13)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:41)
#2      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:159)
#3      VsCode._installedMacOS (package:flutter_tools/src/vscode/vscode.dart:107)
#4      VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:74)
#5      VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:47)
#7      Doctor.workflows (package:flutter_tools/src/doctor.dart:60)
#8      Doctor.canLaunchAnything (package:flutter_tools/src/doctor.dart:156)
#9      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:303)
<asynchronous suspension>
#10     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:219)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:269)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#28     main (file:///Users/geezer./computer-language/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.1.8, on Mac OS X 10.13.3 17D47, locale en-GB)
    • Flutter version 0.1.8 at /Users/geezer./computer-language/flutter
    • Framework revision 6993b203c0 (6 days ago), 2018-02-27 17:39:49 -0800
    • Engine revision e133da723c
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/geezer./Library/Android/sdk
    • Android NDK at /Users/geezer./Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/geezer./Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

• No issues found!
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
cc @DanTup @tvolkert

**Comment by DanTup** [comment]
@SmileArcher Do you know why you might not have permission to `/Users/geezer./Applications/Visual Studio Code.app/Contents`?

@Hixie @tvolkert What's the most sensible thing to do here? I can wrap this in a `try`/`catch` and just pretend the folder didn't exist (eg. don't list VS Code), but I'm not sure if we should show an error somewhere? I tried using `printTrace` inside here, but it didn't seem to output anything even with `--verbose`?

Btw, it seems a bit weird that we're checking for the folders here in `canLaunchAnything` but it's because the validators are kinda "dynamic". A user can have multiple VS Code instances (stable, insiders, stable 64bit, insiders 64bit) so we create a validator for each. `canLaunchAnything` gets a list of all validators, so it's executing the checks for which are installed. I'm not sure if there's something better we could do?

**Comment by tvolkert** [comment]
If you use [`FileSystem.typeSync()`](https://pub.dartlang.org/documentation/file/latest/file/FileSystem/typeSync.html) instead of `existsSync()`, you wouldn't need the `try/catch`.

> I'm not sure if there's something better we could do?

If we tried to catch errors during validator instantiation and skipped validators that threw, I'm afraid it would yield harder to find bugs down the road.  Better to just more resilient to OS issues IMO.

**Comment by DanTup** [comment]
Ah, good call. I've used `isDirectory` which just a wrapper over that checking for directory.

I've opened https://github.com/flutter/flutter/pull/18167 which seems to work find in my testing, with the caveat mentioned on the PR. I'm happy to revisit this logic if it turns out that this is a common issue, but I don't expect it's common for a user not to have access to their own Apps folder :/
