### ISSUE TITLE
[User] Flutter apps causing "critical" restarts on RMX3231 device

### ISSUE THREAD

**Issue by idontveapc** [flutter/flutter#152020]
### Steps to reproduce

The two apps [1](https://play.google.com/store/apps/details?id=com.and96.aggregator_news) [2](https://play.google.com/store/apps/details?id=net.yumnumm.eqmonitor) that...
1st freeze then, screen gets unresponsive and won't turn off (just dims), at any time from 2mins to 5mins screen turns off then, device restarts. [1] app did it twice (while using) and [2] app once.

### Expected results

What's is the reason?

### Actual results

<p> </p>

### Code sample

<details open><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

```

</details>

**Comment by huycozy** [comment]
Hi @idontveapc 
The goal of this Github repo is not to assist in personal applications or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please try to provide all information indicated in the bug template so that we can address the issue properly.

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well. 

Closing this issue, since no provided information can bring this forward.
