### ISSUE TITLE
Embed Flutter UI in existing Xamarin.iOS and Xamarin.Android apps

### ISSUE THREAD

**Issue by VincentH-Net** [flutter/flutter#15200]
For Xamarin teams that need better productivity & more design freedom in building iOS and Android UI than is possible with Xamarin Forms, while minimizing dev skills impact.
(created as separate issue from #14821 as suggested by @passsy and @timsneath)

**Why combine competitors? Can't you just pick one?**
Xamarin Live Player is a tool similar to Flutter's hot reload feature, only it's not so hot: it is created and maintained as an afterthought, not as the core development flow, by a few heroes. Alas, the tool improves very slowly, has limitations on what it can run, and is way slower than hot reload (and will never have UI state preservation).

Xamarin Forms allows sharing UI across platforms, in a different approach to Flutter's. Alas, Forms has longstanding bugs, requires time consuming platform specific tweaks, and severely limits design, especially for navigation.

However, Xamarin Forms is a layer on top of Xamarin.Android and Xamarin.iOS, which are solid, perform well and have excellent support for all the latest native device features. The .NET (Core) support and the mature NuGet ecosystem are very attractive for enterprises with .NET skills that build apps, especially if the app backend is also .NET based.

This allows teams to share .NET skills, libraries and code across backend and (often enterprise) apps; e.g. in a [BFF API contract with design data](http://vincenth.net/blog/archive/2016/07/13/building-bff-backend-for-frontend-apis-for-xamarin-mobile-apps.aspx).

For these teams, a compelling alternative to Xamarin Forms could be to embed Flutter UI in Xamarin.

**Ok, so which source goes where?**
Flutter would be used for the UI layer (screens including image resources + navigation); Xamarin for logic, models and services, including platform services for push, sensors etc. This way the strongest points of Flutter and Xamarin are combined.

**Possible approach**
Use Flutter platform channels, Xamarin bindings and .NET embedding.

**Flutter in Xamarin**
Flutter platform channels are available as a native iOS/Android component and Xamarin can interop with such components  through Xamarin bindings.

We would need a generic 2-way data-binding channel (supporting .NET INotifyPropertyChanged, INotifyCollectionChanged and ICommand) to connect .NET viewmodels with Flutter widgets.

The complete app build & publishing would be with the Xamarin toolchain, so Microsoft cloud services like  [App Center](https://appcenter.ms) and [VSTS](https://www.visualstudio.com/team-services/) can be leveraged.

**Xamarin in Flutter**
Xamarin code can be wrapped as native iOS/Android components with .NET Embedding, and Flutter can interop with such components (again with a platform channel? not sure).

This could be used to embed the .NET coded API contract + design data in Flutter, so the Flutter UI can be developed completely in the Flutter toolchain with high productivity. 

Ideally, we would get intellisense in VS Code Flutter when accessing the embedded design data, so we can code type-safe 'data binding' in Flutter widgets.

**Comment by VincentH-Net** [comment]
At this point the above is a thought experiment; it may prove too involved to realize. I would love feedback and alternatives to see it this could fly,

Also, I have currently no idea what the development experience for the Flutter side of 'data binding' could be like.

In C# (I dont use XAML, why would you want to hand-code an object serialization format? ), this looks like:

`new Label {  }.Bind(nameof(Product.Title)),`
`new Label {  }.Bind(nameof(Product.Description)),`
`...`

You get intellisense when entering above binding names.
(How) can something equivalent be achieved in Flutter in VS Code? When the names are in embedded .NET code?

**Comment by bobzhou80** [comment]
WeChatSight188.mp4（This is a demo video）
https://github.com/flutter/flutter/files/1892512/flutter_image_test.zip（This is a demo ，It needs to run in ios real machine to reproduce this problem）
I added flutter to an existing native application and started the new FlutterViewController the second time. The image was displayed incorrectly in Flutter ，
https://files.gitter.im/flutter/flutter/yR2i/1523967103260.jpg (This is a screenshot showing that the picture is incorrect)
I want to add flutter to an existing native application , but this problem can't let me do it，Because in ios, multiple flutterViewControllers cannot be started, even one flutterViewController cannot be started multiple times，But there is no problem in android

**Comment by touseefbsb** [comment]
I love this idea because xamarin and VS sure provide very strong tooling, and .NET productivity as a whole is best out there for any developmental stack, xamarin forms is slow and performance is not good enough, but flutter is performant, so I agree that we should combine best of both world where we can use UI layer of flutter so it can be common for all devices and use xamarin.android and xamarin.ios as a backend layer, and those 2 backend projects can even share business logic code with a .NET standard library.

**Comment by prasadsunny1** [comment]
i'd love to work in this environment.
Because just to see ui changes, I have to wait for 4 minutes long build process

**Comment by bernardvandaele** [comment]
+1 for this

**Comment by zoechi** [comment]
@bernardvandaele pleas upvote the initial comment instead of +1 comments.
If you want to get notified use the [Subscribe] button on the right.
+1 comments are spam for other subscribers and pointless. Upvotes increase priority.

**Comment by bernardvandaele** [comment]
sorry for that ! newbie here I will delete my spam and this

**Comment by jcmm33** [comment]
FYI, I have gone through the exercise of getting Flutter working within .Net applications. I was successful in doing this but have since updated flutter on my machine and it stopped working again so I'm going to have to do it again, perhaps I'll write the instructions down this time and if it makes sense try and knock up a nuget package for others. 

Currently it operates like Flutter currently does in the existing host native applications i.e. as a view / controller/fragment/activity, you can't directly reference the individual flutter widgets, but you can host flutter solutions and use hot refresh to see UI updates occur in the Xamarin application.  I have also written some demo code which given C# interfaces / classes constructs the automatic code to marshall data and calls automatically between Flutter & .NET. Unfortunately all of this has to be async given how flutter currently works.

**Comment by benoitjadinon** [comment]
> FYI, I have gone through the exercise of getting Flutter working within .Net applications. I was successful in doing this but have since updated flutter on my machine and it stopped working again so I'm going to have to do it again, perhaps I'll write the instructions down this time and if it makes sense try and knock up a nuget package for others.

@jcmm33 do you mind publishing your poc to github ? thanks

**Comment by jcmm33** [comment]
@benoitjadinon I'm currently going through the process of creating a nuget package for the android side of things, everything going great and just about to publish it but now the flutter environment for some unknown reason is producing invalid aar files, looking at this currently and hopefully won't be too long.

**Comment by benoitjadinon** [comment]
sry I didn't see you only wrote this yesterday. 
omg that could be so great for not throwing old xam projects to the thrash ;)

**Comment by VistianOpenSource** [comment]
@benoitjadinon I’ve published an experimental nuget package Vistian.Flutter.Bindings allowing for the embedding of Flutter applications within Xamarin iOS & Android solutions. The nuget package is here https://www.nuget.org/packages/Vistian.Flutter.Bindings/ and the source can be found https://github.com/VistianOpenSource/Vistian.Flutter.Bindings . Currently the Android implementation is available, I’ve got to re-check the Objective-C header mappings I’d previously done for an earlier version of Flutter before making an iOS version available.

Later this week I’ll also hopefully publish another experimental package which allows for the automatic generation of code between Xamarin native applications and Flutter. This means that C# code can be available for use by the Flutter environment without any manual platform code generation; all it requires is a single [Flutter] attribute being applied to any C# interface.

**Comment by VincentH-Net** [comment]
@VistianOpenSource Interesting approach, I'll try that first (since https://github.com/adamped/xamarin.flutter is not production ready yet).

Are you by chance working on updating https://github.com/VistianOpenSource/Vistian.Flutter.Bindings to Flutter 1.0?

**Comment by AcnodeLabs** [comment]
The whole purpose of crossplatform was to use one skillset and leverage accross various devices at the cost of closer to the metal user experience. This approach is pointless as tries to amulgamate two abstractions where you are forced to learn both and a Mish mash of interfacia.

**Comment by timsneath** [comment]
I want to gently push back on that assertion, @AcnodeLabs, if you don't mind. The purpose of Flutter is _not_ "one skillset at the cost of closer to the metal UX", even though that may be the reality with many cross-platform frameworks. 

We are explicitly targeting high performance output; hence we compile directly to ARM machine code, and draw with the same hardware-accelerated Skia graphics library that Android itself uses. We don't use the platform-supplied UI libraries, but instead we draw the pixels directly ourselves.  As a result, we're not an 'abstraction' over the system-provided platform.

I don't have a strong opinion on the merits of this specific issue, just want to clarify our approach to avoid any potential confusion.

**Comment by jmagman** [comment]
Check out the new add-to-app commands.

[`flutter build ios-framework`](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode) will generate the [frameworks to embed](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/native-references#embedding-a-framework) and then bind to in an iOS app.

[`flutter build aar`](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar) will likewise [generate an aar](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar) that can be used in an Android app.

**Comment by kwintAl** [comment]
P6 sounds like it will never be done :(.
In our company, we share business logic, models and a part of view models between three platforms (Android, iOS and Windows). 
A switch to dart is currently not an option (there is currently no support for Windows and the entire application has to be rewritten), but a (partially)switch from Xamarin.Forms to Flutter would be awesome.

I think this can be done with add-to-app.
- Xamarin Android and iOS Bindings for module (aar and framework)
- Xamarin Android and iOS Bindings for referenced flutter framework (dependencies from output pom file)
- a plugin for communication purpose (C# <-> Dart)

I have a working example with Android, theoretically this should be possible with iOS, too. 

This could be an option to start, but it would be nice to get support from flutter team.

**Comment by alexshikov** [comment]
Just a pitch guys, we have been able to make Xamarin + Flutter works for both platforms iOS and Android.
We have plenty of business and network logic in Xamarin, but wanted to move all the UI to Flutter slowly.

The good news - it works :)
The bad news - I don't really have time to share the details on the implementation, because there is plenty to share.

Overall, the idea is described by @kwintAl :
- iOS and Android bindings
- build scripts to compile flutter libraries
- Flutter channels for communication

We also decided to move step by step, so right now we have only one screen implemented as Flutter and other screens are Xamarin (Native). We are targeting to replace all the screens.

**Comment by VistianOpenSource** [comment]
@alexshikov Hi, I like a few others got a rough version of Xamarin & Flutter working together a long time ago (see https://github.com/VistianOpenSource/Vistian.Flutter.Remoting and https://github.com/VistianOpenSource/Vistian.Flutter.Bindings) . At the time though getting Flutter working embedded in other apps was a moving target, literally every time a new version of Flutter was pushed, the guidance and approach to it working within other apps changed. Whilst I did some work to get the channels interfacing working automatically, I could never get myself fully convinced that it was a viable option moving forward so I never did anything else with it. I'd hoped that the work they were doing to call out to external code other than through channels was going to be a little more high level, not just C interop. 

I still think about what other options there are to better improve interop with the native environment and be able to more easily consume existing libraries and logic. One thing that does cross my mind is utilising roslyn and the C# AST to create the associated Dart code automatically. A version of this approach can already be seen taking C# and creating Lua here https://github.com/yanghuan/CSharp.lua . We've already used this approach to take C# view code and have it create the associated Lua code which is run on the mobile (e.g. we were able to utilise a modified version of CSharp lua compiler with https://github.com/VistianOpenSource/Birch/blob/master/MVU-Experiment/SampleWidget.cs and generate the associated Lua which then ran correctly within a Lua host). I contemplate whether a similar approach could be taken with C# -> Dart , or the other way around would be viable.

**Comment by kwintAl** [comment]
Hi @VistianOpenSource. 
When running "flutter build aar" the library is built against a specific flutter version. Just look in the output repo .pom file, the versions are listed there. 
So the Xamarin aar library binding should reference the specified Xamarin Flutter framework binding.
At this point it would be nice to get all this versions from Nuget, we need to create bindings for every Flutter version (release, beta and so on). This is the same approach Flutter team doing with the maven repo hosted by: https://storage.googleapis.com/download.flutter.io

https://flutter.dev/docs/development/add-to-app/android/project-setup

the next part would be to "wrap" the native classes like MethodCall to be accessible from net standard project, at this point it is possible to reuse your C# business logic.

**Comment by VistianOpenSource** [comment]
@kwintAl Hi, yeah, I've been through all of the exercise of getting it working over channels. One of the simple demos we did (https://github.com/VistianOpenSource/Vistian.Flutter.Remoting/blob/master/Xamarin/Vistian.Flutter.Remoting.Droid.Example/TestService.cs) was of an observable generating values for the users current location, with this being marshalled back over to the flutter.  

I'm personally not very keen on going down a route which introduces friction due to it not being a 'supported approach', and I would much prefer, as a starting point for an official solution, but personally I can't see it happening- on the Xamarin side of things the majority of their users are down the Xamarin forms route and looking at the 5K+ issues count on flutter i suspect they have somewhat bigger fish to fry!

**Comment by gahms** [comment]
@alexshikov you write:
> Just a pitch guys, we have been able to make Xamarin + Flutter works for both platforms iOS and Android.
> We have plenty of business and network logic in Xamarin, but wanted to move all the UI to Flutter slowly.
> 
> The good news - it works :)
> The bad news - I don't really have time to share the details on the implementation, because there is plenty to share.
> 
> Overall, the idea is described by @kwintAl :
> 
> * iOS and Android bindings
> * build scripts to compile flutter libraries
> * Flutter channels for communication
> 
> We also decided to move step by step, so right now we have only one screen implemented as Flutter and other screens are Xamarin (Native). We are targeting to replace all the screens.

If you have *any* details on how you got the iOS and Android bindings to work it would a huge help. 

So far I have tried `Objective Sharpie` and it seems to not be up for the task.

**Comment by VistianOpenSource** [comment]
@gahms When i did it, which was a pre-release version of flutter, Android was pretty easy to do. iOS was more difficult. As you said, Objective Sharpie doesn't get you there 100%, you have to do a fair bit of work to you with it. Unfortunately I can't remember exactly what the steps were, but I may be able to find the output of what I did.

**Comment by gahms** [comment]
For what it is worth, I have a working Xamarin.iOS app that shows a Flutter view as a proof of concept. There is almost no doc on what I did.

https://github.com/gahms/xamflutpoc

**Comment by Jddl** [comment]
https://www.flutnet.com/

**Comment by jonahwilliams** [comment]
We don't (or rather we never did) have the bandwith to do this. While its not an unreasonable request to have specific documentation, I don't believe the mechanism for doing add2app for Flutter into Xamarin would be any different than with a "native" iOS/Flutter App. Furthermore we lack the familiarity with Xamarin to do this work.
