### ISSUE TITLE
Extend "flutter create" command to support custom, pluggable, Flutter Starter Project Templates like Dart Stagehand.

### ISSUE THREAD

**Issue by pietergreyling** [flutter/flutter#1520]
We *really* need the equivalent of http://stagehand.pub/ for Flutter with generic widget samples at a granular, composable?, selectable?, level. An option is to extend "flutter create" command to support custom, pluggable, Flutter Starter Project templates. This will allow the community to contribute Flutter Starter Project Templates in the spirit of Dart Stagehand. 
See: [http://stagehand.pub](http://stagehand.pub) and [https://github.com/google/stagehand](https://github.com/google/stagehand).

For info, "**`flutter create`**" command: 
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart
. . .
`abstract class Template {`
. . .
`class FlutterSimpleTemplate extends Template {`
. . .

**Comment by pietergreyling** [comment]
For info, "**flutter create**" command: 
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart

**Comment by sethladd** [comment]
FWIW stagehand never got the ability to allow for 3rd party templates.

One might argue that stagehand should get 3rd party templates, and then `flutter create` could use that :)

**Comment by pietergreyling** [comment]
Yep, that also makes sense :-) Another possibility is to build granular, best practice-, widget snippet templates that could be invoked via IDE/editor (Atom) plugins using CLI.

**Comment by sethladd** [comment]
While I appreciate the intention with this issue, I'm not sure how to decompose this and make it actionable. This could be a great community project, something we could fold back into mainline Flutter if it works out. I think, right now, it's out of scope for `flutter create` to become a stagehand or yeoman. As mentioned above, I think another tool that does facilitate 3rd party plugins should be useable by Flutter. I'm going to close this issue, because it's out of scope, but if someone wants to take action by working on a tool, then please leave a comment on this issue. Thanks again for the feedback!
