### ISSUE TITLE
Cross-Scaffold Snackbar Persistence

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter#15225]
This is a feature request for client mulligan. Currently, Snackbars are shown on a Scaffold. This makes sense for implementing the FAB-moving-behavior defined in the spec, but also means that SnackBars are scoped to a single screen, and disappear when a Navigator transition happens.

We have a variety of snackbars in our app that are not screen-specific and should survive a route change (e.g. when the user switches accounts, we display a snackbar with the new login details). We can potentially work around the "trigger this particular snackbar on every screen" by wrapping our usage of Scaffold, but we'd like a way of persisting a snackbar across route changes without hiding & re-showing it.

**Comment by Hixie** [comment]
Since that's not really what Material calls a snackbar, I would recommend making yourself a new widget. You can just have it be something that puts itself into the Overlay.

If you want it to appear on screen even if the app isn't visible, you might also consider using the native Android toast APIs.

**Comment by johnfesa** [comment]
Current Material implementations for both native iOS and Android apps allow the creation of a snackbar that will persist across screen changes within a single app (I can provide references if needed). It may not be explicitly mentioned in the spec, but there's a lot of desirable, used-in-prod functionality that isn't discussed specifically in the spec.

Seems like this is a philosophical issue of how strictly-adhering the Flutter Material components should be to the spec. It's my understanding that the spec was always intended to be a set of guidelines for the design of individual apps, rather than an exhaustive list of the only allowable functionality.

**Comment by Hixie** [comment]
Flutter's current goal is to implement material features that are documented in the public documentation, but we can certainly consider other features if they are things the material team thinks should be in that documentation. You can contact me at ianh@ if you want to discuss such not-yet-public material features.

**Comment by Hixie** [comment]
I'm going to close this per the comments above. Please don't hesitate to reach out to me if you have any concerns.
