### ISSUE TITLE
Important improvements

### ISSUE THREAD

**Issue by arabnology** [flutter/flutter#152286]
### Use case

Hello, I'm a Flutter developer, and this is my sixth year using Flutter.

Most required features for any app in Flutter are found on [pub.dev](https://pub.dev), which is good sometimes but mostly bad. Why?

Most times, we struggle to find the right packages that fit our needs and are also up-to-date, which should be built-in with Flutter. For example:

> Permissions
> Camera
> Contacts
> App as bubble
> Audio recording
> etc.

All these features should be built into Flutter because they are essential for any app. Why should we struggle with package developers and beg them to update their packages? For instance, managing contacts—there are no new packages available, and existing ones are outdated and unreliable.

Also, every time a new Flutter version is released, many of us struggle with packages that stop working. We end up having to plead with package developers to update their packages or modify them ourselves.

The only solution for now is to create our own packages and develop them natively, which is bad because most of us chose Flutter for its cross-platform capability and because it made our lives easier for app development.

If the Flutter team added paid packages, ensuring they are continuously updated and work flawlessly without delays for our projects—instead of waiting for package developers to update it or modifying packages ourselves—it would be great and much better for most of us.

Thank you.

### Proposal

This has to be provided by Flutter directly.

**Comment by danagbemava-nc** [comment]
> All these features should be built into Flutter because they are essential for any app.

This is not entirely accurate. Even the native development frameworks do not include all these features because they should be opt-in. The libraries are available to be used when they are needed, which is what flutter does. 

> For instance, managing contacts—there are no new packages available, and existing ones are outdated and unreliable.

There seems to be one that is still being updated. See https://pub.dev/packages/flutter_contacts

> Also, every time a new Flutter version is released, many of us struggle with packages that stop working. We end up having to plead with package developers to update their packages or modify them ourselves.

This is not an issue specific to flutter. This is the nature of software development in general. There will always be updates that break existing implementations if packages are not kept up to date. 

Moreover, the flutter team maintaining everything within the framework would take up too much engineering effort and time which would affect work that needs to be done in other areas. 

All in all, this is not a feasible proposal as such I'll be closing it. 

You may start a discussion on the flutter discord if you are so inclined. 

Thank you
