### ISSUE TITLE
Flutter web hangs when downloading file on Chrome (still)

### ISSUE THREAD

**Issue by milke** [flutter/flutter#152273]
### Steps to reproduce

I will just put references to #149417, #150523 and #150526, since they all are closed and locked, but the fix for the issue isn't available in the stable version yet :-(

We have a broken website and broken app and we have been stuck for 2 months now, we need at least some kind of hotfix. Thanks.

### Expected results

N/A

### Actual results

N/A

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

N/A

**Comment by danagbemava-nc** [comment]
Hi @milke, per our policy, issues are closed when they are fixed on main/master and not when they get merged into stable. 
https://github.com/flutter/flutter/issues/149417 was fixed by https://github.com/flutter/engine/pull/53506. You can request a cherry-pick using our cherry-pick template linked below for consideration (Please check if there isn't already a cherry pick request for this). 

Closing this since it has already been fixed. 

Thank you 

https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E
