### ISSUE TITLE
Regression in raster time in platform_views_scroll_perf_ad_banners__timeline_summary

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#152266]
On d4124bd5b571c57e4c5ebe545d61a06322a1fe24 (assuming caused by https://github.com/flutter/engine/pull/54056) there's a regression in `platform_views_scroll_perf_ad_banners__timeline_summary` where ad banners are rapidly scrolling off the screen:

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26test%3Dplatform_views_scroll_perf_ad_banners__timeline_summary&selected=commit%3D41690%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dplatform_views_scroll_perf_ad_banners__timeline_summary%252C

**Comment by jmagman** [comment]
@cbracken has suggested some kind of backoff time to wait for idleness before purging the cache would work.  We could either implement that proactively, or wait to see if we have customer feedback that they are seeing increased hitching.

Note this PR had a significant positive impact on memory benchmarks:
https://flutter-flutter-perf.skia.org/e/?keys=Xe332d40e74211cccfea289ea6902dbd3&selected=commit%3D41690%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dworst_gpu_memory_mb%252Ctest%253Dplatform_views_scroll_perf_ios__timeline_summary%252C&xbaroffset=41690

cc @hellohuanlin

**Comment by cbracken** [comment]
There are a few approaches we could take with respect to layer pool purging that might help for this benchmark in particular, but they'll definitely lead to increased complexity in the code. A few possibilities, instead of purging on the first frame where the layers are unused:
* We could purge after N frames, resetting the countdown each time the layers are used.
* Set a `purge_time` of `now` + N seconds, and each time the layers are used, reset it, on the first frame where `now > purge_time` purge.

Both of these will require a frame to be pumped to actually purge, but they're both relatively simple to implement, whereas scheduling a purge asynchronously from another thread feels potentially dangerous, and doing so by scheduling a frame feels over-complicated for what we're trying to achieve.

**Comment by jonahwilliams** [comment]
Good news, if we fix https://github.com/flutter/flutter/issues/150646 then this problem goes away. Right now this benchmark is alternating a few frames with an overlay and a few frames without. The reason is that as the ad scrolls under the app bar, we (unecessarily) create an overlay.

But since the ad is clipped, we don't actually need the overlay

**Comment by hellohuanlin** [comment]
This feels like where LRU cache can help too. We can keep a cap of unused layers to keep (say `cap=N`), then only dispose the least recently used ones exceeding `N`.

**Comment by jonahwilliams** [comment]
We should not add an LRU cache. These layers are extraordinarily expensive to keep in memory.

**Comment by jonahwilliams** [comment]
Back to baseline: https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dplatform_views_scroll_perf_ad_banners__timeline_summary&selected=commit%3D41787%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dplatform_views_scroll_perf_ad_banners__timeline_summary%252C
