### ISSUE TITLE
[CP] Implement AppLifecycleState.detached as documented

### ISSUE THREAD

**Issue by milke** [flutter/flutter#152303]
### Issue Link

https://github.com/flutter/engine/pull/53506

### Target

stable

### PR Link

https://github.com/flutter/flutter/issues/150636

### Changelog Description

The reason for this CP is to get [this fix](https://github.com/flutter/engine/pull/53506) cherrypicked into the stable version. We have a broken website and broken app and we have been stuck for 2 months now, we need this rather urgently.

### Impacted Users

all Flutter devs

### Impact Description

No impacts.

### Workaround

No known workarounds.

### Risk

low

### Test Coverage

yes

**Comment by zanderso** [comment]
Hi there, we understand this issue is important, and normally this would be a good candidate for a cp into a hotfix release. However since the fix is going out imminently in 3.24, and is available to evaluate on the 3.24 beta channel already, we're not able to turn the crank on the hotfix release process for 3.22 on such a short timeline. Thanks for your understanding, and apologies for the inconvenience.

**Comment by lastingchild** [comment]
I have upgraded my project to version 3.24.0-0.2.pre today and confirmed that this issue has been resolved.
