### ISSUE TITLE
Keyboard usability

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [flutter/flutter#15241]
How can I hide an block when the keyboard is shown and get it back when its dismissed?

How can I animate a text to go up when the keyboard is up and revert it back when dismissed?

How can I change keyboard submit type button?

How can I focus the next field when I press submit on a first field?

I couldnt find just nothing about any of this after searching for about 1 hour, i'm blind or what?

**Comment by jaumard** [comment]
I wondering how to do this also :)

**Comment by zoechi** [comment]
> How can I hide an block when the keyboard is shown and get it back when its dismissed?

https://stackoverflow.com/questions/48750361/flutter-detect-keyboard-open-close
Not perfect. See also the discussion below the answer.

> How can I animate a text to go up when the keyboard is up and revert it back when dismissed?

??? 

> How can I change keyboard submit type button?

covered by #17525

> How can I focus the next field when I press submit on a first field?

covered by #11344

I'm going to close this issue because it covers too many things.
Please open more focused issues for things you think are not addressed yet.
