### ISSUE TITLE
Flutter iOS build malfunction on Testflight and working on Android, Debug and profile ios build

### ISSUE THREAD

**Issue by omarzaki15** [flutter/flutter#152447]
I am facing a weird problem. I have developed an application on flutter that is supported on Android and iOS, the application is working fine on Android and iOS Debug, Profile and Release builds, when the application is uploaded on the store to start internal testing on the test flight some features in the application is not working specially the ones associated with google ml kit and tensor flow lite as i am using them in the application is face detection and face recognition. Do you have any Advise ?

Min IOS: 14 Min Android SDK: 26

I have tried to negate the api condition, i have tried to add some static fields that are calling the APIs, i have added some permissions in the info.plist, i restricted the application to work on iOS device only, i tried to disable code optimization, i tried to release a build with no obfuscation.

iOS Permissions in Info.plist NSCameraUsageDescription, NSLocationAlwaysAndWhenInUseUsageDescription, NSLocationWhenInUseUsageDescription, NSMicrophoneUsageDescription, NSPhotoLibraryUsageDescription, NSPhotoLibraryAddUsageDescription,

**Comment by darshankawar** [comment]
> google ml kit and tensor flow lite as i am using them in the application is face detection and face recognition. Do you have any Advise ?

@omarzaki15 These are third party packages. You will need to narrow down your case by trying to remove third party packages one by one and see which one could be causing the issue. 
Also, Support platforms like StackOverflow is a better place to ask for advice or support. If you have concrete details that shows bug in framework that is not working in TestFlight, then you will need to report it as a bug with relevant details so that we can properly address the issue.
Closing for now, as this is more of a support question rather than bug report or feature request.
