### ISSUE TITLE
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: ERROR: APK path is not specified for module "flutter_app3_android"

### ISSUE THREAD

**Issue by sovoereign** [flutter/flutter#15240]
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: ERROR: APK path is not specified for module "flutter_app3_android"

When I Run project then it shows this error, I found many solutions on the net but none of any solutions is working, When I try to set  .apk path from project Structure but it is showing blank space and not editable, Some time IDE error occurs.

**Comment by abdoasli** [comment]
I have the same problem, please help us.

**Comment by AlekseyDanilov** [comment]
<img width="702" alt="2018-03-29 16 35 41" src="https://user-images.githubusercontent.com/24591916/38091932-8ee42332-336f-11e8-952b-25461efbe927.png">

app -> Edit Configurations... Solved similar problem

**Comment by zoechi** [comment]
Is this still an issue?
Did @AlekseyDanilov s suggestion help?

**Comment by lizhaolin09** [comment]
> <img alt="2018-03-29 16 35 41" width="702" src="https://user-images.githubusercontent.com/24591916/38091932-8ee42332-336f-11e8-952b-25461efbe927.png">
> 
> app -> Edit Configurations... Solved similar problem



> <img alt="2018-03-29 16 35 41" width="702" src="https://user-images.githubusercontent.com/24591916/38091932-8ee42332-336f-11e8-952b-25461efbe927.png">
> 
> app -> Edit Configurations... Solved similar problem

i

> <img alt="2018-03-29 16 35 41" width="702" src="https://user-images.githubusercontent.com/24591916/38091932-8ee42332-336f-11e8-952b-25461efbe927.png">
> 
> app -> Edit Configurations... Solved similar problem

Hi, I solved similar problem using your advice but I really want to know why this works, thanks a lot!

**Comment by smaxwell953** [comment]
I am having this issue since upgrading to Android Studio 3.6. AlekseyDanilov's suggestion did not help.

**Comment by ImtiazXYZ** [comment]
smaxwell 

> I am having this issue since upgrading to Android Studio 3.6. AlekseyDanilov's suggestion did not help.

did you get any solution?

**Comment by imshahidu** [comment]
does anyone know how to solve the error

**Comment by Libor7** [comment]
Hi, 

I have same error in android studio: 

![image](https://user-images.githubusercontent.com/38463656/110143666-c1ee6980-7dd7-11eb-9e44-7802d16dfe40.png)


Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: ERROR: APK path is not specified for module "main"

Those few advices I could find with Google are not applicable, because in my Android Studio, which I downloaded few days ago there are none of the recommended buttons - for example there is no clean project and rebuild project in build tab: 

![image](https://user-images.githubusercontent.com/38463656/110143893-07ab3200-7dd8-11eb-9abe-bc7fbcbc0ebf.png)

similary there is no sync opportunity on file: 

![image](https://user-images.githubusercontent.com/38463656/110143983-1eea1f80-7dd8-11eb-8840-9010340fa7b0.png)

I tried to search in help. I closed the project more times and re-imported it again, but it always shows the same problem. I can see the emulator right, but it doesnt show my project app.
