### ISSUE TITLE
[google_maps_flutter_android] Convert <CameraUpdate> to Pigeon

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#152928]
Child task of https://github.com/flutter/flutter/issues/117907 

Example pull request https://github.com/flutter/packages/pull/7207 
Inital code pointer
https://github.com/flutter/packages/blob/82e8d1eecb4518a28083d7c10bd677d06574f9e6/packages/google_maps_flutter/google_maps_flutter_android/pigeons/messages.dart#L33-L121

**Comment by yaakovschectman** [comment]
cc @stuartmorgan @reidbaker 
So this one looks a little more tricky than the last couple of Pigeon conversions. `CameraUpdate` (the platform interface class, not the pigeon) does not have a set of fields like `Polygon`, for example. Instead, it can contain any of several sets of fields depending on which attribute it encodes, which themselves are stored with as JSON lists, even in the actual class. The JSON lists each contain a String tag to indicate what it encodes, followed by the attribute-specific fields. For converting to a typesafe implementation, since Dart does not have Rust-style enhanced enums (as far as I can tell), my thought was to create a pigeon `Platform...` class for each `CameraUpdate` attribute, then let `PlatformCameraUpdate` contain a single `Object` field that can be any of these. This approach seems to me like it is an improvement over the current approach, but still feels messy. Do you have any thoughts on this approach or alternatives?

**Comment by stuartmorgan** [comment]
> my thought was to create a pigeon `Platform...` class for each `CameraUpdate` attribute, then let `PlatformCameraUpdate` contain a single `Object` field that can be any of these. This approach seems to me like it is an improvement over the current approach, but still feels messy. Do you have any thoughts on this approach or alternatives?

That's exactly how I was planning to approach it as well. I wish we could do better than runtime type inspection, but that's the best option I could see. (I considered adding a `type` enum field to the top-level object, but for languages with type querying built in it's just redundant.)

> Instead, it can contain any of several sets of fields depending on which attribute it encodes, which themselves are stored with as JSON lists, even in the actual class.

This part is pretty gross as well, and I would strongly prefer we fix that in the platform interface class as a precursor, so that it's stored in a typed way and then converted to JSON only in `toJson` (vs. working around that within the Android implementation by moving all the current JSON parsing logic from Java to Dart).
