### ISSUE TITLE
[Feature Request] Support flavors on web

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#152900]
### Use case

A code repository, deploy multiple web applications according to flavors, each application has a different application name and icons.

### Proposal

1. Copy the following files or folders and update the references in the files
`web/index.html` -> `web/free.html`
`web/manifest.json` -> `web/free.manifest.json`
`web/icons/` -> `web/icons-free/`

2. For the free flavor, you can run the following command:`flutter build web --flavor free`. The entry file is changed to `free.html`, so that resources (such as icons, etc.) and manifests can be isolated. If `--target` is also specified, the code can be isolated through different entry files.

**Comment by huycozy** [comment]
This looks similar to https://github.com/flutter/flutter/issues/141371 overall even though it's not exactly the same. I would suggest we concentrate on that one since it has been prioritized and some users requested the same. You may want to follow https://github.com/flutter/flutter/issues/78254 as well since it also requested HTML path. Closing this as a duplicate. Thanks!

**Comment by cedvdb** [comment]
@kjxbyz if interested in the linked issue, you may want to leave a thumbs up for prioritization.
