### ISSUE TITLE
flutter/engine should not require oracle's java installed to commit

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#152968]
Right now committing to the Flutter engine (supposedly) requires Oracle's java installed:
![image](https://github.com/user-attachments/assets/aa0f1c11-a9ab-4ae7-8e04-62c9185bba3a)
https://github.com/flutter/engine/blob/main/docs/contributing/Setting-up-the-Engine-development-environment.md

Which (appears?) to require those of us who work at companies to sign some agreement with oracle to be able to use java?

https://www.java.com/en/download/
<img width="922" alt="image" src="https://github.com/user-attachments/assets/e26eac7d-fa9e-41e5-86c7-132b17146e11">

As far as I can tell, the formatter just wants to *run* java, which users already have installed due to Android Studio or other sources.

`flutter` has a bunch of logic to find `java`:
https://github.com/flutter/flutter/blob/521b0b327c488db2d244b04b80c1bce5e1a6ef51/packages/flutter_tools/lib/src/android/java.dart#L54
We don't need anything quite that fancy, but even just falling back to `/Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin/java` would be sufficient on mac to find `java` for the vast majority of potential Flutter committers.

My guess is that `java` just comes installed on Google Corp and thus this doesn't show up for Googlers. 🤷 

FYI @reidbaker

**Comment by jonahwilliams** [comment]
See https://whichjdk.com/

**Comment by reidbaker** [comment]
@eseidel Would this bug be resolved if I removed the word Oracle from the instructions or is there something else you think needs to happen here? 

Digging into the contents of engine/src/flutter/third_party/java/ I see we use openJDK "The [OpenJDK](https://openjdk.java.net/) is the open source reference implementation of the Java SE Specification" and not Oracle.

**Comment by gmackall** [comment]
> ... even just falling back to /Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin/java would be sufficient on mac ...

There's also a version in the third party directory which engine committers would also be pretty likely to have 
```
engine/src/flutter/third_party/java/openjdk/Contents/Home/bin/java
```

**Comment by eseidel** [comment]
Thanks for the reply @reidbaker!  I've contributed to Flutter engine for years from this machine w/o having java installed (as far as I can tell?) and things have worked.  When I upgraded our fork to 3.24 yesterday i could no longer commit (triggered by this formatter), so I went to the setup instructions to see if I had missed something.  It told me to install oracle java, so I tried, and stopped at the license agreement and filed this.

My guess is that java isn't actually required to contribute to Flutter engine (outside of the one already needed from Android studio) and we should both remove it from the setup instructions as well as change this formatter rule to use one either the Java from Android Studio/SDK or the one @gmackall points to. 🤷 

I'm happy to make the PR to do either, so long as we have consensus as to what should change.  Thanks!

**Comment by reidbaker** [comment]
I think we should remove the word Oracle if it was ever true the trace below shows we have mostly moved that word around since its introduction. I do think we should say java is required to contribute to the engine but since it is a dependency like any other we can remove it from the install instructions (or perhaps mention that java should be on the path and that there is a version of java in the third_party directory) 

I will happily accept a pr that modifies how the formatter works to use a provided version of java. I think what you ran into might be a consequence of moving the flutter dependencies into engine/src/flutter/third_party from engine/src/third_party. 

Tracing history: 
Addition to engine. 
https://github.com/flutter/engine/pull/53595/commits/94f63e20cdc53b5ea8d6c37fe1f7ca01402913b8
Removal from framework 
https://github.com/flutter/flutter/pull/151616/files#diff-8a6e60889dac256073ea47382fed26792b5c6ec654bae35011e59f78c8fbe334
Addition to framework
https://github.com/flutter/flutter/commit/ed8eaf1b84d767547cb2c04fb0d7466f0050b2a6#diff-
Wiki Entry had oracle instructions from about the time I joined https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment/9bc7d00c56373192f0dd5b699c68d03a908f1910 
Looks like it was added in the second revision of that page https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment/_compare/ea61f5d1168ed1e6a19015e2f112e2e869f979dd
