### ISSUE TITLE
Don't use SharedPreferences on Android

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15307]
This surfaced from an internal code review on the periphery of the [`shared_preferences` plugin](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/android).

### Don’t Use SharedPreferences

Android’s SharedPreferences class is used in many sample apps to store small amounts of non-relational data, and avoids doing extra disk I/O with an in-memory cache. You should not use it, for a whole host of reasons:

* __Synchronous API encourages StrictMode violations__. The primary draw of SharedPreferences is that it has a synchronous API, that is (self proclaimed as) safe to call on the UI thread - however, it’s not actually a good idea to do disk I/O on the UI thread, even if it’s wrapped in a method that says it is.
* __[apply()](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply()) has no mechanism of signalling errors__. This lets it [return immediately](https://youtu.be/b2F-DItXtZs?t=68), but isn’t really an appropriate way to store data.
* __Not durable__. Just because you’ve observed a value from SharedPreferences doesn’t mean it’s actually persisted to disk. For example, a user might change a preference (“don’t upload my pictures”), but those changes are reflected in memory before they are successfully persisted to disk. Unless carefully written to avoid this case, an application might show the user that changing their preference succeeded. When the application is restarted and loads its configuration from disk, it’d see the old value of the preference, and cause a privacy incident.
* __No consistency__. It’s not possible to implement a counter in a SharedPreference without external locks guarding it, because sharedpreferences has no transactional semantics.
* __OEM bugs__. SharedPreferences has poorly defined behavior around writes, which fails more often on some devices.

SharedPreferences is never the right tool for basically any given job. Instead, use:

* SQLite. ACID and stable. Great for relational data and larger datasets that get partial updates.
* An encapsulation that stores encoded payloads in an app's local data directory.
* LevelDB

**Comment by Hixie** [comment]
Woah, fascinating. I wonder if the Android team agrees.
This impacts my design decisions for the routing refactor.

**Comment by kurtisnelson** [comment]
The Android team does not agree that SharedPreferences is...not good.
I've put together a PR that sandpapers some of the sharp edges on the existing API down however a proper long term solution that directly operates on a file in the local data directory would be preferred.

**Comment by mehmetf** [comment]
We decided not to avoid SharedPreferences entirely but instead return failures and warn users about the pitfalls. Reasons:

- Expensive backward compatibility implementation needed to switch the underlying storage system and not break existing apps.
- There are no *light* and dependable storage APIs on Android. Sqlite, for instance, is not a good candidate due to complexity of implementation. There's already [a plugin for it](https://pub.dartlang.org/packages/sqflite) so we suggest apps to use that instead of shared_preferences to store critical data.

**Comment by anudwigna** [comment]
Is it good practice store sensitive information in SQLite as they are accessible through ADB ?

**Comment by EmmanuelMess** [comment]
@tvolkert Do you have sources to back your statements?

**Comment by tvolkert** [comment]
@EmmanuelMess the source was an Android expert I spoke to, but many of the statements can be seen in the docs or source code...

**Comment by AndroidDeveloperLB** [comment]
Why not use SharedPrefences? Why not just improve and fix it on new Android versions?
It's a very good API that many use. Using a different one could cause a lot of time and effort being wasted for something that works well already

**Comment by vitto-moz** [comment]
we have a long-running app and use sharedPreferences to store encoded tokens. As we have a refresh token mechanism that updates tokens permanently we set a new value to the SP rather ofter. After some time of using this approach, we noticed that sometimes if the app stopped (due to error, for example) after its restart we have an outdated token for the SP - that brakes our tokens consistency logic.
Looking for the workaround now...

**Comment by AndroidDeveloperLB** [comment]
There is this article:
https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079

In any case, I still think that using any other solution (instead of SharedPreferences) makes things more complex. The issues presented there are most likely extremely rare. 
It would be much better if Android OS itself would be fixed.
As an example, I proposed that there would be an API to request the OS to load specific/all sharedPreferences files together with the loading of the APK file/s:
https://issuetracker.google.com/issues/167583136

Surely if the OS loads those files together, it will fix everything related to performance, ANR and crashes.
The reason is that when your code gets to be executed, the framework has all that you need right on the RAM already, without the step of loading from a file on the storage.

This can also help with libraries that use SharedPreferences, and might use it on the UI thread. 
It can also help handle cases that the user can choose the theme of the app, because as opposed to many cases that you access the sharedPreferences, this one is critical for running on the UI thread, as you need to set the theme before inflation of the View.

And I'm sure it will benefit Flutter too.
