### ISSUE TITLE
Mac tool_integration_tests_2_5 is extremely flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153026]
The tree is closed on this issue.

The test failing a lot is `test/integration.shard/hot_reload_test.dart: hot restart works without error` as in:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_2_5/176/overview

Hot restart is a core part of our offering, and we need to root cause this issue.

I am marking this issue P0, but feel free to de-dup against any issue we already have filed for this.

@jmagman @andrewkolos

**Comment by zanderso** [comment]
There are two flaky tests. The other is:
`test/integration.shard/hot_reload_with_asset_test.dart: hot restart does not need to sync assets on the first reload`

**Comment by zanderso** [comment]
Speculatively reverting https://github.com/flutter/flutter/pull/153028.

**Comment by andrewkolos** [comment]
Related: https://github.com/flutter/flutter/issues/152220. That issue is also effectively a reappearance of https://github.com/flutter/flutter/issues/146879. Though the exact test that was timing out is different, it's also hot-reload related: `test/integration.shard/vmservice_integration_test.dart: Flutter Tool VMService method hotRestart can be called`.

**Comment by andrewkolos** [comment]
Changing title back to original to focus on macos specifically, since the flakiness here is extreme compared to other host platforms.

**Comment by andrewkolos** [comment]
Looks like the same exact test was failing with a timeout in https://github.com/flutter/flutter/issues/145812 back in April. May or may not be related.

**Comment by andrewkolos** [comment]
Closing as superseded by https://github.com/flutter/flutter/issues/153049. This would be worth re-opening if this check is severely flaking due to non hot reload related tests. At the very least, with the revert of https://github.com/flutter/flutter/pull/153028 significantly lowering the flake rate, this is not a P0.
