### ISSUE TITLE
url_launcher on Android does not support javascript

### ISSUE THREAD

**Issue by bhrose** [flutter/flutter#15316]
With forceWebView: true on Android, I'm getting a blank white page. This is the code I'm using:

```
  new RaisedButton(onPressed: _launchURL, child: new Text('Share your feedback'),),

_launchURL() async {
  const url = 'https://brianrose.typeform.com/to/NmGg1a';
  if (await canLaunch(url)) {
    await launch(url, forceWebView: true);
  } else {
    throw 'Could not launch $url';
  }
```

Without forceWebView: true, on Android the survey opens in a new Chrome window and works as intended, and on iOS it opens in WebView also as intended. But with forceWebView: true, my Android app opens a blank white screen. Is it a permissions issue?

Expected: Open survey in WebView.
Actual: App opens a blank white screen.
Device: Pixel XL running Android 8.1.0

My app is at https://play.google.com/store/apps/details?id=com.brianrose.botornot and the survey appears on the final screen (ScorePage).

Discussion on Google Groups at https://groups.google.com/forum/#!topic/flutter-dev/9orHejC4sA8

**Comment by jordyvandomselaar** [comment]
Bump.

**Comment by mehmetf** [comment]
@bhrose could you please give me a bit more detail about this bug?
- Are you seeing this for every URL? e.g. what happens if you try to open www.google.com with forceWebView: true?
- Are you able to run the [sample app](https://github.com/flutter/plugins/tree/master/packages/url_launcher/example) with forceWebView: true?

**Comment by mehmetf** [comment]
I am able to see flutter.io in the webview on Android 8.0.

Currently the webview provided by this plugin is [very basic](https://github.com/flutter/plugins/blob/master/packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java#L96). It does not support javascript for instance. I assume that could be the reason why your website is failing to load.

See basic usage here: https://developer.android.com/reference/android/webkit/WebView.html. That's the capability we are providing. Quoting Android reference for WebView:

> If you actually want a full-blown web browser, then you probably want to invoke the Browser application with a URL Intent rather than show it with a WebView.

**Comment by bhrose** [comment]
Thanks Mehmet. I'm OOO until Fri but will check. I didn't realize webview didn't support javascript, that's probably why I get the blank white page. I'll confirm then close when I'm back home this weekend, cheers.

**Comment by jordyvandomselaar** [comment]
The JavaScript thing is probably the issue for me, I want to show a bitbucket page, but bitbucket is full JS. Since IOS opens a webview by default, does it work in that webview?

Is it possible to automatically close the webbrowser of the user when done? Now the user has to hit "recent apps" twice to switch back to the app and the old page remains open in the browser.

**Comment by mehmetf** [comment]
@jordyvandomselaar if you open a web page on a browser, the control is entirely with the browser. Any other app cannot make the browser do anything (including close). 

That's why most people prefer opening a SafariVCController on iOS. That's the plugin's default behavior on iOS. It also supports javascript.

On Android, default behavior is browser because webview is very limited and the UX is much better. Once user is done with browser, they hit "back" and they should land back on your app closing the page they opened on browser.

**Comment by jordyvandomselaar** [comment]
@mehmetf As far as I've noticed other apps run js in webviews just fine, especially since Android supports setting Chrome as the default webview implementation. I think it's a UX problem to have the user hit "back" to close a login window.

**Comment by mehmetf** [comment]
I see your use case a bit more clearly now.

Login via webview is not a good idea on Android. Stuff [like this](https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/) happens because webviews cannot save sessions and cannot access to the same cookie store as the browser does. I recommend implementing login as a pure Flutter view as opposed to relying on a webview.

Currently the url_launcher plugin does not support embeddable webviews with controls. The only way for you to open a webview is full-screen and the only way to close it is via back button (i.e. same as browser). The only advantage that webview has over browser is the lack of distracting browser controls.

If you want to open a webview inside a custom layout, I recommend taking a look at https://pub.dartlang.org/packages/flutter_webview_plugin. Let me know if that serves the purpose.

**Comment by jordyvandomselaar** [comment]
It's not my login view, else I would've =) It's an OAuth page, there's no session, I just have to read the token from the get param (which I do by temporarily starting a local server to catch the request) -- The webview only has to open the OAuth page, load the redirect, and then close.

I'll make a video with what's going on when I get the time.

**Comment by mehmetf** [comment]
What you are describing does not sound like a good candidate for url_launcher plugin. You want full control of the webview itself. `url_launcher` by definition launches an intent to do something and lets the OS handle the rest.

I am changing this issue to track lack of javascript support, however even if that was fixed, it would not serve your use case. Please try the flutter_webview_plugin that I linked above. I believe that has more control over the webview including closing it.

**Comment by bhrose** [comment]
Thanks Mehmet. Also, I confirmed that changing my target url to www.google.com works as intended, and the sample app works as intended.

**Comment by jordyvandomselaar** [comment]
Thank you, @mehmetf -- I'll give it a shot =)
