### ISSUE TITLE
Issue on the flutter 3.24

### ISSUE THREAD

**Issue by ClementDunstanSiaffu** [flutter/flutter#153142]
Currently there was release of flutter 3.24 but the maximum version of the AGP it can works on is 8.0.1 and the maximum API level that AGP can work on is compile SDK 33 but google play requires us to update our API level to 34 until end of august all app in play store need to change to 34 and for that to work flutter needs to support atleast 8.1.1 AGP version inorder for it to work in 34 API level

**Comment by huycozy** [comment]
I built Android app target as following Gradle/AGP versions and target API 34 but don't see any issue (app can run normally):

- /android/settings.gradle

```gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.1" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}
```

- /android/gradle/wrapper/gradle-wrapper.properties

```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-all.zip
```

What are your current versions in these files? And what error are you seeing?

Please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

**Comment by ClementDunstanSiaffu** [comment]
I have already fixed that I had to update Android Studio

**Comment by ClementDunstanSiaffu** [comment]
Thanks
