### ISSUE TITLE
Flutter in_app_purchase Ios 

### ISSUE THREAD

**Issue by PavloKonopadaDev** [flutter/flutter#153275]
### Use case

I have a problem when using in_app_purchase 3.2.0.  Background, I am developing an application that has autosubscription. In order to test, I use a sandBox account.
When I make the first purchase, I receive a notification, initial purchase, which contains a unique transaction id, unsubscribe (in the settings), and subscribe again, then I receive the same transaction id in the notification, has anyone encountered such a problem? Shouldn't it be?

### Proposal

Background, I am developing an application that has autosubscription. In order to test, I use a sandBox account.
When I make the first purchase, I receive a notification, initial purchase, which contains a unique transaction id, unsubscribe (in the settings), and subscribe again, then I receive the same transaction id in the notification, has anyone encountered such a problem? Shouldn't it be?

**Comment by huycozy** [comment]
Hi @PavloKonopadaDev 
Two sections above are the same and this looks like a bug report rather than a proposal. Please open a new issue and try to fill all information in the proper bug template (see [Report a bug in one of Flutter's first-party packages](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)) so that we have enough information to investigate. Closing this issue.
