### ISSUE TITLE
Stale VERSION file inside the SDK shipped with Flutter

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#15348]
Dart Code displays the contents of the `VERSION` file in the Dart SDK in the status bar. Sometime recently (possibly when Flutter switched to making its own SDK builds) it seems that this file became stale:

```text
Dannys-MacBook:~ danny$ flutter --version
Flutter 0.1.6-pre.3 • channel master • https://github.com/DanTup/flutter.git
Framework • revision 7f03b9e41b (2 weeks ago) • 2018-02-23 12:49:57 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
Dannys-MacBook:~ danny$ cat /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/version
2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
```

The Dart SDK revision is `0b4f01f759` (confirmed by running `dart --version`) so not sure why the file is bad.

Dart Code uses this files because it's faster (and less troublesome) than spawning a process.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/45921 with the potential fix.

**Comment by zanderso** [comment]
These are different because https://github.com/dart-lang/sdk/blob/master/tools/make_version.py has different logic from https://github.com/dart-lang/sdk/blob/master/tools/write_version_file.py.

We should probably eliminate https://github.com/dart-lang/sdk/blob/master/tools/write_version_file.py, and instead use https://github.com/dart-lang/sdk/blob/master/tools/make_version.py to write the version file to make sure that they both say the same thing.

**Comment by Hixie** [comment]
What's the status of this issue?

**Comment by DanTup** [comment]
Still an issue. This is latest master:

```
Dannys-MacBook:flutter danny$ flutter --version
Flutter 0.5.3-pre.18 • channel master • https://github.com/DanTup/flutter.git
Framework • revision 326caa5d22 (15 minutes ago) • 2018-06-09 03:39:27 -0400
Engine • revision 5d2f24aa5c
Tools • Dart 2.0.0-dev.60.0.flutter-a5e41681e5

Dannys-MacBook:flutter danny$ cat bin/cache/dart-sdk/version 
2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c
```

a5e41681e5 is the correct version, which is from 4 days ago.
c080951d45 is wrong, it's a commit from March.
