### ISSUE TITLE
Having trouble debugging wirelessly for an IOS device by using vscode plugin

### ISSUE THREAD

**Issue by LarryWangCA** [flutter/flutter#153799]
Hi there,

I need to debug the IOS device in wireless mode because the lightning port has to be connected to an external USB device. I use VSCode with latest flutter and dart plugin installed. The wired mode debug is fine since I can hot restart and hot reload. Each time after clicking start debugging, it has the following error:

Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
The Dart VM Service was not discovered after 75 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.

Click "Allow" to the prompt asking if you would like to find and connect devices on your local network. This is required for wireless debugging. If you selected "Don't Allow", you can turn it on in Settings > Your App Name > Local Network. If you don't see your app in the Settings, uninstall the app and rerun to see the prompt again.

The app remains white for a few minutes and cannot display anything. Can someone suggest how to debug wirelessly for IOS device with hot restart / hot reload? I am testing with the default Flutter demo project. I can run the project wirelessly in xcode but I do not have the useful hot restart / hot reload function. 

Thank you in advance for any help.

**Comment by huycozy** [comment]
Hi @LarryWangCA 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

For us to investigate this further, please provide the output of `flutter doctor -v`. This seems to be similar to https://github.com/flutter/flutter/issues/144634.

**Comment by LarryWangCA** [comment]
Hi @huycozy 

 Thank you for your kind reply. This issue is indeed similar to #144634. But I did not see a clear solution to the previous issue.

My device:
1: Macbook Pro with MacOS14.2
2: iPhone 11 with IOS17.5.1

Steps to reproduce:
1: follow the following instruction to setup the development environment: https://docs.flutter.dev/get-started/install/macos/mobile-ios and Install fullter and dart plugin in vscode
After running flutter doctor -v:
<img width="1024" alt="92FD59CE-94A2-4BCD-A6B0-BA29E515B33F" src="https://github.com/user-attachments/assets/65c79a6a-8692-48f9-9d79-3b94d8047bd0">
2: use flutter create to create a project
3: Under Run->Start debugging to debug the default project with the wirelessly connected iPhone. It always has the following error (same as debugging by using command line, the app can be installed but nevered opened. I cannot debug anything):
![image](https://github.com/user-attachments/assets/fb2de66f-0588-4bd8-ba73-ad2fcaf35a8b)

Sometimes even if I use build -profile wirelessly, it also has this error (however the app can be successfully launched after waiting 3-4 minutes). This maybe a severe bug if someone uses flutter to develop IOS app wirelessly.

Thank you in advance for any help.

Best,

Larry

**Comment by huycozy** [comment]
That issue is still open and needs to be investigated further. I see you are using XCode 15 and iOS 17 and there is also a user shared a workaround at https://github.com/flutter/flutter/issues/144634#issuecomment-1981987930, you can try to see if it works for you.

I will close this in favor of https://github.com/flutter/flutter/issues/144634 as the team was aware of the issue. Please ask the same there and provide information if needed. Thank you!
