### ISSUE TITLE
Allow for customization of mainAxisMargin in CupertinoScrollbar

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#154040]
### Use case

Needed for https://github.com/flutter/flutter/issues/55025 to correctly draw the scrollbar used in scrollable context menus.

This is what CupertinoScrollbar would look like:

https://github.com/user-attachments/assets/b3e31682-d2a9-4454-a3fd-edb85d0888b2

This is the native margin:

https://github.com/user-attachments/assets/4147116c-307d-4eb0-9587-e8045881aa73

### Proposal

Add property `mainAxisMargin` to `CupertinoScrollbar`.

**Comment by huycozy** [comment]
Hi @victorsanni, I see the main and cross axis margins are set as 3.0 currently:

https://github.com/flutter/flutter/blob/a7eaca934ddca15c9180492a3eb4637bff283fdb/packages/flutter/lib/src/cupertino/scrollbar.dart#L26-L31

I wonder if this is somewhat similar to or is nested in https://github.com/flutter/flutter/issues/32175. Could you take a look and confirm if this issue is a variant or an equivalent one?

**Comment by victorsanni** [comment]
@huycozy yes they seem to be very related. That issue seems to be more of a fidelity one (the scrollbar having different margins in different native scrollviews) and this seems to be more of a customizability one (allow anyone to set what margins they want). 

I'm not sure what a solution for that issue would look like. I do think fixing this issue would reduce the criticality of the other issue.

**Comment by victorsanni** [comment]
Changed to only mainAxisMargin, so that only needed properties are exposed. This would then be closed by https://github.com/flutter/flutter/pull/154133.
