### ISSUE TITLE
Do not include dSYMs for "release" simulators in engine artifacts

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#154019]
As of https://github.com/flutter/flutter/issues/116493 my Flutter artifacts has 4 `dSYMs` directories:
```
bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/dSYMs
bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64/dSYMs
bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64_x86_64-simulator/dSYMs
bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/dSYMs
```
`ios-release/Flutter.xcframework/ios-arm64_x86_64-simulator/dSYMs/Flutter.framework.dSYM` and `extension_safe` version are  590MB each.  However, that simulator dSYM isn't necessary, as `ios-arm64_x86_64-simulator` is a debug copy that's only used when the simulator is launched in release mode (which we don't really support anyway).  

Do not build a dSYM for the copied debug version.

**Comment by jmagman** [comment]
cc @cbracken

**Comment by jmagman** [comment]
`simulator_dsym` logic should be removed:
https://github.com/flutter/engine/blob/fd55b76e51e5abe287a1722a66acd038f17ecf84/sky/tools/create_ios_framework.py#L134-L137

**Comment by cbracken** [comment]
Discussed over chat -- I had added this intentionally to support testing in simulator release builds, since those include a simulator slice. 

Apparently, release simulator runs are an unsupported configuration. @jmagman suspects this was possibly added to allow add-to-app customers to compile their app for release simulators so that users could test the non-flutter bits of their apps.

https://github.com/flutter/flutter/issues/11754 tracks officially supporting release simulator builds. But so long as this is an officially unsupported configuration, we'll stop bundling the simulator dSYMs to save developers the download/storage cost.
