### ISSUE TITLE
Convert package `video_player_android` to kotlin

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#154256]
### Use case

For a custom package, I recently needed to (semi-automatically) convert the `video_player_android` to kotlin. It removed quite a lot of code, and brings advantages like null safety.

### Proposal

Would it be also good to integrate it in the packages repository, as other repos are also written in kotlin (like `shared_preferences`, `interactive_media_ads`, )? So I can create a PR. Or is it still wanted to be in Java.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#languages for the current policy on this.

For `video_player_android` there's the added complication that we are currently exploring having `video_player` be our proof of concept/demonstration plugin for using FFI instead of platform channels, and if we go that route we would likely end up with little or no Java or Kotlin code.

Marking for Android team review, but I think this is probably not something we want to change right now.

**Comment by Gustl22** [comment]
Thank you for pointing to this policy. Feel free to close this issue, if it's not on Flutters agenda, was more of an offer ;D

**Comment by reidbaker** [comment]
Thanks for the bug but @stuartmorgan is correct and video_player_android is amongst the least likely for us to accept a conversation to Kotlin. That said if you are feeling up to it later for a different plugin please file another issue and let us know.
