### ISSUE TITLE
showDialog throws an exception when localizing an app to a language not found in `MaterialLocalizationsDelegate`

### ISSUE THREAD

**Issue by Fideas** [flutter/flutter#15439]
## Steps to Reproduce

I'm using Flutter to write an app that must be localized in norwegian and english. I declared support for both languages using  `supportedLocales` in my main app widget.
At some point I want to display a dialog using `showDialog(Context, Widget)`, but I noticed that in the implementation of `showDialog` there is a call to `MaterialLocalizations.of(context).modalBarrierDismissLabel` that is causing an exception (see below) and prevents the dialog from showing at all. By removing `Locale('nb', 'NO');` from the list of supported locales, the app behaves as expected (the dialog appears)

## Logs

I/flutter (22056): The getter 'modalBarrierDismissLabel' was called on null.
I/flutter (22056): Receiver: null
I/flutter (22056): Tried calling: modalBarrierDismissLabel

**Comment by Fideas** [comment]
Could this be solved by calling `GlobalMaterialLocalizations.of(context).modalBarrierDismissLabel` instead?

**Comment by tygryk** [comment]
Same error with Belarusan Language, locale be-BY

Is there a way to override the call without waiting for full translation from Flutter?

**Comment by HansMuller** [comment]
Flutter has added support for Norweigian since this issue was first opened. Support for the Belarusan Language is not available yet.

There's now a somewhat more informative console warning (debug mode) when the app's `supportedLocales` names a locale that Flutter hasn't been localized for:
```
I/flutter (14227): ════════
I/flutter (14227): Warning: This application's locale, be_BY, is not supported by all of its
I/flutter (14227): localization delegates.
I/flutter (14227): > A MaterialLocalizations delegate that supports the be_BY locale was not found.
I/flutter (14227): See https://flutter.io/tutorials/internationalization/ for more
I/flutter (14227): information about configuring an app's locale, supportedLocales,
I/flutter (14227): and localizationsDelegates parameters.
I/flutter (14227): ════════
```

In this case, probably the best thing to do is for the app to include its own support for the Belarusan Language. Currently there's no explanation in https://flutter.io/tutorials/internationalization/ about how to do that, so here we go.

To add Material library support for a single new locale one must create a locale-specific [GlobalMaterialLocalizations](https://docs.flutter.io/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html) subclass that defines the approximately 65 localizations the Material library depends on. Additionally one must create a [LocalizationsDelegate](https://docs.flutter.io/flutter/widgets/LocalizationsDelegate-class.html) subclass that essentially just constructs an instance of the new GlobalMaterialLocalizations subclass.

There's a complete example, less actual Belarusan translations, here: https://gist.github.com/HansMuller/978e8703c2c4253e3113ef468b6e7936.

The locale-specific GlobalMaterialLocalizations subclass is called `BeMaterialLocalizations` and the LocalizationsDelegate subclass is `_BeMaterialLocalizationsDelegate`. The value of BeMaterialLocalizations.delegate is an instance of the delegate, and that's all that's needed by an app that uses these localizations.

The delegate class includes basic date and number format localizations. All of the other localizations are defined by String valued property getters in BeMaterialLocalizations.

The getters return "raw" Dart strings that have an `r` prefix, like `r'About $applicationName'`, because the $variables are expanded by methods with parameters, like [aboutListTileTitle(String applicationName)](https://docs.flutter.io/flutter/flutter_localizations/GlobalMaterialLocalizations/aboutListTileTitle.html).

More information about the localization strings can be found in the flutter_localizations package's [README](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/README.md) file.

**Comment by HansMuller** [comment]
I'm closing this because we've added a section to the i18n tutorial that covers the material in https://github.com/flutter/flutter/issues/15439#issuecomment-480462059, see https://github.com/flutter/website/pull/2603
