### ISSUE TITLE
Cupertino dialogs should have a blur and opaqueness that approximates iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15431]
iOS 11's dialog boxes' backgrounds are no longer translucent. Remove the transparency.

**Comment by xster** [comment]
Looking more carefully at the sketch specs in https://developer.apple.com/design/resources/ and https://developer.apple.com/ios/human-interface-guidelines/views/alerts/, it looks like there is a blur on the dialog background.

**Comment by matthew-carroll** [comment]
Agreed that a blur still seems to exist in that doc.  Is there a process for determining the blur amount? Or do we have a contact that can give specific details?

**Comment by xster** [comment]
Unfortunately it's difficult to quantify it from those specs. I would place the same background behind a native app and behind Flutter and iteratively try to match it by eye. Many of our other widgets had to follow this approach since many iOS things are not documented.

**Comment by matthew-carroll** [comment]
Blurring a cupertino dialog (including alert dialog) is currently impossible due to a bug in SKIA that breaks blur when used in conjunction with a ClipRRect:
https://bugs.chromium.org/p/skia/issues/detail?id=6753

Fix this ticket when the SKIA bug is corrected.

**Comment by matthew-carroll** [comment]
The SKIA bug has been corrected and clipped blurring now works in the CupertinoDialog.

While working on this ticket @xster and I found that simply blurring the content behind the CupertinoDialog is not enough to match iOS's effect.  On iOS it looks like the dialog applies its blur directly to the content beneath the "modal barrier."  In other words, on iOS the dark barrier does not factor into the blurred background of the dialog.

The technically correct way to achieve iOS's effect is probably to alter the compositor so that the dialog can reach behind the modal barrier, blur what's behind it, and then use that as its background.  For now this work is disproportionate to the value-add of the effect.  Therefore, we are going to use a technique that produces a similar result with much less effort.

The shortcut: The barrier overlay is a translucent black applied to the screen. Therefore, the barrier takes all the colors on the screen and reduces their brightness.  By applying a blend mode to those darkened pixels we should be able to lighten them back up.  Therefore, we can apply a blend mode to the dialog's background to make it appear as if the dialog is blurring what's below the barrier.  The blend mode that we believe works well is "overlay."  The overlay blend mode should be applied with a completely opaque white 0xFFFFFFFF.

In addition to the "overlay" blend mode painted over the blurred background, a translucent white foreground is also required so that the dialog is more opaque, bright, and legible.  The foreground white that we found to work well is 0xC0FFFFFF.

Lastly, the dividers that separate action buttons from dialog content, and the dividers that separate each button from each other, are not a solid color.  These dividers are actually a translucent gray.  We have found 0x20000000 to be a decent approximation.  But translucency isn't the only thing to worry about for these dividers.  The translucent dividers shouldn't show through to the white content background - the translucent dividers should show through to the blurred background.  This means that dialogs are not single pieces, but rather a white content piece followed by one or more white button pieces with thin gray gaps in between.

The PR for this ticket should address all points above.

**Comment by matthew-carroll** [comment]
https://github.com/flutter/flutter/pull/18381

**Comment by shinsenter** [comment]
CupertinoAlertDialog over Google Maps does not have blur background. Tested on master branch.
```
[√] Flutter (Channel master, v1.18.0-5.0.pre.57, on Microsoft Windows [Version 10.0.18363.720], locale ja-JP)
    • Flutter version 1.18.0-5.0.pre.57 at C:\flutter
    • Framework revision a5765331bc (7 hours ago), 2020-04-09 16:15:01 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\mai.tan\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including the following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Windows                   • Windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.720]
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
