### ISSUE TITLE
flutter and native hybrid development will not work

### ISSUE THREAD

**Issue by l476175728** [flutter/flutter#154547]
### Steps to reproduce

1  creat a flutter module from terminal
2 creat a android project with android studio
3 Configure flutter dependencies in the Android project
4  can not run 

### Actual results

this error
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/d51ad67e-ef21-43f5-9d5f-6105cb7d4d11">

config
<img width="778" alt="image" src="https://github.com/user-attachments/assets/2ca9a5c3-04b9-467f-86cb-8cf1552b2852">

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @l476175728 
Please provide the error output in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text).

Also, can you share the AGP and Gradle versions that are being used on Android native project? (These should be found on `build.gradle.kts` and `gradle-wrapper.properties` files)
