### ISSUE TITLE
Day and Month start with lowercase in Spanish locale

### ISSUE THREAD

**Issue by yuruyuri16** [flutter/flutter#154699]
### Steps to reproduce

```dart
final date = DateTime.now();
print(DateFormat.yMMMMEEEEd('es').format(date));
```

### Expected results

```
Jueves, 5 de Septiembre de 2024
```

### Actual results

```
jueves, 5 de septiembre de 2024
```

**Comment by Nishesh73** [comment]
Hi @yuruyuri16 

I noticed that this issue is still open, and I'd like to work on resolving it if no one else is already working on it. Please let me know if I can proceed with addressing the problem of lowercase day and month names in the Spanish locale.

**Comment by darshankawar** [comment]
@yuruyuri16 
Since `DateTime` class comes from dart-core library and `DateFormat` from intl package which is dart based, I think this will need to be reported in https://github.com/dart-lang/i18n/issues
If you think this is incorrect or get redirected here, please write in comments and I'll reopen it.
