### ISSUE TITLE
Google Maps Flutter Web 0.5.10 uses incorrect dart type for `types` fields

### ISSUE THREAD

**Issue by cornwe19** [flutter/flutter#154846]
### Steps to reproduce

1. Use Google Maps Places API on Flutter web to make an autocomplete request
2. When the Future resolves, attempt to read the 'types' field of the AutocompleteResponse.AutocompletePrediction class

Alternatively,

1. Use the Google Maps Geocoder API on Flutter web to make a geocode request
2. When the future resolves, attempt to read the 'types' field of the GeocoderResponse.GeocoderResult.AddressComponents class

### Expected results

In both cases above, `types` should resolve to a Dart `List<String>`.

### Actual results

In both cases above, accessing `types` throws the following error

```console
TypeError: Instance of 'JSArray<Object?>': type 'List<Object?>' is not a subtype of type 'List<String>'
```

### Code sample

<details open><summary>Code sample</summary>

```dart
var result = await Geocoder().geocode(GeocoderRequest(placeId: 'EiU0MCBDaGFycmluZyBMYW5lLCBOZXcgQ2FzdGxlLCBERSwgVVNBIjASLgoUChIJnatqLEQBx4kRkS5TYI0rk5YQKCoUChIJnatqLEQBx4kRpG3SnXjDyIU'));
var types = result.results.first.addressComponents.first.types;
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
TypeError: Instance of 'JSArray<Object?>': type 'List<Object?>' is not a subtype of type 'List<String>'
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/dennis/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for Dennis’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by 625015** [comment]
Can I work on this issue?

**Comment by AlexanderLid** [comment]
Same issue in GoogleMapController animateCamera. Currently blocks upgrading stable channel.

**Comment by kevmoo** [comment]
@lballard625015 – PRs always welcome!

**Comment by huycozy** [comment]
Hi @cornwe19, can you share a complete and minimal sample code so that I can give it a try on my end?

>Same issue in GoogleMapController animateCamera. Currently blocks upgrading stable channel.

@AlexanderLid I can't reproduce the issue with `animateCamera`, can you share a sample code as well? Thanks!

**Comment by AlexanderLid** [comment]
Thank you for looking into this. I've created a minimal example to demonstrate the issue, looks like its animateCamera with  CameraUpdate.newLatLngBounds, and animateCamera works otherwise.
Here's the code:
<details>
<summary>code</summary>
`import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Map View Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MapViewBugDemo(
        fallbackLatitude: 55.676098,
        fallbackLongitude: 12.568337,
      ),
    );
  }
}

class MapViewBugDemo extends StatefulWidget {
  const MapViewBugDemo({
    super.key,
    required this.fallbackLatitude,
    required this.fallbackLongitude,
  });

  final double fallbackLatitude;
  final double fallbackLongitude;

  @override
  State<MapViewBugDemo> createState() => _MapViewBugDemoState();
}

class _MapViewBugDemoState extends State<MapViewBugDemo> {
  GoogleMapController? _mapController;
  CameraUpdate? _cameraUpdate;

  void _onMapCreated(GoogleMapController controller) {
    _mapController = controller;
  }

  void _updateCameraPosition() {
    final LatLngBounds bounds = LatLngBounds(
      northeast:
          LatLng(widget.fallbackLatitude + 0.1, widget.fallbackLongitude + 0.1),
      southwest:
          LatLng(widget.fallbackLatitude - 0.1, widget.fallbackLongitude - 0.1),
    );

    setState(() {
      _cameraUpdate = CameraUpdate.newLatLngBounds(bounds, 50);
    });

    print('CameraUpdate created: $_cameraUpdate');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Map View Bug Demo')),
      body: GoogleMap(
        onMapCreated: _onMapCreated,
        initialCameraPosition: CameraPosition(
          target: LatLng(widget.fallbackLatitude, widget.fallbackLongitude),
          zoom: 13,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _updateCameraPosition,
        child: const Icon(Icons.center_focus_strong),
      ),
    );
  }
}
</details>

**Comment by huycozy** [comment]
@AlexanderLid Thanks for providing the code. I ran it on Web but couldn't see the issue. I'm on the latest Flutter stable 3.24.2 and using `google_maps_flutter: 2.9.0`/`google_maps_flutter_web: 0.5.10`. Can you upgrade Flutter and plugin then retry?

<details>
<summary>Demo screenshot/video</summary>

https://github.com/user-attachments/assets/8021e49f-1901-4502-b3fb-ab989a0d0b90
</details>

**Comment by dhiaCodes** [comment]
> Same issue in GoogleMapController animateCamera. Currently blocks upgrading stable channel.

I confirm this on Android.
```
Flutter (Channel stable, 3.22.2)
google_maps_flutter: ^2.9.0
```

**Comment by bdmasiaenterpris** [comment]
[Uploading https-github.com-bdmasiaenterpris-bdmasiaenterpris-main.zip…]()
[https-github.com-bdmasiaenterpris-bdmasiaenterpris-main.zip](https://github.com/user-attachments/files/16961603/https-github.com-bdmasiaenterpris-bdmasiaenterpris-main.zip)

**Comment by bdmasiaenterpris** [comment]
[Uploading CONTRIBUTING BDM.md…]()

**Comment by kevmoo** [comment]
@ditman – thoughts here?

**Comment by ditman** [comment]
Thanks for reporting!

As for @cornwe19's issue, this looks like a small problem in the JS-interop layer (`package:google_maps`).

I think the problem is the implementation of this method (maybe others, since the package is mostly code-generated?):

* https://pub.dev/documentation/google_maps/8.0.0/google_maps_geocoding/GeocoderAddressComponent/types.html ([implementation](https://github.com/a14n/dart-google-maps/blob/master/lib/src/generated/geocoder/geocoder_address_component.dart#L32-L33))

I think the issue is that `dartify` is not deeply converting the `JSString` to Dart's `String`?

We've often fixed those with something like: `return _types.map((JSString t) => t.toDart).toDart;` right?

@kevmoo I think this issue, and the fix for it belongs in github.com/a14n/dart-google-maps.

(It's not clear that to me that the issue with `CameraUpdate` is related, or even a web thing; seems to be Android only?)

**Comment by cornwe19** [comment]
> Thanks for reporting!
> 
> As for @cornwe19's issue, this looks like a small problem in the JS-interop layer (`package:google_maps`).
> 
> I think the problem is the implementation of this method (maybe others, since the package is mostly code-generated?):
> 
> * https://pub.dev/documentation/google_maps/8.0.0/google_maps_geocoding/GeocoderAddressComponent/types.html ([implementation](https://github.com/a14n/dart-google-maps/blob/master/lib/src/generated/geocoder/geocoder_address_component.dart#L32-L33))
> 
> I think the issue is that `dartify` is not deeply converting the `JSString` to Dart's `String`?
> 
> We've often fixed those with something like: `return _types.map((JSString t) => t.toDart).toDart;` right?
> 
> @kevmoo I think this issue, and the fix for it belongs in github.com/a14n/dart-google-maps.
> 
> (It's not clear that to me that the issue with `CameraUpdate` is related, or even a web thing; seems to be Android only?)

Agree with the above and your hunch about `dartify()` sounds right. Still haven't had a chance to create a more complete code sample yet

**Comment by ditman** [comment]
@cornwe19 To simplify things, you may be able to create a `google_maps`-only reproduction case, starting from its [geocoding-simple](https://github.com/a14n/dart-google-maps/blob/master/example/geocoding-simple/page.dart) example?

To unblock yourself, since this uses the new JS-Interop, you should be able to define a few extension methods on `GeocoderAddressComponent`, where you add your own getters for the `types` variable, something like this:

```dart
extension ToDartTypesGetter on GeocoderAddressComponent {
  @JS('types')
  external JSArray<JSString> _myTypes;
  List<String> get typesAsList => _myTypes.map((JSString t) => t.toDart).toDart;;
}
```

And use the new `.typesAsList` getter from your code.

In any case, if we confirm that this issue is in the `google_maps` package, we'll need to move it to Alexandre's repo (and maybe even contribute a fix at the same time :P)!
