### ISSUE TITLE
CreateProcessW failed 193

### ISSUE THREAD

**Issue by rahulflutter** [flutter/flutter#15481]
```
C:\Users\Rahul Daas>flutter devices
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 28c71bb92315a19b)
CreateProcessW failed 193
CreateProcessW failed 193
Crash report written to C:\Users\Rahul Daas\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by Hixie** [comment]
Can you upload `C:\Users\Rahul Daas\flutter_02.log`?

**Comment by rahulflutter** [comment]
[flutter_02.log](https://github.com/flutter/flutter/files/1816417/flutter_02.log)

**Comment by Hixie** [comment]
Does this work now? We believe the problem was the space in your username, but we think we've solved that now.

If you still see this, please file a new bug with as much information as you can provide us. Thanks!

**Comment by keithmorgan** [comment]
i have the same problem 

`CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 90c51fd53df122d1)
CreateProcessW failed 193
CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\to the moon\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l

**Comment by zoechi** [comment]
@keithmorgan perhaps #18938

**Comment by rakhirocky365** [comment]
i am also getting this error


C:\src\flutter>flutter
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{
u}

**Comment by kangwang1988** [comment]
@rakhirocky365 
If you can reproduce this issue using the latest master, please file a new issue so that we can track it better.

**Comment by zoechi** [comment]
@rakhirocky365 perhaps Git v1.x instead of Git v2.x
Please check the output of `git --verson` and ensure you have 2.x installed.
Also please try running `C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}` from the Flutter install directory.

**Comment by Rakib00111** [comment]
same problem please help me

**Comment by sanjayajena37** [comment]
`CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 90c51fd53df122d1)
CreateProcessW failed 193
CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\to the moon\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l `


i have same issue

**Comment by subham468** [comment]
Can anyone help me with this Error?


[Flutter.txt](https://github.com/flutter/flutter/files/3170177/Flutter.txt)

**Comment by bayardkalyan** [comment]
Same debug error in Flutter Web here. 
"CreatedProcessW failed 2
Exited(1)"

**Comment by sanjayajena37** [comment]
hey subham468 i was see your problem you 

> Can anyone help me with this Error?
> 
> CreateProcessW failed 193
> Unhandled exception:
> ProcessException: %1 is not a valid Win32 application.
> 
> For More info please visit the link and Help me Please
> [Flutter.txt](https://github.com/flutter/flutter/files/3170177/Flutter.txt)

i was see your problem C:\Users\**Subham Paul**\AppData\Local\Android\sdk\platform-tools\adb.exe

**Change pc name in c drive to Subham Paul to Subham**

**Comment by meek2100** [comment]
The solution shouldn't be for the user to change their profile name. 

It should be changed so the the path to the adb.exe inside double quotes with the argument following outside of it.

"C:\Users\Subham Paul \AppData\Local\Android\sdk\platform-tools\adb.exe" devices -l

**Comment by raktimkashyap** [comment]
same problem
i changed the username to one word. re installed android studio. it still gives the same error

**Comment by tonikwater** [comment]
I have the same issue, the problem is also that Im not able to launch my application on emulators or even on my connected device, everything worked, suddenly I was not able anymore to run my application so I ran flutter doctor and got the error message ... so annoying because you basically cant use flutter anymore because you cant run your applications live, without its kind of no fun

btw I also dont know why changing the username should fix it because before everything was working like it should.

and I also tried uninstalling flutter and reinstalling but it doesnt worked :C

**Comment by tonikwater** [comment]
I HAVE SOLVED IT the error seems to appear because their are spaces in your username but its really easy to fix you just have to, move the Android SDK which is located by default in C:\Users\username\AppData\Local\Android\Sdk
You have to move the "Sdk" Folder into a directory where are no spaces included in the path name 
for example:
C:\randomFolderWithoutSpaces\Sdk

Then you have to create a new environment variable called ANDROID_HOME and set its value to the new path of the Sdk ( in this example: C:\randomFolderWithoutSpaces\Sdk )
Therefore you have to add these values to the Environment Variable Path (for this example):
C:\randomFolderWithoutSpaces\Sdk\tools
C:\randomFolderWithoutSpaces\Sdk\platform-tools

run flutter doctor in a new command prompt and the error should be fixed!!
