### ISSUE TITLE
[Impeller] dl dispatch culling still depends on canvas computed cull rects.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#155133]
In investigating https://github.com/flutter/flutter/issues/155104 I discovered that there is a performance regression on an application with a large amount of text. Most of this text is offscreen but contains unique glyphs. The regression is caused by us populating the glyph atlas with these unique glyphs even though they should be culled offscreen.

Some debug printing reveals that we are only rendering ~36 text frames but processing the unique glyphs of 286 text frames.

The rendering dispatcher is actually feeding the impeller cull rect back into the display list in DLDispatcher::drawDisplayList:

https://github.com/flutter/engine/blob/main/impeller/display_list/dl_dispatcher.cc#L1209-L1225

Whereas the text frame dispatcher (which collects glyphs) doesn't do so as it doesn't have that computed yet.

I don't think display list should need to rely on the impeller canvas cull rect - as this cull rect is ultimately derived directly from the information that dl provides. Can we handle nested DL dispatching automatically by plumbing through the correctly transformed cull rect?

FYI @flar

**Comment by jonahwilliams** [comment]
We could of course track the cull rect in multiple places, but its a bit weird imo because the dispatcher would just be re-doing the same work that is already happening in the display list.

**Comment by jonahwilliams** [comment]
So though, can we recurse into the sub display list in https://github.com/flutter/engine/blob/main/display_list/display_list.cc#L151 (provided that display list has an RTree?). Or does not dl culling not take saveLayer or clip state into account?

**Comment by jonahwilliams** [comment]
actually wait this is really the same problem that its hard to cull before we start culling! I think the right fix is to refactor things so its easier to reuse the cull rects in Impeller.

Think we can work around this for now.

**Comment by flar** [comment]
The TextFrameDispatcher doesn't track the clip bounds (I think?) like the regular DlDispatcher, but it could at least use the original cull_rect from the top level to cull the sub-display lists. That will at least prevent caching of off-screen glyphs. Remember that it needs to express the cull_rect in the transform under which the sub-DL is being dispatched.

Even better would be if it tracked the clip bounds as well (which should be a subset of the frame bounds), but just forwarding the frame bounds would be a big step up for this particular case.

If we eventually move to a 2-stage approach where the first stage analyses everything and collects info for rendering and then the second stage just invokes the rendering calls in the proper (re)order, the first stage would probably want to collect that clip info so that it can determine scissors to apply to the render-ops in the second stage. (TBD)
