### ISSUE TITLE
Beta installation bundles report unknown channel

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#15518]
## Steps to Reproduce

on macOS:

```
cd ~/tmp
curl https://storage.googleapis.com/flutter_infra/releases/beta/macos/flutter_macos_v0.1.5-beta.zip -o beta.zip
unzip beta.zip
./flutter/bin/flutter --version
```

=>

```
Flutter 0.1.5 • channel unknown • unknown source
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

**Comment by mit-mit** [comment]
@gspencergoog I still see this in the recent macOS beta:

https://storage.googleapis.com/flutter_infra/releases/beta/macos/flutter_macos_v0.2.3-beta.zip

```
mit-macbookpro2:tmp mit$ flutter --version
Flutter 0.2.3 • channel unknown • unknown source
```

**Comment by gspencergoog** [comment]
Actually, it is fixed, it's just that the fix hasn't made it into the beta channel yet: the packaging bots sync to the branch they are packaging, and use that script.

I think I'm going to have to change the packaging builds so that they checkout master instead of the dev or beta branch, but then build the package from the dev or beta branches, so that they're using the latest packaging script instead of the one on the branch.

**Comment by gspencergoog** [comment]
Here is that change: https://chromium-review.googlesource.com/c/chromium/tools/build/+/989404

**Comment by gspencergoog** [comment]
The change has been merged.  I'll re-run the beta packaging builds.
