### ISSUE TITLE
main.dart.js.map for the sample Flutter app has 37.3% of unmapped code

### ISSUE THREAD

**Issue by Devenik7** [flutter/flutter#155288]
### Steps to reproduce

1. Switch to master channel of Flutter
2. Create new Flutter Sample Project (The Clicker App from an IDE like VSCode)
3. Run `flutter build web --release --source-maps`
4. Run `source-map-explorer build/web/main.dart.js --no-border-checks`
5. Analyse the generated HTML

### Expected results

The entire main.dart.js should have been mapped

### Actual results

37.3% of the main.dart.js is unmapped

<img width="1791" alt="Screenshot 2024-09-17 at 3 34 44 PM" src="https://github.com/user-attachments/assets/1dd978cf-3cde-40dd-b09b-0abb615b82c8">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1791" alt="Screenshot 2024-09-17 at 3 34 44 PM" src="https://github.com/user-attachments/assets/1dd978cf-3cde-40dd-b09b-0abb615b82c8">

</details>

### Logs

<details open><summary>Logs</summary>

For the `flutter build web --release --source-maps`, the console output is,

```console
Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use
"{{flutter_service_worker_version}}" template token instead. See
https://docs.flutter.dev/platform-integration/web/initialization for more details.
Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. See
https://docs.flutter.dev/platform-integration/web/initialization for more details.
```

For the `source-map-explorer build/web/main.dart.js --no-border-checks` command, the console output is,

```console
build/web/main.dart.js
  Unable to map 554294/1486498 bytes (37.29%)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.26.0-1.0.pre.141, on macOS 14.0 23A344 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] VS Code (version 1.93.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
> * Run `flutter build web --release --source-maps`
> * Run `source-map-explorer build/web/main.dart.js --no-border-checks`

@Devenik7 Thanks for the report. Although I see that `main.dart.js` file is generated, but I am unable to run `source-map-explorer` command saying the command not found.  
Is there any other config needed to enable the said command ?

**Comment by Devenik7** [comment]
> > * Run `flutter build web --release --source-maps`
> > * Run `source-map-explorer build/web/main.dart.js --no-border-checks`
> 
> @Devenik7 Thanks for the report. Although I see that `main.dart.js` file is generated, but I am unable to run `source-map-explorer` command saying the command not found. Is there any other config needed to enable the said command ?

Apologies. Please install the extension from npm first.

Use this command

`npm install -g source-map-explorer`

**Comment by shubhang21** [comment]
facing similar issue for web, wanted to analyse maps to optimise part files

**Comment by chiku7665** [comment]
I encountered a similar issue with the web and aimed to analyze the maps to optimize the part files.

**Comment by BladeForerunner** [comment]
same problem here too and it would help if we could analyze the maps for optimization of partial files.

**Comment by darshankawar** [comment]
Thanks for the update. Seeing the same behavior as originally reported using the details provided. Verified on master version.

`Master : 3.26.0-1.0.pre.152`

**Comment by biggs0125** [comment]
It looks like you're trying to use these source maps to profile the code size impact of different parts of your program. Dart2js's  (the production Dart JS compiler) source map strategy isn't really designed for that use case. It's intended as an input to browsers to assist in debugging and stacktrace deobfuscation. It's not meant to "blame" every byte of the JS on a specific line of Dart.

Given that, this seems like it's WAI. That unmapped 37% is the JS glue code dart2js generates that isn't attached to any  executable Dart code. This might be tables of symbols, JS helper functions, or code to manage container objects. Some of these are a result of specific parts of your Dart code (e.g. the name of a static function), but they aren't part of the Dart code execution per-se so we don't map them.

That being said the part of the JS that *is* mapped should give you a rough estimate of the code size impact of various files in your program. It won't be perfect, but it will be an okay approximation.

As an alternative to using source maps, dart2js provides a separate mechanism called "dump-info". This is an additional json metadata file the compiler can produce that, among other things, provides more accurate JS code size estimates for every library, class, function, etc. Using this will be a more reliable way to estimate the code size impact of any given part of your code.

In testing this just now, I've noticed that the command to generate that metadata is broken. I have a PR open to fix this: https://github.com/flutter/flutter/pull/156187

Once the fix is available, if you run `flutter build web --dump-info`, the extra metadata will be generated at `.dart_tool/flutter_build/<build_id>/main.dart.js.info.json`.

The Dart SDK also provides a series of tools to process this info file programmatically:
https://github.com/dart-lang/sdk/tree/main/pkg/dart2js_info

**Comment by Devenik7** [comment]
Thanks @biggs0125. Will look into dump-info for more accurate blaming.

**Comment by nshahan** [comment]
No changes expected here so I'm closing this issue.
