### ISSUE TITLE
Platform adaptive `showAboutDialog` and `AboutDialog`

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#155269]
### Use case

My app runs on android and ios and is designed to look similar to it's platform's design structure. However when I use the `showAboutDialog` in my app it opens up a Material dialog on both platforms. There is no option to open a Cupertino like dialog to show the `AboutDialog`.

### Proposal

1. Update the existing widget and function
    Change the `showDialog` inside `showAboutDialog` to `showAdaptiveDialog`: https://github.com/flutter/flutter/blob/6d04a162109d07876230709adf4013db113b16a3/packages/flutter/lib/src/material/about.dart#L194
    
    Similarly change the `AlertDialog` inside `AboutDialog` to `AlertDialog.adaptive`: https://github.com/flutter/flutter/blob/6d04a162109d07876230709adf4013db113b16a3/packages/flutter/lib/src/material/about.dart#L329
    
    Would also need to add some conditional logic to use `CupertinoDialogAction` instead of `TextButton` on apple platforms: https://github.com/flutter/flutter/blob/6d04a162109d07876230709adf4013db113b16a3/packages/flutter/lib/src/material/about.dart#L354-L381

OR    

 2. Add a new function and widget like `showAdaptiveAboutDialog` and `AboutDialog.adaptive`

**Comment by thejitenpatel** [comment]
I raised PR #155377 for this issue. As I am new to Flutter contributions, I'd appreciate any help in reviewing my code. Additionally, the Linux analyze check failed due to the following error in packages/flutter/test/material/about_test.dart:584: 'skip test without a justification comment.'

The comment is already provided for skipping the test as per doc https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#skipped-tests

**Comment by victorsanni** [comment]
@OutdatedGuy I think this blocked by https://github.com/flutter/flutter/issues/57638.

**Comment by OutdatedGuy** [comment]
@victorsanni Doesn't this aligns with the proposal of #57638 ? I believe while filing #57638 the `showDialog` and `AlertDialog` did not consisted the `.adaptive` constructor.
