### ISSUE TITLE
Should .vscode folders be gitignored?

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#15555]
Currently the `.vscode` folder is in the `.gitignore` file (including some templates). There are a bunch of things that get stored in that folder that are useful to commit (for ex. [Dart Code has a bunch committed](https://github.com/Dart-Code/Dart-Code/tree/master/.vscode), including:

- Launch configs (useful for perssing F5 to launch)
- Recommended extensions
- Workspace-local settings (eg. formatting, trailing newlines, etc.)
- Task definitions

I know sometimes it's useful to put local paths into settings (eg. if using the SDK Switcher in Dart Code it'll do that) but probably those changes should just manually be ignored.

(I just noticed this repo even has its own files in that folder https://github.com/flutter/flutter/blob/master/.vscode/).

**Comment by xqwzts** [comment]
My two cents:

As a plugin/package publisher I have no control over what editor my users/contributors use, so any settings that the project depends on have to be editor agnostic [preferring `dartfmt` over workspace settings for example]. So `.vscode/` has to be considered as a user settings folder, and not something the project can rely on - which just makes it clutter to include in the repo.

With Dart Code it's a safe bet that anyone developing for it is doing so in VS Code, and since it's TS you don't get the dart/flutter tooling out of the box.

**Comment by DanTup** [comment]
I don't think that's a good argument against this. If you don't want `.vscode` in your repo, then you can add it to your `gitignore` or refuse PRs that add it (just like you would with any other random junk people committed). But this isn't some "temporary IDE folder" created by a build process, it's one that can store important parts of a project, including:

- Launch/Debug config (potentially complicated configuration - every person that checks a project out shouldn't need to re-create it)
- Settings (for example, I use it in Dart Code to force tab-indenting and trailing newlines)
- Recommended extensions (if you work on this project, you should be prompted to install these supporting extensions)

By gitignoring this in the template, there's a danger that people will not realise these things were not committed - the majority of what's in this folder probably wants to be shared with colleagues/contributors. Nobody wants to clone a repository and then be told they have to set up the debug configuration themselves.

If you don't gitignore it, then the files will show up when you come to commit, and you can make a call on whether to commit/gitignore them - that's a conscious decision.

> With Dart Code it's a safe bet that anyone developing for it is doing so in VS Code, and since it's TS you don't get the dart/flutter tooling out of the box.

I don't understand what this means; but this very repo (flutter/flutter) also has `.vscode` config committed and there's no requirement/consensus on using Code to developer it. Authors of a project should make this decision, not have it silently made for them without input.

**Comment by Hixie** [comment]
I don't have a strong opinion on this for the template, but we should be consistent and either ignore all IDE's configuration files, or none. Some IDEs write out things like window positions, and checking that in seems like a losing battle since not everyone will have the same window positions.

For the Flutter repo itself we don't want to check in any IDE files because we we use lots of IDEs differently configured, and it's annoying to have to remember to revert your config file each time.

**Comment by DanTup** [comment]
I agree that IDE junk (like window position) is reasonable to ignore by default; but VS Code doesn't write that sort of junk. This folder can contain critical things for running a project.

Project authors should get to decide. It's fair that you don't want it in the flutter repo and others may do the same, but at least if it's seen in the list of changes they can make that decision - if it's silently excluded they're not really making the decision.

(FWIW, VS Code supports workspace-level config that can be stored in a workspace file outside of the folder; so if someone wants to have special settings, they can easily do it in a way that they don't need to revert or exclude :-))

**Comment by NathanaelA** [comment]
@DanTup - I agree with Ian and Victor here, the IDE settings should continue to be excluded by default.  

You can say the same things about intellj based editors; some of the files are window locations; but other contains the start commands and other "important" information for how to run the project from inside IntelliJ or Android Studio.   (Name the editor, and it probably has the same thing)         In all reality any of that information should be documented in the docs, not in some config file in a editor....      

In addition this adds another source of easy to generate merge conflicts; if Victor updates X and I update Y in my editor; then we now have merge conflicts because of the stupid editor; and are wasting time on something we shouldn't be.  ;-)    They just end up being additional maintenance work.

**Comment by Hixie** [comment]
One argument for not ignoring the IDE settings is that there's a giant list of IDE setting files that we could ignore, and calling out a few specific IDEs as needing ignoring seems weird. For example, why aren't you ignoring the files that my home-grown IDE uses?

I don't think we should do anything different for .vscode files than any other IDE's files, whether that means including or excluding.

What might make sense is for Flutter to come up with a general IDE-agnostic configuration file (maybe using pubspec.yaml). If there is information that is in the .vscode file that is useful to environments other than VSC, can we put it in pubspec.yaml?

**Comment by DanTup** [comment]
> In addition this adds another source of easy to generate merge conflicts; if Victor updates X and I update Y in my editor; then we now have merge conflicts because of the stupid editor

I'm not saying you should commit the files. I'm suggesting they should be left for the project author to make a decision about. Ignoring them hides them. Not ignoring them makes them visible. The decision should be a conscious one made by the person who owns the project, not by the person building the template.

IMO the only things that belong in the gitignore of a *template* project are the ones that are clearly useless junk (logs, build artifacts, temp files, etc.). Anything above that should be handled by the user. Template authors shouldn't try to guess - devs all have their own preferences on what's in their projects gitignore - you'll never come up with something that fits everyone so just include things that are not controversial.

>  If there is information that is in the .vscode file that is useful to environments other than VSC, can we put it in pubspec.yaml?

The things that go in `.vscode` are handled by Code, so we can't change them in any way. In my example, I didn't mean non-Code config, but rather that the info in there may be useful for non-Code users (eg. you clone a project, can't figure out how to run it, eg. what flags, what script to run, whatever - thent he proejct owners `launch.json` might be really useful). Also, if the project author has specific style guides (tabs, spaces, line length, whatever) those may be committed in the folders settings as a convenience for others that do use Code.

Again, I'm not saying we should be telling people to include this, I'm suggesting we don't have a stance on it - leave it for the project author. It seems weird to second-guess what they'll want.

Another way of looking at it... How many people will be annoyed if you excluded files that had data they considered important (launch configs, settings, recommended extensions) versus how many will be annoyed if you just didn't exclude a folder by default?

**Comment by xqwzts** [comment]
> IMO the only things that belong in the gitignore of a template project are the ones that are clearly useless junk (logs, build artifacts, temp files, etc.)

This helped me realize your POV, the template should only be ignoring files that would otherwise be generated by flutter/flutter-related tooling in the first place.

In which case none of the IDE folders should be included in the gitignore templates.

**Comment by Hixie** [comment]
> In which case none of the IDE folders should be included in the gitignore templates.

I would be fine with that for the templates.

**Comment by zoechi** [comment]
I think it was a discussion in the Dart SDK repo recently where someone argued that IDE files should be ignored by the user globally and not per repository. I found that a compelling argument.

**Comment by DanTup** [comment]
I used to do that - I had a big global ignore list for Mercurial and Git. However, I found that when someone checked out my project they would find all this junk appearing in their commit list and either be annoyed that I hadn't set up an ignore file, or they would just start adding stuff to one in the repo anyway.

I think it's reasonable to expect a project to contain a gitignore for things that the author doesn't want committed (and if they don't want the `.vscode` folder then they should add it); I just don't think it's reasonable for templates to exclude non-junk files by default.

Although I think the "don't ignore any IDE files" is a reasonable solution here, I still think it's wrong to lump the `.vscode` folder in the same category as temporary/junk files from an IDE like window position. Nothing of that sort goes into `vscode`, only things the user has explicitly set up and configured.

**Comment by NathanaelA** [comment]
I understand Dan's argument; I tend to go the other way because when new people start working with the project they "assume" that the defaults are sane.   And so by default they will be including all the junk files.

A chunk of .vscode settings is mostly pointless for someone else as the path's will be wrong for running things; and I could care less if you prefer tabs vs spaces.   :grinning:    If they use Android Studio then you have the same mix of stuff in the repo that just wastes bandwidth. 

When your internet is super dog slow; all this extra crap is beyond annoying; and very noticeable.   (Trust me, I have some really crappy internet and I do notice these files when I checkout repos and it takes me an extra 5 minutes because of crap that adds no value to the project)

For those power users who really want to add .vscode; even if it is in the .gitignore it doesn't prevent you from adding it manually.    But I do think the sane defaults are to exclude unneeded files to actually run the project; which is the editor files.

**Comment by DanTup** [comment]
> I tend to go the other way because when new people start working with the project they "assume" that the defaults are sane

I think people are misunderstanding what I'm saying. I'm not saying *you* shouldn't add it to the ignore file of *your* project, I'm saying that it shouldn't be thrust upon everyone silently as the default. If you create a Flutter project and don't want vscode then you can add it to your ignore file before people contribute and you'll never have to deal with it. Thing is, you need to deal with weeding out junk files in a PR anyway (you can't possibly exclude all the possible junk people will try to commit, like random log files `Copy of xxx.dart` files) so it's not like you're going to accidentally end up with stuff you don't want.

Neither default is going to keep everyone happy, but IMO not excluding valuable files is safer than not. People don't expect a default ignore file to exclude non-junk/temporary files, and .vscode is almost all non-junk.

(Also, the current templates are stuffed with IntelliJ files and a `.idea` folder I don't want ;-))

**Comment by NathanaelA** [comment]
Dan, 

   We are probably going around in circles now.  :grinning:        If you don't exclude them by default; then  by default they will show up in most projects (where they don't need to be) and they (imho) are pointless (and that goes for the `.idea` folder too!)     

You are correct we will get other garbage in the projects; nothing we can do about that; but what we can do is eliminate a couple known sources of waste (.vscode, .idea, etc)...   :grinning:

But I fully understand what you are saying; you dislike that by default it excludes folders you might want to include in YOUR projects.   I agree that it does seem very opinionated.  :grinning:    I just tend to think that in the vast majority of cases it is probably wiser to set the defaults to ignore it and keep the repos smaller and cleaner.    And those power users that do know what they are doing and really feel strongly about including .idea or .vscode into their repos.   They can easily either remove the line from .gitignore and/or just do a `git add` of the folder specifically...

**Comment by DanTup** [comment]
This was dealt with by #15382. The conclusion was to not put IDE-specific files/folders into the ignore file.
