### ISSUE TITLE
Decide on a path to stop stripping `libapp.so` and `libflutter.so` by default for android builds

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#155576]
Context https://github.com/flutter/flutter/issues/60240.

We currently strip debug symbols when [building the the AOT snapshot](https://github.com/flutter/flutter/blob/bd909542a33ab1d5249363a2434ae50ee468094f/packages/flutter_tools/lib/src/base/build.dart#L146) and when [building the engine](https://github.com/flutter/engine/blob/ba4d39ad3cda8f2a81425a3f1a4c4157d8380bc5/tools/gn#L1113). This means that when Flutter developers build an appbundle (`flutter build appbundle`) these debug symbols are not available to the Android Gradle plugin (AGP), and therefore they obviously can't be included in the appbundle, which results in the warning in the play store that we see in the linked issue.

Since AGP 4.1, AGP itself can handle both stripping the debug symbols from the native code, and automatically including it in the appbundle in a way that is available to app stores, but does not get delivered to end users* (see https://support.google.com/googleplay/android-developer/answer/9848633#upload_file). So ideally, we could simply stop stripping these files when building for Android, and instead let AGP handle the debug symbols.

HOWEVER - the Flutter Gradle plugin has for some time now vended a recommended version of the NDK (`flutter.ndkVersion`) that we use to specify the `ndkVersion` property in apps gradle files, and _importantly_, if an app specifies an ndk version, and doesn't have that ndk version installed locally, **the app will build but silently fail to strip the debug symbols**, meaning that they end up in the final app (greatly inflating the app size).

So before we can stop stripping the debug symbols from these files by default, we need to decide on a path that ensures we don't create a foot gun where developers build, unaware that they don't have the ndk version they are specifying installed, and end up with unnecessarily large apps.

In my mind there are two main options, but other suggestions are welcome:
1. Get rid of `flutter.ndkVersion` entirely via a migrator. If users don't specify an ndk version, apps will instead use the default version provided by AGP. This is option two in this [section of the android docs](https://developer.android.com/studio/projects/configure-agp-ndk#agp_version_41) - AGP will download the version by default. There is also a community issue [suggesting we do this](https://github.com/flutter/flutter/issues/139427).
2. Keep `flutter.ndkVersion` around, and instead modify the flutter tool/flutter doctor to ensure that we check/enforce that users have the version of the ndk that we specify installed.

\* More specifically, the symbols get stripped and included in a `BUNDLE-METADATA` subdirectory of the [app bundle format](https://developer.android.com/guide/app-bundle/app-bundle-format), see [this comment](https://github.com/flutter/engine/pull/50443#issuecomment-1932863940) for more details.

**Comment by AbdeMohlbi** [comment]
What does happen when some used  plugins have a newer version then flutter.ndkversion inside gradle files ? Does the build fail in this case? No conflicts?

**Comment by gmackall** [comment]
Potentially, for 1, write a migrator that instead of removing the line, replaces `flutter.ndkVersion` with AGPs variable that holds their preferred ndk version, if such a variable exists

**Comment by Sameri11** [comment]
I personally don't really like first option because, in my opinion, there should be 1 source of truth for things like that. At least because there are already warnings in android builds, alarming about different versions of NDK in plugins and app ([example](https://github.com/flutter/flutter/issues/156111#issuecomment-2390641254)). Although I do not think that this warning is fixable only by specifying NDK version (it doesn't work already lol), I think that relying on standard AGP mechanism for NDK downloading is another step back from avoiding this kind of problems.

Plus, I believe that another teams on a path of solving similar problem, for example #144530 

I think it would be create doctor validator and, to enforce, Gradle's warning for debug/profile and error for release builds respectfully, if there's no needed ndk version found.

**Comment by gmackall** [comment]
Still no decision has been made, but adding some more info that according to my local testing and some internal info, apparently AGP will automatically download the NDK for every use case _except_ for when it is needed for stripping debug symbols from prebuilt libraries. 

So we can't rely on AGP to guarantee the availability of the NDK.

**Comment by AbdeMohlbi** [comment]
> Still no decision has been made, but adding some more info that according to my local testing and some internal info, apparently AGP will automatically download the NDK for every use case _except_ for when it is needed for stripping debug symbols from prebuilt libraries. 
> 
> So we can't rely on AGP to guarantee the availability of the NDK.

If i recall correctly it's not that hard to know the ndk versions installed on a machine the problem is are they compatible ? 
for instance if u opened a fresh project and add sharedPrefernces or some other package when running the app it will prompt that this project require newer ndk version for exemple 27 and flutter.ndkVersion is 26 , so some users may find it kinda deceiving
