### ISSUE TITLE
Android keyboard popup lag

### ISSUE THREAD

**Issue by no-chili** [flutter/flutter#155587]
### Steps to reproduce

The keyboard popup animation on Android devices is very choppy. Is there a way to fix this?

### Actual results

The keyboard appearance on Android devices is visibly dropping frames.

### Flutter Doctor output

...

**Comment by huycozy** [comment]
Hi @no-chili 
Please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Due to the lack of sufficient details, I will be closing this case. It is advisable to open a new issue for better monitoring. Thanks!
