### ISSUE TITLE
`InputDecoration.errorMaxLines`'s documentation does not match behavior

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#155626]
### Steps to reproduce

1. Use a `TextField`
2. Add `errorText`
3. Don't define `errorMaxLines` in `TextField.decoration`

### Expected results

Not providing a value will wrap the error text by default.

### Actual results

Error text is truncated.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: const HomePage(),
    ),
  );
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: TextField(
            decoration: InputDecoration(
              errorText: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/70003751-768c-4b09-b110-9111d3d4f48a)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.26.0-1.0.pre.170, on Void Linux 6.6.51_1, locale en_US.UTF-8)
    • Flutter version 3.26.0-1.0.pre.170 on channel master at $HOME/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 38105edec4 (4 days ago), 2024-09-20 13:04:24 -0400
    • Engine revision 76b7abb5c8
    • Dart version 3.6.0 (build 3.6.0-269.0.dev)
    • DevTools version 2.40.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at $HOME/.local/lib/android-sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: $HOME/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.30.1
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2024.1)
    • Android Studio at $HOME/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at $HOME/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Void Linux 6.6.51_1
    • Chrome (web)    • chrome • web-javascript • Chromium 129.0.6668.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
I see the `errorText` is `TextOverflow.ellipsis` by default:

https://github.com/flutter/flutter/blob/e0ca1946601dd7c0aafe3301f6d06ff03c860669/packages/flutter/lib/src/material/input_decorator.dart#L447

On the linked PR https://github.com/flutter/flutter/pull/147409, I see the `errorMaxLines` docs is changed:

From:
>/// Defaults to null, which means that the [errorText] will be limited
  /// to a single line with [TextOverflow.ellipsis].

To:
> /// Defaults to null, which means that the [errorText] is not limited.

Flutter versions:
```
Channel stable, 3.24.3
Channel master, 3.26.0-1.0.pre.200
```


/cc @bleroux for thoughts

**Comment by justinmc** [comment]
My attempt:

Defaults to null, which means that soft line breaks in [errorText] are truncated with an ellipse while hard line breaks are respected. For example, an [errorText] that overflows the width of the field will be truncated with an ellipse. However, an [errorText] with explicit linebreak characters (`\n`) will display on multiple lines.

**Comment by bleroux** [comment]
> How would someone in this instance make the errorText wrap always? (aside from explicitly setting maxLines)

Good question, the answer is that there is no other solution than setting `maxLines` because `errorText` overflow behavior is hardcoded to `TextOverflow.ellipsis`:

https://github.com/flutter/flutter/blob/e0ca1946601dd7c0aafe3301f6d06ff03c860669/packages/flutter/lib/src/material/input_decorator.dart#L447 

The hardcoded overflow is there since... almost forever :smile: : see https://github.com/flutter/flutter/pull/13734

https://github.com/flutter/flutter/pull/147409 was only a documentation change. 

I don't think we should introduce an `errorTextOverflow` property, because:
- there are already so many properties (and we will also have to introduce helperTextOverflow). And then it will open the door to errorTextAlign or maybe other properties.
- `InputDecorator.errorText` is just a handy alternative to `InputDecorator.error` which offers more flexibility, for instance it can be set to a Text widget with a specific overflow value.

If we agree to not add such a parameter, what do you think of mentioning that 'always wrap' can be achieved by setting errorMaxLines? (problem is that there is no exact value to advice for, it should just be higher enough, and 'higher enough' depends on the particular errorText and the minimum width of a particular text field).

**Comment by bleroux** [comment]
Based on our discussions, I filed https://github.com/flutter/flutter/pull/156468
