### ISSUE TITLE
Mojo services cannot be used before `runApp` in `main()`

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#1556]
Workaround is to initialize the `MojoShell` instance by calling `WidgetFlutterBinding.ensureInitialized();`

**Comment by chinmaygarde** [comment]
cc @jason-simmons @Hixie: I am patching the game that depends on this. You may close this ticket is this behavior is as intended.

**Comment by Hixie** [comment]
This is intentional. It's so that we can coordinate the registration of services provided by various bindings with the hooking up of our end of the mojo ServiceProvider. Otherwise, there's a theoretical race between when our ServiceProvider has all our services registered and when the app starts receiving requests for them from the embedder.

I think we should probably change the game to start trying to draw pixels sooner, rather than it waiting until all its resources are loaded. We shouldn't have to block showing pixels on whether the sounds are loaded, for example.

**Comment by Hixie** [comment]
This comes up regularly, so we should make sure the various places that can fail because of this suggest the solution in their error message.

**Comment by Hixie** [comment]
No longer applicable.
