### ISSUE TITLE
[Proposal] Date AND time DateFormat in ARB files DateTime placeholders format

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#155817]
There are date formats in [`DateFormat`](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html), like [`yMMMMd`](https://pub.dev/documentation/intl/latest/intl/DateFormat/DateFormat.yMMMMd.html), and time formats like [`jms`](https://pub.dev/documentation/intl/latest/intl/DateFormat/DateFormat.jms.html). If we want to have a `DateFormat` that formats both the date and time, we use a method like so: `DateFormat.yMMMMd(...).add_jms()`.

But we can't take advantage of that in ARB placeholders for `DateTime`. The valid values for the `format` are only:

https://github.com/flutter/flutter/blob/9be22b58c4bfe8b6cb447de13a500db4e1bd8c33/packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart#L31-L73

Because of this, we need to accept two placeholders into a string and stick them together manually and pass the same variable in the code, which is not ideal. The `DateFormat` can handle this.

I propose adding the support for adding parts of the date formats in the ARB file using these `add_x()` methods in DateFormat.

## What we need to do now

```json
{
    "bookingsPage_camo_dataLoaded": "CAMO data from {date} {time}.",
    "@bookingsPage_camo_dataLoaded": {
        "placeholders": {
            "date": {
                "type": "DateTime",
                "format": "yMMMd"
            },
            "time": {
                "type": "DateTime",
                "format": "jm"
            }
        }
    },
}
```

## What I'm proposing

```json
{
    "bookingsPage_camo_dataLoaded": "CAMO data from {date}.",
    "@bookingsPage_camo_dataLoaded": {
        "placeholders": {
            "date": {
                "type": "DateTime",
                "format": "yMMMd+jm"
            }
        }
    },
}
```

The syntax is just an idea from the top of my head. We could split the format with some glueing character (like the `+`) and add the n+1 formats with the `add_x()` to the `DateFormat` in the generated Dart code. This would even work for glueing more pieces, like `

```dart
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

void main() {
  initializeDateFormatting('en');
  final format1 = DateFormat.yMMMMd('en').add_jms().add_QQQQ();
  print(format1.format(DateTime.now()));
  // September 27, 2024 1:06:01 PM 3rd quarter

  final format2 = DateFormat.yMMMMd('en').add_QQQQ().add_jms();
  print(format2.format(DateTime.now()));
  // September 27, 2024 3rd quarter 1:06:01 PM
}

```

**Comment by Albert221** [comment]
@darshankawar if the Flutter team says we want this, I might be able to find some time to develop this. Whom and when could we ask/mention for that? :)

**Comment by darshankawar** [comment]
> Whom and when could we ask/mention for that? :)

@Albert221 You may ask this in flutter's discord channel `hackers-tools` to get feedback on it.

**Comment by andrewkolos** [comment]
Hiya, sorry for the silence on the Discord thread.

I do think this would be a useful feature, and something worth further consideration. I like the idea of the proposal, though I have one hesitation.

The `+` character is already valid in a date format string. As an example, consider:

```dart
final myDateFormat = DateFormat(' yMMMMd++');
print(myDateFormat.format(DateTime.now())); // prints "2024October2++"
```

However, in this proposal, `+` would have a different meaning in the context of date formats in arb files, which could theoretically confuse users.

That being said, I am not aware of any date formats in the world that use `+`, and I cannot think of a better alternative to this proposal myself. With this in mind, I think this concern is fine to ignore.

I'd be willing to review a PR for this (assuming it meets the contributor guidelines—high test coverage would be especially important since we would have more complex parsing logic compared to the current simple [fixed list](https://github.com/flutter/flutter/blob/9be22b58c4bfe8b6cb447de13a500db4e1bd8c33/packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart#L31-L73)). However, if the parsing/code-gen logic ends up being very complex, I may up rejecting the PR for the sake of not introducing too much more maintenance burden into the flutter tool.
