### ISSUE TITLE
Flutter can't run in XCode 16.0

### ISSUE THREAD

**Issue by jjvu-xiao** [flutter/flutter#155905]
### Steps to reproduce

Flutter can't run in XCode 16.0

### Expected results

Command PhaseScriptExecution failed with a nonzero exit code

### Actual results

Command PhaseScriptExecution failed with a nonzero exit code

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

![Uploading flutter-error.png…]()

### Flutter Doctor output

![Uploading flutter-error.png…]()

**Comment by jjvu-xiao** [comment]
![flutter-error](https://github.com/user-attachments/assets/97a5490f-238e-4865-b964-93e11e6172a6)

**Comment by jjvu-xiao** [comment]
I need help
![image](https://github.com/user-attachments/assets/bf0d943f-65f8-4066-a901-f66069a2ce00)

**Comment by mafreud** [comment]
@jjvu-xiao If it is not necessary to use Xcode 16, please install a previous version of Xcode using Xcode or a similar application and try building it.

**Comment by jjvu-xiao** [comment]
This issue will only appear in XCode 16. Our project was previously packaged in the AppStore on XCode 13,14, and 15. Due to code issues, we are temporarily unable to migrate to the latest version of Flutter

**Comment by huycozy** [comment]
Hi @jjvu-xiao 
When opening an issue, please try to provide all proper information indicated in the template so that we can address the issue correctly.

I see you are using very old Flutter version, please try upgrading Flutter SDK to the latest 3.24.3 to see if the issue persists or not. 

And please provide the output of `flutter run -v` which may contain the error trace for us to investigate further (The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it)

_Please provide the information (flutter doctor, flutter run output) in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text)._

**Comment by chenfanfang** [comment]
@huycozy Hello, I have the same problem. You can use Xcode16 Flutter 2.10.5 version. The Debug compilation of the created project will definitely have this problem, but the release package will not have any problem. For some reasons, I cannot upgrade the Flutter version for the time being. Please tell me how to modify it so that I can debug the iOS project normally.

**Comment by chenfanfang** [comment]
https://github.com/flutter/flutter/issues/156556

**Comment by huycozy** [comment]
> #156556

This has been responded at https://github.com/flutter/flutter/issues/156556#issuecomment-2406687488.
