### ISSUE TITLE
[monorepo] ensure CUJs are covered for all user personas that interact with repo code

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#156027]
We have three user personas that interact with the source in our repos. We should make sure their CUJs are covered by the upcoming monorepo design. Personas:

- **App developer**: interacts with the repo code with intent to build an app. The barrier to entry for app developers must remain low. In particular, we should not require that app developers build the engine locally.
- **Framework contributor**: clones the repo intending to hack on the Flutter framework only, and does not change engine code. This sometimes includes app developers who, as part of hacking on an app, would change the framework source code to debug something, e.g. add an extra `print` statement to see what's going on inside the framework.
- **Full-stack contributor**: clones the repo intending to hack on the engine and/or the framework. The dev process requires locally built engine and framework.

One failure mode to watch out for is the tool accidentally picking a wrong engine build. E.g. you think you tested your engine changes, but actually while debugging the app the tool accidentally grabbed a pre-built engine.

One use-case for full-stack contributors that does not exist for others is [A/B testing](https://github.com/flutter/flutter/blob/ceb3a4a5c062d6f1ea61e1e887ac5ef58223be25/dev/devicelab/bin/run.dart#L89). It would be good to preserve this capability.

**Comment by jtmcdole** [comment]
I think we can break this down a bit more for crispness:

  CUJ: App Developer using a release branch (Stable / Beta)
  CUJ: App Developer using tip of tree

For app developers using a release branch, we still intend on having `engine.version` signal what engine should be downloaded.

For app developers on tip of tree; the current thinking is they follow the same hashing strategy used to identify the engine builds. This could be `git ls-files --format='%(objectname) %(path)' engine/ DEPS  | sha1sum` or something more complex. The hashing function will be stored in the tree.

For Framework developers; it's the same as the above.  You change the framework should not change the way we identify the engine build.

For an engine developer, they should be using `et run` for local builds. This sets some flags to `flutter run` that locate the local build.

For AB testing; you're required to pass in the local engine flags. The calculation of the engine binary using `git ls-files` would include files that the developer has modified and committed locally to their tree, and thus, no previous binaries exist except for the locals.  In this world we could find the nearest common ancestor, so `git merge-base HEAD master`, so something like:

```
❯ git ls-tree 0036cef88bb0723443d3948bdd63af410fd2737c -r engine/ DEPS | grep engine/src/flutter/README.md
100644 blob e15957a520eaee19b97b7d15df6d50bb175806b2	engine/src/flutter/README.md
 ❯ git ls-tree HEAD -r engine/ DEPS | grep engine/src/flutter/README.md
100644 blob 0bd9494f6607f2772f6781883549ec483af1d30d	engine/src/flutter/README.md
```

This requires git ls-tree instead of ls-files since we want to operate on the tree.

**Comment by yjbanov** [comment]
I'm convinced that all the CUJs are covered. Closing.
