### ISSUE TITLE
[google_sign_in] Support custom app icons, currently crashes the app.

### ISSUE THREAD

**Issue by codyfilatov** [flutter/flutter#156168]
### Use case

Currently having a custom app icon will cause the app to crash. Support for this would be great.

### Proposal

Since custom app icons requires using a different activity, on Android this will cause an app crash. Please support this.

**Comment by danagbemava-nc** [comment]
Hi @codyfilatov, it's not clear what exactly it is you're requesting. It would help if you could provide details on the error you get and how it relates to the `google_sign_in` package. Also providing steps to reproduce would be very helpful along with the version of `google_sign_in` you're experiencing the issue with. 

Thank you

**Comment by mandoman101** [comment]
I am also having this problem with running a custom app icon. I'm currently running my app in Android Studio using flutter and I am trying to add a custom app icon using the flutter_launcher_icons 0.14.1 dependencies. I am 100% sure all my file paths are correct and the app icon is sized to 512px by 512px. When I run debug mode the app crashes and the app icon displays black. 

this is my pubspec.yaml  looks like. Any help would be greatly appreciated. thank you

name: mandoman
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/mandoman_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon/mandoman_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon/mandoman_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon/mandoman_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo_green.png
    - assets/images/icon/mandoman_icon.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

**Comment by codyfilatov** [comment]
> Hi @codyfilatov, it's not clear what exactly it is you're requesting. It would help if you could provide details on the error you get and how it relates to the `google_sign_in` package. Also providing steps to reproduce would be very helpful along with the version of `google_sign_in` you're experiencing the issue with.
> 
> Thank you

Hey sorry, I don't know how to illustrate this with my code.

To change an app's icon dynamically you need to define multiple activities in the AndroidManifest.xml. Switch between them, and restart the app. This is a common tactic to do this, and is the recommended way to have dynamic app icons. Such as in libraries like https://pub.dev/packages/flutter_dynamic_icon_plus

Although, google_sign_in does not cooperate with this. When launching the Google Sign In when the app icon is customized. The app crashes.

**Comment by iftakher36** [comment]
I am also facing this issue. The problem is not related to Google Sign-In. I am using Crisp Chat and a payment method service (SSL Service in my country). When opening Crisp, the payment activity, or Google Sign-In, it transitions to a different activity. During this time, the app changes the dynamic icon, which is causing the app to crash.

**Comment by danagbemava-nc** [comment]
Hi @codyfilatov, can you share the crash message?
