### ISSUE TITLE
Define the order of dependencies in Flutter apps in the same way as android `build.gradle` file

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#156145]
Documentation: https://developer.android.com/build/dependencies#dependency-order

Why I ask this question? Because the above doc link states an important note:
> This order is important in the event that [resources are merged](https://developer.android.com/studio/write/add-resources#resource_merging) or [manifest elements are merged](https://developer.android.com/studio/build/manage-manifests#merge-manifests) into your app from the libraries.

### CASE: A Flutter Plugin which has used tools:node="remove"

1. [camera plugin](https://pub.dev/packages/camera)
This plugin explicitly removes the `READ_EXTERNAL_STORAGE`:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
    tools:node="remove" />
```
2. [file_picker plugin](https://pub.dev/packages/file_picker)
This plugin requires the `READ_EXTERNAL_STORAGE`:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
```

### After building the Flutter app:
The manifest merger logs states that file_picker permission was rejected:
```
uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:17:5-19:31
REJECTED from [:file_picker] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/file_picker/intermediates/merged_manifest/debug/AndroidManifest.xml:9:5-11:38
	tools:node
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:19:9-28
	android:name
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:18:9-64
```

### Query:
So how do I state in Flutter that file_picker plugin must have the higher priority?
Do I have to define this inside the pubspec.yaml file?

Please let me know if I am missing something here.

**Comment by huycozy** [comment]
As far as I can see, there doesn't seem to be a solution for this in Flutter currently. Could this be related to https://github.com/flutter/flutter/issues/99153? Marking this as a feature request to gather input from others.

**Comment by gnprice** [comment]
I think this would be a complicated feature to design an API for, and it probably wouldn't end up being a very effective solution for the use case.

Fundamentally, the order between two plugins shouldn't matter. If it does, that's probably a bug in one or both plugins and should be fixed in the plugins upstream. I think it's not a common class of bug, and that makes it an unappealing target for a feature that would add complexity to plugin management for everyone.

In fact it looks like that's already what's happened with the example above — `camera_android_camerax` has been fixed so that it no longer removes `READ_EXTERNAL_STORAGE`:
* https://github.com/flutter/flutter/issues/156198
* https://github.com/flutter/packages/pull/7826

---

Then whenever two plugins do have such a conflict and it hasn't yet been fixed (or there's some reason why it won't be fixed) so that one needs to work around it, there's already a good way to handle that: whatever outcome you want your manifest to reflect, just put that outcome explicitly in your app's own AndroidManifest.xml source file. Your app's own manifest file always has the final say, so you can always get whatever result you want, regardless of what the plugins are doing.

In the example above, that means you might write:
```xml
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
    android:maxSdkVersion="32"/>
```

I think that'll usually be cleaner than trying to specify a priority order between the plugins (even supposing we had an API for that), because it's a lot more explicit about what you actually want to happen. This solution also generalizes to any undesired effect a plugin is having on your manifest, even when it's not an interaction with some other plugin.

And conversely this way isn't any more complicated. In the issue's original example, it's two lines of code. In general, each item a plugin might add to an Android manifest tends to be pretty small.

**Comment by camsim99** [comment]
@bartekpacia thank you for the very thoughtful response! I agree that attempting to address this is not as effective as fixing the plugins/the app's manifest itself.

@rohansohonee1 does [his comment](https://github.com/flutter/flutter/issues/156145#issuecomment-2415812129) address your concerns? I think we are best moving forward without implementing this feature.

**Comment by bartekpacia** [comment]
hey @camsim99, I think you meant @gnprice 😅

**Comment by camsim99** [comment]
Omg @bartekpacia so sorry yes I did 😭 was reading many comments this morning! Thanks for pointing that out!
