### ISSUE TITLE
How to show the SnackBar from top of the screen , like push notification does?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15679]
Sometimes we want to show the SnackBar from top of the screen ,how ?

**Comment by HansMuller** [comment]
The Flutter snackbar support appearing at the top of the screen because the Material Design spec only has it at the bottom: https://spec.googleplex.com/m2-component-motion/m2-component-motion/baseline-motion.html#

You could create a snackbar-esque widget that was stacked on top of the Scaffold's body and located wherever you like.

**Comment by zoechi** [comment]
@realcarlos could you solve your requirements with the provided information.
Can this issue be closed?

Perhaps one of the packages
https://pub.dartlang.org/packages/flutter_local_notifications
https://pub.dartlang.org/packages/local_notifications
https://pub.dartlang.org/packages/schedule_notifications
provides what you are looking for

**Comment by kf6gpe** [comment]
Gently closing due to lack of feedback from @realcarlos  --- please reopen if the provided information and @zoechi's package suggestions don't help. Thanks!

**Comment by quetool** [comment]
Hi, @zoechi suggestions doesn't work for me, I don't use any local notification, I am using firebase_messaging and I need to show some sort of snackbar from the top.

**Comment by patelkrunal78** [comment]
There’s three problems. The first is that you don’t have a Scaffold anywhere, and the Scaffold widget is the one that knows how to show snack bars. The second is that you have a key for getting a hold of the scaffold, but you’ve put it on a Padding instead (and Paddings don’t have any knowledge of snack bars). The third is that you’ve used the key before the widget that it’s associated with has had a chance to be initialised, since initState is called before build.

https://icetutor.com/question/display-snackbar-in-flutter

**Comment by lucasarrudadev** [comment]
> I think I will try this one https://pub.dartlang.org/packages/flushbar

Did it worked for you when I try to use it in my project get the following error:

"Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:303:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:311:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();"


I just imported it and tryed to use inside a function as :

"Flushbar(
        message: "Limite de 5 Usuários",
        icon: Icon(
          Icons.info_outline,
          size: 28.0,
          color: Colors.blue[300],
        ),
        duration: Duration(seconds: 3),
        leftBarIndicatorColor: Colors.blue[300],
      )..show(context);"
