### ISSUE TITLE
Facing Crash Issue in IOS devices

### ISSUE THREAD

**Issue by Mohammedomer20610** [flutter/flutter#156815]
Hi Team,

I have almost finished the application development. Most of the time what I am seeing is application got slow down if the users are trying to use the many features of the application. And some times it got stuck for very long time and I need to close and re-open the again to run it very smoothly.

I have checked many blogs regarding this and tried many error identification tools like Sentry and fixed all of the sentry issues. But still the application is bit sluggish.

Please let me know what are the details you need it to review and provide few suggestions.

Thanks.

**Comment by huycozy** [comment]
Hi @Mohammedomer20610 
The goal of this GitHub repo is not to assist in personal code or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please file a new issue (select the appropriate issue template here https://github.com/flutter/flutter/issues/new/choose) and fill all information indicated in the template.

Instead, if you think that the issue might depend on your implementation, please see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well.

Closing this issue because it lacks the necessary information to proceed.
