### ISSUE TITLE
Passing Data to Flutter Widget through iOS 

### ISSUE THREAD

**Issue by Shafran123** [flutter/flutter#156813]
```swift
guard let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine,
  let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil) else {
    return nil
}

addChild(flutterViewController)
flutterViewController.view.translatesAutoresizingMaskIntoConstraints = false

guard let flutterView = flutterViewController.view else { return }

flutterView.translatesAutoresizingMaskIntoConstraints = false

view.addSubview(flutterView)

let constraints = [
    flutterView.topAnchor.constraint(equalTo: view.topAnchor),
    flutterView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
    flutterView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
    flutterView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
]

NSLayoutConstraint.activate(constraints)

flutterViewController.didMove(toParent: self)
flutterView.layoutIfNeeded()
```

_Originally posted by @ahusseini in https://github.com/flutter/flutter/issues/30183#issuecomment-501465821_
            
            
            
            
Im using this approach to render flutter in my application. I want to know how can use FlutterMethodChannel with this approach

**Comment by darshankawar** [comment]
@Shafran123 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Also, as a note, please don't use comments from other issues to file new issue. Try to use new issue template, fill out requested details so that we can properly address it.
The linked comment is from a very old issue, so it is not feasible / practical to go through it to answer your question.
Closing.
