### ISSUE TITLE
How to use table of content?

### ISSUE THREAD

**Issue by function2000** [flutter/flutter#156935]
### Use case

I get content data from server, it is list of map, I want to show it as markdown table.  I am not sure if I need to combine all data as a long string, and give some special characters like '\n' or '\br' or blank to make it as new line.  Please guide.  Thanks!

### Proposal

to make it possible to show the markdown table from table of content.   Thanks!

**Comment by huycozy** [comment]
Hi @function2000 
From my perspective, you should check markdown table format at https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables. Format your data to ensure that it can be easily inserted, and then use the [flutter_markdown](https://pub.dev/packages/flutter_markdown) or other packages on pub.dev to display it.

Since you are asking for assistance on personal code, please see https://flutter.dev/community for resources and ask questions like this. You may also get some help if you post it on Stack Overflow as well. 

Closing from here as this is more of a `how-to` question rather than a valid feature request or proposal for Flutter framework or 1st party packages.

**Comment by function2000** [comment]
I know the markdown format for table, but it is static.  I have a json encoded string, I want to make it also show as markdown table, the question is, which separater should be used to identify it is a new line, like  '\n' or '\br'   or others. Please advise.  Thanks!
