### ISSUE TITLE
[CP-beta] Fix memory leak during upload of multiframe codecs on Android/Impeller.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157114]
### Issue Link

https://github.com/flutter/flutter/issues/156728

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/55928

### Changelog Description

When uploading textures from a multiframe codec on Android/Impeller, eagerly dispose driver resources to prevent memory exhaustion.

### Impacted Users

Android/Impeller

### Impact Description

Applications with multiframe codecs will gradually run out of memory and crash.

### Workaround

Opt out of Impeller.

### Risk

low

### Test Coverage

yes

### Validation Steps

Attached unit test passes.

**Comment by reidbaker** [comment]
@jonahwilliams can I get you to reformat the change log description to follow these best practices. 

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfix-Documentation-Best-Practices.md

In the past this was something a release engineer would do but we are moving to having cherry pickers do it since they have a better understanding of the change.

**Comment by jonahwilliams** [comment]
Like that?

**Comment by reidbaker** [comment]
Here is my attempt. It is missing how likely it is to occur. 
[flutter/156728](https://github.com/flutter/flutter/issues/156728): Prevent memory leak on Android/impeller, When uploading textures from a multiframe codec by eagerly disposing driver resources.
