### ISSUE TITLE
[video_player_android] `can pause` test flaky

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#157307]
I've noticed while working on `video_player_android` that the [`can pause` integration test](https://github.com/flutter/packages/blob/aad3fd00f2fb1563783d53783897265a2ba0af5b/packages/video_player/video_player_android/example/integration_test/video_player_test.dart#L88) added in https://github.com/flutter/packages/pull/7847 is very flaky. We need to revisit how it is implemented since the times it compares often do not align.

Example of a failing build: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733442426089662977/+/u/Run_package_tests/drive_examples/stdout

**Comment by stuartmorgan** [comment]
I was looking at this briefly yesterday since I was hitting the flake as well; my best guess is that there's some kind of single-frame "settling" that happens asynchronously after pausing? I don't see any kind of async callback we get for when the pause is actually done, and if we can't find one we may just have to put in a very small diff tolerance in the test.

**Comment by camsim99** [comment]
> I was looking at this briefly yesterday since I was hitting the flake as well; my best guess is that there's some kind of single-frame "settling" that happens asynchronously after pausing? I don't see any kind of async callback we get for when the pause is actually done, and if we can't find one we may just have to put in a very small diff tolerance in the test.

Ok this makes sense to me. I'll look into this today so that it stops blocking the tree.
