### ISSUE TITLE
Text selection does not work with a mouse

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15754]
The user should be able to press the mouse button, drag over text to select, then release.

**Comment by zoechi** [comment]
Related to #757

**Comment by goderbauer** [comment]
@gspencergoog FYI

**Comment by mdebbar** [comment]
@tvolkert if this is specifically about selection in text fields, then this issue can be closed. I submitted multiple PRs but this is the main one: https://github.com/flutter/flutter/pull/28290

If the issue is about text selection in general, then it should remain open since general text selection hasn't been implemented yet (even for touch).

**Comment by tvolkert** [comment]
Cool - thanks for the heads up @mdebbar.  Deferring to @gspencergoog on whether this should remain open.

**Comment by gspencergoog** [comment]
Closing: I think this has been addressed, and general text selection is another beast.
