### ISSUE TITLE
Flutter web: ChromeProxyService: Failed to evaluate expression

### ISSUE THREAD

**Issue by MacDeveloper1** [flutter/flutter#157784]
### Steps to reproduce

When the code execution is stopped by debugger I noticed that many getters in **Variables** tab of VSS Code Debugger have such value `<InternalError: No batch result object ID.>` and the **Debug Console** contain such lines.
```
ChromeProxyService: Failed to evaluate expression 'x.iconData': InternalError: No batch result object ID..
ChromeProxyService: Failed to evaluate expression 'x.color': InternalError: No batch result object ID..
ChromeProxyService: Failed to evaluate expression 'x.position': InternalError: No batch result object ID..
...
```

I know the was a similar issue in the past but I have almost latest flutter stable version and latest Chrome version.

### Expected results

Effective values

### Actual results

<InternalError: No batch result object ID.>

### Flutter Doctor output

Flutter: 3.24.3 Stable
Chrome: Version 130.0.6723.70 (Official Build) (64-bit)

**Comment by xhc-code** [comment]
help

**Comment by huycozy** [comment]
@MacDeveloper1 I am also on the same Chrome version but can't reproduce this issue when debugging a simple project on VSCode. Does the issue only appear on VSCode or also on Android Studio? Can you try on a newly created Flutter project to see if the issue occurs as well?

>I know the was a similar issue in the past

Please share that issue here. Thanks!

@xhc-code Do you also encounter the exact error as reported? If not, please file a separate issue for better tracking.

**Comment by xhc-code** [comment]
> @MacDeveloper1 I am also on the same Chrome version but can't reproduce this issue when debugging a simple project on VSCode. Does the issue only appear on VSCode or also on Android Studio? Can you try on a newly created Flutter project to see if the issue occurs as well?
> 
> > I know the was a similar issue in the past
> 
> Please share that issue here. Thanks!
> 
> @xhc-code Do you also encounter the exact error as reported? If not, please file a separate issue for better tracking.

I am using the latest version of VSCode, Flutter is also the latest version currently available, and I am using Chrome browser for debugging. The timing of this issue is that after your project starts, you have to modify the code multiple times before encountering this problem. This may be due to the complexity of the code causing hot loading issues.
