### ISSUE TITLE
Xcode 16 + Flutter 2.8.1: app size is increased

### ISSUE THREAD

**Issue by iOSyifeng** [flutter/flutter#157908]
### Steps to reproduce

Xcode16 + Flutter 2.8.1   将flutter的二进制代码 用xcode16打包集成 最后的包体大小增大了20多MB,  主要就是在Framework中的App.framework中的 二进制文件, 想问下大家是这样吗 还是说得升级Flutter版本才行

### What target platforms are you seeing this bug on?

iOS

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

**Comment by huycozy** [comment]
>Xcode16 + Flutter 2.8.1 将flutter的二进制代码 用xcode16打包集成 最后的包体大小增大了20多MB, 主要就是在Framework中的App.framework中的 二进制文件, 想问下大家是这样吗 还是说得升级Flutter版本才行

English version: 

>Xcode16 + Flutter 2.8.1 Package and integrate the flutter binary code with xcode16. The final package size increased by more than 20MB, mainly due to the binary files in App.framework in Framework. I would like to ask if this is the case or if I need to upgrade the Flutter version.

You are using an old Flutter version, please upgrade to the latest stable 3.24.4 and retry. 

If the issue persists, please try to provide all proper information indicated in the issue template so that we can verify it (you duplicated information in all fields, I modified the 1st comment). And please also [consider posting issues in English](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#consider-posting-issues-in-english).

**Comment by jonahwilliams** [comment]
You cannot determine the application size by looking at the size App.framework on disk
