### ISSUE TITLE
How to generate unit test reports in HTML or XML format using the "flutter test "command?

### ISSUE THREAD

**Issue by MrQiaoJian** [flutter/flutter#157985]
How to generate unit test reports in HTML or XML format using the "flutter test "command?

Does it support  “flutter test xxx -- reporter=xml/html” ？

Now through the 'flutter test' command, you can see how many were successful and how many failed, without specific XML or HTML reports to clearly view.

**Comment by huycozy** [comment]
As I can see, there is only json format currently:

```console
-r, --reporter=<option>               Set how to print test results.

          [compact] (default)         A single line, updated continuously.
          [expanded]                  A separate line for each update.
          [failures-only]             A separate line for failing tests with no output for passing tests
          [github]                    A custom reporter for GitHub Actions (the default reporter when running on GitHub Actions).
          [json]                      A machine-readable format (see https://dart.dev/go/test-docs/json_reporter.md).
          [silent]                    A reporter with no output. May be useful when only the exit code is meaningful.

    --file-reporter                   Enable an additional reporter writing test results to a file.
```

If you expect HTML or XML format, please file a new issue ([proposal](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml) template) for that. 

>Now through the 'flutter test' command, you can see how many were successful and how many failed, without specific XML or HTML reports to clearly view.

This is a different request for test tool command, please file a separate proposal as well.

Closing from here as this is more of a `how-to` question rather than a detailed feature request.
