### ISSUE TITLE
Add engine presubmit hook on github

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#15807]
We should have an engine presubmit hook similar to what we've got for the framework driven by whether the Linux, Mac, Windows engine build bots are all green.

@Hixie @yjbanov do you have a pointer to what was required to get something like this (and the rope) set up for the framework?

**Comment by chinmaygarde** [comment]
We don't currently rebuild the engine with the patchsets in pull requests on GitHub. Or did you just mean being able to gate commits on a red tree?

**Comment by cbracken** [comment]
Yep I just mean knowing that Engine (Linux, Mac, Windows) bots are green at the last known build.

**Comment by yjbanov** [comment]
This should be relatively straight-forward. We'd probably have a job that combines something like [this](https://github.com/flutter/cocoon/blob/master/commands/refresh_chromebot_status.go) with something like [this](https://github.com/flutter/cocoon/blob/master/commands/push_build_status_to_github.go).

I can take this, if there are no volunteers, but will likely get to it next week.

**Comment by cbracken** [comment]
That would be fantastic.

**Comment by rmistry** [comment]
Just curious, when do you expect to get to this?
No real rush, just asking for https://bugs.chromium.org/p/skia/issues/detail?id=7730 because it is one of the blockers for automated rolls.

**Comment by yjbanov** [comment]
Starting this now.

**Comment by rmistry** [comment]
Question since this issue is closed: How do we invoke this? is it automatically triggered? (sorry if this is an obvious question).

**Comment by yjbanov** [comment]
Sorry, I forgot that the change was made in a private repo, so this bug was closed without providing any details. The system is automatic. It will forward the latest build status from [the engine build bots](https://build.chromium.org/p/client.flutter/waterfall) to all open pull requests. If the build is known to be broken the pull requests will show "Some checks were not successful" and will produce a warning when you attempt to merge.
