### ISSUE TITLE
Menu is detached from content when MenuAnchor is given tight constraints

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#158264]
### Steps to reproduce

1. Run the code sample
2. Open the menu

This issue is the MenuAnchor version of https://github.com/flutter/flutter/issues/147076 which was reported for DropdownMenu.

### Expected results

The menu is attached at the bottom of the TextField

![image](https://github.com/user-attachments/assets/80ead9ec-a39a-4f6b-8533-f4a9cfd74e00)

### Actual results

The menu is detached from the TextField (it appears below the tight constraints the MenuAnchor was given).

![image](https://github.com/user-attachments/assets/4c06d9ef-6fd9-4390-97ca-1477f5eead3a)

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Container(
        alignment: Alignment.center,
        color: Colors.amber,
        child: SizedBox(
          height: 100.0,
          width: 100.0,
          child: Card(
            child: MenuAnchor(
              builder: (context, controller, child) {
                return TextField(
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                  ),
                  onTap: () {
                    if (controller.isOpen) {
                      controller.close();
                    } else {
                      controller.open();
                    }
                  }
                );
              },
              menuChildren: [
                MenuItemButton(
                  onPressed: () {},
                  child: const Text('This is a very long label',),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.27.0-1.0.pre.395, on Ubuntu 24.04.1 LTS 6.8.0-48-generic, locale fr_FR.UTF-8)
```

</details>

**Comment by bleroux** [comment]
@gspencergoog , I'm seeking your insight on this issue.
I’m not sure if we can find a solution that would apply to any kind of `MenuAnchor` content (widget returned by `MenuAnchor.builder` or `MenuAnchor.child`).
I tried a naive solution in https://github.com/flutter/flutter/pull/158265 (just wrapping the content with a Column), which passes all framework tests (including the one I added based on this issue and [the `DropdownMenu` one](https://github.com/flutter/flutter/issues/147076)) but failed with a little more complex layout such as the one in [this MenuAnchor example](https://github.com/flutter/flutter/blob/master/examples/api/lib/material/menu_anchor/menu_anchor.1.dart).

In https://github.com/flutter/flutter/pull/157496, I was able to fix this issue for `DropdownMenu` because the use case is more narrow: the content is known it is either a `TextField` or a `_DropdownMenuBody`, so it was possible to set the right constraints.

Any ideas on how to make progress is welcomed :pray:.

**Comment by gspencergoog** [comment]
It seems like the problem is that `MenuAnchor` is measuring the size of the area that its builder has to build in, and using that as the rectangle that it uses to place the menu in the overlay instead of using the box that the contents actually want to take up inside the builder. If you look at the widget tree for the example, the `InputDecorator` from the text field is taking up the entire SizedBox parent, so the MenuAnchor is correct in placing it below. Switching the text field for a Container, and the container also takes up the full size of the outer SizedBox, even if you set it to a size that is smaller.

It seems like this might be fixed by adding an `Align` widget around the builder in the MenuAnchor with size factors of 1.0. like so:

```dart
      child: Align(
        alignment: AlignmentDirectional.topStart,
        heightFactor: 1.0,
        widthFactor: 1.0,
        child: Builder(
          key: _anchorKey,
          builder: (BuildContext context) {
            return widget.builder?.call(context, _menuController, widget.child)
                ?? widget.child ?? const SizedBox();
          },
        ),
      ),
```
(from [here in menu_anchor.dart)](https://github.com/flutter/flutter/blob/bd65732cd2f7c8129400f302616bc37a0f9f6b87/packages/flutter/lib/src/material/menu_anchor.dart#L455)

The only issue with that is what to use for the alignment (and there needs to be an alignment to know how to place widgets that aren't the same size as their parent), since it will change how some things are placed in the box. `topStart` might work for most cases, but I'm not sure what the implications would be in general.  Maybe there should be a new optional parameter to `MenuAnchor` that sets the alignment, and if you don't set the alignment, then it doesn't insert the `Align`?  That would help keep from breaking everything, but still let you control the position of the contents.

**Comment by bleroux** [comment]
Thanks for clearly describing the problem :pray: and providing the idea of an optional alignment parameter :+1:.
I will experiment with this optional alignment parameter and see how it goes with the various use cases (especially MenuAnchor usage in DropdownMenu, MenuAnchor examples, and the test I added on https://github.com/flutter/flutter/pull/158265).

**Comment by bleroux** [comment]
Closing as solved per https://github.com/flutter/flutter/pull/159619#issuecomment-2511431738.
