### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by Muhammedalfateh** [flutter/flutter#158279]
Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true

**Comment by Muhammedalfateh** [comment]
can some body help me

**Comment by huycozy** [comment]
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue, since not much information has been provided to move forward. I would suggest you open a new issue and fill all requested information.
