### ISSUE TITLE
http.get in flutter on ios is slow compared to android

### ISSUE THREAD

**Issue by gizmomogwai** [flutter/flutter#15838]
## Steps to Reproduce

I have a minimal rest client that just fetches data with http.get in an async method.
On android this takes around 0.02 seconds according to Stopwatch (and feels like this)
on iOS it takes around 5 seconds according to Stopwatch (and feels like 10).

**Comment by mraleph** [comment]
Can you check if you measuring this in release or debug build? Please try `flutter run —release` both on iOS and Android.

**Comment by gizmomogwai** [comment]
Yes ... I did ... its the same values.

**Comment by gizmomogwai** [comment]
````
  Future<void> index() async {
    try {
      if (_info != null) {
        print('getting index');
        setState(() => _serverResult = new ServerResult());
        final url = infoToUri(_info).resolve('api/state');
        final stopwatch = new Stopwatch()..start();
        final response = await get(url).timeout(const Duration(seconds: 15));
        print('getting in ${stopwatch.elapsed}');
....
````
thats the code i use to make the request ...

**Comment by gizmomogwai** [comment]
i am sure, this must be some problem of mine, otherwise there would be much more problems ...

**Comment by gizmomogwai** [comment]
I did some more testing, and observed, that ios is only so slow, if i do the getting from a mdns/bonjour name. if i directly use the ip associated with this name, the operation is as fast as on the android side.

**Comment by Hixie** [comment]
This sounds like a Dart issue. cc @zanderso

**Comment by jrmarkham** [comment]
Having the same issue with http.post.

**Comment by AresVampire** [comment]
I have the same problem, especially for calling several APIs in parallel.

**Comment by Sleevezipper87** [comment]
It _feels_ like requests on iOS are queued and executed one after the other while on Android they seem to execute in parallel. The problem only occurs in release builds for me which makes it very hard to debug. 

I was using the swagger-generator to generate our API client. This generated code dependent on the flutter http package. I thought the problem may be in this package so I refactored our app to use the openapi-generator with the dart-dio template. This template uses Dio as the http client. Sadly, this did not solve the problem. 

So my guess would be that there might be an issue with the underlying platform specific implementation which I am not familiar with. 

Any ideas that may help with figuring this out?

**Comment by mraleph** [comment]
@Sleevezipper87 @AresVampire - you will need to provide as much information as possible to help us reproduce the issue (e.g. are you running on a simulator or a real device, what kind of device it is etc) Preferably we need a sample project we could build and run locally.

Searching reveals that at least iOS Simulator has issues with DNS resolution which make things very slow (see for example [this SO question](https://stackoverflow.com/questions/8055958/slow-dns-lookup-on-ios-simulator)). This matches what @gizmomogwai has [observed](https://github.com/flutter/flutter/issues/15838#issuecomment-375742351). However if you are running release build on a real device then the problem is most likely different - and might be associated just with performance characteristics of the release build itself (e.g. release build might be slower than debug build). 

@Sleevezipper87 I suggest doing a profile build and then using [DevTools](https://flutter.dev/docs/development/tools/devtools/overview) to look at the CPU profile.

**Comment by Sleevezipper87** [comment]
This seems to have gotten better with Flutter 1.12.13+hotfix.7 (or the version before). Do you guys observe this as well?

**Comment by stefanodecillis** [comment]
This problem still persists on the version flutter_macos_v1.12.13+hotfix.8-stable. I saw this problem using google maps or http clients. Hope it will be fix soon

**Comment by rxwen** [comment]
We had the same problem on iOS platform as well. It took about 5 seconds to perform a simple http get request. flutter version: v1.12.13+hotfix.8-stable. iOS version: 13.3.1. 

The weird thing is, it happened only when I run on the iPhone with wifi on, the speed is normal if I run on 4G connection.
But I can guarantee the wifi network is fine. Because when we access the same site in any other app not built with flutter (safari for example), the speed is normal.

**Comment by rxwen** [comment]
The problem exists no matter we use http or HttpClient to request data.

**Comment by rxwen** [comment]
As a reference, I created a flutter sample project, with 

`flutter create --androidx -t app sample`

Then, add some code in main.dart to perform a simple http get request, whenever user clicks the + button and display the time spent. (https://gist.github.com/rxwen/009c7ae4328ee799f71013f06e206b13)
This simplest example, exhibit the same behavior too.
- Took about 5 second on  wifi
- Safari can open the same instantaneously under the same wifi connection
- Took about 500 ms on 4G

**Comment by rxwen** [comment]
Tried the sample on flutter 1.9.1 version, the problem still exist.

**Comment by rxwen** [comment]
I conducted a further test, calculate the time of running 
IPAddress.lookup("baidu.com")
and 
http get "http://baidu.com"

The pure dns lookup took merely no time at all. But the http get still took more than 5 seconds.

**Comment by rxwen** [comment]
I came to realize why @Hixie said this is a dartlang issue.
Looks like the underlying httpclient and socket in implemented in dart sdk repo.
Guess we should report the issue there.

**Comment by nivekz** [comment]
I am reporting a similar issue at https://github.com/flutter/flutter/issues/55586 which seems to be related to HTTPS.

**Comment by ivanryndyuk** [comment]
I've found kinda temporary work around to increase the response speed with platform channel methods
https://github.com/dart-lang/sdk/issues/41451#issuecomment-619243422

**Comment by Purity1488** [comment]
http.post is giving me 10 second delays too on IOS, very quick on android.
Only sending token text to a php form, shouldnt take that long at all.

**Comment by pedromassangocode** [comment]
If I read the thread right this is clearly a Dart issue so I'm going to close it.
Please feel free to reopen if is related to Flutter.
