### ISSUE TITLE
Requesting for instant marker drag, instead of hold and drag in google_maps_flutter package

### ISSUE THREAD

**Issue by naveen-tharkka** [flutter/flutter#159022]
### Use case

There is flutter_map_line_editor package works with flutter_map package, using this we are able to instantly drag the marker. Same feature i was trying to achieve it in google_flutter_maps. We are actually dealing with a client, where we have to draw polygons. After all they requested for the instant drag option for markers by showing reference application in playstore

https://play.google.com/store/apps/details?id=lt.noframe.fieldsareameasure&hl=en_IN

This was using google maps only

### Proposal

Requesting for a key to enable instant drag for markers. If there are any already achieved solution in flutter please provide the docs

**Comment by stuartmorgan** [comment]
The `google_maps_flutter` packages wraps the features available in the underlying SDK, and there is not option for instant drag in the SDK. The app you are referring to must be writing custom event handling, rather than configuring an option in the SDK, so the solution would be similar for a Flutter app.

Given that there is no such option in the SDK to expose, closing as out of scope.
