### ISSUE TITLE
Flutter DevTool does not work correctly

### ISSUE THREAD

**Issue by Evanfor1990** [flutter/flutter#159060]
### Steps to reproduce

android studio、windows11
1、I use a component which extend route
2、some breakpoint not work. （only when i launch from web）
3、 Uncaught Error: getObject: (-32603) Unexpected DWDS error for getObject: FormatException: Unsupported URI form: C:/Users/***/AppData/Local/Pub/Cache/hosted/pub.dev/flame-1.17.0/lib/src/components/route.dart
4、i use route component directly. breakpoint works well；

### Actual results

some breakpoint not work. e.g. onTapUp，runApp@main(

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
@Evanfor1990 When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly.

In the `Steps to reproduce` section, I don't see you mention Devtools but it's on issue title. Can you update steps to make sure it's more evident?

Also, please provide the following missing info:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- The complete error output [^1]

[^1]: The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.
