### ISSUE TITLE
InputDecoration.focusColor is ignored

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#159254]
### Steps to reproduce

1. Run the given code sample.
2. Observe the color of the filled `InputDecorator`.

### Expected results

The InputDecorator container fill color is yellow (as set for inputDecoration.focusColor):

![image](https://github.com/user-attachments/assets/0ea28767-7f4d-4531-abe8-519247240f4f)

### Actual results

The InputDecorator container fill color is light grey (defaults color for M3):

![image](https://github.com/user-attachments/assets/806bc60b-9136-4648-ae4d-ed514c05efdd)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Material(
        child: Padding(
          padding: EdgeInsets.all(8.0),
          child: InputDecorator(
            isFocused: true,
            decoration: InputDecoration(
              filled: true,
              labelText: 'LabelText',
              focusColor: Colors.amberAccent,
            ),
            child: Text('Flutter'),
          ),
        ),
      ),
    );
  }
}


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel master, 3.27.0-1.0.pre.587, on macOS 14.2.1 23C71 darwin-arm64, locale fr-FR)
```

</details>

**Comment by arslanraza7** [comment]
Hi @bleroux,


The issue here is that the `InputDecorator` fill color does not reflect the color set for `focusColor` in the `InputDecoration`. Instead, it defaults to light grey, which is the default color for Material 3 (M3).

The `focusColor` property in `InputDecoration` does not directly affect the fill color of the `InputDecorator` when focused. Instead, you should use the `fillColor` property to explicitly set the desired fill color.

To achieve the expected result of a yellow fill color, modify the code like this:

```dart
InputDecoration(
  filled: true,
  fillColor: Colors.amberAccent, // Set the fill color directly.
  labelText: 'LabelText',
),
```

This will ensure that the `InputDecorator` container is filled with the correct color (`amberAccent`) as expected.

**Comment by bleroux** [comment]
> This will ensure that the InputDecorator container is filled with the correct color (amberAccent) as expected.

The expectation is the color is correct only when isFocused is true not that the fill color is always amberAccent.
See [my other comment](https://github.com/flutter/flutter/issues/159254#issuecomment-2491282654) on how to use state resolution.

**Comment by bleroux** [comment]
Clsoing as solved per https://github.com/flutter/flutter/issues/159254#issuecomment-2491282654
