### ISSUE TITLE
This  is bad to while(true)   

### ISSUE THREAD

**Issue by yangyudaddy** [flutter/flutter#15939]
```
while (true) {
    attempts += 1;
    code = await runCommandAndStreamOutput(
      _pubCommand(arguments),
      workingDirectory: directory,
      mapFunction: filter,
      environment: _createPubEnvironment(context),
    );
    if (code != 69) // UNAVAILABLE in https://github.com/dart-lang/pub/blob/master/lib/src/exit_codes.dart
      break;
    printStatus('$failureMessage ($code) -- attempting retry $attempts in $duration second${ duration == 1 ? "" : "s"}...');
    await new Future<Null>.delayed(new Duration(seconds: duration));
    if (duration < 64)
      duration *= 2;
  }
```

I am not think this is good idea .  
It makes me force to close my android studio.
I think It can't help me to find problem ,and it makes me be agitated

while (attempts<3)   I think three is good

**Comment by DanTup** [comment]
I think @yangyudaddy is suggesting that the code (which is from [here](https://github.com/flutter/flutter/blob/2e970008add2c041c1fe8e982b850a40667ad7ca/packages/flutter_tools/lib/src/dart/pub.dart#L151-L168)) should have some maximum number of iterations. Currently it will keep doubling the wait time till 64 seconds and then loop indefinitely if it can't connect to pub.

I'm not sure why it would make Android Studio hang though (unless it's blocking waiting for the process to terminate). If it's being run from tooling I'd agree it should probably bail after a while though. If it hasn't succeeded after 10 mins, probably it won't because something is broken.

**Comment by yangyudaddy** [comment]
@DanTup  I am from China. You know we  connect network to update by VPN. If we just forget for set proxy for terminal , that is trouble with us.  Especially， we change net from  outline net to company net.

**Comment by zoechi** [comment]
Should this be moved to the dart-lang/pub repo?

**Comment by DanTup** [comment]
In my opinion, the fix should be in the code above (it should give up after a certain number of iterations and display a message about what it was doing, how long it tried for, and some hints about what the issues might be).

**Comment by zoechi** [comment]
Sorry, I missed that this is part of Flutter, I just saw `pub.dart`. 
Sorry for the noise.

**Comment by Hixie** [comment]
Code 69 happens when there's a network error. Sometimes network errors happen for 11 minutes, so timing out after 10 minutes doesn't work.
