### ISSUE TITLE
Flutter page render exception

### ISSUE THREAD

**Issue by m2k1024** [flutter/flutter#159525]
### Steps to reproduce

设备信息 (Equipment information)
Device name- Vivo Y21
Os version - android 12

### Expected results

<img src="https://github.com/user-attachments/assets/70abf27c-5519-47c0-ba36-3bb42214f703" width="300" />

如何去掉页面所有的绿色，正常渲染 (How to remove all the green on the page and render normally)

### Actual results

<img src="https://github.com/user-attachments/assets/b190a2e5-9d46-4d73-a271-5f908cc650e9" width="300" />

如何去掉页面所有的绿色，正常渲染 (How to remove all the green on the page and render normally)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

#[Upload media here]
<img src="https://github.com/user-attachments/assets/eaf668d0-3ad9-42df-9794-dd209233d00b" width="300" />

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @m2k1024, this was initially reported in https://github.com/flutter/flutter/issues/143573 as affecting PowerVR devices which your Vivo y21 happens to use as the GPU. This has been fixed in and the fix is available in stable 3.24.0+. See 
https://github.com/flutter/engine/commit/5a824e22deb20c478f289473822a8efb046d026a 

If you are using stable 3.24.0+ and you're still experiencing this issue, kindly provide the full output of `flutter doctor -v`. 

Given that this has already been fixed, I'll be closing this issue. 

Thank you
