### ISSUE TITLE
[CP][For 3.28 and NOT 3.27!!!][ios][platform_view] workaround for non-tappable webview

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#159911]
### Issue Link

https://github.com/flutter/engine/pull/57030

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/57032

### Changelog Description

Fix an issue on iOS 18.2 where web view's link is not tappable.

### Impacted Users

all end customers using web view

### Impact Description

Web view's link is not tappable on iOS 18.2

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

What are the steps to validate that this fix works?

1. Launch web view plugin's example app
2. Tap on ... menu on top left corner
3. Tap on any link on web view. The link is working with the fix, and not working without the fix.

**Comment by SoohyungJung** [comment]
@hellohuanlin 
First of all, I would like to sincerely thank you for your significant contribution to resolving this issue.

Can I ask when version 3.28.0, which includes the fix for this issue, will be released? I initially thought it was addressed in version 3.27.0 and updated accordingly, but the issue persists. While searching for more information, I came across this thread.

A large portion of our app relies on webviews, and this issue could significantly impact our revenue. We are eager to update to the version with the fix as soon as possible, and we would greatly appreciate a swift release.

Thank you so much for your efforts.

**Comment by hellohuanlin** [comment]
@SoohyungJung The fix should already be in 3.27.0. So if the problem persist, it likely a separate cause that requires new workarounds. Can you file an issue with a minimal re-reproducible project.

**Comment by SoohyungJung** [comment]
@hellohuanlin 
Thank you for your response!

After reviewing the [release notes for version 3.27.0](https://docs.flutter.dev/release/release-notes/release-notes-3.27.0), I could not find any mention of the issue in question. If I am mistaken, please kindly let me know. The issue I am currently facing appears to be identical to the one described in [this GitHub issue](https://github.com/flutter/flutter/issues/158961).

Could you please confirm if the fix for this issue is indeed included in version 3.27.0? If it has already been addressed in this version, as you mentioned, I will proceed to open a new issue separately.

Thank you for your assistance!

**Comment by hellohuanlin** [comment]
@SoohyungJung Are you using the official flutter webview plugin?

**Comment by SoohyungJung** [comment]
@hellohuanlin 
I am currently using the flutter_inappwebview package.

**Comment by pichillilorenzo** [comment]
Hi @hellohuanlin, I'm the author of the flutter_inappwebview plugin.
The current fix you have made is specifically for embedded views that exactly match the `WKWebView` class kind:

https://github.com/flutter/engine/blob/21d9840bd1d571892c35d36a819a9ea71947eefe/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L583-L588

My plugin wraps the `WKWebView` inside a `UIView`, so this fix is not a valid one.

On the Flutter Engine side, instead of checking the `WKWebView` class kind, a more suitable solution would be to create a specific custom interface that can be used by external plugins and then used by the Flutter Engine to check if the custom platform embedded view matches that class to activate the workaround.

As this is a workaround, another solution could be adding a new property for the `FlutterPlatformViewFactory` class that can be overridden and that acts like a boolean flag to activate it. Just overriding it to return `true`/`false` could activate the workaround or not.

Choose whatever you want to implement, but the current fix will not work for webviews (or maybe other native views) inside other UIViews on iOS.

**Comment by hellohuanlin** [comment]
@pichillilorenzo Thanks for the info. I can probably fix it by doing a DFS traversal in the engine, and no change by the plugin would be required. Could you (or anyone using `flutter_inappwebview`) create an issue with a reproducible sample so I can verify the fix?

**Comment by pichillilorenzo** [comment]
I do not have iOS 18.2 beta installed.
This is the original issue: https://github.com/pichillilorenzo/flutter_inappwebview/issues/2415

Probably, you can use the same code you already used for `webview_flutter` for your tests and change the webview part by simply using the `flutter_inappwebview` plugin, or I think you can use this simple code example:
```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    await InAppWebViewController.setWebContentsDebuggingEnabled(kDebugMode);
  }

  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;

  String url = "";
  double progress = 0;
  final urlController = TextEditingController();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("Example")),
        body: SafeArea(
            child: Column(children: <Widget>[
          TextField(
            decoration: const InputDecoration(prefixIcon: Icon(Icons.search)),
            controller: urlController,
            keyboardType: TextInputType.url,
            onSubmitted: (value) {
              var url = WebUri(value);
              if (url.scheme.isEmpty) {
                url = WebUri("https://www.google.com/search?q=$value");
              }
              webViewController?.loadUrl(urlRequest: URLRequest(url: url));
            },
          ),
          Expanded(
            child: Stack(
              children: [
                InAppWebView(
                  key: webViewKey,
                  initialUrlRequest:
                      URLRequest(url: WebUri("https://flutter.dev/")),
                  initialSettings:
                      InAppWebViewSettings(isInspectable: kDebugMode),
                  onWebViewCreated: (controller) {
                    webViewController = controller;
                  },
                  onLoadStart: (controller, url) {
                    setState(() {
                      this.url = url.toString();
                      urlController.text = this.url;
                    });
                  },
                  onLoadStop: (controller, url) async {
                    setState(() {
                      this.url = url.toString();
                      urlController.text = this.url;
                    });
                  },
                  onProgressChanged: (controller, progress) {
                    setState(() {
                      this.progress = progress / 100;
                      urlController.text = url;
                    });
                  },
                  onUpdateVisitedHistory: (controller, url, androidIsReload) {
                    setState(() {
                      this.url = url.toString();
                      urlController.text = this.url;
                    });
                  },
                ),
                progress < 1.0
                    ? LinearProgressIndicator(value: progress)
                    : Container(),
              ],
            ),
          ),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: const Icon(Icons.arrow_back),
                onPressed: () {
                  webViewController?.goBack();
                },
              ),
              ElevatedButton(
                child: const Icon(Icons.arrow_forward),
                onPressed: () {
                  webViewController?.goForward();
                },
              ),
              ElevatedButton(
                child: const Icon(Icons.refresh),
                onPressed: () {
                  webViewController?.reload();
                },
              ),
            ],
          ),
        ])));
  }
}
```

Thanks for the support!

**Comment by hellohuanlin** [comment]
@pichillilorenzo Can you zip a project that i can run directly?

**Comment by pichillilorenzo** [comment]
here is the zip: [test_ios_18_2_bug.zip](https://github.com/user-attachments/files/18117732/test_ios_18_2_bug.zip)

**Comment by hellohuanlin** [comment]
@pichillilorenzo this gives me build error: 
```
error: ../../../../../flutter/packages/flutter/lib/src/cupertino/colors.dart:751:7: Error: The non-abstract class 'CupertinoDynamicColor' is missing implementations for these members:
 - Color.toARGB32
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CupertinoDynamicColor with Diagnosticable implements Color {
      ^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:219:7: Context: 'Color.toARGB32' is defined here.
  int toARGB32() {
      ^^^^^^^^
Target kernel_snapshot_program failed: Exception
```

**Comment by pichillilorenzo** [comment]
That error has nothing to do with my plugin and I don't know what it is.
I created the project using flutter 3.27.0 version, added the plugin dependency and run it on iOS Simulator without any error.

By the way, you can create your own test project, simply add the `flutter_inappwebview` plugin as a dependency in the `pubspec.yaml` project file, and use my test code from the previous comment here.

Or just use the test project you already used to test your changes for the `webview_flutter` plugin and simply use my test code instead.

**Comment by hellohuanlin** [comment]
@pichillilorenzo I was able to run the project and repro the issue (it was the issue with my setup). I also confirmed that my PR works. I will close this and put up another CP.

**Comment by SoohyungJung** [comment]
@hellohuanlin @pichillilorenzo 
I was planning to share a reproducible example after waking up since I left the comment late at night, but I was genuinely surprised and deeply grateful to see both of you actively working on the issue in the meantime. I sincerely appreciate your swift response and efforts. I’m looking forward to the new Flutter update.

Thank you so much!
