### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by zouxj** [flutter/flutter#160015]
Describe your issue and include the command you're running, flutter_web version, browser version

flutter开发web的，存在实时刷新的数据时，在谷歌浏览器上内存限制一直增长，刷新后没有回收旧的widget

**Comment by danagbemava-nc** [comment]
Hi, 

When filing an issue, it is important that you provide all the required information in the template. 

Simply stating your error doesn't tell us anything other than "my app doesn't work properly/correctly", which we're already aware of since you're filing the issue. 

As such I'm going to close this issue. 

If you have an actual issue, kindly file a new one and fill in all the requisite information. 

Thank you
