### ISSUE TITLE
Readability of framework code is very hard 

### ISSUE THREAD

**Issue by Albinzr** [flutter/flutter#16023]
If I go in to any lib in framework, lets say "StatefulWidget" to see how everything is working.
All is see is extra large comment which doesn't make much sense to the code.
Also the code readability is poor 

Is there any way to understand how the inner code work?
better way to read code?

**Comment by zoechi** [comment]
I think the extensive comments in Flutter are very helpful.
I also see the problem that the actual code is a bit harder to find because of that.
A good way is probably stepping through the code using the debugger
or using IDE features that list all members without all the comments like outline view in IntelliJ/Android Studio.

If you have concrete suggestions where this should be improved and if possible how, please create new more specific issues.
I think the Flutter team is very aware that readability is important and they have strict guidelines, but it is difficult to make it easy for everyone.
  
I don't see any concrete action the Flutter team could do and am therefore closing this issue.
Thanks for filing this issue anyway.

**Comment by Albinzr** [comment]
The only reason I pointed this out is that i felt docs to be very similar to aws docs
[Not so easy to understand] that's all
