### ISSUE TITLE
fullscreenDialog route transition broken

### ISSUE THREAD

**Issue by RepliedSage11** [flutter/flutter#160373]
### Steps to reproduce

This [issue](https://github.com/flutter/flutter/issues/159289) was reported in 3.27 beta and the issue is now closed, however the PR that fixed this in beta is not part of 3.27 stable, so this issue still exists in the stable release

### Expected results

fullscreenDialog transitions sync with the underlying route

### Actual results

fullscreenDialog transitions are mixed with default transition

### Code sample

<details open><summary>Code sample</summary>
https://github.com/kuhnroyal/flutter_route_transition

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@RepliedSage11 
That is correct. The fix is in latest beta and master but not in stable yet. 
You may request a [cherry-pick](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) by providing all requested details so that the release team can decide if it can be hot-fixed or not. I can try to escalate this for team's attention.

I will close this for as this is fixed in master.

**Comment by RepliedSage11** [comment]
I will request a cherry-pick, but how does 3.27 get released to stable when such a bug is known and no cherry-pick is open already?
