### ISSUE TITLE
Not a bug but inconvinience. The properties `r`, `g`, `b`  of `Color`  are double but some constructors take `int`s. Why?

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#160346]
### Steps to reproduce

Why do I need to print redundant chars for cast? Please return `int`s or make all properties `double`.

```dart
final color1 = Color.from(100.0, 100.0, 100.0, 100.0);
final color2 = Color.fromARGB(color1.a as int, color1.r as int, color1.g as int, color1.b as int);
```

### Expected results
```dart
final color2 = Color.fromARGB(color1.a, color1.r, color1.g, color1.b);
```

### Actual results
```dart
final color2 = Color.fromARGB(color1.a as int, color1.r as int, color1.g as int, color1.b as int);
```
### Code sample

<details open><summary>Code sample</summary>

```dart
final color1 = Color.from(100.0, 100.0, 100.0, 100.0);
// Why do I need to print redundant chars for cast?
final color2 = Color.fromARGB(color1.a as int, color1.r as int, color1.g as int, color1.b as int);
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter 3.27.0
```

</details>

**Comment by moffatman** [comment]
I think it has to do with "wide color", where the color depth could be increased beyond normal 8 bits
Note your casts are wrong. Because these properties a, r, g, b are 0.0-1.0, not 0-255. So all your colors are going to be near black instead of the proper color.

If red/green/blue are going to be deprecated, so should the fromARGB etc. We need constructors to take doubles, I agree.

**Comment by bambinoua** [comment]
Finally, I found [this](https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework).
Thanks!
