### ISSUE TITLE
SSL Certificate Pinning using flutter

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#16066]
I want to add a trusted certificate to my HttpClient, but this is not very efficient. Certificates expire so I want to pin the public key. Is there a way to do this in dart/flutter?

**Comment by us3soap** [comment]
We publish a plugin : https://pub.dartlang.org/packages/ssl_pinning_plugin to check pinning with fingerprint (SHA-1).

**Comment by linuxjet** [comment]
Is this available yet?  Documentation?

**Comment by linuxjet** [comment]
That would be great.  So you have a new release for the 0.5.7 beta?   It doesn't seem to be compatible with the latest flutter beta. getting error:  

The current Flutter SDK version is 0.5.7.
 
 Because ssl_pinning_plugin requires Flutter SDK version ^0.4.4, version solving failed.

**Comment by zoechi** [comment]
I guess this should better be asked in dart-lang/sdk because it is about `dart:io`

**Comment by zoechi** [comment]
https://github.com/dart-lang/sdk/issues/33115 mentions that this is now fixed in Flutter
Can anyone confirm?

**Comment by long1eu** [comment]
yes it works

**Comment by zoechi** [comment]
Great! Thanks for the update @long1eu 👍

**Comment by giaur500** [comment]
Well, as I can see, only sha1 is supported. This is a shame, sha1 is very weak. Any thoughts to add sha256? Sha1 is not even worth

**Comment by zoechi** [comment]
@giaur500 please create a feature request in https://github.com/dart-lang/sdk/issues

**Comment by sandeepcmsm** [comment]
@zoechi @mit-mit  thanks for certficate pinning support. Can the SecurityContext validate a public key instead of a certificate? This is more future proof as certificate pinning comes with issues of certificate expiry. or can X509Certificate include public key sha256 signature. Since most of native apps are build on public key pinning. This has become one major blockage for our client. Can we reopen the current issue and  https://github.com/dart-lang/sdk/issues/33115 . since there has been any activity on dart sdk issue from months.

**Comment by pa1more** [comment]
Is this issue resolved for SHA2 certificates ?

I used webview in my application and it stopeed after i installed ssl on my server.

**Comment by mleonhard** [comment]
The ssl_pinning_plugin makes its own HTTPS request and checks the certificate.  It does not check certificates used by the app's real requests.  I see no way to accomplish that with the plugin.  This means that apps using the plugin are still vulnerable to MITM.
