### ISSUE TITLE
MethodChannel.invokeMethod should be generic API. 

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#16112]
(Filed at the request of @Hixie)
MethodChannel.invokeMethod currently returns `Future<dynamic>` though it should be one of a few types (yes, a perfect opportunity for union types, but anyway). A better would be to make it generic in some way `MethodChannel.invokeMethod<T>(...)` or `MethodChannel<T>` depending on how MethodChannel is used... I've only looked at it extremely superficially.

**Comment by Hixie** [comment]
cc @mravn-google @goderbauer

**Comment by mravn-google** [comment]
I guess with Dart 2 a generic `invokeMethod` would make sense. I don't think a generic `MethodChannel` does; the same channel is often used to relay values of different types back to Dart, depending on which methods was invoked.

**Comment by Hixie** [comment]
an alternative would be to put a discussion of this matter in the documentation for the method. right now it's not clear what type to expect back.

**Comment by mravn-google** [comment]
That is because the `MethodChannel` class itself carries no knowledge of that. It all depends on the codec with which an instance is constructed. The documentation for `invokeMethod` currently says as much, though we may be able to make it more explicit, by digging that information out of the paragraph on parameters.

We could also duplicate information from `StandardMessageCodec` in the documentation for `MethodChannel`. I didn't do that originally because the message codec and method channel are orthogonal concepts. However, the `StandardMessageCodec` does govern the behavior of a `MethodChannel` constructed with default parameters. So maybe there is little damage done by coupling the two concepts in documentation.

**Comment by Hixie** [comment]
sure. i think we could make it clearer with examples, a discussion of how the type is determined front the either side, etc.

**Comment by efortuna** [comment]
I will say the existing process for casting compound types on the customer side is pretty dang subtle for the average developer. I had to very carefully write 

invokeMethod('getLocation').then((result) => result.cast<String, double>()
and more intricate:
receiveBroadcastStream().map<Map<String, double>>((element) => element.cast<String, double>())

and I probably understand type systems better than the average programmer. I'm hoping general programmers don't have to figure this out. So, if we can make our users lives easier with a less cast-confusing API, that's great!

**Comment by mravn-google** [comment]
@efortuna Yes, it would be nice if there was a way to avoid or side-step `List<dynamic>` and `Map<dynamic, dynamic>`. The standard codec is designed to work with heterogenous data carrying no external type metadata. It is forced to produce `List<dynamic>` in the same way that a JSON decoder is when faced with `[42,87,103,...`--- for the next element may not be a number. Where JSON always uses `Map<String, dynamic>`, the standard codec does not force String keys, and so we end up with `Map<dynamic, dynamic>` too.

Since https://github.com/flutter/flutter/pull/15414 you can extend the standard codec and do whatever suits your situation better, including typed deserialization, at the cost of some additional coding.

**Comment by mravn-google** [comment]
Documentation with examples has been added. Closing this.
