### ISSUE TITLE
Cookbook on website should be free of analyzer errors

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#16155]
The code snippets in https://flutter.io/cookbook/ currently have 754 analyzer errors [1]. We should clean up those errors and then enforce that the code stays clean by including the cookbook in our travis check [2].

This will also ensure that the code in the cookbook doesn't go stale with new Flutter/Dart releases.

[1] https://travis-ci.org/flutter/website/builds/361245834#L1064
[2] https://github.com/flutter/website/blob/master/tool/extract.dart#L16

/cc @filiph, @mjohnsullivan, @devoncarew

**Comment by filiph** [comment]
cc @brianegan: Could you have a look, please?

**Comment by brianegan** [comment]
@filiph Sure thing, I'll take a look. 

I definitely keep the code free of analyzer warnings or errors when developing, but might have a different analysis_options.yaml setup compared to the one that's running here.

**Comment by brianegan** [comment]
Hrm, just briefly looking at it, this might be a tough challenge. 

The snippets in the Cookbook might refer to libraries, classes, or values that aren't explicitly imported or defined within the snippet. For example, a snippet in step 1 defines the `HeadingItem` class. In Step 2, the snippet does not import or know about this class, unless we repeated the code in that snippet as well.

Another example: `ListView.builder` and `itemCount` are not defined, because we aren't explicitly importing the Flutter material library in the snippet.

This was an intentional choice to keep the snippets short and to the point, so I'd be interested in hearing your thoughts on the best way to approach this. While the snippets should definitely be valid Dart code, they might be easy to analyze.

Would it be possible to analyze only the "Complete Example" sections of each recipe, which contains the full code?

**Comment by brianegan** [comment]
Thanks @devoncarew, that would definitely help in some cases, but not all. See the `HeadingItem` example above (a real failure on the CI).

**Comment by devoncarew** [comment]
Ah, makes sense. I don't have an example to hand, but (from memory) the website analysis mechanism does support hidden sections before a snippet. So, it wouldn't display, but would be included in the analysis. That would support some of your use cases, but long ones would likely mean more code dup than we'd want.

**Comment by Hixie** [comment]
What we do for the API docs is we analyze all of them in one file, so for example the CustomPainter API docs define the `Sky` class and the CustomPaint widget API docs use it.

**Comment by brianegan** [comment]
Thanks for the suggestions, everyone!

Analyzing everything as a single unit might work, but could lead to some interesting errors. Say we have `HeadingItem` defined in Step 1, then repeat `HeadingItem` in the "Complete Example." This would throw an analyzer error since it would be a duplicate definition.

From the discussion, I see two options:

  1. Analyze the "Complete Example" and ignore the snippets
  2. @devoncarew's suggestion: Analyze everything, and duplicate the "Complete Example" for all snippets, showing only the parts that are relevant for the given step

Are there any other options we could consider? Please let me know which direction to take and I'll give it a shot!

**Comment by Hixie** [comment]
You could also add a hidden label to each one that says what bucket to put it in, so your complete examples could get independently analyzed, while the snippets would end up in a shared file.

**Comment by brianegan** [comment]
PR with proposed fix: https://github.com/flutter/website/pull/968

**Comment by brianegan** [comment]
I'll look at one more option for how to handle this, but the extraction logic is now deployed and errors have been addressed.

**Comment by Sfshaza** [comment]
PR 968 has been merged, so this has been fixed. Closing.

**Comment by brianegan** [comment]
Thanks @Sfshaza!
