### ISSUE TITLE
Downloaded file is corrupt

### ISSUE THREAD

**Issue by layounisl** [flutter/flutter#16154]
running $flutter doctor for the first time, i got this error mutliple times
#
It appears that the downloaded file is corrupt; please try the operation again later.
If this problem persists, please report the problem at
https://github.com/flutter/flutter/issues/new
#

**Comment by tvolkert** [comment]
This is happening because this command is failing:

https://github.com/flutter/flutter/blob/06ed3622a3296a4d40ae5631ad4e2ecb67e27982/bin/internal/update_dart_sdk.sh#L55

@layounisl can you change the following line locally:

https://github.com/flutter/flutter/blob/06ed3622a3296a4d40ae5631ad4e2ecb67e27982/bin/internal/update_dart_sdk.sh#L15

... to say `set -ex`

... then try `flutter doctor` again and paste the full output here?

**Comment by mit-mit** [comment]
Closing as we have heard no reply
