### ISSUE TITLE
Extra 4px padding on AppBar

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter#16248]
## Steps to Reproduce

Run an app with an AppBar, such as the flutter gallery. There's an extra 4dp padding at the end of the AppBar. I think this deviates from the Material spec, which states the furthest right action should be exactly 16dp from the edge of the screen: https://material.io/guidelines/layout/structure.html#structure-app-bar

![qehglq3qctz](https://user-images.githubusercontent.com/1498161/38338122-0370dd06-381d-11e8-9f7b-b3e840915909.png)

This is caused by [this line](https://github.com/flutter/flutter/blob/464109c0e74591a710b1e9f6fc9beff6416cbb52/packages/flutter/lib/src/material/app_bar.dart#L409), is this needed for some reason I'm missing?

**Comment by xster** [comment]
cc @HansMuller

**Comment by tvolkert** [comment]
ping @HansMuller

**Comment by HansMuller** [comment]
The "end" padding for the appbar's actions was changed from 8.0 to 4.0 here: https://github.com/flutter/flutter/pull/8263/files#diff-cd3d20d8ad9a4a41df7826017412d6daL417

It was based on the Material spec from over a year ago, and I think it's safe to assume that the layout matched the spec at the time. 

The current spec looks like this:

![image](https://user-images.githubusercontent.com/1377460/40444782-21f190b2-5e7f-11e8-8c65-78c5fdd7f703.png)

In the screenshot below I've added a red vertical line on the right, to match the 16dps margin from the spec and highlighted the overflow menu icon's bounds:

![old](https://user-images.githubusercontent.com/1377460/40445229-60f47e54-5e80-11e8-862d-9e1f794ab452.png)

In this screenshot, I've removed the explicit 4.0dps padding AppBar adds on the right. This does appear to match the latest spec more closely.

![new](https://user-images.githubusercontent.com/1377460/40445238-675acf8c-5e80-11e8-9912-8ffeb30e6abc.png)

Icons that are intrinsically wider than the popup menu icon will extend slightly past the 16dps margin on the right. This is probably OK, since apps can easily add padding if they want it, but they can't remove built-in padding.

![new](https://user-images.githubusercontent.com/1377460/40445582-6045280e-5e81-11e8-8daf-b0a4e6c61022.png)
