### ISSUE TITLE
Customizing the Floating Action Button notch requires rewriting Floating Action Button

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#16288]
The way Floating Action Button creates a notch in a Bottom App Bar, currently I can't change the notch without completely copying the FAB code to make a new button and a new notch.

I think that we can have a more composable API, where the notch computation and the fab widget are orthogonal constructs.

If that's the way we want the API to work, feel free to close.

**Comment by HansMuller** [comment]
Can you explain why you had to copy the FAB code?

**Comment by DaveShuckerow** [comment]
The code to create the Notch is a part of the private _FloatingActionButtonState, managed [here](https://github.com/flutter/flutter/blob/6a080aa950f076d13690bfc3f6027ef945a0b23b/packages/flutter/lib/src/material/floating_action_button.dart#L303).

I want to try out using different Bezier curves on the edge rounding, but to do that I need to bring all the rest of the code with it.

Ideally, I should be able to pass a ComputeNotch as a parameter to the FloatingActionButton or have a NotchProvider.of(context) that I can set in my app's Theme.

**Comment by DaveShuckerow** [comment]
We discussed this offline, and it seems like the best place to move the notch computation is the Scaffold, since it's defining a boundary between the FloatingActionButton and the BottomAppBar.

We can also expose the computation done by the FloatingActionButton currently as a defaultComputeNotch.

**Comment by amirh** [comment]
I believe originally we thought it will make sense to have the FAB define it's notch, so the shapes of the FAB and the notch are coupled.
If we still think the same we can have the FAB take a ComputeNotch parameter (that has a default value).
Otherwise we can do what Dave suggest - make this a Scaffold parameter.

I'm slightly leaning towards keeping it in the FAB, because I expect the shape of the FAB and the notch to be coupled.

@HansMuller @DaveShuckerow let me know what you think.

**Comment by amirh** [comment]
@DaveShuckerow in the case you mentioned above did you want to replace the entire notch computation or just change the proportional positioning of some control points?

**Comment by HansMuller** [comment]
[per offline discussion with @amirh ]

We could give FloatingActionButton a ComputeNotch valued notchBuilder property. ScaffoldGeometry.floatingActionBarComputeNotch would return the FAB's notchBuilder.

We're hoping that we can remove https://docs.flutter.io/flutter/material/Scaffold/setFloatingActionButtonNotchFor.html. It's unlikely to have been used much and wouldn't be needed anymore.

We'd also provide notch builder functions, with some handy parameters, for circular and diamond shaped notches.

**Comment by amirh** [comment]
Discussing this some more - since Scaffold#floatingActionButton's type is Widget we would not be able to fetch its notch safely without looking at RTTI.

The options we currently consider:

1. uncouple the notch computation logic from the FAB (by adding a ComputeNotch property to Scaffold)
2. have Scaffold check if the type of floatingActionButton is a 'NotchMaker' (name TBD)
3. keep the setFloatingActionButtonNotchFor protocol

**Comment by HansMuller** [comment]
The Scaffold's FAB can be any widget at all, so - for 2 - in addition to making FloatingActionButton implement NotchMaker, we'd probably also have to provide a NotchMakerHolder widget like PreferredSize.

The  setFloatingActionButtonNotchFor protocol doesn't really work, since it has to be possible to build a Scaffold for which the NotchMaker is defined.

I think #1 is the best solution, since it's simpler than 2, and 3 (our current solution) doesn't work in general.

**Comment by DaveShuckerow** [comment]
I agree about option 1 being both simpler and more useful from an API users' perspective.

**Comment by amirh** [comment]
There are 2 issues discussed here:

1. Customizability of the FAB notch (issue raised in the first comment)
2. Changing the notchmaker API so that it is set in a more 'Fluttery' way by passing parameters to Widget constructors.

Looks like we know what to do with `#2`.

Regarding `#1`, @DaveShuckerow  can you help me better understand the bits you wanted to customize? was it the s1 and s2 parameters used in the notch computation? or did you want to completely replace the notch computation logic?

**Comment by DaveShuckerow** [comment]
From an offline discussion, the requirement is the ability to replace the notch computation.

**Comment by amirh** [comment]
Fixed by #18372
