### ISSUE TITLE
Support snapshot metadata in cloud_firestore

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16432]
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/SnapshotMetadata

**Comment by c-born** [comment]
Is anyone looking into this?
I spent ages trying to figure out how to get it to work, without success. The Firebase docs examples for ```Android``` that show this aren't for Flutter/Dart, which had me confused for a bit, and the ```cloud_firestore``` package implements the class, but it doesn't seem to be hooked up, unless there is away to use it I just haven't found.
Strangely some of my searches have found people claiming to have used it (.fromCache in Flutter), but with no code to demonstrate how.
As the flutter plugins are marked Beta, with not all the API implemented, would it make sense to have which are and are not currently supported documented somewhere to save this chasing around?

**Comment by leedstyh** [comment]
looking forward to it, and thinking it's an important feature.

**Comment by JSANL** [comment]
any update on this?

**Comment by ashleygeorgeclarke** [comment]
This is the only thing stopping me from using flutter

**Comment by erparker** [comment]
Adding another _bump_ to this issue, would love to see snapshot metadata supported in cloud_firestore!

**Comment by long1eu** [comment]
@collinjackson can you please assign this to me?

**Comment by daveparks23** [comment]
Looking for an update on this also.  Thanks to everyone helping with this issue.

**Comment by noelmansour** [comment]
It looks like support has been added as of 0.12.9. Thanks!

However, there isn't a flutter equivalent for [`getDocumentChanges(MetadataChanges metadataChanges)`](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/QuerySnapshot.html#getDocumentChanges(com.google.firebase.firestore.MetadataChanges)).

I dove into the android plugin code a bit. `parseQuerySnapshot(QuerySnapshot querySnapshot)` calls [`getDocumentChanges()`](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/QuerySnapshot.html#getDocumentChanges()) to populate the dart `List<DocumentChange> documentChanges`.

In order to get updates when the metadata changes, `getDocumentChanges(MetadataChanges metadataChanges)` should be called instead.  However, this would mean the dart API would no longer match the no-param `getDocumentChanges()`. Alternatively, another field (like `documentChangesIncludingMetadata`) could be added to the `QuerySnapshot` object for this case.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/858. Any further collaboration will be done there.
