### ISSUE TITLE
In dark mode FloatingActionButton and RaisedButton render text with different color even if the foreground color is the same

### ISSUE THREAD

**Issue by AxelMarquez** [flutter/flutter#16488]
In dark mode, when I set the same color for FloatingActionButton and RaisedButton, RaisedButton’s **text** has different color.

![dark](https://user-images.githubusercontent.com/8497432/38651280-f5326436-3dc5-11e8-83bc-5201607829e4.png)
![light](https://user-images.githubusercontent.com/8497432/38651281-f54a4f4c-3dc5-11e8-96b5-9d27aedfb8b0.png)

Is this the expected behavior?

The code for the dark screenshot is the following (for the light one just change dark to light):
```dart
class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {

    return new MaterialApp(
      title: 'Flutter Demo',

      theme: new ThemeData(
        primarySwatch: Colors.orange,
        accentColor: Colors.orange,
        buttonColor: Colors.orange,
        brightness: Brightness.dark
      ),

      home: new Scaffold(
        appBar: new AppBar(title: new Text("Title")),
        body: new ListView(children: [
          new RaisedButton(child: new Text("Hi"), onPressed: () {}),
          new FloatingActionButton(child: new Text("Hi"), onPressed: () {})
        ]) 
      ),
    );
  }
}
```

**Comment by gspencergoog** [comment]
No, I don't think this is the expected behavior.  I think the problem is that the FAB doesn't use the `ButtonTheme`, whereas the `RaisedButton` does.  This should be corrected.

**Comment by HansMuller** [comment]
@AxelMarquez - it's been a long time since you opened this issue and I apologize for the lack of activity. If you're still interested in the topic, there's a wide-ranging proposal for updating the button widgets and their themes in https://github.com/flutter/flutter/issues/54776. The new issue includes a proposal for API that would give one control over the text color of RaisedButtons. If you have time, I hope you'll take a look.

I'm going to close this issue in favor of #54776.

**Comment by flutterq** [comment]
Step By Step Guide to [how to change text color of appbar, icon color of fab universally using theme?](https://flutterq.com/wp-admin/post.php?post=245&action=edit)
