### ISSUE TITLE
No way to access BinaryMessenger from outside Flutter specific classes

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#16490]
There are times when you will want to notify Flutter from outside of a Flutter Activity, ViewController, etc but there is currently (?) no standard mechanism to access the current FlutterView/BinaryMessenger. This usually means resorting to something like:

```kotlin
class FlutterMessenger {
  private val registeredFlutterViews = mutableListOf<FlutterView>()
  companion object {
    val instance: FlutterMessenger = FlutterMessenger()
  }

  fun registerFlutterView(view: FlutterView) {
    registeredFlutterViews.add(view)
  }

  fun hasRegistrations(): Boolean = registeredViews().isNotEmpty();

  fun registeredViews() : List<FlutterView> = registeredFlutterViews

  fun invokeMethod(channel: String, method: String, args: Any? = null) {
    registeredFlutterViews.forEach { fv -> MethodChannel(fv, channel).invokeMethod(method, args) }
  }
}
```

I'm not sure if this is the best approach but it works currently. It would be nice if there was a standard mechanism to do this.

cc/ @xster

**Comment by matthew-carroll** [comment]
I expect this issue to resolve itself with a refactor of the Android embedding.  I have transferred this ticket to that project.

**Comment by matthew-carroll** [comment]
On the Android side I have moved BinaryMessenger to be implemented by an object called FlutterEngine.  A FlutterEngine will be instantiated and held by whatever part of your code wants to show a FlutterUI.  Therefore, I think this issue is resolved for Android in the upcoming embedding release:
https://github.com/flutter/engine/pull/6195

@dnfield I'm going to close this for the Android side.  If this issue makes sense to be tackled on iOS, would you mind filing an appropriate ticket in the platform embedding project?
