### ISSUE TITLE
Maybe Dart2 is not ready

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#16517]
## Steps to Reproduce

After I upgrade to new version of flutter, It's very painful of porting code to Dart2.
Like:
### example 1
```dart
// map = json.decode(...)
List<String> image = map['images']; // very sure map['images'] is valid
```
This is valid in Dart1.x, but crash(not warning) in Dart2.

### example 2
And very popular libraries like test depends on some old packages and conflict with [quiver](https://github.com/google/quiver-dart),fluro... 
I cannot reproduce the conflict in `flutter packages get` .

### example 3
```dart
/// like c++ std::pair
class Pair<Left, Right> {
  const Pair(this.left, this.right);
  final Left left;
  final Right right;

  // List<Pair<Left, Right>> not work 
  // Map<Left, Right> not work
  static Map<dynamic, dynamic> asMap(List<Pair> list) {
    Map map = <dynamic, dynamic>{};
    list.forEach((pair) {
      map[pair.left] = pair.right;
    });
    return map;
  }
}

final namedColors = [
  const Pair<String, Color>("Blue", Colors.blue),
  ...
];

// this cause crash(not warning):
final Map<String, Color> _name2Color = Pair.asMap(namedColors);

// this work well
final Map<dynamic, dynamic> _name2Color = Pair.asMap(namedColors);
```
I don't think Dart2 is completly better than Dart1. And `preview-dart-2` default to `true` maybe not a good idea now. At least after most libraries port Dart2.

Please correct me if I'm wrong. @Hixie

**Comment by rmtmckenzie** [comment]
Your first example, while unfortunate, is incorrect. There's no way that the json can know that all of the elements of the list are strings, as it's quite likely that some of them may be maps or lists in a complex json document, so it is actually a List<Object>. You can then cast the individual elements to Strings without crashing. For dart to be able to cast directly to List<String> in a type-safe way it would have to go through each element and check that it is a string.

You could explicitly do the cast (something like `map['images'].map((el) => el as String).toList()`) if you're sure they're all strings.

Your third example is incorrect as well. Because asMap is static, it doesn't know what `Left` and `Right` are. This would work better (the important part is `asMap<Left, Right>`, although I shortened it a bit too:
```dart
class Pair<Left, Right> {
  const Pair(this.left, this.right);

  final Left left;
  final Right right;

  static Map<Left, Right> asMap<Left, Right>(List<Pair<Left, Right>> list) => new Map.fromIterable(list, key: (el) => el.left, value: (el) => el.right);
}
```
Although personally I wouldn't call it Left & Right in the static method so that someone else doesn't get confused about it.

**Comment by pedia** [comment]
After reading https://www.dartlang.org/guides/language/sound-problems again.
Maybe I should close this now.
