### ISSUE TITLE
Gestures lag at edge of screen

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16529]
When dragging on a list view from the edge of the screen on iOS there is a noticeable delay at the beginning of gesture recognition.

See sample code in https://gist.github.com/tvolkert/05616985d86f90350ff51077c744e00d

![lag](https://user-images.githubusercontent.com/15253456/38702767-4ed4451e-3e56-11e8-98d1-443dfa559725.gif)

**Comment by tvolkert** [comment]
/cc @HansMuller 

This was reported against iOS, but it probably happens on Android too

**Comment by eseidelGoogle** [comment]
Tracked as b/77967901 internally.

**Comment by Hixie** [comment]
I can't reproduce this on tip of tree master on Android.

**Comment by Hixie** [comment]
(either using Android mode or iOS mode)

Could it be that you need to have a route to go back to, and it's the back gesture detector that's interfering?

**Comment by Hixie** [comment]
I replaced the top part of the app with this to test my theory:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Lag Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Builder(
        builder: (BuildContext context) => new GestureDetector(
          onTap: () {
            Navigator.push(context, new MaterialPageRoute(builder: (BuildContext context) => new Scaffold(
              appBar: new AppBar(
                title: new Text('Lag Demo'),
              ),
              body: new FakeCarousel(),
            )));
          },
          child: new Text('TEST'),
        ),
      ),
    );
  }
}
```

I still don't get a problem even in iOS mode, except if I drag from the very left where the Carousel is, but then what's happening is that the iOS back gesture is the one that takes effect (with the jump) because it wins agains the carousel. But that's not what the GIF shows as the original complaint, so...

**Comment by eseidelGoogle** [comment]
I think this may be iOS device specific.  It may not give the events to the app until it decides if the system wants to do system edge gesture?

I can replicate it on my iPhone 6s in the "Leave behind list items" demo in the Gallery when swiping from the right hand side of the screen (so not a back gesture).

**Comment by eseidelGoogle** [comment]
Actually, I don't even have to swipe from the side of the screen at all.  The middle is fine too.

I'm on an iPhone 6s, using Flutter Gallery 0.2.11 (1) from Test Flight.

**Comment by Hixie** [comment]
In the leave-behind demo, there's competing vertical and horizontal gesture detectors, so that's normal. Can you replicate it with the code in the gist Todd pasted above, on an iOS device?

**Comment by eseidelGoogle** [comment]
I haven't tried the code from Todd yet.

@Hixie Does the gesture detector system as written support building scrolling leave-behind interfaces (like Inbox's) without this lag?  If not, do we have a bug about supporting such?

**Comment by knopp** [comment]
I think there are two isssues happening at the same time. 

First is that iOS seems to buffer touch events and then there is a noticeable jump in first touchesMoved event. 

https://stackoverflow.com/questions/49079881/the-first-touchesbegan-and-touchesmoved-have-at-least-one-erratic-jump-how-do-i

I asked about this through Apple developer support but was told to file a bug report instead. It is interesting that UIScrollView doesn't suffer from this. It is possible that they "smoothen" the events - I tried taking the first "jumpy" touchesMoved and distribute it evenly to subsequent events and the movement got much smoother.

Second problem is how flutter handles competing gesture recognizers. It is very limited by only allowing one gesture recognizer at the same time. iOS for example allows both UIPanGestureRecognizer and UITapGestureRecognizer to be active at the same time. After a while one cancelled and the other is contninues. I think this is much better than not having any feedback until kTouchSlop is reached.

**Comment by Hixie** [comment]
> @Hixie Does the gesture detector system as written support building scrolling leave-behind interfaces (like Inbox's) without this lag? If not, do we have a bug about supporting such?

Inbox has the lag too, it's just that instead of sticking the surface to the finger, they add the lag to the entire experience (so you have to drag a few pixels and then it starts moving, whereas we drag a few pixels and then once we know what you want we pretend we were dragging all along).

Architecturally we could do either. We'd have to go through all the places where we do drags and switch from the current model to the other model, which would be some work.

**Comment by xster** [comment]
Tested with sample from Todd. I can reproduce on iOS.
The original screen record's FPS is a bit low but I'm assuming the problem is that drags don't do anything for a while and then suddenly jumps. 

There are 2 iOS specific behaviour on drag as far as I can tell. @knopp correctly touched on one.

1. iOS prevents minor drifts in the middle of drags that became stationary. This prevents scrolls from making unintended minor direction reversals or movements when lifting the finger. There's a threshold of ~3 logical pixels in native scroll lists that we mimic in Flutter. I don't detect an issue there when playing around with the sample code.
2. When the initial drag start doesn't seem "decisive" to iOS, iOS doesn't report any x, y coordinate changes in UITouch events until it decides there's movements. Sometimes it starts reporting coordinate changes after a movement of 1px. I've also reproduced cases of coordinate changes only reported after 12px. 

I'll see if there's a way to get 'rawer' touch metrics from the platform. 

Edge of screen is probably a red herring. I think the issue would be present with `touches*: withEvent:` callbacks on UIViewControllers in general.

**Comment by knopp** [comment]
@xster, the way I see it, 2 depends on whether there is any delay before finger movement. If you move finger immediately after touching, iOS will gather some events and then report one event with big jump. On the other hand if you touch, hold and then move (after being stationary for a while), you get movement reported immediately.

As for being able to get "rawer" touch metrics, I would not hold my breath, at least with public API. I asked about this through developer support and was refunded my ticked and was told to submit bug report. 

The issue can indeed be seen on the UIViewController touch callbacks, regardless of whether it's screen edges or not. It also happens with gesture recognisers, not just raw touch events.

**Comment by knopp** [comment]
Also when testing UIScrollView in simulator there seem to be some drag required until it actually starts scrolling, so maybe simple solution of swallowing the movement until gesture is recognised would be viable solution?

**Comment by xster** [comment]
@knopp I'm not sure if I fully interpreted 'swallowing' the way you meant it but I think I'm thinking along similar lines.

After looking at the native scroll behaviour for a bit more, I think the solution is likely easier than getting 'rawer' touch data. 

It's imperfect reverse engineering but:

1. `touches*: withEvent:` buffers but doesn't really filter any coordinate deltas away. From very gradual indecisive motions to very fast motions, over long periods of time, almost no positional data is lost, just timing data.
1.  Once a scroll is already underway, the `touches*: withEvent:` buffers a lot less. UIScrollView itself still buffers a bit after motion stops but liberally re-transfers the threshold breaking delta back once it starts again.
1. When starting a scroll initially, it behaves differently. Native UIScrollView also triggers a start of a scroll as reluctantly as Flutter when the initial motion is indecisive (this means we don't need more precise timing data). But the native scrollable is also less 'responsive' and loses a lot of actual finger distance traveled when the scroll finally starts vs both scenario 2 and Flutter. 

To make the behaviours match better, #16721 will make stationary threshold breaking drags ease into the scroll to prevent jerks. This hesitant scroll start issue also affects scrolls globally on iOS including pickers etc so we'll adjust it for all iOS scrolls. Since I think iOS's finger motion really maps to acceleration rather than position anyway (#13171), a ease-in moves us slightly more towards the right direction.

**Comment by sethladd** [comment]
Thanks for the fix!
