### ISSUE TITLE
Performing encoding in Image.toByteData() bloats engine binary size

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16537]
In https://github.com/flutter/engine/pull/4762, we added `Image.toByteData()`, returning encoded image bytes (jpg, png, or gif).

On Android, where we don't perform LTO in our engine binaries, this change yielded no substantive change in the release binary size.  This is because the lack of LTO means that on Android, we're already shipping support for image encoding in the engine binary.

On iOS, however, where we _do_ perform LTO, the linking of image encoding libraries yielded an increase of ~90K.

Rather than returning encoded image bytes in `Image.toByteData()`, we should just return unencoded (raw) bytes (RGBA form, row-primary) and leave it up to callers to encode the raw data however they see fit (using something like `package:image` or a platform plugin).

https://github.com/flutter/engine/pull/4762 was first released to the dev channel in `v0.2.10`, which, as of the time of this writing, has not yet hit the `beta` channel.  We should fix this issue in time to make the next beta cut, so that we don't have callers start to depend on the API that returns encoded bytes.

**Comment by majido** [comment]
The binary size bloat is unfortunate. Though I personally don't mind 90K increase for the privilege. 

Another argument in favor of a native support for  "encoding" is to provide some symmetry. As it stands, flutter has builtin supports image decoding but if we go ahead with this fix, then it will require plugins or external library for encoding :-1: .

I wonder if there are way to reduce the 90K cost to to the point that it is acceptable.  Here are some ideas:

## Disable all Skia encoders not used

One idea is to actually disabling all image encoder/decoders that are not used by flutter. Skia exposes a few build vars that control this. See [here](https://codesearch.chromium.org/chromium/src/third_party/skia/BUILD.gn?type=cs&sq=package:chromium&l=25).  Issue #6177 is already proposing this anyways.

Perhaps the PR that enabled encoding is causing all encoders to be included while only 3 are ever used. So turning some off can drive down the size increase? 

## Only include one encoder (e.g., PNG)

I think all we really need to do is to provide a single encoder. Perhaps this can be PNG encoding since
I believe PNG encoding is already for some screenshot feature in flutter in debug mode..

What happens if you remove the other two formats? I suppose that should reduce the size. If necessary we can rework the code so that LTO can detect we are only ever using PNG encoder thus not link the other encoders.

**Comment by tvolkert** [comment]
@majido I agree that we should explore those options -- for callers who wish to get encoded byte data, it's significantly cleaner to get it straight from the engine than to have to do it after the fact (see [this email](https://groups.google.com/d/msg/flutter-dev/yCzw8sutC-E/zo2GZw87BgAJ) by @fmorgado).

That said, there are actually use cases for getting raw byte data (such as wiring it up to pixel diffing tests).  That combined with the desire to remove the 100K binary size (for the majority of apps who *don't* need image encoding, it's just wasted size) means I think we should proceed with https://github.com/flutter/engine/pull/5008, then consider adding a separate `Image.toEncodedByteData()` API with the options you lay out above.

**Comment by majido** [comment]
That is understandable. I agree that it is safer to start by having RAW pixel output first and then consider supporting encoded version and if becomes necessary add bloat to the engine size.


As a side note, instead of  `Image.toEncodedByteData()` it seems nicer to me to have  `Image.toByteData(EncodingFormat)` and have `raw` as the default format which maps to the current RGBA version.

**Comment by tvolkert** [comment]
Follow-up work opened as https://github.com/flutter/flutter/issues/16635
