### ISSUE TITLE
Cannot reference generated code in .dart_tool in a Flutter project

### ISSUE THREAD

**Issue by grandstaish** [flutter/flutter#16603]
## Background
[build_runner](https://github.com/dart-lang/build/tree/master/build_runner) looks to be a great tool for meta programming that I'd like to start taking advantage of more in flutter (e.g. by using [inject.dart](https://github.com/google/inject.dart), which is designed to be platform agnostic). By default, when you set up your [build.yaml](https://pub.dartlang.org/packages/build_config), the `build_to` value is set to "cache". This means that generated files won't be checked into source control, they'll be generated in a hidden folder: `.dart_tool/build/generated`. The problem is, flutter projects can't seem to reference files generated in this folder. 

## Steps to Reproduce
1. Clone [monzo-flutter](https://github.com/grandstaish/monzo-flutter/)
2. Switch to branch [flutter-bug-1](https://github.com/grandstaish/monzo-flutter/tree/flutter-bug-1)
3. Run `flutter packages pub run build_runner build` to build the generated code
4. Run the project.

Result:
All of the code successfully generated in `.dart_tool/build/generated`. However the code cannot be referenced from within `lib/`, hence running the app fails with the following issue:

```
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/brad/Sources/monzo-flutter/lib/app_component.dart
...refers, in an import, to the following library:
  /Users/brad/Sources/monzo-flutter/lib/app_component.inject.dart
Unfortunately, that library does not appear to exist on your file system.
```

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.2.12-pre.33, on Mac OS X 10.13.2 17C88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[!] Connected devices
    ! No devices available
```

**Comment by zoechi** [comment]
If you use `build_to: source` you still can use `.gitignore` to exclude `lib/**/*.g.dart` (or similar)

@jakemac53 @natebosh
Is this supposed to work this way?

**Comment by jakemac53** [comment]
We don't have tight integration with flutter yet, and unfortunately I don't know enough about flutter to know what the "correct" solution is here.

We do have the ability to create a merged output directory (-o <dir>) which flutter could use, and has a valid .packages file.

Unfortunately due to the limitations of .packages files we can't just expose a valid one directly in the root package (think like .build.packages or something), because files can live in 2 locations.

So yes, for now only `build_to: source` builders are going to work with flutter out of the box.

**Comment by natebosch** [comment]
cc @yjbanov

**Comment by grandstaish** [comment]
I can confirm that changing `build_to` to `source` works as a workaround for now, but it clutters up the source files a bit. It's a good workaround for now though.

However, I can't see a way to way set `build_to` from anywhere other than the `inject_generator` library. It seems that consumers of the library can't modify this value, only [enabled, generate_for, and options](https://github.com/dart-lang/build/tree/master/build_config#configuring-builders-applied-to-your-package). Is that true or am I doing this wrong?

**Comment by jakemac53** [comment]
> It seems that consumers of the library can't modify this value, only enabled, generate_for, and options. Is that true or am I doing this wrong?

Yes - that is accurate. It is a bit complicated but generally we want/expect the builder authors to set this. The reason is that some builders really should be `build_to: cache`. If their generated code depends on code from packages you depend on, then it isn't safe to publish those files with your package since their content depends on a particular version solve.

However - this logic doesn't really hold for application packages that never get published, and the convenience/utility of having them in the source tree means we might want to revisit that decision. It is primarily a philosophical limitation not a technical one.

**Comment by natebosch** [comment]
You are correct, `build_to` is not something we expect users to set. Generally Builder authors are in a better position to understand whether it is safe to `pub publish` with the outputs of the Builder. If the generated code depends on other packages in the version solve and might not work with a different version solve in pub, then it shouldn't be published.

**Comment by natebosch** [comment]
After some discussion we will look at whether we can allow consuming code to override this option. https://github.com/dart-lang/build/issues/1303

**Comment by yjbanov** [comment]
We (well, at least I) would like to add formal support for `build_runner` in Flutter tools in a way that would obviate the need for extra options. Ideally you would add a dependency on `package:inject` in your `pubspec.yaml`, sprinkle some `@provide`/`@injector` annotations and have the build system take care of the rest. This will require some planning and effort though. In the mean time workarounds such as `build_to` is the way try things out.

**Comment by jimsimon** [comment]
As an aside (and since I can't create issues on inject's repo), it may be worthwhile to mention some of the limitations for using inject with flutter.  For example, you need to override the `build_to` via a `inject_generator.build.yaml` file.  It also doesn't support named constructor parameters which are used pretty heavily in flutter.

**Comment by jonahwilliams** [comment]
FWIW, I am working on build_runner integration currently and that includes having flutter understand the .dart_tool generated directory. See https://github.com/flutter/flutter/issues/25377#issuecomment-457431642

Re: build to source vs cached - the problem with building to source is that by mixing up source files and generated files you lose the ability to know that something is safe to overwrite. If you generate code once and forget about it that is okay, but if you want a hot reload workflow based around codegen its a real drag.

**Comment by jonahwilliams** [comment]
If you're interested in this issue, please follow (and thumbs up) https://github.com/flutter/flutter/issues/27141

**Comment by jonahwilliams** [comment]
Closed via https://github.com/flutter/flutter/pull/29399, please see  #27141 for more information.
