### ISSUE TITLE
flutter app maker 

### ISSUE THREAD

**Issue by alyfreym** [flutter/flutter#16655]
Hello everybody. Tell me please whether it is possible to create flutter app maker? Like storyboard in Xcode? drug and drop element in window and generate code. in web  similar http://mutisya.com   how it works?

**Comment by PaulHMason** [comment]
It's possible, but it won't be a "proper" drag and drop designer. The web designer you mentioned just uses HTML mockups to represent the Flutter widgets, which isn't the way designers such as the Windows Presentation Designer or WinForms designers work. They create the actual widgets on the design surface, which you can't do with Flutter because it doesn't target desktop environments. Also, Flutter would need to support a "designer mode", because widgets on a design surface need to behave differently than they do in the running application (event handling in particular - e.g. a button click handler on a design surface selects it, but in a running application in invokes the click event handler).

So, in my opinion, until Flutter supports desktop targets and has some sort of designer mode, it isn't really possible. The other question is: do you actually need a designer? I'm incline to say no.

**Comment by zoechi** [comment]
Looks like a dup of flutter/flutter-intellij#2347
