### ISSUE TITLE
Support for share extension in iOS Flutter app

### ISSUE THREAD

**Issue by mrbm** [flutter/flutter#16712]
https://flutter.io/flutter-for-android/#how-do-i-handle-incoming-intents-from-external-applications-in-flutter

Got this to work...but https://flutter.io/flutter-for-ios is empty....

One of the exciting things of flutter is the write once run ios/android...been working magically...until this road block.

Wondering if one of the people on the flutter team more knowledgable than me could add the recipe of how to handle incoming data from external applications into my flutter app in ios.

An example of what I am looking to do in ios that matches the handling incoming intents in android, can be found here:

https://medium.com/@ales.musto/making-a-share-extension-that-accepts-text-and-urls-in-combination-with-coredata-swift-3-a0139c0f9800

Thanks for all your hard work, its been fun!

**Comment by chetdeva** [comment]
I've the same issue. Please help!

**Comment by eseidelGoogle** [comment]
It looks like the answer is:
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html#//apple_ref/doc/uid/TP40014214-CH12-SW1

I'm not sure there is much to use Fluter for here.  The Share Extension shows up in another process, so I suspect it would not be wise to try and bring Flutter code along with, but rather the entire Share Extension should probably be written in Obj-C or Swift.

As far as I can tell this is very different from how Android works, where your actual app would receive the intent (rather than just an extension, paired with your app, which gets loaded briefly into another process during the share action).

**Comment by pulyaevskiy** [comment]
Wondering if anyone had experience implementing share extensions in Flutter apps? I'm gonna need this feature as well.

**Comment by romaluca** [comment]
I implemented a share extension in my flutter app time ago and it worked till about a month ago.
After that if i try to launch my app in ios, i receive this error:

```
ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/FBSDKCoreKit'
    ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/FBSDKLoginKit'
    ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/FirebaseMessaging'
    ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/firebase_messaging'
    ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/flutter_facebook_login'
    ld: warning: directory not found for option '-L/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/google_sign_in'
    ld: library not found for -lFBSDKCoreKit
```

**Comment by pulyaevskiy** [comment]
@romaluca you probably need to check Build Settings of your share extension and remove everything that tries to import Cocoapods from your main project.

At least that's how I solved it in my case. What I managed to get:

1. Created share extension with Obj-C instead of Swift, for some reason it was failing to compile with Swift core libraries not being included in the build. Couldn't figure out how to get it to work.
2. When XCode creates a share extension it copies a lot of Build Settings to it from the main app so I had to manually delete all references to Cocoapods as well as Flutter stuff from there.
3. I used NSUserDefaults to share data between extension and the app, which seems to be a recommended way to do it. But also a fairly simple approach.


If anyone can figure out how to use plugins like Firebase in the extension it would be really great.

The best solution would probably be to embed Flutter into the platform view of share extension. ReactNative guys [seems to have figured out](https://github.com/alinz/react-native-share-extension) how to achieve this so I can imagine it should be doable with Flutter too?

**Comment by bagintz** [comment]
I also need something like this.  Does anyone have any news on available plugins?

**Comment by eqwalker** [comment]
I've edited the Runner workspace to add an Action Extension. When I 'flutter build ios' it just builds the extension and not the runner app. It looks like they are looking for the last target in the project and building that? Seems like they should just build the entire Runner app workspace which should allow the developer to do everything they would in a regular Xcode project (frameworks, extensions etc..).

**Comment by eqwalker** [comment]
or expose the invocation of xcrun in a script so iOS developers can control the process

**Comment by eqwalker** [comment]
found it in flutter/packages/flutter_tools/bin/xcode_backend.sh

**Comment by S60bishoyhanna** [comment]
Any update for this issue ?

**Comment by cdharris** [comment]
Does anyone have any pointers for implementing this?

**Comment by KasemJaffer** [comment]
> I also need something like this. Does anyone have any news on available plugins?

I just built a library for this. 

here is the link https://pub.dev/packages/receive_sharing_intent/

**Comment by cdharris** [comment]
> here is the link https://pub.dev/packages/receive_sharing_intent/

Amazing @KasemJaffer does it support sharing urls from the browser too?

**Comment by KasemJaffer** [comment]
@cdharris not for now. The library supports sharing photos only.

**Comment by berkayoztunc** [comment]
is there any documentation "How do I handle incoming intents from external applications in Flutter" for ios ?

**Comment by dctoai** [comment]
> @cdharris not for now. The library supports sharing photos only.

Hi @KasemJaffer 
I downloaded the example in the link https://github.com/KasemJaffer/receive_sharing_intent/tree/master/example and I have some issues:
1. I **cannot built project in flutter** and it show error
`Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET receive_sharing_intent OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: framework not found receive_sharing_intent
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone XR.`

, but I can build it and run in XCode **however** when I share images to the app, it does not show anything "the number of shared file" is still 0

Did I config wrong somewhere?

**Comment by jerryzhoujw** [comment]
@pulyaevskiy  I have create an empty flutter project and add ShareExtension using Xcode. But how to clean Cocopod for the building errors ?

**Comment by pulyaevskiy** [comment]
If I remember correctly when you add share ext to flutter project it inherits a bunch of configuration, including importing cocoapods. I had to go over all include paths for share extension and remove cocoapods from there.

Not s huge expert in Xcode though.

**Comment by jerryzhoujw** [comment]
Thank you,

Because the setting is same as a `simple iOS project after setup Pods, then include ShareExtension` which works fine.

So I confused which part would cause build different.  That's why I was guess if it's related to any flutter script.

**Comment by iapicca** [comment]
Hi @mrbm 
share plugin appear to work with most ([ipad issue](https://github.com/flutter/flutter/issues/19152)) of ios devices,
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
