### ISSUE TITLE
Verbose mode options to tooling should pass the --verbose-logging flag to the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16730]
Running the tools with verbose mode logging enabled should pass the `--verbose-logging` flag [introduced in the engine in this patch](https://github.com/flutter/engine/pull/5022). This enables logging at severity levels in the engine. By default, logging is only enabled in the ERROR and FATAL levels.

**Comment by ashawe** [comment]
looks like this was implemented in #5022 reverted in [f8021e3](https://github.com/flutter/engine/commit/f8021e378dc2a10209921d2010d9ef1869f4f3a5) and then opened again here

**Comment by Pragya007** [comment]
@chinmaygarde How to proceed for solving this..I would like to contribute.

**Comment by Hari-07** [comment]
@chinmaygarde  If this issue is still to be resolved, i'd like to take it up

**Comment by daadu** [comment]
@Hixie  @chinmaygarde  This issue should be closed. Since #29321 (for ios, android) and #67150 (for dekstop) added this feature.

Following are the code where the flag is passed:
- for Android
https://github.com/flutter/flutter/blob/8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8/packages/flutter_tools/lib/src/android/android_device.dart#L657-L658
- for iOS
https://github.com/flutter/flutter/blob/8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8/packages/flutter_tools/lib/src/ios/devices.dart#L365
- for Desktop
https://github.com/flutter/flutter/blob/8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8/packages/flutter_tools/lib/src/desktop_device.dart#L291-L293

**Comment by daadu** [comment]
Spent hours as it was labelled "good first contribution" and turned out it is already implemented.

Although, I had to go through the code that was very educational.

**Comment by Hixie** [comment]
Haha, I've definitely had that experience before also! Sorry about that!
Hopefully you can put what you learnt to good use in other issues!
