### ISSUE TITLE
remove the use of the --package-warnings flag in `flutter analyze`

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1680]
I don't think we want this flag - this causes all direct and transitively imported packages to be analyzed. We should remove it (and verify that all our packages in the flutter repo are still properly analzyed).

Related to https://github.com/dart-lang/sdk/issues/25722. /cc @Hixie. Happy to experiment w/ this myself (after closing out a few other PRs).

**Comment by Hixie** [comment]
Yeah I had turned this on because I wanted all _our_ direct and transitively imported packages to be analyzed. What I really want to be able to express is "analyze anything that didn't get pulled down by pub". For example, say we analyze a test in the stocks package. I want it to analyze all the stocks files, and all the flutter files that that pulls in, and all the files in the newton package that that pulls in. I'm worried that if we just rely on a test in the newton package pulling in the newton package, it'll actually only be bringing in the few files we happened to have tests for.

This gets less and less problematic as we add more and more tests, of course.

cc @pq

**Comment by pq** [comment]
After talking to @devoncarew and @bwilkerson, I think what we really want longer-term is CLI support for directory-based analysis (https://github.com/dart-lang/sdk/issues/25129).

**Comment by devoncarew** [comment]
Closing this since I think supporting project directories (and directories of project directories) in the dartanalyzer will better support Ian's use case.
