### ISSUE TITLE
Need support for configuring Android's SystemNavigationBar color

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#16837]
App's deployed on Android should be able to request a light or dark navigation bar.

![image](https://user-images.githubusercontent.com/1377460/39079287-28f2c074-44cc-11e8-9f7e-c5c390f8b2cb.png)

It would probably make sense to expose this via the SystemChrome API although there's no comparable iOS feature that I know of. Currently `SystemChrome.setSystemUIOverlayStyle()` doesn't do anything on Android (see [PlatformPlugin.java](https://github.com/flutter/engine/blob/ba98f2634b230f6ce006f8513902c3ad0bd8a6d6/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L225) in the engine).  Not clear if it would make sense for that API to do double-duty, since it means something different on iOS.

**Comment by fmatosqg** [comment]
Indirectly related 2 cents:

I know this is a side issue and maybe not worth mixing with this ticket, but would it be possible to deprecate the name `SystemChrome` and whenever a new method is added to do so in a class with a more appropriate name?

BTW I have previously read about `setSystemUIOverlayStyle` and couldn't figure out what it meant. Until now I had no idea it would have no effect on Android. Is there a way to add something that makes it obvious for the developer that this or that method is not expected to have side effects on a given platform? Something half way between annotation and exception? On one side we could have the `setSystemUIOverlayStyle` and this candidate function mention it in the docs. On the other hand sometimes someone can autocomplete from the IDE and not even notice it.

As a reference, I love when you're writing native android and have neat sugars such as `@UiThread` and when accessing some methods it reads your manifest and puts an error because there's a missing permission. That can make a big difference in the future for learning about what to expect of fuchsia for example.

**Comment by fmatosqg** [comment]
I think there's still room for using annotations during compile but discarding in the AOT. Take as an example some methods introduced in some versions of android. Java discards some annotations after compile time, but it's still enough to FORCE the developer to write statements like this before making possibly forbidden calls:

```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.GINGERBREAD) {
     // call to method introduced in Gingerbread
}
```

Is that along the lines of what you imagine for the analyzer?


PS: can you elaborate what system's chrome means for you? I have never heard it meaning anything else than the browser, which makes me a bit confused when talking about native apps.

PS: I am absolutely no expert in either compilers or analyzers, but as a long time static language user I feel too much is delegated to the analyzer. I'm trying to understand a different point of view, but I'd rather have a very strict compiler that refuses to make AOT builds than dive into crashlytics. All things in their due time, but my struggle is understanding what's the general desired direction, which sometimes can be different than the actual taken direction.

**Comment by fmatosqg** [comment]
This thread covers multiple things that could probably be split into multiple issues in possibly multiple repos (analyzer or compiler, flutter/flutter or flutter/intellij etc), but since for completeness and trying to stay on focus I'll try to give an example on the given topic. A

This is a subset of my wishlist, on how I think things should be to avoid runtime surprises at the expense of being forced to address problems before `flutter build` has the chance of succeeding:

1. Some analyzer errors should be encouraged over warnings (most things should be opt-out) such as `missing_required_param`, `missing_return` `implicit-dynamic` and `implicit-casts`, specially in packages who trickle down to new app writers who have no clue why their Dart 2.0 projects are failing
1. Analyzer errors should block `flutter build` from succeeding in a very easy way, opt-out
1. `SystemChrome.setSystemUIOverlayStyle()` should not be allowed to be called without being wrapped in some form of `if ( TargetPlatform.isFuchsia )` and that needs to be done by the app developer who should be aware that there's no side effect on Android. The same would extend to the method created under this ticket in SystemChrome. Not doing it would cause AOT compiler to not succeeed
1. JIT could use some assistance as well, the trending example is MethodChannel.invoke but there are community written things who are creating problems now that Dart 2.0 is rolling in by default. Upgrading a package for 2.0 compliance with the encouraged practice now involves either 100% unit test coverage or 100% example app coverage
1. And I think Android annotations are a big productivity enablers, so why not? Things like `@StringRes` or `@DrawableRes` are big helpers not only to break the compiler but as well as document things for the next developer. `@Nullable`,  flutter's own `@mustCallSuper` and many more https://developer.android.com/studio/write/annotations#call-super. 

I don't mean to pretend those things are easy or possible, or come without creating other problems, or even that I'm having the best ideas possible.

**Comment by jonahwilliams** [comment]
I'm marking this as fixed by https://github.com/flutter/flutter/pull/17171.  Technically there are some new features introduced by P, but that hasn't released yet :3
