### ISSUE TITLE
Embedded FlutterViewController does not display images (black masks) on second open

### ISSUE THREAD

**Issue by alexwhiteside1** [flutter/flutter#16840]
## Steps to Reproduce

Create a native iOS application and add the Flutter View Controller
Segue to the FlutterViewController -> Everything works fine
Return to the native part of the app
Segure to the Flutter View Controller again -> No images load

Note that restarting the app completely does allow the images to load the first time the view is displayed. 

See Video and screenshots:

<img width="1159" alt="screen shot 2018-04-20 at 8 51 27 pm" src="https://user-images.githubusercontent.com/5420059/39080110-0756de30-44dd-11e8-9e36-2ef75adeff02.png">

Video: https://drive.google.com/file/d/13_RCLNo16HdGzegDTulLkr2CL2TK8eM5/view?usp=sharing

## Logs

No errors are displayed

## Flutter Doctor

[✓] Flutter (Channel dev, v0.2.11, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (2 available)

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @cbracken is this something you'd be able to take a look at for customer:windy?

**Comment by chinmaygarde** [comment]
This was happening because images uploaded asynchronously to the GPU on the IO thread were kept in a different context. We used to persist a single instance of this context across multiple Flutter applications. This context should have been torn down and created again when a new instance of the `FlutterViewController` is created. This was fixed in framework versions `v0.3.2` and later. I have verified this with a reduced test case as shown below. In the attached example, the recipe images are uploaded to the GPU thread asynchronously on the IO thread.

![2018-04-30 16_23_42](https://user-images.githubusercontent.com/44085/39455087-95d35c70-4c93-11e8-957e-a444f2debfd9.gif)

@alexwhiteside1: When you return back to the native view, do you fully unload and destroy the Flutter view controller? If so, my reduced test case matches this behavior and updating to the latest framework should fix your issue.

**Comment by alexwhiteside1** [comment]
@chinmaygarde  working great now after updating. Thanks. 

Do you know of any way to 'preload' the view controller so the splash screen doesn't show before the segue?  Not a huge deal, but annoying enough if there are multiple native -> flutter transitions.

**Comment by chinmaygarde** [comment]
The first frame is rendered asynchronously on the GPU thread and the launch screen is used to hide the uninitialized frame contents. The storyboard used for this purpose is the one specified by `UILaunchStoryboardName`. We should probably make this configurable. I have [filed an issue](https://github.com/flutter/flutter/issues/17140) for this.

In a pinch, and this is a massive hack, you could instantiate the FlutterViewController, call the view property on it, iterate over the subviews and remove any instances that are not FlutterView class (NSClassFromString(@"FlutterView")) instances. Again this is a massive hack and we should address this use case by fixing the issue filed. But, if you are blocked, this technique could come in handy.

**Comment by chinmaygarde** [comment]
I am going to close this issue as the ToT contains a fix. Please re-open is there are edge cases not handled.
