### ISSUE TITLE
Unable to retrieve logs from iOS 8

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#16903]
When doing a `flutter run --profile` on an iOS 8 device, the last step (installation and launch) never completes because flutter_tools doesn't seem to be able to see the logs from the device. In the Console app I can see the logs just fine.

**Comment by jmagman** [comment]
I know this was created awhile ago, but do you remember why installation and launch failed?  Was it stuck?  Or could it not connect to the observatory?  Was it only in `--profile`?
Wondering if this is https://github.com/flutter/flutter/issues/46705 or will be fixed by https://github.com/flutter/flutter/issues/46724 but I don't really I have enough info to tell.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
