### ISSUE TITLE
Is something wrong in firebase_messaging example? showDialog without BuildContext

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#16958]
Code in [Here](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/lib/main.dart#L119), Is *context* valid or not?

```Dart
void _showItemDialog(Map<String, dynamic> message) {
    showDialog<bool>(
      context: context,
      builder: (_) => _buildDialog(context, _itemForMessage(message)),
    ).then((bool shouldNavigate) {
      if (shouldNavigate == true) {
        _navigateToItemDetail(message);
      }
    });
}
```

Is this wrong?

And my question is 
How to show dialog in APNS or some other situations without BuildContext?
How to access Navigator.of(context, rootNavigator: true).push in APNS without BuildContext?

**Comment by exavolt** [comment]
As we can see in the documentation of `[showDialog](https://docs.flutter.io/flutter/material/showDialog.html)`, `builder` parameter has a type of `[WidgetBuilder](https://docs.flutter.io/flutter/widgets/WidgetBuilder.html)`, and `WidgetBuilder` is a typedef of function signature which accepts `BuildContext`.

So, in above example, `builder: (_)` is a function which accept a parameter but that parameter will be ignored because it's assigned to `_`. And it seems that, here, the `context` used in `_buildDialog(context, _itemForMessage(message))` is taken from class instance's `context` property rather than from the parameter. You should be able to use this `context` here.

Or you can change it to `builder: (BuildContext innerContext) => ...`.

**Comment by pedia** [comment]
Thank you. @exavolt
The first argment ‘context’ of showDialog(Line 119) is not valid and marked as required.

**Comment by pedia** [comment]
I found context property. 
```
class State{
BuildContext get context => _element;
}
```
