### ISSUE TITLE
flutter_tester exits after finishing main, but "flutter run" does not on a real device

### ISSUE THREAD

**Issue by scheglov** [flutter/flutter#16963]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

This app:
```dart
main() {
  print('Hello!');
}
```

  When run using flutter_tester exists right after printing on the console.
```
/Users/scheglov/Source/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --non-interactive --enable-checked-mode --use-test-fonts --packages=/Users/scheglov/dart/flutter-projects/test_sink/.packages /Users/scheglov/dart/flutter-projects/test_sink/lib/hello2.dart
```

  But when I run it using `flutter run lib/hello2.dart` it prints `I/flutter (22303): Hello!` and stays running:
```
🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel 2 is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
I/FlutterActivityDelegate(22303): onResume setting current activity to this
```

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
Flutter 0.2.12-pre.18 • channel unknown • unknown source
Framework • revision 440a821865 (9 days ago) • 2018-04-16 10:51:40 -0700
Engine • revision 4db7a00677
Tools • Dart 2.0.0-dev.47.0.flutter-4126459025
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

@chinmaygarde

**Comment by DanTup** [comment]
When flutter_tester is used outside of flutter_run maybe this is reasonable functionality; but it's not so good if you're trying to test against `flutter run` (eg. trying to write integration tests for an editor).

Maybe flutter_tester needs a flag about whether to hang around or quit, and if it's invoked by flutter_run it should stay alive until flutter_run shuts down?

**Comment by chinmaygarde** [comment]
`flutter_tester` has a `--run-forever` flag that will ensure that the application hangs around. You can find all `flutter_tester` flags currently supported using the `--help` command.

Does this solve your issue?

**Comment by chinmaygarde** [comment]
And you're right, this behavior is different on the mobile shells because we cannot terminate the application process after `main` as there could be other non-Flutter things pending in the process. OTOH, the only job of the Flutter tester is to wait for the test to finish. So after the root isolate has no live ports, the event loop is torn down (unless you pass the flag). The other way to keep the process around would be to do something that sets up ports (timers, IO, etc.).

**Comment by scheglov** [comment]
Thank you!

I tried to use older version of Flutter (and engine), and `--run-forever` did not work - the app was still terminating right after exit from main.

Then I updated Flutter and ran `flutter upgrade`, and now the app does not exit even without the `--run-forever` flag. But when I `--disable-observatory` it behaves as expected - exists without `--run-forever` and continues to run with it.

I will update the `flutter-tester` device in flutter tools to pass this flag.

**Comment by chinmaygarde** [comment]
> I tried to use older version of Flutter (and engine), and --run-forever did not work - the app was still terminating right after exit from main.

This was a bug in the Mac version of the tester that was not present on Linux. This has now been fixed as all platforms (even Windows) use the same tester target.

> Then I updated Flutter and ran flutter upgrade, and now the app does not exit even without the --run-forever flag. But when I --disable-observatory it behaves as expected - exists without --run-forever and continues to run with it.

This also matches tester behavior on other platforms. The observatory counts as a live port in the VM and we will defer termination of the shell till the observatory is torn down or not started in the first place.

**Comment by DanTup** [comment]
Ok, I think flutter_tester is working fine, but there may be an issue with `flutter run` spawning it. I've opened #16996 with all the details. Thanks both!

**Comment by zoechi** [comment]
Sounds like Observatory protocol is going to be removed https://github.com/flutter/flutter/pull/15876
Just thought this might be relevant here.

**Comment by DanTup** [comment]
I *think* it might actually mean removing the inspector's API from Observatory (so the normal debugging API and service extensions for things like toggling debug painting will remain), otherwise it'd be a big breaking change. @jacob314 can you confirm that's the case, and this won't affect me (since I don't have an Inspector implementation).

**Comment by jacob314** [comment]
https://github.com/flutter/flutter/pull/15876 only impacts the inspector not other APIs over the observatory protocol.

**Comment by DanTup** [comment]
Great, thanks for confirming!

**Comment by DanTup** [comment]
@chinmaygarde I opened #17045 because this still wasn't working as expected, but I think the issue is still in flutter_tester not flutter_tools. If we don't pass `--run-forever` flutter_tester seems to quit after two frames, even while we're connected to Observatory. I connect to Observatory and send a `Resume` to start things, but it just quits. If we pass `--run-forever` then it remains active.
