### ISSUE TITLE
Themes no longer change in Stocks app after toggling performance overlay

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1701]

**Comment by Hixie** [comment]
I can't repro this.

**Comment by Hixie** [comment]
Well, it seems this is something to do with the Inherited logic.

**Comment by Hixie** [comment]
Specifically, after switching the performance overlay on and off, the hashCode of the Theme that is built no longer matches the hashCode of the Theme that is found using Theme.of.

**Comment by Hixie** [comment]
Note that this happens immediately, not just once you try to change theme.

**Comment by Hixie** [comment]
My suspicion is that our inherited map isn't being updated properly. The top of the tree changes, but through reprojection the bulk of the tree stays the same, and this results in that part of the tree still pointing at the old stuff. What I don't understand is why this doesn't break more (e.g. why does changing themes ever work?).

**Comment by Hixie** [comment]
Yeah, we're not calling `_updateInheritance()` on children that we're not rebuilding.

Ideally we'd find a way to do an efficient walk of the tree, hitting only the InheritedElement nodes, and making them update their map.

Alternatively we could use a data structure that looks like a map but is actually just a simpler copy of the full tree, containing only the elements. Or something in between, where the map has knowledge of the tree structure, so it can efficiently and correctly update itself when the tree is mutated, but caches locally, so that lookup is amortized O(1).

**Comment by abarth** [comment]
We could check whether the map matches (by object identity).  If it does match, then there's nothing to update.

**Comment by abarth** [comment]
Here's an approach:

1. Instead of using a regular map, we subclass map for this purpose.  We add a "defunct" bit and a list of derived maps.
2. When replacing the map for an inherited widget, we mark the old map as defunct and walk the tree of derived maps to also mark them as defunct.
3. When querying a map, if its defunct, we walk the parent chain to the next non-defunct map and recreate the maps along that path in the tree.

**Comment by abarth** [comment]
Here's another approach:

1. Instead of using maps, each widget keeps track of its ancestor inherited widget.
2. When updating a child whose widget hasn't changed, check if its ancestor inherited widget is correct.  If not, walk its subtree and repair the ancestor inherited widget field down to the next inherited widget.
3. To query for an inherited property, walk up the ancestor inherited widget chain.

**Comment by abarth** [comment]
The way we do this in CSS is that we just walk the whole subtree to fix up the maps, btw.  That might be the simplest place to start.  (Before walking the subtree, we check if the map is already correct and if so skip the walk---this is the common case.)

**Comment by Hixie** [comment]
This needs tests before it can be truly addressed. I'm tracking that as a separate bug here: https://github.com/flutter/flutter/issues/2438

**Comment by abarth** [comment]
Currently repros with enabling/disabling the material grid.
