### ISSUE TITLE
Failed assertion: line 38 pos 12: 'displayName != null': is not true

### ISSUE THREAD

**Issue by freebumba27** [flutter/flutter#17048]
Getting error while trying google sign in with firebase auth -
`Failed assertion: line 38 pos 12: 'displayName != null': is not true`

Using same as the documented code -

```
Future<FirebaseUser> _handleSignIn() async {
final GoogleSignIn _googleSignIn = new GoogleSignIn();
GoogleSignInAccount googleUser = await _googleSignIn.signIn();

GoogleSignInAuthentication googleAuth = await googleUser.authentication;
FirebaseUser user = await _auth.signInWithGoogle(
  accessToken: googleAuth.accessToken,
  idToken: googleAuth.idToken,
);
print("signed in " + user.displayName);
return user;
}
```

`firebase_auth: "^0.5.5"`
`google_sign_in: "^3.0.2"`

**Comment by darshankawar** [comment]
@freebumba27 
This seems to be an issue related to firebase plugins for which there's a separate repo to track: https://github.com/FirebaseExtended/flutterfire/issues

Also, this seems to be an implementation issue rather than issue in plugin, so I suggest you to ask this question on support channels like StackOverflow.
Closing from here.
