### ISSUE TITLE
flutter.io/install is missing 0.3.1 for Windows

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#17190]
## Steps to Reproduce

Visit https://flutter.io/setup-windows/

Notice it still has 0.2.8

**Comment by mit-mit** [comment]
cc @tvolkert @gspencergoog

**Comment by tvolkert** [comment]
Linux and MacOS are fine -- seems to only be Windows that's affected.

**Comment by gspencergoog** [comment]
I think this is because the packaging [build for the last beta](https://build.chromium.org/p/client.flutter/builders/Windows%20Flutter%20Packaging/builds/29) aborted (before it ever got to packaging).  I've told it to rebuild, and if it fails again, we might have to make a fix to the buildbot to fix it.

It aborted because it couldn't find a buildbot script:
```
E:\b\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe: can't open file '../../../scripts/slave/annotated_run.py': [Errno 2] No such file or directory
program finished with exit code 2
```

**Comment by gspencergoog** [comment]
Also, it appears that the Buildbot used to build that failed build (it was the last thing that it built) is offline still, so we should bring it back online.

**Comment by gspencergoog** [comment]
OK, this is fixed.  I just had to re-run the broken buildbot run.
