### ISSUE TITLE
When generating golden files, catch the case of orphan files

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17360]
Sometimes when writing a test you change your mind about what file names to use, but you do so after having run it with the old names, and then check in the unused files. We should be able to catch that case since when generating goldens we know every test we run and know every file it generated.

This might require that we put files from tests in a directory specific to the test.

cc @tvolkert

**Comment by kf6gpe** [comment]
@Piinks, is this something we're doing with the new golden work you've done? Should we table this as a good pending enhancement?

**Comment by Piinks** [comment]
As I am understanding it, I don't think that this is an issue anymore since our golden file management is handled by Gold. 

We don't manually check in images anymore, only those generated by a given pull request can be approved in triage, and those that aren't approved are disposed of. For older files, IIRC, any old files that are no longer being drawn are also disposed after 100 commits.

**Comment by kf6gpe** [comment]
Great, thank you! I'm going to close this based on that.
