### ISSUE TITLE
ListView nested in Fixed height container that content overflows bug

### ISSUE THREAD

**Issue by qiaoyuwen** [flutter/flutter#17426]
This is the resulting picture:
![wechatimg48](https://user-images.githubusercontent.com/8097860/39815093-921c5b3a-53c9-11e8-9215-f956ed1cfe48.png)

This is my code:
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Test'),
        ),
        body: new Row(
          children: <Widget>[
            new Expanded(
              child: new Container(
                height: 500.0,
                decoration: new BoxDecoration(
                    border: new Border.all(
                      color: Colors.red,
                    )
                ),
                child: new ListView.builder(
                  itemCount: 50,
                  itemBuilder: (BuildContext context, i) {
                    return new Container(
                      height: 50.0,
                      child: new Text('test1 $i'),
                    );
                  },
                ),
              ),
            ),
            new Expanded(
              child: new Container(
                height: 500.0,
                /*decoration: new BoxDecoration(
                    border: new Border.all(
                      color: Colors.black,
                    )
                ),*/
                child: new ListView.builder(
                  itemCount: 50,
                  itemBuilder: (BuildContext context, i) {
                    return new Container(
                      height: 50.0,
                      child: new Text('test2 $i'),
                    );
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

There different of the ListViews only they parent Container one has a border and one does not, the ListView does not have a border then it's content overflows.

## flutter version 0.4.0

**Comment by luizjunior05** [comment]
That happened to me too.

![captura de tela de 2018-06-01 19-30-20](https://user-images.githubusercontent.com/5141762/40866094-4eaa8de8-65d2-11e8-9d62-374e903a6b38.png)

This is my code:
```dart
new Container(
  height: _allArea.length>3 ? 150.0 : _allArea.length*50.0,
  margin: EdgeInsets.only(left: 40.0),
  decoration: new BoxDecoration(
    color: Colors.white,
    border: new Border.all(color: theme.dividerColor)
  ),
  child: new ListView.builder(
    itemCount: _allArea.length,
    primary: false,
    itemBuilder: (BuildContext context, int index) {
      return new InkWell(
        onTap: (){_selectArea(_allArea[index]);} ,
        child: _sugestions(_allArea[index], theme),
      );
    },
  ),
)
```
**Flutter version: 0.4.4**

**Comment by Hixie** [comment]
Weird, maybe the ListView isn't properly clipping?

Can you attach the result of pressing "t" and "L" in the `flutter run` console? (This will dump the render tree and the layer tree).
Maybe also a screenshot of what happens when you press "p" (enables debugPaintSizeEnabled).

cc @goderbauer @liyuqian @HansMuller

**Comment by goderbauer** [comment]
Just looked into this a little bit locally: In the error case the viewport does not clip because `hasVisualOverflow` evaluates to false here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/viewport.dart#L514-L518

In the case where the viewport does clip, `hasVisualOverflow` is set to true in `updateOutOfBandData`:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/viewport.dart#L1330-L1341

Need to do some more digging to figure out why the sliver children in one case think that they do not overflow.

**Comment by goderbauer** [comment]
I believe this is an unintended side-effect of adding the `cacheExtent` to the viewport (in fact, if you set `cacheExtent: 0.0` on the ListView in question everything works as expected). The problem is probably that the SliverList calculates `hasVisualOverflow` based on the `cacheExtent` and not the `paintExtent` here: 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_list.dart#L283

I'll be looking into a fix.

**Comment by luizjunior05** [comment]
Thanks @goderbauer , it really works as expected.

**Comment by goderbauer** [comment]
@luizjunior05 Just FYI: If you set `cacheExtent: 0.0` you reduce the accessibility of your app on iOS. I would not recommend shipping that.

**Comment by goderbauer** [comment]
See also: https://github.com/flutter/flutter/issues/18368 and https://github.com/flutter/flutter/issues/17716, which are both caused by the same bug.

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/how-to-put-two-listview-in-a-column

Similar issue at there

**Comment by klaszlo8207** [comment]
any new on this? Is it fixed?
