### ISSUE TITLE
Waiting for another flutter command to release the startup lock...

### ISSUE THREAD

**Issue by sathishbalan** [flutter/flutter#17422]
Waiting for another flutter command to release the startup lock...

**Comment by zoechi** [comment]
Do you have `flutter packages pub build_runner watch` running?
Kill all dart processes and try again or restart the computer.

**Comment by zoechi** [comment]
@sathishbalan is this still an issue?

**Comment by zoechi** [comment]
Might be a dup of #14703

**Comment by haoma2012** [comment]
yes, get it; it is work

**Comment by YobMe** [comment]
Kill the terminal using the delete (trash) icon if you are using a Visual Studio Code editor

**Comment by D19cannon** [comment]
Hi!
 i'm still having the same issue and @zoechi didn't work for me.

What I noticed is that there is an issue with the 'pub' tool ==> 'build_runner is not found' and that there is an exit code 64 for involved (what ever that means) I looked it up in the documentation, but without any success...

Hopefully, this will be useful for some one to solve the solution!

<img width="576" alt="screen shot 2018-08-15 at 15 12 50" src="https://user-images.githubusercontent.com/14916043/44147723-ea8ba4d0-a09d-11e8-91ba-1a9ebfb687b7.png">

**Comment by CompileYouth** [comment]
You can: rm ./flutter/bin/cache/lockfile

**Comment by shavigrewal** [comment]
This issue also occurs due to internet proxies ,make sure that you have full network access .

**Comment by ztz12** [comment]
you can open flutter/bin/cache/lockfile ,and delete this lockfile ,I solve this problem by this

**Comment by sbefort** [comment]
On OSX:
`rm /Applications/flutter/bin/cache/lockfile`

**Comment by wosilove** [comment]
> On OSX:
> `rm /Applications/flutter/bin/cache/lockfile`

delete 'lockfile',It is work

**Comment by GuoZhiQiang** [comment]
Thanks !  @CompileYouth

**Comment by whataa** [comment]
another way On OSX:
open activity monitor and find process named 'dart', kill it.

**Comment by edycarreyes99** [comment]
> This issue also occurs due to internet proxies ,make sure that you have full network access .

And what about if we have a proxy. What can we do to fix it?

**Comment by mareksip** [comment]
In my case, there was an `flutter packages get` command running in the background. As it was looking for package that did not exist due to incorrect name, changing this package name fixed the issue.

` [eamper-app] flutter packages get
Running "flutter packages get" in eamper-app...                 
Because eamper depends on ffirebase_core any which doesn't exist (could not find package ffirebase_core at https://pub.dartlang.org), version solving failed.

pub get failed (69) -- attempting retry 1 in 1 second...

Because eamper depends on ffirebase_core any which doesn't exist (could not find package ffirebase_core at https://pub.dartlang.org), version solving failed.

pub get failed (69) -- attempting retry 2 in 2 seconds...

Because eamper depends on ffirebase_core any which doesn't exist (could not find package ffirebase_core at https://pub.dartlang.org), version solving failed.

pub get failed (69) -- attempting retry 3 in 4 seconds...

Because eamper depends on ffirebase_core any which doesn't exist (could not find package ffirebase_core at https://pub.dartlang.org), version solving failed.

pub get failed (69) -- attempting retry 4 in 8 seconds...
Running "flutter packages get" in eamper-app...                    23,0s
exit code 0
[eamper-app] flutter packages get
Running "flutter packages get" in eamper-app...                     1,4s
exit code 0
`

**Comment by ripperhe** [comment]
Find the folder where flutter is installed, and delete `flutter/bin/cache/lock` file

**Comment by yuanchen1** [comment]
run flutter clean

**Comment by skaterdude** [comment]
flutter clean won't run either. If I delete the flutter.bat.lock file, it will run clean, but the "Waiting ..." message still comes up when I restart the idea.  Have to reboot my computer to be able to delete lockfile, even when the IDE is shut down. Doesn't fix the problem.

**Comment by loolooii** [comment]
`flutter clean`, changing networks, deleting lockfile, killing dart processes and restarting computer did not work for me. I'm starting to think maybe this happens on specific devices. Going to try that.

**Comment by AdrianBinDC** [comment]
I suspect flutter would get more corporate adoption if it were easier to use in a corporate environment. Might want to figure out a way to remove all the proxy hoops that need to be jumped through to use it.

**Comment by saadnoor** [comment]
Restarting the terminal worked for me.

**Comment by JohnnyQQQ** [comment]
Still having this problem, nothing seems to clear it.

**Comment by vigneshwaranvelmurugan** [comment]
killall -9 dart

**Comment by yanjiepeng** [comment]
delete lock file not worked for me.

**Comment by athlan20** [comment]
> You can: rm ./flutter/bin/cache/lockfile

that'is it,thx

**Comment by codingcity4747** [comment]
I had tried all the solution mentioned above, and nothing works for me and creating flutter application dialog goes forever, but what I did is, end AS task and open it again but this time instead of creating a new project, I just opened the project I just exit from it, and it opens fine,
what causes this problem, I think when I tried to load a picture from image.asset 
after creating a new dir asset/images/pic.jpg and add the asset in pubspec.ymal
when getting the package or something, that's when all this happened
Conclusion: 
just create a new project, and when Creating flutter project dialog appear close Android studio from Task manager, then open it again but this time open an existing project which is the previous one
hope that works for you

**Comment by yanjiepeng** [comment]
there may be a way to resolve this problem 
just install another version of dart
update environment variables 
it will be fixed

**Comment by BhatiPankaj** [comment]
just delete the flutter/bin/cache/lock file and then do flutter upgrade in ide and it will resolve your problem.

**Comment by BhatiPankaj** [comment]
just delete the flutter/bin/cache/lock file and then do flutter upgrade in ide and it will solve your problem.

**Comment by LucasJorgeHubert** [comment]
just remove lock file and restart my Mac work for me

**Comment by msndvlpr** [comment]
I solved the problem by opening task manager and killing the 'dart.exe' process(es)

**Comment by hgadjan** [comment]
> You can: rm ./flutter/bin/cache/lockfile

Work for me, 
thank you

**Comment by originalix** [comment]
@CompileYouth That's wored for me. Thanks

**Comment by rahmanrezaee** [comment]
In my case, following command in Terminal or cmd helped (as suggested by Günter):

    killall -9 dart

On Windows (as suggested by upupming):

    taskkill /F /IM dart.exe

or remove this file

    <YOUR FLUTTER FOLDER>/bin/cache/lockfile

This releases the occupied lock and makes you able to run other commands.

**Comment by zacdaryl** [comment]
On Mac, open Activity Monitor, search dart, then quit all dart process
