### ISSUE TITLE
Cannot get google_maps example to work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#17475]
1. git clone the plugins repo
1. open `packages/google_maps_flutter/example` in editor
1. create a new maps API key
1. add key in `AndroidManifest.xml`
1. run app

=> map appears with no content in it

It was working a few days ago, but doesn't seem to work anymore

**Comment by mit-mit** [comment]
cc @gerryhigh

**Comment by mit-mit** [comment]
cc @mravn-google did anything change?

**Comment by mravn-google** [comment]
Recent changes include removing use of the `new` keyword. It works fine for me when using the CLI tools. Using Android Studio, there does seems to be a problem:
```
05-10 22:05:11.385 28645-28671/io.flutter.plugins.googlemapsexample E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    NoSuchMethodError: Attempted to use type 'MapUiPage' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the MapUiPage constructor and forget the 'new' operator?
    Receiver: MapUiPage
    Tried calling: MapUiPage()
    #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
    #1      _allPages (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:14)
    #2      _allPages (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:13)
    #3      main (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:48)
    #4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165) 0
```
I get a blank screen, the whole app is gone, not just the map.

**Comment by mit-mit** [comment]
Testing was on macOS, running from the terminal. It works for me against the iOS Simulator, but not against the Android emulator.

Log output:

```
$ flutter run -d And
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleDebug'...                           3.2s
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate( 6450): onResume setting current activity to this
D/        ( 6450): HostConnection::get() New Host Connection established 0xde698740, tid 6468
D/EGL_emulation( 6450): eglMakeCurrent: 0xdcf404a0: ver 3 0 (tinfo 0xde6832a0)
Syncing files to device Android SDK built for x86...         2.2s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8105/
For a more detailed help message, press "h". To quit, press "q".
I/zzbz    ( 6450): Making Creator dynamically
W/zygote  ( 6450): Unsupported class loader
W/zygote  ( 6450): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule( 6450): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:219
I/DynamiteModule( 6450): Selected remote version of com.google.android.gms.maps_dynamite, version >= 219
W/zygote  ( 6450): Unsupported class loader
W/zygote  ( 6450): Skipping duplicate class check due to unsupported classloader
I/Google Maps Android API( 6450): Google Play services client version: 11910000
I/Google Maps Android API( 6450): Google Play services package version: 12521024
I/zygote  ( 6450): Do partial code cache collection, code=29KB, data=22KB
I/zygote  ( 6450): After code cache collection, code=29KB, data=22KB
I/zygote  ( 6450): Increasing code cache capacity to 128KB
D/        ( 6450): HostConnection::get() New Host Connection established 0xc58fcd40, tid 6517
D/EGL_emulation( 6450): eglCreateContext: 0xbfb3c800: maj 1 min 0 rcv 1
D/EGL_emulation( 6450): eglMakeCurrent: 0xbfb3c800: ver 1 0 (tinfo 0xba17f170)
D/EGL_emulation( 6450): eglMakeCurrent: 0xbfb3c800: ver 1 0 (tinfo 0xba17f170)
W/DynamiteModule( 6450): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 6450): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule( 6450): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/zygote  ( 6450): Unsupported class loader
W/zygote  ( 6450): Skipping duplicate class check due to unsupported classloader
```

**Comment by mravn-google** [comment]
OK, I can repro the missing map on Android Emulator. As the map view is an overlay, this is most likely not Flutter related. Maybe the emulator has an outdated version of Google Play services. Will investigate.

**Comment by mravn-google** [comment]
With an API level 27 Pixel emulator, the map appears just fine.

**Comment by mit-mit** [comment]
It's also working for me after upgrading to API level 27. @gerryhigh can you try the same?

**Comment by gerryhigh** [comment]
Yes, I can confirm that it works after updating my emulator to API level 27 it works. I'm still doing other testing to get it working in my app. So far I've seen some bugs but not enough to determine what is causing it. Anyhow, this issue seems to be working now. I have not tested this on a device running a pre API 27 version. Thanks

**Comment by mit-mit** [comment]
Thanks. If you find concrete issues, please file new bugs!

**Comment by gerryhigh** [comment]
I will be working with it today. As far as the errors, I saw some errors thrown in the console that could have been memory related. I'll keep testing.

e.g. ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (17911): The following assertion was thrown while dispatching notifications for GoogleMapController:
I/flutter (17911): setState() called after dispose(): MapUiBodyState#be1d9(lifecycle state: defunct, not mounted)
I/flutter (17911): This error happens if you call setState() on a State object for a widget that no longer appears in

 When the exception was thrown, this was the stack:
I/flutter (17911): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1090:9)
I/flutter (17911): #1      State.setState (package:flutter/src/widgets/framework.dart:1116:6)
I/flutter (17911): #2      MapUiBodyState.initState.<anonymous closure> (file:///C:/projects/flutterdev/plugins-master/packages/google_maps_flutter/example/lib/map_ui.dart:57:7)
I/flutter (17911): #3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:161:21)
I/flutter (17911): #4      GoogleMapController._handleMethodCall (file:///C:/projects/flutterdev/plugins-master/packages/google_maps_flutter/lib/src/controller.dart:94:9)
I/flutter (17911): #5      GoogleMapController.init.<anonymous closure> (file:///C:/projects/flutterdev/plugins-master/packages/google_maps_flutter/lib/src/controller.dart:78:20)
I/flutter (17911): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:326:55)
I/flutter (17911): <asynchronous suspension>
I/flutter (17911): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:299:54)
I/flutter (17911): #8      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
I/flutter (17911): <asynchronous suspension>
I/flutter (17911): #9      _invoke3 (dart:ui/hooks.dart:162:13)
I/flutter (17911): #10     _dispatchPlatformMessage (dart:ui/hooks.dart:75:5)
I/flutter (17911): 
I/flutter (17911): The GoogleMapController sending notification was:
I/flutter (17911):   Instance of 'GoogleMapController'

etc.

 Another exception was thrown: setState() called after dispose(): MapUiBodyState#be1d9(lifecycle state: defunct, not mounted)

**Comment by mit-mit** [comment]
Got it. For things you can repro, new bugs (with description, repro steps, steps, etc.) much appreciated!

**Comment by mravn-google** [comment]
@gerryhigh The error reported above should be fixed by https://github.com/flutter/plugins/pull/576. It is an error in the example app, not with the `google_maps_flutter` plugin itself. This kind of error happens when some kind of listener added in `State.initState` is not removed in `State.dispose`, and then fires after the `State` object is no longer mounted, cf. the discussion in https://docs.flutter.io/flutter/widgets/State/initState.html.

**Comment by fritz-flaconi** [comment]
I have the same issue - both on iOS and Android emulators. The example app for Google Maps seems do to everything - except display map images. When I click and drag in the area where the map should be it it tells me the map is moving and changes the coordinates. There are no error messages. There are simply no images except for the Google logo bottom left corner (which changes to the more anti-aliased version when I change the MapType to Satellite)
