### ISSUE TITLE
Gallery has X's where icons should be

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#17485]
Just installed the new Gallery on my Android phone, from https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&rdid=io.flutter.demo.gallery

This is what I see:

![screenshot_20180510-140723](https://user-images.githubusercontent.com/5479/39894443-b548690e-545b-11e8-8be4-69d8df3410d9.png)

My "about gallery" says "April 2018 Preview".

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by xster** [comment]
Hey Seth, what version did the Play Store install? And which phone is it?

**Comment by ryanmt** [comment]
I'm on a pixel XL and play store lists 0.4.2. I also see this issue after receiving an update 6 hours ago.

**Comment by HansMuller** [comment]
Yesterday Xiao and I tried installing the gallery from the Play Store on a few phones; so far we're not seeing the problem. Will keep looking...

**Comment by ryanmt** [comment]
I just installed the p beta release as well.

**Comment by matharumanpreet00** [comment]
I too see Xs in the newer version of the app from play store. I am running on Pixel.

**Comment by MaskyS** [comment]
I could confirm this bug on Marshmello, device is Infocus M535

**Comment by nsreenath** [comment]
Same issue in Android 7.0 Moto G4 Plus.

**Comment by nsreenath** [comment]
I'm attaching the `GalleryIcons.ttf` font file extracted from the apk file installed on my phone (Android 7.0 Moto G4 Plus), which has this issue. You can check if it got corrupted or not.

[GalleryIcons.zip](https://github.com/flutter/flutter/files/2000111/GalleryIcons.zip)

**Comment by HansMuller** [comment]
@nsreenath  - the GalleryIcons.ttf file you uploaded appears to be identical to the expected released version.  I'm afraid we're still trying to find a version of this bug we can reproduce locally.

**Comment by deckerst** [comment]
Running the Flutter Gallery 0.4.2 from the play store on a Sony Xperia Z5C running Android 7.1.1, I get a variation of this issue, with ideograms instead of the no_def squares:
![flutter_gallery_icon_font_issue](https://user-images.githubusercontent.com/13898333/40266942-85dce560-5b8f-11e8-971d-f37cdd1d5ccf.png)

Looks like the icon font fails to load, or is loaded but not applied.

I don't know whether it's related, but I currently face a font loading issue in a personal flutter project, tested on the same device. In this project, custom fonts are not applied on a fresh launch, but they can be applied after a hot reload.

**Comment by zoechi** [comment]
I believe this was fixed.
