### ISSUE TITLE
ScrollableMixedWidgetList should support reversing the direction

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1762]
Continuation of #136 for ScrollableMixedWidgetList

**Comment by abarth** [comment]
Thanks, working on it.

**Comment by abarth** [comment]
@collinjackson IMHO, we should switch to using Block in the hackathon.  The problem is that ScrollableMixedWidgetList doesn't know how many items it has, so doesn't know where to start for the "last" one.  We could change the API and add an "itemCount" field, but that class is already so complex that it would probably be better to just use Block.  If Block is too slow, we can work on making Block faster.

**Comment by Hixie** [comment]
yeah rather than making MixedViewport handle gravity it would be saner to make it support reversing the direction entirely (so the last item is index 0).

**Comment by Hixie** [comment]
(that's what you'd want anyway for a chat app since you'd want to load the history lazily on demand)

**Comment by collinjackson** [comment]
OK! We'll use a Block for now.

**Comment by abarth** [comment]
We'll probably need direction reversing in all the scrolling classes for RTL

**Comment by abarth** [comment]
ListView does this now.
