### ISSUE TITLE
Unable to add border in InputDecoration

### ISSUE THREAD

**Issue by aakashshah94** [flutter/flutter#17638]
## Steps to Reproduce

I am trying to learn flutter using the Course on Udacity. I am trying to give border to a textfield by using InputDecoration but there is no such property. What can be the reason for that?
## Logs

**Comment by hnvn** [comment]
I don't understand your mention about no property for border of InputDecoration. Here's [document](https://flutter.io/cookbook/forms/text-input/), and here's code:
```
          TextField(
            decoration: InputDecoration(
              hintText: 'Input',
              border: OutlineInputBorder(),
            ),
          )
````
Btw, StackOverflow is the proper place for such a kind of question.

**Comment by aakashshah94** [comment]
I tried the same thing.But it is not working..that is the reason I had to
ask it here. Is there a specific version where it is available..I am prety
sure I have the most update version. I am writing my code in android srudio.

**Comment by brianegan** [comment]
This was changed in the past few months, but if you're on the latest beta it should exist. Are you still seeing this problem @aakashshah94?

**Comment by aakashshah94** [comment]
I thought I had already closed the issue. Yes the problem was with older version. I had two versions of flutter on my system. So even though the terminal showed that flutter version is up to date, android studio was using the older version. Sorry for that, thank you for your response.

**Comment by aakashshah94** [comment]
I thought I had already closed the issue. Yes the problem was with older version. I had two versions of flutter on my system. So even though the terminal showed that flutter version is up to date, android studio was using the older version. Sorry for that, thank you for your response.

**Comment by the0neWhoKnocks** [comment]
Without this issue I don't know if I would have been able to figure out how to accomplish this.

- The property  says that it only accepts type `InputBorder` and it only has `none` exposed.
- The cookbook only calls out how to remove the border. https://flutter.io/cookbook/forms/text-input/
- `OutlineInputBorder` isn't called out in `InputDecoration` https://docs.flutter.io/flutter/material/InputDecoration-class.html

Granted I'm new to Flutter, but I keep running into these somewhat common/simple use cases where I have to do research in order to figure out the solution.

**Comment by zoechi** [comment]
@the0neWhoKnocks can you please create a new issue with a link to this one. 
Closed issues aren't monitored.
