### ISSUE TITLE
firebase_messaging getToken() never resolves unless _firebaseMessaging.configure() is called.

### ISSUE THREAD

**Issue by abehaskins** [flutter/flutter#17699]
If you attempt to invoke `await _firebaseMessaging.getToken()` without having called `_firebaseMessaging.configure()` then `getToken()` hangs indefinitely.

It looks to me like `configure()` just sets up callbacks, which appear optional, so we should either throw an error if `configure()` invocation hasn't happened or make it truly optional.

**Comment by blaneyneil** [comment]
i'm having the same problem, sporadically, but i call _firebaseMessaging.configure() in my main() before i even call runApp().  

i don't call _firebaseMessaging.getToken() til my signup logic/screen, and it will occasionally hang - no response and nothing in the catchError block.

**Comment by kroikie** [comment]
@blaneyneil is this happening on Android, iOS or both?

**Comment by blaneyneil** [comment]
iOS, on an actual device.

**Comment by kroikie** [comment]
Looks like the [`configure`](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/lib/firebase_messaging.dart#L69) is responsible for setting the method handlers. So unless you call configure the onToken callback is never handled and awaiting the token will never return.

**Comment by kroikie** [comment]
Like @abehaskins suggested we could return an error is the token is trying to be retrieved before the method call handlers are set.

**Comment by blaneyneil** [comment]
i'm calling configure from the main entry point:

```
_firebaseMessaging.configure(
    onMessage: (Map<String, dynamic> message) {
      print("onMessage: $message");
      //_showItemDialog(message);
    },
    onLaunch: (Map<String, dynamic> message) {
      print("onLaunch: $message");
      //_navigateToItemDetail(message['location']);
    },
    onResume: (Map<String, dynamic> message) {
      print("onResume: $message");
      //_navigateToItemDetail(message['location']);
    },
  );


  FirebaseUser _user = await _auth.currentUser();

  runApp(MaterialApp(
    home: _user != null ? new HomeScreen() : new SplashScreen(),
    title: 'myApp',
    debugShowCheckedModeBanner: false,
    theme: mainTheme,
    routes: myRoutes,
  ));

```

and then only calling getToken() inside my signup screen - which is in another route.  the really odd part is that's it's sporadic.  it hangs maybe 20% of the time.

**Comment by kroikie** [comment]
@blaneyneil could you confirm that you are using version `1.0.3` of the plugin since it updates how the token is retrieved and report if you are getting the same issue?

**Comment by blaneyneil** [comment]
i am.  i know i had done a package upgrade within the last 24, and i explicitly set it to 1.0.3 earlier.  and then i got a hang upon my first test signup:

  ```
Future<String> _getPushToken() async {

    print('called _getPushToken');

    _firebaseMessaging.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true));

    String _token = await _firebaseMessaging.getToken();
    print('received token');
    return _token;    
  }
```
the 2nd print never executed.

**Comment by blaneyneil** [comment]
this appears to be a result of where/when you call _firebaseMessaging.configure().  as noted, i was calling it in main(), before runApp(MaterialApp()) so i could listen for incoming messages.  it mostly worked.   

once i started calling _firebaseMessaging.configure() prior to each each use of _firebaseMessaging.getToken() then i didn't have any problems.

**Comment by aidandavis** [comment]
For me also, getToken() hangs unless .configure() is called first.
I have it just beforehand and don't specify any message handlers, but it's necessary for it to work.

```
_firebaseMessaging.configure();
_firebaseMessaging.getToken().then((token) {
  // use the token
});
```

**Comment by sir-boformer** [comment]
Got the same issue, but it also happens when I call `configure` first. 

I'm doing it in the `main` method, and the app does not start at all because the future never returns. This is my code: 

```dart
void main() async {
  final FirebaseMessaging firebaseMessaging = FirebaseMessaging();

  firebaseMessaging.configure(
    onMessage: onMessage,
    onLaunch: onLaunch,
    onResume: onResume,
  );

  final token = await firebaseMessaging.getToken(); // future never completes

  runApp(MyApp(token: token));
}
```

Looking at the source code of the plugin, it looks like there is something wrong. The future only returns if the token changes because internally it uses the first result of `onTokenRefresh`. But the token does not always refresh when the app starts up, so `onTokenRefresh` stays empty.

To get the current token, the android plugin would have to call `FirebaseInstanceId.getInstance().getToken()`, but it never does.

@goderbauer, I think you made the `firebase_messaging plugin`. Would you mind if I made a few changes to the plugin?

**Comment by wonsuyon** [comment]
var pushToken = await firebaseMessaging.getToken().timeout(Duration(milliseconds: 3000);
This code works for me.

**Comment by kroikie** [comment]
@abeisgoat

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/822. Any further collaboration will be done there.

**Comment by masterplox** [comment]
Hi guys, I hope my message reaches you well. My application development encountered 

**Problem**
`FirebaseMessaging _firebaseMessaging = new FirebaseMessaging();`
         ` _firebaseMessaging.configure();`
         ` final pushToken =
              await _firebaseMessaging.getToken().timeout(Duration(seconds: 3));`

`pushToken` returns null when my app runs in Google Play Internal testing after uploading appbundle file with command `flutter build appbundle --release`. However, while I am running the app  using `flutter run` or in debugging mode hitting `F5` in Visual Studio Code, I can get the `pushToken` to return the token.

**Background**
I have my `google-services.json` file included in its respective directory (android/app),
I have my FirebaseCloudMessagingAPI enabled
I have my FCM Registration API enabled

In my FirebaseCloudMessagingAPI overview, I see a banner noting _'To use this API, you may need credentials. Click 'Create credentials' to get started.' (I'm ignoring since I haven't come across tutorials showing anything regarding this)
I have two API keys, restrictions (Android apps, iOS apps)
I have the most current versions, at the time of writing, on
`firebase_messaging: ^7.0.0`
` firebase_core: ^0.5.0`

My flutter doctor
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.2)
[√] Connected device (1 available)

• No issues found!
PS C:\Users\rmorris\flutter_projects\BEL\beimo> flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at C:\src\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rmorris\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\rmorris\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM J600G (mobile) • 520072cc43b1b5cb • android-arm • Android 10 (API 29)

 • No issues found!
```
