### ISSUE TITLE
Support real fonts in `flutter test`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#17700]
This would be especially handy in screenshot tests.  e.g. @HansMuller has a use case for a screenshot test where he verifies that we're aligning everything correctly to the font's baseline.

Proposed interface:

```
$ flutter test --font=<path/to/font.ttf>
```

This would trigger the test to _not_ specify `--use-test-fonts` in the shell arguments and instead pass the user-specified font to the shell.

**Comment by mehmetf** [comment]
@gamebox Please take this issue on. I see activity for loading dynamic fonts so I expect that to be fixed soon. We need to wire it to flutter_tester and then bring it to g3.

**Comment by HansMuller** [comment]
This test is waiting for this issue to be resolved:
https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/localized_fonts_test.dart

The test was added in https://github.com/flutter/flutter/pull/18222 and #18317 is the issue that could be closed after the test has been updated.

**Comment by gamebox** [comment]
Ok, I've got a PR for this that I'm about to write up.  Does it make sense for us to add some docs around this?

**Comment by tvolkert** [comment]
@gamebox definitely.  Some combination of https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/flutter_test.dart and https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/font_loader.dart probably make sense as to _where_ to document this.

**Comment by gamebox** [comment]
Thanks @tvolkert .  I'll circle back and write up these docs and add them to my PR.

**Comment by mleonhard** [comment]
How about adding documentation showing how to use a real font with flutter_test?

I'm making a golden screenshot test of an alert dialog displayed on a phone-sized screen.  The Ahem font is so enormously wide that two simple buttons are too wide to fit in the dialog, stopping the test.

The FontLoader docs say "Creates a new FontLoader that will load font assets for the specified family.  The font family will not be available for use until load has been called."  So I added `await FontLoader('Muli').load();` to my test's main().  That didn't work.  From #17910 it looks like I can add a font if I have the TTF file bytes.  But that means I need to load the font asset file as bytes.  My real Flutter app doesn't have to do that, so why would the tests have to?
```
final FontLoader fontLoader = FontLoader('Muli');
fontLoader.addFont(rootBundle.load('assets/fonts/Muli-Light.ttf'));
await fontLoader.load();
```
This code doesn't work because flutter_test blocks access to assets (#12999).  This is frustrating.  A working example would go a long way.

**Comment by apaatsio** [comment]
@mleonhard Here's a way to load real fonts in tests.

```dart
final fontData = File('assets/fonts/Roboto-Regular.ttf')
    .readAsBytes()
    .then((bytes) => ByteData.view(Uint8List.fromList(bytes).buffer));
final fontLoader = FontLoader('Roboto')..addFont(fontData);
await fontLoader.load();
```

**Comment by tolotrasamuel** [comment]
This might help https://stackoverflow.com/a/62460566/6727914
