### ISSUE TITLE
Firebase Authentication currentUser() returns null

### ISSUE THREAD

**Issue by brusinovic** [flutter/flutter#17805]
This is about Flutter Firebase Authentication plugin.<br> I am trying to send a verification email after creating a new user, but sendEmailVerification() internally uses currentUser(). The error is the same on Android and IOS.<br>

First two lines successfully return FirebaseUser. The third returns null. Forth, if third is commented throws a null reference error. 

Thanks,
Boris

    user = await _auth.createUserWithEmailAndPassword(email: email, password: password); 
    // result is FirebaseUser
    user = await _auth.signInWithEmailAndPassword(email: email, password: password);
    // result is FirebaseUser    
    user = await _auth.currentUser();
    // result is null    
    await user.sendEmailVerification();
    //null reference, because it internally uses .currentUser()

This has posted as StackOverflow question: https://stackoverflow.com/questions/50439051

**Comment by ITforHome** [comment]
i have the same error... i tried this code:
```dart 
@override
Widget build(BuildContext context) {
  return new Scaffold(
    appBar: new AppBar(
      title: new Text("App bar"),
    ),
    body: new FutureBuilder<FirebaseUser>(
      future: FirebaseAuth.instance.currentUser(),
      builder: (BuildContext context, AsyncSnapshot<FirebaseUser> snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return new Text(snapshot.data.uid);
        }
        else {
          return new Text('Loading...');
        }
      },
    ),
  );
}
```

**Comment by ITforHome** [comment]
@brusinovic How are you implement your code?
i only use this code to check if user logged in or not:

```dart 
enum AuthStatus { notSignedIn, signedIn }

@override
  void initState() {
    super.initState();
    widget.auth.currentUser().then((userId) {
      setState(() {
        authStatus = userId == null ? AuthStatus.notSignedIn : AuthStatus.signedIn;
      });
    });
  }

  _signedIn() {
    setState(() {
      authStatus = AuthStatus.signedIn;
    });
  }

  void _signedOut() {
    setState(() {
      authStatus = AuthStatus.notSignedIn;
    });
  }
```
I don't know, how can i use your code to get the current UserID...

**Comment by androsaz** [comment]
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###

**Comment by zoechi** [comment]
Are you still seeing this with the latest plugin version? I think this was fixed.

**Comment by agharshit08** [comment]
This has still not fixed, what is the alternative? please help

**Comment by agharshit08** [comment]
`Future<String> getCurrentUser() async {
    FirebaseUser user = await FirebaseAuth.instance.currentUser();
    print("mail " + user.email);
    if(user != null){
      String idToken = await user.getIdToken();
      _authenticatedUser =
          User(email: user.email, id: user.uid, token: idToken, photo: user.photoUrl);
      return 'success';
    }else{
      return null;
    }
  }`

I am using this code and the user is always filled with null.

**Comment by kroikie** [comment]
@brusinovic

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/817. Any further collaboration will be done there.

**Comment by ISimplifyComplexity** [comment]
I am also having this exact issue. The user is always returned as null!

**Comment by ISimplifyComplexity** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

This should not be closed! Very frustrating!

**Comment by devv-il** [comment]
I have a similar issue.  FirebaseAuth.instance.currentUser.updateProfile(displayName: username); works for me but when I log in, it shows an error for a second or two and then it updates itself and then the displayname works as expected. I have been struggling with this so much now. I would really appreciate if someone could help me out here.

WHERE I UPDATE USERPROFILE AND ADDD USERNAME TO DISPLAYNAME:

`class AuthScreen extends StatefulWidget {
  @override
  _AuthScreenState createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _auth = FirebaseAuth.instance;
  var _isLoading = false;
  String name;
  void _submitAuthForm(
    String username,
    String email,
    String password,
    String phoneNum,
    bool isLogin,
    BuildContext ctx,
  ) async {
    UserCredential authResult;

    try {
      setState(() {
        _isLoading = true;
      });
      if (isLogin) {
        authResult = await _auth.signInWithEmailAndPassword(
          email: email,
          password: password,
        );
      } else {
        authResult = await _auth.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );

        print("username is: " + username);

        _auth.currentUser.updateProfile(displayName: username);

        await FirebaseFirestore.instance
            .collection('users')
            .doc(authResult.user.uid)
            .set({
          'phoneNum': phoneNum,
          'name': username,
          'email': email,
        });
      }
    } on PlatformException catch (err) {
      var message = 'An error occurred, pelase check your credentials!';

      if (err.message != null) {
        message = err.message;
      }

      ScaffoldMessenger.of(ctx).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Theme.of(ctx).errorColor,
        ),
      );
      setState(() {
        _isLoading = false;
      });
    } catch (err) {
      print(err);
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: AuthForm(
        _submitAuthForm,
        _isLoading,
      ),
    );
  }
}`

WHERE I USE THE DISPLAYNAME:

`class HeyAman extends StatelessWidget {
  final user = FirebaseAuth.instance.currentUser;
  @override
  Widget build(BuildContext context) {
    List<String> firstname = user.displayName.split(' ');

    return StreamBuilder(
      stream: FirebaseAuth.instance.userChanges(),
      builder: (ctx, futureSnapshot) {
        if (futureSnapshot.connectionState == ConnectionState.none) {
          return Center(
            child: CircularProgressIndicator(),
          );
        }
        return Container(
          padding: const EdgeInsets.only(bottom: 7, left: 30, right: 30),
          child: Column(
            children: <Widget>[
              Container(
                width: 300,
                child: Text(
                  user.displayName.indexOf(' ') > -1
                      ? firstname[0]
                      : user.displayName,
                  style: TextStyle(
                    fontWeight: FontWeight.w800,
                    color: Colors.white,
                    fontSize: 33,
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}`

DEBUG CONSOLE WHERE IT SHOWS ERROR FOR THOSE 1-2 SECONDS:
`Reloaded 2 of 650 libraries in 1,344ms.
D/FirebaseAuth( 7789): Notifying id token listeners about a sign-out event.
D/FirebaseAuth( 7789): Notifying auth state listeners about a sign-out event.
W/IInputConnectionWrapper( 7789): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 7789): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 7789): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 7789): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 7789): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 7789): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 7789): getTextAfterCursor on inactive InputConnection
I/FirebaseAuth( 7789): [FirebaseAuth:] Preparing to create service connection to fallback implementation
W/System  ( 7789): Ignoring header X-Firebase-Locale because its value was null.
`
