### ISSUE TITLE
Would like an Apple Pay/Google Pay plugin for physical goods transactions

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#17837]
This tacks payments support for non-software assets. For those, please see https://github.com/flutter/flutter/issues/9591

**Comment by MarkOSullivan94** [comment]
Out of interest how would this plugin be different from #9591?

**Comment by mit-mit** [comment]
The present plugin exposes APIs for Apple Pay / Google Pay, common ways of integrating payments in a "checkout experience" without having to ask the user for payment details. 

#9591 covers "in-app" purchases of digital content, for example through Google Play Billing:
https://developer.android.com/google/play/billing/billing_overview

**Comment by MarkOSullivan94** [comment]
Essentially this feature would handle out of app payments, like using Paypal / debit cards/ credit cards?

**Comment by mit-mit** [comment]
This will likely end up being a selection of plugins, e.g, one for Google Pay, one for Apple Pay, one for PayPal, etc.

**Comment by Niccolohui** [comment]
Any update for app payment for physcia goods？

**Comment by ViniciusSossela** [comment]
Any update on this?

**Comment by Suraj12p** [comment]
Has there been any progress on this as no one has responded in a couple of months?

**Comment by swingywc** [comment]
Is there any solution in Flutter to use Google Pay and Apple Pay to get user credit card token, thus charge user with services like Stripe or etc.?

**Comment by littlemarc2011** [comment]
I am actually working on creating something called flutter_pay which integrates Android pay and Apple Pay using stripe. Currently, I am working on Android Pay and in the future, I will add Apple Pay. However, I have hit a road bump with having to go live with google pay in order to test transactions. Based on the bottom of [this](https://stripe.com/docs/mobile/android/google-pay) page, I must submit my example app as a production build to google in order to test. If somebody apart of this repo from Google could possibly help me, I have not sent the app to google support yet because I am unaware if they will accept a flutter app, but any help is appreciated. (I also do not know what I have to submit besides the APK to google support)

Maybe I do not have to go live with google but I get "Transaction declined: invalid payment method [OR-CCSEH-05]"

**Comment by MarkOSullivan94** [comment]
@timsneath @eseidel @mit-mit can any of you help?

**Comment by timsneath** [comment]
Hi Mark! Yeah, we're aware of the feature request, and it's on our radar. If you're asking specifically about the question @littlemarc2011 asked, I'll ask around to see if there's someone from Google Pay who can comment.

**Comment by MarkOSullivan94** [comment]
Yep, just pinging you all to see if anyone could help @littlemarc2011. Thanks for the reply!

**Comment by littlemarc2011** [comment]
Thank you guys, I just submitted the Google Pay API Production Access Enablement Request Form using the compiled example app. Maybe this will get me somewhere on the error, I found no documentation online about OR-CCSEH-05 when it comes to development. Should I create a new issue for my the plugin since this does not relate to the this issue?

**Comment by mikekono** [comment]
Square currently has a beta open for our In-App-Payments SDK that supports Apple Pay, Google Pay, and keying in a card number. 

Here's a link to request early access for anybody who is interested:
https://www.workwithsquare.com/in-app-sdk.html

**Comment by plusmobileapps** [comment]
I made a very simple plugin that has the very basic framework for opening google pay. Having been the one to integrate this for the Starbucks app, I wanted to play around in the flutter space and see if I could get this working. So far it will simply open the google pay picker, but I plan on building out the functionality of this more to collect the token, and alter allowed payment methods, and accept various payment processors.  

[Here](https://github.com/plusmobileapps/flutter_pay) is the source code for the plugin so far if anybody would like to use it as a base to go build out their own implementation.

**Comment by valterh4ck3r** [comment]
@plusmobileapps , are working ?

**Comment by valterh4ck3r** [comment]
Okay, we can help you :)

**Comment by AlexanderArendar** [comment]
Hi guys,

was there any progress from February?
I've been evaluating abilities of Flutter in the area of payment gateways integration and it looks like only SquareUp dev team provided a Flutter plugin at the moment.

If the Google Pay / Apple Pay integration plugin was implemented that would cover a lot since Google Pay consolidates all other payment gateways.

**Comment by timsneath** [comment]
Looks like there are a couple of plugins available: https://pub.dev/packages/flutter_google_pay and https://pub.dev/packages/flutter_apple_pay.

**Comment by AlexanderArendar** [comment]
@timsneath this is of course great, without doubts but would be great to have a solid solution by Flutter team (especially taking into consideration that Flutter and GPay are both Google products), which will provide good documentation, cover all features, etc.

**Comment by jnblanchard** [comment]
I made a [plugin](https://pub.dev/packages/stripe_native) that creates Stripe tokens from Apple&Google payment sheets. Maybe it helps?

**Comment by Hixie** [comment]
It is unlikely that the Flutter team will provide such a plugin. We would encourage anyone interested in such a plugin to get together and create one, and nominate it to be a [Flutter Favorite](https://flutter.dev/docs/development/packages-and-plugins/favorites).

**Comment by awazgyawali** [comment]
To all who stumble upon here, google has now released a flutter package which just does this. 

Package: https://pub.dev/packages/pay

How to guide: [here](https://dev.to/aawazgyawali/how-to-use-google-pay-and-apple-pay-using-stripe-on-flutter-2i1j)
