### ISSUE TITLE
FlutterView in a fragment needs to render before fragment transition begins

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#17876]
If an entry/exit animation is assigned to a fragment containing FlutterView, the contents do not show until the animation is complete, leading to a abrupt transition from a black view -> content.

Since it is very common for fragments to perform enter and exit animations, we need to figure out how we can make this transition work. We have an internal example that reproduces this issue within the `android_flutter` sample app.

**Comment by matthew-carroll** [comment]
I'm not sure how those points relate back to this issue?

Nearly every Android app that partially integrates Flutter will use Fragments, and those Fragments will have some kind of transition.  And I mentioned IO because the trend is only moving more towards Fragment navigation, not away.

If the FlutterView displays visual artifacts simply because its Fragment is moving around the screen, I think that is completely unacceptable and a huge problem.  I'm actually surprised that this isn't a ship blocker for almost everyone right now.  Am I missing something here?  Did I misunderstand this issue?

**Comment by mehmetf** [comment]
I opened this issue because I wanted to explore what we intend to support w.r.t. Fragments. However, now I realize that isn't very useful since we will be imagining use cases. It would be better to handle this on a case-by-case basis. I will edit this issue (because it is now linked from a couple of documents) to make it about the specific case I have observed with a client hackathon.

**Comment by mit-mit** [comment]
cc @mravn-google to check if this has been resolved already

**Comment by mravn-google** [comment]
It has not been resolved. The Flutter module template does away with the black background by making the Flutter view transparent until the first frame is produced by the Dart side. But more work is needed to play nicely with fragment transitions. I have yet to fully understand how they work (e.g. how/when they interact with the view of an incoming fragment).

I'll un-assign myself as I do not have time for this atm.

**Comment by matthew-carroll** [comment]
@mehmetf do you still have the specific use-cases for this ticket that you mentioned in your last comment?

**Comment by mehmetf** [comment]
I can observe this with the internal add2app sample. Ping me so I can show you how to build and test it out.

**Comment by matthew-carroll** [comment]
I created a demo of fragment transitions using the new embedding and shared with @mehmetf. The new embedding, when using a `TextureView` animates `FlutterFragment`s as expected. Therefore, I'm closing this issue.
