### ISSUE TITLE
Bezier demo does not hit 60fps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17889]
I've not tested it myself, but this came in through another customer.

Here is the example:
https://github.com/eseidelGoogle/bezier_perf

There also is likely a bug in either my integration code or the original sample as it does not redraw correctly while animating.  If you hit the "p" key in `flutter run` (or any other key which forces a redraw) you can see it's actually animating, just not redrawing.

@HansMuller might see the redraw bug off the top of his head.

@chinmaygarde volunteered to take a look at the perf.

**Comment by eseidelGoogle** [comment]
If you set the blur value to something other than 0.0 the animation shows up.  I haven't looked into the details of why.

**Comment by HansMuller** [comment]
Here's a version that animates: https://gist.github.com/HansMuller/d3470c74d6c677075b6e1705e8ea8da0

I noticed a few odd things about the code although I doubt any of them would have a significant performance impact:

- The code doesn't use const types where it could or, as far as I can tell, cache constant values like _getLogoPath().
- To animate BezierPaint() pass along "curve" as its repaint Listenable (call super(repaint: curve)).

At the moment, I don't have time to look into this in more detail.

**Comment by phpthug** [comment]
Add a float larger than 0 to the blur property of the Bezier component to get it to animate:

`new Bezier(Colors.amber, 1.0, blur: 1.0)`

**Comment by eseidelGoogle** [comment]
Learn anything @chinmaygarde?

**Comment by chinmaygarde** [comment]
Update: This appears to be a surprisingly slow edge case in the GPU renderer. Switching to the software renderer for this specific scene makes Flutter comfortably meet its frame budget. [This is a 
trace of scene using the slow GPU renderer](https://github.com/flutter/flutter/files/2051697/SlowInGPU.json.zip) and [this one traces the same scene with the software renderer](https://github.com/flutter/flutter/files/2051698/FastInSoftware.json.zip).

Slow:
<img width="855" alt="screen shot 2018-05-29 at 4 14 35 pm" src="https://user-images.githubusercontent.com/44085/40690340-6fce6810-635b-11e8-8c2e-3daabc042bc7.png">

Fast:
<img width="726" alt="screen shot 2018-05-29 at 4 14 28 pm" src="https://user-images.githubusercontent.com/44085/40690346-746a0f50-635b-11e8-9f15-b6e599c5ff85.png">

In the slow GPU trace, the renderer seems to be creating a bitmap texture for subsequent upload. The scribble into this texture seems to be taking an extremely long time as shown. There are two surprising outcomes here. We should not be doing a per frame texture allocation, scribble and upload. Also, the scribble done by the software renderer is way faster than that in the GPU renderer.

The offending call seems to be the `TextureOp` in `virtual bool GrRenderTargetOpList::onExecute(GrOpFlushState *)`:
<img width="1264" alt="screen shot 2018-05-29 at 4 16 53 pm" src="https://user-images.githubusercontent.com/44085/40690405-ca61a86e-635b-11e8-8aca-18589cf87a69.png">

We have the issue isolated. The fix is not clear ATM. But this scene should be easy to render in a performant manner once this issue is fixed.

Just an update.

**Comment by eseidelGoogle** [comment]
Thank you @chinmaygarde!

**Comment by chinmaygarde** [comment]
cc @brianosman

**Comment by chinmaygarde** [comment]
More update: Marking the path as volatile (`setIsVolatile`) and disabling the `fAllowPathMaskCaching`  GrContext option did not seem to help. Traces for [this are here](https://github.com/flutter/flutter/files/2051877/SkPathIsVolatile.json.zip).

**Comment by chinmaygarde** [comment]
SKP Trace for the scene as requested: 
[flutter_01.skp.zip](https://github.com/flutter/flutter/files/2051924/flutter_01.skp.zip)

**Comment by brianosman** [comment]
cc @bsalomon

**Comment by chinmaygarde** [comment]
Those traces were captured on an iPhone 8.

**Comment by liyuqian** [comment]
Subscription does not allow me to quickly search for this issue so I'm going to CC myself @liyuqian

**Comment by chinmaygarde** [comment]
The guidance from the Skia team is that marking paths as volatile makes this scene go faster. It is not clear if this is a recommendation for all paths.

@bsalomon & @brianosman: Should we mark all paths as volatile?

**Comment by bsalomon** [comment]
Chris Dalton has the best handle on this. In general you want to mark paths volatile that will be rendered once or have control point modifications before being redrawn.

**Comment by liyuqian** [comment]
I've conduct some experiments on Nexus 5X and it seems that Skia's suggestion of marking paths as volatile works there. Maybe there's a bug for Skia's `isVolatile` bit on iOS so Chinmay couldn't make it work on iPhone8 (@bsalomon, @brianosman)?

On the Flutter side, we need to expose the isVolatile bit in our API so our clients can draw those animated paths fast. Shall I go ahead and work on that?

Here are the traces of my experiments:

- Without `setIsVolatile(true)`:
![image](https://user-images.githubusercontent.com/22987568/41563287-0beaa45e-7304-11e8-8843-3322d585d0e3.png)
Note that it's 60fps initially, and suddenly several frames get super slow (probably due to cache overflow and recycling resources), and then it gets fast again.

- With `setIsVolatile(true)`:
![image](https://user-images.githubusercontent.com/22987568/41563433-67fa6c20-7304-11e8-908b-b94f638b548b.png)

Note that in both cases, the performanceOverlay takes a lot of time to draw. So without it, we'll be very comfortably 60fps with `setIsVolatile(true)`.

**Comment by brianosman** [comment]
Related to this, I previously noticed that the technique used to render the
perf overlay is going to be very slow. If we can live without rounded
corners on the bars, or some other simplification, we can make that much
faster.

On Jun 18, 2018 5:35 PM, "liyuqian" <notifications@github.com> wrote:

I've conduct some experiments on Nexus 5X and it seems that Skia's
suggestion of marking paths as volatile works there. Maybe there's a bug
for Skia's isVolatile bit on iOS so Chinmay couldn't make it work on
iPhone8 (@bsalomon <https://github.com/bsalomon>, @brianosman
<https://github.com/brianosman>)?

On the Flutter side, we need to expose the isVolatile bit in our API so our
clients can draw those animated paths fast. Shall I go ahead and work on
that?

Here are the traces of my experiments:

   -

   Without setIsVolatile(true):
   [image: image]
   <https://user-images.githubusercontent.com/22987568/41563287-0beaa45e-7304-11e8-8843-3322d585d0e3.png>
   Note that it's 60fps initially, and suddenly several frames get super
   slow (probably due to cache overflow and recycling resources), and then it
   gets fast again.
   -

   With setIsVolatile(true):
   [image: image]
   <https://user-images.githubusercontent.com/22987568/41563433-67fa6c20-7304-11e8-908b-b94f638b548b.png>

Note that in both cases, the performanceOverlay takes a lot of time to
draw. So without it, we'll be very comfortably 60fps with
setIsVolatile(true).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/17889#issuecomment-398203275>,
or mute the thread

**Comment by liyuqian** [comment]
Nice catch @brianosman ! Although it's less about round corners, it's actually about setIsVolatile again.

The perf overlay is drawing a volatile path (https://github.com/flutter/engine/blob/master/flow/instrumentation.cc#L112) and that path is not prepared by path.cc. Previously, even if we marked all paths from path.cc as volatile, we missed this one. And that could be the root reason why @chinmaygarde couldn't make it fast on iPhone8: Skia is probably caching too many of the perf overlay paths.

On the other hand, the perf overlay path is a complicated path like a sawtooth thanks to a nonzero `sample_margin_width` (https://github.com/flutter/engine/blob/master/flow/instrumentation.cc#L100). I tried to drawRect 120 times instead of draw a 120-tooth sawtooth but that's even slower.

Anyway, it's really problematic that our perf overlay itself is so slow and that makes our profiling tool misleading. Hence I'm going to

1. make the perf overlay path volatile.
2. make ``sample_margin_width = 0` so we'll have a simple rect bar chart instead of a sawtooth.

**Comment by csmartdalton86** [comment]
Is this still a problem? A lot has changed in Skia since June. Now I'd hope that we just use CCPR and everything goes fast. (But would like to verify.)

**Comment by liyuqian** [comment]
With the new CCPR, this is no longer an issue as we're always fast even we don't setIsVolatile:

![image](https://user-images.githubusercontent.com/22987568/46562685-2c6ee880-c8b2-11e8-98ab-318b3b48eb37.png)

**Comment by windrunner414** [comment]
I found that using the bezier curve was still very slow.
#27453 is there any way to solve it? i converted dart to native java it's very smooth.but in flutter is very slow

**Comment by csmartdalton86** [comment]
CCPR is temporarily disabled and an MSAA implementation is in the works. It should land within the next few weeks, at which time bezier curves will be fast again.

**Comment by windrunner414** [comment]
@csmartdalton86 sounds great.I will test it after land

**Comment by windrunner414** [comment]
@csmartdalton86 hi.when was CCPR disabled? I found this issue in february(stable1.0). ccpr may be disabled last month?Is my issue caused by it?

**Comment by liyuqian** [comment]
Yes, CCPR is only disabled recently, but I'm not sure whether it's enabled in Flutter v1.0. It has only been enabled by default probably a few months ago. @csmartdalton86 : can you please provide a commit in Skia that enables CCPR by default for all (or most) paths?

**Comment by csmartdalton86** [comment]
Looks like it was disabled March 18:

https://skia-review.googlesource.com/c/skia/+/201938

CCPR was enabled some time last year, so in February it should have been enabled.

@windrunner414, do you have a specific bezier drawing case in mind that you can share for us to look at?

**Comment by liyuqian** [comment]
@csmartdalton86 : v1.0 was released last year and it was cut on https://github.com/flutter/flutter/commit/5391447fae6209bb21a89e6a5a6583cac1af9b4b which was in November last year. So it would be nice to check that CCPR is included at that time.

Meanwhile, @windrunner414 , can you please post a sample Flutter app (which hopefully only has a single main.dart file) that includes your slow bezier path drawing so we can debug locally to see if it's CCPR or something else?

**Comment by csmartdalton86** [comment]
CCPR was enabled on June 24, 2018.

https://skia-review.googlesource.com/c/skia/+/137207

Stroking was implemented on September 3, 2018:

https://skia-review.googlesource.com/c/skia/+/151188

**Comment by liyuqian** [comment]
Thanks @csmartdalton86 ! So it should definitely be there in v1.0. We'll need more information about the path to see why it's slow, @windrunner414 .

**Comment by windrunner414** [comment]
@liyuqian @csmartdalton86 you can see #27453.
I write the details in it

**Comment by windrunner414** [comment]
This is a very simple example, which is much more complicated in my book reader app.
I write a native app use similar code (only convert dart to java) is very smooth in Samsung galaxy note3 but the flutter app is pretty janky
