### ISSUE TITLE
Image_picker plugin fails, if Flutter activity is killed while native one is shown

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#17950]
On Android device,
* Go to System/Developer options and enable the "Don't keep activities" option.
* Run the image_picker example app and try to pick an image.

```
java.lang.IllegalStateException: Received images from picker that were not requested
```
```
E/AndroidRuntime(31917): Process: io.flutter.plugins.imagepicker.example, PID: 31917
E/AndroidRuntime(31917): java.lang.RuntimeException: Unable to resume activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:11165 flg=0x1 }} to activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.IllegalStateException: Received images from picker that were not requested
E/AndroidRuntime(31917): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(31917): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
E/AndroidRuntime(31917): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31917): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(31917): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31917): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(31917): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(31917): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:11165 flg=0x1 }} to activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.IllegalStateException: Received images from picker that were not requested
E/AndroidRuntime(31917): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3553)
E/AndroidRuntime(31917): 	... 10 more
E/AndroidRuntime(31917): Caused by: java.lang.IllegalStateException: Received images from picker that were not requested
E/AndroidRuntime(31917): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleResult(ImagePickerDelegate.java:337)
E/AndroidRuntime(31917): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChoosePictureResult(ImagePickerDelegate.java:304)
E/AndroidRuntime(31917): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:291)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:146)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:139)
E/AndroidRuntime(31917): 	at android.app.Activity.dispatchActivityResult(Activity.java:7276)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
E/AndroidRuntime(31917): 	... 11 more
```

A NullPointerException is thrown instead, if one cancels the picking from the native activity.

**Comment by mravn-google** [comment]
cc @sigurdm

**Comment by acidjazz** [comment]
@kroikie @sir-boformer @goderbauer @a14n @tvolkert  Any luck or idea on how to solve this? It makes my app completely useless on a good amount of devices including galaxy's and the Moto Z

possibly related:
#21102 
#18700

**Comment by sir-boformer** [comment]
@acidjazz Follow up question: Is the state of your app restored after the image is closed? What happens to the `Future` returned by the image picker?

**Comment by CaiJingLong** [comment]
@sir-boformer  you can see #18059 
some log
I hope you can solve this problem.

**Comment by acidjazz** [comment]
@sir-boformer on other devices yes, but not these

@kroikie @sir-boformer @goderbauer @a14n @tvolkert  another reminder this is 100% consistent and makes apps useless on these devices

**Comment by sir-boformer** [comment]
@acidjazz Flutter does not support saving instance state when the host activity is killed by the system, see #6827. 

That means even if image_picker would not crash the app on re-entry, all state would be lost and the page that processes the selected image probably would not be there.

To prevent the crash (and somehow get access to the selected image), it must be checked if [`pendingResult`](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L108) is null before accessing it  (app state lost). 

Now the app would no longer crash, but the selected image would also not arrive in the app.

A different platform channel method must be called to transfer the image data to the flutter application. In the flutter application, you could expose the image uri as a `Stream`, or maybe call some method.

**Comment by sir-boformer** [comment]
I took a closer look because I'm also interested in a solution. I think it would make sense to solve the issue in 2 steps:

1) Make sure that no exceptions are thrown and just ignore the picked media if the activity was recreated. I think it's still better to have an app that resets and ignores user input that one that crashes.

2) Add 2 new methods to the image_picker api:

`retrievePickedImage`: Get the image that was picked/captured before the activity was recreated, or null if no image was chosen
`retrievePickedVideo`: Same for video.

You can call these from your dart code to check for selected media. Restoring the rest of your application state lies in your own hands.

To add these methods, various changes must be made to `ImagePickerDelegate.java`, and I think also the `PluginRegistry.Registrar` interface:

* `pendingCameraMediaUri` must be saved in the instance state of the host activity. So far I've not found a way to hook into `saveInstanceState` and instance state restoration. Hooks for that would have to be added to `PluginRegistry.Registrar`. 
* When the activity is restored, `pendingCameraMediaUri` must be restored from the instance state.
* When `onActivityResult` is called, it must be checked if there is a `pendingResult`. In that case, the selected media uri should be given to the `pendingResult`.
* If `pendingResult` is null, the `requestCode`, `resultCode` and `data` should be stored in instance fields of the `ImagePickerDelegate`. It's important that this operation is synchronous.
* When `retrievePickedImage` or `retrievePickedVideo`, check if there is data from the activity result and return the corresponding file uri.
* Reset the instance field that stored `requestCode`, `resultCode` and `data`

**Comment by CaiJingLong** [comment]
Sometimes,`FlutterActivity` will be killed, then flutter rerun `main` method.
How to save whole flutter state.

**Comment by acidjazz** [comment]
@sir-boformer @kroikie @sir-boformer @goderbauer @a14n @tvolkert any other ideas or or thoughts on how we can resolve this? I still have consistent constant crashing when people try to use my Flutter app and choose an image.

**Comment by sir-boformer** [comment]
I described a solution above. To make it work, you have to modify image_picker, but even more important, you have to write your own state saving and restoration logic for your app, at least on Android.

**Comment by acidjazz** [comment]
thanks @sir-boformer , @a14n  @mit-mit @roughike @jonahwilliams @zanderso @tvolkert @romaluca @maxatcn anyone up for giving it a try?

**Comment by callumclift** [comment]
having the same issues with a ONEPLUS A6013, is anyone looking into a fix for this? This is a showstopper for releasing my app

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/1509 should fix the crash issue. I also created https://github.com/flutter/plugins/pull/1512 which adds a method to retrieve the lost image/video data.

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/1512 introduced a new API to retrieve lost data(**image_picker 0.5.4**). I will go ahead and close this issue. If any related issue is found, please feel free to open another issue ticket with details!

**Comment by Joao-b4** [comment]
Does this have or will it have a viable solution? in addition to 'retrieveLostData', which is clearly not a solution for several cases, I work in an app that this error occurs for some users, I cannot apply 'retrieveLostData', since several screens allow images, in addition to fields to insert images dynamically generated based on a json

**Comment by augusto-nc** [comment]
> Does this have or will it have a viable solution? in addition to 'retrieveLostData', which is clearly not a solution for several cases, I work in an app that this error occurs for some users, I cannot apply 'retrieveLostData', since several screens allow images, in addition to fields to insert images dynamically generated based on a json

I recommend you use "Camera Plugin" to take photos on Android. As taught in this article: https: //flutter.dev/docs/cookbook/plugins/picture-using-camera#: ~: text = Many% 20apps% 20require% 20working% 20with, and% 20take% 20photos% 20or% 20videos.
