### ISSUE TITLE
Add triage guidelines for user questions that may be better suited to somewhere like StackOverflow

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17993]
People often open issues here for general questions about using Flutter that may be better suited for somewhere like Stack Overflow. I think it'd be useful if there was a cheerfully-worded standard paragraph on the [triage page](https://github.com/flutter/flutter/wiki/Triage) that could be copy/pasted for such issues.

For example, in the VS Code repo, there's a bot that automatically closes issues that are tagged with `*question` with this comment:

> Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).
> 
> Happy Coding!

A bot would be nice, but for now a copy/paste paragraph would be a step in the right direction.

**Comment by Hixie** [comment]
I recommend writing a cheerful paragraph and using it as a GitHub quick reply. :-)

If you write one and want to put it on the wiki's Triage page, obviously feel free to do so.

But as @zoechi says, please first carefully consider whether the question is being asked because our docs are insufficient, or whether the docs are actually fine and the questioner did not read them.

**Comment by DanTup** [comment]
> and using it as a GitHub quick reply

Heh, I didn't realise that existed :-)

Fair points about the docs, though I'm not sure how comprehensive the docs are intended to be. I'll consider carefully, thanks! :-)

**Comment by Hixie** [comment]
The docs are intended to be complete and comprehensive.
