### ISSUE TITLE
[video_player] Add RTSP/RTMP support

### ISSUE THREAD

**Issue by fukemy** [flutter/flutter#18061]
Hi.
I found flutter video_player based on AVPlayer in IOS, which does not support rtsp url.
Can anyone help me know how to play a video with format like 'rstp/rtmp' in flutter? 🤔

**Comment by fukemy** [comment]
@mravn-google

**Comment by mravn-google** [comment]
If iOS AVPlayer doesn't support the format you want, you might have to write a Flutter plugin wrapping a more powerful player than the platform default. Similarly, it should be quite doable to wrap ExoPlayer rather than MediaPlayer on the Android side. We're hoping to get around to do that, but the Flutter community is more than welcome to beat us to it.

**Comment by fukemy** [comment]
thanks you. I am really happy when have a framework that help me code once time then build for android + IOS, now I think i will code IOS for solve that rtsp/rtmp problem, and wait for the great flutter lib that can play it for IOS, because im not master to code flutter lib to solve it :)

**Comment by phillipkerman** [comment]
I wonder if there's an easy way to just bridge to FFMPEG?  I have no clue what's involved as far as distribution.  I just think if FFMPEG was supported (directly or otherwise) you'd be set.  And, I would become super more interested in Flutter.

**Comment by zoechi** [comment]
@phillipkerman I think you are looking for #7053

**Comment by zoechi** [comment]
I'm going to close this because I don't expect the Flutter team to provide a plugin with support for an alternative video player.

**Comment by paayao** [comment]
> I'm going to close this because I don't expect the Flutter team to provide a plugin with support for an alternative video player.

Saw your question on implementing wowza with flutter, need a helping hand on same problem. Thank you

**Comment by zoechi** [comment]
@paayao you mean https://www.wowza.com/community/questions/46506/how-to-use-wowza-with-flutter.html? What kind of help?

**Comment by paayao** [comment]
> @paayao you mean https://www.wowza.com/community/questions/46506/how-to-use-wowza-with-flutter.html? What kind of help?

Yes. Want to know if you were able to use flutter with wowza. Finding it difficult.

**Comment by function1983** [comment]
From my personal experience with Android video player:
- If you need **RTMP** only then you can manually add 'com.google.android.exoplayer:extension-rtmp:2.9.1' to the dependencies of video_player. It will work with just a few lines of code.
- For **RTSP** is a bit more complicated since Exoplayer does not support it. I managed to wrap [IJKPlayer](https://github.com/Bilibili/ijkplayer) inside Flutter on Android and it works great (took me a couple of days since IJKPlayer is pretty extensive)

IJKPlayer does natively support iOS with [DEMOS](https://github.com/Bilibili/ijkplayer/tree/master/ios) so its very much possible that you could archive the same result here (and maybe even write a plug-in the the common good of the Flutter community?).

**Comment by fukemy** [comment]
hello @function1983 , i am very happy when read your comment, i see some people using ijkplayer in IOS as well, and bring it all to once library, the best library i saw i [IOSDevlog link](https://github.com/iOSDevLog/ijkplayer/)
 
  May be it help you.
 Best regards.

**Comment by nsmith1024** [comment]
Sp how is this going, can live video be streamed from one flutter app to many now?

**Comment by AndruByrne** [comment]
Hey, @function1983: 
> From my personal experience with Android video player:
> * If you need **RTMP** only then you can manually add 'com.google.android.exoplayer:extension-rtmp:2.9.1' to the dependencies of video_player. It will work with just a few lines of code.

This is my requirement; was this experience in flutter or box-stock android? The concept of editing a few dependencies is a lot more attractive than creating my own exoplayer wrapper or depending on cjl_spy@163.com's port of the (ancient) ijk repo.

I'm just going to throw it in the video_player's gradle and see what happens... honestly, I think there is only bespoke application for exoplayer wrappers that do not support exoplayer's extensibility.

**Comment by VNAPNIC** [comment]
Flutter WOWZA plugin for iOS/Android. The project is based on Wowza GoCoder SDK
https://pub.dev/packages/flutter_wowza

**Comment by ened** [comment]
RTSP Android side may be covered by https://github.com/flutter/plugins/pull/3933

**Comment by stuartmorgan** [comment]
Rescoping this to adding support on Android, where doing so is feasible. Making a new plugin for platforms where the wrapped player doesn't support it is out of scope.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/4447 had a partial implementation of this, if anyone is interested in picking it up again and completing the PR.

**Comment by Moyout** [comment]
> Rescoping this to adding support on Android, where doing so is feasible. Making a new plugin for platforms where the wrapped player doesn't support it is out of scope.

ExoPlayer project is deprecated.  Should have turned towards AndroidX Media3 direction.  AndroidX Media3 undoubtedly supports streaming media.

**Comment by matanlurey** [comment]
RSTP was completed here: https://github.com/flutter/packages/pull/7081.
