### ISSUE TITLE
Need ability to load/unload bundles to FlutterView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18114]
`runFromBundle` on FlutterView can be called only once. Some add-to-app use cases (such as letting `RecyclerView` manage the lifecycle of the `FlutterView`) requires us to be able to unload these bundles and load them up again. This also affects use cases where the app bundles are dynamically loaded from a URL. According to @sbaranov, this is one the roadmap so I am creating a tracker issue here. Please dedupe as needed.

**Comment by mravn-google** [comment]
@mehmetf This issue seems to be asking for a very fine-grained integration of Flutter into an existing app, and one might indeed wish that a `FlutterView` was comparable to, say, a `TextView` in terms of overhead. This is not currently true, and making it more true might require significant work on reducing the overhead of launching a Dart isolate etc.

So the question is: How urgent is this? And would it make sense to consider alternatives, like using a platform message to tell an existing `FlutterView` to show a different widget?

**Comment by mehmetf** [comment]
@sbaranov is the better person to comment on this requirement.  The isolate overhead needs to come down regardless because of two things:
- For loading code over the wire, we have to spawn a new isolate.
- On both Android and iOS, putting FlutterView inside of a list implies being able to load/unload the isolate relatively quickly.

**Comment by sbaranov** [comment]
The way this is solved today is by destroying the FlutterView and creating a new one from different bundle. I believe this already works. I don't know if there's a way today to replace the bundle without first destroying FlutterView, so this is definitely not a duplicate issue if someone indeed has such requirement.

**Comment by matthew-carroll** [comment]
@mehmetf Do you think this issue will automatically resolve with the architectural changes in the Android embedding refactor?  The changes I'm making will treat the FlutterView as the simplest rendering/interactive surface possible, and the backing engine can be attached/detached at will.  I think that resolves the Adapter issue, right?

**Comment by mehmetf** [comment]
API-wise yes, so I am going to close this issue.

I suspect we will have more fine-grained issues opened about the speed of the isolate loading which has nothing to do with the embedding refactor.
