### ISSUE TITLE
padding and other basic properties should exist on every widget

### ISSUE THREAD

**Issue by touseefbsb** [flutter/flutter#18116]
**Feature request**

padding, margin , alignment and other basic properties like these should be available on every kind of small or big widget, why do I need to provide an extra widget for padding or center the textfield, all these basic widgets should just have a property to set padding and other basic properties on it, this way code will be much simpler and cleaner. Thoughts?

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by Kartik1607** [comment]
Flutter provides a widget which have padding, margin, alignment etc. It is called Container widget. Container widget is then broken up into the various widgets. If flutter provides basic properties in every widget, each widget would take up more of nodes in the render tree.

Also, flutter widgets are immutable, and the render tree is updated every frame. Adding these to every widget could impact performance as well. 

As for why do we need center widget, padding widget etc as parent of widget, you need to understand flutter rendering pipeline.

Flutter rendering pipe line is a bit different. Flutter renders the widgets in a render tree. While traversing the tree, and going from root to leaves, the parent node passes some constraints to the widget. Child widget uses this constraint and calculates it's own size. Then while going from leaf to root back up the child returns its own size to the parent. Based on size, the parent positions the child.

**Comment by touseefbsb** [comment]
ahan thanks for the explaination @Kartik1607  being immutable sure does promote functional programming but as you stated, it also has performance hit. I hope the framework can find a middleground with immutable widgets and optimal performance

**Comment by Hixie** [comment]
@touseefbsb You can definitely create widgets that have padding and so on, just like Container. So if you want Row to have a Padding, for example, you could create a TouseefRow that had a padding argument and that did the right thing with it.

We've found that in practice while people do use Container sometimes to get a bunch of properties at once, people also often just end up using Padding and Center and so on directly, and it's very rare that you really need the widgets like Row or Checkbox to have padding.

I'm going to close this issue since I don't think we're likely to go in that direction at the moment, but please don't hesitate to file new issues or ideas in the future!
