### ISSUE TITLE
Flutter displays only two kinds of font weights in Chinese.

### ISSUE THREAD

**Issue by MiaYi** [flutter/flutter#18150]
I have an experiment of font weight variation from w100 to w800. However the builtin Chinese characters are only 2 kinds of weight variations.

result
![img_6651 3](https://user-images.githubusercontent.com/15973609/40886670-f5ab8276-676e-11e8-8a6a-d9d35af783e1.PNG)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.2-pre.42, on Mac OS X 10.13.4 17E199, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

Test code is available from:
https://gist.github.com/MiaYi/710ffc33aa6381de809e515d421080d0

**Comment by jason-simmons** [comment]
Flutter and Skia will search for a font that most closely matches the requested weight.  But if the font does not provide variants with different weights, then Skia will render a synthetic "fake bold" version of the font.  The "fake bold" is an on-or-off option and does not provide multiple weight levels.

Also, if the font family specified in the text style does not include a character, then Flutter will try to find some other font that does contain the character.  The selected fallback font might not have the desired weight variants.  Try explicitly specifying a different font family if you know that a font with the intended weighting exists and you want to ensure that this font is selected.

**Comment by jason-simmons** [comment]
https://github.com/flutter/engine/pull/5474 should improve this in situations where the host OS does provide different typefaces for different font weights

**Comment by LastMonopoly** [comment]
Is the problem solved? @MiaYi

**Comment by LastMonopoly** [comment]
Can you take a look at this problem? @GaryQian

**Comment by GaryQian** [comment]
The root cause of this is that the font family simply does not support the different weights, or the additional weights were not included in the font family. Without the additional data to work with, we can only fake the weight using skia fakebold.

You should be able to provide a more comprehensive font with all the weights, and Flutter will properly display all of the correct weights.

**Comment by GaryQian** [comment]
The problem with including a large range of weights for CJK fonts is that since the glyph set of CJK fonts are enormous, the file size is often very large. By providing two weights instead of one, the filesize is essentially doubled. Providing four weights causes a 4x increase in file size. Full comprehensive CJK font families can be hundreds of MB and can be a serious I/O bottleneck.

**Comment by LastMonopoly** [comment]
> The problem with including a large range of weights for CJK fonts is that since the glyph set of CJK fonts are enormous, the file size is often very large. By providing two weights instead of one, the filesize is essentially doubled. Providing four weights causes a 4x increase in file size. Full comprehensive CJK font families can be hundreds of MB and can be a serious I/O bottleneck. (for example, NotoSansCJKsc with all weights is 115MB)

So, no solution right now?

**Comment by LastMonopoly** [comment]
@GaryQian Please take a look at this problem again, still not resolved.
