### ISSUE TITLE
Issue from website page Working with long lists

### ISSUE THREAD

**Issue by mikemaksymowych** [flutter/flutter#18168]
From URL: https://flutter.io/cookbook/lists/long-lists/

According to [this page](https://flutter.io/flutter-for-android/#listviews--adapters), in Flutter we should recycle items manually, but I can't find any examples or mentions in the code on how to do this.

**Comment by goderbauer** [comment]
@brianegan

**Comment by brianegan** [comment]
Thanks for pinging me @goderbauer.

Heya @mikemaksymowych -- could you elaborate a bit on the specific section you're talking about? The linked section says: "In an Android ListView, you create an adapter and pass it into the ListView, which renders each row with what your adapter returns. However, you have to make sure you recycle your rows, otherwise, you get all sorts of crazy visual glitches and memory issues."

I believe this is referring to Android ListViews / RecyclerViews, where you're generally required to use the ViewHolder pattern to recycle Views for performance reasons.

In Flutter, you don't need to worry about this type of recycling, because "Flutter takes care of making sure that scrolling is fast and smooth."

That said, if you have `StatefulWidgets` in a List that call out to Web Services or Databases or listen to Streams of Data, it is generally a good idea to ensure you override the `dispose` method and ensure you tear down any connections to those data sources.

Please let me know if that helps, or if I missed something in that description!

**Comment by mikemaksymowych** [comment]
Hi @brianegan, thanks for clearing it up. I had been fighting a memory "leak" for a few days and when I came across this paragraph I misread it as meaning that Flutter required some sort of disposal/recycling. It's all clear now!

**Comment by brianegan** [comment]
Ah, gotcha. Yah, I've seen similar "memory leaks" in a demo app I've been playing with that shows animated gifs in a ListView. Starts to eat up more and more memory, and occasionally crashes on my emulator (not on real device, however).

Anyhow, I'll go ahead and close this out, but please feel free to respond if ya need anything else :)
