### ISSUE TITLE
Rewrite Android shell code to reflect the engine updates

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18186]
@chinmaygarde has done a lot of extensive engine updates in the past weeks ([Google-internal doc](https://docs.google.com/document/d/1n7xgoIpgxMmbVqrkbhYQUHTg0br-By1RSv1psXDIMow)). We need to update the Android shell code to reflect this new world. From what I understand, there's a lot of work to be done in this area. Chinmay, can you please do a pass and come up with a list of action items that can be knocked down by @mravn-google and perhaps myself?

Needless to say, we should strive to avoid breaking changes.

**Comment by chinmaygarde** [comment]
The updates specified in that document are necessary to support multiple shells in the same process with each using their own thread and isolate configurations. This unblocks us from being able to create multiple Flutter views with their own isolates/thread as well as isolates launched in background context without any rendering concerns. It is important to highlight that these features are not implemented in the mobile shells currently (only Fuchsia uses them). But the refactor is a necessary precursor to us supporting these features in the future.

Also, after the shell refactor, there were no changes necessary to the Android or iOS public APIs. However, the way these public APIs were implemented had to be updated to account for the shell API (which is private) updates. If that refactor has caused changes to the public API, it would have broken our templates and the apps already created in the wild that used those templates. So I am not entirely sure what you mean when you say the Android shell code has to be updated to reflect the new world.

Now, the refactor does enable us to implement features we could not before. These features have been listed in the following issues:
* Flutter should provide an abstraction for background execution #3671
* Secondary isolates should get dart:ui bindings. #13343
* Engine support for headless Dart code #6192
* Allow the plugins mechanism to work work with multiple Flutter applications (including isolates launched from the background). Currently, all plugin calls from/to secondary Flutter applications are broken because that infrastructure [assumes that the process only contains one Flutter application](https://github.com/flutter/engine/blob/014a53f588bd36d20fbe143650d32c5aea7ee395/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm#L255).
* Figure out if native plugin calls from background code should be realized in their own isolates or in the isolate of an already running Flutter application. If it is the latter, how is that application chosen? In the [alarm manager prototype](https://github.com/flutter/flutter/issues/6192#issuecomment-344821435), the same isolate was reused because it was accessed via a singleton. This is no longer viable. We need to figure out what the best model here is.

**Comment by mehmetf** [comment]
This issue is supposed to capture our chat the other day about no longer applying "bandaids" to the Android shell code. My gathering from that conversation was that we need to sit down and figure out a design that more closely reflects what the engine implementation is and what we want our long term APIs to be. E.g. getting rid of "FlutterMain" was mentioned.

The last two issues you mention is exactly what I am looking to solve. We indeed need to figure out what the best model is and I believe you can inform that design (then we can implement). I will chat with you f2f tomorrow to capture this.

**Comment by chinmaygarde** [comment]
The proposal is [up for initial comments here](https://docs.google.com/document/d/1AgzL8WEBc6ZMAoJr833nEREooXqwlg9VyxFsXrTTpBA).

**Comment by marcmo** [comment]
any chance to view the content outside of google?

**Comment by matthew-carroll** [comment]
I'm going to close this issue because I think the goal of a more appropriate Android abstraction has been accomplished.

Abstractions around background execution will be investigated by other tickets within this project:
https://github.com/flutter/flutter/projects/27

The engine-side updates to facilitate plugins has been spearheaded by @bkonyi, so I'll defer to him on any such progress and tickets, rather than have this one ticket act as an umbrella issue.
