### ISSUE TITLE
Java developers can be confused by Dart Null behavior

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#18207]
http://cogitas.net/5-lessons-learned-flutter/

"""
Don’t let your print statements crash your app
While working on new code, I often litter it with print statements, so if it doesn’t work  as expected when I run it, I can find out from the logs why. Well, sometimes, the print statements were the reason for the problem!

It turns out that `print("Step 1" + expectedStringInstance.toString())`  will run fine if `expectedStringInstance` is `null` but `print("Step 1" + expectedStringInstance)` will throw an `ArgumentError` exception.

As a Java developer, it’s one of the few counter intuitive things I have found in Dart and I keep being caught out! (I’m guessing it is because null is an instance of the class Null)
"""

Seems like something we should add to our "Flutter for Android Devs" doc?
https://flutter.io/flutter-for-android/

Thoughts @Sfshaza @mjohnsullivan?  Not at all urgent. :)

**Comment by jacob314** [comment]
As some background: 
In Dart if you want to format debug messages you should use string interpolation instead of string concat. String + is designed to be strict to help developers catch bugs early and only allows adding strings to strings not arbitrary objects.
This avoids bugs like showing `Username: undefined` or `Destination: [[Object]]` in their UI because an object was concat with a String.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2061](https://github.com/flutter/website/issues/2061) via [**ZenHub**](https://www.zenhub.com/)
