### ISSUE TITLE
Would like a Cast / ChromeCast plugin for Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#18212]
The Cast team received a request for Flutter support in https://issuetracker.google.com/80453460. It's not clear that adding such would require any work to the Android or iOS Cast SDKs, so I've filed this.

I suspect the desired solution here would be for someone to write a Cast plugin for Flutter, wrapping the iOS and/or Android Cast SDKs:
https://developers.google.com/cast/docs/developers

Flutter's plugin docs are here:
https://flutter.io/developing-packages/

And many examples here:
https://github.com/flutter/plugins

My understanding of the Cast SDK, is that different actions get casted differently.  For example Videos use a separate path than sending screen-by-screen frames, etc.  I'm not familiar enough with the details of the Cast SDK to know how much depth there is to such a plugin, or if to have "full support" will require any changes to the Flutter Engine or Framework itself.

**Comment by gedw99** [comment]
Thanks for raising this.. I raised it with the cast team.

**Comment by bostrot** [comment]
Any update on this?

**Comment by eseidelGoogle** [comment]
No significant update.  I've spoken with at least one member of the Cast SDK team.  I've also now spoken with two teams inside Google who have at least mild interest in a Cast SDK plugin for Flutter existing, but I'm not aware of any engineers actively working on such.

**Comment by Brahmasmi** [comment]
Based on my limited understanding of Google Cast, I do not know if there are changes required to the Flutter engine or the framework.

However, Cast has historically been a fairly fast moving target. It is current on v3 of the SDK. So I think the Cast plugin would be more maintainable in the long term if the Cast team themselves took ownership of it. If I could draw an analogy, it is similar to how Dart's gRPC implementation is better at home in the Protobuf org rather than the Dart org. The domain specs (Protobuf, gRPC) are more important than the language/framework specs.

Just my 2 <fiat_currency_unit/100>.

**Comment by gedw99** [comment]
Good point. Is there anyone in this issue from the Cast team ? What is the
teams position on taking on flutter plugin for cast ?

**Comment by pyros2097** [comment]
Yep. Yep. I'm planning on trying a poc to test if I could use the android cast sdk v3 and integrate it into  my app.

**Comment by dlevesque1980** [comment]
Hi,
This is a plugin I am doing about this. This is not complete, but at a working state. For now It is android only and I am not sure I will do the iOS part. I am a dotnet developer with no experience in Android and iOS. Doing this in Kotlin is already a huge learning curve. The code is MIT license feel free to fork.
https://github.com/dlevesque1980/cast

**Comment by ngocdaothanh** [comment]
Hi, is there any update about this feature?

I've just bought a Chromecast (latest generation), and I'm really excited to cast from Flutter. My main use is casting audio from iOS.

**Comment by snaeji** [comment]
This would be a great feature!

**Comment by mattspaeth** [comment]
I agree. My client is definitely looking for this ability. Considering React Native because it already has a package for this.

**Comment by snaeji** [comment]
I would really like to see this as a goal... It's the most requested feature we have for our app.

**Comment by SocialMammoth** [comment]
This would be a huge step forward for Flutter apps. Please make Chromecast support a priority!

Thanks <3

**Comment by ott-web** [comment]
Is this request really 9 months old? We should be able to do this pretty easily as a community.

**Comment by dlevesque1980** [comment]
There is android plugin I made there. https://github.com/dlevesque1980/cast
For the IOS part I don't the apple license to do it. But If someone is interesting in doing it. My pleasure to help.

**Comment by wilsharo** [comment]
Hi. I see a lot of people have been wanting this feature. So just want to inform you that a developer implemented casting purely in dart and has an example to use it below. 

https://github.com/terrabythia/flutter_chromecast_example

However that example is a little outdated and doesn't work as is. Well I'm glad to inform you that I was able to make some updates to the example project and their dart_chromecast package in order to get this working. I also added controls to play, stop, pause, and fastforward/rewind videos. And best of all it works for both Android and iOS!

Credit should go to terrabythia. But I hope my example helps. 

https://github.com/wilsharo/flutter_chromecast_example

@eseidelGoogle @gedw99 @ott-web @PhilParisot @dlevesque1980

**Comment by showang** [comment]
I made a plugin for display cast button and control connecting behavior.
But does not include cast media behavior, because it's implementation depends on your player.

https://pub.dev/packages/flutter_google_cast_button 

I hope it will helps. : )

**Comment by Hixie** [comment]
Since there are packages and examples for this, I'm going to close it. It's highly unlikely the Flutter team itself would implement this as it is outside of our area of expertise.

**Comment by amitnair32** [comment]
How i can loop a video that's being cast ?

**Comment by amitnair32** [comment]
How can i add loop to video?

**Comment by amitnair32** [comment]
Can i loop videos
