### ISSUE TITLE
We tested flutter_gallery on oppo r7 and found that the local image does not show the problem, and our own app also has this problem. Customer service has feedback Huawei PLE-703L and oppo r7 and Vivo6plus have this problem

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#18269]
We tested flutter_gallery on oppo r7 and found that the local image does not show the problem, and our own app also has this problem, customer service has feedback Huawei PLE-703L and oppo r7 and Vivo6plus have this problem! I come from China!
![image](https://user-images.githubusercontent.com/10591822/41100620-727e245c-6a94-11e8-896e-01dc353e48ca.png)
![image](https://user-images.githubusercontent.com/10591822/41100625-76d9abde-6a94-11e8-9ec9-13642ddc028a.png)

**Comment by zhangruiyu** [comment]
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

**Comment by zhangruiyu** [comment]
@HansMuller

**Comment by Skylled** [comment]
Possibly related: #13763

**Comment by Hixie** [comment]
Could be device-specific.

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by zhangruiyu** [comment]
Galaxy A7 has a problem, too

**Comment by zhangruiyu** [comment]
Galaxy A7 has a problem, too @Hixie @zoechi @jason-simmons

**Comment by debuggerx01** [comment]
![oppo](https://user-images.githubusercontent.com/19624835/41196754-12b00a98-6c7b-11e8-8599-07bd77acfd64.gif)
@Hixie It's very odd . I tested this with some devices , it's quite common in some chinese mobile (just like oppo R7 series) . I tried to find probrem from system log , but I can't find any suspect info . But I found the same model phone whitch has this issue may works well when using a different rom , so i think it maight be caused by some system problem in customed rom in China.

**Comment by zhangruiyu** [comment]
I see the master has been repaired

**Comment by zhangruiyu** [comment]
Repair in version 0.54
