### ISSUE TITLE
Issue with wiki page Tracing-GL-Calls-in-Skia

### ISSUE THREAD

**Issue by mikemaksymowych** [flutter/flutter#18273]
https://github.com/flutter/engine/wiki/Tracing-GL-Calls-in-Skia

Using this page as my reference, I wasn't able to trace any Skia calls in the Observatory. Should this method still work?

@chinmaygarde

**Comment by mikemaksymowych** [comment]
My current workaround is to do something like this in Skia files that I want to trace in the Observatory/time line:

```c
#include "third_party/dart/runtime/include/dart_tools_api.h"
#define TRACE_START(name)           \
    Dart_TimelineEvent(name,        \
        Dart_TimelineGetMicros(),   \
        0,                          \
        Dart_Timeline_Event_Begin,  \
        0,                          \
        nullptr,                    \
        nullptr                     \
    );
#define TRACE_END(name)             \
    Dart_TimelineEvent(name,        \
        Dart_TimelineGetMicros(),   \
        0,                          \
        Dart_Timeline_Event_End,    \
        0,                          \
        nullptr,                    \
        nullptr                     \
    );
```

**Comment by chinmaygarde** [comment]
I believe that method still works. Are you sure you also passed in the `--trace-skia` flag to the run call?

**Comment by mikemaksymowych** [comment]
I did not use that flag. With `--trace-skia`, all is fine. Is that flag documented somewhere?

Thanks!

**Comment by chinmaygarde** [comment]
From the tools: `flutter help run` lists that flag. Also, `flutter-tester --help` lists all supported engine flags along with a short description of what they do. The same engine used in the tester is used on the device as well.

Caveat: On Android, flags need to be packaged (on a per flag basis) into an intent, so you cannot use the tools to pass these flags unless the tools explicitly forward these flags. For this reason, it is easier to just pass these flags on iOS by specifying the same in the Xcode run configuration. So, if you are using a flag to the flutter tool, it is guaranteed to work on all platforms. OTOH, if you are specifying an engine flag, you need to do some per platform configuration. We do this because not all engine flags are stable or useful to the end user.

**Comment by chinmaygarde** [comment]
I added the note about the extra flag to the wiki.
