### ISSUE TITLE
Make Path serializable

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#18458]
Path objects, as they are exposed today, are opaque - once a line/curve/shape is added to them, it is not possible to inspect them (beyond getting bounds and measurements).

I would like to have an efficient way to serialize (and deserialize) Paths.  Some use cases:

- Capture and save a drawing/signature as a vector (rather than being forced to rasterize it).
- Have an efficient way to store and retrieve Paths that were created at runtime from other data (e.g. from SVG path data)

There was previously discussion around using SVG Path data strings, which Skia has some built in support for, here: https://github.com/flutter/engine/pull/4784 - which was rejected for being too SVG specific and potentially bloating the engine.

It would be fine for me if we could even just get the verbs, points, and weights from an SkPath - although it might be nice to expose weights in a more friendly way, or perhaps to stick to a normalized subset of the possible path verbs in Skia (e.g. by decomposing certain curves to a another equivalent curve).  This could be done without adding (much) additional code to the engine, at the cost of relying on Skia's internal Path implementation details a bit more.

**Comment by dnfield** [comment]
And to clarify, my suggestion here is to expose `SkPath::getVerbs` and `SkPath::getPoints`.

There is no current way I can see to get the weights from an SkPath, and it really looks like it's only ever used for `Conic`s and is set to 1 (set to 0 in all other cases).

**Comment by dnfield** [comment]
Another option is to have anyone who creates a Path manually keep track of how they did it and serialize that.

**Comment by DeRealMorgan** [comment]
I do have (yet another) issue with Paths.

My goal: I am trying to serialize my Path objects and send them to another client so that the client can display exactly the same Path.

This seems not doable at the moment as I cant access anything from the Path object.

I need a Path object instead of a plain array of captured points as this will decrease the packet size a lot - which is a lot of money I dont have to spend for a more powerful server.
