### ISSUE TITLE
Text height depends on language

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#18473]
## Steps to Reproduce

Text widgets with same TextStyle, depending on language of text, they will be different height.

iOS simulator:

<img width="509" alt="2018-06-14 18 21 36" src="https://user-images.githubusercontent.com/1098127/41403775-ab54ef6a-7000-11e8-8d8f-685d276e46f4.png">

Android emulator:

<img width="616" alt="2018-06-14 18 22 44" src="https://user-images.githubusercontent.com/1098127/41403784-b2bb0528-7000-11e8-8b3e-fafdf746ed36.png">

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(title: Text('Text heights')),
      body: new DefaultTextStyle(
        child: Padding(
          child: new Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Expanded(
                child: new Container(
                  color: Colors.blue,
                  child: Text("A B C D E F G H I", maxLines: 2, softWrap: true),
                ),
              ),
              Expanded(
                child: new Container(
                  color: Colors.red,
                  child: Text("A B C 😀 G H I 😀", maxLines: 2, softWrap: true),
                ),
              ),
              Expanded(
                child: new Container(
                  color: Colors.yellow,
                  child: Text("あいうえお", maxLines: 2, softWrap: true),
                ),
              ),
              Expanded(
                child: new Container(
                  color: Colors.green,
                  child: Text("あい😀えお", maxLines: 2, softWrap: true),
                ),
              ),
            ],
          ),
          padding: EdgeInsets.only(top: 16.0),
        ),
        style: TextStyle(
          fontSize: 36.0,
          color: Colors.white,
          height: 1.0,
        ),
      ),
    ),
  ));
}
```

## Logs

No errors.

```
[✓] Flutter (Channel dev, v0.5.4, on Mac OS X 10.12.6 16G1314, locale ja-JP)
    • Flutter version 0.5.4 at /Applications/flutter
    • Framework revision 3019ad976d (3 days ago), 2018-06-11 11:31:25 -0700
    • Engine revision d33bbff470
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.24.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.13.2

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone X                  • 3264D9F7-7AB5-4C13-8863-85CEC0730DB1     • ios         • iOS 11.2 (simulator)
```

**Comment by TheMelody** [comment]
Please make sure your screen is wide and high；
Different width of the mobile phone screen display different effects；

**Comment by HansMuller** [comment]
Flutter now defers to system fonts for glyphs not found in the default Roboto font, see for example https://github.com/flutter/flutter/pull/17879. Perhaps that's why you're seeing different heights.

cc @jason-simmons

**Comment by najeira** [comment]
Even with the same FontSize, does the box size depends on the font?

**Comment by zoechi** [comment]
@najeira https://www.creativelive.com/blog/why-do-font-sizes-vary/ seems to answer that.

**Comment by najeira** [comment]
If the fonts are different, it is natural that it is different height. However, it is difficult to lay out that the height is different in the same font.

This is a screenshot of Google search with Chrome browser:

<img width="629" alt="2018-08-27 11 00 47" src="https://user-images.githubusercontent.com/1098127/44636775-82658c00-a9e8-11e8-9c7b-c9d0f027cfd1.png">

Alphabet and Japanese has same box height because they are in the same font.

**Comment by najeira** [comment]
I will try using a custom font to unify the alphabet and Japanese fonts.

**Comment by zoechi** [comment]
@najeira 

>  it is difficult to lay out that the height is different in the same font.

did you ensure this is the case?

I think it is what @HansMuller tried to point out that they might not use the same font:

> Flutter now defers to system fonts for glyphs not found in the default Roboto font,

**Comment by najeira** [comment]
It is not ensure whether it is the same font or not. However, I think that iOS has only system font "San Francisco". On Android, Roboto and NotoSans include both alphabet and Japanese.

**Comment by najeira** [comment]
When using a custom font, the alphabet, Japanese and emoji are the same height.

It is probably because different fonts are used for each character when font is not specified.

Since it does not occur in the platform-native development, I hope a solution.

**Comment by lastant** [comment]
@najeira could you solve the problem by using a custom font? Which font is working?

**Comment by najeira** [comment]
@lastant I confirmed it with "Noto Sans JP".

**Comment by cbracken** [comment]
Related #21997

**Comment by najeira** [comment]
In the Android native app, if the device is set to Japanese, NotoSans/Roboto is selected and both alphabet and Japanese are drawn with NotoSans/Roboto. iOS too. Therefore, the height will be the same.

Flutter and native, I think there is a difference in the mechanism of font selection.

**Comment by 100cm** [comment]
any process on this?

**Comment by najeira** [comment]
I work around this issue using StrutStyle.

See: [Controlling text height using StrutStyle](https://medium.com/@najeira/control-text-height-using-strutstyle-4b9b5151668b)

**Comment by 100cm** [comment]
@najeira Thanks a loooooooot! You are my best friend!

**Comment by GaryQian** [comment]
Ahh yes, forgot this issue was still open. Strut is designed to fix this along with many other height-related issues :)

I'm going to close this now!

**Comment by najeira** [comment]
This issue does not occur in the platform-native development, there is a difference in the mechanism of font selection.

It is better to have a solution without using StrutStyle.

**Comment by 100cm** [comment]
@GaryQian  this problem still not work. if I solved the text height, the hint text will have problem like this:

![image](https://user-images.githubusercontent.com/12691638/58298706-02514300-7e0f-11e9-94f0-e6b37dc44bc0.png)


the input text and prefix at the same line .but hint text will be strange..

**Comment by fanwgwg** [comment]
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
