### ISSUE TITLE
Dart roll regressed complex_layout_scroll_perf__timeline_summary

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#18519]
Dart roll https://github.com/flutter/flutter/commit/bc301263538776aec7eff1631bc1b58f43a5c953 or https://github.com/flutter/flutter/commit/57187b00b2172e7c3e394319764ec95032a0c97f had negative impact on two metrics in the `complex_layout_scroll_perf__timeline_summary` benchmarks:

* `missed_frame_build_budget_count`
* `average_frame_build_time_millis`

/cc @aam

**Comment by goderbauer** [comment]
The following `microbenchmarks` were also affected:

* `stock_animation_subsequent_frame_average`
* `stock_animation_close_first_frame_average`
* `stock_build_iteration`

**Comment by Hixie** [comment]
@a-siva

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/commit/c3b59399659804ee27629c285b1b630283cef221 seems to be the culprit with "missed_frame_build_budget_count" metric 8-run average on Moto G4 goes from 20.5 @839c03e092 to 30.5 @c3b5939965 cc @alexmarkov

**Comment by alexmarkov** [comment]
@aam, thank you for triaging. I'll take a look.

Possible reason for this regression is https://github.com/dart-lang/sdk/issues/33364, which is fixed on the tip of Dart SDK.

**Comment by alexmarkov** [comment]
Double checked the Dart SDK commits in that roll. I'm getting quite stable results for `missed_frame_build_budget_count` metric on my Moto G4:

https://github.com/dart-lang/sdk/commit/35b17f373014cdb54dc7f80cfa59cc7d5f9f3803 6, 5, 5, 6, 5
https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7 6, 7, 6, 7, 6

`average_frame_build_time_millis` is not so stable:
https://github.com/dart-lang/sdk/commit/35b17f373014cdb54dc7f80cfa59cc7d5f9f3803
2.520408163 | 2.203045685 | 2.407216495 | 2.324873096 | 2.153061224
Min: 2.153061224
Avg: 2.321720933
https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7
2.384615385 | 2.578680203 | 2.404145078 | 2.471204188 | 2.286458333
Min: 2.286458333
Avg: 2.425020637

These number are similar to what benchmarks dashboard shows. I can conclude that regressions of `missed_frame_build_budget_count` and `average_frame_build_time_millis` metrics of `complex_layout_scroll_perf__timeline_summary` benchmark were caused by https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7.

Also see https://github.com/flutter/flutter/issues/18378.

/cc @zanderso

**Comment by zanderso** [comment]
It looks like these benchmarks improved after the recent roll that included @rmacnak-google 's fix. @goderbauer can we close this?

**Comment by goderbauer** [comment]
Sounds good.

**Comment by Hixie** [comment]
Looking back, it really doesn't seem to have improved after all, at least not back to the original level.
