### ISSUE TITLE
Request for image_picker to use image automatically after taken with camera.

### ISSUE THREAD

**Issue by zoenberger** [flutter/flutter#18523]
Hello! Thanks for all of your brilliance!

I'm using the image_picker right now directly from camera. After taking a photo, there is a "Retake" or "Use Photo" option. I'd like for the taken photo to be used immediately after being taken. Perhaps this could be an additional parameter passed to the ImagePicker.pickImage() method.

**Comment by sir-boformer** [comment]
It depends on the camera app, at least on Android. So far I've only seen the retake behavior in the emulator.

To modify this kind of behavior, you would have to create your own camera widget with the camera plugin.

**Comment by cyanglaz** [comment]
@zoenberger As mentioned by @sir-boformer, there is no way that the image_picker can handle that. I understand what you need but you might have to create your own UI using the camera plugin to achieve this. https://pub.dartlang.org/packages/camera
I am closing this issue because of what I have mentioned above. If you have any other issue or concerns, please feel free to open a new issue with details.
