### ISSUE TITLE
Compartmentalize CupertinoNavigationBar causes error

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18535]
For some reason, I get this error when I try to compartmentalize CupertinoNavigationBar. What am I doing wrong? 

<img width="691" alt="screen shot 2018-06-16 at 6 08 22 pm" src="https://user-images.githubusercontent.com/666539/41502795-5eb8c46a-7190-11e8-9ce5-68bcf5e544e3.png">

```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blueGrey,
      ),
      home: CupertinoPageScaffold(
        navigationBar: new NavigationBar,
        child: Center(child: Text("Test!")),

      )
    );
  }
}

class NavigationBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new CupertinoNavigationBar(
      leading: Text("lead"),
      middle: Text("Title"),
      trailing: Text("Trailing")
    );
  }
}
```

**Comment by jonahwilliams** [comment]
Hi @lukepighetti 

The error is due to the fact that the `CupertinoPageScaffold` expects a widget that implements the [`ObstructingPreferredSizeWidget`](https://docs.flutter.io/flutter/cupertino/ObstructingPreferredSizeWidget-class.html) interface, such as the `CupertinoNavigationBar` class.  Your `NavigationBar` stateless widget class doesn't implement this interface, hence the type error.

If all you want to do is refactor parts of your widget tree, you could use a method instead. It could be defined on `MyApp` or as top level method, for example:

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blueGrey,
      ),
      home: CupertinoPageScaffold(
        navigationBar: _navigationBar('Title'),
        child: Center(child: Text("Test!")),
      ),
    );
  }

  CupertinoNavigationBar _navigationBar(String middle) {
    return CupertinoNavigationBar(
      leading: Text('lead'),
      middle: Text(middle),
      trailing: Text('Trailing')
    );
  }
}
```

**Comment by lukepighetti** [comment]
Yikes.

**Comment by zoechi** [comment]
Is there still something to do for the Flutter team?
