### ISSUE TITLE
VSC is tracking Flutter repo for some reason

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18572]
Confirmed that this is happening to other VSC users via Discord scuttlebutt.

If you ignore it, it seems to come back anytime you compile. Throws all kinds of errors during development. Something about it having too many changes to be tracked by Git.

<img width="386" alt="screen shot 2018-06-18 at 1 10 35 pm" src="https://user-images.githubusercontent.com/666539/41551315-72eb044c-72f9-11e8-8612-06a3bb0a91e9.png">

**Comment by goderbauer** [comment]
@DanTup

**Comment by DanTup** [comment]
I don't think is related to Dart Code at all, but I do have some questions!

1. What does your Explorer pane look like? Have you opened the Flutter folder? (If so, it's probably expected that you would see Git status for it; if not, I'm not sure why it's showing up - it doesn't seem to show up for me if I open files from Flutter)
2. Why do you have > 5000 dirty files in Flutter? Is that normal? I have 0 (though I'm running master). How did you install Flutter?

**Comment by lukepighetti** [comment]
I do not have Flutter in my explorer pane.
<img width="345" alt="screen shot 2018-06-18 at 4 42 56 pm" src="https://user-images.githubusercontent.com/666539/41561179-25ccc15a-7317-11e8-849f-54e59d50ae74.png">

I don't know why I have > 5000 dirty files in Flutter.

**Comment by lukepighetti** [comment]
I remember now. I had moved a project into the flutter directory by mistake and it must have overwritten the git folder in there. I have replaced the folder with a fresh one and everything appears to be just fine.

**Comment by DanTup** [comment]
Ah, glad you sorted it - though you mentioned other people were seeing this too?

**Comment by lukepighetti** [comment]
Yes, I did. That is why I posted here. Perhaps he also by chance made a mistake.

That all said, I am still seeing Flutter folder but not with the 5000+ changes.

**Comment by DanTup** [comment]
@lukepighetti Something still seems weird - in your screenshot you have 0 open files. I don't see why VS Code would be listing some Git repo from your drive in the Git section if you don't have it open in any way. The only reasonable reasons this should happen are:

- Your project (open folder) is inside your Flutter install
- Your flutter install is inside your project (open folder)
- You have a multi-root workspace that also includes Flutter (hard to tell because `Flutter_Test_1` is collapsed in your screenshot, though since that's the name of the folder on the Git window, I'm guessing it's not this)

If none of those are true, this could be a VS Code bug.

**Comment by DanTup** [comment]
Ok, I did just manage to repro :) Yesterday I was testing with Stocks; forgetting it was inside the Flutter tree. If I open another Flutter project (outside of the Flutter tree) and F12 into a Flutter file, Flutter then appears in my Git sidebar.

Turns out this is a "feature" of VS Code. Whenever you open a file, if it's inside a Git repo (the Flutter SDK is a git repo) it'll do this. Info is here:

https://github.com/Microsoft/vscode/issues/35555

You can disable it by setting `"git.autoRepositoryDetection": false,` in your VS Code User Settings.

**Comment by lukepighetti** [comment]
Thank you for spending so much time on this. I really appreciate it.
