### ISSUE TITLE
ListTile _getIconColor refactoring

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1857]
DrawerItem currently has a _getIconColor.
- [ ] The colours (black26, etc) in this logic should move to the ThemeData structure, so that when we lerp the theme the icon colours also lerp.
- [ ] The theme-brightness-based switch should move to the ThemeData constructor, so that when we switch brightness, the lerp for icon colours lerps smoothly, not snapping half-way between lerping from primary to primary to lerping from accent to accent when the brightness changes.
- [ ] The logic for which colour to pick should probably move to Icon, so that it's more universally usable.

See also https://github.com/flutter/flutter/issues/1815 which talks about killing DrawerItem. The issue here would still apply with whatever replacement it got, though.
See also https://github.com/flutter/flutter/issues/1858 which is the same for text style.

**Comment by pedromassangocode** [comment]
`DrawerItem` was replaced by `ListTile` since https://github.com/flutter/flutter/pull/8992 was merged. Based on the issue description, and on the current implementation the issue should be fixed in the `ListTile` now, since it still exist:

https://github.com/flutter/flutter/blob/5a2153d340f3c591d84d05d4634d34da32006943/packages/flutter/lib/src/material/list_tile.dart#L910-L928
