### ISSUE TITLE
Use Chrome Custom Tab in url_launcher, instead of custom WebView activity

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#18589]
On Android, most apps today tend to use Chrome custom tabs for launching URLs. This provides users with a more seamless experience from their app to the web page that's being launched vs. directly launching the browser.

See comparison: https://developer.chrome.com/multidevice/android/customtabs

**Comment by thedejifab** [comment]
Any new update regarding this?

**Comment by estevez-dev** [comment]
This can help: https://pub.dartlang.org/packages/flutter_custom_tabs

**Comment by daniellampl** [comment]
Any updates here?

**Comment by florian-obernberger** [comment]
Any news on this?

**Comment by VikasAwate5** [comment]
Is there any update regarding this update ?

**Comment by stuartmorgan** [comment]
Switching team assignment to Android; my expectation is that this wouldn't require new API (a new launch mode), but could simply replace our current hand-rolled webview window in the Android implementation.

**Comment by reidbaker** [comment]
@mariamhas  to confirm priority is correct.

**Comment by gnprice** [comment]
It would be great to fix this, because the current behavior (that hand-rolled webview window) is a very odd UX for when the user wanted to open a web page.

Specifically:
* The system status bar is hidden. That would be appropriate for playing a game, or for a lightbox-style display of a photo. It's not normal for simply viewing a web page.
* There's no app bar — so no title orienting the user with "yep, this is a web page, here's the website you're on"; no close button; no share button; no overflow menu for other features like "refresh" or "go forward" or "open in a browser app".

Here's a screen recording showing the current UX:

https://github.com/flutter/flutter/assets/28173/66b624fa-889f-4c13-a962-5b3dd77876b9

All told, as a user this UX doesn't feel like I'm getting a web browser. Or it feels like there's something wrong and broken — it's like how sometimes on a desktop OS if the system window manager crashes then all the applications appear without their title bars and close/maximize buttons.

This odd UX has led to a couple of reports in addition to this thread: the hidden status bar has been reported as #120883, and the lack of a close button at https://github.com/flutter/flutter/issues/120883#issuecomment-1523606839 .

A Chrome custom tab would provide all of the above browser-style features. It's the UX I'm accustomed to seeing in a wide range of Android apps when I follow a link from some content in the app out to an arbitrary web page, and it works nicely.

(And mentioning partly for the sake of search: the behavior we're talking about in this thread is that of `LaunchMode.inAppWebView` on Android, where it's also our default behavior.)

**Comment by gnprice** [comment]
Another issue which would also get resolved automatically if we switched to a Chrome custom tab:
* #105205

When a Chrome custom tab is opened at a URL that turns out to provide a PDF, it goes ahead and starts downloading the file and then offers it for the user to open in an appropriate app. (At least that's what I see when I try following a link to such a URL in a non-Flutter app that uses Chrome custom tabs.)

**Comment by cachapa** [comment]
I want to add that many OAuth terms of service explicitly forbid using webviews to limit exposure of the user's login credentials.

[Here's a relevant Google recommendation](https://support.google.com/faqs/answer/12284343).

**Comment by stuartmorgan** [comment]
This new mode will be supported for devices with Custom Tabs support (which will depend on installed browsers), and when not explicitly passing headers that aren't supported.

If for some reason someone wants to force the old webview behavior, you can do so by passing an arbitrary header in the launch request (e.g., `'prevent-custom-tabs': true`)
