### ISSUE TITLE
ListTile _getTextStyle refactoring

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1858]
DrawerItem currently has a _getTextStyle.
- [ ] The theme-brightness-based switch should move to the ThemeData constructor, so that when we switch brightness, the lerp for icon colours lerps smoothly, not snapping half-way between lerping from primary to primary to lerping from accent to accent when the brightness changes.

See also https://github.com/flutter/flutter/issues/1815 which talks about killing DrawerItem. The issue here would still apply with whatever replacement it got, though.
See also https://github.com/flutter/flutter/issues/1857 which is the same for icon color.

**Comment by pedromassangocode** [comment]
`DrawerItem` was replaced by `ListTile` since https://github.com/flutter/flutter/pull/8992 was merged. Based on the issue description and in the current implementation the issue should be fixed in the `ListTile` now, since it still exist:

https://github.com/flutter/flutter/blob/5a2153d340f3c591d84d05d4634d34da32006943/packages/flutter/lib/src/material/list_tile.dart#L955-L981
