### ISSUE TITLE
Expose Skia's drawText and measureText in the dart:ui Canvas API

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#18656]
_Edit: It seems like the text gradient bug that lead to this proposal was caused by a recent change in the Flutter engine, which will hopefully be fixed soon (see the discussion below). I think exposing the drawText method would still be nice for all the other reasons listed below._

-----

Right now the only way to draw text in a canvas is the [``drawParagraph`` method](https://docs.flutter.io/flutter/dart-ui/Canvas/drawParagraph.html). It allows you to draw single- and multi-line text with a max width, text ellipsis and inline formatting.

Before you can paint the text, you have to build a ``Paragraph`` object and call its ``layout`` method.

Internally, it uses Skia's [`drawTextBlob`](https://skia.org/user/api/SkCanvas_Reference#SkCanvas_drawTextBlob) method. 

------

While porting an existing Android/Web-Application to Flutter, what I often wanted to do is to draw a **single line** of text on a canvas. Often, I would also like to change the alignment of the text (centered, left right) relative to the offset coordinates, as well as measure the width of the text in advance. ~~Also, the app that I am porting draws text filled with [absolute positioned linear gradients](https://github.com/flutter/flutter/pull/18347#issuecomment-398590494).~~

In Android and the web, the main functions for canvas text drawing are [drawText](https://developer.android.com/reference/android/graphics/Canvas.html#drawText(java.lang.String,%20float,%20float,%20android.graphics.Paint)) (Android) and [fillText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText) (Web).

Both of them are less powerful, but also easier to use. I'm not sure if they are also more optimized.

Both of them just draw a single line of text (or multiple lines with manual `\n` line breaks). Both of them handle the [text align](https://www.wikitechy.com/step-by-step-html-tutorials/html5-canvas/img/canvas-images/output-textalign-property-in-html5-canvas.png) in the same way. ~~Both share the same gradient drawing behavior.~~

Also, both APIs provide a `measureText` method, which is basically like ``Paragraph.width``, but for a single line.

Most of the points above can be emulated with the ``drawParagraph`` method ~~(absolute positioned gradients only with a lot of possibly inefficent extra code)~~, but I would prefer a `drawText` method that does exactly the same thing as the other platforms.

Skia already provides [`drawText`](https://skia.org/user/api/SkCanvas_Reference#SkCanvas_drawText) and [``measureText``](https://skia.org/user/api/SkPaint_Reference#SkPaint_measureText) methods, they are just not exposed in Flutter.

**Comment by sir-boformer** [comment]
This is the discussion that lead to my proposal: https://github.com/flutter/flutter/pull/18347#issuecomment-398885580

**Comment by sir-boformer** [comment]
Now that you mentioned libtxt, I was able to find the cause of the special gradient behavior:

https://github.com/flutter/engine/blob/975d4ead668c8a5e8abe5b0a69a6f7f3e4984579/third_party/txt/src/txt/paragraph.cc#L874

libtxt uses the ´translate´ method of the canvas, which also translates the gradient. 

That's also the behavior on Android and Web, and thinking back, that's what I used there to make shaders/gradients relative positioned.

That means to fix the issue, all we have to do is to apply the offset/translation manually instead of using ´translate´.

**Comment by dnfield** [comment]
Looks like that was added in to fix an issue where text wasn't getting properly positioned: https://github.com/flutter/engine/commit/b7b556150cf148cab7b8e14631198ec9d5ed0c2b

**Comment by sir-boformer** [comment]
@GaryQian Is the `translate` call that was in your commit actually required for the fix, or just a try to make the code more elegant? It causes issues with gradient drawing.

**Comment by sir-boformer** [comment]
To come back to this, while porting an existing Android/web application to Flutter, I noticed that text layout and drawing with `TextPainter` is quite slow. Layouting and drawing about 50 short single-line texts in every frame decreases FPS in profile mode dramatically.

**Comment by sir-boformer** [comment]
If anyone else is encountering an issue with text layout performance: I've been working around the problem by introducing a cache for laid out TextPainters (for single line text):

```dart
import 'package:flutter/painting.dart';
import 'package:quiver/collection.dart';

class TextLayoutCache {
  final LruMap<TextSpan, TextPainter> _cache;
  final TextDirection textDirection;

  TextLayoutCache(this.textDirection, int maximumSize) : _cache = LruMap<TextSpan, TextPainter>(maximumSize: maximumSize);

  TextPainter getOrPerformLayout(TextSpan text) {
    final cachedPainter = _cache[text];
    if (cachedPainter != null) {
      return cachedPainter;
    } else {
      return _performAndCacheLayout(text);
    }
  }

  TextPainter _performAndCacheLayout(TextSpan text) {
    final textPainter = TextPainter(text: text, textDirection: textDirection);
    textPainter.layout();

    _cache[text] = textPainter;

    return textPainter;
  }
}
```

FPS almost doubled with this simple trick.

**Comment by jenisonleo** [comment]
Any updates on this feature request. Just curious

**Comment by GAM3RG33K** [comment]
is there any updates on this??

**Comment by GaryQian** [comment]
Regarding the translate call, we have since changed it to a different way of applying the offset. Can anyone confirm if the gradient issue is fixed?

Regarding performance, I remember fixing an issue where the width passed and the width stored in LibTxt was being rounded. This caused a mismatch between layouts that should otherwise be identical, which may be the cause of your fps issues

Regarding exposure of lower skia APIs, I have not fully explored this yet, but here are some initial thoughts. If you were to specify a SkFont that could provide `measureText`, it would require almost all of the same inputs as our existing `Text` widget. At this point, it would not incur significant overhead for simple unadorned text to simply layout the text as opposed to letting `measureText` call the same internal API to return the advances. Same applies for `drawTextBlob`. Unless there were a case where this was truly necessary, I am hesitant to add a parallel API to handle text, as the performance gains would be modest at best, and it would add significant confusion to devs trying to learn Flutter.

Setting a Paragraph to have very large width and then using `longestLine` would have the same effect as measureText. The paint method would also essentially wrap a single raw drawTextBlob call if no fancy TextStyles are applied.

Please let me know if you had a particular and specific use case in mind for the exposure of the skia API, and I can look into it further.

**Comment by Hixie** [comment]
We intentionally don't expose a method to do this, because we want to encourage caching of Paragraph objects across frames.
