### ISSUE TITLE
is flutter have concept like android “addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_CLEAR_TASK)”

### ISSUE THREAD

**Issue by vithanichandresh** [flutter/flutter#18792]
here is flow thats i want to manage back

1 - on click home page's button start store list page.
2 - on click store list page's button start filter page.
3 - on click store filter page's button store list page.
4 - on press back go to home page.

**Comment by zoechi** [comment]
cross-ref https://stackoverflow.com/questions/51022325/is-flutter-have-concept-like-android-addflagsintent-flag-activity-clear-top

**Comment by zoechi** [comment]
I don't really understand what you are asking for, but such behavior can be implemented for sure in Flutter, but Flutter works entirely differently than native Android SDK.
I'd suggest you start with the docs in https://flutter.io/ or perhaps with the https://github.com/flutter/flutter/tree/master/examples/flutter_gallery and check if one of the examples implements similar functionality and then check the source for how it is implemented.
I'm going to close this issue because StackOverflow is the better place for this kind of question anyway.
