### ISSUE TITLE
If you have a list with a focusable element, scrolling the list unfocuses it

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#188]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 21:25 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1529_

---

As each focusable element goes out of the list, we lose its global key, and so we assume that it's gone forever. We might need a way to chain a global key to another global key so that while the master is still alive, the slave isn't considered gone for the purposes of autofocus, or something.

**Comment by Hixie** [comment]
We should fix this and https://github.com/flutter/flutter/issues/105 at the same time. When an input has focus, it should send a notification to tell its ancestor list to keep it alive, so that the keyboard stays up, and if the user types, the text goes to the input, and so forth. If the keyboard is dismissed or the input loses focus, then it should send a release notification.

**Comment by Hixie** [comment]
This is basically the same bu as #105, #170, #172.

**Comment by Hixie** [comment]
Duping to https://github.com/flutter/flutter/issues/10826.

**Comment by ravipatel147** [comment]
I face issue , when i use Listview in form then focused field goes behind the keyboard so user can't see what is type in input any one can help me if already is faced

**Comment by zoechi** [comment]
@ravipatel147 see #10826 #18291 hopefully to land soon
