### ISSUE TITLE
Create a published iOS themed demo app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18802]
cc @RedBrogdon 

Create an iOS themed non copyright complex useful app to validate the iOS look-and-feel creation path. 

As a sample idea, show a list of local in-season produce. Use a tab view to show favorited produce.

**Comment by RedBrogdon** [comment]
This was started on Thursday, and work continues.

**Comment by mehmetf** [comment]
@RedBrogdon We are looking for apps to demo at the beginning of August for a conference. Any chance this will be ready by then?

**Comment by RedBrogdon** [comment]
The app is mostly completed, and can be used as a guide right now:

https://github.com/flutter/samples/tree/master/veggieseasons

There will likely be some additional updates to add more functionality prior to getting the app published (ideally that'll happen in the next week or two), which is why I haven't closed this out yet.

**Comment by xster** [comment]
Veggie Season is shipped \O/
