### ISSUE TITLE
TextField reloads the widget

### ISSUE THREAD

**Issue by guediagael** [flutter/flutter#18828]
## Steps to Reproduce

1.  Have a widget containing depending on a future builder 
2. Have one or more TextField(s) and/or TextFormFields
3. When I press/select/click you name it the future whole scaffold reloads.
 I load a list from an API and I wanted to implement a search through that list. The problem is any time I press into the input field, the keyboard appears for like an half of a second, the whole widget reloads.
Is there a work around ? 

## Logs

```
```

```
```

```
```

**Comment by guediagael** [comment]
``` dart
@override  
  Widget build(BuildContext context) {  
  FutureBuilder futureBuilder = FutureBuilder<List<Venue>>(  
  future: _getDataList(),  
  builder: (context, venuesList){  
  switch(venuesList.connectionState){  
  case ConnectionState.none: return new Text("No connection"); //TODO: have a custum error view that take as input the error message  
  case ConnectionState.waiting:   
 return Container(  
  alignment: Alignment.center,  
  margin: const EdgeInsets.only(top: 50.0),  
  child: new CircularProgressIndicator()  
 ); // TODO show loading wiht message  
  default:  
  if(venuesList.hasError){  
  print(' error ${venuesList.error}')  
  // TODO: show error  
  }else{  
  return _getWidgetList(venuesList.data);  
 } } } );  
  return Scaffold(  
  body: Container(  
  child: futureBuilder,  
 ) ); }
Widget _getWidgetList(List<Venue> venues){  
  return Column(  
  children: <Widget>[  
  Container(  
  margin: EdgeInsets.symmetric(vertical: 16.0),  
  height: 37.0,  
  child: Row(  
  mainAxisAlignment: MainAxisAlignment.spaceBetween,  
  mainAxisSize: MainAxisSize.min,  
  crossAxisAlignment: CrossAxisAlignment.center,  
  children: <Widget>[  
  Container(  
  height: 36.0,  
  width: 259.0,  
  child: TextField(  
  maxLines: 1,  
  decoration: InputDecoration(  
  icon: Icon(Icons.search),  
  hintText: 'Поиск',  
  fillColor: Colors.grey  
  ),  
 ), ),  Container(  
  height: 36.0,  
  child: Row(  
  children: <Widget>[  
  IconButton(  
  iconSize: 22.0,  
  onPressed: ()=> _openSearchModal(),  
  icon: Icon(Icons.sort, color: Colors.white,),  
 ),  Text('Пильтр')  
 ], ), ) ], ), ),  Expanded(  
  child: ListView(  
  children: venues.map((venue)=>Padding(  
  padding: EdgeInsets.only(bottom: 8.0),  
  child: _getDetailableCard(venue),  
 )).toList()  
 ), ) ], );}
```


flutter doctor - v 
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
    • Flutter version 0.5.1 at C:\Users\me\Downloads\programs\flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Users\me\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\173.4548.28
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[!] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by guediagael** [comment]
The only workaround I've found is to use a PageStorage() and also setting resizeToAvoidBottomPadding: false didn't hurt to much.

**Comment by sxd1140** [comment]
```dart
import 'dart:math';

import 'package:flutter/material.dart';

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build page1');
    return Scaffold(
      appBar: AppBar(
        title: Text('Math'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView.builder(
          shrinkWrap: true,
          itemCount: 50,
          itemBuilder: (BuildContext context, int index) {
            if (index.isOdd) return Divider();
            final random = new Random();
            final number1 = random.nextInt(10);
            final number2 = random.nextInt(10);
            return Center(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text('$number1'),
                  Icon(Icons.add),
                  Text('$number2'),
                  Icon(Icons.drag_handle),
                  Flexible(
                    child: TextField(),
                  )
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
```

Use 
```dart 
Navigator.push(context,MaterialPageRoute(builder: (context)=>Page1()));
```

The `Page1.build` method be call again when i click any `TextField`.

Then click another `TextField` everything is ok.

**Comment by sccrgoalie1** [comment]
I used this StackOverflow question for a workaround.  Basically, by storing the future the page doesn't reload when you click in the test field

[https://stackoverflow.com/questions/51224420/flutter-switching-to-tab-reloads-widgets-and-runs-futurebuilder](https://stackoverflow.com/questions/51224420/flutter-switching-to-tab-reloads-widgets-and-runs-futurebuilder)

**Comment by DarshanGowda0** [comment]
This issue still persists and is a serious problem. Using either TextFiled/TextFormFiled inside FutureBuilder/StreamBuilder refreshes the entire builder widget and calls the stream again. In my case cloud-firestore calls are made everytime I click on a TextField.

**Comment by DarshanGowda0** [comment]
The whole widget is refreshed and keyboard goes back within a split second as mentioned clearly by @guediagael . The suggest by @sccrgoalie1 helps to avoid the widget to refresh but the future or stream call is still made. Reads are charged on cloud-firestore and can be a serious issue here.

**Comment by DarshanGowda0** [comment]
The update to this is on this thread.[https://stackoverflow.com/questions/51571065/using-textfield-inside-a-streambuilder/51574523#51574523](url)

**Comment by zoechi** [comment]
The linked SO answer should solve the issue. Thanks @DarshanGowda0 for the link.
Please open a new issue if you think there is more work to be done.

**Comment by xiaoyaoking** [comment]
I had the same problem.

**Comment by muarifer** [comment]
> I had the same problem.

When cache future function, it works.
Please see: https://stackoverflow.com/questions/51224420/flutter-switching-to-tab-reloads-widgets-and-runs-futurebuilder

**Comment by harshshredding** [comment]
I think I might have a solution and a theory. This might not solve all you guy's problems.
Wherever you supply Future builder with a future, make sure it persists across builds by storing it in a variable in Stateful Widget. This will prevent the popping keyboard from building everything again.

Below is a common mistake where we **generate** future in every build. When we generate like this, our application makes a call to the network again, causing everything to rebuild : 

```
class Test {
  Future<Something> getFuture() {
    return generateFuture();
  }
  
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: getFuture(); // generate every time
        builder: () {
           return TextField();
        }
     )
  }
}
```

We should do this instead: 

```
class Test {

 Future<Something> _future = getFutureFromSomewhere(); // Can use setState() to do this as well

  Widget build(BuildContext context) {
    return FutureBuilder(
        future:  _future; // generate every time
        builder: () {
           return TextField();
        }
     )
  }
}
```

**Comment by karnakhilesh** [comment]
> This issue still persists and is a serious problem. Using either TextFiled/TextFormFiled inside FutureBuilder/StreamBuilder refreshes the entire builder widget and calls the stream again. In my case cloud-firestore calls are made everytime I click on a TextField.

I have same problem

**Comment by urvesh-educloud** [comment]
When i am tap on textformfield it rebuid all the widgets which is created.
my sample code is
`import 'package:flutter/material.dart';
import 'package:flutter_app/src/mo/Standard/Standard.dart';
import 'package:flutter_app/src/mo/TimeTable/AcademicPlannerWidget.dart';
import 'package:flutter_app/src/mo/TimeTable/SubjectDropDown.dart';
import 'package:flutter_app/src/mo/TimeTable/TimeTable.dart';
import 'package:flutter_app/src/mo/TimeTable/TimeTableActivity.dart';
import 'package:flutter_app/src/mo/TimeTable/TimeTableDatePicker.dart';

class LessonPlanUIStateLess extends StatefulWidget {

  final title;
  final TimeTable timeTableObj;
  TimeTableActivity timeTableActivity = new TimeTableActivity();

  LessonPlanUIStateLess({
    Key key,
    @required this.title,
    @required this.timeTableObj,
  }) :  assert(title != null && title != ''),
        assert(timeTableObj != null),
        super(key: key);

  @override
  _LessonPlanUIStateLessState createState() => _LessonPlanUIStateLessState();
}

class _LessonPlanUIStateLessState extends State<LessonPlanUIStateLess> {

  final scaffoldKey = GlobalKey<ScaffoldState>();
  final formLessonPlanKey = GlobalKey<FormState>();
  final fieldKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      appBar: getAppBar(),
      body: getPageBody(),
    );
  }

  Widget getAppBar() {
    return AppBar(
      elevation: 0,
      title: Text(widget.title),
      actions: <Widget>[
        FlatButton(
          onPressed: (){
            onSave();
          },
          child: Text("Pre-Plan"),
        ),
        FlatButton(
          onPressed: (){
            onSave();
          },
          child: Text("Publish"),
        )
      ],
    );
  }

  Widget getPageBody() {
    return SafeArea(
        child: Container(
          child: Form(
            key: formLessonPlanKey,
            child: ListView(
              children: getFormsFields(),
            ),
          ),
        )
    );
  }

  List<Widget> getFormsFields() {
    List<Widget> widgetList = new List();

    Widget classWidget = getStandardDropDown();
    if(classWidget != null){
      widgetList.add(classWidget);
    }

   /* Widget subjectWidget = getSubjectsDropDownWidget();
    widgetList.add(subjectWidget);*/

    Widget startDateWidget = getStartDateWidget();
    if(startDateWidget != null){
      widgetList.add(startDateWidget);
    }

    Widget endDateWidget = getEndDateWidget();
    if(endDateWidget != null){
      widgetList.add(endDateWidget);
    }

    Widget lectureNotesWidget = getLectureNotesWidget();
    if(lectureNotesWidget != null){
      widgetList.add(lectureNotesWidget);
    }

    Widget academicPlannerWidget = getAcademicPlannerWidget();
    if(academicPlannerWidget != null){
      widgetList.add(academicPlannerWidget);
    }
    return widgetList;
  }

  Widget getStandardDropDown() {
    return Padding(
      padding: EdgeInsets.all(8.0),
      child: StreamBuilder<List<Standard>>(
          stream: widget.timeTableActivity.allStandardList,
          builder: ( context, snapshot ) {
            if (!snapshot.hasData) {
              return Center(
                child: CircularProgressIndicator(),
              );
            } else {
              List<Standard> standardList = snapshot.data;
              return getStandardDropDownWidget(standardList);
              //return getStandardDropDown_(standardList);
            }
          }
      )
      /*StandardDropDownUI(
        refBloc: widget.timeTableActivity,
        classObj: widget.timeTableObj.standard,
      ),*/
    );
  }

  Widget getSubjectsDropDownWidget() {
    return Padding(
        padding: EdgeInsets.all(8.0),
        child: SubjectDropDown(
          refBloc: widget.timeTableActivity,
          subjectObject: widget.timeTableObj.subject,
          classId: widget.timeTableObj.standardId,
        )
    );
  }

  Widget getStartDateWidget() {
    return Padding(
        padding: EdgeInsets.all(8.0),
        child: TimeTableDatePicker(timeTableObject: widget.timeTableObj,)
    );
  }

  Widget getEndDateWidget() {
    return Padding(
      padding: EdgeInsets.all(8.0),
      child: TimeTableDatePicker(timeTableObject: widget.timeTableObj,),
    );
  }

  Widget getLectureNotesWidget() {
    return Padding(
        padding: EdgeInsets.all(8.0),
        child: TextFormField(
          key: fieldKey,
          controller: TextEditingController(),
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: 'Lecture Notes',
          ),
          onSaved: (value){
            print(value);
          },
        )
    );
  }

  Widget getAcademicPlannerWidget() {
    return Padding(
      padding: EdgeInsets.all(8.0),
      child: AcademicPlannerWidget(
        formKey: formLessonPlanKey,
      ),
    );
  }

  onSave() {
    formLessonPlanKey.currentState.save();
  }

  Widget getStandardDropDownWidget(List<Standard> standardList) {
    return FormField (
      builder: ( FormFieldState state ) {
        return InputDecorator (
          decoration: InputDecoration (
              icon: Icon ( Icons.class_ ) ,
              prefixText: "test"
          ) ,
          child: DropdownButtonHideUnderline (
              child: Padding (
                padding: EdgeInsets.only ( right: 8.0 , left: 8.0 ) ,
                child: DropdownButton (
                  isDense: true ,
                  onChanged: ( dynamic newValue ){
                    setState ((){
                      //classOf = newValue.name;
                    } );
                    widget.timeTableActivity.getSubjectsByStandardId(newValue.id);
                    //widget.classObj = newValue;
                  } ,
                  items: standardList.map ( ( Standard standard ) {
                    return new DropdownMenuItem(
                      value: standard,
                      child: new Text( standard.name ) ,
                    );
                  }).toList () ,
                ) ,
              )
          ) ,
        );
      },
    );
  }

}
`

**Comment by Nandan-Wewhare** [comment]
> This worked for me. I think I might have a good theory; this might not solve all you guy's problems.
> Wherever you supply Future builder with a future, make sure it persists across builds by storing it in a variable in Stateful Widget. This will prevent the popping keyboard from building everything again.
> 
> Below is a common mistake where we **generate** future in every build. When we generate like this, our application makes a call to the network again, causing everything to rebuild :
> 
> ```
> class Test extends StatelessWidget {
>   Future<Something> getFuture() {
>     return generateFuture();
>   }
>   
>   Widget build(BuildContext context) {
>     return FutureBuilder(
>         future: getFuture(); // generate every time
>         builder: () {
>            return TextField();
>         }
>      )
>   }
> }
> ```
> 
> We should do this instead:
> 
> ```
> /// Stateful widget
> class Test extends State<Blah> {
> 
>  Future<Something> _future = getFutureFromSomewhere(); // Can use setState() to do this as well
> 
>   Widget build(BuildContext context) {
>     return FutureBuilder(
>         future:  _future; // generate every time
>         builder: () {
>            return TextField();
>         }
>      )
>   }
> }
> ```
> 
> Will repeat : _look for things that are not making your Future persists over builds._
> 
> They do a similar thing with stream builder [here](https://stackoverflow.com/questions/51571065/using-textfield-inside-a-streambuilder/51574523#51574523)

@harshshredding Thanks man, worked for me.

**Comment by federicoWax** [comment]
> La actualización de esto está en este hilo. https://stackoverflow.com/questions/51571065/using-textfield-inside-a-streambuilder/51574523#51574523

La respuesta funciono para mi gracias!

**Comment by ahamzatariq** [comment]
It's not the textField that triggers rebuilds but the keyboard.

Keyboard causing rebuilds
It makes total sense and is expected that the software keyboard opening causes rebuilds. Behind the scenes, the MediaQuery is updated with view insets. These MediaQueryData.viewInsets make sure that your UI knows about the keyboard obscuring it. Abstractly, the keyboard obscuring a screen causes a change to the window and most of the time to your UI, which requires changes to the UI - a rebuild.

I can make the confident guess that you are using a Scaffold in your Flutter application. Like many other framework widgets, the Scaffold widgets depends (see InheritedWidget) on the MediaQuery (that gets its data from the Window containing your app) using MediaQuery.of(context).
See MediaQueryData for more information.

It all boils down to the Scaffold having a dependency on the view insets. This allows it to resize when these view insets change. Basically, when the keyboard is opened, the view insets update, which allows the scaffold to shrink at the bottom, removing the obscured space.

Long story short, the scaffold adapting to the adjusted view insets requires the scaffold UI to rebuild. And since your widgets are necessarily children of the scaffold (likely the body), your widgets are also rebuilt when that happens.

You can disable the view insets resizing behavior using Scaffold.resizeToAvoidBottomInset. However, this will not necessarily stop the rebuilds as there might still be a dependency on the MediaQuery. I will explain how you should really think about the problem in the following.

Idempotent build methods
You should always build your Flutter widgets in a way where your build methods are idempotent.
The paradigm is that a build call could happen at any point in time, up to 60 times per second (or more if on a higher refresh rate).

What I mean by idempotent build calls is that when nothing about your widget configuration (in the case of StatelessWidgets) or nothing about your state (in the case of StatefulWidgets) changes, the resulting widget tree should be strictly the same. Thus, you do not want to handle any state in build - its only responsibility should be representing the current configuration or state.

The software keyboard opening causing rebuilds is simply a good example for why this is so. Other examples are rotating the device, resizing on web, but it can really be anything as your widget tree starts to get complex (more on that below).

StreamBuilder resubscribing on rebuild
To come back to the original question: in this case, your problem is that you are approaching the StreamBuilder incorrectly. You should not feed it a stream that is recreated each build.

The way stream builders work is by subscribing to the initial stream and then resubscribing whenever the stream is updated. This means that when the stream property of the StreamBuilder widget is different between two build calls, the stream builder will unsubscribe from the first and subscribe to the second (new) stream.

You can see this in the _StreamBuilderBaseState.didUpdateWidget implementation:

if (oldWidget.stream != widget.stream) {
  if (_subscription != null) {
    _unsubscribe();
    _summary = widget.afterDisconnected(_summary);
  }
  _subscribe();
}
The obvious solution here is that you will want to supply the same stream between different build calls when you do not want to resubscribe. This goes back to idempotent build calls!

A StreamController for example will always return the same stream, which means that it is safe to use stream: streamController.stream in your StreamBuilder. Basically, all controller, behavior subject, etc. implementations should behave this way - as long as you are not recreating your stream, StreamBuilder will properly take care of it!

The faulty function in your case is therefore _bloc.inputObservable(), which creates a new stream each time instead of returning the same one.

Notes
Note that I said that build calls can happen "at any point in time". In reality, you can (technically) control exactly when every build happens in your app. However, a normal app will be so complex that you cannot possibly have control over that, hence, you will want to have idempotent build calls.
The keyboard causing rebuilds is a good example for this.

If you think about it on a high level, this is exactly what you want - the framework and its widget (or widgets that you create) take care of responding to outside changes and rebuilding whenever necessary. Your leaf widgets in the tree should not care about whether a rebuild happens - they should be fine being placed in any environment and the framework takes care of reacting to changes to that environment by rebuilding correspondently.

I hope that I was able to clear this up for you :)


Copied from -> https://stackoverflow.com/questions/56313800/why-does-the-software-keyboard-cause-widget-rebuilds-on-open-close
