### ISSUE TITLE
flutter_gallery tabs_demo.dart: have problem when the tabs' num exceed 2.

### ISSUE THREAD

**Issue by marekchen** [flutter/flutter#18832]
I just add a _Page to _allPages(line 27) base on flutter_gallery's tabs_demo.dart.
See https://gist.github.com/marekchen/2adf5d03e845e9fe69ffdbc74533eba4
## Steps to Reproduce
1. run https://gist.github.com/marekchen/2adf5d03e845e9fe69ffdbc74533eba4

problem 1:

1. click the third tab
2. scroll up list(third tab)
3. click the second tab, found that this list also scroll up

problem 2:(restart this page before do the following) 

1. scroll up list(first tab) 
2. click the second tab
3. scroll down list(second tab) 
4. click the first tab, found that the first tab restored to it's original

## Logs
no logs

```
[√] Flutter (Channel master, v0.5.6-pre.39, on Microsoft Windows [Version 10.0.17134.112], locale zh-CN)
    • Flutter version 0.5.6-pre.39 at C:\develope\flutter\flutter
    • Framework revision a18f5e84a1 (6 days ago), 2018-06-20 20:23:51 -0400
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Android\Android-Studio3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 2.3)
    • Android Studio at C:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.1)
    • Android Studio at C:\Android\Android-Studio3
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[√] Connected devices (1 available)
    • ONEPLUS A6000 • 5e5530a6 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by marekchen** [comment]
cc @Hixie

**Comment by marekchen** [comment]
@Hixie can you reproduce this issue?

**Comment by dnfield** [comment]
I believe this has to do with using identical `const` lists...  If you change your pages up a bit the scrolling isn't maintained between the two pages.

**Comment by marekchen** [comment]
@dnfield how to change? I found the second tab's posiotion stored in PageStorage will change when the third tab's list scroll.

**Comment by marekchen** [comment]
This issue blocking me,I can't use SliverAppbar with TabBarView include more than 2 [CustomScrollView]s.
Using debug,I found the cause of this issue is lib/src/widget/scrool_controller.dart line.178 & line.188.
After click the last tab, the _postions contain 2 position(index2 and index1 's position)

**Comment by dnfield** [comment]
It's not related to the list contents being identical.  I'll look into it.

**Comment by dnfield** [comment]
If you specify a `controller` for each `CustomScrollView`, the problem goes away:

```
                    return new CustomScrollView(
                      key: new PageStorageKey<_Page>(page),
                      controller: new ScrollController(),
                      slivers: <Widget>[
```

**Comment by zoechi** [comment]
I think
```dart
key: new PageStorageKey<_Page>(page),
```
should be changed to for example
```
key: new PageStorageKey<String>(page.label),
```

> /// [PageStorageKey]s for the widget and its ancestors. To make it possible
> /// for a saved value to be found when a widget is recreated, the key's values
> /// must not be objects whose identity will change each time the widget is created.
> 

but that still doesn't fix the issue

**Comment by marekchen** [comment]
@dnfield It doesn't work.The SliverAppbar don't scroll if I  specify a specific ScrollController passed to the ScrollView.

**Comment by dnfield** [comment]
So here's something strange - I can reproduce this on an emulator but not on a real device.  Are you seeing this behavior on a real device, or just on the emulator?

**Comment by marekchen** [comment]
real device（OnePlus 6）

**Comment by eturk1** [comment]
In #21574 I posted a simplest one-file demo to see the issue using a ListView.

I tried adding `controller: new ScrollController(),` to each `ListView.builder()` construct. Though I do get three separate controller ids, rather than "using primary controller", they still share the same scroll position. 


Note: My actually code is using three lists with ExpandableTiles, and the same tile indexes get expanded on every tab. (i.e. expand [3] on one view & all [3]s are expanded.) It seems this is more than just a scrolling issue?

**Comment by eturk1** [comment]
Note that in my simple ListView / BottomNavigationBar example, the sync'd scrolling is still a problem with only 2 tabs. (just comment out one of the BottomNavigationBarItem to see it is not just over 2 tabs)

**Comment by eturk1** [comment]
@marekchen, @dnfield, @zoechi 
Ideas on how to get the tab views to scroll independently & not share item state?

**Comment by eturk1** [comment]
@marekchen is your scrolling issue fixed?
I just tried your example for the first time, to test it after fixing mine, and it seems each tab scrolls independently.
I'm on `Flutter 0.10.2-pre.74 • channel master`

I figured out my own issue was just coding. Needed a separate _key_ for each List because they had the same BuildContext. My scroll issue is solved.

**Comment by eturk1** [comment]
Oops, I think I spoke to soon. Had to leave the project right after thinking it was fixed. Returned and it's still there. Still used same offset for all lists.

**Comment by abdalmonem** [comment]
same issue , i spend 3 days on search and there is no solve

**Comment by lab-nit-s** [comment]
Any resolution to this issue ??

**Comment by abdalmonem** [comment]
@lab-nit-s 
after spend a lot of time to solve it , i found a good way to deal with this issue : 
[https://stackoverflow.com/questions/54689594/flutter-tabsview-and-nestedscrollview-scroll-issue/54696347#54696347](https://stackoverflow.com/questions/54689594/flutter-tabsview-and-nestedscrollview-scroll-issue/54696347#54696347)
its not the best way , but you can try to improve it (if you do , please share us )

**Comment by camhunt137** [comment]
@marekchen did you have any luck in the end? This issue is currently blocking me as I am trying to incorporate 3 tabs within the NestedScrollView, with a SliverAppbar. 

Briefly I have some large page titles that I would like to collapse to a truncated version on scrolling. I have a minimal example that I can provide, but it is nothing special. 

I will go with a static AppBar for now, without having to use the NestedScrollView but I would be keen to know when/how this gets resolved.

**Comment by dnfield** [comment]
I think @chunhtai is working on this.

**Comment by chunhtai** [comment]
After some investigation. There are three things that stood out
1. regarding problem 1 in original post. When you go to tab3, for some reason tab2 is not getting disposed. This is probably related to double precision error. Something like when viewport should be in 300 pixel that only display tab3, but it is actually 299.9999999999998 that the layout think tab2 is still require. This is definitely a bug we should fix

2, regarding to problem 2, that behavior is by design. In order to keep scroll offset for every tab, we store it in pageStorage. There is a code in https://github.com/flutter/flutter/blob/8bea3fb2ebadc3933b6b213483d2d4379ac53a5c/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L957
that prevent it from restore when the sliveroverlap extent is still on screen. This problem is more like what would you expect the correct behavior should be.

3, although problem 1 can be solved. It surface another issue. We will still see the same behavior if one of the tab is keepalive. Even it is scroll out of view, it will not be disposed. The scroll will still affect those tabs. Currently we do not have a way to solve this.

Here concluded my investigation. I would like to hear some feedback from (2)

**Comment by eturk1** [comment]
@chunhtai
This issue hasn't been solved. Try my simply coffee from #21574

Tabs fail when we have more than one year with the same class for a list.

**Comment by chunhtai** [comment]
Hi @eturk1 , I replied to the #21574

This issue has been closed due to inactivated, I should keep it open.

As my comment above https://github.com/flutter/flutter/issues/18832#issuecomment-482354735.

(1) should be fixed with https://github.com/flutter/flutter/pull/30979

I will need some clarification on (2), and come up with a way to fix (3)

**Comment by goderbauer** [comment]
Dup of https://github.com/flutter/flutter/issues/40740.
