### ISSUE TITLE
When add an IconButton widget to CustomMultiLayout, the Ink effect of the IconButton is gone

### ISSUE THREAD

**Issue by mengless** [flutter/flutter#18874]
## My code

```dart
new LayoutId(
            id: SendPanelLayoutDelegate.AddICBtn,
            child: new IconButton(
              icon: const Icon(Icons.add),
              iconSize: 54.0,
              onPressed: () {
                _newMessage(context);
              },
            ),
          ),
```
There is no Ink effect when press the IconButton.  But the others buttons like FlatButton is all right.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
Please let us know if you're still seeing this problem.

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
