### ISSUE TITLE
mac: "flutter run" doesn't say how to obtain "ideviceinstaller" or "ios-deploy" if you don't have homebrew.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1890]
This is a problem because we don't claim homebrew to be a dependency.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/1907 would make this moot.

**Comment by eseidelGoogle** [comment]
What is `flutter start`?  Is this still a valid issue?

**Comment by snksoft** [comment]
> This is a problem because we don't claim homebrew to be a dependency.

No, it's an problem because Homebrew is notorious for breaking things (in fact, you even have few issues open in this project where homebrew is to blame). And there are plenty of people avoiding homebrew for that reason. It's fine if you installing things you're developing or if it is a pre-release product (as you would expect some hiccups at this stage), but it's annoying at best if you only using this project to develop something of your own.

If you absolutely must support homebrew, you should still provide alternative ways to install required tools using alternative methods such as MacPorts or just manually installing these tools (even if just as an instruction). I also think Nodejs/npm or SDKMAN could be even better alternatives as they were designed to support multiple environments on the same machine in a non-conflicting way, so they don't conflict with other package managers one might use. But the main point is - keep the choice open. I, for one, like flutter project. But if the only way to use it requires wrecking my dev environment (including all other projects I work on). Then it is simply not an option.

**Comment by eseidelGoogle** [comment]
I don't believe we have any reason to attach ourselves to homebrew other than it was the easiest way we found to install these dependencies.

If you or others wish to suggest alternative ways to get these dependencies, or write PRs to flutter_tools to teach "doctor" how to help others get them, that'd be awesome:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools

**Comment by jonahwilliams** [comment]
We need to revist shipping these tools with our default artifacts. The homebrew installation process is bad, especially with all the work arounds need to support the latest of each tool.

**Comment by christopherfujino** [comment]
Closed in [36093](https://github.com/flutter/flutter/pull/36093).
