### ISSUE TITLE
Provide an option for stripping a JIT snapshot of debug information

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#18928]
Per discussion with @chinmaygarde , it would be nice if there were a variant of `flutter build bundle` to build a JIT snapshot that didn't have all the debug information (or alternately, a post-processing command to strip the debug info from a snapshot), since that could likely be used as a simple Release mode for desktop (where AOT might well not be necessary to get reasonable performance).

**Comment by kf6gpe** [comment]
@a-siva @stuartmorgan Is this still necessary?

**Comment by stuartmorgan** [comment]
We're leaning toward supporting AOT on desktop in which case it wouldn't be, but there hasn't been a performance comparison on desktop to see what the tradeoffs for JIT vs AOT are.

**Comment by chinmaygarde** [comment]
I am having trouble recalling the specifics of this conversation. But, I think what I mentioned was that the kernel file may not have been configured optimally for a mode in which JIT is used in the released application. This is because JIT is only used on the mobile shells in debug mode. Specifically, this is the addition of the `-Ddart.vm.product=true` to the frontend server invocation. This conversation also took place while not discussing anything Fuchsia specific (if anything, it was Desktop related). So I think the `customer:fuchsia` tag is unwarranted. I am removing the same.

**Comment by stuartmorgan** [comment]
> it was Desktop related

Yes, this was definitely about the desktop shells.

**Comment by jonahwilliams** [comment]
FWIW: the produce defines do not work in JIT mode either because of how constants are evaluated in the vm versus in the aot runtime.

**Comment by chinmaygarde** [comment]
In that case, is there anything to do w.r.t this issue? We should close this.

**Comment by stuartmorgan** [comment]
I'm fine with closing this for now, and revisiting if plans for Release change.
