### ISSUE TITLE
Is there a DocumentPicker?

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#18965]
I could not find this in the docs. Is there an official way on how to pick documents? I'm converting my app to Flutter and need a way to select one or more PDF files from the IOS/Android system. What I need is an [ImagePicker](https://pub.dartlang.org/packages/image_picker) equivalent for documents.

**Comment by salihgueler** [comment]
Have you tried [this plugin?](https://pub.dartlang.org/packages/documents_picker) I tried that and it looks like the thing you want.

**Comment by AndreHaueisen** [comment]
@salihgueler , I have but it is still a very early version, and there is no guarantee the author is gonna keep going. I'm not an IOS developer so my help on plugins are very limited. Flutter is not in beta anymore. I think this is a basic functionality and was hoping that this had already been solved by now.

**Comment by salihgueler** [comment]
@AndreHaueisen Yes, on that you are right. From my perspective, since in Android we would be needing permission dialogs and stuff (don't know how it's on iOS either), I think file picking would be handled on the native side of the code. I also read [this](https://flutter.io/cookbook/persistence/reading-writing-files/) but it's also not helping in your case.

**Comment by stuartmorgan** [comment]
This is covered by `file_selector`; marking as a dup of https://github.com/flutter/flutter/issues/110098 which tracks adding Android support.
