### ISSUE TITLE
flutter run "o" doesn't switch gallery OS setting any more

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19023]

**Comment by Hixie** [comment]
cc @HansMuller maybe this broke in the recent redesign?

**Comment by darrenaustin** [comment]
This is due to the fact that the gallery has its own platform setting in the Settings UI that overrides the `defaultTargetPlatform`. Changes to `defaultTargetPlatform` after initialization will be ignored in favor of the gallery's platform setting from the UI.

Given that the Gallery provides its own way to change the platform, I'm going to close this. If you feel strongly that we should make this work from the runner, please reopen and we'll take another look.

**Comment by Hixie** [comment]
I guess it's ok not to fix it, but for what it's worth the original design had carefully set this up so that it would continue working. My bad for not writing a test to verify it though.
