### ISSUE TITLE
Add automatic increment of notification badge on app icon in firebase_messagingg

### ISSUE THREAD

**Issue by bigboateng** [flutter/flutter#19033]
Currently, the server has to send the exact number using the API (nodejs, etc), but allow auto increment so we don't have to keep track of unread notification in the backend. i.e whenever theres a new notification, the number increments by 1.

![image](https://user-images.githubusercontent.com/10779355/42211691-027e4694-7e69-11e8-8c69-b3a1ab385832.png)

**Comment by slightfoot** [comment]
If this is integrated into the firebase package; I think we need to consider the API. For instance, there should be a specific `enableBadge` and a `clearBadge` function.

If its going to be enabled on iOS then I think the same should be done with Android. But this is fraught with complications, especially if it is to support the manufacturer specific badge options. See https://github.com/leolin310148/ShortcutBadger

I just spotted this in that repo: "Remove Android Launcher support due to Google Play Developer Term Violation since 4.4.". So I wonder even if Android apps can support the badge feature on the Android Launcher's.

**Comment by rajeshzmoke** [comment]
is there any update with this issue?

**Comment by ghenry** [comment]
Yes please.

**Comment by kroikie** [comment]
@bigboateng

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/768. Any further collaboration will be done there.
