### ISSUE TITLE
'flutter start' should run pub get, or prompt you to do so, if it hasn't been run for your app

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1904]
Clone the flutter git repo anew, or do a hard git clean, and then try running "flutter start" in "flutter/examples/stocks". You get:
```
Cannot locate the sky_engine package; did you include 'flutter' in your pubspec.yaml file?
```

- [ ] The problem is that you haven't yet run `pub get`. We can determine that easily by checking the pubspec.lock file -- it's not there (or is older than the pubspec.yaml).

- [ ] We should definitely not ask if you've added "flutter" to the pubspec.yaml since we can trivially verify this for ourselves. Either you have or you haven't; if you haven't, we should say explicitly "this package does not depend on 'flutter'. If it is a flutter application, then..." and explain how to add the dependency (we can even figure out the exact path for you right there).

**Comment by eseidelGoogle** [comment]
I get a slightly different message, adding here for searchability:
`Error: incompatible sky_engine package; please run 'pub get' to get the correct one.`

I feel like this is by far the most common error I get with the flutter tool.  Probably because I surf flutter HEAD and often have stale pub gets in my examples folders.
