### ISSUE TITLE
[camera] Support for Android API 16+ 

### ISSUE THREAD

**Issue by dalewking** [flutter/flutter#19083]
The camera plugin needs to work for all versions of Android that support flutter, i.e. 16 and above.

**Comment by amirh** [comment]
Marking this as a feature request. The current plugin relies on the camera2 API which is only available starting API 21. Supporting the previous API will involve re-implementing most of the Android code.

**Comment by p30arena** [comment]
@bparrishMines @amirh 
Is it feasible to use a library in the plugin?
https://github.com/natario1/CameraView
This library supports minSdkVersion 15

**Comment by guominfang** [comment]
It's been five years since Android 21 was released in 2014. Maybe Android 21 will be obsolete next year or the year after, so I think Camera Plugin only needs to support Android 21+, which will greatly reduce the work of adapting the Camera Plugin to the old version and allow more time to adapt the new version of Android.

**Comment by gmackall** [comment]
Closing this, as in the time since the issue was made Flutter has increased the lower bound of its supported Android versions to 21, which aligns with the min sdk requires for the current `camera_android` plugin.
https://docs.flutter.dev/reference/supported-platforms
