### ISSUE TITLE
Flutter Firebase?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19153]
Hey everyone,

Is Firebase ready for production use with Flutter? I cannot find any good documentation on Firebase use for Flutter. I will admit that I am kind of here because I use and love Firebase and it sounded like Google was pushing this combo pretty hard. I'm looking at the various FlutterFire plugins and many of them are in alpha?

**Comment by lukepighetti** [comment]
https://github.com/flutter/plugins/blob/master/packages/firebase_database/example/lib/main.dart#L15

I cannot find any documentation on what "name" is. I have tried project name, public-facing-name, project-id,  app nickname, bundle-id and I still get this error. 

```
5.4.0 - [Firebase/Core][I-COR000004] App with name test-project-838334 does not exist.
```

**Comment by zoechi** [comment]
> I cannot find any good documentation on Firebase use for Flutter.

Documentation could be better but most things are quite similar to how it would be done in Android.

> many of them are in alpha?

Flutter itself is still only beta. Much work is still going on but many use it in production already.

Did you search your config files for `test-project-838334`?
I guess it's the name from the Firebase console.

**Comment by lukepighetti** [comment]
I'm not an Android developer.

**Comment by lukef** [comment]
If firebase is critical to your application then, in my opinion, you should *not* use the firebase plugins. They're consistently out of date and you will have issues if you need to utilize firebase in native code in addition to flutter. I am sure the situation will change in the future but, having built a few large apps on firebase now, I wouldn't recommend the plugins currently.

That said, It depends on how much effort you need to put into building your own logic to talk to firebase (across 2 platforms) and how much you really need to do anything that isn't "vanilla". 

You could also fork the firebase plugins to make them work consistently which is what I'm doing now.

**Comment by lukepighetti** [comment]
Dang. That's pretty clear then, @lukef . I hope the team will prioritize Flutter Firebase packages that are just as production ready as the Javascript firebase packages, especially since "build with Firebase & Flutter" is a huge part of Google's messaging on Flutter.

**Comment by lukef** [comment]
A quick clarification - the plugins themselves are fairly simple wrappers over the **production ready** iOS + Android libraries so it *is* production ready when it is up and running. All it is doing is what you would be doing yourself.

The dependency management issues are what I was referring to. The best way to resolve that is to log issues / PRs with the team. I do know there are some PRs outstanding but I'm not sure what the hold up is on those because they're already partly outdated now. I also know for a fact that it's nearly impossible to update to the latest versions of the plugins and not have one or more plugin create a dependency issue at the moment. It is getting better but slowly.

I would still recommend that, *IF* your app is simple enough, you could copy + paste the code directly or you can wrap the parts you need. I'm guessing that in the long run it's not terribly difficult to swap out later, just time consuming. Or, you can use the plugins and deal with the conflicts every 1-3 months like me :)

**Comment by lukepighetti** [comment]
Thanks for the clarification. I am a little confused why we don't use a Dart library instead of the iOS/Android libraries. It is my understanding that we use the Javascript libraries when developing React-Native apps.

Unfortunately I have no experience with native app development to know how to build and debug these native to flutter wrappers...

So what are your words of wisdom for someone like me who uses Firebase for everything and is looking to use Flutter for everything mobile?

**Comment by zoechi** [comment]
Unfortunately there is no Dart Firebase implementation. 
The non-Flutter version is for the browser only and is also a wrapper of Firebase JS libs.
The Dart console app Firebase lib only supports the limited REST API.
A pure Dart implementation for all platforms would be great though.

**Comment by lukepighetti** [comment]
@lukef whenever I get a snapshot from Firebase the results are not in order. In my experience on JS they are always in order based on id unless you explicitly sort them otherwise. Am I missing something?

**Comment by lukef** [comment]
@lukepighetti - this is probably better to ask on stackoverflow than here but ..
The result returned from the plugin is a Map so the keys will be not be in sorted order. You can, however do a sort on the key set so that they are ordered. Otherwise, you can add a timestamp to the data records and sort that way. I added this to the other issue also.

**Comment by lukef** [comment]
I think this issue can probably be closed?

**Comment by irwinOT** [comment]
and then? .... what is "name"?

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/760. Any further collaboration will be done there.
