### ISSUE TITLE
Pubspec error running app from Atom

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#1916]
My environment: Atom v1.4.3, dartlang 0.6.0, flutter plugin 0.1.3.

I opened the Firechat Flutter app project in Atom.

When I try running any of the steps with Command+R from Atom, it shows this error: "No pubspec.yaml file found. This command should be run from the root of your Flutter project. Do no run this command from the root of your git clone." The pubspec.yaml is already there in the project directory.

Running from the terminal with 'flutter start' works correctly.

**Comment by devoncarew** [comment]
Looks like the issue here was that there was a pubspec.lock and a .packages file in the parent directory (but strangely, no corresponding pubspec.yaml). This was confusing atom when it was trying to determine the best cwd to launch with.

Will close this out, and investigate the ~related issue of why the launch config files are created at the parent dir, and not the project dir.
