### ISSUE TITLE
There is some trouble when I use dialog with snackBar

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#19246]
I want to use an AlertDialog to show a SnackBar in my app,but when I click the button there always show this:
```
flutter: The following assertion was thrown while handling a gesture:
flutter: Scaffold.of() called with a context that does not contain a Scaffold.
flutter: No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This
flutter: usually happens when the context provided is from the same StatefulWidget as that whose build
flutter: function actually creates the Scaffold widget being sought.
flutter: There are several ways to avoid this problem. The simplest is to use a Builder to get a context that
flutter: is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
flutter:   https://docs.flutter.io/flutter/material/Scaffold/of.html
flutter: A more efficient solution is to split your build function into several widgets. This introduces a
flutter: new context from which you can obtain the Scaffold. In this solution, you would have an outer widget
flutter: that creates the Scaffold populated by instances of your new inner widgets, and then in these inner
flutter: widgets you would use Scaffold.of().
flutter: A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the
flutter: key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
flutter: The context used was:
flutter:   DemoText(state: DemoTextState#2041b)
```
And there is my codes:
```
showDialog(
                context: context,
                builder: (ctx) => AlertDialog(
                      title: Text("Title"),
                      content: Text("Content"),
                      actions: <Widget>[
                        FlatButton(
                          onPressed: () {
                            Scaffold.of(context).showSnackBar(
                                SnackBar(content: Text("23333333")));
                          },
                          child: Text("ok"),
                        )
                      ],
                    ),
              );
```
So what should I do?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`.

**Comment by zoechi** [comment]
The AlertDialog is not a child of `Scaffold` and therefore no Scaffold can be found using the current context.
You could use a GlobalKey to get a reference to the Scaffold.

**Comment by hahafather007** [comment]
I will try it,thanks.Em,I'm just a rookie

**Comment by hahafather007** [comment]
Thank you so much,I have already done it.
I replaced
```
Scaffold.of(context).showSnackBar(SnackBar(content: Text("23333333")));
```
to
```
(_snackKey.currentState as ScaffoldState).showSnackBar(SnackBar(content: Text("2233333")));
```
and then,it works!

**Comment by zoechi** [comment]
If you use `GlobalKey<ScaffoldState>` you shouldn't need `(... as ScaffoldState)`

**Comment by patelkrunal78** [comment]
This exception happens because you are using the context of the widget that instantiated Scaffold. Not the context of a child of Scaffold.

You can solve this by just using a different context :
Find more At Here https://icetutor.com/question/scaffold-of-called-with-a-context-that-does-not-contain-a-scaffold

**Comment by patelkrunal78** [comment]
There’s three problems. The first is that you don’t have a Scaffold anywhere, and the Scaffold widget is the one that knows how to show snack bars. The second is that you have a key for getting a hold of the scaffold, but you’ve put it on a Padding instead (and Paddings don’t have any knowledge of snack bars). The third is that you’ve used the key before the widget that it’s associated with has had a chance to be initialised, since initState is called before build.

https://icetutor.com/question/display-snackbar-in-flutter
