### ISSUE TITLE
Using a live camera view with ML Kit plugin

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#19274]
Currently, the main priority right now is to get all the Detector logic working with an image file. However, the next obvious step for the plugin would have it working with a live camera view.

**Comment by dustin-graham** [comment]
@bparrishMines could you please assign me? I'm working on this. 

A few questions though:
1. Does the implementation need to be in Java and Objective-C? It looks like all the other code is, is this a standard?
2. For Android, since we are targeting API 16+, should I worry about the camera2 API? The legacy camera API is deprecated but it works everywhere, does what we need it to do, and will work on all the supported versions. The camera2 API has some oddities such as the ability to turn the flash on/off was only made available in 23, but camera2 was introduced in 21. I could make both implementations and switch based on available version, but that would add complexity. Preference?

**Comment by bparrishMines** [comment]
cc @kroikie 

1. Yes, the implementations will have to be in Java and Objective-C. We do this so a user wouldn't have to download swift and/or kotlin to use the plugin.

2. It depends on what your up for and what you need for your app. In my opinion, it's always easier to start with the simpler solution, then expand to a complex solution. The plugin is still in alpha, so the deprecated camera solution should be fine for now.

**Comment by dustin-graham** [comment]
@bparrishMines I've got a partial implementation working for the text detector on iOS. It only works when the preview video shows in landscape though. Is there a resource on your end I could ask some questions about iOS MLKit? I feel like the issue is a cross section between iOS MLKit and Flutter native textures. Basically: If I rotate the preview, the detector stops working.

![live_text_detector_small](https://user-images.githubusercontent.com/959931/42665689-aaf98976-85f5-11e8-89e8-2f45b0367567.gif)

**Comment by bparrishMines** [comment]
@kroikie Do you know anything about this?

Also, @dustin-graham, could you create the PR and reference this issue so we could take a look at the code.

**Comment by dustin-graham** [comment]
I'll work on getting that to you today.

**Comment by j0nscalet** [comment]
Hey guys... I've been working on this a bit too, more further along in iOS than Android. 

@dustin-graham definitely interested in looking at the PR.

@bparrishMines if I can help in any way with this, please let me know.

Thanks guys!

**Comment by dustin-graham** [comment]
I'm on vacation today. I can probably push codes sometime tomorrow. I'm in
process of swapping out Android camera2 for the legacy camera API.

On Jul 17, 2018 1:54 PM, "Jon Scalet" <notifications@github.com> wrote:

Hey guys... I've been working on this a bit too, more further along in iOS
than Android.

@dustin-graham <https://github.com/dustin-graham> definitely interested in
looking at the PR.

@bparrishMines <https://github.com/bparrishMines> if I can help in any way
with this, please let me know.

Thanks guys!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/19274#issuecomment-405724078>,
or mute the thread

**Comment by j0nscalet** [comment]
@dustin-graham Thanks for the update. Enjoy the rest of your vacation. 😄

**Comment by bparrishMines** [comment]
@dustin-graham I just took a look at the [camera](https://pub.dartlang.org/packages/camera) plugin for Flutter and it seems like it has a minimum sdk of 21 for Android anyways. I hadn't realized that before. 

Depending on how far you are, you could use camera2 to make the camera plugin easier to reference from.

**Comment by bparrishMines** [comment]
@j0nscalet It depends if @dustin-graham is/has already implemented the iOS side of the live camera view with the detectors.

**Comment by j0nscalet** [comment]
@bparrishMines  Sounds good, let's see where @dustin-graham  is at when he's back from vacation.

**Comment by dustin-graham** [comment]
My vacation got extended more than expected but I have been able to make
some progress. I have working implementations for both camera2 and camera1
so far. Once I push up my PR we can take a look and decide where we want to
take it. We could stick with camera1 and keep the low SDK min or we could
make it dynamic. I don't think the camera2 API gives us anything. so long
as we're comfortable using a deprecated API I'd say we go with camera1, I'd
push my code right now but some of my changes done for he Android impl
broke the iOS version and so I'm working that up today.

**Comment by dustin-graham** [comment]
@bparrishMines and @j0nscalet PR is up: https://github.com/flutter/plugins/pull/679

Still a few things to do, some of which will require some external input. Please check it out and let me know what you think.

**Comment by j0nscalet** [comment]
Thanks @dustin-graham. Will do. :)

**Comment by dustin-graham** [comment]
@bparrishMines and @kroikie, I've got an initial PR up but I'm stuck struggling with a couple outstanding bugs. If either of you get a chance to review the PR and provide insight on the issues noted there I would appreciate it. Essentially the big issues are:

1. iOS: displaying the camera preview in upright portrait mode causes the detector to misbehave. I think this is an interesting combination of how the flutter backend textures work and how the MLKit recognizer works.
2. Android detected regions are not translating correctly on the live view. need a second pair of eyes on this to help me spot the trouble.
3. the flutter_plugin_tools don't work for me locally the same way they do on CI which is making it hard to pass validation. Need a little bit of help on setting this up on my end.

any time you could spare would be greatly appreciated.

**Comment by dustin-graham** [comment]
@bparrishMines I appreciate you getting back to me. I've taken a bit of time to try and document and demonstrate the issues I'm seeing. I love the idea of getting the camera plugin cooperating with other plugins. I thought of that at the outset of this effort but that seemed a bit more obscure than this direct approach. perhaps I'll look into it during the balance of today. My project is time-dependent, but I always strive to find the best solution. I don't have any qualms about taking this a different direction. But so far, here's where I'm stuck:

## iOS issue
The main issue I'm facing with iOS has to do with correctly presenting the camera preview at the same while the MLKit detector is working.

### Making the preview image presented upright breaks the detector
In order to present the camera preview correctly in Flutter, steps must be taken while configuring the camera inputs and outputs.
An `AVCaptureConnection` is used to rotate the preview frame so that it can be oriented correctly for Flutter.

For example, the following code will configure the camera preview to show in portrait mode.
```
AVCaptureConnection *connection =
    [AVCaptureConnection connectionWithInputPorts:self->_captureVideoInput.ports
                                           output:self->_captureVideoOutput];
connection.videoOrientation = AVCaptureVideoOrientationPortrait;
if ([self->_captureDevice position] == AVCaptureDevicePositionFront) {
  connection.videoMirrored = YES;
}
[self->_captureSession addInputWithNoConnections:self->_captureVideoInput];
[self->_captureSession addConnection:connection];
```
Note the line: `connection.videoOrientation = AVCaptureVideoOrientationPortrait;`

I picked up this technique from the camera plugin. This does not appear in the iOS MLKit quickstart project.

![screen shot 2018-07-26 at 1 02 04 pm](https://user-images.githubusercontent.com/959931/43287531-29e9803a-90da-11e8-9d39-effe2aeab24b.png)

_Observe that the TextDetector does not pick up any text blocks._

If this line is omitted, the camera preview shows incorrectly, but the TextDetector does it's work successfully. In the iOS MLKit quickstart project, the rotation of the camera is handled at the UI layer, not at the AV input/output layer. But since we are just passing texture ID's around, there are no UIViews to rotate. This is how it's different for a native app vs our Flutter environment.

![screen shot 2018-07-26 at 1 04 19 pm](https://user-images.githubusercontent.com/959931/43287614-63925ca8-90da-11e8-89d5-f898bcd370ee.png)

My guess is that the consequence of the rotated `AVCaptureConnection` configuration causes the actual image sent to MLKit to be distored such that it doesn't pick up any text. If this is true, the solution is either:

  1. Find another way to present the preview image in the correct orientation to Flutter
  2. Find a way to pass the rotated preview image in a way that MLKit can read it.

Additionlly, when the preview image is shown in Flutter it does appear a bit distorted. See the image below. The objects in the image are more squished vertically than they are in real life. I don't know yet if this is because of a Layout error I've introduced in my dart code or if the preview image is being distored at the source somehow.

![connection_portrait](https://user-images.githubusercontent.com/959931/43287637-73f2c0a6-90da-11e8-8ec6-a10aaefb1e49.png)

## Android issue
The main issue I'm facing with Android is that the detection boundaries for the live view do not seem to be translating correctly from detection into Flutter. The same code is used to detect images from files, so the problem should probably be found somewhere between how the preview image is sent to MLKit.

![android_detection_boundaries_off](https://user-images.githubusercontent.com/959931/43287659-822e6350-90da-11e8-9194-4559f91b4997.png)

## What I need
I could use some extra eyes on the code. I'm continuing to try different things and to check and re-check inputs and outputs, but I could use a few new ideas.

**Comment by dustin-graham** [comment]
@bparrishMines I've also tried to keep my branch up-to-date with the upstream. It should function with all the added detectors that are now in `master`. I had to change the way the detectors pass back their results since we are dealing with `Method.Result` and `EventChannel.EventSink` methods of communication. So the Detectors operate with a callback and the caller can flow the results to whatever channel mechanism is required to send data to Flutter. 

Also, the flutter_plugin_tools are working for me now, thanks for the guidance there!

**Comment by dustin-graham** [comment]
@bparrishMines spent a few hours today trying to put together a proof-of-concept for the native side of one plugin communicating with the native side of another plugin. I haven't been able to figure out how to make the build work yet. Are there any reference projects that you all have that can demonstrate this technique? I've been looking through the other plugins and I haven't found anything yet. Each plugin basically sits in it's own silo, not cooperating directly with any other plugin. I haven't pursued seeing if Dart can shuttle frame data between libraries yet. I'm a little worried that passing data along a channel will be too slow and expensive to be practical. If you have any additional details on how this might be done, I'd love to investigate. Thanks

**Comment by dustin-graham** [comment]
@bparrishMines I put together a prototype tonight of utilizing the `camera` plugin for the preview. See here: https://github.com/flutter/plugins/pull/688

**Comment by lewixlabs** [comment]
@dustin-graham i hope i'm not off-topic, if so, sorry!

Have you experiencing this issue like me? Text detection works in landscape mode only.
I noticed this happens with my Samsung (S8) only, not with my Nexus 6.
This is my post:
https://github.com/flutter/flutter/issues/19000

Thank you!

Lewix

**Comment by dustin-graham** [comment]
I have had this problem as well.

**Comment by AlexBacich** [comment]
Same problem here. There is a possibility to rotate image and scan it with MLKit again, but it takes extra seconds.

**Comment by YamanSehzade** [comment]
Hi  @dustin-graham @AlexBacich , I have same issue. Do you have any solution?

**Comment by allanwolski** [comment]
any updates on this?

**Comment by killermonk** [comment]
I'm wondering if a different approach to this makes sense. The camera plugin creates a texture and returns the Texture Id to the dart code. Might it possibly make sense to just use this Texture Id to communicate between the two plugins?

Instead of using detector.detectInImage with FirebaseVisionImage.fromBytes, create a new method like detector.streamFromCamera that takes the camera and uses the texture on the platform-side to stream back results.

This might prevent the discussed performance issues of having to continuously stream back all the bytes from the image to the dart code, then stream them back to the platform for the detector. Keeping all the image data platform-side, then streaming back the detection results instead, could probably speed things up greatly.

It creates a tightly-coupled link between the two plugins, but if it makes sense, then it makes sense.

Would this approach even be feasible?

**Comment by killermonk** [comment]
It appears that @dustin-graham has already run with this idea in flutter/plugins#688

**Comment by dustin-graham** [comment]
@killermonk I meant to reply earlier today, but yes, I did get a working prototype getting camera and mlkit to talk to each other directly on the native side. It took a good amount of work to do, and I'm still very interested in pursuing it. However, I held off because I wanted to be sure that it was the direction the flutter team wanted to take it before I sunk a lot of additional time into it. Even though the PR is now closed, I still think that the Flutter plugin system should have a first class way for plugins to communicate with each other directly without having to incur the cost of a Dart mediator and I'd love to contribute to that effort if I can.

@bparrishMines any update about possibly getting the camera built into the framework as a possible solution for this as you suggested earlier?

**Comment by bparrishMines** [comment]
@killermonk I believe a couple of us looked into using a shared texture initially, however ML Kit on Android requires an `Image`, `ByteBuffer`, or `byte[]`. This essentially requires you to use an `ImageReader` to get camera images. Without a way to convert `Image` to a SurfaceTexture, I think it made this path a non-starter. As for @dustin-graham implementation. It was good however I wanted a solution that 1) Keeps modularity of plugins and 2) not require adding code outside of the dart portion of an app. 

In the long run, we want to add a universal way for plugins to communicate directly. This would solve performance with streaming images, along with other features like audio. This will require changes to [flutter/engine](https://github.com/flutter/engine) and we currently don't have anyone with the time to work on it at this moment.

**Comment by bparrishMines** [comment]
**Current State of This Issue**

The main implementation of this is done. With an [example](https://github.com/bparrishMines/mlkit_demo) project that is used to test live view with ML Kit on different devices.

However, there is still one limitation in the [camera plugin](https://github.com/flutter/plugins/tree/master/packages/camera) that are needed to complete this. 
* Access to the rotation of the physical camera. This would help the implementation work with landscape mode and various devices with less common camera rotation, such as tablets.

**Comment by athornz** [comment]
The orientation issue is definitely a blocker.

**Comment by jaumard** [comment]
Why not using this for now https://pub.dartlang.org/packages/native_device_orientation ? Not sure is relevant as I didn't test yet your example but look like what you need is done by this package @bparrishMines

**Comment by rmtmckenzie** [comment]
Well the native device orientation plugin doesn't give access to the rotation of the camera in respect to the device, but it does give the rotation of the device's window in relation to the device. I don't know whether that will help or not.

**Comment by andaas4** [comment]
Looks like the camera plugin now has support for "sensorOrientation".
https://github.com/flutter/plugins/commit/87e2bdce70cda9e55f2176b9da0b73812864d550#diff-32bf6b6597dea420f832a0e446c8a708

**Comment by kroikie** [comment]
@bparrishMines

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/757. Any further collaboration will be done there.
