### ISSUE TITLE
Soft keyboard animation unsynchronized with Flutter resize animation

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19279]
Internal: b/144470661

[ScreenRecording_07-11-2018 16-36-08.MP4.zip](https://github.com/flutter/flutter/files/2186126/ScreenRecording_07-11-2018.16-36-08.MP4.zip)

https://user-images.githubusercontent.com/666539/138469374-f8e0748b-64aa-4454-be88-ac7096c2b5bd.MP4

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
Are you still seeing this?

Can you please provide a minimal reproduction?

**Comment by lukepighetti** [comment]
Hi Zoechi, yes, this issue still exists.

```
[✓] Flutter (Channel dev, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.0.0 at /Users/lukepighetti/flutter
    • Framework revision 5391447fae (6 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

### Expected
![expected](https://user-images.githubusercontent.com/666539/49527039-144e2200-f87f-11e8-867f-daf84260bff2.gif)


### Actual

![actual](https://user-images.githubusercontent.com/666539/49527057-1dd78a00-f87f-11e8-857a-fdaa594e40f0.gif)


### MCVE

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: ListView(
              children: List.generate(100, (i) => ListItem(i)),
            ),
          ),
          Container(color: Colors.grey.shade400, child: TextField())
        ],
      ),
    );
  }
}

class ListItem extends StatelessWidget {
  final int i;
  ListItem(this.i);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 24.0,
      child: Text(i.toString()),
    );
  }
}

```

**Comment by filipinascimento** [comment]
Is there any workaround for this? Still happens on iOS.

**Comment by msw333** [comment]
You could experiment with an animated container which changes its heigh when the textfield gets a focus, but this solution is very hacky. Hope that Flutter team gives us an info on this issue soon, since it would highly appreciate the smoothness and overall feel of flutter apps

**Comment by msw333** [comment]
BTW: What‘s really interesting is that the animation is perfectly correct in the flutter promotion videos, such as https://m.youtube.com/watch?time_continue=120&v=_ACWeGGBP4E (look at minute 1:56). Love to hear the opinion from a Flutter team member.

**Comment by gabdsg** [comment]
Is there any news?

**Comment by om-ha** [comment]
1- Thankfully in native **native iOS** development what you'd do is grab the NSNotification and extract the animation [curve](https://developer.apple.com/documentation/uikit/uiresponder/1621613-keyboardanimationcurveuserinfoke) and animation [duration](https://developer.apple.com/documentation/uikit/uiresponder/1621600-keyboardanimationdurationuserinf) to use in your custom animation.

2- BUT... as for **_native Android_** there doesn't seem a way to do this. And I think this is where the problem lies. There isn't even an event for plain keyboard showing/disappearing. People use a hack to be notified of this (`onGlobalLayout` and measure frame difference... [SEE THIS!!!)](https://github.com/adee42/flutter_keyboard_visibility/blob/master/android/src/main/java/com/github/adee42/keyboardvisibility/KeyboardVisibilityPlugin.java#L43)

Issue was already mentioned [here](https://github.com/flutter/flutter/issues/32141) and [here](https://github.com/flutter/flutter/issues/32455). 

Annoyingly, it hasn't been resolved yet. Which is tedious for satisfying perfectionist stakeholders :).

>What‘s really interesting is that the animation is perfectly correct in the flutter promotion videos

Hey, for a promising tech like flutter I would use platform-specific constant durations for these demos 🤷‍♂️

**Comment by Manguelo** [comment]
Getting the same issue. Any solution?

**Comment by muhd-ali** [comment]
Issue persists. Any suggestions to fix it?

[Demo.mov.zip](https://github.com/flutter/flutter/files/3906647/Demo.mov.zip)

**Comment by elisar4** [comment]
The only thing we can do right now is:
1. disable default Scaffold insets adjustments (resizeToAvoidBottomInset: false)
2. add Container with Positioned inside Stack
3. add AnimationController to change Positioned bottom: parameter
4. subscribe to Keyboard willChangeFrame notification
5. on will change calculate Positioned bottom offset to show full Container with keyboard presented
6. animate this offset with Curves.easeOutQuad (from my tests is the best match for default iOS keyboard animation, not perfectly match, but we don't have exact Curve transform formula which Apple is using)
I've done all this with Plugin (not published yet), but it is working not stable and I don't have time to finish it properly. Also, Android part can be tricky to implement in the same way (not investigated on that yet)

Few issues I met while doing this test Plugin:
I. SafeArea issue - flutter is using safeArea.bottom properly when keyboard is not presented, but once it is starting to appear on the screen, flutter's SafeArea just ignores bottom inset and behave as it was 0. This behaviour leads to different Container.height while keyboard presented and while it is not presented (difference for ~34px). I fixed that by setting maintainBottomViewPadding: true on SafeArea (in that case SafeArea is always using bottom inset, and I can just subtract it while calculating offset in 5.) But this leads to other issues in other layout setup, for example when using bottom tabBar.
II. I was not able to reproduce iOS keyboard animation Curve, because we don't have it in flutter with matching parameters such as dumping or other params I don't know iOS is using privately
III. Nested views, with current implementation probably will be issues if you try to use KBAContrainer(child: SomeWidgetTree(child: KBAContainer(child: OtherWidget))); it is not really an issue because you probably won't build such tree, but still a restriction. In this case OtherWidget will be lifted up twice as much as needed
IV. Android support. Since it have different API maybe it will be not so easy to implement same things

The best result so far:
![ezgif-2-d75e779e9805](https://user-images.githubusercontent.com/1868219/69917159-0c19ca00-1474-11ea-9b2c-b007862cc8c0.gif)

If someone experienced with plugin development is interested to make a workaround, I can share my test plugin progress

But, anyway support by flutter sdk is required on this topic. Maybe it is even easier to implement inside flutter SDK than with Plugin

**Comment by elisar4** [comment]
After some research and tests I come up with simplest possible solution for now:
1) Disable default Scaffold insets resizing (not animated)
2) Use AnimatedContainer with padding and calculated bottom inset

You can see small example in gist:
https://gist.github.com/elisar4/1d6a968dc6d5c1096a3dc64567a6ec73

Result:
![ezgif-2-24c6d8828c94](https://user-images.githubusercontent.com/1868219/69951624-a1fe3500-1506-11ea-8936-fe1581f3eb26.gif)
Not perfect, but better than nothing

**Comment by om-ha** [comment]
@elisar4 Good solution, I ended up with it as well. However it's not synced with the keyboard animation's properties (duration, curve)  as I mentioned above.

**Comment by orestesgaolin** [comment]
As Flutter matures I wish it would be handled on the platform level instead of custom hacky solutions. But all in all thanks everyone for the provided workarounds!

**Comment by HerrNiklasRaab** [comment]
Just to clarify, this happens also on iOS.

**Comment by lukepighetti** [comment]
Maybe one of us can record a video and try to extract the curves on latest iOS and Android? Does anyone know if the curves differ across Android manufacturers?

**Comment by lukepighetti** [comment]
Looks like it's a spring animation on iOS, we could easily do this with flutter engine. `sprung` has some boilerplate to get people started. https://forums.developer.apple.com/thread/48088

**Comment by drogel** [comment]
I have not been able to find a way to get the exact curves and animation parameters that iOS and Android use for the soft keyboard, but by recording the soft keyboard's showing and hiding in slow motion for several devices, I kind of managed to reproduce them. They are not pixel-perfect, but here is what I found:

**For iOS**

It looks like it is an animation based on a spring simulation. One could create such a `SpringSimulation` in Dart with:

```dart
final spring = const SpringDescription(mass: 8, stiffness: 1, damping: 4.5);
final keyboardShownSimulation = SpringSimulation(spring, 0, 1, 10);
final keyboardHiddenSimulation = SpringSimulation(spring, 1, 0, -10);
```

**For Android**

It looks like the position of the keyboard is animated during 150 milliseconds, using a 0, 0, 0.2, 1 cubic Bezier curve when presenting the keyboard and a 0, 0, 1, 0.2 when dismissing it. So, in Flutter, one can create an `AnimationController` that can be used to recreate the animation like this:

```dart
final controller = AnimationController(
      vsync: vsync,
      duration: const Duration(milliseconds: 150),
      reverseDuration: const Duration(milliseconds: 150),
    );
final animation = CurvedAnimation(
        parent: controller,
        curve: const Cubic(0, 0, 0.2, 1),
        reverseCurve: const Cubic(0, 0, 1, 0.2),
      );
```

Here is what it looks like:

![Example](https://github.com/drogel/keyboard_attachable/blob/master/keyboard_attachable.gif?raw=true)

I have developed a little package that serves as a workaround for this issue, as an animated alternative to `Scaffold.resizeToAvoidBottomInset`, and as an utility to build widgets that can be attached to the soft keyboard. It's called keyboard_attachable, you can find it on [pub.dev](https://pub.dev/packages/keyboard_attachable).

The package contains the hard-coded animations I described, plus a widget to easily animate the shrinkage and expansion of a page when the soft keyboard is shown and hidden. I know it is not the ideal solution, and it's not matching exactly the curves from the platform animations, but for me it is good enough to give some kind of visual guidance when the keyboard appears, instead of an instant jump.

**Comment by lukepighetti** [comment]
The fidelity appears to be excellent, although I wonder if the dismiss animation on Android is appropriate. It looks a little janky but it may be normal? I don't use Android enough to have an opinion. iOS appears to be spot on.

Now who's going to make an issue for a swipe to dismiss iOS keyboard? :D

**Comment by drogel** [comment]
Yeah it is a bit janky. I think the cause of that is a combination of the recording FPS and of the fact that in Android, the keyboard not only moves but it also fades out when dismissing, which causes the component behind the keyboard to be visible for a fraction of second, which is a bit awkward in my opinion... The animations might still need a bit of refinement, maybe easing the curve a bit more for the final part of the keyboard dismissal animation? 

Anyways, I consider this a hacky workaround, only valid until the framework provides a way to handle these animations properly.

**Comment by lukepighetti** [comment]
I'm going to use your package for sure. I really appreciate the efforts.

**Comment by hugopretorius914** [comment]
Using your package @drogel - thank you

**Comment by kensou123** [comment]
@drogel how about if i tap a button then textfield and keyboard will slide up at the same time?

**Comment by drogel** [comment]
@kensou123 Well, my package could be a starting point for that, but you would need to make the textfield shrink and expand when the keyboard shows yourself. The package is more about footers and about resizing the page with animations.

You may find [the keyboard_actions package](https://pub.dev/packages/keyboard_actions) useful though. I have not contributed to it, and I have not used it, but it looks like it is what you need in your case?

**Comment by kensou123** [comment]
Thanks for replying. Very much appreciated.

**Comment by YeungKC** [comment]
maybe iOS can use keyboardWillShowNotification, android can use https://developer.android.com/preview/features#control-ime

**Comment by NicolasCELLA** [comment]
I really think it's a big problem right now on ios! User experience is very heavily affected. Do you know if flutter has planned anything about this problem?

**Comment by Jan-pp** [comment]
I am working on a solution for iOS that perfectly synchronizes the keyboard with Flutter. It also allows you to change the keyboard animation curve and speed. Below example moves the scaffold up with the keyboard, keeping the text field centered:

![ezgif com-optimize-4](https://user-images.githubusercontent.com/56071132/85919139-f41ef300-b868-11ea-8a97-e4557775fcfb.gif)

The solution is pretty hacky but so far so good. I tested it on a real device in release mode while filming the screen with a slo-mo camera. It showed perfect synchronization and no frame skips.

**Comment by buivanthu** [comment]
Can you share you code?

Vào Th 7, 27 thg 6, 2020 lúc 18:34 Jan-pp <notifications@github.com> đã
viết:

**Comment by lukepighetti** [comment]
@jan-pp any chance you can implement a swipe to dismiss the keyboard?

Are you driving the iOS keyboard curve with a Flutter curve? Because if you are, that's wicked smart.

**Comment by Jan-pp** [comment]
Yeah I gave it a try, works well. You need to start dragging from outside the keyboard though, but that's what you probably want anyway.

![ezgif com-optimize-5](https://user-images.githubusercontent.com/56071132/86010742-186f0100-ba1c-11ea-9e25-3506ae29a4f6.gif)

Yes Flutter is controlling the position of the keyboard window, which opens up possibilities. There are still bugs to fix and scenarios to cover.

**Comment by lukepighetti** [comment]
I think that's a brilliant way to solve this problem. Happy to test out a package if you post it up.

**Comment by gabdsg** [comment]
> ![ezgif com-optimize-5](https://user-images.githubusercontent.com/56071132/86010742-186f0100-ba1c-11ea-9e25-3506ae29a4f6.gif)

This is awesome!! 
Happy to test it out too.

**Comment by gabdsg** [comment]
@Jan-pp any update on this? I am very excited about it 🤩

**Comment by Jan-pp** [comment]
I haven't had much time lately. Maybe in a week or two I'll have some time to work on it again, sorry. Don't worry it will come eventually.

**Comment by mkiisoft** [comment]
@Jan-pp if you can share the code we can help you with all possible scenarios and bug fixing. This is awesome! Also, on Android 11 developer preview 4 they created a class which notifies both, keyboard animation show/hide and swipe (same as iOS). If that one is backwards compatible, we can bring it to Flutter (both: iOS and Android).

**Comment by Jan-pp** [comment]
Okay I cleaned up some code. Below I have a rudimentary proof of concept to play with. Wrap a Scaffold with the widget below and make sure to set its `resizeToAvoidBottomInset` to `false`.

```
class KBTestWidget extends StatefulWidget {
  @override
  _KBTestWidgetState createState() => _KBTestWidgetState();
  KBTestWidget({Key key, this.child});
  final Widget child;
}

class _KBTestWidgetState extends State<KBTestWidget> with SingleTickerProviderStateMixin {
  AnimationController _animationController;
  Animation _animation;
  var _kbHeight = 0.0;
  var _kbShown = false;
  final _methodChannel = const MethodChannel('kbtestwidget');
  final _fps = 60; //TODO get actual hertz somewhere

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 400),
      reverseDuration: const Duration(milliseconds: 400),
      value: _kbHeight,
    );
    _setAnimation(begin: 0.0, end: 1.0);

    _methodChannel.setMethodCallHandler(this._didRecieveNativeCall);
  }

  @override
  void dispose() {
    super.dispose();
    _animationController.dispose();
  }

  _setAnimation({double begin, double end}) {
    _animation = Tween(begin: begin, end: end).animate(CurvedAnimation(
      parent: _animationController,
      curve: Curves.easeOutCubic,
      reverseCurve: Curves.easeInCubic,
    ));
  }

  _startAnimation([bool forward = true]) {
    //animation starts at 0, but since it's already at 0 when it starts the first frame is just wasted time, so the value in from: makes it skips this while keeping the curve right
    final firstFrameSkip = 1000000 / (_fps * _animationController.duration.inMicroseconds);
    if (forward) {
      _animationController.forward(from: firstFrameSkip).whenComplete(() => _setAnimation(begin: 0.0, end: 1.0));
    } else {
      _animationController.reverse(from: 1 - firstFrameSkip);
    }
  }

  Future<void> _didRecieveNativeCall(MethodCall call) async {
    print(call);
    _kbHeight = call.arguments;

    if (call.method == 'kbshow') {
      _setAnimation(begin: 0.0, end: 1.0);
      _startAnimation(true);
      _kbShown = true;
    } else if (call.method == 'kbhide') {
      _startAnimation(false);
      _kbShown = false;
      FocusManager.instance.primaryFocus.unfocus(); //failsafe just in case the hide is not triggered by actual keyboard hiding
    }
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onPanUpdate: (details) {
        if (!_kbShown) return;

        final pos = min(MediaQuery.of(context).size.height - details.localPosition.dy, _kbHeight);
        setState(() {
          _setAnimation(begin: pos / _kbHeight, end: pos / _kbHeight);
        });
      },
      onPanEnd: (details) {
        if (!_kbShown) return;

        if (_animation.value > 0.5) {
          _animation = Tween(begin: _animation.value, end: 1.0).animate(CurvedAnimation(
            parent: _animationController,
            curve: Curves.bounceOut,
            reverseCurve: Curves.easeInCubic,
          ));
          _startAnimation(true);
        } else {
          _setAnimation(begin: 0.0, end: _animation.value);
          FocusManager.instance.primaryFocus.unfocus();
        }
      },
      child: Column(
        children: [
          Expanded(
            child: widget.child,
          ),
          Material(
            color: Colors.blueGrey, //set the keyboard background color here
            child: AnimatedBuilder(
              animation: _animationController,
              builder: (_, child) {
                //after Flutter rendered the frame move the native keyboard, still the keyboard may be a frame ahead sometimes (in debug builds anyway), pretty weird
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  _methodChannel.invokeMethod('kbdown', _kbHeight + (_animation.value * _kbHeight) * -1);
                });

                return SizedBox(
                  width: double.infinity,
                  height: _animation.value * _kbHeight,
                  child: child,
                );
              },
            ),
          )
        ],
      ),
    );
  }
}
```


Also add this to the AppDelegate class in AppDelegate.swift:

```
    
    var methodChannel: FlutterMethodChannel?
    
    override func applicationDidBecomeActive(_ application: UIApplication) {
        
        if methodChannel == nil, let rootViewController = window?.rootViewController as? FlutterViewController {
            
            methodChannel = FlutterMethodChannel(name: "kbtestwidget", binaryMessenger: rootViewController as! FlutterBinaryMessenger)
            
            //this method basically sets the y position of the keyboard to what Flutter says it to
            methodChannel?.setMethodCallHandler {(call: FlutterMethodCall, result: FlutterResult) -> Void in
                if UIApplication.shared.windows.count > 2, let kbWindow = UIApplication.shared.windows.last {
                    DispatchQueue.main.async(execute: {
                        kbWindow.frame = CGRect.init(x: kbWindow.frame.minX, y: call.arguments as! CGFloat, width: kbWindow.frame.width, height: kbWindow.frame.height)
                    })
                }
                result(true)
            }
            NotificationCenter.default.addObserver(self, selector: #selector(keyboardNotification(notification:)), name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
        }
        
    }
    
    @objc func keyboardNotification(notification: NSNotification) {
        
        if let userInfo = notification.userInfo {
            
            let startFrame = (userInfo[UIResponder.keyboardFrameBeginUserInfoKey] as? NSValue)?.cgRectValue
            let endFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue
            let duration:TimeInterval = (userInfo[UIResponder.keyboardAnimationDurationUserInfoKey] as? NSNumber)?.doubleValue ?? 0
            let animationCurveRawNSN = userInfo[UIResponder.keyboardAnimationCurveUserInfoKey] as? NSNumber
            let animationCurveRaw = animationCurveRawNSN?.uintValue ?? UIView.AnimationOptions.curveEaseInOut.rawValue
            let animationCurve:UIView.AnimationOptions = UIView.AnimationOptions(rawValue: animationCurveRaw)
            
            if let startFrame = startFrame, let endFrame = endFrame {
                //print(startFrame.size.height)
                //print(endFrame.size.height)
                
                if startFrame.origin.y == endFrame.origin.y
                {
                    return
                }
                
                if startFrame.origin.y > endFrame.origin.y //keyboard show
                {
                    //tell Flutter the keyboard is showing and its height
                    methodChannel?.invokeMethod("kbshow", arguments: endFrame.size.height)
                    
                    //this moves the keyboard frame down with the same animation curve as it is sliding up, effectively keeping it stationary just below the screen
                    if UIApplication.shared.windows.count > 2, let kbWindow = UIApplication.shared.windows.last {
                        UIView.animate(withDuration: duration,
                                       delay: TimeInterval(0.0),
                                       options: animationCurve,
                                       animations: {
                                        kbWindow.frame = CGRect.init(x: kbWindow.frame.minX, y: kbWindow.frame.minY + endFrame.size.height, width: kbWindow.frame.width, height: kbWindow.frame.height)
                        })
                    }
                    return;
                }
                else //keyboard hide
                {
                    //tell Flutter the keyboard is hiding and its height
                    methodChannel?.invokeMethod("kbhide", arguments: endFrame.size.height)
                    
                    //this moves the keyboard frame up with the same animation curve as it is sliding down, effectively keeping it stationary for about 0.4 seconds before it disappears
                    if UIApplication.shared.windows.count > 2, let kbWindow = UIApplication.shared.windows.last {
                        UIView.animate(withDuration: duration,
                                       delay: TimeInterval(0.0),
                                       options: animationCurve,
                                       animations: {
                                        kbWindow.subviews[0].subviews[0].frame = CGRect.init(x: kbWindow.subviews[0].subviews[0].frame.minX+0.0, y: kbWindow.subviews[0].subviews[0].frame.minY - startFrame.size.height, width: kbWindow.subviews[0].subviews[0].frame.width, height: kbWindow.subviews[0].subviews[0].frame.height)
                        })
                    }
                    return;
                }
            }
        }
    }
```

I already have an idea on a more reliable way to get the keyboard frame, and many other things for that matter. It's going to be a challenge to deal with screen rotating and don't even get me started on iPad...

**Comment by lukepighetti** [comment]
Can you put it in a GitHub repo?

**Comment by Jan-pp** [comment]
I dumped it on GitHub now (see prev. post). Not a proper repo yet but it's something.

**Comment by darshankawar** [comment]
Issue replicable on latest Stable (1.20.2). Tested on iPhone SE simulator.

[19279.mov.zip](https://github.com/flutter/flutter/files/5129870/19279.mov.zip)

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/20843 Implements syncing on Android of embedder initiated IME animations

**Comment by rizzi37** [comment]
ping ios

**Comment by buivanthu** [comment]
ping for any update

**Comment by ryanboerner** [comment]
ping iOS. Definitely a problem for clients who expect this to work like the Flutter video demos.

**Comment by Smagold** [comment]
any updates on built-in support for this?

**Comment by Truba** [comment]
Hi Flutter team,

I was taking a look at the implementation of the `FlutterViewController`, especially at this function:
https://github.com/flutter/engine/blob/1411cb671be8ddf4f16f8d3bd96d7a86a43b6fd3/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L1031

Could this issue be solvable by wrapping the `[self updateViewportMetrics];` in `UIView.animate` block with duration and curve taken from the notification?

**Comment by koldoon** [comment]
Any progress on this? Really frustrating thing :(

**Comment by normancarcamo** [comment]
What's the duration of the animation of the keyboard? I am trying to synchronize the keyboard with a custom effect and guessing works, but it would be nice to have a reference, 300/400ms?.

**Comment by lukepighetti** [comment]
It's different on every operating system.

**Comment by MirceaX2Mobile** [comment]
Are there any news about this? This is happening on iOS and Android too. :(

**Comment by Galti** [comment]
Is there any updates? This issue should have already been solved.

**Comment by lukepighetti** [comment]
Related: https://github.com/flutter/flutter/issues/76170

**Comment by sooxt98** [comment]
Ping for iOS field focus animation~

**Comment by NicolasCELLA** [comment]
Hello Flutter team, can you give some news around this problem?

**Comment by rserro** [comment]
This behavior is very annoying for apps that use widgets sticked to the keyboard. It gives the user an uncomfortable experience of watching two animations that should be the same not being the same. It seems like that something broke. It would be great to have a solution.

**Comment by KubaStachecki** [comment]
Facing the same issue. There is a a good 2 seconds delay between keyboard appearing in android and beginning of Scaffold animation (keyboard appears, covers lower part of UI, time passes, UI adjusts with delay showing Text input finally). It doesn't seem to matter how complex UI is - even simple Container lags. 

Using real device and Flutter stable, 2.0.6

What I also discovered is that the lag seems to be more prominent when device is set to 120hz instead of 60hz.

**Comment by rserro** [comment]
This problem is actually solved if there was a way for Flutter to get the keyboard show/hide animation curve and duration from the OS. Then a simple AnimatedContainer/Size padded with viewInsets and the right curve/duration does the trick.

**Comment by b3nni97** [comment]
Any updates?

**Comment by yasinarik** [comment]
It is not an actual solution but when we use an AnimatedContainer or AnimatedPadding we can define a duration and a curve, as most of you already know. 

The iOS and Android behave different of course. 

Does iOS devices differ from each other in case of duration and curve? For example, do iPhone 8 and iPhone 12 Pro have different keyboard opening and closing animations?

Moreover, I think that Android devices have more difference in many UI elements. So probably they have different curves and durations too. 

So it's not possible to put a logic that change the curve and duration values for each and every mobile device. Even we do that, same type of devices may act different because of for example their empty storage.

Thus, we have to have a direct coupling from the native side.

Writing, note taking, messaging, commenting are undeniably the core elements of almost any mobile app today. Considering the people gave thumbs up for the issue, it made me wonder why this is not closed by providing a valid & proper solution. 

🤔👀

**Comment by drogel** [comment]
Just commenting to give a brief status to anyone who stumbles upon this issue trying to find a solution for the keyboard animation problem.

Right now the best I have been able to do is, just like @yasinarik mentioned, building an `AnimatedContainer` with a custom, Flutter-side hardcoded animation controller that tries to imitate the ones Android and iOS apply to animate the keyboard when appearing.

For that, I use:

-  [Janneman84's crazy_cool_keyboard_for_flutter](https://github.com/Janneman84/crazy_cool_keyboard_for_flutter) 
- My own implementation of the "`AnimatedContainer` + custom animation controllers" approach, which I extracted into the [keyboard_attachable package](https://pub.dev/packages/keyboard_attachable) to make it easier to reuse the code.

These are still workarounds, but they have proved enough for me to give a visual guide for users.

**Comment by Truba** [comment]
Hi Flutter team, Apple just release [UIKeyboardLayoutGuide](https://developer.apple.com/documentation/uikit/uikeyboardlayoutguide) for iOS 15.
Would you be able to leverage this new feature to fix the animation for iOS?

**Comment by milanobrenovic** [comment]
Hello Flutter team, when is this issue going to be resolved?

**Comment by vukhacbiet** [comment]
Hi Flutter team, can you give new updates?

**Comment by Vardiak** [comment]
This needs more attention (comment to prevents the issue from being closed)

**Comment by b3nni97** [comment]
I know it's probably not that easy to implement this feature, but it makes any Flutter iOS App much more native. Anyone who has been using iOS for a few years will immediately recognize that something is wrong.

**Comment by om-ha** [comment]
@Tharuja As has been said a few issues ago, a PR by @luckysmg has been raised. [flutter/engine#29281](https://github.com/flutter/engine/pull/29281)

**Comment by luckysmg** [comment]
The PR related to this issue has been merged in flutter engine:https://github.com/flutter/engine/pull/29281

**Comment by om-ha** [comment]
Finally, you put a nail into this 2018 coffin.

No matter how annoying this issue is, I never unmuted it waiting for this glorious moment. Thanks @luckysmg !

**Comment by buivanthu** [comment]
Thanks @luckysmg <https://github.com/luckysmg>

Vào Th 3, 9 thg 11, 2021 lúc 10:25 om-ha ***@***.***> đã viết:

**Comment by josh-umahi** [comment]
Any update on this issue?

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/29281 fixed this, thanks @luckysmg

**Comment by jaesam** [comment]
Just a curiosity, will this be shipped in the next stable version?
