### ISSUE TITLE
setState behavior

### ISSUE THREAD

**Issue by yarumair** [flutter/flutter#19312]
Iam a newbie to flutter and following the tutorial here https://flutter.io/get-started/codelab/. In "Step 5: Add interactivity" the "setState" function is used to update the row to show favorite marked items. I debug the application to check the how the setState is working, by tapping on one row and found that it is actually calling itemBuilder for all the rows. So its not actually updating the row in question instead its updating / rebuilding all the rows. 

Is this how setState is supposed to be working? if so then is there any method which only updates the row in question and not the whole List?

P.S: I didn't include the code since code is already there at above link. Iam debugging by connecting it with actual Iphone 6s device using Visual Studio Code on macbook pro.

**Comment by zoechi** [comment]
I think this is a result of the rendering protocol. When an item in the list is re-rendered, the ListView will want to know because any change in size of the item will probably need other items to be re-rendered on different positions.

You could try wrapping the item in a https://docs.flutter.io/flutter/widgets/SizedBox-class.html with fix height and width and check if `itemBuilder` is still called for all (still might, not sure).

Don't know much about layout myself yet. Lets hope someone more knowledgeable finds this and answers as well ;-)

**Comment by yarumair** [comment]
HI @zoechi 

I tried wrapping the call for `_buildRow` function inside `_buildSuggestions` widget with fixed width & height. However, its still updating all the rows.

Its mentioned on the tutorial itself that:

> In Flutter’s react style framework, calling setState() triggers a call to the build() method for the State object, resulting in an update to the UI.

so it makes sense since the build method actually is buiding all the rows.

So i have got answer to setState behavior, however, still wondering if there is any way to update just one row which is tapped instead of updating all.

**Comment by zoechi** [comment]
You shouldn't worry about that. 
`build()` can be called at any time and you should build your widgets so that this doesn't cause problems when it is called multiple times.
See also #19297

**Comment by zoechi** [comment]
Can this be closed?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
