### ISSUE TITLE
Landscape mode with navigation buttons screen redraw on phones broken.

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#19319]
I am writing an app primarily intended to be used in landscape mode. When you type on a keyboard (so that android shows the navigation bar). On phones in landscape mode (tested on Nexus 5 and Nexus 6 emulator) the navigation buttons (back, home, square) are shown on the short edge of the phone no matter the orientation (on tablets the navigation bar is shown on the bottom edge and so it is not an issue).

Flutter doesnt seem to know that the navigation bar is present (on the right hand side in phones in landscape mode), so the screen will be drawn behind the navigation bar. You can move from page to page and the screen is drawn under the navigation bar and so part of the screen is obscured.

**Comment by Rockvole** [comment]
A reasonable workaround would be to have an opaque navigation bar, or to hide the navigation bar when the keyboard is dismissed. 

I cannot work out how to do either of those.

**Comment by Rockvole** [comment]
I tried to make the navigation bar opaque, with code in MainActivity.java :

    Window w = getWindow(); // in Activity's onCreate() for instance
    w.setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
    w.setFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION, WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);

And :

    Window window=this.getWindow();
    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS); 
    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
    window.setStatusBarColor(0x00000000);

but neither worked.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/6288 in combination with https://github.com/flutter/engine/pull/6282 should deal with this issue. We now use heuristics to "detect" the keyboard and hide the left/right nav bar as needed. Also we will soon provide a SystemChrome call to allow for restoration of previously set system UI (https://github.com/flutter/flutter/pull/22221 and https://github.com/flutter/engine/pull/6322)

**Comment by Rockvole** [comment]
Tested on :

    Flutter (Channel master, v1.0.1-pre.2, on Linux, locale en_CA.UTF-8)

Still has the same problem.

**Comment by GaryQian** [comment]
So there is a workaround that will work to ensure the navigation bar hides again. You can call `SystemChrome.restoreSystemUIOverlays()` which will restore the overlays to the last state set in `SystemChrome.setEnabledSystemUIOverlays()`

I can look further into your specific bug. Would your expected behavior be the app adjusting itself to the navigation bar or the navigation bar disappearing when the keyboard disappears?

**Comment by Rockvole** [comment]
When the keyboard appears (in landscape mode) the navigation bar appears and the arrow button changes direction indicating that the navigation bar back buttons new purpose is to dismiss the keyboard. So pressing that dismisses the keyboard but the navigation bar remains.
 
I think the intended behaviour would be to also dismiss the navigation bar if that button is pressed or the completed check button is pressed on the keyboard.

**Comment by GaryQian** [comment]
I remember from my work on this issue before that it is actually non-trivial to detect when the keyboard has been dismissed. The OS by default enforces that the navbar cannot be hidden if not enough time has passed (about 1 second) since it has appeared, so from the POV of Flutter, it is not reliable for flutter to autohide the navbar if it was previously hidden.

See https://github.com/flutter/flutter/issues/7247 for info regarding dismissing the keyboard.

I recommend that you use `SystemChrome.restoreSystemUIOverlays()` in whatever keyboard dismissal detection system that is appropriate. Keeping timestamps of when the keyboard was displayed and checking enough elapsed time should help work around the OS-enforced min navbar time.

**Comment by Rockvole** [comment]
Ok, I can approximate the way that my Android Apps seem to work.
I just do :

    SystemChrome.setEnabledSystemUIOverlays([]);

In my main at startup to dismiss the navigation bar, and then :

    @override
      void didPopNext() {
        SystemChrome.setEnabledSystemUIOverlays([]);
      }
In a [RouteObserver class](https://docs.flutter.io/flutter/widgets/RouteObserver-class.html)
Which dismisses the navigation bar each time you move to a different page.
