### ISSUE TITLE
How to reproduce .setTimestampsInSnapshotsEnabled(true) in Flutter

### ISSUE THREAD

**Issue by MStanoevich** [flutter/flutter#19356]
I am trying to upload an image to Firebase Storage but when I try to do so I get the following message:

```
W/Firestore( 7877): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore( 7877): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore( 7877):
W/Firestore( 7877): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore( 7877): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore( 7877):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore( 7877):     .build();
W/Firestore( 7877): firestore.setFirestoreSettings(settings);
W/Firestore( 7877):
W/Firestore( 7877): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore( 7877):
W/Firestore( 7877): // Old:
W/Firestore( 7877): java.util.Date date = snapshot.getDate("created_at");
W/Firestore( 7877): // New:
W/Firestore( 7877): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore( 7877): java.util.Date date = timestamp.toDate();
W/Firestore( 7877):
W/Firestore( 7877): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
```
I am not sure how to implement this in Flutter as I cannot find any Settings type class nor any similar methods as in the example in the documentation.

Thank you in advance!

**Comment by zoechi** [comment]
This looks like a dup of #18159. 
I'd suggest you upvote this issue.

**Comment by chintooflutter** [comment]
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'dart:async';

Future<void> main() async {
  final FirebaseApp app = await FirebaseApp.configure(
    name: 'test',
    options: const FirebaseOptions(
      googleAppID: '1:79601577497:ios:5f2bcc6ba8cecddd',
      gcmSenderID: '79601577497',
      apiKey: 'AIzaSyArgmRGfB5kiQT6CunAOmKRVKEsxKmy6YI-G72PVU',
      projectID: 'flutter-firestore',
    ),
  );
final Firestore firestore = Firestore(app: app);
  await firestore.settings(timestampsInSnapshotsEnabled: true);

  runApp(MyApp());
}

final dummySnapshot = [
  {"name": "Filip", "votes": 15},
  {"name": "Abraham", "votes": 14},
  {"name": "Richard", "votes": 11},
  {"name": "Ike", "votes": 10},
  {"name": "Justin", "votes": 1},
];

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Baby Names',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() {
    return _MyHomePageState();
  }
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Baby Name Votes')),
      body: _buildBody(context),
    );
  }

  Widget _buildBody(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection('baby').snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return LinearProgressIndicator();

        return _buildList(context, snapshot.data.documents);
      },
    );
  }

  Widget _buildList(BuildContext context, List<DocumentSnapshot> snapshot) {
    return ListView(
      padding: const EdgeInsets.only(top: 20.0),
      children: snapshot.map((data) => _buildListItem(context, data)).toList(),
    );
  }

  Widget _buildListItem(BuildContext context, DocumentSnapshot data) {
    final record = Record.fromSnapshot(data);

    return Padding(
      key: ValueKey(record.name),
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      child: Container(
        decoration: BoxDecoration(
          border: Border.all(color: Colors.grey),
          borderRadius: BorderRadius.circular(5.0),
        ),
        child: ListTile(
          title: Text(record.name),
          trailing: Text(record.votes.toString()),
            onTap: () => Firestore.instance.runTransaction((transaction) async {
              final freshSnapshot = await transaction.get(record.reference);
              final fresh = Record.fromSnapshot(freshSnapshot);

              await transaction
                  .update(record.reference, {'votes': fresh.votes + 1});
            }),
        ),
      ),
    );
  }
}

class Record {
  final String name;
  final int votes;
  final DocumentReference reference;

  Record.fromMap(Map<String, dynamic> map, {this.reference})
      : assert(map['name'] != null),
        assert(map['votes'] != null),
        name = map['name'],
        votes = map['votes'];

  Record.fromSnapshot(DocumentSnapshot snapshot)
      : this.fromMap(snapshot.data, reference: snapshot.reference);

  @override
  String toString() => "Record<$name:$votes>";
}


===============================================================
**Getting Error as below.** 

Launching lib\main.dart on Redmi 5A in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
D/NetworkSecurityConfig(32614): No Network Security Config specified, using platform default
I/ProviderInstaller(32614): Installed default security provider GmsCore_OpenSSL
Syncing files to device Redmi 5A...
W/Firestore(32614): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore(32614): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore(32614): 
W/Firestore(32614): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore(32614): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore(32614):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore(32614):     .build();
W/Firestore(32614): firestore.setFirestoreSettings(settings);
W/Firestore(32614): 
W/Firestore(32614): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore(32614): 
W/Firestore(32614): // Old:
W/Firestore(32614): java.util.Date date = snapshot.getDate("created_at");
W/Firestore(32614): // New:
W/Firestore(32614): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore(32614): java.util.Date date = timestamp.toDate();
W/Firestore(32614): 
W/Firestore(32614): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
W/art     (32614): Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
W/art     (32614): Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
W/art     (32614): Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/Firestore(32614): (0.6.6-dev) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(32614): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
W/Firestore(32614): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
W/Firestore(32614): 	at java.net.InetAddress.getAllByName(InetAddress.java:752)
W/Firestore(32614): 	at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:497)
W/Firestore(32614): 	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:200)
W/Firestore(32614): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/Firestore(32614): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/Firestore(32614): 	at java.lang.Thread.run(Thread.java:760)
W/Firestore(32614): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(32614): 	at libcore.io.Posix.android_getaddrinfo(Native Method)
W/Firestore(32614): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
W/Firestore(32614): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
W/Firestore(32614): 	... 7 more
W/Firestore(32614): }
W/Firestore(32614): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(32614): [{0}] Failed to resolve name. status={1}

**Comment by zoechi** [comment]
@chintooflutter ensure you have the latest versions of dependencies.
