### ISSUE TITLE
Upgrade problem of Dart to use flutter gallery.

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19382]
When I tried to use flutter gallery, I got this error message.

> Because flutter_gallery depends on shelf >=0.7.3+2 which requires SDK version >=2.0.0-dev.61.0 <2.0.0, version solving failed.
> pub upgrade failed (1)

So I wanted to upgrade dart SDK to dev.61.0, but how can I upgrade? I installed choco and upgarded dart but it didn't work not at all. My flutter doctor said like below.

> [√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale ko-KR)
>     • Flutter version 0.5.1 at C:\flutter
>     • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
>     • Engine revision 1ed25ca7b7
>     • Dart version 2.0.0-dev.58.0.flutter-f981f09760

Yes, my Dart version is 2.00-dev.58.0, but I need 2.00-dev.61.0 to see WHAT FLUTTER GALLERY IS.
How can I fix it?

**Comment by leo-chaoliu** [comment]
The same issue I just faced when I am in Master branch by default, checkout the beta branch will be fine.

> git checkout -t origin/beta
> flutter packages get

**Comment by baeharam** [comment]
@zoechi @leo-chaoliu Sorry for late answer, I had an appendectomy. It was solved by @leo-chaoliu :)

**Comment by zoechi** [comment]
@baeharam thanks for the update. Then let's close this issue.

**Comment by ibanjac** [comment]
Hello, i have the same issue
[flutter_gallery] flutter packages get
Running "flutter packages get" in flutter_gallery...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because flutter_gallery depends on shelf >=0.7.3+2 which requires SDK version >=2.0.0-dev.61.0 <3.0.0, version solving failed.
pub get failed (1)
exit code 1

Flutter doctor
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 0.5.1 at C:\Project\flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760
I have the latest flutter and dart sdk and plugins
I have installed the latest dart release
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "windows_x64"
I am also in beta channel (i have tried other channels, still fails)

**Comment by zoechi** [comment]
> Dart version 2.0.0-dev.58.0.flutter-f981f09760

@ibanjac sounds like you need to update to a newer Flutter version that ships with `requires SDK version >=2.0.0-dev.61.0 `

**Comment by ibanjac** [comment]
I have the latest flutter sdk, latest Dart VM version: 2.0.0-dev.69.5, latest vs code plugins

**Comment by zoechi** [comment]
@ibanjac The installed Dart VM version doesn't matter, only the Dart VM version shipped with Flutter.
Try 
```
flutter channel dev
flutter upgrade
```
