### ISSUE TITLE
Buttons are no longer respecting CrossAxisAlignment.stretch

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#19399]
Prior to a recent update of the master branch, buttons were stretched when placed in `Column` with `CrossAxisAlignment.stretch`. Now the behavior changed and there is no way to make buttons which fill the screen width:

<img src="https://user-images.githubusercontent.com/22688477/42747476-d2e5d1f8-88dc-11e8-97a2-2519479479e7.png" width="300">

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Button Cross Axis Alignment Bug',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new HomePage(),
    );
  }
}

class HomePage extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new Container(
        padding: EdgeInsets.all(16.0),
        child: new Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Container(
              color: Colors.red,
              child: Text('This container is stretched'),
            ),
            RaisedButton(onPressed: () {}, child: Text('Raised Button')),
            FlatButton(onPressed: () {}, child: Text('Flat Button'), color: Colors.orange,),
          ],
        ),
      ),
    );
  }
}
```

**Comment by jogboms** [comment]
Also noticed this regression on the master branch.

**Comment by zoechi** [comment]
This should do what you want

```dart
ButtonTheme(
  minWidth: double.infinity,
  child: RaisedButton(
    onPressed: () {},
    child: Text('Raised Button'),
  ),
),
```
You can also get the parent `ButtonTheme.of(context)` and use `.copyWith(minWidth: double.infinity)` to specialize a parent theme.

**Comment by jonahwilliams** [comment]
In a recent update I added an additional render object which applied constraints to all material buttons with the goal of getting the tap target area to a minimum of 48 by 48 for android accessibility.  Thus if you are applying exterior constraints to stretch it, you will now stretch this outer render object instead of the visible material.  The solution is what @zoechi posted above - use the button theme to apply the constraints you want.

I'm sorry for the confusion this update caused, it was not a use case I anticipated - but the update was probably the least destructive way to implement it.

**Comment by jonahwilliams** [comment]
I'll find a solution to this

**Comment by chornbe** [comment]
Since Flutter is a UI-centric implementation (of Dart, but that's immaterial), I guess what I don't understand is why each element doesn't have some basic, intrinsic elements like height, width, alignment, margin, and padding, just built right in. Leave them blank for auto-layout purposes, but values override. It wouldn't take long for the developer to figure out "oh, I just need to set that value", or perhaps more importantly, to NOT set a value, to get the layout he wants, while still working with a tool set that has a LOT of built-in flexibility and tunability without having to... really?... wrap a button in a button theme, as one example. ** shrug **
