### ISSUE TITLE
flutter_gallery__memory_nav diff_total_kb increased

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19436]
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by aam** [comment]
The way how we run memory benchmarks in profile mode(rather than in release mode) is highly susceptible to fluctuations, interference from vm service. This was brought up before: https://github.com/flutter/flutter/issues/10998 and https://github.com/flutter/flutter/issues/11300.

cc @rmacnak-google

**Comment by Hixie** [comment]
I'll take a look at making a better benchmark so we can debug this better.

**Comment by Hixie** [comment]
Update: We are tracking down the exact cause. Separately we're working on improving the benchmark.

**Comment by gspencergoog** [comment]
I took a sampling of recent builds, back to a particularly "good" memory measurement, and spanning a recent engine roll, ran this test 10 times for each hash, and averaged the results.

The resulting graph:
![image](https://user-images.githubusercontent.com/8867023/42907486-c9506df8-8a92-11e8-8b13-ddbd79178eba.png)

This is significantly less noisy than the benchmark graph:
![image](https://user-images.githubusercontent.com/8867023/42907588-11e3c7ea-8a93-11e8-9aac-b945f121ef56.png)

This implies that we really need to move to measuring memory in release mode (which @Hixie is working on).

**Comment by gspencergoog** [comment]
I took a set of recent builds, back to a particularly "good" measurement, and spanning an engine roll, and ran this test on each revision 10 times and averaged the output values:

![image](https://user-images.githubusercontent.com/8867023/42907800-c459f070-8a93-11e8-9509-9b223e2cea8e.png)

This is significantly less noisy than the corresponding benchmark:

![image](https://user-images.githubusercontent.com/8867023/42907749-9fc49918-8a93-11e8-985b-58a14787b6c0.png)

This bolsters the argument that we are pursuing the right strategy by moving memory benchmarks to running release mode instead of profile mode.

**Comment by gspencergoog** [comment]
Here's a more detailed graph, showing the min and max values for the 10 runs:
![image](https://user-images.githubusercontent.com/8867023/42909060-a476acf4-8a97-11e8-855f-3c900d8a79a1.png)

**Comment by Hixie** [comment]
I'm going to close this since we couldn't support the regression with data. I'm tracking my work on making the benchmarks less noisy in a separate bug.
