### ISSUE TITLE
complex_layout_semantics_perf initialSemanticsTreeCreation ~40% regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19435]
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by aam** [comment]
This seems to have been introduced in https://github.com/dart-lang/sdk/commit/98a2e90d4f0ce1e0fa092d3fde7cbec2b8b6a6ce, which ended up in https://github.com/flutter/engine/commit/d9a831c5557ea06ff53260890d402b96d1af9470

cc @rmacnak-google

**Comment by rmacnak-google** [comment]
In synchronizing with the engine, `flutter drive` creates a gap during startup that the engine reports to the VM as an idle period. At this time, the app hasn't done anything yet and the heap is small and there is no external memory (e.g., dart:ui.Image), so the growth policy chooses a rather low allocation limit. The benchmark proper then starts and the first Images quickly cross this limit and trigger an old space (slow) GC. This is unlikely to occur in a real app because they do not have idle periods before the initial screen.

A possible mitigation is for the engine to defer idle notification until the app has finished startup.

**Comment by Hixie** [comment]
We should consider forcing a GC before we start the timing.

**Comment by Hixie** [comment]
Update: This is caused by the GC timing having changed to now be included in the benchmark. We will attempt to make the test force a GC before starting the measurement.

**Comment by Hixie** [comment]
@rmacnak-google  The fix above didn't make any difference to the benchmark as far as I can tell. Can you elaborate on the expected effect?

**Comment by rmacnak-google** [comment]
The expected effect is the new space growth happens during the setup and the idle GC at the following message boundary gets to an empty state. This worked locally on a Moto G4.

**Comment by rmacnak-google** [comment]
Restored baseline to the value before https://github.com/flutter/flutter/commit/57187b00b2172e7c3e394319764ec95032a0c97f.
