### ISSUE TITLE
Issue from website page Reading and Writing Files

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#19457]
From URL: https://flutter.io/cookbook/persistence/reading-writing-files/

I've try to build a project (Complete eхamplе) and following error is appeares:

```
Launching lib/main.dart on SM G925I in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: /home/misha/IdeaProjects/test_io/android/gradlew app:properties:

BUILD FAILED

Total time: 0.685 secs


FAILURE: Build failed with an exception.

* Where:
Build file '/home/misha/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.1/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':path_provider'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Finished with error: Please review your Gradle project setup in the android/ folder.
```

At the same time, there are no obvious errors (absence of packages, for instance) in the project. All dependencies are resolved. What is the problem?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by brianegan** [comment]
Hey @micrcx -- was this an old project, or did you start a new project? I've had this same trouble since Flutter upgraded to a newer version of Gradle, and the `google` repository might be missing.

You could try following these instructions to see if your Gradle files / project are out of date, and if so, you can follow them to upgrade your app: https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1

**Comment by micrcx** [comment]
It was a completely new project, created from scratch, with the latest version of Gradle. The most interesting thing is: after the failure I re-created the project and no problems with the plugin did not arise. Soon thanks to flutter I'll begin to believe in miracles.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.
