### ISSUE TITLE
Material Bottom Sheet Reveal/Dismiss animation should use a curved animation

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#19469]
Right now the scaffold uses the linear value of the animation controller, which results in a rather abrupt linear animation:
https://github.com/flutter/flutter/blob/c39f2f26f7e74c516060fa3475876de21c38bbf3/packages/flutter/lib/src/material/scaffold.dart#L1710

In the Material Design samples, you can clearly see that the bottom sheets are animated smoothly: https://material.io/design/components/sheets-bottom.html#behavior

The problem is that the animation controller is also to apply the movement caused by dragging the finger, which requires linear interpolation.

**Comment by marcoms** [comment]
Very noticeable going through the Flutter Widget Catalog and seeing lots of cases like this (also on Cupertino). It's hard to view widgets as native feeling when even the animations don't match their Android/iOS counterparts.

I'm in the process of cataloging the most common occurrences of this problem in several widgets so I can create an issue that lists them out for convenience, but so far they are:

## Material

- `BottomSheet` (native: ease-out vs. flutter: linear)
- Buttons, Tappable list items, etc. (native since Android 9: ease-out vs. flutter: linear) -- could be an `InkSplash`/`InkRipple` issue
- `TextField` (native: ? vs. flutter: linear)

## Cupertino

- `CupertinoActionSheet` (native: ease-out-expo vs. flutter: ease-out-cubic?)
- `CupertinoPageRoute` (!) (native: ease-out-expo vs. flutter: basically linear in comparison)
- `CupertinoPicker` (!) (native: ease-out-expo vs. flutter: actually linear)

Some of these marked with '!'s to me looked most jarring. I was a bit more lenient on the Material widgets, since even native apps by Google, at least in practice, don't seem to care whether they use linear/eased animations. The Cupertino widgets however, in their current state differ by quite a large margin, compared to the native alternatives. Animations on iOS are effectively what makes or breaks the experience, so if we get those wrong, it's a dead giveaway that its not a native app.

**Comment by marcoms** [comment]
I made a few screen recording examples and comparisons with native iOS behavior [here](https://photos.app.goo.gl/wqmBTT19wW96QC1c9)

**Comment by jordyvandomselaar** [comment]
I've only just noticed this happening as well. It's really annoying imho. Functionally it works, aesthetically not so much.

**Comment by marcoms** [comment]
With #25788, we added support for many more animation curves that will be much better suited. I can take a look at submitting a PR for this tomorrow.

**Comment by marcoms** [comment]
Made some initial progress at #26825, for those interested :)

**Comment by alyyasser** [comment]
any update for this? the seems to be closed without merged tho
