### ISSUE TITLE
IO thread GrContext memory needs to be cleaned up

### ISSUE THREAD

**Issue by ErosZy** [flutter/flutter#19558]
Original issue title: Android graphics memory can't be reduced when use GridView (maybe leak)

Internal: b/140829916

## Steps to Reproduce

1. create a GridView using GridView.build
2. the GridView's item contains a **CachedNetworkImage** component
3. let item not be keep alive (**addRepaintBoundaries/addAutomaticKeepAlives equal false**)
4. open android project use Android Studio
5. run it profile and open view/tool windows/Android profiler
6. scroll gridview and see graphics memory incrase

**DONT USE EMLUATOR AND DEBUG ENV**

**Comment by ErosZy** [comment]
i saw flutter/engine code, it seems like Image.dispose only clear dart wrapper, but not release skiaImage ?

**Comment by ErosZy** [comment]
i found draw image will make skia add one op, like: 
![image](https://user-images.githubusercontent.com/3158736/42957609-ca2ea9fa-8bb5-11e8-817d-b477945f1cac.png)
i think the op object should be contained image data info, and when ui.image call dispose, it just call clearDartWrapper to release weak ref. its the reason that occurs graphics memory not reduced ?

**Comment by ErosZy** [comment]
First of all, the purpose of my use **CachedNetworkImage** is to not cache the bitmap of the image in native memory (because of ui.image using flutter/engine's image).
Then, The reason why i add the parameters (**addRepaintBoundaries/addAutomaticKeepAlives**) to GridView is let the image can dispose quickly when away from visual area. so that the flutter/engine's image can be released quickly, and only store the items that is in the visible area.
The phenomenon I saw from flutter profile is correct, persistent allocated objects only keep the items that in the visible area, and garbage collecte right and timely.
But the android graphics memory still increases all the time, in the low memory android phone, it will crash because of it.
Now, we cant make a inifinited scrollable gridView or listView. I think this is a terrible problem. anyone can help? @eseidelGoogle

**Comment by eseidelGoogle** [comment]
I'm not sure I fully understand the issue as presented, but @jonahwilliams or @chinmaygarde or @liyuqian might.

**Comment by jonahwilliams** [comment]
@ErosZy To uncache an image you could try releasing it from the cache explicitly - perhaps we need a configuration to do this automatically on image.  For example,

```dart

class ImageTile extends StatefulWidget {
  const ImageTile({Key key, this.url}) : super(key: key);

  @override
  State createState() => new _ImageTileState();
}

class _ImageTileState extends State<ImageTile> {

  @override
  void dispose() {
    // needs to match the url and scale from below
    new NetworkImage(widget.url).evict();
  }
  
  @override
  Widget build(BuildContext context) {
    return new Image.network(widget.url);
  }
}

```

I would also experiment with removing `CachedNetworkImage` as well.

**Comment by ErosZy** [comment]
Thanks @jonahwilliams , whether it is your practice or using **CachedNetworkImage**, it will be released ui.image very timely. But i found the graphics memory always increase when I repeatedly slide gridView. i found  it never be released when i profile using Android Profiler.
![image](https://user-images.githubusercontent.com/3158736/43015677-98201692-8c82-11e8-8b65-daa3605d90d0.png)

**Comment by liyuqian** [comment]
Yes, an example flutter app for us to reproduce your issue would be very helpful!

Also CC  @bsalomon in the Skia team whose name occurred in your screenshot in https://github.com/flutter/flutter/issues/19558#issuecomment-406342149

**Comment by ErosZy** [comment]
Secondly，i also found that the graphics memoryd was released when i press home button to make app exit to the background.

**Comment by liyuqian** [comment]
Maybe this is a bug that's already fixed recently? I used your sample app and the GPU memory does get released. Can you please try the latest flutter from our master branch?
<img width="1459" alt="screen shot 2018-08-01 at 1 42 28 pm" src="https://user-images.githubusercontent.com/22987568/43547735-003ab1a8-9591-11e8-98f5-3150287de12c.png">

**Comment by ErosZy** [comment]
@liyuqian sorry for my late, we tested it and found some improvements, but still didn't see a lot GC like the one shown on your picture. Is your screenshot a GC at runtime or make app exit to the background?

**Comment by liyuqian** [comment]
It's at runtime and I just keep scrolling your sample app back and forth.
One thing that might be different is the network condition. The images are
loading very slowly probably because I'm trying to download images from
some servers in China to my machine in the U.S.. Maybe that leaves more
time and chances for our GC to reclaim the memory? Can you try to pull
images from some U.S. servers, and artificially throttle the network to see
if anything changes?

**Comment by ds84182** [comment]
I've seen this multiple times with my app. Easy way to reproduce is to load a rather large image (in my case I was testing with a 15000x2000 image), render using the image, and then attempt to manually dispose with Image.dispose() and Codec.dispose(). Android Studio's profiler shows an increase in graphics memory usage, but no decrease when a subsequent dispose call is used. Attempting to load the image, dipose, and then load the image again typically ends up with OOM errors being thrown by the GPU vendor's OpenGLES implementation.

Looking at Skia's documentation, it seems that texture memory for SkImages are free'd asynchronously, any time after the image's disposal. Perhaps this is the problem? [Documentation link](https://github.com/google/skia/blob/master/site/user/api/SkImage_Reference.md#SkImage_MakeCrossContextFromEncoded)

Loading other (smaller) images seems to cause the larger image to deallocate (this isn't affected by Flutter's image cache, since I'm loading the image using `instantiateImageCodec`). Maybe Skia doesn't take into account GPU memory usage?

**Comment by ds84182** [comment]
Now I'm 100% sure its a Skia issue. The software renderer uses a more sane amount of memory, averaging 120mb even when scrolling through a grid full of images (loaded over network). Disposals free memory instantly too, the 15000x2000 test image free'd up memory when `Image.dispose()` was called.

**Comment by ds84182** [comment]
I can make a code sample that reproduces the issue, if needed. This one is still affecting me, I've worked around it somewhat by using platform-specific APIs to decode image regions with downsampling.

**Comment by liyuqian** [comment]
@ds84182 a code sample that reproduces the issue would be very helpful. Could you please post it here?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/26837#issuecomment-456675863 might be related

**Comment by cmkweber** [comment]
I'm experiencing this and observe that when changing from GridView to ListView the graphics memory eventually gets reclaimed. With GridView the graphics memory continues to expand as described. It's possible the issue could be found by examining the difference in implementation between GridView/ListView to understand why GridView is keeping references to images it should deallocate. Changing configuration of keepAlive/repaintBoundries has no effect.

**Comment by eseidelGoogle** [comment]
FYI @goderbauer @HansMuller (both of which know GridView/ListView much better than I).

**Comment by ds84182** [comment]
@chinmaygarde How feasible is it to add a Dart service protocol to dump Skia's memory usage with SkTraceMemoryDump? I tested the engine last night to confirm that the issue isn't in the engine, since I can reproduce with a Windows embedder.

**Comment by ds84182** [comment]
I think I might have tracked down the issue. It seems that (in my case) SkImages used in a GridView are always referenced by a SkPicture, even after disposal on the Dart side. Disabling automatic repaint boundaries brings the GPU usage back down to something sensible, since the images are no longer being referenced on the C++ side. This has the downside of reducing overall frame rate, however. I guess the reason why using the software rasterizer fixed the issue was because repaint boundaries don't get used?

**Comment by ds84182** [comment]
For now I've fixed it by rolling my own image cache that calls dispose & disabling repaint boundaries on my GridView.

**Comment by jkurtw** [comment]
b/140829916

**Comment by ds84182** [comment]
@tp Flutter has gotten a lot better in this area recently, mostly due to engine changes to improve image loading and cleanup performance.

For the image cache, I have two different cached since my application deals with low quality and high quality thumbnails. It's a standard least-frequently-used cache with a "time gate" on the low quality cache to prevent thrashing during scroll flings. Both caches are limited to 64mb, but can exceed in some situations (low quality cache loading a lot of images, high quality cache with larger than normal images). The cached images are also reference counted, so only offscreen images are candidates for eviction. (This might be the biggest difference? Flutter allows you to have more images loaded than what the ImageCache reflects. This might allow large images to load multiple times instead of getting cached.)

I've recently reenabled repaint boundaries because I can no longer feel the impact of them being enabled, probably due to another engine change.

**Comment by voiddog** [comment]
Same situation for me. In my app, the graphics memory will touch 4G Size in `Huawei P30 Pro` and then crash @liyuqian 

flutter version: 1.9.1+hotfix.3

**Comment by voiddog** [comment]
@ds84182 Can you tell me which version do you use?

**Comment by Liudiao** [comment]
Same situation. And I made a sample code to reproduce this case. 
When scrolling the grid view very quickly, the graphics memory usage is very high, almost 1G in size, and does not decrease. Sometimes you can touch the 3G size and then the app crashes.

`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Stack(
        children: <Widget>[
          _gridView(context),
        ],
      ),
    );
  }

  Widget _gridView(BuildContext context) {
    ImageCache imageCache = PaintingBinding.instance.imageCache;
    imageCache.maximumSize = 30;
    imageCache.maximumSizeBytes = 50 << 20;
    return GridView.builder(
      itemCount: 1000,
      gridDelegate:
      const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
      itemBuilder: (BuildContext context, int index) {
        return Image.network(
            'http://via.placeholder.com/'
                '${500 + index}x1000',
            key: ValueKey(index));
      },
    ).build(context);
  }
}
`

**Comment by eseidelGoogle** [comment]
FYI @liyuqian @cbracken @iskakaushik (in case this is also manifesting on fuchsia).

**Comment by liyuqian** [comment]
I reproduced the memory issue on MotoG4 with the sample app from https://github.com/flutter/flutter/issues/19558#issuecomment-557021269 with flutter version 7726910a5bc4135a9f1fd497c872c9e5cb1e51b5 :

![image](https://user-images.githubusercontent.com/22987568/69682919-de91e280-1067-11ea-885f-945308e1c587.png)

The issue only happens when I scroll fast. I understand that the GC may be able to reclaim the memory when it's scrolling, but what looks wrong to me is that even if I stopped the scrolling, the memory won't go down to the normal level. It only drops to a higher level, and that level can keeps increasing. For example, I can start fast scrolling with 188.3 MB memory, which increases to 330 MB during the scroll, and only drops to 275 MB instead of 188.3 MB.

Interestingly, if I switched to another app, and switch back, the memory usage will go down to the normal level.

I'll try to write a driver test to add this to our device lab benchmark. Meanwhile, @dnfield , @jason-simmons @chinmaygarde @bkonyi @rmacnak-google : do you know what could be causing this? I think it's definitely related with the image resources.

**Comment by dnfield** [comment]
I have a feeling this is the same bug we were chasing in https://github.com/flutter/flutter/issues/32143

See specifically https://github.com/flutter/flutter/issues/32143#issuecomment-544303867
and https://github.com/flutter/flutter/issues/32143#issuecomment-517501671

From what I recall, Chinmay and I were going to look at something to make sure Skia frees garbage that it wasn't automatically freeing in some cases related to SkImage.  It wasn't entirely clear why Skia was holding on though.

**Comment by ds84182** [comment]
I tried tracking this down once before too, and my only lead was dart:ui Picture objects, which can keep a reference to the underlying image even after the dart:ui Image has been GC'd. I used to be able to consistently reproduce the issue with an example app, but then after a couple of engine rolls the reproduction stopped working.

@liyuqian can you check the amount of dart:ui Pictures in the Dart heap with Observatory?

**Comment by liyuqian** [comment]
@ds84182 : I didn't see many dart:ui Pictures in the Dart heap snapshot.

I do believe the conclusion in https://github.com/flutter/flutter/issues/19558#issuecomment-450303445 is correct: the extra memory is completely from Skia.

However, it's unclear to me who is restricting Skia from clearing such memory. I tried `surface_->GetContext()->purgeUnlockedResources(false)` after each frame as @brianosman suggested, but it doesn't clear the memory.

I've turned https://github.com/flutter/flutter/issues/19558#issuecomment-557021269 into an automated test https://github.com/flutter/flutter/pull/46033, but the same test wouldn't reproduce the memory issue if we're using local images instead of network images (https://github.com/flutter/flutter/pull/46033#discussion_r353967808). So it seems that our network images or image decoding/decompressing code is also contributing to this issue.

What makes memory profiling really difficult is the inconsistency of multiple memory tools. Android studio / adb is giving me one memory reading, which is different from the one that I got from Dart Observatory, and they're both different from the reading in Dart DevTools.

It's not that Android studio / adb is always reporting more memory than the Dart tools as I thought maybe Dart didn't count some native, or GPU objects. Sometimes I see more memory reading from DevTools than Android studio. @terrylucas @cobblest : when you have some spare time, can you please try those 3 tools to profile this memory issue, and see if you can get a consistent reading?

**Comment by liyuqian** [comment]
Update: Dan, Chinmay, and I have further investigated and found that the issue is in the IO `GrContext`. That's why the `purgeUnlockedResources` for the GPU thread `GrContext` doesn't help.

**Comment by dnfield** [comment]
More details:

If you scroll a bunch, watch memory jump way up.
Then rest a second.
Then scroll enough to just load another image.  Memory will purge.

Theory is that Skia is waiting for more activity before purging some resources it holds.  We're not sure why this is since we do this: https://github.com/flutter/engine/blob/9f8e44722a88f4574869ae71e548f1fd30cb1687/shell/common/shell_io_manager.cc#L46

**Comment by dnfield** [comment]
from @brianosman:

1) The IO thread originally has a strong ref, so the texture is "owned" by it's GrContext.
2) Someone initiates a usage of that image on the GPU thread (by drawing the image). This creates a temporary, second ref to the texture.
3) When both of those refs are gone (GPU thread has confirmed it no longer needs the texture, and no one is holding the SkImage), we notify the IO thread's GrContext that it's time to delete the texture. This is done via "message", to deal with the fact that the last ref could be released on the GPU thread.
4) At this point, the message is sitting in the IO thread's inbox, and those messages aren't processed until something jiggles the GrContext again.
Because the IO thread's GrContext doesn't do much other than decoding, that's why triggering another decode causes to free all those stale textures (as soon as we ask the IO's GrContext to allocate a new texture, it first goes through any pending messages).
But calling performDeferredCleanup will have the same effect, and can be scheduled at more regular intervals, hopefully.

We now have a few things that use these message/inbox systems to handle freeing of resources across thread boundaries, and we've discussed adding a mechanism that lets the deletion happen immediately if the last ref is freed on the owning thread (which would be the IO thread in this case). But even if we had that, I think you'd still want the performDeferredCleanup, because otherwise it turns into a race - if the app frees the SkImage before the next frame's flush is done, you still have the last ref released on the GPU thread.

**Comment by liyuqian** [comment]
Terry answered why DevTools and Observatory are reporting [different memory usages][1]: the difference should only exist in memory snapshots because they currently use different mechanisms. It's going to change in the future so they'll eventually report the same data. For the timeline, those two tools should already report the same data now as they're using the same API from the Dart VM.

[1]: https://github.com/flutter/flutter/issues/19558#issuecomment-561832953

**Comment by huyvoduc** [comment]
> @ErosZy To uncache an image you could try releasing it from the cache explicitly - perhaps we need a configuration to do this automatically on image. For example,
> 
> ```dart
> class ImageTile extends StatefulWidget {
>   const ImageTile({Key key, this.url}) : super(key: key);
> 
>   @override
>   State createState() => new _ImageTileState();
> }
> 
> class _ImageTileState extends State<ImageTile> {
> 
>   @override
>   void dispose() {
>     // needs to match the url and scale from below
>     new NetworkImage(widget.url).evict();
>   }
>   
>   @override
>   Widget build(BuildContext context) {
>     return new Image.network(widget.url);
>   }
> }
> ```
> 
> I would also experiment with removing `CachedNetworkImage` as well.

work like a charm. thanks bro, you saved my day
