### ISSUE TITLE
Hot reloading after initState() added.

### ISSUE THREAD

**Issue by skeksk91** [flutter/flutter#19562]
When we add `initState()` newly, then hot reloading exactly does nothing for that.
It is fine logically, but in my opinion, Flutter may recommend user to rebuild it fully in this situation.
How about this? 

_If this affects hot reloading performance, then I think keeping current status is better._

**Comment by mayurdhurpate** [comment]
Yes, it takes quite some time to figure out why exactly initState is not running. All the network call function testing then requires reloading the full app. Would be really great if some way initstate gets handled in hot reload.

**Comment by jonahwilliams** [comment]
Hot reload is state preserving, and we do so by keeping `State` objects around. Since initState is only called when the state object is first created, it won't be called again when reloading. If we tore down every state object, then hot reload would be stateless.

If you want a state object to do something specific during a hot reload, you can also implement [`reassemble`](https://docs.flutter.dev/flutter/widgets/State/reassemble.html) and perform some action there as well.
