### ISSUE TITLE
Exception thrown at runtime is not shown by flutter run output or by IDE, unless you're step-by-step debugging

### ISSUE THREAD

**Issue by wil93** [flutter/flutter#19604]
No exception is shown in the IDE or `flutter run` output, my app just shows the CircularProgressIndicator forever.

The only way to reveal the exception, is to do step-by-step debugging and reaching the line where the error happens (the call to `_getLocation` inside `ranky\lib\event_selection.dart`) and then the IDE will show it.

## Steps to Reproduce

1. Run my application at https://github.com/wil93/ranky
2. Click on the only green button available
3. A loading screen will be shown indefinitely

## Logs

```
[  +65 ms] Connected to _flutterView/0x7eeb1a8298.
[  +15 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[  +59 ms] An Observatory debugger and profiler on FRD L09 is available at: http://127.0.0.1:8100/
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+4694 ms] I/hwaps   ( 7532): JNI_OnLoad
[+1438 ms] I/flutter ( 7532): eventi: 3
```

```
Analyzing ranky...

   info - Unused import: 'package:haversine/haversine.dart' - lib\event_selection.dart:6:8
   info - Unused import: 'package:intl/intl.dart' - lib\event_view.dart:4:8
   info - The value of the field '_event' isn't used - lib\event_view.dart:19:25
   info - Unused import: 'package:flutter/foundation.dart' - lib\model\Participant.dart:1:8
   info - Unused import: 'dart:developer' - lib\model\data.dart:3:8
   info - The value of the local variable 'response' isn't used - lib\model\data.dart:37:7
   info - Unused import: 'package:flutter/material.dart' - lib\supplemental\asymmetric_view.dart:15:8
   info - Unused import: 'package:flutter/material.dart' - lib\supplemental\product_card.dart:15:8
   info - Unused import: 'package:intl/intl.dart' - lib\supplemental\product_card.dart:16:8
   info - Unused import: 'package:flutter/material.dart' - lib\supplemental\product_columns.dart:15:8
warning - The asset assets/ does not exist - pubspec.yaml:36:7

11 issues found. (ran in 15.9s)
```

```
[√] Flutter (Channel dev, v0.5.6, on Microsoft Windows [Versione 10.0.17692.1004], locale en-GB)
    • Flutter version 0.5.6 at C:\flutter
    • Framework revision 472bbccf75 (3 weeks ago), 2018-06-26 17:01:46 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\willi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Users\willi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.15.0

[√] Connected devices (1 available)
    • FRD L09 • 73QDU16B15017567 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by wil93** [comment]
Just to clarify, I get this error even just by running `flutter run` without using any tool (VScode or others), so I'm not sure what is meant by the "tools" tag in this specific case

**Comment by zoechi** [comment]
Hard to tell what part of Flutter is responsible.

![image](https://user-images.githubusercontent.com/405837/43037500-ffb46a8e-8d0d-11e8-82f0-d4827784af1e.png)

I thought this would be good place to start looking for causes.

What exception do you get when you debug step-by-step?

**Comment by wil93** [comment]
I get the exception "Missing location permission in AndroidManifest.xml. You need to add one of ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION. See readme for details." which I reported also here: loup-v/geolocation#36

For some reason, now that I'm trying to reproduce the issue, the exception is not shown even in debug mode. The cursor "stops" at the `throw` line (inside the library I'm using) but the exception message is always "loading..."

![cattura2](https://user-images.githubusercontent.com/1285361/43037716-0fb87580-8d11-11e8-892d-77c31a0d3bb3.PNG)
![cattura4](https://user-images.githubusercontent.com/1285361/43037719-130b7a70-8d11-11e8-8bd7-c64091c4c5a7.PNG)

**Comment by zoechi** [comment]
Is the exception output shown with `flutter logs`?

**Comment by wil93** [comment]
I just noticed that I was using `dev` branch (probably because I was desperately trying to make it work last time I tried).

Now I checked out the `beta` branch again, and did a `git pull` (unnecessary since the last commit there was in May) and tried it again, and I can confirm that I can see the exception only when step-by-step debugging:

![cattura5](https://user-images.githubusercontent.com/1285361/43037848-73fbd702-8d12-11e8-9a68-27e6348cf15c.PNG)

To answer your question: no, `flutter logs` does not show the exception (the last line printed by that command is "eventi: 3" which is my `print()` line in `ranky\lib\event_selection.dart:58` just before the call to the failing library.

When I run with `flutter run` without debugging, the app loads indefinitely, and again the `print()` line is the last thing that is seen in the logs.

**Comment by DanTup** [comment]
I think you might be hitting expression evaluation issues when we're trying to evaluate the `toString()` on the Exception. Could you try on `master`? There have been many expression evaluation fixes so hopefully it's no longer happening.

If it is, could you paste all the red text that's visible in the Debug Console at the bottom of your screenshot (that starts with `compiler message`) and/or [capture a log in VS Code](https://dartcode.org/docs/logging/#capture-logs-command) while reproducing the issue and attach it?

**Comment by wil93** [comment]
I don't know what the issue was, but I can't reproduce it anymore with the latest beta as of today.

**Comment by gderaco** [comment]
Hi there. I'm experiencing the same: the thrown exception is visible in the ide/logs only when the app is started with the debugger attached: if you just run the app the developer is not aware of the exception.

In my case, see the [video](https://www.dropbox.com/s/3rudvmyz2yo6tk4/only-in-debug.mov?dl=0), the exception is thrown because the object doesn't the property _data_ since it's a List object.

_flutter logs_ doesn't report any exception in run nor in debug mode.

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (5 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by DanTup** [comment]
@gderaco Can you repro this in VS Code or from the console? Could you also share a small sample of code that repros it? I can't reproduce it here (with VS Code) but I think it might matter at which point the exception occurs.

**Comment by gderaco** [comment]
Hi @DanTu, thanks for the quick response.
I can confirm that on VSCode happens the same: the exception is notable only when the app is run on debug. I'm not sure about the console.

In order to reproduce the issue add and call this method(first please add _countries.json_ in your library) :

``` 
Future<List<String>> getCountries() async {
  return List<String>.from(json
      .decode((await rootBundle.loadString('countries.json')))
      .ishouldnotbehere
      .map((item) => print("hello-debug"))
      .toList());
}
```
...
Funny thing: while I was writing this comment, now the debug console shows the right error (both on Intellij and VSCode):

_[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: Class 'List<dynamic>' has no instance getter 'ishouldnotbehere'.
Receiver: Instance(length:249) of '_GrowableList'
Tried calling: ishouldnotbehere
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      getCountries (package:flutter_exception_test/main.dart:126:8)
<asynchronous suspension>
#2      _MyHomePageState.initState (package:flutter_exception_test/main.dart:56:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#9      Element.upda<…>_

e.g. this is not consistent. I hope this still may help.

**Comment by gderaco** [comment]
getCountries is called from a widget's initState

**Comment by DanTup** [comment]
@gderaco Sorry for the delay; I'm still unable to repro this with errors in the `initState` method.

Could you share a complete code sample I can run to ensure I'm doing the same, and describe the steps when you see this (eg. is it on first load, a hot reload, a hot restart?). I tried to check your video again, but it's now a 404.

Also please include logs (using the `Dart: Capture Logs` command in VS Code) when you repro it).

Thanks!

**Comment by GyuriMajercsik** [comment]
It's happening for me as well. Is very annoying since I do not know what is the actual error and can't fix it.

**Comment by DanTup** [comment]
@GyuriMajercsik are you able to provide a complete sample I can run, or a log (see my last comment above yours)? Thanks!

**Comment by GyuriMajercsik** [comment]
@DanTup Thanks for the fast reply. It's happening randomly but I will try to get a short sample for you. 
How I can run the Capture Logs command from Android Studio or from command line ?

**Comment by DanTup** [comment]
@GyuriMajercsik Oops sorry, I was in VS Code-mode :) I'm not sure how best to get lots from Android Studio. The command in VS Code collects logs from many sources into a single file which makes it convenient to track down things like this (we see what's happening over the VM service protocol, as well as the Flutter daemon output).

If you can make a sample so I can reproduce it here, that would definitely be the easiest way to track it down (since the logs might not show anything if something is swallowing the error). You could also try enabling breaking on "all exceptions" (this includes handled errors too) and step with the debugger to see if something is catching (and discarding) the error without logging.

**Comment by zanderso** [comment]
@GyuriMajercsik this issue appears inactive, so I'm going to close it. If you're still able to reproduce it and can provide the information that @DanTup requested, please feel free to re-open.
