### ISSUE TITLE
gradle flutter tasks don't seem to mark anything as output

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19626]
Apparently we should be marking something as output, for caching purposes.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by sbaranov** [comment]
@Hixie Is there a specific repro for this particular issue? One problem was fixed by https://github.com/flutter/flutter/pull/20584, where the result of gen_snapshot wasn't cached. I'm certainly seeing it cache things now.

**Comment by Hixie** [comment]
The basic repro is:

1. `time flutter run`
1. (wait for app to start up on device)
1. ^C
1. `time flutter run`

Check that the second flutter run is almost instantaneous.

There's a way to drive gradle using some sort of analysis option which, when I did it by hacking `flutter_tools` locally, indicated that we weren't doing any caching at all for our part of the build.

**Comment by sbaranov** [comment]
First run 24s, second run 8s (kernel file is certainly cached, but asset copying happens for some reason), third run 7s (everything looks cached now). It looks like the problem that you saw has been fixed, except for 1s potential win that we could get from optimizing the asset copying.

**Comment by Hixie** [comment]
It should take mere milliseconds on the second run.

**Comment by dnfield** [comment]
For each instance of flutter run:

1. we run `gradle app:properties` which takes ~1.5s
2. we run `gradle app:tasks` which takes ~1.5s
3. We run aapt to get some information, which seems to only take a 50ish ms
4. flutterBuildDebug task seems to get marked as dirty each time.  Adds 2+ seconds

**Comment by dnfield** [comment]
I'm not sure we can get rid of the `app:properties` or `app:tasks` trivially.  We use those to validate that Flutter's interfacing with a valid gradle project for the tasks we need.  I can't think of a way to get around this short of trying to parse and walk the gradle tree.

I'm trying to figure out why flutterBuildDebug gets marked dirty every time.  We appear to have mostly the right annotations (we mark `verbose` as an input when we probably shouldn't, but otherwise looks ok).

**Comment by dnfield** [comment]
Another alternative is we shortcircuit gradle entirely and just try to determine if the build is dirty ourselves.

**Comment by jonahwilliams** [comment]
With flutter assemble, we now correctly track all inputs and outputs. Because this is done via depfile, gradle still needs a little help determining if something can be skipped.

This issue is succeeded by https://github.com/flutter/flutter/issues/44476, which covers the single case where caching isn't as fast as it could be.
