### ISSUE TITLE
"flutter upgrade" should have a "get me out of trouble" feature

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1963]
I had some local changes, so I did this:

```
ianh-macbookpro:flutter ianh$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 8 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean
ianh-macbookpro:flutter ianh$ git branch -m "old"
ianh-macbookpro:flutter ianh$ git checkout -B master
Switched to a new branch 'master'
ianh-macbookpro:flutter ianh$ git status
On branch master
nothing to commit, working directory clean
ianh-macbookpro:flutter ianh$ flutter upgrade
Flutter from <unknown> (on )
flutter revision: 0494801b173a69121cc36dc32b27b6d68ffa77cf (12 hours ago)
engine revision : 9e1e1fba5474b458458b65f1aa1d0d730af2705b
fatal: no upstream configured for branch 'master'
Unable to upgrade Flutter. No upstream repository configured for Flutter.
ianh-macbookpro:flutter ianh$ 
```

I presumably did bad git here, but flutter upgrade should offer a way to get back on track.

**Comment by gspencergoog** [comment]
When it does try to recover, would you expect it to (ask first! and) do something like `git fetch upstream && git checkout master && git reset --hard upstream/master`?

**Comment by jmagman** [comment]
A `--force` flag was added with https://github.com/flutter/flutter/pull/29192 but it looks like the upstream branch was totally detached, so I'm not sure that should blindly be re-hooked up by the tool since who knows which remote you want origin/master to track (my origin/master tracks my fork, for example).

I'm not sure this can get more magical without decoupling from git.
