### ISSUE TITLE
Add disabled/enabled option for CheckBoxes, Switches and Buttons

### ISSUE THREAD

**Issue by martinjmartinez** [flutter/flutter#19698]
I think this should be implemented. This is something that is needed. The only way this could be done is creating a new CustomWidget.

**Comment by HansMuller** [comment]
Currently controls like CheckBox can be disabled by setting their onChanged/onPressed/etc callbacks to null. Is there are reason that's not sufficient?

**Comment by martinjmartinez** [comment]
@HansMuller  well yes, but visually the users doesn't know that it is disabled.

**Comment by kunit1** [comment]
It's grey when it's disabled. Which should be the standard visual indicator for disabled.

**Comment by HansMuller** [comment]
@kunit1 - that's correct. You can see the disabled versions of selection controls, like checboxes, in the Flutter gallery. For example:

![checkboxes](https://user-images.githubusercontent.com/1377460/43152227-e079aff0-8f22-11e8-9651-ad9d4018844e.png)

**Comment by martinjmartinez** [comment]
Thanks guys!

**Comment by sajidbarcha** [comment]
Even when you set the color to light grey to indicate it is disabled, the user can drag the switch and toggle the switch, is this expected behavior? I want to prevent drag toggle of switch when it is disable. I control the behavior by not doing anything in the onChanged, but the switch still toggles with a drag
