### ISSUE TITLE
Flutter should expose shell handle before rendering begins

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#1976]
Due to a recent change(https://github.com/flutter/flutter/commit/e8a21f5d9174ca0e7f067c4f1c54e66458487e4a), flutter started to expose the shell handle only after rendering begins and runApp has been called.

This is an awkward requirement on flutter applications which are mojo apps, as it causes these apps to connect to other mojo services later in the application life cycle which might not be optimal.

/cc @Hixie

**Comment by abarth** [comment]
You can call runApp as many times as you like.  Why not just call runApp near startup with a Container or something innocuous?

**Comment by alhaad** [comment]
/cc @armansito
The mere fact that we have to do such a thing seems convoluted.

**Comment by Hixie** [comment]
You don't even have to call runApp(). Just initialise the binding. For example if you are using the FlutterWidgetBinding (which you probably are if you're using runApp) then just call "FlutterWidgetBinding.ensureInitialized()" at the top of your main().

But I don't really understand the problem here. Can you elaborate some on what it is you are trying to do before you call runApp()?

**Comment by alhaad** [comment]
For us, we could theoretically just use a flutter app as a mojo app and not draw anything to the screen. In such a scenario, calling anything related to rendering seemed a useless extra step.

Ok, we'll call FlutterWidgetBinding.ensureInitialized() for now.
Closing this issue.

**Comment by Hixie** [comment]
If you're not rendering to the screen at all, then you presumably wouldn't use the widget framework or the rendering framework, and would have a dedicated binding that inherited directly from the one that provides the mojo shell. Such a binding could initialise itself whenever you wanted it to.

The Widget and Rendering bindings want to make sure that they're initialised at the same time as the mojo shell binding because otherwise there's a race condition where the flutter app's dart side has offered services to the C++/Java side, but the dart side hasn't yet actually registered all the services.
