### ISSUE TITLE
Does flutter ship Dart VM along with APK?

### ISSUE THREAD

**Issue by Write4Dinesh** [flutter/flutter#19767]
Hello,
I have seen a platform specific libflutter.so file inside android  apk file. what does this .so file contain? 
is it Dart VM  or Dart Engine? or Skia library code? or Layout renderer written in native code?

Please clarify

Thanks,
Dinesh

**Comment by zoechi** [comment]
Dart does **not** ship the Dart VM in a **release** build, 
but it does in debug builds (this is what makes hot reload possible).

For release Dart is compiled to native binary and it does link some Dart runtime stuff like garbage collection or similar that is also used in the Dart VM.
Skia is also part of the APK.

I don't know what files exactly contain what.

If you need more information can you please elaborate a bit why you want to know that so that others know for example what level of detail you expect.

**Comment by Write4Dinesh** [comment]
Thanks for the reply.
We are a IT professional  services company who work for clients. We compare various mobile frameworks and demo it to clients. hence we need the architecture level of details for Flutter.

We have heard that Flutter doesn't rely on Standard Android Application framework(Activity, Service etc), 
also, in react native, it ships javascript VM in the apk bundle. so, we are thinking does flutter do similar thing by shipping DartVM in every apk. 

so, if you can give us some more details about Flutter Runtime environment, it helps us to compare Flutter with other framework & build Flutter capability in our company.

thanks,
Dinesh

**Comment by zoechi** [comment]
No, Flutter is entirely different to React Native. 
For release Flutter compiles to native binary only contains some runtime library (as mentioned) similar to for example Go.

See also https://flutter.io/faq/#what-technology-is-flutter-built-with

**Comment by Write4Dinesh** [comment]
Thanks zoechi for your response.
One more question.
In flutter framework architecture mentioned  [https://flutter.io/technical-overview/](here), what is **Text** ?
All other components have explanation except "Text" .
you can find it in bottom most layer of the architecture, after "Dart " & "Skia" (with in blue background)

Thanks,
Dinesh

**Comment by zoechi** [comment]
I think it is what is discussed here https://github.com/flutter/flutter/issues/11092
They used text rendering code from Blink (Google Chrome) but switched to libtxt recently.
