### ISSUE TITLE
 X ANDROID_HOME = G:\sdk;       but Android SDK not found at this location. error

### ISSUE THREAD

**Issue by rameshsambu-dev** [flutter/flutter#19805]
I tried in all ways i am trying with android studio this error im getting please help into this

**Comment by zoechi** [comment]
This issue doesn't provide any information that would allow to diagnose.

At first pease add the output of `flutter doctor -v`.

Why do you expect the SDK to be in `G:\sdk;`

> I tried in all ways 

It would be helpful to know what these ways were and how they did not work (error messages, actual behavior, ...)

**Comment by zoechi** [comment]
Cross-link https://stackoverflow.com/questions/51518175/flutter-android-sdk-is-missing-command-line-tools?noredirect=1#comment90031023_51518175

**Comment by rameshsambu-dev** [comment]
C:\Users\Lenovo>flutter doctor -v 
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-US) 
• Flutter version 0.5.1 at C:\flutter 
• Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200 
• Engine revision 1ed25ca7b7 
• Dart version 2.0.0-dev.58.0.flutter-f981f09760 

[X] Android toolchain - develop for Android devices 
X ANDROID_HOME = G:\sdk; 
but Android SDK not found at this location. 

[√] Android Studio (version 3.1) 
• Android Studio at G:\Andorid Studio

**Comment by zoechi** [comment]
How did you install it? Do you have Android Studio installed?

**Comment by rameshsambu-dev** [comment]
yes i have android studio installed.

**Comment by rameshsambu-dev** [comment]
![image](https://user-images.githubusercontent.com/10371244/43243841-18eb6604-90c6-11e8-9f76-2499fabcc720.png)

**Comment by zoechi** [comment]
Can you please post a screenshot of the content of `G:\sdk`?

**Comment by rameshsambu-dev** [comment]
![image](https://user-images.githubusercontent.com/10371244/43244138-4a09db02-90c7-11e8-94a8-11ae20034723.png)

**Comment by zoechi** [comment]
Can you please also post the output of 
```
sdkmanager --version
```
and
```
sdkmanager --list
```

**Comment by rameshsambu-dev** [comment]
![image](https://user-images.githubusercontent.com/10371244/43244583-f23b5f48-90c8-11e8-9a83-16ab9f18317f.png)
sdk manager not recognized but i have sdk manager

![image](https://user-images.githubusercontent.com/10371244/43244594-03ebb878-90c9-11e8-8e72-30bbb6613470.png)

**Comment by rameshsambu-dev** [comment]
this is the fix thankz

**Comment by zoechi** [comment]
Glad to hear \o/

**Comment by bahman2000** [comment]
I am still having the same Issue...
flutter doctor: Android sdk manager tool not found...

**Comment by zoechi** [comment]
@bahman2000 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by harimau99** [comment]
i have the same problem too. 
i already tried few way  with cask or manual download path locate to it. But didn't workout .
I didn't use android studio. i use cli version.

**Comment by zoechi** [comment]
@harimau99 what does `android/local.properties` look like?

**Comment by jitheshkramesh** [comment]
I have the same problem. Yesterday it was worked nicely. But today it's not working.
What's the problem.

**Comment by ipereto** [comment]
I've set up my Android SDK manually with the command line, and I was able to solve this kind of errors while I tried to set up my development environment, if you want to solve it as I did, just follow the next steps:

**In my case I did the process in Windows 10.**

**1.** Download SDK here: [https://developer.android.com/studio](https://developer.android.com/studio)

![image](https://user-images.githubusercontent.com/14301820/55283693-718a4980-532e-11e9-8a9a-cd7a2f84f1bb.png)

**2.** Save and Unzip the file in a new folder, this will be your Android SDK folder, like this:

![image](https://user-images.githubusercontent.com/14301820/55283725-e2c9fc80-532e-11e9-9200-ee1ce73ff2ec.png)

**3.** In your new Android SDK folder go to -> tools -> bin. Open a command line here `Shift + Right-click`  and click to `Open PowerShell window here` and then ...

![image](https://user-images.githubusercontent.com/14301820/55283819-a26b7e00-5330-11e9-9a7e-ab491723f3f4.png)

... run this command: 
`.\sdkmanager.bat "platforms;android-28" "platform-tools" "build-tools;28.0.3"`

After that you will see these new folders and files:
![image](https://user-images.githubusercontent.com/14301820/55283823-cb8c0e80-5330-11e9-95e4-68c973fea770.png)

Now, you have the last version of build-tools, platform-tools, and a platform. If you want to download other available packages you can list them using `.\sdkmanager.bat --list`. For more information about this command go to [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager).

**4.** Finally, set up your PATH variable adding this new packages:

![image](https://user-images.githubusercontent.com/14301820/55283806-3c7ef680-5330-11e9-9a3b-d31fb3803216.png)

**Now you can check your flutter running `flutter doctor` and you will see something like this!**

![image](https://user-images.githubusercontent.com/14301820/55283860-5f5dda80-5331-11e9-9af3-63d9d83831e1.png)

If this message appears, don't be panic!

![image](https://user-images.githubusercontent.com/14301820/55283926-3853d880-5332-11e9-9a10-5051a1be3caa.png)

Just run this command:

`flutter doctor --android-licenses`

**I hope this can help anyone need it! Bye!**

**Comment by ipereto** [comment]
> I have the same problem. Yesterday it was worked nicely. But today it's not working.
> What's the problem.

Hi! Go to the answer I just wrote, maybe it can help you.
https://github.com/flutter/flutter/issues/19805#issuecomment-478306166

**Comment by MUHAMMEDILYAS** [comment]
Thanks,its all working well !!!

**Comment by elidoran** [comment]
Thank you @ipereto 

The shortest version of that solution is:  _use sdkmanager to download the necessary tools_.

The short version of that solution is after downloading and unzipping the android CLI "tools", which has `sdkmanager`, run `sdkmanager --list` to see the available stuff and then download the most recent ones for **platforms**, **platform-tools**, and **build-tools**.

Example:

    sdkmanager platform-tools "platforms;android-29" "build-tools;29.0.0"

I unzipped the sdk CLI into ~/dev/android 
Which created:  `~/dev/android/tools`
After using sdkmanager to download the three things above I had:

    ~/dev/android/tools
    ~/dev/android/build-tools
    ~/dev/android/platform-tools
    ~/dev/android/platforms
    ~/dev/android/licenses

I also set `ANDROID_HOME` to the absolute path for `~/dev/android`.

And I added to my PATH the absolute path for `~/dev/android/tools/bin`.

I think the Android Studio docs maintainers assume everyone is installing the whole IDE instead of the CLI because it doesn't explain this stuff on its download page. I also think it's strange it unzips into "tools" instead of "android/tools" considering running sdkmanager downloads stuff into the **parent directory** of "tools". What if I had not unzipped it into its own "android" directory I created ahead of time? Would it have downloaded stuff into the parent directory still? without even asking?

Anyway, back to flutter... it may be helpful for "flutter doctor" to check if the android sdk tools are available and suggest using sdkmanager to download the three required packages because just saying it can't find the android sdk is confusing. I didn't realize it wasn't saying the tools weren't there; it was saying I hadn't used the tools (sdkmanager) to download the packages flutter wants. So, a nudge in that direction in the flutter doctor message would help... in my opinion.

Again, thank you @ipereto for the solution.

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/flutter-does-not-find-android-sdk-2

**Comment by milanpatel18** [comment]
Already solved at https://github.com/flutter/flutter/issues/15114#issuecomment-541346856

**Comment by torxebec** [comment]
> Please try adding `G:\sdk\tools` and `G:\sdk\platform-tools` to the `PATH` environment variable.

Just loved this line @zoechi

**Comment by SarausAlZoren** [comment]
![image](https://user-images.githubusercontent.com/60129337/96321770-3901ac00-1049-11eb-80b3-cbf2a4b6803b.png)
how should i solve this ?
