### ISSUE TITLE
Overhauling Slider Widget

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#20026]
Hi,

I wanted to use a Slider in my current project and stumbled upon several weaknesses in the current design:

1. [x] #19216 The current design that you have to use a SliderComponentShape if you want to customize the Thumb of a Slider is non intuitive and against the way Flutter typically builds its widgets. I would have expected to have the option to pass the size of the thumb and a builder function that gets the current slider value an returns a Widget that draws the Slider.
In the current approach I'm suddenly confronted with painting on a Canvas. If you want to output a Text inside the Thumb you need a TextPainter too. Not easy for starters and not in the Flutter philosophie of composing widgets. 

2. [ ] Your SliderComponentShape gets the current Slider value as percentage and not the absolute value although you pass limits to the Slider constructor as absolute Values.

3. [ ] If you set a minimum Value you suddenly get fractional value steps if you defined steps for the Slider. 

4. [ ] If you have a big range of values the linear curve of the slider isn't enough there should be an exponential curve too that allows small intervals for small values and then bigger steps.

5. [ ] A way to pass unit Widgets that get displayed at the correct position below or above the Slider.

All of the above should also be supported by the coming `RangeSlider`.

**Comment by zoechi** [comment]
1. #19216 seems related

**Comment by escamoteur** [comment]
Ah yes I haven't even thought of the customizing the Slider track, I think it makes sense to have all in here.

**Comment by slightfoot** [comment]
Here for reference: https://github.com/boeledi/RangeSlider

**Comment by clocksmith** [comment]
4 and 5 should now be possible with the current API for the single slider

For 1, the Slider does not contain any sub widgets because it contains a RenderBox. There are many good examples of painting with the default shapes. I will also be updating the gallery with even more examples.

@escamoteur Can you confirm that the new shape painters can accomplish cases 4 and 5?

2 is also by design of the shape painters

For 3, I am not following 100%, but it seems like its working as intended by rendering tick marks after setting divisions. Is something else expected?
