### ISSUE TITLE
How to remove a dev_dependencies physically, which is as 「yarn remove」in nodejs

### ISSUE THREAD

**Issue by jianggaocheng** [flutter/flutter#20071]
When I add a dev_dependencies in pubspec.yaml and exec "flutter package get", the package will be downloaded to my PC, and I can not delete the file when I remove the dev_dependencies  in pubspec.yaml. 
Is there any way to remove the dev_dependencies file physically when I do not need it?

I was a node.js programmer before, in node.js, I just using 「yarn add PACKAGE_NAME@PACKAGE_VERSION」 to add a dependencies, and it will change the package.json file by itself. And when I exec 「yarn remove PACKAGE_NAME」, the package file will be deleted physically. 

I think the way of node.js may be better, because it save my hard disk storage. And in flutter, there will be more and more dependencies files during my use of flutter.

**Comment by zoechi** [comment]
There is no such thing, but it's easy to 
just delete the directory in `~/.pub-cache/hosted/...`.

`pub` uses a shared cache, this means other projects of the same user might still depend no that package, even when your current project doesn't anymore.  
This also means that `flutter packages get` after adding `dependency:` or `dev_dependency:` might not need to download anything because it might be already in the cache.

If you still think a feature request is justified, then it should be created in https://github.com/dart-lang/pub/issues

**Comment by jianggaocheng** [comment]
Okay, I understand what you mean, 
I think may be we can manually decide it's a global dependency or just private dependency.
I will create a feature in dart-lang.
Maybe dart should try make the package manager function like node.js. It really a bit complex that I need to modify pubspec.yaml by myself.

**Comment by zoechi** [comment]
When you created the issue in https://github.com/dart-lang/pub/issues can you please post a link and close this one?

**Comment by jianggaocheng** [comment]
@zoechi Yeah, I really enjoy the dart-lang and flutter, I hope it will be more and more populate, It's a very cool way for developer to build cross platform apps.

I have create a issue.
[Remove the package file physically when I remove it from dependency](https://github.com/dart-lang/pub/issues/1959)
