### ISSUE TITLE
coverage doesn't counts asserts as executed anymore 

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#20149]
```sh
flutter test --coverage
```
now shows all assert as not executed anymore.

 (dart2) $ flutter doctor -v
[✓] Flutter (Channel master, v0.5.8-pre.215, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.215 at /Users/zoechi/flutter/flutter
    • Framework revision eda03e2586 (5 hours ago), 2018-08-02 12:02:32 +0200
    • Engine revision a76054f4b6
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/43596691-5135d250-9680-11e8-8409-cada10901560.png)

**Comment by jason-simmons** [comment]
The coverage report now includes a record for `assert` statements indicating that these lines were not executed.  Previously there was no record for `assert` lines.

This change was introduced in https://github.com/dart-lang/sdk/commit/079bebb78bf148c4baa31b0f06e5a6fddc6faaf9

@bkonyi

**Comment by bkonyi** [comment]
It looks like observatory is behaving correctly, with `assert`s being included in the coverage summary when `--enable-asserts` is passed. Based on your screenshot @zoechi, I'm guessing you're running into this on coveralls.io?

**Comment by zoechi** [comment]
@bkonyi it's with coveralls.io. It worked fine before there.

If they are registered as executed with `--enable-asserts`, 
I think they should be registered as not-executable code when `--enable-asserts` was not passed instead as not executed.
What do you think?

**Comment by bkonyi** [comment]
@zoechi, thanks for confirming. You're totally right: if `--enable-asserts` is passed we should expect the `assert` statements to be included in coverage, otherwise they shouldn't be. Since the observatory is displaying things properly, I'm wondering if coveralls.io is a bit more picky about token positions since the position provided by the CFE points to the expression within the `assert` not the beginning of the `assert`. I'll investigate whether or not that's the case and see if an additional token position for assert statements would be sufficient to resolve this.

**Comment by zoechi** [comment]
How do I pass `--enable-asserts` to `flutter test --coverage`?
`--enable-asserts` doesn't seem to be a recognized option for `flutter` or `flutter test`

**Comment by zoechi** [comment]
Asserts are now green again.

**Comment by apaatsio** [comment]
I'm seeing this problem with Flutter 0.82. Coverage doesn't count passing asserts.

![passing-assert-not-covered-by-tests](https://user-images.githubusercontent.com/195210/46264115-f085fd00-c518-11e8-8503-cf6a5f827ef7.png)

This issue was closed so is this now fixed in the master branch or **what was the resolution**?

**Comment by zoechi** [comment]
I closed it because I couldn't reproduce it anymore.
I'd suggest you create a new issue because yours looks different. 
Only some asserts are shown as not executed.
