### ISSUE TITLE
GestureArena class name is confusing

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#202]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 14, 2015 at 20:47 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1618_

----

GestureArena is confused about whether it is an arena with multiple matches, or if it's a group of arenas. We seem to use "arena" to mean both interchangeably right now.

**Comment by abarth** [comment]
What should we call it?  GestureDisambiguatior ?  GestureResolver ?

/cc @krisgiesing

**Comment by krisgiesing** [comment]
_GestureArenaState is really the singular GestureArena class (but it's private).

GestureArena today is a map of keys to _GestureArenaState, i.e. it's a global lookup table of arenas.

I would typically rename _GestureArenaState to GestureArena (or _GestureArena if it stays private), and GestureArena to GestureArenaManager.  But we don't tend to use *Manager in Flutter code, so it might be odd to introduce that nomenclature just for this one case.

Another option is to give GestureArena a static lookup method that returns a GestureArena, and make the methods close(), sweep(), hold(), and release() not take a key anymore.  But that introduces lifetime issues since the caller might hold onto a GestureArena longer than necessary.

**Comment by Hixie** [comment]
GestureArena and GestureArenaManager seems fine to me. It's an improvement over the current state.

**Comment by Hixie** [comment]
We should also consider whether to continue making GestureArenaManager (currently GestureArena) pretend that it uses arbitrary keys (as opposed to integers), with GestureRecognizer (the subclass of GestureArenaMember) knowing that they're really ints. We should probably merge GestureArenaMember and GestureRecognizer and move to just saying int everywhere. We're not getting anything from pretending that keys can be arbitrary objects.

**Comment by krisgiesing** [comment]
Agreed; and in fact the notion that the ints are pointer IDs turned out to be pretty important when I was working in this code a few months ago, so I might vote to be even more explicit.
