### ISSUE TITLE
flutter outdated everytime I run vscode

### ISSUE THREAD

**Issue by touseefbsb** [flutter/flutter#20257]
my flutter development editor is vs code and I have installed the dart and flutter extensions into it as well, also have linked the path to the flutter sdk folder. Ican work and run my apps just fine but the problem is everytime I run the vs code editor a notification pops up saying ur flutter is 68 days old, and the next day the day increments to say 69 days old and so on. I click on that and terminal runs the flutter upgrade command and then in logs I can see it says "already up to date" and then it runs flutter doctor and everything seems fine.

**Comment by DanTup** [comment]
The behaviour of the update checking has been improved but the version you're on still has the old behaviour (which is to nag you when it seem like the version of Flutter you have is well out of date). It wasn't expected/planned that there would be no beta update this long but some blocking bugs came up.

If you really want to stop the prompt, you could switch to the `dev` channel until there's a new beta release which includes newer code (and real update checks instead of just assuming if there may be updates based on date).
