### ISSUE TITLE
Linux workstations don't have fn keys

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2036]
A standard keyboard on a linux workstation does not have a “fn” key. Setting a breakpoint with “fn + F9” is confusing. Do you mean just F9? It seems to work.

**Comment by qchong** [comment]
Fixed in the codelab source.
The new text reads as follows:

2. Locate the line where you want to set a breakpoint, click on it, then press the shortcut key to set the breakpoint. The shortcut to toggle the breakpoint on or off depends on the operating system of the development machine you are using:
- Mac: fn+F9 
- Linux: F9

**Comment by qchong** [comment]
Marking as closed.

**Comment by devoncarew** [comment]
@qchong, we also have a right-click menu item now (on an editor) to toggle breakpoints. Will be available in the next plugin version.
