### ISSUE TITLE
In step 5 it doesn’t explicitly mention to set the routes in FirechatApp to create a ChatScreen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2039]
In step 5 it doesn’t explicitly mention to set the routes in FirechatApp to create a ChatScreen. I missed this detail and had to look at the snapshots to find it

**Comment by qchong** [comment]
Fixed in the codelab doc source. Added a new paragraph that reads:

"To specify the default screen that the user sees in your app, set the ’/’ entry in the routes property. The route entry points to a component that defines the UI. The component consists of a  Scaffold widget that has a simple Toolbar as its child widget. "

**Comment by qchong** [comment]
Marking as closed.
