### ISSUE TITLE
Firestore - where array contains 

### ISSUE THREAD

**Issue by adriancmurray** [flutter/flutter#20489]
Is there a way to access the API for Firestore instances which query a collection like the JS implementation : array-contains?

https://firebase.google.com/docs/firestore/query-data/queries#array_membership

@Hixie @sethladd  @xster -> thoughts?

**Comment by adriancmurray** [comment]
Actually, I don't need this... found a way around it. Cheers!

**Comment by BerndWessels** [comment]
I really need this feature too. It will allow for a much better design and might even save money due to less document reads.

In general it would be great to support all firestore features as soon as they are available to avoid that flutter developers feel like second class citizens of firebase.

**Comment by buntagonalprism** [comment]
Hi @Daibaku0615 indentation is important in your pubspec.yaml file - that issue looks like an indentation problem where pub can't parse the options properly. Make sure its indented as follows:
```
dependencies:                                                 # 0 spaces
  flutter:                                                    # 2 spaces
    sdk: flutter                                              # 4 spaces
  cloud_firestore:                                            # 2 spaces
    git:                                                      # 4 spaces
      url: git://github.com/buntagonalprism/plugins.git       # 6 spaces
      path: packages/cloud_firestore                          # 6 spaces
      ref: firestore_array_contains                           # 6 spaces
```

**Comment by buntagonalprism** [comment]
@michael87 After I ran the following to update the firestore pod I was able to successfully build and deploy to iOS simulator, and verify that array-contains functionality is also working as expected on iOS in my fork. 
```
cd ios
pod update Firebase/Firestore
```

While this manual update worked, I feel it would be better if the `cloud_firestore` plugin specified the minimum `Firebase/Firestore` pod version it required so that other people don't need to run this manual update. But none of the other podspec files among the other Flutter plugins specify exact versions for their pod dependencies as far as I can tell, so I'm not sure what the best approach is.

**Comment by Daibaku0615** [comment]
Sorry for late response.
It worked thank you so much!

**Comment by zoechi** [comment]
Looks like https://github.com/flutter/plugins/pull/760 is supposed to fix that.

**Comment by pulyaevskiy** [comment]
@zoechi yes. Also PR is merged and released as `0.8.0`.

**Comment by adriancmurray** [comment]
Looks like this is now a non-issue so I'm closing this... issue.

**Comment by adriancmurray** [comment]
@pulyaevskiy I was hoping an official release would happen soon! Now, when using ArrayContains it's returning all documents in the collection rather than just the ones that match the ArrayContains query. 

```
await _db.collection('collection').limit(limit).where('arrayField',
				arrayContains: string).getDocuments().then((result){
//do stuff with the result
}
```

I've created a composite index but that doesn't help me. I'm doing something wrong.

**Comment by pulyaevskiy** [comment]
@adriancmurray For me it would be hard to tell what's wrong in your case.

I've noticed that (at least on iOS) Firestore SDK is kinda unstable in some cases. Like I don't always get events for local changes. Or when I delete a document manually in Firebase Console I'd still get it in query snapshots, which seems like SDK cache is not invalidated for deletes (the only solution I found for this is to uninstall the app from Simulator, restart it and run the app again).

There is also the whole thing about queries and security rules which if your query even _potentially_ can include a document which it has no access to it will not be executed and will fail. Though if you are listening on snapshots stream you won't see any errors and it'd simply return empty snapshots.

I've just tested `arrayContains` again in my app and it does seem to work as expected for my query:

```dart
var query = firestore
        .collection(path)
        .where('things', arrayContains: thingId)
        .where('serverTimestamp', isGreaterThan: lastUpdatedAt)
        .orderBy('serverTimestamp', descending: true);
```

I'd probably recommend to clear all caches (including flutter clean), make sure that your Firebase/Firestore pod is at least 5.5.0 or later, restart simulator and try again. Check security rules as well (though if it returns everything it seems unlikely because of the rules).

**Comment by adriancmurray** [comment]
@pulyaevskiy the Firebase/Firestore pod update fixed it for me. I forgot that was required. Thank you very much for your help!

**Comment by HerrNiklasRaab** [comment]
Is something like this possible yet? https://stackoverflow.com/questions/52905836/how-to-query-nested-objects-in-firestore/52906042#52906042

**Comment by pulyaevskiy** [comment]
@HerrNiklasRaab arrayContains is supported, though you’ll have to test it yourself if it works with complex objects.

**Comment by GRTO** [comment]
I see until now there is no way to filter elements using Firestore when the condition is "Filter elements where it starts with ..."

**Comment by Frozmen** [comment]
Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.

**Comment by kroikie** [comment]
@adriancmurray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/714. Any further collaboration will be done there.

**Comment by adriancmurray** [comment]
@kroikie thanks, though this is a non-issue now. The plug-in has been updated to support this type of query.

**Comment by FQuouhadiho** [comment]
> Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.

I'm looking for a thing like that. Please take me informed if you find a solution.

**Comment by Frozmen** [comment]
> > Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.
> 
> I'm looking for a thing like that. Please take me informed if you find a solution.

Unfortunately, did not find :(

**Comment by FQuouhadiho** [comment]
> > > Is it possible to somehow filter the query by `arrayNotContains`? I can not find something similar in the documentation.
> > 
> > 
> > I'm looking for a thing like that. Please take me informed if you find a solution.
> 
> Unfortunately, did not find :(
> The only way now, I guess, its query all items and check if the array contains specific elements on a client. Or as an alternative create cloud function if it's possible.

That's what I did. But I wonder what will happen if there plenty things to get from the server, it will take long time to executing. But I didn't use cloud function, maybe it will be the best way. Thanks a lot.
