### ISSUE TITLE
"flutter test" no longer gives a nice message when you don't depend on flutter_test

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#20600]
If you removed the flutter_test dependency in your pubspec.yaml and then ran flutter test, we used to give you a nice message. It doesn't seem to do that any more.

Tested by running "flutter test" in dev/bots (by accident...).

**Comment by srsudar** [comment]
I see a helpful message.

```
$ flutter --version
Flutter 0.7.1-pre.30 • channel unknown • unknown source
Framework • revision 7f0f938de7 (8 hours ago) • 2018-08-27 11:11:14 +0200
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
```

And after deleting the `flutter_test` dep from a project's `pubspec.yaml`:

```
Running "flutter packages get" in flutter_project...
00:00 +0: loading [snip]/flutter_project/test/widget_test.dart

Failed to load test harness. Are you missing a dependency on flutter_test?

00:00 +0 -1: loading 
[snip]/flutter_project/test/widget_test.dart [E]
  Failed to load "[snip]/flutter_project/test/widget_test.dart":
  Compilation failed
  Test: [snip]/flutter_project/test/widget_test.dart
  Shell: [snip]/flutter_path/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester


00:00 +0 -1: Some tests failed.
```

**Comment by Hixie** [comment]
Interesting, I wonder what's different about running `flutter test` in `dev/bots`...

**Comment by srsudar** [comment]
It looks like it is because the first failed compiler message in `dev/bots` is for the package `flutter_test`, whereas the [helpful message is printed when the missing package is `test`](https://github.com/flutter/flutter/blob/eab5cd9853c13ec2207977d9b9ef7b6750fe0817/packages/flutter_tools/lib/src/test/flutter_platform.dart#L216):

Here is the first line of output I get when running `flutter test` in `dev/bots`:

```
compiler message: Error: Could not resolve the package 'flutter_test' in 'package:flutter_test/flutter_test.dart'.
```

After removing `flutter_test` from the `pubspec.yaml` in a project like [flutterflip](https://github.com/RedBrogdon/flutterflip), however, I get the friendly warning. The swallowed compiler message is:

```
compiler message: Error: Could not resolve the package 'test' in 'package:test/src/runner/plugin/remote_platform_helpers.dart'.
```

I'm not sure why the difference exists, or if it is important.

**Comment by Hixie** [comment]
Hm, interesting. I guess the simplest fix is just to look for both.

**Comment by jonahwilliams** [comment]
As of today this is fixed:

```
00:00 +0: ...s/jonahwilliams/Documents/flutter/examples/hello_world/test/hello_test.dart     
Compiler message:


Failed to load test harness. Are you missing a dependency on flutter_test?

```

**Comment by ishaileshmishra** [comment]
what is the fix of : Compiler message:
Failed to load test harness. Are you missing a dependency on flutter_test?
