### ISSUE TITLE
MaterialPageRoute only works in modal way on Android, not iOS

### ISSUE THREAD

**Issue by zinwalin** [flutter/flutter#20673]
```
Navigator.push(
            context,
            new MaterialPageRoute<Null>(
                builder: (context) => new CameraVideoScreen()),
          );
```

When run on Android, it push new screen from bottom to top, but on iOS, it's still push from right to left. 

Here's flutter env I use: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.5 17F77, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by lukepighetti** [comment]
I believe that is expected behavior.

**Comment by xster** [comment]
Can you describe your expected behavior? The page transition follows the platform convention. If you want a different platform's convention, you can also override Theme.platform or more generally `defaultTargetPlatform`. 

If you want a modal page transition while in iOS context like a viewcontroller present style bottom up slide, you can also push a PageRoute with fullscreenDialog = true.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
