### ISSUE TITLE
More deterministic measurement of memory consumption

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#20690]
The engine -> flutter roll in https://github.com/flutter/flutter/commit/9299c02cf708497d6f72edda8efae0bb8340660e triggered a significant regression in the flutter_gallery__memory_nav benchmark.

@rmacnak-google Do you think this could have something todo with recent GC heuristic tuning?

**Comment by rmacnak-google** [comment]
Hm, the harness only waits for a print from Dart, so even before Nathan's change this would be racy.

**Comment by Hixie** [comment]
Do you have any suggestions on how we can make this less racy? I'm eager to make this benchmark more reliable.

**Comment by rmacnak-google** [comment]
Wait for the engine to have an empty message loop or return from Dart_NotifyIdle.

**Comment by Hixie** [comment]
I don't think we expose either of those from Dart, unfortunately.

**Comment by nathanrogersgoogle** [comment]
Hi all, thanks for catching this and bringing it up.
Where can I view the flutter_gallery__memory_nav benchmark mentioned above?  Also, are there instructions on how to run it locally?
Without actually having looked at the exact test, it sounds like this is a testing logic coordination issue, as opposed to an actual user facing regression?  Is the delayed idle notification actually getting a chance to run before taking a measurement?
Let me know if that isn't the case, and if there's anything I can do to help out.
In any case, I don't think we should think of mid animation 100ms GC pauses as something we are willing to do in order to decrease memory consumption.

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test_memory/memory_nav.dart is the memory test app, and the benchmark data is reported via https://github.com/flutter/flutter/blob/a7d954e/dev/devicelab/lib/tasks/perf_tests.dart#L388

**Comment by cbracken** [comment]
Renamed, since I believe the feature we're looking for here is a more deterministic means of measuring memory consumption. e.g., being able to force a GC right before measurement. 

Note: I believe the allocation profile service call used to support such a thing, though the `forceGC` parameter may have been more of a `requestGC` in practice. @rmacnak-google would know.

**Comment by godofredoc** [comment]
Closing as obsolete
