### ISSUE TITLE
Modal bottom sheets should not dismiss on tapping the sheet body

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#20720]
Currently showModalBottomSheet() allows dismissing the displayed sheet by tapping on its body. 
The modal bottom sheet should not dismiss upon tapping the general body.

See https://material.io/design/components/sheets-bottom.html#modal-bottom-sheet, modal bottom sheets can only be dismissed by:
- Tapping a menu item or action within the bottom sheet
- Tapping the scrim
- Swiping the sheet down
- Using a close affordance within the bottom sheet’s top app bar, if available

I can work around this with an opaque noop gesture detector around the sheet widget, but the default behavior ought to conform to material spec.

**Comment by Narumikun** [comment]
I'm troubling with the problem too, I wonder how you use the GestureDetector to solve the dismissing of bottom sheet when tapping its body? Could you please show me a simple code example? Thanks a lot.

**Comment by yathit** [comment]
I also agree with this. Model bottom sheet should not closed, because tap does indicate interest in model, not intention to dismiss.

**Comment by deekay42** [comment]
This is still happening for me.

**Comment by sunnyseeds** [comment]
Agreed. Model sheet should close if tapped outside but not inside unless directed to do so.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by marinat** [comment]
Dear developers, let users decide how bottom sheet will react on tap on it's body

**Comment by jaumard** [comment]
Why just not having this configurable with a dismissable field by default to false to be material compliant?

**Comment by darrenaustin** [comment]
While this isn't technically a breaking API change, in order to fix this we would be changing the current behavior of the bottom sheet implementation. For those interested I posted a breaking change announcement here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/flutter-announce/9m39PZCAKkM

Feel free to add to this ticket to provide feedback.

**Comment by darrenaustin** [comment]
> Why just not having this configurable with a dismissable field by default to false to be material compliant?

We could add a `dismissOnTap` boolean field, but that would add complexity to the API for a feature that most apps would never want, and for those that do, it is simple to implement themselves.

**Comment by njovy** [comment]
@darrenaustin I am currently displaying a content with a Scaffold inside a modal bottom sheet because I had to use a snackbar. If I wrap my content with GestureDetector, it displays nothing. Scaffold handles showing a Snackbar, scrolling upon textfield focuses, etc. so I need to use this widget. Is there any workaround for this case?

**Comment by Timbabs** [comment]
HI @darrenaustin When will this change be releases?

**Comment by dpedrinha** [comment]
IMHO anything modal should be dismissed only grammatically. When a developer pops anything modal he does it precisely to prevent user interaction with whatever is behind it, so he should have control on how to dismiss it.
I was trying to use a modalbottomsheet to show some info while performing some async background work and I expected it to force the user to wait for it to finish but he can just tap anywhere on the screen, close the modalbottomsheet and mess with the entire workflow I expected (finish loading data before being able to edit it).
Same goes for modal dialogs.
