### ISSUE TITLE
MultiChildLayoutDelegate getSize should be called whenever shouldRelayout returns true.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2077]

**Comment by Hixie** [comment]
in what situation is it not?

**Comment by apwilson** [comment]
it's only ever called once as far as I can tell.  So in all situations.

**Comment by Hixie** [comment]
@abarth The problem is that `markNeedsLayout()` doesn't imply a change in how a render box will react to constraints, so we just end up calling `_layoutWithoutResize()`. @apwilson wants to have a `performResize()` that gets recalled each time we call `markNeedsLayout()`.

I guess we could call `parent.markNeedsLayout()`. That would be relatively expensive. We could have a getter on `MultiChildLayoutDelegate` that says whether `getSize()` might change behaviour for the same constraints.

**Comment by abarth** [comment]
RenderCustomMultiChildLayoutBox shouldn't be sized by parent.  In order to be sized by parent:

```
  /// Whether the constraints are the only input to the sizing algorithm (in
  /// particular, child nodes have no impact).
```

This isn't true for RenderCustomMultiChildLayoutBox because there are other inputs.

**Comment by Hixie** [comment]
Yeah, that's probably the right way to fix it.

**Comment by apwilson** [comment]
I don't understand what you guys are talking about - so is it something I need to fix on my side or something on your side?

**Comment by Hixie** [comment]
Our side.
