### ISSUE TITLE
Should global constants be prefixed with `k` ?

### ISSUE THREAD

**Issue by arlindiDev** [flutter/flutter#20858]
The Flutter style guide recommends prefixing global constants with 'k', https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k , 

But the Effective Dart style guide recommends not using prefix letters in such cases https://www.dartlang.org/guides/language/effective-dart/style#dont-use-prefix-letters .

The reason why not to use prefixing is because its part of Hungarian notation which is useless and just adds information to variable names which is already defined in the variable declaration. Here is a longer explanation https://jakewharton.com/just-say-no-to-hungarian-notation/

If I am writing a flutter app should the 'k' prefix be used or not?

**Comment by sir-boformer** [comment]
Obviously it's your decision. A matter of taste. If you want you can even name them `cONSTANT`.

**Comment by zoechi** [comment]
> which is best for readability

is usually personal taste or what you are used to.

In general it is not a good idea to use a `k` prefix for all const fields.
In Dart all kinds of things can be const, for example only for performance reasons, and changing the implementation a bit to fix a bug or add a feature might require removing `const` and
it would be extremely cumbersome to need to rename part of the public API as well because of such a change that might otherwise not be breaking or not for all users.

As far as I know in Flutter only constants that are real constant "magic" values are prefixed with `k`.
It's still up to you how you want to handle that. It might depend on the kind of code you write, library, framework, app, ...

**Comment by zoechi** [comment]
I'm going to close this because I don't expect the Flutter team to take an action here
like making an official recommendation or similar.
Feel free to continue the discussion though.

**Comment by chen-yumin** [comment]
I initially had the same question but eventually decided to follow the [Effective Dart style guide](https://www.dartlang.org/guides/language/effective-dart/style#dont-use-prefix-letters) and do not prefix constants with `k`. The Effective Dart style guide makes much more sense.

The [Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k) is only for contributions to the Flutter project (the framework itself and its sample code), and not for Flutter applications. 
 
Same as the [style guide for contributions to the Android Open Source Project (AOSP)](http://s.android.com/source/code-style.html#follow-field-naming-conventions) requiring prefixing variables with `m` and `s`, while Google explicitly and actively forbids Hungarian notation in their public [Java style guide](https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names), and when writing Android apps we do not add prefixes because we are not writing code for AOSP. Same reasoning here.
