### ISSUE TITLE
Would like an example of sending an image across PlatformChannels

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#20879]
Came up in flutter-dev:
https://groups.google.com/forum/#!topic/flutter-dev/okDxZcKmL2I

Seems like a reasonable request.

**Comment by zoechi** [comment]
I run into such a scenario when I implemented a share feature so that other apps can share an image to my app. 

I used something like
```java
InputStream stream = getContentResolver().openInputStream(sharedImageUri);
if (stream != null) {
  result.success(readBytes(stream));
}
```
to send the image data from Java to Dart.

I tried to avoid reading the file in Java and copying the image data to the Dart side to just write the file back to disk in Dart just to be able to upload to Firebase Cloud Storage, but failed to get a file path from the `sharedImageUri`. Not sure this is possible.

The Firebase plugin then got support added to upload data from memory so this became less of an issue.

**Comment by v7lin** [comment]
why not to support Stream?

e.g.
```
InputStream stream = getContentResolver().openInputStream(sharedImageUri);
if (stream != null) {
  result.success(stream);
}
```

**Comment by kf6gpe** [comment]
@RedBrogdon Is this something that devrel would be interested in doing? Trying to figure out how to triage.

**Comment by sososdk** [comment]
Any Update? It's useful when the device can provide a file path on android Q.

**Comment by RedBrogdon** [comment]
CC: @AyushBherwani1998 

We're actually in the process of planning a new platform channel sample for coding this summer. Can you describe the issue you're running into with Android Q a little more?

**Comment by AyushBherwani1998** [comment]
@RedBrogdon I guess this can be a good example to show how to move different data across platforms.

**Comment by RedBrogdon** [comment]
Are we still lacking the iOS side of the implementation? IF so, we should leave this open until that gets done (if not by you then by someone else).

**Comment by AyushBherwani1998** [comment]
Oh yeah, sorry, forgot about the iOS side completely. Keeping it open makes sense.
