### ISSUE TITLE
Flutter app restarts when it is launched again from Recent apps after few seconds

### ISSUE THREAD

**Issue by Soumyajit19** [flutter/flutter#20897]
I wrote my fairly simple flutter app and was testing in debug mode in my device. However when I try to relaunch the app again from recent apps of my device the app restarts, no state is saved for the app(even if I relaunch after few seconds).

**Comment by audkar** [comment]
Flutter doesn't support state saving on Android.

**Comment by Soumyajit19** [comment]
Can we expect flutter to support state saving in future releases?

**Comment by zoechi** [comment]
What state do you expect to be saved?
You can save state yourself on lifecycle callbacks.
Also in debug mode restarting the app might not work if you used hot-reload because changes applied using hot-reload are not added to the APK, they are applied only in-memory to the Dart VM.

**Comment by zoechi** [comment]
Flutter doesn't maintain state for you, you need to do that yourself.
You need to decide what state you want to persist, perist it, reload it, re-apply it after loading (like navigating to a route)

**Comment by audkar** [comment]
Maybe you know any examples how default Navigator state can be persisted?

All navigation in application is implemented with `Navigator.push(Route)`

Even official Flutter gallery doesn't maintain its navigation state.

**Comment by willvlad** [comment]
+1 This is an important feature to have in an app. It'd be good if there was some guidance somewhere how to persist the navigation state. 
User experience deteriorates massively if one has to re-fill say a long form just because they left the app to look up something on a different app and then returned just to find themselves back to square 1...

**Comment by goderbauer** [comment]
It sounds like this is a duplicate of https://github.com/flutter/flutter/issues/6827. Please feel free to re-open with additional details if this issue is in fact about something not covered by the linked issue. Thanks!

**Comment by patelkrunal78** [comment]
You can also use the runApp(new MyWidget) function to do something similar

This is what this function does:

Inflate the given widget and attach it to the screen.

The widget is given constraints during layout that force it to fill the entire screen. If you wish to align your widget to one side of the screen (e.g., the top), consider using the Align widget. If you wish to center your widget, you can also use the Center widget

Calling runApp again will detach the previous root widget from the screen and attach the given widget in its place. The new widget tree is compared against the previous widget tree and any differences are applied to the underlying render tree, similar to what happens when a StatefulWidget rebuilds after calling State.setState.

https://icetutor.com/question/flutter-how-to-force-an-application-restart-in-production-mode
