### ISSUE TITLE
Would like to have pana coverage as part of testing for flutter/plugins

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#20923]
Not all of our plugins 100% pass pana (dart package analyzer).  Seems like something our flutter/plugins post-commit testing should cover?

Currently for example android_alarm_manager doesn't pass:
https://pub.dartlang.org/packages/android_alarm_manager#-analysis-tab-
(FYI @bkonyi)

FYI @cbracken

**Comment by cbracken** [comment]
Agreed -- seems like a great idea.

/cc @gspencergoog who's been doing a ton of improvements in our plugins testing infra in the last couple weeks.

**Comment by bkonyi** [comment]
The `android_alarm_manager` plugin *should* be working, but since it's utilizing functionality that has only been published in master pub just thinks that those methods don't exist. I imagine this should be resolved once we publish our next release preview.

Either way, +1 for checking this with post-commit testing.

**Comment by stuartmorgan** [comment]
Closing as we're don't a lot of package analysis in CI now; I don't think pana would provide much added benefit and has some issues for our use case (like trying to enforce lints where we've deliberately chosen a different option).
