### ISSUE TITLE
How to update baked in dart SDK

### ISSUE THREAD

**Issue by HardVeur** [flutter/flutter#21001]
In root directory of flutter app: flutter upgrade
-->
``` 
Upgrading Flutter from $HOME/opt/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in app-dir...           
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because app-dir depends on http_server >=0.9.8 which requires SDK version >=2.0.0-dev.61.0 <3.0.0, version solving failed.
pub upgrade failed (1)
``` 
<--

Output of flutter doctor -v 
-->
``` 
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale de-DE)
    • Flutter version 0.5.1 at $HOME/opt/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at $HOME/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = $HOME/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
``` 
<--

I strongly believe the dart version which is baked in and comes with flutter is the problem. I recently updated my general dart sdk to 2.0.0 but I realised that flutter uses a own dart sdk. I could downgrade all dependencies by my own but that can't be the way to go. Their must be a way to update the baked in dart sdk or at least connect it with my general dart sdk and not with flutters own. Is there a way to upgrade the flutters dart sdk?!

**Comment by DanTup** [comment]
You can't just change/upgrade the Dart SDK used by Flutter because it needs to match the version in the engine and also the local code may not work on a different SDK (for example, switching to a newer SDK that runs everything in Dart-2 mode when the Flutter framework code is not expecting will likely result in crashes).

As @zoechi says, if you really need to update you'll need to switch to a newer version of Flutter. For example, you could switch to [the `dev` channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#dev)) which at the time I'm writing this is only a few days old (note: `dev` may be less stable than `beta` but you can always change back if you do hit blocking issues).

Otherwise, you could remain on older versions of packages that don't require the new SDK until the next beta update.
