### ISSUE TITLE
How can I make each tab in BottomNavigationBar have a separate Navigator?

### ISSUE THREAD

**Issue by jaggerwang** [flutter/flutter#21022]
## Situation

My app has following screens:

**BootstrapScreen**: bootstrap app, do somethings like check login status, no BottomNavigationBar
**HomeScreen**: first tab of BottomNavigationBar
**DiscoverScreen**: second tab of BottomNavigationBar
**MeScreen**: third tab of BottomNavigationBar

I want to keep each tab's navigation state when switch between tabs. Right now I'm using the default navigator's `pushAndRemoveUntil` to switch between tabs. This method will rebuild the target tab, and loose previous state, like ScrollView's scroll position. There are a few screens not belong to the any tab, like BootstrapScreen. So there need a parent navigator on top of all tab's navigator.

**Comment by liwenDeng** [comment]
maybe this will helpful [navigators-with-bottomnavigationbar](https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf)

**Comment by jaggerwang** [comment]
@liwenDeng Thanks! I have read this article before, but it's implementation seems to be very complicated. Is there any simple implementation?

**Comment by HansMuller** [comment]
Apps structured this way were blocked by some difficult bugs which have (finally) been  fixed, for example
https://github.com/flutter/flutter/pull/27365 and https://github.com/flutter/flutter/pull/29188.

With the latest version of Flutter (as of now, the "tip of tree" master branch), creating an app with nested navigators should just work.  There's an example here, https://github.com/flutter/flutter/issues/31483#issuecomment-486344199, with a BottomNavigationBar instead of tabs.
