### ISSUE TITLE
Support Snap as a distribution option on Linux

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#21062]
We should consider using snaps to distribute on Linux. They're pretty trivial to set up and maintain and can be easier/more flexible than using deb/rpm/etc. **I'd be happy to look into it** but wanted to know if there were plans for 1.0 that would make this a non-starter?

More info: https://snapcraft.io

**Comment by Hixie** [comment]
Generally speaking I would expect you would want Flutter in userspace, not in the system directories, so it's not clear that any package manager is really suited (as opposed to just checking it out from git or using the prepackaged tarballs).

**Comment by andrewebdev** [comment]
Looking at how flutter is installed it seems like a snap for this will be insanely easy. Think I might snap it as a test over the weekend.

I'm new to flutter, but I always look for snap packages before I install any other way. Snaps are so very convenient. With that said I know that android studio and flutter has some synergy (Android Studio does have a snap package already). Depending on how flutter and android studio works together, it may be necessary to create services and/or plugs to connect the two snaps, because of the confinement model.

**Comment by lanzorg** [comment]
It seems there is a snap here: https://github.com/kenvandine/flutter-snap

**Comment by lukef** [comment]
Looks like this was done. https://snapcraft.io/flutter
