### ISSUE TITLE
Remove "in checked mode" from documentation.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#21066]
From @jacob314 : "In the Flutter doc comments there are a lot of comments that start with "In checked mode" which should probably be updated to be consistent with Dart 2.
Dart 2 doesn't have a concept of checked vs unchecked mode. In Dart 1, unchecked mode meant ignore all type checks as well as ignore asserts.
In Dart2, --enable-asserts turns on asserts which is technically correct for these comments but a bit of a mouthful."

We should update any doc comments that reference "checked mode" with something appropriate.

**Comment by eernstg** [comment]
I'd say that any reference to checked mode that is concerned with a user-written `assert` statement should refer to `--enable-asserts`, and all other references to checked mode should be removed (because the topic would then be checks added implicitly in checked mode with Dart 1, and those checks are _always_ added to the program in Dart 2, so we just stop talking about any particular mode, and keep the rest of the text unchanged).

**Comment by Sfshaza** [comment]
In case someone wants to review (@gspencergoog, @eernstg), here's the short PR: https://github.com/flutter/website/pull/1191

Checked mode wasn't used much on flutter.io. It may be used more on docs.flutter.io.

**Comment by eernstg** [comment]
I just added a single comment about the description of `assert` statements.

**Comment by zoechi** [comment]
I still found a few
https://www.google.at/search?q=site%3Aflutter.io+%22checked+mode%22&oq=site%3Aflutter.io+%22checked+mode%22&aqs=chrome..69i57j69i58.7153j0j7&sourceid=chrome&ie=UTF-8

- https://docs.flutter.io/flutter/material/MaterialApp/debugShowCheckedModeBanner.html
- https://docs.flutter.io/flutter/quiver.testing.runtime/assertCheckedMode.html
- https://flutter.io/docs/testing/debugging
- https://docs.flutter.io/flutter/material/MaterialApp/debugShowMaterialGrid.html
- https://docs.flutter.io/flutter/widgets/CheckedModeBanner-class.html
- https://docs.flutter.io/flutter/flutter_test/benchmarkWidgets.html
...
