### ISSUE TITLE
flutter build --build-number=x --build-name=y doesn't update build.gradle anymore

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#21146]
When I run
```
 flutter build apk --release -t lib/main_origin.dart --build-number 19 --build-name 0.9.3
```
`versionCode` and `versionName` in `android/app/build.gradle` should be updated with these values.
The last time I used this and it updated successfully was a few weeks ago already on `master` or `dev` channel.  
Now these options don't seem to have any effect.

[✓] Flutter (Channel master, v0.7.2-pre.18, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.7.2-pre.18 at /Users/zoechi/flutter/flutter
    • Framework revision 2b14ac1efc (24 hours ago), 2018-08-27 22:17:22 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by zoechi** [comment]
Yup, `android/app/build.gradle` needs manual update.

**Comment by HerrNiklasRaab** [comment]
Hey zoechi,

At the moment I am in the situation, of creating a CI Pipeline for build and deployment with flutter. For this, I am using Fastlane and Travis CI. The expected behavior should be, after a check in, the Travis build starts, calling "flutter build apk" and "flutter build ios". Now the versioncode should bump. And push the new versioncode to the repository. But calling "flutter build apk --release -t lib/main_origin.dart --build-number 19 --build-name 0.9.3" does not update the versioncode. 

Can you explain this little bit more detailed please ?

Niklas

**Comment by zoechi** [comment]
Have you tried with a new project (`flutter create foo`)?
Some related files in `android/` have changed not too long ago, and you would need to update your existing files there.
You can also just delete `ios/` and `android/` and run `flutter create .` and re-apply manual changes.

**Comment by pboos** [comment]
I have a project with the new structure in the android/app/build.grade that reads from local.properties. The problem is, that local.properties does not get updated. As well checked if the final apk has the correct values. But they are the same as in local.properties.

I as well tried creating a new project with `flutter create foo`. There the android/app/build.gradle seems the same and local.properties does not get updated either.

Commands I tried:
```
flutter build apk --build-name 1.2.3 --build-number 99
flutter build apk --build-name=1.2.3 --build-number=99
```

```
Flutter (Channel beta, v0.11.9, on Mac OS X 10.14.1 18B75, locale en-CH)
```

**Comment by HerrNiklasRaab** [comment]
What i did, what worked is. Remove the version number from the pubspec.yml. Then the commands above are working. In Ci i use this script to bump the version:

```
major=$(<ci/majorversion.txt)
minor=$(<ci/minorversion.txt)
patch=$(<ci/patchversion.txt)
version=$(<ci/versioncode.txt)
echo "$major"
echo "$minor"
echo "$patch"
echo "$version"
patch=$((patch + 1))
version=$((version + 1))
echo "$patch"
echo "$version"
echo $patch > ci/patchversion.txt
echo $version > ci/versioncode.txt
echo $(<ci/patchversion.txt)
echo $(<ci/versioncode.txt)```

**Comment by zoechi** [comment]
I can reproduce. This worked for me but doesn't anymore in a new project.
@pboos can you please create a new issue. This one is closed since a while.
