### ISSUE TITLE
How can i make a table's header or column fixed

### ISSUE THREAD

**Issue by okjesse** [flutter/flutter#21165]
something like 
[jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer](https://www.jqueryscript.net/demo/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer)

Thanks

**Comment by okjesse** [comment]
Thank you~~

**Comment by werytert** [comment]
So, how can i do it? i cant understand

**Comment by kismet-** [comment]
I've tried making some changes to the workaround, I'm looking to make only the header row sticky (fixed). I have some issues when scrolling, the header row scrolling is out of sync with the data table.


![stick header](https://user-images.githubusercontent.com/1946071/67509992-c5a5a400-f659-11e9-82fd-1772f9d035e7.gif)

**Comment by Goostavo** [comment]
Nice work!

This is happening because the top table (header) and main table have different sizes and column count. That makes them out of sync.

Looking at [DataTable code](https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter/lib/src/material/data_table.dart) i've found out that the width is build using `tableColumns[displayColumnIndex] = const IntrinsicColumnWidth(flex: 1.0);` to make them dynamic acordingly to the content.

On the end it uses: 
```dart
    return Table(
      columnWidths: tableColumns.asMap(),
      children: tableRows,
    );

```

I'll try to fork the DataTable object and use this `columnWidths`

**Comment by pablobarrera** [comment]
I updated my answer on StackOverflow with a `CustomDataTable` where you can set the data to fill the table and the width of the cells. I think with this you can get an idea of how to improve it:
[Fixed column and row header for DataTable on Flutter Dart](https://stackoverflow.com/questions/58398787/fixed-column-and-row-header-for-datatable-on-flutter-dart/58467209#58467209)

**Comment by kismet-** [comment]
Hi @pablobarrera, I'm trying to follow your solution, how can we use the `_rowsCells`, `_fixedColCells`, and `_fixedRowCells` ? As these are not widget list.

**Comment by pablobarrera** [comment]
I updated the custom widget to receive any lists of data and an optional cellBuilder, you can see in the example how to use it. I also added the option to set the height of the cells. 
[Fixed column and row header for DataTable on Flutter Dart](https://stackoverflow.com/questions/58398787/fixed-column-and-row-header-for-datatable-on-flutter-dart/58467209#58467209)

I won't keep improving it because is just a workaround, as I mentioned in the answer, we're hiding headers of DataTable. It would be good if we could remove headers on DataTable, so this could be a better solution. Anyway, you're free to use it and improve it the way you want.

**Comment by kf6gpe** [comment]
Closing as this discussion should occur on Stack Overflow or one of our support channels at http://flutter.dev/support. Thanks for using Flutter!

**Comment by deadsoul44** [comment]
Could you please reopen the issue? It should be possible to fix table header.

**Comment by maxim-saplin** [comment]
JIC, I've taken appart DataTable and PaginatedDataTable, made the changes to **fix top/header row** and published these versions as a separate package: https://pub.dev/packages/data_table_2

**Comment by edilson14** [comment]
i found [this](https://pub.dev/packages/syncfusion_flutter_datagrid), it solve my problem
