### ISSUE TITLE
get packages failed

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#21321]
Because every version of flutter_test from sdk depends on string_scanner 1.0.4 which doesn't match any versions, flutter_test from sdk is forbidden. So, because flutterapp depends on flutter_test any from sdk, version solving failed. pub get failed (1)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by zoechi** [comment]
Updating to a newer Flutter version should solve that.

**Comment by lizhuoyuan** [comment]
sdk6.0 and 7.0 did not solve it…

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and your `pubspec.yaml` file.

**Comment by haoyoucai** [comment]
i have same issue


flutter doctor -v

E:\ASWorkSpace\TN2\flutter_app2>flutter doctor -v
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 0.6.0 at E:\Android\flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\DanLai\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: E:\ProgramFile\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\ProgramFile\Android\AndroidStudio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at E:\ProgramFile\JAVA\IntelliJ IDEA 2018.1.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • M3s • Y15QKCPM22DTF • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 1 category.

pubspec.yaml

name: flutter_app2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

**Comment by zoechi** [comment]
Sounds like #20809

**Comment by lizhuoyuan** [comment]
sdk 0.51 is ok

**Comment by zoechi** [comment]
I assume this issue is stale. 
Please let us know if you're still seeing this.
