### ISSUE TITLE
Platform questions, Not an Issue!

### ISSUE THREAD

**Issue by jaakidup** [flutter/flutter#21357]
Hi there.

I heard that there is something in the pipeline to add web support to the output platforms, something like javascript, maybe polymer-PWA? 
Flutter is really nice for ios and android, but if it could output for the web as well, it would be amazing.

Any news on this topic. 
(ps. sorry for asking here, wasn't sure where to ask)

**Comment by zoechi** [comment]
That is explicitly stated as a non-goal for now. Theoretically this could change in the future.
If you keep the view layer as thin as possible you could still share a lot of code with AngularDart and only would need to reimplement the view layer in AngularDart.

Closing because there is nothing to do for the Flutter team.
