### ISSUE TITLE
Firebase Dynamic Links cannot open links if application is already running

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#21456]
There's a number of issues with this plugin:

- [x] The example should illustrate how to follow a link and open the new page. 
- [x] When the application is already running, it is not possible to retrieve the deep link. 

Details for 1: Right now it requires user to paste the link to an application like Keep and click on it. Ideally the link displayed on the page should be clickable (see url_launcher plugin).

Details for 2: `initState` is not called so the link cannot be retrieved. I tried retrieving it in various lifecycle events of the State and came up empty. It also seems like the `resume` lifecycle event is not generated which might imply Firebase is handling this case differently than the usual Android lifecycle.

**Comment by bparrishMines** [comment]
@mehmetf I created a PR that allows you to click and copy the link for 1. 

But for 2, the lifecycle event works works for me if you open the link from a non-browser app. I think this is how it is supposed to work, since this restriction exists for iOS as well. It also never works on iOS simulator. I'm not sure if this is true for android emulator too.

Also, I get this weird error

```
E/libEGL  (11220): eglMakeCurrent:806 error 3002 (EGL_BAD_ACCESS)
E/flutter (11220): [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
E/flutter (11220): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
```

when clicking on the short link from the example on Android. I'm not familiar enough with the engine yet to know how to interpret this.

**Comment by mehmetf** [comment]
We should get help from Firebase team on this. I don't think it should matter where you access the link from. A deep link is supposed to open up a certain page in your app regardless of from where you clicked on it and what state the app is in (running vs not running vs not installed).

**Comment by mehmetf** [comment]
Can this be closed now?

**Comment by bparrishMines** [comment]
Yes, this was fixed with https://github.com/flutter/plugins/pull/1569. Closing.

**Comment by kroikie** [comment]
@mehmetf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/670. Any further collaboration will be done there.
