### ISSUE TITLE
VScode autoformat intending spaces

### ISSUE THREAD

**Issue by lkhgvsuren** [flutter/flutter#21476]
I tried to auto-format my code in vscode with a flutter extension. And this gave me this result
![capture](https://user-images.githubusercontent.com/41112144/45130479-784b4680-b1bb-11e8-96a6-504127fbcda3.PNG)
Sometimes it uses 2 spaces, and sometimes it uses 4 spaces. Is this working correctly?

**Comment by zoechi** [comment]
Dart code formatting is usually done with https://github.com/dart-lang/dart_style. Please check the docs and FAQ there and raise issues there is such remain.

The difference between 2 and 4 spaces is usually whether a new statement/expression begins or a statement/expression is broken into multiple lines because of line length limit.

**Comment by zoechi** [comment]
@DanTup please have a look, just to be sure I don't tell anything misleading.
(IntelliJ also has some of it's own formatting behavior independent of dartfmt during editing, don't know if VSCode has as well)

**Comment by DanTup** [comment]
This is correct. The VS Code plugins use the `dart_style` formatter (via the language server shipped in the Dart SDK). These results will match if you run `dartfmt` on your code.

If you'd like to see a customisable formatter, please add a 👍  to https://github.com/Dart-Code/Dart-Code/issues/914. It's not currently being worked on (and there are technical barriers to replacing the formatter) but having a good idea of the demand for it will help inform things.
