### ISSUE TITLE
Android Poor performance of FlutterView in RecycleView

### ISSUE THREAD

**Issue by kamssun** [flutter/flutter#21485]
Poor performance  because of `FlutterView extends SufaceView` 。
so how to solve this problem ， i have to use `FlutterView` in `RecycleView`。

**Comment by ds84182** [comment]
Using a FlutterView inside of a RecyclerView or any other scrolling list is not a good idea, just like how using a WebView inside of a RecyclerView isn't a good idea.

**Comment by kamssun** [comment]
but i have to do this. Do you have any other  idea about  many flutterView and android View in a scrolling list ?

**Comment by kamssun** [comment]
can you give me some suggestions @cbracken  @ds84182 。

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
