### ISSUE TITLE
Race in VideoPlayer initialization

### ISSUE THREAD

**Issue by nichtverstehen** [flutter/flutter#21483]
Video player widget is not sometimes displayed in an application that essentially follows [the example code](https://github.com/flutter/plugins/tree/master/packages/video_player#example) for VideoPlayer plugin.

Sequence of events:
1. VideoPlayerController is created asynchronously.
2. The widgets builds. But since the controller has not yet finished asynchronous initialization at this point, VideoPlayer widget [renders to nothing](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/lib/video_player.dart#L430).
4. VideoPlayerController finishes initialization, but VideoPlayer wants to hear nothing of it. It keeps showing a blank Container.

Unfortunately, making VideoPlayer stateful and making it rebuild itself once the controller becomes initialized doesn't immediately help.

Sequence of events:
1. Dart VideoPlayerController is created: https://github.com/flutter/plugins/tree/master/packages/video_player#example
2. It [calls](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/lib/video_player.dart#L203) plugin "create" method asynchronously.
3. VideoPlayerPlugin [creates](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L98) ExoPlayer.
4. Exoplayer initializes quickly and calls [onPlayerStateChanged](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L161)
5. VideoPlayerPlugin tries to send initialized event to Dart, but there is [nothing listening](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L215).
6. Dart VideoPlayerController [starts listening](https://github.com/flutter/plugins/blob/f98d0d010ea38bb68f2d39afc8c2be3a610b8b97/packages/video_player/lib/video_player.dart#L257) to the events on the channel.

But it's too late. It missed the initialized event. So...

8. The listener is not invoked and VideoPlayer is never rebuilt with the correct texture.

**Comment by recastrodiaz** [comment]
I guess you can close https://github.com/flutter/plugins/pull/692/files and https://github.com/flutter/flutter/issues/19953 . I wonder if there is still a race condition on the iOS version of the video_player plugin though.

PS: I would really appreciate if you could have a look at [this PR](https://github.com/flutter/plugins/pull/690). It needs a rebase after this update but I would otherwise love to get your feedback on it.

**Comment by sigurdm** [comment]
For reviewing the PR I will defer to @cbracken as he is now maintaining the plugins

**Comment by Abgaryan** [comment]
The video_player plugin fails to play videos (sometimes)
logs:
```
W/ACodec  (12738): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  (12738): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (12738): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(12738): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(12738): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(12738): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/ACodec  (12738): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  (12738): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (12738): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(12738): Codec reported err 0xfffffff4, actionCode 0, while in state 1
E/ExoPlayerImplInternal(12738): Playback error.
E/ExoPlayerImplInternal(12738): com.google.android.exoplayer2.ExoPlaybackException
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/ExoPlayerImplInternal(12738): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/ExoPlayerImplInternal(12738): 	at android.os.Looper.loop(Looper.java:180)
E/ExoPlayerImplInternal(12738): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(12738): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(2, null, video/avc, -1, null, [640, 360, -1.0], [-1, -1])
E/ExoPlayerImplInternal(12738): 	... 9 more
E/ExoPlayerImplInternal(12738): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(12738): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(12738): 	at android.media.MediaCodec.<init>(MediaCodec.java:1796)
E/ExoPlayerImplInternal(12738): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1769)
E/ExoPlayerImplInternal(12738): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:415)
E/ExoPlayerImplInternal(12738): 	... 8 more
W/MediaCodec-JNI(12738): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(12738): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
```

**Comment by TahaTesser** [comment]
Hi @nichtverstehen 
Is this issue still valid?
Thank you

**Comment by nichtverstehen** [comment]
I don't know. I fixed this issue on Android in https://github.com/flutter/plugins/pull/767, but this issue was kept open to verify and fix iOS. If no one has done this then this is still not done.

**Comment by ngoctranfire** [comment]
I think this issue is still happening. I'm on the latest video_player and I noticed this is still happening as well too!

**Comment by kw2019ltd** [comment]
same issue

video_player: ^0.10.11+1

I/ACodec  (15445): ignoring message as already freed component: AMessage(what = 'omxL', target = 52) = {
I/ACodec  (15445):   int32_t generation = 1
I/ACodec  (15445):   RefBase *messages = 0x75611e0650
I/ACodec  (15445): }
W/MediaCodecRenderer(15445): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(15445): android.media.MediaCodec$CodecException: start failed
W/MediaCodecRenderer(15445): 	at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(15445): 	at android.media.MediaCodec.start(MediaCodec.java:2159)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(15445): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(15445): 	at android.os.Looper.loop(Looper.java:214)
W/MediaCodecRenderer(15445): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(15445): Playback error.
E/ExoPlayerImplInternal(15445): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(15445): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(15445): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(15445): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(15445): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(15445): 	... 9 more
E/ExoPlayerImplInternal(15445): Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(15445): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(15445): 	at android.media.MediaCodec.start(MediaCodec.java:2159)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(15445): 	... 10 more
D/SurfaceUtils(15445): connecting to surface 0x757de5a010, reason connectToSurface
I/MediaCodec(15445): [OMX.qcom.video.decoder.avc] setting surface generation to 15815691
D/SurfaceUtils(15445): disconnecting from surface 0x757de5a010, reason connectToSurface(reconnec

**Comment by adamdupuis** [comment]
I am also having this issue, same version as @kw2019ltd. Any solutions?

**Comment by P-B1101** [comment]
i have problem with video_player with offline mode. (only iOS)
i can play video with url but when i download that file and try to play it, nothing happens.
every thing is fine in android.
it wont throw exception.

**Comment by maheshmnj** [comment]
Hi @nichtverstehen,
Is the issue still valid with the latest ```video_player: ^2.0.8```?

**Comment by nichtverstehen** [comment]
Mahesh, https://github.com/flutter/flutter/issues/21483#issuecomment-599622727 is still valid. If no one has fixed the issue on iOS then it's still an issue.

**Comment by neelansh-creatorstack** [comment]
I faced a similar issue. When there are multiple video players in the list, and doing `scrollController.scrollTo()` to the top, rebuilds widgets in the list. Hence a race condition happens and all the players just show a black square container. Even a new video cannot be played, leaving the app useless.

**Comment by jmagman** [comment]
Possibly fixed on iOS with https://github.com/flutter/packages/pull/7194. I know this bug is ancient, but anyone still seeing this: can you try on latest video_player? This code has changed quite a bit since this bug was filed.

**Comment by stuartmorgan-g** [comment]
Absent new reports since the rework of initialization, closing.
