### ISSUE TITLE
AndroidView crashes trying to re-set a gesture recognizer's team

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#21514]
When an AndroidView is rebuilt, and is handed the same gestureRecognizer instance it was handed on the previous build, it will try to re-set the gesture recognizer's team field, which fails an assertion and crashes.

Repro test case (can be run as part of widgets/platform_view_test.dart):
```dart
  testWidgets('AndroidView rebuilt with same gestureRecognizers', (WidgetTester tester) async {
    final FakePlatformViewsController viewsController = new FakePlatformViewsController(TargetPlatform.android);
    viewsController.registerViewType('webview');

    final AndroidView androidView = AndroidView(
      viewType: 'webview',
      gestureRecognizers: <OneSequenceGestureRecognizer>[ new EagerGestureRecognizer() ],
      layoutDirection: TextDirection.ltr,
    );

    await tester.pumpWidget(androidView);
    await tester.pumpWidget(const SizedBox.shrink());
    await tester.pumpWidget(androidView);
  });
```

This crashes with:
```
The following assertion was thrown building AndroidView(state: _AndroidViewState#e73f5):
'package:flutter/src/gestures/recognizer.dart': Failed assertion: line 196 pos 12: '_team == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      OneSequenceGestureRecognizer.team= (package:flutter/src/gestures/recognizer.dart:196:12)
#3      _AndroidViewGestureRecognizer.gestureRecognizers= (package:flutter/src/rendering/platform_view.dart:238:18)
#4      new _AndroidViewGestureRecognizer (package:flutter/src/rendering/platform_view.dart:213:10)
#5      RenderAndroidView.gestureRecognizers= (package:flutter/src/rendering/platform_view.dart:105:30)
#6      new RenderAndroidView (package:flutter/src/rendering/platform_view.dart:69:10)
#7      _AndroidPlatformView.createRenderObject (package:flutter/src/widgets/platform_view.dart:250:11)
#8      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4288:28)
...
```

I'm not sure what was the reason to forbid re-setting a `OneSequenceGestureRecognizer`'s team I would think it should be possible as long as the previous team is not currently participating in an arena. (@Hixie do you happen to know if there's some other reason to forbid changing a gesture recognizer's team I'm overlooking?)

**Comment by Hixie** [comment]
I would recommend using an API like that used by RawGestureDetector to avoid actually recreating the gesture recognizers (since that would result in bad UI in the case of build being called during a gesture) and to avoid any risk of the gesture recognizers being mismanaged (it's very easy to not cache/dispose of these objects).

That said, even with an API like RawGestureDetector's, you're still going to hit this bug.

To answer your question, I can't see a good reason. If we want to support this, we should definitely add asserts to make sure that the team itself is ok with members leaving (e.g. assert that _combiners is empty). How do you guarantee that no arena is involved with the team when the gesture recognizers change?
