### ISSUE TITLE
ListView instances of same class scroll together instead of separately 

### ISSUE THREAD

**Issue by eturk1** [flutter/flutter#21574]
When using the same ListVIew class on several pages of a BottomNavigationBar, scrolling one list then going to another tab, the other lists are scrolled to the same position. 

I discovered this because I'm using a BottomNavigationBar with three Listviews of ExpansionTiles (my class used 3 times & different content). If I expand a tile on one tab, the same index number ExpansionsTile is expanded. Seems when the same class is used on multiple tabs, the scroll & state is shared. Weird. Or did I just do it wrong?

![ezgif-3-a9328b88e2](https://user-images.githubusercontent.com/525280/45244255-e2dbaf80-b2ab-11e8-858c-4eb872ad651c.gif)

Quicky main.dart for testing:
```
import 'package:flutter/material.dart';

void main() => runApp(new App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scroll Problem',
      home: Home(),
    );
  }
}


class Home extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _HomeState();
  }
}


class _HomeState extends State<Home> {
  int _currentIndex = 0;
  final List<Widget> _children = [
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab1  $index');
      },
    ),
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab2  $index');
      },
    ),
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab3  $index');
      },
    ),

  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Flutter App'),
      ),
      body: _children[_currentIndex], // new
      bottomNavigationBar: BottomNavigationBar(
        onTap: onTabTapped, // new
        currentIndex: _currentIndex, // new
        items: [
          new BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Home'),
          ),
          new BottomNavigationBarItem(
            icon: Icon(Icons.mail),
            title: Text('Messages'),
          ),
          new BottomNavigationBarItem(
              icon: Icon(Icons.person),
              title: Text('Profile')
          )
        ],
      ),
    );
  }

  void onTabTapped(int index) {
    setState(() {
      _currentIndex = index;
    });
  }
}

```

**Comment by eturk1** [comment]
thanks @zoechi for joining this to #18832 so quickly!
I wasn't able to find the issue in search

**Comment by Hixie** [comment]
cc @chunhtai

**Comment by chunhtai** [comment]
This issue seems related to #18832, but it is different, #18832 is related to nestedscrollview, which is a different scenario, we can chat more about it in that thread.

For this one, what you have seen is expected.

I have a tl;dr solution here.

```
import 'package:flutter/material.dart';

void main() => runApp(new App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scroll Problem',
      home: Home(),
    );
  }
}


class Home extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _HomeState();
  }
}


class _HomeState extends State<Home> {
  int _currentIndex = 0;
  final PageStorageBucket bucket = PageStorageBucket();
  final List<Widget> _children = [
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      key: PageStorageKey<int>(0),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab1  $index');
      },
    ),
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      key: PageStorageKey<int>(1),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab2  $index');
      },
    ),
    new ListView.builder(
      padding: new EdgeInsets.all(8.0),
      key: PageStorageKey<int>(2),
      itemExtent: 20.0,
      itemBuilder: (BuildContext context, int index) {
        return new Text('tab3  $index');
      },
    ),

  ];

  @override
  Widget build(BuildContext context) {
    print(bucket.storage);
    return Scaffold(
      appBar: AppBar(
        title: Text('My Flutter App'),
      ),
      body: PageStorage(bucket: bucket, child: _children[_currentIndex]), // new
      bottomNavigationBar: BottomNavigationBar(
        onTap: onTabTapped, // new
        currentIndex: _currentIndex, // new
        items: [
          new BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Home'),
          ),
          new BottomNavigationBarItem(
            icon: Icon(Icons.mail),
            title: Text('Messages'),
          ),
          new BottomNavigationBarItem(
              icon: Icon(Icons.person),
              title: Text('Profile')
          )
        ],
      ),
    );
  }

  void onTabTapped(int index) {
    setState(() {
      _currentIndex = index;
    });
  }
}
```

Now on with the detail.

You can notice that I don't need separate scroll controller in three pages. you only need separate scroll controller if you want to have more than two scrollable widgets to be able to scroll separately 'in the same screen'. This is not the case for your example, only one widget is present in the screen at a time. That is why you can just use the one primary controller.

The issue you are seeing is due to flutter treating all three listviews as the same widget with slightly different content, so when you switch tabs, flutter only updates its content with new text label but keep all the state that same which include scroll position.

To make flutter think they are different widgets, you will need to assign widget keys to all the listview. Assigning UniqueKey should do the job. With UniqueKey, flutter will now all three widgets are different, so thus it should not inherit the scroll position.

However, it does not preserve the scroll position with UniqueKey when you switch tabs back and force, it will always reset back to 0. To fix that, you will need PageStorageKey, PageStorage and PageStorageBucket. Now, flutter will know to find the scroll position from PageStorageBucket when it visit a newly initialized page.

I will close this issue for now. If you have further question, feel free to reopen

**Comment by eturk1** [comment]
Thanks @chunhtai!
I'm about to leave for travel until June & can try the solution in my project after that
