### ISSUE TITLE
How do I get CPU and memory information through the API during integration testing?

### ISSUE THREAD

**Issue by Wanghuayin** [flutter/flutter#21585]
> Benchmarking
> You can measure and track your app’s performance by writing benchmark tests. The Flutter Driver library provides support for benchmarking. Using this integration test framework, you can generate metrics to track the following:
> 
> Jank
> Download size
> Battery efficiency
> Startup time

and CPU ？Memory？ How can i get them ?

**Comment by zoechi** [comment]
Perhaps https://github.com/dart-lang/dart-services
not sure it's available in profile builds, but I guess so.

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md
https://github.com/dart-lang/vm_service_client

**Comment by Wanghuayin** [comment]
@zoechi , i didn't found any valuable info from your link, any other suggestions?  Is it what i ignored
?

**Comment by zoechi** [comment]
Sorry, didn't look close enough. I expected to get more information out from there.
https://api.dartlang.org/stable/2.0.0/dart-io/Platform-class.html might work.
I'm not aware of other sources for this kind of information.

**Comment by Wanghuayin** [comment]
@zoechi is there any way to get the data of the performance overlay? or the data from the http://127.0.0.1:xxxx/ws ?

**Comment by zoechi** [comment]
@DanTup or @devoncarew might be able to help

**Comment by DanTup** [comment]
I'm not too familiar with this, I don't know how easily you could get it programatically. I did find https://github.com/flutter/flutter/pull/3313/files that seems to be writing a timeline summary, so maybe the data you need can be found in there somewhere. @devoncarew can probably give a better answer though!

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by ravenblackx** [comment]
In case anyone else ends up here while searching for this, the only thing I've found that looks remotely hopeful is [ProcessInfo.currentRss](https://api.dart.dev/stable/2.0.0/dart-io/ProcessInfo-class.html). It doesn't seem *very* useful because there's apparently no way to trigger or wait for garbage collection from within the process itself, only [FlutterDriver.forceGC](https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/forceGC.html) - which, in turn, seems to be unhelpful because there doesn't seem to be a way to request memory usage from FlutterDriver! Without GC-triggering and usage-measuring in the same place it seems unfeasible to usefully benchmark or perform A/B performance testing with respect to memory usage.
