### ISSUE TITLE
benchmark regression on Dart SDK roll

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#21631]
Dart SDK roll in https://github.com/flutter/flutter/commit/88565f68aa1382a89cbd7b770628f5eb7f5ad823 regressed the following benchmark: 

* complex_layout_scroll_perf__memory/diff-median

Please rebase the benchmark if this regression is expected.

@bkonyi

**Comment by jason-simmons** [comment]
Bisected this.  There's some noise in this benchmark, but the difference appears to be tied to https://github.com/dart-lang/sdk/commit/14bdc51ff5ad73f8edba6049d517cb8bd86d2bbc

@rmacnak-google

**Comment by Hixie** [comment]
Can you say more about what changed? It looks from the benchmarks that max memory usage for complex_layout_scroll_perf__memory runs increased, enough that the median increase is clearly visible beyond the noise (solid green before, solid red after).

**Comment by Hixie** [comment]
(Either the issue is real, in which case it needs fixing; or the issue is an intentional regression, in which case we should document it in the changelog; or the issue is a rare one-off change that makes previous values of the benchmark not comparable to new values of the benchmark, but in such a way where the new values are still meaningful, in which case we should describe the change here so that in the future we can figure out why the value changed; or this is a bogus benchmark and an innocent change with no user-facing ramifications caused a benchmark change, in which case we should fix the benchmark.)

**Comment by clocksmith** [comment]
Is somebody working on this? Can there be an update on whether its being fixed, or if it is not actually a TODAY issue? Thanks

**Comment by rmacnak-google** [comment]
As described in the CL, the threshold for the first GC is now related to the application size instead of a constant. For typical Flutter app sizes, the first GC will occur sooner, which downstream may cause the last GC for measurement to occur further from the peak live set size. Growth policy interacts chaotically with the live set size of a program over time, so one should not expect monotonic improvements.

**Comment by Hixie** [comment]
Ryan and I talked about this and it seems the likely next step to make this benchmark better would be to have a profile-only way to trigger a GC so the benchmark becomes less sensitive.
