### ISSUE TITLE
Event funneling

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#217]
<a href="https://github.com/HansMuller"><img src="https://avatars.githubusercontent.com/u/1377460?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansMuller](https://github.com/HansMuller)**
_Wednesday Oct 21, 2015 at 23:09 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1726_

---

If I add a single event handling child to a larger container that just adds some decoration, sometimes I'd like to be able to say that events that occur within the container should be delivered to the event handling child. As if they'd actually targeted the child.

For example: put a button inside a container that adds some padding and a border. It would be nice if it were possible to funnel gestures that landed outside the button but within the container, to the button. So that the entire thing acted like the button.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/krisgiesing"><img src="https://avatars.githubusercontent.com/u/13855787?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krisgiesing](https://github.com/krisgiesing)**
_Tuesday Nov 03, 2015 at 21:31 GMT_

----

I think this would only matter if the child is stateful. If it's stateless, the parent can just wrap the whole container in a GestureRecognizer and ignore the callback parameter to the child. (It does somewhat undermine the utility of the callback, though.)

**Comment by Hixie** [comment]
There's several ways we could do this:
- at the rendering layer, we could have a renderbox which in its handleEvent method visited children recursively (asserting if it hit a node with multiple children) until it found a RenderPointerListener descendant, and just proxied the results to that object.
- at the widget layer, we could do something similar with a widget that had a Listener, and onPointerDown hunted for a GestureDetector and forwarded pointer down to that object's _handlePointerDown method. Or alternatively, forwarded events from its Listener to a descendant Listener's callbacks.
- at the widget layer, we could have a method which did either of those options but using a GlobalKey instead of a walk.

**Comment by Hixie** [comment]
We're addressing this problem by dedicated widgets, e.g. RadioListTile.
