### ISSUE TITLE
Connectivity plugin may cause apps to be rejected from iOS App Store

### ISSUE THREAD

**Issue by kibantony** [flutter/flutter#21753]
The [connectivity](https://pub.dartlang.org/packages/connectivity) plugin depends on a pod called [Reachability](https://cocoapods.org/pods/Reachability). I noticed on the [GitHub repo](https://github.com/tonymillion/Reachability) for this pod there's a warning in large angry letters:

> ### WARNING there have been reports of apps being rejected when Reachability is used in a framework. The only solution to this so far is to rename the class.

There's more info on this issue here: https://github.com/tonymillion/Reachability/issues/95

I'm concerned that since my Flutter app uses the `connectivity` plugin that I could be in for a surprise when I submit my app to the store(s). Also concerning is that the maintainer appears to have not addressed the issue apart from adding some text to the README. Has anyone run into this issue when submitting a Flutter app? Do I have cause to be concerned?

While we're on the topic, I noticed the `Reachability` repo itself hasn't been touched in a year and there are quite a few _very_ old and apparently unaddressed issues. I was curious if there might be cause for reevaluating the suitability of this pod for inclusion in the Flutter system.

**Comment by kibantony** [comment]
Edit: tweaked the title to be more clear on the main issue.

**Comment by filleduchaos** [comment]
I could take a look into this sometime this weekend

**Comment by filleduchaos** [comment]
Looking at it, I'm not certain why the plugin can't just use the builtins from SystemConfiguration instead. I'm going to take a stab at a rewrite this evening to be sure.

**Comment by vipinagrahari** [comment]
Any updates on this?

**Comment by mulderpf** [comment]
I've submitted my app to Apple without any issue using this plugin.

**Comment by cyanglaz** [comment]
@kibantony Thank you for bringing this up! It seems ok to have an app including Reachability as far as I know. The only restriction seems to be that the Reachability should not be included in an iOS framework, which is commented in the README. So I think it won't reject the flutter app that uses the plugin, just as mentioned by @mulderpf.

However, I agree with @filleduchaos, it'd would be super nice to have the plugin implemented all the features directly using the native APIs instead of depending on some other Pods. I am not too familiar with the SystemConfiguration and not sure how much of an effort it would be to completely swap out the Reachability. I'd love to review PRs if anyone is up for it!
