### ISSUE TITLE
Refactor FlutterActivity

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21787]
Refactor FlutterActivity to forward all Activity-exclusive signals to a FlutterFragment and thereby do the absolute minimum amount of work possible.

**Comment by matthew-carroll** [comment]
Done in https://github.com/flutter/engine/pull/6195

**Comment by gitspeak** [comment]
Not quite sure this is the right issue but after reading the PR notes I think it’s imperative to add support for coding Android Services as well. These essentially hint the Android run time to extend the app process lifetime when it's running in the background and are quite critical in many scenarios like: music player apps and messaging apps that queue network requests.

**Comment by gitspeak** [comment]
No worries. Moving forward I suggest we put aside the audio example since IMHO it represents a too easy use-case and by “easy” I don’t mean the specifics of your implementation but rather the fact that audio playback carries single instance semantics and I presume minimal interaction (if any) between an audio service and other running services in the app.

>I think my specific question is about whether we need to provide something in the Android embedding, or whether this is something that should be handled by plugins.

I have very limited understanding of the flutter plug-in api and it’s relationship to “platform embedding” but a cursory read suggests to me that "Plug-in" is an api for invoking android Java classes from dart classes both loaded in the same process. This mechanism seems to me as something which is  orthogonal to the android application model. Therefore I suggest an alternative question: What is the flutter application model on android? I would argue that it is the Android application model.

Yes. Android application model is complex, but not without merit. I think this complexity is completely orthogonal to the complexity of using the UI toolkit . Thus, I highly recommend you expose all android components to dart users rather then attempt to abstract them. During recent years I have seen multiple attempts by the Android team to simplify things by building various abstractions for specific scenario but I would argue that it would have been better to invest in more in-depth documentation/training about how android components are managed and provide best practices for cross component communication for key scenarios. Long story short, I suggest to  mimic all android components (e.g FlutterAndroidActivity, FlutterAndroidService, FlutterAndroidApplication) and expose them to dart users as they are exposed to Java users. Point being, from an architectural stand-point, is   that these components are not "Java specific" it just so happens that the first realization of these conceptual components is a Java implementation. This approach might also require tooling support to auto-generate Java code per component instance to forward the life cycle events to the corresponding dart instance.

**Comment by matthew-carroll** [comment]
@gitspeak I think some of the back-and-forth here may be a lack of background with how one might choose to build a Flutter app, and where the respective behaviors belong.  So let's do this: I've had some discussions with another member of the team about providing some versions of Service in the embedding.  This is for background execution.  Once I land those changes, why don't you let me know how those additions compare to what you're thinking right now.  Then we can adjust from there as needed.

**Comment by gitspeak** [comment]
@matthew-carroll Sounds fair. Once you have these changes I would very much appreciate you post a short code sample demonstrating the usage. This will establish common ground. Specifically, I'm interested to see a sample that covers the api for starting/stopping a service, passing arguments to the service as well as sending completion notification from the service to a listener. I would also be interested to know how your changes will support registering a "Flutter Service" to be run at device boot time, that is without the user launching the app explicitly.
