### ISSUE TITLE
Support XML control of FlutterView splash color and drawable

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21807]
Support XML control of FlutterView splash color and drawable

**Comment by zoechi** [comment]
I don't know how to triage the bulk of issues you created.
It would be good if they had all at least one label, otherwise it becomes cumbersome to find other untriaged issues.

**Comment by matthew-carroll** [comment]
What exactly is involved with triaging in GitHub?  Every ticket I filed is prioritized and categorized within the project that they're tagged with.  Labels would be superfluous for my uses.  Is there some other area of issues where these are creating noise?

**Comment by zoechi** [comment]
Nothing I'm aware of. 
@Hixie ?

**Comment by Hixie** [comment]
@matthew-carroll  We should make sure all bugs the flutter team files directly have labels, so that they come up appropriately when doing searches (and also so that they don't end up on @zoechi's list of "bugs to triage"). See https://github.com/flutter/flutter/wiki/Triage for guidance on how to add labels to bugs.

**Comment by matthew-carroll** [comment]
Blocked by #22102

**Comment by xster** [comment]
This is done. Activity metadata `"io.flutter.embedding.android.SplashScreenDrawable"` specifies a drawable ID for the splash screen.
