### ISSUE TITLE
Flutter upgrade caused problems with dependencies

### ISSUE THREAD

**Issue by cconnerj** [flutter/flutter#21821]
I haven't updated flutter in a long time and i decided i should before i deploy my app to see if anything needed to be changed.  Before i was using v.0.5.1, and i just upgraded to v 0.7.3.  I ran my code to the simulator right away and got errors about my dependencies.  I tried to run packages upgrade but that didn't work.  When i try to run my app i get this error,

Because no versions of flutter_launcher_icons match >0.6.1 <0.7.0 and flutter_launcher_icons 0.6.1 depends on dart_config from git, flutter_launcher_icons ^0.6.1 requires dart_config from git.
So, because "myapp" depends on both dart_config from hosted and flutter_launcher_icons ^0.6.1, version solving failed.
pub get failed (1)

i currently have these 2 versions in my pubspec
 dart_config: ^0.5.0 
 flutter_launcher_icons: "^0.6.1"

**Comment by zoechi** [comment]
I guess copying the `dart_config` dependency from `dependencies: ...` to `dependency_overrides: ...` should help you overcome the problem.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

If you're still stuck and post on one of the listed support channels, please post the relevant parts from your `pubspec.yaml` file.

I'm closing this issue because I'm pretty sure there is nothing to do for the Flutter team.
