### ISSUE TITLE
Dev Bytes video about Add2App

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21835]
Publish a Dev Bytes video that demonstrates Add2App for iOS and Android.

**Comment by Sfshaza** [comment]
@RedBrogdon @efortuna

**Comment by matthew-carroll** [comment]
@efortuna it depends how much you want to show.  If you only want to show the inclusion of a fullscreen Flutter Activity in an existing Android app, then you can probably write the script right now, and then just replace a couple CLI terms within the next couple weeks.

If you want to show serious Flutter integration via FlutterFargment, FlutterView, ListViews, etc. then you'll probably need to wait 2-3 weeks to really know what those Classes will be.  Even that script you could outline right now, but the specifics will take a few weeks to stabilize.

**Comment by neiljaywarner** [comment]
It's been 8 weeks, is there any progress on this please; this is pretty exciting...

**Comment by matthew-carroll** [comment]
@neiljaywarner we're re-evaluating the use-cases that we need to support with Add2App.  If you have a requirement for Add2App functionality, it might be helpful to hear how you would use it.  Please feel free to comment here with details about any such project that you're working on.

**Comment by neiljaywarner** [comment]
A lot of people, especially big companies, including ours are at the beginning stages of evaluating flutter, and have large legacy apps and will be unable to do file-new project.

Therefore I propose you consider really highlight "hello world" of integrating flutter in an existing project really well and rock solid and easy to find.
e.g.
1) in the cookbook recipes
2) in the "For ios devs" and "for Android devs"
3) or even in the "getting started"
it seems this might be very popular.

Also useful would be a PR or commit (a diff) with a project - ideally Android hello world - then a small as possible diff where it becomes Android hello world with a FlutterActivity that all it does is have "Flutter Hello World" Text Widget..

Something so if you have never done anything with flutter at all and your boss says "can we put flutter in our existing app" you can say yes confidently instead of "maybe"

pawan has a video but it is 40 minutes long
https://www.youtube.com/watch?v=Gw211RZGVw8&feature=youtu.be
It would be great to have it more like Andrew's 10 minute video on devbytes about Firestore to existing app, that one is very powerful and useful.
https://www.youtube.com/watch?v=DqJ_KjFzL9I
--
I saw the groupon example article but it was Android only. (as was Pawan's article)

**Comment by neiljaywarner** [comment]
I feel FlutterActivity is a great starting point except that jetpack advises SingleActivity architecture now.  (So FlutterFragment also nice, especially going forward)

From what I can tell so far individual FlutterViews could be considered an edge case...  Thanks so much for prompt response.

The main thing is clarity for the primary use case, and yes, ideally great tooling support for it.

**Comment by zoechi** [comment]
Should this be moved to flutter/website?

**Comment by matthew-carroll** [comment]
@zoechi I'm not sure what the official division of tickets is supposed to be.  It's up to you.

Hi @neiljaywarner, would you mind contextualizing your previous statements?  I'm not sure what topic or topics you're attempting to address.

**Comment by neiljaywarner** [comment]
@matthew-carroll Sure!  

The devbytes video or sample could be a minimal but real world best practice example - the omdb app or a weather app or similar, but something that gives
a) a possible suggestion for structuring the defaultRoute where parameters are passed in.  
Specifically 1) the jetpack guide is very thorough like this with a github example. It mentions DI as Dagger and Retrofit for networking, with sort of a "This is what we are using, use something else if you want to"... 
2) So far I'm using a url format with /section?param1=foo&param2=bar where section is to route to a page and param1 and param2 are parameters you need that the platform app provided, whether it's login id or api key or whatever.

b) An example of something a little less non-trivial where something calls the platform back.  Emphasizing, linking and having an example of platform calls in relation to add2app would be very helpful.  I suggest in particular an exception example like if login Expired go get one from platform, or even if exception, log to platform exception handling

thanks for consideration
@zoechi

**Comment by Hixie** [comment]
We're looking at this for early next year, but the bug system is not where we track that kind of work so I'm going to close this bug.
