### ISSUE TITLE
Code Sample: Adding Flutter to an app within a UITableView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21836]
Publish a code sample that demonstrates flutter/website#7788

**Comment by jkmathew** [comment]
Hey @matthew-carroll, 
I am curious about to know that whether this is possible or not.

Right now I have to embed flutter view controller(didn't tried yet) inside a tableview cell for this. Embedding view controllers in tableview cells.. I am bit afraid of that.

**Comment by matthew-carroll** [comment]
@dnfield can you comment on this?

**Comment by dnfield** [comment]
It'd certainly be possible to rewire the embedding so that we could do a `FlutterView` instead of requiring it be a `FlutterViewController`.  There's been at least one other request like this that I've seen somewhere else on GitHub.

That said, AFAIK it should be possible to use a ViewController in this case.  I'm also a bit concerned about creating a "light weight" feeling `FlutterView` - there's significant memory usage for each instance of the engine.

**Comment by stuartmorgan** [comment]
Closing, since the associated website issue was wontfixed.
