### ISSUE TITLE
First run builds a snapshot on Windows

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#22062]
## Steps to Reproduce

1. Download and extract the [flutter sdk](https://flutter.io/sdk-archive/#windows) on a Windows machine.
2. Run `flutter create --offline foo`

Expected: Shouldn't build a snapshot on the first run (from [rolling the beta channel, #5](https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel))

Actual: Rebuilds snapshot.

## Logs

```
> flutter create --offline test
Building flutter tool...
Running pub upgrade...
Creating project test...
```

Looks like this reproduces from at least `v0.8.2`-`v0.4.4`, possibly earlier?

**Comment by aam** [comment]
The culprit is https://github.com/flutter/flutter/blob/master/bin/flutter.bat#L94 which assumes that when user extracts downloaded zip file timestamps for `packages\flutter_tools` `pubspec.yaml` and `pubspec.lock` are preserved. And while 7-zip extractor does preserve timestamps, Windows Explorer built-in zip-file extractor does not - it assigns timestamps based on extraction time:

``` 7zip:
C:\flutter_windows_v0.8.2-beta1> dir .\flutter\packages\flutter_tools\pubspec.*

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/20/2018   9:51 AM          11056 pubspec.lock
-a----        9/20/2018   9:51 AM           5306 pubspec.yaml

``` Windows Explorer extractor:

C:\flutter_windows_v0.8.2-beta1> dir C:\flutter_windows_v0.8.2-beta\flutter\pack
ages\flutter_tools\pubspec.*

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/18/2018  12:40 PM          11056 pubspec.lock
-a----        9/18/2018  12:35 PM           5306 pubspec.yaml
```

**Comment by dnfield** [comment]
This is still happening with the latest beta.

Unzipping with 7zip works fine - unzipping with built in Windows archiving causes flutter tool to rebuild.
