### ISSUE TITLE
Remove the fire emoji from hot reload prompt.

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#22303]
Since 0.9.3, the flutter command line build process shows a rotating moon (i.e. displays a few moon emoji's after each other).  This is causing a mess on terminals / terminal emulators that do not support emoji's.  The "fire" emoji displayed before the text "To hot reload changes ..." was already annoying, but this is much worse.

Please stop displaying emoji's as part of flutter command line interface, so that everybody can run flutter commands from any terminal without issues.

**Comment by zoechi** [comment]
Seems others run into this already #22243
Should be fixed in master

**Comment by zoechi** [comment]
@josvos I saw you comment in #22243
Are there concrete other examples where emoji printed from Flutter tools cause issues?

**Comment by josvos** [comment]
Additional comment: looking at commit eadd59a mentioned in issue #22243 it looks like the code for the `platform.isWindows` condition could be used on all platforms.

**Comment by gspencergoog** [comment]
So, this bug is to remove the remaining fire emoji? The moon emoji has already been removed and replaced with a regular Unicode character.

**Comment by josvos** [comment]
The bug was triggered by the moon emoji in 0.9.3 causing a lot of messy output, but as a side note I mentioned the fire emoji, that is also displayed as a square with hex chars on some terminals and can better be removed too.

**Comment by Hixie** [comment]
It's 2018... I think it's reasonable for us to assume that people will be able to install modern fonts that support emojis.

**Comment by gspencergoog** [comment]
Yeah, I agree. I am sorry, @josvos, I understand your concern, but I think a) it doesn't affect functionality, only prettiness, and b) there's a workaround (use a modern font with emoji support, or just ignore the one square with numbers in it).

The moon emoji was mainly removed until our fix to a bug in `xterm.js` lands because VSCode uses that package, and it's one of our supported IDEs, not because it's an emoji. The moon might reappear someday when those issues are resolved, but not for a while, and it's not high on our priority list to bring it back, if that helps.
