### ISSUE TITLE
Migrate all tooling that refers to "module" to names that refer to "application"

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#22344]
Add2App introduced a new project structure known as "module" and therefore we now have multiple tooling references to "module".

Along the way the decision was made to use this new project structure for *all* future projects.  Therefore, this project structure, and most of the tooling around it, is not about "modules".  We should rename this tooling to use the term "project" to match the eventual --template term that will be used for it, which will read "flutter create --template project"

**Comment by matthew-carroll** [comment]
@Hixie FYI - this ticket is available for help from others if someone has time.  It's essentially a glorified renaming project (including renaming and updating device lab tests associated with the template tooling).

**Comment by Hixie** [comment]
cc @gspencergoog this would fit under your tool remit quite well. :-)

**Comment by gspencergoog** [comment]
After discussing offline, Matt, Ian and I decided to rename "create -t module" to "create - t application", leaving the old "create -t app", but deprecating it.

**Comment by gspencergoog** [comment]
And as for the method of upgrading: I was going to have it just detect which type of existing project was there, and use that for the default type if no type was specified, but if they specify a type, then generate that type. I'm not sure about this though.  If you specify "application" in an existing "app" project, what should it do? Ideally, it would attempt to convert between the two, but I'm not sure how feasible that is. It seems like it would be complicated and error prone.

**Comment by mit-mit** [comment]
Does this include upgrading the apps in flutter/flutter/examples to use the module/application template rather than the old app template (i.e. to not have materialized hosts in them)?

**Comment by matthew-carroll** [comment]
@mit-mit migrating those projects makes sense to me.  They're partially a marketing tool so I suppose we should keep them up with the latest and greatest.  I'll file a ticket in the Add2App project for that.

**Comment by gspencergoog** [comment]
OK, here's what I'm going to do for `flutter create`:
1. If the destination directory doesn't exist, then I'll create an "application" (née module) project by default.
1. If they ask for a particular template (i.e. '-t application'), and the destination doesn't exist, then I'll create that.
1. If they ask for a particular template (i.e. '-t application'), and the destination already exists, then I'll see if the existing project is indeed one of those, and I'll update it if is, and error out if it isn't.
1. If they don't ask for a particular template (the default), and the destination already exists, then I'll figure out the type of the existing project and I'll update it using what it is currently (any of "app", "application", "plugin" or "package") as the template.

I'm also going to add a "project_type" to the .metadata file that we write, and I'll make the templating system overwrite that file even if it already exists, so that when we update a project, we also update the flutter version used to update it. This will make it easier in the future to determine the type of project that is written.  For projects that don't have this, I will detect the type and then write it.

**Comment by matthew-carroll** [comment]
CC @devoncarew @stevemessick @DanTup to verify that @gspencergoog's proposal won't break the IDEs.

**Comment by DanTup** [comment]
I don't think anything here impacts VS Code. Our only interaction with `create` is the `Flutter: New Project` command and it doesn't pass `-t` and just uses the default.

**Comment by DanTup** [comment]
To clarify - am I right in thinking that a standard app (run from Flutter) and what was called "module" (to be used within an existing native app) are the same? If so, I guess https://github.com/Dart-Code/Dart-Code/issues/1178 is not required anymore?

**Comment by gspencergoog** [comment]
Yes, I think you're correct.  What used to be created with `flutter create` (the "app" template) is no longer going to be the default, and instead we'll create what used to be called a module (now called the "application" template), and we'll be deprecating the old "app" template. There will no longer be a "module" template.

**Comment by stevemessick** [comment]
The next release of the Flutter plugin for IntelliJ will no longer have a
Module option in the new project wizard, so that will bring it in line with
these changes.

However, "Module" is used in a couple different contexts. We have UI
support for Android Studio that links a Flutter module/application into an
Android app. We're hanging that off the "New Module" menu item. I think
that makes sense from and Android programming viewpoint but would be
interested to know if others agree.

**Comment by devoncarew** [comment]
This should be fine. It's `--template` options going away that will cause problems w/o planning. New `--template` options would also need to be planned out, to know when we could safely add them to the new project wizards.

**Comment by gspencergoog** [comment]
OK, cool. In that case, just to be clear, this change will effectively rename the `--template=module` to `--template=application`, and changes the default (running `flutter create` with no template argument) to `application`. The old `app` template type is still there.

**Comment by matthew-carroll** [comment]
@gspencergoog are we truly renaming --template=module to --template-application?  Or do we currently have both doing the same thing?  I thought we might want to leave --template=module without any public docs for one cycle just in case.  Although if others feel confident that we can nuke it right now then I'm fine with that, too.

**Comment by gspencergoog** [comment]
Well, my PR truly does the rename, but I could make an alias for "module" for a bit if we need it. It sounded to me, however, (from the above discussion) like IntelliJ was the only one that used it, and that's going away.

**Comment by matthew-carroll** [comment]
If we merge this to master tomorrow, for example, if a dev is on master wouldn't IntelliJ be broken for them in the project creation use-case?

**Comment by gspencergoog** [comment]
Yes, probably.  We can either wait to merge my PR until IntelliJ isn't using module anymore, or I can make an alias as I said above.

**Comment by stevemessick** [comment]
Yes, that's going away in the next release, at the end of the month. Probably best to leave it and delete it next month.

**Comment by gspencergoog** [comment]
OK, will do.
