### ISSUE TITLE
More efficiently fetch image from iOS (and Android maybe) Photos library

### ISSUE THREAD

**Issue by sprhawk** [flutter/flutter#22517]
I need to access Phones' photos library (like a photo gallery), and I wrote an experimental [plugin](https://github.com/sprhawk/flutter_photos_library/). 

In the plugin I used binaryMessenger to transfer images. But it showed very slow: I can see flicking when show images.

Is there any method to be efficient to transfer data other than channel? 

Or what about using Texture Widget? I just don't know if I can generated may textues inside Flutter framework.

**Comment by sprhawk** [comment]
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-CN)
    • Flutter version 0.11.3 at ***
    • Framework revision 72bf075e8d (5 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = ***
      but Android SDK not found at this location.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at ***
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at ***
    • Flutter extension version 2.21.0

**Comment by zoechi** [comment]
@sprhawk you are aware that a newer Flutter version 1.0.0 is out?

**Comment by sprhawk** [comment]
@zoechi Yes, but
1. when I posted the issue, the version is old
2. I think the poor performance is related deep in architecture , I think it is not resolved by latest version

**Comment by zoechi** [comment]
Related to #18850

**Comment by gaaclarke** [comment]
Your code is decompressing, then recompressing them image to send over the channel, then decompressing it again to upload it to the GPU.  The best option would be to send the url to the image to Flutter, but the Apple API doesn't provide that.  You can experiment with sending the image uncompressed.

Unfortunately because of the limitations in Apple's API there isn't much we can do about making it faster.  From a design perspective I'd treat them like loading images from a network, make a nice animation transition, don't show the empty ui until you have the image, etc.

You might be able to do something like you mention with textures.  In your plugin, upload the texture to the GPU then pass the handle back to Flutter.  I'd check the [camera plugin](https://github.com/flutter/plugins/blob/master/packages/camera/ios/Classes/CameraPlugin.m) for inspiration.  You'll have to be careful there because you'll have to support Metal and OpenGL.

FFI is now an option with dart too.  That will give you the ability synchronously execute code between Flutter and the host platform.  That could provide a way to pause the flutter thread for a fraction of a second while an image resource is loaded.

There are a lot of things to try out provided by the current API.

**Comment by darshankawar** [comment]
@sprhawk 
Is this still a valid issue using latest Flutter version ?
If so, you may look at suggestions made here and try again to see if it works for you.
Thanks.

**Comment by sprhawk** [comment]
> @sprhawk
> Is this still a valid issue using latest Flutter version ?
> If so, you may look at suggestions made [here](https://github.com/flutter/flutter/issues/22517#issuecomment-611131313) and try again to see if it works for you.
> Thanks.

Hi I'm not using flutter anymore, I didn't have a plan to test it.
