### ISSUE TITLE
If onscreen contexts cannot be created in the same sharegroup as the resource context, disable async texture uploads.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#22527]
This may happen on certain Android device. One such device is HUAWEI P6 T00.

**Comment by chinmaygarde** [comment]
Reported in https://github.com/flutter/engine/pull/6358

**Comment by huycozy** [comment]
>This may happen on certain Android device. One such device is HUAWEI P6 T00.

@chinmaygarde I see this device has been discontinued: https://www.gsmarena.com/huawei_ascend_p6-5467.php, https://www.gsmchoice.com/en/catalogue/huawei/ascendp6/. 

And since there has been no update on this for a long time, I will go ahead and close this issue. If you want to keep this for tracking or the issue persists on the latest Flutter version, feel free to re-open.
