### ISSUE TITLE
Benchmark more accurate startup time 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#22578]
We currently have benchmarks like complex_layout__start_up and flutter_gallery__start_up but their time zero starts at `FlutterEngineMainEnter` which is all the way out to the end of the dart vm creation. 

We should create other benchmarks that starts time zero at the `Application.onCreate()` and `main()` of Android and iOS respectively to fully capture the engine, framework and app start time.

**Comment by liyuqian** [comment]
https://github.com/flutter/packages/pull/181 might be related with this. @gaaclarke : can we use something there to fix this issue?

**Comment by gaaclarke** [comment]
Imitation game works by launching the process, then waiting for the process to report how long a certain task took.  If you want to cut out the time it takes to install and launch a process you could take that approach.  It should give you more reliable measurements since the process itself knows exactly what time it actually launched.
