### ISSUE TITLE
(new Duration) OR (const Duration)

### ISSUE THREAD

**Issue by jParliaments** [flutter/flutter#22653]
Now... I can't see the advantages/pros for using const... in IntelliJ and Android Studio you can't fold your code if you leave out the "new" keyword... so I am always using it with (maybe a bug ?)

is there any disadvantage if you don't use any const's there, where you don't need? I see only using constants in a custom color definition. If you don't use, you can see the color icon in the gutter in IntelliJ and Android Studio (maybe a bug too ?)

`const Duration d1 = const Duration(seconds: 1);`

`Duration d1 = new Duration(milliseconds: 1000); `

**Comment by pratikjain04** [comment]
**const Duration d1 = const Duration(seconds: 1)** will work only when you have provided constant values to seconds, but if your seconds value is dependent on some parameter, which changes according to different situations, 'const' keyword would raise an error. So, always prefer to use:
Duration d1 = Duration(seconds: timeDelay), where timeDelay is any variable holding integer values.

(not using 'new' keyword, since its not mandatory from Dart2).

**Comment by zoechi** [comment]
`const` is used for performance improvements.
The difference is not huge but it may sum up.

https://news.dartlang.org/2012/06/const-static-final-oh-my.html

Can you please report the folding but in https://youtrack.jetbrains.com
