### ISSUE TITLE
The default flutter template looks android specific

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22717]
Our default template should be recognizable to developers coming from both Android and iOS backgrounds, however it's current use of a FAB (floating action button) can be confusing to iOS developers. We should consider using material widgets that we more platform neutral.

**Comment by willlarche** [comment]
@mit-mit , do you want me to submit a PR or work with devrel to create a final version?

**Comment by mit-mit** [comment]
@willlarche any news on this?

**Comment by Hixie** [comment]
Please cc me and @InMatrix on any PRs for this. Thanks!

**Comment by mit-mit** [comment]
@willlarche any news on this?

**Comment by zoechi** [comment]
Similar to #18819

**Comment by matthew-carroll** [comment]
@willlarche @mit-mit @Hixie we discussed this in a Cupertino meeting and we'd like to suggest that rather than alter the single, existing project template, that we focus on how we might offer multiple templates. This has been discussed in other contexts as well, such as starting with a simpler structure for those of us that don't need all the boilerplate.

I'm going to close this issue so that we instead focus on #18819, which will introduce a 2nd template, instead of trying to de-materialize the 1st template (which would be very difficult because there is little chance that we could eliminate the "material" import, which iOS developers would take issue with).
