### ISSUE TITLE
Add support for FieldPath for where-clause querying to Firestore Plugin. 

### ISSUE THREAD

**Issue by shashikantdurge** [flutter/flutter#22712]
Querying Firestore doesn't yield results when the  Field name consists special characters.
For example  _abc@gmail.com_ which consists '.' 
Can you include a work around like including _`_ around the Field name so that it treats special characters as Normal one.

**Comment by shashikantdurge** [comment]
#https://github.com/flutter/plugins/pull/616

**Comment by zoechi** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/629

Please add a comment if you're still seeing this to get the issue reopened.

**Comment by tcunningham07** [comment]
The issue described by @shashikantdurge hasn't been addressed, field values which contain a '.' will not be parsed correctly (i.e. email addresses in a map, such as `invitees['abc@abc.xyz'] = 'sent'` then trying to perform a query on "invitees.abc@abc.xyz" field will fail because it parses 'xyz' as a subfield of 'abc@abc'.

Unless there's an escape character somewhere in the documentation that I can't find, this still causes issues

**Comment by kroikie** [comment]
@shashikantdurge

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/626. Any further collaboration will be done there.
