### ISSUE TITLE
Cannot create new project using Start a new Flutter project

### ISSUE THREAD

**Issue by thaingo** [flutter/flutter#22726]
I tried to create a new project, selected "Application" but met an error.
Error message as per enclosed image: `The requested template type 'app' doesn't match the existing template type of 'package'.`

![flutter_issue](https://user-images.githubusercontent.com/627823/46532233-31d82d00-c8ca-11e8-989a-684bde031170.png)

## Steps to Reproduce
1. Open Android Studio
2. Click on "Start a new Flutter project"
3. Nothing shown except an error as per in attached image.

## Environment:
OS: Ubuntu 16
Android Studio: 3.2
Flutter Intellij plugin: 29.0.2
Dart Intellij plugin: 181.5540.11
Flutter SDK: v0.9.7-pre.42

## Output of `flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.7-pre.42, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

Please help look into this.

Thanks,
Thai

**Comment by zoechi** [comment]
That's probably because the Flutter plugin doesn't support the latest changes of the Flutter framework yet.

**Comment by devoncarew** [comment]
cc @stevemessick

**Comment by devoncarew** [comment]
I see this from IntelliJ as well, on Flutter at master:

<img width="634" alt="screen shot 2018-10-05 at 8 32 02 am" src="https://user-images.githubusercontent.com/1269969/46544732-36c0c080-c879-11e8-8530-86237404bac6.png">

**Comment by devoncarew** [comment]
You can reproduce this from the command line, if you create an empty directory (`untitled_app_87623`), and run:

```
flutter create --template app untitled_app_87623
```

```
The requested template type 'app' doesn't match the existing template type of 'package'.
```

**Comment by dnfield** [comment]
Related to https://github.com/flutter/flutter/pull/22565?

**Comment by gspencergoog** [comment]
Yeah, this is my code, trying to make sure that re-run `flutter create` with a template type that is different than the original.  I'll take a look.

**Comment by gspencergoog** [comment]
Yeah, my logic doesn't work right if the directory already exists when 'create' goes to populate it. I'll fix that.  (The logic works fine if the user doesn't create the empty directory first, and lets the create command do it).

**Comment by devoncarew** [comment]
Gotcha. In the IDE case, the (mostly empty) directory is created for us by the new project wizard framework, and then we use the flutter tool to populate the contents.

For FYI, the directory is empty except for an `.idea` sub-directory, with 2-3 metadata files within that directory.

**Comment by gspencergoog** [comment]
OK, thanks.  This all happened because I was trying to be a little too helpful...

Part of the job of the "create" command is to recreate missing pieces of existing projects, and now that the default has changed, I wanted to make it so that if someone had created a default `flutter create` project before, that they could run a default `flutter create` there again, and not have it trashed by using the new default template over the old one.

This meant I had to detect the type of project it was.  Unfortunately, in the past we didn't write anything in the .metadata file to identify the type of project, and since the goal was regenerating missing files, I can't count on *anything* existing, so it's kind of a heuristic match.

I'm going to simplify my heuristics down to just detecting the difference between "app" and "application" projects, and only detect the other types if they're listed in the .metadata file (which my code now does). People used to have to specify the type for those anyhow, so it shouldn't be a surprise to users.

Thanks for telling me about the ".idea" directory in the empty project, that helps.

**Comment by gspencergoog** [comment]
Yeah, I wasn't going to rely on that, but I was assuming initially that IntelliJ was just creating an empty dir, so knowing that it does put stuff in there makes me want to do something more generic.

**Comment by gspencergoog** [comment]
PR is approved: just waiting for PR checks to complete before committing.
