### ISSUE TITLE
[Material] RaisedButton text does not default to ColorScheme.onPrimary

### ISSUE THREAD

**Issue by willlarche** [flutter/flutter#22745]
Function `getTextColor` in `ButtonThemeData` on the case `ButtonTextTheme.normal` returns black or white. Material Guidelines expect `onPrimary` since the fill color is `primary`.

Details: Make backwards compatible with existing behavior.

![simulator screen shot - iphone x - 2018-10-05 at 14 16 20](https://user-images.githubusercontent.com/1271525/46560808-ec0b6c80-c8a9-11e8-849d-f0f95b50fd2e.png)

**Comment by willlarche** [comment]
@HansMuller

**Comment by Levi-Lesches** [comment]
How is this not expected? Doesn't onPrimary mean white or black depending on the `Brightness` of the primary color?

**Comment by willlarche** [comment]
`onPrimary` should be customized to fit in with the other colors in your scheme. Here's how the designer of Shrine did it: 
<img width="698" alt="Screen Shot 2019-08-19 at 11 46 22 AM" src="https://user-images.githubusercontent.com/1271525/63279446-fe4e8900-c276-11e9-9793-38c5787c8e47.png">

**Comment by Levi-Lesches** [comment]
Oh OK, seems like I need to take a closer look at Color Schemes again

**Comment by Levi-Lesches** [comment]
Any progress on this? #38646 needs this to be fixed, since AlertDialogs no longer respect normal theming, and rely solely on ColorSchemes now.

**Comment by bitsydarel** [comment]
Any update on this ?

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by bitsydarel** [comment]
is there a way to track the changes made in the framework regarding the colorScheme ?

**Comment by HansMuller** [comment]
@willlarche, @Levi-Lesches, @bitsydarel - it's been a long time since this issue was opened and I apologize for the lack of activity. If you're still interested in the topic, there's a wide-ranging proposal for updating the button widgets and their themes in #54776. The new proposal does bind the default button colors to the overall theme's ColorSchme, per the Material Design spec.

I'm going to close this issue in favor of #54776.
