### ISSUE TITLE
Support build, run and debug iOS under Linux

### ISSUE THREAD

**Issue by mathieujobin** [flutter/flutter#22771]
I understand this is a dependency on Xcode being only available for OSX

But I wanted to still open it out there, in case anyone had tried fancy hacks, or if there are enough demands, maybe Apple would listen.

I love flutter, a single code base for both Android and iOS is a huge thing for me and my team.

now if only people who choose to work with Linux could still build and test on their iphone, that'd be super awesome

**Comment by zoechi** [comment]
https://www.google.at/search?ei=pg26W4W1G4KLlwTC4ICoCg&q=ios+cloud+build
A common suggestion is https://apple.stackexchange.com/questions/302166/use-a-mac-mini-as-a-remote-build-server-for-an-ios-game

**Comment by gabrc52** [comment]
I'm currently experimenting on this. 

`libimobiledevice` and `ideviceinstaller` work on Linux just fine.

So, I built and installed (installing can be done on Linux using ideviceinstaller/Cydia Impactor) a Flutter app using macOS, and made the change below to Flutter, and rebuilt it using:

`dart --snapshot=./bin/cache/flutter_tools.snapshot --packages=./packages/flutter_tools/.packages 
./packages/flutter_tools/bin/flutter_tools.dart`

```diff
diff --git a/packages/flutter_tools/lib/src/ios/devices.dart b/packages/flutter_tools/lib/src/ios/devices.dart
index c55cb8533..3264a7ec7 100644
--- a/packages/flutter_tools/lib/src/ios/devices.dart
+++ b/packages/flutter_tools/lib/src/ios/devices.dart
@@ -103,7 +103,7 @@ class IOSDevices extends PollingDeviceDiscovery {
   IOSDevices() : super('iOS devices');
 
   @override
   @override
-  bool get supportsPlatform => platform.isMacOS;
+  bool get supportsPlatform => platform.isMacOS || platform.isLinux;
 
   @override
   bool get canListAnything => iosWorkflow.canListDevices;
```

After doing that, `flutter devices` and `flutter attach` work fine: I was able to hot restart and hot reload a Flutter app on my iOS device from Linux.

**Comment by mathieujobin** [comment]
And I thought Xmas was over... Thank you so much !!!!

**Comment by mathieujobin** [comment]
is your iOS device on iOS 12? Which Linux distribution are you using?
I think the packages available on Ubuntu 18.04 does not work with iOS 12 ...

**Comment by mathieujobin** [comment]
Cool, both of my iOS devices are seen by Flutter

```
mathieu:~ :-) (lifebook-wu2) $ flutter devices
Cannot control iOS devices or simulators. iproxy is not available on your platform.
1 connected device:

iPad de Mathieu • a2a...341 • ios • iOS 8.4
mathieu:~ :-) (lifebook-wu2) $ flutter devices
Cannot control iOS devices or simulators. iproxy is not available on your platform.
1 connected device:

Mathieu's iPhone • 4b9...538 • ios • iOS 12.1.2
```

Now if I could find a diff of whatever Xcode is adding to the project, I could try applying that manually..

```
$ flutter run
Cannot control iOS devices or simulators. iproxy is not available on your platform.
Running "flutter packages get" in multilearning...           4.9s
Launching lib/main.dart on Mathieu's iPhone in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
 $ uname -a 
Linux mathieu-FMVWB3U28 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by gabrc52** [comment]
Some things that could be done to do this in a more official and polished way:

* Don't depend on XCode (#26307).
* Allow building debug versions of apps by downloading precompiled Flutter binaries and libraries. Since Dart snapshots aren't platform-specific, they can be compiled without the need of a Mac. (I'm not sure if this could be done for release apps, but an official Google service for building Flutter apps for iOS in the cloud could be integrated to the flutter tool)
* The problem here would be signing these apps, this could be implemented like how Cydia Impactor signs apps (unfortunately it's closed source so it might require some reverse-engineering)

**Comment by gabrc52** [comment]
Open-source game engine Godot has some instructions on cross-compiling games created with it on Linux, this could be of help.

https://docs.godotengine.org/en/3.0/development/compiling/cross-compiling_for_ios_on_linux.html

**Comment by sivang** [comment]
> Cool, both of my iOS devices are seen by Flutter
> 
> ```
> mathieu:~ :-) (lifebook-wu2) $ flutter devices
> Cannot control iOS devices or simulators. iproxy is not available on your platform.
> 1 connected device:
> 
> iPad de Mathieu • a2a...341 • ios • iOS 8.4
> mathieu:~ :-) (lifebook-wu2) $ flutter devices
> Cannot control iOS devices or simulators. iproxy is not available on your platform.
> 1 connected device:
> 
> Mathieu's iPhone • 4b9...538 • ios • iOS 12.1.2
> ```
> Now if I could find a diff of whatever Xcode is adding to the project, I could try applying that manually..
> 
> ```
> $ flutter run
> Cannot control iOS devices or simulators. iproxy is not available on your platform.
> Running "flutter packages get" in multilearning...           4.9s
> Launching lib/main.dart on Mathieu's iPhone in debug mode...
> No application found for TargetPlatform.ios.
> Is your project missing an ios/Runner/Info.plist?
> Consider running "flutter create ." to create one.
>  $ uname -a 
> Linux mathieu-FMVWB3U28 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> ```

does this require having XCode or XCode libs somehow installed on your Linux box?

**Comment by gabrc52** [comment]
> does this require having XCode or XCode libs somehow installed on your Linux box?

To debug, hot reload, hot restart etc it's not necessary but you would have to build your app in debug mode using something like Travis-Ci or Codemagic. (See https://medium.com/flutter-community/developing-and-debugging-flutter-apps-for-ios-without-a-mac-8d362a8ec667)

**Comment by gabrc52** [comment]
It might be technically possible to build using something like this: https://github.com/tpoechtrager/cctools-port

**Comment by Skyost** [comment]
Maybe [Codemagic](https://codemagic.io) can be an alternative.

**Comment by stuartmorgan** [comment]
> Allow building debug versions of apps by downloading precompiled Flutter binaries and libraries. 

Having a prebuilt Flutter framework (which is already what's used) doesn't allow you to build the application (e.g., the iOS code generated by `flutter create`).

**Comment by gabrc52** [comment]
> Having a prebuilt Flutter framework (which is already what's used) doesn't allow you to build the application (e.g., the iOS code generated by flutter create).

Not for release mode, but how about debug mode (it would still be useful for development)? Isn't Dart code built in a platform independent mode when hot restarting? So, a prebuilt app with the same plugins, but configured to start paused, could be downloaded, and then Dart code could be deployed like when hot restarting, right?

**Comment by stuartmorgan** [comment]
> So, a prebuilt app with the same plugins

It's not clear to me how there could be a prebuilt runner for every possible combination of plugins and plugin versions.

**Comment by gabrc52** [comment]
Right, it wouldn't be possible especially when certain plugins require specific configurations. 

But it might be possible to have a build service (like Codemagic) called by the Flutter tool.

**Comment by gabrc52** [comment]
In a built iOS app in debug mode, there seems to be:

- **`Base.lproj`**: contains a launch screen, it doesn't seem to be app-specific unless it is customized

-  **`flutter_assets`**: it doesn't seem platform-specific, it's pretty similar on an APK

- **`Frameworks`**: it includes plugins, each in its own folder. Couldn't these be downloaded and added there? 

-  **`Assets.car`**: seems to contain some assets but they're Flutter specific since the app's assets are in `flutter_assets`

- `*.xconfig`, `*.plist`, `PkgInfo`, `*.png` files: they're generated based on the app's icon, package name, etc. but they could be obtained without macOS

- **`Runner`**: the app's actual executable. On a debug app it wouldn't have to contain the app's Dart code since it can be pushed via hot restart. Would it be possible to build it using something like [tpoechtrager/cctools-port](https://github.com/tpoechtrager/cctools-port)?

Please correct me if I'm wrong

**Comment by stuartmorgan** [comment]
> But it might be possible to have a build service (like Codemagic) called by the Flutter tool.

If you're saying it's possible to have a cloud service build iOS apps on demand, obviously that's theoretically possible, but that's very different than having a generic prebuilt runner that's part of Flutter.

**Comment by waynebloss** [comment]
Perhaps there will eventually be some downstream distribution of Flutter, like Expo for React Native which packages a runner along with a curated set of widely used, pre-configured plugins.

Then, only if and when you need anything outside of those plugins, you switch to setting up your Mac build server or service.

**Comment by samawong** [comment]
In my laptop,I get this error:
`sama@sama-Lab:~/program/ios_app$ flutter run
Launching lib/main.dart on iPhone in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
`
and I run flutter doctor -v :
`sama@sama-Lab:~/program/ios_app$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/sama/flutter
    • Framework revision 7a4c33425d (4 周前), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/sama/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/sama/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/sama/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPhone • 855b40fd70c8c0f641088a8541e0f82bdccfc82c • ios • iOS 12.3

• No issues found!
`
and my linux version 
`sama@sama-Lab:~/program/ios_app$ uname -a
Linux sama-Lab 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
then,how to fix this error?

**Comment by infinito84** [comment]
Guys is possible create a pull request with the latest version?, I think this is very useful, but I haven't been able to detect iPhone device from linux, doing the changes bot in last version, and using @gabrc52 's repo.

**Comment by christiantjl** [comment]
Always lovely to rely on hacks from Medium instead of the Flutter team just adding libimobiledevice/ideviceinstaller/iproxy dependencies for Linux flutter builds, since after a year the hacks don't work anymore and we're forced to work on shitty Apple hardware (`git apply ios.diff` fails now, mac.dart patch no longer works). 

Gotta love Apple's bullshit.

**Comment by christiantjl** [comment]
@gabrc52 Your articles and guidance have been super helpful, but unfortunately with a fast-paced framework like Flutter, the patch no longer works for the current version of mac.dart and I'm in way above my head trying to get hot reload / debugging on Linux to work. Any advice would be appreciated.

I went ahead and bought a Macbook so I have access to Xcode if necessary, but I'd really prefer to just use it for release builds rather than debugging on a laptop.

**Comment by christiantjl** [comment]
[I created a fork ](https://github.com/christiantjl/flutter)(my first fork actually, probably messed up by pushing to the stable branch rather than dev but oh well) here with libimobiledevice support.  Patch assumes these executables are in /usr/bin. 

`flutter attach` works, `flutter doctor -v` output looks good, but it just kinda sits there waiting for a connection from the device. It's running an older version of the app, so that might have something to do with it. Feel free to build on this if you guys want.

**Comment by csells** [comment]
this isn't on our roadmap
