### ISSUE TITLE
Does the flutter driver have plans to support the hybrid app?

### ISSUE THREAD

**Issue by Wanghuayin** [flutter/flutter#22809]
When I used flutter driver for integration testing on hybrid app, I found that only after Dart VM was started, the test would continue. Is there any way I could use the flutter driver for integration testing when native part before the flutter ?  @kangwang1988

**Comment by xster** [comment]
We're not going to support driver tests (since like you pointed out, Dart can't drive a test if the Dart VM isn't going to be started). But we'll support e2e testing via espresso and earl grey. 

We'll create some examples in our samples repository via https://github.com/flutter/flutter/issues/47396.
