### ISSUE TITLE
google_maps_flutter: Marker Z-Index behavior is inconsistent between android and ios platforms 

### ISSUE THREAD

**Issue by Soundbytes** [flutter/flutter#22864]
I just found that the Marker zIndex behaves differently on android and ios.
android: a Higher zindex will bring the marker to the foreground
ios:  higher zindex puts marker in the background.

Note: As you might have mentioned: I am using an outdated version of the package with ios support. I just thought the info might be helpful once the ios platform is going to be reenabled.

**Comment by Soundbytes** [comment]
It looks like you guys have fixed it. Can You confirm and close the issue? 
At least in my App I had to remove the workaround.
Thanks!

**Comment by felangel** [comment]
@Soundbytes what version are you using? We're still seeing this in version `0.5.21+3`

**Comment by eseidelGoogle** [comment]
It looks like the original reporter wishes to close this.

Since Flutter wraps the separate iOS and Android Maps SDKs it wouldn't surprise me if there are slight differences.  The source is here:
https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
for anyone wishing to investigate further.

@felangel would you be willing to file a new bug if you're still experiencing this?  Thanks.
