### ISSUE TITLE
VSC struggles when Flutter project is part of a monorepo

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#22865]
When Flutter is part of a monorepo VSC claims that the included `test/widget_test.dart` file does not import any packages. `flutter test` still works beautifully.

Here is a minimal repo showing the issue
https://github.com/lukepighetti/flutter-vsc-monorepo-mvce

Referenced here:
https://github.com/Dart-Code/Dart-Code/issues/1248

<img width="1268" alt="screen shot 2018-10-09 at 9 41 23 am" src="https://user-images.githubusercontent.com/666539/46673343-88ce5280-cba7-11e8-9669-04ac4ca0001c.png">

**Comment by zoechi** [comment]
@DanTup

**Comment by lukepighetti** [comment]
Sorry to split this I just wasn't sure where to put it!

**Comment by zoechi** [comment]
Is there still something to do?

**Comment by DanTup** [comment]
I'd say this is entirely a Dart Code issue. The problem is that the non-Flutter version of the Dart SDK was being used because the project wasn't detected as Flutter (because we only checked the folder that was opened, not its children) so the flutter packages didn't resolve.

The related issue is https://github.com/Dart-Code/Dart-Code/issues/1248 and in vNext we'll walk down one level when trying to decide whether to use Flutter's version of the SDK. There's a beta linked at the bottom of that issue for testing if anyone wants to try it before it's released.
