### ISSUE TITLE
Flutter packages containing assets are hard to manage and not intuitive

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#22921]
When working with flutter packages that might contain their own set of assets, Flutter does not make it very intuitive to manage those assets. 

In a normal Flutter application, a developer would usually include their assets in an `assets` folder, and then these would be registered in the `pubspec.yaml`, either by adding the full path of the asset, or by adding a relative path that will include all the assets under that directory.

This is not true when working with packages: a developer needs to add those under `lib`, and then register those as `- packages/my_project/assets/my_asset.png`, for example. This is counter intuitive, and does not follow the pattern established for applications. Furthermore, it seems like you can't add relative paths, so in packages where there's a decent amount of assets, it becomes a very time consuming task.

Is there any special reason to keep it this way? What can be done to change this design?

**Comment by jorgecoca** [comment]
For projects that create widget catalogs, for example, this is a very important topic IMO.

**Comment by zoechi** [comment]
The reason it works this way is that this conforms to the pub package layout convention.
Only content in `lib/` is available to importing packages/applications. 
Everything else is just relevant for the development of the package itself, not to consumers (except `bin/` for Dart command line apps). 

Since recently it is supported to just add a directory to `assets:` to register its (direct - not subdirectories) content at once.

There was a comment to my answer in https://stackoverflow.com/a/52754158/217408 that seems to indicate this doesn't work for assets from packages (I'm waiting for a response to a follow up question).

I think it's unrealistic to hope for support for files outside `lib/` because it would require to overhauls the entire Dart ecosystem. I assume once you understand how Dart packages work, this won't be an issue anyway.

If importing directories does not work the same from packages as for assets provided in the application, please create a more specific issue.

Otherwise please elaborate more on what is counterintuitive with

> register those as - packages/my_project/assets/my_asset.png, for example. This is counter intuitive, 

See also 

- https://flutter.io/assets-and-images/#from-packages
- https://www.dartlang.org/tools/pub/get-started#importing-libraries-from-packages

**Comment by zoechi** [comment]
#22944 is the issue about adding an asset folder from resource packages

**Comment by jonahwilliams** [comment]
De-duping into https://github.com/flutter/flutter/issues/27802
