### ISSUE TITLE
nit: flutter doctor output inconsistent for IDE plugins

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#22931]
```
[✓] Flutter (Channel master, v0.10.1-pre.17, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.10.1-pre.17 at /Users/goderbauer/dev/flutter
    • Framework revision 9c01c2b836 (3 weeks ago), 2018-09-18 15:34:46 +0800
    • Engine revision bc6df5bc34
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/goderbauer/Library/Android/sdk
    • Android NDK at /Users/goderbauer/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode_9_4_1.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel XL   • HT6AM0200752                             • android-arm64 • Android 8.0.0 (API 26)
    • Red iPhone • a5295d92abf4a4e63a55f9eabad8571fa7af0440 • ios           • iOS 11.4
```

Android Studio and VS Code are both missing the plugins. Yet, Android studio gets a checkmark, while VS Code has an exclamation mark. Also, the bullets pointing out the missing plugin are different (✗ vs •) and the Android Studio line is printed bold in my terminal whereas the VS Code line is just regular.

/cc @gspencergoog @DanTup

**Comment by DanTup** [comment]
I've changed this to be consistent (VS Code copying Android Studio) but before I open a PR - are we sure the Android Studio behaviour is correct? It seems strange to show a tick against an IDE if it doesn't have the plugin (and has a cross inside it). Shouldn't we use Partial for an IDE that is missing a plugin (since without the plugin, what's the point of it being listed in Doctor - it's just an editor you have installed and is *not* set up for Flutter dev).

(cc @devoncarew)

**Comment by DanTup** [comment]
Chatted with @devoncarew about this, and we think it would be best if the IDE sections showed the `!` ("partial") mark if they have not-installed plugins within them - it seems a bit strange to put a tick next to an IDE that is installed, but doesn't have the plugins.

So, I'll update my change and open a PR so that:

1. The VS Code "missing extension" note will have a X cross
2. The Android Studio section will have a ! warning instead of a tick if it's missing plugins
