### ISSUE TITLE
Camera error !

### ISSUE THREAD

**Issue by ahmdrz** [flutter/flutter#23039]
I wrote a camera application to take pictures or record videos.
Taking pictures work perfectly but when I press button to stop video recorder , I've get an error :
```
I/flutter (16837): /storage/emulated/0/CantonFair/Categories/test/4bc6b03a-202b-4bdd-b3ae-2068bfdf0e31/Movies/1539402896640.mp4
I/RequestQueue(16837): Repeating capture request cancelled.
I/CameraDeviceState(16837): Legacy camera service transitioning to state IDLE
I/CameraDeviceState(16837): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(16837): Configure outputs: 2 surfaces configured.
D/Camera  (16837): app passed NULL surface
I/CameraDeviceState(16837): Legacy camera service transitioning to state IDLE
I/RequestQueue(16837): Repeating capture request set.
W/LegacyRequestMapper(16837): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper(16837): Only received metering rectangles with weight 0.
W/LegacyRequestMapper(16837): Only received metering rectangles with weight 0.
I/CameraDeviceState(16837): Legacy camera service transitioning to state CAPTURING
W/Adreno-EGLSUB(16837): <DequeueBuffer:721>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL(16837): <qeglDrvAPI_eglSwapBuffers:3800>: EGL_BAD_SURFACE
E/CameraDeviceGLThread-0(16837): Received exception on GL render thread:
E/CameraDeviceGLThread-0(16837): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-0(16837): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-0(16837): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-0(16837): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:727)
E/CameraDeviceGLThread-0(16837): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-0(16837): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-0(16837): 	at android.os.Looper.loop(Looper.java:148)
E/CameraDeviceGLThread-0(16837): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/CameraDeviceState(16837): Legacy camera service transitioning to state ERROR
E/CameraCaptureSession(16837): Session 1: Exception while stopping repeating:
E/CameraCaptureSession(16837): android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
E/CameraCaptureSession(16837): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2000)
E/CameraCaptureSession(16837): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:913)
E/CameraCaptureSession(16837): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
E/CameraCaptureSession(16837): 	at io.flutter.plugins.camera.CameraPlugin$Camera.closeCaptureSession(CameraPlugin.java:719)
E/CameraCaptureSession(16837): 	at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:666)
E/CameraCaptureSession(16837): 	at io.flutter.plugins.camera.CameraPlugin$Camera.stopVideoRecording(CameraPlugin.java:658)
E/CameraCaptureSession(16837): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:244)
E/CameraCaptureSession(16837): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:201)
E/CameraCaptureSession(16837): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/CameraCaptureSession(16837): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/CameraCaptureSession(16837): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraCaptureSession(16837): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/CameraCaptureSession(16837): 	at android.os.Looper.loop(Looper.java:135)
E/CameraCaptureSession(16837): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/CameraCaptureSession(16837): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(16837): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/CameraCaptureSession(16837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I/flutter (16837): Error: videoRecordingFailed
I/flutter (16837): Error Message: The camera device has encountered a serious error
```

I'm new in Dart and Flutter and my application is an open souce app, named [CantonFair](https://github.com/ahmdrz/CantonFair2018)

**Note** that I this error on `Lenovo Yoga Tab3` with Android 6.0.1, But this app working perfectly on Android 8.0.0

**Comment by ahmdrz** [comment]
Same as #18138

**Comment by zoechi** [comment]
Merging with #18138
Thanks @ahmdrz for finding the issue!

**Comment by ahmdrz** [comment]
Long time no response on #18138 
How can I fix it?

**Comment by zoechi** [comment]
I don't know how to fix.
Upvoted to increase priority.

**Comment by ahmdrz** [comment]
Thank you @zoechi .

**Comment by Chank1e** [comment]
@ahmdrz I don't really know is my solution would be helpful, but it works on my device.
Firstly, I've changed  
```java
private void stopVideoRecording(@NonNull final Result result)
```
method at **CameraPlugin.java**.
Now it looks like:
```java
private void stopVideoRecording(@NonNull final Result result) {
      if (!recordingVideo) {
        result.success(null);
        return;
      }

      try {
        recordingVideo = false;
        mediaRecorder.stop();
        mediaRecorder.reset();
        //startPreview();
        result.success(null);
      } catch ( IllegalStateException e) {
        result.error("videoRecordingFailed", e.getMessage(), null);
      }
    }
```
I just deleted `CameraAccessException` from `catch` block and commented `startPreview()`. After that 

```dart
await controller.stopVideoRecording();
```
should work.
You just need to "restart" your video controller and start preview by executing:
```dart
await controller.dispose();
controller = CameraController(cameraDescription, ResolutionPreset.high);
```

This works on my Xiaomi Redmi Note 4 and Android Pixel 2 emulator.
But now it take a few seconds to save video(or smth like that), but it works)

**Comment by ahmdrz** [comment]
I've used ImagePicker to record video instead of Camera.
Thank you @Chank1e, Can you create a full example of your code?

**Comment by Chank1e** [comment]
@ahmdrz No problem, I'll create a full example soon.
But via ImagePicker you'll always use default camera without possibility to use your own UI. Am I wrong or not?

**Comment by ahmdrz** [comment]
Yes we can't use own UI
But It was the only way for me

**Comment by xperiafan13-rom** [comment]
I have similar error
java.lang.IllegalArgumentException: submitRequestList:221: Request targets Surface that is not part of current capture session
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:651)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:86)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:935)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:824)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:181)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at io.flutter.plugins.camera.CameraPlugin$Camera.takePicture(CameraPlugin.java:601)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:270)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:196)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/MethodChannel#plugins.flutter.io/camera(13304): Caused by: android.os.ServiceSpecificException: submitRequestList:221: Request targets Surface that is not part of current capture session (code 3)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.os.Parcel.readException(Parcel.java:1960)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.os.Parcel.readException(Parcel.java:1892)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.submitRequestList(ICameraDeviceUser.java:334)
E/MethodChannel#plugins.flutter.io/camera(13304): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:84)
E/MethodChannel#plugins.flutter.io/camera(13304): 	... 15 more

Any hel!

**Comment by Petka17** [comment]
I've added `closeCaptureSession();` before `mediaRecorder.stop();` and it helped.

In order to utilize that change, I had to fork the plugin repository and use it in `pubspec.yml`

```
    private void stopVideoRecording(@NonNull final Result result) {
      if (!recordingVideo) {
        result.success(null);
        return;
      }

      try {
        recordingVideo = false;
        closeCaptureSession();
        mediaRecorder.stop();
        mediaRecorder.reset();
        startPreview();
        result.success(null);
      } catch (CameraAccessException | IllegalStateException e) {
        result.error("videoRecordingFailed", e.getMessage(), null);
      }
   ```
