### ISSUE TITLE
InputDecoration's hintText is announced to screen reader when non empty value is present

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#23119]
I have a `TextField` with an `InputDecoration` that specifies a `hintText`. I expect the `hintText` to be announced when the text field is empty. However, it's still read off when the text field has a value. With TalkBack, this sounds like: "{Actual Value} {Hint Text} Edit Box. Showing {Keyboard Type} Keyboard".

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
This _roughly_ matches the behavior of other text fields with a hint text that is hidden during typing. For example, open up the play store and focus the search box:
```
"Editing search google play edit box"
"t t"
"e e"
"s s"
"t t"
```
Then double tap on the field again:
```
"Editing test edit box, search google play"
```
In the gallery it reads off:
```
"Editing test what do people call you edit box"
```
This is because we don't use the [setHintText](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#setHintText(java.lang.CharSequence)) API, since it is 26+. Its not clear to me what the right thing to do here, as there is no spec for text field a11y behavior.

We could add a "secondaryLabel" semantics and only use it for the text field, and use it to set the hintText or drop it on the floor otherwise.

**Comment by jonahwilliams** [comment]
As a stopgap measure, I can remove the hint text whenever there is input.

**Comment by alanrussian** [comment]
Thanks for looking into this.

In the use case I have, it doesn't make sense to announce the value. I have a text field for a number where the hint text is zero. If a user enters in a number (e.g., 123), it really doesn't make sense to read "123 0 edit box".

I haven't tried, but I'm guessing we could also remove the hint text when the text field has a value. If you think that's the best solution for us, I could pursue that approach.

**Comment by alanrussian** [comment]
Got it, thanks for the detailed explanation. Sounds like this is WAI then?

**Comment by jonahwilliams** [comment]
In general the TextField needs some work, but in your case I think the solution is updating the decoration if possible.

**Comment by Hixie** [comment]
Closing per @jonahwilliams' comments.
