### ISSUE TITLE
Complex_layout_scroll_perf__timeline_summary worst_frame_build_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#23172]
20ms -> 56ms after https://github.com/flutter/flutter/commit/8e2ca93f52d82d22df8b987cef74238ac53b4b28

Similar regressions for complex_layout_semantics_perf initialSemanticsTreeCreation

**Comment by liyuqian** [comment]
@goderbauer : any idea on what's causing the regression?

**Comment by jacob314** [comment]
The problem is those benchmarks are skewed by whether a major GC occurs before or after the benchmark starts timing. With the removed code, it is more likely a GC will occur after the benchmark starts. The simplest fix is to force a GC before starting each of these benchmarks.

**Comment by goderbauer** [comment]
What @jacob314 said is probably the issue. If it is blocking anything feel free to revert the PR. As soon as I can I will try to force a GC with the mechanism provided by https://github.com/dart-lang/sdk/issues/34618 before those benchmarks to see if that fixes things.

**Comment by goderbauer** [comment]
Forcing a GC is blocked on me not understanding how I am supposed to call it: https://github.com/goderbauer/flutter/commit/ee2afb2c5a343384b9eb12d3f32701a7842f6f5a

**Comment by mraleph** [comment]
I still think this is a wrong way to fix this benchmark. Users are *not going* to have GC invoked before benchmark run - so the number you are measuring is too idealized and does not reflect real world performance. You will see 20ms in the testing environment, but users might see 56ms. 

Imagine you have a function `f()` and you want to have how fast it works. An important thing to realize  here is that if `f()` performs any sort of allocation then `f()`'s performance is not a single number but a distribution of possible outcomes - depending on the state of the memory management infrastructure (e.g. amount of live data in the heap).

I have been thinking about this benchmark and I came to realize that because it is based on the timeline recording you actually know exactly how many GCs were triggered and what type they were. I think the right approach for this benchmark is to simply report measurements with GC time excluded - this would be pure best case performance. You can also report time with GC included - that would give you some sort of "worst case" approximation. The real performance would be somewhere in between.

**Comment by goderbauer** [comment]
Naively subtracting GC time from the event time is giving me negative numbers (code is in https://github.com/goderbauer/flutter/commit/7dedfcf32517def7e066d9251cb31e672305e359):

```
{
  "success": true,
  "data": {
    "initialSemanticsTreeCreation": 98,
    "initialSemanticsTreeCreationExcludingGc": -89,
    "gc": 187
  },
  "benchmarkScoreKeys": [
    "initialSemanticsTreeCreation"
  ]
}
```

@mraleph Which GC events do I need to subtract to make this correct?

**Comment by mraleph** [comment]
@goderbauer you need to exclude those GC events that are nested within "initialSemanticsTreeCreation" time line event.

**Comment by Hixie** [comment]
I'm not sure I agree that removing the GC times is the right approach. The problem isn't the GCs per se, the problem is that the GC environment is variable at the start of this benchmark, such that sometimes we're almost due for a GC, and sometimes we're not, unrelated to things this benchmark does. I think triggering a GC immediately prior is exactly the right solution to that problem.

I definitely don't want to just exclude GC times from the benchmark. That would just mean we were ignoring GCs, and GCs are a big cause of jank and performance issues, maybe even the biggest.

**Comment by goderbauer** [comment]
For the record: https://github.com/flutter/flutter/pull/23289 implements the approach were we force a GC before two of the benchmarks that are known to be GC sensitive.
