### ISSUE TITLE
FlutterFragment not retaining state when rotation happens

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#23376]
Hey guys, actually I've already solved this problem and documentated it on this stack overflow:
https://stackoverflow.com/questions/52935136/flutterfragment-is-not-retaining-state

Would be important and usefull if you could add this information on the official documentation at: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

It will be very handy for others trying to embed Flutter on existing apps.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by shinayser** [comment]
Zoechi, as my post said, I've already found a solution. I am just sharing knowledge to those with the same problems. Please consider adding it to the official docs.

**Comment by xster** [comment]
@matthew-carroll to confirm but I think this is now properly covered in the documentation at https://add-to-app-2019.firebaseapp.com/docs/development/add-to-app/android/add-flutter-screen

**Comment by matthew-carroll** [comment]
Yeah, the state of this issue is:

- A `FlutterFragment` that uses a cached engine will automatically retain state as a result of the very concept of using a cached engine
- A `FlutterFragment` that is explicitly set to "retain instance" will not be destroyed on config changes, so the `FlutterFragment` and its `FlutterEngine` will both survive orientation change
- A `FlutterFragment` that is not set to "retain instance", or one that is used in a backstack, with no cached engine, will lose state on orientation change because the `FlutterFragment` will destroy its previous `FlutterEngine` and create a new one.

@xster do you think that 3rd point above is worth reconsideration? I think it's probably OK because developers can take clear steps to avoid it, but we can discuss it if you'd like.

**Comment by matthew-carroll** [comment]
I'll close the issue. We can re-open if additional work is found.
