### ISSUE TITLE
Should pushLayer offset always be zero?

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#23431]
In several places, we call pushLayer() with a non-zero offset. Does this make any sense? Consider, for example, a metadata layer that corresponds to a small square on the screen. If we pass the paint() offset through to the pushLayer, and thus down from there to next render object's painter, the metadata layer isn't going to be the right size and the hit-testing will find it even in places where it should not.

cc @goderbauer @liyuqian

**Comment by liyuqian** [comment]
Short answer: mostly yes; do you have a sample code to reproduce a non-zero offset and a broken hit test?

I believe that calling `pushLayer()` with an `offset` is because we previously only have offset in the leaf layers (e.g., PictureLayer, TextureLayer, etc.) so we have to send the cumulative offsets all the way down to the leaf layers for correct rendering.

After retained rendering, the offset is consumed as soon as possible so those offsets should be zero in most cases (code coverage tool says that all `layerOffset` is always zero in [`ContainerLayer.addChildrenToScene`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L573) during `flutter test` inside flutter/flutter/package/flutter). So I think although `pushLayer` takes an offset, that offset is rarely non-zero. Do you have a sample code that triggers `pushLayer` with non-zero offset?

As for hit testing, I think that it happens on the RenderObject level, not on the Layer level. Therefore any change to Layer's paint offset shouldn't break it (as long as we're still painting things in the same place).

Please let me know if I misunderstood the question or if my answer is incorrect. Maybe we need an offline discussion for more details.
