### ISSUE TITLE
Release version of app crashes on startup if firebase_ml_vision is added in pubspec.yaml

### ISSUE THREAD

**Issue by ankit9607** [flutter/flutter#23479]
**Steps to Reproduce**

1. create new Project `flutter create foo` .
2. Include firebase_ml_vision: in the `pubspec.yaml` dependencies.
3. Link Firebase account with your app through add `google-services.json` file in android>app folder.
4. create release version of your app `flutter clean && flutter build apk`
5. Install this apk to Emulator through Drag & Drop or install manually to your device.
6. Remove `firebase_ml_vision:` from `pubsec.yaml`
7. follow stemp 4,5 and your app will work properly.

**Flutter Doctor Output**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by zoechi** [comment]
Could be a dup of one of #22791,  #22345, #20786

Do I understand your explanation correctly that in step "5.1 run the app" the app crashes?
Have you tried to get any log output?
Do only release builds crash?

**Comment by zoechi** [comment]
You could try with `dev` or `master` channel.

**Comment by ankit9607** [comment]
Any Update ?

**Comment by CanKattwinkel** [comment]
It is a shame that a plugin that is actively promoted at conferences cannot be built into a release app.

I can reproduce and confirm this is still an issue:


```
flutter channel dev
flutter clean && flutter build apk && flutter install -d emulator-xxxx
```

In a new project with no changes but added `  firebase_ml_vision: 0.2.1` to dependencies. Build with active `dev` channel. 


@zoechi any update on this?

@ankit9607 could you somehow work around this issue? 

I have no plans in releasing my app to an app-store since it is only used for a showcase at work but probably a release apk positively affects the performance of the app and therefore I'd love to be able to build a release APK.

**Comment by zoechi** [comment]
Sounds like #8824

**Comment by Kleak** [comment]
Get the same problem today...
App are working in debug mode on smartphone but as soon has i build a release apk it crash.

Here are some more information :

## Steps to Reproduce

1. `git clone git@github.com:flutter/plugins.git`
2. `cd plugins/packages/firebase_ml_vision/`
3. `flutter build apk`
4. `flutter install -d device_id`

## Flutter analyze
```
Analyzing example...                                             
No issues found! (ran in 2.6s)
```

## Flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/kevin/Work/github.com/flutter/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/kevin/Android/Sdk
    • Android NDK at /home/kevin/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/kevin/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5199772/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/kevin/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5199772
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • 8BQX1E3WK • 8BQX1E3WK        • android-arm   • Android null (API null)
    • TA 1012   • NB1GAS3771407100 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by kangwang1988** [comment]
@Kleak 
Please check your crash log with adb logcat and check if it's resulted from 'couldn't find "libflutter.so"'.

**Comment by Kleak** [comment]
no i don't have this message but i have this one 3 times 
```
2019-02-10 20:16:35.805 1353-5108/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.santetis.barcode3/com.santetis.barcode3.MainActivity/1
```

and that one, one time

```
2019-02-10 20:16:35.868 20009-20009/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.santetis.barcode3, PID: 20009
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.santetis.barcode3-C8zQGf0Pfgyh7zjXbvQXKw==/base.apk"],nativeLibraryDirectories=[/data/app/com.santetis.barcode3-C8zQGf0Pfgyh7zjXbvQXKw==/lib/arm64, /data/app/com.santetis.barcode3-C8zQGf0Pfgyh7zjXbvQXKw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5918)
        at android.app.ActivityThread.access$1100(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kaxp** [comment]
Hi all, I'm also facing this same issue after migrating my project to AndroidX. The debug apk is working fine but the released apk just stuck at startup and then crashes after some time. Previously without androidX i have published the same app to play store but after migrating it to the androidX all this problem started. even undoing the androidX is not helping. 

I have tried everything suggested by other developers in other Issues ( #22791, #22345, #20786 ) as well but nothing worked for me.
Please help as this is my First Flutter app and now without the released apk I cannot update my app on play store as it is crashing for some devices due to Image_picker.. 

My Flutter doctor shows
************* 
• No issues found!
Process finished with exit code 0.

my pubspec is-

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  image_picker:
  font_awesome_flutter:
  dio:
  google_sign_in:
  http:
  flutter_webview_plugin:
  url_launcher:
  fluttertoast:
  oktoast:
  launch_review:
  flutter_speed_dial:
#  esys_flutter_share: 1.0.0
  connectivity:
  intl:
  flushbar:
  flutter_crashlytics:
  video_player:
  json_annotation:
  flutter_facebook_login:
  firebase_analytics:
  firebase_messaging:
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons:

and for app/build.gradle-
compileSdkVersion 28
minifyEnabled false
multiDexEnabled true
even package name is manifest and build.gradle is same. 

I have also tried to clone my code from February when I don't even know about androidX, but that code is also showing error related to androidX now, i.e app not compatible to androidX

If u want any other thing plz let me know,
Thanks in advance.
@zoechi 
@Kleak 
@kangwang1988 
@CanKattwinkel

**Comment by panuavakul** [comment]
I'm not sure if this will help anyone but I was getting
```
couldn't find "libflutter.so"
```
error and this article solved my problem.

https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd

**Comment by kroikie** [comment]
@ankit9607

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1163. Any further collaboration will be done there.
