### ISSUE TITLE
Is it possible to show a thumbnail of a video file?

### ISSUE THREAD

**Issue by baseten** [flutter/flutter#23503]
I'm getting video files using the `image_picker` library: `ImagePicker.pickVideo` and I'd like to be able to show the user a list of thumbnails of videos they've captured. `Image.file(videoFile)` won't work for videos. Is this possible in flutter? Can't seem to find any documentation regarding it and there are a couple of unanswered SO posts regarding this:

https://stackoverflow.com/questions/47834495/flutter-display-video-like-image
https://stackoverflow.com/questions/52838120/how-to-make-video-thumbnail-in-flutter

**Comment by YWD** [comment]
waiting...

**Comment by cyanglaz** [comment]
Although I agree it is a good feature to have, I don't think it should be a part of the image_picker. It might be reasonable a part of the video_player plugin. see https://github.com/flutter/flutter/issues/27950 and https://github.com/flutter/flutter/issues/26194. And there seems to be some packages in pubs already doing this. You can find some good one and use it before this functionality is in the first party video_player plugin.
I am going to close the issue. Please feel free to reopen the issue if you think otherwise.

**Comment by Ahmadre** [comment]
If anyone is interested in a flutter-web solution: 
```dart
  void getVideoThumbnail(String path, int secs, callback) {
    html.VideoElement video = html.document.createElement('video');
    video.src = path;

    video.onSeeked.listen((html.Event e) {
      html.CanvasElement canvas = html.document.createElement('canvas');
      canvas.height = video.videoHeight;
      canvas.width = video.videoWidth;
      html.CanvasRenderingContext2D ctx = canvas.getContext('2d');
      ctx.drawImage(video, canvas.width, canvas.height);
      html.ImageElement img = new html.ImageElement();
      img.src = canvas.toDataUrl();
      callback.call(img, e);
    });
    video.onError.listen((html.Event e) {
      callback.call(null, e);
    });
  }
```

**Comment by rnithin133** [comment]
https://medium.com/@sreedevr/creating-thumbnail-from-video-in-flutter-d569000eaeac

I hope this may help you...

**Comment by abdullah432** [comment]
> https://medium.com/@sreedevr/creating-thumbnail-from-video-in-flutter-d569000eaeac
> 
> I hope this may help you...

It's recreating the thumbnail when comeback to page after navigation. Need something like CacheNetworkImage
