### ISSUE TITLE
Explore more retained rendering

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#23535]
After finishing our first milestone of retained rendering (https://github.com/flutter/flutter/issues/21756), let's explore what more we can achieve with retained rendering. Here are some examples:

- [x] Explore `PhysicalShapeLayer` in Fuchsia: https://github.com/flutter/engine/pull/6558
- [ ] Explore if we can add an option to `RepaintBoundary` and improve performance significantly by using snapshot of a layer subtree that's not a child of an `OpacityLayer`. See https://github.com/flutter/flutter/issues/32662.

**Comment by Hixie** [comment]
@liyuqian Can you elaborate on "Explore if we can add an option to `RepaintBoundary` and improve performance significantly by using snapshot of a layer subtree that's not a child of an `OpacityLayer`"?

**Comment by liyuqian** [comment]
@Hixie : I was thinking about raster caching the whole layer subtree for either a `TransformLayer` (https://github.com/flutter/flutter/issues/24627),  or an `ImageFiltered` layer. See https://github.com/flutter/flutter/issues/32662 for more details. @flar has been doing a lot of work recently (including introducing the new `ImageFiltered` layer https://github.com/flutter/engine/pull/14491). So @flar may be able to provide more details.

**Comment by flar** [comment]
ImageFiltered does cache if its child layer is stable, but it is only stable if you use a RepaintBoundary.

Right now we recreate a lot of layers even if nothing changes. I'm still digging into our strategies there, but a lot of it probably hinges on the way that we manage Picture layers. They are recreated if the part of the tree they are in is visited even if they themselves don't involve any Widgets/RenderObjects that changed.

They are also created from groups of RenderObjects that are next to each other in a depth-first traversal of the tree, but that don't necessarily all descend from a single parent. If the picture was generated from a single RenderObject then we might be able to just check a flag on that object, but pictures are actually generated from a group of them and since they aren't aware that they are all contributing to the same picture together, we end up with no specific flag that can be checked to see if the picture is dirty and so we pessimistically recreate it every time we traverse the tree.

I have a change pending that can try to make a better determination if a picture is actually changing, but it is more reactive than I'd like and it doesn't have as much impact as I'd like to see. I'm still investigating its potential and thinking of alternate solutions. A preliminary version of it can be seen in a branch on my fork of the framework repo in this commit: https://github.com/flar/flutter/commit/bc131bf7b28d5c3d984b0f839e982bcd86a57cd6

If we can get our layers to be reused more then it becomes a lot more feasible to cache layer renderings in the engine with a few lines of code in the engine layers and potentially without requiring developers to use RepaintBoundary all the time.

**Comment by jonahwilliams** [comment]
Impeller is moving away from full scene or layer based caching. Closing as obsolete.
