### ISSUE TITLE
[Suggestion] Combined Material & Cupertino App Type

### ISSUE THREAD

**Issue by alantbarlow** [flutter/flutter#23577]
Currently you can either choose to create a Material App (Android Style) or a Cupertino App (IOS Style). In the article below it explains how to combine the two to have native looking apps. My Suggestion is to create a 3rd App type, called Platform App, that combines the two other types of apps. Each widget for the Platform App would have its own documentation just like the other ones, and would work on both platforms. Every widget listed under Material App would be linked to the Cupertino
App equivelent and visa versa. If a widget doesn't have an equivalent, then it should just work the same on both platforms.

The benefits of this idea would be to build platform specific apps using a shared library as opposed to separate ones, share code between apps even though they look different, and the need to learn only one widget library as opposed to two different ones.

https://medium.com/flutter-io/do-flutter-apps-dream-of-platform-aware-widgets-7d7ed7b4624d

**Comment by charafau** [comment]
I'd suggest you to take a look at this library: https://pub.dartlang.org/packages/flutter_platform_widgets

**Comment by xster** [comment]
I'll tentatively dupe this into #24766 and address this.

**Comment by sosite** [comment]
@xster Why this issue has been closed if it points into missing framework feature, not into wrong documentation?

**Comment by galeyang** [comment]
Hello from the Flutter team!

If you’re following this discussion, we are looking for a few Flutter developers to share their experience on **developing Flutter apps that have a platform-specific look & feel for both iOS and Android.** This study will help the Flutter team better understand your needs in order to incorporate them into future enhancements.

Details of the study:
- The duration of the remote study is up to 60 minutes.
- You will be asked to provide your published app’s URLs to both app stores and walk through the design to development process, including getting design spec and Flutter implementation of platform-specific theming on both iOS and Android.
- You will receive a gift code after attending the session.

If you’re interested, please fill out this short questionnaire: https://forms.gle/i7uWQohBdGh2nanWA to verify your eligibility.

Thank you very much for your help!
