### ISSUE TITLE
Provide a plugin for rendering platform modal dialogs [datepicker, timepicker, title/text alert]

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#23594]
This comes up in add-to-app use cases where using small FlutterViews inside say an NSCollection view.

customer:truth has run into this.  There are at least 2 ways to solve this:
1.  Calling out to OEM dialogs via Platform Channels (which of course would render over the top)
2. Being able to render to multiple Views from a single Flutter isolate (and thus have a flutter-rendered dialog appear in a separate FlutterView on top of the smaller view).

I believe truth is currently looking at #1. 

FYI @mehmetf @matthew-carroll

**Comment by matthew-carroll** [comment]
This same issue was raised by @mit-mit.  By 2 cents is that the level of entanglement to pull off #2 is probably prohibitive, especially in a general sense.

#1 makes much more sense to me because the nature of a popup or popover is to exist within a fullscreen overlay, so when Flutter isn't fullscreen this responsibility then falls to the platform rather than the small FlutterView on the screen.

**Comment by Hixie** [comment]
We should talk more about this. There's a lot of reasons why we'd want to be able to support multiwindow in general, this being one of them.

**Comment by Hixie** [comment]
My general idea for how this would work:

Window gets split into two, a superclass and a subclass. Most of the members go on the subclass, the superclass needs only basic things like dimensions.

The engine would provide an API to the embedder to allow the embedder to say "here's a new place for you to provide pixels" (e.g. "Here's a new SurfaceView"). It would get back a token identifying that render surface. Simultaneously, a new Window object (instance of our new superclass) would be made available in dart:ui.

The framework would add a new Layer or equivalent that renders to this new Window instead of to the root window.

Widgets that want to show popup windows would inform the embedder via platform channels that they want to do so, wait for the embedder to send back the token, then look up the Window with that token, and render to it.

**Comment by eseidelGoogle** [comment]
customer: truth I don't think needs a flutter-only solution.  I believe an example of calling out to iOS or Android dialogs from within a small FlutterView would be sufficient for their needs.  @mehmetf can confirm.

**Comment by mehmetf** [comment]
That's correct.

**Comment by matthew-carroll** [comment]
Yeah I would split the issue of multi-window from the issue of popups and popovers as raised here.  There likely isn't much value to be found in offering Flutter control of popups and popovers - they tend to present very simple, static content, and people expect them to match the platform UI.

But multi-window is an interesting topic in general.  I'd like to sit in on any related discussions.  Also @Hixie's proposal would have implications for the embedding APIs.  Either we would need to introduce a variation of FlutterView, like FlutterWindowView, or we'd need to adjust the API for the existing FlutterView.

**Comment by Hixie** [comment]
If this isn't multiwindow, then it's not clear to me what else we need to do here? Can someone clarify what deliverable this bug represents?

**Comment by matthew-carroll** [comment]
I think the goal is pretty clear: provide a path to display dialogs when Flutter is used as a partial UI. 

To that end I recommend either offering a built in platform channel or an official plugin that facilitates alert dialogs on the given platform. On iOS the visual controls are very limited for a standard alert dialog so it’s pretty easy. Android requires a little more thought. 

But that’s the deliverable and a recommendation.

**Comment by Hixie** [comment]
How would we know what to show? Isn't that entirely up to the app?

We already provide a way to send a message to the platform-specific code, I just don't see what our code would do beyond just be a trivial wrapper around that.

**Comment by matthew-carroll** [comment]
We could, for example, allow a dev to say something like the following (pseudo code)

ModalDialog
  .with(myTitle, myMessage)
  .andButton(title, onPress)
  .display()

That would be an easy API to display a standard iOS alert dialog from flutter and that API is essentially enough to cover the gamut. 

Nothing prevents developers from implementing this themselves, but I think this is what the ticket is looking for. I do see value in not requiring every team to build this same thing for their partial flutter areas.

**Comment by matthew-carroll** [comment]
To your question about the specific customer, I don't know, only the customer can answer that.

To the notion of displaying date pickers in alert dialogs - I understand that Flutter lets us do this, but we should at least acknowledge that iOS does not.  A standard iOS app does not have any such generic APIs that I'm aware of for sticking arbitrary content in alert dialogs.

Beyond the single customer in question, I think there is a real possibility that simple alert dialogs are desired, which we can certainly provide.  If you'd like to wait for a customer request for that specific ability then that's fine.  It is difficult to source add2app customer use-cases because it is currently very difficult to achieve add2app.  We may see requests like this appear once add2app is easily do-able across both Android and iOS.

**Comment by Hixie** [comment]
We have to address all platforms, not the lowest common denominator. I agree that we could handle iOS's simple cases easily enough with a plugin. I just don't think those are the actual cases that this bug was filed to address (based on the demos I saw of customer:dream's app).

**Comment by Hixie** [comment]
(On iOS, the date picker case would be handled by a bottom sheet, probably. But that's more or less the same problem as we're discussing here.)

**Comment by Hixie** [comment]
Multiwindow is https://github.com/flutter/flutter/issues/25526.

**Comment by mehmetf** [comment]
To differentiate this further from multiwindow, let's provide a plugin that lets apps open 3 basic dialogs on both platforms:

- DatePicker
- TimePicker
- Basic Dialog (Support title, description and up to two buttons)

**Comment by mehmetf** [comment]
This blocks the full evaluation by customer: truth thus marking as such.

**Comment by matthew-carroll** [comment]
@mehmetf, generally SGTM, though I would expand slightly.  I think we probably want to support N variations of alert dialog and bottom sheet.  I think we should put a little effort in up front to evaluate what the 80/20 threshold is on variations of alerts and variations of bottom sheets, then provide whatever those are.  What do you think?

**Comment by mehmetf** [comment]
For this *particular* issue, the scope is what we can provide in Q1 to unblock the eval. I believe once we demonstrate the three types above, this issue can be closed. We can then track addition of other types of dialogs via new issues (and contributions since we now have a blueprint in the form of a plugin for others to add to). SG?

**Comment by matthew-carroll** [comment]
What do you think about the API implications?  If we solve for very specific cases then isn't it likely that we're left maintaining overly specific APIs after producing a more generic solution?

**Comment by mehmetf** [comment]
That's a very valid concern. Perhaps we can develop this internally first and control visibility so we can break the API if needed. It might be a good solution to experimenting with a solution. If you want to develop it upstream, we can do a private repo at first.  At the same time, we can continue collecting use cases. wdyt?

**Comment by matthew-carroll** [comment]
Private development works for me.  The details of how we do that will be interesting.  I have had many conversations on that topic due to my work on the embedding refactor - I have yet to find a solution that we are technically capable of using.

**Comment by Hixie** [comment]
@mehmetf Do you want to own this? This doesn't seem like something we'd want to provide as a first-party package or part of the framework, but I am happy for us to help the customer in question... Maybe we should close this issue and track it within Google?

**Comment by mehmetf** [comment]
I can own it, sure. If you don't care about having this available as an external resource, we can also create an internal solution first (then open source later). This could be a nice starter project.

**Comment by mehmetf** [comment]
We don't intend this to be an external solution so closing the upstream bug.
