### ISSUE TITLE
Should support all mouse buttons

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#23602]
When a mouse is connected to a phone, or when the app is running on a Chromebook, it would be helpful to be able to handle the right mouse button (and the middle button too) in order to display a context menu.

**Comment by zoechi** [comment]
Related to #757

**Comment by dkwingsmt** [comment]
1. Left/Right buttons have been supported by https://github.com/flutter/flutter/pull/31935.
2. The current plan is that middle button and complex button chording will not be added to flutter framework because they're rarely used, while developers can write their own gesture recognizers now that pointer events contain correct buttons.

Context menu to be discussed in https://github.com/flutter/flutter/issues/31955.
