### ISSUE TITLE
GDG China link on Wiki "Using Flutter in China" is broken

### ISSUE THREAD

**Issue by galeyang** [flutter/flutter#23754]
Link: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

The GDG China link (http://www.chinagdg.com/) isn't working. 
![image](https://user-images.githubusercontent.com/5102864/47758325-c9316580-dc67-11e8-81d2-a6a6fbf2f632.png)

**Comment by timsneath** [comment]
This is actually a little inaccurate. We're working on a plan to migrate this onto Google infrastructure, but it would be better to just say "maintained by the community", and not to link out anywhere. There are sensitivities around this space due to Chinese website publishing policies, so let's keep this simple.

**Comment by InMatrix** [comment]
FYI: I updated the wiki based on @timsneath's suggestion. I suggest we let the China team own this page and do a more thorough review to make sure the content is up to date.
