### ISSUE TITLE
Flutter tools should be more robust with paths, shells, multiple versions of installed deps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2381]
Numerous users reported issues with flutter tools not working as expected. We identified a few root causes:
- a user's shell was different than what our tools expected
- paths were not configured
- multiple versions of installed dependencies were identified, caused confusion

We can look into making a more robust tooling experience that can "survive the wild". Flutter tools should work no matter what shell the user uses, or if they have their environment's paths set correctly, or if they have multiple versions of the Android SDK installed.

**Comment by sethladd** [comment]
cc @devoncarew for ideas

**Comment by devoncarew** [comment]
Some notes on the current situation (and I'll speak to macos specifically, since that's where much of the problem is):

- when the user installs `flutter`, they set up the path to `flutter/bin` for the shell instance they're currently in
- if they start Atom in that shell, then it will inherit the paths for that process, and will be able to see `flutter`, as well as anything else on the path, like `brew`, `adb`, ...
- if they start Atom from the mac Dock, it will run in the `/bin/sh` shell. The default shell on the mac is bash, so it's highly unlikely `sh` will have any of the proper paths for the user. And specifically, they won't have the path to the flutter script from the above shell instance
- Atom will not be able to auto-locate the flutter script (done by shelling out to `which`). The user can set an explicit path for flutter_root, in which case we will be able to run the flutter tool. However, the tool will inherit the paths for the shell we're in, which has none of the user's settings. So `flutter` will not be able to locate adb, any of the brew installed tools, `jarsigner`, ... What the user will see will be an Atom that can't do things like recognize when a device is connected.
- We can (and currently do) try and detect the user's default shell (`zsh`, `tcsh`, `bash`) and shell out first to that shell, and then run the flutter tool `(/bin/bash -l -c 'flutter -d sdfsdf -run`). This picks up the path variable that the user has set up. They'll have needed to have put `flutter/bin/` on their path on their profile file `~/.bashrc`, `~/.bash_profile` for us to auto-locate flutter. I don't think the current getting started guide has users making their path changes permanent though.
- We need to shell out slightly differently depending on the specific shell the user is using. And in some cases it seems like we can't reliably determine the specific shell to use.

Other options are to make paths and locations very explicit. We'd create and read from a flutter config file, something like `~/flutter.config`. This would operate similarly to `.gitconfig`. `flutter doctor` or `flutter config` would be able to automatically create this file w/ auto-discovered info, and the flutter tool would let the user read and write values to it. It would contain info like the path to the flutter repo, the path to the android sdk, and the paths to any other necessary tools like `jarsigner`, the 304 brew installed utils we use. Atom will then be able to locate `flutter`, and the `flutter` process that we spawn off will be able to know explicitly where the other apps are w/o having to have good env vars or a `PATH` set up. This option is more precise but requires some setup on the user's part, and perhaps a bit more knowledge about how our tools work.

**Comment by devoncarew** [comment]
Note that we also have a similar issue w/ a launcher on linux (issue files by @qchong).

**Comment by eseidelGoogle** [comment]
The more I see this come up, the less I believe we can depend on the shell's config (especially from a GUI app!) and the more I believe we need to be explicit about our own config and provide tooling to validate/manipulate such.

**Comment by abarth** [comment]
This is largely fixed.  If there are remaining issues, we should file more specific bugs.
