### ISSUE TITLE
Automatic Right-To-Left text alignment detection in Flutter

### ISSUE THREAD

**Issue by AlexTaran** [flutter/flutter#23881]
In Android `TextView` somehow detects text direction inside (RTL or LTR) by its language.
In Flutter it depends on current locale.
is there any way to make text aligment automatic per-widget?

i'm filing it as a separate issue because it's different from the one which was described in https://github.com/flutter/flutter/issues/23875

And using the same screenshots:

Flutter
![screenshot from 2018-11-02 16-26-18](https://user-images.githubusercontent.com/479365/47924484-1c035b00-debc-11e8-8432-e85a11f2b750.png)

Android
![screenshot from 2018-11-02 16-26-33](https://user-images.githubusercontent.com/479365/47924490-1e65b500-debc-11e8-95c1-3a47091b6adc.png)

**Comment by AhmedAlYousef** [comment]
I wanted the same effect in a textfield where when a user type in a rtl language the direction of the textfield should change, so I made a package that will automatically change the direction based on the text you give it. here is the the package [auto_direction](https://pub.dev/packages/auto_direction)

**Comment by GaryQian** [comment]
After speaking with Hixie about assuming text directions based on content, we came to the conclusion that it is extremely dangerous to do so for generic fields since basic cases like "1902شارع" will be misinterpreted as LTR in Android's way. It is much more reliable to have users or locales specify the direction.

Auto-detection may be applicable in niche circumstances where the directionality is not fixed or in multilingual situations, but we are not planning on implementing it directly within Flutter. It looks like the plugin @AhmedAlYousef made is a great way to achieve this for the cases where it is necessary (thanks for making it!), though we urge you to fully consider the implications of detecting RTL.

**Comment by GaryQian** [comment]
I'm going to close this for now, but please let me know if you have any additional questions or concerns!

**Comment by mado-bohsali** [comment]
What about a widget to change alignment from LTR to RTL based on locale?

**Comment by yousifAlneamy** [comment]
> I wanted the same effect in a textfield where when a user type in a rtl language the direction of the textfield should change, so I made a package that will automatically change the direction based on the text you give it. here is the the package [auto_direction](https://pub.dev/packages/auto_direction)

I've just started using this package and it seems to do the job well. Thanks @AhmedAlYousif
