### ISSUE TITLE
Mocking ui.Image for use in a unit test causes an engine crash

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2391]
As part of #2198, I'm trying to mock out the ui.Image objects looked up in a mocked AssetBundle. These mock ui.Image objects are referenced from a build() function that returns an AssetImage.

Calling WidgetTester.pumpWidget() once with my build function initializes the appropriate ImageResources, but they're not populated yet. Calling pumpWidget() a second time causes the engine to crash.

### Steps to Reproduce

Here's the mock ui.Image class:
```
class TestImage extends ui.Image {
  TestImage(this.scale);
  final double scale;
  int get width => (48*scale).floor();
  int get height => (48*scale).floor();
  void dispose() { }
}
```

There's a bunch of boilerplate I use to get this test image to be returned by my mock AssetBundle, but the end result is that the current canvas is passed this ui.Image subclass in its Canvas.drawImageRect() method.  At that point, the engine crashes.  Running with a locally built debug engine results in this assertion:

ASSERTION FAILED: image
../../sky/engine/core/painting/Canvas.cpp(260) : void blink::Canvas::drawImageRect(const blink::CanvasImage *, blink::Rect &, blink::Rect &, const blink::Paint &)

I assume this is because the mock class has a null in a field that is normally populated.  The relevant classes in the engine seem to be Canvas.h/.cpp and CanvasImage.h/.cpp.

@abarth mentioned that DartConverter<T> is supposed to guard against malformed arguments passed into the native engine layer, but it's unclear to me as of writing where DartConverter would be used in the native method binding call sequence.

**Comment by krisgiesing** [comment]
@Hixie

**Comment by jason-simmons** [comment]
This is failing because the native fields of the TestImage were never set.

ui.Image inherits from NativeFieldWrapperClass2, and native code expects that a ui.Image will have values for the DartWrappable native fields.

However, ui.Image does not provide a constructor that is accessible from Dart and can fill in the native fields.  ui.Image is abstract and can not be instantiated from Dart, but there's nothing that prevents creating a subclass of ui.Image.

When DartConverterWrappable::FromArguments receives a handle to an instance of TestImage, it calls Dart_GetNativeFieldsOfArgument, which returns success and fills the native fields output with zeros.  The zero is then passed on as a null CanvasImage* to Canvas::drawImageRect.

DartConverterWrappable::FromArguments needs a check for this.

**Comment by krisgiesing** [comment]
Thanks for looking further. Can you point me to where Dart_GetNativeFieldsOfArgument (or DartConverterWrappable::FromArguments) gets called in this case?

**Comment by jason-simmons** [comment]
CanvasImage uses the DART_NATIVE_CALLBACK macro to generate the native functions for drawImageRect.

The generated function invokes DartCall -> DartArgIterator -> DartConverter<DartWrappable*>::FromArguments -> DartConverterWrappable::FromArguments
