### ISSUE TITLE
Support for Dart Extensions

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2396]
https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/

We've had at least one request for this.  I suspect it's implemented entirely in the `dart` CLI.

My understanding is it's just a bit of code to map dart-ext: urls to making a dlopen call and passing the symbols off to the VM.  @johnmccutchan 

I'm mostly seeking to document how we'd do this in this bug.  It's not clear if this is generically useful.

**Comment by eseidelGoogle** [comment]
Here is the relevant code in the dart CLI:
https://github.com/dart-lang/sdk/blob/1e5eab3a143f0736d925f546952006fb31127e9a/runtime/bin/dartutils.cc#L445

**Comment by johnmccutchan** [comment]
Assuming we keep this in the embedder, what happens when an import 'dart-ext:' occurs is the following:

1. Load the .so/.dll
2. Invoke the extensionName_Init() method.

In existing extensions, in the _Init method mostly just wires up the native resolver for the Dart code.

I wonder if we could formulate extensions differently and support them directly in the VM. I'll investigate this.

**Comment by johnmccutchan** [comment]
Related- https://codereview.chromium.org/1773643002/

**Comment by Hixie** [comment]
I've moved this to the 2.0 milestone since it doesn't seem like a blocker for a quality first release.

**Comment by eseidelGoogle** [comment]
This is not needed by any near-term customer.  The only bug I've seen which might use this is opengl support: https://github.com/flutter/flutter/issues/179 iceboxing.

**Comment by nacardin** [comment]
I'm currency working on an app that needs to use digital signatures, specifically EdDSA. Since there are C implementations which are stable and known to be reliable, I think it would be safer to use FFI, rather than trying to port the algorithm to dart.

Especially with WebAssembly becoming widely supported, Flutter would be at a disadvantage if it didn't allow FFI to use native libraries.

**Comment by sethladd** [comment]
You may be able to use our plugins system to communicate between the Flutter Dart code and platform-specific libraries: https://flutter.io/platform-plugins/

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/7053 is probably what you want.  You can integrate with C code today with Flutter, you just have to bounce through Java/Obj-C first.

**Comment by eseidelGoogle** [comment]
This need will hopefully be covered by FFI work: https://github.com/dart-lang/sdk/issues/34452 and related tooling work in: https://github.com/flutter/flutter/issues/7053

**Comment by ping996** [comment]
does the flutter support dart native extension?  according to use `import 'dart-ext:library_name';`
https://dart.dev/server/c-interop-native-extensions
