### ISSUE TITLE
Add Flutter to existing iOS App using Carthage

### ISSUE THREAD

**Issue by zwang** [flutter/flutter#24176]
I followed the instruction here to get flutter working with a demo iOS app using CocoaPods: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

I am checking out Flutter for my existing iOS project with Swift and Carthage. Is it possible for me to use Carthage as Dependency Manager for my iOS app to use Flutter as a module?

Any guidance/answer will be appreciated. Thank you.

**Comment by jelenacarnegie** [comment]
So, it is not possible to integrate Flutter module when using Carthage, at the moment?
Any workaround?
Thanks!

@zoechi @eseidel

**Comment by eseidelGoogle** [comment]
I believe the short answer re: carthage is "no", but I think @dnfield was looking to see if we can make that easier.

**Comment by dnfield** [comment]
I was able to do something simple to at least grab the `App.framework` and `Flutter.framework` into a Cartfile.  I wanted to experiment further to see if we could perhaps somehow grab the output of Cocoapods that way to rope in plugins for this as well.

I'll try to clean up what I have and do a write up on how to do this, as well as documenting whatever current limitations there are.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/23839 would help this

**Comment by jelenalecic** [comment]
@dnfield 

so, does flutter team have carthage support in roadmap? 
any dates in mind? 

thanks :)

**Comment by dnfield** [comment]
The official roadmap is here: https://github.com/flutter/flutter/wiki/Roadmap

There are no dates for this at this point.  It's definitely on my radar though.

**Comment by jmagman** [comment]
This will likely require:
1. Frameworks to not be zipped within the container artifacts.zip since Carthage expects .frameworks to be present at the top level of the zip.
2. Flutter to adopt true semantic versioning (no +hotfix etc).
3. No Carthage support for intermediate untagged commits on master.

From there:
1. Could publish the artifacts with the GitHub tags.
or
2. Create a [binary project specification](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification) file similar to https://storage.googleapis.com/flutter_infra/releases/releases_macos.json.

**Comment by mcooly** [comment]
want using Carthage

**Comment by jmagman** [comment]
Closing this, we're going to adopt Swift Package Manager instead.
