### ISSUE TITLE
Cursor too high/short for non-alphabetic scripts such as Chinese, emojis, and others.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24182]
The cursor for text fields is the wrong size/height for the text when typing non-alphabetic/english-like scripts.

This has been confirmed to affect Chinese (and other chinese-like scripts), emojis, Arabic (and arabic-like scripts), but probably impacts more.

Example with Chinese:
![textcursorbug](https://user-images.githubusercontent.com/1887398/48289776-7739ce00-e425-11e8-824f-ddced99a37ed.png)

It is interesting to note that highlighting the text works properly and covers the full vertical extent of the text. The cursor positions seems to be calculated from the same properties, but is coming up with a different result.

GetBoxesForRange() also seems to be outputting expected values.

**Comment by GaryQian** [comment]
in text_painter.dart get preferredLineHeight, we are laying out a ' ' and using the line height. There is probably a better, more consistent way of doing this...

**Comment by xster** [comment]
I suspect our current text painter's preferredLineHeight doesn't take into account the actual height TextStyle property of the TextSpan either. 

We should use your new get box for range API for the cursor too.

**Comment by CaiJingLong** [comment]
In the 0.11.4 version, the height of the cursor seems to be acceptable, but the position is still not aligned.
![image](https://user-images.githubusercontent.com/14145407/48458633-24379080-e802-11e8-9a6f-e27284eb766f.png)

----

Many lines of text also have problems, which may be caused by the same reasons. Half of the last line will be covered.

![image](https://user-images.githubusercontent.com/14145407/48458870-03bc0600-e803-11e8-88eb-ba8618e8731b.png)

code is 
```dart
  TextField(
     maxLines: 2,
  ),
```

flutter --version
----
```
Flutter 0.11.4 • channel dev • https://github.com/flutter/flutter.git
Framework • revision df57dc9da9 (2 days ago) • 2018-11-11 22:36:47 -0800
Engine • revision 5646e86a6f
Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)
```

**Comment by zoechi** [comment]
Dup of #23934

**Comment by longwayto** [comment]
`TextField (
style: TextStyle(height: 1.2)
)`

height ：1.2 solve the problem

**Comment by GaryQian** [comment]
I will close this now, as we have landed fixes that

- Centers the caret
- Makes it taller/take the full height of the line
