### ISSUE TITLE
Changing device targets re-enabled ENABLE_BITCODE for iOS Add2App

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#24366]
Noted initially here: https://github.com/flutter/flutter/issues/24343 and I ended up just reproducing this locally.

Steps to reproduce:

1. Follow Add2App instructions to create an Add2App project
2. Change from simulator to device deployment

This ends up with an ENABLE_BITCODE = YES configuration, which fails to build.  Manual resolution is to set this to NO and you're good again, but maybe we can find a way to get this in the config files properly.  I suspect adding it to Generated.xcconfig will solve things.

**Comment by dnfield** [comment]
Apparently Xcode overrides the setting in the file.  We're only good on this the first time because Cocoapods sets it.

/cc @cbracken @chinmaygarde - do either of you know of a way to fix this?

**Comment by jmagman** [comment]
I removed post_install ENABLE_BITCODE = YES hook because setting it manually in the necessary host app targets was sufficient in my testing with instruction #3 https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile.
@dnfield are you still able to reproduce this?

**Comment by dnfield** [comment]
I was never able to consistently reproduce it - I would just notice that every once in a while it would reset and I'd have to go in and manually change it back.

**Comment by dnfield** [comment]
To clarify - this is no longer an issue because we now support bitcode, right?

**Comment by jmagman** [comment]
> To clarify - this is no longer an issue because we now support bitcode, right?

Yes, but even before that I think it was no longer a thing because no add-to-app tooling altered ENABLE_BITCODE.  It was up to the host app developer to change it in their appropriate targets.  See https://github.com/flutter/flutter/issues/32993#issuecomment-516093302 comment about not altering targets that don't need to embed Flutter (like a notification extension).
