### ISSUE TITLE
Keyboard appearance destroys SystemUIOverlays settings

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#24494]
I have hidden the system bars with `SystemChrome.setEnabledSystemUIOverlays([])`, which works fine.

But from the moment a keyboard appears (because a text input field gets focus), the system top and bottom bars show up again and they even remain active after the keyboard has been closed.

I would expect (a) no top (status) bar because of the keyboard and (b) maybe a bottom bar to close the keyboard (is this really needed?), but then only as long as the keyboard is present.

```
[✓] Flutter (Channel dev, v0.11.6, on Linux, locale en_US.UTF-8)
    • Flutter version 0.11.6 at /home/jos/flutter1/flutter
    • Framework revision d44aa57c12 (4 days ago), 2018-11-14 11:09:56 -0800
    • Engine revision 114d33d3ca
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/jos/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /home/jos/flutter1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.
```

**Comment by GaryQian** [comment]
This is actually something that is forced by the OS (likely as a way to prevent apps from trapping users in their app). Whenever the keyboard appears, the UI will be re-enabled even if it was set to be disabled via SystemChrome. We provide a utility method called `SystemChrome.restoreSystemUIOverlays()` to restore previous settings set by the last `SystemChrom.setEnabledSystemUIOverlays()` call. The restore call should be made whenever the keyboard goes away or when you otherwise need to ensure the UI is disabled again.

See https://docs.flutter.io/flutter/services/SystemChrome/restoreSystemUIOverlays.html for more details.

The relevant PR: https://github.com/flutter/flutter/pull/22221

**Comment by adrianvintu** [comment]
(How) Can we hook to the onHideEvent of the keyboard to call `SystemChrome.restoreSystemUIOverlays()`, or when can we call the restore?

**Comment by adrianvintu** [comment]
@GaryQian  where did you get "This is actually something that is forced by the OS"?

This is NOT happening on my Android app that runs in fullscreen and never ever exits that, even when keyboard appears.

https://play.google.com/store/apps/details?id=com.dex
