### ISSUE TITLE
no callback on setFlutterViewDidRenderCallback from FlutterViewController.

### ISSUE THREAD

**Issue by tdesc** [flutter/flutter#24519]
Render callback not fired in FlutterViewController after setFlutterViewDidRenderCallback

FlutterViewController created from storyboard with instantiateViewController

Flutter (Channel master, v0.11.7-pre.52 )

P.S> it seems that callback now available only if _splashScreenView set.

**Comment by xster** [comment]
cc @dnfield, we should make sure it's consistent with Android if it isn't. Probably sensible to let users hook callbacks all the time regardless of splash screen though.

**Comment by dnfield** [comment]
I don't know that that callback is all that reliable.  It looks like it was only there to let you know when a splash screen was dismissed - it doesn't appear to actually be wired up to the engine to know whether Flutter is rendering or not.

**Comment by dnfield** [comment]
See https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L270

**Comment by dnfield** [comment]
What we could do is use https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L652 after we setup the shell, and call that callback once it fires.

Unfortunately, this would still be shaky at best - There's no guarantee that we wouldn't call your callback before you actually install a hook for it.  So for example, the following sequence is possible:

1. Engine/Shell are initialized and setup
2. Embedding schedules a callback for after the next (presumably first, but not necessarily) frame is rendered.
3. FlutterViewController gets attached, engine needs to start rendering!
4. Callback is fired because frame has been rendered.
5. Application code hooks up to callback to be notified when rendering starts, never getting a callback.

So alternatively, it might be best to just provide some way to provide a callback that fires after the next frame from wherever you are.

I know there's also been some question about whether we could have a sync API to alert you as to whether the engine has rendered **any** frames yet, but again that could have its own problems.

What's your acutally use-case here @tdesc ?

**Comment by xster** [comment]
That's actually how it's set up on the platform_view.h. I think that change is fine (though API breaking). My main concern though is that on Android, it seems like there are no purpose implied. The API is pretty straightforward. You add FlutterView.FirstFrameListener, FlutterView just calls it. The activity just uses it for splashes but the API is first class citizen.

**Comment by dnfield** [comment]
Android seems like it would suffer from a similar problem - what happens if you subscribe after the first frame has already fired?

**Comment by xster** [comment]
ya, but I think it's orthogonal. i.e. there's no real reason for 3 and 5 to not happen synchronously inline.

**Comment by xster** [comment]
> So alternatively, it might be best to just provide some way to provide a callback that fires after the next frame from wherever you are.

Looking at this again, this is just what platform_view->SetNextFrameCallback actually does and as much as what the setFlutterViewDidRenderCallback doc promises. All the extra sequencing are implementation details in FlutterViewController. 

This should just work by deleting all the code that connects splash screens as a prerequisite rather than just another consumer of SetNextFrameCallback.

**Comment by xster** [comment]
conversely, the Android embedding seems to have the desired effect.
