### ISSUE TITLE
unify the output from flutter analyze and flutter analyze --watch

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2469]
Either make the two modes look the same or be deliberate about places where they should look different.

**Comment by Hixie** [comment]
Didn't we do this?

**Comment by devoncarew** [comment]
I see this output:

```
flutter analyze
Analyzing 1357 files...
[hint] Duplicate import. (lib/main.dart, line 11, col 8)
[lint] 52 public members lack documentation (ran in 32.5s)
```

and:

```
flutter analyze --watch
Analyzing /Users/devoncarew/projects/flutter/flutter/examples/flutter_gallery... 1,494ms

   info • Duplicate import. • lib/main.dart:11:8
1 issue found • analyzed 89 files, 1.50 seconds
```

**Comment by Hixie** [comment]
Ah, I guess I only look at the output from `--write` when using `--watch` (that output matches the output from non-`--watch`).

It's important that the output from non-`--watch` and from `--write` be somewhat machine-readable (but still very human readable), specifically that they have full paths and that the line/column numbers be unambiguously distinguishable from the rest, so that e.g. emacs compilation buffers can jump to errors.

I don't have a strong opinion on what the `--watch` output looks like, but I'm guessing people like the pretty bullets? I find it somewhat harder to read than the other style but I'm probably just not used to it.

**Comment by devoncarew** [comment]
I like the bullets, but am not overly attached to them. Using relative path means less text for users to scan. And, I was not aware of the `--write` option :)

We can likely find an output that is aesthetic and generally parsable.

**Comment by Hixie** [comment]
You know what, the output from `--watch --write` doesn't actually match the output from non-watch. We have three different styles right now:

```
[error] Unexpected text '.'. (image_cache.dart, line 5, col 27)

  error • Unexpected text '.'. • dev/flutter/packages/flutter/lib/src/painting/image_cache.dart:5:27

[error] Unexpected text '.'. (/usr/local/google/home/ianh/dev/flutter/packages/flutter/lib/src/painting/image_cache.dart:5:27)
```

But hey, at least `analyze` and `analyze --write` match, so we have that going for us.

**Comment by Hixie** [comment]
This got resolved a while back.
