### ISSUE TITLE
how to remove installed packages that no longer needed?

### ISSUE THREAD

**Issue by gueano** [flutter/flutter#24733]
for example, I just installed the "http" package with:

1. add "http: ^0.12.0" to the secion dependencies in the file pubspec.yaml
2. run command "flutter packages get"

That's great, super easy.

but what if I don't need it anymore? I want to remove it from my project. following is what I have done.

1. I have removed what I added to the file pubspec.yaml
2. run command "flutter packages get" again
3. build project

but the http package is still available in my code. What else I need to do, please?

**Comment by zoechi** [comment]
Packages you add to `pubspec.yaml` are downloaded to 
 `~/.pub-cache/...` per version and shared between all your projects. 
If a package is from pub.dartlang.org it will be stored in 
`~/.pub-cache/hosted/pub.dartlang.org/`
(if `PUB_CACHE` is set `$PUB_CACHE/hosted/pub.dartlang.org/` would be used instead)

If you remove a package from `pubspec.yaml` but another dependency depends on it, the package will still be listed in `pubspec.lock` and therefore will be available in your project. 
You should get an error if your custom code imports a package that is not listed in `dependencies:` in `pubspec.yaml`, but otherwise this doesn't result in a warning.

You can investigate transitive dependencies using  `flutter packages pub deps`

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by doanbh** [comment]
It took me more than 3 days to try  all differently way. But finally I found, you need to go into the "pubspec.lock" file. Then go to the library and change the version there. Then go back to the file "pubspec.yaml" and run **Packages get** and it succeeds.
