### ISSUE TITLE
BigInt modPow much slower on iOS

### ISSUE THREAD

**Issue by curtcox** [flutter/flutter#24827]
## Steps to Reproduce

The BigInt modPow method is much slower on iOS.
Is this a hardware or software issue? 

* Mac Pro 2009 -- 5 seconds
* Kindle Fire -- 70 seconds 
* iPhone 6+ -- 1079 seconds

The times were generated using this app:
https://github.com/curtcox/Flutter_BigInt_Speed_Test/blob/master/bigint_speed/lib/main.dart

The relevant calculation code snippet is shown below:
```
  static String timedTest(x) {
    var out = "";
    var x = BigInt.from(5);
    var y = BigInt.from(2);

    for (int i=1; i<8; i++) {
      x = x.pow(5);
      y = y.pow(3) + BigInt.from(1);
      out = out + "$i " + perf(() => x.modPow(x, y) ) + "\n";
    }
    return out;
  }
```

## Logs

Mac Pro 2009 simulating iPhone XR
```
Launching lib/main.dart on iPhone XR in debug mode...
Starting Xcode build...
Xcode build done.                                            5.1s
Syncing files to device iPhone XR...
flutter: 0:00:00.010314 3
flutter: 0:00:00.000231 9
flutter: 0:00:00.001387 29
flutter: 0:00:00.014520 85
flutter: 0:00:00.020691 257
flutter: 0:00:00.201035 771
flutter: 0:00:04.864773 2306
```

iPhone 6+
```
Starting Xcode build...
Xcode build done.                                            6.4s
Installing and launching...
Syncing files to device Curt’s iPhone 6+...
flutter: 0:00:00.023876 3
flutter: 0:00:00.014451 9
flutter: 0:00:00.054063 29
flutter: 0:00:00.293501 85
flutter: 0:00:01.723762 257
flutter: 0:00:45.312481 771
flutter: 0:17:59.258844 2306
```

Kindle Fire 5th generation
```
Launching lib/main.dart on KFFOWI in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/Kernel  ( 5524): [246853.162912]-(0)[5622:1.ui]dpi vsync
Syncing files to device KFFOWI...
I/Kernel  ( 5524): [246855.195081]-(0)[5622:1.ui]dpi vsync
I/Kernel  ( 5524): [246859.259472]-(0)[5631:SWD-Frame]dpi vsync
I/flutter ( 5524): 0:00:00.049960 3
I/flutter ( 5524): 0:00:00.004278 9
I/flutter ( 5524): 0:00:00.022287 29
I/flutter ( 5524): 0:00:00.075488 85
I/flutter ( 5524): 0:00:00.432738 257
I/Kernel  ( 5524): [246865.355931]-(0)[5831:ple.bigintspeed]dpi vsync
I/flutter ( 5524): 0:00:04.800835 771
I/Kernel  ( 5524): [246873.484620]-(0)[5831:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [246877.548967]-(0)[5626:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [246881.613303]-(0)[5831:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [246897.870677]-(0)[5831:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [246912.095887]-(0)[5626:ple.bigintspeed]dpi vsync
I/flutter ( 5524): 0:01:10.233060 2306
I/Kernel  ( 5524): [246975.093220]-(0)[5622:1.ui]dpi vsync
I/Kernel  ( 5524): [247101.087870]-(0)[5831:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [247164.085189]-(0)[5831:ple.bigintspeed]dpi vsync
I/Kernel  ( 5524): [247418.106657]-(0)[5622:1.ui]dpi vsync
W/IInputConnectionWrapper( 5524): showStatusIcon on inactive InputConnection
I/Kernel  ( 5524): [247800.107272]-(0)[5622:1.ui]dpi vsync
```

```
flutter analyze
Analyzing bigint_speed...                                        
No issues found! (ran in 1.8s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.10 at /Users/curt/work/flutter
    • Framework revision c27c4a265e (2 days ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/curt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected device (3 available)
    • KFFOWI           • G0K0H404540200JE                         • android-arm • Android 5.1.1 (API 22)
    • Curt’s iPhone 6+ • 97ee7412fd98a6b5ff674ee923b2d74c9fc86c1f • ios         • iOS 12.1
    • iPhone XR        • 8EC930BA-3013-41B6-8A49-DAE476DBF4F6     • ios         • iOS 12.1 (simulator)

• No issues found!

```

**Comment by zoechi** [comment]
@mraleph ?

**Comment by mraleph** [comment]
@curtcox please try benchmarking _in release mode_ (e.g. do `flutter run --release`)

In debug mode (default development mode) Dart VM is using pure interpretation on iOS devices because it can't JIT (iOS does not allow JITing) and AOT compilation would be too slow and would not allow hot-reload. 

In general when measuring performance I recommend using `--release` and `--profile` modes - because this is performance end users will see.

**Comment by curtcox** [comment]
Using --release made all the difference on iOS. The 80x speed increase was unexpected. 
```
flutter: 0:00:00.000464 3
flutter: 0:00:00.000098 9
flutter: 0:00:00.000509 29
flutter: 0:00:00.001457 85
flutter: 0:00:00.026152 257
flutter: 0:00:00.557183 771
flutter: 0:00:13.259672 2306
```

On the Kindle Fire, it made things about 30 percent slower.

```
I/flutter (10025): 0:00:00.001315 3
I/flutter (10025): 0:00:00.000653 9
I/flutter (10025): 0:00:00.005024 29
I/flutter (10025): 0:00:00.036044 85
I/flutter (10025): 0:00:00.479570 257
I/flutter (10025): 0:00:10.026453 771
I/flutter (10025): 0:01:33.649685 2306
```

Thanks for the quick response and explanation.

- Curt

**Comment by mraleph** [comment]
I find it interesting that AOT version (release) is 30% slower. I was expecting this benchmark to spend most of the time in `BigInt` intrinsic. We need to check this out.

**Comment by magicly** [comment]
> @curtcox please try benchmarking _in release mode_ (e.g. do `flutter run --release`)
> 
> In debug mode (default development mode) Dart VM is using pure interpretation on iOS devices because it can't JIT (iOS does not allow JITing) and AOT compilation would be too slow and would not allow hot-reload.
> 

hello @mraleph , I'm working on a flutter app recently, and come up with the problem "some cpu intensive dart code is so slow on iOS". e.g. image processing, refer to https://github.com/brendan-duncan/image/issues?utf8=%E2%9C%93&q=ios++slow

After some search, I find your answer, thanks so much~

when on debug model, decodePng cost me **2min**, but on release model it just cost <2 seconds.  I think dart lang is fast enough.

but I have a question,  you said "iOS does not allow JITing", does this mean it is not allowed by Apple AppStore policy or it just can't be done technically. I think if it is not allowed by AppStore policy, actually we can defaut JIT in development mode, because this is just run on our own device and not even publish to AppStore. Because sometimes we need do some cpu intensive work, it is so slow in debug mode now,  we must build release every time after some code change and never get the hot reload effiency.   Any help is welcome, thanks for great work about dart and flutter~

**Comment by mraleph** [comment]
> Because sometimes we need do some cpu intensive work, it is so slow in debug mode now, we must build release every time after some code change and never get the hot reload effiency.

Actually we are currently considering to change how debug mode is implemented for iOS because an engineer has discovered that we could actually use JITing under certain conditions in development environment. It would not be possible to ship a release mode app using JITing, as there are protections built into the iOS kernel - however these protections are disabled during development, meaning that we could actually use JITing there.

I will leave a comment here if we move forward with the change

**Comment by magicly** [comment]
@mraleph sounds like great. thanks very much~

**Comment by mraleph** [comment]
@magicly if you upgrade to master channel you should see much better performance in the debug mode on iOS.

**Comment by duzenko** [comment]
> 
> 
> @magicly if you upgrade to master channel you should see much better performance in the debug mode on iOS.

When can we see this in stable?

**Comment by mraleph** [comment]
@duzenko 

1.  I don't have any information on the concrete release date for the next stable release. However I know that Flutter team is working on picking the stable release candidate - which means promotion to stable would happen in the near future. 
2.  iOS debug builds are now using native JIT instead of an interpreter.
3. It depends on the type of the code. The code like the one in this issue would see orders of magnitude improvement (10x-100x faster).

I am closing this issue because it is essentially fixed.
