### ISSUE TITLE
BoxDecoration.borderRadius incorrect rendering

### ISSUE THREAD

**Issue by GoldenJoe** [flutter/flutter#24883]
When working with BoxDecoration.borderRadius, I get some unexpected behavior. There are two problems:

1. The borderRadius seems to work as a **fill** rather than a **stroke**. When the borderRadius is less than double the width of the border, you get a hard inner edge as seen below:
```dart
Container(
  color: Color(0x20ff0000),
  padding: EdgeInsets.all(4.0),
  constraints: BoxConstraints.expand(),
    child: DecoratedBox(
      decoration: BoxDecoration(
      border: Border.all(color: Colors.blue, width: 10),
      borderRadius: BorderRadius.all(Radius.circular(20.0)),
    ),
  )
),
```

![screen shot 2018-11-30 at 12 27 45 pm](https://user-images.githubusercontent.com/2248993/49304935-c199f200-f49b-11e8-9432-f435b6cb7c5e.png)

2. Even when you specify a borderRadius that is greater than or equal to double the border width, the inner corner radius looks a bit off. I think it's because the "inner" curve is wrong, making corners look pinched, but perhaps my eyes are playing tricks on me?
```dart
border: Border.all(color: Colors.blue, width: 10),
borderRadius: BorderRadius.all(Radius.circular(20.0)),
```

![screen shot 2018-11-30 at 12 34 48 pm](https://user-images.githubusercontent.com/2248993/49305119-57358180-f49c-11e8-923b-cb03ff1d35e7.png)
 
It would also be convenient if you could offset a border by some EdgeInsets without encapsulating everything in another Container.

**Comment by GoldenJoe** [comment]
Josephs-MBP:~ GoldenJoe$ flutter doctor -v
[✓] Flutter (Channel beta, v0.11.12, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.12 at /Users/GoldenJoe/Development/flutter
    • Framework revision 06ec8d3b41 (5 days ago), 2018-11-28 15:56:58 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/GoldenJoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • iPhone XS • 72DDB7C4-680F-456A-9BAF-03612CB90D04 • ios • iOS 12.1
      (simulator)

• No issues found!

**Comment by GaryQian** [comment]
Regarding the first point, I believe it is mathematically/geometrically not possible to satisfy both the expected border with as well as the provided border radius when the width is larger than the radius. There is simply no way to "turn" that corner in a radius that is smaller than the width.

With a 'stroke' like behavior, it may be possible to draw curved inner edges, but it will likely not technically satisfy the user's input for the radius (eg, the inner curve will be much tighter than the outer). I can look into possibilities for providing API for unbalanced radii for inner and outer curves.

Regarding the second point, there is an argument for not providing perfectly circle-based rounded corners as perfect corners (to the human eye) does not seem as "round" as slightly artistically modified corners. I can check on whether or not we use perfect round corners; if we do, then the perceived thinness is likely an optical illusion. Otherwise, you may be right in seeing it looking off.

cc @HansMuller would you happen to know how our corners are rounded and what Material design says about this point?

**Comment by GaryQian** [comment]
I have confirmed that the second image is indeed correctly drawn. The curves drawn are based off a circle.

It doesn't seem that there is anything to do here, so I will close this issue for now.

**Comment by fluttercorner** [comment]
[How to add Border Radius to Container in Flutter ?](https://fluttercorner.com/how-to-add-border-radius-to-container-in-flutter/)
