### ISSUE TITLE
A room equivalent in Flutter

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#24927]
Google has released a Room library in its JetPack library. Please provide a equivalent version with database observing feature in flutter.

**Comment by zoechi** [comment]
Would you mind posting a link to a description of that feature?

**Comment by satjawat** [comment]
I think he mention this feature 
https://developer.android.com/topic/libraries/architecture/room

**Comment by viratshukla** [comment]
Yeah, this, part of JetPack
https://developer.android.com/training/data-storage/room/
https://developer.android.com/topic/libraries/architecture/room

**Comment by zoechi** [comment]
Related to #17433

**Comment by feinstein** [comment]
This would be a WONDERFUL addition. 

Room makes it easy to deal with sqlite databases, getting **compile time checks** for the SQL code and it's much easier to use than a  traditional ORM, since it gives you the power to manipulate the SQL as much as you want, still keeping it simple.

It generates all the code for you, while you only create interfaces, which abstract all the database access.

There are currently some pub packages for sqlite made by the community, but I think this kind of package should be done by Google, to ensure good performance, long term maintainability and security, since database caching is used by so many apps and are a crucial part of mobile development. Also, those packages don't give any of the advantages of Room.

**Comment by neiljaywarner** [comment]
In addition, if something is first party / flutter team/official it gives the feeling that more things come built in - from a marketing/persuading to upper management or new developers either way.

**Comment by feinstein** [comment]
It also gives a sense that the project won't be abandoned overnight, having high quality and secure code.

**Comment by stanmots** [comment]
Yes, we all want to see Flutter as a feature-full cross platform framework. But let's not forget that 1) The Flutter team has limited resources 2) Flutter is completely free and open source. 
Of course, it would be great to have an official database package. However, to reduce the burden on Flutter developers I would suggest a tight collaboration with Realm team. Realm is a great open source database implementation and they already provide React Native integration.

**Comment by feinstein** [comment]
Yes, but community engagement on a particular topic can make the Flutter team change focus, that's why engaging (specially liking) is encouraged.

**Comment by iamshubhamsaurav** [comment]
I would love to see something like Room or CoreData in Flutter.

**Comment by dagema1** [comment]
check this library it's called moor
https://pub.dev/packages/moor_flutter

**Comment by ramamurthyk** [comment]
Folks - have you checked this one?
https://pub.dev/packages/floor
https://github.com/vitusortner/floor

**Comment by 7uthaifah** [comment]
I think it's one of the most important packages ever.

**WE NEED FLUENT SQLITE DATABASE ACCESS**

**Comment by collinjackson** [comment]
The Flutter team doesn't have a near-term plan to develop this plugin, so I'm closing this. Please check out the other packages options that have been posted in this thread.
