### ISSUE TITLE
Typing on a TextField removes full-screen mode

### ISSUE THREAD

**Issue by aswinmohanme** [flutter/flutter#24968]
I have set the flutter application to full-screen mode using this line 
```dart
void main() async {
  // Enable Fullscreen Mode
  await SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);

  runApp(MainApp());
}
```

Here is my navigational strucuture
MainApp -> HomeScreen -> TasksScreen

There is a Text Field in TasksScreen which if selected would add padding from the top and when text is submitted would display the top notification bar, and the bar would stay there even if we press the back button.

Here's the entire issue in video : https://drive.google.com/open?id=1GYAIaswc6Mw-RF2kHqGexwmeHQ0FViGN

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/aswinmohanme/Flutter/flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/aswinmohanme/Android/Sdk
    • Android NDK at /home/aswinmohanme/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/aswinmohanme/Android/Sdk
    • Java binary at: /home/aswinmohanme/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/aswinmohanme/Android/android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Redmi Note 3 • 79c0f009 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!

```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by HansMuller** [comment]
cc @jonahwilliams

**Comment by GaryQian** [comment]
This is actually something that is forced by the OS (likely as a way to prevent apps from trapping users in their app). Whenever the keyboard appears, the UI will be re-enabled even if it was set to be disabled via SystemChrome. We provide a utility method called `SystemChrome.restoreSystemUIOverlays()` to restore previous settings set by the last `SystemChrom.setEnabledSystemUIOverlays()` call. The restore call should be made whenever the keyboard goes away or when you otherwise need to ensure the UI is disabled again.

See https://docs.flutter.io/flutter/services/SystemChrome/restoreSystemUIOverlays.html for more details.

The relevant PR: https://github.com/flutter/flutter/pull/22221
