### ISSUE TITLE
Stack overflow of widgets breaks Flutter with no error message

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#25041]
Just run this:
```dart
    import 'package:flutter/material.dart';
    void main() => runApp(Demo());

    class Demo extends StatefulWidget {
      final Widget child;
      Demo({this.child});

      _DemoState createState() => _DemoState();
    }

    class _DemoState extends State<Demo> {    
      Widget build(BuildContext context) => widget;
    }
```

**Comment by marcglasberg** [comment]
Also, by Remi Rousselet:

    void main() => runApp(
      Builder(builder: (context) => context.widget)
   );

**Comment by marcglasberg** [comment]
Can't at least the trivial case be fixed by checking if the widget returned by the build method is identical to the widget itself, and issuing a proper error message?

**Comment by HansMuller** [comment]
It's definitely easy enough to catch the trivial case and throw an error. Will do that.
```
void main() { runApp(Builder(builder: (context) => context.widget)); } // error
```

Unfortunately detecting when context.widget appears elsewhere in the built tree, would require walking the entire built widget tree. Which might cause a noticeable drag on debug-mode.
```
void main() { runApp(Builder(builder: (context) => Container(child: context.widget))); }
```

Even if we did that, it wouldn't really address the general problem, which is detecting loops in the build tree.
```
Widget foo = Container(child: Builder(builder: (BuildContext context) => bar));
Widget bar = Container(child: Builder(builder: (BuildContext context) => foo));

void main() { runApp(Builder(builder: (BuildContext context) => foo)); }
```

To do that might require a recursive analysis of the entire tree as it was being constructed.

Since this problem doesn't seem to come up very often, it's probably best to just check the trivial case.

**Comment by jason-simmons** [comment]
flutter_tester will segfault when running a test based on this app:

```
void main() {
  testWidgets('test', (WidgetTester tester) async {
    await tester.pumpWidget(
      Builder(builder: (context) => context.widget)
    );
  });
}
```

**Comment by rmacnak-google** [comment]
This seems to be enum initialization happening without enough stack left. The VM assumes enum initialization can't fail, and lets an error escape to places that should only see instances. An even simpler program with the same crash:

```
enum Fruit {
  apple, banana,
}

getFruit() => Fruit.apple;

recurse() {
  try {
    recurse();
  } catch (e, st) {
    print("$e ${getFruit()}");
  }
}

main() {
  recurse();
}
```
