### ISSUE TITLE
[google_maps_flutter] Why are markers not Flutter widgets? (Feature wish)

### ISSUE THREAD

**Issue by Soundbytes** [flutter/flutter#25040]
Working with markers is quite a pain in flutter. With flutter you gave us the most powerful tool at hand and here we just can not use it. 
I am sure you guys must have discussed having markers and info windows live in a stacked widget on top of the map. Is there any chance this could be done or are there too many obstacles?
Thanks for any comments!

**Comment by ThinOfSnowDance** [comment]
How old are you?

**Comment by feinstein** [comment]
AFAIK (and it's not much) maps in Flutter actually show the maps from the Plataform (iOS or Android), so I think we can't place widgets on the map, because the library is just a bridge to the maps implementation on the plataform it's currently running, something like an API to a black box.... But I could be wrong...

**Comment by Soundbytes** [comment]
Sorry for leaving out the details in my first post. Here is some further info:
Maps in Flutter are now Flutter Widgets. These can be stacked (overlayed) with any other Flutter widgets. 
Currently markers and info windows are provided by the platform specific google maps api. 
What I am asking for is an extension to the plugin that would allow to have those in the flutter domain instead of having to use api calls. 
This would allow a heap of really neat stuff like for example:
- vectorized Markers
- animated Markers
- customized Info Windows (eg. as Flutter cards)
- clickable zones on info window to trigger different app responses.
- whatever else you may come up with.

Thanks for taking care!

**Comment by Kamil-H** [comment]
I think support for `Projection` would be sufficent to solve this problem. From documentation:

> A projection is used to translate between on screen location and geographic coordinates on the surface of the Earth (LatLng)

https://developers.google.com/android/reference/com/google/android/gms/maps/Projection

**Comment by Soundbytes** [comment]
Thanks for the input. This looks really promising. So all we would need to get the screen coordinates of the LatLng object (and vice versa) is a method channel call to the platform api?
How about map animations?  Since access through method channels is always asyncronous this might introduce quite a bit of overhead when futter widget positions need to be updated through a platform api controlled map animation.

**Comment by iskakaushik** [comment]
This seems to be very similar to https://github.com/flutter/flutter/issues/24213, let me know if i'm missing something here. Thanks!

**Comment by Soundbytes** [comment]
@iskakaushik Thanks for pointing that out. It seems I did not do enough research before I filed my proposal. 
I have to add though that contrary to to the flutter/plugins#815 PR that is mentioned there I would rather not inject the marker as a bitmap from Flutter into the platform api but instead would love to see a genuine flutter widget stacked on top of the map to handle markers and marker info windows. Thanks for taking care!

**Comment by AndrewPetrovics** [comment]
This would be huge. We currently need a way to update markers without having a .png. Similar to how Airbnb map shows.

**Comment by Zilounay** [comment]
My 2 cents, we would also love to see the marker not being a bitmap, but instead a widget. This would allow so much customization that i'd bring something really new to the maps in general.

**Comment by yuridiniz** [comment]
I did not imagine it was possible to do it, I found the Projection proposal very cool, it should be possible to implement a Dart layer of Projection so that I do not need to make calls to the specific platform. I imagine that even with a Dart implementation to work, it would be necessary to get the current position and zoom of the camera, so I wonder, would it be possible to animate the camera and the Marker at the same time or could the delay of the platform call make the idea of ​​using Projection unfeasible? Following this same idea, I also worry about the "synchronization" of the position of the elements (Markers, Polygons ...) when the map moves ... Apart from these issues, there are many gains and possibilities for evolution!

**Comment by iskakaushik** [comment]
We are using https://github.com/flutter/flutter/issues/24213 to track the general issue of google maps markers being custom widgets. I.e, different from what the google maps api provides. In an effort to de-duplicate the issues, i'm closing this.

Please re-open an issue with a different request if you think there is something missing.

Thanks!
