### ISSUE TITLE
flutter run in the hello_world/ and layers/ example directories crashes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2517]
- [x] Figure out what the crash is
- [x] Make the engine resilient to whatever the cause of the crash is, either failing gracefully with a useful error message or not failing at all - tracked separately at https://github.com/flutter/flutter/issues/2564
- [x] Make the tool not put the engine in that situation in the first place

**Comment by Hixie** [comment]
cc @vlidholt I think this is what you were hitting

We need to make sure that we can run individual files on Android and iOS, even if it means making a temporary directory and using default assets and manifests and so on.

**Comment by jason-simmons** [comment]
This crash occurs because these examples do not have an Android manifest.

Without a manifest "flutter run" can't build an APK, and it tries to run the FLX using SkyShell.  "flutter run" didn't install the latest SkyShell.apk from my local build of the engine, so the FLX was executed on some old version of SkyShell that was installed on the device.

That SkyShell had an old Dart VM that didn't match the FLX's snapshot.  Dart logged a "Wrong script snapshot version" warning, followed by a fatal error on Dart_IsolateMakeRunnable().

What should the tools do in this situation?
Do we still support building Android apps without a manifest and running them with SkyShell?

**Comment by Hixie** [comment]
I'll file a second bug for "crash more gracefully and usefully when the snapshot version doesn't match".
I think we should just give up on having prebuilt skyshells, and just have the flutter tool build one each time, using defaults if relevant files are missing.

**Comment by Hixie** [comment]
FIled https://github.com/flutter/flutter/issues/2564

**Comment by eseidelGoogle** [comment]
@mmclenna hit this this morning.
