### ISSUE TITLE
Support Scenic Z

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#25226]
This comes up in discussions with the Fuchsia folks --- with views with different elevation we need a way of "collapsing" elevations from one view and another as they drag. The dragging will be done by offsetting elevation;  we'll need to cap elevation (using either a linear cap, asymptotic cap, clipping or squishing the layers).

**Comment by mklim** [comment]
So here's my understanding of what Scenic needs from syncing up on this with @amott9 recently. I have the suspicion that I may be restating what's already been said here, just in 3D graphics terminology instead of Flutter terminology. Want to capture my working knowledge in this bug as it stands though.

The basic problem as I understand it is that Scenic needs to be able to transform Flutter UIs along a z axis in addition to an x and y. Flutter UIs are constrained and transformed in 2D along x and y already, but we don't have a clear concept of a z axis or a real 3D bounding box for our UI. There's "elevation" but it's more a 2.5d relative value we use to draw shadows. It's not constrained at all and there's no listeners for when our z space is transformed.

So at a high level:

- [ ] Flutter needs to effectively be aware of an [AABB](https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection) around its UI that includes Z. We currently have X and Y bounds already in the form of a 2D bounding rectangle, no real notion of Z. 
- [ ] Flutter needs to translate "elevation" in its UIs into actual view space z position by normalizing elevation based on the z bounds. So if there's a widget A in the UI with "elevation" of `5`, widget B with "elevation" of `100`, and the UI has an AABB of `[(0, 0, 0), (10, 10, 10)]` with positive z meaning "up/closer to the camera", same as "elevation": A's view space z position would be `0.5` and B's view space z position would be `10`. (We may want to investigate clamping eventually to avoid unwanted side effects from normalization. In the above example if A was created before B, it would initially be placed at `1` and then would actually appear to move backwards/shrink after B was added.) Right now we're [using elevation as an absolute z value directly](https://github.com/flutter/engine/blob/master/flow/scene_update_context.cc#L359).
- [ ] Flutter needs to be able to repaint its UI when its AABB is updated along the z axis. I *think* the hook for x and y is in [`SceneUpdateContext::Clip::Clip`](https://github.com/flutter/engine/blob/master/flow/scene_update_context.cc#L279), where right now there is no Z bounding at all. Z bounds should also be piped up into the framework and exposed where appropriate, most likely to `MediaQuery` and `ChildView` as mentioned above.
- [ ] Flutter needs to offer a hook to Scenic for transforming its UI along the z axis in general. I think we may have a hook for this for x and y already in [`SceneUpdateContext::Transform::Transform`](https://github.com/flutter/engine/blob/master/flow/scene_update_context.cc#L310)? If we don't have this [Z-fighting](https://en.wikipedia.org/wiki/Z-fighting) is a potential problem.
- [ ] (optional) I think it probably makes sense for developers to be able to set z and control the positioning of Widgets in 3D space instead of having to rely on the 2.5d "elevation" concept to try and set z, but I'm not sure the best way to expose this.

**Comment by mklim** [comment]
Initially I assumed I would enforce Z bounds in the engine and expose it in the framework, but as I've dug into this more I don't think that's necessarily the right way to go. 

From what I can tell the root source of the current 2D viewport bounds is [`PlatformView`](https://fuchsia.googlesource.com/topaz/+/master/runtime/flutter_runner/platform_view.h). [`#onPropertiesChanged`](https://fuchsia.googlesource.com/topaz/+/master/runtime/flutter_runner/platform_view.h#141) includes Z, and it's fairly straightforward to update [`ViewportMetrics`](https://github.com/flutter/engine/blob/master/lib/ui/window/viewport_metrics.h) to include an optional `physical_depth` member to go along with `physical_height` and `physical_width`. But from there I'm not sure the best way to use the value. [`Window#updateWindowMetrics`](https://github.com/flutter/engine/blob/master/lib/ui/window/window.h#L65) pipes the info back up to dart [`Window.physicalSize`](https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L446) (a 2D rect at the moment), where it goes through a few more jumps into the framework (and is exposed by `MediaQuery` and `onMetricsChanged` callbacks) before ending up as [`ViewConfiguration.size`](https://github.com/flutter/flutter/blob/92125ed38fcd1834c3e12bf8db325e26e30645d2/packages/flutter/lib/src/rendering/view.dart#L26). I'm having trouble tracing it from there with 100% certainty but I'm fairly sure it's used in the framework to create the layer tree before that's sent down to the engine again, probably through [`ClipContext`](https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/lib/src/painting/clip.dart#L8) and eventually into the engine's [`painting.dart`](https://github.com/flutter/engine/blob/master/lib/ui/painting.dart#L3161).

So at this point I'm wondering whether the right place to enforce z bounds may be in the framework where it's drawing the layer tree, along with x and y. Originally I was thinking it would be where we're currently [using elevation as an absolute z value directly in the engine](https://github.com/flutter/engine/blob/master/flow/scene_update_context.cc#L359), but now I'm thinking it may make more sense where [elevation is set on layer.dart in the framework](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L1332)?

@chinmaygarde what do you think, any guidance/does this analysis sound right to you?

Also /cc @dnfield

**Comment by schwa423** [comment]
Something that just occurred to me, maybe others are already aware:

When Flutter engine squishes content to fit within the max-elevation of the provided bounds (see the "Flutter Interprets Z" section of "Elevation on Fuchsia" doc: https://docs.google.com/document/d/1a5nVPYFVsQaKNVXt-BC6I7aKi4UsIwJNTblmneKLHJA/edit#heading=h.1pr327rhr5q2), it should also take into account embedded child-views; these might need to have their bounds adjusted to match the squished elevations.

**Comment by amott9** [comment]
Yes, that is explained a bit in the use case of scrolling a set of views, here: https://docs.google.com/document/d/1a5nVPYFVsQaKNVXt-BC6I7aKi4UsIwJNTblmneKLHJA/edit#heading=h.hgwbfusr3m7k

**Comment by Hixie** [comment]
@mklim any updates?

**Comment by kf6gpe** [comment]
Note that customer: fuchsia is also tracking specific z-fighting issues with FL-236 and FL-214 in their Jira repo.

**Comment by mklim** [comment]
So far Flutter has been updated to take and track Scenic's z bounds. Right now we're just logging when we're drawing outside of the bounds overflow. 

- [x] ~Take z bounds from Scenic~
- [ ] Expose the z bounds up to the framework
- [ ] Handle the overflow in the engine. By default we should normalize on a non linear curve.

We're no longer z fighting automatically, but we're also not preventing z fighting in apps either. 

- [x] ~Fix bug that causes z fighting when rendering physical layers~
- [ ] Add workaround code that actively stops z fighting from ever happening by inserting epsilons between layers at the same worldspace z.

**Comment by Hixie** [comment]
We should probably split this into the three remaining bugs.

**Comment by Hixie** [comment]
Filed those as:
https://github.com/flutter/flutter/issues/33853
https://github.com/flutter/flutter/issues/33854
https://github.com/flutter/flutter/issues/33855
https://github.com/flutter/flutter/issues/33856

Closing this one.

**Comment by kf6gpe** [comment]
See also #11470
