### ISSUE TITLE
Delayed transitions are not trivial to set up

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#253]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 18:56 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1921_

---

We should look at how we can make wrapping a curve in an interval in a ValuePerformance easier.

**Comment by Hixie** [comment]
Maybe a PerformanceView that take a PerformanceView on one side, has a startAt argument (default 0.0) and an endAt argument (default 1.0), and implicitly creates the Interval that it applies to the PerformanceView that it exposes?

**Comment by abarth** [comment]
Sounds about right.

The tricky question here is whether we want to pump frames in the time period before we start the animation.  Imagine you schedule an animation to start in 30 seconds.  Do we really want to pump frames that whole time or do we want to use a timer to sleep until we're about ready to start?

The downside of using a timer is that the delay won't be measured with the animation clock.  That means if you have animation that's running for a minute and another that starts with a delay of 30s, it's not guaranteed that the delayed animation will start on the exact frame where the first animation passes the halfway mark.

IMHO, we should pump frames during the delay for now because that will be correct behavior and file a bug about using less power when waiting for a delayed animation.

**Comment by Hixie** [comment]
see #175

**Comment by Hixie** [comment]
It seems like this is trivial now using either Interval or async/await.
