### ISSUE TITLE
Can angulardart be used to perfectly develop flutter?

### ISSUE THREAD

**Issue by DreamPWJ** [flutter/flutter#25307]
Can angulardart be used to perfectly develop flutter? I prefer angular to dart

**Comment by DreamPWJ** [comment]
I like angualr and am used to dislike dart. I want to use angualr for cross-platform development. May I ask whether angular dart code can run perfectly in flutter?

**Comment by zoechi** [comment]
AngularDart and Flutter use Dart as programming language and are both developed by Google but are otherwise unrelated. 

AngularDart also uses Dart, so if your issue is with Dart what do you expect to gain?

If you meant TypeScript because of Angular TS, then this also won't work. Angular Dart and Angular TS also don't have much in common except some common roots.

It's probably better to get used to Dart and you'll start to like it. 
It's actually a nice language and there are many improvements planned.
