### ISSUE TITLE
TabBarView display same content on different position

### ISSUE THREAD

**Issue by xiaoluqiaoba** [flutter/flutter#25310]
## Steps to Reproduce

1. 使用TabBar+TabBarView的时候，第一次打开的情况下，默认tab是0，这个时候点击第4个tab，然后再点击第3个tab，此时当前tab(也就是第3个tab)显示的内容是第0个tab的。

我看了下TabBarView的源码，发现了bug所在，并使用了如图所示的方式解决的

> When using TabBar+TabBarView, the first time the tab is opened, the default tab is 0. At this time, click the 4th tab, and then click the 3rd tab. At this time, the current tab (that is, the 3rd tab) is displayed. The content is the 0th tab.
> 
> I looked at the source code of TabBarView, found the bug, and solved it as shown in the figure.

![image](https://user-images.githubusercontent.com/5737150/49921305-1d2a9d80-fee8-11e8-82ef-88987acbfee0.png)

2.bug原因是：TabBarView的_warpToCurrentIndex方法中的几行代码逻辑有问题，参见下面代码注释内容

> There are problems with a few lines of code logic in the _warpToCurrentIndex method of TabBarView. See the code comments below.

```dart
Future<void> _warpToCurrentIndex() async {
    if (!mounted)
      return Future<void>.value();

    if (_pageController.page == _currentIndex.toDouble())
      return Future<void>.value();

    final int previousIndex = _controller.previousIndex;
    if ((_currentIndex - previousIndex).abs() == 1)
      return _pageController.animateToPage(_currentIndex, duration: kTabScrollDuration, curve: Curves.ease);

    assert((_currentIndex - previousIndex).abs() > 1);
    int initialPage;
    setState(() {
      _warpUnderwayCount += 1;
      _children = List<Widget>.from(widget.children, growable: false);

      if (_currentIndex > previousIndex) {
       //导致bug的地方1。此时，如果previousIndex = 0，_currentIndex=4，那么第3个tab就会显示成
       //第0个tab的内容了
        _children[_currentIndex - 1] = _children[previousIndex];
        initialPage = _currentIndex - 1;
      } else {
       //导致bug的地方2。此时，如果previousIndex = 4，_currentIndex=0，那么第1个tab就会显示成
       //第4个tab的内容了
        _children[_currentIndex + 1] = _children[previousIndex];
        initialPage = _currentIndex + 1;
      }
    });

    _pageController.jumpToPage(initialPage);

    await _pageController.animateToPage(_currentIndex, duration: kTabScrollDuration, curve: Curves.ease);
    if (!mounted)
      return Future<void>.value();

    setState(() {
      _warpUnderwayCount -= 1;
      _children = widget.children;
    });
  }
```
3.  请贵司开发人员帮忙确认下，这种修复方式是否正确？

> Please ask your developer to help confirm, is this repair method correct?

**Comment by xster** [comment]
cc @HansMuller

**Comment by SteveAlexander** [comment]
I've been working on a fix to this in https://github.com/flutter/flutter/pull/24821

@xiaoluqiaoba I think your diagnosis is correc.t

The PR still merges cleanly, and there are tests.

It's been there since November, but I need a conversation with a Flutter team member to decide how to move forward on the fix. It's not clear to me which way to go — the current support for KeepAlives is arguably faulty.

I think a correct fix would require StatefulWidget children of a TabView to have unique keys, as the TabView switches the order of children around as it scrolls.

A better long-term fix would be to have the "warping" UI effect happen at the rendering layer, not by switching children around.

@xster @HansMuller I'd love a quick conversation (via the PR, or on Slack perhaps?) on this, so I can move this PR forward. I have time and willingness to do so, but I do need some direction to continue.

**Comment by luohaohaha** [comment]
Is it fixed now? I got the same issue.

**Comment by luohaohaha** [comment]
Is it fixed now? I got the same issue.
![ezgif-2-1909b6f03a22](https://user-images.githubusercontent.com/3376376/53779771-69600980-3f3c-11e9-91bd-04b130d7b845.gif)

**Comment by SteveAlexander** [comment]
@luohaohaha try adding a Key to each of the widgets you're adding in your TabView.

For more advice, I recommend you head to Stack Overflow, and check out this video which explains when to use keys and what you'll see when you don't use them: https://www.youtube.com/watch?v=kn0EOS-ZiIc

**Comment by hahafather007** [comment]
@SteveAlexander I was solved this problem by adding keys, but i found that sometime it can't keep alive.

**Comment by hahafather007** [comment]
Is there a reliable solution to fix TarBarView?

**Comment by HansMuller** [comment]
This PR was intended to address the problem with TabBarView as well as reordering lazily sliver lists in general - https://github.com/flutter/flutter/pull/29188

It was recently landed and then reverted. I believe @chunhtai is working to get it landed again.

**Comment by chunhtai** [comment]
yes, https://github.com/flutter/flutter/pull/29188 should fix it. It also seems like didUpdateWidget is not implemented. The reason you see the tab0 content on tab 3 is because it try to update tab0 with tab3 by calling didUpdateWidget AFTER the warp finish. if you have not implemented didUpdateWidget, it will use the same state as tab0 thus cause the issue. Using the key will let flutter think tab0 and tab3 are different tab, so it will destroy and reinitialize the tab. In this case, my pr should fix the keepalive issue.

I will suggest implement didUpdateWidget first and see if it fixes customers issue
