### ISSUE TITLE
Plugin template: classpath is incomplete in VSCode

### ISSUE THREAD

**Issue by JssDWt** [flutter/flutter#25369]
## Steps to reproduce
1. Create a new plugin project, using `flutter create --template=plugin tryout`
2. Open the project in VSCode
3. Open android/src/main/java/com/example/tryout/TryoutPlugin.java
4. VSCode (RedHat java extension) will show a warning that the classpath is incomplete. This means there is no intellisense on the java files for flutter classes and can't 'go to definition'.

How do I 'complete' the classpath? In Android Studio the classpath is fine and there is no problem to 'go to declaration'.

My flutter doctor is OK, I'm on the latest version of flutter, VSCode and extensions. Build is running fine, so the classpath can be found during build.

**Comment by zoechi** [comment]
@DanTup

**Comment by DanTup** [comment]
I'm afraid I don't know much about Java, but based on https://github.com/redhat-developer/vscode-java/issues/107 I wonder whether it's related to the folder you're opening. If you open the `android` folder (from File -> Open) instead of the main Flutter project, does that change anything? (I'm not suggesting it's a good fix, but may help understand the issue).

**Comment by JssDWt** [comment]
When I open the android folder (from File -> Open) it shows the same warning, unfornutately: Classpath is incomplete.

**Comment by devoncarew** [comment]
> will show a warning that the classpath is incomplete

I think there'd need to be a bunch of work on the part of the user to patch up a working classpath here - jar files for android APIs, and the flutter java apis, and any apis from flutter plugins. I think this error is expected - you can use VS Code to edit the Java files for a flutter project, but shouldn't expect for it to be a functioning android development experience.

For non-trivial changes to the Java side of your app, I would recommend using Android Studio.

**Comment by JssDWt** [comment]
I was hoping it would be a configuration error here, since the redhat java plugin claims to have 'Basic Gradle Java project support' and the classpath can apparently be found on build. I guess for the fullblown flutter app we'll have to use both VSCode and Android Studio (and XCode?) then.
BTW, I hadn't seen the 'Open in Android Studio' shortcut before. I'll be using that from now on.

**Comment by DanTup** [comment]
> I guess for the fullblown flutter app we'll have to use both VSCode and Android Studio (and XCode?) then.

That's the officially supported way, yep. Editing (Java) Android apps in VS Code is likely out of scope for Flutter, though that's not to say it's not/won't be possible with other extensions. I see there's at least one Android extension in the VS Code marketplace that may help (though note that it's marked preview and this is not an endorsement of it's quality or trustworthyness).

I'll close this since I don't think there are plans to do anything here, however if editing the java part of the Android app does become viable in the future and it seems like the Flutter plugin for VS Code could make this easier with some tweaks, feel free to open an issue at https://github.com/Dart-Code/Dart-Code for discussion.
