### ISSUE TITLE
Flutter with Java+C#

### ISSUE THREAD

**Issue by reader-man** [flutter/flutter#25450]
Thanks a lot on this very beautiful and powerful SDK/platform.
It would help us a lot if you make it easy to use all the libraries and widgets with other main stream languages, like Java and C#.

Regards.

**Comment by zoechi** [comment]
You can use https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages or https://docs.flutter.io/flutter/widgets/AndroidView-class.html to make Java features available to Flutter.

There are community approaches to make Flutter and C# work together
like https://github.com/adamped/xamarin.flutter

There is also https://github.com/flutter/flutter/issues/7053

I'm going to close this issue because it's too broad and I don't think it's actionable this way.
