### ISSUE TITLE
Flutter will crash when use TextField to input Chinese with maxLength

### ISSUE THREAD

**Issue by 123lxw123** [flutter/flutter#25511]
### Environment
iOS 12.1

![image](https://user-images.githubusercontent.com/20809823/50158483-32039880-030f-11e9-878c-27f505a88e7e.png)
### Language
Chinese
### Sample Code
```dart
TextField(
   maxLength: 2,
)
```
Very easy to reappear，such as input “hh” when use Chinese input method，it will crash without any log in Android Studio

![image](https://user-images.githubusercontent.com/20809823/50157429-59a53180-030c-11e9-8340-4787ed68c7e0.png)

When I input the second "h", the value in the `editable_text.dart` is this

![image](https://user-images.githubusercontent.com/20809823/50157885-8a399b00-030d-11e9-994a-41faf572562f.png)

Then I debug step by step, it crash in `platform_messages.dart`

![image](https://user-images.githubusercontent.com/20809823/50158110-2bc0ec80-030e-11e9-8aee-e6260d281278.png)

Finally I get some log from Mac Controller.app 

![image](https://user-images.githubusercontent.com/20809823/50158390-fbc61900-030e-11e9-8a15-5c23c9df5883.png)

**Comment by zoechi** [comment]
Could you please post the log output as text so that it is searchable?

**Comment by 123lxw123** [comment]
```
activate generator <_UIKeyboardFeedbackGenerator: 0x6000017cce60: prepared=1> with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2 . 
activate engine <_UIFeedbackSystemSoundEngine: 0x6000002dda40>, clientCount: 1 -> 2   
played feedback <_UICustomDiscreteFeedback: 0x6000017cd9a0> with engine <_UIFeedbackSystemSoundEngine: 0x6000002dda40> at time 471.438826   
deactivate generator <_UIKeyboardFeedbackGenerator: 0x6000017cce60: prepared=1> with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1   
deactivate engine <_UIFeedbackSystemSoundEngine: 0x6000002dda40>, clientCount: 2 -> 1   
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {0, 3} out of bounds; string length 2'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001089961bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107f34735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108996015 +[NSException raise:format:] + 197
	3   CoreFoundation                      0x00000001088de2d3 -[__NSCFString substringWithRange:] + 163
	4   UIKitCore                           0x0000000113f40999 -[UIKeyboardImpl hasMarkedText] + 143
	5   UIKitCore                           0x0000000113f30200 __43-[UIKeyboardImpl generateAutofillCandidate]_block_invoke + 51
	6   UIKitCore                           0x0000000113f83b3b -[UIKeyboardTaskEntry execute:] + 169
	7   UIKitCore                           0x0000000113f8232a -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 374
	8   UIKitCore  <…>
```

**Comment by yy1300326388** [comment]
I have encountered the same problem, and constantly input on iOS, do not click to confirm the input, it will crash.
The current solution is to not limit maxLength on the iOS platform.

**Comment by MrLittleStrong** [comment]
This crash is reported in stable 1.17.1 again , while not reported in stable 1.12.13+hotfix9.  Should I open a new issue? @kangwang1988   @gaaclarke

**Comment by pjyx** [comment]
I fixed it by:
diff --git a/packages/flutter/lib/src/widgets/editable_text.dart b/packages/flutter/lib/src/widgets/editable_text.dart
index fcfaf63913..4f2ab112d1 100644
--- a/packages/flutter/lib/src/widgets/editable_text.dart
+++ b/packages/flutter/lib/src/widgets/editable_text.dart
@@ -4,6 +4,7 @@
 
 import 'dart:async';
 import 'dart:math' as math;
+import 'dart:io' show Platform;
 import 'dart:ui' as ui hide TextStyle;
 
 import 'package:flutter/foundation.dart';
@@ -1666,15 +1667,35 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     final bool isRepeatText = value?.text == _lastFormattedUnmodifiedTextEditingValue?.text;
     final bool isRepeatSelection = value?.selection == _lastFormattedUnmodifiedTextEditingValue?.selection;
     final bool isRepeatComposing = value?.composing == _lastFormattedUnmodifiedTextEditingValue?.composing;
-    // Only format when the text has changed and there are available formatters.
-    if (!isRepeatText && textChanged && widget.inputFormatters != null && widget.inputFormatters.isNotEmpty) {
-      for (final TextInputFormatter formatter in widget.inputFormatters) {
-        value = formatter.formatEditUpdate(_value, value);
+    if (Platform.isIOS) {
+      // ios Composing变化也执行format，因为在拼音阶段没有执行LengthLimitingTextInputFormatter，从拼音到汉字需要重新执行
+      if (((!isRepeatText && textChanged) || !isRepeatComposing) && widget.inputFormatters != null && widget.inputFormatters.isNotEmpty) {
+        for (final TextInputFormatter formatter in widget.inputFormatters) {
+          if ((formatter is LengthLimitingTextInputFormatter) && value != null &&
+              value.composing != null
+              && value.composing.isValid) {
+            // ios拼音阶段不执行长度限制的format
+            // do nothing
+          } else {
+            value = formatter.formatEditUpdate(_value, value);
+          }
+        }
+        // Always pass the text through the whitespace directionality formatter to
+        // maintain expected behavior with carets on trailing whitespace.
+        value = _whitespaceFormatter.formatEditUpdate(_value, value);
+        _lastFormattedValue = value;
+      }
+    } else {
+      // Only format when the text has changed and there are available formatters.
+      if (!isRepeatText && textChanged && widget.inputFormatters != null && widget.inputFormatters.isNotEmpty) {
+        for (final TextInputFormatter formatter in widget.inputFormatters) {
+          value = formatter.formatEditUpdate(_value, value);
+        }
+        // Always pass the text through the whitespace directionality formatter to
+        // maintain expected behavior with carets on trailing whitespace.
+        value = _whitespaceFormatter.formatEditUpdate(_value, value);
+        _lastFormattedValue = value;
       }
-      // Always pass the text through the whitespace directionality formatter to
-      // maintain expected behavior with carets on trailing whitespace.
-      value = _whitespaceFormatter.formatEditUpdate(_value, value);
-      _lastFormattedValue = value;
     }

**Comment by Jaykong** [comment]
Any progress on this bug?

**Comment by eyesoffish** [comment]
I did this
`onChanged: (val) {
      if(val.length > 10) controller.text = val.substring(0,10);
  },
`
