### ISSUE TITLE
Android Dark Mode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#25525]
Since Froyo, Android has had a Dark Mode feature. We should implement it.

This Java code detects if it's enabled:

```java
(mContext.getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES;
```

The activity or fragment's `onConfigurationChange` apparently triggers when this changes.

We should propagate this state to the MediaQuery somehow (via a system channel, I guess, though we would need to find a way to send the data early in the process so that it's available on first build).

MaterialApp should switch between its regular `theme` and a `darkTheme` automatically based on this setting.

cc @HansMuller, @matthew-carroll, @jason-simmons

**Comment by matthew-carroll** [comment]
I'll try hacking on this.  Hopefully won't take much to get working.

**Comment by matthew-carroll** [comment]
CC @willlarche for visibility

**Comment by matthew-carroll** [comment]
@Hixie here's an update after looking into this.

The capability that was added in **Froyo** was intended to be specific to car mode, at least according to this SO post:
https://stackoverflow.com/questions/31934503/to-implement-android-night-mode-using-uimodemanager-and-enable-car-mode-but-sh

However, it looks like **Pie** introduced an Android theme called DayNight, which utilizes a different night mode property found within AppCompatDelegate:
https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate#MODE_NIGHT_YES

With Pie, AppCompatDelegate allows an individual app to force light, force dark, or use an auto value based on time.  However, this setting appears to be per-app, as opposed to a system setting a la Apple's Dark Mode.

Supporting Pie's night mode makes sense because it seems like a mainstream, future facing capability.  @Hixie do you think we want/need to support the Froyo car mode version, too?

**Comment by matthew-carroll** [comment]
@slightfoot I checked with the Android folks and got the correct property hooked up for battery saver and the dev option on Pie.  It's currently in a PR.

**Comment by gedw99** [comment]
So dark mode looks amazing.
How to use it in a real app ?

Are light and dark now available as standard material themes in material design ? So I can just check the OS and flip the baked in material theme.

**Comment by timrijckaert** [comment]
Any example on how to use this?

**Comment by mrk-han** [comment]
@timrijckaert @gedw99 
See https://github.com/flutter/flutter/pull/26605
and https://medium.com/flutter-io/android-dark-theme-in-flutter-9c8070b8b127
