### ISSUE TITLE
Random Chinese text wrong weight/traditional/simplified rendering on iPhone

### ISSUE THREAD

**Issue by wonderful89** [flutter/flutter#25726]
![image](https://user-images.githubusercontent.com/44089389/50389958-a4d79e00-076b-11e9-85d8-4766b7904513.png)

It should be showed in normal font, but it is showed in bold font.

![image](https://user-images.githubusercontent.com/44089389/50389965-bfaa1280-076b-11e9-85ae-c0423fd0c46f.png)

This should be showed in Simplified Chinese, but it is showed in traditional Chinese.

The two cases rarely happen. But it not nice when happen. I guess it is font rendering issue. 

Did anyone encounter this situation?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by wonderful89** [comment]
> Please add the output of `flutter doctor -v`.

➜  Work flutter doctor -v
[✓] Flutter (Channel unknown, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/xyz/Work/GitHub/awesome-flutter/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

It seems that it happened in before version too. Our users encounter it random in release mode.

**Comment by xster** [comment]
cc @GaryQian who handles similar font issues in the past

**Comment by zoeyfan** [comment]
@GaryQian I vaguely remembered that you looked into a similar issue before. Is this still relevant? If not, can we close it now?
Besides, I am not seeing a consistent repro here, if the information provided in the bug is not sufficient for investigation, please feel free to close it with a comment back to the customer.

**Comment by zoeyfan** [comment]
We don't think this issue is still present in the latest Flutter version. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!
