### ISSUE TITLE
What's the default unit of measurement in flutter?

### ISSUE THREAD

**Issue by vanshu** [flutter/flutter#25833]
## Steps to Reproduce

I am using AppBar class to set App bar of the page, there is an attribute called [elevation](https://docs.flutter.io/flutter/material/AppBar-class.html)
```The z-coordinate at which to place this app bar. This controls the size of the shadow below the app bar.```
The document hasn't figured out what's the default unit measurement of elevation, in Android We use dp,px
so how about flutter?

**Comment by timsneath** [comment]
Hi @vanshu, it is measured in pixels, as described here: https://docs.flutter.io/flutter/material/Material-class.html. We could clarify this in the docs.

**Comment by xster** [comment]
I think this should add an FAQ entry for this. We're fairly web-y in our terminology which tends to mainly focus on logical pixels but Android and iOS developers tend to be very specific about whether they meant logical pixels (points, dp/sp) or physical pixels (px, pixels). Us using just 'pixels' when we meant logical pixels is doubly confusing since 'pixels' typically mean physical pixels on Android and iOS.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2156](https://github.com/flutter/website/issues/2156) via [**ZenHub**](https://www.zenhub.com/)
