### ISSUE TITLE
registerResGeneratingTask is deprecated ,   cannot save in firebase database 

### ISSUE THREAD

**Issue by aneesalahsab** [flutter/flutter#25850]
please help
When I run the Flutter application, it works normally but when I save to the database, it does not save؟؟ 
```
Launching lib/main.dart on ????? in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
D/NetworkSecurityConfig(14610): No Network Security Config specified, using platform default
```

**Comment by zoechi** [comment]
A deperecation warning should not cause issues until the deprecated API is actually removed, but then you should get a build error.

**Comment by Steve-sy** [comment]
what is happening guys! did they removed the API? my apps are crashing due to " registerResGeneratingTask is deprecated "

**Comment by zoechi** [comment]
@Steve-sy that's not enough information. Please post the output of `flutter doctor -v` and the full console log.

**Comment by brian-dunn** [comment]
I'm getting the same problem. It seems to be related to a recent version of Firebase or Flutter, as my code used to work. Here is the `flutter doctor` output::

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.3)
[√] Connected device (1 available)

• No issues found!

I get the follow error repeated five time in the debug console:

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

• No issues found!

And, my app won't load. It immediately crashes on the Android emulator.

**Comment by glourencosilva** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
W/.hybrid.afv_ap(16870): Unsupported class loader
W/.hybrid.afv_ap(16870): Skipping duplicate class check due to unsupported classloader
Syncing files to device Android SDK built for x86...
I/.hybrid.afv_ap(16870): The ClassLoaderContext is a special shared library.
I/.hybrid.afv_ap(16870): The ClassLoaderContext is a special shared library.
I/.hybrid.afv_ap(16870): The ClassLoaderContext is a special shared library.
I/DynamiteModule(16870): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:11210
I/DynamiteModule(16870): Selected remote version of com.google.android.gms.ads.dynamite, version >= 11210
I/.hybrid.afv_ap(16870): Background concurrent copying GC freed 12663(2006KB) AllocSpace objects, 11(220KB) LOS objects, 50% free, 1598KB/3MB, paused 27.219ms total 135.037ms
W/.hybrid.afv_ap(16870): Unsupported class loader
W/.hybrid.afv_ap(16870): Skipping duplicate class check due to unsupported classloader
D/DynamitePackage(16870): Instantiated singleton DynamitePackage.
D/DynamitePackage(16870): Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl
D/NetworkSecurityConfig(16870): No Network Security Config specified, using platform default
I/WebViewFactory(16870): Loading com.android.chrome version 73.0.3683.90 (code 368309012)
I/.hybrid.afv_ap(16870): The ClassLoaderContext is a special shared library.
I/cr_LibraryLoader(16870): Time to load native libraries: 33 ms (timestamps 6057-6090)
I/chromium(16870): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(16870): Expected native library version number "73.0.3683.90", actual native library version number "73.0.3683.90"
I/.hybrid.afv_ap(16870): ThreadFlipBegin blocked for 7.987ms
W/cr_ChildProcLH(16870): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup(16870): Initializing chromium process, singleProcess=false
W/.hybrid.afv_ap(16870): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
I/FA      (16870): Tag Manager is not found and thus will not be used
I/OpenGLRenderer(16870): Initialized EGL, version 1.4
D/OpenGLRenderer(16870): Swap behavior 1
D/        (16870): HostConnection::get() New Host Connection established 0xbab41080, tid 17003
W/OpenGLRenderer(16870): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer(16870): Swap behavior 0
D/EGL_emulation(16870): eglCreateContext: 0xc3720000: maj 2 min 0 rcv 2
D/EGL_emulation(16870): eglMakeCurrent: 0xc3720000: ver 2 0 (tinfo 0xc29910c0)
D/EGL_emulation(16870): eglCreateContext: 0xc83b01e0: maj 2 min 0 rcv 2
D/EGL_emulation(16870): eglMakeCurrent: 0xc83b01e0: ver 2 0 (tinfo 0xdba51a50)
D/EGL_emulation(16870): eglMakeCurrent: 0xc3720000: ver 2 0 (tinfo 0xc29910c0)
W/.hybrid.afv_ap(16870): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/.hybrid.afv_ap(16870): Verification of void com.google.firebase.auth.api.internal.zzec.zzd(java.lang.String, java.lang.String, com.google.firebase.auth.api.internal.zzdx) took 269.387ms
W/.hybrid.afv_ap(16870): Verification of void com.google.firebase.auth.api.internal.zzec.zzj(java.lang.String, com.google.firebase.auth.api.internal.zzdx) took 189.448ms
D/        (16870): HostConnection::get() New Host Connection established 0xc8461040, tid 16920
D/EGL_emulation(16870): eglMakeCurrent: 0xc83b01e0: ver 2 0 (tinfo 0xdba51b90)
I/flutter (16870): Transition { currentState: Uninitialized, event: AppStarted, nextState: Unauthenticated

**Comment by PandaGeek1024** [comment]
Im getting the same warning, this should not be just closed like this.

**Comment by ShashankSirmour** [comment]
https://stackoverflow.com/questions/46984770/registerresgeneratingtask-is-deprecated-use-registergeneratedfoldersfilecollec/48309373

**Comment by udxgen** [comment]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
this is my flutter doctor 

[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.6.3 at C:\Users\Viswas Computers\Flutter_SDK\flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Viswas Computers\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\Viswas Computers\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Redmi 5A • 6d9ec85e7d94 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

Any one plz help me how to solve this

**Comment by kroikie** [comment]
@aneesalahsab

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/527. Any further collaboration will be done there.
