### ISSUE TITLE
Expanded text while parent widget only has max-width

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25889]
Just report that I occrued this rare usage, I want a `Container` inside a row to auto wrap it's content, it can be done by automatically. and I can set another container to limited this one's width, But I have a text inside this Container, and I want it auto wrap text, this can only be done in a Expanded, but the Expanded must specific the width of parent widget. This is the conflict part.

Basically, I want a Container, which has a background, it can only wrap it's content (background color will effect if it set to fix width) and meanwhile, I want the text inside the Container to auto wrap text, in this situation what should we do???

It seems very hard to find a solution.

Now I can only set Container to fix width which is ugly:

However, I really want something like this:

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

A screenshot of the actual behavior and the expected behavior (if you are able to achieve that with a workaround) would be helpful as well.

**Comment by jinfagang** [comment]
@zoechi Thanks, I am ending achieve that with Wrapper widget.
