### ISSUE TITLE
shared_preferences: Add String afterwards to a stringlist in Flutter

### ISSUE THREAD

**Issue by dariotrombello** [flutter/flutter#25894]
It would be a feature request to add/remove just one String on a list of Strings instead of just overriding all of them with `setStringList()`.

**Comment by zoechi** [comment]
I haven't tried but I think that's supported already.
Can you please provide a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run that demonstrates the problem and allows to reproduce?

**Comment by Borduni** [comment]
I'm not sure how this can be demonstrated by runnable code the best. I try to explain it a bit better.

In shared preferences you can remove, get or set a value (doesn't matter if string, int etc.). But shared preferences also supports a type called stringList.

Example for a stringlist with 3 items:
```
itemList() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  var items = <String>["item1", "item2", "item3"];
  prefs.setStringList('items', items);
}
```

The problem here with a stringlist is now that if you use `setStringList()` to update the values you override the complete list. In my case i just need to add/remove only one string in this list. On all other types it doesnt matter because for example an int only has one number.

**Comment by zoechi** [comment]
I assume you could read using `getStringList` add/remove strings and then call `setStringList` with the updated list. This seems easier to me than adding a bunch of additional methods to the plugin.

**Comment by sir-boformer** [comment]
I agree with @zoechi. That's also how it works in Android. you always have to set the list manually.
Adding extra methods for adding, removing and replacing items would just increase the complexity of the plugin, with no performance benefit. probably it would even be worse because every modification would trigger a save to disk.

If the readability of your code would benefit from it, you could just create a wrapper class.
