### ISSUE TITLE
Should exist an async version of `compute`

### ISSUE THREAD

**Issue by neokree** [flutter/flutter#25890]
The compute method is really a good way to push a heavy job in background, but I think that it have a major drawback: It cannot accept async methods for his callback.

This forces everyone who wants just to do a background job that require something asynchronous to learn all isolate low level concept. (For which there is not a good documentation at this time of writing). 

It would be nice that flutter provides a new `compute` method for asynchronous tasks. 
Can you please think about it?

**Comment by zoechi** [comment]
I'd expect async functions to work but haven't tried myself yet. 
What problem did you run into?

**Comment by neokree** [comment]
I did not expect async function to work because of this statement in the documentation:
`You may experience errors if you try to pass more complex objects, such as a Future or http.Response between isolates.` 
Available here: https://flutter.io/docs/cookbook/networking/background-parsing#notes-on-working-with-isolates

However, trying things myself, this snippet of code is not working. 
file location: `lib/main.dart`
```
import 'package:flutter/foundation.dart';

void main() async {
  var result = await compute(returnDelayed, 3);
  print(result);
}

Future<int> returnDelayed(int value) async {
  return Future.delayed(Duration(seconds: 1)).then((p) => value);
}
```

The Dart Analysis does not report any error, however, the print statement is never executed. 
My request is about having another method, for example `computeAsync`, which can handle Future returns. 
An alternative with Streams could also be considered.

**Comment by zoechi** [comment]
For me it prints `Instance of 'Future<int>'` which also does not make sense because of the `await`
but I assume this is because of what you posted in your above comment that `Future` instances can't be passed between isolated. 

Actually it looks like `compute()` really can't handle async results which limits it quite a bit.

You can always set up isolates yourself like in plain Dart. For example using https://pub.dartlang.org/packages/isolate.

`compute()` is only a convenience method for basic use cases.

**Comment by devnoname120** [comment]
This can be closed now that https://github.com/flutter/flutter/pull/30275 has been merged.
