### ISSUE TITLE
Flutter Video Player plugin installation steps update

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#25904]
For installation steps in [Flutter Video Plugin](https://github.com/flutter/plugins/tree/master/packages/video_player#installation) , for *Android* the only  step mentioned is to add `<uses-permission android:name="android.permission.INTERNET"/>` to Manifest.

But, the plugin also requires Java 8. So it would nice if documentation was updated to reflect to add the following lines to *build.gradle* , as default Flutter project does not have it and it causes exception.

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by Daibaku0615** [comment]
Hi, thank you for sharing this.
I'm having hard time to initialize video with it and I think it's worth for trying this.
Could you share your ` build.gradle` and which `gradle` is this?
I'm sorry for silly question since I'm from `iOS` land.

**Comment by zoechi** [comment]
If you create a new Flutter project with `flutter create foo` this is already included in the Gradle file.

See https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated for how to update existing projects.

I'm closing because I don't think there is anything specific to do.
Feel free to add a comment if you disagree to have the issue reopened.
