### ISSUE TITLE
image_picker pickImage disable save/cancel

### ISSUE THREAD

**Issue by BoHellgren** [flutter/flutter#25920]
In my app, I use `carImage = await ImagePicker.pickImage(source: ImageSource.camera)` to take a picture. This works fine. After taking the picture, two buttons are displayed, Save and Cancel (or something similar , the labels are in Swedish in my case.) After pressing Save, I am returned to the next statement in my app code.

I would prefer not to have these buttons. I want to return to my code immediately after taking the picture, without having to press a button.

Is this possible? How?

(I cannot use the `camera` plugin due to its orientation bug on Samsung Galaxy phones, issue #25232 )

**Comment by kvandivo** [comment]
Agree that this would be very nice.  It appears that the google drive widget to capture a PDF also started having a 'confirm' dialog recently, so it's probably an underlying code feature that might not be avoidable.

**Comment by cyanglaz** [comment]
@BoHellgren First of all, thanks for raising this feature requests and I do think it is a good feature to have. I can totally imagine some apps can be improved with this feature.

@kvandivo is correct, Unfortunately, there is no way to do it with the current image picker native implementation due to the restriction on the image picker APIs of iOS and Andrioid. The camera plugin is your best bet, or you might need to add your own native camera implementation.
I am closing this issue, but if you find a way to actually do it with the native image picker, please feel free to open an issue to explain the method, I will be happy to implement. Or if you'd like to create a PR for it, I will be happy to review!
