### ISSUE TITLE
How to use Flutter in a large team w/o all developers knowing?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#25979]
Would like instructions on how to use Flutter in a large team w/o all developers needing to install Flutter or know that Flutter is being used.

For example, can the Flutter SDK be a git submodule and the tooling used be relative to the checkout (instead of all developers installing Flutter separately)?

Or can Flutter be used to produce an intermediate build product (a .framework, .aar, etc.) that then can be checked-in/cached, but other parts of the app could depend on?

We've received this question (or ones like it) from several large firms using/exploring-use-of Flutter.

FYI @matthew-carroll who might have other bugs to link this to/dup it to.

**Comment by neiljaywarner** [comment]
Thanks so much for filing this Eric.  I've worked with this quite a bit lately and am down so far to two concerns . re: submodules

1. Documentation, probably including code comments in local.properties like regular Android projects, especially with info about flutter get packages regenerating the file, and ideally in readme.md as well
2. Ideally if we can figure out how to get "flutter packages get" to autorun with a modification to settings.gradle or help from android studio team or both...
2b.  Maybe it can all come down to "flutter create -t --full" and it does it all for us eventually :) . Similar to how gradle version if typically tied to a specific Android project.
3.  the intermediate build product would be fantastic; since it would help with ease of collaboration with other devs and build times

thanks again!

**Comment by zoechi** [comment]
Related #24948

**Comment by kangwang1988** [comment]
I think there are several points for this case:
P1. In a multiple team co-working environment, when only one team use flutter, it's quite simple. The flutter team can develop flutter in a flutter development environment, export their codes as a bundle(aar for android or pod for ios) to other people who don't know flutter. For the non-flutter team, all they need is to import the bundle as before, they don't know/need flutter environment.
P2. However, when multiple team are using flutter(not all), those flutter developers need a unified flutter environment. They can't do as said in P1 directly. Instead, they needs to develop flutter and export multiple pubs. Then a flutter wrapper project will import those pubs and export a bundle(arr or pod) as said in P1. The rest is the same as P1.

**Comment by neiljaywarner** [comment]
@xster  I wonder if there jerry rigging solution is a) Suitable for production and b) a tecnique they would share unofficially. 
i.e. can a technique like theirs serve as a backup solution that is still reliable until their is an official solution..

**Comment by xster** [comment]
@kangwang1988: I suspect you guys probably had a blog post somewhere for @neiljaywarner  :)

**Comment by neiljaywarner** [comment]
@eseidel great job on getting 1.2 out the door at MWC.  Any ideas on this for March?

**Comment by eseidelGoogle** [comment]
@dnfield has done some thinking here (as has possibly @csells), but nothing concrete at this time.

**Comment by pszklarska** [comment]
Hello, are there any updates regarding this issue? I've seen some work done for the Android (e.g. #35217), but nothing for the iOS. I think that's the use case that many companies (including mine) may benefit from. I'd love to see higher priority set on this.

**Comment by neiljaywarner** [comment]
The dependency on cocoapods can also be A challenge...

**Comment by xster** [comment]
This is currently being looked at on iOS as well. Follow progress on https://github.com/flutter/flutter/issues/26099

**Comment by xster** [comment]
Solved by https://github.com/flutter/flutter/issues/26099 and https://github.com/flutter/flutter/issues/36968. Currently documented in https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps and soon moved to flutter.dev website.
