### ISSUE TITLE
Plugin architecture commonly leads to plugins assuming they have an activity available (crashing when used with android_alarm_manager)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26003]
See e.g. #24780, #20913, #21972, #25912, and their duplicates.

cc @matthew-carroll @amirh

**Comment by matthew-carroll** [comment]
FYI - This issue should be resolved by #22117. This issue is a specific manifestation of the larger problems associated with the current Android plugin API.

**Comment by collinjackson** [comment]
#22117 is an issue, not a PR, so removing waiting for PR label

**Comment by lucien-theron** [comment]
Is there a workaround for this in the meanwhile? I cannot use android_alarm_manager and google_maps_flutter together. Thanks

**Comment by amirh** [comment]
@lucien-theron thanks for flagging this, applying the same workaround to maps and camera in https://github.com/flutter/plugins/pull/1255

**Comment by matthew-carroll** [comment]
@Hixie @amirh The plugin embedding API has now been upgraded in the new embedding to avoid the assumptions that this ticket calls out. However, all existing plugins remain as they were. Should we close this ticket because the "architecture" has been improved? Or should we reword this ticket and treat it as a metabug for the individual plugin issues that are linked in the description?

**Comment by Hixie** [comment]
We should probably track the migration of the ecosystem to the new API. cc @amirh since that's probably in his wheelhouse.

**Comment by Hixie** [comment]
I'm going to close this issue. We can track migration and deprecation of the old API at a different level.
