### ISSUE TITLE
Shrine app shows overscroll glow indicator in both dimensions

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26036]
Take a sufficiently tall Android phone. 

Scrolling horizontally shows an overscroll glow. This is expected.
Scrolling vertically also shows an overscroll glow. This is unexpected since nothing scrolls vertically in this screen.

**Comment by xster** [comment]
cc @willlarche

**Comment by willlarche** [comment]
That I will need to do some digging on for sure.

**Comment by willlarche** [comment]
That's not why they are scrollering lists. They are scrolling lists because sized cards broke the backdrop motion.

BUT, they are supposed to be sized inside the list to not trigger scrolling at all.

**Comment by rami-a** [comment]
Looks like there are 2 issues here actually:

1. When all content fits on the screen, the overscroll glow (android) and bounce (iOS) still happens when it shouldn't
2. Sometimes the cards do not all fit on screen and that causes vertical scrolling.

I'm going to make 2 a separate issue, the PR #27217 fixes 1.
