### ISSUE TITLE
Integration Add2App with ImagePicker can't get image from camera Android

### ISSUE THREAD

**Issue by xenixcorp** [flutter/flutter#26053]
## Steps to Reproduce
1. Create new flutter project with code [main.dart](https://gist.github.com/xenixcorp/63f2b4511daa2d4f71251980b40313d5)
2. Create new Android app with code [MainActivity.java](https://gist.github.com/xenixcorp/a61316cf6d679f71f40b3cfa219d917a)
3. Add flutter project into existing android app [(wiki)](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)
4. Run the android app and start the MainActivity will showing flutter view.
5. Click button and open camera, take picture from camera. Usually if running from Flutter App image will show. but if integrate with Add2App the image not showing.
I'm trying logging in activityOnResult in MainActivity.java but the 'data' is null or empty.

## Logs
no error but the image not show.
if i check data in MainActivity.java, the data is null
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
        at com.pede.emoney.ui.activity.loan.LoanActivity.onActivityResult(MainActivity.java:40)
```

## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-ID)
    • Flutter version 1.0.0 at /Users/indoalliz/Desktop/Flutter/fluttersdk
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/indoalliz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/indoalliz/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • 127.0.0.1:62001 • 127.0.0.1:62001 • android-x86 • Android 4.4.2 (API 19)

! Doctor found issues in 1 category.
```

**Comment by filleduchaos** [comment]
@xenixcorp 

So this isn't a bug, more that the Add2App documentation is still a work in progress. In a Flutter-only app, there's quite a bit of platform-specific glue code that hooks things up so that the platform and Flutter can communicate properly. If you're manually including the framework in an app and you're not taking advantage of the classes Flutter already uses for this (e.g. FlutterActivity), then you'll have to write that glue code yourself.

Fortunately it's just a handful of lines in this case: first, you need to actually _register_ the plugin using the `io.flutter.plugins.GeneratedPluginRegistrar` class - this is what lets project-agnostic code (like in the image_picker plugin) interact with _your_ activities and such. A `FlutterView` comes with a plugin registry, so that's a one-liner (`GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());`) before you add the FlutterView to your layout. Second, you need to forward whatever results your Activity receives to the plugins you have installed so they can handle them (in this case, send the selected image over to the Flutter side of the app). Again this is a one-liner - `flutterView.getPluginRegistry().onActivityResult(requestCode, resultCode, data);` - but since you're doing it in the `onActivityResult` handler, you'll need to hang on to a reference to your FlutterView.

Putting both together, you get this activity:

```java
public class MainActivity extends AppCompatActivity {
    private FlutterView flutterView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        flutterView = Flutter.createView(this, getLifecycle(), "route1");
        GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());
        FrameLayout.LayoutParams layout = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        addContentView(flutterView, layout);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!this.flutterView.getPluginRegistry().onActivityResult(requestCode, resultCode, data)) {
            // The plugin registry's onActivityResult handler returns a boolean, so if the intent wasn't meant for a Flutter plugin you can handle it here
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
}
```

which brings up the image picker and displays the selected image as expected.

**Comment by xenixcorp** [comment]
@filleduchaos Sorry for late reply, i  just try your suggestion and its work as expected.
Thank you for helping me.
