### ISSUE TITLE
Invoke Dart code from native Android home screen widget's onUpdate()

### ISSUE THREAD

**Issue by westy92** [flutter/flutter#26148]
I would like to call some Dart code from a [native Android home screen widget's `onUpdate()` method](https://developer.android.com/reference/android/appwidget/AppWidgetProvider#onUpdate(android.content.Context,%20android.appwidget.AppWidgetManager,%20int[])).

For the sake of example, we can assume the Dart code simply returns a `string`.

Due to the extensive use of the term "widget" in Flutter, it has been hard to find anything regarding this topic.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
