### ISSUE TITLE
Package Publish validation regression

### ISSUE THREAD

**Issue by Sh1d0w** [flutter/flutter#26171]
Hi I have published several Flutter plugins.

Until today everything was working ok. I had to publish a change on one of my packages.

Upon running `flutter packages pub publish` I got the following error

<img width="564" alt="screenshot 2019-01-07 at 10 23 47" src="https://user-images.githubusercontent.com/5074917/50757047-cd30c380-1266-11e9-9ebe-905e11515336.png">

I had this folder before, and it was not giving me such warnings.

Furthermore this warning conflicts with GitHub and does not makes sense at all. I have enabled Github pages integration for my repo, where I host the docs for the plugin. Github expects your Github pages source to be in the `docs` folder, but flutter complains I have to rename it to `doc` ...

<img width="316" alt="screenshot 2019-01-07 at 10 22 22" src="https://user-images.githubusercontent.com/5074917/50757145-1123c880-1267-11e9-96f2-7a54b4d9b718.png">

Why this warning was introduced, is there any good reason for it and what can be done about it?

**Comment by zoechi** [comment]
> Furthermore this warning conflicts with GitHub and does not makes sense at all.

It "conflicts" with the docs feature from pub.dartlang.org that uses the `doc` directory.
The `doc` directory mentioned in the warning is listed in https://www.dartlang.org/tools/pub/package-layout.

It might just be an additional check added by `pub` package manager
to avoid a common mistake that `docs` is used instead of the supported `doc`.

Please report the issue in https://github.com/dart-lang/pub
