### ISSUE TITLE
Flutter should be smarter about memory limits for images

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#26187]
Currently there are a number of ways in which users can trigger out of memory errors on a Flutter application which lead to nasty stack traces. For example, https://github.com/flutter/flutter/issues/21571#issuecomment-450519975. We can probably do better than this, but there is some discussion about what parts of the system should be responsible and how "smart" is reasonable.

Do we know how much memory we have available, such that we could detect that decoding an image will cause OOM? For example, If a user loads 50 images and the 39th would cause them to OOM, could we throw an exception that would be surfaced by the ImageProvider instead?

What about cases where a user has accidentally retained images? Could we swap out the bits with a small grey/white buffer to allow the engine to reclaim memory even when the user prevents it? 

What about the memoryPressure signal? Could the engine make use of this to stop decoding images, or does it arrive too later?

cc @eseidel  @chinmaygarde

**Comment by chinmaygarde** [comment]
In my view, it's going to be a stretch to fix this in a sufficiently smart manner. 

> If a user loads 50 images

At this point, its probably too late for the following reasons:
* We can't reliably detect how much device memory is available under changing circumstances and varying driver overhead (which we don't have a view into).
* While we can check whether the next image allocation was successful (the "Can I allocate the next image?" question) and we we do, this puts the system very close to the edge of memory consumption. At this point, all other components in the engine on different thread (include platform specific components) need to do the same checks for each new allocation. This is not the case. So its not the next image allocation that pushes the process over the edge, its the next unchecked allocation (which can be any other component).

> What about cases where a user has accidentally retained images?
This is just a leak. Also, the image may be referenced in a picture or a scene.

> Could we swap out the bits with a small grey/white buffer to allow the engine to reclaim memory even when the user prevents it?

This is not something we have considered. Mostly because detecting this case involves getting close to the state where the next allocation fails. At this point, since the system is already in an unstable state, we may end up crashing while these operations are being performed.

> What about the memoryPressure signal? Could the engine make use of this to stop decoding images, or does it arrive too later?

I don't think the image decoders drop decode jobs that are in flight due to memory pressure but this is certainly something to explore. 

On a related note, @dnfield has been investigating how to be more aggressive about the collection of images that are GC eligible in https://github.com/flutter/flutter/issues/56482. Obviously, this is slightly different from applying a cap on the allocations that can be dedicated for images.

**Comment by jonahwilliams** [comment]
Closing as infeasible
