### ISSUE TITLE
Best practice for Integration with custom engine

### ISSUE THREAD

**Issue by Letty-Liang** [flutter/flutter#26341]
- Requirement: develop with our custom engine, without changing the develop experience

- Questions:

1. I'v read the guide, but just find the way to integrate a local debug engine with local-engine options. In this way, I can test it locally, but for a team, it change the traditional build way, it is not convenient to use;
Is there any suggestion about how to integration with custom engine without changing the local flutter sdk;

2. Can you provide a configuration of how to generate a custom engine just the same as the sdk provides; in this way, our team can easily replace with our custom engine;

3. Will you provide something like gradlew to control the flutter sdk management;

THX

**Comment by kangwang1988** [comment]
@Letty-Liang 
Just FYI
In our practice, we use custom Flutter Engine (C++) and custom Flutter Framework(Dart).
1.
We have a Flutter Framework(Git Repo) which is forked from the git@github.com:flutter/flutter.git
2.
Using `flutter doctor -v`, we can download cache artifacts (default) and get the engine version.
3.
Using `https://github.com/flutter/engine/blob/master/CONTRIBUTING.md`, we can get all dependencies for flutter engine.
For each engine dependency we want to apply patches on, we fork one in our gitlab.
After the "gclient sync" procedure, those patches will be applied.(a custom branch manage those patches)
4.
Call the engine compilation, or triggered by gitlab webhook. Those engine products which is used in Flutter Framework(libflutter.so&gen_snapshot for android, Flutter.framework& gen_snapshot for ios) are used to overwrite the original ones in Flutter Framework.(Done by CI&Scripts)

For those guys who develops engine(just a few), they know where and how to edit the engine.
For those guys who develops flutter(many guys), they don't need to know the custom engine logic. Besides, all the guys in our team share a Flutter Framework repo(where bin/cache is added into git control so that it's exactly the same for all guys).

**Comment by Letty-Liang** [comment]
> @Letty-Liang
> Just FYI
> In our practice, we use custom Flutter Engine (C++) and custom Flutter Framework(Dart).
> 1.
> We have a Flutter Framework(Git Repo) which is forked from the [git@github.com](mailto:git@github.com):flutter/flutter.git
> 2.
> Using `flutter doctor -v`, we can download cache artifacts (default) and get the engine version.
> 3.
> Using `https://github.com/flutter/engine/blob/master/CONTRIBUTING.md`, we can get all dependencies for flutter engine.
> For each engine dependency we want to apply patches on, we fork one in our gitlab.
> After the "gclient sync" procedure, those patches will be applied.(a custom branch manage those patches)
> 4.
> Call the engine compilation, or triggered by gitlab webhook. Those engine products which is used in Flutter Framework(libflutter.so&gen_snapshot for android, Flutter.framework& gen_snapshot for ios) are used to overwrite the original ones in Flutter Framework.(Done by CI&Scripts)
> 
> For those guys who develops flutter(many guys), they don't need to know the custom engine logic. Besides, all the guys in our team share a Flutter Framework repo(where bin/cache is added into git control so that it's exactly the same for all guys).
> 
> For those guys who develops engine(just a few), they know where and how to edit the engine, once submitted and compiled, the products will be copied and submitted to the Flutter Framework repo automatically.


Thank you very much~
Ask for more details about 4；
About how to generate cache artifacts  just like the sdk structure;  I didn't find any official document provided；What's your solution? Just overwrite the the original ones with some specific products, or regenerate all of it and then format these just like the sdk;

**Comment by kangwang1988** [comment]
@Letty-Liang 

You can't and needn't to reproduce them all.
All you need to consider is what your custom engine code has bring changes to bin/cache directory.
Pay attention to: Flutter.framework/flutter.jar(libflutter.so)/gen_snapshot if you change c++ code.

It would be another thing if you've changed sky_engine packages(dart:async,etc).

**Comment by blasten** [comment]
It sounds like this was sorted out as per https://github.com/flutter/flutter/issues/26341#issuecomment-453464581
