### ISSUE TITLE
Publish firebase_auth 0.7.0

### ISSUE THREAD

**Issue by degroote22** [flutter/flutter#26374]
This is just a heads up in case you've forgotten to do this.
[The current version on github is 0.7.0](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/pubspec.yaml#L7)

The docs of the publish version (0.6.6) tells us to use the [example](https://github.com/flutter/plugins/tree/master/packages/firebase_auth/example) for documentaion, and the example only works with version 0.7.0.

This [version of the example](https://github.com/flutter/plugins/blob/50e2ec8760acf026f54b4aadd7c9ab4dcee81958/packages/firebase_auth/example/lib/main.dart) is the one correct for the published version but it is linked nowhere.

Thanks for the attention 👍

**Comment by amirh** [comment]
@collinjackson

**Comment by nhathiwala** [comment]
I'm currently using the latest FirebaseAuth library directly from git repo, how every I have been trying to use ``linkWithCredential`` method to link phone auth to an already existing `EmailAndPassword` account. However, I'm unable to do so, due to ``linkWithCredential`` is only referencing to ``handleLinkWithEmailAndPassword(call, result, getAuth(call));``.

This is seems like the functionality for ``linkWithCredential`` is very much limited and quiet not useful for other usecase, such as social media account linking.

It also lack functionality for changing phone number of a PhoneAuth user.

**Comment by kika** [comment]
@nhathiwala 

> I'm currently using the latest FirebaseAuth library directly from git repo, how every I have been trying to use linkWithCredential method to link phone auth to an already existing EmailAndPassword account.

I'm doing the same and it works for me. I can link phone account to email-password account. I haven't tested linking FB account though yet.

Verification of the phone number on Android is failing with unhandled exception probably because this piece of code is missing: https://github.com/flutter/plugins/pull/980/commits/b26b2722283f072797a13586df91c7d74758d820

Today is the 1 month birthday of this PR :-)

**Comment by kika** [comment]
Related: https://github.com/flutter/flutter/issues/26477

**Comment by mklim** [comment]
Thanks for the reminder, sorry about the delay. 0.7.0 has been published now.

**Comment by kroikie** [comment]
@lucasavila00

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/512. Any further collaboration will be done there.
