### ISSUE TITLE
FadeTransition animation is backwards

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26508]
https://master-docs.flutter.io/flutter/widgets/FadeTransition-class.html <- pretty sure that diagram is backwards. It implies that the child is visible at 0.0 and invisible at 1.0.

cc @gspencergoog

**Comment by gspencergoog** [comment]
Yeah, good point.  I think I did that (and for ScaleTransition and SizeTransition) because it looked better in the initial frame (otherwise it's just an empty frame, and I thought that would be confusing).

You're right though, it is misleading, especially since it's not called out anywhere.  I'll swap all three to be correct.
