### ISSUE TITLE
Obfuscated text fields should disable the IME autocorrect (iOS)

### ISSUE THREAD

**Issue by jbg** [flutter/flutter#26684]
Internal: b/144379659

iOS beautifies punctuation automatically in text input fields, for example in my locale by turning "foo" into “foo” and 'bar' into ‘bar’. In another locale these might instead become «foo» and ‹bar›. Replacements also occur for sequences of dashes, for example -- becomes the em dash (—).

This feature is generally desirable (at least to me), but having control over it can be very useful in some situations. For example, I am developing an app that involves sending messages, which in some cases are sent over SMS (which has complex text encoding considerations) and in other cases directly via my servers (which simply use UTF-8). When I know the message will be sent over SMS, I would like to disable this feature on the text field, as even a single “smart quote” character will cause the entire message to be sent as UCS-2/UTF-16, costing the user twice as much per character.

Another example would be a TextField used for entering code, or for data entry, where the " character is not necessarily punctuation.

iOS provides the ability to control this functionality via methods on [UITextInputTraits](https://developer.apple.com/documentation/uikit/uitextinputtraits), specifically `smartQuotesType` and `smartDashesType`. I was unable to find an equivalent on Android, and my limited experience suggests that this type of automatic punctuation replacement isn’t a feature of Android.

Would a patch that adds support for controlling “smart punctuation” behaviour on `TextField` be accepted despite this functionality being (currently) specific to iOS?

**Comment by clamb** [comment]
This is a serious issue when entering password with a TextField. A user registering with an Android device and using `"` in its password will have trouble using the same app with an iPhone since he won't be able to enter the character `"` when signing in.

![obscured_text_field_flutter](https://user-images.githubusercontent.com/812924/58374643-e69a8980-7f41-11e9-8e34-f2ed446e5794.gif)

**Comment by justinmc** [comment]
I agree this is a big problem.  I think Flutter should do two things:

  1. Expose control of `UITextSmartQuotesType` and `UITextSmartDashesType` via two new parameters on TextField and CupertinoTextField.
  1. Set these parameters by default when `obscureText` is true so that password fields avoid this problem by default.

The docs should state clearly that these two parameters do not affect Android.  If Android adds smart punctuation support in the future, hopefully these parameters can be used to cover both platforms.  

See the [enableSuggestions flag](https://github.com/flutter/flutter/pull/42550) which does something similar for Android only.
See also [this Apple forum thread](https://forums.developer.apple.com/thread/89706).

**Comment by Hixie** [comment]
@robertoscaramuzzi We're not sure we'll be able to make your deadline but we'll give it a go. :-)

**Comment by jbg** [comment]
The scope of the issue I opened seems to have been significantly narrowed, from exposing general control over smart quotes/dashes and the like to just disabling autocorrect on obfuscated fields.

Whilst I concede that 10 months has passed since I opened it :-), I still have a need for control over smart quotes/dashes in text fields in Flutter, though admittedly perhaps not enough of a need to submit a pull request yet.

Should I open another issue to track the general case?

**Comment by justinmc** [comment]
I do intend to solve the original general case, unless I'm misunderstanding the full problem.  I intend to add two parameters to TextField that map to UITextInputTraits on iOS:

```dart
TextField(
  disableSmartQuotes: true,
  disableSmartDashes: true,
)
```

In addition, I plan to default both of these parameters to true when `obscureText` is true, so that people avoid this problem with passwords by default.

I may change the details but that seems reasonable right now.  Let me know if that doesn't cover everything for you.

**Comment by Hixie** [comment]
Please use "enable" rather than "disable" to avoid "disable: true" which is confusing. See style guide.

**Comment by cbracken** [comment]
All PRs for this are now LGTM.

**Comment by justinmc** [comment]
As of https://github.com/flutter/flutter/pull/44923, fields with `obscureText: true` will automatically disable smart quotes and smart dashes.  If you want to manually do this, you can also pass `smartDashesType: SmartDashesType.disabled` and `smartQuotesType: SmartQuotesType.disabled` to any text field.
