### ISSUE TITLE
AnimatedList should be simplified

### ISSUE THREAD

**Issue by martinory** [flutter/flutter#26708]
Hi! AnimatedList is too complicated when lots of things are going on. I rather have the component being fed the model and that the animated list itself decides what to do with it, ie what items are going to be inserted or removed. Otherwise, I end up with a list not matching the model.

**Comment by zoechi** [comment]
Can you please elaborate on your concrete use case?
A minimal reproduction of the problem you face and what you'd prefer to have changed.

**Comment by simolus3** [comment]
Not 100% sure if this is what's meant by the author, but it would be nice to have something like an `ImplicitAnimatedList` that only takes a `List` as model. It could then find an edit script between two lists whenever that widget updates to animate the content. Similar to a `RecyclerView` with `DiffUtil` on Android perhaps.

That would also give us a reactive way to animate list content by wrapping such list into a `StreamBuilder<List<T>>`.

**Comment by RobPFarley** [comment]
I feel that @simolus3 's comment describes the problem perfectly. Flutter is designed to be declarative, but AnimatedList is imperative in that updating its content is quite difficult to do when the data source is further up the tree. For example when using a StreamBuilder<List<T>> to build your view, building an AnimatedList using the updated List<T> becomes very difficult as manipulating the List<T> can't be done from inside the widget containing the AnimatedList. Having a way to make AnimatedList more delcarative would make working with Streams much easier

**Comment by karmazinkd** [comment]
> 
> 
> I feel that @simolus3 's comment describes the problem perfectly. Flutter is designed to be declarative, but AnimatedList is imperative in that updating its content is quite difficult to do when the data source is further up the tree. For example when using a StreamBuilder<List> to build your view, building an AnimatedList using the updated List becomes very difficult as manipulating the List can't be done from inside the widget containing the AnimatedList. Having a way to make AnimatedList more delcarative would make working with Streams much easier

Absolutely right. 
One of the common use cases is displaying data from the Stream.  For example a Firestore data stream.
Every time you have to figure out by yourself which items should be added/removed and figure out their new indices in order to manually call insert()/remove() methods with those indeces on AnimatedList. 
And what about the case when the existing item was updated and it should change it's position (for example the list is sorted by last change date). It should go from one index to another. 
Also don't forget to handle all animations correctly, meaning that on every insertion/removing the list is changed and every next item movement should consider those changes. 
It's a hell of a nightmare. 

We definitely need StreamAnimatedList widget.
