### ISSUE TITLE
Error loading some .webp images

### ISSUE THREAD

**Issue by skycomposter** [flutter/flutter#26757]
I have a simple app that displays .webp assets in Image widgets using the `asset` constructor:

`Image.asset('assets/animation.webp')`

I have 8 such assets, but although they all animate correctly outside of Flutter, only 2 of them work properly in the app. The other six get stuck and stop animating almost immediately, and produce the following exception:

```E/flutter ( 9189): [ERROR:flutter/lib/ui/painting/codec.cc(413)] Frame 18 depends on frame 13 which has not been cached.
I/flutter ( 9189): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 9189): The following _Exception was thrown resolving an image frame:
I/flutter ( 9189): Exception: operation failed
I/flutter ( 9189): 
I/flutter ( 9189): When the exception was thrown, this was the stack:
I/flutter ( 9189): #0      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:498:20)
I/flutter ( 9189): <asynchronous suspension>
I/flutter ( 9189): #1      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:477:9)
I/flutter ( 9189): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9189): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter ( 9189): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
I/flutter ( 9189): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter ( 9189): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter ( 9189): #7      _invoke1 (dart:ui/hooks.dart:173:13)
I/flutter ( 9189): #8      _beginFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 9189): 
I/flutter ( 9189): Image provider: AssetImage(bundle: null, name: "assets/8.webp")
I/flutter ( 9189): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#faddb(), name: "assets/8.webp", scale:
I/flutter ( 9189): 1.0)
I/flutter ( 9189): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

[These](https://github.com/flutter/flutter/files/2773270/assets.zip) are the assets. Only 3.webp and 6.webp work, and the remaining 6 break as shown above.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please also post the image that caused the crash if possible.

**Comment by mehmetf** [comment]
My understanding is that this is a regression as the client is claiming an earlier checkpoint used to work.

**Comment by mehmetf** [comment]
@chinmaygarde Does this look like a Skia problem (in webp decoding)?

**Comment by mehmetf** [comment]
Analyzing the uploaded webp files via libwebp yielded nothing. They are all valid animated webps with no discernible property.

**Comment by eseidelGoogle** [comment]
iirc @amirh added our WebP support, but this may also related to skia?

**Comment by amirh** [comment]
Running this for 1.webp I get:
```
E/flutter (15547): [ERROR:flutter/lib/ui/painting/codec.cc(413)] Frame 17 depends on frame 14 which has not been cached.
```

This looks like a regression we introduced in https://github.com/flutter/engine/pull/7048 .
I'm guessing that it means our assumption that a required frame is either the previous frame or the previous required frame doesn't hold in this case. Though reading the [spec for WebP frame disposal methods](https://developers.google.com/speed/webp/docs/riff_container#animation) again, it says are just 2 disposal methods:

```
0: Do not dispose. Leave the canvas as is.

1: Dispose to background color. Fill the rectangle on the canvas covered by the current frame with background color specified in the ANIM chunk.
```

As far as I understand this, for both disposal methods all the required information is present in the previous frame, so I'm not sure how can frame 17 depend on frame 14. 

This probably means that we need to go back to more aggressive caching, though I'd really like to better understand what's wrong in our frame dependency constraints assumptions, to see if we can still run with less memory.
cc @mklim 

Side note - The exception we got here was not very useful, I also filed #27249 to report back better errors to the Dart side.

**Comment by mehmetf** [comment]
This may very well be an issue with the webp files as well. I can dig up some internal contacts for webp if you wish if you want to verify your understanding of the spec.

**Comment by amirh** [comment]
@mehmetf that will be great

**Comment by mklim** [comment]
@amirh We should still be able to count the amount of times a frame is used and store it that long at least without going back to storing all required frames forever. These files do animate fine in Chrome.

**Comment by amirh** [comment]
Confirmed with the webp team that our frame dependency assumptions should always be correct for animated webp files. This sounds like something weird is going on in Skia, will follow-up with the Skia team.

For reference in 1.webp Skia reported that frame 17 requires frame 14, but the disposal method for frame 17 is actually none, so it should only depend on frame 16.

A handy tool they pointed out that helps debug this is `webpmux -info`, for reference this is the output for 1.webp:

```
Canvas size: 140 x 140
Features present: animation transparency
Background color : 0xFFFFFFFF  Loop Count : 0
Number of frames: 78
No.: width height alpha x_offset y_offset duration   dispose blend image_size  compression
  1:    70   130   yes       40        4       80 background    no       1986       lossy
  2:    70   128   yes       40        6       80 background    no       1990       lossy
  3:    72   124   yes       36       10       80 background    no       2046       lossy
  4:    74   124   yes       30       10       80 background    no       1892       lossy
  5:    76   126   yes       32        8       80 background    no       1914       lossy
  6:    81   128   yes       38        6       80 background    no       2166       lossy
  7:    79   128   yes       44        6       80 background    no       2026       lossy
  8:    77   130   yes       46        4       80 background    no       2054       lossy
  9:    78   128   yes       44        6       80 background    no       2014       lossy
 10:    81   126   yes       38        8       80       none    no       2126       lossy
 11:    85   125   yes       34        8       80       none    no       2144       lossy
 12:    87   126   yes       34        8       80       none    no       2238       lossy
 13:    85   126   yes       36        8       80       none    no       2122       lossy
 14:    80   128   yes       40        6       80       none    no       2130       lossy
 15:    79   128   yes       40        6       80       none    no       2078       lossy
 16:    77   126   yes       38        8       80       none    no       2076       lossy
 17:    80   128   yes       34        6       80       none    no       2116       lossy
 18:    83   128   yes       34        6       80 background    no       2158       lossy
 19:    81   124   yes       38       10       80 background    no       2178       lossy
 20:    77   126   yes       42        8       80 background    no       2110       lossy
 21:    75   126   yes       42        8       80 background    no       2110       lossy
 22:    77   126   yes       40        8       80       none    no       2014       lossy
 23:    79   126   yes       38        8       80 background    no       2046       lossy
 24:    78   124   yes       36       10       80 background    no       2032       lossy
 25:    81   122   yes       34       12       80       none    no       2110       lossy
 26:    81   123   yes       34       10       80       none    no       2104       lossy
 27:    79   126   yes       36        8       80       none    no       2110       lossy
 28:    77   128   yes       38        6       80       none    no       2038       lossy
 29:    77   111   yes       38        6       80       none    no       1858       lossy
 30:    78   128   yes       38        6       80 background    no       2054       lossy
 31:    76   130   yes       42        4       80 background    no       2142       lossy
 32:    75   130   yes       44        4       80       none    no       2098       lossy
 33:    76   130   yes       44        4       80       none    no       2024       lossy
 34:    74   130   yes       46        4       80       none    no       2052       lossy
 35:    77   130   yes       44        4       80 background    no       2044       lossy
 36:    79   130   yes       32        4       80 background    no       1936       lossy
 37:    86   124   yes       20       10       80       none    no       1930       lossy
 38:    86   124   yes       20       10       80       none    no       1852       lossy
 39:    97   126   yes       20        8       80 background    no       2116       lossy
 40:   109   126   yes       28        8       80       none    no       1928       lossy
 41:   118   126   yes       20        8       80 background    no       1850       lossy
 42:    98   118   yes       24       16       80       none    no       2134       lossy
 43:   106   119   yes       24       14       80 background    no       2218       lossy
 44:   124   116   yes       12       18       80       none    no       2390       lossy
 45:   139   116   yes        0       18       80 background    no       2482       lossy
 46:   105   124   yes        0       10       80       none    no       2064       lossy
 47:   108   124   yes        0       10       80 background    no       1946       lossy
 48:    68   122   yes       44       12       80       none    no       1794       lossy
 49:    72   122   yes       40       12       80 background    no       1762       lossy
 50:    69   124   yes       36       10       80       none    no       1850       lossy
 51:    69   126   yes       36        8       80       none    no       1792       lossy
 52:    71   126   yes       38        8       80       none    no       1892       lossy
 53:    70   111   yes       40       10       80 background    no       1688       lossy
 54:    71   109   yes       38       12       80       none    no       1668       lossy
 55:    69   108   yes       40       10       80       none    no       1546       lossy
 56:    68    47   yes       40       10       80       none    no        690       lossy
 57:    61     9   yes       40       40      240       none    no        258       lossy
 58:    70   124   yes       38       10       80 background    no       1828       lossy
 59:    70   120   yes       36       14       80 background    no       1830       lossy
 60:    63   118   yes       34       16       80 background    no       1622       lossy
 61:    65   118   yes       34       16       80 background    no       1734       lossy
 62:    63   118   yes       38       16       80       none    no       1780       lossy
 63:    69   118   yes       36       14       80       none    no       1862       lossy
 64:    76   122   yes       34       12       80 background    no       1894       lossy
 65:    72   134   yes       36        0       80 background    no       2110       lossy
 66:    68   134   yes       38        0       80       none    no       2092       lossy
 67:    72   134   yes       38        0       80       none    no       2132       lossy
 68:    72   133   yes       40        0       80 background    no       2092       lossy
 69:    73   134   yes       36        0       80       none    no       2128       lossy
 70:    75   133   yes       36        0       80       none    no       2080       lossy
 71:    73   134   yes       38        0       80       none    no       2172       lossy
 72:    75   133   yes       36        0       80       none    no       2070       lossy
 73:    75   128   yes       36        6       80       none    no       2060       lossy
 74:    76   128   yes       36        6       80       none    no       2068       lossy
 75:    74   127   yes       38        6       80       none    no       2000       lossy
 76:    71   113   yes       40        8       80 background    no       1838       lossy
 77:    70   113   yes       40        8       80       none    no       1854       lossy
 78:    70   115   yes       40        6       80       none    no       1834       lossy
```

**Comment by LeonScroggins** [comment]
webpmux (like libwebp generally) uses 1-based indices, and SkCodec uses the 0-based indices I'm accustomed to. Based on stepping through the code, it looks to me like the frame 17 you're referring to is frame *18* in webpmux's output, and Skia determined that it depends on frame *15* in the same list. (I'll try to keep referring to the 1-based indices, so I'm in line with the list above, which has the info about the frames.)

Skia computes its dependencies based on the frame rectangles, disposal methods, blend methods, and whether frames have alpha. Let's look at the frames we care about:
```
No.: width height alpha x_offset y_offset duration   dispose blend image_size  compression
 15:    79   128   yes       40        6       80       none    no       2078       lossy
 16:    77   126   yes       38        8       80       none    no       2076       lossy
 17:    80   128   yes       34        6       80       none    no       2116       lossy
 18:    83   128   yes       34        6       80 background    no       2158       lossy
```
18 starts at position (34, 6), and is 38 x 128. It doesn't blend with the frame behind it, meaning that it "blends" as though there were nothing (transparent) behind its rectangle. Whether or not it has alpha, any frame that it is covering with its rectangle ultimately contributes nothing to the fully formed frame 18. (Its dispose method is irrelevant - that determines whether/how it contributes to the following frame.) So let's look at the previous frame - 17. It also starts at (34, 6), but it is only 80 x 128, so it's completely covered (and therefore erased by 18's blend method). Frame 16 also falls within that same rectangle. Frame 15 starts at (40, 6) and it is 79 x 128. So it is not covered by frame 18, and that's why Skia set the dependency that way.

Now the question you might be asking is "Why would I want frame 18 to depend on 15? I've already decoded 17!" The intent is to better support dropped frames. Last I checked (though some of us have questioned the benefit of this), Chromium would never show a frame if the frame's duration has passed. So, for example, the browser showed frame 15, then the image was offscreen or something, so the next frame we actually want to decode is frame 18. Naively, Chromium used to decode frames 16, 17, and 18 in quick succession. Only frame 18 is displayed, and it didn't make a difference to the final image that we spent time decoding frames 16 and 17.

In order to support both that use case, and a perhaps more typical use case of having already decoded frame 17 when it's time to decode frame 18, SkCodec is flexible about which frame you use as the dependent frame. Any frame which is not [kRestorePrevious](https://skia.googlesource.com/skia/+/cb6b8848de75055c60d7058ced7c5be3985faf49/include/codec/SkCodecAnimation.h#34) (note: WEBP doesn't use kRestorePrevious) since the "required" frame can be supplied to [fPriorFrame](https://skia.googlesource.com/skia/+/cb6b8848de75055c60d7058ced7c5be3985faf49/include/codec/SkCodec.h#289). (See the documentation for [fRequiredFrame](https://skia.googlesource.com/skia/+/cb6b8848de75055c60d7058ced7c5be3985faf49/include/codec/SkCodec.h#610). Please let me know if anything is unclear!) Chromium takes advantage of this with its [GetViableReferenceFrameIndex](https://cs.chromium.org/search/?q=GetViableReferenceFrameIndex&type=cs) ([link](https://chromium.googlesource.com/chromium/src/+/0ffa5c7b260f5ac3290bad107d5b74faba967ceb/third_party/blink/renderer/platform/image-decoders/gif/gif_image_decoder.h#71)).

Similarly, I think in [codec.cc](https://github.com/flutter/engine/blob/54f5467155241ce098339db85b08ff5f9649d8a4/lib/ui/painting/codec.cc#L411), you should just check to see whether you have a frame that fPriorFrame supports, rather than insist on having the one that SkCodec recommends. (Perhaps I should have a better name than fRequiredFrame? I'm open to suggestions...)

**Comment by sjmcdowall** [comment]
This isn't exactly related but since the latest upgrades I am now seeing a similar error on loading our Animated Gif -- our error message and trace is:
```
E/flutter (11062): [ERROR:flutter/lib/ui/painting/codec.cc(413)] Frame 10 depends on frame 0 which has not been cached.
I/flutter (11062): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (11062): The following _Exception was thrown resolving an image frame:
I/flutter (11062): Exception: operation failed
I/flutter (11062):
I/flutter (11062): When the exception was thrown, this was the stack:
I/flutter (11062): #0      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:498:20)
I/flutter (11062): <asynchronous suspension>
I/flutter (11062): #1      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:477:9)
I/flutter (11062): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (11062): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (11062): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
I/flutter (11062): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (11062): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (11062): #7      _invoke1 (dart:ui/hooks.dart:173:13)
I/flutter (11062): #8      _beginFrame (dart:ui/hooks.dart:143:3)
I/flutter (11062):
I/flutter (11062): Image provider: AssetImage(bundle: null, name: "assets/images/placeholder_light.gif")
I/flutter (11062): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#b98e0(), name:
I/flutter (11062): "assets/images/placeholder_light.gif", scale: 1.0)
```

Hopefully someone can shed some light on this?

**Comment by mklim** [comment]
Thanks for looking into this and all the info @LeonScroggins! 

I'm going to try and restate what you've said in my own words just to make sure my understanding is correct.

SkCodec has some additional optimizations on top of the bare WEBP/GIF specs to support Chromium's performance optimizations for when animated images are partially offscreen. SkCodec pays attention to how much of the canvas each frame really uses, and goes back and marks `fRequiredFrame` as the most recent disposal method none frame that filled more of the canvas than the current frame does. This can be much earlier than literally the last webp spec required frame going by disposal method. The actual spec compliant required frame still works in these cases for decoding though. So we can work around this in our case by passing any other valid previously decoded frame as `fPriorFrame` instead of panicking because we don't have the exact specified `fRequiredFrame`.

Does that sound right?

@sjmcdowall, that stack trace looks like this issue. Would it be possible for you to upload the asset causing the crash? We could debug it from there to confirm.

**Comment by LeonScroggins** [comment]
That is *almost* correct - the one exception:

> for when animated images are partially offscreen

It's really only for when an image is *completely* offscreen. If they're partially on screen, they animate and we show all the frames.

But more to the point - yes - you can just use the frame you have.

**Comment by sjmcdowall** [comment]
@mklim -- I missed the mention.  If this is still needed after the update (i.e. it didn't fix the GIF Animation issue) I will open a new one, but I bet this fix works for both.
