### ISSUE TITLE
[camera] Computed photo orientation isn't always right on iOS

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#26786]
We weren't saving iOS photo orientations at all until flutter/plugins#1037, but it looks like that patch doesn't work properly across all cases. See [this comment](https://github.com/flutter/plugins/pull/1037#issuecomment-455393496) by @idealopamp for a full analysis.

> I've been testing it out with camera lib 0.2.9+1, and it seems like there is a problem with the orientation that is being detected with the CMMotionManager. In general, we do not always get the correct orientations for our photos, especially when the device is pitched at an angle > 45% (I'm using the term pitch as defined in https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data/understanding_reference_frames_and_device_attitude )

**Comment by idealopamp** [comment]
Hi @mklim .  Wanted to let you know that I have also tested the version with UIDevice orientation on iPhone 6S and it works, even with the orientation locked.  So, it seems that it works on 6S, X, and iPad, but not 5S.  

Also curious - are you locking the orientation from within the app e.g. with flutter's setPreferredOrientation, or by locking the device as a whole into a fixed orientation?  Just wondering so I can make sure I test in the same way with other devices.

**Comment by mklim** [comment]
@idealopamp thanks for looking into it more. I'm locking the whole device, taking the same steps that [this page](https://www.verizonwireless.com/support/knowledge-base-207295/) describes. I'll update this once I test with some more devices and iOS versions on my end.

**Comment by mklim** [comment]
Hmm. I'm also seeing the locked UI problem on an iPad Air 2 (12.1) and 6s (12.1). I'm testing using the `camera/example` app.

**Comment by idealopamp** [comment]
Hi @mklim .  I was testing by locking within the app with setPreferredOrientation; I thought I had the same behavior with the global lock, but looks like I must not have done that test properly, because I am consistently seeing what you see now with the global lock -- it always returns portrait.  Sorry for misleading you on that.  I never have my orientation locked, but it sounds like a lot of users do, so this still seems to be a major problem.  

I'm going to test out an accelerometer-based approach as laid out in https://stackoverflow.com/a/28102890 and some other posts in the same thread. I will update with what I find.

**Comment by idealopamp** [comment]
Hi @mklim .  I tested out the approach used in the above SO post, and was pleasantly surprised to find that it generally seems to work, even for the various special case when the app starts in landscape mode (as well as the case where the screen orientation is locked).  I made a slimmed down version of https://stackoverflow.com/a/28102890 that is less influenced by the device being pointed downward or upward , since I think the user still wants the orientation of the photo to match device orientation if they are taking a picture of something below them.   

I created https://github.com/flutter/plugins/pull/1135 to capture the changes that I've been testing out  -- I had to do it from a fork rather than directly to flutter/flutter because I do not have permission to push branches to flutter/flutter .   Anyway it probably needs some code cleanup even if you do want to use it - I'm not at all familiar with best practices for objective-c code.  

One thing that I have not tested is the logic for front-facing cameras, I just copied over what you had already used with an unverified assumption that it would be the same when using the accelerometer.  

I think this approach might be more robust against unusual amounts of acceleration, e.g. the user is in a bumpy car ride, if one were to take an average/smoothing of the accelerometer metrics over the past few seconds, but that requires a bit more work to implement, so just starting with this to see what you think.  You may notice that if you shake the device up/down in portrait or left/right in landscape that the orientation sometimes comes out wrong.

**Comment by mklim** [comment]
Thanks so much for digging into this and opening a PR @idealopamp! Really appreciate it. 

/cc @bparrishMines
