### ISSUE TITLE
BottomNavigationbar Logic TextField is not touchable

### ISSUE THREAD

**Issue by vmwsree** [flutter/flutter#26810]
Steps To Reproduce
```dart
class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final int _pageCount = 2;
  int _pageIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _body(),
      bottomNavigationBar: _bottomNavigationBar(),
    );
  }

  Widget _body() {
    return Stack(
      children: List<Widget>.generate(_pageCount, (int index) {
        return IgnorePointer(
          ignoring: index != _pageIndex,
          child: Opacity(
            opacity: _pageIndex == index ? 1.0 : 0.0,
            child: Navigator(
              onGenerateRoute: (RouteSettings settings) {
                return new MaterialPageRoute(
                  builder: (_) => _page(index),
                  settings: settings,
                );
              },
            ),
          ),
        );
      }),
    );
  }

  Widget _page(int index) {
    switch (index) {
      case 0:
        return Page1();
      case 1:
        return Page2();
    }

    throw "Invalid index $index";
  }

  BottomNavigationBar _bottomNavigationBar() {
    final theme = Theme.of(context);
    return new BottomNavigationBar(
      fixedColor: theme.accentColor,
      currentIndex: _pageIndex,
      items: [
        BottomNavigationBarItem(
          icon: Icon(Icons.list),
          title: Text("Page 1"),
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.account_circle),
          title: Text("Page 2"),
        ),
      ],
      onTap: (int index) {
        setState(() {
          _pageIndex = index;
        });
      },
    );
  }
}
```

In the above code If one Of the Page has a `TextInputfield` And i am currently on the active page, but i am not able to tap the text input all other buttons are working, the keyboard doesn't show up, or i don't thinks it's being clicked.
In the attached i am not able to tap on write message text box, i have moved its position also the issue still persist.

<img width="267" alt="screen shot 2019-01-20 at 1 37 04 am" src="https://user-images.githubusercontent.com/1706515/51431777-f6345980-1c53-11e9-8c31-bb6d0ed92091.png">

**Comment by Kartik1607** [comment]
This seems a weird bug. I modified the code a bit to see the issue. It's not that the text field is not getting touch events (the *onTap* **is** called for both fields). The issue is keyboard pops up for **only the second** field. 

<img src='https://user-images.githubusercontent.com/17377741/51438234-911e4980-1ccf-11e9-9d9e-9eaee294bbec.gif' width=250/>

Full code I used to test.
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: HomePage(),
        ),
      ),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final int _pageCount = 2;
  int _pageIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _body(),
      bottomNavigationBar: _bottomNavigationBar(),
    );
  }

  Widget _body() {
    return Stack(
      children: List<Widget>.generate(_pageCount, (int index) {
        return IgnorePointer(
          ignoring: index != _pageIndex,
          child: Opacity(
            opacity: _pageIndex == index ? 1.0 : 0.0,
            child: Navigator(
              onGenerateRoute: (RouteSettings settings) {
                return new MaterialPageRoute(
                  builder: (_) => _page(index),
                  settings: settings,
                );
              },
            ),
          ),
        );
      }),
    );
  }

  Widget _page(int index) {
    switch (index) {
      case 0:
        return Column(
          children: <Widget>[
            RaisedButton(
              onPressed: () {},
              child: Text("Button $index"),
            ),
            TextField(
              onTap: (){
                print('Tapped $index');
              },
            )
          ],
        );
      case 1:
        return Column(
          children: <Widget>[
            RaisedButton(
              onPressed: () {},
              child: Text("Button $index"),
            ),
            TextField(
              onTap: (){
                print('Tapped $index');
              },
            )
          ],
        );
    }

    throw "Invalid index $index";
  }

  BottomNavigationBar _bottomNavigationBar() {
    final theme = Theme.of(context);
    return new BottomNavigationBar(
      fixedColor: theme.accentColor,
      currentIndex: _pageIndex,
      items: [
        BottomNavigationBarItem(
          icon: Icon(Icons.list),
          title: Text("Page 1"),
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.account_circle),
          title: Text("Page 2"),
        ),
      ],
      onTap: (int index) {
        setState(() {
          _pageIndex = index;
        });
      },
    );
  }
}

```

I did some digging and have some observations. Updated [this function](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L832)

```dart
void requestKeyboard() {
    print('Requesting Keyboard');
    print(widget.focusNode);
    if (_hasFocus)
      _openInputConnection();
    else
      FocusScope.of(context).requestFocus(widget.focusNode);
  }
```

Finding : Each text field have different focusNodes.
For text field 0 
```
I/flutter (19199): Requesting Keyboard
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): Requesting Keyboard
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): Tapped 0
```

For text field 1
```
I/flutter (19199): Requesting Keyboard
I/flutter (19199): FocusNode#3715f(FOCUSED)
I/flutter (19199): Requesting Keyboard
I/flutter (19199): FocusNode#3715f(FOCUSED)
I/flutter (19199): Tapped 1
```
Requesting keyboard is called **2 times**? The text field 0 is **never** able to get focused. 
To dig deeper I modified [requestFocus](https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/lib/src/widgets/focus_manager.dart#L247) 

```dart
 void requestFocus(FocusNode node) {
    assert(node != null);
    print("Requesting focus");
    print(node);
    print(_focus);
    if (_focus == node)
      return;
    _focus?.unfocus();
    node._hasKeyboardToken = true;
    _setFocus(node);
  }
```

Finding
For textflied 0
```
I/flutter (19199): Requesting focus
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): Requesting focus
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): FocusNode#a51ca
I/flutter (19199): Tapped 0
```

For textfield 1 this method is **not called** since, the field already have focus.

For field 0, somehow node passed and current focused node is same. So, FocusManger *does not try to refocus*. 

I thought to forcefully set focus to field by modifying the code to this, but this also failed.
```dart
  void requestFocus(FocusNode node) {
    assert(node != null);
    // if (_focus == node)
    //   return;
    _focus?.unfocus();
    node._hasKeyboardToken = true;
    _setFocus(node);
  }
```

I tried to go more deep and ended up at notifiers beyond which now I have no idea what is going on. One thing I think is happening is somehow the first text field's node updates current focused node and then as at every function there is a return check to check for equality the full chain stops. This issue would need guidance from official team. Sorry, I couldn't help you. I'll try to learn more and get back to this issue.

**Comment by vmwsree** [comment]
But it's one of the basic and common ux requirement.. i think should be addressed with a solution. And flutter having issues with implementing this is quite a surprise to me, i think as a software advocate we always praise flutter as it is limited by your imagination only. And this is a common requirement

**Comment by vmwsree** [comment]
But it's one of the basic and common ux requirement.. i think should be addressed with a solution. And flutter having issues with implementing this is quite a surprise to me, i think as a software advocate we always praise flutter as it is limited by your imagination only. And this is a common requirement

**Comment by HansMuller** [comment]
I'm looking into this. I created a simpler test case, just a column with two Navigators, each of which builds a route that contains a TextField: https://gist.github.com/HansMuller/dbe2a2673c4b8ee3f086b99489724be1

I agree that something like this should work, or at least it should be straightforward to make it work.

**Comment by HansMuller** [comment]
The root cause of this problem is the extra FocusScopes introduced by the Navigators. One can demo the issue with just a pair of FocusScopes:

```
Widget build(BuildContext context ) {
  return Scaffold(
    body: Container(
      padding: EdgeInsets.symmetric(horizontal: 16.0),
      alignment: Alignment.center,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          FocusScope(
            node: focusScopeNode0,
            child: Builder(
              builder: (BuildContext context) => TextField(),
            ),
          ),
          FocusScope(
            node: focusScopeNode1,
            child: Builder(
              builder: (BuildContext context) => TextField(),
            ),
          ),
        ],
      ),
    ),
  );
}
```

In this case the TextField's EditableText asks the enclosing FocusScope to make its FocusNode the current focus. Although the FocusScope's FocusScopeNode does update its idea of the focus (yes this is confusing) the enclosing FocusScope that belongs to the app's ModalRoute is _not_ changed.

Recursively updating the "first focus" of all of the enclosing FocusScopes mostly does the right thing. There's still a problem with the framework's keyboard visibility state to sort out.

This ordinarily doesn't come up because app's don't create FocusScopes and because ModalRoute.didPush helpfully changes the focus of the enclosing Navigator's FocusScope when it's pushed:
```
TickerFuture didPush() {
  navigator.focusScopeNode.setFirstFocus(focusScopeNode);
  return super.didPush();
}
```

Summary: still working on this.

**Comment by vmwsree** [comment]
Any workaround to achieve non-reloading bottom Navigation Experience?. That can show text widgets.
