### ISSUE TITLE
Widget Ease of use constraints

### ISSUE THREAD

**Issue by guodf** [flutter/flutter#26871]
There is a problem with the previous example, modified to the following question:
`
Scaffold(
      body: SliverAppBar()
    )
`
body is a widget,SliverAppBar is a widget,But the code above can't run. Can you see what I mean this time?

**Comment by guodf** [comment]
@zoechi Increase type limit

**Comment by Kartik1607** [comment]
The issue is **not** that sliver should be allowed. Issue is exactly opposite. If a Widget (Scaffold) **only** requires a child to be of type *RenderBox* then, we should (atleast at compile time) not able to pass a child of type *RenderSliver*. 

The same issue is in *CustomScrollView* which requires the children be of type **Slivers** (it is clear in this case because of use of word Slivers instead of children) but parameter tells to pass a list of Widgets. If someone unfamiliar with Sliver comes along, that person could possibly end up passing RenderBox widgets with no error.

**Comment by guodf** [comment]
> 问题**不**在于应该允许条子。问题恰恰相反。如果Widget（Scaffold）**只**需要一个子类型为_RenderBox，_那么我们应该（至少在编译时）不能传递_RenderSliv​​er_类型的子_元素_。
> 
> _CustomScrollView中_也存在同样的问题，它要求子类型为**Slivers**类型（在这种情况下很明显是因为使用了Slivers而不是子句），但参数告诉我们传递一个Widgets列表。如果有人不熟悉Sliver，那么这个人可能最终会传递RenderBox小部件而没有错误。

That's what I'm talking about.

**Comment by zoechi** [comment]
Sorry for missing the point. I got it :D
