### ISSUE TITLE
android licencing and gradle issue 

### ISSUE THREAD

**Issue by behradkhadem** [flutter/flutter#26909]
hello. I'm new to flutter and there is something wrong with initilizing the hello_world app and I can't figure it out. I'm using genymotion as Amulator and got Android studio 3.1.2 and gradle 5.1 installed and ready (and use VSCODE as IDE on windows 10) but when I run` flutter run` it shows this in the output. 
 
```
Launching lib/main.dart on Samsung Galaxy S7, 6 0 0, API 23, 1440x2560 in debug mode...
Initializing gradle...                                       2.0s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\gradlew.bat" exited abnormally:

> Configure project :app
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\BEHRAD\AppData\Local\Android\Sdk\licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to install the following Android SDK packages as some licences have not been accepted.
        build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
     Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

     Using Android SDK: C:\Users\BEHRAD\AppData\Local\Android\Sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
```

what is the problem and how can I fix this thing?

**Comment by Hixie** [comment]
I can reproduce this locally. Running the examples fails. It used to pass. I don't think I've changed anything locally.

cc @dnfield

**Comment by dnfield** [comment]
Actually, this might be due to something we did - we've updated the `compileSdkVersion` and the `targetSdkVersion` to 28.  

https://github.com/flutter/flutter/pull/26798

and 

https://github.com/flutter/flutter/pull/26790

**Comment by jason-simmons** [comment]
We upgraded to `compileSdkVersion 28` recently:
    https://github.com/flutter/flutter/commit/cf4c903144468372584335f35760b321f1ecc399
    https://github.com/flutter/flutter/commit/f02f4fbed3dc11d61bd747708d33f4e8dc4dd5fe

The Android embedder code does refer to level 28 (Android P) APIs, so we need to use the matching compileSdkVersion in order to support tools like Proguard.

I just created a PR to upgrade our scripts to Android Gradle plugin 3.3.0:
    https://github.com/flutter/flutter/pull/26913

I saw a release note mentioning a feature that lets Gradle auto download missing packages:
    https://developer.android.com/studio/intro/update#download-with-gradle

I'd be curious to try the 3.3.0 plugin on a system that doesn't have SDK version 28 installed and see whether it helps.

**Comment by dnfield** [comment]
I think the ideal solution for this would be to provide some kind of flutter_tools command that would help you to download/upgrade the Android SDK bits you need.  It could just shell out to `sdkmanager`, or perhaps install it for you if need be.

**Comment by RyanRamchandar** [comment]
Could this possibly be related to the `sdkmanager` license issue that recently started happening.

https://issuetracker.google.com/issues/123054726

**Comment by dnfield** [comment]
Quite possible.

**Comment by Hixie** [comment]
As a user I have no idea how to fix this. I downloaded Flutter, ran `flutter create dummy; cd dummy; flutter run` and now I get an incomprehensible Gradle error. It says "accept the SDK license agreements and install the missing components using the Android Studio SDK Manager" but how, as a user, should I have any idea how to do that?

`flutter doctor` doesn't say anything is wrong.
`flutter doctor --android-licenses` says everything is fine.

If I try to run Android Studio, it fails to launch (grey screen on launch).
It I change to a different window manager then run Android Studio, it says it has an update, but that it can't install the update due to irrecoverable errors (it's trying to update Java but Java is in a read-only location).
I can create apps with Android Studio and Gradle seems to work fine there.

I think we have to do a better job of catching this error and guiding our users through fixing it.

**Comment by Hixie** [comment]
(This doesn't seem to affect existing apps, presumably because we didn't update those apps' AndroidManifest.xml files? Are those going to start failing due to having the wrong version of Android targeted?)

**Comment by dnfield** [comment]
I'm not able to reproduce that behavior locally, but I also have installed and accepted the SDK 28/build tools 28 previously.

**Comment by imwillhayes** [comment]
> Have you tried installing SDK 28 and buildtools 28.0.3?
> 
> Unfortunately, I think this is due to an external dependency - not anything we did.
> 
> Try running:
> 
> ```
> C:\Users\BEHRAD\AppData\Local\Android\Sdk\tools\bin\sdkmanager.bat "platforms;android-28" "build-tools;28.0.3"
> ```
> Accept the licenses as request and re-run Flutter.
thanks ！ you save my life

**Comment by dnfield** [comment]
I'm glad that worked - I'm going to hold this open to make sure @Hixie is satisifed with this resolution.

One option that might make sense here is for us to automate this process in the tooling.

**Comment by dnfield** [comment]
For now created a patch that will at least print these instructions when Flutter doctor runs and you don't have SDK 28/BuildTools 28.0.3

**Comment by Hixie** [comment]
That seems like a great solution.
