### ISSUE TITLE
default script code for "zh" should be "Hant", not "Hans"

### ISSUE THREAD

**Issue by seventhmoon** [flutter/flutter#26941]
in [localizations_utils.dart](https://github.com/flutter/flutter/blob/aab92447912f0ead302b043a3e30a1c8d467b145/dev/tools/localizations_utils.dart), the default script code for "zh" is "Hans".

However, in Chinese Language, Traditional Chinese "Hant" is the main set. ["Hans" is a override for around 2000 Character in the main set](https://en.wikipedia.org/wiki/Simplified_Chinese_characters) and is only used in a few countries (although with large population size).

From academic and system point of view, the default script code here for "zh" should be "Hant", not "Hans".

>     /// Adds scriptCodes to locales where we are able to assume it to provide
>     /// finer granularity when resolving locales.
>     ///
>     /// The basis of the assumptions here are based off of known usage of scripts
>     /// across various countries. For example, we know Taiwan uses traditional (Hant)
>     /// script, so it is safe to apply (Hant) to Taiwanese languages.
>     if (assume && scriptCode == null) {
>       switch (languageCode) {
>         case 'zh': {
>           if (countryCode == null) {
>             scriptCode = 'Hans';
>           }
>           switch (countryCode) {
>             case 'CN':
>             case 'SG':
>               scriptCode = 'Hans';
>               break;
>             case 'TW':
>             case 'HK':
>             case 'MO':
>               scriptCode = 'Hant';
>               break;
>           }
>           break;
>         }
>         case 'sr': {
>           if (countryCode == null) {
>             scriptCode = 'Cyrl';
>           }
>           break;
>         }
>       }

**Comment by GaryQian** [comment]
The general guidelines Flutter tries to follow in cases like this are to attempt to best match the precedent set by the platforms we run on such as Android and iOS. Since Flutter attempts to provide a native-like experience for users and developers, we believe that developers would expect Flutter to perform the same localization as the platform itself, which would also be in line with the principle of least surprise as Android and iOS have stable and accepted localization strategies.

In this specific case regarding Chinese without a country, Android defaults to simplified Chinese. Android uses a truncation based algorithm to achieve this. on iOS, users specify language and script together, and it uses a proprietary algorithm that seems to provide similar results to Android when a non-standard language-country pair (eg, `zh_FR`) is specified.

From the user's perspective, the vast majority of users do not care about the historical or linguistic basis of the languages they use, but would notice if the incorrect language is shown. Often times, a mistake here renders the app completely unusable. In order to avoid complete breakage for a large number (in this case, a vast majority) of users, linguistic authenticity may ultimately be required to be sacrificed.

**Comment by kangwang1988** [comment]
Based on comments by @GaryQian , Close this issue now.

@seventhmoon 
Feel free to comment below.

**Comment by seventhmoon** [comment]
> In this specific case regarding Chinese without a country, Android defaults to simplified Chinese. Android uses a truncation based algorithm to achieve this.

Would you lead me to the document / source code of this? I'll follow up submitting a feature request and hope to have it update in the next next release.

(Understand the change will affect large population. But it is also painful to developers doing i18n. Especially to those publishing their app internationally, but don't have much knowledge about Chinese.
i.e. number of user affected vs number of region affected)

**Comment by GaryQian** [comment]
The basic algorithm is explained here: https://developer.android.com/guide/topics/resources/multilingual-support. The actual order it resolves in is based on the order the languages are listed.

Keep in mind that the cases where `zh` is provided without a country or script code are exceptionally rare and would require explicit developer manipulation of the locale to strip away the country or script data to be encountered. Almost all user-accessible ways to manipulate locale will include at least one of country or script.
