### ISSUE TITLE
DropdownButton should have a disabled option

### ISSUE THREAD

**Issue by McRaeAlex** [flutter/flutter#27009]
I have just started using flutter the last couple of days and I am currently using the DropDownButton. From the documentation when onChanged or items is null the drop down will be disabled. I believe this is a poor choice as it would be more simple and intuitive to have a optional property which states clearly whether or not the DropDownButton is disabled.

Thank you for your time.

**Comment by zoechi** [comment]
I don't think this will be changed. It's the same in all widgets that can be disabled.

I haven't seen it mentioned in the docs so I'll make this a docs issue.

**Comment by HansMuller** [comment]
It is mentioned in the constructor and in the disabledHint doc, but not for onChanged or in the class docs. Will update.

**Comment by alyyasser** [comment]
it's even weirder in `DropdownButtonFormField`, when `onChanged` in `DropdownButtonFormField` set to `null`, it didn't disable the `DropdownButton`, because the `onChanged` in wrapped `DropdownButton` inside `DropdownButtonFormField` is set to `_DropdownButtonFormFieldState.didChange` which is just a wrapper (with null check) for `DropdownButtonFormField.onChanged`.

**Comment by nishtahir** [comment]
It looks like this is still an issue. I don't think setting the items to `null` is a completely viable solution considering that it prevents you from displaying a selected option while the field is inactive.

**Comment by nishtahir** [comment]
It looks like this is still an issue. I can confirm the behavior that @alyyasser described. I don't think setting the items to null is a completely viable solution considering that it prevents you from displaying a selected option while the field is inactive.

@HansMuller Have you got any feedback on how this is supposed to work?

**Comment by Laban1** [comment]
I too am having a problem with this.  

**@zoechi / @HansMuller**:  how can I disable a DropDownButtonFormField and still display its value?  

Thanks.

_Ps. I really think having an "enabled" property or similar that clearly communicates what it does would be very beneficial, both for this widget and others._

**Comment by dfmiller** [comment]
> I don't think this will be changed. It's the same in all widgets that can be disabled.

Not true for TextFields: https://api.flutter.dev/flutter/material/TextField/enabled.html

**Comment by dfmiller** [comment]
In order to disable the DropdownButton I had to filter the list of options to only the already selected one.  Not a pretty work-around.

**Comment by Laban1** [comment]
What I did was to create a custom widget (with an enabled property), which uses a TextFormField instead of a DropdownButton when disabled.  Works, but really kludgy!

Note: just because many other widgets also are using this strange, non-intuitive way of setting items to null instead of having an enabled property is not a good reason to continue doing so (especially when it does not even work properly for the DropDownButton).  

Leaving the existing way in place and also adding an enabled property would solve the issue w/o breaking existing implementations.

**Comment by emersonsiega** [comment]
These kind of control give a horrible experience to the developers. 
It must be improved.

**Comment by brandonWARKNAT** [comment]
I believe this issue should be reopened as this control is a MUST for any framework.

**Comment by the-deadshot** [comment]
> I too am having a problem with this.
> 
> **@zoechi / @HansMuller**: how can I disable a DropDownButtonFormField and still display its value?
> 
> Thanks.
> 
> _Ps. I really think having an "enabled" property or similar that clearly communicates what it does would be very beneficial, both for this widget and others._

you can achieve this thing by the workaround. If you want to show a value in disabling state 
show your selected value in **hint** as shown below

DropdownButton<String>(
              hint: Text(genderHint),
)

**Comment by chitgoks** [comment]
@the-deadshot  is correct.
