### ISSUE TITLE
How does the flutter call the system installation apk file

### ISSUE THREAD

**Issue by boot-vue** [flutter/flutter#27066]
flutter app download one apk file by http get  and put the apk file in the application directory, now , how dows the flutter let it start install automatically?  

this is important, after build app release,  in future I  release latest version apk, the old version need download the latest apk and install , I don't know how to  did it by android directlly, could  me  handle it with flutter only?

**Comment by kangwang1988** [comment]
@boot-vue 
The short answer is: You can't do it flutter only.
It's a platform specific feature, you need to do it in android side:
See: https://stackoverflow.com/questions/4967669/android-install-apk-programmatically
If you want to call it from the flutter side, you need a plugin(you can develop it or reuse a third party one), see: https://flutter.io/docs/development/packages-and-plugins/developing-packages

**Comment by pY4x3g** [comment]
because this here is one of the first hits by google I give an answer for other people who will land here (I think the other solutions are outdated):

Use the package open_file, it supports apk files. The code may look something like this:

`var directory = await getApplicationDocumentsDirectory();
OpenFile.open("${directory.path}/yourNameOfYour.apk");`

and add this to your AndroidManifest:
` <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />`

This will open the install process from android and you are able to update the app.
