### ISSUE TITLE
Unclear why "didChangeDepdenencies()" is called

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#27100]
Related issues:

* https://github.com/flutter/flutter/issues/18774
* https://github.com/flutter/flutter/issues/12992
* https://github.com/flutter/flutter/issues/16218

I am also running into this on a hobby app. It would be nice to be able to either call:

* `this.debugWhyDidChangeDepdencjes() => Set<Object>`

... or have it filled in as a diagnostic property, obviously in debug mode. Thanks!

**Comment by rrousselGit** [comment]
<Technically, this issue can be closed>

Besides that, I think there's a need to document the _when_ and _why we need it_ too. 

____ 


I myself have quite a few doubts about `didChangeDependencies`. 


According to the documentation, it should be used for expensive work that shouldn't be done on every build call. But the way it works now seems to indicate the opposite.

Consider a `Foo` class that do expensive stuff inside its `didChangeDependencies` – where `Foo` depends on the `InheritedWidget` named `Provider`.

Then consider this test scenario:

```dart
testWidgets('foo', (tester) async {
  await tester.pumpWidget(Provider.value(
    value: 'hello',
    child: Foo(),
  ));

  await tester.pumpWidget(Provider.value(
    value: 'world',
    // `Foo` is removed from the tree
    child: Container(),
  ));
});
```

In this example, `didChangeDependencies` will be called _twice_. But the second call barely makes sense, since `Foo` will be unmounted.

Due to this behavior, it sounds unusual to recommend using `didChangeDendencies` over `build` for network requests – since doing the request there doesn't guarantee that we actually want to do one.


It would be actually safer to do that instead:

```dart
class Foo extends StatefulWidget {
  @override
  _FooState createState() => _FooState();
}

class _FooState extends State<Foo> {
  bool _didChangeDependencies;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _didChangeDependencies = true;
  }

  @override
  Widget build(BuildContext context) {
    if (_didChangeDependencies) {
      _didChangeDependencies = false;
      // actual didChangeDependencies
    }

    return Container();
  }
}
```

**Comment by matanlurey** [comment]
Thanks! I used the new field successfully today and I think we can close this issue! Woohoo!
