### ISSUE TITLE
No Gradient Color Option for AppBar

### ISSUE THREAD

**Issue by srujalsk** [flutter/flutter#27155]
### Steps to reproduce
There is no option of using gradient colors decoration in AppBar Widget.

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.30.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by OsaXma** [comment]
I don't think that's possible to do since backgroundColor is a Color type. Alternatively, you can build your own AppBar as shown in the first answer here: 

 [How to add gradient color in AppBar in flutter](https://stackoverflow.com/questions/50412484/how-to-add-gradient-color-in-appbar-in-flutter).

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
