### ISSUE TITLE
Expose AppLifecycleState getter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2716]
We expose a change callback for this value but don't expose a getter, so there's no way to tell at app startup if we're paused or not.

**Comment by alanrussian** [comment]
Is this fixed via https://docs.flutter.io/flutter/scheduler/SchedulerBinding/lifecycleState.html ?

cc/ @dguralnick who told me that value may sometimes be null when the application starts until the lifecycle state is changed.

**Comment by dguralnick** [comment]
I just verified the first message sent over the ['flutter/lifecycle'](https://github.com/flutter/flutter/blob/eda03e2586b186ffcf8ea2d4424232710dbb7c81/packages/flutter/lib/src/services/system_channels.dart#L186-L189) system channel is not received on the dart side in a minimal Android app (did not test for iOS).

Tested this by adding a print statements in [SchedulerBinding.hadnleAppLifecycleStateChanged](https://github.com/flutter/flutter/blob/dc36195cb3fc2c8fc8663fadd538db8e400be34e/packages/flutter/lib/src/scheduler/binding.dart#L238) and the various [FlutterView callbacks](https://github.com/flutter/engine/blob/dd791f36aca8fc6f13d6e2fa60f20d4ebea89825/shell/platform/android/io/flutter/view/FlutterView.java#L241-L259) for view lifecycle events.

It seems like an ACK should be sent across these channels from Dart -> Native before they're used to communicate anything from Native -> Dart, no?

**Comment by dguralnick** [comment]
This pull request should fix the issue w/ onStart() not being called:
https://github.com/flutter/engine/pull/6719

**Comment by Hixie** [comment]
cc @GaryQian

**Comment by dguralnick** [comment]
The pull request flutter/engine#6719 only addresses the missing onStart() method call.

Has anyone been able to look into the dropped method channel call from Native -> Dart on app startup? See the last paragraph in https://github.com/flutter/flutter/issues/2716#issuecomment-434898080

**Comment by Hixie** [comment]
We don't buffer messages on the channels, so I'm not surprised we don't see the first message. That's why this bug was filed to expose a getter.

**Comment by GaryQian** [comment]
A few ways to approach this were discussed.

- An async getter that queries the platform every time could be provided, however, this could not be used immediately at startup since it is async.
- A buffer/cache of messages can be kept per platform in order to keep and resend messages when the dart is ready.

If the goal is to have the state at startup before anything is rendered, then I can look into building a synchronous way to obtain this data.

The exact implementation will depend on what is desired, so I would like to see if people have specific use-cases for this.

**Comment by dguralnick** [comment]
Thanks for looking at this, Gary! Will be very helpful for proper latency instrumentation of our app.

We definitely need to know the state on app startup - so a sync getter would be a safe way to ensure the problem is addressed. I think a buffer could also make sense, but I worry there could be a race where the value is set incorrectly the first time we try to access it.

IIRC the problem manifested as WidgetsBinding.instance.lifecycleState being set incorrectly - so you could use the sync getter to make sure that was corrected.

**Comment by GaryQian** [comment]
Since the platform and main dart isolate are not started synchronously, would the following behavior be appropriate?

- Both started and ready: We query the platform and directly return the state.
- Dart started, platform still initializing: Since this is a synchronous call, we cannot wait for the platform to finish, and return a new state "initializing"
- Dart still initializing, platform started: It shouldn't be possible to call dart-side code in this state.
- Both still initializing: It shouldn't be possible to call dart-side code in this state.

The benefit of this is that you can always get a definitive answer to the question of "What lifecycle state is the platform in right now" at the current moment in time even if the answer is "the platform is not ready yet".

**Comment by dguralnick** [comment]
Sounds appropriate to me. As long as we get some known initial state and the subsequent events are fired properly via the WidgetsBindingObserver I should be in good shape.

**Comment by GaryQian** [comment]
I am temporarily putting this on a *brief* hold as the platform messaging channel API on the platform-side is currently a bit fluid and am blocked by another bug. In the meantime, I will throw together a doc to better flesh out what is needed and how to ensure the lifecycle state is always successfully passed to dart at startup.

The issues mentioned above should stabilize soon.

**Comment by GaryQian** [comment]
So after looking through our architecture, I don't think we are able to fully avoid all race-conditions in order to deliver and have the AppLifecycleState available for synchronous getting at dart startup. No matter what, we are vulnerable to the state changing in the time it takes for the system message channels to pass the message.

We discussed a few options, and it seems the best we can do without a overhaul of the architecture would be to make a non-public async query to the platform to send the latest cached state through the existing channels at startup. The `lifecycleState` variable would still be null on very initial startup, but would rapidly populate as soon as the data is available and sent.

This method has a few drawbacks:
- The query call must be async and the `lifecycleState` getter will be null at first
- Since it is async, there is the possibility that the state could change and cause slight inconsistencies.

We are also hesitant to expose a direct async query method as this would result in having two separate APIs for the same task. We prefer to keep the query method private and only use it as necessary at startup in order to obtain a more consistent API. Once the app has started, the sync call to the `lifecycleState` getter should be equivalent if not better than trying to use an async query.

@dguralnick could you verify if this would be sufficient for your needs? You would not have the state immediately, but it should be able to come after a short latency. It would also be helpful to better understand the particular use cases in order to optimize certain aspects such as latency or accuracy.

**Comment by dguralnick** [comment]
I think if you can guarantee our lifecycle state listener will receive an event with some state as soon as it's available (as opposed to the first state change vent being dropped over the uninitialized method channel as is happening today), we'll be OK.
