### ISSUE TITLE
Handle 422 response error

### ISSUE THREAD

**Issue by maheshbhattaraai** [flutter/flutter#27243]
> How to handle error 422( unprocessable entity) while submit Form Using Post Method to API endpoint.
Thank You

**Comment by zoechi** [comment]
That means you are sending something to the server that the server can not process.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

> The HyperText Transfer Protocol (HTTP) 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.

You need either fix the server or fix the request you make so that the server can process it.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
