### ISSUE TITLE
Support different display fps and input refresh rates

### ISSUE THREAD

**Issue by xster** [flutter/flutter#27259]
Such as 60Hz output and 120Hz input on iPads

**Comment by jacob314** [comment]
Please let me know when this is fixed so we can make debugging tools properly reflect the target refresh rate.

**Comment by chinmaygarde** [comment]
We already support 120Hz on devices with ProMotion displays. We get this out of the box because we don't set a [-[CADisplayLink preferredFramesPerSecond]](https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond) on the vsync waiter implementation on iOS. If there is no preference, iOS sets this to the maximum supported display refresh rate. To verify, I captured this trace on an iPad with a ProMotion display. As marked, the frame interval is ~8.3ms (1/120).

<img width="842" alt="Screen Shot 2019-08-14 at 12 51 50 PM" src="https://user-images.githubusercontent.com/44085/63051833-d20bc480-be92-11e9-8522-5b581ee58314.png">
