### ISSUE TITLE
Plugin: Notifications API

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#2731]
Provide an api to access to http://developer.android.com/guide/topics/ui/notifiers/notifications.html and/or the iOS notifications.

**Comment by eseidelGoogle** [comment]
Is this the same as https://github.com/flutter/flutter/issues/201 ?  @collinjackson is this covered by our gmm support?

**Comment by collinjackson** [comment]
I don't think this is covered, this is more about interacting directly with the Android notifications API. I imagine that devs are going to want to write a bit of Java code to do this unless are Dart wrappers are really good.

**Comment by Hixie** [comment]
@mit-mit You marked this as a milestone 3 issue, can you clarify your plans here?

**Comment by Hixie** [comment]
Moving to far future since this doesn't align with our current priorities.

**Comment by sgon00** [comment]
It's unbelievable this is moving to far future. How can a user get a notification without this plugin when the app is in background?  Please don't tell me to use firebase again. Firebase service is blocked in many countries. Firebase support should never be a priority to me. and yeah, somebody may suggest me to write a plugin by myself. But the reason why I use flutter is because I don't want to write any java/kotlin/swift/objective-c codes. Sorry about my words, Thank the flutter team very much for the hard work. Moving to far future means there is no hope for me to have a simple notification support in flutter when the app is in background.

**Comment by mit-mit** [comment]
This issue is currently tagged 'self service', but it's probably not clear what we mean by that: The Flutter core team is currently 100% focused on resolving our last few overall blockers. These are things that due to architectural or complexity reasons are unlikely to happen unless we do them, for example the core plugin framework itself. We understand that it's painful when the exact feature you need isn't there already, but at the same time we need to prioritize the time we have. 

In the case of the present plugin, we feel this is not blocked on anything missing in our framework, and of manageable complexity, so it's not entirely unreasonable to have a community sourced plugin fill the need (hence the self service tag). So if someone is interested in working on this, that would be very much appreciated, and we would gladly help with input, reviews, etc.

**Comment by csbenjamin** [comment]
I am building a music player and I would like to show a notification with a player control, so the user can know where the sound is coming from and easily stop the sound if he/she wants to

**Comment by pakivika** [comment]
My use case is that I'd like to schedule an alarm 15min in the future. Alarm should trigger even when the app is not in the foreground or if the screen is blank.

**Comment by mitchhymel** [comment]
@pakivika Have you tried the [android_alarm_manager](https://pub.dartlang.org/packages/android_alarm_manager) plugin?

I built a basic notification plugin for an app I'm working on. Find it [here](https://github.com/mitchhymel/local_notifications). The plugin isn't published, because I wouldn't recommend using the plugin as it is definitely not well tested, but I think it could be used as an example or proof of concept for someone to build further. 

The reasons I don't recommend using it are:
1) It's not well tested.
2) I can't promise I'll have time to keep working on it to fully flesh it out.
3) Currently only Android is supported, and so the API closely matches the Android notification APIs.
4) Media style notifications are not supported yet.

**Comment by MaikuB** [comment]
I've tried creating a plugin that targets both Android and iOS for displaying basic notifications that also allows for them to scheduled. It can be found at https://pub.dartlang.org/packages/flutter_local_notifications. There's an example for scheduling notifications as well in my GitHub repo for it. Perhaps see if it'll work for you.

**Comment by MaikuB** [comment]
@mit-mit what's the best way to get in touch with your team to get said help :)

I've raised two issues (#16636 and #16662) but got questions on what's possible with the framework to handle certain scenarios

**Comment by eseidelGoogle** [comment]
In our recent user survey results, this was the 4th most asked for item.  @mravn-google @collinjackson are there some easy wins we could get here?

**Comment by mravn-google** [comment]
@MaikuB has contributed https://pub.dartlang.org/packages/flutter_local_notifications. If that plugin does not represent a win, I'd like to understand why so we can help out (e.g. with resolving #16662).

**Comment by MaikuB** [comment]
@mravn-google run into a blocker in supporting notification actions that I've also asked @mit-mit about on my repository (tracked as an issue [here](https://github.com/MaikuB/flutter_local_notifications/issues/17) since I was asked about use cases around notification actions. It seems like there's a limitation in what is currently supported for headless Dart code (see #3671 where I've also brought this up). Execution of headless Dart code is needed to support scenarios when notification actions can execute code even when the application is terminated and shouldn't launch the activity (e.g. when snoozing an alarm). Currently this is available on Android via the runFromBundle method in the FlutterNativeView class, except it doesn't support passing parameters in. There was an issue tracking this before at #15798 but it's now considered closed. Though I think the ideal scenario would be enabling a platform channel's method call handler to run even when the app is terminated though not sure how doable it is. #15798 talks about paving the way for having platform channels run in the background, which I'm guessing is referring to the same thing

**Comment by mit-mit** [comment]
cc @bkonyi can you help with the issues @MaikuB describes above?

**Comment by bkonyi** [comment]
I'm currently working on getting background execution working on iOS, but I'll probably be making some changes to how things work on Android as well. Long story short, I'm working on getting parameter passing to callbacks invoked by a background isolate working. I don't have an ETA at this point since I'm still doing some exploratory work, but this is my main focus at the moment.

**Comment by MaikuB** [comment]
cool, thanks for the update as it's good to know it's being worked :)

**Comment by eseidelGoogle** [comment]
FYI @cbracken @bparrishMines This is our highest-requested "plugin" related feature.  Comes up regularly in user studies.  My understanding of this bug is there isn't a lot of work to do here, the APIs sets are rather small.  What's being requested (AFAICT) is an "official" plugin to cover the local notification cases (https://developer.android.com/guide/topics/ui/notifiers/notifications) other than what https://github.com/flutter/plugins/tree/master/packages/firebase_messaging covers today.

**Comment by MaikuB** [comment]
Something I've been encountering is that there are conflicts when a local notification plugin (as such as mine) registers itself as a UNUserNotificationCenterDelegate and is used alongside with Firebase. Is there a way around that? Have tried method swizzling but that didn't seem to work (I may well be missing something). Is this something the engine can be provide given there are similar mechanisms already e.g. https://docs.flutter.io/objcdoc/Protocols/FlutterPluginRegistrar.html#/c:objc(pl)FlutterPluginRegistrar(im)addMethodCallDelegate:channel:

**Comment by eseidelGoogle** [comment]
@MaikuB Seems worth filing a separate bug about the specific failure you're seeing/goal you're tryin to achieve.  I worry your comment on this one might get lost in the noise. :(

**Comment by MaikuB** [comment]
Good point, I'll do so thanks.

**Comment by MohdLucky** [comment]
Hey, 
please help me in reminder app in flutter ios

**Comment by MohdLucky** [comment]
> FYI @cbracken @bparrishMines This is our highest-requested (and unassigned/unstaffed) "plugin" related feature. Comes up regularly in user studies. My understanding of this bug is there isn't a lot of work to do here, the APIs sets are rather small. What's being requested (AFAICT) is an "official" plugin to cover the local notification cases (https://developer.android.com/guide/topics/ui/notifiers/notifications) other than what https://github.com/flutter/plugins/tree/master/packages/firebase_messaging covers today.

please help me in reminder app in flutter IOS

**Comment by sgon00** [comment]
Hi, sorry to interrupt. I saw `Hixie removed their assignment` and `Hixie removed this from the June 2019 milestone` from this issue. So what is the plan now? I heard flutter team would support this soon.

**Comment by awulkan** [comment]
What's the status on this issue? It appears to be a heavily requested feature, but it doesn't seem like anyone is working on an official plugin for this. Or am I looking in the wrong places?

**Comment by MaikuB** [comment]
@awulkan my understanding is some of the Flutter team have used my plugin that you've come across and have been helping to look into related issues I've raised e.g. comparability with `firebase_messaging`. On a general note, if the community has worked on something, I believe the team tries to support that effort where possible, which would allow the team to focus their efforts elsewhere and avoid fragmenting the community

**Comment by awulkan** [comment]
@MaikuB Definitely, and I didn't mean to sound like your plugin wasn't good enough. It's just that this is such a basic and crucial part of applications that I think most developers want some "insurance" that it's prioritized by the Flutter team, and that it won't stop working because you decide to stop developing. It could potentially break a lot of applications.

Thanks for your, and all other contributors, work so far.

**Comment by MaikuB** [comment]
> Definitely, and I didn't mean to sound like your plugin wasn't good enough.

All good and I didn't interpret it as such. Just sharing my views based on my experience and interactions with the Flutter team. 

> It's just that this is such a basic and crucial part of applications that I think most developers want some "insurance" that it's prioritized by the Flutter team, and that it won't stop working because you for some reason stopped developing the plugin. It could potentially break a lot of applications.

Understood though it's been common in other ecosystems to for plugins to be done by the community. With them being open sourced, others can contribute to help out. Should maintainers stop development and it's something that's widely used, chances are someone else will maintain a fork or ownership will be transferred

> In the future I assume it would have to be integrated with Mac, Windows and the web as well to send notifications. That's a lot of integrations to maintain.

The Flutter team has a documented proposal for plugins that allow for endorsed platform-specific implementations of a plugin where one of the main benefits is to address this problem. From what I briefly saw for web, the API surface is small. For MacOS, the APIs appear to be the same for iOS. Most of my dev experience is with C# and .NET so should have Windows covered if and when it comes time to that though contributions are welcome :)

**Comment by stuartmorgan** [comment]
We'll leave this open to continue to track interest, but to set expectations: we currently don't have any plans to take on this significant new plugin work, and encourage people to use the existing, popular plugins from the community.

**Comment by devxpy** [comment]
> Good point, I'll do so thanks.

Just curious if you followed up on this :)

Would love to be able to implement background notification handlers in flutter code

**Comment by stuartmorgan** [comment]
> We'll leave this open to continue to track interest, but to set expectations: we currently don't have any plans to take on this significant new plugin work, and encourage people to use the various existing, popular plugins from the community.

Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
