### ISSUE TITLE
Remove @protected from ChangeNotifier.notifyListeners

### ISSUE THREAD

**Issue by dcov** [flutter/flutter#27448]
I use `ChangeNotifier` extensively throughout my app, and there are some cases in which I use it as a standalone object which leads to the linter complaining.

So, is there a reason `ChangeNotifier` was only meant to be extended/mixed-in? Or can it be updated to allow for standalone usage. It's not abstract so it can already be used as such, like in my case. 

It would only be a matter of removing the `@protected` label and marking it as such in subclasses where it should be protected. It can also be hidden behind `Listenable` in cases where the receiver shouldn't know about `notifyListeners`.

Is this possible? Or is there a reason for making it protected by default?

**Comment by zoechi** [comment]
@Hixie ?

**Comment by creativecreatorormaybenot** [comment]
How do we suppress / ignore these warnings?

**Comment by Hixie** [comment]
You can make a subclass that exposes a method that calls this one.

It's protected because generally speaking it's a bad idea for the consumer of the API to be able to trigger the notifications. The notifications typically "come from within".

**Comment by creativecreatorormaybenot** [comment]
@Hixie Obviously, but that is cumbersome. I do not quite understand *why* it is "a bad idea for the consumer of the API to be able to trigger the notifications".

I am using `ValueNotifier`'s and need to call `notifyListeners` manually because changes to arrays do not fire that event. Thus, I want to call it manually in a specific case and would like to get rid of the warning. Is there no other way to suppress warnings?

Looking at [this issue](https://github.com/dart-lang/sdk/issues/25685), it seems like I should be able to ignore specific warnings, but I cannot figure out how to do it in this specific case.

**Comment by dcov** [comment]
> It's protected because generally speaking it's a bad idea for the consumer of the API to be able to trigger the notifications. The notifications typically "come from within".

Can't it be exposed as `Listenable` to consumers? I agree that with cases like `ValueNotifier` it might make sense to hide it since it's implied that it should only notify when `value` changes. With a regular `ChangeNotifier` though, shouldn't the owner of it be able to call `notifyListeners` since it knows that it exists hence why it was chosen?

I could subclass it easily, but then I'd have to rewrite it for every project or make a package. It's not too much work, but I'd rather avoid it, especially since it wouldn't be introducing new functionality and is only to avoid a linting error.

I understand though if there are reasons for making it `@protected`, just thought I'd ask first before going ahead with subclassing it.

**Comment by creativecreatorormaybenot** [comment]
Adding to that, why do you not leave it up to the consumer in general? What is the benefit of not enabling this use case? I do not see any risks or limitations.

**Comment by Hixie** [comment]
It's not _that_ cumbersome:

```
class OpenNotifier extends ChangeNotifier {
  void notify() => notifyListeners();
}
```

It's a bad idea for consumers to trigger notifications because it implies a mixed-up ownership and responsibilities model. To minimize bugs, architecture should have data flow in a clearly-defined direction. If the code listening is also sending notifications, then it's an indication that the direction isn't clearly defined.

We could refactor all this code to more clearly have Listenable be the interface everyone exposes, and ChangeNotifier be something that you can use; maybe we could call it Listenable and ListenableController, in much the same way that we have Animation and AnimationController. In practice, ChangeNotifier came first, which is why we have the design we have now. (I've added a note to https://github.com/flutter/flutter/issues/24722.)

**Comment by dcov** [comment]
> It's a bad idea for consumers to trigger notifications because it implies a mixed-up ownership and responsibilities model. To minimize bugs, architecture should have data flow in a clearly-defined direction. If the code listening is also sending notifications, then it's an indication that the direction isn't clearly defined.

Yup, agreed.

> We could refactor all this code to more clearly have Listenable be the interface everyone exposes, and ChangeNotifier be something that you can use; maybe we could call it Listenable and ListenableController, in much the same way that we have Animation and AnimationController. In practice, ChangeNotifier came first, which is why we have the design we have now. (I've added a note to #24722.)

Ok got it, that's all I needed to know :).

@creativecreatorormaybenot I'll make a package that exposes `notifyListeners` through `notify` as was suggested if you're interested. I'll probably call it `notifiers` or something.

**Comment by creativecreatorormaybenot** [comment]
> I'll make a package that exposes `notifyListeners` through `notify` as was suggested if you're interested. I'll probably call it `notifiers` or something.

Importing a package is not better than writing a simple class, I feel like.

**Comment by esDotDev** [comment]
Creating the little subclass is a nice workaround(going to use it right now!), but it does feel like this should be enabled by default.

The use case is not really for consumers triggering notifications, it's for when we're using complex objects as values, and there's no efficient way of triggering the event. 
```
class MyComplexModel {
    ValueNotifier<List<int>> listNotifierer;

    addItem(int item){
       listNotifierer.value.add(value);
       listNotifierer.notifyListeners();
    }
}
```
The alternative is to clone the list/object and set it using `.value=`, but that's extremely inefficient.

**Comment by Hixie** [comment]
The reason it's protected is that we want to avoid people doing:
```dart
MyComplexModel model = source.model; // from somewhere else, not a model we own
model.listNotifier.notifyListeners(); // oops, we just triggered all the consumers of that model
```

**Comment by creativecreatorormaybenot** [comment]
@esDotDev I think your snippet should look like this:

```dart
class OpenValueNotifier<T> extends ValueNotifier<T> {
  OpenValueNotifier(value) : super(value);

  void notify() => notifyListeners();
}
```

Otherwise, the generic type is unused.

**Comment by esDotDev** [comment]
Thanks creativecreatorormaybenot, I guess the Dart compiler was doing the magic for me so I didn't notice. 

I must confess I don't really understand the problem use case, that seems like pretty explicit programmer intent there. 

I just wonder, what is the expected method to notify listeners where our value is a map, list or other complex object? Rebuild/copy the thing each time? That could be extremely inefficient with large datasets, not to mention introduces needless boilerplate.

It's unfortunate cause it kinda stunts what otherwise would be a perfect general purpose multi-listener event dispatcher. Streams work good for this purpose, but have their own boilerplate.
