### ISSUE TITLE
visibility

### ISSUE THREAD

**Issue by lqbach** [flutter/flutter#27466]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by kangwang1988** [comment]
This issue doesn't provide enough information to investigate.
If you are still seeing this please create a new issue with
  •  the output of flutter doctor -v
  •  a minimal runnable reproduction
  •  as a single file so that we can just copy your code into lib/main.dart of a new project and run to reproduce
  •  the complete and exact error output.
