### ISSUE TITLE
multiple audioplayer played in list view  at a time .How to make them separately. 

### ISSUE THREAD

**Issue by mirmahfuz99** [flutter/flutter#27489]
## Steps to Reproduce

1.when one play btn is active from list view i want to stop clicking another play btn from list view .

```
```

```
```

```
```
![51246610_2294430937452400_1412937888403816448_n](https://user-images.githubusercontent.com/20367660/52203105-86041580-289a-11e9-8b41-1f2f1ed33118.png)

**Comment by Kartik1607** [comment]
Please leave some minimal code which you are using right now.

**Comment by Kartik1607** [comment]
You need to rethink how to architect your flutter app and communicate between widgets. Currently, each `AudioApp class` have a different audio player. How should one audio player know if some other audio player is already playing an audio? How about instead of creating an audio player in each widget, you simply share a simple audio player using and pass it to child widgets (or use an [inherited widget](https://docs.flutter.io/flutter/widgets/InheritedWidget-class.html)). If application state  is getting more complex, how about using [BLoC pattern](https://medium.com/flutterpub/architecting-your-flutter-project-bd04e144a8f1) or perhaps [Redux](https://blog.novoda.com/introduction-to-redux-in-flutter)

There are many many [different approaches](https://github.com/brianegan/flutter_architecture_samples) you can use to solve this problem. It depends which one you find best.
