### ISSUE TITLE
AppBar text bleeds below Android Task name in task switcher

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2766]
I'm not sure what the Android framework is doing to avoid this.  Presumably our AppBar is a couple pixels off.
![screen](https://cloud.githubusercontent.com/assets/11857803/13862346/db9d7c64-ec4f-11e5-9411-e1b6563a3389.png)

Strangely it looks fine in landscape mode, but not portrait mode?
![screen](https://cloud.githubusercontent.com/assets/11857803/13862351/ebba4140-ec4f-11e5-99b7-d048c536b346.png)

**Comment by HansMuller** [comment]
I've made extensive, soon to be committed, changes to the AppBar class. I'm not seeing this problem. Will recheck upon landing my changes.

**Comment by HansMuller** [comment]
Summary: we could hack around this problem but probably should not. The source of the problem may be that we're not exposing enough information about the layout of Flutter appbars to Android.

Padding the toolbar's Row elements upwards 3 pixels hides the problem in the stocks demo app.

![screen1](https://cloud.githubusercontent.com/assets/1377460/13936476/38c3f002-ef7b-11e5-8e67-42444276ce28.png)

However that's because the app's title doesn't contain any descender characters. To clear the bottom of the "g" in the "Tabs and Scrolling" demo's appbar title requires 8 pixels of padding.  This introduces a somewhat noticeable amount of "white" space above the tab bar:

![screen3](https://cloud.githubusercontent.com/assets/1377460/13936524/830a7762-ef7b-11e5-82ae-a76c002fe6bb.png)

For comparison, here's the original unpadded appbar in the same app:

![screen4](https://cloud.githubusercontent.com/assets/1377460/13936564/c02b4fa4-ef7b-11e5-91e0-8ac2cb33298b.png)

Returning to the stocks example, one more quirk. When another app is paused, the color of the stock's title bar changes, it no longer matches the exposed part of the app:

![screen2](https://cloud.githubusercontent.com/assets/1377460/13936613/1df48d26-ef7c-11e5-86d1-2cab14edfeef.png)

**Comment by eseidelGoogle** [comment]
Do we understand what the Android framework does here that's different from how Flutter's AppBar works?  @jason-simmons @j9brown :)

**Comment by Hixie** [comment]
@eseidelGoogle Punting to m4 since this doesn't fit our current priority list.

**Comment by eseidelGoogle** [comment]
Agreed.  Lets wait until a customer asks for this.  (I'm not even sure this still reproduces.)

**Comment by Hixie** [comment]
Android no longer has that effect as far as I can tell.

**Comment by bradyt** [comment]
@Hixie did you for example check with the oldest Android version that Flutter supports?
