### ISSUE TITLE
Input set prefix problem

### ISSUE THREAD

**Issue by xiaomei991** [flutter/flutter#27871]
Input sets the prefix, can be displayed when the focus is obtained, and displays a blank when the focus is lost. What is the configuration?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
