### ISSUE TITLE
E/FirebaseInstanceId( 5386): Error while delivering the message: ServiceIntent not found.

### ISSUE THREAD

**Issue by or1one** [flutter/flutter#28000]
How to solve this problem? Thank you in advance!

![flutprob](https://user-images.githubusercontent.com/40713074/52859845-3ef20c00-3147-11e9-9583-89c28364c762.jpg)

E/FirebaseInstanceId( 5386): Failed to resolve target intent service, skipping classname enforcement
E/FirebaseInstanceId( 5386): Error while delivering the message: ServiceIntent not found.

**Comment by zoechi** [comment]
How to reproduce?

**Comment by manishkumar-dsi** [comment]
I am also facing the same problem. 
Here are the steps to reproduce:

**Plugin used:**
firebase_messaging 4.0.0+1

**AndroidManifest.xml**
Added following intent-filter under the activity

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```
Under main.dart:
import 'package:firebase_messaging/firebase_messaging.dart';

Then inside main()

```
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  _firebaseMessaging.requestNotificationPermissions();
  _firebaseMessaging.getToken().then((token){
    print(token);
  });

```

Then run the flutter application and push the notification from "Firebase cloud Messaging"

I am not receiving the notification but the error. I hope this will help.

**Comment by gtupak** [comment]
I have the same issue. Does anyone have a fix for this?

**Comment by gtupak** [comment]
@or1one UPDATE 2h30 later, I solved this by simply deleting the build folder and re-launching the app. 😅

**Comment by misaelastorgac** [comment]
THANKS i had the same issue

**Comment by mayurdhurpate** [comment]
Thanks @gtupak! Deleting the build folder and rebuilding the works. 

I think it could be related to upgradation of Android Gradle to solve this bug: #27254 , which occurs when integrating **firebase-messaging** for first time. Upgrading the gradle dependency in the android/build.gradle file: classpath 'com.android.tools.build:gradle:3.3.1' as suggested in the workaround results in the above bug:


`E/FirebaseInstanceId( 5386): Failed to resolve target intent service, skipping classname enforcement
E/FirebaseInstanceId( 5386): Error while delivering the message: ServiceIntent not found.` 

Deleting the build folder and launching the app solves this error too.

**Comment by rachna1812** [comment]
deleting and rebuilding isn't helping in my case

**Comment by rachna1812** [comment]
that is because of the bug.
try forcefully including the requirement.
inside onCreate method add the block of code that include the permissions yo require with your activity name
 if(ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(yourActivity.this, Manifest.permission.ACCESS_COARSE_LOCATION)!= PackageManager.PERMISSION_GRANTED) { ActivityCompat.requestPermissions(yourActivity.this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, LOCATION_REQUEST_CODE);

    }
    else{
        mapFragment.getMapAsync(this);
    }


and inside your onConnected method try adding.
if(ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(yourActivity.this, Manifest.permission.ACCESS_COARSE_LOCATION)!= PackageManager.PERMISSION_GRANTED) { ActivityCompat.requestPermissions(youractivity.this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION},LOCATION_REQUEST_CODE );

    }

**Comment by zanul11** [comment]
> @or1one UPDATE 2h30 later, I solved this by simply deleting the build folder and re-launching the app. 😅

that's worked for me. thanks

**Comment by zeeshan237** [comment]
First u have to check your internet, also u needs to delete the build folder run the flutter clean command after this u have to flutter run, it will solve this issue.
