### ISSUE TITLE
flutter create should let you customize the "com.yourcompany" part of the generated android manifest

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2803]

**Comment by danrubel** [comment]
This is only an issue when code signing. Rather than add more to the `flutter create` command, the `flutter run` command [detects this situation and provides guidance on what needs to be done](https://github.com/flutter/flutter/pull/5913).

**Comment by eseidelGoogle** [comment]
This bug seems about Android and code signing is an ios thing.  I'm not sure if I understand the original bug correctly?

**Comment by danrubel** [comment]
If we force the user to a choose an id during the `flutter create` command, then we have to explain it and they have to spend time understanding the choice. This is an unnecessary barrier to entry. They don't need to make this choice at the time of `flutter create`. IMO it is better to defer the choice until they encounter a situation where they need it.

If we add an option to `flutter create` to specify the id then who will use it? New users will forgo options as they are getting started because they don't understand the choices and expect the defaults to "just work". Experienced users don't need it. My take on this is that we should not complicate the `flutter create` command.
