### ISSUE TITLE
Swipe to pop CupertinoPageRoute takes precedence over HorizontalDragGestureRecognizer 

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#28045]
Detection of swip-right gesture on iOS (`_CupertinoBackGestureDetector`) takes precedence over a `HorizontalDragGestureRecognizer`, making impossible/very hard to drag, for example, a slider that is at zero to the right.

Minimal example:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Page1());
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () => Navigator.of(context).push(CupertinoPageRoute(builder: (context) => Page2())),
          child: Container(width: 40, height: 40, color: Colors.red),
        ),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  @override
  _Page2State createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  double value = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Align(
        alignment: Alignment.topLeft,
        child: Padding(
          padding: EdgeInsets.only(top: 60),
          child: IntrinsicHeight(child: Slider(value: value, onChanged: (x) => setState(() => value = x))),
        ),
      ),
    );
  }
}
```

# Steps to reproduce

- Go to `Page2`
- Drag the slider all the way to the left and release.
- Dragging the slider to the right will now almost always trigger the back transition of the page.

# Possible solution

Giving the `_CupertinoBackGestureDetector`'s `HorizontalDragGestureRecognizer` a custom slop that is larger than other drag-GestureRecognizers (`2 * kTouchSlop` works for the slider example) seems to solve the problem.

Having to possibility to specify a custom slop for `Horizontal/VerticalDragGestureRecognizer`s would also help with another issue I have (a modal route that can be dismissed by swiping down). However, I don't know whether the slop is intentionally hidden.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.2.2-pre.21 at /Users/spkersten/Development/flutter
    • Framework revision 035e0765cc (8 hours ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

**Comment by xster** [comment]
Tangentially related #28170

**Comment by Hixie** [comment]
Making the slop greater introduces flakiness (see my comment in the PR), and also makes the drag gesture feel less responsive (you have to drag further for it to trigger).

I think the right solution here is to either make the gesture add itself after the slider, so that the slider always beats it, or to position the slider so that there's no ambiguity.

**Comment by xster** [comment]
This is indeed an issue though we wouldn't want to actually change the detector for _CupertinoBackGestureDetector. We would also want to solve the general issue of detection order given 2 ancestor-descendent nested group of recognizers of the same type. 

The solution should be to add an enum to recognizers for recognizing before or after its children and potentially changing the default behavior.

**Comment by spkersten** [comment]
@xster For `_CupertinoBackGestureDetector`, it's placed in a stack above the page. That would be replaced with a some kind of listener that would add a hittest entry after hittesting its child (and only when hit at a small stripe at the left)?

**Comment by xster** [comment]
Not sure what you meant by 'in a stack above the page'

![screen shot 2019-03-08 at 11 10 15 am](https://user-images.githubusercontent.com/156888/54050006-fe5c4000-4192-11e9-9cf1-a5a8cd8692c4.png)

If you meant ancestor to the page, then yes, we should likely do something to the effect of adding another enum dimension to RenderProxyBoxWithHitTestBehavior to let it add itself before/after its children.

**Comment by xster** [comment]
@goderbauer I think you're doing this already. Please correct if it this isn't the right bug.

**Comment by goderbauer** [comment]
@xster That screenshot is slightly misleading. @spkersten is correct with his comment about the stack.

![image](https://user-images.githubusercontent.com/1227763/54238833-bf9df100-44d6-11e9-9905-a223939fb938.png)

As can be seen, the CupertinoBackGesture widget is made up of a Stack with two children: child 1 is essential the content of the current PageRoute (that's where the slider lives). child 2 is the pointer Listener, which is in charge of detecting the start of the back gesture. When a pointer hits the screen where the slider and back gesture area overlap, the [default hit testing algorithm](https://master-docs.flutter.io/flutter/rendering/RenderBoxContainerDefaultsMixin/defaultHitTestChildren.html) for Stacks is performed: Stack children are walked in inverse order and in this case the back gesture listener gets first dips on the drag.

**Comment by goderbauer** [comment]
After some more discussion in the team we've come to the conclusion that we shouldn't change the way the back gesture is detected because it will break many common and established patterns. Many apps (e.g. E-Mail apps, news readers, twitter clients, etc) have ListViews where you can swipe over a list tile to see further options (e.g. archive mail, mark news story as read, fav a tweet). On all these screens we also want the back gesture to continue to work as that's how iOS behaves natively. If we would add the back swipe gesture detector after the gesture detectors within the route, this would break.

It's also odd to make the precedence the back gesture takes configurable on the Route because that would tie the route closely to its content. In many cases the creator of a route wouldn't even know that it may contain a widget that needs a different precedence for the back gesture. Furthermore, with this approach you also couldn't create a route where you have a slider that shouldn't trigger the back swipe and list tiles on which the back swipe should be possible.

I believe, this needs to be fixed on the Slider. It is the one that wants to prevent the back gesture from happening if the user swipes on it. However, I also believe that we should not build this behavior into the slider that ships with the framework. Looking at the iOS and Material UI mocks for sliders, they all discourage placing the slider too close to the screen edge. Instead, they encourage people to show some kind of an image at both ends of the slider to indicate the max/min values and give the sliders some padding from the screen edge. I believe that placing the Slider close to the screen edge where it competes with the back swipe is an anti-pattern and Flutter as a framework should not encourage developers to do this by making it easy.

If you absolutely want this behavior - and you may have good reasons that it makes sense in your particular app - I'd suggest implementing your own custom slider (which of course can take inspirations from Flutter's slider). Instead of using a drag gesture detector that competes with the back gesture in the gesture arena, I'd implement a gesture detector for this custom slider that always claims victory in the gesture arena right away beating the competing detector of the back gesture.

**Comment by spkersten** [comment]
Since we already use a custom slider, changing its gesture detector could
actually be a easy solution. I’ll look into it. Thanks for the input.

**Comment by matthew-carroll** [comment]
Based on @goderbauer's comments above, we're going to close this issue.
