### ISSUE TITLE
I want to know about the progress of built-in database support

### ISSUE THREAD

**Issue by luojieerr** [flutter/flutter#28067]
I learned in a recent user survey that you are working hard to implement built-in database access. I want to know when it will be released. I plan to use Flutter to refactor my application, but it relies heavily on the database, I know Database access is currently available through the sqflite plugin, but I am still very much looking forward to the Flutter team's ability to develop built-in database access, thanks!

**Comment by kangwang1988** [comment]
@timsneath Any comment?

**Comment by zoechi** [comment]
What would "built-in database access" even be?

**Comment by dnfield** [comment]
Since you mentione sqflite, I assume you mean access to SQLite.

## For now:

1. There is an issue open to track ability to integrate directly with SQLite as a C/C++ plugin here: https://github.com/flutter/flutter/issues/16231.

That one depends on FFI availability, which is making progress and should have more news in the coming months.

2. You can use the sqflite plugin, which is pretty popular and widely used.

## Going forward:

We have it in our [roadmap](https://github.com/flutter/flutter/wiki/Roadmap#ecosystem) to have a formal recommendation around this.  @timsneath or @hixie may have something to add to this related to that, but it's likely that the support for this will come down to one of the two mentioned above.

Is there anything that you're looking for that you're concerned the sqflite plugin can't handle at this point?

**Comment by luojieerr** [comment]
sqflite works very well，I just think that the local data storage (SQLite) support by Flutter team will be more reliable.

**Comment by zoechi** [comment]
That should be covered by FFI at least it would make it easy for the community to build such a SQLite integration using it. 
So I think this issue is not needed.
