### ISSUE TITLE
Generic TypeDef does not work with custom class

### ISSUE THREAD

**Issue by gagaJay** [flutter/flutter#28072]
## Steps to Reproduce

Maybe this is more a dart specific issue, but since I found this while developing flutter app so I decided to post it here. I have written a small example try to reproduce the issue.  

So basically I want to create a generic class(Test<T, F>) but with some variable(_cellBuilder) has an external typedef type(CellBuilder<F>) outside the class. testA with String assigned runs fine, but testB failed just as the screenshot shows. 

And when I remove \<Product\> from testB, I get a different error.
"type '(Product) => Widget is not a subtype of type (dynamic) => Widget"

Quite confusing. Any help please?

![image](https://user-images.githubusercontent.com/3827781/52910570-35f76b00-32fe-11e9-80a1-118b7179bc88.png)

```
void main() {

  testA<String>(String content) {
    print(content);
  }

  Widget testB<Product>(Product item) {
    print(item.a);
  }

  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    Test<int, Product> c = Test(testA, testB);
    c.eval();
  });
}

class Product {
 final String a;
 Product(this.a);
}

typedef CellBuilder<F> = Widget Function(F item);
typedef testString<T>(T text);

class Test<T, F> {
  final testString _f;
  final CellBuilder _cellBuilder;
  Test(testString this._f, CellBuilder this._cellBuilder);
  eval() {
    _f("hello");
    _cellBuilder(Product("world"));
  }
}
```

## Logs

```
```

```
```

```
```

**Comment by mraleph** [comment]
Look at these lines:

```dart
  final testString _f;
  final CellBuilder _cellBuilder;
```

If you don't pass type parameters they get some default values - in this case `dynamic`. So what you wrote means:

```dart
  final testString<dynamic> _f;
  final CellBuilder<dynamic> _cellBuilder;
```

Now this error `type '(Product) => Widget is not a subtype of type (dynamic) => Widget` should make more sense to you: indeed `_cellBuilder` has type `(dynamic) => Widget`. 

You probably want something like this:

```dart
  final testString<T> _f;
  final CellBuilder<F> _cellBuilder;
```

Types with type parameters are kinda like functions, you need to pass type arguments explicitly if you want some specific ones. Just because some type parameters have the same names (e.g. `testString` is has type parameter named `T` and class `Test` has type parameter named `T`) that does not mean that they will get substituted implicitly. 

Also in general I recommend using StackOverflow for questions like this.
