### ISSUE TITLE
Manage gestures priority between two widgets

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#28139]
I'm experimenting using the google maps for flutter plugin but I'm running into a problem managing the gesture priority.

My map, which need to handle gestures is rendered inside a PageView which also listen to some gestures. The thing is, It appears that the gesture handler of PageView take the priority over the map one, so if I drag vertically on the map, the map move but if I drag horizontally on the map, the page will switch instead of the map moving.

Is there a way to manage the priority between gesture handlers of widget to fix this sort of problems?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by theochampion** [comment]
I've read a bit about the gesture system in Flutter and from [this article ](https://medium.com/flutter-community/flutter-deep-dive-gestures-c16203b3434f), when a parent and a child widget both are set to handle gestures, the priority goes to the child which in my case should be the map and not the `PageView` 🤔

**Comment by avivbrg** [comment]
That's actually by design, to capture gestures in the map you'll need to supply gestureRecognizers to GoogleMap (which will pass it to the underlying platform view).

See https://docs.flutter.io/flutter/widgets/AndroidView/gestureRecognizers.html 

"When null, an empty set of gesture recognizer factories is used, in which case a pointer event sequence will only be dispatched to the platform view if no other member of the arena claimed it."

**Comment by theochampion** [comment]
@avivbrg Awesome, it make sense now !

So just add this field to the `GoogleMap` widget

```
                gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
                  new Factory<OneSequenceGestureRecognizer>(
                    () => new EagerGestureRecognizer(),
                  ),
                ].toSet(),
```

which require the following imports
```
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
```
