### ISSUE TITLE
[webview_flutter] webview dosent rembers last visited url instead loads initial url

### ISSUE THREAD

**Issue by shuvoprosad** [flutter/flutter#28402]
I am trying to build a news app. I have used TabBarView and three web views as three pages. When I click any link on the webpage and then switch the tab using tab bar and then return to that same web view the web view dosen't remembers the last visited link instead it loads the initial URL again.

**Comment by ozc** [comment]
Webview state is not stored. I've tried creating multiple webviews on initstate. Then used future builder to display created webviews. Still they displayed initialurls as they were just created.

Not just storing last visited url, but all state would good. Or, state can be stored outside and passed to WebView. By this way, instead of creating multiple webviews, a single one can be created and just the state is changed.

**Comment by TahaTesser** [comment]
HI @shuvoprosad 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
