### ISSUE TITLE
flutter run ios with vscode in windows 10

### ISSUE THREAD

**Issue by mammadkoma** [flutter/flutter#28462]
Hi

I searched for run ios by flutter and I found there is flutter inspector for switch between android and ios.

Is it possible to run ios with vscode in windows 10?

**Comment by zoechi** [comment]
You can switch the look-and-feel to Cupertino (iOS) on Android, but you can't run iOS, because for that XCode would need to be installed and that can only be installed on OSX.

There are cloud services that you can use to build for iOS without having it installed locally.

Details are discussed in many similar SO questions.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by mammadkoma** [comment]
Can you give a video or article to show how we can run ios on flutter and windows without mac?

**Comment by zoechi** [comment]
@mammadkoma as I said above, you can't.

**Comment by wangshiyang** [comment]
@zoechi why xamarin+c# can debug ios on windows?

**Comment by easazade** [comment]
there is always a solution. believe it or not most developers use windows to develop apps not mac.
