### ISSUE TITLE
BorderRadius.circular(double radius) should be a const constructor as well

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28535]
`BorderRadius.circular(double radius)` from `broder_radius.dart` isn't marked as a `const` constructor, but it uses a `const` constructor and all others constructors as `const` constructors, so I think it should be marked as one as well.

**Comment by jonahwilliams** [comment]
From the BorderRadius.circular constructor:

```
BorderRadius.circular(double radius) : this.all(
  Radius.circular(radius),
);
```

Even though Radius.circular is a const constructor it isn't being called const here, since it varies based on the value of radius. While a const invocation of the BorderRadius.circular constructor would imply a const radius, there is no way to indicate that Radius.circular should be conditionally const.

**Comment by feinstein** [comment]
I am sorry but I am new to Dart, I don't understand this issue.... if `Radius.circular()` generates a constant object, why this can't be used?

**Comment by jonahwilliams** [comment]
`Radius.circular(radius)` is not a const expression, `const Radius.circular(2)` is.

**Comment by feinstein** [comment]
ohhh now I got it thanks!
