### ISSUE TITLE
Use system icu on iOS/Android

### ISSUE THREAD

**Issue by doumafang** [flutter/flutter#28636]
After reading these two issues，https://github.com/flutter/flutter/issues/392 and https://github.com/flutter/flutter/issues/394. I still think icu can be removed from Flutter.

These days I have tried to remove icu lib in iOS, and the result is very obvious, it haved save 1.7MB of framework's size.

**Comment by jonahwilliams** [comment]
cc @goderbauer

**Comment by ericmayc** [comment]
> After reading these two issues，#392 and #394. I still think icu can be removed from Flutter.
> 
> These days I have tried to remove icu lib in iOS, and the result is very obvious, it haved save 1.7MB of framework's size.

Hello, I want to know. What's the replacement of the icu?

**Comment by dnfield** [comment]
There is no system ICU to use on Android or iOS.

You can remove ICU, but you will then have a lot of issues with text layout/line/word breaking, especially if you have any users of non-English langauges (but even in English it will cause issues). I've filed https://github.com/flutter/flutter/issues/50292 to see what we can do about dynamically loading ICU at runtime from some other source rather than needing to include the whole blob.
