### ISSUE TITLE
VSCode plugin uses much ram and running multiple processes unneccessarily

### ISSUE THREAD

**Issue by canewsin** [flutter/flutter#28639]
![2019-02-28_15-17-33](https://user-images.githubusercontent.com/26790557/53557667-6fd13880-3b6c-11e9-9685-f4a80b339b57.gif)

> Flutter Doctor

```
C:\Users\Me>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by canewsin** [comment]
They are running even i closed vscode
@zoechi any help on this

**Comment by canewsin** [comment]
after some times it throws out of memory error because of this much of ram usage

**Comment by DanTup** [comment]
@canewsin The processes in your list are from when you run a Flutter app. It seems like they're not being terminated correctly when you close your debugging session.

Could you try this:

- Ensure there are no `flutter run --machine` processes listed in explorer
- Open VS Code and open your Flutter project
- Run the **Dart: Capture Logs** command from the VS Code command palette
- Tick only the **Flutter Run** and **Debugger** options 
- Run your Flutter app as normal, then terminate the debug session
- Wait for 60 seconds after terminating the debug session
- Click **Stop Logging** in the logging notification (which may have collapsed into the bell icon in the status bar)

At the end of this, if there is now a `flutter run --machine` running in task manager, please attach the log here.

Thanks!

**Comment by canewsin** [comment]
Ok i followed the above procedure `flutter run --machine` processes are not running after terminating debugging session now processes are closing 

@DanTup
How this problem is solved could you give me some explanation so it is helpful for others

**Comment by DanTup** [comment]
@canewsin My guess is that it's either intermittent, or may depend in how you're terminating your debug session.

That said, your original post shows Flutter v1.0 - if you're updated to v1.2 since (released earlier this week), it's *possible* there are changes in there.

If you haven't upgraded though (still on v1.0), I would try a few more times to see if you can reproduce it. It'd definitely be good to track down what's happening if we're leaving orphaned processes.

**Comment by canewsin** [comment]
i recently downloaded flutter from site but i extracted those to seperate folder every time as versions and update my ENV_VAR as per my requirement so i was using v1.0 and doesn't upgrade and also versioning system shows 550+- around commits for flutter so i can confirm that i was on v1.0

**Comment by DanTup** [comment]
@canewsin Are you still on v1.0 now, or have you upgraded? If you've upgraded, it's *possible* you got a fix (though I don't know of any between 1.0/1.2). If you're still on v1.0 now, then I think the bug is likely still there, just only happens under specific circumstances. If you're able to reproduce it at all and provide a log, we should be able to figure out what's happened.

**Comment by canewsin** [comment]
i think i was using this version
https://github.com/flutter/flutter/commit/8661d8aecd626f7f57ccbcb735553edc05a2e713

**Comment by canewsin** [comment]
![githubdesktop_2019-02-28_22-41-03](https://user-images.githubusercontent.com/26790557/53584618-01ab6680-3baa-11e9-8dae-0dbd7bff3717.png)
Github desktop ScreenShot

**Comment by DanTup** [comment]
@canewsin Ok, so when you originally opened this issue you seemed to be using v1.0, shown in your `flutter doctor` output:

> [√] Flutter (Channel stable, v1.0.

So it seems like you've upgraded to v1.2 since. It's possible something in that version has fixed this issue if you can't reproduce it anymore (though I don't know of any changes that might've fixed this).

It probably makes sense to keep this open for a little just to ensure it doesn't come back. If you do see it again on the version you're on, would you mind trying to obtain a log (as detailed above) and attaching it? Thanks!

**Comment by canewsin** [comment]
no i was still on v1.0 changes are just synced now i just opened my cmd and run `flutter doctor`
Building flutter tool...
```
Running pub upgrade...
Downloading package sky_engine...                                   1.6s
Downloading common tools...                                        15.6s
...
```
tool is building now so still on v1.0
also i just accidentally synced changes just one hour before
anyway i will report the problem if still occurs

**Comment by canewsin** [comment]
my tool built successfully 
```
Downloading android-arm64-dynamic-release tools...                  5.0s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

• No issues found!
```
i will report for any errors thanks for your support

**Comment by canewsin** [comment]
one thing to report is i just remove my vscode and reinstalled it today

**Comment by DanTup** [comment]
> one thing to report is i removed my vscode and reinstalled it today

I wouldn't expect this to make any difference, but let me know if you see it again and can get a log anyway. Thanks!

**Comment by canewsin** [comment]
Hi @DanTup today i faced this issue one more time i think it happens 2 flutter projects at a time i mostly thought, while i state about this issue at first same case there are 2 flutter projects are opened at a time

**Comment by canewsin** [comment]
even those 2 projects are completely closed these processes are not closed

**Comment by DanTup** [comment]
@canewsin Are you able to capture a log (see https://github.com/flutter/flutter/issues/28639#issuecomment-468304924) when reproducing this?

**Comment by canewsin** [comment]
Its rearly happening so not able to capture @DanTup i will randomly trying i will report, if i catch it

**Comment by DanTup** [comment]
Ok, thanks. Though if you can't reproduce on-demand it may be hard to get the logs (you need to be capturing at the time you stopped the debug session, to capture the shutdown logging).

If you do continue to see it but can't get logs, let me know and maybe we can do something different with the logging so that when processes aren't terminated, they leave a log file somewhere.
