### ISSUE TITLE
We call `ancestorWidgetOfExactType` directly or indirectly from `build`.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28668]
The docs say don't do this.  They could be clarified a bit to tell you where to call it.

We should fix all instances of this. It would be nice if we could add an assert, but I'm not sure walking the `StackTrace.current` is feasible for this or not.

**Comment by Hixie** [comment]
It depends what you call it for. If it's an assert looking at the structure of the tree (i.e. it doesn't care about the actual widget, just the type), it's fine (if the structure changes, you're guaranteed to get rebuilt). The problem is only if you're actually looking at the value of the returned widget itself.

Walking the stack is fine, but we should fix https://github.com/flutter/flutter/issues/4021 before we add more logic that does that.
