### ISSUE TITLE
Severe navigator fail on iOS (swipe back) since newest stable upgrade

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#28728]
See video for demonstration:
https://youtu.be/cwzUr5-vN_M

Severe issue since the new stable upgrade (1day ago). Reproducible on any tap-able item, when simple using navigator.push to get to a new screen on iOS. Just tap on an item and swipe back via iOS gesture, then quickly tap the item again. New screen is shortly opened, then closed. Sometimes, this error message pops up:
https://github.com/flutter/flutter/issues/28058

**Comment by HansMuller** [comment]
@cbracken you removed the cupertino label because this problem occurs on Android?

**Comment by HansMuller** [comment]
I was able to reproduce the problem with a simple test case using `platform: TargetPlatform.iOS`: https://gist.github.com/HansMuller/3b26fbbd445764e0e54e95ba64acc156
 
The failure occurs in `_CupertinoBackGestureController`. Looking into it.

**Comment by HansMuller** [comment]
The problem seems to be due to the order in which the route's transition animation status listeners are added/run. TransitionRoute adds a listener that disposes the route (with `finalizeRoute()`):

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/routes.dart#L159

The Cupertino back gesture handler does as well:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/route.dart#L655

If the TransitionRoute's listener runs first the route is disposed before the back gesture handler tries to `Navigator.pop` it.

Still trying to understand how this is supposed to work, what causes the transition route's listener to run first, etc.

**Comment by HansMuller** [comment]
Working with @xster on this and think we've found a solution. Writing tests.

**Comment by HansMuller** [comment]
This appears to be the same bug as https://github.com/flutter/flutter/issues/27334

**Comment by msw333** [comment]
Great - thanks for keeping us up to date 👍.

**Comment by xster** [comment]
I would remove the today tag since the issue has been there for 2 years and isn't that easily producible.

**Comment by HansMuller** [comment]
@xster I've removed the TODAY label even though I've seen you reproduce the bug with just one try :1st_place_medal:

**Comment by Thomson-Tsui** [comment]
I met this trouble too. the application will crash on iPhone6.
