### ISSUE TITLE
Questions about the NestedScrollView

### ISSUE THREAD

**Issue by MrReN** [flutter/flutter#28721]
So using NestedScrollView if we have a Row in the body that contains two listviews, ListViewA and ListViewB, how do we get ListViewA to slide and the NestedScrollView to not move

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
