### ISSUE TITLE
Generated Flutter Module Files Do Not Use AndroidX

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#28805]
Flutter generated files still target SDK 27 and use the non AndroidX version of libraries which conflicts with projects that target SDK 28 and use AndroidX.

I've previously opened an issue about this at **Add Flutter to Existing App Fails, Flutter Tools Generates Incorrect Files** #22090

It's been 5 months and 2 major version releases later so I would like to ask about plans to update the generated files. The problem is that the generated files overwrite my fixes which means I have to make the same fixes EVERY TIME just to build my project.

![maxthonsnap20190303114745](https://user-images.githubusercontent.com/19896174/53699762-71d80900-3db1-11e9-89e0-70229fe3a993.png)

![maxthonsnap20190303114935](https://user-images.githubusercontent.com/19896174/53699764-743a6300-3db1-11e9-82d6-1f464b731e02.png)

![maxthonsnap20190303115406](https://user-images.githubusercontent.com/19896174/53699771-77355380-3db1-11e9-8b7a-0370c31f53b9.png)

![maxthonsnap20190303115536](https://user-images.githubusercontent.com/19896174/53699775-7997ad80-3db1-11e9-845b-fcdd8cc2e878.png)

Are there plans to update Flutter to target SDK 28 and use AndroidX?

**Comment by jonahwilliams** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@jonahwilliams @gspencergoog @dnfield @jason-simmons Do any of you know the right group of people to assemble to make a decision about SDK versions and included libs like AndroidX? This question applies both to a Flutter project, as well as the Android embedding, itself.

**Comment by jiechic** [comment]
the same problem on usr flutter module for an exits project
i want to use flutter but now is shelve

**Comment by neiljaywarner** [comment]
@matthew-carroll referencing https://developer.android.com/distribute/best-practices/develop/target-sdk
Since new apps **_must_** target 28 in August, this is huge; please mark this a must-fix for 1.4 if 1.4 is released in early May, that's pretty much the last chance for August release.

This was a big problem for 'the other guys' so if it can be planned well for flutter that would be very good.

**Comment by neiljaywarner** [comment]
@searchy2 @jiechic  what is the output of flutter-doctor please? I just did file-new-project in intellij with Flutter (Channel stable, v1.2.1) and I get CompiledSDK 28 target SDK 28

I get the same behaviour with add2app .android directories recently created wit flutter 1.2.1

cc @matthew-carroll 

although i would agree communication about it is very important please, e.g.  https://github.com/flutter/flutter/wiki/Changelog and an entry on flutter.dev FAQ for Android developers or even more since the play store requirement is so urgent (august timeline) every year - so charting this item very carefully would be greatly appreciated.

"the other guys" have done poorly in this area so it would be great if flutter would do excellent in this area

**Comment by searchy2** [comment]
I'll create a new project from scratch and give it a try. Flutter has been giving me a lot of problems lately with Git and not committing the right files in .gitignore. Fingers crossed starting a new project will generate the correct file sdk targets.

**Comment by jiechic** [comment]
@neiljaywarner 
![image](https://user-images.githubusercontent.com/518977/53849368-940c9980-3ff2-11e9-82fe-e8396c080a53.png)

**Comment by searchy2** [comment]
Can verify that creating a brand new Android project and adding a new Flutter module does result in incompatible generated files with AndroidX.

**Comment by neiljaywarner** [comment]
Would it be wise to update title? If Android x is the issue but api levels fine?
...

**Comment by searchy2** [comment]
Sure, what title do you think is more accurate?

**Comment by neiljaywarner** [comment]
Just take out "target so 27 and" if they no longer apply

**Comment by dnfield** [comment]
Android X is a bit thorny right now partly because of plugins. In the ecosystem, some plugins are migrated to Android X, others are not.  Processes that we'd hope would assist with migrating automatically projects aren't quite working here.  We're investigating this to try to figure out how to make the migration as painless as possible - but it's not quite there yet.  

If you need this today, you'd have to migrate the template yourself, and then it's possible that you will have trouble using some plugins that have not yet migrated to Android X.  The dependency interactions get kind of messy and TBH I'm not 100% clear on which configurations do and don't work at this point.

This is definitely on our radar, but I don't have a good notion right now for when we'll have it resolved.

/cc @mklim

**Comment by jiechic** [comment]
Any news and progress for this issue？

@dnfield 
We use CI to build different branches（more and more branches will be created），
then use ’flutter packages get‘ to initialize the flutter module in different branches
so we don't migrate the template myself in CI system

I hope to resolve this issue as soon as possible.

**Comment by athornz** [comment]
The problem here is not updating to AndroidX - that is doable.

It's that after running `pub get` any changes made to the generated gradle files are overwritten.

This behaviour is different from a standard Flutter app where it's possible to make changes to the gradle files.

Without a way to control compile version or gradle dependencies from the pubspec file, it really shouldnt be overwriting the generated files.

**Comment by athornz** [comment]
My current work around is to commit the .android folder to git and revert the changes whenever flutter overwrites them.

**Comment by searchy2** [comment]
^This seems to be the only option for now.

**Comment by rowntreerob** [comment]
Just did an flutter-eval over period of couple days by loading some of the samples on AS 3.3.2 then adding firebase cloud, then adding packages like "file_picker" in order to play app that fetches local media files , persists to cloud storage and manages a UI...  (firebase_storage, image_picker)

Immediately, there arose manifold gradle/android build issues ( api 27 v api 28 AndroidX  ) requiring lots of time sorting thru gradle.build dependency errors preventing android builds. And guess what ? Once resolved they all get overwritten and ur back a square on your next rev to pubspec.yaml  && 'pub get' in the main project. 

love that workaround of committing random  auto-gen folders files to git  and reverting each build.... 

what better way is there to discourage nooby like myself.....

**Comment by dnfield** [comment]
/cc @mit-mit @matthew-carroll  (again)

The issue here is less about what Flutter engine supports, and more about that the `.android` ends up requiring end user modification (that then gets overwritten).

As I understand it, the `.android` folder was envisioned as something the user wouldn't have to touch (and, in fact, should not ever touch because it gets overwritten).  I'm not entirely sure what the right solution here is, but it needs a larger conversation.

**Comment by rowntreerob** [comment]
From a platform eval perspective, if you expect relative transparent build / plugin support for ios/android but you also notice this sort of brittle, confusing build time behavior, it looks like a guarantee of getting dragged down into the platform's tools swamp.  I can not be confident that i can solve business problems using the dev platform if i waste all my time learning flutter/android/ios gradle build issues. 

FWIW - the docs samples are good n easy to follow.  However, if in the first couple tries at extending samples, adding new packages / features to the samples you run into build / dependency confusion , then you have to drop it as a platform option... 

IMO - android api revs going in one direction - flutter in another and there is no evidence of  coordination.

**Comment by matthew-carroll** [comment]
@tvolkert @kf6gpe @csells FYI - it would be good to get a tooling and/or infra dev looking into project structure.

**Comment by noordawod** [comment]
Same issue here :/ We want so much to use Flutter but we cannot do that (as a module) when there's no AndroidX support. Even prepare a migratory branch for us who needs that, and broadcast that at a certain future date, that branch is going to be merged into master. That would give a solution for both parties (AndroidX and non-AndroidX).

What do you think?

**Comment by csells** [comment]
Is there a downside to simply switching to AndroidX in the project template?

**Comment by athornz** [comment]
I think the issue there is that there are still quite a few plugins that haven't updated to AndroidX yet.

Switching to AndroidX in the template would break compatibility.

Google build Jetifier for this exact reason - to rewrite the class files of dependencies to use AndroidX. The best fix here would be to get Jetifier working with the Flutter module.

**Comment by noordawod** [comment]
Understood. So why not prepare a separate branch to be compatible with the upcoming AndroidX? That should be an easy task. Hell, I would submit a PR if the Flutter team would accept that as a viable route.

**Comment by athornz** [comment]
I've created a PR (above) that adds support for AndroidX. It adds a new flag to the module section of a pubspec.yaml file which controls whether the generated files use AndroidX.

```
flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage:
    iosBundleIdentifier:
```

**Comment by jiechic** [comment]
it's some wrong on PR build
have any update for after？

**Comment by searchy2** [comment]
Going to test this in Add 2 App and see if the issue is fixed. :crossed_fingers:

**Comment by omid-io** [comment]
Any luck on this working now? @searchy2

I have an existing android app with target and compile SDK version = 28. The project has been migrated to AndroidX.

Ran `flutter channel master` (to get the PR merge fix by @athornz , `flutter upgrade`

then followed documentation here: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

 A) ran `flutter create --androidx -t module my_flutter` <-- added the --androidx flag. 
This generates the flutter module and all other files within the project. 

B) Updated my settings.gradle 

C) Added the flutter module as an implementation dependency to my gradle

However, the pubspec.yaml file **does not** have this flag added: androidX: true. The generated java Flutter classes still use the old android support libraries. 

Am I missing something here?

**Comment by athornz** [comment]
@omid-io I've just created a small PR to fix that, but you can add the androidX flag manually and run `flutter packages get` and the generated files will be updated to androidX.

**Comment by omid-io** [comment]
thanks @athornz, You Da Man! 👍 I'll try it out!

**Comment by searchy2** [comment]
Keeping this issue open because there's still issues with converting an existing project to AndroidX. 
![MaxthonSnap20191020150809](https://user-images.githubusercontent.com/19896174/67165513-99cdaa00-f34b-11e9-9222-7e8cd39f6c96.png)
AndroidX compatibility is still not enabled by default which means that new projects that are created needs to be converted to AndroidX. Unfortunately, the conversion process doesn't always work. When can AndroidX be enabled by default?

**Comment by blasten** [comment]
AndroidX is the default now.
