### ISSUE TITLE
Transparent Flutter App always has black background

### ISSUE THREAD

**Issue by leisim** [flutter/flutter#28844]
Hi,

I need my Flutter app to have a transparent background (just a dialog).
When I use `showDialog`, it has a black background if there is no route below the dialog.

When I set the `color` of the `MaterialApp` to be transparent, I get an error:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building WidgetsApp-[GlobalObjectKey
_MaterialAppState#8500b](dirty, state: _WidgetsAppState#87d79):
'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
color.alpha == 0xFF': is not true.
```

Is there another way to create a transparent app?

flutter doctor -v
```
[✓] Flutter (Channel master, v1.3.3-pre.18, on Mac OS X 10.14.2 18C54, locale de-DE)
    • Flutter version 1.3.3-pre.18 at /usr/local/Caskroom/flutter/1.0.0/flutter
    • Framework revision 2bab21b2bd (31 hours ago), 2019-03-03 05:15:28 -0500
    • Engine revision a28329cb91
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/___/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.
```

**Comment by HansMuller** [comment]
It would help if you provide a small complete application that demonstrates the problem you've run into. Thanks!

**Comment by leisim** [comment]
@HansMuller Here is a small test project: https://github.com/leisim/dialogapp

**Comment by leisim** [comment]
@HansMuller is this a flutter issue or am I doing anything wrong?

**Comment by NMateu** [comment]
@leisim https://github.com/NMateu/flutter_transparent_app 

Some explanation:
1. To make an android app transparent you must edit a app style https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/res/values/styles.xml
2. Apply this theme in manifest https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/AndroidManifest.xml#L16
3. Enable Flutter transparent view in MainActivity https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/java/com/example/flutter_transparent_app/MainActivity.java#L14

After this your Android activity is transparent. Until you use MaterialApp or WidgetApp in the flutter code, it will remain so.

To show dialog in flutter I must use a showGeneralDialog function because showDialog uses a MediaQuery which is dependent of MaterialApp or WidgetApp https://github.com/NMateu/flutter_transparent_app/blob/master/lib/main.dart#L78

The last condition to display the dialog is to wrap AlertDialog in MaterialApp widget https://github.com/NMateu/flutter_transparent_app/blob/master/lib/main.dart#L84

@HansMuller is there any reason why MaterialApp or WidgetApp cannot be transparent? It would be much easier...

**Comment by leisim** [comment]
@NMateu Thank you that really helps me. But it would be nice if it was less complicated to use material widgets...

**Comment by searchy2** [comment]
Thanks @NMateu for your detailed explanation. Your sample project was very helpful in allowing me to setup a transparent FlutterView correctly. Many thanks!

**Comment by phanirithvij** [comment]
@leisim I think it can be done with just
```dart
    return MaterialApp(
      builder: (context, child) {
        return Scaffold(
          backgroundColor: Colors.transparent, // <------ this
...
```

**Comment by leisim** [comment]
@phanirithvij Unfortunately the background is just black if I try that...

**Comment by phanirithvij** [comment]
@leisim I mean after following this https://github.com/flutter/flutter/issues/28844#issuecomment-478939888.

This is a demo app similar to that of what @NMateu's `flutter_transparent_app`.

https://github.com/phanirithvij/invisible_flutter

**Comment by NMateu** [comment]
@phanirithvij I don't think that is a good example... Your app is a new window with a background, but not a transparent view. When you launch my app, you will be able to see a view that is under app, but in your example, that is impossible, because your app has a background with your wallpaper (that's how it works on my phone at least - maybe I have a bad channel for this example?)

It seemed to me that somewhere I saw some commits talking about the transparency of the application, or about the case of transparency when AddToApp, so maybe it is now possible to execute such an application as on my example without having to avoid a transparent color in MaterialApp.
Maybe @matthew-carroll would know?

To clarify, such things can be done only on Android, iOS is impossible - there is no possibility to make a transparent application that will be displayed over another application, maybe that is the reason why you can't use transparent color in MaterialApp

**Comment by phanirithvij** [comment]
@NMateu I was wrong in assuming that transparency is just displaying the wallpaper.
My use case was an android home screen launcher using flutter that's the reason for my assumption.

Is the use case that's being discussed here `Draw on top of other Apps`? I don't understand clearly.

**Comment by NMateu** [comment]
@phanirithvij you have right, that's a good solution. I didn't notice that you changed the style of the application.

In this case, I think this task can be closed. Flutter allows you to use a transparent background, but in this case you must use Scaffold Widget

**Comment by phanirithvij** [comment]
@NMateu
use Scaffold Widget with transparent background color along with all the steps you explained [above](https://github.com/flutter/flutter/issues/28844#issuecomment-478939888)

**Comment by phanirithvij** [comment]
**Update** on this issue. The method `FlutterView.enableTransparentBackground` was deprecated according to https://github.com/flutter/flutter/issues/37025 with https://github.com/flutter/engine/pull/10235.

As the current method prevents accessebility apps like TalkBack to not run properly.

The suggested method to achieve a transparent background is to use [`FlutterView.setZOrderMediaOverlay`](https://developer.android.com/reference/android/view/SurfaceView?hl=en#setZOrderMediaOverlay(boolean))
```kotlin
// kotlin
val view = flutterView
view.setZOrderMediaOverlay(true)
view.holder.setFormat(PixelFormat.TRANSPARENT)
```
Instead of
```kotlin
val view = flutterView
view.enableTransparentBackground()
```

**Comment by jamiejackherer** [comment]
> @leisim https://github.com/NMateu/flutter_transparent_app
> 
> Some explanation:
> 
> 1. To make an android app transparent you must edit a app style https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/res/values/styles.xml
> 2. Apply this theme in manifest https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/AndroidManifest.xml#L16
> 3. Enable Flutter transparent view in MainActivity https://github.com/NMateu/flutter_transparent_app/blob/master/android/app/src/main/java/com/example/flutter_transparent_app/MainActivity.java#L14
> 
> After this your Android activity is transparent. Until you use MaterialApp or WidgetApp in the flutter code, it will remain so.
> 
> To show dialog in flutter I must use a showGeneralDialog function because showDialog uses a MediaQuery which is dependent of MaterialApp or WidgetApp https://github.com/NMateu/flutter_transparent_app/blob/master/lib/main.dart#L78
> 
> The last condition to display the dialog is to wrap AlertDialog in MaterialApp widget https://github.com/NMateu/flutter_transparent_app/blob/master/lib/main.dart#L84
> 
> @HansMuller is there any reason why MaterialApp or WidgetApp cannot be transparent? It would be much easier...

Will this actually provide a mechanism for an app that will be able to draw over other apps? To be clear, I am wanting to have a feature where a music player can be miniaturised and can then be a floating (and moveable) widget that will hover over other apps and still allow the other apps to be used while music is playing?

**Comment by NMateu** [comment]
@jamiejackherer it is possible but not this way. You need a service with connected view to it and system alert permission. Look here “Bring Floating Button Outside the App Android” by Mujjtahidah https://link.medium.com/310tI2KRL2 or on any other google result about fab outside the app. Your view could be a flutter view and flutter app connected to it.

**Comment by iaexc** [comment]
Hi, I have the same problem. I have a reusable class `ImageView `where I send photos to be viewed in full and be zoomed in/out. It's quite simple, I set the scaffold background color to black with 0.5 transparency but it always show a solid color background. 

Here's my code for the said class
`class ImageView extends StatelessWidget {
  final ImageProvider file;
  ImageView({Key key, @required this.file}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black.withOpacity(0.5), //shows transparent background for a second but something overrides it and the background turns solid black
      body: GestureDetector(
        onTap: (){
          Navigator.of(context).pop();
        },
        child: Container(
            height: MediaQuery.of(context).size.height,
            child:  PhotoView(
              backgroundDecoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.5) //doesn't really do anything
              ),
              imageProvider: file,
            )
        ),
      ),
    );
  }
}`

And I call it from other classes using 
`Navigator.of(context).push(PageRouteBuilder(
    pageBuilder: (BuildContext context, _, __) =>
         ImageView(file: _image.image,)
     )
 );`

I don't know what went wrong, it was working the way I was expecting it to work until I updated my flutter sdk.

**Comment by lawonga** [comment]
Can we confirm that this is indeed impossible on iOS?

**Comment by matthew-carroll** [comment]
FYI - here is the website guide that discusses displaying a translucent Android screen that includes Flutter:
https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#add-a-translucent-flutter-screen

**Comment by matthew-carroll** [comment]
Is this issue filed for Android, iOS or both?

Does the issue still occur after following the recommendations in this thread, and the website guide for translucent Android screens?

**Comment by matthew-carroll** [comment]
It looks like the reported issue can probably be fixed by following existing documentation. It doesn't seem like there is a bug here. I've also recently worked with a transparent `FlutterActivity`, so it's not fundamentally broken in the embedding. Since there hasn't been any discussion activity on this thread for almost a week to point to any issue, I'm going to tentatively close this issue as resolved.

Please feel free to re-open this issue if the original problem still looks like an error. If anyone has issues on iOS, please file new tickets for those issues. Thanks.

**Comment by lts1610** [comment]
Hi @matthew-carroll 

**1. In the master channel**:
I found that `renderSurface` is null in this constructor.

```dart
  private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterSurfaceView;

    init();
  }
```
I think `this.renderSurface = flutterSurfaceView;` should be `this.renderSurface = flutterTextureView;`

**2. In the stable channel**
Because of `FlutterActivityLaunchConfigs` is not public. So, I tried: 
```java
intent.putExtra("background_mode","transparent"); 
activity.startActivity(intent)
```
It work fine. But I have another trouble when show `modalBottomSheet` that has a child is TextField:
- Transparent Mode: the keyboard overlaps `modalBottomSheet`.
- Opaque Mode: work fine.

I don't know why? If you have any idea, please give me a suggestion. 
And, may we consider to reopen this issue?

Thank you,
