### ISSUE TITLE
Add support for custom models from ML Kit for Firebase

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#28859]
https://firebase.google.com/docs/ml-kit/use-custom-models

**Comment by shinz4u** [comment]
Is there any work being done on this? I am currently working on a flutter app and it requires a custom tflite classifier. Is there a workaround to use tflite with flutter? Is it possible to follow the custom model steps in order to implement it manually for ios and android within a flutter app? Any help will be appreciated.

**Comment by bparrishMines** [comment]
Hi @shinz4u 

Unfortunately we don't have anyone working on this yet as we focus on testing and infrastructure. However, its possible to create your own plugin using custom models or find a third party plugin that that does at https://pub.dev/.

**Comment by kroikie** [comment]
@bparrishMines

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/401. Any further collaboration will be done there.
