### ISSUE TITLE
META: define a process for transferring community packages to Google maintained repos

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#28884]
Is there a defined process for getting community packages into Flutter core or Flutter plugins?

Possible nomination for core: `provider`
Possible nomination for Google maintained plugins: `zefyr`, `flutter_html`

**Comment by Hixie** [comment]
I don't know if this is necessarily the direction we want to go in, but the general issue of maintaining plugins is definitely one that is on my plate at the moment.

**Comment by Hixie** [comment]
cc @amirh, who is looking at this area now.

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
