### ISSUE TITLE
dart:ui Pictures can retain SkImage objects, causing increased GPU memory usage

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#28912]
Internal: b/140831274

Branching off of #19558. Dart's GC has no information about objects retained by Pictures. This causes the GC to ignore collecting Picture objects while it collects Images instead. However, the internal SkImage is shared with the Picture's underlying SkPicture, so collecting just the Images and ignoring the Pictures causes GPU memory usage to skyrocket when lots of high resolution images are displayed. This even happens when manually disposing Images directly after usage.

Testing my app, after a lot of scrolling there were 2,088 Picture objects currently allocated, and only **87** were strongly reachable. These Picture objects internally have a reference to internal SkImages, and the GC has no knowledge of that. Doing a manual GC in the Observatory, then loading another image (this is required by Skia to recover GPU memory) resulted in GPU usage going down to 512mb (the configured max limit).

I have no clue how to communicate to Dart's GC that a Picture references Images and Paths and etc. other than collecting all resources into a List in Picture's methods.

**Comment by ds84182** [comment]
I have a WIP change to dart:ui that adds a List<Object> _dependencies field to Picture. Still testing to see if the GC uses it as a hint. We'd have to deprecate and no-op Image.dispose though, otherwise it messes with the GC.

**Comment by eseidelGoogle** [comment]
@ds84182 I'm curious as to the fate of your patch?  Another Google customer referenced this bug this week.

**Comment by jkurtw** [comment]
b/140831274

**Comment by ds84182** [comment]
I should still have it on my laptop somewhere. It is sorta incomplete though.

**Comment by ds84182** [comment]
Found it, pushed to https://github.com/ds84182/engine/tree/canvas_recorder_deps

The branch is out of date, but the general concept is there.

**Comment by jacob314** [comment]
Fyi @terrylucas

**Comment by dnfield** [comment]
Based on investigations I've been doing for https://github.com/flutter/flutter/issues/56482 and https://github.com/flutter/flutter/issues/57746, I believe that the root cause of all of this is https://github.com/dart-lang/sdk/issues/42078

What I've seen is that the pictures do increase the refcount on the SkImage, and then eventually become eligible for garbage collection when they (and the image) lose their dart references, but the GC just takes too long to collect them - sometimes waiting as long as after new allocations have already been made.

@ds84182 - I would expect your patch to not make things better, since it actually _increases_ the amount references on the image making it harder to free. I did some similar experiments with tracking the image size in `GetAllocationSize` in the native side for pictures. It did not help enough, unless I just reported pictures as being absurdly large to the embedder.  That's part of why I think this is just a general Dart GC related issue.

I'll keep picking at that.
