### ISSUE TITLE
Arithmetic error when a simple addition of two values 

### ISSUE THREAD

**Issue by sbrsubuvga** [flutter/flutter#28930]
print("*****${4.65+ 1.4}");

output:  *****6.050000000000001

Why the value  000000000000001  added on result

Flutter 1.1.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 985ccb6d14 (8 weeks ago) • 2019-01-08 13:45:55 -0800
Engine • revision 7112b72cc2
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

**Comment by iqbalmineraltown** [comment]
can confirm this with Flutter 1.2.1 and Dart 2.1.2
should this issue be raised on Dart repo?

```
  print('${98.55 + 1.5}');
  print('${98.45 + 1.6}');
  print('${98.35 + 1.7}');
  print('${98.25 + 1.8}');
  print('${98.15 + 1.9}');
  print('===============');
  print('${8.55 + 1.5}');
  print('${8.45 + 1.6}');
  print('${8.35 + 1.7}');
  print('${8.25 + 1.8}');
  print('${8.15 + 1.9}');
  print('===============');
  print('${7.55 + 1.5}');
  print('${7.45 + 1.6}');
  print('${7.35 + 1.7}');
  print('${7.25 + 1.8}');
  print('${7.15 + 1.9}');
```

```
flutter: 100.05
flutter: 100.05
flutter: 100.05
flutter: 100.05
flutter: 100.05000000000001
flutter: ===============
flutter: 10.05
flutter: 10.049999999999999
flutter: 10.049999999999999
flutter: 10.05
flutter: 10.05
flutter: ===============
flutter: 9.05
flutter: 9.05
flutter: 9.049999999999999
flutter: 9.05
flutter: 9.05
```

```
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-ID)
    • Flutter version 1.2.1 at /Users/iqbal/dev/flutter_stable_dev
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by marcelgarus** [comment]
The decimal numbers 4.65 and 1.4 are represented by the periodic binary numbers 100.10100110011... and 1.01100110011....
Because in digital systems, information can't be stored arbitrarily precise, Dart's `double` rounds these periodic numbers at some decimal, causing this rounding error.
This issue is not easily fixable and exists in all major programming languages which support floating point numbers.

**Comment by jonahwilliams** [comment]
Hi @sbrsubuvga , this is not a bug with Dart but how math is implemented in computers today. For some background, check out https://floating-point-gui.de/

**Comment by github-kalpesh** [comment]
i get same problem in simple addition  


void main() {
  double a = 0.1;
  double b = 0.2;
  double c = a + b;
  print(a);//0.1  
  print(b);//0.2
  print(c);//0.30000000000000004
}

So finally what solution for this

**Comment by marcelgarus** [comment]
For exact-precision addition, you shouldn't use floating-point numbers, because their storage representation is not completely accurate, independent of the language being used. So, this is not a Dart-bug, but a big computer science problem in general.

I recommend the [decimal](https://pub.dev/packages/decimal) package for fixed-precision number calculations.
