### ISSUE TITLE
Support for -d all in --machine mode and --use-application-binary.

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#29011]
Dream wants to try running the same app on multiple devices.  `-d all` was created for this use case. 
 This workflow is neither compatible with IDE tooling nor g3 tooling.

IDE uses --machine.  g3 tooling builds the binary with a separate toolchain and uses --use-application-binary to specify which artifact to deploy.

**Comment by DanTup** [comment]
Related: https://github.com/flutter/flutter/issues/16145

There were some discussions around this, and we concluded it may be better for the IDEs to own the multiple-debug sessions (eg. they just run multiple `flutter run --machine`s, one for each device). The way the user can see the multiple sessions, switch between them for stepping, etc.. otherwise I think we'd end up with a single list of isolates in the IDE that actually represent isolates from multiple devices all mushed together (for example).

**Comment by zanderso** [comment]
Is this still relevant for Dream?

**Comment by DanTup** [comment]
FWIW, what I mentioned above works now in VS Code (with some rough edges) - see https://github.com/flutter/flutter/wiki/Multi-device-debugging-in-VS-Code. I don't know if that addresses the original requirement, though.

**Comment by zanderso** [comment]
This is not currently planned, so I'm going to tentatively close this if we're not sure anyone wants it.
