### ISSUE TITLE
Expose an API to fetch isolate id from FlutterView or FlutterEngine on Android

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#29114]
There's a Dart VM service extension API (https://github.com/flutter/flutter/wiki/Engine-specific-Service-Protocol-extensions#list-views-_flutterlistviews) to query the mapping between isolate # and the FlutterView id, but it would be nicer if FlutterView/FlutterNativeView could expose an API to support retrieving isolate #.

This is useful for testing frameworks targeting add2app such as Espresso where there can be multiple FlutterViews on the screen.

EDIT (@matthew-carroll):
Android testing systems need to be able to retrieve the isolate ID of the Flutter code that is executing behind a `FlutterView`.  This might mean we expose that info directly from `FlutterView`, or we offer a `getFlutterEngine()` on `FlutterView`, which then exposes the isolate ID.  Either way, the goal is for a testing framework to get the Dart isolate ID corresponding to a given Flutter UI.  

This solution needs to account for the possibility that a `FlutterEngine` is not yet attached to a `FlutterView`, and the possibility that a `FlutterEngine` will never be attached to a given `FlutterView`

**Comment by dnfield** [comment]
I think @mklim worked on something related to this.

**Comment by goderbauer** [comment]
@matthew-carroll I was just talking about this with @mklim offline and it came up that you have some concerns about adding this kind of API. Can you elaborate? Did you have any other ideas how this could be solved?

**Comment by matthew-carroll** [comment]
@goderbauer my concerns are bit ambiguous, but happy to discuss with you and @mklim to see if there is a better alternative.  First, my concern isn't about `FlutterNativeView` because that will go away in the new embedding API.  My concern is about exposing this info from the new `FlutterView`.

As we move forward, a `FlutterView` is really going to be like any other Android `View`.  It happens to render a Flutter UI, but otherwise its just a part of the `View` hierarchy.  This then begs the question: would it be appropriate in some other Android situation to query a `LinearLayout`, or `ImageView`, or `Drawer` for the equivalent of an isolate ID?  My initial sense is that it wouldn't.  Instead, I think developers would be expected to hold a reference to whatever backs those `View`s and then simply query the source of truth.

This situation is further complicated by the fact that a `FlutterEngine` may, or may not be attached to a given `FlutterView` at a moment in time.  We will no longer be living in a world where these artifacts are all born and destroyed together.  They will come and go independently.  So now do we also need to add listener support on `FlutterView`s for when a `FlutterEngine` is added/removed?

These are open questions in my mind and I'd like for us to find good answers before we lock ourselves into this proposed solution.

**Comment by dnfield** [comment]
It seems to me that the better place to expose the isolate id would be via the `FlutterEngine` in the new embedding - on the iOS side, that would make more sense as well.

**Comment by matthew-carroll** [comment]
@dnfield the complication there is that Espresso is entirely View based.  We could offer a `getEngine()` on `FlutterView`, but then there is still the problem of what if Espresso needs to wait some period of time for the engine to attach?

**Comment by Hixie** [comment]
It seems like to handle this issue and #29375 we should probably take a step back and figure out what the overall solution should be for integrating Flutter and Espresso. We already have an API to expose isolate IDs (the VM service protocol), but it's not clear that that's what you really want.

**Comment by mehmetf** [comment]
@adazh FYI

**Comment by adazh** [comment]
Shall we meet and discuss? There was some context and I'm happy to discuss as a group.

**Comment by Hixie** [comment]
I spoke with Ada. The goal here is just to have a way for the Espresso test to know how to communicate to the flutter_driver logic in the isolate corresponding to the FlutterView that matched whatever finder the test is using, so that we can further talk to the flutter side and test things there.

It's fine if the isolate ID is exposed only indirectly (e.g. FlutterView -> FlutterEngine -> isolate ID) instead of directly on the FlutterView, so long as there is a way to look it up as needed. It's also fine if there's no engine to talk about sometimes, that just means that the test isn't going to want to test anything on that view since it's not rendering anything.

**Comment by matthew-carroll** [comment]
> It's also fine if there's no engine to talk about sometimes

I want to confirm this assertion with everyone.  One of the reasons that Espresso was built was because the raw instrumented system did not know how to wait for platform events.  This lead to terrible thread sleeps and timers.  

Are we sure that we don't need a way for Espresso to wait for an engine to become available?  In fact, are we sure that we don't need to audit all the things in Flutter that might take time, and therefore require some kind of capability to wait for their completion?

**Comment by dnfield** [comment]
@matthew-carroll I don't think anyone is saying we would not need to wait for the engine to become avialable.

As I understand it though, all of this is going to be exposed over the vm service protocol rather than directly as methods on a particular Java class - and the service protocol will be able to tell Espresso things like when the engine has rendered a frame, or the semantics tree has been built, or what the location on the screen of a certain widget is.

**Comment by matthew-carroll** [comment]
So then we also need to support listeners that can register with a FlutterView and be notified when an engine is attached, right?  Or how else might we achieve that notion of waiting?

**Comment by dnfield** [comment]
You should be able to connect to the service protocol without knowing anything about FlutterView right?  It broadcasts in the logs what port it's listening on - and we could make it broadcast via other methods as well.

**Comment by matthew-carroll** [comment]
@mehmetf do you know if this capability needs to be made available on the old embedding? or can we just solve this for the new embedding?

**Comment by mehmetf** [comment]
Given that we would like to dogfood espresso with an external customer in Q2, the answer to that is the question: "Will the new embedding be available upstream in Q2?"

**Comment by matthew-carroll** [comment]
Good question.  Does Q2 mean end of Q2?

**Comment by mehmetf** [comment]
End of May would be a good target.

**Comment by matthew-carroll** [comment]
Ok, I think we'll be stable with the new embedding by end of May.  I'll update the title accordingly.

**Comment by Hixie** [comment]
Added milestone based on previous comment.
