### ISSUE TITLE
Can we make `flutter update-packages` a public tool?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#29301]
The need for such came up in talking with customer: solaris

@tvolkert has more context.

**Comment by tvolkert** [comment]
Even better would be to build this into `pub` - the ability to 1) upgrade without constraints, then 2) pin the constraints to the versions to which we resolved by editing the pubspec.yaml.

Then in a mono-repo, users could just do something like `for f in $(find . -name pubspec.yaml); do pushd $(dirname $f); pub upgrade-and-pin; popd; done`

@mit-mit

**Comment by app-o-matix** [comment]
Is there a way to tell which packages in your pubspec.yaml file have upgrades available? If not, it seems like most of the work for achieving that functionality is already done in update-packages and so it would be nice to have an option that gives you a list with your current versions and latest available versions.

**Comment by mit-mit** [comment]
@tvolkert I don't think I understand. For apps the recommendation is to rely on `pubspec.lock` for pinning deps, so we already support what you mention; you create your `pubspec.yml` with `any` deps, and then you run `pub upgrade` when you want to upgrade and checkin in the regenerated lock file. What am I missing?

**Comment by tvolkert** [comment]
@mit-mit the issue lies in transitive dependencies.  Consider the following:

#### pubspec.yaml
```
name: sample
dependencies:
  foo: 1.2.3
```

Now a developer on the team, John, runs `pub get`, and as a result, the following `pubspec.lock` file gets created, which John checks into Git:

#### pubspec.lock
```
packages:
  foo:
    dependency: "direct main"
    ...
    version: "1.2.3"
  bar:
    dependency: transitive
    ...
    version: "4.5.6"
```

Over the next few days, an owner of package `bar` publishes a few new versions, and after the weekend, when another developer on John's team, Susan, runs `pub get` (against the same `pubspec.lock` since it's checked into source control), she sees the following:

```
$ pub get
Resolving dependencies... 
> bar 4.5.8 (was 4.5.6)
Changed 1 dependency!
```

But Susan didn't want to implicitly update `bar` - she wanted the version that her team was ostensibly pinned to.  By picking up a new version of `bar`, she's opened herself to new bugs that John doesn't see.

The larger issue is that this happens in CI, which is why Flutter created `flutter update-packages --force-upgrade`.  Tests will start failing on innocuous commits because some transitive dependency published a new version that introduced some bug or breaking change.  After having been bit by this several times, we pin all out transitive dependencies explicitly in our `pubspec.yaml` file.  We've heard from customers that they'd like to be able to use this functionality on their own teams because they're being bitten by the same issues that we once were.

**Comment by mit-mit** [comment]
>  Susan, runs pub get (against the same pubspec.lock since it's checked into source control), she sees the following:

I really don't think that is true. The transitive entry in `pubspec.lock` should cause it to pick `4.5.6`. cc @kevmoo

**Comment by tvolkert** [comment]
That's not the behavior I'm seeing.

**Comment by tvolkert** [comment]
> I really don't think that is true. The transitive entry in pubspec.lock should cause it to pick 4.5.6

You're right 😄.  I had run a test before that showed different results, but my test was flawed.  I just verified the correct behavior.

The reason Flutter uses the current mechanism is to force apps that are on a specific Flutter SDK to be pinned to specific versions of packages that Flutter uses ([here's the current set of dependencies](https://github.com/flutter/flutter/blob/1db5d66932b873e17c8c675b3782d9c196b28499/packages/flutter/pubspec.yaml#L10)) -- since Flutter's only been verified (via testing) to work properly against those specific dependency versions.  Given the behavior of `pubspec.lock`, it's not immediately clear how the functionality of `flutter update-packages` would be useful to app teams.

**Comment by Hixie** [comment]
I don't think `flutter update-packages` is particularly relevant to our users. It's just a wrapper around `pub get`.

**Comment by tvolkert** [comment]
This is essentially a dup of https://github.com/flutter/flutter/issues/13428 - coalescing.
