### ISSUE TITLE
flutter build appbundle --release is missing x86 and x86_64 libflutter.so files

### ISSUE THREAD

**Issue by Winner28** [flutter/flutter#29303]
## Steps to reproduce
1. Create a new Flutter app
2. Build release app bundle: ``` flutter build appbundle --release ```
3. Build debug  app bundle:   ```  flutter build appbundle --debug  ```
4. Unzip release/app.aab: ```unzip -l build/app/outputs/bundle/release/app.aab  | grep lib/```
5. Unzip debug/app.aab: ```unzip -l build/app/outputs/bundle/debug/app.aab  | grep lib/```

## Logs

Inside of debug/app.aab: 
```
base/lib/armeabi-v7a/libflutter.so
base/lib/x86/libflutter.so
base/lib/x86_64/libflutter.so
```

Inside of release/app.aab:
```
base/lib/armeabi-v7a/libflutter.so
```

1 . We expect to see .so files for all platforms.
2 . Content of debug/app.aab and release/app.aab are different. 

```flutter analyze``` reports zero issue.

```flutter doctor -v```:

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3
    18D109, locale ru-RU)
    • Flutter version 1.2.1 at
      /usr/local/Cellar/flutter/1.0.0
    • Framework revision 8661d8aecd (4 weeks ago),
      2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices
    (Android SDK version 28.0.3)
    • Android SDK at
      /Users/bagdeyvgmail.com/Library/Android/sdk
    • Android NDK at
      /Users/bagdeyvgmail.com/Library/Android/sdk/ndk-bundl
      e
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[✓] Connected device (1 available)
    • iPhone XR • 36324ACA-876E-4EDC-8DB6-6E0024AD2A59 •
      ios • iOS 12.1 (simulator)

• No issues found!
```

1 . We expect to see .so files for all platforms.
2 . Content of debug/app.aab and release/app.aab are different.

**Comment by luigi-agosti** [comment]
for debug build there is this

**Comment by benadrasni** [comment]
Right now I am not able to create bundle nor apk which covers devices for all 5 platforms. Until 3 days ago when I upload bundle to Play Store it has created APKs only for armeabi-v7a which was working for all devices. Since then it started to create APKs for all platforms, but without libflutter.so. Same problem with APK. When I create APK for armeabi-v7a I am getting this error from majority of devices: 

Issue: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/sk.ab.herbs-1/base.apk"],nativeLibraryDirectories=[/data/app/sk.ab.herbs-1/lib/arm64, /data/app/sk.ab.herbs-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libflutter.so"

and when I create APK for arm64-v8a I am getting this error from minority of devices: 

Issue: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/sk.ab.herbs-1/base.apk"],nativeLibraryDirectories=[/data/app/sk.ab.herbs-1/lib/arm, /data/app/sk.ab.herbs-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"

Am I the only one with this problem? It is kinda serious.

**Comment by softkot** [comment]
No you are not, a am also unable to publish proper flutter build supporting all the variety of devices. That will become critical when in August 2019, Play will require that new apps and app updates with native libraries provide 64-bit versions in addition to their 32-bit versions. 

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html?m=1

**Comment by PiotrWpl** [comment]
We have the same problem. Our release app is not working for devices with arm64-v8a architecture when we are using appbundle format.

**Comment by jmagman** [comment]
Only debug builds of x86 are supported on Android. Check out https://github.com/flutter/flutter/issues/9253 for details.

**Comment by iassal** [comment]
@jmagman Is there is a way to create a release app bundle with debug x86? 

So that all architectures will get release versions and x86 would get the JIT release.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/wiki/JIT-Release-Modes
