### ISSUE TITLE
GlobalObjectKey tests in global_keys_duplicated_test.dart are confusing

### ISSUE THREAD

**Issue by apaatsio** [flutter/flutter#29351]
I was looking for the tests for `GlobalKey` and I found some tests where the test name says `GlobalKey` but the test actually tests `GlobalObjectKey`. Is this a mistake in the tests or is there some logical explanation to this?

Example:
https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/test/widgets/global_keys_duplicated_test.dart#L12-L18

**Comment by markusaksli-nc** [comment]
Hi @apaatsio 
Does the explanation in the [GlobalObjectKey docs](https://api.flutter.dev/flutter/widgets/GlobalObjectKey-class.html) satisfy you?

> A global key that takes its identity from the object used as its value.

Thank you

**Comment by apaatsio** [comment]
@markusaksli-nc Not really. My issue is that the current tests don't test the GlobalKey class per se. They *assume* that GlobalObjectKey implements GlobalKey but that assumption itself is not being tested. In theory, someone could rewrite GlobalObjectKey in a way that does not implement GlobalKey and this test would still pass. I would like to see something like `expect(const GlobalObjectKey(0), isA<GlobalKey>());`. Maybe I'm being too pedantic about this.

**Comment by markusaksli-nc** [comment]
GlobalObjectKey actually extends GlobalKey

https://github.com/flutter/flutter/blob/1ad9baa8b99a2897c20f9e6e54d3b9b359ade314/packages/flutter/lib/src/widgets/framework.dart#L371
I will agree that the use of it in this test is slightly dubious, although technically completely correct. What is more confusing is the fact that the tests in this file don't really test GlobalKey duplication in most cases. Coupled with these comments: https://github.com/flutter/flutter/blob/aeedd71e8433be880b2782f7c2ab46f6dc60091c/packages/flutter/test/widgets/global_keys_duplicated_test.dart#L11-L16
Leaving this open since something might need to be changed or clarified here.

**Comment by goderbauer** [comment]
I think we can close this. a GlobalObjectKey is a GlobalKey.
