### ISSUE TITLE
flutter/textinput channel cannot be handled asynchronously?

### ISSUE THREAD

**Issue by GeertJohan** [flutter/flutter#29444]
I am working on an implementation of codecs for [go-flutter-desktop](https://github.com/go-flutter-desktop/go-flutter). In this implementation I have chosen to handle platform messages asynchronously. Based on documentation found in the Android/Java implementation, it was my understanding that the platform messages are meant as asynchronous messages. I also found that when handling the messages synchronously, a flutter application using a plugin would experience short freezes.

In my current implementation, a call by Flutter on the `platform_message_callback` that was given to `FlutterEngineRun` is returned **before** a reply is sent using `FlutterEngineSendPlatformMessageResponse`.

After implementing the codecs and creating a new plugin structure in go-flutter, I migrated go-flutters existing handling of system channels such as flutter/textinput and flutter/platform, to the new codec handlers. This caused me to find some unexpected behavior.

Three method calls on the flutter/textinput channel don't wait for a reply, and cause a racy behavior in the application. 

- TextInput.clearClient
- TextInput.setClient
- TextInput.setEditingState

The usual call order to switch input is: clearClient, setClient, setEditingState. However, because the framework doesn't wait for a reply,  they are all fired "at the same time" and the order of how they are actually handled is somewhat random. This causes input to malfunction.

For example the setClient call: https://github.com/flutter/flutter/blob/387f885481cd8441237680de0cfcd0802c0af48c/packages/flutter/lib/src/services/text_input.dart#L807

What is the correct behavior here?
Should these methodcalls not be invoked all at the same time, and instead wait for a reply in the Flutter Framework?
Or should platform_message_callback only return when a reply has been sent? But then, it's not async at all and causes freezing...??

**Comment by GeertJohan** [comment]
Related to #12196 and #21815

**Comment by GeertJohan** [comment]
I've now tried different scenarios in java plugins and deduced the following behaviours:
- A call to handle a platform message is returned immediately, and provides the Dart side with a Future immediatly.
- On the host side, in Java, the handling of a platform message is performed after the call from dart to host has returned (hence the Future in Dart), but synchrounously with other messages on the host side, and in chronological order.
- In Java, adding a Thread.sleep(..) in the onMethod handler blocks the main thread. Rendering stops and other method calls are delayed as well (since they're handled synchronously).
- I did notice that two consecutive invokeMethod calls in Dart both return a Future, before the Thread.sleep(..) in the onMethod handler in Java blocks the main thread.

Based on this, I draw the following conclusions. I would like to know if the following statements are true about the embedder and the way messaging should be implemented, so I may be able to implement this correctly.

- The call on `FlutterProjectArgs.platform_message_callback` may return immediately, before the message is handled, and before a reply is sent back to the Dart side.
- Platform messages are assumed to be handled in sync, even if the Dart side is not waiting for the reply. Therefore, the host must queue platform messages and handle them in the same order that they were received in.
- `FlutterEngineSendPlatformMessageResponse` must be called from the main thread. 
- Handling of a platform message may occur on a background thread (as long as the reply is sent to the Engine on the main thread, as per previous point).

I'm still wondering about the following:
- Must all platform messages be handled synchronously? Or is this on a per-channel basis? It would be very useful if some slow handler on a channel didn't block messages on other channels.

I hope someone with more knowledge on the engine could help me out here, or point me in the right direction. Thanks in advance!

**Comment by stuartmorgan** [comment]
I'm not the ideal person to answer, but I can give it a shot:

> The call on FlutterProjectArgs.platform_message_callback may return immediately, before the message is handled, and before a reply is sent back to the Dart side.

This is certainly true as a general statement, if I'm understanding the statement correctly. (If it weren't, there would be no reason to have a response method and a response handle; the reply would just be a return value.) I'm not actually sure what "handled" means exactly in your statement though, given that it's listed separately from both returning and calling the callback.

> Platform messages are assumed to be handled in sync, even if the Dart side is not waiting for the reply. Therefore, the host must queue platform messages and handle them in the same order that they were received in.

This question seems to conflate sync/async with ordering, so it's hard to tell what exactly the question is.

I can say in general that it's not the case that all platform message callbacks must be called in the order in which the original call was received, because it's impossible to guarantee that across an ecosystem of arbitrary third-party plugins.

An individual channel might or might not have expectations about ordering.

> FlutterEngineSendPlatformMessageResponse must be called from the main thread.

IIRC unless otherwise noted all functions in embedder.h must be called on the same thread.

> Handling of a platform message may occur on a background thread (as long as the reply is sent to the Engine on the main thread, as per previous point).

Since the response is asynchronous, and the handle is just an opaque pointer, the engine would have no knowledge of what thread(s) you are doing any logic on.

> FlutterEngineSendPlatformMessage must be called from the main thread.

See above.

> There is currently no way to obtain a reply from a method call sent by the host to the Dart side.

Yes, that's #18852

(That is, "yes" in the sense of the actual response mechanism managed by the engine, as present in the Android and iOS APIs. You can work around it manually on a per-plugin basis by having the "reply" be a new message from the Dart side, using a request ID if necessary to match up replies.)

> Must all platform messages be handled synchronously? Or is this on a per-channel basis? It would be very useful if some slow handler on a channel didn't block messages on other channels.

I think this is covered by the answers above.

**Comment by Hixie** [comment]
cc @cbracken @amirha

**Comment by GeertJohan** [comment]
Thanks a lot for these answers! It helped me to implement the platform message system correctly in go-flutter.

Perhaps these definitions and "rules" should be properly documented somewhere, so others have less trouble discovering them? Otherwise this issue can be closed as far as I'm concerned.

**Comment by stuartmorgan** [comment]
I think the only rule in what I listed was the threading requirement; I've added a note about that to the existing bug about improving embedding documentation.
