### ISSUE TITLE
[Suggestion] List.map should return a List instead of a Iterable

### ISSUE THREAD

**Issue by Larry-Liu2016** [flutter/flutter#29485]
Currently, the map() method of a List object returns an Iterable. If a List is expected, then .toList() method has to be called, otherwise an Exception 'Iterable is not a subtype of type List' will be thrown.

From my experience with Flutter so far, when I map a list, I would always want to get a list(usually a list of Widget as children for a Row or Column). Therefore, typing .toList() every time feels like totally unnecessary boilerplate. It makes the code look more complicated, and could cause confusion/surprises to those who are not familiar with the quirks of Dart. [https://medium.com/@esplo/be-careful-to-iterable-in-dart-3c42bfe00625](url)

Why not make List.map just returns a List? That would make our lives just a little easier :)

**Comment by jonahwilliams** [comment]
The advantage of making `map` return an `Iterable` is that it is lazy, and that is more efficient if you are chaining multiple methods. For example, the following code will never create any more lists, nor will it traverse the iterable more than once.

```
List<int> xs = ...
xs
  .map((x) => x + 1)
  .where((x) => x.isEven)
  .forEach(print);
```

Ultimately, this was a decision made by the Dart language since `List` is part of the SDK, and its not something that Flutter can or should change.
