### ISSUE TITLE
Please add Crashlytics fatal crash support

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter#29689]
Currently the Crashlytics plugin is limited to only report non-fatal reports. It would be nice to have the ability to report fatal reports as well.

**Comment by jaumard** [comment]
The issue here is that the native crashlytics libraries doesn't let you specify if the crash is fatal or not, so all the one you report manually are tagged as non fatal. Would be nice if the crashlytics libraries allows us to specify this. I understand that it will need synchronization with the crashlytics team to do that, but that was the point of #14765 to do it :)  
So here I'm not sure it's the same feature as the one you describe as normally the ability to report fatal reports (meaning native crashes) should already be available on the PR you did.

**Comment by kroikie** [comment]
@jaumard the idea was to provide official support for Crashlytics. We are working on fatal reporting integration which as you mentioned requires work with the Crashlytics team but we did not want that work to totally block the publishing of an official plugin.

**Comment by jaumard** [comment]
Sure no problem @kroikie :) just wanted to be sure it was still the plan ^^ 
Thanks !

**Comment by audkar** [comment]
Can you make a friendly ping to Firebase team from time to time regarding this issue? These are actual hard limitations for productions apps. No serious company will release product on platform where no crash reporting tool available which:
- Reports issues as they happen (limitation of non-fatal issues on Firebase)
- Has capability to deobfuscate crash reports.

**Comment by shhh9** [comment]
Exactly as @audkar said. In order for Flutter to be production-ready, all these basic logging and reporting requests should be of high priority to the team. Proving production-grade features is the best way to drive up Flutter adoption and show its potential.

**Comment by audkar** [comment]
Working crash reporting service was most requested ticket on Flutter repository. It was closed as solved... which is obviously not the case. Real projects requires service which correctly tracks issues in app. There is none for Flutter and community can't do much here. 
@eseidelGoogle mentioned in [comment](https://github.com/flutter/flutter/issues/14765#issuecomment-389288254) that flutter team started talking about this issue with Firebase team two years ago, but seems no progress was made since then.
This is so bad and sad that any crash tracking service doesn't have real support for Flutter.

**Comment by eseidelGoogle** [comment]
I've reached out to the team again last week, they had a lot on their plates last time we talked.  You're also welcome to submit a direct request via the various Crashlytics/firebase support channels.  I'm sorry I don't have a better answer at this time, but I'll keep asking.  FYI @csells @shobhitchugh

**Comment by froesmatheus** [comment]
Any news on this?

**Comment by kroikie** [comment]
@kroikie

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/398. Any further collaboration will be done there.
