### ISSUE TITLE
flutter build release big apk file

### ISSUE THREAD

**Issue by mohammedalwusool** [flutter/flutter#29741]

**Comment by mohammedalwusool** [comment]
how to get reduce apk file during build release

**Comment by tomalabaster** [comment]
How big is it? Are you using many packages? Are you using many binary assets? Are you building using `flutter build apk --release`?

**Comment by mohammedalwusool** [comment]
the apk size about 25 mb
i using 7 packages all of them important to my app
i used flutter build apk --release

**Comment by mohammedalwusool** [comment]
color: any
  fit_image: "^0.1.2"
  http: ^0.12.0+1
  cached_network_image: ^0.5.1
  font_awesome_flutter: 
  flutter_launcher_icons:
  flutter_inappbrowser:  
  pdf_viewer_plugin: ^0.0.5
  path_provider: ^0.4.0+1
  flutter_spinkit: ^3.1.0 
  uuid:

just use above packages in simple project don't use it just include it and build release apk see how big will be

**Comment by tomalabaster** [comment]
@mohammedalwusool right now, with Flutter version 1.3.8, the empty project is 4.9MB.
Adding in all of your packages brings it to 23.6MB.
If you remove `pdf_viewer_plugin`, it takes it down to 6.5MB. 

I can't really see how this is an issue with Flutter, I'd raise the issue with the creator of the `pdf_viewer_plugin`, and then close this issue here.

**Comment by mohammedalwusool** [comment]
is there any staple pdf viewer i can use instead of pdf_viewer_plugin

**Comment by tomalabaster** [comment]
Have you tried the `url_launcher` plugin? I've used this to show PDFs before.
