### ISSUE TITLE
Determine why platform messages and responses are happening when not attached.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#29757]
Determine the root cause of:
#28651

Changes were made to avoid crashing the app when platform messages are sent or responded while C++ is not attached.  But this shouldn't happen.  Find out why it is and what we can do about it.

**Comment by joshuaferguson** [comment]
https://github.com/flutter/flutter/issues/28651#issuecomment-475375704

I believe the above referenced comment on the #28651 issue is related to this. This appears to happen when the device goes idle, and appears to be happening more on older hardware (As mentioned in the bug, I'm seeing this most on 32bit builds for the SM-T377V and SM-P600 that most of our users use).

**Comment by matthew-carroll** [comment]
@jason-simmons do you think it's possible that the bug you just fixed internally is also the root cause of this issue?

**Comment by jason-simmons** [comment]
That bug would cause Dart->Java messages to be dropped at a time when the FlutterNativeView was still alive.  This issue looks like it involves Java->Dart messages.

**Comment by joshuaferguson** [comment]
So here's what I'm seeing and what I've been able to glean from the logs since rolling the latest code from Master:

After a certain amount of time, my app will always return to its initial login screen. It's hard to discern from the logs exactly what's happening because it doesn't seem to be happening from anywhere within my code (it is, after all, only happening when idle). These are the lines that stand out to me just looking at the logcat entries related to my PID:

First sign of trouble:
```
03-22 15:09:00.823 2767-25229/? W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[24,tid=25229,Native,Thread*=0x97c73400,peer=0x12f060a0,"Thread-11779"]
```
...
```
03-22 15:09:01.086 2775-3549/? D/InputDispatcher: Focus left window: 2767
```
...
```
03-22 15:09:01.156 2767-2767/? D/PhoneWindow: *FMB* installDecor mIsFloating : false
03-22 15:09:01.156 2767-2767/? D/PhoneWindow: *FMB* installDecor flags : -2139029248
```
...
```03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: Trying to get library list
03-22 15:09:01.261 2767-2767/? E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: Library list: ""
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: First attempt to load libs
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: Trying to init OpenCV libs
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: Trying to load library opencv_java3
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: Library opencv_java3 loaded
03-22 15:09:01.261 2767-2767/? D/OpenCV/StaticHelper: First attempt to load libs is OK
03-22 15:09:01.266 2767-2767/? I/OpenCV/StaticHelper: General configuration for OpenCV 3.4.1 =====================================
...
03-22 15:09:01.266 2767-2767/? I/OpenCV/StaticHelper: -----------------------------------------------------------------
```
... Then these lines indicate it's returned to the login screen:
```
03-22 15:09:01.436 2767-9927/? I/flutter: new UploadModel created
03-22 15:09:01.436 2767-9927/? I/flutter: new OrderModel created
03-22 15:09:01.436 2767-9927/? I/flutter: new PinModel created
``` 
Then I get some other sporadic messages that may or may not be related, and then about 100 of these in a row:
```
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
03-22 15:09:03.516 2767-2767/? D/FlutterNativeView: FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_messaging
```
...
```
03-22 15:09:03.551 2767-2767/? W/FlutterJNI: Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 5
```

I know some of this may be random noise, but I have no other way to debug why or where this might be occurring. If you'd like, I can send the entire log around the time of the "crash" (not really a crash? reset? error? whatever.)

**Comment by matthew-carroll** [comment]
@joshuaferguson it looks like the engine roller has yet to pick up Jason's change into the framework.  Can you do me a favor and test your situation again once the following commit has rolled into the framework?

https://github.com/flutter/engine/commit/68bd4f2c6479c19a4e4af6574db45900fcade346

Jason mentioned that it probably won't help, but I'd like to be sure before we dig further.

**Comment by joshuaferguson** [comment]
Good news and bad news. I did manage to figure out the cause and a local fix! However, I think there may need to be a fix on the flutter side as well. The device could consistently reproduce the crash on still crashed with this latest engine roll - flutter/engine@68bd4f2 looks like it was rolled in a few days ago. However, when looking at the logs I noticed when I set it to verbose it was getting bombarded with messages relating to the SIM card in the device. The SIM card is deactivated because it's a device we use exclusively for testing, so I tried removing the SIM card and lo-and-behold no crash. 

I'm going to proffer a theory - I noticed that other people reporting similar crashes were referencing a geo-location plugin, which our app doesn't make use of - but we do use Firebase and the Firebase plugins report back geo-location data (the streaming view in the Firebase console shows where user events are being generated), so while our app isn't directly requesting any location data, Firebase is accessing it in the background. 

The reason I bring this up is that any geo-location data is obviously going to try to narrow location data by cell first, and use wifi location data as a fallback, so there may be some interaction between Firebase trying to log system/user events and the device not properly reporting back the deactivated sim. I did notice that when trying the same test in Chrome (obviously not a Flutter app, and a first-party Google app), there was no crash or noticeable effect when running the same idle test. 

I hope that helps provide some context for reproducing the issue (try on a device with cellular capabilities but a deactivated SIM). Even though the majority of our users will probably NOT be using a device with a deactivated SIM, and if they ARE then we have a workaround (remove the SIM), we will still be waiting for a fix or workaround for this situation, or at least confirmation from you guys before shipping, so it's still a high-priority issue for us. It doesn't reflect well on us to have to respond to any user writing in about our app being unstable, and we can't rely on release notes to tell users to remove their SIM cards if they're deactivated ;). 

Thank you for your attention and quick turnaround on this issue, I really appreciate it! Hopefully we're close to a full fix!

**Comment by matthew-carroll** [comment]
Thanks @joshuaferguson 

So you're still seeing the problem on master as of today?

You mentioned a local fix.  Can you share details of that fix?

**Comment by joshuaferguson** [comment]
The fix was removing the SIM card from the device completely.

**Comment by joshuaferguson** [comment]
And yes, it's still occurring on today's master channel.

**Comment by matthew-carroll** [comment]
Ok, I'll see if I can repro with a SIM on our end.  Thanks.

**Comment by joshuaferguson** [comment]
We are using a Samsung SM-T377V w/ a deactivated SIM. Simply leaving it idle for a few minutes should reproduce it. I do have it configured to never fully go to sleep for testing purposes. I'm not sure if that matters. Thanks!

**Comment by joshuaferguson** [comment]
Any update on reproducing this issue?

**Comment by matthew-carroll** [comment]
I haven't had a chance to try it yet, but it's on my TODO list.

**Comment by joshuaferguson** [comment]
We are currently trying to decide whether to release with this as a known issue or wait for a fix. I know it's a very specific scenario but one that's not out of the ordinary when 97% of our customers use cellular-enabled tablets. Any idea when this might get looked at? Should we wait on this or move forward with a release on the current master branch?

**Comment by matthew-carroll** [comment]
@joshuaferguson I just obtained a sim card and I'm ready to try to repro.  Unfortunately we don't have any sim tablets, so I'm gonna have to try to repro on a phone.

Would you mind sending or posting a minimal source code repro of the issue?

**Comment by joshuaferguson** [comment]
If it helps, I was able to reproduce it with this app: https://github.com/krolmic/recipes_app - I was looking for a simple app that incorporated Firestore and Firebase Auth. This meets the bill. You'll see this occur if you let the app site for a certain period of time - it may require setting the tablet to never go to sleep - this is when I notice it crashing back to the first page of the app.

**Comment by matthew-carroll** [comment]
Thanks I'll give that a try as soon as I can.

It sounds like you're pretty confident that this issue is specific to the Firebase plugins.  Is that correct?  Or have you witnessed this issue occur with non-Firebase plugins as well?

**Comment by joshuaferguson** [comment]
I have not tested it with other non-Firebase projects - the reason I assumed it was related to Firebase is because there seemed to be a lot of GPS-related errors with the SIM card in logcat. Firebase is the only plugin in our app that actively uses location data to send back usage statistics to Firebase; we don't call or use any location services at all in our app directly. It may be coincidental, but it seems to make some sense?? Maybe?

**Comment by joshuaferguson** [comment]
Any progress on this issue?

**Comment by matthew-carroll** [comment]
A few other issues have come up that I need to resolve first. No progress yet.

@tvolkert if anyone else has any free cycles, repro'ing this issue would be helpful.

**Comment by amreniouinnovent** [comment]
Could not send. Channel: plugins.flutter.io/connectivity_status. Response ID: 0
Still in FLutter 1.12.13 hotfix 5

**Comment by KrishnaPravin** [comment]
We are using firebase_messaging_plugin.
FlutterJNI is properly attached for the first time when the app is opened or when the app is force stopped and opened.
But FlutterJNI is not attaching to the platform when the app is resumed after

The app is minimized using either back or home button/gesture
The app cleared from the recent apps tray
Background messages are received properly when the app goes to the background for the first time.
Due to this issue when the app goes to the background for the second time onwards background messages are not received.

I guess there is a problem is removing the FlutterJNI and reattaching it to the platform.

**Comment by inceptusp** [comment]
I don't know if it helps, but I am receiving the same issue alert from crashlytics and all occurs on Samsung phones... A Galaxy J2 and a Galaxy Grand Prime Plus... I'm developing our app on a Galaxy J6 but I'm pretty sure that I have not faced this issue on my phone yet, but some clients are...

My app uses firebase analytics/crashlytics and cloud message, besides geolocalization (which seems to be causing the problem as stated by @joshuaferguson in his theory)...

I'm on Flutter release as our app is in production right now...

From Crashlytics:
`Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative()
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable()
       at io.flutter.embedding.engine.h.a.a()
       at io.flutter.embedding.engine.h.a.a()
       at io.flutter.embedding.engine.h.a$b$a.onFrameAvailable()
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Queue`

**Comment by VadPinchuk** [comment]
Is this issue still not fixed? 
I have faced the same one in plugin

Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/charging. Response ID: 0

**Comment by MisterJimson** [comment]
I'm also seeing this in the logs when working on a plugin, however its not causing me any issue I can see.

**Comment by markfili** [comment]
I'm also seeing this message after I exit the app that uses the `sensors` plugin. Plugin's stream of accelerometer events is passed to the StreamBuilder in a StatefulWidget. I don't see any issues but I am afraid that it will drain the battery even after the app is terminated.

**Comment by xster** [comment]
Merging back into #28651 which is still an issue.

**Comment by joelbrostrom** [comment]
> I'm also seeing this message after I exit the app that uses the `sensors` plugin. Plugin's stream of accelerometer events is passed to the StreamBuilder in a StatefulWidget. I don't see any issues but I am afraid that it will drain the battery even after the app is terminated.

I stil have issues with this as well.
