### ISSUE TITLE
Mulit click issue

### ISSUE THREAD

**Issue by wuxuan2811** [flutter/flutter#29789]
When I click  button1 and did't touch up, another click   button2 down and up.
Unfortunaly, button2 work.
How can I do to solve the situation in global project

**Comment by justinmc** [comment]
I think you're talking about touching and holding on button 1, meanwhile tapping button 2 with another finger.  In that case, I see that both Flutter and native Android register the tap on button 2.

What do you expect to happen?  Can you provide a sample app that demonstrates the problem?

**Comment by wuxuan2811** [comment]
I wish tapping button2 is not work when I hold on button1.
Another, what can I do if tap button1 an button2 at same time.I don't wish both work

**Comment by justinmc** [comment]
I'm going to close this because Flutter seems to behave the same way that both native iOS and Android do for both of your cases.

However, it's probably possible to create the behavior that you want manually in Flutter.  If you want really fine grained control over the tap events that happen to your buttons, you could try wrapping them in [GestureDetectors](https://docs.flutter.io/flutter/widgets/GestureDetector-class.html).  Then you could use `onTapDown` and `onTapUp` to set and unset a flag that prevents other buttons from being pressed.

**Comment by wuxuan2811** [comment]
I try the both way:
1. "android:splitMotionEvents=”false”"
2.<style name="MyStyle">
      <item name="android:windowEnableSplitTouch">false</item>
      <item name="android:splitMotionEvents>false</item>
</style>
Howerver, it doesn't work in flutter through android native. @justinmc
