### ISSUE TITLE
If something goes wrong while running flutter test on a mac it leaves behind SkyShell processes in the dock

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2987]
Even now I have three SkyShell processes sitting in my dock even though it's been ~ an hour since I last ran flutter test.  Also, during flutter test you see tons of SkyShell instances launching and closing in the dock.  Beautiful but weird.

**Comment by eseidelGoogle** [comment]
To hide from the dock we can set LSUIElement=0 in the Info.plist to not appear in the dock: https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256

That won't be the behavior you'll want when you're running non-headless, but I'm not sure it's configurable at runtime.  @chinmaygarde 

But the real bug is that these processes get left around, which is likely a bug in our usage of package:test.  @devoncarew

**Comment by eseidelGoogle** [comment]
I don't think this is still an issue?  @chinmaygarde @cbracken.  Speculatively closing.

**Comment by chinmaygarde** [comment]
No. This is no longer an issue.
