### ISSUE TITLE
{@inject-html} showing up in generated dart docs

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#29919]
![image](https://user-images.githubusercontent.com/1227763/54937866-83a95980-4ee2-11e9-90e6-7b37f78b3328.png)

On https://master-api.flutter.dev/flutter/foundation/BindingBase/registerServiceExtension.html

/cc @gspencergoog @jcollins-g

**Comment by markusaksli-nc** [comment]
Still there on latest master `1.21.0-6.0.pre.117`.
[registerStringServiceExtension](https://api.flutter.dev/flutter/foundation/BindingBase/registerStringServiceExtension.html), [registerNumericServiceExtension](https://api.flutter.dev/flutter/foundation/BindingBase/registerNumericServiceExtension.html), [initServiceExtensions](https://api.flutter.dev/flutter/widgets/WidgetsBinding/initServiceExtensions.html), [registerSignalServiceExtension](https://api.flutter.dev/flutter/foundation/BindingBase/registerSignalServiceExtension.html), [registerServiceExtension](https://api.flutter.dev/flutter/foundation/BindingBase/registerServiceExtension.html), and [registerBoolServiceExtension](https://api.flutter.dev/flutter/foundation/BindingBase/registerBoolServiceExtension.html). They are all in [binding.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/binding.dart). Should this be fixed by #2274 @srawlins?
Thank you

**Comment by goderbauer** [comment]
This is a dupe of https://github.com/dart-lang/dartdoc/issues/1945 and will be fixed with the next release of dartdocs.
