### ISSUE TITLE
Error with my dropdown  (class, button)

### ISSUE THREAD

**Issue by rslimm** [flutter/flutter#30144]
Hello,
I'm new on Flutter and I'm now working on my first app concerning our project at school . then on one of my page, I'd like to let appear more than one Dropdown button, but as you can see my code, I got this error:
 DropdownMenuItem<dart.core::String>' can't be assigned to the parameter type '(dynamic) → dynamic'.

Please HELP ME :(

`![1](https://user-images.githubusercontent.com/47043823/55198166-344e7c00-51b5-11e9-900e-92ff4a788d7e.jpg)

`import 'package:flutter/material.dart';

class DropDown extends StatefulWidget {

  @override
  _DropDownState createState() => _DropDownState();
}

class _DropDownState extends State<DropDown> {

  // Here we're going to define the LIST

  List _colors = ["","red","green","blue","orange"];
  List _dogs = ["","muff","rover"];
  List _people = ["","mum","dad","sister","brother"];

  // End
  var resultsList = new List.filled(3, "");

  @override
  void initState(){
    // Here we're going to set the initial values

    resultsList[0] = "red";
    resultsList[1] = "muff";
    resultsList[2] = "mum";

    return super.initState();
  }

  // Here we're going to create the method which will build and update the dropDown menu

  _fieldDropDown(List theList, int resultPosition, var dbField) {

    return new FormField(

      builder: (FormFieldState state) {

        return InputDecorator(

          decoration: InputDecoration(),

          child: new DropdownButtonHideUnderline(

            child: new DropdownButton(

              value: this.resultsList[resultPosition],

              isDense: true,

              onChanged: (String newValue) {

                setState(() {

                  this.resultsList[resultPosition] = newValue;

                  state.didChange(newValue);

                  print(

                      'The List result = ' + this.resultsList[resultPosition]);

                  //write newValue to a database field, which can be used in the override init to set the field originally

                });

              },

              // Comment to remove Error

              items: theList.map((String,  value) {

                return new DropdownMenuItem(

                  value: value,

                  child: new Text(value),

                );

              }).toList(),

            ),

          ),

        );

      },

    );

  }

  @override
  Widget build(BuildContext context) {

    return new Scaffold(

      appBar: new AppBar(

        // title: new Text(widget.title),

      ),

      body: new SafeArea(

          top: false,

          bottom: false,

          child: new Form(

            //key: _formKey,

              autovalidate: true,

              child: new ListView(

                padding: const EdgeInsets.symmetric(horizontal: 16.0),

                children: [

                  //create some fields, hand in the list

                  _fieldDropDown(_colors, 0, 'colorDBfield'),

                  _fieldDropDown(_dogs, 1, 'dogDBfield'),

                  _fieldDropDown(_people, 2, 'peopleDBfield'),
                ],
              ))),
    );
  }
}`

**Comment by tomalabaster** [comment]
This is a question for Stack Overflow.

However, you're getting the error because the `onChanged` property on the `DropdownButton` wants a method which takes a parameter of a `dynamic` type, but you're giving it a method with a `String` type. So either remove the type declaration `String` from the method you're giving the `onChanged` property or change `String` to `dynamic`.

Same for the `theList.map` method. Because your `theList` property is declared as a parameter `List theList`, the type of `theList` is in fact `List<dynamic>` so the `theList.Map` method is expecting a method argument that takes a `dynamic` type, not a `String` type.

So your lines should be changed to `items: theList.map((dynamic  value) {` and `onChanged: (dynamic newValue) {`. Although at this point you may as well do without the `dynamic` keyword anyway.

Regardless of whether or not this solves your issue, can you please close this and if I haven't explained this clearly enough, ask it on Stack Overflow instead and someone else will likely pick it up and explain it better.

**Comment by rslimm** [comment]
Thank you so much sir, I did it and it's works... thank you sir :)

**Comment by tomalabaster** [comment]
No problem, glad to hear! You can close this issue now.
