### ISSUE TITLE
Emoji problem

### ISSUE THREAD

**Issue by amervelic** [flutter/flutter#30186]
Why emoji "switched"?
![Screenshot_20190329-130303](https://user-images.githubusercontent.com/19406255/55231745-d4db8500-5223-11e9-9c8f-4f4e6cb46f20.png)

**Comment by TahaTesser** [comment]
Hi @amervelic 
Emojis input seems to be consistent on latest Stable.
As this issue is old and it would be better to have new information on newer version of Flutter and device related information if it is device specific..
If you're still experiencing this issue, please create a new issue and provide the information required in the template.
Thank you
