### ISSUE TITLE
Test case interrupt the upgrade progress

### ISSUE THREAD

**Issue by wanwusangzhi** [flutter/flutter#30233]
## Steps to Reproduce
1. When I run 'flutter channel' and upgrade packages, the test cast interrupt the upgrade progress. 
2. channel -> master 2e637d830..89807e68d   2019/03/30

## Logs
```
file:///flutter/packages/flutter_tools/lib/src/commands/test.dart:102:27: Error: The argument type 'Future<Set<DevelopmentArtifact>>' can't be assigned to the parameter type 'Set<DevelopmentArtifact>'.
 - 'Future' is from 'dart:async'.
 - 'Set' is from 'dart:core'.
 - 'DevelopmentArtifact' is from 'package:flutter_tools/src/cache.dart' ('file:///flutter/packages/flutter_tools/lib/src/cache.dart').
Try changing the type of the parameter, or casting the argument to 'Set<DevelopmentArtifact>'.
    await cache.updateAll(requiredArtifacts);
                          ^
Process finished with exit code 254
```
so i open the file of 'test.dart' and to delete the follow line code 
(file path:  xxx/flutter_tools/lib/src/commands/test.dart)
```
  @override
  Future<FlutterCommandResult> runCommand() async {
//    await cache.updateAll(requiredArtifacts);
  ...
```

```
```

**Comment by jonahwilliams** [comment]
Hi, unfortunately that change was commited without syncing, causing the aforementioned problem. It has since been reverted at https://github.com/flutter/flutter/commit/c10e7ba6e9087478e5c7a277304d1e4a3dedc7fa.

If you're going to work off master branch, I recommend checking the build status at https://flutter-dashboard.appspot.com/build.html before upgrading.

**Comment by wanwusangzhi** [comment]
thanks
