### ISSUE TITLE
WebView does not load in iOS if navigationDelegate prevents navigation. 

### ISSUE THREAD

**Issue by joaquinrok** [flutter/flutter#30256]
On iOS, the `WebView` calls the its `navigationDelegate` when loading the `initialUrl`, meaning that if the `navigationDelegate` always returns `NavigationDecision.prevent`, the `WebView` never loads the `initialUrl`. 

On Android, the `navigationDelegate` is **not** called at the beginning so the `WebView` gets to render the `initialUrl` successfully and then prevents any further navigation.

## Steps to Reproduce
using: `webview_flutter: ^0.3.0`
set: `<key>io.flutter.embedded_views_preview</key><string>YES</string>`

Example project to reproduce the problem:
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var initialUrl = "https://github.com/flutter/";
    return Scaffold(
        body: WebView(
      initialUrl: initialUrl,
      navigationDelegate: (navigationRequest) {
        print(navigationRequest.url);
        return NavigationDecision.prevent;
      },
    ));
  }
}
```

### Workaround
To make iOS show the same behavior and Android:
```
navigationDelegate: (navigationRequest) {
        return navigationRequest.url == initialUrl ? NavigationDecision.navigate : NavigationDecision.prevent;
      },
```

My flutter doctor log:
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.2.1 at /Users/user/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • ONEPLUS A3003    • 323768cd                  • android-arm64 • Android
      8.0.0 (API 26)
    •iPhone • 00008020-0014442C3E01002E • ios           • iOS 12.1.4
```

**Comment by kritikaperiwal12** [comment]
I am showing SVG in WebView and also set the functionality of zoom in/out the WebView. It is working fine. But when user zoom in the webView and on tap button for reloading the webView then, in this case, webView content is hidden and after scrolling to top the content will display. How can I adust the scrollView height of webView?

**Comment by Smarto-Dev** [comment]
facing the same problem @zoechi any work aroid, webview is working on android ut in loading view on ios

**Comment by escamoteur** [comment]
@joaquinrok It's not clear to me which would be your desired behavior, I guess you want it to be like on iOS but your issue title suggests that the problem lies in iOS.
Does the problem still exists with the latest version of web_view ?

@kritikaperiwal12 Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

**Comment by neokree** [comment]
@escamoteur This problem still exist with the latest version of web_view. I'm using `0.3.15+1`.

I think @joaquinrok request is about changing when `NavigationDelegate` is called on iOS. 
Since the name contains "Navigation" it is assumed that it would only be called when the `initialUrl`'s page navigate somewhere else. 

However in iOS the callback is used also to load `initialUrl`, causing developers (like me) to think that the plugin do not work because it shows a blank page.

The fact that no warning or errors are showed in console also promotes this idea, while the plugin is simply working correctly.

Some way to resolve the issue could be: 
- Internally check if the link that is called is the initial one and do not call NavigateDelegate for him
- Document this behaviour on the NavigationDelegate declaration doc
- Document this behaviour on the pub.dev plugin page

**Comment by escamoteur** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by ruturajchavda182** [comment]
Add this in your info.plist
<key>io.flutter.embedded_views_preview</key>
<string>YES</string>

**Comment by ISLEMNEDDAR** [comment]
this problem still happend in IOS, we have different behaviour in Android and ios platform:
in android the request is fired when we click on the web view on url,
in ios all the urls can fire the navigationDelegate any solution to have the same behaviour in ios as in andorid ?
