### ISSUE TITLE
RadioListTile inconsistent behaviour during deselection

### ISSUE THREAD

**Issue by gtrochimiuk** [flutter/flutter#30311]
## Summary
RadioListTile can be selected by tapping the title or radio control widget. It can be deselected (by changing the `groupValue` to `null` in `onChanged` callback) only by tapping the title. Tapping the radio control widget when it is selected does not trigger the callback.

The `onChanged` callback in the `Radio` class is not called when the radio is being deselected.
Callback handler implementation from the `Radio` class:
```
void _handleChanged(bool selected) {
  if (selected)
    widget.onChanged(widget.value);
}
```
Is it desired behaviour **not** to call `onChanged` when the value **changes** to `false`?
That seems counterintuitive to me and it causes inconsistency with how `onChanged` callback works in `RadioListTile` class.

## Steps to Reproduce

Small app to reproduce the issue:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyPage(),
  ));
}

class MyPage extends StatefulWidget {
  @override
  _MyPageState createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  List<int> values = [1, 2, 3];
  int selectedValue;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: values.length,
        itemBuilder: (BuildContext context, int index) => RadioListTile(
              onChanged: _onChanged,
              value: values[index],
              groupValue: selectedValue,
              title: Text(values[index].toString()),
            ),
      ),
    );
  }

  _onChanged(int value) {
    setState(() {
      selectedValue = value == selectedValue ? null : value;
    });
  }
}
```

1. Tap on one of the values to select it
2. Tap on the radio control - the value is not deselected
3. Tap on the title - the value is deselected

## Flutter doctor
```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.3.8 at /Users/gtrochimiuk/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gtrochimiuk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by shihaohong** [comment]
I agree that this is an inconsistency. I'll look into a fix that prevents tapping a selected `TileList` to deselect the `Radio`, since that is more consistent with how Radio buttons should operate

**Comment by gtrochimiuk** [comment]
I appreciate you taking the time to fix this issue. Unfortunately the way you fixed the inconsistency is basically the opposite of what I hoped for. 

In my use case users are filling a questionnaire inside the application. One of the possible types of questions is what we call "single choice question", in which users select one option from a set of possible answers. If answer for that question is not required I want to allow users to uncheck the option they selected.

In my understanding the most natural way to implement this behaviour is to use radio buttons - which I can't do if my callback is not called.

I believe that it would be a better solution to change the `Radio` class to call the `onChanged` callback regardless of whether the radio was selected or deselected.

If you decide that this use case is not valid for radio buttons, then I propose to rename the callback from `onChanged` to something like `onChecked` or `onSelected`, since `onChanged` implies that it will be called on every state change, not only when the state changes to checked.

**Comment by shihaohong** [comment]
Thank you for the feedback, I really appreciate the thought you put in explaining your situation. I currently see two different points to be made based on your suggestions: 

### Allowing deselecting radio buttons on tap
Originally, I was in the same boat as you as well and was thinking that it would be a better solution to just allow the radios to be deselected on tap, since that would be the more flexible approach. 

After doing some digging into why radio buttons are typically implemented the way they are (aka not allowing you to deselect), the justification for my choice was to have RadioListTile behave consistently with how it's typically seen elsewhere to not cause any potential confusion to users. Here is an example of a Stack Overflow [thread](https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs) that I looked at.

### Updating the name of the onChanged parameter to onChecked/onSelected
I agree that this would be a much more intuitive name for the parameter, since its name implies that it will be called on when the state changes to checked. I see two possibilities here:
1) Keep onChanged. This causes the least amount of pain for Flutter developers, since it would only cause a breaking change to users with your use case
2) Switch to onSelected/onChecked. This would cause a breaking change for every existing developer using the RadioListTile, since their parameter name would have to be updated in their codebase.

Currently, I'm of the opinion that:
1) We should not allow deselecting of radio buttons when tapped to ensure consistency with other ecosystems like the web.
2) We should keep the parameter name to onChanged to prevent massive breakage, _but_ include some clear, concise documentation to clarify this behavior.

I'll spend some time thinking more about this before sending out a breaking change announcement and implementing this change, but definitely please share more thoughts and concerns you may have about this.

**Comment by gtrochimiuk** [comment]
Thank you for explaining your thought process.

It never occurred to me that users expect not being able to deselect a radio button. Personally I am not a fan of keeping standards that limit flexibility, but I can understand that you want radio buttons behaviour to be inline with how they behave in other systems. This is not that big of a deal for my application, I can always create an "AlmostRadio" widget :)

Regarding changing the name of the `onChanged` parameter I agree that it is not worth it to force all developers to update their code for this, but an update to the documentation is most welcome.

**Comment by shihaohong** [comment]
Sounds good! Once again, thank you for the feedback. I'll be creating another issue to track updating the docs for a clearer `onChanged` description, since it seems that `Radio` does not highlight this behavior either.

**Comment by Cvilia** [comment]
But When I set many RadioListTile in Row ,then ,anything visible.However,Column is OK
