### ISSUE TITLE
MediaQuery.of(context).orientation incorrect value

### ISSUE THREAD

**Issue by bnayagrawal** [flutter/flutter#30356]
I am using OrientationBuilder widget Inside a stateful widget. Inside that builder function, I check whether the screen is in portrait mode or landscape mode. 

`bool isInPortraitMode = MediaQuery.of(context).orientation == Orientation.portrait;
`

I ran my app in debug mode and rotated my device many times to check the boolean value and found that sometimes even if the device is in landscape mode it says its in portrait mode.

**Comment by MarcoTTC** [comment]
I can confirm this bug is present on the stable 1.2.1 version of the Flutter framework. Until this bug is fixed, my recommendation is to use the MediaQuery.of(context).orientation variable, instead of using the orientation parameter from the OrientationBuilder widget. Using the full request command always yield a correct value.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
