### ISSUE TITLE
Engine roll regressed many benchmarks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#30404]
https://github.com/flutter/flutter/pull/30337 regressed the following benchmarks:

flutter_gallery__transition_perf average_frame_rasterizer_time_millis
flutter_gallery__transition_perf 90th_percentile_frame_build_time_millis
flutter_gallery__transition_perf 99th_percentile_frame_build_time_millis
flutter_gallery__transition_perf_with_semantics delta_average_frame_build_time_millis
flutter_gallery__transition_perf_with_semantics delta_90th_percentile_frame_build_time_millis
flutter_gallery_ios32__transition_perf average_frame_build_time_millis
flutter_gallery_ios32__transition_perf 90th_percentile_frame_build_time_millis
flutter_gallery_ios__transition_perf average_frame_build_time_millis
flutter_gallery_ios__transition_perf  90th_percentile_frame_build_time_millis
cull_opacity_perf__timeline_summary average_frame_build_time_millis
cull_opacity_perf__timeline_summary 90th_percentile_frame_build_time_millis
complex_layout_semantics_perf initialSemanticsTreeCreation
microbenchmarks stock_build_iteration
microbenchmarks_ios stock_build_iteration
microbenchmarks stock_layout_iteration
microbenchmarks_ios stock_layout_iteration
microbenchmarks stock_animation_subsequent_frame_average
microbenchmarks_ios stock_animation_subsequent_frame_average

**Comment by johnsonmh** [comment]
Just pulling in communications from different channels into here: 

* The engine roll in question contained only a [dart_lang -> engine roll](https://github.com/flutter/flutter/pull/30337).
* The currently suspected culprit changes are https://github.com/dart-lang/sdk/commit/a062221b763deeffedd5b80af7a3d63a226ec0d7 and https://github.com/dart-lang/sdk/commit/94362f1af0f21455e723d1c53bc3953c830ccb6f
* Both of these commits were temporarily reverted in https://github.com/dart-lang/sdk/commit/49c94d3600db7e572d97f4cab06c66c013f79b77
* Both commits were then re-landed in dart-lang in https://github.com/dart-lang/sdk/commit/d63d0b4bcdda09caef6ebb6c173d9aa165e32ade

Next steps are `dart_lang` -> `engine` roll then `engine` -> `framework` roll.

@bkonyi, since you relanded the two `dart_lang` commits, are we confident that the regressions are fixed at ToT, or is the intention that we only roll the `dart_lang` -> `engine` at the [temporary revert](https://github.com/dart-lang/sdk/commit/49c94d3600db7e572d97f4cab06c66c013f79b77)?

**Comment by a-siva** [comment]
We haven't yet resolved it the temporary revert did not help because there was another change on top of tree that broke the engine build, I believe we have a fix for that but the temporary revert has to be repeated again tomorrow to figure out if they caused the perf regression.

**Comment by johnsonmh** [comment]
Ah I see, thanks for the update, so we're still searching for the culprit change(s). Tomorrow after https://github.com/dart-lang/sdk/commit/a062221b763deeffedd5b80af7a3d63a226ec0d7 and https://github.com/dart-lang/sdk/commit/94362f1af0f21455e723d1c53bc3953c830ccb6f are successfully reverted, we will verify that they're the source of the perf regression.

Only then will we move forward with `dart_lang` -> `engine` roll.

**Comment by mraleph** [comment]
I think benchmark recovered at https://github.com/flutter/flutter/commit/3c9ffbca47fadaf43f74d8262cd3e8f5159cd10e which is pretty much in line with what we see on Golem. 

Can you confirm this?

**Comment by mraleph** [comment]
The actual culprit is dart-lang/sdk@3fd124db1f

**Comment by dnfield** [comment]
Looks like we're all back to green on these after that revert.  I think this can be closed.
