### ISSUE TITLE
Scrolling glitches with ListView on iOS

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#30511]
On [this Flutter app](https://itunes.apple.com/us/app/veggie-seasons/id1450855435?mt=8), I'm experiencing some glitches with scrolling listviews. 

Repro:
1. Open Veggie Seasons app, scroll fairly rapidly up and down
2. After a number of seconds, see jank manifesting either in a rapid jump or in missed frames.

See the following demo videos, recorded with a Pixel 3 XL:

 - [Demo 1](https://drive.google.com/open?id=1TXKIXhwgPCdBvQsk1ky2eJ_pPWhYIZ4Y) (glitch occurs at 0m24s)
 - [Demo 2](https://drive.google.com/open?id=145aY8ji34PUlMwXjbo-6xK2yiZ4Brb26) (glitch occurs at 0m17s)

Device type: iPhone Xs, iOS 12.2. App compiled with Flutter 1.2 using Xcode 10.1.

**Comment by xster** [comment]
I'll do a test run too but this is a this is an excellent opportunity to test drive our doc as well :D

@RedBrogdon, would you like to take a whack at https://flutter.dev/docs/testing/ui-performance as well to both check the app and do a critical read of our documentation?

**Comment by RedBrogdon** [comment]
Whoa. Yeah, I'll run through the doc and see if I can reproduce the problem.

**Comment by xster** [comment]
FWIW, I've been trying it out in profile mode on an iPhone X trying to get it to glitch up but I haven't been able to get it to cough up after ~5 min scrolling around. 

Tangentially, through a cursory analysis, I did notice something else non-ideal where scrolling to the bottom of the list and scrolling back to the top causes the top 9 images to be evicted from the bitmap cache and re-decoded. 

https://github.com/flutter/flutter/issues/13493 may be the super tracking bug where we might need to do something smarter with image caching (since either way, 100mb image cache is probably too small on iPhones in general).

**Comment by xster** [comment]
Oh I see what's going on in the video (after adding a scrollbar to the list). It's not so much that it's dropping frames but the sliver dead-reckoning is having trouble figuring out where the current scroll offset as it's crossing back through the boundary of 'not in season' back into 'in season' list. 

I'm not sure where the math went wrong exactly yet but looking at https://github.com/flutter/samples/blob/master/veggieseasons/lib/screens/list.dart#L73, building a full list of widgets via ListView.children is a performance anti-pattern rather than using the builder pattern which builds lazily https://flutter.dev/docs/testing/best-practices#render-grids-and-lists-lazily. 

cc @InMatrix, I think we tried adding some automated lint warnings to IntelliJ previously. 

Tangentially, as a UI feedback I hadn't realized there are an in-season list and a non-in-season list :) 
Opened https://github.com/flutter/flutter/issues/30737.

**Comment by xster** [comment]
We should still use the builder pattern but https://github.com/flutter/samples/pull/67 will fix the symptoms of this issue (because the heights of the cards are more static. Otherwise, as we evict the top images from cache, scroll to the bottom then scroll back to the top, we ask what the intrinsic sizes of the images are, which are momentarily 0, then the dimensions change as the images become decoded and confuses the sliver offset calculations).
