### ISSUE TITLE
Material Slider has no adaptive constructor

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#30571]
The switch has an adaptive constructor. The slider should also have one.

**Comment by matthew-carroll** [comment]
CC @willlarche @HansMuller do you two know what you'd like to do for this? It seems like switch received some special treatment here in terms of being "adaptive" across platforms. Can you elaborate on a larger philosophy for this going forward?

**Comment by HansMuller** [comment]
@matthew-carroll For material components that have been material-only but need support adapting to the target platform, the plan is to add a ".adapt" named constructor that DTRT.  https://github.com/flutter/flutter/pull/30572 is an example. We don't plan to do this for every component.

**Comment by matthew-carroll** [comment]
@HansMuller in the ticket you linked it reads "we should provide adaptive constructors for as many widgets as necessary in the Material library" - do you know how we're determining which widgets are "necessary" when it comes to this adaptive behavior?

CC @xster @LongCatIsLooong

**Comment by willlarche** [comment]
So, just for the product, we should do it with as many as makes sense. It's requested over and over and over.

For these, it's the ones the Material designers have marked in [this page](https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines) or IRL with me as we work on beefing up our iOS guidance.

**Comment by matthew-carroll** [comment]
Are you sure that you want these behaviors to be constructors within the material space, rather than a new collection of widgets which are essentially "xWidgets"?  I'm thinking that these changes kind of "pollute" the material API space with other platforms. Also, right now it's just Cupertino, but I imagine that we'll see other platforms supported in the future. What happens when the parameters begin to slightly vary and we end up needing slightly different constructors?

Would it be easier to introduce a package that offers explicitly cross-platform widgets that internally configure whatever widget(s) are needed for the given platform? This would allow Material to stay Material, Cupertino to stay Cupertino, and would offer a sandbox where new platforms can be added.

Additionally, a new package could be released externally instead of bundled within the framework which would allow a more forgiving versioning approach.

**Comment by willlarche** [comment]
We've spoken and thought about this extensively, yes. But of course nothing is codified yet. It's really a cross-team question that should be decided at a high level or something.

xWidgets seems like a good idea at first but it requires speccing them out, desiging them, supporting them with an entire separate team. Take it from us in Material, it's really hard and really expensive. And the ROI would be low.

We suggest you use Material widgets as primitives when possible. They already exist and can do things in predictable ways. We have intended them to be so customizable that you can theme them to look correct in any design language (tho there is still more work to be done opening them up). Csells is good to talk to about that and how it relates to more platforms.

Having a constructor makes a lot of sense for the widgets that Material believes should not show on iOS. People want things to be 'automatic' when possible. And we wouldn't be faithful to Material if we didn't make it as easy as possible to show the correct widget with Material APIs. We could check with UXR but it seems to be a paradigm that people understand. And we've dedicated a lot of screen time to teaching it in the past few months.

But again, a PM should look at this holistically.

**Comment by willlarche** [comment]
Oh, and I should clarify that the adaptive constructor wasn't my idea or anything. I've just been using it and watching other people use it.

**Comment by clocksmith** [comment]
Just in case it was missed, the PR for this issue is https://github.com/flutter/flutter/pull/30572 and it is very similar to the [existing .adaptive constructor on the Switch](https://github.com/flutter/flutter/commit/bbb080b3a3d4e2f3b61b2f7b029cafdb9b9cab99#diff-fe2bb980c6207699cbf45538fe927afa)

**Comment by xster** [comment]
Cool, neat. Thanks @clocksmith
