### ISSUE TITLE
Material Design 2

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#30593]
Google is rolling out updates for its apps, that use slightly different Material guidelines. You can see this in Gmail, Files, Photos, and more.

Things I've noticed:

Default text color is grey, not black.
App bar uses a lower elevation, the shadow is not as harsh.
Tab indicators are rounded and change to the size of the text.
Search app bar is floating.
Drawer is more compact.

Will Flutter update to meet these guidelines, or will it fall behind in design, and we will have to fall back to custom theming and packages to meet these new standards?

**Comment by tottomotto** [comment]
Is there an official changelog with these updates or we need to figure them ourselves? Updating the widgets bit by bit when we notice a change doesn't seem very clever.

**Comment by creativecreatorormaybenot** [comment]
[Material.io](https://material.io/) ("Get the latest updates") does not mention it. It could just be internal Google design to differentiate Google applications from others. You can interpret this however you like.

**Comment by dnfield** [comment]
I think @HansMuller or @willlarche would have more to say about this, but it would probably be most helpful to file specific bugs where the Material library isn't matching what you're expecting.

It's also possible that some of the differences you're seeing are just the way a particular app is customizing Material :)

**Comment by willlarche** [comment]
Thanks for the question! I think I understand what the miscommunication here is.

My name is Will Larche. I'm the Flutter Lead here in Material Design. I run a team that works on the Material library in partnership with @HansMuller 's Material team in Flutter.

Last May, we introduced a huge expansion to Material Design. It now supports custom, brand-driven styling throughout your app in a set of features and guidelines we call [Material Theming](https://material.io/design/material-theming/overview.html#material-theming).

![Screen Shot 2019-04-06 at 12 55 15 PM](https://user-images.githubusercontent.com/1271525/55672634-43939080-586b-11e9-93e3-1168b8baf77b.png)

The problem Material Theming aims to solve is the lack of visual distinction we noticed in Material apps in the wild. They all looked the same. Even though we intended Material to be flexible and extensible, we realized we didn't dedicate enough of our guide to telling people how they could do that. Material Theming shows you some options for styling that you'll find in almost every Material Component so your app can uniquely express your brand while also building on research-backed UX and UI best practices.

[Google was our first client!](https://material.io/articles/how-google-created-a-custom-material-theme.html#01) What you've noticed is that Google apps have used the new Material Theming features in Material Component libraries to create a custom Material theme that expresses Google's brand (building from white, the colors from the logo, custom rounded fonts, rounded corners, etc.)

Since Flutter is built for the whole world, and not just Google, its defaults in Material Components do not automatically look like Google apps. **You should not be attempting to imitate theming based on someone else's brand.** Instead, check out the starter themes we've released as [Material Studies](https://material.io/design/material-studies/about-our-material-studies.html). Your designer can play with them in the [Material Theme Editor for Sketch](https://material.io/tools/theme-editor/).

You can also learn more about Flutter's support for Material Theming in [this Medium article](https://medium.com/flutter-io/building-beautiful-flexible-user-interfaces-with-flutter-material-theming-and-official-material-13ae9279ef19) from us. Inside you'll find a link to my and @maryx 's talk on using Flutter's Material Components to build a fully themed app and a series of codelabs we wrote on the subject. [MDC-103](https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#0) in particular teaches you how how to theme a complicated Material app.

We're always adding more features to Material Components in Flutter to support building everything in the Material Guidelines. If your favorite UI feature is missing, [create a GH issue](https://github.com/flutter/flutter/issues/new/choose)! Having the community let us know what they need helps us prioritize our work. You can also submit features as pull requests right to Flutter! See our [guide on contributing](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) to learn how.

Thanks for using Flutter and having such a keen eye for design!

**Comment by willlarche** [comment]
@tottomotto , there is no official changelog to the Material Guidelines per se. It our team's responsibility to work with the designers as they finalize new features and figure out when and how they can be deployed across Android, iOS, web, and Flutter. If you've noticed a new feature in the guidelines and you don't see a GH issue for it, create one and we'll comment on it.

**Comment by giaur500** [comment]
I don't understand why did you close issue. Google has introduced new widgets and themes library for material design 2, buttons, fab buttons, navigation drawer looks completly different.

Look there: https://material.io/develop/android/docs/getting-started/

Flutter's material widgets are still clone Google's Material Design 1. And that's actually deprecated look.
