### ISSUE TITLE
Let flutter app developers use our testing framework

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#307]

**Comment by Hixie** [comment]
- [ ] `flutter test` should look in current directory/subdirectories for tests to run (like flutter start) 
- [ ] have `flutter test --flutter-repo` to test the flutter repo
- [ ] put the flutter test utility files into `flutter/lib/src/test/*` (or into a separate flutter_test package) so that other projects can import them

**Comment by abarth** [comment]
We should be ready to give this a try now.

**Comment by abarth** [comment]
Still missing
 - [ ] `flutter test` should use binaries from cloud storage

**Comment by abarth** [comment]
`package:flutter_test` is https://github.com/flutter/flutter/pull/555
