### ISSUE TITLE
Implement Widget Combining Checkbox/Radio/Switch with a Label

### ISSUE THREAD

**Issue by cubuspl42** [flutter/flutter#30781]
Issue #254 ("Checkbox + label should be a widget") was closed by #10160, which adds `RadioListTile`.

I really believe that most radio buttons do **not** appear in lists, but in forms of various kinds. 

It's not purely a semantic issue; `RadioListTile` looks weird when put in a form, probably because its internal padding. Also having more than one labeled radio button in a row is not possible with `RadioListTile`.

**Comment by shihaohong** [comment]
Hi @cubuspl42, 

The `Radio` widget is standalone and can be used to build other custom widgets of your own choosing (see docs [here](https://docs.flutter.io/flutter/material/Radio-class.html)). As for the `RadioListTile`, it is meant to look like as it does in the [Material specifications](https://material.io/design/components/selection-controls.html).

I'm actually not very clear on what you're asking for through this issue. Could you please clarify the ask? Thank you!

**Comment by cubuspl42** [comment]
@shihaohong I believed it is clear. The problem is as described in https://github.com/flutter/flutter/issues/254, and the solution provided in https://github.com/flutter/flutter/pull/10160 which closes the mentioned issue is not what was asked for, which I explained in the opening comment.

It's just a practical thing. (Nearly?) every developer who ever uses the `Radio` has to develop a widget that couples `Radio` with its label, and most of the time `RadioListTile`, or any other `ListTile`, is not what they look for. This issue can be summed up as "https://github.com/flutter/flutter/issues/254 was never solved".

**Comment by cubuspl42** [comment]
The `RadioListTile` integrates nicely only with other list tiles. Imagine you're doing any kind of form with a radio button. You'd probably like to integrate it with comboboxes/selects (`DropdownButton` in Flutter, a weird name btw) or text inputs. Now you can use `RadioListTile` (when you're not really doing anything that is remotely a list) or implement your own `Radio`+`Text` widget.

**Comment by shihaohong** [comment]
The extra context helps, thank you for the feedback and have had some time to think about how to approach this issue.

Currently, as I understand it, the root of the issue is that `Radio` itself is too bare bones, whereas `RadioListTile` is too specific, so the ask is for some direction for a middle ground implementation.

Let's assume a `LabeledRadio` widget that essentially puts a `Radio` and `Text` widget side by side, with parameters for customization like padding, ink responses, etc.

I see two paths forward:
1) Implement `LabeledRadio` as a widget in the material library.
2) Create a sample doc for `LabeledRadio` under the `Radio` documentation.

Currently, I'm looking towards option 2. This is because, as you stated, developers may have to build a widget that couples `Radio` with a label. The main concern I have with option 1 is that developers may have issues with the particulars of how it's implemented (ie. size constraints, text alignment, nuances of gesture detection/ink responses).

Thus, I'd rather leave it to the developers to have a sample to go off of, and then tailor its implementation themselves such that it behaves as expected. That way, if your vision of a Radio + label widget differs from other developers, you can customize the code yourself to fit your use case. Let me know what you think.

**Comment by shihaohong** [comment]
To add some context, I've run into a similar situation with developers expecting `ListTile` to be a one-size-fits-all solution for their list items, when in reality, it has a particular design spec as described by Material. 

Rather than trying to push a customized widget to fit every developers' needs, I find it's better to provide suggestions for how to build a widget that suits your particular needs and empower developers with the power to customize their own apps.
