### ISSUE TITLE
[Firebase messaging] iOS gets 2 times the payload of the message while Android gets it only once

### ISSUE THREAD

**Issue by ZatacaSystems** [flutter/flutter#30906]
I have noticed that iOS is receiving twice the payload of the message while android is getting the payload only once. iOS shows 2 notifications while android only get's one.

**Comment by ZatacaSystems** [comment]
I also have noticed that it happens in some devices, for me, 2 iphones (8 plus and 7) behave on differente ways. The 8 plus recive 2 notifications while the 7 only 1.

**Comment by escamoteur** [comment]
If the problems still isn't solved, please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!

**Comment by iapicca** [comment]
Hi @ZatacaSystems 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
