### ISSUE TITLE
Timestamp is not a subtype of type 'DateTime'

### ISSUE THREAD

**Issue by preetjdp** [flutter/flutter#31182]
## Steps to Reproduce

The version of firestore(0.9.13+1) is having a issue where it does not parse the Timestamp in the database
version 0.9.7+2 works perfectly!!!

1.  pubspec => cloud_firestore: ^0.9.13+1
2. get the date from the database and use DateTime for computation and fails

![photo_2019-04-17_12-27-59](https://user-images.githubusercontent.com/27439197/56267381-48c6ca00-610c-11e9-947d-647c7370c220.jpg)

## Logs

```
I/flutter (15576): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15576): The following assertion was thrown building ExpenseDetailCard(dirty, state:
I/flutter (15576): _ExpenseDetailCardState#d64c1(tickers: tracking 1 ticker)):
I/flutter (15576): type 'Timestamp' is not a subtype of type 'DateTime'
I/flutter (15576):
I/flutter (15576): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15576): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15576): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15576):   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

```
```

**Comment by superciccio** [comment]
`( json["creationDate"] as Timestamp).toDateTime()`
where `Timestamp `is the one coming from `cloud_firestore`

**Comment by ThalesDFS** [comment]
Can you solve it?

**Comment by rostopira** [comment]
Using DateTime in firestore were deprecated long time ago
It's not an issue, it works as intended

**Comment by sma** [comment]
A database field of type timestamp resolves on iOS as Dart `DateTime` and on Android as Dart `Timestamp`. This IMHO is a bug and shouldn't be considered as "works as intended". My expectation is that the native code must deal with any differences that might occur and provide a sane API to the Dart side.

**Comment by preetjdp** [comment]
.toDate() converts TimeStamp to DateTime and fixes the "issue"

**Comment by mfreeman451** [comment]
> A database field of type timestamp resolves on iOS as Dart `DateTime` and on Android as Dart `Timestamp`. This IMHO is a bug and shouldn't be considered as "works as intended". My expectation is that the native code must deal with any differences that might occur and provide a sane API to the Dart side.

I concur.

**Comment by srihamat** [comment]
As I realized that firebase only have timestamp and flutter is support firebase. I decided to use timestamp in my whole project. Later, I spend few days find the method to convert timestamp to date, which I found ppl mentioned milisecondsSinceEpoch is helping. But no because int is not a subtype of type 'Timestamp' in type cast.

Look like, milisecondsSinceEpoch may help if and only if we are at the converting to json ( in my case for upload to firebase).  So, to make it work, I need to change whole of code related with TimeStamp to DateTime. Then only convert particular DateTime to TimeStamp at converting to json.

With time consuming experienced, I support idea from @sma .
During this period of not making change, I hope ppl read my comment and avoid same mistake with me.

**Comment by fluttercorner1** [comment]
I think you have make mistake in converting datetime here is tutorial about [Converting TimeStamp in Flutter, Flutter Date time to Timestamp](https://fluttercorner.com/converting-timestamp-in-flutter-flutter-date-time-to-timestamp/)
