### ISSUE TITLE
CustomPainter allows painting outside specified size

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#31202]
## Steps to Reproduce

1. Create a CustomPainter widget.
2. When painting in the `paint()` method, ignore the size parameter and paint wherever you'd like (treating 0, 0 as the top left of your widget, and negative values as up and left from there).

This makes simple tasks like drawing a line from one corner of the canvas to another, much more difficult. Even with a small stroke width, it's impossible not to have the line overlap the outside container where it meets the corners:

![flutter1](https://user-images.githubusercontent.com/9156188/56302840-6b96b580-60ef-11e9-8bd8-b332b8cad94f.png)

This also seems like it could possibly be a security risk for two reasons:
 1. A package using the `CustomPainter` widget could silently overwrite the screen, in the right circumstances. See the screenshot below for a proof of concept.
 2. If it's possible to extract enough information from the canvas (even if just by observing side effects), then it could be possible to read the entire screen. (Doesn't seem likely, but I wanted to point out this high-risk scenario.) 

Here's an proof-of-concept of a `CustomPainter` widget replacing the name of an app that's displayed above the widget:

![flutter3](https://user-images.githubusercontent.com/9156188/56304056-1d36e600-60f2-11e9-801e-6bdf83fb8d7d.png)

Both examples are in this gist: 
https://gist.github.com/mtcliatt/2bc1e538869def82115af4a0b3b11a36

### flutter --version

```
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (9 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by GaryQian** [comment]
@liyuqian Any opinions on this behavior? A ClipRect would prevent the overdraw behavior.

**Comment by liyuqian** [comment]
@mtcliatt : the behavior is expected as we recently set most widgets to not clip by default to improve the rendering performance (see `none` in https://docs.flutter.io/flutter/dart-ui/Clip-class.html for more details). As @GaryQian mentioned, if a widget doesn't expose a `Clip` option, you can wrap it with a `ClipRect` to achieve the clip.

For the `CustomPainter` specifically, please note the document in https://docs.flutter.io/flutter/widgets/CustomPaint-class.html

> The painters are expected to paint within a rectangle starting at the origin and encompassing a region of the given size. (If the painters paint outside those bounds, there might be insufficient memory allocated to rasterize the painting commands and the resulting behavior is undefined.)

Because drawing outside of bounds is an undefined behavior, Flutter makes no guarantee what would happen. Therefore, it's the developers' responsibility to ensure the inside-of-bounds drawing if they own the `CustomPainter` class. If they don't own it, then adding a `ClipRect` is the way to go.

One action Flutter can take here is to improve the documentation of `CustomPainter` to include the above information.

Alternatively, Flutter can also automatically call `clipRect` before the `CustomPainter` to avoid the undefined behavior. The `clipRect` shouldn't have too much impact on the performance. This might be a breaking change if someone relied on our behavior of not clipping. But drawing outside-of-bounds is an undefined behavior, so rigorously speaking, they shouldn't rely on that. What do you think, @Hixie ?

**Comment by mtcliatt** [comment]
Thanks for the detailed information!

Ensuring in-bounds drawing seems like a lot of responsibility to put on the owner of the `CustomPainter`, considering that even drawing a small line from one corner of the canvas to another results in drawing outside the given bounds. Are there cases where it is desirable and reasonable to allow the `CustomPainter` to draw outside the given bounds?

I really like your recommendation of Flutter calling `clipRect` before the `CustomPainter`.

I don't think owners of `CustomPainter` can be expected to know if they are drawing in-bounds or not. Another simple example that demonstrates how difficult it is to know if you'll be in bounds: drawing a rectangle. If you draw a `Rect` from `(0, 0)` to `(size.width, size.height)`, then you're out of bounds on 3 sides by `strokeWidth / 2`. This is because Flutter draws the `Rect` such that the topmost point is the top you specified, the leftmost point is the left you specified minus `strokeWidth / 2`, the rightmost point is the point you specified plus `strokeWidth / 2` and the bottom-most point is the bottom you specified plus `strokeWidth / 2`. It took a little while to figure this out, and I was never able to find anything in the documentation that could have helped me arrive at this discovery (I should probably file a separate bug for the relevant documentation).

Even if the owner could know without error and without extra computation if their drawing will be in bounds or out of bounds, they are still faced with the dilemma of deciding whether to draw or not. If the drawing would lay over the bounds, then the painter can either draw over the bounds, not draw, or use a `clipRect`. Drawing over the bounds obviously isn't reasonable, and not drawing wouldn't work well either (imagine a star flying across the screen that suddenly disappears when it approaches the edge). This leaves the `clipRect` solution. 

Since reasonable users of `CustomPainter` can't be expected to know when they're drawing in-bounds vs out-of-bounds, reasonable users need to use `clipRect`. If all reasonable users need this, shouldn't it be default?

**Comment by liyuqian** [comment]
A little note: owner of `CustomPainter` can also call `canvas.clipRect` in the beginning of `CustomerPainter.paint` to ensure that everything is inside of bounds.

**Comment by mtcliatt** [comment]
Thanks, I think that's definitely the solution. So if it should always be done, then can/should it be handled by Flutter?

Also, are there any situations where it's necessary to allow a CustomPainter to paint outside of its bounds?

**Comment by Hixie** [comment]
It's always desireable to allow it: clipping is very expensive and if we clipped, it would slow down execution performance.

**Comment by mtcliatt** [comment]
It sounds like the proposed solution is too slow, but does that mean it's actually desirable to allow a CustomPainter to paint outside of its bounds? 

If we assume that we can find a solution with no performance implications, would that solution be preferred over allowing any `CustomPainter` to paint outside of its bounds? If not, why not?

**Comment by Hixie** [comment]
If we could find such a solution, I think it would be reasonable to use it.

**Comment by liyuqian** [comment]
Shall we close this issue by https://github.com/flutter/flutter/pull/31454 ?

Meanwhile, I'd also encourage @mtcliatt to write some flutter driver performance tests to determine the impact of adding `ClipRect` automatically. (Sorry, the Flutter team currently has so many other performance issues to solve that we don't have resources to write this test ourselves.) If we can prove that it's tiny, we may be able to add that automatically for every `CustomPaint`.

**Comment by mtcliatt** [comment]
Happy to help! Could you please point me to some example performance tests for similar use cases (if possible)?

**Comment by liyuqian** [comment]
Maybe the simplest example I can find is https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/lib/src/cull_opacity.dart

You can run that test by `flutter drive --profile test_driver/cull_opacity_perf.dart` inside `dev/benchmarks/macrobenchmarks`.

In order to track its performance in our devicelab and dashboard, you'll also have to add something like https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/cull_opacity_perf__timeline_summary.dart and modify https://github.com/flutter/flutter/blob/master/dev/devicelab/manifest.yaml

**Comment by natebot13** [comment]
I'm writing an app that I think needs to rely on this behavior, since I don't know any better way to do it. What I have is a custom painter that draws a regular hexagon behind a square child. I want to be able to butt two hexagons up against each other, but if I'm restricted to only painting inside the child, I can't butt them together. Image for demonstration:
![Allowed but not desired](https://user-images.githubusercontent.com/6336166/91794922-1f0f2580-ebd1-11ea-8621-def9223643ae.png)

If I want to butt these two hexagons together, then I would need to scale the hexagons and draw outside the bounds on the top and the bottom. Like this:
![Desired but not allowed](https://user-images.githubusercontent.com/6336166/91795270-11a66b00-ebd2-11ea-98e1-21e2bdda8060.png)

Unless there's a different approach I should take, I'm counting on this behavior for now.

**Comment by liyuqian** [comment]
I think our APIs have settled to not adding clips by default so you can count on it. If a clip is needed, you can always call `canvas.clipRect`, or maybe add a `ClipRect` widget on top. I'm closing this issue. Please feel free to reopen if there's more.
