### ISSUE TITLE
Issue getting with Google_maps_flutter

### ISSUE THREAD

**Issue by princeagra21** [flutter/flutter#31241]
Dear Developers , 

i am using Google_maps_flutter plugin please suggest us how can we implement following. 

1. Moving smoothness or animation  for example please check given below image.
![moving-animtion](https://user-images.githubusercontent.com/11417381/56341373-79713700-61d2-11e9-9ceb-fc2b0ab97461.gif)

2.  Unable to apply animation effect see example below. 

![zniDu](https://user-images.githubusercontent.com/11417381/56341542-02886e00-61d3-11e9-8498-c77298491992.gif)

**Comment by NathanAP** [comment]
We use something similar to the second situation in our app with the [avatar_glow](https://pub.dartlang.org/packages/avatar_glow) package, you could try to use it with your map as well!

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
