### ISSUE TITLE
[Material] Applying a color scheme to a flutter app is difficult.

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#31284]
The Material Design spec defines the colors of components according to the [the color system](https://material.io/design/color/the-color-system.html#).
![nYXGWq02dBU](https://user-images.githubusercontent.com/4229329/56392036-565c7c80-61fe-11e9-81e8-2485932b2a21.png).

In Flutter, we have a class that represents the color system ([color_scheme.dart](https://github.com/flutter/flutter/blob/ccdd50578c7ba145845921b93eb44d93b6b61037/packages/flutter/lib/src/material/color_scheme.dart)). But when you create a `ColorScheme` object and assign it to `ThemeData.colorScheme`, it is only used to apply color defaults to a couple of components.

There are lots of color related parameters in [theme_data.dart](https://github.com/flutter/flutter/blob/b1039f0f1b761b0e4ec1825eed269b10af6104d4/packages/flutter/lib/src/material/theme_data.dart#L112), like `primaryColor`, `accentColor`, `hintColor` etc. Rather than worry about these...

We should have a way to create a `ThemeData` and pass in a single `ColorScheme` object, and then have all of the Material Components in our Flutter app pull from that `ColorScheme`. Unless users specify a color directly to a widget (which should always be honored). 

This will be especially convenient if users want to create an entirely new `darkColorScheme` for creating a darkTheme, they can specify it once at the top of their apps, and have all of the components update automatically.

**Comment by godlessturtle** [comment]
use theme property in your main.dart file like below

`MaterialApp(
      ...
      ...
      theme: ThemeData(
        fontFamily: 'SFDisplay',
        hintColor: Colors.black,
        bottomAppBarColor: Colors.black,
        primaryColorDark: Color.fromRGBO(25, 118, 210, 1),
        primaryColor: Color.fromRGBO(33, 150, 243, 1),
        tabBarTheme: TabBarTheme(
            indicator: BoxDecoration(
              color: Colors.black12,
              border: Border(
                bottom: BorderSide(color: Colors.black87),
              ),
            ),
            labelColor: Colors.black87,
            unselectedLabelColor: Colors.grey),
      ),
    ),`

**Comment by HansMuller** [comment]
This problem has a wide scope and we will have to chip away at it for a while. The overall plan is sketched out here:  https://flutter.dev/go/material-theme-system-updates.

**Comment by chinkysight** [comment]
I am not able to apply the color that I defined in the colorScheme property of ThemeData in my application. Here is my `theme.dart` file : https://gist.github.com/chinkysight/33b02b733e3b45bd341f509e9dc85577

Inside the `MaterialApp` I set `theme` to `AppTheme.lightTheme`

**Comment by timekone** [comment]
> 
> 
> I am not able to apply the color that I defined in the colorScheme property of ThemeData in my application. Here is my `theme.dart` file : https://gist.github.com/chinkysight/33b02b733e3b45bd341f509e9dc85577
> 
> Inside the `MaterialApp` I set `theme` to `AppTheme.lightTheme`

Right now the workaround for this issue is to use [ThemeData.from](https://api.flutter.dev/flutter/material/ThemeData/ThemeData.from.html) constructor. It is not ideal, but it is something. See #43823 and #48195.

**Comment by rydmike** [comment]
Thanks @johnsonmh for raising this issue. I agree with @HansMuller that it is a bigger topic as well, but we could start small and fix some of the minor annoyances first. 

There are actually not that many color properties anymore in a `ThemeData` object that a `ThemeData.from(ColorScheme)` factory would need to set to fix `ColorScheme` based color theming gaps when using the `ThemeData.from(ColorScheme)` factory, which is otherwise very neat, only a few of them are still left out when you do that.

It would indeed also be very nice if when you use `ThemeData()` factory and give its `colorScheme` property a `ColorScheme`, if it did the same thing as the `ThemeData.from(ColorScheme)` does, to set the color properties in `ThemeData` based on the on the passed in `ColorScheme` colors, can't argue with that either.

In addition it would be **outstanding if the both also set color values to color properties** in `ThemeData` that even `ThemeData.from(ColorScheme)` currently neglects. Yes I know these color properties might eventually go away based on this too: https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit 
**but** while we wait for that, those color properties should get values from `ColorScheme` if it is used.

I was doing these additions and corrections so repeatedly that I ended up publishing a package [FlexColorScheme](https://pub.dev/packages/flex_color_scheme) that address these gaps, and yes it does many other convenience things I liked and often needed too. In this package extensive readme, [at the end of it](https://pub.dev/packages/flex_color_scheme#themedata-default-modifications) I also describe in detail what it addresses, regarding themes and colors.

While making that package I learned that when it comes to `ThemeData.from()` that it still neglects setting provided `ColorScheme` colors for these properties in `ThemeData`:

 - `toggleableActiveColor`
 - `primaryColorDark`
 - `primaryColorLight`
 - `secondaryHeaderColor`

So these then get `ThemeData()` factory defaults, which seldom result in colors you would expect based on your `ThemeData.from(ColorScheme)` and you will see this in widgets that still use and depend on those `ThemeData` color properties, or if you otherwise use these color properties to theme your own custom widgets.

Addressing this is relatively minor: 
- `toggleableActiveColor` just needs to be set to `colorScheme.secondary` 
- The other three properties needs to get appropriately computed values based on provided `colorScheme.primary`.

---

By the way, the default dark theme for `ChoiceChip()` should still also be fixed, it is broken regardless of if you create your theme using `ThemeData()` or `ThemeData.from()`, see here https://github.com/flutter/flutter/issues/65663

**Comment by magician20** [comment]
Any solution for implement theme ??

**Comment by darrenaustin** [comment]
This is an old bug and a lot of this has been addressed. Most of the Material components have been moved over to using `ColorScheme` colors for defaults. To track any further progress on theme updates, you can follow #91772.

**Comment by rydmike** [comment]
@magician20 this is a bit of shameless plug, but you can try the FlexColorScheme package, https://pub.dev/packages/flex_color_scheme (disclaimer: I'm the author), if color and even component themes feels tedious or confusing. It takes care of all these legacy color issues and much more, plus it has more flexible seed generated M3 ColorSchemes than Flutter offers out of the box for M3 ColorScheme generation.

In its fresh new doc site https://docs.flexcolorscheme.com I also generally talk about, and demonstrate all the ways you can make a `ThemeData` object, including old swatch based (shows why you should not use them), ColorScheme based ways (shows their gaps too) all the new seed based ones as well, they share the same `ThemeData` gaps, plus the new `ThemeData.colorSchemFromSeed` makes a crazy divider theme since the M3 outline color is applied to it directly without any opacity. Using `ThemeData.from(colorScheme: ColorScheme.fromSeed( ...) )`, works better and does not have that issue, it sets opacity on divider.

You can find that study here https://docs.flexcolorscheme.com/theming_roads. It is general info and not package related.

![image](https://user-images.githubusercontent.com/39990307/164544405-61ed24eb-9f3d-4610-8060-0ac485ea8ab2.png)

I also analyze the results, plus show how you can manually address some of the gaps they all leave out when it comes to still  important direct color properties in `ThemeData`. Sure I plug `FlexColorScheme` as an option and show what it does in comparison too.

With FlexColorScheme you can also use more than one seed color when you generate a ColorScheme, so you get own seeds for colors used to make Tonal Palettes for secondary and tertiary colors, not just computing them from same "primary" seed color. 

You can also adjust the chroma limits differently than what `ColorScheme.fromSeed` does, so you can make the colors brighter and/or closer in hue to your source key colors, if you like. Lastly you can also adjust the tone mapping of what seeded Tonal Palette tone is used by which color in the light dark mode `ColorScheme` that gets made from the core tonal palettes.

**Comment by magician20** [comment]
@rydmike I actually follow your PUB from the start and it was overwhelming.
But now you have the documentation so I'll give it a try.
Thanks & Good Work

**Comment by rydmike** [comment]
Thanks @magician20, in addition to the doc for the FlexColorScheme package, regarding both its general guide and Roads to ThemeData chapters, I wrote a slightly shorter version in response to a similar issue to this one, here https://github.com/flutter/flutter/issues/19089#issuecomment-1106644732.

In it I also demonstrate how one can make a color consistent ThemeData where **all** built-in widgets will get themed consistently by the used ColorScheme.
