### ISSUE TITLE
Cannot provide both a color and a decoration I/flutter ( 9015): The color argument is just a shorthand for "decoration: new BoxDecoration(color: color)". I/flutter ( 9015): 'package:flutter/src/widgets/container.dart': Failed assertion: line 269 pos 15: 'color == null || I/flutter ( 9015): decoration == null'

### ISSUE THREAD

**Issue by hezhiwebworld** [flutter/flutter#31312]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
This is intentional. The `color` property is a shorthand for creating a BoxDecoration with a color field. If you are adding a box decoration, simply place the color on the BoxDecoration.

In general, assertions like these are not errors in the framework - they are hints to the developer that there is a problem in the code.
