### ISSUE TITLE
Consolidate duplicate code in widget tests and rendering tests

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3142]
These two files have duplicated code:

```
packages/flutter/test/rendering/rendering_tester.dart
packages/flutter_test/lib/src/widget_tester.dart
```

We should consolidate to simplify maintenance.

**Comment by krisgiesing** [comment]
@Hixie

**Comment by esarbanis** [comment]
I cannot spot the code duplication among those classes anymore. Is this still a relevant issue?

**Comment by pedromassangocode** [comment]
Will close this because those files were updated since the issue was filled and it is not valid anymore.

The files in question are:
https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/rendering_tester.dart
https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/widget_tester.dart
