### ISSUE TITLE
Create a generated variable based on flavor

### ISSUE THREAD

**Issue by guitcastro** [flutter/flutter#31441]
As today there is no hint to get what flavor is running in dart code. The current workaround is to use the `-t` flag in the build command to change the main file target, creating main_dev.dart and main_prod.dart per example. 

Would be nice to have some generated variable or something similar to expose which flavor is in compile time.

**Comment by zanderso** [comment]
This sounds like something that could be plumbed to `String.fromEnvironment()`. /cc @jonahwilliams

**Comment by jonahwilliams** [comment]
We do have the --dart-defines option, but that isn't wired up for non-JavaScript targets yet. We could do something automatically, but for the most part the dart code doesn't depend on chosen flavor, so we'd introduce another angle of invalidation. This might waste some time if the flavor-dependent environment variable would otherwise not be used

**Comment by zanderso** [comment]
Is there an issue filed to wire up `--dart-defines` for non-Web platforms?

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/44483

**Comment by friebetill** [comment]
Now that #44483 is solved, what would happen next?

**Comment by jonahwilliams** [comment]
In your code:

```
const String flavor = String.fromEnvironment('app.flavor');

void main() {
  print(flavor);
}
```

From command line:

`flutter build ios --flavor=paid --dart-define=app.flavor=paid`

This would print "paid" when run.

**Comment by friebetill** [comment]
That's wonderful. Are there any plans to avoid having to double-specify the flavor?

**Comment by jonahwilliams** [comment]
doing this automatically would require us to fully invalidate a build whenever someone switched flavors. That might be surprising if someone wasn't using the actual constant value

**Comment by jonahwilliams** [comment]
I think this can be scripted easily enough from the command line. closing as resolved

**Comment by hicnar** [comment]
@jonahwilliams Your proposed solution does not work if one tries to run an app on iOS (ex `flutter run --flavor=paid --dart--define=app.flavor=paid`) neither on simulator nor on a real device. 

For some reason no dart defines are passed into the environment so that they could be subsequently read by String.fromEnvironment(...).

It does seem to work on Android though, but with Android the main method can be defined in an arbitrarily named dart file and again as opposed to iOS the -t ... / --target=... arguments work perfectly well.

I think observations by Denis Baketsky may be relevant here: https://medium.com/@tatsu.ukraine/what-you-should-know-before-you-upgrade-flutter-in-your-project-with-compile-time-variables-3ec3d2e9ba79

> In your code:
> 
> ```
> const String flavor = String.fromEnvironment('app.flavor');
> 
> void main() {
>   print(flavor);
> }
> ```
> 
> From command line:
> 
> `flutter build ios --flavor=paid --dart-define=app.flavor=paid`
> 
> This would print "paid" when run.
