### ISSUE TITLE
[Feature Request] vue-template-like syntax  for widget syntax  

### ISSUE THREAD

**Issue by Akimotorakiyu** [flutter/flutter#31462]
## want

want vue-template-like syntax  for widget syntax  

1. Increase recognizability
2. Simplified Rendering Logic
3. Easy style modification

[VUE](https://github.com/vuejs/vue) which has 136,408 stars.

eg:
`index.html`
```html
<body>
<div id="app></div>
</body>
```
`todo-item component`
```js
<template>
     <li>{{ todo.text }}</li>
</template>

Vue.component('todo-item', {
  props: ['todo'],
  // the same with in <template/>
  // template: `<li>{{ todo.text }}</li>`
})
```
`index.js`
``` js
<template>
    <ol>
      <todo-item
        v-for="item in groceryList"
        v-bind:todo="item"
        v-bind:key="item.id"
      ></todo-item>
    </ol>
</template>

var MyApp= new Vue({
  el: '#app',
  data: {
    groceryList: [
      { id: 0, text: 'Vegetables' },
      { id: 1, text: 'Cheese' },
      { id: 2, text: 'Whatever else humans are supposed to eat' }
    ]
  }
})
```

**Comment by tangpanqing** [comment]
haha
i also love vue template syntax
but i think the team could not accept this opinion

**Comment by minh98** [comment]
no. i don't like this .
i hate it 😅

**Comment by ThinkDigitalRepair** [comment]
Yeah, I don't like this either. Looks like React.

**Comment by SilverLeaves** [comment]
@ThinkDigitalRepair @minh98 Do you know why vue is so popular? Because its learning curve is very smooth, all junior web engineers can get started directly and go deeper with practice step by step. React has a very steep learning curve.
vue and react are very different. Would you please evaluate them after trying vue?

**Comment by ThinkDigitalRepair** [comment]
@SilverLeaves, the thing is, Flutter isn't styled after web technologies where tags are used. It seems to go way beyond the direction of the Flutter idea for styling to use tags

**Comment by SilverLeaves** [comment]
@ThinkDigitalRepair I've seen your profiles. you're a static language developers.
And do UI development in both static and dynamic languages, and I know what I'm talking about.
Time has changed, and the separation of interface and business logic is the general trend, so as to improve production efficiency.

**Comment by ThinkDigitalRepair** [comment]
Well coming from your background, it would make sense that you prefer it that way. It's what you're used to. I'm the other way around. This is what I'm used to. So it's understandable we'll have a difference of opinion. However, my statement was about the design of the language.
I also don't like it, nor any other language that uses tags, which is why I stayed out of web development and UI in general until Flutter came along. I'm not saying you have a bad idea. I'm only mentioning that I don't like tags. And developer feedback is important when choosing a direction. So I'm just adding my feedback.

**Comment by dnfield** [comment]
The Flutter team does not have any plans to take this feature on in the foreseeable future.  Closing as won't fix.

**Comment by dnfield** [comment]
(Of course, if community members which to take this on it should be possible - but it's a very large, non-trivial project and doesn't align well with our current roadmap)
