### ISSUE TITLE
why the app size get bigger after flutter upgraded from 1.0.0 to 1.2.1

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#31467]
Hi,

Actually It isn't an issue, but just a question. we are going to upgrade flutter from 1.0.0 to 1.2.1. We found the app size got bigger when upgrade to 1.2.1. the android apk get bigger from 18M to 18.2M, and iOS get bigger from 17.4M to 19.2M. shall we know what's the reason for it? 

thanks, Yawei

**Comment by hacker1024** [comment]
You can't add more features without adding more code...

**Comment by 7syw** [comment]
it is same code line for our stage branch.

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

To your question, the size of generated code may vary slightly from build to build for all kinds of reasons including changes in Flutter and Dart, dependencies and downstream SDK changes. [The FAQ contains details](https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine) about specific changes made in recent builds to support new requirements of the Android and Apple appstores. 

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
