### ISSUE TITLE
Minor suggestion: Firebase Crashlytics plugin: Crashlytics() is exposed

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#31460]
Crashlytics() is exposed, and there is Crashlytics.instance
If i understand correctly, the constructor should be private so that devs do not try to use it on accident, and of course it doesn't achieve the right result.

**Comment by BondarenkoStas** [comment]
@neiljaywarner please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close this issue.

**Comment by iapicca** [comment]
Hi @neiljaywarner  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
