### ISSUE TITLE
Back swiping then dropping the gesture back where it started breaks

### ISSUE THREAD

**Issue by xster** [flutter/flutter#31471]
Seems like https://github.com/flutter/flutter/pull/30422 broke this again

**Comment by 1AlexFix1** [comment]
Hello!
I climbed into the source and found the following, I hope he will help you. As it was written here 
https://github.com/flutter/flutter/issues/29596#issuecomment-485114430, this happens after a certain number of uses, but this is not what you see in the GIF, this is because if you finish scrolling on your own, the screen cannot be rejected by scrolling. I already had this error earlier and your team has already solved it https://github.com/flutter/flutter/issues/27774 , https://github.com/flutter/flutter/issues/27333
![Без названия](https://user-images.githubusercontent.com/44409006/56596976-39f38200-65fa-11e9-9dc0-665082036247.gif)

**Comment by ninnepinne** [comment]
Hello!
Came because I hit: https://github.com/flutter/flutter/issues/29596
Switched to master and it works.

About to release my app and a bit worried by this one.

Do you have any more information about the issue?

I can't reproduce it on a physical iPhone 6S.
but...
I can reproduce it on a iPhone X emulator.

@1AlexFix1 Any tip for reproducing it on a physical device?

@xster Any time frame for a fix?

Thanks!

**Comment by 1AlexFix1** [comment]
> Hello!
> Came here because I hit: #29596
> Switched to master and it works.
> 
> About to release my app and a bit worried by this one.
> 
> Do you have any more information about the issue?
> 
> I can't reproduce it on a physical iPhone 6S.
> but...
> I can reproduce it on a iPhone X emulator.
> 
> @1AlexFix1 Any tip for reproducing it on a physical device?
> 
> @xster Any time frame for a fix?
> 
> Thanks!

i was test on simulator XS, no real device

**Comment by ninnepinne** [comment]
@1AlexFix1 Ahhh, sorry, false alarm/hopes...

I now understand the technique.
Start a drag and then fully drag back to original position.

Now getting the error on the physical device too... (bad words here):-(

@1AlexFix1 Thank you!

Have to go with a workaround then...

**Comment by xster** [comment]
Embarrassingly the fix is one line. I'm adding tests at the moment.

**Comment by msw333** [comment]
Thanks for the fast solution. Again, any clue when it’s in master 😉?

**Comment by xster** [comment]
Unfortunately the PR was reverted because it made a test flaky. Will try again.
