### ISSUE TITLE
How to access the asset images from the native code in flutter

### ISSUE THREAD

**Issue by headspy** [flutter/flutter#31501]
Hi, I am a newbie at this so, please help me.

For my project, I need to access images (present in the folder named "assets") in native code(Android code) in flutter so that i can set it as my phone wallpaper.

![Untitled](https://user-images.githubusercontent.com/23632601/56604754-599da100-6620-11e9-8bbb-2822e31ad720.png)

I have used assetsmanager to access the file but it is showing me that it can't find any file. Below is the code snippet.

I also added the image in pubspec.yaml under assets.

`WallpaperManager wm = null;`
`wm = WallpaperManager.getInstance(this);`

`try{`
`AssetManager assetManager = getAssets();`
`InputStream is = assetManager.open("assets/wall3.jpg");`
`Bitmap  bitmap = BitmapFactory.decodeStream(is);`
`wm.setBitmap(bitmap);`
`}`

`catch (IOException e){`
`System.out.println("Exception occurred - 1");`
`System.out.println(e);`
`}`

![image](https://user-images.githubusercontent.com/23632601/56604928-b4cf9380-6620-11e9-95e2-6a308a8b81c4.png)

Where are these files stored.(Ex: /assets/image1.jpg or somewhere else)

**Comment by BaderEddineOuaich** [comment]
Please check [here](https://flutter.dev/docs/development/ui/assets-and-images#android)

**Comment by headspy** [comment]
@matthew-carroll @dnfield is there any update on this issue.
And can you suggest me an alternative for this issue?

**Comment by matthew-carroll** [comment]
@headspy unfortunately, I don't have any concrete updates. I have a proposal out for loading resources, but it will take a bit of time to get it implemented. I think that for now you're best bet is probably to run this logic on the Android side.

**Comment by jmagman** [comment]
A workaround could be to transmit the bytes from a plugin.

**Comment by gaaclarke** [comment]
I've added an experiment to get something working on iOS: https://github.com/gaaclarke/native_images

Some of the issues I ran into while implementing it and talking to various members of the team:

- What about other asset types: videos, sounds, fonts?
- What about vector images?
  - I don't believe Flutter renders vector images.
  - It seems to me that for vector images there isn't as big of an issue duplicating the assets since they are smaller.
- For the case where the client is using UIImage from an asset catalog on iOS there isn't many options for getting data into the isolate
  - You can't get an URL to the asset.  There is no API for it and Apple will package the asset catalog into a binary blob.
  - You can recompress the image but you can't introspect into wether the source image was a PNG or a JPG so choosing to send in the wrong format can lead to artifacts or slowdowns.
  - You could potentially send uncompressed images over the wire but the transition cost might offset the extra compression cost.
- One non-optimal approach for some of these problems could be writing out data to a temp directory and sending the file URL across the wire.
- If our solution asks clients to not use UIImages with asset catalogs, are we even achieving what we set out to do?
- [There is already a way](https://flutter.dev/docs/development/ui/assets-and-images#ios) to share resources from flutter in the native host, maybe that is enough?  I don't know if there is a burning requirement that you go the other way with the data.

**Comment by gaaclarke** [comment]
Another note, alternatively we can add support to make it easier to use flutter assets from the host app.  For example on iOS we could add a method:
```objc
[UIImage flutterImageWithEngine:engine name:@"pug.png"]
```
That method could automatically grab `@2x` or `@3x` assets if available.

**Comment by gaaclarke** [comment]
Here is a design doc that suggests the techniques already outlined in our documentation for sharing Flutter assets with the host and provide some extra helper code to make it easier:
https://docs.google.com/document/d/1lEX6-D74Jwq_yqk903kc1DnR9yh6Uk6DNMgkNbr3_RM/edit?ts=5da8af1e#

**Comment by matthew-carroll** [comment]
The add-to-app team has looked into this issue and discussed approaches. We concluded that separate plugins for Android and iOS is the best way to proceed due to fundamental differences between what the platforms call "assets". I have filed 2 tickets, one for each:

Android:
https://github.com/flutter/flutter/issues/43548

iOS:
https://github.com/flutter/flutter/issues/43549

I'm going to close this ticket in favor of the 2 new tickets.
