### ISSUE TITLE
Set device orientation as horizontal screen by force doesn't work for ios

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#31528]
Hi,

We expect to set the device orientation as horizontal screen by force, the code is as below. 
 
```dart
void main() async {
  try {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
        .then((_) {
      runApp(BlocProvider<ApplicationBloc>(
        bloc: ApplicationBloc(),
        child: BlocProvider(child: OilApp(), bloc: MainBloc()),
      ));
    });
  } catch (e) {
    debugPrint(e);
  }
}
```
it works fine for Android, but doesn't work for iOS. any ideas? thanks

Yawei

**Comment by dnfield** [comment]
We're missing code here that would force the device to use that orientation if only one is specified.

That said, I'm not sure we should add it.  What would the expected behavior be if you specified multiple orientations?

There's a plugin here that does what you're looking for: https://pub.dartlang.org/packages/auto_orientation

As you can see, the code to do it isn't overly complicated.  Can you give that a try?

**Comment by dnfield** [comment]
(It does seem wrong that we're inconsistent between Android and iOS, but from what I remember they're a bit different in how they handle this - and it seems wrong to me that we're letting Android force it at all, what happens if you say you support 3 of the four orietnations?)

**Comment by 7syw** [comment]
@dnfield 
so far it works fine for iOS after I add one more code line 'AutoOrientation.portraitUpMode();'

Thanks Mate,  Yawei

**Comment by dnfield** [comment]
Great!

**Comment by arturomf** [comment]
@7syw Hi, have you tried this plugin solution in iPad?

**Comment by SinoMiles** [comment]
@7syw that no effect .
