### ISSUE TITLE
Remove Y-axis rounding for lines in LibTxt and floating point hack rounding in framework

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#31707]
Text is currently being rounded in two places:

- LibTxt rounds as a legacy feature (from blink) to better align vertical layouts with pixel boundaries to produce sharper text on low-DPI devices. This is no longer necessary as device DPI has increased significantly in recent years, and we now prefer more accurate layout.

- `TextPainter` applies a rounding we call `_applyFloatingPointHack` to metrics. The reasoning is probably best explained by the todo: 
     > // Unfortunately, using full precision floating point here causes bad layouts
  // because floating point math isn't associative. If we add and subtract
  // padding, for example, we'll get different values when we estimate sizes and
  // when we actually compute layout because the operations will end up associated
  // differently. To work around this problem for now, we round fractional pixel
  // values up to the nearest whole pixel value. The right long-term fix is to do
  // layout using fixed precision arithmetic.

We should remove such rounding sooner rather than later, as it will result in < 0.5px (logical) shifts across almost all text in Flutter. Such a change should eventually be made, and the earlier, the less disruption it can cause.

**Comment by GaryQian** [comment]
cc @jason-simmons @Hixie

**Comment by Hixie** [comment]
I recommend trying to just remove it all and seeing what happens. I would not be overly surprised if nothing noticeably changed in the common case.

**Comment by knopp** [comment]
Removing `_applyFloatingPointHack` would be very nice indeed. I suspect it would improve jumpy text in CupertinoNavigationBar when sliding back. However I do remember trying to remove it a while ago and immediately got hit by tiny overflows.

**Comment by GaryQian** [comment]
Removing `_applyFloatingPointHack` is more likely to cause overflows than removing the rounding in LibTxt. Flutter often lays out with the ground truth being the LibTxt metrics, whereas the framework-side rounding are operations on top of this already rounded ground truth.

Changing either will require a fairly time consuming pass of adjusting hard-coded test values across all of our tests and goldens.

I removed rounding in LibTxt as an experiment, and I am seeing about ~150 broken values in txt_unittests and 104 broken tests in the framework tests. It causes the text to visually shift slightly, which is most noticeable when there are many lines of text, although this shifting can be considered an improvement in both accuracy and precision.

**Comment by GaryQian** [comment]
![](mtp://[usb:001,011]/Internal%20shared%20storage/DCIM/Screenshots/Screenshot_2019-05-02-13-44-45-585_io.flutter.demo.gallery.png)

This is what happens with a simple removal of `_applyFloatingPointHack` with no other changes.

Removing rounding in LibTxt looks harmless in terms of layout though and I should be able to proceed with that in a fairly straightforwards (if not tedious) manner.

Removing both instances of rounding results in 120 broken framework tests, and incorrect layout.

**Comment by knopp** [comment]
If you remove the _applyFloatingPointHack then you need to make sure in each layout calculation that you don't overflow. Also it would be nice to ensure that a Text widget will not shift next widget to subpixel position, as that might cause blurry rendering of images on lower dpi devices. Although maybe that already happens when `devicePixelRatio` is not integer and widgets don't land on pixel boundaries.

**Comment by Hixie** [comment]
I don't understand why removing the hack would make the "SUBMIT" text wrap. We should be setting the width of the paragraph to exactly the width we get back from the layout, which shouldn't trigger another layout of the paragraph. In fact, the fact that it's even possible for this to happen is concerning, because there shouldn't be a codepath by which we can lay out the text twice. We should lay it out once, get the metrics, and paint it, without any possibility of the metrics or layout changing again.

**Comment by jason-simmons** [comment]
The second pass of layout is done by `TextPainter.layout` after the first pass obtains the `maxIntrinsicWidth`.  See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_painter.dart#L431

If you remove `_applyFloatingPointHack`, then the second pass of layout may result in word wrap because `Paragraph::layout` in the engine is truncating the width passed into the framework:
    https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/paragraph.cc#L486

The `floor(width)` originated from an attempt to be consistent with Blink's behavior (including the interaction between `_applyFloatingPointHack` and Blink).  See https://github.com/flutter/engine/pull/5962 and https://github.com/flutter/flutter/issues/18665.

**Comment by GaryQian** [comment]
Since we are no longer required to match Blink, we could consider removing the `floor` operation. Since `_applyFloatingPointHack` is a `ceil` operation, without the floor, we should not see additional word wrapping, although I suppose it is possible a sub-pixel width glyph could be drawn in that additional space, or it is just enough to allow a whole word to fit one line above (compared to current behavior)

**Comment by Hixie** [comment]
If we remove all the hacks (truncating, ceil'ing, rounding, whatever) everywhere, it should all just work, right? I would like us to remove all the hacks.

**Comment by GaryQian** [comment]
As an additional note, there should be places where values go from 32bit to 64bit or vice versa. This could potentially cause issues when the values happen to not convert cleanly that could be difficult to uncover in tests, although I believe the majority of the values used are currently double precision. The rounding is currently masking any existing unclean conversions.

**Comment by Hixie** [comment]
Can we use 64bit throughout?

**Comment by GaryQian** [comment]
Much of the Skia API uses SkScalar which is just a typedef over 32bit float.

**Comment by Hixie** [comment]
Can we make sure we never read back from the 32bit world? Or are we required to as part of how our text work is implemented?

**Comment by GaryQian** [comment]
I believe that reading 32bit values is a core part of the layout algorithm. SkFontMetrics are provided as 32bit floats.We could potentially change all of our variables to use 32bit floats though. Even harfbuzz seems to handle both floats and doubles.

This precision problem may or may not end up being negligible or irrelevant though.

**Comment by GaryQian** [comment]
The LibTxt rounding should be lessened by SkParagraph switch, although the framework level rounding would still be present.

**Comment by olof-dev** [comment]
Can I check what the status of this is? Strange rounding is precisely the type of thing that I suspect might be behind a number of small-but-noticeable text rendering errors I've seen with baseline-alignments. Two example scenarios: 

1. For a `Text` widget with a given font, at a certain font size the relative alignment of the text on the baseline might be correct, but at a different font size it can be fractionally below the baseline. Screenshot, with the same font at size 17.0 and size 20.0 (heavily zoomed in in the emulator, with `debugPaintBaselinesEnabled = true`):

![TextBaselines](https://user-images.githubusercontent.com/66305960/93766053-1fba3b00-fc16-11ea-8679-0ddd9ef49253.png)

2. Incorrect baseline alignments between text and widgets in a `Text.rich`. This seems to happen particularly when there are multiple lines involved. Despite text and the `WidgetSpan`s being set to be aligned by alphabetic baseline, the alignment can be correct on some lines while incorrect on others (with the exact same text and widgets in the different `WidgetSpan`s).

It could be that these issues are caused by something else, but the mismatch in baseline alignment is in both cases very small, and rounding somewhere seems a likely issue.

**Comment by GaryQian** [comment]
cc @mdebbar @jason-simmons

This issue still appears to be a problem after SkParagraph. Is this still viable to fix/remedy?

**Comment by shilangyu** [comment]
Is it currently possible to get the real size without the hack being applied to it? Assuming one would be willing to accept the dangers of floating point

**Comment by LongCatIsLooong** [comment]
There're only a few cleanup tasks left, but the rounding is now [disabled by default](https://github.com/flutter/engine/pull/44544).
