### ISSUE TITLE
Converting a StatefulWidget to a StatelessWidget, then hot reloading, crashes the app

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#31940]
Run the following app:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Stateless to Stateful Hot Reload Crashes App',
    home: Scaffold(
      body: SafeArea(
        child: Home(),
      ),
    ),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Text('foo');
  }
}
```

Then, once the app is started, change `Home` to be a `StatelessWidget`, like so:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Stateless to Stateful Hot Reload Crashes App',
    home: Scaffold(
      body: SafeArea(
        child: Home(),
      ),
    ),
  ));
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('foo');
  }
}
```

... then try to hot reload.  The app crashes.

@devoncarew do we have work on the docket for detecting when a change is likely to _not_ be hot reloadable?  I thought I remember vague discussions along those lines, but I'm not sure if they ever went anywhere.

**Comment by devoncarew** [comment]
We had done some work to first warn, and later visually indicate, that a changed line had not been executed on hot reload; this would mean that that change wasn't represented in the current UI of your app.

The warning turned out to have too many false positives, so was misleading to users. The visual indications were easy for users to miss. We might in the future explore improved visual indicators for non-executed reloaded lines.

We don't have any plans currently to show code changes which can't be reloaded. The user does get feedback after the reload that there were issues, so can choose to restart then (the main issues we were trying to solve above were silent failures).

cc @InMatrix @jacob314

**Comment by tvolkert** [comment]
In this particular case, it's an engine (hard) crash, and I've surprisingly ran into it several times while messing with my for-fun app (I thought I needed a widget to be stateful, then later realized I didn't).

**Comment by devoncarew** [comment]
> it's an engine (hard) crash

That seems like a separate issue; after this crash, you're not able to hot restart?

**Comment by tvolkert** [comment]
Nope, after this issue, the VM process dies, and the app closes.

**Comment by jacob314** [comment]
This sounds like it could be a new regression in hot reload robustness that should be a high priority VM bug.

**Comment by tvolkert** [comment]
I filed https://github.com/dart-lang/sdk/issues/36838 to track the fact that it crashes the engine.

**Comment by tvolkert** [comment]
I'm closing this in favor of the Dart SDK issue.  It's not clear that there's any planned work for detecting when a change was made that will not allow for hot reloading.
