### ISSUE TITLE
Add docs to clarify SwitchListTile `onChanged` behavior

### ISSUE THREAD

**Issue by orosznyet** [flutter/flutter#31984]
## Steps to Reproduce

1. Add the following code to a flutter app (flutter create project will do the trick)
```
SwitchListTile(
  value: false,
  onChanged: (bool value) => print(value ? 'Switch is on': 'Switch is OFF'),
  title: new Text('Toggle'),
)
```
2. Build the app and drag the switch to the "on" state. The log shows the "Switch is on" message.
3. Now, drag the switch to the "off" state. The log shows nothing. 
4. Drag the switch to the "on" state and you can see the "Switch is on" message.

This works the other way around: if the value was initially true, it will only onChaned when it's being set to off.

Also, if you tap the label itself, the onChanged event will get triggered every time, that's okay. But the value in the event will be the opposite of the initial value.

## Logs

Nothing special with, `flutter run --verbose`, nor `flutter analyze`.

```
λ flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.2.1 at c:\dev\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\___\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 191.6014.8
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\ONet\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.26.0

[√] Connected device (1 available)
    • ELE L29
```

**Comment by shihaohong** [comment]
I've only done preliminary research into this so far, but it seems that this does not pose a problem if you do the following: 
```
bool _value = false; // or true
...
SwitchListTile(
  value: _value,
  onChanged: (bool value) {
    print('updating value to $value');
    setState((){ _value = value; });
  },
  title: new Text('Toggle'),
)
```

I believe this is caused by `value` passed into `SwitchListTile` mismatching with the internally managed state. Is there a reason you're passing a constant `boolean` into the switch instead of updating it with `setState`?

**Comment by shihaohong** [comment]
In the meantime, I'll update the documentation with clearer instructions and a more fleshed out sample to highlight proper usage with `setState`

**Comment by chornbe** [comment]
This is absolutely horrible. onChanged should fire NO MATTER the default value / new value. If it changes. onChanged should fire. Period. That's just basic  good design. Otherwise it's a useless one-way switch, and we have to find some other way to call setState()...

**Comment by shihaohong** [comment]
I'm not entirely sure if I'm interpreting you correctly, but based on the context, I think you're saying that even if state isn't passed into the `Switch` correctly, it should still fire `onChanged` when dragging the switch, regardless of whether its mismatched. I will describe my thought process based on that assumption.

I do believe that in a reactive framework, state passed into the `Switch` should have final say in what actually happens. Therefore, in this case, since the `Switch`'s passed in state is mismatched, it's going to behave erratically. In my opinion, I think that the Switch should not move at all if dragged and state is not updated appropriately. Meaning, I agree with you that there could be safeguards against getting into this situation, but I don't think having `onChanged` fire regardless is the solution.

Also, I understand the frustration you are feeling, but please remember to adhere to the [Code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md#code-of-conduct) and be mindful of how you're conveying yourthoughts.

**Comment by chornbe** [comment]
Ok, let’s get this part out of the way first... you’re saying that I’m violating code of conduct for pointing out what is clearly a poor design?

Back to the meat of the situation: forget about initial state, for a moment. Just set that aside, because that is NOT the issue - in EVERY other platform, in EVERY other UI library, in EVERY other language, when a user changes an on-screen object, its changed delegate fires. Pick any single one. Check box in C#, fires. In HTML, fires. In java, fires. That’s what I’m saying. Regardless of the control’s previous value, its delegate fires and the current value of the control comes along. 

My questions remain: how did anyone think this was the right way to go, and how did this not fail a design peer review? It’s bad design. Just because every other platform works a certain way, doesn’t mean it’s the wrong way. Every other one works that way because it’s logical design. 

If you take that as my breaking rules of conduct, then yes, I guess I am, and happy to do it.

This is bad design. The delete should ALWAYS fire, regardless of previous state. 

This is... just... it’s NOTHING but obvious.

**Comment by Hixie** [comment]
@chornbe Our code of conduct (please review it) requires actively pleasant behaviour. Your comments are not actively friendly, and therefore, yes, it is a code of conduct violation.

   https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

If that is unacceptable to you, or if you do not understand why what you wrote is not friendly, then I ask that you please not participate in this community. Thanks.

**Comment by filly82** [comment]
I also think that the `onChanged ` should fire every time. I'm in a `StatelessWidget `and I am unable to use the Switch/SwitchListTitle Widget at all because of the really really weird behaviour. There is no chance to react correctly on switching on/off. Or am I missing something?

**Comment by Roomka** [comment]
Hi @shihaohong , @Hixie 

if I understood correctly from https://github.com/flutter/flutter/issues/31984#issuecomment-488790378 , this implies that SwitchListTile be used cannot use with Flutter Bloc. 

What would be the recommended approach to achieve the right functionality following the next snippet of code?

`BlocBuilder(
    bloc: BlocProvider.of<PreferencesBloc>(context),
    builder: (context, state) {
    return SwitchListTile(
        title: Text('Change Preference Value'),
        value: state.preferenceName,
        onChanged: (bool newValue) {
        preferencesBloc.add(FlagChanged(
            preferenceName: newValue));
        },
    );
    },
)`

Thank you advance,
Roman

**Comment by shihaohong** [comment]
@Roomka I'm not familiar enough with Flutter Bloc to comment, but could you file a new issue to describe the problem that SwitchListTile has when used with Flutter Bloc? That way, it's easier to track since it's particular to the situation you're dealing with. Thank you!
