### ISSUE TITLE
Embedder should provide "buttons" of events

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#32052]
Currently the embedding API does not set "buttons" to pointer events, resulting in `buttons = 0`, which blocks adding support to buttons.

Embedding API should pass the correct buttons to pointer events:
1. Pointer events by mouse should set `buttons` to the buttons pressed. 
1. Pointer events by touch should set `buttons` to 1 (`kTouchContact`).
1. Pointer events by stylus should set `buttons` to 1 (`kStylusContact`) as well as the physical buttons pressed.
1. Buttons should be non-zero when and only when the pointer is down.

Blocking: https://github.com/flutter/flutter/pull/31935
More discussion: https://github.com/flutter/flutter/issues/31884

**Comment by stuartmorgan** [comment]
Currently there's no device type in the embedding API; we could potentially add it as part of adding buttons, but it's probably better to keep this focused specifically on addressing what's needed to unblock #31935, which means we only need to handle mouse-type, since embedding.cc hard-codes the type to mouse currently.

Note that as discussed in the issue linked above, just adding the API for buttons and then passing them through isn't sufficient unless we're willing to have this be a breaking change for everyone using the embedding API.

I think the right approach is to add a new field+constants to the API to allow passing buttons in, but when the struct size indicates that the embedder wasn't built using a version with that field, synthesize button 1 for down and move.

That would be preserve behavior at an ABI level, but would still be effectively an API-breaking change, as upgrading to a new header without changing anything in the client code would regress behavior. The best option I can think of for that would be to still do the synthesis if `buttons` is 0 for a down or move event, but log a warning, so that clients won't be broken, but will get clear guidance that they should update their code to send actual buttons to avoid the synthesis codepath.

@chinmaygarde does that sound good to you?

**Comment by dkwingsmt** [comment]
My takeaway is that:
1. Also synthesize kPrimaryButton for mouse
2. Log a warning for any synthesis
Is that correct?

**Comment by stuartmorgan** [comment]
Your summary of (1) is missing too many details for me to know if your understanding matches my proposal.

For (2), I think we should only warn if the struct size of the event data coming from is large enough to contain the new field, so that we're not adding warnings for people who haven't recompiled since the new API became available.

**Comment by dkwingsmt** [comment]
Sorry I'm confused. When you talk about synthesis, are you refering synthesizing in framework (as in [here](https://github.com/flutter/flutter/pull/31819/files#diff-c1dfac99ccc50aaadb3a3d5fbd299908R50)) or in embedder? Because "struct size" seems like a concept of C++ hence you're suggesting logging by embedder.

**Comment by stuartmorgan** [comment]
Stepping back for a moment: I still think my description in https://github.com/flutter/flutter/issues/31884#issuecomment-488347301 is the right approach to take. My comments here are conflating the two parts. As I said there, only stage 1 is necessary to unblock you, and then you can assign this issue to me to implement stage 2.

> When you talk about synthesis, are you refering synthesizing in framework (as in here) or in embedder?

In `embedder.cc`, as I said [here](https://github.com/flutter/flutter/issues/31884#issuecomment-488355006). The term "embedder" is ambiguous as to whether it means our `shell/platform/embedder/` code, or the many possible 1P and 3P clients using `embedder.h` and the associated library, so I recommend we avoid referring to just 'the embedder' in this discussion.

So focusing just on stage 1, in more specific detail, my suggestion is that you just add the primary button to the event data created in `FlutterEngineSendPointerEvent` for the appropriate change types (which based on your point 4 in the initial comment for this bug I expect would just be `down` and `move`). I expect that's just a few lines of cod in `FlutterEngineSendPointerEvent`, plus adding constants for primary and secondary button somewhere (internal for now). Those constants and the corresponding Dart constants would need cross-referencing comments about needing to stay in sync, as with other pointer data constants we have crossing languages.

(All the struct size checks, conditional logging, adding new APIs to embedder.h, etc. that I brought up above would be stage 2, which would be done by me in a follow-up, and would not block your work.)
