### ISSUE TITLE
Support OS NSURLSession file download for iOS

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#32161]
iOS supports migrating an on-going `NSURLSession` file download from a foreground app over to the OS when the app moves to the background. Flutter should support this either directly, or as a plugin.

iOS background execution docs:
https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

**Comment by matthew-carroll** [comment]
CC @xster @dnfield

**Comment by dnfield** [comment]
I wonder if this is something we could support nicely in the Dart VM instead.  It would be pretty slick if the `http` stuff in `dart:io` could "just work" in this case.  /cc @zanderso

**Comment by zanderso** [comment]
The http implementation in `dart:io` sits on top of `dart:io` sockets rather than sitting on native http client libraries, so the refactor to use `NSURLSession` there would be substantial.

**Comment by gahms** [comment]
To have the http implementation not use NSURLSession is quite bad for a number of reasons.

Some reasons are security related, some related to be a good citizen of the platform, behave as expected by users, administrators and developers, some functional and convenience. If it of any help I could try to spell the reasons out in more detail. 

So I really hope that an NSURLSession based http implementation is or will be on the roadmap. 

Xamarin had the exact same problem with the initial http implementation that was based on the .NET stuff instead of NSURLSession.

**Comment by dnfield** [comment]
It would definitely be helpful to know concrete items that the current implementation lacks (other than being able to shift to background, for example).

It should be entirely possible to, if nothing else, write a plugin that could handle HTTP requests via NSURLConnection instead of dart:io - but then you would have to avoid other plugins or pieces of the framework that are using dart:io directly.

It should also be possible (although perhaps not entirely ergonomic) to have the Darwin part of the http implementation use NSURLConnection etc.

We have another request though to make it possible to plug in other network implementations, particularly to avoid the size of BoringSSL (https://github.com/flutter/flutter/issues/40220#issuecomment-545731459) - I think there's some possibility for intersection here. For example, maybe there's some build of the engine that just delegates the calls to `dart:io` for sockets and HTTP to some other implementation.  This will probably also have problems with ergonomics (e.g. a method throwing an UnsupportedError on some platform or another, or behaving differently because of underlying platform differences). It would be interesting though to see if we could have some kind of flag for doing that - but it would require work on the Dart side first.

**Comment by gahms** [comment]
Ok, here is my take. I am pretty sure there are other good reasons but this is what my skill amount to. I know most about iOS but I know enough about Android that I am pretty sure most of it applies to Android also. Please reach out to me here or otherwise if I am unclear or something needs details.

For a lot of the issues I list here, you would be able to find similar issues and arguments with the UI model of Flutter, that is the way Flutter do not use native widgets. My initial reaction to Flutter was similar to what I outline below and that the best model is to use native widgets. I come from using Xamarin a lot and can see how that model just don't work in practice and how wonderfully the Flutter way works in practice.

With regards to other areas, such as with http, where Flutter hits the OS, I still think it is better to use the OS implementation although the greatness of the UI implementation in Flutter make me less certain.

### Security Related

Apple implements various security features in their http and especially https implementation. Most developers do not care about the fine details in this and should, in my opinion, not be forced to. Security is one of the areas where "I will implement it myself" is not a very good option. It is also best if it is easy to do it the right way.

* App Transport Security (ATS): App developers are nudged to make high security requirements to https or explicitly state (in Info.plist) when exceptions are needed.
* SSL certificates checks: iOS has (as most OS'es) a built-in list of valid root certificates. You cannot do https to a server that does not have a valid trust chain.
* OS installed certificates: With MDM an administrator can push certificates to devices in a secure manner. This can be client certificates or additional root certificates.
* OS configured proxy settings: The user or an administrator (e.g. through MDM) can configure proxy settings and all traffic (http/https) go through this configured proxy.
* VPN: I am not sure at what level this is working in iOS, but it is possible to configure a VPN to be on-demand, for certain apps, for certain domains or IP ranges. This all works without the app being aware or have to do anything. The VPN part will work with any TCP traffic but I am not sure if OS features for activating the VPN will work for custom http implementations that uses TCP directly.

### Be a Good Citizen

All the "security" reasons can also be said to be stuff an app does to be a good citizen of the platform. This is how things are expected to work.

Apple has implemented various features that target e.g. energy consumption, performance and user experience.

I do not know a lot about the details but I think there is throttling on slow or metered connections, prioritization between contestants for the bandwidth and more. 

I am pretty sure that if you go directly to TCP you are circumventing these measures.

### Behave as Expected

If an administrator pushes out a proxy configuration, a certificate or a VPN configuration, it is expected that this configuration is used. If the administrator has to take special care for specific applications to respect this configuration it is a huge nuisance. I guess that for a Flutter app to even respect a proxy configuration it would have to be implemented by the developer?

Similarly a user might set up a proxy for a specific purpose and be disappointed that it does not work. As a developer I often use Charles Proxy to debug for example.

Subtle differences in implementation and varying features (such as HTTP/2 mentioned below) can also lead to unexpected behaviour. In contrast to difference between Flutter and native in UI behaviour, these kinds of differences are much less visible and possibly subtle and for a lot of developers in areas less well understood.

### Functional and Convenience

This github issue is about background download and that is a huge and really important one. Support for HTTP/2 could be another one - I do not know if the dart:io implementation support HTTP/2. Handling of cookies, redirects, long-running downloads or uploads and support for file and ftp schemes could be others.

**Comment by sametvmw** [comment]
Hello all,

Is there any progress about supporting NSURLSESSION? One of the SDK only supports NSURLSESSION then to be able to integrate this SDK then NSURLSESSION needs to be supported.

Thanks.

**Comment by aam** [comment]
https://pub.dev/packages/cupertino_http recently published by @brianquinlan should help here

**Comment by brianquinlan** [comment]
[`cupertino_http`](https://pub.dev/packages/cupertino_http) supports [`downloadTaskWithRequest:`](https://pub.dev/documentation/cupertino_http/latest/cupertino_http/URLSession/downloadTaskWithRequest.html) and [`backgroundSessionConfigurationWithIdentifier:`](https://pub.dev/documentation/cupertino_http/latest/cupertino_http/URLSessionConfiguration/URLSessionConfiguration.backgroundSession.html) but I haven't tested the two together.

I filed a bug to write unit tests for that: https://github.com/dart-lang/http/issues/760

But it would be amazing if you could try `cupertino_http` and create issues for functionality that is missing!

**Comment by brianquinlan** [comment]
[cupertino_http](https://pub.dev/packages/cupertino_http) has been available for over a year now. If it has issues accomplishing a background download use case, please file a bug/feature request in the [`package:http` issue tracker](https://github.com/dart-lang/http/issues/new/choose).
