### ISSUE TITLE
[web] Shadows on flutter_web not rendering like shadows in flutter

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#32215]
**Describe the bug**
Using this exact code on both web and mobile results in noticeably different rendered output.
I expect that the rendering of shadows should be consistent.  The most noticeable difference can be noticed between the `BoxShadow`, but `Material` with elevation seems to render differently as well.    I use both as an example here.
```
void main() {
  runApp(
    Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        mainAxisSize: MainAxisSize.max,
        children: <Widget>[
          Container(
            height: 200.0,
            width: 200.0,
            decoration: BoxDecoration(
              color: Colors.orange,
              boxShadow: <BoxShadow>[
                BoxShadow(
                  color: Colors.black38,
                  blurRadius: 6.0,
                  offset: new Offset(4.0, -4.0),
                  spreadRadius: 0.0,
                ),
              ],
            ),
          ),
          Padding(
            padding: EdgeInsets.only(top: 20.0),
          ),
          Container(
            height: 200.0,
            width: 200.0,
            child: Material(
              color: Colors.lightBlueAccent,
              elevation: 8.0,
            ),
          ),
        ],
      ),
    ),
  );
}
```

**To Reproduce**
Use the code above, and run on web and mobile.  You should notice the same thing as in the images below

**Expected behavior**
Shadows should render similarly if not exactly the same.

**Screenshots**
On the left is Chrome, on the right an iOS emulator:
<img width="924" alt="Screen Shot 2019-05-01 at 4 38 18 PM" src="https://user-images.githubusercontent.com/9346834/57041175-9aed0c80-6c2f-11e9-9727-e85170dd4295.png">

**Desktop (please complete the following information):**
 - OS: `macOS 10.14.4 (18E226)`
 - Browser: `Chrome Version 73.0.3683.103 (Official Build) (64-bit)`
 - Dart Version: `2.2.1 (build 2.2.1-dev.4.0 None)`
 - Flutter Web commit SHA:`ecbdadf118b497f41c4ed4599baa0cc1c1c0fc08`

**Comment by aloisdeniel** [comment]
It also seems that children'shadow is cropped :

### `flutter`

![image](https://user-images.githubusercontent.com/7687231/57677213-9c063c80-7626-11e9-959e-746c44c533d4.png)

### `flutter_web`

![image](https://user-images.githubusercontent.com/7687231/57677112-64979000-7626-11e9-993d-8858816e1720.png)

**Comment by NicTanghe** [comment]
![image](https://user-images.githubusercontent.com/13624265/59554253-7dd28a00-8fa0-11e9-944c-7079bab2d7b2.png)

**Comment by 7Kronos** [comment]
I got also an issue when I add an Image widget. The shadow do not render as blury but solid lines.

**Comment by searchy2** [comment]
The issue is worse when elevation is increased. 

Here, I've set an elevation of 8.

**Android**
![MaxthonSnap20191102163221](https://user-images.githubusercontent.com/19896174/68077302-5fbec800-fd8f-11e9-8590-338d62b371f6.png)

**Web**
![MaxthonSnap20191102163205](https://user-images.githubusercontent.com/19896174/68077305-64837c00-fd8f-11e9-96f0-b10459174866.png)

**Comment by EliasDeuss** [comment]
@yjbanov Thank you for working on this issue.

**Comment by rydmike** [comment]
Happy to find that this is an issue being worked on already. I was considering adding it otherwise. Just as info, the Flutter Community is looking forward to a resolution of this issue as well. It was e.g. recently mentioned in this [tweet](https://twitter.com/ThomasBurkhartB/status/1221786157643706369),  [here](https://twitter.com/DmytroGladkyi/status/1222080597000118274) and [here](https://twitter.com/RydMike/status/1222096904579883009). Here is a link to a brief [gist](https://gist.github.com/rydmike/e7ba470d632d65d096103dc3d91f6529) I made for the tweets, where it is demonstrated as well, but I think this issue has it all covered well enough. I just wanted to give my support and thumbs up 👍 for working on the issue!

**Comment by yjbanov** [comment]
**Update**: as I was trying to understand how shadows worked in Flutter for mobile, I discovered [an issue there too](https://github.com/flutter/flutter/issues/51237). My current plan is, instead of emulating what mobile does, I'll do something "reasonable". For example, we blur too aggressively, our HTML shadows do not match canvas shadows, they do not work on Safari canvas, and our bounds estimator does not match either (which is what I think causes the clipping). I'll fix these issues, but the shadows will still be a bit different from mobile.

**Comment by rydmike** [comment]
Thanks for looking into this issue and working on it. The things you found and mention in issue [51237](https://github.com/flutter/flutter/issues/51237) are indeed a bit different from this case. I have however seen the matter you mention in the new issue you made as well and will add some comments to it there.

I think this issue should focus on getting shadows on HTML to look the same as they do on Android/iOS (and Desktop) given the same Flutter shadow or material elevation input. As far as I have seen given the same input the shadows and elevations on Android/iOS/Mac/Win are fairly close already, but web is totally different to the extent that it is broken, it looks totally wrong and cannot even be used as the look will deviate a lot from what was intended if designed on mobile/tablet/desktop.

As for the issue in [51237](https://github.com/flutter/flutter/issues/51237) I think that is more a matter of how the imaginary light source that casts the elevation shadows is placed and that the current placement is not so suitable for larger surfaces. I will drop a comment on it there with some examples as well.

**Comment by ds84182** [comment]
Shadows are also incorrectly clipped in Chrome when using a custom ShapeBorder, which can be seen in #50508's example images.

This is because clip-path clips the box shadow also, so you need to use CSS filter drop-shadows on the parent element (see https://css-tricks.com/using-box-shadows-and-clip-path-together/).

**Comment by cbracken** [comment]
Re-openened post-revert until re-land. /cc @yjbanov

**Comment by IoanaAlexandru** [comment]
Wanted to add another simple example of this occurrence:

`Padding > Container with BoxDecoration (with BoxShadow)`

![image](https://user-images.githubusercontent.com/25504811/76152649-79b84080-60ca-11ea-95a2-3492b22db905.png)

<details>
<summary>Code to reproduce</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(30.0),
          child: Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                  boxShadow: [
                    BoxShadow(color: Colors.black, blurRadius: 12.0),
                  ],
                  shape: BoxShape.circle,
                  image: DecorationImage(
                      fit: BoxFit.fill,
                      image: NetworkImage(
                          'https://images.theconversation.com/files/93616/original/image-20150902-6700-t2axrz.jpg')))),
        ),
      ),
    );
  }
}
```
</details>

**Comment by alexpavelm** [comment]
I believe the issue of shadow clipping comes from the parent not using specified constraints because it is empty and html tags it as irrelevant. To fix this, you can simply add a property to a parent Container, best for this case:

`color: Colors.transparent`

This makes the html draw the entire container, therefore not clipping it's child container, so you can add padding to the child and make enough space for the shadows.

```
Container(
  width: 100,
  height: 100,
  color: Colors.transparent,
  child: Padding(
    padding: const EdgeInsets.all(15.0),
    child: Container(
        decoration: BoxDecoration(
            boxShadow: [
          BoxShadow(color: Colors.black, blurRadius: 12.0),
        ],
            shape: BoxShape.circle,
            image: DecorationImage(
                fit: BoxFit.fill,
                image: NetworkImage(
                    'https://images.theconversation.com/files/93616/original/image-20150902-6700-t2axrz.jpg')))),
  ),
),
```

**Comment by LucasAschenbach** [comment]
Is this fix already available on the beta channel? Somehow, I just encountered this very same issue in my app:
![grafik](https://user-images.githubusercontent.com/37406743/76807246-060de600-67e4-11ea-8726-52a4f968b4fc.png)

**Comment by EliasDeuss** [comment]
No the beta and stable channel haven't been updated in 2-3 months for some reason. @LucasAschenbach
