### ISSUE TITLE
Plugin for local storage 

### ISSUE THREAD

**Issue by bevc101** [flutter/flutter#32219]
Add support for dart:io library for the Web?

**Comment by jonahwilliams** [comment]
It would be helpful to know which specific functionality you are using in dart:io that is otherwise missing, or what problem you are trying to solve.

For example, for HTTP requests I would recommend package:http. Implementing dart:io HttpClient is likely infeasible since the web has much more restricted capabilities here.

**Comment by bevc101** [comment]
The ability to read and write files to disk.  Perhaps there is another way to do it than using dart:io and the File class.

**Comment by jonahwilliams** [comment]
On the web that would likely use local storage, which is a very different API than a filesystem. We should provide a plugin to use local storage eventually.

**Comment by bevc101** [comment]
Thanks for the update.  Should we just close this bug then?

**Comment by jonahwilliams** [comment]
We can re-use this as a request for a plugin for local storage? cc @kevmoo

**Comment by kevmoo** [comment]
> We can re-use this as a request for a plugin for local storage? cc @kevmoo

I'd rather not. This is a MUCH bigger issue than just storage... networking, platform, etc

**Comment by chertov** [comment]
I dream about websocket connection in flutter web!

**Comment by yjbanov** [comment]
If anyone feels that local storage is important in the short term, let's open a dedicated issue for that. I'll close this issue though.
