### ISSUE TITLE
Browser Forward button not enabled

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#32248]
**Describe the bug**
You can use the back button to step to the previous page in your Flutter app, but after pressing "back" the "forward" button does not become enabled on my browser.

**To Reproduce**
Open the Flutter Gallery app in your browser. Tap to navigate to any page. For example, "Style", then "colors". Hit the back button. The forward button does not become enabled after navigating to the new page.

**Expected behavior**
I expect the forward button to become enabled after I navigate to the previous page. 

**Desktop (please complete the following information):**
 - OS: mac
 - Browser Chrome 73.0.3683.86
 - Dart Version 2.2.1-dev.2.0.flutter-None on "macos_x64"
 - Flutter Web commit SHA: 04e53468fd60f6d7613a0745fba2dc14eac676c9

**Comment by Levi-Lesches** [comment]
Any updates on this?

**Comment by andesappal** [comment]
Hi there! When should this be completed? Thanks!

**Comment by andesappal** [comment]
Also, when should Tesler's copy and paste function work for Flutter web? Thanks!

**Comment by mahmoudsalah37** [comment]
i have same issue

**Comment by sujithkanna** [comment]
Hi, any update on this?

**Comment by 12people** [comment]
@yjbanov Why was this labeled as P5 instead of P4?

This is a pretty serious UX issue, as people have come to expect their browser forward button to work on all websites.

Rather than treating it as a nice-to-have feature request, I'd like this to be treated with the severity of a bug, at the very least. A UX bug is still a bug.

**Comment by Akashmathwani** [comment]
It's been pending since a long time. Any ETA for this ?

**Comment by andesappal** [comment]
Wow this is still open?

**Comment by ochmist** [comment]
Anything on this?

**Comment by ch-muhammad-adil** [comment]
Hi, Any update on this?

**Comment by okamototomoyuki1988** [comment]
Flutter cannot be used as a web page until this bug is fixed.
I would appreciate it if you could correct it.

**Comment by chunhtai** [comment]
This issue should be fixed if you use Router widget, see https://github.com/flutter/flutter/pull/63424

**Comment by steeling** [comment]
FYI might want to update the FAQ's that say this is not ready

https://flutter.dev/docs/development/platform-integration/web#how-are-forward-and-backward-buttons-presented-in-the-web-ui

**Comment by chunhtai** [comment]
open this issue to keep track doc update

**Comment by mariamhas** [comment]
assigning to myself, already working on updating FAQs and this specific question

**Comment by mariamhas** [comment]
docs updated

**Comment by jpv123** [comment]
For me, this issue is still not closed. Some of us want to use Navigator 1.0 for the web with the onGenerateRoute, onUnknownRoute, and routes param. This is because Navigator 2.0 can be extremely difficult to implement in some cases

However, using the Navigator 1.0 approach (which is supposed to be supported and not deprecated), the forward button is still not enabled which is a serious UX problem.

Do we know if there is any workaround besides using Navigator 2.0?

**Comment by chunhtai** [comment]
There is no planed work to support the forward button in nav 1, and I doubt we will spend time doing it in the future. Our current plan is to improve the usability of nav 2. See https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research
