### ISSUE TITLE
[in_app_purchase] iOS: queryPastPurchases returns error when device is offline

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#32292]
in_app_purchase 0.1.0+1:

When iOS device is in flight mode queryPastPurchases() returns error "Cannot connect to iTunes Store".

On Android queryPastPurchases() is returning past purchases when device is in flight mode.

**Comment by mklim** [comment]
Thanks for the bug report!

We can't really return purchases on iOS in this case since that's not supported by the underlying SDK. But it looks like this is throwing a `PlatformException`. We should probably instead handle the exception and return a `PurchaseDetailsResponse` with an empty `pastPurchases` list and a `PurchaseError` with the problem.

/cc @cyanglaz

**Comment by cyanglaz** [comment]
@mklim Totally makes sense! I will work on this. Assigning to myself.

**Comment by benadrasni** [comment]
Is it possible to use receipt stored locally to get past purchases?

https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2

**Comment by cyanglaz** [comment]
@benadrasni If you do want to retrieve the receipt data, you can call `SKReceiptManager.retrieveReceiptData()` to get the receipt on iOS

**Comment by cyanglaz** [comment]
Fixed in 0.1.1. Closing the issue now. If any related issue is found after updating,  please feel free to reopen or open another issue with details.
