### ISSUE TITLE
ExpansionPanel List Styling Options Limited to cardColor

### ISSUE THREAD

**Issue by ardenn** [flutter/flutter#32293]
I have been trying to use flutter's `ExpansionPanelList` widget, however, styling options are quite limited. The widget automatically uses `cardColor` attribute of the current theme and from what I see, the only option to apply custom styles/widgets is to override the `_ExpansionPanelListState`, which I can't because it is private. As per this [S.O comment](https://stackoverflow.com/questions/56030464/flutter-expansion-panel), currently the only solution is to copy the entire `expansion_panel.dart` file and override the widgets's `build` method.

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue, the color for the `ExpansionPanel` is decided inside the `MergableMaterial` where we can first add a new property to change the color, and later we can expose that in `ExpansionPanelList`. 

I found one more issue in the implementation, that it completely ignores the `CardTheme.color` which should be the first priority, and it only focuses on `ThemeData.cardColor`.  So, in the first PR to add a new property to `MergableMaterial` I would also fix that. WDYT?

**Comment by shihaohong** [comment]
Sounds good! I would first add the feature to modify the color by hand. In terms of fixing the color to first reference `CardTheme.color`, make that a separate change but first write a design doc, since it'd be a breaking change. It might also make sense to create a new issue to track that since it's not related to the original issue.

**Comment by shihaohong** [comment]
Also something to consider is being able to modify every card's color separately instead of having the entire list specified. For example, maybe I'd want `ExpansionPanelList.tileBackgroundColor` to be yellow, but maybe I want one or two of them to be green or pink, so make sure to take that into consideration as well.

**Comment by AyushBherwani1998** [comment]
> 
> 
> Sounds good! I would first add the feature to modify the color by hand. In terms of fixing the color to first reference `CardTheme.color`, make that a separate change but first write a design doc, since it'd be a breaking change. It might also make sense to create a new issue to track that since it's not related to the original issue.

Sure, I'll create a new issue to keep track of it.

**Comment by AyushBherwani1998** [comment]
> 
> 
> Also something to consider is being able to modify every card's color separately instead of having the entire list specified. For example, maybe I'd want `ExpansionPanelList.tileBackgroundColor` to be yellow, but maybe I want one or two of them to be green or pink, so make sure to take that into consideration as well. I'm not sure if that's easy or not to do, but would be nice to add along with your intended/mentioned behavior.

That's a good suggestion. I had a look at the source code of `MergeableMaterial`, and these are my findings. Instead of having `color` property defined inside `MergeableMaterial` it would make more sense to declare it inside the `MaterialSlice`. Instead of adding color [here](https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L542) and [here](https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L614) it would make more sense to add color [here ](https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L594)when the `MaterialSlice`s are being added to `slices` which are then added to `ListBody`.

Since `MaterialGap`s cannot be the first in the `MergeableMaterialItem` list, take a look [here ](https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L245) the color will always be added to the slices.

Once, we have added the above property, we can have `color` property inside `ExpansionPanel` and when we are creating `MergeableMaterialItem` list in `ExpansionPanelList`, we can add the color to `MaterialSlice` which will be taken from ExpansionPanelList[index]. Take a look [here](
https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/expansion_panel.dart#L533)

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted the PR for the first part. Looking forward to your reviews :)
