### ISSUE TITLE
[firebase_auth] Migrate linkWithCredential function from FirebaseAuth to FirebaseUser

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#32317]
Firebase authentication plugin should have `linkWithCredential` function inside the user object, currently, it is on the FirebaseAuth class which makes no sense. As the linking should be done to an existing user, adding the function to the user object would make more sense. 

Its similar approach to the native firebase auth SDKs on Android and IOS. Documentation to the `linkWithCredential` on Android is [here](https://firebase.google.com/docs/auth/android/account-linking).

**Comment by awazgyawali** [comment]
Merged flutter/plugins#1584

**Comment by ebologger** [comment]
It's using current user not the user linkWithCredential method invoked on. 

In my case when linkWithCredential fails due to credential is linked with another user I want to unlink that credential from previous user and then link again.

```
FirebaseUser user = await _auth.currentUser();
user.linkWithCredential(credential); // this fails with credential linked with another user

FirebaseUser oldUser = await _auth.signInWithCredential(credential);
oldUser.unlinkFromProvider(....)

// this tries to link credential to 'oldUser' not 'user' since oldUser is the current signed in user
user.linkWithCredential(credential)

```

**Comment by awazgyawali** [comment]
How can firebase handle multiple users? The function is always called on the current signed in user. Please correct me if I am wrong.

**Comment by ebologger** [comment]
linkWithCredential method is on FirebaseUser instance not on FirebaseAuth. So logically calling something like userA.linkWithCredential(credential) should link credential into userA not currentUser i think.

In my case, my currently signed in user wants to connect Facebook account. But that facebook account is already connected to different user. What i want is sign in using facebook account (which will sign out first user). And then unlink facebook from second user and link it to first user. Since first user is not currently signed in user & at this moment i don't have the credential to first user anymore, i can't just sign in and link. So order for me is first link fb to first user then sign in using that credential. Can you point me to right direction, maybe i'm going all wrong?


Here's what's stated in firebase doc. There's prevUser and currentUser. 
```

The call to linkWithCredential will fail if the credentials are already linked to another user account. 
In this situation, you must handle merging the accounts and associated data as appropriate for your app:

FirebaseUser prevUser = FirebaseAuth.getInstance().getCurrentUser();
mAuth.signInWithCredential(credential)
        .addOnCompleteListener(new OnCompleteListener<AuthResult>() {
            @Override
            public void onComplete(@NonNull Task<AuthResult> task) {
                FirebaseUser currentUser = task.getResult().getUser();
                // Merge prevUser and currentUser accounts and data
                // ...
            }
        });
```

**Comment by kroikie** [comment]
@awazgyawali

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/377. Any further collaboration will be done there.

**Comment by parmarravi** [comment]
hello , The Problem still exists. Is there a way to solve it ?
