### ISSUE TITLE
Use Custom View inside AppBar

### ISSUE THREAD

**Issue by codekeyz** [flutter/flutter#32337]
Is there any way, I can customize the AppBar Widget to look like that of Google PlayStore AppBar?
Something like this form would be appreciated 
```dart
appbar: AppBar(
  child: CustomView() 
) 
```

**Comment by rshrc** [comment]
I am guessing you just want a whole new widget to replace the whole AppBar and make it custom
```
import 'package:flutter/material.dart';

class CustomAppBar extends StatelessWidget {
  final String title;

  GradientAppBar(this.title);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: barHeight,
      decoration: BoxDecoration(color: Colors.blue),
      child: Center(
        child: Text(
          title,
        ),
      ),
    );
  }
}
```
and then inside the Scaffold you can just
```
return Scaffold(
      body: Column(
        children: <Widget>[
          GradientAppBar("treva"),
        ],
      ),
    );
```
Let me know if your question meant for something else

**Comment by codekeyz** [comment]
This approach will be cumbersome. It would be like rebuilding the current Flutter AppBar Widget. I want to be able to pass a CustomView to the AppBar Widget through an extension like this
```dart
new Scaffold(
       appBar: AppBar(
              child: CustomView() 
       ) 
);
```

**Comment by dnfield** [comment]
You could try using `AppBar(title: CustomView())`, but if that's not working you probably want to just create your own special AppBar widget.  AppBar, as designed, is meant to make it easy to conform to the material specification rather than support specializations of it.  It's probably possible to do that as is, but it also wouldn't be terribly difficult to reuse a lot of the AppBar code to achieve your own effect (which may not quite be the Material spec but might be close!).

I suspect you'd get better support on this on StackOverflow, or one of the other channels mentioned at https://flutter.dev/community.  Please feel free to re-open this issue if there's something missing here though, or if you really are looking for a feature request for the app bar!

**Comment by codekeyz** [comment]
It works fine by passing `CustomView()` through the `title`. Thanks @dnfield
