### ISSUE TITLE
SystemNavigator.pop should support being animated

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32382]
I think we semi-arbitrarily decided to implement SystemNavigator.pop as being non-animated https://github.com/flutter/engine/blob/c12b917e95074aec4700dd5554563bc84f93ecc2/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L205

But it makes it hard to conform to UINavigationController animations symmetrically in add to app. 

We should be able to make this signature change while remaining backward compatibility.

**Comment by IchordeDionysos** [comment]
This would be great to have.
Looks weird if one screen is built in Flutter and is not animating.

**Comment by IchordeDionysos** [comment]
Do you want to implement this by allowing developers to override whether "popping" should be animated?

For example calling `SystemNavigator.pop(animated: true)` instead of just `SystemNavigator.pop()`.
This change will at least allow app developers like us to animate the `FlutterViewController` if they use add-to-app.

If this works for you, I will try to implement this into the Flutter engine.

**Comment by xster** [comment]
Indeed. I think with the right default and the right method call argument handling, we can make this non-api-breaking. I also suspect there might be nothing we need to do on Android. 

Would be happy to take a PR if you'd like to send us one.

**Comment by xster** [comment]
Right, it seems like us piping pop to activity.finish() on Android makes it always animated so nothing to do on Android.

**Comment by blasten** [comment]
cc @matthew-carroll @gaaclarke

**Comment by xster** [comment]
@gaaclarke you did this right?

**Comment by gaaclarke** [comment]
yep
