### ISSUE TITLE
GestureDetector on tap not call many time

### ISSUE THREAD

**Issue by fengqiangboy** [flutter/flutter#32397]
I have write a demo, and the GestureDetector ontap don't call many time

Here is the demo project: [https://github.com/fengqiangboy/flutter_flare_button](https://github.com/fengqiangboy/flutter_flare_button)

**Comment by fengqiangboy** [comment]
I test it on Android device

**Comment by jason-simmons** [comment]
I tried running this example and it seemed to work as expected.

One thing to watch out for is Android's chatty log detector.  The example app was printing "tap" on each double tap event, and Android may notice the duplicated log lines and filter some of them out.

Try adding a counter to the log message so that each message will be unique.  This should work around the log filter.
