### ISSUE TITLE
When does Kotlin support flutter?

### ISSUE THREAD

**Issue by HandsomeXi** [flutter/flutter#32427]
When does Kotlin support flutter?

**Comment by stuartmorgan** [comment]
See https://flutter.dev/docs/resources/faq#why-did-flutter-choose-to-use-dart for discussion of the language choice for Flutter.

**Comment by oky2abbas** [comment]
Dart has nothing to say about big, well-built languages like Kotlin and swift, and I also want to change the official flutter language to Kotlin or swift as soon as possible, or Google will introduce a new language.

**Comment by forresthopkinsa** [comment]
I think JRebel demonstrates that you can have stateful hot reload in a compiled language

**Comment by 12people** [comment]
@stuartmorgan 

I can understand why Google initially chose Dart for Flutter. That said, that doesn't necessarily prevent Flutter from supporting other languages too. Frameworks like GTK+ or Qt have long enjoyed support for multiple languages, and even Android's SDK has moved to officially support 2 languages — Java and Kotlin.

It's important to keep in mind that people coming from Android development may have a lot of code written in Kotlin. It could make life a lot easier for them if they could reuse some of their code and didn't have to learn a new language while at it. Not only that — Kotlin has a lot of great language features that Dart doesn't have yet, which is why many Kotlin developers might want to stick with Kotlin.

Now, the article pointed to above says that Dart was chosen because of these features:
- Developer productivity.
- Object-orientation.
- Predictable, high performance.
- Fast allocation.

Kotlin seems to meet all of these requirements as well.

I suggest that this issue is reopened and Kotlin as a second supported language is seriously evaluated.

**Comment by yuridiniz** [comment]
I have an app that has Google Maps as its main functionality. I may be wrong, but it seems to me that it would solve several problems that we have today at Flutter.

One of the problems we have is in relation to the animation of the markers, it is impracticable to animate all the markers via Dart, due to the delay of calls to the platform. An alternative that we tried was the use of widgets as fakes markers, it is possible, but due to the onCameraMove event coming from the host, the delay is noticed at the moment the user moves the map, so, it is also not a solution.

Anyway, I don't want to stick to what I faced with Google Map.

In general, there would be no delay between MethodChannel, as there would be no MethodChannel, since Skia could  be rendered directly through Kotlin

This could lead to the perfect marriage between Kotlin Multiplatform ❤️  Flutter
