### ISSUE TITLE
Does flutter_web support any networking? Ref #32412

### ISSUE THREAD

**Issue by QoLTech** [flutter/flutter#32430]
> I am trying to make a web request for data, but the http package isn't supported. Is there a way to perform a network request? Image.Network seems to work just fine, but looking at the source for that, I couldn't discern how to replicate what it was doing for network calls.
> 
> Any help is appreciated!

> `package:http` should work. You can also use [HttpRequest](https://api.dartlang.org/stable/2.3.0/dart-html/HttpRequest-class.html) from the `dart:html` library. Please reopen if it doesn't work.

> I get this error when building anything that uses `package:http`
> `Heartbeat: 14.1s elapsed, 895/898 actions completed.
> build_web_compilers:entrypoint on web/main.dart: Skipping compiling flutter_web.examples.hello_world|web/main.dart with ddc because some of its
> transitive libraries have sdk dependencies that not supported on this platform:
> 
> http|lib/src/multipart_file.dart
> http|lib/src/io_client.dart
> 
> https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
> Heartbeat: 15.7s elapsed, 2833/2833 actions completed.`

**Comment by QoLTech** [comment]
Reference this issue [https://github.com/flutter/flutter/issues/32412](https://github.com/flutter/flutter/issues/32412)

**Comment by QoLTech** [comment]
Looks like I needed to specify using http: ^0.12.0 in my pubspec. Silly of me to assume that it would use the latest version, I guess.

**Comment by raghukas** [comment]
Adding http in the pubspec didn't work for me. I am getting an error "build_web_compilers:entrypoint on web/main.dart: Skipping compiling market_web|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that not supported on this platform:" as soon as I add "import 'package:http/http.dart' as http.

**Comment by QoLTech** [comment]
I was getting the same issue. Add this to your pubspec - http: ^0.12.0

You're getting an older version for some reason that doesn't support flutter_web.

**Comment by yjbanov** [comment]
Is there anything left to do for this issue? It seems the issue was that an older version of `package:http` was picked up.

**Comment by natebosch** [comment]
The latest package:http should not have this problem since it is using config specific imports. Can you confirm that you are on the latest? `pub deps` or `flutter packages pub deps` should tell you the versions.

**Comment by yjbanov** [comment]
`package:http` should be working on the latest Dart/Flutter SDKs. Closing.

**Comment by annaacc** [comment]
Hello, 
I am getting the same error too.

uild_web_compilers:entrypoint on web/main.dart: Skipping compiling line2_dashboard_hybrid|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

testproject|lib/services/http/httpWebClient.dart
http|lib/src/multipart_file.dart
http|lib/src/io_client.dart

I am supposed to use the latest Flutter version 
environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

**Comment by yjbanov** [comment]
@annaacc can you please follow @natebosch's instructions from https://github.com/flutter/flutter/issues/32430#issuecomment-494083023 to make sure you are using the correct versions?

**Comment by annaacc** [comment]
Hi @yjbanov 
I am using -- http 0.12.0+2

**Comment by natebosch** [comment]
> I am using -- http 0.12.0+2

The error message you pasted reports an unsupported SDK import from `http|lib/src/multipart_file.dart`. The file at `0.12.0+2` is: https://github.com/dart-lang/http/blob/0.12.0%2B2/lib/src/multipart_file.dart#L5-L16

There is no import to `dart:io` there. What information are you using to determine that this is the version of the package you have?

> It was actually "import 'dart:io';" what was causing the same exception.

It looks like you might also have a direct import to `dart:io` from `testproject|lib/services/http/httpWebClient.dart` based on the error. Is that the only one you saw after upgrading to `0.12.0+2` of `http`? If so it's something you'll need to solve.
