### ISSUE TITLE
Track the overall frame time (latency) between the start of VSYNC (in the UI thread) and the end of Rasterizer::Draw (in the GPU thread)

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#32447]
Currently our flutter driver performance tests only have UI thread `VSYNC` times (`frame_build_time_millis` in `timeline_summary.json`), and GPU thread `Rasterizer::Draw` times (`frame_rasterizer_time_millis` in `timeline_summary.json`).

Tracking them separately and ensuring them to be no more than 16ms (for 60fps) only guarantees smoothness, but not latency.

Moreover, something could happen between `VSYNC` and `Rasterizer::Draw`.

So as a first step, we could simply track the sum of  `VSYNC` and  `Rasterizer::Draw` times for a frame. In the end, we should directly compute the latency by comparing two timestamps.

**Comment by eseidelGoogle** [comment]
It looks like a bunch of work was done here.  Should this still be open?

**Comment by liyuqian** [comment]
Closing this as https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html allows computing the overall frame time (latency).

**Comment by sanlittt** [comment]
@liyuqian 
we're thinking about using this as a measure of the FPS：https://github.com/flutter/flutter/issues/32447  
but worry  that the FPS value calculated here (frame UI time + frame Raster time < 16.66ms)  is lower than what the user really feels due to multiple sharedBufferStack mechanisms
Do you have any Suggestions？
