### ISSUE TITLE
scoped_model_counter sample should be converted to provider

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter#32506]
Now that scoped model is no longer our "default" state management choice, the scoped_model_counter sample app should either be removed from flutter/samples or converted to use provider.

@filiph, since you wrote the original, I'm assigning this to you. Feel free to send it back if you don't have time or don't want to bother. 😄

**Comment by filiph** [comment]
Thanks for reminding me, I'll take this.

**Comment by filiph** [comment]
Ok, I've done the work in three stages, so that we can a) link people to the minimal possible change, b) make sure links are correct.

* https://github.com/flutter/samples/pull/81
* https://github.com/flutter/samples/pull/82
* https://github.com/flutter/samples/pull/83

Note that https://github.com/flutter/samples/pull/82 and https://github.com/flutter/samples/pull/83 are marked WIP so that nobody accidentally reviews/approves them before their predecessor(s). But otherwise, they are ready to be reviewed from my point of view.

**Comment by filiph** [comment]
Fixed with #83. I accidentally forced push the last PR, sorry for that!
