### ISSUE TITLE
Mouse entering/exiting a desktop window causes shadow change

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#32529]
## Problem
Mouse entering or exiting a window of Flutter on Linux causes Tooltip shadow to change. See below, notice the button on the bottom right corner:
![Flutter_-Shadow-bug-caused-by-mouse-connection-_1_](https://user-images.githubusercontent.com/1596656/57562012-3a06b800-7344-11e9-928f-41931407ff19.gif)

## Cause
Mouse entering and exiting the window triggers mouse connection and disconnection respectively, which changes `_TooltipState._mouseIsConnected`.

## Environment
- gLinux
- Framework: https://github.com/flutter/flutter/pull/31631
- Engine: 6e3c0431410ce3ae1e1ee7cf8c139fefd34a6cde
- Embedder: https://github.com/google/flutter-desktop-embedding/pull/355 , linux example with the following patch:
```
// flutter_embedder_example.cc L71
  flutter_controller.window()->SetHoverEnabled(true);
```

**Comment by stuartmorgan** [comment]
@gspencergoog It seems like I've interpreted add/remove differently than that code does. I remove the device when it's no longer over the Flutter area, because there's no other concept of "exit". If I just stop the stream of hover events, then, e.g., a hover effect at the edge of the window would not clear on exit.

Can we reconcile that, or do we need new phases specifically for enter/exit? (I'm curious why the shadow of an element that the mouse isn't anywhere near would change as a result of the existence of a mouse; that seems surprising.)

**Comment by gspencergoog** [comment]
No, there's some other bug going on here.  What you're doing (adding/removing the pointer when you enter/leave the window) should be correct, but I suspect that the FAB isn't handling hover correctly, or that something is wrong with the AnnotatedRegion that hover uses to add a layer for hit testing.  Just because `_mouseIsConnected` is true shouldn't be sufficient for triggering the elevation change, it should have to be inside the bounding box of the control as well.

**Comment by stuartmorgan** [comment]
@gspencergoog Assigning to you, but feel free to reassign if there's a better owner. I'd like to make sure it's on someone's plate, since #32835 is going to make this very prominent (everyone running the example from FDE will see it immediately).

**Comment by gspencergoog** [comment]
OK, makes sense.  I'm going to submit https://github.com/flutter/flutter/pull/32776 in a few minutes, which should make it a lot less garish.

**Comment by jonahwilliams** [comment]
Is the shadow change a result of us switching from the framework shadow to the engine shadow, or is there something else going here?

**Comment by stuartmorgan** [comment]
While testing some other mouse handling, I've noticed that there are actually three different shadow effects:
1. A light shadow when the mouse isn't in the window (the initial state of the animation above)
2. A medium shadow when the mouse is in the window but not over the FAB (the end state of the animation)
3. A heavy shadow when the mouse is over the FAB

So it's not just a bounding box issue, or 2 and 3 would be the same.

Separately from the question of why `kAdd`/`kRemove` is transitioning between 1 and 2, I'm curious why there are three separate states in the first place rather than just two.

**Comment by stuartmorgan** [comment]
See duplicate linked just above for some more info. There's very strong evidence that the heavier shadow is because the widget is being drawn twice.

**Comment by shyndman** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L2667

Looks like this line could be the culprit. Passing a noop paint function corrects the behavior, although I'm not sure what other implications that might have.

**Comment by dkwingsmt** [comment]
@shyndman I'll put the `pushLayer` into the `else` clause, but yes, there is definitely something wrong with it. Also it only fixes the 2nd shadow. I'm taking a look at the 3rd shadow...

**Comment by shyndman** [comment]
The third shadow is likely an intentional change. FABs change elevation on hover.

**Comment by dkwingsmt** [comment]
You're absolutely correct. I'll submit a fix (and see if we can find a way to test it).

**Comment by shyndman** [comment]
Good afternoon. Any movement?

**Comment by dkwingsmt** [comment]
@shyndman I've written a fix and related tests, but I didn't post it because a large PR https://github.com/flutter/flutter/pull/36217 is changing the same place and is about to be merged. Hopefully that PR merges soon and I'll submit this fix asap after it. If that PR has to stall then I'll rebase the fix to master and submit.

**Comment by shyndman** [comment]
Thanks for the update!
