### ISSUE TITLE
Textfield selection handle(s) are covered by keyboard

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32551]
Flutter version

```
[✓] Flutter (Channel master, v1.5.9-pre.205, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

Issue Screenshot:

![flutter_05 copy](https://user-images.githubusercontent.com/1555508/57567917-e1522080-7412-11e9-9d35-ec16574e2d7b.png)

![flutter_06 copy](https://user-images.githubusercontent.com/1555508/57567922-edd67900-7412-11e9-8180-fe468caba1ea.png)

Expected: 

I think the selection handles should cover the keyboard instead. Otherwise, it makes very hard to select. 

(Btw can I make the handles smaller? It looks too big to me. )

**Comment by daniilguit** [comment]
Agree, in GMail (which I think is native android App) those markers are on the top of keyboard
![photo_2019-05-13_13-29-17](https://user-images.githubusercontent.com/231284/57615016-56446800-7583-11e9-93d0-e6aaabd99cb9.jpg)

**Comment by justinmc** [comment]
I'm looking at what we can do to improve this right now.  As a workaround in the meantime, keep in mind that you can use `scrollPadding` on your TextFields to manually give your selection handles a bit more room when the field is scrolled to.

**Comment by justinmc** [comment]
Unfortunately, it's not possible for Flutter to show the selection handles on top of the keyboard right now because the keyboard sits entirely on top of the Flutter view.

Instead I've merged a PR that will give more space between the input and the keyboard so overlap shouldn't happen anymore.  It should look like this, and combined with recent work on the selection handles, should be a lot more usable:

Material             |  Cupertino
:-------------------------:|:-------------------------:
![flutter_04](https://user-images.githubusercontent.com/389558/58734675-f20c0b80-83ac-11e9-85c2-c584ae596b50.png)  |  ![flutter_03](https://user-images.githubusercontent.com/389558/58734676-f20c0b80-83ac-11e9-9b8c-24d4b1f8d92c.png)
