### ISSUE TITLE
How to pass a function with parameters

### ISSUE THREAD

**Issue by nsmith1024** [flutter/flutter#32553]
Hello,

I need to pass a function with parameters to be executed in another class when widget is tapped. The code is below. 

Basically im building a list of card widgets, where for each card i want to make a function with unique parameters that gets called when tapped. I have a common card function in another class that generates the card GUI, and i want to pass the function to it with the unique parameters that gets called when the card is tapped. In this case i want to call showTaskDetails(uniqueTask) when any of the card is tapped.

When i run the code, and tap a card, i get exception of "closure calls with mismatched parameters" i guess the problem must be calling func() with no parameters when there is actually parameters in the function being called? But how do i pass the function with parameters to another function so it can get called? Seems i need something like a delegate function definition so it knows which parameter to pass..... or something.... dont know how to do it...anybody knows?

class MyClass {
....
Widget _buildListItem(BuildContext context, DocumentSnapshot data) {
 final task= Task.fromSnapshot(data);
  return Padding(
     key: ValueKey(record.taskID),
     padding: const EdgeInsets.symmetric( horizontal: 0.0, vertical: 0.0),
     child: GlobalClass.makeCard(title,(task) => showTaskDetails(task))); //<<<<<<-----------
  }

 void showTaskDetails(Task task)
 {

 }
}

class GlobalClass{
....
static Widget makeCard(String title,Function func)  ///<<<<<<<<<<<<
  {
    return Widget(
     ....
    onTap: () => func() // <<<<<<<<<<<<< --- crash, needs Task parameter
 }

**Comment by nsmith1024** [comment]
Never mind, figured it out

https://api.dartlang.org/stable/2.3.0/dart-core/Function/apply.html

**Comment by patelkrunal78** [comment]
That is the type of functions that can be called with zero arguments and which does not return a useful value. That does not seem to be what you want. It's not entirely clear what you do want since the program isn't syntactically valid, but would this work for you:

class MyClass { 
  static doSomething(int i) { /* ... */ }
  MyOtherClass myOtherClass = new MyOtherClass(doSomething);
}
class MyOtherClass {
  final void Function(int) callback;
  MyOtherClass(this.callback);
  void callCallaback() { callback(5); }
}
Here we define the type of the callback field to be the type of functions that can be called with one integer argument and which returns no useful value. The doSomething method has that type, so it can be assigned to callback.

You could also use a typedef to name the function:

typedef Int2VoidFunc = void Function(int);
// or: typedef void Int2VoidFunc(int arg);
class MyOtherClass {
  final Int2VoidFunc callback;
  MyOtherClass(this.callback);
  void callCallaback() { callback(5); }
}
The effect is exactly the same, it just allows you to use a shorter name for the function type, but that only really makes sense if you use it a lot.

https://icetutor.com/question/pass-a-function-with-parameters-to-a-voidcallback
