### ISSUE TITLE
/_getVMTimeline not available in flutter run profile

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#32570]
in flutter 1.5.4 & linux;
the url of flutter profile changed from http://127.0.0.1:43377    to http://127.0.0.1:43377/q24EfVk8x6U=/   
but in timeline.js which still tries to call    http://127.0.0.1:43377/_getVMTimeline, but it is not there ,
as it is at  http://127.0.0.1:43377/q24EfVk8x6U=/_getVMTimeline

for in timeline.js 
the code looks 

 var requestUri = 'http://' +
                   parser.hostname +
                   ':' +
                   parser.port +
                   '/_getVMTimeline';

in fact use relative path is more flexiable

**Comment by kangwang1988** [comment]
@wanjm 
I've reproduced this issue using flutter 1.5.4 and find it fixed in latest master.

It should be fixed by commit: https://github.com/dart-lang/sdk/commit/eeb7a92b212441e4f61aa4b4e7b724f16055c141

I'm closing this issue now.
If you can reproduce this issue using the latest master, please leave a comment so we can reopen it.

**Comment by wanjm** [comment]
@kangwang1988  能告诉我timeline.js编译后被压缩到哪儿去了， 我本地改下，现在主要学习flutter，不想太散；谢谢！
