### ISSUE TITLE
Multiple FirebaseMessaging crash issues reported by Google PlayStore

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#32577]
APK built using latest stable version `1.5.4+hotfix2-stable`

After uploading build to android playstore beta channel, here is what I see.

![screencapture-play-google-apps-publish-2019-05-12-13_15_19](https://user-images.githubusercontent.com/14252381/57579539-0a2df080-74bb-11e9-9423-5ccf372272b9.png)

**Comment by yuridiniz** [comment]
I had a problem similar to Google Maps, I realized that I was giving a "method not found" message in the log during APK generation.
I solved it by disabling ProGuard.
I do not know if it's exactly the same problem as yours, because of the logs I did not get to publish to see what happened
But try to do this and use the Firebase Test Lab to see if you managed to work around the problem

**Comment by kroikie** [comment]
@tiholic

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1061. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
@tiholic did you manage to solve it?
