### ISSUE TITLE
Add Flutter Existing app without debug, profile and release mode

### ISSUE THREAD

**Issue by longhoang2984** [flutter/flutter#32630]
Hi Flutter team,

How can I add Flutter app to Existing App Withou Debug, Release and Profile mode. Currently, My App using Development, QA, Staging And Production Configuration.

**Comment by MartinNiederl** [comment]
Is this a Flutter problem, or why are you asking here?

Go to StackOverflow or ask the community at one of the locations listed here: https://flutter.dev/community.
The Flutter Team certainly doesn't have time to look at every "problem" that others can answer as well. Because of these kinds of questions, the issue page becomes more and more cluttered, and really important ones get overlooked.

**Comment by kf6gpe** [comment]
Closing, as this is a support request and not directly relevant to Flutter's build modes.
