### ISSUE TITLE
Clean up github issues

### ISSUE THREAD

**Issue by ethanblake4** [flutter/flutter#32661]
There are too many open issues in the Flutter repo, with many having no response or being incomplete. It makes it difficult to find issues that are active or under consideration. The Flutter team should consider dedicating some time to this, as the [VSCode team did](https://code.visualstudio.com/updates/v1_28). This would involve closing issues that are no longer relevant, fixing trivial bugs that take no longer than half an hour to fix, and categorizing old issues to make them more easily searchable.

**Comment by yuridiniz** [comment]
There are many issues that could be solved by posting a question in StackOverflow, a feeling that serious problems are being abandoned.
I think it's a good idea

**Comment by c0h1b4** [comment]
I agree with you 100%. The issue stack here is getting totally out of control.

**Comment by glancer000** [comment]
Agree 100%

**Comment by anondev32** [comment]
Waiting for A.I. to automatically sort and delete dupilcates and help requests.

**Comment by MichaelPriebe** [comment]
https://github.com/marketplace/stale

**Comment by KlausJokinen** [comment]
@Hixie

**Comment by KlausJokinen** [comment]
Any updates regarding this "issue". @Hixie 
Sorry if I'm pinging wrong person here.

**Comment by timsneath** [comment]
Thanks: this is a good question and we certainly understand where it's coming from.

Our incoming rate has grown dramatically over the last few months as the project has grown in popularity; in August 2019 alone, a record 2,200 issues were opened. We closed 1,600 issues in the same period (roughly fifty per day), which was also a new record; but that still leaves us in deficit.

So we’ve now brought on extra help with our front-line triage to filter and redirect technical questions (which are better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or other communities), identify issues that need additional information, and appropriately label issues that are ready for us to work on. This should help us, but we also recognize that as a successful open-source project, there’s always likely to be more issues than we can immediately address. Our plan is to keep triage in place to get a better signal from the issues that are filed, and bring them up in our team triages and critical issue triage meetings so we’re better aware of what people are experiencing when they use the product and can prioritize accordingly.

Also, as much as tools like [Stale](https://github.com/marketplace/stale) (thanks for the link, @MichaelPriebe) can be useful, we have a philosophy of not closing bugs merely because they are “old”, which means comparing raw numbers here to other open source projects isn’t always an apples-to-apples comparison. We often keep issues open if they provide information for fixing future issues or provide input into future designs. In that sense, we're similar to other popular projects like [Visual Studio Code](https://github.com/Microsoft/vscode/issues) which also have many open issues but are healthy, well-maintained and high-quality. 

Hopefully this explains our philosophy in a little more detail.
