### ISSUE TITLE
Add RasterCache option to RepaintBoundary widget

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#32662]
## Use case

Although [RepaintBoundary](https://docs.flutter.io/flutter/widgets/RepaintBoundary-class.html) is a key widget in improving Flutter’s performance on the UI thread, it’s not well-utilized on the GPU thread. For example, only the lowest-level `RepaintBoundary`, which corresponds to leaf-level engine PictureLayer, currently triggers the raster cache on the GPU thread. In certain scenarios, raster caching can make a big performance difference -- e.g., 20%-30% in our *home_scroll_perf average_frame_rasterizer_time_millis* benchmark.

With the recent introduction of retained [EngineLayer](https://docs.flutter.io/flutter/dart-ui/EngineLayer-class.html)s, we now have the opportunity to use `RepaintBoundary` to trigger more raster caching on the higher level `RepaintBoundary`. Similar to the recent opacity and PhysicalShapeLayer optimizations, we may be able to improve our performance by multiple times.

## Proposal

Add a `RasterCache` option to the `RepaintBoundary` widget, so the developer can decide when to engage the optimizations. This option is not only to override our current raster cache heuristics, which are not very smart or reliable, but also allows developers to elect to make the tradeoff between quality and speed themselves. For example, when there’s a rotation transformation above the RepaintBoundary, raster caching the whole `RepaintBoundary` means that we’re no longer drawing pixel-perfect graphics, but the performance gain may significantly outweigh the quality drop (see https://github.com/flutter/flutter/issues/24627).

Things to implement:
  * [ ] Write performance tests for the scenarios where we’d like to see improvements. This will guide our implementation and check our correctness and performance.
  * [ ] Add a `RasterCache` option to the `RepaintBoundary` widget and wire it up between the framework and the engine.
  * [ ] Enable the engine-side raster caching based on the option.
  * [ ] Document the feature, and update Github issues to reflect the performance improvement, to teach our developers how to do it themselves.

Proposed by @liyuqian

**Comment by liyuqian** [comment]
Thanks for polishing the proposal! Closing https://github.com/flutter/flutter/issues/27952 as a duplicate and add a reference to https://github.com/flutter/flutter/issues/27677

**Comment by liyuqian** [comment]
Paste Yegor's comment here for convenience: "It sounds a lot like will-change. Wondering if we could just map the proposed RasterCache to it."

**Comment by arsen** [comment]
Any progress on this?

**Comment by liyuqian** [comment]
@flar : I have the same question on the progress :smile: 

We just received some internal bug b/137395062 last week, and its current solution cl/260167188 is to manually take a snapshot of the blurred widget. Adding RasterCache option to RepaintBoundary widget would:
1. Make developer do much less work for these kind of issues. Potentially just one line of change on `RepaintBoundary` instead of 50 lines of code to snapshot manually.
2. Make CPU/GPU do much less work as our current snapshot requires GPU->CPU->GPU copies. And according to comments in cl/260167188, Flutter also strangely requires an unnecessary raw->PNG->raw encoding/decoding process. (I'll write a test and probably create a issue on that encoding issue).

**Comment by flar** [comment]
I'm looking into revisiting my RepaintBoundary caching work. Meanwhile I think that @chinmaygarde had some suggestions or feedback on faster ways to snapshot widgets that might help with the solution for b/137395062

**Comment by jason721017** [comment]
Thanks for the proposal. Any ETA on the implementation?
While we can try to find workaround in the scenario like b/137395062, it is often counter intuitive. It is hard to be certain on what will be raster cached or not. Having an option in RepaintBoundary will be very helpful.

**Comment by zanderso** [comment]
@liyuqian @flar What is the status of this issue? What is the remaining work to do?

**Comment by flar** [comment]
I've been working on various internal caching mechanisms that would work automatically behind the scenes and fixing up errors in our existing caching mechanisms. Since RepaintBoundaries aren't visible to the engine, a significant rework of our layer mechanism would be required to make them visible so that they can control caching.

**Comment by fredlee12345678** [comment]
@flar I just want to know the status of this issue, is it ready for us?

**Comment by ravenblackx** [comment]
A related suggestion! Rather than a boolean RasterCache option, how about a cacheStrategy option, with `CacheStrategy.default` being the current behavior of "trying to figure out the best option itself", `cacheStrategy.raster` for the people wanting that previously in this bug, and for me, `CacheStrategy.noCache`, which paints the child the normal way on the existing buffer as if RepaintBoundary wasn't present.

The distinction between `CacheStrategy.noCache` and not having a `RepaintBoundary` is for the case of non-overlapping widgets, let's say `animatingWidget` and `staticWidget[1-10]`. With no `RepaintBoundary`, all ten `staticWidget`s repaint every frame because animatingWidget is updating. With a `RepaintBoundary` on `animatingWidget` there's a buffer allocated for `animatingWidget`; the buffer isn't providing anything useful because `animatingWidget` is repainting every frame anyway, but the `RepaintBoundary` is preventing the other widgets from repainting when they don't need it. So the `RepaintBoundary` serves a purpose, but the buffer does not.

The buffer, in this case, incurs a nontrivial memory cost and maybe also a performance cost.

**Comment by Ibtesam-Mahmood** [comment]
@liyuqian @flar Is there any update on this issue?

**Comment by mj-hd** [comment]
As a workaround, I created a widget that attaches cache hints (isComplex, willChange) to the current/parent RepaintBoundary like this:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// set `isComplex`, `willChange` hints to current DisplayList
class RasterCacheHint extends SingleChildRenderObjectWidget {
  const RasterCacheHint({
    Key? key,
    this.isComplex,
    this.willChange,
  }) : super(key: key);

  final bool? isComplex;
  final bool? willChange;

  @override
  void updateRenderObject(
    BuildContext context,
    _RasterCacheHintRenderObject renderObject,
  ) {
    renderObject.isComplex = isComplex ?? false;
    renderObject.willChange = willChange ?? false;
  }

  @override
  RenderObject createRenderObject(BuildContext context) =>
      _RasterCacheHintRenderObject(isComplex, willChange);
}

class _RasterCacheHintRenderObject extends RenderProxyBox {
  _RasterCacheHintRenderObject(bool? _isComplex, bool? _willChange)
      : isComplex = _isComplex ?? false,
        willChange = _willChange ?? false;

  bool isComplex;
  bool willChange;

  @override
  void paint(PaintingContext context, Offset offset) {
    // we need this line to generate a PictureLayer to set the hints
    context.canvas;

    if (isComplex) {
      context.setIsComplexHint();
    }

    if (willChange) {
      context.setWillChangeHint();
    }

    super.paint(context, offset);
  }
}
```

**Comment by fzyzcjy** [comment]
Hi, I wonder whether the `toPictureSync` will solve this problem?

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
