### ISSUE TITLE
Demos for each component and possibly a playground for prototyping/preview.

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#327]
Each component should have some - ideally interactive - demo on the website. 

It would be even more amazing if there could be a hackable playground and the demos run in there. The playground would allow developers to quickly preview and prototype with layouts, components and styles.

@abarth

**Comment by afandria** [comment]
I support this as well.

I personally do not have a good intuition for how widgets in Flutter stretch/center/align, so I would find a playground to be a massive time-saver. In general, the Flutter playground would allow quick experimentation to see how new layouts (widget trees, themes, etc.) look. If the UI could update on the fly, that would be even more helpful.

In order to preload a widget tree or "screen" into the playground, we might use something along the lines of `debugDumpApp`. Instead of the tree printout, it would produce the code needed to recreate that tree in the playground. (From there, it would be possible to tweak each "screen".)

**Comment by sethladd** [comment]
It's out of scope to provide a web version of Flutter, thus an interactive demo on the website isn't likely. :(

Instead, we are looking at ways to make building Flutter apps more iterative, interactive, and live. cc @lukechurch 

Will close this in the meantime.
