### ISSUE TITLE
flutter.gradle is incompatible with jetifier/androidx

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32714]
Our flutter.gradle has an addFlutterTask as a project.afterEvaluate. Though that would have added the Flutter engine too late to let jetifier convert it if there are androidx elements in the wrapper project.

**Comment by xster** [comment]
cc @mklim, I suspect this is doubly needed because of plugins involved in https://github.com/flutter/plugins/pull/1138. 

It basically means the build.gradle pulled in for the plugins have androix in their dependencies.

The Flutter engine itself is implemented in terms of android.support.v4. And there's no place during the build process to let jetifier convert the Flutter engine.

**Comment by mklim** [comment]
I'm not 100% that afterEvaluate is the root or only cause of the jetifier incompatibility. I think something about our subprojects is also related.

Previously I had refactored gradle.dart so that plugins were all built as separate targets without using `subprojects`, but still using `afterEvaluate`. flutter/flutter#29460 There were other non-jetifier related issues with the PR that kept it from landing (described in that PR), but Jetifier was working there on account of building the plugins as aars instead of including them as subprojects.

@dnfield did some more work on this at flutter/flutter#29849 and found that the only thing that seemed to matter in some cases was `compileSdkVersion`, but I don't know if that's because it side stepped Jetifier needing to run at all or something else. We've discussed it offline, it may be that subprojects are still viable for jetifier but there's some way of including them t

This is strongly related to flutter/flutter#29328, a lot of the gradle issues are discussed there.

cc @dnfield

**Comment by dnfield** [comment]
My suspicion is that Jetifier worked in that case because we didn't try to do as much in a single afterEvaluate.  It's hard to be sure though.

**Comment by mklim** [comment]
Yeah, potentially. I did still keep the [`afterEvaluate` block for adding `flutter.jar`](https://github.com/mklim/flutter/blob/f898aac2d422d9a4c0c880185eccdecec2e5403d/packages/flutter_tools/gradle/plugins_init.gradle#L17) in the PR. But there could be some other thing happening in `afterEvaluate` that's breaking the interaction.

**Comment by xster** [comment]
Related #31189, https://github.com/flutter/flutter/issues/23586

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/23586
