### ISSUE TITLE
vscode/flutter suggestions (intellisense) no longer smart since last vscode update

### ISSUE THREAD

**Issue by gkrawiec** [flutter/flutter#32723]
This might be related to the last vscode update and suggestions now also coming from other modules, but now suggestions almost never suggest Widgets.
For example if I type "Containe" the suggestion list will still not suggest "Container()"
![Screenshot 2019-05-14 19 52 17](https://user-images.githubusercontent.com/645451/57737358-d05b1680-7681-11e9-907a-a6108e376419.png)
Here is MaterialApp()
![Screenshot 2019-05-14 19 51 53](https://user-images.githubusercontent.com/645451/57737366-d4873400-7681-11e9-9c94-ce9121df0aec.png)
Row
![Screenshot 2019-05-14 19 56 42](https://user-images.githubusercontent.com/645451/57737544-6f800e00-7682-11e9-8fbe-3c7c57ccc6f7.png)
but the same problem happens with all widgets I've tried. If I complete it myself, then the properties are suggested correctly
![Screenshot 2019-05-14 19 54 09](https://user-images.githubusercontent.com/645451/57737422-0bf5e080-7682-11e9-9dfd-40f4b3883bc0.png)

**Comment by gkrawiec** [comment]
I found issue #32572 which suggested to restart the IDE. Which I did, and indeed this fixed the problem. Is this a vscode or flutter plugin issue?

**Comment by gkrawiec** [comment]
This happened again today. It fixes itself after restarting vscode.

**Comment by danbydesign** [comment]
I can confirm that this is happening as well.

**Comment by SeanErvinson** [comment]
Also experiencing this problem. After the last vscode update version 1.34.0

**Comment by gkrawiec** [comment]
it seems this starts to happen every time I remove and then add a folder to a workspace.

**Comment by DanTup** [comment]
@gkrawiec If you can reliably reproduce this, could you enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer), reproduce it and then open an issue at https://github.com/Dart-Code/Dart-Code with the log? Thanks!

**Comment by gkrawiec** [comment]
It doesnt seem to be doing it anymore on my machine. There was an update last week, though I didnt pay attention to what it was.
I will close this and reopen if I notice the issue comes back.

**Comment by DanTup** [comment]
There was a memory leak in VS Code prior to 1.35 that could result in the editor slowing down over time (and eventually crashing), though I wouldn't have expected it to cause this.

There are some additional improvements to completion coming in the next version of the VS Code extension (for ex. [filtering out all the "duplicates"](https://github.com/Dart-Code/Dart-Code/pull/1789) that appeared due to being re-exported by multiple libs) - you could try them out with [the latest preview release](https://github.com/Dart-Code/Dart-Code/releases).

If you do see strange things around this again, please do open issues. If you think they're specific to VS Code, you can open them at https://github.com/Dart-Code/Dart-Code.

**Comment by 0rAX0** [comment]
I've been having issues with this for a while now. Not sure if this is the right place to put the file but here it is:

[dartlog.txt](https://github.com/flutter/flutter/files/3316705/dartlog.txt)

I have a widget that I want to wrap with a GestureDetector but I'm not getting auto-complete. Before today autocomplete would stop working for all widgets everywhere.

**Comment by DanTup** [comment]
@0rAX0 it's best to open a new issue rather than post on the bottom of a closed one. Since this is code-completion related though, please raise it at https://github.com/Dart-Code/Dart-Code and include the log file. Please also include a screenshot of where you're invoking completion and what you see (eg. press Ctrl+Space to force completion to appear and take a screenshot of what appears). Thanks!

**Comment by msreekm** [comment]
same issue here, restarting vs code fixed it.

**Comment by 7elven** [comment]
> same issue here, restarting vs code fixed it.

don't work

**Comment by edex96** [comment]
The problem persist with this version.
Is there any workaround I can do while it's getting fixed?

```
Version: 1.39.0
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:57:43.593Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by DanTup** [comment]
Please see the comment above https://github.com/flutter/flutter/issues/32723#issuecomment-504977963. There's not enough information here to investigate, so we need a clear description of the problem in a new issue. Completion is not handled by Flutter, so please raise issues in the Dart-Code repo for VS Code and flutter-intellij for IntelliJ/Android Studio.

**Comment by edex96** [comment]
@DanTup Sure. 
But I'm not really sure this is a problem with dart extension.

----------- My problem is --------
Code completion works but (ctrl+space) triggered "code suggestion" doesn't work.

---------- What I did to diagnose ------------
I'm using a Hackintosh with this setup
dart ext: 3.5.1
flutter ext: 3.5.1
vscode: 1.39.0
os: Catalina 10.15

And my friend is using a MacBook with the same setup as mine only the os is different
os:  Mojave 10.14

And I've tried on another friend's MacBook with Catalina on it I reproduce the same problem.


------- Sum up ---------
(ctrl+space) triggered "code suggestion" works on my friends' laptop but doesn't work on mine.
This problem started occurring when I updated from Mojave to Catalina.

So I think the problem is Catalina consumes (ctrl+space) key at the os level so it doesn't pass to vscode.

**Comment by DanTup** [comment]
@edex96 if that's the case, then it also doesn't sound like a Flutter issue.

That said, I just tested on my MacBook (which is Catalina) and I can't repro - pressing Ctrl+Space opens the completion list as expected.

You should test it with another language in VS Code - eg. open a JS file and press Ctrl+Space. If completion still doesn't work there, then it does sound like a VS Code issue and you should file an issue there. If it works everywhere except Dart, then please do open an issue in the Dart-Code repo and we can do some more digging. I don't think it's likely to be a Flutter issue (Flutter isn't involved much in code completion, since the Dart SDK handles all of the language support for editors).

**Comment by samuel-arna** [comment]
Sorry for my english, i am Brazilian,
But i try to explain my solution...

1. Run Android Studio as root
in my case 
`cd /Applications/Android\ Studio.app/Contents/MacOS/`
then run it as root user by executing
`sudo ./studio`
2. Update Dart and Flutter Plugins
3. Restart IDE (in my case VSCODE and Android Studio works fine)
4. (Hint) When write a Widget don't forgot ',' after widget ( i.e. `Container([ "without suggestions"]` => `Container(["with suggestions"]),` ) 

Hope this helps
