### ISSUE TITLE
Slider thumb is clipping incorrectly in gallery app.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#32784]
I noticed that inside of an expansion panel, the slider thumb is being clipped to the ink splash.  It doesn't happen in the "Sliders" page of the gallery, so it has something to do with context.
![image](https://user-images.githubusercontent.com/8867023/57813688-d1458400-7725-11e9-9a8e-3cfaf520785b.png)

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
The intrinsic height of the slider is the max of the track, thumb, and overlay. The overlay wins here with height 48dp. But the value indicator gets painted to the canvas of the context, and on the slider demo page the context is the whole screen.

How can this work so that the value indicator always paints outside of its boundaries?

**Comment by HansMuller** [comment]
Perhaps we need to disable clipping when drawing the value indicators.

**Comment by clocksmith** [comment]
The slider value indicator now draws in the overlay after #52663
