### ISSUE TITLE
Make it convenient to create a FlutterActivity with an existing engine

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32870]
Explore making an engine reuse in FlutterActivities possible without subclassing FlutterActivity. 

For instance letting FlutterActivity have a `static createIntentWithEngine(Engine engine)`

Which puts the engine in a static map with hash. getFlutterEngine checks the map when that intent type is used. 

Figure out a way to prevent leaks.

**Comment by matthew-carroll** [comment]
We should discuss this. I don't think I like the idea of bringing static behavior into Activitys. I also don't want to entangle the concept of an Activity with the concept of engine caching. If we're going to offer engine caching, it should be an independent capability.

Since this ticket is based on your attempt to use the new embedding, and finding it cumbersome to extent FlutterActivity, it would be helpful to start this issue with what you did, and why you think its cumbersome.

**Comment by xster** [comment]
I like the idea of making this composable like an ExistingEngineIntentBuilder or some such.

**Comment by matthew-carroll** [comment]
That still requires an Activity to have god access to static stuff. I think we should chat in person about this goal.

**Comment by athornz** [comment]
A good approach might be to pass a flag or an engine 'tag' to the activity, which requires implementing an interface in the application class, and providing the engine to reuse there?

**Comment by matthew-carroll** [comment]
For the record of this thread, since we're getting some external additions, I'll articulate the specifics of what is implied in this ticket.

First, the application development goal that is being discussed is the re-use of a `FlutterEngine` instance across multiple `Activity`s. This is 100% doable today, and it can be done with a subclass of `FlutterActivity` that requires about 3-5 lines of code. That said, we do not currently offer any kind of `FlutterEngine` cache, so either you'd have to write that (maybe 10-15 lines of code), or we could provide that as a standalone class.

This ticket is suggesting that instead of requiring such a subclass, that `FlutterActivity` itself have the capability to statically cache `FlutterEngine`s baked into its definition. 

I do not think such an addition to `FlutterActivity` is a good idea. There will be `FlutterActivity`s that do not use a static cache, e.g., every full-Flutter app. Moreover, whose to say that the cache API we come up with will suit all caching needs? If it doesn't, then people are not just subclassing `FlutterActivity`, they're also overriding the caching logic that we baked in. 

I'm not entirely sure why subclassing is seen as something to avoid. The Android framework is fundamentally based on it. But if, for some reason, we really don't want developers to have to subclass anything while still getting a caching ability, then what I would recommend is that we ship our own subclass of `FlutterActivity`, e.g., `EngineCacheFlutterActivity`, which provides the desired behavior. But we should not be in the business of expanding `FlutterActivity`s API surface without dramatic cause. We will regret it.

**Comment by xster** [comment]
Ya, composing this behavior via a FlutterActivity subclass or a separate builder class which caches sounds good.

**Comment by matthew-carroll** [comment]
Closing via https://github.com/flutter/engine/pull/10481
