### ISSUE TITLE
Spawned isolates should have access to Mojo-backed services

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3294]
Isolates created via Isolate.spawn() do not appear to have access to the objects exposed by the MojoServices.takeXXX methods.  For example, the rootBundle global object (exposed by asset_bundle.dart) is null in spawned isolates.

Logic running in spawned isolates may have valid uses for these services, so we should try to find a way to expose them.

**Comment by krisgiesing** [comment]
@jason-simmons @abarth

**Comment by j9brown** [comment]
So in general these services can only be used by one isolate at a time (though you can Clone() an ApplicationConnector).

If you want to pass capabilities to the new isolate, you may have to arrange to transfer them yourself, or perhaps proxy the requests you actually care about.

Keep in mind that the isolate may be acting like a sandbox of some kind so there might be reasons it should / shouldn't be able to access certain capabilities.  In general, it seems safest to me if all capabilities have to be passed explicitly after the isolate is spawned so that every new isolate is least-privilege by default.

**Comment by krisgiesing** [comment]
Right, I'm not dictating the method of exposure here. I'm just flagging that we should have some way to accomplish this overall goal.

I thought about manually proxying through sendPorts, but this has the disadvantage of incurring a copy cost for data blocks. For some operations involving reduction of large data sets, that may defeat the purpose of spawning an isolate.

**Comment by sethladd** [comment]
fyi @kasperl

**Comment by j9brown** [comment]
*nod*

We should offer some way to pass Mojo handles between isolates, if we don't already.  Then for services that we want to access in multiple places, we can introduce a Clone()-like mechanism to obtain another message pipe endpoint for the same service, like ApplicationConnector.

**Comment by krisgiesing** [comment]
If/when this bug is fixed, we should update `examples/layers/services/isolate.dart`.

**Comment by eseidelGoogle** [comment]
We've been slowly removing mojo from our public apis in flutter (but still using it for our own services).  Unclear if that changes the need for this bug.

**Comment by krisgiesing** [comment]
Wrapping Mojo APIs with Flutter-specific APIs doesn't affect this, I don't think.  Whatever tries to reference the MojoServices.takeXXX methods will just get null back (IIRC, hopefully doesn't just crash) so the Flutter-specific wrapper code would fail.

**Comment by Hixie** [comment]
Closing this on the basis that Mojo doesn't exist.
We should presumably make sure they can access FIDL services but we can track that as part of the Fuchsia work.
