### ISSUE TITLE
Make iOS cocoapods integration easier

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32993]
Adding to existing Android app is fairly simple via include_flutter.groovy. But iOS is a bit more cumbersome.

If the user doesn't already use CocoaPods, the user has to:

- pod init
- copy a line invoking Flutter module project's podhelper.rb 
- pod install
- disable bitcode in the outer project
- add some steps in the outer project's build phases

It would be nice to have a single command that does this (in the same way that pod install makes a bunch of changes to your xcode project). 

We can reuse cocoapod's cocoapods/xcodeproj to modify the xcode project. 

Also consider renaming the xcode phase to something less generic like Embed Flutter.

**Comment by xster** [comment]
@jmagman this one is what we talked about today

**Comment by xster** [comment]
Repurposing this bug since it was based on the presumption that we need to perform all these steps. But since https://github.com/flutter/flutter/pull/36793 simplifies it a bit, they can be manual as long as it's easier.

**Comment by jmagman** [comment]
> Repurposing this bug since it was based on the presumption that we need to perform all these steps. But since #36793 simplifies it a bit, they can be manual as long as it's easier.

Agreed!  I would prefer any changes needed to the host app to be explicit since only the developer knows the correct place to put the Flutter logic.  For example, they wouldn't need to pod install Flutter or disable bitcode for all their targets (notification extension, even a sticker pack!)--only the targets embedding Flutter.
https://github.com/flutter/flutter/pull/36793 handles "add some steps in the outer project's build phases" but I think the other ones should make it manual.

**Comment by jmagman** [comment]
Once https://github.com/flutter/flutter/pull/39503 and the docs are updated, the bitcode setting will no longer need to be changed in the host app.
Is there more to track here, @xster?

**Comment by xster** [comment]
Nop, I think we're good. Let's close this.
