### ISSUE TITLE
Expose embedder API on desktop

### ISSUE THREAD

**Issue by handicraftsman** [flutter/flutter#33004]
## Use case

I am trying to build a Wayland compositor using wlroots which can use a flutter application as its graphical shell by providing plugins for rendering windows, pushing notifications etc.

Since I am rendering compositor shell, it exists in a context which is bound to the whole screen (like surfaceflinger in android) and not to a window which is created by the prebuilt desktop embedder. Sadly I cannot just implement my own embedder using provided APIs, because my PC is too old to compile flutter engine in reasonable time.

## Proposal

Please, expose embedder API (`embedder.h`) into Flutter SDK and add a backend angnostic prebuilt library (like that is done by imgui and nuklear).

**Comment by stuartmorgan** [comment]
There are already prebuilt embedder libraries, separate from the desktop shells:
https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders

We do not plan to have both the shell API and the embedding API within the *same* prebuilt library, as they are very different levels of abstraction.

**Comment by handicraftsman** [comment]
Okay, thanks!

**Comment by JakeSays** [comment]
@stuartmorgan what do you mean by "shell api"?

**Comment by stuartmorgan** [comment]
It looks like the [proper Flutter term](https://github.com/flutter/flutter/wiki/Glossary) is 'embedding' not 'shell'. Specifically for desktop what I mean is the API surface of FlutterMacOS.framework, flutter_windows.dll, and flutter_linux.so.

(I think the symbols are currently exported even though the header isn't included, but if so that's a bug that will be fixed at some point.)
