### ISSUE TITLE
Reconcile FlutterEngine/DartExecutor/BinaryMessenger between Android and iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33099]

**Comment by xster** [comment]
This relates to #26007 where it's not possible to make this VC leak on Android since the view doesn't implement the binary messenger.

**Comment by xster** [comment]
Specifically on Android, a FlutterActivity has an engine. The engine has a dart executor which is what runs a dart entrypoint and what implements binarymessenger. On iOS, the engine runs a dart entrypoint directly and is a binarymessenger too. But the FlutterViewController is also a binarymessenger and delegates to the flutter engine as well.

**Comment by gaaclarke** [comment]
> On iOS, the engine runs a dart entrypoint directly and is a binarymessenger too. But the FlutterViewController is also a binarymessenger and delegates to the flutter engine as well.

https://github.com/flutter/engine/pull/9419 . Helped this a bit since the FlutterViewController and the FlutterEngine are no longer binary messengers.

**Comment by matthew-carroll** [comment]
@gaaclarke Have you made all the changes for this that you think are appropriate? Or are you still investigating API refactors?

**Comment by gaaclarke** [comment]
Not actively looking into it.  Here is a proposition for you though, we could make a "BinaryMessenger getBinaryMessenger()" method on FlutterEngine in android to make it more like ios, instead of making people use the DartExecutor directly that way.  In fact, hiding the concrete type of the BinaryMessenger is something we did on iOS and android could benefit from it as well.  How does that sit with you?

**Comment by matthew-carroll** [comment]
Let's get the team together on Thursday and see if we can come up with a definition of done for this. I'm not sure I see any reason to alter the Android side at this point. And the `FlutterEngine` already provides a BinaryMessenger via `getDartExecutor()`. We now have customers depending on it, and all 1P plugins are in the middle of migrating to it. So my suggestion would be to only change things that are demonstrably erroneous at this point. I don't really have any strong opinions about making iOS match, but I do think a definition of done is important so that we know when we can close this issue.

**Comment by gaaclarke** [comment]
> We now have customers depending on it

That can be said of both API's.

> already provides a BinaryMessenger via `getDartExecutor()`

Yea, the point I'm trying to make is that isn't very clear and shouldn't be up to the clients to know that a DartExecutor is a BinaryMessenger.  Also, it ties our hands a bit when compared to keeping the implementation of BinaryMessenger in our hands.

> I do think a definition of done is important so that we know when we can close this issue.

Sounds good to me.

**Comment by gaaclarke** [comment]
https://docs.google.com/document/d/1uRCvbE5_p1zErZibKNUV70E5ySQbSQ3SSPt-D0-B5To/edit?usp=sharing . Design doc for proposing the change to Android's BinaryMessenger.

**Comment by Hixie** [comment]
What is the problem we're trying to solve here?

**Comment by gaaclarke** [comment]
> What is the problem we're trying to solve here?

@xster isn't available right now, he would be the authority.  My take of this issue is:
_We have 2 different API's on Android and iOS.  Make your best effort to make them as similar as possible without violating platform specific idioms._

It's a very subjective issue that that is difficult to navigate considering different people's philosophy about what Flutter is suppose to be.
