### ISSUE TITLE
REGRESSION: TextField Hint Multiline

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#33133]
Problem: TextField Hint is not multiline and there is no way to make it multiline. This is.a regression of https://github.com/flutter/flutter/issues/20941 #20941

## Steps to Reproduce
1. Create a multiline TextField with a Hint Input Decoration.
2. Verify that the multiline TextField works by setting `multiLine: null`.
3. Verify that the hint does not work. 

Load https://gist.github.com/searchy2/8ca6f4d92fb4044552928d56a6dc9962 to see example. 

## Flutter doctor
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/christopher/Development/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/christopher/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone X • BAFA7B7D-73DB-45DD-8DC1-F0D8834D01BD • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by jason-simmons** [comment]
`InputDecorator` hint text is rendered with ellipsizing enabled:
    https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L1959

If `hintMaxLines` is null, then the text will be ellipsized at the first line that exceeds the width constraint:
    https://api.flutter.dev/flutter/painting/TextPainter/ellipsis.html

Try setting `hintMaxLines` to a non-null value that will be large enough for the text in this widget.

**Comment by searchy2** [comment]
@jason-simmons Thanks for the temporary workaround. However, your solution should not be accepted as the desired behavior for the following reasons:
1. The original solution https://github.com/flutter/flutter/commit/114335dff0e511b6555a05c99511ad07563252c9 specifies that the InputDecoration hintMaxLines inherits from the parent TextField's maxLines. This means the hint behavior should be inherited as well for consistency.
2. Setting hintMaxLines does not allow the InputDecoration to calculate its layout or ellipsize correctly.
![Untitled20190521161310](https://user-images.githubusercontent.com/19896174/58131517-7f4ca480-7be4-11e9-93d6-2161669372b3.png)

The desired behavior is as follows:
1. hintMaxLines should correctly inherit the behavior from the parent TextField's maxLines value. 
2. The placeholder hint text should ellipsize if it exceeds the placeholder text bounds.

**Comment by justinmc** [comment]
A similar complaint about this behavior was posted in https://github.com/flutter/flutter/issues/32830 (and a PR was opened https://github.com/flutter/flutter/pull/33017).  @searchy2 What are your thoughts on that and would that PR solve your problem?

I think I agree with Jason that this is working as it was written, but the behavior might not be ideal and we can probably make some improvements.  About your desired behaviors:

  1. [hintMaxLines does inherit the value of maxLines](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_field.dart#L532) if it's not specified. However, the behavior can be slightly different, like you see in your gist, because [hint is rendered using Text under the hood](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L1956) and Text just isn't exactly the same as TextField.  Mainly:
  1. I don't think it's currently possible to ellipsize a multiline Text when maxLines is null.  If you specify a number > 1 for maxLines then it will show an ellipsis on the final line, but if you specify null then it will ellipsize on the first line.

So for your gist, it's not currently possible to ellipsize the hint in that TextField with maxLines: null on the final line.  You could work around this by specifying a number for maxLines that effectively looks the same and removing the height on the parent Container.

<img width="200" src="https://user-images.githubusercontent.com/389558/58194004-3abf1880-7c79-11e9-80e5-cffb97e0c739.png" />

And lastly, I don't know how you created a TextField where the hint renders outside the top like in your screenshot but that looks like it could be a bug :confused:

**Comment by searchy2** [comment]
@justinmc thanks for taking a look and filling me in on the background of this issue. I hope we can agree that when hintMaxLines is set to null, text should not ellipsize on a single line but continue until it is clipped? If so, then #33017 is sufficient. 

I understand that text input is a major problem for Flutter right now that is being worked on. If I could provide a suggestion from my experience working with text on Android, it would be to have two text rendering logic flows controlled by whether the TextField's constraints are fixed or flexible. If the bounds are fixed, then text should be properly ellipsized at the end of the line when the text runs out of room. This would also enable text to be ellipsized in the middle. If the bounds are flexible, then the TextField should expand to wrap text. Of course, having a maxHeight and maxWidth is necessary when using flexible. 

For now, the single line PR would be enough. Until we get a smarter text layout engine 🙏

**Comment by justinmc** [comment]
The single line fix seems ok to me after investigating a bit, so I'm just waiting for the author to come back with some tests and hopefully we can get that merged.

Flutter doesn't quite have the first class distinction between flexible/fixed, but does sort of work that way under the hood.  There are several changes to TextField and Text in progress now, so hopefully those will start to clear up things like this.

**Comment by searchy2** [comment]
Thanks @justinmc for your hard work! I'll close this issue for now as a fix is in the works.

For how text should behave, I think the best test case is to support multline ellipsis middle. On Android this is not possible because of the text rendering order. If it was, it would solve so many text layouting issues. 

Look forward to the improvements!
