### ISSUE TITLE
path_provider installing fails with other plugins!

### ISSUE THREAD

**Issue by eslamwael74** [flutter/flutter#33345]
When installing the path_provider plugin and I'm used some other plugins!!
 ```
  path_provider: ^1.1.0
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  cached_network_image: ^0.8.0
  http: ^0.12.0+2
  web_socket_channel: ^1.0.13
  sqflite: ^1.1.5
```

I'm getting errors-------->

Running "flutter packages get" in flutter_packages...           

Because cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on **path_provider** ^0.5.0+1, cached_network_image >=0.7.0 requires **path_provider** ^0.5.0+1.
So, because flutter_packages depends on both cached_network_image ^0.8.0 and **path_provider** ^1.1.0, version solving failed.
pub get failed (1)

I'm very tired to solve this issue...

**Comment by kangwang1988** [comment]
It's a common but annoying issue resulted from version conflicting.
The error message says that because of the transitive version requirement by  cached_network_image, it expects a path_provider ^0.5.0+1. However, you specified `path_provider: ^1.1.0`, so the version resolving issue fails.
In order to resolve this issue, you can remove the version limit to path_provider, like 'path_provider: any'. If you must use `path_provider: ^1.1.0`, you should consider change the version limit of `cached_network_image` until the version solving succeed.

@eslamwael74
