### ISSUE TITLE
'late' word

### ISSUE THREAD

**Issue by Davarg** [flutter/flutter#33373]
Hello, Flutter team, I don't know if you already see this bug, but it is very important to fix this issue. 

> Dart 2.3.0
> Flutter 1.5.4-hotfix.2
> I can't use 'late' word as variable name or method name.
> For example

```dart
class A {
    int get late => 0;
}
```

I've already created ticket https://github.com/dart-lang/sdk/issues/37067 but as I understand now this bug is only on your side

**Comment by timsneath** [comment]
Also adding https://github.com/dart-lang/sdk/issues/36691 for reference purposes. 

This is fixed in the latest builds of Flutter, which contain an updated version of Dart. 

@Davarg, you can either [switch to the `dev` Flutter channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) until this fix makes its way to the `stable` channel, or use a different name for your field in the meantime. 

Hope this helps! Tim
