### ISSUE TITLE
Make it more Beautiful

### ISSUE THREAD

**Issue by luneice** [flutter/flutter#33385]
## Use case
Material design is a standard cross plantform of google, but in some ways it is too ugly, so i have to choose the native solution. 

## Proposal
It is great that hiring a excellent ui designer like ios ui designer.

**Comment by stuartmorgan** [comment]
It's impossible for a design language to satisfy everyone's preferences. If you don't like Material Design, you can build and use your own widget set with a different design language; this is one of the features of Flutter's layered approach.

Closing since there is no specific, actionable feedback here.
