### ISSUE TITLE
Allow formatting of DataTable

### ISSUE THREAD

**Issue by AlbinCederblad** [flutter/flutter#33434]
## Use case

I want to be able to adjust the padding or row height of each row in my DataTable, like illustrated in this image:

![datatable](https://user-images.githubusercontent.com/10009313/58493085-80487d80-8172-11e9-9b77-db4e59b3d64c.png)

I looked for solutions at stackoverflow in [this thread](https://stackoverflow.com/questions/56344271/flutter-reduce-padding-between-datarows-in-datatable)

I solved the problem by (like others suggested) copying the content of data_table.dart into a new file, and changed the variable there, and then using that instead, but it's an ugly solution imo.

## Proposal

make formatting DataTable variables accessible?

Thanks.

**Comment by HansMuller** [comment]
This is a reasonable request. Glad to hear that you were able make progress by hacking a copy; agree that it would be better if this kind of styling was possible without resorting to that.

**Comment by shihaohong** [comment]
I just submitted a PR for custom height. I did some preliminary investigation into padding and the way that it's done on DataTable is nuanced based on whether it's the first/last column and whether it has a checkbox column, and I feel passing in a parameter for padding can cause a great deal of confusion. 

If you have an idea for how to approach this, let me know. Otherwise, I think we should not worry about padding.
