### ISSUE TITLE
StreamBuilder's snapshot doesn't have data despite sending it through Stream.

### ISSUE THREAD

**Issue by sa-sully** [flutter/flutter#33515]
Hello,

I'm currently facing a strange problem: one of my widget must rebuild its header based on a selected item. I have wrap the Text widget of my widget with a StreamBuilder, and feed it with my BLoC stream:

```dart
...
StreamBuilder<String>(
   stream: _bloc.onNameChange,
   builder: (context, snapshot) {
      String value = "Default POI name";
      if (snapshot.data != null) 
         value = snapshot.data;
      return Text(
         value,
         style: TextStyle(fontSize: 22, color: Colors.black54),
      );
   })
...
```
Here is my BLoC class:

``` dart
class POIPanelBloc extends BlocBase {
  StreamController<String> _name = StreamController.broadcast();
  Stream<String> get onNameChange => _name.stream;

  @override
  void dispose() {
    _name.close();
  }

  void openPanel(String name) {
    _name.sink.add(name);
  }
}
```
The StreamBuilder is raised 2 times when I call the `openPanel()` function, but no data is available in the snapshot nor error:
<img width="516" alt="Capture d’écran 2019-05-29 à 14 52 55" src="https://user-images.githubusercontent.com/51162371/58559472-7f235900-8223-11e9-9dfa-34685f436eb9.png">

Yet, when I listen the Stream, the data is send correctly, and only one time:
<img width="294" alt="Capture d’écran 2019-05-29 à 15 09 01" src="https://user-images.githubusercontent.com/51162371/58559619-d0cbe380-8223-11e9-962f-21b3cac9fe15.png">

I have already run `flutter upgrade` and `flutter clean` a couple of times:
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```
Any idea?

**Comment by ketanm** [comment]
A couple of thoughts:
- Can you add `snapshot.hasError` in StreamBuilder and see if there is any error. Null or non-null may not be checking it. On the first invocation, it will be null if there is no default value assigned.
- Can you use `initalData` property on `StreamBuilder` and assign your default value to ensure it gets correct default?
- Based on the code it appears that BLoC is not destroyed earlier but you can confirm that it is not disposed early.

**Comment by sa-sully** [comment]
Thanks for your answer ketanm:
- I have added an if statement with `snapshot.hasError` in the StreamBuilder, but it's never true.
- When providing the `initialData` property, the snapshot data is always equal to that value, not the value I sink in.
- I double checked with breakpoints, and indeed my BLoC is not destroyed/disposed to early.

I have yet to find a solution, seems like there is a loss of data when using a StreamBuilder (in my case) since I do not have this strange behaviour when manualy listening to the stream.

**Comment by ketanm** [comment]
Hi sa-sully,

Saw updates now. Based on what I know it appears that conceptually you are using Stream correctly. However, I noticed that you are using the package `bloc_pattern`. Either try to remove it and use stream directly to confirm it is working fine. You do use `BlocBase` but then don't use BlockProvider to get access to BLoC ( `stream: _bloc.onNameChange`). Please check package documentation and let me know if you can solve your problem.
Ketan

**Comment by iapicca** [comment]
Hi @sa-sully 
are you still experiencing this issue with the latest version of Flutter?
If so Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by ashutoshsingh05** [comment]
Ran into a similar problem today, but the only difference was
>Yet, when I listen the Stream, the data is send correctly, and only one time:

Instead of getting a single value, I see two statements on the console log, one with the correct value which was added to the stream which was immediately followed by the initialValue which was passed to the stream builder.

In my case, I was using [generic_bloc_provider](https://pub.dev/packages/generic_bloc_provider)

---
Elaboration

I have a bloc [udhariBloc.dart](https://github.com/ashutoshsingh05/Udhari/blob/v3.0/lib/bloc/udhariBloc.dart)(line 99) which listens to a collection reference and adds the value to some sinks. These sinks are then later consumed in a streamBuilders inside [Dashboard.dart](https://github.com/ashutoshsingh05/Udhari/blob/v3.0/lib/Screens/HomePageScreens/Dashboard.dart)(line 145). The problem is that even after adding data to respective sinks(in this case, `_totalDebitSink`), the values are not updated in the stream builder inside `Dashboard` class. For investigating further, I attached a listener to the `_totalDebitStream` inside the UdhariBloc's constructor and every time there was a change in the value, I saw this log in the console.
```
CURRENT DEBIT: 100
CURRENT DEBIT: 0
============INSIDE DEBIT STREAM BLDR============
Conn State: ConnectionState.active
Has Data: true
Data: 0.0
Has Error: false
Error: null
```
Here, `CURRENT DEBIT: 100` was the updated value from Firestore and `CURRENT DEBIT: 0` was the initialValue which was provided to the streamBuilder.

I used a similar technique in [dashboardBloc.dart](https://github.com/ashutoshsingh05/Udhari/blob/v3.0/lib/bloc/dashboardBloc.dart)(line 88) and [Dashboard.dart](https://github.com/ashutoshsingh05/Udhari/blob/v3.0/lib/Screens/HomePageScreens/Dashboard.dart)(line 212) and it works like a charm.

I haven't been able to find any solutions so far.
