### ISSUE TITLE
Transform mouse events to the local coordinate system

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#33675]
Events dispatched via Listener's onPointerExit, onPointerEnter, onPointerHover are currently not transformed to the local coordinate system of the Listener. (For all other callbacks we implemented the transform in https://github.com/flutter/flutter/pull/32192). We should do something similar for those exit/enter/hover mouse events.

**Comment by dkwingsmt** [comment]
Note: Fix https://github.com/flutter/flutter/pull/44631#discussion_r348101919 after fixing this issue.

**Comment by goderbauer** [comment]
@dkwingsmt @gspencergoog Is this on your radar?

@kenzieschmoll I am curious, what's your use case that requires local mouse events?

**Comment by gspencergoog** [comment]
Yes, I even have a fix that I'm test driving.

**Comment by gspencergoog** [comment]
An example use case would be wanting to draw a graph and highlight points as the mouse moves over them.  Since it's not possible to know the local transform in a build function, it's necessary to have the local coordinates in the hover details message.

**Comment by kenzieschmoll** [comment]
My use case is similar to the one @gspencergoog described. I am using MouseRegion's onHover field to track the position of the mouse and display a tooltip over the graph element at the local position. Wrapping each graph element in a Tooltip is too expensive, so calculating which element is at the local position allows us to use only one Tooltip widget instead of one for each item in the flame chart. Right now I am getting around this by adding a hard-coded offset to the absolute position (I know what the offset is in my use case), but this is not ideal.
<img width="1389" alt="Screen Shot 2019-12-20 at 9 31 25 AM" src="https://user-images.githubusercontent.com/43759233/71278109-84eda280-230b-11ea-8247-758012139f32.png">

**Comment by kenthinson** [comment]
Another example use case click and drag selection boxes. I'm also using a manual offset for now like @kenzieschmoll is. Looking forward to this fix. Thanks flutter team :)

![cover](https://user-images.githubusercontent.com/2245494/71499038-70863a00-2824-11ea-8d60-028b70a664d2.jpg)

**Comment by dkwingsmt** [comment]
Moving it to near-term goals and unassigning myself because it depends on a large change in progress that refactors how mouse annotation is detected.

**Comment by MeloJR** [comment]
I tried it in web with a configuration like this:
InteractiveViewer -> MouseRegion -> Container
and `event.localPosition` returns the same as `event.position`. If I change MouseRegion to GestureDetector and listen to `onTap` event the localPosition has the desired value. Is there a way to fix this?
