### ISSUE TITLE
using variable font in flutter

### ISSUE THREAD

**Issue by DJafari** [flutter/flutter#33709]
Internal: b/215481602

is possible using [variable fonts](https://developers.google.com/web/fundamentals/design-and-ux/typography/variable-fonts/) in flutter ?

**Comment by misaelriojasftf** [comment]
I need **variable fonts**!

**Comment by orestesgaolin** [comment]
Did anyone succeed with using variable fonts in Flutter?

**Comment by surajmandalcell** [comment]
+1

**Comment by bluemix** [comment]
I hope there are updates to this.
+1

**Comment by srix55** [comment]
Need this. Especially when lots of fonts are bloating up my app size.

**Comment by rebel-codeaz** [comment]
Needed. I can add it in pubspec.yaml but dunno what to do next! 
+1

**Comment by shyndman** [comment]
I'd love to see this too.

One option for those who want to use a few variations of a variable font — you can create static "instantiations" at specific weights using [fonttools](https://pypi.org/project/fonttools/), then use those. 

```sh
fonttools varLib.mutator ./NotoSansArabic-VF.ttf wght=140 wdth=85
```

**Comment by Hixie** [comment]
In principle this works today using the FontFeature feature, but `wght` doesn't seem to work.

**Comment by shyndman** [comment]
Ohhh, interesting. Do other axes?

**Comment by Hixie** [comment]
I haven't tried anything but `wght` as far as the newfangled "variable fonts" axes go. In general lots of OpenType font features work, for example, I'm looking at code here that works with `aalt` and `cwsh` with values 1, 2, and 3 (using Raleway for `aalt` and BioRhyme Expanded for `cwsh`.)

If you have any test cases it would be great to attach them here, especially if there are open source fonts that you _know_ support a particular axis (i.e. you've tested that specific .ttf file with other tools and they work), but when you try it with FontFeature in Flutter it doesn't work.

For `wght` in particular, let's track that using https://github.com/flutter/flutter/issues/67688.

**Comment by esDotDev** [comment]
> FontFeature

Is there any examples of how to do this? We have a variable font Fraunces and would like to use it in Flutter. 
https://fonts.google.com/specimen/Fraunces

In addition to the bundled weights and sizes, it has (new to me) properties like Softness and Wonkiness.  Would these be supported currently?

**Comment by shyndman** [comment]
As far as I can tell, this doesn't work yet. 

I grabbed the Fraunces you linked, checked the allowed ranges for the variation axes (opsz, wght, SOFT, and WONK), and built a little Flutter app that displays two `Text`s side-by-side — one using the variable font, one using an instanced variable font.

Here's the instancing command:
```sh
fonttools varLib.instancer -o Fraunces-var-instanced.ttf Fraunces-VariableFont_SOFT,WONK,opsz,wght.ttf opsz=140 wght=500 SOFT=0 WONK=1
```

And the app:
```dart
class VariableFontTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: [
          Text(
            pangram,
            style: TextStyle(
              fontFamily: 'Fraunces',
              fontFeatures: [
                FontFeature('opsz', 140),
                FontFeature('wght', 500),
                FontFeature('SOFT', 0),
                FontFeature('WONK', 1),
              ],
            ),
          ),
          Text(
            pangram,
            style: TextStyle(
              fontFamily: 'Fraunces-var-instanced',
            ),
          ),
        ],
      ),
    );
  }
}
```

And the result:
<img width="910" alt="Screen Shot 2021-01-13 at 5 41 55 PM" src="https://user-images.githubusercontent.com/42326/104518979-a8deee80-55c6-11eb-8ba3-07f627c22761.png">

`wght` is the most obvious, but if you look carefully the other axes are not being picked up either.

To see what I mean, you can see the intended effects of each axis at https://github.com/undercasetype/Fraunces. Wonkiness is the easiest to pick up outside of weight, because it's essentially a set of stylistic alternatives.

**Comment by Hixie** [comment]
There's a sample here: https://master-api.flutter.dev/flutter/dart-ui/FontFeature-class.html

**Comment by Hixie** [comment]
(The hope is that we will work on this in the next few months; it's not super-high priority relative to e.g. getting the null safety migration working well, or getting desktop and web support to be more solid, but it is something we do care about and want to get working when we find the time. If anyone is interested in seeing if they can figure it out, don't hesitate to try. It's probably just a minor tweak to how we're passing the FontFeature data to HarfBuzz. If you want to try to contribute, you can see instructions on how to get started, build the engine, and hang out on our Discord in the CONTRIBUTOR.md doc in this repo.)

**Comment by shyndman** [comment]
> It's probably just a minor tweak to how we're passing the FontFeature data to HarfBuzz

This may need a bit of tweaking on the Dart side as well. It appears that axis values are floats, and `FontFeatures` only supports integer values currently.

**Comment by esDotDev** [comment]
Great, thx for all the info guys

**Comment by shyndman** [comment]
Last bit of info I found — Harfbuzz represents the axis value as a float:
[hb_variation_t](https://harfbuzz.github.io/harfbuzz-hb-common.html#hb-variation-t)
[hb_font_set_variations](https://harfbuzz.github.io/harfbuzz-hb-font.html#hb-font-set-variations)

**Comment by Hixie** [comment]
Ah, interesting. We will need some tweaks to the Dart API as well then, indeed.

**Comment by marchellodev** [comment]
+1

**Comment by DJafari** [comment]
@Hixie any update about this feature ?

**Comment by Fabhi** [comment]
Much needed

**Comment by bryanoltman** [comment]
Marking this issue as P2 to match the internal bug b/215481602

**Comment by Hixie** [comment]
@bryanoltman P2 means this is about to block a customer, is that accurate?

**Comment by bryanoltman** [comment]
@Hixie After looking into it a bit, I think the internal bug was misclassified. Updating this to a P3.

**Comment by AbdulSamadMalik** [comment]
+1

**Comment by guopeng1994** [comment]
Any updates?

**Comment by guidezpl** [comment]
small nit but this is indeed blocking, bumping to P2

**Comment by davelab6** [comment]
For context, fonts.google.com has updated 100s of font families to be variable fonts, including the # 2 most popular family [Open Sans](https://fonts.google.com/specimen/Open+Sans) - and the previous "Open Sans Condensed" family is no longer listed (although the CSS API serves it so existing users aren't effected) because those styles are now available in the `Width (wdth)` axis. 

(I also kindly note that in comments above and eg https://github.com/flutter/flutter/issues/67688#issuecomment-742966776 there's a conflation between OpenType **features** (`aalt`, `cwsh`, `ss01`, etc) and OpenType **variations** (`wght`, `wdth`, `WONK`, `GRAD`, etc); features are binary toggles, introduced in the late 90s, and variations are continuous ranges introduced in 2019 - and reaching mass adoption in 2022. The underlying libraries (freetype, harfbuzz) that processes them, that Dart/Flutter depend on, treat them rather separately.

The `FontFeature()` method would perhaps be only appropriate for features, while a new `FontVariation()` method may be more appropriate. This would mirror the CSS properties `font-feature-settings` and `font-variation-settings`

Although, I also note that those properties are poorly designed for actually cascading (see eg https://web.dev/variable-fonts/#font-variation-settings-inheritance). 

An equivalent/superior to the CSS property `font-optical-sizing: auto` is also strongly desirable for Flutter; I say superior because again that CSS property was poorly designed and a improvement proposal is at https://github.com/w3c/csswg-drafts/issues/4430

Finally, CSS underspecifies how "outline stroking" and semi-opaque overlapping glyphs should work, and variable fonts exacerbate this - since they make overlapping contours, intra-glyph, very common; inter-glyph overlaps are also common and not consistently handled. While glyph overlaps were always allowed in the TrueType specification (since late 80s...) the PostScript font specs disallowed them, and many TTFs were made as derived from PS fonts, such that much software does not correctly handle them. https://jsbin.com/xewuzew demos some issues in current browsers with this. 

So, to implement full support for variable fonts, I recommend Flutter have those 4 things:

* a way to set variable font axes values with inheritance 
* by default, when the `opsz` axis exists in a font, set the value to the font size, and allow a ratio override, plus override via the above axis value sette. (Ideally the auto value is resolved to physical Points, 1/72nd of an inch, although I am recommending that ideal as a partisan and recognize there are other positions on what value to use; but the key idea is that it is set based on font size)
* correctly render semi-opaque text
* correctly render outline-stroked text

**Comment by davelab6** [comment]
Oh there's 2 more things, which might not be relevant to flutter, but maybe are more relevant to flutter than a typical design app... 

* Flutter developers and end users of flutter apps will need a easy way to know what's actually available in each VF family; that's because they will often be constructing UIs for end users to set axes values, as much as they will set axes values within the apps own code itself. 

eg How to obtain a dict of axes in each variable font family (which can be more than 1 TTF file, despite a lot of oversimplification in docs that "a VF is lots of font files turned into 1 file", especially 2, one roman and one Italic) and their tags, labels, min/default/max values, and flags, which are all in the font files fvar tables.

A nuance here is that axes have a bit mask of flags, and the only one defined so far is "HIDDEN", which isn't meant to mean "inaccessible to users" but rather "shown on request", like from some progressive disclosure or preference UI. 

At a high level, there's 3 benefits to VFs: to compress, to express, and to finesse. Compress is as [stated nicely](https://github.com/flutter/flutter/issues/33709#issuecomment-719890208) by @srix55 above, to use a bunch of weight styles in a smaller file-size disk representation by run time instantiation of those weights. Express is where the maker user slides the slider or dials the dial or whatever to find just the right value of the axis that expresses their intent, which could be just a very specific weight like 427, or some FUNK or WONK axis to whatever value they feel like, and typically it's clearly visible to anyone what the charge was. Finesse is like opsz or GRAD where the value is set indirectly, based on the context of the text (like font size or dark mode) and are often very subtle adjustments. 

So, with this understanding, it may be that some axes are intended for indirect use, or direct but infrequent use, and are best left out of the axes controls shown to every user, always, but rather only shown to users who somehow indicated they do want to see every axis in the font. 

It would be nice if flutter made that information also easily available to developers so they can do the right things when exposing axes to their end users.

I guess there may already be such a getter method for font features, and as above a separate and similar method for variations would be great. If there isn't already that for features, that's also necessary, since axes can trigger features and control of both is necessary in that case. The Frances and Recursive fonts demo this. 

* There is at least 3 "axis registry" data sets, one from ISO MPEG Open Font Format, which is fed mainly by the next one, the Microsoft OpenType Specification which actually has a website version of the spec and is almost always in sync with the first; and the Google Fonts one at GitHub.com/GoogleFonts/axisregistry , which is a superset of, although not directly derivative from, the others.

These provide additional contextual information about axes, like longer descriptions that explain an axis, typical interesting instance locations, etc. 

This is similar to the above, being about providing convenience methods for app developers to expose the full depth of facilities offered by VFs.

**Comment by davelab6** [comment]
Great to see https://github.com/flutter/flutter/pull/100978 merged as the next but not final step towards making it possible to use variable fonts in flutter :)

**Comment by chinmaygarde** [comment]
@Hixie The engine PR has landed. I don't think there are other engine work items in flight on this effort at the moment.

**Comment by goderbauer** [comment]
@jason-simmons is still working on the CanvasKit implementation for this.

**Comment by chinmaygarde** [comment]
Per the internal issue, the P2-ness of this issue was related to its implementation on the mobile platforms which has been completed. Dropping the priority as Jason was pulled away to work on higher priority tasks ATM.

**Comment by guidezpl** [comment]
Thanks @jason-simmons! Can you confirm this issue can be closed now that https://skia-review.googlesource.com/c/skia/+/563536 has been rolled in with https://github.com/flutter/flutter/pull/108821?

**Comment by jason-simmons** [comment]
No - there will need to be a roll of CanvasKit into the engine that includes the Skia change, followed by a PR in the engine that integrates the web UI libraries with the CanvasKit API.

I've built the engine PR - it's just waiting on the CanvasKit roll.

**Comment by guidezpl** [comment]
Ah gotcha, makes sense.

> it's just waiting on the CanvasKit roll.
I'm not sure if I understand all the rolls happening but isn't https://github.com/flutter/engine/pull/35088 it?

**Comment by jason-simmons** [comment]
The CanvasKit roll into Flutter Web is separate from the Skia->engine roll.

See https://github.com/flutter/engine/blob/main/lib/web_ui/README.md#rolling-canvaskit

**Comment by jtmcdole** [comment]
customer:fun would also like this.

**Comment by zanderso** [comment]
@jason-simmons Is this done? Can we close it?

**Comment by jason-simmons** [comment]
This has landed on all platforms.
