### ISSUE TITLE
Evaluation of this constant expression throws an exception 

### ISSUE THREAD

**Issue by Ritesh11** [flutter/flutter#33752]
At step 4 in example https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3 on line child: Text(wordPair.asPascalCase), I am facing the error at compile time that is Evaluation of this constant expression throws an exception

**Comment by khaile** [comment]
@Ritesh11 
Did you remove the `const` keyword before the Center?
Replace 
```dart
body: const Center(
  child: Text(wordPair.asPascalCase),
)
```
with
```dart
body: Center(
  child: Text(wordPair.asPascalCase),
)
```

**Comment by kaynz** [comment]
@Ritesh11 If your problem is solved please close this issue.

**Comment by tajchert** [comment]
I had same issue.
As description above states "Make following changes:" and this one (removing `const` keyword) is not marked I spend 5 minutes chasing why it has a problem with it.

**Comment by smac89** [comment]
The problem arises if you pass in parameters which are not compile-time constants to the constructor. See [`const`](https://dart.dev/guides/language/language-tour#final-and-const):

For example, this will work:

```dart
body: Center(
  child: const Text('Hello World'),
)
```

because the string inside `Text` is constant and won't change at runtime.

This will not work:

```dart
body: Center(
  child: const Text(wordPair.asPascalCase),
)
```

because we won't know the content of the `Text` widget until runtime.

**Comment by gitsofian** [comment]
thanks!
