### ISSUE TITLE
Flutter versioning mismatch/old when pub get

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#33793]
Update: This is likely caused by the versioning calculation taking the earliest branch point as the version.

When working on old branches of Flutter, the version can remain old and become out of sync with master.

Error:
```Running "flutter pub get" in platform_channel...                    4.5s
The current Flutter SDK version is 1.4.2-pre.103.                       
                                                                        
Because flutter_gallery depends on device_info 0.4.0+2 which requires Flutter SDK version >=1.5.0 <2.0.0, version solving failed.
Running "flutter pub get" in flutter_gallery...                         
pub get failed (1)
```
This is after syncing tags, deleting flutter/version and running pub get and update-packages.
cc @jonahwilliams

**Comment by shihaohong** [comment]
Running `git fetch upstream master --tags` resolved this for me.

I ran into a similar issue trying to run `flutter_gallery` when my Flutter SDK version was showing as Flutter 1.2.1-pre.1477 on tip-of-tree `master`. It seems like the tags for each branch do not get updated when running `git fetch upstream`. 

The current Flutter SDK version is 1.2.1-pre.1477.                      
                                                                        
Because flutter_gallery depends on video_player >=0.10.1+3 which requires Flutter SDK version >=1.5.0 <2.0.0, version solving failed.
Running "flutter pub get" in flutter_gallery...                         
pub get failed (1)
```

**Comment by zanderso** [comment]
@GaryQian Could you give some detailed repro steps along with expected/actual behavior? Thanks!

**Comment by jmagman** [comment]
ping @GaryQian
