### ISSUE TITLE
pub.dev should expose if a Plugin supports AndroidX

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#33817]
## Use case
I got an issue related to a plugin updated while it uses AndroidX

## Proposal
Option 1-I want a warning on breaking changes on the console when a plugin got an update.
Option 2-When someone makes a new app or plugin it should use AndroidX by default.
Option 3-When a plugin uses AndroidX there should be an indication on pub.dev website.
Option 4-Show specification section on pub.dev website like min SDK, iOS version, AndroidX support, etc.

**Comment by iapicca** [comment]
I also have often problems of compatibility with AndroidX on my Flutter apps;
I agree with "amorenew", all 4 options make sense and are not mutually exclusive.

The option 2 is logical and I'm a bit surprised that isn't the standard yet;
3 and 4 would add a lot of transparency and this in my opinion isn't enough
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

My own proposal (that doesn't exclude anything from what already suggested:
 for dependencies mark a default version that gonna be used when gradle.build fail due to androidX

**Comment by ElectronSz** [comment]
Same here, the provided soulution never worked for me.

The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

I've created so many AndroidX flutter projects, every of them failed with the same error. I follow the instruction exactly if fails. This is bad please convert the flutter plugins to AndroidX. Because sseemingly they are looking for something like android.support instead of androidx.support whatever it is.

**Comment by mikhail-tokarev** [comment]
Hi @amorenew 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by amreniouinnovent** [comment]
@mikhail-tokarev I didn't get it recently 
But I think pub.dev should show more info about the plugin

> Option 3-When a plugin uses AndroidX there should be an indication on pub.dev website.
> Option 4-Show specification section on pub.dev website like min SDK, iOS version, AndroidX support, etc.

**Comment by iapicca** [comment]
thank you for your feedback @amorenew

**Comment by timsneath** [comment]
It's a great feature idea, but I'm going to close this because we are moving the entire ecosystem to AndroidX. In the next version of Flutter, it won't be possible to use `flutter create` to create an app that uses the obsolete Android support library any longer. It's fairly complex to differentiate plug-ins that don't support AndroidX (but should) from plug-ins that don't need to support AndroidX, and so we'd prefer to invest that time in other areas that can make Flutter developers more efficient. 

Thanks again for your support of Flutter!

**Comment by amorenew** [comment]
@timsneath For Option 4
I made a barcode plugin but it shows iOS and Web support
How could I show Android only? Is it by deleting the iOS and Web folder from the project?
https://pub.dev/packages/barcode_plugin/
![image](https://user-images.githubusercontent.com/2842459/80895504-bed9a700-8cf6-11ea-969d-6f583c3afead.png)

**Comment by timsneath** [comment]
Hi there, thanks for your contribution. This isn't a great place for questions -- it's for issues with the Flutter framework. 

Nevertheless, you'll find the answer in our new blog post here: https://medium.com/flutter/modern-flutter-plugin-development-4c3ee015cf5a

Check the section "New pubspec format", which lets you explicitly call out the supported platforms for a package.
