### ISSUE TITLE
Gallery, Components, Tabs and Scrolling is < 30fps in CPU

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3392]
Testing on a Nexus 5. Go into Gallery, Components, Tabs and Scrolling. Swipe left and right. See the GPU graph looks good, but the CPU graph has spikes when swiping.

![screenshot_20160418-145849](https://cloud.githubusercontent.com/assets/5479/14621253/55edbd46-0576-11e6-8709-fdeacc65f614.png)

Here's the non-slow mode:

![screenshot_20160418-160459](https://cloud.githubusercontent.com/assets/5479/14622541/70e311f6-057f-11e6-8b07-089fee18e78e.png)

**Comment by HansMuller** [comment]
Here's a screenshot of the same demo on a Nexus 5x. We're getting 60 fps.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/14622809/8bef2668-0581-11e6-865a-f2849ae998fd.png)

**Comment by HansMuller** [comment]
It's possible that the spike (spikelet) that can be seen at the beginning/end of each tab change is due to rebuilding the Scaffold to deal with the scrollableKey change. Which may not be needed, since only one vertical scrollable tends to be visible when the user gets around to scrolling - unless they manage to scroll both scrollables while the tab selection animation is running. Which would be difficult without slowing the animations way down. And even then, it's not clear that it would be wrong to have the appbar respond to each scroll.

**Comment by sethladd** [comment]
We're looking good on a Nexus 5 w/ non-slow mode.
