### ISSUE TITLE
Remove test timeouts by default

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#33931]

**Comment by dnfield** [comment]
Cirrus has a hard limit of 1 hour for tests to complete - we can bump that as high as 90 minutes, but have resisted doing so (because we should really shard rather than doing that).  I'm not sure what the exact timeout is for LUCI, but it's longer - I've seen tests run for at least a couple hours before finally being killed by the agent when things go bad.  On the devicelab it's 15 minutes - I don't know if you're proposing removing that as well though.

I'm concerned that this change will have a few undesired consequences on CI infra:

1. Tests that are broken or flaky will still fail to complete, but they'll just exhaust the entirety of the remaining duration on CI.
2. CI machines will be less available for running new commits.  This is particularly troubling on LUCI and the devicelab, where we're constrained to a few machines available for all testing.  
3. These problems (1 and 2) will compound as we shard things out.  Tests should get shorter over all, but badly behaving tests (or environments) could end up getting booked for hours without the tester killing them.

**Comment by dnfield** [comment]
It's entirely possible that these concerns are based on a misunderstanding of the role of `initialTimeout`.

**Comment by Hixie** [comment]
That's fair. Maybe we should set the `package:test` timeout to 30 minutes or some such?

**Comment by dnfield** [comment]
That's better, but it would still mean that one misbehaving test could tie up a machine for 30 minutes instead of the current limit of something like 5.

**Comment by Hixie** [comment]
The current limit is 2 minutes.

How do we know if 2 minutes (or 30 minutes) is enough to avoid flakes?

**Comment by Hixie** [comment]
I guess my problem is I have no idea how to pick the timeout to avoid the race condition.
