### ISSUE TITLE
flutter_markdown 0.2.0 - Flutter v1.7.2-pre.30

### ISSUE THREAD

**Issue by calvinmuller** [flutter/flutter#33965]
## Steps to Reproduce
pubspec.yaml
  flutter_markdown: ^0.2.0

## Logs

```
Compiler message:
file:///Users/calvinmuller/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///Users/calvinmuller/iStreet/Mobile/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.
        List<TextSpan> children = previous.text.children != null

```

```
[✓] Flutter (Channel master, v1.7.2-pre.30, on Mac OS X 10.14.4 18E226, locale en-ZA)
    • Flutter version 1.7.2-pre.30 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision 14414f350a (8 hours ago), 2019-06-05 18:14:17 -0700
    • Engine revision 3371da1e09
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 9dcb026b26)


```

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/commit/14414f350ac040f9626f1aa0b3071f42cc9136a6 changed `RichText` to return an `InlineSpan` instead of a `TextSpan`.

`flutter_markdown` will need to be updated for the new API:
    https://github.com/flutter/flutter_markdown/blob/master/lib/src/builder.dart#L343

@GaryQian `flutter_markdown` is trying to merge the content of multiple `RichText` widgets into a single `RichText`.
Would it be useful to move the `children` property from `TextSpan` up to `InlineSpan` and have the other `InlineSpan` subclasses return an empty list?  Or should `RichText` users check the type of `RichText.text` and handle each subclass differently?

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter_markdown/pull/102 fixes this. There was a breaking change.

**Comment by calvinmuller** [comment]
This is solved! thanks!

**Comment by GaryQian** [comment]
We added additional compatibility API to minimize the breaking nature of the Text Inline widgets change. The API adds deprecated properties to `InlineSpan` in order to make it backwards compatible with the old version of `TextSpan`.
