### ISSUE TITLE
Bug: the text filed I cann't delete what I just Input.

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#3399]
Bug: the text filed I cannot delete what I just Input.
and the password filed if I click the delete button, it dose not delete a character.On the contrary, it add a new character!
My phone OS is based on android 5.1.

**Comment by sethladd** [comment]
cc @mpcomplete 

Thanks for the feedback! We're still working on text input editing. You can follow along here: https://github.com/flutter/flutter/issues/1567

Because this is a known issue, I'm going to close this in favor of https://github.com/flutter/flutter/issues/1567. However, please do keep the feedback coming!
