### ISSUE TITLE
skCanvas::flush use a lot of time,what can i do next

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#34035]
![Screenshot from 2019-06-07 15-12-09](https://user-images.githubusercontent.com/3118573/59088029-eaaeaa00-8938-11e9-8cfc-a5290372eb2c.png)

in the picture the ui thread last 37.5ms while the skCanvas::flush used about 31ms. 
what can i do next why does it doing.
I am use a custom Paint to draw on small line

**Comment by wanjm** [comment]
![Screenshot from 2019-06-07 16-26-34](https://user-images.githubusercontent.com/3118573/59091051-0ae26700-8941-11e9-87ae-dd48d69a1338.png)
add more info from trace-skia
this frame last 37.981ms, in which GrGLProgramBuilder::finalize used 23ms;

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!

**Comment by fzyzcjy** [comment]
Hi do you find the solution? I am having a similar problem!

**Comment by ilkercankaya** [comment]
Any solutions?
