### ISSUE TITLE
Firebase messaging get token returns null (firebase_messaging 5.0.2)

### ISSUE THREAD

**Issue by GervaisYO** [flutter/flutter#34253]
After updating our flutter application from Android to Android X we are having some issues with firebase messaging (firebase_messaging 5.0.2). When calling get token in our flutter application we are getting null on all Android version below or equal to 4.4.

We are currently using flutter version 1.5.4-hotfix.2.

Could someone please help with this issue?

Best regards

**Comment by mikhail-tokarev** [comment]
Hi @GervaisYO 
re you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by iapicca** [comment]
Hi @GervaisYO 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
