### ISSUE TITLE
callBack for Scaffold.drawer and Scaffold.endDrawer

### ISSUE THREAD

**Issue by PabloduPontavice** [flutter/flutter#34334]
## Use case

As far as I know, the best way to manually control the Scaffold's drawer and endDrawer is to give the scaffold a key, get either ```_scaffoldKey.currentState.isDrawerOpen``` or ```_scaffoldKey.currentState.isEndDrawerOpen``` and then depending on those booleans call ```_scaffoldKey.currentState.openDrawer()```, ```_scaffoldKey.currentState.openEndDrawer()``` or ```Navigation.of(context).pop()```.

The main issue with this is that when the drawers are dragged in or out those booleans don't get updated which makes it tricky to have an app where you have both manual management of the drawers and allow the drawers to be opened by dragging. 

The last thing I did try was to directly implement a DrawerController() but this isn't practical since it seems that any widget that is set to Scaffold.drawer or Scaffold.endDrawer automatically seems to get wrapped in a DrawerController which causes issues (see: [https://github.com/flutter/flutter/issues/21272#issuecomment-479868411](url)).

## Proposal

Maybe have a Scaffold.drawerCallback and a Scaffold.endDrawerCallback?

## Flutter Doctor

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.13.6 17G65, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by CountPablo** [comment]
Another use case I found was when using an appbar/bottomappbar that isn't always visible and I'd like to detect when the drawer/enddrawer opens so that I can make the appbar/bottomappbar visible again. Since there is no callback I don't see how this is possible.

I tried wrapping the body in a GestureDetector and setting the onHorizontalDragStart (I also tried onHorizontalDragEnd and onHorizontalDragUpdate) parameter to make the appbar/bottomappbar visible again but for some reason it doesn't get triggered when opening a drawer.

**Comment by CountPablo** [comment]
I really find that this severely limits what is otherwise a very well implemented feature.

**Comment by bikcrum** [comment]
This should be resolved by #67249

**Comment by pedromassangocode** [comment]
Thanks!
