### ISSUE TITLE
Design a better raw keyboard API

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3438]

**Comment by Hixie** [comment]
Proposal:

Pressing keys on a physical input device (keys on keyboards, device keys like volume controls on phones, buttons on joysticks, etc) generates a sequence of bracketed events:

* When the key is physically pressed, you get a DOWN event.
* If the key remains pressed and the system decides it should autorepeat, then you get a REPEAT event.
* Once the key has returned to its unpressed position, you get an UP event.

Each event has the following fields:
 - The hardware USB HID key code if available (might be available on Android as the scan code?). If unavailable (e.g. on iOS), null.
 - A logical key code that represents the semantic of the pressed key, see below.
 - An NFC Unicode string representing the text input that the current interaction should result in, if relevant. For example, for the "A" key this would be the string `'a'`, but for the F1 key, this would be null. This is a string, not a character, because some combinations of dead keys with character keys may generate combining characters that don't have corresponding normalized code points. For shifted keys, compose sequences, and dead key sequences, every key generates up and down events, but only one of them generates a Unicode string in its events (the last one in the sequence).

The logical key code is a 36 bit integer in a namespace that we control and define. It has values in the following ranges:

0x0 0000 0000 - 0x0 0010 FFFF: For keys that generate Unicode characters when pressed (this includes dead keys, but not e.g. function keys or shift keys), the logical key code is the Unicode character corresponding to the simplest (uppercase) representation of the key in the current keyboard mapping (as determined by the user's locale settings). The Unicode codepoint might not actually match the string that is actually generated for an unshifted key press of that key, for example we would use U+0034 for the `4 $` key in the US layout, and also the `4 ;` key in the Russian layout, and also, maybe less intuitively, for the `' 4 {` in French layout (where the in the latter case, and unshifted press gets you a `'`, not a `4`). Similarly, the `Q` key in the US layout outputs a `q` in normal usage, but its code would be 0x0 0000 0051 (U+00051 being the code for `Q`).

0x1 0000 0000 - 0x1 FFFF FFFF: For keys that are defined by USB but do not fall into the above category, the logical key code consists of the 32 bit USB extended usage code, with the 33rd bit set. For example, the Enter key would have code 0x1 0007 0028. Only keys that fall into collections like "Keyboard", "Keypad", and "Tablet PC System Controls" are considered for this API; for example, a mixing desk with multiple collections of volume controls would not be exposed via DOWN and UP events, nor would a mouse, joystick, or golf simulator control.

0x2 0000 0000 - 0x2 FFFF FFFF: For keys that aren't defined in USB at the time of implementation and have no Unicode equivalent, but that we need to support, and for which a key code exists in Android, the logical key code might be the Android key code with the 34th bit set. For example, the "3D Mode" key exposed on Android as KEYCODE_3D_MODE might be given the code 0x2 0000 00CE.

0x3 0000 0000 - 0xF FFFF FFFF: For keys that don't fall into any of the above categories, but that we need to support, key codes in this range are minted and amply documented. For example, if Flutter were ever ported to the Symbolics LM-2, the "thumb up" key might be given the code 0x3 0000 0001. Where possible, we will use specific subranges of this space to reuse codes from other platforms.

This is intended to get us out of the business of defining key codes where possible. We still have to have mapping tables up the wazoo, but at least the actual minting of codes is deferred to other organisations to a large extent. Coming up with a code is a mechanical process consisting of just picking the lowest number code possible according to the definitions above.


Here are some examples.

For example, on a French keyboard layout, pressing CAPS LOCK then pressing SHIFT + Y would generate the following sequence:
1. DOWN, HID 0x00070039, logical 0x100070039. (CAPS LOCK DOWN)
2. UP, HID 0x00070039, logical 0x100070039. (CAPS LOCK UP)
3. DOWN, HID 0x000700E1, logical 0x1000700E1 (SHIFT DOWN)
4. DOWN, HID 0x0007001D, logical 0x000000059, string U+00059 (Y DOWN, note that the HID code is for the "Z" key, but logical code matches the character, "Y")
5. UP, HID 0x0007001D, logical 0x000000059, string U+00059
6. UP, HID 0x000700E1, logical 0x1000700E1 (SHIFT UP)

Here's another example. German keyboard layout, you press `^e` (the `^` key is at the top left of the keyboard and is a dead key):
1. DOWN, HID 0x00070035, logical 0x00000005E. No string, because it's a dead key. The HID key is for "Keyboard grave accent and tilde" in AT-101 keyboard typical position 1, the logical key is the same as the code point for the Unicode character for `^`.
2. UP, HID 0x00070035, logical 0x00000005E.
3. DOWN, HID 0x00070008, logical 0x000000045, string U+000EA (Unicode for `ê‬`). Note that the logical key is the Unicode character for `E` (capital E, not lowercase E), but the output is lowercase.
4. UP, HID 0x00070008, logical 0x000000045, string U+000EA.

**Comment by Hixie** [comment]
cc @j9brown, @abarth for comment.

**Comment by j9brown** [comment]
I like the idea of getting out of the business of definitions keycodes but there are a few problems with this particular approach.

1. App developers still have to contend with mapping logical key codes to various functions.  This may be hampered if we have OS specific overlays in the namespace.  Moreover there are often many ways of expressing roughly the same function.

2. Keyboards are hard.  I'd say that 99% of the time app developers should not be messing with raw keyboard data.  They should be operating at a higher level semantic layer in terms of text editing (ime), navigation, shortcuts, etc. that have well-defined accessibility mappings independent of specific devices.

3. The raw keyboard data stream will often be incomplete from the perspective of any particular client.  Supposing focus was elsewhere when CAPS LOCK was pressed, the client would not have observed it.

4. In general, it is not possible to go directly from key sequences to characters.  Many non-latin layouts rely on modal text editing and completion behaviors that require an IME with access to sufficient context.

Fwiw, I am thinking to use USB HID to define our raw keyboard namespace as you suggest.  However anyone using this API, except perhaps a game which wants to treat the keyboard as a mess of buttons, is basically doing it wrong.

With that in mind, I am thinking of modeling access to raw keyboard as a kind of "keyboard capture" function much like "mouse capture".  ie. As a special mode that fundamentally changes the interpretation of the keyboard.

**Comment by abarth** [comment]
@j9brown We should probably talk in person because this is a complex topic.  I agree with your points, but we get a steady stream of requests for raw keyboard events, particularly for non-text editing use cases.  For example, suppose someone wants to switch between screens of their app using the F1-F12 keys.  Our plan is to continue to use IME for actual text input.

**Comment by j9brown** [comment]
Yeah that's a relatively easy case.  I just don't want to repeat history by
encouraging misuse of raw keycodes.  I was probably a bit overzealous.

If we supposed instead that users should be able to navigate to different
parts of the app by hitting alphabetic keys, would the design be the same
as for F-keys?  Should we report the keycap symbol instead of the generated
character and use that for shortcuts?  What if the keyboard isn't Latin or
isn't currently operating in a Latin mode?  Should we remap the raw
keycodes themselves according to the layout (AZERTY vs. QWERTY)?  How do
the IME and keyboard layouts interact?

I'm not eager to tread this road again...

**Comment by abarth** [comment]
> would the design be the same as for F-keys?

I think that's a reasonable use case.  Consider a game like StarCraft where there are keyboard mnemonics for various actions (i.e., "a" for "attack").

> If we supposed instead that users should be able to navigate to different parts of the app by hitting alphabetic keys, would the design be the same as for F-keys?

Ian's proposal has three values, which address different use cases:

1. The hardware USB HID tells you which physical key was pressed, which is useful for games that care about the physical input to the device (and don't care about any sort of semantic value those keys have).

2. A logical key code, which takes into account the current locale/keymap.  This value has the most compelling use cases (e.g., screen switching, accelerators).  It's the value you'd use for alphabetic screen switching (to answer your question).  The sadness here is there's no existing naming scheme that covers this use case because the namespace of logical key codes is larger than both Unicode, USB HID, Windows VKeys, or anything else we could find.  That's why Ian is proposing inventing a new namespace to contain these values.  (We can tell you lots of sad stories about trying other approaches here.)

3. A Unicode string.  Regardless of how much we evangelize using IME for text input, some developers are going to want to derive text from key input.  Rather than having them each do it wrong in their own way, we can provide something halfway reasonable in this regard.  Ironically, this value is the easiest to derive on existing platforms.

This model matches what most platforms do, including the sadness of each platform inventing its own logical key code namespace.

> Should we report the keycap symbol instead of the generated character and use that for shortcuts?

Yes, that's (1).

> What if the keyboard isn't Latin or isn't currently operating in a Latin mode?

This approach should work fine for non-Latin keyboards.  Is there a particular scenario you're worried about?

> Should we remap the raw keycodes themselves according to the layout (AZERTY vs. QWERTY)?

Physical descriptions of the keys are (1).  Their logical representation according to the current keymap is (2).

> How do the IME and keyboard layouts interact?

They're largely independent processes.  The IME provides you information about the user's text editing, which make take place via a keyboard or via some other input modality (e.g., voice, handwriting digitation).  This approach differs from the Windows approach of trying to send IME information through key events.  It also differs from the iOS approach of trying to send key press information through the IME.

Specifically, it's impossible to correctly reproduce the information you receive from the IME using key events and it's impossible to correctly reproduce the information you receive from key events using the IME.

> I'm not eager to tread this road again

Agreed.  However, the use cases exist and need to be addressed somehow.

**Comment by Hixie** [comment]
@j9brown I hear you might be working in this space. We should talk, to make sure what you're doing addresses Flutter's needs. I'm eager to convince you to use the model above or to hear what's wrong with it. :-)

**Comment by eseidelGoogle** [comment]
Unsure if this is still an issue, and if it affects API stability?

**Comment by Hixie** [comment]
Since this bug was filed our API improved sufficiently.

**Comment by ZhangBanger** [comment]
I'm still having issues using the hardware keyboard in my emulator. Is this known / expected behavior?

**Comment by eseidelGoogle** [comment]
Probably https://github.com/flutter/flutter/issues/9347?
