### ISSUE TITLE
 How to avoid naming conflicts with flutter？

### ISSUE THREAD

**Issue by zjuwjf** [flutter/flutter#34395]
How to avoid naming conflicts with flutter SDK, especially with the evolution of flutter? 

When I upgraded to flutter v1.7.2, I tragically found that flutter added a new [lib/src/widgets/actions.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/actions.dart) file that exports a class named Action.

This leads to conflicts between the previous definitions and the use of Action, such as the use of fish-redux (Action is a common definition, especially in the Redux system).

It can be resolved by using an "as" or "hide" keyword,  but it would be a very offensive practice if the Action is so commonly used.

While Action is just a special case, there may be other naming conflicts that occur in other flutter-based libraries.

So my question is whether it should have a better solution or rule to reduce the occurrence of similar situations ?

**Comment by kangwang1988** [comment]
Currently, we can use the `import a.dart as A` and `import b.dart as B`, while refer them using A.action and B.action to resolve the conflicts. 
cc @xster  Any recommended practice towards this issue?

**Comment by xster** [comment]
cc @gspencergoog this is a good point. We can potentially undercut users on desirable namespaces in the core libraries that exports. 

Unfortunately I'm not sure what the right solution is besides what @kangwang1988 proposed.

Is widgets.Action the right name? Could it perhaps be UserInputAction or some such?

**Comment by zjuwjf** [comment]
My suggestion is to name the definition of the new non-flutter core concept, which should be decorated with the corresponding prefix.

In the case above, if you can change the Action to something like UserInputAction, that's great.

**Comment by jonahwilliams** [comment]
If we change the name `Action` to `UserInputAction`, well someone could have defined a `UserInputAction` class too. we could perhaps name it `FlutterUserInputAction`, but again nothing is stopping a user from naming a class with a `Flutter<Something>` either.

I don't really want to end up with a framework full of `FlutterUserSpecialistActionAppliedFromKeyboard` because there is a lower probability of a naming collision.

Dart does not have namespaces, for better or worse. The tools we have to solve this problem are `show`, `hide`, and ` as identifier` on import statements.

cc @Hixie for his thoughts on backwards compatibility

**Comment by zjuwjf** [comment]
I agree with @jonahwilliams, a framework full of FlutterUserSpecialistActionAppliedFromKeyboard is ugly. 

And I fully agree that flutter has the first option for the naming of definitions.

But if a definition meets the following points:
1. It is new
2. It is non-core
3. It needs to be exported

Its naming should be treated with more caution, especially some common names. This will be more friendly to other developers and will also contribute to the healthy growth of the community's ecology.

**Comment by jonahwilliams** [comment]
> It is non-core

I think keyboards are fairly core to certain desktop experiences, but probably not core to a lot of mobile of web ones?

maybe this is in indication it should be exported though a separate library like `flutter/keyboard.dart`

**Comment by zjuwjf** [comment]
> maybe this is in indication it should be exported though a separate library like `flutter/keyboard.dart`

So is there a plan to avoid naming conflicts between flutter and other libraries? Such as the "Action" naming conflicts above?  

In my opinion, the two solutions above are both feasible.

@xster @jonahwilliams

**Comment by dnfield** [comment]
FWIW, we ran into this when the Material library introduced a class called `CardTheme` and another google team had a class named `CardTheme`. The solution there was to `hide` the new definition from material, although it would have mad ejust as much sense to use named imports.

I'm not sure there's a general solution available here without some kind of change at the Dart language level though...  Any given name we create could cause this.

**Comment by zjuwjf** [comment]
At present, the problem of "Action" name has greatly affected the developer's experience, not only within the xianyu team, but also in other teams whose projects relies heavily on the fish-redux.

As fish-redux-based projects continue to upgrade to 1.7,  this problem will become more common and serious,  it will make the code compiled fail, and there are many files to be modified.

The [hide] or [as] solution does not solve the intrinsic conflict problem. In projects which using fish-redux, [fish-redux] and [flutter/widgets] are strongly dependent, and their conflicts are pervasive.

At present, it seems that there are two quick solutions to this problem:

1. Flutter modifies the "action" name . Because action is not its basic concept for the core library of flutter. It is more reasonable to change it to a more specific name in a specific scenario. 

2. Fish-redux changes the name of action to "fish-action", but this is a betrayal of the Redux system, and a breaking-change which requires a lot of renaming for previous projects using fish-redux.

Change or not, please let us reach a conclusion as soon as possible.

**Comment by zjuwjf** [comment]
cc @gspencergoog @Hixie any suggestions?

**Comment by zhangruiyu** [comment]
dedede

**Comment by gspencergoog** [comment]
While I understand your frustration, and I'm sorry that this has impacted you, I can't really see a better alternative at the moment to modifying your imports.

The author of a package (be it Flutter, or `fish-redux`) should have the flexibility to define symbols specific to their package without having to worry overly about naming conflicts with other packages. It results in generally clearer, easier to read APIs all around, and widespread collisions are rare in practice.

Dart provides mechanisms for hiding, showing, and aliasing of symbols, which are fairly powerful, but I agree that there may be further things that the Dart team could do to make dealing with this easier (namespaces, or some other solution). However, for better or worse, Dart's default behavior is to bring all imported symbols into the same namespace, which means that eventually some name collisions will occur. Resolving the conflicts should be done by the developer when colliding names are used together because only the developer knows how they want it to be resolved. E.g. do they want to translate one flavor of "Action" into another, or are they just not using one of them?

You can avoid collisions by always importing things with `as` _[package]_. For instance, you could import all flutter libraries like so:
```dart
import "package:flutter/widgets.dart" as flutter;
import "package:flutter/material.dart" as flutter;
```

And then reference all flutter symbols with the `flutter` prefix (e.g. `flutter.Action`). This is the equivalent of adding "Flutter" to the front of all the flutter symbols, but more flexible since you only have to do it in files where there are collisions. In general, I wouldn't recommend it (it's more tedious to type, and more cluttered to read), but it depends on your use case, and on how much overlap you have between Flutter code and the code of other packages. Maybe it would instead make more sense to do this with other packages and leave Flutter in the default namespace, or, as you've described, just hide those colliding symbols that you're not using.

As for the specific case of `Action`, it's a core concept to keyboard shortcuts and menus common to desktop and web platforms, as well as for undo/redo patterns. As with all Flutter APIs, we attempt to name them as straight-forwardly as possible, in the same way that `fish-redux` has named theirs in a straightforward fashion for them, so renaming either package's class to avoid a naming conflict here isn't really something I'd prefer to do.

If we (and other package authors) were to defer to the naming used in all Flutter-compatible packages before naming our classes, we'd pretty shortly end up prefixing all of our names with "Flutter".  As mentioned above, this is not something we'd like to do: it's unnecessarily verbose, and the equivalent can be done as described above by the importer with `as`.

**Comment by dnfield** [comment]
One option along the lines of @gspencergoog's suggestion that might be less painful is something like

```dart
import "package:flutter/material.dart" hide Action;
import "package:flutter/mateiral.dart" as flutter show Action;
```

Which would then only require the prefix for when you want to use Flutter's actions.

Alternatively, you could just hide `Action` altogether for now until you want to use it later.

**Comment by gspencergoog** [comment]
Actually, there's one more way you could solve this.  You could create your own "my_flutter.dart" package and just export the parts you want from it, and import that package instead of importing flutter's packages directly.  For instance:

in `my_flutter.dart`:
```dart
library my_flutter;

export 'package:flutter/foundation.dart';
export 'package:flutter/widget.dart' hide Action;
export 'package:flutter/material.dart' hide Action;
// ... and any other packages you want to use from flutter.
```

And then in your app, do this import:
```dart
import 'my_flutter.dart';
```
instead of importing flutter directly.

That way you'd have control over what symbols from flutter were exposed, all in one place instead of in each individual component.  If you wanted to, you could have a separate one for each flutter package, or you could put them all in one (which could affect compile/reload times, so be sure to test it to see if it's acceptable).

You'd have to update all your code once to swap the imports to use yours, but then you'd have control centrally.

**Comment by zjuwjf** [comment]
I don't think that the above tips can really solve the problems, especially when a large number of teams are using fish-redux. Although we do this at the moment, it brings a very bad code experience.

Going back to the beginning of the question, is the name 'Action' should be used in Flutter to handle the keyboard shortcuts and menus common to desktop and web platform or left this name to the community more friendly?

Action is not from fish-redux, but from Redux. Especially before Flutter, Redux has gained wide recognition and influence in data state management. Action is a fundamental concept in the Redux system.

I think that without the name Action, it does not have any effect on the Flutter system itself, but it will cause great damage to the Redux system.

**Comment by timsneath** [comment]
This is good food for thought, @zjuwjf. Thank you for raising this issue. I think we need to step back and think about what might be a good general-purpose solution to this problem. 

Unfortunately, the `Action` clash is challenging to solve in the short term since a subsequent build has now been promoted to the `stable` channel. Please accept our apologies. Other than renaming `Action`, I'm interested in hearing if there are any other language or scoping solutions that you would find palatable?

**Comment by zjuwjf** [comment]
Consider not exporting Actions in the following libraries.
```dart
'package:flutter/material.dart';
'package:flutter/cupertino.dart';
'package:flutter/widget.dart';
```

The Action or Keyboard can be exported in a separate library. Like
```dart
'package:flutter/keyboard.dart';
or
'package:flutter/actions.dart';
```

In the longer term, as flutter covers more devices and features, it is necessary to break down into more independent libraries.

**Comment by jeepc** [comment]
agree @zjuwjf

**Comment by tianlinzx** [comment]
agree @zjuwjf

**Comment by gspencergoog** [comment]
Yes, we also considered separating actions into a separate package, but because we are about to add support for actions and shortcuts to most material and cupertino widgets, those packages would explicitly depend on the `Action` class, and we don't want to reference a class in a public API which is then not exported from the library that references it. That leads to confusion, since methods in a library would be returning instances of a class (in this case `Action`) which the caller doesn't have a definition for. The developer would have to discover which additional package to import in order to use the class that returns the `Action`, which is not how any of our other APIs work.

In addition, code like yours (with it's own definition of `Action`) might fail in strange ways because it would be providing the wrong definition of `Action` to the compiler that is not compatible with the one the material and cupertino widgets would be expecting.

**Comment by baotoushashou** [comment]
In my opionion,it's better to rename the 'Action' fish-redux has to 'ReduxAction'. I don't think the name 'ReduxAction' will break specification of Redux.  The fish-redux is a very excellent framework, I have choosen it for my next app.It would make me very exciting if it would upgrade more frequently.

**Comment by dnfield** [comment]
My sense on this is that the language provides a way to deal with this (`import`s that use `hide/show` and `as`, potentially `exports` doing the same as well), but that it would still be burdensome to deal with this in a larger software project.

Is there some way that tooling could help automate resolving these kinds of conflicts more painlessly?  I don't know if that would be the analyzer or the LSP or the IDE plugin(s), but something like a "quick action" or "quick fix" or whatever it's called to refactor the imports for you?

/cc @devoncarew @DanTup @jacob314 @pq @stereotype441

**Comment by chenxianqi** [comment]
The same problem is here, I hope to get a good solution

**Comment by DanTup** [comment]
> Is there some way that tooling could help automate resolving these kinds of conflicts more painlessly? I don't know if that would be the analyzer or the LSP or the IDE plugin(s)

This would have to come from the analysis server. I think it makes sense. Maybe when a naming conflict is found in the document, a warning (lint?) could be added against the imports that bring in those names with quick-fixes to hide the type from that import? Adding a prefix may be trickier since we'd want to prompt for a name (it's more like a refactor than a quick-fix) but in VS Code we could probably inject that if we had a stable lint code to detect.

**Comment by devoncarew** [comment]
Some of the newer code completion work will auto-add the correct `show` / `hide` clause. But I don't think relying on this scales very far. I think that generally the framework should be very conservative about adding new classes w/ names that would be very common in user code or other libraries. The Dart libraries themselves had this problem when we added the `Resource` class several years ago.

**Comment by zjuwjf** [comment]
So it seems that there is no plan to adjust the name of "Action", and there is no better solution.

What can we do? 
Can I use a name "Intent" ? It sounds dangerous, maybe it will be used by flutter in the next version.  

Can I use the name "Message", no, it is even more dangerous.

I think I can only pick a name called "FishReduxAction",  I think there will be no guy to grab the name with me. 

If I do this, developers who use fish-redux will probably feel awesome.  
Each file is filled with lots of "FishReduxAction",  just like a laptop covered with lots of "Intel-Inside" logos on the keyboard, on the screen, etc. how awesome the laptop is.

In addition to complaining, we have nothing to do.

**Comment by liugangnhm** [comment]
expect a language level solution

**Comment by amreniouinnovent** [comment]
In Android Native when there is a conflict then the library owner should change his naming not Android
in Fish Redux it could be Actions or ActionModel or just Act

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
