### ISSUE TITLE
textSelectionHandler can't move,and color can't change on iOS

### ISSUE THREAD

**Issue by phoenixsky** [flutter/flutter#34486]
### 1. The left one can't move....but the right one  is ok .
as the image ⬇️
![image](https://user-images.githubusercontent.com/6359214/59498438-03363b80-8ec8-11e9-942e-9f26a711a298.png)

### 2. textSelectionHandleColor can't change on iOS
I know the cursor color changed by the `cupertinoOverrideTheme` 's primaryColor on iOS,
what about `textSelectionHandleColor` ?

![image](https://user-images.githubusercontent.com/6359214/59500061-46de7480-8ecb-11e9-9cdf-7b05568f9e14.png)

![image](https://user-images.githubusercontent.com/6359214/59500277-b3f20a00-8ecb-11e9-8ee9-2c20aca485a6.png)

it's also blue

**Comment by justinmc** [comment]
For 1, can you try on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)?  I saw similar problems recently but it should have been fixed in  https://github.com/flutter/flutter/pull/31852 from 2 weeks ago.

For 2, you are right that the handles don't change color, but I believe that's on purpose.  The handle color is definitely hard coded in cupertino/text_selection.dart.

@HansMuller Do we purposely not support changing the color of iOS selection handles?

**Comment by phoenixsky** [comment]
thks , I user it   on the stable channel before .
