### ISSUE TITLE
Show the version from pubspec.yaml instead of 0.0.1 for iOS plugin CocoaPods

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#34565]
Inspired by https://github.com/flutter/plugins/pull/1736/files#diff-88359a9bc306f2f14ca58406beaad9b9 I think we could automatically populate more of the metadata in the podspec template for iOS plugins. This will avoid reporting an incorrect version of 0.0.1 on the command line when installing iOS plugins.

**Comment by jmagman** [comment]
I don't think this is a good idea--these podspecs should never prompt CocoaPods to initiate version solving because that could cause CocoaPods to install a random pod instead of the one embedded in the symlinked plugin package `ios` directory.  For example, https://cocoapods.org/pods/camera instead of https://github.com/flutter/plugins/blob/master/packages/camera/camera/ios/camera.podspec.

It's a little confusing, but I'd rather it be confusing than completely wrong.
