### ISSUE TITLE
FlutterPlatform._startTest fails if updateGoldens is not set

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#34615]
updateGoldens should be @required in 
https://github.com/flutter/flutter/blob/9d364043afa833606974ed3245f01618ed705e4a/packages/flutter_tools/lib/src/test/flutter_platform.dart.  Not passing this variable causes code using it to crash in unexpected ways at runtime.

In general, we should be requiring the booleans be nonnull, either with @required or with constructor asserts -- Dart booleans should never be null.

**Comment by pedromassangocode** [comment]
Hi @DaveShuckerow 
I found the method in question but I could not determine if this issue is still valid. Can you confirm if this still valid?

#### FlutterPlatform._startTest
https://github.com/flutter/flutter/blob/cba91c97d03ac8aae66317097f9e8aeade86257f/packages/flutter_tools/lib/src/test/flutter_platform.dart#L383

The parameter mentioned does not exist for `FlutterPlatform._startTest` but it does now for `FlutterPlatform. generateTestBootstrap`
https://github.com/flutter/flutter/blob/cba91c97d03ac8aae66317097f9e8aeade86257f/packages/flutter_tools/lib/src/test/flutter_platform.dart#L128

**Comment by christopherfujino** [comment]
This looks obsolete
