### ISSUE TITLE
webview_flutter: unknown setting key: debuggingEnabled

### ISSUE THREAD

**Issue by yezxxx** [flutter/flutter#34620]
Hey guys, I use webview_flutter plugin and I got a wrong message `webview_flutter: unknown setting key: debuggingEnabled`, what should I do to fix this problem? Thank you!

**Comment by wqhiOS** [comment]
the same issue

**Comment by jjjachyty** [comment]
+1

**Comment by nnquan** [comment]
+ 1

**Comment by nnquan** [comment]
+1

**Comment by mnc12004** [comment]
+1

**Comment by shuyanzi** [comment]
the same issue....

**Comment by jonahwilliams** [comment]
+1 adds nothing to the discussion and only creates noise for subscribers of the issue. Please add a reaction +1 to the original issue instead

**Comment by chustruth** [comment]
Same Issue and I'll include code because no one has stated anything:

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

`import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewContainer extends StatelessWidget {
  final url;
  WebViewContainer(this.url);
  final _key = UniqueKey();
  @override
  Widget build(BuildContext context) {
    final GlobalKey<ScaffoldState> _scaffoldKey =
        new GlobalKey<ScaffoldState>();
    return Scaffold(
      key: _scaffoldKey,
        body: Column(
          children: [
            Expanded(
                child: WebView(
                    key: _key,
                    javascriptMode: JavascriptMode.unrestricted,
                    initialUrl: url))
          ],
        ));
  }
}
`

**Comment by amirh** [comment]
Which platform are you running on? can you share the output of `flutter doctor -v` and the version of webview_flutter you're using?

**Comment by amirh** [comment]
Seems like a regression introduced in https://github.com/flutter/plugins/pull/1401 the iOS code was not updated to ignore the setting key and thus is logging an error.

Sent https://github.com/flutter/plugins/pull/1857 to fix the issue.

**Comment by amirh** [comment]
Fixed in 0.3.10+3
