### ISSUE TITLE
[local_auth] Is there a support for fallback when a user provides incorrect Touch/Face ID ?

### ISSUE THREAD

**Issue by sonalikal** [flutter/flutter#34638]
If the user tries to login via Touch/Face ID and gives too many incorrect attempts is there any way this condition is handled so that the user is presented with a appropriate dialogue ?

**Comment by yasinarik** [comment]
For iOS, I wonder the same. Is it possible to use the 4 character pin code of the phone's system if a user has too many incorrect Touch ID attempts? 

If not, how can I prompt a self-made pin code widget instead of the native Touch ID? After those unsuccessful attempts, the user must lock the screen and unlock with the pin code because the biometric auth is temporarily disabled.

**Comment by SebAubin** [comment]
Any progress on that?

**Comment by stuartmorgan** [comment]
For iOS, there's an initial PR at https://github.com/flutter/plugins/pull/2616 (although per comments there, it will need adjusting)

**Comment by carman247** [comment]
Not sure if this is related ...

After several failed attempts on iOS, using fingerprint (I'm guessing face ID as well) and then failing the PIN prompt, the phone becomes disabled, the app remains open, and the `availableBiometrics` then returns and empty list.

Therefore it is difficult to know whats going on.
