### ISSUE TITLE
Add StatusListener to implicitly animated widgets

### ISSUE THREAD

**Issue by RobinJespersen** [flutter/flutter#34799]
## Use case
I use an implicitly animated widget (like AnimatedPositioned) and I want to be able to trigger a function as soon as the animation is completed. 

## Proposal
Extend the abstract ImplicitlyAnimatedWidget class to take an AnimationStatusListener and add it in the ImplicitlyAnimatedWidgetState class as StatusListener to the AnimationController.

Furthermore extend the AnimatedPositioned widget (and similar) to handle the StatusListener appropriately.

I currently have a quick and dirty solution for that, but if this is considered to be useful I would be happy to implement it and create a proper PR.

**Comment by goderbauer** [comment]
Instead of a flow blown status listener it would probably be enough to just have an onEnd VoidCallback since the implicit animations only ever run in one direction...

**Comment by esDotDev** [comment]
I have a use case, where I want to swap children at some point during the animation (ie, button is shrinking, I want the text to appear/dissapear at the 50% mark of the animation)

Currently I have to create a whole other animationController, and play it alongside my AnimatedContainer, so that I can access the current animation value.

It would be much cleaner if we could just register an onUpdate(double value) callback for any ImplicitlyAnimatedWidget, or to have any other way we can reference it's current value.

A child widget is already animating. I think the default assumption should be that a developer may want to hook into that in the parent widget for some supplemental effects, and that should be made as easy as possible. 

It would also help us use the Animated widgets in a more composition friendly way. Rather than have to create a whole new Base Class of ImplicitlyAnimatedWidget, just to get 1 additional property, we could use whatever variant of Animated widget we need, and just hook into that to manipulate another set of properties. 

For example, if AnimatedContainer gets me most of the way there, but I also need to change color of a TextField during animation, it would be extremely simple to just hook into the existing AnimatedContainer and allow it to drive those additional updates.

**Comment by RobinJespersen** [comment]
I had a similar problem in the beginning and that was the reason y I wanted to use a full StatusListener.
But for me it was sufficient to just connect two animations.
If that is not helping u it should not be too difficult to add the onUpdate(double value) callback.

**Comment by stjfk** [comment]
> 

What do you think is the simplest way to add onUpdate?

**Comment by goderbauer** [comment]
We now have an `onEnd` callback: https://master-api.flutter.dev/flutter/widgets/ImplicitlyAnimatedWidget/onEnd.html
