### ISSUE TITLE
Multiple performance regressions

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34822]
All the following benchmarks have a small regression recently. The data is too noisy to tell which commit to blame:
* flutter_gallery_ios32__transition_perf 90th_percentile_frame_build_time_millis
* flutter_gallery_ios32__transition_perf 90th_percentile_frame_rasterizer_time_millis
* home_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis
* flutter_gallery__transition_perf 99th_percentile_frame_build_time_millis

![image](https://user-images.githubusercontent.com/22987568/59887929-16d71b80-937a-11e9-84a5-0f3df70f03a2.png)

**Comment by chinmaygarde** [comment]
<img width="1421" alt="Screen Shot 2019-06-21 at 4 38 36 PM" src="https://user-images.githubusercontent.com/44085/59956101-06d73e80-9443-11e9-934d-dbb8ce4a0b84.png">
Numbers today are again back below the baseline. This may be due to the Skia reverts made in order to fix the [other TODAY bug](https://github.com/flutter/flutter/issues/34820). The one patch run that exceeds the baseline is a change to the Dart Web stuff that should in no way affect iOS and is hence believed to be an outlier.  Closing.
