### ISSUE TITLE
TextEditingController ignores text = null

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34847]
## Steps to Reproduce

```
  final editName = TextEditingController();
...
    editName.text = 'qwe';
    editName.text = null;
```

Expected: empty text field.
Observed: text 'qwe'.

I see this behavior as counter intuitive. I would suggest adding the` ?? '' `check into `TextEditingController ::   set text(String newText)`.

Workaround: 
`    editName.text = map['field'] ?? '';`

**Comment by kangwang1988** [comment]
@abarth 
Do you have more context for the logic:
```dart
  TextEditingValue copyWith({
    String text,
    TextSelection selection,
    TextRange composing
  }) {
    return new TextEditingValue(
      text: text ?? this.text,
      selection: selection ?? this.selection,
      composing: composing ?? this.composing
    );
  }

```

**Comment by TahaTesser** [comment]
issue still exist 

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController();

  @override
  void initState() {
    super.initState();

    myController.text = "Flutter";
    myController.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    super.dispose();
  }

  _printLatestValue() {
    print("Second text field: ${myController.text}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: <Widget>[
            TextField(
              controller: myController,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
          onPressed: () {
            setState(() {
              myController.clear();
            });
          },
          label: Text('myController.text to null')),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.17.0-3.2.pre at /Users/taha/Code/flutter_beta
    • Framework revision 2a7bc389f2 (31 hours ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 81.0.4044.113
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
• No issues found!
```

</details>

**Comment by Tomucha** [comment]
Suggestion:

```
set text(String newText) {

  if (newText == null) {
     value = TextEditingValue.empty();
     return;
  }

  value = value.copyWith(
    text: newText,
    selection: const TextSelection.collapsed(offset: -1),
    composing: TextRange.empty,
  );
}
```
Or something in that sense.

**Comment by cbracken** [comment]
Taking a look at the history, I suspect this is the result of an oversight on our part pre- Flutter 1.0. We should probably have added an assertion that the argument to `set text()` be non-null and similar for the constructor prior to 1.0. Semantically, a null text value for a TextEditingController doesn't make much sense, but for optional parmaters, null is generally treated as "default value", in this case, the empty string.

I imagine the constructor was written that way because it was the most straightforward implementation at the time. `text` is an optional parameter, and optional parameters are generally treated as default. The code in question dates back to the the commit where TextEditingController was created: flutter/flutter#9119. The documentation describing the behaviour when the `text` parameter is null was added in flutter/flutter#9174, though the behaviour with respect to null is only described for the constructor and not the setter; again, because a TextEditingController with a null value doesn't make much sense semantically.

I suspect the right thing to do is to simply make the parameter non-nullable so that callers are required to set the empty string if they mean the empty string.

@justinmc and @Hixie may have thoughts on this.

**Comment by justinmc** [comment]
I am not aware of any reason that `text` should be null.  I agree that it should be non-nullable.

This got me thinking if we could work around this, what do you think of something like this? https://github.com/flutter/flutter/pull/68638

Maybe I could add a warning if the passed in value is null, and we can enforce that it's non-nullable later?

**Comment by cbracken** [comment]
I almost wonder if we should just go straight to the breaking-change of making it non-nullable rather than delay until after we go live with NNBD. 

Rationale: it's possible that some people currently have bugs in their code that rely on this being a no-op today; for them, setting it empty will be a (silent) breaking change with no compile-time warning. Making it non-nullable will be a second breaking change (with a compile-time warning). I'd be tempted to just go straight to making it non-nullable and have the compiler tell the user exactly what's wrong so they can fix their code.

**Comment by justinmc** [comment]
I agree, given we have the chance to make changes like this now!  I will update the PR https://github.com/flutter/flutter/pull/68638 to make it non-nullable.
