### ISSUE TITLE
Feature request for creating project for desktop, mobile, web targets

### ISSUE THREAD

**Issue by uuttff8** [flutter/flutter#34908]
## Description

Hello, I introduce support creating flutter project for many targets. My incomplete pull request that is can create a project just by chose the target. My fork: https://github.com/uuttff8/flutter/tree/complex-flutter-create

## Video:

![ezgif-1-6b94ed9c6f64](https://user-images.githubusercontent.com/40335671/59960670-47cb6380-94d4-11e9-8c59-7da0054f6f77.gif)

## Unresolved:

- [ ] Support create for desktop, web
- [ ] Compatibility with package, module, etc
- [ ] Make --verbose for choosing more targets and complex
- [ ] Refactor
- [ ] tests

## Checklist
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes ([x]). This will ensure a smooth and quick review process.

- [x]   I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x]   I signed the CLA.
- [x]   I read and followed the Flutter Style Guide, including Features we expect every widget to implement.
- [ ]   I updated/added relevant documentation (doc comments with ///).
- [ ]   All existing and new tests are passing.
- [x]   The analyzer (flutter analyze --flutter-repo) does not report any problems on my PR.
- [x]   I am willing to follow-up on review comments in a timely manner.

## Breaking Change
Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ]  Yes, this is a breaking change.
- [x]  No, this is not a breaking change.

**Comment by stuartmorgan** [comment]
Closing, as the issue tracker is not the right place for a PR submission.

If the goal here is to gather feedback, please file one or more feature requests that clearly describe the problem you want to solve (rather than just posting code that partially implements one possible solution to the problem). For something as significant as restructuring the way `create` works, the next step would likely be a design document, not a PR.
