### ISSUE TITLE
CupertinoDatePicker's time picker doesn't honor minimumDate and maximumDate

### ISSUE THREAD

**Issue by joharei** [flutter/flutter#34951]
## Use case

I need to limit both the date _and_ time that the user can pick in `CupertinoDatePicker`. The constructor parameters `minimumDate` and `maximumDate` take `DateTime` values, but it seems only the date part is taken into consideration.

## Proposal

When I scroll to a time outside the limits of `minimumDate` or `maximumDate`, I want the picker to scroll back to the closest valid time, just like the native iOS picker does.

For example, if I specify `minimumDate` as today at 12:00, and scroll the hour back to 09:00, the wheel should spin back to 12:00 after it settles.

**Comment by wagner1343** [comment]
I was searching for the same feature

**Comment by kerberjg** [comment]
I have encountered the same issue as of Flutter v1.7.8+hotfix.2

**Comment by mleonhard** [comment]
Same problem in Flutter 1.8.4-pre.65.

Flutter team, please fix this.  Without this fix, the experience for iOS users is poor.  When will Google take iOS seriously enough to allocate enough headcount to solve these long-standing issues and close the feature gap between Flutter for Android and Flutter for iOS?

Related issue: #24820

**Comment by magax** [comment]
This should be reopened, I have the same issue on every channel. I'm using the widget with `mode: CupertinoDatePickerMode.time`, when the `minimumDate` value is selected it does not fire any update. Since I just want a time greater than the current time, my workaround for this is to set the minimum time allowed 1 minute earlier but this is not a great user experience. The value color is grey instead of black, can be selected but is not being returned.

**Comment by LongCatIsLooong** [comment]
@magax could you provide a minimal repro so we can confirm/investigate?
