### ISSUE TITLE
IconButton cannot skip focus traversal

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#34983]
## Use case

In a list of widgets an IconButton will get focus when requesting next focus and currently there is no way to prevent this since it only sets the *focusnode* of the *Focus* widget but not the *skipTraversal* propery.
And the focus widget overrides the skipTraversal property of the focusnode given.

## Proposal

Add a skipTraversal property to IconButton that passes it on to the Focus widget.

**Comment by gspencergoog** [comment]
The part about overriding `skipTraversal` from what is set on the `focusNode` is already fixed, I'm pretty sure, in which case you should be able to set that on the node and have it act the way you want. I'd prefer not to add every `Focus` attribute to every control that can take focus if we can help it: the API is already pretty viral.

If the `Focus` widget is still overriding the `focusNode`'s notion of `skipTraversal`, then we should fix that, however. I think it properly sets it [here in `didUpdateWidget`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/focus_scope.dart#L407), so that if the widget's `skipTraversal` is null (as it is in `IconButton`), then it should take the one from the `focusNode`:

**Comment by Kavantix** [comment]
Ah I see, that's probably why `skipTraversal` no longer has a default value.
Then we just need to update that part of the documentation, (it currently states that it cannot be null)
