### ISSUE TITLE
gitignore key.properties

### ISSUE THREAD

**Issue by SpectralKH** [flutter/flutter#35027]
Documentation does tell you to to keep it `android/key.properties` private, but I think it would still be helpful to add `**/android/key.properties` to `.gitignore` in the default Flutter project.

**Comment by kangwang1988** [comment]
I checked the signing logic for a default Flutter project and finds it depends on ~/.android/xxx.keystore, which is not contained in my flutter project and doesn't to be added in .gitignore.
I think it's ok for the default Flutter project to set .gitignore for a most commonly-used scenario and give the developers more freedom where they can customize the file according to their requirements.
Closing this issue now.

**Comment by SpectralKH** [comment]
@kangwang1988 Could you please elaborate? I don't really get what you mean

I'm not sure why you're mentioning ~/android/xxx.keystore, as I'm talking about <app dir>/android/key.properties, which the [Flutter documentation](https://flutter.dev/docs/deployment/android#reference-the-keystore-from-the-app) tells you to create and not commit.

**Comment by tedhenry100** [comment]
I think the combination of documentation and Flutter defaults should work well together. I agree that `**/android/key.properties` should be added to `.gitignore`.

**Comment by cytryn** [comment]
That was the first thing I looked after I say the documentation suggesting not to check on public source control. I quickly checked the default `.gitignore` for Flutter project and its not there. So I got confused because the goal of creating an app is to eventually publish it to the stores, where you need a key store.
So I think it should be on default `.gitignore` too.

**Comment by guidezpl** [comment]
FYI fixed in https://github.com/flutter/flutter/pull/57601
