### ISSUE TITLE
Request for additional translations of the Flutter material widget strings 

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#35024]
There is an internal team building a mobile app using Flutter getting close to launch. They've identified 22 out of the 88 locales that do not have translations for the Flutter material widget strings, and would like them to be added.

The missing locales are:

```
[af, am, az, bn, eu, gu, is, ka, kn, ky, lo, mk, ml, my, ne, no, pa, si, sq, te, uz, zu]
```

More info at: https://b.corp.google.com/issues/135720347

**Comment by Hixie** [comment]
Status: waiting for translators.

**Comment by diegovar** [comment]
Any updates on this?

**Comment by Hixie** [comment]
I believe this has landed? @HansMuller ?

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/36589 includes all of the localizations exception for 'kn'. 

We've temporarily removed the Kannada localization ".arb" files because viewing them with Emacs on Linux can crash the GUI version of the editor.

packages/flutter_localizations/lib/src/l10n/cupertino_kn.arb
packages/flutter_localizations/lib/src/l10n/material_kn.arb

These files contain characters that will cause google emacs to SEGV because of a bug in OpenType Font (libotf) library.
More information here: http://emacs.1067599.n8.nabble.com/bug-30193-The-deadliest-file-in-Emacs-history-td447264.html.

The files will be restored when https://github.com/flutter/flutter/issues/36704 is resolved.
