### ISSUE TITLE
crash while building an flx

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3508]
## command

flutter build flx --target ... --output-file ... --snapshot ... --depfile ... --no-include-roboto-fonts --manifest assets.yaml

## exception

FileSystemException: Cannot open file, path = .../build/flx/icon.png' (OS Error: No such file or directory, errno = 2)

```
dart:io                                                           _File.readAsBytesSync
package:flutter_tools/src/zip.dart 89                             _ZipToolBuilder.createZip
package:flutter_tools/src/flx.dart 383                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/flx.dart 401                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/flx.dart                                assemble
package:flutter_tools/src/flx.dart 308                            build.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 60                    runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/flx.dart                                build
package:flutter_tools/src/commands/build_flx.dart 48              BuildFlxCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/build_flx.dart                 BuildFlxCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 156         FlutterCommand._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 108                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 94          FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 239  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 187  FlutterCommandRunner.run
package:flutter_tools/executable.dart 85                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 79                          main.<async>

**Comment by eseidelGoogle** [comment]
Presumably the asset is listed in the flutter.yml but doesn't exist?

**Comment by alhaad** [comment]
It exists, and the curious thing is that every alternate build fails.

**Comment by jason-simmons** [comment]
It looks like this is happening because the asset is located in the root directory of the Flutter project.

The FLX builder (specifically _parseAssets) searches through the directory tree where the asset lives in order to find other variants of the asset.

The first time you build the FLX, _parseAssets finds "icon.png" at the root of the project and adds it to the ZipBuilder.  When the ZIP is built, the ZipBuilder then copies it to its "build/flx" working directory, creating "build/flx/icon.png".

During the second build of the FLX, _parseAssets finds both "icon.png" and the leftover "build/flx/icon.png", and both source paths are added to the ZipBuilder's work list.  The ZipBuilder destroys and recreates the "build/flx" working directory.  ZipBuilder processes the "icon.png" source path, creating "build/flx/icon.png".
ZipBuilder then processes the "build/flx/icon.png" source path.  This file now exists because of the prior copy of "icon.png", so ZipBuilder copies "build/flx/icon.png" to the working directory, creating "build/flx/build/flx/icon.png".

In the third run, _parseAssets find "icon.png", "build/flx/icon.png", and "build/flx/build/flx/icon.png" (the latter two left over from the second build).
However, after the ZipBuilder destroys and recreates the "build/flx" directory, "build/flx/build/flx/icon.png" no longer exists.  The result is the error shown above.

Future builds will alternate between the behavior seen in run #2 and run #3 as "build/flx/build/flx/icon.png" is created and deleted.

As a quick fix, you can work around this by moving the asset file out of the project root directory and into a separate assets directory.

Beyond that, the flutter tool should exclude the ZIP working directory when searching for assets.
It might make sense to delete the ZIP working directory at the start of the FLX build process.  Or place some restrictions on where the tool searches for variants.

**Comment by alhaad** [comment]
Cool. Thanks for taking a look @jason-simmons!
Will do the quick fix in our repo.
