### ISSUE TITLE
Setting form field validator error text manually keeping animation

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#35101]
Hi everyone,

I'm building a form in which I validate the inputs with an API call and therefore can't use the built-in `validator` function to set the error under the field.
I am aware that the error can be set manually via the `errorText` attribute but doing so get rid of the nice animation provided by the widget.

Is there a way to set the validator animation manually while keeping the animation?

Thanks!

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
