### ISSUE TITLE
Error when Ink.image child property is not specified

### ISSUE THREAD

**Issue by Rotanticu** [flutter/flutter#35191]
The documentation said 

> The image argument must not be null. The alignment, repeat, and matchTextDirection arguments must not be null either, but they have default values.

But in fact the child must not be null too,Otherwise, it will throw a error.
```
Ink.image(
  image: NetworkImage(post.previewUrl),
  child: Container(),
),
```
It's strange. image is not a child？When I just new a empty Container(),It's working perfect,
I didn't find a place to use child, Why there is a "child"?

**Comment by shihaohong** [comment]
Hi @Rotanticu, I did a quick check and `child` does not have to be null here. _However_, you must at least specify a width/height, padding or some kind of sizing constraint. 

Otherwise, the Ink does not know how to size itself. I get the following error message:
```
I/flutter (32343): #0      debugWidgetBuilderValue.<anonymous closure> 
package:flutter/…/widgets/debug.dart:271
I/flutter (32343): #1      debugWidgetBuilderValue 
package:flutter/…/widgets/debug.dart:288
I/flutter (32343): #2      _LayoutBuilderElement._layout.<anonymous closure> 
package:flutter/…/widgets/layout_builder.dart:114
I/flutter (32343): #3      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2320
I/flutter (32343): #4      _LayoutBuilderElement._layout 
package:flutter/…/widgets/layout_builder.dart:109
```

Try specifying a width/height and see if that resolves your issue. If it does, we can move forward by adding documentation to better describe this behavior. Otherwise, please submit a minimal reproducible sample if your error/conditions are different.
