### ISSUE TITLE
Flutter shouldn't offer to run "mac" if examples don't work yet.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#35215]
```
eseidel@eseidel-macbookpro3 /src/flutter/examples/flutter_gallery %flutter devices   

2 connected devices:

macOS  • macOS  • darwin-x64     • Mac OS X 10.14.5 18F132
Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 

eseidel@eseidel-macbookpro3 /src/flutter/examples/flutter_gallery %flutter run -d mac

Launching lib/main.dart on macOS in debug mode...
Podfile missing
```

**Comment by stuartmorgan** [comment]
Other than needing a better error message (filed the above issue to track that specifically), this seems right; what is the behavior you are expecting? `flutter devices` isn't offering to run on macOS, it's just (correctly) listing it as available for Flutter. It's not project-aware, since it can be run from anywhere. Do you think it should be changed to only work in the context of a project, and then filter?

(Compare with stable channel behavior of plugging in a phone or launching a simulator/emulator, then running `flutter devices` from, say, your home directory. It'll list that device, but that doesn't mean your home directory can be run as a Flutter project on that device.)

**Comment by eseidelGoogle** [comment]
I agree with you that this is in the right ballpark and I don't think my bug serves much use. :)

I think whether `flutter devices` should show mac yet (without explicit opt-in from the user) or not is a separate question that we should sort out with the PMs.

Thanks for the considered response.

**Comment by stuartmorgan** [comment]
Something that occurred to me later is that we could likely augment the `devices` output with support annotations when run in a project. So it would still be runnable from anywhere, but if you're in a project devices that were unsupported would say something like `not supported by this project` in a new column at the end.
