### ISSUE TITLE
PointerHoverEvent is misleadingly named

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#35226]
The Windows definition of "hover" is that the pointer has remained still over a control for some period of time, and there is an associated event (WM_MOUSEHOVER) that is sent when this happens. When a mouse enters a region it gets (the first of a series of) WM_MOUSEMOVE events, and when it exits it gets WM_MOUSEEXIT.

CSS defines a ":hover" pseudo-class that is active when the pointer is over an element (the pointer doesn't have to be still). The corresponding events are mouseenter and mouseleave; there is no specific "hover" event.

Flutter defines PointerEnter and PointerExit events, which are consistent with HTML/CSS and do not particularly conflict with Windows' terminology. However, it also defines a PointerHover event, which contrasts with Windows' terminology, and has no equivalent in HTML/CSS. Its closest equivalent is WM_MOUSEMOVE in Win32 and mousemove in HTML/CSS with the exception that those events fire whether the pointer is down or up.

PointerMove is already defined in Flutter as happening specifically when the pointer is down, so it's understandable why that name was not used for what PointerHover does; however, the current name is misleading, since "hover" literally means "remain in one place in the air", and so the implication of the name PointerHover is that it implements the Win32 definition of hover. (The CSS pseudo-selector is similarly misleading and should probably have been named :over instead.)

I would suggest either finding some compatibility story that would allow re-use of PointerMove whether the pointer is up or down, to make it consistent with other platforms, or finding a name that doesn't conflict with related usage.

**Comment by PixelToast** [comment]
As far as I know `MouseHover` events used in this way has only existed in WinForms and not any other Windows UI frameworks so not many people are going to be confused by it's usage in Flutter.

I don't think the term itself is misleading as there are multiple definitions of hover, see https://www.merriam-webster.com/dictionary/hover

"to position (a computer cursor) over something (such as an image or icon) without selecting it"
"to remain suspended over a place or object"

It doesn't make much sense for a delayed event like that to exist in Flutter so I don't think developers will assume it has the same behavior as WinForms especially since the event is both stateful and has an opinionated delay.

**Comment by krisgiesing** [comment]
Neither definition you quote above implies motion. Rather, they both imply motionlessness.

The reason for a delayed event to exist in Flutter is to add things like hover-triggered tooltip, as for example in Chrome tabs to show the full page title in a tooltip. The PointerHoverEvent as currently defined would be used to create this effect, but the code to do so ends up scanning very awkardly (pseudocode):

if (pointerEnter) set hoverTimer;
if (hoverTimer.expired) show tooltip; // mouse is hovering
if (pointerExit || pointerHover) hoverTimer.cancel; // mouse is no longer hovering

Notice how the word "hover" ends up having two completely opposite meanings, one related to motionlessness (for a period of time) and the other (Flutter's definition) related to motion.

**Comment by Hixie** [comment]
In practice this does not seem to have been a problem (people extrapolate from CSS `:hover`).
