### ISSUE TITLE
Android TV remote control (DPAD) support

### ISSUE THREAD

**Issue by renatofrota** [flutter/flutter#35346]
## Use case

[Issue #33456 (closed)](https://github.com/flutter/flutter/issues/33456) is about DPAD support. However, I think (and hope) the support could be improved.

React Native supports DPAD keys on Android TV devices in a form it "just works", [as they say](https://facebook.github.io/react-native/docs/building-for-apple-tv):

> TV devices support has been implemented with the intention of making existing React Native applications "just work" on Apple TV and Android TV, with few or no changes needed in the JavaScript code for the applications.

Any app written in React Native have support for Android TV remotes in a way you press the DPAD arrows and the elements on screen are "focused" dynamically:

2 buttons, side by side. You press "right arrow" in DPAD and the button at the right side is focused. You press "left arrow", left button is focused. Pressing central key behaves the same as tapping the element on a touchable screen.

Note: using the TVEventHandler as in their example is only necessary in the cases you need to perform custom actions (other than just focusing the elements).

The only limitation on React Native's support for DPAD is Text fields not being focusable this way:

> Known issues:
>        InputText components do not work for now (i.e. they cannot receive focus).

## Proposal

Supporting DPAD controls in a similar way would stimulate Android TV developers to adopt Flutter - specially in case Text fields are also supported, since this is an important lack in RN.

**Comment by tvolkert** [comment]
@gspencergoog is this done now as part of your recent work?

**Comment by gspencergoog** [comment]
Yes, as far as I know, this should work.

**Comment by sabinbajracharya** [comment]
@gspencergoog  I am not sure if this is the place to ask but her it goes. The DPAD seems to work but is there a way to control the speed at which the focus move to different nodes (widgets)? 

I am thinking about developing TV apps using flutter instead of Android Leanback framework and the device I have to build the app on has very low specifications (Ram and CPU).  When holding DPAD, DPAD events are generated faster and the focus moves very fast (eg: in list or grid view) which can be problematic on older and less powerful devices. So, what I would like to do is when I press and hold the DPAD key, I want to focus to move once every one second. Is it possible right now with the current implementation?
