### ISSUE TITLE
Flutter cold start is slowly in some low-end Android devices

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter#35358]
After we use Flutter in our app, we found that the performance of cold start is not good as we expected. After I read the code of startup, I think there is room for improvement.
I discover that there is a latch between platform thread and ui thread when create `Shell`. These threads are always very busy when startup especialy in large complex app. The latch will slow it down, even produce  ANR. So I have tried remove the latch in PR https://github.com/flutter/engine/pull/8489.
We have used this patch online, I make sure that is effective. Our first frame time of cold start is almost 2 times earlier than before.
Hope the PR will help you find a effective way for boost startup.

**Comment by mm-public-tx** [comment]
mark

**Comment by zoeyfan** [comment]
Spoke with customer "headline" that this issue no longer is a priority for them.

**Comment by zoeyfan** [comment]
@liyuqian

**Comment by liyuqian** [comment]
If this is specific to add-to-app, there's a PR in review https://github.com/flutter/engine/pull/17192 that also claims ~2x speedup. I noticed that the original PR https://github.com/flutter/engine/pull/8489 for this issue has been closed since we haven't heard back from the author for a while. Meanwhile, Aaron does land something similar in https://github.com/flutter/engine/pull/10182.

**Comment by xster** [comment]
I assume this is the main-thread cost of pre-warming the engine and the request is for async engine starts?

**Comment by liyuqian** [comment]
I believe so.

**Comment by darshankawar** [comment]
Keeping this issue open based on recent above activity and comments.
