### ISSUE TITLE
Incorrect(Improvement to) documentation related to publishing a package

### ISSUE THREAD

**Issue by VikasJilla** [flutter/flutter#35453]
Hi 

I followed the steps provided [here](https://flutter.dev/docs/development/packages-and-plugins/developing-packages) to publish a package. 

the dry run command worked fine 

then when I finally tried to publish using  `flutter pub publish` provided in the above link it didn't work

But when I used this -  `flutter pub pub publish` it got published successfully.

Please add `flutter pub pub publish` to the documentation as well. So, that some other person doesn't loose lot of time like I did.

**Comment by mikhail-tokarev** [comment]
hi @VikasJilla 
I see that since this issue was opened 
changes have been made to the [documentation](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#publishing-packages).
I think it's safe to close this issue,
if you disagree please write in the comments and I will reopen it.
