### ISSUE TITLE
blank page when I started web flutter debugging

### ISSUE THREAD

**Issue by ocelili** [flutter/flutter#35563]
I have a problem when flutter web debugging. My launching project doesn't stop and displays a blank page
look like this 
![xJpuA](https://user-images.githubusercontent.com/51776661/60632529-56990b00-9e30-11e9-903a-19232f495dea.png)

and blank page 
![Untitled](https://user-images.githubusercontent.com/51776661/60632543-657fbd80-9e30-11e9-874b-a815aee9569e.png)

please help mee

**Comment by spiralni** [comment]
The same here. Besides I've got this error 

`[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 670ms
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 407ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.6s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 407ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.6s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 3ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Serving DevTools at http://127.0.0.1:50792
[INFO] Starting resource servers...
[INFO] Serving `web` on http://127.0.0.1:50783
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 786ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 280ms
[INFO] Succeeded after 1.1s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
Unhandled exception:
FormatException: Unexpected character (at character 1)
Not Found
^

#0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)
#2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)
#3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)
#4      JsonDecoder.convert  (dart:convert/json.dart:493:36)
#5      JsonCodec.decode  (dart:convert/json.dart:151:41)
#6      jsonDecode  (dart:convert/json.dart:94:10)
#7      parse
#8      Sources.scriptParsed  (package:dwds/src/sources.dart:55:19)
<asynchronous suspension>
#9      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
#10     CastStreamSubscription._onData  (dart:_internal/async_cast.dart:81:11)
#11     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
#12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)
#14     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:68:11)
#15     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)
#16     WipDomain.eventStream.<anonymous closure>.<anonymous closure>  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
#17     _HandlerEventSink.add  (dart:async/stream_transformers.dart:228:7)
#18     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:120:24)
#19     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
#20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
#21     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
#23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
#24     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)

Exited (255)
`

**Comment by jakemac53** [comment]
cc @grouma

I believe the fix here is to downgrade to an older Dart SDK version (in this case that would mean an older flutter sdk). This is fixed upstream but I don't know when the next Dart SDK update in flutter will be.

**Comment by grouma** [comment]
Yes. This is a Windows specific issue that was fixed recently: 
https://github.com/dart-lang/sdk/issues/37364

**Comment by ocelili** [comment]
@grouma but my version dart is 2.4.0 ??

**Comment by grouma** [comment]
I haven't been able to reproduce this locally but this looks very similar to this issue:
https://github.com/dart-lang/stagehand/issues/620

The user resolved their problem by using localhost instead of 127.0.0.1. Let me know if this works for you as well.

We will have a release in the near future which will keep the injected client unminified so that the errors returned are more helpful. This should help us fully resolve the issue instead of just providing a work around.

**Comment by truthmast** [comment]
Is there a branch with the unminified version of webdev?

I've been getting `Uncaught Instance of 'minified:p'` and found this issue following a trail of others that have been closed and their unminified branches have been deleted. Here's my error:

```
Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8888/web/webdev/src/serve/injected/client.js:367:3)
    at nq.$0 (http://localhost:8888/web/webdev/src/serve/injected/client.js:5445:20)
    at Object.uK (http://localhost:8888/web/webdev/src/serve/injected/client.js:1268:5)
    at kK.uP (http://localhost:8888/web/webdev/src/serve/injected/client.js:1270:7)
    at lL.$1 (http://localhost:8888/web/webdev/src/serve/injected/client.js:4865:3)
    at vk (http://localhost:8888/web/webdev/src/serve/injected/client.js:441:17)
    at MutationObserver.<anonymous> (http://localhost:8888/web/webdev/src/serve/injected/client.js:449:51)
```

Related Issues:
https://github.com/dart-lang/stagehand/issues/620
https://github.com/dart-lang/build/issues/2337

**Comment by ferhatb** [comment]
See --minify in https://github.com/dart-lang/build/blob/master/docs/getting_started.md. Basically add build.yaml file next to your pubspec.yaml

**Comment by truthmast** [comment]
It's not my code that is minified, it is the code distributed with the [development web-server] (https://github.com/dart-lang/webdev)

**Comment by grouma** [comment]
I just published a new version of `webdev` (`2.3.0`) which does not minify the injected client. Hopefully the corresponding unminified error will help us get to the bottom of the issue.

**Comment by mohalmah** [comment]
I got the exact same issue with the new `webdev (2.3.0)`

this is the debug log:
`[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 366ms
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 333ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 333ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.2s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 2ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:52438
[INFO] Serving `web` on http://127.0.0.1:52424
[INFO] About to build [web]...
[INFO] Running build...

[INFO] Running build completed, took 497ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 515ms
[INFO] Succeeded after 1.0s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
Unhandled exception:
SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 52534
#0      ChromeConnection.getUrl  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:79:19)
<asynchronous suspension>
#1      ChromeConnection.getTabs  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:45:26)
<asynchronous suspension>
#2      ChromeProxyService.create  (package:dwds/src/services/chrome_proxy_service.dart:70:44)
<asynchronous suspension>
#3      DebugService.start  (package:dwds/src/services/debug_service.dart:83:55)
<asynchronous suspension>
#4      DevHandler.startDebugService  (package:dwds/src/handlers/dev_handler.dart:87:25)
<asynchronous suspension>
#5      DevHandler._createAppDebugServices  (package:dwds/src/handlers/dev_handler.dart:235:15)
<asynchronous suspension>
#6      DevHandler.loadAppServices.<anonymous closure>  (package:dwds/src/handlers/dev_handler.dart:105:24)

#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:281:23)
#8      DevHandler.loadAppServices  (package:dwds/src/handlers/dev_handler.dart:104:24)
#9      Dwds.debugConnection  (package:dwds/dwds.dart:44:46)
<asynchronous suspension>
#10     AppDomain._initialize  (package:webdev/src/daemon/app_domain.dart:67:37)
<asynchronous suspension>
#11     new AppDomain  (package:webdev/src/daemon/app_domain.dart:120:5)
#12     DaemonCommand.run  (package:webdev/src/command/daemon_command.dart:91:29)
<asynchronous suspension>
#13     CommandRunner.runCommand 
package:args/command_runner.dart:197
<asynchronous suspension>
#14     _CommandRunner.runCommand  (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> 
package:args/command_runner.dart:112
#16     new Future.sync  (dart:async/future.dart:224:31)
#17     CommandRunner.run 
package:args/command_runner.dart:112
#18     run  (package:webdev/src/webdev_command_runner.dart:19:56)
#19     main 
..\…\bin\webdev.dart:17
<asynchronous suspension>
#20     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:299:32)
#21     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

Exited (255)`

**Comment by grouma** [comment]
@mohalmah you are running into a different issue. In your case `webdev` can't connect to the debug port of your Chrome instance. Are you launching through VS Code or `webdev`? If it's `webdev`, I assume you are using `webdev serve --debug`. In that set up Chrome should automatically launch with the debug port enabled. I need more details on your set up to figure out what's going on.

**Comment by grouma** [comment]
Closing this in favor of: https://github.com/dart-lang/build/issues/2337

**Comment by mohalmah** [comment]
@grouma I figured it out later on .. I was launching through VS code (F5 debug) and getting that error .. but when I launched using `webdev serve` and it worked fine through http://127.0.0.1:8080

Thanks

**Comment by grouma** [comment]
cc @DanTup

**Comment by DanTup** [comment]
@grouma I'm not sure what what the issue here is (there seem to be a few different errors) - though some of them look the same as I start hitting recently and raised at:

https://github.com/dart-lang/webdev/issues/514

I hit that both through VS Code and from the terminal when using current Flutter master (its Dart SDK about 9 days old).
