### ISSUE TITLE
[web]: Rebind scrollwheel?

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#35686]
I would like to be able to have gesture based dragging on a listview and scrolling to have different functions in my application. Is there a way to have the scrollwheel on my mouse function similar to pinch zoom would on mobile and have the drag gesture keep current functionality?

**Comment by stuartmorgan** [comment]
Could you elaborate on what issue you are encountering in trying to do this? You can implement `onPointerSignal`, which receives scroll signal events, however you like.

**Comment by MichealReed** [comment]
@stuartmorgan I can make drag scrolling and then scrollwheel do different actions with onPointerSignal?

**Comment by stuartmorgan** [comment]
Implementing `onPointerSignal` should have no effect at all on drag scrolling; the event paths for gestures and pointer signals are completely separate. Again, it would be helpful if you could explain what you have tried that didn't work, because it's still not clear to me what problem you've encountered that makes you think this doesn't work as expected.

**Comment by MichealReed** [comment]
I was not aware that the scrollwheel was considered a gesture. Thank you for the quick response, will dive in there.
