### ISSUE TITLE
Flutter apps should be able to receive navigations from browsers

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#357]
For example, to complete an OAuth flow.

**Comment by Hixie** [comment]
On Android this basically means either implementing our own custom scheme or assigning a URL space to an app, right? Do both of those work on iOS too?

**Comment by eseidelGoogle** [comment]
iOS: https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10

On Android, it's startActivity*:
http://developer.android.com/guide/components/intents-filters.html#ifs

**Comment by eseidelGoogle** [comment]
I had this personally asked of me 3 times across our 2 hackathons.

**Comment by abarth** [comment]
I've added the "adoption blocker" label to indicate the importance of this issue.  Not sure if that's the right label to use to flag these sorts of issues.

**Comment by sethladd** [comment]
Is this critical to fix before the end of August?

**Comment by eseidelGoogle** [comment]
We no longer have a customer asking for this, so although we definitely should do this, I don't think this has to be August.

**Comment by eseidelGoogle** [comment]
Somehow this got bumped back to M4.  Given the number of requests we've had for this, I think we should think about this for M2 or 3.

**Comment by mit-mit** [comment]
@eseidelGoogle @sethladd, FYI I'm removing the plugin tag from this, as this is different from regular plugins in that this needs to tie in with the navigation model.

Also, @sethladd did you mean to edit the milestone; looks like it's still in 4...

**Comment by Hixie** [comment]
We definitely should have an example of an OAuth flow, which presumably depends on this.

**Comment by collinjackson** [comment]
Basic OAuth with Flutter is already possible. Here's an example: https://medium.com/@segaud.kevin/facebook-oauth-login-flow-with-flutter-9adb717c9f2e

It seems like the only OAuth functionality that isn't addressed by the current url_launcher plugin is an API that calls `finish()` on the launched activity on Android and dismisses the launched `UIWebViewController` on iOS. That way, the user doesn't have to switch back to the Flutter app manually. (We don't use a `UIWebViewController` on iOS but probably should.)

Having a reasonable Facebook auth plugin that doesn't use the browser seems like a higher priority to me. If anyone has an OAuth use case that wouldn't be addressed by just adding a `finish()` API to url_launcher, please say so on this bug.

Deep linking is a separate issue and is covered in #9768.

**Comment by mit-mit** [comment]
Collin, your analysis SGTM!

**Comment by faxal** [comment]
I'm sorry if I'm missing something, but that blog post seems more a like a workaround than a solution. Usually OAuth is handled within the Application through a WebView preferably within a Dialog or some sort of popup such that user does not feel they are moved away from the application. 

To me lack of a proper solution for the most widely used authentication mechanism is big blocker in adopting flutter. It is to me.

I'm loving the framework itself.

**Comment by collinjackson** [comment]
The [flutter_webview_plugin](https://pub.dartlang.org/packages/flutter_webview_plugin) mentioned in #730 provides a way to finish the WebView activity.

I think this bug should probably be closed, and a new one opened to address the need for a plugin wrapper around the Facebook login APIs.

**Comment by refextu** [comment]
I would like to add a new use case for receiving navigations from the browser. We building a webapplication as well as a native App for our service. When someone clicks on a link in an email oder browser to a specific item, we want to open the app (if installed) with the correct view.

**Comment by Alexays** [comment]
@refextu Like deep-linking ? #11607

**Comment by tiagosito** [comment]
So...
I've been looking for an answer to OAuth2 for some time and I do not find it, all I see are parts of something that does not actually fix the problem.

As I said in this link ( https://stackoverflow.com/questions/33683162/how-can-i-navigate-to-a-web-page-from-within-a-flutter-app-oauth ), how can I resolve the case that a private provider (not google, not facebook, not Twitter, or another known but my private provider that already works with native apps) opens in a page browser, outside of my app and being able to retrieve the authorization code to perform the authentication token request?

1) How can I navigate to the OAuth web page?

I have figured out that I can navigate to an internal route like this:

Navigator.of(context).pushNamed('/some_page');
But what if I want to go to an external page like https://coolsite.com/oauth/authorize?

How can I do this (a) by opening the url in the local web browser, and (b) with an in-app web view?

2) What URL should I redirect the user to after authenticating so that they go back to the app, and how do I parse the response?

It seems there are 2 ways:

(a) Let the user be redirected to a blank page with the authorization code in the URL and title of the page. If this method - how do I parse the page or url?

(b) Redirect the user to some kind of scheme, like my-dart-app://coolsite-oauth?code=xyz". If this method - how do I register the scheme, and wouldcoolsite-oauthmap to a route that I specify when callingnew MaterialApp`, or somewhere else? And how would I parse the query param?

**Comment by samgithub-duplicate** [comment]
In these days of high focus on security, it seems to me this is a very important must have.

**Comment by markmooibroek** [comment]
Looks like this is a good start for those getting here from Google :-)
https://pub.dartlang.org/packages/uni_links

**Comment by thosakwe** [comment]
I want to share my current flow, for all those who find this issue, whether from a Web search, through perusing Flutter's issue tracker, or otherwise.

Obviously, there are a variety of ways to provide OAuth/SSO flows, but some feel clunkier than others, and this is the smoothest approach I've tried, at least in terms of user experience. 

There more often than not will have to be some sort of Web server in the equation somewhere. In my use cases, I'm running my own API server for the application. If you're not planning on setting up a remote server for your app, then you will indeed have to set up a temporary HTTP server within the context of your Flutter application, like mentioned in the above blog article (I personally am not a fan of having an entire, typically-unsecured server in the hands of an arbitrary client, but YMMV).

The flow is as follows:

1. Your user clicks the "Sign in Button."

2. A WebView is opened, *that points to your server*. If you're using an external provider, like Twitter or Facebook, when your server receives this request, it should query said external provider with the necessary credentials, and then *redirect the user* to the provider's SSO (single sign-on) page.

For example, in the Angel framework, there is a package named `angel_auth_twitter` that when visited in the browser, requests an OAuth `access code` + `login URL` from Twitter, and then redirects the user to the `login URL` sent by Twitter.

3. Once the user has signed in with the external provider, the provider sends the user *back to your server (not the app directly)*, to a callback page.

Whichever provider you are using will have a way to specify which URL's can be considered valid authentication callbacks; for example `http://mysite.com/auth/twitter/callback`.

4. Your server, upon receiving a callback request, should then exchange the access code for an access token (if using OAuth), and then somehow transmit this back to the app. If you intend to perform most functionality client-side, you'll probably want to send the token, the refresh token, the token secret, etc. all to the app. If you're managing things server-side, you'll want to sign the user into *your database*, and return some sort of token (i.e. a JWT).

Almost every server-side framework in any language has some sort of provision for this, whether it is Laravel, Express (via Passport), Angel, etc.

The goal in this step is to take the external provider's response, and turn into some sort of data that the client (your app) can use.

5. Note that the above steps 2-4 *all* took place on the server, and not within your app. Step 5 is typically the easiest, because at the end of the day it's merely a hand-off of information to the app.

Using a package like `uni_links` (https://pub.dartlang.org/packages/uni_links), your app should be listening for deep links (on a custom URL scheme) before the OAuth/SSO dance even begins.

When your server has the token ready, all that is left to do is redirect the user to a link with your custom scheme, and the necessary data attached as query parameters.

If you mounted your own HTTP server, instead of redirecting to a custom scheme, just close your server, and send the token/information back to the rest of your application using `setState`/whatever mechanism.

Example: Say I have an app named DartIsCool, and I register the scheme `dart_is_cool`. My server, when authentication is complete, should produce a redirect like `dart_is_cool://foo.bar.baz/?token=<jwt>`. 

The actual processing of the URL is up to you; in the above example, the URI's hostname doesn't really matter, just the `token` parameter. Use Dart's `Uri` API to parse and extract data from it.

At this point, if you are using `flutter_webview_plugin` or otherwise, make sure to `close` it. I don't like to use WebViewScaffold with `Navigator.push`, as IMO it is a bit clumsy, so instead I create a StatefulWidget that renders a `WebViewScaffold` *if* the current state is one of authentication.

Hopefully this is of help to someone; it took me a bit of time to figure out, but IMO it's a good way to get SSO going in a Flutter application. One of these days I'll see if I can send a PR to add `close` functionality to `url_launcher`, because other existing Flutter WebViews have proven unpredictable to me.

*Note: If you're using a custom URL scheme, keep in mind that other applications may be able to register this scheme, so it would be smart to combine this with PKCE to ensure that user data doesn't fall into the wrong hands.*

**Comment by samgithub-duplicate** [comment]
I just started using flutter and run into the same problem; getting an authorization code from the browser after using url_launcher.  Is this still in the pipeline or was this resolved.  As Hixie suggested on June 6, 2017,
**We definitely should have an example of an OAuth flow, which presumably depends on this.**

I totally agree, a simple example using url_luncher for the Oauth flow and returning at least an access code, AND some **non-manual** way of closing the browser will be great.

I noticed the milestone(s) kept getting moved around.  What is the current state?
Thanks

**Comment by thosakwe** [comment]
Is there even a non-manual way to close the browser at all?

I have a PR open to add a `close` method to url_launcher, but I don’t see how the Webview would close without being specifically told to.

**Comment by thosakwe** [comment]
Yes, the PR was merged yesterday.

**Comment by zoechi** [comment]
@thosakwe I guess you mean https://github.com/flutter/plugins/pull/924

**Comment by amadeu01** [comment]
This does not fix what is asked in the issue. But, for people who is looking at auth flow:
https://github.com/LinusU/flutter_web_auth
That plugin might help.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/26184

**Comment by rodydavis** [comment]
Here is an example on how to use routing with flutter web: https://github.com/rodydavis/flutter_routing

**Comment by r-naruo** [comment]
Related to this issue, I want to do OAuth authentication in Flutter without using Firebase or other SNS authentication, etc. in the same way.

So, I tried to use the Flutter AppAuth plugin, but it doesn't work.
https://pub.dev/packages/flutter_appauth#-readme-tab-.

The demo authentication server shown in the example code is well, but
If I change to my own server, the app will close abnormally.

Can anyone try and tell me if this plugin can solve this problem?

**Comment by Hixie** [comment]
This seems to be possible in a similar way to just handling intents at this point.
