### ISSUE TITLE
how to get _history from NavigatorState

### ISSUE THREAD

**Issue by MrLiuYS** [flutter/flutter#35715]
example:
push page1 and push page2 and push page3.
i just want to close page2. 

i look code the navigator.dart .I found _history to be private.
how to get _history from NavigatorState?

**Comment by amrfarid140** [comment]
You can use `pushAndRemoveUntil` to remove page2 when you are pushing to page3

**Comment by MrLiuYS** [comment]
> You can use `pushAndRemoveUntil` to remove page2 when you are pushing to page3

thank you! 
i know `pushAndRemoveUntil`. but  i only remove page2. 

change example:
push page1 and push page2 and push page3 and page4.
current page is page4.  i just want to close page2.

**Comment by markusaksli-nc** [comment]
Hi @MrLiuYS 
This functionality is planned to be included in an upcoming update to Navigator.
Please follow up on #45938 and feel free to comment there with your case, closing the current issue in order to track it in the mentioned one. You can comment here if you disagree and I'll reopen.
Thank you
