### ISSUE TITLE
Document why GlobalKeys aren't performant.

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#35730]
The documentation of `GlobalKey` states that they aren't performant but doesn't explain why.

Looking at the source code, I don't see anything that can cause performance issue – most of the job is done in development only.

From my understanding, the only thing performed in production is something roughly similar to: (peuso code)

```dart
void mount() {
  if (widget.key is GlobalKey) {
    assert(widget.key._element == null);
    widget.key._element = this;
  }
}
```

**Comment by micimize** [comment]
There's also the [tree re-grafting](https://github.com/flutter/flutter/blob/de7908f9e966687d03fb4eb1989bcb3d027c7226/packages/flutter/lib/src/widgets/framework.dart#L3407-L3447) - idk why that would be more expensive than any other subtree though.

Personally, at first I was kinda afraid to use any `GlobalKey`s because they were described as being expensive, but I decided that was probably meant as "relative to regular `Key`s", so that if I wasn't making 10+ it wouldn't be an issue.

**Comment by rrousselGit** [comment]
Right. 
But you could use GlobalKey only for accessing a State. 

The documentation is unclear on whether it is only the reparenting or any GlobalKey manipulation that is expensive.
