### ISSUE TITLE
First frame timeline event not reported on the simplest app

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3579]
First frame timeline event is not recorded on an app like this:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(new Text('Hello'));
}
```

It works when `MaterialApp` is used.

/cc @Hixie

**Comment by Hixie** [comment]
Yeah, if you don't use the WidgetApp widget (or MaterialApp, which uses WidgetApp) then you won't set the flag and so won't see the notification. If you never see `'Widgets completed first useful frame'`, you can just use the end of the first `'Frame'` event. If you like, I can reverse the logic so that instead of setting the flag when we're ready, we suppress it each frame that we're not. Then, any widgets-using app would fire the `'Widgets completed first useful frame'` notice. Would that work?

**Comment by yjbanov** [comment]
If it's reasonable to expect that all non-trivial apps will use `WidgetApp`, then I'm totally fine with the status quo.

**Comment by Hixie** [comment]
I think we can expect people to not use WidgetApp. It's easy to make the change. I'll fix it.
