### ISSUE TITLE
flutter create --list-samples should offer human readable output

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#35894]
New customers will love that there's a fast-expanding catalog of great Flutter samples. But it's hard to know what is available. You can spelunk through the docs and look out for a sample that has a 'Sample in an app' tab, but that's like searching for a needle in a haystack. Conversely, we have the `--list-samples` option in `flutter create`, but that produces fairly impenetrable JSON output.

It would be great if `--list-samples` defaulted to human-readable output, and the existing option was renamed to `--list-samples-json` or similar. I'd love `flutter create --list-samples` to show something like the following:

```
material.FloatingActionButton.1    Simple FloatingActionButton in a Scaffold, with a background color and thumbs up Icon
material.DropdownButton.1          This sample shows a `DropdownButton` whose value is one of "One", "Two", "Three", or 
                                   "Four".  
material.RaisedButton.1            Render a disabled RaisedButton, an enabled RaisedButton and lastly a RaisedButton 
                                   with gradient background.
...
```

**Comment by hey24sheep** [comment]
I am thinking of working on this issue, could you please let me know how should I approach? 

I have seen the command exists [here](https://github.com/flutter/flutter/blob/a1d3edc446c9df61a0fb6c3a7691e77c12b53205/packages/flutter_tools/lib/src/commands/create.dart) but how could I build the changes and run new flutter cli commands and test them in terminal. I wasn't able to find it in contribute guide.

Thank You

**Comment by muj-programmer** [comment]
Hey

I would also like to make a contribution to this feature.

Thank You

**Comment by muj-programmer** [comment]
i made a very crude attempt and i landed [here](https://drive.google.com/open?id=1DRKQMm1Qgj1WjfIa25n_jU9wNj2hP890)

**Comment by DanTup** [comment]
I think for commands run by users, we should keep the interface simple (eg. users shouldn't need to add things like `stdout` to the end). I think there are two options to do this:

1. If the filename is not provided, write the non-JSON version to stdout (otherwise, write JSON)
2. Add a `--machine` flag to get JSON output (which matches other commands)

The first option is simplest, but less consistent. For the second, we would need to migrate the tools to pass `--machine` and ship them before this change shipped. In order to do that, I think we'd need to:

1. Make the `--machine` flag work (it currently gives an error) and have the same behaviour as without it (while not actually changing the behaviour without it)
2. Ship updates to the tools (VS Code extension + IntelliJ/Android Studio) to switch to using `--machine` for the versions we know support it
3. Change the behaviour for without `--machine` to be the user-friendly version (and not require extra flags or a filename)

@gspencergoog are you the best person to run this by? Do you have opinions on the above?

(also @pq FYI - as this may lead to a change in IntelliJ/AS).

**Comment by DanTup** [comment]
@hey24sheep 

> I have seen the command exists here but how could I build the changes and run new flutter cli commands and test them in terminal

You need to delete the `flutter_tools` snapshot file in the `(Flutter SDK)/bin/cache folder` for it to be rebuilt with your changes (you may also be able to run it with `dart path_to_flutter_tools/bin/flutter_tools.dart` for faster iteration while working on it).

**Comment by devoncarew** [comment]
> I have seen the command exists [here](https://github.com/flutter/flutter/blob/a1d3edc446c9df61a0fb6c3a7691e77c12b53205/packages/flutter_tools/lib/src/commands/create.dart) but how could I build the changes and run new flutter cli commands and test them in terminal. I wasn't able to find it in contribute guide.

@jonahwilliams @zanderso we may want to think about adding more contribution instructions for flutter tools to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/README.md.

**Comment by devoncarew** [comment]
I think a good UI for this would be for `flutter create --list-samples` to list the samples to stdout in a human readable format, and for `flutter create --list-samples --machine` write the samples info to stdout as json. I'm not sure what the best migration story is for IDEs currently using the command however - I'd generally like to avoid the complexity of version checks.

**Comment by DanTup** [comment]
The existing version we've shipped will error if you pass `--machine` so I think a version check is unavoidable if we go with that (though I think it's the better option). Using `--machine` would also potentially open the door to having the json output in stdout (eg. `--machine` without a filename) which could help with permissions issues IntelliJ has having (though the reason we didn't do this originally was in case Flutter started a download or wrote other non-JSON output).

If we went with option 1 (`--list-samples` does stdout in human-readable form, and `--list-samples foo.json` does json) then it doesn't editor changes, but it's less consistent (providing a filename is what changes the output format) and wouldn't allow json to stdout (at least without some other flag or magic filename).

**Comment by muj-programmer** [comment]
@DanTup even i like the option 1 (`--list-samples` does stdout in human-readable form, and `--list-samples foo.json` does json)

but I would like to know why the flutter team initially chose to write the json output to a file, as i believe for the user the extra keys are unnecessary (user only needs the id to create a sample).

**Comment by DanTup** [comment]
>  I would like to know why the flutter team initially chose to write the json output to a file

This was done because sometimes when you invoke `flutter` it will write output to stdout (for example, but you delete the folder `(flutter sdk)/bin/cache` then it will download the Dart SDK and some other components). Having that mixed in with the JSON would make it more complicated for tools to parse. Writing it to a file ensured the JSON and any other output Flutter might generate are kept separate.

Of course, there are other ways this could be handled, but they all involve much more work (things like the SDK download are handled by a basic shell script and not in the main Dart codebase, so they're trickier to work with) and would've held up exposing the samples in the editors.

In hindsight, `--machine` probably should've been included from the start. I guess it was expected that users would find the samples from the editors and/or website.

**Comment by muj-programmer** [comment]
okay i get your point now
thanks for the proper explanation

**Comment by zanderso** [comment]
@devoncarew we have https://github.com/flutter/flutter/issues/5548 filed for that. I'll update things a bit.

**Comment by DanTup** [comment]
Some other possible thoughts @devoncarew had today:

- Hide the `--list-samples` flag from the help output and add another (`--list`, `--show-samples`) that gives the textual output
- The IDEs may move off using this command in future to directly use a manifest file shipped inside the SDK - when that happens `--list-samples` could be changed without breaking anything

**Comment by gspencergoog** [comment]
That sounds good to me.

**Comment by devoncarew** [comment]
Perhaps, use `--list-widget-samples`? I think it would be good to put a bit of space between the word `templates` - things to start new projects - and the samples demoing various aspect of various widgets.

We saw in IntelliJ that there was a fair bit of confusing for what to start new projects with - templates or samples (the templates have been designed and validated wrt the getting started experience, so should be what we guide people towards using for new projects).

**Comment by timsneath** [comment]
Are they all widget samples though? I can imagine others over time...

**Comment by devoncarew** [comment]
Are think they are all right now. That might change a bit going forward, but the issue I'm more concerned with is disambiguating between templates and samples, esp. for new users just getting started.

**Comment by Hixie** [comment]
I think it's fine for us to not support this. This option is intended for us by automated tools, it's not something we support for our users.
