### ISSUE TITLE
flutter_gallery__memory_nav regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#35896]
Around 2019-07-03, plus or minus a few days, this benchmark got worse.

**Comment by jason-simmons** [comment]
This benchmark seems to be back to normal results now.  flutter_gallery__memory_nav/diff-median increased around 7/3 and decreased around 7/16.

I tried running some of the commits near the 7/3 change but didn't notice any obvious culprit.  This benchmark is very noisy given the variability in GC behavior, so it's difficult to bisect.

**Comment by franciscojma86** [comment]
Started regressing more aggressively after [9b150f134b9b6ba103ec305f489645b5fee905d2](https://github.com/flutter/flutter/commit/9b150f134b9b6ba103ec305f489645b5fee905d2). It's all red since.

**Comment by Hixie** [comment]
cc @liyuqian this one also regressed apparently starting with the same commit that regressed the other benchmark.

**Comment by liyuqian** [comment]
This should be an improvement instead of a regression: both the start memory and the end memory drops after that PR.  The start memory drops more significantly so the diff (end memory - start memory) increases. Presumably, less start memory leaves GC more room to retain more objects so the diff increases. But since the overall memory strictly decreases, this has no negative effect for any users.

I think we should:
1. Rebaseline the diff memory
2. Ensure that the GC is called right before measuring the start and end memory for diff computation (https://github.com/flutter/flutter/issues/37318).

**Comment by liyuqian** [comment]
Rebaselined.

**Comment by franciscojma86** [comment]
@liyuqian is it the same case for [9b150f134b9b6ba103ec305f489645b5fee905d2](https://github.com/flutter/flutter/commit/9b150f134b9b6ba103ec305f489645b5fee905d2)?

**Comment by liyuqian** [comment]
@franciscojma86 : correct (I copy/pasted the response for all those 3 issues :smile: )

**Comment by franciscojma86** [comment]
Sorry I missed it in https://github.com/flutter/flutter/issues/36079, but you didn't copy it on https://github.com/flutter/flutter/issues/37273 so wanted to double check :)

**Comment by liyuqian** [comment]
Ah, I wasn't aware of https://github.com/flutter/flutter/issues/37273. Now added the response there.

**Comment by franciscojma86** [comment]
Thanks!
