### ISSUE TITLE
Calls to `runChecked*` should catch the exceptions

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#35929]
The tool contains calls to `runChecked*` functions, which may throw exceptions when the process exits with a non-zero error code, that do not wrap the calls in `try {} catch {}`. It should to so, and take appropriate action when the spawned processes fail.

**Comment by zanderso** [comment]
For example, there are reports from analytics that https://github.com/flutter/flutter/blob/v1.7.8-hotfixes/packages/flutter_tools/lib/src/android/android_device.dart#L571 is resulting in unhandled exceptions from the tool. We should catch them and fail with a better error message so that users and/or us can better track down the issue.

**Comment by jonahwilliams** [comment]
At a high level, there are roughly 2 action items:

1. Standardize on a process for handling process exceptions

For example, whenever we invoke the processManager to call adb or gradle we need to provide additional context instead of a stackTrace, including:
   - The exact command executed.
   - The stderr from that command
   - Additional context, such as why that command was executed.

To facilitate the above, we should reduce the number of ways we have to invoke an external process. 
 This should be enough information that either the user knows what they should do to fix it, or if not they can file a highly detailed bug.

2. Longer term, we should provide more informative contextual messages for well known error cases, such as when gradle fails to download itself. This will, to some extent, require user reports from 1).

**Comment by blasten** [comment]
The action item from the meeting is to wait for the next dev release and look at the number of exceptions, which should have dropped.

**Comment by Hixie** [comment]
Any news now that we have had a dev release?

**Comment by blasten** [comment]
This is fixed!
