### ISSUE TITLE
About TextSelectionOverlay class

### ISSUE THREAD

**Issue by Rannie** [flutter/flutter#35962]
Can I use the TextSelectionOverlay class to implement a Text widget that can select text?
If so, is there any relevant documentation or samples? Thanks.

**Comment by dnfield** [comment]
This kind of question would be more appropriate for stackoverflow, or one of the other channels at https://flutter.dev/community

If you think there's a bug (for example, a bug in the documentation around TextSelectionOverlay not being clear), please feel free to re-open and clarify.  I'm going to close this for now since in it doesn't quite fit the issue tracker in its current form.
