### ISSUE TITLE
Image widget load images slowly

### ISSUE THREAD

**Issue by haianhsing** [flutter/flutter#35977]
## Details

I have a function in my app that take some photos and show. But it take me at leave 3 seconds to show that. How to load it quickly.Thanks.

## Logs

```
```

```
```

**Comment by dnfield** [comment]
This bug is not actionable in its current state. We need a reproducible case - ideally an image that loads slowly.

Is it loading slowly because it's just a very large image on an older device?  Or is it loading slowly because you have an encoder that's creating some pathological case for one of our decoders?  Or something else entirely?

If you're able to share an image that reproduces this, please feel free to ping this issue or file a new one.
