### ISSUE TITLE
How to add iOS multiple flavor app name for multiple language

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#35985]
How to add iOS multiple flavor app name for multiple language

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
