### ISSUE TITLE
RaisedButton colorBrightness property is not clearly defined

### ISSUE THREAD

**Issue by MonkeyInWind** [flutter/flutter#36055]
colorBrightness: Brightness.dark
![image](https://user-images.githubusercontent.com/34543887/61116665-77fc9580-a4c7-11e9-8594-e2837c950145.png)
------------------------------------------
colorBrightness: Brightness.light
![image](https://user-images.githubusercontent.com/34543887/61116770-b09c6f00-a4c7-11e9-874c-6689e8f54600.png)

version: Flutter 1.8.1-pre.71 • channel master

Is that the opposite?

**Comment by shihaohong** [comment]
It seems to look fine when the app itself has `Brightness` set to `Brightness.dark`. Did you have an expectation for how this should behave? I'm assuming your app's theme is `Brightness.light`, whereas your button is set to `Brightness.dark`.

<img width="398" alt="Screen Shot 2019-07-12 at 11 29 37 AM" src="https://user-images.githubusercontent.com/27032613/61150473-5932da80-a498-11e9-8db4-af19de0f9f60.png">

**Comment by shihaohong** [comment]
In any case, the docs for `RaisedButton.colorBrightness` are not particularly clear on how it affects the changes for the `RaisedButton`. I'm sure we can document that a little better.

**Comment by MonkeyInWind** [comment]
![image](https://user-images.githubusercontent.com/34543887/61196561-3441a000-a702-11e9-87fd-670b85b7a9b9.png)
When I set it to `dark`, It looks bright.
![image](https://user-images.githubusercontent.com/34543887/61196622-808ce000-a702-11e9-9bba-fb5e7225e458.png)
When I set it to `light`, It looks dark.
I'm not sure if I understand it wrong, but it seems to be the opposite.
If I'm wrong, please let me know.
Or maybe my usage is wrong.

**Comment by shihaohong** [comment]
@MonkeyInWind So, the brightness here refers to the app's setting for Brightness. Brightness.bright means that your app is in the default theme, whereas Brightness.dark assumes a dark theme app. Hence, the `RaisedButton` assumes a bright color in order to contrast with a supposed dark background. 

There's a much better description in the [Brightness documentation](https://api.flutter.dev/flutter/material/ThemeData/brightness.html), it might be good to link it to the RaisedButton.colorBrightness documentation to prevent this kind of confusion in the future.

**Comment by MonkeyInWind** [comment]
Thank you for your explanation. I thought it was setting the brightness of the button. It's because I don't read the document carefully enough, and there's something confusing about the document.

I hope the documentation can be more detailed, so that it can be better for beginners like me. Thank you very much.
