### ISSUE TITLE
Unexpected close during integration test

### ISSUE THREAD

**Issue by Leocardoso94** [flutter/flutter#36086]
After upgrade to v1.7.8+hotfix.3 my integrations tests are having unexpected behavior. After some steps, the app closes and the tests are failing.

## Steps to Reproduce

1. run `flutter drive --target=test_driver/app.dart --verbose`

## Logs

```
[+7782 ms] 00:21 +5 -1: Onboarding Self Invite logout [E]
[   +4 ms]   Failed assertion: boolean expression must not be null
[  +48 ms]   package:flutter_driver/src/driver/driver.dart 432:17  FlutterDriver._sendCommand
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/future_impl.dart 22:43                     _Completer.completeError
[        ]   dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
[        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
[        ]   dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
[        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
[        ]   package:flutter_driver/src/driver/driver.dart 459:11  FlutterDriver.tap
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
[        ]   dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
[        ]   package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
[        ]   package:test_api/src/backend/invoker.dart 250:15      Invoker.waitForOutstandingCallbacks.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
[        ]   dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
[        ]   dart:async/timer.dart 52:45                           new Timer
[        ]   dart:async/timer.dart 87:9                            Timer.run
[        ]   dart:async/future.dart 174:11                         new Future
[        ]   package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /home/leocardoso/flutter
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/leocardoso/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/leocardoso/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by Leocardoso94** [comment]
I'm notice after `get_health` command the response is 
` {type: Sentinel, kind: Collected, valueAsString: <collected>}`
and when this happens the app closes

https://github.com/flutter/flutter/blob/e91822da24c013aa6f21d03ed3af3587923d9fd2/packages/flutter_driver/lib/src/driver/driver.dart#L432

**Comment by jonahwilliams** [comment]
cc @liyuqian @rmacnak-google

**Comment by jiahaog** [comment]
I was looking into something similar

**Comment by jiahaog** [comment]
I was looking into something similar internally. It appears that this is a race condition when the driver tests on the host runs too fast before the Flutter application has started completely on the device.

### Workaround

Add a `await Future.delayed()` before the `FlutterDriver.connect()` in the tests, or to catch the exceptions and do exponential retries.

### Cause

The cause of these errors is that the `FlutterDriver.connect` function scopes future VM calls after the first `getVM()` call to the first `isolateId` that is returned.

https://github.com/flutter/flutter/blob/ef62092b9b8b1c92de9f16108814c0a3b34cb59d/packages/flutter_driver/lib/src/driver/vmservice_driver.dart#L99

On the application, there are two isolates (or more?) isolates in play. The first isolate for bootstrap on the device (not sure for what this is for yet) is transient and is ultimately garbage collected, and Flutter runs on another isolate.

If `FlutterDriver.connect` is called too early, the entirety of the connect method will be using the wrong `isolateId` which is collected. Both the "boolean expression must not be null" and unexpected sentinel errors occur because the RPC methods are scoped to a isolate which has been garbage collected while flutter runs on another new isolate.

### Fix

Discussed on discord - proper fix would be to filter all isolates of the dart vm and pick the correct one that Flutter is running on. We should be able to call the `_flutter.listViews` extension method to obtain the correct isolate id. This is how the Flutter Tools does it:

https://github.com/flutter/flutter/blob/ef62092b9b8b1c92de9f16108814c0a3b34cb59d/packages/flutter_tools/lib/src/vmservice.dart#L1083

The driver package is using the deprecated `package:vm_service_client`, we might want to migrate it to https://pub.dev/packages/vm_service as well.

Internal bug: 147455985

**Comment by jonsamwell** [comment]
Does this actually make the test fail or just print the error message

**Comment by jiahaog** [comment]
Sorry for not catching up earlier - this should have been fixed as part of https://github.com/flutter/flutter/issues/41029
