### ISSUE TITLE
https://13266488751883217300.googlegroups.com/attach/d6883328e4019/Screenshot_1562852907.png?part=0.1&view=1&vt=ANaJVrFF28DRL8JEf2xN_RkYbhavqtoX0NurL84OeWK_EV1NGALmFrdkVXh5q5Bk85CnSKQgCDhO7mpJ4OReSTBlf7mUnAnaUKCAI8G4GdwtvF5rF7EkYLM

### ISSUE THREAD

**Issue by manjesha12** [flutter/flutter#36162]
[

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by manjesha12** [comment]
i have been facing thiss issue long time can anyone know how to solve this,


thanks in advance

**Comment by manjesha12** [comment]
Expanded(
            child: ListView(
              children: _addEntry/*.reversed*/.map((data) {
                return Dismissible(
                  key:ObjectKey(data),
                  onDismissed:(direction){
                  setState(() {
                    _addEntry.removeAt(data);
                  });},
                  background: Container(color: Colors.blue),
                  child: ListTile(
                    title: Text(data),

                  ),
                );
              }).toList(),
            ),
          ),




// for thi code

**Comment by stuartmorgan** [comment]
There's not enough context in your code sample; it's not clear what the type of your entries collection is, what it contains, etc.

Closing since there's no indication here that there's a bug in Flutter, rather than your code. I would suggest a resource like StackOverflow that's intended for helping people with their code, rather than the Flutter issue tracker.
