### ISSUE TITLE
Deprecate and delete the location_background plugin

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#36299]
@bkonyi 
As discussed we do not intend to support this plugin.

We need to publish it once with a README explaining it, and then delete the plugin from the repo.

**Comment by amirh** [comment]
@bkonyi are you still planning to do this?

**Comment by sjmcdowall** [comment]
How do you plan to support the functionality if not the plugin?

**Comment by bkonyi** [comment]
@sjmcdowall this plugin wasn't made for production use and was used as an example of allowing for background execution of Dart code on iOS in Flutter. Since there wasn't any intention to add Android support to this example, we've decided to remove it from the Flutter plugin repository.

I'm fairly certain there's more fully featured plugins available on pub.dev which provide location functionality.

@collinjackson just confirming, but we've already removed this plugin from our repository right? I'm fairly certain we have but if not, feel free to reopen this issue.

**Comment by collinjackson** [comment]
Yes, the plugin was removed in https://github.com/flutter/plugins/pull/1902. Thanks.
