### ISSUE TITLE
Displaying text like '🔥'  causing significant memory growth

### ISSUE THREAD

**Issue by Qxyat** [flutter/flutter#36358]
## Details
I find that when displaying text like '🔥' ，the memory grows significantly.
![image](https://user-images.githubusercontent.com/11627283/61366907-17050100-a8bd-11e9-8c1e-f8d6658c0208.png)
(Device: iPhone XS MAX)
As shown in the figure：
1. Before displaying the '🔥',  the memory is 84MB
2. After displaying the '🔥', the memory is 149MB

How do we reduce memory usage in this scenario? Any suggestions?

Demo:  https://github.com/Qxyat/flutter_demo/tree/master/emoji_memory_demo

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.2)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Qxyat** [comment]
@xster Would you give me some advice?

**Comment by xster** [comment]
Perhaps @GaryQian might have some insights wrt emojis and libtxt

**Comment by GaryQian** [comment]
The memory usage is probably from loading the emoji font, which is essentially a collection of images representing all emojis. You can verify this by looking at memory before and after typing/using other emojis.

I don't know if there a way around this, since the whole font needs to be loaded for use to look up the correct emoji to draw. On the bright side, once any emoji is loaded, any additional emojis should not cause additional memory. The memory is a one-time overhead.

**Comment by VladyslavBondarenko** [comment]
Hi @Qxyat 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
