### ISSUE TITLE
Include Discrete Progress Reports in Terminal Operations

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#36364]
Hi guys, a big thank you to the Awesome brains behind Flutter. Keep up the good work.

However, I was thinking , would it be possible for the flutter team to include discrete progress reports during terminal operations.

For Example.`.Initializing Gradle.....10%..`  is better of than just` Initializing Gradle...` So that I know what's going on. I am saying this because I am currently stucked at` Initializing Gradle... `for the past 4hrs. I have no idea what is going on...

**Comment by zanderso** [comment]
It sounds like gradle wandered off into the weeds in this case. FYI @blasten. I'm reluctant to optimize for the case where operations take this long, since it likely indicates a bug somewhere. Instead, I think we should move toward having timeouts for child processes of the tool: https://github.com/flutter/flutter/issues/39141.
