### ISSUE TITLE
Implement message loop

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#36420]
The initial Win32 embedding (https://github.com/flutter/engine/pull/9835) doesn't yet use the new message loop implementation that was recently added to the GLFW embedding, and uses a call that blocks on Windows events. That means this will regress to the earlier Windows behavior of not noticing plugin events unless there's an active native event stream, as described [here](https://groups.google.com/d/msg/flutter-desktop-embedding-dev/otxOui9kZZs/tA9DQAbzBgAJ).

**Comment by clarkezone** [comment]
I have a change going to resolve this.

**Comment by stuartmorgan** [comment]
@clarkezone Could you describe the current state of your PR and the open questions that need to be resolved for it? We probably need to have @franciscojma86 take this over since I'm assuming you won't be able to get back to it in the near future.

**Comment by clarkezone** [comment]
I will try and get to it tomorrow evening.

**Comment by clarkezone** [comment]
The main open question with the PR is how best to expose the API.  Win32 apps typically own the main message loop rather than delegating it to a library.. this is the pattern that is now in use in the win32 engine / example.  The problem is, the busy wait implementation in this PR needs to take care of the GetMessage part on behalf of the app to avoid the app calling getmessage and starving plugins.  Approaches I considered for this:

1) Expose a GetMessageFlutter or similar API.. this would enable the task runner implementation to use messagewaitformultipleobjects and get woken up either by a timeout in the case that there is a task or by an incoming message.  If awoken by a window message, it would return that, else it would loop around and wait again.  I.e. a message would only be returned when one is present but internally other work can happen to service plugins.  The problem with this approach is that GetMessage is a flat API and a GetMessageFlutter style message would have to be exposed as an instance method on the API in order for the state to line up the way things are currently set up.  I didn’t think too deeply about this, if there is a way of exposing GetMessageFlutter as a flat API / without needing to refer to state (by making it global in some way) it would have been my preferred approach because it is a small change to an “ordinary” window message loop and cognitively strait forward.  It would still preclude some patterns where apps call peek message rather than getmessage.  That’s also something I didn’t think about / investigate.

2) Wrap the message loop as in the original GLFW implementation.  I don’t like this because it is what you’d want in the add to app scenario and it removes flexibility an app would otherwise enjoy by owning it’s own loop.  It also makes it harder to interoperate with other frameworks in a mix framework app.  It would be the easiest thing to do to unblock plugins but likely something to revisit if this is the chosen approach.

3) I had a third approach but it is currently escaping my memory unfortunately.

**Comment by stuartmorgan** [comment]
If I'm understanding option 1 correctly, it wouldn't work for more than one engine instance running at the same time, which is something that ideally we should support.

Maybe we could just expose a sort of `DoFlutterWork` method that processes the internal task queue, then returns the wait time it currently needs. If there are multiple engines, the app-level loop could just use the minimum of the returned values.

I'll experiment with that a bit and see if I can get something working.

**Comment by stuartmorgan** [comment]
Status update: I have a working implementation using the above (branched from the initial PR). I'm doing some refactoring to make it part of the engine rather than the window; once I get a chance to finish that I'll post for review.

**Comment by clarkezone** [comment]
Sounds good.  From memory I was able to avoid waking up in the situation where there are no User32 messages pending and no task queue tasks scheduled unlike in the GLFW impl which work up regardless causing CPU overhead.. where u able to retain that aspect?

**Comment by stuartmorgan** [comment]
Yes, it still uses the core of your approach, just with enough exposed to hoist the runloop itself up a level. Very low steady-state CPU, but engine events (e.g., method channel messages) are no longer gated on the arrival of a native event.
