### ISSUE TITLE
call a Flutter method while the app is in foreground service and is close

### ISSUE THREAD

**Issue by saeiddjawadi** [flutter/flutter#36633]
Hello,

I asked this question on stackoverflow and nobody answer it.
https://stackoverflow.com/questions/57123509/is-there-a-way-call-flutter-method-when-foreground-service-is-running-and-app-is

I wrote an app that listens to SMS while it is in foreground service with broadcast receiver.
I want to know that is there a solution to call dart method from native while the app is closed while the foreground service is running?

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
