### ISSUE TITLE
Downloaded executables cannot execute on host.

### ISSUE THREAD

**Issue by 1048300461** [flutter/flutter#36636]
I use centos7 to install flutter sdk.
But when I run flutter doctor,
it shows that 
![image](https://user-images.githubusercontent.com/43379773/61591958-51450a00-abff-11e9-99a2-abce4ff022c3.png)
what shall I do? I search it on the Internet, but I can't find the solution

**Comment by timsneath** [comment]
That's really a question for a CentOS expert, rather than for Flutter, since every Linux distro has its own way of installing support for 32-bit packages. Here's a (dated) forum article I found based off a quick search: https://www.centos.org/forums/viewtopic.php?t=2265. Don't know whether this is still accurate or not.
