### ISSUE TITLE
error: A value of type 'Null Function(FirebaseUser)' can't be assigned to a variable of type 'void Function(AuthCredential)'.

### ISSUE THREAD

**Issue by Developer-Anjan** [flutter/flutter#36644]
For the following code the error is showing.

```
final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user){
      print('verified';)
    };
```

**Comment by Ramesh21** [comment]
Even i was facing same issue and fix it. change your code like below and it will work.

final PhoneVerificationCompleted verifiedSuccess = (AuthCredential phoneAuthCredential) {
       print('verified');
    };

**Comment by manney12** [comment]
It worked for me but i am wondering why does that work ? is it due to the calling of a instance of another package or  what ?

**Comment by BondarenkoStas** [comment]
@Ramesh21 thank you! @Developer-Anjan Is the issue still relevant?

**Comment by iapicca** [comment]
Hi @Developer-Anjan 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
