### ISSUE TITLE
Encode Kannada translations to safeguard Emacs

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#36704]
Flutter localizations for the Kannada ('kn') locale exist. They've been temporarily removed (https://github.com/flutter/flutter/pull/36589) because viewing them with Emacs on Linux can crash the GUI version of the editor. The files contain characters that will cause a SEGV because of a bug in OpenType Font (libotf) library.

More information here: http://emacs.1067599.n8.nabble.com/bug-30193-The-deadliest-file-in-Emacs-history-td447264.html.

The problem can be worked around by configuring emacs with:
```
(push "Noto Serif Kannada" face-ignored-fonts)
```

Need to find a way to include these files that will not put emacs developers at risk.

[packages/flutter_localizations/lib/src/l10n/cupertino_kn.arb](https://github.com/flutter/flutter/files/3418938/cupertino_kn.txt)
[packages/flutter_localizations/lib/src/l10n/material_kn.arb](https://github.com/flutter/flutter/files/3418942/material_kn.txt)

**Comment by timsneath** [comment]
Forgive me for butting in, but I'm a little surprised that we've removed language support to save developers working around a bug... 

I think we can live with its removal for a couple of weeks, but I'd be concerned if we shipped the next stable release without Kannada support, since I believe we have a number of released apps in the store that depend on this language. 

I know you've only had the bug for two hours, Shihao -- but when you've had the chance to investigate, can you let me know if there's a risk that a fix won't be checked in by mid-August (the cut-off point for the 1.9 stable release)? Then I'd want to do some research to figure out the customer impact...

Thanks :)

**Comment by shihaohong** [comment]
@timsneath Of course! I'll let you know my findings as soon once I dig into this next week

**Comment by HansMuller** [comment]
@timsneath The fix  has been waiting to land since Friday: https://github.com/flutter/flutter/pull/37026. We're just (still) waiting for our infrastructure to finish.

**Comment by timsneath** [comment]
Oh that's great! Thanks.
