### ISSUE TITLE
Allow MaterialStateProperty<Color> for ToggleButtons

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#36861]
This allows for an alternative approach to selecting the colors in ToggleButtons.

Changes involve: 
1. Keeping track of a Set<MaterialState> _states inside of _ToggleButton.
2. Calling MaterialStateProperty.resolveAs<Color>(color, _states); in the build method of _ToggleButton.
3. Specifying in the documentation here that if color is a MaterialStateProperty<Color>, selectedColor, and disabledColor will be ignored.

**Comment by shihaohong** [comment]
Removing assignment since I haven't had time to come back to this

**Comment by craiglabenz** [comment]
Do we want to have widgets with mixed styling rules? For example, right now, `TextButton` is entirely styled by its single `ButtonStyle` attribute, whereas `ToggleButton` still uses the old pattern and accepts each of its styling attributes as individual parameters.

We could modify ToggleButton to accept a dynamic color resolver, but is that worth doing when compared against migration to the full `ButtonStyle` pattern?

**Comment by HansMuller** [comment]
[SegmentedButton](https://api.flutter.dev/flutter/material/SegmentedButton-class.html), which is now recommended instead of ToggleButtons can be configured with a [ButtonStyle](https://api.flutter.dev/flutter/material/ButtonStyle-class.html).  All of the `ButtonStyle` color properties are `MaterialStateProperty<Color?>`.
