### ISSUE TITLE
sharing file support for share plugin

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#36894]
https://github.com/flutter/plugins/pull/970 adds sharing file support (android & ios)

The PR has a lot of thumbs up in the flutter/plugins repo but would be good to include an integration test for when we have that capability. Creating this issue so it can be prioritized.

**Comment by AriCohen8** [comment]
Please can this be done. The longer it takes to do the merge, the more work will need to be done to make it compatible given ecosystem changes. Looks like the original work was finished 8 months ago.

**Comment by allanwolski** [comment]
I also think this needs more attention.

**Comment by artob** [comment]
Bump. This is essential baseline functionality.

**Comment by bulwinkel** [comment]
Bump

**Comment by joemclean** [comment]
Also bumping! We could really use this; curious if we can help.

**Comment by JonasVautherin** [comment]
Kindly pinging here to mention that there has been recent activity in https://github.com/flutter/plugins/pull/970 that would probably require attention :innocent:.

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/9817

**Comment by maheshkumar2150** [comment]
If we have to write platform specific code for everything except the design, then flutter is no good use for me. Sharing file is an important feature :-(

Actually i am learning Udacity Android Course. 
It seems easier to learn android.
I don't know how to take flutter. Though flutter is super fast to create ios and android, it needs time to grow. React Native has all the important plugins :-:

**Comment by JonasVautherin** [comment]
@maheshkumar2150: Have you tried flutter/plugins#970? It seems like it works reasonably well for multiple people. It may not get much attention and it may never get merged, but that does not mean you cannot use it in your project.

**Comment by maheshkumar2150** [comment]
> @maheshkumar2150: Have you tried [flutter/plugins#970](https://github.com/flutter/plugins/pull/970)? It seems like it works reasonably well for multiple people. It may not get much attention and it may never get merged, but that does not mean you cannot use it in your project.

My mistake. I did not see that plugin. It seems promising. Thanks for the help.

**Comment by JonasVautherin** [comment]
@collinjackson: Looking at [pub.dev](https://pub.dev/packages?q=share) and the 1000+ results when I search for "share", it seems to me that if would be more efficient if people contributed to an official package instead of publishing their own. However, from what I can see with e.g. flutter/plugins#970, it seems like it has been mostly ignored by the flutter team in the last year and a half.

9 months ago, you mentioned adding integration tests. It doesn't seem like this will ever be done by the flutter team, so my question is the following: is there a way for the community to create those integration tests, or should the author of flutter/plugins#970 give up on contributing to `flutter/plugins` and instead publish his own package as a third party?

**Comment by ditman** [comment]
`share: ^0.6.5` has been tagged and [published](https://pub.dev/packages/share/changelog#065).
