### ISSUE TITLE
Regression in complex_layout_scroll_perf_memory_diff_median

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37176]
Looks like it began with https://github.com/flutter/flutter/commit/9b150f134b9b6ba103ec305f489645b5fee905d2.

**Comment by franciscojma86** [comment]
Also affects flutter_gallery__image_cache_memory diff_median

**Comment by Hixie** [comment]
cc @gaaclarke can we revert?

**Comment by Hixie** [comment]
cc @liyuqian maybe you can revert if @gaaclarke is not around?

**Comment by liyuqian** [comment]
This should be an improvement instead of a regression: both the start memory and the end memory drops after that PR.  The start memory drops more significantly so the diff (end memory - start memory) increases. Presumably, less start memory leaves GC more room to retain more objects so the diff increases. But since the overall memory strictly decreases, this has no negative effect for any users.

I think we should:
1. Rebaseline the diff memory
2. Ensure that the GC is called right before measuring the start and end memory for diff computation (https://github.com/flutter/flutter/issues/37318).

**Comment by liyuqian** [comment]
Rebaselined.
