### ISSUE TITLE
Changing the default behavior of `flutter precache`

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#37184]
Currently the behavior of flutter precache is:

1. Always precache Android and iOS artifacts (if on macOS).
2. Optionally precache additional platform artifacts if specified via flags, like `--web` or `--macos`.
3. Disable precache of artifacts if provided a `--no-platform`.

I would like to adjust the precache behavior so that it is:

1. Always precache Android and iOS artifacts (if on macOS) _if no other platform flags were passed_
2. If at least one platform flag is passed, only precache the provided flags.
3. Disable precache of artifacts if provided a `--no-platform`.

@zanderso @DanTup @devoncarew @csells

**Comment by zanderso** [comment]
sgtm

**Comment by stuartmorgan** [comment]
> 1. Always precache Android and iOS artifacts (if on macOS) if no other platform flags were passed

If we're going to keep a no-flags version of `precache`, is there a reason not to have it download all enabled platforms that are relevant to your host? It seems like preserving the conceptual meaning ("Just give me all the things that I might need") rather than exact current behavior ("Give me all the things that happened to be stable when the command was created") is going to be a much better match for the likely user model for what the command does.

**Comment by jonahwilliams** [comment]
I would prefer only having a flags version. I'm concerned about precache downloading way more than a user will need (eventually). Especially in terms of larger artifacts like the flutter_runner and fuchsia SDK.

But precache is currently used by the IDE tools and the google3 roller and I don't want to break them in the meantime. 

I would also consider deprecating and removing the old behavior gradually. But, I'm not too set on that.

**Comment by stuartmorgan** [comment]
> But precache is currently used by the IDE tools and the google3 roller and I don't want to break them in the meantime.

But those could easily be changed to pass flags, so that adjusting the behavior of the non-flag version later wouldn't be a problem.

> I would also consider deprecating and removing the old behavior gradually.

That sounds fine too. I just think we should have a plan of record that isn't to indefinitely leave a default behavior that is going to become increasingly confusing for users (exhibit a: Greg's bug above).

**Comment by devoncarew** [comment]
> But precache is currently used by the IDE tools and the google3 roller and I don't want to break them in the meantime.

For IntelliJ at least, we're just using `flutter precache` after the initial sdk installation to ensure that the time to run `flutter create` is short and relatively predictable.

**Comment by DanTup** [comment]
And FWIW, in VS Code we never use `precache` (I didn't really know about it until now :-))

**Comment by stuartmorgan** [comment]
> For IntelliJ at least, we're just using flutter precache after the initial sdk installation to ensure that the time to run flutter create is short and relatively predictable.

This seems like an argument for it including all stable platforms for as long as it exists. Presumably when desktop is stable, we don't want `flutter create` to be fast and predictable for mobile and randomly slow for desktop

**Comment by jonahwilliams** [comment]
If we're moving towards a workflow that starts with zero platforms by default, it might be odd to spend time downloading artifacts a user is not particularly interested in.

**Comment by devoncarew** [comment]
Does `flutter create` really require any engine artifacts to be present?

**Comment by jonahwilliams** [comment]
No. We may need to download the "universal" artifacts shortly after though. For example, to identify that an iOS device is attached we need the libimobile device and friends

**Comment by devoncarew** [comment]
Gotcha, `create` wouldn't need the artifacts, but something the user might run soon after - like `doctor` - would.

**Comment by jmagman** [comment]
In https://github.com/flutter/flutter/issues/71954 @timsneath proposed:
> We should simplify the options from the current set of eight choices to two general usage patterns:
>  - No flags set: cache artifacts for platforms that are enabled in `flutter config`
>  - `--all-platform` flag: cache artifacts for all platforms

**Comment by timsneath** [comment]
The usage pattern that I hear is that customers want to download everything they need while they have good connectivity, so that when they go offline or onto a metered connection they're not surprised by a missing dependency. That was what drove my recommendation above. I was surprised to discover that today's `flutter precache` doesn't download dependencies for the platforms that are enabled.

**Comment by jonahwilliams** [comment]
I believe the original issue here pre-dates our decision to make flutter config/features tied to platform support. With that decision made, I see no reason to remove/deprecate the platform flags and make it driven entirely by config like @timsneath suggestions.

**Comment by zanderso** [comment]
> I see no reason to remove/deprecate the platform flags and make it driven entirely by config like @timsneath suggestions.

I agree the platform flags for `precache` are useful either way. Also removing them would be a breaking change. It sounds like @timsneath is suggesting that we could remove some confusion by changing the logic [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/precache.dart#L150) to be (`isEnabled(feature) || boolArg(featureFlag))` instead of `&&`. Would that be a problem?

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/73733
