### ISSUE TITLE
iOS app lifecycle and FlutterViewController lifecycle are ambiguously merged

### ISSUE THREAD

**Issue by loongliu** [flutter/flutter#37226]
In `FlutterViewController.mm`, Flutter's lifecycle is binding with FlutterViewController' and `UIApplication` at the same time. This may be not correct when use flutter with `add2app`.

When FlutterViewController is covered by other native ViewController, Flutter's lifecycle is paused. Now when application resign active and become active again. FlutterViewController is not visible but Flutter's lifecycle is resume due to UIApplication notification.

This [pr](https://github.com/flutter/engine/pull/10253) fixes problem.

This problem is critical when some logic needs to be executed when flutter becomes resumed.
What's more, if one needs to show keyboard when flutter becomes resumed, the keyboard will be shown on the native UIViewController.

**Comment by loongliu** [comment]
@dnfield Would you like to check this?

**Comment by blasten** [comment]
cc @xster @jmagman

**Comment by xster** [comment]
Thanks for pointing this out. I edited the bug title. Hopefully this still adequately describes your issue. 

This is indeed an issue as you pointed out. Though rather than removing the app lifecycle events from Dart knowledge, I think the best way to accommodate both full Flutter apps and add-to-app cases is to let the 'foreground' definition be the intersection of FlutterViewController and the app being in the foreground.

**Comment by loongliu** [comment]
When FlutterViewController is active, the application is just active, so the intersection of lifecycle of FlutterViewController and the app is just lifecycle of FlutterViewController.
If flutter only provides lifecycles for resumed and paused, FlutterViewController lifecycle is enough. Just like Android, flutter's lifecycle is bind with Surface's lifecycle, which is nearly same with FlutterView's lifecycle. It does not matter with application's lifecycle.

Actually, Flutter may need the application lifecycle state to distinguish situations that FlutterViewController navigates to other FlutterViewController or application becomes inactive. So developer can do some business logic in flutter when application become inactive. In both situations, flutter's lifecycle changed from resumed to paused. I implemented an `ApplicationLifeCycleNotifier` to handle these situations. It is nice for flutter to provides these application lifecycle state. Should this be a pull request?

**Comment by xster** [comment]
I added some tests but it turns out this was already fixed. We're not coupling in the application lifecycles to the AppLifecycle events anymore through the WidgetsBindingObservers. This makes the behavior match Android's which is desired. I'll close this issue.

**Comment by xster** [comment]
Actually, sorry, I didn't run the tests right. This is indeed a problem in production https://github.com/flutter/engine/blob/a4de006f2139ab982888ce2e6054c1e73ddad47d/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L175. As mentioned above, conflating the 2 is a problem. 

I would just disconnect the AppLifecycle enums from the application lifecycle since it's a strict superset of the view controller's lifecycle. 

> Actually, Flutter may need the application lifecycle state to distinguish situations that FlutterViewController navigates to other FlutterViewController or application becomes inactive. So developer can do some business logic in flutter when application become inactive. 

Can you elaborate on a concrete scenario? (where you would use it in the Dart code rather than in a plugin where all of this is accessible via the FlutterPluginAppLifeCycleDelegate)

Either way, if that does become something we'll want to do, it'll not be into an existing enum value so the first step would be removing the application lifecycle from the existing enums.

**Comment by loongliu** [comment]
For some apps with private personal information, such as bank app. It is desired to re-input password, assume in flutter page, when app re-becomes active.

So it is needed to distinguish the two events that app re-becomes active and app navigates from native page back to flutter page.

**Comment by xster** [comment]
If you just meant while the view controller is still displaying and trimming out the application events while the view controller is not displaying then I agree.
