### ISSUE TITLE
Regressions on flutter_gallery__image_cache_memory diff_median

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#37273]
Regressions on flutter_gallery__image_cache_memory diff_median started on [9b150f134b9b6ba103ec305f489645b5fee905d2](https://github.com/flutter/flutter/commit/9b150f134b9b6ba103ec305f489645b5fee905d2)

**Comment by liyuqian** [comment]
This should be an improvement instead of a regression: both the start memory and the end memory drops after that PR.  The start memory drops more significantly so the diff (end memory - start memory) increases. Presumably, less start memory leaves GC more room to retain more objects so the diff increases. But since the overall memory strictly decreases, this has no negative effect for any users.

I think we should:
1. Rebaseline the diff memory
2. Ensure that the GC is called right before measuring the start and end memory for diff computation (https://github.com/flutter/flutter/issues/37318).

**Comment by liyuqian** [comment]
Ignore my comment in https://github.com/flutter/flutter/issues/37273#issuecomment-516958708 since this regression happened much earlier: https://github.com/flutter/flutter/commit/b69feb5340f3b50864fae8786b5176ae1dd06bdd

We'll need to bisect the engine roll to figure out why.

CC @chinmaygarde @jason-simmons to see if this regression was expected.

**Comment by jason-simmons** [comment]
This is a result of the image decoder redesign in https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc.

The image_cache_memory benchmark is sensitive to the timing of when images are decoded.

**Comment by franciscojma86** [comment]
Should this be rebaselined?

**Comment by franciscojma86** [comment]
Discussed offline with @jason-simmons, he did an auto rebase of image_cache diff-median and start-min. Will remove TODAY label and keep monitoring.

**Comment by franciscojma86** [comment]
Closing since it has been looking good in the last couple of days
