### ISSUE TITLE
Flutter's local `.pub-cache` doesn't interact well with separate Dart install

### ISSUE THREAD

**Issue by vsmenon** [flutter/flutter#37481]
When a developer has separate installs of the Flutter and Dart SDKs, our tools are confused by Flutter's separate `.pub-cache`.  This can lead to inscrutable errors.  E.g.,:

https://github.com/flutter/flutter/issues/36933

**Comment by gspencergoog** [comment]
Just to explain why why we have the cache:

The pre-populated cache serves several purposes:

1. people can just run "flutter run" and it will work right out of the box, with no extra downloading.
2. People who download flutter when they have a fast connection, but try to use it the first time without a connection, or with a slow one, aren't disappointed (the airport problem), and
3. People in other parts of the world without access to the pub server (i.e. China) can download our package and use it instead of being stopped by not being able to access the server.

Ideally, we'd do some magic behind the scenes to merge that cache with the user's cache on first run or something.  Even more ideally, we'd have a "real" installer, and be able to just install stuff into the user's cache in the first place.

Another option would be to have pub look in multiple caches (via some sort of PUB_CACHE_PATH var or something), and then we could set it in the flutter tool to look in the user's cache first and the pre-populated one second.

**Comment by Hixie** [comment]
How does pub determine which cache to use?

**Comment by gspencergoog** [comment]
Via the `PUB_CACHE` environment variable.  We set that inside of the flutter tool if we notice that the flutter directory has a `.pub-cache`.

The workaround for this issue is to have people delete the flutter directory's `.pub-cache` and just use theirs.
