### ISSUE TITLE
Question about State class

### ISSUE THREAD

**Issue by jkmpariab** [flutter/flutter#37486]
It may be a newbie question. what's the point of disposing in State.dispose() while dart already have gc to do the work?

**Comment by Lucas0Braz** [comment]
It depends of your application, you can use that feature for something, like for example close or dispose an StateFulWidget, im not 100% sure, but that is it

**Comment by mohitjadav** [comment]
this method called  when this State object will never build again. After the framework calls dispose, the State object is considered unmounted and the mounted property is false.
For Better understating this you should try an tab view  Because i got an batter idea about state with Tab View Controller Hope its can work with you
