### ISSUE TITLE
flutter web - Pub get Issue

### ISSUE THREAD

**Issue by kavin014** [flutter/flutter#37511]
I am getting this warning as output,

```
Warning: You are using these overridden dependencies:
! flutter_web 0.0.0 from git https://github.com/flutter/flutter_web at 1c1f2d in packages/flutter_web
! flutter_web_ui 0.0.0 from git https://github.com/flutter/flutter_web at 1c1f2d in packages/flutter_web_ui
```

And I couldnt see the anything in browser when I run 

> webdev serve

How could I fix this?

**Comment by ja2375** [comment]
I personally think that message should say INFO instead of warning. Because warning sometimes scares users. And that message is just there to inform, not to scare anyone... :P

Are you opening http://127.0.0.1:8080 or whatever address the webdev serve command tells you to open?
Can you post the entire command output please?
Did this commando work for you anytime? Or is this the first time you are running it?

**Comment by jld3103** [comment]
That is not a problem. Pub always prints such a message when you override dependencies.

**Comment by BondarenkoStas** [comment]
Closing as it's not a flutter issue.
