### ISSUE TITLE
Creating columns/rows/flex with padding is noisy

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3753]
I often find myself wrapping Column, Row, and Flex in padding.

```
new Padding(
  padding: const EdgeInsets.all(15.0),
  child: new Column(
    children: [
      new Item(),
      new Item()
    ]
  )
)
```

I would love it if these widgets all learned the padding property. The extra nesting, indentation, and noise from constantly wrapping things in padding reduces the delight of using flutter.

```
new Column(
  padding: const EdgeInsets.all(15.0),
  children: [
    new Item(),
    new Item()
  ]
)
```

**Comment by Hixie** [comment]
You could create your own PaddedColumn widget that takes the arguments of Padding and Column and combines them into a Padding and a Column. This is more or less what Container does with ConstrainedBox, Padding, DecoratedBox, and Transform. I'd be wary of adding padding knowledge to RenderFlex itself, because that class is already one of our most complicated classes.

**Comment by drewwarren** [comment]
I agree it would be trivial to write my own Padded{Row,Column,Flex} widgets. It still feels like something that should be part of the default widget library.

The only similar framework I have used in the past supported this:
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/containers/HBox.html

Doing a quick look most other frameworks have this built in:
- http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Flayout%2FRowLayout.html
- https://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/HBox.html

**Comment by Hixie** [comment]
We could add it to Column by making Column into a component that has both a Padding and a Flex, instead of the current setup of having it just extend Flex. That would avoid making RenderFlex more complicated.

As a general philosophy, we expect to be different from other frameworks on issues like this because we've taken the approach of having many dedicated trivially simple widgets rather than few complicated widgets. The latter approach is used by most frameworks. The Web, in particular, takes the latter approach to an extreme, where `<div>` supports almost all the layout algorithms itself. Once you add padding, the next question is why not add decoration? Then when you have decorations, Why not add margins? Then why not add knowledge of clipping, or the ability to have some children take part in the flex and others be just stacked on top?

There's a slippery slope here which we're very wary about going down.

But that doesn't mean we shouldn't consider this specific request. We have some precedent, like the Container example I mentioned before.

**Comment by Hixie** [comment]
I'm going to WONTFIX this. We are happy with our composition approach and in practice this hasn't been a particularly notable pain point.
