### ISSUE TITLE
Text selection handles display outside when toggle obscureText value in TextField

### ISSUE THREAD

**Issue by basketball-ico** [flutter/flutter#37548]
You can reproduce this bug when run  in the galley app app.https://github.com/flutter/flutter/blob/3928f30ce996bb9fc832876f8b15ee08f860c3ae/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart#L74

1. Type text with "big" width like `wwwwwwww`
2. Press the eye icon multiple times to toggle `obscureText` value

3. the selection handle is wrong

This is a flutter bug?
Can I make something in my code to solve this? I try with `textEditingController` but not works.
Thanks.

![Screenshot_2019-08-03-05-40-44-834_io flutter demo gallery](https://user-images.githubusercontent.com/48268866/62410934-8e6fab80-b5b2-11e9-8f98-1e0b1aa2faa8.png)

![Screenshot_2019-08-03-05-40-36-956_io flutter demo gallery](https://user-images.githubusercontent.com/48268866/62410937-90d20580-b5b2-11e9-9346-64fc4d072d2d.png)

**Comment by justinmc** [comment]
I tried this and it seems fixed to me in master.  I believe it was fixed in https://github.com/flutter/flutter/pull/34665, which would mean that version 1.8.3 and above should have it.  Make sure you're using the right [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get the latest version of Flutter.
