### ISSUE TITLE
my app crashing  at starting when I use latest firebase_admob plugin but working fine with older plugin

### ISSUE THREAD

**Issue by pktintali** [flutter/flutter#37551]

**Comment by pktintali** [comment]
![flutter_doctor](https://user-images.githubusercontent.com/47480465/62413590-3a0a1180-b62e-11e9-8793-4e73cceac2d2.JPG)

**Comment by kangwang1988** [comment]
@pktintali 
The crash log when running with the latest version might help.

**Comment by BondarenkoStas** [comment]
@pktintali Can you provide you crash log? Also please provide your ```flutter doctor -v``` output.

**Comment by iapicca** [comment]
Hi @pktintali 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
