### ISSUE TITLE
Why are most Flutter tutorials on Youtube UI design and not the real project?

### ISSUE THREAD

**Issue by michaelodafe** [flutter/flutter#37552]
Here are a few tutorials
https://www.youtube.com/watch?v=2E-n0WWooGs
https://www.youtube.com/watch?v=80vWzQB0Eto
https://www.youtube.com/watch?v=OLmE2Pu-coU
https://www.youtube.com/watch?v=w45GyPYTEU0
https://www.youtube.com/watch?v=wWH66F9y63U&t=719s
https://www.youtube.com/watch?v=lxOekPQPyy0

**Comment by moseskarunia** [comment]
This has nothing to do with this repo. But since you might be a beginner, so i'll try to help you:

1. Setting up a real project is time consuming and beginners won't easily understand the complexity. Not beginner-friendly.
2. If you really want a full project course on flutter, check PAID online courses. On udemy for example, or maybe there's one on udacity as well.
3. Youtube content creators have no obligations to create any video. :)

Good luck on your learning journey!

**Comment by michaelodafe** [comment]
> This has nothing to do with this repo. But since you might be a beginner, so i'll try to help you:
> 
> 1. Setting up a real project is time consuming and beginners won't easily understand the complexity. Not beginner-friendly.
> 2. If you really want a full project course on flutter, check PAID online courses. On udemy for example, or maybe there's one on udacity as well.
> 3. Youtube content creators have no obligations to create any kind of videos. :)
> 
> Good luck on your learning journey!

Thank you very much, I'd check Udemy or Udacity

**Comment by stuartmorgan** [comment]
Closing; independent YouTube videos about Flutter aren't part of the project.
