### ISSUE TITLE
Provide an option to make the GFLW window on Linux not resizeable

### ISSUE THREAD

**Issue by skycomposter** [flutter/flutter#37623]
## Use case

For applications that require a fixed size and can't handle resizing gracefully.

## Proposal

This is a simple one line change before the window is created:
`glfwWindowHint(GLFW_RESIZEABLE, GFLW_FALSE)`

What I'm not sure about is the proper API to actually pass in the boolean to the flutter_window_controller and pipe it down to flutter_glfw.

**Comment by stuartmorgan** [comment]
I think window creation details should just be added as arguments to `FlutterDesktopCreateWindow`. In the interests of future-proofing this a little bit, rather than adding a boolean argument let's add a struct of window properties. That will make adding other properties in the future trivial (and not cause breaking changes for clients that don't care about them).

We can move initial width, height, and title into that struct as well to make the API more consistent.
