### ISSUE TITLE
Determining which widgets to wrap in padding to acheive margins seems arbitrary

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3764]
Let's say I want to have an icon and some text with 5.0 spacing between them.

```
new Row(
  children: [
    new Icon(...),
    new Padding(
      padding: const EdgeInsets.only(left: 5.0),
      child: new Text("Hello")
    )
  ]
)
```

Easy enough to achieve, but why did I wrap the Text in the padding? I could have just as easily wrapped the Icon in a padding right of 5.0. It feels very unnatural to me coming from a web development background to do this. I guess if it was HTML I would make a similar arbitrary choice in the CSS on which element to apply margin to, but at least that was abstracted away from my markup. Without having this abstraction layer I feel like I want a HorizontalSpacing(5.0) widget to put between the elements. I could easily write that widget (or use a Container) but I prefer using paradigms that are built into the framework. In fact before I learned about the Padding widget I was using an empty Container(width: 5.0) to achieve this spacing.

**Comment by Hixie** [comment]
I would have used a `Container(width: 5.0)`. That's just as built into the framework as Padding. There's nothing special about Padding -- it's just another widget.

You could also use `Padding(padding: const EdgeInsets.symmetric(horizontal: 2.5))` (with no child).

By the way, you can also use Container instead of Padding. Container has a `padding` argument. (Container is just a convenient wrapper around a bunch of our most basic widgets to make it easier to combine them.)

This comment probably didn't help. :-)

**Comment by drewwarren** [comment]
This is more about finding a semantic solution. When I see container I expect children. I know it works fine without them, but it doesn't read naturally to me using an empty container as a margin. I guess after a while maybe it would grow on me? :D  I also don't remember seeing an empty container used this way in any examples so I assumed the current practice to use a Padding wrapper.

**Comment by abarth** [comment]
> This is more about finding a semantic solution.

Row, Icon, and Text are all pretty visual widgets.  If you have more semantic widgets, sometimes it the best way of handling the spacing becomes clearer.  For example, http://docs.flutter.io/flutter/material/PopupMenuDivider-class.html makes sense for popup menus because the menus conceptually have dividers.  For buttons in material design, http://docs.flutter.io/flutter/material/ButtonBar-class.html takes the opposite approach and wraps the buttons in Padding widgets because the space between the buttons doesn't have a semantic meaning in the same way a divider in a menu does.

The basic widgets (e.g., Text, Padding, Row, etc) don't offer a strong opinion on this topic to allow more flexibility for the higher-level, more semantic widgets.

**Comment by Hixie** [comment]
Yeah maybe the solution here is to make a widget around the whole Row that fills in the right icon and text based on its configuration. That's what DrawerItem does, IIRC.

**Comment by eseidelGoogle** [comment]
Is there more to resolve here?  Docs perhaps?

**Comment by drewwarren** [comment]
I'd still love a best practice around this. I think the one I will advocate on our project is using a custom 'VerticalSpace' and 'HorizontalSpace' widget.

For example, look at fitness_demo.dart. The 'JUMPING JACKS' title was wrapped in a top padding of 20. This very well could have been a bottom margin on the container holding the sprite. Another option would have been to wrap the container holding the sprite with a bottom padding of 20. I will advocate instead for adding a const VerticalSpace(20.0) between the flexible holding the sprite and the title -- wrapping nothing in padding.

**Comment by Hixie** [comment]
@eseidelGoogle All of drew's bugs will at a minimum warrant doc improvements.

**Comment by Hixie** [comment]
Since this bug was filed we added a ListItem class that does this pattern, and have pointed to it all over the place. As far as what exact pattern to recommend, all the ones discussed above are equally valid. I don't know what we could say in the docs to resolve this. I'm going to close this bug on the basis that it's not sufficiently actionable. I expect we'll answer the philosophical points here in some of our upcoming layout docs.

**Comment by patelkrunal78** [comment]
Exactly Similar To [Flutter Layout Container Margin](https://icetutor.com/question/flutter-layout-container-margin)
