### ISSUE TITLE
error flutter firestore 0.12.9

### ISSUE THREAD

**Issue by orgio** [flutter/flutter#37657]
![error](https://user-images.githubusercontent.com/27058809/62508017-c1c36c00-b838-11e9-86d3-ea8a5ba1e7c5.PNG)

**Comment by atos93** [comment]
Just switch to AndroidX -> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by orgio** [comment]
Thank you so much for sending email to me And i used androidx but does not help maybe i missed something

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 6, 2019 at 5:29 PM, Emanuele Deriu<notifications@github.com> wrote:   
Just switch to AndroidX -> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by iapicca** [comment]
Hi @orgio 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
