### ISSUE TITLE
Firestore.instance.runTransaction((transaction) async doesn't work what should i do :(

### ISSUE THREAD

**Issue by melianawinata** [flutter/flutter#37662]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by melianawinata** [comment]
Trying to implement from this tutorial : https://codelabs.developers.google.com/codelabs/flutter-firebase

**Comment by melianawinata** [comment]
stuck at step 11 ..

**Comment by dnfield** [comment]
This would be a better question for StackOverflow or one of the chat channels listed at https://flutter.dev/community.  

Since this is not a feature request or bug report, I'm going to close this issue.  If you think that's in error, please feel free to re-open - for example, if there is documentation that is incorrect.
