### ISSUE TITLE
Implement full key event support for Windows

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#37710]
Once the Win32 embedding lands, we'll want to generate a full Windows key mapping and send Windows-specific data over the key event channel (rather than Android, as is currently done, or Linux, as the GLFW embedding will currently do).

**Comment by stuartmorgan** [comment]
@franciscojma86 I'm going to assign this to you since you're our expert on the framework's desktop key event handling, and were interested in some starter Windows issues.

**Comment by canewsin** [comment]
i thought this is working now, don't remember via plugin may be !

**Comment by stuartmorgan** [comment]
> i thought this is working now

It is not: https://github.com/flutter/engine/blob/master/shell/platform/windows/key_event_handler.cc#L47

**Comment by stuartmorgan** [comment]
@franciscojma86 What's the status of the previous work you had for this? I just tested this, and sending Android key data as we are now is basically just a stream of garbage (e.g., my A key's logical key is "Launch Mail" according to logging), so it's much more broken than the GLFW implementation was. Depending on when the rewrite can be ready we may need something shorter term, since this prevents any meaningful use of key events.

**Comment by franciscojma86** [comment]
I don't think the keys ever mapped correctly for Android keys, which I think would make sense. We are passing Windows keycodes and mapping them to Android. The GLFW because there is an actual GLFW mapping. 

https://github.com/flutter/flutter/pull/52265 creates the Windows mapping, but we still don't have a RawKeyboardWindows.dart. We could add that in the meantime while the new design is implemented.

**Comment by franciscojma86** [comment]
Windows keyboard mapping is now implemented on both framework and embedder.
