### ISSUE TITLE
`flutter test` should only build tests that were asked to run

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#37810]
## Use case

`flutter test --platform=chrome test/foo_test.dart` should be fast. Instead, as of right now it will first build every single `*_test.dart` file before running the test. For a project with a large number of tests (e.g. `package:flutter`) this can take a long time (e.g. on my dual Xeon workstation with 128GB RAM it takes 2.5 _minutes_ before the test starts running).

## Proposal

Make the build smarter. Teach it to scope the build to only tests that were requested.

/cc @jakemac53 @jonahwilliams

**Comment by jonahwilliams** [comment]
Originally I had it this way by piping through a list of targets to build. It was pointed out to me that you can't have multiple build daemons running with different configurations. This means that trying to build and run a single test while you are running your web application won't work.

**Comment by yjbanov** [comment]
So is the fix somewhere in dart_lang/build?

**Comment by jakemac53** [comment]
cc @vsmenon for prioritization

Adding full featured functionality for this would be a lot of work, but it would benefit all users. Especially for release mode tests having to compile all apps just to run a single one is a major pain.

Specifically for good support one thing we would need is the ability to know what other files a test depends on outside of just the compiled javascript so we ensure that gets built too. That almost certainly has to involve configuration, but it could be optional and only required for tests that rely on other generated artifacts.

**Comment by jakemac53** [comment]
It would also be possible to add a feature such as `build all the transitive primary outputs of this input file` which might work well enough for the flutter case, and a lot of other cases. You could just provide the test file and then it would build everything required for a basic test.

**Comment by jonahwilliams** [comment]
I don't know how import --platform=chrome actually is. It would certainly make Yegor's debugging easier but I don't think we expect people outside of the flutter web team to use it

**Comment by yjbanov** [comment]
@jonahwilliams It also affects the speed of our CI tests. We won't be able to shard our tests effectively if every shard builds all the tests.

/cc @ferhatb to comment on whether we aim `flutter test --platform=chrome` to be a developer-facing tool. If so, then this is much more critical, as 2.5 minutes for a single tests would be unacceptable.

**Comment by yjbanov** [comment]
Added `dependency: dart` as it seems that the fix is in https://github.com/dart-lang/build

**Comment by jakemac53** [comment]
> @jonahwilliams It also affects the speed of our CI tests. We won't be able to shard our tests effectively if every shard builds all the tests.

As far as CI specifically goes - its actually much more efficient in general to build all tests in a single step, then use that build output to run each test shard. That way all the shards share compilation of any shared libraries, and don't do any duplicate work.

> /cc @ferhatb to comment on whether we aim `flutter test --platform=chrome` to be a developer-facing tool. If so, then this is much more critical, as 2.5 minutes for a single tests would be unacceptable.

While initial builds do matter, our position is that incremental builds are a lot more important. How long does it take to do a new build after making an edit to something in flutter?

The main reason that we haven't tackled this feature previously is that the individual tests themselves compile quite quickly, so its only when you have a large number of them that it really starts to matter. The complexity added on both the build system and users hasn't been worth it (yet).

**Comment by yjbanov** [comment]
> its actually much more efficient in general to build all tests in a single step, and then use that build output to run each test shard. That way all the shards share compilation of any shared libraries, and don't do any duplicate work.

I don't believe we have access to CI infrastructure capable of sharing build artifacts. Also, I'm very skeptical that building thousands of tests in a bottleneck is faster. It didn't take long to feel the pain from it already.

> While initial builds do matter, our position is that incremental builds are a lot more important. How long does it take to do a new build after making an edit to something in flutter?

Without editing the framework:

```
$ time flutter test --platform=chrome test/foundation/assertions_test.dart
00:02 +7: All tests passed!                                                               

real	0m8.669s
user	0m8.061s
sys	0m2.158s
```

After editing the framework:

```
$ time flutter test --platform=chrome test/foundation/assertions_test.dart
00:02 +7: All tests passed!                                                               

real	2m34.243s
user	0m42.012s
sys	0m9.525s
```

So 8.6 seconds vs 2.5 minutes. Looking at `--verbose` output I see this line:

```
9.9s elapsed, 76/87 actions completed.
```

Followed by a long tail of lines like this:

```
building for target test/widgets/parent_data_test.dart.browser_test.dart
```

So the vast majority of time is spent on recompiling all tests when all I want to do is run one test.

> The main reason that we haven't tackled this feature previously is that the individual tests themselves compile quite quickly, so its only when you have a large number of them that it really starts to matter. The complexity added on both the build system and users hasn't been worth it (yet).

I think we're finding out that this approach doesn't scale. This is going to be a big pain point for the team very shortly, and possibly for users, particularly for big customers.

**Comment by jonahwilliams** [comment]
I think I should add the test filtering back to unblock your local development. We can deal with changes to package:build and the web testing story afterwards

**Comment by jakemac53** [comment]
I think the fix here is to do one of the simple but not really complete options I outlined above. I think probably the best option is allowing you to specify an exact output to build. This would be a pretty simple change and would be good enough for flutter since the hardcoded build script means you can't have any other generated files the test is relying on anyways.

> I think I should add the test filtering back to unblock your local development. We can deal with changes to package:build and the web testing story afterwards

Be careful how this is done - I can't remember the details of how it worked before but I don't know of any way to do it that won't cause issues of some sort given the features available today. Feel free to cc me on any prs here.

> I don't believe we have access to CI infrastructure capable of sharing build artifacts. 

CI limitations here are unfortunate, I don't think there is anything our team can really do about that. This seems like it would benefit all flutter tests not just web tests and is a more systematic issue.

> Also, I'm very skeptical that building thousands of tests in a bottleneck is faster. It didn't take long to feel the pain from it already.

The pain you feel is when trying to run a single test locally, which is legitimate for projects of this size.

From a CI perspective based on the results above I think it shows that it would be a net benefit today to build them all in a single build (rebuilding all the tests took significantly less than half the time of the initial build, so building all deps was the majority of the time not building the tests).

> I think we're finding out that this approach doesn't scale. This is going to be a big pain point for the team very shortly, and possibly for users, particularly for big customers.

Yes, the system was explicitly never designed to scale well for running single tests in a package of this size. It is built on an assumption that packages are generally <=medium-large in size. We have had a small number of larger external users run into it though, so fixing this would help them too.

There isn't anything blocking supporting this use case other than sufficient motivation/prioritization to actually solve the problem. But as I mentioned i think we can half solve it in a way that works for flutter and lots of other people, so that is likely worth doing.

**Comment by yjbanov** [comment]
As an extra data point the same one test that takes 2.5 minutes on my workstation, [takes >9 minutes on Cirrus CI](https://cirrus-ci.com/task/6147450996260864) to run.

**Comment by grouma** [comment]
The support is now added. @jonahwilliams please confirm that this issue is resolved.
