### ISSUE TITLE
NSBundle bundleWithIdentifier causes slowdown when creating FlutterEngine

### ISSUE THREAD

**Issue by xster** [flutter/flutter#37826]
The addition of traversing the bundles by searching for an identifier added in https://github.com/flutter/engine/pull/5986/files#diff-8e54aca7e9d4fd69a57fb86d6ec3dee2R36 adds a 100ms latency when instantiating a FlutterEngine (7ms -> 106ms on an iPod). 

It's hard to figure out the original feature request from the PR. Can we revise the approach?

**Comment by jamesderlin** [comment]
Internally we wanted to support having multiple bundles and not rely on the main bundle when looking up Flutter assets. (I'm still trying to refresh my memory about exactly why... I think we considered it a burden for add2app?)

The `+[NSBundle bundleForClass]:` call to initialize `engineBundle` could be moved to where it's used.  I'm not sure what to do about the `+[NSBundle bundleWithIdentifier:]` call.  Possibly we could replace it with `+[NSBundle bundleWithPath:]` (although since the point of finding the bundle is to extract paths from it, probably not).  Maybe another possibility would be to change the ordering so that the expensive lookup is done only after checking cheaper sources.

Anyway, I'm happy to ponder this and assist however I can, but I currently am no longer set up to make and test changes, so this probably would be better owned by someone else.

**Comment by xster** [comment]
For context, the original feature request was b/112004455

**Comment by gaaclarke** [comment]
<img width="1038" alt="Screen Shot 2019-11-18 at 1 15 52 PM" src="https://user-images.githubusercontent.com/30870216/69094614-91799500-0a05-11ea-8af3-ad9a259412ea.png">

FWIW [FlutterDartProject init] takes 4ms on iPhone SE.  Debug build at dd77b73d7e03fcbbd49536a3b58395f086b91d8d

**Comment by gaaclarke** [comment]
I measured with the same previous settings, but an Add-to-app scenario and didn't notice any problem either.

<img width="1035" alt="Screen Shot 2019-11-18 at 2 20 30 PM" src="https://user-images.githubusercontent.com/30870216/69099037-ad356900-0a0e-11ea-89b7-58d5384fc515.png">

The slowdown is plausible.  I just don't know what conditions lead to `[NSBundle bundleWithIdentifier:]` being so slow.  Any ideas?

**Comment by chinmaygarde** [comment]
The [discussion on `[NSBundle bundleWithIdentifier:]](https://developer.apple.com/documentation/foundation/nsbundle/1411929-bundlewithidentifier?language=objc)` has a section on performance implications of this call and suggests alternatives. Specifically:

```
As an optimization, you can use the bundleWithPath: or bundleWithURL: method instead to avoid file system traversal.
```

**Comment by cailianqing** [comment]
![image](https://user-images.githubusercontent.com/15902773/167769159-db31d8eb-1030-40a8-a9da-d26bcde80fca.png)
hi，the problem caused watchdog crash。

**Comment by chuckern** [comment]
@gaaclarke Our project use engineGroup, and there are some watchdog crash when create engine.
Could u please kindly check this?
btw: Flutter version is 2.8.1.
![image](https://user-images.githubusercontent.com/15389630/173722624-bac47969-4f7f-4908-b1de-38a59fa781bd.png)

**Comment by jiahaog** [comment]
It seems like this could be proportionate to the size of the app. For example, `customer: chalk` is more impacted by it than the raw hello flutter app. Googlers - see http://shortn/_WcifhO48X6 for details.
