### ISSUE TITLE
VSCode HotReload  not working on 1.37.0

### ISSUE THREAD

**Issue by allen-hsu** [flutter/flutter#37934]
Hi, All

I had some issue about Vscode hotreload not working 

it' s detail

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hant-TW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
[✓] VS Code (version 1.37.0)
[✓] Connected device (1 available)

But When i change code,  And save, Hotreload not working. Please help me.
Thanks

**Comment by yclive0925** [comment]
In my case, save the code will not automatically hot reload. You have to press 'R', or 'Shift R' to do that.

Do you mean trying to press R or shift+R and your flutter App won't hot Reload? If so, did you have other application running so that it has some shortcuts that will conflict with the hot reload command?
