### ISSUE TITLE
== & hashCode on ImageFilter, Shader and Paint

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#38011]
I'm trying to establish an identity for objects painted on a canvas. Currently, of the non-primitive properties of `Paint`, only `MaskFilter` and `ColorFilter` seem to implement ` == and hashCode`. What about `ImageFilter` and subclasses of `Shader`?

Is there a significant performance/memory overhead in making them equatable?

A PaintBuilder can solve my problem but wrapping ImageFilter and Shader just seems unnecessary and I'm curious if this was a deliberate decision. 

Thanks.

**Comment by jonahwilliams** [comment]
In order to implement `operator.==` and `hashCode`, a class must be immutable. Paint, ImageFilter, and others are mutable objects and therefore these methods cannot be implemented correctly. 

For example, imagine placing a ColorFilter as the key in a map and passing it to a render object. that render object may (though it shouldn't) mutate a value in the ColorFilter. This would require its hashCode to change, despite the fact that it may have already been bucketed in the map based on the previous values. Worse, it could cause it to become equal to another object. What should happen then?
