### ISSUE TITLE
[Tooling] MaterialApp Navigator stack appears as children in the widget tree

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#38038]
## Steps to Reproduce

Made a 2 min video of how this affects us in particular. When using the select widget tools, widgets from the back layers get selected.
https://www.youtube.com/watch?v=067oK-kWi2s

1. Is this expected behaviour
2. If not, then what might be causing this, also how to get around this problem?

**Comment by eseidelGoogle** [comment]
@jacob314 would know if this is a bug.  Thanks!

**Comment by jacob314** [comment]
This is a bug. Thank you so much for filing such an easy to follow repro video.
Either one of two things is true and I am working to figure out which it is.
1. The Inspector is not being properly informed that the main page is not visible in this case.
2. The main page is still rendering when it shouldn't be possibly leading to flutter to be less efficient than it could be in this case.

**Comment by jacob314** [comment]
Update. You caught a flutter performance bug by using the inspector. Thanks for your help!

**Comment by raveesh-me** [comment]
Hi @jacob314! The last PR was closed. This issue heavily affects a lot of things related to daily programming experience.
Can we get a status update, please?

**Comment by jacob314** [comment]
@HansMuller can your team please take a look at 
https://github.com/flutter/flutter/pull/38475
This shows a quick and dirty fix for a real issue currently where the Element tree contains content it shouldn't when navigation is set to a route other than the default route.
Fixing this issue is likely to improve general app performance slightly in this case as more content than needed is rendered and included in the element tree due to the bug.
