### ISSUE TITLE
Dart_GetField is 2ms of each frame in the gallery weather demo

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3808]
This trace: https://github.com/flutter/flutter/issues/3082#issuecomment-217916705
...shows that about 2ms of each frame of the weather demo in the gallery consists of calls to Dart_GetField.

**Comment by eseidelGoogle** [comment]
Most of them are for Paint._value, although there are several other field names represented.

**Comment by abarth** [comment]
Yeah, I didn't do `Paint._value` in my previous pass.  I can do that one too.

**Comment by eseidelGoogle** [comment]
Counts of GetField calls under Paint phase in that trace:
     73 "Paint._value"
      6 "OffsetBase._dy"
      6 "OffsetBase._dx"
      4 "Color._value"
      2 "TransferMode.index"
      2 "Point.y"
      2 "Point.x"

**Comment by abarth** [comment]
I think the solution here is to record the canvas commands into a ByteData buffer in Dart and then move all the commands into C++ in one operation.

**Comment by mraleph** [comment]
BTW, I have been discussing with some folks that if Dart had an FFI-centric bindings instead of API-centric bindings then this kind of overhead (like `Dart_GetField`) would disappear. 

In FFI-centric bindings you will describe marshaling rules on the Dart side instead of having them on the C++-side. Having marshaling rules on Dart side allows us to generate specialized marshaling stubs dynamically leading to a very good performance. 

For example we could allow writing something like this:

```dart
// This ffi.Signature is some sort of description of how arguments are marshaled.
@ffi.Signature("void foo (struct { double offset._dx, double offset._dy })")
void x(OffsetBase offset) native "foo";
```

The hardest part is actually deciding on format for these signature descriptions.

**Comment by abarth** [comment]
Interesting.  I've been experimenting with doing something like that manually by encoding the arguments into a typed array.

**Comment by abarth** [comment]
https://github.com/flutter/engine/compare/master...abarth:encoded_buffer?expand=1 is an example with encoding into typed arrays.  Unfortunately, it didn't seem to be measurably faster.

**Comment by abarth** [comment]
Canvas no longer calls Dart_GetField.
