### ISSUE TITLE
Downloading dart sdk prints a staircase of #

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3826]
FYI, looks like the staircase effect is still happening. This is from master as of 5 minutes ago:

![screen shot 2016-05-09 at 6 15 19 pm](https://cloud.githubusercontent.com/assets/5479/15132823/109f2390-1612-11e6-827b-1ecd4ce504c5.png)

**Comment by Hixie** [comment]
I think this is a bug in `curl`, I don't know what we can do about it. Do you still see it anywhere other than bots? (Bots are probably handling the \r wrong.)

Moving to conference milestone because if we do anything that's when we should do it by. But I think we might just want to close this if we're not seeing it anymore.

**Comment by sethladd** [comment]
I see it on my local machine (Mac).

**Comment by Hixie** [comment]
do you see it just using curl?

**Comment by sethladd** [comment]
Once our next roll of the Dart SDK is finished, I'll let you know what happens

**Comment by Hixie** [comment]
@sethladd I'm closing this because I'm pretty sure we don't use this feature of curl anymore.
