### ISSUE TITLE
Error: The key 'B {}' does not have a primitive operator '=='.

### ISSUE THREAD

**Issue by miguelcmedeiros** [flutter/flutter#38298]
(Apologies for the cryptic title but I couldn't properly translate the error into something better...)

While updating flutter from v1.7.8+hotfix.3 to v1.8.4 I get errors similar to the following:
```
test.dart:27:27: Error: The key 'B {}' does not have a primitive operator '=='.
 - 'B' is from 'test.dart'.
  const c = C(<B, String>{B("1"): "11", B("2"): "22"});
                          ^
test.dart:27:9: Context: While analyzing:
  const c = C(<B, String>{B("1"): "11", B("2"): "22"});
        ^
```

The error above is produced by the following sample code that I created for this ticket (but that mimics what we have in our app):
```
import 'package:meta/meta.dart';

class A {
  const A(this.a);

  final String a;

  @override
  bool operator ==(dynamic other) => other.runtimeType == runtimeType && other.a == a;

  @override
  int get hashCode => a.hashCode;
}

@immutable
class B extends A {
  const B(String a) : super(a);
}

class C {
  const C(this.b);

  final Map<B, String> b;
}

void main() {
  const c = C(<B, String>{B("1"): "11", B("2"): "22"});

  print(c.b);
}
```

I couldn't pin-point from where this different behaviour is coming from... I am hoping to get some insights on this and advice on how to proceed. 

### v1.7.8+hotfix.3
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-NL)
    • Flutter version 1.7.8+hotfix.3 at /Users/user/IdeaProjects/hue_blue/dev/flutter
    • Framework revision b712a172f9 (5 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0
```

### v1.8.4
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.8.4, on Mac OS X 10.14.4 18E226, locale en-NL)
    • Flutter version 1.8.4 at /Users/user/IdeaProjects/hue_blue/dev/flutter
    • Framework revision 954714c967 (10 days ago), 2019-08-02 10:10:39 -0700
    • Engine revision 26368225b5
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)
```

**Comment by munificent** [comment]
Dart has always behaved this way. Or, at least, that has always been the *intended* behavior. If the error message is new, it may have been a bug that was fixed. The error should always have been reported.

What's going on here is the code has a *const map* whose keys are a *user-defined class.*

1. Because it's a map, it needs to deduplicate overlapping keys. So, `{1: "a", 1: "b"}` becomes `{1: "b"}`.
2. In order to tell if two keys overlap, the language relies on the `==` operator of the key's type.
3. Because the map is const, that deduping process has to happen at compile time.

If the key is a user-defined type with its own `==` operator, (2) and (3) would imply calling arbitrary user code at compile time. We don't want to allow that, so the language prohibits using classes with custom `==` operators as keys in const maps.

You have a couple of options:

1. Make the map non-const.
2. Don't override `==` in the class.
3. Use a different class for the key.

**Comment by miguelcmedeiros** [comment]
@munificent, thanks for the explanation and for the possible options.
