### ISSUE TITLE
flutter_webview_plugin breaks flutter build aar command

### ISSUE THREAD

**Issue by PoojaB26** [flutter/flutter#38416]
I have tried the **Depend on the Android Archive (AAR)** approach from the [Add2App ](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) documentation. Everything works fine for a sample app, but the `flutter build aar` command broke as soon as I added all the plugins from my project. 
I get the following error 

```
Poojas-MacBook-Pro:metrobikes_flutter pooja$ flutter build aar
Running "flutter pub get" in metrobikes_flutter...                  0.9s
Initializing gradle...                                              0.9s
Resolving dependencies...                                           1.6s
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   16.9s
Gradle task assembleAarRelease failed with exit code 1
```

After some trial-n-error, I realized removing `flutter_webview_plugin` creates a successful build. 

```
Poojas-MacBook-Pro:metrobikes_flutter pooja$ flutter build aar
Initializing gradle...                                              0.8s
Resolving dependencies...                                           1.4s
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   71.2s
Built build/host/outputs/repo.
```

Now when I try the same source code with the second approach - **Depend on the module's source code** on the Add2App documentation, the app runs successfully. There were some merged manifest errors during this approach. Even after fixing them, I tried `flutter build aar`, but I get the following error. 

`Gradle task assembleAarRelease failed with exit code 1`

**1. What is the issue with AAR and Webview plugin?
2. Can we get a more descriptive error log during `flutter build aar`?** 

Flutter Doctor
```
Poojas-MacBook-Pro:metrobikes_flutter pooja$ flutter doctor -v
[✓] Flutter (Channel master, v1.8.5-pre.117, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.8.5-pre.117 at /Users/pooja/flutter
    • Framework revision 83a8a575ee (3 days ago), 2019-08-10 12:38:20 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/pooja/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 38.1.3
    • Dart plugin version 191.8369
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jason-simmons** [comment]
I'm not sure if this is the right solution, but I can get an AAR depending on `flutter_webview_plugin` to build by patching its build script.

In a local copy of https://github.com/fluttercommunity/flutter_webview_plugin/blob/master/android/build.gradle, go to the `allprojects` / `repositories` section and add a `google()` repository.

Without this, `flutter build aar` will fail in the `:flutter:buildPluginReleaseFlutterWebviewPlugin` task.  You can see this by passing the `-v` verbose log flag to the `flutter` tool.

Debugging further requires extracting some of the `gradle` and `flutter` tool command lines invoked while executing `buildPluginReleaseFlutterWebviewPlugin`.  That task runs `flutter build aar` within the pub cache directory containing the `flutter_webview_plugin` sources.  That in turn runs another Gradle task that fails because it can't find some `androidx` packages in the repository search path.

@blasten is there a way to see the logs from these nested runs of Flutter and Gradle tooling?

**Comment by xster** [comment]
@jason-simmons, are you saying that the root cause of this issue is that flutter_webview_plugin's own build rules didn't list out its own transitive dependencies "implementation group: 'androidx.appcompat'" since that dependency seems to be fulfilled from the google maven repository only rather than jcenter? https://stackoverflow.com/questions/57125966/could-not-find-androidx-appcompatappcompat1-0-2

If so, then this seems like a bug that should be filed on https://github.com/fluttercommunity/flutter_webview_plugin for being non-self-sufficient in its own build rule.

**Comment by PoojaB26** [comment]
Thank you @jason-simmons @xster Closing this issue because it is an error on the plugin's part, and not on flutter's.

**Comment by blasten** [comment]
> is there a way to see the logs from these nested runs of Flutter and Gradle tooling?

@jason-simmons No from the Flutter tool. However, if you run `gradle` or `./gradlew` in the project's directory you can pass `-Pverbose=true` and that will add the `--verbose` flag to the nested runs of the tool. (We should fix the tool though)

Jason is correct that AndroidX dependency is available on Google Maven only, so the plugin must add `google()` to the `allProjects -> repository` function call.

I'm going to reopen the issue, since it would be great if we can run Gradle in verbose mode (always), but show the logs only if an error occurred. This can help save time while troubleshooting.

**Comment by vAugagneur** [comment]
The plugin flutter_webview_plugin could not be built due to the issue above.

0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
3      _rootRunBinary (dart:async/zone.dart:1146:38)
4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
8      Future._completeError (dart:async/future_impl.dart:532:5)
9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
10     _rootRun (dart:async/zone.dart:1126:13)
11     _CustomZone.run (dart:async/zone.dart:1023:19)
12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by blasten** [comment]
This issue is fixed. `flutter build aar` prints the stdout/stderr from Gradle if an error occurred.

**Comment by blasten** [comment]
Running the plugin `flutter_webview_plugin` as an AAR results in:
```
Unsupported Android Plugin version: 3.5.3.
```

**Comment by blasten** [comment]
Closed since it was fixed already
