### ISSUE TITLE
Table default column flexing is hard to debug when scrolling horizontally

### ISSUE THREAD

**Issue by bmsan** [flutter/flutter#38526]
> Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 20e59316b8 (4 weeks ago) • 2019-07-18 20:04:33 -0700
> Engine • revision fee001c93f
> Tools • Dart 2.4.0
> flutter pub global run webdev --version shows 2.4.0

Browser : Chrome  76.0.3809.100 (Official Build) (64-bit)
OS: Windows 10 x64

I'm hitting an issue with flutter webdev when using a Table inside a SingleChildScrollView which has scrollDirection horizontal(doesn't show anything).  See examples below.

1. Vertical direction works perfect
2. The command prompt where I started flutter doesn't give any error
3. The console log of the browser doesn't say anything different between (Vertical and Horizontal)
4. I've tried making the elements inside the TableRow to use SizedBox with width  & height given but that didn't help

SingleChildScrollView(horizontal scroll) doesn't show anything:
`SingleChildScrollView(scrollDirection: Axis.**horizontal**, child : Table(children: rows) ) `
![image](https://user-images.githubusercontent.com/52523668/63009326-f19fee80-be8c-11e9-8ade-d06b9f337e53.png)

SingleChildScrollView(vertical scroll) works ok:
` SingleChildScrollView(scrollDirection: Axis.**vertical**, child : Table(children: rows) ) `
![image](https://user-images.githubusercontent.com/52523668/63009241-c3221380-be8c-11e9-85a8-91009864e16d.png)

[Code example which exhibits problem](https://gist.github.com/bmsan/958bb793b2b3ed6e69f85327ba9f604e)

```
import 'dart:async';
import 'dart:convert';

import 'package:flutter_web/material.dart';
import 'package:http/http.dart' as http;



void main() => runApp(MyApp());


class MyApp extends StatelessWidget {

  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {

    List<TableRow> rows = [];
    rows.add(TableRow(children: [Text('00'), Text('01'), Text('02')]));
    rows.add(TableRow(children: [Text('10'), Text('11'), Text('12')]));

    return MaterialApp(
      title: 'Table Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Table example'),
        ),
        body: Center(
          // The commented line below shows correct ouput 
          //child: SingleChildScrollView(scrollDirection: Axis.vertical, child : Table(children: rows) ) 
          // The  line below won't show the table in the browser
          child: SingleChildScrollView(scrollDirection: Axis.horizontal, child : Table(children: rows) ) 
        ),
      ),
    );
  }
}
```

**Comment by GMC254** [comment]
This is not only affecting web platform but is also affection android platform. Running the same code on an android emulator results in the same result.

**Comment by Piinks** [comment]
This is happening because the `Table.defaultColumnWidth` is `FlexColumnWidth(1.0)`. 

This `TableColumnWidth` sizes all of the columns based on the available space, but since the `SingleChildScrollView.scrollDirection` is `Axis.horizontal`, the remaining space is infinite. The column can't flex because it can't tell how to divide up infinite space between the columns. 

You can fix this by using a different [`TableColumnWidth`](https://api.flutter.dev/flutter/rendering/TableColumnWidth-class.html) for `Table.defaultColumnWidth`, there are a number to choose from that can be applied for horizontal scrolling:
- [`FixedColumnWidth`](https://api.flutter.dev/flutter/rendering/FixedColumnWidth-class.html)
- [`IntrinsicColumnWidth`](https://api.flutter.dev/flutter/rendering/IntrinsicColumnWidth-class.html)
- [`MaxColumnWidth`](https://api.flutter.dev/flutter/rendering/MaxColumnWidth-class.html)

I think we can definitely improve the documentation here. I'll mark this for doc work. :)

Here is an updated code sample with `Table.defaultColumnWidth`:
```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<TableRow> rows = [];
    for (int n in Iterable.generate(4)) {
      List<Text> rowChildren = [];
      for (int m in Iterable.generate(4))
        rowChildren.add(Text('$n-$m'));
      rows.add(TableRow(children: rowChildren));
    }

    return MaterialApp(
      home: Scaffold(
        body:SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child : Table(
            children: rows,
            defaultColumnWidth: FixedColumnWidth(200.0),
          ),
        ) 
      ),
    );
  }
}
```
