### ISSUE TITLE
Flutter does not support to run USSD codes in background 

### ISSUE THREAD

**Issue by sindejr** [flutter/flutter#38548]
is there a way to make USSD calls and receive callbacks from a USSD calls. It would be awesome if this feature is provided

**Comment by oloohezbon** [comment]
waiting for this feature.

**Comment by amaaradji** [comment]
can't wait for it!

**Comment by MoeinElwani** [comment]
still waiting for it!

**Comment by vkammerer** [comment]
Disclaimer: [plugin](https://pub.dev/packages/ussd_service) author here.

Since Android API level 26, the method [sendUssdRequest](https://developer.android.com/reference/android/telephony/TelephonyManager.html#sendUssdRequest(java.lang.String,%20android.telephony.TelephonyManager.UssdResponseCallback,%20android.os.Handler)) is exposed to make silent USSD requests.

I made a Flutter plugin called [ussd_service](https://pub.dev/packages/ussd_service) to be able to easily access it from dart in a Flutter application. It can be used in the following manner:
```dart
import 'package:ussd_service/ussd_service.dart';

makeMyRequest() async {
  int subscriptionId = 1; // sim card subscription Id
  String code = "*21#"; // ussd code payload
  try {
    String ussdSuccessMessage = await UssdService.makeRequest(subscriptionId, code);
    print("succes! message: $ussdSuccessMessage");
  } on PlatformException catch (e) {
    print("error! code: ${e.code} - message: ${e.message}");
  }
};

makeMyRequest();
```

If you are targeting only Android, this could be helpful. Unfortunately, iOS doesn't support running silent USSD requests.
Let me know on the [Github repo](https://github.com/vkammerer/ussd_service)'s issues if you have any issue with it.
