### ISSUE TITLE
Provide API to notify framework that system fonts have changed

### ISSUE THREAD

**Issue by kpozin** [flutter/flutter#38556]
OSes can notify applications if the list of installed fonts has changed. It would be helpful for Flutter to be able to respond to such notifications and redraw text, particularly if previously a fallback font was used or no font was found for particular code point.

**Comment by Hixie** [comment]
e. g. https://docs.microsoft.com/en-us/windows/win32/gdi/wm-fontchange

**Comment by kpozin** [comment]
Per discussion with @Hixie, please add labels `customer: fuchsia`, `severe: customer critical`.

**Comment by Hixie** [comment]
What we need here is:

- [ ] A mechanism by which Fuchsia can tell code somewhere in flutter_runner that the list of fonts has changed.
- [ ] Code in the Fuchsia embedder or in Skia to listen to the notification from Fuchsia.
- [ ] Code in the Windows embedder to listen to WM_FONTCHANGE in the same way.
- [ ] Maybe macOS and Linux also have notification mechanisms for when fonts are added? If so, same thing there.
- [ ] Code to pass that notification to the framework, probably over a message channel, possible over a dart:ui callback.
- [ ] Code in the binding to multiplex that notification to listeners who care about it. The listener mechanism can't just be a ChangeNotifier because there's going to be a lot of listeners. We want a Set or something like that.
- [ ] Code in RenderParagraph and other places that use TextPainter that register with the binding to be told when the fonts list changes, and mark themselves as needing layout when that happens.
- [ ] Tests. Ideally an end-to-end test on Windows and Fuchsia.

cc @GaryQian @jason-simmons @goderbauer @xster @matthew-carroll @stuartmorgan 

Separate from this we should also make sure we support fallback fonts on Skia (fontFamilyFallback).

**Comment by chunhtai** [comment]
@kpozin May I know how would you intend to call the api? is there any callback involve? and will that be called from skia library or fuchsia embedder? If possible, it will be perfect if you can provide a snippet of code that demonstrate how you would expect to use the api

**Comment by kpozin** [comment]
There will be a FIDL event that we'll register for. Still being reviewed, but here's the [current version](https://fuchsia-review.googlesource.com/c/fuchsia/+/311329/3/sdk/fidl/fuchsia.fonts/events.fidl).

I'm not yet sure whether we'll call it from Skia or from the embedder; I don't know if we have access to  a thread with an event loop in `SkFontMgr`.

**Comment by chunhtai** [comment]
I think we should be able to leverage systemchannel to provide the api from any layer of engine. Since there is no counter part in mac and linux, and Fuchsia is still not clear about exact implementation, I will focus on windows for now and provide some api example for fuchsia.

**Comment by kf6gpe** [comment]
@chunhtai Do you have a milestone estimated for when this will land? Thanks!

**Comment by chunhtai** [comment]
Besides framework change, I am in the middle of implementing the change in windows embedding, as well as the providing an example for fuchsia

**Comment by jonahwilliams** [comment]
+ @hterkelsen @mdebbar this might also be relevant for loading web fonts

**Comment by cbracken** [comment]
@chunhtai one week to end of Sept -- sounded like we were still on schedule for this milestone, is that still correct?

**Comment by chunhtai** [comment]
@cbracken yes, waiting for tree to go green before I can land the pr

**Comment by chunhtai** [comment]
Change landed.
To reload the flutter app and system font, you will only need to call this embedder api

https://github.com/flutter/engine/blob/aadd5a346bb5fcf970a90e3c98d55818b4734e48/shell/platform/embedder/embedder.h#L1211

you will also need to modify current logic of loading default fonts.
https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/platform_fuchsia.cc
because the skia api SkFontMgr::RefDefault() will cache the result internally.
