### ISSUE TITLE
Remove engineSwitches property from (Flutter)DartProject

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38569]
`FlutterDartProject` (macOS) and `flutter::DartProject` (Windows) have an engine switches property that allows passing switches directly to the Flutter engine. This is a problematic API since those switches aren't generally intended for production use and don't have any stability guarantees. This doesn't exist on the corresponding iOS class.

These are the use cases I'm currently aware of that prevent me from removing it right now:
- `disable-observatory` and `disable-dart-asserts`. This is a partial workaround for the lack of Release support, but that will go away soon.
- Use of `dart-flags` for a specific internal client; the timeline for removing the need for this is TBD.

If you are using this property to pass something other than the above, please comment to explain what you are passing and why so that I can evaluate that in determining when to remove this.

**Comment by fertrig** [comment]
We are using `FlutterDartProject.engineSwitches` to pass these two switches:
- `observatory-port=12345`
- `disable-service-auth-codes`

We are working on a tool that automates developer tasks. Some of those tasks include launching a flutter app, attaching to it and hot restarting it as needed. To manage the flutter app we need to know ahead of time the observatory port on which it will be running, which is why we need to use the `observatory-port=12345` switch. We also need to disable the auth codes (via the `disable-service-auth-codes` switch), otherwise we would not be able to compute the observatory url to connect to.

If there is another way to accomplish what we need we are open to change our code.

**Comment by dnfield** [comment]
I want to be able to use this for debugging purposes. Sometimes I need to pass additional arguments to the Dart VM to get extra logging or behavior - e.g. to observe more about GC operations.

I also like ot use it to disable service auth codes and specify what observatory port is being used.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/60393 tracks adding something other than this API for one-off debugging uses cases. The primary concern about this API as I understand it was that since it's build-time rather than runtime, it encourages use of these flags as if they were APIs (e.g., the assertion disabling that was used to make faux-release builds prior to actual release build support).

> We are working on a tool that automates developer tasks. Some of those tasks include launching a flutter app, attaching to it and hot restarting it as needed. To manage the flutter app we need to know ahead of time the observatory port on which it will be running

This use case should be addressable with whatever approach we take for #60393. However, I'm curious why you need to know ahead of time; the `flutter` tool does *exactly* what you are describing, and doesn't use either of those flags, instead getting the URL from `stdout`. Why can't your workflow do the same thing?

**Comment by fertrig** [comment]
You are right, we don't need to know ahead of time. However, it is a cleaner solution to pass the flags than to read the url from stdout. That is why we used the `engineSwitches`.

We can certainly pattern match stdout to find the observatory url. Please confirm that is what flutter tool does to get the observatory url.

Also, since our tool is for developers, a solution that works only in debug mode is fine.

**Comment by stuartmorgan** [comment]
> We can certainly pattern match stdout to find the observatory url. Please confirm that is what flutter tool does to get the observatory url.

https://github.com/flutter/flutter/blob/6067571fabca7e104f15d0bd74de50568cb4597a/packages/flutter_tools/lib/src/protocol_discovery.dart#L108

**Comment by stuartmorgan** [comment]
This was removed for Windows before the alpha, and https://github.com/flutter/engine/pull/21468 will shortly remove it for macOS. Summarizing the migration for all cases raised here:
- "`disable-observatory` and `disable-dart-asserts`" -> Remove. This was a temporary workaround for the lack of release builds; if people still have old project that are still passing these flags in release (from a native build perspective) builds, it's already been a no-op for quite a while.
- "Use of `dart-flags` for a specific internal client" -> enableMirrors is added to macOS in the PR above to temporarily allow enabling that specific flag as a compile-time option.
- "We are working on a tool that automates developer tasks." -> That tool can [set the environment variables directly](https://github.com/flutter/flutter/issues/60393#issuecomment-696940505 ) (or, as noted in discussion above, not do this at all).
- "I want to be able to use this for debugging purposes." -> For custom use, [set the variables manually](https://github.com/flutter/flutter/issues/60393#issuecomment-696940505). For most use, https://github.com/flutter/flutter/issues/66532 (which will be fixed using the new env variable functionality) should avoid the need to.
