### ISSUE TITLE
Support Texture widget in Windows embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38601]
This is necessary for supporting arbitrary non-native-view content, such as video playback.

(See #30717, #30718 )

**Comment by chichid** [comment]
I'd be happy to contribute if this is not started already.

**Comment by stuartmorgan** [comment]
I'm not aware of any blockers, it just hasn't been implemented.

**Comment by ds84182** [comment]
Wondering if it would be worth using the DirectComposition API on Windows 8+: https://docs.microsoft.com/en-us/windows/win32/directcomp/basic-concepts

Using DC would allow applications to embed another window's visual without having to figure out parenting. It might also be worthwhile using DC for Flutter's entire layer tree to reduce power usage, since DC is already used for the rest of the desktop & XAML applications.

For Windows 7 there isn't a way to get the compositor to do cool things. Maybe https://devblogs.microsoft.com/oldnewthing/20130513-00/?p=4393 would work OK.

**Comment by stuartmorgan** [comment]
> Using DC would allow applications to embed another window's visual

That sounds like platform views rather than `Texture`, unless I'm not understanding the proposal.

**Comment by ds84182** [comment]
Ah right, my train of thought is that platform views are just textures with additional input capabilities. The role of a Surface on Android is just about the same as the role of a HWND on Windows, minus input support.

Typically, when embedding content you'd have someone create a window handle, which you then pass into some other API/program. For example [SDL_CreateWindowFrom](https://wiki.libsdl.org/SDL_CreateWindowFrom), or [mpv's --wid parameter](https://mpv.io/manual/stable/#options-wid). In either case, the created window serves both roles. If there's input it's a platform view, if there isn't its a texture.

**Comment by stuartmorgan** [comment]
> If there's input it's a platform view, if there isn't its a texture.

Do `Texture` widgets on any other platform cause render tree separation into separate native surfaces the way `PlatformView` does? I thought that was a significant architectural difference between the two.

**Comment by ds84182** [comment]
Just checked, and from what it looks like that answer is "no". Windows doesn't have an API that fits then, if the contents are supposed to be placed within Flutter instead of sandwiching native surfaces. I don't think there's an alternative that isn't intrinsically linked with the underlying graphics API, other than accepting a raw buffer of pixels and calling it a day.

**Comment by stuartmorgan** [comment]
This was fixed by the PRs above.

There may be follow-up work in the future to support non-pixel-buffer versions of the API, but those would need to be proposed and evaluated individually.

**Comment by Sunbreak** [comment]
> This was fixed by the PRs above.
> 
> There may be follow-up work in the future to support non-pixel-buffer versions of the API, but those would need to be proposed and evaluated individually.

Is there any related issue about `non-pixel-buffer` that we could track progress with?

**Comment by stuartmorgan** [comment]
Someone would need to file an issue proposing a specific implementation.
