### ISSUE TITLE
Should I add a Key property to my custom widgets?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3868]
For example:

```
class ItemLimitWarning extends StatefulWidget {
  @override
  State createState() {
    return new ItemLimitWarningState();
  }
}
```

I have no constructor, and have no notion of a `Key` in the Widget. I currently have never used `Key`, nor do I understand when I would.

**Comment by HansMuller** [comment]
StatelessWidget and StatefulWidget are fundamental building blocks for app developers so perhaps we should document them in slightly more tutorial fashion. Maybe something like this:

A typical simple Stateless widget has a final field for each of its constructor parameters and a build() method that returns a widget tree which reflects the parameters' values. The typical widget's constructor also accepts a key parameter.

```
class MyWidget extends StatelessWidget {
 MyWidget({ Key key, this.parameter1, ..., this.parameterN }) : super(key: Key);

 final Type1 parameter1;
 ...
 final TypeN parameterN;

 @override
 Widget build(BuildContext context) {
   // Return a widget tree that reflects the constructor's parameters.
 }
}
```
Callers may specify a Key to ensure that the widget's Element will be reused or a GlobalKey so that the widget's Element can be referred to later.

**Comment by drewwarren** [comment]
> The typical widget's constructor also accepts a key parameter.
When should a widget's constructor not accept a key parameter? What is the impact if none of the widgets I have created so far take a Key? Should I refactor them to accept a Key?

**Comment by abarth** [comment]
> When should a widget's constructor not accept a key parameter?

I'd recommend always accepting a key parameter except if the widget is private to the current library (i.e., has a name that starts with `_`) and no code in that library wants to use a key with the widget.

> What is the impact if none of the widgets I have created so far take a Key?

The impact is that if future code wants to associate a key with the widget, they'll either need to modify the widget to add the key parameter or they'll need to wrap the widget in another widget that does have a key.

> Should I refactor them to accept a Key?

All of the widgets in the framework accept a Key and I'd recommend it as a best practice.

**Comment by eseidelGoogle** [comment]
https://flutter.io/widgets-intro/#keys discusses the utility of keys and perhaps answers @drewwarren's question as to their utility?  If not we can update said section here:
https://github.com/flutter/website/blob/master/widgets-intro.md

**Comment by sethladd** [comment]
Tracking the doc work here: https://github.com/flutter/flutter/issues/8818

I assume that further docs will help address this. If we need to do more, please reopen. Thanks!
