### ISSUE TITLE
Issues with flutter run

### ISSUE THREAD

**Issue by AmitKrSurjo** [flutter/flutter#38784]
I have run: flutter run 
but the command prompt shows error....
initializing gradle..
oops... flutter has exited

**Comment by KasarAkash** [comment]
initializing gradle...                                                 ⣟
Oops; flutter has exited unexpectedly.
Sending crash report to Google.                                 
Failed to send crash report due to a network error: SocketException: Failed host lookup:
'clients2.google.com' (OS Error: Name or service not known, errno = -2)
Initializing gradle...                                                  Crash report written to /home/ubantu/my_app/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by BondarenkoStas** [comment]
@AmitKrSurjo is it still relevant? Please provide your ```flutter doctor -v``` output. And maybe logs of ```flutter run --verbose``` to give more information.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
