### ISSUE TITLE
Add analyze to engine framework tests

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#38848]
This would catch the failure in https://cirrus-ci.com/task/6210121732980736?command=test#L12 (caused by https://github.com/flutter/engine/pull/11041) early in the engine pre-submit tests.

**Comment by dnfield** [comment]
I had done this a little while back but I don't think it was wired up to CI...  Or, I thought it was...

**Comment by liyuqian** [comment]
@dnfield : can you still find your work locally so we can wire it up to CI?

**Comment by liyuqian** [comment]
The problem I have is that `flutter analyze --dartdocs --flutter-repo --local-engine=host_debug_unopt` doesn't seem to be picking up `@Deprecated` change in my local engine.

**Comment by dnfield** [comment]
I don't think I would expect `flutter analyze` to work - you'd want to just use `dartanalyzer`.

**Comment by dnfield** [comment]
Yup - 
```
autoninja -C out/host_debug_unopt
cd flutter/testing/dart
pub get
dartanalyzer .
```

There are a bunch of errors/warnings now since we don't have this running on CI.

**Comment by dnfield** [comment]
Ahh I misunderstood what this issue was about.

This should be possible, but it will probably require some changes in the tooling - or it will require some other magic in the CI.

I'm going to unassign this - I don't have an entirely clear picture right now about when it will happen, and I'm a but murky on how to best make the testing of framework against engine commits happen.
