### ISSUE TITLE
Text Widget: Chinese characters and English characters  line height problem

### ISSUE THREAD

**Issue by X-Liang** [flutter/flutter#38875]
```
Container(
  child: Text(
    "测试",
    style: TextStyle(color: Colors.white, height: 1, fontSize: 18),
  ),
  color: Colors.red,
),
Container(
  child: Text(
    "Test",
    style: TextStyle(color: Colors.red, height: 1, fontSize: 18),
  ),
  color: Colors.green,
),
```
I have two Text widget, one of them set Chinese characters and another one set English character, but I found they have different line height
like this:
![Simulator Screen Shot - iPhone 5s - 2019-08-20 at 12 48 07](https://user-images.githubusercontent.com/10297030/63318350-c7e13e80-c348-11e9-80d7-1ac88a98bfa5.png)
And I found `stuctStyle` property maybe solve my problem，and I change my code like this:
```
Container(
  child: Text(
    "测试",
    style: TextStyle(
      color: Colors.white,
    ),
    strutStyle: StrutStyle(height: 1.01, fontSize: 18),
  ),
  color: Colors.red,
),
Container(
  child: Text(
    "Test",
    style: TextStyle(
      color: Colors.red,
    ),
    strutStyle: StrutStyle(height: 1.01, fontSize: 18),
  ),
  color: Colors.green,
),
```
screen snapshot like this:
![Simulator Screen Shot - iPhone 5s - 2019-08-20 at 12 51 02](https://user-images.githubusercontent.com/10297030/63318512-463de080-c349-11e9-9145-e894fa5318d2.png)
I have a problem：**Why the strutStyle property ‘height‘ value is：1.01 not 1.0. Does they have some special arrangement?🤔**
Looking forward to answer my question，Thanks🤟🏼

**Comment by InMatrix** [comment]
@GaryQian

**Comment by GaryQian** [comment]
The `StrutStyle` property defines a imaginary font+styling whose metrics are used as the minimum line height across the paragraph. Since you did not specify a `fontFamily`, the font whose metrics the strut was based off of is whatever the default font is.

Regarding heights, there has been a recent breaking change regarding the height behavior. See the master channel API docs: https://master-api.flutter.dev/flutter/painting/TextStyle-class.html#painting.TextStyle.4

There is now a distinction between null height and 1.0 height. Null height indicates using the font's line height. When height is set to a non-null value, the height becomes scaled against the fontSize. For example, let us say with `height: null`, the font specifies 12pixels tall for a 10pt font. When `height: 1.0`, the text becomes 10pixels tall. With `height: 2.5` the text becomes 25pixels tall.

This applies to both TextStyle and StrutStyle. The behavior you are seeing looks like is still of the old behavior (where height is a direct multiplier of the font specified height, 12 in the example above), which is no longer valid going forwards because it would generate different heights depending on what the font specifies as its default height. I recommend trying the new system on the beta dev or master channels which should produce more predictable and consistent line heights.

When you set the height to 1.01, it likely produced a strut that was taller than any of the fonts in the line, causing them to be padded to fill the extra space. Note that strut does not actually make the characters larger/smaller, only the line height.

**Comment by GaryQian** [comment]
I'm going to close this issue for now, please let me know if you have any additional questions/follow up and I am happy to reopen!
