### ISSUE TITLE
Search engines can return https://docs.flutter.io, which has invalid cert

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#3889]
To reproduce, search for "flutter BindingBase", or directly visit https://docs.flutter.io/ in Chrome.

NET::ERR_CERT_COMMON_NAME_INVALID

"This server could not prove that it is docs.flutter.io; its security certificate is from *.storage.googleapis.com. This may be caused by a misconfiguration or an attacker intercepting your connection."

Somehow, search engines think https should work for docs.flutter.io, but it doesn't. We need to teach search engines to only use http.

(Why can't we use https? Because we use google cloud storage, and it doesn't support custom domains + custom certs)

**Comment by sethladd** [comment]
Sorry about that. That's a problem with google cloud storage's configuration. I think this is out of our control, unfortunately, since GCS doesn't allow us to use a custom domain + custom SSL cert. I'm surprised they are responding to https://docs...

We don't explicitly link to https://docs... for this reason. If you see that link in the wild, please let me know and we'll need to fix it.

I don't know what to do about this, so I'm going to close. But open to ideas (if we know of a good way to host a large amount of static files, with custom domain, and ssl, let's discuss).

Thanks for the feedback!

**Comment by skybrian** [comment]
I found this by doing a Google search for "flutter BindingBase". 

The first link doesn't work:
http://docs.flutter.io/flutter/services/BindingBase-class.html

The second link is to the page with the invalid cert:
https://docs.flutter.io/flutter/material/BindingBase-class.html

So it seems like some SEO needs to be done here - perhaps change robots.txt?

**Comment by sethladd** [comment]
Ah, thanks for the additional info. Looks like https://github.com/flutter/flutter/commit/e41c1c0b06ac47ff43e0b038407253535faf4111#diff-e0989d36b6c597940e32f43c1fa603f6 split services into foundation.

I suspect the search bots will drop the 404 links soon. At least, I hope so.

I'm more worried about the second case. Thanks for bringing that up. Will look into it.

**Comment by sethladd** [comment]
Did some experimenting with hosting the docs on Firebase Hosting. Seems to be OK. A bit more stress testing (we're uploading 17k files) but should provide a pretty good solution for SSL api docs. Stand by...

**Comment by sethladd** [comment]
Update: Opened an issue internally to unblock us. Stay tuned...

**Comment by sethladd** [comment]
Update: We are no longer unblocked. We are working to fix this now.

**Comment by sethladd** [comment]
We're now serving docs from SSL. (Big thanks to @jason-simmons for the help.)

http should auto-redirect to https

**Comment by rchick** [comment]
Can you share what you did to resolve this? I am getting the same on my own custom domain pointing to GCP storage.
