### ISSUE TITLE
Failure on `integration_tests_gradle2-linux`: could not resolve artifacts

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#38975]
Saw the following failure on the `integration_tests_gradle2-linux` shard in Cirrus

https://cirrus-ci.com/task/5073087998984192

Relevant snippet of error is captured in [this gist](https://gist.github.com/tvolkert/f3955f4ad24aa936c4aacb17ac661303).

/cc @blasten

**Comment by blasten** [comment]
Looks like JCenter was down:
```
 Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.71/kotlin-reflect-1.2.71.pom'. Received status code 504 from server: Gateway Time-out
```
I scheduled another task.

**Comment by tvolkert** [comment]
Does the tool have any retry logic built into it?  Should it (can it distinguish network failures from compiler failures)?

**Comment by blasten** [comment]
Task finished successfully: https://cirrus-ci.com/task/5691062657482752

> Does the tool have any retry logic built into it? Should it (can it distinguish network failures from compiler failures)?

We throw a `ToolExit` for any failure, but we could add the retry logic based on the error message. I wonder at what extend we should also log the Gradle `stderr`.  (There might be more network related error messages) Is this something we can add as a metadata to the crash report? cc @zanderso

**Comment by zanderso** [comment]
The tool's own network requests are retried a handful of times on network failures, but it doesn't try to parse network/download failures out of e.g. gradle crash output.

Generally, when a subcommand invoked by the tool fails, the stderr from the subcommand can either be appended to the ToolExit() message, which will show in the console and/or log file, or included in a non-ToolExit unhandled exception message, which will be sent to crash logging. We should throw a ToolExit like this if the stderr has something user-actionable in it (like wait for network issues to clear up), but we should not throw a ToolExit if the subcommand failure is due to a bug in the tool.

**Comment by blasten** [comment]
Correct. I was referring to Gradle failures specifically.

**Comment by blasten** [comment]
This is fixed now.
