### ISSUE TITLE
Failed decoding image when trying to display images from file system

### ISSUE THREAD

**Issue by spvalencia** [flutter/flutter#38981]
I'm having an issue when I try to display an image from file system.
```
Example: FileImage(File(path))

[ERROR:flutter/lib/ui/painting/codec.cc(207)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
```
Can anybody help me?

**Comment by BondarenkoStas** [comment]
@spvalencia This is a question better suited for StackOverflow (you will find help there faster), since there doesn’t seem to be anything wrong with Flutter itself, but relates to implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
For the next, please add also you ```flutter doctor -v``` output, as well as some code snippet to reproduce the error, otherwise it will be hard to help.
Also, if you found a solution already, it would be nice to post it here as well as it may be helpful to other.
