### ISSUE TITLE
Matrix4 needs a simple 2d factory constructor.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#38994]
`Matrix4` is basically useless for the regular user, without a master's degree in Math. It should have detailed documentation, or at least a link to a detailed documentation.

In special, `Container` and `AnimatedContainer` need a `Matrix4` in their `transform` parameter.

The regular user **usually** needs only translation, rotation, scale, and to define an origin for rotation/scale. So I miss a factory for these simple 2d transformations. I'd suggest:

   Matrix4.2dFrom(x, y, angle, scaleX, scaleY,  originX, originY)

**Comment by goderbauer** [comment]
Matrix4 is pulled in from another package: https://github.com/google/vector_math.dart. Documentation will need to be added over there.

**Comment by dnfield** [comment]
I think it'd be very nice to have a package to make these things easier.  I'm not sure the signature you're suggesting would be very helpful though - the order of these operations matters.

Matrix4 nearly has a builder-like interface in dart, e.g. `Matrix4.translation(Vector3(x, y, 0))..rotate(...)..scale(...)` etc, where you can specify the order of these.

I do agree this issue probably belongs in vector_math rather than here.

**Comment by marcglasberg** [comment]
@dnfield @goderbauer Just created a package to help with Matrix4:

   https://pub.dev/packages/matrix4_transform

I'd appreciate if you could give me some feedback/suggestions.
However, I have no idea how to create tests for it. It "seems" ok, by looking at its transformations.
