### ISSUE TITLE
[camera] iOS photos do not have full exif data

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39070]
In Android, I receive all Exif data for the captured photo via both `Camera` plugin (0.5.3+1) and `Image_Picker` plugin (0.6.0+17) but on iOS I receive full Exif data only from `Image_Picker` plugin, not the `Camera` plugin.
Based on what you mentioned above, I know that the reason why we still receive the orientation data is related to your fix PR which has already merged.
What I really need is the full Exif data not only the orientation. Fortunately, my app's deploy target is iOS 11+ so I'm happy to use the new callback you mentioned above.
Is there any sample code related to that in Objective-C to be able to replace it with the current approach in the Camera plugin?
Is there any roadmap for fixing the issue to have full Exit data on iOS as well?

_Originally posted by @iNima in https://github.com/flutter/flutter/issues/16587#issuecomment-522395437_

To implement the above we'd likely need to limit support to iOS 11, or only do this in iOS 11.

**Comment by mvanbeusekom** [comment]
Just adding some more details to this issue regarding the mentioned callbacks on iOS: 

- `captureOutput:didFinishProcessingPhotoSampleBuffer`: the callback currently used by the camera plugin and deprecated since iOS 11+. The iOS documentation can be found [here](https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/1778647-captureoutput?language=objc);
-  `captureOutput:didFinishProcessingPhoto`: the new callback available on iOS 11+,  includes the photo meta data (EXIF) but not supported by the camera plugin as of yet.

**Comment by mvanbeusekom** [comment]
Added the `didFinishProcessingPhoto` callback in PR flutter/plugins#3337 which will make sure EXIF data is stored on iOS 11.0 and higher.

For previous versions of iOS the orientation is still determined using the accelerometer sensors.
