### ISSUE TITLE
Text rendering fails on Strings containing unpaired surrogate

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#39114]
Repro steps:

Create a new Flutter app, and replace `main.dart` with:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String hi = 'Hi 🇩🇰';
    String shortHi = hi.substring(0, hi.length - 1);

    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(body: Center(child: Text(shortHi))));
  }
}
```

This code is flawed; `hi` ends with a surrogate pair, and removing 1 "character" make the string end with an unpaired surrogate. But why does that cause the whole rendering to fail? The same string passed to `print()` in a Dart console app prints `Hi 🇩���`

Stack trace:
```
flutter: #65     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #66     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: (elided one frame from package dart:async-patch)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderParagraph#a2e17 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: RichText ← Text ← Center ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
flutter:     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
flutter:     _InkFeatures-[GlobalKey#654d5 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
flutter:     PhysicalModel ← ⋯
flutter:   parentData: offset=Offset(184.0, 436.5) (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
flutter:   semantics node: SemanticsNode#6
flutter:   size: Size(46.0, 23.0)
flutter:   textAlign: start
flutter:   textDirection: ltr
flutter:   softWrap: wrapping at box width
flutter:   overflow: clip
flutter:   locale: en_US
flutter:   maxLines: unlimited
flutter: This RenderObject had the following child:
flutter:     text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'dart:ui/painting.dart': Failed assertion: line 3645: '<optimized out>': is not true.
```

**Comment by goderbauer** [comment]
The engine is checking whether the text is malformed and throws if it is. We may want to change that to just render something like `�` instead of throwing.

Here's the full stack trace:

```
I/flutter (31786): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31786): The following ArgumentError was thrown during performLayout():
I/flutter (31786): Invalid argument(s): string is not well-formed UTF-16
I/flutter (31786):                                                      
I/flutter (31786): The relevant error-causing widget was:               
I/flutter (31786):   Text file:///Users/goderbauer/dev/animated_size/lib/main.dart:15:44
I/flutter (31786):                                                      
I/flutter (31786): When the exception was thrown, this was the stack:   
I/flutter (31786): #0      ParagraphBuilder.addText (dart:ui/text.dart:2177:7)
I/flutter (31786): #1      TextSpan.build (package:flutter/src/painting/text_span.dart:209:15)
I/flutter (31786): #2      TextPainter.layout (package:flutter/src/painting/text_painter.dart:560:13)
I/flutter (31786): #3      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:502:18)
I/flutter (31786): #4      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:525:5)
I/flutter (31786): #5      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:597:5)
I/flutter (31786): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter (31786): #7      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
I/flutter (31786): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter (31786): #9      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
I/flutter (31786): #10     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:497:7)
I/flutter (31786): #11     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
I/flutter (31786): #12     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)

```

**Comment by mehmetf** [comment]
Customer:money is seeing this in the wild quite often. They are sanitizing text from their own data sets but they think the impact of this is potentially big. After they assess the impact, this might escalate to P1. +1 to @goderbauer 's suggestion that we should render a placeholder instead of throwing (perhaps only in no-asserts mode?).

**Comment by chinmaygarde** [comment]
This was brought up in triage and the guidance is to sanitize the potentially malformed text before it gets to the engine. This can probably be done right above the ParagraphBuilder Dart to Native interface. The replacement can be anything.

**Comment by goderbauer** [comment]
That would mean doing the fix in the `TextSpan` class just before we call `ParagraphBuilder.addText` (we need to adit if we call this from anywhere else). 

@chinmaygarde Out of curiosity, what's the rational behind pushing this up one level instead of doing it in the ParagraphBuilder?

**Comment by chinmaygarde** [comment]
> Out of curiosity, what's the rational behind pushing this up one level instead of doing it in the ParagraphBuilder?

We believe the selection of a fallback in case of validation failures is an application concern.

**Comment by Hixie** [comment]
Throwing an exception here seems like the right behaviour. We should not be accepting bad Unicode data. In general, accepting malformed Unicode is a path towards security problems. (Not necessarily in rendering, but in general.)

**Comment by Hixie** [comment]
I would recommend using package:characters to avoid splitting the string in the wrong place.

**Comment by mehmetf** [comment]
These strings might be the result of app doing splitting or (more commonly) malformed content that app does not own. One such case, that is hitting customer:money, are malformed strings in the phone contacts.

What would the reason for us not to sanitize the text in the framework? Is it performance, i.e. we don't want to sanitize *every* string?

If apps are supposed to do this, what is the right way? I see this:

```dart
return utf8Codec.decode(utf8Codec.encode(str), allowMalformed: true);
```

**Comment by chunhtai** [comment]
It may be security problem to me if the app just blindly accept corrupted data from other app. They should verify its content integrity before feed that into our widget. I think our job at framework is to crash in such case instead of accepting it silently(in production code).

not sure if this can help but the we also check for surrogate in our text painter (for other use case)
```dart
static bool _isUtf16Surrogate(int value) {
    return value & 0xF800 == 0xD800;
  }
```

**Comment by mehmetf** [comment]
Thanks @chunhtai . 

Many apps would opt to "fix" the corruption (such as showing a placeholder text) since any other option will likely cause usability issues and inconsistency with other apps ("my Contacts app can show this name, why can't my Flutter app?").

Do you or Ian have a suggestion on how to do this in a performant way? You have been dealing with String APIs on Dart longer than I have :-)

**Comment by Hixie** [comment]
By the time you have a String, it should be valid. Wherever in your system you convert from bytes to String, you should be making sure that you only do so if the incoming data is valid.

It's more likely that this problem occurs because it's possible today to manipulate a valid String in a way that turns it into an invalid one (e.g. all of the index-based APIs on String allow this trivially). Using `package:characters` should avoid most of those cases.

> ```dart
> return utf8Codec.decode(utf8Codec.encode(str), allowMalformed: true);
> ```

If your incoming data is UTF-8 then it should not be possible to end up with an unpaired surrogate unless our UTF-8 decoder is broken...

**Comment by mehmetf** [comment]
>  Wherever in your system you convert from bytes to String...

I wonder whether our method channels are doing this check... I assume the application isn't receiving contact details as bytes: https://github.com/lukasgit/flutter_contacts/blob/7a4e175c65a4cb50b688d853918406a7b7d25d2c/lib/contacts_service.dart#L22-L30

We can safely close this issue; we all agree that this isn't something Framework should magically handle. I will continue digging this with the customer and see if we can identify where these invalid strings are coming from.

**Comment by goderbauer** [comment]
Closing as per previous comment.

**Comment by dnfield** [comment]
I think that the solution chosen here is not entirely ideal. It currently involves doing a UTF-8 decode every time text is added to a paragraph, and then using a _single_ replacement character when we could be showing at least the valid part of the string. This leads to a poor user and development experience, since something like `Foo Hello, world �` becomes _just_ `�`. It also uses more processor cycles because we end up decoding the data multiple times.

I'm proposing an alternative in https://github.com/flutter/engine/pull/30956
