### ISSUE TITLE
Using an iframe from another domain causes incorrect behavior

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#39127]
## Steps to reproduce

1. Create a web app with an `iframe` that loads a Flutter for web app from another domain. (e.g. a `localhost` app with an `iframe` that loads `https://dartpad.dev/experimental/embed-new-flutter.html`)
2. Press a button that changes the state of the app (e.g. a counter app)
3. Observe that not every button press changes the state correctly.

This will not happen if the iframe is on the same domain.

An small example app is here: https://github.com/johnpryan/dartpad_slow_cross_domain and is hosted at http://jpryan.me/dartpad_slow_cross_domain/

Related to dart-lang/dart-pad#1223

**Comment by ferhatb** [comment]
Have you tried configuring CSP using meta tag on your page ?

**Comment by johnpryan** [comment]
no - I'll try that

**Comment by johnpryan** [comment]
That didn't seem to fix it - I tried allowing everything by adding `<meta http-equiv="Content-Security-Policy" content="default-src *; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: 'unsafe-inline'; connect-src * 'unsafe-inline'; frame-src *;">` to the parent page at http://jpryan.me/dartpad_slow_cross_domain/

**Comment by RedBrogdon** [comment]
@ferhatb, if CSP or some other security issue were the root cause, that would prevent one or more of the scripts from working entirely, wouldn't it? That's not the behavior we're seeing, which looks more like some kind of race/timing issue (at least as far as I can tell).

I've made a brief screen recording comparing the behavior of DartPad embedded in John's example and embedded into a page on the same domain:

https://drive.google.com/open?id=1HfhfFBDrud2rdCcjwVA9Pnp2wxSQ4vvr

When using the cross-domain iframe, the button works occasionally, typically after a long press. In the same-domain iframe, it works every time.

@johnpryan, I can't do a long press on the counter examples you've embedded at  http://jpryan.me/dartpad_slow_cross_domain/ (I believe it's triggering the tooltip too quickly). Can you either add a second button to them or drop the tooltip and rebuild/rehost?

**Comment by ditman** [comment]
Any chances anybody from Chrome can lend a hand on this one? They might have more insight in what might be triggering this behavior (note that AFAIK this is only a Chrome issue)

**Comment by ditman** [comment]
It seems disabling "Site Isolation" helps: 

**chrome://flags/#site-isolation-trial-opt-out**   (set to:  _Disabled (not recommended)_)

We can't ask users to do this because _"this disables important mitigations for the Spectre CPU vulnerability affecting most computers"_, but it seems to be the culprit. I really think we should get somebody from Chrome involved :)

_(This is the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=988577) that gave me the idea to disable that flag)_

**Comment by legalcodes** [comment]
@ditman nice catch, see also these known issues: 
https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Known-Issues

**Comment by RedBrogdon** [comment]
@ditman Wow, you're not kidding. The iframes behave identically with that flag set to disabled on my installation.

I located a DA who wrote the devsite article on site isolation:

https://developers.google.com/web/updates/2018/07/site-isolation

I'll reach out to see if I can work a little DevRel networking magic and get this looked at by someone from Chrome.

**Comment by RedBrogdon** [comment]
Actually, it looks like they may have already fixed it. I'm unable to replicate the issue with either the Canary (78) or Beta (77) builds of Chrome.

Can either of you double-check that result?

**Comment by legalcodes** [comment]
I just tried multiple examples in Canary (78), everything works fine.

**Comment by johnpryan** [comment]
Chrome 77 should be stable in [early September](https://www.chromestatus.com/features/schedule) - should we close this issue?

**Comment by legalcodes** [comment]
We should.
