### ISSUE TITLE
Engine web test harness injects non-empty title

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#39159]
The test harness injects a non-empty title, which leaks into tests. Tests should start with empty title.

See: https://github.com/flutter/engine/blob/fad38e252f0748d49471bf2e09a2eb74ea04ce0b/lib/web_ui/test/title_test.dart#L19

**Comment by pedromassangocode** [comment]
Is this still a valid issue? If I understood this right, the line mentioned in the OP starts with an empty  title as expected. 

Probably I'm wrong since the file was last edited by you to add a TODO that references this GitHub issue. 

https://github.com/flutter/engine/blob/cd516eedbca114269949c6527741bf02e0b5fd68/lib/web_ui/test/title_test.dart#L20-L53

**Comment by tugorez** [comment]
@yjbanov I'll pick this issue. Would you mind assign it to me? Thanks :)!

**Comment by Hixie** [comment]
`lib/web_ui/test/engine/platform_dispatcher/application_switcher_description_test.dart` is the file that contains this test now, FWIW.
