### ISSUE TITLE
[Sentry] Add captureMessage, and automatically send environmental information for iOS and Android platforms.

### ISSUE THREAD

**Issue by SammyO** [flutter/flutter#39208]
This is a request for two features for the Sentry library:

1. Similar to `captureException` it would be useful to have a method `captureMessage` that composes an Event with a message parameter and sends it off, rather than having to create this manually and send it through `capture`.
2. When this library is used on iOS or Android platforms, there is a lot of contextual/environmental information that can (should) be provided to events, like app version, platform, device model, etc. 

I'd be happy to submit a PR for this.

**Comment by SammyO** [comment]
There is an already open PR for part of this: https://github.com/flutter/sentry/pull/40

**Comment by maks** [comment]
LIkewise I am a *very* happy newer user of the Sentry package, but PR 40 doesnt address capturing platform data which is essential for me. 
I'd also be happy to contribute a PR for that, but @yjbanov I'm bit concerned about the number of PRs already outstanding, will there be delays in getting new PRs for the Sentry package reviewed and merged? or was the hold up just due to work in getting the recent Flutter 1.9 release out?

**Comment by maks** [comment]
Perhaps this issue should be made more explicit to ask specifically for support in sending Device context in Events per: https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/#device-context

**Comment by marandaneto** [comment]
This is in the making.

`captureMessage` is already available: https://pub.dev/packages/sentry/versions/4.0.0-alpha.1

Working on the native integrations, which is gonna send Device Contexts etc.

**Comment by marandaneto** [comment]
btw another update, we've released a Flutter integration (Prerelease) which sends the environmental information -> https://pub.dev/packages/sentry_flutter
try out and let us know if you find any issues :)

**Comment by bruno-garcia** [comment]
It's available: https://pub.dev/documentation/sentry/latest/sentry/Sentry/captureMessage.html
