### ISSUE TITLE
Flutter Web build crashed. Unable to start build daemon

### ISSUE THREAD

**Issue by Akora-IngDKB** [flutter/flutter#39213]
## Steps to Reproduce

1. flutter create --web webby
2. flutter run -d chrome

Here is the gist of my main.dart (lib). [main.dart](https://gist.github.com/Akora-IngDKB/8b26a4db7779c74c547bd85c88b0abfa)

`flutter run -d chrome
Bad state: Unable to start build daemon.                                
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)       
<asynchronous suspension>
#2      BuildDaemonCreator._connectClient
(package:flutter_tools/src/build_runner/web_fs.dart:306:30)
#3      BuildDaemonCreator.startBuildDaemon
(package:flutter_tools/src/build_runner/web_fs.dart:271:46)
<asynchronous suspension>
#4      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:143:8)    
<asynchronous suspension>
#5      ResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:156:34)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:458:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:490:18)
#8      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#22     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)      
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)  
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)        
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)   

Failed to build application for the web.`

## Logs
flutter doctor -v

[√] Flutter (Channel master, v1.9.6-pre.4, on Microsoft Windows [Version 10.0.18362.175],
    locale en-GH)
    • Flutter version 1.9.6-pre.4 at C:\flutter
    • Framework revision 17813975a9 (24 hours ago), 2019-08-24 17:06:36 -0400
    • Engine revision deca2c0da8
    • Dart version 2.5.0
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)  
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.100

• No issues found!

**Comment by jonahwilliams** [comment]
I've recently landed fixes to both error surfacing, and rolled in the latest web tooling. Could you try again on the latest master to see if you experience a similar issue?

If so, could you rerun with verbose `-v` and post the resulting logs?

**Comment by Akora-IngDKB** [comment]
``` flutter run -d chrome
Building application for the web...
flutter_tools|lib/src/build_runner/build_script.dart was not found in the asset graph, incremental builds will not work.

 This probably means you don't have your dependencies specified fully in your pubspec.yaml.

Exception: Unable to connect to Chrome debug port: 65361
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 65365

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher._connect (package:flutter_tools/src/web/chrome.dart:139:7)
<asynchronous suspension>
#2      ChromeLauncher.launch (package:flutter_tools/src/web/chrome.dart:120:12)
<asynchronous suspension>
#3      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:216:48)
<asynchronous suspension>
#4      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:159:34)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:460:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Building application for the web...                                47.8s
Failed to build application for the web.```

**Comment by jonahwilliams** [comment]
Thanks! Looks like we're failing to launch chrome. What does `flutter doctor -v` say about your workspace?

**Comment by Akora-IngDKB** [comment]
```
$ flutter doctor -v
[√] Flutter (Channel master, v1.9.6-pre.70, on Microsoft Windows [Version 10.0.18362.175], locale en-GH)
    • Flutter version 1.9.6-pre.70 at C:\flutter
    • Framework revision 4984d1a33d (80 minutes ago), 2019-08-28 17:04:07 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.100

• No issues found!
```

**Comment by jonahwilliams** [comment]
Update: I'm able to repro this locally. Looking into a fix

**Comment by rydmike** [comment]
Here is a to this case related Win10 Flutter Web issue. Starting of differently, but IMO ending up in the same end-point.

I wanted to test what @Akora-IngDKB  did in https://medium.com/flutter-community/flutter-for-the-web-deploy-to-github-da454e4bc079 article, basically just to get Flutter Web to build on a Win10 setup. 

All my attempts to build a Flutter Web app on my Win10 machine have failed so far (Windows 10 builds for Desktop works fine btw). I have tried extensively with various setups, env variables, paths etc, and googling answers, but no luck with Flutter Web on my Win 10 PC yet. So I wanted to follow along @Akora-IngDKB example to see where it would lead. My first build with his example simply said:

**flutter run -d chrome**
FileSystemException: Directory listing failed, path =
'...\code\flutter\webby\.dart_tool\*' (OS Error: The system cannot find the pathspecified.
, errno = 3)

And yes I can see that it would be an issue, since there is not even a **.dart_tool** folder in my project, created with $ flutter create --web webby, so whatever it was looking for there would not be there.

Since the code was just a copy paste test for the build in the example article, I also tried the build for it:

**flutter build web**  And it tried to build it and gave no errors, looked promising I thought.

Compiling lib\main.dart for the Web...                             72.8s
It did however not produce any .js files in the web folder that could be used, only thing in the web folder was still the index.html file.

It DID however create the **.dart_tool** folder, with a build folder containing flutter_web folder and some kind of hahscode folder name with asset_graph.json in it.

Since I now suddenly got a .dart_tool folder that it was looking for first time I tried flutter run in debug, I it tried it again and now got:

**flutter run -d chrome**
flutter_tools|lib/src/build_runner/build_script.dart was not found in the asset graph, incremental
builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
Exception: Unable to connect to Chrome debug port: 62399
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 62407
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher._connect (package:flutter_tools/src/web/chrome.dart:139:7)
<asynchronous suspension>
#2      ChromeLauncher.launch (package:flutter_tools/src/web/chrome.dart:120:12)
<asynchronous suspension>
#3      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:216:48)
<asynchronous suspension>
#4      ResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:159:34)
<asynchronous suspension>
:

So now I'm getting what looks to be the **same error** that @Akora-IngDKB reported in this issue.

Additonal questin/issue. Why did "flutter run -d chrome" not create the needed .dart_tools folder but "flutter build web" did?

---

Here are the versions used in my Windows 10 Flutter Web tests on master channel:

>flutter doctor -v
[√] Flutter (Channel master, v1.9.7-pre.21, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.9.7-pre.21 at c:\src\flutter
    • Framework revision 9f4ab273f1 (8 hours ago), 2019-08-28 20:02:08 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29025.244

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.8423

[√] VS Code (version 1.36.0)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Windows                      • Windows       • windows-x64    • Microsoft Windows [Version 10.0.17763.615]
    • Chrome                       • chrome        • web-javascript • Google Chrome 76.0.3809.100

• No issues found!

----

My Windows 10 desktop setup is running great (as far along as it is), but it would be really sweet to get the Flutter Web setup to work on Windows 10 too.

We are of course at the moment just using it for dev, tech demo and feasibility studies. So it is not critical, but I assume the intent is to get the Flutter WEB tooling to work on Windows 10 machines as well eventually. Hopefully this can help with getting the tooling to a more robust level.

**Comment by rydmike** [comment]
Wow, great, I just wanted to confirm that it works great in my setup. @Akora-IngDKB you might want to give it try too.

**Comment by Akora-IngDKB** [comment]
Yeah
Tried it out already. It's working fine now.
