### ISSUE TITLE
Bitcode on iOS should be enabled by default in our templates

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39356]
Once we have enough feedback on how this is working out, we should consider enabling bitcode by default in our templates and migrate the rest of our applications that are eligible for bitcode to bitcode.

As of this writing, Flutter Gallery is _not_ elligible because of the Connectivity library, which is not build with bitcode.

**Comment by jmagman** [comment]
What else needs to be done to make us confident enough to do the switch, @dnfield?
Our recent add-to-app customers have been shipping with bitcode enabled.

**Comment by dnfield** [comment]
The only problem I can think of is if there are plugins out there (either many or popular ones) that are not compatible with Bitcode.  

My sense is that we're stable enough, but we should probably understand the impact to users (especially new users).

**Comment by jmagman** [comment]
From https://github.com/flutter/flutter/issues/48092#issuecomment-577345215:

> When I run `flutter build ios --release` in the module, the host app can then archive successfully. When I run `flutter build ios --debug` in the module, we see the reported error on archive.
> 
> The "Run Flutter Build Script" host app script build phase should be swapping the right version of the engine based on the host app build configuration (Debug, Release), but:
> 
> 1. The plugin target (shared_preferences) is being built before the host app, so before that build phase can run.

The plugin frameworks get built before the app does.  On archive, if they have bitcode enabled, all frameworks they link on must have bitcode enabled.  So if `flutter build --debug` was last run, it will fail because the plugins are linking against the Debug version of Flutter.framework, which doesn't have bitcode enabled.  The app build phase script would have copied the Release version of Flutter.framework to the right spot, but it runs after the plugins are built, so the build fails before it even gets that far...

**Comment by jmagman** [comment]
I think as of https://github.com/flutter/flutter/pull/70224 we should try this.

> The only problem I can think of is if there are plugins out there (either many or popular ones) that are not compatible with Bitcode.

It's should be up to the plugin and pod authors to set `ENABLE_BITCODE=NO` themselves in their podspec.  All the dependencies of those specs shouldn't need to also set it.

**Comment by dnfield** [comment]
Update: Per comment in #73607 we shouldn't do this until Apple requires it, to avoid breaking anyone who depends on the current behavior.

**Comment by jmagman** [comment]
Closing this, the only bitcode work we're going to do at this point is remove it https://github.com/flutter/flutter/issues/107887.
