### ISSUE TITLE
Remove third_party checked in code form buildroot

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39532]
We should replace all of the checked in code in https://github.com/flutter/buildroot/tree/master/third_party - if necessary, we could keep custom BUILD.gn files in there for building, but we should be pulling these in as `DEPS` the way we do with other third party sources.

This has a couple challenges:

1. We've modified all the libraries in there at some point except for expat. Some of those modifications are to build rules, and some are to presumably pull in new files (e.g. https://github.com/flutter/buildroot/commit/bc8826aab0fc4f7e17b21f64dec4c8a28ea42e3e)
2. Pulling in updated deps may cause new breakages on systems we don't have coverage for until pretty late in the game.

/cc @chinmaygarde @jason-simmons @iskakaushik

**Comment by dnfield** [comment]
related: https://github.com/flutter/flutter/issues/17780

**Comment by godofredoc** [comment]
All the repos have been created. Please let me know if we will need initial imports with history.

**Comment by jason-simmons** [comment]
@godofredoc I'd like to initialize the libpng repository to this commit:

https://skia.googlesource.com/third_party/libpng.git@386707c6d19b974ca2e3db7f5c61873813c6fe44

See https://github.com/flutter/flutter/issues/76079

**Comment by godofredoc** [comment]
This is complete please take a look at: https://flutter.googlesource.com/third_party/libpng

**Comment by godofredoc** [comment]
Keep it open for the remaining projects.

**Comment by cbracken** [comment]
It'd be pretty nice if we could get to a state where we're maintaining pristine copies from upstream to make it easier to cleanly roll for security updates etc.

Based on a quick survey of local patches since import to the buildroot repo, it looks like:
* expat: No patches since initial import
* fontconfig: Initial import + some additional headers (though maybe just missed in the initial import since they occurred soon after).
* libxml: Includes one code patch for ICU compatibility.
* zlib: Fair number of patches, particularly around angle.

These were all initially sourced from Chromium's copies. I'm not sure how much patching they did vs upstream, but it would be kind of nice to be using a clean copy of upstream and authoring our BUILD.gn files and any build-related scripts/tooling under `secondary` to keep our copies of the third-party libs pristine. That doesn't cover local patches we've made but not submitted upstream, though I suppose we could pretty easily whip up some tooling that would allow us to maintain and apply patches in secondary.

If we can't get to that state, or if there's a ton of chromium patching, it'd be nice to at least be using a clean copy of chromium's copies.

**Comment by cbracken** [comment]
Expat is now migrated. Migration happened in https://flutter-review.googlesource.com/c/third_party/expat/+/12700, deletion in flutter/buildroot#445, buildroot roll/update in flutter/engine#25683.

**Comment by godofredoc** [comment]
Closing this issue as all the third party repositories have been created.

**Comment by chinmaygarde** [comment]
> Closing this issue as all the third party repositories have been created.

Setting up the repos is only part of solving the issue.

The following repos are still checked in:
* [`//third_party/fontconfig`](https://github.com/flutter/buildroot/tree/430b57c643883e6090b5af09faddd8048efee57c/third_party/fontconfig)
* [`//third_party/libxml`](https://github.com/flutter/buildroot/tree/430b57c643883e6090b5af09faddd8048efee57c/third_party/libxml): 
* [`//third_party/zlib`](https://github.com/flutter/buildroot/tree/430b57c643883e6090b5af09faddd8048efee57c/third_party/zlib)

The mirrors for these repos are bare ([libxml](https://flutter.googlesource.com/third_party/libxml/), [fontconfig](https://flutter.googlesource.com/third_party/fontconfig/), [zlib](https://flutter.googlesource.com/third_party/zlib/)) at this time.

**Comment by chinmaygarde** [comment]
Removing `infra` tag (thanks @godofredoc) as assigning for re-prioritization.

**Comment by chinmaygarde** [comment]
The bare repos are being initialized to the current contents of the Flutter buildroot ([fontconfig](https://flutter-review.googlesource.com/c/third_party/fontconfig/+/24222), [libxml](https://flutter-review.googlesource.com/c/third_party/libxml/+/24223), [zlib](https://flutter-review.googlesource.com/c/third_party/zlib/+/24224)). Once setup, we can tackle how each dependency must be updated (and the cadence) on a case-by-case basis.

IMO, we should just start from scratch and deal with the fallout.
