### ISSUE TITLE
I am having difficulty running flutter commands

### ISSUE THREAD

**Issue by awesome-urch** [flutter/flutter#39647]
## Steps to Reproduce

1. Run "flutter doctor"
2. In fact, error occurs on all flutter commands

## Logs

```
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_tools depends on build_test >=0.10.7 which requires SDK version >=2.2.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
```

**Comment by GaspardMerten** [comment]
Did you try to upgrade Flutter?

You can do it through flutter version vX.X.X

I'm currently working on v1.7.4 and no issue so to switch to 1.7.4 use:

`flutter version v1.7.4`

**Comment by glancer000** [comment]
This should be a question for https://stackoverflow.com/

**Comment by BondarenkoStas** [comment]
@awesome-urch The error text clearly advices you to upgrade your Dart SDK to at least 2.2.0. Please report if upgrading solves your issue. 
And right, this is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
