### ISSUE TITLE
Auto-complete text field as a material widget

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3969]
Spec'ed at https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field
- [ ] full width
- [ ] inset
- [ ] full-width inline
- [ ] inline auto-complete

**Comment by eseidelGoogle** [comment]
customer: mulligan reached out to indicate this is a blocker for their application (due to their customer having many complex-but-auto-completable tags, etc. to input).

**Comment by abarth** [comment]
We should talk with them to figure out what they're looking for here.

**Comment by abarth** [comment]
I don't think there's an autocomplete widget in the material spec per se, so we'll need a bit more input.

**Comment by abarth** [comment]
Nevermind.  If I could read, then I'd have seen the link above.  Nevermind.  :)

**Comment by eseidelGoogle** [comment]
customer: mulligan notes that this is a blocker because their server side will reject invalid values.  i.e. autocompleted values are the only allowed entries into their form.  However they have way too many of them for a dropdown to be the correct UI.  If we have something simple to unblock their development that could also work.  Happy to put folks in touch offline.

**Comment by eseidelGoogle** [comment]
I saw mocks from customer: mulligan, and their mocks only use the "inset" mode from the MD spec.

**Comment by eseidelGoogle** [comment]
I've split customer:muligan's needs off into https://github.com/flutter/flutter/issues/8342.

**Comment by tvolkert** [comment]
This has been built internally at Google with plans to open source it.  Closing since that would mean that it wouldn't live in the framework.  Feel free to re-open if needed.

**Comment by barry-schneider** [comment]
Has auto-complete field been released yet?

**Comment by tvolkert** [comment]
Not yet again.  /cc @DaveShuckerow

**Comment by jaumard** [comment]
Any idea when we it will be @tvolkert @DaveShuckerow  ? Even if it's an external plugin for now it will still be really useful :) thx

**Comment by hundeva** [comment]
Any update? It's been a while since this was "built internally at Google". 🙂

**Comment by eseidelGoogle** [comment]
@DaveShuckerow or @mehmetf would know.

**Comment by mehmetf** [comment]
This is now available in the framework as https://docs.flutter.io/flutter/material/showSearch.html

**Comment by mehmetf** [comment]
@jaumard Android components have grown quite large over the 10 years or so that Android existed. Flutter core framework cannot provide the entire list of UI components that Android provides. We rely on the community to provide functionality as needed.

What Flutter core has signed up for is supporting the Material design language. Inline auto-complete that offers multiple items to choose is **discouraged** in Material design language and thus is not provided by the core team. The supported patterns are full screen autocomplete and inline _single item_ autocomplete.

**Comment by mehmetf** [comment]
I totally agree that there are use cases where the multi-item inline autocomplete is useful. I am just clarifying what you can expect from the core Flutter team. Anything outside of Material core and iOS core widgets is evaluated on a case by case basis and supplied only if there's sufficient interest **and** no one else has stepped up to provide it. We get _many requests_ for widgets like this and rely on the contributions of others to fill the other gaps.

This is the only search pattern recommended by Material team. There's no separate auto-complete pattern as of today: https://material.io/design/navigation/search.html

**Comment by freezy** [comment]
Thanks for the link!

I understand your situation about having to decide how to allocate resources. What's weird about this case is that the Material team seems to deprecate stuff without really providing alternatives. 

Also, I couldn't find any history of what was going on. Content like the auto-complete that was obviously part of the page linked in the issue has just disappeared. Wouldn't it be better to keep deprecated guidelines and mark them as such instead of just removing them?
