### ISSUE TITLE
des 加密算法

### ISSUE THREAD

**Issue by huifeidemao** [flutter/flutter#39733]
你好，我们app 新的版本使用的flutter开发。因为我们的接口是使用des 加密的，目前我没有找到可用的des 方法库或者API  ，需要你们的帮组

**Comment by BondarenkoStas** [comment]
@huifeidemao Please check https://pub.dev/packages/flutter_des if I correctly understood your question.

For later, please use english while writing and issue, it's not a good practice to force people to use translator in case they don't know the language an issue is written with, and might scare away potential helpers.
Also, this is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options.
Closing, as this is not an issue report, if there are any problems, feel free to open a new issue.
