### ISSUE TITLE
Is there anyway to get  a thumbnail of a video file?

### ISSUE THREAD

**Issue by atheist1** [flutter/flutter#39730]
Is there anyway to get  a thumbnail of a video file in both IOS and android
i tried two methods.
1.use thumbnail plugin 
but its only support for android
2.use video_player plugin 
its seems too many video_player in a single page caused my apps crashed

**Comment by BondarenkoStas** [comment]
@atheist1 You are correct about the first method. I would advise to open a new issue with proposal for developing a thumbnail plugin for iOS.
And would advise you to open a new issue about the second method with more detailed information.

The question about other ways to get a thumbnail of a video is better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, there you will find help faster. See also https://flutter.dev/community for support options.
