### ISSUE TITLE
Manually Trigger Hot Reload/Full Restart with HTTP/CURL requests to the Observatory server

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#39760]
I am trying to develop a UI to control the project development and workflow but I am not able to trigger Hot Reload or Restart.

1. Is there a way of manually triggering the **Hot Reload/Full Restart** using **HTTP/CURL** request to the observatory dart server on http://127.0.0.1:8888/ when running the command ```flutter run --observatory-port 8888 --disable-service-auth-codes lib/main.dart```?

2. Is there a way of manually uploading source files to the Dart VM?

**Comment by zanderso** [comment]
The observatory server speaks a json-rpc protocol defined here: https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md.

The Dart package https://pub.dev/packages/vm_service is a library that wraps up interacting with the observatory server in a nice Dart API.

Hot reload and lots of other things can be triggered this way.

Closing since there is no action to take.
