### ISSUE TITLE
Enable bitcode on the pods targets when adding plugins

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39793]
Related to https://github.com/flutter/flutter/issues/39356

When we add a plugin, we should enable bitcode by default (provided the plugin supports bitcode).

/cc @jmagman - not sure if you're already covering this elsewhere.

**Comment by jmagman** [comment]
Hopefully this doesn't cause too many problems with plugins that do need bitcode off, but never needed to specify it in their podspec since that was Flutter's default.
May be worth an audit to the top ~50 plugins and see if that's the case anywhere.

**Comment by dnfield** [comment]
In theory, we should be able to check any binaries shipped with the plugin for bitcode, right?  Either using `otool` or `bitcode_strip` and comparing the output with the input.  But neither of those is especially nice.

**Comment by jmagman** [comment]
This might be tricky for another reason.

From https://github.com/flutter/flutter/issues/48092#issuecomment-577345215:

> When I run `flutter build ios --release` in the module, the host app can then archive successfully. When I run `flutter build ios --debug` in the module, we see the reported error on archive.
> 
> The "Run Flutter Build Script" host app script build phase should be swapping the right version of the engine based on the host app build configuration (Debug, Release), but:
> 
> 1. The plugin target (shared_preferences) is being built before the host app, so before that build phase can run.

When the project is built in Release, the plugin frameworks get built first.  If they have bitcode enabled, all frameworks they link on must have bitcode enabled.  So if `flutter build --debug` was last run, it will fail because the plugins are linking against the Debug version of Flutter.framework, which doesn't have bitcode enabled.  The app build phase script would have copied the Release version of Flutter.framework to the right spot, but it runs after the plugins are built, so the build fails before it even gets that far...

**Comment by jmagman** [comment]
I think as of https://github.com/flutter/flutter/pull/70224 we should try this.
