### ISSUE TITLE
RenderStack object was given an infinite size during layout

### ISSUE THREAD

**Issue by savadodesigns** [flutter/flutter#39802]
flutter: The malformed error has 2 summaries.
flutter: Summary 1: RenderStack object was given an infinite size during layout.
flutter: Summary 2: RenderStack object was given an infinite size during layout.
flutter:
flutter: This error should still help you solve your problem, however please also report this malformed error
flutter: in the framework by filing a bug on GitHub:

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it's not clear if this is a bug in user code, a bug in the framework, or something else entirely.

Please feel free to re-open if you can add the following information:

The version of Flutter you're using
The output of ```flutter doctor -v```
The full exception you see
A minimal reproduction that leads to this exception.

If you think it's an implementation problem, better ask for help on StackOverflow as help there may come faster. See https://flutter.dev/community for support options.

Also, in similar issue the problem was that the box constraint height or length was set to infinity, which leads to the infinite size, if it may be helpful.
