### ISSUE TITLE
how to show emojis on keyboard instead of text when button is pressed

### ISSUE THREAD

**Issue by jitenders859** [flutter/flutter#39830]
I am working on a chat application and want to show keyboard with emojis instead of showing characters on emulator keyboard when a button is pressed.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options.

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!

**Comment by jlavyan** [comment]
This is not only question there are no way to do that without custom package such as image_picker .... which is not acceptable since we need standard emoji keyboard
