### ISSUE TITLE
flutter 打包ios包，审核时一直被拒，提示说是app 一直停留在启动页

### ISSUE THREAD

**Issue by huifeidemao** [flutter/flutter#39863]
我直接运行是没有问题的，生产环境的证书配置也是没有问题的。打包上线的就被appstore拒绝。拒绝的信息如下，后台我咨询确认了一次，他们的意思就是应用停留在启动页。
Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app when reviewed on iPhone and iPad running iOS 12.4 on Wi-Fi.

Specifically, your app stays at the splash screen after launch.

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide.

For a networking overview, please review About Networking.

**Comment by BondarenkoStas** [comment]
@huifeidemao This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but relates to AppStore review policies and the app implementation. See https://flutter.dev/community for support options. Closing as it's not an issue report.
If you disagree, feel free to open a new issue, providing more details about the app. 
For future, please use English while describing your issue as it's generally accepted, not that many people who could help are speaking Chinese and it can scare them away.

**Comment by wangyu204** [comment]
打包之前运行下如下命令就可以了  flutter build ios --release
