### ISSUE TITLE
Year picker support

### ISSUE THREAD

**Issue by serendipity1004** [flutter/flutter#39961]
Currently `showDatePicker` only allows users to pick a full date e.g. year, month and day. However, sometimes you want to enforce that users only pick specific sections of date for example just year. I know year picker is available as a widget right now but there is no explanation on how to use this solely in showDatePicker.

I think it would be very useful if we can specify what part of date we want users to pick. Maybe something like

```
DatePick.year
DatePick.yearAndMonth
DatePick.all
```

meanwhile, it would be great if anyone could provide example on just using year picker and getting year input only.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by Basher7** [comment]
**After upgrading flutter stable v1.12.13+hotfix.9 to v1.17.0 showing 'YearPicker' is deprecated and shouldn't be used.** 
**I didn't find anything. Could you please share any suggestion for only year pick.**

**Comment by ranghetto** [comment]
Still a needed feature

**Comment by darrenaustin** [comment]
While I understand the desire for this feature, the current implementation is based on the [Material Design spec](https://material.io/components/pickers) which doesn't really address this need, as it is all based on selecting a specific day. I will pass this feedback on to the design team for consideration.

It would be tricky to add some of these restrictions given the current UI. For example the `yearAndMonth` case would be probably require a completely new UI as it currently just allows navigation of months, but not selection. The grid shown for each month is setup for selecting days not months. In addition, there is now a text input mode that would need completely different validators and prompts to only allow the user to enter just a year or month. Not unsolvable issues, but it would need a design.

That said, it might be possible to extract out the year selection UI as a stand alone widget similar to the previous YearPicker so that apps could use it to build their own picker for this.

**Comment by darrenaustin** [comment]
I just landed PR #71061 that exposed the `YearPicker` used by the Date Picker as a public widget. You should be able to use it to build a UI for just selecting a year.
