### ISSUE TITLE
How to solve the problem that android can not pop up the soft keyboard after accessing the physical keyboard.

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#39978]

**Comment by BondarenkoStas** [comment]
@lyqiai Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Please provide your ```flutter doctor -v``` output.

Also it may be a good question to StackOverflow, in case the issue is related to implementation.

**Comment by BondarenkoStas** [comment]
Closing as asked
