### ISSUE TITLE
关于溢出问题 (About overflow issues)

### ISSUE THREAD

**Issue by z624821876** [flutter/flutter#40144]
在Row中放多个Text，但是数据不固定，有可能会溢出，怎么提前计算Text的宽度，控制加入Row中的Text个数

**Comment by martinjeret** [comment]
(Google translate) "Put multiple Text in Row, but the data is not fixed, it may overflow, how to calculate the width of Text in advance, control the number of Text added to Row"

@z624821876, please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they’re enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github “gist” - https://gist.github.com/.
Also, please provide your `flutter doctor -v` output.

For the future, please use English, while filing your issue, because potential helpers, who don't know Chinese, can miss it.

**Comment by SBNTT** [comment]
What about wrapping the `Text` widget which overflow into a `Flexible`one ?

**Comment by z624821876** [comment]
example:
![image](https://user-images.githubusercontent.com/8405670/64660578-99e8a900-d473-11e9-8056-018d015264b0.png)
The number of elements in the red box is not fixed, the elements on both sides of the red box are fixed!

**Comment by z624821876** [comment]
> example:
> ![image](https://user-images.githubusercontent.com/8405670/64660578-99e8a900-d473-11e9-8056-018d015264b0.png)
> The number of elements in the red box is not fixed, the elements on both sides of the red box are fixed!
