### ISSUE TITLE
My notebook freezes when I try to update dart

### ISSUE THREAD

**Issue by IL7Games** [flutter/flutter#40176]
Hello,

I've been having some problems developing applications with Flutter using Solus.
Well .. the first problem happened today. Saw that the new version of dart came out and so I decided to upgrade here. However, the terminal does not leave this part and my notebook freezes: "Building flutter tool..."
I can not upgrade, this operation exceeds my 3,8 gigabytes, I do not know what to do!

My second problem is when I try to run the "flutter run" along with an open editor.
When it arrives at the "Running Gradle task 'assembleDebug'" part, the notebook also freezes!!
(Note: I am not using an emulator, I am using a physical device)

This is horrible and I have no idea how to solve it! Can someone give me a light ?!

(Note2: OS: Solus 4.0 Fortitude; GNOME: 3.32.1; RAM memory: 3,8; Processor: Intel® Core™ i3-4005U CPU @ 1.70GHz × 4; Intel® Haswell Mobile;)

**Comment by MichalTorma** [comment]
I'd recommend you to allocate swapfile in Linux for this operation and be patient while it's building. (you can read about it for example [here](https://wiki.archlinux.org/index.php/Swap#Swap_file)).

**Comment by henriquearthur** [comment]
The operation is using all your RAM that's why it freezes. Apparently you don't have swap memory, so I recommend the same as @MichalTorma, allocate some swapfile. The operation will be slow but it will finish eventually. This is not related to Flutter/Dart itself.

As your notebook only has 4GB RAM, I recommend you use another DE like xfce or lxde because it is less RAM-consuming than GNOME, that will probably improve overall performance.

**Comment by IL7Games** [comment]
I did what @MichalTorma recommended and it worked, I really have to be a little more patient @henriquearthur ..

Thanks and sorry for the delay in replying!
