### ISSUE TITLE
Rename PlatformView to PlatformBridge or some such

### ISSUE THREAD

**Issue by xster** [flutter/flutter#40283]
Discussed in Discord but we never did it. 

PlatformView is a misnomer since a- it collides with the PlatformViewFactory's platform view which is entirely a different thing and a real view. b- this shell/common/platform_view are not views and don't have the same lifecycle as actual views. It's long lived and shouldn't be named with something that's conflicting.

**Comment by chinmaygarde** [comment]
`PlatformViewFactory` is in the embedder implementation and the `PlatformView` is in the core engine. `PlatformView` is still arguably a misnomer but not because its name collides in-part with a component in another target. Note that we have many "surface" abstractions at many layers of the API for instance.

For context, these components were called views because they tied into the WSI to provide render surface to rasterizer. The responsibilities of this component have grown since.

I want to vote against `PlatformBridge` because most components bridge to the platform but this is a private API so we can change it to whatever we want with minimal consequence.

**Comment by xster** [comment]
- bit of a nit, but I would argue the same thing even if there were Dart classes in Flutter-land called *PlatformView* (which there are). Ideally we can name things with absolute directionality that they don't have to be ambiguous regardless of perspective and where they sit to remove as much cognitive overloading as possible.
- since the embedder is the forward looking API, how about `EmbedderPlatformBinding`?

**Comment by jonahwilliams** [comment]
We're not going to rename this
