### ISSUE TITLE
all stack parsing busted in --profile builds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4030]
Turns out some builds don't include line numbers. All the code I've written that parses stacks assumes that there are line numbers.

Probably best fixed using https://github.com/flutter/flutter/issues/4021

**Comment by eseidelGoogle** [comment]
My understanding is that @rmacnak-google recently fixed Dart AOT support to include line numbers.  This should be fixed?

**Comment by rmacnak-google** [comment]
As of flutter/engine@588d6a4798f28607b1989165a782765ca4166377, all stack traces in Flutter should contain line numbers.

This bug seems to really be about the robustness of stack parsing, so I should point out that there's an open issue (dart-lang/sdk#28785) to require external symbolization of Dart stack traces in Flutter release mode, which would break all existing stack trace parsers.

**Comment by zoechi** [comment]
Is this issue still relevant?
