### ISSUE TITLE
navigator support get routing history?

### ISSUE THREAD

**Issue by KingWu** [flutter/flutter#40329]
Will plan to open the routing history? As i know, the routing history is stored as the internal state in Navigator

**Comment by adriancmurray** [comment]
@goderbauer I would do a PR for this since all it needs is a public getter for the private _history list of routes but I'm just not setup to do that right now. If someone is setup as a contributor for flutter (can do the tests, etc) this would be a nice easy addition to the NavigatorState class:

```
///Public getter for Navigator State history
  List<Route<dynamic>> get history => _history;
```

**Comment by goderbauer** [comment]
We do not want to expose the history to the world as manipulating that directly will cause problems. We are working on a new Navigator API that will allow you to provide the history directly to the navigator as a list of pages: http://flutter.dev/go/navigator-with-router

@KingWu Please provide additional information as to what your use case is for directly accessing the history.

**Comment by adriancmurray** [comment]
@goderbauer I understand that you don't want manipulation of the current Navigator which is why I just created a public getter so modifications weren't possible - just obtaining pages within the list. Navigator 2.0 looks very promising. I skimmed through it but its design seems to be related to iOS 13's new modal/card/pages design. I created my own version of that and made my own modifications on the navigator that allowed me to change the `opaque` property of my routes. This new API seems much more usable from a few points. Thanks for sharing.

**Comment by adriancmurray** [comment]
@goderbauer what if, while we wait for the new API, access was granted via an UnmodifiableListView from the dart:collection core library? 

`UnmodifiableListView<Route<dynamic>> get history => UnmodifiableListView(_history);`

**Comment by goderbauer** [comment]
We don't really want to add hacky API. Once in place, they are hard to remove even when a better alternative exists.

**Comment by adriancmurray** [comment]
Fair enough. I guess having the public `history` getter and the future `pages` list could become a headache. One last question for you or @Hixie , any ETA on the new API? My guess is Flutter 2.0 is the goal, and if you're thinking of doing yearly updates on the framework that would probably be coming up. Though, these are all my best guesses.

**Comment by Hixie** [comment]
You can follow along at: https://github.com/flutter/flutter/issues/45938

**Comment by lijian2011** [comment]
I need to know if there is an interface in the history that I want to pop, and then call pushNamedAndRemoveUntil, because I'm not sure if there is an interface in the history

**Comment by Faiyyaz** [comment]
We want routing history to know if i am on a chat page in my app and i want to get the data of the current page so that if a notification comes i can check if the notification is coming for same person message or is it some different person so that i can decide whether to show notification inside tray or not.
