### ISSUE TITLE
Aspect ratio broken in image_picker

### ISSUE THREAD

**Issue by autolainen** [flutter/flutter#40334]
I am using https://pub.dev/packages/image_picker  plugin:
```
                ImagePicker.pickImage(
                        source: ImageSource.camera,
                        maxHeight: 1024,
                        maxWidth: 1024)
                    .then((imageFile) { ... })
```
By business requirements I don't need photos with high resolution modern cameras usually make. The plugin resizes the original image and after that aspect ratio of the image appears to be broken. The same for gallery source. Such behaviour is on iOS only.

**Comment by Xavjer** [comment]
Having the same issue,

it comes from FLTImagePickerImageUtil.m
`  // Scaling the image always rotate itself based on the current imageOrientation of the original
  // Image. Set to orientationUp for the orignal image before scaling, so the scaled image doesn't
  // mess up with the pixels.
  UIImage *imageToScale = [UIImage imageWithCGImage:image.CGImage
                                              scale:1
                                        orientation:UIImageOrientationUp];

  UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, height), NO, 1.0);
  [imageToScale drawInRect:CGRectMake(0, 0, width, height)];`

This will may the image and then apply the width/height to it. 
If it is not rotated, it is working fine. If it is rotated, then width/height must be inverted, otherwise it inverts the aspect ratio

**Comment by Xavjer** [comment]
Created PR https://github.com/flutter/plugins/pull/2060

**Comment by cyanglaz** [comment]
@autolainen Could you explain what did you mean by aspect ratio is broken? What is the expected behavior and what is the behavior you've got?

**Comment by autolainen** [comment]
Hello Chris!

When picture is taken in portrait orientation on iOS and one or both parameters maxHeight and maxWidth specified - the result image aspect ratio is incorrect. The correct behavior is, obviously, that the aspect ratio would be preserved.

Please feel free to contact me in case further explanations needed.

Anton

>Среда, 25 сентября 2019, 7:27 +03:00 от Chris Yang <notifications@github.com>:
>
>@autolainen Could you explain what did you mean by aspect ratio is broken? What is the expected behavior and what is the behavior you've got?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Антон Чумак

**Comment by YAPPDEF** [comment]
Same here. On iOS devices, the aspect ratio is broken as soon as I add a maxWidth or maxHeight.

**Comment by chwo** [comment]
There is a duplicate issue for this: #40831

Both issues were fixed by https://github.com/flutter/plugins/pull/2070, so this issue can be closed.

**Comment by BondarenkoStas** [comment]
Thank you @chwo! Closing the issue, please try it on master.
