### ISSUE TITLE
`firebase_core` not found for flutter_web (Flutter 1.9)

### ISSUE THREAD

**Issue by ptyagicodecamp** [flutter/flutter#40360]
I upgraded my flutter to 1.9, and trying out flutter-web for an existing project. Got stuck at "firebase_core" is not found error  anyone experiencing the same issue ? Here's error:
```
i$ flutter run -d Chrome
Launching lib/main.dart on Chrome in debug mode...
Skipping compiling flutter_widgets|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
firebase_core|lib/firebase_core.dart
```

**Comment by yjbanov** [comment]
Existing Flutter plugins do not yet work on the Web. One workaround is to create an abstraction over Firebase and use different implementations, one for mobile (such as firebase_core) and one for web (such as [firebase](https://pub.dev/packages/firebase)).

/cc @mit-mit this is another signal that we need to teach pub to surface which platforms are supported by which plugins. The issue will become even more acute with the Web and desktop in the mix.

**Comment by AppleEducate** [comment]
Here is what i am doing to use the native SDKs: https://stackoverflow.com/a/57979044/7303311

Here s the article i did: https://medium.com/@rody.davis.jr/how-to-build-a-native-cross-platform-project-with-flutter-372b9e4b504f

You have to use conditional imports. 

If you want to use Firebase auth on web and mobile i created a package that does this for you with the official SDKs: https://pub.dev/packages/fb_auth

Let me know if you have any questions

**Comment by ptyagicodecamp** [comment]
Thanks Rody for the pointers. I see https://pub.dev/packages/fb_auth uses
Bloc, and example is also based on Bloc pattern. Could you explain how
could I use this plug-in for Provider pattern ?

**Comment by AppleEducate** [comment]
The bloc part is purely optional and not needed to use the plugin, I just include it to simply all the logic usually around auth. 

You can call the plugin directly with FBAuth.login() and other calls!

**Comment by ptyagicodecamp** [comment]
Cool. Thank you!

**Comment by ptyagicodecamp** [comment]
@AppleEducate I got Firebase auth working on web. However no luck using `cloud_firestore` for Flutter web. It seems to have dependency on `firebase_core|lib/firebase_core.dart`, which is causing it to fail.

**Comment by AppleEducate** [comment]
cloud_firestore is just for mobile, on web everything is in firebase, including firestore.

You will just import cloud_firestore on the mobile side. I will release a blog post soon

**Comment by ptyagicodecamp** [comment]
@AppleEducate I've written a plugin wrapper for mobile and web Firebase auth [here](https://github.com/ptyagicodecamp/flutter_cookbook/tree/widgets/flutter_widgets/lib/plugins/firebase). Usage example is in [this project](https://github.com/ptyagicodecamp/flutter_cookbook/tree/widgets/flutter_widgets/)

I've created a generic user say [`MyAuthUser`](https://github.com/ptyagicodecamp/flutter_cookbook/blob/widgets/flutter_widgets/lib/plugins/firebase/change_notifier.dart#L14) in wrapper to deal with web and mobile since both returns different data types (AuthUser for web, and FirebaseUser for mobile). Do you have a better idea to deal with this ?

**Comment by ditman** [comment]
Wow! This is great! Thanks for all this work! 

I'm sure @collinjackson is going to love this too!

**Comment by AppleEducate** [comment]
I also created a wrapper 😅 

fb_auth that does the same thing! 
https://pub.dev/packages/fb_auth

**Comment by Jeremywhiteley** [comment]
@ditman @collinjackson   We are using @AppleEducate 's fb_auth https://pub.dev/packages/fb_auth  in our web and mobile app.  So far it works great.  Hoping to get Firestore, Firebase Storage, and Functions working soon with both mobile and web.   Any thoughts, tips, or updates on these?   I know @AppleEducate is working on those too and also trying to get Google signin working for web.

**Comment by ptyagicodecamp** [comment]
> I also created a wrapper 😅
> 
> fb_auth that does the same thing!
> https://pub.dev/packages/fb_auth

@AppleEducate I created a wrapper for [fb_auth](https://pub.dev/packages/fb_auth) with intention to add missing functionality around firestore, google-signin for web etc. Do you have an ETA for this to be included in  [fb_auth](https://pub.dev/packages/fb_auth). I would rather prefer waiting if it's around the corner :)

**Comment by AppleEducate** [comment]
Oh yes! I’m planning on adding all the methods that are shared! And probably a week. 

Feel free to make a PR too, I can add what you have so far 👍🏼

**Comment by ditman** [comment]
Hello all!

We still haven't landed on the *exact* approach on where to put the code for the web implementations of plugins, but it is likely that the current approach we're using will change a little bit.

There's currently talks on going to a "Federated" model, where plugins can be split across multiple packages, and any plugin author can "endorse" 3rd party implementations for platforms that they can't (or don't want to) build.

Here's a document discussing the federated approach: https://flutter.dev/go/federated-plugins . (The technical approach will result familiar because @hterkelsen did something similar to what is being proposed there for the current plugins for web implementation!)

I think the model above fits pretty well what we need to do for the Flutter for web plugins, but the plugins team is taking some time to make sure the transition is smooth for everybody (tooling, maintainability, currently open PRs, the works!)

As soon as the federated approach solidifies enough, we can answer the question of "How can I help you build this?". We'll probably prepare a writeup on "How to write plugins for Flutter for web", and push some of the ones that we've been working on so far (like the url_launcher or image_picker). 

In the meantime, we'll have to live with the extra friction that is well documented on this ticket (and probably others). Hang in there!

Again, thanks for all the contributions! Keep them coming!

**Comment by kroikie** [comment]
@ptyagicodecamp

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1128. Any further collaboration will be done there.
