### ISSUE TITLE
`flutter upgrade` should invoke `flutter update-packages`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#40382]
If a flutter developer runs `flutter upgrade` and there was a dependency change in one of the `pubspec.yaml`'s in the flutter repo, their pub cache will reflect the old state, not their current, upgraded state. While we're fast forwarding their git repo and pre-caching all artifacts, we should also call `flutter update-packages`.

**Comment by Hixie** [comment]
This would slow down the upgrade significantly and most people aren't going to benefit since most people don't care about these `pubspec.yaml`s. For most people, we'll run `pub get` automatically when we need to. It only really matters for `flutter analyze --flutter-repo`, which should be covered by https://github.com/flutter/flutter/issues/37439.
