### ISSUE TITLE
CameraPlugin: The new embedding does not support the old FlutterView.

### ISSUE THREAD

**Issue by PoojaB26** [flutter/flutter#40423]
Trying to integrate a FlutterModule with plugins with an existing Android codebase with the new `io.flutter.embedding.android.FlutterActivity` instead of `io.flutter.app.FlutterActivity`.

When using the `ShimPluginRegistry` to register with `GeneratedPluginRegistrant.registerWith()`, GoogleMapsPlugin & SharedPreferencePlugin works, but adding CameraPlugin (io.flutter.plugins.camera) crashes the Android app.

The error is
```
The new embedding does not support the old FlutterView.
```

From the codebase of `Camera.java` class, it is evident that `io.flutter.view.FlutterView` is used, what should be the workaround here?

`Flutter Doctor`

```
[✓] Flutter (Channel master, v1.10.2-pre.73, on Mac OS X 10.14.6 18G95, locale en-IN)
    • Flutter version 1.10.2-pre.73 at /Users/pooja/flutter
    • Framework revision a7cfdbd3f3 (15 hours ago), 2019-09-12 19:13:42 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/pooja/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 38.1.3
    • Dart plugin version 191.8369
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available
```

**Comment by janmoppel** [comment]
Hello @PoojaB26!

Thank you for posting the issue!
Can you please provide an output of the `flutter doctor -v` command as well? 

Also, Flutter community on StackOverflow is very active and helpful. Maybe you can post your question there too, so that it can be addressed there as well.

Thank you.

**Comment by PoojaB26** [comment]
This issue is mostly regarding the `addToApp` APIs that the Flutter Team is working on, currently.  It seems like it's an API level issue, rather than the usage of the API, so I didn't ask in StackOverflow. I can probably find a hacky way to solve this, but I'm guessing this needs to be fixed from API level side.

**Comment by xster** [comment]
@amirh @matthew-carroll we have another FlutterView accessing plugin here. 

It looks like it's using it to create a SurfaceTexture to feed its texture ID back into Flutter once populated with the viewfinder video. 

https://github.com/flutter/plugins/blob/05c25052c5dca98c411da925196d7eff766e9dd7/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java

I think we can probably solve this one (once we have the parallel new API path in the plugin) to use FlutterPlugin.getFlutterEngine.getRenderer.createSurfaceTexture instead of Registrar.view.createSurfaceTexture. 

@matthew-carroll might be worth making this one one that you migrate this quarter as a demo for the big migration.

**Comment by matthew-carroll** [comment]
I'm pretty sure I already migrated camera months ago and proved that we don't need a View. We can do this with the FlutterRenderer.

**Comment by xster** [comment]
I think we're saying the same thing.

**Comment by vitor-gyant** [comment]
@matthew-carroll @xster What should be done meanwhile to fix this ?

**Comment by matthew-carroll** [comment]
@vitor-gyant what's the specific issue that you're running into?

**Comment by vitor-gyant** [comment]
@matthew-carroll I've migrated my app2app code to use the new embedding package. Everything went well until I realize the plugins were not registered. After some research I got to the following code:

```
        ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(
                instance);

        GeneratedPluginRegistrant.registerWith(shimPluginRegistry);
```

Which crashes when register the Camera plugin with:

`The new embedding does not support the old FlutterView. `

I've checked the latest camera plugin version and it still references the view:

```
  public static void registerWith(Registrar registrar) {
    CameraPlugin plugin = new CameraPlugin();
    plugin.maybeStartListening(
        registrar.activity(),
        registrar.messenger(),
        registrar::addRequestPermissionsResultListener,
        registrar.view());
  }
```

Thanks,

**Comment by matthew-carroll** [comment]
There are 2 efforts that are underway to resolve this. First, Flutter's 1P plugins are being extended to support the new embedding. Second, a new version of `GeneratedPluginRegistrant` will be introduced that knows how to register old and new plugins, together.

At this juncture, to use the new embedding with plugins, you probably need to manually register plugins. You'll need to add plugins that have been extended like the following:

```
flutterEngine.getPlugins().add(myUpdatedPlugin)
```

For the old plugins, you'll need to register them with the `ShimPluginRegistry` one-by-one.

The reason you can't use the `GeneratedPluginRegistrant` in your particular situation is that it will attempt to register the old version of the Camera plugin against the new embedding, which fails because the old `FlutterView` no longer exists. By manually registering each plugin, you can avoid registering the old version of the Camera plugin.

The Camera plugin has been extended on master:
https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java#L28

However, master is not a stable branch. It is not recommended that one ship code against master.

In the meantime, if you need the Camera plugin, and working with master is not acceptable, then you'll have to go back to the old embedding until plugin extensions stabilize.

**Comment by vitor-gyant** [comment]
@matthew-carroll Just another questions, how easy is to understand which of the plugins I use were already migrated to the new embedding ?

**Comment by matthew-carroll** [comment]
If you see a class that `implements FlutterPlugin` that means it's using the new embedding.

**Comment by vitor-gyant** [comment]
@matthew-carroll Got it. Do you think we could create a new page on the wiki to keep track of already migrated plugins and others where the community could help ? I'm not sure where to discuss this kind of suggestions. Thanks.

**Comment by matthew-carroll** [comment]
There is a room on the contributors Discord server for the ecosystem where the community can offer to help.

@amirh can you comment further on organizing community involvement? Also, do you think a member of the ecosystem team can update the Wiki migration guide with the latest team preferences for where the files should go and how they should be named?

**Comment by vitor-gyant** [comment]
@matthew-carroll This issue seems to be solved. Is there any further action ?

**Comment by matthew-carroll** [comment]
I'm not sure. I'll defer to @amirh @mklim or @bparrishMines to close this issue if they believe it's been resolved.

**Comment by bparrishMines** [comment]
I agree we should be able to close this. If i understand correctly, you should be able to add the Camera Plugin as a v2 Embedding plugin and don't need to use `ShimPluginRegistry`. Closing
