### ISSUE TITLE
Disable "Red Screen of Death" in Release mode

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#40452]
## Use case

When a widget crashes (because it got bad data passed to its parameters for example), we make the area that widget previously occupied turn red, with the error message. This happens in debug _AND_ release mode. 

People can currently override this behavior by setting a custom onError handler or creating a custom ErrorWidget builder (see examples discussed [here](https://github.com/flutter/flutter/issues/24950) and [here](https://github.com/flutter/flutter/issues/10695) ), but this unfortunately means that it's potentially less obvious what's going on while debugging and this default behavior scares off potential users (not everyone knows they can implement the aforementioned options, and it was cited in the team's recent Japanese trip report as a reason why users there are hesitant about Flutter). 

I have heard this request from multiple independent sources myself as well.

[Related issue](https://github.com/flutter/flutter/issues/29233) around overflow rendering in release mode.

## Proposal

Only have this behavior with the red screen in _debug_ mode. 

Ideal behavior if a widget has crashed in release mode would be to keep rendering what it shows the moment before crash (like when you're debugging and it freezes when an exception occurs). I seem to recall readin in another bug that may be not possible, in which case, a more "external-user-friendly" option might be to just show a blank widget with whatever the app's default background color is. Logging to a console should still take place, with options to connect to things like Crashlytics, but we shouldn't expose these problems to the end users of the apps.

**Comment by Levi-Lesches** [comment]
> Ideal behavior if a widget has crashed in release mode would be to keep rendering what it shows the moment before crash (like when you're debugging and it freezes when an exception occurs).

See #11624 and #10695.

> a more "external-user-friendly"

If this gets rejected, which I hope it doesn't, then #16774 is for making the error widget look nicer. 

But I agree with this -- can we do away with the error widget in release mode? It looks horrible and _extremely_ unprofessional.

**Comment by Levi-Lesches** [comment]
Also, in #13578, it is now possible to override the error widget by setting [`ErrorWidget.builder`](https://api.flutter.dev/flutter/widgets/ErrorWidget/builder.html). It defaults to [`RenderErrorBox`](https://api.flutter.dev/flutter/rendering/RenderErrorBox-class.html), which has a number of static properties you can change to alter its appearance. Or you can just replace it with another widget entirely (but read the docs for warnings).

**Comment by goderbauer** [comment]
> Ideal behavior if a widget has crashed in release mode would be to keep rendering what it shows the moment before crash (like when you're debugging and it freezes when an exception occurs).

Why would you consider this as the ideal behavior? To me, this seems confusing. I don't know if the app is frozen because my device is under heavy load and it will respond again once the background processing is done or if if the app will never respond again because it has crashed.

**Comment by efortuna** [comment]
I discussed this with some of the other DevRel folks. And you're right -- keeping that widget to what it looked like before but not responding is weird. 

We were thinking... actually just a full app crash is better. Red screen is reasonable for development, but in production if something is not behaving as you expect, you're in solidly undefined territory if only part of your app works. Log the issue, and shut it down.

But I'm curious if others from the community have other thoughts on this.

**Comment by anaisbetts** [comment]
> We were thinking... actually just a full app crash is better.

I strongly agree with this. Letting the app crash lets error reporting take over, and it also sends users back to a place that they know what to do with (the launcher). This is also consistent with what happens when other apps crash on their phones.  

The only alternative I could think of is to automatically restart the app (i.e. somewhat mimicing Android's native "Just pretend they hit back button when the activity crashes" behavior), but this could result in rolling crashes that users can't get out of.

**Comment by Levi-Lesches** [comment]
Yeah that's definitely not a good thing. I myself gave `main` a boolean parameter that defaults to `false`. If the init logic fails I delete the cache, log the user out and run `main` with `true`. If it still fails and the parameter is already `true` I just crash and hope Crashlytics caught something useful. This helps me avoid cases where simply outdated data is causing the error while not forcing users to wait too long to know if the app will work or not.

**Comment by Hixie** [comment]
Sometimes the ErrorWidget might only be visible for one frame in a tiny part of the screen. Quitting the app would make such a trivial issue into a fatal one. That doesn't seem like a great solution either.

We could replace it with a subdued gray sad face or something.

**Comment by efortuna** [comment]
Fair. How do folks feel about that? I'm primarily relaying what I hear from others so I'm deferring to others' opinions here.

**Comment by Hixie** [comment]
(FWIW, rendering the old state of the widget is non-trivial; we might not have that state any more, the widget might be brand new, the widget might itself have been the one to throw the exception, etc.)

Here's an alternative rendering where in release builds the error message is elided and the box made black on gray instead of yellow on red:

![Screenshot_20191114-182917](https://user-images.githubusercontent.com/551196/68912352-cbe4e880-070c-11ea-977f-773a2917ece9.png)

We could remove the text entirely, or use some sort of punctuation instead.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/44967 is an attempt to make this part of Flutter mildly less aggressive. It implements the above gray look in release builds and makes the debug-time rendering slightly less ugly (e.g. only showing the message once). I also added documentation to show how you can make your own version of the widget and how you can still keep the debug version as-is so that you can keep debugging easily.

**Comment by anaisbetts** [comment]
> Sometimes the ErrorWidget might only be visible for one frame in a tiny part of the screen. Quitting the app would make such a trivial issue into a fatal one. That doesn't seem like a great solution either.

This seems like a condition that is easy to check for - if the ErrorWidget displays for more than N frames, or take up more than M pixels on screen, blow up

IMHO, even in these edge casey edge cases, I'd much much prefer the crash because crashes are something that I can get notified about and fix

**Comment by Levi-Lesches** [comment]
> Sometimes the ErrorWidget might only be visible for one frame in a tiny part of the screen. Quitting the app would make such a trivial issue into a fatal one.

Yes, that's right. In my case I was describing an error with corrupted data. The only real option there is log the user out (the login page has proper error UI).

**Comment by Hixie** [comment]
It's easy to make your app quit if that's what you want. I'd really rather not make that the default though.

**Comment by Tridie2000** [comment]
> It's easy to make your app quit if that's what you want. I'd really rather not make that the default though.

Can you tell me how to do that because I want to implement that in my apps?

**Comment by goderbauer** [comment]
The more I think about it the more I think we should just crash. As a user I find it always annoying when I am presented with with an interface that doesn't work properly because in the background unknown to me something has thrown an irrecoverable error...

**Comment by Hixie** [comment]
`FlutterError.onError = (_) => exit(1);` would cause your application to quit whenever an error was hit (including one that causes this display to appear).

**Comment by Levi-Lesches** [comment]
There seem to be two different types of errors people are talking about: 

1. Errors caused by the UI. These can be something as trivial as `Column` running out of space by a few pixels to something as complex as a widget being given invalid constraints. 
2. Errors caused by logic. These can be caused by business logic failing, corrupted data, etc.

IMO, problem 1 should be solved by Flutter either working something out (like scaling `Column` down to fit the constraints). Of course, I mean only release mode. Debug mode should still show these as errors. If a layout problem really cannot be fixed, show a user-friendly error widget. Obviously, the branding of said widget and extent to which the rest of the app is even usable without it (eg, `MaterialApp` itself crashed) is highly case-specific and there should be some sort of way for the developer to specify these in advanced (conveniently of course). I know `ErrorWidget` can be customized, but Flutter can help with improvising layout issues before they even become a problem. To my second point, perhaps there should be a way to specify a widget as necessary -- all errors regarding that widget will crash the app instead of hanging there (again, like `MaterialApp`). Maybe a `ShouldCrashOnError` widget to wrap the offending widget? Also, as was mentioned, some errors are trivial -- only occurring for a frame or two. In this case, Flutter can try simply waiting a couple of frames to see if the errors go away. Really, guarding against common errors one-by-one save a lot of frustration among end-users. Again, these require more discussion, but I think those are nice starting points. 

Type 2 errors should be treated by the developer. In general, they should ALWAYS show something to the user, to let them know the app is no longer behaving as expected. This is especially important for some services, such as email clients, so users know an important operation failed. Again, these should really be handled by the developer, but it might be necessary sometimes to configure Flutter to crash on an unhandled error, at least so the OS and error reporting can take over. 

Really though this issue is for "type 1" errors.

**Comment by Levi-Lesches** [comment]
See my comment in that PR, but can we get a way to customize that error widget? That's kinda what this whole issue is about. Currently we can control the debug mode error widget but how about the release mode one?

**Comment by amreniouinnovent** [comment]
@Hixie I think making the ErrorWidget as an optional way could satisfy the original behavior and support a second solution

**Comment by Hixie** [comment]
Errors caused by business logic shouldn't in any way involve the ErrorWidget. ErrorWidget is only about errors thrown during build. We can't make it optional; it's only used in the cases where we tried to ask a build method for a widget, and instead of returning a widget, it threw an exception. We have to have a widget, so we have to make one up, and that's what ErrorWidget is.

Errors like Column running out of space are also not relevant to ErrorWidget, because those are layout errors. During layout or paint if there's an exception we just don't update that widget's subtree, because there's really not much else to do.

**Comment by amreniouinnovent** [comment]
@Hixie I hope the Flutter team give more attention to the Code Push as it will avoid all red screens in the release mode
https://github.com/flutter/flutter/issues/14330

**Comment by Levi-Lesches** [comment]
I guess as a conclusion to this issue: 

The red screen of death can be customized using [`ErrorWidget.builder`](https://api.flutter.dev/flutter/widgets/ErrorWidget/builder.html). The `builder` function can be further customized using `kReleaseMode` and `kDebugMode` bools from `package:flutter/foundation.dart`. 

Solutions for business logic should be handled by anything else. My recommended solutions are trying to manage data manually, crashing, or perhaps a `runApp` call to a basic error page.

**Comment by jnaval04** [comment]
Based on what I read on the thread, which I just skimmed, I am on a predicament and we encountered this on prod builds. Our point was, we are using crashlytics if ever the app crashes. We would have preferred to just shutdown the app. Don't worry about the logs in production. We never want our debug logs/stacktrace to show up in production. I mean seriously, who shows a the stacktrace in full screen on a red background when an app crashes? Who literally asked for that? We have toolset to deal with crashes and ways to retrieve those logs. This is just annoying on consumer end.

**Comment by Hixie** [comment]
Please do try the latest master and let us know (by filing a new bug) if it's not what you would like. It has facilities to override the default behaviour, and by default it shows no stack traces (indeed no error message at all), and no red, in case of widget error.

**Comment by Pebsie** [comment]
Bumping an old issue, sorry, but the current method of giving the user a grey screen feels a bit silly.

For one thing, it shows this grey screen when debug mode does not (e.g when "Incorrect usage of parent data widget" is thrown, debug mode **doesn't** fullscreen error but release mode **does**) The biggest issue with this is that the user has absolutely nothing to feed back to the developer meaning that the developer has to try and replicate the issue knowing only what screen the problem occurred (and the lack of consistency between what is and isn't a red screen error between debug and release makes this extremely difficult)

Furthermore if your app is erroring that's **your** fault. **No app should be shipping with the potential to have these red screen errors occur** as it shows that you're building widgets wrong or aren't catching potential errors in user input. 

I lack the technical knowledge to revert this or change it, but I think that it'd be worth adding back in error displays for users (or perhaps adding a `releaseShowErrors` option to `MaterialApp`?)

**Comment by Hixie** [comment]
This is just the default. Anyone is free to make their applications act however they want.

As a default, this behaviour is probably where we're going to stay. There's three cases:

1. a part of an app just fails, but the user can back out of it. It doesn't really matter if it fails gray or red, but crashing is a worse experience. Users generally see the red as scary and the gray as just failure.

2. an exception is briefly thrown during a transition. With red, users see a flash and think the app is bad. With gray, it's not such a big deal. With a crash it's a really bad experience.

3. an exception occurs that makes the app unusable. With red, the user has something to report but then is lost. With grey, the user is left lost with no idea what happened. With a crash, the user has something to report and can then restart the app. This is bad in all cases, though crash is probably most useful to the user.

Red is therefore worse than gray in all cases and crash is also worse than gray, in most cases. But again, as a developer, you have full control over what you want the app to do here. If you want it to go red, you can do that. If you want it to crash, you can do that.
