### ISSUE TITLE
Document how to run flutter commands with experiments

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#40490]
I am playing around with non-nullable types and added this to my `analysis_options.yaml`:

```
analyzer:
  enable-experiment:
    - non-nullable
```

I have a code-generator that is utilising the nullability extension. Visual Code is fine with my code.

Now, I try to run:

```
flutter packages pub run build_runner watch 
```

I get this error message:

```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] xyz.dart:95:7: Error: This requires the 'non-nullable' experiment to be enabled.Try enabling this experiment by adding it to the command line when compiling and running.
```

How can I pass `--enable-experiment:non-nullable` to `flutter packages pub run`?

The same happens if I run:

```
flutter build ios
```

I get the error message:

```
  lib/main.dart:61:26: Error: This requires the 'non-nullable' experiment to be enabled.

    Try enabling this experiment by adding it to the command line when compiling and running.
```

So, same question: How can I pass `--enable-experiment:non-nullable` to `flutter build`?

Ref: https://stackoverflow.com/questions/57934341/error-this-requires-the-non-nullable-experiment-to-be-enabled

**Comment by renanyoy** [comment]
someone can post the solution here before updating the flutter documentation ?

**Comment by mklim** [comment]
Unfortunately I don't think it's possible to get `--enable-experiment:non-nullable` working with a Flutter app right now. The Flutter framework itself isn't written to be non-nullable by default yet. So even if Flutter was passing the flag to the Dart compiler, compilation would then fail based on a bunch of NNBD errors in Flutter itself. For that experiment to actually work with a Flutter app, the Flutter framework needs to be migrated to NNBD too.

The Flutter framework needs to wait until the language feature is stabilized in Dart and no longer experimental. You can follow dart-lang/language#110 for the progress of NNBD in Dart for now.

**Comment by szotp** [comment]
non-nullable is not the only experiment that could be enabled, extension-methods would also be pretty useful.

**Comment by ollydixon** [comment]
Would be nice if we could enable it for 'lib' or project only directory. Super handy, our main errors are from nulls atm.

**Comment by rrousselGit** [comment]
@mklim Considering nnbd is designed with partial migration in mind, can't Flutter explicitly opt-out of nnbd until it's properly migrated?

**Comment by ollydixon** [comment]
Would be nice if we could isolate directories/files like with the **json_annotation** package. The we could just **target lib/src directory.**  

We spent 3 days converting a whole project only to find out the builds were failing on release only, no documentation how we could fix that. Had to revert the whole project (talking $$$$$ money here).  

This feature should be **number #1** on the Flutter teams radar, 'Optionals' (non-nullables..) is the main reason why our apps are crashing (since request models can contain nullables and we really miss @nullable in Java and just '?' in TypeScript/Kotlin/Swift.  

We've been promised this for 3 years now, what a joke. It's things like this that push legetimate corporate app development architects back to native (which I hate).

**Comment by derolf** [comment]
Fully agree! Also in our growing codebase NN-issues are the main crash reason and flakiness.

Nowadays, engineers are just not used to that 90s null-thing anymore!

**Comment by ollydixon** [comment]
@derolf yeah it feels so backwards to write ///optinal as a comment, 2012 vibe. 😂 But seriously how do we get the flutter team to notice?

**Comment by rrousselGit** [comment]
They are working on it. The fact that we have an `enable-experiment` flag for it is already awesome.

I'm not sure that the opt-in/out mechanism is fully ready though. 

As far as I know, we only have `// @dart = 2.6` for now.

We should get something within the next few months I guess

**Comment by ollydixon** [comment]
@rrousselGit "They are working on it" we've heard that for 3 years now, people are getting rather impatient. This is an essential language feature. It doesn't even seem to be on their radar, the issue isn't making any progress the last few months.

**Comment by derolf** [comment]
A few months ago, I wrote an experimental analyzer plugin that substituted “/*?*/“ into “?” and “/*!*/“ into “!” and run it through the analyzer with NNBD enabled. Worked quite well!

But we had too many false positives back then, so I put it on ice. I also opened some PRs with fixes, but they were completely ignored by the Dart team. https://github.com/dart-lang/sdk/issues/38585

**Comment by ollydixon** [comment]
Maybe we can just strip "?" and "!" before building for release. I mean TypeScript is just a superset and that's good enough, we just need the analysis. Are there clear ways for pre-compilation steps?

**Comment by SpookyTabz** [comment]
change 

from
environment:
    sdk: ">=random <random"
to
environment:
    sdk: ">=2.3.0 <what ever"

**Comment by SpookyTabz** [comment]
in sdk 2.3.0 it uses all experiments

**Comment by flukejones** [comment]
> in sdk 2.3.0 it uses all experiments

This is misleading and incorrect. I think you mean to say that the code for NNBD is there, but it still requires enabling. It would also be better to restrict to `2.8.0-dev` which is the upcoming release which should have NNBD enabled by default.

After Using Rust for the last nearly 5 years jumping in to Dart with try/catch and nulls feels like having an arm tied behind my back. I especially dislike the inability to see if a function throws just by looking at the function signature rather than needing to look at the code or docs (sorry, I know this is not the appropriate place to vent, but hey). try/catch is absolutely developer unfriendly.

**Comment by jonahwilliams** [comment]
I'm not quite sure what this issue is tracking - there might have been some misunderstandings along the way. There is no documentation for this feature because this feature does not actually exist.

The dart analyzer is capable of running with a non-nullable experiment, to show some examples of what warnings and changes will occur when null safety becomes the default. This is what the experiment flag does above.

This flag does not globally enable null safety, because the VM and the flutter engine **do not support this mode** yet. As a result of this, there will be numerous problems if you try and use null-safe code today.

When null-safety is usable, we will absolutely provide the capability to opt-in/opt-out code.

**Comment by ollydixon** [comment]
@jonahwilliams why was this closed?

**Comment by derolf** [comment]
@jonahwilliams Why are you closing the ticket?

**Comment by Aidanvii7** [comment]
Hi Neha,

It seems the original email was marked as deleted, so it wasn't appearing
in the email thread.

Reading through the job description I have some questions regarding the
team structure and workflow.

   1. How many developers are in the team and what are their positions?
   (android, iOS, web and backend developers, UX designers, product owners,
   scrum masters)
   2. Do you use modern software development processes such as Scrum or
   Kanban?
   3. Do you have product owners responsible for communicating the desired
   features from stakeholders to rest of the team (me included)?
   4. Do you know any technologies that are being used here, and which
   technologies I'm expected to have knowledge of? I only see mentions of CSS,
   HTML and JavaScript which are all web (non-android) technologies, which
   tells me this may be a React Native focussed job as opposed to native
   android development.
   5. Regarding all of the above, where would this job position fall under?


Kind regards,
Aidan

**Comment by DanTup** [comment]
@Aidanvii7 you may have replied to the wrong email.

**Comment by liudonghua123** [comment]
I have the same issue, I have use the latest master branch flutter and set the following in pubspec.yaml.
```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
```
And add the analysis_options.yaml file
```yaml
analyzer:
  enable-experiment:
    - non-nullable
    - extension-methods
```

I also tried to add `--enable-experiment:non-nullable` to the VSCode dart settings. But none of them worked.

![image](https://user-images.githubusercontent.com/2276718/77744488-a5d53a80-7054-11ea-828d-48fffb9e9ab9.png)

**Comment by jmars** [comment]
@liudonghua123 I had the same issue, setting the min SDK version to 2.8.0-dev seems to work. So ">=2.8.0-dev <3.0.0" and the analysis_options.yaml you already have. It even seems to work in VSCode at a package level, so you can have app-common with non-null and app-flutter without.

**Comment by liudonghua123** [comment]
@jmars Hi, Thanks for your response, What does you mean it is only work in package level? I can only write flutter packages/plugins using this feature, and not support in a flutter app code?

**Comment by jmars** [comment]
Flutter does not support the feature yet as far as I can tell. By package level i mean if you have multiple folders with a pubspec.yaml and analysis_options.yaml in your workspace, the lower ones override the top level one. You can get flutter 'working' by giving it an options with:

```
analyzer:
  errors:
    missing_default_value_for_parameter: info 
  enable-experiment:
    - non-nullable
```
