### ISSUE TITLE
WidgetOrderFocusTraversalPolicy cannot previousFocus() out of single child scopes

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#40507]
Take the following focus tree, configured with a `WidgetOrderFocusTraversalPolicy`:

* `FocusScope` (a)
  * `FocusScope` (b)
    * `FocusNode` (c)
  * `FocusScope` (d)
    * `FocusNode` (e) **primary focus is here**

Calling `previousFocus()` on (a) on a will repeatedly focus (e), while the expectation is that (c) should receive focus.

I was able to fix this by changing the condition under which `previousNode` is set by `visit()` in `WidgetOrderFocusTraversalPolicy`. If we're going backwards, and `visited.hasFocus`, we don't set it.

While I'm here, I have two questions about how all this stuff works, if you would be so kind:

1. `FocusNode.traversalChildren` omits children that cannot request primary focus, but their children can still be focusable, right? Shouldn't we visit those?
2. Traversals operate on the receiving node's `nearestScope`, which means that calls to `nextFocus` on a node deep in the tree (like (c) in the example above) will trap traversal within the (b) scope, but calling `nextFocus` on (b) will consider all peers of (b) as well as their children. Is that intended behavior?

cc @gspencergoog

**Comment by gspencergoog** [comment]
Hmm.  Yes, I would expect calling `previousFocus` on (a) to traverse all the children. I'll take a look.

For your questions:
1. Well, we do, using `traversalDescendants`.  That's what the traversal policies use to find descendants, and that has all the descendants, but the unfocusable/traversable ones are filtered out.
2. Note that `nearestScope` is different from `enclosingScope`. For `nearestScope`, it can find the node you call it on (if it is a scope), and for `enclosingScope`, it only includes ancestors of the node you call it on.  If you call `nextFocus` on (b), since it is itself a scope, it will use only itself to look for nodes, and hence select (c) only (or at least that is the intention).

**Comment by shyndman** [comment]
> Well, we do, using traversalDescendants. That's what the traversal policies use to find descendants, and that has all the descendants, but the unfocusable/traversable ones are filtered out.

Ah, you're right. Thanks. This makes a lot more sense.

> Note that nearestScope is different from enclosingScope. For nearestScope, it can find the node you call it on (if it is a scope), and for enclosingScope, it only includes ancestors of the node you call it on. If you call nextFocus on (b), since it is itself a scope, it will use only itself to look for nodes, and hence select (c) only (or at least that is the intention).

I'll take a look.

**Comment by shyndman** [comment]
I'm back to working on this. Want me to post a repro?

**Comment by shyndman** [comment]
This is no longer an issue.
