### ISSUE TITLE
How to render image using HTML, CSS using flutter to create iOS-App?

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#40565]
I had asked the question 18 days ago in Stackoverflow. And I had put the bounty but no one knows the answer. The only hope from the Flutter Team. Waiting for the reply.

https://stackoverflow.com/questions/57702924/how-to-render-image-using-html-css-using-flutter-to-create-ios-app

**Comment by escamoteur** [comment]
I don't think this is a flutter problem. Because its about accessing assets from a web view if I understand this right. It may be that you have to put your iOS assets under the resources of the iOS project. 
Best to change the title of your SO question to describe this better

**Comment by jazzbpn** [comment]
Hi @escamoteur , There is a problem only with iOS because we can access the asset images in android and can render the image via html, css. **But in iOS I do not know how to access the asset image path in order to render image via HTML, CSS.**

**Comment by escamoteur** [comment]
I got that, but try to find out how native ios apps do that. Am 18.09.2019 06:25 schrieb bipin <notifications@github.com>:Hi @escamoteur , There is a problem only with iOS because we can access the asset images in android and can render the image via html, css. But in iOS I do not know how to access the asset image path in order to render image via HTML, CSS.
