### ISSUE TITLE
Callstack frames are numbered inconsistently in 'flutter logs' vs in Atom

### ISSUE THREAD

**Issue by jamesr** [flutter/flutter#4062]
## Steps to Reproduce

Make a flutter app that throws an exception and run it in Atom and run it with 'flutter logs' running.  Observer the numbers of the callstack in Atom and the ones in the command line.  Atom numbers things in the opposite way from the command line.  In 'flutter logs' the higher number frames are the callers and the lower number frames are the callee.  In Atom, the opposite is true.  Thus for a 254 frame exception the 'main()' function is called frame 3 in Atom but it's called frame 250 in 'flutter logs'

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jamesr/flutter
    • Framework revision a48b063a10 (4 hours ago), engine revision 8ecb015767

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/jamesr/Library/Android/sdk
    • Platform android-23, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

**Comment by Hixie** [comment]
This is especially notable because the framework's dump of the stack might be (intentionally) omitting entries, and the numbering will be discontinuous as a result (intentionally). If Atom is renumbering the stack, it'll not be accurate. If it's getting the stack out of band, then that's a different matter, but then we'll probably want to apply the same filtering.

**Comment by devoncarew** [comment]
Yeah, for atom I made this choice so that the frame numbers would be consistent as you stepped into and out of methods. So as the call stack changed, frame `#300` would always be the same frame until it went out of scope. If you number from the top, the same frame will have different numbers depending on the number of children it has.

It may not be important to show numbers at all in atom; not showing them would eliminate the problems of the reverse ordering and the filtered out framework frames.
