### ISSUE TITLE
Selection cursors vanishing

### ISSUE THREAD

**Issue by hugocbpassos** [flutter/flutter#40633]
When creating a `TextField` with a `TextStyle` which `height` property is 1, the selection cursors won't pop up when selecting a text.

## Steps to Reproduce

Just create a `TextField` as previously described:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: TextField(
          style: TextStyle(height: 1),
        ),
      ),
    );
  }
}
```

### Default `TextStyle`:

![Screenshot_1568676553](https://user-images.githubusercontent.com/47678313/65000407-de37d700-d8c1-11e9-8dce-418c0f63da84.png)

### `TextStyle` with `height` 1:

![Screenshot_1568676532](https://user-images.githubusercontent.com/47678313/65000438-f9a2e200-d8c1-11e9-8b6e-2dfdcbd09197.png)

## Logs

```
[√] Flutter (Channel unknown, v1.9.1+hotfix.2, on Microsoft Windows [versÃ£o 10.0.18362.356], locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (10 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\hugoc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

@justinmc Perhaps you have some ideas on this. Thanks.

**Comment by justinmc** [comment]
I was able to reproduce this on an Android device.  Very weird that height should affect this!  Thanks for reporting.

**Comment by jason-simmons** [comment]
This is happening due to a difference in text metrics calculation when the text style specifies a height.

The visibility of the selection handles is determined by `RenderEditable._updateSelectionExtentsVisibility`.  `_updateSelectionExtentsVisibility` uses caret positions calculated based on the engine's `Paragraph.getBoxesForRange` API.

If height is set to `1.0`, then the top of the rectangle returned by `getBoxesForRange` will be negative because the engine computes a baseline that is shorter than the font's ascent. 
 `_updateSelectionExtentsVisibility` then thinks that the caret is partially outside the editable's visible region, and it does not paint the selection handles.

The handles become visible with `height: 1.0` if I patch `TextPainter._getRectFromDownstream` to pass `boxHeightStyle: ui.BoxHeightStyle.strut` in the call to `getBoxesForRange`.

@GaryQian would `BoxHeightStyle.strut` make sense for cursor positioning?

**Comment by GaryQian** [comment]
Without a specified strut, BoxHeightStyle.strut will fall back to tight bounds. If I remember correctly, we are now using the strut height to decide the height of the textfield. The caret will be consistent height when using BoxHeightStyle.strut, and should not extend past the box. I think the way it works is that we derive a strut from the textstyle, unless otherwise specified by the user.

In this case, using strut should solve this specific problem, but unsure about how it would impact the selection rects in other situations. Namely, it is possible it would cause gaps in the selected rects between lines (we currently still do this, but with tight bounds instead of strut bounds). Overall, it should be fine, definitely worth a try.
