### ISSUE TITLE
can't read file from android emulator

### ISSUE THREAD

**Issue by ldbing** [flutter/flutter#40651]
I pushed one file into sdcard of emulator, but I can't find the file when invoke `directory(path).list()`. Why?
flutter version is 1.7.8+hotfix.4

**Comment by janmoppel** [comment]
Hello @ldbing !

Thank you for posting an issue.
Can you please post an additional information such as an output of the `flutter doctor -v` command? 
Also, have you tried to upgrade your Flutter version by running `flutter upgrade`? Today's stable version is `v1.9.1+hotfix.2`, and your issue can be potentially fixed in this upgrade.

Thank you.

**Comment by janmoppel** [comment]
Hello @ldbing !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
