### ISSUE TITLE
What online tool do you use to automate translation of .arb files? (Google Translate Toolkit sunset)

### ISSUE THREAD

**Issue by maszhin** [flutter/flutter#40662]
Do you know any good tools to support the translation of .arb files?

It's a standard for Flutter and since Google Translator Toolkit will be sunset soon (https://support.google.com/translatortoolkit/answer/9462068) we're searching for a good solution to translate/gather our translations.

PS. I know I should ask the question in another place (i.e. stackoverflow), but for some reason my question is downvoted there. https://stackoverflow.com/questions/57972593/what-online-tool-do-you-use-to-automate-translation-of-arb-files

**Comment by escamoteur** [comment]
As you got some replies on SO I close this issue for now.

**Comment by maszhin** [comment]
@escamoteur Perhaps we should reopen the issue?

We didn't get any relevant suggestions on SO (only redirection to issues) and this issue could be a blocker for many users using Flutter.

Here is a link to the potential solution: https://github.com/dart-lang/intl_translation/issues/74

**Comment by escamoteur** [comment]
Hi,
currently there is a lot of discussions about internationalization see https://github.com/flutter/flutter/issues/41437
For a translator tool I guess you are better at the Dart issue because this is also relevant for pure Dart projects.
I don't know if you have seen the VS Code plugin for internationalization it offers translation too
