### ISSUE TITLE
Map doesn't show current location dot after got permission on android

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#40670]
I created map with option - myLocationEnabled: true. On app first launch I have location permission dialog and set it enabled. After that I call setState{} and expect that I see my location and button that move camera to my location. But nothing happens. All work only after restart application.

**Comment by marinat** [comment]
Temporary workaround:
in google map library add in GoogleMapController.java:
updateMyLocationSettings();
in case "map#update": section

**Comment by jbxbergdev** [comment]
Another workaround is to use wrap the map in a StreamBuilder, and feed the Stream with null initially and then the returned permission state. Inside the StreamBuilder, only build the map when there is a permission value.

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
