### ISSUE TITLE
Release independent single windows app

### ISSUE THREAD

**Issue by jimist** [flutter/flutter#40688]
How can we build an installer or **single independent app** for windows?
I know that flutter for windows is still not production-ready but is having a final app that works alone under consideration?

**Comment by stuartmorgan** [comment]
> How can we build an installer

This isn't within the scope of the current desktop work; existing Windows installer builders could be applied to Windows applications built with Flutter (once there are Release builds).

> or **single independent app** for windows? [...] is having a final app that works alone under consideration?

It's not clear what you are asking. What do you mean by "independent" and "alone"?

**Comment by jimist** [comment]
@stuartmorgan by independent I mean **portable** apps that don't need installation on windows.
And by alone I mean that **no third-party runner is necessary**.

**Comment by stuartmorgan** [comment]
> by independent I mean portable apps that don't need installation on windows

The build creates a self-contained folder; no installer is necessary if you don't want to use one.

> And by alone I mean that no third-party runner is necessary.

No version of Flutter for Windows has ever used a third-party runner. I suspect this is coming from a misunderstanding of what `flutter run` is. All it does is do the same thing `flutter build` does, which generates a native executable (a .exe on Windows, plus dependency libraries and resources), then launches that executable and attaches to the observatory. You can use Flutter on Windows right now without ever using `flutter run`.

Closing since as far as I can tell this isn't requesting anything that we don't already do.
