### ISSUE TITLE
type 'Color' is not a subtype of type 'MaterialColor'

### ISSUE THREAD

**Issue by loveringfinger** [flutter/flutter#40828]

**Comment by BondarenkoStas** [comment]
@loveringfinger This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue. Then please provide your ```flutter doctor -v``` output and a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
