### ISSUE TITLE
Flutter Sentry. I can't find any documentation.  How to send user information when throwing exception?

### ISSUE THREAD

**Issue by gauravsoti1** [flutter/flutter#40827]

**Comment by escamoteur** [comment]
Have you checked this here https://github.com/flutter/sentry

**Comment by gauravsoti1** [comment]
@escamoteur Yes, I did and I couldn't find it. And it says to file a bug here.

**Comment by escamoteur** [comment]
Sometimes it helping looking into the source code comments of a library.
I made a helper class for sentry some times ago, this should answer all your questions https://gist.github.com/escamoteur/57d37e712befd8bd377f15c85136dcec

**Comment by gauravsoti1** [comment]
@escamoteur I did look at the source code comments but I agree I didn't look at the source code of events that well. Also the point is still there that there is no documentation. Should I create a doc with the help of gist that you shared, so that it helps others as well?

**Comment by escamoteur** [comment]
Best to write a medium article Am 20.09.2019 20:28 schrieb Gaurav Sobti <notifications@github.com>:@escamoteur I did look at the source code comments but I agree I didn't look at the source code of events that well. Also the point is still there that there is no documentation. Should I create a doc with the help of gist that you shared, so that it helps others as well?
