### ISSUE TITLE
use webview_flutter can not open a file dialog

### ISSUE THREAD

**Issue by gitzhangliang** [flutter/flutter#40934]

**Comment by BondarenkoStas** [comment]
@gitzhangliang Please provide your ```flutter doctor -v``` output, and `webview_flutter` version. On which device or emulator do you test it? Does it log any errors or just doesn't react?
Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Otherwise it's hard to determine if it's a bug with plugin or with implementation.

**Comment by gitzhangliang** [comment]
#40844  this is detailed problem

**Comment by BondarenkoStas** [comment]
Okay, then I think it's safe to close this issue as it doesn't give extra info.
