### ISSUE TITLE
Use font-awesome library in Flutter-app online as well as offline?

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#41096]
**Full Question at stack overflow:**

https://stackoverflow.com/questions/57956232/icons-not-rendering-in-flutter-app-how-to-use-font-awesome-library-in-flutter-a

**Comment by BondarenkoStas** [comment]
@jazzbpn Why did you create this issue after creating #41093?

**Comment by markusaksli-nc** [comment]
Hi @jazzbpn 
From what I can see, the issue is related to a plugin maintained by the ‘fluttercommunity’ rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/font_awesome_flutter/issues).
Closing, as this isn't an issue with Flutter itself.
Thank you
