### ISSUE TITLE
Dialog is dismissed on screen touch

### ISSUE THREAD

**Issue by audkar** [flutter/flutter#41178]
Flutter dialog are closed immediately on screen touch. Android native behavior is different. User can touch screen and swipe away to abort dialog dismissal. Problem becomes very visible when using flutter dialogs with android 10 gestural navigation

| Native Android | Flutter |
| ------ | ------- |
| ![dialog_dismiss_native](https://user-images.githubusercontent.com/1947112/65495454-77b54900-debf-11e9-8d2f-9a77f1db2482.gif) | ![dialog_dismiss_flutter](https://user-images.githubusercontent.com/1947112/65495833-09bd5180-dec0-11e9-84b4-42d01e2b5e55.gif) |

## Steps to Reproduce

1. Open dialog
2. Press & hold screen, make swipe gesture
3. Drag back to abort back navigation
4. Observe: Dialog should not be dismissed

```dart
RaisedButton(
  child: Text("openDialog"),
  onPressed: () async => await showDialog(
    context: context,
    builder: (context) => SimpleDialog(
      children: <Widget>[Text("Some dialog")],
    ),
)),
```

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/audrius/Documents/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/audrius/Documents/android-sdk-canary
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/audrius/Documents/android-sdk-canary
    • Java binary at:
      /home/audrius/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5791312/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
```

**Comment by sroddy** [comment]
This behavior is not consistent also w.r.t. iOS. There is not a single app (even Google ones) which dismisses modals on tap down.

This problem has been worsened even more after #36956. It's now impossible to dismiss modals if another gesture recognizer participates in the arena, as the `_AnyTapGestureRecognizer` immediately rejects the gesture on `PointerUpEvent`. I think it should be much better to use a recognizer that accepts anyTap (but not any tapDown).

cc @dkwingsmt, author of the PR

**Comment by dkwingsmt** [comment]
Sorry for causing the trouble.

@audkar Is this something new to Android 10? I've tested this on several apps on earlier Android versions and it seems to me that those dialogs are closed on tap down. I don't currently have Android 10 devices to test so I'll appreciate it if you can describe the updated behaviors.

@sroddy Rejecting gestures is definitely a bug that I should fix. Thanks for bringing this up.
As for iOS dialogs, the only dismissable native dialog I can find is action sheets (corresponding to `CupertinoActionSheet`), and I can see that it's indeed dismissed on tap up instead of tap down. I'll fix it soon.

**Comment by audkar** [comment]
> Is this something new to Android 10?

No. This not specific to Android 10 or gesture navigation. It happens on all Android versions

**Comment by dkwingsmt** [comment]
@audkar I built the following example that contains nothing but a dialog, and tested on a Pixel running Android 9. I confirm that the dialog is dismissed on tap down instead of tap up.

```kotlin
package com.example.testdialog

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

import kotlinx.android.synthetic.main.activity_main.*
import android.app.AlertDialog


class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        fab.setOnClickListener { _ ->
            showDialog()
        }
    }

    private fun showDialog() {
        val alertDialog = AlertDialog.Builder(this).create()
        alertDialog.setTitle("Alert")
        alertDialog.setMessage("Alert message to be shown")
        alertDialog.setButton(AlertDialog.BUTTON_NEUTRAL, "OK") { dialog, _ ->
            dialog.dismiss()
        }
        alertDialog.show()
    }
}
```

Your experience of dismiss on tap up might be a result of gesture competence: when another gesture is competing with the modal barrier, the tap gesture won't claim victory until all other competitors leave the arena when pointer is up. With this conclusion I'll leave the Android behavior as tap down.

Nevertheless, the modal barrier should compete with the gesture navigator on Android 10, resulting in dismissing on tap up. I'll see if I can find a fix.

**Comment by audkar** [comment]
> I confirm that the dialog is dismissed on tap down instead of tap up.

Seems that this behavior is different on android 10. I can reproduce that 
- Dialog is dismissed on tap down on Android 9
- Dialog is dismissed on tap up on Android 10

[dialog_dismiss_android_10](https://user-images.githubusercontent.com/1947112/65636346-c57aa000-dfea-11e9-8ddc-584a1b971b7f.gif)

**Comment by dkwingsmt** [comment]
@audkar Thank you very much. It's very important. Let me discuss with others and see how we handle this.

**Comment by MustafaYusef** [comment]
showDialog(
      barrierDismissible: false,
      context: context,
      builder: (BuildContext context) {
        return alert;
      },
    );
for me set barrierDismissible :false solve the issue
