### ISSUE TITLE
How do I adjust the spaces between the words in a Text widget in order to fit them perfectly on the screen?

### ISSUE THREAD

**Issue by saurabhpetkar** [flutter/flutter#41219]
I want to adjust the spaces between the words, because I want it to look uniform on the screen.
without the space adjustments the screen would look like this:
"Lorem ipsum dolor sit amet, consectetur adipiscing
 elit, sed do eiusmod tempor incididunt ut labore 
et dolore magna aliqua. Ut enim ad minim veniam"

how do I make each line of the text take up the entire space of the screen?

**Comment by timtraversy** [comment]
Hey! The [`Text`](https://api.flutter.dev/flutter/widgets/Text-class.html) widget has a `textAlign` property that you can set to `justify` to get the behavior you want.

If you have a support questions its helpful to post them on the [Stack Overflow page ](https://stackoverflow.com/questions/tagged/flutter?sort=frequent), since they aren't Flutter bugs.
