### ISSUE TITLE
DropdownButton with invalid value generates error that can be confusing

### ISSUE THREAD

**Issue by singh-preet** [flutter/flutter#41259]
I am trying to use DropdownButton, which is working without the value paramenter. 
However, as soon as I initialise value, it gives me the below error. 

```
Syncing files to device Redmi 4A... ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════ 
The following assertion was thrown building PrintPage(dirty, state: _PrintPageState#a2354): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 620 pos 15: 'items == null || items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true. 
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub: #41259
```

**Comment by escamoteur** [comment]
Are you sure you have an element in the `items`collection with the  value of `value`  because that's my guess.

please provide us the output of `flutter doctor` and give us more context. 
Otherwise we cannot help you.

@HansMuller I think this assert should be split into two separate to give a better error message.

**Comment by shihaohong** [comment]
https://github.com/flutter/flutter/pull/43511 should have fixed this issue, so I'll close this for now.
