### ISSUE TITLE
Failed assertion: line 2247 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by abdosaidbassuony** [flutter/flutter#41340]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @abdosaidbassuony !

Thank you for posting.
However, without any additional information, such as the code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.
But feel free to open a new issue and fill the information requested in the template.

Thank you.
