### ISSUE TITLE
occur a error when run "webdev serve"

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#41358]
## Steps to Reproduce
hi,
I get a  following error when I config my web dev-env  on macos .

```
admin$ webdev serve 
admin$webdev could not run for this project.
Could not find a file named "pubspec.yaml" in "/Users/admin/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.5".
```
I'm using the latest version of Flutter. Any idea on how to solve that?

**Comment by janmoppel** [comment]
Hello @lyf571321556 !

Thank you for posting an issue.
This seems like a known problem and the solution was proposed here: #32313. Try to run the `flutter packages pub global run webdev serve` instead of `webdev serve`.

Closing this issue for now, as the same problem was discussed before. However, if proposed solution won't work, please, feel free to open a new issue.

Thank you.
