### ISSUE TITLE
Regression in cull_opacity_perf__timeline_summary benchmark

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#41394]
Starting with https://github.com/flutter/flutter/pull/41314, the "cull_opacity_perf__timeline_summary" regressed:

90th_percentile_frame_build_time_millis: baseline, 9.7ms; actual 12ms
90th_percentile_frame_rasterizer_time_millis: baseline, 17.2ms, actual 48ms

**Comment by tvolkert** [comment]
PRs contained in that engine roll:

@yjbanov  Force exit felt tool on sigint, sigterm (flutter/engine#12443)
[auto-roller] Roll src/third_party/skia 6abaff3041a3..559ffe4a23ce (flutter/engine#12444)
@arbreng [fuchsia] Wire up OpacityLayer to Scenic (flutter/engine#11322)
@yjbanov  delete golden files; switch to flutter/goldens (flutter/engine#12434)

**Comment by yjbanov** [comment]
Neither of my changes affect this benchmarks afaict.

**Comment by tvolkert** [comment]
The Skia changes contained in the Skia roll were:

@brianosman Particles: Added particle flags for tracking state (one-time triggers, etc)
mtklein@google.com poor man's contention profiler

**Comment by brianosman** [comment]
Neither of the Skia changes affects any code that's enabled in Flutter. Just from the PR name and the regressed benchmark, this is @arbreng's change, right?

**Comment by jason-simmons** [comment]
Confirmed that the change in this benchmark started with https://github.com/flutter/engine/commit/fcc4ab32301396986dd5103d6d444bff35fe0f63

**Comment by arbreng** [comment]
Taking a look at this now

David Worsham

**Comment by jason-simmons** [comment]
The `single_child` mechanism added in https://github.com/flutter/engine/commit/fcc4ab32301396986dd5103d6d444bff35fe0f63 is causing a problem during layer tree construction.

The `SceneBuilder` API exposed to Dart provides:
  * a set of `push` methods that add a child to the current node and set the current node to the new child
  * a `pop` method that resets the current node to the previous current node

`SceneBuilder::pop` is just calling `Layer.parent()` to get the previous node:
    https://github.com/flutter/engine/blob/master/lib/ui/compositing/scene_builder.cc#L194

So if the app creates an `OpacityLayer`, pushes a child layer, and then calls `pop`, then the `SceneBuilder's` current node will be the `TransformLayer` acting as the `OpacityLayer's` single child.  But it actually should be the `OpacityLayer'.

Previously this wasn't an issue because there was a one-to-one correspondence between `SceneBuilder` nodes and `Layers` during tree construction.  `OpacityLayer` would convert its children to a single child at `Preroll` time after the `SceneBuilder` is done building the tree.

If that design is no longer viable, then `SceneBuilder` could maintain its own stack of layers and we could eliminate `Layer::parent`

**Comment by arbreng** [comment]
Thank you so much, you just saved me a lot of debugging!

I should be able to construct a PR to fix this shortly

David Worsham

**Comment by arbreng** [comment]
#12523

**Comment by arbreng** [comment]
https://github.com/flutter/engine/pull/12523 should fix this
