### ISSUE TITLE
[web]: Debugging Dart DevTools are not yet supported

### ISSUE THREAD

**Issue by davidcavazos** [flutter/flutter#41428]
Running on VS Code 1.38, doing a debug run and then opening the Dart DevTools is still not supported in Web.

```
> flutter --version
Flutter 1.10.7-pre.41 • channel master • https://github.com/flutter/flutter.git
Framework • revision 26465f4c65 (2 hours ago) • 2019-09-26 18:02:41 -0400
Engine • revision 5b5fd7508c
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 6ff8d2199d)
```

**Comment by anwar907** [comment]
do you use Dart DevTools in flutter web project?

I have write in my blog, maybe you can use like this:
https://kuasaitechnology.blogspot.com/2019/04/dart-devtools-lewat-terminal-flutter.html

**Comment by jacob314** [comment]
Do you mean that opening the debug page is not supported or that DevTools are not working in general? We're intentionally disabling the debug page in the DevTools because you already have a good debugger in VSCode. If you want to use the debugger in DevTools you can clear the query parameter to disable the debugger and it will show up.

**Comment by vsmenon** [comment]
Is this still valid?

**Comment by grouma** [comment]
What's the update here? This doesn't look valid anymore.

**Comment by creativecreatorormaybenot** [comment]
@jacob314 I think they mean that DevTools is not supported on web **at all** → it is disabled.

**Comment by Hixie** [comment]
This should work fine now.
