### ISSUE TITLE
Do I need to commit() SharedPreferences on iOS?

### ISSUE THREAD

**Issue by dpedrinha** [flutter/flutter#41550]
It's a simple question but the documentation isn't clear.
On SharedPreferences.commit() it says 

> "On iOS, synchronize is marked deprecated. On Android, we commit every set."

Does `synchronize` means `commit`? If it's deprecated what should I use on iOS instead of commit?

Or does it commit every set on iOS too?

**Comment by stuartmorgan** [comment]
You [don't need to call it](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/ios/Classes/SharedPreferencesPlugin.m#L48). It's marked as `@deprecated` because you don't need to call it on any platform.

> Does `synchronize` means `commit`?

This refers to an implementation detail of the iOS native implementation ([NSUserDefaults synchronize](https://developer.apple.com/documentation/foundation/nsuserdefaults/1414005-synchronize?language=objc))

> If it's deprecated what should I use on iOS instead of commit?

Nothing; NSUserDefaults no longer requires anything beyond the call that stores a value.

**Comment by dpedrinha** [comment]
Thank you for clarifying.
That said, I believe the documentation should be updated to make it clearer. Something like 

> "This method is deprecated. Every set is automatically commit."

.
