### ISSUE TITLE
How can I make a task run in background in Flutter

### ISSUE THREAD

**Issue by mostafa5731** [flutter/flutter#41603]
hello guys
I want to check with a socket ASP SignalR core a method to send a notification from the app whenever needed.
What should I do to solve it?????

**Comment by BondarenkoStas** [comment]
@mostafa5731 Please check https://flutter.dev/docs/resources/faq#can-i-run-dart-code-in-the-background-of-an-flutter-app. Also you may find https://pub.dev/packages/signalr_client.

This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options. Closing as it's not an issue report.
