### ISSUE TITLE
Allow a BoxDecoration to be specified in ButtonThemeData

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#41627]
Internal: b/141787699

Flutter doesn't have a good way of decorating a button with something that isn't a flat color. This is because the underlying Material widget doesn't allow for it.

Right now we just stack a DecoratedBox behind a MaterialButton with a transparent background. This works for our larger buttons, but fails for our smaller buttons, since the MaterialButton pads the height up to 48dp. This makes the button look like a regular sized button and there's no reasonable way to workaround it.

A proper fix would be to allow a BoxDecoration to be specified in ButtonThemeData. Then we can remove the Stack + DecoratedBox workaround.

Related to or same as https://github.com/flutter/flutter/issues/21125

**Comment by jkurtw** [comment]
b/141787699

**Comment by shihaohong** [comment]
Hi @jkurtw, we shouldn't support this type of modification since that would violate the Material specification. 

However, I think what you could be looking for is creating a custom button composed of a `GestureDetector` and a `Container`, similar to [this S.O. post](https://stackoverflow.com/questions/55216108/button-with-image-background-flutter).

**Comment by lukepighetti** [comment]
@shihaohong Does it "violate" the Material spec or is it "unspecified" by Material spec?

**Comment by shihaohong** [comment]
I believe that modifying components to have an appearance outside of the design language is a violation of the design language.
