### ISSUE TITLE
Is an Alarm App possible?

### ISSUE THREAD

**Issue by Mektrode** [flutter/flutter#41673]
Heyy,

So I've been researching how to develop a Alarm App using a one code base solution. I read into the capabilities of React Native and hit a brick wall. Their architecture does not support background processes.

That has now lead me to Flutter to see what the the options are for such a project and how much native code (if any) would have to be written to complete such a project.

The app would be running mostly behind the scenes and trigger the alarm on the time that it has been set in the app (as any Alarm App works).

Any advice or guidance on my research for the architecture of this project using Flutter would be highly appreciated :)

**Comment by janmoppel** [comment]
Hello @Mektrode !

Thank you for posting.
This is definitely possible! You can learn more about background processes here https://flutter.dev/docs/development/packages-and-plugins/background-processes.

But overall, your question seems to be a better fit for the [StackOverflow](https://stackoverflow.com/tags/flutter), because it is not an issue report. Flutter has a very active and helpful community there, so feel free to post it there. Also, see other support options here: https://flutter.dev/community

Closing this ticket, as it is not an issue report.
