### ISSUE TITLE
Drawer - Scrim

### ISSUE THREAD

**Issue by hivesey** [flutter/flutter#41738]
Hi,

I would like to detect user click on the Drawer scrim. The drawer closes wonderfully when I click on the scrim but I need to also perform another app related activity when the user clicks on drawer scrim to close the drawer.

I understand scrim is a bottomsheet under the drawer, can we detect clicks on it?

Thanks,
Arathi

**Comment by escamoteur** [comment]
Please ask such questions on [stackoverflow](stackoverflow.com) , because we unfortunately not able to give individual development support here. 
This place is only for reporting bugs or suggesting new features.

**Comment by hivesey** [comment]
I have researched and found there's no way to access the scrim, was
wondering if there could be a new API method to get a handle on the drawer
scrim. (new feature suggestion?)

Thanks,
Arathi

**Comment by escamoteur** [comment]
As a non native Flutter developer can you explain what a Scrim is in this context? Possibly with a picture? If this is missing I happily reopen this issue as feature request

**Comment by escamoteur** [comment]
@goderbauer is this currently possible or a new feature?

**Comment by hivesey** [comment]
Its a new feature.

Thanks,

**Comment by escamoteur** [comment]
@hivesey when you write a method to access the drawer scrim, that wouldn't help much I fear. What we would need is either the possibility to pass a custom scrim Widget to Scaffold, or a new handler function on the scaffold that is called when the scrim is dismissed.
To me it seems that this isn't a use case that is need by many people so I fear it won't be implemented soon if at all.
I recommend to create a copy of scaffold in your own App and modify it. If you find a good non breaking solution you could open a PR so that it get's merged into the framework

**Comment by hivesey** [comment]
I have closed this issue because I created a new one # 43512 with more clarity on the issue.

**Comment by hivesey** [comment]
Hi,

I have closed this one and created a new request with more information #
43512.

Please let me know if you have any questions.

Thanks,
Arathi

**Comment by escamoteur** [comment]
see https://github.com/flutter/flutter/issues/43512
