### ISSUE TITLE
Wiki page describing local engine web builds is missing

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#41748]
Now this only links to flutter.dev/web. however that page used to contain information on how to build a local engine with ninja

**Comment by jonahwilliams** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Do you mean https://github.com/flutter/flutter/wiki/Compiling-the-engine should also describe how to build a local web engine? I'm not aware of any existing pages having used to contain this information 🤔

**Comment by jonahwilliams** [comment]
I wrote an initial doc in the wiki describing this workflow, I was hoping you know why the link got changed, and where the old wiki page is.

**Comment by yjbanov** [comment]
I know that pages on the flutter.dev website were updated around September 10, 2019. I'm not aware of any recent Wiki changes. I clones the Wiki repo and scanned the history for "destroyed" pages. I only found "Destroyed Building a web application with Flutter (markdown)" by @sfshaza2, but I'm guessing that's not the page that talks about local engine builds, is it?

**Comment by yjbanov** [comment]
A-ha! I'm wrong. That page does contain engine build instructions:

## Current Status

Flutter now has early experimental support for running flutter web applications. There are still many missing features and known performance issues, so it isn't recommended for production use. This requires the latest flutter master from at least commit [4c0145](https://github.com/flutter/flutter/commit/4c0145d97bd7f48843b360923f59ed30811b7f23).

**IMPORTANT:** The unforked flutter web workflow is still missing several features currently present in flutter_web. Work is ongoing to upstream these changes in Flutter proper.

If your app is using `package:flutter_web`, see [Upgrading from package:flutter_web to the Flutter SDK](https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK).

### Examples

Only the flutter gallery and hello_world have been configured to work with flutter for web. The additional files required can be added to an existing project with the command  `flutter create .` once the feature is enabled. For a new project the web sub-project is created automatically.

### Tooling

Use the `config` command to enable:

```
flutter config --enable-web
```

If this is set up correctly, Flutter devices will output a device named chrome. Flutter doctor will also check for a locatable chrome executable which is required for development mode and tests. If one cannot be found, try setting the CHROME_EXECUTABLE environment variable to the path to your Chrome executable.

```
$ flutter devices
> 1 connected device:
> 
> Chrome • chrome • web-javascript • Google Chrome 75.0.3770.80 
```

```
$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, v1.7.3-pre.52, on Mac OS X 10.14.5 18F132, locale en-US)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.0)
> [✓] iOS tools - develop for iOS devices
> [✓] Chrome - develop for the web
>     ! CHROME_EXECUTABLE not set
> [!] Android Studio (version 3.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] IntelliJ IDEA Community Edition (version 2018.3.4)
> [✓] VS Code (version 1.35.0)
> [✓] Connected device (1 available)
```

`flutter run` will launch the application using the development compiler in a Chrome browser. The name of the web "device" is currently "chrome", but this doesn't need to be specified if there are no other devices attached.

```
$ flutter run -d chrome
> Running "flutter pub get" in hello_world...                         0.4s
> Compiling lib/main.dart for the Web...                              1.0s
> 
> 🔥  To hot restart (and rebuild state), press "R".
> For a more detailed help message, press "h". To quit, press "q".
```

To see additional build output, you can run with -v. If there are issues with changes not propagating or compilation errors that can't be resolved, run `flutter clean` and then file a bug describing what you changed.

This includes a basic hot restart functionality: though IDEs do support hot reload on save, this functionality does not exist yet for flutter web. While flutter web intends to support modern browsers for shipped applications, for development we require the use of a chrome browser to make use of Chrome devtools.

### Plugins

Plugins are not currently supported in flutter web.

### Engine development

Development on the web engine requires the same setup as the normal engine workflow. Follow the setup in the engine contributing guide at [Setting-up-the-Engine-development-environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment).

To build the web engine:

```
./flutter/tools/gn --unopt --full-dart-sdk
ninja -C out/host_debug_unopt
```

And then to run with a locally built web engine:

```
flutter run -d chrome --local-engine=host_debug_unopt
```

The web implementation of `dart:ui` is located at https://github.com/flutter/engine/tree/master/lib/stub_ui and the rules to build the sdk are located at https://github.com/flutter/engine/tree/master/web_sdk.

Subsequent changes to the dart sdk in the engine will require another run of `ninja -C out/host_debug_unopt` and a restart or browser refresh. Currently the web compilers do not recompile the web engine, and instead it works because the dart sdk is loaded as a separate javascript bundle in the browser during development mode.

### Release and profile builds

A release build uses dart2js instead of the development compiler to produce a single JavaScript file. This can be run with the `flutter run -d chrome --release/--profile` flag or built using `flutter build web`. The latter will output files at build/web, including the assets, which need to be served together. A profile build contains unminified JavaScript for easier debugging, but is otherwise identical to a release build. There is no support for "building" a debug build, since they generally consist of potentially thousands of small files.

### Tests

Unit tests can be run on the web with the argument `--platform=chrome`. This will compile the tests to JavaScript and run them in a headless Chrome browser. Note that there are still compatibility issues with many flutter tests and bugs with the test bootstrap itself that will need to be resolved.

```
$ flutter test --platform=chrome
> Downloading Web SDK...                                              1.1s
> Running "flutter pub get" in flutter...                             0.4s
>                                                                        
> Compiling test/scheduler/debug_test.dart for the Web...   
```


There is no current support for driver tests.

**Comment by yjbanov** [comment]
I added a web section to the engine wiki: https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web
