### ISSUE TITLE
Flag emojis have incorrect width on Android M devices

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#41792]
## Steps to Reproduce

Reproduction snippet:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Row(
            children: <Widget>[
              Text(
                String.fromCharCodes([55356, 56826, 55356, 56824]),
              ),
              Text("Hello, World"),
            ],
          ),
        ),
      ),
    );
  }
}
```

Displays like this on a Nexus 5X running M. 
![image](https://user-images.githubusercontent.com/2268005/66065353-0ba89580-e4fc-11e9-8141-866df7e4b3c8.png)

Notice the extra space between the flag and "Hello, World". This space isn't present if it's all a single string, but it still messes with the width of the Text widget (so wrapping with a Center or Alignment makes it off-center).

As a workaround, setting the textWidthBasis to `TextWidthBasis.longestLine` works, but this isn't a problem on Android N+.

On the dart:ui level, the paragraph's width and intrinsic width are both around 35.0px, while the longestLine is just 16.4px. This problem doesn't show up with the cursor in text fields, so selection boxes and cursors are already calculated correctly.

cc @GaryQian

**Comment by GaryQian** [comment]
This may be due to flags consisting of letter emojis connected with zero width joiners. For example, the USA flag is represented as such:  `[U]<zwj>[S]`. It looks like it is rendering with the width of both the U and S emojis instead of the combined flag emoji.

What is interesting is why this is limited to certain versions of android.

**Comment by ds84182** [comment]
Could be slight differences between Noto emoji fonts. I don't have an M device with an OEM customized version of Android (like Samsung or LG), would be useful to test on them also.

**Comment by jason-simmons** [comment]
I have not yet obtained a device that reproduces this bug as shown above with Android M.

But I was able to produce a different incorrect output by running this app on a Nexus 4 running Android L.  On that phone, the "Hello World" text is rendered on top of the flag.

This happens because the line breaker's call to Minikin's `Layout::measureText`/`Layout::doLayoutRun` for the flag emoji returns a width of zero.  This zero width is then written to the `max_intrinsic_width_` calculated by `ParagraphTxt::ComputeLineBreaks`, and eventually that width is returned to the framework text widget.

Within `Layout::measureText`, HarfBuzz is returning two glyphs (presumably representing the `U` and `S` regional indicators) each of which has a zero advance.

Interestingly, after `ComputeLineBreaks` finishes, `Paragraph::Layout` does another call to `minikin::Layout::doLayoutRun` to do the full text layout.  In this call HarfBuzz produces the flag emoji glyph with the correct advance.

I haven't figured out why HarfBuzz behaves differently during line breaking versus layout.  The two invocations should both be passing the same text with the same font.

Also tried this app with the new SkShaper-based text renderer.  SkShaper produces correct output on the Nexus 4.

**Comment by GaryQian** [comment]
@ds84182 Can you confirm you are still seeing this? We have one report that this issue has been fixed in https://github.com/flutter/flutter/issues/43230

**Comment by ds84182** [comment]
I don't see the issue anymore, thanks!
