### ISSUE TITLE
[android_alarm_manager] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41830]

**Comment by mklim** [comment]
This needs `ViewDestroyListener` from the previous embedding, and so I think a lifecycle from the new embedding. That makes it blocked for now. Is that understanding correct @matthew-carroll or am I missing a non-lifecycle alternative here?

**Comment by matthew-carroll** [comment]
@mklim can you reference the specific line(s) that you believe are dependent on `View` destruction and not just something like `Activity` destruction? I want to make sure I look at the exactly the areas that you believe are blockers.

**Comment by mklim** [comment]
@matthew-carroll I was looking at these:

- https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java#L150-L163
- `implements ViewDestroyListener` at https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java#L41

However now that I'm looking at this more deeply I'm not really seeing a meaningful use of `sBackgroundFlutterView` in the service.

/cc @bkonyi

**Comment by matthew-carroll** [comment]
Ok, so the concern is `FlutterNativeView` rather than `FlutterView`, right? If I'm understanding correctly, the answer is to replace uses of `FlutterNativeView` with a `FlutterEngine`. That native view part wasn't really about Android UIs at all. It was displaced by `FlutterEngine`. Let me know if that helps resolve the blocker concern.

**Comment by mklim** [comment]
Yeah, that makes sense. Thanks for clearing that up @matthew-carroll!

**Comment by bkonyi** [comment]
Sorry for the delay, was OOO Friday. @matthew-carroll is right, we should be moving this to use `FlutterEngine` instead of `FlutterNativeView`. I'm in the process of updating the plugin for the new embedding (assuming @mklim hasn't started anything, I'll continue doing so) so I'll update this while I'm there.
