### ISSUE TITLE
[webview_flutter] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41851]

**Comment by mklim** [comment]
The `onFlutterViewAttached` callbacks didn't roll until `v1.10.9`, and stable is `v1.9.1`. It would be possible to hack around it and comment out the `@Override` so that it still compiled, but trying to use this on stable would be completely broken. I'm considering this blocked until the next set of embedding changes releases to the next stable.

**Comment by mklim** [comment]
> It would be possible to hack around it and comment out the `@Override` so that it still compiled, but trying to use this on stable would be completely broken. I'm considering this blocked until the next set of embedding changes releases to the next stable.

I discussed this offline with @amirh and @matthew-carroll and overall it's still preferable to migrate this early and have the V2 embedding path broken in the meantime on stable than to not migrate at all for a few more months. It's practically unlikely that anyone will be using the V2 embedding on stable so it shouldn't actually introduce breakages, even though it could. I'll re-land the migration with a bunch of caution tape around the embedding APIs.
