### ISSUE TITLE
User-created ancestor of the error-causing widget was:

### ISSUE THREAD

**Issue by minhhoang1007** [flutter/flutter#41887]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @minhhoang1007 !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Comment by nisimjoseph** [comment]
I got the same message and the solution was the Router didn't find any route and return to MaterialApp empty Widget.
