### ISSUE TITLE
Exception Caught By widgets library

### ISSUE THREAD

**Issue by 97loser** [flutter/flutter#41893]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @97loser !

Thank you for posting. 
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.
