### ISSUE TITLE
Is there any way of screen video recording using flutter? if yes, how? 

### ISSUE THREAD

**Issue by ad7194** [flutter/flutter#41991]

**Comment by escamoteur** [comment]
Hi, can you please elaborate what exactly you want to do?

**Comment by ad7194** [comment]
i am working on project and i want to implement a feature in my app where user can draw anything on the screen and the way he is drawing on the screen he can record that within the app. And that exported video can be uploaded on server. So is it possible in flutter ?

**Comment by escamoteur** [comment]
You can save the contentens of Wifgets see here https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb

So you could repeatedly save while the user is dragging.

Please ask such questions on [stackoverflow](stackoverflow.com) , because we unfortunately not able to give individual development support here. 
This place is only for reporting bugs or suggesting new features.
