### ISSUE TITLE
Support multiline TextOverflow effects

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#4202]
## Steps to Reproduce

During the [step 10 of the codelab](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#9) I entered a large text in the `Input` and the created `ListItem` lets the text overflow on the following messages.

![flutter_01](https://cloud.githubusercontent.com/assets/1206632/15563984/f2d95fca-230d-11e6-85a0-efea41911999.png)

According to [the spec on Material List](https://www.google.com/design/spec/components/lists.html) the content of a `ListItem` should be limited to 3 lines (BTW thus I'm not sure that this component is suitable for a chat).

2 alternatives :
- hide the overflow on the framework to be sure only 3 lines are displayed
- compute the height of `ListItem` based on its content and put the following `ListItem` afterward (Not sure it's Material Design compliant)
## Flutter Doctor

```
[✓] Flutter (on Linux, channel codelab)
    • Flutter at xxx
    • Framework revision b4313b04b0 (il y a 9 jours), engine revision a1f4a12baa

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at xxx
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by abarth** [comment]
Yeah, ListItem isn't really the proper widget for a chat program because of this issue.

We recently added TextOverflow effects for single-line text widgets.  We should make them work well for multiline widgets as well.  Handling this problem in full generality is slightly subtle because in some languages (and fonts) the lines can overlap vertically.

/cc @Hixie for ideas about how to handle multi-line text overflow effects.

One approach would be to put an ellipsis in the corner and use a diagonal linear mask gradient to fade out the text behind the corner.

It's not obvious how to get the "three line" behavior.  One idea is to calculate the height of the text from the line height and the font size.  Another option is to tell the engine that you only want N of the line boxes and to not paint (or reserve space for) the rest of the lines.  That would prevent content from line N+1 from reaching up from below the clip.

**Comment by Hixie** [comment]
For chat we should just show variable-height cards.

**Comment by Hixie** [comment]
Looks like we have use cases for two kinds of multiline text-overflow effects:

- ellipsise when you reach a certain number of lines
- ellipsise when the next line would overflow the maxHeight

**Comment by mpcomplete** [comment]
We now have support for "ellipses when the next line would overflow the maxHeight". I don't know what this means or how it differs from the other one: "ellipsise when you reach a certain number of lines".

**Comment by abarth** [comment]
One is based on the number of lines and one is based on the number of pixels.  Prior to layout, it's known how the number of lines correlates with the number of pixels.

**Comment by abarth** [comment]
I think the one you implemented was "ellipsise when you reach a certain number of lines"

**Comment by eseidelGoogle** [comment]
I think we have some of this now?  @dvdwasibi to confirm.

**Comment by Hixie** [comment]
We have some multiple overflow effects, if someone wants particular ones, we should file a specific bug for that effect.
