### ISSUE TITLE
Flutter first-party plugins CI tests should run on master and stable for every change

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#42377]
This will ensure that the first-party plugins work on both branches.

We probably only need to run the analyzer on master though.

**Comment by mklim** [comment]
This is particularly important because we guarantee that our [1.0.0 plugins support stable](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#plugin-compatibility), but right now we're only testing them on CI with master and we generally develop with master. We've had multiple bugs in the past where we've accidentally regressed stable in ways that CI would have caught.

**Comment by mklim** [comment]
This was reopened by flutter/plugins@c155379d137603821410a0851ff691713b5ba38b.
