### ISSUE TITLE
Have a shell argument to disable Metal

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#42403]
Similar to having a shell argument to force software rendering.  Once we're shipping metal by default, someone may see rendering issues that are metal specific - it would be nice to have a way to easily drop down to OpenGL to see if the issues persist.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
As discussed with @pcsosinski and company, we are going to stay away from adding flags unless absolutely necessary. We have a flag in place already while we tinker on this in development, but this will be removed when Metal is ready. For tinkering with OpenGL builds, building the engine is the way to go.

I am closing this as wont-fix.

**Comment by ened** [comment]
We're currently investigating issues in raw h264 video decoding (using VideoToolbox APIs) that did not occur until the Metal was on by default. I'd love for a switch to temporarily turn metal rendering off to get clues on where the issue can be fixed.

VideoToolbox returns errors like -12911 (pointing to decoder problems, likely due to resource access).

**Comment by pcsosinski** [comment]
@ened have you filed an issue with the problems you're seeing (and logs?)
