### ISSUE TITLE
Custom task runners are difficult to use with `FlutterEngineRun`.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42460]
Currently, `FlutterEngineRun` initializes the engine and runs the root isolate. This has worked out fine so far. However, as fix for https://github.com/flutter/flutter/issues/17579#issuecomment-537746362, there is a desire to expose more task runners for the embedder to control. Exposing task runners themselves is fairly straightforward. However, for embedders to post expired tasks back to the engine, they need a handle to the engine. This handle is only returned to the embedder after `FlutterEngineRun` returns. But `FlutterEngineRun` may have to wait for tasks to be serviced on another thread before it can return. So the engine will wait for the task to be posted on another thread before returning from `FlutterEngineRun` while the embedder will wait on `FlutterEngineRun` to return so it can get a handle to the engine to for it to post the expired task. This causes a deadlock.

The proposed solution is the create two new embedder API calls. These are `FlutterEngineInitialize` and `FlutterEngineRunInitialized` respectively. The first will create an engine  but not bootstrap its shell or run any root isolates. Using this minimal setup, the embedder can get a hold of the engine handle. It can then make the second call and avoid the deadlock scenario described above.

The existing call stays as is. It works well enough for embedders not performing complicated task runner configuration.

**Comment by chinmaygarde** [comment]
https://github.com/flutter/engine/pull/12757 depends on this.

**Comment by chinmaygarde** [comment]
Discussed this with @cbracken the other day and cc @franciscojma86 who is tracking progress on the linked issue.

cc @stuartmorgan as a breadcrumb for context on the changes made during the leave of absence.

**Comment by stuartmorgan** [comment]
Do you want to take this opportunity in the new API to fix the weird behavior of `args` in the current API where we have to pass in a dummy 0th argument?

It can't be fixed in the original API for compatibility reasons, but we're could make the newer API less surprising (with the downside of inconsistency with the old API, but I think it's still worth doing). It could be called `flags` or something like that to emphasize that it's not the same.

I know it's unrelated to the purpose of the change, but if we don't do it while introducing the API well be such with it there too.
