### ISSUE TITLE
Document how to achieve blank cells in Table/TableRow

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#42523]
## Use case

Sometimes we need to leave Table cells blank (no child widget) by design.
Right now the workaround is e,g, to put a blank `Container()` in to imitate emptiness. However it clutters the widget tree and building code.

## Proposal

Instead of throwing a `FlutterError(
             'One of the children of one of the rows of the table was null.\n'
             'The children of a TableRow must not be null.'
           );` accept `null` and treat it the same way you now treat an empty `Container()` as a child.

**Comment by goderbauer** [comment]
I don't see how `null` is less clutter-y then `Container()`?

**Comment by duzenko** [comment]
> 
> 
> I don't see how `null` is less clutter-y then `Container()`?

You need to make an effort to understand the purpose of Container() in layout generation code when looking at someone else's code or even your own after a while. Why Container() and not one of dozens of other widgets? Are there other widgets that can be used for this? Why prefer Container() instead? What is the recommended widget for empty table cells? Where is it stated in the docs? These are all the questions that hundreds of flutter users wouldn't need to ask and spend time on if Table just accepted nulls.

**Comment by tvolkert** [comment]
For consistency with other widgets that accept children, we're unlikely to change it to allow nulls, but at the very least, we could document how to achieve empty cells by using `Container()`.  Updating the title accordingly.

**Comment by jonl-percsolutions-com** [comment]
I ran into this today. However, I chose the logical operation which was to add a Spacer().  Which ended up throwing an error due to the Spacer having an Expanded and not having the correct ParentData type.  So I simply created a static method to create the desired container.  I think it would be logical to have a TableCell.emptyCell().  Was going to add this as an extension, but because static extensions are not yet allowed  [dart#723](https://github.com/dart-lang/language/issues/723), I settled for a utility method.,
