### ISSUE TITLE
stock_animation_open_first_frame_average regressed 

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42564]
This looked fairly noisy before but never got back below the selected baseline after https://github.com/flutter/flutter/pull/42278.
![Screen Shot 2019-10-11 at 8 59 26 PM](https://user-images.githubusercontent.com/44085/66694639-77140500-ec6a-11e9-8cc8-152bc33fbd05.png)

**Comment by chinmaygarde** [comment]
cc @gspencergoog

**Comment by gspencergoog** [comment]
Dang, looks like I just moved the regression from one benchmark to another.  I might need some help finding something other ways to speed this up: I've already tried a lot of things.

**Comment by gspencergoog** [comment]
OK, I'm officially stumped.  I spent all day yesterday optimizing this code, and thought I had found a combination that almost eliminated this regression (1.3% instead of 5.1%), so I checked it in, but there has been no change in the benchmark.

I have a spreadsheet where I tracked my changes and their effect, and it showed a clear improvement.  I ran the benchmark 10x for each data point in my spreadsheet, and took the median (and the mean, just to sanity check). I'm running it on a Moto G4, set up the same as our benchmark devices.

If I can't measure the impact of my changes, it's going to be pretty hard to optimize this...

**Comment by gspencergoog** [comment]
After talking with others about this, I am going to rebaseline this as a fixed cost for the feature of keyboard shortcuts and focus traversal. I've done quite a lot of investigation and optimization of this code, and in reality there are probably more impactful optimizations that could be done in other areas of the code.
