### ISSUE TITLE
Replace RenderConstrainedOverflowBox with RenderCustomSingleChildLayoutBox

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4267]
RenderConstrainedOverflowBox sizes itself to `constraings.biggest`, which means its use case is subsumed by RenderCustomSingleChildLayoutBox.

/cc @Hixie

**Comment by abarth** [comment]
RenderSizedOverflowBox looks like it is also subsumed by RenderCustomSingleChildLayout.

**Comment by Hixie** [comment]
The use cases for both would include some caveat along the lines of "without requiring a delegate". The custom layout widgets are escape hatches for when you can't do it easily any other way. I don't think they justify removing easier solutions. Our whole system is a big stack of layers that simplify things. If we start removing things because you can build them out of the previous layers, we're rapidly going to end up without a framework. :-)

**Comment by abarth** [comment]
Maybe we should look at how often these are used.  If we had RenderCustomSingleChildLayoutBox before running into these, there's a good chance we wouldn't have added them.  (I also have trouble keeping all the subtle variants straight.)

**Comment by abarth** [comment]
As discussed on the CL, it's not clear that removing these render objects is a win.
