### ISSUE TITLE
Plugin: Camera

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#427]
This is a request for an API to access the device's camera.

**Comment by jumpkick** [comment]
I'm not sure if it's available in Flutter, but it seems there is an Android-only "mojo:camera" service class here: https://github.com/domokit/mojo/blob/master/examples/dart/camera_video/lib/main.dart

**Comment by olostan** [comment]
So there is no iOS version for now?

**Comment by sethladd** [comment]
We are going to try adding a binary data transport to our plugin/services API, which would allow a camera plugin to be built. See https://github.com/flutter/flutter/issues/6575

**Comment by sethladd** [comment]
Here's a work-in-progress camera plugin: https://github.com/FaisalAbid/flutter-camera-plugin

**Comment by sethladd** [comment]
I'm going to close this request, because our strategy is to build out a plugin/interop layer, and allow for a camera plugin to be built.

Flutter itself is unlikely to ship a direct camera API, but we fully intend to allow for a plugin to expose and control a camera.

**Comment by pulyaevskiy** [comment]
@sethladd Wondering if there is an open issue for "plugin/interop" layer to subscribe to? Or is it just a combination of FlutterView and message-passing mechanism?

**Comment by eseidelGoogle** [comment]
@pulyaevskiy there are a bunch of pieces.

1. For one, we need to integrate hello_services with the default workflow (so that it's possible to use custom Android code in a default flutter project): https://github.com/flutter/flutter/issues/4796
1. Another is we have to publish some example plugins.
1. We need to make it possible to distribute them.
1. And consume the distributed plugins.  https://github.com/flutter/flutter/issues/5744

**Comment by franzsilva** [comment]
Will flutter only be a viewing layer? Will it be possible to access the systems APIs from dart code in the future? Similar to hoy nativescript works?

**Comment by sandeepreddy-vinta** [comment]
Sorry I couldn't get completely. 

Right now is it possible from flutter ui to access camera ? If yes can you provide link example or docs?

**Comment by eseidelGoogle** [comment]
@franzsilva Flutter's focus is on being a cross-platform way to write UIs.  We try to provide a very nice developer experience when doing so.  Because we use a portable language (dart), it is of course possible to write your entire application in Dart and only then call-out to system services on the device when necessary (camera, location, etc.)  Our current system for supporting these call-outs is documented at https://flutter.io/platform-services/ with an example at https://github.com/flutter/flutter/tree/master/examples/hello_services.  We believe that model needs some improvement, most notably in terms of tooling and supporting an ecosystem of pre-built service plugins.  Those are both areas we're working on now, as [discussed above](https://github.com/flutter/flutter/issues/427#issuecomment-264646862).

@sandeepreddy-vinta it's possible to access any system functionality, including the Camera, using the methods described above. Doing so is not nearly as easy as we'd like, hence the discussion above about improving such.  Another Flutter user @FaisalAbid made an example plugin showing how to access the camera: https://github.com/FaisalAbid/flutter-camera-plugin.

Although we've made this all *possible* today, it's not nearly as easy as we'd like.  We'll be improving this soon.

**Comment by laike9m** [comment]
@eseidelGoogle, the link you gave showing an example with camera no longer exists.

**Comment by jsiedentop** [comment]
@laike9m, Erick Ghaumez forked the plugin from Faisal Abid: https://github.com/rxlabz/flutter-camera-plugin The Plugin was developed only for Android with the hello_service example.
But the hello_service example is outdated. You can use the new examples 
https://github.com/flutter/flutter/tree/master/examples/platform_channel or https://github.com/flutter/flutter/tree/master/examples/flutter_view and search for code snipplets for how taking pictures or migrate the platform specific code from the camera-plugin-example. 

Keep https://github.com/flutter/flutter/pull/8971 in mind. Last week, they did some breaking changes in the ios part of flutter apps. If you try to launch an old example, you have to do some migration stuff.

**Comment by collinjackson** [comment]
Update on this: There's a super rough camera plugin in github.com/flutter/image_picker. Besides documentation and tests, the main thing that's missing for M2 is that iOS version needs to be able to take photos (right now it only picks from the gallery). Should be fairly straightforward to add.

**Comment by ayazzali** [comment]
Sorry, but I don't know where write.
I have 2 errors in  https://github.com/rxlabz/flutter-camera-plugin
(i tried build this at the ubuntu64 and WIN8)
i don't understand What's wrong in this. ( 

:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/ayaz/flutter-camera-plugin/android/app/src/main/java/com/example/flutter/MainActivity.java:40: error: cannot find symbol
    private FlutterView.MessageResponse _response;
                       ^
  symbol:   class MessageResponse
  location: class FlutterView
/home/ayaz/flutter-camera-plugin/android/app/src/main/java/com/example/flutter/MainActivity.java:54: error: cannot find symbol
                new FlutterView.OnMessageListenerAsync() {
                               ^
  symbol:   class OnMessageListenerAsync
  location: class FlutterView
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by eseidelGoogle** [comment]
@ayazzali can you file a new bug? https://github.com/flutter/flutter/issues/new or ask on stack overflow? stackoverflow.com/questions/tagged/flutter . Both of those would be fine places to ask where we can be sure to get you a resolution.  This bug is closed and about a different issue, so likely not the right way to reach resolution for your issue.

**Comment by eseidelGoogle** [comment]
Flutter now provides https://github.com/flutter/plugins/tree/master/packages/camera (also published on pub as https://pub.dartlang.org/packages/camera).  It's done via a plugin, so others could write fancier camera plugins if so desired.

**Comment by ayazzali** [comment]
Cool, thank you very mach

**Comment by javidnoutash** [comment]
How can I achieve 4:3 previewSize and pictureSize?

**Comment by Arthur-Kamau** [comment]
concerning https://github.com/flutter/plugins/tree/master/packages/camera  is it possible to add feature for streaming the camrea to a server ip.

**Comment by rogerfleenor** [comment]
Is there any API that not only allows access to camera but allows access to ISO, Shutter Speed, etc.. settings?
