### ISSUE TITLE
Regression in flutter_gallery_ios32__transition_perf 99th_percentile_frame_build_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42765]
And likely the same in flutter_gallery_ios32__transition_perf90th_percentile_frame_rasterizer_time_milli. Looks like it started with the engine roll in #42501 or #42495.

**Comment by Hixie** [comment]
I asked @matthew-carroll to check this out.

I would recommend the following approach:
1. See if you can reproduce locally by running a commit that shows the regression and a commit from a week earlier (the benchmark was very steady before), on an iOS 32bit device, and seeing if you see the same increase. You may have to run several times as it may be flaky.
2. If you can, try git bisect.
   If you cannot, try rebooting the mac5 host and device, see if that helps.

**Comment by franciscojma86** [comment]
Yesterday the phone was changed to a 6s in the lab, around 4pm. The benchmarks lowered for that period. They just changed it back to the iPhone 4s after rebooting it.

**Comment by franciscojma86** [comment]
This was a devicelab issue that has now been solved. The benchmarks are back to normal.

**Comment by matthew-carroll** [comment]
To verify, I checked out a red commit and green commit from the perf history. I ran the perf test against each commit, locally, twice. The timing results are below:

Red commit:
51.361, 50.413

Green commit:
58.216, 66.596

The result is that timing actually appears to be improved in the commit that triggered a benchmark failure in the dashboard. This seems to confirm that the issue was infra and not source code.

CC @Hixie
