### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.

### ISSUE THREAD

**Issue by saravananmnm** [flutter/flutter#42829]
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Saravanan\i-eX_Driver\iex_driver>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.137, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

C:\Saravanan\i-eX_Driver\iex_driver>

**Comment by BondarenkoStas** [comment]
Thank you @saravananmnm for the report! Can you come up with a small self-contained app that reproduces the problem? You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by prasant10050** [comment]
I am also facing this issue,please support me for solve this issue

**Comment by allenbrunson** [comment]
i get this error several times a day. it's harmless, but it's annoying, because it spams up the terminal, obscuring my own terminal output that i need to see for debugging.

it's going to be very difficult to isolate a test case. i spent several hours on it and gave up. could you guys please just take our word for it that this is happening? the fix is very easy.

in (package:flutter/src/widgets/navigator.dart:139:17) --

  @protected
  @mustCallSuper
  TickerFuture didPush() {
    return TickerFuture.complete()..then<void>((void _) {
      navigator.focusScopeNode.requestFocus();
    });
  }

all you have to do is change that one line to:

if (navigator != null) navigator.focusScopeNode.requestFocus();

... and the problem would be fixed. (or use the ? operator, i guess. personally i never do, because i think it's ugly and obscures intent.)

i keep making this fix in my own copy of flutter, and of course it keeps getting overwritten on every update.

please, guys. put me out of my misery.
