### ISSUE TITLE
AnimatedContainer ignores alignment specified

### ISSUE THREAD

**Issue by Hassan-Fa** [flutter/flutter#42856]
been trying to animate scale with **center** anchor point using AnimatedContainer like this :
```
 AnimatedContainer( // to animate scale
            duration: Duration(milliseconds: translationDuration),
            curve: Curves.fastLinearToSlowEaseIn,
            alignment: FractionalOffset.center,
            transform: Matrix4.diagonal3Values(1.0, generalTextScale, 1.0),
            child: ...)
```
but alignment is ignored and focalPoint [0,0] is used

am i missing sth ?
could use AnimatedController and ScaleTransition instead but AnimatedContainer is so much easier to use , so is there anyway to solve this problem ?

**Comment by Hassan-Fa** [comment]
so this isn't actually an issue ?
is there any easy solutions for this I missed?

**Comment by iapicca** [comment]
Hi @Hassan-Fa 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by luke14free** [comment]
I confirm that this issue is still a problem; if you use a normal `Transform` the alignment is respected and the transformation will apply over the correct focal point; while in an `AnimatedContainer` the "alignment" parameter is ignored and it is always 0-0 or topLeft. This makes it impossible to make rotations over the center of the widget using `AnimatedContainer`.

The only workaround is to use a custom tween and animate the Transform widget manually, which is a bit inconvenient.

**Comment by iapicca** [comment]
@luke14free 
I recommend to open a new issue providing you flutter doctor -v
and most importantly a **_minimal reproducible code sample_**
(w/o 3rd party packages or plugins)
