### ISSUE TITLE
iOS 13 Modal Presentation Style

### ISSUE THREAD

**Issue by jamesdixon** [flutter/flutter#42894]
Apologies if this already exists, but I'm trying to figure out if this style of modal presentation is available out of the box with the recent Flutter updates for iOS 13?

If not, is there a feature request for it that I may have missed (couldn't find anything in search)?

![image](https://user-images.githubusercontent.com/110114/66976829-980c9980-f060-11e9-8f1b-95f58de9429d.png)

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by justinmc** [comment]
This doesn't exist but it's coming soon!  Someone recently opened a similar issue (https://github.com/flutter/flutter/issues/42560) so I'm going to close this one as a duplicate.  I'll add some of your verbiage over there so that it comes up in future searches.

You can track all iOS 13 related stuff in this master issue that I created: https://github.com/flutter/flutter/issues/35026

I'll hopefully open up a PR for this in a few days, so you'll be able to track progress there.

**Comment by jamesdixon** [comment]
@justinmc thanks! I figured I was probably calling it the wrong thing :)

Cheers.
