### ISSUE TITLE
Focus traversal is unpredictable sometimes

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#42955]
For example, when moving between items in a list, sometimes the focus disappears.

![Focus traversal](https://user-images.githubusercontent.com/1278212/67045318-e5314f80-f0e2-11e9-945d-b3b6b5a701a5.gif)

All I'm doing in this screen recording is click "down" repeatedly until I reach the bottom, then click "up" repeatedly until I reach the top.

Notice how "Banner" doesn't receive focus. And the focus disappears between "Bottom sheet: Modal" and "Bottom sheet: Persistent".

cc @gspencergoog

**Comment by gspencergoog** [comment]
OK, I turned on the debugging in the `FocusManager` and I know what the problem here is.  It's not that focus is unreliable, it's that the gallery doesn't mark the items in the backdrop widget as not focusable. When the focus "disappears", try hitting the ENTER key and see what happens: it'll bring up the dropdown menu from the backdrop that it's focused on.

I also noticed that I forgot to plumb `canRequestFocus` and `skipTraversal` into the `FocusScopeNode`.  I'll have a PR shortly.
