### ISSUE TITLE
Material Design Feature Discovery

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4296]
https://material.io/archive/guidelines/growth-communications/feature-discovery.html#

Pieces flutter should probably provide (and demo in the Gallery):
- [ ] Tap Target colored overlay with help text and pulsing target area
- [ ] Straightforward way to trigger ripple effects on certain elements during guided flows
- [ ] Guided Flow helper class of some form to help orchestrate one of these.
- [ ] Completion Toast (just a styled active-colored bottom bar?)
- [ ] Hint Text widget 

Thoughts @Hixie @HansMuller?

**Comment by HansMuller** [comment]
I think this is really important feature, mobile apps are getting rather complicated, and it's not like users are going to read a manual.

I'll put demoing the features you've listed at the top of my short stack.

**Comment by sethladd** [comment]
Moving this out from Gallery App milestone. We can ship the gallery without this feature. It's a good feature for a v1.1 or later.

**Comment by mehmetf** [comment]
Leafy currently implements this in the native android app; we had to rely on the following features of Android platform to make it happen. Flutter solution might be drastically different:

- Find any widget in the widget tree and discover its coordinates on screen on layout complete.
- If the widget is currently not visible on screen, we should be able to find the scrollable parent and do programmatic scroll to make it visible. 
- Listen on scroll events to fire an event on scroll complete; i.e. be able to detect when the widget is now fully visible and the UI has settled.
- Overlay a view on top of the screen which prevents the user from interacting with the app. It should consume all gestures. Tapping on this view should advance the guided flow (or end it).
- Some way to highlight the aforementioned widget. We originally tried animating the background by triggering ripple but we found out that users didn't understand/discover that. So it would be better to hide irrelevant parts of the app:
Material does this: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B4kv-3uZbS1qeGJFTWZ0M2R6ZEE/useredu_er_featuredisc_design_01.png
We do this:
![image](https://cloud.githubusercontent.com/assets/6687929/17349135/439ddefc-58d0-11e6-92d3-d0b22943f0a6.png)

We achieved it by painting a gray rectangle and using "clear" paint to punch a hole. We then blurred the whole thing using renderscript and overlaid it. It is extremely hacky but it works well.
- Finally, a way to lay help text at specific coordinates on the screen. This can be part of the overlay widget itself.

If these capabilities are provided, we can contribute to flutter by writing a user-friendly version of it so that a list of widget tags and help texts is the only thing needed for the guided tour to run.

**Comment by eseidelGoogle** [comment]
My understanding is that this is not on leafy's top-asks list at current, so bumping this to M2.

**Comment by Hixie** [comment]
This is a bigish project for someone once we do it, and with so much on our near-term plate, I think we should wait until it's really an issue.

**Comment by meggamind** [comment]
@eseidelGoogle : Are the demos mentioned in the first comment still required, if so I can work on them.

**Comment by rrousselGit** [comment]
I can potentially work on these too.

But there's one thing I wonder :  What are the rules behind the first video about TapTarget [here](https://material.io/guidelines/growth-communications/feature-discovery.html#feature-discovery-design-patterns) ?

![screen shot 2018-04-02 at 6 44 35 pm](https://user-images.githubusercontent.com/20165741/38205188-f484ca00-36a5-11e8-9cba-319a4197706d.png)


As it doesn't seems to fit `mobile` rules. Shouldn't the example be similar to 

![image](https://user-images.githubusercontent.com/20165741/38205145-c7470a4e-36a5-11e8-9928-6c19bd48cb36.png)

?

**Comment by anderscheow** [comment]
It would be great if Flutter team could provide an official Feature Discovery library with long term support

**Comment by fabiocarneiro** [comment]
I think this is deprecated?! It was removed from material specs and only lives in the archive. 

I would like to know what was the study and motivation from Google to remove that, but unfortunately, I was not able to find or they don`t share the reasoning.

I think this is the new way to do that:
https://material.io/design/communication/onboarding.html

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by willlarche** [comment]
It has not been updated in a few years since it's lower in priority. But we have an internal version we'd like to open source that mirrors the expected existing spec.

**Comment by rahulraj64** [comment]
This is a crucial feature in making the app more user-friendly. Every now and then I visit this issue hopefully for checking any updates. 
@willlarche Please consider contributing this feature to the official Flutter repo or publishing this as a stand alone package like the Google's material design widgets for Android.

**Comment by creativecreatorormaybenot** [comment]
@willlarche Is this internal version already Flutter code?  
Then publishing it might even be beneficial without any polishing as it can take away a bunch of work from people (like me) trying to implement this.

**Comment by ayalma** [comment]
Use this [lib](https://pub.dev/packages/feature_discovery)

**Comment by EliuTimana** [comment]
is feature discovery still part of the MD specs? is not present in the docs anymore, just in the archive.

**Comment by jdeltoft** [comment]
I've been using the lib @ayalma mentioned now for many weeks.  I love it!  I've also been able to add commands right in the discovery text to "dismiss" or "skip tour" so users can skip all of them if they want.  And then a button under account profile to "take the tour" again.

Here are some code snipets:

```
  void initState() {
    SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
      if (SessionInfo?.of(context)?.mySkipTour == false) {
        FeatureDiscovery.discoverFeatures(
          context,
          const <String>{
            'search',
            'defaults',
            'add_new',
          },
        );
      }
    });
```

```
                              child: DescribedFeatureOverlay(
                                featureId:
                                    'search', // Unique id that identifies this overlay.
                                tapTarget: Icon(
                                  Icons.search,
                                  color: Theme.of(context).accentColor,
                                  size: 44,
                                ),
                                title: Text('Search For Spaces and Devices'),
                                backgroundColor: Theme.of(context).primaryColor,
                                targetColor: Colors.white,
                                textColor: Colors.white,
                                contentLocation: ContentLocation.below,
                                onDismiss: () =>
                                    featureDiscoveryDismiss(context),
                                description: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    const Text(
                                        'Tap the search icon to search for specific serial numbers, device names, or space names.'),
                                    Container(
                                      height: 10,
                                    ),
                                    Row(
                                      children: <Widget>[
                                        FlatButton(
                                            child: Text('Dismiss',
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .button
                                                    .copyWith(
                                                        color:
                                                            lightGreyMenuColor)),
                                            onPressed: () => setState(() {
                                                  FeatureDiscovery
                                                      .completeCurrentStep(
                                                          context);
                                                })),
                                        FlatButton(
                                            child: Text('Skip Tour',
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .button
                                                    .copyWith(
                                                        color:
                                                            lightGreyMenuColor)),
                                            onPressed: () => setState(() {
                                                  SessionInfo.of(context)
                                                      .skipTour();
                                                  FeatureDiscovery.dismissAll(
                                                      context);
                                                })),
                                      ],
                                    ),
                                  ],
                                ),
                                child: FlatButton(
                                    onPressed: () => searchDialog(),
                                    child: Icon(
                                      Icons.search,
                                      color: Theme.of(context).accentColor,
                                      size: 44,
                                    )),
                              ),
```

**Comment by Jerry-Lau** [comment]
Feature Discovery Library is long waited!

**Comment by arndt-s** [comment]
Just found this library: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview

**Comment by HansMuller** [comment]
This issue is now nearly 6 years old and although if would be an interesting project for the Flutter team, there are still no plans to do it. The Material Design spec only covered this topic in the [first version of the spec](https://material.io/archive/guidelines/growth-communications/feature-discovery.html#), it hasn't been included in any of the updates since about 2018.  So with that said, I am going to (finally) close this issue.
