### ISSUE TITLE
simple_animation_perf_iphonexsgpu_percentage regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43186]
Started with #42982, so if this is the case, could be related to the test infrastructure and not a real regression.

**Comment by franciscojma86** [comment]
There are a few commits before https://github.com/flutter/flutter/pull/42982 that didn't capture the benchmark results, but could've introduced the regression. Will try to reproduce.

**Comment by franciscojma86** [comment]
I ran the tests locally against HEAD and a healthy commit. The results are fairly similar, which leads me to believe this is an infra issue, maybe caused by the lab migration. I'll re-baseline the benchmarks.


Here are my results:
```

Commit | gpu percentage | 90th_percentile_frame_build_time_millis | 90th_percentile_frame_rasterizer_time_millis

HEAD 8cac409d90755c64466588109c422b25e4c6102e | 22.5000 | 1.7240 | 16.7850
-- | -- | -- | --
  | 21.7000 | 1.6070 | 2.0000
  | 22.1000 | 1.6010 | 2.7650
  | 22.0000 | 1.4540 | 16.7390
  | 21.9000 | 1.6710 | 16.8560
  | 22.1000 | 1.4670 | 2.1760
  
Average | 22.0500 | 1.5873 | 9.5535

1faf6a9a890749220cb9e33669781fa058e7ae06 | 22.2000 | 1.5940 | 3.1230
  | 21.9000 | 1.4920 | 16.7070
  | 21.8000 | 1.6640 | 2.6330
  | 22.1000 | 1.5140 | 1.9950
  | 22.3000 | 1.5660 | 2.2100
  | 21.9000 | 1.6300 | 16.8780
  
Average | 22.0333 | 1.5767 | 7.2577


```

Note that 90th_percentile_frame_rasterizer_time_millis is flaky, with most results around 2.5, but sometimes showing ~16.5 times.
