### ISSUE TITLE
test/integration.shard/hot_reload_test.dart flakiness

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#43464]
https://cirrus-ci.com/task/4742482515984384?command=main#L159:
```
01:51 +3 -1: test/integration.shard/hot_reload_test.dart: newly added code executes during hot reload [E]                                                                                              
  Expected: contains '(((((RELOAD WORKED)))))'
    Actual: '[{"event":"app.progress","params":{"appId":"506a800b-0dc4-41b0-b02e-ca4fe19c0ad0","id":"1","progressId":"hot.reload","message":"Initializing hot reload..."}}]\n'
              '[{"event":"app.progress","params":{"appId":"506a800b-0dc4-41b0-b02e-ca4fe19c0ad0","id":"2","progressId":null,"message":"Syncing files to device Flutter test device..."}}]\n'
              '[{"event":"app.progress","params":{"appId":"506a800b-0dc4-41b0-b02e-ca4fe19c0ad0","id":"2","progressId":null,"finished":true}}]\n'
              '((((TICK 2))))\n'
              '[{"event":"app.progress","params":{"appId":"506a800b-0dc4-41b0-b02e-ca4fe19c0ad0","id":"1","progressId":"hot.reload","finished":true}}]\n'
              'Reloaded 0 of 474 libraries in 215ms.\n'
              '[{"id":1,"result":{"code":0,"message":"Reloaded 0 of 474 libraries"}}]\n'
              ''
  package:test_api                                                      expect
  org-dartlang-app:///test/integration.shard/hot_reload_test.dart 45:7  main.<fn>
```

cc @DanTup

**Comment by DanTup** [comment]
Hmmm, this is weird. The test modifies a file on disk (adding a `print`) and then hot reloads, and this failure suggests that during the hot reload the `print` did not fire.

Assuming that the hot reload does not complete until after the build method has been called (which I'm fairly sure it does, and I'd expect this test to be super-broken if not) then I wonder if the hot reload *did not* load the new changes. We've got an open report of something like this happening, where a hot reload always has stale contents (changes from before the save, instead of after):

https://github.com/flutter/flutter/issues/32573#issuecomment-491831008
https://github.com/flutter/flutter/issues/32573#issuecomment-492186558

We could add a delay after writing the file, but that feels a bit like shotgun-debugging.

**Comment by DanTup** [comment]
Just saw this in my PR too:

https://cirrus-ci.com/task/6179374897823744?command=main#L906
