### ISSUE TITLE
Flutter CupertinoNavBar make leading content expand?

### ISSUE THREAD

**Issue by mana-ai** [flutter/flutter#43590]
Simillar question on stackoverflow:

https://stackoverflow.com/questions/58578386/flutter-cupertinonavbar-make-leading-content-expand

**Comment by pedromassangocode** [comment]
Hi @mana-ai 
It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

You can follow up on https://github.com/flutter/flutter/issues/36689 which is a feature request instead of a question.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
