### ISSUE TITLE
[web] Add support for spacebar Shortcut to include ScrollIntent

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#43694]
I am building web pages with Flutter Web and the widget layout is as follows.
```
Scaffold(
   body: SingleChildScrollView(
      child: Column(
          children: <Widget>[
              // page widgets
```

All of my widgets that build the content of the page are the children of the column. Scrolling works fine if I use my trackpad or click on the page and drag (which makes sense because this is how mobile applications scroll). I understand it is currently working as it was designed for mobile. However, there is no scroll bar on the side of the page as there normally would be with any other website. Since we can only make webpages scrollable by using nested scrollable widgets like SingleChildScrollView, there should be a way to recognize nested SingleChildScrollViews that hold the body of the webpage as being scrollable with a website scroll bar so that functions such as scrolling by pressing spacebar, page up/page down, up/down arrow keys or by using a side scroll bar are possible.

**Comment by khari998** [comment]
Don't know how this will be addressed but I have a suggestion for a way it could. You could set a boolean property on scrollable widgets such as "ContainsWebpageBody" that is by default set as false. When changing this value to true, the scrollable widget gets a scrollbar on the right side to mimic a webpage scrollbar and gets the functionality of webpage scrolling that includes scrolling by pressing spacebar, page up/page down, up/down arrow keys.

**Comment by khari998** [comment]
Please also extend this functionality to widgets like PageView. I am sure this can apply other types of widgets as well.

**Comment by Skquark** [comment]
This is a feature that deserves to be implemented.  I'm having same complaint with of of my projects that is primarily for web, not app, that looks real good in the browser, but the only way to scroll is with the mouse wheel.  I expected to be able to drag scroll with mouse or use the keyboard arrow keys, and can't find any way to hack it to be functional enough.
The changes should be added to CustomScrollView and SingleChildScrollView to work on web.  I was looking for a way to take the keyboard input to manually move the ScrollController, but not simple like I thought.  Was even considering making a custom scroll bar widget to wrap the ScrollView with to give it a customizable scroll bar in a stack on web platform, but would be nicer if we can use the browser's native scroller.  I know web support is still iffy, but this feels like a big missing piece at this point..

**Comment by esDotDev** [comment]
Yes, if Flutter is serious about building web apps, native scrollbar support is a must-have feature.

**Comment by khari998** [comment]
This is probably one of the most debilitating issues in terms of using Flutter for web because I have started building a web page with a lot of content on it. I can't really deploy it if no one can scroll on the website unless they are accessing the website from a mobile device. I really don't want to have to rebuild everything in another framework. I know Flutter Web isn't meant for production yet but this is definitely a big issue holding it back from getting there. Please give this one a deeper look soon. Thanks.

**Comment by khari998** [comment]
Applying overflow-y: auto as a css property makes elements scrollable in HTML for a reference point

**Comment by Zizico2** [comment]
I'm also stuck on this. I can scroll with noise wheal but touch scrolling is still enabled. My workaround is to disable ScrollingPhysics and then manually catch the mouse scroll and scroll the SingleChildScrollView manually. I might work on implementing a custom scroll bar but native scrolling would just be ideal (or non-native scrolling that would be undistinguishable from native scrolling for all major browsers).

**Comment by JasterV** [comment]
Hello, i have the same problem, page doesnt scroll hen i scroll with the mouse wheel or the touchpad

**Comment by esDotDev** [comment]
Just need some way to let that content be unbounded vertically, and let the native scrollbars do their thing. Easy right? ;)

**Comment by woutervanwijk** [comment]
+1. For flutter web it's quite essential

**Comment by Skquark** [comment]
At least the mouse scroll wheel support and drag is working reliably.  In my opinion, it doesn't need to use the native scrollbar of the browser, that'd be messy and break theme appearance. What it should be is a variation of the Scrollbar() component, but with more customizations to behave more like browser's scrollbar.  The difference to Scrollbar I'm picturing is options to have up/down arrows, option to keep from hiding, and a focus node type listener for keyboard keys to tell the ScrollController to animate scroll of up/down/pageup/pagedown/space/home/end... Seems simple enough, the only thing that might be complicated is focus for physical keyboard when there's other input fields on page.  It might be nice to have horizontal scroll support on that too, but less needed by most.  Any devs up for that challenge?

**Comment by santhonydo** [comment]
Working on my first flutter web project and came across this issue immediately. Hopefully something soon!

**Comment by lukepighetti** [comment]
This is a glaring usability issue. Everyone who touches my Flutter web website goes "ew gross!" when they try to select text and instead the viewport scrolls.

**Comment by Skquark** [comment]
I've been playing with making a ScrollBar package using a RawKeyboardListener to move the position on the ScrollController, and got it mostly working, so it's very possible to make a browser-like scrollbar with a bit more work, but it'd still be better as a built-in Flutter feature/fix rather than a hacked package..  I was modifying the official Scrollbar component, but the problem I discovered is it's not draggable and auto-hides.  I might try to add the keyboard options to the [draggable_scrollbar](https://pub.dev/packages/draggable_scrollbar) package instead.
Regarding trying to select text and scrolling instead, I think that's less of a big deal.  For that, I recommend you use the package [flutter_selectable_text](https://pub.dev/packages/flutter_selectable_text) for those text blocks that someone might want to copy to clipboard..

**Comment by khari998** [comment]
> I've been playing with making a ScrollBar package using a RawKeyboardListener to move the position on the ScrollController, and got it mostly working, so it's very possible to make a browser-like scrollbar with a bit more work, but it'd still be better as a built-in Flutter feature/fix rather than a hacked package.. I was modifying the official Scrollbar component, but the problem I discovered is it's not draggable and auto-hides. I might try to add the keyboard options to the [draggable_scrollbar](https://pub.dev/packages/draggable_scrollbar) package instead.
> Regarding trying to select text and scrolling instead, I think that's less of a big deal. For that, I recommend you use the package [flutter_selectable_text](https://pub.dev/packages/flutter_selectable_text) for those text blocks that someone might want to copy to clipboard..

We need these features to be native to web and not rely on 3rd party packages. I'm going to look into these as potential work arounds

**Comment by Skquark** [comment]
Ran into another glitch while trying to get the keys to move the scrollController.  I got it working using a RawKeyboardListener and taking the RawKeyEvent to animateTo the new scroll position, but that worked on Android Emulator, but not in Web browser!  It looks like RawKeyboardListener is not handling events from hardware keyboard.. Can somebody else confirm this issue?  I didn't find any existing bug reports on this except for it not working on iOS, which hasn't been resolved.  I could share my code, but it's standard use of a RawKeyboardListener with a focusNode and onKey: handleKeyboard, and it's firing on Android but not Web (and probably iOS).  Came so close to finishing my scrollbar keyboard hack implementation too.. This is more of a core issue that needs some love in the Flutter Web native code....

**Comment by ThomasJaeger** [comment]
Is there any update on this?

**Comment by JaviBonilla** [comment]
Hi @Skquark,

I forked your flutter-draggable-scrollbar repo, but I get a bunch of error when compiling, probably I am missing something, any idea? Thanks.

```
  error • The class '_DraggableScrollbarState' doesn't have a default constructor •
         lib/draggable_scrollbar.dart:131:45 • new_with_undefined_constructor_default
  error • Missing concrete implementation of 'State.build' • lib/draggable_scrollbar.dart:314:7 •
         non_abstract_class_inherits_abstract_member
  error • Methods must have an explicit list of parameters • lib/draggable_scrollbar.dart:357:3 •
         missing_method_parameters
  error • The name of a constructor must match the name of the enclosing class •
         lib/draggable_scrollbar.dart:357:3 • invalid_constructor_name
   info • Use `;` instead of `{}` for empty constructor bodies • lib/draggable_scrollbar.dart:357:26 •
          empty_constructor_bodies
  ..........
  160 issues found. (ran in 12.8s)
```

**Comment by Skquark** [comment]
It was a work in progress, I was starting to get it to implemented, but had a side version that was modifying Flutter's Scrollbar widget that I wanted to get going first.  I got it going on android, but as I mentioned there was no response from the RawKeyboardListener on Web, so I put it on hold until that part got fixed first since there doesn't seem to be any other way to process a key press in Flutter.
Regarding my forked [flutter-draggable-scrollbar](https://github.com/Skquark/flutter-draggable-scrollbar) experiment, I just fixed those errors you got, so you can try again.  I don't know if it's done enough to function since I haven't tested, but it's at least a good starting point if anybody wants to play with it and see if they can take the mods further.  Would be nice to have it as a workaround until they fix the problem at the core, but Flutter Web is still a work in progress..

**Comment by JaviBonilla** [comment]
Thanks a lot @Skquark, I will test it.

**Comment by mdebbar** [comment]
@Skquark I read the documentation and it looks like the `focusNode` that you pass to `RawKeyboardListener` has to be focused in order to receive key events. This means the focus has to be somewhere within the widget tree under the `RawKeyboardListener`.

I tried adding `RawKeyboardListener` in multiple places in the flutter gallery app, and it works fine when the focus is in the right place. If you want to always receive key events, put the `RawKeyboardListener` as high as you can in the tree.

Could you please try 2 things so we can start pin pointing the source of the issue:

1. Place the `RawKeyboardListener` at the top of your widget tree.
1. Add `print('Key event: ${event.data.logicalKey.debugName}');` in https://github.com/flutter/flutter/blob/456d80b9ddd74b4b5ca3b77bbfb70ab0e05d3fa8/packages/flutter/lib/src/services/raw_keyboard.dart#L523-L525

If you are placing the `RawKeyboardListener` inside the scrollable area, there's a good chance it won't work until you focus on something inside the scrollable view. You could try to use `RawKeyboard.instance.addListener/removeListener` directly instead of going through `RawKeyboardListener`. `RawKeyboard` will always give you key events regardless of focus. But you need to be careful because there could be other widgets consuming key events too (e.g. text fields).

cc @gspencergoog who might shed some more light on how focus and keyboard events work in Flutter.

**Comment by khari998** [comment]
We definitely need a native solution for this issue. It is probably the main issue holding me back from using Flutter Web at the moment. I have to split codebases between Angular/React for web and Flutter for mobile

**Comment by Skquark** [comment]
Agreed that it should be native inside the SingleChildScrollView & CustomScrollView or deeper where it handles the mouse ScrollWheel since that's scrolling well on web.  We're just trying to find a bandaid until then.
I put the RawKeyboardListener inside the Scrollbar component which wraps the SingleChildScrollView, and I'm not using any other focusNodes inside it.  Like I said, it works the way it should on Android, but it does not work as a deployed build web.  As an update, I just tried as web debug test and was shocked that it worked there in the browser localhost!  So RawKeyboardListener is firing when you run in web debugger, but not after I upload build to ftp and browse where it matters.. What's up with that? 
If someone else wants to confirm this, here's my simple mod of Flutter's Scrollbar component you can try:
https://gist.github.com/Skquark/c33538aa7f2bd25779ab11a837331b6a

**Comment by JaviBonilla** [comment]
Hi @Skquark,

The `package:flutter/GoodScrollbarPainter.dart` file is missing.

**Comment by Skquark** [comment]
Oh yeah, forgot I had to clone that one too and was making some mods there to add features.  Here's the link for that: https://gist.github.com/Skquark/c33538aa7f2bd25779ab11a837331b6a#file-goodscrollbarpainter-dart
I could make it as a full addon package, but it wasn't ready for that yet, especially since it didn't solve the primary problem of navigating with the keys in browser.  Good enough to copy/paste file to you project and wrap your existing ScrollView in the GoodScrollbar component to test.

**Comment by iapicca** [comment]
related to https://github.com/flutter/flutter/issues/40107

**Comment by zibizz1** [comment]
I've solved that this way. But it scrolls outer and inner scroll at the same time

`Scaffold(
   body: RawKeyboardListener(
      onKey: (k) => _handleKey(k, context),
      focusNode: _focusNode,
      child: CustomScrollView(
       controller: _scrollViewController,
      child: Column(
          children: <Widget>[
              // page widgets

void _handleKey(RawKeyEvent value, BuildContext context) {
    if (value.runtimeType == RawKeyDownEvent) {
      var size = _scrollViewController.position.viewportDimension;
      double offset;
      if (value.logicalKey == LogicalKeyboardKey.arrowDown)
        offset = _scrollViewController.offset + 50;
      if (value.logicalKey == LogicalKeyboardKey.arrowUp)
        offset = _scrollViewController.offset - 50;
      if (value.logicalKey == LogicalKeyboardKey.pageDown)
        offset = _scrollViewController.offset + size;
      if (value.logicalKey == LogicalKeyboardKey.pageUp)
        offset = _scrollViewController.offset - size;
      if (offset != null) {
        offset = offset.clamp(_scrollViewController.position.minScrollExtent,
            _scrollViewController.position.maxScrollExtent);
        _scrollViewController.jumpTo(offset);
      }
    }
  }
`

**Comment by Skquark** [comment]
@zibizz1 That's basically what I had in my ScrollBar component, only difference is having the RawKeyboardListener at the top directly under Scaffold.  However, in my test it still doesn't work on the web.  Can you confirm that this works if you do a flutter build web, then upload to website and open in browser?  I know it works on Android and web debug, but not in a deployed release where it mattered.  Thanks.

**Comment by zibizz1** [comment]
@Skquark I have only web app. I had to call _focusNode.requestFocus(); to be able to catch keyevents but that breaks keyboard on mobile browser, so it is not great.

**Comment by pedromassangocode** [comment]
Hi @khari998 
Are you still facing this issue? if yes, can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by wilpar** [comment]
@pedromassango yes this is still an issue. Will be attempting the workaround from @zibizz1 until this core functionality is in.

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-CA)
    • Flutter version 1.22.0 at /Users/rhof/work/flutterSDK
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rhof/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

**Comment by Piinks** [comment]
Bad bot, reopening.

**Comment by khari998** [comment]
Thank you for reopening. I didn't get notifications for this thread. Having a scrollbar is the most important feature I can think of to begin to actually use Flutter web in production. Definitely will be a welcome addition.

**Comment by Piinks** [comment]
Going to reopen this for a moment longer, I'd like to add the space bar as a default web shortcut for scroll actions.

**Comment by sanalkv** [comment]
so until the scrollbar feature is added for flutter web, we will have to manually listen to mouse wheel scroll and keyboard arrow keys for page scroll :(

**Comment by creativecreatorormaybenot** [comment]
@sanalkv Mouse wheel scroll already works.

**Comment by sanalkv** [comment]
> @sanalkv Mouse wheel scroll already works.

Is it available in Beta channel ?

**Comment by Piinks** [comment]
> so until the scrollbar feature is added for flutter web, we will have to manually listen to mouse wheel scroll and keyboard arrow keys for page scroll :(

@sanalkv 

Default keyboard navigation was added in https://github.com/flutter/flutter/pull/70893. By specifying a scroll view as the `primary` for a given route, ScrollActions initiated by keyboard Shortcuts will apply to that scroll view by default, regardless of the location of the current focus.

The space bar is a special case though, since right now Shortcuts do not support binding more than one Intent to a LogicalKey. The space bar is already tied to the activate intent, so we need to find a way to include a ScrollIntent for the space bar at the same time. 

Mouse wheel scroll is already supported as well. That was added a while back AFAIK.

**Comment by Piinks** [comment]
I am going to rename this issue to reflect the remaining work for this specific issue. I have some ideas to propose how to implement the space bar as both an activate intent and a scroll intent. Updating the milestone as well as this last portion will probably be handled after the holidays. :)

**Comment by khari998** [comment]
@Piinks  was a scrollbar added? That's the biggest issue I have been looking forward to a solution for. My webpages need a scrollbar. Otherwise, they are unusable in production.

**Comment by Piinks** [comment]
> @Piinks was a scrollbar added? That's the biggest issue I have been looking forward to a solution for. My webpages need a scrollbar. Otherwise, they are unusable in production.

Please follow #70866 for scrollbars.

**Comment by sanalkv** [comment]
> @Piinks was a scrollbar added? That's the biggest issue I have been looking forward to a solution for. My webpages need a scrollbar. Otherwise, they are unusable in production.

Mouse wheel scroll is available in latest flutter beta channel. For scrollbar use scrollbar widget and set isAlwaysShown property as true.

**Comment by devanflores** [comment]
How do i prevent spacebar from scrolling if a textfield is in focus?

**Comment by Piinks** [comment]
> How do i prevent spacebar from scrolling if a textfield is in focus?

Hey @devanflores that is separate issue that is currently being worked on. You can track progress here:
https://github.com/flutter/flutter/issues/47156 and https://github.com/flutter/flutter/issues/70507

**Comment by GyuriMajercsik** [comment]
> How do i prevent spacebar from scrolling if a textfield is in focus?

As a workaround for Flutter web you can just remove the default shortcut for [`space`] in the following way: 

```
    import 'package:flutter/foundation.dart';
    ....
    return MaterialApp(
      shortcuts: {
        ...WidgetsApp.defaultShortcuts,
        if (kIsWeb) LogicalKeySet(LogicalKeyboardKey.space): null,
      },

```
