### ISSUE TITLE
Host messages should let you discover what is registered

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4371]
We should add a message that dumps the list of registered callbacks.

**Comment by abarth** [comment]
@collinjackson Is this still worth doing?

**Comment by collinjackson** [comment]
If I remember correctly, we wanted this to allow wrappers around native host messages to detect when the native side hadn't been set up correctly and log an error. If a handler isn't registered, sendJSON will complete with null, and that can be distinguished from an empty JSON object, so it is possible to accomplish this goal with the current setup.

Is there a reason not to throw an error instead of completing with null? That would make for an informative log message if the error isn't caught, but maybe there are some use cases for sending messages to nonexistent handlers that I haven't thought of.

**Comment by abarth** [comment]
Sounds like fixing #5962 would be sufficient if we make non-existent handlers return errors.

**Comment by collinjackson** [comment]
Agree, I think we can close this one.
