### ISSUE TITLE
Print message when app is using the Android embedding v1 and a plugin using v2

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#43779]
This will require a go link with some actionable information.

**Comment by xster** [comment]
If the pubspec plugin class name is wrong, we should point the plugin consumer to go open an issue on the plugin supplier. 

Otherwise, platform_plugins.dart _getEmbeddingVersion probably needs a bit more info for whether old embedding usage even exists in the plugin to determine if we need to show an error. 

Point to https://github.com/flutter/flutter/issues/36491

**Comment by xster** [comment]
Point to flutter.dev/go/android-project-migration

**Comment by mklim** [comment]
@blasten @xster the PR that merged to close this doesn't just print a message, it actually throws an exception and crashes if any of the plugins in a project have v2 embedding support. Should we really be actually crashing here? This effectively makes any of the plugins with v2 embedding support unusable on more recent versions of Flutter unless users are already using the v2 embedding or willing/able to migrate. The plugins weren't updated with major version bumps and this makes them a form of breaking change too, so this will effectively break semver for the affected packages.

I think it would be better to keep them backwards compatible for longer if possible.

/cc @escamoteur

**Comment by mklim** [comment]
Oh, sorry--on a second look at that PR, it is attempting to _just_ print a warning if the plugin also has support for v1. There must be a bug somewhere. I'll comment on the PR.

**Comment by xster** [comment]
@mklim, I tihnk the issue you're pointing to is now solved in #44214. Can you confirm?

**Comment by mklim** [comment]
Yes, that was the forward fix.
