### ISSUE TITLE
Horizontal ListView a11y scrolls in wrong direction on iOS

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#43883]
Internal: b/143653210

Consider a ListView(scrollDirection: Axis.horizontal). On iOS, when I use 3 fingers to a11y scroll horizontally then the content should move in the same direction as my fingers, but instead it moves opposite.

For instance if the horizontal list view children are numbered 0-9 LTR then:
3 fingers physically swipe from right to left => list view should also move RTL to reveal higher-numbered children
3 fingers physically swipe from left to right => list view should also move LTR to reveal lower-numbered children

Note that vertical scrolling is OK; the content moves in the same direction as my fingers. This axis is WAI and matches standard iOS a11y scroll behavior, for example horizontally between home screen pages or vertically in the notification center.

----
Here's a layout that demonstrates the difference in a11y scrolling direction in both axes

```dart
MaterialApp(
      home: Scaffold(
        body: ListView(
          children: List.generate(
            childCount,
            (i) => SizedBox(
              height: 100,
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: List.generate(
                  i == 4 ? childCount : 1,
                  (j) => Container(
                    color: colors[(i * childCount + j) % colors.length],
                    width: 100,
                    child: Center(
                      child: Text(
                        'ROW$i\n\nCOLUMN$j',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
```

**Comment by goderbauer** [comment]
Looks like we have the scroll direction mapping messed up in our iOS to Flutter mapper:

https://github.com/flutter/engine/blob/fe0838e94860d30ea68a2f3dda52be17ca20411a/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L26-L39

UIAccessibilityScrollDirectionRight probably needs to map to flutter::SemanticsAction::kScrollRight and UIAccessibilityScrollDirectionLeft to flutter::SemanticsAction::kScrollLeft.

(This is not as embarrassing as it sounds because due to Natural vs Reverse Scrolling, UIAccessibilityScrollDirectionUp actually needs to map to flutter::SemanticsAction::kScrollDown and UIAccessibilityScrollDirectionDown needs to map to flutter::SemanticsAction::kScrollUp).

/cc @darrenaustin Any chance you can take a look at this?
