### ISSUE TITLE
[web]: Looks like fluttertoast package doesn't work yet

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#43928]
Just reporting that I noticed that flutter for web doesn't seem to support this package yet.

https://pub.dev/packages/fluttertoast

I do NOT see any errors reported in the console.

**Comment by Abdusin** [comment]
you have to share more details about yout project ... 
your code 
flutter doctor -v
flutter analyze

**Comment by stuartmorgan** [comment]
That's a plugin package, which means it has native code for each platform it supports. The plugin would need to be updated to support web explicitly. It's not a question of Flutter for web supporting it, but it supporting Flutter for web.

Closing since that's a third-party plugin; yours need to request support in the plugin's project.
