### ISSUE TITLE
Start up tests requires the device to be awake in the Android embedding v2 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#44004]
The tests `flutter_gallery__start_up`, `platform_view__start_up` and `smoke_catalina_start_up` require the device to be awake when the app under test is migrated to the new embedding.

Here's the logs:

**Current embedding**:
https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvOGUwNzk5YTY1NzA1MWJmNTQwZDk4YjhhZWNmOWNmYTEzMjVmM2Y3MQwLEgRUYXNrGICAkI3UjokKDA

**New embedding**:
https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvNzkzMjNmN2MxMzdhMjhmMzZhYzI3ZTU4OWY0YzgwZGM3Yzk2YzA3MgwLEgRUYXNrGICAkO3Fiv8IDA

**Missing events from the VM (When the device is in sleep mode):**
```
2019-10-30T23:39:25.353355: stdout: [ +415 ms] Notification from VM: {streamId: Extension, event: {type: Event, kind: Extension, extensionKind: Flutter.Frame, isolate: {type: @Isolate, id: isolates/4226900115933295, name: main, number: 4226900115933295}, timestamp: 1572503967749, extensionData: {number: 1, startTime: 728297322002, elapsed: 311011, build: 2687, raster: 307937}}}
2019-10-30T23:39:25.354244: stdout: [        ] Notification from VM: {streamId: Extension, event: {type: Event, kind: Extension, extensionKind: Flutter.FirstFrame, isolate: {type: @Isolate, id: isolates/4226900115933295, name: main, number: 4226900115933295}, timestamp: 1572503967750, extensionData: {}}}
```

**Comment by blasten** [comment]
@matthew-carroll can you think of anything that might be causing this issue?

cc @xster

**Comment by xster** [comment]
Actually I'm not sure if this is it (leaving the screen off). Locally, I can't even get the old embedding on head to pass with the screen off.

**Comment by xster** [comment]
@liyuqian I'm also have some suspicion of the current implementation for detecting how to `stopTracingAndDownloadTimeline`. Based on https://github.com/flutter/flutter/blob/ade8dfac3dfb4d2ea04b45ff589fd073d8fc4274/packages/flutter/lib/src/widgets/binding.dart#L768, it seems like we're hardcoding the fact that we're registering a callback on the first frame (which we happen to know is a pre-warm) and that the second frame is the first valid frame that we want to unblock tracing on.

**Comment by xster** [comment]
So I've been playing around a bit and made some comical discoveries around startup tests, flutter_tools tracing, the WidgetsBinding's first frame callbacks, the old embedding and the device lab phones. 

# Moto G4
It turns out the old embedding can only work on the Moto G4. I tested on a whole bunch of other phones and they can't pass the startup tests with the screen off on the old embedding. After some digging, it turns out the Moto OEM's AOSP is totally not respecting the Android API's contracts (e.g. `onResume(). When the activity enters the Resumed state, it comes to the foreground, and then the system invokes the onResume() callback. This is the state in which the app interacts with the user`). 

Instead, onstart, onresume, onpause, onstop all get called **while the screen is off**. (It also creates a surface on the view and attaches it to the window while the screen is off, which is unexpected too). 

We would always schedule a warm-up frame and count the second frame after that. This incorrect lifecycle traversal was what allowed the the animator to get turned on momentarily via lifecycle resumed|inactive and created a second frame which fulfilled the start-up trace.

# Old vs new embedding

Why does the new embedding also not successfully exploit this loophole and run? On activity onstop, we're now detaching the flutterview from the engine. https://github.com/flutter/engine/blob/7aa40556a42d0bbc66deb207321a78551d10d654/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L403 This causes a call to surface destroyed. So via a thread hops (where the onstop would have been slow to stop the animator to prevent the second frame), we're increasing the odds of letting the second frame draw attempt happen after the surface is destroyed, which stops it. 

In other words, startup tests only worked in the past by the most strenuous series of incorrect behaviors happening in a lucky sequence. The Moto OEM Android sends incorrect lifecycle events, the Moto OEM Android isn't strict in enforcing UI and surface event sequences (unlike iOS which crashes on gl surface operations after UI 'onStops') and the thread hop sequence let an invisible frame squeeze through. 

In general, all current startup tests which runs with the screen off are invalid since they don't correspond with the behavior of correctly implemented Android (which most of our users are presumably using). 

I think the right course of action should be to use the Android developer options to keep the screen on (maybe with the backlight off) if we want to keep these startup tests.

cc @godofredoc @liyuqian @jason-simmons

**Comment by matthew-carroll** [comment]
The recommended course of action sounds good to me. Thanks for delving into
all that.

**Comment by liyuqian** [comment]
Agree that we should keep the screen on (I believe it's also the documented setup in the device lab doc).

As for the first frame callback, unfortunately the engine can't differentiate whether a frame is a real one or just a pre-warm frame. Other than the first frame, the engine will try to batch the callback for multiple frames into one to save some overhead, and there could be a latency up to 1 second before the callback is issued. Do you need something like "for the first 10 frames, issue the callback immediately"?

**Comment by godofredoc** [comment]
We now have +20 android devices and ensuring they all have the screen on
manually won't be scalable. We will implement it as health check and device
recovery. How urgently we need to land this change to prioritize the
health check and recovery in infrastructure properly?

**Comment by liyuqian** [comment]
@godofredoc I don't know the priority for this specific issue, but I can imagine that most of our performance benchmarks will be incorrect if the screen is turned off. I think whenever we add a new device to the lab, we should follow some protocol to make sure that it turns "stay awake" on?

**Comment by xster** [comment]
I don't think we need to do anything manually. The screens can be kept one one time per hardware install
![aid9091950-v4-900px-Keep-the-Screen-on-While-Charging-on-Android-Step-6](https://user-images.githubusercontent.com/156888/68147933-ed192e00-feef-11e9-8a50-bc0fe40d3ceb.jpg)


This is blocking the add-to-app release. We should disable the startup tests (since they don't really produce real data) or keep the screens on somehow within the next day or 2.

**Comment by godofredoc** [comment]
All the phones have "stay awake" checked and some of them are still going
to sleep. Not sure if somehow the setting for sleeping after 30 mins is
interfering with "stay awake" or maybe we just pressed the power button
after installing some of those phones. I'll ask the current on call to
check all the phones have the display on.

**Comment by xster** [comment]
The sleep timer setting shouldn't interfere (unless the Moto OEM did something different again :D). But pressing the power button will definitely throw them off.

**Comment by godofredoc** [comment]
I just came back from the lab, the manual setup works properly until we
start running tests . Also found that we are explicitly sending the phone
to sleep by pressing the power button after running a test
https://github.com/flutter/cocoon/blob/master/agent/lib/src/commands/ci.dart#L130.
Probably we just want to wake up the phone before running the test.

**Comment by xster** [comment]
Oh interesting. Your proposal sounds great if that's doable via adb.
