### ISSUE TITLE
background service for notification and also tracking a person for every 15min

### ISSUE THREAD

**Issue by eswarvarma-dev** [flutter/flutter#44104]
Hi,

i need a help in background service which should work like messaging apps even if app was closed.
i am doing project for tracking for every 15min and also notification building i am not getting like how to do it i have tried background_fetch but i am not clear with it.  can you please suggest me the way or with any good pub suggestion to solve my problem..

 Thank you.

**Comment by iapicca** [comment]
Hi @eswarvarma-dev 
This platform is not met for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.

I'd like to recommend you this [article ](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124), 
not just because it's suggested in the [documentation](https://flutter.dev/docs/development/packages-and-plugins/background-processes), 
but I've followed it myself.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by eswarvarma-dev** [comment]
ok
