### ISSUE TITLE
☂️ Desktop resize is janky

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#44136]
Split off from #30671. See the second part of the original post, and [this doc](https://docs.google.com/document/d/1OTy-qCGdP7tYfrEKCNX9A24sgnx5vshfK6FupfniyxA) for more context, but in summary resizing, at least on macOS, causes extremely visually janky "jumping" of content relative to the upper-let corner, and on all platforms expanding flashes a color that may be very jarring (e.g., black in a mostly-white app) in the new regions.

Update by @iskakaushik on Sep 23, 2020:

I've made this issue an umbrella issue to cover desktop resize issues across all desktop platforms. This issue will be considered closed when all the sub-issues are fixed. My understanding is that the behavior in linux is good (not janky). This now tracks smooth resizing for macOS and windows (non-UWP).

Update by @knopp on May 3, 2021

This is actually a problem in Linux as well, reopening the issue until Linux resizing is fixed.

- [x] https://github.com/flutter/flutter/issues/66475
- [x] https://github.com/flutter/flutter/issues/66476
- [x] https://github.com/flutter/flutter/issues/81677

**Comment by DrBendson** [comment]
Don't resize. Please clean cd-rom

**Comment by knopp** [comment]
I'm not sure if this have to be so complicated. I've got proof of concept implementation for smooth resizing on macOS available [in my fork](https://github.com/knopp/engine/tree/macos_resize_experiment).

Before
<img src="https://i.imgur.com/FwI6jN1.gif" width=370></img>

After
<img src="https://i.imgur.com/y46EumT.gif" width=370></img>

To get smooth content resizing synchronized with window resizing, two changes are required:

### Rendering and rasterizing must be done synchronously while AppKit view size is being updated

This means holding the platform thread (on macOS it is same as rasterize) while shell obtains the layer tree and then rasterizing the layer tree *before* returning from NSView size update notification.

While waiting for layer tree, the shell should discard any layer tree with wrong size, i.e. possible leftover from previous frame.

### Ensuring that OpenGL context update is synchronized with CoreAnimation transaction

The step before solves half of the problem, but unfortunately it's not a complete solution. The main issue remaining is that `[NSOpenGLContext flushBuffer]` often updates the view too early, because it's not synchronized with core animation transactions.

For metal this should be fixable using `presentsWithTransaction`, sadly opengl has no similar property.

One way to fix this for OpenGL is to create `IOSurface` backed context and set the surface as view layer content. This is synchronized with current transaction. The drawback is, that this possibly relies to `[CALayer setContentsChanged]` call, which is not documented. As far as I can tell, both Safari and Chrome are using this. Alternative to this is using `CGIOSurfaceContextCreateImageReference`. At this point I'm not sure if either of these is mac Appstore safe.

The benefit of using `IOSurface` backed rendering is, that if at any point Flutter supports rendering of only changed part of layer tree, we can use multiple CALayers to simulate partial updates (there is no API for partial redraws on macOS for either OpenGL or Metal). This could make quite a large impact on energy saving when only small part of window is updating.

**Comment by iskakaushik** [comment]
@knopp thanks for your PoC. I'm also working on solving this problem, and I have a WIP PoC with some problems to fix: https://github.com/flutter/engine/pull/20824.

> Rendering and rasterizing must be done synchronously while AppKit view size is being updated

This will work, but potentially problematic as we could block the main thread for a long time while the frame is being produced in dart. Also limits out capability to separate the platform thread from the raster thread at a later point in time. As as alternative to this, I am rendering to an off-screen texture and then blitting it to the window FBO after aligning it to top left. This is what Chrome does and leads to a smoother resize experience. [Look at this video (minus the red outline)](https://photos.app.goo.gl/Zycdoaa5txUvxv768).

> Ensuring that OpenGL context update is synchronized with CoreAnimation transaction

This could potentially be a reason why i'm seeing blobs rather than text sometimes. 
![blobs](https://user-images.githubusercontent.com/1006071/91589997-7a11f580-e90f-11ea-9b74-e3af0066ed68.png). I will explore the solution you mentioned with `[CALayer setContentsChanged]`. I haven't looked at your change completely yet, but https://github.com/knopp/engine/commit/f8d36d4effbe6f1bc1a33da30bd03d6ef5caff17#diff-1909269bde88434c8f297743ebc537e7R55 looks relevant for me.

**Comment by knopp** [comment]
> This will work, but potentially problematic as we could block the main thread for a long time while the frame is being produced in dart. Also limits out capability to separate the platform thread from the raster thread at a later point in time. As as alternative to this, I am rendering to an off-screen texture and then blitting it to the window FBO after aligning it to top left. This is what Chrome does and leads to a smoother resize experience. Look at this video (minus the red outline).

I was worried you'd want to go this way. If you don't synchronize this with the platform thread, you will unfortunately never get resizing comparable to native toolkits. For example, if you resize left corner of electron app, you will see that everything right-aligned moves around. It feels like a web view, not a UI toolkit.

If you try out my commit, you'll see that the resizing is perfect, without glitches and every right aligned element stays right aligned when resizing left border.

I think this can work even when raster thread being separate.

I'm going to look at your PR, but I don't quite see why you'd need to create FBOs and pool them. My implementation basically only needs one IOSurface alive at a time.

**Comment by knopp** [comment]
Your implementation also seems to be doing additional work, as each FBO, needs to be blitted. That's lot of extra pixels moved for a 4k window.

**Comment by iskakaushik** [comment]
> I'm going to look at your PR, but I don't quite see why you'd need to create FBOs and pool them. My implementation basically only needs one IOSurface alive at a time.

My implementation is a work in progress. I am prototyping to see if it works - definitely has scope for improvement. To answer your questions, we can have multiple frames in flight being rendered by the raster thread that haven't yet been presented, the render target pool should probably be renamed to something that conveys that.

> Your implementation also seems to be doing additional work, as each FBO, needs to be blitted. That's lot of extra pixels moved around for a 4k window. OpenGL in macOS is already double buffered by WindowServer.

We could change it to only happen during resize as mentioned [here](https://docs.google.com/document/d/1allwMZXgX9gGVPguFy3-XydjXEIJgYR1Uhz8Vhm9Rrs/edit#heading=h.yrdho02lmad9). This will still be expensive during the resize operation.

> For example, if you resize left corner of electron app, you will see that everything right-aligned moves around. It feels like a web view, not a UI toolkit.

> I think this can work even with raster thread being separate.

Do you have any ideas on how that could be done? The two things I see as being potentially problematic with the approach in the patch you proposed are that resize could continue to be janky in cases where the raster thread is overloaded. We also don't do synchronous drawing while resizing or any platform updates on other platforms. So that is something we'd also want to weigh it against.

@knopp Are you on [discord](https://github.com/flutter/flutter/wiki/Chat#chatting-on-discord) by any chance? I'd love to brainstorm more about this issue in a synchronous way. If not, no worries, we can continue our conversation in this thread.

**Comment by knopp** [comment]
@iskakaushik, I didn't mean to sound brash, I apologize if it came across that way. Discord might be better place to discuss this.

**Comment by iskakaushik** [comment]
> @iskakaushik, I didn't mean to sound brash, I apologize if it came across that way. Discord might be better place to discuss this.

Nope, it's all good 😊

**Comment by knopp** [comment]
@iskakaushik forgot to mention, the name on discord is matt_kn, you can ping me when you're there.

**Comment by iskakaushik** [comment]
@knopp strange, I don't find you on the discord server: https://discord.gg/BS8KZyg. Could you join there please? I'm `iskakaushik` there as well. Thanks!

**Comment by iskakaushik** [comment]
@knopp and I had a productive conversation. The main takeaways for me were:

1. The resize experience with sync rendering (blocking the platform thread during resize) is significantly smoother than what I was seeing with renedr-to-texture-and-blit.
2. Using IOSurface lets us avoid an extra blit in https://github.com/flutter/engine/pull/20824.
3. This also lets us get around the synchronization problem we have with `[NSOpenGLContext flushBuffer]`.

There are a couple of trade-offs:

1. Is it acceptable to block the platform thread during resize. (Unlike iOS this might not be a huge deal in macOS)?
2. Would usage of `[CALayer setContentsChanged]` which is a private API be acceptable? This is [used in chromium](https://chromium.googlesource.com/chromium/src.git/+/master/ui/accelerated_widget_mac/display_ca_layer_tree.mm#20) FWIW.
3. Will this take us farther from a world where raster thread and platform thread are discrete?

@knopp has graciously offered to prepare a design document detailing his approach and listing the tradeoffs. I am going to hold-off on https://github.com/flutter/engine/pull/20824.

**Comment by knopp** [comment]
Just want to mention that if `[CALayer setContentsChanged]` turns out to be problematic there might be ways to avoid using it. It's not actually needed during resizing (since different IOSurface instances are allocated for each size).

**Comment by knopp** [comment]
I fell bit stupid for not realizing this sooner
```
  [self.layer setContents:nullptr];
  [self.layer setContents:(__bridge id)_ioSurface];
```
seems to force layer update just like
```
  [self.layer setContentsChanged];
```
does. Without having to use undocumented selector.

**Comment by ansarizafar** [comment]
Microsoft Windows desktop apps have the same janky resize issue.

**Comment by stuartmorgan** [comment]
> Is it acceptable to block the platform thread during resize.

One significant concern that's been raised about this in previous discussions: what happens if someone uses a platform channel call while building?

> Would usage of [CALayer setContentsChanged] which is a private API be acceptable? This is used in chromium FWIW.

It sounds like this is resolved, but in case it's not: definitely not. The fact that Chromium uses it is irrelevant; Chrome isn't an App Store app. Preventing any developer using Flutter from choosing to distribute their app there is a non-starter.

**Comment by stuartmorgan** [comment]
> Microsoft Windows desktop apps have the same janky resize issue.

Yes, this is labeled as relevant to all desktop platforms. The solutions may or may not vary by platform, depending in what the best options are in each case.

**Comment by stuartmorgan** [comment]
It would be useful to add comments to the doc linked in the original comment, and have some of the discussion there. Some of the pro/con discussion above is rehashing things that are already in that doc, and the parts that aren't already captured there should be.

**Comment by knopp** [comment]
@stuartmorgan, for now it seems that no undocumented API is needed; 

As for main thread being blocked, it is indeed a problem for platform channel. Fortunately `CFRunLoop` supports running recursively, so fingers crossed, it should be possible to make platform channel messages go through while also holding the resize event; I'm working on prototype that does this (while also pushing the raster queue back to separate thread). We'll see how it goes.

**Comment by knopp** [comment]
I published [macos_resize_experiment2](https://github.com/knopp/engine/commits/macos_resize_experiment2) branch with different implementation, which
- works with raster task on separate thread (yay)
- runs the run loop while blocking resize event, so things like platform channel messages should be uninterrupted
- doesn't use any undocumented methods

As far as I can tell it performs as well as previous attempt, I couldn't get any glitches, crashes or lock-ups with flutter gallery. I'll try to write a design doc soon.

**Comment by knopp** [comment]
I've put together a [design document](https://docs.google.com/document/d/1slGllp1Jhde7wkF6snqGhdrZwHV1VVmXeIF3f0t24JU/edit?usp=sharing).

**Comment by stuartmorgan** [comment]
@knopp Thanks, that design doc looks great! @iskakaushik and @chinmaygarde should definitely review it and weigh in; I know @chinmaygarde has had strong concerns about cross-thread blocking and may have specific cases in mind where it could result in deadlocks.

**Comment by knopp** [comment]
Thanks for the feedback! I'm expecting that any kind of thread blocking in flutter is going to raise eyebrows. The things to consider here are that 
1. The platform thread here is blocked until layer tree with proper size is produced and rasterized. As far as I can tell producing layer tree in flutter is essentially synchronous and doesn't wait for feedback from platform thread.
2. During waiting we are draining the event loop. This isn't expected to yield any appkit events (because one is already in progress), but it does execute tasks scheduled on main dispatch queue.

There is one possible caveat here: My implementation uses rather simplistic approach of CFRunLoopRun() and CFRunLoopStop(). If any of the scheduled blocks executed during resizing runs another nested run loop instance, CFRunLoopStop will only terminate the innermost one. If this turns out to be a problem in practice, we can either reevaluate whether running the loop during waiting is even necessary, and if is, provide a more robust solution using an observer.

**Comment by knopp** [comment]
I did spend some time looking at Windows version and made a proof of concept implementation for now available [here](https://github.com/knopp/engine/commits/windows_resize_experiment).

Before
<img src="https://i.imgur.com/3kcvEiN.gif" width=370></img>

After
<img src="https://i.imgur.com/hLoDwKf.gif" width=370></img>

Couple of observations: Current behavior is glitchy, but less than macOS. There are some threading issues (during resizing surface is recreated on platform thread, while it is being painted to on raster thread), but surprisingly I didn't get any crashes, just an occasional error message.

Fixing this would involve the following steps:

1. After the resize event, discard and don't rasterize any layer trees with stale size, similar to macOS 
2. Block during the WM_SIZE event until a new tree is rasterized and surface flipped, again, similar to macOS implementation, but bit more straightforward.
3. Move the surface creation during resizing to raster thread

Unlike core animation, DWM doesn't have any transaction guarantees with API that's currently public (confirmed by @clarkezone). However by experimenting it seems, that if we manage to flip the surface within or fast enough after the WM_SIZE event, it does the right thing and synchronizes the update with new window size.

During resize, I also synchronize the rasterizer thread after flipping with `DwmFlush()`. It seems to alleviate the problem with occasional "wobble", where surface is stretched briefly with old content over new size (or new content over old size), similar to what happens on mac without synchronizing with CA transactions.

Doing all this, at least on my setup, results in experience that's approaching UWP apps territory (I'm likely overly optimistic here), and seems better than Chromium (which may not be a fair comparison though, because Chromium in current version uses Direct Rendering).

There is, as usual, the question of blocking platform thread. Currently the implementation doesn't process posted tasks on platform thread while waiting, so things like platform channel messages will be paused until tree is rasterized. This shouldn't be too difficult to implement, I'm just not entirely convinced it needs to be done (even for macOS). 

Again, the question is whether not responding to platform messages can somehow delay building the layer tree, given that as far as I can tell building widgets and computing layouts is strictly synchronous.

**Comment by liyuqian** [comment]
I guess this janky issue is similar to those described in https://github.com/flutter/flutter/issues/19222 where each frame is rendered fast but the end result still looks janky and non-smooth.

It's nice to see some integration tests planned in [the design doc][1] where we're going to capture the frames and count the number of blue/red pixels. I wonder if we could make it more general so we can use similar tests in other cases. Here's a preliminary idea:
1. Drive the app/animation and record all frame images either by Flutter, or by a screenshot software (which should be easier for desktop scenarios than mobile apps).
2. Count the number of different pixels between adjacent frames, or the summation of the RGBA difference of each pixel.
3. If the animation is smooth, the count or the RGBA difference should be significantly smaller than the case where the animation is not smooth (widgets are jumping around, or when there are flashing red edges).

[1]: https://docs.google.com/document/d/1slGllp1Jhde7wkF6snqGhdrZwHV1VVmXeIF3f0t24JU/edit#heading=h.kl5r9cko7h3h

**Comment by tvolkert** [comment]
With flutter/engine#21525 merged, is this fixed now?

**Comment by knopp** [comment]
> With [flutter/engine#21525](https://github.com/flutter/engine/pull/21525) merged, is this fixed now?

It is, on Mac. There are still issues on Windows (I plan to do PR for it in a bit) and I have no clue what the situation is like on Linux.

**Comment by knopp** [comment]
Reopening because this is still a problem in Linux.
