### ISSUE TITLE
The tool builds the same kernel file three times

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#44187]
A team member built the app from https://github.com/Shashikant86/Flutter-App and noted in the logs:

```
$ flutter build apk --debug -v
...
[  +99 ms] [  +19 ms] "flutter bundle" took 5,605ms.
...
[        ] [  +20 ms] "flutter bundle" took 5,618ms.
...
[        ] [  +19 ms] "flutter bundle" took 5,742ms.
```

The build produced three identical build files:
```
$ sha1sum .dart_tool/flutter_build/c1e341d78579f243bfccef5c0ee1e672/app.dill .dart_tool/flutter_build/27fa6f89c8de0795d7e98f67847f5b23/app.dill .dart_tool/flutter_build/20aa69b1713dd9b9de9d3061c2de66da/app.dill
8d05d431bea344ee2220df519fe3ad65030ee02c  .dart_tool/flutter_build/c1e341d78579f243bfccef5c0ee1e672/app.dill
8d05d431bea344ee2220df519fe3ad65030ee02c  .dart_tool/flutter_build/27fa6f89c8de0795d7e98f67847f5b23/app.dill
8d05d431bea344ee2220df519fe3ad65030ee02c  .dart_tool/flutter_build/20aa69b1713dd9b9de9d3061c2de66da/app.dill
```

If this is correct, we can improve the log messages to show that the build steps are distinct. If this is incorrect, we can save a lot of time by not repeating the same kernel builds.

**Comment by jonahwilliams** [comment]
When building a fat APK with N target ABIs, flutter.gradle makes N calls into build/bundle and build aot. The fix is somewhat straightforward once https://github.com/flutter/flutter/pull/43876 can land:

We update the android bundle rules to build the .so such that there is a rule for each ABI, then update the gradle script to make a single call into assemble. There would only be a TargetPlatform.android, and instead of encoding the android ABI into a define, we would use the list to choose which rules to invoke.

**Comment by jonahwilliams** [comment]
The API would look something like:

command:
```
flutter assemble -dBuildMode=profile -dTargetPlatform=android ...
  profile_android_x64_application
  profile_android_arm_application
  profile_android_arm64_application
```

build artifacts:
```
/app.dill
/android-arm/app.so
/android-arm64/app.so
/android-x64/app.so
```

Just need to update assemble to take N targets and automatically combine them, introduce an `android` targetPlatform, and then update gradle to read the assets from the locations above.

**Comment by zanderso** [comment]
Sounds good. However based on your description, I think I will move the milestone out to end of December.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/44534
