### ISSUE TITLE
TextFormField not resetting its Initial Value

### ISSUE THREAD

**Issue by psygo** [flutter/flutter#44208]
## Use case

What I'm going to discuss is a problem I have discussed in [this StackOverflow question](https://stackoverflow.com/q/58715192/4756173), thanks to the user Filip P.

In my use case or app, I have the following dynamics:

1. Let the user create a custom form for a given date.
1. Have him upload the data to a server (more specifically, `Firebase`).
1. If he clicks on a date, the form should be updated to the most recent one saved on `Firebase`.
    - To do this, I'm deleting all of the `TextFormField` widgets (they are held in a `Map` which I reset with `widgetsMap = {}`, which is also what I do for the form data itself) and rebuilding them with the data retrieved from `Firebase`.
    - The `TextFormField` should have an initial value based on what was retrieved from `Firebase`. To achieve this, I've tried to use a `controller` and an `initialValue`, but neither have worked.
        - The **problem** is that, if I want to update the initial value of a field a second time, the previous one will remain. For example, if `date 1` has an initial value of `Hello` and `date 2` has an initial value of `World`; when I click on `date 2` coming from `date 1`, although the `TextFormField` widgets (there might even be a different number of them) will be built correctly, the initial value shown will still be `Hello`.

## Proposal

According to Filip P., since I had put the new `TextFormField` in the same position of the widget tree, `Flutter` will reuse the previous state, and that's why I won't be able set a new initial value for it. 

However, the important question I have is 

> **Why is it still keeping track of the previous state if I had previously deleted it with `widgetsMap = {}`?**

Since `dart` is (as far as I know...) *garbage-collected*, shouldn't the widgets be deleted everywhere once I execute something like `widgetsMap = {}`?

In order to show the widgets on the screen, I'm using `ListView.builder` which extracts the widgets from `widgetsMap`. So the only clue I have as to why this is happening is that &mdash; otherwise I really don't know why this all should happen... &mdash;, somehow, the `ListView.builder` is still storing the previous widgets after I delete them with `widgetsMap = {}`.

And, by the way, if I'm correct and this is indeed a legitimate issue, is it a `dart` or a `Flutter` problem?

**Comment by Frankdroid7** [comment]
I am also experiencing this same issue.
I think the solution is to use keys (UniqueKey especially), but I noticed when I used it, the textfields updated but it slowed the performance and smoothness of the app a bit.

Is there a better solution?

**Comment by gnprice** [comment]
> Why is it still keeping track of the previous state if I had previously deleted it with `widgetsMap = {}`?

In Flutter, a `Widget` object is never where state is kept. The widget is an immutable description of how some part of the UI should be built. Once that UI is built, as a tree of `Element` objects, the state lives on the elements.

In normal Flutter idioms, you're constantly creating new `Widget` objects anyway; there's no expectation that you keep them around in a map. So if you clear the map and make new widgets, you're just returning to normal patterns of using Flutter and it doesn't have any special effect on the state.

For more on this subject, the following documentation is recommended:
https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html
https://master-api.flutter.dev/flutter/widgets/Element/rebuild.html
https://api.flutter.dev/flutter/widgets/Widget-class.html
or ask Stack Overflow or other sources of advice.

Closing this issue because there isn't a bug or a proposal here.



> I think the solution is to use keys (UniqueKey especially), but I noticed when I used it, the textfields updated but it slowed the performance and smoothness of the app a bit.

This would best be asked as its own question in a forum like Stack Overflow, with concrete details. Or if you believe it's an issue in Flutter, then please file a new issue and fill out the information in the template, including sample code to reproduce the issue.

**Comment by Frankdroid7** [comment]
> I am also experiencing this same issue. I think the solution is to use keys (UniqueKey especially), but I noticed when I used it, the textfields updated but it slowed the performance and smoothness of the app a bit.
> 
> Is there a better solution?

One solution I later found was to the make use of flutter_hooks (useTextEditingController) and update the textfields state in useEffect method.

**Comment by gnprice** [comment]
> One solution I later found was to the make use of flutter_hooks (useTextEditingController) and update the textfields state in useEffect method.

Ah, yes. For the state of a text field specifically, this documentation is also relevant:
https://api.flutter.dev/flutter/widgets/TextEditingController-class.html
