### ISSUE TITLE
Getting device info such as Localizations.localeOf(context) shouldn't require context

### ISSUE THREAD

**Issue by dpedrinha** [flutter/flutter#44229]
Why do we need to provide a context to get device info such as Localizations.localeOf(context)?

The device doesn't care for the app's current state to provide its information.

Such methods should use the main app context and we shouldn't be required to provide one.

Or am I missing something here?

**Comment by dpedrinha** [comment]
This plugin seems to do it the right way: [https://pub.dev/packages/devicelocale](https://pub.dev/packages/devicelocale)

This should be the default.

**Comment by HansMuller** [comment]
The Localizations widget is typically built the the app (like WidgetsApp or MaterialApp) and does reflect the device's locale by default. However, the locale can be overridden at any point within the widget tree, see for example https://api.flutter.dev/flutter/widgets/Localizations/Localizations.override.html. That's why it's necessary to provide a context when looking up a widget's locale.

**Comment by goderbauer** [comment]
I am going to close this one with the explanation that Hans gave above.

**Comment by dpedrinha** [comment]
Yes, it makes sense when it is needed to override the i18n. But I still think the context should be optional. If used, then it gets the MaterialApp/widget localization. If not, then it gets the device language. Otherwise, there's no way to get the device language before a valid context and sometimes we need it to set our environment.
