### ISSUE TITLE
[devicelab] iOS device lab supervision

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#44246]
It would be nice to mange the ios test devices in a automated way, e.g. https://support.apple.com/en-us/HT202837.
See @jmagman 's email about using Apple Configurator to do that.

**Comment by digiter** [comment]
I have experimented with Apple Configurator 2 for a bit, here are my findings:

Benefits
* Can skip the tedious setup assistant on boarding flow.

Drawbacks
* Only able to post pond iOS system update for at most 90 days.
* Unable to suppress "No SIM Card installed" pop-up.
* No settings for Display & Brightness nor Auto-Lock.

**Comment by jmagman** [comment]
Another pro is that the devices won't refuse pairing from any host mac with the same organization supervision identity set up (any devicelab device can be plugged into any devicelab host).

Unfortunately a lot of settings aren't exposed for remote management.  One way you can get around this is to set up supervision, then manually set all the settings that aren't exposed (display brightness, emergency alerts, etc), then take a backup.  You can then periodically restore from this backup to get back to that iOS version.  Unfortunately I don't think (?) backups between devices are supported anymore due to secure enclave complications, so you can't use these backups as generic images to provision new devices.

**Comment by godofredoc** [comment]
@yusuf-goog please take a look and let us know if this is something we still want to implement.

**Comment by godofredoc** [comment]
@yusuf-goog @keyonghan is this something we still want to do or should we close as obsolete?

**Comment by yusuf-goog** [comment]
IOS device remote config would be nice to have. Not sure how difficult it would be to work with the existing tools.

**Comment by godofredoc** [comment]
Closing as obsolete.
