### ISSUE TITLE
SliverOverlapAbsorber & SliverOverlapInjector have confusing child/sliver api

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#44282]
These slivers have sliver children, currently specified by the property `child`. This should be changed to `sliver` to match Sliver-Wrapping-Sliver conventions and provide an easier to understand API. :)

**Comment by krisgiesing** [comment]
Having widget children be called `child` is a very core naming convention in Flutter. Why not change the other classes to use `child` instead of `sliver`?

**Comment by Piinks** [comment]
I think that using `child` for sliver-wrapping-sliver classes often leads to confusion.

There are not many classes of slivers-wrapping-slivers currently, but we are planning on introducing more classes of these slivers that have sliver children. As such, this is a chance to clarify what we already have, establishing a clearer convention for these particular widgets. 🙂 

cc/ @Hixie

**Comment by krisgiesing** [comment]
Why is using `child` confusing? Perhaps I'm not understanding the deeper significance of a sliver-child vs a regular widget-child?

**Comment by Piinks** [comment]
Using a `Widget child` doesn't provide a specific indication that the child must be a box or a sliver. As a simple example, a sliver that has a sliver child would throw an exception if you were to give it a box, since boxes and slivers use different layout protocols.

The API documentation for [RenderBox](https://master-api.flutter.dev/flutter/rendering/RenderBox-class.html) and [RenderSliver](https://master-api.flutter.dev/flutter/rendering/RenderSliver-class.html) describe how these protocols differ.

`SliverPadding` and `SliverSafeArea` have a ` sliver` specified child, and `CustomScrollView` has `slivers` for its sliver children. Future slivers are going to also follow this.

**Comment by krisgiesing** [comment]
I see. So there are some `Widget`s that are valid to pass to the `child`/`sliver` argument, and some that are not. `RenderSliver` describes how its protocol is different, but also says: 

> Slivers can have sliver children, or children from another coordinate system, typically box children.

So perhaps there's an opportunity to improve the documentation.

Even better would be giving the argument a type that signifies validity. This is more amenable to tooling, which would otherwise have to be taught these different naming conventions in order to provide accurate guidance. The obvious choice would be to create a `SliverWidget` class. I'm guessing that has been considered; is there a drawback to this that I'm missing?

**Comment by Piinks** [comment]
Absolutely, there is always room for documentation improvement! 😋 
Creating a `SliverWidget` I think would be a much bigger breaking change than the one proposed.
