### ISSUE TITLE
Flutter 1.10.15 shows crash spike regression over 1.10.14...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#44445]
Crash of the tool is 4.5%, nearly 3x what 1.10.14 was.

/cc @zanderso

**Comment by zanderso** [comment]
That high number is likely an artifact of a small number of users on the first day after the new dev release. Today so far the number is 1.9%, and since the release the aggregate number is ~2.3% for ~1000 users. None of the crashes in crash logging affects more than 5 users. The top I expect the crash rate to settle down as more folks try out the new dev.

As an aside, I think the difficulty of monitoring the crash rate over a short time scale for a small number of users speaks to a growing need to select the stable release from more dev candidates over a longer period of time, or something equivalent to that. /cc @tvolkert

**Comment by kf6gpe** [comment]
Agreed --- the number has settled as of this morning. Closing --- and when I screen in the future for high crash rates, I'll omit the first couple of days on a dev release to avoid premature filing. Thanks!
