### ISSUE TITLE
PageView should allow for implicit a11y scrolling

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#44484]
`PageView` normally does not allow implicit a11y scrolling, but some applications may want that - e.g. if used to create a carousel type of widget that would otherwise have many of the same behaviors as a page view (snap-to scrolling) but that should otherwise participate in a11y navigation for the current page.

/cc @goderbauer @darrenaustin

**Comment by dnfield** [comment]
Only challening part of implementing this is that we currently apply a hidden global to the physics here regardless of what the user wants the physics to be.

**Comment by dnfield** [comment]
Currently, a user can work around this by setting pageSnapping to false (so that the PageScrollPhysics we don't like is skipped over by the framework) and providing a custom scroll physics:

```dart
PageView.builder(
  pageSnapping: false,
  physics: _AllowImplicitScrollingPageScrollPhysics().applyTo(ScrollConfiguration.of(context).getScrollPhysics(context)),
  ...
),

...

/// [PageScrollPhysics] normally disallows implicit a11y scrolling. This
/// overrides that behavior so that the [_Carosel] works better for a11y
/// navigation.

class _AllowImplicitScrollingPageScrollPhysics extends PageScrollPhysics {
  const _AllowImplicitScrollingPageScrollPhysics({ ScrollPhysics parent }) : super(parent: parent);

  @override
  _AllowImplicitScrollingPageScrollPhysics applyTo(ScrollPhysics ancestor) {
    return _AllowImplicitScrollingPageScrollPhysics(parent: buildParent(ancestor));
  }
  @override
  bool get allowImplicitScrolling => true;
}
```

But this feels pretty ugly and brittle.

**Comment by goderbauer** [comment]
In order to get implicit scrolling on iOS you need to specify a cache extend for the scrollable. Currently, the PageView doesn't do that because iOS uses the presence of a cache extend as a signal to do implicit scrolling. Before we can give the PageView a cache extend we need to fix that and make iOS only do implicit scrolling when the corresponding semantics flag is set (and there's also a cache extend). See also: https://github.com/flutter/flutter/pull/42107#issuecomment-540163058
