### ISSUE TITLE
Assertion failure in flutter_runner

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#44480]
With the flutter_jit_runner built at https://github.com/flutter/engine/commit/9113543f0562a53ffc9209f18f0198b7ccb67d3b

with
```
flutter/tools/gn --goma --fuchsia --unoptimized --fuchsia-cpu arm64 --runtime-mode debug
```
I'm hitting an assertion failure shortly after the runner starts:
```
[692.505] 64354.65284> [FATAL:flutter/fml/memory/weak_ptr.h(78)] Check failed: (checker_.checker).IsCreationThreadCurrent().
```
I'm not sure how to get a full backtrace but it seems to be coming from this area:

https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/flutter/vsync_waiter.cc#L53

Maybe in the PostDelayedTask callback?

@chinmaygarde @iskakaushik

**Comment by iskakaushik** [comment]
@gw280 let me know if you have trouble reproducing this failure.

**Comment by gw280** [comment]
Couple of things:

- This affects debug builds only
- This is because the VSyncWaiter object is owned by the Shell, and thus lives on the platform thread. In AwaitVSync we are dereferencing the weakptr (which can only be derefed on the platform thread) on the UI thread, so we get this failed assertion.

I will have a think about the best way to fix this. @chinmaygarde - do you think it'd be safe to just pass in `this` instead of a weak ref? I'm not familiar enough with the lifetimes of the objects involved to conclude whether this would be safe or not.

**Comment by zanderso** [comment]
> * This affects debug builds only

In general, debug assertion failures are presumed to indicate a problem that does affect release builds. However, it affects them in ways that can be unpredictable and harder to track down.
