### ISSUE TITLE
[firebase_analytics] - `setUserId` method is not working since Google Analytics for Firebase property has been upgraded by Firebase.

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#44604]
Since Google Analytics for Firebase property has been upgraded by Firebase. The `setUserId` method is not displaying `user_id` in the Firebase Console.

This issue is across my all projects since the upgrade.
The `firebase_analytics`  plugin needs attention by the Flutter team.

**Comment by iapicca** [comment]
Hi @kaumudpa 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
