### ISSUE TITLE
Text overflow with ellipsis also has fade

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#4478]
## Steps to Reproduce

A **text** widget with _overflow_ set to _TextOverflow.ellipsis_ should not have a fade. 
![screen shot 2016-06-07 at 4 56 50 pm](https://cloud.githubusercontent.com/assets/3635416/15914296/ac8b3b92-2d94-11e6-9b8d-92c6e2f12c2e.png)

## Flutter Doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/dayang/Flutter
    • Framework revision 21fa2753d8 (13 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.3

**Comment by abarth** [comment]
It's unclear how to implement ellipsis without a fade in languages like Arabic where removing letters from a word doesn't necessarily result in glyphs that take up less space.  Arabic is particularly tricky because letters at the end of words get different glyphs than those in the middle of a word.

/cc @Hixie

**Comment by abarth** [comment]
One possibility is to break word boundaries or at boundaries between ligatures.

**Comment by dvdwasibi** [comment]
@sethladd can you add customer:queue for this issue. Thanks!

**Comment by sethladd** [comment]
One short-term thing we can do is mention in the API docs that choosing ellipsis auto-opts-you-in for fade as well.

(or, just decouple fade from ellipsis :)

**Comment by Hixie** [comment]
Ok the plan is that rather than truncating individual characters until it fit, we will truncate entire atomic positioned glyph sequences (e.g. whole ligatures or shaped words) until the ellipsis fits. That would have the advantage of being much more performant. It would have the disadvantage of truncating the entire word if the whole line was one ligature (e.g. if your line was the word "Zapfino" in the Zapfino font, and it overflowed at the "o", we would replace the whole thing with a "...", rather than just the "no".)

**Comment by dvdwasibi** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3635416/19046454/5283dbee-8952-11e6-86f5-e2fa5302de05.gif)
