### ISSUE TITLE
download_goldctl.sh should retry if the depot_tools clone fails

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44786]
## Use case
It looks like sometimes cloning depot_tools fails on Cirrus (network issues?).
```
ulimit -S -n 2048
./dev/bots/download_goldctl.sh
Cloning into './depot_tools'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
./dev/bots/download_goldctl.sh: line 4: cd: depot_tools: No such file or directory
./dev/bots/download_goldctl.sh: line 6: ./cipd: No such file or directory

Exit status: 127
```
https://cirrus-ci.com/task/5949937388355584?command=main#L0

## Proposal

Consider a sleep and retry as is done in a few other tests.  With increased control logic, it may be a good time to migrate to a dart test.

**Comment by jmagman** [comment]
\cc @Piinks

**Comment by christopherfujino** [comment]
On this issue https://github.com/flutter/flutter/issues/44394 we can move downloading this to the `Dockerfile`, which would circumvent this problem.

**Comment by christopherfujino** [comment]
Oh, but I guess we still need to download it on LUCI

**Comment by Piinks** [comment]
Putting `goldctl` in the `Dockerfile` would be awesome. 🙂 

The tool has been in the process of landing new features for months, which is why we have been checking out the latest version via script, but I think it is stable enough now to move into the `Dockerfile` once this last change lands: https://skia-review.googlesource.com/c/buildbot/+/253698

We currently aren't executing golden tests on LUCI, so as long as we are running on Cirrus it should be ok.

**Comment by christopherfujino** [comment]
My PR #46640 fixed this for Linux, but this is still a potential issue on mac/windows.

**Comment by godofredoc** [comment]
@Piinks is this obsolete? it seems like we are downloading goldctl from cipd.

**Comment by christopherfujino** [comment]
this is obsolete, we haven't had issues with this since switching to cipd
