### ISSUE TITLE
Want to print Intercepter for httpRequest using "Stetho" !! 

### ISSUE THREAD

**Issue by hardypatel30** [flutter/flutter#44801]
Any idea about printing "request payload" in stetho tool using flutter?

We are havin same class in for android native 
` .addNetworkInterceptor(new StethoInterceptor())`

Want exact implementation in flutter using `http`

**Comment by iapicca** [comment]
Hi @hardypatel30 
This platform is not met for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.

What you are proposing sounds like a good idea for a [3rd party plugin](https://pub.dev/packages/flutter_stetho), 
rather than an improvement on the [http package](https://pub.dev/packages/http).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by hardypatel30** [comment]
No its not for personal assistance.. stetho is printing request header for
flutter but not requestbpayload. Everything else is being printed on stetho
tool.

**Comment by iapicca** [comment]
Hi @hardypatel30 
can you please provide your updated  `flutter doctor -v`
and  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
