### ISSUE TITLE
How about using the kotlin to develop flutter?

### ISSUE THREAD

**Issue by yangwuan55** [flutter/flutter#44887]
Is it possible to develop flutter with kotlin in the future?

**Comment by rs5173** [comment]
build castles in the air

**Comment by iapicca** [comment]
Hi @yangwuan55 
this doesn't appear to be an issue with Flutter
and I struggle to see it as a proposal for improvements,
there are several reasons why Flutter uses Dart instead of
`Kotlin`, `JS`, `Java` etc...
and have been extensively discussed on many platforms,
here's [one](https://youtu.be/5F-6n_2XWR8).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
