### ISSUE TITLE
[WEB] How to get the hot-reload status/signals (for refreshing the page) from web-server devices

### ISSUE THREAD

**Issue by tianna1121** [flutter/flutter#44974]
## Use case

Get the hot-reload status from web-server device. The page in the chrome device can be refreshed automatically when user sent 'r' or 'R' command. However, we cannot get the similar signal from web-server device.

Flutter web servers are mostly build on web-server device. We want to provide auto-refresh feature when the flutter apps changed.

## Proposal

Provide some sort of signals when hot-reload finishes (for web-server devices).

**Comment by tianna1121** [comment]
I have noticed that only ChromeDevice can get Page.reload command via wipConnection api call. How can I use wipConnection.sendCommand('Page.reload') to WebServerDevice?

**Comment by yjbanov** [comment]
@jonahwilliams how easily can this be supported?

**Comment by jonahwilliams** [comment]
Someone already filled an issue for this, maybe it got closed? Its a trivial change to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L1094 to conditionally register hot reload and hot restart hooks based on device supporting hotreload/restart instead of service protocol

**Comment by jonahwilliams** [comment]
Duplicate of https://github.com/flutter/flutter/issues/44795
