### ISSUE TITLE
does the Dart_Invoke() will be failed.

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#44982]
I have customed the flutter engine with add some native call from dart to c/c++, I also need to call back to dart by using the dart_invoke() method, does the dart_invoke() will be failed when find the function in dart caused by GC, if this will be happen, how to avoid this situation?  use Dart_EnterScope()/Dart_ExitScope() to protect the dart invoke call will not failed?

**Comment by iapicca** [comment]
Hi @ping996
if I understand correctly you are manually changing flutter engine code
in order to call c/c++ code; 
you may want to consider as an alternative leaving `flutter/engine` intact using instead [dart:ffi](https://dart.dev/guides/libraries/c-interop) for such a purpose.

Can you please provide you error logs and a minimal code sample to reproduce the problem
Thank you

**Comment by ping996** [comment]
I have used the dart:ffi, but ffi only can dart call c/c++,  I also need to call dart methods triggered by c/c++ side. so I want to know the dart_invoke call executed successfully every time?

**Comment by dcharkes** [comment]
Callbacks on the Dart mutator thread (what you would need for Dart_Invoke as well) are supported on the ffi.

Asynchronous callbacks are supported through using the native ports mechanism (see https://github.com/dart-lang/sdk/issues/37022#issuecomment-613287693).
