### ISSUE TITLE
Continue to push frames after overflow scroll is finished

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4502]
See this in action here: https://www.youtube.com/watch?v=Pa-u4Ae9m9A

Notice that after the overflow scroll animation is complete and disappears from the screen, we continue to see frames pushed (based on the performance overlay's continued animation).

**Comment by abarth** [comment]
Yeah, when to stop pushing frames is slightly tricky.  It would be interesting to look at the iOS version to see if the overscroll is still going on.

**Comment by sethladd** [comment]
iOS doesn't have this issue. We have a different behavior there (no overflow scroll). As soon as the grid settles, the animation and frames stop.

I don't know this is is particularly "bad", as it stands. If we think this is a systemic thing we should look into, let's keep the issue open. If we don't think there's any "harm" here, we can close.

**Comment by abarth** [comment]
We run the animation as if we were on iOS and just use a different visual appearance on Android.  That's why we keep pushing frames until the iOS version of the animation would be complete.

We probably need to re-think how we generate this animation on Android.  There are a number of bugs on file about it that can probably all be resolved by iterating on the approach.

**Comment by Hixie** [comment]
Done.
