### ISSUE TITLE
[web] GestureDetector doesn't handle HitTestBehavior

### ISSUE THREAD

**Issue by mikepyts** [flutter/flutter#45253]
## Steps to Reproduce

1. Create Flutter for Web project
2. Build simple page with two GestureDetectors (one inside another one) with `behavior: HitTestBehavior.translucent`:

`GestureDetector(
                          behavior: HitTestBehavior.translucent,
                            child: GestureDetector(
                              behavior: HitTestBehavior.translucent,
                                child: Container(color: Colors.red),
                                onTap: () => print('Inner GestureDetector')),
                            onTap: () => print('Outer GestureDetector')),`
3. Launch the project and observe console output.
4. HitTestBehavior.translucent is not taken into account and I only receive output from inner widget, instead should receive from both `onTap:`

## Logs
![image](https://user-images.githubusercontent.com/26088845/69244364-81041e80-0bad-11ea-9ee4-4687a8219264.png)

```
/Users/mike/Documents/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.12.5-pre.21, on Mac OS X 10.15.1 19B88, locale en-UA)
    • Flutter version 1.12.5-pre.21 at /Users/mike/Documents/flutter
    • Framework revision 399aebc4b7 (27 hours ago), 2019-11-19 12:12:56 +0100
    • Engine revision ecb32952ff
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mike/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Users/mike/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/mike/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by iapicca** [comment]
Hi @mikepyts 
are you experiencing the same issue with other Flutter versions from different channels?
thank you

**Comment by mikepyts** [comment]
@iapicca have tried with master and dev channels, unfortunately on another project, I have to use master channel due to other features, so at least on two channels it has the same behavior for me

**Comment by mikepyts** [comment]
@iapicca

**Comment by yjbanov** [comment]
Does this happen on Android or iOS as well?

**Comment by mikepyts** [comment]
@yjbanov have checked on my iPhone 6:
![iPhone 6](https://user-images.githubusercontent.com/26088845/70436579-4d246680-1a92-11ea-8557-64e85898d1d8.gif)

**Comment by yjbanov** [comment]
Thanks for checking! Sounds like a framework issue.

/cc @goderbauer @dkwingsmt

**Comment by goderbauer** [comment]
This is working as intended. When you tap, both the inner and outer tap gesture recognizer enter the gesture arena, which can only be won by one detector. Since there is no clear winner here, the first one to enter the arena wins it by definition. That's why you only see the onTap handler for the inner detector fire because it was the first one to enter the arena. More details can be found here: https://flutter.dev/docs/development/ui/advanced/gestures#gesture-disambiguation

In your example, the HitTestBehavior.translucent only determines which gesture detectors can participate in recognizing the gesture (for a different HitTestBehavior the outer detector wouldn't even enter the gesture arena). It does not change the number of recognizers that can win the arena, which is always just one.

If you replace the GestureDetector widgets in your example with Listener widgets (with onPointerDown handlers) you will see that both listener widgets see the onPointerDown event as expected. Unlike GestureDetector widgets, Listener widgets do not participate in the gesture arena and give you the raw pointer events.

**Comment by mikepyts** [comment]
@goderbauer  thanks, that clarified situation

**Comment by phanirithvij** [comment]
@goderbauer can you give an example showing how a `GestureDetector` with the behavior of `HittestBehavior.translucent` can be used?

**Comment by phanirithvij** [comment]
And the docstring for `translucent` behavior needs to be more precise and also describe where it should or shouldn't be used.

The current explanation suggests it can be used anywhere.
> Translucent targets both receive events within their bounds and permit targets visually behind them to also receive events.
