### ISSUE TITLE
Hot reload regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#45277]
As of https://github.com/flutter/flutter/pull/45024 we are reliably slower on hot reload. It's especially visible on smoke_catalina_hot_mode_dev_cycle__benchmark hotReloadMillisecondsToFrameAfterChange.

Seems to be a Dart roll specifically.

cc @tvolkert @a-siva @bkonyi @cbracken

**Comment by tvolkert** [comment]
Specifically, looks like it started at https://github.com/flutter/engine/commit/59b5a0cf76765767e3ead8e7157b5f8e682c644f

**Comment by tvolkert** [comment]
dart-lang/sdk@d6b0a27 [test] Explicitly mark streamed_conversion_json_utf8_decode_test as slow in reload test modes.
dart-lang/sdk@1c12878 [ dart:io ] Added timeline events for HttpClient connections and requests
dart-lang/sdk@545b103 [vm, service] Compute allocation stats on demand, instead of during allocation and GC.
dart-lang/sdk@6239777 [dart2js] Fix a few missing and one unneeded `covariant`s
dart-lang/sdk@a2fe9d4 [analyzer] Report invalid variance positions in methods of a class.
dart-lang/sdk@329d091 [vm] Late modifier for non-final local variables.
dart-lang/sdk@a8b3773 [vm, reload] Guard against field loads that no longer conform to the field's static type.
dart-lang/sdk@33c95a8 Migration: account for definite assignment.
dart-lang/sdk@f3ee4d0 Add a failing test case for http://dartbug.com/39401 -- quick fix improvement around angular generated files
dart-lang/sdk@15e5c23 nnbd preview tool: Better text when inserting 'required'
dart-lang/sdk@6ec813e [analyzer] Modified type inference constraints wrt variance.
dart-lang/sdk@249a917 Migration: don't mark fields as nullable due to factory and redirecting constructors.
dart-lang/sdk@ea6c7f2 [fuzzer] Added void functions to the API table
dart-lang/sdk@a6635d0 [nnbd_migration] Show "exact nullability" in output directory.
dart-lang/sdk@557ed60 Temporarily do not enable nnbd when building packages for ddc tests
dart-lang/sdk@89dc1a7 Updated analyzer error messages in variance_multi_subclass_error_test.
dart-lang/sdk@d290f1c Add nonfunction-type-aliases experimental flag
dart-lang/sdk@faa4eb7 Partial support for an incremental workflow
dart-lang/sdk@c5b87f2 [vm] Disable entire test (apparently status files can no longer disable individual multitests)

**Comment by jonahwilliams** [comment]
Isn't this the same as the regression from https://github.com/flutter/flutter/issues/45109?

**Comment by Hixie** [comment]
Maybe. The offending PR didn't mention any regression that I could see, so I filed one.

**Comment by tvolkert** [comment]
Yep, same one.  Closing this in favor of the earlier discussion.
