### ISSUE TITLE
[cloud_functions] Add web support

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45299]
We should add web support to `cloud_functions`

**Comment by sbeitzel** [comment]
I've written a web implementation but am having some trouble writing unit tests. I've created mock objects for the JS Firebase layer, cribbing largely from the tests in [firebase_auth](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart). However, it seems that my mock objects aren't being used; instead I'm getting an error message that's coming from the JS Firebase layer.

I'm also not able to attach a debugger to the test to see what's up, since the `--start-paused` flag doesn't seem to be working. I'm invoking the test with `flutter test --platform chrome --start-paused test/cloud_functions_web_test.dart` and it just runs and fails.

Would anyone care to take a look and maybe give me a pointer toward what I should be doing differently?

[cloud_functions_web_test.dart](https://github.com/sbeitzel/flutterfire/blob/cf_pi_p2/packages/cloud_functions/cloud_functions_web/test/cloud_functions_web_test.dart)

**Comment by hterkelsen** [comment]
Odd... the test shouldn't be able to call into the Firebase JS layer since in the test HTML you aren't loading the Firebase JS scripts. Can you post the error stacktrace you're seeing?

**Comment by sbeitzel** [comment]
Here's the output from a test run.

[test.log](https://github.com/flutter/flutter/files/4110891/test.log)

**Comment by hterkelsen** [comment]
To me it looks like somehow `firebase.functions(app).httpsCallable` is returning `null`. I would either debug or add some print statements in `package:cloud_functions_web/cloud_functions_web.dart` to make sure things are non-null.

**Comment by sbeitzel** [comment]
It seems that I'm somehow not hooking up the mocks correctly. When [CloudFunctionsWeb.call](https://github.com/sbeitzel/flutterfire/blob/cf_pi_p2/packages/cloud_functions/cloud_functions_web/lib/cloud_functions_web.dart#L47) calls to get the Firebase functions API, it seems I'm actually getting it and not the mock functions object.

**Comment by hterkelsen** [comment]
The firebase-dart library should use whatever JS mocks you have set up: https://github.com/FirebaseExtended/firebase-dart/blob/master/lib/src/top_level.dart#L131

Hopefully looking at the firebase-dart source can help you track down the problem. If you are really stuck and you can't debug using Chrome DevTools you can always check out a local copy of firebase-dart and change your pubspec to use the local copy and put print statements in there.

**Comment by sbeitzel** [comment]
Really I'm just feeling frustrated -- I don't truly understand the whole Dart/JS interaction layer. It seems as though everything under `top_level.dart` is some kind of JS object that gets deserialized at runtime into some Dart code. The error that I'm getting suggests that at the point we finally get to instantiating an HttpsCallable (by calling `Functions.httpsCallable`) then the thing that gets instantiated doesn't have the expected JS object and so there's a null pointer exception when the Dart/JS logic tries to do the deserialization.

The puzzling bit, one of the bits that I don't understand, is, why is *that* the HttpsCallable that's being instantiated? After all, the test installs a special HttpsCallable and that's the thing that should be coming back. But it isn't. Then again, the test installs a special Functions, and *that* isn't being returned. So, the part where the test installs FirebaseMock by calling this: `@JS('firebase')
external set firebaseMock(FirebaseMock mock);` assigns the custom Functions object to a place that is not accessed when the CloudFunctionsWeb code calls `firebase.functions(app);` (where `firebase` is defined as an import as: `import 'package:firebase/firebase.dart' as firebase;`

Now, should I be importing something else? top_level.dart, maybe? And should I be getting the Functions instance in some other way? Because that's all I've got, right now.

**Comment by hterkelsen** [comment]
I'll try to debug it later today and see if I can track down the problem. I have a little bit of experience with JS-interop.

**Comment by hterkelsen** [comment]
I took a quick look. I think the main problem is that your mock that returns a mock `HttpsCallable` object, rather than an actually callable function. I got a few steps further in the test by changing your mock initialization to:

```dart
      firebaseMock.functions = allowInterop(([app]) => FirebaseFunctionsMock(
            httpsCallable: allowInterop((functionName, [options]) {
              _debugLog(
                  'FirebaseFunctionsMock getting a callable for app ${app.name} with function name $functionName');
              return allowInterop(([data]) {
                _debugLog(
                    'FirebaseHttpsCallableMock \'$functionName\' is being called');
                log.add(<String, dynamic>{
                  'appName': app.name,
                  'functionName': functionName,
                  'parameters': data
                });
              });
            }),
            useFunctionsEmulator: allowInterop((url) {
              _debugLog('Unimplemented. Supposed to emulate at $url');
            }),
          ));
```

But then I started getting problems with `package:firebase` trying to call `.then()` on the result of calling the callable. I think you can solve that by copying how the `firebase_auth_web` tests mock js Promises: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart#L86

Hope this helps! Thanks again for contributing to the plugin!

**Comment by sbeitzel** [comment]
Wow, thank you! Yes, that's very helpful; a bit of trying and I have got the test cases working. Going to clean up all the debugging detritus and then submit a PR.

**Comment by sbeitzel** [comment]
I know it's trivial, but can this get moved to the "Writing Web Implementation" in the [kanban](https://github.com/flutter/flutter/projects/69) page? I like seeing progress!

**Comment by hterkelsen** [comment]
Of course!

**Comment by sbeitzel** [comment]
I'm working on making the web example in [cloud_functions](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions/example) work, but I'm missing one bit of information. Not sure if it's important, yet, as I haven't gotten to the part where I try running the thing. Configuring the appId for the example application, I'm cribbing from the details in the [iOS example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/example/ios/Runner/GoogleService-Info.plist#L21) but the appId is platform-specific and I don't actually have access to Firebase project `flutterfire-cd2f7`. Who does? And is it even important? I suspect it may be...

**Comment by hterkelsen** [comment]
`package:cloud_functions` now works on the web. Thanks so much for your contributions @sbeitzel !!

**Comment by sbeitzel** [comment]
Glad to help!
