### ISSUE TITLE
[firebase_crashlytics] Add web support to plugin

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45301]
We should add web support to `firebase_crashlytics`

**Comment by amreniouinnovent** [comment]
@hterkelsen Do Firebase Chrashlytics support web?!
As I know it supports Mobile only
check this https://github.com/firebase/firebase-js-sdk/issues/710

**Comment by marcschw** [comment]
Crashlytics do not support web. However, since now it is possible to compile the same codebase to mobile or to web it would be very convenient to have this package flagged as working on flutter web just so that the code still compiles for flutter web and there is no need to have a different code base for both.

**Comment by cyanglaz** [comment]
@kroikie Should we move this to the flutterfire repo?

**Comment by MrBirb** [comment]
@TahaTesser Same thing here.

**Comment by TahaTesser** [comment]
See https://github.com/FirebaseExtended/flutterfire/issues/1693#issuecomment-671287612

> Hello. Crashlytics only currently supports Android, iOS and Unity therefore we can't bridge web support as no underlying SDK exists.
> 
> I'd advise adding an upvote [here](https://github.com/firebase/firebase-js-sdk/issues/710) and submitting a [feature request](https://firebase.google.com/support/troubleshooter/report/features).
> 
> Closing this as it isn't actionable.

Closing as invalid
