### ISSUE TITLE
How i inject custom css and js files in my webview from local asset folder

### ISSUE THREAD

**Issue by urvesh-educloud** [flutter/flutter#45324]
How i inject custom css and js files in my webview
for eg :
```
<html>
<head>
<link rel="stylesheet" href="bootstrap.min.css">
<script src="jquery-3.2.1.min.js"></script>
<script src="bootstrap.min.js"></script>

<script type="text/javascript">
</script>
	$(document).ready(function() {
		try {
			console.log("onReady called...");
		} catch(err) {
			onError("Error in On Ready Function..! "+err.message);
		}
	});
</head>
</html>
```

**Comment by iapicca** [comment]
Hi @urvesh-educloud 
I see you already opened a [question ](https://stackoverflow.com/questions/58968573/how-i-inject-custom-css-and-js-files-in-my-flutter-webview-from-local-asset-fold)on stackoverflow,
that's the right approach since this platform is not met for assistance on personal code.

Please see https://flutter.dev/community for resources for asking questions like this.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
