### ISSUE TITLE
 On iOS, when a text field is focused on a webpage, the webview scrolls into an empty white area

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#45482]
See internal bug: b/144826626

It seems to me that when keyboard appears, the UIKitView is resized immediately, but the change in size of the UIKitView is not propagated to the web page. I've submitted a hack to fix this issue (putting the entire webview in a scrollview so that it is not resized when keyboard is up). We should investigate why there is a discrepancy in the window size.

**Comment by mehmetf** [comment]
customer:quill just escalated this to P0 saying that the hack (putting webview in scrollview) does not work for them. Could we please triage this?

**Comment by Brooooooklyn** [comment]
Put Webview in a scrollview will trigger another issue on iOS https://github.com/flutter/flutter/issues/40666

**Comment by mehmetf** [comment]
Not sure what the etiquette is for assigning issues :-) Making sure this is on @amirh 's radar.

**Comment by amirh** [comment]
@cyanglaz can you take a look?

**Comment by cyanglaz** [comment]
Some updates after initial debugging: The webview seems always has the correct size; the WKContentView (which is the subview of WKScrollView which shows the web content) has a wrong frame.  I suspect the `ReconstructClipViewsChain` in FlutterPlatformViews.mm in engine somehow somehow broke it. I will look into this more and send out more updates if I find anything.

**Comment by cyanglaz** [comment]
update: The issue is because iOS automatically adjusted the content inset of the webview when it detects a keyboard is showing up.
Flutter also does some trick to update the view port when keyboard comes up, so it ended up becoming a "double adjustment" if you will.
It would be ugly to add some "special case" code in flutter engine to fix the adjustment for just webview.
There also doesn't seem to be a simple set-and-done flag to disable the behavior on iOS.

My current best solution would be reverting the contentInset after iOS sets it.

**Comment by cyanglaz** [comment]
update: (Thanks @amirh for the help with coming up the solutions)

Root cause:  In the WKWebView open source code (https://github.com/WebKit/webkit), we found that the WKWebView object is listening to the keyboard events and explicitly adjust the contentInset (or adjustedContentInset after iOS 11) during `UIKeyboardWillChangeFrameNotification`, `UIKeyboardWillShowNotification` and `UIKeyboardWillHideNotification`. This adjustment is based on the webview's frame and where the textfield appears on the screen. The adjustment happened before the Flutter Engine resizes the PlatformView (aka WKWebView in this case). This caused the adjustment happened on the incorrect WebView frame. 

After offline discussion with @amirh(Thanks @amirh for the help with coming up the solutions),  we came up with 2 possible solutions and we currently favor solution 2.


1. Manually post keyboard notification to `WKWebView` again after the webview's frame changed. This way we makes sure the adjustment of the content inset is happened after the webview's frame is updated.

Pros: 

- Cleaner code

- Reuse WKWebView's own logic to reset the `contentInset`(or `adjustedContentInset` after iOS 11).

Cons:

- We rely on the private implementation of WKWebView and regression may occur if WKWebView changed their implementation. (i.e. The `WKWebView object doesn't listen to the notification anymore)

2. Revert the adjustment. Before iOS 11, it is as simple as setting the `contentInset` to `.Zero` whenever it wants to change. After iOS 11, the adjustment is happened on the newly introduced field `adjustedContentInset`. And `adjustedContentInset` is readonly. So in iOS 11 we need to set `contentInset.bottom` to be `-adjustedContentInset.bottom` to compensate the change in `adjustedContentInset` and the sum will be 0.

Pros: 

- We are not relying on any private implementation of WKWebView

Cons:

- The code is not as clean as solution 1.

 
We currently favor solution 2 because it seems to be less error prone.
