### ISSUE TITLE
[dashboard] ability to find out test bed ip address

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#45549]
The new dashboard does not have a way to look at the testbed information and the old the overlay to show the testbed information was removed from the old dashboard.

Please enable the overlay to show testbed info and test names in the old dashboard until that functionality is available in the new dashboard.

Note: This is very important for the infra build cop to triage issues and right now we don't have a way to find the ip addresses.

/cc @keyonghan  @digiter

**Comment by CaseyHillers** [comment]
This is an issue in the Angular build process since just the feature isn't working. None of the back end functionality changed that relates to this.

https://v312-dot-flutter-dashboard.appspot.com/build.html is a working version of this feature.

I am going to look into documenting what versions we use for building the Angular project.
