### ISSUE TITLE
Retain cycle in -[FlutterEngine setupChannels] in -[_binaryMessenger setMessageHandlerOnChannel::]

### ISSUE THREAD

**Issue by PJLX** [flutter/flutter#45592]
in file `FlutterEngine.mm`,fun `setupChannels`
```
[_binaryMessenger setMessageHandlerOnChannel:@"flutter/isolate"
                          binaryMessageHandler:^(NSData* message, FlutterBinaryReply reply) {
                            self.isolateId = [[FlutterStringCodec sharedInstance] decode:message];
                          }];
```
`self.isolateId` self retain _binaryMessenger, _binaryMessenger retain self

**Comment by iapicca** [comment]
Hi @PJLX 
can you please describe the issue in detail
and provide your `flutter doctor -v`  
and a minimal code sample to reproduce the problem.
Thank you

**Comment by jmagman** [comment]
@dnfield https://github.com/flutter/engine/pull/10823/files/21365a8686cbf6a7a2edf94714ed08d29faa858a#r312707654 Does _binaryMessenger handle clearing out its message handler?  I can't remember how this works.

**Comment by dnfield** [comment]
Hmm.  _binaryMessenger does not retain self, it keeps hold of a nilable pointer.

I think what I wanted rather than `__block` is `__unsafe_unretained` (we can't use `__weak` since we're not using ARC).

I'm not really sure how this could result in a memory leak though - I suppose if you tried to allocate the engine and then deallocate it before shell setup finished?  @PJLX can you speak more to that?

**Comment by dnfield** [comment]
no, `__unsafe_unretained` won't actually help us here.  But we already have a weakptrfactory for flutter engine and shoul dbe able to use that.
