### ISSUE TITLE
Document how NestedScrollView.physics/scrollDirection/reverse affect outer/inner scroll views

### ISSUE THREAD

**Issue by xinle** [flutter/flutter#45619]
I read code ,find this code in scrollable.dart

 ```dart
void _updatePosition() {
    _configuration = ScrollConfiguration.of(context);
    _physics = _configuration.getScrollPhysics(context);
    if (widget.physics != null)
      _physics = widget.physics.applyTo(_physics);
    final ScrollController controller = widget.controller;
    final ScrollPosition oldPosition = position;
    if (oldPosition != null) {
      controller?.detach(oldPosition);
      // It's important that we not dispose the old position until after the
      // viewport has had a chance to unregister its listeners from the old
      // position. So, schedule a microtask to do it.
      scheduleMicrotask(oldPosition.dispose);
    }

    _position = controller?.createScrollPosition(_physics, this, oldPosition)
      ?? ScrollPositionWithSingleContext(physics: _physics, context: this, oldPosition: oldPosition);
    assert(position != null);
    controller?.attach(position);
  }

```

**Comment by helinanever** [comment]
Hi @xinle,

Could you. please, provide `flutter doctor -v`

Thank you.

**Comment by xinle** [comment]
> Hi @xinle,
> 
> Could you. please, provide `flutter doctor -v`
> 
> Thank you.

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.12.6 16G29, locale zh-Hans-HK)
    • Flutter version 1.9.1+hotfix.6 at /Users/xinle/flutter
    • Framework revision 68587a0916 (3 个月前), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xinle/Library/Android/sdk
    • Android NDK at /Users/xinle/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jamesblasco** [comment]
It doesn't work also for my project. I created a dartPad with the issue
https://dartpad.dartlang.org/84e6c7159a34e607cd5216c2fbf3d5b6

**Comment by jamesblasco** [comment]
I forked the NestedScrollView and created a CustomNestedScrollView modified to work with NeverScrollableScrollPhysics.
https://gist.github.com/jamesblasco/5b609ecff66c3fd1b1f21cd36564d8db
The demo example : https://dartpad.dartlang.org/5b609ecff66c3fd1b1f21cd36564d8db

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-10.0.pre.196`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.196, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.196 at C:\Development\flutter_master
    • Framework revision ea039ed3f9 (9 hours ago), 2020-09-15 17:57:04 -0400
    • Engine revision 1cabedf8ac
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>
<details>
 <summary>Code sample from DartPad</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          controller: PrimaryScrollController.of(context),
          physics: NeverScrollableScrollPhysics(),
          headerSliverBuilder: (context, _) => [
            SliverAppBar(
              title: Text('NestedScrollView issue'),
            ),
          ],
          body: SingleChildScrollView(
            physics: NeverScrollableScrollPhysics(),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                ),
                Container(
                  margin: EdgeInsets.all(16),
                  height: 200,
                  width: 200,
                  color: Colors.blue,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

@jamesblasco Would you considering working on a PR for this?

**Comment by yasinarik** [comment]
> I forked the NestedScrollView and created a CustomNestedScrollView modified to work with NeverScrollableScrollPhysics.
> 
> https://gist.github.com/jamesblasco/5b609ecff66c3fd1b1f21cd36564d8db
> 
> The demo example : https://dartpad.dartlang.org/5b609ecff66c3fd1b1f21cd36564d8db

Dear @jamesblasco , I have an open issue that might be related to this issue and your forked `CustomNestedScrollView` . 

So can you have a look at this issue: #71289

Thanks a lot!

**Comment by jamesblasco** [comment]
Sure, I will take a look. It has been a year since I don't work with this change so I might have forgotten a bit about it. But I still use it in my project with a PageView inside and works without problem for me

**Comment by red282** [comment]
A quick workaround here. (Referred to #82391, which describes a root cause well.)

1) Fork `NestedScrollView`.
2) Replace `updateCanDrag` implementation
https://github.com/flutter/flutter/blob/87eddcb1a0df44af8f234108b56fba5a2cb5f86f/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1615-L1617
with
```dart
void updateCanDrag(double totalExtent) {
  if (physics.shouldAcceptUserOffset(this)) {
    context.setCanDrag(totalExtent > (viewportDimension - maxScrollExtent) || minScrollExtent != maxScrollExtent);
  } else {
    context.setCanDrag(false);
  }
}
```
3) Use this forked version of `NestedScrollView`.

**Comment by Piinks** [comment]
Hi folks, I am not sure here what the expected vs. actual results here are. Currently if I set the inner (body) scroll view of a NestedScrollView physics to NeverScrollableScrollPhysics, the inner scroll view does not scroll - which I think is expected.

I checked against the linked Dartpad as well. If someone can update with the actual/expected behavior, we can take a look! It is also possible we may have already fixed it 🤞 
Thanks!

**Comment by Piinks** [comment]
Hey @lavinov-mercury thanks for the update! i see what you mean. I will look into this. :)

**Comment by lavinov-mercury** [comment]
@Piinks I can also confirm, that fix proposed above worked as expected
@red282 would you mind to open a PR?

**Comment by Piinks** [comment]
Hey @red282 thanks for sharing! Your workaround would not work in all cases though. I have checked it out and one such case it does not work for is mouse scrolling. Your proposed change to update `setCanDrag` does not affect mouse scrolling, only scrolling through dragging.

I also found that this may be working as intended. Here are my findings:

The `NestedScrollView` should absolutely pass down whatever `ScrollPhysics` are provided to `NestedScrollView.physics` (I have a patch coming shortly for this), but in [the Dartpad example](https://dartpad.dev/?id=7c6b777299cd89fa53eb529d6e84eca0) @lavinov-mercury provided, it still will not result in the desired behavior.

If you look at how `ScrollView` is implemented, the Dartpad example is running into this specific case:

https://github.com/flutter/flutter/blob/4f5cc21be239c3cdefcad89f2bbbe1c508c36026/packages/flutter/lib/src/widgets/scroll_view.dart#L112

In a **vertical** `ScrollView` (like the `CustomScrollView` in the Dartpad), if `ScrollView.physics` has not been set, it will apply `AlwaysScrollableScrollPhysics`. So setting `CustomScrollView.physics` to `NeverScrollableScrollPhysics` would be required in your use case. With the patch I have coming, `Axis.horizontal` would see the expected behavior. The NestedScrollView cannot do that because it does not know what the `NestedScrollView.body` is, let alone what parameters it may or may not have set.

Even with my patch to allow the inner scroll view to inherit `NestedScrollView.physics` properly, those `AlwaysScrollableScrollPhysics` in that vertical case will always be there taking precedence. 

https://github.com/flutter/flutter/blob/4f5cc21be239c3cdefcad89f2bbbe1c508c36026/packages/flutter/lib/src/widgets/scrollable.dart#L408

I've noticed as well that this may be something folks expect, depending on their use case. I can see that `physics` is not the only property that would need to be set for both, the same goes for properties like `scrollDirection` and `reverse`. The `NestedScrollView` doesn't set these for the `CustomScrollView` either, so they can mismatch for different behaviors, or require both to be set.

I think we should definitely document all of this, so I will update this bug to reflect that.

**Comment by Piinks** [comment]
Actually, my patch makes me think this is even more intentional. It breaks a lot of existing tests if I pass down the physics. I think the opening line in the docs should be emphasized more:

> A scrolling view inside of which can be nested other scrolling views, **with their scroll positions being intrinsically linked.**

I think the option to have a different physics for the inner/outer scroll view is intentional, it is the linking of the position, having them move together in unison, that the NestedScrollView is primarily concerned with.
