### ISSUE TITLE
Code generator for widget equality

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4562]
It'd be really nice if we had a code generation for equality between widgets, like for example:

```
@equalableFields
class MyWidget extends StatefulWidget {
  final Foo myFoo;
  final Bar myBar;
  ...
}
```

would generate the following:

```
class MyWidget extends StatefulWidget {
  final Foo myFoo;
  final Bar myBar;
  ...
  bool hasEqualFields(MyWidget other) => myFoo == other.myFoo && myBar == other.myBar;
}
```

**Comment by Hixie** [comment]
cc @eseidel 

We have requested this from our upstream: https://github.com/dart-lang/sdk/issues/26703

**Comment by Hixie** [comment]
I'm going to close this because in our experience checking equality of widgets would be expensive since you'd be walking a tree. But please follow the aforementioned Dart bug if you want to implement this anyway in your code.

**Comment by iLoveDocs** [comment]
@Hixie Does this also mean that there is no benefit of using `const` in widgets like

```
const SizedBox(width: 2)
```
vs 

```
SizedBox(width: 2)
```

in terms of performance?

**Comment by Hixie** [comment]
`const` is great for performance because it makes the nodes equal with a pointer test, which is very cheap, and bypasses any need to walk any trees.
`operator ==` on a node with a child means potentially traversing the same size tree as the check would be avoiding in the first place, except you have to do it at _every level_, so you end up O(N^2) which is more expensive than just doing the work in the first place (O(N)).
