### ISSUE TITLE
FlutterActivity should extent AppCompatActivity instead of Activity

### ISSUE THREAD

**Issue by beiger** [flutter/flutter#45678]
[Added by @matthew-carroll because there was no description]
`FlutterActivity` currently extends `Activity`. It should extend `AppCompatActivity` so that Flutter developers can leverage newer capabilities like `Lifecycle` and `ViewModel`.

**Comment by beiger** [comment]
AppCompatActivity is more powerful than activity, such as LifecycleOwner, ViewModelStoreOwner. It is more popular in Android projects.

**Comment by helinanever** [comment]
Hi @beiger,

Is it proposal? Could you elaborate it more extendedly? 

Thank you.

**Comment by beiger** [comment]
Yes, it's a proposal.

Sometimes, I need to use Android code to complete some Android specific functions, while the MVVM architecture commonly used by Android needs ViewModel, which requires the activity implements the viewmodelstoreowner interface.

For another example, I need to listen to the life cycle of an activity, which needs to implements the activity of the lifecycle owner interface.

What's more, the official attitude of the Android team is very clear. In the future, Android x will dominate. For example, if I want to use the dialogfragment of Android x, I need to the activity implements FragmentActivity from Android X.

Appcompatactivity can meet the above conditions.

So I hope that FlutterActivity or Flutter2Activity can extends AppCompatActivity.

**Comment by matthew-carroll** [comment]
Hi @beiger. Flutter provides a `FlutterFragmentActivity`, which you can choose to use instead of `FlutterActivity`:

https://api.flutter.dev/javadoc/

`FlutterFragmentActivity` extends `FragmentActivity`, which implements `LifecycleOwner` and `ViewModelStoreOwner`:

https://developer.android.com/reference/android/support/v4/app/FragmentActivity

Can you please give that a try and let us know if it handles your use-cases?

**Comment by beiger** [comment]
Thanks for your response @matthew-carroll .

FlutterFragmentActivity is about to meet my needs. I also hope FlutterFragmentActivity can migrate to AndroidX.

**Comment by matthew-carroll** [comment]
@beiger Flutter's Android embedding will move to AndroidX sometime in the near future, but we're not sure exactly when.

I'll go ahead and close this issue because it sounds like `FlutterFragmentActivity` will handle your use-case.

**Comment by GhostInMatrix** [comment]
Can't agree more...I was using embedding FlutterActivity and communicating with Native Libs which has been already published using FragmentActivity as there super activity... Now... I have to modify these libs to support android.app.Activity as there super activity , because FlutterActivity extends android.app.Acitivty...
