### ISSUE TITLE
Some microbenchmarks stopped sending data 

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#45732]
![2019-11-27-140830_2529x473_scrot](https://user-images.githubusercontent.com/31859944/69762629-b4036080-111f-11ea-8d2e-8dcebd212f27.png)

Started happening since https://github.com/flutter/flutter/commit/5df4b7db239964c479ac0d8cddf381b358ebc157

@blasten @liyuqian

**Comment by Hixie** [comment]
@liyuqian suggests this is because `flutter run xxx.dart` is ignoring the `xxx.dart`. If this is true then this is a stop-ship regression.

**Comment by blasten** [comment]
@Hixie I'm looking at this issue. I doesn't seem `flutter run` is ignoring the entrypoint.  As you noted, it's very likely that this issue is caused by https://github.com/flutter/flutter/pull/45307#discussion_r351482035.

**Comment by xster** [comment]
`flutter run -t xxx` seems to work for me on head as well`

**Comment by blasten** [comment]
The issue is that the test relies on the `flutter run` stdout. In verbose mode, `flutter run` stdout also includes the device's stdout (from the device logger) which used to skip logs that were older than the `flutter run` command invocation.  In my change, I forwarded all the device logs that have the "flutter" tag, so that isn't what the test expects.

**Comment by liyuqian** [comment]
I just confirmed that `flutter run xxx.dart` worked for me too. Sorry for giving you the wrong suggestion because I tried to modify the running target in [microbenchmarks.dart](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/microbenchmarks.dart) and saw the result of `dart bin/run.dart -t microbenchmarks` to be not changed. Now I understand that the result doesn't change because we're always reading the old log...

**Comment by Hixie** [comment]
Ok, good. Removing panic markers.

Can we return to the previous behaviour? We didn't have the old behaviour just randomly, it was very much intentional that `flutter logs` and `flutter run` not give you old logs. :-)

**Comment by blasten** [comment]
The microbenchmarks are back!

**Comment by Hixie** [comment]
Yay! Thanks for fixing this on your day off! Please definitely don't feel you must do that, but it is appreciated! :-)
