### ISSUE TITLE
Recommended design pattern for clean architecture

### ISSUE THREAD

**Issue by wisnuwiry** [flutter/flutter#45752]
Recommended design pattern for clean architecture...

**Comment by KalilDev** [comment]
Provider, redux and BLoC are really good state management options. I personally use BloC, in a way that the top level BLoCs are initialized on main, and the BLoC providers are the root widgets, before the MaterialApp. With this, I can easily replace the BLoCs with mock ones for integration tests. And, because all the state is managed by BLoCs, my app is mostly stateless, and it doesn't rebuild unnecessarily, but this is the case for all good state management on flutter. Also, the flutter team, on one talk, mentioned they used provider, but it's up to the user to choose how he will manage the state as most options for doing so are really good.
