### ISSUE TITLE
Missing AnimatedGrid widget

### ISSUE THREAD

**Issue by jasin755** [flutter/flutter#45770]
There is no AnimatedGridWidget. I have wanted to create grid like iOS with computing changed with animation. But I haven't found any sample or something like AnimatedGrid.

**Comment by iapicca** [comment]
Hi @jasin755 
sure an "out of the box" animated grid can be useful,
but if you can wait you may try to adapt this [code](https://flutter.dev/docs/catalog/samples/animated-list) to a grid
thank you

**Comment by troy379** [comment]
Any update in 2022? I've spent a bunch of time looking for a library or any working code snipped but had no luck... I also made unsuccessful attempts to create my own solution but my expertise is not enough to beat the beast 😓 
Since we already have [SliverAnimatedList](https://api.flutter.dev/flutter/widgets/SliverAnimatedList-class.html) and [AnimatedList](https://api.flutter.dev/flutter/widgets/AnimatedList-class.html) isn't it that obvious to have the same concept for grids?
