### ISSUE TITLE
Whitelist flutter's ip's being used to pull packages

### ISSUE THREAD

**Issue by RanABI** [flutter/flutter#45859]
Hi,
I am getting this message while trying to develop on my work laptop:

> Waiting for another flutter command to release the startup lock...
> Running "flutter pub get" in RejectsManager-master...           
> Got socket error trying to find package autocomplete_textfield at https://pub.dartlang.org.

The problem is the list of IP's flutter use to get the packages are not on the company's whitelist.

I failed to find these ip's, and wondered if I might be able to find help here.
Thanks !

**Comment by iapicca** [comment]
Hi @RanABI 
I'm not sure about what can be done on flutter side,
although you might find some useful information [here](https://github.com/flutter/flutter/issues/17285)
and on stack overflow.
Does this solution help your case?
thank you

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
