### ISSUE TITLE
Use caret syntax for all dependencies in flutter_localizations

### ISSUE THREAD

**Issue by ramsestom** [flutter/flutter#45863]
the flutter_localizations pubspec.yaml file (https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml) should use "^" for all its dependencies. For example `intl: 0.16.0` should be `intl: ^0.16.0`  as enforcing a specific version put serious constraints on all apps using this package meaning that this app wouldn't be able to use any other package requiering a version of a dependency superior to the one used in flutter_localizations. 
For example if you try to use flutter_localizations and flutter_form_builder you end up with this issue:
https://github.com/danvick/flutter_form_builder/issues/185

> Because every version of flutter_localizations from sdk depends on intl 0.15.8 and flutter_form_builder >=3.5.4 depends on intl ^0.16.0, flutter_localizations from sdk is incompatible with flutter_form_builder >=3.5.4

**Comment by jonahwilliams** [comment]
Constraining `intl` with a caret would not solve the error you've posted, since for versions less than 1.0 the caret only goes until the next minor version. Furthermore, we specifically pin our versions of all dependencies to ensure the versions we test are the same versions that are shipped, avoiding purposeful or accidental breaking changes due to version selection that is difficult to reproduce.

The version of intl was updated to 0.16 in https://github.com/flutter/flutter/commit/0167f53101acba7c61a01b1dab843c2bf6367f6d which was about 3 months ago, so it should be in the current beta or whenever the next stable candidate is. In the meantime, you can work around the issue locally by either downgrading to a version of flutter_form_builder that supports intl 0.15, or using a [pubspec dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) to force the version of your choice.
