### ISSUE TITLE
Firebase Analytics Flutter

### ISSUE THREAD

**Issue by SteviePlaysMc4** [flutter/flutter#45876]
Been looking around haven't find any fix for this problem with flutter

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)

Using firebase_analytics: ^5.0.6 in my flutter dependences

**Comment by iapicca** [comment]
Hi @SteviePlaysMc4 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
