### ISSUE TITLE
Rename either `dev/tools/localization/gen_l10n.dart` or dev/tools/localization/gen_localizations.dart

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#45909]
- `gen_l10n.dart` is the tool that Flutter developers can use to internationalize their Flutter applications
- `gen_localizations.dart` is a tool that Flutter uses to internationalize the Cupertino and Material libraries

Maybe we should rename `gen_localizations.dart` to  `gen_cupertino_and_material_localizations.dart`? The only problem I have with that is how long the name is, but that should clear up any confusion between the two files.

cc/ @HansMuller

**Comment by pedromassangocode** [comment]
This issue is not valid anymore since the file names were updated and some of them moved from their original location.

I'm closing this as probably fixed. Please open it back if there is still work to do in order to fix this.

![Screen Shot 2020-09-24 at 14 45 34](https://user-images.githubusercontent.com/67424416/94153477-bb48e700-fe74-11ea-9fb1-e69d0699bab2.png)
