### ISSUE TITLE
UserAccelerometer sensor returns 0 values on some phones

### ISSUE THREAD

**Issue by orosznyet** [flutter/flutter#45980]
**Target Platform:** Android
**Target OS version/browser:** Android 9
**Devices:** Huawei Mate 9 Pro

I'm currently working on an application detecting phone shakes using UserAccelerometer  TYPE_LINEAR_ACCELERATION on Android), but some phones can only produce events with x:0,y:0,z:0 while accelerometer and gyroscope works. [(my testing tool)](https://github.com/orosznyet/flutter_visual_accelerometer)

After investigating the [android native code](https://github.com/flutter/plugins/blob/master/packages/sensors/android/src/main/java/io/flutter/plugins/sensors/SensorsPlugin.java) I'm fairly certain that the issues comes from the OS/device itself rather than the Flutter plugin. 

I tried to bypass this issue by using the basic accelerometer with gravity, but it turns out that there's more to it than some basic math (like combining multiple sensor inputs in a specific way).

**Comment by zoeyfan** [comment]
We're closing this issue because it seems to be a question or request for help rather than a bug in Flutter plugin. 

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
