### ISSUE TITLE
Error   Failed assertion: line 1334 pos 7: 'tileWidth != leadingSize.width' from version 1.7.8+hotfix.4 

### ISSUE THREAD

**Issue by Cheanakhim007** [flutter/flutter#46048]
I/flutter (24760): The following assertion was thrown during performLayout():
I/flutter (24760): Leading widget consumes entire tile width. Please use a sized widget.
I/flutter (24760): 'package:flutter/src/material/list_tile.dart':
I/flutter (24760): Failed assertion: line 1334 pos 7: 'tileWidth != leadingSize.width'
I/flutter (24760):
I/flutter (24760): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24760): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24760): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24760): https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24760):

How to fixed  Failed assertion: line 1334 pos 7: 'tileWidth != leadingSize.width' from version 1.7.8+hotfix.4

**Comment by iapicca** [comment]
Hi @Cheanakhim007 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
and provide your updated `flutter doctor -v` 
together with a minimal code sample to reproduce the problem
thank you

**Comment by micimize** [comment]
@Cheanakhim007 this will happen when the tile is squeezed to being narrow due to a parent, or (apparently) when it mounts when the screen is off as in #37451

I think this assertion should be removed or turned into a warning - it seems fairly inconsistent to me that it crashes the whole application in situations where there hasn't really been a mistake (like `Visiblity(visible: false, child: Container(width: 0, height: 0, child: ... ListTile))`)

```
Flutter 1.12.12 • channel master • https://github.com/flutter/flutter.git
Framework • revision bae92c32e5 (6 weeks ago) • 2019-11-24 22:29:28 -0800
Engine • revision b6b54fd606
Tools • Dart 2.7.0
```
