### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#46571]
@Gyoko reports that users are getting a crash on startup in their app built against 1.12.

@Gyoko, can you answer the following questions:
1. What device(s) is this crash happening on?
1. Can you reproduce the error locally?
1. Can you include the `adb logcat` output of a crash or an adb bugreport?
1. Can you attach the APK in which this is happening, or the Play Store listing with the version that is crashing?

**Comment by tvolkert** [comment]
@Gyoko any update?

**Comment by Gyoko** [comment]
Like I said, this is not an issue with the `beta 1.12` release itself.
If I perform a clean install on a device - it will work as intended.
HOWEVER, if a user has app already installed, and the app was built using `master 1.9.1`. If I publish a release built with `beta 1.12`, and this user will try to update his` master 1.9.1` app with` beta 1.12`, then the app will be stuck on black screen. This happens on pretty much every phone. If the user uninstalls the `1.9.1 `app, and then installs `beta 1.12`, then the app will work as intended.

Meaning that` beta 1.12` is nonviable for public release, since it would present black screen for all existing users and would force them to reinstall the app.

**Comment by tvolkert** [comment]
@Gyoko in #37155 you had reported "_Sigh_, now that "black screen" users are okay, normal users start getting crashes at startup."

_This bug_ is specifically tracking these crashes you reported -- and the black screen on update is tracked separately in #46570.

Many times, crashes are due to Java/Kotlin code, not Flutter code, so without a stack trace (`adb logcat`), there's no actionable info against which we can try to diagnose the problem.  Hence, the questions in the summary of this issue:

1. What device(s) is this crash happening on?
1. Can you reproduce the error locally?
1. Can you include the `adb logcat` output of a crash or an adb bugreport?
1. Can you attach the APK in which this is happening, or the Play Store listing with the version that is crashing?

**Comment by godofredoc** [comment]
Removing team: infra seems like not related to infra

**Comment by iapicca** [comment]
Hi @tvolkert and @Gyoko 
is this issue meant to remain open?
thank you

**Comment by tvolkert** [comment]
Closing, as we've had no other reports of this, and we don't have sufficient info to investigate.
