### ISSUE TITLE
flutter/plugins CI should use analysis_options.yaml

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#46808]
Right now we have an analysis_options.yaml but it seems like our CI is ignoring it because undocumented methods are still being allowed.

~We could copy it into the root of each package before running the analyze command.~ (edit: this doesn't seem to matter)

Flutterfire repo would make use of this as well.

This would help ensure that the `public_member_api_docs` lint rule is followed (all methods are documented). However there's going to be a bit of work required to turn this on initially because all the failures will need to be fixed or skipped.

**Comment by mklim** [comment]
@collinjackson could you link to an instance where it appears that CI is ignoring this file? In my testing I remember being blocked in multiple PRs based on analysis failures from the `analysis_options.yaml`, so I'd be really surprised if we weren't using it _at all_. I think it's probably more likely that there's a specific issue with it being applied to a particular package somehow.

**Comment by mklim** [comment]
Actually, I do have concrete proof it's getting generally used, or at least was recently. We were red at tip of tree for 24 hours based on `package:pedantic` updating to a newer minor version and applying new lints that we were failing on until I locked it to a specific patch revision in flutter/plugins#2354. You can see a previous failing run from before that fix but from the new `pedantic` package in https://cirrus-ci.com/task/4569764797612032.

**Comment by collinjackson** [comment]
I'm basing this on the Flutterfire CI passing while are undocumented methods and other analysis failures. Moving the analysis_options up to the package level seems to trigger the analysis.

See for example https://github.com/FirebaseExtended/flutterfire/pull/1626 which updates cloud_functions package.

Despite there being 2 undocumented methods, the analysis step has no failures.

https://cirrus-ci.com/task/5973384092975104

What I get when I run analyze locally:
```
$ flutter analyze
Running "flutter pub get" in example...                                     ⣷
    5.5s
Analyzing example...                                                    
No issues found! (ran in 2.4s; one public member lacks documentation)
```

**Comment by mklim** [comment]
Thanks for clarifying. Yeah, so the reason you're not seeing an error there is because `cloud_functions` already has a bunch of undocumented methods so it has a custom `analysis_options.yaml` that is excluding it from linter rules that it's already failing: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/analysis_options.yaml#L11 It's how I landed the linter without needing a massive migration first. The top level lints are being used, but not all packages have been cleaned up to meet them yet.

I think this is a dupe of #45440, where I'm tracking cleaning up all the already failing exclusions. Though I didn't talk about the FlutterFire repo there, so maybe there could be a second issue for that. WDYT?

**Comment by collinjackson** [comment]
Thanks for clarifying, I see how it works now. Closing this issue and will update FirebaseExtended/flutterfire#1610
