### ISSUE TITLE
Provide custom autocomplete text widget

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#46824]
TextFields could benefit from having an autocomplete feature where a dropdown provides suggestions based on already what's already been typed into the text field, similar to https://www.w3schools.com/howto/howto_js_autocomplete.asp

cc/ @hillelcoren @justinmc

**Comment by shihaohong** [comment]
cc/ @willlarche, I'm wondering if Material has guidance on this

**Comment by mdebbar** [comment]
For clarification, there are two features that could be referred to as "autocomplete":

1. **Browser's autofill**: this is where the browser can fill your text fields with info like address, email, first/las name, etc.
2. **Typeahead**: this is a dropdown that shows app-dependent suggestions like Google or Youtube's search box.

These two are entirely separate features. The first one needs to be built into the framework so that the material/cupertino text fields can be autofilled by the browser.

The second one can be built as a 3rd party package (it's possible that the material team would provide something out-of-the-box if they want to).

**Comment by nturgut** [comment]
Thanks for filing the issue.

for the (1) part @mdebbar mentioned, we will be adding it in near term. We are working on a solution with Framework team.

I am removing the platform-web label since we have another one: https://github.com/flutter/flutter/issues/41634

Please feel free check the TextEditing project for issues we are planning to work on (or already working on). https://github.com/flutter/flutter/projects/57

**Comment by hillelcoren** [comment]
@shihaohong thank you for creating this issue! 

From the number of up-votes it's clear there is tremendous interest from the community in having a first-party autocomplete solution (type #2). I've been building web apps for 20 years, I've used an autocomplete component in almost every app I've ever built. For reference this [Javascript solution](https://github.com/select2/select2) has almost 25k stars. 

It would obviously be impossible for the Flutter team to develop every type of widget however one of Flutter's greatest strengths is that it has built in support for "common widgets" which I'd argue this is a good example of.

**Comment by yjbanov** [comment]
I changed the description and the labels to reflect that this is a new widget request rather than request to integrate with the platform's built-in autocomplete.

We will use https://github.com/flutter/flutter/issues/41634 to track the platform-integrated version.

**Comment by mariamhas** [comment]
For the second use case, typeahead. There is https://pub.dev/packages/autocomplete_textfield that seems like a good fit. It should work for web.

**Comment by hillelcoren** [comment]
@mariamhas thanks for the suggestion, sadly from the readme it doesn't look like it's being actively worked on.

We're currently using this package: https://pub.dev/packages/flutter_typeahead. It has a great API but needs some improvement to make it work better on web/desktop, for example you can't use the keyboard to select a value.

**Comment by justinmc** [comment]
I think we can close this now that the Autocomplete widget is in master ([docs](https://master-api.flutter.dev/flutter/material/Autocomplete-class.html), [PR](https://github.com/flutter/flutter/pull/73753)).  See the [design doc](https://docs.google.com/document/d/1fV4FDNdcza1ITU7hlgweCDUZdWyCqd-rjz_J7K2KkfY/edit) for planned upcoming work.

**Comment by hillelcoren** [comment]
@justinmc and team thanks for your work on this. I've started to incorporate it into our app, it's working great!

Hope this is an ok place for feedback/questions

- With the `RawAutocomplete` widget I can set the initial value by specifying the `textEditingController`, I don't see a way to set the initial value when using the `Autocomplete` widget. Would it make sense to add an an `initialValue` property or is there another solution I'm missing? 

- When defining the `optionsViewBuilder` it's common to use the current filter to render the UI, for example to highlight the part of the record which matches. This is possible with the current design by tracking a `_filter` variable in `onChanged` in the `fieldViewBuilder` but it may be convenient to pass the `textEditingValue` to the `optionsViewBuilder` like it's currently passed in the `optionsBuilder`. 

- I don't see this in the design doc but it would be very helpful to have a way to manually request the options list to be shown.

**Comment by justinmc** [comment]
I'm really excited that you're able to use this!  This is great feedback.  We should probably open issues for these.

  1. I don't think there's any other way.  When I added `textEditingController` and `focusNode` to RawAutocomplete, I wondered if we might end up needing them for Autocomplete too.  Does that sound like a good solution to this to you?
  2. I hadn't thought of that use case, but it seems pretty common.  You could do this with RawAutocomplete by passing the TextEditingController, and if we added that to Autocomplete too as mentioned in 1, then you could do it there too.  Though, even if TextEditingController is made available this way, maybe we should still pass TextEditingValue as you suggested?
  3. [Currently](https://github.com/flutter/flutter/blob/16af4aa7ebf549f893ebed12106c45adb9440fbd/packages/flutter/lib/src/widgets/autocomplete.dart#L652) the options list is shown when the field is focused, the selection is null, and the options list isn't empty.  Maybe we could just provide a nullable boolean parameter that forces it open/closed if set?

CC @shihaohong for opinions on this when you're back from Chinese new year.

**Comment by hillelcoren** [comment]
1. I think the challenge is in Flutter when adding a text field to a form you can either use the `initialValue/onChanged` properties or set a TextEditingController to wire it up. To make it easy to drop in an AutoComplete where you would have a TextField it would be simplest if they had similar APIs. You can set an `onChanged` handler using the `fieldViewBuilder` but I don't see an easy way to set the initial value without supplying and managing a TextEditingController. Pre-selecting an item is very common, I think it should be as simple as possible. How do you feel about adding an `initialValue` or `selectedValue` property? Note: it may be called `initialValues/selectedValues` to support multi-selection. 

2. I'm always trying to "make common things easy and rare things possible", although it's possible using a TextEditingController I'd argue this is common enough that it's worth passing the TextEditingValue. 

3. Maybe... two alternatives to consider could be allowing to override the `_shouldShowOptions` method or creating an optional AutocompleteController with show/hide methods to support imperative interactions.

4. One small problem I thought was worth mentioning is if you're using dark mode the theme isn't applied in the Overlay. I think this may be caused by [this issue](https://github.com/flutter/flutter/issues/39379). A workaround is to wrap the `optionsViewBuilder` result in a Theme widget passing the main theme data.

**Comment by hillelcoren** [comment]
Sorry, one more important thing... 

5. It would be great if when the overlay is shown clicking outside of it would hide it.

**Comment by shihaohong** [comment]
Sorry for taking some time to respond to this!

> With the RawAutocomplete widget I can set the initial value by specifying the textEditingController, I don't see a way to set the initial value when using the Autocomplete widget. Would it make sense to add an an initialValue property or is there another solution I'm missing?

I think wiring through a `textEditingController` parameter for Autocomplete should be pretty simple and straightforward! I filed the following issues:
Expose `Autocomplete.textEditingController`: https://github.com/flutter/flutter/issues/78179

> How do you feel about adding an initialValue or selectedValue property? Note: it may be called initialValues/selectedValues to support multi-selection.
I don't see an `initialValue` parameter on `TextField` -- Did you mean using `onChanged` together with `controller`? When you say pre-selecting an item, did you mean already having an item highlighted/selected when the options are shown?

> When defining the optionsViewBuilder it's common to use the current filter to render the UI, for example to highlight the part of the record which matches. This is possible with the current design by tracking a _filter variable in onChanged in the fieldViewBuilder but it may be convenient to pass the textEditingValue to the optionsViewBuilder like it's currently passed in the optionsBuilder.
This seems pretty straightforward as well (and the suggestion makes sense). The only concern is that it'd be a breaking change since the function signature would change and the Autocomplete widget has already made it into stable :( We should definitely create a feature for it and describe the workaround for getting this to work somewhere.
Update Autocomplete optionsViewBuilder function signature to share the current `TextEditingValue`: https://github.com/flutter/flutter/issues/78181

> Maybe... two alternatives to consider could be allowing to override the _shouldShowOptions method or creating an optional AutocompleteController with show/hide methods to support imperative interactions.
Both ideas sound good here, although we should make sure that we make it explicit to the user that they are overriding the behavior here. Filed issue: https://github.com/flutter/flutter/issues/78182

> One small problem I thought was worth mentioning is if you're using dark mode the theme isn't applied in the Overlay. I think this may be caused by this issue. A workaround is to wrap the optionsViewBuilder result in a Theme widget passing the main theme data.
This feels like a bug. I know we run into these situations with overlays quite frequently (I've commonly seen this pop up with Tooltip and DropdownButton). I'll file an issue: https://github.com/flutter/flutter/issues/78183

> It would be great if when the overlay is shown clicking outside of it would hide it.
This makes sense! I think this should be the behavior by default (it would be breaking, but it seems like this is what most users would/should expect). We can also provide an option to let the developer decide whether it does or not. Filed issue: https://github.com/flutter/flutter/issues/78184

**Comment by hillelcoren** [comment]
Amazing, thank you!!

The `initialValue` property belongs to `TextFormField`. Yup exactly, for example preselecting the item in a form.
