### ISSUE TITLE
Travis sometimes fails due to pub version conflicts

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4695]
On Travis, we run `pub upgrade` on each package in sequence.  If there's a write to `pub.dartlang.org` during this process, we can end up with different versions of our dependencies for each of our packages.  We will then fail the later Travis step that checks that we have consistent versions for all of our dependencies.

**Comment by eseidelGoogle** [comment]
I guess one way we could hack around this is to have `flutter update-packages` (the command which knows how to do these 17 pub upgrades) include the version check step and know to re-run itself once if the versions don't align?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart

Or @munificent maybe there is a better way we should be holding pub here?  We want to make sure all 17 of our packages have run pub get, and that they all got the same versions of packages. :)

**Comment by munificent** [comment]
cc @nex3

> We want to make sure all 17 of our packages have run pub get, and that they all got the same versions of packages. :)

Even if you could run all commands at the exact same instant in time and ensure nothing gets pushed to pub during that window, it doesn't guarantee all of those packages will end up with the same version of some dependency. They may have different constraints (immediate or transitive) that lead to it picking different versions for each.

Each of those 17 packages has its own little sea of dependencies that the solver operates in. Even if each of those packages access the same *universe* of packages, it's dependencies may lead to picking a different set of versions. Is there a reason you want to avoid that?

If you *really do* want all 17 packages to have the exact same versions of every dependency they happen to have in common, then from pub's perspective, what you're talking about is more like a single monolithic package, not 17 separate ones.

You could try to make something like that work. Make an ur-pubspec that has path dependencies on all 17 of those. Run pub upgrade on it, then copy the resulting lockfile and .packages file over to each of the 17 packages and have them use it.

That's a little fishy because those packages will end up with access to other packages they may not depend on because one of their 16 siblings does.

**Comment by abarth** [comment]
> Is there a reason you want to avoid that?

Yes, we want to use a consistent set of packages.  Consider the case where package:args has a subtle behavior quirk that changes from version x to y.  We either want all of our tools to have that quirk or none of them.

> what you're talking about is more like a single monolithic package, not 17 separate ones.

Ideally we want to solve for a single set of dependencies, but we won't want those dependencies to be available in each of our packages.  In that sense, we don't want it to be monolithic.  I know that runs contrary to pub's philosophy of over-approximating the set of dependencies for a package.

> copy the resulting lockfile and .packages file over to each of the 17 packages and have them use it.

We don't want to do that because, for example, we don't want package:markdown available in package:flutter.  Specifically, if a random file in package:flutter accidentally imports package:markdown, we want the tests for package:flutter to fail with an unknown import.  If this didn't occur, an end-developer who depends on package:flutter would get that error when they tried to use the package.

> That's a little fishy because those packages will end up with access to other packages they may not depend on because one of their 16 siblings does.

Correct.

**Comment by munificent** [comment]
> Consider the case where package:args has a subtle behavior quirk that changes from version x to y. We either want all of our tools to have that quirk or none of them.

Yeah, that makes sense.

> Ideally we want to solve for a single set of dependencies, but we won't want those dependencies to be available in each of our packages. In that sense, we don't want it to be monolithic.

Right. One way to look at this is that you want it monolithic at first, but then split it up later. Something like:

1. Run pub upgrade on a mega-package that unions all 17 packages' dependencies.
2. Now get the set of resulting packages—with a single version of each—and consider that the universe of possible packages.
3. Now run pub upgrade on each of the 17 packages individually, against that universe.

Pub doesn't currently have a way to express step 2, but I wonder if this is common enough problem that it should, or if it should have some other primitive operation that the above process could be expressed in terms of.

>  I know that runs contrary to pub's philosophy of over-approximating the set of dependencies for a package.

Well, it's not that we *like* over-approximating. Just that we're willing to trade off that in order to get other desirable stuff (mainly simplicity and few things users have to manually configure and risk getting wrong). We're as precise as we can be without making users jump through a lot of error-prone hoops.

**Comment by Hixie** [comment]
Since our medium term plan is to pin everything and have a bot do rolling updates, this is probably moot, so I'm going to close it.
