### ISSUE TITLE
Expose FilterQuality in DecorationImage

### ISSUE THREAD

**Issue by Afsar-Pasha** [flutter/flutter#46978]
Currently `DecorationImage` uses `FilterQuality.low` to paint image and there is now way to change that. It would be great if `DecorationImage` exposes `FilterQuality` which defaults to `FilterQuality.low` and used in `paintImage`.

**Comment by iapicca** [comment]
Hi @Afsar-Pasha 
could you describe you proposal more in dept?
thank you

**Comment by Afsar-Pasha** [comment]
@iapicca updated issue.

**Comment by iapicca** [comment]
thank you @Afsar-Pasha

**Comment by yjbanov** [comment]
@Afsar-Pasha `FilterQuality.low` should actually look pretty good despite the "low" in the name. It uses bilinear interpolation, which is not that much worse than bicubic. The issue might have been that we weren't passing the filter quality to the engine _at all_. I fixed it in https://github.com/flutter/flutter/pull/74854 yesterday, so you should see improvement on the master channel. Can you please give it a shot?

**Comment by Afsar-Pasha** [comment]
@yjbanov looks like you misunderstood the issue, I meant `DecorationImage` uses [hard coded](https://github.com/flutter/flutter/blob/49de01c92810e2dd0ca205a9eaecd8c481dba46a/packages/flutter/lib/src/painting/decoration_image.dart#L288) `FilterQuality.low` for painting image and there's no way to change that, I would like to have an optional parameter `filterQuality` (defaults to `FilterQuality.low`) in `DecorationImage` which should be used to paint image instead of that hard coded value.

**Comment by yjbanov** [comment]
You are right that `DecorationImage` hard-codes `FilterQuality.low`. However, prior to a recent fix we didn't apply `filterQuality` at all because it was applied conditionally:

https://github.com/flutter/flutter/blob/45e02daf22818b3cf0b9d57a39a8f1d511bf23c7/packages/flutter/lib/src/painting/decoration_image.dart#L476

So I think what you were actually seeing in your app was `FilterQuality.none`, not `FilterQuality.low`.

I'd be curious if `DecorationImage` looks better in your app. If it looks good then perhaps we don't need to customize `filterQuality` on `DecorationImage`?

**Comment by Afsar-Pasha** [comment]
Yeah that was the problem, now it looks good.
Sorry for not checking earlier, also thanks for the PR.
