### ISSUE TITLE
Documentation error: dependOnInheritedWidgetOfExactType

### ISSUE THREAD

**Issue by tedhenry100** [flutter/flutter#47067]
From https://api.flutter.dev/flutter/widgets/BuildContext/dependOnInheritedWidgetOfExactType.html

> This method should not be called from widget constructors or from State.initState methods

From https://api.flutter.dev/flutter/widgets/State/initState.html
> You cannot use BuildContext.dependOnInheritedWidgetOfExactType from this method

Which one is it? Is it "should not" which is a best practices recommendation _or_ is it "cannot" which is a technical impossibility?

A common case where using the build context inside `initState` is convenient is to get some _unchanging_ inherited widget like a services object. (A sort of dependency injection without having to pass/inject the dependency manually all the way down the widget tree.)

    @override
    void initState() async {
        super.initState();
        var data = await this.context.dependOnInheritedWidgetOfExactType<Services>().loadData();
        this.setState(() {
            this._data = data;
        });
    }

Also there is a formatting error in the initState documentation when rendered as HTML: The last bullet point about dispose runs into the next paragraph.

**Comment by petermichaux** [comment]
It appears the "should not" wording was introduced by @Hixie on Aug 29, 2016
in the following commit.

https://github.com/flutter/flutter/commit/ea6bf4706a64532fbadf483367c99bcf8ae2c531#diff-16a8dc6e114c65d7a516fc759bac2316

It looks like that documentation was based on the work of @HansMuller on Aug 26, 2016 in the following commit.

https://github.com/flutter/flutter/commit/d0e72d616bd6d143d2a56e93ed378b5fc4697770#diff-16a8dc6e114c65d7a516fc759bac2316

Is it only an assert that stops the getting of inherited widgets during `initState`? If getting inherited widgets during `initState` is otherwise technically possible, is what is perhaps seen as a best practice by the Flutter team really something that should be limited? Is knowing the inherited widgets at the time of `initState` really such a bad thing? Everything else that is done during `initState` is based on the app's state at the time `initState` executes. Why not have access to the inherited widgets at that time too?

**Comment by Hixie** [comment]
In the documentation, we don't really distinguish between "should not" and "cannot" because nobody stops you from forking the framework, removing whatever asserts make it "impossible", and violating the "cannot" anyway.

I'll change these to "should not" for consistency, and will make sure the right behaviour is mentioned.
