### ISSUE TITLE
Flutter isn't very helpful when you're missing a `macos` directory

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47145]
Steps:

In an existing Flutter project (created before enabling desktop), try `flutter run -d macos` (on macOS, obviously).

The error message will look like this:

```
Running "flutter pub get" in blank...                               0.4s
 
Launching lib/main.dart on macOS in debug mode...
Unable to get Xcode project information:
 xcodebuild: error: The directory /Users/dnfield/src/flutter_projects/blank/macos does not contain an Xcode project, workspace or package.
```

It would be great if this command either automatically created a blank macos project, or at least printed out steps on how to do so (`flutter create .`).  I haven't tested this on other platforms, but I assume the same applies there.

/cc @jonahwilliams @stuartmorgan

**Comment by stuartmorgan** [comment]
@csells has a proposal in a doc for how the tool should behave in situations like this.

**Comment by kf6gpe** [comment]
Hmm. On the dev channel with 1.13.7-pre.29, I'm seeing
```
$ flutter run -d macos
No devices found with name or id matching 'macos'
```
Am I doing something wrong here?

**Comment by stuartmorgan** [comment]
Sounds like you didn't enable macOS support with `flutter config`.

**Comment by csells** [comment]
Make sure the following are true:

- that you're running on master or dev
- that you've done ```flutter config --enable-macos-desktop```
- that you have a macos folder with a Runner project in it

If the last one isn't true, delete the macos folder you have and run ```flutter create .``` which should produce that folder for you

**Comment by stuartmorgan** [comment]
> that you have a macos folder with a Runner project in it

Missing just that step gives the error originally reported, rather than the device error.

(Separately from the big-picture design of what the tool should do longer term to make multi-platform support more graceful, I do plan in the short term to add a quick sanity check to the desktop platforms that the project exists, because forms of this error come up for Windows and Linux too when people don't follow the instructions and just try turning on the config setting and then running a project.)

**Comment by stuartmorgan** [comment]
It looks like there was a regression at some point here; all the desktop builds actually do have a specific check that the platform directory exists with an early error-out if it doesn't, but it appears that somewhere along the way we started unconditionally creating generated files when trying to run, so that check is passing. I'll improve the tests, and fix up the generation to not run when the directory doesn't exist (which was supposed to be the case already).

I can add some basic instructions to the error messages as well.

**Comment by kf6gpe** [comment]
Thanks, @stuartmorgan and @csells! And yes, I'd forgotten the flutter config step, too.
