### ISSUE TITLE
Scroll wheel scrolling is not smooth

### ISSUE THREAD

**Issue by dimiril** [flutter/flutter#47536]
I just started learning Flutter. And I faced one big problem which is bad scrolling in complex list. Let's say we have 5 different item type in our ListView and some item type must display images and it's infinite scroll. I read a lot articles and posts about ListView for Flutter and all the things I've seen are simple list with text. How can I make smooth scroll?

**Comment by HansMuller** [comment]
Scrolling, even for a list with complex items, should be smooth by default.

It would help if you could provide the output of `flutter doctor` and a small self-contained app that demonstrates the scrolling problem. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by dnfield** [comment]
It would also help to know if you're seeing this on web, desktop, mobile, or all of the above.

**Comment by dimiril** [comment]
Shaper in the app with pictures gets slow to scroll

**Comment by iapicca** [comment]
Hi @dimiril 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by kunit1** [comment]
Below applies to all platforms that support a mouse / touch-pad: 
No sure of this is related but I noticed that scrolling with a scroll wheel vs a touch pad is provides a different experience. If the mouse wheel has scroll break points (each partial turn of the wheel has a ridge) then Flutter will simple jump directly to that scroll position. Using the same mouse wheel on a standard web page or desktop application there is a "curve" or "animation" where the page will scroll and slowly pause at the scroll location.

Using a touch-pad Flutter feels smoother because the scrolling motion is more continuous.

See the following Flutter Web page sample and scroll very slowly with a mouse wheel vs touch-pad.
 [Flutter sample Page](https://marcinusx.github.io/egipt/#/)
