### ISSUE TITLE
rebuild question

### ISSUE THREAD

**Issue by jiangyh1024** [flutter/flutter#47576]
I have a tab page called 'me'. And on this page, I have an avatar generated through `Image.memory()`.
code snippet like:
```
container(
 child : imguint8list != null ? Image.memory(imguint8list) : Image.assets("default_avatar.png")
)
```

There are also some routes directing to others pages which are put in a listview on 'me' page, for example 'change password'

after I push 'change password' into route stack, do some stuffs and then pop it. The 'me' page is rebuilt thus causing 'avatar' to be flashed in a short period of time. I am wondering how to solve this flashing issue. 
Thanks.

**Comment by phanirithvij** [comment]
Is your avatar going to change frequently?
If not, I suggest storing it as a file after getting it instead of using `Image.memory`.
And use the `Image.file(path)` which I believe would not be built again.
These might help [flutter cookbook](https://flutter.dev/docs/cookbook/persistence/reading-writing-files), [a plugin](https://github.com/renefloor/flutter_cache_manager)

**Comment by jiangyh1024** [comment]
thanks for your reply. I'll try it

**Comment by iapicca** [comment]
Hi @jiangyh1024 
This platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
