### ISSUE TITLE
I want my flutter app to launch automatically on delivery of fcm data message like whatsapp react to whatsapp call.

### ISSUE THREAD

**Issue by deensquare** [flutter/flutter#47660]

**Comment by janmoppel** [comment]
Hello @deensquare !

Thank you for posting.
As this is not an issue report, this question is more suitable for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too. Also, see other support options here: https://flutter.dev/community

Closing the issue here for now.
