### ISSUE TITLE
path_provider library uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by themisir** [flutter/flutter#47816]
## Steps to Reproduce

1. Create a new flutter project
2. Add `path_provider: ^1.5.1` dependency and install via `flutter pub get`
3. Run the app for android platform
4. "_.../PathProviderPlugin.java uses or overrides a deprecated API._" error message appears on Android Studio build output.

**Target Platform:** Android
**Target OS version/browser:** Android 9
**Devices:** Xiaomi Mi A1

## Logs

```
Launching lib\main.dart on Mi A1 in debug mode...
Running Gradle task 'assembleDebug'...
Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

```
No issues found! (ran in 37.6s)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\misir\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\misir\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\misir\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Mi A1 • 192.168.0.100:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by TheMisir** [comment]
Hm, fixed by itself after rebuilding again.

**Comment by answer0732** [comment]
same question,  rebuilding not working

**Comment by TheMisir** [comment]
Hm, I'm reopening the issue

**Comment by answer0732** [comment]
https://github.com/flutter/flutter/issues/47833#issue-542617775

**Comment by ejain** [comment]
Just noticed the same warning, after [migrating a project to AndroidX](https://flutter.dev/docs/development/androidx-migration).

> Note: C:\Users\...\AppData\Roaming\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by TheMisir** [comment]
Yeap @ejain the package needs to be upgraded to Android x too

**Comment by iKK001** [comment]
How do you upgrade the package to AndroidX ?
And if this can only be done by the package creator - how can you undo AndroidX in your Flutter project ?

**Comment by TheMisir** [comment]
I don't  suggest undoing Android X because standart app compat libraries
will no longer receive updates. I just ignore the warnings for now. Because
it just works. I suggest be patient and wait for team to upgrade package to
Android X (aka: Jetpack).

Could you upgrade yourself?

- Yes and no. Flutter is open source project, so everybody can contribute
to it. But it doesn't mean everyone's changes will be approved. So you'll
need to wait a bit to get your code approved / declined. Also the package
will not published instantly after update. It will take some time too.
Because a little bug may crash lots of apps.

--
Misir Jafarov

**Comment by TheMisir** [comment]
Take a look at the file: [build.gradle:41](https://github.com/flutter/plugins/blob/master/packages/path_provider/android/build.gradle#L41)

```java
// TODO(cyanglaz): Remove this hack once androidx.lifecycle is included on stable. https://github.com/flutter/flutter/issues/42348
```

I checked that the Jetpack Lifecycle package is currently on the stable version that you can [check out here](https://developer.android.com/jetpack/androidx/releases/lifecycle). I tried upgrading to AndroidX myself but I failed to set up a dev environment, lol. I have never worked on plugin projects before.

**Comment by oom-** [comment]
Same problem for me with version `path_provider: ^1.6.5`

**Comment by thiago-zaidem** [comment]
Same problem for me with version path_provider: ^1.6.5

**Comment by ib0o0** [comment]
Same problem for me with version `path_provider: ^1.6.5`

**Comment by TheMisir** [comment]
I have seen this issue also on other flutter packages by Google. Eg.: some firebase for flutter packages.

**Comment by JonatasCosta1983** [comment]
O meu está dando erro deprecated API firebase admob 0.9.3

**Comment by oom-** [comment]
> O meu está dando erro deprecated API firebase admob 0.9.3

moui bien

**Comment by preetshah21699** [comment]
Same issue here. Working with plugins becomes difficult due to such issues.

**Comment by AgiliApps** [comment]
**open** 

FLUTTER_PATH/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java

**replace FLUTTER_PATH with flutter path**

**then replac**

`binding.getFlutterEngine().getDartExecutor()`

**with**

`binding.getBinaryMessenger(),`

**Comment by bawantha** [comment]
same

**Comment by bawantha** [comment]
any working version to use

**Comment by AgiliApps** [comment]
**Android : 9
flutter:1.12.13+hotfix.9
path_provider : 1.6.5**

if not working, add below code to android/build.gradle to explain issue

```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}
```

**Comment by YassineChe** [comment]
Hello,

Some API's are deprected on latest version of some packages.
You need guys to upgrade the minSdkVersion.
If you are using path_provider-1.6.5 on your flutter project to avoid this issue upgrate `minSdkVersion` to **21**  in your `build.gradle` inside `app/ build.gradle`.

Good luck.

**Comment by Miyo-Excellent** [comment]
**### Friends should just install the package like this:**

name: TEST
description: A new Flutter project.
version: 1.0.0 + 1
environment:
   sdk: "> = 2.1.0 <3.0.0"

**dependencies:**
   flutter:
     sdk: flutter
   cupertino_icons: ^ 0.1.2
   image:
   introduction_screen: ^ 1.0.8
   grouped_buttons: ^ 1.0.4
   rxdart: ^ 0.23.1
   sqflite: ^ 1.3.0
   **path_provider:**

dev_dependencies:
   flutter_test:
     sdk: flutter
   flutter_launcher_icons: ^ 0.7.4

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets / icon / icon.png"
   adaptive_icon_background: "# 000000"
   adaptive_icon_foreground: "assets / icon / icon.png"

**Comment by blackcrabb** [comment]
Launching lib\main.dart on vivo 1951 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\Users\Dark Deathscyther\Downloads\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       269.1s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        10.3s
D/FlutterActivity(16775): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(16775): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(16775): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(16775): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(16775): Detaching from a FlutterEngine: null
D/FlutterView(16775): Not attached to an engine. Doing nothing.
D/FlutterView(16775): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8c5218b
D/FlutterActivityAndFragmentDelegate(16775): Executing Dart entrypoint: main, and sending initial route: /
I/flutter (16775): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16775): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (16775): The method 'update' was called on null.
I/flutter (16775): Receiver: null
I/flutter (16775): Tried calling: update(0.0)
I/flutter (16775): 
I/flutter (16775): When the exception was thrown, this was the stack:
I/flutter (16775): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (16775): #1      GameController.update (package:the_seeker/game_controller.dart:71:18)
I/flutter (16775): #2      GameRenderBox._update (package:flame/game/game.dart:388:10)
I/flutter (16775): #3      GameRenderBox._tick (package:flame/game/game.dart:381:5)
I/flutter (16775): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (16775): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1017:11)
I/flutter (16775): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (16775): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1015:17)
I/flutter (16775): #8      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:846:7)
I/flutter (16775): #17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (16775): #18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (16775): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (16775): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (16775):
I/flutter (16775):
I/flutter (16775): This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
I/flutter (16775): #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:116:33)
I/flutter (16775): #1      new _FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:119:6)
I/flutter (16775): #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:518:49)
I/flutter (16775): #3      GameRenderBox._scheduleTick (package:flame/game/game.dart:369:50)
I/flutter (16775): #4      GameRenderBox.attach (package:flame/game/game.dart:356:5)
I/flutter (16775): #5      RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2912:14)
I/flutter (16775): #6      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
I/flutter (16775): #7      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1238:11)
I/flutter (16775): #8      RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2905:7)
I/flutter (16775): #9      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5460:18)
I/flutter (16775): #10     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5295:35)
I/flutter (16775): #11     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5058:5)
I/flutter (16775): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16775): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16775): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (16775): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16775): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (16775): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16775): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16775): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (16775): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16775): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (16775): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16775): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16775): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (16775): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16775): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (16775): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16775): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16775): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (16775): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (16775): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16775): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16775): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16775): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (16775): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16775): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16775): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (16775): #54     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (16775): #55     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (16775): #56     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17) 
I/flutter (16775): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (16775): #58     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (16775): #59     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (16775): #60     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (16775): #69     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (16775): #70     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (16775): #71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (16775): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (16775): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device vivo 1951...                                    
I/OpenGLRenderer(16775): Initialized EGL, version 1.4
D/OpenGLRenderer(16775): Swap behavior 2
D/FlutterView(16775): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8c5218b
D/FlutterView(16775): Already attached to this engine. Doing nothing.
E/flutter (16775): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
E/flutter (16775): The hitTest() method was called on this RenderBox: RenderSemanticsGestureHandler#49e9a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
E/flutter (16775):   creator: _GestureSemantics ← RawGestureDetector ← GestureDetector ← [root]
E/flutter (16775):   parentData: <none>
E/flutter (16775):   constraints: MISSING
E/flutter (16775):   size: MISSING
E/flutter (16775):   gestures: <none>
E/flutter (16775): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
E/flutter (16775): If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter (16775): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:2102:11)  
E/flutter (16775): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2133:6)
E/flutter (16775): #2      RenderView.hitTest (package:flutter/src/rendering/view.dart:187:13)
E/flutter (16775): #3      RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:370:16)
E/flutter (16775): #4      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:128:7)    
E/flutter (16775): #5      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16775): #6      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16775): #7      _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (16775): #8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (16775): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (16775): #10     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (16775): #11     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (16775):
E/flutter (16775): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
E/flutter (16775): The hitTest() method was called on this RenderBox: RenderSemanticsGestureHandler#49e9a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
E/flutter (16775):   creator: _GestureSemantics ← RawGestureDetector ← GestureDetector ← [root]
E/flutter (16775):   parentData: <none>
E/flutter (16775):   constraints: MISSING
E/flutter (16775):   size: MISSING
E/flutter (16775):   gestures: <none>
E/flutter (16775): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
E/flutter (16775): If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).



i just get a black screen and when i click on this the all of these E/flutter (16775):  arises

**Comment by YassineChe** [comment]
Hello @blackcrabb ,

Please provide us, your dependencies.

Thank you.

**Comment by YassineChe** [comment]
Hello @blackcrabb,

You forget to specify the version of path provider,
put this line `path_provider: ^1.6.5` instead of `path_provider:`

Thank you.

**Comment by blackcrabb** [comment]
Hello @YassineChe 

Still not working

**Comment by YassineChe** [comment]
Ohh, by reading your ouput carefully it seems this error has no relation with path provider,
seems to me it an error logical, by trying to rendering something.. Its hard to know what's it specifically without part of code,
Please proivde us the code that causes this issue , or contact me on my email to figure it out together.
Good luck.

**Comment by aman4411** [comment]
> path_provider:

It worked for me. 
Thanks

**Comment by relativityboy** [comment]
When building with Android studio, path_provider `1.6.5`

```
Note: /Users/<redacted>/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
```

**Comment by YassineChe** [comment]
@relativityboy 

This is just a Note (warning) your code compiled successfully,
To avoid this note upgrade you minSdkVersion (Follow my first comment on this issue).

**Comment by flutterq2** [comment]
All Possible working solution here [[Solved] FlutterFirebaseCorePlugin.java uses or overrides a deprecated API](https://fluttercorner.com/solved-flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api/)

**Comment by stuartmorgan** [comment]
Closing as obsolete; we're compiling with warnings as errors in CI now.
