### ISSUE TITLE
Regression in flutter_test_performance

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47839]
It seems to be consistently hovering slightly over the baseline for `interface_change_elapsed_time_ms` since 21 Dec 2019. 

An [older issue](https://github.com/flutter/flutter/issues/37203) for the same benchmark seems to still be open. Should we move discussion here, or keep that one open?

**Comment by franciscojma86** [comment]
Seems like this is a different issue from https://github.com/flutter/flutter/issues/37203. Will continue investigation here.

**Comment by DaveShuckerow** [comment]
This is blocking a g3 roll.

**Comment by franciscojma86** [comment]
I ran this benchmark locally and I do see the increase over time. It would be really hard to find a single culprit, given that the increases are so subtle. However, I don't think this should block the roll since the latests commits are just barely above the baseline (less than 3 ms over). 

It is safe to re-baseline and investigate if it increases any further.
