### ISSUE TITLE
[Google_Maps_Flutter] | I can't  show & hide traffic using code during use the app

### ISSUE THREAD

**Issue by almodoen** [flutter/flutter#47895]
My only solutions for this problem is:
1. hiding the map Widget and then show it again to change the state (by changing a variable value , and let the map listen for the current value)
2. create two maps widgets one with trafficEnabled=false and the second with trafficEnabled=true .. and request one of them every time i click a button (because it doesn't work without clicking a button !)..

this is very bad thing and when i try the two option i get this error (always):
[https://github.com/flutter/flutter/issues/45695](url)

we want it to be simple .. we need the map widget options listen to a bool var if its true then trafficEnabled=true , and show the traffic , else hide the traffic .. , thats all ..

and why it doesn't work on android 4.4.4 and smallers for example  ?

please fix these problems, i am working on an application will change the world , and your plugin stops in front of me :laughing:

**Comment by iapicca** [comment]
Hi @almodoen 

For the implementation of the specific behaviour you described,
keep in mind that this platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this,
you may also get some help if you post it on Stack Overflow.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you


I want to thank you for bringing to my attention the issue you linked 
that I'm going to reopen, since appears to affect many user,
please follow up on that issue.
