### ISSUE TITLE
Flutter apps flash when brought back up on Android

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#47903]
Steps to reproduce:

0. On an Android device, close all applications, and (for recent versions of Android) enable "3-button navigation" under "System navigation" in the settings.
1. `flutter create dummy_splash`
2. `cd dummy_splash`
3. `flutter run` onto the Android device 
4. Double-tap the square button that switches applications.

Expected results (seen with v1.0.0): the application shrinks then expands, as it flows smoothly into and out of the recent applications list.

Actual results (seen with v1.13.6-pre.38 on multiple devices): the application flickers briefly when it reexpands from the recent applications list.

cc @matthew-carroll @xster

**Comment by Hixie** [comment]
I believe (without much evidence) that this is an embedding v2 regression.

**Comment by Hixie** [comment]
Looks like what is going on is that the launch theme is briefly visible when the app is restored for some reason. This was not the case previously.

I tried using the "NormalTheme" logic described [in the add-to-app documentation](https://flutter.dev/docs/development/add-to-app/android/add-splash-screen), but that made things worse because now the splash screen gets hidden too early and instead you see a blank screen for a while on startup, and it still doesn't fix the flashing issue when returning to the app.

Since this seems to affect new apps on all devices, upgrading to critical.

**Comment by peerwaya** [comment]
I am actually using this on v2 embedding and I can confirm this issue happens. it shows the splash briefly when the app is minimized.

**Comment by xster** [comment]
I'm on `v1.13.7-pre.41`, but I wasn't able to reproduce it on Pixel 3 and Galaxy S10

https://streamable.com/8wj1o
https://streamable.com/u5fh9

Anything else involved in the repro?

**Comment by xster** [comment]
Wonder if it's the same as this issue https://github.com/flutter/flutter/issues/27449

**Comment by matthew-carroll** [comment]
@xster WRT to your repro attempts, what happens if you single tap the switcher instead of double tapping? I think if you single tap, see the apps in the switcher, and then tap on your Flutter app to bring it back, you'll see the issue.

I'm about to look into this. I believe I have a repro. My guess is that this issue is multi-faceted. First, there may be some timing details with regard to the launch theme and normal theme that I wasn't aware of when working on the splash behavior. Second, there may be an issue with when and how Android snapshots the UI and when it gives control back to the app. The second issue may have been prevented in v1 by not cleaning up the connection between Flutter and its Activity, but my guess is that even in that case if a user waited until Android cleaned up memory then this problem would still exist when returning to the app.

My plan is to create a normal Android app with a launch screen, map out the different interactions that I can see, and then apply that information to the embedding and hopefully resolve this issue.

**Comment by matthew-carroll** [comment]
The root cause of this issue the combination of Android lifecycle methods and Flutter's asynchronous rendering. The soonest that we can attempt to render a frame upon switching back to a Flutter app is in `onStart()`. However, it appears like the time it takes to paint the `Surface`'s pixels is long enough to momentarily display nothing.

I think on iOS this problem was solved by blocking the UI thread until Flutter's first frame is rendered. I don't think that we can do this same thing on Android because all JNI calls must be sent from the Main/UI thread. If we block the UI thread then Flutter JNI can never invoke the callback that tells us the first frame is rendered. Thus the app freezes indefinitely.

The only approach that I can think of is to generate a bitmap of Flutter's UI the moment that `FlutterActivity` hits `onPause()`. This bitmap will be held in memory as long as the app remains in memory. Upon switching back to the app, in `onStart()` we can immediately display this bitmap, giving the impression of a Fluter UI, and then hide that bitmap when Flutter finally renders its 1st frame.

@Hixie what do you think about this proposed solution?

**Comment by matthew-carroll** [comment]
CC @jason-simmons for any other thoughts on the approach, and CC @gaaclarke for visibility into iOS/Android differences here.

**Comment by Hixie** [comment]
Can't we just not unregister engine?

**Comment by matthew-carroll** [comment]
@Hixie I tried that initially. It did reduce the length of the flash, but for some reason it didn't completely remove the flash. I'm not sure why, but some questions that come to mind are:

 * Does a Surface retain its last rendered frame when the app goes to the background?
 * Does a Surface automatically request a redraw when returning from the background?
 * Does Flutter clear its Surface at the beginning of processing a new frame, and thereby cause a blank Surface until rendered?

Or maybe it's something else entirely.

When I implemented the bitmap approach, I do believe the flash disappeared entirely. But a couple tradeoffs include:

 * addition of bitmap rendering time when backgrounding (I didn't notice any obvious regressions in the emulator)
 * the possibility that the content of Flutter's 1st frame upon return is significantly different than the last frame when backgrounded, thus leading to a visual jump from one to the other

**Comment by Hixie** [comment]
We used to not have this problem -- we would intentionally prerender images when the screen was not visible (e.g. because you rotated), and there was no flash.

**Comment by matthew-carroll** [comment]
@Hixie I just created a project using the old embedding and I'm still getting the same slight, occasional flicker in the app switcher that I'm seeing with the new embedding. To be clear, the flicker in the new embedding that I'm talking about is the improved flicker from re-ordering initialization calls. But I think that the problem I'm seeing now in the new embedding actually does exist in the old embedding. I'm running on a Pixel device for this comparison.

You mentioned "we would intentionally prerender images when the screen was not visible" - can you elaborate on that? I'm not sure I'm familiar with that behavior.

**Comment by Hixie** [comment]
We looked at this together. The flicker was present in v1.0.0 too, just more subtle. Other apps don't have it, though.

**Comment by howieweiner** [comment]
Hi

I'm not sure if this is a separate issue or part of this one. I have just update my app and it has been released for test (production build). I am seeing an issue on Android 9 (Moto G6) when the app is minimised. There is a very noticeable flicker. I have recorded it and slowed it down and it is a black bar scanning down the screen. It happens consistently, and only on minimising.

![flitter-flutter-scan](https://user-images.githubusercontent.com/955237/81739237-e1a45200-9492-11ea-9866-71c5c01d82f1.png)

I have a [video](https://drive.google.com/open?id=1moerA66WA12ZNlOQLEeZm9Bks1ZZzEie) of this issue.

I have upgraded to Flutter v1.17 for this release and added a background image in this release. I can't think of anything else that might have caused this change.

I don't see this issue on Android 10 in a virtual device, nor on a physical device running (cough) Android 6, nor on an iOS device. I can't recreate it on Android 9 using a virtual device.
