### ISSUE TITLE
flutter doctor: ArgumentError: Invalid argument(s): Cannot find executable for where.

### ISSUE THREAD

**Issue by general08** [flutter/flutter#47969]
[flutter_01.log](https://github.com/flutter/flutter/files/4008915/flutter_01.log)

## Steps to Reproduce

1. ...i first download and extract flutter sdk from flutter.io to C:/flutter
2. ...i add the bin directory to the path (C:/flutter/flutter/bin)
3. ...i run flutter doctor in my command prompt and send me the message attached below
4. ...and i want to used Vs code instead of android studio

## Logs

```
```

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):

Sending crash report to Google.
Crash report sent (report ID: 0262a663b8e95aea)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\HP PC\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```
```

**Comment by jonahwilliams** [comment]
The actual error message is:

```
ArgumentError: Invalid argument(s): Cannot find executable for where.
```

Which terminal are you running this in? Does `where` exist?

**Comment by general08** [comment]
I'm using Git Bash or run the command in command pilates on my vs code terminal 

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 30, 2019 at 7:49 AM, Jonah Williams<notifications@github.com> wrote:   
The actual error message is:
ArgumentError: Invalid argument(s): Cannot find executable for where.

Which terminal are you running this in? Does where exist?

**Comment by jonahwilliams** [comment]
I do not believe flutter will work from git bash. See the https://flutter.dev/docs/get-started/install/windows#system-requirements for more information. Does it work normally if run from a newer powershell?

**Comment by general08** [comment]
I will start everything a fresh from from the guide you send And i wull contact you back

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 30, 2019 at 9:08 PM, Jonah Williams<notifications@github.com> wrote:   
I do not believe flutter will work from git bash. See the https://flutter.dev/docs/get-started/install/windows#system-requirements for more information. Does it work normally if run from a newer powershell?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by edSarti** [comment]
The same issue happened to me yesterday (2020 May, 21), after receiving a message on the "terminal / Android Studio" to perform a "flutter upgrade". After executing the command, the Flutter crashes completely. Incredibly, not even the "flutter doctor" worked anymore, which for me is kind of unacceptable.

I didn't know that the "flutter upgrade" did not consider the channel being worked on. Before the crash, I had the beta channel version (for Web dev) and the command updated to the latest version of the "stable channel". The link with Git has been broken.

I tried to find something like a "flutter unupgrade" to revert the update, but it seems that it doesn't exist (yet). I think it is important that an update can be reversed in these cases.

After literally hours of searching for this issue, my drastic solution was to REMOVE and REINSTALL THE FLUTTER COMPLETELY, from the beginning and redo the "flutter upgrade" on the beta channel. Operationally speaking, the problem was solved, but I think that Flutter people should "check the channel in use by the user, before even suggesting a" flutter upgrade ", and in doing so, do it on the right channel", at least until solve the problem really.

And, also, it is important that the "flutter doctor" is a completely segregated process and that it does not crash together with the Flutter. As it is, it doesn't make sense to me.

Trying to contribute, thank you!

**Comment by jmagman** [comment]
@edSarti The originator was using `git bash`.  If you see a crash again, please file a new issue with the details of your exact crash and completely fill out the template so we can take a look.

> I tried to find something like a "flutter unupgrade" to revert the update, but it seems that it doesn't exist (yet). I think it is important that an update can be reversed in these cases.

It's `flutter downgrade`.
