### ISSUE TITLE
[flutter_test] Update packages

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#47994]
Got this:

Because every version of flutter_test from sdk depends on image 2.1.4 and therapist_training depends on image ^2.1.10, flutter_test from sdk is forbidden.
So, because therapist_training depends on flutter_test any from sdk, version solving failed.

Not sure if there's a better way of dealing with this. I'm including 

  image: ^2.1.10

I switched it to 
  image: ^2.1.4

to get it working.

**Comment by jonahwilliams** [comment]
The latest version of flutter has since been updated to use the latest image: https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml#L20

If you want to use different dependencies locally, you can always use a dependency override: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by sgehrman** [comment]
I'm still having this problem.  The latest image is 2.1.11, not 2.1.4
