### ISSUE TITLE
[proposal] [triage] separate plugins issues like FirebaseExtended

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#48021]
I propose to change the first party plugins' issues allocation
consistently with the reorganization of  `FirebaseExtended` flutter plugins
which has transferred [flutterfire](https://github.com/FirebaseExtended/flutterfire)'s issues
from the [flutter/flutter/issues](https://github.com/flutter/flutter/issues) to the [FirebaseExtended/flutterfire/issues](https://github.com/FirebaseExtended/flutterfire/issues),

**prosal**

-  create an `issue tab` in [flutter/plugins](https://github.com/flutter/plugins)

- transfer first party plugins' related issues from [flutter/flutter/issues](https://github.com/flutter/flutter/issues) 
to the newly created **_flutter/plugins/issue_**.

**advantages**

- at the moment of writing https://github.com/flutter/flutter/issues 
contains **> 8000 open issues**
this is on one hand a signal of the SDK popularity,
but due to the presence of a big number of issue addressing _first party plugins_
provides a misleading representation of the health of the SDK;
separating the issues addressing the SDK from the issue addressing the plugins
would provide a more reliable and truthful portrait of the situation

- triaging issues addressing SDK and plugins separately
would make easier to spot and label regressions, critical bugs and duplicates

thank you for reading

**Comment by stuartmorgan** [comment]
> provides a misleading representation of the health of the SDK

Number of open issues is not, and never will be, a good metric for the health of a project or SDK. It's a function of popularity, size, and triage philosophy. As long as Flutter's triage philosophy explicitly favors leaving bugs open (see [here](https://github.com/flutter/flutter/wiki/Issue-hygiene#issue-philosophy), [here](https://github.com/flutter/flutter/wiki/Issue-hygiene#goals-stretch-goals-future), and [here](https://github.com/flutter/flutter/wiki/Issue-hygiene#file-bugs-for-everything)), the number of open issues will be large and ever-increasing.

People who conflate triage philosophy with project health (e.g., comparing Flutter to other projects who have a policy of closing all issues they don't intend to fix in the foreseeable future) are always going to draw the wrong conclusion. Reducing (temporarily) the open issue count from 8,000 to 6,800 isn't going to change anyone's mind.

> triaging issues addressing SDK and plugins separately would make easier to spot and label regressions, critical bugs and duplicates

A substantial disadvantage, which IIRC is a primary driver for the current arrangement, is that people routinely file bugs in the wrong places, and moving bugs between projects requires a very high level of permission (project owner, I believe). So it could well become harder to find and manage duplicates, rather than easier.

**Comment by stuartmorgan** [comment]
Given the number of bugs I've encountered that are incorrectly triaged as plugin bugs, I'm confident that this would not actually make triage easier.

**Comment by iapicca** [comment]
> Given the number of bugs I've encountered that are incorrectly triaged as plugin bugs, I'm confident that this would not actually make triage easier.

make sense
