### ISSUE TITLE
mySQL1 package connection error

### ISSUE THREAD

**Issue by bengalliboy** [flutter/flutter#48086]
I have been getting this below error while I try to use mySQL1 package to directly talk to the database using flutter.
```bash
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 57351
```
Not sure why it is trying to use a different prot and not the one I am asking to use.....

Thanks!
Here is my code:
```dart
import 'package:mysql1/mysql1.dart';

void mySQLConnect () async{
  final conn = await MySqlConnection.connect(new ConnectionSettings(
      host: 'localhost', port: 3306, user: 'xxxx', db: 'xxxx', password: xxxx' ));
  var results = await conn
      .query('select * from users');
  for (var row in results) {
    print('UserName: ${row[0]}, Name: ${row[1]}');
  }
  await conn.close();
}

```

**Comment by iapicca** [comment]
Hi @bengalliboy 
since [mysql1](https://pub.dev/packages/mysql1) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/adamlofts/mysql1_dart/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
