### ISSUE TITLE
onActivityResult called twice in Plugin class.

### ISSUE THREAD

**Issue by MangeshKadam** [flutter/flutter#48202]
I am creating plugin to retrieve Phone Number and implementation is based on this [Phone Retriever](https://github.com/googlearchive/android-credentials/blob/master/sms-verification/android/app/src/main/java/com/google/samples/smartlock/sms_verify/ui/PhoneNumberActivity.java). My code for showing hint picker is `fragmentActivity.startIntentSenderForResult(intent.getIntentSender(), RC_HINT, null, 0, 0, 0);` and implemented **PluginRegistry.ActivityResultListener** in my PhoneRetrieverPlugin class. I am getting **onActivityResult** call twice. Below is code for onActivityResult
```
 @Override
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == RC_HINT) {
            if (resultCode == Activity.RESULT_OK) {
                Credential cred = data.getParcelableExtra(Credential.EXTRA_KEY);
                Log.d(TAG, cred.getId());
                result.success(cred.getId());
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
```
where result is initialized in onMethodCall.  As this method is called twice, result is found to be null in second call.  How to avoid this method call twice?

**Comment by iapicca** [comment]
Hi @MangeshKadam 
can you please provide your `flutter doctor -v` 
and  a **reproducible** minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by MangeshKadam** [comment]
@iapicca https://github.com/flutter/flutter/issues/48239 this is exact same code having above issue. I am getting result variable null in second onActivityResult call

**Comment by kinex** [comment]
I can reproduce the same issue with my plugin https://github.com/kineapps/flutter_file_dialog if I make small changes to example app's MainActivity.kt

This code works (current code in repo):

```kotlin
// OPTION A
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity()
```

With this code the `onActivityResult `gets called twice (causing the issue https://github.com/kineapps/flutter_file_dialog/issues/1 in my plugin):
```kotlin
// OPTION B
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```
The problem is that instructions here [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects ) tell to use the OPTION B (which does not wok). You will get the same code with `flutter create` (Flutter 1.12.13+hotfix.8).

But instructions here [Supporting the new Android plugins APIs](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration) tell you to use the OPTION A which does not cause the issue. But it is unclear if this OPTION A is safe to use in an app where I have tens of plugins some of which probably not migrated to V2 yet.

So in my opinion those two referenced documents give conflicting and/or confusing instructions. I don't know now how this should be implemented. Documents should cover also the case that an app depends on both V1 and V2 plugins which is probably the most common scenario currently.

**Comment by kinex** [comment]
The actual reason for this issue at least in my case is that `ActivityAware.onAttachedToActivity` is called twice (plugin instance is created twice?) on app startup with OPTION B. `ActivityAware.onDetachedFromActivity `is not called inbetween as you could expect. Not sure if this is a known feature, Flutter issue or an issue in my plugin. Anyway, it seems to be a mistake to perform initialization like `addActivityResultListener `in the `ActivityAware.onAttachedToActivity` because it will cause double registration for a listener. I refactored my plugin to prevent this by only saving the binding reference in `ActivityAware.onAttachedToActivity` and perform the actual initialization later in `onMethodCall`.

**Comment by matpag** [comment]
I can confirm this bug, just create a new project with `flutter create` with version 1.12.13+hotfix.8
and the bug is already there simply implementing `PluginRegistry.ActivityResultListener` and `onActivityResult(..)`

Proposed workaround by @kinex is working, simply commenting those lines:
```
class MainActivity: FlutterActivity() {
//    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
//        GeneratedPluginRegistrant.registerWith(flutterEngine);
//    }
}
```
Is this safe to do or can we expect more bugs without registering the engine here?

**Comment by TahaTesser** [comment]
Hi @MangeshKadam 
Can't reproduce this issue on the latest `master channel the issue even with `configureFlutterEngine` 
`MainAcitivty` doesn't need `configureFlutterEngine` anymore in V2 Embedding, 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.64, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.64 at /Users/tahatesser/Code/flutter_master
    • Framework revision 4d4d017aa5 (6 hours ago), 2020-12-03 21:38:10 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!
```

</details>
