### ISSUE TITLE
BackdropFilter inside ShaderMask stop working after https://github.com/flutter/engine/pull/6264

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#48212]
Using BackdropFilter inside ShaderMask stop working as stated here https://github.com/flutter/flutter/issues/20859#issuecomment-422435416

A simple  demo app

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: MyApp(),
      ),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Stack(
            alignment: Alignment.bottomCenter,
            fit: StackFit.expand,
            children: <Widget>[
              Container(
                child: Image.network('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQlXYdeEKhFq34sh8-0ZKC1uqCcVGgOzdW_ZRAqCBkWxG-oeCB1',
                fit: BoxFit.cover,
                    alignment: Alignment.bottomCenter),
              ),
              Positioned(
                top: 400,
                bottom: 0,
                left: 0,
                right: 0,
                child: ClipRect(
                  child: ShaderMask(
                  shaderCallback: (rect) {
                    return LinearGradient(
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter,
                      colors: [Colors.transparent, Colors.black],
                    ).createShader(Rect.fromLTRB(0, 0, rect.width, rect.height));
                  },
                  blendMode: BlendMode.dstIn,
                  child:  BackdropFilter(
                  filter: ImageFilter.blur(sigmaX: 2, sigmaY: 10),
                  child: Container(
                    color: Colors.black.withOpacity(1),
                ),
              ),

                ),
              ),)
            ]
        ),
      ),
    );
  }
}```

**Comment by liyuqian** [comment]
I remember that @flar once commented something like the following in another issue:

`BackdropFilter` can only apply the filter to the last Skia layer. Since `ShaderMask` creates a new layer, a `BackdropFilter` inside `ShaderMask` won't be able to blur the background in the previous layer.

Before https://github.com/flutter/engine/pull/6264, `ShaderMask` didn't properly creates its Skia layer. That's probably why `BackdropFilter` inside `ShaderMask` used to work.

**Comment by jamesblasco** [comment]
Thanks for the explanation @liyuqian
Would there be a way I could mask a BackdropFilter now?

**Comment by liyuqian** [comment]
Try using [ImageFiltered](https://master-api.flutter.dev/flutter/widgets/ImageFiltered-class.html) (only available in the master branch, not the stable branch) for the blur instead of `BackdropFilter`, and then wrap `ImageFiltered` with the `MaskFilter` (or wrap `MaskFilter` with `ImageFiltered` depending on what you want). @flar implemented the `ImageFiltered` so he should be able to provide you more help. Your use case could also be a good example to put in the API doc of `ImageFiltered`.

**Comment by jamesblasco** [comment]
Perfect! I will play with it and let you now 👍👍

**Comment by jamesblasco** [comment]
So it works perfectly! 


<details>
  <summary>Example code</summary>

 ```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: MyApp(),
      ),
    ),
  );
}

class MyApp extends StatelessWidget {
  final image  = 'https://images.unsplash.com/photo-1535892449425-d45bdcb2d016?ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80';

  @override
  Widget build(BuildContext context) {
   return Transform.scale(
    scale: 1.2,
     child: Stack(
        alignment: Alignment.bottomCenter,
        fit: StackFit.expand,
        children: <Widget>[
         Image.network(
                  image,
                  fit: BoxFit.cover,
                  alignment: Alignment.bottomCenter),
         /*  BackdropFilter(
               filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),*/
           ImageFiltered(
                    imageFilter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                    child: ShaderMask(
                      shaderCallback: (rect) {
                        return LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: [Colors.black, Colors.black.withOpacity(0)],
                            stops: [0.4, 0.75]).createShader(rect);
                      },
                      blendMode: BlendMode.dstOut,
                      child: Image.network(
                          image,
                          fit: BoxFit.cover,
                          alignment: Alignment.bottomCenter),
                    )
          ),
           Container(
              decoration: BoxDecoration(gradient:  LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: [Colors.black.withOpacity(0), Colors.black.withOpacity(0.6)],
                            stops: [0.3, 0.8]))
            )

        ]));
  }
}
```
</details>

The goal of using BackdropFilter with ShaderMask was to be able to apply it to the image without needed to modify it. 

With ImageFiltered and ShaderMask I blur the part I want of an image and then, I add the full image behind in a stack. (This method can also be achieved with using ShaderMask for the part I don't want to blur and blur the back image with an ImageFiltered or a BackdropFilter)

|  ImageFiltered |  BackdropFilter |
|---|---|
| <img width="397" alt="Captura de pantalla 2020-02-27 a las 21 37 43" src="https://user-images.githubusercontent.com/19904063/75484724-9a391a00-59a9-11ea-8916-a75b4c270cfc.png">  | <img width="395" alt="Captura de pantalla 2020-02-27 a las 21 38 10" src="https://user-images.githubusercontent.com/19904063/75484715-95746600-59a9-11ea-8d2e-f22a811159f8.png"> |

Thanks for the help. I think we can close it now

**Comment by flar** [comment]
That's a nice effect!

Just to be clear - the output shows an inversion of the blur between the two implementations. Was that an intentional change?

From the later comments it sounds like you like the new widget for the image test, but still have reservations about using it on a piece of a scene instead of an image?

We would appreciate if you could clarify with a comment that calls out explicitly what you feel is resolved about this issue and what you think remains unresolved.

**Comment by jamesblasco** [comment]
> Just to be clear - the output shows an inversion of the blur between the two implementations. Was that an intentional change?

@flar Yes it was an intentional effect, in the example code attached to it you can see two lines of code commented. In one I used the ImageFiltered so it blurs the child and the second I use BackdropFilter so it blurs the background behind the image with a mask.

> From the later comments it sounds like you like the new widget for the image test, but still have reservations about using it on a piece of a scene instead of an image?

My concern is that for doing something like this you need to have the same widget duplicated in a stack, one for the blurred layer and the other for the not blurred. With a simple image is okey, maybe for a complex widget (e.g. entire app) wouldn't make any sense.

It would me nice to be able to mask the filter and not just the image with the filter, so the filter applies to the image.

|Now| Proposal|
|---|---|
|<img width="410" alt="Captura de pantalla 2020-02-28 a las 8 56 09" src="https://user-images.githubusercontent.com/19904063/75521524-3eea4480-5a08-11ea-8bea-3a1dd8f34869.png">| <img width="333" alt="Captura de pantalla 2020-02-28 a las 8 57 09" src="https://user-images.githubusercontent.com/19904063/75521554-4f9aba80-5a08-11ea-96eb-b23dd1f261a2.png"> |

Also I think personally shouldn't be a priority but I would be happy to see it in the future.

**Comment by flar** [comment]
Thank you for your detailed explanation with very informative pictures. It seems like the proposed functionality is outside the scope of this issue and so we should close this issue?

**Comment by jamesblasco** [comment]
Sure 👍

**Comment by jascodes** [comment]
Any update on this?

**Comment by flar** [comment]
The update back in February was that the proposed behavior was outside the design scope of the widgets involved. Everything here is currently working as intended.

@jascodes Was there some other update you were looking for?

**Comment by jascodes** [comment]
https://user-images.githubusercontent.com/1231593/103069898-638e5900-45e6-11eb-9934-252bc86beb32.MP4

@flar Check out App bar I implemented. Blur sigma goes from tweened with curve and goes low to high. In this workaround I just positioned slices on stack with different blur. Right now Backdrop filter is not working inside shareder mask otherwise gradient would be ideal solution.

Thx

**Comment by flar** [comment]
We don't have a good way to have the BackdropFilter xray through all of the intervening layers to operate on the source behind a ShaderMask. Adding such a facility would make BackdropFilter even more heavyweight than it already is and potentially disrupt one of its use cases which is to blur a single widget behind it.

The workaround of having to list the image twice is much cheaper in the long run, especially if you switch to ImageFiltered instead of BackdropFilter to achieve the blur.

Another path forward to achieving some of these results would be to beef up the capabilities of ImageFiltered. Right now we have a small library of filters, but as of [this PR](https://github.com/flutter/engine/pull/20309) landed in November we can now chain ImageFilter objects and use ColorFilter objects in the chains. The above "image partially blurred" effect could be done by a chain of ImageFilter objects with a bit more work, something like:

```
source -> blur -> mask \
                        Blend(modulate)
                source /
```

We'd have to add a filter that could use a shader to mask the input (Skia supports this) and a filter that could blend the results of one sequence of filters with another sequence (one of those inputs would simply be left null to apply it to the original image) and then the above effect could be achieved with a single Widget - ImageFiltered.

Trying to achieve these results on the web backend would be the challenging part.
