### ISSUE TITLE
Regression in flutter_gallery_ios32__transition_perf worst_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#48248]
This benchmark went from being mostly green with some red spikes, to consistently red with some green runs. Should this be re-baselined? Maybe something change in the infra?  @jason-simmons  @liyuqian 

Not marking as a TODAY issue since this has been going on for a long time.

**Comment by liyuqian** [comment]
`flutter_gallery_ios__transition_perf 90th_percentile_frame_rasterizer_time_millis` also had a big regression from 3ms-17ms. It's not noticed because it's archived. @flar has already reproduced the regression with iPhone 6 (used by `flutter_gallery_ios__transition_perf`)  so we're already aware of that even though we probably haven't looked at the particular archived trace.

**Comment by liyuqian** [comment]
BTW, triage discussing is happening inside https://github.com/flutter/flutter/pull/43677

**Comment by flar** [comment]
The 90th percentile measurement may have had multiple reasons for regression. One is the introduction of a libzip dependency which regressed the worst frame rasterization by a lot, but it doesn't affect the 90th percentile results if you revert just that change. See the triage comments in https://github.com/flutter/flutter/pull/43677 for more information on that.

Another is potentially due to https://github.com/flutter/flutter/commit/d189b94bad7ee1adc9d676c6f36a4a07b5586e80 and while it regressed from ~3ms to ~16-17ms - that could be due to a different anomaly we are tracking which is that our iOS rasterizer thread can get stuck on vsync waits that make it appear that frames are taking 1 full frame to render even when the actual work is much less. It could mean there was a much smaller regression that somehow triggered the vsync wait condition, or it could just be a side effect of something else that really doesn't reflect on performance.

**Comment by christopherfujino** [comment]
![pr-benchmark](https://user-images.githubusercontent.com/7856010/75370614-3b28b780-587a-11ea-8f91-84fd1f11f089.png)
https://github.com/flutter/flutter/pull/50772 improved this benchmark from ~70ms to ~33ms (it looks like it's since regressed to ~50ms (maybe after https://github.com/flutter/flutter/pull/51418).

**Comment by liyuqian** [comment]
Thanks @christopherfujino ! I also confirmed that the worst_frame_rasterizer_time has recovered from the regression:

![image](https://user-images.githubusercontent.com/22987568/75374691-98743700-5881-11ea-961a-3f9f6899111f.png)

I'm going to open a new regression issue on https://github.com/flutter/flutter/pull/51418
