### ISSUE TITLE
Too much debug log verbosity from Android embedding

### ISSUE THREAD

**Issue by xster** [flutter/flutter#48275]
<img width="772" alt="Screen Shot 2020-01-06 at 5 30 28 PM" src="https://user-images.githubusercontent.com/156888/71861161-42b5b680-30aa-11ea-9744-49545fbbfe30.png">

We're adding a lot of extra logs for the default run case whereas we previously tended to use Log.v instead of Log.d at a quick inspection.

**Comment by matthew-carroll** [comment]
@xster @dnfield I kept this ticket on a list for me to go back and develop a comprehensive logging strategy that limits verbosity by default, but still allows us to log moments that are useful when debugging the Android embedding. I didn't get around to that so I'll just leave this ticket by saying that I think a lot of those nuanced logs can be useful, and have been useful in some debugging circumstances. Whatever the future of Android embedding logging, I would recommend not deleting a bunch of those logs because it's likely that other devs will have to continuously re-add them during debugging.
