### ISSUE TITLE
iOS Accessibility: On/Off labels

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4830]
Draws an extra graphic in switches, not sure if it does anything else.  Presumably very easy to add assuming there is a function to access this preference.

![img_0021](https://cloud.githubusercontent.com/assets/11857803/16636193/73428e5a-438b-11e6-8f0f-ff9e953358a7.PNG)

**Comment by brandondiamond** [comment]
Looks like a fun issue to tackle :) I'll take a look this week.

I did some testing in the simulator and it seems that the on/off labels are purely graphical -- they seem to be unaffected by language / text size changes. Unless someone finds a case I missed, I'll implement these by adding a bit of simple drawing.

Should I also look into (say) extending MediaQueryData to include a bool indicating whether (say) labeledSwitches/onOffLabeledSwitches are enabled? Is there a better place to put this since this is a cupertino-centric change? Maybe keep it simple and add an optional parameter?

Last, who is a good point of contact for obtaining this data from iOS on the platform side? It looks like this setting is exposed here:

https://developer.apple.com/documentation/uikit/uiaccessibility/3131973-isonoffswitchlabelsenabled

**Comment by jonahwilliams** [comment]
Feel free to reach out to me or @goderbauer if you have questions on accessibility, and @HansMuller for the implementation of the labels themselves.

Placing the value on the media query sounds reasonable, and you can populate it via the existing engine accessibility code. See https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L912. that will also require a corresponding change in dart:ui

My recommendation would be to start with the design of the labels themselves in a PR. Plumbing of the value on the media query would be fairly mechanical

**Comment by brandondiamond** [comment]
Thanks! That's super helpful. Do you think it would be reasonable to build this in ~3 PRs? One building the UI, one adding support for the flag in the platform, and one connecting the two in the framework?

**Comment by jonahwilliams** [comment]
That sounds reasonable. For engine PR's, you'll need to wait a few hours (max) for the change to roll into the framework. You could work on the label design and adding the flag to the dart:ui window (https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L1236) independent of the engine roll. You would only need to wait for the engine roll to connect the window to the media query

**Comment by brandondiamond** [comment]
I've got the first part of the fix pretty close to finished -- I've been thinking it might be easiest to update MediaQueryData to have a stub field (that's always false for now) so that CupertinoSwitch can be "complete" in the first PR. This would also make testing easier (I'd just have the field return true to trigger the label path).

Does this sound like a reasonable approach?

**Comment by brandondiamond** [comment]
![cupertinoSwitchMetrics](https://user-images.githubusercontent.com/1036976/64366221-c15af400-cfe3-11e9-95bf-9a915d9df131.png)

Here's my reference for label positioning / painting.

**Comment by HansMuller** [comment]
I think it would be best if we interested a new InheritedWidget in the cupertino library, rather than extending MediaQuery et al.  Most of the features exposed by MediaQuery more or less cross-platform. This  "on/off labels flag" is specific to iOS and there are more flags like it. Instead of extending MediaQuery you could create a similar widget in the cupertino library called, say, CupertinoSystemSettings.

**Comment by brandondiamond** [comment]
Just confirmed that the accessibility labels have the same color regardless of whether dark/light mode is active (on iOS13.1).

![darkLightSwitchLabels](https://user-images.githubusercontent.com/1036976/65633388-fe465500-dfa9-11e9-830c-3108c5ad8c43.png)

**Comment by Hixie** [comment]
Sounds like this is fixed!
