### ISSUE TITLE
Expose "3D Touch" handlers in GestureDetector

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4838]
iOS has a "3D touch" feature. We could allow developers to respond to a 3D touch from within a Flutter app.

**Comment by eseidelGoogle** [comment]
FYI @rock3r

**Comment by chinmaygarde** [comment]
The [`pressure`](https://docs.flutter.io/flutter/dart-ui/PointerData/pressure.html) property on [`PointerData`](https://docs.flutter.io/flutter/dart-ui/PointerData-class.html) is wired up in the engine on iOS/Android. I don't think the framework makes use of this in higher layers of the stack.

**Comment by xster** [comment]
The original FR title was a bit too generic. Changed it to a more specific task of adding the responder to the gesture detector in this issue. 

Let specific usages of it be in other specific bugs like https://github.com/flutter/flutter/issues/17030 since native versions of https://flutter.io/widgets/cupertino/ generally don't respond to 3d touch.

**Comment by dark-chocolate** [comment]
@eseidel Does flutter also support 3D touch shortcuts in iOS when you hard press the app icon? And also in Android, when we long press app icon (on devices running Android 7.0 and higher), they show app shortcuts. 

So, does flutter provide support for both platforms?

**Comment by xster** [comment]
No, quick actions would be an orthogonal issue (currently fulfilled by a package https://github.com/flutter/plugins/tree/master/packages/quick_actions)

**Comment by dark-chocolate** [comment]
@xster Thank you so much, I didn't know the plugin. Really appreciate your help :)
