### ISSUE TITLE
[google_sign_in] version solving failed for Flutter SDK version 1.5.4-hotfix.2

### ISSUE THREAD

**Issue by CheshtaK** [flutter/flutter#48424]
**The bug**
Using google_sign_in: ^4.1.1 throws the following error for Flutter SDK version 1.5.4-hotfix.2

![bug](https://user-images.githubusercontent.com/32400008/72001393-670cc100-326b-11ea-8106-fb3a13aa493f.jpg)

Here is a screenshot of my version and environment sdk

![bug2](https://user-images.githubusercontent.com/32400008/72000095-92da7780-3268-11ea-982f-64b4936e3189.jpg)

**To Reproduce**
1. Use Flutter sdk: ">=2.1.0 <3.0.0"
2. Add google_sign_in: ^4.1.1 to pubspec.yaml and run pub get

**Expected behavior**
google_sign_in should be made compatible with newer Flutter SDK versions

**Comment by VladyslavBondarenko** [comment]
Hi @CheshtaK 
Try to update your Flutter SDK (current stable version is v1.12.13+hotfix.5)
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
Closing this issue, since it's clear from your logs that `google_sign_in: ^4.1.1` requires `Flutter SDK version >=1.10.0` while you have `1.5.4-hotfix.2`
If you disagree please write in the comments and I will reopen it.
Thank you
