### ISSUE TITLE
Android FlutterTextureView doesn't release the Surface instance created by itself.

### ISSUE THREAD

**Issue by QingYun** [flutter/flutter#48535]
We noticed that in a hybrid App with multiple Flutter views attached to the same Flutter engine rendering under the texture mode, there is a resource leaking issue caused by the [Surface instance created by a FlutterTextureView](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterTextureView.java#L175) not being released on dispose. We believe simply calling `surface.release()` right after its creation can solve this bug.

**Comment by matthew-carroll** [comment]
@QingYun can you provide minimal repro steps to set up an Android app that demonstrates the leak? I'd like to confirm directly that the suggested solution prevents the leaks.

**Comment by matthew-carroll** [comment]
Update on the problem statement after some internal discussion:

There are a few issues that need to be investigated, and possibly corrected with relation to this ticket.

**Leak in back-to-back Flutter experiences**
First, the specific situation reported that should cause the leak is:

1. Display a FlutterFragment, fragA, with a cached `FlutterEngine`, engineA
2. Detach fragA
3. Immediately attach a new FlutterFragment, fragB, using the same cached engineA

Technically, this back-to-back Flutter experience with the same `FlutterEngine` is unsupported at the moment. Because a single `FlutterEngine` can render to only 1 `Surface` at a time, any use-cases that use the same `FlutterEngine` back-to-back could suffer from unpredictable visual artifacts or other race conditions. However, even in this unsupported case, there should not be a leak and we should fix it.

**Crash when re-attaching FlutterFragment**
The OP also described an attempt to re-use the same `FlutterFragment` by detaching it at one point and then re-attaching it at another. The OP said that attempt causes a crash. We need to attempt to repro this and fix the crash if it exists.

**Back-to-back Flutter experiences with a Redux store**
There is one final challenge that goes beyond the scope of this ticket, but I'm capturing it here for future reference. The OP has a situation where a `FlutterFragment` needs to launch a `FlutterActivity`. This is a standard back-to-back use-case, which currently officially requires 2 `FlutterEngine`s.

The challenge is that the OP has a Redux store in `engineA`. If a second `engineB` is introduced then that `FlutterEngine` will not have the Redux store. The only current solution to this problem that I can think of is to introduce a 3rd `FlutterEngine` dedicated to running the Redux store and then using isolate ports to communicate with the UI engines. This is a situation that I predicted might come up about a year ago, so we should log this customer requirement. CC @xster @mehmetf

**Comment by matthew-carroll** [comment]
I have reproduced the `FlutterTextureView` leak when switching between parallel `FlutterFragment`s using tabs in an `Activity`. Now I'm working on the fix.

**Comment by matthew-carroll** [comment]
This issue is fixed here: https://github.com/flutter/engine/pull/15899
