### ISSUE TITLE
Support for dashed line

### ISSUE THREAD

**Issue by midoringo8823** [flutter/flutter#4858]
## Steps to Reproduce

There's no API for setting path effect for dashed lines for drawing.

**Comment by eseidelGoogle** [comment]
@Hixie I recall you saying once that this was an intentional omission because dashed lines are slow?  But then also that flutter/game had an implementation (or some example did?).  Am I remembering correctly?  Could you point me to that example?  FYI @mit-mit

**Comment by Hixie** [comment]
I implemented it on a circle for one of our demos (now the drag and drop manual test). We don't have generic path dashing because as you say, it's expensive to compute such paths. You can manually implement this by writing the code to manually draw the path dashed, but that'll be a lot of work, and thus feel expensive. Expensive things should look and feel expensive, so that people don't do them as much.

**Comment by mzimmerm** [comment]
This is probably obvious question, as I do not see anything like that in the Flutter API,  but let me ask to confirm: In Flutter, there is no classes for Android equivalent (or Android similar) role of PathEffect or it's extensions ComposePathEffect, CornerPathEffect, DashPathEffect, DiscretePathEffect, PathDashPathEffect, SumPathEffect, is that correct (at timepoint August 2017)? Thanks

**Comment by sethladd** [comment]
@mzimmerm thanks for the questions!

**Comment by Hixie** [comment]
That is correct at the moment. In due course we'll probably expose more and more such APIs, especially the fast ones.

**Comment by nsreenath** [comment]
![image](https://user-images.githubusercontent.com/3154529/37234748-a4b21624-241f-11e8-849c-5e94c4119b2c.png)

@Hixie, Skia already has these [effects](https://github.com/google/skia/tree/master/src/effects) implemented.  Is the implementation less performant ?

**Comment by cbazza** [comment]
Quite a shame that SkiaSharp has great coverage of Skia (a Google project) functionality available for C# (a Microsoft project), yet Flutter/Dart (a Google project) has almost nothing.

Just take a look at their API docs and compare that to Flutter and Skia
https://developer.xamarin.com/api/namespace/SkiaSharp/

https://developer.xamarin.com/api/type/SkiaSharp.SKPaint/
https://skia.org/user/api/SkPaint_Reference
https://docs.flutter.io/flutter/dart-ui/Paint-class.html

**Comment by Hixie** [comment]
It's actually very intentional. We are being very careful in what we expose, so that using the API in the intuitive way will result in fast code where possible. We are being careful to make expensive APIs feel expensive.

This is a case where "less is more" is really true.

**Comment by cbazza** [comment]
> It's actually very intentional. We are being very careful in what we expose, so that using the API in the intuitive way will result in fast code where possible. We are being careful to make expensive APIs feel expensive.

Removing an API, doesn't make it feel expensive, it makes it feel non-existant and it is a hidiculous argument to me because instead of using an optimized API designed by graphics experts and tested to work on all scenarios, you now put that responsibility on general developers that couldn't care less about performance or general correctness. Not to mention that proper dashing code is non trivial and pretty hard to get it right when you consider thickness, gaps, offsets, general path, conics, beziers, etc.

If you want to bring the 'performance' argument, show numbers but even with numbers it is nonsensical; Vector Graphics engines have a certain minimum feature list and dashing is part of it. The original Mac from the mid-80's had rounded rects, dashes and regions. The original iPhone from 11 years ago was able to have a performant and powerful graphics engine without bastardizing the API.

Imagine if you removed the 'Q' letter from the fonts with the argument that it took too long to render it and devs could just use an 'O' and an comma. Is it really the case where "less is more"...

**Comment by nsreenath** [comment]
https://github.com/mono/SkiaSharp/issues/47
They didn't even talk about performance, regarding this same issue in SkiaSharp !!

**Comment by Hixie** [comment]
We _have_ made that kind of choice. For example, we made the explicit choice not to support vertical text layout (as used in traditional Japanese typography, for instance) because we believe that supporting vertical text layout would dramatically increase the complexity of our framework (which would affect performance and usability).

Having said that, I have some good news for you if what you want is dashed lines. @dnfield has been working on a patch which will make it possible to implement dashed lines as a platform feature relatively easily. When that lands, you'll be able to write a little utility method that turns any Path into its equivalent dashed Path.

**Comment by cbazza** [comment]
OK, so you are adding the path operation stuff and I assume you are thinking of using 'extractPath' and operations (intersect, union, etc) to create dashes. Let's consider animating a dash; how is your proposed 'new' method more performant than what Skia has natively implemented?

How will the API look compared to normal Skia ? Looks hacky (and heavy) to me since to draw dashes on a rectangle I would first need to convert to a path (same for all the other canvas primitives aside from Path). 

My money is on Skia for performance and intuitive APIs. 

You should modify the architecture diagram: https://flutter.io/technical-overview/
so that instead of 'Skia' it says 'Quasi-Skia', 'Semi-Skia', 'The-margarine-of-Skia' or 'The-diet-coke-of-Skia', anything else seems like false advertising.

**Comment by eseidelGoogle** [comment]
@cbazza I'm glad that you're expression passion on this topic.  :)  However I would ask that we keep the discussion as technically (and positively) focused as possible.  I don't read the 4th paragraph in your previous comment as really aiding bringing this discussion to a helpful resolution.  Patches are certainly welcome to flutter.io/faq to answer if Flutter exposes all of Skia's APIs if you believe that's a common concern. :)

As Ian noted, Flutter was founded with a bias towards trying to make it easy to go fast, in part by only providing the "fast" apis.  Obviously that may not always sufficient, and we may have erred here in by not (yet) providing a line dashing API!  But the only way to correct that is going to be through reasoned discussion of the user benefits of doing such and the tradeoffs those entail.  I suspect it may be too early to make this call as we have so many other missing holes to fill in yet. :(  This specific bug is relatively low on our user voted list of issues:
https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
We review those regularly as part of planning engineering work.

This bug (as others have noted) also has a known (albeit possibly ugly) workarounds, as demonstrated by charts_flutter having dashes without an official Flutter Skia API:
https://github.com/google/charts/blob/master/charts_flutter/lib/src/canvas/line_painter.dart#L81

In any case, I have no strong opinion as to whether Flutter exposes Skia line dashing APIs.  I leave that to @Hixie and other senior engineers to drive.  I do expect us all to work together to resolve these things and follow our code of conduct.
https://flutter.io/design-principles/#code-of-conduct

Thanks all.

**Comment by cbazza** [comment]
That 4th paragraph was an attempt at humour :)

Anyways, please send your alternatives to the Skia team and ask them if they think this is a good idea.

Your current workaround is extremely limiting (as commented in the code):
https://github.com/google/charts/blob/master/charts_flutter/lib/src/canvas/line_painter.dart#L81
and I'll repeat here:
`Dash patterns are currently only supported between vertical or horizontal line segments at this time.` 

Regarding the new path ops stuff, I don't think the API will be nice and I don't think it will perform anywhere near Skia. 

Get Skia people involved here and listener to what they have to say.

>  But the only way to correct that is going to be through reasoned discussion of the user benefits of doing such and the tradeoffs those entail.

Skia is a nice and feature rich 2D vector engine. When they designed it, they provided stuff people needed and that other such engines have it. This is obvious stuff like lowest common denominator for Vector Graphics engine, and you want us to 'show user benefit, etc, etc' before you do something about it? 

https://github.com/flutter/flutter/issues/9641
Provided great specs :)

https://skia.org/user/api/skpaint_overview
Has basic functionality that every Vector Graphics developer would find needed.

**Comment by Hixie** [comment]
We work very closely with the Skia team.

If you think there is a performance issue with a particular API, please write a benchmark demonstrating the problem. We carefully investigate performance issues and they directly inform our API design. If you think there is a faster way to implement a particular feature, please don't hesitate to implement that faster way and compare the benchmarks. You may find you are surprised as to what is slow and what is fast. For example, we recently discovered that it's just as fast to parse SVG path descriptions in Dart and construct the paths manually in Dart, than it is to have the entire operation done in C++. We discovered this by benchmarking the two options and comparing the results, before deciding on the implementation strategy.

**Comment by cbazza** [comment]
> We work very closely with the Skia team.

Excellent, so could you please include one of their senior devs in this discussion to move it forward so that I can have some answers to my concerns that require Vector Graphics Engine expertise?

**Comment by dnfield** [comment]
I think a reasonable approach here would be to try to get some tests of doing dashed paths as a dart library and test it against the native Skia calls.  I can try to get to that at some point, but have a few other things I'm trying to wrap up that are higher on my personal list at the moment.

**Comment by cbazza** [comment]
Hi @dnfield,

As before, don't let what I say stop you... but having said that the race here is not even close, it's orders of magnitude apart.

Thing is, the drawing operations are performed in the GPU (hardware accelerated) whereas the 'path ops' are executed in the CPU (C++ code) and the computations are heavy (specially considering splitting conics, beziers, circles, rounded rects, etc).

So you can just let the GPU do it's thing at drawing time, or use lots of CPU cycles followed by GPU rendering.  It's like clocking 'Usain Bolt' vs 'Usain Bolt carrying a desktop computer' :)

As always I could be wrong here and once again I am asking for the professional opinion/input of the experts in the field. Can someone from the Skia team shred some light here?

@reed-at-google @bsalomon @HalCanary @mattsarett @egdaniel
@fmalita @brianosman @jvanverth @LeonScroggins

**Comment by cbazza** [comment]
> The PR that I have made that @Hixie was referring to would allow for a fair amount of this work to be done on the GPU thread, AFAICT - something like measure the path, get subsegments of the path, and draw those; only a few calculations would actually be done in Dart land.

I read every line of your PR and my comments above reflected that.
https://github.com/flutter/engine/pull/4799/files

Let me give it another shot at explaining the situation. Plain C++/Dart code are relatively comparable speedwise. When Plain C++ code is not fast enough, Vector Graphics engineers embed assembly language into their C++ code. These instructions take advantage of the parallel arithmetic vector hardware inside the CPU. Google around for 'SIMD' and you will see what I am talking about.

When a graphics engine says that they use SIMD to speed up their code, they have done benchmarks, etc and there is no way for plain C++ to beat that. When SIMD code is not fast enough, Vector Graphics engineers use the hundreds of smaller CPUs inside the GPU to obtain another other of magnitude speed improvement. GPU code looks like C code written in GLSL (the OpenGL Shading Language). Again, when a graphics engine says that they are GPU accelerated, they have benchmarked their GPU code against SIMD & CPU (just to quantify how much faster it is) and there is no way for SIMD & CPU to beat it. Also GPU code is a lot more energy efficient than CPU code, and that's why you can watch video on your mobile for hours without killing the battery.

So you can implement dashes in 2 ways:
(A) 
*  (step 1) Let the GPU draw the shape with the given paint ('Usain Bolt').

or
(B) 

* (step 1) Use the CPU (with Plain C++/Dart code) to break the path into a whole bunch of smaller pieces. This unfortunately is very CPU intensive because of the math involved breaking conics, beziers (quadratic & cubic), circles, arcs, etc ('desktop computer')
* (step 2) Let the GPU draw the shapes with the given paint ('Usain Bolt') 

Mathematically speaking:

'A-step-1' same speed as 'B-step-2'
'B-step-1' extra computation that happens to be heavy 
therefore
'A' always faster than 'B'

If you are just comparing C++ against Dart code with similar algorithms then yeah no point in discussing performance, just instrument/measure it and now we have something to talk about it.

With Graphics, architecture has a big impact because depending where code is it is using more powerful hardware.

The best way to deal with Graphics API is to assume the Skia API is super fast because you won't be able to make anything faster with plain C++ or Dart code. The pathOps code (path manipulation, union, intersection, difference) is just plain C++ code.

I think it would be way better to just take what Skia provides instead of wasting time (tying to make something fast go slow), frustrating app developers and insulting Skia developers (their silence is speaking volumes).

**Comment by dnfield** [comment]
So on my analysis of the Skia Dash effects code, I don't see any direct use of SIMD - and as far as I can tell any indirect use of it is already exposed in the Dart code.  Can you point me to anything I might be missing here in the Skia codebase?  I'd be interested to see it.

I think there are some valid questions about how well this code will perform in the "GPU" thread in the Flutter architecture vs. the Dart thread, but that's a little bit different than what you seem to be getting at.

At any rate, it doesn't really seem like Skia is working the way you think it is _in this case_.  But without any real tests, we're both pointing at code and diagrams and mental models that we disagree on, and I'm not sure we'll make much progress.

**Comment by cbazza** [comment]
I never opposed your measurements; do them but I would wait to first hear back from the experts which is the Skia people.

**Comment by cbazza** [comment]
Just spent some time looking at Skia code... lots of code my head is spinning... but it looks like the Dash effects are *not* GPU accelerated so it is going to be a close race to call, might as well just do the measurements.

**Comment by nsreenath** [comment]
Android AOSP also delegates rendering of dash path to `SkDashPathEffect`. They have been using it since [2008 ](https://github.com/aosp-mirror/platform_frameworks_base/blob/54b6cfa9a9e5b861a9930af873580d6dc20f773c/graphics/java/android/graphics/DashPathEffect.java)in their first commit! They [still](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/jni/android/graphics/PathEffect.cpp#L46) use it because it performs better than implementing it in Java. But in our case, implementing it in Dart may be as powerful as the C++ implementation in Skia.

> So you can implement dashes in 2 ways:
(A)
(step 1) Let the GPU draw the shape with the given paint ('Usain Bolt').
or
(B)
(step 1) Use the CPU (with Plain C++/Dart code) to break the path into a whole bunch of smaller pieces. This unfortunately is very CPU intensive because of the math involved breaking conics, beziers (quadratic & cubic), circles, arcs, etc ('desktop computer')
(step 2) Let the GPU draw the shapes with the given paint ('Usain Bolt')

[Skia](https://github.com/google/skia/blob/master/src/effects/SkDashPathEffect.cpp) seems to be following case B, may be because it is not easy to implement it using GLSL.

**Comment by nsreenath** [comment]
OpenGL has a function called `glLineStipple`.
It can be used to create dashed line. I am not sure if it can be used for creating paths others than lines.

Below is a screenshot from http://cse.csusb.edu/tongyu/courses/cs420/notes/drawing.php
![image](https://user-images.githubusercontent.com/3154529/38470559-47507758-3b82-11e8-97e8-d4fd1f26a39b.png)

**Comment by cbazza** [comment]
Shader-Based Antialiased, Dashed, Stroked Polylines
http://jcgt.org/published/0002/02/08/paper.pdf

**Comment by dnfield** [comment]
Initial implementation here: https://github.com/dnfield/flutter_path_drawing/blob/master/lib/src/dash_path.dart

Requires 0.3.6

Potential enhancement that I don't think is possible right now: only dash visible portion of path.

**Comment by csga5000** [comment]
Just my +1 of this issue, I accidentally commented on a closed dup: https://github.com/flutter/flutter/issues/9641

But tl;dr: While I understand that one of flutters goals is to be performant and speedy on a range of devices, I'm pretty sure flutter also very highly values being easy to use and speeding up development time.  Regardless of the performance of dashes people are going to want dashes in their apps in certain cases.  And I think this should be as easy as changing a BorderStyle.  If you're worried about "performance" then put in the documentation of BorderStyle.dashed "WARNING: dashed borders can affect drawing performance on some devices".

Making something so commonly used difficult to implement seems to go against many of flutters values especially where it's easy to implement on not just the native platforms but really any platform.  As part of google it seems to me like your guys' job to figure out how to make it fast, but we (developers using flutter) need this to be easy.  And when we see dashed isn't in the BorderStyle's enum we go "Flutter doesn't support dashes?"

Since things have perhaps been heated, I will add that I love flutter!  And I think the flutter team has done a fantastic job of considering how to make things easy for developers and allow creating quality applications!  And my liking of flutter is why I kinks like this need to be worked out.

**Comment by marcglasberg** [comment]
I must agree with @csga5000 that it's enough that the documentation of BorderStyle.dashed contains a "WARNING: dashed borders can affect drawing performance on some devices"; The alternative of simply not providing basic functionality, like dashed lines, tarnishes the reputation of Flutter. I once was going to use a BackdropFilter but read this: "This effect is relatively expensive, especially if the filter is non-local, such as a blur." That's good! Give us the option, and let us decide. We're all adults here. Otherwise, that's just a bad case of "premature optimization". It's very easy for devs to experiment with dashed lines and see if it made their code slow in practice, for their use cases.

**Comment by Hixie** [comment]
Given the availability of `Path.computeMetrics` and `PathMetric.extractPath`, this is now a relatively straight-forward problem to solve in Dart, as Dan showed above. Given this, is this still something you think we need to see in Flutter itself?

**Comment by cbazza** [comment]
I think people would prefer to have a borderStyle of dashed and a way to pass the dash array and dash offset. 

By the way, dash array & offset are the corner stone of creating handwriting-like reveal animations:
https://css-tricks.com/svg-line-animation-works/

**Comment by csga5000** [comment]
@Hixie Flutter prides itself in being easy and having a small learning curve.  While we still maintain that it seems sensible to provide dashed path as a simple configuration on a border like everything else does, any option that a new developer could pick up and do in a few minutes would probably be ok.  (Even if it warns them that dashed lines have poor performance).

Correct me if I'm wrong, but at the moment it doesn't seem well documented or super easy and therefore it's a typically trivial task that here has quite a high learning curve considering.  Please point me to where the documentation is, if it exists, but googling around I don't see much.  And even @dnfield's library doesn't appear to be documented which seems to suggest you have to rely on digging into the code, or maybe try going off of intellisense?  And either way it means someone has to install an extra package just for a dashed line.  It seems excessive to make the average dart programmer write logic to draw their own path just to give something a certain kind of common appearance.

Though, @dnfield seems to have a good point, the svg line animation in CSS seems like it is a manipulation of CSS, and I can see value in writing that using more appropriate code. (Even if it takes more effort/lines of code)  That's a task you'd expect to take some effort anyway.

**Comment by Hixie** [comment]
Sounds like what's left to do here then is to make sure that we have a library that's well-documented available in pub.

**Comment by cbazza** [comment]
> @cbazza that works in HTML/CSS (I guess because there's no other good API for it exposed), but I don't believe that's the way it should be done for Flutter, where you could directly compute the path length, get the appropriate subpath, and draw that.

@dnfield there are other APIs in JS to do this imperatively just like you describe but the key here is that if Flutter supports borderStyle of dashed with dash array & offset, I can write animation code that is totally declarative and need no procedural manipulation as you recommend. 

I have mentioned this before but Flutter needs to use more declarative techniques than just imperative ones.

**Comment by rmtmckenzie** [comment]
Just weighing in here as I've had someone ask me how to make a dashed border in flutter before and I ended up writing something somewhat similar to the above to make the path segments.

I agree with a few others that it needs to be simple, and think that ideally an option of 'dashed' or 'custom' for BorderStyle (with performance caveat in documentation) would be great as 1) a new user won't have to dig to find it, and 2) all of the existing shapes would theoretically be compatible i.e. TableBorder, InputBorder, RoundedRectangleBorder, StadiumBorder etc...., and 3) it would make it simple to have a shape with some borders dashed and some not.

That being said, I have no idea how I'd go about implementing that, given that dart's enum don't allow for much flexibility. Maybe something like BorderStyle.custom and an optional CustomBorderStyle interface would do? Or making BorderStyle no longer be an enum? With a solution like that, it would then be simple enough to provide DashedBorderStyle in a library (which could be mentioned in the docs for CustomBorderStyle). And I think the existing implementation wouldn't have to be changed all that much, it would just mean that if any/all of the sides were Custom, then it would have to do the less efficient non-uniform painting process.

I could see each of the Borders listed above potentially having use for at least one dashed border, and it would be unfortunate if each of them had to be replicated with minor changes other than support for dashed lines.

**Comment by Hixie** [comment]
Making BorderStyle extensible somehow would be interesting.

**Comment by Hixie** [comment]
Filed that as https://github.com/flutter/flutter/issues/23801

**Comment by dnfield** [comment]
I've made some minor improvements to the documentation of `path_drawing`, and implemented a path trimming routine.  I haven't published it to pub just yet because I'd like to get some tests, and I'd also appreciate any feedback on the API interface.

**Comment by lukepighetti** [comment]
Hi everyone, just wanted to say that I am looking to implement a dashed/dotted line in CustomPainter. I would like to remind the Flutter team that what is trivial for you is not trivial for the average developers. Having to implement your own dotting/dashing algorithm for a path is a quantum leap from "2px dashed black"

**Comment by dnfield** [comment]
(Since my last comment I've added tests and published)

**Comment by matthew-carroll** [comment]
@dnfield I came across this as I was searching for how to render a dashed border on a Container.  Would you mind posting here with a link to where an outside developer should start learning about your solution?  Also, can you post a code snippet here that demonstrates an example use-case of your solution?

**Comment by dnfield** [comment]
@matthew-carroll  until we fix #23801 it won't be trivial to do this.  Here's a quick example that works for uniform borders, based on `Border`:

```dart
import 'package:flutter/material.dart';
import 'package:path_drawing/path_drawing.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              decoration: BoxDecoration(
                border: DashPathBorder.all(
                  dashArray: CircularIntervalList<double>(<double>[5.0, 2.5]),
                ),
              ),
              padding: const EdgeInsets.all(20.0),
              child: const Text('You have pushed the button this many times:'),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class DashPathBorder extends Border {
  DashPathBorder({
    @required this.dashArray,
    BorderSide top = BorderSide.none,
    BorderSide left = BorderSide.none,
    BorderSide right = BorderSide.none,
    BorderSide bottom = BorderSide.none,
  }) : super(
          top: top,
          left: left,
          right: right,
          bottom: bottom,
        );

  factory DashPathBorder.all({
    BorderSide borderSide = const BorderSide(),
    @required CircularIntervalList<double> dashArray,
  }) {
    return DashPathBorder(
      dashArray: dashArray,
      top: borderSide,
      right: borderSide,
      left: borderSide,
      bottom: borderSide,
    );
  }
  final CircularIntervalList<double> dashArray;

  @override
  void paint(
    Canvas canvas,
    Rect rect, {
    TextDirection textDirection,
    BoxShape shape = BoxShape.rectangle,
    BorderRadius borderRadius,
  }) {
    if (isUniform) {
      switch (top.style) {
        case BorderStyle.none:
          return;
        case BorderStyle.solid:
          switch (shape) {
            case BoxShape.circle:
              assert(borderRadius == null,
                  'A borderRadius can only be given for rectangular boxes.');
              canvas.drawPath(
                dashPath(Path()..addOval(rect), dashArray: dashArray),
                top.toPaint(),
              );
              break;
            case BoxShape.rectangle:
              if (borderRadius != null) {
                final RRect rrect =
                    RRect.fromRectAndRadius(rect, borderRadius.topLeft);
                canvas.drawPath(
                  dashPath(Path()..addRRect(rrect), dashArray: dashArray),
                  top.toPaint(),
                );
                return;
              }
              canvas.drawPath(
                dashPath(Path()..addRect(rect), dashArray: dashArray),
                top.toPaint(),
              );

              break;
          }
          return;
      }
    }

    assert(borderRadius == null,
        'A borderRadius can only be given for uniform borders.');
    assert(shape == BoxShape.rectangle,
        'A border can only be drawn as a circle if it is uniform.');

    // TODO(dnfield): implement when borders are not uniform.
  }
}
```
![image](https://user-images.githubusercontent.com/8620741/54334829-69b76f00-45e4-11e9-94d6-786821d33423.png)

**Comment by dnfield** [comment]
If we changed that `DashPathBorder` to just a `PathBorder`, we could probably add it to the framework and let someone pass in the path they want,which should probably resolve the linked issue as well.

**Comment by dnfield** [comment]
Also, that `dashPath` method comes from `path_drawing: ^0.4.0`.

**Comment by dnfield** [comment]
I've opened a PR to make it a bit easier to draw a border with an arbitrary path.  I think if we can get something like that in, we should probably just close this issue - I don't know that the framework will be adopting any additional logic to dash paths.

**Comment by anztrax** [comment]
thanks bro @dnfield  👍

**Comment by hoaquo** [comment]
That's unbelivable there's no basic path operations in Flutter:

- Enumerate path (PathMetrics is good but for simpler operations why we should take those expensive)
- Create stroke outline from unclosed path
- Dash path
- Unclosed path intersecting

Could you please consider support those features.

**Comment by micimize** [comment]
Adapted @dnfield's example to a `StadiumBorder`, with an `inset` option (for my dashed-chip usecase)
```dart
import 'package:flutter/material.dart';
import 'package:path_drawing/path_drawing.dart';

class DashedStadiumBorder extends StadiumBorder {
  DashedStadiumBorder({
    this.inset = false,
    CircularIntervalList<double> dashArray,
    BorderSide side,
  })  : this.dashArray = dashArray ??
            CircularIntervalList<double>(
                <double>[4 * side.width, 2 * side.width]),
        super(side: side);

  DashedStadiumBorder.inset({
    this.dashArray,
    BorderSide side,
  })  : inset = true,
        super(side: side);

  final CircularIntervalList<double> dashArray;

  final bool inset;

  @override
  EdgeInsetsGeometry get dimensions {
    return EdgeInsets.all(inset ? 0.0 : side.width);
  }

  @override
  void paint(Canvas canvas, Rect rect, {TextDirection textDirection}) {
    switch (side.style) {
      case BorderStyle.none:
        break;
      case BorderStyle.solid:
        if (inset) {
          rect = rect.deflate(side.width);
        }
        final Radius radius = Radius.circular(rect.shortestSide / 2.0);
        final rrect = RRect.fromRectAndRadius(rect, radius);
        canvas.drawPath(
          dashPath(Path()..addRRect(rrect), dashArray: dashArray),
          side.toPaint(),
        );
    }
  }
}
```

**Comment by feinstein** [comment]
I understand dashed lines as slow, but what are the options we have then? Not drawing a dashed line at all? Doesn't this goes against Flutter's own principle of:

>Flutter helps deliver the original design vision, without loss of fidelity or compromises

If I go to my designer and say "Can you remake it without dashed lines? Our code doesn't support it", this just takes me back to native development where design compromises where a daily routine.

I honestly think flutter should support dashed lines, with big warnings on the docs. This is something very basic to any UI and shouldn't be a decision on the Framework level not to provide it, but our decision as devs to know when to avoid it. I have seen such warnings on the docs before.

In my particular case, I just need a straight dashed line to be shown once, dividing a `Card` in half. No animations, no nothing. I am pretty confident that it won't take any visible performance impacts, so I feel this decision should be mine, as I know my use case, and not from the Flutter team.

Thanks for listening.

**Comment by dnfield** [comment]
@feinstein - is there some reason that you can't just use `flutter_path_drawing`?  

The framework enables all you need to draw dashed lines at a pretty low level - in fact, flutter_path_drawing's code to do this is really only a few dozen lines of code wrapping that functionality.

The reason to not put the code in the framework itself is because it's something that is fairly expensive, and thus should be hard to do.  For example, in the case of a straight dashed line shown once, you could create the path you want and get subsegments of it - or you could just pre-calculate it and draw only the paths you actually want on a canvas - or you could pre-calculate it using `ColoredBox`es or `Container`s in a `Row` or `Column` or `Stack` or what-have-you.

I'm going to close this bug - I don't believe the framework will ever make it any easier to draw dashed lines (for reasons outlined in this bug).  There is also a package available that helps you do it, which is maintained by a framework maintainer (which happens to be me! :)).

**Comment by feinstein** [comment]
@dnfield you mean [this package](https://pub.dev/packages/path_drawing) right? I am going to use it, it just felt weird that Flutter wouldn't support dashed lines natively as this is something pretty basic nowadays and I wanted to share my thoughts on this.

**Comment by marcglasberg** [comment]
@feinstein  Once in a while you find these strange things that all other languages/frameworks provide, but Dart and Flutter don't because they think developers shouldn't do it. It's an ideological barrier, so it's useless complaining. Dashed lines is one example. Another is to check if a Future is completed. You can't. Another is to be able to format your code with your own formatter. You also can't because they think you shouldn't. It's OK, Flutter is good, nothing is perfect.

**Comment by feinstein** [comment]
@marcglasberg I feel like Apple telling me I am "holding it wrong" lol, but fortunately `path_drawing` makes this possible (although its a bit cumbersome/low level to use), but as long as it works its fine by me.

I agree with you that things can be frustrating sometimes, but then I remember how much more frustration I had in Java, so I start to feel better again.

BTW, dart provides an additional [async ](https://pub.dev/packages/async) library (2 parts blog post [here](https://news.dartlang.org/2016/03/unboxing-packages-async-part-1.html) explaining it) that many don't know about and there you can use `ResultFuture` which lets you ask if the `Future` already completed and get its value synchronously.

**Comment by marcglasberg** [comment]
@feinstein I know that lib, but async/await returns a regular Future. Anyways.

**Comment by Hixie** [comment]
This issue is about dashed lines, which is now possible (using Path.computeMetrics et al).
For other topics, please file separate issues. I'm not aware of anything preventing you from using your own formatter (indeed, the Flutter framework itself doesn't use dartfmt), but if there's something that would prevent it, we would want that filed as a bug so it could be fixed. Regarding Futures, if there's something you can't do because of the Future API, then again please file an issue so that we can make sure your use case is handled.

Commenting on this issue is unlikely to result in any changes since it is closed.
