### ISSUE TITLE
TextField calls InputFormatter twice for each keypress.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#48608]
Extracted from b/146389916

The TextField calls the InputFormatter twice for each keypress. If the first pass changes the TextEditingValue state, then the second pass may produce different results as the first pass, resulting in unexpected behavior with no obvious cause.

This has been verified for when the keyboard type is set to `TextInputType.numberWithOptions()`

We should figure out why the second pass is called and see if we can just do one call of the formatter.

**Comment by GaryQian** [comment]
The double call is due to the framework notifying the engine of the post-format value, which then loops back when the engine takes the post-format value and tells the framework.

This was made to match iOS behavior, but it is now causing unexpected behavior in Android formatters.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/49406 is an attempt at fixing this. The PR resolves this issue, but I have concerns at how it applies generally. Will verify.

**Comment by luistrivelatto** [comment]
Apparently, we're experiencing this or a similar bug in https://github.com/gtgalone/currency_text_input_formatter/issues/11. The issue is happening with keyboards for numbers (`number` or `numberWithOptions`), but, instead of happening at any keypress, it's happening only on backspace presses. And not only does it call the formatter twice, but we've also noticed the formatter being called four times.

Code for reproducing the bug, flutter doctor and a gif illustrating the issue can be found here:
https://github.com/gtgalone/currency_text_input_formatter/issues/11#issuecomment-749743947
