### ISSUE TITLE
Flutter Gallery Tabs example can't scroll at 60fps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4860]
You can swipe between tabs at 60fps, but the rasterizer can only hit about 40fps when scrolling.  Not sure why.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/tabs_demo.dart

![flutter_05](https://cloud.githubusercontent.com/assets/11857803/16702286/da70a50a-4519-11e6-97b3-ce1e8cd29e1e.png)

**Comment by eseidelGoogle** [comment]
14ms swap buffers.

![screenshot from 2016-07-08 14 45 55](https://cloud.githubusercontent.com/assets/11857803/16702437/bd274a8e-451a-11e6-8c71-79116165e1d8.png)

**Comment by eseidelGoogle** [comment]
Showed @abarth in person just now.  Trace: http://s000.tinyupload.com/index.php?file_id=55165834735224643828

**Comment by HansMuller** [comment]
Performance improves a little if LazyBlock is used instead of Block.

Performance is 60fps if Card is replaced by Container.

**Comment by mehmetf** [comment]
Leafy's performance is also affected by this. As mentioned in https://github.com/flutter/flutter/issues/4367, turning off shadows (by setting card elevation to 0) remedies the issue for the most part.

**Comment by HansMuller** [comment]
Reducing this demo to a simple scrolling list of cards doesn't really address the performance problem.

It's very odd that the Shrine product page and the cards demo, both of which display more cards (and more drop shadows) don't exhibit any performance problems.

Just worked through this with @abarth.

The source of the problem is the heuristic for raster caching in the engine: https://github.com/flutter/engine/blob/a126207c6eaa06785e6ac49eb36d90eee225abff/flow/raster_cache.cc#L22

Making the cards graphically more complex (which is worthwhile anyway since they're boring) causes raster caching to kick in and performance jumps to 60FPS.

Support for advising the raster caching heuristic is coming, see https://github.com/flutter/engine/pull/2816

**Comment by mehmetf** [comment]
We also observed that Shrine's product page is affected by shadow performance. The only thing on that page casting a shadow is the FAB and when the FAB is over the image grid, FPS suffers a great deal.

Would raster caching help here since shadows are dynamic? The shadow is being cast onto a scrolling image.

**Comment by abarth** [comment]
Each product card is casting a shadow too.

> Would raster caching help here since shadows are dynamic? The shadow is being cast onto a scrolling image.

Yes, the caching happens before the shadow is composited into the scrolling items below.
