### ISSUE TITLE
Allow setting FLAG_SECURE on individual app screens

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#48680]
See internal bug b/147369329

Customer Request:

> FLAG_SECURE is used to secure certain screens from device screenshots and/or screen recording. The way to use it is to add the flag to the Window params for the screens that we want to protect.
> 
> Currently in Flutter, since the entire app runs on a single Activity, it doesn't seem like there's a way to selectively add FLAG_SECURE to only parts of the app (e.g. only secure the settings screen, let user be able to still do screenshots on home screen).
> 

This is theoretically possible. SurfaceView (which is what Flutter uses) has a method to [secure its buffer](https://developer.android.com/reference/android/view/SurfaceView.html#setSecure(boolean)). It would require the embedder to un-attach and reattach the surfaceview to the view hierarchy before you push the secure route (and do it again to unsecure it when the route is popped). This might cause artifacts.

**Comment by mehmetf** [comment]
It is unclear whether it is possible to do this on iOS. Recommendation to the user is to secure the entire app for now.

**Comment by dnfield** [comment]
I think this is the same as https://github.com/flutter/flutter/issues/33236 - see specifically https://github.com/flutter/flutter/issues/33236#issuecomment-503783281 and https://github.com/flutter/flutter/issues/33236#issuecomment-503876922

**Comment by dnfield** [comment]
Although in those comments the solutions I suggested were not targetted to specific flutter routes/screens.

**Comment by jonahwilliams** [comment]
Strawman design:

Create a new system channel method: secureRoute: true/false. When received, pop the surface view and toggle FLAG_SECURE on the SurfaceView used for rendering.

Create a new route type called "SecureRoute" which (only on Android) sends the message when the route is pushed/popped.

TBD:
  - implications for rendering performance
  - implications for accessibility tree
  - implications for PlatformViews

**Comment by dnfield** [comment]
I think the problem with that is the message is async and we don't know if it will complete in time for when the application is backgrounded, right?

**Comment by jonahwilliams** [comment]
Then wait for a response before pushing/popping the route - these are already async operations

**Comment by dnfield** [comment]
I believe we could make it work for iOS as well as long as we control the app delegate

**Comment by dnfield** [comment]
Perhaps even if not we could subscribe to the right notification

**Comment by jonataslaw** [comment]
Even adding FLAG_SECURE natively before starting a route (using await so that the operation is actually completed before the next route is pushed) it still doesn't work. In fact, FLAG_SECURE only prevents screen locking, but screen recording on Flutter is still possible in any situation. In the previous version, if you started an activity with FLAG_SECURE, and the recording started before the application, FLAG_SECURE worked. In the latest version, with the new FlutterActivity there is no way to make FLAG_SECURE work.
likewise, "SurfaceView(this).setSecure(true)" has no effect on applications with Flutter.

**Comment by mehmetf** [comment]
I am escalating this to critical since in the last meeting customer:money mentioned this will be a release blocker.

**Comment by Hixie** [comment]
Can we just... not support this at all? It's so user-hostile...

**Comment by Hixie** [comment]
Separate from my own concerns about the value of this feature, I think we should not support this in the framework. We should make sure it's possible for people to implement this manually (using something similar to what @jonahwilliams described above), but not actually implement the feature.

**Comment by cbracken** [comment]
Since this isn't something we expect a huge demand for across most apps, this is probably a better fit for a plugin than it is for the engine itself. Since there should be nothing blocking implementing such a plugin, I'm going to remove the customer blocker label.

If it turns out that for some reason, it is not possible to implement this as a plugin, please let us know and provide details, so we can take another look.
