### ISSUE TITLE
[web]: web package:http

### ISSUE THREAD

**Issue by zhouxingtuan** [flutter/flutter#48704]
Response headers in the package http parse the 'content-length, content-type' only. Will it support to parse all the return headers, like self define header 'XXX: YYY'?

**Comment by VladyslavBondarenko** [comment]
Hi @zhouxingtuan ,
Since [http](https://pub.dev/packages/http) is a 3rd party plugin I suggest you to ask your question in the [dedicated repository](https://github.com/dart-lang/http)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you
