### ISSUE TITLE
Enable lazy async stack traces via tool feature

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#48725]
The additional flags `--no-causal-async-stacks` and  `--lazy-async-stacks` can drastically improve the performance of async/await operations, at the cost of slightly different stack traces.

**Comment by Hixie** [comment]
Marking critical for now based on #40345's markings; that may change if the customer affected by that bug is happy.

We should consider having `-Os` and `-O2` flags that change the balance of features/optimizations towards size/performance, rather than having each of these features individually controllable. cc @a-siva who has talked about doing that on the VM side too.

**Comment by jonahwilliams** [comment]
This requires a small change in the dart SDK where we could set the --lazy-async-stacks flag via dart define similar to the existing define for --no-causal-async-stacks. Currently the latter can be configured via https://github.com/dart-lang/sdk/blob/f689f145b1a210b05639421c4535dcdee7a2dcef/runtime/vm/symbols.h#L73 but the former can't

**Comment by jonahwilliams** [comment]
Actually, this may not be necessary at all provided we're only going to enable it for profile/release

**Comment by jonahwilliams** [comment]
fyi @zanderso

**Comment by zanderso** [comment]
We may need `-Os` and `-On` flags at some point, but we should consider whether we want to enable these specific flags by default to avoid the multiplicative effect from testing flag combos.
