### ISSUE TITLE
Enable Observatory timeline on Fuchsia

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48819]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=44063.

**Comment by rmacnak-google** [comment]
The destination of timeline/trace events coming from either Dart code or the Dart VM is selected at start up with the VM flag --timeline-recorder. The value "systrace" will forward events to Fuchsia's system tracing. The values "ring" (remove oldest event when full), "startup" (drop new events after full), and "endless" (grow without bound) will keep the events in the VM itself, where they can later be accessed with the VM service through Observatory or other tools. The VM does *not* provide a way to simultaneously keep events in its own buffer and forward them to the system tracing.

Unconditionally enabling --timeline-recorder=systrace on Fuchsia should be quite cheap, because the Dart VM will bail out quickly when generating events if the Fuchsia tracing system indicates that a trace category is not enabled.

**Comment by kf6gpe** [comment]
Closed upstream.
