### ISSUE TITLE
GlobalKeys causing unexpected rendered Widget position

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#48855]
Steps to Reproduce

1. Run flutter create
2. Add the three files at this gist to your project, including replacing main.dart: https://gist.github.com/emshack/0bdfee8f86377301075ee573a994d66c
3. Run the app on a target device
4. Observe three things: A tree structure on the left, "Expected order" text on the right, and an icon button at the bottom. The order of the tree structure from top to bottom should match the order in "Expected order" from left to right. (Nodes 0-8, where 0 is a group node containing children 1-6, and 6 is a group node containing children 7-8)
5. Click the icon button. This moves group node 6 to index 0 in group 0's children.
6. Observe that the tree structure now no longer matches the "Expected order" text. While group node 6 has moved to the correct position in the tree, its children have not moved with it, and child node 1 has moved to the bottom. The "Expected order" text, which is determined within the tree's build method and operates off the same list of widgets passed to the tree, reflects the expected tree structure.
7. Comment out either the if clause in line 113 or all of line 116 in tree.dart and do a Hot Restart. This either removes or refreshes the GlobalKeys passed into each row in the tree.
8. Observe the original tree structure and "Expected order" text.
9. Click the icon button.
10. Observe that the tree structure now appears as expected, and matches the "Expected order" text.

Any idea what's going on here? Am I violating some assumption about GlobalKeys in how I'm using them, or does this look like a Flutter bug?

Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.10-pre.60, on Mac OS X 10.14.6 18G2022, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

**Comment by gspencergoog** [comment]
Looking at this, it seems like what is happening is that because the children have keys, and didn't actually change (their `setState` wasn't called, so they weren't marked dirty), the `Column` holding them doesn't think they need to be rebuilt and/or relocated in the list.  When they don't have keys, then the `Column` tries to re-use widgets that it already has, and so it resets the contents of the children to match the new data, and so they appear to "move" but in reality the Row widget at that position is just getting its children list reset.

BTW, it doesn't matter if you use a `ValueKey` or a `GlobalKey`, so it's not `GlobalKey` related.

**Comment by gspencergoog** [comment]
Here's a DartPad with this code in it: https://dartpad.dartlang.org/82c2cd997094e23af2af4611cc0aa0fc

**Comment by gspencergoog** [comment]
@Hixie, is this how `Key`s are supposed to work? The main thing is that when the `Column` is being rebuilt, it's not reordering the `Column` children, even though if you look at the `debugDumpApp` output, the nodes have moved in the `Column`'s children list.

**Comment by Hixie** [comment]
I simplified that to: https://dartpad.dartlang.org/ff07a1203684296acde4b543d7664a2f
That made the debugDumpApp output more readable.

The same instance of the model object is passed to the Tree each time it is built. In principle, the Tree could notice that the instance hasn't changed and thus not rebuild. In practice, it does rebuild regardless, so this bug does not manifest in the application, but that is merely luck.

There does seem to be a real bug here. I don't really understand what's going on, and ran out of time to debug it. Hopefully my work on the dartpad above helps.

cc @goderbauer

**Comment by goderbauer** [comment]
Interesting. I am going to take a look at this.

**Comment by goderbauer** [comment]
Here's what's happening:

The Column puts each child Element into a [slot](https://master-api.flutter.dev/flutter/widgets/Element/slot.html), which identifies where a given child is located in the Column's list of Element children. The Column uses the previous child as the slot indicator essentially creating a linked list. Initially, the list of child Element of the Column element look like this:

E0 is in slot null (first child)
E1 is in slot E0
E2 is in slot E1
E3 is in slot E2
E4 is in slot E3
E5 is in slot E4
E6 is in slot E5
E7 is in slot E6
E8 is in slot E7

Now we provide a new list to the Column widget, where the widgets W6, W7, and W8 have been moved to behind W0. Since all nodes are keyed, the old elements get reused and their slots are updated in RenderObjectElement.updateChildren [1] (or more specifically Element.updateChild [2]) giving us this child element list of the Column element:

E0 is in slot null (first child)
E6 is in slot E0
E7 is in slot E6
E8 is in slot E7
E1 is in slot E8
E2 is in slot E1
E3 is in slot E2
E4 is in slot E3
E5 is in slot E4

As we can see from this list, only the slots for elements E6 and E1 have changed. Element.updateChild will therefore only call Element.updateSlotForChild for those two elements. Ultimately, this will cause the two RenderObjects backing those two elements to move to their new position by calling MultiChildRenderObjectElement.moveChildRenderObject:

https://github.com/flutter/flutter/blob/72d2a8c5c17382569ef0e6e20f3890d94b05677e/packages/flutter/lib/src/widgets/framework.dart#L5818-L5824 

This will call ContainerRenderObjectMixin.move:

https://github.com/flutter/flutter/blob/72d2a8c5c17382569ef0e6e20f3890d94b05677e/packages/flutter/lib/src/rendering/object.dart#L3216-L3227

This is were it gets interesting now. This method removes the RenderObject R6 from its child list and inserts it after R0 (`after` is the RenderObject that belongs to the slot of the element backing R6). In a later call it will also remove R1 from its childlist and re-insert it after R8.

The RenderObject linked child list has now changed from

R0 -> R1 -> R2 -> R3 -> R4 -> R5 -> R6 -> R7 -> R8

to

R0 -> R6 -> R2 -> R3 -> R4 -> R5  -> R7 -> R8 -> R1

It is no longer in sync with the order in the element child list. So, yeah, there's definitely a bug here. In this case, when we move a RenderObject we also need to be moving all following RenderObjects. I'll investigate a fix tomorrow.

[1] https://github.com/flutter/flutter/blob/72d2a8c5c17382569ef0e6e20f3890d94b05677e/packages/flutter/lib/src/widgets/framework.dart#L5382
[2] https://github.com/flutter/flutter/blob/72d2a8c5c17382569ef0e6e20f3890d94b05677e/packages/flutter/lib/src/widgets/framework.dart#L5382
