### ISSUE TITLE
allow `FormFieldState` the option to not validate initially when `autoValidate` is True.

### ISSUE THREAD

**Issue by tjonganthony** [flutter/flutter#48876]
## Use case

When `FormFieldState` has `autoValidate` as `true`, it will validate upon `build`.
See: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/form.dart#L419

This is a different behaviour than `FormState` when `autoValidate` is set to `true` where each individual field won't be validated upon build.
However, even when `FormState`'s `autoValidate` is set to `true`, if a `FormField` has `autoValidate` set to `true`, then that `FormField` will be validated upon build.

## Proposal

Since this might be a breaking changes for people who depends on validation upon build, I suggest to add an option to opt out for validation upon build on `FormFieldState`.

However, if we are okay with breaking build, it would be better if we can standardise the behaviour between `FormFieldState` and `FormState`.

**Comment by justinmc** [comment]
You're right, I'm seeing the same behavior and it seems confusing to me.  Specifically:

When autovalidate on a field is true, the field will be validated immediately when created and on any change. When autovalidate on a Form is true, all form fields will be validated after the first character is entered in any field, and on any change after that.

I think I would support standardizing this behavior if we can get away with making a breaking change.  I would say that the behavior of Form should be changed to be the same as a field, so that it is immediately validated and validated on every change.

@goderbauer @HansMuller Do you guys have any thoughts on this?

**Comment by justinmc** [comment]
If this [onInteraction proposal](https://github.com/flutter/flutter/pull/48155#issuecomment-583150157) is implemented, then autovalidate will be deprecated and this issue should be obsolete.
