### ISSUE TITLE
Keyboard focus is lost when popping multiple screens with Navigator.popuntil

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#48903]
@goderbauer
@gspencergoog
@lorenzOliveto

Steps to reproduce:
- Attach a keyboard to an Android device
- push multiple Widget in the navigator stack
- going back to the root with Navigator.popUntil

The keyboard focus is lost and it doesn’t respond anymore. You can find an example in this repository, https://github.com/lorenzOliveto/flutter_keyboard_navigation_issues (pop_until_example.dart).

**Comment by gmoraja** [comment]
@gspencergoog we tested this in the latest master but we haven't noticed any difference in the behavior, should we open a new issue or wait for an update?

**Comment by chunhtai** [comment]
Taking a look

**Comment by chunhtai** [comment]
Ok, I found the issue, My fix does not fix all the possible use cases.
Will put up another pr to make the focus traversal more robust

**Comment by goderbauer** [comment]
@gspencergoog Does #50831 fix this or how does it relate to this issue?

**Comment by gspencergoog** [comment]
It incorporates part of @chunhtai's fix (finding a focusable parent to focus), but I should probably incorporate the test that @chunhtai created here into that PR too.

**Comment by gspencergoog** [comment]
But yes, https://github.com/flutter/flutter/pull/50831 fixes this.

**Comment by HerrNiklasRaab** [comment]
Hey @gspencergoog, this change seems to break this plugin, just try the example:
https://github.com/drogel/keyboard_dismisser

Is there any migration needed?

**Comment by gspencergoog** [comment]
@HerrNiklasRaab It looks like there is a fix for the keyboard_dismisser that works for the case you want.

That particular change in the focus code was made because without a valid scope for the node requesting to be unfocused, there isn't a way to determine what the next focused node should be. Unfocus is not about losing focus, it's about transferring focus to another node, since there can't really be a case where nothing has focus, or focus traversal stops working.

Because of this, you may notice that with keyboard_dismisser as it is now, that once the soft keyboard is dismissed, pressing TAB when there is a hardware keyboard connected will no longer move to the next available focus node until focus is explicitly given to a node that is in the focus tree.

This may not matter to you, since you're clearly interested in the mobile experience, but it does matter in other contexts (e.g. on the web, or a desktop app).
