### ISSUE TITLE
Appbar is not focusable with a keyboard when used with PageView and FocusScope

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#48904]
@goderbauer
@gspencergoog
@lorenzOliveto

We’re using a FocusScope widget inside every page of a PageView. When a keyboard is attached to an Android device and the focus is moved to the PageView, the AppBar is no more focusable. 
You can find an example in this repository, https://github.com/lorenzOliveto/flutter_keyboard_navigation_issues (appbar_actions.dart)

**Comment by gspencergoog** [comment]
Can you describe why you are using a `FocusScope` inside every `PageView`?

**Comment by lorenzOliveto** [comment]
I updated the repository with an example more similar to our use case; we basically have a PageView that's not scrollable by the user but only using a page controller, so the `physics` of the is a `NeverScrollableScrollPhysics` and the page is changed with `_pageController.animateToPage(...)`.
 
We inserted the FocusScope to every page so when the page is changed the corresponding `FocusScope` requests the focus, otherwise the keyboard focus remained in the previous page and when you move it the `PageView` was scrolled to the page that had the focus previously. 

Is this usage of `FocusScope` wrong? How can we achieve what I described?

**Comment by gspencergoog** [comment]
`FocusScope` is used to prevent the focus from leaving the scope.  For instance, it is used on a modal dialog so that other controls on the page aren't focusable, and it is used on a `Stack` sometimes to prevent hidden components from being focusable.

A user can focus another item in another scope, and then be restricted to that scope, but they can't tab from one to the other.

In your example, simply switching to a `Focus` widget instead of a `FocusScope` widget will do what you want, I think.

**Comment by lorenzOliveto** [comment]
Thanks @gspencergoog, I switched to `Focus` and it's now working.
