### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by Juliotati** [flutter/flutter#49018]
<img width="960" alt="2020-01-17 (1)" src="https://user-images.githubusercontent.com/59662912/72582894-2c92cc00-38dc-11ea-9305-2947930ebcf3.png">

this is what I have been getting when trying to migrate to AndroidX, please help.

**Comment by JarvanMo** [comment]
@Juliotati Hi, please right click on android folder of your flutter project, then select `Open Android module in AndroidStudio`. After that you can do the migration.

**Comment by iapicca** [comment]
Hi @Juliotati 
in the hope that @JarvanMo 's solution will solve your issue,
please note that since the latest stable version `androidx` is used by default,
moreover
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Comment by Juliotati** [comment]
> @Juliotati Hi, please right click on android folder of your flutter project, then select `Open Android module in AndroidStudio`. After that you can do the migration.

@JarvanMo Hi, I cannot find that option on my screen. Is there anything I am missing?

<img width="960" alt="2020-01-17 (2)" src="https://user-images.githubusercontent.com/59662912/72620694-b3c15d80-3937-11ea-8752-94eb8e656130.png">

**Comment by JarvanMo** [comment]
@Juliotati It seem you have issues with the `Flutter` option, it's grey. Anyway, you can open android folder with AndroidStudio directly.
