### ISSUE TITLE
[web]: my web application with flutter is too Slow and not smooth 

### ISSUE THREAD

**Issue by mehrdaddolatkhah** [flutter/flutter#49058]
when I run my flutter project it works perfectly on android. but on the web, It's slow and laggy. I want to make all front (Web, Android, IOS) for my project with flutter. and It's really important for me my web app with flutter work perfectly. and this is my version:

`version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter`

I do something wrong or flutter in the web part still need work to be better and use it in a real-world project? right now I can use the web in flutter or I must wait?

**Comment by Zazo032** [comment]
Web support is still in beta so performance may not be fully polished yet. Which version of Flutter are you using (`flutter doctor -v` output)? Are you running it using `flutter run --release -d chrome`?

**Comment by mehrdaddolatkhah** [comment]
@Zazo032 Thank you. with 
`flutter run --release -d chrome` I have really better performance. and this is my flutter version 
`Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.6 at
      /home/mehrdad/Workspace/Flutter/SDK/flutter
    • Framework revision 18cd7a3601 (5 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
`
if I want to make it for release and for example test it on Surge what command I must run?
I run this command:
`flutter build web` and use Surge but it's laggy. 
http://quizzical-gun.surge.sh/#/
do you think this is have lag Or that I'm very sensitive?

**Comment by Zazo032** [comment]
Do it using `flutter build web --release` (not sure which is the default mode for web). You can read more about these modes here: https://flutter.dev/docs/testing/build-modes

**Comment by mehrdaddolatkhah** [comment]
@Zazo032 Sure, thanks for your help.

**Comment by dutch-game-studio** [comment]
Dit flutter build web --release help with the performance @mehrdaddolatkhah

**Comment by michael-ottink** [comment]
Dit flutter build web --release help with the performance @mehrdaddolatkhah ?

**Comment by Lurzapps** [comment]
> Dit flutter build web --release help with the performance @mehrdaddolatkhah ?

yeye

**Comment by qiwang97** [comment]
> Dit flutter build web --release help with the performance @mehrdaddolatkhah ?

it does not work for me.

**Comment by mrgulshanyadav** [comment]
I'm not sure about the earlier version on flutter web, but in Flutter 2.0.6, it is not working, the loading time is very slow for the first time visiting the url

**Comment by Ahmadkazbar** [comment]
i have the same problem is very slow in mobile browser @mrgulshanyadav

**Comment by steeling** [comment]
10+ seconds for initial loading time as well for me

**Comment by dernoun** [comment]
Running the app on release mode give a better performance, but how about launching the app on debug mode, what is launcher configuration should I use, even with F5 take a long time ?

**Comment by on1yyou** [comment]
yeah, encountered slow first load too: two page site with all the blows and whistles gives about 12+ seconds to load. Stripped one page with app bar, firestore attached and single button in the middle gives about 5 seconds if deployed with firebase. Is there any methods to improve it? or better drop it and go with next.js?

**Comment by kiaxseventh** [comment]
Do not the Flutter development team really want to think fundamentally about this problem?
This problem basically exists
And the problem is not with release or debug mode
In the past, they answered that the problem is because the web version is in beta
But there is still the problem of slowness in versions 2 and 2.2

 do not request a sample please
you can see this problem in any example

# first load is slow 

# scroll and animations and pageview on android or ios chrome or safari is very slow

# HTML renderer and  canvaskit are both slow on mobile devices
flutter web basically has problem
flutter web is not ready for premium projects
Flutter Development Team Please tell me if you have a plan to fix it or not ?

thank you

**Comment by pilgrim1385** [comment]
I have a simple flutter web project with only 2 pages. And deploy it in ECS(cloud server).
It takes almost 20s to load the first view in browser. Because main.dart.js is over 2M, and MaterialIcons-Regular.otf is 1.3M, but my ECS server is only 1Mbps.
I changed index.html which "flutter build web" generated, uploaded main.dart.js to my OSS(Object Storage Service) server, and link it in index.html.
Now it takes 10s to load the first view.
But MaterialIcons-Regular.otf still takes 9.97s, and I can't find a way to deploy it in other place except my ECS.
![1625824553904](https://user-images.githubusercontent.com/8338907/125060488-01f38f00-e0df-11eb-943f-7212ca87f916.jpg)

For a web page, it's too long for 10s.
How to resolve this problem? Or is there a best practice for flutter web deploy?

**Comment by on1yyou** [comment]
dont waste your time with flutter web if you are doing something for web - it is a horrible choice for the moment as I learned myself. Switch to next js (that was my option and I'm totally happy with it now)

**Comment by kiaxseventh** [comment]
dear @mehrdaddolatkhah please re open this issue
thank you lot of

**Comment by spreadbusiness** [comment]
it's very slow

**Comment by srhtytr7** [comment]
I am not surprised with this comments.I finished a project on flutter web right now.  Scrolls are laggy and inconsistent. Loading time is a joke. I'd like to know that my site needs 10s loading time before i spent 3 months. As developing the site i always thought its a debug issue and i left the performance to the end. I was really upset when found out its a chronic issue. Its really a shame. At the end,  I am afraid i have agree with @on1yyou. Flutter Web is a poor choice for now. I hope flutter teams takes action about this stuff.

**Comment by kiaxseventh** [comment]
dear @filiph can you see this issue ?
thanks

**Comment by apieceofcode1801** [comment]
please re-open or open new issues. I think the Flutter team will not take a look if it's closed.
