### ISSUE TITLE
Scrolling horizontally right after scrolling vertically is not working correctly with bouncing effect!

### ISSUE THREAD

**Issue by maddada** [flutter/flutter#49090]
## Description:
When scrolling vertically, then scrolling horizontally an issue arises. The problem is that it gets stuck scrolling vertically instead of switching to scrolling horizontally, even if my vertical scroll is completely sideways.

## Demonstration of the issue in the live app:
https://photos.google.com/lr/photo/AMyoWWkmZlaVeD1LYvyngdsAXlnILPyJLN-YTa9zo6I63PkVkHVVS2dny7Ll8Q-v0Tef7H74TZciNWCGg_RR-pKkHu-AiiXqhQ

## Steps to Reproduce
Here's a gist with the code to reproduce the issue:
https://gist.github.com/maddada/fee32bf26fb61c5d4e52735dc148cbe2
or
https://dartpad.dev/fee32bf26fb61c5d4e52735dc148cbe2

Just scroll up or down, then try to scroll the vertical list (it won't work unless the vertical scroll has completely died down)

## Version:
I'm on the latest stable.

**Comment by VladyslavBondarenko** [comment]
It doesn't look like an issue with flutter, because outer vertical scroll view will handle gesture before inner horizontal scroll view. I can't see difference with or without bouncing physics.
Closing. 
@maddada If you disagree please write in the comments and I will reopen it.

May be related https://github.com/flutter/flutter/issues/53737
