### ISSUE TITLE
Qt project for Desktop app

### ISSUE THREAD

**Issue by aissat** [flutter/flutter#49146]
## One code For all NATIVE desktop app
Everyone knows **Qt cross-platform** why don't use inside flutter desktop app 
**one code For all NATIVE desktop app** this will be amazing

**Comment by stuartmorgan** [comment]
Qt is primarily a widget toolkit, and that whole portion of Qt would be irrelevant for Flutter since Flutter controls drawing directly, and itself a widget toolkit.

Implementing the embedding with Qt would mean layering a cross-platform abstraction on top of another cross-platform abstraction, which would limit our flexibility and almost certainly affect our ability to tune performance. It would either add complexity to platform view support, as well as to plugins.

Other than presumably being slightly less code to maintain in the embedding itself, which isn't something that users of Flutter need to care about, I'm not clear on what advantages this would provide. Can you give some specific examples of benefits that would be provided by using Qt?

**Comment by aissat** [comment]
Nice. and thanks for answering.
For example now I'm developing an app for Linux, macos and windows now And I need to write native code for every platform that mean have 3 project: 
Macos xcode project 
Windows visual studio project
Linux project
but when using QT project just need one project 
Thanks 😊

**Comment by stuartmorgan** [comment]
> I need to write native code for every platform

Can you give specific examples of native code that you are writing for a Flutter app that would be simpler using Qt?

> that means have 3 projects

Projects and toolkits are largely orthogonal. For instance, we could use GN or CMake on all three desktop platforms without changing anything else about the current approach. There are advantages to a unified build system, but also drawbacks (e.g., in terms of ease of integration with existing native code). Again, can you provide specific examples of problems you are having that would be eliminated by having one project?

**Comment by stuartmorgan** [comment]
Closing due to lack of response; absent more details it's not clear what use cases this would improve.

**Comment by damilolarandolph** [comment]
I might be a little late but how I see it, if flutter was embedded in qt, we would things like clipboard support, tray icons, dark mode , gesture support on touch enabled screens etc for free. Unless the hurdles that come with embedding in qt far outweigh these.

**Comment by stuartmorgan** [comment]
> if flutter was embedded in qt, we would things like clipboard support, tray icons, dark mode , gesture support on touch enabled screens etc for free.

This is not the case; everything you listed requires embedding code to implement regardless of the APIs they are implemented with.

**Comment by damilolarandolph** [comment]
> > if flutter was embedded in qt, we would things like clipboard support, tray icons, dark mode , gesture support on touch enabled screens etc for free.
> 
> This is not the case; everything you listed requires embedding code to implement regardless of the APIs they are implemented with.

Oh thank you for the clarification.

**Comment by psstoyanov** [comment]
Out of curiosity, wouldn't a Qt shell allow for easier integration of multimedia such as video or audio playback?
