### ISSUE TITLE
Rasterizer in flutter, draw lot of points

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#49216]
I am creating a rasterizer in flutter. So basically I want to texturize triangles and models. I am using now the CustomPainter class for this.

All is good, but when I have to draw a lot of points to the screen it is very laggy. 

I just use the **drawPoints** method with a single point because I need to draw points with different colours. 

Any way to do something like drawing to a frame buffer like in opengl or just bypass the points and the colours to a function in one batch?

Any way to speed up the process on a lot of points?

**Comment by cmkweber** [comment]
I suggest looking into [drawVertices](https://api.flutter.dev/flutter/dart-ui/Canvas/drawVertices.html) which will allow you to apply vertex colors and draw in one batch.

**Comment by klaszlo8207** [comment]
I will try tomorrow, but

https://developer.android.com/guide/topics/graphics/hardware-accel#unsupported

Is it not a probleme?

**Comment by cmkweber** [comment]
That is for android graphics, Flutter utilizes Skia - you can see the underlying implementation here:
[https://skia.org/user/api/SkCanvas_Reference#SkCanvas_drawVertices](https://skia.org/user/api/SkCanvas_Reference#SkCanvas_drawVertices)

**Comment by klaszlo8207** [comment]
Thanks I will try that :)

**Comment by klaszlo8207** [comment]
I tried it but this is slow too... can you show an example? 

I have a texture and uv coords with vertices...

**Comment by cmkweber** [comment]
If it is just solid colors you don't need a texture and can use the colors parameter in [Vertices](https://api.flutter.dev/flutter/dart-ui/Vertices/Vertices.raw.html).

As for speed, it depends on how many points you are trying to draw and if they are static or not. If they are dynamic there is always going to be the issue of uploading all the points to the GPU as they change.

As for examples, this is a small sample I created recently to demonstrate supersampling, but there are more thorough examples elsewhere.
[https://gist.github.com/cmkweber/c17aae8fa48a4853a87f242835cb65cb](https://gist.github.com/cmkweber/c17aae8fa48a4853a87f242835cb65cb)

It would be better if I had understood what you are trying to accomplish because it is still a little unclear - you may also have better luck on stackoverflow as this is mainly for flutter issues and bugs.

**Comment by klaszlo8207** [comment]
error: The method 'ImageFiltered' isn't defined for the class 'ViewState'. (undefined_method at [flutter_app_testxxx] lib\main.dart:44)

**Comment by cmkweber** [comment]
ImageFiltered is new and probably hasn't made it to dev or stable yet, you can switch to master or just remove that part...

**Comment by klaszlo8207** [comment]
Now my algorith looks like this:

https://github.com/davidmigloz/3d-engine/blob/master/src/main/java/com/davidmiguel/engine_3d/utils/DrawUtils.java


And I using a simple canvas.drawPoints algo with point from this class. Colours come from a texture map. 

It is very slow when I have a lot of pixels. Only fast when we have few point in the screen (and also few vertices/triangles)

So my algo is very goos when I have 10.000 colored points for a cube (it is 40-60 fps on my Huawei Mate 20 pro, with a 10ms delay for redraw the CustomPainter)

when I zooming in, and my cube become bigger: 

~25.000 colored points for my cube: fps 30
~50.000 colored points for my cube: fps 12
~100.000 colored points for my cube: fps 3

**Comment by klaszlo8207** [comment]
I made a video

https://www.youtube.com/watch?v=q4wVxLKzqqs&feature=youtu.be

**Comment by cmkweber** [comment]
Can you post a reduced sample of your dart implementation? You should be able to drawVertices with a full buffer (65,535 triangles) once per frame easily - for 100k you would need two drawVertices calls but it should still be performant.

You can also check this demo I made awhile back here demonstrating drawPath vs drawVertices: [https://github.com/flutter/flutter/issues/33849](https://github.com/flutter/flutter/issues/33849)

**Comment by klaszlo8207** [comment]
I am Hungary, so 21:50 is the time here, tomorrow I can see the code. But this will be a flutter library, so I want to upload to github and dev pub.

**Comment by klaszlo8207** [comment]
https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer

Here is the code

**Comment by klaszlo8207** [comment]
I did it via drawVertices, very cool. :) is it drawing in the opengl es via skia? Any way to bypass normals to it?

**Comment by cmkweber** [comment]
Hey KL - I'm not sure I have a chance to go through all of this since it's not a reduced sample, but here are some things I found while looking through object3d_viewer:

- [build - setState](https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer/blob/ed563679b5d368d57a48d0f8f19c154a461ea348/lib/obj3d/object3d_viewer.dart#L261) Instead of refreshing the state through the build and recreating your CustomPainter each frame, create your CustomPainter once, extend it from ChangeNotifier and notify listeners. See here about triggering repaints: [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter-class.html)
- [Measing fps](https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer/blob/ed563679b5d368d57a48d0f8f19c154a461ea348/lib/obj3d/object3d_viewer.dart#L543) A more reliable way to monitor fps would be to use the timings callback [addTimingsCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addTimingsCallback.html)
- Since you are computing the vertex locations in software, you will have to upload them to the GPU dynamically, but flutter only exposes a static buffer (Vertices and Vertices.raw). A slight optimization would be to only regenerate the vertices buffer when the view changes.

Those are my suggestions, but others may be able to suggest additional alternatives...

**Comment by cmkweber** [comment]
Skia supports a few different backends OpenGL, Vulkan, Metal.
I'm not aware of a way to supply normals.

**Comment by klaszlo8207** [comment]
> 
> 
> Hey KL - I'm not sure I have a chance to go through all of this since it's not a reduced sample, but here are some things I found while looking through object3d_viewer:
> 
>     * [build - setState](https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer/blob/ed563679b5d368d57a48d0f8f19c154a461ea348/lib/obj3d/object3d_viewer.dart#L261) Instead of refreshing the state through the build and recreating your CustomPainter each frame, create your CustomPainter once, extend it from ChangeNotifier and notify listeners. See here about triggering repaints: [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter-class.html)
> 
>     * [Measing fps](https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer/blob/ed563679b5d368d57a48d0f8f19c154a461ea348/lib/obj3d/object3d_viewer.dart#L543) A more reliable way to monitor fps would be to use the timings callback [addTimingsCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addTimingsCallback.html)
> 
>     * Since you are computing the vertex locations in software, you will have to upload them to the GPU dynamically, but flutter only exposes a static buffer (Vertices and Vertices.raw). A slight optimization would be to only regenerate the vertices buffer when the view changes.
> 
> 
> Those are my suggestions, but others may be able to suggest additional alternatives...

Thanks:)

**Comment by cmkweber** [comment]
If there's nothing left here can you close this issue and your other issue [https://github.com/flutter/flutter/issues/49216](https://github.com/flutter/flutter/issues/49216) that linked to this?

**Comment by klaszlo8207** [comment]
Can you help me how to use addTimingsCallback? Any example?

**Comment by cmkweber** [comment]
I don't have an example, but you should be able to get it through SchedulerBinding.instance and then just add your callback through addTimingsCallback.

**Comment by klaszlo8207** [comment]
Thanks, I updated the code : https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer/blob/master/lib/main.dart

:P Now using notifyListeners

Finally I ended up just remove the fps counter

Now I can handle textures and normals/colors/shading too.  Thanks!

**Comment by klaszlo8207** [comment]
Also I create some fun with fbx files: 

The code coming soon: https://www.youtube.com/watch?v=hTnkwEGFu9k :P
