### ISSUE TITLE
HttpClient SecurityContext stream slow with client certificate

### ISSUE THREAD

**Issue by dubbelpunt** [flutter/flutter#49392]
Hi,

When I stream an IP-cam over a client authenticated connection, the response is very slow.
Via a browser on a computer, the response is good.

This is the code I have for the authentication:
```dart
ByteData data = await rootBundle.load('assets/mycert.pfx');
sslbytes = data.buffer.asUint8List();
SecurityContext sslcontext = new SecurityContext(withTrustedRoots: true);
sslcontext.useCertificateChainBytes(sslbytes, password: crtpasswd);
sslcontext.usePrivateKeyBytes(sslbytes, password: crtpasswd);
_httpClient = new HttpClient(context: sslcontext);
final request = await _httpClient.getUrl(Uri.parse('https://url_to_ipcam'));
final response = await request.close();

 _subscription = response.listen((data) async {
	...
}
```

**Comment by dnfield** [comment]
In its current form, this looks like a Dart SDK bug.

It would be worth verifying that this is still slow from a command line app in Dart.

It would also be worth verifying whether it's still slow without the security context in Dart.

Either way, I'm going to close this since it's not a Flutter bug - please feel free to open a similar issue in github.com/dart-lang/sdk

**Comment by mraleph** [comment]
@dubbelpunt when filing an issue at dart-lang/sdk please make sure to include fully runnable reproduction for your issue otherwise it would be hard to help you.
