### ISSUE TITLE
Create a convention for naming engine C++ test files

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#49648]
C++ tests in the engine don't necessarily follow a convention today.

This can make the internal roll a little more difficult than it has to be sometimes,  requiring the roller to manually update scripts that copy/move/exclude test files in the roll.

/cc @chinmaygarde @cbracken

**Comment by chinmaygarde** [comment]
Why does engine naming convention affect rollers?

**Comment by dnfield** [comment]
There's an internal file that is using glob patterns to match test files.  CC'd you on internal thread.

**Comment by chinmaygarde** [comment]
Highly in favor of more convention and this proposal in particular seems extremely reasonable.

However, having internal process depend on the name or structure of files on the filesystem is something I would advise against. In the past we have been bitten by rolls a long way down failing because of changes to the location of a file on disk. A convention is not a contract or a replacement for one. Depending on the existence of one is trading short term convenience for overall brittleness in the system. If you are want to exclude test files in the internal process, please enumerate them explicitly.

**Comment by dnfield** [comment]
The system we have today enumerates them mostly explicitly, but it then requires manual updates when things change by people who are not familiar with the changes.

What if we maintained a list in the engine repo of test files?

**Comment by chinmaygarde** [comment]
> What if we maintained a list in the engine repo of test files?

We do. They are in BUILD.gn files. They all should be in `testonly = true` exclusive targets.

**Comment by chinmaygarde** [comment]
I checked the names of existing files and they seem to have the `test`, `tests`, `unittest` or `unittests` suffix. This doesn't seem particularly problematic. That is just for TUs that contain test cases though. There are other TUs that contain code that is shared between multiple harnesses (`test_gl_surface.cc`, `test_metal_surface.cc`, `_main.cc`, etc) which follows the convention of naming the TUs based on the name of the class.

It is not clear which file is not following convention. Can you list the same?

**Comment by dnfield** [comment]
It was https://github.com/flutter/engine/blob/master/shell/common/shell_test_platform_view_gl.h that required manual changes for the last roll

**Comment by chinmaygarde** [comment]
That’s not a test. Just a utility that is used to build a fixture used by tests. It also seems to follow the standard naming convention. Which bring me back to my original point. Glob-ing files and filtering tests or their dependencies based on solely their names is going to be very brittle. Whether the extra manual intervention needed due to this brittleness is worth building a system that consults the way in which the primary build system specifies its test files is your call. 

Since there is no deviation from convention, I am closing this issue as wont-fix.
