### ISSUE TITLE
CircleAvatar doesn't clip child

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#4964]
If we want to use `CircleAvatar` to represent user accounts with profile pictures, we need to have a way to clip images passed to `CircleAvatar` as a child. Right now, it does no clipping so you would need to passed a clipped image inside.

**Comment by HansMuller** [comment]
Clipping the child isn't efficient and currently we don't antialias the circular clip. I think that a better option would be to give CircleAvatar a backgroundImage attribute which would just be passed along to the BoxDecoration that's already being created. The backgroundImage will be rendered correctly vis the backgroundColor and the child and it will be rendered efficiently.

The docs for CircleAvatar should mention that if an arbitrary widget child is specified, rather than a Text(singleInitialCharacter), you'll want to wrap it with ClipOval if it's possible that it will overflow.

**Comment by dragostis** [comment]
That makes sense, but are profile pictures already circles on Android for example? If not, `ClipOval` might be necessary for all profile pictures, so it might be a good idea to have an easy way to just use them without worrying about making them circles.

**Comment by abarth** [comment]
A backgroundImage with shape of BoxCircle will be a circle.  It's just a more efficient way to clip the image.
