### ISSUE TITLE
fatal error: module 'firebase_core' not found

### ISSUE THREAD

**Issue by infonotics** [flutter/flutter#49667]
Just created a new flutter project, added google-services-info.plist file to iOS and added firebase_core to pubspec.yaml. Ran the project and got this error.  
`Error: fatal error: module 'firebase_core' not found  @import firebase_core;`

I have searched a lot on the stack overflow and gitlab. Tried all the workarounds like flutter clean, update repo, delete pod and reinstall pod but still got no success in resolving this error.

This has blocked me for 5 days. Unable to find anything on this. Please help.

Link to my project on GitHub. : https://github.com/infonotics/stocklyticsSO Do add your own googleService-Info.plist file to the Runner folder. I have removed my file for security reasons.

Thanks in advance.

**Comment by iapicca** [comment]
Hi @infonotics 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
