### ISSUE TITLE
Devices are not listed, and showing below exception on mac

### ISSUE THREAD

**Issue by vethemail001** [flutter/flutter#49678]
Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17

**Comment by VladyslavBondarenko** [comment]
Hi @vethemail001 
This is the meaning of the error https://github.com/flutter/flutter/issues/44898#issuecomment-577475787
There is an open issue https://github.com/flutter/flutter/issues/49375 about giving message to error code
Possible solution: https://github.com/flutter/flutter/issues/36789#issuecomment-516510908
Closing the issue as duplicate
If you believe that your issue is different from all existing, 
please write in the comments and I will reopen it
Thank you
