### ISSUE TITLE
[local_auth] Allow authentication for devices without biometrics

### ISSUE THREAD

**Issue by kennethj** [flutter/flutter#49703]
Allow local authentication for devices without biometrics.

Ideally, a method (`LocalAuthentication().authenticate()`) that would defer to the OS to determine the proper authentication type.

iOS:
https://developer.apple.com/documentation/localauthentication/lapolicy/lapolicydeviceownerauthentication?language=objc

Android:
https://developer.android.com/training/sign-in/biometric-auth#biometric-or-lock-screen

**Comment by vanlooverenkoen** [comment]
@VladyslavBondarenko is it possible to already review this pr? This is something we need in our current application

**Comment by VladyslavBondarenko** [comment]
@vanlooverenkoen you can ask assigned for the review person in the pr conversation

**Comment by vanlooverenkoen** [comment]
@VladyslavBondarenko there is nobody assigned yet.

**Comment by VladyslavBondarenko** [comment]
@vanlooverenkoen sorry, ambiguously said, I meant @mehmetf in reviewers

**Comment by kennethj** [comment]
@vanlooverenkoen 
You could use this fork. It was created as a stopgap until this could be reviewed and merged.
https://pub.dev/packages/local_auth_device_credentials

**Comment by REKURDennis** [comment]
Sadly on iOS the passcode as fallback is not shown for FaceID users. This is because the plugin sets 
`context.localizedFallbackTitle = @"";` hardcoded and is not configurable. The title should be configurable to show a customised title or disable it. 

https://developer.apple.com/documentation/localauthentication/lacontext/1514183-localizedfallbacktitle?language=objc

**Comment by REKURDennis** [comment]
There is another problem:
next to getAvailableBiometrics there should be a second method getAvailableAuthenticationMethods or similar. Because it should be possible to check if the user either enrolled any biometric method, or a code/pattern/what_so_ever. "isDeviceSupported" returns true even if the user hasn't enabled any authentication. If he then turns on authentication for my app he is locked out and has to know that he should set at least a device passcode to get in again.

**Comment by stuartmorgan** [comment]
Looks like this didn't get closed as fixed when the PR landed; closing.

@REKURDennis Please file new issues for follow-ups.
