### ISSUE TITLE
Security issue ELF binaries do not enforce secure binary properties

### ISSUE THREAD

**Issue by liapalaria** [flutter/flutter#49801]
Hello,

When running security scans for any Flutter Android APK the issue that ELF binaries do not enforce secure binary properties is reported.  (https://www.ostorlab.co/). 
It specifies that no RELRO and no canary are found for libapp.so binaries. 

RELRO is enforced since Android 4.3 https://source.android.com/security/enhancements/enhancements43 and when scanning APKs that don't use Flutter the issue is not reported.

The recommendation to add cppFlags `-fstack-protector-all` does not solve the issue.

```
defaultConfig {
        externalNativeBuild {
            cmake {
        cppFlags "-fstack-protector-all"
            }
        }
}
```

My question is why is the Flutter engine generating the ELF binaries without a stack canary. Is there a compensation mechanism in place for this?

**Comment by jay-web** [comment]
Hi, I am facing the same vulnerability issue in the flutter android app while scanning from Ostorlab "ELF binaries do not enforce secure binary properties".

Did anyone get the solution for the same?

**Comment by xster** [comment]
@jason-simmons seems relevant. Would you like to read in on it a bit and see if there are knobs we should turn in our gn?

**Comment by jason-simmons** [comment]
`libapp.so` is not produced by the engine build process - it contains the app's compiled Dart code and is generated by Dart's `gen_snapshot`

**Comment by xster** [comment]
oops, misread the question. @mraleph can you see if these Android binary security enforcements are applicable to the dart compiler?

**Comment by mraleph** [comment]
Short answer to this would be:

- We don't use normal GOT/PLT mechanism at all so RELRO does not really make much sense. Our equivalent of GOT is pool pointer, which unlike GOT is located in a randomised location so it is harder to exploit. Theoretically we could make our pool read-only similar to RELRO - but I don't think it is worth it.
- We don't generate stack canaries because unlike C++ we don't really have stack allocated arrays (primary source of stack smashing in C/C++).

Note that in general when you write _pure_ Dart (and don't use dart:ffi) - you already have much stronger isolation guarantees than any C++ mitigation can provide - simply because pure Dart code is managed language, so things like buffer overruns do not exist.

**Comment by xster** [comment]
Thanks @mraleph. I wonder if we can document these anywhere such as https://dart.dev/faq or
https://github.com/dart-lang/sdk/wiki or would it be too niche?

@liapalaria did that answer your question?

**Comment by mraleph** [comment]
@xster I think it would be too niche to document it - but if we see a significant increase in people asking about this we should probably document it somewhere directly on the https://flutter.dev.

**Comment by xster** [comment]
SG. This bug can serve as documentation in the meantime :D

**Comment by 3asm** [comment]
Thanks for the technical details @mraleph . https://www.ostorlab.co/ will no longer report flutter `libapp.so` as missing `RELRO`.

**Comment by liapalaria** [comment]
Thank you for the clarifications!

**Comment by xster** [comment]
Closing the issue since there are no further action anticipated. We can add more documentation as stated in https://github.com/flutter/flutter/issues/49801#issuecomment-629997651 if this topic comes up again.
