### ISSUE TITLE
HTTP header lowercase issue

### ISSUE THREAD

**Issue by balaji101010** [flutter/flutter#49881]
```
final Response<Map<String, dynamic>> _result = await _dio.request(
        'parent-category',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{
              'Authorization': contentType,
              'Installation-Id': installationId
            },
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
```

The headers **Authorization** becomes 'authorization`

**Comment by iapicca** [comment]
Hi @balaji101010 
if you are using the 3rd party plugin [dio](https://pub.dev/packages/dio)
consider opening an issue in the dedicate [github](https://github.com/flutterchina/dio/issues)

if you believe the issue is w/ flutter itself 
please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by balaji101010** [comment]
Ok thank you @iapicca I will try to not use dio thanks
