### ISSUE TITLE
Is there support for iOS on-demand resources in Flutter?

### ISSUE THREAD

**Issue by bormind** [flutter/flutter#49901]
## Use case
We have relatively large static html files as application assets. 
We have to deliver them as a part of the application bundle per Apple's requirements.
We would like to load some of those assets by utilizing ios on-demand resource facilities: [On-Demand Resources Guide](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html#//apple_ref/doc/uid/TP40015083)

We can't find any documentation indicating if this is possible or not.

## Proposal

It would really help to have these features implemented or to know what is the current capability and the roadmap for the implementation.

**Comment by gaaclarke** [comment]
> We have to deliver them as a part of the application bundle per Apple's requirements.

There is no requirement that html files have to ship as part of the app.  The only requirement is that code must be shipped with the app.  The obvious exception is javascript present in web pages, otherwise you'd never be able to display web content.

Using On-Demand Resources will obviously only work on iOS.  You can implement your own solution for loading remote resources with your own server if you want it to be cross-platform.

If you are dead set on using iOS's On-Demand Resources take a look at [ios_platform_images](https://github.com/flutter/plugins/tree/master/packages/ios_platform_images).  It allows you to load system images (which can be setup to work with On-Demand), you could tweak it to load html pages.

Since this is an iOS specific feature that relies on Apple's servers this is really in the province of plugins.
