### ISSUE TITLE
Canvas shadow BlendMode is not respected during scrolling

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#49928]
I have a `CustomPainter` that paints 2 `Shadow`s with 2 different `BlendMode`s. The initial render looks fine, but the moment that a scrolling action takes place, e.g., `PageView` swiping or `Drawer` swiping, the `BlendMode` is ignored and results in an ugly rendering artifact.

Here is a screenshot of an initial shadow render:
![Screen Shot 2020-01-31 at 9 46 24 PM](https://user-images.githubusercontent.com/7259036/73587666-9336ee80-4473-11ea-9afc-e0eb918150f0.png)

Here is a screenshot of the same shadow the moment that I begin to scroll a `PageView`:
![Screen Shot 2020-01-31 at 9 46 31 PM](https://user-images.githubusercontent.com/7259036/73587672-9f22b080-4473-11ea-8283-c3fbc0dd5ed3.png)

I reproduced the above bug on an iPhone simulator, and a physical iPhone 7. The glitch looks even worse on a physical device (the above screenshots are from the simulator).

And here is a minimal repro project:
https://github.com/matthew-carroll/flutter_bug_repro_49928

I left a note in the source code of that project that explains that the problem only occurs when I paint a shadow twice. I also explain in there why I do that.

Flutter Doctor:
```
Flutter (Channel master, v1.13.6-pre.23, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.13.6-pre.23 at ---
    • Framework revision 6e72facad1 (5 weeks ago), 2019-12-24 10:54:04 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)
```

**Comment by matthew-carroll** [comment]
CC @cbracken @chinmaygarde for visibility as a possible engine rendering/compositing bug.

**Comment by iapicca** [comment]
Hi @matthew-carroll 
did you mean to add the `a: triage` label here?
thank you

**Comment by matthew-carroll** [comment]
I thought it would be good to triage this issue in case it reveals other rendering bugs. If that tag shouldn't be there, please feel free to remove it.

**Comment by jason-simmons** [comment]
The shadows render differently during scrolling because at that point the SkPicture has been placed into the raster cache.

@liyuqian

**Comment by liyuqian** [comment]
Thank you @matthew-carroll for your sample app! It reveals a very fundamental problem in our raster caching mechanism: whenever a picture is raster cached instead of directly gets drawn, it risks of changing the semantics if there are multiple blending modes, or if the blending modes are non-associative. It is very similar to how `saveLayer` may [change the semantics](https://github.com/flutter/flutter/issues/18057#issuecomment-394197336).

An analogy is to view the blending as an arithmetic operation like plus `+` or multiply `*`. Formula `a * b + c` has different semantics with `a * (b + c)`. Raster caching and `saveLayer` are essentially putting brackets around some draw operations and their blending.

For this specific issue, the fix would be to give `willChange: true` to `CustomPaint` to disable the raster cache so Flutter won't change its semantics.

In  general cases, Flutter need to be more careful about applying raster caches. There might be no silver bullets so we should again give developers an option to explicitly choose the trade-off between performance and qualities/semantics, like what we did for `clipBehavior`. I'll create a new issue for that, and close this issue due to the simple `willChange: true` fix.
