### ISSUE TITLE
Not able to get flutter_localizations packages

### ISSUE THREAD

**Issue by manishp1412** [flutter/flutter#49931]
I want to implement localization in flutter application. I am  getting below error after adding "flutter_localizations" in pubspec.yaml

Because flutter_sample depends on flutter_localizations any which doesn't exist (could not find package flutter_localizations at https://pub.dartlang.org), version solving failed.

**Comment by Jasoneng2017** [comment]
I have the same question.
notes:
because no versions of flutter_form_builder match >3.7.3 <4.0.0 and flutter_form_builder 3.7.3 depends on intl ^0.16.1, flutter_form_builder ^3.7.3 requires intl ^0.16.1.

And because every version of flutter_localizations from sdk depends on intl 0.16.0, flutter_form_builder ^3.7.3 is incompatible with flutter_localizations from sdk.

So, because depends on both flutter_localizations any from sdk and flutter_form_builder ^3.7.3, version solving failed.

**Comment by VladyslavBondarenko** [comment]
Hi @manishp1412 
You need to import this package this way ([documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization))
```
flutter_localizations:
    sdk: flutter
```


@Jasoneng2017 
This is versioning issue. I would advice you to update your Flutter SDK (from `flutter_localizations from sdk depends on intl 0.16.0` is visible that you are using some of the old versions, because last versions are compatible with `intl 0.16.1`. If you don't want to update it, you can use another lower version of flutter_form_builder < 3.7.3 which will be compatible with intl 0.16.0


Closing the issue
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by rafaband** [comment]
I got the same problem on import a project that has location.

Because test_app depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because test_app depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because test_app depends on intl ^0.16.1, version solving failed.)

**Comment by albertms10** [comment]
Same here.

```
Because cabin_booking depends on flutter_localizations any from sdk
which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.

So, because cabin_booking depends on intl ^0.16.1, version solving failed.
```

**Comment by globaljuli** [comment]
Had the same error here, then I replaced ` intl: ^0.16.1` for `intl: ^0.17.0-nullsafety.2` but now all my generated files are broken with various errors from `Class Locale isn't defined` to `'AppLocalizationDelegate.isSupported' ('bool Function(Locale)') isn't a valid override of 'LocalizationsDelegate.isSupported'`..

It's being a real nightmare to internationalizate the app as the official documentation didn't work for me and had to use the Flutter Intl plugin which I knew it would bring problems...

**Comment by globaljuli** [comment]
In order to solve everything in my case was to find a mid-term

In one hand, the _channel dev_ had a higher version that was making all my translations to break while staying in _channel stable_ was doing some dependencies to deny the pub get because of outdating.

So, I changed to _beta channel_ and it seems that it's the mid term where the internationalizations does not break and the dependencies can work properly.

Also in my case, I had to use dependency_overrides:
`dependency_overrides:
  intl: ^0.17.0-nullsafety.2`

Because flutter_localizations need ` intl: ^0.16.1` while the last version of `  flutter_svg: ^0.19.2+1` needed `  intl: ^0.17.0-nullsafety.2`

Hope I can help somebody with this info!

**Comment by albertms10** [comment]
In my case, just changing the Flutter channel to `dev` and updating the affected packages (`intl: 0.17.0-nullsafety.2`) solved the issues.

**Comment by leszekkrol** [comment]
Flutter is already up to date on channel dev
Flutter 1.25.0-4.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision a7f5fd5360 (7 days ago) • 2020-11-30 13:14:13 +0100
Engine • revision 20caf54969
Tools • Dart 2.12.0 (build 2.12.0-76.0.dev)

 flutter pub get
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and jiffy 3.0.1 depends on intl ^0.16.0, flutter_localizations from sdk is incompatible with jiffy 3.0.1.
And because no versions of jiffy match >3.0.1 <4.0.0, flutter_localizations from sdk is incompatible with jiffy ^3.0.1.
So, because fanroom depends on both jiffy ^3.0.1 and flutter_localizations any from sdk, version solving failed.

**Comment by chenasraf** [comment]
My error was: 

```
[app] flutter pub get
Running "flutter pub get" in app...                             
Because intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0 and no versions of intl_translation match >0.17.10+1 <0.18.0, intl_translation ^0.17.10+1 requires intl >=0.15.3 <0.17.0.

So, because app depends on both intl 0.17.0-nullsafety.2 and intl_translation ^0.17.10+1, version solving failed.
pub get failed (1; So, because app depends on both intl 0.17.0-nullsafety.2 and intl_translation ^0.17.10+1, version solving failed.)
exit code 1
```

Adding this to `pubspec.yaml` solved it for me:

```yaml
dependency_overrides:
  intl: 0.17.0-nullsafety.2
```

**Comment by jagritjkh** [comment]
Same issue!

Because test_app depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because test_app depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because test_app depends on intl ^0.16.1, version solving failed.)

**Comment by exeptionerror** [comment]
All Possible working solution added [[Solved] flutter_localizations from SDK depends on intl 0.17.0 and fstore depends on intl ^0.16.1, flutter_localizations from SDK is forbidden](https://fluttercorner.com/flutter-localizations-from-sdk-depends-on-intl-0-17-0-and-fstore-depends-on-intl/)

**Comment by vkas8447** [comment]
I get this error:
Because app depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because app depends on intl 0.16.0, version solving failed.
pub get failed (1; So, because app depends on intl 0.16.0, version solving failed.)
