### ISSUE TITLE
SizedBox does not constrain CircularProgressIndicator as advertised.

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#50075]
According to the SizedBox class docs: "If given a child, this widget forces its child to have a specific width and/or height".

However for a CircularProgressIndicator child:

```
main() =>
    runApp(
        SizedBox(width: 30, height: 30, child: CircularProgressIndicator()));
```
... results in a full-screen CircularProgressIndicator, and the progress indicator is not 30x30 as requested.

This is resolved as follows:

```
main() =>
    runApp(Center(child: 
        SizedBox( width: 30, height: 30, child: CircularProgressIndicator())));
```
.... but seem it shouldn't be necessary. And, if I understand the docs of SizedBox, the need to do this is a bug.

```
$ flutter -v doctor
[✓] Flutter (Channel master, v1.14.7-pre.58, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.7-pre.58 at /home/sir/development/flutter
    • Framework revision 83d4d63a71 (4 days ago), 2020-01-30 18:10:36 -0800
    • Engine revision e5209202fb
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/sir/Android/Sdk
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-ultimate/198
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 76.0.3809.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by dnys1** [comment]
The new [Understanding constraints](https://flutter.dev/docs/development/ui/layout/constraints) article by the Flutter team may help clear confusion on why your example is performing the way it is.

**Comment by markusaksli-nc** [comment]
The fact that when SizedBox is already forced to be a certain size, the constraints will be ignored, could be explained better. The current explanation of:

>If given a child, this widget forces its child to have a specific width and/or height (assuming values are permitted by this widget's parent).

Doesn't explicitly mention that the parent is able to **not permit** a size smaller than itself, which leads to new users thinking: "But SizedBox will just apply the size constraints to its children, the parent **obviously** allows this since the child is smaller than the parent, why doesn't my code work, flutter is broken!" Just one sentence to mention this caveat would help avoid this confusion. Also, the [Understanding constraints](https://flutter.dev/docs/development/ui/layout/constraints) page should be linked in more places (like here).

@stuz5000 In this case, the constraints are effectively overwritten by the screen forcing the SizedBox to be the same size as the screen. The screen isn't the only thing that can do this. Anything that passes already passes tight constraints to SizedBox will.

```dart
import 'package:flutter/material.dart';

void main() => runApp(
    Center(
      child: Center(
        child: Container(
          width: 200,
          height: 200,
          color: Colors.red,
          child: SizedBox(
            width: 100,
            height: 100,
            child: Container(
              color: Colors.blue,
            ),
          ),
        ),
      ),
    )
);
```
In this case, the constraints of SizedBox are also ignored due to the already tight constraints of its parent Container. Once again you can only achieve the desired effect only by wrapping SizedBox in a widget that allows it's children to be any size up to the size of the parent (like Center or Align).
