### ISSUE TITLE
Gallery, Cards (travel stream): reproducable stutter when scrolling up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5007]
On my iPod Touch:

* open gallery
* tap Cards
* pull down as far as you can go
* then, pull up as far as you can go, such that the top card is scrolled off the display
* let go

Expected:

* cards gracefully scroll/animate back down into position

Actual:

* missed frames when (apparently, from what I can tell) the top card enters the display again

The spike below is when the top card animates back into view:

![img_0009](https://cloud.githubusercontent.com/assets/5479/17069078/7f7f020e-5009-11e6-9d92-d3ec10c0c8d6.PNG)

**Comment by abarth** [comment]
We looked at this issue a bit.  All the time is going into image uploads.  Some ideas:

 * Make sure we're using the best texture format (to avoid the driver having to swizzle the format on upload)
 * Cap the size of decode images to the screen size
 * Upload image data to the GPU on the image decoding thread rather than deferring to raster time

**Comment by sethladd** [comment]
Thanks for the analysis!

**Comment by eseidelGoogle** [comment]
My understanding is that this is related/same as #3805.

**Comment by abarth** [comment]
This is fixed by async image uploads.
