### ISSUE TITLE
MaxLines of TextField not working. The TextField expands beyond maxLine

### ISSUE THREAD

**Issue by huma11farheen** [flutter/flutter#50112]
-----Shortened Code-----
```
class MultiLineField extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Multi-Line TextField Example'),
      ),
      body: Center(
        child: TextField(
          keyboardType: TextInputType.multiline,
          maxLines: 10,
        ),
      ),
    );
  }
}

```

The `maxLine` property of TextField does not restrict the input to the Max Lines provided. Though the number of displayed lines are 10, as shown below, the cursor still moves to the 11th line and beyond. Adding `inputFormatters`, `maxLength` does not make any change.  How can a fixed number of input Lines be implemented.

![Screenshot_1580830072](https://user-images.githubusercontent.com/56956749/73758752-61dd5c00-47ae-11ea-9f38-1d0bef76120b.png)

**Comment by justinmc** [comment]
What `maxLines` does is to limit the height of the TextField, not the length of the content.  `maxLength` does limit the length of the content, but by number of characters, not number of lines.

I can't think of a way to limit the length of the input to a certain number of lines.  Maybe that's not what you want, though.  What would happen if the user rotated their device from portrait to landscape, would they suddenly be able to enter more text?  The limit would also depend on the size of your users' devices.

I'm going to close this since I don't see how Flutter could implement this.  Definitely feel free to respond if you have any specific ideas though, and I can reopen this.

**Comment by huma11farheen** [comment]
@justinmc 
I could suggest you to make a similar property `LengthLimitingTextInputFormatter()` for number of lines
For example , if i give maxLines = 3 , when the user reaches line 3, the user should be limited to press enter again.

**Comment by justinmc** [comment]
That might work, and people could implement it on their own if they wanted.  Can formatters figure out what the number of lines in the old and new text is?
