### ISSUE TITLE
Command for AS plugins is missing

### ISSUE THREAD

**Issue by BartosStore** [flutter/flutter#50332]
Firstly thanks for Flutter!

## Steps to Reproduce

1. Have a provisioned IT infrastructure
2. Move Android Studio config files from /home to local HDD/SSD (due to network traffic)
3. Flutter does not see AS plugins anymore cause /home is hardcoded

## Logs

```
[!] Android Studio
    • Android Studio at /var/userdata/miroslav.bartos/app/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /var/userdata/miroslav.bartos/app/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

There is command to setup AS path:
```
flutter config --android-studio-dir="/var/userdata/xxx/app/android-studio"
```

But **there is no way to configure custom AS plugins** path. Default is:
```
$HOME/.AndroidStudioX.Y
```

Content of "flutter/packages/flutter_tools/lib/src/android/android_studio.dart":

```
// Android Studio layout:
// $HOME/.AndroidStudioX.Y/system/.home

final RegExp _dotHomeStudioVersionMatcher =
    RegExp(r'^\.(AndroidStudio[^\d]*)([\d.]+)');
```
## Workaround

Create symlinks for .AndroidStudio folder. This solution will be broken by the first AS update.

## Solution

Am I missing some comfortable way to handle this? 
**How to setup path to Android Studio plugins?**

**Comment by iapicca** [comment]
Hi @BartosStore 
to be honest I'm not sure this is a Flutter issue, 
a  [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) issue [github](https://github.com/flutter/flutter-intellij/issues)
or a question for the [community](https://flutter.dev/community ) and stackoverflow.

In the doubt I'll keep the issue open for now,
but I'd recommend to try also the aforementioned alternatives as well.
Thank you

**Comment by jmagman** [comment]
It is indeed hardcoded into Flutter.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L129-L143

**Comment by dratushnyy** [comment]
@jmagman, Hi! I would like to create a PR to resolve this issue.
At the current moment, I can see two potential solutions.  

1) Use the `android-studio-dir` to get the plugins directory.

2) Introduce a new configuration key which will allow o set the path to android studio plugins and then use it in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L129-L143

So, I have a question, what approach will be better?

**Comment by jmagman** [comment]
@dratushnyy Thanks for being willing to contribute!  

The plugin warnings `flutter doctor` throws up are informational only, and the tool doesn't actually use those paths for anything but this message as a hint to new users.  A non-clean `doctor` causes users stress, and we don't want to encourage people to ignore `doctor` warnings, but it shouldn't actually be causing real issues. 

We've had a lot of issues chasing various paths in `IntelliJ` IDEs since they seem to move based on different flavors and versions (not so much Visual Studio, VS Code,  or Xcode which seem more stable).
https://github.com/flutter/flutter/issues/57642
https://github.com/flutter/flutter/issues/54867

1. How would you use the existing `android-studio-dir` flag?
2. We probably don't want to introduce a new config key just for the sake of the doctor validator.

@christopherfujino You're on the hook since you threw that tempting `good first contribution` label on this one.  😃   We were discussing removing this check, right?  I can't find a related issue though.

**Comment by dratushnyy** [comment]
@jmagman 
If my understanding is correct, according to this documentation it is possible to get the plugin path from the AS path

https://intellij-support.jetbrains.com/hc/en-us/articles/207240985-Changing-IDE-default-directories-used-for-config-plugins-and-caches-storage
So, answering to your question, I would try to get `IDE_HOME\bin\idea.properties` file using the  `android-studio-dir` flag, and try to get the actual path for the plugins from it.

Also, looks like that changing plugins path is something that is not so rare to occur.  
However, I am not sure is it really worth doing this kind of fix or not. 😃 There are plenty of issues to work on 😃

**Comment by christopherfujino** [comment]
We had discussed it, but there was no official issue tracking, so I created one https://github.com/flutter/flutter/issues/61246.

Thanks for offering to fix @dratushnyy, but I as this keeps breaking (and we plan to imminently deprecate), your time would probably be better spent elsewhere. Sorry about that!

**Comment by dratushnyy** [comment]
Thank you for the clarification, I  will pick some other issue to work on, no problem 😃

**Comment by christopherfujino** [comment]
Closing this as we plan to deprecate these validators: https://github.com/flutter/flutter/issues/61246
