### ISSUE TITLE
Error creating project: could not ensure the target project location exists and is accessible

### ISSUE THREAD

**Issue by Vuyisile619** [flutter/flutter#50403]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
Hey guys sorry if i am doing this wrong but i am new to programming and have not yet learnt how to use github but i am running into the issue with android studio "could not ensure the target project location exists and is accessible". So the issue is more with android studio than flutter. I know there are other similar questions to it but non of the solutions have worked for me and they somehow just get abruptly closed just because there's some
![Screenshot (407)](https://user-images.githubusercontent.com/53944331/74081974-8f9bfc80-4a5d-11ea-9d6b-0c162fe7f7aa.png)
 other question that looks similar to it but i do not know what to do anymore i am stuck guys please help

**Comment by jonahwilliams** [comment]
Hi @Vuyisile619 the problem is that the directory C:\AndroidStudioProjects either doesn't exist, or you lack permissions to edit it. I would recommend creating a folder under Documents instead.

At any rate, these sorts of questions are not really suitable for github issues, which should be reserved for bugs or features requests.

For help on topics like these in the future, you might check out one of the channels at flutter.dev/community

**Comment by karankumar2000** [comment]
I have facing the same problem but I couldn't find the solution can u elaborate what to do to slove this issue..
