### ISSUE TITLE
Request: an easy way to re-establish an Observatory connection to a running app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5043]
It's easy for an android app to get killed when the device runs out of memory, etc. When the app is brought back up (e.g. when the user taps the app launcher icon again), it creates a new observatory port. Unfortunately, it's difficult to re-establish the connection unless you know about `adb logcat` and `adb forward`. During profiling and debugging, it's all about Observatory and so when the Observatory connection dies, my profiling workflow dies.

I was doing a full `flutter run --profile` but that's a slow process to run if all I'm trying to do is bring back Observatory.

May I suggest we offer something like a `flutter connect` command that finds the running Flutter app on the device/emulator and does any port forwarding/mapping business.

That would be a YUGE time saver as we're profiling our Flutter apps.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew thoughts?

**Comment by sethladd** [comment]
In the meantime, here's what you can do:

* restart your Flutter app
* run `adb logcat | grep Observatory`
* find the last "Observatory listening on ..."
* copy the last port number (e.g. `:44324`)
* Control-C
* run `adb forward tcp:44324 tcp:44324`
* Open your browser
* go to `127.0.0.1:44324`

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by devoncarew** [comment]
@jason-simmons did some work to discover running apps on a device and forward their ports. That's exposed through the daemon protocol but not through the CLI.

That said, it sounds like the launching and re-launching apps w/ `flutter run --profile` was slow. Just making a null build for it fast would solve the use-case of the app closing while profiling.

**Comment by sethladd** [comment]
> launching and re-launching apps w/ flutter run --profile was slow. 

This is true. Especially if nothing has changed.

If `flutter run --profile` was crazy fast when nothing has changed (essentially: start the app on my phone and forward ports) then yes, that would solve the use case.

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/5112

**Comment by Hixie** [comment]
Use cases here:
1. Attaching a debugger after demoing an app untethered.
2. Reattaching the "hot reload" console to a device after it was disconnected.
3. Doing this from IDEs.

**Comment by Hixie** [comment]
This is not currently on our radar, so if it's something that we should prioritise, let me know.

**Comment by zoechi** [comment]
@DanTup is `flutter attach` doing what is requested here?

**Comment by DanTup** [comment]
It may do some of what's mentioned above. Right now, you need to run `flutter attach` before the Observatory URL is written to the logs. So, if running the app from the launcher on the device does log URL then running `flutter attach` and *then*" launching the app should work.

However if you've already launched the app again (or it was already running and you just want to attach to it) then that's not supported because we have no way to get the Observatory URL.

I believe there's some work going on that may give us options to improve this - allowing us to "ping" the phone and ask for the Observatory URL for already-running apps but I'm not sure how far it is, which platforms it covers (the mechanism to do this on iOS and Android will be different) or how close it gets us. I think @dnfield did some work on it, so he may know more.

**Comment by dnfield** [comment]
I  need some changes to land in dart vm to continue this for iOS, but it's in progress there.

**Comment by jonahwilliams** [comment]
Closing as https://github.com/flutter/flutter/issues/23687 is more specific
