### ISSUE TITLE
hello_world_android_compile_license_compressed_bytes regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50472]
Looks like part of this engine roll: https://github.com/flutter/flutter/pull/50305

**Comment by goderbauer** [comment]
Looks like this was most likely caused by adding more licenses in https://github.com/flutter/engine/pull/16347. If adding those licenses was actually intentional (and the software under that license actually ships to clients of Flutter and is not just used for building Flutter itself) we should re-baseline that benchmark.

/cc @stuartmorgan

**Comment by stuartmorgan** [comment]
rapidjson is used in the shipped framework; adding the new variants was intentional.

I didn't realize we were that close to tolerance on the licenses benchmark again.

**Comment by stuartmorgan** [comment]
Rebaselined to 61000 bytes.
