### ISSUE TITLE
Determine if we need to keep the existing Refresh Time benchmark

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#5056]
Define what the 'refresh time' benchmark is measuring. 

It appears to be measuring the time it takes to build the snapshot on the host + copy the file to the device. It should probably measure:

- snapshot on the host
- copy snapshot to device
- launch a fresh isolate
- render the first frame

**Comment by sethladd** [comment]
Did you mean "hot reload" or "fast refresh" ?  (I ask because I'm not aware that snapshot generation is involved in the hot reload process.)

I think of measuring hot reload like:

* Developer hits 'r' in Flutter tools, to signal they want to reload.
* Frame is drawn on the device (android and ios).

The total time between when the developer signals they want a reload, and when they can see the effect of that change on the device.

We can assume:

* the APK has been built and uploaded to the device
* the initial set of source has been sent to the device
* the app is up and running on the device
* the app is running in checked/debug/development mode

**Comment by johnmccutchan** [comment]
@sethladd This issue is about the 'refresh time' benchmark on the dashboard. A hot-reload benchmark is a separate issue

**Comment by sethladd** [comment]
After doing some research, I believe we should create a new benchmark that measures hot refresh (as spec'ed in https://github.com/flutter/flutter/issues/5056#issuecomment-235420661) and deprecate this benchmark (and remove it from the dashboard). The initial refresh time benchmark helped get us here, but we have a new cycle that we need to measure.

@devoncarew do you need to keep the refresh time benchmark up and running? It seems to measure snapshot building time, are we looking to drive that number down?

In the meantime, we can start building a new benchmark that measures end to end hot refresh.

**Comment by johnmccutchan** [comment]
@a-siva

**Comment by devoncarew** [comment]
This is measuring the edit / refresh time from the user's perspective - the time between when the user hits run (after making changes), and when those changes are visible on the screen. This currently is measuring the snapshot generation+copy time, as well as the isolate restart and app bring-up time (up to when we get the `Flutter.FrameworkInitialization` event - https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run.dart#L89).

I think it would make more sense to re-swizzle this benchmark to use `--hot` than to start a new one, since the intent here is the same.

**Comment by sethladd** [comment]
Thanks for the feedback! @yjbanov mentioned that our historical data might look weird after we refactor this benchmark? Whether or not we refactor the existing benchmark or create a new one, sounds like you don't need to keep a benchmark of measuring snapshot gen time. If I misunderstood that, please correct me.

**Comment by devoncarew** [comment]
Yeah, I'm fine with it being refactored, but to be clear, this is not measuring snapshot gen. time, but the edit/refresh experience of the user.
