### ISSUE TITLE
move the showFoo methods to Foo.show

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5063]
It would make the docs easier to browse if things like showDialog where statics of the form Dialog.show.

**Comment by Hixie** [comment]
As of the time of writing this, we had at least:
- [ ] showAboutDialog
- [ ] showDatePicker
- [ ] showDialog
- [ ] showLicensePage
- [ ] showMenu
- [ ] showModalBottomSheet
- [ ] showTimePicker

**Comment by sethladd** [comment]
Is this actually an issue with how dartdoc displays info? I'd hate to get rid of top-level functions only because our API docs could be formatted better :)

**Comment by Hixie** [comment]
It's also just generally clearer, IMHO.

**Comment by HansMuller** [comment]
I also find it clearer when utility functions are bound to related classes. 

This seems like a good change to me.

**Comment by abarth** [comment]
I got 10% of the way through this change and decided it wasn't an improvement.  The problem is that the Foo isn't always a public class.  For example, the ModalBottomSheet is a private class to force you to use showModalBottomSheet.  It wouldn't make sense to expose the class just to attach a `show` method to it.
