### ISSUE TITLE
Flutter needs a tips-and-tricks or "effective flutter" guide.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5067]
We've had requests from customers for some sort of tips-and-tricks guide for Flutter, presumably something akin to:
https://www.dartlang.org/guides/language/effective-dart

I think us creating a stub, where we can start dumping this knowledge is the first step.  Akin to a FAQ for engineering-with-flutter topics.

My first guess would be we should just clone effective-dart's style and fill in a first few entries for Flutter.

Thoughts @qchong? @Hixie

**Comment by qchong** [comment]
We currently have the [Flutter style guide doc](https://flutter.io/style-guide/) which covers formatting and API documentation, but not a separate design and usage guide. 

@Hixie Are the tips from the "Effective Dart" site all applicable to Flutter app developers also? Are there Flutter-specific tips that supercede the Dart tips, that we should highlight? If you could compile and share some of them, I'd be happy to write them up for the flutter.io site.

**Comment by Hixie** [comment]
Their document is actively maintained, so I would reference it (it's quite relevant to our needs) but not clone it.

We have a whole bunch of additional things that we should recommend in a similar doc for Flutter, though. I would recommend starting a page somewhere that's trivially editable, a bit like a FAQ, so that whenever we have some advice to give someone, we can throw it there. Once we've collected a bunch of things we can make it more coherent.

A page on github somewhere or in a wiki would be fine.

**Comment by qchong** [comment]
Here's the initial wiki page: [Developer best practices](https://github.com/flutter/flutter/wiki/Developer-best-practices).
