### ISSUE TITLE
kIsWeb is always false in analysis server

### ISSUE THREAD

**Issue by scheglov** [flutter/flutter#50765]
This declaration used to evaluates to `true` when Dart Analyzer, or Dart Analysis Server evaluates it.

```dart
const bool kIsWeb = identical(0, 0.0);
```

But strongly speaking, it should be `false`.
According to the Dart language specification, `int` and `double` are never identical.
![image](https://user-images.githubusercontent.com/384794/74486104-0af01a80-4e71-11ea-9c46-652840ebc245.png)

While at runtime `int 0` is `double 0.0`, during analysis it is not.

[My CL](https://dart-review.googlesource.com/c/sdk/+/135781) starts checking types, and breaks the Flutter bot. I will add a workaround for `identical(0, 0.0.)`, but I wonder if this should have a better fix. @devoncarew

**Comment by jonahwilliams** [comment]
We could use a dart define instead of `identical(a, b)`. That said, I imagine more than just flutter is depending on this trick working.

**Comment by yjbanov** [comment]
What's a good way to detect that we're on the Web using a constant expression? We'll use that method instead.

/cc @vsmenon @sigmundch

**Comment by sigmundch** [comment]
@yjbanov - the method you have is what we currently recommend on the web tools.

@scheglov - to every rule there is an exception :) Unfortunately I don't think it will be enough to whitelist just that case with 0 and 0.0.

I have yet to find if this is explicitly stated on the spec or somewhere else, but the current strategy is that numbers have special semantics when compiled to JavaScript. Because all numbers are represented by the JavaScript `Number` when we compile it down, we have several variations on the meaning of numbers and their types. For example, under web semantics `int <: double`, certain 64-bit literals are reported as compile-time errors because they cannot be represented precisely in JavaScript (which uses 53-bits floats), and constant evaluation is adjusted to incorporate the fact that when two values are identical at runtime, they will also be identical as constants.

Here are some relevant pointers:
* the CFE can be configured on whether it is running under JS (web) or non-JS semantics here: https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/target/targets.dart#L45
* the CFE uses this for constant evaluation. See: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/constant_evaluator.dart#L599
* dart2js exhaustive tests (with > 800 cases) to ensure this is respected. See: https://github.com/dart-lang/sdk/blob/master/tests/compiler/dart2js_extra/constant_folding_test.dart

Does analyzer has any notion of these different number semantics today?

**Comment by scheglov** [comment]
No, Analyzer does not have a notion of number semantics.
@leafpetersen Should the language spec state this semantics?

The issue with analyzer and analysis server is that Flutter as a package can be used both when `kIsWeb` is `true`, and when it is `false`. It is individual widgets that might have `assert` and so report compile-time constant errors. And analysis server, in contrast to CFE and backends, analyses the whole package, all its files, where some might be OK only for Web, and some only when not Web. It has always been know that static analysis of constants is done to the best effort, but it can never be accurate.

**Comment by leafpetersen** [comment]
@scheglov There is an appendix to the specification (`Appendix: Integer Implementations`) which has some discussion of this, including the fact that when compiled to javascript, the int instances are a subset of the double instances (rather than a disjoint set).  The exact implementation of all of the integer operations on the web platform is not specified though.  There was at one point a desire to specify the dart2js implementation choices there, but I don't think it's ever been done.  cc @rakudrama @sigmundch

**Comment by rakudrama** [comment]
The differences between VM and dart2js can become arbitrarily large.
Consider
```dart
const x = identical(0, 0.0) ? [] : {};
```
In one case `x` is a List, the other a Map.
Because of this difference (and differences due to configurable uri imports), a Dart program is a large set of related programs. Does analyzer present a view of _one_ of these configurations, or of _all_ of the configurations at once?

In the latter case, it would be necessary for the constant system, result of resolution, etc to include a conditional result. You can't say that `kIsWeb` is `true` or `false`, only something like

`kIsWeb:` {_web_: `true`, _vm_: `false`}
`x:` {_web_: `const []`, _vm_: `const {}`}

A simple, but less precise, approach would be to represent the value as an _unknown constant_. You might have this already since analyzer must work on incomplete programs.

Since numbers are ubiquitous, and every arithmetic operation differs between the web and vm, I think analyzer needs to model both vm and web arithmetic, if only to know where the results are not the same.

**Comment by scheglov** [comment]
Ah, yes, that's an interesting idea. Just like for `bool.fromEnvironment()` we don't actually know the exact value, similarly for `identical(0, 0.0)` we don't know if it is `true` or `false`, so it should be "unknown".

**Comment by pedromassangocode** [comment]
Is this still an issue today?

**Comment by kevmoo** [comment]
https://github.com/flutter/flutter/blob/91aeda7bf6f977207d7ac07ca46c26560007a244/packages/flutter/lib/src/foundation/constants.dart#L71

We changed the implementation here!
