### ISSUE TITLE
CompositedTransformFollower with vertical offset also offsets mouseover effect of wrapped widgets (Desktop)

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#50800]
## Steps to Reproduce

This bug is about an UI issue with mouse over highlighting effect on `ListTile`s that are wrapped in a `CompositedTransformFollower` with an offset.

1. Create a new flutter project
2. replace main.dart with content from [this gist](https://gist.github.com/technolion/ed626ff133602cc99693953ed6d93c42) 
3. run the app on macOS
4. focus the app's text field **country**
5. move your mouse over the list

**Expected results:** Mouse over highlighting effect should be in sync with the position of the mouse

**Actual results:** Mouse highlighting is off by the offset of the `CompositedTransformFollower`

![hightlight-off](https://user-images.githubusercontent.com/1611505/74537957-625abd00-4f3b-11ea-9fd2-6d59c2024c48.gif)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by technolion** [comment]
Sample code inspired by [this medium article](https://medium.com/saugo360/https-medium-com-saugo360-flutter-using-overlay-to-display-floating-widgets-2e6d0e8decb9)

**Comment by rofrankel** [comment]
I think there is a(n unrelated?) issue here regarding onTap.  I ran into this with the search_widget package, and when I removed the Positioned the highlighting look right (onHover triggered as expected), but selecting things still didn't work (onTap did not trigger when I clicked on highlighted items).  I mentioned this [here](https://github.com/apgapg/search_widget/issues/12#issuecomment-591242595) as well.

**Comment by rofrankel** [comment]
I played with this a bit more, and it looks like (with search_widget) overlay mouse clicks that are over the actual text entry part of TextField that is the child of the CompositedTransformTarget are recognized (i.e. when the mouse cursor is an I-beam pointer), but otherwise not.

Here are some debug logs from a successful tap (`Gesture arena 7`) and an unsuccessful one (`Gesture arena 9`).  The difference is only two vertical pixels, and the inkwell I was clicking on showed its hover highlight in both cases, but in `Gesture arena 9` my pointer was below the range of the CompositedTransformTarget's TextField child.  In the former case, I could hold my mouse button down and see the inkwell highlighted (with `debugPaintPointersEnabled = true`), but in the latter case, the overlay was immediately dismissed by the pointer going down.

Gesture arena 7    ❙ ★ Opening new gesture arena.
Gesture arena 7    ❙ Adding: TapGestureRecognizer#09837(debugOwner: GestureDetector, state: ready, button: 1)
Gesture arena 7    ❙ Adding: VerticalDragGestureRecognizer#26148(start behavior: start)
handleEvent: PointerDownEvent#ae6ec(position: Offset(505.0, 888.0), localPosition: Offset(164.7, 12.0), timeStamp: 6:19:01.433704, pointer: 7, kind: mouse, device: -1, buttons: 1, down: true, pressure: 0.5, pressureMin: 0.0)
Gesture arena 7    ❙ Closing with 2 members.
handleEvent: PointerUpEvent#837d4(position: Offset(505.0, 888.0), localPosition: Offset(164.7, 12.0), timeStamp: 6:19:01.575509, pointer: 7, kind: mouse, device: -1, down: false, pressure: 0.0, pressureMin: 0.0)
Gesture arena 7    ❙ Rejecting: VerticalDragGestureRecognizer#26148(start behavior: start)
Gesture arena 7    ❙ Sweeping with 1 member.
Gesture arena 7    ❙ Winner: TapGestureRecognizer#09837(debugOwner: GestureDetector, state: ready, finalPosition: Offset(505.0, 888.0), finalLocalPosition: Offset(164.7, 12.0), button: 1, sent tap down)


Gesture arena 9    ❙ ★ Opening new gesture arena.
Gesture arena 9    ❙ Adding: TapGestureRecognizer#ce434(debugOwner: GestureDetector, state: ready, button: 1)
Gesture arena 9    ❙ Adding: VerticalDragGestureRecognizer#56cf0(start behavior: start)
handleEvent: PointerDownEvent#1d6cf(position: Offset(507.0, 896.0), localPosition: Offset(166.7, 20.0), timeStamp: 6:19:03.774115, pointer: 9, kind: mouse, device: -1, buttons: 1, down: true, pressure: 0.5, pressureMin: 0.0)
Gesture arena 9    ❙ Closing with 2 members.
Gesture arena 9    ❙ Rejecting: TapGestureRecognizer#ce434(debugOwner: GestureDetector, state: possible, button: 1)
Gesture arena 9    ❙ Rejecting: VerticalDragGestureRecognizer#56cf0(start behavior: start)
Gesture arena 9    ❙ Arena empty.

**Comment by ashutosh1211** [comment]
```dart 
 RenderBox renderBox = context.findRenderObject();
    var size = renderBox.size;
    return OverlayEntry(
        builder: (context) => Positioned(
              width: size.width,
              top: size.height,
              child: CompositedTransformFollower(
                link: _layerLink,
                showWhenUnlinked: false,
                offset: Offset(0.0, size.height + 5.0),
```
   top: size.height, this line should align the overlay below your text field.

**Comment by pedromassangocode** [comment]
Hi @technolion 
This seems to be fixed today.

![gif](https://user-images.githubusercontent.com/67424416/93757237-4bc9c200-fbfe-11ea-9a0f-e8b38fa94a1b.gif)

Closing this as fixed. If you disagree please feel free to write a comment bellow and I will reopen it.
Thank you

**Comment by technolion** [comment]
perfect, thanks!
