### ISSUE TITLE
No way to test new features for DartPad API doc sample

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#50813]
When writing new API documentation, it may not be possible to write DartPad samples for features that do not exist in the Flutter version that https://dartpad.dartlang.org/ uses (I'll assume it's `stable`). 

The [snippets documentation](https://github.com/flutter/flutter/blob/master/dev/snippets/README.md) suggests pasting the code in there to see what the sample looks like, but that did not work for https://github.com/flutter/flutter/pull/50058, since in that PR, `prefixIconConstraints` and `suffixIconConstraints` were new parameters that did not yet exist in `stable`.

**Comment by gspencergoog** [comment]
It doesn't target `stable`, it targets a particular ref (listed [here](https://github.com/dart-lang/dart-services) as the `flutter @ <ref>` directory). So new features will be available a couple of weeks or so after the commit of the feature.  Ideally, there would be a DartPad per branch, selectable via query parameter.  This will get worse once DartPad samples make it to the `stable` docs, since any breaking change has the potential to break samples, with no way to update the sample.

**Comment by gspencergoog** [comment]
cc @RedBrogdon

**Comment by RedBrogdon** [comment]
We've got backend services running with the dev, beta, and stable channels, which makes it possible to test with a local copy of DartPad by switching out the endpoint URL. 

We plan to update the front-end to make using these endpoints as simple as flipping a switch, but weren't able to fit that work into our Q3 roadmap.

**Comment by goderbauer** [comment]
Samples can be tested now that they life in their own file
