### ISSUE TITLE
Expose setInitialScale() in Flutter Webview API 

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#50837]
Internal bug: b/149330492

Expose WebView.setInitialScale() in the Flutter webview API. 

This is needed for the customer:dream launch by **end of Februrary**. Please ping the internal bug if you don't think it is doable in that timeline.

**Comment by Hixie** [comment]
@bparrishMines Any updates?

**Comment by bparrishMines** [comment]
We decided we wanted to avoid supporting this on Android since iOS doesn't have an equivalent method. When iOS transitioned from `UIWebView` to `WKWebview`, support for this was not included. This was a cause for concern that this was done intentionally and imply that this should be solved another way.

One solution is to configure the the html through meta tags as explained here: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

Closing this issue since the internal bug is considered resolved for the time being.
