### ISSUE TITLE
Unnecessary RAM consumption

### ISSUE THREAD

**Issue by AbhayVAshokan** [flutter/flutter#50894]
I am using HP Bx576tx, Ubuntu 19.10 OS. Every time "flutter run" command is executed the app is run consuming 600-1000MB of RAM on the laptop. The issue is after the runtime is quit by pressing "q" the run time ends. But the amount of RAM reserved for the same does not get cleared. When the app is run for the second time, it allocates a new portion of the RAM. When I use this cumulatively, the laptop starts to lag and get eventually stuck/hangs. There is no other way but to force shutdown the laptop.
![Screenshot from 2020-02-16 22-11-29](https://user-images.githubusercontent.com/35297280/74608685-4f95e300-5109-11ea-9e49-3a8741dcfc36.png)

**Comment by jonahwilliams** [comment]
You haven't actually provided any information on what version of flutter you are using and how much ram it is consuming

**Comment by rockyprabowo** [comment]
Have you ever worked on Android development before? That's how Gradle works. Those processes are the daemon(s) spawned and used by Gradle whenever you're building something, in your case your Flutter app project. Gradle will terminate any idle daemons after 3 hours, but since you seemingly have resource availability issues especially RAM, these are my recommendations to you:

- Please add more RAM when it's possible. Any kind of modern Android development needs a lot of memory, 4 GB of RAM won't cut it, you need more.

- Please check what the daemons are doing by executing `./gradlew --status` in `<your project root>/android`. Stop any idle daemons to reclaim the memory. To stop them, instruct the Gradle wrapper to stop the daemons it has spawned. Execute `./gradlew --stop` in `<your project root>/android`.

- You can disable the daemon completely. You can disable them system-wide or per-project basis. To disable the daemon, you can see the solutions [here](https://stackoverflow.com/questions/52928108/disabling-gradle-daemon-in-a-specific-project). You will have to wait longer during the debug/build session when compared to daemon enabled since the build process restarts from scratch (more information [here](https://docs.gradle.org/5.6.2/userguide/gradle_daemon.html))

**Comment by TahaTesser** [comment]
Hi @AbhayVAshokan 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
