### ISSUE TITLE
Gallery, Tabs: Jumping tab body when swiping right

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5094]
Open gallery, tap Tabs and scrolling, scroll the contents up, then swipe to the right.

Expected: smooth transition into the new tab body.

Actual: tab transitions to the Right, and then jumps the tab contents.

**Comment by HansMuller** [comment]
What's going on here is the demo app scrolling the new TabBarView to that it's scroll offset matches the tab you're coming from.  This is because the app bar's height depends on the scroll offset and we don't want the app bar to change size when you switch tabs. 

In the short term the simplest fix for this is to change the app bar's behavior to not scroll.

Once #4430 lands we'll revise the appbar logic that causes the problem.
