### ISSUE TITLE
Gallery, App bar: Should snap into place at a threshold, shouldn't be left in arbitrary height

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5099]
Open the Gallery, and slowly scroll up, shrinking the app bar. Pick up your finger when the text in the app bar is very close to the top.

Expected: the app bar snaps into place:

![screen shot 2016-07-27 at 1 36 50 pm](https://cloud.githubusercontent.com/assets/5479/17191542/3955e65e-53ff-11e6-98c7-881c7d238a9f.png)

Actual: app bar can be left in any position:

![screen shot 2016-07-27 at 1 36 56 pm](https://cloud.githubusercontent.com/assets/5479/17191561/4f2149b0-53ff-11e6-987f-ffc64ee6a86b.png)

**Comment by sethladd** [comment]
Confirmed this is still happening, on a Nexus 5, with a release build from today.

**Comment by HansMuller** [comment]
I don't think this is a bug, at least not as stated. Likewise for https://github.com/flutter/flutter/issues/1723 which seems to cover the same issue. 

The scrolling examples in the material spec, https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior, might imply that snapping should occur for big flexible pinned appbars. I have not been able to find an example of an Google Android app that does this and I think having the content your dragging jump away from you (over a significant distance) would be disconcerting. Most examples of floating appbars in our app's -do- snap in and out of view.  This is at least less disconcerting since they're only 56 pixels high.

Getting floating appbars to snap (the way most native apps do) seems worthwhile.

**Comment by Hixie** [comment]
We do this for floating app bars now. Closing since as @HansMuller says it's not clear it should happen for the other kinds of app bars.
