### ISSUE TITLE
stray "shuffling test order" message in `flutter test` output

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#51010]
Any time I run `flutter test` there's a stray line of output in the stdout:

```
Shuffling test order with --test-randomize-ordering-seed=0
```

This violates our style guide which requires no non-actionable output in general.

Looks like this is a regression with a recent package:test rev, and that we had a test that verified that we didn't regress this but it was modified in https://github.com/flutter/flutter/pull/50879 to allow for this output.

**Comment by Hixie** [comment]
cc @jonahwilliams @dnfield

**Comment by natebosch** [comment]
This was caused by https://github.com/dart-lang/test/pull/1150

There used to be no behavior difference between passing `--test-randomize-ordering-seed=0` and not passing the flag at all, now there is a difference. `flutter_test` chose to always pass the flag and lean on `0` being treated like not passing it.

**Comment by jonahwilliams** [comment]
I thought we were intentionally passing `0` and the message was expected/new 🤷‍♂ . Seems like an easy fix

**Comment by dnfield** [comment]
We should only omit it if it is 0.

**Comment by natebosch** [comment]
> We should only omit it if it is 0.

You should remove the default of `0` and omit it is if is `null`.

**Comment by natebosch** [comment]
#51018 will also correct the usage output to match `package:test`, but the test PR hasn't been reviewed yet so the wording might change slightly.
