### ISSUE TITLE
Gallery, Pesto: back button does nothing after going home from drawer

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5103]
* Open gallery
* Tap pesto
* Tap to open drawer
* Tap home
* Tap recipe
* Hit the back button
* Hit the back button
* Hit the back button

On that third back button, I'd expect to be taken to the Gallery home. Instead, nothing happens.

On the fourth tap on the back button, I am taken back to the homescreen.

**Comment by mpcomplete** [comment]
The problem with this one (even after Jason's crash fix) is that when you tap `Home` from the open Drawer, the Drawer is never closed - just destroyed. This leaves the drawer-opening on the navigation stack, so you need to hit `back` an extra time to skip past it.

Maybe the Drawer should close itself when disposed.

**Comment by jason-simmons** [comment]
This is happening because the tap of "Home" is considered a navigation that pushes another instance of Pesto onto the history stack.

When you hit the back button, you navigate from the second instance of Pesto back to the first.  You can see the change if you scroll the recipe list in the two instances to different places.  In your example, the two instances looked identical, so it seems like the back button did nothing.

If you're already in Home, then should another tap of Home in the drawer do anything?

**Comment by Hixie** [comment]
@HansMuller was looking at this today.

**Comment by HansMuller** [comment]
I have most of a fix. Hope to finish today.  I filed a separate issue: https://github.com/flutter/flutter/issues/5159
