### ISSUE TITLE
web_benchmarks_html_draw_rect.html.averageDrawFrameDuration, other web benchmark regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51055]
The benchmarks are pretty noisy, so it's hard to pinpoint a cause. Looks like it started around https://github.com/flutter/flutter/pull/50693.

![benchmark](https://user-images.githubusercontent.com/1435716/74858003-6dc23580-52f9-11ea-8ebb-cbacaaf8d1be.png)

**Comment by dnfield** [comment]
@yjbanov - this benchmark looks like it's been noisy from inception, but it seems like it has trended upwards at some point.  Any ideas?

**Comment by yjbanov** [comment]
It will remain noisy for some time. The work on Web benchmarks is just starting. I hope we can reduce noise with future improvements. For now, I can just set the baseline above the noise. I'm removing the TODAY label, as it's not critical.

**Comment by liyuqian** [comment]
@yjbanov : the `averageDrawFrameDuration` benchmark seems to have been replaced by `drawFrameDuration.average`. The `drawFrameDuration.average` benchmark is now at 27340 μs which is much lower than 34132 μs in the screenshot above. I wonder if this means that the regression is gone, and we're having a big speedup here compared to 1 month ago? (Sorry, I can't confirm it myself due to https://github.com/flutter/flutter/issues/52692.) If so, maybe we can close this issue.

**Comment by yjbanov** [comment]
One difference is that we now wait for noise from multiple metrics to settle. Previously we only waited for the overall draw frame noise to settle. That would affect the numbers.

**Comment by kf6gpe** [comment]
@yjbanov Have we subsequently deprecated this benchmark on the dashboard, or am I just not seeing it? I'm not finding it now to have a look, and leaning towards closing this issue as a result.

**Comment by kf6gpe** [comment]
This benchmark looks like it's no longer being tracked. I'm closing it for now, as it's not on the dashboard. If we have actionable things here, please re-open it.
