### ISSUE TITLE
Browser zoom doesn't trigger rebuild

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#51210]
Zooming in or out in Chrome the app size doesn't match the window size.

Steps to reproduce:

1. zoom in or out in Chrome
2. observe the app doesn't align with the window
3. resize window
4. app is correctly displayed.

**Comment by johnpryan** [comment]
Yes this working in master for me

**Comment by bgrcs** [comment]
This needs to be pushed to the dev channel, especially since it's an important accessibility feature... However, I'm still finding issues with in-browser zoom, in certain circumstances, setting it to 100% after zooming in/out quite a lot causes the same issue to occur and the rebuild is not triggered! However, it's much better than in the dev channel.
