### ISSUE TITLE
Make ExpansionPanelList more customizable - divider colors and elevation control

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#51321]
## Use case

Would be nice to be able to customise `ExpansionPanelList` and `ExpansionPanel` widgets more. For example, for my use case I don't want elevation but this can't be changed since it is hardcoded in `MergeableMaterial`. Also I want to change the color of the divider.

## Proposal

Expose more properties as parameters to these widgets so more customisation would be possible.

- [x] customizable divider colors
- [ ] customizable elevation/shadows

**Comment by ftvs** [comment]
+1, I was looking for this as well. As an alternative, [ExpansionTile](https://api.flutter.dev/flutter/material/ExpansionTile-class.html) can be used to build a custom ExpansionPanelList equivalent. You can check the [Dartpad sample](https://dartpad.dev/0412a5ed17e28af4a46f053ef0f7a5c2).

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue and start by exposing the `elevation` property. The `elevation` property used by `MergableMaterial` uses `kElevationToShadow` which has some predefined elevations which can be used by the users. My concern here is that even if we expose `elevation` property users will not have complete control over the `elevation`.

**Comment by AyushBherwani1998** [comment]
@shihaohong I also looked at the possibilities of changing the divider colour. The `MergableMaterial` uses `Divider.createBorderSide` to have the divider which has a colour property which is not exposed by the `MergableMaterial`. So, if users want to change the colour of the divider, they can change the divider colour through `DividerTheme`. 

So, if we want to provide a way for users to change the divider colour in `ExpansionPannelList`, we will first need to expose the colour property in `MergableMaterial`.

**Comment by shihaohong** [comment]
Note: This is just my thoughts out loud as I did research into shadows and elevation, since I'm new to this as well. So, don't take these explorations as recommendations to do anything, but as situations to consider.

I started looking into shadows and elevation since I wasn't as familiar with how Flutter handled shadows. From what I understand, like you said, `MergeableMaterial` uses `kElevationToShadow` to use a set of `BoxShadow`s to generate the widget's shadows. 

Some other widgets use `PhysicalModel` simply takes an `elevation` double, which represents the z-coordinate of the widget and paints it [a different way](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L1795). I'm actually still not sure how the offset for the shadow generated by `PhysicalModel` is defined, and it seems it doesn't account for spread radius and blur radius like `BoxDecoration` does. `BoxDecoration` takes a list of `BoxShadow`s and has its [own opinion on how to paint shadows](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_decoration.dart#L435) compared to `MergeableMaterial` (MergeableMaterial implementation available [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/mergeable_material.dart#L691)). 

It's also hard-coded to use a `Card`'s [RRect default border radius](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/mergeable_material.dart#L699), so we need to decide if this should be flexible as well.

@tudor07 Can you further clarify what type of control over elevation you need?

**Comment by shihaohong** [comment]
@AyushBherwani1998 Providing customization of the divider color does not seem as complex as the shadow problem. It should be okay to expose a `dividerColor` property through `MergeableMaterial` and then to `ExpansionPanelList`.

**Comment by AyushBherwani1998** [comment]
> 
> 
> Note: This is just my thoughts out loud as I did research into shadows and elevation, since I'm new to shadows/elevation in Flutter. Don't take these explorations as recommendations to do anything, but as situations to consider and as some context to the problem.
> 
> From what I understand, like @AyushBherwani1998 said, `MergeableMaterial` uses `kElevationToShadow` to use a set of `BoxShadow`s to generate the widget's shadows.
> 
> Some other widgets use `PhysicalModel` simply takes an `elevation` double, which represents the z-coordinate of the widget and paints it [a different way](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L1795). I'm actually still not sure how the offset for the shadow generated by `PhysicalModel` is defined, and it seems it doesn't account for spread radius and blur radius like `BoxDecoration` does. `BoxDecoration` takes a list of `BoxShadow`s and has its [own opinion on how to paint shadows](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_decoration.dart#L435) compared to `MergeableMaterial` (MergeableMaterial implementation available [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/mergeable_material.dart#L691)).
> 
> `MergeableMaterial` is also hard-coded to use a `Card`'s [RRect default border radius](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/mergeable_material.dart#L699), so we need to decide if this should be flexible as well.
> 
> @tudor07 Can you further clarify what type of control over elevation you need?
> 
> Edit: Might be useful, but this is how Material Design described elevation: https://material.io/design/environment/elevation.html

I'll have a look at different ways these widgets are painitng and do a little bit of research since I'm not very familiar with painting layer and how the `boxShadows` are defined for every default value.

**Comment by AyushBherwani1998** [comment]
>@AyushBherwani1998 Providing customization of the divider color does not seem as complex as >the shadow problem. It should be okay to expose a dividerColor property through >MergeableMaterial and then to ExpansionPanelList.
So, if we are going to expose the `dividerColor` for `MergeableMaterial` should I create a new issue and submit a PR, or a PR with both the changes is okay to go?

> Does updating `DividerTheme` already modify the divider color for `ExpansionPanelList`? If it doesn't we should be careful about adding that functionality, since that could be a breaking change for users already using `DividerTheme` and `ExpansionPanelList`.

Changing the `Theme.dividerColor` and `Theme.dividerTheme` updates the divider color usesd for `ExpansionPanelList`.

**Comment by shihaohong** [comment]
> So, if we are going to expose the dividerColor for MergeableMaterial should I create a new issue and submit a PR, or a PR with both the changes is okay to go?

You can create two separate PRs for the different features, but just link both PRs to this issue

> Changing the Theme.dividerColor and Theme.dividerTheme updates the divider color usesd for ExpansionPanelList.

Great, so wiring the parameter through while respecting the theme values should be pretty straightforward!

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR to expose `dividerColor` property in `ExpansionPanelList`. Looking forward to reviews 😄

**Comment by AyushBherwani1998** [comment]
@shihaohong I did check how other widgets provide elevation. As you said widgets that use `Material` provide elevation using `PhysicalModel`. It feels like if we want to provide the customizable elevation it will require a code refactoring to see if it's possible to incorporate it or not. 

Instead of doing that, we can also provide two properties, the `elevation` and `boxShadow`. The `elevation` property will expose the predefine sBoxShadow`'s and if users want a custom `elevation` they can define their own `BoxShadow`. For implementation, we can check if `boxShadow` is not `null` we will override the `elevation`. We can mention this behavior in the docs too.

**Comment by shihaohong** [comment]
I think that the solution can be okay -- I'm hesitant on the API because it took us some digging into the implementation details of the widgets before we figured out the differences between `elevation` and `boxShadow` for the variety of widgets that want to display a shadow/elevation. 

Could we defer to @tudor07 -- What level of control over elevation are you looking for? Is there any component of existing widgets' elevation controls/APIs that confuse you and would prefer to be different?

**Comment by AyushBherwani1998** [comment]
> Could we defer to @tudor07 -- What level of control over elevation are you looking for? Is there any component of existing widgets' elevation controls/APIs that confuse you and would prefer to be different?

Makes sense to me to find a way to introduce elevation property after we have the needs.

**Comment by shihaohong** [comment]
@tudor07 any updates on what you are looking out of the elevation feature?

**Comment by tudor07** [comment]
I just needed to remove it entirely (eg. make it `0`)

**Comment by shihaohong** [comment]
If that's the case, maybe we can just stick with the predefined `BoxShadows`, since those are readily available and easier to use/define through a simple `elevation` property. If the need ever arises for more granular control, we can always consider exposing a `boxShadows` property and figure out how to make the API as simple as possible. WDYT @AyushBherwani1998?

**Comment by AyushBherwani1998** [comment]
SGTM, I'll try to submit a PR exposing the `elevation` property of `MergeableMaterial`.

**Comment by AyushBherwani1998** [comment]
@shihaohong I guess we can provide the `elevation` property but before that, we may need to add a new mapping in `kElevationtoShadow`. Since the [default elevation for material design](https://material.io/design/environment/elevation.html#default-elevations) also has 0 elevation value, I think we can add it. WDYT?

**Comment by shihaohong** [comment]
@AyushBherwani1998 Creating a zero option seems reasonable to me. I'm surprised it doesn't already exist given that it's a default value for some of the existing widgets like TextButton, standard side sheet or top app bar. Maybe since "zero" elevation just meant omitting any widgets that painted shadows, it was left out as a mapped value for 0, so it should be fine to add it. 

cc/ @HansMuller if he has any insights to the lack of the `kElevationToShadow[0]` map, but it looks good to me on the face of it.

**Comment by AyushBherwani1998** [comment]
I would also like to know how the mapping of elevations to shadows is done, and the calculations behind it. I found [this](https://web.archive.org/web/20140628054353/http://www.google.com/design/spec/layout/layout-principles.html#layout-principles-dimensionality) on web archive which explains the shadows and depths, but I'm not entirely sure if this is valid due to changes in the Material. But, in the above link also, I'm confused about how the calculations are done for the depicting depth.

**Comment by shihaohong** [comment]
I just spoke with Hans about the source of the list of `BoxShadow`s and apparently the values were derived from some source internal to Google, but unfortunately is not on the Material spec. In the event that the shadows/elevation implementation ever changes, we'll need to retrieve these values from the designer.

**Comment by AyushBherwani1998** [comment]
Thanks for informing :)

**Comment by AyushBherwani1998** [comment]
@shihaohong I guess we can close the issue since the support to customize the elevation has been added with #62840

**Comment by shihaohong** [comment]
I'll close the issue since both requested features have been added. Thanks for working on this @AyushBherwani1998!
