### ISSUE TITLE
--enable-vulkan-validation-layers should set skia_enable_vulkan_debug_layers to true 

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#51376]

**Comment by chinmaygarde** [comment]
That flag appears to be unused in Skia. All it does is set `SK_ENABLE_VK_LAYERS` which doesn't seem to have any users in Skia. We should see if that flag is actually necessary.

**Comment by chinmaygarde** [comment]
That flag is only used by Skia to setup validation layers in their tools and tests. Since Flutter already creates the Vulkan application instance as well as the device before creating the GrContext used by Skia, all validation layer setup must occur in Flutter.

Setting this flag is immaterial to the setting up of validation layers in Skia.
