### ISSUE TITLE
How run flutter command if I removed all the git files

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#51400]
How run flutter command if I removed all the git files， I have customed the flutter sdk on a stable version and save it on my git repository, but the flutter needs itself git, two git will conflict when CI. How to fix the errors when I removed the flutter original git?

**Comment by TahaTesser** [comment]
Hi @ping996 
You need git files ` The flutter tool requires Git in order to operate properly;`
You can fork stable branch from stable branch and make your changes in your forked repository.

For questions like these 
Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow. Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
