### ISSUE TITLE
Flutter url_launcher canLaunch() method returning false on some (valid) web schemes

### ISSUE THREAD

**Issue by vazkir** [flutter/flutter#51471]
## The problem

Some valid url schemes seem to work (so the launch() method doesn't fail), even-though the url_launcher's canLaunch() method on flutter web returns false.

These are some examples:
- canLaunch("whatsapp://send?text=testing");
- canLaunch("twitter://post?message=testing");

## Information

I have tested this on:
- My Safari browser on my Iphone XR
- Google chrome on my macbook
- Samsung J3's default browser

## A solution?

Could this be fixed? Or is this not possible since you're trying to open apps from a web environment?

Thanks in advance for any help!

**Comment by mobikats** [comment]
I am also getting a false response recently on file reference URLs that are valid, of the form:

https://valid.host.com/media-documents/Copy%20of%20BBB%20MY%2021%20Product%20Guide`05022021-114813.pdf

If I open the same link in the mobile browser it happily opens it.

If I don't run canLaunch() and just call launch(), it crashes (I'm not managing to even get a stack trace so far but will try and have a closer look).

**Comment by stuartmorgan** [comment]
@ditman We should probably document the web limitations of `canLaunch` in the README.

**Comment by ditman** [comment]
Or maybe just return `true` on canLaunch for the web. The web can launch any URL, really :) It's not like we can check if there's a protocol handler attached to a specific URL within the browser!

**Comment by stuartmorgan** [comment]
Returning true for arbitrary protocol handlers that aren't actually going to launch is not great either though.

Another option would be to do a breaking change to return an enum with true/false/unknown.

**Comment by mobikats** [comment]
My problem turned out to be the inverted comma in the URL example I posted above. Encoding those to 06 (iirc) solved the problem. Strangely though Safari would happily open the original with the inverted comma.

**Comment by ditman** [comment]
> Another option would be to do a breaking change to return an enum with true/false/unknown.

@stuartmorgan we cannot tell the difference between "false" and "unknown" in the web. If you ask canLaunch(x) and it tells you "false", in web it means "unknown".

Maybe letting users pass [their own set of accepted protocols](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L35)?

That way in web we can return "true" whenever we hit one of those.

@10686142 in my macbook (without a twitter desktop client, nor whatsapp installed, neither of the links you provided do anything, as expected :P)

**Comment by ditman** [comment]
I'm labeling this P6 until we have a clear path to resolution. What'd be a good solution for this? (considering that you can't effectively check what protocol handlers are registered on a browser, you don't know what schemes it's going to be able to even attempt to handle)

**Comment by stuartmorgan** [comment]
> @stuartmorgan we cannot tell the difference between "false" and "unknown" in the web. If you ask canLaunch(x) and it tells you "false", in web it means "unknown".

Right, but that's fundamentally different than what `false` means in other platforms. I'm not saying we should have three states because web has three states, I'm saying that we have three states across the set of platforms we support, and shoehorning web into the two we currently have creates a confusing mismatch.

If we had three states in the API, people would need to think about all three possibly cases and design their flows accordingly, instead of thinking they will always get a yes/no and then probably having their code do the wrong thing on web.

**Comment by ditman** [comment]
Gotcha, so web would return 'unknown' instead of 'false' in that 3-state return, to standardize the weirdness of the web. Sounds good.

**Comment by 10686142** [comment]
I did [find a possible solution](https://stackoverflow.com/questions/627916/check-if-url-scheme-is-supported-in-javascript/14706422#14706422) to validate if a url can be opened to other platforms like twitter of facebook, but then you would have to work with timeouts in javascript

**Comment by ditman** [comment]
> I did [find a possible solution](https://stackoverflow.com/questions/627916/check-if-url-scheme-is-supported-in-javascript/14706422#14706422) to validate if an url scheme, but then you would have to work with timeouts in javascript

@10686142 I've seen some solutions like that, but all depend on watching what the browser does *after the click happened*; this isn't something that we can do in the `canLaunch` method, I think!

If you want to try and integrate the solution above, you can do so modifying stuff around [here](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L70) :)

**Comment by singhteekam** [comment]
If you just simply try launch(url) rather than canLaunch(url) then it's working fine for me. I think this is a temporary solution to resolve the issue.

Try this:
void _launchURL() async {
   const url = 'https://pub.dev/packages/url_launcher';
  await launch(url);
 }

**Comment by mdrideout** [comment]
Spotify web links open the native spotify app with the following protocol + string: `spotify:track:0L9c80qCCy5EBI3X714nSK?context=spotify%3Auser%3Aboon4376%3Acollection`

I have a custom protocol for my users, to open a specifically registered app in windows. 
I am aware of only one condition where this will work for my users, if the Flutter App is running on Flutter web, and the operating system is Windows. 

I can do this in flutter with `kIsWeb` and `defaultTargetPlatform == TargetPlatform.windows`

However, I do not have another way to detect whether the application is actually installed and "canLaunch".

## How Spotify Handles This
- If the spotify desktop app is not installed on windows, and one attempts to use "**Open in Desktop App**" from Spotify's web player, the following happens: **nothing**. 
- A new tab will open to that protocol + string, but nothing else happens. No warnings, nothing.

If my users click multiple times, I may show an alert to ensure the program is correctly installed on their Windows PC. Otherwise, If spotify is getting away with that, it seems like a common endpoint. 

### However,
It would be great if one could register or define custom "canLaunch" scenarios with the plugin. Otherwise, one can resort to creating their own functions for checking custom circumstances.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/79043#issuecomment-1102942482 for why this was closed. However, the README, API docs, and example have been significantly changed to make the limitations of `canLaunch` clear, and to recommend against using it in most cases.
