### ISSUE TITLE
Add missing MaterialButton parameters to OutlineButton

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#51573]
## Use case

I need a bunch of [OutlineButton.icon](https://api.flutter.dev/flutter/material/OutlineButton/OutlineButton.icon.html) instances, but I need them with a `minWidth` so they look pretty stacked.

## Proposal

There are a few [MaterialButton](https://api.flutter.dev/flutter/material/MaterialButton-class.html) parameters missing from [OutlineButton](https://api.flutter.dev/flutter/material/OutlineButton-class.html) such as:
* `minWidth`
* `height`

Why can't those be added to `OutlineButton` too?

My alternative is to create my own OutlineButton just so that I can pass `minWidth`.

**Comment by Piinks** [comment]
OutlineButton has been removed from the framework, and it is replaced by OutlinedButton now. 
You can use ButtonStyle in order to style the button now (including minimum and fixed sizes), and have it be inherited using OutlinedButtonTheme. That way you do not have to apply it to all of the buttons, and they will all have a uniform appearance. :)

I think this issue has been resolved, but if it hasn't, please let us know and we will take another look.

https://docs.flutter.dev/release/breaking-changes/buttons
