### ISSUE TITLE
Warn developers if they try to decode too many pixels in a single frame or small number of frames.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51584]
A not-uncommon issue for Flutter users is finding that they get OOM killed when they:

- Create a large list of images that ends up eagerly loading the whole list at full resolution
- Attempting to precache a lareg number of images (e.g. sprites) at too high of a resolution
- Repeatedly and rapidly try to decode a large image that is not getting cached or is getting evicted from the cache

The experience is particularly unpleasant right now because the app just disappears, usually with no errors/logs, unless a native debugger is attached in which case you might see something like `Terminated due to memory issue`.

I suspect we could help users here by adding something to the `PaintingBinding`'s `instantiateImageCodec` indirection that tracks how many images you've tried to decode in the last `N` frames.  If that value goes too high for the number of frames, we either assert or print a warning that this behavior is not safe, may OOM, and should probably be redesigned (e.g. lazilly loading images when they're needed, or making sure to load them at a lower resolution).  We could even tune this so that it's more permissive if they're providing the `cacheHeight` and `cacheWidth` parameters as opposed to just using the native image dimensions.

I'm not entirely sure this makes sense on every platform, e.g. an older iPhone vs a high end desktop workstation with tons of RAM.  But I do suspect that decoding _lots_ of images in a handful of frames is usually a mistake, at least for some value of _lots_, and that our users do this and don't understand why it's broken.

See also: 

- https://github.com/flutter/flutter/issues/51046
- #28037
- #32143
- https://github.com/flutter/flutter/issues/50697

**Comment by dnfield** [comment]
This would help address part of the concerns in https://github.com/flutter/flutter/issues/50024

**Comment by dnfield** [comment]
We could vastly improve this and warn based on actual pixel sizes if we added the proposal in https://flutter.dev/go/encoded-image-dimensions to the framework.  /cc @goderbauer @Hixie

**Comment by Vikrech** [comment]
Hi @dnfield 
I have experienced a similar issue, where memory consumption of my app took my attention. To keep story short,I have tested on pretty simple app with Scaffold and Image loaded from asset bundle on different channels and versions of flutter and see consistent pattern between image resolution and how much external memory it takes. The single image was a square shape with a solid color, and interestingly, the size of the image did not greatly affect the final result. Testing deveice is a Pixel 2 xl Android 10. 

4096px -> 89mb 
2048px -> 22mb

In my case, my application loads a few images (10 to be precise) in similar largest size, and that cost me a little less 1gb of external memory.

**Comment by dnfield** [comment]
@Vikrech - could you provide your exact image dimensions? 

The basic formula should be w*h*4*1.3 to get the number of bytes used for an image.

**Comment by Vikrech** [comment]
Sure, the exact image sizes are 2048x2048 and 4096x4096 respectfully. Maybe you are quite right with the formula btw.
Another fact is that when I just use method to fetch ByteData using root bundle and conver it from uint8list to Image used by Painter class, it was bring me to exact same picture with memory consumption.

**Comment by dnfield** [comment]
Yes - those size images are quite large and will take up the amounts of memory you're saying.  You can use the `cacheWidth` and `cacheHeight` parameters to downsample them to the resolutions you will actually display at.

**Comment by Vikrech** [comment]
Good point, but actually in such large image (4096x4096) i have 64 animation frames with 512x512px size)

**Comment by jacob314** [comment]
Fyi @terrylucas

**Comment by sobrienpdx** [comment]
I'm having the same problem... too many SVGs and my app crashes due to OOM. We use  PageView() for swiping between cards with SVG images rendered using flutter_svg library.   If there are too many pages with SVG images, the app runs out of memory and results in a crash with no stack trace. The Flutter dev tools show no issues with memory but the Xcode debug navigator shows that with each swipe on PageView more memory is used.

Our SVGs consist of one medium resolution jpeg background image with some text on top. We can't get our SVG file size any lower without sacrificing user experience. Is there a way to do garbage collection on the SVGs that are not being currently rendered? What objects in flutter_svg are hidden memory consumers that I can do garbage collection on?

**Comment by dnfield** [comment]
@sobrienpdx you should file a bug against flutter_svg for that.

I will say that images embedded in svg will generally give you less control over this and it would likely be better to use the image directly rather than in an svg

**Comment by sobrienpdx** [comment]
@dnfield  thanks, I have done so here: https://github.com/dnfield/flutter_svg/issues/388

**Comment by kbokarius** [comment]
I've been running into this. I have a 3840x5760 image that I was using as a static background for the app. Memory usage was up at around 150mb total on an iPhone 11 Pro. I then calculated the smallest size the image can be resized to while keeping the aspect ratio and used ResizeImage to scale the image down. The result was a drop to 100mb in memory usage, but if you look closely you can see the image is slightly more blurry and pixelated than the original image.

@dnfield instead of using ResizeImage to scale down the image, is there a way to cut out the center of an image based on a height and width? In other words, instead of scaling and changing the quality of an image, is there a way to crop away the top, bottom, left and right parts of an image and have the result be the image stored in the ImageCache? I'm wondering if that'll result in a higher quality image being displayed to the user.

**Comment by dnfield** [comment]
We don't currently provide any ways to crop an image. You could use `package:image` to do that, maybe on a first run and store the result in a cache dir. Otherwise, you could ship the properly cropped sizes so your users only get the right size based on their device.

**Comment by dnfield** [comment]
I'm going to close this as fixed based on debugInvertOversizedImages.
