### ISSUE TITLE
StreamBuilder doesn't update when a new value added in another screen.

### ISSUE THREAD

**Issue by vulongc3** [flutter/flutter#51681]
## StreamBuilder doesn't update when a new value added in another screen.
I have a project created by using provider and RxDart stream to manage states and actions, I have a BehaviorSubject named _page_subject to manage currently displaying page on my screen;
I expect:
1. When I press a navigation button, _page_subject.sink adds new page.
2. When _page_subject.sink added new page, StreamBuilder rebuilds;

![image](https://user-images.githubusercontent.com/54987362/75599305-3ceeb700-5ad6-11ea-8306-3e40555e74a7.png)

```
//home-screen-controller.dart
void navigate_to(Widget page_route) {

  //_page_subject.sink
  page_sink.add(page_route);

 //log new value of _page_subject
  print(_page_subject.value);
}

static Home_Screen_Controller of(BuildContext context) {
  return Provider.of<Home_Screen_Controller>(
    context,
    listen: true,
  );
}
```
```
//home-screen.dart
Widget build(BuildContext context) {
  Color primary_color = Theme.of(context).primaryColor;

  //a static function defined to returns Provider.of<Home_Screen_Controller >(context, listen: true);
  Home_Screen_Controller home_screen_controller = Home_Screen_Controller
  .of(context);

  return StreamBuilder(
    builder: (context, snapshot) {
      Widget home_page = snapshot.data ?? SizedBox();

      return Scaffold(
        appBar: AppBar(
          actions: [

            //navigate to profile button, works OK.
            IconButton(
              icon: Icon(
                Icons.account_circle,
                color: primary_color,
                size: 30,
              ),
              onPressed: () => home_screen_controller
              .navigate_to(Profile_Screen()),
            ),
          ],
          ...

          //navigate back to home screen button, works OK.
          leading: IconButton(
            icon: Icon(
              Icons.arrow_back_ios,
              color: primary_color,
            ),
            onPressed: () => home_screen_controller
            .navigate_to(Main_Menu_Screen()),
          ),
         ...
        ),
        body: home_page,

        //defined in bottom-navigation-bar-screen
        bottomNavigationBar: Bottom_Navigation_Bar(),
      );
    },

    //_page_subject.stream
    stream: home_screen_controller.page_stream,
  );
}
```
```
//bottom-navigation-bar.dart
//build bottom navigation bar
Widget build(BuildContext context) {
    Navigation_Bar_Controller navigation_bar_controller = Navigation_Bar_Controller.of(context);
    Home_Screen_Controller home_screen_controller = Home_Screen_Controller.of(context);

    return StreamBuilder<List<Bottom_Navigation_Bar_Item>>(
      builder: (context, snapshot) {
        List<Bottom_Navigation_Bar_Item> bar_items = snapshot.data ?? new List();

        return Material(
          child: Container(
            child: Row(
              children: bar_items.map((bar_item) => bar_item.to_button(

                //test to make sure everything doesn't go wrong, but It does go wrong
                //_page_subject.value is Notification_Screen but StreamBuilder doesn't rebuild.
                () => home_screen_controller.navigate_to(Notification_Screen()), 
                primary_color, 
                false,
              )).toList(),
            ),
        ...
    //Material ends
    );
  }
```
When I pressed profile button or back to home button, everything was fine. But when I pressed bottom navigation buttons, 'Notification_Screen' was logged, but StreamBuilder in home-screen.dart didn't rebuild.

**Comment by hoshinokanade** [comment]
Hi there. I attempted to replicate your app however did not come across with the mentioned problem. I think the code where the Provider widget in is also important.

I have come cross similar problems before, most of the time if I log also the hash code then I spot out there are actually more than one instance of the controller. As different parts of app rely on different instances of the controller, then StreamBuilder obviously do not update. 

btw, you might be using Provider incorrectly because `listen: true` implicate to rebuilt the widget when the provided value is swapped (i.e. in this case, the instance of the controller). I suggest to use `Selector` from the provider package when you need to use the current value of the controller.

btw again, you looks like coming from react native. We are pleased to have you in the Flutter community!
You are encouraged to follow the naming practice from [Dart style guide](https://dart.dev/guides/language/effective-dart/style), and also as Flutter comes with many builtin widgets for navigation, you might found that there is lessened need of doing navigation using the bloc pattern.

**Comment by iapicca** [comment]
Hi @vulongc3 
Streams between pages seem to work just fine ([code sample](https://dartpad.dev/68ab1d902a8cc3d8c7c75bbd360e8826)),
please note that both [rxdart](https://pub.dev/packages/rxdart) [[github](https://github.com/ReactiveX/rxdart/issues)] and [provider](https://pub.dev/packages/provider) [[github](https://github.com/rrousselGit/provider/issues)]
are third party packages, if you believe the issue is related to one of these packages
please open an issue in the dedicated github.

This platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
