### ISSUE TITLE
CupertinoTabBar set height

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#51704]
Is there a way to set height of CupertinoTabBar height?

**Comment by thearaks** [comment]
Shouldn't this issue be included in Project 124 (_Mobile - Cupertino widget review_)?
https://github.com/flutter/flutter/projects/124

Also, this is probably a trivial fix:
- Add a `height` attribute to the constructor that defaults to `_kTabBarHeight`
- Use `height` in `preferredSize` and `build` methods instead of `_kTabBarHeight`
- An assertion to verify that `height` is non-negative will be needed

**Comment by jinfagang** [comment]
I think this is reasonable. @thearaks

**Comment by najeira** [comment]
I created https://github.com/flutter/flutter/pull/72919 last year.

Please vote if you want this to be merged!
