### ISSUE TITLE
Error: package androidx.lifecycle does not exist while building release apk

### ISSUE THREAD

**Issue by rakeshh025** [flutter/flutter#51765]
I'm trying to build a release apk by `flutter build apk`. Here's the error I get :

```
D:\flutter\flutter_windows_v1.12.13+hotfix.5-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\pl
ugins\lifecycle\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
import androidx.lifecycle.Lifecycle;

                        ^
D:\flutter\flutter_windows_v1.12.13+hotfix.5-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\pl
ugins\lifecycle\FlutterLifecycleAdapter.java:22: error: cannot find symbol
  public static Lifecycle getActivityLifecycle(
                
  symbol:   class Lifecycle
  location: class FlutterLifecycleAdapter
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
```

Here's flutter doctor -v : 

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Applns\Sdk\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Applns\Sdk\Sdk
    • Java binary at: D:\Applns\AndroidStudio3.4.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\Applns\AndroidStudio3.4.1
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @rakeshh025 
Can you please try `flutter clean` and then provide `flutter build apk --verbose` here?
Thank you

**Comment by KabluBR** [comment]
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE

           Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
           Use '--warning-mode all' to show the individual deprecation warnings.
           See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings
           17 actionable tasks: 1 executed, 16 up-to-date

[   +3 ms]
C:\DEV\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.4\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle
\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
           import androidx.lifecycle.Lifecycle;
                                    ^

C:\DEV\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.4\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle
\FlutterLifecycleAdapter.java:22: error: cannot find symbol
             public static Lifecycle getActivityLifecycle(
                           ^
             symbol:   class Lifecycle
             location: class FlutterLifecycleAdapter
           2 errors
           
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           Execution failed for task ':compileReleaseJavaWithJavac'.
           > Compilation failed; see the compiler error output for details.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 9s
           Picked up _JAVA_OPTIONS: -Xmx512M
           
[  +21 ms] "flutter apk" took 252.626ms.
The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by riansyaaah** [comment]
Hi,

finally, I fix it this error with steps:
1. Make sure your flutter_plugin_android_lifecycle using gradle 5.4.1
2. Delete your pubspec.lock in your project
3. _flutter clean_
4. _flutter pub get_

Now you can _flutter build apk_. 
Hopefully can help you :)

**Comment by TahaTesser** [comment]
Hi @rakeshh025  @KabluBR 
Please take a look this possible [solution](uhttps://github.com/flutter/flutter/issues/51765#issuecomment-601493234l) comment above
Thank you

**Comment by KabluBR** [comment]
Hi guys, thanks for the answer, but it still the same... tried the solution but gave same results...

**Comment by P-B1101** [comment]
not helping me either

**Comment by rakeshh025** [comment]
My issue was with url_launcher package version. I updated it and it resolved

**Comment by KabluBR** [comment]
this not solves my issue...

**Comment by TahaTesser** [comment]
Hi @KabluBR 
Could you please create a new issue and provide all the necessary details?
Each system is different
thank you

**Comment by wugemu** [comment]
修改gradle-wrapper.properties
distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip
android.useAndroidX=true
android.enableJetifier=true

修改android/build.gradle
classpath 'com.android.tools.build:gradle:3.5.0'

修改编译版本为 compileSdkVersion 29

its work！

**Comment by skyberk** [comment]
Thanks @wugemu my gradle version newer(gradle-5.6.2-all.zip) then you suggest so I just changed compileSdkVersion and targetSdkVersion to 29. And it works.

**Comment by PiN73** [comment]
Related: https://github.com/flutter/flutter/issues/60883

**Comment by berrylawchingman** [comment]
Ok
