### ISSUE TITLE
[gen_l10n] Notify users if message translations are missing that are defined in the template ARB file

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#51778]
In new `localization` command in flutter dev tools, it seems must implement all translation in other language.
Steps to produce:
1. I have upgraded my flutter under `master` channel.
2. 
```
${YOUR_FLUTTER_PATH}/dev/tools/localization/bin/gen_l10n.dart \
    --template-arb-file=intl_en.arb \
    --output-localization-file=localizations.dart \
    --output-class=Localizations
```

3. `flutter format .`

It creates a class like `class LocalizationsFa extends Localizations` for my `fa` language and must implement all `en` phrases, but in previous version no needs to implement all translation for `fa` or other languages.

my flutter doctor output:
```
[✓] Flutter (Channel master, v1.15.4-pre.240, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)
```

**Comment by shihaohong** [comment]
To clarify, is the issue that you currently need to implement messages for languages other than the template language when you didn't have to before? What have you been doing before when your ARB files did not contain the translation in a locale other than the template? For example:

**app_en.arb as template**
```json
{
  "helloWorld": "Hello World.",
  "greetings": "Greetings!"
}
```

**app_fa.arb**
```json
{
  "helloWorld": "Hello World."
}
```

**Comment by shihaohong** [comment]
^If that's the case, we're planning on handling that eventually -- We plan on doing so by using overriding the [NoSuchMethodError](https://api.dart.dev/stable/2.7.1/dart-core/NoSuchMethodError-class.html) class and having the tool automatically display some placeholder String like "Please implement me" or just default to the base localization's string.

**Comment by aliyazdi75** [comment]
Yes this scenario is what be expected that `greetings` in `locale('fa')`  equals to template language like `en` and shows `Greetings!`

**Comment by shihaohong** [comment]
In the flutter gallery, the the template language is used because a script is used to generate the ARB files internally at Google. If the translations do not exist, it simply uses the template file's messages in the ARB file.

See [an example of what I mean here](https://github.com/flutter/samples/pull/329/files#diff-8e6969f24f64e79a4fecc8cea29ab839L19) -- The Flutter Gallery app has its own placeholders for when the translated message does not yet exist.

Thinking about it again, I actually do not think we should be creating these placeholders by default since developers may not want this behavior, and it could also hide the fact that the placeholders are being used instead of actual translated messages. I think instead, we should display an error warning and/or suggesting to the developer to add a message or a placeholder themselves.

**Comment by aliyazdi75** [comment]
I think manually placeholder is a good idea, but the actual template language also is a good idea, like what script does.
Is that script open source? It's very usable :)

**Comment by shihaohong** [comment]
It's not open source, but the meat of it is basically:
1) read the template ARB file and parsing it (ARB files are basically JSON files, so you can use json.decode if you're writing a Dart script)
2) reading the rest of the ARB files and parsing them
3) iterate over the template ARB file's messages. wherever you see a missing message from the template ARB file, add the message and the placeholder message (could simply be the template ARB message) as a key/value pair
4) overwrite the existing ARB files with the new ARB files containing a placeholder.

**Comment by aliyazdi75** [comment]
oh thank you, may be this script can be contained in `gen_l10n.dart` :)

**Comment by shihaohong** [comment]
It could be an optional feature, although it is likely more involved than expected, so I may not be able to get to it in the short term. 

I'm concerned that there are edge cases or problems that I have not considered, so I want to make sure it's well thought through before we add behavior like this into the tool. However, I will add a clearer error message to the tool so that developers understand the problem that they're currently facing.

**Comment by shihaohong** [comment]
I've separated this feature from https://github.com/flutter/flutter/issues/53767. This issue will track figuring out if a message that exists in the template ARB file is not translated. The other issue tracks handling calling getters/methods that do not exist yet and using a placeholder message.

**Comment by shihaohong** [comment]
This issue has been resolved. The remaining work of having a default value for completely unimplemented methods/getters will be tracked in https://github.com/flutter/flutter/issues/53767
