### ISSUE TITLE
Default Android page transition

### ISSUE THREAD

**Issue by carlowenig** [flutter/flutter#52113]
Hi there,
I am struggling to find a way to use the normal Android transition (sliding in from the right) as a Page Transition. The default transition of MaterialPageRoute seems really out of place compared to other Android apps.
For now I am using the CupertinoPageRoute, because it comes closer to the familiar Android behavior than the MaterialPageRoute, but it is not quite the same. I tried to use a custom slide in transition, but it always seemed a bit off. Is there a way to just use the native page transition of the installed system?

Thanks!

**Comment by Zazo032** [comment]
The default navigation transition is usually the latest from each OS. In Android, it'll be changed to the one on Android 10 here: https://github.com/flutter/flutter/pull/51538

You can read more info about that here: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior

You're probably using an Android device with an outdated navigation transition or with some kind of Android skin, so maybe people with newer devices will feel the app is out of place. I don't think there's a native implementation in Android for that transition, so that may be something custom from an OEM (like Huawei, Xiaomi, etc.)

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @carlowenig, could you describe which page transition you're referring to? A few [are listed](https://master-api.flutter.dev/flutter/material/PageTransitionsBuilder-class.html) in the `PageTransitionsBuilder` documentation. I can take a look at whichever one you feel isn't fully matching the native OEM one. 

I don't think there's a way to use the native page transition as far as I can tell

**Comment by carlowenig** [comment]
Thank you, for your replies. I've settled with the Android 10 transition now.
