### ISSUE TITLE
How to animate marker smoothly?

### ISSUE THREAD

**Issue by feel2174** [flutter/flutter#52186]
0

I'm developing custom marker on google map using Flutter.

I just want to know about Marker.

Can I implement marker animation smootly??

ex. LatLng(xx.xxxxxxx) => LatLng(yy.yyyyyyy) when marker move, it has to move smoothly.

please refer to this image. https://github.com/flutter/flutter/issues/31180

**Comment by dnfield** [comment]
This is not currently written as a bug report or a feature request, and would be better suited for a site like StackOverflow. Given the linked issue, it sounds like the requested feature is possible, so I'm not even sure this would make sense as a feature request.

I'm going to reluctantly close this since it's not actionable in its current state for this issue tracker.
