### ISSUE TITLE
How to reuse identical MacOS and iOS code in a plugin

### ISSUE THREAD

**Issue by ryanheise** [flutter/flutter#52285]
In some cases it is possible to add MacOS support to a plugin by simply copying `ios/Classes/*.m` to `macos/Classes/*.m` and making some small changes to the headers and podspec (as demonstrated by this PR: https://github.com/ryanheise/just_audio/pull/54). As @sachaarbonel (the author of that PR) wrote:

> This this how sqflite did it and there are no best practices instructions from the flutter team so until then ...

If it were possible to reuse the code, that would make maintenance a lot easier when new features are added.

In that example, within the `*.h` files, the only difference is:

```objc
#import <FlutterMacOS/FlutterMacOS.h>
```

vs

```objc
#import <Flutter/Flutter.h>
```

But the `*.m` code is identical and works on both platforms.

Given that iOS and MacOS do largely offer the same set of APIs, I think this use case could be quite common, but I do not see any Flutter documentation or examples on how to reuse an identical iOS/MacOS implementation.

The documentation (https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-project) refers to the following official plugin examples as a guide: `url_launcher`. `shared_preferences`, `connectivity`, `path_provider`. However, these don't show how to reuse code that is identical. On the contrary, those examples actually implement the iOS side in Objective C, and the MacOS side in Swift, so there is definitely no code reuse.

**Comment by stuartmorgan** [comment]
This was discussed a couple of times, but never captured in a bug. I think we should pick some recommended practice and have one flutter/plugins plugin use it—so there's an example that we can point to, and so that we'll know immediately if it breaks.

Distilling down the discussions, the options I know of are:
1. Move the bulk of the logic to a separate Pod, and have both the macOS and iOS versions use it.
    - This is somewhat cumbersome, and doesn't help avoid the duplicate boilerplate-ish code binding the method channel logic to that core.
1. Symlink (see [firebase_core](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core) for an example):
    - This currently works. It does depend on internals (the fact that we symlink the whole plugin directory, not just the specific platform), which isn't ideal even that that internal detail seems very unlikely to change, and it feels a bit hacky. But it requires no special tool support, which is very nice.
1. Add a `platformDirectory` (or similar) key for iOS and macOS pubspec definitions, allowing them to point to a different directory for the implementation.
    - This would allow sharing a `darwin` directory like that used `firebase_core`, but without symlinking. It would even allow for a shared podspec (and wouldn't have the odd property of the symlink solution that it's not actually valid as a Pod, only as a Flutter plugin). But it would have backward compatibility issues that we would need to address, and add tool complexity.

**Comment by stuartmorgan** [comment]
> those examples actually implement the iOS side in Objective C, and the MacOS side in Swift

FWIW, that's because Swift is the plugin language for Flutter on macOS; there has never been a plugin template for macOS plugins that uses any other language. ObjC works without wrapping only because modules abstract out the details of the interface language, not because it's an official plugin language for macOS the way it is for iOS. Having the initial plugins do something other than the expected, recommended practice for developing macOS plugins would have been confusing.

**Comment by stuartmorgan** [comment]
Capturing from offline discussion: In addition to picking a flutter/plugins example+testcase, we can add a flutter_tools test that explicitly validates that the symlinking is providing all the platform directories next to eachother (which is the internal detail that the plugin-level symlinking relies ons), with a comment explaining why that must continue to be true.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/2618 will add an example of symlinking.

**Comment by ryanheise** [comment]
Hi @stuartmorgan , will the symlinking approach also work for Swift, or only Objective C?

**Comment by stuartmorgan** [comment]
I don't know that anyone's tried, but I can't think of any reason it wouldn't work with Swift. You'd need to `#if os(OSX) ... #elseif os(iOS) ... #endif` or similar for the Flutter include, but otherwise it seems like it should work the same way.

**Comment by ryanheise** [comment]
Ah, I see. I assumed the whole directory was being symlinked and wondered if this would have worked with Swift, but I see now that this example symlinks just the implementation files which removes a lot of the mystery about how that would work with Swift. Thanks for the pointer!

**Comment by namniav** [comment]
> [flutter/plugins#2618](https://github.com/flutter/plugins/pull/2618) will add an example of symlinking.

@stuartmorgan  Thank you for the example!
But there is a bit wired that symlinks to folders do not work when their names are contained in `spec.source_files`, and I have to replace the symlink's name to `*` or `**` pattern.

With this tree:
```
├── macos
│   ├── native_lib
│       └── src -> ../../native_lib
│   └── my_plugin.podspec
└── native_lib
    └── src
        └── native_code.c
```
`spec.source_files = 'native_lib/*/*.c'` works,
`spec.source_files = 'native_lib/**/*.c'` works,
`spec.source_files = 'native_lib/src/*.c'` DOES NOT WORK.

**Comment by namniav** [comment]
> [flutter/plugins#2618](https://github.com/flutter/plugins/pull/2618) will add an example of symlinking.

@stuartmorgan Symlinking folders do not work. Both [firebase_core](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core) and [package_info](https://github.com/flutter/plugins/tree/master/packages/package_info) symlink every files. Can I just symlink a folder(eg. symlink `macos/Classes/my_native` to `../../ios/Classes/my_native`) instead of every files inside it?

(I deleted my last comment because I messed up something and that comment could be much misleading and confusing. Sorry:confused:)

**Comment by ryanheise** [comment]
I have been using the symlink successfully for a while, but just now I encountered this when attempting to publish [just_audio](https://pub.dev/packages/just_audio):

```
$ flutter packages pub publish
....
Do you want to publish just_audio 0.4.1 (y/N)? y
Uploading...
Package archive contains a symlink: `ios/Classes/AudioPlayer.m`.
pub finished with exit code 1
$
```

I wonder if this is because there is a new recommended best practice? Or would this be a bug in pub.dev?

**Comment by stuartmorgan** [comment]
I looked into the test aspect of this more, and I don't think there's actually anything we need to test at the Flutter level here; the symlink is into the package, which is pulled by pub, not Flutter. Once that link resolves resolves, intra-package symlinks shouldn't be an issue.

The already-completed part of using this approach in flutter/plugins should be sufficient.

**Comment by stuartmorgan** [comment]
FYI for anyone who was following this: We are revisiting the decision to just use symlinks, and have published https://flutter.dev/go/plugin-shared-ios-macos for discussion.
