### ISSUE TITLE
Share performance and probably other data from China

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#52345]
We'd like to have a way to let our Chinese partners share some performance metrics with us because:

1. Some hardware is hard to get in America. Having our Chinese partners running perf tests on those devices and sharing the results with us would let Flutter discover regressions on those devices faster.

2. Google play store is not available in China so Flutter doesn't have much market performance data (e.g., which device model is particular popular; how healthy is Flutter's usage in end-users). It would be nice if we can aggregate some data to share without compromising the confidentiality of our partners.

**Comment by dasebasto** [comment]
You seem to imply that the Flutter team already has access to aggregated performance metrics from the Play store.

Is there somewhere where we can view this data, and ideally compare the metrics of Flutter apps with those of Native Android apps?  (crash rates and main performance metrics).

I'm currently reluctant to launch a commercial app in Flutter because of the big uncertainty regarding stability and performance.
Such stats would help make an informed decision.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by liyuqian** [comment]
I think this is still valid but we don't have bandwidth to work on it yet.

@dasebasto : Unfortunately, there's no way of viewing such data. https://github.com/flutter/flutter/issues/37437 is a related issue where we try to collect some publishable performance metrics on real user devices.

**Comment by cbracken** [comment]
Closing as too vague/unactionable.
