### ISSUE TITLE
Google map flickering when add new marker. 

### ISSUE THREAD

**Issue by jabedbd** [flutter/flutter#52395]
I'm using  google_maps_flutter 0.5.24+1 plugin on my app. 
I'm trying to add marker grammatically on my google map.  to do this first i define a 
`Set<Marker> _markers = {};`
then on my _onMapCreated function i make a post request to my server, get all the marker data and add them to the _markers like this: 
```
setState(() {
_markers.add(Marker(
         markerId: MarkerId('driver'),
         position: pinPosition, // this pinPostions is coming from my server. 

      ));
)}; 
```

with the code, it's successfully add the marker to the map, but the issue is when i add each new marker the map start flickering  and reload again to show the marker.

**Comment by VladyslavBondarenko** [comment]
Hi @jabedbd 
Your map will reload on each setState, when you call it for each marker. 
I would advice you to add all new markers to a new list out of setState and then inside of setState concatenate it with _markers (in order to update all of them in once).
Closing, as this seems to be not an issue with Flutter,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by jabedbd** [comment]
Hi @VladyslavBondarenko 
Thanks for your reply. Is there any way to update the position of a marker without remove and adding it again?

**Comment by VladyslavBondarenko** [comment]
@jabedbd I'm not sure,
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help on Stack Overflow.
