### ISSUE TITLE
Bug of environment variable on Windows

### ISSUE THREAD

**Issue by TinkMingKing** [flutter/flutter#52489]
On windows, if the environment variable contains "&", executing "fluent" will result in an error.

**Comment by JosepBove** [comment]
Hi @TinkMingKing 

I don't really understand your issue. If you run "fluent" meaning "flutter?", you get an error if you have a special character in the environment variable path?

Thanks!

**Comment by TinkMingKing** [comment]
I accidentally misspelled. It is "flutter"

In user variable or system variable
for example
`path="%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;E:\Python\;E:\Python\Scripts\;E:\SecureSoft\;E:\Flutter\bin;D:\XXX&X;"`

`&` Will cause errors

**Comment by iapicca** [comment]
Hi @TinkMingKing 
This issue doesn't seem related or caused by flutter.

Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow.

You may want to double-check with the [docs](https://flutter.dev/docs/get-started/install/windows).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by TinkMingKing** [comment]
Obviously this will cause an error and it will not be able to get the correct path for "git".
![image](https://user-images.githubusercontent.com/32903588/76606064-93cfa400-654c-11ea-8761-5a1d520eaaed.png)
![image](https://user-images.githubusercontent.com/32903588/76606154-be216180-654c-11ea-88f1-f1e6ee430850.png)
If another program's folder path contains an `&` and needs to be added to the `path`, then flutter will not run. In the past, I didn't know what caused the error, and I had to reinstall the system to fix it.
