### ISSUE TITLE
Shift-tab not working on debug Web builds

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#52482]
Repro steps:

Shift-tabbing works in release mode: https://flutter.github.io/samples/web/animations/
When building from source (https://github.com/flutter/samples/tree/master/animations) as a debug build, shift-tabbing no longer works.

```
flutter --version
Flutter 1.15.21-pre.11 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 7c9f95ac0a (18 hours ago) • 2020-03-11 16:57:06
-0700
Engine • revision 9a3016fbed
Tools • Dart 2.8.0 (build 2.8.0-dev.13.0 684c53a6f1)
```

**Comment by mdebbar** [comment]
I have been able to use Tab and Shift+Tab in both debug and release builds. There's a known issue where if you do a browser-defined shortcut (e.g. `cmd+alt+i`) the browser doesn't send a `keyup` event for the `i` in this example. This makes the framework confused because later when you click `Tab`, the framework thinks both `i` and `Tab` are down, so it doesn't trigger the action associated with the `Tab` click.

Can you please confirm if this is the issue you are seeing?

**Comment by guidezpl** [comment]
I don't think this was the issue but as I'm now able to use both, I am closing the issue. Thanks!
