### ISSUE TITLE
Improvement  for constants

### ISSUE THREAD

**Issue by LefebvreIlyas** [flutter/flutter#52600]
Hello everyone,

- In the file fundation/constants.dart the constant precisionErrorTolerance does not respect the naming convention for constants (See [Begin global constant names with prefix "k"](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#naming)).

```dart
/// The epsilon of tolerable double precision error.
///
/// This is used in various places in the framework to allow for floating point
/// precision loss in calculations. Differences below this threshold are safe to
/// disregard.
const double precisionErrorTolerance = 1e-10;
```

- In the file material/constants.dart that references the minimum dimension of any interactive region according to Material guidelines. But other constants are scattered throughout the framework, wouldn't it be better to gather them all in this file even if it means a huge breaking change? So that developers can easily find and use them.

Here are some constants: 

See floating_action_button_location.dart
```dart
// TODO(hmuller): should be device dependent.
/// The margin that a [FloatingActionButton] should leave between it and the
/// edge of the screen.
///
/// [FloatingActionButtonLocation.endFloat] uses this to set the appropriate margin
/// between the [FloatingActionButton] and the end of the screen.
const double kFloatingActionButtonMargin = 16.0;
```

In the floating_action_button.dart file the dimensions of the floatingActionButtons are written hard in private variables of type BoxConstraints, wouldn't it be better to extract this also in the file material/constants.dart?

```dart
const BoxConstraints _kSizeConstraints = BoxConstraints.tightFor(
  width: 56.0,
  height: 56.0,
);

const BoxConstraints _kMiniSizeConstraints = BoxConstraints.tightFor(
  width: 40.0,
  height: 40.0,
);

const BoxConstraints _kExtendedSizeConstraints = BoxConstraints(
  minHeight: 48.0,
  maxHeight: 48.0,
);
```

In addition, the kRealaseMode constant page does not exist.

**Does it make sense to create a pull request for this right now?**

**Comment by HansMuller** [comment]
Changing the names of public constants, even though they don't adhere to the [Flutter style guidelines](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k) isn't a good idea, since (as you pointed out) a breaking change. Changing the names of private constants defined with `_kFoo` isn't really necessary per the guidelines either. 

The reason that the myriad layout constants in the the material and cupertino libraries aren't public is that that the underlying specs do change, so committing to the all of these dimensions (documenting and sustaining them) is something we'd prefer not to do.

**Comment by HansMuller** [comment]
I'm going to close this per https://github.com/flutter/flutter/issues/52600#issuecomment-599729421
