### ISSUE TITLE
Add DropdownButton / DropdownButtonFormField / DropdownMenuItem `onTap` callback for logging

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52671]
https://b.corp.google.com/issues/151599231.

This is the minimum code to reproduce it

```dart
GestureDetector(
  behavior: HitTestBehavior.translucent,
  onTap: () {
    // Do some logging.
    print('tapped');
  },
  child: DropdownButtonFormField(
    items: [
      DropdownMenuItem(
        value: 'value 1',
        child: Text('option 1'),
      ),
    ],
    onChanged: (newValue) => print('newValue: $newValue')
  ),
),
```
Expected behaviour:
When the dropdown button is tapped, 'tapped' should be logged and the dropdown items are displayed.
The event should be combined, no exclusive of each other.

On a side note:
what we're trying to achieve is do logging when the dropdown button is tapped.
This is actually an alternative method of doing it. The preferable way is for DropdownButton(and DropdownButtonFormField) to have `onTap` callback. I am not sure what's the opinion on having such callback.

**Comment by HansMuller** [comment]
I think what's needed here is a "me too" onTap callback like https://api.flutter.dev/flutter/material/TextField/onTap.html

**Comment by tjonganthony** [comment]
I'm the person who reported the bug.
If you guys don't mind, I can take a stab on this to accelerate the process.
Is it okay for me to say that adding `onTap` callback to `DropdownButton` and `DropdownButtonFormField` is the way to go?

**Comment by tjonganthony** [comment]
If `onTap` is indeed the path that we're pursuing, can I extend this issue into also adding `onTap` to `DropdownMenuItem`?
We also need to do logging when user taps onto the item, and currently since there are already `InkWell` integrated, it would be cleaner to do so instead of wrapping `DropdownMenuItem` with `GestureHandler`(which also doesn't quite work as expected).

**Comment by kf6gpe** [comment]
This is marked as a P1 in the upstream database, so I'm tagging it with the `severe: customer critical` label. @tjonganthony and @HansMuller if I'm wrong, please remove it. Thanks!

**Comment by tjonganthony** [comment]
Yes, if possible we would like to get this sorted as soon as possible as it is considered as launch blocking when we are not able to do logging for event.
However, I can try pushing back a bit if you guys have different priority at the moment.

**Comment by shihaohong** [comment]
@tjonganthony Would you need this logging to be done on a tap down (pointer down), or on a tap (pointer down, followed by pointer up)?

The only worry I have is that users might get confused between using the `onChanged` and `onTap` callbacks since they sort of overlap in functionality, but we can always add an assert that if one is defined, the other shouldn't be and explain the use-case for each callback.

**Comment by tjonganthony** [comment]
It should be "on a tap", as we only want to log a valid tap.

I think the confusion between `onChanged` and `onTap` would not be too hard as `onChanged` will have `newValue` as a parameter, while `onTap` should not have any parameter.  Correct me if I'm wrong, but I think both `DropdownButton` and `DropdownButtonFormField` can have both `onTap` and `onChanged` callback.

Maybe something that might be concerning is the order in which the callback is defined. My 2 cents is it should be this sequential order
- `DropdownButton.onTap` or `DropdownButtonFormField.onTap`
- `DropdownMenuItem.onTap`
- `DropdownButton.onChanged` or `DropdownButtonFormField.onChanged`

**Comment by shihaohong** [comment]
Yeah that makes sense! Actually thinking about it now, having both defined should be okay, as long as we're very clear with what each callback actually does and when it's called.

**Comment by shihaohong** [comment]
One thing that would work for DropdownButton for now is using a `Listener` instead of a `GestureDetector`, since it does not participate in the gesture arena and gesture disambiguation:
```dart
      Listener(
        onPointerUp: (_) {
          // Do some logging.
          print('Log on pointer up');
        },
        child: DropdownButtonFormField(items: [
          DropdownMenuItem(
            value: 'value 1',
            child: Text('option 1'),
          ),
        ], onChanged: (newValue) => print('newValue: $newValue')),
      );
```

However, this wouldn't work on `DropdownMenuItem` since `DropdownButton` takes a `DropdownMenuItem` widget so there's no easy way to wrap them with a `Listener`.
