### ISSUE TITLE
--trace-skia not getting sent to the engine for iOS simulator

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#52676]
Flutter version: bbc5b9d967449cdf0ba601e20e7662dcf04c886f

If I run flutter with: `flutter run --trace-skia`

On an engine that has the following patch:
```
--- a/shell/common/switches.cc
+++ b/shell/common/switches.cc
@@ -271,9 +271,11 @@ Settings SettingsFromCommandLine(const fml::CommandLine& command_line) {
 
   settings.trace_skia =
       command_line.HasOption(FlagForSwitch(Switch::TraceSkia));
+  FML_LOG(ERROR) << "trace skia:" << settings.trace_skia;
 
   command_line.GetOptionValue(FlagForSwitch(Switch::TraceWhitelist),
                               &settings.trace_whitelist);
```

It prints out: `[VERBOSE-2:switches.cc(274)] trace skia:0`

I supplied the flag `--observatory-port 123` and that does get passed through.

Seen on: iOS

**Comment by jonahwilliams** [comment]
It looks like for simulators we pass very few of the args through. Not sure if this is intentional, but at least with the current design it seems like an easy mistake to make. Especially since the android device/emulator are implemented with the same class, while only iOS is split between the physical device and simulator

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L397

**Comment by jmagman** [comment]
Simulator:
https://github.com/flutter/flutter/blob/d40f6d1e681f17e3b7b7290afb4c9b4175b976e7/packages/flutter_tools/lib/src/ios/simulators.dart#L430-L449

Physical device:
https://github.com/flutter/flutter/blob/d40f6d1e681f17e3b7b7290afb4c9b4175b976e7/packages/flutter_tools/lib/src/ios/devices.dart#L352-L377

Simulator tests:
https://github.com/flutter/flutter/blob/d40f6d1e681f17e3b7b7290afb4c9b4175b976e7/packages/flutter_tools/test/general.shard/ios/simulators_test.dart#L1011-L1025

Physical device tests:
https://github.com/flutter/flutter/blob/d40f6d1e681f17e3b7b7290afb4c9b4175b976e7/packages/flutter_tools/test/general.shard/ios/ios_device_start_prebuilt_test.dart#L282-L300

Simulator does not need `--disable-observatory-publication` since it's not doing mDNS broadcasting.

In the simulator these options are not being passed:
```
  '--trace-systrace',
  '--trace-skia',
  '--endless-trace-buffer',
  '--dump-skp-on-shader-compilation',
  '--verbose-logging',
  '--cache-sksl',
  '--purge-persistent-cache',
```
