### ISSUE TITLE
Hot Reload is on by default for Flutter team

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5280]
Just wanted to capture this in our August milestone.  Please feel free to close this/remove this if this isn't helpful.  My understanding is that end-of-august is a reasonable timeframe for all of Flutter to be using --hot?  @johnmccutchan

**Comment by johnmccutchan** [comment]
I'm hoping that next week Android developers can switch completely.

Assets are now supported as is 'cold restart'

There are some minor usability issues that I want to fix but I think the Flutter team can deal with the current state.

Usability issues:
- [] Detect when an isolate has exited due an unhandled exception and notify the user that they must restart instead of reload.
- [] Initial DevFS sync is slower than it should be.

**Comment by sethladd** [comment]
This landed! Can we close?
