### ISSUE TITLE
Issue in getting subcollection from document in firebase

### ISSUE THREAD

**Issue by ShabanGomaa** [flutter/flutter#52984]
I have an issue, I can't get subcollection from the document:
I have firestore db with
collection: collectionName
Inside collection documents and inside one document subcollection "items"

- collectionName
  - Document1
    - Items <- subcollection
      - Item1
      - Item2

I use the following code but the items subcollection can't be retrieved from my db....

QuerySnapshot snapshot = await Firestore.instance
      .collection('collectionName')
      .orderBy("order")
      .getDocuments();

then
snapshot.documents.forEach((document) {})

The document doesn't have the items subcollection

**Comment by iapicca** [comment]
Hi @ShabanGomaa 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
