### ISSUE TITLE
Status Bar Color doesn't change in real device

### ISSUE THREAD

**Issue by ampersanda** [flutter/flutter#53034]
Regards of my question in stackoverflow (https://stackoverflow.com/questions/60733747/annotatedregion-doesnt-work-on-real-device) by using `setState` and `AnnotatedRegion` to change status bar brightness.

## Steps to Reproduce

1. A fresh flutter project
2. A simple `setState` and `AnnotatedRegion<SystemUiOverlayStyle>` value set toggled between 
light and dark

This runs perfectly on iOS Simulator but doesn't work in real device

#### iOS Simulator
![kqcw3](https://user-images.githubusercontent.com/13579812/77242487-5dbbaf80-6c31-11ea-832c-999de9c1b622.gif)

#### Real device (iPhone XR)
![ioPA2](https://user-images.githubusercontent.com/13579812/77242475-4bda0c80-6c31-11ea-8d26-fcb59157bf70.gif)

**Comment by VladyslavBondarenko** [comment]
Hi @ampersanda 
from your stackoverflow question I see you are using `1.12.13+hotfix.8`. I checked, it's true for stable, but not for the current master (tried with v1.16.2-pre.41).
You can consider to use another flutter channel which can already have this fix.
Closing the issue since it's fixed, but not yet for stable.
if you disagree please write in the comments and I will reopen it.
Thank you
