### ISSUE TITLE
Why running `git fetch --tags` every time when using `flutter xxx`? It always gets stuck for a long time. 

### ISSUE THREAD

**Issue by weichengwu** [flutter/flutter#53053]
## Capture

![image](https://user-images.githubusercontent.com/17878528/77253806-d9e8de00-6c97-11ea-87ba-e527a143c046.png)

**Comment by jonahwilliams** [comment]
fyi @dnfield

**Comment by dnfield** [comment]
Does devices specifically request the version?

**Comment by dnfield** [comment]
This isn't reproducing locally.  What commit of Flutter are you on?  There are a few commits on master where this was running on ever command, but we fixed that.  When I run this command on master it is not fetching tags.

**Comment by dnfield** [comment]
Argh.  2294d75bfa8d067ba90230c0fC2268f3636d7584 is beta.  It contains the original landing of my change, but not the fix for it or the revert (e7d70fbf7564cb00f1541fb90df8ee61adb4de5d).

Unfortunately, beta is pointing to a commit between the landing and the revert.  If you patch in e7d70fbf7564cb00f1541fb90df8ee61adb4de5d you should see this go away.

**Comment by dnfield** [comment]
I've retroactively updated the Bad-builds page. If possible, can we try to roll beta to a better revision?

**Comment by kf6gpe** [comment]
cc @kf6gpe

**Comment by christopherfujino** [comment]
Closing this as beta is now at version `1.17.0-dev.3.1`, which includes the fix for this.
