### ISSUE TITLE
Text Editing should integrate with Actions and Shortcuts APIs.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#53189]
Text editing is currently a cooperation between the engine and the framework, and the engine can perform editing operations on the text field (by way of the IME), and sends the result to the framework.

Ideally, the engine would simply send the editing commands themselves to the framework, and the developer would be able to override their key bindings and actions performed on the text.

We have a mechanism for actions and shortcut bindings, but the text editing subsystem doesn't use them, and probably should.

**Comment by justinmc** [comment]
Here's my [design doc](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#) for migrating text editing to use actions and shortcuts.

**Comment by justinmc** [comment]
With https://github.com/flutter/flutter/pull/75032 being merged, we're on the way to solving this.  I'm continuing to work on porting text editing related interactions to Shortcuts/Intents/Actions, but we also will need to move overlapping logic out of the engine as mentioned above.  I'm unassigning myself for now since I'm not actively working on moving that code out of the engine yet, but it is a longer term goal for me.

**Comment by justinmc** [comment]
I think we can close this now that all of the keyboard logic has been moved out of RenderEditable with https://github.com/flutter/flutter/pull/86986.  We plan to handle tap gestures through Actions as well, but that will be tracked separately.
