### ISSUE TITLE
Flutter missing libflutter.so crashes

### ISSUE THREAD

**Issue by aldwnesx** [flutter/flutter#53461]
I used app bundle and it keeps crashing on pixel 2 device.

I searched for hours for solution and they suggest using android-arm64 as target etc.

What should I actually do?

**Comment by canewsin** [comment]
submit a minimal code to reproduce issue.

**Comment by aldwnesx** [comment]
> submit a minimal code to reproduce issue.

can you tell me which codes i need to submit?

**Comment by iapicca** [comment]
Hi @aldwnesx 
did you try to proposed [solution](https://github.com/flutter/flutter/issues/53411#issuecomment-605385160)?
Thank you

**Comment by aldwnesx** [comment]
> Hi @aldwnesx
> did you try to proposed [solution](https://github.com/flutter/flutter/issues/53411#issuecomment-605385160)?
> Thank you

still crashing

**Comment by iapicca** [comment]
Hi @aldwnesx 
according to your [message](https://github.com/flutter/flutter/issues/53459#issuecomment-607091010)  this issue seems to be a duplicate of the referenced [issue](https://github.com/flutter/flutter/issues/53461) 

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
