### ISSUE TITLE
Gallery, Pesto: non-fading app bar when opening a recipe

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5350]
Open Gallery, open pesto, scroll up enough to minimize the app bar. Tap a recipe.

Notice how the app bar immediately disappears, before the recipe begins its motion up. This is a jarring effect that the user could notice.

We could try something more subtle, like animating or fading the app bar away as the recipe opens?

**Comment by Hixie** [comment]
This is basically https://github.com/flutter/flutter/issues/5232

**Comment by sethladd** [comment]
(Fixing this issue might also resolve https://github.com/flutter/flutter/issues/5351)

**Comment by sethladd** [comment]
I believe @HansMuller is taking a look at this.

**Comment by eseidelGoogle** [comment]
I'm not sure what I'm looking for here.  It looks reasonable?
![transition mov](https://cloud.githubusercontent.com/assets/11857803/22602039/6c813fb4-e9f6-11e6-98d3-404d9056a32d.gif)

**Comment by sethladd** [comment]
> Notice how the app bar immediately disappears, before the recipe begins its motion up. This is a jarring effect that the user could notice.

**Comment by HansMuller** [comment]
At the start of the Hero transition the Hero, the recipe image in this case, is moved into the overlay. It was partially behind the appbar, now it's completely on top. It's not entirely clear how to handle this case. It turns out to be difficult for Android native as well: https://plus.google.com/+AlexLockwood/posts/RPtwZ5nNebb

Do really do this well we'd need to stage the hero transition: first get the appbar out of the way, then do the recipe image hero transition.

There's probably advice about how to handle this scenario here: https://material-motion.github.io/material-motion/

**Comment by sethladd** [comment]
We've hidden Pesto.
