### ISSUE TITLE
Android setup launch_image cannot set duration time.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53554]
Android setup launch_image cannot set duration time.
Please see the screenshot:
![图片](https://user-images.githubusercontent.com/58280808/77877350-216afd80-7288-11ea-952c-9f75b016dfe7.png)

**Comment by TahaTesser** [comment]
Hi @gionchat
To set custom duration, you can Flutter Splash Screen instead of `launch_background
Please check it out [Flutter Splash Screen
](https://medium.com/@vignesh_prakash/flutter-splash-screen-84fb0307ac55)

This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow. Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it Thank you
