### ISSUE TITLE
Proposing a "flutter clean" to clean up old downloaded artifacts

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5359]
Not sure how common this is, maybe I'm just updating every day :), but I had 1GB in my `$FLUTTER_ROOT/bin/cache/artifacts` directory.

![screen shot 2016-08-11 at 3 24 29 pm](https://cloud.githubusercontent.com/assets/5479/17628993/ec62acb8-606c-11e6-9c8e-ac99f9ceb257.png)

If this is something more people are running into, we could offer a `flutter clean artifacts` command and delete all the old artifacts we've downloaded.

**Comment by abarth** [comment]
Looks like you just have two copies of stuff because we renamed "sky_engine" to "engine" at some point.  In general, the cache doesn't grow with the number of updates.  The new stuff replaces the old stuff.  I deleted my cache and ran `flutter doctor` and I got back to the same 511M I was at when I started.

I'd recommend deleting your cache and re-opening this issue if you see it growing again.

**Comment by sethladd** [comment]
ah, thanks for clarifying! That makes sense. I deleted the directory, and the next `flutter upgrade` pulled down bits. Will keep an eye on it, but so far, everything is good.
