### ISSUE TITLE
[Image_picker]: in flutter module, can't get viewcontroller  in ios

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#53630]
```
UIViewController *viewController =
      [UIApplication sharedApplication].delegate.window.rootViewController;
```

the method  that get window viewcontroller not well when initial plugins before window.rootviewcontroller.

**Comment by TahaTesser** [comment]
Hi @OHeroJ 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by hiquanta** [comment]
This problem also occurs in the latest version. The viewController can only be set once through the plug-in initialization. If the window.rootViewController is changed in mixed development, the plug-in will not work properly. It is best to expose the excuses and set the viewController dynamically. Expose the viewController in FLTImagePickerPlugin so that the plugin can change its value after initialization

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
