### ISSUE TITLE
SliverOverlapAbsorber widget on stable version does not support sliver parameter

### ISSUE THREAD

**Issue by healer2030** [flutter/flutter#53656]
## Steps to Reproduce

1. Look at the SliverOverlapAbsorber widget at the stable branch https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1329
2. Look at the same widget on the beta branch https://github.com/flutter/flutter/blob/beta/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1487

**Expected results:** 
As shown in the beta branch, the `child` parameter was supposedly 'deprecated after v1.10.16,' and replaced by the `sliver` parameter. However, the current flutter stable version is 1.12.13+hotfix.8 and those changes has not been reflected in the stable version

**Comment by Piinks** [comment]
Hey @healer2030 thanks for bringing this to our attention!
It turns out that this change was first tagged at v1.13.0, so no, it is not on stable yet - but that means the deprecation warning isn't either! :)

When we make these sort of changes that add deprecations, we use the current version at the time of the change. What version it actually gets rolled into is not determined until after the change lands, so it is deprecated _after_ v1.10.16, but not specifically _at_ v1.10.16.

You can see the versions a change was applied to by looking at the commit: https://github.com/flutter/flutter/commit/2a5e528a18bf04d48483a8e493438f907171994d

I hope this has answered your question. If not, leave a comment and we can re-open this to discuss further! Thanks!
