### ISSUE TITLE
color_filter_and_fade_perf__timeline_summary regression worst_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54095]
Clear jump at this engine roll: https://github.com/flutter/flutter/pull/53890

![Screen Shot 2020-04-06 at 7 58 17 AM](https://user-images.githubusercontent.com/1435716/78572491-650bbd00-77dc-11ea-9346-81df2cc6737f.png)

**Comment by tvolkert** [comment]
@liyuqian @chinmaygarde thoughts?

**Comment by liyuqian** [comment]
No PR in that engine roll seems to be suspicious to me regarding this Android performance test. CC engine sheriff @gw280 : can you reproduce this regression locally? I'd like to first check if this is an engine issue or an infra issue.

**Comment by gw280** [comment]
I don't have an Android device I'm afraid :(

**Comment by chinmaygarde** [comment]
> I'll try to reproduce this regression locally and check if this is an engine issue or an infra issue.

@liyuqian I didn't review https://github.com/flutter/engine/pull/17486 so not sure what the context was but if we are rendering to a texture now instead of a surface, the extra onscreen composition could totally cause this regression. I would try bisection from there. But yeah, the toolchain thing is a massive change too. But that would have affected absolutely all targets.

**Comment by tvolkert** [comment]
@godofredoc can you see if there's some issue with the device running this benchmark?

**Comment by keyonghan** [comment]
I am looking at this issue.

**Comment by keyonghan** [comment]
This task has been run across four agents (mac 17, 19, 20, and 21). There are no issue found on any of them. Since we are not able to capture android screen from a mac at this moment(https://github.com/flutter/flutter/issues/51802), we are not sure if any window pop up on these devices. For now, I issued a reboot for all devices and hosts.

**Comment by tvolkert** [comment]
Thanks @keyonghan!

@liyuqian if the values don't return to normal now that the hosts and devices have been rebooted, more investigation will be needed, since we've ruled out infra issues.

**Comment by jason-simmons** [comment]
I can reproduce this on a Moto G4 (comparing https://github.com/flutter/flutter/commit/85664beb900ae200aa1a3184d5ed63a479a9a329 and https://github.com/flutter/flutter/commit/a8b3d1b74fac5251c61c8a898cf7544fd77ddd16)

Trying to bisect now.

**Comment by jason-simmons** [comment]
This started with https://github.com/flutter/engine/commit/abc72933e

@iskakaushik

**Comment by tvolkert** [comment]
Can we revert and then re-apply with a fix?

**Comment by liyuqian** [comment]
Thanks @jason-simmons ! With your discovery, I now figured out why I couldn't reproduce the regression early: `--trace-startup` is needed to see the regression. It seems that @iskakaushik 's commit https://github.com/flutter/engine/commit/abc72933e broke some tracing contracts when `--trace-startup` is given.

Specifically, with `--trace-startup`, we see frame times like
```
    609,
    372340,
```
which seems to be adding the time of 2 frames into 1.

Without `--trace-startup`, it would be more like
```
    207123,
    188726,
```

See [color_filter_with_or_without_trace_startup.zip](https://github.com/flutter/flutter/files/4441401/color_filter_with_or_without_trace_startup.zip) for more details.

Hence I'm removing the TODAY label as this is not an actual performance regression, but more like a tracing issue.

**Comment by jason-simmons** [comment]
There is definitely something wrong with the tracing format when the `SceneDisplayLag` event is added.

In the attached timeline, look at the events between timestamps `7267951896` and `7268116859`.  There are two `GPURasterizer::Draw` end events in a row, with a `SceneDisplayLag` event in between.

The two `GPURasterizer::Draw` end events are probably causing bad results in the benchmark script when it tries to find begin/end pairs in the timeline.

[bad_timeline_1.json.txt](https://github.com/flutter/flutter/files/4441473/bad_timeline_1.json.txt)

**Comment by iskakaushik** [comment]
I think this is a problem with the way we are parsing the timeline events in the test rather than the timeline events itself. I'm working on fixing this along with taking a look at https://github.com/flutter/flutter/issues/54205

**Comment by jason-simmons** [comment]
I'm still concerned that something is wrong with how the timeline events are being recorded.

I tried adding logging to `runtime/vm/timeline.cc` in Dart and found that some calls to `Dart_TimelineEvent` are not shown in the timeline JSON file downloaded by flutter_driver.

The missing events happen when the `SceneDisplayLag` event is logged with a begin timestamp in the past.  Prior to that event the rasterizer had called `Dart_TimelineEvent` to log a `GPURasterizer::Draw` begin event with a later timestamp.  But the `GPURasterizer::Draw` begin record is missing from the JSON, which then causes failures in the code that tries to match begin/end pairs.

**Comment by iskakaushik** [comment]
I reached out to @rmacnak-google , It seems like the underlying issue is that as a client we need to sort the events on the timestamps before consuming them. Pasting my conversation here for posterity. Based on this I'm going to sort the events by their timestamp before exporting the `json`.

me: When we create timeline event with Dart_Timeline_Event_Async_Begin as the event type, is the event allowed to specify the timestamp that is in the past? In particular, does the caller need to do anything to ensure that the Dart_TimelineEvent implementation will buffer events that are logged out of order and then write them to JSON in sorted order?

ryan: The answer somewhat depends on which underlying recorder is being used. If the recorder is a VM buffer or Fuchsia tracing, then it should be fine if an event is from the past because the client will have to sort things anyway because of buffering. If the recorder is Android systrace (or iOS signpost, I think) then when we forward the event the underlying record does not take a timestamp as an argument and uses the current time instead.

me: Upon further investigating the attached trace file in https://github.com/flutter/flutter/issues/54095#issuecomment-610114914, it seems like the missing event between the two `E`s occurs after them

```
{"name":"GPURasterizer::Draw","cat":"Embedder","tid":13450,"pid":13434,"ts":7267952095,"tts":2246953,"ph":"B","args":{}}
```
