### ISSUE TITLE
[Web] broken gestures for mobile Safari

### ISSUE THREAD

**Issue by LeiQiao** [flutter/flutter#54269]
after upgrade flutter, it is works fine on mac safari or chrome, but unable respond any touch/scroll event on mobile safari

```
Upgrading Flutter from /Users/lei.qiao/flutter...
From https://github.com/flutter/flutter
   0f68b46f6a..981afe39ae  master     -> origin/master
Already up to date.
Flutter is already up to date on channel dev
Flutter 1.18.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8f7327f83a (27 hours ago) • 2020-04-06 22:11:01 -0400
Engine • revision 49891e0653
Tools • Dart 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
Process finished with exit code 0
```

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
Checking Android licenses is taking an unexpectedly long time...⣷Unknown architecture armv7s, defaulting to arm64
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Reproduced on mobile Safari (iOS 13.4).

Built with `dev 1.18.0` - http://flutter-test.netlify.com/
Built with `beta 1.17.0` - https://flutter-test-beta.netlify.com/

<details>
 <summary>code sample</summary>
 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView(
          children: List.generate(100, (index) => Text(_counter.toString())),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

</details>

**Comment by chunhtai** [comment]
If you meant the platform view bug, I don't think it is related. v1.18  does not include that change

**Comment by chunhtai** [comment]
diff commit that are in dev

8f7327f83 49891e065 Roll src/third_party/skia 04513752fd6e..3ef77ddf9ec4 (3 commits) (flutter/engine#17530) (#54156)
39954a092 [cleanup] Remove unused script (#54155)
de1baeeae Roll engine ab434c5540f5..2fab00eb8352 (3 commits) (#54153)
ccb4f737e Roll engine df257e59c241..ab434c5540f5 (5 commits) (#54148)
de1e57291 Don't checkout master in roll_dev (#54150)
e3e189219 [web] Fix race condition in widget benchmarks (#53952)
de27d7131 disable the "gpu" tracing category (#54122)
98e43bc6a [flutter_tools] ensure the tool can find SDK manager on windows (#54133)
727552e5c Manual roll of engine 9b8dcc7ecffe..df257e59c241 (#54111)
f5a990257 enable avoid_equals_and_hash_code_on_mutable_classes (#52507)
80bc3f4a3 Test creation of Android AlertDialogs with a platform view context (#53980)
2d623278e Restructure the Windows app template (#53600)
d35ade4a6 Added 'barrierColor' and 'useSafeArea' parameters to showDialog. (#54110)
4037e5069 [flutter_tools] update asset manifest to use package_config instead of package_map (#53944)
602475e56 Sanitize error message sent to GitHub crash reporter (#53936)
61b336178 Revert "[flutter_tools] Migrate to vm service 3 (reland): electric boogaloo (#53957)" (#54114)
d6b09626f [flutter_tools] Migrate to vm service 3 (reland): electric boogaloo (#53957)
17079f26b 9b8dcc7ec Roll src/third_party/dart 987ad1d96748..05103dfe5a0e (2 commits) (flutter/engine#17522) (#54064)
be6234d56 Read custom app project name from gradle.properties (#52791)
f118e99f0 Roll engine f1f7d5db59f0..6e4817f09c47 (1 commits) (#54057)
0a4b27dc1 f1f7d5db5 Roll src/third_party/dart a7f1a5e677e5..987ad1d96748 (1 commits) (flutter/engine#17520) (#54056)
4fe7559d2 Roll engine 2cc6a6d66d50..bd725935ecfa (2 commits) (#54045)
6d52bf988 Roll engine cb6fc305346f..2cc6a6d66d50 (1 commits) (#54032)
f9c58bea4 [flutter_tools] also listen to web stderr stream (#53949)
f5fe1e3e6 Update roll_dev to work with new version numbers (#54015)
afed50771 Roll engine 4cfbe45033ef..cb6fc305346f (8 commits) (#54019)
fef9d4d7c [flutter_tools] Launch DevTools with 'v' (#53902)
caeaac773 disable MotionEvents test (#54023)
46ce54db8 Roll engine 09bc1fc45e50..4cfbe45033ef (2 commits) (#53970)
f0aea666d revive the android_views test (#53963)
4bbdca911 Disable deploy_gallery-macos shard while we investigate cert issues (#54018)
a2e6c30b4 Update Highlight mode initial value calculation. (#52990)
14f3a36ab Clear ImageCache on MemoryPressure (#53959)
4b92c1675 Use "measured_frame" instead of "CrRendererMain" to detect process ID (#53969)
5c69785b1 Roll engine 83e493ae6262..09bc1fc45e50 (6 commits) (#53966)
30738982b Remove network images from cache on any exception during loading (#53875)
4e811d281 [gen_l10n] Fix plural parsing for translated messages (#53954)
c6ee4d268 Temporarily mark web benchmarks as flaky (#53967)
29c88081b Collect chrome://tracing data in Web benchmarks (#53879)
58acf4e7b Revert "[flutter_tools] surgically remove outputs from shared directory (#53773)" (#53956)
d5795b6ff Roll engine f5127cc07a76..83e493ae6262 (5 commits) (#53940)
8a3bede1d [flutter_tools] surgically remove outputs from shared directory (#53773)
66f490775 Revert "[flutter_tools] update to package vm_service: electric boogaloo (#53809)" (#53951)
1e86c1fb1 [flutter_tools] re-enable debug extension (#53765)
66d7a6c26 [flutter_tools] update to package vm_service: electric boogaloo (#53809)
365528aad Use `no` locale as synonym for `nb` (#53880)
e01275263 [flutter_tools] Don't generate native registrant classes if no pluginClass is defined (#53785)
63f8b9a4d Improving A11y for Flutter Gallery Demos (#53616)
85ad69986 Remove URL shortening from GitHub reporter similar issues URL (#53882)
b336452cd Fix diagnostics crash in profile mode (#53878)
6837b0e35 [gen_l10n] Add scriptCode handling (#53868)
2396616e0 Support old and new git release tag formats (#53715)
ab14307e0 Roll engine abc72933e70c..f5127cc07a76 (2 commits) (#53895)
85664beb9 Roll engine f56e678e7fa9..abc72933e70c (5 commits) (#53890)
a8b3d1b74 Add toggleable attribute to Radio (#53846)
e97c385c1 Roll engine 49d65b45cfee..f56e678e7fa9 (2 commits) (#53866)
e2621bfd8 Roll engine 8166a91bca11..49d65b45cfee (2 commits) (#53856)
66eb92e62 (tag: 1.17.0-dev.4.0) Roll engine 1adfd639b465..8166a91bca11 (2 commits) (#53845)
3f69e83fe only auto-lock issues, not pull requests (#53851)
127787c87 Roll engine 46277fd2ca54..1adfd639b465 (23 commits) (#53838)
77ea848c4 Inject Usage dependency into FallbackDiscovery and BuildEvent (#53443)
c3ec1caac Replace isInstanceOf<T> uses with isA<T> (#53834)
40aea4799 [web] Unskip assertions test. Update for latest stack trace format. (#53795)
1c8b81fae Fixed the "touch target size" broken docs link. (#53793)
e20080b5d Add LICENSE file to packages/flutter, add test to make sure it… (#53799)
aad460b7f Roll engine c9506cb8e93e..46277fd2ca54 (3 commits) (#53769)
1a685e03a Improve downgrade-upgrade integration test (#53775)
6fddb7ee8 [flutter_tools] Handle full device when creating a temp directory (#53691)

**Comment by chunhtai** [comment]
bi-select down to this commit

de1baee Roll engine ab434c5540f5..2fab00eb8352 (3 commits) (#54153)

**Comment by goderbauer** [comment]
Thanks for the bisect!

Of the engine commits in that PR, this one looks the most suspicious: https://github.com/flutter/engine/pull/17495

/cc @mdebbar

**Comment by chunhtai** [comment]
I can confirm that commit causes mobile safari to not respond to pointer event

**Comment by mdebbar** [comment]
Ack. Looking into it.
