### ISSUE TITLE
Add support for SkSL shader warm-up in IDE plugins

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#54287]
Helps: SkSL-based shader warmup #53607

This would allow developers to prepare SkSL shader warm-up artifacts inside IDE without having to use the command line.

Needs:
  - [x] Connect flutter tools to VM service callback to pull sksl files from device #53116
  - [x] Add support for --sksl-shader-warmup to package sksl files into flutter_assets #53115

**Comment by jonahwilliams** [comment]
For the first point, rather than talking to the vm service getSkSL method, the IDEs should talk to a new method that the flutter tool registers. This method will ensure the files are packaged with the additional info that the command line option adds, and could support more features like specifying an output path 

The second point would be an argument to flutter build apk/ios. I don't think the IDE's automate that.

**Comment by liyuqian** [comment]
@devoncarew @jacob314 : now that the command line tools are finished and documented in https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up, please let us know if there's anything we need to provide for IDE plugins.

**Comment by ShaowenSu** [comment]
> @devoncarew @jacob314 : now that the command line tools are finished and documented in https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up, please let us know if there's anything we need to provide for IDE plugins.

Hi, just want to know what's the version of flutter supporting this tool, since I try `flutter run --cache-sksl` on command line and press `M`, nothing happen and nothing generated in the folder. The command line keys info(press `h`) has not mentioned such a key.

Below is my flutter's info.

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.17.5 at /Users/shaowensu/Library/Mobile Documents/com~apple~CloudDocs/Develop/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/shaowensu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
```

Thanks for any advice.

**Comment by liyuqian** [comment]
@ShaowenSu : using the tip-of-tree master branch Flutter would be the safest bet to try it (https://github.com/flutter/flutter/commits/master). If you want to know exactly what old versions has this capability, @jonahwilliams added those features to tools so he should be able to give you some more information.

**Comment by Hixie** [comment]
What is left to do here?
