### ISSUE TITLE
Test "flutter create; flutter run" on pre-commit (Simulator on Cirrus/LUCI?)

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#5433]
In #5398 flutter create myapp && cd myapp && flutter run was broken on iOS but we didn't have a test for it.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/5428 is about doing this on the post-checkin bots, but yes, doing it on travis would be even better if that's possible

**Comment by eseidelGoogle** [comment]
We used to have a test for this:
https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/flutter/flutter.py#26
But it got disabled for some reason.  @yjbanov might remember.

**Comment by yjbanov** [comment]
That test did both `flutter create` a sample app and run a driver test on the Simulator. It was disabled because the Simulator was flaky on the Chromebots and we have no SSH access to debug the issue (https://bugs.chromium.org/p/chromium/issues/detail?id=642933). We could enable just the `flutter create` + build parts, but not the "run on Simulator" part.

**Comment by eseidelGoogle** [comment]
We definitely need to revive this test.  We've broken this a couple times since (most recently last week).

**Comment by eseidelGoogle** [comment]
This may be part of solving https://github.com/flutter/flutter/issues/5428.

**Comment by markusaksli-nc** [comment]
Seeing as https://github.com/flutter/flutter/issues/5428 was closed, is this still relevant?

**Comment by jonahwilliams** [comment]
we test this reasonably well on CI now
