### ISSUE TITLE
Regression in web_size__compile_test hello_world_dart2js_size, hello_world_dart2js_size_gzip benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54371]
My gut assessment since these are new is that the baseline's a little low --- maybe rebaseline?

![Screen Shot 2020-04-09 at 9 17 52 AM](https://user-images.githubusercontent.com/1435716/78916902-01cf9400-7a43-11ea-9226-6b6e295ef7a1.png)

**Comment by kf6gpe** [comment]
Checked in with @yjbanov; looks like this is expected as he tightened thresholds. Rebaselining.

**Comment by kf6gpe** [comment]
These have regressed again since https://github.com/flutter/flutter/pull/56379. Canb we rebaseline again?

**Comment by kf6gpe** [comment]
hello_world_dart2js_size still shows red: 

![Screen Shot 2020-05-08 at 9 00 39 AM](https://user-images.githubusercontent.com/1435716/81424183-69443680-910a-11ea-959a-07cf9d008788.png)

cc @yjbanov

**Comment by mdebbar** [comment]
The recent PRs that caused increases in code size are:
* https://github.com/flutter/flutter/pull/54227 (+4KB)
* https://github.com/flutter/flutter/pull/55405 (+4KB)
* https://github.com/flutter/flutter/pull/56379 (+24KB ?)
* https://github.com/flutter/flutter/pull/56485 (+4KB)

@yjbanov the ICU data is still being tree-shaken out because the code that exercises it hasn't landed yet :) Locally, I had to add a few lines of code that exercise the data in order to measure the size impact.

**Comment by yjbanov** [comment]
Rebaselined
