### ISSUE TITLE
Full screen dialogs should say "cancel" instead of "X" on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5450]
This is to match the system behavior.  I believe this is what @sethladd agreed with the Material Design team.

Here is an example dialog from inside "General > Keyboard > Keyboards > Add new keyboard..." in the Settings app.

![img_0291](https://cloud.githubusercontent.com/assets/11857803/17720259/622a7848-63d5-11e6-9304-978c2a536f52.png)

Compared with Dialogs > Full Screen in the Flutter Gallery.

![simulator screen shot aug 16 2016 5 18 24 pm](https://cloud.githubusercontent.com/assets/11857803/17720270/7460a384-63d5-11e6-8a85-81aebc5b9169.png)

**Comment by eseidelGoogle** [comment]
Maybe a more direct comparison is the contacts app:
![simulator screen shot aug 16 2016 5 19 33 pm](https://cloud.githubusercontent.com/assets/11857803/17720298/9db83f44-63d5-11e6-9683-89f0cf4bcb48.png)

**Comment by Hixie** [comment]
Do you want this to be "CANCEL" or "Cancel"? (Contrast "DONE" vs "Done" in the screenshots above.)

**Comment by sethladd** [comment]
"Cancel" please. I check a few iOS apps. Thanks!

**Comment by Hixie** [comment]
That's going to look really ugly and inconsistent with everything else in Material. Can we get confirmation from the Material UX team?

**Comment by sethladd** [comment]
Sure, let me ask.

**Comment by sethladd** [comment]
I heard back from our designers. They feel that *Material* prefers icons when they are established and understood. Since X and < are established, they are preferred over text, for the context of Material.

I looked at various non-Apple iOS apps which received the Editor's Choice:

* Lonely planet: Cancel
* Honest Beauty: X
* Habit Tracker: X
* Elevate: X
* Facebook: X and Cancel (depending on the screen :)
* 1Password: Cancel
* Yelp: Close (?!?! :)

Of course, seemingly all the Apple apps use "X".

Probably the right thing to do here is to allow developers to opt-in to "Cancel" if they choose. Not all developers will want to follow all Material suggestions/guidance. Some developers will want to use "Cancel".

But, for the Gallery itself, it appears to be fine to use "X".

**Comment by Hixie** [comment]
The framework doesn't have an opinion on this, the X is coming just from the way the dialog is written in the gallery:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/full_screen_dialog_demo.dart#L147

So I don't think there's anything left to change here. Closing.
