### ISSUE TITLE
Problema na autenticação da versão (Version authentication problem)

### ISSUE THREAD

**Issue by Fabio0013** [flutter/flutter#54736]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Building flutter tool...

**Comment by AndreiCalazans** [comment]
Maybe you forgot to install the comand-line tools for xcode?

`xcode-select --install` 

if that doesn't work:
`sudo xcode-select --reset`

**Comment by VladyslavBondarenko** [comment]
Thanks @AndreiCalazans,

Related to https://github.com/flutter/flutter/issues/43565
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Closing, since after running the commands the issue should be solved,
@Fabio0013 comment please if it's not so and I'll reopen it
