### ISSUE TITLE
Codelab references firechat-flutter repository that no longer exists

### ISSUE THREAD

**Issue by aikinai** [flutter/flutter#5475]
## Steps to Reproduce

1. Follow [codelab](https://codelabs.developers.google.com/codelabs/flutter/#2)
2. See reference to `https://github.com/flutter/firechat-flutter.git` on page 3
3. Try to clone or browse to repo
4. Get repository doesn't exist or 404 error

**Comment by qchong** [comment]
@aikinai Thanks for your interest in our codelab. Please note that the codelab has been pulled due to dependencies on an out-of-date version of the Flutter SDK and Flutter Atom plugin. We hope to republish a new version of the codelab soon. In the meantime, please refer to the developer docs on [flutter.io](https://flutter.io/) and the Github [examples code](https://github.com/flutter/flutter/tree/master/examples).
