### ISSUE TITLE
Code highlighting is broken

### ISSUE THREAD

**Issue by rnitta** [flutter/flutter#54797]
In the flutter api doc, the highlighting of the sample code is slightly broken.

For instance,
https://api.flutter.dev/flutter/widgets/AnimatedSwitcher-class.html
<img width="620" alt="スクリーンショット 2019-08-08 16 24 39" src="https://user-images.githubusercontent.com/31783570/62683303-0ac21e80-b9f9-11e9-95cd-13ad419de11d.png">

The cause seems to be fixed [here](https://github.com/highlightjs/highlight.js/issues/1941) (and released in v9.14.0,)
and currently the apidoc uses highlight.js v9.13.1,
It worth to update the package.

fyi: pub.dev uses highlight.js v9.15.6

**Comment by TahaTesser** [comment]
Hi @rnitta 
Looks like code highlighting is fixed in https://api.flutter.dev/flutter/widgets/AnimatedSwitcher-class.html

<img width="932" alt="Screenshot 2020-04-15 at 4 08 51 PM" src="https://user-images.githubusercontent.com/48603081/79328325-76b73800-7f33-11ea-9326-adc27a152022.png">

if you disagree please write in the comments and I will reopen it 
Thank you
