### ISSUE TITLE
Elevated crash rates in 1.17.0

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54850]
We're above the threshold we set for monitoring.

<img width="1440" alt="Screen Shot 2020-04-15 at 8 28 52 AM" src="https://user-images.githubusercontent.com/1435716/79355929-2a4c0800-7ef3-11ea-9b7b-197160dad697.png">

Looks like two clusters (these are Google links)
https://crash.corp.google.com/browse?q=stable_signature%3D%27StateError+at+_StreamSinkImpl.add+at+dart%3Aio%2Fio_sink.dart-bb77f1e7%27
both around `Thread 0 main thread CRASHEDStateError: Bad state: StreamSink is closed`

<img width="427" alt="Screen Shot 2020-04-15 at 8 29 48 AM" src="https://user-images.githubusercontent.com/1435716/79356018-49e33080-7ef3-11ea-9b6a-1c9c11f5eb53.png">

cc @zanderso, @pcsosinski..

**Comment by pcsosinski** [comment]
first seen in 1.15.17

**Comment by kf6gpe** [comment]
Looks that way. I wonder why the increase in percent occurrence in 1.17.0, though.

**Comment by zanderso** [comment]
The elevated crash rate on 1.17.0 is web-related and won't carry over to stable. In particular, "StateError: Bad state: StreamSink is closed" is fixed upstream, and the fix should already be on master and dev afaiu. If it would calm nerves, we could mark the fix PR for cherrypicking. /cc @jonahwilliams for details if desired.

The elevated crash rate on hotfix.9, is for the same reason as on hotfix.8, and is fixed in master, dev, and beta.

Having said that, though, I don't know why the crash rate % is higher relative to yesterday. @jayoung-lee

**Comment by jayoung-lee** [comment]
The graph in the screenshot shows 'today' crash rate since midnight. So it can fluctuate throughout the day, due to the small number of samples.

**Comment by pcsosinski** [comment]
the next beta release will be mid-May.  sounds like this is not something we need to fix for 1.17

**Comment by pcsosinski** [comment]
@kf6gpe anything we need to do here?  based on the above comments it can probably be duped or just closed as obsolete?

**Comment by kf6gpe** [comment]
Let's close it as obsolete.

**Comment by dasebasto** [comment]
@Google: can you make this crash rate data public?
