### ISSUE TITLE
[flutter_tools] generate local test reports for flutter_tools

### ISSUE THREAD

**Issue by kawka-maciej** [flutter/flutter#54874]
## Use case

I would like to leave tests running and get back to them after they are finished to see some generated report so I could quickly tell which tests are failing without need to scroll console output manually.

## Proposal

Optional generation of tests reports for flutter_tools repo.

CC: @christopherfujino

**Comment by christopherfujino** [comment]
So I just found this: https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md

Obviously JSON is not the most human-readable. When we run the tools tests, we're not using the flutter CLI tool at all, we're using the external https://github.com/dart-lang/test package, so any feature requests (i.e. for HTML report generation) should be against that repo. However, maybe writing a script to parse the JSON output would be easiest?

**Comment by christopherfujino** [comment]
I came back here because I spent half an hour trying to figure out why my test was failing on CI but not locally...only to discover I was running the wrong test.

Giving this more thought, I'm thinking that writing a script to parse package test's json reporter and pretty-printing it in cirrus would make addressing test failures a lot easier.

**Comment by jonahwilliams** [comment]
This is definitely interesting, but it seems like it would be better suited as a feature request for https://github.com/dart-lang/test . We use this library with zero modification in the tool for testing.

**Comment by christopherfujino** [comment]
This was fixed by https://github.com/flutter/flutter/pull/120716
