### ISSUE TITLE
Several of our customers are missing tons of possible errors/warnings in their apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5488]
One possible solution would be to include an analysis_options file.  If we did that, ideally a rather aggressive one, possibly matching flutter's:
https://github.com/flutter/flutter/blob/master/.analysis_options

Currently we don't have one:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/create

I learned that several of our customers don't have .analysis_options files and the default dartanalyzer is very loose, thus they are missing tons of possible errors/warnings in their apps.

@pq @Hixie @devoncarew

**Comment by devoncarew** [comment]
If we're comfortable with using flutter's, we could copy it into the newly created project as part of `flutter create` (copying and tweaking either the one in // or in //packages/flutter_tools).

**Comment by pq** [comment]
👍   Adding this to `flutter create` makes sense to me.

**Comment by abarth** [comment]
We've been around this circle before.  The analysis options file we use ourselves for flutter is too strict for our customers.  For example, we require types to be used everywhere possible, which many customers don't like.

This bug is framed as a solution rather than stating a problem, so it's hard for me to know what other solution to propose.  @eseidelGoogle what is the problem you would like solved here?

**Comment by eseidelGoogle** [comment]
My understanding is the old solution was that we enforced our styles from the package rather than the create template, but yes, we've definitely explored other points in this space before.

I learned that customer: fast didn't have any analysis options turned on when I had lunch with one of their engineers on Weds.  The problem they hit was they were having errors which dart could tell them about but wasn't, it seemed odd to me that we had set them up this way.

**Comment by sethladd** [comment]
I like putting in a starter-recommendation for .analysis_options. I don't think we'll include every option that Flutter uses, but I'm sure there are a few lints that we would recommend.

Bonus: as @eseidelGoogle points out, the .analysis_options is a file under user control.

@eseidelGoogle do you happen to remember what our users should have seen in their editor? We could start an .analysis_options file with those lints turned on.

**Comment by danrubel** [comment]
@eseidelGoogle @sethladd @johnmccutchan @devoncarew 
Please look over the [analysis_options in my PR](https://github.com/flutter/flutter/pull/5573) which are a copy of the repo analsys_options. I can have `flutter create` copy them as part of project generation rather than a separate analysis_options template file as I have done, but I assumed (incorrectly?) that the project analysis_options will be different than the repo analysis_options.

**Comment by abarth** [comment]
I'm not sure I agree with the title of this issue.  It's difficult to propose alternate solutions because this issue is phrased as a solution (i.e., include an .analysis_options file) rather than as a problem that could potentially have other solutions (e.g., customer X was sad because they missed lint Y).

**Comment by Hixie** [comment]
I changed the title, though more specifics would be useful indeed. @eseidelGoogle

**Comment by abarth** [comment]
Specifically, what I'd like to understand is whether the errors/warnings they are missing are specific to Flutter or would be valuable for Dart developers in general.  If they would be valuable to Dart developers in general, that might guide us towards a solution for Dart as a whole rather than a Flutter-only solution, as was previously proposed.

**Comment by danrubel** [comment]
Based on the comments above, I'm leaning towards dropping https://github.com/flutter/flutter/pull/5573 in favor of:
* updating the existing [`flutter_analysis_options`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/flutter_analysis_options) which is already used by `flutter analyze`
* update `flutter analyze` to use the `.analysis_options` in the project root if it exists
* add a top level `flutter_ide_analysis_options` file similar to the `flutter_analysis_options`
* update Atom and IJ to analyze with `flutter_ide_analysis_options` if an `.analysis_options` file is not present in the project root
* document and encourage other flutter IDE integrators to do the same

Advantages:
* all who use `flutter analyze` or a flutter IDE plugin get this functionality automatically
* the `.analysis_options` file can be updated for all users when they upgrade their SDK
* users can override by having their own `.analysis_options` file in their project root

This gets better analysis results to our customers today, enables us to update the analysis options for all users tomorrow, and decouples working with the analyzer team over time to perhaps turn on some of these options for all Dart customer as @abarth suggested.

**Comment by danrubel** [comment]
Per conversation with @Hixie, the current plan is to update `flutter analyze` to have
* 2 modes: strict and not strict where https://github.com/flutter/flutter/pull/5679 represents the strict mode analysis options
* flutter project analysis defaults to strict mode analysis
* a flag to disable strict mode stored somewhere in the customer's project (in `flutter.yaml` or `pubspec.yaml` or ?... will talk with the Analyzer team) 
* when analyzing anything in the flutter repo, regardless of whether `--flutter-repo` flag is present, use the `.analysis_options` in the flutter repo root
* when analyzing a customer's project, use the `.analysis_options` in the customer's project root if it exists

and longer term
* work with the Dart analyzer team to update `dartanalyzer` with the necessary features so that eventually we can call it as a separate process rather than embedding the analyzer package
* work with the Dart analyzer team so that analysis of flutter projects (e.g. using analysis server) uses our default analysis options if an `.analysis_options` file is not present in the project root
* work with the Dart IJ plugin team to surface this less strict mode option so that user's can easily turn off 

@eseidelGoogle @abarth and others... thoughts?

**Comment by sethladd** [comment]
> strict and not strict

I'm concerned about so many modes. Is strict == flutter_sdk_rules and not strict == ?? Maybe different names for the different presets.

> a flag to disable strict mode stored somewhere in the customer's project

Why would a user need to opt-out of Flutter SDK's rules? Shouldn't the Flutter SDK opt _in_ to their additional checks?

**Comment by Hixie** [comment]
strict is not flutter_sdk_rules. flutter_sdk_rules is the rules in the .analysis_options file in the flutter repo root. (There's some complication to handle here with respect to the dartdoc lint, so that `flutter analyze` can report the count of that lint but IDEs don't complain about it. We could even enable the todo lint in the `flutter analyze` case and report that count too. And further to what @pq suggested earlier today, maybe also the count of `// ignore`'ed errors.)

strict is probably more like flutter_sdk_rules minus things like `sort_constructors_first` which are really just flutter style rules in lint form.

not strict is strict minus things like `always_specify_types` and `annotate_overrides` to make the language more attractive to people who care about specifying types.

Ideally, IDEs would offer to downgrade from strict to non-strict the first time they report a strict warning, if the user hasn't made a choice yet.

**Comment by Hixie** [comment]
@sethladd and I spoke more about this today. Seth is concerned about us forcing out opinions on people, and about having multiple modes. We came up with the following alternative proposal:

1. There's a small number of sensible defaults that every Flutter dev should have turned on, e.g. `valid_regexps`. These are things that prevent real bugs and have no plausible reason to be off.

2. New projects get a default minimal .analysis_options file, which does nothing but link to http://dart-lang.github.io/linter/lints/ and whatever other documentation exists for this file.

3. `flutter analyze` does the same as IDEs for a brand new project.

4. The project's `.analysis_options` file overlays the Flutter's defaults from item 1, it's not a wholesale replacement.

5. We can provide, in our documentation, a sample `.analysis_options` file that has things like `always_specify_types`, but we don't make it the default. The context would be "here are ways to opt in to even more checking that might make your code stronger". This is the only step that is really our opinion (an "editorial piece"). Maybe it just points to our SDK's `.analysis_options`.

It's not clear to me how well this addresses Eric's original bug report because I don't really know what errors Eric was talking about. It does take care of type-averse users, since by default it doesn't require types. It takes care of type-enamoured users (like us) since they can opt-in to whatever they want. It avoids the problem Adam mentioned in the PR about users falling off the train if we provide people a detailed `.analysis_options` file, since by default the `.analysis_options` file does nothing and anything they put there merely overlays on top of what we define as "sensible defaults".

**Comment by sethladd** [comment]
Related (just FYI), stagehand is now creating a default (but commented out) .analysis_options: https://github.com/google/stagehand/pull/333

**Comment by danrubel** [comment]
Updated bullet list above based upon conversation with @sethladd et al.

**Comment by eseidelGoogle** [comment]
I'm not sure what (if anything) is more to do with this bug?

**Comment by danrubel** [comment]
I'm still working on cleaning up `flutter analyze`, but no need to keep this bug open for that.
