### ISSUE TITLE
Which instruction to follow while enabling platform views

### ISSUE THREAD

**Issue by SametSahin10** [flutter/flutter#54906]
While installing google_maps_flutter plug-in, it's required to enable embedded view on iOS side. According to the instructions on [pub.dev page of google_maps_flutter](https://pub.dev/packages/google_maps_flutter#-readme-tab-), one needs to add the key `io.flutter.embedded_views_preview` into Info.plist file with the value `YES`. As a developer with Android Development background, I find this a bit confusing. The statement does not specify the type of value which in this case is ´YES´. On the other hand, I've seen people using value `<true/>`. This usage can be found in the  **[Adding Google Maps to a Flutter App](https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/#0)** codelab as well. I've successfully added google_maps_flutter plugin to my app by using `<true/>`. Which way to do this is the right one? Am I missing something related to Info.plist file and the way it works?

**Comment by darshankawar** [comment]
@SametSahin10 
The plugin has gone through many updates since this issue was logged. The plugin is now out of developer preview and since Flutter 1.22 we no longer need to use the `io.flutter.embedded_views_preview to Info.plist in iOS.`

Check this change log when it was introduced: https://pub.dev/packages/google_maps_flutter/changelog#101

Current plugin version is https://pub.dev/packages/google_maps_flutter/install

Closing this since it is not a valid issue anymore.
