### ISSUE TITLE
"Building flutter tool..." takes forever when upgrading flutter

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#54943]
## Steps to Reproduce

on macOS Catalina
1. Invalidate cache in Android Studio 3.6
2. Open Terminal, and type `flutter upgrade`. Note that I'm on dev channel
3. Seeing the logs below

## Logs

```sh
$ flutter upgrade
Downloading Dart SDK from Flutter engine beb8a7ec48f6b980a778d19eeda613635c3897c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0     25      0 --:--:-- --:--:-- --:--:--    25
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries 
Warning: left.
Throwing away 16 bytes
100  219M  100  219M    0     0  6082k      0  0:00:37  0:00:37 --:--:-- 6324k
Building flutter tool...
```

```sh
$ flutter doctor -v
Building flutter tool...

```

**Comment by kakyoism** [comment]
I've ruled one more possibility: After a macOS Catalina upgrade, I had to install Xcode command-line components. But even after that, once again I'm stuck at the same place.

There should have been a clear log message telling me what's taking so long. 
The download logs do that well.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/26391

**Comment by kakyoism** [comment]
Solved. Seems a network issue. I'm located in China. Had to use StealthVPN to finish the building. 

There really should be a clear warning. It's hard to imaging "building ..." involves internet access.

**Comment by jonahwilliams** [comment]
This isn't something we can fix in the flutter tool. The website contains documentation on this in https://flutter.dev/community/china

**Comment by hisreal123** [comment]
For i had the same issue for 2weeks, i had to change IPVanish VPN to change my location and it worked well .
Change Location with VPN
run flutter upgrade again in terminal
run flutter doctor

**Comment by alvindera97** [comment]
Is there something that can be done to mitigate these network provider related issues that are happening with Flutter? The first time I had to install flutter, I had network issues that didn't let me to download flutter and I had to change my ISP just so that I could install flutter on my PC.

Now upgrading flutter is a hassle just because of this network related problem again. This is a very big problem. I have never experienced ISP related constraints or issues from basically every other package, be it linux's app repos or python's package index. Why does it have to be Flutter?????
