### ISSUE TITLE
Support for Firebase Analytics FlutterFire

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#5497]
In order to enable developers to create fully-featured Flutter apps with Firebase, the Flutterfire SDK should support at least Firebase Analytics and Firebase Storage. 

Specifications can be found on https://firebase.google.com/docs/analytics/ and https://firebase.google.com/docs/storage/ . Some features may have already been implemented in https://github.com/firebase/firebase-dart, so this may be worth a look as well.

**Comment by eseidelGoogle** [comment]
FYI @collinjackson.  We recently re-wrote our plugin/services model, you can see the new approach here: https://github.com/flutter/flutter/tree/master/examples/hello_services.  Unfortunately that meant that all our old plugins (including for firebase) were no longer valid.  We'll be replacing them over time, but it may be a while.  We're currently very distracted by helping internal Google customers ship their Flutter apps.  FYI @collinjackson

**Comment by sethladd** [comment]
If you're curious, please do give it a try yourself. See some docs here: https://flutter.io/platform-services/

The services model is pretty new, so we're definitely looking for feedback.

**Comment by collinjackson** [comment]
Thanks for the feedback. Analytics is pretty high up on my list of future plans for flutterfire. :)

**Comment by sethladd** [comment]
Going to split this issue into two. Thanks for the feedback!

**Comment by collinjackson** [comment]
Here are some notes I took while researching this.

Firebase docs for Analytics:

iOS:
https://firebase.google.com/docs/analytics/ios/start
https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics

Android:
https://firebase.google.com/docs/analytics/android/start/
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics

The FirebaseAnalytics methods are all static and there's only a handful of them, so it should be pretty straightforward to implement. The only method that needs to work for the codelab is this one:

FirebaseAnalytics.logEvent(name: 'send_message', parameters: {'content_type': 'image'});

There are three static FIRAnalytics methods that can be called in the developer's AppDelegate on the iOS version of their app to get optimal analytics. I'm thinking that maybe we should have FlutterAppDelegate provide plugins with a way to register handlers for these types of callbacks, because this is a very common pattern we're seeing in plugins. But for now, we can make the developer can do it manually if they want to get the extra info.

There are a bunch of "suggested" event and parameter names that should probably be copied and live as constants in the Dart part of the plugin:

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param

Example of a Flutter Firebase plugin: https://github.com/flutter/firebase_storage

You can create use "flutter create --plugin firebase_analytics" to make the Analytics plugin, and create a repo called https://github.com/flutter/firebase_analytics

You can create a temporary throwaway Firebase instance for testing at console.firebase.google.com. Eventually we probably won't want the google-services.json/GoogleSignIn-Info.plist files to be checked in to the examples on GitHub, but it's not a huge deal if they end up getting checked in as we can easily recreate Firebase instances.

**Comment by yjbanov** [comment]
Thanks for the notes!

**Comment by mit-mit** [comment]
For an overview of Firebase plugins, see https://github.com/flutter/plugins/blob/master/FlutterFire.md

**Comment by kroikie** [comment]
@stemuk

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1018. Any further collaboration will be done there.
