### ISSUE TITLE
image_picker: how to access to Gallery directly

### ISSUE THREAD

**Issue by faspadaro** [flutter/flutter#55034]
Using the gallery of image_picker on Android you get a type of document picker with menus allowing you to choose the image from many resources but I would like to access to Gallery directly without to choose it from menu.
Is it possible?

**Comment by TahaTesser** [comment]
Hi @faspadaro 
I don't think it's possible, since each device has different type of gallery apps.
Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow. 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
