### ISSUE TITLE
No MaterialLocalizations found if ...

### ISSUE THREAD

**Issue by skmohammadi** [flutter/flutter#55035]
Hi. please look at following code:

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BMS',
      home: Scaffold(
        body: Container(
          child: Center(
            child: RaisedButton(
              color: Colors.redAccent,
              textColor: Colors.white,
              onPressed: () {
                testAlert(context);
              },
              child: Text("PressMe"),
            ),
          ),
        ),
      ),
    );
  }
}
```
By clicking on Button i got this error: `**No MaterialLocalizations found**.`

But if **home** value be **stateless** widget like below, it works very well:

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BMS',
      home: HomePage(),
    );
  }
}
```

So, why it is need that value of **home** be a stateless widget?

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @skmohammadi, this is because the BuildContext, `context`, you're passing into your `testAlert` call is from the widget tree _above_ your `MaterialApp`, where localizations are defined. In order to correctly pass the BuildContext that contains your MaterialLocalizations, you needed to create the `home` widget to pass the BuildContext from that level of the widget tree upwards.

```
App
  | --> MaterialApp
          |--> home (context here)
                   |--> testAlert(context)
```

vs
```
App (context here)
  | --> MaterialApp
           |--> home 
                  |--> testAlert(context)
```

I will close this issue, since this isn't really a problem with Flutter.
