### ISSUE TITLE
Android keyboard not displayed using Android EditText

### ISSUE THREAD

**Issue by apally-orange** [flutter/flutter#55046]
Hello,
I have a problem with a Android EditText embedded in layout view with Flutter UI/Activity plugin, the keyboard not display when EditText have focus.

## Steps to Reproduce
Create a Flutter UI/Activity plugin, in the class native view (implement PlatformView), the getView method, return a layout with embedded EditText:
```
private val layout = LinearLayout(context)

init {
        layout.layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        layout.orientation = LinearLayout.VERTICAL
        val tv2 = EditText(context)
        layout.addView(tv2)
}

override fun getView(): View {
        return layout
}
```

When the edit text have the focus, the keyboard not display.
I have create this repository to reproduce in basic application the problem
https://github.com/apally-orange/flutter_test_embedded_android_view

<details>
  <summary>Logs</summary>

I have this trace error when i click on EditText :
```
D/InputMethodManager(23912): SSI - flag : 0 Pid : 23912 view : com.example.test.flutter_test_embedded_android_view_example
D/InputMethodManager(23912): showSoftInput - cancel : mServedView != view : DecorView@c0bb281[MainActivity]  view : android.widget.EditText{dd001f VFED..CL. .F.P.... 0,54-1080,179}
D/Editor  (23912): waiting for the right moment
```

`flutter doctor -v` output:
```
[√] Flutter (Channel dev, v1.18.0-dev.5.0, on Microsoft Windows [version 10.0.17763.1039], locale fr-FR)
    • Flutter version 1.18.0-dev.5.0 at C:\Users\XCNT2590\flutter
    • Framework revision 7f56b53de4 (5 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\XCNT2590\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\XCNT2590\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • SM A505FN  • R58M93DGX4J • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome      • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server  • web-javascript • Flutter Tools

• No issues found!
```
</details>

**Comment by xster** [comment]
Thanks for the repro @apally-orange. I have a slightly tangential question. Is the root cause that there are Android EditText functionalities missing in the Flutter TextField that necessitated inserting an Android EditText in the middle of the hierarchy?

**Comment by letsar** [comment]
Hi @xster.

For the context, the issue is happening in an Android third party package for which we are creating a Flutter plugin. In this package, there is a native view where there is an EditText, in which the keyboard does not show up when we want to enter text.

We wanted to know if it was an issue from the package itself or from an EditText embedded in a PlatformView.

We created this simpler project to see if we could reproduce it without the third party package, that's why the repro case is very simple.

**Comment by gaaclarke** [comment]
@apally-orange can you update your example to be a complete example please?  One that can just be run to see the results?  Currently it is missing a `main` and when one is added I get:
```
Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running
`flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
```

**Comment by gaaclarke** [comment]
(Previously I asked for an update to the repro code, I got to working thanks!)

**Comment by gaaclarke** [comment]
@apally-orange I've done some research and poked around at your sample code.  I've found some ominous documentation that seems to suggest what you are trying to do isn't as straight forward as I'd expect: https://github.com/flutter/flutter/wiki/Android-Platform-Views#text-input

The webview plugin which would be doing text entry seems to be doing some of this trickery with the input connection: https://github.com/flutter/plugins/blob/266185f553ee7ae9221f5db0ba57a4c9e2d6f0d8/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java#L95

The TextEntryPlugin in the engine seems to have some special case logic apropos platform views as well: https://github.com/flutter/engine/blob/4bcfae82c7c18460c1558cea52c993ebe4439a03/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L143

I don't quite understand all of this.  I'll try to get ahold of some people who knows this code better.  I'm still not clear if there is a bit of extra work that has to be done on the plugin to get text input, or if there is the bug in the mechanism that's suppose to make that work.

**Comment by xster** [comment]
@amirh I just read @gaaclarke's last point. You were saying that since this doesn't revolve around the webview's complex handling, the normal platform view text handling should mostly work and this is just a bug rather than a big new feature right?

**Comment by mklim** [comment]
So webview's workarounds can be safely ignored for this case. It has some special cased logic because of multi-threaded logic around text in Chromium. [Described here for reference, but shouldn't be relevant to other cases](https://github.com/flutter/flutter/wiki/Android-Platform-Views#in-embedded-webviews). The only way this _may_ be relevant is that the `isInputConnectionLocked` bool in the engine is mostly in place because of webview's unusual needs, so if that's related to a bug then this suddenly becomes related again.

The workarounds we're doing under the hood for text input are brittle, but they _should_ enable text input in platform views by default as far as I'm aware. I didn't try to repro but at a glance  apally-orange/flutter_test_embedded_android_view looks like it should work to me. If we're not it could be a regression or a new bug in the webview logic.

[This](https://github.com/flutter/engine/blob/036ddbb0ee6858ae532df82a2747aa93faee4487/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L206) is the mechanism that should enable text input in all webviews without more work required from the plugin developer.

@apally-orange what versions of Android are you seeing this bug in? The text input logic changes internally slightly based on that, so that may be related.

**Comment by gaaclarke** [comment]
I ported the example code to `v1.12.13+hotfix.8` and the keyboard doesn't come up there either.

**Comment by gaaclarke** [comment]
I looked for third-party plugins that may be doing this for reference and there doesn't appear to be any: https://github.com/search?q=%22io.flutter.plugin.platform.PlatformView%22+edittext&type=Code

I also found this stackoverflow question asking this same question from one year ago: https://stackoverflow.com/questions/55057319/edittext-not-showing-keyboard-when-tapped-in-flutter-androidview. (reported for v1.2.1)

I suspect this is something that never got implemented, not a bug per-say, but an oversight in implementation.

**Comment by gaaclarke** [comment]
I talked to @amirh, he is under the impression that [this PR](https://github.com/flutter/engine/pull/9257) would have implemented text entry which got rolled in [v1.16.3](https://github.com/flutter/flutter/commit/7a877f62d96743033eff5be720de98ba4ac7d3c2)

He also suspects it may be an OS version issue, I've reproduced it on Android Q, I'll try a previous version.

**Comment by gaaclarke** [comment]
I tested the example code on Android 9 (pie) and it also doesn't bring up the keyboard there either.

**Comment by xster** [comment]
nit re: https://github.com/flutter/flutter/issues/55046#issuecomment-619267252, it's v1.7.4 rather than v1.16.3 I think (expand the tags, there are older ones).

**Comment by apally-orange** [comment]
> @apally-orange what versions of Android are you seeing this bug in? The text input logic changes internally slightly based on that, so that may be related.

I see the bug on Android 9

**Comment by apally-orange** [comment]
I have do some tests on new Flutter release (1.19.0-1.0.pre) and the bug always present

**Comment by letsar** [comment]
Hi @xster and @gaaclarke. 
If you need anything from us to progress on this issue we will be happy to help.
This is a thorn in our side and it could literally kill our product if we don't find a solution or a workaround. Do you have a hint on how to resolve this issue?

**Comment by gaaclarke** [comment]
Here is the good news, what you are trying to do is possible.  There isn't a bug, it's just not straightforward to do.  We know that because text entry works with the `webview_flutter` plugin.  I've been poking at trying figure out how that works.  Here is my latest suspect: [ThreadedInputConnectionProxyAdapterView](https://github.com/flutter/plugins/blob/e26634c4ac1def13776769912d3873ec17316fbc/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/ThreadedInputConnectionProxyAdapterView.java#L38) which is created in [InputAwareWebView](https://github.com/flutter/plugins/blob/37145e726659140c0b4bb8fec85deabad461d48b/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java#L104)

If you follow the code you'll see that that is ThreadedInputConnectionProxyAdapterView is getting created with [`registrar.view()` as the container view](https://github.com/flutter/plugins/blob/e26634c4ac1def13776769912d3873ec17316fbc/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java#L49).

Your plugin is doing nothing with the Registrar's view.  I'll poke around some more but honestly you can probably try things out quicker than I can since I usually don't work with Android.  I don't have direct steps to fix your problem yet but that's my best lead so far.

**Comment by gaaclarke** [comment]
I fixed your example: https://github.com/apally-orange/flutter_test_embedded_android_view/pull/1

It isn't pretty I'll admit, but there you go =)  We can look into making this easier in the future at some point.  *spikes football*

**Comment by gaaclarke** [comment]
For future archaeology, my thoughts in the previous comment were right about ThreadedInputConnectionProxyAdapterView and InputAwareWebView.  I duplicated the trickery it is doing with [checkInputConnectionProxy](https://developer.android.com/reference/android/view/View#checkInputConnectionProxy(android.view.View)) and text input started working in the example.

**Comment by mklim** [comment]
I'm glad there's a workaround, but I think this is still an open bug in the Android text/platform view logic. We shouldn't be requiring general Android platform views to perfectly mimic webview's multithreaded internal logic to work. Webview is only as complicated as it is because there were extra obstacles that needed to be worked around to pass off the input connection on the right thread to chrome.

**Comment by letsar** [comment]
Thank you for the workaround and the fix in the sample @gaaclarke. But as @mklim  said I don't think we should require to do this.

Moreover in our case the workaround won't work because in the end the EditText is in a view from another native third party package and we cannot modify its code.
The sample was as simple as that just to demonstrate the issue. How can we fix this if we don't have the hand on the native code of the view where the EditText is?

**Comment by gaaclarke** [comment]
@mklim Yep, I agree there is still an outstanding issue.  The implementation has nothing to do with threading and just setting up input connections.  I plan on making a new issue that is more apropos and saving this one for letsar's specific issue.

@letsar Put the 3rd party View in your own View that does the InputConnection setup.  I'm going to spawn another bug that will get triaged and when it eventually gets fixed it will be in beta release until finally makes it to Stable.  Realistically we are talking months.  If it were my product I would try to use the workaround through a custom parent view or setting up the input connection without subclassing (I'm not too familiar with the Android API so I don't know if the latter is possible offhand).

**Comment by letsar** [comment]
Thank you @gaaclarke. 

We tested with a custom parent around the native third party view but the issue was still here. If the workaround is pure Android, maybe we can talk with the third party developers so that they could help us. Otherwise, since this is very critical for us, I will come back to you to see what we can do to reduce the delay for fixing this.

**Comment by gaaclarke** [comment]
![input-connection-setup](https://user-images.githubusercontent.com/30870216/82357526-1d22ad00-99ba-11ea-9f50-f85d54a54901.png)

![input-connection-sequence](https://user-images.githubusercontent.com/30870216/82359699-16496980-99bd-11ea-9aca-87c0e39fe7bd.png)

I added a diagrams of the workaround to help document.

@letsar I'm willing to help you apply the workaround but you're going to have to give me more information to work with.  I fixed the provided sample code with the workaround, can you provide a more apropos sample that reflects the current issue?

**Comment by letsar** [comment]
Hi @gaaclarke, did you had time to look at the new repo we created (https://github.com/apally-orange/test_bug_visio) with the integration of the third party SDK we mentioned?

**Comment by letsar** [comment]
Hi @gaaclarke this is me again.

We tried your workaround (https://github.com/gaaclarke/flutter_test_embedded_android_view/tree/fix-text-input) on different devices and he have strange results:
At first, the keyboard does not appear, but when we switch between the two inputs, at some time (25s on the video below), the keyboard starts showing up, but it will only write in one input, even if we select the other one.
This is a link to a video showing this: https://youtu.be/0loIlvzccGk

We tested this with Flutter 1.20.0-7.4.pre on these devices, with the same result each time:
- Samsung Galaxy S8, Android 9
- Samsung Galaxy Note10+, Android 10
- Redmi Note7, Android 10
- Samsung A40, Android 10
- Samsung Galaxy A6+, Android 10
- Samsung A40, Android 9
- Motorola G6, Android 9

A coworker told us that it worked on a OnePlus 5T though.

The workaround seems to not work on all devices. Do you, or another member of the team have time to look into this issue again?

cc @timsneath

**Comment by blasten** [comment]
I tried the example app using hybrid composition and the keyboard works just fine.  @letsar Give it a try: https://github.com/flutter/flutter/wiki/Hybrid-Composition#android

**Comment by dailystudio** [comment]
> Hi @gaaclarke this is me again.
> 
> We tried your workaround (https://github.com/gaaclarke/flutter_test_embedded_android_view/tree/fix-text-input) on different devices and he have strange results:
> At first, the keyboard does not appear, but when we switch between the two inputs, at some time (25s on the video below), the keyboard starts showing up, but it will only write in one input, even if we select the other one.
> This is a link to a video showing this: https://youtu.be/0loIlvzccGk
> 
> We tested this with Flutter 1.20.0-7.4.pre on these devices, with the same result each time:
> 
> * Samsung Galaxy S8, Android 9
> * Samsung Galaxy Note10+, Android 10
> * Redmi Note7, Android 10
> * Samsung A40, Android 10
> * Samsung Galaxy A6+, Android 10
> * Samsung A40, Android 9
> * Motorola G6, Android 9
> 
> A coworker told us that it worked on a OnePlus 5T though.
> 
> The workaround seems to not work on all devices. Do you, or another member of the team have time to look into this issue again?
> 
> cc @timsneath

Hi @letsar,

As @mklim @blasten said, with Flutter 1.20, this issue could be fixed through Hybrid Composition. I have created a repository to test it:
https://github.com/dailystudio/flutter-hybrid-composition-demo

I hope this could help you to address the problem.

**Comment by letsar** [comment]
Youhouuuuuuuuu :tada: :clap: :clap: :clap: :clap:
It works with hybrid composition, thank you a lot @mklim @blasten @dailystudio  !!!!!
This is good news. We will test further to be sure we don't see any drawback with this solution, before closing this issue, but it seems to works like a charm at a first glance :-).

**Comment by letsar** [comment]
I think we can close this issue since we didn't see any drawbacks with this so far. Thanks again everyone for helping us out!
