### ISSUE TITLE
MediaPlayer widget 

### ISSUE THREAD

**Issue by hiwa-jalal** [flutter/flutter#55086]
playing a video or an audio is a feature that is very essential and most of apps need it, yet flutter doesn't have a way to handle it without third-party packages, i appreciate those people work on creating those packages but most of them have some flaws, so we just need a one way solution to play media and have controller over it like in notification bar or lock screen and having seek, loop, etc...features.

**Comment by iapicca** [comment]
Hi @hiwa-jalal 
[video_player](https://pub.dev/packages/video_player) is a first party plugin,
what feature are you finding missing?
thank you

**Comment by hiwa-jalal** [comment]
oh thanks, and yes i actually find that there is a lot of room for improvement and first i think it's name should be changed to `media_player` because at first glance you won't even think of it being capable to play audio, and also i think we should be able to control it through notification bar and lock screen and if it can provider a basic player interface like exoplayer does then it will be amazing.

**Comment by VladyslavBondarenko** [comment]
@hiwa-jalal 
follow up on the media lock screen request https://github.com/flutter/flutter/issues/40722
and the seek bar request https://github.com/flutter/flutter/issues/33338 (since not implemented, you can consider to use a 3rd party plugin with a seek bar, for example [chewie](https://pub.dev/packages/chewie)).
Please create separate issues for controls in notification bar and renaming (or other, if they are not already filed).
Closing since initial issue was answered,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by hiwa-jalal** [comment]
thank you.
