### ISSUE TITLE
Unable to login into APP through gmail account.

### ISSUE THREAD

**Issue by shah0203** [flutter/flutter#55158]
hi,

when i am trying to login into my fluxstore woocommerce app through gmail account but it is getting faile with below error. Can anyone help me to resolve it.

**Warning: There is an issue with the app during request the data. please contact admin for fixing the issue platformexception(sign_in failed com.google.android.gms.common.api.apiexception 10 null)**

**Comment by iapicca** [comment]
Hi @shah0203 
the [fluxstore](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325) seems to be a commercial product rather than part of flutter framework;
the warning you from your logs invites to contact admin, this might be the right course of action to take.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
