### ISSUE TITLE
Pesto: Topmost item remains invisible till it is scrolled to its image.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#5522]
While scrolling down, the topmost item will only become visible when the item is scrolled far enough down till its image is on the visible scroll surface.

Video: https://www.youtube.com/watch?v=zHq_F25WLtE

**Comment by sethladd** [comment]
cc @mpcomplete might be interested in this?

**Comment by mpcomplete** [comment]
The problem is the `padding` argument to ScrollableGrid's delegate:

```
    final EdgeInsets padding = new EdgeInsets.fromLTRB(8.0, 8.0 + _kAppBarHeight + statusBarHeight, 8.0, 8.0);

    return new ScrollableGrid(
      ...
      delegate: new MaxTileWidthGridDelegate(
        maxTileWidth: _kRecipePageMaxWidth,
        rowSpacing: 8.0,
        columnSpacing: 8.0,
        padding: padding
      ),
      ...
    );
```

The bug goes away if I remove the _kAppBarHeight factor from the `padding` - though this introduces a different bug. I think the ScrollableGrid is incorrectly taking the padding into account when deciding whether to render a child item.

**Comment by sethladd** [comment]
Thanks for the fix!
