### ISSUE TITLE
shared_preferences: persistence not guaranteed?

### ISSUE THREAD

**Issue by pedroslopez** [flutter/flutter#55234]
Hi! Reading the flutter docs while searching for an alternative to localStorage for flutter apps, they suggest using shared_preferences to persist values to disk [https://flutter.dev/docs/cookbook/persistence/key-value](https://flutter.dev/docs/cookbook/persistence/key-value)

However, the first paragraph of [https://pub.dev/packages/shared\_preferences](https://pub.dev/packages/shared_preferences) states that neither platform (ios/android) can guarantee the persistence. Why exactly is this persistence not guaranteed?

**Comment by philipdolenko** [comment]
Hi, the library is using native android and ios ways to store data locally so there are no disadvantages comparing with native development. "persistence is not guaranteed" its just the nature of storing files local rather than the cloud. For example on Android users can clear app data then all data in shared prefs will be deleted, again it's not a flutter specific "problem" it's just how it works.

**Comment by stuartmorgan** [comment]
Please use one of the more general options on https://flutter.dev/community for questions in the future; the issue tracker is for bug reports and feature requests.

The system preference store on iOS (I assume the same is true on Android) write asynchronously to disk, so if you set a preference and then the application crashes immediately there's no guarantee the write will have happen, even if the method call returned.
