### ISSUE TITLE
Rewrite format.sh in Python

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#55472]
format.sh is nearly 100 lines of somewhat complicated logic; it should really be rewritten in Python (IMO, but also [per Google style](http://google.github.io/styleguide/shellguide.html#when-to-use-shell)).

See https://github.com/flutter/engine/pull/17891#issuecomment-618150933 for a concrete example of where doing something that should have been straightforward was not, due to the use of bash.

**Comment by smarty1palak** [comment]
Hi, I would like to work on this issue. Thanks!

**Comment by stuartmorgan** [comment]
Great! Just link to the PR when you have one ready, and someone can review it.

**Comment by Matt-Gleich** [comment]
I can't seem to find this file anymore. Has it be renamed or merged into a different file?

**Comment by stuartmorgan** [comment]
No, it it's still at https://github.com/flutter/engine/blob/master/ci/format.sh

**Comment by Matt-Gleich** [comment]
Oh I though it was in this repo. Thanks!

**Comment by AndrewAblenas** [comment]
Is this still issue still looking for additional contributors?

**Comment by stuartmorgan** [comment]
Until someone links to a PR here, I would assume it's not being worked on.

**Comment by cyriacbijun** [comment]
Hello @stuartmorgan , I would like some clarification regarding the mentioned file. Pardon me if this seems like newbie questions:
1)How to implement the `set -e`  command in python?
2) Can I get more clarification as to what happens when `git remote get-url upstream >/dev/null 2>&1;` is run?
I had searched for the 1st question online, to no avail. There was not much comment provided for second one.  Please help as I am just starting off contributing and would be glad to refer some material, if provided

**Comment by Niranjan-10** [comment]
hello @cyriacbijun, I am also new to open source project and I would like to contribute to this issue, can we work together?
