### ISSUE TITLE
Linear Progress Indicator does not match the material spec

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#55481]
The [material spec](https://material.io/components/progress-indicators#specs) calls for a height of 4dp but it is currently set to 6dp (with no way to change it).

**Comment by Abhi011999** [comment]
Regarding the Linear Progress Indicator's material specs [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/res/anim/progress_indeterminate_horizontal_rect1.xml) and [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/res/anim/progress_indeterminate_horizontal_rect2.xml), the animation duration is actually 2000 ms while in flutter's implementation it's 1800 ms.

Is this intentional ?
