### ISSUE TITLE
Writing customer code in windows directory for windows app

### ISSUE THREAD

**Issue by jesseframework** [flutter/flutter#55496]
Hello Flutter Team,

Not sure if this is something possable but i would like to know if it possable to write custom code in the windows director of my flutter app. My plan is to write custom codo for function not yet supported. Example:

1. Localization
2. Firebase Messaging - I want to used windows messaging as custome code. Is this possable?

**Comment by stuartmorgan** [comment]
Flutter's model is that other than the code in the `flutter/` subdirectory, once you've created your application from the template you can change it however you like.

However, since Windows isn't stable yet, be aware of the fact that as noted [here](https://github.com/flutter/flutter/wiki/Desktop-shells#create) an in the warning at the end of the `flutter create` output, there will continue to be breaking changes in that folder until Windows has stabilized further. It will be up to you every time that happens to either
- re-apply your changes to a clean template, or
- apply the template changes to your project.
(I recommend the former, because you will be familiar with the changes you made, but not the template changes.)

Until Windows reaches the point where that warning is removed, I suggest isolating your code to separate files as much as possible to make it easier to update to new templates. Once the warning is gone, you can more freely mix your changes into what's generated by the template.

**Comment by jesseframework** [comment]
So i guest the answer is yes. Do yu have any documenation on where i can put some customer code? If it was android i beleave we could put custome code in the main java class. Is there a main class in the windows directore i could put code or call customer code?

**Comment by stuartmorgan** [comment]
There is not any documentation for that, no; we're not focused on documentation while the structure of the runner is still in flux.

**Comment by jesseframework** [comment]
I just want to have idea of where to start putting some customer code in Windows directory.
