### ISSUE TITLE
Feature Request:  ColoredBox or ColoredContainer

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5555]
The number of times I've typed:

```dart
new Container(decoration:new BoxDecoration(backgroundColor:new Color(0xFFFFFF00)), child:...)
```

is "Too Damn High".

I'm thinking this would be better:

```dart
new ColoredContainer(color:new Color(0xFFFFFF00), child:...)
```

**Comment by apwilson** [comment]
The fact I've memorized this magical incantation is a good indication that it would be a good widget:
"container, decoration, box decoration, background color, color, child"
"container, decoration, box decoration, background color, color, child"
"container, decoration, box decoration, background color, color, child"
"container, decoration, box decoration, background color, color, child"
"container, decoration, box decoration, background color, color, child"
"container, decoration, box decoration, background color, color, child"

**Comment by apwilson** [comment]
I'm up for other names for the class as well... ColoredBox?  Chip (as in paint chip)?

**Comment by Hixie** [comment]
We could just have Container take a color.

**Comment by apwilson** [comment]
yeah that'd work too, but it begs the question about the purpose of decoration at that point, because it could all be added to Container.  Also, you have other things like Margin and Padding that are just Containers with margin and padding applied.  It's confusing to me whether you guys want more specialized widgets or more general purpose ones.

**Comment by Hixie** [comment]
Container uses Padding to implement its 'padding' and 'margin' arguments. (There's no Margin.)
We could add more parts of BoxDecoration to Container. We'd still have the 'decoration' argument because you can give it things that aren't BoxDecorations (e.g. you can give it a FlutterLogoDecoration).

We have a layered system. You can use any layer. Container is a layer above Padding and DecoratedBox and ConstrainedBox. We have no opinion about which is best, it's up to you.

**Comment by apwilson** [comment]
Okay, well having Container take backgroundColor would be fine with me.

**Comment by eseidelGoogle** [comment]
My recommendation would be that pink should just write their own common library here. :)  But yes, we also could have some fancier helpers here.
