### ISSUE TITLE
You can hit two contradictory buttons in the same frame

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#556]
Suppose you have two buttons, and one does navigator.pop(), and the other does navigator.push().
You tap both of them simultaneously.

**Comment by Hixie** [comment]
Or suppose you tap the fab and a row in the stocks app at the same time...

**Comment by abarth** [comment]
Here's a thought about this issue:

1) In general, we want to be able to tap two different things in the same animation frame.  For example, if the buttons incremented separate counters (or even the same counter), it would be legit to tap them both at once.
2) The problem arises because the two input try to mutation shared state in the navigator.

Maybe the solution is that in order to mutation the navigator's state, you need to get a transaction object and do all your mutations inside the transaction.  The navigator could then have a rule that it allows only one transaction per animation frame.

**Comment by Hixie** [comment]
I think that would be an eminently reasonable solution to this problem.

**Comment by Hixie** [comment]
Concrete proposal: move push(), pushNamed(), and pop() on NavigatorState to a NavigatorTransaction object, then have NavigatorState have a method that returns a transaction, and have that method return null or some such if it's already had a transaction since the last time it built. Call sites for these methods now only act if the returned transaction is non-null.

**Comment by dglinyanov** [comment]
Would it be better to return Future with transaction when it is available?

**Comment by Hixie** [comment]
The goal is to prevent any navigation at all from the second tap, not to delay it. If you delay it by one frame you get basically the same effect as now.
