### ISSUE TITLE
Gallery Apk Size 46MB: Too big

### ISSUE THREAD

**Issue by tjerkw** [flutter/flutter#5567]
## Steps to Reproduce

Create the Gallery Flutter app and install it on your android.
Check out the APK size.

# Results

APK size is 46mb... When i see the .apk in the /build folder its 'only' 15mb, i assume because its zipped. Checking the contents, i see that the snapshot_aot_* files use a lot of data. And the libsky_shell.so. I assume we cant do without those. But its difficult to write a killer-app if your initial app size is already 30MB

## Expected Results

Simple apps should not be bigger than 5mb... Maybe the sky runtime can be bundled into android? 
Note: Probably this is low priority for a early-access library. But i think its important to keep an eye on. I would say 10mb is acceptable for the Gallery app.

![screen shot 2016-08-24 at 09 54 56](https://cloud.githubusercontent.com/assets/818865/17922645/5e33f6ae-69e0-11e6-8bb5-138d1b0a228b.png)

**Comment by eseidelGoogle** [comment]
If you're interested in "initial size" I recommend comparing against the built result of`flutter create` as a baseline.  We track the that size and it currently shows as 8mb compressed on our team's dashboard.  That's still too large, but we believe that to be a more accurate than the gallery (which intentionally tries to touch every aspect of the framework as a demo).

There is a ton we can do to make this smaller.  Just not been a focus yet.  See https://github.com/flutter/flutter/issues/394 and https://github.com/flutter/flutter/issues/892 for instance.  Regardless, thanks for the report.

**Comment by eseidelGoogle** [comment]
To explain some of the numbers you see (we should add something like this to the faq):

- app.flx is the resources folder for Flutter.  So the gallery contains 6.2mb of gallery-specific images compressed.
- icudtl.dat is the data file for ICU.  2mb compressed we shouldn't need at all.  See #394  for context.
- snapshot_* are the compiled parts of the dart code. Gallery (intentionally) uses more of Flutter's framework than I would expect most apps to as it intentionally tries to demo each Widget, etc.  But regardless, we have teams working on making this Dart code smaller.  FYI @a-siva @kasperl
- libsky_shell.so is the c++ parts of Flutter's runtime, see flutter/engine.  I'm a bit surprised it's 3.6mb compressed, I'm sure we can make that smaller but it's probably not the lowest hanging fruit.  FYI @jason-simmons @abarth 
- classes.dex is just part of being an Android app. :)  These should be pretty small in flutter apps comparatively since we use so little java.
- res is android-specific resources, for which the gallery has basically none.
And the rest on that list is noise.

As noted above, lots to do.  This hasn't been a focus for us yet.

**Comment by sethladd** [comment]
Thanks for the feedback @tjerkw and thanks for the in-depth explanation @eseidelGoogle !

I think we can help explain "what's inside a flutter APK?" on our website. Maybe not with specific sizes (as those will fluctuate) but we can help explain what's going on. I filed https://github.com/flutter/flutter/issues/5571 to track.

No doubt we should continue to look for ways to drive this size down, but I don't know how to take specific action on this issue. I'm tempted to close this issue in favor of specific ones, like https://github.com/flutter/flutter/issues/394. Please reopen if you feel differently.

@eseidelGoogle should we open an issue to investigate the size of skyshell?

@tjerkw as you are building out your app and find opportunities for flutter to help make the APK smaller, please let us know. No doubt our compiled code should be small, etc, but I'm wondering if most apps' APKs are filled mostly with resources like images and sounds?

**Comment by tjerkw** [comment]
@sethladd In my latest native android app the biggest part of the app is indeed the images and other illustrations. Not so much the codebase. This has changed in recent years due to bigger screens requiring better graphics. However SVG's solve a bit of that issue.

Regarding closing this issue: I totally agree. Documentation would be better in this stage.
