### ISSUE TITLE
Why build mips texture  as default ?

### ISSUE THREAD

**Issue by linxuebin1990** [flutter/flutter#55710]
I find code as follow, in `flutter/lib/ui/painting/image_decoder.cc`:
```
sk_sp<SkImage> texture_image = SkImage::MakeCrossContextFromPixmap(
                context.get(),  // context
                pixmap,         // pixmap
                true,           // buildMips,
                true            // limitToMaxTextureSize
            );
```
The code up means, flutter build mips texture as default. For example,  an image is 128 x 128, mips mode will build texures, 128x128, 64x64, 32x32, 16x16, 8x8, 4x4, 2x2, 1x1.
Mips mode will consume an additional 1/3 of the memory.
Why ?

I measure memory of image list, get a chart as follow:
 
![f04fa725-5781-4863-b317-e4273b827e90](https://user-images.githubusercontent.com/3382181/80328816-0b466200-8873-11ea-963a-394e1a4400ef.png)

**Comment by chinmaygarde** [comment]
Flutter did not initially perform mip-mapping by default. However, it was added later after it was discovered that that rendering performance was severely and adversely affected on lower end devices due to the additional texture lookups when rendering textures at non-native resolutions (which is the dominant use case in most Flutter apps). This is a known tradeoff. `ui.Image`s are meant to be performant wrappers around textures.
