### ISSUE TITLE
gallery.flutter.dev Cupertino examples do not respect dark-mode

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55931]
1.  The "system" theme does not seem to respect Dark mode if the phone is already in Dark Mode (iOS).

Note how the phone is in Dark mode (Dark top banner, etc), but the cupertino example is on a white background:

![image](https://user-images.githubusercontent.com/11857803/80558028-b8150200-898d-11ea-9202-f0ccd6d19b47.png)
(The slider shadows being wrong are filed separately, just re-using the screenshot.)

2.  Even if I manually set the "Theme" in the options to "Dark" the Cupertino examples do not change.

![image](https://user-images.githubusercontent.com/11857803/80558053-ca8f3b80-898d-11ea-92cc-fda144a317e6.png)

Maybe these are separate bugs?  Happy to split out if needed.

**Comment by willlarche** [comment]
It was on purpose. @rami-a could probably explain the reasoning (I forget)

**Comment by rami-a** [comment]
This was an intentional design choice when we worked with the designers on this initially. We wanted the demo content to stand out more against the demo chrome. Totally open to revisiting this of course.

Now that I think about this more, we probably should have the demo content respect the dark-mode setting, so that developers can see what the components look like in dark mode.

**Comment by ferhatb** [comment]
Verified both at startup and change, dark mode updates correctly on the engine side.
WAI. Closing this issue. If you decide gallery should change approach please file in flutter/gallery.
