### ISSUE TITLE
[tool_crash] Presence of windows directory causes crash for other devices

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#55958]
After using `flutter create` to get web files, I was unable to run my app on Chrome.

### Repro
1. Start with a non-windows project.
2. `flutter create .` adds windows file.
3. `flutter run` with a non-windows device (in my case, Chrome).
4. Delete windows directory*
5. Subsequent `flutter run`s with a non-windows device fail.

*To be clear, I didn't so much delete the windows directory, as I removed non-ignored files using git (Git doesn't delete directories)

- [ ] `flutter run` for a non-windows device should not fail even if there exists an incomplete windows subdirectory in the project.
- [ ] if a windows subdirectory exists but files are missing (i.e. windows/Runner.sln), show a useful error message to run `flutter create`.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=chrome lib/main.dart

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/plg/development/gallery/windows/Runner.sln' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
## flutter doctor

```
[✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Mac OS X 10.15.4 19E287, locale en-DE)
    • Flutter version 1.18.0-9.0.pre.14 at /Users/plg/development/flutter
    • Framework revision dd88b20435 (3 days ago), 2020-04-25 19:02:03 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/plg/Library/Android/sdk
    • Platform android-stable, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/plg/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
    • Pixel 3a   • 976AY0ZMV1 • android-arm64  • Android 10 (API 29)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122

• No issues found!
```

**Comment by stuartmorgan** [comment]
> `flutter run` for a non-windows device should not fail even if there exists an incomplete windows subdirectory in the project.

The stack posted here doesn't seem to have anything useful in it for some reason, but I suspect given the file involved that this was attempting to update the plugins for the project. By design, that is done for all platforms at once, not only the currently platform.

So if that's what the codepath was, I don't agree with this statement. We should toolExit rather than crash, but we shouldn't just ignore the fact that we needed to update a platform directory and couldn't.

> if a windows subdirectory exists but files are missing (i.e. windows/Runner.sln), show a useful error message to run `flutter create`.

In general, the tool treats the presence of a platform directory as an indication that you are supporting that platform. If we want to guard every use of a platform file against the possibility that someone has damaged the directory, that should be done across the board, not just for Windows. That's potentially a lot of complexity though, depending on how thorough we want to be (E.g., do we only handle the case of deleting all files, or deleting any arbitrary file? The latter has the problem that there are many files that someone could delete that would break their build, but that the tool doesn't ever use directly, such as platform source files referenced by the projects).

> To be clear, I didn't so much delete the windows directory, as I removed non-ignored files using git (Git doesn't delete directories)

We should at the very least fix the crash, but it's worth pointing out that this is not the right way to remove a platform from a project. You should delete the whole directory (either manually, or by passing the relevant flag to git).

**Comment by jonahwilliams** [comment]
Unfortunately it looks like in this case there is enough nested async/await that the actual untrimmed stack would probably be nearly 100 lines long. We should probably cut off a bit less
