### ISSUE TITLE
flutter_test_performance with_coverage_time_ms & without_change_elapsed_time_ms regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#56054]
These have been edging up, looks like a regression at this point. First clear signal at this revert: 
https://github.com/flutter/flutter/pull/55763

![Screen Shot 2020-04-30 at 9 15 01 AM](https://user-images.githubusercontent.com/1435716/80733862-214a6180-8ac3-11ea-82cd-1fb6accc1448.png)

I'm not sure which chunk of the code this benchmark tests, however.

**Comment by jonahwilliams** [comment]
One possibility is that the version calculation logic became slightly more complicated in https://github.com/flutter/flutter/commit/37ac9015ad0eb728b15503009619aa3e3d8090b1

Unfortunately all of the flutter commands are sensitive to it. We could disable the version check for this test to stabilize the numbers.

Fyi @christopherfujino 

Otherwise we should rebaseline

**Comment by christopherfujino** [comment]
Hmm, #55763 was reverted...

**Comment by christopherfujino** [comment]
It seems to me there was a regression in 
```
flutter_test_performance implementation_change_elapsed_time_ms
flutter_test_performance interface_change_elapsed_time_ms
flutter_test_performance with_coverage_time_ms
flutter_test_performance without_change_elapsed_time_ms
```

Starting at https://github.com/flutter/flutter/commit/8cbba0a5c7aaece30af0bbc1406ea2dd5280b222

![Screen Shot 2020-05-01 at 2 37 28 PM](https://user-images.githubusercontent.com/7856010/80843508-5afd9400-8bb9-11ea-899d-a2ddc14b5316.png)

(Some of these have red before 8cbba0a, but they all look to have jumped at that point)

**Comment by christopherfujino** [comment]
After discussion in engine chat, I rebased these.
