### ISSUE TITLE
[local_auth] Unable to check if iOS device supports Touch Id Or Face Id if not enrolled. 

### ISSUE THREAD

**Issue by rohitgarg4989** [flutter/flutter#56104]
I am using local_auth: 0.6.1+3 package in my application.
I didn't find any way to check whether an iOS device supports Touch Id Or Face Id if it(TouchId/FaceId) is not enrolled on the device.

If it is enrolled I am able to get the supported biometric type using the getAvailableBiometrics() method. But if the user has not enrolled yet, then the same method getAvailableBiometrics() returning the list as [null]. So there is no way to detect which type of biometric my device supports Touch id or Face Id.

Is there any way in local_auth or some other package to check the supported biometric type for a device, if the user has not enrolled yet?

**Comment by hawkinsjb1** [comment]
On iOS, there is no clear way to determine
1. has the user been prompted for biometrics
2. is the user enrolled (without relying on PlatformExceptions)

When I use the iOS simulator, and DO NOT check "enrolled", canCheckBiometrics still returns TRUE, so then if I call "authenticateWithBiometrics" it doesn't throw an error but instead shows 

"Biometric authentication is not set up on your device. Please either.."

Shouldn't this mean canCheckBiometrics returns false? Then after closing the dialog, still no error is thrown so programmatically I cannot know if they simply failed the check, or didn't receive a check at all

I need to use biometrics in conjunction with custom PIN feature (if user doesn't want to use biometrics) and there is no way to implement such functionality because I cannot directly get any of the info I need, and what info I can actually get requires me to force a prompt + PlatformException.

**Comment by pedromassangocode** [comment]
Hi @rohitgarg4989 does the [getAvailableBiometrics()](https://pub.dev/documentation/local_auth/latest/local_auth/LocalAuthentication/getAvailableBiometrics.html) works for your use-case?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
