### ISSUE TITLE
Support for larger DartPad API Doc examples

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#56163]
An API example that's longer than 10 or 20 lines can be a little unwieldy to maintain as part of a DartDoc comment. On the other hand, interactive DartPad examples that do a more than demonstrate instantiating a class or calling a method, like this one https://master-api.flutter.dev/flutter/animation/Curve2D-class.html, are pretty compelling.

It would be helpful if larger examples could be included by reference. We'd need a way to refer to a file/directory in a stable repo. Maybe somewhere in the samples repo?

```
/// {@tool dartpad <new source option here>}
/// {@end-tool}
```

This approach might also simplify analyzing and testing example code; at least the kind of example code that's a functional small app rather than a code fragment.

**Comment by HansMuller** [comment]
CC @gspencergoog @JoseAlba @johnsonmh @willlarche

**Comment by gspencergoog** [comment]
cc @devoncarew, for the impact on the IDE support for examples.

I think this is a good idea, but I want to make sure that this is used only for large examples. One of the goals of the dartdoc examples is to make it so that if you are perusing the code, you get the same information as if you were perusing the docs website. If we could, I'd put a webview with the docs inline in the IDE, Dartpad and all (but we can't).

For large examples, this breaks down, since then you're paging past pages and pages of comments when you're looking for actual code, so this seems like a good idea. I think the examples should be part of the Flutter tree itself, since it's important to make sure that the examples and the code are in sync with each other, or they might not compile when the user goes to run them.

**Comment by gspencergoog** [comment]
Also, it's nice to have the example code right there next to the code you're changing: makes it easier to remember to update it.

**Comment by goderbauer** [comment]
Now that samples live in their own independent file, this problem should no longer exist.
