### ISSUE TITLE
frontend_server isn't configured to allow disabling --track-widget-creation for dartdevc target

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#56212]
Even though the flags seem to be piped through normally, passing --no-track-widget-creation still results in Location objects being added to the generated JavaScript. part of the issue was the flutter tool passing `--track-widget-creation=true` unconditionally for web. Even fixing this, the issue persists.

**Comment by 2ZeroSix** [comment]
caused by #52497

It seems that there is no way to determine if options was changed since last run in `frontend_server`, so the file provided via `--initialize-from-dill` is used unconditionally, so the only way to change options is to run `flutter clean` or remove `build/cache.dill`

Other targets use some caching layers based on options changes and `assemble` calls. For example on android `:app:compileFlutterBuildDebug` is skipped, on other targets where assemble is called `kernel_snapshot` command is skipped on subsequent runs with the same options

**Comment by jonahwilliams** [comment]
The frontend server needs to correctly invalidate the full based on changes to the compiler flags. If this can be fixed by cleaning, then a short term fix would be to use two fill files.

**Comment by jonahwilliams** [comment]
That is, we check the current compilation mode and save to `track.cache.dill` or `cache.dill`

**Comment by 2ZeroSix** [comment]
Probably the proper fix would be to add `trackWidgetCreation` in `_ComponentIndex` so it might be handled the same way as `NonNullableByDefaultCompiledMode` here https://github.com/dart-lang/sdk/commit/a85a7fc254e541a3808fa9c7465311ae035af32a#diff-e6f9e6c828708c5cf1237b2a2f44da08

Anyway I created PR with workaround used for other builds.
