### ISSUE TITLE
Stream low frame rate behind reverse proxy

### ISSUE THREAD

**Issue by dubbelpunt** [flutter/flutter#56256]
Hi,

I'm using https://pub.dev/packages/flutter_mjpeg in flutter to stream ip camera's. I noticed when I put the stream behind a reverse proxy from Nginx, the frame rate is very low. I have only 1 frame after x seconds. Direct url of the cgi-stream, works perfect. Opening the reverse proxy url from the browser also works perfect.

Example:
http://ip_ipcam/videostream.cgi ==> works perfect with Mjpeg() via flutter.

reverse proxy rpserver conf:
Location /ipcam1 {
    proxy_pass http://ip_ipcam/videostream.cgi
}

http://rpserver/ipcam1 ==> very low framerate with Mjpeg() via flutter. In the browser, this works perfect.

I have reported this issue in dart: https://github.com/dart-lang/language/issues/950. They sent me here.

**Comment by iapicca** [comment]
Hi @dubbelpunt 
the issue you are describing seems to be related to
the 3rd party plugin [flutter_mjpeg](https://pub.dev/packages/flutter_mjpeg) and your backend implementation
rather than with flutter's framework itself
you may want to open an issue in that plugin's [github](https://github.com/mylisabox/flutter_mjpeg/issues) or
 see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
