### ISSUE TITLE
Can't build a release version of my project because assembleAarRelease not found in root project 'geolocator'

### ISSUE THREAD

**Issue by Sakorni** [flutter/flutter#56252]
I'm trying to build an apk of my project and it crashes with exception:
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'geolocator'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```
Is there an any way to solve this problem?

**Comment by iapicca** [comment]
Hi @Sakorni 
if you believe the error is cause by the 3rd party plugin [geolocator](https://pub.dev/packages/geolocator) you may want to open an issue in the dedicated [github](https://github.com/Baseflow/flutter-geolocator/issues);

otherwise please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Sakorni** [comment]
Well, i just started new project and copied libsfrom original project, and also pubspec.yaml's packages.
Looks like i've fucd up my .xml in original project
