### ISSUE TITLE
`flutter run` should fail better if project files are missing

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#56315]
Steps to reproduce:
1. Create a directory with a legitimate `pubspec.yaml` file and with a `lib/main.dart` file.
2. From that directory, do `flutter run`.

Result:
```
No supported devices connected.
```

I do have connected devices, so this message is wrong and is rather confusing.

We used to give a better error message explaining to run `flutter create .` (see https://github.com/flutter/flutter/issues/27417).  Somehow this regressed in https://github.com/flutter/flutter/pull/33867.

**Comment by jmagman** [comment]
What does `flutter devices` say?

**Comment by jamesderlin** [comment]
`flutter devices` says:

```
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27)
(emulator)
```

The message is completely bogus.

**Comment by jmagman** [comment]
1. The tool definitely shouldn't crash like #27417 when platform directories are missing, and if it does, that's a bug that needs to be fixed.
2. 
> We used to give a better error message explaining to run `flutter create .`

Are you referring to #27417:
```
No application found for TargetPlatform.android_x86.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```
That scenario was detecting that a required Android file was missing when running against an Android device.  I see a similar message for when the Info.plist is missing when an iOS device is targeted.  In both cases would be an `android` or `ios` platform directory.

3.  From https://github.com/flutter/flutter/pull/56531
> If we can't fix the existing code meant to cover this case, is it dead code that can be removed?

I don't see previous behavior where an entire platform directory was missing and `flutter` recommended you run `flutter create .`.  The messages from point 2 were only triggered when the platform directory is present, and was `flutter run` against a supported device.  I don't think there is a regression here.

4. From https://github.com/flutter/flutter/pull/56531
> Why is this tied to connected devices?  I'm guessing that we depend on connected devices to determine which project directories to look for?  How about instead checking for project directories for all supported platforms and emitting a message about `flutter create .` if none of them exists?

The presence of the platform directory is what tells the tool what platforms are supported and therefore what available devices are supported, not the other way around. 
https://github.com/flutter/flutter/blob/c2b7342ca470b11cfaad4fbfb094f73aa4c85320/packages/flutter_tools/lib/src/linux/linux_device.dart#L35-L37
So if there's a web directory, Chrome is a supported device.  However if the `web` directory is missing and the `android` directory is present but they have no Android devices plugged in, the error state is that they have no supported devices plugged in, not really that they need to generate a `web` directory because they have Chrome installed.  I think most users would find that confusing.

**Comment by jamesderlin** [comment]
> 1. The tool definitely shouldn't crash like #27417 when platform directories are missing, and if it does, that's a bug that needs to be fixed.

Yeah, that crash is old and is no longer occurring.

> I don't see previous behavior where an entire platform directory was missing and `flutter` recommended you run `flutter create .`. The messages from point 2 were only triggered when the platform directory is present, and was `flutter run` against a supported device. I don't think there is a regression here.

No, there is definitely a regression.  My complaint from #27417 was about when the entire iOS directory was missing.  As mentioned, before #33867 (0d9a1b201), there was a message about running `flutter create .` if the Android or iOS directories were missing.

Before:

```shell
~/.../dart/flutter/bare $ ls
lib/  pubspec.lock  pubspec.yaml

~/.../dart/flutter/bare $ flutter run
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
AndroidManifest.xml could not be found.
Please check
/home/jamesdlin/Desktop/dart/flutter/bare/android/AndroidManifest.xml for
errors.
No application found for TargetPlatform.android_x86.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

After:
```shell
~/.../dart/flutter/bare $ flutter run
No supported devices connected.
```

> The presence of the platform directory is what tells the tool what platforms are supported and therefore what available devices are supported, not the other way around.

Then it seems like we can print a better message if no platform directories are present.

**Comment by jamesderlin** [comment]
To give some context: the reason why I care about this is because we publish packages that sometimes include runnable examples (e.g. https://github.com/google/flutter.widgets/tree/master/packages/visibility_detector/example ), but we don't bother checking in the files generated by `flutter create` and keeping them updated.  We do have documentation that explains to run `flutter create .` first, but there used to be better error messages too, and the current "No supported devices connected." message is really confusing.

**Comment by jonahwilliams** [comment]
I re-labelling this to quality from regression, because while I believe it is something we can do better with, it doesn't represent a substantial regression in common user workflows

**Comment by darshankawar** [comment]
@jamesderlin 
Followed your steps to replicate this issue and `flutter run` shows below message:

```
No supported devices connected.
The following devices were found, but are not supported by this project:
iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
• com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
macOS (desktop)            • macos                                • darwin-x64
• Mac OS X 10.15.4 19E2269 darwin-x64
Chrome (web)               • chrome                               •
web-javascript • Google Chrome 89.0.4389.114
If you would like your app to run on ios or macos or web, consider running
`flutter create .` to generate projects for these platforms.
```

It indicates the list of devices aren't supported and also says to run `flutter create  .` to generate projects for said platforms.

Do you think this message is satisfying and addresses your original issue ?
