### ISSUE TITLE
form field validator: allow async function

### ISSUE THREAD

**Issue by gustavomassa** [flutter/flutter#56414]
## Use case

Using a TextFormField inside a form with a validation function.
Example: TextFormField for an email address.
```
  String validateEmail(String value) {
    Pattern pattern =
        r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$';
    RegExp regex = new RegExp(pattern);
    if (!regex.hasMatch(value))
      return 'Enter a Valid Email';
    else
      return null;
  }
```
But also I need to check if the email is not already registered on the database, but the database function that queries the email is async. 
```
  Future<String> validateEmail(String value) async {
    Pattern pattern =
        r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$';
    RegExp regex = new RegExp(pattern);
    if (!regex.hasMatch(value)) return 'Enter Valid Email';

    bool isAvailable =
        await DataService.isEmailAvailable(value);
      if(isAvailable == false) return 'Email already in use';

    return null;
  }
```
I could put the dup email validation logic on the submit/save function, but it would be a much better experience for the user to be able to see the error for the specific input.

## Proposal
Change the FormFieldValidator<T> type to async, also implement the logic to await the function return
```
/// Signature for validating a form field.
///
/// Returns an error string to display if the input is invalid, or null
/// otherwise.
///
/// Used by [FormField.validator].
typedef FormFieldValidator<T> = String Function(T value);
typedef FormFieldValidatorAsync<T> = Future<String> Function(T value);
```

**Comment by justinmc** [comment]
Here's a dartpad showing how to handle this currently: https://dartpad.dartlang.org/4608e62118b2f16bac3679873ccfef96

My instinct is to say that `validator` shouldn't be async because a form field should always have a valid or invalid state.  If it were async, we'd have to make some assumptions that all developers might not agree with, like how to handle [isValid](https://github.com/flutter/flutter/blob/9bfe50cb8191c71a9378d0b07020209bea7d34fd/packages/flutter/lib/src/widgets/form.dart#L360), and whether to hide or show the error while waiting.

I think I favor keeping FormField simple and unopinionated and allowing developers to build their own abstractions on top of it.  Using an approach similar to what's in my dartpad above, you could create an AsyncTextFormField that wraps TextFormField and has the functionality you want.

I'm definitely interested in what people think, though.

**Comment by pedromassangocode** [comment]
Hi @gustavomassa 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/9688).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
