### ISSUE TITLE
Would like a way to opt-into in-progress features

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5642]
This came out of conversation with @abarth yesterday.   Some customers (including the Gallery) will want to disable in-progress features (like the back-gesture which just landed last week).  Having a way to do so would be nice.

Ideally it would be possible to run the gallery with in-progress features, compile-time or runtime or however.

I would recommend that this choice not be just specific to the gallery since other apps are going to want this.  Another alternative would be that we use branches for feature development, but personally I've had less success with that in the past.  Up to you all.

Thoughts @Hixie @HansMuller @mpcomplete?

**Comment by Hixie** [comment]
I would argue that we shouldn't ship in-progress features. The existence of an in-progress feature should be a stop-ship bug for releasing to the alpha branch. This means it's fine to check in in-progress features that you're actively working on and expect to have done soon, but it's not ok to check it half-done work then not fix it. If we get to the point of wanting to ship and we still have in-progress work, we should remove it, because otherwise we are taking on technical debt.

**Comment by sethladd** [comment]
> releasing to the alpha branch.

We have no process for the alpha branch :) Let's chat about this in person.

**Comment by mpcomplete** [comment]
I think we should stick to something simple for now. The back gesture should just be disabled (hard-coded) until it's ready. I don't see a need for customers to be able to pick and choose which "alpha" features they want.

That said, I think there's value in keeping in-progress features checked into trunk, even in a disabled state.

**Comment by Hixie** [comment]
Disabled features will bit-rot and just cause us pain down the road.

**Comment by Hixie** [comment]
@sethladd The alpha release process is https://github.com/flutter/flutter/wiki/Release-process

**Comment by sethladd** [comment]
Great! We might want to add "everything is green on our dashboard buildbots".

**Comment by eseidelGoogle** [comment]
This hasn't come up since.  Closing for now.
