### ISSUE TITLE
[web] should use the version settled in pubspec.yaml

### ISSUE THREAD

**Issue by niklasbartsch** [flutter/flutter#56532]
As I am building more and more flutter web apps, I ran into the same problem.

When I deploy my app with Firebase Hosting, the customer doesn't see the newest version. He has to delete his cache first. 

> The solution to a problem lies in the problem itself.

The web browser doesn't detect, that there is a new version online. 

Quick Google search and you find the following:

[Caching in Flutter for Web](https://medium.com/flutter-community/caching-in-flutter-for-web-42b3ae0e348f)
Thank you [Constantin Stan](https://medium.com/@constanting)

We only have to add a version in our **index.html**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>to_cache_or_not_to_cache</title>
  </head>
  <body>
    <script src="main.dart.js?version=1" type="application/javascript"></script>
  </body>
</html>
```

I would like Flutter to be able to do it by itself with the version settled in the `pubspec.yaml`

**Comment by jonahwilliams** [comment]
The web browser does detect that there is a new version, but the new service worker needs to activate and install first.

> the customer doesn't see the newest version. He has to delete his cache first.

I don't have enough information to diagnose any issue here. Simply refreshing the page likely isn't sufficient. This also could have been an issue with a service configuration that we cannot diagnose either.

For more information see: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

If you don't want this behavior you can remove the service worker from your index.html

**Comment by sma** [comment]
The problem is – if I may answer the question for my colleague – that running `firebase deploy` (which does a fresh `flutter build web`) deploys something that isn't picked up immediately when accessing the website. This caused confusion because the customer didn't see the new (and improved) version of the app and became unhappy.

This is probably because the integrated service worker still has all assets cached. Removing the service worker from `index.html` is an obvious work around, but because that worker is added by default now, it would be nice if the app would also immediately update itself by default and only cache assets which haven't been changed.

Forcing such an update, as I understand, can be caused by added some unique information to either `index.html` or `flutter_service_worker.js` file. This could be the version number + build number from the `pubspec.yaml`.

Adding that version would have the additional benefit of knowing the version of the deployed app by simply looking at the source code in the browser … something you could ask a customer to do.

Hope that helps.

**Comment by jonahwilliams** [comment]
The service worker already contains such information - if you've changed any dart code, dependencies, assets et cetera, but service worker activation is asynchronous and refresh is often not sufficient.

**Comment by azbuky** [comment]
I was facing a similar problem with Firebase Hosting. Turns out that after a deployment with firebase deploy, when the new service worker is activated, the fetch requests for the resources, done by cache.addAll(), go through the regular browser HTTP cache.

The fix I found was to disable caching for all files in the project by adding a 'headers' entry in firebase.json
```
{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
      {
        "source": "**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      }
    ]
  }
}
```
You still have to activate the new service worker so a simple refresh of the page is probably not enough, you have to close the current tab and open a new one.

**Comment by jonahwilliams** [comment]
Interesting! I wonder if there is a way we can fix that or make it more obvious from the service worker controls. Thanks for bring this up @azbuky

**Comment by jonahwilliams** [comment]
An obvious solution might be to try a url-param with the content sha

**Comment by jonahwilliams** [comment]
The service worker will now always cache files by sending requests with `no-cache` headers

**Comment by sgehrman** [comment]
I'm having this problem.  I'm on the latest beta.  I saw that a merge claimed to fix this. Is it fixed?

[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
[✓] Connected device (3 available)
