### ISSUE TITLE
Pod install not fired after clean and remove package

### ISSUE THREAD

**Issue by stefandevo** [flutter/flutter#56558]
When you add a package (f.e. flutter_email_sender https://pub.dev/packages/flutter_email_sender) and run, pod install is fired.

When you remove the package from the pubspec file, Flutter Clean, Build, pod install is not fired, leaving the project with errors upon build. Reference in the project.pbxproj are still there. A manual pod install in the ios folder fixes the problem.

Reference:
https://github.com/sidlatau/flutter_email_sender/issues/45

**Comment by iapicca** [comment]
Hi @stefandevo 
are you experiencing the issue only with said plugin?
If so you may want to open an issue in the dedicated [github](https://github.com/sidlatau/flutter_email_sender/issues)
otherwise
could you please provide your `flutter doctor -v`,
confirm and reproduce the steps you provided
- add plugin to `pubspec.yaml`
- run `flutter build ios`
- remove the plugin from `pubspec.yaml`
- run `flutter clean`
and lastly provide you `flutter build ios --verbose`
Thank you

**Comment by stefandevo** [comment]
Hi, I tried it with some other plugins that uses pods inside of the ios project, and these are removed without any problems. So it seems a specific issue with the package.
There is already an issue created for the package.
