### ISSUE TITLE
Update 1.17 breaks FocusScope.of(context).unfocus();  

### ISSUE THREAD

**Issue by n00bm0nkey** [flutter/flutter#56560]
Had a working GestureDetector, upgraded to Flutter 1.17 and it stopped working! 

```
Widget build(BuildContext context) {
      return GestureDetector(
        onTap: () {//fixes keyboard not closing
          FocusScopeNode currentFocus = FocusScope.of(context);
          if (!currentFocus.hasPrimaryFocus) {
            currentFocus.unfocus();
          }
        },
      child: MaterialApp(...),
   );
}
```

**Comment by HansMuller** [comment]
CC @gspencergoog - is this a regression?

**Comment by gspencergoog** [comment]
Perhaps, but I need to understand what the goal of the code above is.  It looks like this code was relying on the behavior that unfocusing a scope node which had focus would transfer focus to the root focus node, which was incorrect behavior, since it broke focus traversal whenever it happened.

If that's the case, then a fix here would be to call `FocusManager.instance.rootScope.requestFocus()` instead of `currentFocus.unfocus()`.

However, I question that this code does what you actually want. I'm guessing that you have had to also put in places where you explicitly focus things that happen after a tap on the application in order for focus traversal to work properly, since once the root scope node gets focus, focus traversal has no context in which to evaluate which node should come next (since there isn't any `FocusTraversalPolicy` to look for above the root node).

The unfocus code was changed in https://github.com/flutter/flutter/pull/50831 to take a disposition (where to place the focus when the node loses focus).  You might also try `currentFocus.unfocus(disposition: UnfocusDisposition.previouslyFocusedChild)` and see if that helps, since that's closer to the original algorithm.

**Comment by n00bm0nkey** [comment]
@gspencergoog Resolved with #50831. 
"If you want to remove the focus from the primary focus instead of the scope, that's easy enough to do: just call primaryFocus.unfocus()." 

The provided code was supposed to remove primaryFocus from a child widget in the context. This issue was simply a lack of my understanding of the focus() function. My apologies and thanks for the hasty reply!

**Comment by oemdaro** [comment]
I have the same issue. My goal is to unfocus when user tap anywhere on the screen. 

I resolve the issue by change it to:

```dart
Widget build(BuildContext context) {
  return GestureDetector(
    onTap: () {
      FocusScopeNode currentFocus = FocusScope.of(context);
      if (currentFocus.canRequestFocus) {
        FocusScope.of(context).requestFocus(new FocusNode());
      }
    },
    child: MaterialApp(...),
  );
}
```
I'm not sure, if I use the right way. But it solve my problem. Lets me know, if I'm using the wrong way.

**Comment by gspencergoog** [comment]
@oemdaro I think, with the code you have now, if you tap on the screen and then hit TAB, then it won't move to the correct next node. You could accomplish the same thing with:

```dart
onTap: () {
 FocusManager.instance.primaryFocus.unfocus();
}
```

and it would move to the correct next node when you hit TAB.

You definitely don't need to check to see if it can request focus: the `requestFocus` function already does that internally.

**Comment by oemdaro** [comment]
> @oemdaro I think, with the code you have now, if you tap on the screen and then hit TAB, then it won't move to the correct next node. You could accomplish the same thing with:
> 
> ```dart
> onTap: () {
>  FocusManager.instance.primaryFocus.unfocus();
> }
> ```
> 
> and it would move to the correct next node when you hit TAB.
> 
> You definitely don't need to check to see if it can request focus: the `requestFocus` function already does that internally.

Thank @gspencergoog , It's working.

**Comment by jesswin** [comment]
> @oemdaro I think, with the code you have now, if you tap on the screen and then hit TAB, then it won't move to the correct next node. You could accomplish the same thing with:
> 
> ```dart
> onTap: () {
>  FocusManager.instance.primaryFocus.unfocus();
> }
> ```
> 
> and it would move to the correct next node when you hit TAB.
> 
> You definitely don't need to check to see if it can request focus: the `requestFocus` function already does that internally.

Thank You Sir, was working with the Focus.of(context) and that was giving me errors...after spending hours on it, I found this Solution to unfocus() without context!
