### ISSUE TITLE
"Stocks" example app - low FPS

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#5658]
This issue is a follow-up to a Twitter conversation with @sethladd: https://twitter.com/sethladd/status/770645155657363456

## Steps to Reproduce

* check out  https://github.com/flutter/flutter/commit/22fe5db91aed57f192d039b32a1341e0e0aa1180
* `cd flutter/examples/stocks`
* `flutter run`

I made two videos showing the occasionally low frame rate:

https://www.youtube.com/watch?v=3fKLCabNfQs
https://www.youtube.com/watch?v=5j9Q5qGbyd4

The videos were made on my LG G2 running Android 4.4.2.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/dmta/flutter/flutter
    • Framework revision f6353b686d (17 minutes ago), 2016-08-30 08:51:28
    • Engine revision c4022b61fa
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /home/dmta/development/android-sdk-linux
    • Platform android-24, build-tools 24.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[x] Atom - a lightweight development environment for Flutter
    • flutter plugin not installed; this adds Flutter specific functionality to Atom.
      Install the plugin from Atom or run 'apm install flutter'.
    • dartlang plugin version 0.4.14
```

**Comment by chinmaygarde** [comment]
@DavidMihola Both screen captures are of the application running in checked mode (the "slow" banner on top). Are you still seeing dropped frames in `--profile` or `--release`?

**Comment by DavidMihola** [comment]
@chinmaygarde Oh, I am so sorry - to be honest, I was wondering a bit about the "slow" banner... should have done more research about the various run modes.

In any case, the scrolling is much better when I use `flutter run --release`, as well as the opening and closing of the hamburger menu - both are now as fluent as a normal `RecyclerView` or `NavigationDrawer`. The transition from the list to a `StockSymbolPage` still hangs a bit at the start:

https://youtu.be/8oHPnSAXQFs

**Comment by brianegan** [comment]
Hey, just as a follow-up: I've actually noticed that Flutter is pretty slow on my Nexus 5 as well.

https://youtu.be/zunJ6_eU_Lc

This video doesn't do the best job of showing it, but if you compile the Stocks or Gallery app in release mode on a Nexus 5, performance is clearly not as smooth as a native app.

**Comment by sethladd** [comment]
Thanks for the video! We still have perf optimization work to do, and we're looking at various options. Many of our demo screens are at-or-near 60fps, but some transitions need more investigation.

It's most useful for us to open individual issues for specific transitions/animations. That way, we can add Trace data and dive in. Please feel free to open specific issues for specific cases.

Since this original issue was highlighting perf in slow mode, I'm going to close this issue. If you're curious about existing performance issues, please check out https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22%E2%9A%A0+astounding+performance%22

We really appreciate the feedback. Please keep it coming!
