### ISSUE TITLE
DropdownButtonFormField does not render InputDecoration correctly

### ISSUE THREAD

**Issue by Tbhesswebber** [flutter/flutter#56601]
## Steps to Reproduce

1. Create a `DropdownButtonFormField`
2. Supply the required arguments using `DropdownMenuItem(child: Text('Some Text), value: 'Some Text')`
3. Add the line: `decoration: InputDecoration(labelText: 'Theme'),` to the arguments list.

**Expected results:** 

A label that appears in a reasonable location in relation to the `DropDownButton`.

**Actual results:** 

![image](https://user-images.githubusercontent.com/28069638/81347165-9997c080-9089-11ea-8c24-b7b19d7871f5.png)

**Comment by Tbhesswebber** [comment]
I resolved this on my own, it appears that the argument `value` should also be required and I went down a debugging rabbit hole prematurely.  Is this something that should be fixed or is it "as intended"?

**Comment by VladyslavBondarenko** [comment]
Reproducible code sample

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  String value;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: DropdownButtonFormField(
            decoration: InputDecoration(labelText: 'Theme'),
            onChanged: (newValue) {
              setState(() {
                value = newValue;
              });
            },
            value: value,
            items: [
              DropdownMenuItem(
                child: Text('Dark'),
//                value: 'Dark',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by shihaohong** [comment]
I was thinking about this a little bit and my first instinct was that we can add an assert at the constructor to ensure that `DropdownMenuItem` could never be `null`. However, I realized this would technically be breaking because users might use `null` as an actual value to display a particular `DropdownMenuItem`. For example:

```dart
DropdownButtonFormField(
  decoration: InputDecoration(labelText: 'Theme'),
  onChanged: (newValue) {
    setState(() {
      value = newValue;
    });
  },
  value: value,
  items: [
    DropdownMenuItem(
      child: Text('Dark'),
      value: 'Dark',
    ),
    DropdownMenuItem(
      child: Text('This value is null'),
      value: null,
    ),
    DropdownMenuItem(
      child: Text('Light'),
      value: 'Light',
    ),
  ],
);
```

I'm not sure if the breaking change is worth making since there are ways to prevent this from happening, and adding the assert has the potential to break an unknown number of users, but on the flip side of things, helps prevent running into this kind of problem in the first place.

**Comment by shihaohong** [comment]
One approach we could attempt to make is to have the InputDecorator acknowledge that there is a `null` value menu item and properly show the input decorator if a dropdown item with a null value is present.

**Comment by pedromassango** [comment]
Is this really worth to have? Allowing null values and expect values like this?

I mean it is very hard to see usage with null values. But we never know

**Comment by shihaohong** [comment]
Since both changes necessitate a breaking change (although one more breaking than the other), you could argue that we should just not allow a null value for `DropdownMenuItem`, but like you said, it's unknown how many developers actually use this pattern.

I think it's valid to go for the bigger breaking change as long as there's a migration path. For example, the migration guide would need to outline how a user would want to set value to `null` by tapping a `DropdownMenuItem` if we were to not allow a null `value` for `DropdownMenuItem`. If that's not possible, there needs to be a compelling argument for not allowing this behavior (which can be made in the design document that needs to be written as part of the breaking change steps). 

From what I can tell from the way `DropdownMenuItem` is written, not allowing a null value might be a breaking change that cannot be worked around, so I'm concerned about the feasibility of not allowing `null` values.

**Comment by shihaohong** [comment]
I guess one way devs can create a workaround is:
```dart
DropdownButtonFormField(
  decoration: InputDecoration(labelText: 'Theme'),
  onChanged: (newValue) {
    setState(() {
      if (newValue == 'placeholder value') {
        value = null;
        return;
      }
      value = newValue;
    });
  },
  value: value,
  items: [
    DropdownMenuItem(
      child: Text('Dark'),
      value: 'Dark',
    ),
    DropdownMenuItem(
      child: Text('Set DropdownButton to null to show hint.'),
      value: 'placeholder value',
    ),
    DropdownMenuItem(
      child: Text('Light'),
      value: 'Light',
    ),
  ],
);
```

I think the primary situation would be that developers might want to set value to `null` in order to display the hint. Special logic can be incorporated into the `onChanged` callback to set that value to null with a unique value in `DropdownMenuItem.value`.

**Comment by pedromassango** [comment]
> I think the primary situation would be that developers might want to set value to `null` in order to display the hint.

Are you talking about `DropdownMenuItem` or `DropdownButtonFormField`?

**Comment by shihaohong** [comment]
`DropdownButtonFormField`, but by using the `null` value passed into `DropdownMenuItem`. I'm trying to help come up with use cases for which a developer might want to pass `null` into `DropdownMenuItem.value`, and that's the biggest one I can think of.

**Comment by pedromassango** [comment]
You're right, thins can happen too. If the problem is with show/hide hint, we can add a param to decide wheter to show hide the hint.

Just thinking in possible ways to fix this

**Comment by pedromassangocode** [comment]
Reproducible on latest `master` channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (6 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by glennarixxi** [comment]
We also ran into this - in our case, its not that we want a null item in the item list, its that we set the original value to null because we don't want the list to be preset until the user selects a list item. The expected behavior is that it shows the hint and the user then selects an item from the list. Setting it to the first one in the list, makes it too easy for a user to simply bypass the entry even if it is required, because the first one is wrongly selected.

**Comment by TahaTesser** [comment]
Hi everyone

This seems to be working fine now, here I created an example based on https://github.com/flutter/flutter/issues/56601#issuecomment-628156659, where null value was provided.

I don't see layout issues even after using the value in the menu item.



<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

const List<String> fruits = ["Mango", "Apple", "Banana", "Strawberry"];

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String? _dropdownbuttonFormValue;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: Center(
        child: DropdownButtonFormField<String>(
          decoration: const InputDecoration(labelText: 'Theme'),
          onChanged: (newValue) {
            setState(() {
              _dropdownbuttonFormValue = newValue;
            });
          },
          value: _dropdownbuttonFormValue,
          items: const <DropdownMenuItem<String>>[
            DropdownMenuItem(
              child: Text('Dark'),
              value: 'Dark',
            ),
            DropdownMenuItem(
              child: Text('Set DropdownButton to null to show hint.'),
              value: null,
            ),
            DropdownMenuItem(
              child: Text('Light'),
              value: 'Light',
            ),
          ],
        ),
      ),
    );
  }
}

``` 
	
</details>

If the problem persists, please comment below, thanks
