### ISSUE TITLE
[BUG?] The flutter.framework is too big

### ISSUE THREAD

**Issue by duomoteng** [flutter/flutter#56697]
Hi, I am currently in 1.17, I use the command
` flutter build ios --split-debug-info && tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa` to measure the size.
The result is 
`Built /Users/xxxx/AndroidStudioProjects/xxxxx/build/ios/iphoneos/Runner.app.
-rw-r--r--  1 xxxx  staff   177M May  9 00:34 build/app.ipa`

However, the result is very large! 

<img width="758" alt="Screen Shot 2020-05-09 at 1 38 49 am" src="https://user-images.githubusercontent.com/48649432/81432890-45c6cd80-9196-11ea-88b9-2d678f606c8f.png">

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-AU)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

**Comment by timsneath** [comment]
Measuring size in iOS is hard, because the produced asset itself isn't representative of the final in-store download. 

More information on this is here: 
https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine

**Comment by duomoteng** [comment]
Can I conclude that the reason why it is so big is because of the bitcode. The release  will be smaller.

**Comment by timsneath** [comment]
I can't speak to your application, since I don't know what it contains. What you upload to the store is much larger than what you download. It's a "fat binary" that contains versions for a variety of processor architectures. Apple does a lot of server-side optimization on their side to produce packages optimized for each device (also including removing Swift libraries on devices with a recent iOS version). 

As an example, I've just uploaded a small app to the store, and the sizes are as follows:
![image](https://user-images.githubusercontent.com/2319867/81488680-d649f000-9220-11ea-854b-ff5879ad3616.png)

**Comment by FZiOS** [comment]
What's the reason of the problem?I have this problem, too.

**Comment by duomoteng** [comment]
Hi, @FZiOS  
This is not a problem. The size of the `ipa` file is not the actual size. After uploading it to the App Store, the size of my App is much smaller (about 30mb, but different from devices).
