### ISSUE TITLE
Flutter API reference should be less mobile-focused

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#56726]
The current site has the old strapline. We should tidy this up to include mention of desktop and web.

**Comment by jeffque** [comment]
I find it interesting to say that this issue is in a very close context of updating docs PR #42873, from 2019-oct (same author @timsneath).

So, as this is the second time about similar issue in "readme"s documents, I've browsed a little and found this one with what I think is the same problem:

- [packages/flutter](https://github.com/flutter/flutter/tree/master/packages/flutter/README.md)

as this readme focus only on mobile, even citing "on Android and iOS" that was removed from both PRs #42873 and #56727
