### ISSUE TITLE
How to improve PageSpeed Insights score for a flutter web app?

### ISSUE THREAD

**Issue by sjsam** [flutter/flutter#56759]
Appreciate the great work folks. 
Can somebody in the flutter team write an _official_ document on how to get an excellent Pagespeed Insights score for a flutter web app?
At present, I am not sure where to start but I feel that few issues need to be addressed.

![Screen Shot 2020-05-09 at 2 14 56 PM](https://user-images.githubusercontent.com/5788077/81468910-e56c7600-91ff-11ea-9c31-dc3f2d579a02.png)

I have **mod_pagespeed** enabled in my apache server with the default configuration but not sure how to fine tune the flutter web for use with that module.

**Comment by timsneath** [comment]
Thanks for the compliments! Yeah, we have more work to do on our side to improve initial load time. In the meantime, a document is probably unlikely to be helpful, since it will be quickly obsoleted. 

However, it's worth noting that Flutter's web support is intended more for apps than content sites. Our perf work at the moment is weighted a little more to performance after load, rather than initial startup time, since the kind of use case we have in mind for Flutter web is an app like Gmail where people will load it once and then spend time using it. 

Stay tuned -- our web support is still beta-quality, and our primary focus is driving performance and compatibility improvements right now. 

Thank you for your support and using Flutter.

**Comment by sjsam** [comment]
> since the kind of use case we have in mind for Flutter web is an app like Gmail where people will load it once and then spend time using it.
@timsneath  I see the point there. I should admit that the loading times are at the greener end though above that 80 mark. So not a big concern at the moment now.  

Hoping for the first stable version to take it for a spin. Take care.
