### ISSUE TITLE
[desktop]: 取消desktop自带的关闭、最小化、最大化，怎么取消或者隐藏？

### ISSUE THREAD

**Issue by Dan-ni** [flutter/flutter#56771]
Describe your issue and include the command you're running, flutter_desktop version, browser version

**Comment by timsneath** [comment]
Google translate: https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%5Bdesktop%5D%3A%20%E5%8F%96%E6%B6%88desktop%E8%87%AA%E5%B8%A6%E7%9A%84%E5%85%B3%E9%97%AD%E3%80%81%E6%9C%80%E5%B0%8F%E5%8C%96%E3%80%81%E6%9C%80%E5%A4%A7%E5%8C%96%EF%BC%8C%E6%80%8E%E4%B9%88%E5%8F%96%E6%B6%88%E6%88%96%E8%80%85%E9%9A%90%E8%97%8F

We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
