### ISSUE TITLE
Windows: flutter upgrade: now flutter 'command not found' ... flutter gone!

### ISSUE THREAD

**Issue by remoteportal** [flutter/flutter#56773]
I can't do a flutter doctor because flutter is gone.

**Comment by amanv8060** [comment]
Things to try:
1.Open the folder where you have installed flutter
2.Open Terminal , try running flutter doctor, if that works, add the folder to path again

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
