### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by xintianyou** [flutter/flutter#56861]
```bash
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve io.flutter:x86_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve io.flutter:x86_64_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 53s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by iapicca** [comment]
Hi @xintianyou 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by ErrataSEV** [comment]
I have the same problem and the problem is with any application (it includes a newly created application). Although it does compile (install) and you can run the application without any problem (the problem is to run it in debug mode).

**Comment by zifeiyu666** [comment]
I have the same problem

`name: nlnw
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dio: any
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.6
  mobx: ^0.3.9+3
  flutter_mobx: ^0.3.3+3
  provider: ^3.2.0
  drop_cap_text: any
  like_button: ^0.1.9
  gradient_text: ^1.0.2
  device_info: ^0.4.1+4
  address_picker: ^0.0.1
  multi_image_picker: ^4.6.0
  image_picker: ^0.6.3+1
  video_player: ^0.10.5+1
  chewie: ^0.9.8+1
  flutter_svg: any
  path_provider: ^1.5.1
  pdf_viewer_plugin: ^1.0.0+2
  # flutter_alipay: '^0.1.0'
  # sy_flutter_alipay: any
  tobias: any
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  transparent_image: ^1.0.0
  badges: ^1.1.0
  spon_rating_bar: ^0.0.1
  flutter_pdfview: ^1.0.0+10
  flutter_easyloading: ^1.1.0
  city_pickers: ^0.1.30
  left_scroll_actions: ^1.2.1
  file_picker: ^1.4.3+2
  rxdart: ^0.23.1
  webview_flutter: ^0.3.19+2 #官方插件
  flutter_time_picker_spinner: ^1.0.6
  flutter_datetime_picker: ^1.3.1
  permission_handler: ^4.0.0
  fluttertoast: ^3.1.3
  web_socket_channel: ^1.1.0
  # w_popup_menu: ^0.3.0
  flutter_webview_plugin: ^0.3.10+1
  progress_dialog: ^1.1.0+1
  toast: ^0.1.4
  flutter_full_pdf_viewer: ^1.0.6

  extended_image: ^0.6.8
  flutter_android_downloader: ^0.0.1+2
  sqflite: ^1.2.0
  flutter_widgets: ^0.1.9
  flutter_badge: ^0.0.1
  extended_list: ^0.1.4
  uuid: ^2.0.4
  flutter_plugin_record: ^0.1.2
  easy_contact_picker: ^0.0.2
  lpinyin: ^1.0.9
  animated_widgets: ^1.0.3
  r_scan: ^0.1.3+2

  flutter_swiper: any
  jpush_flutter: 0.5.3
  flutter_easyrefresh: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  date_format: '^1.0.4'
  json_model: ^0.0.2
  json_serializable: ^2.0.0
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/image/
    - assets/images/file_manager/
    - assets/image/file_manager/
    - assets/images/file_manager/search.png
    - assets/images/voice/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
`

`FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:                                                       
         project :app                                                   
         project :app > project :flutter_pdfview                        
         project :app > project :flutter_plugin_android_lifecycle       
         project :app > project :screen                                 
         project :app > project :video_player_web                       
         project :app > project :r_scan                                 
         project :app > project :file_picker                            
         project :app > project :image_picker                           
         project :app > project :multi_image_picker                     
         project :app > project :permission_handler                     
         project :app > project :shared_preferences                     
         project :app > project :easy_contact_picker                    
         project :app > project :jpush_flutter                          
         project :app > project :city_pickers                           
         project :app > project :webview_flutter                        
         project :app > project :device_info                            
         project :app > project :shared_preferences_macos               
         project :app > project :flutter_full_pdf_viewer                
         project :app > project :shared_preferences_web                 
         project :app > project :fluttertoast                           
         project :app > project :sqflite                                
         project :app > project :path_provider                          
         project :app > project :video_player                           
         project :app > project :flutter_plugin_record                  
         project :app > project :pdf_viewer_plugin                      
         project :app > project :flutter_webview_plugin                 
         project :app > project :tobias                                 
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:                                                       
         project :app                                                   
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
   > Could not resolve io.flutter:x86_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:                                                       
         project :app                                                   
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
   > Could not resolve io.flutter:x86_64_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:                                                       
         project :app                                                   
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                `

**Comment by solomanlove** [comment]
我也有同样的问题，跟上面描述的一摸一样，可以调试，就是不能打包

**Comment by xxNull-lsk** [comment]
because pub.dartlang.org, this URL Inaccessible in China.
And Environment variables named PUB_HOSTED_URL is no effect.
Maybe this bug in bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot

**Comment by VladyslavBondarenko** [comment]
I tried this simplest code with `stable 1.17.0` and `dev 1.19.0-1.0.pre`. 
Android app is running. Debugging is working in Android Studio, couldn't reproduce the error.

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: RaisedButton(
        child: Text('button'),
        onPressed: () {
          print('pressed');
        },
      ),
    ),
  );
}
```

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/nevercode/dev/flutter_stable
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Redmi Note 7 • 6345c469 • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

**Comment by solomanlove** [comment]
Thank you for your reply. I have dealt with the problems caused by the latest version yesterday. Just switch to dev channel and then switch back




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vladyslav Bondarenko"<notifications@github.com&gt;; 
发送时间: 2020年5月13日(星期三) 晚上10:05
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "过眼云烟"<1009760663@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] App cannot be debugged and run after installing flutter1.17.0 (#56861)





 
I tried this simplest code with stable 1.17.0 and dev 1.19.0-1.0.pre.
 Android app is running. Debugging is working in Android Studio, couldn't reproduce the error.
 import 'package:flutter/material.dart'; void main() =&gt; runApp(MaterialApp(home: MyApp())); class MyApp extends StatelessWidget {   @override   Widget build(BuildContext context) =&gt; Scaffold(     body: Center(       child: RaisedButton(         child: Text('button'),         onPressed: () {           print('pressed');         },       ),     ),   ); }    flutter doctor -v [✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)     • Flutter version 1.17.0 at /Users/nevercode/dev/flutter_stable     • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700     • Engine revision 540786dd51     • Dart version 2.8.1   [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)     • Android SDK at /Users/nevercode/Library/Android/sdk     • Platform android-29, build-tools 29.0.3     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)     • All Android licenses accepted. [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)     • Xcode at /Applications/Xcode.app/Contents/Developer     • Xcode 11.4.1, Build version 11E503a     • CocoaPods version 1.9.1 [✓] Android Studio (version 3.6)     • Android Studio at /Applications/Android Studio.app/Contents     • Flutter plugin version 45.1.1     • Dart plugin version 192.7761     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211) [✓] VS Code (version 1.45.0)     • VS Code at /Applications/Visual Studio Code.app/Contents     • Flutter extension version 3.10.1 [✓] Connected device (1 available)     • Redmi Note 7 • 6345c469 • android-arm64 • Android 9 (API 28) • No issues found!

**Comment by suhaishuang** [comment]
i have the same problem

**Comment by YQjiuhao** [comment]
i have the same problem

**Comment by notigit** [comment]
i have the same problem

**Comment by suhaishuang** [comment]
> i have the same problem

when i change the sdk version，it working。

environment:
  #sdk: ">=2.1.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

**Comment by VladyslavBondarenko** [comment]
Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by YQjiuhao** [comment]
i have the same problem

**Comment by elderSword** [comment]
it works for me
`
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://download.flutter.io" }
    }
}`

**Comment by EdifierX** [comment]
it works for me
1.find your flutter/packages/flutter_tools/gradle
2.open flie: **aar_init_script.gradle**, **flutter_gradle**,**resolve_dependencies.gradle**
3.find code : `https://storage.googleapis.com/download.flutter.io` and replace it with code : `http://download.flutter.io`

**Comment by ngbede** [comment]
So I experienced this issue when incorporating firebase into my app. What I did to resolve this was run **flutter clean** in the project terminal.

**Comment by BradGroux** [comment]
> So I experienced this issue when incorporating firebase into my app. What I did to resolve this was run **flutter clean** in the project terminal.

**flutter clean** worked for me, thanks!

`C:\src\flutter>flutter clean`
`Deleting build...                                                  169ms`
`Deleting .dart_tool...                                               4ms`
`Deleting Generated.xcconfig...                                       1ms`
`Deleting flutter_export_environment.sh...                            0ms`

**Comment by madd-project** [comment]
@iapicca here is my issue,
```
F:\Apllications\toodo\toodo\android>flutter run --verbose
[  +82 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [C:\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +79 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +42 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[+2344 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +69 ms] List of devices attached
           4200acb99791a43d       device product:j7maxlteins model:SM_G615F device:j7maxlte transport_id:2
[   +9 ms] C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200acb99791a43d shell getprop
[ +114 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Changing current working directory to: F:\Apllications\toodo\toodo
[  +68 ms] Skipping pub get: version match.
[  +80 ms] Found plugin emoji_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +19 ms] Found plugin flutter_local_notifications at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+1\
[   +8 ms] Found plugin gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\
[  +27 ms] Found plugin image_gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[  +20 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +3 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +7 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +24 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +3 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +4 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +5 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +31 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +248 ms] Found plugin emoji_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +13 ms] Found plugin flutter_local_notifications at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+1\
[   +9 ms] Found plugin gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\
[  +19 ms] Found plugin image_gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[  +16 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +6 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +14 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +3 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +4 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +28 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +40 ms] Generating F:\Apllications\toodo\toodo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +93 ms] ro.hardware = mt6757
[        ] ro.build.characteristics = default
[  +53 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +4 ms] Launching lib\main.dart on SM G615F in debug mode...
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\ADMINI~1\AppData\Local\Temp\flutter_tools.e08cca47\flutter_tool.da588966\app.dill --packages F:\Apllications\toodo\toodo\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +28 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200acb99791a43d shell -x logcat -v time -t 1
[ +860 ms] <- compile package:toodo/main.dart
[ +160 ms] --------- beginning of main
                    05-05 11:40:54.907 D/NetworkController.MobileSignalController(0/4)( 1522): getMobileIconGroup(): 13
[  +18 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +75 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +76 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[  +27 ms] Using gradle from F:\Apllications\toodo\toodo\android\gradlew.bat.
[  +54 ms] F:\Apllications\toodo\toodo\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +38 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +278 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +3 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [F:\Apllications\toodo\toodo\android/] F:\Apllications\toodo\toodo\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=F:\Apllications\toodo\toodo\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2555 ms] > Configure project :emoji_picker
[ +127 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[  +69 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[   +9 ms] You will no longer be able to disable R8
[+1315 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:mergeDebugAssets'.
[        ] > Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
[        ]    > Could not create task ':app:minifyReleaseWithR8'.
[        ]       > Trailing char < > at index 48: C:\Users\Administrator\AppData\Local\Android\sdk \package.xml
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[ +593 ms] Running Gradle task 'assembleDebug'... (completed in 5.1s)
[+8166 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 15,844ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +175 ms] ensureAnalyticsSent: 172ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +14 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by iapicca** [comment]
@madd-project 
please open a new issue providing **_all_** the info requested [here](https://github.com/flutter/flutter/issues/56861#issuecomment-626676884)
