### ISSUE TITLE
Cannot read pixels from a SkImage created by MakeCrossContextFromPixmap

### ISSUE THREAD

**Issue by wqyfavor** [flutter/flutter#56966]
We are using Skia in Flutter engine to implement a html5 compatible canvas. There is a problem that `readPixels` or `makeRasterImage` method of SkImage do not work for SkImage(actually a SkImage_Lazy) created by `SkImage::MakeCrossContextFromPixmap`.

In `SkImage::MakeCrossContextFromPixmap` finally we get an image returned by  `SkImage::MakeFromGenerator` and the SkImage is of type SkImage_lazy.

    sk_sp<SkImage> SkImage::MakeFromGenerator(std::unique_ptr<SkImageGenerator> generator, const SkIRect* subset) 
    {
        SkImage_Lazy::Validator validator(SharedGenerator::Make(std::move(generator)), subset, nullptr, nullptr);
        return validator ? sk_make_sp<SkImage_Lazy>(&validator) : nullptr;
    }

I try to call `makeRasterImage` on it. `makeRasterImage` finally calls `readPixels` of SkImage. For SkImage_Lazy, code finally goes to SkImageGenerator::onGetPixels which only returns false and does nothing. Currently in OpenGL, the generator is an GrBackendTextureImageGenerator but it does not implement onGetPixels.

By the way, in my opinion, a SkImage returned by `MakeCrossContextFromPixmap` should be a GPU texture. But calling `isTextureBacked` on the instance returns false and `getBackendTexture` does not provide valid texture info.

The call stack is like this:
<img width="1516" alt="截屏2020-05-09 下午5 52 30" src="https://user-images.githubusercontent.com/113776/81635463-dd047d00-9443-11ea-8ed1-d31c15b4cb76.png">

So my final question is:
Is it possible or allowed to get pixels buffer out of a GPU backed texture SkImage instance created by `MakeCrossContextFromPixmap`.

**Comment by wqyfavor** [comment]
@liyuqian @zoeyfan 

Thanks, please help check this issue.

**Comment by liyuqian** [comment]
@iskakaushik mentioned that he ran into the same issue last year and could provide some feedback. Thank you Kaushik!

**Comment by iskakaushik** [comment]
`readPixels` (and `makeRasterImage` which eventually calls `readPixels`)  is meant to return a CPU copy of the image data. For many image types, that's straightforward. For cross-context images in Flutter, we run into a problem, because we don't know the GPU context to use for the read-back. The context that's stored (that created the image), is almost certainly wrong for the read back (in Flutter's usage).

Depending on what you're trying to do (would you be able to provide some additional information here?), you may be able to implement something similar with a tiny bit of code and the additional contextual information that's needed to make it work correctly.

One way to do it would be to make a surface of the size that you want, then draw the image to that, and then call `surface->makeImageSnapshot()`.

**Comment by chinmaygarde** [comment]
Just a heads up: There is also an assumption in the engine that Skia images backed by textures are always released on an unref queue (this way, the engine can guarantee a context is bound when the references are released and their textures collected). I see in your backtrace that the operations are occurring on an internal thread. Unless the image is sent to the unref queue for collection, there will be a texture memory leak.

Also, this is a custom engine build using private APIs and thread model that is subject to change. The team cannot guarantee the stability of these internals.

**Comment by Hixie** [comment]
IMHO our use of Skia at all is an implementation detail and not a supported feature. Directly accessing the underlying Skia objects is not a supported configuration.

**Comment by wqyfavor** [comment]
Thanks a lot to all of you. I will close this issue and will try other ways like painting the image to a surface.
