### ISSUE TITLE
request for wrap.builder method

### ISSUE THREAD

**Issue by aasirmutwalli22** [flutter/flutter#56980]
It is much better if there will be any widget like gridview.builder or listview.builder for wrap, as wrap widget is responsive to desktop and web ui, but without builder method it is very painful to map a list as widget[] for wrap widget

**Comment by kenthinson** [comment]
Not sure if the flutter team is interested in that or not. However in the mean time while you wait for a response. You can use List.generate to create something similar to a builder.
`
Wrap(
          children: List.generate(10, (index) {
            return Text("Test");
          }),
        ),
`

**Comment by VladyslavBondarenko** [comment]
thanks @kenthinson ,
@aasirmutwalli22 I hope this approach meets your needs, closing.
If you believe Wrap.builder is still needed, please write in comments and I'll reopen the issue

**Comment by NatoBoram** [comment]
Hi! I think `Wrap.builder` is still needed so that widgets are only built once they're in the screen.

Right now, I have a `Wrap` widget which contains way too many custom `Chip`. If I use both `Iterable.map().toList()` and `List.generate()`, the result is pretty much the same performance-wise and I have a few missing frames. It would be nice to be able to use the `ListView.builder()` pattern to gain some performance.
