### ISSUE TITLE
Adding Firebase to Flutter project

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#57034]
I am getting this errror after adding all the required dependencies for firebase ------

Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.

**Comment by iapicca** [comment]
Hi @SAMYAK99 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
