### ISSUE TITLE
web_benchmarks_canvaskit bench_picture_recording.canvaskit.estimatePaintBounds regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#57030]
![Screen Shot 2020-05-12 at 10 23 53 AM](https://user-images.githubusercontent.com/1435716/81725448-b261f680-943a-11ea-8462-e3614a6b4144.png)

If this device lab commit caused it, we may want to consider updating the baseline to reflect changes in testing: 
https://github.com/flutter/flutter/pull/56416

**Comment by Hixie** [comment]
cc @flar looks like this happened on your commit

**Comment by flar** [comment]
The commit in question doesn't get within a mile of this code. It only comes up when you run an A/B engine comparison manually.

@yjbanov @liyuqian any thoughts? Can this code somehow depend on the A/B stuff?

**Comment by flar** [comment]
If you click on the inspection icon and look at the long term trend of the benchmark you see that it has had a regression for a very long time ever since https://github.com/flutter/flutter/commit/5c5bb485a0db95fabc040253da42cd7d43cfac78

In fact, the 3 or 4 green samples you see at the left of the snapshot above are an anomaly and they only existed for 3 or 4 commits. Here is the bigger picture:

<img width="674" alt="Screen Shot 2020-05-12 at 5 29 05 PM" src="https://user-images.githubusercontent.com/50503328/81758277-1fdf4880-9476-11ea-9f4a-590398f78321.png">

**Comment by kf6gpe** [comment]
Thanks, @flar! I missed that in the history, too. I'll be more careful to drill down in the history in the future.

**Comment by liyuqian** [comment]
This regression is likely also due to "2020-04-22 dnfield@google.com Roll CanvasKit to 0.14.0, fix Canvas.saveLayer(null, paint) (flutter/engine#17849)"

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/55389. I will also rebase so it doesn't pop-up in the benchmark triage.
