### ISSUE TITLE
Not responding to all taps on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5709]
(feedback from four user tests with the gallery on Nexus 5X phones)

I watched users play with the gallery, and saw noticeable missed taps. I can't quantify how frequent or if there was an obvious pattern. But both the users and I noticed the app not responding in the way they expected.

Since this was across all four users, I wonder if we can take a closer look at why this was happening and why we weren't responding to taps in the way they expected.

If there's some debug/diagnostics we can add/enable, I'm happy to run other tests to get quantified data.

**Comment by Hixie** [comment]
We should expose `debugPaintPointersEnabled` in the gallery (debug mode only). This would allow you to try using the app for a while to see if the problem is that we're missing the event entirely or if we're just not thinking it taps the object.

We also have outstanding bugs with taps that could be the cause: https://github.com/flutter/flutter/issues/5557 https://github.com/flutter/flutter/issues/5017

**Comment by eseidelGoogle** [comment]
It may also be scroll hysteresis?  We're confusing taps for scrolls/flings?  e.g. https://github.com/flutter/flutter/issues/5524

**Comment by sethladd** [comment]
Yeah. @dragostis also had a similar insight :)

**Comment by sethladd** [comment]
Definitely seeing missing taps when trying to tap to open drawer on 5X.

**Comment by sethladd** [comment]
Possibly related: https://github.com/flutter/flutter/issues/5201

**Comment by HansMuller** [comment]
One source of this problem on Android is the overscroll animation, see https://github.com/flutter/flutter/issues/5717

Another source is the fact that press-drag-release gestures unconditionally generate fling animations, see #5870

**Comment by abarth** [comment]
Hans mentioned that he was looking at this issue.

**Comment by sethladd** [comment]
👍
