### ISSUE TITLE
Need better error message when nesting Positioned (and other) elements within each other.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#572]
```
'widgets/framework.dart': Failed assertion: line 1217: '() {
                  "You cannot nest parent data widgets inside one another.";
                  return ancestor is !ParentDataElement;
                }' is not true.
```

**Comment by Hixie** [comment]
We should probably print something to the log first, as we do in other similar places.

**Comment by Hixie** [comment]
@abarth I seem to recall you worked on this; do you know what the state of that was?

**Comment by abarth** [comment]
We can still improve here.  The message I improved was for widgets that wanted to be inside a Material.  The infrastructure for generating that message will probably be useful in improving this message.

**Comment by Hixie** [comment]
So I think the "You cannot nest parent data widgets inside one another." message should basically just go away, and instead we should give the same message as when you use a Positioned on its own: "Positioned must be placed inside a Stack". Similarly with the others.

And if there is already a Stack ancestor, but there's something else in the way, then it should say something like: "Positioned must be placed directly inside a Stack. You cannot place a Listener between the Stack and the Positioned."

I'll make this generic so that it can work for all ParentDataWidgets.

**Comment by Hixie** [comment]
We only have three ParentDataWidget classes: LayoutId, Positioned, and Flexible. They all fit the same pattern: require one particular class ancestor.

**Comment by Hixie** [comment]
Actually Flexible has to work for Column and Row... Tricky.

**Comment by Hixie** [comment]
And Positioned works for Stack and IndexedStack. Hmm...
