### ISSUE TITLE
flutter release apk: Unhandled exception when factory procedure uses @pragma("vm:entry-point") annotation

### ISSUE THREAD

**Issue by kongshanshan33** [flutter/flutter#57213]
I use the flutter sdk: v1.12.13+hotfix.7-pre.42

I want to set the class A and factory method as the entry points，the code like this：

main.dart
@pragma("vm:entry-point")
class A {
  const A();
  @pragma("vm:entry-point")
  factory A.icon() = _B;
}

class _B extends A {
  _B();
}
void main(){
print("test");
}

It throws exception when I run flutter  build apk --release:

Unhandled exception:                                                    
Assertion failed.                                                       
#0      assertx (package:vm/transformations/type_flow/utils.dart:34:5)  
#1      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:260:9)
#2      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:175:14)
#3      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1231:32)
#4      TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1439:23)
#5      Call.apply (package:vm/transformations/type_flow/summary.dart:210:31)
#6      Summary.apply (package:vm/transformations/type_flow/summary.dart:602:33)
#7      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:250:24)
#8      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:175:14)
#9      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1231:32)
#10     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1211:7)
#11     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1359:14)
#12     transformComponent (package:vm/transformations/type_flow/transformer.dart:59:20)
#13     runGlobalTransformations (package:vm/kernel_front_end.dart:461:5)
#14     compileToKernel (package:vm/kernel_front_end.dart:348:11)       
<asynchronous suspension>                                               
#15     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:505:54)
#16     new Future.<anonymous closure> (dart:async/future.dart:176:37)  
#17     _rootRun (dart:async/zone.dart:1122:38)                         
#18     _CustomZone.run (dart:async/zone.dart:1023:19)                  
#19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)             
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#21     _rootRun (dart:async/zone.dart:1126:13)                         
#22     _CustomZone.run (dart:async/zone.dart:1023:19)                  
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)   
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by mkustermann** [comment]
@alexmarkov Could you take a look?

**Comment by alexmarkov** [comment]
The problem is that kernel AST looks really weird for the redirecting factory constructors:

```
  class A extends core::Object /*hasConstConstructor*/  {
    static field dynamic _redirecting# = <dynamic>[tes::A::icon];
    const constructor •() → tes::A*
      : super core::Object::•()
      ;
    @#C3
    static factory icon() → tes::A*
      let dynamic #redirecting_factory = tes::_B::• in invalid-expression;
```

TFA cannot really interpret `let dynamic #redirecting_factory = tes::_B::• in invalid-expression;` body of such constructor, as it involves tear-off of a constructor `_B` and invalid expression.

Related: https://github.com/dart-lang/sdk/issues/28424, https://github.com/dart-lang/sdk/issues/28421.

Ideally we should have a dedicated RedirectingFactoryConstructor AST node to represent redirecting factory constructors and avoid malformed AST in their bodies. /cc @johnniwinther

As a workaround, I'll try to recognize redirecting factory constructors when handling entry points in TFA and avoid using their bodies.

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/148203 fixes this crash and ensures that target of a redirecting factory constructor is retained while tree-shaking.

However note that VM currently ignores redirecting factory constructors after they are desugared by the front-end (e.g. `new A.icon()` invocations are replaced with `new _B()` by the front-end and `A.icon` is discarded). So, it is currently not possible to call redirecting factory constructors via Dart C API (this is tracked in https://github.com/dart-lang/sdk/issues/33041).

@kongshanshan33 How do you plan to use that redirecting factory constructor annotated with `@pragma("vm:entry-point")` ? If you would like to call it from C code, then I would suggest to change redirecting factory constructor to an ordinary factory or even just a static method:

```dart
  @pragma("vm:entry-point")
  factory A.icon() => new _B();
```

**Comment by kongshanshan33** [comment]
@alexmarkov I want to make a tool to output the dependencies of input class。 For example A depends on B，B depends on C, I input class name of A the tool will output B C 。So I traverse procedures of class and call function addRawCall of TypeFlowAnalysis by modify dart sdk。I found that when I encounter redirecting factory constructor an exception is thrown。At first I thought it was a problem with my code。But I found it also threw an exception when I added @pragma("vm:entry-point") at the source level as shown above。

**Comment by alexmarkov** [comment]
@kongshanshan33 That's an interesting way of using TFA. Note that you may get different results depending on the order of adding raw calls: calculation of dispatch targets depends on the set of allocated classes seen so far, so adding one call may cause another call to discover more targets for method invocations.

Unfortunately the fix https://dart-review.googlesource.com/c/sdk/+/148203 won't help for your tool, because redirecting factory constructors are handled before calling addRawCall. But you could try to add similar handling of redirecting factory constructors into your tool.

https://github.com/dart-lang/sdk/issues/41915 might help a bit more: if redirecting factory constructors would have a normal body we can remove all this special handling of redirecting factory constructors and they would just work as ordinary factory constructors.

**Comment by alexmarkov** [comment]
The fix was rolled into the Flutter.
