### ISSUE TITLE
Expose detailed native heap allocation to DevTools

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#57230]
This is a tracking issue to figure out how to tie Dart heap (and thus application code) to the native heap behavior.

We discussed in a couple of recent meetings that Flutter developers need to be able to tell the effect of their application code on the native heap allocations. Potentially related: https://github.com/flutter/flutter/issues/31498

**Comment by mehmetf** [comment]
@devoncarew FYI

**Comment by zanderso** [comment]
The Dart VM has some code to profile native memory allocations. It depends on the VM knowing that it is linked against tcmalloc, which I believe may be the default on some platforms---Linux, and maybe Android ([impl here](https://github.com/dart-lang/sdk/blob/master/runtime/vm/malloc_hooks_tcmalloc.cc)).

This information is collected and exposed by the VM service ([_getNativeAllocationSamples](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service.cc#L4809)) by the command line VM when it is passed the flag[ --profiler-native-memory](https://github.com/dart-lang/sdk/blob/master/runtime/vm/flag_list.h#L188), but currently only in debug builds since it was primarily intended to help track down internal VM leaks.

Making this developer-facing would involve at least
* Figuring out how to enable in Flutter profile builds, reducing the runtime cost if necessary,
* Adding hooks for non-tcmalloc allocators, or using tcmalloc more uniformly,
* Adding vmservice hooks for configuring the native allocation sample buffer size,
* https://dart-review.googlesource.com/c/sdk/+/152587

fyi @bkonyi

**Comment by bkonyi** [comment]
cc @rmacnak-google

**Comment by devoncarew** [comment]
I wonder if this would be easier to solve as a kernel transformer, if we just wanted to track targeted types of objects? Like having an API to enable and disable tracking allocation locations for objects of a certain class.

cc @jacob314 @terrylucas

**Comment by zanderso** [comment]
@devoncarew That sounds like a good idea. You could instrument allocations of objects extending `NativeFieldWrapperClass{1,2}` like `dart:ui#Image`: https://github.com/flutter/engine/blob/master/lib/ui/painting.dart#L1589, and the native size could be surfaced either statically in an annotation on the class declaration, or dynamically with a runtime call or method call. Since the allocations of some of those objects might be internal to `dart:ui` and `dart:io`, you might need an instrumented platform.dill.

My comment was more in relation to native allocations that aren't associated with a Dart object, which is a different problem.

**Comment by Hixie** [comment]
Getting visibility into our memory usage should be a higher priority, as it will inform many other aspects of our work.
cc @dnfield @liyuqian @terrylucas

**Comment by a-siva** [comment]
After the recent change by Flutter engine to not report the exact external size of native objects which are referenced by Dart it is not possible for the Dart VM to surface the native memory usage accurately.
It appears to me that the Flutter engine needs to track and report this value to devtools.

**Comment by kf6gpe** [comment]
Per a-siva, I suggest closing.

I don't have triager privs for the repo anymore, but I'll look to @a-siva and @zanderso to close it.

And hi! :)

**Comment by zanderso** [comment]
Hi Ray!
