### ISSUE TITLE
Overview bar doesn't cover app bar entirely 

### ISSUE THREAD

**Issue by AliGharian** [flutter/flutter#57359]
## Steps to Reproduce

1. Press overview button.

**Expected results:**
overview  bar should be cover app bar entirely just like native applications.

**Actual results:**
overview bar doesn't cover app bar completely.

<details>
  <summary>I attached an image that shows different in flutter app and native android app when overview button pressed</summary>

```
```

```
```

```
```

</details>
![screen](https://user-images.githubusercontent.com/41072136/82112394-b6a35200-9761-11ea-99bf-6795dc26fb1d.jpg)

**Comment by darshankawar** [comment]
@AliGharian 
Since this is an year old issue, I suggest you to verify again using [latest](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos) Flutter version to see if you still get same behavior or not.

Since you didn't provide any code or version details, it's hard to make it actionable. 

I am going ahead and closing this issue as stale. If you still see the same behavior on latest stable version, provide all required details like `flutter doctor -v`, a complete code sample to properly address it.
