### ISSUE TITLE
Need a way to distribute plugins/services for Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5744]
With the (new) hello_services architecture, "plugins" or services for flutter consist of 3 pieces:
- iOS specific HostMessage sender/listener code (obj-c or swift)
- Android specific HostMessage sender/listener code (java)
- dart HostMessage sender/listener code and x-platform api abstraction.

And of course the necessary code to build/integrate the iOS and Android code into the developer's final application (cocoapods? gradle/maven?).

We don't yet have a full design for this.  This bug is just for tracking.

**Comment by brianegan** [comment]
Just to throw in a "nice to have," don't know if it's desirable, just a bit of feedback from a potential user: At SoundCloud, we use few C++ libs for sharing code between iOS and Android. Might be cool to have native C++ support in addition to the Android / iOS path. 

That way, we could integrate Flutter directly with our C++ libs, rather than wrapping them in iOS / Android code, and then wrapping them once more for Flutter.

**Comment by mit-mit** [comment]
Thanks for the feedback @brianegan, we are tracking that in https://github.com/flutter/flutter/issues/7053

**Comment by mit-mit** [comment]
Closing this bug in favor of the more specific issues https://github.com/flutter/flutter/issues/7815 and https://github.com/flutter/flutter/issues/7816
