### ISSUE TITLE
audit all try-finally blocks and reduce the number of calls inside them

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5756]
try-finally blocks have an O(N) cost in the number of calls within the block. We should make sure we don't have calls at the top of try-finally blocks that could be placed before hand.

**Comment by abarth** [comment]
Can we just wrap the body in a function so there's only one call?

**Comment by Hixie** [comment]
Yes, if we are left with multiple statements in a hot try/finally block after we've moved out as much as we can, then that's the next step.

**Comment by Hixie** [comment]
cc @goderbauer @liyuqian This could be an easy win, if the compiler still does this. We should check.
Even better would be to improve the compiler of course...

**Comment by liyuqian** [comment]
Talked with @mraleph about this. Right now, try/catch still disables some optimization, but penalizing each statement is no longer case. For that, I wonder if we can close this issue. @mraleph : it would be even better if you can share some benchmarks that can support the fact that the cost no longer grows linearly as the number of statements increases.

**Comment by mraleph** [comment]
Here is the [internal design doc](https://docs.google.com/document/d/1_vX8VkvHVA1Om7jjONiWLA325k_JmSZuvVClet-x-xM/edit) that covers the change which we did in 2017 - it explains what were the costs associated with calls in try blocks and how we addressed it.

>  it would be even better if you can share some benchmarks that can support the fact that the cost no longer grows linearly as the number of statements increases.

I am not sure I understand this requirement - obviously as you add more code the cost grows proportionally to the added code, e.g. if you have N calls each costing C in the try block then overall cost would be at least C * N ~ O(N). 

However what happened before is that each call was adding non a constant amount cost, but it rather had additional overhead proportional to the number of live variables in the method, so instead of getting C * N you would get (C + V) * K ~ O(V * K). We have since removed this cost. 

I think the only two things that are currently disabled for functions with try catch are:

- allocation sinking
- inlining of functions containing try-catch (we can still inline into functions that contain try catch).

**Comment by liyuqian** [comment]
> > it would be even better if you can share some benchmarks that can support the fact that the cost no longer grows linearly as the number of statements increases.
> 
> I am not sure I understand this requirement - obviously as you add more code the cost grows proportionally to the added code, e.g. if you have N calls each costing C in the try block then overall cost would be at least C * N ~ O(N).

Cool, it's nice to know that it was super-linear and now linear. For the sub-linearity, I'm thinking about the following case:
```
try {
  throw exception;
  another N-1 statements;
} finally {
  something very cheap;
}
```

As N increases, does the above code's run time grow linearly with N, or does it stay constant, or somewhere sublinear.

@Hixie : is the above case part of the reason why this issue was originally created?

**Comment by mraleph** [comment]
@liyuqian `another N-1 statements` would be thrown out as dead code, but the cost would be dominated by throwing an exception (which is not that cheap).
