### ISSUE TITLE
[device_info] Add Support for Android UiModeManager to Detect Android TV at Runtime

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#57571]
To detect the specific Android runtime device, such as Android TV or Android Auto. 

For Android TV, the current recommended method is to call the UiModeManager API when writing Kotlin or Java, as per this documentation: https://developer.android.com/training/tv/start/hardware#runtime-check

Currently the Device Info plugin package does NOT support this API. It would make sense for device_info to support this for detecting at runtime TV, cars, watches etc. This would allow selection of differing layouts within a single Flutter app, based on the specific Android platform on which it is running. For example, for an app with a landscape orientation type screen, could determine if it was a tablet in landscape orientation, or running on an Android TV with the Leanback Launcher.

Specifically for my use case, would like this getCurrentModeType method implemented in device_infoas per API documentation here:
https://developer.android.com/reference/android/app/UiModeManager#getCurrentModeType()

**Comment by vklyovan** [comment]
While I support this enhancement in order to make it in a recommended way, but it shouldn't be a problem since all of this can be found using the list of system features that is available in device_info plugin right now.

Code example:
`if (Platform.isAndroid) {
      AndroidDeviceInfo androidDeviceInfo =
          await DeviceInfoPlugin().androidInfo;
      _isAndroidTv = androidDeviceInfo.systemFeatures
          .contains('android.software.leanback');
    }`

Link: https://developer.android.com/guide/topics/manifest/uses-feature-element#features-reference

Automotive should have "android.hardware.type.automotive" feature
Watches should have "android.hardware.type.watch" feature

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
