### ISSUE TITLE
[web] Page title is set via title property of MaterialApp

### ISSUE THREAD

**Issue by BoHellgren** [flutter/flutter#57673]
I use Firebase hosting to host my Flutter web app. When I run it on Chrome on Windows, the text on the Chrome tab is  "Flutter Demo". I don't know where that name comes from, and I want to see the name of my app instead.
![Skärmklipp](https://user-images.githubusercontent.com/18601125/82450833-7fa8a580-9aad-11ea-99f1-9a47b28745a0.JPG)

My index.html:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="new_vem_bor_var">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>

  <title>new_vem_bor_var</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```
My manifest.json:
```
{
    "name": "new_vem_bor_var",
    "short_name": "new_vem_bor_var",
    "start_url": ".",
    "display": "standalone",
    "background_color": "#0175C2",
    "theme_color": "#0175C2",
    "description": "A new Flutter project.",
    "orientation": "portrait-primary",
    "prefer_related_applications": false,
    "icons": [
        {
            "src": "icons/Icon-192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "icons/Icon-512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}
```
Flutter version:
```D:\AndroidStudioProjects\new_vem_bor_var>flutter --version
Flutter 1.18.0-11.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2738a1148b (7 days ago) • 2020-05-13 15:24:36 -0700
Engine • revision ef9215ceb2
Tools • Dart 2.9.0 (build 2.9.0-8.2.beta)```

**Comment by VladyslavBondarenko** [comment]
Hi @BoHellgren 
Change the title property of MaterialApp widget for this.
Closing as solved,
If you disagree please write in the comments

**Comment by BoHellgren** [comment]
Thanks, that did it. I had
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
          textTheme: TextTheme(bodyText2: TextStyle(fontSize: 22.0))),
      home: VemBorVar(title: 'Vem Bor Var'),
    );
  }
}
```
There are two _title_: here, and it is far from obvious that the first _title_: is used this way. This should be documented somewhere!

**Comment by Pebsie** [comment]
Wouldn't it make sense to be able to alter this programatically during execution?

**Comment by syfulin** [comment]
There is a problem with the page title in Flutter Web.

after setting the title parameter:

```
...
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Title',
      theme: ThemeData(
...
```
The custom title is displayed correctly in the desktop version of the site:

![ok_desktop](https://user-images.githubusercontent.com/20333151/96358218-eac6d880-112e-11eb-9c17-b699ff7a7405.png)


But in mobile browsers, instead of the title, a string with the value "flutter" is displayed.

I tried to find the 'flutter' string in the compiled js code and replace it with another value:
![replace](https://user-images.githubusercontent.com/20333151/96358240-3d07f980-112f-11eb-9b81-eb53f0ade433.png)


Problem solved, but I don't think it is a good solution:
![comp](https://user-images.githubusercontent.com/20333151/96358250-4beeac00-112f-11eb-8669-4ff947ddea76.png)

Examples:

1. Correct mobile header:
http://hhhhtyu.000webhostapp.com/test_title_2/

2. Invalid mobile header:
http://hhhhtyu.000webhostapp.com/test_title/

I also noticed that in the second example, `/#/` is inserted at the end of the url.

Help me to understand

**Comment by Oklahomawhore** [comment]
how to change individual page title ?

**Comment by easeccy** [comment]
> how to change individual page title ?

https://stackoverflow.com/a/60456688/7314211
