### ISSUE TITLE
[shared_preferences] [android] cannot find API

### ISSUE THREAD

**Issue by pazhut** [flutter/flutter#57781]
i am getting the following error:
E/flutter (17343): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

Thanks

**Comment by Thesmader** [comment]
MissingPluginException usually happens when you included the plugin but did not restart the app. Hot reload, or hot restart won't do the trick. Flutter has to inject the dependencies of the plugin to platform-specific parts of your app. Close the app and rerun it. Always search for the problem online before opening issues. 
You can check this [issue](https://github.com/flutter/flutter/issues/10912). If this solved your problem, please close this issue.

**Comment by iapicca** [comment]
Hi @Thesmader 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by pazhut** [comment]
Thanks for your reply, the problem got solved it was related issues in the
AndroidManifest.xml file, i will close the issue for now
