### ISSUE TITLE
A request for Sublime Text Support

### ISSUE THREAD

**Issue by clintonnzedimma** [flutter/flutter#57862]
Hello Flutter Team,  I am humbly making a request for flutter to be supported on Sublime Text. A handlful of us like the editor and would like to continue using it for building apps. Kindly help the developer community using sublime text. Thank you.

**Comment by jonahwilliams** [comment]
The supported editors are described at https://flutter.dev/docs/get-started/editor?tab=androidstudio . We're unlikely to contributor to any more implementations, since there are a ton of IDEs/editors.

Dart has supported for the language server protocol, I would recommend looking into using that in combination with a sublime text LSP client.
