### ISSUE TITLE
flutter_windows.dll is too big and cannot be statically linked

### ISSUE THREAD

**Issue by texasbruce** [flutter/flutter#57875]
##  Use case

flutter_windows.dll alone is ~28M. Plus kernel_blob.bin which ~27M. Bundle size is almost 60M for a simple one window application.

Also there is no way to create single binary including all the libraries and assets.

## Proposal

1. Allow statically linking of windows library.
2. Separate into different modules and allow only linking libraries needed.
3. Find other ways to reduce the library size
4. Create a way to compile all resources into single binary (VS Compiler supports it)

**Comment by stuartmorgan** [comment]
We can't discuss and track four distinct proposals in one issue; please file a new issue for each proposal. I've added some initial feedback below that would be helpful to address when filing the new issues. As a general note for all of them, please keep in mind that the purpose of the "Use case" section is to explain what real-world uses are allowed, or improved, by the proposal. The goal there is to explain why it's valuable, not just what the proposal is.

> flutter_windows.dll alone is ~28M. Plus kernel_blob.bin which ~27M. Bundle size is almost 60M for a simple one window application.

It's not at all clear why you are concerned about debug artifact sizes. Please explain in size-related proposals what use case is impacted by having 60M debug builds.

> Also there is no way to create single binary including all the libraries and assets.

This is true, but again, not a use case.

> 1. Allow statically linking of windows library.

Static linking requires building everything from source using the same toolchain and build options. Please [build the engine from source](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) if you haven't already before filing this proposal, so that you understand how much more complex that use model would be for Flutter application developers, and then explain what benefits you see and in what use cases the benefits would be worth that much added difficulty.

> 2. Separate into different modules and allow only linking libraries needed.

Please provide specific examples in the new issue of what modules you would like separated out that you don't believe you need.

> 3. Find other ways to reduce the library size

See above about motivating this; what is the use case where debug build binary size is a significant issue.

> 4. Create a way to compile all resources into single binary (VS Compiler supports it)

This would add non-trivial API complexity, for use on only one platform. Please explain in the new issue what use case is addressed by this—especially keeping in mind that it would be possible to create a single-file output with static linking, which as noted above is dramatically more difficult, meaning this would be rarely used.

**Comment by texasbruce** [comment]
Debug build size is mentioned because there is no Release mode currently for Windows port AFAIK.

 flutter_windows.dll is more of a concern. I mentioned modulization because it allows developers to distribute only necessary dlls without having to bundle everything, which essentially reduce the distribution size.

I will create another issue dedicated to reducing release distribution size. Thanks!

**Comment by texasbruce** [comment]
@stuartmorgan Debug build size is mentioned because there is no Release mode currently for Windows port AFAIK.

flutter_windows.dll is more of a concern. I mentioned modulization because it allows developers to distribute only necessary dlls without having to bundle everything, which essentially reduce the distribution size.

I will create another issue dedicated to reducing release distribution size. Thanks!
