### ISSUE TITLE
why you people not fixing the existing bugs flutter has,

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#58096]
on simple run i m getting 100 and 100 of warning,,,return type string int type,,,list type  lost inpu connections etc,  even not human friendly errors,,,i would say it's just a buggy framework,,,,and i can't believe it's created by google, just  garbage nothing else,

**Comment by atta1234** [comment]
i would say lean from the   founder php and then create frameworks,,

**Comment by kamathprasad9** [comment]
Have you tried coding for the first time? I guess we all get 3/4 errors or warnings for a silly mistake. Are you frustrated with flutter because of your inability to solve those errors/warnings? I would say give yourself some more time with flutter before speaking any rubbish. I cant understand why some people want to report needless stuff. And more importantly, be precise of what you are speaking. 
> on simple run . What does on simple run mean?

**Comment by kamathprasad9** [comment]
Have you tried coding for the first time? I guess we all get 3/4 errors or warnings for a silly mistake. Are you frustrated with flutter because of your inability to solve those errors/warnings? I would say give yourself some more time with flutter before speaking any rubbish. I cant understand why some people want to report needless stuff. And more importantly, be precise of what you are speaking.
> on simple run . 
What does on simple run mean?

**Comment by kamathprasad9** [comment]
Have you tried coding for the first time? I guess we all get 3/4 errors or warnings for a silly mistake. Are you frustrated with flutter because of your inability to solve those errors/warnings? I would say give yourself some more time with flutter before speaking any rubbish. I cant understand why some people want to report needless stuff. And more importantly, be precise of what you are speaking.

>on simple run <. What does on simple run mean?

**Comment by kamathprasad9** [comment]
Have you tried coding for the first time? I guess we all get 3/4 errors or warnings for a silly mistake. Are you frustrated with flutter because of your inability to solve those errors/warnings? I would say give yourself some more time with flutter before speaking any rubbish. I cant understand why some people want to report needless stuff. And more importantly, be precise of what you are speaking.
> on simple run
