### ISSUE TITLE
flutter_test_performance regressed by ~3x

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58126]
The regression clearly started from https://github.com/flutter/flutter/commit/9d7116cd843016670bc77684171865d1d720d07d

<img width="546" alt="Screen Shot 2020-05-27 at 2 42 06 PM" src="https://user-images.githubusercontent.com/22987568/83075351-8b094d00-a028-11ea-9e5c-1f2ac05755f1.png">

A bisect for engine commits is needed.

**Comment by liyuqian** [comment]
CC test author @Hixie to see if there's any insight.

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/53ac4d53f273485e33f8bc063d9d418ef6933e83

@jensjoha

**Comment by jensjoha** [comment]
It became slow with https://github.com/dart-lang/sdk/commit/53ac4d53f273485e33f8bc063d9d418ef6933e83 because the nnbd mode is now actually set for the platform (it must have not been before). It is compiled as nnbd weak which is not allowed to be mixed with nnbd disabled (which is what the other stuff is compiled as).

I'm not totally sure if it actually should be allowed --- @johnniwinther or @mralph might know...

(Also it seems that we haven't thought about this situation where we load a single dill that's not agnostic and compile against that in another mode --- probably we should; again, @johnniwinther might have thoughts?)

**Comment by liyuqian** [comment]
@jensjoha : shall we revert the commit, and reland later once we figured out either a fix, or that we should rebaseline the benchmark to allow this regression?

**Comment by Hixie** [comment]
We should definitely not regress test performance 3x, it's already 10x slower than it was a few years ago.

**Comment by jensjoha** [comment]
We will allow mixing disabled and weak. That should fix the issue.

**Comment by jensjoha** [comment]
This should now be fixed in part, meaning it should go back to normal when dart is rolled.

**Comment by pcsosinski** [comment]
is this fixed?

**Comment by liyuqian** [comment]
The last Dart roll was 5 days ago. It was resumed today but the last 2 rolls have failed. So we're still waiting for a Dart roll, and then an engine roll to fix this.

**Comment by liyuqian** [comment]
Closing as benchmarks returned to green.
<img width="711" alt="Screen Shot 2020-06-04 at 11 47 51 AM" src="https://user-images.githubusercontent.com/22987568/83798558-4a798700-a659-11ea-9566-7ed9c938bb6d.png">
