### ISSUE TITLE
[webview]Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference

### ISSUE THREAD

**Issue by vishnunew** [flutter/flutter#58229]
My app constantly crashing with below crash in webview for some devices. is anyone have the solution for this ?

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:2078)
       at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:765)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
Version : `webview_flutter 0.3.19+10`

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at
    • Framework revision f139b11009 (8 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available
```

**Comment by TahaTesser** [comment]
Hi @vishnunew 
Please upgrade to latest `stable` and try again with latest `webview_flutter 0.3.22+1`
if the problem persist after upgrade, can you please provide  your `flutter doctor --verbose`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by rajeshzmoke** [comment]
this happens when a link is trying to open a new window or tab in the webview

**Comment by vishnunew** [comment]
Thank you @rajeshzmoke. It is not happening in all the devices. Few devices i am facing this issue.

**Comment by vishnunew** [comment]
@TahaTesser Yes i am updating my project and will let you know the same. Thanks

**Comment by Mauiie** [comment]
I also encountered the same problem.

This problem occurs when webview page A jumps to webview page B, and then there is an input dialog box that invokes our keyboard, and then displays the Android dynamic permission request, and the application crashes.

I tried to solve this problem, I found that this problem may be related to #38375,
And when I remove the 'containerView' passed to InputAwareWebView in FlutterWebView everything is normal.

I know I can't do this violently, so I extended the onPause and onResume methods in InputAwareWebView to remove 'containerView' and add back containerView.
Actively call onPause when webview page A jumps, and then call onResume when you come back. 
This solves the problem I encountered, and the application can run normally. 
The relevant code is as follows, I wrote badly so you can refer to and write better code.

InputAwareWebView:

` private View containerView;
    private View viewTimp;
    public void onPause() {
        super.onPause();
        resetInputConnection();
        containerView = null;
    }


    public void onResume() {
        super.onResume();
        containerView = viewTimp;
    }`

WebViewFlutterPlugin -> onAttachedToActivity :

`Lifecycle lifeCycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
        lifeCycle.addObserver(new DefaultLifecycleObserver() {
            @Override
            public void onPause(@NonNull LifecycleOwner owner) {
                factory.onPause();
            }

            @Override
            public void onResume(@NonNull LifecycleOwner owner) {
                factory.onResume();
            }

            @Override
            public void onDestroy(@NonNull LifecycleOwner owner) {
            }

            @Override
            public void onCreate(@NonNull LifecycleOwner owner) {
            }

            @Override
            public void onStop(@NonNull LifecycleOwner owner) {

            }

            @Override
            public void onStart(@NonNull LifecycleOwner owner) {

            }
        });`
 


There is also an extended interactive method that allows me to actively drop the webview's onPause when the page jumps


But Then in the end I didn’t use this method.
Because I didn’t know whether this solution was completely correct, and I didn’t know if it would cause other problems.
So we changed the rules of the app, when webview page A jumped to webview On page B, I used pushReplacement to replace push.

The webview page A\B I just mentioned is a Flutter page containing webiew_flutter, not H5page.

I hope that what I said will help someone, I tried my best.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Mauiie** [comment]
I created a new issue, and attached code, log and flutter doctor -v  @TahaTesser
