### ISSUE TITLE
[image_picker] Is photo-library-permission necessary for pickImage/pickVideo from gallery？

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#58252]
Is photo-library-permission necessary for pickImage/pickVideo from gallery？As far as I know, picking image by system UI does not require this permission. (For example of iOS, UIImagePickerController seems do not require PHAuthorizationStatusAuthorized). I don't like those apps **looking over my WHOLE gallery** for just picking one image, and I want users know that my apps are not doing that.

I tried replacing this [line](https://github.com/flutter/plugins/blob/image_picker-v0.6.7/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m#L115) with `[self showPhotoLibrary]`
```dart
    switch (imageSource) {
      case SOURCE_CAMERA: {
        NSInteger cameraDevice = [[_arguments objectForKey:@"cameraDevice"] intValue];
        _device = (cameraDevice == 1) ? UIImagePickerControllerCameraDeviceFront
                                      : UIImagePickerControllerCameraDeviceRear;
        [self checkCameraAuthorization];
        break;
      }
      case SOURCE_GALLERY:
        // [self checkPhotoAuthorization]; // replace this
        [self showPhotoLibrary]; // to this
        break;
      default:
        result([FlutterError errorWithCode:@"invalid_source"
                                   message:@"Invalid image source."
                                   details:nil]);
        break;
    }
```
, everything seems working without PHAuthorizationStatusAuthorized.

At the moment I have only done some simple tests on iOS. I am new to both flutter and mobile development.  It's appreciated if any one could tell me how I can make it correctly(or where I can learn that). Of course, it would be awesome if image_picker could do that.

**Comment by Hixie** [comment]
This is probably a question for Android and iOS more than Flutter, but we should at least add the answer to the question to our documentation.

**Comment by vainman** [comment]
@Hixie Hi, thank you for reply. I think this is a question for Flutter/image_picker because the plugin always checks the permission(which seems unrequired) before showing system UI to pick image.

**Comment by pedromassangocode** [comment]
@cyanglaz to properly answer/handle this issue.

**Comment by cyanglaz** [comment]
The permission is not necessary anymore since iOS 11 on iOS. However, the permission is required if you need to access detailed meta data of the images/videos you picked. There's a plan to add a flag to disable the permission. See: https://github.com/flutter/flutter/issues/65995#issuecomment-704588955
It is also being actively worked on here: https://github.com/flutter/plugins/pull/3264

**Comment by pedromassangocode** [comment]
Hi @ghost
Since this is being worked in https://github.com/flutter/plugins/pull/3264 and the question is now answered I'm going to close this. This question will be answered in the API docs of the property being added by https://github.com/flutter/plugins/pull/3264 so no additional fix is required.
Thank you
