### ISSUE TITLE
BM_ShellShutdown regressed ~16x

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58261]
See https://flutter-perf.skia.org/e/?begin=1590623523&end=1590741783&keys=X9f1bf2296ffa1906179257e3f4475f70&xbaroffset=17822

The commit that caused the regression is https://github.com/flutter/engine/commit/89cf074d37633e030bb86a047f6e5bb49ef44b43 (https://github.com/flutter/engine/pull/18225)

**Comment by liyuqian** [comment]
@jason-simmons @scutlight : shall we revert the commit before figuring out why this happened and how to fix it?

**Comment by liyuqian** [comment]
I also saw a big speedup in ShellInitialization: https://flutter-perf.skia.org/e/?begin=1590623523&end=1590741783&keys=X0fffad7016a0440022353623dc52ae28&xbaroffset=17822 . Could it be possible that we're just shifting time? In that case, maybe we should revise our test to correctly measure the initialization and shutdown time.

**Comment by jason-simmons** [comment]
The benchmark results are changing because work is being shifted out of `Shell::Create` and into a task posted on the UI thread that initializes the default font manager.

`BM_ShellInitialization` measures the time consumed until `Shell::Create` returns.  This no longer includes font manager setup.

`BM_ShellShutdown` measures the time consumed by the `Shell` destructor.  `Shell::~Shell` queues a task to the UI thread and waits for it to complete.  That task can not execute until the font manager task queued by `Shell::Create` finishes.  So most of the time spent by font manager setup is now credited to the `BM_ShellShutdown` metric.

We could exclude font manager setup from the benchmark by queuing another task to the UI thread and waiting for that to complete before measuring the `Shell` destructor.

@chinmaygarde

**Comment by liyuqian** [comment]
Thanks @jason-simmons for the investigation! I'll take P0 and TODAY label out as there's no actual performance regression. The suggestion to let `BM_ShellShutdown` only measure the `Shell` destructor sounds good.

**Comment by scutlight** [comment]
@liyuqian @jason-simmons : I've new a pr to fix this benchmark regression. https://github.com/flutter/engine/pull/18676

**Comment by liyuqian** [comment]
Closing this as https://github.com/flutter/engine/pull/18676 landed and we confirmed the improvement of the metric.
