### ISSUE TITLE
Flutter build without triggering an Xcode build

### ISSUE THREAD

**Issue by JacobWrenn** [flutter/flutter#58336]
## Use case

When performing continuous delivery of a Flutter application an Xcode build is run twice. Once using the `flutter build ios` and then a second time through Fastlane to send it to Apple. This is the current official way to do this.

## Proposal

The ability to build all the Flutter parts of the iOS app but not trigger an Xcode build. This new command would not add any functionality but it would mean that an Xcode build can be then triggered by Fastlane or another tool specifying all the custom options wanted. All this new command would do is put everything in place and ready from a Flutter perspective and then stop.

**Comment by jmagman** [comment]
You may be able to do what you want with the `flutter assemble` command.  The command is intended to be used by the Flutter build system to compile your dart code, move resources into place, etc, so there's not much documentation for it.  `flutter assemble -h` has a few more details.  

More helpfully, if you run `flutter build ios --release -v` you can see the exact parameters to use for your app.  It will be something like:
```
/Users/m/Projects/flutter/bin/flutter --verbose assemble --output=/Users/m/Projects/test_create/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=armv7 arm64 -dSplitDebugInfo= -dTreeShakeIcons=true -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions=release_ios_bundle_flutter_assets
``` 

This is a pretty niche proposal and not something we're going to make more user-friendly, so I'm going to close this since I think you can get away with writing a script that leverages `assemble`.
