### ISSUE TITLE
ReorderableListView destroys children even if Key-Type of children wasn't changed

### ISSUE THREAD

**Issue by MariaMelnik** [flutter/flutter#58364]
Hi,
I noticed ReorderableListView rebuilds children every time even if Key-Type of children wasn't changed.

demo: https://dartpad.dartlang.org/d5cdcdbd79081a06f0b5bdacfeb55c33
(https://gist.github.com/MariaMelnik/d5cdcdbd79081a06f0b5bdacfeb55c33)

**Steps to reproduce:**

- Create new flutter project with main.dart copied from example above.
- Run on device (I used Chrome(web) and simulator iPhone 11 Pro max).
- Hit refresh icon button at the AppBar.

**What do I expect:**
Nothing changed. Because keys which I set to widget didn't changed (I used ValueKey with int inside. int will always be equal same int). So I expect my _MyListTileState keeps ms values but not drops it.

In this demo case I use empty setState just to demonstrate issue. In real world it is supposed to be meaningfull update. And ms changes in real world could be animation changes.

**What is happening:**
Every child of the ReorderableListView was destroyed and created again with new state. They lost all states.

**Why it is happening (imho):**
Reordable list under the hood wraps children I gave with new widget and assign new keys to that widget. That keys is GlobalObjectKey that use children's I gave keys as inner value.
To check if two GlobalObjectKey object is equal identical is used. And because ValueKey I assign to my tiles every time is new object (with same int inside though) GlobalObjectKey that stores them every time fail equal checks. And flutter destroy my MyListTile widget with state and create new one with initial state.

reorderable_list.dart
```
  // Wraps one of the widget's children in a DragTarget and Draggable.
  // Handles up the logic for dragging and reordering items in the list.
  Widget _wrap(Widget toWrap, int index, BoxConstraints constraints) {
    assert(toWrap.key != null);
    final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(toWrap.key);
    // We pass the toWrapWithGlobalKey into the Draggable so that when a list
    // item gets dragged, the accessibility framework can preserve the selected
    // state of the dragging item.
   ...
    // We pass toWrap with a GlobalKey into the Draggable so that when a list
    // item gets dragged, the accessibility framework can preserve the selected
    // state of the dragging item.
    //
    // We also apply the relevant custom accessibility actions for moving the item
    // up, down, to the start, and to the end of the list.
    return KeyedSubtree(
      key: keyIndexGlobalKey,
      child: MergeSemantics(
        child: Semantics(
            customSemanticsActions: semanticsActions,
            child: toWrap,
         ),
       ),
     );
  }
```

framework.dart
```
@optionalTypeArgs
class GlobalObjectKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
  /// Creates a global key that uses [identical] on [value] for its [operator==].
  const GlobalObjectKey(this.value) : super.constructor();

  /// The object whose identity is used by this key's [operator==].
  final Object value;

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is GlobalObjectKey<T>
        && identical(other.value, value);
  }

  @override
  int get hashCode => identityHashCode(value);

...
}

```

flutter doctor output:
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G4032, locale en-RU)
    • Flutter version 1.17.1 at {$pathToFlutter}
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at {$pathToAndroidSdk}
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 112D9763-364B-48C1-9B0F-BA92AEE6B5F8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

```

**Comment by iKrupp** [comment]
Hi! I ran into the same problem. In my case, I needed to add another child to the list. And with each addition, I get the destruction of all the children of the reorderable list. You may not notice this when all the children in the list are stateless widgets. But in my case, the widgets had a state and animated. What was my surprise when the whole state began to be overwritten after updating the list.

I have repeatedly read that if you do not change the keys and type of widgets, then the framework will take care of saving the state and reusing the element. However, here is behavior that is not expected by the user at all. Any updating of the list, not even aimed at updating the list itself, leads to the complete destruction of the states.

It turns out that I can’t use this list in any builders (both the regular and the stream builders and their various manifestations in the form of BlocBuilder (bloc lib), StoreConnector (redux lib), etc.), I can’t use setState in the parent widget, I can’t even work with InheritedWidget, because he can update everything too. It seems to me that even if, according to the developers, this does not need to be fixed, then at least it’s worth describing the behavior in the documentation.

**Comment by Renesanse** [comment]
Same issue here, I found widgets unnecessary disposing and removing from the tree when setState happened inside StreamBuilder for example. This behaviour is opposite to regular List widget.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.214, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.214 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1d395c5e18 (24 hours ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by iapicca** [comment]
Hi @MariaMelnik @iKrupp @Renesanse 
could you please double check your code with my [code sample](https://dartpad.dartlang.org/7fe4673094698f848520f4440ce7c5f0)
Thank you

**Comment by MariaMelnik** [comment]
@iapicca I think you don't clearly understand how it should work. What you did it is workaround to fix bug.
It should be fixed in framework not by user's workaround.

**Comment by iKrupp** [comment]
@iapicca Hi!
Thank you. I know how I can get around this problem. Another thing is that this is a workaround, not a good solution. It seems to me that it is still necessary to solve this problem on the part of the framework, because this widget does not satisfy the expected behavior that is observed in other widgets.

**Comment by iapicca** [comment]
Hi @MariaMelnik @iKrupp 
the code sample [above](https://github.com/flutter/flutter/issues/58364#issuecomment-640085987)  is not meant to be a workaround, 
but to be demonstrative of the cause of the issue 
which is the approach below  (snippet from your sample)

```dart
 List<Widget> _buildTiles() {
    List<Widget> tiles = data.map((int val) {

      return MyListTile(
        key: ValueKey(val),
        data: val,
        title: "tile $val",
      );
    }).toList();
    return tiles;
  }
}
```
with this approach it is expected that the widget gets rebuilt 
every time the `_buildTiles` function is called,
since said the function is in the `build` function this would happen every `setState`;

this is a common behavior that can be observed, among others in a simple listview,
in this [simplified code sample](https://dartpad.dartlang.org/3cbad0c60ec4bb054625aed3a7b3e45d) you can switch between the 2 approaches and observe the difference in behavior.

Thank you

**Comment by iKrupp** [comment]
Hi @iapicca 
It seems to me that you did not fully understand the problem. The problem is that all list children are DESTROYED when the list is rebuilt. The state of widgets is destroyed. They call dispose, their element is destroyed and deleted from the tree when it should be reused (and, therefore, save its state).
And your WORKAROUND will fix only our examples, and not the gap in general. The list can be reassembled for various reasons (for example, didChangeDependencies is called on the screen.). Moreover, NO ONE widget has changed its key (by value, because we use ValueKey and compare them through ==). This behavior is not expected; the user should not store the list of keys manually. This is a workaround.

**Comment by MariaMelnik** [comment]
@iapicca we told about keep state here but you use Stateless widget (ChronoListTile). 
Of course behaviour will be different.

Let's wait until somebody else check it.
If you know person who can help with it tag here please.

**Comment by iapicca** [comment]
Hi @MariaMelnik
I've updated both code samples with `ChronoListTile` as `StatefulWidget`, these work perfectly.

To better describe the behavior you are experiencing 
run the simple [third code sample](https://dartpad.dartlang.org/cbf27671cbd6cdfe01cc7059cdcca653)
you may observe the following:

1. adding and removing element does not rebuild the existing widgets

2. try moving an element from the middle of the list to the bottom, 
you will notice that the element above the moved item do not rebuild
while the element below are, this is an expected behavior
since all the elements "moved" are destroyed and recreated
as described in the `insert` method

`void insert(int index, E element);`    

> Inserts the object at position [index] in this list.
> This increases the length of the list by one and shifts all objects
>  at or after the index towards the end of the list. [...]

3. the refresh button does not rebuild the widgets

I don't believe that [this](https://dartpad.dartlang.org/7fe4673094698f848520f4440ce7c5f0) is a workaround, but if it is, it's one for the `insert` method which is in [dart](https://github.com/dart-lang/language/issues)'s domain rather than flutter's.

Thank you

**Comment by iapicca** [comment]
Hi @MariaMelnik @iKrupp 
I've updated the [code sample](https://dartpad.dartlang.org/7fe4673094698f848520f4440ce7c5f0) with `ChronoListTile` as `StatefulWidget`
everything works perfectly

I believe my code sample is a correct implementation rather than a workaround;

if you don't like my sample please provide one
where the `List <Widget>` is declared  as variable (or final) 
**instead of generating the list every rebuild**,

I'm fairly confident that with the approach I described
you wont experience the issue

Thank you

**Comment by iKrupp** [comment]
Hi @iapicca 
You are constantly making new workarounds to protect your workaround. This is still not a solution, I insist. There are many examples where you cannot store a widget sheet (and this is wrong in most cases). If you were to use a regular ListView, you would simply not need it. Imagine that you can get a list from the server, then with each update the status would simply be reset, instead of saving it with the same key. But you are still trying to solve the problem on simplified samples without seeing the whole picture. I propose to end this, just leave the problem open, we will wait for someone from the development team or contributors so that they can evaluate this problem themselves. Thanks you.

**Comment by MariaMelnik** [comment]
@iapicca somehow you lost your switcher when changed StatelessWidget to StatefulWidget.
I added: https://gist.github.com/MariaMelnik/5a760b61db67bdc4042db42363076a5e. List won't be rebuild neither switcher on nor off. Flutter works this way.

About workaround:
if you created list to store something it is your choice. But not requirement. 
If you use not required things to make something work and it doesn't work without that things - it is workaround.

**Comment by PixelToast** [comment]
@MariaMelnik Hi, sorry about the confusing comments. Most state issues regarding rebuilds are due to poor state management, its easy to assume the user's code is at fault since the framework is good at implicitly retaining child elements when rebuilt.

I do indeed believe this is a bug in ReorderableListView however, here is an actual test that reproduces it:
```dart
  testWidgets('ReorderableListView preserves child elements when rebuilt', (WidgetTester tester) async {
    void onReorder(old, cur) {}

    Widget build() {
      return MaterialApp(
        home: Directionality(
          textDirection: TextDirection.ltr,
          child: SizedBox(
            width: 100,
            height: 100,
            child: ReorderableListView(
              children: [
                SizedBox(key: Key('key'), width: 10, height: 10),
              ],
              onReorder: onReorder,
            ),
          ),
        ),
      );
    }

    await tester.pumpWidget(build());

    var e0 = tester.element(find.byKey(Key('key')));

    await tester.pumpWidget(build());

    var e1 = tester.element(find.byKey(Key('key')));

    expect(e0, equals(e1));
  });

  testWidgets('ListView preserves child elements when rebuilt', (WidgetTester tester) async {
    void onReorder(old, cur) {}

    Widget build() {
      return MaterialApp(
        home: Directionality(
          textDirection: TextDirection.ltr,
          child: SizedBox(
            width: 100,
            height: 100,
            child: ListView(
              children: [
                SizedBox(key: Key('key'), width: 10, height: 10),
              ],
            ),
          ),
        ),
      );
    }

    await tester.pumpWidget(build());

    var e0 = tester.element(find.byKey(Key('key')));

    await tester.pumpWidget(build());

    var e1 = tester.element(find.byKey(Key('key')));

    expect(e0, equals(e1));
  });
```

Tested on:
```
Flutter 1.19.0-4.0.pre.25 • channel master • https://github.com/flutter/flutter
Framework • revision 37bc900860 (4 days ago) • 2020-06-03 11:26:29 -0700
```

ReorderableListView fails this test but ListView does not.

**Comment by PixelToast** [comment]
I think I have found the culprit, `_ReorderableListContentState._wrap` wraps each widget with a `GlobalObjectKey` to the child corresponding to that child's own key:

```dart
    final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(toWrap.key);
```

This is problematic because `GlobalObjectKey` relies on identity rather than operator==, breaking our assumption that this subtree will be preserved.

The intention of this was to allow the child to be moved in and out of the `SingleChildScrollView` without losing state, but the side-effect is that when a new key instance is provided to a child, regardless of equality, the subtree resets.

**Comment by MariaMelnik** [comment]
@PixelToast thanks!
Yes, I pointed to ```_ReorderableListContentState._wrap``` in first post.

Using such logic makes this widget not so performant as well.
For my purposes I copied this widget and changed creating GlobalObjectKey. 

In ```_ReorderableListContentState``` I added field ``` List<Object> _keysValues;```. 

Changed ```initState``` and ```didUpdateWidget``` to initialize/change it: 
```_keysValues = widget.children.map<Object>((Widget w) => (w.key as ValueKey).value).toList();``` 

And changed ```_wrap``` a little bit to use it:
```    GlobalObjectKey keyIndexGlobalKey;
    if (index < _keysValues.length) {
      keyIndexGlobalKey = GlobalObjectKey(_keysValues[index]);
    } else {
      keyIndexGlobalKey = GlobalObjectKey(toWrap.key);
    }
```

So keys of ReorderableListView children's are kind of respected. But it seems like workaround as well for me. On the other hand GlobalKey looks necessary there and for now I don't know better way to fix it. What do you think?

**Comment by iKrupp** [comment]
@PixelToast hi!
Perhaps it might make sense to create a class that inherits GlobalKey, similar to GlobalValueKey, but with the new == operator behavior (where it would compare by value). Moreover, the key can be private and used only by this list.

**Comment by Hixie** [comment]
Here's a simplified reproduction. To reproduce, run this, and hit "r" for hot reload. Nothing should change, but in practice the hash code of the State changes (which means the widget got destroyed and recreated).

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: OuterTest()));
}

class OuterTest extends StatelessWidget {
  OuterTest({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      children: <Widget>[ InnerTest(key: ValueKey(0)) ],
      onReorder: (_, __) {},
    );
  }
}

class InnerTest extends StatefulWidget {
  InnerTest({ Key key }): super(key: key);

  @override
  _InnerTestState createState() => _InnerTestState();
}

class _InnerTestState extends State<InnerTest> {
  @override
  Widget build(BuildContext context) {
    return Text('$hashCode - should not change in hot reload');
  }
}
```

**Comment by doppio** [comment]
Any thoughts on the correct solution here? Should `ReorderableListView` be using the widget's provided key directly, rather than wrapping it in a new GlobalObjectKey? I'd be happy to submit a pull request for this, but I'm not entirely sure what the right fix is.

**Comment by PixelToast** [comment]
I was considering making a new RenderObject so we can avoid having to move children in and out of sub-trees completely, that would also address any performance concerns.

**Comment by doppio** [comment]
I was looking at the change history for ReorderableListView and it looks like this has been known for some time: https://github.com/flutter/flutter/issues/41334

**Comment by awhitford** [comment]
This is causing **jank** just from _selecting a list item_ -- not even reordering.

**Comment by iapicca** [comment]
@TahaTesser 
running the [code above](https://github.com/flutter/flutter/issues/58364#issuecomment-640290134) with the latest master

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.142, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-6.0.pre.142 at
      /home/francesco/development/flutter_master
    • Framework revision d261f1ef58 (34 hours ago), 2020-08-03 00:59:36 -0400
    • Engine revision 083282e33b
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 365525432a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[!] VS Code
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.105

! Doctor found issues in 3 categories.

```
the issue still occurs
