### ISSUE TITLE
Flutter Web with CanvasKit: Text won't display special characters

### ISSUE THREAD

**Issue by vs-krasnov** [flutter/flutter#58496]
## Steps to Reproduce

1. Add the following `Text` widget:
```
Text("Some characters: ⌘, ⌫"),
```
2. Run `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

**Expected results (DomCanvas):** 
![Flutter Demo - Google Chrome 2020-06-02 17 50 24](https://user-images.githubusercontent.com/13119003/83536194-931b2e00-a4fb-11ea-8c8e-8d6c4170f1a9.png)

**Actual results: (CanvasKit)** 
![Flutter Demo - Google Chrome 2020-06-02 17 51 03](https://user-images.githubusercontent.com/13119003/83536208-97dfe200-a4fb-11ea-8c8d-d0550e8c5970.png)

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale ru-RU)
    • Flutter version 1.18.0-11.1.pre at c:\sdk\flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vs_kr\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\vs_kr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.
```

</details>

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/54330, https://github.com/flutter/flutter/issues/53897

**Comment by yjbanov** [comment]
@hterkelsen can you please triage this? (this should probably be deduplicated with the other issues)

**Comment by yjbanov** [comment]
Reopening as Reopening as https://github.com/flutter/engine/pull/23096 was reverted was rolled back

**Comment by ljmatan** [comment]
@hterkelsen @yjbanov  I'm still having the same issue with latest beta and master

**Comment by woprandi** [comment]
And dev too

**Comment by steffenhaak** [comment]
We are using CanvasKit in production since last fall. For chat messages in our app, we also rely quite heavily on emojis. So far we lived quite well by adding NotoColorEmoji as fontFamilyFallback everywhere where emojs could be part of the text. We also have included an emoji picker for users to add emojis in text fields.

With the current beta release (1.26.0-17.5.pre), the emoji picker now has become unusable, because it takes over a minute to be finally displayed. I can only assume, that the special chars recognition slows down the performance by orders of magnitude.

@hterkelsen @yjbanov I really appreciate your hard work on this issue (!!!)

Is it possible, that you build in a switch (just like the web-renderer option) to configure the emoji/special character recognition?

My proposal would be something like the following:

Add a flag "**special-chars**" to the build command with the following options (or the like):

"**auto**": the current implementation, detecting special chars and auto downloading noto fonts
"**download**": not detecting special chars, but always downloading noto fonts and adding as fallback font
"**included**": not detecting special chars, but expecting noto fonts already included in the bundle and adding them as fallback font
"**off**": not detecting special chars, no font family fallback, for apps that know they won't use special chars / emojis

**Comment by woprandi** [comment]
@ljmatan  I opened new issue : https://github.com/flutter/flutter/issues/76003
