### ISSUE TITLE
Update emulator/simulator profile/release mode restriction to use arch restriction

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#58886]
Instead of attempting to gate release mode on the target device being a simulator/emulator, use a restriction based on supported AOT architectures. This would allow the tool to run release mode on x86_64 emulators today, and on iOS simulators if we decide to upload release artifacts for iOS x86_64

fyi @zanderso

**Comment by helin24** [comment]
Just found this change because I saw the message "Release mode is not supported by iPhone SE (2nd generation)." and was confused about whether I needed to do additional setup steps to be able to run release mode on an iOS device.

It makes sense to be more specific about the device, but can we still give users a hint that their device may be unsupported because it's an emulator?

**Comment by jonahwilliams** [comment]
I could update the messaging to include the device ABI info, and if we think it might be a simulator. In the Android case we can't definitely know something is an emulator, but if we've already failed to run including the output couldn't hurt

**Comment by helin24** [comment]
Yes that would be great!
