### ISSUE TITLE
Improve image memory reporting from engine

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#59016]
Internal: b/160378219

We'd like to
- More accurately report which objects have image memory weight to Dart VM
- Improve collection profiles for image memory allocation
- Avoid overlapping image memory allocations for new images and images that are no longer reachable.

We'll also set a test for image memory measurements to compare between Xcode, DartVM, and maybe adb so we know how accurate our reporting is.

**Comment by liyuqian** [comment]
CC @dnfield . I created this as a sub-issue of https://github.com/flutter/flutter/issues/56486 using the items that we discussed in OKRs.

**Comment by dnfield** [comment]
@liyuqian  - can you help me clarify how this bug is different from #56486 and https://github.com/flutter/flutter/issues/56482? I feel like I'm forgetting something but I'm not sure what :D

**Comment by liyuqian** [comment]
I believe #56486 is a superset of this issue: it includes both #56719 and this issue.

Issue #56482 seems to be a subset of this issue: it corresponds to the 3rd bullet point of this issue -- "Avoid overlapping image memory allocations for new images and images that are no longer reachable".

Does that sound about right? It has been some time since we discussed it around June 8th so my memory could be inaccurate.

**Comment by Hixie** [comment]
Is this still on track for September?

**Comment by dnfield** [comment]
I think I'm going to close this in favor of #56482.

For the first bullet point, we've come to realize that we should only report the image itself as having image memory to the Dart VM, because doing otherwise regressed performance and creates confusion in the memory dumps from Dart.

For the second two, they should be resolved by the linked bug. We'll be making sure to hint the VM to do a GC when image memory disposal happens (see https://github.com/flutter/engine/pull/20754). That's as close as we'll be able to get to avoiding overlapping allocations.
