### ISSUE TITLE
Pre-commit luci mac tasks timed out due to limited mac bots in the try pool

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#59036]
On Jun 5th, there were tasks pending in pool `luci.flutter.try` for almost 3 hours, causing test failure. This happened mainly on bots with OS: Mac-10.14.6. This further caused **Engine** build failure.

Active tasks and max pending time for Jun. 5th.
<img width="1116" alt="Screen Shot 2020-06-08 at 5 25 31 PM" src="https://user-images.githubusercontent.com/54558023/84092717-14b40580-a9ad-11ea-8a1c-78fb1615b784.png">

Bots (Mac-10.14.6) status over that time period
<img width="1122" alt="Screen Shot 2020-06-08 at 5 24 54 PM" src="https://user-images.githubusercontent.com/54558023/84092686-fbab5480-a9ac-11ea-9be5-59d5aa20b8c8.png">

We can see from above charts that Mac bots were fully occupied for most of time of the day, and caused task pending/scheduling timeout.

Extra bots seem to be needed.

**Comment by godofredoc** [comment]
We implemented several improvements:

* Removed unnecessary builders.
* Enabled caching for the two versions of xcode used by ios builds.
* Prevented unnecessary retries caused by flakiness of three builders (try-1-3)
* Added a retry for bot_update to checkout source code to prevent flakiness associated with source checkout.
