### ISSUE TITLE
Will the flutter support a layout similar to Android ConstraintLayout with a visual editor, That would be great!

### ISSUE THREAD

**Issue by zeplee** [flutter/flutter#59040]
Will the flutter support a layout similar to Android ConstraintLayout with a visual editor,
That would be great! It will greatly reduce the number of unaccountable UI errors, for example, sometimes reporting errors is simply a matter of using fewer widgets. And this feature makes layout easier, so developers don't have to worry about a lot of widgets

**Comment by TahaTesser** [comment]
Hi @LeeZepeng 
Flutter doesn't have its own IDE, where you would suggest to have this visual editor?
Would it possible in VS Code and Android Studio plugin?

**Comment by zeplee** [comment]
Thanks for your reply, both tools are available as plugins

**Comment by zeplee** [comment]
> Hi @LeeZepeng
> Flutter doesn't have its own IDE, where you would suggest to have this visual editor?
> Would it possible in VS Code and Android Studio plugin?

Thanks for your reply, both tools are available as plugins

**Comment by iapicca** [comment]
Hi @zeplee 
your proposal seems to be directed to an ide rather than flutter framework;
you may want to open an issue on flutter's [vs code plugin github](https://github.com/Dart-Code/Dart-Code/issues)  or [android studio github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
