### ISSUE TITLE
FilteringTextInputFormatter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#59099]
We should create a FilteringTextInputFormatter that takes a filter Pattern and an "allow" flag that controls if the filter is an allow list or a block list.

Then we can make BlacklistingTextInputFormatter and WhitelistingTextInputFormatter inherit from this class, with the constructor passing in the pattern and the flag appropriately, and with the properties unique to each just forwarding on to the filter pattern. And we can @deprecate these classes.

**Comment by jmewes** [comment]
Maybe `WhitelistingTextInputFormatter` and `BlacklistingTextInputFormatter` could also be replaced with functionally equivalent classes, e.g. `MatchingTextInputFormatter` and `BlockingTextInputFormatter`.

**Comment by pedromassango** [comment]
> Maybe `WhitelistingTextInputFormatter` and `BlacklistingTextInputFormatter` could also be replaced with functionally equivalent classes, e.g. `MatchingTextInputFormatter` and `BlockingTextInputFormatter`.

I think a single class is better, so we don't need to remember both classes names. The proposed changes is good, but maybe `FilteringTextInputFormatter` should receive `match` and `block` parameter and only one of then should be `true` because these names are more self-explanatory than the proposed `allow` name.

**Comment by Hixie** [comment]
@pedromassango In the PR I actually provided constructors along those lines.
