### ISSUE TITLE
[pigeon] support non-null types

### ISSUE THREAD

**Issue by xster** [flutter/flutter#59118]
If the schema declares nullability in fields and methods, translate them to Dart and platform generated code.

**Comment by iapicca** [comment]
as requested in [pigeon feedback](https://pub.dev/packages/pigeon#feedback) cc @gaaclarke

**Comment by fzyzcjy** [comment]
This is very much needed - Since now null safety is a **stable** release (not a beta one any more)! So when will we have null safety for pigeon?

**Comment by fzyzcjy** [comment]
If I make a PR, will it be accepted?

**Comment by matejdro** [comment]
From what I see, there is currently no way to even declare non-nullable pigeons?

Pigeon compiler complains about `pigeons.dart:117:10: Error: Field 'X' should be initialized because its type 'String' doesn'tallow null.`

**Comment by gaaclarke** [comment]
> So when will we have null safety for pigeon?

Pigeon supports null safety with the `--dart_null_safety` flag.  What it doesn't support is non-null types, which is what this issue is tracking.  We should probably try to do something to automatically set that flag, too.

> If I make a PR, will it be accepted?

PR's have been accepted from contributors that did good work, who were responsive to feedback and patient.

**Comment by fuzzybinary** [comment]
I've been looking into this and it feels like it's probably a multi-step process to support non-null types, since it drastically changes how pigeon would create, serialize and deserialize types. That would likely mean multiple PRs to get everything accomplished.

This was my thoughts on the process

1. Support constructors - when an unnamed constructor for a class is defined in the Pigeon, it should generate a constructor in Dart and in client platforms. These don't have to be used by any other generated code initially.
2. Switch decoding (decode / fromMap) to support using constructors when available
4. Support default values in field declarations and constructor arguments. Modify decode / fromMap to check for nil and replace with default values.
3. (Unrelated, nice to have) - Support and translate "final" fields in Dart. Generate proper syntax for client libraries for readonly properties (At this point we'll have satisfied everything needed to make https://github.com/flutter/flutter/issues/58904 possible)
4. Support generating null and non-null field and return types. Having constructor support should make this easier as anyone creating non-null fields will need to supply a constructor in Dart.

Does that sound like the correct process? Does it hit everything? Are the tasks here small enough to be doable / reviewable and potentially not break downstream work?

**Comment by stuartmorgan** [comment]
This is largely complete, and was just never closed, so closing. Specific missing pieces (e.g., non-nullable generics) have their own tracking issues already.
