### ISSUE TITLE
[Linux/Windows] TextEditingController.clear() doesn't actually clear the TextField's text

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#59140]
## Steps to Reproduce

Using the latest Flutter SDK and GTK embedding, I confirmed the TextField widget. Pressing the button once doesn't actually clear the text. To clear the text, you need to press twice the button.

GLFW embedding is the same.

1. Enter to some characters in the TextField.
2. Click clear button.
3. Enter to a character in the TextField.

![bug_report1](https://user-images.githubusercontent.com/62131389/84243093-ad2cc000-ab3c-11ea-8a79-adb0981cf113.gif)

Sample code
```
class _MyTextField extends StatelessWidget {
  var _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Textfield test'),
      ),
      body: Center(
        child: TextField(
          controller: _controller,
          decoration: InputDecoration(
            hintText: 'Linux text input test',
            suffixIcon: IconButton(
              onPressed: () => _controller.clear(),
              icon: Icon(Icons.clear),
            ),
          ),
        ),
      ),
    );
  }
}
```

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-6.0.pre.42, on Linux, locale ja_JP.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by iapicca** [comment]
Hi @HidenoriMatsubayashi 
testing your code with the latest master 

 francesco@francesco-yoga720  ~/projects/linux_test  flutter_master run -d linux -v                                                                                                   ✔  1450  12:37:58 
[ +118 ms] executing: [/home/francesco/development/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d9653445f4d1257b5f5adb4b271d1316469e8cf1
[        ] executing: [/home/francesco/development/flutter_master/] git tag --contains HEAD
[ +284 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/home/francesco/development/flutter_master/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-5.0.pre-42-gd9653445f
[   +8 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/francesco/development/flutter_master/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +41 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: /usr/lib/Android/platform-tools/adb devices -l
[  +41 ms] List of devices attached
[  +10 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +214 ms] Generating /home/francesco/projects/linux_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +73 ms] Starting incremental build...
[   +2 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/francesco/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/development/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/francesco/development/flutter_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tools.MMDKPT/flutter_tool.BAICCR/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +22 ms] Building Linux application...
[  +10 ms] <- compile package:linux_test/main.dart
[   +2 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/francesco/projects/linux_test/linux
[ +531 ms] -- The CXX compiler identification is Clang 6.0.0
[   +9 ms] -- Check for working CXX compiler: /usr/bin/clang++
[ +166 ms] -- Check for working CXX compiler: /usr/bin/clang++ -- works
[   +2 ms] -- Detecting CXX compiler ABI info
[ +149 ms] -- Detecting CXX compiler ABI info - done
[   +5 ms] -- Detecting CXX compile features
[ +852 ms] -- Detecting CXX compile features - done
[   +6 ms] -- Configuring done
[  +11 ms] -- Generating done
[   +7 ms] -- Build files have been written to: /home/francesco/projects/linux_test/build/linux/debug
[  +32 ms] executing: ninja -C build/linux/debug install
[  +27 ms] ninja: Entering directory `build/linux/debug'
[+18726 ms] [1/15] Generating /home/francesco/projects/linux_test/linux/flutter/ephemeral/libflutter_linux_glfw.so, flutter_export.h, flutter_glfw.h, flutter_messenger.h, flutter_plugin_registrar.h,
/home/francesco/projects/linux_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc,
/home/francesco/projects/linux_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc,
/home/francesco/projects/linux_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc,
/home/francesco/projects/linux_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc,
/home/francesco/projects/linux_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc, _phony_
[   +6 ms] [ +284 ms] executing: [/home/francesco/development/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] d9653445f4d1257b5f5adb4b271d1316469e8cf1
[        ] [        ] executing: [/home/francesco/development/flutter_master/] git tag --contains HEAD
[        ] [ +379 ms] Exit code 0 from: git tag --contains HEAD
[        ] [   +2 ms] executing: [/home/francesco/development/flutter_master/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [  +24 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [        ] 1.19.0-5.0.pre-42-gd9653445f
[   +2 ms] [  +15 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/francesco/development/flutter_master/] git ls-remote --get-url origin
[        ] [   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +68 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref HEAD
[        ] [  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +72 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +62 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +126 ms] Initializing file store
[        ] [  +25 ms] Skipping target: gen_localizations
[        ] [   +2 ms] unpack_linux: Starting due to {}
[        ] [ +861 ms] unpack_linux: Complete
[        ] [  +61 ms] kernel_snapshot: Starting due to {}
[        ] [  +52 ms] /home/francesco/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/development/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/francesco/development/flutter_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --packages
/home/francesco/projects/linux_test/.packages --output-dill /home/francesco/projects/linux_test/.dart_tool/flutter_build/41b6e5f253301e53c0ea94382f009b49/app.dill --depfile
/home/francesco/projects/linux_test/.dart_tool/flutter_build/41b6e5f253301e53c0ea94382f009b49/kernel_snapshot.d package:linux_test/main.dart
[   +3 ms] [+13809 ms] kernel_snapshot: Complete
[        ] [ +676 ms] debug_bundle_linux_assets: Starting due to {}
[        ] [ +164 ms] debug_bundle_linux_assets: Complete
[        ] [ +775 ms] Persisting file store
[        ] [  +10 ms] Done persisting file store
[        ] [   +9 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 16,694ms.
[        ] [   +4 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +309 ms] [2/15] Building CXX object CMakeFiles/linux_test.dir/window_configuration.cc.o
[ +522 ms] [3/15] Building CXX object CMakeFiles/linux_test.dir/flutter/generated_plugin_registrant.cc.o
[ +553 ms] [4/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o
[ +288 ms] [5/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o
[  +90 ms] [6/15] Building CXX object CMakeFiles/linux_test.dir/main.cc.o
[ +510 ms] [7/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o
[  +10 ms] [8/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o
[ +197 ms] [9/15] Linking CXX static library flutter/libflutter_wrapper_plugin.a
[ +243 ms] [10/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o
[ +125 ms] [11/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o
[ +125 ms] [12/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o
[  +36 ms] [13/15] Linking CXX static library flutter/libflutter_wrapper_app.a
[ +215 ms] [14/15] Linking CXX executable linux_test
[        ] [14/15] Install the project...
[  +15 ms] -- Install configuration: "Debug"
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test
[   +1 ms] -- Set runtime path of "/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test" to "$ORIGIN"
[   +4 ms] -- fixup_bundle
[        ] --   app='/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test'
[        ] --   libs=''
[        ] --   dirs=';/home/francesco/projects/linux_test/linux/flutter/ephemeral'
[        ] --   ignoreItems=''
[  +15 ms] -- fixup_bundle: preparing...
[  +65 ms] -- fixup_bundle: copying...
[        ] -- 1/4: *NOT* copying '/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test'
[        ] -- 2/4: copying '/home/francesco/projects/linux_test/linux/flutter/ephemeral/libflutter_linux_glfw.so'
[ +538 ms] -- fixup_bundle: fixing...
[        ] -- 3/4: fix-up not required on this platform '/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test'
[        ] -- 4/4: fix-up not required on this platform '/home/francesco/projects/linux_test/build/linux/debug/bundle/libflutter_linux_glfw.so'
[        ] -- fixup_bundle: cleaning up...
[        ] -- fixup_bundle: verifying...
[   +5 ms] -- ===========================================================================
[        ] -- Analyzing app='/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test'
[        ] -- bundle='/home/francesco/projects/linux_test/build/linux/debug/bundle'
[        ] -- executable='/home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test'
[        ] -- valid='1'
[  +11 ms] -- executable file 1: /home/francesco/projects/linux_test/build/linux/debug/bundle/linux_test
[  +58 ms] -- verified='1'
[        ] -- info='Verified 1 executable files in '/home/francesco/projects/linux_test/build/linux/debug/bundle''
[        ] -- 
[        ] -- verified='1'
[        ] -- info=''
[        ] -- 
[        ] -- fixup_bundle: done
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/icudtl.dat
[   +5 ms] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/fonts
[   +1 ms] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.ttf
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +33 ms] -- Installing: /home/francesco/projects/linux_test/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[  +17 ms] Building Linux application... (completed in 24.6s)
[ +809 ms] Observatory URL on device: http://127.0.0.1:40345/vd3G2aTYess=/
[  +23 ms] Caching compiled dill
[ +131 ms] Connecting to service protocol: http://127.0.0.1:40345/vd3G2aTYess=/
[ +228 ms] Successfully connected to service protocol: http://127.0.0.1:40345/vd3G2aTYess=/
[        ] Waiting for Linux to report its views...
[   +6 ms] Waiting for Linux to report its views... (completed in 5ms)
[  +12 ms] DevFS: Creating new filesystem on the device (null)
[  +23 ms] DevFS: Created new filesystem on the device (file:///tmp/linux_testBHZTCO/linux_test/)
[   +5 ms] Updating assets
[ +115 ms] Syncing files to device Linux...
[   +1 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:linux_test/main.dart 0adc32d0-513f-4472-8b1e-dc6b306b4c6a
[        ] <- 0adc32d0-513f-4472-8b1e-dc6b306b4c6a
[ +160 ms] Updating files
[ +107 ms] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 274ms)
[        ] Synced 0.9MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x1bf5a50.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:40345/vd3G2aTYess=/
[+70839 ms] DevFS: Deleting filesystem on the device (file:///tmp/linux_testBHZTCO/linux_test/)
[  +15 ms] DevFS: Deleted filesystem on the device (file:///tmp/linux_testBHZTCO/linux_test/)
[  +50 ms] Service protocol connection closed.
[        ] Application finished.
[   +3 ms] "flutter run" took 97,587ms.
[   +3 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0

[✓] Flutter (Channel master, 1.19.0-6.0.pre.42, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-6.0.pre.42 at /home/francesco/development/flutter_master
    • Framework revision d9653445f4 (11 hours ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Linux      • Linux      • linux-x64      • Linux
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

! Doctor found issues in 1 category.

I can reproduce the behavior you are describing
thank you
