### ISSUE TITLE
Improved 60hz testing

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5915]
We currently have a transitions test for the gallery:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test_driver/transitions_perf_test.dart

Which currently tracks the duration of the first frame after a transition is started:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/item.dart#L34

To better know "are we 60hz" I'd like us to track slightly different metrics.  Specifically:
1.  Time from Start Transition (user interaction) to completion of first frame.  (Target: <150ms)
2.  Duration of second frame (we do heros here and should track it separately). (Target: <15ms)
3.  Max duration of all subsequent frames during transition. (Target: <15ms)

@abarth @HansMuller @yjbanov

**Comment by yjbanov** [comment]
Is it possible to identify key frames in hero transitions, such as "hero departed", "hero arrived"? We could then mark and measure these frames separately from others. We could also test that such frames happen at the right time (e.g. that frame number 2 is really a "hero departed" frame).

**Comment by Hixie** [comment]
Heroes use the same AnimationController as page transitions, so there's no special frames. In frame 0 they render with an offset of zero, in frame 1 they render with an offset of x%, in frame N they render with an offset of 100%. where the offset is the distance from the start to the end.

The only thing that's special about frame 0 vs frame 1 is that in frame 0 we render the target page in its final state (but invisibly) so that we can measure the hero target locations. (We should probably change how we do this to handle things like moving targets when scrolling.)

But I disagree that the first frame (frame 0) can be more than 16ms (even if less than 150ms). Any jank on that frame is still visible if the page has any ongoing animations. We have to hit <16ms on every single frame, even the first frame of a transition, if we're to have 60Hz animations.

**Comment by Hixie** [comment]
It's not clear that tracking these separately will actually be particularly useful. We are tracking the transition perf for the gallery and have an outstanding work item to address perf issues there, at which point we can write special benchmarks as we deem necessary.
