### ISSUE TITLE
Temporarily provide API for enabling mirrors

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#59233]
The Linux shell doesn't currently provide any `command_line_args` to the Flutter engine or provide any API for an app author to do so.

**Comment by stuartmorgan** [comment]
This exists in the current desktop embeddings for legacy reasons; the goal is not to expose it. There's only one internal use case that still might require this; I need to check if that's still necessary.

**Comment by robert-ancell** [comment]
> This exists in the current desktop embeddings for legacy reasons; the goal is not to expose it. There's only one internal use case that still might require this; I need to check if that's still necessary.

Ah good. I don't have a reason to add this feature other than the existing bindings did it. So please close this issue if it's not necessary.

**Comment by stuartmorgan** [comment]
I checked, and this is still needed. However, rather than allow arbitrary flags and encourage people to potentially rely on this for other things, let's just add a temporary affordance for the specific thing that's needed (retitling accordingly).

So what we need is an `FlDartProject` option for enabling mirrors which, when set, causes the engine initialization to pass `--dart-flags=--enable_mirrors=true` as an argument.

**Comment by stuartmorgan** [comment]
@robert-ancell Assigning to you since I assume you're the best person to do this, but if you don't have cycles you can assign it to me.
