### ISSUE TITLE
in_app_purchase 0.3.4 is not working in EU countries showing grey screen while fetching subscription packages.!!

### ISSUE THREAD

**Issue by sagar440** [flutter/flutter#59242]
Hi all, i am facing the issue on android and ios both i.e. i am not able to fetch subscription package(monthly, 6 month and yearly) in other country(tested in France) it is showing a full grey screen. Although i have published app on play store ( [https://play.google.com/store/apps/details?id=com.deligence.noji](url) ) it is working fine on my devices android (6,7,8,9,10) version in india. and  i am also not able to reproduce this issue. Suggestions will appreciated in advance. 
you people can checkout above application link for test subscription page. if anyone know something about this issue please help and i also want to know it is working fine in your device or showing grey screen error.

**On setting tab press "Compte"**

![Screenshot_20200611_124142](https://user-images.githubusercontent.com/58718920/84356218-82e10e00-abe1-11ea-9cc9-c79a176f3db7.jpg)

**After that press "ABONNEZ-VOUS!" button**

![Screenshot_20200611_124150](https://user-images.githubusercontent.com/58718920/84356207-81174a80-abe1-11ea-9d12-2fe0776b68a3.jpg)
 
**Can you see packages (monthly , 6 Month, Yearly)**
on this page it is showing grey screen in france. 

![Screenshot_20200611_124156](https://user-images.githubusercontent.com/58718920/84356181-79f03c80-abe1-11ea-99f1-09e520edee2f.jpg)

Please help, i am searching for the solution from last 4 days.

**Comment by TahaTesser** [comment]
Hi @sagar440 
Since this is working in India, i am not sure `in_app_purchase` issue for EU countries.
check withhttps://developer.android.com/google/play/billing and contact support if needed.


This platform is not meant for assistance on personal code. 
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
