### ISSUE TITLE
web_benchmarks_html text_canvas_cached_layout.html.layout.average and text_canvas_color_grid.html.text_layout.average regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59339]
Looks like roll https://github.com/flutter/flutter/pull/59222.

![Screen Shot 2020-06-12 at 8 51 04 AM](https://user-images.githubusercontent.com/1435716/84524905-9054d180-ac8f-11ea-8539-295de834709f.png)

This is the same roll as implicated in https://github.com/flutter/flutter/issues/59335, but they may not be related.

**Comment by yjbanov** [comment]
Reducing priority because canvas-based text layout is under experiment flag.

**Comment by mdebbar** [comment]
The increase in `text_canvas_color_grid.html.text_layout.average` is expected, though it's higher than I saw on my laptop. The reason I was okay with it is because the actual effect on the app was not significant.

That being said, I have a few [ideas](https://github.com/flutter/engine/pull/18795#discussion_r436857500) that will help here.

**Comment by Hixie** [comment]
> the actual effect on the app was not significant.

If the benchmark is not representative, please change the benchmark.

**Comment by hterkelsen** [comment]
Reducing to P4 because this is not a customer critical issue. This is a performance regression of an experimental feature that is under active development.
