### ISSUE TITLE
TextField semantics are gone when being disabled

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#59402]
b/158725443
b/239596152

This might be WAI but it is inconsistent.

Dropdown buttons still have a Semantic widget associated with them when they are disabled but it seems we remove the Semantic widget when TextField is disabled.

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by chunhtai** [comment]
This is a known issue, the problem is that the TextField uses IgnorePointer to disable pointer interaction when the textfield is disabled, and the ignore pointer will unfortunately disable the semantics. I have a draft pr that exploring the possible way to fix it https://github.com/flutter/flutter/pull/37199, but it was abandon due to low priority. Does the [read only](https://master-api.flutter.dev/flutter/material/TextField/readOnly.html) work in your case? The difference between them is the read only textfield can still be selected.

The dropdown button works differently because it only has one gesture detector, we can easily disable it by detaching the callback. The Textfield however has three to four layer of gesture detector across widget and render object, we figure it will be easier to just use ignorePointer. Maybe that is not a wise decision.

**Comment by chunhtai** [comment]
@mehmetf Is fixing the semantics necessary to resolve the issue given my comment above?

**Comment by mehmetf** [comment]
@chunhtai I pinged the customer. However, if you want a speedier response from Googlers, I suggest pinging on the internal bug.

**Comment by chunhtai** [comment]
Will get back to this once i have time
