### ISSUE TITLE
Flutter Windows build broken after accidentally running command in WSL 2

### ISSUE THREAD

**Issue by rolznz** [flutter/flutter#59455]
## Steps to Reproduce

1. Install Flutter on Windows and verify it is working correctly (e.g. with flutter doctor)
2. Run `flutter build apk --release` in WSL 2 bash instead of powershell
3. Try to run any Flutter command inside Powershell (e.g. `flutter doctor`)

Ideally it should detect that we're running in the wrong shell and exit immediately, rather than breaking my flutter folder.

## Logs

```
The system cannot find the path specified.
```

**Comment by TahaTesser** [comment]
Hi @rolznz 
I recommend you reinstall Flutter setup since WSL 2 isn’t supported yet and it might not work as expected.

Please see https://github.com/flutter/flutter/issues/42521#issuecomment-622570307

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, i will reopen it 
Thank you
