### ISSUE TITLE
Set default MouseCursor in ButtonThemeData

### ISSUE THREAD

**Issue by JonLatane** [flutter/flutter#59575]
## Use case

The new "clickable" mouseCursor is inappropriate and confusing for desktop apps, and the implementation of defaulting to a static const in every widget using cursors means a single point of responsibility for cursor behavior is not accessible to developers.

The default `mouseCursor` for any widgets using it should be in `ButtonThemeData`, not a hardcoded `const`.

## Proposal

`ButtonThemeData.mouseCursor` field is added, and all buttons and other Widgets in a given `BuildContext` using `MaterialStateMouseCursor.clickable` instead use `ButtonTheme.of(context).mouseCursor`.

Relates to https://github.com/flutter/flutter/issues/31952

**Comment by dkwingsmt** [comment]
I agree that we should be able to customize cursors globally in theming. 

@HansMuller Do you think it's ok to add these APIs despite the ongoing [theming update](flutter.dev/go/material-theme-system-updates)?

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/59702, which - if all goes well - should land in the next week or so, adds mouse cursor support to the new (replacement) button classes and their themes.  I'd really prefer to not make additional changes to ButtonTheme because that's what we're trying to leave behind. However, I think it it would make sense for Theme/ThemeData to define an overall default mouse cursor.

**Comment by JonLatane** [comment]
Woohoo! Wasn't aware of this pending change. Looks good to me so far. Thank you!

**Comment by gspencergoog** [comment]
@HansMuller should this issue be closed?

**Comment by HansMuller** [comment]
Yes, I'm going to close this issue. The new buttons define default mouse cursors and one can override the mouse cursor using a constructor parameter or a theme -  https://flutter.dev/go/material-button-system-updates.
