### ISSUE TITLE
Introduction of characters package causes crash on `flutter run` for preexisting Flutter applications

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#59645]
After e0ed12c73a3df00b72af6e5657d35035a76c90db I get this error when building:
```log
[        ] [ +566 ms] Error: Could not resolve the package 'characters' in 'package:characters/characters.dart'.
[        ] [ +215 ms] ../../flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
[        ] [        ] import 'package:characters/characters.dart';
[        ] [        ]        ^
[        ] [ +261 ms] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
[        ] [        ] import 'package:characters/characters.dart';
[        ] [        ]        ^
[  +37 ms] [  +96 ms] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
[        ] [        ] import 'package:characters/characters.dart';
[        ] [        ]        ^
[+3398 ms] [+3415 ms] ../../flutter/packages/flutter/lib/src/material/text_field.dart:801:61: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]   int get _currentLength => _effectiveController.value.text.characters.length;
[        ] [        ]                                                             ^^^^^^^^^^
[        ] [   +2 ms] ../../flutter/packages/flutter/lib/src/material/text_field.dart:855:43: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]       if (_effectiveController.value.text.characters.length > widget.maxLength) {
[        ] [        ]                                           ^^^^^^^^^^
[+1698 ms] [+1665 ms] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:243:64: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]        assert(obscuringCharacter != null && obscuringCharacter.characters.length == 1),
[        ] [        ]                                                                ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:358:35: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]     assert(value != null && value.characters.length == 1);
[        ] [        ]                                   ^^^^^^^^^^
[        ] [   +2 ms] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:564:11: Error: 'Characters' isn't a type.
[        ] [        ]     final Characters remaining = string.characters.skipWhile((String currentString) {
[        ] [        ]           ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:564:41: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]     final Characters remaining = string.characters.skipWhile((String currentString) {
[        ] [        ]                                         ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:572:42: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]       return _isWhitespace(currentString.characters.first.toString().codeUnitAt(0));
[        ] [        ]                                          ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:597:47: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]     for (final String currentString in string.characters) {
[        ] [        ]                                               ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/rendering/editable.dart:599:40: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]           !_isWhitespace(currentString.characters.first.toString().codeUnitAt(0))) {
[        ] [        ]                                        ^^^^^^^^^^
[ +495 ms] [ +466 ms] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:180:11: Error: 'CharacterRange' isn't a type.
[        ] [        ]     final CharacterRange iterator = CharacterRange(value.text);
[        ] [        ]           ^^^^^^^^^^^^^^
[        ] [   +2 ms] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:180:37: Error: Method not found: 'CharacterRange'.
[        ] [        ]     final CharacterRange iterator = CharacterRange(value.text);
[        ] [        ]                                     ^^^^^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:181:20: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]     if (value.text.characters.length > maxLength) {
[        ] [        ]                    ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:200:61: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]     if (maxLength != null && maxLength > 0 && newValue.text.characters.length > maxLength) {
[        ] [        ]                                                             ^^^^^^^^^^
[        ] [        ] ../../flutter/packages/flutter/lib/src/services/text_formatter.dart:203:25: Error: The getter 'characters' isn't defined for the class 'String'.
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
[        ] [        ]       if (oldValue.text.characters.length == maxLength) {
[        ] [        ]                         ^^^^^^^^^^
```
@justinmc

**Comment by raviganwal** [comment]
Same issue I am facing

**Comment by gtrompet** [comment]
Installing https://pub.dev/packages/characters solved the problem for me.

**Comment by shihaohong** [comment]
I quickly tested this on a sample app and got the same issue. Here is my stack trace for my first `flutter run`.

<details>
<summary>First Stack Trace</summary>

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Error: Could not resolve the package 'characters' in 'package:characters/characters.dart'.
../../flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../flutter/packages/flutter/lib/src/material/text_field.dart:801:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
  int get _currentLength => _effectiveController.value.text.characters.length;
                                                            ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/material/text_field.dart:855:43: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      if (_effectiveController.value.text.characters.length > widget.maxLength) {
                                          ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:243:64: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
       assert(obscuringCharacter != null && obscuringCharacter.characters.length == 1),
                                                               ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:358:35: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    assert(value != null && value.characters.length == 1);
                                  ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:564:11: Error: 'Characters' isn't a type.
    final Characters remaining = string.characters.skipWhile((String currentString) {
          ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:564:41: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    final Characters remaining = string.characters.skipWhile((String currentString) {
                                        ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:572:42: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      return _isWhitespace(currentString.characters.first.toString().codeUnitAt(0));
                                         ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:597:47: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    for (final String currentString in string.characters) {
                                              ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/rendering/editable.dart:599:40: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
          !_isWhitespace(currentString.characters.first.toString().codeUnitAt(0))) {
                                       ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:180:11: Error: 'CharacterRange' isn't a type.
    final CharacterRange iterator = CharacterRange(value.text);
          ^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:180:37: Error: Method not found: 'CharacterRange'.
    final CharacterRange iterator = CharacterRange(value.text);
                                    ^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:181:20: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (value.text.characters.length > maxLength) {
                   ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:200:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (maxLength != null && maxLength > 0 && newValue.text.characters.length > maxLength) {
                                                            ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_formatter.dart:203:25: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      if (oldValue.text.characters.length == maxLength) {
                        ^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acharacters%2Fcharacters.dart; message=StandardFileSystem only supports file:* and data:* URIs)
[38;5;248m#0      StandardFileSystem.entityForUri  (package:front_end/src/api_prototype/standard_file_system.dart:33:7)[39;49m
[38;5;248m#1      asFileUri  (package:vm/kernel_front_end.dart:626:37)[39;49m

[38;5;248m#2      writeDepfile  (package:vm/kernel_front_end.dart:820:21)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#3      FrontendCompiler.compile  (package:frontend_server/frontend_server.dart:566:15)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#4      _FlutterFrontendCompiler.compile  (package:flutter_frontend_server/server.dart:40:22)[39;49m
[38;5;248m#5      starter  (package:flutter_frontend_server/server.dart:178:27)[39;49m
[38;5;248m#6      main  (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)[39;49m
[38;5;244m#7      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:299:32)[39;49m
[38;5;244m#8      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m




FAILURE: Build failed with an exception.
* Where:
Script '/Users/shihaohong/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/shihaohong/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exited (sigterm)
Exception: Gradle task assembleDebug failed with exit code 1
```

</details>

On a subsequent attempt to `flutter run`, I saw this at the beginning of the stack trace, followed by the contents of the first stack trace:
```
Invalid depfile: /Users/shihaohong/dev/apps/test_tab_animation/.dart_tool/flutter_build/2094b875432a5b46b5b5cc10f81d4205/kernel_snapshot.d
Invalid depfile: /Users/shihaohong/dev/apps/test_tab_animation/.dart_tool/flutter_build/2094b875432a5b46b5b5cc10f81d4205/kernel_snapshot.d
```
Based on a hunch, I deleted the `.dart_tool` directory from the sample Flutter application and tried `flutter run` again, and it ended up working. It might be an issue with the flutter tool's cache? That being said, maybe we should revert the `characters` package PR until we figure out what's going on.

cc/ @justinmc @jonahwilliams

**Comment by Hardikkr** [comment]
Can't understand this error

**Comment by jmolins** [comment]
In my case, I resolved the issue with `flutter clean`

**Comment by jld3103** [comment]
That works, but still this needs to be fixed.

**Comment by justinmc** [comment]
Revert here for additional reasons: https://github.com/flutter/flutter/pull/59677

I'll come up with a plan for this when I reland it.

**Comment by justinmc** [comment]
The usage of the new characters package has been reverted (https://github.com/flutter/flutter/pull/59677).

If anyone on the master channel updates Flutter after the time this comment was posted and still sees this problem, please let me know.  The addition of the characters dependency is still in master, it's just not used right now, but that does seem to have fixed the problem for me.

I will keep this issue open as I look for a long term solution so I can unrevert.

**Comment by jonahwilliams** [comment]
If you've hit this issue, could you provide the full verbose logs and the command you've run?

Flutter should automatically run `pub get` for you, but its possible there are some code paths where this is not possible (i.e. directly through build/gradle). In that case we need to detect the stale pubspec and exit, not crash with a compiler error.

**Comment by jonahwilliams** [comment]
It sounds like @justinmc reproduced it, so we should be able to find the reason

**Comment by justinmc** [comment]
Repro steps:

  1. Check out a commit before the characters package was added. `git checkout 77859c682edbcc6a8af772dcf79d46b3786f10f9^`
  1. Create a new project somewhere with `flutter create <project name>`.
  1. Run the project with `flutter run`.
  1. Check out a commit after characters began being used, but before it was reverted. `git checkout a99d146ba98a62baeb091fcc31e47ce0923ee121^`
  1. Try to run the project you created again with `flutter run`.

You should get a bunch of errors about being unable to find the characters package.

**Comment by Hardikkr** [comment]
I have added this code below in my "pubspec.lock" and it resolved the problem.
`characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"`

**Comment by jonahwilliams** [comment]
I'll try this again tomorrow, my current theory is that there is a difference depending on whether there are additional experimental platforms enabled

**Comment by justinmc** [comment]
Use of the characters package has landed again in https://github.com/flutter/flutter/pull/59778, so this problem may reappear in existing projects.  See above for how to fix it.

**Comment by jld3103** [comment]
Upgraded flutter and everything works normal again. The error doesn't happen again

**Comment by mehrdad-shokri** [comment]
This happened to me after upgrading flutter, running ``flutter clean`` solved it for me

**Comment by Lalit0725** [comment]
Even after flutter clean, its still showing error for me.

**Comment by Nishtha3512** [comment]
Thanks @gtrompet .I download it and solve my issue.

**Comment by kokocooler2020** [comment]
I fix it by command: flutter pub get.

**Comment by manulsan** [comment]
It caused by upgrade flutter and compiled stuffs that is made by previous flutter
so 
just  do as below  ==> "flutter clean"
and recompile it   "flutter run "
To me , this issue is cleaned by do "flutter clean"

**Comment by shabeenabarde** [comment]
> The usage of the new characters package has been reverted (#59677).
> 
> If anyone on the master channel updates Flutter after the time this comment was posted and still sees this problem, please let me know. The addition of the characters dependency is still in master, it's just not used right now, but that does seem to have fixed the problem for me.
> 
> I will keep this issue open as I look for a long term solution so I can unrevert.

I shifted from flutter stable to flutter master and still facing this issue.

**Comment by natgross** [comment]
Upgraded flutter today, and exactly this problem came up.
Per advice of @manulsan, I simply ran 'flutter clean', and all is ok.

**Comment by muralikumarch** [comment]
Yes. Its works.

"flutter clean"

"flutter run"

**Comment by Shubhamr837** [comment]
Same issue

**Comment by Shripardhi01** [comment]
```
flutter clean
flutter packages get
flutter run
 
```
these commands solve all my problem.

**Comment by prismars** [comment]
Yes. Its works.
"flutter clean"
"flutter run"

**Comment by danielroek** [comment]
Same issue here, after upgrading flutter building failed. 
This was the stacktrace: `Error: Could not resolve the package 'characters' in 'package:characters/characters.dart'.
../../../flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../../flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not found: 'package:characters/characters.dart'
export 'package:characters/characters.dart';
^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../../flutter/packages/flutter/lib/src/material/text_field.dart:822:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
  int get _currentLength => _effectiveController.value.text.characters.length;
                                                            ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/material/text_field.dart:824:118: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
  bool get _hasIntrinsicError => widget.maxLength != null && widget.maxLength > 0 && _effectiveController.value.text.characters.length > widget.maxLength;
                                                                                                                     ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:355:11: Error: 'CharacterRange' isn't a type.
    final CharacterRange iterator = CharacterRange(value.text);
          ^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:355:37: Error: Method not found: 'CharacterRange'.
    final CharacterRange iterator = CharacterRange(value.text);
                                    ^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:356:20: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (value.text.characters.length > maxLength) {
                   ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:375:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (maxLength != null && maxLength > 0 && newValue.text.characters.length > maxLength) {
                                                            ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_formatter.dart:378:25: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      if (oldValue.text.characters.length == maxLength) {
                        ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:244:64: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
       assert(obscuringCharacter != null && obscuringCharacter.characters.length == 1),
                                                               ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:361:35: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    assert(value != null && value.characters.length == 1);
                                  ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:567:11: Error: 'Characters' isn't a type.
    final Characters remaining = string.characters.skipWhile((String currentString) {
          ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:567:41: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    final Characters remaining = string.characters.skipWhile((String currentString) {
                                        ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:600:47: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    for (final String currentString in string.characters) {
                                              ^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/editable.dart:602:40: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
          !_isWhitespace(currentString.characters.first.toString().codeUnitAt(0))) {
                                       ^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acharacters%2Fcharacters.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:574:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



FAILURE: Build failed with an exception.

* Where:
Script '/home/daniel/projects/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildProfile'.
> Process 'command '/home/daniel/projects/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...
Running Gradle task 'assembleAarRelease'...
✓ `android/settings_aar.gradle` created successfully.
Building plugin flutter_barcode_scanner...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/daniel/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-1.0.1/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

Exception: The plugin flutter_barcode_scanner could not be built due to the issue above.
`

After running flutter clean the build did succeed

**Comment by shivktyr** [comment]
If you have updated to newest version, please run 'flutter clean'. It will resolve your issue.

**Comment by subrat0130** [comment]
flutter clean worked for me.

**Comment by niladrimahato96** [comment]
uninstall previous app if installed, run **flutter pub get**  in terminal and run the app again. It worked for me.

**Comment by leeprobert** [comment]
I upgraded today and now it just doesn't build. I tried to do a `flutter clean` and `cache repair` and everything else mentioned here. Still no luck. One question though, is this at all related to the `characters` package or is that error a red herring? Do I even need to be adding that package into my `pubspec`? It's really hard to debug what the issue is.

**Comment by leeprobert** [comment]
I had to add `characters: ^1.0.0` to my `pubspec.yaml` file. I also added `flutter_svg: ^0.18.0` as there was an error about this too. Both of these packages hadn't existed in my project before the upgrade. There was also a Firebase messaging deprecation error so I upgraded that to `6.0.16` - of these amendments, I have no idea which one made it build. It works though.

**Comment by thaihoang305** [comment]
I got the same situation. solved by run*

flutter clean 

in your terminal. Thank anw.

**Comment by awarmfastbear** [comment]
Flutter clean did not work for me after i upgraded flutter and ran into this error. 

Now I am getting:

```
$> flutter pub get
Because no versions of dartx match >0.3.0 <0.4.0 and dartx 0.3.0 depends on path >=1.6.4 <1.7.0, dartx ^0.3.0 requires path >=1.6.4 <1.7.0.
And because every version of flutter_test from sdk depends on path 1.7.0, dartx ^0.3.0 is incompatible with flutter_test from sdk.
So, because flutter_voice_cards depends on both flutter_test any from sdk and dartx ^0.3.0, version solving failed.
Running "flutter pub get" in flutter_voice_cards...                     
pub get failed (1; So, because flutter_voice_cards depends on both flutter_test any from sdk and dartx ^0.3.0, version solving failed.)
```

**Comment by mayhew3** [comment]
I am also having this problem. None of the above worked except adding "characters: ^1.0.0". It runs if I add that to pubspec.yaml. My full logs can be found here:  #66501
