### ISSUE TITLE
error permission when delete file from removable storage

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#59745]
I have a file in this address:

` path = '/storage/084C-1C0F/Yalin - Deva Bize Sevisler [128].mp3' `

So after inserting this permission in android manifest:

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

I want to delete this file:

     checkPermission().then((value) {
      final dir = Directory(model.path);
      dir.deleteSync(recursive: true);
      BlocProvider.of<AllMusicBloc>(context)
          .add(DeleteDeviceMusic(model.id));
    });

      Future<bool> checkPermission() async {
        var status = await Permission.storage.status;
        if (!status.isGranted) {
          await Permission.storage.request();
        }
        return true;
      }

but i got this error:

    E/flutter (16660): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Deletion failed, path = '/storage/084C-1C0F/Yalin - Deva Bize Sevisler [128].mp3' (OS Error: Permission denied, errno = 13)

**Comment by TahaTesser** [comment]
Hi @tazik561 
What package are you suing to manage permissions?  if you're using [permission_handler](https://pub.dev/packages/permission_handler#-readme-tab-)

If you think this is an issue with Flutter itself,  Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by tazik561** [comment]
I think I need to add android.permission.MEDIA_CONTENT_CONTROL, but system says that permission is only granted to system app.So how can i delete file from removable sd card (second external storage) like native file managers

**Comment by TahaTesser** [comment]
Hi @tazik561 

For issues related to 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated GitHub issues
	

This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
