### ISSUE TITLE
Flutter in_app_purchase problem : In iOS working in sandbox but not working in live

### ISSUE THREAD

**Issue by gaurang4** [flutter/flutter#59763]
We implemented flutter in app purchase and tested ios sandbox which is working well.

When we test the same in live then we do not get any previous purchase or subscription history.

**Comment by VladyslavBondarenko** [comment]
Hi @gaurang4 
are you using the last version `in_app_purchase 0.3.4`?
could you provide your `flutter doctor -v` and complete minimal reproducible code sample?

**Comment by gaurang4** [comment]
Thank you for reply @VladyslavBondarenko 

Yes we are using in_app_purchase 0.3.4

Here is output of flutter doctor -v

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.1 at /Users/mac2/Desktop/Desktop/flutter
    • Framework revision f7a6a7906b (5 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac2/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (1 available)
    • iPhone X • 7db7bd78f721c47fe73f26c652821a7ddfd6335e • ios • iOS 13.5.1
• No issues found!

We used same code of this repository without any changes.

We get it working perfectly on ios sandbox, but when we submit app on store and check on live and subscribe then we do not get any purchase history that's why each time it ask user to subscribe.

**Comment by gaurang4** [comment]
We are stuck, I would be thankful if someone can assist. Thank you in advance!

**Comment by iapicca** [comment]
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by Hixie** [comment]
Is there a minimal reproduction test case we can use to test this?

**Comment by cacianokroth** [comment]
Here it is happening too, in the sandbox testing is working, but not in the production lane.

**Comment by Hixie** [comment]
Please provide us a reproduction test case so that we can test this out. We have been unable to reproduce it ourselves. If you can provide us with an example that lets us see the problem (along with detailed instructions on how to see the problem) we will be able to work on it. Thanks!

**Comment by Hixie** [comment]
There is code in https://github.com/flutter/flutter/issues/60344 which might help reproduce this; it sounds like maybe pushing the code via Codemagic is part of how to reproduce this problem?

**Comment by Dfisch3r** [comment]
No, it has nothing to do with Codemagic. Codemagic just take care of the upload to the AppStore for users who have no Mac. In the issue #60344 you can find the code and pubspec.yaml, so you should be able to reproduce the problem by:
-	Create a new project
-	Copy the pubspec.yaml
-	Copy the Code
-	Create an inApp Purchase (Renewal Subscription) in iTunes Connect with the same name choosed in the code
-	Build iOs App (if you have a Mac)
-	Upload it to iTunes Connect
-	Use TestFlight

I think there is no other way to deal with this problem, since all other contributers here also say that the problem only accure in TestFlight / App Store and not in Sandbox-Mode

Thanks for your help!

**Comment by Hixie** [comment]
@xster @jmagman Any chance y'all could take a look and see if you can reproduce this?

**Comment by jmagman** [comment]
Do you have the in-app purchase capability on in Xcode?  I don't see that in your reproduction steps.
[in_app_purchase README](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/example/README.md#ios) links to https://help.apple.com/app-store-connect/#/devb57be10e7
> Enable your app for in-app purchase capability in Xcode, as described in Add a Capability in the Xcode Help. Make sure that the bundle identifier and product identifiers for your app in Xcode match the identifiers for your app in your developer account and for the in-app purchases you configured in App Store Connect.


See https://developer.apple.com/library/archive/technotes/tn2259/_index.html#//apple_ref/doc/uid/DTS40009578-CH1-CERTIFICATES__IDENTIFIERS___PROFILES

![tn2259_EnableIAPCapability](https://user-images.githubusercontent.com/682784/88741457-947c6780-d0f4-11ea-8132-52d220588d28.png)

Between https://github.com/flutter/flutter/issues/60344 and this issue we still don't have a reproducible app, it just has some dart code.  I can't see a Xcode project or entitlements file.

@RedBrogdon maybe? I've never used TestFlight.

**Comment by jmagman** [comment]
\cc @cyanglaz

**Comment by Dfisch3r** [comment]
> Do you have the in-app purchase capability on in Xcode? I don't see that in your reproduction steps.
> [in_app_purchase README](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/example/README.md#ios) links to https://help.apple.com/app-store-connect/#/devb57be10e7

@jmagman Isn't this step automatically done by the in_app_purchase plugin?

**Comment by cyanglaz** [comment]
@Dfisch3r The plugin can't configure this setup for the app. The app has to do it. 

You can follow the [workflow](https://help.apple.com/app-store-connect/#/devb57be10e7) to set it up.

**Comment by Hixie** [comment]
Is there some way we can detect that the flag isn't set? At compile time or runtime?

**Comment by jmagman** [comment]
I don't think the app itself can detect it at runtime ([SecTaskCopyValueForEntitlement](https://developer.apple.com/documentation/security/1393461-sectaskcopyvalueforentitlement?language=objc) is macOS only).  Theoretically the tool could check at `flutter run` time but it doesn't have any code for first-party plugin checks like this (otherwise it could also check the firebase `GoogleService-Info.plist`) and no plugin-able way to do that?

**Comment by Hixie** [comment]
@gaurang4 Does adding this entitlement fix your problem?

@jmagman Sounds like this is an issue we should fix with the plugin/tool integration, maybe provide a way for the plugin to provide some code for the tool to run at analysis time or some such. I'll triage this to tool and plugin. Thanks!

**Comment by dannycortesv** [comment]
Any update for this? is iOS in app purchases support working properly?

**Comment by jmagman** [comment]
@gaurang4 Was the missing entitlement your issue?  We never heard back...

**Comment by JigarKotak7** [comment]
Is there any update on above issue? I have the same problem (everything worked fine in sandbox & even TestFlight but when the app is Live on the App Store and tried to test the subscription using real payment app does not detect past purchases (customer has been charged & even it shows on App Store subscription tap that user has subscribed but app cannot detect past purchases) Any help is really appreciated. Below is the link of the app on the App Store, it is really difficult to debug the issue as everything works fine in debug mode.

https://apps.apple.com/in/app/footlooze/id1537079695

**Comment by jmagman** [comment]
@JigarKotak7

> Was the missing entitlement your issue?

> customer has been charged & even it shows on App Store subscription tap that user has subscribed but app cannot detect past purchases

That sounds like it may be an issue on Apple's side, or some other entitlement being required?

**Comment by JigarKotak7** [comment]
> @JigarKotak7
> 
> > Was the missing entitlement your issue?
> 
> > customer has been charged & even it shows on App Store subscription tap that user has subscribed but app cannot detect past purchases
> 
> That sounds like it may be an issue on Apple's side, or some other entitlement being required?


<img width="778" alt="Screen Shot 2021-01-07 at 1 48 15 AM" src="https://user-images.githubusercontent.com/31124960/103816149-8874d880-508a-11eb-8738-eb0d9e30bce3.png">

I do have In-App Purchases Capability enabled in Xcode (Please let me know if anyone has any other ideas I could try to fix this problem)

Thank you!!

**Comment by urvashikharecha** [comment]
i  am facing same issue , i had done everything , i am receiving product list in my app . i can able to buy the product with my sandbox account and it is working fine , as soon as i checked with production mode i am not able to buy product in fact in app on buy button pressed i am not able to see the purchase dialog, even i upload my app to apple store but they can not able to check due to the issue.
this works in sandbox perfect but not in live..required support !!

**Comment by JigarKotak7** [comment]
__

> i am facing same issue , i had done everything , i am receiving product list in my app . i can able to buy the product with my sandbox account and it is working fine , as soon as i checked with production mode i am not able to buy product in fact in app on buy button pressed i am not able to see the purchase dialog, even i upload my app to apple store but they can not able to check due to the issue.
> this works in sandbox perfect but not in live..required support !!

Hi Urvashi,

Same here, I even got the app approved by Apple App Store and everything works fine in debug mode but when the app is live it charges the customer but the app cannot fetch pastPurchases so that user cannot access the premium features. If you figure out something please let me know(Probably we can share some note) as I have checked almost everything but no luck yet. Also if there is anyone else here who can help please let me know as this app needs to be delivered to my client as soon as possible and everything is ready except this final bug. 

Thank you
Jigar Kotak

**Comment by urvashikharecha** [comment]
Hi @JigarKotak7 
have you able to see the purchase pop up in live mode ??

**Comment by JigarKotak7** [comment]
> Hi @JigarKotak7
> have you able to see the purchase pop up in live mode ??

Yes and even payment goes through but I cannot fetch back the purchases (only in Live Mode) to provide premium the service to user.

**Comment by urvashikharecha** [comment]
in my case i am not able to see the popup? can you guide me something about it? @JigarKotak7

**Comment by urvashikharecha** [comment]
> > Hi @JigarKotak7
> > have you able to see the purchase pop up in live mode ??
> 
> Yes and even payment goes through but I cannot fetch back the purchases (only in Live Mode) to provide premium the service to user.

for that you can store your transaction to your server and than fetch back...

**Comment by JigarKotak7** [comment]
> > > Hi @JigarKotak7
> > > have you able to see the purchase pop up in live mode ??
> > 
> > 
> > Yes and even payment goes through but I cannot fetch back the purchases (only in Live Mode) to provide premium the service to user.
> 
> for that you can store your transaction to your server and than fetch back...

jigarkotak7@gmail.com is my email, please contact me there.

**Comment by Pilaba** [comment]
My app just got rejected for the third time, i can purchase any item on my end with release or debug mode. But when 
apple check my app seems not to work. (purchase popup just doesn't appear). I ask them to try on and Iphone instead of an Ipad. But I don't know if it will work. (As a side note i successfully implemente IAP on google play with almost the same code, and works great)

**Comment by jmagman** [comment]
Please make sure you are following the setup instructions for the [Flutter plugin](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/in_app_purchase/example/README.md#ios) and for your [iOS app](https://help.apple.com/app-store-connect/#/devb57be10e7).  If you are sure you have followed those instructions, please file a new issue and fully fill out the template, with either full reproduction steps or attach ios/Runner.xcodeproj/project.pbxproj and we'll investigate.
