### ISSUE TITLE
Flutter with deps roller failing due to type mismatch issues

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59780]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=54326. Assigning to @chaselatta, who owns the upstream issue.

**Comment by jonahwilliams** [comment]
I can't figure out how to use that bug tracker, but for the record:

There was a breaking change in the coverage API, with the flutter_tool has since updated: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/coverage_collector.dart#L69

This error could only happen if the roller is using a different coverage version than the constraint than the pubspec.yaml of the tool.

**Comment by kf6gpe** [comment]
@chaselatta reports that he is working a higher-priority issue, and will be getting to this after that.

**Comment by chinmaygarde** [comment]
@kf6gpe says Chase is still working on it and it is blocked on one higher priority item.

**Comment by chinmaygarde** [comment]
Fixed upstream.
