### ISSUE TITLE
Hot-reloading anonymous callbacks

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#59899]
Hot-reload does not apply to anonymous callbacks, which can require developers to do a hot-restart instead – with added confusion as it is not immediately obvious why the new code isn't applied.

I understand that extracting the callback to a function will make the hot-reload work, but in many situations, this is simply inconvenient.

For example, as a package author, I have an object that is used like this:

```dart
// computed is a global
final computed = Computed((read) {
  // TODO: return some computed state
  return 42;
});
```

Using a callback makes the code simple and readable, but changes made by hot-reload are not applied anymore.

We could change the code to:

```dart
final computed = Computed(_computed);

int _computed(Reader read) {
  // TODO: return some computed state
  return 42;
}
```

But that increase the complexity of the code, for nothing but hot-reload. It is also unintuitive, and most users of a package wouldn't think of doing this.

It would be great to have a way to perform hot-reload on anonymous callbacks (although I'm sure that this is fairly complex).

**Comment by mraleph** [comment]
Note that this has nothing to do with whether closure is anonymous or not. Hot reload simply does not affect the behaviour of already existing closures (does not matter if they are anonymous or not) at all. 

There are various issues with hot reloading closures, but I'd say the main issue is that there is simply no reliable way of telling (especially when closures are anonymous - which is the most common case) which closure body should be used to overwrite which other closure body. I guess this can be solved with some heuristics (e.g. if there is just one closure in scope), but overall it is just really gnarly problem. 

One other common problem with closures is their dependence on captured state - it's unclear how reload should handle newly introduced references into the outer scope. So supporting closures would introduce new failure modes which need to be detected and properly handled in the hot reload. 

Overall, at least to me it feels like a major complexity point. Right now Dart Hot Reload is relatively simple - program structure (including method bodies) gets updated, data (including closures) is not.

For example, V8's LiveEdit attempts to update closure bodies on edits - and it's just a never ending can of worms, to the point that [V8 wants to delete the whole thing](https://docs.google.com/document/d/1aE8XEyuqBpR5XoxHeSaBJHxZmT7rjBJtOat9rVqTXsc/edit#heading=h.7nki9mck5t64).

@rmacnak-google might have a different perspective on this though.

**Comment by rrousselGit** [comment]
I most definitely agree that this is a complex task

Although it's worth noting that in package's situation, there is no external state. 

Maybe we could have a limited support, for the specific for cases where the closure doesn't use any external variable (besides static ones)?
But then I'm not sure if that's worth it besides my limited usage.

**Comment by rmacnak-google** [comment]
In not attempting to match old closure to new closures, we follow Smalltalk semantics. I think following these predictable semantics is a much better experience as a programmer than adding heuristics, even if the heuristics cover 99% of cases, because a surprise reliably indicates a problem with my program's structure rather than a potential bug in the language implementation. (Stable semantics also allow for making changes programmatically, such as updaters and plugin loaders.) Smalltalk has had these semantics for decades, and code that follows good style works very well with them. For example, Smalltalk heavily frowns on large methods (more than ~7 lines) for reasons of readability and separation of concerns, and this naturally discourages prematurely capturing behavior.

Bad style:
```smalltalk
build
    ...
    self button: 'Do Something' action:
        ["Complex logic not updated when button pressed after #build is edited"].
    ...
```

Good style:
```smalltalk
build
    ...
    self button: 'Do Something' action: [self respondToDoSomething].
    ...

respondToDoSomething
    "Complex logic updated when button pressed after #respondToDoSomething is updated."
```

This way of thinking is not "for nothing but hot-reload," but hot-reload does push further in this direction.

For your Dart example, I disagree that the first option is more readable or intuitive; too much is happening in an initializer.

For JavaScript I'm sympathetic to V8's attempt to do this matching since there's not really any other structure in JavaScript to work with, and the lack of JS IDEs makes it difficult to get it to par with Self.
