### ISSUE TITLE
Mpd video file downloading

### ISSUE THREAD

**Issue by sumanthkumarps** [flutter/flutter#59947]
Is there any option to select the video qualities and audio tracks from MPD. then download video based on the selected track.

**Comment by mkiisoft** [comment]
Follow this example: https://www.wowza.com/docs/how-to-use-alternative-audio-or-video-tracks-with-mpeg-dash-streams

This should not be open as an issue. StackOverFlow is a better platform for that.

**Comment by sumanthkumarps** [comment]
Hi @mkiisoft,
 Thanks for the input, this may not be an issue if the flutter framework doesn't support this kind of feature.
 For any kind of video player app, this will be the major feature,  excepting flutter framework for support. If you still think this is not the right place to ask this kind of question please comment back I shall close this issue.

**Comment by mkiisoft** [comment]
Flutter doesn't support videos technically. It uses other libraries in order to achieve that... for example, it uses ExoPlayer on Android for playback.

https://pub.dev/packages/video_player

You can check the official docs there or even file a ticket if that features is not present/broken. AFAIK, at least on Android, ExoPlayer is able to do that, but is an native feature.

**Comment by iapicca** [comment]
Hi @sumanthkumarps 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
