### ISSUE TITLE
analysis_options exclude don't work

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#59976]
```
  exclude:
    - "lib/helpers/viet_calendar.dart"
```
but still get warning
<img width="1159" alt="Screen Shot 2020-06-22 at 5 52 02 PM" src="https://user-images.githubusercontent.com/52562340/85279734-1f908f00-b4b1-11ea-99b0-b2aba7af2620.png">

**Comment by iapicca** [comment]
Hi @tbm98 
If you are experiencing the issue only with Android Studio or IntelliJ and not with VS Code, then following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Otherwise, please provide your ´flutter doctor - v´ output.
Thank you

**Comment by tbm98** [comment]
yep.
