### ISSUE TITLE
MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)  

### ISSUE THREAD

**Issue by shinde-vrushali** [flutter/flutter#60343]
trying to use the plugin in Flutter for web i am getting error
MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)  

I am trying to read data from firebase in flutter for web . for ios and android firebase database read work well but for web giving error whille reading firebase database on db.once().then((

**Comment by iapicca** [comment]
Hi @shinde-vrushali 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
