### ISSUE TITLE
[WidgetTester] pump for infinite animation

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#60372]
This is a sub-issue for #59882 

Currently we have `pump`, `pumpBenchmark` and `pumpAndSettle`, The first two only trigger frame once and the second assumes there's an end. For testing infinite animation we need a pump method for a given time period and ask for frames regularly.

**Comment by CareF** [comment]
Just found that @dkwingsmt added a `pumpFrams` that is very similar to my goal, but since it includes a `target`, I can't use this as a subroutine of a serial test operation.

**Comment by dkwingsmt** [comment]
The reason I added a new method was because I was trying to minimize the code used to use frame recorders, which I thought would be applied to many widgets. In your case, is it possible just to use pump in a loop?

**Comment by CareF** [comment]
> The reason I added a new method was because I was trying to minimize the code used to use frame recorders, which I thought would be applied to many widgets. In your case, is it possible just to use pump in a loop?

Effectively yes it's a loop. But to keep consistent with other pumps I added some more thing. I added a draft PR above for showing what I wanted to do. I may also add a callback in each frame.

**Comment by Hixie** [comment]
What's wrong with `for (int count = 0; count < 10; count += 1) await tester.pump();` ?

**Comment by CareF** [comment]
> What's wrong with `for (int count = 0; count < 10; count += 1) await tester.pump();` ?

I think you mean `tester.pump(Duration(1/60Hz))`. It is a loop but with a little assert check, as a convenience wrap like what we do in `pumpAndSettle` for `while (binding.hasScheduledFrame) await binding.pump();`

**Comment by Hixie** [comment]
Yes, I should have included a duration.

I'm not sure it's really worth a convenience wrap. pumpAndSettle has to use an obscure API (binding.hasScheduledFrame) and has some logic to handle non-terminating cases. In this case the direct equivalent seems pretty straightforward.

**Comment by CareF** [comment]
Closed because we decided not to introduce the convenience wrap. 

Just to clarify, this issue is not about  #60739 or #60796

**Comment by NatoBoram** [comment]
I think it would actually make sense to have a convenience method to avoid writing `for (int c = 0; c < 10; c += 1) { await tester.pump(const Duration(milliseconds: 17)); }`. Those values aren't exactly easy to get right - why should I pump 10 times and why 17 milliseconds? It's related to the framework and how it works, so I think it should be provided by the framework.

**Comment by dkwingsmt** [comment]
@NatoBoram Can you describe why you need this?

**Comment by NatoBoram** [comment]
"For convenience!"

I was copying Hixie's comment but then I realized that 10 was *many* frames pumped separately. Why is it done this way? Why exactly 1 frame, 10 times, and why do I have to calculate myself what's `1000 ~/ 60`? I started tweaking the numbers but anything less just doesn't work.

It must have something to do with the framework. An emerging property, perhaps. But I think it should be exposed by the framework rather than having to find this snippet in every project where it's needed.

But, no really, for convenience.

**Comment by dkwingsmt** [comment]
In my opinion it's really only related to how you want to test your code (since it only affects unit tests, not actual product). For example, you have something that rotates a circle per second. You pump 1 frame for 16ms? You expect it rotates 60 degrees. You pump 1 frame for 33ms? 120 degrees instead.

The 16ms really doesn't matter much: Flutter supports both lower and (hopefully) higher framerates, so if we're _really_ emulating actual devices, there will be many different frame durations. But no, it should be transparent to normal developers. Use whatever frame duration and frame count that suit you best.
