### ISSUE TITLE
Running app on iOS sandbox errors Sandbox: deny(1) iokit-get-properties IONameMatched

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60406]
Looks like an entitlement is missing, though I can't find one at the moment for `iokit-get-properties` (if there is one).

See https://github.com/flutter/engine/pull/18752.

```
Sandbox: Runner(393) deny(1) iokit-get-properties CFBundleIdentifier
Sandbox: Runner(393) deny(1) iokit-get-properties IOMatchCategory
Sandbox: Runner(393) deny(1) iokit-get-properties IOProviderClass
Sandbox: Runner(393) deny(1) iokit-get-properties IONameMatch
Sandbox: Runner(393) deny(1) iokit-get-properties IOSourceVersion
Sandbox: Runner(393) deny(1) iokit-get-properties CFBundleIdentifierKernel
Sandbox: Runner(393) deny(1) iokit-get-properties IONameMatched
Sandbox: Runner(393) deny(1) iokit-get-properties IOProbeScore
Sandbox: Runner(393) deny(1) iokit-get-properties IOReportLegend
Sandbox: Runner(393) deny(1) iokit-get-properties IOReportLegendPublic
Sandbox: Runner(393) deny(1) iokit-get-properties IOPowerManagement
Sandbox: Runner(393) deny(1) iokit-get-properties SCMVersionNumber
Sandbox: Runner(393) deny(1) iokit-get-properties SCMBuildTime
Sandbox: Runner(393) deny(1) iokit-get-properties AGXTraceCodeVersion
Sandbox: Runner(393) deny(1) iokit-get-properties GPURawCounterBundleName
Sandbox: Runner(393) deny(1) iokit-get-properties GPURawCounterPluginClassName
```

**Comment by jmagman** [comment]
\cc @gaaclarke

**Comment by gaaclarke** [comment]
These are known not to be available since they are private APIs.  On  release builds they are ripped out.  Are these warnings or errors?  Right now I have the feature turned on always for debug and profile builds but I could make it a flag.

Is your setup different than mine you think or did I just not notice these messages?

**Comment by jmagman** [comment]
It's warnings from the kernel process on the device, not from the app process.  So unless you had the console open and were looking, you wouldn't see them.

I don't care about the warnings in debug per se, it's that the app is trying to use iokit and it's being denied getting any of those properties.  So is the perf gathering actually working?

**Comment by gaaclarke** [comment]
@jmagman Yea, those functions were giving me meaningful results.

**Comment by jmagman** [comment]
Hm.
Feel free to close then.

**Comment by maxp89** [comment]
Hi folks,

since latest upgrade to Flutter 1.20.1, I have a problem with my iPhone 8 when starting a Flutter app out of Android Studio (just plain run button).

It stops nearly for 2-3 minutes in the native splash screen before it decides to load the first Flutter view.

All I see in Console log are a lot of Kernel Errors like:

> Sandbox: Runner(867) deny(1) iokit-get-properties CFBundleIdentifier
> Sandbox: Runner(867) deny(1) iokit-get-properties IOMatchCategory


Also I have another issue in production where the app was build in release mode, but could be another problem as I don't have device logs yet for this.
Description can be found here: 
https://stackoverflow.com/questions/63373414/flutter-app-freezes-in-native-splash-loading-screen

**Comment by jmagman** [comment]
@maxp89 We wouldn't expect those Sandbox warnings to impact initial view loading (or anything, based on @gaaclarke's answer).  You should definitely file a new issue and completely fill out the template so it can be investigated by the right team.

**Comment by maxp89** [comment]
After trying to explore the reason I was not able to reproduce this every time, especially not when using verbose output option. I did open: https://github.com/flutter/flutter/issues/64544
