### ISSUE TITLE
Add a new `LiveTestWidgetsFlutterBindingFramePolicy` for benchmark on device

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#60739]
There's a discussion about `LiveTestWidgetsFlutterBindingFramePolicy` in my [recent PR](https://github.com/flutter/flutter/pull/60410#discussion_r447938985), where I believe we are clarifying some ambiguity about the documents for `LiveTestWidgetsFlutterBindingFramePolicy`. 

There are two places explaining this enum
- https://api.flutter.dev/flutter/flutter_test/LiveTestWidgetsFlutterBindingFramePolicy-class.html
- https://api.flutter.dev/flutter/flutter_test/LiveTestWidgetsFlutterBinding/framePolicy.html 

And it seems that `fullyLive` can or is intended to be used for effectively a synchronized (self-pumping) tester as requested in [DesignDoc:synchronized-widgettester](http://flutter.dev/go/synchronized-widgettester) . The only thing is that it's still responding to `pump`s from both user calls of a test app or from some test gestures, which leads to extra frame requests besides those from engine and framework animation. This prevents a faithful simulation for performance test cases running on a device. 

If I interpret the enum flags correctly, I think it would be necessary to introduce another flag that is between `fullyLive` and `benchmark`, say `benchmarkLive`, that ignores all `pump`s like `benchmark` but still responds to other framework frame request like animations, while still serves all engine frame requests like `fullyLive`. This would be helpful for test apps running on a device to simulate the device behavior.

**Comment by CareF** [comment]
cc @liyuqian @dnfield 
cc @Hixie can you check if I correctly understand the motivation of these flags?

**Comment by CareF** [comment]
Meanwhile I would also like to re-arrange these dart-docs to put them together and leave a link in the other place, and clarify the usage of `benchmark` (especially it's not used for performance test).

**Comment by dnfield** [comment]
@CareF it would helpful if you could write a test case that would _fail_ with `fullyLive` and `benchmark`, but not fail with your new proposed change.

**Comment by CareF** [comment]
@dnfield Something like counting the number of Frame request in timeline?

**Comment by dnfield** [comment]
It's not clear to me why we couldn't use the fullyLive enum for that, but a test case would help illustrate it more clearly.

**Comment by liyuqian** [comment]
It seems that a mock test would be helpful in explaining how these new enums and APIs will be used. How about writing a mock test (maybe in a gist) for https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart using the `WidgetTester` and your envisioned enums/APIs?

**Comment by CareF** [comment]
A best demo would require a test gesture that has a time duration, which is in one of my PR. But for demo purposes see this branch: https://github.com/CareF/flutter/tree/benchmarkLiveDemo particularly this test: https://github.com/CareF/flutter/blob/benchmarkLiveDemo/dev/benchmarks/complex_layout/test_driver/scroll_perf_e2e.dart 
@liyuqian @dnfield

**Comment by dnfield** [comment]
With the fully live binding, is the frame count higher just because you're getting that many `pump`s in, which causes a new frame to generate? IOW, I suspect you're counting artificial frame pumps rather than what you're really interested in. Put another way, I would be surprised if a Moto G4 could actually give you >60fps that you're seeing when you call `pump`.

I'm also pretty sure you don't want to use a future here: https://github.com/CareF/flutter/blob/benchmarkLiveDemo/dev/benchmarks/complex_layout/test_driver/scroll_perf_e2e.dart#L45 since that will get you to the end of the current event loop anyway and may actually take longer than 8ms - for example, if your average frame takes 16ms, and all that workload is running synchronously. You probably want a microtask there, although I'm not sure that will be quite correct either. It might be interesting to store timestamps and dump them at the end to see when your gesture events are actually occurring - I suspect they're occuring more than 8ms apart.

For this kind of test in particular, I wonder if you really want some kind of fixture based test in the engine, so that you can just directly push pointer events from native code at the correct rate without worrying about the Dart VM event loop or synchronous code in the frame pipeline getting in your way. IOW, if you're trying to simulate 120hz input events purely from Dart code, it's going to be really hard to not trip over everything else going on in the event loop unless you're outside it.

**Comment by CareF** [comment]
> With the fully live binding, is the frame count higher just because you're getting that many `pump`s in, which causes a new frame to generate? 

This is very likely. To be more concise, the ticker is invoked in `SchedulerBinding.handleBeginFrame`, whose document says "Called by the engine to prepare the framework to produce a new frame."

By the end of the day, my point here is, the new framepolicy is meant to avoid such thing in the beginning. 

> I'm also pretty sure you don't want to use a future here: https://github.com/CareF/flutter/blob/benchmarkLiveDemo/dev/benchmarks/complex_layout/test_driver/scroll_perf_e2e.dart#L45 since that will get you to the end of the current event loop anyway and may actually take longer than 8ms 

This is a concern I discussed with @liyuqian yesterday. One thing I can say now is in other places of `flutter_test` where we need a given delay, sometime an un-`await`ed `Timer` is used, and I believe they are promised to be `await`ed due to the of of `TestAsyncUtils.guard`. `Future.delayed` is a convenience wrapper of `Timer`. 

> For this kind of test in particular, I wonder if you really want some kind of fixture based test in the engine, so that you can just directly push pointer events from native code at the correct rate without worrying about the Dart VM event loop or synchronous code in the frame pipeline getting in your way. IOW, if you're trying to simulate 120hz input events purely from Dart code, it's going to be really hard to not trip over everything else going on in the event loop unless you're outside it.

This is something I will explore with features introduced by the pending PRs. But there is one promising fact I can say: `_handlePointerEvent` both in my version and in the framework `GestureBinding` are **sync** and I'm expecting them to be fast.
