### ISSUE TITLE
Newline character \n Not Working While Loading Text From Firebase

### ISSUE THREAD

**Issue by atheistrepublic** [flutter/flutter#60833]
Hi i am using some text data to load from firebase and then showing it as Text.I am using Text() widget .I have a field called description in my firebase document which for example contains info like this:

**description**: This is \n some text.

So as you can see there should be two lines first containing This is and second line containing some text.But this does not happen.All the text is shown in one line only.
Also note that _this only happens when i read the text from firebase document and but when i replace it with custom text(string) containing \n which is not read from firebase it works fine._
Why is this happening and how can i resolve this?Why does it not work when loading string from firestore.

**Comment by iapicca** [comment]
Hi @...
This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Moreover if you believe the issue is related to a FlutterFire plugin, please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, 
please write in the comments and I will reopen it.
Thank you
