### ISSUE TITLE
Implement delta for DragStartDetails

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter#60841]
I would like to ask if is it possible to implement delta for DragStartDetails since only DragUpdateDetails have it.

https://api.flutter.dev/flutter/gestures/DragUpdateDetails-class.html

https://api.flutter.dev/flutter/gestures/DragStartDetails-class.html

Thank you.

**Comment by goderbauer** [comment]
What would the delta be? Wouldn't it always be 0 at the start of the drag?

**Comment by d-apps** [comment]
> What would the delta be? Wouldn't it always be 0 at the start of the drag?

I am developing a game with flutter and I needed to move my player from his current position (x, y) to the users's position first touch before dragging, I thought that onStartDetails could give me a delta or someway for me move the user's touch position (x, y) progressively, maybe I will have to implement that myself, is there any method on flutter api that could help me do that, go progressively from a number to another?

Current position (x = 100, y= 100 )
New position (x = -100, y = 50) (but goes progressively and not directly)

Thank you.

**Comment by goderbauer** [comment]
I don't think we can give you that delta in the DragStartDetails because we don't know the point of reference. The delta in  DragUpdateDetails is the delta from the last event and since DragStartDetails is the first event, there's no delta.

You can use an AnimationController and a Tween (or one of its subclasses) to animate from one position to another, if that's what you're asking.

I am closing this issue since the original request doesn't seem doable.
