### ISSUE TITLE
Lists should have a firstOrNull and lastOrNull property

### ISSUE THREAD

**Issue by enloc-port** [flutter/flutter#60887]
## Use case

In cases you want to have the first/last list element _or null_, but don't know whether the list is empty, you'd usually do something like this:

```
List<String> myStringList = <String>[];
String foo = myStringList.isNotEmpty ? myStringList.first : null;
```
That's because calling `.first` (or `[0]`) or `.last` on an empty list throws an exception, which is reasonable, because you might actually want to distinguish, whether you got a `null` because the list is empty or because the respective list element is actually `null`.

## Proposal

However, in cases where you are certain that there is no `null` in the list or you don't care about that difference, it would be nice to have a property which handles the null check on its own:

```
List<String> myStringList = <String>[];
String foo = myStringList.firstOrNull;
```

**Comment by iapicca** [comment]
Hi @enloc-port 
[dart](https://dart.dev/null-safety) and flutter are in the process of implementing [null-safety](https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3)
I'm not sure that the feature you are proposing would play well with this;
moreover what you are proposing seems to be aimed to dart rather than flutter
I suggest you to open an issue in the dedicated [github](https://github.com/dart-lang/sdk/issues).

in the meantime you might want to consider using the extension method

```dart
extension ExtendedText on List {
  T indexOrNull<T>(int index) => this.length >= index ? this[index] : null;
  T firstOrNull<T>() => this.isEmpty ? null : this.first;
  T lastOrNull<T>() => this.isEmpty ? null : this.last;
}


void main() {
  final List<String> _list = [];
  print(_list.indexOrNull(5));
  print(_list.firstOrNull());
  print(_list.lastOrNull());
  
  _list.add('hello');
  print(_list.indexOrNull(5));
  print(_list.firstOrNull());
  print(_list.lastOrNull());
  
  _list.addAll([for (int i = 0; i < 5; ++i) 'hello']);
  print(_list.indexOrNull(5));
}
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
