### ISSUE TITLE
iOS Build get error  Unknown FLUTTER_BUILD_MODE:xxx

### ISSUE THREAD

**Issue by huainanzi** [flutter/flutter#60888]
![截屏2020-07-06 下午4 28 13](https://user-images.githubusercontent.com/17873544/86573041-5df47680-bfa6-11ea-9809-bbdba1b286e0.png)

my project has many Build Configuration.I run Release and Debug is ok. How I sloved it?

![截屏2020-07-06 下午4 32 13](https://user-images.githubusercontent.com/17873544/86573054-651b8480-bfa6-11ea-9776-575b988f519a.png)

**Comment by TahaTesser** [comment]
Hi @huainanzi 
You can only build in `release`, `debug` and `profile` [Flutter's build modes](https://flutter.dev/docs/testing/build-modes)   
Since you can successfully build release and debug. Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
