### ISSUE TITLE
Callbacks in the app drawer make strange things happen

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#6096]
## Steps to Reproduce

In the leafy app, some types of UI configuration changes made with a widget in the app drawer cause an exception to get thrown and stops inkwells from working.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Framework revision fa52b456ec (14 hours ago), 2016-09-25 19:30:44
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
...

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39

## Logs and Crash Reports

Happy to leaf full reports with you if you wood like me to.  I'm tracking this at b/31757934.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@Hixie commented on the internal bug:

Looking at the AppDrawer code, some possible things that stick out:
- you don't seem to ever unsubscribe from teamListener, so nothing protects you from being called after you're disposed.
- you have a setState call where you don't change anything that the State's build function depends on (you just call Navigator.pop).

the bug was later resolved with a code-change on leafy's side, so I'm going to assume this can be closed externally as well.  Please feel free to re-open if you feel there is something more flutter should do here (documentation, asserts, etc.)
