### ISSUE TITLE
Rethink Forms

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#6097]
The Form/Input API is confusing. I think it needs a redesign.

In general, FormField provides a second, slightly easier way of doing things that Input does. This is nice to have but it also causes a lot of confusion. Ideally there's a way to combine FormField's ease of use with Input's flexibility.

Problems:
- [ ] You can provide a `formField`, which causes the Input to manage the InputValue for you - but only when a descendant of a `Form`. This is a strange restriction that we should remove.
- [ ] If you provide a `formField`, the `value` argument acts as an initial value, not the current value. Changes to `value` are ignored in future widget re-builds.
- [ ] FormField's `setter` callback and Input's `onChanged` callback fight each other. We should have one or the other.
- [ ] FormField's `validator` callback and Input's `errorText` argument fight each other. We should have one or the other.
- [ ] Form's onSubmitted callback is not useful. It doesn't inform you which Input was submitted, and whole forms are generally not submitted when the "accept" key is tapped anyway.
- [ ] It would be convenient if there was a way for the Form to tell you if any of the fields were invalid (e.g. to disable/enable the "Submit" button). [added by @Hixie]

At the very least, we should remove the `Form` ancestor. We can store that form state on the Input itself.

**Comment by abarth** [comment]
We should probably layer this as two widgets, `Input` and `InputField`, where `InputField` wraps an `Input` and integrates it with a `Form`.  That would let us have `RadioField` and the like which do similar things for the other form controls.

**Comment by abarth** [comment]
Reassigning to @Hixie given that he posted a partial patch for this issue.

**Comment by mehmetf** [comment]
We have been thinking about forms for a while as well:
- We need state keeping not just in Input() fields but for other types of elements such as DropdownButtons and Sliders. Dropdown buttons actually need to be able to show errors. We have an outstanding issue for that [https://github.com/flutter/flutter/issues/6422]

- There is common logic to be executed for such fields (such as validation, saving value/error) and we wanted to capture that in a common place rather than repeating it everywhere.

- The typical pattern of onChanged(value) { editedObject.attr = value; } does not really work for us because of two reasons:
  - Not all our form field values can be stored in the edited object. Some are derived; so we would have had to create intermediate state to save these anyway.
  - We can't set attributes on our objects multiple times due to the way our patch API works. Our objects are mutable and we have a patch mechanism that calculates diff in a cheap way. The proper way would have been to have immutable objects and clone the object and do an intelligent diff after edit but alas.

After going back and forth on design a few times:

```Dart
class GtFormField<T> {
  T _value;
  String _error;
  final FormFieldValidator<T> validator;
  final FormFieldSetter<T> onSave;

  GtFormField({
    @required this.onSave,
    @required T initialValue,
    this.validator,
  })
      : _value = initialValue;

  set value(T value) {
    if (validator != null && value != null) {
      _error = validator(value);
    }
    _value = value;
  }

  T get value => _value;

  String get error => _error;

  bool get hasError => _error != null;

  bool save() {
    if (hasError) {
      return false;
    } else {
      onSave(_value);
      return true;
    }
  }
}
```

Typically the page that includes a form has to edit an object and the form values are populated via its attributes. So we do this:

```Dart
class MyWidgetState extends State<MyWidget> {
  GtFormField<double> sliderField;
  GtFormField<InputValue> textField;
  Object object;

  initState() {
    textField = new GtFormField(
      initialValue: object.text,
      onSave((InputValue value) {
        object.text = value.text;
      },
      validator((InputValue value) {
        if (value == null) {
          return "Need to have value";
        }
      }),
    );
  }

  void onSaveClicked() {
    for (var field in [sliderField, textField]) {
      if (!sliderField.save()) {
        //handle error in form.
        return;
      }
    }
    // do something with object.
  }

  build() {
    // build some button with onTap: onSaveClicked.
    // and build a list of form elements hooking the valuechanged,
    // error and value setters to form fields.
    return [
      new Slider(
      onValueChanged: (value) {
        setState() {
          sliderField.value = value;
        }
      }
      errorMessage: sliderField.error,
      value: sliderField.value,
    ), new Input(....)];
  }
}
```
I am not sure how much of this it makes sense to internalize in the framework. Our design choices are shaped by limitations of the patch API we use. However, I wanted to show you a real-life use case for forms. 

One of the issues I still have not tackled is the notion of required vs optional fields. Typically, validation should ignore null values but not if they are required. My current thinking is to have a mutable property on the FormField object to indicate whether the field is currently required or not because the requiredness of our fields can change (imagine a form that optionally requires address, if user wants to receive a newsletter [based on a toggle], all of a sudden address becomes required).

**Comment by mpcomplete** [comment]
Thanks for the real-world use case. It definitely helps me think how we want this to work. I think things like Input and Slider and the like should remain low-level components, but it would be nice if we provided a higher-level API to help you manage all the form logic in a common place.
