### ISSUE TITLE
Error while running example given in TextFormField class documentation 

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/flutter#61078]
Getting the below error while trying to run the [interactive example](https://api.flutter.dev/flutter/material/TextFormField-class.html#material.TextFormField.2) on [TextFormField class documentation](https://api.flutter.dev/flutter/material/TextFormField-class.html)

![image](https://user-images.githubusercontent.com/65178249/86899357-89eb3580-c127-11ea-8d6a-56cff29dafc9.png)

**Comment by TahaTesser** [comment]
Thanks @dev-aentgs  for catching this issue

**Comment by HansMuller** [comment]
CC @gspencergoog - Replacing `Intent(NextFocusAction.key)` with `NextFocusIntent()` fixes the compilation error however the enter key doesn't move the focus. There's another problem: restarting the app, by pressing 'Run' again, causes the tab key to start advancing the focus twice instead of just once.

**Comment by gspencergoog** [comment]
The enter key doesn't move the focus because on the web engine, the text field handles the enter key itself, calling unfocus, which focuses the surrounding scope, which in this case is the modal scope for the navigator. That means that the Shortcuts widget is no longer in the focus chain, and so it never sees the enter key. This example works fine on other desktop platforms.

Adding a FocusScope between the Form widget and the Shortcuts widget also doesn't solve the problem: then the unfocus causes the new scope to be focused, which now allows the Shortcut to see the enter key, but when it invokes the NextFocusIntent, since the surrounding scope has the focus, it moves to the first field in the form, rather than what the user thinks of as the next field.

This is yet another case indicating why we need to refactor the text editing model so that we can override editing operations (in this case, form commit via enter) with different actions. cc @justinmc

BTW this all works just fine if you change from using the enter key to using the space bar.

**Comment by gspencergoog** [comment]
As for the TAB key advancing more than once, that seems to be cumulative: the more times you press "Run", it adds to the number of times it moves.  Luckily, this only seems to happen in Dartpad: doing hot reload or hot restart on the example built for web (or linux) doesn't seem to have this problem. When it happens, the web browser reports "Script error", which turns out to be an assertion failure in parsing the stack frame, [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/stack_frame.dart#L115), so perhaps that is masking another error, since it wouldn't be parsing a stack frame unless something had crashed.

**Comment by incon** [comment]
This example doesn't appear to work on mobile. iOS or Android.
