### ISSUE TITLE
Flakes running unit-tests on Fuchsia are causing tree closures on LUCI.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#61167]
A sample [failure is here](https://chromium-swarm.appspot.com/task?id=4d4c91ee020e2110). They all look like failures to pave the device.
![Screen Shot 2020-07-09 at 8 28 03 AM](https://user-images.githubusercontent.com/44085/87059507-3d9f0480-c1be-11ea-8023-429490d77186.png)

**Comment by chinmaygarde** [comment]
This is blocking all presubmits, commits, and rolls. Can this step be disabled till the paving issues are sorted out?

**Comment by godofredoc** [comment]
\cc @digiter can you please disable the builder and follow up the bug in the fuchsia side?

**Comment by digiter** [comment]
Thanks Godofredo, fuchsia infra is working on the paving bug: http://fxb/55818. I'm looking for ways to ignore the builder.

**Comment by godofredoc** [comment]
The problem with the bots was fixed and we are now monitoring the results. 

This is a manual retry to unblock the tree: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/4459

The expectation is that new builds of Linux Fuchsia will succeed, moving this bug to P1 while monitoring.

**Comment by godofredoc** [comment]
The issue with the bots was:

* lab-001-001 host had a bad sata error.
* all the bots attached to lab-001-001 where failing all the tasks.
* lab-001-002 host had a bad bot that was picking most of the tasks because it cache was fresher than the others and failing all the tasks.

What we did was:

* Disable lab-001-001 host.
* Remove bad device from lab-001-002

**Comment by digiter** [comment]
![Rwfe89zHTgU](https://user-images.githubusercontent.com/6259181/87085650-127bdb80-c1e5-11ea-925c-12a0ed744443.png)
Looks like the fix works.
