### ISSUE TITLE
Provide an option for Flutter web driver tests to be visually easier to verify

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#61214]
Whenever I execute a Flutter driver test for web, a browser window opens momentarily and then quickly disappears.

The tests seem to execute correctly, ie, they find content that should be there and they fail to find content that shouldn't be there.

This browser behavior remains true even if I artificially delay the execution of a test.

I'd like for the browser to stay open during the tests for visual verification, similar to running on a simulator, emulator, or device.

Flutter 1.20.0-8.0.pre.40 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6eaaf1650e (6 hours ago) • 2020-07-09 18:04:37 -0700
Engine • revision 9b3e3410f0
Tools • Dart 2.9.0 (build 2.9.0-20.0.dev 06cb010247)

**Comment by nturgut** [comment]
Generally tests run very fast. Right now there isn't an option for making them slower hence easier to confirm visually. I have two options in my mind which can help:

(1) I observed Safari tests to be better for "visual verification". Please try `--browser-name=safari` option to see if it's better (you should also run safari driver first, `/usr/bin/safaridriver --port=4444`)

(2) May be not quite what you need since the test API is different but, have you tried [e2e](https://pub.dev/packages/e2e) tests? `artificially delay the execution of a test.` will also work there. Example: https://github.com/flutter/engine/tree/master/e2etests/web/regular_integration_tests

`flutter drive -v --target=test_driver/text_editing_e2e.dart -d web-server  --profile --no-headless --browser-name=chrome` Provides a detailed visual there cursor goes over each test field one by one.

**Comment by matthew-carroll** [comment]
The problem here is not the speed of the test. One can easily place pauses in a test. It has no impact here.

My browser window opens and then closes, and THEN my tests run. I can see logs being written to the console when there is no browser window open.

Driver tests are not a good replacement for this purpose. Those tests are written very differently and with a lot more code. 

I believe this is a bug, not a new feature.

**Comment by matthew-carroll** [comment]
It looks like the variation of the command with `--no-headless` made the difference. 

I guess it's headless by default?

Is this analogous to Driver behavior for mobile? I'm wondering if the default should show the browser...
