### ISSUE TITLE
imagefiltered_transform_animation_perf__timeline_summary 90th_percentile_frame_build_time_millis has climbed, now predominantly regressed...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61237]
I've missed this one for the last few days, because it's drifted in and out of being red. It's pretty clear now looking at the history that it's regressed slightly:

![Screen Shot 2020-07-10 at 9 29 27 AM](https://user-images.githubusercontent.com/1435716/87177054-dfdaed00-c28f-11ea-86de-019fbd2234d1.png)

It's difficult for me to pinpoint a single roll causing it. The first time it went red was in restoring it after a gap (https://github.com/flutter/flutter/pull/60415), but I don't think that's it; I rather prefer engine roll https://github.com/flutter/flutter/pull/60384, in which the benchmark was still green, but a jump from its predecessor.

I'm tentatively giving this to the engine team, and given that it's not a huge regression, assigning it a P2 for investigation.

**Comment by kf6gpe** [comment]
Aha! Interesting. average_frame_build_time_millis is also affected, and regressed at the same engine roll.

![Screen Shot 2020-07-10 at 9 34 20 AM](https://user-images.githubusercontent.com/1435716/87177478-8cb56a00-c290-11ea-8b5f-65e63cc8ea91.png)

**Comment by flar** [comment]
Yes, this figure regressed slightly, but I haven't investigated why. For one thing it makes no sense because the engine changes should have no effect at all on the dart-level frame building.

It was associated with a much more significant improvement in the average rasterization times, though, so we should probably accept it since overall time per frame should have gone down. We lost about .3ms on the build, but gained about 10ms on the render. That's the much more significant outcome.

With respect to why this happened when nothing changed in the framework code - The only thing I can think of is that by rendering more frames (the missed frame count went down and we render every frame now rather than every other frame and a half) we are experiencing more memory churn than before and so we have more GC happening.

Let me run some timelines before/after the change and graph them and see if that shows any interesting phenomena and then I'll re-baseline accordingly if that sounds like a good plan.

**Comment by flar** [comment]
I've graphed the frames sorted by build duration and there is a bump towards the far end of the measurements taken from the build that caches the children. Note that the cached (newer) version drew 36 more frames than the uncached (older) version (597 rendered frames vs 561). The older uncached version also performed 4 IdleGC cycles whereas the newer cached version performed 6 IdleGC cycles - suggesting that memory strain might be a contributing factor. I didn't look to see how much memory pressure existed across the GC cycles, though.

<img width="1200" alt="TL_imagefiltered_uncached_build_durations" src="https://user-images.githubusercontent.com/50503328/87212213-3a953880-c2d2-11ea-8e07-e3bac6548ac4.png">
<img width="1200" alt="TL_imagefiltered_cached_build_durations" src="https://user-images.githubusercontent.com/50503328/87212216-3ff28300-c2d2-11ea-9bf0-f580f3337ba0.png">

**Comment by chinmaygarde** [comment]
This looks like a candidate for re-baselining.

**Comment by zanderso** [comment]
@flar Could you check if this was rebaselined? Thanks!

**Comment by flar** [comment]
I've rebaselined them all now. They should be green on the next refresh of the dashboard data.
