### ISSUE TITLE
Misleading CLI error message on wrong option

### ISSUE THREAD

**Issue by BondarenkoStas** [flutter/flutter#61231]
Hello!
Sometimes it gets confusing while using misspelled hyphens before flags or options in Flutter CLI.

1. 
Correct command: `flutter build apk --flavor dev`
Misspelled command: `flutter build apk -flavor dev`
Output: `Could not find an option with short name "-f".`

2.
Correct command: `flutter build apk --verbose`
Misspelled command: `flutter build apk -verbose`
Output: `Could not find an option with short name "-e".`

3.
Correct command: `flutter build apk --device-id api28_API_28` runs correctly
Misspelled command: `flutter build apk -device-id api28_API_28`
Output: `Target file "api28_API_28" not found.`

While it's easy to spot the mistake and cli api is great, it's strange to see such error outputs instead of stating e.g. Could not find a flag or option "-flavor".

It's just a suggestion, but maybe it's better to have CLI more strict and straightforward?

**Comment by jonahwilliams** [comment]
The flutter tool uses https://github.com/dart-lang/args for the arg parsing, and this is its default behavior. The short option syntax is fairly consistent with other CLI tools. If `-f` wasn't short for anything, you could look for `--flavor` and see if it exists I guess. 

Closing here because it should be opened on args
