### ISSUE TITLE
request: AppBars in PopupRoutes should display CloseButton

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#61255]
## Use case

In a `PopupRoute` like used by `showModalBottomSheet`, the `AppBar` currently shows a `BackButton` rather than `CloseButton`.

This is a result of https://github.com/flutter/flutter/blob/5a00d54eece05852e9f2166713cdfb587ce03a18/packages/flutter/lib/src/material/app_bar.dart#L506

## Proposal

An `AppBar` within a `PopupRoute` should likely display a `CloseButton` because it's displayed over top of another page and `BackButton` doesn't make much sense.

Current:
<img width="398" alt="Screen Shot 2020-07-10 at 4 37 33 PM" src="https://user-images.githubusercontent.com/6323077/87200984-b2ac3000-c2cb-11ea-9de4-cc62aae3020c.png">

Proposed:
<img width="392" alt="Screen Shot 2020-07-10 at 4 37 05 PM" src="https://user-images.githubusercontent.com/6323077/87200985-b2ac3000-c2cb-11ea-9ac4-928acafe42ae.png">

**Comment by shihaohong** [comment]
Thank you for the proposal. As mentioned in the PR you submitted, I think that using an `AppBar` in the context of a `PopupRoute` is not advisable since it's made for use at the top of a screen, particularly for new fullscreen pages. `PopupRoute` is typically used for modals or dialogs that occupy a portion of the screen. Using a `Row` with custom content that suits the needs of the pop up seems more appropriate for this behavior.

I'll close the issue for now, but feel free to reopen with discussion points if I've missed something!
