### ISSUE TITLE
Add prefixIcon and suffixIcon parameters to InputDecoration.collapsed

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter#61331]
InputDecoration has a lot of parameters that helps us to customize TextField and TextFormField.

![image](https://user-images.githubusercontent.com/20110433/87254272-dac89a00-c457-11ea-86e2-449a65926430.png)

when using **InputDecoration.collapsed**, it's missing a lot of parameters that could help us to customize more easily the widget.

![image](https://user-images.githubusercontent.com/20110433/87254266-c71d3380-c457-11ea-9011-2de97ece3195.png)

I would like to request if is it possible to add at least this two parameters:  prefixIcon and suffixIcon.

Thank you.

**Comment by justinmc** [comment]
@HansMuller Any idea if prefix and suffix were intentionally disabled for `InputDecoration.collapsed`?

@d-apps Keep in mind that you can achieve the same thing by passing `isCollapsed: true` to a the default InputDecoration constructor.

**Comment by bleroux** [comment]
@justinmc
I’m looking at `InputDecoration.isCollapsed,` `InputDecoration.isDense` and `InputDecoration.contentPadding`. I read some previous discussions on this topic, for instance https://github.com/flutter/flutter/issues/46160#issuecomment-596245331.

To summarize the history behind `isCollapsed` :
- `InputDecoration.collapsed` was added long ago in https://github.com/flutter/flutter/pull/9119. And the `isCollapsed` property was not exposed in the default constructor.
- In https://github.com/flutter/flutter/pull/55911, the `isCollapsed` property was added to the default constructor which gave more flexibility but also opened up to many bogus cases (because there are no asserts to restrict its usage, for instance it is valid to set `isCollapsed` to true while providing a label, but it will render badly).

The less disruptive way to go is probably to consider adding checks (assert) to the default `InputDecoration` constructors (might be tricky because some people perhaps rely on the current flexibility) and to try to adapt the rendering logic to use cases that we find acceptable (for instance, specifying prefix/suffix icons for a collapsed decoration). 

This might increase even more the complexity of the rendering logic but It looks like we can’t afford to get back to the more restricted constructor (this kind of constructor is interesting because its signature clearly states the expected restrictions and it is also a clear entry point where the feature can be documented. But because one can bypass the constructor restriction by using copyWith it is not a complete solution ).

**Comment by justinmc** [comment]
@bleroux Exposing the isCollapsed parameter may have been a bad idea, I'm on board with removing it if we can get away with it.
