### ISSUE TITLE
Where can I find the code to add breakpoint for this error `flutter: Fatal Error: Callback lookup failed`

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#61336]
I got this error message when I use this plugin [audioplayers](https://github.com/luanpotter/audioplayers)

I see this [error](https://github.com/luanpotter/audioplayers/issues/344) in this library, and also get the same error when I using this plugin.

My question is: 

1. How can I add breakpoint for this error, I think this message is from flutter lib, just couldn't find that line of code.
2. Also this error is not so clear that:  this `callback` is belong to flutter side or native side ?

**Comment by darshankawar** [comment]
Hi @jerryzhoujw,
The plugin you mentioned seems to be a 3rd party plugin. I suggest you raise this issue against that plugin's repo (https://github.com/luanpotter/audioplayers/issues).
Closing this ticket, since this issue isn't related to Flutter itself. 
If you disagree, please write in the comment and I'll reopen.
Thanks.

**Comment by jerryzhoujw** [comment]
Hi @darshankawar , do you means this error is nothing related to flutter ?

My question actually was  how to find out the error's stack trace. If I know more information when error happened, I can fix it by myself.
