### ISSUE TITLE
Scrollbar doesn't change color with dark theme

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#61364]
## Steps to Reproduce

Using a Scrollbar in a Cupertino app doesn't change it's color to white when the app is using a dark theme.

See this comment for the original bug report: https://github.com/flutter/website/issues/4306#issuecomment-656468600

**Comment by darshankawar** [comment]
Hi @johnpryan, This seem to be related to [36603](https://github.com/flutter/flutter/issues/36603).
Although that ticket is closed, [this](https://github.com/flutter/flutter/issues/36603#issuecomment-515490742) comment from the ticket probably shows we can't change scrollbar color without modifying source code.
I see that there's a new ticket opened to propose this change, [61362](https://github.com/flutter/flutter/issues/61362).

I am closing this since the similar issue is mentioned in 61362.
If you disagree, please write in the comment and I'll reopen.
Thanks.

**Comment by johnpryan** [comment]
I'll update https://github.com/flutter/flutter/issues/61362 to include this.

**Comment by salaryazdjerdi** [comment]
Hi @johnpryan and @darshankawar, I know this issue has been discussed But I don't see a good reason why iOS scrollbar color is not changed to light color on a dark background. On my app the iOS scrollerBar is not visible and I have no way to change it. This is definitely a bug and should be addressed.

**Comment by johnpryan** [comment]
@salaryazdjerdi I think @darshankawar is proposing that we consider that part of https://github.com/flutter/flutter/issues/61362
