### ISSUE TITLE
Fuchsia unit test SessionConnectionTest.SimplePresentTest flaky timeout

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#61463]
This test suffers flaky time outs. We have observed it happening on the same host but with different attached devices.

https://chromium-swarm.appspot.com/task?id=4d53a08f6b3b6510
https://chromium-swarm.appspot.com/task?id=4d63d45454be2610

Tests here:

https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/flutter/tests/session_connection_unittests.cc#L57

@farchond writes:
> So if Flutter is having trouble connecting to some system services, that timeout error would make sense as the session_connection tests spin up a Scenic and connect to it. Display issues could cause Scenic to not be brought up correctly, as Scenic needs to connect to the real display IIRC

Marking P0 because this flake is blocking an unhealthy number of engine PRs including rolls from Skia and Dart.

@iskakaushik @gw280 @godofredoc @arbreng

**Comment by zanderso** [comment]
Assigning @godofredoc on the assumption that this is an issue with the attached physical display.

**Comment by iskakaushik** [comment]
Downgrading to P1, while I attempt to get the logs.

**Comment by farchond** [comment]
Currently, I believe the issue has something to do with Scenic startup taking too long. Locally I would consistently fail the test, but consistently pass if I slept for a long time, such as 10 seconds before making requests to Scenic. Sleeping for 1 second was not enough to pass.

It's possible that when the test runs on the bots, we start making requests at some interval that fails intermittently.

One thing that I still do not understand is why the test appears to time out on the bots, given that there are no synchronous calls. Locally I do not observe timeouts, but rather just the test logic failing on line 76 of session_connection_unittests.cc since Scenic did not initialize in time to handle requests.

My next step is to repro on the bots, with sleeps of different quantities to see if the local issue is the same as the one observed on the trybots.

**Comment by iskakaushik** [comment]
Getting sys-logs from Fuchsia test runs:

1.  Follow instructions in [Flutter LUCI](https://g3doc.corp.google.com/company/teams/flutter/luci/SITEMAP.md?cl=head) to set up a dev environment to kick-off try jobs.

2.  Patch the following changes to your change: <https://github.com/flutter/engine/pull/19756/files>

3.  Make changes to re-enable the tests or any other local changes.

4.  To kick off the try jobs on a commit that you made to your remote, do something like:\
    `led get-builder 'luci.flutter.try:Linux Fuchsia' | led edit -p 'git_url="https://github.com/<github_user_name>/engine"' -p 'git_ref="<commit_hash>"' -p 'clobber=true' | led launch`

5.  You will get a swarming task url like: <https://chromium-swarm.appspot.com/task?id=4d6cbc58f0cc1310>.

On the right iframe, cmd + click on "task UI: flutter_fuchsia_unittests". You should see the logs after the test runs.

**Comment by chinmaygarde** [comment]
The linked patch has landed. Marking as fixed.
