### ISSUE TITLE
[cocoon] GitHub checks API shows hard coded flutter dashboard text on LUCI checks in cocoon

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#61559]
![Cocoon PR with LUCI check showing flutter-dashboard info](https://user-images.githubusercontent.com/2148558/87576921-f1086d00-c686-11ea-82f9-c5ce0a81ae34.png)

The check shows info for Flutter's post submit dashboards, however, this check is run as presubmit. Instead, I expect to be redirected to the luci page for that check.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/cocoon/pull/845/checks?check_run_id=874284644 for an example

**Comment by godofredoc** [comment]
If the state of the checks is "Queued" then the link to the dashboard is expected as we don't have a task yet:

![image](https://user-images.githubusercontent.com/54371434/87582661-91628f80-c68f-11ea-899e-e48bd78764a9.png)

The real problem was that checks were not being processed. Marking this as duplicated of https://github.com/flutter/flutter/issues/61560
