### ISSUE TITLE
Would like a product definition of the 1st hour/zipfile/offline workflow

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#61575]
Currently the Zipfiles we upload to flutter.dev include everything from the flutter repo, most of the pub dependencies, and many of the pre-cache artifacts. This lead to a massive regression in total size when the new_gallery was included: https://github.com/flutter/flutter/issues/61487

I initially proposed removing the update-packages call, which grabs all of the dependencies for the flutter repo (examples, tests), and only updating the dependencies for the template flutter app and the flutter tool. There was some push back on this because it was claimed that it would break the offline workflow. Unfortunately there are no tests or definitions of what the offline workflow is, so I cannot confirm anything. In fact, it is highly likely that the offline workflow is already broken today.

Before any improvements can be made here, we need a product definition - what actions should a user that downloaded the flutter zip but without internet be able to perform? From there we can figure out how to write integration tests to determine if we currently support this workflow, and in the future how we can trim the zip size.

**Comment by gspencergoog** [comment]
I'd also like to put out the option of just dropping this as a supported workflow.  We initially supported it so that developers in China who were hamstrung because of not being able to access (or having very slow access) to our pub server could have a better experience.  For a while we have had a (maintained by a third party) pub mirror in China, so perhaps the workflow is no longer needed.

There are surely folks who find the pre-loaded nature of the archives convenient, but I suspect not many would notice if we suddenly stopped including all the pub dependencies, and more users might prefer that the initial download is ~800MB smaller.

If we do end up keeping it, we might be better to generate two archives: one before running pub in the gallery, etc. that is slim, and one that is meant for offline use that includes the world. The offline archive could also include a copy of the offline docs.

**Comment by gspencergoog** [comment]
Also, if we don't support offline as a workflow, we can also drop building the offline docs archive and the Dash/Zeal docsets, which have been some work to keep going (for unknown benefit to users).

**Comment by jonahwilliams** [comment]
There is also the question of whether or not we will expand this to include pre-cached web, linux, macOS, windows, fuchsia artifacts

**Comment by timsneath** [comment]
Adding @csells and @mit-mit also. 

I'd generally optimize for smaller initial size for all, rather than reduced friction in China. China users will need a working cache eventually anyway, although if we're going to suddenly change the experience we should make sure the user messaging is clear. 

We could also advertise `flutter precache` better, so that someone getting on a plane (hah!) can make sure they know how to grab key dependencies in advance.

Why is this suddenly an issue? Why did the new_gallery get included? Can't we simply remove it for now?

**Comment by jonahwilliams** [comment]
> Why is this suddenly an issue? Why did the new_gallery get included? Can't we simply remove it for now?

I think it's been a problem for a while, but the large increase from gallery is the breaking point. There have been other issues that have come up that we haven't really dealt with - such as the presence of the pub-cache override that we've introduced.

And of course, without really knowing what the cached zips should be able to do, who is to say that any changes I make to them will leave them in a working state.

**Comment by christopherfujino** [comment]
So `flutter update-packages` has a `--consumer-only` flag, which presumably is what we could safely update the `prepare_packages` script to use:

```
    // "consumer" packages are those that constitute our public API (e.g. flutter, flutter_test, flutter_driver, flutter_localizations).
    if (isConsumerOnly) {
      if (!isPrintTransitiveClosure) {
        throwToolExit(
          '--consumer-only can only be used with the --transitive-closure flag'
        );
      }
      // Only retain flutter, flutter_test, flutter_driver, and flutter_localizations.
      const List<String> consumerPackages = <String>['flutter', 'flutter_test', 'flutter_driver', 'flutter_localizations'];
```

IDK if this flag works, but I found it in the code...

**Comment by gspencergoog** [comment]
Since this is a P1 bug, could we have a quick meeting to formulate a decision? I can set it up.

**Comment by jonahwilliams** [comment]
SGTM

**Comment by jonahwilliams** [comment]
Result of meeting:

- Small download -- no arbitrary choices that cause friction, easy to get hold of
- Make it possible to precache what you need for offline usage
- Be platform-neutral: e.g. support a world of Linux desktop apps where user may never write a mobile app

AI:

- Download ZIP with repo and precompiled tools
- Minimize size by removing precached artifacts and integration test dependencies
- Single command to precache enough that flutter create and flutter run can be run offline on a target platform

**Comment by jonahwilliams** [comment]
Filled engineering work

https://github.com/flutter/flutter/issues/61751
https://github.com/flutter/flutter/issues/61753

Will file new issues for documentation and verification once we're there
