### ISSUE TITLE
Typo in Flutter Accessibility page

### ISSUE THREAD

**Issue by vanillabeach** [flutter/flutter#61606]
There's a typo on flutter.dev, specifically at https://flutter.dev/docs/development/accessibility-and-localization/accessibility#inspecting-accessibility-support

```In the Accessibility Inspector, select Audit in the toolbar, and then select Run Audio to get a report of potential issues```

should read

```In the Accessibility Inspector, select Audit in the toolbar, and then select Run Audit to get a report of potential issues```

(replace "Audio" with "Audit")

Nice documentation btw :)

**Comment by darshankawar** [comment]
Hi @vanillabeach,
I think it should read `Audio`, since the`Accessibility Inspector` in Xcode is used as a voiceover for the elements and has `Play` button for it, so I think the statement / word is correct, unless I missed anything that I didn't understand.

![Screen Shot 2020-07-16 at 4 51 31 PM](https://user-images.githubusercontent.com/67046386/87665775-15e30a00-c785-11ea-80f8-498be84d18e0.png)

**Comment by vanillabeach** [comment]
Hi @darshankawar ,

Thanks for your quick response :)

I assumed it was **Audit** based on the context of the instructions, and the option in the toolbar (see tooltip in screenshot).

<img width="360" alt="Screen Shot 2020-07-17 at 9 36 52 AM" src="https://user-images.githubusercontent.com/2682461/87766729-87689a00-c811-11ea-8f2d-e9cc3a40132c.png">

Either way, feel free to close this issue if you think it does not need changing.

Thanks

**// J**

**Comment by darshankawar** [comment]
@vanillabeach  ah I see :-) It should be `Run Audit` in the docs.

![Screen Shot 2020-07-17 at 3 02 27 PM](https://user-images.githubusercontent.com/67046386/87771947-afbabd80-c83e-11ea-9235-866474b66822.png)
