### ISSUE TITLE
 Connecting mis-matched Flutter platforms between blaze and device

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61628]
https://b.corp.google.com/issues/161381934.

**Comment by chinmaygarde** [comment]
Once the host side tooling attaches to a running Flutter instance, snapshots sent to the target are not platform specific. From the internal issue, it seems like the issue is with Blaze rules for attaching to running instance. These aren't vended or maintained by Flutter. Can you confirm this isn't an issue with `flutter attach`?
