### ISSUE TITLE
Error messages are cut off on Android.

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#6168]
Below is a screen shot of a flutter error message. It's annoying to try and read as it's drawn behind the status bar, and it's also drawn behind the "SLOW MODE" banner.

It'd be nice if the error message / text wasn't obstructed, so it could be easily read.

<img width="642" alt="screen shot 2016-10-02 at 11 38 02 pm" src="https://cloud.githubusercontent.com/assets/871169/19027010/6390ff96-88fa-11e6-9368-b62e92c930d8.png">

**Comment by eseidelGoogle** [comment]
We could do something slightly smarter, but these can be too small/obscured to read for other reasons too.  I guess I've assumed most folks will read these from within the IDE/command line the app was run from?  FYI @Hixie

**Comment by Hixie** [comment]
It's actually just painted instead of the affected widget. It just happens that the widget is under the status bar in this case. (We can't center the message because we don't know how much space we have, or where we are on the screen.)

But the message should also be on the console, anyway. In more detail.

We should make that clearer.

**Comment by ScottPierce** [comment]
Offsetting it down from the top based on the screens DPI would be pretty simple, and would adequately improve readability.

**Comment by abarth** [comment]
Yeah, I think it would make sense to take the device pixel ratio into account when selecting the font size.

Offsetting from the top is tricky because we don't necessarily know where the widget that is experiencing the error is relative to the screen.

**Comment by ScottPierce** [comment]
@abarth I see, so the error appears in the given widget that the error occurs in? So far I've only seen this full screen like this.

**Comment by abarth** [comment]
That's correct.  It's common for the full-screen widget to have an error.  We could try to detect that by seeing if the size of the error widget matches the size of the screen...

It's a little tricky because when this code runs, the system is in some sort of error state, so we want to minimize the amount of logic and assumptions this code makes.  Several people have brought this issue up, so we should try for something better than what we have currently though.

**Comment by Hixie** [comment]
I guess the size does still get constrained to the constraints, so we could compare it against the screen size and if it's an exact match assume that we're full-screen. That's a bit sketchy but the number of false positives would be low (hopefully?).

The font size is intentionally small because the message is long, but we could make it bigger.

The error is in the console (in the logs, see `flutter run`). It's not expected that people will actually read the error from the screen. Maybe we should only show the first line of the error message and then say to look at `flutter logs` or something.

**Comment by abarth** [comment]
Yeah, I'd rather have a legible first line then a long run of unreadable text.  :)

**Comment by eseidelGoogle** [comment]
My understanding was @xster recently landed a patch to improve this?  Is this bug still desired?

**Comment by xster** [comment]
It's the same issue as #3091. Please `flutter upgrade` and take a look again.
