### ISSUE TITLE
Flutter WebView - Android System WebView Outdated

### ISSUE THREAD

**Issue by mellorafael** [flutter/flutter#61758]
Hello, 
I´m building an application for an Android 7.1 device with a Flutter WebView. 
But this device doesn´t have access to the Play Store to update the Android System Webview, so i get a outdated Chrome navigator user agent (Chrome 53) (my web page loses a good user experience and i have to use polyfill to many things)

Is it possible to Flutter WebView use Androidx Support to get a updated Android WebView ? or should i try something else?

  
Thanks

**Comment by TahaTesser** [comment]
Hi @mellorafael 
This seems more related to the itself and not being able to use updated webview, `flutter_webview` simply launches native webview since you cannot update native webview, i am sure this is related `flutter_webview` itself 

You can try other webview packages but this might not help at all instead you can use [url_launcher](https://pub.dev/packages/url_launcher) and launch your link in your browser

Closing, as this isn't an issue with `flutter_webview` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
