### ISSUE TITLE
Cupertino style checkbox (multi-selection)

### ISSUE THREAD

**Issue by furkansarihan** [flutter/flutter#61789]
## Use case

Contribute to IOS look and feel.

## Proposal

Match the look and feel of an IOS app with implementing a Cupertino style Checkbox.

<img src="https://user-images.githubusercontent.com/27918319/88031930-f01f8180-cb45-11ea-9137-bca192c2e723.gif" width=40%>

## My Flutter App on multi-selection

<img src="https://user-images.githubusercontent.com/27918319/87851252-99c10180-c8ff-11ea-9beb-22a7e8483924.jpg" width=40%>

## Known Native App on multi-selection

<img src="https://user-images.githubusercontent.com/27918319/87851397-f5d85580-c900-11ea-8be2-cd1814514734.jpg" width=40%>

See #102813 for single-selection

**Comment by ManuLpz4** [comment]
Hi!
Can you post zoomed videos to help me make it?

**Comment by furkansarihan** [comment]
@ManuLpz4 Hi! I updated issue with an animated gif. It really simple compared to original material styled one.

**Comment by ManuLpz4** [comment]
@furkansarihan thank you so much, I'll be working on it to PR :)

**Comment by ManuLpz4** [comment]
@furkansarihan I was doing a little research (because I don't have an iPhone) and the Checkbox component does not exist natively, in that case it's created by WhatsApp if I'm not mistaken.

Anyway, you can visit the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/controls) to see all the native components, and if you still want to use that checkbox you can find a similar one in this [pub package](https://pub.dev/packages/circular_check_box).

I hope I've helped you, have a great day 😄

**Comment by furkansarihan** [comment]
Thank you.

I just find a solution from [this issue](https://github.com/flutter/flutter/issues/33916)

With [this package](https://github.com/virskor/flutter_sfsymbols) we can use combinations of these icons;

- circle
- checkmark_circle
- checkmark_circle_fill

Icons can be viewed [here](https://framework7.io/icons/)
