### ISSUE TITLE
pub upgrade error

### ISSUE THREAD

**Issue by Sadique-Ilyas** [flutter/flutter#61828]
Waiting for 0 seconds, press CTRL+C to quit ...
Error: 'pub upgrade' still failing after 10 tries, giving up.
The system cannot find the batch label specified - final_exit
Building flutter tool...
Running pub upgrade...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9
tries left)

**Comment by shameemreza** [comment]
Looks liek your antivirus creating the issue. You can test by disabling your antivirus since its blocking flutter.dev and run flutter doctor

You also can delete the cache folder located in flutter/bin directory. And after then run in command line pub cache repair.

And if you are using flutter from China or behind a firewall, make sure you check this doc: https://flutter.dev/community/china

Hope your issue will resolve.

**Comment by Piyushhhhh** [comment]
Can you send your pubsec.yaml here ?

**Comment by iapicca** [comment]
HI @Sadique-Ilyas 
does @shameemreza [solution](https://github.com/flutter/flutter/issues/61828#issuecomment-660715732) solves the issue?
If doesn't please provide your `flutter doctor -v` and your `pub upgrade -v` output;
Thank you

**Comment by Sadique-Ilyas** [comment]
It is working fine now, antivirus was creating the problem ! Thank u guys, u all r doing great job
