### ISSUE TITLE
PageView does not scroll as expected when using unfocus

### ISSUE THREAD

**Issue by NiamhG** [flutter/flutter#61827]
## Steps to Reproduce

1. Run the below example. 
2. Enter something into first text field, press next
3. Enter something into second text field, press next

You will notice that it starts to scroll to the 3rd item, but then bounces back to the 2nd item for some reason. I am not sure why and can't figure out how to even debug this or if it's an issue with flutter.

However if you comment out the unfocus() then it works as expected (which leads me to believe it's something up with flutter).
```
import 'package:flutter/material.dart';


final MainScreenViewModel model = MainScreenViewModel();

class MainScreenView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: SafeArea(
      child: Scaffold(
        body: Column(
          children: <Widget>[
            Items(),
            _PreviousNextButtons(),
          ],
        ),
      ),
    ));
  }
}

class _PreviousNextButtons extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        RaisedButton(
          onPressed: model.isFirstItem() ? null : () => model.previousItem(),
          child: const Text("Previous"),
        ),
        RaisedButton(
          onPressed: () => model.nextItem(),
          child: const Text("Next"),
        )
      ],
    );
  }
}

class Items extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: PageView(
          physics: const NeverScrollableScrollPhysics(),
          controller: model.pageController,
          scrollDirection: Axis.vertical,
          children: model.itemFormKeys.mapIndexed((item, index) {
            return Form(
              key: model.itemFormKeys[index],
              child: Column(children: <Widget>[
                Text(model.items[index]),
                _NumberField(),
              ]),
            );
          }).toList()),
    );
  }
}

class _NumberField extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 200,
      height: 100,
      child: TextFormField(
        controller: TextEditingController(),
        keyboardType:
            const TextInputType.numberWithOptions(signed: true, decimal: true),
        autofocus: false,
      ),
    );
  }
}

class MainScreenViewModel {
  int _currentItemIndex = 0;
  final PageController pageController = PageController();
  final List<String> items = ["1", "2", "3"];
  final List<GlobalKey<FormState>> itemFormKeys = [
    GlobalKey<FormState>(),
    GlobalKey<FormState>(),
    GlobalKey<FormState>()
  ];

  void previousItem() {
    if (_currentItemIndex != 0) {
      _currentItemIndex--;
      pageController.animateToPage(
        _currentItemIndex,
        curve: Curves.linear,
        duration: const Duration(milliseconds: 500),
      );
    }
  }

  void nextItem() {
    FocusManager.instance.primaryFocus.unfocus();
    _currentItemIndex++;
    pageController.animateToPage(
      _currentItemIndex,
      curve: Curves.linear,
      duration: const Duration(milliseconds: 500),
    );
  }

  bool isFirstItem() => _currentItemIndex == 0;
}

extension IndexedIterable<E> on Iterable<E> {
  Iterable<T> mapIndexed<T>(T Function(E, int) f) {
    var i = 0;
    return map((e) => f(e, i++));
  }
}
```

**Expected results:** It should scroll to the 3rd item

**Actual results:** Scrolls to the 3rd item, then scrolls back up to the 2nd item.

<details>

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale en-GB)
    • Flutter version 1.17.5 at A:\src\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at A:\AppData\Android
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = A:\AppData\Android
    • Java binary at: A:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at A:\Programs\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

```

</details>

**Comment by darshankawar** [comment]
Issue reproducible on latest Flutter dev. After inputing in 2nd textfield with keyboard open and tapped on `Next` button, the 3rd textfield doesn't scroll up and bounces back.  Although if we input in 2nd textfield, tap on Done on keyboard, then tap on `Next`, then 3rd textfield scrolls up properly. 

[61827_withunfocus.mp4.zip](https://github.com/flutter/flutter/files/4947492/61827_withunfocus.mp4.zip)
[61827_wo_unfocus.mp4.zip](https://github.com/flutter/flutter/files/4947496/61827_wo_unfocus.mp4.zip)

**Comment by darrenaustin** [comment]
cc @gspencergoog

**Comment by gspencergoog** [comment]
What platforms have you tried this on? It appears to work fine on Linux and web.

For instance: here's a Dartpad that seems to work:https://dartpad.dartlang.org/def10d8f8eaf943e745550f33102104a

(I modified your buttons to be stateful widgets so that they would properly update their disabled state, but it worked without that change too)

**Comment by gspencergoog** [comment]
And it appears to work OK on Android too.

**Comment by NiamhG** [comment]
@gspencergoog Now i'm very confused! I'm testing it on my Android phone (P20 Pro), and I copy and pasted everything from the dart pad and it is still happening. A video of it https://streamable.com/cfrw91

Happy to provide anymore information which might be useful

**Comment by gspencergoog** [comment]
I tried this again, and I was able to reproduce it on master.  The specific steps to reproduce it are:

1) launch the app (I used an Android Moto G4)
2) tap the first field.
3) enter a character
4) (without hitting the check-mark/done button on the keyboard) press the "Next" button.
5) enter a character in the second field.
6) (without hitting the check-mark/done button on the keyboard) press the "Next" button.

It will then bounce between the 2 and 3 screens, and back to 2.

Looking into why.

**Comment by gspencergoog** [comment]
OK, I think I know what the problem is here.  It less to do with focus, and more to do with the way PageView operates. It only affects platforms that have a soft keyboard (like Android).

The problem is that once the focus leaves the text field, the soft keyboard disappears.  When the keyboard disappears, it changes the size of the viewport for a "page".  But because the `PageView` has already calculated the offset to scroll to with a viewport that has a keyboard visible, it keeps animating to that offset. When it gets there, that offset is no longer the correct offset for the top of page "3", because the keyboard is now gone, and the pages are different sizes.  The page view then applies the `PageScrollPhysics` to make sure that it ends up aligned on a particular page, instead of somewhere in between, and since the pages are now different sizes than they used to be, the destination offset now corresponds to page 2 instead of page 3.

My simplest suggested workaround would be to not drop the keyboard between changing pages by calling `unfocus`, as that would keep the keyboard from changing state while the page scrolls. (Users don't generally like having to keep calling back the keyboard all the time anyhow.)

As an aside, calling `primaryFocus.unfocus()` could easily do something that you don't expect if the focus is actually on a focus scope, or a widget other than the text field.  You'd be better off calling unfocus on a focus node that you know is on one of the input fields.

**Comment by NiamhG** [comment]
Thanks for taking a look @gspencergoog 

I suppose there are 2 reasons why I am wanting this functionality. 

1) In the example I gave, there are 3 text fields. However, in my actual app, it could go for example text field -> radio buttons -> text field. As a user, I don't think I would expect/want the keyboard to be up for the radio buttons, which is when I would unfocus.

2) I have a bug when the following happens:
- Tap first text field
- Enter some text e.g. "foo"
- Press next
- Keyboard will still be open, and without tapping on anything, type something e.g. "bar". 

As the focus is still on the first text field, it will enter the text there, and so the first text field will have "foobar", even though the user can't see that text field anymore.

I am not very knowledgeable on how focus works and best practices (should do some reading), so I may be handling this wrong. If you have any suggested workarounds or best practices, then I would really appreciate that.

Thanks for the extra tip as well!

**Comment by gspencergoog** [comment]
You could try placing a `FocusTraversalGroup` around each `Form`, and setting the `descendantsAreFocusable` attribute on the group to be true only if the group is the "current" one. I think that will solve your focus problem (that the focus stays on the field in the first page), but it won't solve the problem of the keyboard disappearing and changing the viewport during the `PageView` transition.

Are there UI changes you can make that would make it easier to do what you want?  Like maybe scrolling the page view horizontally instead of vertically?  Then the change in the keyboard/viewport shouldn't make any difference to the width of the viewport and it will scroll to the right place.

**Comment by NiamhG** [comment]
Thanks for the tip.

Unfortunately this pageview is in another pageview going the opposite way, so I think no matter what I'm gonna have this issue. Might have to rethink how I'm handling the UI here.

Thanks for your help, i'll close this since I at least understand what's happening now.
