### ISSUE TITLE
Hot restart hangs when a breakpoint is hit during a restart request

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#61906]
From https://github.com/Dart-Code/Dart-Code/issues/2345

The hot restarting the following application with a breakpoint set will cause flutter_tools to hang:

```dart
import 'package:flutter/material.dart';

void main() {
  foo();
  foo();
  runApp(SizedBox());
}

void foo() {
  // put breakpoint here
  print('foo');
}
```

Hot restart works by creating a new isolate rather than using hot reload functionality built into the VM, but I noticed that the original isolate remained the sole isolate even after a restart which doesn't seem correct. Looking at the hot restart code in flutter_tools, it appears that [we try to resume the isolate if it's paused so the embedder is able to kill it](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L504). If we set the breakpoint from the example and do a hot restart, we resume the isolate and then immediately hit the same breakpoint.

We should either investigate the engine code to determine why the isolate needs to be resumed before being killed or update flutter_tools to behave properly by disabling breakpoints or ensuring we're resumed before performing a hot restart.

**Comment by jonahwilliams** [comment]
I did recently touch that code but I don't really have context into why that is/was required. The first step to trying to fix this would just be to remove that logic and see what breaks.

Thanks for the reduced example, I'll try and take a look this week

**Comment by jonahwilliams** [comment]
Confirmed that the restart still hangs when the tool makes the runInView request, which would indicate something in the engine

**Comment by jonahwilliams** [comment]
So the issue here seems to be that we attempt to run the runInView request from the UI thread, but that is blocked when the root isolate is paused. I'm not sure if it is feasible to move runInView to a different thread, at least in the context of a hot restart and not the initial run.

We can't just kill the isolate either, as this seems to take down the whole engine.

**Comment by jonahwilliams** [comment]
If this isn't feasible, we could instead request all of the breakpoints for a paused isolate and remove them

**Comment by jonahwilliams** [comment]
FYI @chinmaygarde if you have any insight into the threading requirements for hot restart

**Comment by chinmaygarde** [comment]
> I'm not sure if it is feasible to move runInView to a different thread, at least in the context of a hot restart and not the initial run.

This is not feasible because the specific engine components are not thread safe (the DartIsolate engine peer itself is not thread safe). If there was a native Dart API that we could call to manually unpause an isolate from a different thread before calling run in view, that would work really well as we could unconditionally unpause an isolate before killing it. In its absence, Jonahs suggestion to request and remove all existing breakpoints seems like a viable solution.

**Comment by jonahwilliams** [comment]
> This is not feasible because the specific engine components are not thread safe (the DartIsolate engine peer itself is not thread safe

Makes sense, thanks for the explanation. I'm going to look into removing breakpoints for now, but I'll file a issue in the Dart SDK for a new API
