### ISSUE TITLE
Add toolbarHeight to AppBarTheme, then we can set toolbarHeight once to whole app

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#61959]
## Use case
```dart
ThemeData(
    appBarTheme: AppBarTheme(
       toolbarHeight: 48,
    ),
);
```

## Proposal
@AyushBherwani1998 [PR#59405](https://github.com/flutter/flutter/pull/59405) only add toolbarHeight to AppBar. We need more support.

**Comment by AyushBherwani1998** [comment]
@Piinks can I work on this? This would be pretty straight forward to fix. I'll also need to move the assertion for `collapsedHeight` from the constructor of `SliverAppBar` to the `_SliverAppBarState.build` since it depends on the `toolBarHeight`.

https://github.com/flutter/flutter/blob/ddb8e6e3bfef90c8674ac0ab5508e581a3873dae/packages/flutter/lib/src/material/app_bar.dart#L1064

**Comment by Piinks** [comment]
> @Piinks can I work on this? 

Sure! You are always welcome to submit a PR! :)

**Comment by AyushBherwani1998** [comment]
Hey @Piinks,
I did check if we could add the `toolbarHeight` in the `AppBarTheme` and this will be the blocker.

https://github.com/flutter/flutter/blob/ddb8e6e3bfef90c8674ac0ab5508e581a3873dae/packages/flutter/lib/src/material/app_bar.dart#L218

Since the `preferredSize` depends on the `toolbarHeight` checking `AppBarTheme.toolbarHeight` should be necessary. We can't move it to the `build` method since `Scaffold` uses `AppBar.preferredSize` and moving it to build, means `Scaffold` will always get the `null` value resulting breakage in `Scaffold`.
https://github.com/flutter/flutter/blob/ddb8e6e3bfef90c8674ac0ab5508e581a3873dae/packages/flutter/lib/src/material/scaffold.dart#L2391

**Comment by Piinks** [comment]
Ah, I see. We'd have to find a way to satisfy the Scaffold first. Thanks for looking into it!

**Comment by v7lin** [comment]
this is my idea
```dart
abstract class PreferredSizeWidget implements Widget {
  @deprecated
  Size get preferredSize;

  Size getPreferredSize(BuildContext context);
}
```

**Comment by AyushBherwani1998** [comment]
@Piinks Do you think it is a good idea to have two different properties in `Scaffold`, for an `AppBar` and `PreferredSizeWidget`? We can have assertions to make sure users can only use a single property at a time. If we have a property that gives us access to `AppBar` we can access the `AppBar.toolbarHeight`, `AppBar.bottom.height`, and `AppBarTheme` to calculate the max_height for the `Scaffold`.

We can have few conditional statements to check which property is null, do some calculations. Doing this can be a breaking change so I don't have a good feeling to go with this approach just to introduce `toolbarHeight` in the `AppBarTheme`. WDYT?

I'll try to look at code, and see if we can have any other solution without breaking the APIs. Also, if you have any leads to overcome the issue, let me know. I'll be happy to try it out.

**Comment by rami-a** [comment]
Fixed with https://github.com/flutter/flutter/pull/80467
