### ISSUE TITLE
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

### ISSUE THREAD

**Issue by HLGB26** [flutter/flutter#62145]
How do i save a reference, somebody provide me a code , i am quite new to flutter and the documentation is not helping

**Comment by darshankawar** [comment]
Hi @HLGB26,
This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this.
You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by prasant10050** [comment]
@darshankawar We are also getting the same issue.
As per documentation, This method should not be called from State.dispose because the element tree is no longer stable at that time. To refer to an ancestor from that method, save a reference to the ancestor in State.didChangeDependencies. It is safe to use this method from State.deactivate, which is called whenever the widget is removed from the tree.
