### ISSUE TITLE
Codelab Building beautiful UIs with Flutter mistake on page 4 (Build the main user interface)

### ISSUE THREAD

**Issue by mbilalakmal** [flutter/flutter#62228]
Under the heading Build the chat screen, the first sub-heading [(Create the FriendlyChatApp widget:)](https://codelabs.developers.google.com/codelabs/flutter/#3)

> 5. Start typing ChatScreen, and select ChatScreen() from the popup. (Choose the ChatScreen entry that is marked with an equal sign inside the yellow circle. This gives you a class with empty parentheses, rather than a constant.)

The popup will only appear if the ChatScreen widget has already been created (which is done in the next sub-section).
So the steps of the next sub-section should be done before this step.

> 1. Under the FriendlyChatApp class, around line 27, start typing stless. The editor asks if you want to create a Stateless widget. Press Return to accept. The boilerplate code appears, and the cursor is positioned for you to enter the name of your stateless widget.

> 2. Enter ChatScreen.

**Comment by avk29** [comment]
Hi, I would like to work on the issue. Would appreciate if you could give me instructions on the same.

**Comment by cv692001** [comment]
Hey@mbilalakmal I am very new to contributing It will be very nice of you if you can help me how to proceed

**Comment by maheshmnj** [comment]
@TahaTesser could you  please point me out to the source code of this codelab I dont see it in flutter/website repo

**Comment by TahaTesser** [comment]
@maheshmnj  https://github.com/flutter/codelabs

**Comment by Roshan13046** [comment]
I am working on this issue.

**Comment by Roshan13046** [comment]
> @maheshmnj https://github.com/flutter/codelabs

I tried twice to find a particular file where I have to make the changes. But was unable to find.
Can you please help me to find it?

**Comment by maheshmnj** [comment]
@Roshan13046 I searched a bit back then and found that the source code is not public for that codelab as mentioned here https://github.com/flutter/friendlychat-steps/issues/89

**Comment by Roshan13046** [comment]
> @Roshan13046 I searched a bit back then and found that the source code is not public for that codelab as mentioned here [flutter/friendlychat-steps#89](https://github.com/flutter/friendlychat-steps/issues/89)

Thanks!

**Comment by Roshan13046** [comment]
> @Roshan13046 I searched a bit back then and found that the source code is not public for that codelab as mentioned here [flutter/friendlychat-steps#89](https://github.com/flutter/friendlychat-steps/issues/89)

Does this mean none of the codelabs issues can be fixed as their source code repo is not open source?

**Comment by Abhishek01039** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
@Roshan13046 the source code for Flutter codelabs is in the [flutter/codelabs](http://github.com/flutter/codelabs) repository. However, the text content of the codelabs is internal because we utilise Google internal infrastructure to publish it.

**Comment by Silvagni** [comment]
I ran into this same issue 2 years after the issue was first reported.  I believe the instructions are incomplete. Step 4 of the instructions read:

4. Select the block of text after home:. Start with Scaffold( and end with the Scaffold's closing parenthesis, ). Do not include the ending comma.

Step 5 should be reworked to read:

5. Right-click, and select Refactor > Extract > Extract Flutter widget. Enter ChatScreen into the ExtractWidget dialog, and click the Refactor button. The Scaffold code is placed in a new stateless widget called ChatScreen, and MaterialApp( home: is updated to call that class when MaterialApp() is called from the FriendlyChat build() function.

By performing the revised step 5, it produced the ChatScreen class exactly as shown in the sample:

https://github.com/flutter/codelabs/blob/master/friendly_chat/step_04/lib/main.dart

**Comment by domesticmouse** [comment]
Friendly chat has been retired in favour of [Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful).
