### ISSUE TITLE
Passing arguments with Navigator.pushNamed()

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#6225]
It would be nice to have a standard way to pass some arguments to a new route, something like URL query parameters.

Currently, I'm embedding the arguments in the route name:

``` dart
Navigator.pushNamed(context, '/email/thread/$threadId');
```

and using the `onGenerateRoute` callback of `MaterialApp` and manually parsing the route name.

It'd be nice if I could do something like:

``` dart
Navigator.pushNamed(context, '/email/thread', <String, String>{ 'id': threadId, ... });
```

and receive the arguments in the `RouteSettings` object.

**Comment by Hixie** [comment]
Certainly seems better than having to parse the string. I'd probably make it an opaque `dynamic` slot that the route can decide what type to make (so it can be a random struct class of the page's choosing rather than a `Map`).

**Comment by eseidelGoogle** [comment]
Appears this is still a valid request: https://docs.flutter.io/flutter/widgets/Navigator/pushNamed.html

**Comment by ZhangBanger** [comment]
How does `MaterialPageRoute` handle the args? The `WidgetBuilder` type only takes a `BuildContext`, right?

**Comment by gspencergoog** [comment]
I think I'll take a look at this one. It seems pretty straightforward to add a `dynamic arguments` optional argument to the RouteSettings object, and be able to pass one to pushNamed that drops it into the RouteSettings it builds.

For initial routes passed in as strings, my plan is to treat routes with a "?" in them specially:

If the initial route contains a '?', followed by a JSON-encoded object, then the object will be inflated by `JSON.decode()` and sent as a new `arguments` member variable in the `RouteSettings` object sent to `onGenerateRoute`. This is analogous to the query parameter on a URL, but it is JSON encoded, not URL encoded, to allow for more complex data types. If it is not valid JSON, then the whole thing will simply be passed as part of the route (or not?  Maybe it should just always strip anything after a '?' and pass it as a string to the arguments if it can't parse it?)

So passing `"/foo/baz?{"foo": "bar"}"` would pass an argument (of type `dynamic`) set to a `<String, String>{}` in the RouteSettings passed to onGenerateRoute for the initial route, but only for the final route on the stack (i.e. the intervening "/", and "/foo" routes would have no arguments associated with them).

This parsing would happen before we split out the sections of the initial route in the code that Ian just added, of course, because otherwise you couldn't have slashes in your JSON data.

**Comment by Hixie** [comment]
We should think about how this would interact with https://github.com/flutter/flutter/issues/10975.

**Comment by Hixie** [comment]
As a general rule I'm dubious about anything involving `dynamic` and I'm dubious about JSON and I'm dubious about doing anything URL-like, and I'm dubious about doing anything that looks similar to URLs but isn't exactly what URLs do, so the proposal is lighting all kinds of warning lights for me, but I really don't have a better suggestion, so...

Maybe a good place to start would be enumerating concrete use cases.

**Comment by gspencergoog** [comment]
Hmm.  Seems like what we want is a way to configure a "initial route parser" that can decide how to handle an initial route string, and provide a default implementation that does the slash splitting, and an alternate implementation that just uses the unmolested string as a route name.

Any configured route parser would be able to decide what to pass as my proposed `arguments` field of the RouteSettings object when it creates a route.

Other than being part of the refactored slash-splitting parser, I think that my proposed arguments change above would be pretty orthogonal to #10975.

**Comment by gspencergoog** [comment]
You sound dubious. :-)

OK, so a concrete case for just adding the argument field would be to create a new contact card in a contact app by just navigating to a route, passing an argument containing a map of the field values we wanted to create it with.

It wouldn't *have* to be dynamic, but it would be more flexible if it were.  An alternative would be something like <String, dynamic>{} so that you wouldn't be limited to just strings as values, but that limits you to a map, and sometimes a list or a single value would be more appropriate, hence the dynamic.  This part seems pretty reasonable to me, and the dynamic here seems appropriate, since it truly is fairly opaque data. The onGenerateRoute would need to know what to do with it, but nobody else.

As for the parsing of arguments from the initial route, I'm also a bit dubious about the usefulness of that.  The only concrete case I can think of off the top of my head is for driving an app from the "flutter run" command and passing it an initial route with parameters, but that's only for developers really, not a production use case.

I picked JSON because it's easily created by external apps, easily parsed by humans, requires minimal escaping (just the quotes), and can represent complex data.  URL encoding is less flexible and suffers from less readable escaping rules.

Making it URL-like without *being* a URL is potentially confusing, I agree.  Maybe just not using a "?" for the separator would be enough to fix that.

**Comment by Hixie** [comment]
You're mixing collecting use cases and proposing solutions. :-)

So far we have:

* Opening a full-screen dialog to create a new contact with prefilled values.

* Being able to open a route, e.g. an e-mail thread, from elsewhere in the app, without having to serialise and deserialise the data into a single string when it's already represented in a high-level form.

It would be good to get some clarify on these use cases. For example, is the first for opening a dialog or thread from within the app, from another app, from a link in an e-mail or Web site...? In both cases, does it have to be a _named_ route?

**Comment by gspencergoog** [comment]
If it's not a named route, I don't see how a route factory can decide what to do with it.  Maybe I just don't understand what the alternatives would be, however.

OK, sticking to use cases, I think you hit on two more when you were asking about clarification:

- Going to a thread in a messaging app from a link on a web page. (e.g. App Links on Android).
- Creating an email with pre-filled subject and To: field from another app.

**Comment by Hixie** [comment]
You can push any arbitrary route. If it doesn't have to have a name, you can just call `Navigater.push()` and pass a newly-constructed route to which you've passed whatever arguments you want. If, for example, you just want to create a contact from within the app and don't need it to be named or open from another app, then you can just create a ContactRoute or whatever, and pass it whatever data you want.

But maybe there's a reason to prefer named routes?

For the use cases of opening an app link or basically handling a mailto: link, what are the mechanisms that Android and iOS provide for doing these things? What structure will we be receiving messages in?

**Comment by gspencergoog** [comment]
Ahh, I'm starting to get it.  In that case, making your own route subclass seems like it would take care of most use cases inside the app, actually.  Named routes might be still be useful if you wanted to have the same route code handle requests from outside the app, since you might need data from the request to instantiate your custom route class.

For the use cases of opening an app link or handling a mailto: request from another app, it would be in the form of a URI from [App Links on Android](https://developer.android.com/training/app-links/index.html#url-handling), and [URL schemes on iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW1), so it looks like URL encoding would be reasonable after all.  There are mechanisms for transferring larger chunks of data too (e.g. [AirDrop on iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW3) or [Intents on Android](https://developer.android.com/training/sharing/send.html)), so we'd have to decide if we want to handle that with this mechanism or another way. I think it is probably more appropriate to use a different mechanism (I'm thinking here of the differing permissions requirements of the methods), but there's something to be said for the simplicity of having only one way to do something.

**Comment by gspencergoog** [comment]
All of this is making me think that the "initial route parser" I mentioned above is really more of an "external data handler" that takes external data like URIs and AirDrop/Intent requests and converts them into data in a known form to be passed in to the RouteFactories.

**Comment by gspencergoog** [comment]
OK, after looking into what it would take to handle a URL link from the platform, I'm pretty sure that it could be implemented as a platform plugin.  Regardless, it would require a way to pass the URL arguments to the Navigator, as requested in this issue.  So, I propose to add a `Map<String, dynamic>` to the `RouteSettings` object, and associated methods (like adding a similar argument to `pushNamed`) so that implementing such a plugin is possible.  We can open another issue for implementing handling of external URL links, as that is much more involved to implement.  I'll put together a PR.

**Comment by blastrock** [comment]
Any news or workaround for this issue?

**Comment by Hixie** [comment]
We haven't had a chance to look at it yet. It's on our radar for the next few months though.

**Comment by sethladd** [comment]
@blastrock this SO question might be relevant to help in the meantime: https://stackoverflow.com/questions/47419908/how-do-i-pass-non-string-data-to-a-named-route-in-flutter

**Comment by Hixie** [comment]
I have a patch to do this. I need to do more work to test it and make sure the API is reasonable though.

**Comment by MichaelSowah** [comment]
@Hixie that's nice looking forward to the new navigation routing you have been working on

**Comment by Hixie** [comment]
Hmm, my solution was not good enough. I am working on a better solution now.

**Comment by Hixie** [comment]
I'm really struggling to come up with a good way to do this that doesn't involve using `dynamic` in some way. I tried using type arguments on RouteSettings, but that ended up infecting everything that touches routes and it was really ugly. Still searching...

**Comment by Hixie** [comment]
I have a solution for this in my Router patch. I used a TypedDictionary class so that arguments are keyed by type, which keeps things typesafe and extensible (use a custom class for your argument data).

**Comment by wittedroom** [comment]
Any estimates as to when this will be included in a flutter update? Really looking forward to this feature.

**Comment by Hixie** [comment]
No estimate yet. Sorry. I managed to hurt my arm so typing is slower. :-/

**Comment by andrewrabon** [comment]
@Hixie I just hurt my arm recently so I know the impact it can have on coding, I had to hold off on my Flutter app until a few days ago. Hope you get well soon!

**Comment by jayjun** [comment]
@Hixie @andrewrabon That makes three of us! 🚑🚑🚑

**Comment by ViniciusSossela** [comment]
Any news about this feature? Missing in our project too..

**Comment by ravipatel147** [comment]
Its a pretty simple with the this pakage
: https://pub.dartlang.org/packages/navigate

That provide to much your expect and easy to use

```
  Map arg =  {"transactionType":TransactionType.fromLeft,"replaceRoute":ReplaceRoute.thisOne};
    Navigate.navigate(context,
                          "home",
                          transactionType:TransactionType.fromLeft ,
                          replaceRoute: ReplaceRoute.thisOne,
                          arg: arg
                          );
```

**Comment by AlexGoranov** [comment]
I also need to use it in my project. Would love to see it done.

**Comment by anderscheow** [comment]
Any progress on this?

**Comment by Hixie** [comment]
Sorry, haven't had the opportunity to work on this recently. It's still on my list, but I've been focusing on stability and flakiness of our tests first.

**Comment by Symous** [comment]
I'm shocked since flutter do not support this kind of simple feature actually.

**Comment by therealchiko** [comment]
Any possibility of this feature being introduced soon-ish? It's badly missing

**Comment by lucaslcode** [comment]
I have another use case: Restoring UI state.

Say you have an "Edit Journal Entry" screen with a partially changed entry. This means saving the Route, the original Journal entry that was passed into the "Edit Journal Entry" screen and any changed UI elements.

WIthout restoring UI state, I would just `push()` a `MaterialPageRoute` and pass in the journal entry from a button or something, but if I have to go the when the app opens to restore the state, it seems to me I need a named route and a way to pass in the parameter.

Would love to hear any workarounds in the meantime. Maybe extending `MaterialPageRoute`?

**Comment by ericjatis** [comment]
Looking forward for this too...It's been a year.

**Comment by ericjatis** [comment]
I'm expecting this too....It would be helpful to have this. Especially when you are passing an Object not just an ID.

**Comment by guyzk** [comment]
Route params definitely a must!
Something like '/someRoute/:someId'
This is actually a pretty basic request...
Most frameworks out there have much more advanced navigation features and it is pretty disappointing that flutter hasn't gotten there yet.

**Comment by Hixie** [comment]
Yeah, sorry this has taken so long. My branch is months old at this point and I'm a little scared of trying to merge it back in...

**Comment by srujalsk** [comment]
@Hixie any update, would love to see this feature please.

**Comment by szotp** [comment]
I'm surprised that Flutter even attempted named routes, maybe it would be better to leave for community. Main framework could only support passing objects.

**Comment by xTaz1** [comment]
Any news here?

**Comment by goderbauer** [comment]
I've dusted off @Hixie's work on this. I am not actively working on this and should have a PR ready for review soon.

**Comment by gspencergoog** [comment]
Did you mean "now actively working"?

**Comment by goderbauer** [comment]
@gspencergoog Good catch!

**Comment by goderbauer** [comment]
I've posted a PR for review that implements this: https://github.com/flutter/flutter/pull/27058.

**Comment by damiafuentes** [comment]
It is everything here now:
https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments
https://flutter.dev/docs/cookbook/navigation/returning-data

**Comment by patelkrunal78** [comment]
You can use the parameter routes of your App for directly passing arguments.

Like this:

routes: {
HomePage.route: (_) => HomePage(),
DetailsPage.route: (context) =>
DetailsPage(ModalRoute.of(context).settings.arguments),
},
In this case, the complete example will look like the next:

Found At [Here](https://icetutor.com/question/how-do-i-pass-non-string-data-to-a-named-route-in-flutter/)

**Comment by milanpatel18** [comment]
Similar To https://icetutor.com/question/how-do-i-pass-non-string-data-to-a-named-route-in-flutter-2/
