### ISSUE TITLE
Option to 'add <this> to path' and other proposals, to help increase devs smooth flow. [FEATURE REQUEST]

### ISSUE THREAD

**Issue by prik-k** [flutter/flutter#62354]
## Use case
1. Less trouble during **Flutter setup** (which i had).

## Proposal
It would be nice if the set-up procedure can be more simplified.

- [ ] 1. I would like to suggest that wouldn't it be nice if give users, especially someone who's new to flutter, to give a popup or an option to automatically add flutter and required directory '**`path`**' to the system files without having trouble to add them manually. 

- [ ] 2. I have seen other softwares do so, that increased the ease to use them, or adding even a setup Wizard '**_type_**' installation method with current installation methods with checkboxes to add to path and other major setup things would be highly appreciated.  

- [ ] 3. Also that snap store installation method should be deprecated as it lead to even confusion on how to actually setup Flutter on my mint OS system.

- [ ] 4. Android SDK (build tools and other key components) **download/installation _LINKS_** for users who don't wish to install Android Studio to get which are a main components, them due to slow system support (usually in **India**).Or including SDK with Flutter SDK if user chooses to use VS code or other editors apart from Android Studio.

- [ ] 5. Also During "`Flutter doctor -v` " run, if some issues persists then if possible then Flutters SDK should try to auto-fix the isses (if possible) like missing downloads or Use of deprecated tags and auto correct them to newer ones. 

- [ ] 6. A guide for iOS (Xcode) users to setup (version compatibilities) that before following the current installation docs present.

**Comment by christopherfujino** [comment]
Thanks for suggestions! I'll respond inline:

> * [ ]  1. I would like to suggest that wouldn't it be nice if give users, especially someone who's new to flutter, to give a popup or an option to automatically add flutter and required directory '**`path`**' to the system files without having trouble to add them manually.

This is a fair suggestion, and I know a lot of other CLI tools will automatically update your path. However, the main reason why we haven't done it is because it's difficult to determine exactly how the user's path is being constructed (at least on Linux/macOS), and thus which file to modify. Blindly appending `export PATH="/path/to/flutter:$PATH"` to the end of any of `~/.bash_profile`, `~/.bashrc` and `~/.zshrc` that exist will probably work for most users, but will be messy, and prone to the problem of duplicate entries if the user has already manually added it to their path. That having been said, this is probably worthy of being split out into its own issue for discussion.

> * [ ]  2. I have seen other softwares do so, that increased the ease to use them, or adding even a setup Wizard '**_type_**' installation method with current installation methods with checkboxes to add to path and other major setup things would be highly appreciated.

Agreed, this is being tracked https://github.com/flutter/flutter/issues/39939.

> * [ ]  3. Also that snap store installation method should be deprecated as it lead to even confusion on how to actually setup Flutter on my mint OS system.

Can you elaborate more? I'm not sure what you mean by deprecate the method. Do you mean take it off the snap store, or remove some documentation to it?

> * [ ]  4. Android SDK (build tools and other key components) **download/installation _LINKS_** for users who don't wish to install Android Studio to get which are a main components, them due to slow system support (usually in **India**).Or including SDK with Flutter SDK if user chooses to use VS code or other editors apart from Android Studio.

So Android Studio is only required if you're doing android development...but it is officially required for android development. It is technically possible to build and test android apps with only the command line tools; however, you will require other dependencies, such as Java 8. If you want to use an android emulator, you will need the AVD manager. If the user installs each of these separately, the flutter CLI tool may have difficulty locating them. To minimize the support overhead, we officially require Android Studio (which bundles all these dependencies in a stable file directory) for Android development.

> * [ ]  5. Also During "`Flutter doctor -v` " run, if some issues persists then if possible then Flutters SDK should try to auto-fix the isses (if possible) like missing downloads or Use of deprecated tags and auto correct them to newer ones.

This would be cool! It is currently being tracked at https://github.com/flutter/flutter/issues/15794

> * [ ]  6. A guide for iOS (Xcode) users to setup (version compatibilities) that before following the current installation docs present.

Not sure what you mean here. If you had difficulty setting up your dev environment for ios, I would recommend opening a PR to the website: https://github.com/flutter/website/blob/master/src/docs/get-started/install/_ios-setup.md

**Comment by prik-k** [comment]
Great then. Looking forward to improvements soon. You guys are doing a great work! Thank you.

Closing the issue.
