### ISSUE TITLE
Rasterizer last layer tree is unset, causing screenshot tests to fail

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#62389]
In `Rasterizer::ScreenshotLastLayerTree`, `GetLastLayerTree()` is occasionally returning null, causing us to [return empty data](https://github.com/flutter/engine/blob/2b2d65f94e1cd4fc08cdfccef3d3449d37348373/shell/common/rasterizer.cc#L586), resulting in test failures.

This can be seen in the `integration_ui_ios` devicelab test for commit https://github.com/flutter/flutter/commit/39fa00201dfa8340b93e4f2de4fb395510b03b9b

https://github.com/flutter/flutter/blob/39fa00201dfa8340b93e4f2de4fb395510b03b9b/dev/integration_tests/ui/test_driver/screenshot_test.dart#L29

**Comment by tvolkert** [comment]
@liyuqian can you take a look or find the right owner?

**Comment by tvolkert** [comment]
A cursory look at the logs of failing tests indicates that this is the cause of `integration_ui_ios` failing about 50% of the time.

**Comment by liyuqian** [comment]
Thanks for diagnosing the flaky tests down to the `Rasterizer::ScreenshotLastLayerTree` call! I'll investigate from there.

**Comment by liyuqian** [comment]
This issue is caused by the iOS update dialog again. See the screenshot on the mac6 below. With the dialog, Flutter wasn't able to draw anything (see the left screenshot below) so the last layer tree is indeed null. By closing the update dialog on mac6, the test succeeded with the proper screenshot. 

If there are future failures like this, follow "Dismiss system dialog" in https://g3doc.corp.google.com/company/teams/flutter/devicelab/macos_host.md?cl=head#attached-ios-device for the specific mac host that fails the test.

**Comment by tvolkert** [comment]
Is there any way for us to detect the dialog so we fail (a) quicker, and (b) in a more informative way?

**Comment by liyuqian** [comment]
If we can either detect the dialog, or run the infra-dialog XCUITest automatically before each iOS devicelab task, that will significantly ease a lot of flaky issues, including those noisy performance regressions caused by the update dialog. I'm not very familiar with XCUITest/iOS so I may not know the best way. One way I can think of is to run `idevicescreenshot` to get a screenshot, and then OCR the image (e.g., using https://cloud.google.com/vision/docs/ocr) to see if there's "Software Update" in the screenshot.

CC @gaaclarke @digiter to see if there's a better way.

**Comment by liyuqian** [comment]
Aha, simply running `xcodebuild test -project infra-dialog.xcodeproj -scheme infra-dialog -destination 'platform=iOS,name=iPhone'` (documented [here][test_doc]) from the command line will run that infra-dialog XCUITest automatically. @digiter : can we add that to the beginning of all devicelab iOS tasks?

[test_doc]: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html

**Comment by digiter** [comment]
haha, I just checked in and deployed the changes to automate this. I will send an announcement soon.

**Comment by liyuqian** [comment]
@tvolkert : shall we close this as a duplicate of https://github.com/flutter/flutter/issues/54792 ?

**Comment by tvolkert** [comment]
Sounds good - thanks!

**Comment by lionoggo** [comment]
> Thanks for diagnosing the flaky tests down to the `Rasterizer::ScreenshotLastLayerTree` call! I'll investigate from there.


Can you tell me what this method is used for? And what circumstances will the engine call it?

**Comment by liyuqian** [comment]
@lionoggo It's used during `flutter screenshot` command. For example, when we want to snapshot a frame in SKP format using `flutter screenshot --type=skia ...` so we can send the frame to Skia team for further triage.

**Comment by lionoggo** [comment]
Thanks, i think i have understood.

Yuqian Li <notifications@github.com> 于2020年10月20日周二 上午2:36写道：
