### ISSUE TITLE
Google Sign In 4.5.1 - ServerAuthCode returns null value for Web

### ISSUE THREAD

**Issue by Zaheer6110** [flutter/flutter#62474]
ServerAuthCode returns null in case of web.
```
try {
  final _googleSignIn = GoogleSignIn(
    scopes: [
      'email',
      'https://www.googleapis.com/auth/contacts.readonly',
    ],
  );
  final googleSignInAccount = await _googleSignIn.signIn();
  final googleSignInAuthentication = await googleSignInAccount.authentication;
  final code = googleSignInAuthentication.serverAuthCode;
  print(code);
} catch (error) {
  print(error);
}
```
for android https://github.com/flutter/plugins/pull/2792lutter/plugins#2792
for iOS https://github.com/flutter/plugins/pull/2788
these pulls fixes the issues but on web it still shows null.

**Comment by TahaTesser** [comment]
Hi @lrhn 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/57712
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Zaheer6110** [comment]
Hi @TahaTesser this open issue is regarding android.
I follow up with this #57712 and got ServerAuthCode fix on android but on web its still an issue

**Comment by TahaTesser** [comment]
> Hi @Zaheer6110
> I see there's an open issue addressing the case you described. #57712
> Added web and other labels to better describe the issue
> Please follow up on that issue, I'm closing the current one as a duplicate.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

@Zaheer6110 
added web label

**Comment by Zaheer6110** [comment]
Hi @TahaTesser this open issue is regarding android.
I follow up with this #57712 and got ServerAuthCode fix on android but on web its issue still exists.

**Comment by ditman** [comment]
I'm reopening this to track progress of this new feature in the web implementation of the plugin. I'll remove the "platform-web" from the parent issue.

**Comment by ditman** [comment]
As you can see here:
https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L135-L146

Web has never had this feature (although it seems it may be implemented, if you can request offline access after authenticating).

**Comment by TahaTesser** [comment]
@ditman 
Thanks, i just wanted track all platform issues in parent issue and i wasn't aware that web never had this :)

**Comment by ditman** [comment]
@TahaTesser no problem! I just revived this issue so it can be added to the Web Plugins project, so we don't lose track of these odds and ends!

**Comment by hillelcoren** [comment]
I've created a pull request with a fix against @aseef17's fork which has other [required fixes](https://github.com/flutter/flutter/issues/57712#issuecomment-703382420)

https://github.com/aseef17/plugins/pull/1/files

**Comment by MohammadaliDodiya** [comment]
did anyone get Access Token in Flutter web

**Comment by DmitrySikorsky** [comment]
In Flutter version 3.3.4 serverAuthCode is still null on **web**. It is very important to fix, otherwise it makes impossible to use server-side validation which is required in many cases.

**Comment by ditman** [comment]
The mobile version of the plugin retrieves all the authentication credentials (idToken, accessToken and serverAuthCode) in a single flow, but AFAIK this cannot be done in the web (it's becoming harder to even get idToken AND accessToken at the same time).

The API of the plugin needs to be modified so the programmer can tell what authorization type they want: either the accessToken or the serverAuthCode (they use [different](https://developers.google.com/identity/oauth2/web/guides/use-code-model) [mechanisms](https://developers.google.com/identity/oauth2/web/guides/use-token-model)).

**Comment by T-P-F** [comment]
@ditman & contributors any further thoughts on this? Is there a best practice for retrieving a serverAuthCode from a Flutter web app?

**Comment by ditman** [comment]
@T-P-F the documentation you're linking is from a deprecated/obsolete SDK. Here's the flow that needs to be used now:

* https://developers.google.com/identity/oauth2/web/guides/use-code-model

I haven't looked much into this (I don't have a server-side app to do proper testing), but I suspect we could implement the "code" client similarly to how we implement the "token" client here:

* https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in_web/lib/src/gis_client.dart#L127-L128

Since the mobile API doesn't make a distinction between client-side and server-side authorization (and it just fetches all the possible tokens at once), it's hard to achieve a nice implementation on the web.

(One option could be to expose two versions of the web plugin, one for client-side flows, and another for server-side flows, but there might be a more graceful way of implementing this!)

**Comment by T-P-F** [comment]
@ditman I'm thinking something like this which appears to be returning a valid server auth code: [PR5227](https://github.com/flutter/packages/pull/5227) (draft)

**Comment by ditman** [comment]
> @ditman I'm thinking something like this which appears to be returning a valid server auth code: [PR5227](https://github.com/flutter/packages/pull/5227) (draft)

@T-P-F yes! that's the wiring we'd need to enable this feature. The problem I see is that it is "hard" to call `requestServerAuthCode` [code](https://github.com/flutter/packages/pull/5227/files#diff-e21094a3fe08972e54217fb27a87234fa1831293c9612489b799b44742b1bc86R306) from your (potentially) multi-platform app.

We may be able to reuse the [`forceCodeForRefreshToken` configuration variable](https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L181-L182) to decide whether to call the TokenClient or the CodeClient when doing `requestScopes`, or we might want to make the `requestServerAuthCode` visible on all platforms.

Is there any case where a client is going to be using both the TokenClient and CodeClient at the same time?

**Comment by T-P-F** [comment]
Hi @ditman, ok, nice.

Since this PR only touches `google_sign_in_web` it seems out of scope to consider here how other platforms pull a server auth code. Whether they do it through [CodeClient](https://developers.google.com/identity/oauth2/web/reference/js-reference#CodeClient) or some other mechanism, at a minimum this PR makes it possible via google_sign_in_web, which seems a win ;) 

My understanding is that [Android can get it through](https://pub.dev/documentation/google_sign_in/latest/google_sign_in/GoogleSignIn/GoogleSignIn.html) `GoogleSignIn.forceCodeForRefreshToken`.

I've not looked into iOS or desktop cases.

> decide whether to call the TokenClient or the CodeClient 

As for web, the way I implemented it in the PR leaves it to the implementer to decide what they need.

If the web app needs an access token 'locally', the implementation would use a combination of `GoogleSignIn.signInSilently()`, `sign_in_button.buildSignInButton()`, `GoogleSignIn.onCurrentUserChanged()`, `GoogleSignIn.canAccessScopes()`, and `GoogleSignIn.getTokens()`. 

And if the web app needs a server auth code the implementation would just use the `GoogleSignInPlugin.requestServerAuthCode()` from my PR. I completed testing this yesterday all the way through server-side token exchange for access & refresh tokens and it works, at least for my fairly narrow test case.

> it is "hard" to call requestServerAuthCode from your (potentially) multi-platform app.

My app is multi-platform but for now I'm only showing the affordance for connecting to Google to users on web with `if (UniversalPlatform.isWeb) ...`

<details><summary>Super-minimal implementation</summary>
<p>

```
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';
import 'package:google_sign_in_web/google_sign_in_web.dart' as web;

class TGCalLinkWidget extends StatefulWidget {
  const TGCalLinkWidget({super.key});

  @override
  State<TGCalLinkWidget> createState() => _TGCalLinkWidgetState();
}

class _TGCalLinkWidgetState extends State<TGCalLinkWidget> {
  late final GoogleSignIn _googleSignIn;
  final List<String> _scopes = [
    'https://www.googleapis.com/auth/calendar.events',
  ];

  @override
  void initState() {
    super.initState();
    _googleSignIn = GoogleSignIn(
      scopes: _scopes,
      clientId: ' < YOUR CLIENT ID >',
    );
  }

  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: _requestServerAuthCode,
      child: const Text('Link with Google Calendar'),
    );
  }

  void _requestServerAuthCode() async {
    web.GoogleSignInPlugin googleSignInPlugin = GoogleSignInPlatform.instance as web.GoogleSignInPlugin;
    String? authCode = await googleSignInPlugin.requestServerAuthCode();
    if (authCode != null) {
      bool isAuthorized = await _googleSignIn.canAccessScopes(_scopes);
      print('isAuthorized: $isAuthorized');
      // Send authCode to your Firebase Function for token exchange / or whatever...
    }
  }
}
```

</p>
</details> 

See any issues with proceeding with review/merge?

**Comment by ditman** [comment]
@T-P-F super quick question about the `requestServerAuthCode` flow: Do you need to sign-in previously and obtain an IdToken, or do you get everything you need both authentication and authorization from the `authCode`?

@stuartmorgan what do you think about adding a new web-only API to cover this gap? Should we attempt to integrate it with the old behavior of the plugin? (In mobile, the plugin returns all possible types of tokens at once, but on the web, each token requires user interaction + separate call to the plugin).

**Comment by T-P-F** [comment]
@ditman No other auth is needed.

**Comment by ditman** [comment]
If it is a completely stand-alone flow, I wouldn't mind adding a web-only method, like `Widget renderButton({configuration})`.

(Especially because it seems that the new ["AuthorizationResponse"](https://developers.google.com/android/reference/com/google/android/gms/auth/api/identity/AuthorizationResult) for Android is going to continue exposing all tokens, so I don't foresee any significant changes to the architecture of the core plugin because of it moving to the GIS SDK)

**Comment by stuartmorgan** [comment]
> (cc/ @stuartmorgan to weigh in on adding an additional web-only method to allow for server-side Oauth flows, and solve this ancient issue!)

When we don't expect something to be relevant for any other platform, adding it to a single platform's implementation package as a API is fine; we have other examples of that in other plugins.

I would recommend giving it some kind of convenient affordance to call it other than `GoogleSignInPlatform.instance.foo` (e.g., a stand-alone function that internally calls that), since we don't necessarily want to encourage people to interact with the platform interface directly. We have some cases where we do that, but I prefer to avoid it since once someone is using `SomePlugin.instance` in their code their IDE is going to auto-complete a lot of methods that they almost certainly should *not* call (but which are often going to sound very similar to the app-facing object's methods, making it confusing).

**Comment by ditman** [comment]
> I would recommend giving it some kind of convenient affordance to call it other than GoogleSignInPlatform.instance.foo (e.g., a stand-alone function that internally calls that), since we don't necessarily want to encourage people to interact with the platform interface directly.

Good call, let me try modifying @T-P-F's code review to expose his new method (and `renderButton`) from a separate method / import or similar.

**Comment by ditman** [comment]
@stuartmorgan I ended up with something like this:

```dart
// web_only.dart

GoogleSignInPlugin get _plugin {
  assert(GoogleSignInPlatform.instance is GoogleSignInPlugin,
      'The current GoogleSignInPlatform instance is not for web.');

  return GoogleSignInPlatform.instance as GoogleSignInPlugin;
}

/// Render the GIS Sign-In Button widget with [configuration].
Widget renderButton({GSIButtonConfiguration? configuration}) {
  return _plugin.renderButton(configuration: configuration);
}
...
```

That lets me rewrite [this](https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in/example/lib/src/sign_in_button/web.dart) as:

```dart
import 'package:google_sign_in_web/web_only.dart' as web;

/// Renders a web-only Sign-In button.
Widget buildSignInButton({HandleSignInFn? _}) {
  return web.renderButton();
}
```

Instead of having to fish on the methods of the cast `Platform.instance`. I think this works well for this package!

(If I were to wrap a non-static instance of the platform interface, I'd have the user do something like: `SomePluginWebFacade.of(_somePluginInstance)` and call methods on the wrapped value that just forward calls to the appropriate method of the `_somePluginInstance`.)

**Comment by T-P-F** [comment]
@ditman [New PR](https://github.com/flutter/packages/pull/5357) submitted from my personal account now with 'allow edits' enabled.

**Comment by ditman** [comment]
@T-P-F please use a branch on your repo, I cannot push to your `main` (bad things happen with the PR)

**Comment by T-P-F** [comment]
@ditman done, **[new PR](https://github.com/flutter/packages/pull/5358)**

**Comment by ditman** [comment]
Thanks @T-P-F! I'll rebase my local changes with your new PR and push directly there. (We'll need a 2nd review to land your change since it's your first contribution)

**Comment by stuartmorgan** [comment]
Publishing this broke the incredibly simple integration test we have in `google_sign_in` that creating a `GoogleSignIn()` with no parameters works:

```
Failure in method: Can initialize the plugin
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following NativeError object was thrown running a test:
  Error: Missing required parameter scope.

When the exception was thrown, this was the stack:
https://accounts.google.com/gsi/client 226:367                      new Vp
https://accounts.google.com/gsi/client 218:179                      Wp
https://accounts.google.com/gsi/client 278:395                      fr
https://accounts.google.com/gsi/client 281:336                      new kr
https://accounts.google.com/gsi/client 286:634                      initCodeClient
packages/google_sign_in_web/src/gis_client.dart.js 181:83           [_initializeCodeClient]
packages/google_sign_in_web/src/gis_client.dart.js 380:52           new
packages/google_sign_in_web/google_sign_in_web.dart.js 214:61       initWithParams
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50  <fn>
dart-sdk/lib/async/zone.dart 1407:47                                _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                runUnary
dart-sdk/lib/async/future_impl.dart 162:18                          handleValue
dart-sdk/lib/async/future_impl.dart 838:44                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                           [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                           callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                    _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                     _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7  <fn>
```

Given that, I have retracted that version. @ditman We need to either fix this forward today, or I'll have to revert the PR to make sure it doesn't get incidentally re-published with some other change.

We'll also need to figure out what this wasn't caught by implementations package integration tests.

**Comment by ditman** [comment]
The underlying issue for the Cocoon crash is that when we attempt to initialize a `CodeClient` without `scopes`, the GIS SDK throws the exception that @stuartmorgan found above:

```
Error: Missing required parameter scope.
```

The plugin is seemingly swallowing the error at some indeterminate point; the external symptom (reported by cocoon) is that the button gets stuck in "Getting ready", which is the fallback for the FutureBuilder when the "initialization" future does not complete.

I've published a small patch for this breakage, and will link it to this PR.
