### ISSUE TITLE
Gesture detect Middle Mouse Button

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#62488]
## Use case

There seems to be a [`PointerEvent` for the middle mouse button](https://api.flutter.dev/flutter/gestures/kMiddleMouseButton-constant.html), however, I see no way to access it from widgets.

## Proposal

It would be very useful if you could have an `onMiddleMouseButtonPressed` callback on the widget level.

**Comment by gspencergoog** [comment]
It's possible to do this by looking at `TapGestureRecognizer`, you can see how it's implemented, and that recognizer can participate in the gesture arena.  Basically you have to use a lower level interface than `GestureDetector`.

It would be good, however, to support `onTertiaryTap*` for the gesture recognizer.

**Comment by creativecreatorormaybenot** [comment]
@gspencergoog Yes, thank you. I was aware of that, however, it would be useful to have this option on the widget level. Do you think making a PR would be benificial?

**Comment by creativecreatorormaybenot** [comment]
I mean that it would be nice to not have to use `RawGestureDetector` or a custom `RenderObject`.

**Comment by gspencergoog** [comment]
Yes, I agree.  If you'd like to make a PR, that would be great, and otherwise we will get to it eventually.  You'll want to look at `onSecondaryTap{Up,Down,Cancel}` on the `GestureDetector`, and call it `onTertiaryTap{Up,Down,Cancel}`. There shouldn't be a plain `onTertiaryTap` because we don't support double-tap on the secondary button, much less the middle button, and `onTap` is there mainly to be able to determine the difference between double and single tap.

**Comment by creativecreatorormaybenot** [comment]
@gspencergoog That sounds good. I think that I will open a PR for it 👍🏼

**Comment by creativecreatorormaybenot** [comment]
@gspencergoog I openend a PR, according to how I understood your guidance.

I really hope that I got it right 😂 Performing changes for that is a mess 😅

**Comment by gspencergoog** [comment]
Thanks!  I'm actually out on vacation this week, so it'll be a bit until I get to it, but maybe someone else will take a look before then.
