### ISSUE TITLE
Add file watcher to flutter cli instead of manual command entry

### ISSUE THREAD

**Issue by Parkar99** [flutter/flutter#62679]
IntelliJ and Vscode have excellent extensions that automatically trigger hot reload. But some developers, like myself, either want to take matters into their own hands or use other IDEs like VIM or Sublime. 

My suggestion is to add a flag like `flutter run --watch` to the cli resulting in the auto hot reload natively in the cli instead of relying on ~3rd party~ extensions.

**Comment by christopherfujino** [comment]
@Parkar99 if you're using vim, this plugin will enable hot reload from save https://github.com/iamcco/coc-flutter. I think implementing reload on save is more reliable from the editor side (because it knows exactly what was saved) than from the CLI tool side, because it would have to watch all the files, and supporting filesystem watching across host operating systems is non-trivial.

That's not to say we won't implement `--watch` flag, but from a user perspective, I would rather have my editor trigger a reload than rely on a file system watcher, which I've always had problems with (doesn't always trigger on save).

**Comment by Parkar99** [comment]
I do use [coc-flutter](https://github.com/iamcco/coc-flutter) but simple things like being able to clear the devlog is frustration. I don't think that it would be a problem since [nodemon](https://github.com/remy/nodemon) is a console application and works perfectly for node applications.

The analysis tool already implments a `--watch` flag. Just run `flutter analyze --watch` and it watches for file changes. So it's been done, just not for the `run` command

**Comment by Parkar99** [comment]
It will also allow developers to use custom commands like `flutter run -d all` and others without jumping into launch configs, tasks, etc. It'll make life really easy. All other major frameworks do this, why not Flutter, right?

**Comment by jonahwilliams** [comment]
We've definitely explored filesystem watching before, but it is difficult to get right due to the (IMO) poor native file system APIs resulting timing issues and missed changes. This is a feature we're unlikely to add, since it would be difficult to ensure that it meets our standards of performance/reliability

**Comment by christopherfujino** [comment]
> I do use [coc-flutter](https://github.com/iamcco/coc-flutter) but simple things like being able to clear the devlog is frustration. I don't think that it would be a problem since [nodemon](https://github.com/remy/nodemon) is a console application and works perfectly for node applications.

This anecdotal, but I've had enough problems with `nodemon` (of the manner where I saved, refreshed the browser, saw that my code still wasn't working, kept updating and saving for a good half hour until I realized that `nodemon` wasn't picking up changes) that I just stopped using it and instead manually restarted the server.

**Comment by Parkar99** [comment]
I see your points of view. But how come the `flutter analyze` command does have a `--watch` flag since the above points would apply there as well right?

**Comment by jonahwilliams** [comment]
Because despite the poor APIs, most IDE/LSP/Analysis servers are expected to have a watch mode.

**Comment by Parkar99** [comment]
Alright.. Guess this will not be implemented.. I'll close this for now. But I still hope that the situation on file watching improves enough to consider adding this
