### ISSUE TITLE
Need to rollback on modification made on animation_controller.dart

### ISSUE THREAD

**Issue by 5c0rp264** [flutter/flutter#62752]
Hello, a few days ago a commit has been made modifying the animations for avoiding null on a parameter ( [see here](https://github.com/flutter/flutter/commit/a7e868dd876f4b84462cc29fa2dd4092280a1d7a#diff-82a88b0b4aa73ca8c85c9fc068be95b6) ). This modifications lead to an error while compiling and using Flutter "The named parameter 'vsync' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'vsync'.dartundefined_named_parameter"

**Comment by Quijx** [comment]
I had the same problem a few days ago, but it resolved itself after a while somehow. I think the problem was that an older Dart SDK was used. The `AnimationController` clearly has a named parameter `vsync`, but it uses the new `required` keyword that was introduced with the null-safety. Try run `dart --version` and see if your version is hight enough. Mine is `2.8.4` and it works for me. If that checks out, maybe try raising the sdk version in the `pubspec.yaml`.

**Comment by DJafari** [comment]
in your `pubspec.yml`

change this to :

```yml
environment:
  sdk: ">=2.8.0 <3.0.0"
```

and `flutter pub get`

i'm using android studio, then i invalidate cache and restart!

**Comment by TahaTesser** [comment]
Hi @5c0rp264 
Does above solutions works for you? 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by 5c0rp264** [comment]
Yes perfectly !! I mark this issue as closed, thank you !!!

**Comment by vankhoa01** [comment]
I got same issue when use *master* channel
It was fixed after I switch to *stable* channel
