### ISSUE TITLE
'flutter test' does not run 'flutter pub dev'

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#62834]
When I run `flutter test', 'flutter pub dev' does not get run that result in compilation failures.
If i pre-run 'flutter pub dev', 'flutter test' works well.

You can repro it with this package:
https://github.com/google/flutter.widgets/tree/master/packages/flutter_simple_treeview

Version information:

flutter channel
Flutter channels:
  master
  dev
* beta
  stable

flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0-7.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (3 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

**Comment by jamesderlin** [comment]
`flutter test` *does* call `flutter pub get` (otherwise the Travis tests for the google/flutter.widgets repo wouldn't work at all.)

The problem seems to be that `.dart_tool/package_config.json` is stale but `flutter test` isn't automatically triggering `flutter pub get` in this case. `flutter test` works after running `git clean -dxf` in the repo. (That's also why the Travis tests for the google/flutter.widgets repo succeed; they're always run against a clean checkout.)

I'm guessing that `flutter test` just compares the timestamp of `pubspec.yaml` against the timestamp of `.dart_tool/package_config.json` to determine if running `flutter pub get` is necessary, but maybe it doesn't take into account dependency changes in Flutter itself?

**Comment by jonahwilliams** [comment]
I think we fixed this with https://github.com/flutter/flutter/commit/d8b6fa153a1ba065cbd4584141cbe8cc1350dc43#diff-04c58bcf01db77bc3935c69a88c1f6b1R404 - the pub logic did not account for updates to the flutter SDK itself
