### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by sandroarnaldo** [flutter/flutter#62867]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/app/src/main/AndroidManifest.xml:13:9-14:60: AAPT: error: resource string/faceboook_app_id (aka br.com.colorsdj.colorsdj:string/faceboook_app_id) not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @sandroarnaldo 
This is due to missing string in your code
```
/Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/app/src/main/AndroidManifest.xml:13:9-14:60: AAPT: error: resource string/faceboook_app_id (aka br.com.colorsdj.colorsdj:string/faceboook_app_id) not found.
```

This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
