### ISSUE TITLE
'Flutter release notes' page issue

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#63109]
Page URL: https://flutter.dev/docs/development/tools/sdk/release-notes/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/release-notes/index.md

Description of issue: Release notes for Flutter 1.17.1 is MIA.

**Comment by kf6gpe** [comment]
Electing to assign this a P3 so that we collect feedback and document changes this month. Milestone indicates when we'll have a proposal for what we're doing, not a commitment to when the next stable release ships with changes to the release notes --- to be clear, I anticipate that the next version of stable will include the changes we make based on this feedback, but I'm not saying that the next stable is based on the August milestone. To get an idea of our release schedule, see our [roadmap's](https://github.com/flutter/flutter/wiki/Roadmap discussion of [release cadence](https://github.com/flutter/flutter/wiki/Roadmap#release-channels-and-cadence).

**Comment by miguelcmedeiros** [comment]
I would like to add a few more thoughts on this:
- As a developer I usually take a look at the changelog of the packages when upgrading dependencies of my projects. If a package author does not update CHANGELOG, then I'll open the repo and take a look at the commit history.
- This type of action (going through commit history) for a package upgrade is quite doable, in case the history is kept clean. Otherwise, it's not so easy...
- This would not be practical to do when upgrading the Flutter framework. I think my human brain can't process that huge amount of information 😅.
- For a new stable, I don't think people will read every single line of the release notes, but it's really useful when figuring out whether that specific issue or feature landed in that release. This point becomes more relevance for issues that span across multiple repos (flutter, engine, plugins,...).

Currently a developer has to look at several places to check what has changed:
- https://flutter.dev/docs/development/tools/sdk/release-notes
- https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
- https://github.com/flutter/flutter/issues
- Medium articles

You mentioned that we can look at https://github.com/flutter/flutter/issues to get the list of issues. Can you elaborate how to do this for a past release? I looked at the [milestone for 1.20](https://github.com/flutter/flutter/milestone/55?closed=1) and without looking into the details, it seemed somewhat incomplete with only 82 issues closed.

These might all be my personal opinions/preferences on the topic, so I think it's a great step to gather feedback from the community about it 👍. The quarterly survey might be a good place to check this.

Aside from reaching out, there's probably some data that you can analyse. How many visits do the release notes pages have? Is the number of visits changing per version (might be interesting to correlate with new approaches)? I guess that if those pages a really useful, people will visit them multiple times (I have...).

**Comment by pedromassangocode** [comment]
I would like to suggest a webpage in the Flutter.dev website that is automatically updated when there is a new release and this page shows issues that were closed on that release, something like this would be fine for release notes. This would require a more elaborated issue titles that explains the exact problem that need to be solved. Also we can have a label for the issues that need to get listed there so we don't list team member issues or issues that aren't important for everyone to know about it.

**Comment by MisterJimson** [comment]
An example of what I would like to see: https://github.com/facebook/react/blob/master/CHANGELOG.md

A list of all changes, organized by release and date. One place where you can go to see the history of changes.

**Comment by kf6gpe** [comment]
So, @csells and I have talked, and the proposal we've come up with should be online on the Flutter site for 1.17 and 1.20 in the next few days pending an OK from @sfshaza2. In a nutshell:
 
* For 1.20 and 1.17, [this page] on the web site will have two links.
  * The first will go to the Medium post for the release, just as the original link did. 
  * The second will go to a page with two lists -- the first will be a collection of merged PRs clustered by the labels on the PR for each of the labels, and the second list will be a list of all merged PRs for the release in question.

I think this meets the goals y'all are looking for: a single place to find what's been addressed for a given release. 

Most, not all of this, can be automated; we already have scripts that generate the raw clustering and PR reports, addressing @csells's concern that whatever we do be scalable; we found that it was just too much of the team's time to put together both a blog post with samples and editorial about the release and the summary release notes like we did for previous releases like [this one](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-1.7.8). 

As far as determining what's in the release from the GitHub issue tracker itself, you can run a query like [this one](https://github.com/flutter/flutter/pulls?q=is%3Apr+is%3Amerged+closed%3A2019-11-25T16%3A05%3A00..2020-04-02T18%3A26):
```
is:pr is:merged closed:2019-11-25T16:05:00..2020-04-02T18:26   
```

It's admittedly unwieldy to scroll through, though, which is why we understand the desire to provide a flat list somehwere.

Hope that helps!

**Comment by kf6gpe** [comment]
Closing this based on the PR we landed to the web site and the fact that we'll follow the process in the last comment --- the web site will have a link to the blog post and a link to a changelog with two sections: one a list of PRs landed, and the other a list of PRs landed by the labels on the PRs.
