### ISSUE TITLE
url_launcher: wrong destination address when using mailto scheme

### ISSUE THREAD

**Issue by yegor-pelykh** [flutter/flutter#63110]
Hello flutter team!

I'm using **url_launcher** plugin and I had a problem with wrong destination address when using **mailto:** addresses.
When the mail client is opened, the recipient's address contains the value like "**//**[email]" instead of "[email]".

That is, there are 2 extra slashes at the beginning of the address.

Example:

```
import 'package:url_launcher/url_launcher.dart';

...

launch('mailto://some@email.com');

```

After executing this code, there is such an address in the mail client: "//some@email.com"

But it is working properly when I execute it without slashes after scheme:
`launch('mailto:some@email.com');`

Please could you have a look on this bug?

Flutter version:
**Channel master, 1.21.0-6.0.pre.194**

**Comment by stuartmorgan** [comment]
The format of a URI is [scheme]:[path], where `path`'s format is decided by the scheme. `mailto` doesn't use slashes like that in its path. This isn't a bug, it's a misunderstanding about how `mailto` URIs work.

**Comment by yegor-pelykh** [comment]
If we talk about `mailto` RFCs, then yes, you are right. I would say, `mailto` just **doesn't need** slashes because it couldn't have authority. But:

1. Your plugin supports `tel` and `sms` schemes. They also have no authority, so their RFCs don't have info about slashes. But using **url_launcher**, if we have URIs like `tel://0123456789` or `sms://0123456789`, it successfully processes them throwing out extra slashes, opening the corresponding clients with the destination address _0123456789_. So, only `mailto` is processed without throwing slashes.
2. Complementing the previous point, I would say that the use of a colon with slashes (`://`) has already become a de facto "unpublished" URI standard, without going into details of which protocol is actually used.
3. In most cases, this plugin is (or will be) used where there is (let's say) an input field in which the user has to enter the address with scheme, and then the application will open it. This plugin supports different schemes. So the user must enter the URI based on his knowledge of the standards, which not everyone can know. So that the user does not get confused with the question of "why slashes are allowed in http / https / tel / sms scheme, and the program successfully removes them, but in case when using mailto, they are not removed?", I would suggest at least standardizing their processing in this regard. Just the simplest processing is required. You will probably agree that it looks strange that almost all supported schemes throw out slashes, but mailto does not.

Please consider removing possible slashes in mailto URIs.

**Comment by stuartmorgan** [comment]
> But using **url_launcher**, if we have URIs like `tel://0123456789` or `sms://0123456789`, it successfully processes them throwing out extra slashes, opening the corresponding clients with the destination address _0123456789_.

There is no such processing code in `url_launcher`; you seem to be conflating the plugin and the handlers that receive the URIs.

If you want to try to convince all of the popular mail clients to parse `mailto` URIs they receive in a non-standard way using this argument, that's an option, but it's not within the scope of `url_launcher`.

> In most cases, this plugin is (or will be) used where there is (let's say) an input field in which the user has to enter the address with scheme, and then the application will open it.

I have never seen such a use of the `url_launcher` plugin, nor have I ever seen a UI that expects users to type `mailto` URIs by hand. I don't know why you believe this use case would be at all common, let alone the majority.

If you want to build such a UI (I wouldn't personally recommend it; getting URIs right has a lot of pitfalls), you are welcome to do whatever processing you like to try to guess what the correct, valid URI that the user intended was. If you believe that's a common use case, you could publish such a thing as a package.

`url_launcher` passes URIs to the OS, by design. It doesn't do processing that might cause unexpected side-effects, and so expects to receive valid URIs.

**Comment by yegor-pelykh** [comment]
The fact is that as I indicated above, I tried to use URIs `tel://0123456789` and `sms://0123456789`. And after that the phone/messages client showed me address as `0123456789`. I thought your plugin did it, which I really liked. But if you say the plugin doesn't do it, then yes, you are probably right that clients/OS do it. So I was confused by this.
Now everything becomes clear to me and comments on the `mailto` scheme also disappear.
Thanks for the clarification and thanks for such a cool framework! ☺
