### ISSUE TITLE
Meet Microsoft's component governance review

### ISSUE THREAD

**Issue by luisagalva** [flutter/flutter#63231]
## Use case

Using version 1.17.4(previous stable) for building iOS and android application. We decided to use Azure DevOps pipelines for a CI/CD integration.

When running the pipeline, component governance review tool trhows a security vulnerability from using Json 2.2.0 whit a medium severity

`The JSON gem through 2.2.0 for Ruby, as used in Ruby 2.4 through 2.4.9, 2.5 through 2.5.7, and 2.6 through 2.6.5, has an Unsafe Object Creation Vulnerability. This is quite similar to CVE-2013-0269/GHSA-x457-cw4h-hq5f, but does not rely on poor garbage-collection behavior within Ruby. Specifically, use of JSON parsing methods can lead to creation of a malicious object within the interpreter, with adverse effects that are application-dependent.`

## Proposal

Upgrade json from 2.2.0 to 2.3.0 to fix the vulnerability in the following files:

- /s/flutter/dev/ci/docker_linux/Gemfile.lock

- /s/flutter/dev/ci/mac/Gemfile.lock

This will make the framework compliant to Microsoft policies and security recommendations.

**Comment by markusaksli-nc** [comment]
[The json issue in question](https://www.ruby-lang.org/en/news/2020/03/19/json-dos-cve-2020-10663/)

Closing since this was fixed by https://github.com/flutter/flutter/pull/62987 but it is worth mentioning that this is still the case on the new stable `1.20.1`.

https://github.com/flutter/flutter/blob/2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d/dev/ci/mac/Gemfile.lock#L145

https://github.com/flutter/flutter/blob/2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d/dev/ci/docker_linux/Gemfile.lock#L96

**Comment by christopherfujino** [comment]
@luisagalva @markusaksli-nc for what it's worth, this gem is only used by `fastlane`, which flutter uses on CI to deploy the gallery app to the play store. This is an integration test. Flutter never installs the `json` gem on end users' computers, and doesn't directly depend on it.
