### ISSUE TITLE
image_picker and WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#63282]
Hi, I work for a bank and the security doesn't allow the app to use the WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE.
I realized that this permission was added to the manifest of my app. 
Is there a way to avoid this permission using the image_picker plugin?

**Comment by darshankawar** [comment]
Hi @rlecheta,
What api level does your app target ?
Per the plugin's official documentation, for api > 29, no configuration is required and for api <= 29, there's a flag `android:requestLegacyExternalStorage="true"`.
If you are on api <=29, you may try to set above flag to `false` and see if you see any issues while using the plugin.

**Comment by srockytfl** [comment]
Hi, with this flag:
android:requestLegacyExternalStorage="false"

My build never completes, it complains something about the cloud_firestore plugin:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     android/app/src/main/AndroidManifest.xml:14:5-57:19: AAPT: error: attribute android:requestLegacyExternalStorage not found.
      

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin flutter_money_formatter...
Running Gradle task 'assembleAarRelease'...
✓ Built build/app/outputs/repo.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.

In my build.gradle I have:
minSdkVersion 21
targetSdkVersion 29

**Comment by rlechetaudemy** [comment]
Hi, with this flag:
android:requestLegacyExternalStorage="false"

My build never completes, it complains something about the cloud_firestore plugin:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Android resource linking failed
android/app/src/main/AndroidManifest.xml:14:5-57:19: AAPT: error: attribute android:requestLegacyExternalStorage not found.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 11s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin flutter_money_formatter...
Running Gradle task 'assembleAarRelease'...
✓ Built build/app/outputs/repo.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.

In my build.gradle I have:
minSdkVersion 21
targetSdkVersion 29

**Comment by darshankawar** [comment]
Hi @rlecheta @rlechetaudemy with `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` entries intact in manifest file, do you get any error while building or does it prohibit to use `image_picker` plugin ?

**Comment by rlecheta** [comment]
Hi, it throws the same exception, with or without the WRITE/READ permissions. Now my manifest is like this and I got the same error:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="...">
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="Gama Saúde"
        android:requestLegacyExternalStorage="false"
        >

**Comment by darshankawar** [comment]
@rlecheta,
Usually if you have `minSdkVersion 21` and `targetSdkVersion 29`, then you won't explicitly need to specify the permissions in manifest. 
I am on same settings and tried the official image_picker plugin [example](https://pub.dev/packages/image_picker/example) on latest Stable (1.20.1). When I try to access gallery or camera, it by default asks you for the permission as below:

![63282](https://user-images.githubusercontent.com/67046386/89980019-9f0b3500-dc8e-11ea-9269-a49638afde48.png)

**Comment by rlecheta** [comment]
Hi @darshankawar , sure it works like you explained. But please, read again what I explain in the first post.
The problem is that I didn't put the WRITE/READ permission in my Manifest, but during the manifest merge, the plugin put it there. If you Analyse your apk, you are going to see both permissions there, even if you don't wanna it.
My app doesn't pass the security requirements of my company because that.
It's very important that Flutter plugins doesn't put any unnecessary permissions on the Manifest if they are not necessary.
And finally, we are talking about some official plugin.

**Comment by darshankawar** [comment]
This will probably need for analysis, so keeping this issue open.

**Comment by TahaTesser** [comment]
Hi @rlecheta 
For now, only way to avoid this using `image_picker`  [locally](https://stackoverflow.com/a/51238421) in your project and removing the permission [line](   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>)

I don't think write permission would be removed from the package itself 
Closing as there is an easy solution to this. If you disagree, please write in the comments and I will reopen it.
Thank you
