### ISSUE TITLE
Support warning users before leaving route containing an unfinished form

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6331]
Is this possible for the scaffold to pop up a dialog on back button click before doing navigator.pop?

**Comment by Hixie** [comment]
We should add support for doing this, then do it in the text fields demo of the gallery.

**Comment by eseidelGoogle** [comment]
Updated title to reflect the use-case in question.

**Comment by eseidelGoogle** [comment]
Leafy will need this by end of Q1.

**Comment by eseidelGoogle** [comment]
@HansMuller has been looking into Navigator this week.  It's possible he's interested in this one too. :)

**Comment by HansMuller** [comment]
OK, I've just become interested in this topic. Will sort out an API proposal.

**Comment by eseidelGoogle** [comment]
It looks like https://github.com/flutter/flutter/pull/7488 is work towards this?

**Comment by HansMuller** [comment]
Yes, that fixes this. I've added a "fixes" comment to #7488. It should land soon.

**Comment by mehmetf** [comment]
@HansMuller How would you do this if you were not using a form widget? We have our own FormField implementation and the way to standardize the UI (as we have discussed before). 

- Use an empty form?
- Replicate the willPop registration in our own widget?

**Comment by HansMuller** [comment]
I think you want the second option. The FormWidget just registers an onWillPop callback with its route. Since you have your own form container, I think you'll want to do the same thing.

The willPop registration code is a little messy to account for the fact that the Form's route may change, I don't think there's any way to avoid that.

**Comment by mehmetf** [comment]
Agreed. The code that renders our form (and preps the callback) is a bit messy as well. We need to load an object for instance before we can set a callback. So we can't quite use the dependenciesChanged() override. For now I am doing this in build():

```Dart
      final ModalRoute route = ModalRoute.of(context);
      if (route != null && !route.hasScopedWillPopCallback) {
        route.addScopedWillPopCallback(() async {
          if (_createPatch(myObject).isNotEmpty) {
            print('Oh no! Changes detected');
          } else {
            print('Please proceed');
          }
          return true;
        });
      }
```

myObject is loaded sometime later and setState() is called on the form to fill it in. That's when this code executes. Any comments/suggestions/concerns?

**Comment by Hixie** [comment]
Depending on route.hasScopedWillPopCallback sounds really dangerous. It should be possible to register a no-op callback without affecting any other code.

**Comment by mehmetf** [comment]
@Hixie I am considering other solutions but none seems viable:

- We could set the callback only when data is ready but what if Flutter changes the route object and calls build() again? Data ready callback does not fire then so we will be stuck.
- We could do it on dependenciesChanged() as suggested but at that point data may or may not be ready. We could save the data as part of the state but that's an anti-pattern in our code so far.

Codewise, the cleanest way seems to be doing it in the build() which is called many times for a myriad of reasons. We can't keep local state either without keeping a reference to the Route object (yuck).

So if hasScopedWillPopCallback is not a good solution, what is?

**Comment by HansMuller** [comment]
Can you use the dependenciesChanged, didUpdateConfig approach like FormState does, but just have your method return true unless the data you need to make a veto decision is available?

**Comment by HansMuller** [comment]
Note also `hasScopedWillPopCallback` is going to become protected, see #7826

**Comment by Hixie** [comment]
I don't really understand why registering a private method in `dependenciesChanged` isn't ok. 

You should assume `build` is being called continually and that every time the ModalRoute can be different.

**Comment by mehmetf** [comment]
Registering a private method is usually ok; if you have a simple app OR you are starting from scratch. **Basically, all of the business logic that goes into rendering our widgets right now lives in build(). It is a natural place for that kind of code. This requirement breaks that pattern.**

Our widget state pattern has been more or less this:

```Dart

class MyComplexWidgetState {
  void initState() {
     myStore.subscribe(this);
  }  

  void dispose() {
    myStore.unsubscribe(this);
  }

  Widget _buildMyComplexForm(MyObject obj) {}

  Widget build(BuildContext) {
     var data = myStore.data;
     if (data != null) {
       return _buildMyComplexForm(obj);
     }
  }
}
```

We never needed the data object outside of methods called from build(). initState() and dispose(), for example, does not need it. However, if we have to register this callback inside dependenciesChanged, we have to do something like this:

```Dart
class MyComplexWidgetState {
  MyObject _data;

  void initState() {
     myStore.subscribe(this);
  }  

  void dispose() {
    myStore.unsubscribe(this);
  }

  Widget _buildMyComplexForm() {
     // Build using _data
  }

  void dependenciesChanged() {
     registerCallback(() {
        // do something with _data if _data is not null
     });
  }

  Widget build(BuildContext) {
     _data = myStore.data;
     if (_data != null) {
       return _buildMyComplexForm();
     }
  }
}

```

We could do it. It is just not a pattern we have been following in the app because we never needed it as part of the state.

**Comment by Hixie** [comment]
I'm saying do this (pseudo-code):

```dart
class MyComplexWidgetState {
  MyObject _data;

  void initState() {
     myStore.subscribe(this);
  }  

  void dispose() {
    myStore.unsubscribe(this);
    route.unregisterCallback(_callback);
  }

  Widget _buildMyComplexForm() {
     // Build using _data
  }

  void dependenciesChanged() {
    // ...
    oldroute?.unregisterCallback(_callback);
    newroute.registerCallback(_callback);
  }

  void _callback() {
     _data = myStore.data;
    if (_data != null) {
      // ...
    }
  }

  Widget build(BuildContext) {
     _data = myStore.data;
     if (_data != null) {
       return _buildMyComplexForm();
     }
     return ...; // don't forget to return something here if data == null
  }
}

```

Is there some reason this isn't feasible? I don't really understand what "myStore" is here (does it come from the widget tree? or is it a global? how does _data get set?)

**Comment by mehmetf** [comment]
I understand. Thanks for the suggestions.

It is definitely doable. The data accessor is not as simple as shown here but we could move it to a common place that can be called from the callback and build(). 

I was merely pointing out that it is annoying to change our access pattern to data since it can have 3 states (not ready/null, empty or filled) and handling its implications in two places rather than one is annoying. May be we should simplify that but nevertheless this seemingly innocuous change will cause a chain reaction in our code and cause us to update some of the common patterns we have been using.

We digressed quite a lot from the original discussion. I was merely asking if it is possible to support this callback pattern in build() and it seems like the answer is no. We will readjust and do something else. For instance perhaps the answer is to not need _data at all and instead rely on FormFields to save their changed state (similar to how Flutter Form does it actually). Thanks for the comments.

**Comment by Hixie** [comment]
You could do this:

```dart
class MyComplexWidgetState {
  MyObject _data;

  void initState() {
     myStore.subscribe(this);
  }  

  void dispose() {
    myStore.unsubscribe(this);
    route.unregisterCallback(_callback);
  }

  Widget _buildMyComplexForm() {
     // Build using _data
  }

  void dependenciesChanged() {
    // ...
    oldroute?.unregisterCallback(_callback);
    newroute.registerCallback(_callback);
  }

  VoidCallback _actualCallback = () { };

  void _callback() {
     _actualCallback();
  }

  Widget build(BuildContext) {
     _data = myStore.data;
     if (_data != null) {
       return _buildMyComplexForm();
       _actualCallback = () {
         // ...
       };
     }
     return ...; // don't forget to return something here if data == null
  }
}
```

...then you can make a superclass that has all the boilerplate (everything except the `build()` seems like it'd be the same for every class like this).

**Comment by mehmetf** [comment]
Thank Ian. Yes, numerous solutions exist. None of which is particularly elegant but I certainly appreciate the time you put into it 👍 .

I believe the best way is for us to use the existing form fields to figure out whether something changed or not. Those are already part of the State and they are init'ed in a saner way so they can be used anywhere within state including any life-cycle methods.
