### ISSUE TITLE
Double date separators appearing in DatePicker, preventing date selection

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#63373]
Originally mentioned in https://github.com/flutter/flutter/issues/55535 by @whoch in [this comment](https://github.com/flutter/flutter/issues/55535#issuecomment-670933115).

The issue might be related to incorrect date separators for particular locales: https://github.com/flutter/flutter/issues/63372

This issue occurs because the dateHelpText, dateSeparator in MaterialLocalization are different from the compactDateFormat used by the validator in TextFormField.

In Korea, helpText and separator of MaterialLocalizationKo are as follows:
```
String get dateHelpText => 'yyyy/mm/dd';
String get dateSeparator => '/';
```
And compactDateFormat is y. M. d.

InputText is initially shown in y. M. d. format, but when the value is modified, it is changed to y//M//d// by inputFormatters. And Only '/' is entered, therefore cannot be entered y. M. d. format.

HintText also outputs 'yyyy/mm/dd' which is different from the compactDateFormat.

Even if input the hintText format,  the errorText is displayed because the _validateDate method, validator of InputDatePickerFormField, internally parse the compateDate.
```
String _validateDate(String text) {
  final DateTime date = _parseDate(text);
  if (date == null) {
    return widget.errorFormatText ?? MaterialLocalizations.of(context).invalidDateFormatLabel;
  } else if (!_isValidAcceptableDate(date)) {
    return widget.errorInvalidText ?? MaterialLocalizations.of(context).dateOutOfRangeLabel;
  }
  return null;
}

DateTime _parseDate(String text) {
 final MaterialLocalizations localizations = MaterialLocalizations.of(context);
 return localizations.parseCompactDate(text);
}
```

Can I modify compactDateFormat or can someone solve this issue?
![photo1](https://user-images.githubusercontent.com/45822402/89712701-756fb680-d9cd-11ea-8750-c7ff4e66d524.JPG)
![photo2](https://user-images.githubusercontent.com/45822402/89712702-76a0e380-d9cd-11ea-94f3-3cbd534d130d.JPG)

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
Yikes. So all of this is stemming from the date picker trying to keep the user from typing invalid dates. In order to do that it uses a date text formatter that rejects anything but digits and the date separator. This is based on an apparently faulty assumption that there is a single character as the separator for all locales. Perhaps a better solution would be remove the text formatter altogether and let the user type whatever they want and let the validator handle the errors.

We would still need to get the help text correctly translated (as per #63372), but we could get out of the separator business altogether. 

I will put together a PR that removes the formatter and see what that looks like.
