### ISSUE TITLE
Malware detected in flutter web

### ISSUE THREAD

**Issue by komrat1988** [flutter/flutter#63393]
Hello. If scanning for example https://gallery.flutter.dev with popular site scanning I get error - Malware Found https://gallery.flutter.dev/main.dart.js. And this problem happened if I scan my site written on flutter.
Thank you.

**Comment by markusaksli-nc** [comment]
Hi @komrat1988 
When scanning [gallery.flutter.dev](https://www.virustotal.com/gui/url/e2cf536ade2dcb3df48dbf2556c4f51f64c013c1e6412c9eb7114bdf1914e1bb/detection) or [main.dart.js](https://www.virustotal.com/gui/file/35bcfe19818bc189a57872f74f6d60676cc799b7d3c2af6d5962b6666e9fe589/detection) with almost every popular scanner out there using [VirusTotal](https://www.virustotal.com/gui) there are no detections. This means your scan is either a false positive or there is an issue with your scan setup.

Please follow up on https://github.com/flutter/flutter/issues/61997 if this is a hindrance for you during development. Closing this, since it isn't an issue with Flutter.
Thank you
