### ISSUE TITLE
add-to-app via CocoaPods cannot find flutter_assets on iOS 14

### ISSUE THREAD

**Issue by xster** [flutter/flutter#63552]
Run https://github.com/flutter/samples/tree/master/add_to_app/ios_fullscreen via the CocoaPods integration path. 

Fails to launch the Flutter screen on iOS 14 / Xcode 12

```
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[VERBOSE-2:engine.cc(148)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(487)] Could not launch engine with configuration.
flutter: Observatory listening on http://127.0.0.1:63033/hwmX53Eqeq0=/
```

Interestingly, once I launch it once via iOS 13 / Xcode 11, then go back to iOS 14 / Xcode 12, it works. 

cc @jmagman

**Comment by xster** [comment]
Tried another one. This is pretty suspect. 

```
../[flutter-module].ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
```

Perhaps it didn't run xcode_backend.sh (the next line to flutter_export_environment.sh) at all?

**Comment by szotp** [comment]
Here is a fix, please merge: https://github.com/flutter/flutter/pull/63568

It's not related to iOS 14. You just need to buidl app once, then execute "pod install" and run again.

"inherited: command not found" is also a bug, but not related to this.

**Comment by jmagman** [comment]
The `inherited` bug is the problem here.  I fixed up the App.framework path problem (which https://github.com/flutter/flutter/pull/63568 also does) and it still doesn't embed the App.framework into the resulting host app, though it does make the phantom `/User/` directory go away.  The Flutter script doesn't run any `flutter` code, it just bails at `flutter_export_environment.sh: line 8: inherited: command not found`.  When I escape the `export "OTHER_LDFLAGS=$(inherited) -framework Flutter"` parenthesis, it embeds as expected.

Let's follow along at duplicate https://github.com/flutter/flutter/issues/63176.

**Comment by BrunoVillanova** [comment]
I have found the same error trying to build in Xcode 12.2 on Apple M1. 
The difference was that the error only happens when building from the native app, because I am building add-to-app.
What worked for me was to handle the VALID_ARCHS on my iOS Project Podfile as you can see in this [CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/10077)

Fix all configuration

```
target 'Demo' do
  post_install do |installer|
    installer.pods_project.build_configurations.each do |configuration|
      installer.pods_project.build_settings(configuration.name)['VALID_ARCHS'] = []
    end
  end
end
```

Fix one configuration, like Debug

```
target 'Demo' do
  post_install do |installer|
    installer.pods_project.build_settings('Debug')['VALID_ARCHS'] = []
  end
end
```

**Comment by ArshAulakh59** [comment]
I was able to get my add-to-app project building again from Xcode with the solution mentioned here https://github.com/flutter/flutter/issues/71959#issuecomment-755535401.
