### ISSUE TITLE
Exceptions thrown in SDK

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#63674]
I can't provide steps to reproduce, but, after installing https://pub.dev/packages/catcher, some SDK exceptions are being caught (rendering Catcher useless). This reports, for example, comes from a user (I don't know exactly how to trigger it and it doesn't happen in all of my devices).

I *guess* this is related with the poor Dart debugging capabilities (for instance, breaking inside a caught exception: https://github.com/Dart-Code/Dart-Code/issues/2670#issuecomment-668877154), but I'm not sure.

This is rendering most of quality control tools useless (in this particular case, a dialog was presented so the user could send me an e-mail... but there is no user code whatsoever in this case)

Error:
**PlatformException(error, Permission Denial: get/set setting for user asks to run as user -2 but is calling from uid u0a202; this requires android.permission.INTERACT_ACROSS_USERS_FULL, null)**

Stack trace:
```
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)

#2 TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039)

#3 AndroidViewController.create (package:flutter/src/services/platform_views.dart:746)

#4 RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176)
```

Device parameters:

id: QPFS30.103-43-7
board: def
bootloader: MBM-3.0-def_retail-2ccb26b0b9-200707
brand: motorola
device: def
display: QPFS30.103-43-7
fingerprint: motorola/def_retail/def:10/QPFS30.103-43-7/1a0ca:user/release-keys
hardware: qcom
isPhysicalDevice: true
manufacturer: motorola
model: motorola one hyper
versionBaseOs: motorola/def_retail/def:10/QPF30.103-43/3ed81:user/release-keys
versionCodename: REL
versionIncremental: 1a0ca
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01

**Comment by markusaksli-nc** [comment]
Hi @JCKodel 
Catcher is a third-party plugin so this can't be considered an issue with Flutter itself. Please consider opening an issue in the [catcher repository](https://github.com/jhomlala/catcher/issues).
Closing this for now. Let me know if you disagree and I'll reopen.
Thank you

**Comment by JCKodel** [comment]
> Hi @JCKodel
> Catcher is a third-party plugin so this can't be considered an issue with Flutter itself. Please consider opening an issue in the [catcher repository](https://github.com/jhomlala/catcher/issues).
> Closing this for now. Let me know if you disagree and I'll reopen.
> Thank you

This is NOT about Catcher!
This is about Flutter exceptions in the SDK caught by any exception handler package (including Firebase Crashlytics).

This is an internal Flutter exception that can't be fixed by me. Catcher is just an example how bad this is (because it will not log this exception silently)

**Comment by markusaksli-nc** [comment]
Thanks for clarifying.

What specific exceptions have you encountered that reflect this issue? Could you also please provide your `flutter doctor -v` so we know what exactly what SDK version the stack trace is referring to (the line numbers may be incorrect otherwise). Do I understand correctly that the desired behavior here is for exceptions to be uncaught for better debugging?

**Comment by JCKodel** [comment]
> What specific exceptions have you encountered that reflect this issue?

So far, this one. I'm writing a new version and decided to implement Catcher, at least in Beta, to be able to catch some bugs that doesn't happen on my devices.

The idea is to catch only my exceptions, not Flutter's! I know this is impossible, because Flutter do crash (I have an app with 3 million users and no matter what, exceptions arise in Android SDK and Flutter SDK for a small percentage of devices (there is no relation - is not a specific model, etc.))

But, Catcher shows a popup to the user so he can send the error report to me. If those exceptions come from Flutter, there is nothing I can do to fix them, and those users will always see those popups, no matter what. In other words: nice tools like Catcher is being rendered useless by bugs in some devices.

> Do I understand correctly that the desired behavior here is for exceptions to be uncaught for better debugging?

This error was in production (it never happened in debug). There is nothing to do, really. It's an exception. It happened once among 1000 Beta test users. The report is only for you to be aware that there is some kind of bug in some devices and/or environment at that location (I don't know what the error means, but it would be nice if some errors could only just be ignored - perhaps some flag in the global error handling so we know if this is an SDK error or user code error, otherwise there is no point in report them to  me)

> Could you also please provide your `flutter doctor -v` so we know what exactly what SDK version the stack trace is referring to (the line numbers may be incorrect otherwise). 

Not really, sorry. That build was built in a Windows 10 machine, using Flutter 1.20.0, 1.20.1 or 1.20.2 (stable channel), I really don't remember and now I'm on a Linux machine with latest 1.20.2, so I can't really tell which version was and the platform itself is different, so, it wouldn't be much useful.

**Comment by markusaksli-nc** [comment]
I'm sorry but at this point, I am not sure what can be done here. The exception itself is obscure and happened with a production app with third-party plugins so there is nothing to indicate an issue with flutter itself. If your problem is error handling then this

> it would be nice if some errors could only just be ignored - perhaps some flag in the global error handling so we know if this is an SDK error or user code error, otherwise there is no point in report them to me

sounds like a proposal for Catcher, since that is what you are using for reporting.

Finally on ignoring this exception: The exception seems like it occurs during the platform view creation and would cause a fatal crash. Exceptions thrown by the framework can still be used to find and diagnose issues in your app (or usage cases). Just because they weren't thrown by your specific code doesn't mean they don't point to an issue in a use case for your specific code. 

It's always helpful to simply google the exception message. In this case, it would lead you to [this SO question](https://stackoverflow.com/questions/28134128/android-permission-interact-across-users-full) which contains a good starting point on what the message means and the associated permissions.

Do you have any precise change or new feature you want to propose to flutter itself here?
