### ISSUE TITLE
Find flutter drive custom TextField

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#63704]
I am using a custom library `pin_code_fields` and I want to test it by flutter drive on my app but I can't extract the text as it is not a TextField
Then how could I override `_getText` on flutter drive or similar behavior? https://github.com/flutter/flutter/blob/c67eafa87d2de441a195a8aa46c92eac37ce4616/packages/flutter_driver/lib/src/extension/extension.dart#L549
Error for using getText on custom TextField
`DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type PinCodeTextField is currently not supported by getText`

I know StackOverflow for common support, And I will not find an answer to this question there.

**Comment by darshankawar** [comment]
Hi @amorenew,
Currently `getText()` only supports handful of widgets like:
RichText
EditableText
TextField
TextFormField

See this [PR](https://github.com/flutter/flutter/pull/48809) for more details. Since you said, `PinCodeTextField` is not a textfield, that's the reason you are seeing that error. It's just a limitation with Flutter driver.

**Comment by amorenew** [comment]
@darshankawar So what would be the best solution in the future? find where type like the following
`    final pinInput = find.byValueKey('pinInput').whereType<TextFormField>();`
https://stackoverflow.com/questions/54235752/flutter-how-to-get-text-widget-on-widget-test
Or I need to create a PR for the custom library I need with a custom key for the TextFormField child like
`final Key textKey;`

**Comment by darshankawar** [comment]
@amorenew,
Since the issue you are facing is with custom library, `pin_code_fields`, you may open a PR in their repo and see if it resolves your issue.
As far as making changes in Flutter driver itself, it may not be possible as of now.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by marcin-jelenski** [comment]
Fixed in #67711
