### ISSUE TITLE
Windows desktop Platform environment issue

### ISSUE THREAD

**Issue by johannphilippe** [flutter/flutter#63718]
Building a  windows desktop with `flutter run -d windows` on Windows 10, Platform.environment["HOME"] returns null. 
I checked in Powershell, and `echo $HOME` returns the expected path.

**Comment by stuartmorgan** [comment]
> Platform.environment["HOME"] returns null.

`HOME` is not a standard environment variable on Windows, so unless you've set it as a custom system-level or user-level variable that's the expected behavior.

> I checked in Powershell, and echo $HOME returns the expected path.

`$HOME` isn't how you access an environment variable called `HOME` in PowerShell. `$Env:HOME` is the environment variable called `HOME` (which, per the above, you can expect to be empty); `$HOME` is a PowerShell variable.

**Comment by johannphilippe** [comment]
I actually didn't know that. The fact that system and PowerShell do not share the same environment is not so intuitive . Thank you for this helpful comment. I could replace HOME with UserProfile in my case.
