### ISSUE TITLE
DatePicker should allow the selected date to be null

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#638]
Maybe should default to today?

/cc @tvolkert

**Comment by tvolkert** [comment]
I think it should support no selected date.  The use case I had was asking the user to pick a date from a given range, and dismissing the picker once the user has selected a date.  With this use case, you really want there to be no selected date initially, because as soon as you select a date by default, you run the risk that the user wants to in-fact select *that* day, and then your app won't receive the onChanged() notification.

**Comment by abarth** [comment]
I see, so there should be no selected date and the picker should default to showing the start of the range.

**Comment by tvolkert** [comment]
Yep

**Comment by minh98** [comment]
hey there. any update ?

**Comment by tvolkert** [comment]
FYI @darrenaustin (I was browsing through our oldest issues, and this is twelfth on the list 🙂 )

**Comment by YeungKC** [comment]
This issue is so old that I'm not sure it's still valid.
In regards to @tvolkert  case, you can now use showDateRangePicker to fix it.

Expected:
There is no need to force initialDate, the default is null.
The selected datetime is unchecked by clicking on it again and the value is null.

I'm waiting for an exact answer, if that still works, then I'll PR.

**Comment by niltonvasques** [comment]
Hello guys, 

Is not possible to clear the date in the latest flutter versions?

**Comment by Bungeefan** [comment]
Regarding the clear functionality:
I think it's still valid, as Material 3 seems to specify a "Clear" button in the bottom-left corner for date picker, alongside the "Cancel" and "OK" buttons.
https://m3.material.io/components/date-pickers/specs

It is also mentioned in the Accessibility section:
https://m3.material.io/components/date-pickers/accessibility#5f015ede-4e77-4cfc-843b-0a0cd025bf4b

**Comment by jinosh05** [comment]
This Feature was already Implemented and can be closed

**Comment by tvolkert** [comment]
@jinosh05 `initialDate` is still a required non-nullable parameter of the `CalendarDatePicker` constructor, and the same is true for the `initialDate` parameter to the `showDatePicker()` method. So it doesn't look like this has been implemented yet.

**Comment by tvolkert** [comment]
For reference, the feature request is to support the following:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: CalendarDatePicker(
          initialDate: null,  // <-- currently, this is non-nullable, so you'd need to use e.g. DateTime(2023, 4, 15),
          firstDate: DateTime(2023, 4, 1),
          lastDate: DateTime(2023, 4, 30),
          onDateChanged: (DateTime _) {
            print('$_');
          },
        ),
      ),
    ),
  );
}
```

**Comment by jinosh05** [comment]
https://github.com/flutter/flutter/pull/126778 Check this Pull request as the code works fine to me

**Comment by tvolkert** [comment]
@jinosh05 in that PR, you default `initialDate` to the current date.  This issue is to allow it to be null (no selected date at all), not simply defaulting the selected date to the current date.

**Comment by Hixie** [comment]
Implementing the ability for a date picker to have no selected date would be a significant breaking change, because `onDateChanged`'s argument is non-nullable, `showDatePicker` uses `null` to mean the user canceled the dialog, etc, so we can't really support there not being a selected date.

We could implement it if we don't have to support the user unselecting the current date, though.

**Comment by tvolkert** [comment]
We don't have to support the user unselecting the current date.  The use case is to allow `initialDate` to be null.
