### ISSUE TITLE
1.7.7 Error flutter run pub

### ISSUE THREAD

**Issue by angelohu** [flutter/flutter#63900]
<img width="862" alt="errror" src="https://user-images.githubusercontent.com/64202693/90335049-2d0a5700-dfd2-11ea-81b0-c6a2f50f8287.png">

**Comment by angelohu** [comment]
@iapicca  ok ,   later issue 
<img width="862" alt="截屏2020-08-16 下午4 10 32" src="https://user-images.githubusercontent.com/64202693/90336290-2cc28980-dfdb-11ea-959e-4a86f54f44c4.png">

**Comment by Tejaswgupta** [comment]
@angelohu can you try the following and report back:
```flutter clean ```  and ```pod upgrade``` from ios directory

**Comment by jonahwilliams** [comment]
@angelohu please fill out the issue template, and use a single github issue per bug. Looking at this, it is impossible to tell what the problem, or if the problem was solved based on your second comment.

It is also impossible for anyone using a screen reader or translating the issue to read any of the images you posted

**Comment by angelohu** [comment]
ho provato  comandi ,  dopo flutter run ,  mi da stesso errore
