### ISSUE TITLE
Example of TextFormField  doesn't work: API docs incorrectly suggest pressing ENTER instead of SPACE

### ISSUE THREAD

**Issue by believeInJha** [flutter/flutter#63912]
The flutter [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html) has an [example](https://api.flutter.dev/flutter/material/TextFormField-class.html#material.TextFormField.2),

it says 

> this example shows how to move the focus to the next field when the user presses the ENTER key.

but when I press the ENTER, it doesn't work,

**Comment by kmartins** [comment]
Seems the problem was solved in #61078.

However, the documentation is not updated and also seems does not to work on Android and iOS.

**Comment by believeInJha** [comment]
Hello! I want to start my contribution to this repo. Can I take up this issue?

**Comment by kmartins** [comment]
Yes, sure 😃 
See https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

**Comment by believeInJha** [comment]
Hello @kmartins, @jonahwilliams  and @pedromassangocode. Thank you all for your responses. This is my first open-source contribution to flutter. And as previously mentioned by @kmartins that this problem was solved in #61078 but not updated in the documentation. So I'm a bit confused on how to work on the documentation part. please guide me on this.

**Comment by AyushBherwani1998** [comment]
Hey @believeInJha, glad to see you want to contribute. The example heading needs to be updated.  In #61123 the `LogicalKeyboardKey.enter` was changed to `LogicalKeyboardKey.space` in order to move the focus. The change has not yet propagated to the stable version. You can check out the documentation for the master branch [here](https://master-api.flutter.dev/flutter/material/TextFormField-class.html#material.TextFormField.2) which has this change. If you press space, it will move the focus to next `TextFormField`.

What you can do is just change the heading so it's not confusing for the users. You need to update the line below by replacing the "ENTER" key with the "SPACE" key. https://github.com/flutter/flutter/blob/a42c56791b176df32f6dea5e2d6863608cbe8bc3/packages/flutter/lib/src/material/text_form_field.dart#L74

As @kmartins mentioned, do read [CONTRIBUTING.md](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) to get started. 

Looking forward to seeing your first contribution.

**Comment by believeInJha** [comment]
Hey @AyushBherwani1998, I have made the changes as you told me to do, kindly take a look into it. And Thank you very much to give such great insight into the issue.
