### ISSUE TITLE
Someone removed a '@' from animation_controller.dart on line number 242

### ISSUE THREAD

**Issue by SupremNandalDev** [flutter/flutter#63922]
Hello there, I'm on Dev channel and recently saw this issue... Please fit and push asap
AnimationController({
    double? value,
    this.duration,
    this.reverseDuration,
    this.debugLabel,
    this.lowerBound = 0.0,
    this.upperBound = 1.0,
    this.animationBehavior = AnimationBehavior.normal,
"@"    required TickerProvider vsync,
  }) : assert(lowerBound != null),
       assert(upperBound != null),
       assert(upperBound >= lowerBound),
       assert(vsync != null),
       _direction = _AnimationDirection.forward {
    _ticker = vsync.createTicker(_tick);
    _internalSetValue(value ?? lowerBound);
  }

**Comment by TimWhiting** [comment]
@SupremNandalDev 
This is from null-safety related changes. You should still be able to use the dev version of flutter with null safety without opting your project in to null-safety. I ran into this same issue a little while ago. To fix it, I had to exit all my VSCode windows and reopen my projects. You see analysis errors like this I'm guessing when you upgrade flutter with a project open because the analyzer doesn't restart once the upgrade finishes. However, by restarting the editor or if that doesn't work, restarting your computer, the project will be reanalyzed and these analysis errors will go away.

**Comment by goderbauer** [comment]
Closing with the description given in the previous comment.

**Comment by shao8843** [comment]
How can I get the patch?
