### ISSUE TITLE
Color identification of a widget using flutter driver

### ISSUE THREAD

**Issue by MounicaGit** [flutter/flutter#64023]
There is a use case based on widget's color in automation.
Need a feature to identify the color of a widget using the flutter driver in flutter_gherkin package

**Comment by darshankawar** [comment]
Hi @MounicaGit,
If you are specifically looking for `flutter_gherkin` plugin to have that feature, you'll need to raise this issue in their repo (https://github.com/jonsamwell/flutter_gherkin/issues) since that plugin is a 3rd party.
Closing, as this feature request is not specific to flutter driver, but with the 3rd party plugin. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by MounicaGit** [comment]
Hi @darshankawar,
Kindly have a look here https://github.com/jonsamwell/flutter_gherkin/issues/79, I have already raised a bug there.

**Comment by darshankawar** [comment]
@MounicaGit Thanks.
I am afraid but Flutter team is moving away from Flutter driver and are not accepting new feature request related to it.

**Comment by sigis151** [comment]
@MounicaGit Is there a place where we could read up why is it being deprecated, and with what is it being replaced? should I start to implement integration tests using flutter_driver or is it better to wait for a new solution?
For now the [documentation](https://flutter.dev/docs/cookbook/testing/integration/introduction) says to use flutter_driver for integration tests.

**Comment by darshankawar** [comment]
@sigis151 see [this](https://github.com/flutter/flutter/issues/7474#issuecomment-558882182) comment for your reference.
Hope it helps.
