### ISSUE TITLE
[Feature Request] Unified desktop API modeled after ElectronJS

### ISSUE THREAD

**Issue by colinskow** [flutter/flutter#64074]
Flutter is currently the wild west in terms of figuring out how to interact with operating system features like menu bars, notifications, screen capture, tray icons etc.

[ElectronJS](https://www.electronjs.org) is a battle hardened desktop shell for web technology apps. It has a robust API to integrate with MacOS, Windows and Linux which handles most common needs.

## Use case

It would be nice to have a standard API built into Flutter for interacting with desktop operating systems. Or at least have a standard set of recommended plugins which are supported. Developing desktop apps with Flutter would be much easier if there were standard solutions rather than a jungle of competing plugins of varying quality.

## Proposal

My proposal is to use the [Electron API](https://www.electronjs.org/docs) as a guide to develop standard desktop integrations which work with each major operating system. Electron is MIT licensed, so developers could probably copy much of the underlying native code and simply convert the JavaScript bindings to Dart bindings. The JavaScript interfaces should be simple to translate into Dart classes.

**Comment by stuartmorgan** [comment]
> Flutter is currently the wild west in terms of figuring out how to interact with operating system features like menu bars, notifications, screen capture, tray icons etc.

It is certainly the case that desktop, whose implementations are currently either alpha (macOS, Linux) or not even alpha yet (Windows) don't have a robust ecosystem, or wealth of examples (including open source projects, SO answers to questions, etc.). That is the nature of being in early stages.

> It would be nice to have a standard API built into Flutter for interacting with desktop operating systems. Or at least have a standard set of recommended plugins which are supported.

For things that we believe should be built into the framework, there will be standard APIs; that's how Flutter works currently with mobile. Similarly, Flutter already has a model for supported plugins ([flutter/plugins](https://github.com/flutter/plugins)). So I'm not sure what this is requesting that's different from the current situation (other than perhaps "add more APIs and plugins", but that's too general to be actionable).

> Developing desktop apps with Flutter would be much easier if there were standard solutions rather than a jungle of competing plugins of varying quality.

This seems to be a description of a theoretical concern about what you think might happen, rather than a concrete issue; in practice, there is not a "jungle" of desktop plugins, because the desktop plugin ecosystem is still extremely new. In the case of Windows, we strong discourage publishing *any* plugins at this stage, in fact.

So the reality is that the root cause of your problem statement (that it's hard to figure out how to interact with desktop OS features) is not that plugins are a jungle, it's that the functionality you are looking for simply doesn't exist anywhere at this point. The assumption that a robust ecosystem won't solve that problem over time as the project matures is just that: an assumption.

> My proposal is to use the Electron API as a guide to develop standard desktop integrations which work with each major operating system

Replicating Electron's entire API surface is not a goal. We will evaluate specific feature requests for framework APIs and/or first-party plugins.

If there is a community of people interested in making a suite of plugins that closely replicate the Electron API surface, however, they could certainly do so.

**Comment by colinskow** [comment]
Thanks for your reply @stuartmorgan. I'm just suggesting that since desktop support is still in alpha and being formulated Electron (as a mature desktop framework) is a good guide for the necessary platform interfaces. I don't care how the API is implemented, the functionality is what is important.

**Comment by stuartmorgan** [comment]
Then the key part of my reply is:
> Replicating Electron's entire API surface is not a goal. We will evaluate specific feature requests for framework APIs and/or first-party plugins.
