### ISSUE TITLE
Windows docs and flutter-gold presubmit checks pending for many hours

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64158]
See for example https://github.com/flutter/flutter/pull/64122, which is needed for a g3 roll

/cc @mehmetf

**Comment by zanderso** [comment]
Incidentally, the link "View more details on flutter-dashboard" for Windows docs just takes you to the main page of the Flutter dashboard, which is not too helpful.

**Comment by jonahwilliams** [comment]
Windows docs were just disabled with https://github.com/flutter/flutter/pull/64125

**Comment by godofredoc** [comment]
Presubmit configuration are now read from a json file from the repository. Windows docs builder was removed and the roller PR was reading a json file which included windows docs builder but it was never running.

For this type of issues we need to rebase the PRs to get the latest version of the builders json file. In the future we expect this to happen very rarely as this race condition is happening with more frequency because of the migration of the builders to luci.

**Comment by Piinks** [comment]
The flutter-gold check only resolves after all other checks have resolved, so if other checks were stuck (like the Windows doc), that is why the flutter-gold check was stuck.

**Comment by godofredoc** [comment]
tests_only builder was fixed here:

https://github.com/flutter/infra/pull/193

That along with closing the roll to force the creation of a new one with a rebased commit fixed the problem and the new roll succeeded.
