### ISSUE TITLE
flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by SongHuaixu** [flutter/flutter#64216]
## Steps to Reproduce

1. flutter upgrade
Upgrading Flutter from /Users/songhuaixu/development/flutter...
Downloading Dart SDK from Flutter engine 74d32ecdbd46fae7320f496a445fff94c03c549f...
100  174M  100  174M    0     0  3045k      0  0:00:58  0:00:58 --:--:-- 3026k
Building flutter tool...
Read failed
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
2. ...
3. ...

## Logs

```
```

```
```

**Comment by DaZiYuan** [comment]
I encountered the same issue

···
flutter upgrade
Building flutter tool...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Running pub upgrade...
Because flutter_tools depends on dwds 6.0.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)

等待 0 秒，按 CTRL+C 退出 ...
Error: 'pub upgrade' still failing after 10 tries, giving up.
Can't load Kernel binary: Invalid SDK hash.
···

**Comment by fynxiu** [comment]
Disable `PUB_HOSTED_URL` and `FLUTTER_STORAGE_BASE_URL`. `dwds 6.0.0` hasn't been indexed in flutter.cn yet.

**Comment by SongHuaixu** [comment]
It's ok now

**Comment by Zony-Zhao** [comment]
No it't not. Still having this issue.
```
Because flutter_tools depends on dwds 7.1.1 which doesn't match any versions,
  version solving failed.
```
