### ISSUE TITLE
Flag to always log all exceptions in `dumpErrorToConsole()`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6423]
Exceptions after the first message are truncated in the logs, which can be a hindrance. Workaround right now is to call `resetErrorCount()` in strategic locations -- which works well if you know, roughly, where the exception is thrown.

This is a feature request from customer Leafy to add a flag to turn this off.

**Comment by Hixie** [comment]
Exceptions after the first are almost always completely bogus. I strongly, strongly recommend not looking at anything except the first exception.

Having said that, you can easily do this today, just add this line of code to your app's main:
```dart
  FlutterError.onError = (FlutterErrorDetails details, { bool forceReport: false }) {
    FlutterError.dumpErrorToConsole(details, forceReport: true);
  };
```

**Comment by mehmetf** [comment]
@Hixie Let me add some context to this. We found that it is common to have a layout related exception which is sometimes caused by platform, sometimes our code. For instance, we currently see this _all time time_:
```
I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during performLayout():
I/flutter : The _ToolbarLayout custom multichild layout delegate provided invalid box constraints for the child
I/flutter : with id "_ToolbarSlot.title".
I/flutter : BoxConstraints has non-normalized width constraints.
I/flutter : The offending constraints were:
I/flutter :   BoxConstraints(0.0<=w<=-64.0, 0.0<=h<=56.0; NOT NORMALIZED)
I/flutter : The minimum width and height must be greater than or equal to zero.
I/flutter : The maximum width must be greater than or equal to the minimum width.
I/flutter : The maximum height must be greater than or equal to the minimum height.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      MultiChildLayoutDelegate.layoutChild.<anonymous closure> (package:flutter/src/rendering/custom_layout.dart:64)
I/flutter : #2      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:48)
I/flutter : #3      _ToolbarLayout.performLayout (package:flutter/src/material/app_bar.dart:63)
I/flutter : #4      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:144)
```

We might not necessarily know how to fix this issue or it might not impact us significantly so currently it is marked as "cleanup". However, it hinders actual development because it is hiding any other exceptions that are completely unrelated.

In general, it is counterproductive to assume that the app should always be exception free. The clients should have the ability to prioritize which exceptions to tackle.

Your workaround works great though, so thanks. No need to reopen this issue. I just wanted to explain the rationale.

**Comment by Hixie** [comment]
The problem is that the exception you paste above is a great example of something that could be completely throwing everything off. If you try to fix exceptions after that one, you could be chasing ghosts.

**Comment by Hixie** [comment]
(btw, that particular one looks like a framework issue; please do file a bug so we can fix it)
