### ISSUE TITLE
Gesture handling causing a null-unsafe operation

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#64253]
Internal: b/167318775

Split off from https://github.com/flutter/flutter/issues/63984 as requested. Comes in two flavors:

```
Thread 0 main thread CRASHED_CastError: Null check operator used on a null value
at DragGestureRecognizer.acceptGesture(monodrag.dart:294)
at GestureArenaManager.sweep(arena.dart:157)
at GestureBinding.handleEvent(binding.dart:223)
at GestureBinding.dispatchEvent(binding.dart:199)
at GestureBinding._handlePointerEvent(binding.dart:157)
at GestureBinding._flushPointerEventQueue(binding.dart:103)
at GestureBinding._handlePointerDataPacket(binding.dart:87)
at _rootRunUnary(zone.dart:1206)
at _CustomZone.runUnary(zone.dart:1100)
at _CustomZone.runUnaryGuarded(zone.dart:1005)
at _invoke1(hooks.dart:267)
at _dispatchPointerDataPacket(hooks.dart:176)
```

```
Thread 0 main thread_CastError
at DragGestureRecognizer.acceptGesture(monodrag.dart:322)
at GestureArenaManager._resolveByDefault(arena.dart:251)
at GestureArenaManager._tryToResolveArena.<anonymous closure>(arena.dart:232)
at _rootRun(zone.dart:1182)
at _CustomZone.run(zone.dart:1093)
at _CustomZone.runGuarded(zone.dart:997)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1037)
at _rootRun(zone.dart:1190)
at _CustomZone.run(zone.dart:1093)
at _CustomZone.runGuarded(zone.dart:997)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1037)
at _microtaskLoop(schedule_microtask.dart:41)
at _startMicrotaskLoop(schedule_microtask.dart:50)
```

**Comment by HansMuller** [comment]
CC @goderbauer @dkwingsmt

**Comment by ryanhz** [comment]
I have a similar issue _CastError: Null check operator used on a null value

in the line of:
`final Duration timestamp = _lastPendingEventTimestamp!;` below:

```
  @override
  void acceptGesture(int pointer) {
    if (_state != _DragState.accepted) {
      _state = _DragState.accepted;
      final OffsetPair delta = _pendingDragOffset;
      final Duration timestamp = _lastPendingEventTimestamp!;
      final Matrix4? transform = _lastTransform;
```

**Comment by ryanhz** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-2.0.pre.34, on Mac OS X 10.15.6 19G2021, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.1)
[✓] Connected device (1 available)

**Comment by Hixie** [comment]
Assigned per comment on https://github.com/flutter/flutter/issues/63984

**Comment by dkwingsmt** [comment]
I've carefully examined the code and yet to think of a possibility that could have lead to this, nor can I reproduce it. I suspect that this might be caused by the thrown error of the router, and would not happen in normal operation. I suggest closing this issue (as well as #63984) until another occurrence.

**Comment by mehmetf** [comment]
I thought  #63984 is reproducible?

**Comment by dkwingsmt** [comment]
I tested gallery with the current master (on iOS simulator), tried to swipe back in various motions and couldn't observe crashes. Can you make sure it's still reproducible on master, and what exactly is the trigger?

**Comment by YeungKC** [comment]
@mehmetf 

I am interested in this, can u provide has reproducible steps?

**Comment by mehmetf** [comment]
@dkwingsmt It is still not clear to me whether you are talking about this issue or 63984.

63984 is not happening in Gallery because Gallery does not attempt to programmatically remove routes. @goderbauer 's repro isn't based on just motion, it is based on a sequence of events (both gesture and code) that happen to trigger the wrong thing.

**Comment by mehmetf** [comment]
This crash is happening in nearly all Flutter 1p apps with varying frequencies. customer:trends is getting hit the worst with nearly 1500 occurrences per week. I have asked for a repro but have not heard back.

**Comment by goderbauer** [comment]
@mehmetf Is there any kind of additional information available for the context of the crash? Like, what was the user doing when this happened? What was visible on screen? Anything that would help in debugging this further...

**Comment by goderbauer** [comment]
(Also: As long as we don't know if the crashes are related, can we keep the discussion of #63984 and this one separated? Makes it easier to follow what the current state is.)

**Comment by mehmetf** [comment]
customer: trends does not keep detailed logs unfortunately and this crash is happening rarely for many other users. customer:money reported only 20 instances in the past month. I asked them whether they can provide visual logs. Waiting to hear back.

**Comment by dkwingsmt** [comment]
@mehmetf Do they always observe both errors or they also ovserve the gesture crash alone?

**Comment by klivin** [comment]
I get the same error after updating to simulator with iOS 14.  

I can reproduce the error very quickly with a
Scaffold ->  ListView [vertical scrolling] -> [ListView [horizontal scrolling], ListView[horizontal scrolling]]

The horizontal scrolling lists are 3/4 screen height and contain 1 - 10 elements

Scrolling down and up while scrolling left and right reproduce this crash almost instantaneously

**Comment by goderbauer** [comment]
@klivin Can you post some runnable sample code that reproduces this reliably? That would help us a lot!

**Comment by klivin** [comment]
I will work on that. 

Since posting, after a few minutes of testing, I was not able to reproduce this on an iPhone X device yet.  Nor am I able to produce the crash when I switch from an iPhone SE simulator to an iPhone 8 simulator.  Very odd, beceuase on the iPhone SE simulator, I could reproduce very easily...

**Comment by Hixie** [comment]
@klivin It might be based on the screen size or pixel ratio or it could be a race condition based on something the OS is doing... hard to say. But if you have a very specific case where it reproduces reliably that will be super helpful regardless of what kind of device or simulator it is. :-)

**Comment by mehmetf** [comment]
We will keep an eye on this. I played with an app that was exhibiting this behavior but could not reproduce the crash. We aspire to make crash debugging better in 2021 through instrumentation. 

I am closing this as "could not repro".

**Comment by sudha-anecure** [comment]
Hi - we got this error from a user using our app built on 1.22.0 version of flutter, on an android device. Here is the stack trace reported on crashlytics from the screen. We have no further information. The above is the only information we have since this is on a production device of an end user.

Error:
Null check operator used on a null value
Stack trace:
#0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321)
#1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157)
#2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362)
#3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267)
#5      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295)
#6      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240)
#7      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213)
#8      _rootRunUnary (dart:async/zone.dart:1206)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
#11     _invoke1 (dart:ui/hooks.dart:265)
#12     _dispatchPointerDataPacket (dart:ui/hooks.dart:174)
Device parameters:
id: PPR1.180610.011
androidId: 4a3352dba7abae8c
board: MT6737
bootloader: unknown
brand: Nokia
device: NE1
display: 00WW_5_18D
fingerprint: Nokia/TA-1032_00WW/NE1:9/PPR1.180610.011/00WW_5_18D:user/release-keys
hardware: mt6735
host: cm-build-42-128
isPhysicalDevice: true
manufacturer: HMD Global
model: TA-1032
product: TA-1032_00WW
tags: release-keys
type: user
versionBaseOs: Nokia/TA-1032_00WW/NE1:9/PPR1.180610.011/00WW_5_180:user/release-keys
versionCodename: REL
versionIncremental: 00WW_5_18D
versionPreviewSdk: 0
versionRelease: 9
versionSdk: 28
versionSecurityPatch: 2020-09-05
