### ISSUE TITLE
Make flutter update-packages available for any project

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#64304]
I want to contribute to the Firebase repository and there we can finds lots of packages, each one with its own `pubspec.yaml`. AFAIK `flutter update-packages` only works for the Flutter repo, but it would be nice if we could use it as `flutter update-packages --current` for the current folder. So running it under the Firebase repo would update all the `pubspec.yaml` files automatically.

**Comment by jmagman** [comment]
Flutter is shelling out to pub here (on top of the checksum checking and dependency pinning logic).  
https://github.com/flutter/flutter/blob/c0ea00ed3f8db142e524aacfd5ebcdbfceb17278/packages/flutter_tools/lib/src/dart/pub.dart#L382-L393
You can file a pub feature request at https://github.com/dart-lang/pub/issues/new/choose since `flutter` tooling wouldn't add a feature to do this for non-Flutter projects.
