### ISSUE TITLE
[video_player] Add Fullscreen for Web

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#64397]
Add Fullscreen for Web

**Comment by ditman** [comment]
This feature is not available in any of the platforms, according to this:

https://github.com/flutter/flutter/issues/58114

**Comment by Bilonik** [comment]
@ditman if I change the parameter to make controls = true fullscreen works great.

video_player_web.dart line 157
 videoElement = VideoElement()
      ..src = uri
      ..autoplay = false
      **..controls = true**
      ..style.border = 'none';

**Comment by ditman** [comment]
@Bilonik I understand that that can be done, however, the plugin needs to run consistently across all platforms. (Ideally we should think on how to add the full screen feature to all platforms, that's why I linked the global issue)

**Comment by sondresorbye** [comment]
This works for web, but not the other platforms, right?

**Comment by sondresorbye** [comment]
Any updates?

**Comment by JiangJuHong** [comment]
Waiting for results

**Comment by michalkubizna** [comment]
@ditman I believe this feature should only be available on the web, as developers may want to include custom transitions and animations on other platforms, but that is not possible on the web due to restrictions in browsers like Apple's WebKit. Additionally, the web is currently the only platform where packages built on top of video players cannot utilize the enter functionality, as the VideoElement implementation is hidden.
