### ISSUE TITLE
Flutter Web Engine: Make the html page adapt to the canvas' size instead of hiding it

### ISSUE THREAD

**Issue by Auties00** [flutter/flutter#64501]
Hello,
I want to propose a change to the Flutter Web Engine in order to make scrolling easier and smoother.

The current implementation doesn't take into consideration that HTML pages, unlike Android, IOS or Desktop platforms, adapt to the size of the content that it's displaying. Because of this, when using a Scrollable widget, like a ListView, instead of letting the page adapt to the content of the scrollable widget and letting the browser handle scrolling as it would for any normal page, Flutter Web hides the overflow and handles internally scrolling using translations and offsets. 
You can find below what flutter web does right now visually, the red rectangle is the browser's viewport. For the browser, because the page isn't scrollable, only what is in the viewport exists. When the user scrolls, flutter web adds the needed widgets to the DOM and simulates scrolling using offsets and transformations.
![70Q906U](https://user-images.githubusercontent.com/28218457/91090326-2aa0a080-e655-11ea-8e47-8c58ec6b8cac.jpg)

Obviously, this introduces a lot of lag and makes it impossible to have the native scrolling bar next to the page.

What I'm proposing is to modify the engine and let the browser handle scrolling natively for scrollable widgets if their size is known, for example, this is not the case for a ListView.builder that doesn't specify its itemCount.

**Comment by markusaksli-nc** [comment]
The smoothness part is related to https://github.com/flutter/flutter/issues/32120

**Comment by ferhatb** [comment]
Will research feasibility. Very unlikely due to framework architecture and the way gestures/physics is handled.

**Comment by Auties00** [comment]
> Will research feasibility. Very unlikely due to framework architecture and the way gestures/physics is handled.

Thanks :)

**Comment by Auties00** [comment]
> Will research feasibility. Very unlikely due to framework architecture and the way gestures/physics is handled.

Any news?

**Comment by Hixie** [comment]
We've talked in the past about having a way for the framework to report to the engine the size it should render at (previously in the context of add-to-app where Flutter is being used to render content in a non-Flutter context). This would be similar. It'd probably require a non-trivial change to the dart:ui/framework integration, since we'd essentially need to have dart:ui pass down a BoxConstraints-like data structure and the `render()` method would then take a `Size` along with the `Scene` (or the `SceneBuilder` would take a size, or similar).

cc @chinmaygarde @xster @goderbauer

**Comment by yjbanov** [comment]
If the goal is to gain nativeness (i.e. scroll physics and scrollbars, not performance), then what's described here should be partially possible today, at least at the page level. Essentially, you could remove all scrollable widgets from Flutter, and instead put a scrollable platform view behind Flutter-rendered content. Then you can observe the [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) property and communicate it to Flutter so that Flutter updates the view according to browser's scroll position. You can probably also use it to render browser-native scrollbars (use [this trick](https://stackoverflow.com/questions/13382516/getting-scroll-bar-width-using-javascript) to get the scrollbar width and shrink Flutter content accordingly revealing the scrollbar. You would need to layout the entire page to know the total height and communicate it to the platform view so that the scrollbar appears in the right place.

This is assuming we're not doing anything funny with pointer event handling. I don't believe we call `stopPropagation` or anything, so this should be doable.

**Comment by yjbanov** [comment]
See also https://github.com/flutter/flutter/issues/77883

**Comment by Tofil** [comment]
I follow up my comment of #77883 that most browsers have scrolling happening off the main thread possibly yielding less jank on lower-end devices when the main thread is busy. So this issue might be a good step toward acceptable performance on mobile.
An interesting read about this topic :
 https://blogs.windows.com/msedgedev/2017/03/08/scrolling-on-the-web/

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/77883.
