### ISSUE TITLE
Engine linting fails on existing files

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#64576]
The linter was recently turned on (https://github.com/flutter/flutter/issues/61875), and it seems to be running on entire files, any time those files are touched. See for example [this failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871220052057936704/+/steps/lint_test/0/stdout), which is on a line that [the PR](https://github.com/flutter/engine/pull/20714) doesn't touch. Having these linter 'land mines' in files adds friction to PRs, and encourages mixing of linter fixes with functional changes.

Can we either run the linter only on changed lines (not sure if that's possible) or not enable the linter where the codebase isn't already clean?

@gaaclarke

**Comment by gaaclarke** [comment]
The linter was run against all the files in the engine repo, the ones that didn't pass were given the [FLUTTER_NOLINT](https://github.com/flutter/engine/commit/21efd7325e389881de4b46f946a2314db246bb3c) annotation which turns off linting for that file.  If you are experiencing problems with the linter that means your merge base may be before the addition of FLUTTER_NOLINT, make sure to rebase off of the latest.  Or there was some introduction of a lint failure between generating the FLUTTER_NOLINT annotations and when it actually landed.

Closing issue since not running the linter except where it is already clean is already happening.

**Comment by stuartmorgan** [comment]
We can add FLUTTER_NOLINT to the file in question, but what you describe above doesn't match what I'm seeing:

- https://github.com/flutter/engine/blob/master/shell/platform/linux/testing/mock_engine.cc Does not have `FLUTTER_NOLINT` on head.
- It was last changed on July 9th.
- The change enabling the linter was on July 22nd.

**Comment by gaaclarke** [comment]
Ahh, you know what.  I generated the list of files that needed FLUTTER_NOLINT on a mac.  Files only in Linux builds wouldn't have existed in my build commands to check.  We can FLUTTER_NOLINT them as we see them or you can run the linter across all the files on linux to find them.

Running the linter with the environment variable `FLUTTER_LINT_ALL` will allow you to have it do a pass on whatever system you last ran GN for.
