### ISSUE TITLE
Please upgrade to the generally available Firebase Crashlytics SDK to continue getting crash reports in the Firebase console past November 15, 2020. Learn more

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#64641]
google message:
Please upgrade to the generally available Firebase Crashlytics SDK to continue getting crash reports in the Firebase console past November 15, 2020. Learn more

https://firebase.google.com/docs/crashlytics/get-started?authuser=0&platform=android

**Comment by kunit1** [comment]
Issue should be posted in the flutter fire repo:
[Flutter Fire](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
