### ISSUE TITLE
[image_picker][android] PickedFile should store the original file name. 

### ISSUE THREAD

**Issue by 123cristen** [flutter/flutter#64685]
The image picker plugin generates new file names for the selected image which don't match the original ones. I would like to show the original file name to users in order to confirm their selection.

**Comment by mehmetf** [comment]
image picker returns a `PickedFile`. It should be relatively easy to add support for this in the interface and then return the actual OS filename using `ContentResolver` (https://developer.android.com/training/secure-file-sharing/retrieve-info).

Please feel free to contribute this to image_picker, it would be very much appreciated!

**Comment by liangtian123** [comment]
Any idea on how to resolve this problem?How get the image original filename？thinks！

**Comment by blue492** [comment]
Same problem here, how to get the origin image name?

**Comment by pedromassangocode** [comment]
iOS version of this bug is https://github.com/flutter/flutter/issues/54815.

**Comment by renehw** [comment]
Has anyone found a solution for this solution?

**Comment by allanwolski** [comment]
I need it too. Any progress?

**Comment by ydag** [comment]
Hi,

I researched to get the actual file name to send it when an image is picked with `image_picker`.  Let me explain a bit.

The current `image_picker` implementation combines a random string after the "image_picker" and it creates the file name that is saved in the `cache/` folder on Android and the `tmp/` folder on iOS. So when you received the `path` you will have this randomly created name instead original file name.      

Example: 
> tmp/image_picker67FB58C5-3859-4898-B06B-EBD196FA9E40.jpg

So the possible solution would be to create a randomly named folder after `cache` and `tmp` folders and save the image to that folder with the original name. So in this case, when you received the `path` it means you can actually have the real file name as well. 

Example: 
> tmp/D20CD4D0-9847-4087-8745-7E1233064CA6-61533-00070D13FF3B7EDA/original_name.jpg

After some investigation I found out :

- For Android, I was able to create a randomly named folder and get the image name with `Cursor` as it is mentioned on [this comment](https://github.com/flutter/flutter/issues/64685#issuecomment-681535581). So it might be relatively easy to implement this on Android.

- For iOS, this functionality isn't built-in to `UIImage` but I found out we can get the original image name from the `PHAsset`. But in this case, users must give full access to the picked image thus we can get the image name from the `PHAsset`. Since users also may choose limited access then the name will be `nil`. Maybe we can return images with names when we have access and return random names when we have limited access in this situation. But this is something I will discuss within the team if we want to implement it. (Related issue : [#54815](https://github.com/flutter/flutter/issues/54815) )

Please let me know if you have an idea or another way to solve this. Also, you can give thumbs up 👍🏻 if you want us to implement it like this.

After discussion, if we decide to implement this I will create a PR.

**Comment by brightseagit** [comment]
@ydag sounds good to me 👍.

**Comment by BistruBao** [comment]
Any update?  ;)

Thanks

**Comment by ArefMozafari** [comment]
Hi there 
Any Update? :)

**Comment by BernardinD** [comment]
I'm also curious about an update

**Comment by AlexV525** [comment]
The solution is quite simple while reading assets on both side:
- Android:`MediaStore.MediaColumns.DATA`
https://github.com/fluttercandies/flutter_photo_manager/blob/ba51cb0fdcf6b421bc8858655992ec4430c48af6/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt#L234
- iOS:`PHAssetResource.originalFilename` or `PHAsset valueOfKey:filename` https://github.com/fluttercandies/flutter_photo_manager/blob/ba51cb0fdcf6b421bc8858655992ec4430c48af6/ios/Classes/core/PMManager.m#L657-L661

**Comment by SynSzakala** [comment]
This should also trivial to implement on Web and desktop platforms since they provide this out of the box.
@AlexV525 I'd want to give it a shot if you're not already working on it.

**Comment by AlexV525** [comment]
> @AlexV525 I'd want to give it a shot if you're not already working on it.

@SynSzakala Sure. The picker doesn't seem involved with the `ContentResolver`, but the `Intent` mechanism instead.

If the resolver is the main scope of your requests, maybe try with [photo_manager](https://pub.dev/packages/photo_manager).

**Comment by SwiftDeveloper859** [comment]
Is it possible to change the file name with the original image name? currently it is showing the "img_picke with udid" can we replace this with the original image name in flutter iOS app?

**Comment by Tienisto** [comment]
The title should either remove "android" or add "iOS" also.

**Comment by MOhsain** [comment]
Can anyone please give me solution?
How to get the original file name after pick images from the ImagePicker?

**Comment by Tienisto** [comment]
A workaround would be to use [wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker)

**Comment by AlexV525** [comment]
> The title should either remove "android" or add "iOS" also.

@Tienisto The issue is about the ability on the Android platform and it seems to be fixed by https://github.com/flutter/plugins/pull/6096. Could you provide more details about iOS in a new issue? The issue has been triaged and fixed so we should move on next to avoid confusion for the team and other users.
