### ISSUE TITLE
'Flutter for Android' dependency list missing

### ISSUE THREAD

**Issue by Slifer47** [flutter/flutter#64740]
My Flutter project can't find io.flutter.app.FlutterApplication, and when I go to the project structure it tells me that the android module of my project is missing the dependency 'Flutter for Android'. I've run flutter doctor -v and everything is fine.

Does anyone have any idea of what I did wrong?

![image](https://user-images.githubusercontent.com/23084186/91481079-cd4a6080-e89b-11ea-9821-3694ae0b8f79.png)
![image](https://user-images.githubusercontent.com/23084186/91481132-de936d00-e89b-11ea-8ed0-2f602c6dc294.png)
![image](https://user-images.githubusercontent.com/23084186/91481150-e3f0b780-e89b-11ea-8561-f57ef4d06879.png)
![image](https://user-images.githubusercontent.com/23084186/91481208-f4089700-e89b-11ea-8129-ee2e1ce9900d.png)

**Comment by pedromassangocode** [comment]
Hi @Slifer47 
It is recommended to open the android module as a project in Android Studio IDE so that your imports are understood. You're receiving this message because you are opening files from android module while you opened a Flutter project.

You can fix this by opening a new instance of Android Studio and then open the android module of your project as a project in Android Studio.

Will close this as this is not an issue with Flutter itself. If you disagree please feel free to write in the comments bellow and I will reopen it.
Thank you
