### ISSUE TITLE
TextInputType.phone keyboard doesn't delete typed text when the keyboard is switched to extra symbols on Android

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#64761]
I think that Flutter is missing a concept in our key handling: we don't make a distinction between a lock key (`NumLock`, `ShiftLock`, or `ScrollLock`) being currently pressed, and the "lock" state being on/off.

I think Flutter should keep its current behavior with respect to key presses in that it should show when the key is actually being pressed, and add some API to ask if a lock state is currently enabled.

This might be hard to implement on macOS, where the lock keys don't send one of the key press events (key up, I think?) but should still be possible to detect based on waiting for a repeat event (if we don't get a repeat event within a timeout, send a key up anyhow).

Related to https://github.com/flutter/flutter/issues/60922

cc @dkwingsmt @stuartmorgan

**Comment by dkwingsmt** [comment]
I would say it's easier to implement the _state_ on macOS since we have the source of truth. It's harder to implement the events, but the least we could do is to follow a `down` with an immediate `cancel`, and precede an `up` with an immediate `sync`.

For other systems though, we might have to track the states, which is prone to losing sync.

**Comment by gspencergoog** [comment]
Ahh, yes, the cancel/sync events would help here.  GTK also has a clear understanding of the state of the lock, with `gdk_keymap_get_num_lock_state()`, et al.

**Comment by garlicPasta** [comment]
Is there any update on this one? It's crucial to our app that user can enter their phone number without getting confused, when they lets say enter '+' twice per accident and want to delete the last char then. It's in particular important for us since the phone number is required during the registration process.
Would be outstanding if somebody can fix that.
Thanks flutter team!

**Comment by dkwingsmt** [comment]
The demanded API has been added as `lockModesEnabled`. There's no plan to add them to `RawKeyboard`. 

@garlicPasta I'm not sure what your exact problem is, but can you check if any errors occur in the latest version? (If there's a problem in the stable channel, check out the master channel.)
