### ISSUE TITLE
MaterialApp onGenerateRoute show unexpected behaviour.

### ISSUE THREAD

**Issue by thangvip4321** [flutter/flutter#64775]
## Steps to Reproduce

3
This is the file /lib/main.dart, nothing else needed `import 'package:flutter/material.dart';

```dart
import 'login.dart';
import 'home.dart';
import 'splash.dart';
import 'register.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    initialRoute: '/splash',
    onGenerateRoute: (settings) {
      if (settings.name == '/splash') {
        return MaterialPageRoute(builder: (_) => SplashPage());
      } else if (settings.name == '/home') {
        print("ok");
        return MaterialPageRoute(builder: (_) => MainScreen());
      } else if (settings.name == '/login') {
        return MaterialPageRoute(builder: (_) => LoginPage());
      } else if (settings.name == '/register') {
        return MaterialPageRoute(builder: (_) => RegisterPage());
      }
    },
  ));
}
```

**Expected results:** 
 `settings.name` argument should be '/splash' on the first onGenerateRoute call. 
**Actual results:** 
`settings.name` argument was '/' on the first onGenerateRoute call, despite setting the initialRoute to '/splash'. And it turned to '/splash' on the second call, which is not explicitly executed from my part( no call to navigator.Push or Pop).
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hamdikahloun** [comment]
@thangvip4321 did you add home: SplashPage () in your code ?

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      initialRoute: '/SplashPage',
      onGenerateRoute: (settings) {
        // If you push the SplashPage route
        if (settings.name == '/SplashPage') {
          return MaterialPageRoute(
            builder: (context) {
              return SplashPage();
            },
          );
        } else if (settings.name == '/home') {
          // If you push the MainScreen route
          return MaterialPageRoute(
            builder: (context) {
              return MainScreen();
            },
          );
        }
      },
      home: SplashPage(),
    ));

class SplashPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Welcome"),
      ),
      body: Center(
        child: Text("SplashPage"),
      ),
    );
  }
}

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Welcome"),
      ),
      body: Center(
        child: Text("MainScreen"),
      ),
    );
  }
}
```

**Comment by thangvip4321** [comment]
Yes it solved my problem. However,i thought that  'setting.name'  is supposed to be  'initialRoute' on the first call to onGenerateRoute, why bother using 'initialRoute' when you also have to use 'home' property?

**Comment by markusaksli-nc** [comment]
I think you are somewhat misunderstanding how initialRoute works. As stated in the documentation for [`initialRoute`](https://master-api.flutter.dev/flutter/material/MaterialApp/initialRoute.html):

> If the route name starts with a slash and has multiple slashes in it, then it is treated as a "deep link", and before this route is pushed, the routes leading to this one are pushed also.

Navigator will **always** try to build the `/` route first in this case. This is described better in [defaultGenerateInitialRoutes](https://api.flutter.dev/flutter/widgets/Navigator/defaultGenerateInitialRoutes.html).

For your `/splash` initialRoute, the Navigator will attempt to build `/` (defined by the `home:` property of MaterialApp in this case) and then `/splash`. This is to ensure that the deep link to `/splash` can be popped and return to `/`. In this regard specifying `home: SplashPage()` **and** `initialRoute: '/SplashPage'` at the same time is completely wrong since it will push two copies of SplashPage. 

If you want push SplashPage with no root every time on startup, you shouldn't use initialRoute and simply specify `home: SplashPage()`. If you want to be able to change initialRoute before startup and not load SplashPage at the root of the deep link every time then your previous use case **will** work.

The documentation for initialRoute can be improved to explain this a lot better to new users. It should be stated that

> may be overridden by the code that launched the application

is the primary purpose of initialRoute, unless you want to load a deep link every time you launch or not use forward-slashes in your route names. It should also be mentioned that `/` is pushed first.

> For example, if the route was /a/b/c, then the app would start with the three routes /a, /a/b, and /a/b/c loaded, in that order.

This is just plain misleading.

**Comment by thangvip4321** [comment]
@markusaksli-nc i get it now, thank you for explaining this.

**Comment by markusaksli-nc** [comment]
Let's keep this open to clarify documentation for now
