### ISSUE TITLE
App freezes on Android Nougat after resumes from background

### ISSUE THREAD

**Issue by islavstan** [flutter/flutter#64784]
## Steps to Reproduce

1. launch demo app https://bitbucket.org/vkropivko/test-flutter/src/master/ on Android Nougat 
2. press button Start flutter screen with tabs
3. press home button
4. press the recent apps button and re-entering

Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (2 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
 

**Expected results:** 
app works
**Actual results:** 
App freezes
<details>

  <summary>Logs</summary>
E/EGL_emulation( 4235): tid 4287: swapBuffers(514): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation( 4235): egl_window_surface_t::swapBuffers called with NULL buffer

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @islavstan 
This issue was recently reported (https://github.com/flutter/flutter/issues/64414) and it was fixed by https://github.com/flutter/engine/pull/20735. The fix was recently cherrypicked into `beta` channel in https://github.com/flutter/engine/pull/20797.

If you want to have this fixed please use the `beta` channel where this issue was fixed, or you can wait until the fix lands into the `stable` channel.

Closing this since it was recently fixed and cherrypicked into `beta` channel.
Thank you
