### ISSUE TITLE
Multiple output directories specified with --pub

### ISSUE THREAD

**Issue by warent** [flutter/flutter#6489]
Something odd happens with `flutter create <project>`
If you try it without any options it works fine. If you try it with the --pub flag it says `Multiple output directories specified`

**Comment by eseidelGoogle** [comment]
@danrubel

**Comment by danrubel** [comment]
Does `flutter create --pub myapp` work for you?
Does `flutter create myapp --pub` fail?

My guess is that the underlying Dart command framework only handles options immediately after the command name (e.g. `create` is the command in this situation). I'll try to improve the error message so that its more obvious what the tool expects.

**Comment by somay-py** [comment]
try removing space from your app name

**Comment by GhagSagar23** [comment]
Just move your app name after the `--pub` flag
