### ISSUE TITLE
Custom device types as a solution for custom embedder support for flutter run

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#65067]
See also: https://github.com/flutter/flutter/issues/56404

A new command: `flutter add-custom-device --path-to-start-script=/?/` which takes a path to some executable (not the bundled asset itself). This is used to register some specific information in the persistent tool state. This would require some intermediary tooling. For example, it could not just consume `go` for the go desktop embedder or `cargo` for the rust embedder. The custom device would be treated as a non-ephemeral device, and always present.

The expectations of this custom script are that it can be passed flutter run launch arguments in a to-be-determined format: build mode, target file, et cetera. That custom script can then reentrantly call into flutter assemble to perform the actual build, or return a non-zero exit code and print stderr if that config is not supported. The embedder _must_ build with the same version of Flutter & Dart that the SDK is currently using.

To support discovery of the VM Service instance, whatever the executable is will need to forward a VM service URI over stdout, similar to the desktop devices.

This proposal is currently looking for potential customers (owners of custom embedders) to determine whether it is feasible. The advantage of this approach is that it enables features like full IDE support, and allows custom embedders to delegate more of the tooling to the existing flutter tool.

fyi @Hixie

**Comment by Hixie** [comment]
I like it. Suggestion: Should we make the thing that you pass in be a declarative static file rather than code? Obviously you'd need to expose hooks that run code in that, but it would give us a more flexible way to configure things (e.g. we could more efficiently populate places in the output that just need the name of the device).

cc @ardera who may be interested in being the first customer.

**Comment by Hixie** [comment]
> The custom device would be treated as a non-ephemeral device, and always present.

We don't necessarily even have to do this, do we? We could provide a hook for "is the device present" or "enumerate the actual device names of this type" the same way we do for Android/iOS.

**Comment by jonahwilliams** [comment]
I'm not quite sure whether a config or script makes the most sense, I suspect we'd have to try a few options. With the config you could enumerate the various build options that are supported, as well as run/detect scripts too (more scripts).

**Comment by jonahwilliams** [comment]
something I have been worrying about is making sure that we're very aware of any public APIs we create too

**Comment by jonahwilliams** [comment]
Also for reference, here is flutter devices --machine output, we'd likely need similar info for a custom device type, which lends more credence to a config file being the right way to start:


```
[
  {
    "name": "macOS",
    "id": "macos",
    "isSupported": true,
    "targetPlatform": "darwin-x64",
    "emulator": false,
    "sdk": "Mac OS X 10.15.6 19G2021",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Web Server",
    "id": "web-server",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Flutter Tools",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Chrome",
    "id": "chrome",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Google Chrome 85.0.4183.83",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  }
]
```

**Comment by ardera** [comment]
I really like the idea!

> cc @ardera who may be interested in being the first customer.

Somehow I didn't get a notification for this at all, just saw it by chance when I was looking for another issue.
Definitely interested, I always wanted to get SDK integration for flutter-pi but the SDK code was kinda hard to understand + I didn't want to maintain a fork.

**Comment by jonahwilliams** [comment]
Unfortunate! That is OK, no time like the present.

In order for this to work, the flutter tool would need to know how to build and install an app bundle for the flutter pi embedder. That leads to a few questions:

* What is an app bundle? Is that just a flutter build bundle
* How do you install onto the device?
* How do you detect that a device is conected?

**Comment by ardera** [comment]
> In order for this to work, the flutter tool would need to know how to build and install an app bundle for the flutter pi embedder.

There's 2 cases here:
- the target device is a remote device reachable via network. In that case we can just rely on SSH, even Windows 10 comes preinstalled with OpenSSH & scp AFAIK. The device is shown as connected when it is reachable via network.
- the target device _is_ the host device, i.e. the device running the SDK. Seems like an inferior solution since any build process would be far slower but I've seen some people using it

<br>

> * What is an app bundle? Is that just a flutter build bundle

- For debug mode, flutter-pi only needs the `build/flutter_assets`, which is created by `flutter build bundle`.
- For release mode, flutter-pi also needs an `app.so`, which by default is not located inside `build/flutter_assets`. Currently not an issue though bc release mode for linux ARM is not supported by the SDK anyway.
- flutter-pi has different cmdline invocations for release mode and debug mode, so we need to differentiate that in the config as well

<br>

> * How do you install onto the device?
- If it's a SSH device:
  - I think we can just deploy it to a random, anonymous folder on the target device (something like `/tmp/ABCD1234/app_name_here`)
  - if the host is running linux or macOS, `rsync` would be fine
  - if the host is running Windows you can use `scp`. It's actually pretty easy to get `rsync` running on Windows using cygwin and it is far superior to `scp`, but there are no recent precompiled executables available on the internet so it's one additional dependency you'd have to build & maintain
- If host == target you can just launch flutter-pi with `my_app/build/flutter_assets` directly

Right now, when launched with `/tmp/ABCD1234/app_name_here` as the arg, flutter-pi would expect the directory structure to look like this:
```
/tmp
└ ABCD1234
  └ app_name_here
    ├ (contents of build/flutter_assets here)
    └ app.so (for release mode)
```

<br>

> * How do you detect that a device is conected?

Not sure there's a way to get notified of some network device going online / offline, so I guess we could just ping it each time the user queries the device list?

<br>

**Creating a new device**
I think when registering custom devices, it'd be better to let the SDK manage all the config files.
In that case, some example invocation to register a new custom device could look like this:
```
$ flutter add-custom-device my-raspberrypi --template=ssh
Created a new custom device named 'my-raspberrypi'.
To configure it, edit the config file '/some-flutter-dir/custom_devices/my-raspberrypi.yaml`

$ flutter add-custom-device my-local-raspberrypi --template=local
Created a new custom device named 'my-local-raspberrypi'.
To configure it, edit the config file '/some-flutter-dir/custom_devices/my-local-raspberrypi.yaml`
```

Normally, `flutter devices` shows only the connected devices. But I think when custom devices are registered, it should show them when they're disconnected too, so it can also be used as a way for listing your registered custom devices.

<br>

**Example config file**
An example config file could look like this:
```yaml
custom-device:
  name: my-raspberrypi
  ssh-command: 'ssh pi@raspberrypi'
  embedder-invocation:
    debug: 'flutter-pi ${assetsDir} ${engineArgs}'
    release: 'flutter-pi --release ${assetsDir} ${engineArgs}'
```

or like this:
```yaml
custom-device:
  name: my-local-raspberrypi
  embedder-invocation:
    debug: 'flutter-pi ${assetsDir} ${engineArgs}'
    release: 'flutter-pi --release ${assetsDir} ${engineArgs}'
```

That `${engineArgs}` is just there so the SDK can provide any custom [engine switches](https://github.com/flutter/engine/blob/master/shell/common/switches.h) if it wants to.

<br>

**Observatory**

To hook up hot reload / hot restart, the SDK needs access to the dart observatory. I don't know an elegant way to do this, but flutter will always output a `flutter: Observatory listening on http://127.0.0.1:43003/UAjfA70UX6o=/` message when flutter-pi runs, so I guess one could just use a regex and skim the output for that message?

Then, to access the observatory on the host machine, you could use a ssh tunnel. Something like this: `ssh pi@raspberrypi -L 43003:127.0.0.1:43003`. After that, the observatory can be reached on the _host_ machine via `http://127.0.0.1:43003/UAjfA70UX6o=/`.

**Comment by jonahwilliams** [comment]
For an initial implementation I think it worth starting with a narrow set of use cases, i.e. remote device only in debug mode.

For detecting availability, we could definitely just ping every duration.

And the addition of a new command to register the custom device seems reasonable. I don't think we'd want to change the behavior of the existing devices command, so perhaps this command would have options for listing the registered custom device types.

As far the observatory goes, the tool can scan a process stdout to look for the observatory string - so as long as the command used to start the app can forward logging info it should "just work"

**Comment by JakeSays** [comment]
I think that we need to be mindful of the fact that just because something is running a linux kernel, that it will have ssh available. Currently ssh is not required to attach to an observatory, and I'd really like it to stay that way.

**Comment by jonahwilliams** [comment]
It would be up to whatever tooling is provided by the custom device script to make the connection - this could would not live in the flutter tool.

**Comment by jonahwilliams** [comment]
(That said, I'm still waiting for someone to get back to me with an initial implementation)

**Comment by ardera** [comment]
> I think that we need to be mindful of the fact that just because something is running a linux kernel, that it will have ssh available. Currently ssh is not required to attach to an observatory, and I'd really like it to stay that way.

I'm not sure I understand. AFAIK, we're not changing any existing behaviour here, it's a completely new feature. If a ssh-server is not installed on your target, you can just install it. If you don't have root access, sshd supports running as a non-root too, so you can (not 100% sure, but it should work) just install it to your user folder if you want to. If your target device doesn't have a network connection and is connected via serial or something, you can't access the observatory anyway, or did I miss something?

> (That said, I'm still waiting for someone to get back to me with an initial implementation)

That's okay, just a bit surprised bc I thought self-assigning meant you were going to work on it yourself? 😅 Or does it just mean you're going to design it?

**Comment by jonahwilliams** [comment]
Sorry! to be clear I just meant that I am available to help design/review as needed. I do not have any access to your device/tooling, 
so on my end there is nothing for me to do yet,

**Comment by ardera** [comment]
> Sorry! to be clear I just meant that I am available to help design/review as needed. I do not have any access to your device/tooling,
> so on my end there is nothing for me to do yet,

That makes sense, I'll work on it when I have time

**Comment by JakeSays** [comment]
@ardera I have a device that runs a tcp to can bridge, and I access the observer over can. My point is that whatever is done to the flutter tool to support custom embedders doesn't assume that ssh is always an option. But according to @jonahwilliams this shouldn't be an issue because all the custom stuff happens outside the flutter tool, if I am understanding correctly.

**Comment by GiovanniSM20** [comment]
and how can I currently edit these attributes ? have an app and one of my emulator have "fastStart" propertie which is returned as true but I need to pass a false

**Comment by jonahwilliams** [comment]
I'm not sure what you're referring to @GiovanniSM20 . The current device attributes are not configurable, and instead describing how our tooling works. This issue is about adding a new API to register custom device types, which would require telling the flutter tool how that device behaves.

**Comment by GiovanniSM20** [comment]
I understood what the issue is about but it was the issue that came closest to the problem I have. I'm trying to configure this attributes [posted from your output](https://github.com/flutter/flutter/issues/65067#issuecomment-686700859) the log are saying I need to Assign a value to ```fastStart``` propertie

**Comment by jonahwilliams** [comment]
Which logs?

**Comment by GiovanniSM20** [comment]
The logs from ```flutter run```

Log:
```
* What went wrong:                                                      
A problem was found with the configuration of task ':app:compileFlutterBuildDebug' (type 'FlutterTask').
  - Type 'FlutterTask': property 'fastStart' doesn't have a configured value. This property isn't marked as optional and no value has been configured. Possible solutions: Assign a value to 'fastStart' or mark property 'fastStart' as optional. Please refer to https://docs.gradle.org/7.0-milestone-2/userguide/validation_problems.html#value_not_set for more details about this problem.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 4s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         4.9s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by jonahwilliams** [comment]
@GiovanniSM20  Can you please file a bug and include the output of `flutter doctor -v` ?

**Comment by GiovanniSM20** [comment]
Sure I'll open a issue, thanks @jonahwilliams !

**Comment by ardera** [comment]
I'm currently working on implementing this, however there are a few things I'm not sure of:

What's the correct way to build the asset bundle. I'm currently using this, is this right?
```dart
await BundleBuilder().build(
  platform: await targetPlatform,
  buildInfo: BuildInfo.debug,
  mainPath: 'lib/main.dart',
  depfilePath: defaultDepfilePath,
  assetDirPath: getAssetBuildDirectory(),
  treeShakeIcons: false
);
```

#### config file
- I chose a single config file instead of multiple ones bc thats probably nicer for both the SDK and the user.
- used JSON for the config file because the SDK already uses it and it also allows us to use a JSON schema for autocompletion (that way you don't have to remember the exact "syntax" & meaning of any config options, works really well for Windows Terminal config at least. for YAML it's not really there yet). Where should we put that schema? It needs to be accessible via http/s. Should we just add it to the repo somewhere?
- config file currently lets you specify a command for:
  - pinging the device (for example `ping -n 1 raspberrypi`)
  - installing the app (`scp -r ${localPath} pi@raspberrypi:/tmp/${appName}`)
  - uninstalling the app (`ssh pi@raspberrypi "rm -rf '/tmp/${appName}'"`)
  - running the app in debug mode (`ssh pi@raspberrypi "flutter-pi /tmp/${appName} --observatory-host=192.168.178.123"`)
- also lets you disable a device config, so we can have templates / examples in the config file

#### port forwarding
- kinda difficult. First of all, for ssh it's kinda hard to detect doubly-forwarded ports, bc for example `ssh -L 127.0.0.1:12345:127.0.0.1:12345 pi@raspberrypi` will work, even if there's another command like `ssh -L 127.0.0.1:12345:127.0.0.1:12346 pi@raspberrypi` already running, so you can have a single local port forwarded to multiple remote ports. However, it will fail if that local port is used by any other (non-`ssh`) program. Not sure this is a problem though.
- Also, it's kinda hard to detect errors with ssh port forwarding. When you start the ssh port forward command, you get an exitCode != 0 on failure. But on success, the ssh executable will just stay running. So you never really know if the port forwarding succeeded and you can now use the port.
- We could just use a regex and consider it a successful launch when maybe we found the bash prompt or something like that, but then we'd depend on ssh-specific behaviour
- Maybe we should let the user configure their own `portForwardingSuccessRegex` in the config?
- Another way would be to let the user specify a port `forward` and `unforward` command in the config
- Though to get the correct behaviour for these two commands using just ssh as a base, they'd have to write their own script files and store them somewhere on disk again which is kinda inconvenient

- Currently, I just don't forward the ports at all and assume the observatory URL as printed by the device can be connected to as-is, so I use the `--observatory-host` engine flag to make the observatory accessible to the LAN.


What do you think? Where should I put the JSON schema? How should I implement the port forwarding?

**Comment by JakeSays** [comment]
@ardera I am confused. What exactly is this that you are implementing?

**Comment by jonahwilliams** [comment]
For building a bundle:

Yes, I think that is a reasonable way to start. We'll need to pipe through all the correct configuration from the debuggingOptions.buildInfo object, but It might be easier to point that out in a code review

For schema:

single JSON file sounds great, its generally much easier to process and validate than yaml is. 

on port-forwarding:

Yeah its tricky- I don't have any great suggestions here. Tools like adb use a daemon that tracks this sort of thing, maybe the flutter tool should track the forwarded ports for this device similar to how it does that for regular devices.

>We could just use a regex and consider it a successful launch

I think that is a reasonable place to start. For locating the schema, I think we could have a tool command that accepted a file path, then maybe the tool could copy it somewhere in the cache?

**Comment by JakeSays** [comment]
@jonahwilliams @ardera I am confused by this issue. I thought this was about creating a generic way to extend the flutter tool for any custom embedder. From what I see there are some very specific constraints being placed on it, like the need for ssh/port forwarding, etc. Is this the case?

**Comment by jonahwilliams** [comment]
>  I thought this was about creating a generic way to extend the flutter tool for any custom embedder

Correct, but this is currently being driven by use cases and @ardera is using ssh to connect to their embedder. I don't imagine we'd require anything, besides the config file mentioned earlier.

**Comment by ardera** [comment]
> @jonahwilliams @ardera I am confused by this issue. I thought this was about creating a generic way to extend the flutter tool for any custom embedder. From what I see there are some very specific constraints being placed on it, like the need for ssh/port forwarding, etc. Is this the case?

Additionally to what @jonahwilliams said, you can substitute anything you want for the install / uninstall / runDebug / forwardPort command in the config, so you should be able to make them work with your specific setup. I'll still try to make them work best with ssh of course.

> For building a bundle:
> 
> Yes, I think that is a reasonable way to start. We'll need to pipe through all the correct configuration from the debuggingOptions.buildInfo object, but It might be easier to point that out in a code review
> 
> For schema:
> 
> single JSON file sounds great, its generally much easier to process and validate than yaml is.
> 
> on port-forwarding:
> 
> Yeah its tricky- I don't have any great suggestions here. Tools like adb use a daemon that tracks this sort of thing, maybe the flutter tool should track the forwarded ports for this device similar to how it does that for regular devices.
> 
> > We could just use a regex and consider it a successful launch
> 
> I think that is a reasonable place to start.

Okay, thanks!

> For locating the schema, I think we could have a tool command that accepted a file path, then maybe the tool could copy it somewhere in the cache?

I'm not sure I understand, what file should be copied to cache?

**Comment by JakeSays** [comment]
@ardera will all of those commands be required? For instance, forwardPort - on my embedder there is nothing to forward.

**Comment by ardera** [comment]
@JakeSays I plan on making it not required, but even if not, you should be able to just substitute it with a no-op like `/usr/bin/true`, or if we use that regex to detect a successful launch, just any command that outputs something that triggers the regex. (so for example, a `echo hello` command and a `hello` regex)

**Comment by jonahwilliams** [comment]
We don't have to make forward port required. The desktop devices already handle a no-op here.

**Comment by jonahwilliams** [comment]
> For locating the schema, I think we could have a tool command that accepted a file path, then maybe the tool could copy it somewhere in the cache?

> I'm not sure I understand, what file should be copied to cache?

Sorry, I meant the JSON schema you are writing - I'd imagine we'd have a flutter command to sort of "install" it. That way the tool would have a simple check when it starts up to check for custom device types.

**Comment by ardera** [comment]
> Sorry, I meant the JSON schema you are writing - I'd imagine we'd have a flutter command to sort of "install" it. That way the tool would have a simple check when it starts up to check for custom device types.

May be a misunderstanding 😄  The schema I meant is a JSON document that describes the properties of another JSON doc.
For example, let's say our schema is this: https://aka.ms/terminal-profiles-schema
Then we'd make our config file look like this to have autocompletion when editing in VS Code:
```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "copyOnSelect": false,
    "copyFormatting": false,
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            // profiles here 
        ]
    },
    "schemes": [],
    "actions":
    [
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },
        { "command": "find", "keys": "ctrl+shift+f" },
        { "command": "closeTab", "keys": "ctrl+shift+w" },
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}
```

So ideally, the schema would somehow be available via http/s. I think it'd work via a filepath too when the schema is somewhere inside the flutter SDK, but then for you couldn't copy configs between devices, couldn't edit them nicely without a SDK installed, etc. We could just put it somewhere in the github repo and access it via the raw github url

**Comment by jonahwilliams** [comment]
Ahh, that makes sense. I think generally we put stuff like that in the tool repo itself, so that we can keep updates in sync with the exact version of the tool that people are using.

**Comment by ardera** [comment]
> Ahh, that makes sense. I think generally we put stuff like that in the tool repo itself, so that we can keep updates in sync with the exact version of the tool that people are using.

okay 👍

**Comment by JakeSays** [comment]
Would it be possible to add a post build step to support custom packaging of the build results?

**Comment by ardera** [comment]
> Would it be possible to add a post build step to support custom packaging of the build results?

sure, I can do that

**Comment by JakeSays** [comment]
@ardera thank you!
