### ISSUE TITLE
Add more OS information to 'flutter doctor' on Linux

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#65095]
Currently `flutter doctor`'s OS field on Linux just says "Linux". By contrast, on macOS it has the full OS version including the exact build number.

We have frequently needed to get distro information when investigating Linux desktop issues, so it would be good to add the distro name and version to that string.

/cc @robert-ancell

**Comment by jonahwilliams** [comment]
I think we tried to add this information a while back, but that failed during a g3 roll. I'm not clear on the exact details, but @zanderso might

**Comment by zanderso** [comment]
Ah, sorry for dropping the ball on this. The g3 roll failed due to an old version of `package:platform` there, but the tool no longer uses `package:platform`, and instead uses `dart:io`'s `Platform` directly, so this should be safe to try again.

PR here: https://github.com/flutter/flutter/pull/50739
Older issue here: https://github.com/flutter/flutter/issues/50575

That PR might not include distro information. It is just taking whatever info we can get from the Dart VM. But it might be possible to extend if it can be found in some canonical location. I can try to resurrect the old PR, but others might be able to get to that sooner than me.

**Comment by stuartmorgan** [comment]
Based on the test in that PR, it's stripping out distro, so we'll need to adjust that.

@robert-ancell suggested in another issue that we could read [`/etc/os-release`](https://www.freedesktop.org/software/systemd/man/os-release.html), which avoid having to try to tease apart what is and isn't useful from the full string that `Platform` gives us. Maybe we could use `PRETTY_NAME` from there plus the version from `Platform`
