### ISSUE TITLE
Export widget as Video

### ISSUE THREAD

**Issue by marcobraghim** [flutter/flutter#65254]
## Use case

At this time we know that is possible export a widget as an Image file using RenderRepaintBoundary. Would be great to have some way to export an animation as video.

## Proposal

I'm sugesting that because at this time I have a scenario with: into a Stack there's a video as background, some texts, images, color filters over video and I need to convert all it into a single video, which is very difficult.

**Comment by premingiet** [comment]
>That won't work like that,
>Basically you need to do these steps
1) create an opengl context and render video on the surface.
2) draw over the surface as textures.
3) Attach a low level decoder and encoder to that surface, like you may use __MediaCodec__ api for that
4) Make your own low level filters as textures and shaders in opengl
5) use mediaplayer to play video and redirect its output to that opengl surface where you can re-encode the transformations to video as h264 or something.

>Issues
1) currently flutter doesn't create any opengl context or handle painting for opengl, even in texture widget. All opengl paintings are handled in background.
2) You have to do low level stuff for this, and currently no crossplatform api is available for that because now, Android uses __OpenGLES__ for rendering surfaces and all, but iOS has stopped support of openGLES in latest version and uses __METAL__ framework for that, so basically crossplatform api needs to be built from ground-up to support both features and do some low level video frame manipulation stuff.

>Solution
1) you have to use __java or kotlin__ and program for android and use  low level api and work with __openGLES__ surface.
2) use __swift__ for iOS and use its own __Metal__ framework and its own lowlevel api for frame manipulation.

**Comment by markusaksli-nc** [comment]
Labeling this as a proposal but feel free to close if this is infeasible

**Comment by polarby** [comment]
Any updates on this?

**Comment by polarby** [comment]
I have now developed a high-level [render package](https://pub.dev/packages/render) that heavily optimizes the approach of repaint boundary capturing.


Wrap you widget with `Render`widget:
```dart
import 'package:render/render.dart';

final controller = RenderController();

@override
Widget build(BuildContext context) {
   Render(
      controller: controller,
      child: Container(),
   );
}
```
And then capture the motion with the controller:
```dart
final result = await renderController.captureMotion(
     duration,
     format: Format.gif,
);

final file = result.output;

```

**Comment by marcobraghim** [comment]
> I have now developed a high-level [render package](https://pub.dev/packages/render) that heavily optimizes the approach of repaint boundary capturing.
> 
> Wrap you widget with `Render`widget:
> 
> ```dart
> import 'package:render/render.dart';
> 
> final controller = RenderController();
> 
> @override
> Widget build(BuildContext context) {
>    return Render(
>       controller: controller,
>       child: Container(),
>    );
> }
> ```
> 
> And then capture the motion with the controller:
> 
> ```dart
> final result = await renderController.captureMotion(
>      duration,
>      format: Format.gif,
> );
> 
> final file = result.output;
> ```

That's really nice, thank you. I don't need it anymore, the task I was working on when asked it is over, but it's really great to the community that someone has done. Cool

**Comment by polarby** [comment]
Thanks! Yes, I just wanted to put the answer here as a reference for others. I know that this might not be a native way from flutters SDK, but I don't think they will put more effort into doing something like that. @marcobraghim So maybe we should close this issue?

**Comment by polarby** [comment]
This package is very well documented, please refer to the [Using settings to keep up performance](https://pub.dev/packages/render#limitations-and-performance) heading to check what you can do to keep performing at high quality. Due to hardware limitations, you must compensate for either the process duration, video quality, or fluency (what you have described). I recommend taking longer rendering time instead of fluency.

**Comment by jonahwilliams** [comment]
We don't intend to add this to the framework.
