### ISSUE TITLE
Support [quick_actions] on Flutter Web

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#65353]
Using [Quick Actions](https://pub.dev/packages/quick_actions) and running the app in Flutter Web results in:

    MissingPluginException(No implementation found for method getLaunchAction on channel plugins.flutter.io/quick_actions)

upon startup.

Quick actions aren't supposed to work on the web, of course, but the plugin should tolerate being included in a cross-platform app that gets compiled for both web and mobile.

Yes, `if (!kIsWeb)` is a possible and simple workaround but it probably should be included in the plugin itself, to make it transparent.

<details>
  <summary>Doc</summary>

[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.2.pre at E:\Android\flutter-beta
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
Process finished with exit code 0
</details>

**Comment by softmarshmallow** [comment]
Is it because of annoying exception logs?
for not-that-smart work around you can register global exception handler and catch the `PlatformException`

**Comment by deakjahn** [comment]
As a general rule, I think that each and every plugin that only provides services to some platforms should handle the case of being compiled on a non-supported platform gracefully.

Or, at least, they should provide some static `IsSupported` to check for, if there is no other viable solution, that can be called safely before actually using the services.

**Comment by stuartmorgan** [comment]
> As a general rule, I think that each and every plugin that only provides services to some platforms should handle the case of being included on a non-supported platform gracefully.

There is no issue with including the plugin; the issue is only with *calling* a plugin when there's no implementation for it. Silent no-ops would be more confusing than getting an error.

> Or, at least, they should provide some static IsSupported to check for, if there is no other viable solution, that can be called safely before actually using the services.

This would undermine one of the goals of plugin federation, which is that anyone could provide an implementation for any platform. We don't know, as authors of the app-facing plugin, what platforms someone might have implementations for.

> But, in this case, as a bare minimum, a specific exception saying 'Not supported on the Web' would still be better than this one above.

This would require registering a web implementation for the plugin just to throw that error, which would cause the plugin to show on pub.dev and in the pubspec as supporting web, which would be far more confusing.

Clients of plugins that don't support all of the platforms they are targeting should do their own platform checks before attempting to call into those plugins. (Or, if they personally want no-ops, make a no-op implementation of the platform interface, and set that at startup on unsupported platforms.)

> how can we check if is web to ignore the error :(

See https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html
