### ISSUE TITLE
Flutter doctor command not working.

### ISSUE THREAD

**Issue by KESHAVBERG** [flutter/flutter#65364]
![issue](https://user-images.githubusercontent.com/49027903/92436220-d43d7100-f1c1-11ea-8dd5-387650ba7ed7.png)
![Annotation 2020-09-06 151051](https://user-images.githubusercontent.com/49027903/92436222-d7d0f800-f1c1-11ea-9a47-12c08b4fd0cc.png)

I have been trying to run flutter commands for weeks still it is just showing the cursor and no improvement. I can't create a project in AS as well as in VS code.

**Comment by darshankawar** [comment]
Hi @KESHAVBERG,
Have you followed all the steps mentioned [here](https://flutter.dev/docs/get-started/install/windows) ?
Do you have by any chance multiple folders downloaded at same path due to which it could be conflicting the command ?
Are you able to run any other flutter command ?
If you have multiple folders downloaded before, can you delete all and start afresh by following all the steps in the document linked above ?
Thanks

**Comment by KESHAVBERG** [comment]
> Hi @KESHAVBERG,
> Have you followed all the steps mentioned [here](https://flutter.dev/docs/get-started/install/windows) ?
> Do you have by any chance multiple folders downloaded at same path due to which it could be conflicting the command ?
> Are you able to run any other flutter command ?
> If you have multiple folders downloaded before, can you delete all and start afresh by following all the steps in the document linked above ?
> Thanks

Yes, I followed the steps. I deleted everything and started again 5 times this past week. Nothing happened. I Still have that issue.

**Comment by KESHAVBERG** [comment]
I solved the problem by moving flutter SDK to c\..

**Comment by darshankawar** [comment]
Closing this as non-issue.
