### ISSUE TITLE
Plugin: sqlite

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#654]
Both Android and iOS expose sqlite. We can expose it as a service to our developers.

**Comment by sethladd** [comment]
An internal customer asked for this. So, +1 for them :)

**Comment by sethladd** [comment]
Found a plugin for sqlite: https://github.com/tekartik/sqflite

**Comment by sethladd** [comment]
I think we can close this issue, because https://github.com/tekartik/sqflite exists? We have this issue labeled as "self service".

**Comment by tvolkert** [comment]
> I think we can close this issue, because https://github.com/tekartik/sqflite exists?
> We have this issue labeled as "self service".

👍  -- it's published as https://pub.dartlang.org/packages/sqflite

**Comment by eukreign** [comment]
Since sqlite is just a C library it would be much simpler and produce a more consistent developer experience if it was the same library built the same way for Android and iOS. If you look at the sqflite project there are certain differences documented between the two native versions of SQLite (ios/android) because sqflite re-uses the sqlite installed in each respective OS instead of bundling it's own.

Can we have one sqlite embedded inside Flutter without all of the "native API" overhead/differences?

**Comment by sethladd** [comment]
Perhaps that will be possible when you can add/access C/C++ to Flutter's plugins, which is this issue: https://github.com/flutter/flutter/issues/7053

**Comment by mit-mit** [comment]
@eukreign very interesting, that sounds look a good potential idea. But it's a bit different from what we are tracking in the present bug, so would you mind opening a new bug for that request?

**Comment by sethladd** [comment]
I'm going to close this issue, as sqflite is the option we have today. It supports iOS and Android, as far as I can tell. We can reopen this issue if we need to, but for now, please use sqflite :)
