### ISSUE TITLE
Navigator.pushReplacement

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6544]
A common pattern which both customer:fast and customer:mulligan have run into is as follows:

App starts up. App shows a loading screen.
App finds you are not logged in. App pushes a login screen. You shouldn't be able to go back to the loading screen.
User logs in. App pushes a home screen. You shouldn't be able to go back to the login screen.

We need a way to push a new route in such a way as it animates in but you can't go back to the previous one and the previous one goes away once it's in.

**Comment by Hixie** [comment]
keywords: Navigator route replace

**Comment by gavindoughtie** [comment]
Another feature that would be nice is a way to push navigations outside of a particular widget context. Say for example you are listening for push notifications and (for critical notifications) you want to force the user to a particular route when the notification comes in.

**Comment by lear7** [comment]
@HansMuller Dear sir, I do have a similar scenario: 
step1: page1 (cart page) -> page2 (add address) 
step2: add a new address
step3: pushReplacement to page3 (addresses book)
step4: user choose the address just added from page3 (addresses book)
step5: pop page3 with the selected address, now we have page1. **BUT, page1 can not receive the result now, since page1 have received the result at step3.**
step6: then page1 (cart page) can show the address that user just added.

So, if there is a solution to make this work? Have a nice day!
