### ISSUE TITLE
[quick_actions] Method Channels reverse direction example in doc

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#65595]
In docs:
https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab

`Note: If desired, method calls can also be sent in the reverse direction, with the platform acting as client to methods implemented 
in Dart. A concrete example of this is the quick_actions plugin.`

But quick_actions https://github.com/flutter/plugins/tree/master/packages/quick_actions/android/src/main/java/io/flutter/plugins/quickactions

Doesn't provide example where channel.invokeMethod  was used.

**Comment by mvanbeusekom** [comment]
@Alexufo apologies for the late reply. But you are correct the quick_actions plugin only uses method channels in reversed direction for the iOS implementation (see the [FLTQuickActionsPlugin.m](https://github.com/flutter/plugins/blob/master/packages/quick_actions/quick_actions/ios/Classes/FLTQuickActionsPlugin.m) file).

If you are still looking (or maybe someone else) for a good Android example, one can be found as part of the camera plugin (see the [DartMessenger.java](https://github.com/flutter/plugins/blob/master/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java) file).

Since this is more an issue for the flutter/website repo I raised the issue flutter/website#5636 there with the question to improve the documentation. In the meantime I will close this issue, if you disagree feel free to let me know and I will reopen it.
