### ISSUE TITLE
video and audio both media play at same time in flutter app for both android and iOS.

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [flutter/flutter#65609]
I am trying to play video and audio at same time in flutter by using 

  **assets_audio_player: ^2.0.9+2 ==> For assets  audio file playing
  audioplayers: ^0.16.1 ==> for URL audio file playing
  video_player: 0.10.12+2 ==> for URL Video file playing** 

but when play audio and video in same time at same screen that time video was stack and video volume is stopped.

Thanks

**Comment by darshankawar** [comment]
Hi @bhallaramdhatarwal,
Except `video_player` plugin, rest of the plugins you mentioned are 3rd party. Please consider opening this issue in their respective repository, since it doesn't seem to be an issue with Flutter and it's plugin.
Closing this as non-issue from Flutter side. If you disagree, write in comments and I'll reopen.
Thanks
