### ISSUE TITLE
Flutter crash during app creation 

### ISSUE THREAD

**Issue by IumoInfinium** [flutter/flutter#65604]
I think it is due to some antivirus installed making it to go crash on creating a new app but this issue can be solved just by putting exception on that particular file for antivirus 
[flutter_01.log](https://github.com/flutter/flutter/files/5207126/flutter_01.log)

**Comment by darshankawar** [comment]
Hi @IumoInfinium,
You may add an exception in the anti-virus sofware settings to ignore the particular file, since it may not be feasible from Flutter framework to add exception for each anti-virus, as there are N number of anti-viruses.
I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen.
Thanks.
