### ISSUE TITLE
its annoying using separate widgets for everything

### ISSUE THREAD

**Issue by godalming123** [flutter/flutter#65651]
I switched to flutter from html css and js for the reasons below:
I hate having 3 scripts to manage
js is hard to use and not scalable
I am considering developing desktop/mobile applications and want to use one language. 

However it is very annoying using separate widgets for separate tasks.
EG I want an animated widget to appear with a fade animation, be positioned and be a certain size. This would require in flutter :
Position (
    //positioning,
    child: AnimatedOpacity(
        //animations,
        Container(
            //sizing,
            child: widget,
        ),
    ),
)
whereas in html it would only require :
<widget styling="positioning, animations, sizing">
    
</widget>

**Comment by Yodart** [comment]
Hey, @godalming123 I'm not sure what the end goal of this issue is. The flutter community uses the repo as a safe place to share knowledge and more importantly help the framework and its developers/users grow. I can personally tell you that as a person that migrated from the web myself you'll find flutter a delight to work with once it clicks for you, in the meantime lets keep repo for the more specific questions, perhaps u could use some of the following material to explore more about the framework and help us yourself to make Flutter better each day:

https://www.youtube.com/watch?v=b_sQ9bMltGU&list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG
https://www.youtube.com/watch?v=wgTBLj7rMPM&list=PLjxrf2q8roU2HdJQDjJzOeO6J3FoFLWr2
https://www.youtube.com/watch?v=TF-TBsgIErY&list=PLjxrf2q8roU0Net_g1NT5_vOO3s_FR02J
https://www.youtube.com/watch?v=GXIJJkq_H8g&list=PLjxrf2q8roU2v6UqYlt_KPaXlnjbYySua

**Comment by markusaksli-nc** [comment]
Hi @godalming123
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
