### ISSUE TITLE
what about make context to be global variable instead of parameters?

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#65727]
I think it will be easy and help developers to use context anywhere without pass it as parameters.

**Comment by PixelToast** [comment]
Many contexts exist at once (there is one for every widget in the tree) so just making it global is not feasible, what use case do you have in mind specifically?

**Comment by pedromassangocode** [comment]
You can read more about BuildContext at https://api.flutter.dev/flutter/widgets/BuildContext-class.html.

**Comment by mahmoudsalah37** [comment]
> Many contexts exist at once (there is one for every widget in the tree) so just making it global is not feasible, what use case do you have in mind specifically?

look at this links :
-----------------------
why i need everytime to use someting like navigator and snakbar (etc...)  out of statefull ot stateless widget 
i must pass param of BuildContext.
1) https://github.com/flutter/flutter/issues/32304
2) https://stackoverflow.com/questions/55956707/how-do-i-access-buildcontext-outside-of-a-stateful-or-stateless-widget
3) https://stackoverflow.com/questions/51803755/getting-buildcontext-in-flutter-for-localization
4) https://stackoverflow.com/questions/56144016/how-do-i-make-the-global-type-context-variable-in-flutter

**Comment by pedromassangocode** [comment]
@mahmoudsalah37 
You can think of a BuildContext as a reference of a Widget and depending on the use case, you may need a reference of different widgets for different tasks.

For example to navigate you need a context that is a descendant of a `Navigator` widget. To show a `SnackBar` you need a context that is a descendant of a `Scaffold` widget. Widgets in Flutter can change locations and when they change they may (or may not) be a child of a `Scaffold` widget and if then you try to show a `SnackBar` it may throw an exception because it needs a `Scaffold` widget to show a snackBar and the scaffold is not available anymore.

To navigate you can avoid context by using a global navigatorKey/NavigatorState as described at https://stackoverflow.com/a/53397266.

To show snack bars you can always create a global variable of ScaffoldState and use it to show it. Keep in mind that if you use it in a point where the `Scaffold` is not in the tree you will not be able to display a snackBar:

```dart
final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey();

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      body: Center(
        child: RaisedButton(
          onPressed: () {
            scaffoldKey.currentState.showSnackBar(SnackBar(
              content: Text('Hi!'),
            ));
          },
        ),
      ),
    );
  }
}
```

@mahmoudsalah37 Does this helps?
@PixelToast do you agree that this is not a valid proposal and should be closed?
