### ISSUE TITLE
how to set cookie

### ISSUE THREAD

**Issue by NieYinlong** [flutter/flutter#65745]

**Comment by Abhishek01039** [comment]
Hi @NieYinlong 
This plugin is useful for you 
https://pub.dev/packages/universal_html 
Thanks.

**Comment by darshankawar** [comment]
Hi @NieYinlong,
Your question is incomplete and in order to help you better, please provide some description on the issue or question you have.
Also, this question is more suitable to be asked on StackOverflow.
Please see https://flutter.dev/community for resources and  if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
