### ISSUE TITLE
Form validation using by model

### ISSUE THREAD

**Issue by maxime-aubry** [flutter/flutter#65760]
Hello.

Today, i uploaded my new library on pub.dev : [flutter_model_form_validation](https://pub.dev/packages/flutter_model_form_validation).
So, my library permits developers to use model form validation into flutter projects, as Microsoft propose it with [System.ComponentModel.DataAnnotations](https://docs.microsoft.com/fr-fr/dotnet/api/system.componentmodel.dataannotations?view=netcore-3.1).
Actually, I create the equivalent in Dart.
Of course, this is a first version and it's not as complete as Microsoft's version.

## Use case

I understood that "classical" validation is not centralized and does not permit to validate a property compared to another easily.
So, validate a form using by a model is a good way in my opinion.
You can visit the homepage of my package [flutter_model_form_validation](https://pub.dev/packages/flutter_model_form_validation).
There is an example project provided with my library.

## Proposal
I think it should be provided directly in Flutter, but an external package could be ok too.

## Problem
My library is not finished. I have many difficulties to create PhoneNumber validator. I need documentation about phone number formats for each country in the world.
I think I will add many validators for collections for example. Of course, I accept ideas if you have.

Thanks.

**Comment by pedromassangocode** [comment]
Hi @maxime-aubry 
This is a great feature but it can't be added into the core of Flutter because it would add too much complexity into the framework and making the code base hard to maintain this specific feature. If Flutter would implement this it probably would be an external package and not part of the framework itself.

You did a great job on coming with a package for that and now anyone who  want this feature can simply use your package.

Closing as this does not seems to be a valid proposal for the Flutter framework.
Thank you
