### ISSUE TITLE
Parsing Json

### ISSUE THREAD

**Issue by michael-shields** [flutter/flutter#65770]
REMOVED CONTENT as who ever is managing the site doesn't want fix any issues found.

**Comment by Abhishek01039** [comment]
Hi @michael-shields 
This platform is not meant for your personal code assistance.
please ask your question in https://flutter.dev/community
Thanks.

**Comment by michael-shields** [comment]
Sorry,
	I was reporting a bug, what is the purpose of this site then?  Confusing, I will retract any further involvement with this site.

Regards,

**Comment by iapicca** [comment]
@michael-shields 
#
1. your content isn't remove since github keep tracks of the edit, below is a quote of your post before content got "removed"

> Example below, the primary problem is in the second example where I need to assign the List to a variable to the '_tempList', how come? There is no reason to store the variable as its only used once here in the parsing phase. In the First example, this is how I naturally intended to use the json in code. Am I missing something?
> 
> ```dart
> // DOES NOT WORK? -- This is what I would like to do --
> Map<String,dynamic> json = jsonDecode(result.body);
> List _parsedList = json['someList'].map((l)=>SomeList(l)).toList(); // This doesn't work// This doesn't work
> List someList = List.from(_parsedList);
> 
> // DOES WORK -- This is what I need to do currently, the extra assignment to a variable??
> Map<String,dynamic> json = jsonDecode(result.body);
> var _tempList = json['someList'];
> List _parsedList = _tempList.map((l)=>SomeList(l)).toList(); // This doesn't work
> // E X T R A V A R I A B L E F O R N O R E A S O N
> List _parsedList = _tempList.map((l)=>SomeList(l)).toList();
> List someList = List.from(_parsedList);
> ```
#
2.  

> Sorry,
> 	I was reporting a bug, what is the purpose of this site then?  Confusing, I will retract any further involvement with this site.
> Regards,

@Abhishek01039 is correct,  the purpose of this "site" is to improve flutter with bug report  or feature requests,
for assistance for your personal code follow the last option in the [New Issue](https://github.com/flutter/flutter/issues/new/choose) menu.

The issue likely depends form your code or the API rather than with flutter itself,
(although it's hard to tell without detail of `SomeList()` in `.map`)
try running the code below on [dartpad](https://dartpad.dartlang.org/)

```dart
import 'dart:convert';

const String _json = '{"someList": ["Hello", "World"]}';

void main() =>  print(jsonDecode(_json)['someList'].toList().join(' '));
```
#
3. if there actually was a bug with [dart:convert](https://api.dart.dev/stable/2.9.3/dart-convert/dart-convert-library.html) the issue should be opened [here](https://github.com/dart-lang/convert/issues) and not on flutter's repo

**Comment by PixelToast** [comment]
@michael-shields
Sorry for the confusion, we interpreted the original question as general code help rather than a bug report.

If you have a reproducible example with the error message you receive I will be happy to re-open the issue.

Otherwise its always good to ask for help in [StackOverflow](https://stackoverflow.com/tags/flutter) and [Discord](https://discord.gg/N7Yshp4).
