### ISSUE TITLE
SharedPreferences sync get/set methods

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#65779]
At the moment, all prefs methods are async:
```dart
await prefs.setInt('counter', counter);
```
It is not very convenient. Consider creating sync versions of all the methods and deprecate the async API.
```dart
prefs.setIntSync('counter', counter);
```

**Comment by iapicca** [comment]
> Consider creating sync versions of all the methods and deprecate the async API.

I believe this issue is neither realistic nor desirable

1. AFAIK there's no way to communicate with a [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels) **synchronously**
2. I cannot conceive any compelling reason to deprecate an entire set of perfectly working API

you may want to consider [hive](https://github.com/hivedb/hive), much faster than [shared_preferences](https://pub.dev/packages/shared_preferences)
and since doesn't use any native code [[quote](https://github.com/hivedb/hive#usage)] 

> You can use Hive just like a map. It is not necessary to await Futures.

**Comment by PixelToast** [comment]
@subzero911 The `SharedPreferences` interface contains a cache that you both read and write to synchronously, you shouldn't need to wait for the `setInt` future to complete before being able to read that data back. To put it simply, this is already the current behavior and you can just ignore the return value.

**Comment by darshankawar** [comment]
@subzero911 deprecating the async api doesn't seem to be a realistic ask. Please look into suggestions made by @iapicca and @PixelToast and see if they work per your need.
I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen.
Thanks.
