### ISSUE TITLE
How to contribute to google_maps_flutter and google_maps_flutter_platform_interface at the same time ?

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#65788]
I made a PR on `google_maps_flutter`. However, `google_maps_flutter` depends on `google_maps_flutter_platform_interface` and my PR needed to modify both plugins.

So I changed `pubspec.yaml` as follow in `google_maps_flutter`

    dependencies:
      flutter:
        sdk: flutter
      flutter_plugin_android_lifecycle: ^1.0.0
      google_maps_flutter_platform_interface: # I changed this from ^1.0.4
        path: ../google_maps_flutter_platform_interface

Then I did the Pull Request but on of the checks says:

    * Don't depend on "google_maps_flutter_platform_interface" from the path source. Use the hosted source instead. For example:

I don't understand. How am I supposed to use the hosted plugin although I am modifying it

**Comment by pedromassangocode** [comment]
Hi @tolotrasamuel 
It seems you are asking for assistance. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on https://www.reddit.com/r/flutterhelp/

Please understand that GitHub issues is not for support on sending PRs into Flutter, you may get help by posting on https://discord.com/invite/N7Yshp4.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ditman** [comment]
@tolotrasamuel our tooling is not able to merge changes to multiple packages simultaneously, in order to contribute a change to google_maps_flutter that requires changes into google_maps_flutter_platform_interface, you'll need to have a PR to modify the platform_interface, get that merged and published, and then have another PR that modifies the plugin. (You can use this time to bump the minimal version required of the platform interface with the version you just published as well).

In my experience, it's been best to have one big PR with all the changes (like the one you already have), which is unpublishable *but* easy for people to download and test, and once that's reviewed, then create the two (or sometimes three) reviews that need to be merged in the right order, those should be approved quickly, given that the whole review work happened in the main (unpublishable) review.

Thanks!
