### ISSUE TITLE
change flutter run to support a toolable stream

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#6593]
We should update flutter run to support a toolable stream. This will better support the internal workflow. The commands supported will be a subset of the daemon protocol; we'll iterate on a design outside of this issue. The stream can either always be toolable (understand JSON commands and fire JSON events) or can opt-into toolability w/ the use of a cli flag (`--machine`).

/cc @danrubel

**Comment by mit-mit** [comment]
Dan, assigning to you. The is the key dependency to unblock the internal workflow in IJ.

**Comment by Hixie** [comment]
I thought this was what `flutter daemon` was for.

**Comment by danrubel** [comment]
As [Devon mentioned in the PR](https://github.com/flutter/flutter/pull/6645#issuecomment-257929701), we are [updating IJ to use `flutter run --machine` rather than `flutter daemon`](https://github.com/flutter/flutter-intellij/issues/401) to launch and interact with Flutter applications. Once that is complete, we can [remove launch functionality from `flutter daemon`](https://github.com/flutter/flutter/issues/6658).
