### ISSUE TITLE
Notification panel not showing up on Xiaomi devices

### ISSUE THREAD

**Issue by KhayyamA47** [flutter/flutter#65931]
![b23298cb-c80e-4e42-9889-8e43b2bb08d7](https://user-images.githubusercontent.com/54634944/93322930-f455db80-f824-11ea-8148-a263a3715cb9.jpeg)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by KhayyamA47** [comment]
I use local push notification and firebase messaging.In samsung s9 devices show notification panel when notification coming but Xiomi devices not show.Only app icon show status bar.

**Comment by darshankawar** [comment]
Hi @KhayyamA47,
This seems to be specific to notifications using Firebase and `flutter_local_notifications` which is 3rd party. For firebase messaging related issue, please consider opening this issue here : https://github.com/FirebaseExtended/flutterfire/issues.
Closing, as this isn't related to Flutter.
