### ISSUE TITLE
☂️ ReorderableListView updates

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#66080]
We have had numerous requests for new features and bug fixes related to the `ReorderableListView`. This issue will be used to track the main issues and describe our current plan for resolving them. We have an initial [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0) that summarizes the current features/bugs we would like to address in an update to the `ReorderableListView`. It is an incomplete design, but it will hopefully give you an idea of what we are thinking and how we might address these issues.

To summarize, here are the main issues we would like to address:

- [ ] Support for drag handles
- [ ] Configuring drag initiation (i.e single click on desktop, long press on mobile)
- [ ] Parity with ListView features:
   - [ ] `.builder` constructor
   - [ ] `.separated` constructor?
   - [ ] `reverse`, `primary`, `shrinkwrap`, `padding`, and `scrollPhysics` properties
- [ ] It is hard to embed in a `SliverList`
- [ ] Doesn’t work well inside a `RefreshIndicator`
- [ ] Item tooltips and popup menus are incorrectly positioned
- [ ] Lack of visual polish and some interactive jankiness

Please feel free to comment here or on the doc itself with any feedback about this as we are still in the early stages of design work for it.

Main related bugs:
- #25789
- #46805
- #42330
- #53059
- #36314
- #63709
- #63708

**Comment by TonyDowney** [comment]
The design doc mentions footers as a non-goal, but I disagree. Being able to wrap the list with a header and footer means the entire widget would have one scroll context, which solves some of the simplest use cases. I agree that it's somewhat beyond the scope, but ease of use should be a consideration too.

**Comment by pedromassangocode** [comment]
Labelling proposal and new feature since some of the issues mentioned also have those labels.

**Comment by pedez** [comment]
I'm not the most experienced of programmers, so pardon me if what I'm saying is nonsense, but it would be great to have a property that would be a function (a name like, onFinalListOrder) that would run once the user either left the page or the app where the reorderable list is.

The goal of the function would be to allow us to place a function there that would persist the list's new order to the database. Right now, I have no idea how to save the new list order (I even made a post on stackoverflow and didn't get any replies). Sorry if any of this is silly/nooby. Feel free to delete this if it's not helpful

**Comment by Ran73Cohen** [comment]
> 
> 
> I'm not the most experienced of programmers, so pardon me if what I'm saying is nonsense, but it would be great to have a property that would be a function (a name like, onFinalListOrder) that would run once the user either left the page or the app where the reorderable list is.
> 
> The goal of the function would be to allow us to place a function there that would persist the list's new order to the database. Right now, I have no idea how to save the new list order (I even made a post on stackoverflow and didn't get any replies). Sorry if any of this is silly/nooby. Feel free to delete this if it's not helpful

Its a bit off topic but...

You can wrap your widget (the page) with WillPopScope like so
`
Future<bool> yourExitMethod(){
//write code in here
}

return WillPopScope(
      onWillPop: () => yourExitMethod(),
      child: SomePage()`

return true if you want the scope to pop or false if you want to cancel it and stay in the page

**Comment by Kavantix** [comment]
The scrolling jank discussed in the design doc is probably related to my proposal: #64706

**Comment by philip-brink** [comment]
It would be very useful to provide the ability for drag handles at the `Draggable` and `LongPressDraggable` level rather than just the `ReorderableListView` level. This would allow a lot more flexibility when designing all types of draggable widgets.

**Comment by satvikpendem** [comment]
Here are the problems I've found with `ReorderableListView`:

## 1. The dragging up and dragging down tolerances are not correct.

When dragging up, it works correctly, as when the midpoint of the previous element is crossed, the two elements swap. However, when dragging down, you have to move the entire distance of the element being dragged and then the midpoint of the next element as well.

See this GIF and the code below:

![](https://user-images.githubusercontent.com/42670561/95088185-9ebc7280-06f0-11eb-85f1-49a12f6f1db5.gif)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static const colors = [Colors.red, Colors.green, Colors.blue];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: ReorderableListView(children: [
            for (var i = 0; i < 3; i += 1)
              Container(
                width: 100,
                height: 100.0,
                color: colors[i % colors.length],
                key: ValueKey(i),
              ),
          ], onReorder: (int oldValue, int newValue) {}),
        ),
      ),
    );
  }
}
```

This is because ReorderableListView uses an incorrect algorithm for checking whether two elements should swap. It only checks whether the **_top edge_** of the dragging element overlaps the midpoint of the next or previous one, when in reality it should be checking:

```dart
/// Moving down
/// If not the last box in the list
if (box.position < boxList.value.length - 1 &&
    box.end > positions[box.position + 1].midpoint) { ... }

/// Moving up
/// If not the first box in the list
else if (box.position > 0 &&
    box.start < positions[box.position - 1].midpoint) { ... }
```

That is to say, it should check first whether the element is moving up or down, and only then check whether the start or end of the box is greater than or less than the next or previous element to be swapped.

In contrast, I've been making my own implementation of RLV and here is how it works:

![](https://user-images.githubusercontent.com/42670561/95088537-15597000-06f1-11eb-98ac-c24f0245e791.gif)

Notice how it checks for overlap based on the direction it's dragging in, and how it still works properly even for elements that are smaller than the dragging element. I can't share the code currently as it's being used in another project but I can try to make a smaller example with it and share that code. I can notify this thread once that's done. This actually uses a Stack which is not that efficient for larger items 

## 2. No animation

It is true that the dragged over element will animate when swapped, but I would like some more customization that that. My implementation uses a `SpringSimulation` which is where you get that bouncy transition. Having an `Animation` value be able to be passed into RLV as an `onReorderAnimation` property or something like that would be nice.

As well, there is no animation when starting the drag, or ending it. I would expect some smooth transition for the dragging element but there is none. This seems to be an inherent limitation of `Draggable` and `DragTarget` actually, not necessarily related to RLV. However, having an `Animation` value be passed in as `onDragStartAnimation` and `onDragEndAnimation` would be good. You could combine this with the `onReorderAnimation` above somehow, such as a new class called `ReorderAnimations` that accepts these values. That way we can control the animations however we want.

## 3. Forced styling

I understand RLV is for Material apps but having a box shadow as a forced style with no way to get rid of it is quite annoying. As suggested in #53059 and my comment there specifically about RLV (https://github.com/flutter/flutter/issues/53059#issuecomment-611372492), we should try to decouple the UI (styling, animations, etc) from the UX (dragging and swapping behavior) of more widgets like RLV. I would have loved to use RLV instead of making my own implementation but unfortunately because I wanted my own styling and animations, I had to make my own. This shouldn't be the case simply because RLV ties the styling with the actual functionality of a swappable list.

---

Let me know if you would like more detail on any of these, I can provide it if needed.

**Comment by stephenhuey** [comment]
I took a look through here and also in the design doc and was curious if anything will be done to address [20573](https://github.com/flutter/flutter/issues/20573).  I'm aware that for improved performance on large lists I could switch to [flutter_reorderable_list](https://pub.dev/packages/flutter_reorderable_list) but it seems reasonable to expect large lists to be less laggy with ReorderableListView.

**Comment by AdiLaxman** [comment]
I have an app that heavily depends on this widget. 
Can you please provide an approximate timeline for this implementation to be available in the stable channel?
Also, can you please comment whether #20573 will be addressed or not?
Thank you.

**Comment by satvikpendem** [comment]
> Would really love to see this example, is it enough just to do into the source code and perform the edits you suggest?

@honne23 Sure you could modify the RLV source but there are quite a few things hard-coded in, and I didn't fully understand how it worked, so I made my own. Might just be better to start from a ListView implementation and modify that instead.

**Comment by welfvh** [comment]
![IMG_96F08F765F5F-1](https://user-images.githubusercontent.com/36489530/101495646-adc5d800-3960-11eb-97e3-e9e483f14cba.jpeg)
Something rather annoying is that when using multiple lists, RLVs will scroll within themselves, thus destroying the expected scrollability of the whole page. Plus, there's currently no way of reordering across two or more lists?

**Comment by pedromassangocode** [comment]
https://github.com/flutter/flutter/issues/72673 maybe a valid proposal as well.

**Comment by hlemcke** [comment]
@satvikpendem Could you please provide your modifications here?
I totally agree in having a proper tolerance handling in both directions. In addition I need to have the option to drop an item onto another one. Do you see a chance to integrate another hook function like `onDrop` which fires before or instead of `onReorder` when the dragged item is _dropped on top_ of the drag target (just before the target would move to the space left from the dragged item)?

**Comment by satvikpendem** [comment]
@hlemcke @honne23 You can run the example here: https://gitlab.com/pantheonlabs/products/artemis/frontend/-/blob/master/lib/examples/swap_list_example.dart

It has most of the code regarding the swap logic, but it also doesn't expose everything, you'll have to look in `util` for that. I use `flutter_hooks` so it might not make sense for someone who doesn't know hooks, but this is mainly for the spring transition animations on swap, not necessarily the swap logic itself.

Let me know if you have questions, it's not necessarily understandable at first glance, but if you want you can try using it.

**Comment by darrenaustin** [comment]
Thanks for all the great feedback folks! We have addressed a lot of the issues with the recent PRs: #74299 and #74697. With these in place you now have more options and control over the reorderable lists:

* **ReorderableListView** - A Material Design implementation of the reorderable list updated to use the new SliverRerorderableList internally. This should address a lot of the issues with performance and jankiness. There is also a new builder constructor `ReorderableListView.builder` similar to the `ListView.builder` constructor that will allow for better performance as the list items are only constructed when they are needed instead of requiring everything be built upfront. We also added most of the `ScrollView` parameters that were missing (like `physics`, `primary`, etc).

* **ReorderableList** - a lower level flexible widget that allows the user to interactively move items around the list. It is design-language agnostic and lives in the widgets package.
* **SliverReorderableList** - a SliverList version of the `ReorderableList`, also in the widgets package.

The `ReorderableList` and `SliverReorderableList` allow you to customize how the drag operation starts. This is be done by wrapping each item in a drag listener that will tell the list to start dragging. We have provided two such listeners for the common cases:

* **ReorderableDragStartListener** which triggers the drag from a single pointer down event (useful for wrapping just a drag handle instead of the whole item).
* **ReorderableDelayedDragStartListener** which triggers after a long press.

Or you can subclass `ReorderableDragStartListener` and build your own listener.

One of these methods is required by `ReorderableList` and `SliverReorderableList`, but the Material `ReorderableListView` will automatically wrap each child in a delayed listener for mobile and adds a default 'dragHandle' on top of each item by default on desktops. These can be turned off if you want to build your own.

We have also provided a `proxyDecorator` callback that will allow you to wrap the dragging item with whatever decoration (drop shadow, border, etc) while it is being dragged.

While these don't address all the issues raised, hopefully they address the main pain points of the previous implementation and will make it easier for you to build what you need. We can follow this up with more enhancements in the future.

I'm going to close this tracking bug with these PRs. If you have specific issues or features that weren't addressed please file separate issues for them. Thx.
