### ISSUE TITLE
Ignore const constructor modifier for debug builds

### ISSUE THREAD

**Issue by s0nerik** [flutter/flutter#66233]
## Use case

I have a strict lint setup that enforces `const` constructors where possible ([prefer_const_constructors](https://dart-lang.github.io/linter/lints/prefer_const_constructors.html), [prefer_const_constructors_in_immutables](https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html)). Most of the widgets in my project end up having `const` constructors. This is great for performance in release builds, but not so great in debug mode when I often get `Const class cannot remove fields` hot reload error.

As soon as I receive that error, a hot reload is no longer possible and I have to fully rebuild my app. During the 8 hours coding session, it can happen 20+ times and it's very annoying.

## Proposal

I'd love to have an option to ignore `const` constructor modifiers globally during debug build (re)compilation.

I'm ready to give up even 50% of debug build performance in order to remove that annoying error.

**Comment by knaeckeKami** [comment]
Hm, this would cause different behaviour in debug in release builds, especially when using `==` or `identical`.

**Comment by mraleph** [comment]
I think ignoring `const` is pretty dodgy due to semantic changes it implies (though we have widget transformer that kinda violates these things, but it feels wrong to expand this even further).

Instead I think it is worth asking a question: why can't constant objects loose fields on hot reload? The only real problem I see is that removing fields from constant objects can cause two (or more) different constant objects to collapse into a single object (in a cascading fashion). Though it might not be straightforward to implement this efficiently, it is still possible to support this. It probably requires a fix-point pass over canonical tables first to compute which instances collapsed and then adding mapping for those into become mappings. Ryan might have some thoughts about it /cc @rmacnak-google

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/issues/40442
