### ISSUE TITLE
InteractiveViewer web zoomscrollview OnInteractionUpdate details.scale does not provide useful information

### ISSUE THREAD

**Issue by TerrenceAddison** [flutter/flutter#66270]
When using interactiveViewer for mobile devices, the onInteractionUpdate details.scale value is:
_The scale implied by the average distance between the pointers in contact with the screen._
This means the value will be the resultant scale when zooming in / out. The log as below:
'
I/flutter ( 6070): 1.0109037994120005
I/flutter ( 6070): 1.019937329440527
I/flutter ( 6070): 1.0332409875340767
I/flutter ( 6070): 1.0387293803040731
I/flutter ( 6070): 1.0442768304011694
I/flutter ( 6070): 3.0482381843787585
I/flutter ( 6070): 3.094021567223479
I/flutter ( 6070): 3.590798193364565
I/flutter ( 6070): 3.595535799126826
'
This value is approximately the current scale of the zoom.

Previously when doing the PR for zoomscroll not calling onInteractionUpdate, it was decided to set the details.scale value to be the scaleChange. The scaleChange value is the amount of scroll by the zoom wheel (1 - (scroll / child height)). This means that in general if you scroll per scrollwheel tick, the value of scaleChange is constant at the same value.

Log as below:
Zoom in
`
1.1358695652173914
1.1358695652173914
1.1358695652173914
1.1358695652173914
`
Zoom out
`
0.8641304347826086
0.8641304347826086
0.8641304347826086
0.8641304347826086
`
This value seems to not be that useful, and to even get the current scale from this value is too difficult because the calculation is done within the interactiveViewer matrix functions. I propose to change the value of details.scale for mouseScrollWheel to be the currentScale replace it with:

`      
final double currentScale = _transformationController.value.getMaxScaleOnAxis();
`

I feel that this is much more useful and more fitting with the name and definition of "scale" property  in which the value is assigned to.

**Comment by TerrenceAddison** [comment]
@justinmc Sorry for spontaneously tagging you! But I'd like to propose this again with you after further trials and consideration. Hope to hear your opinion on this!

**Comment by justinmc** [comment]
No worries!  I'm still really invested in trying to make InteractiveViewer useful for everyone.

Here's my counterargument for this idea, but let me know what you think.  My approach for event data given to users of InteractiveViewer has been to just be consistent with the rest of the framework. So because the scale property of ScaleUpdateDetails elsewhere contains just the current change in scale, I did the same thing for onInteractionUpdate.  It is important that users can easily get the values that they need, but in this case they can use `_transformationController.value.getMaxScaleOnAxis()` themselves to get the current overall scale.

Am I missing a case where the user might want to calculate the final scale after some change?  I did make some small changes to onInteractionUpdate in https://github.com/flutter/flutter/pull/66065.

Another thing I've considered is exposing the internal methods that are used to scale and translate.  That might be a separate issue though.

**Comment by TerrenceAddison** [comment]
I'm a bit unfamiliar about this but how would I be able to get the `_transformationController.value.getMaxScaleOnAxis()` while I'm using the interactiveviewer widget?
For the case regarding user might want to calculate the final scale, is it any different from getMaxScaleOnAxis? they should be the same right?
I've been testing again on the ScaleUpdateDetails on mobile devices and it seems it is the change from the current zoom scale, not the base 100% zoom(e.g if I zoom in again when I'm zoomed in at around 500%, it will give me a smaller number instead). 
I think a possible solution is to also expose the current overall scale!

**Comment by justinmc** [comment]
If you pass your own TransformationController, then you can use it to get the scale:

```dart
InteractiveViewer(
  transformationController: myTransformationController,
  onInteractionUpdate: (ScaleUpdateDetails details) {
    print('scale after this interaction update is ${myTransformationController.value.getMaxScaleOnAxis()}');
  },
)
```

In that example in onInteractionUpdate, the printed value will be the value after the interaction update.

Does that cover your use case?  I'm not sure how the details.scale numbers relate to zoom level currently, but I guess that would make sense.

**Comment by TerrenceAddison** [comment]
Yes, that covers my use case thank you very much. I think this way it is fine to leave the scale value as the scaleChange since both value are also accessible thank you!

**Comment by justinmc** [comment]
No problem!
