### ISSUE TITLE
HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by Antonimo** [flutter/flutter#66437]
a follow up to this issue: https://github.com/flutter/flutter/issues/59878

Ive created a test project: https://github.com/Antonimo/ps_test

When running the project, this is the result:

![image](https://user-images.githubusercontent.com/612902/93998325-0a234d80-fd9d-11ea-9876-afdd44803c74.png)

expected: no HandshakeExceptions

**Comment by pedromassangocode** [comment]
Hi @Antonimo 
From what I can see, the issue may be related to the http package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http).

Please see if this can help you fix the issue: 
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by Antonimo** [comment]
This is not a certificate-verify issue, and its not reproducible within a dart environment, its only reproducible in flutter environment. 
So the http team will say let the flutter guys investigate, what then?
