### ISSUE TITLE
Unable to connect to LAN http server

### ISSUE THREAD

**Issue by enyo** [flutter/flutter#66471]
## Steps to Reproduce

I created a simple test http request inside my app:

```
final uri = 'http://10.0.0.148';
var response = await http.get(uri);
```
It works fine on the Apple Simulator but fails when debugging on an actual iPhone with:

```
flutter: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 10.0.0.148, port = 80
```

I have made sure that the URL works on my iPhone though (opening it in Safari). The iPhone is on the same network as my server.

I have tested this with Flutter `1.20.0` stable and `1.22.0-12.1.pre`

<details>
 <summary><code>$ flutter analyze</code></summary>

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Analyzing mobile...                                                     
No issues found! (ran in 6.2s)
```

</details>

<details>
  <summary><code>$ flutter doctor -v</code></summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-AT)
    • Flutter version 1.22.0-12.1.pre at /Users/enyo/local/flutter
    • Framework revision 8b3760638a (8 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/enyo/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (2 available)            
    • Destroyer (mobile)                  • 60ca238f17cb69a3d45f4708dc55c47e4e8b532e • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 438088D6-6D89-4BF3-A34A-D05F0257B9F5     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Destroyer is busy: Copying cache files from device. Xcode will continue when Destroyer is finished. (code -10)

! Doctor found issues in 1 category.
```

</details>

**Comment by enyo** [comment]
I've used `upnpc` to forward an external port to my local server, and am now using my external IP address to connect. That's working but it's a pretty ugly workaround.

**Comment by TahaTesser** [comment]
Hi @enyo 
From what I can see, the issue is related to  `http` plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by natebosch** [comment]
> From what I can see, the issue is related to `http` plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).

@TahaTesser - The `http` and `web_socket_channel` packages are _extremely_ unlikely to be the root causes for problems like this. The usage of `package:http` does _not_ suggest that users should file issues there.

This looks like an issue with the environment or with networking permissions. See https://github.com/flutter/website/issues/3592

**Comment by TahaTesser** [comment]
Hi @natebosch 
I've seen a bunch of issues like this, your explanation is really helpful, 
I will make sure to forward such issues to the issue you linked for flutter/website
Appreciate your feedback


It's the issue link from the [pub](https://pub.dev/packages/http) page for `http`, that's the reason I add the link. Please let me know which is the correct place http issues 
Thank you

**Comment by natebosch** [comment]
> Please let me know which is the correct place http issues

There are a few places.

If it's a question like "this works in dev but not a prod build", "this works on an emulator but not a device", or "I can make https but not http requests" and similar, the question is best answered by the flutter team (or stack overflow) since it it is likely related to things like hardware or app permissions.

If it's a question like "This works on flutter mobile but not flutter web" it's likely something like a CORS issue and stack overflow is the best resource. Pointing users to the browser console for errors is the best response for web specific problems.

If it's a question like "I need to support a newer TLS version" or "I get an error about failing to parse a header value with invalid characters", it's mostly likely something related to the Dart SDK which implements the mechanics of making the HTTP requests.

`package:http` is a thin shim on top of functionality from the SDK. If the users doesn't have a stack trace that points _specifically_ to `package:http` then it's most likely unrelated.

The _vast_ majority of issues in this space seem to be user mistakes and stack overflow is a good place to point in almost all cases.

**Comment by TahaTesser** [comment]
@natebosch 
This is really helpful for my team, thanks for sharing this.
