### ISSUE TITLE
remove launch functionality from flutter daemon

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#6658]
Once  [IJ to uses `flutter run --machine` rather than `flutter daemon`](https://github.com/flutter/flutter-intellij/issues/401) to launch and interact with Flutter applications, we can remove launch functionality from `flutter daemon`.

**Comment by DanTup** [comment]
I'm trying to add Flutter support to Dart Code and using the daemon for launching seems like a better fit to me (comments [here](https://github.com/Dart-Code/Dart-Code/issues/198#issuecomment-304368463)). I'd be curious to know why you think it's better to separate these and have a deamon that doesn't support launching?

**Comment by Hixie** [comment]
@danrubel @devoncarew @DanTup What's the status of this?

**Comment by DanTup** [comment]
My previous comments is somewhat void - I implemented using `flutter run` (since the app is launched from a completely different place to where we have the daemon). So, removing it is fine from my side (though I don't know about IntelliJ/AndroidStudio).

Slight tangent - we should document which commands are available in `flutter run`. I've recently been trying to use `daemon.shutdown` in there to solve an issue and it's accepted but doesn't do what it should. It's unclear whether `daemon.xxx` commands should work in there or not. I understood that `flutter run --machine` was a subset of `flutter daemon` but if launch is removed from daemon this definitely won't be the case.

**Comment by danrubel** [comment]
Nothing new on from my end as I've been focused on CFE / Analyzer integration for the past year.

**Comment by Hixie** [comment]
> Slight tangent - we should document which commands are available

Yes, we should document this whole API in detail. Feel free to start (e.g. create a page on our wiki), put in what you know, anything is better than nothing and it'll evolve over time to become more accurate and detailed.

**Comment by devoncarew** [comment]
Note that the protocol is documented here: https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode - we should just make sure that that page is up-to-date and accurate.

**Comment by DanTup** [comment]
We do have #10546 open about the docs. If launch is being removed (it's not clear to me from the above if that's the case) it might be a good time to update, since `run --machine` was a somewhat undocumented-subset of `daemon` but with this change that won't be the case, so it may be worth separating them (I'm not sure after this change what the overlap will be).

**Comment by Hixie** [comment]
Oh I totally forgot about those docs. Excellent.

Feel free to edit those docs as you see fit. Any improvement is welcome.

**Comment by DanTup** [comment]
I'm not sure which commands are intended to be available in which mode (`daemon`/`run --machine`). For example `daemon.shutdown` is in the `daemon` section not `app`, but if you send it to a `flutter run --machine` it doesn't error, but also doesn't behave correctly. I *think* it should work, but it could equally be expected that only `app.` commands work here.

I don't mind updating the docs if someone can clarify exactly what should be supported in which mode(s).

**Comment by DanTup** [comment]
PR to remove the `app` domain from `flutter daemon` here:

https://github.com/flutter/flutter/pull/18873
