### ISSUE TITLE
[web:a11y] implement the "selected" semantic property

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#66673]
Internal: b/258949931

Using the `Semantics` widget and setting the `selected` property to true does not currently cause any sort of additional announcement in flutter web. This gets read out as "selected" on iOS and Android. There is likely some sort of mechanism in ARIA that can be utilized for this.

**Comment by rami-a** [comment]
cc @nturgut

**Comment by pedromassangocode** [comment]
Any reproducible steps?

**Comment by rami-a** [comment]
@nturgut and I confirmed that this is currently the case. You can reproduce by creating a simple widget such as this, and then trying to use a screen reader with it on flutter web. It will end up reading out as "text, button". Compared to iOS/android where it will read "selected, text, button".

```
Semantics(
  selected: true,
  button: true,
  child: Center(
    child: Text(
      'Text',
    ),
  ),
)
```

**Comment by xster** [comment]
Setting to P2 to reflect b/246006912

**Comment by yjbanov** [comment]
Dropping back to P4. A workaround confirmed by the customer is to use `toggled` instead of `selected`.

**Comment by yjbanov** [comment]
Received another report for this issue b/258949931.

**Comment by yjbanov** [comment]
We're drowning in flutter triage bot traffic. Resetting the triage bot timer.

**Comment by yjbanov** [comment]
This will have to be a multi-step process (unless the repos merge before then, and it could take fewer PRs):

- [ ] Introduce a `hasSelectedState` flag in the engine. The flag will initially be a noop. The goal of this step is to adjust the downstream code to mere presence of the new flag, rather than its functionality. For example, there are tests that enumerate all flags and verify their values.
- [ ] Roll the new flag into the framework and beyond, fixing code as it lands downstream.
- [ ] Change all widgets in the framework that use `isSelected` to also supply the `hasSelectedState`.
- [ ] Implement the engine functionality. In the web case, when `hasSelectedState` is set, the engine will set `aria-selected` to "true" or "false" according to the value of the `isSelected` flag. If `hasSelectedState` is unset, then `isSelected` is ignored, and `aria-selected` attribute is not added to the DOM tree.
- [ ] Let the new functionality roll downstream again, fixing code as necessary.
