### ISSUE TITLE
HitTestBehavior.translucent not work [Channel beta, 1.20.2]

### ISSUE THREAD

**Issue by zhou67832033** [flutter/flutter#66952]
In the following example the bottom GestureDetector doesn’t activate, even though the top one’s behaviour is set to translucent. How can I make it work?

[Flutter Channel beta, 1.20.2]

```
      Stack(
        fit: StackFit.expand,
        children: [
          GestureDetector(
            child: Container(
              color: Colors.purple,
            ),
            onTap: () => print('bottom'),
          ),
          GestureDetector(
            child: Container(
              color: Colors.green,
            ),
            onTap: () => print('top'),
            behavior: HitTestBehavior.translucent,
          ),
        ],
      ),
```

**Comment by darshankawar** [comment]
@zhou67832033 
Since you have set `fit` to `expand` and have `Containers` wrapped with `GestureDetector`, the Container will span across entire width and height, unless given custom dimensions. In your case, provide `height` to both containers and then see that both the `Containers` are displayed and then you are able to tap on both.

```
I/flutter (11648): bottom
I/flutter (11648): bottom
I/flutter (11648): bottom
I/flutter (11648): top
I/flutter (11648): top
I/flutter (11648): top
I/flutter (11648): bottom
I/flutter (11648): bottom
I/flutter (11648): top
I/flutter (11648): bottom
I/flutter (11648): bottom
I/flutter (11648): bottom
```

```
GestureDetector(
                child: Container(
                  height: 50,
                  color: Colors.purple,
                ),
                onTap: () => print('bottom'),
              ),
              GestureDetector(
                child: Container(
                  height: 5,
                  color: Colors.green,
                ),
```

Also please see https://flutter.dev/community for resources, you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
