### ISSUE TITLE
Flutter does not provide prebuilt ARM64 binaries for Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6715]
At least not to my knowledge.

**Comment by tvolkert** [comment]
Per @chinmaygarde:

> I suspect there will be some complexity in the tooling w.r.t the AOT snapshotter since the i386 based snapshotter for armv7a wont work when creating snapshots for aarch64 (we could just the same snapshotter that is used for iOS but obviously that is absent on linux hosts).

**Comment by eseidelGoogle** [comment]
This will be required by the Play Store by August 2019:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

I expect we'll have it long before then however.

**Comment by eseidelGoogle** [comment]
@chinmaygarde @cbracken @mravn-google @jason-simmons do we have a high-level guesstimate of what work will be required to make this work?

**Comment by chinmaygarde** [comment]
* On the engine side there is nothing to do. `./flutter/tools/gn --android --android-cpu=arm64` should build the appropriate engine.
  * Estimate: See if it already works and we haven't broken it :)
* The buildbot would have to build and upload the assets to the cloud.
  * Estimate: Maybe a few mins to cook up the patch to build and upload the new artifacts.
* The Flutter tools currently assume that Android uses the `armv7` engine and iOS the `aarch64` engine. Because of this, it defaults to using the `i386` `gen_snapshot` for Android targets and the `x86_64` `gen_snapshot` for iOS when generating the AOT snapshot. This assumption would no longer hold and the tools would need to select the correct `gen_snapshot` depending on the Android target CPU. I believe `flutter build flx` already has a `--flavor` flag that we can use to communicate the intent to the Android build scripts as well. We already support `x86_64` Android target so `arm64` should be more of the same kind of variant selection.
  * Estimate: I am not too familiar with the Flutter tooling side but it can't be more than a few days work at most for someone unfamiliar with that codebase.

**Comment by mravn-google** [comment]
On Android, the `--flavor` option is currently used to specify Android [product flavor](https://developer.android.com/studio/build/build-variants.html#product-flavors) (e.g. demo version vs full version of the app), not [target architecture](https://developer.android.com/studio/build/configure-apk-splits.html).

We could repurpose it of course, but we risk confusing Android developers.

**Comment by a-siva** [comment]
We have two options -
```
flutter build aot
flutter build apk and
flutter build flx
```
build both the 32 bit and 64 bit flavors always

or

we wire the --target-platform which is currently only supported in 'flutter build aot' to accept android-arm64. This same option would also have to be plumbed into 'flutter build flx' and 'flutter build apk' for consistency.

**Comment by Hixie** [comment]
What would `flutter run` build?

**Comment by Hixie** [comment]
I think it makes sense to have a `--target-platform` (with some useful default).

`flutter build flx` will presumably go away soon.

Ideally `flutter install` would call `flutter build` in the same way that `flutter run` does, picking the right default, so it's only when you actually ship the final app that you have to worry about this.

What does the play store expect? Binaries for every architecture supported?

**Comment by cbracken** [comment]
> I think it makes sense to have a --target-platform (with some useful default).

Agreed. Potentially also useful for iOS, depending on how we implement armv7 support, once that makes it higher in the priority list.

**Comment by eseidelGoogle** [comment]
We had a client need this sooner than expected.  @jason-simmons took this on and is almost done.

**Comment by cbracken** [comment]
@jason-simmons is this safe to close?

**Comment by Hixie** [comment]
@jason-simmons says this is fixed!
