### ISSUE TITLE
Consider Theme.of()! and other related topics

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#67163]
With the null safety migration, we've added a lot of `!`s near `of` methods. This issue is to track what we should do about it.

cc @goderbauer @HansMuller @gspencergoog @a14n

**Comment by goderbauer** [comment]
For `Theme.of` it can only return null when the `shadowThemeOnly` is set to true. My suggestion: Splitting this up into two methods:

* `Theme.of(BuildContect context)` never returns null. This is the most common usage.
* `Theme.shadowThemeOf(BuildContext context)` may return null.

**Comment by HansMuller** [comment]
Outside of the ~half dozen internal uses of this API, locally there's just one. Maybe we should remove it, rather than perpetuating it? It appears to just be a hack to get around the fact that new routes don't see the same inherited widgets that the caller who's built the route does (it's a hack because it only deals with the special case of Theme). The InheritedTheme.wrap method is supposed to be a more general way of dealing with this issue. https://api.flutter.dev/flutter/widgets/InheritedTheme/wrap.html

**Comment by tvolkert** [comment]
If most callers are going to have to migrate their `Theme.of(context)` calls to be `Theme.of(context)!` after we laucnh null safety, should we make this change before the null safety launch? (in which case it should probably be something higher than P5)

**Comment by gspencergoog** [comment]
@tvolkert I agree, probably should be higher priority.  I already have a design doc for doing this, among others: https://flutter.dev/go/eliminating-nullok-paramters (I know, I'm fixing the name typo in the go link).

**Comment by gspencergoog** [comment]
Oh, actually, I just realized that Theme.of doesn't actually have a `nullOk` parameter. I mean, it's a similar problem, so maybe it should be linked, but I was just trying to address the `nullOk` problem.

**Comment by HansMuller** [comment]
Per https://github.com/flutter/flutter/issues/67163#issuecomment-703743767 we don't need a nullable Theme.of(), we need to fix the one code path that uses `Theme.shadowThemeOf(BuildContext context)`.
