### ISSUE TITLE
open default audio recorder

### ISSUE THREAD

**Issue by flashiran1** [flutter/flutter#67173]
hi I need open default audio recorder for record and get path recorded please add this Feature

**Comment by iapicca** [comment]
@flashiran1 
without this being an endorsement 
there are 3rd party plugins that offer the feature you are looking for
[flutter_audio_recorder](https://pub.dev/packages/flutter_audio_recorder)
[audio_recorder](https://pub.dev/packages/audio_recorder)

although I'm not sure what you mean by "default", 
I'm quite sure that most platforms do not have a default audio recorder

**Comment by flashiran1** [comment]
@iapicca 
this plugins needed permission  android.permission.RECORD_AUDIO but I do not want to give this permission 
And I only need this theme on Android and iOS

**Comment by iapicca** [comment]
I'm not sure to understand what are you trying to achieve

if your issue is a `feature request` can you please describe it more in details 
the specific use case in particular

if instead you are looking for assistance for your app 
I suggest to ask a question on `StackOverflow` 
as indicated by the option `I want help writing my application` in the [new issues menu](https://github.com/flutter/flutter/issues/new/choose)
