### ISSUE TITLE
[gen_l10n] Document messages with translations for supported locales

### ISSUE THREAD

**Issue by szotp** [flutter/flutter#67206]
Consider this localization file:
```json
{
    "@@locale": "en",
    "@@last_modified": "2020-10-03T09:49:55.929624",
    "helloThere": "Hello there {name}",
    "@helloThere": {
        "placeholders": {
            "name": {}
        },
        "description": "Lorem ipsum...",
        "type": "text"
    },
}
```

It will generate this property:
```dart
// Lorem ipsum...
String heloThere(Object arg0);
```

But it would be much nicer if it also added documentation comment with translations:
```dart
/// en: Hello there {name}
/// Lorem ipsum...
/// de: !!! translation missing !!!
/// pl: No elo {name}
String heloThere(Object arg0);
```
This way, IDE will guide you as your are writing widgets, and you can now easily find missing translations with search functions.

@shihaohong Does this sound good? If yes, I could try to implement this and submit PR

Related ticket: https://github.com/flutter/flutter/issues/41437

**Comment by szotp** [comment]
Also, current `@comment` logic does not handle new lines. On one hand, it's a bug, on the other hand, I can use it to insert the documentation I want here.

**Comment by christopherfujino** [comment]
@shihaohong could you take a look?

**Comment by shihaohong** [comment]
I like the idea in concept, but applications that support a larger number of translations would have a massive number of comments. For example, the gallery supports dozens of locales and the comments for each message would be extremely long if we wanted to document every single translation for each message.

To clarify -- Is the issue here difficulty in figuring which translations are missing? There's an option called `--untranslated-messages-file` that helps list out the messages that are missing translations and for which locales.

**Comment by szotp** [comment]
Good point. For me the most common case is two supported languages (english + developer's native language), so putting all translations there made sense.

So instead we could put only template language + info for missing translations + maybe some docs about placeholders.

This issue is not really about untranslated messages, I just mentioned it as it seemed nice to have. Actual issue is about having clear information about given localization string without looking up the .arb file or generated code. When writing widgets it's not always clear which text will be used.

BTW, I'm aware of `--untranslated-messages-file` it's printed every time I'm running the app, but I don't really know which command to use. `flutter pub get --untranslated-messages-file x.txt` doesn't work.

**Comment by shihaohong** [comment]
Actually, that's a bug and has been printing incorrectly. I just submitted https://github.com/flutter/flutter/pull/68553 which should fix that issue.

I _believe_ the issue you're facing here is that you're using `--untranslated-messages-file` correctly, but since you have all translations completed, the file is just not generating. I've made an adjustment in the same PR that causes the tool to generate an empty JSON instead of not doing anything in the event that all messages for every locale have existing translations.

**Comment by szotp** [comment]
Cool. Then this ticket is mostly about adding some comment docs, could be as simple as:

```dart
/// en: Hello there {name}
String helloThere(Object arg0);
```

**Comment by shihaohong** [comment]
I'll take a look into what we can do to make the docs helpful without cluttering it with too much noise. Maybe I'll start with the simple string getters first as a start and iterate to address the more complex ones, like methods with placeholders.

**Comment by shihaohong** [comment]
@szotp I created a PR that adds a new comment line with the message value in the template arb locale. Take a look and provide any feedback if you have any!
