### ISSUE TITLE
[image_picker] crash when opening gallery more than once at ios 14

### ISSUE THREAD

**Issue by t0n1zz** [flutter/flutter#67263]
**Configuration:**
- image_picker: ^0.6.7+11
- Flutter 1.22.0 • channel stable

**Issue:**

1. Open gallery using this code

```
 final pickedImage = await picker.getImage(
      source: ImageSource.gallery,
      maxWidth: widget.containerWidth,
  );
```
2. select the image from gallery
3. reopen gallery using the first code again 
4. the app crash

**Comment by surveshoeb** [comment]
@t0n1zz have you solved this issue?

**Comment by t0n1zz** [comment]
no, i just closed it because there is already been asked here
[https://github.com/flutter/flutter/issues/66322](https://github.com/flutter/flutter/issues/66322)

**Comment by YouSour** [comment]
i face this problem too , any solution ? @t0n1zz

**Comment by AdamJonsson** [comment]
Just found a temporary fix by waiting a small duration before getting the image:

```dart
    await Future.delayed(Duration(milliseconds: 500));
    var pickedFile = await picker.getImage(
      source: source,
      imageQuality: ImageSource.gallery,
      maxWidth: 750,
    );
```

I think the issue is triggered when touching the screen while the native platform gallery becomes visible. Waiting half a second prevents this. Not the prettiest solution, but seems to work until the Flutter team fixes the main issue.
