### ISSUE TITLE
Flutter app turns white after installing it on IOS 14

### ISSUE THREAD

**Issue by Buscuit-Dev** [flutter/flutter#67280]
Hello, I am having an issue where whenever i run the app on My iPhone running iOS 14 it works if I press launch the app using Xcode but whenever i close the app and try to open again on the device it gets past the launch screen fast but then sits on a white screen forever. Any help would be appreciated.

**Comment by TahaTesser** [comment]
Hi @Buscuit-Dev 
on iOS 14, if you're running in debug mode, you can't launch the app from the home screen. Please use profile or release mode 
![Image from iOS](https://user-images.githubusercontent.com/48603081/95091717-6b0b3800-0744-11eb-8c14-7712bd11d062.png)

Instead of a white screen, you should see this warning screen if you're on the latest `master`
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
