### ISSUE TITLE
TextField and TextFormField prefixText and suffixText spaces

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#67392]
TextField and TextFormField have no prefixText and suffixText spaces by default.
it could be nice to add some spaces between prefixText, Input area and suffixText.

**Comment by sidrao2006** [comment]
Hello @zs-dima , could you please mention the use case for it.

Thank you!

**Comment by zs-dima** [comment]
```dart
TextFormField(
  decoration: const InputDecoration(prefixText: 'PREFIX', suffixText: 'SUFFIX'),
  initialValue: 'SOME TEXT',
* * *
),
```

**Comment by zs-dima** [comment]
![screenshot](https://user-images.githubusercontent.com/25195453/95177979-879c8400-07c7-11eb-89a0-a637804c2f00.jpg)

**Comment by zs-dima** [comment]
![screenshot](https://user-images.githubusercontent.com/25195453/95178462-21fcc780-07c8-11eb-9a91-581f3730ceb7.jpg)

**Comment by Dasunx** [comment]
```
TextFormField(
          decoration: const InputDecoration(
            prefix: Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Text("PREFIX"),
            ),
            suffix: Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Text("SUFFIX"),
            ),
          ),
          initialValue: '123 456789 123',
          readOnly: true,
        )
```

you can use "Padding" to add spaces for now

**Comment by zs-dima** [comment]
@Dasunx I mean 'prefixText' and 'suffixText' - but NOT 'prefix' and 'suffix'

**Comment by darshankawar** [comment]
@zs-dima 
Although `TextField` and `TextFormField` doesn't have those properties, you may leverage the `prefixIcon` and `suffixIcon` properties, that accepts all widgets, so you may want to try these properties and see if they serve your purpose.
Thanks.

**Comment by zs-dima** [comment]
@darshankawar  I mean 'prefixText' and 'suffixText' with current issue. I know other properties works fine but is not about case I posted.

**Comment by zs-dima** [comment]
And if 'prefixText' and 'suffixText' should not work then what about remove them?

**Comment by darshankawar** [comment]
@zs-dima 
If I understand your issue correctly, you are looking to add space after `prefixText` and before `suffixText` so that the middle value is displayed correctly.
you probably need to implement a workaround using `decoration` property.

Also, please see https://flutter.dev/community for resources, you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
