### ISSUE TITLE
Benchmark dashboard page is failing

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#67457]
The performance benchmark dashboard (https://flutter-dashboard.appspot.com/benchmarks.html) is rendering a blank page

**Comment by godofredoc** [comment]
Web compilers were updated yesterday https://github.com/flutter/cocoon/pull/964 and that change was released today in the morning. I'll move the production version to yesterday's to see if that fixes the problem temporarily as we find and fix the issue.

**Comment by godofredoc** [comment]
Issue has been mitigated and we'll continue trying to get a fix

**Comment by keyonghan** [comment]
From doc: https://pub.dev/packages/build_web_compilers/versions/2.10.0#configuration, option `compiler: dart2js` is needed for version `2.10.0` which we are using now.

However checked that the doc also suggests option `compiler: dart2js` for our earlier version `2.7.2`: https://pub.dev/packages/build_web_compilers/versions/2.7.2#configuration

Did a local test build by adding the option, it passes locally, and the benchmark dashboard rendered. Will confirm it works in production.

**Comment by keyonghan** [comment]
Though succeeded locally, but still failed in cloud build.

**Comment by keyonghan** [comment]
Based on conversations in https://github.com/flutter/flutter/issues/67319, cocoon cloud build failure is due to an upstream dart issue residing in flutter `dev` channel which cocoon cloud build relies on. 

@christopherfujino will help roll a new version to `dev` hopefully tomorrow, and that will move cloud build back on track.

To mitigate similar issues in the future, I will separate the `flutter` image build from the cocoon build (changing it to bi-monthly).

**Comment by keyonghan** [comment]
Now flutter image is being build every month, and current version passes cocoon builds. 
With benchmark dashboard back on online, closing the issue.
