### ISSUE TITLE
onbackground message working

### ISSUE THREAD

**Issue by kittugithubpandey** [flutter/flutter#67520]
I want to launch a screen in onbackgroundmessage in flutter in firebase messaging

**Comment by Calamity210** [comment]
Please see https://flutter.dev/community for resources, you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

**Comment by TahaTesser** [comment]
Hi @kittugithubpandey 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by Calamity210** [comment]
I wouldn't personally advise to open an issue unless you are actually facing something. If this is just a request for help, search around in the other communities

**Comment by TahaTesser** [comment]
Hi @Calamity210 
From the looks of it, sure I agree but on Flutterfire, when creating they can provide necessary details in the template if it is a bug and it could be determined by the flutterfire team if it is a legit issue or not. 

@kittugithubpandey 
If you're looking for assistance,  please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Thank you
