### ISSUE TITLE
InitialStartupTime windows_chrome_dev_mode regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#67534]
https://flutter-flutter-perf.skia.org/e/?begin=1601769723&end=1601925724&keys=X22646a9f94d2899ca71f9c3c645e4192&num_commits=50&request_type=1&xbaroffset=21780

First seen at commit https://github.com/flutter/flutter/pull/67150, although I don't see how one could be linked to the other. Could this be a lab issue?

Starting with the `tool` label, since that's the commit where this started; please retriage as appropriate.

cc @jonahwilliams the originator of the PR where it occurred, and @godofredoc in case it's a lab issue.

**Comment by jonahwilliams** [comment]
Tool commit doesn't really touch any web code, and that is a pretty huge jump.

**Comment by kf6gpe** [comment]
@yjbanov could this be something in the web site of things?

**Comment by liyuqian** [comment]
CC @zanderso to see if this is worth some more investigations, and if so what priority it has. @jonahwilliams (the author of the regression PR #67150, and the original test PR #33629) believes that #67150 has 0 chance to affect that perf test. If this is an infra issue, we'd like to confirm if this regression is reproducible locally using the same machine with and without #67150.

**Comment by zanderso** [comment]
I looked at the logs on a recent commit for this benchmark. It looks like a large download might be getting included in the benchmark time:
```
2020-10-12T14:41:28.266986: stdout: [   +6 ms] Downloading Web SDK...
2020-10-12T14:42:20.307765: stdout: [+52048 ms] Downloading Web SDK... (completed in 52.0s)
```
If that isn't supposed to be included in the result, then either the [`Stopwatch` start](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/web_dev_mode_tests.dart#L58) should go later, or the benchmark should precache artifacts, if possible.

Since I think there isn't actually a regression here, I'll drop the priority, but assign @jonahwilliams to take a look at the benchmark.

**Comment by kf6gpe** [comment]
Based on Zach's comment that it's likely not a regression, I'm going to drop the regression tag, too.

**Comment by jonahwilliams** [comment]
Sorry, I've been incredibly busy the last week with the devicelab flakes

**Comment by kf6gpe** [comment]
https://flutter-flutter-perf.skia.org/e/?begin=1601570934&end=1603147925&keys=X22646a9f94d2899ca71f9c3c645e4192&requestType=0&xbaroffset=21780 shows it's recovered; closing.
