### ISSUE TITLE
FlutterDriver for web in the Cirrus CI is not hermetic in flutter/flutter

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#67569]
Context: https://github.com/flutter/flutter/issues/67560

## Problem 1: Cirrus Docker

Cirrus gets Chrome from Docker. Whenever Docker updates it also updates Chrome. Because Docker updates happen outside the PR cycle a Chrome upgrade that breaks the build breaks random PRs.

I can't tell if LUCI has the same problem, but it might.

## Problem 2: web_installers driver versions

web_installers [enumerates all browser-driver versions](https://github.com/flutter/web_installers/blob/58081a8b2fbf234e9c8da86fce28adfefe3c2093/packages/web_drivers/driver_version.yaml#L4). When we upgrade to a new version of Chrome and web_installers can't pick a chromerdriver for it, the build breaks.

## Problem 3: web_installers dependency

On top of that we fetch web_installers [from Github straight to HEAD](https://github.com/flutter/flutter/blob/5e4c86d124e8795e738aecd4288892fd2d95ca00/.cirrus.yml#L189). So every CI run can get a different version. We need to lock it.

The same is happening [in the plugins repo](https://github.com/flutter/plugins/blob/8c9908ea731ee588e636fe2fae8f0687202b77cd/.cirrus.yml#L55).

/cc @nturgut

**Comment by nturgut** [comment]
Problem 1: No LUCI Chrome versions are hermetic. You would probably remember, we documented how they can be changed before: https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md#upgrade-browser-version

Problem2: we knew from the very first day. That's why we were always updating web_installers' chrome version (you can check the history for the repo). We discussed this issue a lot back in the day, the problem is there is no link we can download the suggested driver version for a chrome driver. It's only written on the chrome driver download's page: https://chromedriver.chromium.org/downloads

Problem 3: I think we can resolve this issue. The reason I kept them was actually problem 2. This happened before in plugins.  Cirrus updated on plugins repo, tests immediately broke since the chrome driver was missing. When we only fetch of top of the head it's only one PR fix. Since LUCI felt tests are hermetic for example, we didn't need this trick for the engine repo. Engine repo always uses a SHA.

I'm suggesting to drop the priority of this issue since other than Cirrus which is under deprecation there is not an actionable item. What do you think? @yjbanov

**Comment by nturgut** [comment]
Let's discuss this issue in more detail later. As I replied in the previous comments most of these are known issues.

I'm dropping the priority.

**Comment by yjbanov** [comment]
We moved most of the tests to LUCI. The only smoke test that runs on Cirrus hasn't been problematic, so I'm closing this.
