### ISSUE TITLE
[web] Accessibility Support

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#67611]
I have made this site using Flutter for my little brother and it looks good and he likes it. The problem is that when I tried to use VoiceOver it did not work as expected. It reads just two things on screen and not in the correct location and does not scroll when I use the three-finger gesture during VoiceOver.

Site link for interested people: [https://abdulmalik.alkhalaf.dev/](https://abdulmalik.alkhalaf.dev/)

Video showing the problem on an iPhone 6: [https://streamable.com/aghffk#/](https://streamable.com/aghffk#/)

**Comment by darshankawar** [comment]
@YazeedAlKhalaf 
Accessibility support on web is not yet 100%. See some of these open issues related to it.
https://github.com/flutter/flutter/issues/66383
https://github.com/flutter/flutter/issues/52106
https://github.com/flutter/flutter/issues/45198

I'd suggest you follow-up in above issues instead of creating a new issues, because once these are fixed, probably your issue will be fixed too.
Closing this. If you disagree, write in comments and I'll reopen.
Thanks.
