### ISSUE TITLE
flutter_localizations doesn't initialize en_US, corrupting existing DateFormat variables

### ISSUE THREAD

**Issue by knuesel** [flutter/flutter#67644]
Without initialization, the `intl` package allows to use (only) the `en_US` locale, so one can do:

```dart
final DateFormat _dateFormat = DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US');
```
However, `flutter_localizations` [initializes](https://github.com/flutter/flutter/blob/82ff246156c23bdd8cc4ac0e043c3f72ee10b87f/packages/flutter_localizations/lib/src/utils/date_localizations.dart#L43) the `intl` symbols for many locales, including `en` but **not** `en_US`. This can put `intl` in a corrupted state: new `DateFormat` variables created for `en_US` will automatically be converted to `en`, but existing variables with `en_US` locale become unusable, causing crashes when used.

This causes a crash in `firebase_auth`: https://github.com/FirebaseExtended/flutterfire/issues/3374 . For a full analysis of that crash, see https://github.com/dart-lang/intl/issues/315#issuecomment-703085167

It's not clear if the bug is in `intl` or `flutter_localizations`, but it seems odd that `flutter_localizations` doesn't initialize `en_US`?

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by TahaTesser** [comment]
Hi @knuesel 
Thank you for filing the issue, I can reproduce the issue 

### `intl` sample with `flutter_localizations`
**logs**
```
flutter: en
```
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';
import 'package:intl/intl.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: Home(),
      locale: Locale('za', 'CH'),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(
        fallback: Locale('en', 'US'),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final DateFormat _dateFormat =
        DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US');

    return Scaffold(
      appBar: AppBar(
        title: Text(I18n.of(context).title),
      ),
      body: Center(
        child: Container(
          child: Text(I18n.of(context).greetTo('World!')),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          print(_dateFormat.locale);
        },
      ),
    );
  }
}

```

</details> 

### `intl` sample without `flutter_localizations`

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final DateFormat _dateFormat =
      DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {
            print(_dateFormat.locale);
          }),
    );
  }
}

```

</details> 

**logs**
```
flutter: en_US
```

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final DateFormat _dateFormat =
      DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {
            print(_dateFormat.locale);
          }),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.254, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.254 at /Users/tahatesser/Code/flutter_master
    • Framework revision 0d8696f655 (10 hours ago), 2020-10-09 01:12:02 -0400
    • Engine revision 349889833c
    • Dart version 2.11.0 (build 2.11.0-203.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • FFCA7F6E-C704-436E-B356-D287FCB4D714 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2
      x86_64
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```

</details>

**Comment by knuesel** [comment]
@TahaTesser you're welcome! There's also an MWE for the crash at https://github.com/knuesel/dateformat_bug.

**Comment by shihaohong** [comment]
## Findings and Explanation
I just looked into this and it is a matter of when the `DateFormat` is initialized. The class [has some logic to discover errors and use fallbacks if the exact locale match cannot be found](https://github.com/dart-lang/intl/blob/master/lib/src/intl/date_format.dart#L266). In the [example above](https://github.com/dart-lang/intl/issues/315#issue-713617859): 

1. If `DateFormat` is initialized before Flutter loads (in `main()` but before `runApp()`), its date i18n patterns and symbols [uses en_US because its patterns and symbols are defined as a fallback](https://github.com/dart-lang/intl/blob/master/lib/src/date_format_internal.dart#L39) if locale data has not been initialized. Note that `_locale` here is set as `en_US`.
2. On the other hand, after `runApp` is called with a MaterialApp set up with localizations, the set of date patterns and symbols Flutter uses are loaded, which does not generate the patterns and symbols explicitly for `en_US` since our scripts assume `en` and `en_US` are the same. So, when you try to call `format.parse()` the second time, it fails because it tries to reach for patterns and symbols for `en_US`, even though they are not defined when we loaded Flutter's i18n date patterns and symbols.
3. When `DateFormat` _is not_ instantiated before `runApp` is called (in the original example, comment out the first `format.parse()` in `main()`, leaving the second `format.parse()`), the app works just fine because `DateFormat`'s constructor tries to infer which locale to use if an exact match is not found. In this case, it results in the DateFormat instance using `en`, since it does not detect `en_US` as a valid locale, but then uses `en`, which was defined in Flutter's set of date patterns and symbols, as the fallback. See the [DateFormat constructor](https://github.com/dart-lang/intl/blob/master/lib/src/intl/date_format.dart#L266) and the [Intl.verifiedLocale logic for using an alternative locale value](https://github.com/dart-lang/intl/blob/master/lib/src/intl_helpers.dart#L148).

## Proposed Solution
We can just include `en_US` as a required set of date symbols and patterns in the Flutter framework.
