### ISSUE TITLE
Make any widget statefull

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#67880]
Hi,
Why many flutter widgets are stateless?
Why we need ValueListenableBulder?

Is it possible make all flutter widgets statefull?
How?
Implementation ValueListenableBulder logic in every widget of flutter.
F.e.
 Container widget can change its state if f.e it's height, or it's color is changed .

Class Container extends Some class{
If (container width !=old container width)
Refresh the state of this component (Container)
... Other if else's to update the state }

I see native views are statefull  but in flutter we need to write boilprate codes to change the state any widget

**Comment by ayRatul** [comment]
This is dumb. We NEED stateless widget to have fine controll of what it's rebuilt and what is not. There is already a ton of libraries to manage the building proccess of deep nested stateless widgets, like provider, hooks, bloc, rxdart and many more. The logic that you specified is the same logic that inheritedWidget uses. and InheritedModel allows us to have really fine controll of what it's rebuilt and what not.

**Comment by II11II** [comment]
How ios swift ui and android jet pack technology achieved not to use  setState logic, or how any view are statefull there?

**Comment by ayRatul** [comment]
Flutte takes a reactive approach. Which means you update a value and call setState and the widget rebuilds with the new value.

i come from java. Where in vanilla you woulr find each component with findViewById then update the value one component at a time. This is manual state and more than half the code is just locating components and assigning values.

Even android studio is making their own version of state and stateless plugins because it's just so efficient

**Comment by II11II** [comment]
Th
