### ISSUE TITLE
CupertinoTextField default font differs from that of UITextField's default.

### ISSUE THREAD

**Issue by DanielEdrisian** [flutter/flutter#67953]
The UIKit textfield's font seems to be a bit narrower. Two examples:

<img width="424" alt="Screen Shot 2020-10-12 at 1 04 16 PM" src="https://user-images.githubusercontent.com/11810973/95786195-f8421580-0c8b-11eb-8a45-179debdffecb.png">

<img width="318" alt="Screen Shot 2020-10-12 at 1 07 33 PM" src="https://user-images.githubusercontent.com/11810973/95786191-f710e880-0c8b-11eb-93ba-b5eb62dd3ed3.png">

**Comment by justinmc** [comment]
CC @MitchellGoodwin maybe something to look at in the comparison tool, not sure what's different.

**Comment by MitchellGoodwin** [comment]
Compared to the text in both CupertinoSearchField and CupertinoTextField, the font weight of a SwiftUI text input does seem to be different slightly (or I've gone crazy from staring at pixels too much). Here's an S side by side for comparison.
<img width="56" alt="Screen Shot 2022-10-20 at 4 16 06 PM" src="https://user-images.githubusercontent.com/58190796/197077317-6faacd44-4dd7-4c0c-bae4-e0453a98a524.png">
The Flutter text is on the left, the SwiftUi is on the right. The tricky thing is that the text's font weight seems to be in between our `FontWeight.w400` and our `FontWeight.w500`. Maybe by about 20%, as far as my eyeballs can tell. In order to match native, seems like we'd have to either: 
* Adjust the font weight enums to match perfectly.
* Do something tricky to the default font to get it to match, which the developer would likely not be able to match fully with a `style` overwrite.
Both of these feel like overkill and a small breaking change that may break too many goldens compared to the benefit they'd bring.

However the padding of both CupertinoSearchField and CupertinoTextField can be adjusted to match native a little better, which causes the text to overlap a little more naturally.

CupertinoSearchField defaults before:
<img width="409" alt="Screen Shot 2022-10-20 at 4 15 10 PM" src="https://user-images.githubusercontent.com/58190796/197078560-166a85da-1768-4c46-9c79-ce3111b1e888.png">

And after adjusting:
<img width="410" alt="Screen Shot 2022-10-20 at 4 14 56 PM" src="https://user-images.githubusercontent.com/58190796/197078586-a2ae9358-98ed-49c0-971f-ca5c00e251ae.png">

It's a little harder to see with the CupertinoTextField, but here's the SwiftUi text field overlayed the Flutter CupertinoTextField at 50% opacity. Before:
<img width="402" alt="Screen Shot 2022-10-20 at 4 40 56 PM" src="https://user-images.githubusercontent.com/58190796/197079323-49747d91-3760-4b39-88e3-f1afefc7508c.png">

After
<img width="400" alt="Screen Shot 2022-10-20 at 4 40 38 PM" src="https://user-images.githubusercontent.com/58190796/197079345-2af0e31c-0d20-4012-a706-8ac019e788d1.png">

I think for now just making the adjustments to the padding would be fine? And we can see if there's interest in making the small adjustment to the font size?

**Comment by justinmc** [comment]
Thanks for doing that detailed analysis!  The padding change seems like a major win to me...

**Comment by MitchellGoodwin** [comment]
Partially addressed by #113958 adjusting the padding. If there's enough interest in getting the font width for the weights 100% aligned, we can reopen this issue, but I'm going to close this as that would be a fairly substantial change for a lot of apps for seemingly not a lot of interest.

**Comment by MitchellGoodwin** [comment]
Reopened from merge failure

**Comment by MitchellGoodwin** [comment]
Addressed by #115164
