### ISSUE TITLE
Transient engine presubmit failures due to inability to fetch dart tags due to rate limiting (HTTP 429).

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#67966]
An example of such a failure is [here](https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine/15684?). The specific error is:
```
fatal: unable to access 'https://dart.googlesource.com/a/sdk.git/': The requested URL returned error: 429
[W git.go:289] Transient error string identified in STDERR: "fatal: unable to access 'https://dart.googlesource.com/a/sdk.git/': The requested URL returned error: 429\n"
```

**Comment by godofredoc** [comment]
We can stop fetching dart tags.

**Comment by chinmaygarde** [comment]
Is there an ability to relax the rate limits for requests from our bots?

**Comment by godofredoc** [comment]
This problem is being generated most likely from git commands hidden in the scripts. Those git commands are using the system git  which makes un-authenticated requests hitting the default quota.

We can increase quota for our bots service accounts but that won't solve the problem. From the dashboard we are using less that 1 third of the allocated quota at peak times.

**Comment by christopherfujino** [comment]
https://flutter-review.googlesource.com/c/recipes/+/7620 will stop fetching dart tags.

**Comment by christopherfujino** [comment]
Closing this after https://flutter-review.googlesource.com/c/recipes/+/7620. If there are additional 429 errors, those are being tracked at https://github.com/flutter/flutter/issues/67661.
