### ISSUE TITLE
Scenario tests don't exit after crashing

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#68033]
See: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/9808?

**Comment by zanderso** [comment]
Marking P2 since this looks like it is chewing up a lot of infra resources and for visibility.

**Comment by dnfield** [comment]
We should reduce the overall time allowed for the bots. They shouldn't be allowed to run for 2.5 hours.

It's not clear to me where the crash is - it looks like the test harness is still running but stuck?

**Comment by zanderso** [comment]
/cc @godofredoc and adding infra label for bot timeout.

@cyanglaz yes on presubmit. Note the shiny new 'team: presubmit flakes' label =)

**Comment by dnfield** [comment]
We could also add a timeout on the step itself I believe.  @godofredoc WDYT? I would probably rather just have fewer individual timeouts though.

In this case, it looks to me like XCTest/xcodebuild have just hung. The process does not appear to be crashing. We shouldn't let it go this long, but again I think the root problem here is that the bots are allowed to run for so long.

**Comment by godofredoc** [comment]
I'll create a CL to have a max 1 hour execution time.

**Comment by chinmaygarde** [comment]
We may be hitting the same issue here as in the gtest harenss where tripping an assertion on a Dart VM managed thread does not take down the process because of the VM hijacking some signal handlers. In the gtest harness, we we have a per test case timeoout of 30s. We might need to do something similar here. Or, more precisely, figure out how to make VM no hijack signal handlers so we get the desired expected behavior. Lowering the priority of this issue because the timeout has been applied on the bot but will followup with the DartVM folks about the right fix for this.

**Comment by godofredoc** [comment]
In the scenarios case this is happening because we are running the script to build and test and we are killing the emulator after without a defer_results block which means if the test/build fails we are not killing the emulator. To fix it we can add ```api.step.defer_results():``` to this context https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/scenarios.py;l=101?q=scenarios.py&ss=flutter

**Comment by zanderso** [comment]
@godofredoc are you doing that or do we need to find someone to do that?

**Comment by godofredoc** [comment]
I can send a CL for that during the day.

**Comment by chinmaygarde** [comment]
This issue is still being reported:
* https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/11167

**Comment by zanderso** [comment]
I believe this has not reoccurred recently, so I am closing this as stale.
