### ISSUE TITLE
Flutter should improve Date and Time inputs

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68047]
The Date and Time input options are very limited, Flutter should provide a more comprehensive set of Widgets for this end.

For example, there's `InputDatePickerFormField` for dates, but not for time. There isn't an input widget that can automatically open a Calendar picker or time picker for easiness, if the user don't want to type the date or time.

**Comment by gnprice** [comment]
This issue is not useful, because it's too broad and non-specific to be actionable. See here:
https://github.com/flutter/flutter/wiki/Triage#what-makes-an-issue-actionable

There are many specific issues in the tracker for the date and time pickers:
https://github.com/flutter/flutter/labels/f:%20date%2Ftime%20picker
If there are specific problems or desired features not covered by those existing issues, then filing specific new issues for those would be helpful.

**Comment by feinstein** [comment]
Hi Greg, as you can see in the history, this issue was used as a reference for a PR over 2y ago, so it's not relevant anymore, specially with the new Material widgets for time and calendar.
