### ISSUE TITLE
Filter or Order Suggestions Accounting to Type on Intellisense Popup

### ISSUE THREAD

**Issue by EmreSURK** [flutter/flutter#68474]
Both on VSCode AndroidStudio autocomplete popup suggest unrelated things.
If we can filter or order suggestions according to accepted type that would increase development speed.

For example;
Column
 -- crossAxisAlignment -> Popup should only contain (or order to top at least) CrossAxisAlignment type, and the functions and the classes that can return CrossAxisAlignment type.
 

What happens now;

<img width="618" alt="unrelatedAutoComplate" src="https://user-images.githubusercontent.com/9450430/96430303-aad52380-120a-11eb-9f69-d48eacfac8a7.png">

What is expected;

<img width="602" alt="expextedSuggestions" src="https://user-images.githubusercontent.com/9450430/96431641-7a8e8480-120c-11eb-9223-2744f58564d8.png">

That situation may be happened because of Dart Language Server, if so, we may need to carry that issue to Dart's page.

Thanks.

**Comment by sidrao2006** [comment]
Hey @,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is a feature request for flutter extensions and plugins, please close this issue and open it [here for VSCode](https://github.com/dart-code/dart-code/issues) and [here for IntelliJ and Android Studio](https://github.com/flutter/flutter-intellij/issues) instead.

Thanks

**Comment by pedromassangocode** [comment]
This is definitely not related to Flutter, please open this issue in the Flutter plugin for the editors in their related repository.
