### ISSUE TITLE
bodyText1 and bodyText2 are the same font size

### ISSUE THREAD

**Issue by kaarens93** [flutter/flutter#68495]
There is no discernible difference between `bodyText1` and `bodyText2`. They look to be the same exact style (fontSize and letterSpacing). `bodyText2` should be size 16 with 0.5 spacing

**Comment by darshankawar** [comment]
@kaarens93 
According to 2018 [specs](https://api.flutter.dev/flutter/material/TextTheme-class.html), the `bodyText1` has size 16 and spacing 0.5. `bodyText2` has size 14 and spacing 0.25.
Are you not seeing the font size per the specs ?

**Comment by kaarens93** [comment]
Yes I know, I note the specs in my original comment. The issue is the current style does not reflect the specs.

**Comment by darshankawar** [comment]
@kaarens93 
Tested this on latest stable and I see the font size for both text styles properly.

![68495](https://user-images.githubusercontent.com/67046386/96679617-a38c5200-1391-11eb-929e-099ce3390ebd.png)

<details>
<summary>code sample</summary>

```
return MaterialApp(
      theme: ThemeData(
        textTheme: TextTheme(
          bodyText1: TextStyle(),
          bodyText2: TextStyle()
        ),
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('This is Body text 1', style: Theme.of(context).textTheme.bodyText1),
              Text('This is Body text 2', style: Theme.of(context).textTheme.bodyText2)
            ],
          )
        )
      ),
    );
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

Can you share your code or a screenshot of what you are seeing when you use these textstyles ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Antzy** [comment]
![image](https://user-images.githubusercontent.com/8206319/120914350-63c57100-c6bb-11eb-8af3-b88e2c87fdd4.png)

```
<Widget>[
  Text(
    'This is bodyText1',
    style: Theme.of(context).textTheme.bodyText1,
  ),
  Text(
    'This is bodyText2',
    style: Theme.of(context).textTheme.bodyText2,
  ),
  Text(
    'This is bodyText1 (specs)',
    style: TextStyle(
      fontFamily: 'roboto',
      fontWeight: FontWeight.w400,
      fontSize: 16,
      letterSpacing: 0.5,
    ),
  ),
  Text(
    'This is bodyText2 (specs)',
    style: TextStyle(
      fontFamily: 'roboto',
      fontWeight: FontWeight.w400,
      fontSize: 14,
      letterSpacing: 0.25,
    ),
  ),
]
```
            
Using default theme, this is the comparison between what fonts have been implemented by Flutter vs what the specs says they should be. @darshankawar screenshot also shows the same output.
Compared to [specs here](https://api.flutter.dev/flutter/material/TextTheme-class.html):

1. bodyText1 font size is same as bodyText2 whereas specs mention they should be 16 and 14 respectively.
2. The line spacing is the same for both instead of 0.5 and 0.25.
3. bodyText1 seems to have medium(FontWeight.w500) instead of regular(FontWeight.w400)

I've been overriding Flutter default font theme to fix these discrepancies. This test has been done on the latest stable flutter version 2.2.1

**Comment by Antzy** [comment]
I was facing the same problem. Even screenshot by @darshankawar shows that the font size is same for both instead of being 16 for bodyText1 and 14 for bodyText2, as per specs here: https://api.flutter.dev/flutter/material/TextTheme-class.html. Also bodyText has medium font weight instead of regular and line spacing is incorrect.
Then reading further in the shared specs link, it mentions that for backwards compatibility, flutter uses 2014 specs instead of the 2018 specs (which is completely counter-intuitive for new users). For anyone in the same boat as me, to use the latest 2018 specs:
```
MaterialApp(
  theme: ThemeData(
    typography: Typography.material2018(),
  ),
)
```
