### ISSUE TITLE
Profile build of hello world does not launch with --sound-null-safety

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68561]
command:

```
flutter run  --sound-null-safety --enable-experiment=non-nullable --profile
```

Result:

```
E/flutter (18201): [ERROR:flutter/runtime/dart_isolate.cc(228)] CreateDartIsolateGroup failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-dwarf_stack_traces_mode no-causal_async_stacks lazy_async_stacks no-lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts" no-code-comments arm64-sysv null-safety' but the VM has 'release no-dwarf_stack_traces_mode no-causal_async_stacks lazy_async_stacks no-lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts" no-code-comments arm64-sysv no-null-safety'
```

release and debug works fine.

**Comment by chinmaygarde** [comment]
@a-siva: "snapshot requires ... `null-safety` ... but the VM has ... `no-null-safety`." indicates that the snapshot is incorrectly built right? But, I am not sure how this can happen because the isolate can be launched in either mode depending on the isolate flags we set (by introspecting the snapshot itself).

I'll try to debug this as I am not able to reproduce this in profile runtime mode in the engine native test harness.

**Comment by a-siva** [comment]
It appears that the snapshot was built with the --null-safety string but the isolate is starting in no-null-safety mode, this isolate could be the service isolate, we should check how the service isolate is started.

**Comment by chinmaygarde** [comment]
The engine doesn't initiate the launch of the service isolate. Instead, the VM gives the engine a callback in response to the launch of the root isolate. In the callback, the isolate flags of the parent are passed in which are used (unmodified) to create the new isolate.

**Comment by chinmaygarde** [comment]
@jonahwilliams: Are the outstanding changes on ToT? I am unable to run the Hello World application with the command you used because the default of complaints that packages don't fully support null-safety.

[`dart pub outdated --mode=null-safety`](https://gist.github.com/chinmaygarde/7b466776a9d24ebde0cf8e7258735ed7) result.

In the meantime, I'm debugging this in the engine test harness to dump service isolate launch flags.

**Comment by jason-simmons** [comment]
@chinmaygarde Try changing the hello_world package SDK constraint (https://github.com/flutter/flutter/blob/master/examples/hello_world/pubspec.yaml#L5) to:
`sdk: ">=2.11.0-213.0.dev <2.12.0"`

**Comment by chinmaygarde** [comment]
So, the isolate flags [don't seem to be inherited](https://github.com/dart-lang/sdk/blob/043bebcd02c42eb38502494b3feee2cdcfbc681f/runtime/vm/service_isolate.cc#L352). But then, I am not sure how this works in `debug` mode since the procedure is the same. Also, since the flags are not inherited, I can't stash the original flags anywhere. Will chat with @a-siva about how this is meant to work.
