### ISSUE TITLE
Some widgets' nullOk parameters are inconsistently applied.

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#68637]
The `Actions` widget has a number of static methods with a `nullOk` parameter, which can be used to enable or disable the throwing of errors when the caller's requested object was not found.

Turns out, this parameter is only considered when asserts are enabled. This feels a little iffy to me, as the documentation makes no mention of how the contract can change depending on environment.

**Request**: Improve docs (and maybe the name of the param, since it's sort of a debug only thing), or alternatively normalize behavior between asserts-enabled and disabled builds.

Affected methods:
* `Actions.find`
* `Actions.of`
* `Actions.handler`
* `Actions.invoke`

Thanks!

@gspencergoog

**Comment by gspencergoog** [comment]
The name of the parameter is consistent across many different similar static methods, not just `Actions`, and has the same behavior there (e.g. `MediaQuery.of`, `Focus.of`, `Localizations.localeOf`, etc.). And yes, it only applies to builds with assertions on, but that was always its intent.

I agree that the behavior should be mentioned more explicitly in the docs.

**Comment by shyndman** [comment]
I took a look at all of those, and it appears they are designed to throw regardless (although `Localizations.localeOf` might throw an NPE as opposed to a well-formed `FlutterError`).

**Comment by gspencergoog** [comment]
Ahh, I see what you mean.  OK, I can see making those throw a `FlutterError` on a non-assert build.

We seem to actually be quite inconsistent with our methods that take `nullOk` as a parameter, perhaps we should try and normalize that across the framework.

**Comment by shyndman** [comment]
Couldn't hurt. :)

Thanks!

**Comment by gspencergoog** [comment]
I'm converting this issue over to cover all the static methods that take a `nullOk` parameter.

We have a bunch of static member functions that have a `nullOk` argument to them, but we're really inconsistent with how we apply it.  Sometimes it will return null in some circumstances even if `nullOk` is false (e.g. `CupertinoDynamicColor.resolve()`), sometimes it only works when asserts are enabled (e.g. `Actions.find`), and other times it throws a `FlutterError` in release mode (e.g. `MediaQuery.of()`). Sometimes I think the checks are assert-only because of performance, though, so we can't just make them all throw FlutterError all the time.  At the least, we should probably update the API docs for each one that describes what behavior is expected.

**Comment by shyndman** [comment]
Thanks Greg. 

When the time comes, I'd love to be CC'd on that PR if you get a chance.

**Comment by gspencergoog** [comment]
Sure, will do.

**Comment by gspencergoog** [comment]
Related: https://github.com/flutter/flutter/issues/67163

**Comment by gspencergoog** [comment]
Here's a design doc for doing this: https://flutter.dev/go/eliminating-nullok-paramters (I know, I'm fixing the name typo in the go link).

**Comment by gspencergoog** [comment]
FYI, in discussions about this, @Hixie was of the opinion (and I agree) that eventually the `FlutteError` exceptions here should be thrown only from inside of asserts, since we eventually want to remove debug messages from release builds for size reasons (and because they're not really actionable there anyhow).

**Comment by shyndman** [comment]
Makes sense. Would exceptions without messages be thrown in the non-assert case?

**Comment by gspencergoog** [comment]
@shyndman Yes, and I added wording to that effect in the docs.

**Comment by gspencergoog** [comment]
This is all done, except for `Localizations.localeOf`, since a client (flutter_svg) is still using it. Once https://github.com/dnfield/flutter_svg/pull/443 lands, and then we remove the nullOk from `Localizations.localeOf`, this issue can be closed.

**Comment by shyndman** [comment]
Thanks!

It's one of those things where a few people will never realize the thanks they owe — the bug they didn't have to track down. :)

**Comment by goderbauer** [comment]
There's one more nullOK param remaining after all changes linked from this bug are submitted: https://master-api.flutter.dev/flutter/widgets/Actions/invoke.html

**Comment by gspencergoog** [comment]
I'll fix the `Actions.invoke` `nullOk` before closing.

**Comment by shyndman** [comment]
Thanks Greg
