### ISSUE TITLE
TextAlign is missing Justify

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6865]
Our engine supports it:
https://github.com/flutter/engine/blob/6c5315c3a1d72ee2aae520e05c1ebf0f6794ae0e/sky/engine/core/rendering/style/RenderStyleConstants.h#L153

We just don't expose it to Dart:
https://docs.flutter.io/flutter/dart-ui/TextAlign-class.html

@olostan ran into this.

**Comment by Khordad36** [comment]
it didn't work in right to left languages.

**Comment by eseidelGoogle** [comment]
@Khordad36 would you be willing to file a new bug?  I'd like to make sure we understand and can fix the issues you're seeing.  Thank you!

**Comment by Khordad36** [comment]
@eseidelGoogle thanks for your attention!
I submit this issue. #30986

**Comment by 3bua7m3d** [comment]
I have a problem with Justify with Arabic, where the lines with numbers have a defect, as well as the footnote number when uploading it, the numbers in one line will be flipped so that if (1) (2) (3) becomes like this (3
![WhatsApp Image 2021-03-19 at 6 00 53 PM (1)](https://user-images.githubusercontent.com/54246027/111801714-406dff80-88de-11eb-8bf2-fabffb47e2c9.jpeg)
![WhatsApp Image 2021-03-19 at 6 00 53 PM](https://user-images.githubusercontent.com/54246027/111801719-4237c300-88de-11eb-8bbe-d95a36d8fbd2.jpeg)

) (2) (1)
