### ISSUE TITLE
Adding Kurdish Central to official Flutter (RTL ckb)

### ISSUE THREAD

**Issue by msurchy** [flutter/flutter#68689]
Hello everyone,
Demand for mobile apps is heavily increasing in Kurdistan region of Iraq which uses Central Kurdish "RTL". The official language name is Central Kurdish with language code (ku, ckb (Central Kurdish Branch)). 

In React Native the language is added and it is working properly. However we would like to develop our apps using Flutter and Dart but without an official support of the language it is taking us much more time to fix issues related to RTL direction and we use workaround to bypass language code issue. 

What are requirements to add Central Kurdish with language code CKB to official flutter?

- React Native has no issue adding to it. 
- Central Kurdish is officially Supported by Google (Google Search and Translate)
- Official language of Microsoft Windows 
- Supported in Translator.bing 

We would like to add Central Kurdish to Flutter officially.
Any help where to start is appreciated!

**Comment by iapicca** [comment]
please note that, while being subject of this [issue](https://github.com/flutter/flutter/issues/57216),
a [3rd party repository ](https://github.com/HawkarShwany/kurdish_localization) has been provided [here](https://github.com/flutter/flutter/issues/57216#issuecomment-630849101)

**Comment by darshankawar** [comment]
@msurchy 
Also see these comments to implement the said language in your app. 

https://github.com/flutter/flutter/issues/35103#issuecomment-505913672

https://github.com/flutter/flutter/issues/35103#issuecomment-536661741

Your best bet is to add the new language manually or use the above referred plugin.

I am going ahead and closing this, since above links should be enough for you to get started. If you disagree, write in comments and I'll reopen.
Thanks.
