### ISSUE TITLE
[Feature Request] 希望Flutter能支持iOS iPad随手写功能

### ISSUE THREAD

**Issue by changleibox** [flutter/flutter#68764]
## Use case

产品经理想让我们用Flutter开发的应用支持iPad的随手写功能；

**Comment by SeasonLeee** [comment]
@changleibox Hello, 请问你是在提新功能建议吗？

建议你最好详细表达一下，并且在open issue的时候选择'Feature Request'.

然后如果你希望你的问题能够更准确的有人帮上忙的话，最好详细描述清楚。

另外，你可以看下`GestureDetector`这个Widget的文档，你可能会找到你想要的：
https://api.flutter.dev/flutter/widgets/GestureDetector-class.html

So, to those who wonder what happen in here, the author [probably] want a feature request, which is enable certain ability on iPad, which I don't quite understand what it was even in Chinese and hoping he/she will provide further detail on what it was...

Thanks

**Comment by changleibox** [comment]
> @changleibox您好，请问你是在提新功能建议吗？
> 
> 建议你最好详细表达一下，并在open issue的时候选择“ Feature Request”。
> 
> 然后如果你希望你的问题能够更准确的有人帮上忙的话，最好详细描述清楚。
> 
> 另外，你可以看下`GestureDetector`这个小工具的文档，你可能会找到你想要的：[https](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) : //api.flutter.dev/flutter/widgets/GestureDetector-class.html
> [](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html)
> 
> 因此，对于那些想知道这里发生了什么的人来说，作者[可能]想要一个功能请求，该请求可以在iPad上启用某些功能，我什至不甚了解中文，并希望他/她将提供进一步的功能。这是什么细节...
> 
> 谢谢

你好，我是需要一个新功能，在iPad上用手写，随手写功能输入文本，谢谢

**Comment by tion126** [comment]
Scribble

**Comment by pedromassangocode** [comment]
Using Google Translate since I don't understand the author’s language.

嗨 @changleibox
我看到有一个未解决的问题 (https://github.com/flutter/flutter/issues/38135) 解决了您描述的情况。
请继续解决该问题，我将关闭当前的副本。
如果您不同意，请在评论中写下来，我将重新打开它。
谢谢

Hi @changleibox 
I see there's an open issue (https://github.com/flutter/flutter/issues/38135) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
