### ISSUE TITLE
frontend_server --initialize-from-dill does not account for autodetected sound mode

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68901]
In https://github.com/flutter/flutter/pull/68898 I will land a mitigation that caches a sound dill separately from a non-sound dill. This only works if `--sound-null-safety` is specified from the command line.

If the soundness mode is autodetected, then the tool does not know whether the dill was compiled in sound or unsound mode.

There are three potential long term fixes:
  * The frontend_server accounts for sound/unsound in --initialize-from-dill and recompiles accordingly
  * The frontend_server communicates in some way to the tool what mode the dill was compiled in, and the tool implements additional caching logic to account for this.
  * The tool disables --initialize-from-dill

**Comment by annagrin** [comment]
@jonahwilliams I am having a very similar problem with the expression compiler worker (that provides expression evaluation for webdev and google3). I was thinking about the following approach:

- add null safety mode to metadata
- add a "setNullSafetyMode" API to the expression compiler worker/frontend server
- after the page is loaded in the debugger, read the metadata and let the worker/server know 
   what the mode is before loading dependency dill files
  - the worker/server in that case will load the corresponding sdk (instead of loading it on start)
  - this will need some refactoring of how we currently initialize the worker/server
  -  the frontend server might need to know the mode before the debugger starts, 
      but it has assess to the metadata and can read the information from there directly

How does this sound?

**Comment by jensjoha** [comment]
When the incremental compiler is asked to load from dill it also knows which settings it is asked to compile with. It should give an error if the two are not compatible, that it doesn't is a bug and I'll fix that.

@annagrin either I'm mis-reading what you're writing (or missing something else) or you're talking about adding as metadata information that is already available.

For a little background information:
* Each kernel library has a nnbd compilation mode (`nonNullableByDefaultCompiledMode`) and a `isNonNullableByDefault` 
* Each component (should) have a nnbd compilation mode (`mode`, `modeRaw`)
* When asking to compile something the options given specify it as well

Is there something I'm missing?

**Comment by jakemac53** [comment]
@jensjoha the situation Anna is describing is a bit different because the tool which is passing in the dill files is not actually the tool that compiled them - it doesn't know the current mode and it doesn't actually read the dill files either (it is really just an intermediary between bazel/build_runner and the expression compiler worker).

**Comment by annagrin** [comment]
@jensjoha @jakemac53 You are right - I thought that the situations are similar but  frontend server and expression compiler worker are different wrt compilation information. Frontend server gets the soundness info from compiling the app, and expression compilation worker just loads dill files from an unknown compilation. Even if the information is stored in the dill files, the expression compilation worker cannot load them without matching sdk outline file, so it has to get soundness info from somewhere. Metadata seems appropriate enough... So please ignore the my messages, as they seem not relevant:)

**Comment by jakemac53** [comment]
I think that the expression compiler worker will still benefit from better error reporting here though - we had discussed adding that ourselves but may no longer need to (although it wouldn't hurt as an extra layer of invalidation if it is cheap to do).

**Comment by jonahwilliams** [comment]
It would probably be best to capture that in a new issue on the Dart SDK? This is specifically about caching dills for the flutter tool build process

**Comment by jakemac53** [comment]
Yes, agreed that it isn't directly related to this

**Comment by jonahwilliams** [comment]
This is fixed
