### ISSUE TITLE
Bad state: Future already completed #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)

### ISSUE THREAD

**Issue by aalhadhoud** [flutter/flutter#68999]
Flutter was working fine. then I was trying to upgrade dart after that I am not able to run my project or even flutter doctor.

here's my log after running flutter doctor:
```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0 20A5395g, locale en-US)
⢿Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12) 

```

 % dart --version
Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "macos_x64"

also if i try to run the app through VS code it says: The Flutter Daemon has terminated.
and If i try to run flutter run on the terminal i get:
```
 % flutter run
Launching lib/main.dart on SM N975F in debug mode...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12) -->
```

**Comment by pedromassangocode** [comment]
Hi @aalhadhoud 
Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by Whypins** [comment]
I am also facing same issue.

MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B28, locale en-GB)
    • Flutter version 1.22.3 at /Users/name/Documents/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


⣽Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by prashantdwivedi** [comment]
Please check this commends on my case that the below method works.
https://github.com/flutter/flutter/issues/40515#issuecomment-714499891
https://github.com/flutter/flutter/issues/40515#issuecomment-726878465

**Comment by jonny7737** [comment]
I have the same problem after Big Sur Mac OS update.  I am not using AdGuard.

flutter doctor -v
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

**Comment by alaadahmed** [comment]
I have the same issue exactly. I just upgraded mac to Big Sur, and when I start using flutter, it informed me that there is new update for flutter so I ran `flutter upgrade` then I got this error: 
```
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```
Now flutter doesn't work any more, and when I run `flutter doctor -v` it also give the same error message.

**Comment by LFSousa** [comment]
I had this issue after install Avast on Big Sur. Uninstalling it solved the problem.

**Comment by jonny7737** [comment]
> I had this issue after install Avast on Big Sur. Uninstalling it solved the problem.

I uninstall and reinstall Avast to solve most of the problem.  Then disable Avast VPN connection to solve the remaining problems.  Everything is working fine now.

**Comment by les-larsj** [comment]
Removing Avast from Big Sur fixed this problem for me too. Many thanks!

**Comment by marclester-tang** [comment]
I'm under a corporate proxy and currently experiencing this issue. Our proxy tool (proxifier) creates a virutal vpn thus whenever i execute flutter doctor im getting this similar issue. Maybe someone was able to resolve this issue without removing/turning off the vpn. thanks in advance.

**Comment by pedromassangocode** [comment]
For anyone facing this issue, please provide what was asked in https://github.com/flutter/flutter/issues/68999#issuecomment-716385621.

**Comment by PerLycke** [comment]
OS: MacOS Big Sur

Every http call fails in iOS simulator when using Adguard. It works with Adguard turned off. Everything worked fine in MacOS Catalina.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/per/dev/flutter
    • Framework revision 1aafb3a8b9 (3 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 0ADA9C75-A68D-4181-ADD6-E27467F91F24 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

```
</details>

**Comment by KishorAndroid** [comment]
I used `flutter config --no-analytics` . Now it's working fine.
Ref from [https://github.com/flutter/flutter/issues/40515#issuecomment-726878465](url)

**Comment by gyenattila** [comment]
I had same issue, but for me turning off the AdGuard helped. After that I was able to upgrade Flutter and run the application

**Comment by alejandroaap** [comment]
I have the same problem. Why does MacOS Catalina work in Big Sur not?

**Comment by eldados** [comment]
Same issue here ob Big Sur, disabling AdGuard did the trick

**Comment by pedromassangocode** [comment]
Since this is happening on the latest MacOS BigSur I suggest anyone to file a new issue and link into this one to better track the issue related to the BigSur OS.

**Comment by KishorAndroid** [comment]
> I had same issue, but for me turning off the AdGuard helped. After that I was able to upgrade Flutter and run the application

But I am using Kaspersky Internet Security, any similar fix for this?

**Comment by gyenattila** [comment]
> > I had same issue, but for me turning off the AdGuard helped. After that I was able to upgrade Flutter and run the application
> 
> But I am using Kaspersky Internet Security, any similar fix for this?

Try this one -> https://github.com/flutter/flutter/issues/41336, hope it'll help

**Comment by alejandroaap** [comment]
@gyenattila I also have kaspersky, I have opened a ticket in the kaspersky support. I don't understand what may be causing flutter not to update, the only thing that has changed has been the version of the operating system. I have no problem with anything except flutter.

**Comment by AlexV525** [comment]
I ran into this issue with MacOS Big Sur and Proxifier, solved with `flutter config --no-analytics`.

**Comment by pedromassangocode** [comment]
For anyone facing this issue on MacOS BigSur, please follow up on https://github.com/flutter/flutter/issues/70596.

**Comment by KishorAndroid** [comment]
> @gyenattila I also have kaspersky, I have opened a ticket in the kaspersky support. I don't understand what may be causing flutter not to update, the only thing that has changed has been the version of the operating system. I have no problem with anything except flutter.

Quit Kaspersky, then I can successfully run `flutter doctor` `flutter pub get` `flutter create`.

**Comment by andersoncarlosfs** [comment]
Hello, 

For those who have installed Avast. Please, you just need to deactivate the option "Scan secure connection" on Web Shield (Core Shields)

Cheers,

**Comment by lsuhov** [comment]
Hello,
The solution for me was different. I was missing permissions for Android Studio and Visual Code in Security & Privacy -> Privacy -> Full Disk Access.
![missing_permissions](https://user-images.githubusercontent.com/20156338/108053083-a05e5580-7055-11eb-9c37-fbf7ce0e2716.png)

**Comment by davemgl** [comment]
I have the same problem. 

How to reproduce this issue:

First I have experienced a problem when entering the command:  "flutter pub get" with the following error:

[        ] MSG : It looks like pub.dartlang.org is having some trouble.
[        ]     | Pub will wait for a while before trying to connect again.
[   +5 ms] IO  : HTTP error:
[        ]     | SocketException: Connection failed, address = pub.dartlang.org, port = 443

After this, I have checked the internet connection by changing all possible things such as VLAN, DNS, even using Mobile Data instead of the wired connection. A VPN tool has also been tried without a result.

As the problem persisted and I tried to upgrade the flutter back to the stable as following:

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
dave@Davaas-MacBook-Pro net_test % flutter channel 
Flutter channels:
  master
  dev
* beta
  stable
dave@Davaas-MacBook-Pro net_test % flutter channel stable 
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  + 5d36f2e7f5...a29104a69b beta             -> origin/beta  (forced update)
git:  + f99efdb760...e0bb275860 Hixie-patch-3    -> origin/Hixie-patch-3  (forced update)
git:    a706cd2112..f8cd24de95  dev              -> origin/dev
git:    98aa24cbe3..a29104a69b  flutter-1.26-candidate.17 -> origin/flutter-1.26-candidate.17
git:  * [new branch]            flutter-1.27-candidate.0 -> origin/flutter-1.27-candidate.0
git:  * [new branch]            flutter-1.27-candidate.1 -> origin/flutter-1.27-candidate.1
git:  * [new branch]            flutter-1.27-candidate.2 -> origin/flutter-1.27-candidate.2
git:  * [new branch]            flutter-1.27-candidate.3 -> origin/flutter-1.27-candidate.3
git:  * [new branch]            flutter-1.27-candidate.4 -> origin/flutter-1.27-candidate.4
git:  * [new branch]            flutter-1.27-candidate.5 -> origin/flutter-1.27-candidate.5
git:  * [new branch]            flutter-1.27-candidate.6 -> origin/flutter-1.27-candidate.6
git:  * [new branch]            flutter-1.27-candidate.7 -> origin/flutter-1.27-candidate.7
git:  * [new branch]            guidezpl-patch-1 -> origin/guidezpl-patch-1
git:    29e604e241..2c5c509486  master           -> origin/master
git:  * [new branch]            revert-75160-conditional_dart_define -> origin/revert-75160-conditional_dart_define
git:  * [new branch]            revert-76404-flutter-engine-flutter-autoroll-70a5bb13-88aa-42f7-ba5e-049c5c0de978-1613767354 -> origin/revert-76404-flutter-engine-flutter-autoroll-70a5bb13-88aa-42f7-ba5e-049c5c0de978-1613767354
git:  * [new tag]               1.26.0-17.0.pre  -> 1.26.0-17.0.pre
git:  * [new tag]               1.26.0-17.1.pre  -> 1.26.0-17.1.pre
git:  * [new tag]               1.26.0-17.2.pre  -> 1.26.0-17.2.pre
git:  * [new tag]               1.26.0-17.3.pre  -> 1.26.0-17.3.pre
git:  * [new tag]               1.26.0-17.4.pre  -> 1.26.0-17.4.pre
git:  * [new tag]               1.26.0-17.5.pre  -> 1.26.0-17.5.pre
git:  * [new tag]               1.26.0-17.6.pre  -> 1.26.0-17.6.pre
git:  * [new tag]               1.27.0-1.0.pre   -> 1.27.0-1.0.pre
git:  * [new tag]               1.27.0-4.0.pre   -> 1.27.0-4.0.pre
git: Switched to branch 'stable'
git: Your branch is behind 'origin/stable' by 1 commit, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
dave@Davaas-MacBook-Pro net_test % flutter upgrade
Downloading Dart SDK from Flutter engine ae90085a8437c0ae94d6b5ad2741739ebc742cb4...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  172M  100  172M    0     0  8769k      0  0:00:20  0:00:20 --:--:-- 7965k
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Unhandled exception:




And After this, I have all same error when I enter any of flutter commands including flutter doctor, flutter -help etc.

The error I am encountering now:


dave@Davaas-MacBook-Pro net_test % flutter  clean
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up

**Comment by davemgl** [comment]
my flutter doctor -v log is attached.
[flutter_doctor.log](https://github.com/flutter/flutter/files/6017640/flutter_doctor.log)

**Comment by Yorch-Medina** [comment]
> Hello,
> 
> For those who have installed Avast, you just need to deactivate the option "Scan secure connection" on Web Shield (Core Shields)
> 
> Cheers,

I unistalled BitDefender and worked fine !!!

Thanks

**Comment by davemgl** [comment]
The uninstall BitDefender solved this issue. Thanks all!

**Comment by nashihu** [comment]
i follow @KishorAndroid and @AlexV525 solution and works fine 

> solved with `flutter config --no-analytics`.

**Comment by erperejildo** [comment]
> > Hello,
> > For those who have installed Avast, you just need to deactivate the option "Scan secure connection" on Web Shield (Core Shields)
> > Cheers,
> 
> I unistalled BitDefender and worked fine !!!
> 
> Thanks

I cannot do that since I use the company laptop and it needs bitdefender running

**Comment by Abion47** [comment]
I had this problem with the newest version of Sophos, running `flutter config --no-analytics` did the trick.
