### ISSUE TITLE
Do not rebuild bottom sheet if the new one has the same key

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#68992]
b/171424422

### Context

This is a proposal by customer:money to workaround the issue of disappearing focus when widgets rebuilt. As we have decided in https://github.com/flutter/flutter/issues/54695, the fact that focus is reset after widget rebuild is WAI. However, there might be certain edge cases that we can handle in the framework to make this easier for applications.

### Customer Proposal

If a persistent bottom sheet is rebuilt at all, the whole sheet is [removed and then rebuilt](https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/material/scaffold.dart#L2690-L2709), this is causing focus to be lost for screen readers.

The suggestion is to also check if the old widget bottom sheet matches the new widget bottom sheets key. If so, then don't close/rebuild the bottom sheet. 

### mehmetf's take

I believe this is happening because some data change happens in the parent page which then rebuilds the page including bottom sheet; I don't think the buttom sheet is buildable via `const`.

This feels like an infeasible request to me. I am not sure if we have any other logic in framework that overrides `didUpdateWidget` behavior based on keys. If the (bottom sheet) widget indeed changes but user forgets to update its key, it will turn into a tough to debug issue. However, I wanted to open it to discussion.

**Comment by mehmetf** [comment]
There's a number of issues that are blocked behind this decision so we should give some guidance asap.

**Comment by mehmetf** [comment]
FYI @goderbauer @chunhtai

**Comment by chunhtai** [comment]
I would like to point out one thing, the focus disappear due to rebuild, it disappear because the original widget is considered as a totally different widget from the new one, thus the flutter framework remove the semantics node and replace it with a new one.

A rebuild does not do that, it merely update its content, but will reuse the same semantics node.
 
From the look of the code, it seems like we are trying to transition out the old bottom sheet and transition in the new bottom sheet when it changes.

this code shows the effect that we are trying to achieve
```dart
/// Flutter code sample for ScaffoldState.showBottomSheet
// @dart = 2.9

// This example demonstrates how to use `showBottomSheet` to display a
// bottom sheet when a user taps a button. It also demonstrates how to
// close a bottom sheet using the Navigator.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

/// This is the main application widget.
class MyAppState extends State<MyApp> {
  static const String _title = 'Flutter Code Sample';
  int bottomSheet = 1;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title),),
        body: MyStatelessWidget(),
        bottomSheet: Container(
          height: 500/bottomSheet,
          color: Colors.red[bottomSheet*50],
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text('$bottomSheet'),
              ElevatedButton(
                  child: const Text('update BottomSheet'),
                  onPressed: () {
                    setState(() {
                      bottomSheet += bottomSheet;
                    });
                  })
            ],
          )
        ),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('body')
    );
  }
}
```
Note that there are animation when transitioning out the old bottom sheet.
![bottomsheet](https://user-images.githubusercontent.com/47866232/97215369-93a1b300-1781-11eb-9182-12251e0e1f09.gif)
If we don't need this effect, then we can definitely fix it so that the semantics node of the bottom sheet persist after the update (event if there is a rebuild). The child semantics node will be updated based on the subtree, but if they are the same, the semantics subtree will persist too.

I looked around the document, I can't find where we document the behavior when bottom sheet changes, whether it should update the content vs treat it as new bottomsheets and do the transitioning. That being said, I also don't think we should make this change, because this is a rare use case and it does not make sense to change the current behavior so that the developer can workaround the semantics focus issue event if the current behavior is not well documented.

I am thinking about providing way to change semantics focus. Although the focus disappearing issue matches the native iOS/Android, the native iOS and Android both provides way to change current focus. This does indeed provide a way to work around that issue.

Do you have any input on this @goderbauer ?

**Comment by goderbauer** [comment]
Wouldn't the easiest way around this be to just cache whatever value is passed to `Scaffold.bottomSheet` so you can pass in the exact same widget instance again when for whatever reason the widget surrounding the scaffold is rebuild?

**Comment by mehmetf** [comment]
> I am thinking about providing way to change semantics focus.

This definitely has been asked several times even though so far we have said "no" :-).

> Wouldn't the easiest way around this be to just cache the bottom sheet?

That's why I was first looking into whether `const` can be used. I will make this suggestion and see what they think. I dislike explicit caching of widgets since it introduces another layer of complexity for apps. We recommend against it unless there's a performance reason. Hopefully this is an isolated use case and is not necessary for every single bottom sheet in their app.

**Comment by chunhtai** [comment]
looks like customer is ok with our suggestion, closing this issue
