### ISSUE TITLE
Allow us to use different yaml files (l10n.yaml, analysis_options.yaml) for different envs

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#69023]
## Use case

- I want to be able to have a different `l10n.yaml` file for when I deploy to the web and on an Android phone. (https://github.com/flutter/gallery/issues/357)
- I want to have a different `analysis_options.yaml` file depending on the environment, so that in tests I can be less strict compared to when developing. (See https://github.com/flutter/gallery/issues/356) This might be a Dart issue rather than a Flutter issue.

## Proposal

Via Environment variables let us set the path to the different yaml files.

`L10N_PATH=web/l10n.yaml flutter build web`
`ANALYSIS_OPTIONS_PATH=tests/analysis_options.yaml flutter analyze`

**Comment by perclasson** [comment]
cc @shihaohong Do you think this is something we'd like to support?

**Comment by christopherfujino** [comment]
So those two config files you listed get consumed in different ways. `analysis_options.yaml` is implicitly read by `dartanalyzer`, which `flutter analyze` wraps. `dartanalyzer` provides the flag `--options /path/to/config.yaml`. Supporting that would just be a matter of adding the flag to `flutter analyze` and piping it through to the underlying invocation to `dartanalyzer`.

**Comment by christopherfujino** [comment]
cc @shihaohong about supporting genl10n config files

**Comment by shihaohong** [comment]
Hey! Sorry, I thought I had sent my comment, but apparently I didn't.

Regarding the `l10n.yaml` files, if it's a CI step to publish/deploy a particular version for a target platform, you can also use the explicit command itself instead of using an `l10n.yaml`:`flutter gen-l10n {all options}`. That'd be a good way to use explicit command line arguments over env. variables, which Chris has already mentioned is preferred.
