### ISSUE TITLE
Dart  terminated

### ISSUE THREAD

**Issue by basha97** [flutter/flutter#69083]
Dart is terminated every couple of minutes in both android studio and vscode after upgrading new flutter version ( Channel stable, 1.20.4 )

**Comment by sidrao2006** [comment]
Hey @basha97 ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a plugins, please close this issue and open it [here](https://github.com/dart-code/dart-code/issues) instead for VS Code with your logs

Thanks
