### ISSUE TITLE
Как расположить несколько RadioListTitle в горизонтальном порядке? on Flutter.

### ISSUE THREAD

**Issue by RQRQ000** [flutter/flutter#69167]
я столкнулся с проблемой, у меня есть 2 RadioListTitle, они расположены по вертикали, а мне необходимо расположить их по горизонтали. Как это сделать? Текст программы:
```
RadioListTile(
        title: const Text('Мужской'),
        value: GenderList.male,
        groupValue: _gender,
        onChanged: (GenderList value) {setState(() { _gender = value;});},
      ),

       RadioListTile(
        title: const Text('Женский'),
        value: GenderList.female,
        groupValue: _gender,
        onChanged: (GenderList value) {setState(() { _gender = value;});},
      ),
```

**Comment by pedromassangocode** [comment]
Здравствуй @RQRQ000 
Эта проблема, похоже, не описывает ошибку или запрос функции. Посетите https://flutter.dev/community, чтобы найти ресурсы и задать такие вопросы,
вы также можете получить некоторую помощь, если опубликуете ее на Stack Overflow, и если вам нужна помощь с кодом, см. https://www.reddit.com/r/flutterhelp/
В заключение, поскольку это не проблема самого Flutter. Если не согласны, пишите в комментариях, и я открою его повторно.
Спасибо

Hi @RQRQ000 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

NOTE: I had to use Google Translate because I don't understand Russian.
