### ISSUE TITLE
In list view, Scrollable.ensureVisible works only till the 7th key. Post that it does not scroll.

### ISSUE THREAD

**Issue by minal2709** [flutter/flutter#69173]
## Steps to Reproduce

1. Create a list using list builder and add more than 7 elements. I have 11 elements.
2. Then in a stateful widget, do 
WidgetsBinding.instance.addPostFrameCallback((_) => {
      Scrollable.ensureVisible(selectedDataKey.currentContext)
});

**Expected results:** It should scroll to that element.

**Actual results:** It scrolls to the key for up to 7th place, for the remaining elements it does not.
So for 'first', 'second' .... 'seventh' it scrolls to 7th on load. but for the 'ninth', etc, it stays where it was.

**Comment by darshankawar** [comment]
@minal2709 
This seems to be a current limitation of `Scrollable.ensureVisible`, because when the list item go away from screen, it loses the context and `Scrollable.ensureVisible` works only with current context, ie, with list item that are visible. See [this](https://github.com/flutter/flutter/issues/17668) open issue for your reference. If you list is static and not going to change, you may try to replace it with SingleChildScrollView instead of ListView.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
