### ISSUE TITLE
Add web platform to Get to know Firebase for Flutter

### ISSUE THREAD

**Issue by sumithpdd** [flutter/flutter#69182]
Firebase web codelab links missing n https://firebase.google.com/learn/codelabs/firebase-get-to-know-flutter?return=https%3A%2F%2Ffirebase.google.com%2Flearn%2Fpathways%2Ffirebase-flutter%23codelab-https%3A%2F%2Ffirebase.google.com%2Flearn%2Fcodelabs%2Ffirebase-get-to-know-flutter#9

**Comment by domesticmouse** [comment]
@sumithpdd The [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter) codelab doesn't yet cover Flutter for Web. Are you saying the codelab should cover Flutter for Web?

Or am I mis-reading your bug report?

**Comment by sumithpdd** [comment]
Yes,
Also there is another similar code lab  ,
https://firebase.google.com/codelabs/firebase-get-to-know-web#1

I would say we should merge the use case and the story together, and if
possible for flutter 2.0 we can even extend to flutter web.
Thanks
Sumith

**Comment by domesticmouse** [comment]
The[Get to know Firebase for web](https://firebase.google.com/codelabs/firebase-get-to-know-web#1) was the direct inspiration for [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#1). 

However, the two will not be merged because they use different technology stacks. The version for web uses JavaScript, and the one for Flutter uses, err, Flutter.

With that said, I'm marking this bug up as a request to add the web platform target to Get to know Firebase for Flutter.

**Comment by domesticmouse** [comment]
This has been partially addressed by https://github.com/flutter/codelabs/pull/86. Next up is landing the changes to the codelab text.

**Comment by domesticmouse** [comment]
Codelab text update has landed. Closing this out...
