### ISSUE TITLE
Documentation on OutlineButton vs OutlinedButton is not clear

### ISSUE THREAD

**Issue by omaracrystal** [flutter/flutter#69270]
In documentation here -> https://api.flutter.dev/flutter/material/OutlineButton-class.html
Says "This class is obsolete, please use OutlinedButton instead."
I go to switch from OutlineButton to OutlinedButton and get several errors since the schema of this button is now different than previous. 
When I tried to find code examples here --> https://material.io/develop/flutter/components/buttons#outlined-button

I see that the example uses OutlineButton and not OutlinedButton. Is this simply a typo?

Pic attached. 
![Screen Shot 2020-10-28 at 8 53 02 PM](https://user-images.githubusercontent.com/11908147/97519870-9d810d00-195f-11eb-97be-a7a14dc3d21e.png)

**Comment by pedromassangocode** [comment]
Hi @omaracrystal 
This is definitely a typo, looks the docs need to be updated. 
The documentation of OutlinedButton is at https://api.flutter.dev/flutter/material/OutlinedButton-class.html. 

Please refer to https://github.com/flutter/flutter/issues/54776 for some usage examples.

Since this is an issue in the Material Design website I'm going to close it. 
Thank you
