### ISSUE TITLE
Add official support for material design image lists types

### ISSUE THREAD

**Issue by HrX03** [flutter/flutter#69302]
MD docs available at: https://material.io/components/image-lists

## Use case

The masonry image list is useful to achieve Google Keep UI style, the quilted image list could be cool for something like a news app and woven image list is already used on the Shrine material study

## Proposal

I would add some sliver delegates to use with the gridDelegate GridView param, to keep compatibility with older gridview and also provide an easy to use api. For example for the woven image list offer an aspect ratio param, for the quilted image list you could use another widget like "GridTile.quilted(crossAxisExtent: ...)" and for the masonry grid just shrinkwrap vertically tiles. It would be nice to also add support for reorder/animations

**Comment by iapicca** [comment]
@HrX03 
according to the link you shared 
the status for android, ios and flutter is `planned`
maybe a feature request on the matter  is a bit premature

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/97595651-9106be00-1a0c-11eb-9963-b51ea65fa80f.png)

</details>

**Comment by HrX03** [comment]
doesnt planned mean that it's coming but no idea when? like, it's supposed to come but no one knows when. i would love to work on it but still need some more understanding on grids/lists/slivers

**Comment by HrX03** [comment]
could actually try implementing it, will look up current grid stuff and see if i can figure out something

**Comment by Hixie** [comment]
Looks like the main thing missing here is the SliverGridDelegate implementations for the remaining types of grids. (The rest is pretty much covered by GridView and GridTile already, it seems.)

**Comment by cpboyd** [comment]
I'm using [flutter_staggered_grid_view](https://github.com/letsar/flutter_staggered_grid_view) in the interim, but I see some layout performance issues reported in the logger when scrolling.

**Comment by letsar** [comment]
I would be happy to implement the quilted and woven variants when I find the time but I don't see how we can implement the masonry variant with the current SliverGridDelegate. @Hixie have you some hints concerning this one?
I tried to implement it in https://github.com/letsar/flutter_staggered_grid_view but for dynamic heights there are some performances issues because each tile placement depends on every tile before it.

**Comment by letsar** [comment]
I released a complete refactoring of [flutter_staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view) which provides the following types of [Material Image List](https://material.io/components/image-lists):

### Masonry

![masonry](https://user-images.githubusercontent.com/9378033/147645183-64700eef-23b9-4a24-b65f-50cea8bcb120.png)

### Quilted

![quilted](https://user-images.githubusercontent.com/9378033/147645193-08e2007b-015c-4e49-9449-d7a6e8429572.png)

### Woven

![woven](https://user-images.githubusercontent.com/9378033/147645196-0c66937a-ac25-4ec8-b7a3-25cce1f8de6a.png)

Since the Standard Image List is built-in in Flutter, we have now a simple way to have all kind of Image Lists.
Would it make sense to add a link to this package into the [Flutter implementation page](https://material.io/components/image-lists/flutter)?

**Comment by HansMuller** [comment]
CC @willlarche - update https://material.io/components/image-lists/flutter?

**Comment by willlarche** [comment]
Definitely a mistake if it's marked planned. I believe we could link out to a package if that's what you wanted @HansMuller . @guidezpl can handle any changes to the documentation with Content dept.

**Comment by HansMuller** [comment]
@guidezpl - I think it would be reasonable for  https://material.io/components/image-lists/flutter to point to https://pub.dev/packages/flutter_staggered_grid_view
