### ISSUE TITLE
LUCI pre-submit tasks are still running even PR is closed

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#69333]
We should cancel existing running/pending tasks whenever a PR is closed.

<img width="736" alt="Screen Shot 2020-10-29 at 1 09 30 PM" src="https://user-images.githubusercontent.com/54558023/97627118-217ed780-19e8-11eb-8718-20c33a753681.png">

**Comment by godofredoc** [comment]
\cc @nehalvpatel this is a good one for the cocoon backend.

**Comment by nehalvpatel** [comment]
So, I've been looking into this and I'm trying to figure out if this is a bug in the pull request handler.

I realized that there is logic in the pull request event handler that should detect a closed, unmerged PR and cancel the related builds, and it has been present since Jan 2020:
- https://github.com/flutter/cocoon/blob/ba296c0eecd6b457895e60f2526e7761be2b89b9/app_dart/lib/src/request_handlers/github_webhook.dart#L84-L101
- https://github.com/flutter/cocoon/blob/ba296c0eecd6b457895e60f2526e7761be2b89b9/app_dart/lib/src/request_handlers/github_webhook.dart#L335

It was slightly modified through refactors but it's mostly the same logic today:
- https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/github/webhook_subscription.dart#L111-L121
- https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler.dart#L261-L267
- https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart#L291

**Comment by godofredoc** [comment]
@ricardoamador I believe this is already fix, am I right?

**Comment by ricardoamador** [comment]
Correct. this is fixed.
