### ISSUE TITLE
Module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by monizj** [flutter/flutter#69414]

**Comment by sidrao2006** [comment]
Hey @monizj ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a 3rd party package, please close this issue and open it [here](https://github.com/FirebaseExtended/flutterfire/issues) instead.

If you disagree, please post the outputs of `flutter run -v` and `flutter doctor -v` and provide a complete minimal reproducible code sample.

Thank you!
