### ISSUE TITLE
Adopt a Widget - StatusTransitionWidget

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69472]
The [StatusTransitionWidget](https://master-api.flutter.dev/flutter/widgets/StatusTransitionWidget-class.html) widget needs:

- A code / DartPad sample
- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by Sameerkash** [comment]
@johnpryan I would like to work on this 🚀

**Comment by Sameerkash** [comment]
I'm unable to come up with an implementation for this, any pointers would help, should I extend this or Instantiate this? since it's an abstract class.
I thought It would just be like a `NotificationListner()` updates its child on animation notification, but there is no child.

**Comment by Sameerkash** [comment]
After discussing with @shihaohong, the class seems to have originated 5 years ago and doesn't seem fit for any use case as it restricts to `Animation<double>`, which is bad because the value isn't used for anything else, and `AnimatedBuilder()` just does a better job of the intended use case.  The proposal is to deprecate the class. Please let us know your thoughts. @johnpryan

**Comment by johnpryan** [comment]
@Sameerkash We'll mark this issue as closed. It was added to the list because of its short doc comment. Thanks for looking into this!

**Comment by johnpryan** [comment]
@Sameerkash Thanks for participating in AdoptAWidget. We would like to send you a special thanks. If you are interested, please send an email to nyener at google dot com and provide a link to this issue.

**Comment by Sameerkash** [comment]
@johnpryan thank you so much. 
I'll get in touch.
