### ISSUE TITLE
IconButton slash doesn't persist while finger is down

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#695]
We've got the splash effect for icon button now, but we're missing the persistent highlight.  Also the splash appears to be the wrong color in the toolbar of the stocks app.  (It's dark instead of light).

@Hixie

**Comment by Hixie** [comment]
The splash being the wrong colour is a known issue, we should file a separate bug for that. I couldn't find any reference to what the colour should be, which is why it's the way it is.

For the persistent highlight, do you have a pointer to the relevant part of the spec? I couldn't find anything about it, and none of the other platforms do it for icon buttons as far as I can tell.

**Comment by abarth** [comment]
> For the persistent highlight, do you have a pointer to the relevant part of the spec?

The spec isn't very specific about how these highlights should work.

> none of the other platforms do it for icon buttons as far as I can tell.

Take Inbox for example.  On the main screen, press and hold on the menu button.  Notice that the splash grows to a certain size and then stays visible.  In Stocks, the splash fades away.  The splashes in Calculator and Dialer are similar in that they stay visible until you lift your finger.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/721
