### ISSUE TITLE
flutter doctor reports Android Studio (version 4.1); Flutter plugin not installed and Dart plugin not installed errors

### ISSUE THREAD

**Issue by gayanpathirage** [flutter/flutter#69514]
## Steps to Reproduce
OS: MacOS Catalina 10.15.7
Android Studio: 4.1
install flutter plugins

and check;

flutter doctor

## Logs
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
```

**Comment by gayanpathirage** [comment]
Apparently found the issue thanks to this post; [Flutter plugin not installed error; When running flutter doctor](https://stackoverflow.com/a/64529134/1820413)

Plugin folder has changed in 4.1 version; 
From : ~/Library/Application\ Support/AndroidStudio4.1
To: ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins

**Comment by gayanpathirage** [comment]
Temporary fix as suggested in the above answer;

`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by hamdikahloun** [comment]
Hi @gayanpathirage 

Failing to detect the plugins will not affect Flutter development at all. The Flutter CLI tool does not touch the plugins, only your editor does. Because of this, we plan to deprecate the plugin validators : #61246 .

Thank you

**Comment by pedromassangocode** [comment]
As mentioned above this is not a big issue since it does not stops customers to use Flutter.

**Comment by rs-anhnq2** [comment]
I have the same issue due to I want to backup from my laptop to desktop. I used android studio 4.2 and try many way even remove my flutter and download again or reinstall android studio. But if only occurs when I checkout to version 1.22.6. Channel dev, stable, master doctor -v run ok without warning. Luckily even though has warning that "Flutter and dart not installed" but I still build flutter project on android and by android studio smoothly. 
 So I 'll ignore this. :)))
