### ISSUE TITLE
Send a notification to google infra when ngine artifacts are built

### ISSUE THREAD

**Issue by renyou** [flutter/flutter#69621]
Hi I have built the tools to perform the "Google testing" and now expanded the coverage to engine's postsubmit PRs. Our tests use LUCI built artifacts but we don't know when they are ready to download. Currently we have a fixed delay before trying. If there could be a notification sent to Google infra, we can start the testing much sooner and provide signals more promptly.

**Comment by godofredoc** [comment]
\cc @keyonghan FYI this is the onboarding project for Yusuf

**Comment by godofredoc** [comment]
Flutter uses the cocoon backend to send rpc requests to the luci services [presubmit example](https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/service/luci_build_service.dart;l=199?q=scheduleBuildRequest&ss=flutter%2Fcocoon). We are currently using those presubmit configurations to update the github states.

In order to notify the G3 team when there are new artifacts we need to add a notification configuration to the post-submit requests. Although in this case will be in two different places: [cocoon for retries](https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/service/luci_build_service.dart;l=387?q=scheduleBuildRequest&ss=flutter%2Fcocoon) and in the the [infra engine configs](https://cs.opensource.google/flutter/infra/+/master:config/engine_config.star) by adding a [notifies configuration](https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/lucicfg/doc/README.md#luci.builder) to the enginge luci.builders 

I'd recommend to create a new pubsub topic in the flutter-dashboard e.g "projects/flutter-dashboard/topics/luci-builds-prod" for this purpose.

**Comment by yusufm** [comment]
Created "projects/flutter-dashboard/topics/luci-builds-prod" to hold the build complete messages.

**Comment by yusufm** [comment]
After speaking with the LUCI team, they had a few recommendations on how this could be achieved.

They mentioned that the ideal method would be to complete the "user defined pubsub topic" feature (https://bugs.chromium.org/p/chromium/issues/detail?id=843720) that is currently in development. 

But given the remaining work that needs to be completed for the feature, the more likely path to get this working immediately would be to add to the LUCI recipes. I will be looking into extending the relevant recipes to send a message to the pubsub topic on completion of the build.

**Comment by yusufm** [comment]
To clarify, the requirement for the type of messages from Ren:

 We probably only cares about successful ones now. But it might be useful to sent the failed ones too. For example, you could have a simple service to retry the build, or some other usecases?

**Comment by yusufm** [comment]
Discussing with Ren, the notifications are required for the engine builds only. Notification should include githash, and build status.

**Comment by yusufm** [comment]
CL is submitted, messages are now appearing the topic.

**Comment by yusufm** [comment]
Tree was closed due to failing jobs with this change:

ERROR: (gcloud.pubsub.topics.publish) PERMISSION_DENIED: User not authorized to perform this action.

**Comment by yusufm** [comment]
Added necessary permissions to appropriate prod builder user. And will modify the code to not fail if publish step fails.

**Comment by yusufm** [comment]
Changes have been resubmitted, now ignoring failures in the gcloud step.
