### ISSUE TITLE
MethodChannel performs slow

### ISSUE THREAD

**Issue by cs-robert** [flutter/flutter#69647]
I record start time at channel.invokeMethod ,record end time at setMethodCallHandler callback,
send 4000 byte data from native to dart ,it cost 40 ms .
but some times it perform good, only cost 10ms.
When called frequently, the performance will be worse.
No time-consuming method is executed in the channel.
Dart to native have the same problem.
In addition，how to send and receive dart message in non-ui thread？

**Comment by pedromassangocode** [comment]
Hi @robert-wq 
Can you share the code you used for performance tests and your `flutter doctor -v`?

For asking questions I would suggest you to use Stack Overflow or see https://flutter.dev/community for a list of Flutter communities.

Thank you

**Comment by robert-wq** [comment]
`for (int i = 0; i < 10; i++) {
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    Map map = new HashMap();
                    map.put("timestamp", System.currentTimeMillis());
                    Map map2 = new HashMap();
                    map2.put("params", "XXXXXXXXXXXXXXXXXXXXXX");
                    map.put("param", map2);
                    mChannel.invokeMethod("gettime", map);
                }
            }, i * 100);`


 android flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/jc/.fvm/versions/v1.12.13+hotfix.5-stable
    • Framework revision 27321ebbad (11 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jc/software/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/jc/software/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Mi 10 • 48bbb91b • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @robert-wq 
Looks like you are using a really old Flutter version.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v` and a minimal complete reproducible project sample?
Thank you

**Comment by robert-wq** [comment]
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/jc/software/flutter
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.sankuai.com
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jc/software/android
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/jc/software/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • Mi 10 (mobile) • 48bbb91b • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.


[flutter_test.zip](https://github.com/flutter/flutter/files/5485363/flutter_test.zip)


output log

(standard input):11-04 11:37:44.100 19951 19992 I flutter : callData  native to dart gettime 793  
(standard input):11-04 11:37:44.108 19951 19992 I flutter : callData  native to dart gettime 702  
(standard input):11-04 11:37:44.110 19951 19992 I flutter : callData  native to dart gettime 604  
(standard input):11-04 11:37:44.110 19951 19992 I flutter : callData  native to dart gettime 504  
(standard input):11-04 11:37:44.111 19951 19992 I flutter : callData  native to dart gettime 405  
(standard input):11-04 11:37:44.112 19951 19992 I flutter : callData  native to dart gettime 305  
(standard input):11-04 11:37:44.112 19951 19992 I flutter : callData  native to dart gettime 206  
(standard input):11-04 11:37:46.509 19951 19992 I flutter : callData  native to dart gettime 1  
(standard input):11-04 11:37:46.591 19951 19992 I flutter : callData  native to dart gettime 1  
(standard input):11-04 11:37:46.691 19951 19992 I flutter : callData  native to dart gettime 1  
(standard input):11-04 11:37:46.791 19951 19992 I flutter : callData  native to dart gettime 1  
(standard input):11-04 11:37:46.892 19951 19992 I flutter : callData  native to dart gettime 2  
(standard input):11-04 11:37:46.994 19951 19992 I flutter : callData  native to dart gettime 4  
(standard input):11-04 11:37:47.094 19951 19992 I flutter : callData  native to dart gettime 3  
(standard input):11-04 11:37:47.193 19951 19992 I flutter : callData  native to dart gettime 2  
(standard input):11-04 11:37:47.293 19951 19992 I flutter : callData  native to dart gettime 3  
(standard input):11-04 11:37:47.392 19951 19992 I flutter : callData  native to dart gettime 2

**Comment by pedromassangocode** [comment]
Cc @chinmaygarde @liyuqian

Note: it is required to update the Gradle URL in `<project-name>/android/gradle/wrapper/gradle-wrapper.properties` to run the project mentioned in the comment above to:
`distributionUrl=https://services.gradle.org/distributions/gradle-4.10.1-all.zip`

Somehow it give me error while trying to run the project.

**Comment by ilber** [comment]
I am running into the same problem. Trying to send this string:

`R0lGODlh4gBkAPcAAAAAAAAAMwAAZgAAmQAAzAAA/wArAAArMwArZgArmQArzAAr/wBVAABVMwBVZgBVmQBVzABV/wCAAACAMwCAZgCAmQCAzACA/wCqAACqMwCqZgCqmQCqzACq/wDVAADVMwDVZgDVmQDVzADV/wD/AAD/MwD/ZgD/mQD/zAD//zMAADMAMzMAZjMAmTMAzDMA/zMrADMrMzMrZjMrmTMrzDMr/zNVADNVMzNVZjNVmTNVzDNV/zOAADOAMzOAZjOAmTOAzDOA/zOqADOqMzOqZjOqmTOqzDOq/zPVADPVMzPVZjPVmTPVzDPV/zP/ADP/MzP/ZjP/mTP/zDP//2YAAGYAM2YAZmYAmWYAzGYA/2YrAGYrM2YrZmYrmWYrzGYr/2ZVAGZVM2ZVZmZVmWZVzGZV/2aAAGaAM2aAZmaAmWaAzGaA/2aqAGaqM2aqZmaqmWaqzGaq/2bVAGbVM2bVZmbVmWbVzGbV/2b/AGb/M2b/Zmb/mWb/zGb//5kAAJkAM5kAZpkAmZkAzJkA/5krAJkrM5krZpkrmZkrzJkr/5lVAJlVM5lVZplVmZlVzJlV/5mAAJmAM5mAZpmAmZmAzJmA/5mqAJmqM5mqZpmqmZmqzJmq/5nVAJnVM5nVZpnVmZnVzJnV/5n/AJn/M5n/Zpn/mZn/zJn//8wAAMwAM8wAZswAmcwAzMwA/8wrAMwrM8wrZswrmcwrzMwr/8xVAMxVM8xVZsxVmcxVzMxV/8yAAMyAM8yAZsyAmcyAzMyA/8yqAMyqM8yqZsyqmcyqzMyq/8zVAMzVM8zVZszVmczVzMzV/8z/AMz/M8z/Zsz/mcz/zMz///8AAP8AM/8AZv8Amf8AzP8A//8rAP8rM/8rZv8rmf8rzP8r//9VAP9VM/9VZv9Vmf9VzP9V//+AAP+AM/+AZv+Amf+AzP+A//+qAP+qM/+qZv+qmf+qzP+q///VAP/VM//VZv/Vmf/VzP/V////AP//M///Zv//mf//zP///wAAAAAAAAAAAAAAACH5BAEAAPwALAAAAADiAGQAAAj/APcJHEiw4EAAAAQiVIiwIcOFBxNGhNhQIkGIDC863FeR4saMEyV6BKmxpEGOIjuaxBhRY8WVKU+iJCmzpk2DI1G+1GlxZsiHPWmy3Nkx5dCeRGP6NEkT5k6QLIWqbOkzKlWrN7OezFkUKFOeXgsedWl049OlYKsq/YpV7dmcbKdCXSuWrta7decmHfszbVyyQD3yDcs1KNq2gj+qxYlU7mK0MPFKzuvWrOKjiRnHTZyZKmGlVgdT7nrVMObLoA3Pncz6Mem3jTv/7fsaNWDXphvL5Kwb8mHHhXfbbZ218N7en0MjT1tbdNLVlJuWhi39NF+4o1UTr2ncsnPvuTeX/5X9O7hv0U5tn4+tHnvk7Xe7kz8ddnZy8OKhK/+a/nr4kP5JBx18xaV2XH5+eVbeeGUhaJ592VG3HlkB+jYggTbJ16CCB0a3YGAbSmXefgr21xuJIL6H2HAYalbZfOzVx2GMPMF424MzCpdiaS7uqJ927rXoIm8y0pegVDdOJeFnFyK5FYPviVfhigIKyWONIX545G9JdihiatUtZ2KUM0oYZJNWqqikevf1qGVzyz33GIRjXinliSzOmWZ2Oy7JnGJO3mcjbWB6SCWWZH45JZB5pqlhkTSeFeifXr5ZKJ3Ttfefj7jpaOGejyZopKRcElrpqJfm+CSnQVqHZ5Vngv9qIH5lZjnpcYMyqeekdaLpqpqetuXorLlSuqmlp0aaKq+ZVngnsKt+OqxetH4p463gFStnq2I2+6qhwC1r555qJtvlsaiaS6iv3VLrbK2LBqvdtC9mmS66yqqrK7f8eZvogvFGK6yVofpZKbZEiqosu/26++2zVx46sJAFs2msm/dqaxnDJfo7rqLfSjwvwcTamy++52o8IsoChxsmhSEzWiW9CRtcraqCmpwkx7BC+THAMctL7pA+20wewkVbvO1w6HnMM6IRyywtyQ5Dei7GJ6tcKIqfJvw0aT8KPXS5N9+Ldco6r7trqUSbia/bPc9Mdb1Wm8pyznXvy3S7dP///GvUYo/9o74Xg4t23n9+LTXYa/8ddsuCR034wWwbq/XjmFbtN3sBEx354GWffLbdl3dqeMtwg5u6yJ/jNvnNSPep9MaN8+117TBD6/nnFX93dOW4pq33yx1rrvjqi49MccmIU+570s9jjnOEmmKNfOCC9x4n7MBnK3ziuBff9/HVd93o3DXP/nv0UBu99d3Uvwuy7nzyzrzCV5+ON/5q8yv+7f5jlbjQRC7tOQhQ3Usf+3DELOOFT4AEXFsB7+e+ayUQettb2ejaVj6ISe9fE9RcBbe0wDWVUHHySp0HTbe7yBmwVhYs4es0qL/4PQxeQYOc/USoPltdUHYnfKD5mCA4IQDlsIXZo2APY5hBDB4QhajrIA7pB0JZ8VCG8Ate82gXwCFCjXydq58LlYjFDVrue0sjXty+KETGMfBnIezbCEmFxdK9sWkO7KIbByhBK8pxiSRsIhAFycLp9aqNLutjrGjmRBgG8oAzfJ8ZD6nHRMZqkehrpLUe6Ug4PRGRKZTi/ACnwzFekZB0RKUJVQlFDsoPaFSE/6MfFahKrmUMjVzcW8PGh8jrlTKJp4RkFr23RRpmjpeV9CUSx/bCTaZSmHYUFx6RqUsjxjKCjBykMM2oRf4Nr4hr3KMa2fhGbGZSm51EYB1xaUxDOq2X5WPdDv9Yxhp2c47StJ3PwHhEMQKTnrUcJi0/WclQvtJxhaxiNtsHyGemM5IfrBwlq0nES55vecF8qEA1aalW2vBfCC1nHxfqSY1yk5jeBF9Bo3hQzvVToedkaD0hdM+G5nOXAKQoOfmISYwCdJv2RCk+PTrRcYpTkRdtUTORtVF0OvOm/9snPMMIU58O1KRBvepTifrOZMYzea1bqtmyylFUcTWPOj2qRf/lZtWyio6sTu0oKFl6w1FG1JxtjetYaSpUm56Vmka1ZJ56qlQyBvSkWpXrSl1ZV1iScplDE+tb+ZpYs86VsSB16TVHGtOSPtWWWWOnJGtYVHDuNIKExZBk80dZt+7ssh/dXO4e609mGhaordXrwmBbWtAqs7aRvS1WcytTVvK2q2kVbDiVV9iMts6UU3tuc704sekmVrpxrC52t7PW6FqXo9tdaHhnCdZ5Xne830UvebE3GX1QoSgIEUA0JMc9geijFipAyAHgUBB2FCUAoRjIffMLgP0K+L3wla998atf/rJ3H+6FLwAUDGFhEFgGyzDIMLSAEARo4sASpvA+Ntz/4Q8/GJvD2AJCAgCH+RIkHwguigBOQd/f7YMeMW4IBAgSjP8G+MY5RsiO9wHjENMYx0UZMmSLnGAa64MQRYkDj4tiBIEwWcY03kePO3KEE/dxyxVJQFaeDAAp19iH+6AFAHSQ4X0gI79mTjOAZaJmNgvkzWWWCZnNXOc24znOVbUvlM3sXwRkWB89pvA88utgYQBgzifZs0AWDYBGP/rHwCXgolksECQD+iQ9rjLZfufeBxSkHACwgKBFTJBSnzrVMgm1falgaoKgWtWQBTUARP3kAGRZIIqAtKwH0uMgxHrXxEZ2soHwSxCqGdD+VfJJFp0AF5/ZgjLJhwpq7V5p/2dF27UuCLWtfRJwN3vaKqh2TfQR7AD3GtP7WDQCyD3pdLv43QQZd67XVmp630TS9fPsTXahbP/+gMEBUIO/CUJwUbd60ANXdqYfnmc9LwIAQ34yq93LaghDfNXk5ri/u2uVRUNAHxd/dItt4t8HjFy4N1k0hcEc5oXHWwUd34d/1V0TmS+8pztfOKV3fW8q8HzVvxZI0A98dI/nnOSG8W8Rgtx0in86cpSOs5pz4OJh5Nfh+YazQdhdcZlkHUNkv/qkY3ADhOTAyrQOOSE2roiyQzjuD5/x2Pz7aBN7XeIF0XbVBWfhSt9E8PQuvIPFbe+aKL5F+raJPtRsavdWXf8Reh9I5OF++ZwLyb+Qrvfg99Hw59730WoviMatffoApL70ka4F6oU07H9TQb6rf/HtyQ17gsyd3DD2fIsQn3d/4/tzZJ63VjSe5eTb/Piqh7LyWwR9yc/9FOwO/c2PXn0Itzvso4d84wWMeeMb3eZWIjMQzM/qnQsaAOtf9/nHDuX4C8ny9BZ52F1OesDX/u6D13taBnh7QmZ3AH7+Fm2t02PMRmcAgAA/VnhmxoA3oYAGQYFpYoEFoWYQKBB/14CUZmnap4FhZ3j74GjaRy6g52B/p3b/NzQRBl/qpg8c1hG8FmQNcXQveHcSFn5asYPel2TWRnMIAXYDaITJZoNlrSN7HeFtA4FqqWclfCeD98ZgAOAAJqZzEgYAR0dwVzeFReGDWQGFesYLBNYAizcQJPaAWfiEdlcQa+hh0oUMMIAQaKheeJiHeriHfNiHfviHgBiIgjiIhFiIhniIiJiIiqiIAQEAOw==
`
from dart to android and the 

`_methodChannel.invokeMethod(FUNCTION_NAME, STRING)`

Is taking randomly from 2 to 6 seconds. And of course during this time the app is freezing. 

What are your plans for fixing this? Do you have any idea why is happening or how to improve the performance? Tried also with a `Uint8List` instead of a string but the result was the same.

**Comment by liyuqian** [comment]
> (standard input):11-04 11:37:44.100 19951 19992 I flutter : callData native to dart gettime 793
(standard input):11-04 11:37:44.108 19951 19992 I flutter : callData native to dart gettime 702
(standard input):11-04 11:37:44.110 19951 19992 I flutter : callData native to dart gettime 604
(standard input):11-04 11:37:44.110 19951 19992 I flutter : callData native to dart gettime 504
(standard input):11-04 11:37:44.111 19951 19992 I flutter : callData native to dart gettime 405
(standard input):11-04 11:37:44.112 19951 19992 I flutter : callData native to dart gettime 305
(standard input):11-04 11:37:44.112 19951 19992 I flutter : callData native to dart gettime 206
(standard input):11-04 11:37:46.509 19951 19992 I flutter : callData native to dart gettime 1
(standard input):11-04 11:37:46.591 19951 19992 I flutter : callData native to dart gettime 1
(standard input):11-04 11:37:46.691 19951 19992 I flutter : callData native to dart gettime 1
(standard input):11-04 11:37:46.791 19951 19992 I flutter : callData native to dart gettime 1
(standard input):11-04 11:37:46.892 19951 19992 I flutter : callData native to dart gettime 2
(standard input):11-04 11:37:46.994 19951 19992 I flutter : callData native to dart gettime 4
(standard input):11-04 11:37:47.094 19951 19992 I flutter : callData native to dart gettime 3
(standard input):11-04 11:37:47.193 19951 19992 I flutter : callData native to dart gettime 2
(standard input):11-04 11:37:47.293 19951 19992 I flutter : callData native to dart gettime 3
(standard input):11-04 11:37:47.392 19951 19992 I flutter : callData native to dart gettime 2

@robert-wq : does this mean that in Flutter 1.22 everything is fast (1-4 ms) after a few slow calls in the beginning? The slow ones in the beginning might be expected as there's a lot of work to do during startup.

**Comment by lengzds** [comment]
I have meet the same problem and want to the reason.

**Comment by jonahwilliams** [comment]
The fix here is to use ffi instead of method channels. Upcoming support for ffigen/jnigen will make that even easier on mobile platforms.
