### ISSUE TITLE
Built-in Flutter Staggered Grid View?

### ISSUE THREAD

**Issue by jloLOLS** [flutter/flutter#69645]
Flutter beginner here. 

I need a GridView whose children have varying heights. People recommend that I use @letsar's [flutter_staggered_grid_view](https://github.com/letsar/flutter_staggered_grid_view). It's great, but it produces undesirable results if you were to run a Flutter project on a web browser. With its latest release, the grid does not respond appropriately when the window resizes, and it also does not show some of the children widgets if you resized the window to a certain width and height.

I probably should have reported an issue to its Github repository, but I think the developer abandoned the project. Its latest release was in January 2020, and since then, there have already been 21 Flutter beta SDK releases. It would be greatly appreciated if Flutter has a built-in staggered grid view widget.

**Comment by letsar** [comment]
Hi @jloLOLS 🙂. I didn't abandon the package. I just need a few days to refactor it. And since then I haven't had the proper time. (Day job, family, other side projects). Maybe in December.

**Comment by darshankawar** [comment]
@jloLOLS 
Since @letsar himself as responded on this issue and hinted to re-work on it, I'd suggest you to open this in plugin's repo so that he can keep track of the issue and you may follow-up for any updates directly.  I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
