### ISSUE TITLE
Prioritize frame creation over other async computation

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69694]
https://b.corp.google.com/issues/172325242 is the upstream bug.

cc @zanderso @chinmaygarde for visibility.

**Comment by zanderso** [comment]
Unrelatedly, we had some discussion about this a couple of weeks back. @chinmaygarde is already working on drafting a doc on this topic.

**Comment by chinmaygarde** [comment]
I am in the process of designing a reworking of the message loops right now. However, the solution won't involve indefinite deferral of results of async computation. So, if the async computation result workloads are high enough, there is still the possibility of these affecting frame generation. The guidance for such cases is and remains moving said workloads to a secondary isolate.

@mehmetf: Happy to keep this as P1 since I am working on it already, but just wanted to give a heads up that resolving this issue is not a silver bullet. We are only going to better organize the work we do on the root isolates threads, but we can only do a finite amount of work there. If this is a blocker for the customer, a parallel effort to move the work to a secondary isolate is recommended.

**Comment by mehmetf** [comment]
I don't think this is a blocker. P1 was part of an automated update since buganizer is seen as the source of truth for internal bug priorities. Downgrading back to P3 to reflect the true priority.

**Comment by chinmaygarde** [comment]
Initial proposal is at go/flutter-engine-task-prioritization

**Comment by zanderso** [comment]
Re-opening for revert.

**Comment by iskakaushik** [comment]
This was fixed in https://github.com/flutter/engine/pull/25789 and has rolled everywhere.
