### ISSUE TITLE
when page1 with TickerProviderStateMixin jump to page2 ,then page1 cause rebuild

### ISSUE THREAD

**Issue by chenchunhao9125** [flutter/flutter#69727]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by sidrao2006** [comment]
Hello @chenchunhao9125 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by darshankawar** [comment]
@chenchunhao9125 
There's no description / details in the issue you created. When opening an issue, please provide a minimal reproducible code sample that we can use to replicate the issue you are facing along with a description of what you are trying to do along with expected behavior. Also provide `flutter doctor -v`.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
