### ISSUE TITLE
iOS - not working when starting offline

### ISSUE THREAD

**Issue by MightyRai90** [flutter/flutter#69755]
If you start Admob in Offline (Airplane) mode. Initialize Interstitial and Rewarded. Then switch to online. 
Nothing works... 

Really bad if a user has no internet at the start. And never receive ads until the next app (cold) start. 

thanks!

**Comment by darshankawar** [comment]
@MightyRai90 
I am assuming you are using `firebase_admob` to implement ads. If yes, it seems to be an issue with the plugin and you may need to open this issue here : https://github.com/FirebaseExtended/flutterfire/issues
Closing this from here. If you disagree, write in comments and I'll reopen.
Thanks.
