### ISSUE TITLE
Testing not working properly after pana validation

### ISSUE THREAD

**Issue by Arunsanthoshh** [flutter/flutter#69875]
In simple flutter app, I have getting more issues when using the flutter test command, once pana validation done.

Issue replication steps--

Create a simple flutter app.
Use **flutter tes**t command in the terminal. (It has worked fine)
Use **pana** command in the terminal. (It will validate the corresponding project)
Then again using the **flutter test** command. (In this case, we have getting more number of issues)

_**Note --** Already created a issue on pana. Find the link here. https://github.com/dart-lang/pana/issues/798 But still no response from them._

**Comment by darshankawar** [comment]
@Arunsanthoshh 
I am assuming you are using pana library that analyzes packages. That seem to indicate the issue seem to be with the plugin and you were right to open the issue here : https://github.com/dart-lang/pana/issues
I'd suggest you to follow-up in that repo for updates and tracking.
Closing this from here. If you think the issue should belong to Flutter repo, write in comments and I'll reopen.
Thanks.
