### ISSUE TITLE
EarlGrey for Flutter uses private API on FlutterView

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#69928]
We should expose something public for synchronization so that it does not have to rely on private implementation details in FlutterView.

@albertwang0116 has more information on this.

**Comment by AlbertWang0116** [comment]
Sorry I missed this!

I revisited the synchronization code, and it is now using all public methods. There is only one place that EarlGrey is relying on Flutter's private API, on FlutterView.

The background is, EarlGrey needs to know which Dart isolate to talk. Dart isolate is exposed by [FlutterEngine](https://github.com/flutter/engine/blob/flutter-1.24-candidate.9/shell/platform/darwin/ios/framework/Headers/FlutterEngine.h#L353), whereas EarlGrey doesn't have access to FlutterEngine directly because FlutterEngine is not part of UI hierarchy. Instead, test code uses EarlGrey (native) matchers to find the target FlutterView, and EarlGrey will figure out the FlutterEngine that ties to the matched FlutterView at that moment. To achieve this, EarlGrey currently swizzles FlutterView and maintains a lookup table of {FlutterView -> FlutterEngine} mapping.

I'm not sure what's the right way for Flutter to expose this information. Just throw some ideas:

1. Flutter exposes a C API that takes id and returns FlutterEngine. If the input is a FlutterView and there is a FlutterEngine currently attached to it, returns that engine.

2. Flutter binds FlutterEngine instance to its attached FlutterView instance through [associated object](https://developer.apple.com/documentation/objectivec/1418865-objc_getassociatedobject?language=objc), and exposes the associate object key. This way is essentially the same as 1, but no C API is needed.

3. FlutterView exposes another semantic object under its accessibility tree, and expose the isolate ID through that object.

**Comment by dnfield** [comment]
@gaaclarke would probably have some good thoughts on this.

**Comment by zanderso** [comment]
From issue triage. Is there any update on this?

**Comment by gaaclarke** [comment]
There is a way you can get the FlutterViewController from the FlutterView by crawling up the responder chain: https://stackoverflow.com/a/24590678

Once you have FlutterViewController you can get the FlutterEngine.

**Comment by zanderso** [comment]
Since it sounds like the right public API is available, I will close this as not needing any further action from the Flutter team. Please feel free to re-open if I'm mistaken and there is still work for the Flutter team on this. Thanks!
