### ISSUE TITLE
How to change Facebook Audience Network Native ad layout to match my UI? 

### ISSUE THREAD

**Issue by TamlaHtoo** [flutter/flutter#70044]
I am using facebook audience network plugin [https://pub.dev/packages/facebook_audience_network](url) in my flutter app. But the thing is their provided Native ad doesn't match with my user interface. How can I change it to match my user interface? I can't open xml  Android Studio Layout Designer in flutter project.  

A snippet of Xml code to match my UI would be highly appreciated.

Here is my app UI and the Native ad.
https://i.imgur.com/z6cXABH.jpg

**Comment by EliasDeuss** [comment]
@TamlaHtoo This isn't really a flutter issue, you should file this on the packages GitHub repo not Flutters.

**Comment by iapicca** [comment]
@TamlaHtoo 
this repository is dedicated to improve flutter with bug reporting and feature requests,
if you have question I recommend you to follow `I want help writing my application` tab
on the [new issues menu](https://github.com/flutter/flutter/issues/new/choose)

I also noticed you already opened an [issue](https://github.com/dreamsoftin/facebook_audience_network/issues/74) in the 3rd party plugin repo;
I'm not sure is needed to duplicate the issue here

**Comment by pedromassangocode** [comment]
Hi @TamlaHtoo 
It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
