### ISSUE TITLE
Get request in bad format

### ISSUE THREAD

**Issue by EnmanuelAlx** [flutter/flutter#70127]
I have this problem
When I make the request to my backend, flutter receives the json with a bad format, as you can see in the image
But there are times when if you receive the request well and process it properly, the error is totally random. This happens mostly when the request result is large
Now, if I make the request by another means, such as postman or even the same browser, the request always comes in handy.

![image](https://user-images.githubusercontent.com/29907790/98595458-663e2480-22ac-11eb-996a-befe04138db7.png)

**Comment by darshankawar** [comment]
@EnmanuelAlx 
Not sure if this issue is related to Flutter framework, as you said `flutter receives the json with a bad format` which indicates the data in bad format could be coming from the backend you are calling. Flutter processes the json from the server / backend and then decodes it to render in UI. 

Please see https://flutter.dev/community for resources, you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
