### ISSUE TITLE
Complete mouse input for UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70199]
The majority of mouse handling is implemented in https://github.com/flutter/engine/pull/23573 with the exception of 

- mouse leave support
- Flutter cursor support
- right mouse button

which this issue now tracks.

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
