### ISSUE TITLE
Set up unit tests for UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70197]
From UWP doc notes:
- may require changes / additions to test infra to make this build correctly
- Figure out how to activate above runner as part of test automation (cannot be launched with regular shell execute)
- Enable disabled tests in shell\platform\windows\build.gn
- Add FlutterWindowUwp tests

**Comment by clarkezone** [comment]
I have got a test runner building and executing a subset of tests for the UWP target per the latest patch to https://github.com/flutter/engine/pull/23573 and this should be able to test any code in the UWP target that
1. uses WinRT API's that are compatible with the `WINAPI_FAMILY_PC_DESKTOP` partition or 
2. that can be mocked as in the case of `UWPFlutterWindow` where the dependency `CoreWindow`, which isn't compatible with `WINAPI_FAMILY_PC_DESKTOP`. _should_ be able to be mocked.

The initial set of tests being targeted will be:

      # "flutter_project_bundle_unittests.cc", //TODO failing due to switches test failing
      # "flutter_windows_engine_unittests.cc", //TODO failing to send / receive platform message get plugins working first
      "string_conversion_unittests.cc",
      "system_utils_unittests.cc",
      "testing/engine_embedder_api_modifier.h",

as well as "//flutter/shell/platform/windows/client_wrapper:client_wrapper_windows_unittests", and the aforementioned `UWPFlutterWindow` test.

**Comment by clarkezone** [comment]
Building the UWP test runner as a UWP console app may be the way to go: https://blogs.windows.com/windowsdeveloper/2018/05/18/console-uwp-applications-and-file-system-access/ looks like this might obviate the need for 3. above.  The only open question is how some of the interesting WinRT API’s behave in said app type eg https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.getforcurrentview?view=winrt-19041.  

Another different approach would be to attempt to dependency inject the tricky API’s used by `UwpFlutterWindow` so that it doesn’t directly depend on them.  That would enable the existing test infra to be used at the expense of having to mock more types.

**Comment by stuartmorgan** [comment]
The console app approach definitely sounds worth investigating further, since avoiding weird launch scripting would be very nice. Generally unit tests don't necessarily interact with displays well anyway (e.g., all our Linux unit tests are running without an X server, so lots of display stuff would fail there), so I'm not too concerned about having areas there that we'll need to avoid and/or do dependency injection for.

**Comment by clarkezone** [comment]
OK, good feedback.  The biggest unknown I'm facing in the immediate term is host best to mock out `CoreWindow`.  It has a large number of members so generating a manual mock will be very time consuming.  Looking into different approaches for code generating one.

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
