### ISSUE TITLE
Complete drawing for UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70198]
The majority of the implementation is landing in https://github.com/flutter/engine/pull/23573.  This issue now tracks the remainder:
- [X] Fix resizing so that it doesn't flicker; evaluate direct `CoreWindow` hosting vs `SpriteVisual`. ([PR: Windows: Improve window resizing](https://github.com/flutter/engine/pull/24428))
- [X] Verify DPI change is correct
- [ ] Handing system font changed correctly
- [ ] Destruction path

**Comment by clarkezone** [comment]
https://github.com/flutter/engine/pull/23573 references this issue

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
