### ISSUE TITLE
Implement key events for UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70202]
Specifically: 

- [x] Fix cursor keys and delete
- [ ] modifier keys likely using https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow.getkeystate?view=winrt-19041
- [ ] shortcut support
- [ ] handing unicode correctly
- [ ] handling UWP specific system keys like back
- [ ]  refactor `OnKey` method in WindowBindingHandlerDelegate to remove need for win32 magic values in UWP implementation
- [ ] remove action code from game_pad_cursor_winuwp.cc `OnGamepadButtonPressed` and `OnGamepadButtonRelased`
- [ ] make sure that once IME support is landed, that it behaves nicely with key events

**Comment by clarkezone** [comment]
Referenced in https://github.com/flutter/engine/pull/23573

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
