### ISSUE TITLE
Implement system channels in UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70214]
- [ ] settings
- [ ] clipboard support

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
