### ISSUE TITLE
☂ Add UWP support to the flutter tool

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70211]
Once we have a UWP embedding we'll need to add support for it in the tool. We can add sub-issues for some of these once we're closer, but at a high level:
- [x] Upload all the engine artifacts
- [ ] Add an app template
- [ ] Add a plugin template
- [x] Add a new experiment flag
- [ ] Add new requirements to `doctor`, if any
- [x] Add tool arguments for specifying UWP (and clarifying in help strings and such that the current arguments are for Win32)
- [x] Wire up the artifact download, UWP variant build, template inflation, etc. keyed off of that argument

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
