### ISSUE TITLE
Bring up build_test for UWP

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70213]
Once https://github.com/flutter/flutter/issues/70211 is done, we will need to bring up build_test. We should do that ASAP so we don't have to worry about build regressions (as happened for some of the other desktop embeddings due to the delay in getting the CI set up for it).

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
