### ISSUE TITLE
[pigeon] redirect pigeon resources to ffi

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#70254]
I've cross posted this in the ffi repo:
https://github.com/dart-lang/ffi/issues/58

@gaaclarke 

So I want to express what I'm sure will be a controversial opinion.

The nub of the idea is to drop the pigeon project and instead focus all resources onto ffi.

Background:

I'm the author of the Sounds project:
https://pub.dev/packages/sounds

One of the big issues we are grappling with is having to be across four development languages:
Dart
Java
Objective-C
Swift

This is a significant problem for getting resources applied to the project and has the core team bumbling around with languages that they just aren't familiar with.

We have been experimenting with ways to make the project easier to maintain.

The first thing we looked at was converting all of the objective-c to swift as swift is a simpler language and more 'dart' like than objective-c.
This helped some but we still had bits of objective-c left in the code for bridging purposes and we are still not swift experts (or even novices).

Next we had a look at pigeon for a couple of reasons.
1) we liked that it largely managed channels for us.
2) we hoped it would take care of some of the bridging code (not so much).
3) we liked the concept of a federated model (yes not pigeon specific but it helped).

We did an initial implementation with pigeon and the process actually helped us improve our platform api but it did nothing to reduce the no. of languages that we needed to support.

So we are now looking at ffi and dart-native.
https://pub.dev/packages/dart_native

The dart-native project is useful but still very primitive however its clear (to our team at least) that using ffi is a much better path than pigeon.

Once we complete the ffi work we should go close to eliminating all objective-c, swift and java code.
This will make our project much simpler to maintain and should make it easier to get additional contributors.

The biggest stumbling block is that, whilst dart-native, helps we are still having to implement ffi wrappers for large parts of the ios api (and currently all of the java api).

My view is that pigeon is really just a stop gap measure and long term I don't see pigeon being a part of the dart ecosystem.

As such I'm arguing that rather than wasting resources on a stop gap measure those resources would be better placed on completing ffi, improving the documentation and providing a complete set of ffi mappings for the ios and android apis.

I understand that this will be a large task but it is one that could be rolled out progressively and one that the community could easily contribute to by backfilling apis that they need them.

# Summary

* stop work on pigeon
* commence work on providing a full set of dart api wrappers for the android and ios libraries.
* improve the ffi documentation with more worked examples.
* Encourage the community to contribute api wrappers.

**Comment by gaaclarke** [comment]
Thanks @bsutton for writing out your thoughts.  Reducing the number of languages was never a goal for Pigeon since many plugins / add-to-app developers want to integrate with the platform libraries.  Only a subset of use-cases could be fully implemented with a host handler written in C/C++.  If you want to do that today I think you are right to consider FFI.  It was never a problem Flutter channels addressed and so by extension Pigeon didn't prioritize addressing it.

If we were to support that use-case in Pigeon we'd have to probably expose the Flutter channels API for C/C++ and create a new code generation target.  It gets a bit tricky on Android since the project needs to be setup correctly to compile and link in a C/C++ library.  I can throw up another issue so we can track that use case, but frankly the backlog for Pigeon is large I'm still working with many clients to figure out how to prioritize them.

Here's the use cases where FFI is the better choice over Pigeon today:
1) You want synchronous handling of host messages (this plans to be addressed at some point)
1) You want to call a C/C++ library on android (your use case, for the sake of sharing code)

**Comment by bsutton** [comment]
To be clear, my use case isn't to call a custom c/c++ library but rather to
make calls into the native sdk on each platform.

My post wasn't really about my own use case but rather the wider
communities use case.
We already have a path forward for our project but I see a significant
problem for flutter developers is the requirement to work in multiple
languages.

What I desire is a way to build any dart application/package without having
to write any native code (swift/object-c/java/c/c++).

FFI is the beginning of a way to achieve this.
Whilst I appreciate what you are trying to do with pigeon, my argument is
that it's a distraction from what the end goal should be - build any
flutter app in dart only.

My assumption was that you were part of the dart core team and hence I was
advocating that time on pigeon would be better spent on building on ffi to
provide complete access to the native apis.

**Comment by stuartmorgan** [comment]
> I see a significant problem for flutter developers is the requirement to work in multiple languages. What I desire is a way to build any dart application/package without having to write any native code (swift/object-c/java/c/c++). FFI is the beginning of a way to achieve this. Whilst I appreciate what you are trying to do with pigeon, my argument is that it's a distraction from what the end goal should be - build any flutter app in dart only.

It's not clear to me from your description how you've come to the conclusion that the languages themselves are the problem. There is a lot of complexity involved in understanding the API structures, SDK idioms, etc. for multiple platforms; language is only a portion of that. Importantly, the language the SDK is designed for is often strongly reflected in the APIs themselves.

As an example, consider [this code](https://github.com/flutter/plugins/blob/25957033132ac17094e82bec58e429fac073a483/packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart#L118-L141), which is from an FFI-based Windows implementation of a plugin. This code is not actually much more understandable to a Dart developer with no Win32 experience than the corresponding C code would be (and in some ways is actually more complex, because understanding it now involves knowing *both* Win32 idioms and FFI details). Language projections into Dart from a bunch of very different SDKs written for very different languages aren't going to solve those problems.

Your fundamental assumption here seems to be that writing platform-specific code against platform-specific SDKs in Dart is inherently superior to writing platform-specific code against platform-specific SDKs in the platform's standard language. Your team may find that to be the case, but teams with different structure/background are likely to have the opposite viewpoint. Which leads into the fact that:

> stop work on pigeon

is completely unrelated to:

> commence work on providing a full set of dart api wrappers for the android and ios libraries.
> improve the ffi documentation with more worked examples.
> Encourage the community to contribute api wrappers.

I encourage you to file issues that just provide specific details of things you want improved in FFI, rather than trying to approach this from the standpoint of trying to make project management/resource allocation requests, as doing the latter is just going to distract from evaluation of the merits and priority of the former.

**Comment by bsutton** [comment]
So firstly I think you may have somewhat mis-understood the objective.

I'm not looking for the typical developer to have to interact with FFI but
rather have a community effort to provide dart wrappers for the platform
sdk's (yes I know this is a large effort hence the community involvement).

Oddly enough my background is actually in win32/C development but these
days I'm a java/dart/javascript developer.

I don't agree that having to understand the idioms of something like win32
requires a deep understanding of C and I certainly wouldn't equate the
complexities of understanding an api with that of understanding a complete
language (or in the flutter cases a minimum of three languages). I've
worked professionally with something like 20 languages so I have some
understanding of the effort to get up to speed with a language compared to
that of an api.

I've been involved with numerous projects that do cross language
development (C->java, C-pascal, java->C, c->ole, java->ole, basic-> C,
dart->java, dart->swift, dart->c) as well as projects that simply use a
different backend language to a front end language.

My involvement in these projects has been both as a project manager and as
a developer.

As a more recent example we are currently porting the Sounds project from
ObjectiveC/swift to ffi.
We have most of the ios platform calls mapped into ffi and the team is
already reporting productivity improvements.
The team is now saying it is easier to maintain the ios code than the
android code (android is still using pigeon at this point). The team has no
real swift/objective-c experience.
Previously it was the other way around (android was easier than ios).

The general process is that you build wrapper classes for each of the
foreign api interfaces and then you can forget about them.
So I would strongly disagree your statement that:
'Language projections into Dart from a bunch of very different SDKs written
for very different languages aren't going to solve those problems.'

The above noted experience of our team also goes against this statement.
(if the statement was correct, moving to ffi should have made the ios
support harder).

I don't see any api as more difficult than another, just because it was
written in a different language. You deal with the type mappings and the
memory management and then you are simply dealing with yet another api.

There are almost no scenarios where developing a project in different
languages is more efficient than developing in a single language. I've
worked cross language many times, on many projects, it's simply expensive.
The exceptions to this revolve around existing code bases and human
resources. The FFI path still allows these teams to develop in their
language of choice.

The two issues (pigeon vs wrappers for ffi) are not unrelated.
Both have the single objective of making calls from dart into platform code.

The path I'm suggesting makes the pigeon project obsolete and will provide
a huge boost to the flutter communities productivity.

I do agree with your statement that requesting a resource re-allocation is
a risky path forward (as you note it can distract from the core premise) on
the other hand we should be able to talk about what is best for the flutter
community in an open manner.

**Comment by stuartmorgan** [comment]
> I'm not looking for the typical developer to have to interact with FFI but rather have a community effort to provide dart wrappers for the platform sdk's (yes I know this is a large effort hence the community involvement).

This is essentially equivalent in scope to the entire Flutter plugin ecosystem, and so isn't at all comparable to Pigeon. Given that, I'm even less clear on why you are trying to make this about stopping work on Pigeon.

What, exactly, is your specific, actionable request to the Flutter project here?

> I don't agree that having to understand the idioms of something like win32 requires a deep understanding of C

Having watched Flutter developers who have never used a C-like language try to understand the calling semantics of Win32 APIs, we'll have to agree to disagree here.

> The general process is that you build wrapper classes for each of the foreign api interfaces and then you can forget about them. So I would strongly disagree your statement that: 'Language projections into Dart from a bunch of very different SDKs written for very different languages aren't going to solve those problems.'

Well, that's not really disagreeing; what you are describing is not a language projection. I thought you meant actual language projections, since you were suggesting it as a replacement for Pigeon.

> The two issues (pigeon vs wrappers for ffi) are not unrelated. Both have the single objective of making calls from dart into platform code.

They are not unrelated, but as I mentioned above they have dramatically different scope.

> on the other hand we should be able to talk about what is best for the flutter community in an open manner.

Separating highly separable requests does not reduce the openness of discussion. We use the issue tracker to track and prioritize bugs and feature requests, which are *inputs* to resource allocation. "Stop working on pigeon" is neither, so the issue tracker isn't the right place for that discussion. Given that, I don't see any outcome for this other than being closed as not relevant to the issue tracker if you focus the discussion on that.

If, on the other hand, you can provide concrete feature requests, those can be considered (and prioritized against other efforts, including but not limited to, Pigeon).

**Comment by bsutton** [comment]
So for a moment let's accept your premise that dart developers will have trouble understanding c/windows or objective/ios.

Pigeon does not solve this problem.

With pigeon you require developers to understand pigeon/objective-c/ios libraries.

With ffi you only require the developers to understand ffi/ios libraries.

So how can pigeon be a better solution? Developers must still understand the ios api as well as 'Objective C'.

Of course it's actually worse than that.
With pigeon you actually require developers to understand pigeon/objective-c/java/platform libs. And thats with only two target platforms. How many more languages will be required to deal with all of the target platforms. Javascript,C#,....

With ffi you only require ffi/platform libs.

Once the wrappers are built (either in pigeon or ffi) then you are completely in dart land so it makes no difference after that.

With the cross language projects I've worked we normally assign a single resource to create the wrappers.
After that person comes up to speed with the rules of wrapping an object or function this process is largely boiler plate code.
If the core dart team needs access to a new api the ask the api guy to add a new wrapper.

The dart-native project is actually trying to automate this process and does a moderate job of generating wrappers for ios.

So now we have changed our project from needing skills in dart/java/objective-c/C/JavaScript/C#/platform libs to dart/platform libs with a single resource required to manage the api calls (even on a large project this is usually only a part time job and after the front loading its often only a couple of hours a week). I've been this resource on multiple projects.

You then start to get a compounding effect with the dev team. As everyone is using the same language your teams overall skills set in dart grows much faster as everyone can help everyone else.

You then get to share all of your code. With Sounds there are significant amounts of code that is 'common' across ios and android but has to be written twice. With ffi these will collapse down to a single code base.

> equivalent in scope to the entire Flutter plugin ecosystem

There is no intent to replace the flutter ecosystem. Part of the reason for the community involvement is to ensure that we implement wrappers for the pieces we need to fill out the missing bits of flutter (e.g. sounds). My preferred path is actually the creation of automation tools that generate the wrappers. But having a project that exposes commonly used apis would be extremely useful.

I'm not certain what you mean by the term 'language projection'? When I create a wrapper for ffi the aim is to make the api as 'dart' native as possible. For instance a 'C' string should always be converted to a Dart string at the wrapper interface. Users of the wrapper libraries shouldn't have to be concerned with platform specific types (e.g. uint8 or pointers).

> dramatically different scope.

This I disagree with. The core objective of both technologies is to call platform apis, everything else is an implementation detail.

> which are inputs to resource allocation. "Stop working on pigeon" is neither

This issue is exactly that. 'inputs to resource allocation'.

The problem is that you are taking a periocial view of this issue.

When you look at the ffi/pigeon as single development effort (make it easy to call platform apis) then this feature request is about redirecting resource like every other bug/feature request is.

The feature requests here is to achieve the most optimal path to making platform specific calls.

The fact that this requests covers off two project seems to be part of the difficulty in accepting the point of this issue.

Rather this issue should be viewed as a feature request that is asking the two development team to stop and reflect on what the ultimate goal is and combine their resources.

The discussions here suggest to me that there hasn't been sufficient consideration of where pigeon and ffi will end up and a lack of understanding of what the real goal is.

I will raise a second issue on the ffi project to automate the creation of wrappers and to create a per platform package that exposes commonly used apis.  But my core request in this issue - to cease pigeon development - stands.

Hopefully we can see past the 'sunk costs fallacy' and stop for a moment and look at the bigger picture.

My point here is not to be derogative of the work done with pigeon but to point out that it has become redundant and that there is a better pathway forward.

**Comment by stuartmorgan** [comment]
> > which are inputs to resource allocation. "Stop working on pigeon" is neither
> 
> This issue is exactly that. 'inputs to resource allocation'.

Please don't selectively edit my comments to change their meaning. What I said was "We use the issue tracker to track and prioritize bugs and feature requests, which are inputs to resource allocation. "Stop working on pigeon" is neither". As in, neither a bug report nor a feature request.

> But my core request in this issue - to cease pigeon development - stands.

As I've said above, the issue tracker is not the right place for that conversation. If that's the core request here, then closing per my comment above.

If you have concrete suggestions for improving FFI, please file them.

**Comment by bsutton** [comment]
Can you please re-open this issue as closing it at this point in the conversation is poor form.

I didn't selectively edit you comment to changing the meaning. I selected the core piece of text to try and get you to understand that issues are all about resource allocation which is exactly what I'm talking about.

From my perspective you are currently driving a bus over cliff  (yes a little melodramatic) and I'm saying 'hey let's stop the bus' and your saying 'if your not going to help steer the bus over the cliff then your not helping'.

> the issue tracker is not the right place for that conversation

If the issue tracker isn't the right place then where is? This is the only forum that I'm aware for long form conversations over this sort of issues. And as I've said before this is all about resource allocation so it is the correct place.

I also note that you haven't responded to any of my points regarding your arguments supporting pigeon.

**Comment by stuartmorgan** [comment]
> Can you please re-open this issue as closing it at this point in the conversation is poor form.

I've explained that the conversation you want to have is off-topic for this forum, which is why it's closed.

> to try and get you to understand that issues are all about resource allocation which is exactly what I'm talking about.

You can of course use issues however you like in your own projects, but as I've said several times, we don't use the issue tracker as a discussion forum for resource allocation.

> If the issue tracker isn't the right place then where is?

The flutter-dev mailing list seems like a reasonable option, or there are various other general discussion forums (e.g., r/FlutterDev, Medium) where you could pitch your viewpoint on how the Flutter community should allocate engineering resources.
