### ISSUE TITLE
99th_percentile_frame_build_time_millis	new_gallery__crane_perf regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70300]
https://flutter-flutter-perf.skia.org/e/?begin=1604649491&end=1605078243&keys=X79977886e5d56b92be2a53faf431ee5d&requestType=0&xbaroffset=22452

Why would https://github.com/flutter/flutter/pull/70130 cause this? Is this benchmark tested with the gallery?

**Comment by jonahwilliams** [comment]
We rolled the gallery, so we got a different version of it. A change in perf is a possible outcome - its not even necessarily a flutter regression.

**Comment by zanderso** [comment]
@kf6gpe it looks like there is a gap in the Skia perf graph. Does that indicate that the benchmark didn't run on some commits? /cc @liyuqian

**Comment by blasten** [comment]
I was a bit surprised by the increase in build times. Maybe, the removal of pubspec.lock had the most impact. This benchmark will be noisy until pubspec.lock is added back. The issue though is that the dependencies should be resolved based on what version of Flutter is used.

**Comment by kf6gpe** [comment]
Ah, thanks @jonahwilliams for the explanation. I wasn't sure if the gallery was implicated in that test. Makes sense!

**Comment by liyuqian** [comment]
The regression is likely caused by the Gallery code changes between https://github.com/flutter/gallery/commit/53462151bf753dc70284be9274a798fa485265f2 and https://github.com/flutter/gallery/commit/8542ca8beebc8e989adee160f7f1f0841a734db2 . CC @guidezpl to see if the regression is unexpected from Gallery's perspective.

@kf6gpe : we probably should document in our performance regression handling doc that if perf regression is caused by a Gallery version roll, we should notify @willlarche's team for triage as we did in https://github.com/flutter/flutter/issues/66989.

@zanderso : the gap is caused by test failures of https://flutter-dashboard.appspot.com/#/build?taskFilter=new_gallery__crane_perf between 21e802746b15377a6bd46651fd5e9331d7ca887a and 6e5845f0253f5574c0bd059808650b2d419260bb

**Comment by guidezpl** [comment]
4 new demos were added and some state restoration was added to the Reply study, so this isn't totally unexpected to see an impact, however almost 2x is surprising.

**Comment by zanderso** [comment]
@blasten Why would a pubspec.lock file affect 99th percentile frame build time?

The regression is in the range of commits that includes migrating the gallery to null safety https://github.com/flutter/flutter/commit/21e802746b15377a6bd46651fd5e9331d7ca887a, but we are missing data from skia perf for that commit.

We need to verify that this regression is not caused by the null safety migration. Returning to P0 and assigning @blasten for that.

**Comment by jonahwilliams** [comment]
This is a different gallery

**Comment by jonahwilliams** [comment]
To clarify further, this was not a regression caused by NNBD - the flutter/gallery is a different application. By rolling to a new version of it, we started measuring something different (because it is under development)

**Comment by blasten** [comment]
correction: I misread the task name as just build time of the AOT/JIT code. (I've been debugging those).. pub packages don't affect FRAME build times.

**Comment by blasten** [comment]
While testing locally on Android 10/Pixel 2, I got these results:

 new_gallery__crane_perf:

https://github.com/flutter/gallery/commit/8542ca8beebc8e989adee160f7f1f0841a734db2 (Current HEAD)

Attempt 1: **99th_percentile_frame_build_time_millis**:  17.477
Attempt 2: **99th_percentile_frame_build_time_millis**:  14.263

https://github.com/flutter/gallery/commit/53462151bf753dc70284be9274a798fa485265f2

Attempt 1: **99th_percentile_frame_build_time_millis**: 17.618
Attempt 2: **99th_percentile_frame_build_time_millis**: 24.124

This suggests that the`99th_percentile_frame_build_time_millis` didn't regress by ~2x as pointed out. I'm not sure if this useful, but I'm unable to reproduce this regression.

**Comment by liyuqian** [comment]
The regression number may depend on the device. The device lab uses Moto G4 which is significantly weaker than Pixel 2. @kf6gpe do you have any spare Moto G4 to send out for future perf regressions like this? I also wonder if we shall document in the perf regression handling doc like this "_Find a Moto G4 to reproduce Android perf regression; if you can't find one, please feel free to buy one from Amazon with the gCard._"

**Comment by blasten** [comment]
I don't have a Moto G4, but I tested on a G7, and the trend was similar:  

flutter/gallery@8542ca8
Attempt 1: 53.424 
Attempt 2: 34.694

flutter/gallery@5346215
Attempt 1: 94.145 
Attempt 2: 69.48

**Comment by kf6gpe** [comment]
I have one G4 left I'm happy to send out. Let me know who wants it (reach me on my Google email) with an address and I'll get it shipped!

I'll talk to people at Google about ordering and expensing a few more. I certainly don't see a problem with that.

**Comment by guidezpl** [comment]
Tested on a Moto G4 (with flutter@1.26.0-2.0.pre.129):

flutter/gallery@8542ca8 (rolled HEAD, from flutter's perspective)
Attempt 1:  55.2
Attempt 2: 52.2

flutter/gallery@5346215
Attempt 1: 46.6
Attempt 2: 47.5

Out of curiosity, current HEAD
flutter/gallery@HEAD
Attempt 1: 65.2
Attempt 2: 60

I don't understand how the device lab Moto G4 would be seeing about 80
