### ISSUE TITLE
Would like the dashboard to surface infra failures as purple and not close the tree

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#70331]
Since Infra failures are likely not caused by changes in flutter/flutter either closing the tree or marking the square as a failure may be misleading.

Consider surfacing this as a new failure type at a minimum, and otherwise adjusting the build logic so that they either
1. Do not close the tree or
2.  Do not close the tree when rerunning

**Comment by godofredoc** [comment]
Can you please add example builds? the current issue is anything unexpected coming from builds and tests e.g an exception from the test runner, test runner leaking processes show up as infra issues.

Not closing the tree in the current state would be equivalent to not closing the tree on flakes which may be dangerous.

**Comment by jonahwilliams** [comment]
Commented in chat too, but there were multiple failures yesterday from the -9 issue on macOS, this kept the tree closed for 2-3 hours for reruns

**Comment by godofredoc** [comment]
@CaseyHillers will take a look for the dashboard presenting builds as purple for infra failures.

**Comment by CaseyHillers** [comment]
The current Flutter tree policy closes on reruns (flakes). We can modify the policy to be more specific to only close the tree on reruns of failures. However, Cocoon does not currently have the previous status information to be able to make those decisions.

Cocoon needs to track the status for every task attempt (https://github.com/flutter/flutter/issues/47018).

**Comment by CaseyHillers** [comment]
The build dashboard is now surfacing these infra failures as purple instead of red. For the time being, these still act as failures for the tree status policy.

We would like to give some soak time to observe what's being marked as an infra failure before allowing these to ignored by the tree status.

**Comment by godofredoc** [comment]
Is this only the -9 or anything reported as infra failure by luci is painting the dashboard purple?

**Comment by CaseyHillers** [comment]
> Is this only the -9 or anything reported as infra failure by luci is painting the dashboard purple?

Since purple closes the tree, these builds are rerun. Only 3 are left as purple (due to backfilling).

[Mac retcode -9 example](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_custom_host_app_name_test/904/overview)
[Bot died](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20build_aar_module_test/896/overview)
[collect timeout](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests/1258/overview)

I need to update BigQuery to upload infra failures to make it possible to triage. We could use the Flutter LUCI console as well.

From these results, they seem like expected infra failures. The collect timeout should be reduced as it spent 1 hour running.

**Comment by jmagman** [comment]
> Since purple closes the tree, these builds are rerun. 

Is that true?  I just checked this morning and the tree was closed on 2 tasks that were purple due to the retcode -9 issue and they weren't re-run.

**Comment by godofredoc** [comment]
This has been addressed as retries of infra failures.
