### ISSUE TITLE
flutter preferences reset on installing new version on device

### ISSUE THREAD

**Issue by petkoivanov** [flutter/flutter#70344]
Its not a huge problem per see, but quite an inconvenience.

## Steps to Reproduce

when i build my new version:
1. flutter build apk
2. copy it to my physical phone via : flutter install -d XXX
3. all my preferences from previous usage are gone

They are there when i open/ close the app, restart my phone/ etc.
Any ideas?
(i know this is super generic but i literally dont do anything fancy, just write a bunch of strings to strings).
I search around a lot, could not find it on the forums and i hit this a lot so I must be doing something wrong, just not sure what.

**Expected results:** 
Preferences should be there after update via flutter command.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

Analyzing lib...

   info • Name non-constant identifiers using lowerCamelCase • main.dart:23:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:24:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:25:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:26:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:204:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:205:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • main.dart:206:14 • non_constant_identifier_names
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: LearningModule.folderName,
          LearningModule.fullFolder, LearningModule.resources, LearningModule.hasIntro, LearningModule.hasModuleIcon • main.dart:207:7 • must_be_immutable

8 issues found. (ran in 4.2s)

petko@petkos-iMac lib % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

[✓] Connected device (1 available)

</details>

**Comment by TahaTesser** [comment]
Hi @petkoivanov 
You can update the existing app by installing APK directly (Copy to the device or Send it via Google drive) instead of running the command, it would uninstall the existing app and delete  your app data and install it with a new APK

Here it uninstalls the old version, you can't preserve any app data. This is working as intended.
```bash
PS C:\Users\taha\AndroidStudioProjects\triage\flutter_plugin_examples\shared_preferences_example> flutters install -d rmx
Installing app.apk to RMX2001...
Uninstalling old version...
Installing build\app\outputs\flutter-apk\app.apk...   
```

Instead, install the  APKd irectly  to update 
![Screenshot_2020-11-12-16-12-49-34](https://user-images.githubusercontent.com/48603081/98930171-44d67600-2502-11eb-8676-edb05c01484e.jpg)



Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by petkoivanov** [comment]
ok understoood, make sense. it would be great if the flutter install behaved like installing the APK.
Also i dont always lose the preferences, may be 2/3 of the time so sometimes they get preserved , sometimes not. Which was of course, even worse.

**Comment by TahaTesser** [comment]
@petkoivanov 
In my testing, it resets every time, not sure how it's preserved for you
