### ISSUE TITLE
AlertDialog title cuts of bottom of text when you add an emoji 

### ISSUE THREAD

**Issue by odonc** [flutter/flutter#70356]
## Steps to Reproduce
Add an emoji into an AlertDialog popup title, bottom of text title gets cut off. 
See [dartpad. ](https://dartpad.dev/09932364ad1de4e4936545bd7fc5d31e)

**Expected results:** 
Text doesn't get cut off.

**Actual results:** 
Text gets cut off at bottom.

**Comment by darshankawar** [comment]
This is happening due to the multi-byte characters emojis comes with. There's similar open [issue](https://github.com/flutter/flutter/issues/70181) describing your case which has similar root-cause. Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
