### ISSUE TITLE
Flutter attach不可用

### ISSUE THREAD

**Issue by Victory886** [flutter/flutter#70516]
flutter sdk 1.7.8版本升级到1.16.3 之后flutter attach 不能使用了【Waiting for a connection from Flutter on XXX】报这个错误
还请Flutter 开发团队指点一二，万份感谢~

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
