### ISSUE TITLE
Memory leaks when starting foreground service

### ISSUE THREAD

**Issue by beingcoderr** [flutter/flutter#70526]
## Steps to Reproduce

1. Start foreground service in native platform android using startForegroundService().
2. Exit the application. Remove app from recent.
3. Reopening the app again and again causing memory leaks.

**Expected results:** No Memory Leaks

**Actual results:** Memory Leaks

<details>
  <summary>Logs</summary>

```
```

```
```

```[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_IN)
    • Flutter version 1.22.3 at /opt/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/digibyte/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

</details>

![MemoryLeak](https://user-images.githubusercontent.com/28594823/99141783-aae30a80-2674-11eb-8517-4f5c6a0735e2.png)

forService in the intent used to start service

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
