### ISSUE TITLE
I want to remove this duplicated Android Studio on macOS

### ISSUE THREAD

**Issue by Da-Vinci10** [flutter/flutter#70528]
mohamedfahmi@Mohameds-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at
      Users/mohamedfahmi/Library/Android/sdk/Contents
[✓] VS Code (version 1.51.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
@Da-Vinci10 you may want to consider asking this question on stackoverflow
since doesn't have much to do with flutter's repo

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
