### ISSUE TITLE
While I using android studio for flutter, I  could not able to inject "crossAxistAlignment" to Column widget, It shows me error

### ISSUE THREAD

**Issue by Opshanka** [flutter/flutter#70541]
Column(
                      children: [
                        Container(
                          child: Text(
                            tx.title.toString(),
                            style: TextStyle(
                              fontSize: 24.0,
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        Container(
                          child: Text(
                            tx.date.toString(),
                            style: TextStyle(
                              color: Colors.grey,
                              fontSize: 12,
                            ),
                          ),
                        ),
                      ],
                    )

**Comment by timsneath** [comment]
We're closing this issue because it seems to be a question or request for help rather than a clearly reproducible bug, regression or new feature request.

Good places to ask questions or work through problems where you're more likely to get a fast response include:

- [Stack Overflow](https://stackoverflow.com/tags/flutter)
- [Gitter](https://gitter.im/flutter/flutter)
- [Flutter Community Slack](https://fluttercommunity.dev/joinslack)

Thanks for using Flutter!
