### ISSUE TITLE
Pub not respecting PUB_CACHE inside docker container

### ISSUE THREAD

**Issue by James-Darko** [flutter/flutter#70552]
The Flutter command-line utility is not properly respecting `PUB_CACHE` env variable within a docker container I created. It's instead storing the cache in /root/.pug-cache, which is creating file permission problems. 

I complete reproduction can be found here https://github.com/James-Darko/flutter-cli/tree/flutter-pub-bug

Clone and run `deploy.sh`.This assumes a Linux host and a docker installation. After `deploy.sh`, run `fl build web` where the working directory is the root of a flutter application. 

`deploy.sh` stores `fl` in /usr/local/bin/ if you want to cleanup afterward. There's also the docker images, of course.

My host is Ubuntu 20.04. It's a very simple build. If you're on another OS, you should be able to adapt the re-creation easily. 

Workaround: Uncomment `flutter pub get` in `entrypoint.sh` and rebuild the `Dockerfile`. Flutter then respects `PUB_CACHE` while running `fl build web`. 

As an aside, I don't know why Pub is trying to use /root/.pub-cache to begin with. Perhaps I'm just missing something there. 

Let me know if y'all need any more info.

**Comment by pedromassangocode** [comment]
Hi @James-Darko 
Since PUB_CACHE is a pub command env variable I will suggest you to file an issue in the Pub [repository](https://github.com/dart-lang/pub).

See for few more information https://dart.dev/tools/pub/environment-variables.

**Comment by pascalw** [comment]
I'm running into this as well and it seems like it might be specific to Flutter, not dart/pub.

I'm running Flutter in Docker for CI purposes. `flutter pub get` is failing because it tries to store/read from the pub cache in `/root/.pub-cache`, even though I'm not running as the root user. `dart pub get` does work as expected and correctly uses the pub cache in `$HOME/.pub-cache`.

I'm on `1.23.0-18.1.pre` for this project. I'm running the exact same configuration with Flutter 1.22.2 and there things are working as expected.

@pedromassangocode is there any way that this might be an issue in Flutter itself?

**Comment by pascalw** [comment]
This is my environment:

```
ANDROID_SDK_TOOLS_VERSION=6609375
HOSTNAME=461779246ee2
LANGUAGE=en_US:en
ANDROID_PLATFORM_VERSION=29
FLUTTER_HOME=/sdks/flutter
PWD=<REDACTED>workspace
JENKINS_UID=112
ANDROID_BUILD_TOOLS_VERSION=28.0.3
HOME=/home/jenkins
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
ANDROID_HOME=/opt/android-sdk-linux
TERM=xterm
FLUTTER_VERSION=1.23.0-18.1.pre
SHLVL=1
ANDROID_SDK_ROOT=/opt/android-sdk-linux
FLUTTER_ROOT=/sdks/flutter
LC_ALL=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk-linux/cmdline-tools/tools/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/emulator:/sdks/flutter/bin:/sdks/flutter/bin/cache/dart-sdk/bin
_=/usr/bin/env
```

**Comment by pascalw** [comment]
Hmm after further inspection the issue seems to be that running `flutter pub get` in my project runs `flutter pub get` inside of the Flutter SDK directory. My Docker image is based on https://github.com/cirruslabs/docker-images-flutter which installs the Flutter SDK as root, so `/sdks/flutter/packages/flutter_tools/.dart_tool/.packages` and `/sdks/flutter/packages/flutter_tools/.dart_tool/package_config.json` contain references to `/root/.pub-cache`.

**Comment by pascalw** [comment]
@pedromassangocode I don't think anything is wrong here. The reason that `dart pub get` worked for me, but `flutter pub get` doesn't is that `dart pub get` only resolves direct dependencies from my project and `flutter pub get` also resolves dependencies of `flutter_tools` - which in my case where unintentionally owned by `root`.

**Comment by pedromassangocode** [comment]
Ok, closing then.
