### ISSUE TITLE
Regression in BM_ParagraphBuilderLongParagraphConstruct & BM_ParagraphBuilderShortParagraphConstruct

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70623]
See https://flutter-engine-perf.skia.org/e/?begin=1605297782&end=1605337933&keys=Xc483e651421937ea72290db129340d6c&num_commits=50&request_type=1&xbaroffset=20241.

Looks like it occurred when we did the ICU roll https://github.com/flutter/engine/pull/22465

**Comment by chinmaygarde** [comment]
Jason is taking a look at this related to the ICU roll.

**Comment by jason-simmons** [comment]
The increase in this benchmark happened because constructing an ICU line break iterator is taking noticeably more time after the roll to ICU 68.1.

Each call to `icu::BreakIterator::createLineInstance` is creating an `RBBIDataWrapper` object based on the breaker rules in the ICU data file.  It looks like this is slower in ICU 68.1 because of a UTF-8 string conversion in `RBBIDataWrapper::init`.  This is now required due to a change in the rule format intended to reduce its size (see https://github.com/unicode-org/icu/commit/c5ebb80a73b07b8eeb5b8365adc67cd84ad102d6)

The `Paragraph` constructor in Flutter/Libtxt creates an ICU break iterator.  The BM_ParagraphBuilderLong/ShortParagraphConstruct benchmarks are showing a large increase because they construct `Paragraph` objects but do not run layout.  So most of the time in this benchmark is just spent creating the ICU iterators.

This will be less noticeable in real applications because they will call `Paragraph::Layout` and other `Paragraph` APIs instead of immediately discarding the `Paragraph` as this benchmark is doing.  So slower ICU performance will have a smaller percentage effect on the total time spent in text construction/layout/painting.

However, we should investigate ways to improve this.  Libtxt could potentially cache and reuse a line breaker instead of paying the cost of processing the breaker rules data on every paragraph.  We should also look into how SkParagraph is managing its ICU breakers.

**Comment by kf6gpe** [comment]
Given @jason-simmons comment, I'm going to downgrade this to a P3, because it's less likely to be visible in real-world applications. Feel free to upvote/reprioritize if I'm wrong.
