### ISSUE TITLE
Support secret storage for local_auth

### ISSUE THREAD

**Issue by html-rulez-d00d** [flutter/flutter#70789]
## Use case

Using biometrics to return a boolean seems less secure than using a secure storage option to store a secret the backend can validate. I understand you can use a separate plugin to handle the storage process once local_auth authenticates the user but that route will leave an exploitable gap in security. The main use case for my team would be during the log in process for our app.

## Proposal

I would like the existing local_auth plugin to support the option to set a secret and upon successful biometric authentication, return said stored secret to be handled by the app's backend for validation.

Example:
```
//Once its determined device is bio auth capable, backend provides a secret to store for next login
await local_auth.setSecret('secret_abc');

//local_auth authenticates biometrics before returning secret:
String secret = await local_auth.getSecret(); //Operates exactly like authenticateWithBiometrics() but returns the secret vs a boolean

//If at any point you want to nuke the secret
await local_auth.clearSecret();
```

**Comment by pedromassangocode** [comment]
> Using biometrics to return a boolean seems less secure than using a secure storage option to store a secret the backend can validate.

Flutter tries keep any first-party package as flat as possible and this may not be a common use-case to be implemented in the core of the package.

> I understand you can use a separate plugin to handle the storage process once local_auth authenticates the user but that route will leave an exploitable gap in security. The main use case for my team would be during the log in process for our app.

You can create a brand new plugin with such feature to avoid the security issue. This package is open-source and can be freely forked and extended.

I'm not sure if this would be a great addition for the package in question since this doesn’t seems to be a common use-case. The `local_auth` package is expected to wrap only the native approach from the host platform and this use-case goes beyond the basic of local authentication feature.

**Comment by html-rulez-d00d** [comment]
@pedromassangocode Thanks for the quick response! 

I guess this new feature seems rather obvious to me as an inclusion to any authentication process. It boils down to accountability. You simply cannot take anything for its word without a cross reference, hence validating the secret with the backend. Otherwise a hacker just reverse engineers the app, modifies the bio_auth variable with an always true value for unlimited access. Without accountability in a security based plugin, it appears incomplete; hence the request.

**Comment by pedromassangocode** [comment]
Cc @cyanglaz
