### ISSUE TITLE
Docs feed URL missing for stable version

### ISSUE THREAD

**Issue by jcelliott** [flutter/flutter#70810]
I was trying to add the Flutter docs to Dash and realized the stable docs are missing the feed URL.

This file exists: `https://master-api.flutter.dev/offline/flutter.xml`
But this does not: `https://api.flutter.dev/offline/flutter.xml`

It was difficult to track down where those files actually were because they aren't mentioned in the docs anywhere. I believe doc viewers like Dash, Zeal, others are fairly popular, but people may not be finding the Flutter docs since they aren't in the "official" distribution sources that those viewers use. I'd be happy to create a PR to link to those in the flutter docs if we have an official stable feed to link to.

**Comment by fl0gic** [comment]
Been experiencing this too, not sure if it's useful, but the logs for the [latest stable build](https://cirrus-ci.com/task/5231061103804416?command=main#L235) (failed) vs. those for the [latest successful build](https://cirrus-ci.com/task/4591877150212096?command=main#L251) are slightly different for the docs-linux task.

**Comment by darshankawar** [comment]
I tried accessing both the links mentioned in original post and was able to download the files as mentioned in respective urls:

<img width="500" alt="Screenshot 2023-01-27 at 5 02 14 PM" src="https://user-images.githubusercontent.com/67046386/215076589-6c4ba8e5-a293-45fb-80dd-045abeeba48d.png">

Optimistically closing this as resolved since this is quite an old issue. If anybody disagrees, please write in comments and I'll reopen it.
