### ISSUE TITLE
video_player h.264 bitstream as input 

### ISSUE THREAD

**Issue by tobisweb** [flutter/flutter#70821]
Hello,
I was wondering whether it is possible to pass a **h.264 bitstream as input to the flutter_video_player** ? And if yes, how it could be done.

The reason I need to do this is because I want to _receive a stream using the [srt protocol](https://www.haivision.com/products/srt-secure-reliable-transport/), _which is currently not supported by the [video_player](https://pub.dev/packages/video_player).
My first approach was to store the incoming stream as temp file and pass its reference to the player. But it didn't work so far.
I would really appreciate any help.

**Comment by pedromassangocode** [comment]
Hi @tobisweb 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Cc @cyanglaz because maybe something here may be considered as proposal!?

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
