### ISSUE TITLE
Create a Gallery Android test that we can run on Saucelabs Real Device Cloud

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7087]
See:
https://saucelabs.com/devices
https://wiki.saucelabs.com/display/DOCS/Real+Device+Testing

Related #7088

**Comment by yjbanov** [comment]
@jason-simmons successfully demonstrated that this is possible by running the hello_services example on Saucelabs and Firebase. Closing this.

**Comment by brianegan** [comment]
@yjbanov @jason-simmons Do either of you have a sample project or any info to share on this topic? I'd love to run my app on SauceLabs as part of a CD pipeline, but have only been able to run unit / widget tests.

**Comment by jason-simmons** [comment]
A long time ago I did some experiments running Flutter apps on cloud testing services, but that work just involved running standard Android instrumentation tests with apps that used Flutter.  I haven't tried to use `flutter drive` on a hosted service.

**Comment by yjbanov** [comment]
I created an instrumentation test that uses a subset extracted from `FlutterDriver` extension to run the test. Here are the relevant files:

 - https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_gallery_instrumentation_test.dart
- https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test/live_smoketest.dart

**Comment by yjbanov** [comment]
We run this test regularly in the devicelab, so it should be good to go if you want to try it in SauceLabs.

**Comment by brianegan** [comment]
Thanks for the info!

**Comment by mmcc007** [comment]
@brianegan FYI: I got @yjbanov's example running on SauceLabs. You can see it running on:
https://travis-ci.com/mmcc007/test_flutter_saucelabs/builds/102025976
and a video and logs on:
https://app.saucelabs.com/tests/0953cb723204478ab206b7b8f0097554/watch

This kind of instrumentation test (using espresso) uses test code that does not work with flutter driver. It would be nice if we could run flutter driver directly! 

@yjbanov @jason-simmons  Are there any plans to get flutter driver to work on SauceLabs, Firebase, AWS Device Farm, etc... (ie, vendors that provide hardware accelerated android emulators and real devices as a service). 

The problem is android emulators in the cloud are practically unusable due to lack of hardware acceleration (whereas iOS simulators seem to work fine)... and writing flutter-specific espresso tests in place of flutter driver tests seems like more that a minor inconvenience.

BTW: I was able to get flutter driver working on AWS Device Farm by shoe-horning it into an Appium (python) test... kinda like a trojan horse. Not very convenient, but at least demonstrates that, with the right access to an accelerated emulator or real device (as a service), it is possible to get flutter driver working.

**Comment by mmcc007** [comment]
BTW: Got the flutter driver equivalent of above espresso test running on a genymotion emulator via an ssh tunnel:
https://travis-ci.com/mmcc007/test_flutter_saucelabs/jobs/180159349

-- demonstrating it is easy to run flutter driver once there is adb access to the emulator or real device.

The problem, AFAIK, is that emulator and real device providers do not provide easy (or any?) access via adb. Any suggestions on getting flutter integration tests running with these providers (other than Genymotion, which does not offer real devices)?
