### ISSUE TITLE
[State Restoration] showDialog/showGeneralDialog not state restorable

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#70918]
Dialogs are not state restorable.

This was discovered migrating the Flutter Gallery's Dialog demos.

Reproduction:

1. Create an app that displays a dialog. You can build `flutter/gallery` and go to any of the Dialog demos (there are 4 configurations).
2. Open any of the dialogs in the demo.
3. Kill the activity on Android, notice that the dialog state is not restored.

**Comment by goderbauer** [comment]
Instead of making showDialog showGeneralDialog restorable, I think we should expose a DialogRoute that people can push via pushRestorable if they need the dialog to be restorable.

Same will be true for the DatePicker as well. Instead of calling showDatePicker, I think we can have a DatePickerRoute that people need to push with the new restorable navigator API.
