### ISSUE TITLE
Flutter freezes on command prompt when initializing

### ISSUE THREAD

**Issue by ThePhoenixRisen** [flutter/flutter#70997]
typing in flutter will not run flutter on CMD Windows 10 It just freezes the cmd with the cursor blinking in the line under it forever. I have attempted running it as user and admin through CMD. When running from clicking on icon of flutter bin in folder /Program Files/flutter, it opens up and gives me the Flutter display just fine. I can't seem to run it from CMD though. 

1. Installed Git through wizard
2. Downloaded latest stable Flutter zip and extracted to src/Program Files/
3. Set path variables to include Program Files/flutter/bin
4. installed Android SDK
5. Open CMD

Attatched file
![flutter error 1](https://user-images.githubusercontent.com/71746795/99885365-daa48c00-2bf9-11eb-8b85-d7ecafa1d265.JPG)
 is exactly what I get.

**Comment by darshankawar** [comment]
@ThePhoenixRisen 
Can you try to unzip it somewhere under `Documents` instead of `Program Files` and check again ?
See the official installation [document](https://flutter.dev/docs/get-started/install/windows) for Windows, as it says `not to install under Program Files`.

<img width="883" alt="Screenshot 2020-11-23 at 6 45 30 PM" src="https://user-images.githubusercontent.com/67046386/99966295-1ab36c80-2dbc-11eb-9e1b-8bc2621f89e0.png">

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by carasen12** [comment]
[image: 3f137c6560a4b460b26b728e1094c1c5be6fb2cd]
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
