### ISSUE TITLE
Really fast swipes move page a small amount

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#710]
Compared to the Google Newstand app (as a reference point).

In Stocks, visit the Stock's homepage.

Perform a slow scroll up, and lift the finger. The page seems to scroll for some time, displaying more stocks.

Now, perform a fast scroll up. Not insanely fast, but towards the fast end of normal.

Expected: the page scrolls up.

Actual: one of two things happen. One: it appears a tap is registered, and a stock's "detail" page is displayed. Or two: a very small amount of scrolling occurs.

Compare this to Google Newstand, where a fast scroll will scroll the page quickly.

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
The source of the problem appears to be GestureDetector.  Every vertical Swipe in the trivial app below causes the onVerticalDragEnd callback to fire twice, the second time with velocity == Offset.zero. This doesn't appear to be right, although it's not what causes the Scrollable failure, because Scrollable ignores the second zero velocity gesture because the animation triggered by the first is still running.

The Scrollable problem occurs because fast swipes are sometimes reported as zero velocity; possibly because the tracker doesn't see enough move events to fit a line.

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class FastSwipe extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Scaffold(
      body:  new GestureDetector(
        onVerticalDragEnd: (v) { print("onVerticalDragEnd $v"); }
      )
    );
  }

}

void main() {
  runApp(new MaterialApp(
    title: 'List',
    routes: <String, RouteBuilder>{
      '/': (RouteArguments args) => new FastSwipe()
    }
  ));
}
```

**Comment by HansMuller** [comment]
The source of the problem is a missing `else` here:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/drag.dart#L108

I will include the fix as part of https://github.com/flutter/flutter/pull/820

**Comment by sethladd** [comment]
Thanks @HansMuller !!
