### ISSUE TITLE
RenderAnimatedOpacityMixin causes child pixel snapping when fully opaque

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#71008]
`RenderAnimatedOpacityMixin` has the following paint method, which avoids painting both the child widget and the opacity later when fully transparent. When fully opaque, the opacity layer is elided while the child is painted. Unfortunately this last optimization causes obvious pixel snapping on low DPR screens. 

`RenderAnimatedOpacityMixin.paint`
```dart
 @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      if (_alpha == 0) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        return;
      }
      if (_alpha == 255) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        context.paintChild(child!, offset);
        return;
      }
      assert(needsCompositing);
      layer = context.pushOpacity(offset, _alpha!, super.paint, oldLayer: layer as OpacityLayer?);
    }
  }
```

This can be seen fairly easily when a mouse hover first reveals a tooltip, such as in the "example app" section of the flutter gallery. The last frame visible shifts - fairly dramatically compared to the previous animation. Though the video below uses 10x time dilation to make it more obvious, it is still hard to see in the low res/low framerate GIF. 

![ezgif-6-2fad4fb28e3e (1)](https://user-images.githubusercontent.com/8975114/99893174-bc5a8280-2c31-11eb-9908-3e5ddcbd72df.gif)

Keeping the opacity layer even when at fully opaque removes this jump.

**Comment by jonahwilliams** [comment]
More of an engine question, but how much does eliding the opacity layer buy us?

**Comment by jonahwilliams** [comment]
https://user-images.githubusercontent.com/8975114/107298876-16960300-6a2b-11eb-961d-0590c93b7fef.mp4


Github now supports mp4s, yay!

**Comment by flar** [comment]
The likely cause of this is that when the opacity layer is rendering its save layer to which to apply its opacity, the entire picture there is being rendered independently from the surrounding picture data. We've essentially introduced a break in the scene rendering at that saveLayer.

When you remove the layer and thus remove is saveLayer, the picture is rendered into the rest of the scene as one big picture. The slight shift is due to "pixel snapping" of each picture independently. When it is a separate picture, it gets individually pixel snapped based on its local bounds. When it is part of the bigger picture, the picture snapping happens on a larger group and then the individual widget is rendered relative to that non-local pixel snapping decision.

**Comment by flar** [comment]
There may be a simpler solution than keeping the widget when it isn't needed. Basically just ensure that the Picture objects are not glued together with or across this widget by careful manipulation of the current recording - with the potential addition of adding a RepaintBoundary mechanism to prevent opacity changes from forcing repaints of the surrounding content.

See #83145 (comment)

**Comment by dnfield** [comment]
We can fix this this pretty easily by just putting the 255 child in an offsetlayer instead of using the offset parameter.

**Comment by dnfield** [comment]
Or, as @flar mentioned on the PR, just wrapping the child in a repaint boundary, which will mean it always gets an OffsetLayer.

**Comment by flar** [comment]
Or, endRecordingIfNeeded before and after painting the child? But that would also happen, possibly more organically, by using a layer instead.
