### ISSUE TITLE
Flutter Painter class starts marking from wrong position when wrapping painter with InteractiveViewer

### ISSUE THREAD

**Issue by Musaddiq625** [flutter/flutter#71054]
Im using painter package: https://pub.dev/packages/painter - painter: ^0.4.0 and default **InteractiveViewer** Widget

Painter class standalone is working fine but, when wrapping it with InteractiveViewer
InteractiveViewer(child: Painter(_controller))

on marking, it starts marking with delay, like approx. 10px from global position

I've tested my code by removing all other widgets, but the problem is still there.

**Comment by sidrao2006** [comment]
Hey @Musaddiq625 ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a 3rd party package, please close this issue and open it in the respective repository instead.

Thanks

**Comment by Musaddiq625** [comment]
okay

**Comment by Musaddiq625** [comment]
@sidrao2006 which 3rd party package?
Interactive Viewer is a existing widget in flutter

This bug is not in painter class
It's in Interactive Viewer

**Comment by sidrao2006** [comment]
@Musaddiq625 , since InteractiveViewer is working properly with all other widgets, this suggests a bug/ an incompatibility issue in the painter package.

I would suggest you to open an issue in the painter package's repository try to pin point the bug and whether it's related to the package or InteractiveViewer

**Comment by Musaddiq625** [comment]
got it, thanks
