### ISSUE TITLE
"flutter precache" fails confusingly if Android SDK is absent

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71107]
Before https://github.com/flutter/website/pull/5013, our installation instructions suggested running "flutter precache" before "flutter doctor", which leads to this failure mode because the user won't have installed the Android SDK yet:

```
afterihavedreamed@penguin:~/Programming$ flutter precache
Failed to download the Android dependencies                            
Downloading Android Maven dependencies...                           0.1s
afterihavedreamed@penguin:~/Programming$
```

We should provide more detail about why we "Failed to download the Android dependencies" and what to do about it, at a minimum suggesting "flutter doctor".

**Comment by jonahwilliams** [comment]
I think we need to remove the maven precache artifact. We don't have the correct checks to make sure it can actually pass, and getting it working is going to conflate flutter artifacts with project specific setup

**Comment by jmagman** [comment]
Introduced in #39157. @blasten do you have thoughts about removing the precache artifact?

**Comment by blasten** [comment]
As @Hixie suggested, it sounds like the issue is that the error message is bad, and that `flutter precache` should check that it has all the runtime dependencies it needs (or noop when it doesn't, and provide a note).

I'm not sure what removing the precache artifact does other than "it doesn't precache Android artifacts".
