### ISSUE TITLE
Forms would like a cheaper GlobalKey for accessing widget State

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#7124]
Forms make heavy use of GlobalKeys for getting access to the FormState and FormFieldState in order to save or validate. This is more expensive than it needs to be. All we really want is a way to grab the State object of a widget. GlobalKey comes with extra baggage.

See [this example](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/text_field_demo.dart#L62) and [this comment](https://github.com/flutter/flutter/pull/6569#issuecomment-256783236).

Something like this would be sufficient:
```
class StateKey<T extends State<StatefulWidget>> extends Key {
  // Called when Element is mounted.
  void _register(Element element) {
    currentElement = element;
  }

  StatefulElement currentElement;
  T get currentState => currentElement?.state;
}
```
@Hixie

**Comment by Hixie** [comment]
It would still have to be a globally unique key, otherwise using the same configuration in two places would stomp on the key. So in debug mode we'd probably still have to put it in the map (in general we do a terrible job of verifying non-duplicate use of global keys today, but that's a separate bug).

What would this approach lose us over regular global keys today?

I guess you lose the GlobalObjectKey support (`operator ==` on keys). You wouldn't really lose anything else though right? We could reimplement GlobalObjectKey via a factory that looks up the canonical instance in a cache, or something (though how would you evict the cache? Hmm).

cc @abarth

**Comment by Hixie** [comment]
(Note that my comment, cited in the original description above, wouldn't be resolved by making global keys cheaper. I wasn't concerned over the cost of using global keys, I was concerned over the API shape. I'm not a fan of this kind of magic pointer as  a way to get to objects.)

**Comment by Hixie** [comment]
It's not clear that the cure is better than the disease here.
