### ISSUE TITLE
Zipperdown Vulnerability - Application seems to be compiled with ZipArchive library for ARM64 which might be vulnerable to zipperdown vulnerability

### ISSUE THREAD

**Issue by kharisazhar** [flutter/flutter#71296]
## Zipperdown Vulnerability

After we Run Pentest (penetration test) Flutter Application especially Flutter iOS , the result appear _Vulnerability Error,_ they say _**Application seems to be compiled with ZipArchive**_, but i don't know which part make Vulnerability Error, 
i think this problem for flutter CMIIW 

### Full Result
**Title** :
Zipperdown Vulnerability leading to Remote Code Execution Attack

**Description** :
The remote code execution occurs inside the affected app allowing a remote attacker to possess the same privileges or permissions as the vulnerable app. For instance, if a vulnerable app has permission to access the user’s address book, the ZipperDown attacker will also have access to the affected user’s address book.

**Vulnerability** :
Application seems to be compiled with ZipArchive library for ARM which might be vulnerable to zipperdown vulnerability

Image : 
<img width="848" alt="Screen Shot 2020-11-27 at 10 29 49" src="https://user-images.githubusercontent.com/30395764/100407642-871fbb80-309b-11eb-8bdb-8692cce3c1ec.png">

**Comment by darshankawar** [comment]
@kharisazhar 
Not sure if Flutter framework issue. Since the error says `Application seems to be compiled with ZipArchive`, possibly this could be related:

`The app uses the ZipArchive or SSZipArchive library to decompress it. Since the ZipArchive and SSZipArchive libraries allow unzipping files in parent directories, malicious .zip file can be unzipped to overwrite app data or codes.`

Also see [this](https://securityboulevard.com/2018/05/zipperdown-remote-code-execution-attack-on-ios-apps/) link for more details.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
