### ISSUE TITLE
[feature_request] Disable scrolling by drag with a mouse

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#71322]
## Use case

When having long text field in web, it is very hard to select the text without making unintentional drag and scroll.

## Proposal

Give possibility to disable scrolling by dragging, but leave enabled scrolling by scroll event.
In theory it could be done by listening the scroll event and NeverScrolllabePhysics, but at the same time it does not follow text field position (so writing in text field does not scroll the page, because of NeverScrollablePhysics).

**Comment by johnpryan** [comment]
@mdebbar can you triage?

**Comment by Piinks** [comment]
We plan to do this once we have made sure we have a good scrolling experiences with mouse & keyboard.

**Comment by yasinarik** [comment]
@Piinks Hi, I'd love to have this option too. 

Since I am currently building macOS, Windows, and WebApps; I want users to be able to scroll only with the mouse wheel but not by clicking and dragging. This is a huge pain point at the moment.

BTW, I know giving a thumbs up increases the priority so I already did. I just wanted to give some more insights. Thanks for the effort! :)

**Comment by johnpryan** [comment]
Any update on this?

**Comment by Piinks** [comment]
@johnpryan This isn't actively being worked on. I think the change itself would be really really simple, but we still want to only do this once mouse/keyboard scrolling is well handled. Not sure who can evaluate that right now. 

I was considering that after our next stable release we would look at this, since there have been a **lot** of changes to mouse and keyboard scrolling that have not reached stable yet. I think having a chance for those features to arrive on stable will give us the chance to evaluate if the functionality is there to remove the dragging.

**Comment by ahmetcj4** [comment]
Is there any workaround to prevent drag on web?

**Comment by johnpryan** [comment]
> Is there any workaround to prevent drag on web?

No, not that I'm aware of.

**Comment by mordivgor** [comment]
@ahmetcj4  if you are not using text fields then it shall be possible to apply NeverScrollabePhysics and listen for scroll events to move the screen. However with text field I am not aware of any workaround.

**Comment by ahmetcj4** [comment]
I wrapped `SingleChildScrollView` with `Listener` and create a widget to use it every component that needs scroll.

Here is the link to the workaround solution:
https://stackoverflow.com/a/66066321/10116426

**Comment by Piinks** [comment]
Update: This is currently blocked on #75059 and #75180 and also I want to loop in the Dartpad team to get their feedback. I have seen users of dartpad use the mouse to drag scrollables as if it is a touch device emulator and want to make sure we don't break that expectation.

I do have an initial proposal in #75728 - this will be updated to include consideration for what kind of pointer device it is, like touch or mouse etc. There is a link to the public design doc there as well.

**Comment by hacker1024** [comment]
This can make a lot of functionality inaccessible to users who don't have a scroll wheel and users that don't know how to use trackpad scrolling in apps that haven't added visible scrollbars yet.

Is there a way to allow drag scrolling globally as a temporary workaround?
