### ISSUE TITLE
[Feature request] Element listeners

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#71370]
## Use case

I want to add an `Extension` to `BuildContext`, I want to listen to a stream, But I don't know how can I cancel listening when `Element` is removed

```dart
extension WatchStreamContext on BuildContext {
   void watchStream(int id){
        final stream = GetStreamFromServiceLocator(id);
        final streamSubscription = stream.listen((value) {
            (this as Element).markNeedsBuild();
        });
       //streamSubscription.cancel();
   }
}
```

for me it is more easier than to use `watchStream` instead if using `StreamBuilder` widget

## Proposal

It's nice to have some listener callback on `Element` , like `onMounted` , `onDisposed`

**Comment by kizoojun01** [comment]
Kizoojun

**Comment by kizoojun01** [comment]
Kizoojun

**Comment by kizoojun01** [comment]
@Wjustins

**Comment by kizoojun01** [comment]
![Uploading 100539734...]

**Comment by kizoojun01** [comment]
![Uploading 100539743...]

**Comment by sm2017** [comment]
@kizoojun01 Are you spamming?

**Comment by Captcha123** [comment]
Who

**Comment by pedromassangocode** [comment]
Not sure if this is a valid proposal. 
Cc @Hixie to verify and validate.

**Comment by kizoojun01** [comment]
kizoojun

**Comment by Hixie** [comment]
@sm2017 You can create a widget to provide those hooks for yourself, but fundamentally doing it as an extension on BuildContext isn't really going to work, the whole system is working against you. It's all designed around making things work for inheritance, not for extension methods.

**Comment by Hixie** [comment]
That said if you can describe in more detail the problem that led you to wanting to do this, maybe we can find another solution that addresses your concern.

**Comment by sm2017** [comment]
@Hixie why there is no way to add listener on the widgets lifecycle?

I am creating an application with entities that closely related to each other, I have `project`, `bid`, `milestone` and `invoice` entities
When some action done to an entity it affect other entities, for instance when a user `awards` a bid, the project is changed to `awarded` status and other bids of the project changed to `canceled` (I have to update all instances)

I using `bloc` to manage state,I have many many blocs, for instance, my projects, favorite projects, latest projects, detail of a ptoject,...
When a projects updated, I must sync all same projects in different blocs, its too combersome, so I make a centeral store for projects(and other entities) with ValueNotifer and Streams

I have many `ValueNotifier` and `Stream` in my application, sometimes they are dependent, and for instance, when you want to create value notifier of B you must firstly resolve value notifier of A
When I have too many dependencies , I have many nested `ValueListenableBuilder` and `StreamBuilder` 

I think libraries like flutter-hook is not good for my use-case, I want to create an extension on context, to listen on ValueNotifers and Streams without nested widgets, simply with a few line of codes like


```dart
final projectA = context.watchNotifier<Project>(id:1);
final ownerUser = context.watchNotifier<User>(id:projectA.ownerUserId);
User freelaner;
if(project.freelancerUserId!=null){
   freelaner = context.watchNotifier<User>(id:projectA.freelancerUserId);
}
```

**Comment by Hixie** [comment]
> @Hixie why there is no way to add listener on the widgets lifecycle?

There is, that's what the State class does.

There's no way to listen in on other widgets because that's a bug-prone programming style so we try to steer people away from it. Widgets should be self-contained. When widgets have dependencies outside of themselves it becomes very hard to reason about their behavior and our optimizations start falling apart, which leads to bugs, performance issues, and so on.

**Comment by Hixie** [comment]
Looking at your description of the problem, it sounds like what you're really saying is that individual widgets need to listen to many parts of your application state, and that leads to having too many ValueListenableBuilders and StreamBuilders. In that case, on the short term I would recommend making your application state less fine-grained (e.g. just listen to a whole project rather than just the project's owner user id and its freelance user id), and on the long term I would wait for work on things like https://github.com/flutter/flutter/issues/51752 to develop.

**Comment by sm2017** [comment]
@Hixie Thank you
