### ISSUE TITLE
Flutter vscode response error in ubuntu

### ISSUE THREAD

**Issue by sezgindev** [flutter/flutter#71406]
Hello i install ubuntu 18.04 and fetch my flutter project in bitbucket.
But i have a problem , my project  gives an error just ubuntu (its run windows succesfuly)
Error photos below.
![Ekran Görüntüsü - 2020-11-30 17-40-29](https://user-images.githubusercontent.com/24322384/100623760-a6387a80-3333-11eb-9b2b-b3abb52b90e3.png)

**Comment by TahaTesser** [comment]
Hi @sezgindev 
Please execute `flutter pub get` to update your packages,
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutterchina/dio/issues).
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
