### ISSUE TITLE
Flutter & Dart plugin not installed while they are

### ISSUE THREAD

**Issue by ZCJ** [flutter/flutter#71472]
## Steps to Reproduce
I have Android Studio installed on ubuntu 20.10 (installed by jetbrains Toolbox). I have flutter and dart plugins installed, however I still get these error messages.

## Logs
```
flutter doctor --verbose                                                                                                                
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/zcj/tools/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/zcj/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/zcj/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/zcj/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/zcj/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category
```

```
```

**Comment by hello-addweb** [comment]
Solution (Its happen because of not restart android studio after install plugin) : 
1.  Just install plugins.
2.     Studio>>File>Settings>Plugins>Browse Repositories
3.     Search for flutter.
4.     Tap on Install (a dialog will pop regarding dart dependency. click Yes).
5.     Once the installation is finished restart android studio.
Now run flutter doctor.

**Comment by ZCJ** [comment]
They are already installed - tried to remove them and install them again - restarted the IDE - nothing worked

**Comment by darshankawar** [comment]
@ZCJ 
This issue was [fixed](https://github.com/flutter/flutter/issues/67986) and merged. Also see [this](https://github.com/flutter/flutter/issues/67986#issuecomment-707511812) issue comment regarding the warnings you see. You should be able to continue using the plugins as usual.
You may switch to latest master and try again.
Closing this as already fixed.  If you disagree, write in comments and I'll reopen.
Thanks.
