### ISSUE TITLE
Flutter Gallery pixelated overscroll

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#7149]
When scrolling on high resolution devices the overscroll is pixelated.
![screenshot_20161204-115943](https://cloud.githubusercontent.com/assets/2686902/20865706/0e147664-ba1a-11e6-8509-a896ddf90d03.png)

Device: Nexus 10
OS: Android 6.0.1 (CM 13.0)
Flutter Gallery Version: Q3 Preview

**Comment by eseidelGoogle** [comment]
Likely just confusion around using antialiasing or not.  @HansMuller would know.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by eseidelGoogle** [comment]
Here is the paint code:
https://github.com/flutter/flutter/blob/f7d501024c83a3d75cc5e208312df73c36e685b2/packages/flutter/lib/src/material/overscroll_indicator.dart#L30

I suspect the problem is we should use drawArc instead of draw circle.  @HansMuller or @dragostis fixed something similar elsewhere (animations demo?) in Flutter this summer.

**Comment by HansMuller** [comment]
I don't think that drawing a filled arc instead of an implicitly clipped filled circle would perform better or avoid aliasing. SKIA should be better at this than we are.

In fact it looks like the native glow rendering code also just draws a filled circle: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/EdgeEffect.java#335.

We have run into this sort of problem before. It looks like we're inadvertantly turning antialiasing off. There's an open issue for this: https://github.com/flutter/flutter/issues/5720.

**Comment by zoechi** [comment]
Looks good on Pixel XL. Can this be closed?

![screenshot_20181130-123152](https://user-images.githubusercontent.com/405837/49287010-3a994980-f49c-11e8-9a05-5ffb4069e9da.png)
