### ISSUE TITLE
Audit engine Dart code for null safety

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71507]
We should check all *.dart files in the engine repo to see if they've been migrated to null safety. (For example, tests, utilities, etc.)

**Comment by dnfield** [comment]
The only things left right now are:

- [ ] `//flutter_frontend_server/bin/starter.dart`
- [ ] `//flutter_frontend_server/lib/server.dart`
- [ ] `//shell/platform/fuchsia/dart/compiler.dart`
- [ ] `//shell/platform/fuchsia/flutter/kernel/extract_far.dart`
- [ ] `//shell/platform/fuchsia/runtime/dart/profiler_symbols/dart_profiler_symbols.dart`
- [ ] `//testing/benchmarks/bin/parse_and_send.dart` @dnfield
- [ ] `//testing/benchmarks/test/parse_and_send_test.dart` @dnfield
- [ ] `//testing/symbols/verify_exported.dart` @dnfield


For the frontend server ones: @zanderso or @jonahwilliams are these getting removed? I think they didn't get migrated because of outstanding deps - but if we plan to remove these anyway maybe we should just remove them?

For the Fuchsia ones: @akbiggs can you take a look at these? I am not sure how to test them.

I can take a look at the ones remaining under `//testing`. The only one I'm not entirely sure of is verify_exported, I know @chinmaygarde was suggesting we could use a linker script instead of this script - maybe it would be better to just migrate to that and delete the dart program.

**Comment by jonahwilliams** [comment]
I think we were planning to switch to the front end server built in the Dart SDK?

**Comment by zanderso** [comment]
The frontend server in the engine tree is only used for tests in the engine tree, IIRC. So, yeah, we should re-write those GN rules, and delete.

**Comment by jonahwilliams** [comment]
We did this
