### ISSUE TITLE
Unhandled exception: Invalid argument(s): Cannot find executable for sysctl.

### ISSUE THREAD

**Issue by BriscoPeas93** [flutter/flutter#71516]
After upgrading flutter on macbook here is the error I got.
Even Flutter doctor is giving me the same error.

```
Unhandled exception:
Invalid argument(s): Cannot find executable for sysctl.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:91:30)
#2      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:649:37)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:548:14)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:649:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:420:51)
#6      _MacOSUtils.hostPlatform (package:flutter_tools/src/base/os.dart:305:25)
#7      _MacOSUtils.name (package:flutter_tools/src/base/os.dart:291:123)
#8      new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:247:18)
#9      new Usage (package:flutter_tools/src/reporting/usage.dart:81:9)
#10     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:263:20)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#15     flutterUsage (package:flutter_tools/src/globals.dart:55:35)
#16     _handleToolError (package:flutter_tools/runner.dart:133:13)
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:87:13)
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:81:17)
#19     _rootRunBinary (dart:async/zone.dart:1222:13)
#20     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#21     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
#22     _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#23     Future._propagateToListeners (dart:async/future_impl.dart:646:16)
#24     Future._completeError (dart:async/future_impl.dart:537:5)
#25     _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
```

**Comment by cdye0000** [comment]
I'm given the same error

**Comment by jmagman** [comment]
Didn't think [`sysctl`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctl.3.html) could ever be missing.

What's the output of 
```
$ which sysctl
```

**Comment by zenkairan** [comment]
I have the same error, after trying the which command it simply says sysctl not found.

**Comment by zenkairan** [comment]
Resolved the issue by replacing the installed folder by the previous stable version (1.22.3).

**Comment by jmagman** [comment]
What's the output of:
```
$ ls /usr/sbin/sysctl
$ echo $PATH
```

**Comment by jmagman** [comment]
https://stackoverflow.com/a/42352026 suggests it could be at `/sbin/sysctl` on some macs, updated the request for info.

**Comment by hqdoremi** [comment]
Resolved this problem by adding `/usr/sbin` to PATH . In my case, the `sysctl` is in `/usr/sbin`

**Comment by yuchuan08** [comment]
vim ~/.bash_profile
export PATH=/usr/sbin/sysctl:$PATH

this code resolve error,I check it

**Comment by tanzilzubair** [comment]
I have the same problem and I can't seem to find a solution. Can someone please help ? I don't know much about the PATH variable or sysctl files in general, so I have no idea what's actually happening here.
I also tried a fresh install, and that didn't work either. 
Any help would be very nice, as I'm completely stuck on what to exactly do.

**Comment by HeudmannLima** [comment]
**I have the SAME problem, it persists even after a fresh install and changing PATH info. I'm really stuck on it**

**Comment by tanzilzubair** [comment]
Hey, I actually managed to solve the problem yesterday. So what you have to do is locate the `.bashrc` or `.zshrc` file (whichever is applicable) and completely reset it with this:

```
#This is the default one, it probably won't change for you
PATH=/usr/bin:/bin:/usr/sbin:/sbin 
export PATH

#This is for HomeBrew, the directory might change for you
export PATH=/usr/local/bin:$PATH

#This is for Flutter, the directory might change for you
export PATH="$PATH:/Users/[USER NAME]/flutter/bin"   
```

Then, just go to the directory where the flutter folder is stored, and just delete it.

Run `which sysctl' in the terminal, and it should output a directory now, which means it found it. Then proceed to do a fresh install of the flutter sdk through the official docs.
Everything should normally happen now. Also, skip the step where they tell you to set the path variable, since you've already done it. 

I don't know about VS Code, but I'm using Android Studio for my development, and the first time I opened it after all of this, it couldn't locate the Dart SDK. There's a folder inside the flutter folder, at flutter/bin/cache/dart-sdk , that's the one where you should point it to. 

I'm not sure about this, but what I think the problem was that the PATH variable got mixed up, and so the terminal could no longer find crucial files.

Hope this helps dude.

If you have other questions or problems, reply here so that I can try and help out, and for future reference by others.
