### ISSUE TITLE
Consent screen is not showing right 

### ISSUE THREAD

**Issue by pr0ph0z** [flutter/flutter#71541]
Hi there, I'm currently using this `google_sign_in` plugin to get only the user ID but the consent screen title is not showing as what I filled in Google console. It shows the application name (`mobile2`) instead project name I filled in the Google console.
![image](https://user-images.githubusercontent.com/17337978/100848896-59c87880-34b4-11eb-974f-8db8420ccf68.png)
But in the scope agreement, it shows correctly.
![image](https://user-images.githubusercontent.com/17337978/100849025-88465380-34b4-11eb-8b00-6a123bf0a571.png)
Have I missed something? Thank you.

**Comment by TahaTesser** [comment]
Hi @pr0ph0z 
The first screen is showing the app name 
This is working as intended, if you want to show the app name on the second screen, you can write an app name and paste in  `app name` instead of the project in the consent screen settings

https://console.cloud.google.com/apis/credentials/consent/

<img width="640" alt="Screenshot 2020-12-02 at 4 09 00 PM" src="https://user-images.githubusercontent.com/48603081/100862400-1fada580-34b9-11eb-88db-0ec5183ad534.png">


This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with `google_sign_in`  itself. If you disagree, please write in the comments and I will reopen it.
Thank you
