### ISSUE TITLE
Style guide clarification request on trailing commas

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#71596]
Regarding [this section](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-a-trailing-comma-for-arguments-parameters-and-list-items-but-only-if-they-each-have-their-own-line) in the style guide:

```
Use a trailing comma for arguments, parameters, and list items, but only if they each have their own line.
Example:

List<int> myList = [
  1,
  2,
];
myList = <int>[3, 4];

foo1(
  bar,
  baz,
);
foo2(bar, baz);
```

Could we get clarification on what it means for each item to _not_ have its own line? Since you could write every element on one line, is this specifically after dartfmt has been applied? If so, wouldn't it be easier to say "only if the elements don't fit on one line"?

With the examples given, both are shown with and without trailing commas, and it's not stated whether either or both are valid. Can we add "good: " and "bad: " where relevant please?

Also, since the examples shown both should or both shouldn't use trailing commas, can we add an example where the opposite is true?

**Comment by Hixie** [comment]
> Could we get clarification on what it means for each item to _not_ have its own line?

For example, in the examples above the first list literal (1,2) has a trailing comma and each item is on its own line, but the second (3,4) has no trailing comma because the items are all on the same line.

> Since you could write every element on one line, is this specifically after dartfmt has been applied?

We don't use `dartfmt` for the flutter/flutter repo, which is what this style guide refers to. When using `dartfmt`, there's no need for the formatting rules of the style guide. (Personally I would recommend using `dartfmt` if you are not disciplined about code style, and not using it if you are able to maintain high code style consistency without it, because you can get better results by manually formatting than by using the formatter.)

> If so, wouldn't it be easier to say "only if the elements don't fit on one line"?

It's not about whether they fit or not, so much as about whether they are or not. In the example above, both lists fit on one line, but the first list doesn't put them all on one line.


> With the examples given, both are shown with and without trailing commas, and it's not stated whether either or both are valid.

Both are valid.


> Can we add "good: " and "bad: " where relevant please?

They're all good.


> Also, since the examples shown both should or both shouldn't use trailing commas, can we add an example where the opposite is true?

Not sure what this means.


I've updated the style guide.

**Comment by mtcliatt** [comment]
Thanks for the clarification. There is one more scenario I'd like to get your opinion on:

When there are several back-to-back calls and all but one of them fit on one line, and the exception fits on two lines, like so:

```
fooBarBaz(one: firstArgument, two: secondArgument),
fooBarBaz(one: firstArgument, two: secondArgument),
fooBarBaz(
    one: firstArgument, two: secondArgument, three: thirdArgument)
fooBarBaz(one: firstArgument, two: secondArgument),
```

is it more readable to use the above style, where exception omits a trailing comma and fits on two lines, or the below style where the exception has a trailing commas and differs somewhat from the other calls?

```
fooBarBaz(one: firstArgument, two: secondArgument),
fooBarBaz(one: firstArgument, two: secondArgument),
fooBarBaz(
    one: firstArgument,
    two: secondArgument,
    three: thirdArgument,
),
fooBarBaz(one: firstArgument, two: secondArgument),
```

**Comment by Hixie** [comment]
The first one violates the section immediately above the one we're discussing:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation

**Comment by mtcliatt** [comment]
That's true. Ok that clears up all of my confusion, thank you!

**Comment by mtcliatt** [comment]
Wait, how does that example violate the section you mentioned, but this line (which is from the sample) does not:

```
foo(bar,
    baz);
```

**Comment by Hixie** [comment]
There's no newline after the `(` in that most recent example, and no newline before the `)`.
In the earlier ("bad") example, there _is_ a newline after the `(` but not before the `)`.
