### ISSUE TITLE
Increase Android platforms tested in the Firebase Test Lab...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#71603]
Let's add support for testing on dev rolls for the following Android releases:
```
SDK 19 (Android K)
SDK 20
SDK 21 (Android L)
SDK 22
SDK 23 (Android M)
SDK 25 (Android N)
SDK 26 (Android O)
SDK 27 (Android O)
SDK 30 (Android 11)
```

/cc @csells @dnfield (who is probably going to be doing the work)

**Comment by dnfield** [comment]
At a high level:

- Update the firebase testlab harness to run on these virtual devices if branch != master.
  - Alternative: since these are virtual devices, they may be fast/stable enough to just run on every commit.

First step will be to update the recipe (the bash script is obsolete) and see how long it takes to run all the tests. If that works out, we can consider running them on every commit instead of just on dev.

Unfortunately, SDK 20 is not available at all in FTL. Here's a proposed list to add:

```
  # Virtual devices for API level coverage.
  "model=Nexus5,version=19"
  # version 20 not available.
  "model=Nexus5,version=21"
  "model=Nexus5,version=22"
  "model=Nexus5,version=23"
  # SDK 24 is run on a physical griffin/Moto Z above.
  "model=Nexus6P,version=25"
  "model=Nexus6P,version=26"
  "model=Nexus6P,version=27"
  # SDK 28 is run on a physical blueline/Pixel 3 above.
  # SDK 29 is run on a physical flame/Pixel 4 above.
  "model=NexusLowRes,version=30"
```

/cc @godofredoc @keyonghan

**Comment by kf6gpe** [comment]
Looks like a good plan to me.

**Comment by dnfield** [comment]
Fixed in https://flutter-review.googlesource.com/c/recipes/+/9620

**Comment by dnfield** [comment]
See also https://github.com/flutter/flutter/issues/49095 - also closed now, but similar.

**Comment by dnfield** [comment]
Change is getting reverted due to some failures. Reopening while it's investigated.

**Comment by dnfield** [comment]
Reland in https://flutter-review.googlesource.com/c/recipes/+/9643

**Comment by dnfield** [comment]
This has landed again. @kf6gpe - I'm not sure if I mentioned this before, but FTL completely lacks coverage for API version 16, 17, and 22, so we're not testing those. But we now run tests on API levels 18-30, 22 excluded.

**Comment by dnfield** [comment]
Also for future us: Android API level violations are dynamically checked at runtime, only if you hit the code path that would violate. The tests we're running are definitely not exhaustive of all functionality in the Android Java embedding code. That said, we know at the very least that a few example applications run without API violations, which is better than we were :)
