### ISSUE TITLE
[flutter_tool]: support launching DevTools from command line links

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#71688]
We have several DevTools issues/feature work that requires support for launching DevTools from a link in the command line. In order to accomplish this, we will need two things:
1) launch devtools from pub instead of from devtools_server. This will mean that the version of DevTools that is launched is always the latest published version (this mirrors what we do from the IDEs).
2) launch the devtools server from pub (without launching the web app in chrome) at `flutter run` so that clicking a CLI link such as `127.0.0.1:9100/#/inspector?widgetId=1234` will hit the already-running server
    - one thing to think about here, is will we have to change the way we launch devtools from ide's if the devtools server is always running? @helin24 

@jonahwilliams to add some additional details

FYI @jacob314 @devoncarew

**Comment by jonahwilliams** [comment]
The tool has some existing logic for launching devtools via the devtools_server package, which is implemented by https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devtools_launcher.dart#L16 (the interface is separately implemented in google3).

The devtools_server package does not work with the prebuilt SDK snapshots we create for our download links, so this implementation should be updated so that it does a `pub global activate devtools` and then a  `pub global run devtools --no-launch --machine`. This can be done unconditionally during the resident runner startup, ideally without blocking the rest of the app startup process.

Some caveats:
  * We should avoid launching multiple devtools instances. Ideally if IDEs are also starting devtools, they should instead use this version - or else the tool should avoid launching devtools when run in --machine mode.
  * Ideally we would avoid `pub global activate` if devtools was already up to date.
  * Ideally we would be resilient to timeouts or failures in `pub global activate` if there is already a devtools version available.

**Comment by jonahwilliams** [comment]
For an example of a PR that _almost_ implements this, see https://github.com/flutter/flutter/pull/65137/files

**Comment by helin24** [comment]
Regarding starting DevTools from IntelliJ, we currently have two different ways of starting the server:
1. for external projects, we run `pub global run devtools` to start a new server
2. for internal projects, we use the devtools launcher mentioned above, so a request is made to the daemon to start the server

In both cases, I think it would be great to verify that a server is running instead of starting a server. For method 2, IDE changes wouldn't be necessary (or would be minimal) if we can continue using a daemon request and instead return info about an existing server. It would also be nice to change IDE uses of method 1 to method 2, e.g. with the implementation change Jonah mentioned; otherwise we would probably need to add some other logic to find an existing DevTools server.

**Comment by DanTup** [comment]
Would it be better for the IDEs to launch DevTools and then pass that to Flutter rather than the other way?

Right now an IDE can reuse DevTools across multiple debug sessions (or even for multiple concurrent debug sessions) so if you stop/start a debug session we don't need start up a new server (and we can also re-connect orphaned embedded views to new debug sessions when they start by calling an API in the server). It seems like this would become more complicated if the server only lived as long as a debug session.

**Comment by jonahwilliams** [comment]
The IDE launching devtools is an interesting idea, I would imagine `flutter run --machine` also accepting a `devtools-url` address and then displaying a deeplink for the app in the current devtools app or something. When run from the CLI, the absence of this URL could prompt the tool to start the server but not open the browser. With this functionality, I think we should consider retiring the `v` to open devtools functionality.

Taking a look at the updated usage of `pub global run` though, I'm not really happy with the perf - it seems to take a decent chunk of time even when it is up to date. I think we need a way to skip `pub global activate`. This shouldn't be that difficult provided we're okay with some heuristics for updating (i.e. at most once a week or if pub global run fails) instead of always trying to grab the latest version.

**Comment by kenzieschmoll** [comment]
If we could get https://github.com/dart-lang/pub/issues/2791 resolved, then the perf would stop being a concern. @sigurdm  is this task trivial or would it be a large undertaking?

**Comment by DanTup** [comment]
> it seems to take a decent chunk of time even when it is up to date. I think we need a way to skip `pub global activate`

I saw this too - there is some discussion in https://github.com/dart-lang/pub/issues/2097. It was adding around 6 seconds to launching DevTools in VS Code, so now I'm calling the Pub API directly to check the latest version of the package (and caching that for 24 hours) to skip it if there's no update (although this [does mean dependency updates wouldn't be picked up](https://github.com/dart-lang/pub/issues/2097#issuecomment-471546661)).

**Comment by jonahwilliams** [comment]
From discussion today on where to automatically launch: I think the best place to perform the launch is in `attach`, since this runs during both flutter run and flutter attach:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L864

The method is abstract and separately implemented by the HotRunner (debug mode), the ColdRunner (release & profile), and the WebRunner. The common logic could be added to a special protected method `Future initializeDevTools()` which is present on the base runner. Then, this method could be called concurrent with the vm service logic happening in attach, to avoid slowing things down.

I'm not sure whether it makes sense to launch devtools server for release mode apps, or web. This can be changed later of course. We should consider retiring the `v` to launch devtools after this is fully implemented.

Some requirements:

* needs to handle --offline mode.
* needs to fail gracefully, probably print an error message and keep running, at least initially.

**Comment by DanTup** [comment]
Are there plans to allow the IDE to provide a URL as described above? There are several things in VS Code that won't work well if Flutter owns the DevTools instance, but it would also be strange if clicking links in Flutter output spawns a second copy.

(a slight aside - if a user is using the embedded version of DevTools, might they want to click a link in the output that navigates an existing embedded Inspector view to that widget?)

**Comment by kenzieschmoll** [comment]
We could probably support passing a devtools-url as an argument to flutter run / attach if the IDE needs to launch the DevTools instance. By default we'd launch from pub, but if this flag is present, we'd just set the active devtools server in flutter_tools as the one passed. Whatever we do, we need to make sure the same server is being used across the IDE and flutter tools so that deep links from flutter tools are pointing to the DevTools address.

Alternatively, what if we have the IDEs pull the running server through flutter tool, and then make some call over the daemon api to effectively "take over" devtools server shutdown to tell the tool that it should no longer manage the devtools server life cycle.
