### ISSUE TITLE
Provide a way to turn off warning when auto-registering plugins

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#72027]
Google tooling provides a different way to generate registrant (since build system is different). All apps currently see this in their logs:

```
FlutterEngine: Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f7c0a9d) but could not find and invoke the GeneratedPluginRegistrant.
```

**Comment by mehmetf** [comment]
It would be good to expose a manifest attribute such as `autoRegisterPlugins` which can default to true. We can then turn it off in Google.

**Comment by shuoch-g** [comment]
btw, code searching `"Tried to automatically register plugins with FlutterEngine"` gave me two blocks of code that are almost duplicated.

maybe `FlutterEngine` should call [`GeneratedPluginRegister. registerGeneratedPlugins(this)`](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/plugins/util/GeneratedPluginRegister.java) instead of forking this code block.

**Comment by xster** [comment]
You're right, filed https://github.com/flutter/flutter/issues/74646.
