### ISSUE TITLE
AX information on Android does not appear to account for device pixel ratio

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7205]
Discovered this when using an internal AX inspection tool:
e.g. go/hsv/5051009483145216?node=11#
(Note the displayed layout is ~1/3rd the expected size.

@Hixie suggests @abarth might have broken this when moving the boundary between logical and physical around?

I haven't yet tested on a real device, so this may be a red herring.

**Comment by Hixie** [comment]
I have this fixed on the framework side but it revealed a matching bug on the Java side whereby we are not properly scaling the positions (though we do scale the sizes correctly, interestingly). I haven't figured out what's going on there. The data is fine, since the touch-exploration feature is hit-testing correctly...

**Comment by eseidelGoogle** [comment]
@jason-simmons is probably the person who knows our Android java code the best.
