### ISSUE TITLE
Use application name/id for log tag instead of 'flutter'

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#7226]
The tag used for logging today uses is 'flutter'. When user has multiple flutter apps on their phone, it would be hard to sift through crash logs unless we use app.id or some other app specific string during logging.

**Comment by eseidelGoogle** [comment]
Agreed.  This will take a bit of work since it's currently hard-coded in the engine:
https://github.com/flutter/engine/blob/d658f9d324a401589174400cf0463d9948b4bcb0/lib/ui/dart_runtime_hooks.cc#L155

There is a second place this is hard-coded for engine errors as well, but those can probably stay `flutter`?
https://github.com/flutter/engine/blob/6c5315c3a1d72ee2aae520e05c1ebf0f6794ae0e/sky/engine/wtf/Assertions.cpp#L65

@jason-simmons @chinmaygarde

**Comment by mehmetf** [comment]
This should be in place before we release the app to production.
