### ISSUE TITLE
Crash when handling delete key

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#72400]
```
201209 14:33:48.536 SEVERE 9 main Unhandled error, error: RangeError: Value not in range: -1, stackTrace: 
#0 _StringBase.substring (dart:core-patch/string_patch.dart:399)
#1 TextRange.textBefore (dart:ui/text.dart:1533)
#2 RenderEditable._handleDelete (package:flutter/src/rendering/editable.dart:824)
#3 RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:550)
#4 RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:634)
#5 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74)
#6 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73)
#7 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284)
```

This implies the delete key handling is happening on an invalid selection. I am not sure how we are getting to this state because there's no reproduction. It has been observed ~1600 times across 450 people across different _Android_ versions. iOS does not have this problem. It could be that we are getting out-of-band, unexpected key events.

**Comment by mehmetf** [comment]
Marking as P2 since this is customer:money's top crasher at the moment.

**Comment by Jjagg** [comment]
I've gotten the exact same error while working on my rich text editor. I fixed it by changing my approach, but the issue was IIRC that I changed focus away from the text field in the onKey callback of the text field's focus node when a delete happened. That set the selection to invalid (-1) which caused the error when the delete was applied.

I think you can check the selection is still valid in the [_handleKeyEvent](https://github.com/flutter/flutter/blob/78910062997c3a836feee883712c241a5fd22983/packages/flutter/lib/src/rendering/editable.dart#L512) callback and return out of the method if it isn’t to fix the issue.

**Comment by pedromassangocode** [comment]
Hi @Jjagg 
Are you able to provide a reproducible code sample? That would be helpful to fix the issue.

**Comment by Jjagg** [comment]
I didn't check my old code into source because it didn't work and I assumed it was my mistake and not something worth bringing up here, so I didn't have it handy.

But, I still tried to reproduce this for a bit. I'm not sure I've gotten the exact path that caused the error for me before (because I really think it had to do with focus), but I've gotten a very small sample that causes this stack trace:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

final controller = CustomController();

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          controller: controller,
        ),
      ),
    ),
  ));
}

class CustomController extends TextEditingController {
  @override
  set value(TextEditingValue v) {}
}
```

Backspace in the text field causes the error.

It looks dumb like this, but in a more involved set up, perhaps the underlying cause is the same. I know I overrode the `TextEditingController.value` setter at least, to modify the text value. Perhaps I forgot to keep the selection somewhere.

I played around with focus too, but haven't managed to get a crash that way.

**Comment by Hixie** [comment]
cc @justinmc

**Comment by justinmc** [comment]
This reminds me of a fix I made in the engine for negative selection, but that was 6 months ago (https://github.com/flutter/engine/pull/19785).  @mehmetf Do we know how long this error has been happening?

I was able to reproduce this locally on the Android emulator.  I'll try to see what's different between Android and iOS.

**Comment by justinmc** [comment]
The merged PR will make this no longer cause an error.  A delete in an empty field that would previously cause a crash will now just do nothing.  However, we're still not sure how customer: money was hitting this error in the first place.  We should keep an eye out for anything else that might seem awry.
