### ISSUE TITLE
Regression in 	hotReloadInitialDevFSSyncAfterRelaunchMilliseconds

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#72435]
15ms ~7% regression so marking P0.

https://flutter-flutter-perf.skia.org/e/?begin=1607714599&end=1608103683&keys=X4a4e3c57b71c45caf7d762fcf76c8434&requestType=0&xbaroffset=22860

Likely https://github.com/flutter/flutter/commit/4ed3432e8f43dd92130d3360537c0a30c7283a3f

/cc @jmagman @jonahwilliams

**Comment by xster** [comment]
reverting. We can probably pick a lower zlib level number.

**Comment by jonahwilliams** [comment]
Drive by comment - I don't think any regression is necessary here. The problem is that you are eagerly encoding the NOTICES file, which works against previous optimizations I've done to do most work lazily. The goal should be to only encode and sync the NOTICES file if any of the underlying license changes.

The way I would accomplish this is with a special DevFSContent subtype that does this computation on the fly. Then constructing the asset bundle could use the same invalidation logic as the DevFSString, but would only perform the encode when the bytes are accessed.

**Comment by xster** [comment]
Ha, thanks for checking. I tried to understand what the optimization was (https://github.com/flutter/flutter/pull/71899/files#diff-1339eded5eeb35ab9fbc61051c530c73e307d4640328760c1af0eee36c142be2R356) but must have gotten wrong. Let me bug you about it when you come back in January.
