### ISSUE TITLE
After upgrading Flutter, VSCode doesn't recognize valid code.

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#72510]
I'm experiencing some strange behaviors each time I upgrade Flutter, either from stable to stable, or stable to beta/dev or beta/dev to stable, etc...

VSCode doesn't recognize some valid arguments and shows them as errors.

Like here, on the `BoxDecoration()`. It shows that the parameter colors isn't defined.
![image](https://user-images.githubusercontent.com/9553253/102483728-71cbfa80-4065-11eb-821e-2c3f83bf6a81.png)

When opening up the available parameters for this Widget, something other strange happens... it shows `List:`
![image](https://user-images.githubusercontent.com/9553253/102483736-7395be00-4065-11eb-98cb-3ffff3ba6606.png)

I tried `flutter clean` in a terminal and `Flutter: Clean Project` in VSCode, but none of these help. The only thing that helps, is restarting VSCode.

**Comment by darshankawar** [comment]
@ad-on-is 
Although I don't use VSCode, but this sounds like an issue with Flutter plugin extension for VScode. Did you check if you have updated Flutter plugin. If not, can you try to update it and see if it helps ?

Also, if issue persists, you may have to follow up in plugin extension's dedicated repo : https://github.com/Dart-Code/Dart-Code/issues

**Comment by DanTup** [comment]
@ad-on-is how are you upgrading Flutter? Using the built-in **Flutter: Upgrade** command should automatically restart the analysis server once it completes (which should have the same effect as reloading VS Code). If you're running `flutter upgrade` from a terminal you'll need to do this manually. Upgrading Flutter replaces the Dart SDK so the anlaysis server running in memory won't match.

Otherwise, it could be https://github.com/dart-lang/sdk/issues/43532 that you're seeing - when moving from non-null to null-safe packages, the analyzer context might not be recreated which results in the `required` keyword not being understood correctly (you can check this by using Go-to-definition on a function you see this for and seeing whether it has a `required` keyword (note: this is different to the `@required` annotation) on any parameters.

Let me know if neither if doesn't seem to either of these (and if so, two exact versions you've seen this switching between). Thanks!

**Comment by DanTup** [comment]
It occurs to me that we could detect Flutter upgrades done outside of the VS Code command with a watcher, so I've opened https://github.com/Dart-Code/Dart-Code/issues/3020 which could resolve the issue if it was the first thing mentioned above.

**Comment by ad-on-is** [comment]
@daadu aaah, thank you. Yes, I always upgraded flutter via the terminal, never through VS Code, so this seems a logical behavior.

**Comment by DanTup** [comment]
Got it - in that case let's consider https://github.com/Dart-Code/Dart-Code/issues/3020 the fix for this. Thanks!

**Comment by daadu** [comment]
> @daadu aaah, thank you. Yes, I always upgraded flutter via the terminal, never through VS Code, so this seems a logical behavior.

@ad-on-is  Why quote me mate!

**Comment by ad-on-is** [comment]
hahaha, sorry... I accidentally hit the wrong user from the autocomplete, no offense 😂👍
