### ISSUE TITLE
DatePickerHeader should has option to disable/hide `entryModeIcon`

### ISSUE THREAD

**Issue by Xawery94** [flutter/flutter#72513]
## Use case

In application there should be an option to disable edit mode icon via some property [true/false]. In our app we don't want to use `DatePickerEntryMode.input` at all and maybe more developers want to disable that option.

## Proposal

Add property to DatePickerHeader to disable `entryModeIcon`

**Comment by HansMuller** [comment]
cc @darrenaustin

**Comment by darrenaustin** [comment]
Thanks for the suggestion. Can you share more on why you don't want the input mode available to your app? Just curious to better understand your needs.

Instead of adding a new property, we could extend the existing `DatePickerEntryMode` with two new values: `calendarOnly` and `inputOnly` that would force the dialog to only every show one of the modes.

**Comment by Xawery94** [comment]
@darrenaustin Hi, from a graphic and design point of view, maybe others have the same problem that they want to disable this option, but there is no such option as of now.

It will be very nice to add what you suggested, I really like your proposal.

Maybe it's nice future but it should be an option, not a compulsion :)

**Comment by Xawery94** [comment]
@darrenaustin Hi, any news about the progress, do you try to do this what you suggested?

**Comment by darrenaustin** [comment]
No news yet. We have had other higher priority items we have had to deal with. This is still on my list to look at.
