### ISSUE TITLE
Text is not vertically centered with customized height

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#72521]
Internal: b/175850701

Repro:

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(title: Text('Text')),
        body: Center(
          child: Container(
            color: Colors.grey[300],
            child: Row(
              children: [
                Text(
                  'Input: ',
                  style: Theme.of(context).textTheme.bodyText1.copyWith(
                        backgroundColor: Colors.blue.withAlpha(100),
                        height: 3,
                      ),
                ),
                Expanded(
                  child: TextField(
                    decoration: InputDecoration(
                      hintText: 'Message...',
                      border: InputBorder.none,
                      focusedBorder: InputBorder.none,
                      contentPadding: EdgeInsets.zero,
                    ),
                    style: Theme.of(context).textTheme.bodyText1.copyWith(
                          backgroundColor: Colors.red.withAlpha(100),
                          height: 3,
                        ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<img height="720" src="https://user-images.githubusercontent.com/6687929/102516120-5fd96000-4043-11eb-8361-d695d3e24837.png">

**Comment by HansMuller** [comment]
CC @johnsonmh @goderbauer

**Comment by johnsonmh** [comment]
I believe the best solution to this is implementing half-leading. Engine proof of concept here: https://github.com/flutter/engine/pull/22814

With ongoing discussion in go/flutter-half-leading

**Comment by johnsonmh** [comment]
Note, you should be able to force the single line of text to use the height pulled from the font file with `TextHeightBehavior`, which should alleviate the issue here.

Although I'm not sure if the text field cursor will cause any unexpected behaviors.

**Comment by pedromassangocode** [comment]
Reproduces on Flutter `1.26.0-2.0.pre.145`.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.145, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.145 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 38fe7e2b1c (7 hours ago), 2020-12-28 21:39:03 -0500
    • Engine revision 892034dc6a
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Redmi 5 Plus (mobile) • 0258ff700005 • android-arm64  • Android 8.1.0 (API 27)
    • macOS (desktop)       • macos        • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by Hixie** [comment]
cc @justinmc

**Comment by Hixie** [comment]
Update from @johnsonmh: He's unlikely to get to the line height stuff in the near term, so we should look at this specifically in the meantime, in case it turns out that the best fix is not the line height behaviour feature after all.

**Comment by Hixie** [comment]
cc @LongCatIsLooong

**Comment by Hixie** [comment]
@LongCatIsLooong any updates?

**Comment by LongCatIsLooong** [comment]
I've been playing with my `TextSpan` level (i.e. `TextStyle` level) `TextHeightBehavior` [implementation](https://github.com/flutter/engine/compare/master...LongCatIsLooong:block-level-text-height-behavior). Is there a use case for per-textspan `TextHeightBehavior`? The layout of the text blobs (and the overall line box height) doesn't seem to be easy to reason about when you mix these 2 behaviors in the same line:

<img src="https://user-images.githubusercontent.com/31859944/105879331-e5431f00-5fb6-11eb-9db7-d7a44b8f9c3b.png" width=10%> <- there're 2 "abcdefghijkl" `TextSpan`s side by side and one uses half-leading and the other ascent/descent scaling, with the same `TextStyle.height` value. This doesn't seem particularly useful.
<img src="https://user-images.githubusercontent.com/31859944/105882181-36084700-5fba-11eb-8435-00c304f2c269.png" width=10%> <- somewhat confusing overall line box height. `TextStyle.height` is set to 0 for both `TextSpan`s but the line box height (in blue) is not empty. This is not a problem if we prevent `leading` from going negative (i.e., change to A/D scaling when `TextStyle.height` < 1.0) as @johnsonmh suggested in go/flutter-half-leading, but that slightly deviates from the css spec and requires special casing when height is smaller than 1.0)

Additionally, let `TextStyle.textHeightBehavior` inherit from `ParagraphStyle.textHeightBehavior` makes the inheritance a bit more convoluted since `TextStyle` already has an `inherited` property and can inherit attributes from parent `TextSpan`s or `DefaultTextStyle`s.

Would it be sufficient to keep the configuration at paragraph level?

**Comment by johnsonmh** [comment]
My main concern about putting this on the paragraph level is how it will work with Material Text Themes. For example, the body text of dialogs gets `TextTheme.bodyText1`, if a theme calls for `bodyText1` to have a line height of `1.25`, but with half-leading not AD scaling, how would the user specify that?

If the option is on the `TextStyle` level, in the users theme they will specify: 
```dart
TextTheme(
  bodyText1: TextStyle(
    height: 1.25, 
    lineHeightBehavior: LineHeightBehavior.halfLeading, 
    ...
  ),
),
```

If the option is on the paragraph level, I don't know what it would look like to specify the line height + behavior to make sure they don't have the "text not centered" issue.

**Comment by LongCatIsLooong** [comment]
@johnsonmh  in that case should we deprecate  `DefaultTextStyle.textHeightBehavior` or even the `DefaultTextHeightBehavior` widget? The number of things in the framework that may affect the `TextHeightBehavior` is a bit concerning. For example:

In a `Text` widget the defaulting order would look like this with `TextStyle.textHeightBehavior`: `Text.textStyle.textHeightBehavior` -> `DefaultTextStyle.textHeightBehavior` > `DefaultTextStyle.style.textHeightBehavior` > `DefaultTextHeightBehavior.textHeightBehavior`. 

that said, would it be sufficient to use an app-level `DefaultTextHeightBehavior` and set the entire app to use half-leading? Are there cases where we would want to use both half-leading and ad scaling in the same app? I'm under the impression that most design tools and css use half-leading?

**Comment by johnsonmh** [comment]
I agree with your statement of the problem, there are too many ways to configure the `textHeightBehavior` that may be confusing or conflicting. 

Personally, my ideal API is to remove `DefaultTextStyle.textHeightBehavior`, `DefaultTextHeightBehavior`, `Text.textHeightBehavior` all in favor of `TextStyle.textHeightBehavior`. The pros of such a migration may or may not outweigh the cons.

> would it be sufficient to use an app-level DefaultTextHeightBehavior and set the entire app to use half-leading? Are there cases where we would want to use both half-leading and ad scaling in the same app? I'm under the impression that most design tools and css use half-leading?

I don't imagine that mixing and matching will be very common, the concern is more around how it will play with theming. Creating a `ThemeData` for your app involves setting a `TextTheme` with all of your `TextStyle`s. Then, you take that and plug it into `MaterialApp.theme`. None of this involves inherited widgets or the widget tree at all, and having to add an inherited widget kind of breaks the flow. Especially if you're getting a `ThemeData` from an external library, if it specifies line heights, you would want it to also specify the line height behavior.

That being said, yes, setting `DefaultTextHeightBehavior` once isn't _that bad_ (that's why we created it!). As long as it works fine with routes and everything.

**Comment by Hixie** [comment]
I've no objection to us eventually removing TextHeightBehavior from ParagraphStyle and all the knock-on-effects of that (such as removing it from Text), but we'd have to do that incrementally via deprecation, and we probably couldn't automate it. Long story short, we'd still have to support the current API for a year or more and so we still have all of these problems to deal with regardless.

**Comment by LongCatIsLooong** [comment]
One additional concern is that having `applyHeightToFirstAscent` and `applyHeightToLastDescent` in `TextStyle` is slightly confusing. With the current implementation every styled run (and the strut) in the first/last line must have consistent `applyHeightToFirstAscent`/`applyHeightToLastDescent` to produce the expected leading. Would it be better to not reuse `TextHeightBehavior`?

The PR is ready for review. Will verify with Christian that it matches figma/css.

**Comment by Hixie** [comment]
> Would it be better to not reuse `TextHeightBehavior`?

Can you elaborate on what you the API you are proposing would look like?

**Comment by LongCatIsLooong** [comment]
> Can you elaborate on what you the API you are proposing would look like?

Keep `TextHeighBehavior` a paragraph-level property, and add `LeadingDistribution` to `TextStyle`, so `applyHeightToFirstAscent` and `applyHeightToLastDescent` are still configured per-paragraph. It's the same as the recommended solution in `go/flutter-half-leading`.
This ensures `applyHeightToFirstAscent` and `applyHeightToLastDescent ` work in a line-break-invariant way. But I'm not sure if it's desirable to add  `applyHeightToFirstAscent` and `applyHeightToLastDescent` to theming @johnsonmh ?

**Comment by Hixie** [comment]
I don't have a strong objection to splitting things that way. I think both ways will end up with some level of subtlety that'll lead to some confusion. If you prefer that particular setup I think we should go with that since you're writing the code. :-)

**Comment by LongCatIsLooong** [comment]
With #77001 landed this should work if you're using libTxt. Lowering the priority.

**Comment by LongCatIsLooong** [comment]
All the functionalities should be in (except for the HTML renderer which uses half-leading by default). 

I was planning to create an interactive example but it seems I'd have to wait until the feature lands in the stable channel: https://github.com/dart-lang/dart-pad/issues/774. Closing.
