### ISSUE TITLE
99th_percentile_frame_rasterizer_time_millis regression on engine roll...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#72750]
https://flutter-flutter-perf.skia.org/e/?begin=1608245265&end=1608571746&keys=Xf5c75aaa34c194d39513caee2051940e&num_commits=50&request_type=1&xbaroffset=22916

https://github.com/flutter/flutter/commit/194711e5091aecb655d084aea90310e6e9058583

/cc @zanderso This week's engine sheriff.

**Comment by zanderso** [comment]
Comparing before/after that engine roll, I'm not able to reproduce this locally on my Nexus 5x. The benchmark appears bimodal, occasionally having a ~5-10% larger 99th %-ile frame rasterization. @CareF for advice.

**Comment by CareF** [comment]
`multi_widget_construction_perf__e2e_summary` test is designed to rebuild many widgets in the widget tree for every frame. The original motivation is to observe the cost of rebuilding the widget tree, but as a side effect there are many GCs during the test. If the larger number of the bimodal distribution comes from some random peaks in rasterize time/build time, this may be the issue. 
Previously we also see bimodal behavior https://github.com/flutter/flutter/issues/68620 where the app becomes slower as the test runs: this may be because of device thermal issue.

**Comment by jason-simmons** [comment]
I can reproduce this on a Moto G4 and bisected it to https://github.com/google/skia/commit/1d89532d5988c3e70f31fce471c6eb41ae68c05e.

Not sure why that change would affect the rasterizer metrics in this benchmark.

**Comment by kf6gpe** [comment]
@herbderby, this looks like something you committed --- any thoughts? Thanks!

**Comment by herbderby** [comment]
This would be *very* surprising. Looking at the trace, you don't have much history. The trace starts on Dec 16th, and this was flagged on Dec 18th. I suspect you are measuring something environmental, and not the code change.

**Comment by chinmaygarde** [comment]
Thanks for the clarification. Let's re-baseline and move on.
