### ISSUE TITLE
path_provider get's stripped out by proguard

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#72819]
Hi,

I ran today into this issue here:

https://github.com/flutter/flutter/issues/46679

And it seems it was caused in my case because Proguard is set to on by default since some point in the past. Before that I could build it without problems.

When adding 

```
            signingConfig signingConfigs.debug
            minifyEnabled false
```

to build.gradle

I finally got rid of the MissingPluginException,

I seems the reason is that path_provider doesn't add an entry to `lib\generated_plugin_registrant.dart` which would prevent the stripping out.

Used the latest version of path_provider: 1.6.24
I tired it on all channels with the same result.

**Comment by escamoteur** [comment]
cc @csells

**Comment by csells** [comment]
thoughts @amirh ?

**Comment by cachapa** [comment]
I'm having the same issue on all channels except for `stable`.

**Comment by thexaib** [comment]
same issue with path_provider 1.6.27
Flutter 1.26.0-2.0.pre.132 • channel master •

**Comment by blasten** [comment]
I'm a bit confused. `generated_plugin_registrant.dart` is a web thing.  Did you mean GeneratedPluginRegistrant.java? 

I'm unable to reproduce this issue if using `path_provider: 1.6.27` example app, and Flutter master.  Do you mind providing the exact steps that yield into this issue?

PSA: We enabled `minifyEnabled` by default for flutter run, but it has been on for `flutter build apk/appbundle` since more than a year.

**Comment by escamoteur** [comment]
@blasten it only shows up in release builds

**Comment by blasten** [comment]
Please see https://github.com/flutter/flutter/issues/46679#issuecomment-759701153. I strongly suspect that is the root cause. Otherwise, please reopen the issue!

**Comment by escamoteur** [comment]
@blasten but why is only this and not other plugins affected?
