### ISSUE TITLE
Flutter- GestureDetector not working with containers in stack

### ISSUE THREAD

**Issue by ycg520520** [flutter/flutter#72874]
``` dart

import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Center(
      child: Stack(
        clipBehavior: Clip.none,
        children: <Widget>[
          Container(
            color: Colors.green,
            constraints: BoxConstraints.tightFor(width: 50.0, height: 50.0),
          ),
          Positioned(
            top: -50.0,
            left: 25.0,
            child: GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () {
                  print('onTap ${DateTime.now()}');
                },
                child: Container(
                  color: Colors.blue,
                  width: 50.0,
                  height: 50.0,
                )),
          ),
        ],
      ),
    ));
  }
}
```
GestureDetector不能被点击在盒子外。

**Comment by ehsan-mrt** [comment]
I think the reason is that the container is outside of the stack. The portion which is outside of the stack is not clickable. Instead of this approach, you can create a stack with 2 containers inside. Align one of them to the bottom left of the stack and resize it to be slightly smaller to leave some room for the other container. Then set the alignment of the other container to the top right of the stack and resize it as you need. Then wrap the container with a GestureDetector and that should work.

**Comment by chunhtai** [comment]
doesn't seem to be a framework issue. closing as WAI

**Comment by ycg520520** [comment]
这和html+css布局表现不一致，在web端很容易实现这样的布局，可以轻松实现弹窗居中。
