### ISSUE TITLE
Improve Cupertino docs

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#72926]
By adding [snippets, samples, and dartpads](https://github.com/flutter/flutter/tree/master/dev/snippets)

**Comment by guidezpl** [comment]
Thanks for all your work @TahaTesser!

Just wanted to note the remaining items, as identified in #102812, for anyone looking to contribute: 
- [CupertinoActivityIndicator](https://master-api.flutter.dev/flutter/cupertino/CupertinoActivityIndicator-class.html)
- [CupertinoSearchTextField](https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html)
- [CupertinoSwitch](https://master-api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html)

**Comment by TahaTesser** [comment]
@guidezpl I'm on it! :)

**Comment by guidezpl** [comment]
Sweet, thank you :) 

As an aside, I noticed that since my system brightness is dark, some cupertino samples use dark mode as well. I wonder if we should just hardcode the theme to be light...

**Comment by TahaTesser** [comment]
> As an aside, I noticed that since my system brightness is dark, some cupertino samples use dark mode as well. I wonder if we should just hardcode the theme to be light...

I'm aware of this, TBH since nobody complained I thought it only bothers me. 
I have a local Cupertino template set the light theme by default for testing Cupertino issues. 

Also, some examples don't show the text at all, due to this https://github.com/flutter/flutter/issues/48438

| Light | Dark |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/165967877-0bfcfe41-31ee-4ccf-89e1-fcaab0c0879a.png" height="250" /> | <img src="https://user-images.githubusercontent.com/48603081/165967865-683008fe-e232-4424-877c-41de92648c08.png" height="250" /> |



Thanks for your comment, it gives me a stronger to fix this now. I am on it.
