### ISSUE TITLE
Better describe BottomNavigationBarType.shifting's usage

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#72936]
Started off of https://github.com/flutter/flutter/issues/72778 originally. The user had trouble understanding the color behavior for BottomNavigationBar.shifting and how to define it.

`BottomNavigationBarType.shifting`'s behavior is probably not well exposed enough. It is described in a bullet point in the [BottomNavigationBar](https://master-api.flutter.dev/flutter/material/BottomNavigationBar-class.html) API doc, but we could do the following to improve the experience:

1) Create a pointer to [BottomNavigationBar] in the [BottomNavigationBarType.shifting] doc, saying something like "For a sample on how to use this type, see [BottomNavigationBar].
2) Add dartpad samples for BottomNavigationBar.

**Comment by emem365** [comment]
Hi @shihaohong, is this issue open for contributions? I'd like to try and fix this if possible. 

And, just to clear this up, what we need to do is, add a sample for BottomNavigationBarType.shifting to the BottomNavigationBar docs (a sample for BottomNavigationBar using the default type already exists on the page)?

**Comment by shihaohong** [comment]
Sure thing! 

Yes, basically we should add two samples: One for fixed and shifting in the `BottomNavigationBar` docs. Then, a sentence with a link in `BottomNavigationBarType` saying something like "For an example of each type, see [BottomNavigationBar]"

**Comment by emem365** [comment]
Got it. I'll get to it right away!

**Comment by emem365** [comment]
Hi @shihaohong, I created a sample that uses  BottomNavigationBarType.shifting by default, please take a look [here](https://dartpad.dev/37cf177da59ed4b424627ce70e68ee2b?null_safety=true). 
Also, since all I had to do to get this done was add a couple lines, I figured maybe we can merge the two separate samples into one. I wasn't really sure about this, so I created this in a separate dartpad. Have a look [here](https://dartpad.dev/9e0aec7d695d7aedc71c036c30231838?null_safety=true). 
Please take a look a let me know whichever you think seems better. 
I'll create a PR soon!

**Comment by shihaohong** [comment]
Hi @emem365, the sample looks good! I don't have a preference for creating a new sample or merging the existing one. So, just choose whichever approach you prefer

**Comment by emem365** [comment]
@shihaohong , I linked a PR #73103  a few days ago. Let me know what you think about it whenever you can review him.
