### ISSUE TITLE
Hot reload doesn't update assets

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7302]
I added an image to my flutter.yaml and hot reloaded, but the image didn't show. I did a full restart and it worked.

cc @johnmccutchan

**Comment by johnmccutchan** [comment]
The issue here is:

When the application first boots it is using assets and script sources pulled from the APK/IPA installation directory. When we reload we switch to script sources from a temporary directory but not the assets. On a hot-restart we also switch the asset directory.

To fix this:

1. Add a new service protocol RPC that tells the engine to look in a specific directory for assets. This is mostly implemented today by the existing `_flutter.runInView` RPC which takes an `assetDirectory` parameter.
2. Send this RPC after the first reload.
3. Make sure that any cached assets are evicted.

**Comment by a-siva** [comment]
@aam does this change with the new incremental kernel generator implementation? Since the sources are not pushed we should be able to switch to the assets directory right.

**Comment by aam** [comment]
I don't think it changes with IKG. We still want to explicitly switch assets directory on hot reload by sending an RPC request(`_flutter.setAssetDirectory` , for example?) to flutter engine. Currently, only RPC request that is sent on hot reload is to `_reloadSources` to Dart VM to pick up updated sources(or kernel).

**Comment by aam** [comment]
This can be address with https://github.com/flutter/flutter/pull/12872 and https://github.com/flutter/engine/pull/4323

**Comment by Hixie** [comment]
Leaving in current milestone since "make hot reload trustworthy" is a priority.
