### ISSUE TITLE
I installed flutter SDK but I can not find the flutter sdk path

### ISSUE THREAD

**Issue by onlyformestudy** [flutter/flutter#73020]
## Steps to Reproduce

1. I can`t open the flutter_console.bat in my computer.
2. I installed the flutter SDK using git or in the flutter dev website, but both of them I couldn`t find the path of flutter sdk in Android studio
3. Also reinstalled all of them(Android studio, flutter sdk), but I still I can not find the path.
4. I set the system variable path but it didn`t work
5. Finally in my console "flutter doctor" is not working

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@onlyformestudy 
This seems to be an issue with your setup rather than issue with Flutter framework. Please consider asking this question on Stackover flow. Please see https://flutter.dev/community for resources.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
