### ISSUE TITLE
API Places isn't retrieving photos in the sample app

### ISSUE THREAD

**Issue by aoprado** [flutter/flutter#73065]
Hello.

I tried to run this app: https://github.com/flutter/samples/tree/master/flutter_maps_firestore, but there is a problem when I try to get the photos from the Places API.

The error is;
 **E/flutter (16331): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'photos' was called on null.**

Furthermore, the Firebase plugin version used in the code require the function "Firebase.initializeApp()". I tried to used it in my code, but it doesn't seems to be in the "right place". The app works, but I keep receiving this error also:

[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

**Comment by darshankawar** [comment]
@aoprado 
Your question / issue is better suited for StackOverflow since it's not an issue with Flutter framework but issue with code implementation.

Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
