### ISSUE TITLE
Flutter release app keeps stopping

### ISSUE THREAD

**Issue by Ayonto** [flutter/flutter#73080]
I built an app bundle of my app and released it on Play Store. But when I install the app and run it it stops immediately saying 
example_app(app name) keeps stopping.
I'm fetching data in api calls in the app. I have also added necessary permissions such as Internet permission on the AndroidManifest file.
I can't find the solution of this and don't know why this is happening.

my flutter doctor -v : 

![image](https://user-images.githubusercontent.com/58147322/103280434-9aa3a680-49fa-11eb-873d-ddcec85f7ddc.png)

I've used **flutter build appbundle** to build my bundle
app is releases on playstore but when someone opens it doesn't start and says **example_app(app name) keeps stopping**

I don't know what to do now

**Comment by darshankawar** [comment]
@Ayonto 
Are you able to see the issue locally in non-prod environment ?
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that we can copy paste and run to see the issue.

**Comment by Ayonto** [comment]
@darshankawar I've added my flutter doctor please help me out

**Comment by darshankawar** [comment]
@Ayonto 
Your channel shows `unknown 0.0.0` so not sure what version are you on. You need to be on any of either latest stable, dev, beta or master in order to function your app properly. Please switch to a proper channel and then provide the `flutter doctor -v`. We also need to see a complete minimal reproducible code sample that shows the issue you are facing.

Also, do you have any stacktrace or logs that will show why the app is stopping ? Unless there's a log that shows any error, it'll be difficult to analyze the issue. So if possible, provide a log of the issue where the error occurs.

**Comment by Ayonto** [comment]
@darshankawar yes I just reinstalled flutter now everything is fine in flutter doctor
Google Play console sent me a crash report saying java.lang.ClassNotFoundException
I don't know what it is

**Comment by darshankawar** [comment]
@Ayonto 
In order to better address your issue, it would be helpful if you could provide a minimal complete reproducible code sample that shows the issue. I'd suggest you to try to look into your code and the crash report and see where exactly are you getting this error.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
