### ISSUE TITLE
ListItem should call out that it's intentionally fixed height

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7318]
https://github.com/flutter/flutter/issues/7311#issuecomment-269754638
We've had other (internal) customers with this confusion too.  We should even consider renaming it MaterialListItem to be more clear (since the material namespace doesn't really do much).  A paragraph explaining that it's intentionally fixed height and what to do instead seems useful?

Thoughts @Hixie?

**Comment by Hixie** [comment]
I have a post-it on my desk with the new name. It's part of the post-refactor cleanup.

**Comment by Hixie** [comment]
The doc part will go in a patch soon.

**Comment by HansMuller** [comment]
The plan is top rename ListItem to ListTile. The docs have already been updated to reflect its fixed sizes.

Calling this widget ListItem caused some confusion because the name implies that the widget is a universal list entry. One that's an arbitrary size and not Material Design specific. The Material Design spec uses the term "tile" for list entries which is evocative of something that comes in fixed sizes.
