### ISSUE TITLE
I have installed android studio and flutter with the instruction provided on flutter website, and also installed the packages of dart and flutter in android studio but then also it is not showing me the option to create a flutter app on the home screen.

### ISSUE THREAD

**Issue by PuneetDadhich** [flutter/flutter#73183]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by PuneetDadhich** [comment]
please resolve it or tell me how to troubleshoot that issue.

**Comment by iapicca** [comment]
@PuneetDadhich 
can you please run from terminal 
```bash
flutter doctor -v
flutter create example -v
```
and provide the full output

**Comment by TahaTesser** [comment]
Hi @PuneetDadhich 
After installing plugins in Android Studio, restart Android Studio and then you will `create new flutter project`
<img width="675" alt="Screenshot 2021-01-04 at 2 33 26 PM" src="https://user-images.githubusercontent.com/48603081/103518499-dd9dc800-4e99-11eb-88cc-701073c301c9.png">
Also if you've added Flutter in your environment path, you can create a project using terminal using `flutter create mydemo`

Since not enough info is provided to take action on this issue to consider it as a bug. I feel safe to close this issue.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
