### ISSUE TITLE
the real webview should be able kept in memory when webview_flutter not show;

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#73268]
as platformView has performance issue,  and the official document suggest using screenshot, but when using screenshot and the WebView should be removed from widget tree, then after that when I need to show the WebView, it is reloaded again, which is not acceptable, the content of webView should kept unchanged instead of reloaded to the first page;

so 
1. there should be one way the kept the webview from reloaded after removed from the widget tree and show again;
2. WebView_flutter should provided one function the get the screenshot as PlatformView doesn't support it #25306, so plugin should provide this function, we have implement this function and hope to accepted by the official ;

**Comment by TahaTesser** [comment]
Hi @wanjm
Wouldn't webview be too expensive for memory? Can you please explain the proposal in detail and provided some use cases
Thank you

**Comment by wanjm** [comment]
```
Stack(children:[
WebView(...),
MyAnimationWiget(...),
]);
```
but my animation is  slow with WebView under it, so I need to use screenshot of the WebView to as a placeholder; as following code shows;
```
Stack(children:[
WebViewScreenShot(...),
MyAnimationWiget(...),
]);
```
but when I try to sho WebView again( the first code), the WebView is reloaded for it has been disposed as it removed from widget tree  and the reloading takes a lot of time. So i need the webview in memory and when it returned to widget tree, it show the previous page immediately.

**Comment by TahaTesser** [comment]
Hi @wanjm 
It doesn't sound realistic to keep webview in memory for this usage. You can approach this issue in other ways,
You can use native view or try to hide webview instead of destroying it or some native code solution, or ask in Flutter community you get other suggestions based on your desired results.

Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wanjm** [comment]
sorry, I have tried to surround with SizedBox(width:0,height:0,child:WebView),then the webView can't be hidden;
and then I use SizedBox(width:1,height:1,child:WebView), it is also slow;
so hide doesn't work;

**Comment by TahaTesser** [comment]
Hi @wanjm 
As mentioned https://github.com/flutter/flutter/issues/73268#issuecomment-754477406, there could be various ways to acehive

**Comment by wanjm** [comment]
thanks @TahaTesser
