### ISSUE TITLE
InputDecoration label text not accepting bigger text. It shows elipses (...) at the end

### ISSUE THREAD

**Issue by sanjay070783** [flutter/flutter#73321]
I am new to flutter and using some form elements where using InputDecoration provide element text. If labelText goes bigger then it is truncating text and showing three dots at the end. Any way to make this work? Please help, let me know if more information required from my end. Any way to display multilines if text is bigger?

**Comment by darshankawar** [comment]
@sanjay070783 
Your question is better suited for StackOver flow since it seems to be a support question. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
