### ISSUE TITLE
[web] Need kIsWebHtml & kIsWebCanvasKit, need ability to find out current renderer from app code set by "Auto detect mode".

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#73369]
"Auto detect mode" was added recently by this PR: https://github.com/flutter/engine/pull/21852
But there is no ability to find out from the code which renderer was actually set by auto setting.
It has to be exposed to Flutter app, preferable as constant. We have kIsWeb, probably adding kIsWebHtml and kIsWebCanvasKit will cover all cases.

**Comment by TahaTesser** [comment]
Hi @slavap 
That sounds like a good idea to me
Thank you

**Comment by yjbanov** [comment]
@slavap What's the use-case for this feature? Our goal is for both renderers to work equally.

**Comment by slavap** [comment]
@yjbanov Your goal is unfortunately just a distant future :-( The reality is quite opposite. For example: SVG images (works fine with html renderer, but need third party library to work with canvasKit).

**Comment by jpeiffer** [comment]
As the author of one of the SVG projects, it would help me create a bridge for the users of my library until the SVG stuff is fixed.  As @slavap mentioned, the `Image.network` is the only way to render SVGs in HTML mode, but the `flutter_svg` project is needed to render in Canvas mode.

Previously, my library worked by detecting native (using `flutter_svg`) and web (`Image.network`), but the fact that Web is split as well, I now have no reliable way to detect and pick the right render mode.

Here's a relevant issue from my repo that may provide background / context:
https://github.com/peiffer-innovations/websafe_svg/issues/15

**Comment by deakjahn** [comment]
@TahaTesser This is **very** bad. You really can't implement an auto detection without thinking about packages and plugins that need to adapt to which engine is used. As a minimum, you really have to add at least a

    @JS('window.useCanvasKit')

in `lib/web_ui/lib/src/engine/canvaskit/initialization.dart` so that it can be at least read on the JS side. Providing a constant up to the Flutter app level would be a nice bonus but not being able to check it even on the JS side is, well, a showstopper for those poor plugin developers that have to work around the differences in the rendering engines.

**Comment by deakjahn** [comment]
@yjbanov Yegor, sorry, that's the wrong kind of thinking. It might be a goal up on the Flutter app level, but we, plugin developers who provide new functionality that works with the low level, yes, providing a unified approach up there for our users, this is indispenasble. Just as an example, I have my `flutter_dropzone` plugin where I just mentioned this issue. The whole setup of the underlying HTML page is radically different between CanvasKit and DomCanvas, thus I have to adapt to that in order to be able to provide a service that's already unified for my plugin users.

**Comment by yjbanov** [comment]
You can do this today by checking for `window.flutterCanvasKit`. If it's not null or undefined, then you are using CanvasKit. Otherwise, it's HTML. We will reevaluate adding a proper stable API for this in the future, but for now we still aim to make the two backends as close to each other as possible.

**Comment by slavap** [comment]
Confirming that in Flutter the following code works successfully:
```dart
import 'dart:js' as js;

bool get rendererCanvasKit {
  var r = js.context['flutterCanvasKit'];
  return r != null;
}
```
