### ISSUE TITLE
I want reader mode in web view. because it is very important.

### ISSUE THREAD

**Issue by irvanthole** [flutter/flutter#73399]
can anyone help me to find this solution? I am developing the application and when I register a policy popup will appear with a webview, I need reader mode in the web view.

**Comment by pedromassangocode** [comment]
Hi @irvanthole 
I don't think this is possible since the native Android API for that [was deprecated and has not effect when used](https://developer.android.com/guide/webapps/migrating.html#Columns). See [this SO answer](https://stackoverflow.com/questions/32664338/android-webview-with-reader-mode/46060576) for reference.
