### ISSUE TITLE
Weird 3D effect in ToggleButtons

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#73403]
When `canvaskit` is used as web renderer than widget `ToggleButtons` has weird 3D effect on switching.
![toggle-buttons-canvas-kit](https://user-images.githubusercontent.com/45417992/103757678-c5ed4d80-5019-11eb-9238-3112677ede16.png)

**Comment by pedromassangocode** [comment]
Hi @bambinoua 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by bambinoua** [comment]
```
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19041.685], locale ru-RU)
    • Flutter version 1.25.0-8.2.pre at D:\Programs\Flutter\sdk\flutter
    • Framework revision b0a2299859 (18 hours ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Platform android-29, build-tools 29.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
```
Create a release version:
```dart
flutter build web --web-renderer canvaskit --release
```
Sample:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _isSelected = List.generate(3, (index) => false);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Center(
        child: ToggleButtons(
          children:
              List.generate(_isSelected.length, (index) => Text('$index')),
          isSelected: _isSelected,
          onPressed: (index) {
            setState(() {
              for (var i = 0; i < _isSelected.length; i++) {
                _isSelected[i] = i == index;
              }
            });
          },
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment]
I was able to reproduce this on latest beta and master and channel. I can confirm that this is a CanvasKit only issue.

![Screen Shot 2021-01-07 at 12 28 57](https://user-images.githubusercontent.com/67424416/103887782-f0a3d880-50e3-11eb-8fbb-bc56848f0365.png)

<details><summary>flutter doctor (master)</summary>

```

```
</details>

<details><summary>flutter doctor -v (beta)</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-8.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision b0a2299859 (2 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by bambinoua** [comment]
So should I post an issue to them?

**Comment by pedromassangocode** [comment]
Here is the right place to post the issue. Thank you for doing that!

**Comment by rxlabz** [comment]
I'm having the same effect with Flutter Desktop macOS on the dev branch.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on Mac OS X 10.15.7 19H114
    darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by rydmike** [comment]
This is a very old issue, it has always existed since the first version when Flutter Web and `ToggleButtons` coexisted. Saw it maybe a year ago first time. Decided to ignore it then, but I was recently reminded of it the other day as well when I did a simple theme mode toggle button example:

https://twitter.com/RydMike/status/1356443727959588866?s=20
![image](https://user-images.githubusercontent.com/39990307/106767875-00abcb00-6644-11eb-9748-30918c8b8870.png)

I found this issue since I was about to report it too, so dropping some insights on it here.

----

The issue is simple enough to fix and I think it should be fixed. Having this kind of 3D elevated hover as the default style is not a very modern look or design, but perhaps it is the Material way, not sure, did not check specs. 

This issue also applies to all desktop platforms, it would apply to devices too if you could hover or move focus to a 'ToggleButtons` button on those platforms. It would indeed be nice to get a fix for this design before web and desktop platforms hit stable.

## Why does it look this way? 

The 3D elevation effect on **hover** and **focus** come from the `RawMaterialButton` that `ToggleButtons` uses in its implementation.

`ToggleButtons` sets, `elevation` and `highlightElevation` to 0, and they are not exposed by `ToggleButtons` API.

![image](https://user-images.githubusercontent.com/39990307/106767065-2be1ea80-6643-11eb-91c1-2f146ed0351a.png)

The `RawMaterialButton` also has `disabledElevation` that default to 0 and it is not set by `ToggleButtons`. 

The problematic `RawMaterialButton` properties are however, 'focusElevation` and `hoverElevation`, they both default to 4 and are not set not set, nor exposed by `ToggleButtons`, 

![image](https://user-images.githubusercontent.com/39990307/106767696-d0fcc300-6643-11eb-83d3-5bbfafe34d94.png)

So we then see those 3D elevations by default on `ToggleButtons` when it is **hovered**, or **focused** by moving to it with TAB on Web or Desktop. There is nothing we can do to remove the effect since the API that would allow its removal is not exposed by `ToggleButtons`.

At the very least `Togglebuttons` need to expose all the different `elevation` properties by the used `RawMaterialButton` in the implementation, so they can be modified as required.

Personally I think that defaulting `focusElevation` and `hoverElevation` to 0 as well, would also be a welcome small breaking change. Then those that like or must have 3D hover/focus effects from the ´90s can the put them back manually. 😄

**Comment by yjbanov** [comment]
@rydmike thanks for the detailed analysis! Sounds like the issue is on the framework/material side.

/cc @goderbauer @HansMuller

**Comment by rydmike** [comment]
It can indeed be solved in the Material layer of the SDK by just letting ToggleButtons expose a few properties from RawMaterialButton it uses, so users can adjust the look. Another question, or design choice, is of course if it should offer such configuration. If not, then flat focus & hover is probably preferred and it should set the two offending elevations to 0 in its RawMaterialButtons, Which again could be considered a small visual breaking change, but I doubt there is any test for the look, I did not check though.

It probably looks the way as it does due to an oversight, since this visual cannot be seen on current two stable platforms that don't have focus and hover highlights.

In either case it is a simple fix. A bit more if the properties are exposed as they also need to be added to Widget's theme. Personally I think including the properties is a good way, as it offers more config options to devs, I also think that even in that case the props should default to 0, as that is probably what is desired in +80% of cases.

**Comment by HansMuller** [comment]
@rydmike - I agree that the hover and focus elevations for toggle buttons should just be zero. Similar issues have  come up before - for example https://github.com/flutter/flutter/pull/65662 - however, in this case I don't think a tricky solution is needed.  

Note also: as you pointed out, this isn't a web-specific issue, it occurs anywhere the focus or hover highlights come into play.

I'm going to try and land a simple fix. Existing (internal) golden image tests are likely to be the only obstacle.

**Comment by rydmike** [comment]
@HansMuller wow thanks that was fast, it already landed in master! 💙 

I totally agree the quick fix of you did of just setting focus, highlight and hover elevations to 0 is probably all that 99% of cases will ever need or use with this Widget. No need to expose them, at least not now.

Funny thing I was just going to set them to 0 to see what it looks like, but when I built my test case with master they were already flat since your fix had already landed. Nice! Thanks again. 😃 

----

To anybody else dropping by to check up on this issue. 

This is what the fixed **ToggleButtons** with flat highlight, hover and focus looks like with the default Flutter Light `theme: ThemeData.from(colorScheme: ColorScheme.light())` and Dark `darkTheme: ThemeData.from(colorScheme: ColorScheme.dark())`.

![ToggleButtonsDef-scheme1](https://user-images.githubusercontent.com/39990307/107028165-dd089200-67b5-11eb-854a-04bc9fbe0c55.gif)

As you can see the Dark mode hover is not so visible, the focus is bit more visible in dark mode, but can also be hard to spot as well. But you can easily adjust that by setting your ToggleButtons or its ThemeData to for example:

```dart
      hoverColor: Theme.of(context).colorScheme.primary.withOpacity(0.2),
      focusColor: Theme.of(context).colorScheme.primary.withOpacity(0.3),
```

For a slightly more visible hover and selection in dark mode, the above adjustment would look like this instead:

![ToggleButtonsDef-scheme2](https://user-images.githubusercontent.com/39990307/107030007-9d8f7500-67b8-11eb-96f2-bc7d4ce481e5.gif)


The code for this demo theme toggler is available here: https://github.com/rydmike/theme_demo, but using another color scheme.

**Comment by bambinoua** [comment]
Just for remind, that this 3D effect is occurred *only* when **canvaskit** is used as web renderer. IF renderer is **html** `ToggleButtons` loos fine (but fonts on some widgets become "jumping").

**Comment by rydmike** [comment]
@bambinoua It occurred also on all desktop builds. It has been fixed now. Not sure how far down the fix has progressed channel wise, but it is at least available on master.

**Comment by bambinoua** [comment]
We work on `beta` channel and it is still not fixed for us.

**Comment by woprandi** [comment]
@bambinoua the commit has not reached beta channel yet
