### ISSUE TITLE
How do I build a release app with --no-sound-null-safety?

### ISSUE THREAD

**Issue by Andreigr0** [flutter/flutter#73485]
I can run an app in release mode on my phone with passing flag `flutter run --no-sound-null-safety --release`, but 
neither `flutter build apk --enable-experiment=non-nullable` \
nor `flutter build apk --no-sound-null-safety` \
nor `flutter build apk --enable-experiment=non-nullable --no-sound-null-safety` \
will work

So how do I build a release APK?

**Comment by pedromassangocode** [comment]
Hi @Andreigr0 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Since Null-safety has nothing to do with the flutter build  command but the code. You just need to migrate your code and packages and then use the command to build the app. See https://stackoverflow.com/a/65117431 to learn how to enable null-safety in your code.

**Note:** Null-safety is still a beta feature and it is  not recommended to be used in release mode!


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Andreigr0** [comment]
@pedromassangocode I set Dart version to 2.12 for a project and use Flutter beta version 1.25.0-8.2.pre and can't build a release app, so in my opinion it is a bug
