### ISSUE TITLE
[local_auth] Give feedback immediately when an fingerprint error is identified

### ISSUE THREAD

**Issue by Godfather6666** [flutter/flutter#73550]
如果我想local_auth插件的指纹验证功能在一次错误的验证后立刻反馈给我该怎么做，验证指纹如果失败立即返回错误而不是在验证数次失败之后才返回

**Comment by pedromassangocode** [comment]
Hi @Godfather6666 
Can you please elaborate what this issue is about? I'm not sure if I understood you right.

Please avoid comments in language other than English as Flutter uses English as the language for communications.
Thank you

[from Google Translate]
@Godfather6666嗨，您能详细说明一下这个问题吗？ 我不确定我是否理解正确。 请避免使用英语以外的其他语言发表评论，因为Flutter使用英语作为交流语言。 谢谢

**Comment by Godfather6666** [comment]
> @ Godfather6666嗨，
> 您能详细说明一下这个问题吗？我不确定我是否理解正确。
> 
> 请避免使用英语以外的其他语言发表评论，因为Flutter使用英语作为交流语言。
> 谢谢
> 
> [来自Google翻译]
> @ Godfather6666嗨，您能详细说明一下这个问题吗？我不确定我是否理解正确。请避免使用英语以外的其他语言发表评论，因为Flutter使用英语作为交流语言。谢谢

I want LOCAL_AUTH to give feedback immediately when an error fingerprint is identified, rather than after multiple errors have been locked. How do I do that

**Comment by Godfather6666** [comment]
Sorry, I think my English is not good, so I use the translation software to translate these.

**Comment by stuartmorgan** [comment]
Is this for Android, iOS, or both?

**Comment by maxakak1998** [comment]
I think it should include this feature for both of Andoird and IOS. Any update ?

**Comment by stuartmorgan** [comment]
This is not configurable in the underlying system APIs, do can't be implemented in the plugin.
