### ISSUE TITLE
Linux Arm Host Engine builds not producing `gen_snapshot` for profile or release

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#73625]
In an effort to unblock https://github.com/flutter/flutter/pull/61221, I am trying to generate the linux arm desktop package, `linux-arm64-flutter-gtk.zip`, but I'm running into a missing `gen_snapshot` file that is present in the x64 builds.

With the regular [linux engine](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#673) build, we do:

```
RunGN(api, '--runtime-mode', 'profile', '--no-lto')
Build(api, 'host_profile')
```

Then we [bundle](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#656) `src/out/host_profile/gen_snapshot` into `linux-x64-flutter-gtk.zip`.

I'm trying to do the same for [linux arm engine recipe](https://flutter-review.googlesource.com/c/recipes/+/9640), with:

```
RunGN(api, '--runtime-mode', 'profile', '--no-lto', '--target-os=linux', '--linux-cpu=arm64')
Build(api, 'linux_profile_arm64')
```

But the [build fails](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/cfac55aa5d0b6259abe073fd4e03e394349f2fdac24e982f231e6f91edb2ed42/+/build.proto?server=chromium-swarm.appspot.com) with:

```
OSError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/src/out/linux_profile_arm64/gen_snapshot'
```

I'm not sure why this file is not being generated, and whether a change is needed in the engine config or dart.

**Comment by HidenoriMatsubayashi** [comment]
Thank you! I will also investigate. In the case of linux-x64, `src/out/host_profile/gen_snapshot` and `sr/out/host_profile/gen_snapshot_product` are generated.

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure yet, but in the linux-x64 case, the files are generated in bellow.

 - out/host_release/dart-sdk/bin/utils/gen_snapshot -> out/host_release/gen_snapshot
These files are the same binary.

- out/host_release/gen_snapshot_product
I'm not sure the difference between `gen_snapshot` and `gen_snapshot_product`.

On the other hand, the files for arm64 are generated in bellow. 
- out/linux_release_arm64/dart-sdk/bin/utils/gen_snapshot -> out/linux_release_arm64/gen_snapshot_product
These files are the same binary. But it renamed and there isn't original `gen_snapshot_product`.

**Comment by HidenoriMatsubayashi** [comment]
I think I got it. I think that we need to use ` out/linux_release_arm64/gen_snapshot_product` for the engine artifact in the linux-arm64 case. Naturally, we need to rename from `gen_snapshot_product` to `gen_snapshot` when we bundle it to the engine Artifacts.

Common files such as `flutter_pacthed_sdk` (platform_strong.dill, vm_utline_strong.dill etc) which are not CPU architecture dependency are generated on a host build machine. But if the target CPU which is `linux-cpu` in gn command option and the host CPU which is build machine are different, that is, cross-build, you need to build the tools needed to generate those files for the host CPU. If the target CPU is arm64, binary files for the host CPU (x64) will be created under `src/out/linux_*_arm64/clang_x64`. Then common files like 'platform_strong.dill' are generated by  `src/out/linux_*_arm64/clang_x64/gen_snapshot`.
Note: `src/out/linux_*_arm64/clang_x64/gen_snapshot` is a binary for **x64** hosts

On the other hand, if the target CPU and host CPU are the same, that is target CPU is x64, `clang_x64` directory will not be created. All files are generated under `out/linux_*_x64` instead. Therefore there is a `gen_snapshot` under 'out/linux_*_x64'.

But I'm not sure why the artifacts of linux-x64 currently uses `out/linux_*_x64/gen_snapshot` instead of `out/linux_*_x64/gen_snapshot_product`.

**Comment by chinmaygarde** [comment]
cc @zanderso

**Comment by christopherfujino** [comment]
per @zanderso, we might not want to use `gen_snapshot_product`, as this is generated by the Dart SDK build rules, but I will defer to him.

**Comment by christopherfujino** [comment]
I think [this PR](https://github.com/flutter/engine/pull/23694) should un-block this issue.

**Comment by HidenoriMatsubayashi** [comment]
I think so, too :)
