### ISSUE TITLE
[Feature Request] Option to use markNeedsBuild instead of setState

### ISSUE THREAD

**Issue by NWalker1208** [flutter/flutter#73648]
## Use case

As I've been developing with Flutter, I've always felt that the setState workflow was rather unintuitive. You pass a function who's entire purpose is just to change state that you could have changed before calling setState. Looking at the source code, all setState does is call the function that you gave, then call markNeedsBuild. There is no asynchronous behavior, nor does your function get put on some sort of queue to be called at a specific time. There are some asserts that make sure a rebuild is not happening at the wrong point in time, but these checks could just as well occur in a markNeedsBuild method.

So, then, what is the point of having to nest a function within setState when all it does is call your function, then call markNeedsBuild? This nesting just seems to create cluttered code.

## Proposal

The state class should provide a markNeedsBuild method that we can call when we find it appropriate to do so. For example, after changing a widget's state. Plus, this better mimics how RenderBoxes call markNeedsPaint or markNeedsLayout when something changes.

For the sake of backwards compatibility, the behavior of setState method does not need to be changed in any way. This would just be an additional method of State that does practically the same thing as setState without asking for a function to call.

While this behavior could be mimicked by calling setState with an empty function, that would look confusing to someone reading the widget's code. Having a standalone method that is appropriately named would make much more sense.

**Comment by iapicca** [comment]
> ## Proposal
> The state class should provide a markNeedsBuild method that we can call when we find it appropriate to do so. For example, after changing a widget's state. 

AFAIK `setState` essentially does call `markNeedsBuild` after some checking 
```dart
@protected
void setState(VoidCallback fn) {
  /// `doing stuff`
  _element.markNeedsBuild();
}
```

how calling directly `markNeedsBuild` would make it `async friendly`?

**Comment by NWalker1208** [comment]
> @NWalker1208 
> 
> > ## Proposal
> > The state class should provide a markNeedsBuild method that we can call when we find it appropriate to do so. For example, after changing a widget's state. 
> [...]
> 
> AFAIK `setState` essentially does call `markNeedsBuild` after some checking 
> ```dart
> @protected
> void setState(VoidCallback fn) {
>   /// `doing stuff`
>   _element.markNeedsBuild();
> }
> ```
> 
> how calling directly `markNeedsBuild` would make it `async friendly`?
> you would circumvent the assertion, but changing the widget state while building won't end well

That's true, however, I don't think this would be any different from how async friendly setState is right now. You can just as well call setState from an async function, and doing so doesn't seem that uncommon (i.e. setting state after loading a file). SetState has no way of telling if it's been called from an async function, it only checks if the function it was given to set the state returns a future. Using an async function to change state and call markNeedsBuild would do exactly the same thing as calling setState from an async function.

**Comment by adrianflutur** [comment]
Hi, I just wanted to say that `setState` is not useless nor pointless as it has at least three roles.

The first one is to guide, or maybe "trick" the user into believing that any assignments that will eventually change the state should be passed into that function. This way he will not call `markNeedsBuild` everywhere, for no real reason.

The second is that React Native (and perhaps other frameworks) uses the exact same concept, and I guess Flutter is trying to supply similar syntax in order to be easier to understand for RN devs.

The third may be that `markNeedsBuild` is exposed to the end user through `setState` so that if at some time they decide to rename it to, say, `rebuild`, then the end user would not be affected by this. Otherwise, everyone would have to rename all occurences of `markNeedsBuild` with `rebuild` everywhere, in every class.

So, if you really wanna use it like this (note that I didn't see anyone using it this way in production code), you can define your own extension method and/or a mixin to achieve this:
```dart
extension MarkNeedsBuildExtension<T extends StatefulWidget> on State<T> {
  void markNeedsBuild() {
    (context as Element).markNeedsBuild();
  }
}
```
or
```dart
mixin MarkNeedsBuildMixin<T extends StatefulWidget> on State<T> {
  void markNeedsBuild() {
    (context as Element).markNeedsBuild();
  }
}
```

**Comment by pedromassangocode** [comment]
Hi @NWalker1208 
I don't think this is a valid proposal for Flutter at least because there is no benefits and valid reasons to make this change in the framework. See https://github.com/flutter/flutter/pull/54009#pullrequestreview-389345587 as I think it somehow answer this proposal.

And as suggested above, you can make use of Dart's extension methods to easily achieve this feature.
