### ISSUE TITLE
[pigeon] Add support for macOS

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73738]
## Use case

Currently, [pigeon](https://pub.dev/packages/pigeon) only supports generating for iOS and Java and allows very easy platform calls.

However, plugins might also want to support **macOS** and use pigeon for that.

### Implementation

It seems that using Swift could also be beneficial for the iOS generation that pigeon already supports.

### Other desktop platforms

See also:

* Windows feature request: https://github.com/flutter/flutter/issues/73739
* Linux feature request: https://github.com/flutter/flutter/issues/73740

**Comment by gaaclarke** [comment]
I don't know that the generated code has a dependency on iOS.  It may work already for macOS, did you give it a shot?  I haven't tried it yet.

**Comment by creativecreatorormaybenot** [comment]
@gaaclarke Sounds interesting - should give it a try!

**Comment by pedromassangocode** [comment]
If it works, we may want to make sure to update the docs.

**Comment by creativecreatorormaybenot** [comment]
@gaaclarke @pedromassango Unfortunately, I did not find the time to try it out just yet. I think I will not be getting to it very soon; potentially someone else might try it.

If you do, it would be awesome to hear about it here :)

**Comment by stuartmorgan** [comment]
Since the canonical language for macOS plugins is Swift, I think it would be better to add Swift support to Pigeon before advertising it for macOS in the docs. I think it would be somewhat confusing for us to actively advocate for people adding ObjC code to their plugins, and adding a second language to the mix for people without a lot of macOS experience could make things harder for developers to understand.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Yep, it is also the reason why I did not use it :)

**Comment by stuartmorgan** [comment]
(Also relevant: there was recent Discord discussion about how it would be nice for Pigeon to support null safety; one limitation is that ability to actually enforce it fully on the native side depends on language, and we could do so in Swift, but not really in ObjC.)

**Comment by gaaclarke** [comment]
Doesn't macOS development have the same bridging mechanism that iOS has?  While not ideal I didn't prioritize Swift because there was a workaround with the bridge.  I'm pretty sure it does have the bridge.: https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift

The generated Objc code should have the proper null safety annotations so it will work with Swift.

That said, I'd prefer to have Swift generation, it's just a matter of project prioritization and convincing the team to invest into it or finding someone willing to step up.

**Comment by stuartmorgan** [comment]
Yes, it definitely has the bridge. I expect it would work (there are plugins for macOS in the wild that use ObjC because they share most of their code with existing ObjC iOS plugins), and don't want to dissuade anyone from trying it out. I just don't think we should actually recommend its use for macOS since it encourages the addition of an extra language to most macOS plugins. Unlike iOS, we have only ever had Swift templates for macOS plugins.

> The generated Objc code should have the proper null safety annotations so it will work with Swift.

Work with, yes, but there's no meaningful enforcement of null safety in ObjC. Swift is a much better match for nullsafe Dart where it's actually part of the type system.

**Comment by xPutnikx** [comment]
> @gaaclarke @pedromassango Unfortunately, I did not find the time to try it out just yet. I think I will not be getting to it very soon; potentially someone else might try it.
> 
> If you do, it would be awesome to hear about it here :)

Hi,
I tried to use files generated by pegion in a macOS plugin. It works well with one tiny adjustment. In the generated files I manually replaced `#import <Flutter/Flutter.h>` with `#import <FlutterMacOS/FlutterMacOS.h>`

**Comment by Jordan-Nelson** [comment]
I was able to get this working on MacOS with @xPutnikx's workaround. One thing that was a little awkward was getting native source code generated for MacOS & iOS without manual intervention. As far as I know, there is no way to specify multiple locations for the native source code to be generated, so you either have to copy it manually between /ios and /macos or use two different classes with two different `ConfigurePigeon` annotations.

As part of official MacOS Support it might make sense to have a way to specify multiple output locations.

**Comment by gaaclarke** [comment]
Sorry, this was fixed in https://github.com/flutter/packages/pull/2587

**Comment by Jordan-Nelson** [comment]
@gaaclarke It seems to be addressed if swift is used for MacOS. It doesn't seem to be addressed if you want to use objective-c on MacOS. Might be worth a note in the readme? I'll probably switch over to swift now that it is supported, but I found it a little confusing that the objective c code is still not generating code that works with MacOS.

**Comment by Jordan-Nelson** [comment]
Is [TaskQueue](https://pub.dev/documentation/pigeon/latest/pigeon_lib/TaskQueue-class.html) supported for swift? It seems to ignore the annotation when generating swift code.

**Comment by gaaclarke** [comment]
> It doesn't seem to be addressed if you want to use objective-c on MacOS

I just found out that objc can be used for macOS plugins the other day.  They seemed to really push Swift for macOS.  I don't know if we are going to explicitly support that.  I'm keeping an eye on it.

> Is [TaskQueue](https://pub.dev/documentation/pigeon/latest/pigeon_lib/TaskQueue-class.html) supported for swift? It seems to ignore the annotation when generating swift code.

The swift code generator is still experimental, it's possible it is missing the TaskQueue feature.  Even if it did have it though, macOS doesn't support it (see https://github.com/flutter/flutter/issues/93945).

**Comment by Jordan-Nelson** [comment]
But swift could be used on iOS where it is supported, right?

**Comment by gaaclarke** [comment]
> But swift could be used on iOS where it is supported, right?

Right, it should be implemented.  You should file an issue, I don't think we have one.

**Comment by stuartmorgan** [comment]
> It doesn't seem to be addressed if you want to use objective-c on MacOS.

Flutter technically doesn't support Obj-C for macOS plugins, FYI; that's why there's no way to create an Obj-C plugin for macOS with `flutter create --template=plugin`. In practice it works because of the way Swift/Obj-C interop works, but it's not something we actively support.

**Comment by Jordan-Nelson** [comment]
> > But swift could be used on iOS where it is supported, right?
> 
> Right, it should be implemented. You should file an issue, I don't think we have one.

Done: https://github.com/flutter/flutter/issues/111512
