### ISSUE TITLE
[pigeon] Add support for Linux

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73740]
## Use case

Currently, [pigeon](https://pub.dev/packages/pigeon) only supports generating for iOS and Java and allows very easy platform calls.

However, plugins might also want to support **Linux** and use pigeon for that. cc @gaaclarke 

### Other desktop platforms

See also:

* macOS feature request: https://github.com/flutter/flutter/issues/73738
* Windows feature request: https://github.com/flutter/flutter/issues/73739

**Comment by stuartmorgan** [comment]
Currently we're in the process of refactoring the existing generators to build a common structure that will make new implementations easier to build and maintain (based on the experience of adding several more generators). One that's done it should require less ramp-up on Pigeon internals for someone to build this implementation.

**Comment by stuartmorgan** [comment]
@robert-ancell Is this something you would be interested in doing, by any chance? It would be great to have Linux support in Pigeon (it's now the only 1P embedding that Pigeon doesn't support), but since my GObject-fu is weak I'm skeptical that I would do a good job of it.

**Comment by robert-ancell** [comment]
I'm on holiday at the moment but I'll have a look when I get back.

**Comment by robert-ancell** [comment]
I've added this to our backlog, however, don't block on me if someone else is interested in this. I'll note here if I start working on it.

**Comment by mateuszboryn** [comment]
Hi, when can we expect support for Linux? I'm very interested in using it.

**Comment by domesticmouse** [comment]
> I've added this to our backlog, however, don't block on me if someone else is interested in this. I'll note here if I start working on it.

Hey @robert-ancell any chance of getting a high level sketch of what's required to get this working?

**Comment by stuartmorgan** [comment]
I can provide that. At a high level the main things that are needed are:
- The generator implementation ([example](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/cpp_generator.dart)), which is most of the work.
- Glue (flags, adaptor, etc.) in [the main Dart code](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/pigeon_lib.dart).
- The test plugin ([example](https://github.com/flutter/packages/blob/main/packages/pigeon/platform_tests/test_plugin/windows/test_plugin.cpp)) that drives the integration tests.
- [Test tool](https://github.com/flutter/packages/tree/main/packages/pigeon/tool) code, including new [suites](https://github.com/flutter/packages/blob/main/packages/pigeon/tool/shared/test_suites.dart) (should be minimal work, mostly the same as Windows) and [generation](https://github.com/flutter/packages/blob/21c2ebb39c0732b8c4ae2d68f25b96a895be915f/packages/pigeon/tool/shared/generation.dart#L84) (also not a lot of work).
- The [example app](https://github.com/flutter/packages/tree/main/packages/pigeon/example).
- The [README](https://github.com/flutter/packages/blob/main/packages/pigeon/README.md).

More tactically, the actual process of implementing this would probably look like:
- Wire up the tool-level glue with a mostly empty skeleton generator, using flags that are temporarily hidden.
- Wire up the tests, but skipping all the integrations tests on Linux.
- Incrementally implement functionality (e.g., just get Host API calls with no arguments or return values working first, then build out from there), enabling tests as functionality comes online.
- Eventually unhide the flag, add the example, and add documentation.

However, before implementing anything it would be good to have a design for what the generated APIs should look like. Some considerations:
- How much of the message channel types will carry over into Pigeon? (As with C++, some of this is unavoidable; for instance there are no data structures or generic types to translate to.)
- What are the desired representations for each argument type, for Host and Flutter APIs? There are subtleties with things like nullable Flutter APIs, where if we use the obvious things (pointer to type), passing literals becomes very cumbersome in a C-based language.
- What should data classes look like exactly? How do we handle construction of instances when there are non-nullable values?

**Comment by domesticmouse** [comment]
Yeet. No promises, but I'll have a look during the summer doldrums. From a quick review, glib looks intriguing, but it isn't the only API style that a Linux user may want to integrate with. There are plenty of C and C++ APIs out there. Is there a world in which we generalise the win32 C++ pigeon to also work on linux as a first pass?

**Comment by stuartmorgan** [comment]
> From a quick review, glib looks intriguing, but it isn't the only API style that a Linux user may want to integrate with.

It is the API style of the Flutter GTK embedding's message channels though.

> There are plenty of C and C++ APIs out there.

That's true, but it's not clear to me how many of those use cases are better served by message channels than they would be by FFI.

> Is there a world in which we generalise the win32 C++ pigeon to also work on linux as a first pass?

I assume you mean just the client API design parts and the data classes? Most of the generated code is interacting with the message channel system and would have to be written from scratch for the Linux channel APIs.

It's something we've discussed, but there are several issues with it:
- We [would not use it ourselves](https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style) which means we would have no real-world experience as clients of such an implementation. Actually using Pigeon ourselves has been how almost all of its evolution has happened.
- Since it would not handle our use cases, we would still need an implementation we would use, so we would be maintaining two implementations for Linux forever. Every new implementation we take on adds significant work to maintaining the plugin, and doing so for our least-requested platform is unlikely to be worth the cost.
- Such an implementation would be inherently less efficient, because it would have to do yet another copy of most data (e.g., all strings). That's probably not a big deal in most cases, but it's not ideal to hide inefficiencies in a code generator that we would be recommending. (E.g., we would need to have a bunch of documentation comparing the two different generators people could choose and explaining the drawbacks of the C++ version.)

If there's a strong demand for a C++-based method channel system on Linux, it would almost certainly better to do that at the level of the engine—where we could re-use more code, and avoid the extra copies—not Pigeon.

**Comment by robert-ancell** [comment]
I did a small start of this in https://github.com/robert-ancell/packages/tree/pigeon-linux, the next step I was looking at is hand-writing some output code, so we could review that is what we want and then write a generator that would make that. @stuartmorgan did you have any thoughts on what the output should look like or is that too much GObject-fu for you?

**Comment by stuartmorgan** [comment]
I'm happy to review a doc of sample hand-written output, especially from a standpoint of what things have been tricky in other languages. For questions about the right way to do things (e.g., express errors in sync and async methods, or do nullable parameters to Flutter API methods) I would mostly defer to you since I still don't know GObject conventions well at all.

**Comment by robert-ancell** [comment]
@stuartmorgan I've made the Linux example with manually "generated" code in https://github.com/flutter/packages/pull/5100/files - please review.
