### ISSUE TITLE
Implement CupertinoActionSheet

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7376]
https://developer.apple.com/ios/human-interface-guidelines/ui-views/action-sheets/

**Comment by gspencergoog** [comment]
Note that [`UIActionSheet`](https://developer.apple.com/documentation/uikit/uiactionsheet) has been deprecated since iOS8 (but the replacement [`UIAlertController`](https://developer.apple.com/documentation/uikit/uialertcontroller) can still accept the style [`UIAlertController.Style.actionSheet`](https://developer.apple.com/documentation/uikit/uialertcontroller/style/actionsheet)). I don't think that changes anything for us: we still want an action sheet, but it might affect how we decide to name/implement it to make it familiar/findable for iOS developers.

**Comment by xster** [comment]
@nataliesampsell: I took another look at bottom_sheet.dart. 

It seems like each layer had some Material related logic that are small enough it may not be worth extracting. We can take a similar approach but we can recreate them in Cupertino. 

We can create a showCupertinoBottomSheet type function that also pushes a PopupRoute type that follows iOS animation speeds. 

We don't have to handle the dragging functions in BottomSheet since iOS action sheets are not draggable. 

Let's take the transparency logic from the Cupertino dialog classes @matthew-carroll just made.

**Comment by nataliesampsell** [comment]
@xster: Okay, so to confirm, we would no longer be doing any extracting, and would instead be creating a Cupertino class modeled after the Material version, looking to the Cupertino dialog classes to find the transparency aspect?

**Comment by xster** [comment]
Indeed, let's model the Cupertino version after the Material one (with PopupRoute, animations etc) but the Material code doesn't have enough non Material code to extract. 

Also, let's make the pop-up mechanism non-specific to action sheets since pickers should pop up the same way. Only the content of the pop-up should be action sheets specific.

**Comment by nataliesampsell** [comment]
@xster Could we do something similar to what the Cupertino dialog classes do for the actions - have a class like the CupertinoDialogAction class to represent each action in the action sheet? Also, should we allow scrolling (developer guide advises against enabling scrolling, but I believe it is possible)?

Finally, would the pop-up mechanism go in the Cupertino route.dart class, or in another class, so it could be used by multiple Cupertino widgets?

**Comment by xster** [comment]
Let's put the pop-up mechanism in the cupertino route.dart file. For the sub actions, please do a quick research. I very strongly suspect it's not possible to add anything besides buttons into the action sheet but please make sure. I'd model scrolling after native behavior.

**Comment by nataliesampsell** [comment]
What I've found is that action sheets are very similar to dialogs in that they can have an optional title and message at the top, and the non-optional arguments are a set of two or more actions that are styled differently depending on whether they are the default action (bolded text), a destructive action (red text), or a cancel button (is grouped separately from the other buttons). The actions are all buttons, but because they are styled and grouped differently depending on what kind of action they are, I was thinking of making a class similar to CupertinoDialogAction so that the user could specify the type of action so that the buttons could be styled correctly. Were you thinking it would be a better idea to instead have the ActionSheet take a List<CupertinoButton>? Users could style the buttons themselves then, but I'm not sure how having a separately-grouped Cancel button would work.

**Comment by xster** [comment]
Thanks for looking into it. If natively there are no options of styling the contents differently than the preset button styles, let's do something similar to the CupertinoDialogAction.

**Comment by xster** [comment]
@nataliesampsell, assigning this to you

**Comment by long1eu** [comment]
any news on this?

**Comment by xster** [comment]
Implementation is at #19232. Leaving this bug open after for @matthew-carroll to combine with code in #18381

**Comment by xster** [comment]
The action sheet is in the gallery and the widgets catalog website now. Leaving #20470 as clean up task.
