### ISSUE TITLE
Firebase TestLab tests are failing when run from the pipeline

### ISSUE THREAD

**Issue by ALaaDawood** [flutter/flutter#73797]
I'm trying to automate testing with firebase Test Lab with every commit to a certain branch
we are using google cloud build for CI/CD.. and my cloudbuild.yaml file has the following commands :

```
  - name: 'gcr.io/$PROJECT_ID/flutter'
    id: 'build'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        flutter channel beta
        flutter build apk
        cd android
        ./gradlew app:assembleAndroidTest
        ./gradlew app:assembleDebug -Ptarget=./integration_test/app_test.dart
  - name: gcr.io/cloud-builders/gcloud
    id: "firebase testlab"
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        <activating google-service-account and setting the firebase project>
        gcloud firebase test android run --type instrumentation \
        --app build/app/outputs/apk/debug/app-debug.apk \
        --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
        --timeout 2m
```
When I run these exact same commands from my local machine, it uploads to testlab successfully and my tests pass.
But when running from he pipeline it fails with the following logs :

![image](https://user-images.githubusercontent.com/25867891/104355022-baff5500-5512-11eb-97bd-13274d8eda51.png)

**Comment by darshankawar** [comment]
@ALaaDawood 
if the issue does not occur locally running from your machine, but only with your CI/CD,
I recommend you to ask support directly to the service provider. Since the test details from your log shows failed reason as `test failed to run`. It doesn't seem to be related to infrastructure.

If you disagree, please write in the comments and I will reopen it.
Thank you
