### ISSUE TITLE
Implement ActionBarDrawerToggle

### ISSUE THREAD

**Issue by AlexeySemigradsky** [flutter/flutter#7389]
https://developer.android.com/reference/android/support/v7/app/ActionBarDrawerToggle.html

Example of icon animation:
![](http://i.giphy.com/oGOeuB9RvPBgk.gif)

**Comment by eseidelGoogle** [comment]
Is this a request specifically for the icon animation of the drawer icon turning into the arrow?  Or are you asking for something else?

**Comment by aleki** [comment]
> Is this a request specifically for the icon animation of the drawer icon turning into the arrow? Or are you asking for something else?

Yes, it is.

**Comment by eseidelGoogle** [comment]
I'm confused by that image, since Material Design seems to suggest drawers go over the top of the AppBar.
https://material.io/guidelines/layout/structure.html#structure-system-bars

However there are other places this animation could be used, e.g.
https://material.io/guidelines/motion/material-motion.html#material-motion-what-makes-a-good-transition

**Comment by aleki** [comment]
> I'm confused by that image, since Material Design seems to suggest drawers go over the top of the AppBar.

Yes, it wrong.

> However there are other places this animation could be used, e.g.

Thank you, it is good example.

**Comment by Hixie** [comment]
We have fixed this now! https://docs.flutter.io/flutter/material/AnimatedIcons/close_menu-constant.html
