### ISSUE TITLE
It's possible for us to output the "out of date flutter" banner on a --machine call

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#73977]
I just ran into this:
```
ianh@burmese:~/dev/assets-for-api-docs$ bin/generate.sh 
Dart path: lib/main.dart
Temp directory: /tmp/diagrams
Unhandled exception:
FormatException: Unexpected character (at character 3)
  ╔════════════════════════════════════════════════════════════════════════...
  ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:505:36)
#5      JsonCodec.decode (dart:convert/json.dart:156:41)
#6      jsonDecode (dart:convert/json.dart:96:10)
#7      DiagramGenerator._findIdForDeviceName (file:///home/ianh/dev/assets-for-api-docs/bin/generate.dart:161:35)
<asynchronous suspension>
#8      DiagramGenerator.generateDiagrams (file:///home/ianh/dev/assets-for-api-docs/bin/generate.dart:108:10)
<asynchronous suspension>
#9      main (file:///home/ianh/dev/assets-for-api-docs/bin/generate.dart:402:5)
<asynchronous suspension>
```

What's going on there is that we run `flutter devices --machine` but the output isn't valid JSON because we happened to output the "your flutter is out of date" banner above the JSON.

**Comment by jmagman** [comment]
This check is guarded by a check for the machine flag.
https://github.com/flutter/flutter/blob/fc25d8b0cc23b55dd5800ca973b68b86dcb2da97/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L250-L251

`topLevelResults['machine']` is false for `flutter devices --machine`, but true when I ran `flutter doctor --machine` (`ArgResults` `_parser.options` Map contains `machine` but it's not in `_parsed`).  Maybe because that command re-adds `machine` even though it's already been added in the command runner #50581?
https://github.com/flutter/flutter/blob/30c0fc1bce85024f0e75409b9d8b2af560aac2d8/packages/flutter_tools/lib/src/commands/devices.dart#L15
https://github.com/flutter/flutter/blob/fc25d8b0cc23b55dd5800ca973b68b86dcb2da97/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L72-L75

**Comment by jonahwilliams** [comment]
Fixed in https://github.com/flutter/flutter/pull/150138
