### ISSUE TITLE
Scrolling perf regression in Complex Layout benchmark

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7407]
The complex layout benchmark seems to show a performance regression in the [Tabs API](https://github.com/flutter/flutter/commit/b23aed7a86093e5378597cdf010bed0006785918) change. It is mostly visible in worst frame build times and missed rasterizer (GPU) frame counts.

## Steps to Reproduce

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/complex_layout_scroll_perf__timeline_summary.dart
```

## Logs

![complex-layout-tab-api-regression](https://cloud.githubusercontent.com/assets/211513/21790612/63f258f0-d692-11e6-9685-28a633bf0ab3.png)

**Comment by Hixie** [comment]
@HansMuller Looking at this, my first step towards debugging it would be to run the benchmarks under the profiler immediately before the suspect patch and immediately after the suspect patch to see what the difference is.

**Comment by HansMuller** [comment]
I was able to confirm the problem and that it was introduced by #7387. Since then the benchmark's performance has returned to normal. 

It would be useful to sort out what caused the regression however at the moment https://github.com/flutter/flutter/issues/7763 makes it difficult to profile the benchmark.

**Comment by Hixie** [comment]
@HansMuller #7763 is obsolete now, so this should be testable again.

**Comment by yjbanov** [comment]
This has improved greatly since the issue was filed. Closing.
