### ISSUE TITLE
Feature Request: Flutter build auto copy VCRedist dll to build target directory.

### ISSUE THREAD

**Issue by netroby** [flutter/flutter#74095]
As the document said, we should copy VC Redist dll files into the same directory of the build target directory.
May this step can be auto done by the flutter build tools?

![image](https://user-images.githubusercontent.com/66301650/104792846-de5c2580-57da-11eb-89be-6f74a2636c81.png)

If user do not have the Visual Studio Community, it will failedt build.

If user already installed Visual Studio Community, find the path will be possible.

![image](https://user-images.githubusercontent.com/66301650/104792899-08154c80-57db-11eb-9266-eddac12dcc2a.png)

Any help ?
If this step can be done by the build tools, we can easier build and ship our app to other user.

https://flutter.dev/desktop

For example, we can put the exported DLL file into github repository, and then download it from github, then finish the build progress?

https://github.com/netroby/vcredist-for-flutter

**Comment by stuartmorgan** [comment]
We have decided not to do this, as explained here: https://github.com/flutter/flutter/issues/53167#issuecomment-635641418

If you are choosing not to use an installer, you can certainly add a step to your local build that copies them automatically.

> If user do not have the Visual Studio Community, it will failedt build.

If a developer doesn't have Visual Studio they can't do a build in the first place, because they don't have the build tools; build requirements and runtime requirements are completely separate questions.

> For example, we can put the exported DLL file into github repository, and then download it from github, then finish the build progress?

I don't understand what problem you are trying to solve by adding complexity in fetching remote codes instead of using the local ones. But if for some reason you want to structure your own build this way, I guess you can.
