### ISSUE TITLE
Problem with Flutter app created on MacOS and run on windows

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#74222]
Hello,
I have found a problem that occurs with flutter projects if they are created on MacOS and then opened on Windows. The opposite doesn't happen.

If I create a project on MacOS, it runs fine and there are no problems and I can build and run it. However, whenever I run it on Windows a lot of errors show up. My prompts me to get dependencies whenever I open the project, and it runs pub get. The problem is it fails and gives the following error:
`Because ninja_id depends on integration_test any from sdk which doesn't exist (could not find package integration_test in the Flutter SDK), version solving failed.`.
Running flutter pub get or dart pub get gives the same error and the IDE is unable to import the flutter package, giving errors throughout the entire project.

This means that any projects created on MacOS cannot be run on windows. There is also a difference between the files created by flutter when creating an app on MacOS and Windows. Some folders are created on MacOS such as integration_test and are not created on Windows. I solved this problem once by deleting a bunch of stuff though I do not remember what it was and it was not practical.

The opposite doesn't happen; creating a project on Windows makes it run just fine on MacOS.

Please let me know if you need clarification on anything or need any extra information or resources such as screenshots or screen recordings.

Thank you very much!

**Comment by TahaTesser** [comment]
Hi @HadyMash 
You probably have different channels installed on your mac and windows machine. 

> Because ninja_id depends on integration_test any from SDK which doesn't exist (could not find package integration_test in the Flutter SDK), version solving failed.

You're getting this error because you're running a project which has `integration_test` in` pubspec.yaml` that points to SDK 
```yaml
  integration_test:
    sdk: flutter
```
This is currently only supported from `beta` to `master`, your windows machine probably running `stable` channel. Please upgrade to `beta` and try again 

Likewise, you can create a stable project on windows and run it on macOS without any issues, which Is because the `stable` channel project doesn't have `integration_test` as a dependency and it's optional

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by HadyMash** [comment]
Hello, this issue has happened again. The windows device is on the beta channel and I am getting an error in intergration_test that 'run' is not defined. Please help.

Should I open a new issue for this or is commenting here fine?
