### ISSUE TITLE
Mainland China: Stuck in "Running pub upgrade"

### ISSUE THREAD

**Issue by liu-yunfei** [flutter/flutter#74314]
## Steps to Reproduce

1. I am trying to install flutter on my Windows PC. According to the documents on flutter.cn, I set my environment variables with these command
```shell
 set PUB_HOSTED_URL=https://pub.flutter-io.cn
 set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
2. I used git clone to get the SDK
```shell
git clone -b dev https://github.com/flutter/flutter.git
```
3. After that, I added the /bin directory into PATH
4. Then, it shows
```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Building flutter tool...
Running pub upgrade...
```
And stuck here for hours. I had tried to use a proxy, but it didn't work, still stuck here.

P.S. I used the proxy with the following commands
```shell
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
```
Then test with `curl google.com` and it works well.
###System Information
Windows version
```
Windows 10 Enterprise LTSC
```
Powershell version
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Logs

<details>
<summary>Logs</summary>

when running `flutter --verbose`, I got the same output
```
Building flutter tool...
Running pub upgrade...
```

when running `flutter doctor -v`, also the same output
```
Building flutter tool...
Running pub upgrade...
```

</details>

**Comment by SeasonLeee** [comment]
My suggestion is, if you can curl google and it works well, then don't follow the tutorial on flutter.cn and ditch everything you have done so far, just go to follow what's on the flutter.dev.

Yeah, that's how I do when I setup my environment. What flutter.cn teach is for those who can't access the internet outside of the Great Fire Wall.. since you can, why do you.... yeah...

**Comment by liu-yunfei** [comment]
> My suggestion is, if you can curl google and it works well, then don't follow the tutorial on flutter.cn and ditch everything you have done so far, just go to follow what's on the flutter.dev.
> 
> Yeah, that's how I do when I setup my environment. What flutter.cn teach is for those who can't access the internet outside of the Great Fire Wall.. since you can, why do you.... yeah...
> 
> Also, if you ditch the tutorial on flutter.cn, make sure all your dart request is routed to the network outside of the GFW.
> 
> Carry on, my friend, Flutter is awesome once you know it😆
Hello SeasonLeee, thank you for your suggestion and your kindness.

I reinstalled flutter and follow the steps in flutter.dev, but it seems didn't work.

Thank you again.

**Comment by SeasonLeee** [comment]
have you tried `flutter clean`? Some of my friends also stuck at problems like this and all they have done is just `flutter clean`

**Comment by liu-yunfei** [comment]
> have you tried `flutter clean`? Some of my friends also stuck at problems like this and all they have done is just `flutter clean`

For `flutter clean` the same problem...
```
Building flutter tool...
Running pub upgrade...
```

**Comment by SeasonLeee** [comment]
hmm... that's odd... 

I want to repeat things again, that, if you can curl google.com and you have result like this:
![image](https://user-images.githubusercontent.com/13610283/105345653-79ac2b00-5c1f-11eb-885f-59caccd3e228.png)

meaning you can access resource outside the GFW, 

also meaning you don't need to follow what's on the flutter.cn.

also meaning you have revert what you have done before when you followed the tutorial on flutter.cn like change the pub origin, like what you have said above:

> ## Steps to Reproduce
> 1. I am trying to install flutter on my Windows PC. According to the documents on flutter.cn, I set my environment variables with these command
> 
> ```shell
>  set PUB_HOSTED_URL=https://pub.flutter-io.cn
>  set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
> ```
> 

also meaning you need to make sure your `PUB_HOSTED_URL` value is set to default which should be `https://pub.dev` because you can access the resource outside the GFW so you can directly download dependencies from original website pub.dev.

After you have check those and set things right, then you can go ahead to use `flutter clean` then `flutter WHATEVER_YOU_WANT_TO_DO_NEXT`

And I am not sure how do you access the resource outside the GFW, but please make sure all the connection in your computer route through that thing that help you access the world outside.

I know there's a tool on window which can intercept all the network request in the computer, and you can check the information of each connection to see if they are route through your tool or just bypass the tool.

Setting up environment in China takes a great deal of hard and mundane work, but I believe those experience will help you grow... just don't give up!

**Comment by liu-yunfei** [comment]
Hello SeasonLeee

Thank you for your patience and warm heart, I can't express how grateful I am.

Actually, I still cannot install it on Windows, even I use the original guide, not the one on flutter.cn. However, I successfully install it on **Ubuntu 20.04** with snap, and it works well. Now I am starting to make Flutter apps.

Thanks again for your help and encouragement, and have a good day!

**Comment by SeasonLeee** [comment]
Good to hear from you! And good luck with your flutter journey!

Ps, coding on windows and in China IS really a pain in the ass hahahahaha
