### ISSUE TITLE
Is there a way to play WEBM video with transparent background in flutter

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#74476]
Hello Flutters,

To complete my app design, I need to play a WEBM video with transparent background on other widget, after a few time searching on google I hasn't find any thing about this function.

Do any one know, if there is a pub, or any solution to do this?

thanks

**Comment by darshankawar** [comment]
@Kassan424kh 
Your question is better suited for StackOverflow since it doesn't describe a bug or feature request in the Framework. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
