### ISSUE TITLE
Mozilla is not showing network svg images properly(Flutter web)

### ISSUE THREAD

**Issue by franarolas** [flutter/flutter#74491]
Mozilla is not reacting to "fit: BoxFit.contain" property properly, it works fine in Chrome and Edge but not in Mozilla.
I've a cdn with SVGs images and I use Image.network() to show them, Mozilla has an strange behaviour with the property BoxFit.contain, as shown in the following image:

Mozilla:
![imagen](https://user-images.githubusercontent.com/42511706/105493332-8d0bd480-5cb9-11eb-9dbd-bcccc609b51d.png)

Chrome/Edge:
![imagen](https://user-images.githubusercontent.com/42511706/105493419-ac0a6680-5cb9-11eb-8cee-fc6dbc6cf53a.png)

## Steps to Reproduce

I've uploaded a Github project so you can easy reproduce the issue, just deploy it and test it with Mozilla browser.
[Github project](https://github.com/franarolas/mozilla_svg_image_error)

**Expected results:**
It should be shown as it is in Chrome/Edge browsers

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.746], locale es-ES)
    • Flutter version 1.25.0-8.3.pre at C:\flutter
    • Framework revision 5d36f2e7f5 (8 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\F-Laptop\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Issue replicable on latest beta.

<img width="424" alt="Screenshot 2021-01-22 at 7 15 57 PM" src="https://user-images.githubusercontent.com/67046386/105499035-e9d1b400-5ce6-11eb-8991-01868afc6c08.png">
<img width="586" alt="Screenshot 2021-01-22 at 7 16 19 PM" src="https://user-images.githubusercontent.com/67046386/105499045-ec340e00-5ce6-11eb-979a-11ad545449b5.png">

Can't verify this on latest master, due to this issue. https://github.com/flutter/flutter/issues/74489.

<details>
<summary>latest beta flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.3.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 5d36f2e7f5 (8 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        •
      android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                 • chrome                               •
      web-javascript • Google Chrome 87.0.4280.141

• No issues found!


```

</details>

**Comment by darshankawar** [comment]
May be related to https://github.com/flutter/flutter/issues/66412

**Comment by yjbanov** [comment]
We currently do not support SVG natively in the engine. This happens to work today in the HTML renderer because we use the `<img>` tag, which supports more formats than Flutter normally does. However, it does not implement all features if `Image.network`.

Alternatives are:

- Use a platform view and create an `<svg>` tag in it ourself. This solution should be fine if you have few SVG images displayed simultaneously.
- Use `package:flutter_svg`. This only supports a subset of SVG but is efficient when you have lots of SVG images on the screen.

This topic is more generally discussed in https://github.com/flutter/flutter/issues/1831, so I'm deduplicating this issue with that one.
