### ISSUE TITLE
Autocomplete options customizability

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#74509]
The [Autocomplete](https://github.com/flutter/flutter/pull/73753) and [RawAutocomplete](https://github.com/flutter/flutter/pull/62927) widgets ([design doc](https://docs.google.com/document/d/1fV4FDNdcza1ITU7hlgweCDUZdWyCqd-rjz_J7K2KkfY/edit#)) allow custom options via optionsViewBuilder, but the options are always placed in an Overlay at the location of RawAutocomplete with full-screen constraints.  There are many common use cases that are not possible with this arrangement:

  * Users may want the options in-line in the widget tree and not in an Overlay.
  * Users may want the options to be the same width as the field.
  * Users may want the options to be the same width as is available to the RawAutocomplete widget.
  * Users may want to the options to be positioned somewhere else in the Overlay.

I think we can allow all of these use cases by adding the `overlayEntryViewBuilder` parameter of the following type:

```dart
Widget Function(
  BuildContext context,
  LayerLink fieldLayerLink,
  BoxConstraints contraints,
  Size fieldSize,
  Widget child,
)
```

This parameter would default to the current behavior, which builds a CompositedTransformFollower at the location of the field with full screen width.

If null is explicitly passed to this parameter, then the options will be built in-line instead of in an Overlay.

If the user passes this parameter, they can use the given arguments to handle all of the remaining use cases above.  `fieldSize` can be used to set the options' width to the width of the field.  `constraints` is the constraints of the Autocomplete widget, so that can be used to create options that align with that point in the widget tree.

**Comment by sgehrman** [comment]
the options width is critical.  Looks weird now being wider than the text field.

**Comment by sylianeu** [comment]
As is, the overlay will be hidden if the Autocomplete box is at the bottom of the screen (in a ListView, for example). It would be better if it followed the same rules as Tooltip, where it places the overlay above the widget if there is no room underneath.

**Comment by TimWhiting** [comment]
The options width is really bad on desktop with a small field. I think we need to add optionsMaxWidth to complement the optionsMaxHeight parameter, or provide a boolean to match the size of the text field. (Personally I think that it should match the text field size by default, and people can customize it to not match the text field width if they want).

**Comment by bdemeure** [comment]
No news about justinmc proposal about an overlayEntryViewBuilder ?

**Comment by justinmc** [comment]
There is another PR trying to solve the width problem: https://github.com/flutter/flutter/pull/110032

As I mentioned over there, I don't know how viable the overlayEntryViewBuilder parameter is as proposed in this issue.  It's not possible to get the Size and Constraints in the same frame.

**Comment by gnprice** [comment]
> As is, the overlay will be hidden if the Autocomplete box is at the bottom of the screen (in a ListView, for example). It would be better if it followed the same rules as Tooltip, where it places the overlay above the widget if there is no room underneath.

This specific feature request was later filed as #101620 and can be followed there.

And for cases where you know in advance whether the autocomplete options should go above or below (so perhaps not a ListView, but when you have an input field placed at the bottom of a UI's layout), there's now a way to do that. See #129748 or https://github.com/flutter/flutter/issues/101620#issuecomment-1626095240 .

---

> The options width is really bad on desktop with a small field. I think we need to add optionsMaxWidth to complement the optionsMaxHeight parameter, or provide a boolean to match the size of the text field. (Personally I think that it should match the text field size by default, and people can customize it to not match the text field width if they want).

There's an issue #78746 specifically about the width of the options, though with a different focus. If neither that nor another existing issue covers what you're looking for, I'd encourage you (@TimWhiting, or anyone else interested in this) to file a new issue for that request. Do also mention this issue there, so that GitHub shows a link to that new issue in this one's thread.

---

More generally, for any concrete axis on which to customize the autocomplete options or change their behavior, if it seems like something that many apps might reasonably want then I'd encourage filing an issue for that specific feature request, for two reasons:
* For this general customizability feature, there's a question of what the API should look like, and that API design can be informed by seeing the ways that people want to customize the widget.
* Even if we eventually build this general customizability feature, I think it will continue to be useful to have simple options in the API for making simple common customization choices. So we can go ahead and build specific features without necessarily getting in the way of this general feature or duplicating work.

**Comment by justinmc** [comment]
Given @gnprice's response I think we should actually close this issue and focus the attention on the specific issues people need.  I'm also no longer sure that overlayEntryViewBuilder makes sense given the recent addition of OverlayPortal, which we may want to take into consideration.
