### ISSUE TITLE
Successful LUCI builds not updated in build dashboard

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#74536]
The build dashboard is currently red the tip of tree https://github.com/flutter/flutter/commit/9817cabf8810a7e15d455502cd17aaca8fa4667a has many grey (queued) boxes, and on the previous commit those tasks were purple. However, when clicking through to the milo dashboard, the builds actually finished successfully over an hour ago. Some examples:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_aar_module_test/1393/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_host_with_custom_build_test/1385/overview
* https://ci.chromium.org/p/flutter/builders/prod/Linux%20plugin_test

![Screen Shot 2021-01-22 at 3 22 08 PM](https://user-images.githubusercontent.com/7856010/105559302-9f8c0b00-5cc5-11eb-9e12-6e4381d49cd5.png)

**Comment by godofredoc** [comment]
Moving as P1 as the symptoms were fixed but will keep this bug open to revisit the code we are using to cache builds and process new build state.

**Comment by godofredoc** [comment]
This has been an issue for a long period of time a few months from the data we have checked. The root cause is we are putting a lot of pressure on the buildbucket grpc endpoints and they are failing very frequently.

The result of this problem is results are not updated frequently enough in the flutter dashboard causing the tree to be closed for hours even though the builds have already been retried and they passed.
