### ISSUE TITLE
Add ScrollBar display option.

### ISSUE THREAD

**Issue by YeungKC** [flutter/flutter#74637]
Currently scrollbar only allows to set isAlwaysShown, but sometimes we need the logic to show if scrollview is scrollable, for example #73654. currently we can only set scrollable by calculating the total height.

design code:

```dart
Scrollbar(
  showScrollbar: scrollable, // default , always
)
```

@HansMuller

**Comment by MrBirb** [comment]
Related (if not duplicate) [#40107](https://github.com/flutter/flutter/issues/40107)

**Comment by Piinks** [comment]
Hey @YeungKC does the scrollbar show up currently if the scrollview is not scrollable? It should not show up by default if there is not enough content to scroll.

**Comment by MrBirb** [comment]
@Piinks This is what this issue is about: show scrollbar if the scroll view is scrollable :D . We were discussing if this issue is a duplicate of your last issue on scrollbars

**Comment by Piinks** [comment]
> @Piinks This is what this issue is about: show scrollbar if the scroll view is scrollable :D . We were discussing if this issue is a duplicate of your last issue on scrollbars

Thanks @MrBirb! I think `Scrollbar.isAlwaysShown` shows the scrollbar if it is scrollable, and won't show the scrollbar if it is not scrollable. If that's not the case we should fix that.

If there is behavior the Scrollbar is missing, a code sample that shows off what is missing is super helpful.

I don't think this is a dupe of #40107 if I understand correctly. That issue is hoping to add Scrollbars automagically on desktop and web for scrollables, so you don't have to add a `Scrollbar` yourself.

**Comment by YeungKC** [comment]
I found out that I was wrong about something, currently @Piinks is right, if it is not scrollable then setting isAlwaysShown will not show it either.
