### ISSUE TITLE
Move pipeline state object creation outside the frame workload.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#74630]
Today, when the engine needs a unique shader variant to render parts of scene, it is already in the middle of a frame workload. Determining the shader needed, constructing the shader, translating it through the various intermediate formats and finally compiling it before constructing pipeline state objects from it can take multiple frame intervals worth of time. Due to the flexible nature of the Flutter rendering APIs, knowing the entire set of shader variants upfront is not possible. Instead, API affordances must be available for callers to create these shaders outside the frame workload so that their use can be made in frames without jank. This is an umbrella issue tracking the design work necessary for such APIs.

**Comment by Hixie** [comment]
cc @goderbauer

If we had a dart:ui API in SceneBuilder where we could give two alternative child layers, the "main" one and the "fallback" one, with some callback to notify when the "main" one has had enough preparation work done that it can be rendered, we could make a widget that enabled developers to delay starting transitions and so forth until they knew the transition could start without janking.

This doesn't help with cases where mid-way through an animation we suddenly discover we need a new shader. I'm not sure how to handle that case, since even at the framework level we don't know what's coming in the future (e.g. worst case it could be driven by server-side decisions).

**Comment by Hixie** [comment]
We've continued to study this. Some concerns that we're facing so far:
* This wouldn't work for animation sequences that involve creating shaders in secondary frames, e.g. https://github.com/flutter/flutter/issues/76180. We've considered looping such animations quickly to generate all the subframes and check them all for shaders that need compiling, but that's prohibitively expensive without some sort of caching, and there's no meaningful solution we can see to cache invalidation in a Flutter context since each run of the animation could be arbitrarily different (e.g. based on application state). Even that wouldn't work for user-driven animations (e.g. opening the drawer) since there'd be no way to predict the entire animation sequence.
* This approach puts the burden on the developer more than we'd like.
* Some animations would end up with a really long delay since some shader compilations are proving to be absurdly long. For example, an animation like https://github.com/flutter/flutter/issues/76517 would likely have a four second (!) delay before the animation started the first time. That's arguably better than jank, but not by much.
* It's likely some animations only create one shader, but that that shader is itself not done in the first frame (because e.g. the first frame has opacity set to zero so nothing actually paints, like a router transition). Making those cases work might be tricky.

We haven't yet abandoned this idea but it's not looking promising.

See https://github.com/flutter/flutter/projects/188 for other ideas we are investigating.

**Comment by Hixie** [comment]
To clarify I meant it's not looking promising as a silver bullet for all early-animation jank problems. As mentioned in my last message we haven't abandoned this; it's still something that could help in situations where all the shaders are needed in one go, for example it could enable showing a loading spinner while the shaders for a static SVG image are being compiled (as opposed to today where loading an SVG that needs shaders compiled would cause the rendering to freeze).

**Comment by Hixie** [comment]
I just thought of another case where this would have difficulty. Suppose that we have a static SVG that requires shaders to compile, but the shaders depend on the orientation the SVG is being rendered at. If we wrap the SVG widget with one based on this issue's idea, we could spin a progress indicator while we compiled the shader, then when it's ready, render the SVG. But what if the whole scene is itself being rendered inside a slowly rotating transform? Now, every time we think we've compiled the shader, it turns out we need a new shader because the SVG is at a different orientation...

**Comment by ldasilva-net** [comment]
> I just thought of another case where this would have difficulty. Suppose that we have a static SVG that requires shaders to compile, but the shaders depend on the orientation the SVG is being rendered at. If we wrap the SVG widget with one based on this issue's idea, we could spin a progress indicator while we compiled the shader, then when it's ready, render the SVG. But what if the whole scene is itself being rendered inside a slowly rotating transform? Now, every time we think we've compiled the shader, it turns out we need a new shader because the SVG is at a different orientation...

It seems like the new warmup widget needs to "preload" full scenes. I can't saw another way to resolve this kind of animations.

BTW just yesterday, I found that a simple InFromDown transition Animation works well with common widgets but shows jank if the content has static SVGs.

**Comment by dolpheen** [comment]
@chinmaygarde
Just some thoughts, after investigation https://github.com/flutter/engine/pull/23914#issue-560981583

Although MTL archives are loaded, it looks like they are not actually used in pipeline creation.
Mentioned 'add' functions are used only for archive initialization https://github.com/google/skia/blob/f326e4faef66d529904a7b53eb931fd576c82887/src/gpu/mtl/GrMtlPipelineStateBuilder.mm#L503
But the compilation process stays the same in the GrMtlPipelineStateBuilder::finalize not taking in account previously loaded archive and binaryArchiveMiss logic as mentioned in WWDC 2020
