### ISSUE TITLE
Allow looser constraints on packages in `dev/`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#74667]
Flutter handles pub packages but requiring that every pubspec in the repo use the same version of all transitive deps in the repo.

This has the unfortunate side effect of making some dependencies _only_ used in `dev/**/pubspec.yaml` cause problems for upgrading packages int he rest of the repo.

For example, until recently we had a reference to `googleapis_auth` in there for CI authentication purposes. This introduces a dependency on `http`, which was not ready for NNBD migration (and still is not as of this writing), which blocked rolling other packages in user-facing parts of the repo. I'm also facing similar problems with `package:image`, used in dev but not elsewhere.

It might help to allow looser constraints for `dev`, or to treat it separately from the rest of the repo when building the master pubspec to resolve all packages.

/cc @jonahwilliams @Hixie for thoughts on this

**Comment by Hixie** [comment]
Loose constraints means that when any of those dependencies roll, we have a chance of going red. This increases our flakiness. (Or rather, it increases the number of uncontrolled tree closures.) The frequency of those problems is what led us to our current situation -- we would literally get about a breakage a week, and they are annoying breakages to deal with since they occur out of nowhere and affect a random commit so figuring out the cause is non-trivial.

A better solution IMHO is to reduce the number of dependencies. We have a benchmark that represents number of dependencies; we should be stricter about not regressing it. Maybe we could make it a test rather than a benchmark, literally have a number of dependencies we allow and don't allow it to increase by policy. (The problem is, everyone always has a good reason why their dependency should be an exception.)

**Comment by dnfield** [comment]
I think it should be easier to add dependencies to dev if they're useful.

It would work if we just treated dev and everything else separately - so one shrink-wrapped version for dev and another one for others.

**Comment by Hixie** [comment]
To be honest I'm pretty negative on taking on dependencies in general. The more dependencies we have, the more sources of problems we have. Certainly I think we should take great care to only adopt dependencies we are confident are high-quality and whose benefit far outweighs the costs.

That said, wouldn't having two buckets just mean that we'd risk depending on multiple versions of packages? Like, instead of just having to deal with foobar 1.2.3, now we'd have to deal with foobar 1.2.3 and foobar 1.2.4, with all the confusion that that entails? It's not like the dev bucket is entirely hermetic and sealed off from the rest of the repo, I mean, for one, a lot of stuff in dev/ depends on flutter, flutter_test, flutter_driver, and (in a way) flutter_tools.

**Comment by jonahwilliams** [comment]
For dependencies in dev that are meant to be used as applications, we could potentially leverage a pubspec.lock file to keep them in sync on CI. This will not work if other packages depend on it though, the lock isn't transitive.

I wonder if there is a way for us to structure our dev dependency integration tests to be more like the customer testing shard? Then we could run pinned tests in a way that is less exposed to the internal details of the framework repo. I'm not quite sure if that is a good idea though.

**Comment by Hixie** [comment]
If you want to add tests in flutter_tests (separate from the customer_testing stuff), that's fine by me. I'm not sure how much that really helps though, because now creating and fixing those tests will be a huge pain.

I'm not really sure I understand the motivation for this issue. Is it basically that we are having trouble upgrading packages because package:image (say) or one of its dependencies has some bug or breaking change or some such, and it happens that the dependency is coming from dev/ so if we were to cut dev/ off we'd be reducing the number of places we have to fix? Maybe specifics would help here. I wonder though if any description of the problem won't just reinforce my bias against having dependencies, more than convince me that we need more flexibility.

**Comment by dnfield** [comment]
The pain point I'd like to address is when a package that is only depended on in `dev/` has some incompatible transitive dependency with another package depended on in `pakcages/`.

We had two instances of this recently:

1. `googleapis_auth` introduces a dependency on `http`, which introduces several other dependencies. Some package in that tree was not compatible with a constraint being introduced by an unrelated package used in `flutter_tools` or `flutter_driver`. This was resolved by deleting all code that referred to `package:gooleapis_auth` from dev, which was tolerable.
2. `image` used in `dev/` had an incompatible `package:crytpo` dependency with other packages used in e.g. `flutter_tools` and `flutter_driver`. This was resolved by working with the author of package:image to publish a new version of the package, which, luckily was not very painful but further delayed and complicated a process that's been going on for several days now.

IMHO we should not block rolling dependencies for our user-facing packages because of conflicts between version solving for a dev-only package. Getting rid of those extra packages is one possibility, but several of the packages used in there are really just there for testing purposes.

We'd still have to rev them if a rev to our user-facing packages required it, but we could potentially avoid the confusion.

That said, looking at the usage of package:image, I'm not sure we really truly even need it :\

**Comment by Hixie** [comment]
Was the package:crypto problem because package:image had not migrated to a newer crypto, and the newer crypto wasn't backwards compatible?

If we _did_ roll these separately, wouldn't that mean that we now depended on two different versions of package:crypto? That seems like a bad situation to be in. Especially for a crypto-related package.

I dunno. It seems like the trade-offs here just offset one set of inconveniences for another, potentially worse, set. At least with the current inconveniences we are forced to do the right thing in general (e.g. keep package:image moving), which is good for the wider ecosystem.

**Comment by dnfield** [comment]
It was because package:image had a constraint like `^2.0.4` and we had another package going to 3.x.

Yes, this would mean we'd have two copies of the package at play.

Maybe the real answer here is to just more closely audit `dev` for stale/unused/unnecessary packages.

**Comment by Hixie** [comment]
> Maybe the real answer here is to just more closely audit `dev` for stale/unused/unnecessary packages.

I would certainly support that enthusiastically.

**Comment by Hixie** [comment]
see also https://github.com/flutter/flutter/pull/74682

**Comment by dnfield** [comment]
I filed https://github.com/dart-lang/linter/issues/2431 - at least one instance of `package:image` was unused in there.

**Comment by jonahwilliams** [comment]
I think we're going with https://github.com/flutter/flutter/issues/74070 instead
