### ISSUE TITLE
Migrate markdown to null safety and to packages repo

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#74757]
We need to migrate https://github.com/flutter/flutter_markdown/ to our packages repo (https://github.com/flutter/packages/) and port it to null safety.

(fyi @domesticmouse since you seem active in this repo; fyi @kf6gpe since you've looked at merging repos before)

**Comment by domesticmouse** [comment]
I'm curious what is required to port `flutter_markdown` to the packages repo?

**Comment by Hixie** [comment]
Nothing special, just making sure it fits the pattern in the other repo (changelog, readme, license, that kind of thing).

**Comment by thisisamank** [comment]
@domesticmouse I am interested in helping, but I am a newbie to open source so I will need some guidance.

**Comment by domesticmouse** [comment]
Hey @thisisamank,

You can see my initial attempt at [migrating to null safety](https://github.com/flutter/flutter_markdown/pull/324), but it's tests are currently reporting red. Feel free to pull my PR and see if you can figure out what changes are required to make Mockito happy.

Thanks!

**Comment by mjordan56** [comment]
Good morning Brett,

I've been looking at PR #324, your null safety first attempt. I figured out
what was failing in the link_test.dart tests. It's interesting to see how
some of the code reacts to the null safety changes. I assume you did the
"dart migrate" command to get these changes. I noticed at least one
instance of a null safety change being redundant. I won't hurt anything but
it wasn't necessary either. I'm looking at some of the other tests that are
failing. I just started looking at the image_test.dart tests. At
this point, this seems to be a MockHttpClient problem.

So, how do you want to coordinate our effort? I don't want to waste my time
if you or others are already working on something. Also, how do you want to
take fixes? I created a local branch in my fork with your PR. Do you want
us to merge our changes into your PR? I haven't done this before but GitHub
says this is doable.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork


https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

It looks like you have to grant permission to do this, which makes sense. I
have a change for the link tests now if you want them.

Michael

**Comment by mjordan56** [comment]
Hi Brett,

I've confirmed the image tests are failing due to a problem in
utils/createMockImageHttpClient line 195.

  when(client.getUrl(any))
      .thenAnswer((_) => Future<io.HttpClientRequest>.value(request));


The mock closure "any" has a return type of Null. I'm not sure of the
correct solution to fix this problem. I can figure it out but I thought you
or @thisisamank might have more insight into Mockito and know how to fix
this bug.

Anyhow, when I set the six image tests that fail to skip and with the fixes
I have for the link tests, I'm able to successfully complete all of the
tests with your PR. How would you like to proceed?

Michael

**Comment by Hixie** [comment]
I believe that Mockito isn't supported in null-safety right now. The fix we've used elsewhere is migrating away from mockito.

**Comment by domesticmouse** [comment]
Interestingly, the Mockito project has a null safety preview [version](https://pub.dev/packages/mockito/versions/5.0.0-nullsafety.5) and a [Null Safety README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md).

**Comment by tehprofessor** [comment]
Ahoy!

I have a side project I'm working on; where I had forked `flutter_markdown` to add a feature (`lang` attr to codeblocks), and last night also added null-safety. I backported the null-safety fix to master but didn't realize this PR exited... 😅  The branch with the null-safety migration completed is here: 

https://github.com/tehprofessor/flutter_markdown/tree/tehprofessor/null-safest

The test issues as noted above seem to stem from defining methods on the mocks themselves. The `createHttpClient` stub in `TestHttpOverrides` doesn't seem to do much so I removed it and the tests went green:

```
-class TestHttpOverrides extends io.HttpOverrides {
-  io.HttpClient createHttpClient(io.SecurityContext context) {
-    return createMockImageHttpClient(context);
-  }
-}
+class TestHttpOverrides extends io.HttpOverrides {}
```

There were also a couple of minor tweaks to the code beyond what the migration did and some cleanup from Dart Analysis.

I would've opened a PR but I don't want to step on your toes @domesticmouse since you've been working on coordinating and fixing the issue. I'm happy to try and coordinate cherry-picking changes from mine, copy-pastas, or whatever works to get us all to null-safety moar fastest... 🤘🏽😬 just let me know how y'all would like to proceed. Thank you for your time!

**Comment by domesticmouse** [comment]
Hey @tehprofessor please feel free to open a PR with your changes. My PR was meant mainly to discover blocking issues and start a conversation. 

I'm more than happy to close mine out in preference for a null safety migration that has been more thoroughly tested. Thanks!

**Comment by domesticmouse** [comment]
@Hixie the migration to null safety is progressing. 

I'm curious as to the need to migrate to the packages repo. I'm concerned about how to move across the git history to make sure the many contributors to `flutter_markdown` continue to get their appropriate attribution.

**Comment by Hixie** [comment]
> I'm curious as to the need to migrate to the packages repo.

We're trying to reduce the number of repos overall. It's not critical if you don't want to do it, but we need to do it eventually.

> I'm concerned about how to move across the git history to make sure the many contributors to `flutter_markdown` continue to get their appropriate attribution.

I've never done this before, but it seems there are ways, e.g. https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b

We'd need to make sure the PR doesn't do a "squash and merge" or whatever it's called when we land it.

**Comment by kf6gpe** [comment]
That's not the page I've followed, but essentially the same steps I've used.

As @Hixie has noted, we'd like to lower the number of repositories we have (both public and private). It's been on my to-do list ever since joining the team and unfortunately hasn't happened; the best I've been able to do is discourage adding new ones! (mostly...)

**Comment by domesticmouse** [comment]
I'll migrate the repo after the null safety migration has stabilised. I feel better now I know there is a way to keep Git history.

**Comment by stuartmorgan** [comment]
@domesticmouse I'm doing some other migrations, and could do this one if you're ready. It looks like there are a few open PRs; any that you want to land before migration?

**Comment by domesticmouse** [comment]
Please go ahead and migrate. The outstanding PRs require work from the authors to bring them up to date, add tests, and the like.

**Comment by stuartmorgan** [comment]
@domesticmouse Are you a member of the flutter.dev verified publisher on pub? If so, could you transfer https://pub.dev/packages/flutter_markdown over to the verified account (in the Admin tab)? If you're not, we should have @kf6gpe add you.

**Comment by stuartmorgan** [comment]
- Merge landed
- I closed the few remaining PRs with a message explaining what happened and what to do if they still want to move forward
- I migrated all the issues to flutter/flutter and tagged them with `p: flutter_markdown`

Once https://github.com/flutter/flutter_markdown/pull/368 is approved and landed we should be able to archive the repo.

**Comment by domesticmouse** [comment]
@stuartmorgan I'm OoO this week. I don't know if I'm part of the blessed group, and I don't know the process to transfer ownership. 

@kf6gpe can I get some time on your calendar next week for this?

**Comment by kf6gpe** [comment]
@domesticmouse Sure thing! When you're back, toss something on my calendar --- it should only take us a few munutes.

Enjoy (hopefully) your OoO-ness in the mean time.

**Comment by stuartmorgan** [comment]
> and I don't know the process to transfer ownership.

Once you've been added to the verified publisher group, it's super-easy:
- Go to https://pub.dev/packages/flutter_markdown/admin
- Pick "flutter.dev" in the first dropdown
- Press the red TRANSFER TO PUBLISHER button

**Comment by stuartmorgan** [comment]
@domesticmouse Alternatively you could add me to the package (`dart pub uploader --package=flutter_markdown add stuartmorgan@google.com`) and I can transfer it.

**Comment by domesticmouse** [comment]
@stuartmorgan uploader invite sent. Check your inbox =)

**Comment by stuartmorgan** [comment]
It's converted over, and I published the update that has the new metadata (pointing to the new source location), so this is finished!
