### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by safield** [flutter/flutter#74752]
The only Flutter bluetooth library is [flutter_blue](https://pub.dev/packages/flutter_blue). This library has seemingly been abandoned by the maintainer before even reaching 1.0. 

I think a core mobile functionality like bluetooth should be given first class support by the flutter team.

**Comment by sarbogast** [comment]
And the truth is that even native support for Bluetooth is ridiculous. On Android there are many differences between versions of Android. On iOS, libraries are very low-level and complicated to use. On both platforms, privacy and battery-life concerns have made APIs incredibly inconsistent and poorly documented. So much so that you almost have to use libraries on top of the standard APIs to do any meaningful work. There is a real opportunity for Flutter to unify and simplify those APIs but it needs to be done by people who have a deep understanding of how Bluetooth works on each platform, and it needs to offer more than just the smallest common denominator in features. It needs to support background scanning, UDID filtering, all services and characteristics, background notifications when a new client appears, both client and server functionality, etc. Right now, the absence of first-class Bluetooth support is the only thing preventing me from migrating one of my dual-native apps to Flutter.

**Comment by n30phyte** [comment]
The initial claim is wrong, but I agree with the rest. There are other Bluetooth libraries that work better than flutter_blue, such as https://pub.dev/packages/flutter_reactive_ble and https://github.com/Polidea/FlutterBleLib

**Comment by safield** [comment]
> The initial claim is wrong, but I agree with the rest. There are other Bluetooth libraries that work better than flutter_blue, such as https://pub.dev/packages/flutter_reactive_ble and https://github.com/Polidea/FlutterBleLib

Gonna give those a try! Thanks! Still believe in the sentiment that bluetooth should be rolled into the umbrella of the official repo.

**Comment by darshankawar** [comment]
Hello @safield 
There's a similar open proposal describing your case, https://github.com/flutter/flutter/issues/53493. I suggest you to follow-up there for updates and for any questions you may have.

I see your proposal has got lots of upvotes, but for better tracking of this issue and to avoid duplicates, I recommend to use the original issue.
Closing this as a duplicate in favor of https://github.com/flutter/flutter/issues/53493.
