### ISSUE TITLE
Plugin: Audio / Media

### ISSUE THREAD

**Issue by aleki** [flutter/flutter#7482]
It is not possible today with Flutter, right?

**Comment by eseidelGoogle** [comment]
Possible using https://flutter.io/platform-services/ (e.g. https://github.com/flutter/flutter/tree/master/examples/hello_services).

We definitely need an example of this common case.  We used to have one via https://github.com/vlidholt/game, but the system has changed since that time and that example no longer works.

**Comment by sethladd** [comment]
There's also a "proof of concept" plugin here: https://github.com/rxlabz/flutter-mediaplayer-plugin

**Comment by rxlabz** [comment]
a little update :) the POCs have evolved, there is 2 simple plugins now : 
- video_launcher https://pub.dartlang.org/packages/video_launcher
- audioplayer https://pub.dartlang.org/packages/audioplayer
with support for remote and local files for both

**Comment by sethladd** [comment]
Sweet!

@mit-mit what do you recommend we do with this issue?

**Comment by mit-mit** [comment]
Let's close it now we have plugins. Thanks again @rxlabz!

**Comment by rxlabz** [comment]
my pleasure !

**Comment by dellagustin** [comment]
Some time ago I was trying to build a media player app in cordova for Android.
One problem I had was that the existing plugins did play media on the main thread instead of playing it in a service and that caused the device to kill it when it was in background.
I imagine this plug in would have a similar issue.

**Comment by zoechi** [comment]
Backgroundprocessing for Flutter is being worked on. That might allow better solutions.
