### ISSUE TITLE
Duplicate GlobalKey exception thrown when using ReorderableListView

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#74840]
Using the latest `ReorderableListView`, if you have a lot of items and drag an item from the top of the list all the way the bottom and all the way back up to the top of the list you will trip an exception:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.
The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
instance is moved to the new location. The key was:
- [_ReorderableListViewChildGlobalKey ValueKey<int>#5b354]
```

This is caused by the way the internal list handles a child that has been unmounted and then rebuilt after it comes back into view. I will have a fix for this shortly.

**Comment by blono** [comment]
Until yesterday, https://github.com/flutter/flutter/pull/74842 this bug was not fixed even with this PR being merged.
However, I just ran a flutter upgrade and updated to the following version, and confirmed that the bug is fixed.

Flutter 1.26.0-18.0.pre.156 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 45508985b1 (65 minutes ago) • 2021-02-02 22:46:04 -0500
Engine • revision 2c144c3eeb
Tools • Dart 2.12.0 (build 2.12.0-282.0.dev)

**Comment by pedromassangocode** [comment]
@darrenaustin  can you confirm that https://github.com/flutter/flutter/pull/74842 fixes this?

@blono do you have a reproducible code sample for me to test?

**Comment by darrenaustin** [comment]
PR #74842 should fix this bug. Not sure how it was still failing if you had the change. @blono, when you saw the problem are you sure you were testing a version that had this PR? If so, can you give us the version you tested against and a how you reproduced the error?

I am going to close this, but please reopen if you can reproduce the problem with this PR in place. Thx.

**Comment by blono** [comment]
I upgraded flutter to include the fix from https://github.com/flutter/flutter/pull/74842.
I confirmed that the fix for https://github.com/flutter/flutter/pull/74842 was also imported locally.
However, https://github.com/flutter/flutter/issues/74840 was not fixed and the problem still occurred.
I then did another flutter upgrade and updated to the following version

Flutter 1.26.0-18.0.pre.156 - channel master -
https://github.com/flutter/flutter.git
Framework - revision 4550898 (65 minutes ago) - 2021-02-02 22:46:04 -0500
Engine - revision 2c144c3eeb
Tools - Dart 2.12.0 (build 2.12.0-282.0.dev)

https://github.com/flutter/flutter/issues/74840
The problem was fixed.
And now

Flutter is already up to date on channel master
Flutter 1.26.0-18.0.pre.215 - channel master
https://github.com/flutter/flutter.git
Framework - revision f3c10bd23a (47 minutes ago) - 2021-02-08 21:52:03 -0800
Engine - revision b04955656c
Tools - Dart 2.13.0 (build 2.13.0-0.0.dev)

I am using this version and the problem has been solved perfectly.
That's all from me.
