### ISSUE TITLE
Allow text to be selectable by default on the web

### ISSUE THREAD

**Issue by nwparker** [flutter/flutter#74871]
## Use case
Text on desktop websites is generally selectable. You'll notice this on all popular websites (google, amazon, youtube, facebook).

I strongly believe many web developer would like their text to be selectable by default. The previous issue (#32246) was closed, but had [much support](https://github.com/flutter/flutter/issues/32246#issuecomment-569154029)

## Proposal
The idea would be to allow flutter web to easily make all text selectable. If not by default, perhaps a setting on the `Theme` object itself to easily allow for this change.

**Comment by pedromassangocode** [comment]
Hi @nwparker 
Text selection by default was already discussed in #32246, please make sure you read the whole thread before reposting it again.

For the proposal you are requesting, there is a open issue with the same purpose https://github.com/flutter/flutter/issues/64854. Please follow up on that issue for updates.

**Comment by nwparker** [comment]
Thank you for the reply @pedromassango 

However, I do not think this issue should be closed.

> Text selection by default was already discussed in #32246, please make sure you read the whole thread before reposting it again.

I know and I have the read it in it's entirety. That's why I specifically referenced the issue in my issue. There was no solid conclusion to the above thread. If you disagree on this point, I'm happy to discuss. Please let me know your interpretation and how you reached it.

> For the proposal you are requesting, there is a open issue with the same purpose #64854. Please follow up on that issue for updates.

#64854 is a different issue. My issues is not about selection text across multiple widgets, but about about allowing text to be selectable by default on the web. 


With all due respect, I do not believe this issue should be closed for the reasons addressed above

**Comment by AmethystLiang** [comment]
Agree with @nwparker that this issue is different from the ones @pedromassangocode mentioned. 

#32246 was closed by an admin because he deemed that supporting selectable texts **on web** by default (which btw is the expected UX behavior) is not reasonable:

 > mdebbar commented on Oct 25, 2019
@dnfield @lubritto In Flutter, text isn't selectable by default. Try using SelectableText to enable selection of text. Please let us know if you face any issues. 


#64854 talks about the text selection widget, but even it is fixed, we still need to wrap every text with the selectable text. But texts should be selectable **by default** on the web. 

I hope someone can look at these proposals and make flutter usable on the web.

**Comment by pedromassangocode** [comment]
Hi @nwparker 
Please see https://github.com/flutter/flutter/issues/74881#issuecomment-768916018 for reasons. In short, in Flutter Text are not selectable by default, that is why the SelectableText was built, to support that. In https://github.com/flutter/flutter/issues/74881 you can find a code sample in how to build a custom widget that behave differently on Web and other platforms.

**Comment by maheshmnj** [comment]
There's an open issue for this proposal https://github.com/flutter/flutter/issues/78899 if someone stumbles upon this issue
