### ISSUE TITLE
About flutter tools

### ISSUE THREAD

**Issue by lycstar** [flutter/flutter#74892]
For first run flutter build apk , it will download some compile tools(gradle or some binary file), Where can I find documentation for these things？

**Comment by darshankawar** [comment]
@lycstar 
I am not sure if you'll get exact details as why it downloads the tools for the time, but I'll try to give you an idea. Hope it helps:

`flutter build apk` need to gather all arch types (arm, arm86 for example) before it could build the apk and hence when you run it for the first time, it'll download the required tools as below:

```
Downloading android-arm-profile/darwin-x64 tools...                912ms
Downloading android-arm-release/darwin-x64 tools...                555ms
Downloading android-arm64-profile/darwin-x64 tools...              684ms
Downloading android-arm64-release/darwin-x64 tools...              571ms
Downloading android-x64-profile/darwin-x64 tools...                587ms
Downloading android-x64-release/darwin-x64 tools...                545ms
```

Next time when you run same command, since the tools are already downloaded, it won't install it again.

You can find information related to how `building an apk` (although not in exact details, but it should give you an idea) here: https://flutter.dev/docs/deployment/android#build-an-apk

**Comment by lycstar** [comment]
@darshankawar Thank you for your reply , So Where can I find the x64 tool's source code, because i want to compile to get these tool for linux arm.

**Comment by darshankawar** [comment]
@lycstar 
Check out this https://github.com/flutter/flutter/tree/master/packages/flutter_tools/lib/src/linux
