### ISSUE TITLE
Text Editing Shortcuts/Intents/Actions

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#75004]
Currently, user events related to text editing are handled by a bunch of disparate code that could be consolidated.  For example, there is a [RawKeyboard listener in RenderEditable](https://github.com/flutter/flutter/blob/52e90f55f46a3c8d30403e07e0b019e89f523a87/packages/flutter/lib/src/rendering/editable.dart#L1040) in addition to our built-in keyboard Shortcuts system.

Key events should be consolidated into Shortcuts.  Mouse, tap, and other events should dispatch Intents that are handled the same way that the keyboard Intents are handled.

Related:
https://github.com/flutter/flutter/issues/30725
https://github.com/flutter/flutter/issues/57679
https://github.com/flutter/flutter/issues/101151

**Comment by justinmc** [comment]
When we've got some mouse/tap Actions being overridden, then an example of overriding these should be added to TextEditingActions.  I've removed the original one I had there for now.

<details>

<summary>Code</summary>

```dart
///
/// {@tool snippet}
///
/// This example shows how to use an additional [Actions] widget to override
/// the left arrow key [Intent] and make it move the cursor to the right
/// instead.
///
/// ```dart
/// final TextEditingController controller = TextEditingController(
///   text: "Try using the keyboard's arrow keys and notice that left moves right.",
/// );
///
/// @override
/// Widget build(BuildContext context) {
///   return Scaffold(
///     body: Center(
///       child: Actions(
///         actions: <Type, Action<Intent>>{
///           ArrowLeftTextIntent: TextEditingAction<ArrowLeftTextIntent>(
///             onInvoke: (ArrowLeftTextIntent intent, EditableTextState editableTextState) {
///               editableTextState.renderEditable.moveSelectionRight(SelectionChangedCause.keyboard);
///             },
///           ),
///         },
///         child: TextField(
///           controller: controller,
///         ),
///       ),
///     ),
///   );
/// }
/// ```
/// {@end-tool}
```

</details>

**Comment by justinmc** [comment]
We've now got a system for handling text editing interactions with Shortcuts/Intents/Actions: https://github.com/flutter/flutter/pull/75032

For this issue to be complete, we still need:

  - [ ] All text editing keyboard shortcuts ported to Shortcuts.
  - [ ] Text selection toolbar interactions ported to Intents/Actions (see https://github.com/justinmc/flutter/tree/text-editing-refactor-including-mouse-stuff).
  - [ ] All pointer-related text editing interactions ported to Intents/Actions, like tapping, long pressing, etc.

**Comment by boyan01** [comment]
Does this Text Editing Shortcuts/Intents/Actions in composing input mode for other languages such as Japanese and Chinese  has been considered?

## Background

  I am developing a flutter application with text input, However, it is found that the current `TextField` of flutter has serious experience problems on the macos platform in Chinese and Japanese input.

  Chinese and Japanese input methods will have a special place, they need to rely on multiple letters for combined input. which was named `Compsing` in [flutter](https://api.flutter.dev/flutter/services/TextEditingValue/composing.html) and `MarkedText` in [macOS](https://developer.apple.com/documentation/appkit/nstextinputclient/1438246-setmarkedtext) 

For example, in Chinese `Pinyin - Simplified` inpu mode

when you typed letters `n` `i`  in sequence, which a floating window will appear on the`TextField` with candidate text related to the letters which you just input(`ni`), and the first charater would be `你`.

This is an example of the video corresponding to the text input process described above.
https://user-images.githubusercontent.com/17426470/121132488-c9ecf800-c863-11eb-9e41-ff32204b5de8.mov

## Current problem

1. `DeleteTextIntent` did not support delete compsing text in macOS.  https://github.com/flutter/flutter/issues/78061
https://github.com/flutter/flutter/blob/ba5208122acb21002222b47f34d4664dba36fbd9/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L344-L349
2. the `MoveSelectionDownTextIntent` has intercepted `arrow down` key event during in composing state. As a result, the `arrow up` and `arrow down` keys cannot be used to expand the floating window for combined candidate text selection.
https://github.com/flutter/flutter/blob/ba5208122acb21002222b47f34d4664dba36fbd9/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L358

##  End

I tried to solve the above problem by modifying the flutter engine. Although the problem was temporarily resolved. But I still hope that flutter's text input framework takes into account the composed text input processing from the beginning of its design , in this way can the flutter framework be more usable.

**Comment by justinmc** [comment]
@boyan01 Thanks for the detailed comment!  We are trying to ensure that composing keyboards work on all of Flutter's platforms.  I can confirm that problem 2 is broken for me too.  I've created an issue for it here: https://github.com/flutter/flutter/issues/85328

**Comment by justinmc** [comment]
Unassigning myself as @LongCatIsLooong is the one working on bringing this to mouse/tap gestures.

**Comment by justinmc** [comment]
I'm going to close this now that the only work remaining is captured by https://github.com/flutter/flutter/issues/101151.
