### ISSUE TITLE
Scrollcontroller issues.

### ISSUE THREAD

**Issue by Darkhorse07232020** [flutter/flutter#75011]
How can I detect whether maxScrollExtent of Scroll controller is changed or not when I add children into Listview or Grid dynamically?

**Comment by iapicca** [comment]
@Darkhorse07232020 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@Darkhorse07232020 
Your issue description sounds more of a `How to` question rather than a bug or feature request in the framework. I'd suggest you to ask this question on support channels / use the link referred above. 
Closing this for now. If you think you are facing an issue in the framework, provide above requested details and I'll reopen it.
Thanks.
