### ISSUE TITLE
Please add the following information to assist when users are unable to install for MACOS BigSur

### ISSUE THREAD

**Issue by JamesVanWaza** [flutter/flutter#75041]
This link - https://stackoverflow.com/questions/58387606/flutter-app-running-error-dart-can-not-be-opened-developer-can-not-be-verified. Please add it in the documentation so that, it assists users when setting up Flutter. 

Thank you.

**Comment by darshankawar** [comment]
@JamesVanWaza 
There's an open issue similar to the error described in the SO link, https://github.com/flutter/flutter/issues/42969.
There's also a workaround to fix the issue, https://github.com/flutter/flutter/issues/36714#issuecomment-557617988.

A related issue was fixed already, https://github.com/flutter/flutter/issues/36714

I believe once https://github.com/flutter/flutter/issues/42969 is fixed and merged, you won't see the issue while upgrading macOS and devs will be able to use the current documentation to setup Flutter on macOS without any issues.

Closing this, as this issue is already being tracked above. If you disagree, write in comments and I'll reopen it.
