### ISSUE TITLE
Implement CupertinoNavigationBar

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7508]
https://developer.apple.com/ios/human-interface-guidelines/ui-bars/navigation-bars/

**Comment by xster** [comment]
Note to future self: content can slide under the navigation bar and be blurred

**Comment by xster** [comment]
Further note to future self (from gitters), Ian suggests using a CustomScrollView and the nav bar in a sliver that's semi transparent and doesn't move to have the effect of the list scrolling under the nav bar and the nav bar being translucent and blurry.

**Comment by xster** [comment]
Further further note to future self: the app bar needs a slot to hold #7509

**Comment by xster** [comment]
Brain storming:

I think whether the app bar is used with an iOS scaffold or not, it needs to be outside of the PageRoute/CupertinoPageTransition since it doesn't slide with the body content (#9446). 

Rather, the hierarchy is more like

Root > CupertinoTabBar > PageView > (CupertinoScaffold: CupertinoNavigationBar + Navigator) > pages

vs Material's

Root > Navigator > page > Scaffold > AppBar + BottomNavigationBar

(not too sure how to deal with fullscreen things like dialog barriers etc yet, maybe add something like look for the eldest navigatorstate)

For sharing/interchangeability, CupertinoTabBar is just going to be dumb UI (maybe we need something else to bundle CupertinoTabBar and PageView together for convenience) so that can just go into Scaffold.bottomNavigationBar. 

CupertinoNavigationBar will have a simple mode and an 'immersive' mode. The simple mode just mimics the AppBar with less dynamic stuff. One button left, one button right, one title/segmented control/wtv widget in the middle. Can be used for fullscreen dialogs or with material in Scaffold.appBar for just UI.

In full iOS mode, extract a superclass out of MaterialPageRoute that's easy to share with CupertinoPageRoute. Let CupertinoPageRoute take both the normal body builder and an CupertinoNavigationBar builder. If there's CupertinoScaffold (which would hold an animated navigation bar), it would use the page transition animation controller to also coordinate the crossfade between the 2 CupertinoNavigationBars.

**Comment by Hixie** [comment]
For full-page dialogs, you can have another Navigator on the outside.

**Comment by xster** [comment]
Remaining task in this issue:

- [ ] automatic addition of the leading button as a back or cancel/close button depending on the page type (which would require moving the fullscreen dialog concept from material page route to widget)
- [ ] more testing for integration with material scaffolds

Extracting support for double row nav bars to a different issue #10469.

**Comment by yathit** [comment]
Can `CupertinoTabScaffold` be used in `MaterialApp` ?

**Comment by Hixie** [comment]
Yes, in theory at least. I don't know if we've tested it.

**Comment by xster** [comment]
@yathit, yes, Cupertino scaffolds can be used in MaterialApps. Cupertino nav bars and tabs can be used in Material Scaffolds and Material app bars can be used in CupertinoPageScaffold too.

I created an example mixing and matching everything here:
https://github.com/xster/flutter-test/blob/master/t48_material_and_cupertino/lib/main.dart
