### ISSUE TITLE
Shift-mousewheel for horizontal scroll

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#75180]
On desktop, shift+mousewheel usually means "scroll horizontally". We don't seem to support this.

**Comment by stuartmorgan** [comment]
What OS were you testing? Unless I'm misremembering, macOS at least automatically translates this to horizontal scroll events at the OS framework level, so it should work there. I'm not sure how much Linux and Windows do for us.

**Comment by Hixie** [comment]
I tested on Linux and Web.

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
I think this will be easy to support, we should check the keyboard state here and adjust accordingly: 
https://github.com/flutter/flutter/blob/2dfc86ea0b2c0af54e0aa2155310053c3fe203b1/packages/flutter/lib/src/widgets/scrollable.dart#L639
cc @dkwingsmt who has a really big keyboard revamp underway. :)

**Comment by stuartmorgan** [comment]
Given that the behavior varies by OS, I would actually recommend implementing this in the embeddings rather than the framework.

**Comment by Piinks** [comment]
Makes sense. :)
Tested on MacOS, it does not appear to be supported on that platform either.

**Comment by stuartmorgan** [comment]
That's odd; macOS should definitely be sending the view horizontal scroll events.

Were you testing with a mouse or a trackpad?

**Comment by Piinks** [comment]
> That's odd; macOS should definitely be sending the view horizontal scroll events.
> 
> Were you testing with a mouse or a trackpad?

Just checked against another mouse, I am guessing the magic mouse is considered a trackpad. Using a stepped wheel mouse it does work. Updated comment above.

**Comment by Hixie** [comment]
> Given that the behavior varies by OS, I would actually recommend implementing this in the embeddings rather than the framework.

What if someone wants shift-mousewheel to do something else? Implementing it in the framework seems consistent with our usual approach of making everything configurable.

**Comment by stuartmorgan** [comment]
If we want to support that, we need to send something closer to raw hardware events. The discussion above is exactly the kind of problem we'd hit if we did this in the framework: we would treat shift+vertical trackpad scroll on macOS as a horizontal scroll, but that's not correct macOS behavior. macOS only applies shift to scroll wheels (i.e., hardware that doesn't have its own source of horizontal scroll events).

**Comment by Hixie** [comment]
I haven't thought this through, but my instinct is that the trackpad scroll (horizontal and vertical) would send different types of events than real mouse wheel. Is that feasible? Does it make sense?

**Comment by stuartmorgan** [comment]
Eventually trackpad scroll should send different events. I had a PR to do it 2 years ago or so, but you had concerns about how it was being done and wanted it redesigned, and then it never made it back to the to of the priority.

So right now, we send exactly the same events for both cases as a shortcut to make scrolling with a trackpad work. (Which is why macOS trackpad scroll doesn't do overscroll at the moment. And why pinch-to-zoom doesn't work.)

**Comment by yjbanov** [comment]
I think a more serious issue right now is that if a view scrolls horizontally there's no way to use the scroll wheel to scroll at all. Dragging the view to scroll isn't something desktop users may even think to try. Perhaps, until we figure out what to do with the Shift key, we should just scroll in the desired direction for all scroll wheel events?

**Comment by Piinks** [comment]
> Perhaps, until we figure out what to do with the Shift key, we should just scroll in the desired direction for all scroll wheel events?

@yjbanov I am not sure I follow, how do we determine the desired direction? 

Just making note, this may be a blocker for https://github.com/flutter/flutter/issues/71322

**Comment by stuartmorgan** [comment]
> I think a more serious issue right now is that if a view scrolls horizontally there's no way to use the scroll wheel to scroll at all.

For any platform where this is true (again, it's not true on all of them), I expect it would be fixable at the embedding level without breaking trackpad.

(/cc @cbracken)

**Comment by yjbanov** [comment]
@Piinks 

> @yjbanov I am not sure I follow, how do we determine the desired direction?

Scrollable containers know the scroll direction. For example, `ListView.builder` takes `scrollDirection` parameter.

@stuartmorgan 

> For any platform where this is true (again, it's not true on all of them), I expect it would be fixable at the embedding level without breaking trackpad.

True, modulo @Hixie's configurability concern (https://github.com/flutter/flutter/issues/75180#issuecomment-772001397)

**Comment by Piinks** [comment]
> > @yjbanov I am not sure I follow, how do we determine the desired direction?
> 
> Scrollable containers know the scroll direction. For example, `ListView.builder` takes `scrollDirection` parameter.

Ideally, yes, but there are use cases where I think this assumption would break expectations. If I am scrolling a mouse wheel, and we assume because the scroll direction is horizontal that we should just apply that delta horizontally, what happens if the horizontal scrollable is within a vertical scrollable?

**Comment by yjbanov** [comment]
> If I am scrolling a mouse wheel, and we assume because the scroll direction is horizontal that we should just apply that delta horizontally, what happens if the horizontal scrollable is within a vertical scrollable?

Hmm, good point. Let's not do that then :)

**Comment by TahaTesser** [comment]
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          if (index == 0) {
            return SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: SizedBox(
                height: 240,
                child: ColoredBox(
                  color: Colors.redAccent,
                  child: Center(
                    child: Text(
                      'This is a horizontally scrolling view. ' * 20,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 142,
                      ),
                    ),
                  ),
                ),
              ),
            );
          }
          return SizedBox(
            width: double.infinity,
            height: 120,
            child: ColoredBox(
              color: HSVColor.fromAHSV(1, (index * 45) % 360, 3 / 4, 3 / 4)
                  .toColor(),
            ),
          );
        },
      ),
    ),
  ));
}

``` 
</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.295, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.3.0-17.0.pre.295 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f289aa19e7 (88 minutes ago), 2021-06-10 02:29:02 -0400
    • Engine revision ad6c83164e
    • Dart version 2.14.0 (build 2.14.0-194.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0
[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233
[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0
[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1052]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.101
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.41
• No issues found!
```

</details>

**Comment by saibotma** [comment]
Would be great to also have it as an option to scroll horizontally by default without having to press shift.
Most of our customers don't know that they have to press shift in order to scroll horizontally.

**Comment by creativecreatorormaybenot** [comment]
After the scrolling changes that now landed in stable, this is somewhat critical to the out-of-the-box behavior of most Flutter apps because of https://github.com/flutter/flutter/issues/83359.

That is it is now impossible to scroll horizontally by default, unless you explicitly override the `scrollBehavior`.

**Comment by renancaraujo** [comment]
At Rows, we have a use case where dragging is not a valid scroll gesture. So we made a workaround on this. We replicated the mousewheel resolving code from `Scrollable` checking if `RawKarboard.instance.keysPressed` contains any shift. The problem with checking the keyboard in that way is that **RawKarboard.instance only maps the keys pressed when the app is focused**. 

Since the flutter can receive pointer signals even if it is not focused, this workaround can have an unintuitive result for the end user.

**Comment by Hixie** [comment]
Interesting. Can you file a bug specifically about how "shift" state isn't represented when the app isn't focused?

**Comment by renancaraujo** [comment]
> Interesting. Can you file a bug specifically about how "shift" state isn't represented when the app isn't focused?

Done here: https://github.com/flutter/flutter/issues/97528

**Comment by vanceism7** [comment]
Any updates on when this issue will be resolved?

**Comment by feinstein** [comment]
Could we also have a mechanism for forcing an horizontal scroll with just the scroll wheel? I mean to be optionally without the shift.

I have seen some desktop applications that have a banner rolling some information continuously (like a stock market quote list, with all stocks scrolling horizontaly... Or latest news), and many of those apps help the user experience by just allowing the user to scroll on them, and they will be smart enough to scroll horizontaly, without forcing the user to use both hands, which can be very helpful for applications that demand speed (stock market) or accessibility for people with mobility issues.

**Comment by dkwingsmt** [comment]
> Could we also have a mechanism for forcing an horizontal scroll with just the scroll wheel? I mean to be optionally without the shift.
> 
> I have seen some desktop applications that have a banner rolling some information continuously (like a stock market quote list, with all stocks scrolling horizontaly... Or latest news), and many of those apps help the user experience by just allowing the user to scroll on them, and they will be smart enough to scroll horizontaly, without forcing the user to use both hands, which can be very helpful for applications that demand speed (stock market) or accessibility for people with mobility issues.

Can you open a new issue to explain this so that it's easier to track?

**Comment by feinstein** [comment]
@dkwingsmt I opened #109433, please let me know if it needs more clarification.

**Comment by Piinks** [comment]
Chatted with @yjbanov and @gspencergoog about this recently (and separately). We considered again approaching this from the framework, but while looking into how this is already done on Mac, it looks like by the time the input data is received in the engine, the axis has already been flipped. We don't flip it ourselves based on the keyboard state.

Enabling this on other platforms through the embedder is the right way to go I think, otherwise we would have inconsistency between what type of signal we are getting on one (Mac) versus the others.

**Comment by Hixie** [comment]
The more we do at the embedder the less power we are giving developers at the framework level. In general I'd much rather we do as much as possible in the framework and get true and real data from the embedders. (In other words, I'd much rather we fix Mac to send the real data.)

**Comment by feinstein** [comment]
Maybe the embedder can send a flag that indicates how's the behavior of the platform, and at the framework level we can correct any input in the way that we want, so we can have all the options at our disposal.

**Comment by Piinks** [comment]
I agree, I much preferred doing this in the framework to allow customization, but since we don't control the input from Mac (it appears to flip axes itself when shift is applied before it reaches Flutter), do we add complexity to the framework by re-flipping the signal, or assume the signal from the engine is wrong, or right based on which platform we are on? Or change it in the engine back to the original axis before sending it to the framework?

I can see it causing a lot of confusion if it is not consistent across platforms, after all, it already is. 😂 

It would still be very easy to do this in the framework (read: here is a proposal PR I just whipped up https://github.com/flutter/flutter/pull/115610)
 - but adding a workaround for Mac already handling it felt like code smell.

I'd love to fix this finally if we can agree on an approach one way or the other. I think the lack of a clear solution is why this has not been resolved yet. However, many of the concerns above are no longer an issue because trackpad has its own, separate handling now, which is how we ended up circling back to it.

**Comment by gspencergoog** [comment]
I would very much like to get support for horizontal scrolling on Linux and Windows into the next stable release. It really seems embarrassing that we don't have support for horizontal scrolling. So whatever we do, we should at least implement a first pass at it quickly.

I dislike that macOS is determining our implementation choice here. Could we flip the direction back on macOS before we send it if shift is down? Then the values coming from the embedder could be consistent across platforms, and we could check in the framework for the shift being down. It might be more complicated than that, though, since we'd also probably have to account for "natural" scroll direction settings being different for horizontal and vertical and flip the sign too in the appropriate cases.

So, I propose: fix macOS to un-flip the values coming from the embedder, then detect whether shift is down or not in the framework, and use that as a signal to switch between horizontal and vertical scrolling.

**Comment by cbracken** [comment]
Is shift-scroll a standard pattern across all OSes? If so, (and I _think_ that's the case currently?) then agreed it'd be nice for this to happen in the framework. We do other event normalisation type tasks in the embedders; there's probably no reason we couldn't do the same for macOS to undo its auto-horizontalisation.

**Comment by Hixie** [comment]
Is there anywhere I can read more about what macOS is doing? What exactly is being translated, by whom, from what to what?

**Comment by Piinks** [comment]
I do not know a whole lot about it, but this is what I found in the engine as far as how the scrolling input is bubbled up on Mac: https://github.com/flutter/engine/blob/aeb2cd95b19dfab26bc4ab21137c62783e523d69/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm#L646

We aren't checking in the engine if the shift key is down, so the incoming input has already been flipped from dy to dx.

**Comment by stuartmorgan** [comment]
We receive scroll events via `NSScrollWheelEvent`s via `-[NSView scrollWheel]`. These are logical scroll events, not raw hardware events, so as discussed earlier here, if someone holds down shift and scrolls the scroll wheel on a standard mouse, what we get is horizontal scroll deltas. If they've enabled the system setting for reverse scroll, that's already been applied as well.

If we want to do everything in the framework instead, we'd either need to:
- find another API that gives us untranslated events (if there is such a thing), or
- attempt to reverse-engineer the behavior and reverse it (if we have enough information)

If we want to do the latter, we would need to be very careful to test a variety of edge cases. E.g., what if someone has a device like a Mighty Mouse that actually has physical horizontal scrolling, holds down shift, and scrolls the ball/wheel horizontally?

We'd also need to make sure that we're either continuing to honor system settings like reverse direction at the embedder level ourselves, or plumbing those into the framework to honor in the framework.

**Comment by Hixie** [comment]
If the system is sending us logical "scroll delta" events, are those distinguishable from hardware "mousewheel + shift" events? I think it would be fine to honour logical events from the system on systems that give those to us, while honoring hardware events on those that do not. The idea is to do the best we can on each platform.

**Comment by stuartmorgan** [comment]
The scroll event system I added when bringing up scroll support initially on desktop doesn't distinguish, but we could potentially add more metadata to the scroll events at the embedder.h level and have each embedding tag the events accordingly.

**Comment by Hixie** [comment]
Right to be clear I mean does the OS distinguish. The embedder itself should as much as possible just pass through the OS data as completely as possible while coercing it into our protocol (so e.g. making sure down events are matched by up events and so on). This may indeed mean adding additional metadata to our events to be able to distinguish the kind of event we get from one platform from those we get on another.

**Comment by gspencergoog** [comment]
It would be nice if it did add some of the metadata: while working on the Time Picker, I realized that I can "scroll" the dial on the time picker, because a two-finger scroll is considered a drag, just with two fingers: the scroll gesture just adds to the delta, making for a weird interaction.  If I knew whether it was part of a scroll or not, I could filter those drags out.

**Comment by stuartmorgan** [comment]
> Right to be clear I mean does the OS distinguish.

Right now we have no mechanism in the macOS embedding to receive anything other than preprocessed logical be deltas, so there's nothing to distinguish between.

As mentioned above I don't know offhand if there are other (e.g., CG-level) APIs for anything else.

**Comment by Hixie** [comment]
that sounds about par for the course on mac. But in general that's not unusual. We have this situation with the keyboard APIs too, where each platform does some preprocessing before the embedder does it, and the embedders do their best to provide a coherent unopinionated view of the keyboard so that the framework can then do the best thing on each platform. When you have the precise platform-specific semantic, you pass that through; when you don't, you pass in the ground truth, and the framework implements the semantic directly if available and otherwise does the platform-specific thing with the ground truth.
