### ISSUE TITLE
Ability to build into a single file executable for Windows and Linux

### ISSUE THREAD

**Issue by ekasetiawans** [flutter/flutter#75200]
A project built for macOS becomes an app file, which makes distribution a lot easier. But in windows and linux it becomes several files and folders. So, consider that flutter can create an executable file for windows and linux to make distribution easier and also more portable than copying multiple files.

**Comment by stuartmorgan** [comment]
A single-file Flutter application is infeasible. Static libraries need to be built with the same toolchain and build settings as the executable linking them, so this would require Flutter developers to [build the entire engine from source](https://github.com/flutter/flutter/wiki/Compiling-the-engine), which is several orders of magnitude harder than installing Flutter.

Other changes that would be necessary include:
- somehow building the `app` shared library from the Dart code in a way that was compatible with static linking; currently that's driven by the `flutter` tool, so would require a completely different build setup.
- adding an application target to the engine build system.
- adding new APIs to embedder.h to load resources by memory offset from the binary instead of by path.
- writing new tooling to embed those resources.
- changing the plugin ecosystem to require that all plugins build as static libraries (which significantly increases the risk of cross-plugin conflicts), including any dependencies they may have; this would be a breaking change, and also limit plugin developer flexibility.

Building and maintaining all of that as a completely separate way of building apps would be a large amount of work, add complexity to the ecosystem, and almost nobody would ever actually use it due to the significantly higher difficulty in setting up the build environment.

> A project built for macOS becomes an app file, which makes distribution a lot easier. But in windows and linux it becomes several files and folders.

A `.app` is not a file, it's a directory that looks like a file in Finder. The basic structure of the macOS application is not actually fundamentally different from the self-contained folder that's built on Windows and Linux. The only difference is that the OS provides a standard bundled application format.

(/cc @cbracken since this has come up a few times in various places, so this will probably be useful to link to in the future.)
