### ISSUE TITLE
Horizontal scrollbar is not clickable and is not shown on the first frame when `isAlwaysShown: true` 

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#75352]
Here is gist with sample code for the problem: https://gist.github.com/kenzieschmoll/c9152384ce6487a181750e35f8a0d169.
Reproducible on web and desktop.

The vertical scrollbar is shown on the first frame. The horizontal scroll bar is only shown after scrolling has begin in the horizontal list view. The vertical scrollbar is also clickable and draggable, while the horizontal scrollbar is not.

**Comment by TahaTesser** [comment]
Thanks for filing the issue.
Reproducible on mobile, web, desktop

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SizedBox(
          height: 300,
          width: 300,
          child: Scrollbar(
            isAlwaysShown: true,
            controller: _scrollController,
            child: ListView(
              scrollDirection: Axis.horizontal,
              children: [
                Container(height: 100, width: 100, color: Colors.red),
                Container(height: 100, width: 100, color: Colors.green),
                Container(height: 100, width: 100, color: Colors.red),
                Container(height: 100, width: 100, color: Colors.green),
                Container(height: 100, width: 100, color: Colors.red),
                Container(height: 100, width: 100, color: Colors.green),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

```

</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.186, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.186 at /Users/tahatesser/Code/flutter_master
    • Framework revision 39114251af (2 hours ago), 2021-02-04 01:16:04 -0500
    • Engine revision 1c2c78398c
    • Dart version 2.12.0 (build 2.12.0-284.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by xu-baolin** [comment]
CC @Piinks Hi
I just take a look at this issue. Here is the investigation result,
Both of the `Scrollbar` without a `ScrollController` then they will share a `PrimaryScrollController` and causes this issue.
We can work around it by providing them `ScrollController`.

Furthermore, we can improve the description of the documentation or revert to force a controller when `isAlwaysShown` is true like before.

**Comment by Piinks** [comment]
Hey @xu-baolin thanks for investigating!! You are right, and this is very curious behavior to me. I did not realize that the `PrimaryScrollController` is used when `primary == null && controller == null`... but only in the vertical axis?

However, I found this to be the case in multiple places of the API:
https://github.com/flutter/flutter/blob/06e9456a909a020b12c0c88da88ae6bd40692983/packages/flutter/lib/src/widgets/scroll_view.dart#L108
https://github.com/flutter/flutter/blob/06e9456a909a020b12c0c88da88ae6bd40692983/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L231

But not everywhere:
https://github.com/flutter/flutter/blob/06e9456a909a020b12c0c88da88ae6bd40692983/packages/flutter/lib/src/widgets/editable_text.dart#L1568

I don't know that this makes much sense, it is at least inconsistent. If `primary == null`, and the Scrollable uses the `PrimaryScrollController` anyways, I think this would present conflict if another scrollable in the same scope sets `primary = true`. As I understand it now, this could potentially be an issue beyond just the `Scrollbar`, if `primary` is not explicitly set to false.

If `primary == null && controller == null` I think maybe we should be creating a `ScrollController`, instead of assuming that the `PrimaryScrollController` is available. Curious to know what you think and see if that kind of change exposes more understanding of why it is the way it is right now. 

As for the changes to the assertion in `isAlwaysShown` I don't think we want to revert that. That was part of the changes to make it possible to incorporate `isAlwaysShown` into `ThemeData`. cc @HansMuller Reference: https://github.com/flutter/flutter/pull/72316

There may be some adjustments to make there, this is a new feature so if there is something missing we can certainly tweak it. Thoughts welcome on this. :)

**Comment by Piinks** [comment]
Also could just require more documentation as the exclusion of the horizontal axis seems intentional.

**Comment by xu-baolin** [comment]
1.about `PrimaryScrollController` used.
This behavior is indeed a bit strange. I tried to find some clues from the merge log and then found this #8506. It did this intently without explaining the reason.
https://github.com/flutter/flutter/blob/da6528cda6ad884488868fd30cd10b7ded34b114/packages/flutter/lib/src/widgets/scroll_view.dart#L168

2.tweak `Scrollbar`
The `Scrollbar` use of `PrimaryScrollController` is based on the premise that `ScrollView` will also use it(The fact is that there are many situations where scrollview will not use it.), and cannot have multiple Scrollbar share it(this issue scenario), otherwise, the interaction of bar will conflict.

Also, If we change the second ListView scroll direction to vertical too, the scrollbar will trigger a exception,
```dart
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109:12)
#3      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:863:27)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
...
====================================================================================================
```


I agree that improve the documentation and suggest that assign a controller to the bar.

**Comment by Piinks** [comment]
This strange behavior in the horizontal axis has also been reported in https://github.com/flutter/flutter/issues/75713
