### ISSUE TITLE
Flutter framework checks failing on seemingly unrelated Dart errors

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#75524]
Some recent commits seem to be failing on unrelated Dart or file directory errors in the post-merge checks.

For example, [this commit containing framework changes](https://github.com/flutter/flutter/commit/a77388e670ad9860c0be0d249c9c832de719e6f2) is failing on the following:
1. linux_analyzer_benchmark: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyzer_benchmark/504/overview
2. linux_flutter_test_performance: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_test_performance/514/overview

**Comment by shihaohong** [comment]
cc/ @godofredoc

**Comment by godofredoc** [comment]
Yesterday we landed a change to use "flutter doctor" instead of "flutter update-packages" we validated most of the tests but seems like we missed those two.

We reverted the change: https://flutter-review.googlesource.com/c/recipes/+/10200

There are three action items here:

- [ ] Add linux_analizer_benchmark to the led recipe tests 
- [ ] Add linux_flutter_test_performance to the led recipe tests 
- [ ] Update the tests to run flutter update-packages rather than delegating to the recipe.

**Comment by godofredoc** [comment]
Additional fix was required for the dart_docs in the devicelab tests: https://github.com/flutter/flutter/pull/75933
