### ISSUE TITLE
[question]Calling C ++ via the plugin introduces a compilation error caused by the VCPKG package in CMake

### ISSUE THREAD

**Issue by fawdlstty** [flutter/flutter#75617]
## Steps to Reproduce

1. win7 x64, install flutter、vs2019、vcpkg (run: vcpkg install fmt:x64-windows fmt:x64-windows-static)、etc.
2. create a flutter project and flutter plugin project, in plugin_project/windows/CMakeLists.txt, append:

```cmake
find_package(fmt CONFIG REQUIRED)
target_link_libraries(main PRIVATE fmt::fmt)
#target_link_libraries(main PRIVATE fmt::fmt-header-only)
```

3. goto flutter project and run `flutter build windows`

## Logs

<details>
<summary>Logs</summary>

```bash
E:\projects_flutter\mitao_livestation>flutter build windows

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/live_native/windows/CMakeLists.txt:26 (find_package):

  Could not find a package configuration file provided by "fmt" with any of

  the following names:



    fmtConfig.cmake

    fmt-config.cmake



  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"

  to a directory containing one of the above files.  If "fmt" provides a

  separate development package or SDK, be sure it has been installed.




Unable to generate build files

E:\projects_flutter\mitao_livestation>flutter build windows

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/live_native/windows/CMakeLists.txt:30 (find_package):

  Could not find a package configuration file provided by "fmt" with any of

  the following names:



    fmtConfig.cmake

    fmt-config.cmake



  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"

  to a directory containing one of the above files.  If "fmt" provides a

  separate development package or SDK, be sure it has been installed.




Unable to generate build files

E:\projects_flutter\mitao_livestation>
```

</details>

look similar: #32719

**Comment by TahaTesser** [comment]
Hi @fawdlstty 
Looks like you're trying to achieve this while there is no support for it, the error is purely from Cmake instead of Flutter
Closing in favor of https://github.com/flutter/flutter/issues/32719
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by stuartmorgan** [comment]
Specifically, this doesn't work because `vcpkg` doesn't just make things globally available; you have to point CMake to your installation: https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#cmake-toolchain-file

There's not currently a way to do that in Flutter since apparently that CMake flag can only be passed via the command line.

**Comment by fawdlstty** [comment]
I was able to introduce the VCPKG package and compile it through the cmake project of vs2019, so this problem can be solved by templates, right?

**Comment by fawdlstty** [comment]
such as using CMakeSettings.json
