### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

### ISSUE THREAD

**Issue by aradhya32psp** [flutter/flutter#75699]
Hi!
I used image_picker in my project. It was working fine until I did not work of Firebase. After using firebase authentication, the image_picker started giving error. Please help because it is urgent.

```
E/flutter (27288): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter (27288): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (27288):
E/flutter (27288): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (27288): #2 MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
E/flutter (27288): #3 ImagePicker.pickImage (package:image_picker/image_picker.dart:61:34)
E/flutter (27288): #4 ImagePickerHandler.openGallery (package:talent/Screens/Profile/image_picker_handler.dart:26:35)
E/flutter (27288): #5 ImagePickerDialog.build. (package:talent/Screens/Profile/image_picker_dialog.dart:93:42)
E/flutter (27288): #6 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (27288): #7 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (27288): #8 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (27288): #9 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (27288): #10 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (27288): #11 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (27288): #12 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27288): #13 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (27288): #14 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27288): #15 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27288): #16 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:368:19)
E/flutter (27288): #17 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
E/flutter (27288): #18 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
E/flutter (27288): #19 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
E/flutter (27288): #20 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
E/flutter (27288): #21 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
E/flutter (27288): #22 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
E/flutter (27288): #23 _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (27288): #24 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (27288): #25 _CustomZone.runUnaryGuarded (dart:async/zone.dart:
```

**Comment by kashishkhullar** [comment]
Ensure that the package is installed and is present in the pubspec.yaml file. If restart does not work, undeploy the app, uninstall from the emulator or device, run `flutter clean`, rebuild and deploy the app.

**Comment by aradhya32psp** [comment]
> Ensure that the package is installed and is present in the pubspec.yaml file. If restart does not work, undeploy the app, uninstall from the emulator or device, run `flutter clean`, rebuild and deploy the app.

Hello brother, all of these steps are attempted many times. But problem is still...

**Comment by darshankawar** [comment]
@aradhya32psp 
When do you get this error ? After adding `firebase_auth` in `pubspec.yaml` and then while running `flutter pub get` ? or while running your app ?
Can you provide `flutter doctor -v`, `pubspec.yaml` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?

**Comment by aradhya32psp** [comment]
Hello **@darshankawar** 

### **flutter doctor -v**
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Pushpendra\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Redmi 5 (mobile) • 9aebd24c7d25 • android-arm64 • Android 8.1.0 (API 27)


### **pubspec.yaml**

name: talent
description: A new Flutter application.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  video_player: ^1.0.1
  salomon_bottom_bar: ^2.0.0
  gender_selection: ^1.0.0
  intl: ^0.16.1
  direct_select_flutter: ^1.0.7
  expand_widget: ^1.1.0
  flutter_staggered_grid_view: ^0.3.2
  combos: ^1.2.0
  image_cropper: ^1.3.1
  pin_code_fields: ^6.0.2
  flare_flutter: ^2.0.6
  email_validator: ^1.0.6
  cool_alert: ^1.0.3
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  flutter_launcher_icons: ^0.8.1
  splash_screen_view: ^1.0.3
  data_connection_checker: ^0.3.4
  connectivity: ^2.0.2
  firebase_core: ^0.7.0
  sign_button: ^1.0.1
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  transition: ^1.0.2
  firebase_database: ^6.0.0
  cloud_firestore: ^0.16.0
  path_provider: ^1.6.27
  uuid: ^2.2.2
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  image_picker: ^0.6.7+22



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  path: ../

flutter_icons:
  image_path: "assets/gutargoo_logo.png"
  android: true
  adaptive_icon_background: "assets/gutargoo_logo.png"
  adaptive_icon_foreground: "assets/gutargoo_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/photo_camera.png
    - assets/gutargoo_logo.png
    - assets/verify.png
    - assets/otp.flr
    - assets/Phone.png

### **image picker code**

File img;

handleTakePhoto(int type) async{
   Navigator.pop(context);
   File obj = await ImagePicker.pickImage(source: (type == 1 ? ImageSource.camera : ImageSource.gallery), imageQuality: 75);
   setState(() {
     img = obj;
   });
 }

 uploadImage(Pcontext) {
   return showDialog(
       context: Pcontext,
       builder: (context) {
         return SimpleDialog(
           children: [
             SimpleDialogOption(
               child: Text('Camera'),
               onPressed: () => handleTakePhoto(1),
             ),
             SimpleDialogOption(
               child: Text('Gallery'),
               onPressed: () => handleTakePhoto(2),
             ),
             SimpleDialogOption(
               child: Text('Cancel'),
               onPressed: () => Navigator.pop(context),
             )
           ],
         );
       }
   );
 }

### **Error**

E/flutter (27223): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter (27223): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (27223): <asynchronous suspension>
E/flutter (27223): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (27223): #2      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
E/flutter (27223): #3      ImagePicker.pickImage (package:image_picker/image_picker.dart:61:34)
E/flutter (27223): #4      _UploadPics.handleTakePhoto (package:talent/uploadPictures.dart:55:33)
E/flutter (27223): #5      _UploadPics.uploadImage.<anonymous closure>.<anonymous closure> (package:talent/uploadPictures.dart:69:33)
E/flutter (27223): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
E/flutter (27223): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
E/flutter (27223): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (27223): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (27223): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (27223): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (27223): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (27223): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (27223): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27223): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (27223): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27223): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27223): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:368:19)
E/flutter (27223): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
E/flutter (27223): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
E/flutter (27223): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
E/flutter (27223): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
E/flutter (27223): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
E/flutter (27223): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
E/flutter (27223): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (27223): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (27223): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (27223): #28     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (27223): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by aradhya32psp** [comment]
I am not sure but I think this is happening after change in build.gradle..

**Comment by darshankawar** [comment]
@aradhya32psp I am guessing this is happening due to a known issue in Android's v1 and v2 embedding. From your `pubspec.yaml` I see that there are lot of 3rd party plugins which may still be using v1 embedding which could be the root-cause of the issue you are facing.  See [this](https://github.com/flutter/flutter/issues/75416) open issue for reference. 

For now, you may have to go back to your previous setting in `build.gradle`.

**Comment by aradhya32psp** [comment]
@darshankawar Sir, May you help me on remote connection?

**Comment by darshankawar** [comment]
@aradhya32psp 
Please see https://flutter.dev/community for resources to get help on your issue.
You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Also, as I suggested earlier, did you try to switch back to previous `build.gradle` settings to know if it resolves your issue ?
Since your issue is similar to the one I referred earlier, I'll need to close this as duplicate and you may need to follow-up in original issue for updates.

**Comment by avid00** [comment]
I don't get any errors but my output is somewhat the same and the raisedbutton() doesn't work. like nothing happens when I click on it.


here is what I get:

E/flutter (27113): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter (27113): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
E/flutter (27113): #1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
E/flutter (27113): #2      FirebaseStorage.instance (package:firebase_storage/src/firebase_storage.dart:53:21)
E/flutter (27113): #3      _HomeState.uploadImage (package:untitled1/main.dart:56:38)
E/flutter (27113): #4      _HomeState.build.<anonymous closure> (package:untitled1/main.dart:48:30)
E/flutter (27113): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (27113): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (27113): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (27113): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (27113): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (27113): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (27113): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (27113): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (27113): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27113): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (27113): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27113): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27113): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (27113): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (27113): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (27113): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (27113): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (27113): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (27113): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (27113): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (27113): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (27113): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (27113): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (27113):
