### ISSUE TITLE
OpacityLayer causes sharp increases in memory usage in trivial apps

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#75697]
Reproduction code (only depends on `dart:ui` and a large image):

https://gist.github.com/ds84182/2621bab595f769474be9971fbfab89b4

Copied from the documentation comment on main():

-------------------

Raw, dart:ui-only example of an issue with opacity layers & the rasterizer cache.

Works best on Desktop, controls need to be changed for Android & iOS.
Web untested.

## Controls:

Left Click - Add Opacity Layer
Right Click - Remove Opacity Layer

## Expected Behavior:

Adding opacity layers does not increase the total memory usage.

## Actual Behavior:

Each opacity layer causes the RasterCache to allocate a new 4,000 by 2,000 texture.

One would expect that nested opacity layers would collapse into a single (equivalent) layer, and one would expect that a picture layer displaying a simple image could merge with the opacity layer, resulting in a call to drawImage with a Paint applying the equivalent opacity.

## Why does this matter?

There are many scenarios where a developer can place one (or more) opacity layers around a simple image. For example, the built-in FadeInImage widget, which uses FadeTransition, which eventually produces an opacity layer in RenderAnimatedOpacity.

Apps fade in images a lot. An image-heavy application (e.g. our application) can vary in memory usage wildly, regardless of the Flutter-level ImageCache.

Additionally, an app with an infinite scrolling list of images being faded in will hit memory limits on fast flings. Not because of image loading, but because the raster cache is unbounded when used in conjunction with  OpacityLayer. This is also why video memory usage can seemingly fluctuate, or fail to match the exact number of images loaded.

## What can be done?

OpacityLayer currently delegates out to the RasterCache, drawing the child layer with the specified paint.

https://github.com/flutter/engine/blob/ecfe5aec50e5a8d97e4818addbcef47f7300d2d1/flow/layers/opacity_layer.cc#L63

This can be changed to allow layers to:

1. Trivially combine paints (OpacityLayer -> OpacityLayer situation)
2. Circumvent the need for the raster cache by combining paints together, if compatible (OpacityLayer -> simple PictureLayer situation)

Perhaps an ImageLayer can be introduced, to make this situation easier to optimize, since Skia Pictures are opaque (can't get list of Ops out).

------------------------------

cc @dnfield 
also goodnight, it's 1:30am.

**Comment by dnfield** [comment]
I wonder if @flar or @chinmaygarde have a good idea for this.

I think this is probably WAI right now. Opacity layers are expensive, and caching them is generally the right thing to do. Using lots of large opacity layers is not going to be great for performance - it requires having additional render targets and is computationally expensive. 

It sounds like we _might_ want some kind of cap on the raster cache so that it doesn't just keep gobbling up memory. 

The problem with "combining paints" is that it won't always be correct. There are trivial situations where it will work, but as soon as you need to blend multiple opacities it will sometimes be incorrect. Flutter SVG tried to optimize things this way and had to stop because it only worked for simple cases and detecting when those cases are valid is actually pretty expensive and difficult.

If you or anyone has an idea for a foolproof heuristic that would actually work _and_ isn't more expensive than just doing what we currently do, it'd be super cool. I think the hard part is the case where it has to get invalidated because you encounter a new opacity layer getting blended in, and making sure you still have access to the _original_ opacity values for each layer you combined that you now have to un-combine to get the correct alpha blend.

**Comment by flar** [comment]
There is currently no way to inspect the contents of a PictureLayer. The associated Picture/SkPicture objects are opaque and the best we can tell is the "number of operations", but we can't tell what those ops are. We'd have to annotate the objects heavily on our end to be able to detect something that could be collapsed.

With regard to collapsing Opacity+Opacity, that might be easier, but how often does this happen?

**Comment by ds84182** [comment]
@flar:

Not sure if Opacity+Opacity is frequent enough to have a specific optimization, maybe it should be documented as a potential performance pitfall instead.

For Opacity+Picture, as a way to sidestep being unable to inspect the contents of a PictureLayer, would it be possible to add an ImageLayer just for drawing trivial images? Then when drawing through the RasterCache, the incoming opacity paint can be combined directly with the image's paint (which is known to be trivial), optimizing it down to a single call to drawImage.

@dnfield:

A cap on the raster cache would be a good first step, as long as we can get some logging information when it happens. I'm going to also look through at all the places where we use FadeTransition or AnimatedOpacity to see if we can simplify some of our commonly used UI widgets.

**Comment by flar** [comment]
The problem with an "ImageRenderLayer" is that at the time an image is expressed to the scene, we have no idea if it will be in isolation or if it will be a part of a hundred image thumbnails being shown. If there are a lot of images to show, then collecting them into a Picture is the fastest way to render them all. If it is a one-off, then having an explicit rendering layer will be similar in price.

If we can switch to a new Picture format that is inspectable then we could have the best of both worlds.

**Comment by ds84182** [comment]
Posting my findings from Thursday:

Removing usages of FadeTransition from our app, instead using custom Decorations & CustomPainters to implement our fade-in animations, reduced our peak cold-start memory usage by 100 MB. However, this required a ton of manual intervention, as well as looking at raster cache and offscreen layer usage.

Additionally, I think this change can apply to other layers that are trivially applicable to images and other trivial-to-paint operations. For example ClipRectLayer, which can apply directly to images and canvas ops like drawPaint/drawRect, etc. Of course, OpacityLayer should be highest priority since it's the biggest footgun in this area.
