### ISSUE TITLE
Support mice properly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#757]
Right now we support mice by pretending they're a touch while down, with a unique touch ID for each click/drag.

We should probably move to a model more like:
- [x] touches pretend to have button 1 set.
- [x] gesture recognition pays attention to buttons.
- [ ] we have a separate set of identifiers for touches/mice in general, and touches/mice while down. We use the latter to do gesture recognition. (Gesture recognition is explicitly only about "down" moves.)

**Comment by goderbauer** [comment]
@gspencergoog Is this something you're working on?

**Comment by gspencergoog** [comment]
Not yet, but I'll probably end up touching on this while working on mouse support.

**Comment by mdebbar** [comment]
The way we do this for the web today is:
### Touch
The browser includes an identifier with each touch event (it tracks each finger with a separate identifier). We pass that identifier to Flutter as a pointer ID.

### Mouse
Modern browsers provide support for the newer [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) which include a `pointerId` with each event. So we forward that to Flutter.

Some browser though don't support pointer events, and we fallback to using touch events (if available) or mouse events. For touch events, we do what I described above. For mouse events, the browser doesn't include any kind of ID, so we use a hardcoded ID (`-1` I believe) because we assume there's only one mouse and there's no need to change the ID.
<hr>
The hardcoded ID for mouse events is different from what Flutter does, but it's working fine for us at the moment. Do you think we need to revisit and start using a new ID for each click/gesture?


cc @gspencergoog @Hixie

**Comment by stuartmorgan** [comment]
Is there any work left here after the recent changes?

**Comment by gspencergoog** [comment]
We think this is done.
