### ISSUE TITLE
[camera] update cookbook and docs

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#75723]
update the https://flutter.dev/docs/cookbook/plugins/picture-using-camera#6-display-the-picture-with-an-image-widget
to match latest camera API changes, in particular i found `takePicture` call that now doesn't have a path argument

also, now i don't understand what is the file i get when i call `takePicture`. is it temporary (which is the case i suppose) or is it saved in app documents directory? document this as well
https://github.com/flutter/plugins/blob/d0b7109f6b00a0eda03506fed2c74cc123ffc6f3/packages/camera/camera/lib/src/camera_controller.dart#L322-L326

**Comment by danielroek** [comment]
The XFile is an abstract layer around the file, this is done mainly to support web in the future, because that implementation won't be saved to the device first. The iOS and Android implementations both save the image in a cache directory. So if you want to save it to the application directory you'd have to move it yourself.

I'm not sure how the cookbook needs to be updated.

**Comment by nt4f04uNd** [comment]
as i mentioned takePicture doesn't have path argument anymore. i'm not sure if there's anything that has changed in the plugin that requires changes to the cookbook

![image](https://user-images.githubusercontent.com/39104740/107524414-cd7ab600-6bc6-11eb-88cc-876e3533221f.png)

**Comment by nt4f04uNd** [comment]
oh just looked at the chagnes history, turns out that there were never such argument. i don't even know where this code comes from

**Comment by bharat-biradar** [comment]
I am having same the same doubt. Even the [example](https://github.com/flutter/plugins/blob/d0b7109f6b00a0eda03506fed2c74cc123ffc6f3/packages/camera/camera/example/lib/main.dart#L602) given in repo doesn't have any argument being passed in the takePicture(). Please verify.

**Comment by bharat-biradar** [comment]
Hi @pedromassangocode the example in the [cookbook](https://flutter.dev/docs/cookbook/plugins/picture-using-camera#5-take-a-picture-with-the-cameracontroller) should not have a argument passed to takePicture() method. Because the takePicture() function in [camera_controller.dart](https://github.com/flutter/plugins/blob/9d00dd22b868f4ed98de8170f25e2a508a44b93a/packages/camera/camera/lib/src/camera_controller.dart#L331) doesn't have any arguments. Even in [MethodChannelCamera class](https://github.com/flutter/plugins/blob/9d00dd22b868f4ed98de8170f25e2a508a44b93a/packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart#L200) from where the method channel is being invoked we see that only camera id is being passed and we are receiving the path for the file created in the [native](https://github.com/flutter/plugins/blob/9d00dd22b868f4ed98de8170f25e2a508a44b93a/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java#L401). If you agree that it needs to be changed, then shall I open a pr making the required changes to [picture-using-camera.md](https://github.com/flutter/website/blob/master/src/docs/cookbook/plugins/picture-using-camera.md).

**Comment by nt4f04uNd** [comment]
@bharat-biradar feel free to open PR. if you will, please add some comments regarding 
what XFile is (https://github.com/flutter/flutter/issues/75723#issuecomment-776746407) as well
