### ISSUE TITLE
FitBit sdk plugin for flutter application

### ISSUE THREAD

**Issue by elogic2square** [flutter/flutter#75840]
When can i expect fitbit sdk plugin for flutter mobile android application

**Comment by iapicca** [comment]
@elogic2square 
I feel that is not much a future proof investment of time
since[ google bought fitbit](https://blog.google/products/devices-services/fitbit-acquisition/)
isn't impossible to imagine that soon fitbit products might sport  [wearOS](https://wearos.google.com/#hands-free-help)
which is [already within reach of flutter](https://medium.com/flutter-community/flutter-building-wearos-app-fedf0f06d1b4)

**Comment by TahaTesser** [comment]
Hi @iapicca 
@iapicca mentioned it's not feasible to support entirely new and smaller platform like Fitbit OS
WearOS is better in this regards
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
