### ISSUE TITLE
After upgrading Dart SDK, flutter breaks for beta channel in windows

### ISSUE THREAD

**Issue by arnabchat90** [flutter/flutter#75872]
## Steps to Reproduce

1. upgraded flutter with flutter upgrade
2. upgrade process fails with following issue on windows.

## Logs

<details>
<summary>Logs</summary>

```
flutter doctor
Building flutter tool...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
Because flutter_tools depends on charcode 1.2.0 which doesn't match any versions, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Error: 'pub upgrade' still failing after 10 tries.
Can't load Kernel binary: Invalid kernel binary format version.

```

```
```

</details>

**Comment by arnabchat90** [comment]
Also tried - 

To switch back to stable version - Not possible same error.

Deleted the flutter folder and then installed again.

Stable channel works well. Upgrading to beta introduces the same issue.

**Comment by dnfield** [comment]
Are you perhaps using a pub mirror that is not up to date? pub.dev/packages/charcode shows 1.2.0 as published...

This is an unfortunate cycle though. What's happening is the tool fails to rebuild because of a pub failure, and then it looks like it might be trying to load an older snapshot somehow that isn't compatible with the new revision of Dart.

@jonahwilliams do we have a bug for this? I'm not 100% sure I understand how to reproduce it - like, what kernel binary is it actually trying to load and failing...

**Comment by TahaTesser** [comment]
Hi @arnabchat90 
Unable to reproduce this on Windows 10 when `beta` or any other channel (multi SDK setup)
Can you please provide the details asked above?
Thank you

**Comment by Ruzo** [comment]
Also had the same kind of error but it was after adding some packages with Pubsect Assist. I fix it by either upgrading to null-safety version or downgrading to latest stable version of packages. It was in a new Flutter beta project.

This error:
-------------------------------------
[rocket_guide] flutter pub get
Running "flutter pub get" in rocket_guide...                    
Because google_fonts 1.1.2 depends on http ^0.12.0+2 and no versions of google_fonts match >1.1.2 <2.0.0, google_fonts ^1.1.2 requires http ^0.12.0+2.

So, because rocket_guide depends on both google_fonts ^1.1.2 and http ^0.13.0, version solving failed.
pub get failed (1; So, because rocket_guide depends on both google_fonts ^1.1.2 and http ^0.13.0, version solving failed.)
exit code 1
-------------------------------------
was the last one where I had to change http from the null-safety (preview) version ^0.13.0 to the latest ^0.12.2.
I had a previous error pertaining to freezed_annotation and I fixed it by upgrading to the null-safety version. The message always seems pretty confusing to me.

I know it's not the same as upgrading flutter but these are new errors and might be related, IMHO.

**Comment by arnabchat90** [comment]
the issue is still there, and its because somehow after switching to beta channel, flutter is unable to get preview packages, as charcode 1.2.0 and all other preview packages are in dependencies for flutter_tools it fails - 
![image](https://user-images.githubusercontent.com/15185453/109556307-a98efe00-7afc-11eb-9612-9d00c45092a4.png)

I have tried down grading to stable versions, and the error goes away, but ofcourse due to a huge dependency chain its impossible that it works that way.

Any leads on why preview packages might not be pulled?

**Comment by arnabchat90** [comment]
i could finally fix this.
needed to clear the pub cache -  %LOCALAPPDATA%\Pub\Cache go to this location in windows, and remove everything. Try flutter upgrade again.
