### ISSUE TITLE
Flutter doctor can't find Android Studio or plugins

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#75918]
## Steps to Reproduce

1. Install Android Studio using the standard method, and the Flutter and Dart plugins. 
2. Download the flutter SDK and extract it somewhere, add it to PATH.
3. Run `flutter doctor`.

It says Android Studio is not installed, even though it definitely is and I can run it and I installed it to the default location. I found [a stackoverflow question with the same problem](https://stackoverflow.com/q/59647791/265521), they suggest running this command:

    flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"

Which enables `flutter doctor` to find Android Studio` but not the Flutter or Dart plugins (even though they are installed). One answer suggested that resintalling the plugins fixes it but that did not work for me.

## Logs

<details>
<summary>Logs</summary>

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.18363.1316], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK 30.0.2)
    X Android license status unknown.
[!] Android Studio (not installed)
[√] VS Code (version 1.52.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

```
>flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"
Setting "android-studio-dir" value to "C:\Program Files\Android\Android Studio".

>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.18363.1316], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK 30.0.2)
[√] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Timmmm 
Try [this](https://github.com/flutter/flutter/issues/68429#issuecomment-740430602) solution and see if it works.
Also, the AS or plugins message you see in `flutter doctor` isn't an issue. They are just warnings. You should be able to use them as usual during developement.
This has been fixed in master but may not have reached stable. You may switch to latest master and check again.
Closing this, as this is already [fixed](https://github.com/flutter/flutter/issues/67986). If you disagree, write in comments and I'll reopen it.
