### ISSUE TITLE
[Suggestion/Request] Git Cleanup

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#75989]
This isn't a common issue or bug report like the other ones opened here, but a suggestion as a flutter user:

**This issues list need a cleanup.**

We have some from the end of 2015, beggining of 2016 - 5 years ago - and as users we don't know if or have a expectation of them being solved. Some of them might be already fixed on the new updates (or don't), some may contain great ideas for new features that aren't on the code till today.

The list is already passing 8k opened issues - and growing - and at least for me, i can't easily see what the flutter team is fixing/creating. I know that there is the milestones for the month releases but they don't come close to covering everything (and this is normal). The team's custommer service speed for reading the problems and labeling them is awesome, but the core point is acting on them, and like i said there are labeled issues from 2015 that don't seem to be working on.

Like i started saying, this isn't a crticism to your job guys, you and what you are doing here is amazing! It's just a wish as an user to know what will be done, and that if our requests/problems will be solved.

**Comment by pedromassangocode** [comment]
Hi @Macacoazul01 

> It's just a wish as an user to know what will be done, and that if our requests/problems will be solved.

You can see issues being worked in the milestones as you said: https://github.com/flutter/flutter/projects. If you want the "big picture"about what is being worked on you can check the Flutter Roadmap: https://github.com/flutter/flutter/wiki/Roadmap.

> Some of them might be already fixed on the new updates (or don't), some may contain great ideas for new features that aren't on the code till today.

The triage team is checking old issues to verify if they are still valid issues (or already-implemented feature proposal) and acting on them from time to time to make sure old issues don't last for ever. I know Flutter has lots of issues so it may take some time to check every issues.

> and as users we don't know if or have a expectation of them being solved.

The Flutter team has its own priority and you can check this by the `P` labels that are applied on issues and PRs. I understand that those priorities does not mean that they will be worked on by a Flutter member as they may not be aligned with the priorities of the Flutter team lead. 

![Screen Shot 2021-02-15 at 12 42 07](https://user-images.githubusercontent.com/67424416/107942212-39746a00-6f8b-11eb-8ce0-886e1eb2fa74.png)

Flutter leave issues open because it is a open source project so even if a team member does not work on a specific issue, anyone interested on that issue can contribute by issues that are blockers for his project.

**Comment by Hixie** [comment]
FWIW I literally just landed patches for two 3-digit bugs, for example https://github.com/flutter/flutter/pull/74798 fixed #505, and https://github.com/flutter/flutter/pull/74972 fixed #125. I wouldn't have done so if we'd just closed those bugs. :-)

Anyway, you're welcome to participate in triage and fixing and so forth. Check out our contributing docs, join our discord (the link in those contributing docs). We would love to get more help in going through old issues!

**Comment by Macacoazul01** [comment]
I'm wasn't saying to close old issues randomly, just asking if the team was looking to old issues that were already solved. But as @pedromassangocode said, they are.

**Comment by Hixie** [comment]
Yup, we definitely do. If you do notice any that should be closed though, don't hesitate to let us know in the #hackers-triage  channel on our Discord and we will close it!
