### ISSUE TITLE
Make Observatory opt-in for debugging, disabled by default for deployed apps

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#76]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:29 GMT_
_Originally opened as https://github.com/flutter/engine/issues/38_

----

_From @Hixie on June 30, 2015 17:2_

_Copied from original issue: domokit/mojo#284_

**Comment by sethladd** [comment]
Is this issue about not shipping the Observatory polymer webapp in our copy of the VM, or about disabling profiling in a production build of a Flutter app?

**Comment by Hixie** [comment]
This bug is about making it possible to connect a debugger to any random deployed app (to get some of the "easy view source" magic that made the Web successful), but requiring an explicit user opt-in to do this (so that random other apps can't just connect to my bank's debugging port and pull out my bank details).

**Comment by eseidelGoogle** [comment]
This is done.  We now have dart_product_mode build flag and exposed to the user as --debug, --profile and --release.
