### ISSUE TITLE
[file_selector_web] update documentation

### ISSUE THREAD

**Issue by pedromassangocode** [flutter/flutter#76067]
I was following the installation guide for [file_selector_web](https://pub.dev/packages/file_selector_web) plugin and I think it needs tome update.

The docs says to add those two dependencies but they don't work:
```
file_picker: ^0.7.0
file_picker_web: ^0.7.0
```

Instead they work with:
```
file_selector: ^0.7.0+2
file_selector_web: ^0.7.0+1
```

Cc @ditman

**Comment by bharat-biradar** [comment]
Can I update the documentation and a open a quick pr?

**Comment by pedromassangocode** [comment]
Hi @bharat-biradar 
Feel free to do so!

**Comment by ditman** [comment]
`file_picker: ^0.7.0` should be the same as `file_picker: ^0.7.0+2`, it's just a patch version.

@pedromassango how did this happen? Did you have an old pubspec, or maybe a stale dependency cache?

As far as I know, pub should be resolving to the latest "patch" of any specified version, when using `^`.

**Comment by pedromassango** [comment]
> `file_picker: ^0.7.0` should be the same as `file_picker: ^0.7.0+2`, it's just a patch version.

The issue is about the docs mentioning the wrong package, AFAIK the [file_picker](https://pub.dev/packages/file_picker) that the docs mention is not from Flutter and that is probably why it does not work.

> @pedromassango how did this happen?

I've followed the docs and then copy/pasted the sample code but it was not working.


> Did you have an old pubspec.lock, or maybe a stale dependency cache?

I'm not sure about that, but I can say that this was the first time using this package on the project.

**Comment by ditman** [comment]
> The issue is about the docs mentioning the wrong package

# OUCH

Totally didn't notice it was the wrong package, just looked at the versions! You're right, thanks for the fix!
