### ISSUE TITLE
Ability to hide/remove all snack bars in the scaffold's queue

### ISSUE THREAD

**Issue by ianspryn** [flutter/flutter#76081]
## Use case

I have a complicated form a user can fill out. They have the option of adding and removing rows of text fields. Every time a user removes a text field row, a snackbar appears with an "UNDO" action. If the user removes multiple rows, then a queue of snackbars is formed for each removed row.

Let's assume the user removes several rows. Right after doing so, they tap "save," which changes the screen to a friendly read-only format and sends the form data to a database. Right now, a snackbar is still visible with an "UNDO" option. Should the user tap this, the page would try to re-insert the row and possibly crash the UI if this scenario wasn't handled properly. Even if the UI did not crash, the user might think they successfully undid their deletion action, but in reality, the database still contains the form in its original state.

While you can say something like `scaffoldKey.currentState.hideCurrentSnackBar()` whenever there user saves the form, this only removes the currently visible snackbar if there is one, and you have no way of knowing if another snackbar is still in the queue.

## Proposal

I have 2 possibilities in mind:

### 1:
Create a getter `[ScaffoldState.snackBars]` for the private variable `_snackBars` so that developers can do something like:

```
while (scaffoldKey.currentState.snackBars.isNotEmpty) {
   scaffoldKey.currentState.hideCurrentSnackBar();
}
```

### 2:
Create two new methods that empties the queue of snackbars.

```
void removeAllSnackBars({ SnackBarClosedReason reason = SnackBarClosedReason.remove }) { ... }

void hideAllSnackBars({ SnackBarClosedReason reason = SnackBarClosedReason.hide }) { ... }
```

### Final thoughts

The first proposal offers more control to the developer if they only want to pop a certain number of times or check some condition each round, but it may not be as obvious to developers they can do this. The second approach is easier for a developer to use, but offers less control. Perhaps offer both?

**Comment by HansMuller** [comment]
cc @Piinks

**Comment by chinmoy12c** [comment]
Hey @Piinks, I've submitted a PR implementing the first case of the proposal. Let me know if the second case also needs to be implemented :smile: . Also, should this be part of a separate PR?

**Comment by Piinks** [comment]
Hey @chinmoy12c thanks for the PR! I think the first case proposed here may have some issues, and the seconds seems ok, but we may need to tweak in order to implement properly.

I don't think exposing `_snackbars` is a great idea. It leaves open the opportunity to break things in a lot of wild ways I probably can't fully imagine. :) Plus, I don't think the proposed use of it would work right..
> ```
> while (scaffoldKey.currentState.snackBars.isNotEmpty) {
>   scaffoldKey.currentState.hideCurrentSnackBar();
>}
>```

`hideCurrentSnackBar` is meant for the current SnackBar that is already on screen. So I don't know that this would work since SnackBars in a queue are not on screen yet. Only one is on screen at a given time. `removeSnackBar` might, but then I wonder, what is the SnackBarClosedReason in this case? When `removeCurrentSnackBar` is called, it completes (ScaffoldFeatureController._completer) with that reason. Should all the SnackBars in the queue be completed? If their completion triggers something else, should that still happen?

My initial impression is that we should provide a separate, single method that clears the queue, and if one is showing currently, triggers a graceful animation out. I am thinking we might want to handle the one that is visible last, because IIRC it is the animation out that triggers the next SnackBar in the queue to show up.

What do you think?

**Comment by chinmoy12c** [comment]
> Hey @chinmoy12c thanks for the PR! I think the first case proposed here may have some issues, and the seconds seems ok, but we may need to tweak in order to implement properly.
> 
> I don't think exposing `_snackbars` is a great idea. It leaves open the opportunity to break things in a lot of wild ways I probably can't fully imagine. :) Plus, I don't think the proposed use of it would work right..
> 
> > ```
> > while (scaffoldKey.currentState.snackBars.isNotEmpty) {
> >   scaffoldKey.currentState.hideCurrentSnackBar();
> > }
> > ```
> 
> `hideCurrentSnackBar` is meant for the current SnackBar that is already on screen. So I don't know that this would work since SnackBars in a queue are not on screen yet. Only one is on screen at a given time. `removeSnackBar` might, but then I wonder, what is the SnackBarClosedReason in this case? When `removeCurrentSnackBar` is called, it completes (ScaffoldFeatureController._completer) with that reason. Should all the SnackBars in the queue be completed? If their completion triggers something else, should that still happen?
> 
> My initial impression is that we should provide a separate, single method that clears the queue, and if one is showing currently, triggers a graceful animation out. I am thinking we might want to handle the one that is visible last, because IIRC it is the animation out that triggers the next SnackBar in the queue to show up.
> 
> What do you think?

Yes, now that I think about it, you're completely right. The idea of cleaning the queue seems rather clean. I'll implement this tomorrow, thanks for this :+1: :smiley:
