### ISSUE TITLE
I'm trying to display polylines as per Google road map on my flutter app using authorized google key which is working fine in android app. But In flutter app it's showing unauthorised key.

### ISSUE THREAD

**Issue by bhagyashrieducloud** [flutter/flutter#76115]
I'm using google_maps_flutter: ^0.5.11+1 and flutter_polyline_points: ^0.1.0 plugin.

`When i'm debugging internal libraries i'm getting following errors in response -> { "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 2405:204:969c:11f6::24b9:a8a4, with empty referer", "routes" : [], "status" : "REQUEST_DENIED" }
`
My code is in this file->
[Google_Map_Page.txt](https://github.com/flutter/flutter/files/5988518/Google_Map_Page.txt)

**Comment by darshankawar** [comment]
@bhagyashrieducloud 
I believe this isn't an issue with the Flutter plugins but with the type of api key you are using. You may need to use server key instead of Android api key.  

Please see https://flutter.dev/community for resources, you may also get some help if you post it on Stack Overflow / google around the issue and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Closing, as this isn't an issue with Flutter framework or plugins. If you disagree, write in comments and I'll reopen it.

**Comment by bhagyashrieducloud** [comment]
@darshankawar 
Than you so much! 
As you say i used server key in and poliylines are working fine now.
