### ISSUE TITLE
Flutter iOS run error : Could not parse callback cache, aborting restore

### ISSUE THREAD

**Issue by jpmehedi** [flutter/flutter#76199]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@jpmehedi 
Your issue doesn't have any details on the problem you are facing. Just mentioning the issue in the title won't help.
Please provide all the details of the issue mentioned in the [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) so that we can properly address it.
