### ISSUE TITLE
shared_preferences on iOS stores data after uinstalling the app 

### ISSUE THREAD

**Issue by pkhivesara** [flutter/flutter#76340]
## Steps to Reproduce
Uninstalling and reinstalling app on iOS platform does not clear the shared preferences. Is this an expected behavior on iOS?

**Expected results:** Shared preferences should be cleared.

**Actual results:** Existing user data is retained.

**Comment by PassionPenguin** [comment]
`NSUserDefaults` should be deleted after uninstallation

**Comment by darshankawar** [comment]
@pkhivesara 
It is not an expected behavior. The data should persist only across hot restarts.

I tried the official `shared_preferences` repo on latest stable using iOS 14.3 and didn't notice such behavior. The app cleared data upon reinstall.  See below:

1. Ran the app and tapped on button few times:

<img width="346" alt="Screenshot 2021-02-19 at 1 48 51 PM" src="https://user-images.githubusercontent.com/67046386/108477522-537ab900-72b9-11eb-9aee-3d34d845acfa.png">

2. Uninstalled and ran it again which showed reset data:

<img width="350" alt="Screenshot 2021-02-19 at 1 48 59 PM" src="https://user-images.githubusercontent.com/67046386/108477575-668d8900-72b9-11eb-8f16-c69015754d07.png">


Can you elaborate by providing `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)` that shows the issue ?

**Comment by nt4f04uNd** [comment]
do you test this on simulator? this might be a simulator bug https://stackoverflow.com/q/24985825/9710294

**Comment by pkhivesara** [comment]
Thanks for your responses everyone!
@darshankawar 
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/xxx/flutter/flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

⢿Unable to find any JVMs matching version "1.8".                                                                                                                                                                                                                        [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/xxx/Library/Android/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/xxx/Library/Android/Android/Contents
    • Try updating or re-installing Android Studio.

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 4 categories.

```
For some reason, doctor keeps complaining for the dart plugin, even though I can obviously compile and run all kinds of Flutter apps.

I cant provide a sample code however. This is happening on our internal project. Tested on iPhone 7S running iOS 14.3
How could I debug this?

@nt4f04uNd No, on a physical device.

**Comment by darshankawar** [comment]
@pkhivesara 


> For some reason, doctor keeps complaining for the dart plugin, even though I can obviously compile and run all kinds of Flutter apps.

Those are just warnings and already fixed in master and dev, but may not be in stable yet. But that shouldn't be an issue. You can use the plugins as usual.



> I cant provide a sample code however. This is happening on our internal project. Tested on iPhone 7S running iOS 14.3
> How could I debug this?

Without a reproducible use case, it'll be tough to identify the root-cause. If possible, please create a sample repo that shows the issue, which we can clone and verify.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
