### ISSUE TITLE
"flutter test --machine" has started emitting "observatoryUri":"null" for non-debug test runs

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#76533]
Running `flutter test` with `--machine` has started emitting a startedProcess` event that has the string `"null"` as its `observatoryUri`:

```
[{"event":"test.startedProcess","params":{"observatoryUri":"null"}}]
```

VS Code (and perhaps IntelliJ) uses this event to wire up a debugger, but `"null"` is not a valid VM service URI. On current stable, this event is not emitted at all when running without debugging (`--start-paused`). 

```
danny@Dannys-MBP flutter_hello_world % flutter test --machine test/broken_test.dart 
{"protocolVersion":"0.1.1","runnerVersion":null,"pid":9256,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/test/broken_test.dart"},"type":"suite","time":1}
{"test":{"id":1,"name":"loading /Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/test/broken_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":2}
{"count":1,"type":"allSuites","time":5}

[{"event":"test.startedProcess","params":{"observatoryUri":"null"}}]
```

If the event does need to be raised and there's no VM Service, I think this should be a real `null` and not a string. I'll see if I can figure out when this started.

@devoncarew FYI - unsure if this will affect IntelliJ (in VS Code, it results in errors, although I don't think it actually stops anything from working).

**Comment by DanTup** [comment]
@jiahaog bisect led me to #74176 although I couldn't tell from the PR why the event would have started arriving now. It could be easily converted to a real `null` with a `?` in the call to `toString()` though the original behaviour was that the event didn't arrive at all, so preserving that might be safest for clients.

**Comment by jiahaog** [comment]
Yeah, I thought I was "fixing" it in #74176 because `handleStartedDevice` seems to imply that it should be called unconditionally, even when the VM service url is null. 

https://github.com/flutter/flutter/blob/ff8f4717f798e890cf2fb7abc61fd04ac2b4e21f/packages/flutter_tools/lib/src/test/flutter_platform.dart#L417-L422

Perhaps to match the method semantics we should do a `observatoryUri?.toString()` like you mentioned when we serialize the URI? 

Also, are we expecting a crash or something because of this for the VSCode plugin? I'm not sure if I'm testing it correctly, but I'm clicking on the "run" button beside the test main and it works fine.

**Comment by devoncarew** [comment]
cc @stevemessick, @helin24 for the question about whether IntelliJ's use of `flutter test` / `flutter test --machine` would have problems with this change

**Comment by DanTup** [comment]
> Also, are we expecting a crash or something because of this for the VSCode plugin? I'm not sure if I'm testing it correctly, but I'm clicking on the "run" button beside the test main and it works fine.

In the few cases I tested, it didn't actually break anything - it just resulted in unhandled errors being written to the console (it tries to connect to `"nullws"` as a VM service becaue we appended `"ws"`).

> Perhaps to match the method semantics we should do a observatoryUri?.toString() like you mentioned when we serialize the URI?

I'd be ok with that. It'll still need a tweak in Dart-Code but since nothing is _broken_ it's not critical. I don't know if the same is true for IntelliJ though - @stevemessick / @helin24 may be able to confirm.

**Comment by jiahaog** [comment]
Thanks! I tested it locally and it doesn't seem to have any issues as well with the IntelliJ plugin. I'll send out #76579 tentatively then.

**Comment by helin24** [comment]
@jiahaog I think this is okay for us since we usually run `flutter test --machine --start-paused test/test_file.dart`, and it looks like the output from that combination of args is unchanged. We run `flutter test --machine test/test_file.dart` for the case of running all of the tests in a directory, but in that case, we don't allow debugging and we don't connect to the observatory.

**Comment by jiahaog** [comment]
Do let me know if there are any other issues, thanks!
