### ISSUE TITLE
Running release Windows app from console doesn't stay attached

### ISSUE THREAD

**Issue by Merrit** [flutter/flutter#77002]
## Steps to Reproduce

<details>
  <summary>Logs</summary>

`flutter analyze`

```
PS C:\Users\Merritt\Dev\myapp> flutter analyze
Analyzing myapp...
No issues found! (ran in 4.0s)
PS C:\Users\Merritt\Dev\myapp>
```

```
PS C:\Users\Merritt\Dev\myapp> flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-4.0.pre at C:\tools\flutter
    • Framework revision f8cd24de95 (13 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31019.35
    • Windows 10 SDK version 10.0.18362.0

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Merritt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.804]

• No issues found!
PS C:\Users\Merritt\Dev\myapp>
```

</details>

When running a Flutter for Windows Desktop app from cmd the running app does not stay attached to the console and output print statements (This is exactly what it _does_ do in Linux).

## Working in Linux:

```dart
void main() {
  print('Hello Linux!');
  runApp(MyApp());
}
```

1. `flutter build linux`
2. `myapp/build/linux/release/bundle/myapp`

Output as expected:

`Hello Linux!`

Terminal session stays attached to the running program to output further messages. :thumbsup:

## Not working in Windows:

```dart
void main() {
  print('Hello Windows!');
  runApp(MyApp());
}
```

1. `flutter build windows`
2. `.\build\windows\runner\Release\myapp.exe`

Expected output:

`Hello Windows`

Actual output:

None, and console does not attach to running program and immediately goes to a new cmd line awaiting input.

I have been trying to debug an issue that only appears in release and not debug build, and doing so without access to a debugger or being able to follow print statements has been very troublesome. I do expect it should work the same way as it does on Linux.

**Comment by stuartmorgan** [comment]
> When running a Flutter for Windows Desktop app from cmd the running app does not stay attached to the console and output print statements

This is just how non-console apps (i.e., GUI rather than command-line, which is a project-level switch when building Win32 apps) behave on Windows. There is code in the default runner created by `flutter create` that [attaches to the parent console if the OS provides it](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/windows.tmpl/runner/main.cpp.tmpl#L11-L15), but when you launch a GUI app from cmd, the OS simply does not provide it.

> (This is exactly what it _does_ do in Linux).

Linux doesn't have this concept of a command line application and a GUI application being fundamentally different things.

> Expected output:
> 
> `Hello Windows`

We don't control how the OS does console inheritance. I understand why this is the behavior you want in this scenario, but it is not actually the expected behavior for launching a Windows GUI application from `cmd`.

> I have been trying to debug an issue that only appears in release and not debug build, and doing so without access to a debugger or being able to follow print statements has been very troublesome.

I would recommend modifying the code I linked above in your runner to make the console unconditionally for debugging purposes. It'll be a separate window, not inline, but you'll have access to it.

(/cc @cbracken FYI)

**Comment by Merrit** [comment]
> I understand why this is the behavior you want in this scenario, but it is not actually the expected behavior for launching a Windows GUI application from cmd.

I see, real shame it can't work that way. Thank you for clearing that up!

> I would recommend modifying the code I linked above in your runner to make the console unconditionally for debugging purposes. It'll be a separate window, not inline, but you'll have access to it.

Moving `CreateAndAttachConsole();` directly out of the if statement and a few other attempted tweaks don't seem to accomplish this, but I am very much not familiar with C++ & win32 so I will play around with it. (or try to get a logger that logs to a file going).

Thanks very much for your insight - much appreciated!
