### ISSUE TITLE
Flutter 2.0 Raised button color issues.

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#77222]
Flutter 2.0

Our project has lots of custom colors on buttons.

Before it was as simple as using ```Colors.red``` for example.

Now we're not sure how to customize this as it's using a non-standard way to enter colors into widgets.

```
ElevatedButton(
          onPressed: () {
            if (_formKey.currentState.validate()) {
              widget.onName(_workoutNameController.text);
            }
          },
          style: ButtonStyle(
            backgroundColor: <---> None of our style guide colors work, errors.
          ),
          child: Text(
            lang('Save'),
            style: TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.w700,
            ),
          ),
        )
```

**Comment by Zersya** [comment]
Try to use

```
ElevatedButton(
  style: ButtonStyle(
    backgroundColor: MaterialStateProperty.all<Color>(Colors.green),
  ),
)
```

https://api.flutter.dev/flutter/material/ButtonStyle-class.html

**Comment by pedromassangocode** [comment]
Hi @ollydixon 
What do you mean by `None of our style guide colors work, errors.`?

I may be wrong but `backgroundColor` does not receives a Color type anymore and you are probably trying to pass one there.

You can read more about this at https://docs.google.com/document/d/10Fbn59hiHkppqJ6y_1Rjwl7klN-OvJXQU3SFEqicpME/edit#heading=h.nxddek4w5dli.

Please elaborate on this issue and provide a reproducible test case and your `flutter doctor -v`.
Thank you

**Comment by ollydixon** [comment]
@pedromassango it's a straightforward issue. In the new flutter 2.0, instead of using deprecation properties (which they are supposed to do), people have overwritten properties, causing 10,000s of libraries to break.

The main issue here is that instead of using Material colors, which is what everything else uses, they are using a pallet on a simple background color, which is inconsistent with other components and the way it works. For us with complex styled apps it doesn't work using the default material basises.

I feel sorry for people just getting into Flutter for the first time; what a mess.

**Comment by pedromassangocode** [comment]
Hi @ollydixon 
Can you please answer my questions in my previous comment? For what I know, the Material button styles where changed (see the link in my previous comment) and this was expected.

Flutter 2.0 may be breaking for people who didn't migrate his project from the recent previous versions so if that is the case, may you will have to migrate now or use the previous stable version while you migrate your codebase.

Unless this is not the case, please describe what you mean by `backgroundColor: <---> None of our style guide colors work, errors.` and how can I reproduce the issue.
Thank you

**Comment by ollydixon** [comment]
@pedromassangocode I have given you a code example.

**Comment by pedromassangocode** [comment]
> @pedromassangocode I have given you a code example. Please read it.

Sorry but as I said it is not clear what is the issue to me. 


> Now we're not sure how to customize this as it's using a non-standard way to enter colors into widgets.

As for this I have given the design doc for the changes made (you can look at the docs as well) in my comments above.

For a simple example, here is what you are (eventually) trying to acheive:

 ```dart
   ElevatedButton(
      onPressed: () {
      },
      style: ButtonStyle(
        backgroundColor: MaterialStateProperty.resolveWith((states) => Colors.red)
      ),
      child: Text('',
        style: TextStyle(
          color: Colors.white,
          fontSize: 18,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
```

It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please provide the steps to reproduce the issue alog with the actual vs expected results.
Thank you

**Comment by ollydixon** [comment]
@pedromassangocode I can't believe you closed this. ```MaterialStateProperty.resolveWith((states) => Colors.red)``` is really the soltuion? That is really bad. When all the other Widgets in Flutter use Color? That is poor. What about juniors writing Flutter now, they need to type MaterialStateProperty.resolveWith((states) => [some color]) each time?..

@eseidelGoogle @eseidel I want you to be aware of this. And how you are pushing developers away.

**Comment by inceptusp** [comment]
I agree with @ollydixon... It has become overly complicated... I've just had to change 66 buttons that used the old `backgroundColor:  [someColor]` approach on a project because it was not working anymore... @pedromassango said 

> Flutter 2.0 may be breaking for people who didn't migrate his project from the recent previous versions so if that is the case, may you will have to migrate now or use the previous stable version while you migrate your codebase.

The stable exactly previous version has not a deprecation notice about this change neither does flutter 2.0...

**Comment by ollydixon** [comment]
@inceptusp imagine that but 40+ flutter projects I have to manage.

**Comment by HansMuller** [comment]
To create an ElevatedButton with a custom background color you can do what [Pedro suggested](https://github.com/flutter/flutter/issues/77222#issuecomment-790653267) or use ElevatedButton's styleOf convenience method to create a ButtonStyle that's based on an override of the color scheme's primary color:

```dart
ElevatedButton(
  style: ElevatedButton.styleFrom(
    primary: Colors.red, // background
  ),
  onPressed: () { },
  child: Text('TextButton with custom foreground'),
)
```

The styleOf() expression creates a ButtonStyle with a `MaterialState<Color>` valued background property that returns red, for all states. The fact that the default for an ElevatedButton's background color is the primary ColorScheme color is documented by the [defaultStyleOf method](https://api.flutter.dev/flutter/material/ElevatedButton/defaultStyleOf.html). 

Most simple button customizations - for TextButton, ElevatedButton, OutlinedButton - can be made without creating `MaterialState<Color>` values, by using the Button's styleOf method.  It's true that this approach, using ButtonStyle instead of specialized constructor parameters and `MaterialState<Color>` instead of simple color values

There's a migration guide here:  flutter.dev/go/material-button-migration-guide. The rationale for all of this change is flutter.dev/go/material-button-system-updates. 

We are working on a set of examples that will become part of the API doc for each button class. The examples should clarify how to make simple customizations of this kind. For now, hopefully the [migration guide](flutter.dev/go/material-button-migration-guide) will do.

**Comment by ollydixon** [comment]
@HansMuller thank you for the reply and for reopening. But do you not think this is a classic case of overengineering or framework bloat?

**Comment by HansMuller** [comment]
@ollydixon since it's my doing, I'm not likely to agree with you :-) I do agree that we've created a frustrating obstacle for some apps. My experience in porting Google's apps hasn't been too bad, in most cases I was able to just substitute the new button classes for the old ones and in some cases I had to replace some constructor parameters with styleOf() expressions, like https://github.com/flutter/flutter/issues/77222#issuecomment-790769972. 

The new button code is actually more compact than the old and a great deal more flexible.  The added flexibility was added because app developers asked for it. We decided to leave the old button widgets and ButtonTheme behind because adding that flexibility to the old classes was no longer possible.

**Comment by ollydixon** [comment]
@HansMuller thanks. I think in the future it's also important to use deprecated like most of the widgets do. I have to manage many teams and when this happens it ends up costing us tens of thousands of dollars hehe.

**Comment by HansMuller** [comment]
I'm going to leave this issue open until the new API doc includes samples that cover all of the common cases.

**Comment by pedromassangocode** [comment]
> I'm going to leave this issue open until the new API doc includes samples that cover all of the common cases.

This may be a duplicate of https://github.com/flutter/flutter/issues/75642 which has some linked PRs.

**Comment by HansMuller** [comment]
I'm going to close this issue per #75642. Of course we could always use more better examples.
