### ISSUE TITLE
[template] flutter create --template=plugin-ffi

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#77252]
`flutter create --template=plugin` creates a Flutter plugin for working with method channels on iOS and Android. The  Flutter `dart:ffi` [documentation](https://flutter.dev/docs/development/platform-integration/c-interop) takes this template as a basis, and works from there to add C source files to be included in the iOS/Android builds.

Getting these steps right is non-trivial: symbol visibility, building, linking, and code stripping (some issues: #62666, https://github.com/dart-lang/ffi/issues/39, https://github.com/dart-lang/ffi/issues/41, https://github.com/flutter/flutter/issues/33227#issuecomment-611838825). The steps are reproduced in [initial commits package:webcrypto](https://github.com/google/webcrypto.dart) or [this internal repo](https://user.git.corp.google.com/dacoharkes/boringssl_flutter_app/+log).

It would be beneficial to create a new template for working with `dart:ffi`: `flutter create --template=plugin-ffi`.

This template could also skip the method channels, because these are not needed when using `dart:ffi`.

Some internal context: [go/flutter-apps-using-dart-ffi](http://go/flutter-apps-using-dart-ffi).

cc @jonasfj @mit-mit

**Comment by mit-mit** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
@stuartmorgan @cyanglaz

**Comment by stuartmorgan** [comment]
In general [I agree](https://github.com/flutter/flutter/issues/33227#issuecomment-534842170). There are some questions we need to work through:
- Do we want to call this kind of thing a plugin?
- Do we want to use the same `plugin` metadata?
  - If so, we probably need `dartPluginClass` support for mobile before proceeding here
- Alternately, should the concept of platform restriction be elevated into the general pubspec format (per recent discussion with @mit-mit and @jonasfj), since a non-Flutter Dart package can use FFI, and will thus be platform-specific.
- How should we disambiguate this kind of thing (a package that calls code that it builds and packages) from the similar-in-concept-but-wildly-different-in-construction-details package that uses FFI solely to call system libraries?

**Comment by Milerius** [comment]
In general i also agree, but how do you plan to add static library linking (ios/macos) and shared library ?

If the goal is really to support static/shared native wrapper in dart, we need to have a way to link an external library and download it (static and shared)

**Comment by Piero512** [comment]
I've recently been experimenting with this, and although vanilla build scripts are able to just pick up a correctly compiled shared library in the src/main/JniLibs/<ABI> folder (in Android) for each ABI, since the flutter tool isn't aware of it, the APKs generated end up bundled with all the supported architectures

**Comment by maks** [comment]
was this implemented as part of https://github.com/flutter/flutter/pull/96225 ?

**Comment by dcharkes** [comment]
Yes it was.
