### ISSUE TITLE
autoninja complains about goma not being run

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#77267]
When running `autoninja`, we see the error:

`Goma is not running. Use "goma_ctl ensure_start" to start it.`

We do not see this error when using:

`ninja -j50 ...`

instead. This also causes `analyze.sh` to fail locally.

**Comment by flar** [comment]
`which -a ninja` returns only the version in depot_tools. I didn't do anything to install other copies of ninja, it seemed to come out of the blue. Does `autoninja` still work for you?

**Comment by flar** [comment]
The autoninja command gets a bad status back after trying to run `depot_tools/.cipd_bin/gomacc port` which prints out the following when I try to run it manually:

```
E0310 18:36:47.099577 254594496 gomacc_common.cc:154] failed to connect to: /var/folders/t_/[uniq-dir-name]/T/goma_[myusername]/goma.ipc: No such file or directory [2]
E0310 18:36:47.102337 254594496 goma_ipc.cc:71] call failed: Failed to connect to /var/folders/t_/[uniq-dir-name]/T/goma_[myusername]/goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to /var/folders/t_/[uniq-dir-name]/T/goma_[myusername]/goma.ipc, http_return_code: 0
```

**Comment by bdero** [comment]
I ran into this problem back when I was attempting to use the goma distribution different than the one that's fetched by the Chrome package deployer in depot_tools.

The reason was as follows:
* Each goma distribution tracks bits of its own state. So if you launch `compiler_proxy` from one distribution (e.g. the goma distro that ships with Fuchsia) and then attempt to interact with a different one (e.g. the one in `.cipd_tools`), it fails similarly to the above.
* `autoninja` always checks `$(dirname $(which autoninja))/.cipd_bin` first when looking for the goma binaries, and the Chrome package deployer seems to run (and so `.cipd_bin` is regenerated) when I update `depot_tools`.

Check which `compiler_proxy` you launched with `ps aux | grep compiler_proxy`. If it's not `depot_tools/.cipd_bin/compiler_proxy`, then that's a good reason for `depot_tools/.cipd_bin/gomacc port` to not work.

I was able to get both goma distributions to work, but using the `.cipd_bin` one only and eliminating the other goma distribution from my environment seemed like the clear path of least resistance given the `autoninja` behavior I described above.

After resolving all the other problems, I ended up here:
```bash
function path_prepend() {
  if [[ ! "$PATH" =~ (^|:)"${1}"(:|$) ]]; then
    export PATH=${1}:$PATH
  fi
}

function start_goma() {
  export GOMA_DIR=~/projects/depot_tools/.cipd_bin
  path_prepend $GOMA_DIR

  # b/187768413
  export GOMA_SERVER_HOST=rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog
  export GOMA_SERVER_PORT=443

  goma_ctl stop
  killall compiler_proxy  # Just in case

  goma_auth login
  goma_ctl ensure_start
}
```

From here, remote builds are working.

```
./tools/gn --unoptimized --goma --xcode-symlinks --no-lto
autoninja -C ../out/host_debug_unopt -j 400
```

**Comment by bdero** [comment]
This should be solved now with in dev_tools/main when `GOMA_DIR` is properly set.

Update dev_tools: `git remote update; ./update_depot_tools`
