### ISSUE TITLE
[flake] Isolate is already scheduled on mutator in ShellTest.Spawn

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#77304]
Seeing the following failure in Linux Host Engine tests:
Build:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/9217/overview

Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8853647090808312816/+/steps/Host_Tests_for_host_release/0/stdout

```
[ RUN      ] ShellTest.Spawn

GMOCK WARNING:
Uninteresting mock function call - taking default action specified at:
../../flutter/shell/common/shell_unittests.cc:2501:
    Function call: CreateRenderingSurface()
          Returns: 0x7f1680595990
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: IsValid()
          Returns: false
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: OnPlatformViewDestroyed()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.
[ERROR:flutter/shell/common/platform_view.cc(87)] Failed to create platform view rendering surface
```
Crash happens immediately after the above, here:
```
../../third_party/dart/runtime/vm/dart_api_impl.cc: 1537: error: Isolate �� is already scheduled on mutator thread 0x7f16880004c8, failed to schedule from os thread 0x7f1693fff700
```

**Comment by cbracken** [comment]
Potentially related: https://github.com/flutter/flutter/issues/72312 and https://github.com/flutter/flutter/issues/73435

**Comment by chinmaygarde** [comment]
cc @gaaclarke as the test author but I think this may be an underlying issue with all isolate teardowns based on the bugs listed by @cbracken.

I think we should combine issues of this class into a single tracking bug and tacking there.

**Comment by cbracken** [comment]
Saw this again today: 
Build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/9944/overview
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847852602004201056/+/u/Host_Tests_for_host_release/stdout

**Comment by hterkelsen** [comment]
Saw this again just now:
Build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/10378/overview
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8845507206293127760/+/u/Host_Tests_for_host_profile/stdout

**Comment by zanderso** [comment]
The tree is closed on this again. Escalating this to P1.

**Comment by zanderso** [comment]
Slightly different failure mode: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/10414/overview

**Comment by iskakaushik** [comment]
Backtrace for a failure: https://gist.github.com/iskakaushik/472251f387ff7caf3c43b87eea4d92b3

**Comment by gaaclarke** [comment]
@iskakaushik That PR seems to only address `ShellTest.Spawn` but above it was speculated that there is a deeper issue with isolate teardown.  Are we just papering over a deeper issue?

**Comment by jason-simmons** [comment]
I believe I've figured out what is happening here.

Spawned engines use `Dart_CreateIsolateInGroup` to create a new root isolate that shares an isolate group with the parent engine.

It turns out that `Dart_CreateIsolateInGroup` expects an isolate cleanup callback to be passed as an argument.  This differs from other isolate creation APIs, which use the cleanup callback provided in the `Dart_InitializeParams` used to set up the Dart VM.

The engine uses the isolate cleanup callback to delete the `flutter::DartIsolate` object that wraps the isolate.  So when the `Dart_CreateIsolateInGroup` isolate shuts down, the `DartIsolate` is leaked.

The `Dart_CreateIsolateInGroup` isolate also sets up a `Dart_SetMessageNotifyCallback` handled by `DartMessageHandler::OnMessage`.  `DartMessageHandler::OnMessage` queues a task that captures a `weak_ptr<DartIsolate>`.

The queued task expects that the `weak_ptr<DartIsolate>` will be invalid if the task executes after the isolate was shut down.  But since the `DartIsolate` for the `Dart_CreateIsolateInGroup` isolate was never deleted, the queued task thinks the isolate is still alive and tries to call `Dart_EnterIsolate`.  This causes the "Isolate is already scheduled" error that crashes the test.

I'll send out a PR that installs the cleanup callback for these isolates.

**Comment by iskakaushik** [comment]
@gaaclarke , did not mean to not root-cause the underlying issue. I was planning on continuing the investigation after Friday, but looks like Jason figured out the underlying issue. My fix was primarily aimed at preventing the flakes/tree-closures, I should've filed an issue to continue to investigation of the root-cause. I will re-open this issue and close it after @jason-simmons's fix lands.

**Comment by zanderso** [comment]
Closing as it looks like the fix landed.
