### ISSUE TITLE
Flutter Windows App Error Exception: Build process failed.

### ISSUE THREAD

**Issue by rupamking1** [flutter/flutter#77330]
`error-
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'H:\Flutter\Test Environment\harekrishna_1\build\windows\CMakeFiles\6a0b75e938984fb7d3bff3b48bc2e6e9\flutter_windows.dll.rule;H:\Flutter\Test Environment\harekrishna_1\build\windows\CMakeFiles\e6c9680ce1edfc3a05a35d41b430487c\flutter_assemble.rule' exited with code 1. [H:\Flutter\Test Environment\harekrishna_1\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.`

**Comment by TahaTesser** [comment]
Hi @rupamking1 
This is probably caused by a space in your path to your project
`[H:\Flutter\Test Environment\harekrishna_1\build\windows\flutter\flutter_assemble.vcxproj]` 
`Test Environment`, rename it to `Test-Environment` or `Test_Environment` and try with `futter clean` and then `flutter run -d windows`.
Hope this helps.
Related to https://github.com/flutter/flutter/issues/73644 https://github.com/flutter/flutter/issues/75611

If the problem persists, Can you please provide `flutter run -d windows --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Abhishek0116** [comment]
> `error- C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'H:\Flutter\Test Environment\harekrishna_1\build\windows\CMakeFiles\6a0b75e938984fb7d3bff3b48bc2e6e9\flutter_windows.dll.rule;H:\Flutter\Test Environment\harekrishna_1\build\windows\CMakeFiles\e6c9680ce1edfc3a05a35d41b430487c\flutter_assemble.rule' exited with code 1. [H:\Flutter\Test Environment\harekrishna_1\build\windows\flutter\flutter_assemble.vcxproj] Exception: Build process failed.`

Hey @rupamking1 
I have faced the same issue and thanks to @TahaTesser who identified the cause.

You may find [this superuser answer](https://superuser.com/a/1346983/1187264) helpful if you want to remove space from your username.
