### ISSUE TITLE
[Flutter Web] Ability to disable listener on arrow keys

### ISSUE THREAD

**Issue by kcin9** [flutter/flutter#77336]
I am currently working on some interactions with raw key events, i.e. pressing ← ↑ → ↓ should somehow interact with the UI.
As the UI components are wrapped with SingleChildScrollView, whenever press of  ↑ ↓  happens, the scrollview will result in changing vertical offset.

Hence, I would like to know if there is a way to prevent such unwanted behaviour of the scrollview? Or should I create a feature request with this? Thanks.

**Comment by mdebbar** [comment]
Have you considered using [`Shortcuts`](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html)/[`Actions`](https://api.flutter.dev/flutter/widgets/Actions-class.html)? If you have `Shortcuts` that handle arrow keys, then the default scrolling behavior will  automatically be disabled.

Removing the `platform-web` label since this isn't a web-specific issue.

**Comment by kcin9** [comment]
@mdebbar Thanks for the insight. Using Shortcuts and DoNothingIntent did make things working as I wished.

However, Shortcuts is described to be `A widget to that creates key bindings to specific actions for its descendants.`, which shall not mean to override the default behaviour(the scrolling effect) literally?

I originally believed that RawKeyboardListener would be the cure by instinct, just like keyboard listener in JS. And I checked again its definition: `A widget that calls a callback whenever the user presses or releases a key on a keyboard.` Guess we shouldn't consider matters in Flutter following the JS logic right?

**Comment by gspencergoog** [comment]
Closing as "as designed". (Desktop triage)
