### ISSUE TITLE
Consider using a static set of less specialized shaders that can be compiled on startup

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#77412]
Since we currently pay a price (jank) each time a new shader is used, and since some animations end up using a lot of new shaders, one option would be to use less specialized shaders.

If we had a static set of shaders, we could asynchronously compile them on program startup, so that by the time the application runs an animation we can use this static set and not stutter while we prepare a new one.

Medium term we could also determine what specialized shaders we would want to use in each scene, and compile them in the background so that the next time, if all the specialized shaders we would want to use are ready, we could just use them. That way we get the long-term sustained performance benefits of specialized shaders and the short-term smooth start performance benefits of a static shader set.

**Comment by armandsLa** [comment]
Any updates?

**Comment by Hixie** [comment]
Work is ongoing (@chinmaygarde made a demo of a subset of this for Metal which looks promising), but this is a long-term research project so I wouldn't expect frequent updates.

**Comment by mariopepe** [comment]
Hi all, is there any update on this issue?
Is there any chance we are going to get better (not to say production ready) animations on iOS by H1 2022?
If not, is there any chance we are going to get better (not to say production ready) animations on iOS by end 2022?
Is there any chance the priority of the issues related to animation jank on iOS is going to be elevated from P3 to, say P2 or P1?

Thanks

**Comment by Hixie** [comment]
For people who wish to follow along with this work, the library was recently merged into the engine tree (very much still as an experiment and nowhere near ready for production, please don't expect this to be available in stable for many many months yet): https://github.com/flutter/engine/tree/main/impeller

**Comment by chinmaygarde** [comment]
After a preview period since January 2023, Impeller is now on-by-default on iOS in a stable branch. We are now primarily focused on rounding out support for the remaining platforms with [Android up next](https://github.com/orgs/flutter/projects/21/views/11).

Impeller uses a static shader set and all shaders are compiled and optimized on our build servers. Depending on the backend, the optimized shader representation is packaged as a blob in the engine and necessary pipeline state objects created at startup asynchronously. There is no runtime shader generation or compilation at all.

Closing this issue as completed.
