### ISSUE TITLE
flutter doctor should help with firebase setup

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#77640]
I was using Flutter with Firebase this last weekend:
https://medium.com/flutter/must-try-use-firebase-to-host-your-flutter-app-on-the-web-852ee533a469

And it works (those instructions are old and point you to the node.js setup rather than the standalone executable which appears to be the new hotness).  But it could be a lot better/easier.

## Use case

Particularly for Flutter Web, where it seems immediately obvious that you'd want to be able to publish your Flutter app on the web, and firebase hosting is well setup for that.

## Proposal

`flutter doctor` should (maybe only when detecting `firebase` on the command line?) help you ensure that you have firebase setup correctly (similar to what we do for Android Studio), or maybe at least offer pointers to how to ensure similarly for Firebase?

Things which didn't work but could have:
* Setting up Github building for Flutter Web (seems to default to node and didn't seem to respond to my changes during setup)
* Setting up .gitignore correctly for firebase and flutter assets
* Installing Firebase was a pain (due to needing to add Node.js and then also make some sort of security exception for the firebase.ps1 tool).
* Setting up a corresponding hosting project was harder than necessary (I had to even contact Firebase support, but possibly relating to specific quirks to my old firebase account).

Thoughts @puf?  @kroikie?  Maybe I'm heading in the wrong direction and we should just be directing folks towards firebase tooling?

**Comment by jonahwilliams** [comment]
Detecting AndroidStudio and other IDEs is probably one of the weakest areas of the tool. There is an ongoing maintenance struggle: the other tool probably has a different release schedule than ours, sometimes that means breaking changes to our recommendations/detection at inopportune times.

If we were to support something like this, I'd like to see us set up a better standard for and reasonable expectations for what we could do, that includes:

* Specific policies on what versions of the firebase tooling we support. Could be a range, but hopefully not "all versions, forever". i.e. last 2 major versions.
* Some sort of release coordination or communication channel so that we could ensure that breaking changes in firebase tooling is delivered to stable channels at a reasonable cadence.

IIRC firebase also includes some per-project configuration as well, which seems like flutter create could support.

**Comment by jonahwilliams** [comment]
Detecting firebase on the PATH might be sufficient, but we'd probable need more information/version info to decide if it was supported. That also doesn't necessarily signal intent to use firebase with flutter, and it will miss cases where users have misconfigured firebase as well.

**Comment by jonahwilliams** [comment]
We didn't do this
