### ISSUE TITLE
Improve Flutter's  Test Suite CLI output 

### ISSUE THREAD

**Issue by Sameerkash** [flutter/flutter#77695]
## Use case

flutter test currently only shows a single line like so in case of test pass and fail respectively, without any additional information or additional UI.

```zsh
00:07 +63 -1: Some tests failed.
                                                                                                     
$ flutter test test/streamviewmodel_test.dart 

00:03 +19: All tests passed!    
``` 

## Proposal

Improve flutter's test suite CLI output UI, much like `jest` 's test suite.   To show grouped tests, and individuals tests implemented.  Also would be helpful if the Failing test's call stack is formatted a bit better.

![Screen Shot 2021-03-09 at 3 55 48 PM](https://user-images.githubusercontent.com/40424087/110458210-81e9f800-80f1-11eb-8b30-87e6c919437f.png)

It would be also helpful to include a watcher and code coverage, but that is already covered by  #4719

**Comment by darshankawar** [comment]
@Sameerkash 
Check out [this](https://groups.google.com/g/flutter-dev/c/A4OoGLEZy_w) thread and underlying solutions and see if it helps / answers your proposal.

**Comment by Sameerkash** [comment]
> @Sameerkash 
> Check out [this](https://groups.google.com/g/flutter-dev/c/A4OoGLEZy_w) thread and underlying solutions and see if it helps / answers your proposal.
> 

There doesn't seem to be a solution to my proposal. 


The problem at hand and the solutions in the thread are for report generation, 
What I'm looking for is some clean ui in the terminal to check the test as soon as I run it. 
This is of course just a developer experience, not related to the actual functionality of the test suite.

**Comment by gnprice** [comment]
If you want a line for each individual test, that's `flutter test -r expanded`. See `flutter test --help`:
```
-r, --reporter                                               Set how to print test results. If unset, value will default to either compact
                                                             or expanded.

          [compact]                                          A single line, updated continuously (the default).
          [expanded]                                         A separate line for each update. May be preferred when logging to a file or in
                                                             continuous integration.
          [failures-only]                                    A separate line for failing tests, with no output for passing tests.
          [github]                                           A custom reporter for GitHub Actions (the default reporter when running on
                                                             GitHub Actions).
          [json]                                             A machine-readable format. See: https://dart.dev/go/test-docs/json_reporter.md
          [silent]                                           A reporter with no output. May be useful when only the exit code is
                                                             meaningful.
```

> flutter test currently only shows a single line like so in case of test pass and fail respectively, without any additional information or additional UI.

This is the default for passing tests because it's convenient interactively; as mentioned above, you have several other options. For failing tests I don't think this has ever been the behavior — failures produce detailed output to help you debug.


> To show grouped tests […]
> Also would be helpful if the Failing test's call stack is formatted a bit better.

I'm not sure what "grouped tests" means here, or what you would like to be different about the formatting of call stacks. These would each be best expressed as a separate issue, with details about what you're asking for.

Closing because I don't think an umbrella issue in this form will be actionable. I do agree that Jest (https://jestjs.io/) has a very nice interface and that there are places where `flutter test` (and `dart test`) could benefit from copying it. The way to make progress on those will start by filing a specific issue for each concrete feature request or other improvement.
