### ISSUE TITLE
Web: How can I redirect assets to other domain ?

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#77700]
I deploy flutter web html file on **https://a.com/**
and set <script src="https://b.com/static/main.dart.js" type="application/javascript"></script> for cdn

so when i visit https://a.com/#  it will load all js file on https://b.com/
BUT assets file still load from https://a.com/ like http://a.com/assets/assets/images/sub.png

SO how can I tell flutter to found assets from **https://b.com/static/assets**  ?

**Comment by darshankawar** [comment]
@sunjianan9900 
Your question is better suited for support channels like StackOverflow, since this repo is use to track bugs and feature requests.
Closing from here. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
