### ISSUE TITLE
TextField cursor gets stuck on web

### ISSUE THREAD

**Issue by BertrandBev** [flutter/flutter#77929]
Here, a regular text widget shows the content of the `TextField`, swapping *spaces* with *bullet points* for clarity.
The issue occurs when moving the cursor around with the mouse, and then adding *spaces*. Text input works normally, but the cursor seemingly gets stuck when moved back at the end of the first line

**Issue**
![example](https://user-images.githubusercontent.com/12652154/110817768-e68d8a00-828c-11eb-8134-baf25ae83461.gif)

Tested on stable & dev channels, both on Chrome & Safari

Code used for the demo
https://github.com/BertrandBev/text_field_issue

**Comment by pedromassangocode** [comment]
I can reproduce this on latest stable channel with CanvasKit renderer. This does not reproduce with HTML renderer.

|HTML|CanvasKit|
|-|-|
|![gif](https://user-images.githubusercontent.com/67424416/110929192-fe661c00-8327-11eb-8a3e-7f9ec6cd4c47.gif)|![gif2](https://user-images.githubusercontent.com/67424416/110929535-556bf100-8328-11eb-9482-22bddec46bbb.gif)|



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.0.1 at /Users/pedromassango/Code/flutter_stable
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```

</details>

**Comment by mdebbar** [comment]
This is an issue in CK's paragraph API. There are two issues AFAICT.

### `getBoxesForRange`

**Example**: when the text field contains `"ABCD   \nXYZ"` and the cursor is placed at index 7 (right before the "\n"). `getBoxesForRange` in this case ignores all the whitespace between "ABCD" and "\n". It returns a box positioned right after "D", which is incorrect. It should take into account the 3 whitespace characters.

### `getPositionForOffset`

**Example**: when the text field contains `"ABCD   \nXYZ"` and the user clicks in the whitespace area between "D" and "\n". The `getPositionForOffset` method always returns index 7. It should be able to return indices 5 and 6 (i.e. between the whitespace characters) so that the cursor is placed correctly.

cc @hterkelsen @yjbanov

**Comment by mhrst** [comment]
This issue has come up before in Flutter's history:
- https://github.com/flutter/flutter/issues/40095

But it only seems to be affecting CanvasKit for the web on the stable branch.

As it is a reoccurring issue, it would be nice to have a test with the accompanying fix this time.

**Comment by alexeyinkin** [comment]
I cannot reproduce this with Flutter 3.3.5-stable, CanvasKit, Chrome 106, Ubuntu.

![vokoscreen-2022-10-31_17-49-51](https://user-images.githubusercontent.com/44893228/199024753-8a2b6707-b8b2-4aa4-9664-e6945884c823.gif)

@BertrandBev can you check if the issue is still standing? Or produce a minimal reproducible sequence of keys and clicks like 'click on the input, a, enter, a, click at the end of first line, dot, space'.

I am concerned because this issue's workarounds are hard to maintain.

**Comment by BertrandBev** [comment]
Yep, seems like it's gone. Thanks @alexeyinkin !

**Comment by gumbarros** [comment]
Is this fixed in what Flutter version?
