### ISSUE TITLE
[Mobile, Web, Desktop] Putting ElevatedButtons inside Column will have top and bottom margins if run in mobile but appear without top and bottom margins if run in web and desktop.

### ISSUE THREAD

**Issue by Ossabla** [flutter/flutter#78070]
When aligning ElevatedButtons on top of each other the display becomes different between mobile and web.
Please use the following code to reproduce this difference in mobile and web and look at the attached screenshots:

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('My first App'),
        ),
        body: Column(
          children: [
            Text("Elevated Buttons"),
            ElevatedButton(
              onPressed: null,
              child: Text('Answer 1'),
            ),
            ElevatedButton(
              onPressed: null,
              child: Text('Answer 2'),
            ),
            ElevatedButton(
              onPressed: null,
              child: Text('Answer 3'),
            ),
          ],
        ),
      ),
    );
  }
}

</details>
![web](https://user-images.githubusercontent.com/80549397/111000618-69990800-8393-11eb-8db1-93afea5d4bea.jpg)
![mobile](https://user-images.githubusercontent.com/80549397/111000644-7a497e00-8393-11eb-8a67-5cef892e26ed.jpg)

**Comment by Ossabla** [comment]
![web](https://user-images.githubusercontent.com/80549397/111001247-808c2a00-8394-11eb-8065-ea2c6ee66a94.jpg)

**Comment by jordyvandomselaar** [comment]
Hi,

Have you checked what happens when you try to run it as a desktop app? It might have something to do with the visual density but I'm not sure.

**Comment by Ossabla** [comment]
@jordyvandomselaar I have checked on Windows desktop same issue too. For your information I am using Flutter 2 on Windows 10. 
![desktop](https://user-images.githubusercontent.com/80549397/111017346-fa87d780-83c3-11eb-89a9-10c3af0071eb.jpg)

Thx!

**Comment by jordyvandomselaar** [comment]
@Ossabla I'm confident the issue is `visualDensity` then. What happens if you add `visualDensity: VisualDensity.comfortable` to your `themeData`?

**Comment by Ossabla** [comment]
@jordyvandomselaar Tried visualDensity, unfortunately same behavior.

**Comment by jordyvandomselaar** [comment]
Hmmm, that's odd. What happens if you manually add padding, do mobile devices get more padding?

**Comment by Ossabla** [comment]
@jordyvandomselaar Yes it adds!

**Comment by jordyvandomselaar** [comment]
That does sound like it's caused by the `column` widget 😅

**Comment by jordyvandomselaar** [comment]
I found out that if I change

```
   return Semantics(
      container: true,
      button: true,
      enabled: widget.enabled,
      child: _InputPadding(
        minSize: minSize,
        child: result,
      ),
    );
```

to

```
return Semantics(
      container: true,
      button: true,
      enabled: widget.enabled,
      child: result,
    );
```

In `button_style_button.dart` that makes it consistent. 

If I change `minSize: minSize,` to `minSize: Size.zero`, that also works.

When I look further, I can see that `minSize` is calculated like this:

```
 final Size minSize;
    switch (resolvedTapTargetSize!) {
      case MaterialTapTargetSize.padded:
        minSize = Size(
          kMinInteractiveDimension + densityAdjustment.dx,
          kMinInteractiveDimension + densityAdjustment.dy,
        );
        assert(minSize.width >= 0.0);
        assert(minSize.height >= 0.0);
        break;
      case MaterialTapTargetSize.shrinkWrap:
        minSize = Size.zero;
        break;
    }
```

`densityAdjustment` is defined as `final Offset densityAdjustment = resolvedVisualDensity!.baseSizeAdjustment;` and finally `resolvedVisualDensity` is `final VisualDensity? resolvedVisualDensity = effectiveValue((ButtonStyle? style) => style?.visualDensity);`

As we can see here it does have something to do with visualDensity. Now I know `Size.zero` works because I tried hard-coding it. If we look at the `switch` statement above, it actually uses `Size.zero` if `resolvedTapTargetSize` equals `MaterialTapTargetSize.shrinkWrap`. 

`resolvedTapTargetSize` is defined as follows: ` final MaterialTapTargetSize? resolvedTapTargetSize = effectiveValue((ButtonStyle? style) => style?.tapTargetSize);`

Here we see that `ButtonStyle` has a property called `tapTargetSize` which determines what the `resolvedTapTargetSize` is. Because it has to be `MaterialTapTargetSize.shrinkWrap` we can add it to our `ElevatedButton` like this:

```
  ElevatedButton(
              style:
                  ButtonStyle(tapTargetSize: MaterialTapTargetSize.shrinkWrap),
              onPressed: null,
              child: Text('Answer 1'),
            )
```

I've tested it, and now it looks the same on all platforms, without padding!

Hope that helps =)

**Comment by Ossabla** [comment]
@jordyvandomselaar Many many thanks for your efforts. Actually, this is excellent explanation and solution. Now all platforms display the buttons without margins/paddings. 
Can you please tell me where this code is located
return Semantics(
      container: true,
      button: true,
      enabled: widget.enabled,
      child: _InputPadding(
        minSize: minSize,
        child: result,
      ),
    );
Thanks in advance

**Comment by jordyvandomselaar** [comment]
@Ossabla I'm glad I could help =), I do think the Flutter team should have a look at this, I'd at least expect the padding to go away if I changed the visualDensity.

**Comment by Ossabla** [comment]
@jordyvandomselaar However, you did wonderful job in locating a workaround about this issue and I hope that Flutter team will take this into account.
Thanks again!
