### ISSUE TITLE
route.hasScopedWillPopCallback is a foot gun

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7826]
See for example https://github.com/flutter/flutter/issues/6331#issuecomment-277060988

**Comment by HansMuller** [comment]
It is the case that we assume that hasScopedWillPopCallback implies that the app may veto the pop.  We need to know so that the back gesture can be disabled if the app might veto a pop.

However the API was really only intended as a way for MaterialPageRoute to communicate with ModalRoute. So per our discussion, I'm going to make the method protected.
