### ISSUE TITLE
Window desktop, drag the edge to zoom the window, and there will be no response when dragging

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#78318]
The recurring path is as follows：
1、win10 system
2、flutter create myapp
3、flutter create --platforms=windows .
4、run window app
5、Drag the form to enlarge, no response
![无标题](https://user-images.githubusercontent.com/3191545/111303106-1b378200-868f-11eb-9a3c-bb02e6a68af4.png)

**Comment by darshankawar** [comment]
@chongbo2013 
Can you provide `flutter doctor -v` ?

**Comment by chongbo2013** [comment]
@darshankawar ok thank u.
C:\Users\huatai\Desktop\dolawin>flutter doctor -v
[√] Flutter (Channel master, 2.1.0-13.0.pre.103, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 2.1.0-13.0.pre.103 at C:\src\flutter
    • Framework revision 0cbe597540 (27 hours ago), 2021-03-15 16:28:02 -0700
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\huatai\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1198]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@chongbo2013 
Tried the same on latest stable using a sample app and was able to drag the windows from all corners and resize properly. I could've shared video of it, but since it's not different machine, it's time consuming, but below is my machine config:

![IMG-0693](https://user-images.githubusercontent.com/67046386/111431673-153eb100-8722-11eb-9ecf-84cf10339ccb.JPG)


If I understand this issue correctly, when windows app launches, trying to drag from any corner edges, isn't zooming out or in for you ?
If so, can you share a video of this issue ?

**Comment by chongbo2013** [comment]
okYes, the computer is not by my side now, but I can record my actions for you

**Comment by chongbo2013** [comment]
https://user-images.githubusercontent.com/3191545/111432948-a28d0000-8738-11eb-82f8-4d67d4cb49b7.mp4

Just drag the window and zoom like this, but there is no response, but this is just an example of operation, not flutter, this video lets you know how I operate

**Comment by chongbo2013** [comment]
@darshankawar  I have already sent you, I doubt whether it has something to do with the computer's configuration GPU information

**Comment by darshankawar** [comment]
I don't seem to get the issue you mentioned. Also the video you shared isn't full so can't really understand what exactly the issue is here. I am able to Drag the app from corners which dragged and resized properly.


https://user-images.githubusercontent.com/67046386/111461327-1207ed00-8743-11eb-8c95-473ff935c18b.MOV

**Comment by Dairyo-Gokan** [comment]
This issue depends on Flutter master channel, not realized on stable channel.

I also had really same issue, flutter (master channel) for Windows desktop, on Windows 10 20H2 (Version 10.0.19042.868).
After found this thread, I had been watched carefully.

But, I confirmed that, this issue was solved, after upgrading to 2.1.0-13.0.pre.175, on this morning.

First time, I had noticed this issue few days ago (3/16), after upgrading Flutter to 2.1.0-13.0.pre.103 from 2.1.0-13.0.pre.86. 

On the next day (3/17), I tried to upgrade Flutter again, to 2.1.0-13.0.pre.132 from to 2.1.0-13.0.pre.103. 
But, same issue still realized.

Then, I tried to downgrade Flutter, 2.1.0-13.0.pre.103. But, same issue still realized. I tried with both release build, and debug build. Both build caused same issue.
