### ISSUE TITLE
Change the language of camera buttons.

### ISSUE THREAD

**Issue by osamasado** [flutter/flutter#78314]
How can I change the language of camera buttons, when i open the camera i want to show "cancel" button and "photo" text in other language exactly such as the device language. the text appears always in English.

**Comment by darshankawar** [comment]
@osamasado 
Your question is better suited for support channels like StackOverflow, as this repo is meant to track bugs and feature requests for the framework. You may access [this](https://github.com/flutter/flutter/issues/new/choose) link, select `I want help writing my application` and click on `open` link to get more help on your issue.
Closing from here since this is more of a `how to` question.
