### ISSUE TITLE
plugins connectivity (Error web)

### ISSUE THREAD

**Issue by allessandrosj** [flutter/flutter#78324]
Error when running the connectivity plugins on the web presents the following error

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/connectivity_status:
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/connectivity_status)

the code tested the following
https://github.com/flutter/plugins/blob/master/packages/connectivity/connectivity/example/lib/main.dart

**Comment by bjoernahrens** [comment]
I experience the same and from my research I can say that this bug was introduced in Connectivity version 3.0.0. The exception was not thrown in version 2.0.2, but there are no breaking changes mentioned in the changelog.

**Comment by stuartmorgan** [comment]
Fixed in 3.0.3, which was just published. Web support was temporarily removed (which due to a bug in the way it was done wasn't reflected in the pub.dev UI) for 3.0.0, and has been re-endorsed in 3.0.3 now that the web implementation supports null safety. That should have been in release notes, but was accidentally dropped when we cleaned up prerelease notes in the stable release.
