### ISSUE TITLE
☂️ Rewrite the Flutter Runners in Dart

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#78373]
From @timsneath:
> A true test of [our ability to write Windows apps in Flutter] and our overall Win32/FFI support would be to rewrite the relatively small amount of runner code in Dart, rather than C++. Aside from the test of our own support, this would have some obvious app benefits -- a developer can debug the entire app from beginning to end, they can customize the window (e.g. owner-draw title bars, programmatically resize etc.). 
>
> Most importantly, this would allow Windows developers to build Flutter desktop apps without needing a full licensed copy of Visual Studio. This is a huge impediment -- Visual Studio is several gigabytes, installation is full of friction points, and the license starts at $600/year for commercial use outside of OSS projects.

We would like to consider doing this, and also investigate what it would take to rewrite other platforms' Runners in Dart as well so that all platforms can get similar benefits. We'd need to have a "base API" that all the runners could hook into that would call the necessary FFI-based interactions with the host platform, and common logic could be shared.

/cc @csells @cbracken

**Comment by stuartmorgan** [comment]
> A true test of [our ability to write Windows apps in Flutter]

This seems like an odd framing; by this standard, no Flutter applications have been written for any platform, since none of the runners work this way.

> a developer can debug the entire app from beginning to end

Is not being able to easily debug the runner--code that it seems like most developers never actually touch--an actual pain point?

> they can customize the window (e.g. owner-draw title bars, programmatically resize etc.).

This is already true; do we think most people who don't know how to do this now are primarily stopped by not knowing C++ rather than not knowing Win32? I'm skeptical, since the C(++) knowledge to do things like change window creation flags is minimal. Knowing how to find those flags is much harder.

> Most importantly, this would allow Windows developers to build Flutter desktop apps without needing a full licensed copy of Visual Studio.

This could be done much more easily by switching to ninja+clang for Windows. There's another issue where this was discussed recently.

Keep in mind that this is not just a question of what one developer needs, it's a question of what is supported for the entire ecosystem. Whatever toolchain we bless is, effectively, the only one the ecosystem can use (unless we want to subject all Flutter developers to the significant pain of plugins that each have their own toolchain requirements). If the goal is to remove the need for a C++ toolchain then we are *requiring* all plugins to be written in Dart. (And implications for supporting C#, which is a poplar request, are significant.)

**Comment by Hixie** [comment]
This is an interesting idea, but I think the right way to approach this would be a design doc, rather than a brief idea on an issue. I'm going to close this for now but would be very interested in reading a design doc if someone wants to run with this idea.
