### ISSUE TITLE
[Web] Image.network does sets Origin=null on redirects (302)

### ISSUE THREAD

**Issue by peterlauri** [flutter/flutter#78374]
We have an API endpoint that generates an image resource, and makes a redirect to another location where the image is located.

When using Image.network, the initial request made to our API endpoint includes the correct Origin in the requests header. But after it gets the 302 and redirects, the Origin is set to null. This causes CORS to fail.

Following the same pattern using curl -v -L, one can see that the Origin is kept over the redirect.

GET https://myserver.com/generate-image (with header Origin=https://myflutterapp.com)
Response: 302 Location https://myimageserver.com/the-image-link
GET https://myimageserver.com/the-image-link (with header Origin=**null**)

The current workaround is the modify our CORS settings on the image server to the below, that is not that sane :)

```
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
```

**Comment by darshankawar** [comment]
@peterlauri 
Can you elaborate on what are you proposing on Flutter web side to handle this case ?

**Comment by peterlauri** [comment]
> @peterlauri
> Can you elaborate on what are you proposing on Flutter web side to handle this case ?

Image.network should send proper Origin header even on a **redirect**.

**Comment by darshankawar** [comment]
Thanks for the update @peterlauri 
Does [this](https://github.com/flutter/flutter/issues/57187) issue sound similar to yours ? and https://github.com/flutter/flutter/issues/57187#issuecomment-635637494 for further reference.

**Comment by peterlauri** [comment]
> Thanks for the update @peterlauri
> Does [this](https://github.com/flutter/flutter/issues/57187) issue sound similar to yours ? and [#57187 (comment)](https://github.com/flutter/flutter/issues/57187#issuecomment-635637494) for further reference.

No it is not similar to this issue. The Image.network sends the Origin correctly on the first request, but on the redirect request the Origin=null. It should send the real Origin, meaning same as in the original request.

**Comment by peterlauri** [comment]
@darshankawar this issue is present in 2.0.2 release branch. It will break for ANY images that uses a redirect pattern to provide the final image resource (unless the final image resource is fully open and allows any CORS).

**Comment by ditman** [comment]
`Image.network` is using the browser stack to perform XHR/fetch requests. **The browser will transparently follow all redirects** until a request succeeds or fails.

When the browser detects that a redirect changes the domain of a request ("privacy-sensitive context change"), it'll clear the Origin header. Here's a Stack Overflow question relevant to this issue:

* [**SO**: Are there any browsers that set the origin header to “null” for privacy-sensitive contexts?](https://stackoverflow.com/questions/22397072/are-there-any-browsers-that-set-the-origin-header-to-null-for-privacy-sensitiv)

_You can verify this is *not* a flutter-web only issue, if instead of using `curl` (which is not constrained by the same security restrictions that a web browser), you use the JS debug console in your browser and do `fetch('YOUR_ORIGINAL_IMAGE_URL');`, and take a look at the Network panel,  you should see all the redirects there, and how headers differ from one request to the next._

According to the docs, [`null` is an accepted value for the `Origin` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#origin); it is also [recommended that you return whatever was sent to you as an `Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#examples), after comparing it with an internal allow-list, and I suppose the whole problem is originating.

Is there any possibility that you serve images directly, without intermediate 30X redirects?

**Comment by peterlauri** [comment]
> [`Image.network` is using](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/canvaskit/image.dart#L39) the [standard browser stack](https://api.dart.dev/stable/2.9.2/dart-html/HttpRequest-class.html) to perform XHR requests. **The browser will transparently follow all redirects** until a request succeeds or fails.
> 
> When the browser detects that a redirect changes the domain of a request ("privacy-sensitive context change"), it'll clear the Origin header. Here's a Stack Overflow question relevant to this issue:
> 
> * [**SO**: Are there any browsers that set the origin header to “null” for privacy-sensitive contexts?](https://stackoverflow.com/questions/22397072/are-there-any-browsers-that-set-the-origin-header-to-null-for-privacy-sensitiv)
> 
> _You can verify this is _not_ a flutter-web only issue, if instead of using `curl` (which is not constrained by the same security restrictions that a web browser), you use the JS debug console in your browser and do `fetch('YOUR_ORIGINAL_IMAGE_URL');`, and take a look at the Network panel, you should see all the redirects there, and how headers differ from one request to the next._
> 
> According to the docs, [`null` is an accepted value for the `Origin` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#origin); it is also [recommended that you return whatever was sent to you as an `Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#examples), after comparing it with an internal allow-list, and I suppose this behavior is what's causing your problem since you can't look at the Origin value anymore.
> 
> Is there any possibility that you serve images directly, without intermediate 30X redirects?

Thanks @ditman for your very clear explaination :)

The API is implemented in a way to reduce data traffic from our API server, so we only redirect the user to a signed location in a private S3 bucket. We will reconsider this approach :) In my opinion it should be safe to allow any ORIGIN for GET on our private S3 bucket, as we can assume that someone holding a signed S3 url should be allowed to get the image... :)

**Comment by ditman** [comment]
> In my opinion it should be safe to allow any ORIGIN for GET on our private S3 bucket, as we can assume that someone holding a signed S3 url should be allowed to get the image...

@peterlauri agreed! `*` sounds like a reasonable approach in the signed URL case, especially if those signed URLs have an expiration time!

**Comment by peterlauri** [comment]
> > In my opinion it should be safe to allow any ORIGIN for GET on our private S3 bucket, as we can assume that someone holding a signed S3 url should be allowed to get the image...
> 
> @peterlauri agreed! `*` sounds like a reasonable approach in the signed URL case, especially if those signed URLs have an expiration time!

@ditman yes, they have short expiration time, so I will leave the GET open to any origin :)
