### ISSUE TITLE
A Velocity type with units, like Duration, would simplify fling gesture handling

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#785]
Currently we convert from pixels/second to pixels/ms ad hoc. See scroll_behavior.dart, scrollable.dart, dismissable.dart, bottom_sheet.dart, etc. Constants like_kMinFlingVelocity and _kMaxFlingVelocity have an implicit unit that has to be accounted for.

A Velocity analog of Duration would help.

**Comment by cooler-king** [comment]
Better to use the term Speed than Velocity; Velocity implies a vector quantity with direction.

Also you may want to consider having the constants based on physical length instead of pixels (that is, convert pixels to length first using the device's pixels/cm).  Doing so would give you a device independent consistent feel.

I have a package that helps with units (`quantity`).  It doesn't have a quantity type for pixels but you may get ideas from the Speed class:
https://github.com/cooler-king/quantity/blob/master/lib/src/si/types/speed.dart

Or I can look into adding support for pixels if you want to use the package directly.

Note that the package also has support for Angles, Time, Mass, Length and other quantities you may find useful for flutter.
