### ISSUE TITLE
flutter web not starting on Edge and chrome on debug mode 

### ISSUE THREAD

**Issue by michaelandom** [flutter/flutter#78595]
Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at

C:\flutter_windows_2.0.1-stable\flutter\bin\flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at C:\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@michaelandom 
Are you using AS or Vscode ? 

Are you able to launch from terminal (command prompt) ?

**Comment by michaelandom** [comment]
I am using android studio

**Comment by darshankawar** [comment]
> Are you able to launch from terminal (command prompt) ?

@michaelandom Can you try this and check if you get same error or not ?

**Comment by michaelandom** [comment]
Are you able to launch from terminal (command prompt) ?
i have the same error

**Comment by darshankawar** [comment]
@michaelandom 
Can you provide `flutter run -d chrome --verbose` ?

I have been using Windows 10 machine to run apps on web and haven't seen this issue at all, so not sure where the issue could be.

![Uploading Screenshot 2021-03-23 at 12.37.28 PM.png…]()

**Comment by deCardenas** [comment]
I'm trying to run flutterfolio on web and I had the same problem.

![image](https://user-images.githubusercontent.com/8282194/114252701-3a62c000-996c-11eb-9239-8fcaaa0541d0.png)

with flutter run -d chrome  not start

![image](https://user-images.githubusercontent.com/8282194/114252777-9fb6b100-996c-11eb-8fa1-6e916d011916.png)
 
this is the result of flutter run -d chrome -v
![image](https://user-images.githubusercontent.com/8282194/114252870-1358be00-996d-11eb-8a7f-67e9a69ad324.png)

> 
[  +87 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +83 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +43 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +52 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +102 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] executing: C:\Users\Diego\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] executing: C:\Users\Diego\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +18 ms] Skipping pub get: version match.
[  +26 ms] Found plugin file_chooser at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\file_chooser\
[  +10 ms] Found plugin menubar at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\menubar\
[   +3 ms] Found plugin window_size at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\window_size\
[  +13 ms] Found plugin bitsdojo_window at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window-0.0.5\
[   +3 ms] Found plugin bitsdojo_window_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.0.1\
[   +5 ms] Found plugin bitsdojo_window_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.0.1\
[  +25 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +5 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[  +17 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +3 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[  +11 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-7.1.8\
[  +29 ms] Found plugin multi_image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.7.15\
[   +7 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +19 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.5+4\
[   +4 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +2 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\       
[   +2 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\      
[   +3 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +2 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.2+3\   
[   +6 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+3\
[  +15 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +2 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +2 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[ +301 ms] Found plugin file_chooser at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\file_chooser\
[   +2 ms] Found plugin menubar at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\menubar\
[   +2 ms] Found plugin window_size at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\window_size\
[   +8 ms] Found plugin bitsdojo_window at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window-0.0.5\
[   +1 ms] Found plugin bitsdojo_window_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.0.1\
[   +2 ms] Found plugin bitsdojo_window_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.0.1\
[  +10 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +3 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[   +8 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +5 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +2 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +2 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +4 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-7.1.8\
[  +16 ms] Found plugin multi_image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.7.15\
[   +7 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +8 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.5+4\
[   +2 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +1 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\       
[   +1 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\      
[   +1 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +1 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.2+3\   
[   +4 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+3\
[  +11 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +2 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +3 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[  +22 ms] Generating D:\FlutterProjects\flutter-folio\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +88 ms] List of devices attached
[  +77 ms] Launching lib\main.dart on Chrome in debug mode...
[   +9 ms] List of devices attached
[ +113 ms] Updating assets
[ +222 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[  +11 ms] Found plugin file_chooser at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\file_chooser\
[   +2 ms] Found plugin menubar at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\menubar\
[   +2 ms] Found plugin window_size at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\window_size\
[   +4 ms] Found plugin bitsdojo_window at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window-0.0.5\
[   +1 ms] Found plugin bitsdojo_window_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.0.1\
[   +2 ms] Found plugin bitsdojo_window_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.0.1\
[   +9 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +1 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[   +8 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +2 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +2 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +3 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-7.1.8\
[  +15 ms] Found plugin multi_image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.7.15\
[   +7 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +11 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.5+4\
[   +1 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +1 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\       
[   +1 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\      
[   +1 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +1 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.2+3\
[   +3 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+3\
[  +12 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +2 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[  +23 ms] Found plugin file_chooser at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\file_chooser\
[   +1 ms] Found plugin menubar at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\menubar\
[   +1 ms] Found plugin window_size at
C:\src\flutter\.pub-cache\git\flutter-desktop-embedding-040f36c82b63e8764ec2fd97066767503a667b6d\plugins\window_size\
[   +4 ms] Found plugin bitsdojo_window at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window-0.0.5\
[   +2 ms] Found plugin bitsdojo_window_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.0.1\
[   +1 ms] Found plugin bitsdojo_window_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.0.1\
[   +7 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\
[   +1 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+2\
[   +8 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\
[   +2 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.3\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +4 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-7.1.8\
[  +13 ms] Found plugin multi_image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.7.15\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +7 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.5+4\
[   +1 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +1 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\       
[   +2 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\      
[   +3 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +2 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.2+3\   
[   +4 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+3\
[   +8 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[ +298 ms] <- reset
[  +26 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/      
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill       
C:\Users\Diego\AppData\Local\Temp\flutter_tools.9fd13460\flutter_tool.2687c082\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\FlutterProjects\flutter-folio\.dart_tool\package_config.json    
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Diego\AppData\Local\Temp\flutter_tools.9fd13460\flutter_tools.371bbb32 --filesystem-scheme org-dartlang-app --initialize-from-dill   
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +45 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+29272 ms] Waiting for connection from debug service on Chrome... (completed in 29,9s)
[   +1 ms] Synced 45.4MB.       
[        ] <- accept
[        ] Caching compiled dill
[ +157 ms] Using 
[  +11 ms] Failed to launch browser. Command used to launch it: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
--user-data-dir=C:\Users\Diego\AppData\Local\Temp\flutter_tools.9fd13460\flutter_tools_chrome_device.f0f7c612 --remote-debugging-port=29157
--disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check       
--disable-default-apps --disable-translate http://localhost:29131
[   +7 ms] "flutter run" took 31.587ms.
[   +9 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead andfiling an
           issue at https://github.com/flutter/flutter/issues.
[   +7 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1325:9)
           #3      _rootRun (dart:async/zone.dart:1346:47)
           #4      _CustomZone.run (dart:async/zone.dart:1258:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1346:47)
           #12     _CustomZone.run (dart:async/zone.dart:1258:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1346:47)
           #23     _CustomZone.run (dart:async/zone.dart:1258:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1346:47)
           #35     _CustomZone.run (dart:async/zone.dart:1258:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
           #44     _rootRunUnary (dart:async/zone.dart:1370:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[ +275 ms] ensureAnalyticsSent: 258ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[+1896 ms] Shutdown hooks complete
[  +18 ms] exiting with code 1

**Comment by TahaTesser** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/79225
