### ISSUE TITLE
Not able to install any packages

### ISSUE THREAD

**Issue by anoopkumar1223** [flutter/flutter#78611]
Running "flutter pub get" in sit_cse_hub...                     
The current Dart SDK version is 2.7.2.

Because sit_cse_hub depends on flutter_native_splash >=1.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.

pub get failed (1; Because sit_cse_hub depends on flutter_native_splash >=1.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)

I am not able to install any packages. Please help me fix this.

Here is my pubspec.yaml file

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  lottie: ^0.7.0+1
  clay_containers: ^0.2.2
  font_awesome_flutter: ^8.11.0
  flutter_gradient_colors: ^1.0.0
  flutter_native_splash: ^1.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by darshankawar** [comment]
@anoopkumar1223 
The error clearly states what you need to do. You are on on older dart version which doesn't support null safety. The packages you are using must have migrated to null safety and hence the conflict.

`Because sit_cse_hub depends on flutter_native_splash >=1.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)`

Upgrade your dart version as mentioned in the error message which should resolve your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
