### ISSUE TITLE
Fix and re-enable SkpWarmup tests on Fuchsia Emulator

### ISSUE THREAD

**Issue by yz-zhi** [flutter/flutter#78650]
I disabled the tests
```
flutter_runner_tests 
  EngineTest.SkpWarmup
shell_tests
  SkpWarmupTest.Basic
  SkpWarmupTest.Image
```

on Fuchsia Emulator. To see the test fail, you can remove the test filters at
https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/femu_test.py#206

Then run the femu builder
```
led get-builder 'luci.flutter.try:Linux Fuchsia' | led edit -r femu_test | led edit-recipe-bundle | led launch
```

**Comment by freiling** [comment]
So the shell_tests are passing on ToT on Estelle, and appear to only be failing on FEMU. I'm struggling to get a FEMU setup working so its hard to confirm.

 EngineTest.SkpWarmup is broken on ToT on Estelle and I can fix that, but on FEMU it is failing in the same way as the other two, which i think might be unrelated. 

I was going to try to diagnose the the shell_tests first but I'm running into a lot of friction with FEMU (I use macbook+cloudtop and neither one seems to want to run FEMU very easily), so I think I'm going to try to deal with the Engine test problem first since I can at least try to get that working on hardware

**Comment by godofredoc** [comment]
\c @yz-zhi @freiling who should this bug be assigned to?

**Comment by freiling** [comment]
I think is should go to Yilong, he has a fix for the issue i was looking at and is investigating the infra specific failures. I don't know his github username though, I'll ask.

**Comment by gnoliyil** [comment]
Okay I'll take it.

**Comment by freiling** [comment]
Thanks Yilong!

**Comment by godofredoc** [comment]
Is anyone from fuchsia working on this? should we close this bug?
