### ISSUE TITLE
Feature Request: let Navigator.push optionally pass a parameter to the page being pushed

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#7877]
## Steps to Reproduce

Under "Routes can return a value" the [Navigator class documentation](https://docs.flutter.io/flutter/widgets/Navigator-class.html) only talks about `Navigator.pop` being able to pass a parameter back when a route is removed. But what about passing a parameter forward to the page being called with a `Navigator.push()`? 

As an example use case, say I have a list of items which a user can click to go to a detail page about the item chosen.  It would be useful if I could write something like this:

```dart
    @override
    void itemTapped() {
      Navigator.pushNamed(context, NavigationRoutes.itemDetail, myItemId);
    }
```

so I can pass my generic ItemDetail widget the ID# of the item it is to be displaying details about.  (Or, better yet, pass it the entire `myItemProtobuffer` with all the details of the current item that it will need when filling in the display.)

Currently I do this instead, which feels messier:
```dart
    @override
    void itemTapped() {
      global_state.currentItemId = myItemId;
      Navigator.pushNamed(context, NavigationRoutes.itemDetail, myItemId);
    }
```

**Comment by abarth** [comment]
We have vaguely thought about using `RouteSettings` for this sort of thing.  We might want to combine this with a way of parsing out parameters from route names (e.g., after a `?` or something).

**Comment by aubykhan** [comment]
@abarth for now, [fluro](https://pub.dartlang.org/packages/fluro) is doing something similar but I feel that should be part of the core flutter framework and shouldn't have dependency on external plugins.

**Comment by seenickcode** [comment]
I'm writing my first major app with Flutter and coming across this, unless I'm missing something from the docs, it seems that defining "routes" for a `MaterialApp` is half-useful, because the vast majority of screens require some type of context to load. 

For example, say you have an EditFoobar screen. You'd pass a `FoobarId` to that page and then load that object. Therefore, it seems one would define a strange mix of "routes" for this `MaterialApp`, for only pages that do not require context then use the following for passing in some kind of context (i.e. a `FoobarId`).

```
                  Navigator.push(
                      context,
                      new MaterialPageRoute(
                        builder: (BuildContext context) =>
                            new Foobar(new Key(foobarId), foobarId),
                      ));
```

**Comment by goderbauer** [comment]
This is now implemented: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments
