### ISSUE TITLE
Enable OS X testing on Travis

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#7894]
It's supported as part of https://github.com/travis-ci/travis-ci/issues/216

https://docs.travis-ci.com/user/multi-os/

**Comment by tvolkert** [comment]
Attempted to do this in https://github.com/flutter/flutter/pull/8095 -- yielded "Too many open files" errors (https://travis-ci.org/flutter/flutter/jobs/201210315)

**Comment by tvolkert** [comment]
@yjbanov

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/2976 is likely the cause.  @zanderso helped us track down a related bug in the `dart` handler, he may have some tips for us tracking down that bug in sky_shell.

**Comment by zanderso** [comment]
The problem in the standalone VM was that its loader is asynchronous and it wasn't doing any throttling of open() calls for imports. It would see a bunch of imports, and then do a bunch of open()s to load them in, thereby running on of file descriptors on Mac.

AFAIU, sky_shell has a different loader, which is synchronous. It hits an import, open()s the file, reads it in, and then closes it, so I don't think that's the problem we're hitting here.

I did a little sleuthing on the string 'Failed to load "..."'. It turns out that the test package has its own loader (whose purpose I couldn't begin to guess) and, it's the only place in the Dart or Flutter trees that has that string. See: https://github.com/dart-lang/test/blob/master/lib/src/runner/load_exception.dart

/cc @nex3

**Comment by nex3** [comment]
In this case, the `LoadException` is just wrapping an exception from `dart:io`.

**Comment by zanderso** [comment]
Sorry I don't know exactly how the test package works, but I would guess that whatever loading the it's doing manually will likely need to be throttled to avoid running out of file descriptors on MacOS.

**Comment by nex3** [comment]
The only file IO the `test` package does manually is synchronous, and so should only allocate a small number of file descriptors at once. Everything else is done through the isolate API.

**Comment by zanderso** [comment]
Hmm, okay. It looks like flutter_tool creates a custom "Platform" for the test package, which spawns a bunch(?) of sky_shell instances, that then presumably go on to load in the test package, which is probably why the error report string is coming from there.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart

I'm afraid I have to punt now, but that looks to me like a good place to start looking.

**Comment by eseidelGoogle** [comment]
FYI @cbracken @yjbanov, not sure of the current status.

**Comment by tvolkert** [comment]
I think #2976 is still an issue

**Comment by yjbanov** [comment]
Last time I tried our installation flow would get stuck. But we've been running things successfully in the devicelab on Macs, so probably that process should be solid now.

**Comment by tvolkert** [comment]
I got further than installation flow in #8095, but ran into #2976 (see https://github.com/flutter/flutter/issues/7894#issuecomment-279509879)
