### ISSUE TITLE
[ImagePickerPlugin] io.flutter.plugins.imagepicker.ImagePickerPlugin instance had a memory leak.

### ISSUE THREAD

**Issue by HarmanJi** [flutter/flutter#78951]
## Plugin Version 0.7.3

When we use it, we find that the activity field held in the ImagePickerPlugin class is not set to null when the teardown method is executed, resulting in a memory leak. Please repair, thank you.

**Comment by darshankawar** [comment]
@HarmanJi 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by HarmanJi** [comment]
We adopt a mixed development mode. In terms of scenarios, we currently use flutter to realize some page functions. One of the flutter pages uses imagepicker plug in function, but when the page is closed, leakcanary reminds you of memory leak, as shown in the figure.

![issue](https://user-images.githubusercontent.com/15935220/112292623-3bd58c80-8ccc-11eb-99c4-dc81033c11bf.png)

**Comment by HarmanJi** [comment]
We testers find this problem in the process of testing, but it can't happen every time.

**Comment by darshankawar** [comment]
Are you using [FlutterBoost](https://pub.dev/packages/flutter_boost) hybrid solution ? 
If so, you may need to reach out in dedicated repo: https://github.com/alibaba/flutter_boost/issues

If not, it'll be great if you could provide us steps to replicate this issue without any 3rd party plugins or tools, so that we can properly address this.

Thanks.

**Comment by HarmanJi** [comment]
Yes, we are using  FlutterBoost.

**Comment by HarmanJi** [comment]
Thanks.
