### ISSUE TITLE
local_auth: Open pattern/pin option if user faces some sensor issues or any.

### ISSUE THREAD

**Issue by Praveen-Ramalingam** [flutter/flutter#79123]
Currently in local auth if device supports fingerprint the fingerprint is shown and not giving any option for user to open pattern/pin to login is there a way to open pattern/pin in case if user faces difficulty with fingerprint.

**Comment by Praveen-Ramalingam** [comment]
@mehmetf  @dnfield  can you please help me on this

**Comment by darshankawar** [comment]
@Praveen-Ramalingam 
I don't think if biometric is set, the option to use patterrn/pin/password will be feasible due to security standards and policies set by the OS (Android, iOS). Check [this](https://stackoverflow.com/a/54905122) SO answer and see if it helps.

I am going ahead and closing this. If you disagree, write in comments and I'll reopen it.
Thanks.
