### ISSUE TITLE
The template code created by the flutter module does not support http access

### ISSUE THREAD

**Issue by jiechic** [flutter/flutter#79433]
We have native app on android or ios，we use flutter module add Flutter to existing app
some time ，we will debug only flutter module , we use test environment  with http access buy not https , 
we will get error that means it is not to use http on after ios 9(android 9) 
can update flutter module template to support http access?

**Comment by jmagman** [comment]
We purposely keep the module app as clean as possible because nothing you change in this app matters unless you change it in the host app, and we would need corresponding documentation for how to change it.  And most apps shouldn't disable networking security restrictions.

I don't think we should do this.

**Comment by jiechic** [comment]
in module app，it's have two parts 
1、flutter module
2、flutter host app

normal development process with add to app have some step like next
1、run flutter host app debug with test environment
2、build flutter module （only module，not host app）to android aar or ios-framework（without host app config）
3、android or ios import aar or ios-framework

so in step 1，Our development usually executes the following commands
```shell
flutter clean
flutter packages get
flutter run
```
template code will be create by `flutter packages get`
When we need to debug in a test environment with http, every time I need to modify the host app code to disable networking security restrictions，because most testing environments do not have https support，**This is a cumbersome thing every time**

so we want to disable networking security restrictions on host app then facilitate the development process
and then it's not on flutter module，that config will not import to original project with flutter module project

Please think about the convenience proposal, or do you have a better way to modify the host app to provide http access every time?

**Comment by gaobin881201** [comment]
I need this function

**Comment by gaobin881201** [comment]
I need this feature

**Comment by jmagman** [comment]
`http` instead of `https` access isn't something we want to imply users should add to any part of their app (especially since the Info.plist change you added to https://github.com/flutter/flutter/pull/79435 would actually fail an app store submission for most developers).  There are all kinds of things an app may need to add to their `AndroidManifest.xml`, `Info.plist`, entitlements, etc, and we can't just add all possible permutations to the default template.  Most users never need to change anything about the project.

The platform module app is supposed to be just a little bootstrap app to get you started.  There's nothing particularly special about it, it's mostly an empty iOS/Android project.  If you don't want to test your module in your full host app, I suggest making a very simple version of the host app that is mostly an empty iOS/Android project that does nothing except start the Flutter view.  You can then edit this all you want.

There's more conversation in https://github.com/flutter/flutter/issues/32989 and https://github.com/flutter/flutter/issues/52496.
