### ISSUE TITLE
Presubmit tasks don't appear to be running if PR is opened while build is running.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#79458]
I opened a PR to fix the broken build, but after several minutes there were still no presubmit tasks besides the flutter build check: https://github.com/flutter/flutter/pull/79456

Is this a regression from switch to webhooks? Postsubmit scheduling seems to work just fine, and PRs that were opened before the build went red also had presubmits scheduler.

@CaseyHillers 

![2021-03-31](https://user-images.githubusercontent.com/8975114/113168065-29da7900-91f9-11eb-8c04-e9879aea0736.png)

**Comment by jonahwilliams** [comment]
Maybe It was just delayed/I caught some deploy window?

**Comment by CaseyHillers** [comment]
Thanks Jonah for filing this! The time window does conflict with the latest Cocoon deployment (starts at 8 AM PST, and rolls out between 8:10 AM - 8:20 AM)

The timeline for this bug seems to be:
1. PR created at 8:08 AM
2. Cocoon deploy rolls out right here, causing 502 on github notification for ~10 seconds
3. PR description edited at 8:12 AM

**Comment by CaseyHillers** [comment]
@keyonghan does the timeline sound right? Should we dedupe this against a general issue of ensuring LUCI presubmit checks are run against PRs?

**Comment by keyonghan** [comment]
All checks were refreshed on that PR at this moment.
It looks to me that presubmit tasks were triggered successfully first, then cocoon was rolling out a new version (causing a couple of minutes delay), later on the new cocoon deployment refreshed task statuses back to github.

Created https://github.com/flutter/flutter/issues/79464 to track, and closing here.
