### ISSUE TITLE
First hot reload does too much reloading

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7946]
The first hot reload after a Run/Debug does a bunch of reloading even if you don't change anything in-between starting the app and reloading:

```
Reloaded in 1474ms.
Reloaded 389 of 405 libraries.
```

This issue occurs on Android simulator, but not iOS simulator.

Overall, this is a confusing user experience, and I'm concerned it can contribute to developers building a lack of trust in the robustness of hot reload, and for that reason would be great to fix.

**Comment by johnmccutchan** [comment]
Context here:

In the past we had the loader and when a Flutter application booted up the loader would be displayed until all the sources are copied. After this the loader would be killed and the application would be launched from sources on the device.

Having a loader was slower and ugly. Developers would have to wait seconds (!) before their application would appear on the device. 

In order to kill the loader, I made the VM capable of reloading on top of a script snapshot. So the application would run immediately from a script snapshot and then on the first reload we would use the sources on the device. 

When switching from the snapshot to the sources we can't know what has changed and have to assume everything is dirty, and we end up reloading all of the program's libraries (405 - 389 = 16 dart: libraries).

The obvious way to fix this bug is to bring the loader back, that will make the first reload only reload changed libraries.

We probably don't want to bring the loader back so we need a better way of knowing which sources files were changed *after* the script snapshot was generated (both of these happen on the host system). This is racy and difficult to get precise. If we think a library hasn't changed when it has the program can get into a weird state.

A workable solution: Flutter tools can timestamp all sources files fed into the script snapshot and then maintain the set of files that have changed since then. This set would need to be passed to the VM on the first reload.

**Comment by Hixie** [comment]
How much of this work can we do on the device while the app is running? Could we wait for the first few seconds of idleness on the device and do it then, silently?

**Comment by johnmccutchan** [comment]
@Hixie The issue there is that at the moment we do the auto-initial-reload we may have bad/weird sources and we break the application. We might be able to get the VM to extract the script snapshot sources onto the disk in the same layout as DevFS will use and then reload from the extracted sources (known good enough to get the app running)

**Comment by Hixie** [comment]
Fair enough.

In that case I suggest that for the first hot reload, we replace the message with "Initialising hot reload subsystem, please stand by...", to set the right expectations.

**Comment by johnmccutchan** [comment]
https://github.com/flutter/flutter/pull/9418

^--- changes the message.

**Comment by mit-mit** [comment]
Moving to M4 now that we have a better message in the tool.

**Comment by a-siva** [comment]
This will get fixed when we switch to using the new front end. The workflow is a bit different whenusing the new pipeline, the app is incrementally compiled on the host and the resulting kernel file is pushed to the device. The engine then reloads this new incremental kernel file. So this notion of treating all source files as new after they are pushed to the device will not be there.
(assigning this bug to @aam as he has wired the new pipeline path for hot reload).

**Comment by mit-mit** [comment]
Great news, thanks :-)

**Comment by zoechi** [comment]
Is there still work to do? #13699 was merged a year ago.

**Comment by a-siva** [comment]
Closing this issue as we have migrated to Dart 2.
