### ISSUE TITLE
Installing specific flavor via `flutter install` command.

### ISSUE THREAD

**Issue by piedcipher** [flutter/flutter#79761]
There is no `--flavor` argument for `flutter install` command. How can I install a specific flavor via `flutter install` command?

**Comment by pedromassangocode** [comment]
Hi @piedcipher 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by piedcipher** [comment]
Don't close the issue right away!! There is no ``--flavor`` option for command.

**Comment by piedcipher** [comment]
I used `gradlew` to do this. Also, don't close the issues @pedromassango :unamused:

**Comment by piedcipher** [comment]
@pedromassangocode re-open this issue. This is an issue. Flutter run command has a switch to provider flavor where as Flutter install command doesn't have that.

**Comment by pedromassangocode** [comment]
> @pedromassangocode re-open this issue. This is an issue.

This issue seems to ask for questions in how to use specific Flutter features, if you believe that this is not currently supported by Flutter then please file a new issue as a feature proposal and make sure to fill the issue template. Bellow is the option you have to choose while opening a new issue: 

![Screen Shot 2021-04-14 at 11 16 51](https://user-images.githubusercontent.com/67424416/114694904-ed3b7100-9d12-11eb-95ee-85111fc49873.png)
