### ISSUE TITLE
Add the ability to disable ContextMenu in TextFields

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#79796]
In the case where we have implemented a consistent ContextMenu theme across the entire app, we would like to disable the built-in context menu and use our own instead. Currently the TextField widget swallows the RightClick event, so there is no way for us to override it.  See this comment for more specifics: https://github.com/flutter/flutter/issues/74255#issuecomment-790810610

@justinmc

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
As discussed in https://github.com/flutter/flutter/issues/74255#issuecomment-790810610, I agree with the ability to disable the desktop context menus for now.  Long term, we'd additionally like to make the built-in desktop context menus fully customizable, which is discussed in other issues like https://github.com/flutter/flutter/issues/74255.

**Comment by justinmc** [comment]
To achieve this I think we'd need to remove the secondary tap handlers in TextSelectionGestureDetector [here](https://github.com/flutter/flutter/blob/7b251f5f37b2b10334752da6bed1f5b136f0cb4b/packages/flutter/lib/src/widgets/text_selection.dart#L1233).

**Comment by esDotDev** [comment]
Note that this also seems to be happening now with SelectableText as well.

**Comment by csells** [comment]
cc @justinmc upon his return

**Comment by justinmc** [comment]
## Hacky current solution

Right now, if you want to disable the right click menu in TextField, it's not easy and you'll have to copy a bunch of internal Flutter code.  This is how you could do it:

  1. Copy the [text_field.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_field.dart) file into your own project, renaming it to something new (like MyTextField).  Alternatively, modify your copy of the Flutter source code.
  2. Override the TextSelectionGestureDetectorBuilder in that file [here](https://github.com/flutter/flutter/blob/1e2753b7411712af314f191b0bb636182b83036b/packages/flutter/lib/src/material/text_field.dart#L40) so that onSecondaryTap and onSecondaryTapDown are noops.

```dart
  @override
  void onSecondaryTap() {}

  @override
  void onSecondaryTapDown(TapDownDetails details) {}
```

The result will be that right clicking will have no effect for all instances of the modified TextField.

## Can we add a parameter to do this?
It might not be a good idea to add a parameter to switch off the right click menu like this.  Currently, these menus are very early and not finalized.  This parameter would be a hack and would need to be deprecated and removed later as work continues on these menus.

## Long term solution
Long term, the desktop right click menus should be a global menu not specific to text.  They should be able to be used anywhere in your app, and they should be fully customizable.  This would make it easy to disable them as desired in this issue, while also fixing many other problems they have right now.

## From here
I think we should move towards the long term solution and resist adding a parameter for now.  However, if someone has a strong case for being unable to use the hacky solution and needs a parameter in the near-term, then maybe we can reconsider.

**Comment by esDotDev** [comment]
Hey @justinmc I kinda missed this, just looping back to it now. 

So for me, this is really frustrating. Flutter is such an easy and productive framework to build things in, but then it does stuff like this that is just inexplicable, shooting itself right in the foot. 

Like, we had perfectly functional context menus, I spend a few days making them fully featured, beautiful, copying behavior from Windows/MacOS, polishing everything exactly as my designer wants. And then one day, Flutter just comes along and breaks them, replacing them with uglier, less functional versions. And then just leaves it in this broken state. Never thinking to itself, "_hey if we're going to consume a bunch of gesture events, and show a non-styleable menu, we obviously need to allow developers to disable it_". 

I have created a lib here, which imo really eliminates the need for this to be native at all (it's actually not a bid deal if you can't overflow the window chromem with the right offset-logic): https://pub.dev/packages/context_menus but I think it remains partially broken / useless because of this issue. 

I do appreciate the workaround, the obvious reason this is not great is because it immediately adds a significant chunk of Technical Debt in any project employs it. `TextField` is now out of sync with future fixes, team members need to be made aware of this special case, it becomes very easy for some team member to accidentally use the wrong TextField. What about selectableText?

**Comment by esDotDev** [comment]
If there are other more important priorities than desktop context menu, can we at least allow us to turn off the baked in stuff?

This package is 200LOC at it's core, and does everything we need for beautiful robust context menus.
https://pub.dev/packages/context_menus
![0tVhpe5OY2](https://user-images.githubusercontent.com/736973/158074623-053821cf-6f8a-4da9-94a6-9f8b1200cc7b.gif)

But it's basically unusable, because Flutter is implementing a partially baked implementation of its own, with no means to turn it off. 

It feels like we need some movement here, as Flutter Desktop and Web is becoming more stable and used more frequently, the current context-menu solution is really not good enough.

**Comment by justinmc** [comment]
With https://github.com/flutter/flutter/pull/107193 it should be possible to disable the context menu (except on web).

**Comment by justinmc** [comment]
https://github.com/flutter/flutter/pull/107193 has been merged, so you can now do this to disable context menus:

```dart
TextField(
  contextMenuBuilder: null,
),
```

On web we'll need to wait for a solution to https://github.com/flutter/flutter/issues/78671 before this can work.
