### ISSUE TITLE
 Is Dart a single threaded language?

### ISSUE THREAD

**Issue by CoderJackySong** [flutter/flutter#79948]
I have been learning Flutter recently and I have a question, is Dart a single threaded language? I would appreciate it if you could give me a reply.

**Comment by iapicca** [comment]
@CoderJackySong 
- [flutter](https://flutter.dev/) != [dart](https://dart.dev/), issue regarding dart should be open in correct [repo](https://github.com/dart-lang/sdk/issues)

- this seems a question rather than an issue you may want to ask on [stackoverflow](https://stackoverflow.com/tags/flutter), [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

regardless

> Is Dart a single threaded language?

no it is not, you may want to look into [isolates](https://api.dart.dev/stable/2.10.5/dart-isolate/Isolate-class.html)

**Comment by TahaTesser** [comment]
Hi @CoderJackySong 
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by CoderJackySong** [comment]
@iapicca @TahaTesser Thank you very much for your reply.
