### ISSUE TITLE
Widget Inspector tests are not hermetic

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#79962]
The widget inspector tests are sharing state between test cases, which makes them non-hermetic. It appears that mainly the selection [1] is not cleared between tests and a previous selection in influencing the behavior of subsequent tests. 

This can be observed in https://github.com/flutter/flutter/pull/79958, where I am explicitly clearing the state between tests by instantiating a fresh WidgetInspectorService. 

I've looked at the tests that are failing now, but it is actually not clear to me what these tests are supposed to test.

@jacob314 Can somebody with more knowledge of the widget inspector take a look?

For context: This was discovered while working on https://github.com/flutter/flutter/pull/79957.

[1] https://master-api.flutter.dev/flutter/widgets/WidgetInspectorService/selection.html

**Comment by jacob314** [comment]
Long term we should use WeakRef objects to make InspectorRef objects play nicer with GCed objects.
https://github.com/dart-lang/sdk/issues/45455
Short term let me fix the inspector tests so they don't blow up in this case. Should be easy as I expect we are just failing because of a poorly written test that is using an old widget tree instead of a new one by mistake.

**Comment by goderbauer** [comment]
@jacob314 Is there more to do, or should we close this as fixed now?

**Comment by jacob314** [comment]
No more to do.
