### ISSUE TITLE
flutter update-packages times out after 5 mins

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#80066]
We started adding timeouts to different steps in the test process and "flutter update-packages" has been timing out frequently after 5 mins when that step takes ~2 mins in average:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20SDK%20Drone/71021?

**Comment by Hixie** [comment]
Please don't add timeouts. That will just make things flake more. Sometimes it will take more than 2 minutes because pub is slow.

**Comment by godofredoc** [comment]
What we are trying to prevent with the timeouts is tasks that usually run in <5 mins to timeout after 45 mins because "flutter update-packages" was stuck. Just letting them run until the task timeouts increases the overall commit validation time to the max task timeout(currently 1 hour).

**Comment by Hixie** [comment]
If a task takes _t_ seconds 80% of the time, and we therefore apply a timeout of _t_ seconds to that task, we're saying we want it to fail 20% of the time.

Basically you have two choices basically for how to handle hangs ("foo got stuck" behaviour) in tests:
* make non-hanging but slow runs into flakes (by having timeouts that get hit when the task is taking slightly longer than the timeout).
* have the hang take a long time to fail (because there's only one timeout and it's big).

Now, if `flutter update-packages` is actually getting stuck regularly, that's something we should file a bug on and try to debug, because that's a legitimate problem. However, setting a timeout on it just means we're going to have more flakes.

**Comment by godofredoc** [comment]
This is related to the "connection reset by peer" problem.

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/recipes/+/13502 to remove the temporary timeouts.
