### ISSUE TITLE
Application UI is completely distorted when Mobile Phone Display Text Size is enlarged - Not Responsive

### ISSUE THREAD

**Issue by DishitaShah** [flutter/flutter#80102]
**When the user increases the Display Font Size of mobile phone Android/iOS the application UI is completed broken.**

**Requirement: I need to fix the size of all the TextFields though the user increases the display font size. (Give no support for Accessibility)**
Note: I have already given "fontSize" to my textfields, though it enlarges when font size is increase.

Steps to reproduce it:
iOS Mobile: Settings -> Accessibilities -> Display and Text Size -> Large Text -> On -> Maximum
Android Mobile: Settings -> Display -> Font Size -> Huge

Please find the attached files to get the highlight of the issue.

| Preview | Preview |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/22871294/114140321-bb4e9700-992d-11eb-8f09-d32f4d7570cd.png" height="450" /> | <img src="https://user-images.githubusercontent.com/22871294/114140329-bd185a80-992d-11eb-8213-12b36d54f21b.png" height="450" />

Please let me know if any solution prevails.
Help will be appreciated.

**Here is my flutter doctor -v** 

<details> 
<summary>flutter doctor -v</summary> 

```bash
Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-arm, locale en-IN)
    • Flutter version 1.22.6 at /Users/sunflower/Documents/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sunflower/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/sunflower/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```
	
</details>

**Comment by DishitaShah** [comment]
**Things I found:**
1. RichText does not scale to the size of the font selected. (Don't know how)
2. Text scales the font according to mobile phone selected fonts. (Though font size is given)

**Comment by TahaTesser** [comment]
Hi @DishitaShah 
UI responsiveness depends on the layout you create, if you don't give any flexibility to adapt to different sizes, you will end up with results like yours Here is a quick demo of the gallery app in `small` and `very large` text on the same device

| Small | large |
| --------------- | --------------- |
![Screenshot_2021-04-09-17-31-23-80_551cc8ea80df0491c602715222aaf8f4](https://user-images.githubusercontent.com/48603081/114196466-10080700-995a-11eb-9e76-c8c8bde40230.jpg) | ![Screenshot_2021-04-09-17-31-53-09_551cc8ea80df0491c602715222aaf8f4](https://user-images.githubusercontent.com/48603081/114196471-11393400-995a-11eb-9b0f-d6edefe845c1.jpg)

Instead of using hardcoded text sizes, you should theme-based text size and keep your UI flexible enough to adjust on different screen sizes and font sizes set by the system. There are more things to consider when developing a production app but this is the place to get those techniques. 


Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
