### ISSUE TITLE
Runner.xcodeproj vs Runner.xcworkspace

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8010]
There's a Runner.xcodeproj and a Pods/Pods.xcodeproj now. Should we change all the documentations that refers to Runner.xcodeproj to refer to Runner.xcworkspace instead so that the user can build directly from xcode if needed?

cc @cbracken

**Comment by chinmaygarde** [comment]
Yeah. The workspace is the way to go.

**Comment by xster** [comment]
Cool, thanks

**Comment by kasperl** [comment]
Just ran into this issue too. I had an issue running on an attached device (not enough device management trust), so `flutter tools` suggested opening `Runner.xcodeproj` and running from within there. That failed because of linking issues with `libPods-Runner.a`. Opening `Runner.xcworkspace` instead made it work. Thanks to @jakobr-google for unblocking me here :)
