### ISSUE TITLE
Cannot connect to VM Service via IPv6 loopback in cloud environment

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#80138]
Original issue: dart-lang/sdk#45365.

flutter_tools is trying to connect to DWDS/DDS in a cloud environment via `[::1]` which results in a `Cannot assign requested address` error. Updating [this URI](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L672) in Flutter tools to have a `localhost` host seems to allow for the connection to succeed.

cc @DanTup @jonahwilliams

**Comment by DanTup** [comment]
I'd previously tried to repro this with some simple scripts (just hosting and connecting to a websocket) but failed (it seemed to work). I did have some issues connecting from Dart-Code which [I've worked around](https://github.com/Dart-Code/Dart-Code/blob/7a64a2c916b960a8223d226de6ab5b0c2a7d9086/src/shared/vscode/utils.ts#L130-L132) for now by replacing `[::]` with `localhost` when connecting there, but I don't fully understand why it failed.

I have a weird recollection of something in the past (I can't remember if it was in Dart/Flutter or a previous system I worked on), where `localhost` would resolve to both `127.0.0.1` and `::`, and some processes would get one and others another. I wonder if something similar may be happening here. It'd be interesting to know if using 127.0.0.1 works, and if so, where the IPv6 loopback IP is coming from. I'll try to do some more testing.

**Comment by DanTup** [comment]
Replacing the hostname with `127.0.0.1` also works. The `/etc/hosts` file in this environment does include both IPs for `localhost`:

```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
```

This definitely sounds something like the issue described above... The service is binding to `localhost` that was resolved as `127.0.0.1` but in flutter_tool it's ended up resolving to its IPv6 address. I found the original place this came up - it was at https://github.com/dart-lang/webdev/issues/233. My nodeJS debugger was resolving as IPv4 but the service was only bound to IPv6. This seems like the opposite problem now.

I see in flutter_tools there's an `--ipv6` flag to enable IPv6 support, but that's not being passed here, so I wonder where the ipv6 loopback address is coming from that's being used here.

**Comment by DanTup** [comment]
Ok, I think I've tracked this down. I'm passing `--web-hostname any` to Flutter (IIRC this is because we need Flutter to bind to all network IPs and not just the loopback, so we can connect from the proxy). This is then passed to DWDS, which is passed to `HttpMultiServer`:

https://github.com/dart-lang/webdev/blob/658f69284cab7b025a4742f1039ced6e16cd6143/dwds/lib/src/services/debug_service.dart#L259-L263

However, reading `server.address.host` then returns the IPv6 loopback IP which is _not_ actually bound, so the connection fails.

I can repro this without Flutter, DDS or DWDS with the following code:

## Works with localhost

```dart
import 'dart:convert';
import 'dart:io';

import 'package:http_multi_server/http_multi_server.dart';

main() async {
  var server = await HttpMultiServer.bind('any', 0);
  print('Listening at ${server.address.host}:${server.port}!');
  server.listen((req) { 
    req.response.write('Hello, world!');
    req.response.close();
  });

  var client = new HttpClient();
  var req = await client.get(server.address.host, server.port, '/');
  var resp = await req.close();
  var output = await resp.toList();
  for (var out in output) {
    print(utf8.decode(out));
  }

  server.close();
}
```

It seems if I pass `any` then it only binds to IPv4, but returns the IPv6 loopback address. However, if I try to bind specifically to IPv6, then I receive the same error as above. So I think `next` may be failing to bind to IPv6 silently, but still returning its address - but the actual problem is that it thinks IPv6 is supported but it actually doesn't work.

So this may be a `HttpMultiServer` issue, or it may be that this environment is weird (looking like IPv6 is supported but not). I'll do some testing to see if I can avoid using `--web-hostname any` as well as track down what's happening in `HttpMultiServer` (and whether it's the environment that's broken).

**Comment by DanTup** [comment]
Ok, it turns out we don't need `--web-hostname any` or `--disable-dds` here now. I'm not sure why we don't need the former, and I think using it is what had led us to need the latter.

So I think this is resolved - though @kevmoo @jakemac53  if my last comment above seems like a bug in HttpMultiServer that should be raised in its repo, let me know. Thanks!

**Comment by DanTup** [comment]
(After discussing with @grouma, this definitely seems like a HttpMultiServer bug so I've filed https://github.com/dart-lang/http_multi_server/issues/35)
