### ISSUE TITLE
[proposal] consider updating milestone flutter version reference

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#80196]
at the moment [milestones](https://github.com/flutter/flutter/milestones) refers to flutter versions between `1.28 `and `1.30`

<details>
<summary>screenshot</summary>

![Screenshot from 2021-04-10 20-14-45](https://user-images.githubusercontent.com/45637986/114278899-867c3600-9a3a-11eb-9301-3e124becb718.png)

</details>

it may need to be updated

**Comment by darshankawar** [comment]
Revisiting this issue, currently it seems there are 2 milestones open:

<img width="900" alt="Screenshot 2023-01-27 at 5 16 12 PM" src="https://user-images.githubusercontent.com/67046386/215079196-5f3548e5-17a5-45a9-8b13-c139336fb06f.png">

So I am wondering if this issue is relevant to be kept open. @iapicca what do you think ?

**Comment by iapicca** [comment]
I feel this issue is superseded
