### ISSUE TITLE
[Web][Scrollbar] show scrollbar on mouse over is not working

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#80262]
## Proposal
Scrollbar will hide automatic
But want to show scrollbar when mouse over at web.
I think this is a natural behavior when scrolling by a user who is using the service from a PC.

Current Scrollbar 

https://user-images.githubusercontent.com/7422251/114370579-991d7900-9bba-11eb-9aae-3f9c660b1e23.mp4

**Comment by pedromassangocode** [comment]
Hi @hatano0x06 
Does the `showTrackOnHover` works for you? See https://master-api.flutter.dev/flutter/material/Scrollbar/showTrackOnHover.html.

**Comment by hatano0x06** [comment]
@pedromassangocode 
I try it but it just work only scrollbar is active

`showTrackOnHover is null`
https://user-images.githubusercontent.com/7422251/114375315-7e013800-9bbf-11eb-8a23-4bcc178dfc90.mp4

`showTrackOnHover is true`
https://user-images.githubusercontent.com/7422251/114375369-88bbcd00-9bbf-11eb-857c-c6fe8e89bde1.mp4

**Comment by pedromassangocode** [comment]
This seems to be what you need to use but it also seems to have a bug here: the scrollbar is not visible on hover.

Cc @Piinks @xu-baolin 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: Text("Home")),
        body: Scrollbar(
          showTrackOnHover: true,
          child: ListView(
            children: [
              Container(
                height: 500,
                width: 200,
                color: Colors.red,
              ),
              Container(
                height: 700,
                color: Colors.blue,
              ),
            ],
          ),
        ),
      )
    );
  }
}

```

</details>

**Comment by Piinks** [comment]
This is not currently supported by the scrollbar. I was actually looking at this last week, and found it is a much more complicated feature to support than I thought. Right now, the Scrollbar is dependent on scroll notifications in order to know where and how to paint itself. Without information on the scrollable, it cannot decide how to paint. If the Scrollable has never scrolled, when you hover over the scrollbar area, it has no idea what to paint yet.

Right now, nothing is even painted since it has no information, so it cannot even detect the mouse hovering. I think we should support this, but we'll need to find a way to inform the Scrollbar without a scroll notification.

We should probably investigate the platforms that this happens on natively as well. On Chrome on Mac, this behavior does not happen.

**Comment by hisaichi5518** [comment]
there is a problem that the scrollbar does not appear even if hover it until you scroll once in Chrome on Mac.

https://user-images.githubusercontent.com/248093/134301635-116d1cf6-4942-47ee-9722-54631a4498f6.mov

**Comment by Piinks** [comment]
We might be able to better implement this now that the Scrollbar is listening to `ScrollMetricsNotification`s.
