### ISSUE TITLE
flutter_driver should be null-safe in stable Flutter 2.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#80293]
Flutter_driver is not yet null-safe in beta/stable.

This is creating all sorts of problems. I'd say flutter_driver is the biggest pain point in null-safety migrations at the moment.

This is related to https://github.com/flutter/flutter/issues/77282

**Comment by jonahwilliams** [comment]
Flutter driver was migrated to null safety in https://github.com/flutter/flutter/pull/74856

This did not make the cut for 2.0, but it will be in the next release. Note that all of the driver runtime code was migrated, so it is still possible to test applications in sound null safety.

**Comment by dnfield** [comment]
For a little more context here: the changes to support flutter_driver would require cherry-picking in changes from other packages as well, and the patch surface is really large.  We had tried to land some of the more risky parts of that change before the 2.0 cut off, which might have made cherry picking this possible. Unfortunately, that attempt to be reverted because it broke debugging in a way that is really hard to write automated tests for. 

We're confident that things work on master/dev/beta, but the cherry pick to move driver with full NNBD migration to stable is actually a fairly large and risky cherry pick. Customers who really need to use an updated driver should switch to the beta channel for now.
