### ISSUE TITLE
buttons `defaultStyleOf` should use splashFactory from theme

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#80391]
currently, instead of using theme's splash factory, buttons hardcode this to InkRipple.splashFactory

https://github.com/flutter/flutter/blob/457985f2900230ba07bd252b05073029862a52a7/packages/flutter/lib/src/material/text_button.dart#L349

**Comment by nt4f04uNd** [comment]
cc @HansMuller

**Comment by nt4f04uNd** [comment]
also, why are `defaultStyleOf` and `themeStyleOf` not static `@factory`s? they make you to instantiate an additional button class for no reason

**Comment by HansMuller** [comment]
The default splash factory for the new Material button widgets is InkRipple because that's the correct default per the Material Design spec. Apps can override it per button or per button class using he corresponding themes.

The protected defaultStyleOf and themeStyleOf methods are protected because they're only intended for subclasses. Despite the intriguing names, they're not intended to support statically looking up default property values.  It would be generally useful if Material widgets could statically reveal their defaults, which I assume is what you're implying. Unfortunately, that's a difficult request, because the defaults can have complex dependencies on the theme's brightness, and the widget's state. For now, one-off buttons that are intended to share defaults with the Material buttons, are most easily constructed by subclassing.

**Comment by nt4f04uNd** [comment]
@HansMuller ok I missed that default theme value is InkSplash.splashFactory. It is planned to change default value to InkRipple.splashFactory (see https://github.com/flutter/flutter/issues/73163). Could you reopen this, so we can revisit it after that change?

About defaultStyleOf - I get the point about subclassing. Though if method is static, nothing prevents from fetching defaults from context, I'm still pretty much sure we could add a static method for each of the existing button class in the framework that would expose defaults, without touching defaultStyleOf. Though the naming is getting kinda confusing with this
