### ISSUE TITLE
[BUG] Double typing when using inputFormatter

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#80569]
input double values when typing. The issue was on some keyboards. ( latest keyboard in MI / ONE PLUS or custom keyboard -  [sample custom keyboard app](https://play.google.com/store/apps/details?id=lk.bhasha.helakuru&hl=en_US&gl=US))

https://user-images.githubusercontent.com/34953062/114861278-a8930100-9e0a-11eb-976b-4872cfab8578.mp4

Code

```
TextFormField(
          inputFormatters: [UpperCaseTextFormatter()]
),

class UpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    return TextEditingValue(
      text: newValue.text?.toUpperCase(),
      selection: newValue.selection,
    );
  }
}
```

Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
```

**Comment by bhanuka96** [comment]
Temporary Solution

Downgrade from `2.0.4` to `1.22.6`

**Comment by pedromassangocode** [comment]
Hi @bhanuka96 
This seems to be caused by your implementation, you are not updating the `compose` property.

I've installed the keyboard app and by updating the formatter to use the one bellow it works as expected:

```dart
class UpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    return newValue.copyWith(
      text: newValue.text.toUpperCase()
    );
  }
}
```

**Comment by bhanuka96** [comment]
@pedromassangocode Thanks. I will check and update you now. can you install this plugin and add their mask too? because it also has this issue. they said the issue is on flutter. because plugin mask issue also fixed when downgrading flutter SDK.

[easy_mask](https://pub.dev/packages/easy_mask)

CODE
```
  final maskFormatter = TextInputMask(mask: 'AAAAA-9999-A');

 inputFormatters: [maskFormatter],
```

**Comment by bhanuka96** [comment]
@pedromassangocode Thanks. The issue is fixed. can you install that plugin and check it?

**Comment by pedromassangocode** [comment]
Good to know the issue is fixed.


> can you install this plugin and add their mask too? because it also has this issue. they said the issue is on flutter.

If the issue is not reproducible without that plugin/package then the issue is not caused by Flutter. Flutter changes a lot because of different bug fixes and new features and package owners should update their own packages to match the latest updates made into Flutter.

Just did a quick look and it seems that that package is not updating the composing range as well (I may be wrong though):
https://github.com/danilocoppi/flutter-textfield-mask/blob/562337ed464405b7ca5dfcaffeec799c0fc0e4c5/lib/src/text_input_mask.dart#L62-L68

If you are able to reproduce the issue without that package feel free to file a new issue about that.
Thank you
