### ISSUE TITLE
 Scrollbar: radius → Radius? "The color of the scrollbar thumb."

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#80726]
Hi,

I think a property named radius should not be described with color.
Please check your documentation at https://api.flutter.dev/flutter/material/Scrollbar-class.html.

By the way, is the apperaing animation of the scroll thumb disabalable?

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
The documentation has already been fixed on the master branch. https://master-api.flutter.dev/flutter/material/Scrollbar-class.html

> By the way, is the apperaing animation of the scroll thumb disabalable?

 Do you mean to not have the Scrollbar disappear? Scrollbar.isAlwaysShown may be what you are looking for. :) 

Closing as fixed.

**Comment by Wissperwind** [comment]
Hi,
No, I don't want to make the scrollbar dissappear. I have set isAlwaysShow to true.
My problem is, that if I call set State in the statefull widget containing the scrollbar, the "spawn" animation of the scrollbar is played again. So the user notices that something is refreshed. I would like to disable the spawn animation so that the scroll thumb is displayed instately.

**Comment by Piinks** [comment]
I think you could place your scrollbar above your stateful widget then. The Scrollbar can be higher up in your widget tree, since it listens for scroll notifications in order to lay out.
It is hard to say without knowing how you have composed your widgets, especially how you are managing your state. I would recommend posting about this on stack overflow.
