### ISSUE TITLE
TextFields backspace and tab functionality corrupts when keyboard language change inside whole flutter desktop windows app

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#80791]

**Comment by darshankawar** [comment]
@Ali-Fadaei 
I believe you've opened a similar issue, https://github.com/flutter/flutter/issues/80787
I suggest you to update the original issue with this use case since it looks to be similar to the one mentioned in 80787.
Closing this as self-duplicate. If you disagree or think this is a different issue than 80787, write in comments and I'll reopen it.
Thanks.
