### ISSUE TITLE
Show error if Material widgets are used without uses-material-design: true

### ISSUE THREAD

**Issue by jakobr-google** [flutter/flutter#8086]
Currently, if you use Material widgets in your app, but haven't specified `uses-material-design: true` in the `flutter:` section of `pubspec.yaml`, you get the missing glyph icon instead of the Material icons, since the Material font is not included in the app bundle (#7039).

It would be nice if the framework could throw a warning or error letting users know what's going on, and how to fix it.

**Comment by Hixie** [comment]
Ideally, the Paragraph class would have a callback that fires when the selected font didn't have the glyph.
cc @jason-simmons @chinmaygarde @xster who have looked at the font code / Paragraph before or now.

**Comment by Hixie** [comment]
We really should generalise the whole `uses-material-design` thing anyway.

**Comment by Hixie** [comment]
See also #12569 which would make the material icons font into a package rather than a magic feature of the tool.

Moving this out to beyond m3 since it doesn't currently fit our priorities, but it is something we will fix in due course. Please let us know if this is a priority for you and you can't work around it.

**Comment by xster** [comment]
I'm just gonna close this. The fix will just be to do #12569
