### ISSUE TITLE
About FlutterEngineGroup

### ISSUE THREAD

**Issue by yaoming04111** [flutter/flutter#80870]
你好。目前我遇到一个疑惑。因为我的项目是 flutter 调用原生组件 而非 原生组件 调用flutter 组件
那么我如果想要使用 FlutterEngineGroup 的话 要如何来处理呢。

**Comment by TahaTesser** [comment]
Hi @yaoming04111 
Translated 
`Hello there. Currently, I have a doubt. Because my project uses flutter to call native components instead of native components to call flutter components
So what should I do if I want to use FlutterEngineGroup.`


It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
