### ISSUE TITLE
License script is unreasonably slow

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#8106]
It takes around 25 minutes to run the license script on my machine. Updating the expectation files after a roll requires running this twice, then waiting for a third run on Travis to go green. I can build the engine from scratch in only 2 minutes; merely checking the licenses should be faster than that.

**Comment by chinmaygarde** [comment]
I agree that this is an extremely frustrating part of working on the engine. The situation is worse if there are multiple PRs in flight. There is no way to update the licenses for each of them simultaneously such that the Travis jobs pass, and, have the commits be readily mergeable (because the first one to land causes merge conflicts in the rest of the patches). I also need to have a dedicated Ubiquity instance just to update the licenses because the tree needs to be clean. And, if someone else commits an update to the licenses file after I update the PR to make Travis pass but before I land the commit, there is a merge conflict and I have to start again.

A few possible solutions:
* Maintain a separate list of licenses per GN target. Then run something like `gn desc directory :build` to obtain the list of targets being actually built and generate the licenses file for those targets. If we add a new target without adding a license for it, `flutter/tools/gn` itself can quit with an error. I don't know if we need to check every file in each target to see if its header contains a license block that matches what its targets LICENSE file says.
* Run the license script fewer times. Maybe on every engine roll into the framework. That way, multiple PRs can be under review and be mergeable simultaneously.
* Make the license script faster. Assumes that the only thing wrong with our current brute force approach is that we are not applying enough of said force. #NotSwoleEnough.
  * I think @jason-simmons already attempted this too. He may have some ideas that make the entire process fast enough to not be noticeable.

Any more ideas?

**Comment by abarth** [comment]
We could skip running the script on files in `//flutter`.  That would make it easier to have changes in flight to that directory (but probably won't speed it up too much).

**Comment by abarth** [comment]
We could produce subdirectory summaries with some sort of key.  For example, we could avoid crawling the whole Android SDK if the version hash of the SDK is the same as what we crawled last time.

**Comment by abarth** [comment]
(Same with other third_party dependendencies)

**Comment by Hixie** [comment]
The script itself is ridiculously poorly written. It just applies literally hundreds of absurdly complicated regular expressions to tens of thousands of files, all in one thread. A more clever approach could certainly make things better. Furthermore, since we have the "correct answer" now, one could write a new script and easily verify that it is correct by just running it against the repo and seeing if it gets exactly the same results.

Any approach that works by splitting the work would need a secondary merge step that takes the various subparts and creates a new output file. (That should be fine, I'm just making sure y'all are aware!)

We do need to run it on files in `//flutter`. There's dozens of different copyrights in there.

**Comment by Hixie** [comment]
Jason checked in a change that should dramatically help with this, so I'm closing this bug.
