### ISSUE TITLE
Allow users to pass in Xcode build settings as env variables to "flutter build macos" FLUTTER_XCODE_

### ISSUE THREAD

**Issue by renancaraujo** [flutter/flutter#81377]
This is a feature request on the flutter_tools package. 

## Use case

When running `flutter build macos` one may need to specify an [Xcode build setting](https://xcodebuildsettings.com/). 

Some flutter commands already allow the specification via a prefixed model of environment variables, as defined on https://github.com/flutter/flutter/pull/43553.

Weirdly, among these commands, we have flutter clean (that already affects the macOS project) but not `flutter build macos`.

This is vaguely related to #49378.

## Proposal

Allow `flutter build macos` to fetch for `FLUTTER_XCODE_` env vars.

**Comment by renancaraujo** [comment]
Added a PR for this: https://github.com/flutter/flutter/pull/81384

**Comment by jmagman** [comment]
@renancaraujo https://github.com/flutter/flutter/pull/81384 was reverted at https://github.com/flutter/flutter/pull/82004 due to post-submission test failures.

Error log here:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847932325253177104/+/u/run_hot_mode_dev_cycle_macos_target__benchmark/stdout?format=raw
```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] error: Pods-Runner does not support provisioning profiles. Pods-Runner does not support provisioning profiles, but provisioning profile match Development * has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Pods-Runner' from project 'Pods')
```

The Flutter CI sets iOS `FLUTTER_XCODE_` environment variables for iOS signing:
```
  FLUTTER_XCODE_CODE_SIGN_STYLE: Manual
  FLUTTER_XCODE_DEVELOPMENT_TEAM: S8QB4VV633
  FLUTTER_XCODE_PROVISIONING_PROFILE_SPECIFIER: match Development *
```
And I totally forgot that the macOS `FLUTTER_XCODE_` feature was already implemented, but was removed in an extremely lame workaround https://github.com/flutter/flutter/pull/71860 for the same reason.
I just reopened https://github.com/flutter/flutter/issues/71232 to properly fix the issue on the CocoaPods side.  Relanding #81384 will be blocked on that work.

Sorry for not remembering the details of this, and thank you for your contribution and patience.

**Comment by renancaraujo** [comment]
Oh heck, Cant we use `FLUTTER_XCODE_MACOS` or something like that?

**Comment by jmagman** [comment]
I'd rather fix the cocoapods issue. I'll try to get to it on Monday.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/82048 was merged.  Waiting to confirm all the tests are happy in post-submit.

@renancaraujo would you mind putting out https://github.com/flutter/flutter/pull/81384 for review again on top of that commit?

**Comment by jmagman** [comment]
Reland https://github.com/flutter/flutter/pull/82298 merged.  Looking good so far, `hot_mode_dev_cycle_macos_target__benchmark` passed (the post-submit test that caused the revert):  https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847483377804790128/+/u/run_hot_mode_dev_cycle_macos_target__benchmark/stdout.

I'll close this when it all goes green.

**Comment by jmagman** [comment]
Everything passed.  Thanks again, @renancaraujo.
