### ISSUE TITLE
Sending test notification from Firebase Messaging console crashes the app

### ISSUE THREAD

**Issue by arjinakgul** [flutter/flutter#81375]
I try to send test notification manually from Firebase Messaging console. After sending the notification I get the following error.

Here I paste the output that I took after running "flutter doctor -v"

**Comment by TahaTesser** [comment]
Hi @arjinakgul 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you
