### ISSUE TITLE
[proposal] Add borderColor to Checkbox

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#81380]
Changing the Color of the border of a CheckBox 

having a border color for the different states

  ///  * [MaterialState.selected].
  ///  * [MaterialState.hovered].
  ///  * [MaterialState.focused].
  ///  * [MaterialState.disabled].

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/53420

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/70171 added support for specifying a Checkbox's border and shape. The border probably should have been a `MaterialStateProperty<BorderSide>`, so that (as @chrisDK1977 points out) you could have a different border depending on the checkbox's state. We could retrofit the API by adding support for MaterialStateBorderSide.
