### ISSUE TITLE
“Some input files use or override a deprecated API” Error

### ISSUE THREAD

**Issue by regenin** [flutter/flutter#81389]
I just created an app bundle and I encountered such an error.
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

I guess this is the code that gives error.
`var coinList = List<CoinDeepInfo>();`

I created a bundle for trial purposes, can't I upload it to playstore because it gives an error? How can I fix this error? I don't know how to use the new code version.

**Comment by darshankawar** [comment]
@regenin 
They seem to be warning than errors and indicates there are some functions which are deprecated. Check if any of the plugins you are using which needs upgrade that may get rid of these messages. Also the IDE helps to identify these and fixes to make.

You may still upload it to playstore since they are not errors.
Search over StackOverflow to get more details on it.

I am going ahead and closing this, as this issue seems more of a question rather than bug. If you disagree, write in comments and I'll reopen it.
Thanks.
