### ISSUE TITLE
Deprecate `dev/benchmarks/microbenchmarks`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#81394]
Previously I've added my own performance tests, this time around I decided to try to get my tests integrated with microbenchmarks and found it is more difficult to work with microbenchmarks instead of just making your own test harness.

Reasons why:
1) The microbenchmarks take a long time to execute and are executed serially.  This means you have to comment out tests in code to actually get a decent workflow.
2) The test harness relies on the `target` parameter to flutter run which makes debugging the tests more difficult since you can just open them up in Android Studio or Xcode and execute them.
3) It's difficult to use plugins with them (possibly an edge case for my tests).  The embedder API was never upgraded to v2 for android and there is something funky about the test harness that is messing up platform channels communication.

I recommend we just encourage people to make their own test harness and think of ways to make that easier instead of adding any new work to the microbenchmarks test harness.  Maybe we can think of ways to make creating test harnesses easier.

cc @dnfield @goderbauer

**Comment by dnfield** [comment]
I'm not really clear what deprecating these would mean. We don't want to lose continuity of the benchmarks we track, and we don't want a rewrite to potentially alter the performance characteristics of the application.

If you can do things to improve the workflow you desire, I think we should do it. If we can't improve it without breaking it or doing a drastic rewrite, adding a new harness is fine too.

The microbenchmarks harness has been pretty reliable and unflaky. Migrating it to the v2 embedding should be pretty uncontrversial, but so should adding a new harness that uses the v2 embedding to test whatever it is you specifically want to test.

**Comment by goderbauer** [comment]
If we were to deprecate them, what would the replacement look like? As far as I can tell, these have been running pretty reliably. Maybe we can just iterate on them to improve the workflow?

**Comment by gaaclarke** [comment]
My proposal is to add a README.md in microbenchmarks/ that says they are deprecated and not accept any new submissions.  Instead we'd encourage people writing new microbechmarks to make separate test harnesses for all the reasons I mentioned above.  We can link to that recommendation in the microbenchmark's readme and the devicelab readme.

I think the microbenchmarks approach is flawed, we should make creating new test harnesses easier instead of encouraging people to add more tests to test harnesses that launch multiple apps serially like microbenchmarks does.  It doesn't scale (can't be parallelized by the server farm) and is harder to develop (as per the points in the description).

**Comment by dnfield** [comment]
It could be paralellized by just moving the `_runMicrobenchmark` out of the task and into the builder itself. We haven't needed to do that because these tests run quickly enough together, but we certainly could.

My understanding of running them independently is to make sure that state from one test can't pollute another test. We also haven't really added a ton of microbenchmarks either.

I think if we have a harness that's clearly better and easy to use, and we believe it would be more work to refactor the existing microbenchmarks than to just use that harness, we should definitely do what you're suggesting.

**Comment by gaaclarke** [comment]
I'm going to try making a different test harness that reuses the work that's been done in microbenchmarks but doesn't have the problems I mentioned in the description.  That might make the alternative more clear.

**Comment by gaaclarke** [comment]
Here is the alternative approach: https://github.com/flutter/flutter/pull/81414/

By having a separate task it's easier to execute on its own, easier to run in the debugger, easier for the bot to parallelize efficiently and works on the existing `task` interface instead of creating a new one.

**Comment by goderbauer** [comment]
> Here is the alternative approach: #81414

One downside of that is that there's a lot of duplication going on for those boilerplate files e.g. in the iOS and Android directory. I wonder if we can find a way to avoid checking in all those files? Could we only check in the relevant implementation files and before running the benchmark generate the other cruft around it with `flutter create`?

**Comment by gaaclarke** [comment]
> One downside of that is that there's a lot of duplication going on for those boilerplate files e.g. in the iOS and Android directory. ... Could we only check in the relevant implementation files and before running the benchmark generate the other cruft around it with flutter create?

I think so.  In my case there are subtle edits to the iOS and Android directories that make the tests work by setting up platform channels.  I'll spend a bit of time to see if there is other things I can delete and regenerate.

**Comment by Hixie** [comment]
I'm going to close this because it is a low-priority technical debt issue (per guidelines at https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues). This does not imply a value judgement for the underlying issue. Feel free to reopen this if you are actively working on it.

That said, I would caution that there is a cost to each approach we are actively using. Deprecating something but not getting rid of it, and then adding something new, doubles the cost of having those things. Even if one of the things is bad in some way, it is cheaper to have a bad thing than it is to have both a bad thing and a good thing.
