### ISSUE TITLE
Run Flutter with Color Correct Skia

### ISSUE THREAD

**Issue by mattsarett** [flutter/flutter#8152]

**Comment by mattsarett** [comment]
I'm looking to use it as a progress tracker for myself.  Is this not a good use of the issue system?  Are you able to assign it to me?

**Comment by eseidelGoogle** [comment]
Tracking related CLs is a totally fine use of the issue system. :)  Just wasn't quite sure what this was for (if we had to do something, etc.)

**Comment by mattsarett** [comment]
I've started preparing a CL for Android:
https://github.com/mattsarett/engine/commit/e0194c66b72741ce7474284ca8045ed5fe4b5f6c

This will depend on https://github.com/flutter/engine/pull/3417.

chinmay@ I'm a little bit stuck trying to figure out how to set the egl attributes based on what the GrContext supports.  Any thoughts?

brianosman@

**Comment by chinmaygarde** [comment]
We create the GrContext after the EGL attributes are set. What EGL attribute keys do you require? Also, it might be easier to get started with iOS first since all you would need to do there is set the `[kEAGLColorFormatSRGBA8](https://developer.apple.com/reference/opengles/keaglcolorformatsrgba8?language=objc)` on the layers color format property. I am not too sure about EGL to be hones. Would need to look it up and get back to you.

**Comment by chinmaygarde** [comment]
Oh, nevermind. I just noticed the keys in [your patch](https://github.com/mattsarett/engine/commit/e0194c66b72741ce7474284ca8045ed5fe4b5f6c#diff-e36bd573c8feccc5a107830ec8cc7b51R129).

**Comment by chinmaygarde** [comment]
How about we try to create both the window and pbuffer surfaces with the attributes in your patch. In case of failure, those calls probably return `EGL_BAD_ATTRIBUTE` (have you checked on a device that does not support the same?). In that case, we try again without those keys. In both cases, EGLContext can make a note of the accepted configuration. Then, when we are creating the GrContext, ask that instance for its configuration.

**Comment by mattsarett** [comment]
So it's my understanding that...
(A) It is possible for the GrContext to indicate that GL supports sRGB - but the EGL attributes fail (I think you're right, we'd get `EGL_BAD_ATTRIBUTE`.
(B) It is also possible for the GrContext to not support sRGB - but the EGL attributes are fine.

I *think* that I need to try something like...
(1) Create GrContext - check if sRGB is supported
(2) Create the EGL surfaces - check if sRGB is supported
(3) Only create the SkSurface with a color space if (1) and (2) are true

**Comment by chinmaygarde** [comment]
It might be a good idea to have the GrContext be created at the same time as the EGL surface.

- Create window or pbuffer surface with the SRGB attribute set, then create the GrContext indicating SRGB support as well.
- If successful, SRGB support is present or enabled. If not, toss away both the EGL surface and the GrContext and try again without support in both.

Right now, GrContext is created separately from the where the EGL surfaces are held (in [`AndroidContextGL`](https://github.com/flutter/engine/blob/481049f9cd71e807472bd3261f561227c51b141b/shell/platform/android/android_context_gl.h#L37)). Maybe `AndroidContextGL` can also create the sk_sp<GrContext> that the platform can use (instead of creating one of its own).

**Comment by mattsarett** [comment]
sgtm, I'll give that a shot.

**Comment by Hixie** [comment]
Closing. We experimented with color correctness and I believe ended up at a place we are happy with.
