### ISSUE TITLE
Bug When execute after kill operations like notification

### ISSUE THREAD

**Issue by mustafa-707** [flutter/flutter#81655]
## Issue : 

After upgrading to flutter 2 , my notification system based on firebase ,  begin to have issues after killing the app , which when  press on notification the app not getting any data from the notification , i already made an issue in `firebase_messaging` but i guess its start happens only when i upgrade to flutter 2 ,also when i push to a screen and that screen have an interstitial Ads , the close button of the interstitial Ads make pop to the screen  , So i got it back to flutter 1.66.2 to run the app smoothly and this's my plugins used in my project and all flutter doctor is give me √  , and the app still running good except this issue :

```
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_messaging: ^9.1.3
  google_mobile_ads: ^0.12.1+1
```

**Comment by darshankawar** [comment]
@mustafa-707 
It seems to be an issue with Firebase even though it's happening after upgrade, you need to follow-up in the issue you created for `firebase_messaging`, because flutter framework can't do anything here if something broke in the firebase plugin after upgrade, the plugin owner team should look and take care of it.

Also, regarding the interstitial ad issue, please file issue in dedicated repo: https://github.com/googleads/googleads-mobile-flutter/issues

Closing from here, since this isn't related to framework, but Firebase.
