### ISSUE TITLE
[in_app_purchase] add example app and complete README for in_app_purchase_ios and in_app_purchase_android

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#81695]
The federated `in_app_purchase` plugin contains a `in_app_purchase_ios` package and a `in_app_purchase_android` package.
For the most cases, people use the federated `in_app_purchase`, however, it is possible to use `in_app_purchase_ios` and `in_app_purchase_android` separately with more customization on both platforms. 

There are currently no example apps or README documentations to guide users to use either of them and we should add those.

**Comment by stuartmorgan** [comment]
This is more serious than just user guidance; since there's no example app, there's no integration testing. That means that changes to the iOS implementation won't have any integration tests run in the PR that changes them, which is bad. (I know the IAP integration test currently isn't doing much, but we should at least have some minimal test.)

(/cc @mvanbeusekom since I pinged about it in Discord)

**Comment by cyanglaz** [comment]
Note that once we have the example apps set up, the XCUITests should also be duplicated in the platform plugin. (For now it's just iOS)

**Comment by mvanbeusekom** [comment]
This issue can be closed as the example apps and integration_tests have been added by pull requests flutter/plugins#3861 and flutter/plugins#3870.
