### ISSUE TITLE
Change flutter tool to run with a precompiled app snapshot

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8170]
The most recent Dart SDK (1.22) changes all the tools to run with a precompiled app snapshot. This lead to a 2x - 3x speedup in startup time:
http://news.dartlang.org/2017/02/dart-122-faster-tools-assert-messages.html
https://github.com/dart-lang/sdk/wiki/Snapshots

We should consider the same for the `flutter` tool.

**Comment by johnmccutchan** [comment]
@rmacnak-google Do we need to provide a training script to enable this?

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/bin/flutter
is the fancy bash script we use to compile our snapshot and run it.  Presumably there is just a new flag to pass?

(Separately it's always seemed strange to me that every project needs to write this little bash script to do snapshot compile/caching around a .dart program.)

**Comment by rmacnak-google** [comment]
`flutter analyze` on the gallery is probably a good training run. Unfortunately, this does not exit cleanly for me.

Currently the flutter tool is distributed as source rather than a snapshot, with snapshot generation happening on the user's machine on first use (unlike the Dart SDK, which distributes snapshots). Creating an app snapshot instead of a script snapshot will make this take much longer: roughly 30 seconds to analyze the gallery. I don't think that's acceptable, so we'd either need a scheme to generate it in the background or prebuild it and fetch it with the other artifacts.

**Comment by zoechi** [comment]
Is this issue still relevant?
It's about Dart 1 and a lot has changed since.

**Comment by mit-mit** [comment]
I *think* it's still relevant, cc @devoncarew ?

**Comment by bkonyi** [comment]
The `flutter` tool automatically generates an AppJIT snapshot on its first run, so this is resolved.
