### ISSUE TITLE
[flutter_tools] Running `flutter config` should only show configured settings

### ISSUE THREAD

**Issue by royarg02** [flutter/flutter#81831]
## Use case
Currently running `flutter config` also prints the usage information, which constitutes all the flags the user could pass to turn a specific feature on, thus resulting in extra noise for someone who would only want to view the currently configured settings:
```
$ flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve
Flutter tools over time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
...
```
The (new) user would have to scan this message all the way down to view the settings, or worse, might completely miss them.

## Proposal
Since the usage information can be also viewed by passing `-h`/`--help` just like other flutter sub-commands, `flutter config` could be _configured_ to only show the current user settings, with a suggestion to run `flutter config -h` to view all settings.
```
$ flutter config
Configured Flutter settings.
Run "flutter config -h" to see all available settings.

  enable-linux-desktop: true
  enable-web: true
  enable-ios: false

Analytics reporting is currently disabled.
```

**Comment by darshankawar** [comment]
The original use case occurs using latest versions. Keeping this issue open.

**Comment by AlexV525** [comment]
Adding an argument like `--all` might be a solution that helps to display all settings.

**Comment by AlexV525** [comment]
![image](https://github.com/flutter/flutter/assets/15884415/e51fa5d7-8fcc-4d57-830b-34bf95c1a550)

**Comment by andrewkolos** [comment]
Following a [discussion on Discord](https://discord.com/channels/608014603317936148/608022056616853515/1144368354795192474) and reconsideration of this proposal, my opinion is that `flutter config` by itself has no discernible meaning. As a result, I think it is appropriate to keep showing the full help text in response to the command.

I understand that it is unnecessarily difficult for a user to examine their current config (they have to know to type `flutter config -h` and look at the bottom of the output). Because of this, I would be open to a proposal for a subcommand (such as `flutter config list`) that only lists the current config.

**Comment by AlexV525** [comment]
The proposal has been reaccepted in #133834.
