### ISSUE TITLE
Auto-submit bot should check that the google testing has completed

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#81852]
The Google testing shard is only initiated after a PR has been approved. This has left open the opportunity for a PR to be approved and merged by the bot before the check even starts. Checking for this to make sure it has been completed will help with the rolls and needing to revert a change that breaks a customer in Google.

**Comment by godofredoc** [comment]
A few things that we'll need before making this status mandatory:

* Get some metrics about how many times people bypass the check.
* It is still too flaky with many false negatives.
* We need SLOs from g3 to ensure we don't block PRs for hours.

**Comment by godofredoc** [comment]
@Hixie should we enable this functionality to get feedback before making the removing the submit access?

**Comment by Hixie** [comment]
Sure.

I agree that we need SLOs from closed-source partners (including Google) when they provide out-of-band testing (like FRoB), since it doesn't make sense for a contributing partner to be able to block all PRs indefinitely. It probably suffices for us to track how often a PR is out of SLO, and then open a conversation when it has been out of SLO multiple times in a row across multiple PRs. The reason I say this is that I wouldn't want us to kick out a partner's testing automatically just because they happened to have an outage. For example, suppose Facebook were to be a Flutter partner; their recent network outage would have pushed them out of SLO for all PRs for a whole day. How should we have handled that? Should we stop landing PRs that day? Should we take them out of the CI process entirely forever? Or maybe just until they say they can fulfill the SLO?

I don't know what the answers should be, but it seems like we should come up with answers and write them down, at least.

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/issues/95355 is very similar, I have added it to the project.

**Comment by XilaiZhang** [comment]
this would be fixed once the migration of google testing to check run is complete.

**Comment by ricardoamador** [comment]
This is currently being done. Closing.
