### ISSUE TITLE
RasterCache should take the total size of an `SkPicture` into account when deciding whether to rasterize it.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81887]
Specifically, if the `SkPicture` references a large `SkImage`, the raster cache will end up retaining that image memory. 

A challenge here is that `SkPicture` doesn't tell us anything about this, so we'd need to track it in some other way e.g. on `PictureLayer`.

/cc @flar @chinmaygarde @knopp who might have good ideas about this.

**Comment by flar** [comment]
The tests in the picture cache don't really look at the memory storage of the SkPicture anywhere. They do have a test for the number of op counts, but that is an attempt to assess rendering complexity, not size.

**Comment by chinmaygarde** [comment]
Not sure I understand the ask. As @flar said, when deciding whether to add to the raster cache, we look at the rendering complexity. But, when the cache entry is populated, the picture is discarded and the major factor in the memory usage associated with that entry is the texture. So the size of the pictures and their referenced images should not matter. Isn't this already working as intended? Or maybe the ask is that the raster cache should disregard adding to the cache past a certain size?

**Comment by dnfield** [comment]
Hmm. I will have to try to construct the example that was concerning to me again. It seemed like it may have been retaining a large image beyond just rasterizing for the purpose of the cache. But I may have been mistaken. I'll close this until I can come up with a repro for it.

**Comment by flar** [comment]
Just to clarify, when we add a picture to the raster cache we don't "discard" the picture, but the cache should not be holding a reference to the picture. SkPicture objects have a complicated life cycle that starts in the Framework and the raster cache should not be holding any references to complicate that life cycle. The association between the SkPicture and the raster cache is handled by a unique ID rather than a reference.
