### ISSUE TITLE
_SliverAppBarDelegate shouldRebuild() should check the pinned parameter

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8193]
Noticed that it was missing; just surveying the code...

**Comment by Hixie** [comment]
Moving this out to beyond m3 since it doesn't currently fit our priorities, but it is something we will fix in due course. Please let us know if this is a priority for you and you can't work around it.

**Comment by zoechi** [comment]
Is this referring to https://github.com/flutter/flutter/blob/d8b57c2ab255f84f54fbb6f62c09dd257d4ae19e/packages/flutter/lib/src/material/app_bar.dart#L717 or an additional check?

**Comment by pedromassangocode** [comment]
The line bellow was added (by https://github.com/flutter/flutter/pull/8345) seven days after this ticket was opened
https://github.com/flutter/flutter/blob/d8b57c2ab255f84f54fbb6f62c09dd257d4ae19e/packages/flutter/lib/src/material/app_bar.dart#L717

Wondering if this issue was not already fixed by https://github.com/flutter/flutter/pull/8345. Can you confirm?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
