### ISSUE TITLE
[null safety] dynamic hides illegal assignment of null to a non-nullable var

### ISSUE THREAD

**Issue by dmitry-fbm** [flutter/flutter#81934]
The problem is easy to illustrate with the following screenshots from dartpad. 

Obviously, such code results in error:

![2021-05-05_180999](https://user-images.githubusercontent.com/72771850/117207943-399f3b80-adfd-11eb-986d-294f85084ab3.png)

And now suddenly assignment of null to a non-nullabe var becomes valid:

![2021-05-05_214511](https://user-images.githubusercontent.com/72771850/117208152-78cd8c80-adfd-11eb-9ccf-73aadfc59290.png)

There either has to be a distinction between `dynamic` which is not nullable and `dynamic?` which is, or assignment of  `dynamic` to anything not nullable has to be invalid operation.

**Comment by stuartmorgan** [comment]
In the future, please file issues about Dart in the Dart issue tracker, not the Flutter issue tracker. Flutter is a framework using Dart, not the language itself.

However, this is not a bug:

> And now suddenly assignment of null to a non-nullabe var becomes valid

`dynamic` is a wildcard; it can hold *any* type, including nullable types. Your example does not involve an assignment to a non-nullable value, which is why it's valid.



> There either has to be a distinction between `dynamic` which is not nullable and `dynamic?` which is, or assignment of `dynamic` to anything not nullable has to be invalid operation.

Neither of these statements is correct. This is why you should almost never actually use `dynamic` in modern Dart; `Object` and `Object?` have the behavior you want, and should be preferred in almost every case.
