### ISSUE TITLE
flutter doctor support to detect visual studio using VSINSTALLDIR

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82006]
Flutter plugins and some of the flutter SDK tests require visual studio installed. To fix problems with missing Root CAs we had to move back to run flutter VMs using chrome images that do not include visual studio.

To fix this problem we are preparing hermetic VS installations that set the following environment variables:

* VCINSTALLDIR: C:\b\s\w\ir\cache\windows_sdk\VC\
* VCToolsInstallDir: C:\b\s\w\ir\cache\windows_sdk\VC\Tools\MSVC\14.16.27023\
* VSINSTALLDIR: C:\b\s\w\ir\cache\windows_sdk 

`flutter doctor` is not recognizing the environment variables making the plugins tests fail.

**Comment by godofredoc** [comment]
\cc @zanderso @stuartmorgan @jonahwilliams do you know who can help us with this functionality?

**Comment by stuartmorgan** [comment]
Can we give the variable more distinctive names that make it clear they aren't for general use? E.g., `FLUTTER_CI_*`?

We don't just use `vswhere` to find paths, but to make sure all the necessary components are installed. If we are going to have a way to bypass all those checks, I don't want end users using it without realizing they shouldn't be.

Also, is this temporary? flutter/plugins should be running tests on stable (although IIRC that request is still open), where this won't work for several releases.

**Comment by godofredoc** [comment]
Any env variables that we can set to tell flutter tool to use VS from that location will work as long as `flutter doctor` and `flutter build` can find it. This will be a permanent fix, chrome landed a few changes to fix the Root CAs issue that are not available in the Windows 2019 image and we are not getting VS installed in the base image anymore.

Regarding `vswhere` took a quick look, are the windows registry the only conflicting checks?

**Comment by stuartmorgan** [comment]
Oh right, I forgot we're looking at the registry now in addition to using `vswhere`.

Is there somewhere I can download the hermetic VS package we're using so that I can test out overrides against it?

**Comment by stuartmorgan** [comment]
That package doesn't have CMake, so isn't usable for our purposes as-is. Can we easily create a package where we control the components that are installed?

**Comment by godofredoc** [comment]
For Linux we are passing cmake, ninja and clang as separate dependencies, we can do that same for windows. Additionally for UWP @cbracken is creating a flutter specific package not sure if that bundle contains everything needed https://chrome-infra-packages.appspot.com/p/flutter/windows/windows-sdk/+/27OHlfdOgagJDjIGkv9h4EFi71z2LfiYu6dtXQp8SosC?

**Comment by godofredoc** [comment]
We are planning to fork the module to make it point to our own cipd package that way we can control the components we want to use.

**Comment by stuartmorgan** [comment]
> For Linux we are passing cmake, ninja and clang as separate dependencies, we can do that same for windows.

Perhaps; I don't know whether the VS-bundled CMake is the same as a stock CMake installation. It would also add even more complexity to the override logic.

**Comment by stuartmorgan** [comment]
After beating my head against this for a while, I discovered that CMake finds Visual Studio using exactly the same backend that `vswhere` uses. It's not clear to me whether it's even possible to override that (I thought `CMAKE_GENERATOR_INSTANCE` would, but I no longer think that's the case based on my testing; I think it may just let you control which of multiple found instances would be selected).

Can we please revisit the restriction that we cannot have a standard VS installation on the bots that tests end-user tool functionality whose requirement is that VS be installed?

(Note that even if we could somehow get this working, we would be fundamentally undermining the "integration" nature of the tests here, since we'd be bypassing all the `vswhere` logic that is on the critical functionality path for all end users for the things that the flutter/flutter build tests that are blocked by this are supposed to be testing.)

**Comment by jonahwilliams** [comment]
Cmake which is used to build Flutter applications on windows cannot locate visual studio installed in the current manner. This means that we are incapable of building or testing Windows applications or plugins in any capacity in the framework tree. Whatever the engine is using is unaffected, perhaps because gn support is different.

**Comment by jonahwilliams** [comment]
(That is my understanding of the situation)

**Comment by stuartmorgan** [comment]
> Whatever the engine is using is unaffected, perhaps because gn support is different.

Yes, gn toolchains are defined in terms of specific binaries (like `cl.exe`), so just needs paths to those binaries. CMake's VS generator expects to find a Visual Studio *installation*.

**Comment by godofredoc** [comment]
We found a reliable way to install visual studio using offline installations.

https://flutter-review.googlesource.com/c/recipes/+/13400
