### ISSUE TITLE
[Request] Better Linux build prompts

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#82018]
## Use case

I want build a Linux app with sqflite plugin support on Ubuntu, I have sintalled all dependenices but not able to build it:

```
❯ sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
cmake is already the newest version (3.5.1-1ubuntu3).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.3).
clang is already the newest version (1:3.8-33ubuntu3.1).
The following packages were automatically installed and are no longer required:
  libmysofa0 libx265-179 qml-module-qtquick-controls qml-module-qtquick-dialogs
  qml-module-qtquick-privatewidgets
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 470 not upgraded.

```

```
❯ flutter run
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Linux
Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                          ⣻
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found                                      
Call Stack (most recent call first):                                    
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:27 (pkg_check_modules)                         
                                                                        
                                                                        
Building Linux application...                                           
Exception: Unable to generate build files

```

## Proposal

1. Better promots which package lacking;
2. Linux examples with plugin simple use case, such as sqflit etc.

BTW. Linux desktop seems more and more urgently as a user of flutter. because of a **serious** reason, some vendor cross platform support such as go-flutter have a better support of plugins, but  **they really lack of maintainance and support and hear no voice from users**. For example, I am Chinese user until now they not fix input Chinese charactor crash issue on Linux.

Hope flutter team can help us build a strong Linux support, with plugin support and forregin language support.

**Comment by TahaTesser** [comment]
Hi @jinfagang 
You've two different proposals and issues, whicb are unrelated to each other

1. Which linux distro are you using? I have Ubuntu, Manjaro, Fedora (none of them show this error) 
2. `sqflite` is a third-party package, you can create an issue on their GitHub for linux sample

> . For example, I am Chinese user until now they not fix input Chinese charactor crash issue on Linux.

If it is not a known issue, please file a new issue for this

Thank you

**Comment by stuartmorgan** [comment]
> 1. Better promots which package lacking

You have not included your output from `flutter doctor`, which is where information about what you are missing would be surfaced. The errors you are seeing are from CMake, and we can't control them, which is why the setup instructions say to run it. Please provide your `flutter doctor -v` output.

> Hope flutter team can help us build a strong Linux support, with plugin support and forregin language support.

As I have explained to you before, Flutter for Linux already has plugin support, and had for quite some time. And as I've explained before, the process of adding Linux implementations of third-party plugins like sqflite is **up to the developers of those plugins**. Continuing to ask here for third-party plugins to add Linux support is not productive.

**Comment by stuartmorgan** [comment]
> If it is not a known issue, please file a new issue for this

The comment you are replying to here is about go-flutter, which is a completely separate project with its own embedding implementation.

**Comment by TahaTesser** [comment]
@stuartmorgan 
I meant `input Chinese character crash issue on Linux.` issue in Flutter itself since the author has filed an issue here. Apologies if i wasn't clear

**Comment by stuartmorgan** [comment]
I think the issue here is likely a docs bug; the desktop setup instructions were changed in a way that's not yet correct for stable, just master. I've followed up in the PR where it was changed.

**Comment by stuartmorgan** [comment]
> But i am disappointed about I am not able to bring up my Linux desktop app via `flutter run` and always got error.

Please provide the information I requested above, so that we can try to help you. That's why I asked for it (and why the initial bug template asked for it). Without seeing what `flutter doctor -v` is reporting we have no way of knowing what library specifically is missing.

You could also look at line 27 of `linux/flutter/CMakeLists.txt` to see what library it is failing to load, per the error message you received from CMake.

> But it's looks normal using `hover run` from go-flutter

There is absolutely nothing in common between a Flutter Linux project and go-flutter project at the layer at which this error is happening, so this is irrelevant to the issue here.

> as I said, they doesn't quite take any close look to users issues, they seems directly ignored users from China like me using Chinese characters.

Denigrating another project here is not productive, and is not consistent with our code of conduct. Please stop using this issue to air your grievances about a completely different project.

**Comment by jinfagang** [comment]
@stuartmorgan this is the question I met. the log message gives me all this:

```
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                          ⣻
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found                                      
Call Stack (most recent call first):                                    
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:27 (pkg_check_modules)                         
                                                                        
                                                                        
Building Linux application...                                           
Exception: Unable to generate build files
```

It just indicates pakcage not found, but I do not know which one. 

And I just followed steps in official documentation with all those installed:

```
❯ sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
cmake is already the newest version (3.5.1-1ubuntu3).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.3).
clang is already the newest version (1:3.8-33ubuntu3.1).
The following packages were automatically installed and are no longer required:
  libmysofa0 libx265-179 qml-module-qtquick-controls qml-module-qtquick-dialogs
  qml-module-qtquick-privatewidgets
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 470 not upgraded.
```

So I think it might help:

1) In error messages, throw out which pakcage is missing (by changing CMakeLists maybe?);
2) Bold libs that **really** enssential to run `flutter run` on Linux. in case some lib not mentioned but really needed.

**Comment by stuartmorgan** [comment]
> the log message gives me all this

Yes, I read your earlier comment.

> It just indicates pakcage not found, but I do not know which one.

I've already explained how we can find out, but you refuse to provide the information necessary even after I've requested it several times. Since we cannot make progress without that, I'm closing this. If you provide the information I've requested we can re-open it.

This has been a pattern with issues you've filed. Please don't file issues if you aren't willing to answer follow-up questions that are necessary in order to make progress.

> * In error messages, throw out which pakcage is missing (by changing CMakeLists maybe?);

I already responded to this above.

> * Bold libs that **really** enssential to run `flutter run` on Linux. in case some lib not mentioned but really needed.

And this.
