### ISSUE TITLE
Flutter build Appbundle Error:* What went wrong: A problem occurred evaluating project ':app

### ISSUE THREAD

**Issue by Cistexa** [flutter/flutter#82269]
I am new and  I need help.After write flutter build appbundle,

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Kodlar\flutter projeler\howtoplay\android\app\build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
Malformed \uxxxx encoding.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full i
nsights.

* Get more help at https://help.gradle.org/

BU�LD FAILED in 2s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                      2.900ms
Gradle task bundleRelease failed with exit code 1

**Comment by darshankawar** [comment]
@Cistexa 
It seems there's some misconfiguration in one of your gradle files or key.properties file, something like use of \ instead of '/' for file paths.
Check all your files under `android` folder and see if they are in correct configuration / syntax. You may create a new project and compare its setting with your current one to see where the gap could be.

**Comment by Cistexa** [comment]
@darshankawar  thank you for help :)

**Comment by darshankawar** [comment]
Assuming your issue is resolved based on above comment. Closing.
