### ISSUE TITLE
flutter on native end should offers callback on   GeneratedPluginRegistrant.register(with: flutterEngine) function

### ISSUE THREAD

**Issue by 348446059** [flutter/flutter#82338]
## Use case
Before I start, I make a clear that I don't use flutterViewController as binaryMessenger but flutterEngine. I run the flutterEngine.run  and  GeneratedPluginRegistrant.register(with: flutterEngine) code, I have no idea that what the moment I registered my plugin  is. I will get exception in flutter when I call  the function written in flutter that  uses services offered by my plugin. This  exception means obviously that I use the plugin services  before I registered it successfully. 

## Proposal

   Delaying the call almost 1 second get work, so my advice to solute this problem is I can get feedback after I call   GeneratedPluginRegistrant.register(with: flutterEngine) function. this is my first provide issue in English, if you cannot understand the describe of this issue above, I can correct it. thanks for your reading, I am looking forward your feedback.

**Comment by stuartmorgan** [comment]
That registration function is synchronous, so there's no need for a callback. It's finished running when it returns.

It's not clear to me what the underlying issue you're trying to solve is, but the proposal here seems to be based on misdiagnosing the problem. I suggest filling a new issue where you describe in detail, with reproduction steps, the actual problem, rather than jumping ahead to what you think the solution would be.
