### ISSUE TITLE
hotReloadInitialDevFSSyncAfterRelaunchMilliseconds, hotReloadInitialDevFSSyncMilliseconds regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#82361]
See https://flutter-flutter-perf.skia.org/e/?begin=1620396542&end=1620837185&keys=X3ede329e250323f68d006ede1b60b568&requestType=0&xbaroffset=24008. Looks like it started with https://github.com/flutter/flutter/pull/82291, although I don't see how any of those engine commits could have raised the hot reload times.

/cc @jason-simmons, this week's engine sheriff. 

Given the small increase involved, I'm marking this a P1 so it doesn't block further releases.

**Comment by jason-simmons** [comment]
I tried reproducing this locally.  The change to the metric in the benchmark graph is around 5%, and the variance between local runs of the benchmark on my setup is larger than that.  So I was not able to reproduce a consistent change due to a recent commit.

The only engine change that landed in that range was https://github.com/flutter/engine/commit/0fe6b7b410d43c18ce8932360295887dc993a25e.  There were no rolls or Dart or other dependencies.

Besides the engine roll there were two framework changes, neither of which seem related to hot reload.

Given that, I'd vote for rebaselining this benchmark.

**Comment by kf6gpe** [comment]
SGTM. Will do and closing.
