### ISSUE TITLE
ScrollableState.setCanDrag should not contradict with scroll physics

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#82391]
Currently, because `ScrollableState.setCanDrag` doesn't check whether it complies with `ScrollPhysics.shouldAcceptUserOffset`, it's possible that user of ScrollableState doesn't check whether it can be set to `true` or `false` and thus ignores scroll physics by mistake - which is what happens to NestedScrollView, which forgets to do exactly this https://github.com/flutter/flutter/issues/45619

https://github.com/flutter/flutter/blob/ff15d04f214ae7cc4ffbacde2faefa1772e112e4/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1619-L1621

I propose that we force users of the ScrollableState to check the physics before they apply their own conditions with such assert (or something similar)

```dart
assert(
  _physics == null || newCanDrag == _physics!.shouldAcceptUserOffset(position),
  'When scrollable has physics, canDrag should be equal to shouldAcceptUserOffset result',
);
```

cc @Hixie

**Comment by Piinks** [comment]
Came across this while working on https://github.com/flutter/flutter/pull/127718
I realized working on that we cannot add this assertion since it would break the nested scroll view. If the outer position is not draggable, but the inner position is, this assertion would trip when the NestedScrollView set drag. Adding more docs in the linked PR. :)
