### ISSUE TITLE
Linkcheck and analysis of code on the website needs to be automated

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#8242]
Rather than running linkcheck and flutter analysis on the code when we submit a PR, can we have a nightly or weekly process that runs these checks and emails a report?

This is why:

Yesterday I went to submit a PR for my tutorial, and the submit failed. When I investigated, it turned out that the API docs had changed, and the animation.md page, which linked to a page that no longer existed on docs.flutter.io, was failing the linkcheck.

So, my submit failed, due to something that had nothing to do with my PR. I had to figure out what was going on, create a new PR, and ask engineering to approve. Once it was approved (and in that interval I felt helpless to proceed in my work though, luckily, the SWE was quick to approve though it was after hours), I had to go back to the master branch, do a pull, go back to my original branch, merge the changes, and THEN I was able to successfully submit my PR.

This is a fairly onerous process and is reliant on someone submitting a PR to find problems.

It would be nice if we had a nightly, daily, weekly (whatever) process that ran these checks and sent a report to the Flutter devrel team. And then, perhaps, reduce the burden on the submission process. I can envision long periods when no one submits a PR on the website, so problems can go undetected.  (Unless there is already a regularly automated linkcheck which emails reports, and I'm just not in the loop.)

Thoughts, @sethladd, @LarkAscending?

**Comment by sethladd** [comment]
I hear you. :/ That's a pain.

We're really concerned that a nightly job will just email into the void. And the "build cop" model is a tough model, no one is incentivized to fix any root cause and we're just reacting to annoying emails.

I'm very concerned about decoupling the correctness checks on our website from the PR process, and moving the correctness checking to a weekly schedule. It might be weeks before we fix something in that model. :(

What might be a better fix, is to run the link checker on the main Flutter builds. That way, when the Flutter SDK team changes an API, they are warned that they break the docs. At least, at _that_ point we should send an email. I think this is a fairly easy thing to wire up.

I think it's fair to TBR a PR that fixes a link. You probably don't need to wait for a review before landing a fix for a 404 (unless it's unclear what the fix is, of course).

Let's talk to the framework team on Monday and ask if we can run the link checker when they commit to Flutter. That should at least send us an email or open an issue. I'll open an issue for that, but for now, I'd like to keep running correctness checks on PRs.

**Comment by Sfshaza** [comment]
I am definitely OK with that approach and thanks for opening an issue.

You can talk about this on Monday, but that might be hard since it's a holiday and I'm taking the day off. ;)

**Comment by sethladd** [comment]
I didn't say _which_ Monday!

**Comment by LarkAscending** [comment]
The API changes are a blip and are likely to slow way down - we're going
through a phase.
Before we change processes because they're cumbersome right now, let's
think about the way things are likely to be Real Soon Now.

I'm wary of the batch approach because it is VERY painful to fix a batch of
breakage. Much better to fix breakage incrementally.

**Comment by sethladd** [comment]
Agreed fixing a bunch of broken links all at once is painful. We hope that with more frequent monitoring, though, we will identify breaks "as they happen", instead of "all at once" when an orthogonal PR is trying to land.

Right now, we're not proposing any change to process... just adding a more frequent automated check. No action required for our website contributors.

**Comment by LarkAscending** [comment]
If the /website contributors don't also have to monitor a nightly log, SGTM.

Most breakages are not simple to fix, tho. When an API changes, the doc
often gets hit hard: descriptive text, steps, code samples.
Knowing about breakage earlier might be nice, but usually someone will have
to clear a window of time to resolve them.
:-)

**Comment by sethladd** [comment]
> If the /website contributors don't also have to monitor a nightly log, SGTM.

The nightly link check job won't require active monitoring (it will send emails to the team when it finds a break).
