### ISSUE TITLE
No alert was triggered for 100% of devicelab windows machines dead

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82513]
Given that the size of the pool is 2, the expectation is to receive a notification when a single bot goes down.

**Comment by godofredoc** [comment]
\cc @keyonghan

**Comment by cbracken** [comment]
Related https://github.com/flutter/flutter/issues/82514

**Comment by keyonghan** [comment]
The alert will be triggered when the ratio between active bot number and all bots number < 80% for 4 hours.
The numbers are both calculated based on device os and bot os. However when the bots are died (I suppose the device os info is not available), the alert will not find any bot matching pre-defined filters and will not be triggered.

This seems fixable by using the absolute number of active bots rather than the ratio as the trigger for these alerts.

This needs some work and is not blocking the tree. Moving it out of ticket queue.

**Comment by keyonghan** [comment]
Alert is updated to use absolute active device number: cl/374911993
Threshold to trigger different platforms:
```
LINUX_ANDROID_DEVICE_THRESHOLD = 7
MAC_ANDROID_DEVICE_THRESHOLD = 5
MAC_IOS_DEVICE_THRESHOLD = 7
MAC_IOS32_DEVICE_THRESHOLD = 1
WINDOWS_ANDROID_DEVICE_THRESHOLD = 2
```
