### ISSUE TITLE
platform_channels_benchmarks is 3.33% flaky

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#82743]
The benchmark test platform_channels_benchmarks has a flaky ratio 3.33% (3/90 [source](go/flutter_15day_flakiness_dashboard)), which is above our self-imposed 2% threshold.

Link to a failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20platform_channels_benchmarks/57/overview

(Creating this issue as part of the gardener rotation.)

**Comment by keyonghan** [comment]
Assigning to @gaaclarke for adding the ownership, and please help reassign to the correct sub team TL. Thanks!

**Comment by gaaclarke** [comment]
Do we have a link to a failure?

**Comment by gaaclarke** [comment]
@keyonghan what does that column that says `@flutter/engine` mean?  The benchmark is measuring things in the engine and the framework?

**Comment by keyonghan** [comment]
> @keyonghan what does that column that says `@flutter/engine` mean? The benchmark is measuring things in the engine and the framework?

That's the sub-team who will take the responsibility to triage/reassign.

**Comment by keyonghan** [comment]
> Assigning to @gaaclarke for adding the ownership, and please help reassign to the correct sub team TL. Thanks!

Two builds for the same commit (first failed while the second succeeded)
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20platform_channels_benchmarks/57/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20platform_channels_benchmarks/59/overview

**Comment by zanderso** [comment]
This looks like the failure:
```
[platform_channels_benchmarks] [STDERR] [STDERR] [  +37 ms] AndroidManifest.xml could not be found.
[platform_channels_benchmarks] [STDERR] [STDERR] [        ] Please check /opt/s/w/ir/x/w/recipe_cleanup/tmpNp4jQL/flutter sdk/dev/benchmarks/platform_channels_benchmarks/android/app/src/main/AndroidManifest.xml for errors.
[platform_channels_benchmarks] [STDERR] [STDERR] [   +4 ms] No application found for TargetPlatform.android_arm.
[platform_channels_benchmarks] [STDERR] [STDERR]            Is your project missing an android/app/src/main/AndroidManifest.xml?
[platform_channels_benchmarks] [STDERR] [STDERR]            Consider running "flutter create ." to create one.
```

**Comment by gaaclarke** [comment]
What is the denominator you are using when calculating the percentage in this case?  Since the test is new this test may be just as flakey as any other test, it just doesn't have as many samples.  From the output of the failure there is no apparent reason why this test would be more flakey than any other test since the tool is crashing.

**Comment by gaaclarke** [comment]
What is the expect flake rate for an android linux android test that has a larger sample size?  If it is zero I think we should mark the test flakey.  If it is greater than zero we should get a larger sample size and update the formula for calculating flakiness to take into account sample size.

**Comment by keyonghan** [comment]
Here is the dashboard: go/flutter_15day_flakiness_dashboard. It is calculated as `No. of Flaky Runs/No. of Total Runs` in the last 15 days.

**Comment by gaaclarke** [comment]
FWIW that test hasn't been running 15 days so its denominator is smaller than others.  There are plenty of tests with 0 flakes so there is something fishy going on with the build, but it also might be under 2% if it is given the same math as the other tasks.  Its sample count is at 90 when the others are at ~120.

**Comment by gaaclarke** [comment]
This test isn't hermetically sealed, `dev/benchmarks/platform_channels_benchmarks/android/app/src/main/AndroidManifest.xml` is a file that isn't checked into the repository.  It is regenerated with `flutter create`.  It seems like `flutter create` may have failed to create that file.  I this is a unique situation for this test too so that might explain why this is flakey and not other tests.

**Comment by gaaclarke** [comment]
Jonah's PR will fix it.  It was a race condition where the test wasn't awaiting on `flutter create` so necessary files might not have been generated yet.

**Comment by gaaclarke** [comment]
After that PR lands we'll have to follow the protocol for reenabling the test: https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests
1) [ ] Enable the test in the staging env. first for validation - make sure 50 consecutive successful runs without any flakiness issue
1) [ ] If no flakiness issue pops up, then enable the test in the prod env

**Comment by keyonghan** [comment]
As @zanderso suggested, we will not remove these flaky tests from builder.json, which means they will still show up in the flutter build dashboard (with flaky flag not affecting the tree).
So for the first check action, we can use flutter build dashboard as the source of true, rather than going through the staging pool.

But as for any future new test, we still recommend go through staging pool. Updated the wiki page accordingly.

**Comment by zanderso** [comment]
On https://github.com/flutter/flutter/pull/82754 we discussed simply marking the test as flaky and not moving to staging. I think that is probably the right approach in cases like this where the presumed fix is identified quickly.
