### ISSUE TITLE
Add UWP support to flutter/plugins tooling

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82817]
In the short term, we need the tooling to support
- [x] build-examples
- [ ] drive-examples

That will let us run integration tests (the critical test type for plugins) in UWP mode via the tooling.

(Longer term we'll also need native unit test support for UWP, but we can track that in https://github.com/flutter/flutter/issues/82445)

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
