### ISSUE TITLE
UWP support for integration_test/flutter_driver

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82821]
To test plugins for UWP, we need to be able to run integration tests via Flutter driver.

IIRC there was almost no work needed to enable this for the other desktop platforms once `flutter run` worked, but since running is more complicated with UWP I'm not sure if that will be true here as well.

/cc @cbracken

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
