### ISSUE TITLE
[X] Android toolchain - develop for Android devices

### ISSUE THREAD

**Issue by sbhardwaj8717** [flutter/flutter#82886]
[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Users\Daywi\AppData\Local\Android\Sdk
      but Android SDK not found at this location.

_Originally posted by @DaywisonSilva in https://github.com/flutter/flutter/issues/13078#issuecomment-528525122_

**Comment by TahaTesser** [comment]
Hi @sbhardwaj8717 
Can you please provide your `flutter doctor -v` ?

Make sure your SDK files are not nested inside another inside `Local\Android\Sdk`, otherwise this folder `Local\Android\Sdk` should have SDK files.  Also `ANDROID_HOME` is deprecated, it is advised to change to `ANDROID_SDK_ROOT`.

**Comment by sbhardwaj8717** [comment]
Thank you @TahaTesser  for your initiative.

I had double-checked it and the SDK path was correct.

I have just found another method and it worked for me.

Thanks again....🤗
