### ISSUE TITLE
No devices found with name or id matching 'iPhone'

### ISSUE THREAD

**Issue by yash-1th** [flutter/flutter#83166]
I was doing a codelab called 'Get to know Firebase for Flutter'. I cloned the code from Github as suggested in the codelab. When I clicked the run option the emulator is not loading the app, instead I got the following one line output(mentioned as issue name). Why is the app not getting loaded in the emulator?

Link to codelab: https://firebase.google.com/codelabs/firebase-get-to-know-flutter#0
Link to code: https://github.com/flutter/codelabs/tree/master/firebase-get-to-know-flutter/step_02

https://stackoverflow.com/questions/67499613/no-devices-found-with-name-or-id-matching-iphone

**Comment by TahaTesser** [comment]
Hi @yash-1th 
This is because of VS Code[ launch config](https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_02/.vscode/launch.json)

After you open the project, from the bottom left, select Android config and launch the emulator, run your app. If you're on macOS, you can use simulator and select iPhone 

Closing as it is an issue with codelab or Flutter
Thank you
