### ISSUE TITLE
RasterCache could reuse or combine (i.e. atlas) SkSurfaces during composited scale animations

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#83189]
cc @dnfield @flar 

Currently, the RasterCache allocates SkSurfaces tightly fitting the content being rasterized. Skia then tries to match an existing allocation in GrResourceCache using requested resolution. During a scale animation, this typically results in a resource miss. A simple scale+opacity route transition can fill up Skia's resource cache, increasing memory usage until the cache hits its limit.

One mitigation I tested was changing RasterCache to round up pixel resolutions to a multiple of 64. Increasing the tile size reduces the number of allocations needed, but has diminishing returns for small composited/raster cached content. I may send out a PR for the mitigation to see how it affects benchmarks.

A more complete solution would be using a rect packing algorithm such as https://blackpawn.com/texts/lightmaps/ to place RasterCache content on a small set of large surfaces, similar to how its done in [Cobalt's OffscreenTargetManager](https://cobalt.googlesource.com/cobalt/+/master/src/cobalt/renderer/rasterizer/egl/offscreen_target_manager.cc).

I'll work on a minimal dart:ui-only test-case + RenderDoc capture for this tonight.

**Comment by nt4f04uNd** [comment]
Could this issue be related https://github.com/flutter/flutter/issues/82711 ?

**Comment by ds84182** [comment]
I'm not sure if its completely related, but it does seem like some bad repainting behavior. I think in that situation the RepaintBoundary is doing more harm than good. What may be happening is the following:

```
TransformLayer (RotationTransition)
  OpacityLayer (FadeTransition) <- Requests explicit rasterization of PictureLayer
    PictureLayer (Image) <- Inserted into RasterCache due to cache heuristics
```

which results in double rasterization, once as an offscreen layer (requested by OpacityLayer) and then by the RasterCache itself. When this happens, I think the PictureLayer is rasterized by the RasterCache for one frame, then that rasterized image is drawn in the offscreen layer requested by OpacityLayer. Next frame the OpacityLayer is redrawn using the offscreen layer, and the RasterCache entry for PictureLayer is dropped since its unused. And then the frame after that, the size of the OpacityLayer changes so it drops the original offscreen layer, restarting the cycle.

**Comment by flar** [comment]
The double-caching was also documented in https://github.com/flutter/flutter/issues/70124

**Comment by flar** [comment]
Other advantages to caching layers together in a large texture would be reduction of texture switching during the caching phase and potentially during the render phase.

One (potentially obsolete) disadvantage is that if one layer's rendering depends on another layer's and they are both cached - you can't blit from a texture to itself. I added "potentially obsolete" there because if the decisions are made correctly, then it is unlikely you would cache both dependent textures in the first place.

In the issue [linked above](https://github.com/flutter/flutter/issues/70124) about the double-caching, a couple of solutions are presented to avoid rendering the caches until after the preroll is done. This would also help with intelligent allocation in a shared texture.

**Comment by flar** [comment]
@knopp might also have some ideas

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
