### ISSUE TITLE
Flutter themeing is hard to understand and inconsistance

### ISSUE THREAD

**Issue by burhankhanzada** [flutter/flutter#83206]
I am new to flutter but i have android background where i use material themeing with its best practice and now when i move to flutter i also want to fully understand how themeing works in flutter but its so inconsistance and breaking changes in thememing system described [here](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#) makes it more difficult to understand like if new system promoting colorScheme and used in most of the material widgets to use its defined properties but for instance appBar uses primaryColor or primarySwatch making its inconsistance and also if there is all properties have defined in colorScheme why not removing primaryColor and primarySwatch or deprecate them like done with accentColor in master channel also still in stable chanel there is also so much confusion as some changes not including like i find accentColor is not deprecated there

**Comment by TahaTesser** [comment]
This transition is in progress, there are so many widgets and classes that need new examples and docs updates, You can find such issues using this [filter](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22f%3A+material+design%22+label%3Adocumentation). Since this issue doesn't add any else tangible, I safe to close the issue. As they progress, we might have deprecation messages and new examples to easier to follow new themeing 
Thank you
