### ISSUE TITLE
Why does `pub` not support a constraint for the required Flutter SDK channel in the `pubspec.yaml` file?

### ISSUE THREAD

**Issue by DarkPurpleKnight** [flutter/flutter#83226]
`pub` supports a [constraint](https://dart.dev/tools/pub/pubspec#flutter-sdk-constraints) for the required Flutter SDK version in the `pubspec.yaml` file, but according to #29211 its usage seems to be not quite clear yet.

However, what is completely missing is a constraint for the required Flutter SDK channel in the `pubspec.yaml` file. Why does `pub` not support such a constraint?

**Comment by stuartmorgan** [comment]
> according to #29211 its usage seems to be not quite clear yet.

Its usage is to indicate what versions of Flutter a package is compatible with. People in that issue seem to want it to do something totally different (cause their Flutter version to change on the fly as if Flutter were a pub package rather than the tool being used), which is likely where their confusion comes from.

> However, what is completely missing is a constraint for the required Flutter SDK channel in the `pubspec.yaml` file. Why does `pub` not support such a constraint?

Because such a constraint isn't useful; it doesn't specify a version range.

**Comment by DarkPurpleKnight** [comment]
That clears up my questions. Thanks.
