### ISSUE TITLE
FLUTTER_ROOT env variable is required to build iOS app with Fastlane

### ISSUE THREAD

**Issue by xit0c** [flutter/flutter#83335]
I followed the [official guide for CD in Flutter](https://flutter.dev/docs/deployment/cd), but the iOS build step was failing every time.

The error was `** ARCHIVE FAILED **`, with `Exit status: 65`.

Reading the logs I found out the path of the script that was causing the failure:
`~/Library/Developer/Xcode/DerivedData/Runner-fvfnfmbagfhwynatujspinmrqqmb/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh`
(I suppose that the names of the "Runner-" dir and the "Script-" file may vary).

The content of the script file is the following:
```bash
#!/bin/sh
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
```

Since I didn't had FLUTTER_ROOT set in my env, the script couldn't run properly. Setting FLUTTER_ROOT to my env solved the problem.

To save other developers' time and headache, I suggest to add explicitly in the CD guide the requirement of the FLUTTER_ROOT env variable (that must point to the Flutter installation dir).

**Comment by TahaTesser** [comment]
Hi @xit0c 
The issue is related to the Flutter website, please file an issue on their dedicated GitHub [repository](https://github.com/flutter/website/issues).
Follow this [link ](https://github.com/flutter/website/issues/new?title=%27Continuous%20delivery%20with%20Flutter%27%20page%20issue&body=Page%20URL:%20https://flutter.dev/docs/deployment/cd.html%0D%0APage%20source:%20https://github.com/flutter/website/tree/master/src/docs/deployment/cd.md%0D%0A%0D%0AFound%20a%20typo?%20You%20can%20fix%20it%20yourself%20by%20going%20to%20the%20page%20source%20and%20clicking%20the%20pencil%20icon.%20Or%20finish%20creating%20this%20issue.%0D%0A%0D%0ADescription%20of%20issue:) to file an issue, thank you
