### ISSUE TITLE
Adding documents with same ID to Firestore at the same time

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#83348]
Hello! I want to add 2 documents with the same ID to Firestore when doing the following (see code below). I want [2] to have the same document ID as [1], since both are adding the same info to different places in Firestore. Right now, [1] and [2] give me different document IDs. I want to see if it is possible for them to have the same ID. Preferably if [2] can have the same doc ID as [1]. How could I do this? Thanks

```
void _sendPost() async {
 FirebaseFirestore.instance.collection('post').doc(docX).collection('posts').add({}) [1]
 FirebaseFirestore.instance.collection('users').doc(user.uid).collection('userPosts').add({}) [2]
}
```

**Comment by TahaTesser** [comment]
Hi @Alvaro-99 
It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Alvaro-99** [comment]
Hello! This is NOT me asking for help on personal code. I just attached my code so that it is easier to understand. I am asking about a general feature in Firestore and see if it is possible to do. I want to see if it is possible to add two documents with the same ID to Firestore at the same time. So, please reopen this discussion. Thanks

**Comment by TahaTesser** [comment]
Hi @

>  I want to see if it is possible to add two documents with the same ID to Firestore at the same time. So, please reopen this discussion. Thanks

GitHub issues are not for meant assistance or discussion, please ask such questions on Stackoverflow or https://www.reddit.com/r/flutterhelp/

If you want to file an issue, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).

**Comment by TahaTesser** [comment]
Hi @

>  I want to see if it is possible to add two documents with the same ID to Firestore at the same time. So, please reopen this discussion. Thanks

GitHub issues are not for meant assistance or discussion, please ask such questions on Stackoverflow or https://www.reddit.com/r/flutterhelp/

If you want to file an issue, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
