### ISSUE TITLE
Plugins CI failing with "The Flutter SDK is tracking a non-standard remote"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#83373]
This was caused by a recent tools PR https://github.com/flutter/flutter/pull/79372

**Comment by christopherfujino** [comment]
Opened https://flutter-review.googlesource.com/c/recipes/+/13920 to fix

**Comment by stuartmorgan** [comment]
> The Flutter SDK is tracking "https://chromium.googlesource.com/a/external/github.com/flutter/flutter" but "FLUTTER_GIT_URL" is set to "https://chromium.googlesource.com/external/github.com/flutter/flutter".

Note the `/a/`.

I'm not sure why flutter/plugins and flutter/packages use `flutter upgrade`; maybe just convenience of not encoding information about where the Flutter install is since it's already part of the image? I'm fine with moving away from that for LUCI as long as we're getting the latest version of the given channel. (Ideally I think we want a pinned version and a roller to avoid out-of-band failures, in which case we'd need to be off of `ugrade` anyway.)

**Comment by christopherfujino** [comment]
This was permanently fixed by https://github.com/flutter/plugins/pull/4213
