### ISSUE TITLE
Deflake ios32 DeviceLab tests?

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#83429]
All ios32 DeviceLab tests are marked as flaky, and not affecting the tree.

This issue tracks whether we will deflake them back, or leave them flaky all the time.

Context: go/flutter-devicelab-ios32, https://github.com/flutter/flutter/issues/82940#issuecomment-844542784

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by jmagman** [comment]
mac_ios_native_ui_tests_ios32 isn't flaky, it's failed 0 times in the last 50 commits, but was marked flaky in https://github.com/flutter/flutter/issues/82940 because `flutter_gallery__transition_perf_e2e_ios32` is flaky?  I'm not sure why `flutter_gallery__transition_perf_e2e_ios32` is failing, but it sounds like it's worth investigating since all the `transition_perf_e2e` have had problems https://github.com/flutter/flutter/issues/83298, though this is manifesting differently.  If it were a problem with the device I'd expect both tests to be failing.

I think we should:
1. Mark `mac_ios_native_ui_tests_ios32` as unflaky, since it's not.
2. Actually investigate why `flutter_gallery__transition_perf_e2e_ios32` is failing.

**Comment by jmagman** [comment]
> If it were a problem with the device I'd expect both tests to be failing.

Although we've had problems like that that have been solved by rebooting the device.  Has anyone tried that?

**Comment by keyonghan** [comment]
Please see go/flutter-devicelab-ios32, https://github.com/flutter/flutter/issues/82940#issuecomment-844542784 for more discussion on decision to mark all ios32 tests as flaky.

**Comment by jmagman** [comment]
go/flutter-devicelab-ios32 suggests that the Flutter gardener and release team are still responsible for making sure those tests pass, and if they are removed from the dashboard how could it be monitored?  And if the test is failing because those old devices need a kick, will the infra team be able to do that?  Are we just supposed to ignore forever-red tests in milo if the devices are in a bad state?

Personally I think these devices should be kept upright and working as best as possible, as they are the barest validation we have that we haven't broken 32 bit iOS (and at least try to add more to the pool as Yuqian suggested in the proposal).  It really does sometimes catch problems like https://github.com/flutter/flutter/issues/53581 or https://github.com/flutter/flutter/issues/65258.  However I know it's a pain point for the infra team and enrages @jonahwilliams.  Alternatively, could we temporarily remove these devices from the devicelab and then bring them back when the infra team is once again in person in the lab and periodically intervening (as suggested in go/flutter-devicelab-ios32) is less painful?

In any case, I don't think removing them totally from the dashboard is in the spirit of go/flutter-devicelab-ios32.

**Comment by keyonghan** [comment]
I guess the purpose of this issue is to track whether we want to deflake ios32 tests in the future or leave them flaky all the time, rather than remove them from the dashboard or not. Have updated the title and description to reflect that.

**Comment by keyonghan** [comment]
For the phone rebooting request, filed b/189378992 to track.

**Comment by keyonghan** [comment]
Rebooted the phone, and both ios32 tests are running successfully for the TOT commit.

**Comment by chinmaygarde** [comment]
cc @zanderso

**Comment by zanderso** [comment]
32-bit iOS devices are planned to be removed.
