### ISSUE TITLE
Migrate Google Maps plugin to hybrid composition

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#83524]
Google Maps currently doesn't work with the Admob plugin if they are used in the same screen.

I suggest we do a minor release, and change the default backend (Similar to the webview plugin).

**Comment by blasten** [comment]
cc @bparrishMines

**Comment by bparrishMines** [comment]
With `2.1.0` there is now documentation for switching the Google Maps widget to Hybrid Composition: https://pub.dev/packages/google_maps_flutter#android. I'm going to go ahead and close this issue.

**Comment by stuartmorgan** [comment]
The original description of the issue was to change the default, not just make it an option; is that no longer the plan?

**Comment by bparrishMines** [comment]
WebView doesn't actually use Hybrid Composition as the default yet: https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/lib/src/webview.dart#L122. 
Since it was only a suggestion and WebView hasn't converted yet, I didn't make it the default.

We could create a separate issue to make `webview_flutter` and `google_maps_flutter` to use it by default?

**Comment by stuartmorgan** [comment]
Separate issues works for me, I just want to make sure we're still tracking it (or that we're explicitly saying that changing the default is no longer the goal), since the issue as filed was for changing the default.

**Comment by bparrishMines** [comment]
https://github.com/flutter/flutter/issues/93335
