### ISSUE TITLE
[video_player_web] HTTP headers are not supported

### ISSUE THREAD

**Issue by lqmminh** [flutter/flutter#83602]
video_player: ^2.1.4
My server request Authorization on header and i has insert it into header:
`VideoPlayerController controller = VideoPlayerController.network({URL}, httpHeaders: {
        'Authorization': 'Bearer ${token}'
});`
But doesn't seem to work!
I give error:
PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

Please check this issue!

**Comment by lqmminh** [comment]
I have found issue.
Because this package write on VideoElement - html library, but VideoElement not support header authentication.
Looks like this will come to a standstill if flutter dev doesn't support it!

https://api.flutter.dev/flutter/dart-html/VideoElement-class.html
https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/lib/video_player_web.dart

**Comment by TahaTesser** [comment]
HI @lqmminh 
Thanks for filing the issue

Looks  like it is not supported on the web
Related https://github.com/flutter/flutter/issues/16466
https://github.com/flutter/flutter/issues/16466#issuecomment-827819973

**Comment by lqmminh** [comment]
@TahaTesser Tks for response!
Since 2018  🤦

**Comment by ditman** [comment]
I don't think token-based (Bearer) authentication is the current standard way of retrieving video from a website.

See this Stack Overflow question:

* [**using token based authentication for HTML5 video**](https://stackoverflow.com/questions/56146913/using-token-based-authentication-for-html5-video)

(One of the SO solutions covers downloading the video via fetch, but I'm not covering that, it's probably not what you need)

I think what you need from your CDN is something similar to [**Signed URLs**](https://cloud.google.com/cdn/docs/using-signed-urls) (or maybe [Signed Cookies](https://cloud.google.com/cdn/docs/using-signed-cookies)). Check the docs of your current CDN to see how to configure/retrieve these URLs securely.

I'm going to close this issue, since there's not much we can do from flutter web (in a performant way).
