### ISSUE TITLE
Automatic Icons Updater for Flutter

### ISSUE THREAD

**Issue by JaffaKetchup** [flutter/flutter#83741]
Hi Flutter team,
Great work on the v2.2 update btw!
However, can you please implement some sort of automatic icon updater so that the Flutter Icons get updated automatically when new Material Icons are released? There are now many missing icons.
This issue is to reopen/draw attention to the same problem as https://github.com/flutter/flutter/issues/27956, but needs a more permenant solution.
Thanks 👍.

**Comment by GroovinChip** [comment]
Suggestion: move material icons out into their own package, like cupertino icons

**Comment by bernaferrari** [comment]
I think it would be complicated because Flutter/Material relies on them in many places, and the icon's mapping may change from version to version, so the map icon (represented by 123456) might now point to what was the facebook icon.
Unless they just grab the top-10 most used material icons and set in stone in Flutter while let the other be free (which I think is what they do with iOS back button, for example).

**Comment by JaffaKetchup** [comment]
Well, idk then? Why not just update based in name rather than ID?

**Comment by bernaferrari** [comment]
Material icons is a font, that's how Flutter works with icons until we have native svg or something else support. As a font, each label has its own position. But this position changes when icons are re-generated.

**Comment by JaffaKetchup** [comment]
I have no idea, but that's not my job. If this can't be fixed easily, then so be it, but I hope Flutter can do something about this, because there are many missing icons.

**Comment by bernaferrari** [comment]
Which icons are missing? They updated a few weeks ago.

**Comment by JaffaKetchup** [comment]
I'm not sure exactly, see #27956

**Comment by JaffaKetchup** [comment]
Hi,
Any news about this?
Thanks 👍

**Comment by JaffaKetchup** [comment]
Is anything happening with this?

**Comment by chrissto79** [comment]
I miss Icons.route.

**Comment by JaffaKetchup** [comment]
Any news?

**Comment by iulian0512** [comment]
Icons.question_mark_outlined is missing

**Comment by superaldo** [comment]
Icons.handshake_outlined is missing :s

**Comment by makhele** [comment]
Icons.handshake 
Icons.calendar_month

**Comment by GibreelAbdullah** [comment]
Icons.heart_broken 💔

**Comment by JaffaKetchup** [comment]
Icons.save_as missing

**Comment by derDeno** [comment]
add_card_outlined is missing too

**Comment by miketrebilcock** [comment]
It's mentioned in one of the other threads, but I found this package:

https://pub.dev/packages/material_design_icons_flutter

by https://github.com/ziofat saved the day for me.

**Comment by tphinney** [comment]
Just noting that in the font versions of the icons, both glyph names (via ligature) and codepoints are completely stable from version to version. Even if we delete a duplicate glyph from the font, we maintain BOTH the old ligature and the old codepoint in the next version of the font.

If somebody is talking glyph ID (GID) then yes, that is literally the physical ordering of glyphs in the font, and is not guaranteed to be stable from one version to the next in this or any other font. GID references should not be used in that way.

**Comment by bernaferrari** [comment]
@tphinney I'm not sure which was used, but it changed every version, it was a nightmare. Now they made it stable.

**Comment by JaffaKetchup** [comment]
So maybe what we need then, as well as a way to automatically get the latest icons (in another package like someone at the top of the thread suggested) is a map middleman between the package and app. This would ensure that they don't change unexpectedly.

And just a note about separating into a separate package. The default Flutter project automatically imports Cupertino Icons to demonstrate how to use the pubspec. Would it not be too difficult to do the same thing with a new official Material Icons package?

**Comment by tphinney** [comment]
As the contractor doing the variable font, I would like to understand what the problem was before, how the characters were being referenced—just to make sure it does not become a problem in the future. Or for me to warn if the referencing method being used is “wrong.” Not knowing exactly what broke means I can’t promise it will remain stable!

With regards to some of the other points in this thread, for add_card_outlined and handshake_outlined, I will note as a general thing, however, that in the source variable font (from which other font versions derive, currently), some of the named glyphs with "outline" in the name no longer exist as separate glyphs. The default versions are outlined, and a filled version is accessible by using the Fill axis. (And you can even animate the transition if you want.) That is definitely true for these two characters.
