### ISSUE TITLE
Webview & Null Safety

### ISSUE THREAD

**Issue by lyntree** [flutter/flutter#83891]
Hello,

Right, this all has started due to the 'Flutter Web View Plugin', trying to embed a live view for my client's page on 'Mixcloud - https://www.mixcloud.com/live/Audio_Damage_Radio/ 

It works on Android - No Issues!
IOS, however... Countless issues! 

Fair enough, this particular page does not work on the emulators...

So I've tried to get it to work, then Flutter told me I had to migrate the application over to Null Saftey.... I've managed to migrate all the packages over but once more seems to matter what it doesn't like this plugin because it's still claiming that. the 'Flutter Web view' Package is not null safety 'despite' it's listed on pub dev as[ 'null safety'..](url)

Can someone please advise assistance as to what now because the 'code' has apparently now been depreciated and the application will not let run or build?

any insight would be greatly appreciated,

kindest regards,

Lyntree

<img width="1418" alt="Screenshot 2021-06-03 at 12 39 12" src="https://user-images.githubusercontent.com/71215061/120659339-2de77900-c47e-11eb-905e-0aa0e4d7871b.png">

**Comment by stuartmorgan** [comment]
Please paste logs in rather than posting screenshots of errors. The latter is hard to read, and not searchable.

The deprecation warnings are harmless, and are there because you're targeting iOS 9.0+ but the plugin supports 8.0+. The error is:
```
ld: framework not found fluttertoast
```

That's a third-party plugin; you'll need to report your issue to its developer.

(You haven't provided any details about the null safety issue you referenced, and they have nothing to do with what's in your screenshot. Please file a new issue about just that piece, with full error logs of the relevant error.)
