### ISSUE TITLE
Devicelab performance test results are wildly different than local results

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#83938]
## Description
I've landed [a PR](https://github.com/flutter/flutter/pull/83371) that locally decreases the time for the `linux_platform_channels_benchmarks/platform_channel_basic_binary_2host_1MB` test ~50%, but when executed on devicelab it is only [showing ~15%](https://flutter-flutter-perf.skia.org/e/?begin=1621972627&end=1622677144&queries=sub_result%3Dplatform_channel_basic_binary_2host_1MB%26test%3Dlinux_platform_channels_benchmarks&requestType=0).

Similar work on iOS was shown to have ~45% decrease so a number closer to that is expected.

@Hixie commented on possibilities for the discrepancy.  I'm no sure if there is much we can do about this but it seems to throw the performance tests for android in question:

_"Different hardware, different OS, difference in how long since someone touched the display, different temperature in the room, the engine built with slightly different alignment causing the CPU to use different microcode to decode the instructions... any number of things can affect performance numbers unfortunately."_

## Steps to reproduce
```
cd $DEVICELAB
../../bin/cache/dart-sdk/bin/dart bin/run.dart -t platform_channels_benchmarks
```

## Flutter doctor
```
aaclarke-macbookpro2:devicelab aaclarke$ flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.188, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.188 at /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 14b2e7ffee (2 hours ago), 2021-06-03 10:50:11 -0700
    • Engine revision 939fb62b30
    • Dart version 2.14.0 (build 2.14.0-176.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Pixel 4a (mobile) • 11121JEC203798 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos          • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 90.0.4430.212
```

**Comment by gaaclarke** [comment]
I'm not sure who manages the devicelab, maybe @godofredoc has some ideas about this issue.

**Comment by Hixie** [comment]
Comparing numbers on performance tests only makes sense when you're comparing the exact same environment from data point to data point. This isn't particularly specific to Flutter or devicelab, or even to computers. It's just how empirical science is.

**Comment by godofredoc** [comment]
I'd start using the same phone and android os version. From the doctor output it seems like are using a Pixel 4a while the device lab is using moto g4.

**Comment by gaaclarke** [comment]
@Hixie the comparison is for the same environment.  The disparity is in the ratio between 2 data points in the exact same environment, for 2 different environment.

The same thing would happen if you switch an O(n^2) to an O(n) algorithm.  You'd expect the same ballpark ratio across multiple environments.

I'm not sure what is going on here, but if we are running performance tests in an environment where performance tests aren't showing proper results for algorithm changes we aren't getting good results.  Like maybe the phone is setup in low-energy mode so the operating system isn't scheduling the process at a rate where changes in algorithm would be evident.

**Comment by Hixie** [comment]
Even the magnitude of the difference between two data points can't be reliably compared between two environments. For example, if environment Q has 1GB of RAM and environment R has 4GB of RAM, and an algorithm change reduces total memory usage over time from 2GB to 1GB, then R might not change at all, while Q might improve dramatically, since while total usage was 2GB maybe Q had to do a GC every 16ms while at 1GB it doesn't have to do a GC at all (same as R in both modes).

There are lots of examples like this.

It's possible there are specific conditions that are making devicelab tests misleading in some way, but the same is true for local tests. For example, when I'm doing local tests I will often use the following (flawed) procedure:

1. Unlock phone and plug it in.
2. Launch test in condition A.
3. Launch test in condition B.

This is flawed because step 1 causes the CPU to be throttled up (I touched the screen), and eventually the CPU throttles back down, such that what I'm really comparing is the performance of my phone over time after being touched. It's also flawed because running the tests can heat the device, and at the second test it might be running in a thermally-reduced regime. It's also flawed because maybe the resources used by A and B are cached by the time B runs. Also maybe I received a text message during one of the tests and this used some of the CPU in one test but not the other. I've seen any number of weird things affect mobile device performance, including the angle relative to gravity, the ambient temperature, the time of day, wifi and network conditions, the acceleration the device is experiencing, the unfortunately-timed occurrence of political events triggering network-wide emergency messages...

**Comment by gaaclarke** [comment]
Yea, fair point.  The problem is that we know ~50% is closer to the _real_ number you'd see if the number of cycles were counted to perform this algorithm.  That's what we would like to be evaluating, how do we get our performance tests to show results that are more inline with the gains we would expect on a imaginary computer where none of these things are an issue.

If the operating system is wasting its time throttling itself for heat and energy and swapping memory and triggering garbage collection, it isn't really telling us much about the work we are actually doing.  It's just telling us how shitty the setup is.

**Comment by Hixie** [comment]
At the end of the day, what matters is what end-user devices do. And those are very much prone to heat and energy and swapping memory and triggering garbage collection. I caution against assuming that the number you expect to see is "more correct" than the number you see in a more controlled environment. It's quite possible that the change you made in fact does not achieve the theoretical results on the kind of devices we use in devicelab (which are real devices representative of the kind of device used by more people than the device you tested with locally).

I guess what I'm saying here is that the premise of this issue is that the difference you're seeing is due to a problem with the devicelab, but there's no reason to believe that hypothesis is any more likely than any number of other hypotheses. The thing to do is to test the various hypotheses, e.g. by getting the same kind of hardware and testing locally on that, attempting to replicate the setup of the devicelab as closely as possible, finding differences between the device lab environment and the "local test" environment that could be affecting the result. Maybe the result of this is we find that "real world" conditions differ in some key specific way from devicelab conditions, and then we can adjust the test conditions accordingly. But maybe the result is that it turns out the situation is more subtle than it seems, and the real gain on some devices _is_ closer to 15%.

**Comment by gaaclarke** [comment]
> and the real gain on some devices is closer to 15%.

Yea, that's true and isn't so far fetched.  I guess my concern would be that is 15% the outlier?

One thing I can pretty reasonably say is that the function f where `f(device_manufacture_year) = time_ratio_between_prs` should have an asymptote around ~50% based on the results from iOS and running on a newer Android devices.  That would mean to me that a test harness that returns ~50% would be more useful.  But we also have the problem that our test device for performance tests is becoming non-representative of our user base as time progresses, but upgrading that device would invalidate history of the results...

Ultimately I have to communicate a number to our users and saying "performance test of 15% to 50% depending on the device" is kind of lame, especially if 15% is an outlier or non-representative of our user's userbase.

**Comment by Hixie** [comment]
Our premise is that performance matters more on lower-end devices, for a variety of reasons. That's why our test devices are low-end.

> But we also have the problem that our test device for performance tests is becoming non-representative of our user base as time progresses

I think you may be surprised as to how representative it actually is. There's some 4+ billion users of mobile phones out there, and I assure you most are not using high-tier (or even mid-tier!) devices. There's another 4+ billion people who aren't yet active mobile phone users, and their first device is highly unlikely to be on the high end.

> but upgrading that device would invalidate history of the results...

Invaliding the history every few years is fine.

For what it's worth, there is an effort underway to replace the Moto G4s in our devicelab, but the reason is not that they are too slow (the currently preferred replacement, the Xiaomi Redmi 6A, is arguably slightly slower) it's just that the Moto G4 is no longer a phone we can physically obtain, which makes maintenance hard.

> Ultimately I have to communicate a number to our users

Not really, right? I mean, our job is just to make it better, we don't have to community specific details of performance improvements.

> and saying "performance increase of 15% to 50% depending on the device" is kind of lame, especially if 15% is an outlier or non-representative of our user's userbase.

I would just say 15%, if for some reason we _have_ to give a number. Under-promise, over-deliver.

**Comment by gaaclarke** [comment]
Okay, my suggestion is to run the performance tests on 2 different devices, one that is representative of our low-end device and one that is a high-end device.  That will give us both types of measurements we are interested in.  The low-end device measurements will make sure we don't break real world performance for low-end devices and the high-end devices will ensure that we are making the correct investments and improvements for the future of Flutter.

At some point we'll have to do some calculus about wether an optimization is worth it and we'll need both pieces of information.  Imagine an optimization that decreases performance 5% on old devices but increases it 10% on new devices, like an extra layer of indirection that allows us to take advantage of a new API.

**Comment by Hixie** [comment]
I believe that's the current proposal, but doing that is non-trivial from a financial and maintenance perspective.

For what it's worth, I would not conflate "low-end device" with "old device". Average new devices in large and growing markets like India and Africa _today_ are slower than the now old Moto G4, which was a moderately good device in its day. Slow devices may have access to newer APIs than older (but faster) devices. Investing in the future of Flutter may mean largely ignoring the mostly unrepresentative high-end devices.

**Comment by godofredoc** [comment]
We have many of those phones in the lab, if you need one, we can leave it for you in the 1842 lab for pick up.

**Comment by gaaclarke** [comment]
Thanks, ray is sending me one.

**Comment by gaaclarke** [comment]
I got the device on and verified the devicelab results:
**phone info**
```
    • Moto G 4 (mobile)                    • ZY2245H6KS                           • android-arm    • Android 7.0 (API
      24)
```
indirect bytebuffers:
```
I/flutter (10116): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 621.1 µs
I/flutter (10116): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 13617.5 µs
I/flutter (10116): BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 1318.6 µs
I/flutter (10116): BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 9393.5 µs
```

direct bytebuffers:
```
I/flutter (10435): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 536.0 µs
I/flutter (10435): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 13805.7 µs
I/flutter (10435): BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 864.9 µs
I/flutter (10435): BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 8311.2 µs
```

So thats ~11% which is in line with devicelab results.  I'll try flashing the device to a new OS to see what effect that has as well.

**Comment by gaaclarke** [comment]
I was unable to update the phone to 8.1 like the internet lead me to believe but I did run the test after a fresh install:
**indirect bytebuffers**
```
I/flutter ( 8533): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 545.5 µs
I/flutter ( 8533): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 13540.1 µs
I/flutter ( 8533): BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 1267.7 µs
I/flutter ( 8533): BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 9431.8 µs
```

**direct bytebuffers:**
```
I/flutter ( 8264): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 431.6 µs
I/flutter ( 8264): BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 13457.0 µs
I/flutter ( 8264): BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 858.4 µs
I/flutter ( 8264): BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 7876.6 µs
```

That's a 20% speed increase instead of an 11% speed increase.  So, there may be a system setting that is affecting the performance results.

**Comment by godofredoc** [comment]
Can we close this one? or are there any action items?

**Comment by gaaclarke** [comment]
@godofredoc it is a bit concerning that I was able to see a 9% difference in measurements after resetting the device.  That means that either:
1) Android devices slow down over time for some reason
1) There was a system setting that was slowing down the measurement that got wiped out when the device was factory reset

What are we doing to mitigate those risks?  Are we factory resetting the devices regularly?  Are all devices flashed to the same exact settings?

**Comment by godofredoc** [comment]
The device you got was not from the devicelab it would be difficult to know which configurations it had.

1. Does this correlate with the data from the devicelab? I would expect a 9% difference from early 2020 to today in the  skia dashboards.
2. If you can find out which setting was affecting the performance we can add the correct values to the provisioning steps.

Regular factory resets would be a manual process expensive in terms of time. If you can provide a set of steps to clean up devices to get them to an expected performance without a factory reset we can potentially automate the process.

All the devices are provisioned in the same way with the same configurations.

**Comment by gaaclarke** [comment]
The device was a Moto G4 like devicelab.  The performance test results before the factory reset were about 200ms slower than devicelab measurements.  After factory reset they were about 200ms faster than devicelab.  So, it's hard to tell if my device obviously had something weird set.

It's impossible for me to know what system setting were wiped out in the process since I didn't set up that device.  Even if I did, there are too many variables to pinpoint exactly what was the cause.

How about this, on Android there can be background processes running.  A factory reset would have potentially removed them.  Are we killing all background processes before running a new devicelab test?  ( Here is instructions on how to do it through adb: https://stackoverflow.com/questions/31079853/how-do-i-kill-all-active-tasks-apps-using-adb/31079988 )

**Comment by godofredoc** [comment]
I believe this is something that we can add to the device doctor as a health check/recovery step. @keyonghan is this something that can be added to the device doctor tool?

**Comment by keyonghan** [comment]
> I believe this is something that we can add to the device doctor as a health check/recovery step. @keyonghan is this something that can be added to the device doctor tool?

Sounds a good fit to device doctor. Adding to my to-do list.

**Comment by keyonghan** [comment]
Actually this is not suitable for device doctor health check. Swarming server keeps running health check around every 1 min. It will kill existing running adb processes from the test if we add the logic here.

As for recovery, the device is already set to reboot whenever a failure happens.

Recipe is a better place to enforce this by adding a step to clean up in the beginning.

**Comment by keyonghan** [comment]
`on_before_task` sounds an option. Let me double check.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
