### ISSUE TITLE
[plugin_tools] check-version should make sure the old version of the updated plugin is published

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#83998]
It would be beneficial for the plugins and packages repo's version-check ci job to make sure the exiting versions have published on HEAD~ or merge base in pre-submit.

There are many times that versions of plugins are skipped due to lack of this check.

This can benefit both manual publish workflow and auto publish workflow. 

The version-check will work like below:

1. Get the versions at current TOT (master or branch).
2. Get the versions in the base-sha.
3. if the versions in the base-sha are published, proceed with the version-check to make sure the new version is valid.
4. If the versions in the base-sha are not published, and if the current versions are not revert, report failure.

**Comment by stuartmorgan** [comment]
> It would be beneficial for the plugins and packages repo's version-check ci job to make sure the exiting versions have published on HEAD~ or merge base in pre-submit.

I don't know that I agree with this. Why is blocking unrelated PRs a desirable way of handle publish failures? What problem is being solved by preventing new code from *landing*?

In the extreme case, you're saying that if there were a temporary issue that made it impossible to publish packages for a day or two, the tree should be closed for that time, which sounds terrible.



> There are many times that versions of plugins are skipped due to lack of this check.

I would argue that they've been skipped in the past because it was an entirely manual process with no established process to make sure there was follow up on landed PRs. The latter has already been addressed, and I hear the former is almost done 🙂

**Comment by cyanglaz** [comment]
> I don't know that I agree with this. Why is blocking unrelated PRs a desirable way of handle publish failures? What problem is being solved by preventing new code from landing?

> In the extreme case, you're saying that if there were a temporary issue that made it impossible to publish packages for a day or two, the tree should be closed for that time, which sounds terrible.

I was not purposing blocking the tree if any plugin has not published. I was purposing to only block landing PRs if the PR updates a plugin, whose previous version on TOT has not published. Unrelated PRs (whether it's updating different plugins, a none-version change update to the same plugin, or a tooling change) should not be blocked. Do you think this is still too extreme?

With auto-publish process, I agree that this won't happen with the GA solution. Because we can queue up GA workflows to make sure publishing jobs only execute sequentially. That is, a publish job won't start until all the previous publish jobs are successful. 
However, with the LUCI solution, which we might end up implementing, I'm not sure how reliable it is.

**Comment by stuartmorgan** [comment]
Having though about this some more: I think the framing of the problem is not what we want. The actual issue we want to solve isn't actually "skipped versions" it's "unpublished versions". If we land version 1.0.1, but don't publish it, **that** is the problem; it doesn't only become a problem once we have a version 1.0.2. When we publish 1.0.2 may be when we have tended to notice that problem, but it was already a problem before that. Consider a rarely-updated plugin: if we don't publish an update, and nobody changes changes that plugin again for 3 months, we've had an issue for 3 months, not just when that new plugin is posted. So for non-race-style issues, this isn't solving the right problem; we need to know **when publishing fails**, not find out whenever we next try to change the plugin.

And for rapid updates, I don't think it actually matters. If we publish 1.0.5, then 1.0.4 a few minutes later, no harm is done as long as 1.0.4 was published from the right hash. (And, very rarely, we actually want to do this deliberately. See [path_provider_windows 0.0.5](https://pub.dev/packages/path_provider_windows/versions) for instance).

I think the only thing we would actually want to rigidly enforce is that we shouldn't allow updating the version to a version that has already been published (e.g., attempting to do a pure revert of a PR that has been published). So I think we should revisit the design discussions that led to this.

Maybe moot given the above, but some specific responses:

> I was not purposing blocking the tree if any plugin has not published.

Maybe I misunderstanding the way this would work on master then; I thought that since on master checks run against all plugins, any subsequent commit would fail in post-submit if the previous commit hadn't been published.

> Unrelated PRs (whether it's updating different plugins, a none-version change update to the same plugin, or a tooling change) should not be blocked. Do you think this is still too extreme?

My current view is that a PR that is updating the same plugin is also unrelated to the fact that a publishing event hasn't happened yet, so yes.

> Because we can queue up GA workflows to make sure publishing jobs only execute sequentially. That is, a publish job won't start until all the previous publish jobs are successful.
However, with the LUCI solution, which we might end up implementing, I'm not sure how reliable it is.

Are there actual downsides to non-sequential publishing that I'm forgetting about?

**Comment by cyanglaz** [comment]
>And for rapid updates, I don't think it actually matters. If we publish 1.0.5, then 1.0.4 a few minutes later, no harm is done as long as 1.0.4 was published from the right hash. (And, very rarely, we actually want to do this deliberately. See path_provider_windows 0.0.5 for instance).

I didn't know this. The whole reason I think this proposal is useful is behind the assumption that versions on pub must be published sequentially. Closing the issue. 

>I think the only thing we would actually want to rigidly enforce is that we shouldn't allow updating the version to a version that has already been published

I agree, do we have an issue for this?

**Comment by stuartmorgan** [comment]
> I agree, do we have an issue for this?

I don't think I filed it, no.
