### ISSUE TITLE
Devicelab bots should always upload full attached device log

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#84000]
For example, it should start `adb logcat` or `idevicesyslog` and dump that to something in the `env['FLUTTER_LOGS_DIR']`.

We should be able to do this from the test harness itself. This will catch issues where we either incorrectly filter logs, or find that we're unable to make sense of the logs from a tooling perspective.

**Comment by dnfield** [comment]
@jmagman - I'd like to make `flutter log` work on iPhone's without observatory/lldb. From a local experiment, it looks like idevicesyslog works with an iOS 14.4.2 phone. Do you know what's up?

`flutter logs` works for me locally if I remove https://github.com/flutter/flutter/blob/0acf53e3108b2ab0739e2b5e458dc113b94f65a7/packages/flutter_tools/lib/src/ios/devices.dart#L730-L733

**Comment by jmagman** [comment]
> For example, it should start `adb logcat` or `idevicesyslog` and dump that to something in the `env['FLUTTER_LOGS_DIR']`.

The `FLUTTER_LOGS_DIR` logic is in:

https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/dev/devicelab/lib/framework/host_agent.dart#L23

Currently used like:
https://github.com/flutter/flutter/blob/2d862494353447ed446ac449ae725dbe32b07295/dev/devicelab/bin/tasks/module_test_ios.dart#L362-L364



> @jmagman - I'd like to make `flutter log` work on iPhone's without observatory/lldb. From a local experiment, it looks like idevicesyslog works with an iOS 14.4.2 phone. Do you know what's up?
> 
> `flutter logs` works for me locally if I remove
> 
> https://github.com/flutter/flutter/blob/0acf53e3108b2ab0739e2b5e458dc113b94f65a7/packages/flutter_tools/lib/src/ios/devices.dart#L730-L733

It would be awesome to get `flutter logs` working again https://github.com/flutter/flutter/issues/44199.  However, we shouldn't remove the `lldb` attaching/log parsing that was added to workaround the loss of those logs since it let us remove all the mDNS port discovery reliance for `run` and `drive` (see https://github.com/flutter/flutter/pull/66399 for details).  Using `idevicesyslog` again for `logs` and `attach` would be great.

**Comment by dnfield** [comment]
I'm not sure if using `HostAgent` is the right pattern for this, mainly because I want this to be done for all commands on CI, and _optionally_ when doing a local run (we should't fill up dev machines with logs they can easily get themselves).

WDYT?
