### ISSUE TITLE
FocusableActionDetector DartPad sample is broken

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#84009]
The DartPad sample for [FocusableActionDetector](https://api.flutter.dev/flutter/widgets/FocusableActionDetector-class.html) shows errors:

```
error: The name 'ShortcutActivator' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [tmp_focus_bug] lib/main.dart:53)
error: The name 'ShortcutActivator' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [tmp_focus_bug] lib/main.dart:54)
error: The keys in a const map literal must be constant. (non_constant_map_key at [tmp_focus_bug] lib/main.dart:55)
error: The method 'SingleActivator' isn't defined for the type '_FadButtonState'. (undefined_method at [tmp_focus_bug] lib/main.dart:55)
error: The argument type 'Map<dynamic, Intent>' can't be assigned to the parameter type 'Map<LogicalKeySet, Intent>?'. (argument_type_not_assignable at [tmp_focus_bug] lib/main.dart:103)
```

FYI @gspencergoog

**Comment by gspencergoog** [comment]
I'm very confused. How did `ShortcutActivator` make it into a stable docs sample? That class is available on dev, but not on stable, and I wouldn't expect a sample to be merged before the class exists (mainly because it would fail analysis).

I would expect this to not work on master-api.flutter.dev because Dartpad doesn't use the dev channel, but anything on api.flutter.dev should be functional.

**Comment by piedcipher** [comment]
FocusableActionDetector's sample available at mentioned link is working fine. Hence closing this one!
