### ISSUE TITLE
Recipes roller is failing led tests

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#84290]
The recipe's roller is currently failing several tasks:

https://flutter-review.googlesource.com/c/recipes/+/14381

**Comment by yusufm** [comment]
The CL currently has merge conflicts. @godofredoc should this be closed in exchange for a newer roll?

**Comment by godofredoc** [comment]
There was a merge conflict, abandoned the CL to allow the autoroller to create a new one.

**Comment by godofredoc** [comment]
Waiting for https://flutter-review.googlesource.com/c/recipes/+/14620 to land

**Comment by keyonghan** [comment]
Latest roll fails again: https://flutter-review.googlesource.com/c/recipes/+/14800
It failed on builder: `Mac Unopt` - the fix is to [run step under Goma context](https://flutter-review.googlesource.com/c/recipes/+/14820/1/recipes/engine_unopt.py) explicitly.

Though CL https://flutter-review.googlesource.com/c/recipes/+/14820 passed all CQ dry runs, we may have builders not picked up in the dry run but need to update to run under Goma context explicitly. Otherwise builds will fail with the rolling merged.

@iskakaushik @zanderso Anybody can help identify the steps that need to run under Goma context? This is blocking the recipes dependences rolling.

**Comment by godofredoc** [comment]
Some more context for this issue:

https://github.com/flutter/flutter/issues/84618

@dnfield, @blasten and I are meeting tomorrow to discuss how to migrate the failing scripts to GN/Ninja.

**Comment by CaseyHillers** [comment]
It looks like the roll was abandoned, but a new CL wasn't generated. Is there a manual way to kick this off?

**Comment by godofredoc** [comment]
Let me try to abandon it.

**Comment by godofredoc** [comment]
Isolated has been deprecated and some of the isolated module methods have been removed blocking the recipe's dependency rolls.

**Comment by godofredoc** [comment]
Some changes to migrate to CAS have landed but we are missing a few more (engine_unopt, web_engine):

https://flutter-review.googlesource.com/c/recipes/+/15920
https://flutter-review.googlesource.com/c/recipes/+/16127
https://flutter-review.googlesource.com/c/recipes/+/16129

**Comment by godofredoc** [comment]
engine_arm declared the dependency but they were not using it. Removing the declaration of the module:

https://flutter-review.googlesource.com/c/recipes/+/16200

**Comment by godofredoc** [comment]
Flutter recipes are finally using the latest dependencies.
