### ISSUE TITLE
[in_app_purchase] Document changes to `originalPrice`

### ISSUE THREAD

**Issue by rocboronat** [flutter/flutter#84428]
I'm checking the migration guide on pub.dev (https://pub.dev/packages/in_app_purchase/changelog) and it's almost perfect. But some things that change don't appear there.

1. `IAPSource` disappeared but we don't know where. It was useful to do things like
```dart
final source = purchases[0].verificationData.source;
if (source == IAPSource.GooglePlay) {
  return await launchGooglePlayPurchaseCheckCall(purchases);
}
```

Previously, IAPSource was an enum like this:
```
/// Which platform the request is on.
enum IAPSource { GooglePlay, AppStore }
```

Now, it's just a String 😢 Is that correct? May we know the String values beforehand?

2. `ProductDetails` of a bought item used to have a `skuDetail` field that included some values, as the `originalPrice`, that doesn't appear now. It's useful to know how much the user paid when buying the SKU. The field `ProductDetails.price` that we can use now is the price of the product nowadays. In case the price changed, the list of purchased items will show a wrong price. If I'm wrong, please update the documentation of the `price` field of the `ProductDetails`, that says `The price of the product, formatted with currency symbol ("$0.99")` to clarify that the price that appears it the one the user paid some time ago.

**Comment by TahaTesser** [comment]
Hi @rocboronat 
Thanks for filing the issue
1. https://github.com/flutter/flutter/issues/83905 
2. Could be documentated

**Comment by mvanbeusekom** [comment]
Hi @rocboronat, 

Here is my attempt to answer your questions:

1. The `IAPSource` enum has indeed be replaced by a `String` value. This is done to make it easier to introduce support for other store fronts in the future without having to introduce a change in the `in_app_purchase_platform_interface` package because of the need to introduce a new enum value. Now each platform implementation (at the moment these are `in_app_purchase_android` and `in_app_purchase_ios`) define a constant called `kIAPSource` which contain the string value used as source for that particular implementation. For Android the value is defined [here](https://github.com/flutter/plugins/blob/f469f22c1ff5b9f6be1967d8090cf8a62c7e4001/packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform.dart#L25) and for iOS you can find the value [here](https://github.com/flutter/plugins/blob/f469f22c1ff5b9f6be1967d8090cf8a62c7e4001/packages/in_app_purchase/in_app_purchase_ios/lib/src/in_app_purchase_ios_platform.dart#L19). 

2. It is still possible to access the platform specific product or purchase information however you need to do a little bit of extra work. During the release of version 1.0.0 of the in_app_purchase plugin this was missed in the documentation but is now rectified. Please read the [following documentation](https://pub.dev/packages/in_app_purchase#accessing-platform-specific-product-or-purchase-properties) which explains how to access the platform specific information of a `ProductDetails` or `PurchaseDetails` object.

If you have any more questions please leave a comment and I will try to answer them.

**Comment by rocboronat** [comment]
Cool! That's it. Thanks a lot, team 😊

**Comment by mvanbeusekom** [comment]
@rocboronat Thank you for your response and confirming that this answered your questions. Since the only open thing is to document the new structure of the `IAPSource` and this is also tracked in issue #83905, I will now close this issue. If you feel this is incorrect please let me know and I would be happy to re-open it again.
