### ISSUE TITLE
need a multi-platform way to run Dart code in the background of a Flutter app that works on the web

### ISSUE THREAD

**Issue by csells** [flutter/flutter#84448]
## Use case
It's common to want to push computationally expensive calculations onto a background thread to avoid freezing the UI thread, e.g.

* image compression
* frame detail computation for Flutter DevTools
* calculating the last digit of pi
* etc.

This can be accomplished in Dart via the [`compute` function](https://docs-flutter-io.firebaseapp.com/flutter/foundation/compute.html) but does not work in Flutter web apps. The web has a similar mechanism via [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) but they provide a subset of functionality that Dart provides, namely all data pass between a worker and the UI thread must be JSON-serializable, which is not a limitation of the `compute` function.

## Proposal
I propose a new function, e.g. `computeWithJson` (or something with a better name) that works in a multi-platform manner and respects the limitations of Web Workers. It would bottom out in a call to `compute` on platforms that supported it and in Web Workers on the web. This would allow developers to write background processing code in a multi-platform manner and solve the 80% case (at least).

**Comment by jonahwilliams** [comment]
The problem with the `compute` API, isolates, and web workers in general is that their capabilties are entirely different. There are a lot of assumptions baked into `compute`, beyond the ability to pass data back and forth, namely:

* You can start an isolate with a static function signature
* Starting an isolate is fast enough that it makes sense to do so on-demand
* Starting an isolate requires no other build/platform configuration

OTOH, web workers along with dart2js have a set of restrictions that are contradictory to the above:

* We have no way to support launching a JS bundle with anything other than its main method. This means that in order to use a web worker you have to separately compile an entirely new main.dart and ship it with your application.
* The performance of starting a new web worker is significantly then starting up another isolate in AOT, this favors keeping persistent background workers instead of spinning up on demand.

**Comment by csells** [comment]
If we built something that worked for web, even within the restrictions you describe, could it also be made to work for the other platforms?

**Comment by jonahwilliams** [comment]
If we make something that is harder to use than dart:isolate - which web workers certainly are - who would use it?

**Comment by csells** [comment]
The people who would use it are the ones writing Flutter apps that have no way to run computationally intensive tasks in the background today, e.g. Flutter DevTools.

**Comment by jonahwilliams** [comment]
I mean who would use it over `dart:isolate` in mobile/desktop space. Agree that it would be useful for web targets, but that doesn't imply a unified API to me

**Comment by csells** [comment]
If they're not targeting web, a developer can use dart:isolate w/o trouble today. If they are targeting web, using the feature we're talking about on the web + zero code to make it work on other platforms is better than writing two code paths.

**Comment by yjbanov** [comment]
Workarounds:

We already support web workers. All you need to do is compile a piece of Dart code to JavaScript and load it in a web worker. You can talk to it using message passing as normal. We cannot offer this feature via `dart:isolate` as @jonahwilliams describes.

`computeWithJson` can be implemented as a package (e.g. refer to a function by string, then look-up the function from a map on the "other side", e.g. isolate or web worker). The data that's passed needs to be JSON-able.

**Comment by csells** [comment]
Great! Do we document the process of setting up background processing for Flutter web apps?

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/33577
