### ISSUE TITLE
english_words WordPair

### ISSUE THREAD

**Issue by Sameer939** [flutter/flutter#84576]
It should be WordPair.random().asPascalCase instead of wordPair.asPascalCase in codelabs

**Comment by anshulshacks** [comment]
I believe you are talking about the guide written at this link: [Write your first Flutter app](https://flutter.dev/docs/get-started/codelab)

If so, a variable is assigned in the `build()` function in the MyApp stateless widget.

```
final wordPair = WordPair.random();
```

Since `wordPair` is defined as `WordPair.random()` we can just use the `wordPair` variable when using the pascal case method on it.

Let me know if that makes sense or if you meant something else!

**Comment by domesticmouse** [comment]
@Sameer939 can you give more detail as to what URL you are referring to? The code that @anshulshacks links to looks correct to me. It's even tested: https://github.com/flutter/codelabs/blob/master/startup_namer_null_safety/step2_use_package/test/widget_test.dart
