### ISSUE TITLE
Ternary expressions no longer supported after null check

### ISSUE THREAD

**Issue by ljg6861** [flutter/flutter#84638]
On Flutter 2.2.2 - Channel Stable

What used to work:
`child: child ?? kIsWeb ? MyWebApp() : MyApp()`

Is now throwing error:
`Expected a value of type 'bool?', but got one of type 'MyWebApp'`

What fixes it:
Rewriting to
`child: child == null? kIsWeb ? MyWebApp() : MyApp():child`
Or taking out ternary expression:
`child: child ?? MyWebApp()`

Platform used: Web
Have not tried on other platforms

**Comment by TahaTesser** [comment]
Hi @ljg6861

You need to wrap your ternary expression in a bracket

If you provide this 
`child ?? kIsWeb ? MyWebApp() : MyApp()`

If `child` is null,  `kIsWeb` is returned 

SInce I cannot see what `child` widget suppose to be your code but it should work similar 
Try this
`child ?? (kIsWeb ? MyWebApp() : MyApp())`

Here is the complete code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

@immutable
class App extends StatelessWidget {
  Widget? child;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: child ?? (kIsWeb ? MyWebApp() : MyApp()),
    );
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp',
      home: Scaffold(
        appBar: AppBar(
          title: Text('MyApp App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}

class MyWebApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyWebApp',
      home: Scaffold(
        appBar: AppBar(
          title: Text('MyWebApp App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}

``` 

</details>


Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
