### ISSUE TITLE
REPLACEMENT CHARACTER (�) for not well-formed UTF-16 character

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#84693]
## Use case

Currently `Text` widget needs well-formed UTF-16 text to render, and throws `string is not well-formed UTF-16` error if its not

```dart
Text('😈'.substring(0,1))
```

it's very dangerous, consider the following scenario

- we have an application and let users to leave comments
- a hacker leave a comment with not well-formed UTF-16 character
- other users cannot open app because it crashes with `string is not well-formed UTF-16` error

## Proposal

Simply use [Specials (Unicode block)](https://en.wikipedia.org/wiki/Specials_(Unicode_block))

> U+FFFD � REPLACEMENT CHARACTER used to replace an unknown, unrecognized, or unrepresentable character

� is the most common used character to ignore not well-formed UTF-16 characters

**Comment by sm2017** [comment]
Flutter web is safe and uses � but mobile not

**Comment by sm2017** [comment]
@darshankawar Please add a high priority tag, As it can down whole flutter application

**Comment by Hixie** [comment]
If you are allowing users to insert invalid Unicode data into your databases, that is a security concern quite aside from any issue with Flutter misrendering text. You should sanitize user input.

**Comment by sm2017** [comment]
@hixie why it's a security issue? Can you explain more, or refer me to an article?

**Comment by sm2017** [comment]
@Hixie Also, can you please tell me how you sanitize it? I read your changes, but I cannot understand how it works

**Comment by Hixie** [comment]
There are many potential issues with invalid Unicode text, it's hard to say exactly which issues you would be prone to without doing a security review of your specific code. But for example, suppose you don't sanitize Unicode in usernames, and two different parts of your system treat invalid Unicode data differently, so that in one place two usernames compare equal and in another the same two compare as different. This could lead to a user being able to log in as another by creating a new "different" user name that's invalid in a slightly different way so that it gets treated as a new account in account creation but gets treated as the same account in login. There's tons of examples like that.

The answer about how to sanitize your input really depends on where you're getting it from. If you're decoding UTF-8 data using dart:convert, set allowMalformed to false (the default) and reject anything that throws FormatException. If you're accepting input from a text field, verify that it doesn't contain unpaired surrogates. If you're manipulating text that might contain characters outside the basic multilingual plane (or, indeed if you care about Unicode (extended) grapheme clusters), use package:characters rather than the String API directly, or, if you can't use package:characters, at least use the `runes` API rather than manipulating UTF-16 code units.

**Comment by sm2017** [comment]
@Hixie WOW! Awesome answer!
Thank you
