### ISSUE TITLE
AccentColor deprecation needs link to migration guide

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#84748]
We have a nice migration guide for the `AccentColor` change, but it's not linked in the API itself: 
https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide
![image](https://user-images.githubusercontent.com/2319867/122310147-89752600-cec4-11eb-800a-493074e223fe.png)

In this case, we include a brief warning ("'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. This feature was deprecated after v2.3.0-0.1.pre..") but there's no help for a user to know how to use colorScheme, and it turns out to be pretty intricate. 

I had to go off and Google to find the solution, and I think it could and should be a lot easier for us to walk users through this kind of breakage.

**Comment by bernaferrari** [comment]
> I had to go off and Google to find the solution

I also have to go to Google to see when 2.3.0-0.1.pre was released, so I know this is a recent change or not. I wish the guideline was "version - date" instead of version, so people can see and have time to react (e.g., oh, this was deprecated 10 months ago, I should hurry in replacing it! vs oh, this was deprecated last week, I can wait a bit more).
