### ISSUE TITLE
Update gradle versions in flutter/plugins to gradle-6.7

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#84873]
The current gradle versions in `wrapper/gradle-wrapper.properties` in flutter/plugins are mostly 3.x and 4.x, which are out-dated compares to the flutter's default template: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin/android.tmpl/gradle/wrapper/gradle-wrapper.properties

We should update all the plugins to use the same gradle version in flutter template.

**Comment by cyanglaz** [comment]
cc @blasten @bparrishMines

**Comment by hpoul** [comment]
Sorry if this is a stupid question - but why does the *plugin* `android` directory need a gradle wrapper configuration in the first place?
When I understand it correctly, it would only be needed if somebody wants to build the plugin on it's own. But I think it is common practice, or [at least documented this way to develop the native parts](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#:~:text=Select%20Open%20an%20existing%20Android%20Studio%20Project%20in%20the%20Welcome%20to%20Android%20Studio%20dialog%2C%20or%20select%20File%20%3E%20Open%20from%20the%20menu%2C%20and%20select%20the%20hello/example/android/build.gradle%20file.) by using `example/android` project.

For example `path_provider` plugin also [has no gradle wrapper configuration for the plugin itself](https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider/android), so it doesn't seem to be necessary? (but only for the `example/android`)

**Comment by stuartmorgan** [comment]
This issue covers the entire repository, including the example apps.

**Comment by TahaTesser** [comment]
Hi @cyanglaz 
Since AGP `7.0.0` & Gradle `7.0,2` is out, see https://github.com/flutter/flutter/issues/87649 
I have filed an issue to migrate all packages and examples to a newer major version and also filed a draft PR, When this issue was filed, Flutter used AGP 4.1 and Gradle 6.7 which is already outdated, my proposal is to migrate AGP 7.0.0 and Gradle 7.0.2.

So I am closing this for https://github.com/flutter/flutter/issues/88666,  If you disagree, please write in the comments and I will reopen it.
Thank you
