### ISSUE TITLE
All Linux flutter/plugins jobs waiting forever on Dockfile compilation

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#84990]
See https://cirrus-ci.com/build/5851594769039360 for an example.

There are two problems here:
1. We shouldn't be waiting forever for Dockerfile generation to run
2. That PR doesn't change the Dockerfile, and we *just* went through a bunch of problems due to expiration of the Dockerfile cache, meaning it was rebuilt last week and so there's no reason this PR should even be *doing* a Dockerfile compilation step.

**Comment by stuartmorgan** [comment]
I'm assuming this is https://github.com/flutter/flutter/issues/84667

Is there a better way to escalate failures that prevent all work in an entire repository? I thought a P0 infra bug was that process, but 7+-hour triage latency isn't really workable for an issue like that.

**Comment by stuartmorgan** [comment]
@godofredoc for the question above

**Comment by fkorotkov** [comment]
FYI you can use support+urgent@cirruslabs.org (I mentioned it to @kf6gpe a while back) for an urgent support with Cirrus issues.

In this particular case the issue was in the expired credentials. This caused Cirrus to unable to check of Docker image exists and it just went into retry loop. 

The long triaging time was due to two factors:

1. The error message was not particularly useful. Just that JWT signature is incorrect.

2. Tasks are running on your infrastructure and we had to ping pong with @godofredoc via emails to get to the bottom of the issues.



This was quite a weird edge case with the credentials so I doubt we'll get such surprise any times soon. Or at least we'll know right away that there is an expired credential.

**Comment by aDrIaNo34500** [comment]
FR

**Comment by godofredoc** [comment]
@stuartmorgan infra bugs that require gardener attention need to go to the [ticket queue project](https://github.com/flutter/flutter/projects/171). The process is described here:  https://github.com/flutter/flutter/wiki/Infra-Ticket-Queue. You can also use http://go/flutter-infra to find the current gardener and ping him directly.

**Comment by stuartmorgan** [comment]
Thanks, I'd somehow missed that page. I'll remember that for the future!

The issue is resolved by the recent PR, do this is indeed a duplicate.
