### ISSUE TITLE
ChromeOS version

### ISSUE THREAD

**Issue by Time-dragon** [flutter/flutter#84995]
Sorry for not using the template! I had to make this in a hurry to do some open-source software!

**Comment by asashour** [comment]
Open source doesn't mean sacrificing quality.

I personally don't understand what is needed, from reading the title.

**Comment by stuartmorgan** [comment]
Closing, as it is not at all clear what the intent here is. If you have a bug to report, please file an issue using a bug template. If you have a feature request, please file an issue using the feature request template. Either way, please follow the template.

The questions in the templates are there because we need that information in order to understand the issue.
