### ISSUE TITLE
flutter tool wants a JDK on MacOS

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#8508]
## Steps to Reproduce
1. Start with a brand-new install on macOS 10.12.3 (Sierra)
1. Run `flutter doctor` for the first time, no problem.
1. Run `flutter create gallery`, get prompt:
   "To use the "java" command-line tool you need to install a JDK"
    Looks like the Gallery was created. Can't tell if flutter run works because, Santa.

## Logs
Run your application with `flutter run` and attach all the log output.
Can't do this because, Santa.

Run `flutter analyze` and attach any output of that command also.
Analyzing lib/main.dart...
No analyzer warnings! (ran in 7.2s)

## Flutter Doctor

Paste the output of running `flutter doctor` here.
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/eastrue/flutter
    • Framework revision 6b97757b6d (5 days ago), 2017-02-24 17:47:29
    • Engine revision 335daf1930
    • Tools Dart version 1.23.0-dev.0.0

[-] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/eastrue/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    ✗ No Java Development Kit (JDK) found; you can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    ✗ ios-deploy not installed: 1.9.0 is required.
      Install via 'brew install ios-deploy'.

[✓] Android Studio (version 2.2)
    • Android Studio at /Users/eastrue/Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] Connected devices
    • iPhone SE • D6E31428-32E2-4AEF-8C87-7719F568D94A • ios • iOS 10.2 (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jakobr-google** [comment]
By "prompt" do you mean a dialog popped up with the message? Unfortunately, that's the standard behavior on macOS if you run 'java', and Java isn't installed. The dialog pops up because we try to detect if JDK is installed (by trying to run 'java'...) as part of the doctor checks before running your command.

Simply checking if the 'java' binary exist in $PATH doesn't work, since it does -- that's the one popping up the dialog -- so we'll have to get cleverer to detect this if we want to the dialog. Or, alternatively, stop requiring JDK to be installed. We only need it for Android development, and we might be able to get by using the JRE that comes with Android Studio (which we also require for Android development).

It's not really an error, though, just really annoying. The project got created, and I'm pretty sure `flutter run` (on an iOS device/Simulator) would work.

**Comment by LarkAscending** [comment]
If we could test w/o popping up the dialog, that would be awesome.

@jakobr-google Yes, it's a popup. Can't paste it in here, but I can share it if you need.

It's more than annoying because it diverts attention from flutter doctor output, where the real solution lies. And the link to get the JDK is not only the wrong link (to the Apple Safari home page!), it leads users to think that they need to do yet another standalone install. 

The correct path for them is to look at doctor output, and then just update their path to point to the JDK that is bundled w/Android Studio, and voila!

**Comment by jakobr-google** [comment]
Cool, just wanted to make sure I was able to repro the exact issue you reported.

Looks like we should use java_home on macOS to determine if/where Java is installed (and default to using Java from Android Studio if it isn't, #8515).

**Comment by eadafonso** [comment]
Good night guys I have flutter installed on my Mac but I can not run the application because I'm using Xcode 8.2, my mac does not support version 9 of xcode has how to run the application in version 8?

If so, help me.

**Comment by eseidelGoogle** [comment]
@eadafonso I would encourage you to file a new bug or reach out via stack overflow: flutter.io/support has links.
