### ISSUE TITLE
[web] Please add ability to add javascript libraries to flutter easily

### ISSUE THREAD

**Issue by ZdenekKrcal** [flutter/flutter#85154]
It would be nice to have ability to add all javascript libraries  into Flutter web app easily. For example web camera, echarts etc.

**Comment by darshankawar** [comment]
@ZdenekKrcal 
Did you get a chance to look at https://pub.dev/packages/js library which I think provides ability to use javascript libraries into web platform ? You may check the https://github.com/google/chartjs.dart/ example for reference.

**Comment by iapicca** [comment]
in my humble opinion it's totally fine to use js libraries in flutter web
for features that cannot be (for now) achieved otherwise (like multithreading, wasm etc)

but I don't see any reason why any effort should be spent into facilitate
the port of js libraries like chars or other ui elements
that can be 100% achived using dart

[gallery](https://google.github.io/charts/flutter/gallery.html) 
[repo](https://github.com/google/charts/tree/master/charts_flutter) 
[package](https://pub.dev/packages/charts_flutter)

**Comment by ZdenekKrcal** [comment]
Yes I know package js etc. But for example echarts needs div element with id, yea I can put it to the index.html, but how it is working when i build layout and other stuff with flutter? I just dont know how to figure it out.

**Comment by darshankawar** [comment]
> but how it is working when i build layout and other stuff with flutter? I just dont know how to figure it out.

@ZdenekKrcal 
It may be a good question to ask on support channels like StackOverflow or https://www.reddit.com/r/flutterhelp/ if you need help in figuring that out.
