### ISSUE TITLE
How to get positioned lines in flutter while dragging?

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#85199]
Please see this question https://stackoverflow.com/questions/68112202/how-can-we-achieve-the-positioned-lines-while-dragging-widget-in-flutter

**Comment by darshankawar** [comment]
@jazzbpn 
I see that you've already asked this question on StackOverflow, but since this is more of a `how to` question rather than a bug or feature request for which this repo is for, I'd suggest you to keep following on other support channels as well to get help.  Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
