### ISSUE TITLE
Back Button of browser does not work in Flutter web

### ISSUE THREAD

**Issue by liqiang1995** [flutter/flutter#85236]
How are you?
I built a website with Flutter 2.
https://yklmauctions.com
But sometimes when I press the back button of the browser, I can not see the previous page.
I got this error on the console.
![image](https://user-images.githubusercontent.com/54995513/123303837-d2764b80-d550-11eb-9a7f-ac2d11dfd51a.png)
Please let me know how to solve this problem.
Thank you.

**Comment by darshankawar** [comment]
@liqiang1995 
In order to properly address this issue, we would need your `flutter doctor -v` alongwith a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugin code, using which the issue you mentioned would be replicable.

Is it replicable in debug or in release mode locally ?  If so, please provide a code sample as mentioned above.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
