### ISSUE TITLE
[web]: <Unsupported operation: Platform._version>

### ISSUE THREAD

**Issue by rahulrkhot** [flutter/flutter#85310]
when i run app as web then occurred this issue "Unsupported operation: Platform._version" and  Error: Unsupported operation: Platform._operatingSystem

**Comment by darshankawar** [comment]
@rahulrkhot 

It seems you are using a plugin that is not supported on web. Check all the plugins and the platforms they support and remove the ones which doesn't support web and try again to see if you still get the same error or not.

Also, this issue is better suited for support channels like StackOverflow. Please ask it there if above solution doesn't work for you.
