### ISSUE TITLE
Regressions in hotReloadInitialDevFSSyncAfterRelaunchMilliseconds & hotReloadInitialDevFSSyncMilliseconds

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#85352]
See https://flutter-flutter-perf.skia.org/e/?begin=1624464663&end=1624659663&keys=Xe5c1c3aad8a00555085f8ba3ac86482e&requestType=0&xbaroffset=24726.

Looks like it's around https://github.com/flutter/flutter/commit/102acbe39d67a5830be358fffcdf9e9e64e8c1cf (https://github.com/flutter/flutter/pull/85267), which doesn't surprise me given the nature of the change. If this is it, we should consider a rollback; it's caused a 2x regression.

**Comment by zanderso** [comment]
Will this regress only when there are assets being reloaded, or does the above change increase the latency for all cases?

**Comment by jonahwilliams** [comment]
This is first run but seems pretty bad. Since the edge its fixing is very edgy ... lets revert and then explore some of the alternative solutions @chingjun ?

Perhaps we could modify the Vm Service devfs code to do the right thing

**Comment by chingjun** [comment]
I'm surprised that syncing an additional empty file took that long. I wonder if it is because of the overhead of HTTP transfer, or is it because of the device is slow in creating directories. If the latter, even if we do the "right thing" that we discussed yesterday, we will still see a similar performance hit.

But ya, for now let's revert and explore the alternative solutions.

**Comment by jonahwilliams** [comment]
Performance returned to previous levels, closing
