### ISSUE TITLE
integration_test: Can't run XCode "Product" --> "Test"

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#85444]
## Description
I tried to set up XCTest with the `integration_test` package. What I did is:

1. Create a new fresh flutter project with `flutter create`
2. Add integration test (I copied the widget test as integration test)
3. Run integration test with `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d 63B1E047-86E5-462C-9B49-16E6FD9F131D` --> everything worked ✅
4. Now I followed the steps to set tup the XCTests: https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing
5. For this I created a new target, which I called `RunnerTests`
6. Added this to my `Podfile`:
```ruby
target 'RunnerTests' do
    inherit! :search_paths
  end
```
7. Replaced `RunnerTests.m` with:
```swift
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```
8. And finally I tried to run the test via XCode: "Product" --> "Test" (or the shortcut: Command + U)

## Problem

XCode started building, but I got this expection:
```
can't link with a main executable file '/Users/nils/Library/Developer/Xcode/DerivedData/Runner-agxmbwcpuxvqzdbzeonhnekntuhm/Build/Products/Debug-iphonesimulator/Runner.app/Runner' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

![image](https://user-images.githubusercontent.com/24459435/123606397-27d68500-d7fd-11eb-8cc7-77d86bd27825.png)

## Tested device
Running build from MacBook Pro M1, macOS 11.3. Tried to build for iOS Simulator.

## Code to reproduce
I published all my Code in this Repo: https://github.com/nilsreichardt/integration_test_problem

<details>
  <summary>Flutter Doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2-0.0.pre.1, on macOS 11.3 20E232 darwin-arm, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.58.0-insider)
[✓] Connected device (4 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone von Roland is connected. (code -13)

! Doctor found issues in 1 category.
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@nilsreichardt 
Thanks for the detailed report.
Does it build for you from command line if you try: `flutter build ios --config-only integration_test/foo_test.dart`

And can you also please provide the entire exception log here ?

**Comment by nilsreichardt** [comment]
Hi @darshankawar, thanks for the quick response!

`flutter build ios --config-only integration_test/app_test.dart` seems to work for me.

```
flutter build ios --config-only integration_test/app_test.dart
Running "flutter pub get" in integration_test_problem...         1,549ms
Building com.example.integrationTestProblem for device (ios-release)...
Signing iOS app for device deployment using developer identity: "3rd Party Mac Developer Application: Nils
Reichardt (AJ3PMPVZ7H)"
Running pod install...                                             969ms
```

I tried also to do this:
1. Run `flutter build ios --config-only integration_test/app_test.dart`
2. Run in XCode "Product" -> "Test"

This does also **not** work for me.

**Comment by jmagman** [comment]
Ah, we haven't updated the `integration_test` docs for M1.  Flutter apps don't set support the arm64 iOS simulator (soon to be fixed with https://github.com/flutter/flutter/pull/85059).
There are a few ways around this.
### Option A
In your RunnerTests target, find the Excluded Architectures (`EXCLUDED_ARCHS`) build setting. Click the right arrow disclosure indicator icon to expand the available build configurations. Hover over Debug and click the plus icon. Change **Any SDK** to **Any iOS Simulator SDK**. Add arm64 and i386 to the build settings value. (note this screenshot shows Runner but do it for your RunnerTests test target).
<img width="1142" alt="Screen Shot 2021-01-12 at 6 37 29 PM" src="https://user-images.githubusercontent.com/682784/104399359-58538c80-5505-11eb-9e91-23c6cde7f416.png">


### Option B
Inherit the Flutter base xcconfig in the RunnerTests target.  In Runner (PROJECT, not TARGET) > Info expand Configurations.  Make the RunnerTests target inherit from Debug, Release, and Release.
<img width="773" alt="Screen Shot 2021-06-28 at 6 14 25 PM" src="https://user-images.githubusercontent.com/682784/123722184-ad2d5a00-d83c-11eb-9c0e-6e9cc3a49e90.png">

I recommend trying Option A.

**Comment by jmagman** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/87244.
