### ISSUE TITLE
All links on website have the little "goes to outside" arrow

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8545]
Just noticed that all internal and external links now have the little arrow:

![screenshot_20170302-150034](https://cloud.githubusercontent.com/assets/5479/23533192/fb84c00e-ff64-11e6-900b-37adf18dcf9a.png)

![screen shot 2017-03-02 at 4 25 56 pm](https://cloud.githubusercontent.com/assets/5479/23533196/ff1d19aa-ff64-11e6-8b73-27ee85b54566.png)

**Comment by sethladd** [comment]
@LarkAscending @Sfshaza does this look familiar? Thanks for taking a look!

**Comment by LarkAscending** [comment]
When abarth and I reworked https://github.com/flutter/website/pull/407 and turned it into https://github.com/flutter/website/pull/412, we left out a very small CSS change to _sass/_customstyles.scss

This affects the class that hides that FontAwesome icon. It's possible that a new PR w/that small change could fix this. No way to test locally that I know of.

What's wrong with this theory is, that tiny change was never merged and never found its way to flutter.io. So it can't be responsible for the prior appearance of internal links. Anyway, I'll create a new PR w/that change because it's needed anyway. And we'll see how that affects this issue, or not.

**Comment by Hixie** [comment]
I would be totally fine with ditching the icon entirely, FWIW.

**Comment by sethladd** [comment]
Me too, fwiw.

**Comment by LarkAscending** [comment]
Fixed by https://github.com/flutter/flutter/issues/432
