### ISSUE TITLE
Container takes up maximum width inside ListView even giving it width

### ISSUE THREAD

**Issue by ibrahimxcool** [flutter/flutter#85490]
In `Column` and `SingleChildScrollView` the `Container` widget doesn't expand to max width.. But its not the same with `ListView`

```
ListView(
        children: [
          Container(
            constraints: BoxConstraints(maxWidth: 20),
            height: 10,
            width: 10,
            color: Colors.grey[900],
          )
        ],
      )
```

![Screenshot_1624923156](https://user-images.githubusercontent.com/69388870/123716037-0de78180-d893-11eb-8baa-3757b3e68120.png)

**Comment by darshankawar** [comment]
@ibrahimxcool 
You can make use of `margin` inside `Container` while providing custom height and width to the Container, so that it doesn't take up entire space, as below:

```
ListView(
          children: [
            Container(
              margin: EdgeInsets.all(50),
              height: 10,
              width: 10,
              color: Colors.red[900],
            )
          ],
        )
```

<img width="342" alt="Screenshot 2021-06-29 at 6 04 58 PM" src="https://user-images.githubusercontent.com/67046386/123798150-89cde200-d904-11eb-8526-0efc8c602978.png">

You can adjust the margin as you want.

Closing this as non-issue. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by ibrahimxcool** [comment]
This is going to be a problem where if I have lets say a chat app. And `Container `to take width of `Text`

```
ListView(
        children: [
          Container(
              padding: EdgeInsets.all(16),
              margin: EdgeInsets.all(10),
              color: Colors.black,
              child: Text('Hello', style: TextStyle(color: Colors.white))),
          Container(
              padding: EdgeInsets.all(16),
              margin: EdgeInsets.all(10),
              color: Colors.green[900],
              child: Text('Hi',
                  style: TextStyle(color: Colors.white),
                  textAlign: TextAlign.end))
        ],
      ),
```

![Capture](https://user-images.githubusercontent.com/69388870/123802804-20020800-d905-11eb-88b7-b7f8c03b7f6b.JPG)

**Comment by ibrahimxcool** [comment]
A workaround is to wrap the `Container` in a `Row` widget. But I don't think this is the way to do it. Or is it?
