### ISSUE TITLE
App does not run on phone emulator

### ISSUE THREAD

**Issue by Bicentricnote33** [flutter/flutter#85506]
I just downloaded flutter on android studio, and there's a demo app. However, I cant run the demo app.
I downloaded the Pixel 3 XL api 28
after opening the phone, when i press the green run button, i get this error:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x7a7153) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x7a7153

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

im not sure what this means, please help!

**Comment by darshankawar** [comment]
The error is:

`java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x7a7153) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x7a7153`

It seems the gradle version you are using isn't yet compatible and hence throwing the error. Try downgrading the gradle version which hopefully should resolve your issue.
See these similar issues: https://github.com/gradle/gradle/issues/15538,https://github.com/gradle/gradle/issues/16641. https://github.com/gradle/gradle/issues/16641#issuecomment-839542816

Also, this doesn't seem to be framework issue, but maybe coming from gradle, so if you still face any issue, please file it here: https://github.com/gradle/gradle/issues or ask support questions on StackOverflow.

Closing from here.
