### ISSUE TITLE
ProgressIndicatorTheme

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#85510]
## Steps to Reproduce

I want to use `ProgressIndicatorTheme` to globally change color on progress indicators, in previous version of flutter the color was accent by default and currently it's primarySwatch, after upgrading flutter all colors of progress indicator changed and I want to set all accent again

But there is no way to use `ProgressIndicatorTheme`, I cannot import it, Where is it?
See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/progress_indicator.dart#L110-L116

**Comment by sm2017** [comment]
Also there is no way to change the color on progress indicator from `ThemeData`

**Comment by TahaTesser** [comment]
Hi @sm2017 
`progressIndicatorTheme` current exist on all channels except stable


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData(
        progressIndicatorTheme: ProgressIndicatorThemeData(
          circularTrackColor: Colors.yellow,
          linearTrackColor: Colors.pink,
        ),
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: Column(
        children: [
          CircularProgressIndicator(),
          LinearProgressIndicator(
            value: 0.5,
          ),
        ],
      )),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
```

</details>

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`



> and I want to set all accent again

I am not sure this is possibles since changes are already made in Flutter

**Comment by sm2017** [comment]
@TahaTesser Thanks a lot
