### ISSUE TITLE
Convert flutter/packages local_test to a plugin tools command

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85543]
flutter/packages has a shell script that runs a custom script command for every package that has it. It's still using the old bash copy of the change-detection logic, which a) we don't want to maintain, and b) is already strictly worse than the new Dart version.

We should convert it over to a new command in the tools package so that we have less code to maintain, the behavior is consistent (we can use all the same flags to control what it runs on, we get the same output format, tool changes re-run for all packages, etc.).

This would also be a good opportunity to rename it to something clearer, since I'm not sure what "local" means in this context, and ideally to clarify what it should (and shouldn't) be used for—we don't want to get into a situation where each package has its own complex, bespoke test control script rather than using specific commands from the tools package. (For instance: we have specific commands that know how to run iOS and Android unit tests; I'd like to understand whether Pigeon's test system really needs its own versions.)

/cc @gaaclarke

**Comment by gaaclarke** [comment]
I just wrote this in a PR, it's apropos to this issue:

> The idea for local_tests is that certain packages have more complex test harnesses, there isn't a generic wrapper for the whole repo that can run tests that have to do codegen and linting in different languages for example. Plus we have the problem that we don't want CI running tests in a different way as people are developing locally. We have to try to keep them as similar as possible.

**Comment by stuartmorgan** [comment]
> The idea for local_tests is that certain packages have more complex test harnesses

It doesn't follow that if a package needs more complexity than other packages the only option is to write the entire test harness from scratch though. For instance:

> there isn't a generic wrapper for the whole repo that can run tests that have to do codegen

Is needing to do codegen the only thing preventing you from using the existing commands for running iOS and Android unit tests? Because if so, it seems to me that adding a pre-test script hook to the existing commands (which other packages could use for other things, like, say, starting a local server) would be far better than having a second copy of all the logic for running native unit tests but with an extra step before. It's easier to maintain, it's more consistent across packages, it's more re-usable, etc.

> Plus we have the problem that we don't want CI running tests in a different way as people are developing locally.

How do we have that problem? `flutter_plugin_tools` is intended for both CI and local development.

**Comment by soulhope** [comment]
Crypto Solution has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [flutter/flutter] Convert flutter/packages local_test to a plugin tools command (#85543) <https://confidential-mail.google.com/msg/AG7J_YSQriZpNKAwuBoFrbZGtJK-UMCeuF9jj58-MkluKemE0CAjsbl5D_56odeHz3DIzz75aOU0xbDh9ry97SmjB99jFAXZ9d0ft3BHIZE9h486CL3jyQrxT9qogHZJG5YWNtjID40h88u4GcS78BwEcoE3fTsTlbSIhc7k0W3c5hwEAXZXxepBvyM-8u_3-87d0gaFHOao2dflYccU>

This message was sent on Jun 29, 2021 at 11:09:47 AM PDT
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AG7J_YSQriZpNKAwuBoFrbZGtJK-UMCeuF9jj58-MkluKemE0CAjsbl5D_56odeHz3DIzz75aOU0xbDh9ry97SmjB99jFAXZ9d0ft3BHIZE9h486CL3jyQrxT9qogHZJG5YWNtjID40h88u4GcS78BwEcoE3fTsTlbSIhc7k0W3c5hwEAXZXxepBvyM-8u_3-87d0gaFHOao2dflYccU>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Comment by gaaclarke** [comment]
Nope, not just running codegen.  Outside of running dart unit tests the local_tests are also downloading and executing custom linters (like checkstyle) and executing platform specific test harnesses (like xcode unit tests).

**Comment by stuartmorgan** [comment]
> are also downloading and executing custom linters (like checkstyle)

I understand that there are *some* parts of the current test that are going to be highly specific to Pigeon. But the options are not "don't have any custom test script" and "write absolutely everything from scratch without using any of the existing tools". Again, as a specific example:

> and executing platform specific test harnesses (like xcode unit tests).

As I said in both of my comments above, we have commands that do exactly that in the tool package:

> we have specific commands that know how to run iOS and Android unit tests
> [...]
> Is needing to do codegen the only thing preventing you from using the existing commands for running iOS and Android unit tests?

**Comment by stuartmorgan** [comment]
Another reason we need to do something about this: the bash logic for figuring out what packages to run is much cruder than the Dart logic in the tool, and it doesn't understand the concept of re-running all tests for repo-affecting changes. Notably, the new flutter->packages autoroller won't fail if it breaks `local_test`, because `local_test.sh` will determine that no packages need to have tests run.

**Comment by stuartmorgan** [comment]
The current set of tests:
- flutter_image: runs a test server before running the test
- flutter_lints: asserts that there is no Dart code outside of example/
- pigeon: runs code generation, then does a bunch of tests (most or all of which are tests the tooling already knows how to run, except in subdirectories of the main package which is a complication)
- rfw: makes coverage assertions

I think given the diversity here, we should just add a command for this to the tooling now, and then revisit eliminating the need for as many as possible (via additional tool functionality, such as pre/post run hooks for various types of tests) later.
