### ISSUE TITLE
Where's my green circle?

### ISSUE THREAD

**Issue by treeplate** [flutter/flutter#85540]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Change main.dart to: 
```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  ByteData file = await rootBundle.load("first.wvg");
  ui.window.onDrawFrame = () {
    ui.PictureRecorder recorder = ui.PictureRecorder();
    ui.Canvas canvas = ui.Canvas(recorder);
    canvas.drawCircle(Offset.zero, 1, Paint()..color = Colors.green);
    ui.window.render((ui.SceneBuilder()
          ..addPicture(const Offset(0, 0), recorder.endRecording()))
        .build());
  };
}
```
3. flutter run

**Expected results:** a green circle, or more accurately, a quarter of a green circle.

**Actual results:** White screen

**Comment by Hixie** [comment]
The 1 means the radius of the circle is 1 pixel, so the green circle should be a single pixel at the top left. Does it work if you make the 1 into something like 500.0?

**Comment by treeplate** [comment]
no

**Comment by shirne** [comment]
Maybe you should call runApp at end of main
```dart
void main() async {
  
/// your code

  runApp(Container());
}
```

**Comment by Hixie** [comment]
Chatted with @treeplate offline, and the problem here is that `WidgetsFlutterBinding.ensureInitialized` is taking over the `ui.window.onDrawFrame`, handles the first frame (rendering nothing), then after the `await` returns on the `load`, this code sets `ui.window.onDrawFrame` again but doesn't schedule a frame, so nothing happens. If you resize the window, it appears, as expected.
