### ISSUE TITLE
[Codelabs][Building beautiful UIs with Flutter] Code error?

### ISSUE THREAD

**Issue by kosei-s** [flutter/flutter#85619]
https://codelabs.developers.google.com/codelabs/flutter#6
Isn't "required" in the following code on the above page "\@required"?
`ChatMessage({required this.text}); // NEW`

**Comment by domesticmouse** [comment]
Prior to null safety, Flutter had an annotation for required parameters, sourced from the [`meta`](https://pub.dev/packages/meta) package. With Null Safety there was now a requirement for being able to mark parameters as required due to the new type system, so the old `@required` annotation was upgraded to part of Dart the language. See Bob's [Understanding null safety](https://dart.dev/null-safety/understanding-null-safety), specifically the [Required named parameters](https://dart.dev/null-safety/understanding-null-safety#required-named-parameters) section, for more detail.
