### ISSUE TITLE
[image_picker] Add support for picking by custom format 

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#85623]
Hi, it would be great to have ability to specify what image types are allowed to pick

**Comment by TahaTesser** [comment]
If I understand correctly you mean picking images and videos based on file extensions
So if you specify ".jog" type, it would only show the ".jpg" type 


Do you have any example where Android or IOS support this type of picker with a file type?

**Comment by vytautas-pranskunas-** [comment]
I have just found this: https://pub.dev/packages/file_picker it supports files filtering by extension

**Comment by stuartmorgan** [comment]
The iOS API at least does not allow this level of filtering, so this would never work on at least one major platform. Given that, I'm skeptical of the utility of supporting it even if it works on Android.

**Comment by vytautas-pranskunas-** [comment]
What about file_picker (https://pub.dev/packages/file_picker) this library is capable to do filtering.

**Comment by stuartmorgan** [comment]
That's not accessing the image gallery, it's accessing files. They are completely different APIs. `image_picker` is specifically for the former, per its name.

If you want generic file access in a 1P plugin that would be an iOS implementation of file_chooser.

**Comment by vytautas-pranskunas-** [comment]
If it is not possible to add filtering on library scale it can be added on code level meaning that after selection not allowed files can be stripped.

**Comment by stuartmorgan** [comment]
You could certainly choose to have your code discard some of the files selected by the user, yes. That wouldn't require any changes to the plugin though.

**Comment by vytautas-pranskunas-** [comment]
For sure i can, and I did but this is improvement task right? :)

**Comment by vytautas-pranskunas-** [comment]
Also under the hood you can start using file picker rather than image picker and add filterng. This might also help to bypass iOS 14 limitation (that current multi image picker has) wich strips huge amount of devices

**Comment by stuartmorgan** [comment]
> For sure i can, and I did but this is improvement task right? :)

Allowing the user to select something and then discarding their selection is not something we would build into the plugin.

> Also under the hood you can start using file picker rather than image picker and add filterng.

Or people who want the file selector UI rather than the photo gallery UI could use the `file_selector` plugin, rather than us building and maintaining two different plugins that do the same thing. I don't see any advantage in eliminating options.

**Comment by vytautas-pranskunas-** [comment]
:) You have been deffensive :) I do not need file selector. I need ability to filter out such filef as ```webp```. But i see this disucssion is going nowhere :(

**Comment by stuartmorgan** [comment]
> You have been deffensive

I have explained the OS API limitations that we are constrained by. That's not defensiveness, just technical reality.

> I do not need file selector.

I was responding to your suggestion that we use the OS file selector API to implement the functionality you want. I'm simply pointing out that if that implementation works for your use case, the plugin that will already be using the OS file selector API already has the API you seem to want (selecting files with a file type filter), and thus using it would be a better solution than us removing access to the APIs that `image_picker` wraps to give a slightly different Dart API to the same OS functionality.

> But i see this disucssion is going nowhere

I am not aware of a better solution for the functionality you are requesting than to use `file_selector` (once implemented), due to OS limitations. If you or anyone else has other suggestions, we can certainly consider them.

**Comment by stuartmorgan** [comment]
The system-provided image picker controls that `image_picker` provides access to do not provide APIs to control details of camera behavior. As discussed above, applications that require specific file type filtering can use `file_selector` (which now has mobile implementations).
