### ISSUE TITLE
API to allow drawing directly on ui.image

### ISSUE THREAD

**Issue by jdevp** [flutter/flutter#85712]
I'm not sure if it is possible in Flutter to allow drawing directly onto  an ui.Image.  I'm trying to create a drawing tool similar to 'smudge' tool.  It does require to blend the underline pixels with the drawing color as a finger being dragged cross the screen. So far, I haven't found a way to implement this in Flutter since Flutter doesn't allow you to draw directly on an image.

**Comment by dnfield** [comment]
I'm not entirely sure I understand what this bug is requesting, but you should be able to use `Canvas.drawImage` or alternatively get the pixels of the image and apply transformations to individual pixels today.

I don't think there are realistically any plans to support image manipulation at this level in the Flutter SDK directly though - if you find there's a specific filter you're missing it should be possible to add that, but it should be possible to blur specific parts of an image without changes today.
