### ISSUE TITLE
Best practice for intended single platform targeted plugins

### ISSUE THREAD

**Issue by EP-u-NW** [flutter/flutter#85762]
I'm currently developing a plugin for Android only. Since the plugin is about Android foreground services it is only usefull on Android and no other platform. In my `pubspec.yaml` I only use the
```yaml
flutter:
  plugin:
    platforms:
      android:
```
keys to specify that it is intended that my plugin only runs on Android.
On the other hand [pub.dev](pub.dev) and `pana` give me score penalties for not supporting multiple platforms.

So this penalty leads me to the following question:
What is the best practice for such a plugin concerning other platforms?

My implementation is guaranteed to work on any other flutter platform by providing no-op implementations of the methods (even web with conditional imports/exports). This behaviour is very clearly documented. I could add the remaining flutter platforms to my `plugin` key. This on the other hand would add the badges of these platforms in the top left corner of the plugins pub page. But I'm not sure if I like this behaviour, since again, my plugin explicitly targets Android and makes no sense on any other platform.

What shall I do?
* Take the penalties and remove the no-ops for other platforms so that it is really just Android and a developer must do the platform check
*  Take the penalties but keep the no-ops so that a developer doesn't have to worry about platform checks
* Claim to support the other platforms and provide no-op implementations so a developer finding my package on `pub.dev` is not worried about using it on other platforms since he can see the platforms bages

**Comment by stuartmorgan** [comment]
> On the other hand [pub.dev](pub.dev) and `pana` give me score penalties for not supporting multiple platforms.

@csells @mit-mit @jonasfj I think we should revisit whether this makes sense. Since we can't distinguish between plugins that could support other platforms that don't, vs plugins that are only meaningful for specific platforms (of which there are a variety: one-platform, mobile-only, desktop-only, etc.), using it for scoring is somewhat problematic. Especial since it's actually incentivizing a bad outcome here (see below).

We have 1P plugins in exactly the same situation even.

> * Take the penalties and remove the no-ops for other platforms so that it is really just Android and a developer must do the platform check
> * Take the penalties but keep the no-ops so that a developer doesn't have to worry about platform checks

This is highly subjective, and may also depend on the specific use case. E.g., if it's an API where the likely construction is to call it on Android but do something else on other platforms instead, internal no-op is less likely to make sense.

> * Claim to support the other platforms and provide no-op implementations

Doing no-ops in native code (which this requires, at least on mobile) is strictly worse than doing it in Dart (which would be the second option above). It:
- adds time and complexity to the build
- adds binary size to apps on every other platform
- is less efficient at runtime.
Each of these effects of small, but there's literally no upside to it.

Also, this undermines pub.dev features, like being able to filter searches by platform.

> so a developer finding my package on `pub.dev` is not worried about using it on other platforms since he can see the platforms bages

A plugin not having an implementation for a platform should never cause problems when building for that platform, so people shouldn't worry about that.

**Comment by stuartmorgan** [comment]
Closing; there's nothing to do at the Flutter level here since declaring just the supported platforms is the correct behavior. That just leaves the question of whether pub.dev should penalize for that, which should be raised in https://github.com/dart-lang/pub-dev/issues.
