### ISSUE TITLE
Codelab `photos-sharing` uses deprecated `accentColor`

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#85824]
Update the `photos-sharing` codelab to remove the deprecated `accentColor` usage.

```console
== TESTING photos-sharing/initial
+ flutter analyze
Running "flutter pub get" in initial...                            13.8s
Analyzing initial...                                            

   info • 'accentColor' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/main.dart:57:5 • deprecated_member_use

1 issue found. (ran in 8.3s)
```

**Comment by SinaElahimanesh** [comment]
The ThemeData accentColor, accentColorBrightness, accentIconTheme and accentTextTheme properties have been deprecated because the Material library no longer uses them.

The Material Design spec no longer specifies or uses an “accent” color for the Material components. The default values for component colors are derived from the overall theme’s color scheme. The ColorScheme’s secondary color is now typically used instead of accentColor and the onSecondary color is used when a contrasting color is needed.

To configure the appearance of the material components in about the same way as before, specify the color scheme’s secondary color instead of accentColor.

Code before migration:
```
MaterialApp(
  theme: ThemeData(accentColor: myColor),
  // ...
);
```

Code after migration:
```
final ThemeData theme = ThemeData();
MaterialApp(
  theme: theme.copyWith(
    colorScheme: theme.colorScheme.copyWith(secondary: myColor),
  ),
  //...
)
```

I hope this guide can solve your problem.
So you can use these solutions instead of `accentColo`r

**Comment by domesticmouse** [comment]
Thanks @SinaElahimanesh!

@RedBrogdon can we use this as the basis for some documentation on flutter.dev? 
FYI @sfshaza2

**Comment by SinaElahimanesh** [comment]
You are welcome! @domesticmouse 
I hope these comments would be useful for you.
