### ISSUE TITLE
Add UWP support to plugin template

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85836]
The plugin template for `create` needs to be updated to support UWP: code, build file, and pubspec. Currently it's Win32-only

As mentioned [here](https://github.com/flutter/flutter/issues/14967#issuecomment-813082220) we could do this after we have at least one 1P plugin supporting UWP so that we know we have everything in place that is needed.

**Comment by ManasMalla** [comment]
Yah!

**Comment by stuartmorgan** [comment]
> after we have at least one 1P plugin supporting UWP

Current WIP for this is https://github.com/flutter/plugins/pull/3828

Its status is:
- Includes the (not yet documented) [pubspec entry declaring UWP support](https://github.com/flutter/plugins/pull/3828/files#diff-6c293f6f8d30d4b678493a2b61e2416390e5df4656eeed6db8a321d2cfa7074eR17-R19) which is necessary to cause plugins to be built as part of UWP builds.
- [Demonstrates the relevant #ifdef](https://github.com/flutter/plugins/pull/3828/files#diff-d15a91a9088ebcd85f78d9ab4ae179049f37938adefacef11d5cde16eaacb0eaR11)

However, the build is currently hanging. It's not clear yet if that's related to the plugin build, or the Flutter UWP build in general.

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
