### ISSUE TITLE
I have a problem with ongeneraterouting and dialogs

### ISSUE THREAD

**Issue by ahmeddigi** [flutter/flutter#85872]
hi i am using repository bloc architecture for my app but I have a problem my app has a lot of dialogs in it and I have some problems with passing bloc/cubits instances.
i have tried ongeneraterouting but the problem is that I can not push a new dialog (black background)  and  the method show dialog is not a type of "Route"

**Comment by darshankawar** [comment]
@ahmeddigi 
Since you are using bloc arch, it is a 3rd party plugin, so you can ask this question in dedicated repo. You can also ask this on support channels like StackOverflow, so please ask this question there to get help.
Closing from here. If you disagree, or think there's a bug in routing, write in comments and I'll reopen it.
Thanks.
