### ISSUE TITLE
Edge-To-Edge by default on android

### ISSUE THREAD

**Issue by LasseRosenow** [flutter/flutter#86248]
## Use case

Recently flutter got official android edge-to-edge support for android (flutter/flutter#81303). But its not enabled by default even though edge-to-edge is considered to be the new default way of developing modern android applications.
Changing edge-to-edge to be the default behaviour would make all flutter applications look much more modern without the need of specifically opting in, which is something many people would forget to do, or don't even know about.

## Proposal

Make this the new default:
```dart 
SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
```

**Comment by LasseRosenow** [comment]
@Piinks I guess you would be the correct person to ping regarding this demand :)

**Comment by Piinks** [comment]
Thanks for reporting! I did not know edge to edge was the default. We'll just need to see if making that change is breaking first. :)

**Comment by hectorAguero** [comment]
@Piinks I have two problems with the implementation of Edge to Edge support.

1. In addition to set `SystemUiMode.edgeToEdge` I need to set `systemNavigationBarColor: Colors.transparent`, because without that EdgetoEdge don't work, I said in #69999 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        systemNavigationBarColor: Colors.transparent);
    return MaterialApp(
        title: 'Material App',
        home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body: ListView.builder(
              itemCount: 50,
              itemBuilder: (context, index) => Container(
                  height: 100,
                  color: index % 2 == 0 ? Colors.white : Colors.grey.shade900)),
        ));
  }
}
```

2. EdgeToEdge broke in some way Android Native Splash Screen in xml, I create a new project and set flutter logo in the center, when I enable edgeToEdge the logo go down.

https://user-images.githubusercontent.com/31939754/125499214-89a125d6-d3cd-4c5e-98f0-56148138b68a.mp4

**Comment by NaikSoftware** [comment]
Also viewInsets.bottom animated with lags when keyboard start showing and this cause lags on all screens with text fields in bottom of the screen (chat, etc)

**Comment by TheJulianJES** [comment]
Did anyone try ``SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);`` on Android SDK 16 - 19?
For me, a BottomNavigationBar completely merges underneath the Android navigation bar.
I'd assume that (like in SDK 21+) the navigation bar renders on top but the "SafeArea" padding at the bottom is increased to accommodate the Android navigation bar.

**Comment by paolovalerdi** [comment]
@TheJulianJES The WindowInsets API was added on Android SDK 20 thus enabling this mode on any prior version will result in the bottom inset being 0. 
See https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat#getSystemWindowInsetBottom()

**Comment by Piinks** [comment]
I heard a similar query from someone else today. We set up edge to edge at the earliest API that it could be available (16) but that may not be the best choice, you cannot change the navigation bar color until 26, and the contrast scrim to ensure visibility isn't available until 29. I have opened https://github.com/flutter/flutter/issues/89774 to discuss, we might update this to support edge to edge starting at 29.

**Comment by LasseRosenow** [comment]
Will this be part of #91605?

**Comment by camsim99** [comment]
cc @mariamhas for context on how Flutter currently uses edge-to-edge mode (not by default).

**Comment by camsim99** [comment]
@mariamhas The issue for the Android 15 edge-to-edge support is https://github.com/flutter/flutter/issues/146657 unless you think we should consider this proposal with that work.

I believe the main difficult here is described by [this comment](https://github.com/flutter/flutter/issues/86248#issuecomment-916348604) and how to handle the other platforms if this change were made.

**Comment by mariamhas** [comment]
Thanks camsim, I thought this was the main issue for tracking. will update this issue accordingly.

**Comment by camsim99** [comment]
Bumping this in priority as this will round out the work to support [changes coming to edge-to-edge in Android 15](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge).

**Comment by camsim99** [comment]
FYI to the iOS team because edge-to-edge mode is used by default on iOS and completing this to better align with iOS and Android moving forward will make this consistent across the two platforms.

**Comment by camsim99** [comment]
Some updates here...

### What has been done
Android is enforcing edge-to-edge mode by default for Android apps that target Android 15+. Flutter updated the default target SDK version to 35 in https://github.com/flutter/flutter/pull/153795, effectively opting in apps running on Android 15+ devices into edge-to-edge by default. In this way, **we have aligned Flutter Android apps on devices running Android 15+ with Flutter iOS apps by making edge-to-edge the default mode**, effectively addressing this issue.

### What we also considered
We considered enforcing edge-to-edge modes on devices it is available on (API 29+), but this would make it hard for developers to also design for API < 29 devices where it is not available.

We also considered enforcing edge-to-edge mode for devices running some API >= 29, but having edge-to-edge be the default and still allowing for opt outs (see [migration guide](https://docs.flutter.dev/release/breaking-changes/default-systemuimode-edge-to-edge)) keeps us aligned with Android's timeline for edge-to-edge, which [notably](https://developer.android.com/reference/android/R.attr#windowOptOutEdgeToEdgeEnforcement) is allowing opt outs to give developers time to migrate.

### What's left to do
- [ ] https://github.com/flutter/flutter/issues/150367: We plan to update the `SystemUiMode` documentation to state edge-to-edge as the default on Android 15+.
- [ ] https://github.com/flutter/website/issues/10755: We plan to add a migration guide to help folks migrate their apps to edge-to-edge mode, since this is the default mode moving forward (Android 15+).


cc @reidbaker if you have any further thoughts from our offline discussion

**Comment by camsim99** [comment]
> ### What's left to do
> - [ ] https://github.com/flutter/website/issues/10755: We plan to add a migration guide to help folks migrate their apps to edge-to-edge mode, since this is the default mode moving forward (Android 15+).

After talking with the team, we've decided that the priority for this task was publishing a migration guide for folks wishing to use a non edge-to-edge mode (done, see https://docs.flutter.dev/release/breaking-changes/default-systemuimode-edge-to-edge). Documentation on how to migrate design-wise is a nice to have and this issue shouldn't depend on it, so I'm going to close this issue as complete!
