### ISSUE TITLE
Java for Linux Flutter applications

### ISSUE THREAD

**Issue by Iftach-Nevo** [flutter/flutter#86279]
I am looking to build an application that will run both on Android and Linux devices. The application is implemented mainly using Java.
Today I can only add C files to a Linux Flutter application and calling Java from C is quite complex.

I request to add the option of adding Java files directly to a Linux Flutter application (like I can do with an android app) as today I can only add C files.

**Comment by stuartmorgan** [comment]
You can add Java files to an Android Flutter application because Android applications are Java based. A Linux Flutter application has no Java VM.

If you want to bundle a Java runtime with your application (making it *much* larger) and manually run the JVM in your runner (adding substantial memory overhead) you can certainly do so, but that's not something that will be included in the `flutter create` template.
