### ISSUE TITLE
HttpClient setClientAuthoritiesBytes not working

### ISSUE THREAD

**Issue by alexrainman** [flutter/flutter#86365]
## Steps to Reproduce

1. Load .p12 file from assets

```
ByteData keystore = await rootBundle.load('assets/security/client.pfx');
final String passPhrase = "mypassphrase";
```

2. Set SecureContext

```
SecurityContext sc = SecurityContext();
sc.setClientAuthoritiesBytes(keystore.buffer.asInt8List(), password: passPhrase);
HttpClient client = HttpClient(context: sc);
```

3. Run a post

```
final request = await client.postUrl(Uri.parse('myserveruri'));
request.headers.set(HttpHeaders.contentTypeHeader, "application/json");
request.add(json.encode(body).codeUnits);
final response = await request.close();
```

Error:

```
Exception has occurred.
HttpException (HttpException: , uri = myserveruri)
```

Running this on my dev environment without client certificate works as expected.

**Comment by darshankawar** [comment]
@alexrainman Hi,
I think this issue belongs to dart-lang repo since you are using `dart:io` related methods. Please open this issue in dedicated repo. I see that you've already commented about same issue:  https://github.com/dart-lang/sdk/issues/37173

Also check out this issue and see if it helps:  https://github.com/flutter/flutter/issues/27536

Closing from here. If you disagree or think this issue should belong in this repo, write in comments and I'll reopen it.

**Comment by alexrainman** [comment]
Dart? Flutter? It is very difficult to separate one from the other.

Does HttpClient belongs to Dart or Flutter? What is not working here is this part:

sc.setClientAuthoritiesBytes(keystore.buffer.asInt8List(), password: passPhrase);

**Comment by darshankawar** [comment]
HttpClient belongs to `dart:io` library used by Flutter. 
Can you provide a complete minimal reproducible code sample that we can directly use to verify this ?
