### ISSUE TITLE
flutter doctor issue

### ISSUE THREAD

**Issue by VishakhMehta** [flutter/flutter#86462]
I was using flutter 2.2.2 and I upgraded to 2.2.3. I'm unable to run flutter doctor --android licenses. I already tried to solve it using a previous issue about it on github but nothing is working.

This is the output of `flutter doctor -v`:

![image](https://user-images.githubusercontent.com/51699332/125736789-33c6a448-5650-4d25-a075-73fa0f346fd2.png)

This is the output of `flutter doctor --android-licenses`:

![image](https://user-images.githubusercontent.com/51699332/125736882-77e356fb-7497-44e4-86c8-c02800f1a26f.png)

Someone suggested that I download the Android SDK Command-Line Tools (latest) on my Android Studio.

This is the output of `flutter doctor --android-licenses` after doing this:

![image](https://user-images.githubusercontent.com/51699332/125737142-d89bdca3-ae74-4445-afa0-22b9e0483299.png)

I am using Android studio 4.2.1. Is it occurring because of that?

**Comment by maheshmnj** [comment]
Hi @VishakhMehta,
Thanks for filing the issue, Please remember to share the proper logs in future issues rather than the screenshots. Did you download the Android SDK command-line tools? 
if not can you try downloading by [following this link ](https://stackoverflow.com/a/60705505/8253662), And in case if you have already downloaded it, try to uncheck the  
 - Android SDK command-line tools
 - Apply (Let it delete)
 - recheck and apply (redownload)

**Comment by VishakhMehta** [comment]
Yes, I downloaded the Android SDK Command-Line Tools which caused the error as shown in image 3.

**Comment by maheshmnj** [comment]
Please paste the output of `flutter doctor -v`.

**Comment by VishakhMehta** [comment]
I've followed the instructions in issue #56778 and it worked.
