### ISSUE TITLE
SocketException: OS Error: Connection reset by peer, errno = 104, address = xxx.xxx.xxx, port = 43606

### ISSUE THREAD

**Issue by hanjt** [flutter/flutter#86486]
My code is 
```
 List results = await Future.wait([
        A,
        B,
        C,
        D,
        E,
        F,
        G,
      ]).catchError((e, stack) {
        debugPrint('Future.exception : $e $stack');
      });
```

And error message is `SocketException: OS Error: Connection reset by peer, errno = 104, address = xxx.xxx.xxx, port = 43606`

Some  WiFi / 4G have the problem.

**Comment by darshankawar** [comment]
@hanjt 
`SocketException: OS Error: Connection reset by peer, errno = 104` may be causing due to your ISP blocking the connection. you can try with a different internet provider and see if it helps.
Also, check this similar issue and see if it helps. https://github.com/flutter/flutter/issues/44164#issuecomment-549735577

You can also ask this issue on support channels like StackOverflow for solutions. Closing from here.
If you disagree or think this is a bug in sockets, write in comments and I'll reopen with valid argument.
Thanks.
