### ISSUE TITLE
Google Maps Marker animation on marker location update

### ISSUE THREAD

**Issue by heeshala** [flutter/flutter#86597]
There is no possibility to animate the navigation of a marker when location is changed

Eg from A location to B location when LatLong is updated the marker jumps there is no smooth movement to the new location

Instead in java there is an option called animator where interpolar animation can be done like uber vehicles moving smoothly on location update

**Comment by maheshmnj** [comment]
Hi @heeshala,
You could achieve this by listening to the location changes and then animating the camera to that location.
Here is a solution mentioned on stackoverflow: https://stackoverflow.com/a/59873409/8253662

Since this bug doesn't seem to describe a issue or a feature request, I am going to close this as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
