### ISSUE TITLE
Access to the path of the application's config directory

### ISSUE THREAD

**Issue by james-bay** [flutter/flutter#86602]
I would like to be able to cross-platform access to the standard application config directory. That is: 
`$HOME/.config`
`C:\Users\UserName\AppData\`
etc. 
I didn't find that in `path_provider`

**Comment by stuartmorgan** [comment]
Can you give a full list of what you expect this to return on each platform? If the two you listed, the Windows path is the same as what's already provided, and I don't know what directory you're looking for on iOS or macOS.

It's not clear to me that this is actually a cross-platform concept.

**Comment by ljonya** [comment]
That's a very good idea. More specifically, I would like to access the following directories:
### System-wide configuration:
Windows: `%PROGRAMDATA%\_APPNAME_` or `C:\ProgramData\_APPNAME_`
Linux: `$XDG_CONFIG_DIRS/_APPNAME_` or `/etc/xdg/_APPNAME_`
macOS: `/Library/Application Support/_APPNAME_`

### System-wide temp directory:
Windows:  `%TEMP%\_APPNAME_` or `%TMP%\_APPNAME_` or `C:\Users%\USER%\AppData\Local\Temp\_APPNAME_`
Linux: `$TMPDIR/_APPNAME_` or `var/tmp/_APPNAME_` (more persistence as with Windows, suitable for large files, always mountable)
macOS: `$TMPDIR/_APPNAME_` or `var/tmp/_APPNAME_`

### User-level configuration of applications:
Windows: `%APPDATA%\_APPNAME_` or `C:\Users\%USER%\AppData\Roaming\_APPNAME_`
Linux: $`XDG_CONFIG_HOME/_APPNAME_` or `$HOME/.config/_APPNAME_`
macOS: `$HOME/Library/Application Support/_APPNAME_`

### User-level application cache dir:
Windows: `C:\Users\%USER%\AppData\Local\_APPNAME_`
Linux: `$XDG_CACHE_HOME/_APPNAME_` or` $HOME/.cache/_APPNAME_`
macOS: `$HOME/Library/Caches/_APPNAME_`

### User-level application data:
Windows: `%LOCALAPPDATA%\_APPNAME_` or `C:\Users\%USER%\AppData\Local\_APPNAME_`
Linux: `$XDG_DATA_HOME/_APPNAME_` or `$HOME/.local/share/_APPNAME_`
macOS: `~/Library/Application Support/_APPNAME_`

### User-level application logs: 
Windows: `%TEMP%\_APPNAME_\Logs` or `%TMP%\_APPNAME_\Logs` or `C:\Users%\USER%\AppData\Local\Temp\_APPNAME_\Logs`
Linux: `XDG_STATE_HOME/_APPNAME_/logs` or `$HOME/.local/var/lib/_APPNAME_/logs` (according to XDG)
macOS: `~/Library/Logs/_APPNAME_`

I could be wrong about the paths, but this is how I see it so far. 
I don't know about mobile devices, I have a Nokia 3220

The `_APPNAME_` variable is supposed to consist of `producer_name/project_name` if `producer_name` is set or just `project_name`, where `project_name` = `name` in `pubspec.yaml`.

**Comment by stuartmorgan** [comment]
I'm still not clear what conceptual difference you are drawing between "user-level data" (which is already there) and "user level config". On macOS going listed the same path. On Windows you've listed the same path except that one is roaming and the other is local, for reasons that are not clear to me; I don't see why data would be local-only.

If really only want the config directory on Linux, why not just use `xdg_directories` to get it?

**Comment by ljonya** [comment]
@stuartmorgan The difference is simple, the data is e.g. a database file, the config are settings.json. Cross-platform variant, should take into account the peculiarities of different operating systems. If in macOS it is common to store different things in the same directory, then it should be in the same directory. In Linux it is common to separate configs and data. 
On Windows, large files are not stored in Roaming because of the overhead of roaming. So configs go into Roaming, big files like the database go into Local. You can take a look at the example paths in the [JetBrains](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) products. 

Using the `xdg_directories` is Linux-centric and not cross-platform.

**Comment by stuartmorgan** [comment]
>If in macOS it is common to store different things in the same directory, then it should be in the same directory.

Abstracting this away is potentially dangerous, however. It is very non-obvious that storing a file with the same name in two "different" directories would be fine on Windows and Linux, but silently destroy data on macOS.

> In Linux it is common to separate configs and data.
> On Windows, large files are not stored in Roaming because of the overhead of roaming. So configs go into Roaming, other files go into Local.

"Config vs. data" and "large vs small" are not the same conceptual difference. A to-do list application on Windows would store its data in roaming, not local, because it is small, and can't easily be recreated in another machine.

Abstractions only work when there is sufficient alignment of the concept on the underlying platform.

> You can take a look at the example paths in the [JetBrains](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) products.

And you can see that there *is not* cross-platform alignment over which of those are the same or different across different platforms. They made a per-platform differentiation, which your suggested abstraction would not do.

> Using the `xdg_directories` is Linux-centric and not cross-platform.

My point is that the distinction between "configuration" and "data" is itself not cleanly cross-platform. Just as a local vs roaming abstraction would work for Windows, but not for Linux or macOS.

**Comment by ljonya** [comment]
> And you can see that there is not cross-platform alignment over which of those are the same or different across different platforms. They made a per-platform differentiation, which your suggested abstraction would not do.

If you take their names and paths (except for plugins), add paths to cache and correct only path to logs according to XDG, it will be almost the same as I suggested and I am completely satisfied.

**Comment by ljonya** [comment]
and if you replace JetBrains "System (idea.system.path): ~/.cache/JetBrains/IntelliJIdea2020.3" path with "System (idea.system.path): ~/.local/share/JetBrains/IntelliJIdea2020.3", it is the same as I suggested :)

**Comment by stuartmorgan** [comment]
> If you take their names and paths (except for plugins) and correct only path to logs according to XDG, it will be almost the same as I suggested and I am completely satisfied.

Those is how they may to your config proposal:

Windows:
Config
Config
Data
Data

macOS:
Both
Both
Neither
Neither

Linux:
Config
Neither
Neither
Neither
 
That's not a strong case for this being a consistent cross-platform concept.

You've also not responded to the general conceptual problem I raised above, nor the trivial example where that abstraction breaks down.

**Comment by ljonya** [comment]
At first I thought that excluding the data directory would solve the problem, but yes, it doesn't solve the overall problem with the probability of data destruction (especially on Windows).  I guess I should leave it as it is.

**Comment by stuartmorgan** [comment]
> I think it should be left as is.

Does this mean you want to close the request, or that you're proposing something different?

**Comment by ljonya** [comment]
> > I think it should be left as is.
> 
> Does this mean you want to close the request, or that you're proposing something different?

But I didn't open it. Perhaps the creator of the issue has some suggestions?

**Comment by stuartmorgan** [comment]
> But I didn't open it.

Sorry, I missed that all of the replies to my questions were from someone other than the reporter.

**Comment by james-bay** [comment]
Yes, I have nothing really to offer, so I closed the issue.
