### ISSUE TITLE
Tests with coverage takes 10x time than just running flutter test

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#86722]
## Details

A codebase with 80 tests (unit and widget tests) takes 12 seconds to run tests (both unit and widget tests) without coverage and a seed; however, it takes 3 and half minutes to to complete with coverage and a random seed.

```bash
❯ flutter test
00:12 +80: All tests passed!
❯ flutter test --no-pub --coverage --test-randomize-ordering-seed random
Shuffling test order with --test-randomize-ordering-seed=1858316085
03:36 +80: All tests passed!
```

Flutter Doctor:

```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 11.4 20F71 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)
```

**Comment by jorgecoca** [comment]
FYI in the past we had this issue as well: https://github.com/flutter/flutter/issues/23157

**Comment by iapicca** [comment]
@TahaTesser

**Comment by eseidelGoogle** [comment]
This came up in our weekly sync this morning with Nevercode.  FYI @grouma

**Comment by grouma** [comment]
cc @natebosch 

I don't expect `--test-randomize-ordering-seed` to be slowing down your tests but it would be good to confirm. Can you run your tests with only coverage enabled, and only randomization enabled to see what the performance characteristics are?

**Comment by natebosch** [comment]
cc @a-siva @jonahwilliams who have investigated other cases where coverage slows down testing.

I agree that this effect is likely caused by coverage, not test shuffling.

**Comment by jorgecoca** [comment]
Yes, I can confirm shuffling does not have a big impact (we just run our tests with a random seed always by default, that's why it was included).

Here are the results on the same codebase (we just added a few more tests over the week):

```bash
❯ flutter test
00:14 +94: All tests passed!
❯ flutter test --no-pub --coverage
04:30 +94: All tests passed!
```

**Comment by grouma** [comment]
cc @liamappelbe who owns `package:coverage` for the VM platfoorm.

**Comment by Hixie** [comment]
Does the random seed have any impact on the performance here? The numbers above confound random seed and coverage as far as I can tell.

**Comment by jorgecoca** [comment]
The random seed does not have an impact, just the `coverage` flag

**Comment by aam** [comment]
Note also https://github.com/dart-lang/sdk/issues/45985 that is tracking slow coverage testing.

**Comment by cmc5788** [comment]
This comment is probably unhelpful, but running with coverage locally not only takes 10x longer but spins up my laptop fans so hard that it sounds like a helicopter about to take off the whole time 😂

**Comment by liamappelbe** [comment]
Context: I work on the Dart VM and am one of the maintainers of `package:coverage`.

I did a bit of printf benchmarking of flutter test today, and I've confirmed that the coverage slowness is caused by the large number of RPCs that the coverage collector is doing. Specifically, here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/coverage_collector.dart#L221

It does a `service.getSourceReport` and `service.getObject` call for every script in every isolate. I was running `sector_layout_test.dart` from the flutter tests, and it takes 2 seconds without coverage and 16 seconds with coverage, because it's doing ~2700 RPCs, each of which takes about 5ms.

Interestingly, it seems `coverage_collector.dart` doesn't really use `package:coverage` at all (except for a few utilities that aren't part of the slowness). `coverage_collector.dart` is essentially re-implementing `package:coverage`'s `collect.dart`. That's not to say `package:coverage` doesn't also have this slowness issue, but any fix I add to `package:coverage` won't benefit flutter.

Some possible fixes:
 - Implement some filtering to restrict the source files that it looks up coverage info for. Maybe we don't need all this data? I don't have enough information to answer that though.
 - Presumably when this test pulls in data about ~1350 source files, that's most of flutter. But when I run multiple tests, the slow down is a multiplier rather than a constant 15 second overhead, so is it pulling in those files for each test? I'll try running multiple tests tomorrow to check if it's duplicating RPCs. `package:coverage` has a lot of caching for this stuff, but at first glance I don't see any such caching in `coverage_collector.dart`.
 - There was a suggestion on another thread that the VM service protocol might be compressing the responses by default, and we could speed things up by disabling this. I don't know where this setting would be in flutter though.
 - Another suggestion I've heard is to move all this coverage processing logic into the VM and just have a VM service RPC to get all the coverage data. This might work, but we consider it a last resort, as it would be against the general design of the VM service protocol.
 - Add a batching API to the VM service protocol so we can request multiple objects with a single RPC. This would be a lot of work, but would probably be worth it. This is the approach I'm leaning towards if the quick fixes don't work, because it's the most general and straightforward solution.

**Comment by jonahwilliams** [comment]
@liamappelbe you might find go/better-dart-coverage interesting.

**Comment by TahaTesser** [comment]
Similar issue was reported in https://github.com/dart-lang/test/issues/1423

**Comment by vincevargadev** [comment]
@jonahwilliams Where can we find "go/better-dart-coverage"? Is it an internal Google link?

**Comment by jonahwilliams** [comment]
Yes, the TLDR; coverage downloads a ton of JSON data as @liamappelbe mentions above and that is where 99% of the time goes

**Comment by liamappelbe** [comment]
@jonahwilliams Thanks for the doc. It seems that several of these mitigations have already been implemented, and the results section says that they reduced single test time from 15 seconds to 3 seconds. Now 2 years later we're back to 15 seconds. Has performance regressed that much, or were the mitigations not landed? Where do you think I should be focusing my efforts to improve performance? Is there a change we can make to the VM service API to help?

**Comment by jonahwilliams** [comment]
It's possible there were regressions that we missed since we only tested on the equivalent of the "hello world" flutter app. The other likely possibility is that since the mitigations only excluded extra information from dart:* libraries that would be discarded, once the app gets to a certain size it does not matter as much.

If you wanted to fix this "once and for all", I think we'd need a new RPC that used a much more efficient encoding of the data - either using the hitmap format directly, or using a binary encoding in place of JSON to sidestep the cost of deserializing large JSON structures.

**Comment by liamappelbe** [comment]
Ok, I'll talk to my team about it. I'm less concerned with the amount of data being downloaded than the sheer number of requests. When the server is running on the same machine as the test framework, I'd expect that downloading a few tens of MB (or even hundreds) via a loopback IP would be negligible compared to the 13 seconds of overhead I'm seeing. So my hunch is that batching will help.

**Comment by jonahwilliams** [comment]
I suspect that the JSON de-serialization of 100s of MBs of data is going to contribute more than request overhead.

**Comment by liamappelbe** [comment]
I discussed it with the VM team. Switching from JSON to a binary format is going to be very difficult, since the format needs to be compatible between versions and we don't want to pull in additional dependencies such as protocol buffers.

Some alternative solutions I'm going to investigate/implement:
1. The token position to line number mapping should be consistent between tests for a given source file, so I'll add a cache for that. This means that half of the RPCs will only have to happen once, so for large test suites this should roughly halve the test time.
2. We can get the coverage report for the entire isolate at once, rather than per script. Combined with fix 1, this means that for large test suites the number of RPCs will be O(tests) rather than O(tests*srcs). Whether or not this actually saves any time depends on the source of the slowness, since it will mean the library filter is applied after the RPC.
3. Similar to 2, I think we can also get the coverage report per library, which might be better because we should be able apply the library filter here.
4. We can add a mode to the source report that reports line numbers rather than token positions, eliminating the need for the separate RPCs to get the token pos to line number map.
5. I think the RPC that gets the token pos to line number map implicitly gets the source code, which flutter's coverage tool isn't using. So maybe we should have a way for the API to not return the source code.
6. I also mentioned the idea of returning the lcov report directly in the RPC, and they weren't as opposed to it as I thought they'd be, so this is also an option if the other fixes aren't sufficient.

**Comment by jonahwilliams** [comment]
for 6. you don't necessarily need the exact LCOV format, but you could have a structure like `Map<Script, Map<Line, int>>` that returns hits. It would significantly more compact, still JSON, and trivially convertible into lcov

**Comment by grouma** [comment]
Getting back from vacation so I may be missing some context but I recall resolving some internal customers performance issues with the use of this: https://github.com/dart-lang/coverage/pull/262

See cl/259645244. Coverage for an internal customer would timeout after 620+ seconds but properly using this argument would allow the coverage runs to complete in ~14 seconds.

**Comment by Hixie** [comment]
Writing a binary version of JSON doesn't require more than a few hundred lines of Dart code (speaking from experience having done it a few times) and certainly doesn't require importing protobufs. It would be pretty easy to have the VM Service support both formats for a few years until all the clients have migrated.

**Comment by liamappelbe** [comment]
I've implemented and benchmarked the first two fixes (caching the get script RPCs and doing one source report RPC per isolate). I ran a bunch of arbitrary test suites from the flutter repo, but this isn't a project I do much direct work on, so let me know if there's other tests that would be good to try. The results are a bit mixed.

| Suite | No coverage | Coverage | Cov with script cache | Cov with isolate report |
| --- | --- | --- | --- | --- |
| [All packages/flutter tests](https://github.com/flutter/flutter/tree/master/packages/flutter) | 4:08 | 71:12 | Timeout | 39:15 |
| [physics tests](https://github.com/flutter/flutter/tree/master/packages/flutter/test/physics) | 0:03 | 0:51 | 0:37 | 0:28 |
| [A single random flutter test](https://github.com/flutter/flutter/blob/master/packages/flutter/test/examples/sector_layout_test.dart) | 0:02 | 0:16 | 0:15 | 0:12 |
| [hello_world example tests](https://github.com/flutter/flutter/tree/master/examples/hello_world) | 0:02 | 0:02 | 0:02 | 0:05 |
| [flutter_gallery integration tests](https://github.com/flutter/flutter/tree/master/dev/integration_tests/flutter_gallery) | 1:40 | 1:44 | 1:45 | 2:00 |
| [flutter_tools tests](https://github.com/flutter/flutter/tree/master/packages/flutter_tools) | 13:46 | 17:26 | 19:00 | 19:09 |

Caching the get script RPCs turned out to be less effective than I thought, since only about 30% of the requests actually hit the cache. I also haven't been able to figure out why this change causes timeouts for the very large flutter test suite. So given that it's going to be moot once I implement fix number 4, I'm probably not going to go ahead with this change. [Changes here](https://github.com/liamappelbe/flutter/compare/10e53e99819444e6e533ef54e9f40bd4b2052e7a..76965989bf7962c00d9068a79ca7e816ebfd35f8).

Doing one source report RPC per isolate, rather than for each script, was very effective for large test suites, but for small suites it took longer. [Changes here](https://github.com/liamappelbe/flutter/compare/10e53e99819444e6e533ef54e9f40bd4b2052e7a..3d54be4f7ab5b9ab6d000d5193f42a16ad967059). We should definitely implement some version of this change. There's a few options, depending on the flutter team's appetite for adding flags or complexity to the tool:
1. Land it as is. Even in the worst cases it doesn't slow things down much in absolute terms.
2. Decide whether to do per script or per isolate source reports based on a heuristic of the number of scripts under test.
3. Put this change behind a flag, so the user can decide if it saves time for their project or not.

**Comment by Hixie** [comment]
(If I can make a vague plea for not having a flag: nobody will ever use this flag except by mistake. Few enough people use coverage as it is, the odds that they'll use it _and_ learn to use the flag _and_ do so optimally are minimal at best.)

**Comment by liamappelbe** [comment]
Yeah, that's what I thought. Would you vote for a heuristic, or just enable it unconditionally?

**Comment by jonahwilliams** [comment]
@liamappelbe for small test suites/projects the coverage report will be dominated by coverage data from dart:* libraries that are not used. Perhaps provide a parameter to exclude those (since we discard that data anyway)

**Comment by Hixie** [comment]
Update from @liamappelbe: _I benchmarked inlining the line numbers in the coverage report and it saves a lot of time, so I'm about to start adding that as an option to the VM service API_

**Comment by Hixie** [comment]
Update from @liamappelbe: _I just mailed the first CL today, which has the API changes and the VM implementation: https://dart-review.googlesource.com/c/sdk/+/211081_

**Comment by liamappelbe** [comment]
I have a CL that updates flutter_tools to use reportLines, but it's blocked on updating package:dwds due to version constraints.

I also benchmarked a client side mitigation for particularly slow test suites. The test framework runs each test separately and gathers coverage data for each test before merging all that data into a single report. So if you have a large test suite for a densely interlinked project, this will mean something like O(test_files * project_files) getSourceReport RPCs. If we could run all the tests in a single isolate, this would reduce to O(test_files + project_files). I don't know if it's possible to rewrite the test framework to run tests this way, but users can write a wrapper test that runs all their other tests. For example, for the [physics tests](https://github.com/flutter/flutter/tree/master/packages/flutter/test/physics), I wrote this wrapper test:

```Dart
import 'package:flutter_test/flutter_test.dart';

import 'clamped_simulation_test.dart' as clamped_simulation;
import 'friction_simulation_test.dart' as friction_simulation;
import 'gravity_simulation_test.dart' as gravity_simulation;
import 'near_equal_test.dart' as near_equal;
import 'newton_test.dart' as newton;
import 'to_string_test.dart' as to_string;
import 'tolerance_test.dart' as tolerance;
import 'utils_test.dart' as utils;

void main() {
  group('friction_simulation', friction_simulation.main);
  group('gravity_simulation', gravity_simulation.main);
  group('near_equal', near_equal.main);
  group('to_string', to_string.main);
  group('tolerance', tolerance.main);
  group('newton', newton.main);
  group('utils', utils.main);
  group('clamped_simulation', clamped_simulation.main);
}
```

The physics tests are particularly affected by --coverage. Without coverage they run in 3 sec, with coverage they run in 51 sec, and with reportLines they run in 22 sec. This wrapper runs those same tests without coverage in 3 sec, with coverage in 15 sec, and with reportLines in 9 sec.

So users who are really badly affected by --coverage might want to consider writing a wrapper test like this.

**Comment by annagrin** [comment]
@liamappelbe do you need an actual support of the reportLines parameter or just a version of dwds that ignores it and is compatible with the VMService protocol 7.3.0?

**Comment by annagrin** [comment]
for the latter: is https://github.com/dart-lang/webdev/pull/1407

**Comment by liamappelbe** [comment]
Just the latter I think

**Comment by annagrin** [comment]
published dwds, here is the CL updating dwds and vm_service in flutter:

https://github.com/flutter/flutter/pull/89797

**Comment by a-siva** [comment]
@zra and @cbracken please see comment from @liamappelbe here https://github.com/flutter/flutter/issues/86722#issuecomment-914688482.
Changes in the way flutter test is run could significantly improve flutter test times with coverage. Is such a change feasible ?

**Comment by dnfield** [comment]
I think this change is not feasible. It changes the semantics of the test, and may make tests that currently pass start to fail, as well as impact the way random ordering seeds are handled. 

For example, we have some tests that are explicitly split into separate files because of the way they impact global state. Ideally there's no global state to impact, but in some cases refactoring code to avoid that will be very expensive and potentially breaking - in particular, the way that `Binding` classes are handled in Flutter.

There may be good reasons to try to group tests into singular compilation units - possibly faster overall compilation time, less disk I/O and cleanup, etc. - but coverage should not depend on this.

**Comment by annagrin** [comment]
@liamappelbe dwds and vm_service are now updated in flutter.

**Comment by christopherfujino** [comment]
> If we could run all the tests in a single isolate, this would reduce to O(test_files + project_files). I don't know if it's possible to rewrite the test framework to run tests this way...

Here's a proof-of-concept test-runner that I believe runs all the tests in a single isolate: https://github.com/jonahwilliams/tester

**Comment by zanderso** [comment]
As @dnfield mentions, automatically refactoring an app's tests to be executed from the same isolate isn't safe, in general.

However, we could consider documentation updates that guide developers to this pattern. We should proceed with the improvements @liamappelbe already has going, independent of that, though.

**Comment by a-siva** [comment]
> As @dnfield mentions, automatically refactoring an app's tests to be executed from the same isolate isn't safe, in general.
> 
> However, we could consider documentation updates that guide developers to this pattern. We should proceed with the improvements @liamappelbe already has going, independent of that, though.

the improvements @liamappelbe is making is independent and will land but bridging the gap further is going to be harder.
I can understand that tests with potential side effects would be hard to combine into a single isolate but I don't believe all the tests in the set have side effects.

**Comment by dnfield** [comment]
Perhaps this has already been considered, but could the VM just take a flag that would generate a coverage file (e.g. an lcov file directly) - rather than needing any RPC calls to gather and generate some JSON based format?

**Comment by dnfield** [comment]
Talked with @a-siva offline about this. The LCOV idea might help but it's not clear how much.

One thing we might be able to do that's closer to what @liamappelbe is suggesting is running each test suite in its own isolate, or hot restarting it into an isolate. This might be closer to what @christopherfujino and @jonahwilliams had in mind. 

This would still lose things like tags from `package:test`, but maybe if `package:test` itself supported this it could still work.

**Comment by Hixie** [comment]
I would much rather have fast coverage than tags... :-)
(I may have literally never used package:test tags ever.)

**Comment by dnfield** [comment]
The framework uses tags now to help with the shuffle migration and to avoid running non-golden tests on certain platforms

**Comment by liamappelbe** [comment]
#90142 is merged. That should mitigate the worst slowdown cases. So can we downgrade the priority of this bug? Or close this bug and file separate issues for the other discussions?

**Comment by zanderso** [comment]
Closing this, and tracking the ideas that @dnfield mentions as separate issues sgtm.
