### ISSUE TITLE
Linux Web Engine Red on "Reformat manifests"

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#86756]
Linux web engine is red on https://github.com/flutter/engine/pull/27603

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/6080/overview

cc @tamird @yjbanov

**Comment by zanderso** [comment]
I'd be surprised if the "Reformat manifests" PR is related.

**Comment by GaryQian** [comment]
It could be infra changes landed by @CaseyHillers

**Comment by CaseyHillers** [comment]
The current errors start on 651dd485 relating to the felt unit tests. My infra change starts on 651dd485.

I unfortunately didn't see the tree closure and mistakenly submitted my tree due to a red tree, so sorry if there's any confusion. Any errors stemming from the infra change shouldn't appear until rolls
