### ISSUE TITLE
Text Widget minLines property

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#87001]
Purpose is to havw the Text widget occupy the same height as that when maxLines is reached.

This is useful in Gridview where each item height is the same.

If a Text has only 1 line while the other grid column has Text with 3 lines, their widget height will be the same with the minLines propertt.

=====            =====
=====            =====
=====            Line1
Line1             Line2
Line2             Line3

=== is the image itself. so the first grid column image occupies more height since the Text has only 2 lines.

**Comment by darshankawar** [comment]
@chitgoks
Please elaborate on the issue by providing `flutter doctor -v` and a minimal code sample that shows the current limitation and a proposal / feature request you would like to see in the framework. Also try to use `feature request` option from `new issue` template, so that we can properly address this. https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
