### ISSUE TITLE
Launching debug Flutter without a host computer ios 14.5 not working

### ISSUE THREAD

**Issue by heeshala** [flutter/flutter#87034]
Although it is possible to launch the app through Xcode it is still not possible to launch the app without Xcode. Is there a fix ? I reviewed and saw that the error was reported last year

**Comment by darshankawar** [comment]
@heeshala 
Check [this](https://flutter.dev/docs/development/ios-14#launching-debug-flutter-without-a-host-computer) link and see if it helps to answer your question.

**Comment by heeshala** [comment]
Yes i referred it so is there no possibility at the moment to relaunch without a host machine? Will there be a near update ?

**Comment by darshankawar** [comment]
Per the documentation:

`To launch the application in debug mode on a physical device again, re-run the app from the host computer (by using flutter run, a Flutter-enabled IDE, or Xcode).`

This seems to be the way to go at the moment. I am not sure about a near update on this at the moment.
Also check this issue comment for your reference, https://github.com/flutter/flutter/issues/60657#issuecomment-688478590

`All Flutter apps built with a Debug Flutter build cannot be launched on iOS 14 physical devices from the device itself without a host computer. This includes launching via the home screen (springboard), deep linking, notifications etc. This is a new restriction from iOS 14 on apps' ability to set itself in debug mode in order to change the execution mode of newly JIT'ed code.`

I am going ahead and closing this as above links should help you to answer your original question. If you disagree, write in comments and I'll reopen it.
Thanks.
