### ISSUE TITLE
Getting Started says "Click the Hot Reload button" but it's not clear what that is

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8717]
(From a UX study today)

On https://flutter.io/getting-started/

Step 3 says "Click the Hot Reload button."

There are two buttons that look like they could be Hot Reload.

Could we show a screenshot for the button, in the doc?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by InMatrix** [comment]
In addition, it's easy to miss the moment the hot reload button is clicked in the animation on the Getting Started page. Maybe stop the animation and call out where the button is before it is clicked?

**Comment by johnmccutchan** [comment]
See also https://github.com/flutter/flutter-intellij/issues/803

1. Some users are not aware that hot reload is even a thing. Should we start prompting developers who click restart to try reload?
2. The icons are indescribable and unmemorable (both reload and restart). 
3. I think the restart icon should be hard to get to, i.e. not directly next to the reload button.

**Comment by sethladd** [comment]
Naive question: Why can't the Green Run Button turn into "Hot Restart" after the first run? If we can do that, I have only two buttons. Green Run button is for "first launch" or Hot Restart, the lightning bolt button is Hot Reload.

**Comment by Hixie** [comment]
There's some bug where I described what I would like to see in more detail, but briefly my ideal is something like a single button with a drop-down which when clicked does a run or hot reload as appropriate, and when dropped down allows you to pick between hot reload, hot restart, cold restart, start profile, start release.

**Comment by mit-mit** [comment]
Meta-comment: Changes to this UX are "delicate"; even small changes can have large effects, and we have seen a number of times now that changes that we thought intuitively would work did in fact not work. So we need to approach this methodically, and through validated step-wise increments. CC @lukechurch 

@johnmccutchan yes, I'm agree that we need to do something. I just checked analytics, and in flutter_tools in Feb. we saw a distribution of reload/restart of 5064/2627 = 66%/34%. In IJ the numbers are almost the same: 6803/3164 = 68%/32%. I would think generally reloads should be in the 90-95% range...

@sethladd that was my intuition as well, but Android Studio went down that path a few releases, and realized that it did not work and caused lots of confusion. In they most recent design they just reverted the whole thing: https://android-developers.googleblog.com/2017/03/android-studio-2-3.html

@Hixie interesting proposal!

**Comment by sethladd** [comment]
From the blog post: "The Run action will now always cause an application restart to reflect changes in your code that may require a restart, and the new Apply Changes action will attempt to swap the code while your app keeps running"

I think that's what I'm suggesting. Two buttons: Run (start or hot restart, depending on if the app is launched on the device yet), and Lightning Bolt (hot reload).

Maybe I'm missing something, but that's my intuition for what to try next.

**Comment by mit-mit** [comment]
Sorry, I misunderstood then. Yes, I made a note over in https://github.com/flutter/flutter-intellij/issues/803 that I think that design sounds promising.

**Comment by sethladd** [comment]
No worries. Glad to see we're still iterating!

**Comment by Hixie** [comment]
FWIW we've seen a number of people just assume that saving will trigger hot reload. It might be worth just going down that route.

**Comment by lukechurch** [comment]
@Hixie I've seen this in a couple of the studies as well.

However, hot reload on save can be pretty problematic as well. A lot of developers have developed a habit of e.g. saving between switching tabs to avoid a raft of subtle problems (e.g. manually reloading and debugging a behaviour to only discover later that the code that was running was in a buffer but not saved).

Tieing hot-reload to save means that we'd need a good story about what to do in cases like this so as to not make the editor feel fragile. I would certainly recommend a slightly cautious approach to turning it on, perhaps a prototype?

I think we might be better going to the route of displaying a diff between what has been done since the last hot reload in a 'flutter pane' with a bigger hot-reload button. That would also give us some screen real-estate to add other richer debugging/diagnostics information to.

**Comment by sethladd** [comment]
Why do they think saving is sufficient to trigger the reload? Do we ever say that? Or hint at it?

**Comment by InMatrix** [comment]
@sethladd for the last two participants, they both used tools to watch code changes for web development. Also, our wording on [Getting started]( https://flutter.io/getting-started/) about hot reload might be slighly misleading: "Hot reload reloads your app very quickly **after a change to your source code**, offering a best-in-class development cycle."

**Comment by sethladd** [comment]
Good catch! Easy to fix wording :)

(/me is surprised the web dev tools actually triggered a reload of the webpage, especially with complex frameworks like Angular... ?)

**Comment by InMatrix** [comment]
@hixie @lukechurch There are a few UI remedies, addition to what Luke has mentioned, we can try before going down the path of tying hot reload to file changes:

1. Make the hot reload button visually different when there are new changes to the code. After the reload is performed, the hot reload button will return to its "inactive" appearance.
2. Provide some affordance on the device/simulator for triggering Hot Reload when there are changes to the code? This will provide a similar experience of refreshing the webpage in the browser.
3. Say something in the console along the lines of "The code has changed. Do a hot reload to refresh the app in the simulator/device."

@sethladd they didn't confirm if their dev tools did auto refresh of the webpage. I think this issue is a combination of an incorrect mental model and lack of clarity in our docs and tools.

**Comment by Hixie** [comment]
FWIW in my dev environment I have hot reload hooked to the same keystroke as "save all and show analyzer errors", and it works reasonably well. When there's a syntax error, the hot reload just gets skipped, you don't end up in a bad state. I much more often end up in a bad state after doing something intentional, like changing a stateless widget to a stateful widget (which the framework can't handle), or adding a member variable with a null value then changing the semantics of the code to not accept null as a value (which usually leads to exceptions galore).

**Comment by lukechurch** [comment]
@sethladd @InMatrix I asked one of the participants who thought that reload might happen on save. 

They said that their instinct that it might came from using https://browsersync.io/ and https://github.com/bhauman/lein-figwheel

**Comment by johnmccutchan** [comment]
I don't think automatic reloading is a good idea. Mostly because it interferes with a developer making changes to multiple files and I worry it could lead to an impression that hot reload is a less buggy because we end up reloading at the *wrong* times.

Also, personal anecdote, I save my files all the time, even when I'm not happy with their contents.
