### ISSUE TITLE
[cocoon] Add AppEngine health checks

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#87222]
These should ensure requests to `/api/public/get-status` work before marking the instance as healthy (thus promoting to prod)

**Comment by godofredoc** [comment]
@CaseyHillers  We are already checking the Dart Appengine application is up and running before redirecting traffic. Can you please share logs or more details of what happened in this release?

**Comment by CaseyHillers** [comment]
@godofredoc the frontend fails. Between 8:04 AM PST to 8:11 AM PST I see 
![image](https://user-images.githubusercontent.com/2148558/128039786-61c9ef53-0e97-4abd-b3ba-e58a6fff8736.png)

I sent a github check, and it wasn't processed. https://github.com/flutter/flutter/pull/87522/checks?sha=1fe7405d39f4b248d7499e9a0e1a4a92552d0eb8 (no flutter-dashboard checks)

**Comment by godofredoc** [comment]
Took a look at the data and the problem seems to be that the `gcloud deploy` is moving traffic as the new version is created. Following the example provided:

8:04 is when the new version is created. Server side 8:04 is when we start getting the few logs.
8:04 - 8:07:33 we see several liveliness and readiness check failures.
8:07:33 we see the first successful liveliness and readiness checks.
8:07:33 cloudbuild side the deployment is now complete.

To try to fix this issue we are setting `gcloud config set app/promote_by_default false` and then cloudbuild side do `gcloud app services set-traffic default --splits version-abc=1 --quiet` after the deploy command is complete.

**Comment by godofredoc** [comment]
Now from the logs I see the correct the correct behavior. Please reopen if you see this issue again.
