### ISSUE TITLE
Flutter web rendering different on mobile

### ISSUE THREAD

**Issue by THeuker** [flutter/flutter#87335]
My Flutter web app is rendering different on mobile.

Components like the back button (with text next to it) only shows up the correct way when pressing or holding
another component. Even a whole container with components in it doesn't show up correctly, no idea where this goes wrong.

On Desktop this app is working well, even when I'm toggling device toolbar to use iPhone X dimensions.

Using Google Chrome on my iPhone won't make a difference for me and also Android didn't work.

So same browsers, same dimensions and same deployed app, but different behaviour.

Try it yourself https://kivi-stemapp.netlify.app and hope someone can help.

Flutter version: 2.2.3 from stable channel.

<img src="https://user-images.githubusercontent.com/51358713/127650803-51cbc1b7-c0f8-4579-b2b2-a2366a3a9310.png" height="450" />

**Comment by TahaTesser** [comment]
Hi @THeuker 
When you build Flutter app, web on desktop vs web on mobile uses different renderers, see [this](https://flutter.dev/docs/development/tools/web-renderers#choosing-which-option-to-use)  for more details

if you have used `flutter build web`, this uses auto, so `canvaskit` on desktop and `html` on mobile, this would make your issue be related to mobile since you're running on mobile 

Can you please provide your `flutter doctor -v` & a complete reproducible minimal code sample,
Thank you

**Comment by THeuker** [comment]
> Hi @THeuker
> When you build Flutter app, web on desktop vs web on mobile uses different renderers, see [this](https://flutter.dev/docs/development/tools/web-renderers#choosing-which-option-to-use) for more details
> 
> if you have used `flutter build web`, this uses auto, so `canvaskit` on desktop and `html` on mobile, this would make your issue be related to mobile since you're running on mobile
> 
> Can you please provide your `flutter doctor -v` & a complete reproducible minimal code sample,
> Thank you

I solved the issue by changing the build command to the following:
`flutter build web --web-renderer canvaskit --release`

This may introduce some performance issues on mobile, but this is a simple app and I don't
see any drops in the first place, so I'm fine with this solution!

Thanks for your help!
