### ISSUE TITLE
flutter tool is too aggressive about catching exceptions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8742]
There are a number of places in the flutter tool where we just catch any exception, print it, then move on, or return failure.

This is masking real errors, and results in confusing error messages. For example, it catches NoSuchMethodErrors and prints them to the user, instead of crashing and generating a crash log.

`try .. catch` blocks should only catch expected exceptions that can be handled, or that can be usefully reported before aborting cleanly.

We should remove all cases of blanket-catching exceptions, and all cases of catching exceptions and printing them but otherwise continuing unaffected.

You can easily find affected files by search for the regexp pattern `} catch \([a-z_]+\) {`.

cc @johnmccutchan

**Comment by zoechi** [comment]
Enabling the linter rule avoid_catches_without_on_clauses would enforce this
https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L52

**Comment by Levi-Lesches** [comment]
Doing a quick search with @Hixie's regex on Flutter itself (ie, not any Flutter packages), not many results came up. However, I'm still having trouble catching all errors for a zone, especially in Futures. [This](https://stackoverflow.com/questions/57879455/flutter-catching-all-unhandled-exceptions) Stack Overflow question seems to have an answer about the problem being debug vs. release mode, but I can confirm that even in release mode these unhandled errors are not being caught. 

1. Should this be closed? The few results that did come up were mostly commented as intentional. 
2. Should I make a separate issue about not being able to catch all unhandled errors? There is at least one other issue(s) about this, such as #10761.

Also cc @yjbanov since he is usually associated with catching unhandled errors.

**Comment by vkammerer** [comment]
I can also confirm that running in release mode doesn't fix the issue: I am still not able to handle errors when implementing the example at https://flutter.dev/docs/cookbook/maintenance/error-reporting#5-catch-and-report-dart-errors

**Comment by Hixie** [comment]
@levi-lesches and @vkammerer: this is about the `flutter` tool, not the framework.

**Comment by tudor07** [comment]
What is `flutter tool`, or what is the difference between `flutter` and `flutter tool`?
Is this issue only a dev thing, or also happening in release?

**Comment by zanderso** [comment]
In https://github.com/flutter/flutter/pull/52021, the tool has enabled the `avoid_catches_without_on_clauses` lint.

**Comment by christopherfujino** [comment]
> What is `flutter tool`, or what is the difference between `flutter` and `flutter tool`?
> Is this issue only a dev thing, or also happening in release?

This only affects devs. The "flutter tool" is the command line tool used in flutter development: https://github.com/flutter/flutter/tree/master/packages/flutter_tools
