### ISSUE TITLE
Hot Restart disappears the moment I click on Hot Restart and ctrl+s stop working Accordingly

### ISSUE THREAD

**Issue by kareemX** [flutter/flutter#87637]
Hot Restart disappears the moment I click on Hot Restart and ctrl+s stop working Accordingly
![image](https://user-images.githubusercontent.com/31194429/128140282-3b085678-e7d7-4cab-91d8-ad231d00a081.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1110], locale ar-EG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

**Comment by darshankawar** [comment]
@kareemX 
What IDE are you seeing this behavior on ?

**Comment by Efaayin** [comment]
I'm experiencing the same problem on VS Code

**Comment by DanTup** [comment]
This was [a bug](https://github.com/Dart-Code/Dart-Code/issues/3511) in v3.25.0 of the VS Code extension and was fixed in v3.25.1. You may need to reload VS Code after it's installed v3.25.1 for the update to be loaded.

If you still see this after upgrading to v3.25.1 and reloading, please file an issue at https://github.com/Dart-Code/Dart-Code/issues. Thanks!

**Comment by Efaayin** [comment]
Thanks
