### ISSUE TITLE
Install instructions mention .bash_profile, but some users don't have that file

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8770]
From a recent study of users onboarding Flutter.

Brand-new Macs sometimes don't have a .bash_profile file, however our instructions indicate that a user should edit that file.

We can help our users by letting them know that the file might not exist, which is OK, and that they should create it in their home directory.

**Comment by Hixie** [comment]
I think on Mac you're actually better off changing `.bashrc`? I forget the details but I recall using `.bash_profile` being an issue for me at some point.

**Comment by cbracken** [comment]
It'd be nice if we provided exact instructions that 'just work'. That gives developers who aren't as comfortable on the shell a means to just copy, paste, and have a working setup. Developers who live in a zen-like communion with their terminals should have no problem making an equivalent change to their setup.

For [Get the Flutter SDK](https://flutter.io/setup/#get-the-flutter-sdk), something like:

The above command sets your `PATH` variable temporarily, for the current terminal window. To avoid this manual step each time you open a terminal window, you can add the following line to a shell configuration file:
```bash
export PATH="~/flutter/bin:$PATH"
```
On macOS or Linux, you can do this as follows:
```bash
echo "export PATH=\"~/flutter/bin:$PATH\"" >> ~/.bashrc
```
On Windows:
```
// TODO
```

**Comment by goderbauer** [comment]
Windows already has a very detailed description of how to do this in [wiki/Flutter-on-Windows](https://github.com/flutter/flutter/wiki/Flutter-on-Windows) (see step 5).

**Comment by LarkAscending** [comment]
The instructions used to be more generic, and the UX team asked for this section to point more specifically to bash_profile because it's usually right on Mac and Linux. See https://github.com/flutter/website/pull/413/commits/b604443ede5b3a5cff51b74a5b2a7239003d7a79 .
 
FTR today we do not say to edit your .bash_profile file. We say "for example,..." which means YMMV.

There's a delicate balance between level of detail and generic enough for all users. Detailed steps are longer, and paradoxically it's likely that users will get lost/frustrated in the content forest. 

How do we fix on an approach? Users who are not comfortable setting up their environment typically need an installer. This may or may not be in the cards, but sometimes the way forward is changing the setup process, rather than adding to/changing documentation.

**Comment by sethladd** [comment]
Agreed, the best long-term fix here is an automated installation process.

**Comment by Romnn** [comment]
I'm still having trouble ..-bash: flutter: command not found.. two days eaten up by flutter installation and flutter claims fast cross platform app development .. its funny

**Comment by Hixie** [comment]
@Romnn Please file a new bug, let's see if we can figure out what the problem is!
