### ISSUE TITLE
Execution failed for task ':app:mergeDebugJavaResource'

### ISSUE THREAD

**Issue by KeemoKimo** [flutter/flutter#87777]
Hello everyone , I m new to flutter and when I run my app I got this problem : 

`Execution failed for task ':app:mergeDebugJavaResource'.
> java.nio.file.FileSystemException: C:\Users\ASUS\Desktop\Programmin\Flutter\app_with_firebase\build\app\intermediates\merged_java_res\debug\out.jar: The process cannot access the file because it is being used by another process. BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1`

Before I imported CloudFirestore into my project, It seem to be working fine. I deleted it once, and did `flutter run`, and it didn't work either.

I also tried `Files > Invalidate Caches/Restart`, but it also did not work.

Any help is appreciated, thanks.

![image](https://user-images.githubusercontent.com/80016602/128465923-d702007a-66a5-4caf-8433-42c6041a9d96.png)
![image](https://user-images.githubusercontent.com/80016602/128465933-bac81869-2fb0-4acc-8edd-2c182f12acd7.png)

**Comment by darshankawar** [comment]
@KeemoKimo 
This could be happening due to absence of `multidexenabled " set to true. Try that and see if it helps.
Also, your issue is better suited for support channels like StackOverflow. So please ask the same there. Check [this](https://stackoverflow.com/questions/57009683/process-cannot-access-the-file-because-it-is-being-used-by-another-process-andr) similar one asked there for your reference.
Closing from here, as this doesn't seem to be an issue in framework.
