### ISSUE TITLE
[cross_file] Using the name specified in the constructor for the file backed by a dart.io File 

### ISSUE THREAD

**Issue by LefebvreIlyas** [flutter/flutter#87808]
## Use case

Hello everyone, 

I use in my application files from Firebase and from the filesystem. And for the files from Firebase I specify as path the download url and the specific name, however the implementation backed by a dart:io File does not take into account the name and returns it as follows: 

```dart 
_file.path.split(Platform.pathSeparator).last;
```

## Proposal

Would it be reasonable to change the implementation to 
```dart
_name ?? _file.path.split(Platform.pathSeparator).last;
```

**Comment by stuartmorgan** [comment]
We should document that `name` is ignored, as we do for `bytes`.

What problem are you trying to solve with your proposal? Why do you want `XFile` to return something other than the filename as the name?

**Comment by LefebvreIlyas** [comment]
I am trying to display the name, but currently it is the last part of the URL that is displayed.

**Comment by stuartmorgan** [comment]
> it is the last part of the URL that is displayed 

What do you mean "the URL"? There's no URL for an IO-backed `XFile`.

**Comment by LefebvreIlyas** [comment]
I specify as path the remote file download url and as name the file name and bytes.

**Comment by stuartmorgan** [comment]
> I specify as path the remote file download url

That's not a file path. Constructing an IO-backed `XFile` with a `path` argument that is not a file path is unsupported; I'm not sure why you are trying to use `XFile` for this in the first place.

We are not going to make behavioral changes for the sole purpose of handling an unsupported use. I'll file a new issue for updating the parameter docs.

**Comment by LefebvreIlyas** [comment]
I use it like this because I have a form in which remote files and files from the file system coexist during editing, and I don't want to create temporary files on the file system for the remote files.

**Comment by stuartmorgan** [comment]
> I use it like this because I have a form in which remote files and files from the file system coexist during editing

`XFile` is, per its docs "a cross-platform, simplified File abstraction"; i.e., it's a variant of `File` that supports web. `XFile`, like `File`, is for representing files within the filesystem.

> Once the form is submitted, thanks to this I know that if the path is a url I must not re-upload it.

As I said above: a URL is not a file path. It may, in your use case, corresponding to a conceptual file, but it is not *a file path*. A file path is a specific concept, and it does not encompass URLs.

> As CrossFile is an abstraction

It's an abstraction file files in the filesystem. It's not an abstraction for any arbitrary conceptual file-like thing that some application may have.

> I find that paths like url:URL or another format is valid.

I explicitly said that it's not valid in an earlier comment, so I'm not sure what that means. If you mean that you are asserting that you can simply pass invalid data into the API and it should work, I'm not sure what to say.

> But if you have a suggestion, I'll take it!

I suggest writing an abstraction that applies to your use case, instead of trying to use `XFile` to represent something that it is not meant to represent by passing it invalid constructor arguments.

**Comment by LefebvreIlyas** [comment]
Thank you very much for taking the time to answer me!

I had a doubt if I could also use CrossFile as a conceptual abstraction, but reading your comment, it's obvious I can't!
