### ISSUE TITLE
Consider allowing raster cache entries to survive 1+ frames without usage

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#87827]
Currently the raster cache clears all entries that have not been used at the end of the frame. In the case of SVGs, this can lead to repeated rendering jank in scenarios like a scrolling list or tabbar view where the same picture (pending flutter_svg fix) is continually re-rasterized as a user interacts with the application.

For especially complex pictures (https://github.com/flutter/flutter/issues/87826), we should support some method of keeping the cache entry alive past one frame. Some ideas:

* We could tune a threshold for lack of access. Probably flaky, risk optimizing for benchmarks.
* We could tie the entry to the lifetime of the engine Picture object. If the picture isn't disposed, then the framework must be keeping it alive intentionally
* We could provide a new API that returned some sort of raster handle that the framework could manage

**Comment by dnfield** [comment]
Since the framework now tells us when pictures are not going to be used again, we should base raster caching decisions on that instead.

**Comment by dnfield** [comment]
Specifcially, we should base eviction decisions on whether the picture has been disposed.  /cc @flar @knopp @chinmaygarde

**Comment by dnfield** [comment]
For this to work, I think we'd want some kind of weak pointer to the SkPicture (or perhaps to the flutter::Picture and the flow::PictureLayer(s) it is part of). Once that is no longer strongly held, the cache entry should be removed.

**Comment by dnfield** [comment]
As I investigate this further, it seems like it should be enough to just keep the raster cache entry around until the `PictureLayer`s holding that picture go out of scope. After calling `ui.Picture.dispose`, the framework will never add it to a new picture layer, and its copy of the layer tree will also be letting go of the engine layers. The engine can't get rid of `PictureLayer` objects before that happens anyway, so they'll always get deleted sometime after `Picture.dispose` anyway (roughly speaking, ignoring possible races). And needing to talk to the RasterCache from the UI thread only further complicates things.

**Comment by dnfield** [comment]
Ok. The reason that is wrong: the framework could potentially hold on to a picture layer even after the current layer tree goes out of scope and reuse it.

**Comment by flar** [comment]
If we had a list of "recently disposed picture unique_id's" then we could use that in our zombie algorithm. Basically, we flush the entry when it is no longer used in a frame and it has either exceeded its N frames of staying power or when we see it on the zombie list. Something like:

```
  if (!entry.used_this_frame) {
    if (zombie_list.contains(entry.unique_id) || entry.unused_count > N) {
      // delete entry
    } else {
      entry.unused_count++;
    }
  }
```

Something else to consider is potentially keeping the entry around, but getting rid of its image. Right now I think we get rid of the entry entirely, which means the next frame we see it, it will have to go through the count-up to caching again from scratch. We might want to keep an entry around (without its image) that was previously cached in case it is useful again and then it will get cached on first reappearance rather than Nth frame of reappearance. The entries don't cost that much, but we don't want our cache to fill up with them as our end-of-frame processing that enumerates them might start to bog down after a while, so some "waiting for it to be used again" limit might be useful, unless we consider that the fact that it wasn't turned into a zombie means there is still the potential for it to come back?

**Comment by chinmaygarde** [comment]
I see there is an ongoing patch to address this. But, I am not sure we have enough evidence to suggest that this is a good idea? I feel like we are jumping into fixing this issue without a more thorough investigation. Perhaps a design doc with empirical evidence based on something that looks the linked patch?

**Comment by dnfield** [comment]
At one point my idea was to expire pictures from the cache when their `.dispose` method had been called in Dart (now that the framework does this appropriately).

However, doing this correctly is pretty complicated and it's not clear if this will be a net win or loss. If we can get an experimental patch to run benchmarks on it would help, but the main caution here is that this is not guaranteed to work: if we regress memory usage too much we won't be able to use it, and there's no guarantee that it will actually improve raster times.

**Comment by jonahwilliams** [comment]
Closing as I don't believe the raster cache is worth working on anymore
