### ISSUE TITLE
Add support for fractional translation

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#88131]
`SUPPORT_FRACTIONAL_TRANSLATION` isn't currently enabled in any targets. Evaluate enabling it or removing the `ifndef`'s altogether.

**Comment by chinmaygarde** [comment]
cc @flar based on our conversation.

**Comment by flar** [comment]
Since it is always used with `#ifndef`, its absence is enabling various sections of code. The fact that it is not defined means there is code in our workspace that is doing something. If you get rid of it the behavior will be changed.

So, this isn't so much as "it isn't defined anywhere" as "should we be supporting fractional translations"?

**Comment by chinmaygarde** [comment]
> its absence is enabling various sections of code. ... If you get rid of it the behavior will be changed.

I meant get rid of `#ifndef` and `#endif`. As you said, its never defined so the code is always enabled.

> "should we be supporting fractional translations"?

According to the code, we already are.

**Comment by flar** [comment]
> > "should we be supporting fractional translations"?
> 
> According to the code, we already are.

Actually, it's the other way around. "SUPPORT FRACTIONAL" is not defined so we don't. The modifications of the matrices are removing the fractional translations so that we don't encounter them...

**Comment by jonahwilliams** [comment]
We removed SUPPORT_FRACTIONAL_TRANSLATION  and instead perform pixel snapping based on the presence of the raster cache. Closing as obsolete
