### ISSUE TITLE
Failed assertion: line 6223 pos 12: 'renderObject.child == child': is not true.

### ISSUE THREAD

**Issue by Hillary-K-Mutai** [flutter/flutter#88266]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by enzodanjour** [comment]
Please, can you send an example of your code?

**Comment by darshankawar** [comment]
@Hillary-K-Mutai 
Whenever you file an issue, please follow the guidelines on how to provide details properly. Please don't put the entire error as an issue title and try to provide all the requested details in the new issue template, so that we can properly address it.

Closing for now since no information is provided.
