### ISSUE TITLE
CustomScrollView not able to disable the scrollbar

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#88345]
Having the following code, I can't disable the scrollbar of the nested `CustomScrollView`. Because of this there are overlapping scrollbars. One for the `NestedScrollView` and the other one for the `CustomScrollView`.

I'm running on the web platform.

The expected behavior is to have only the scrollbar of the `NestedScrollView`.

<details> 
<summary>minimal code example</summary> 

```dart
void main() {
  runApp(
    MaterialApp(
      home: Scrollbar(
        child: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) {
            return [
              SliverToBoxAdapter(
                child: Container(
                  height: 200,
                  color: Colors.red,
                ),
              ),
            ];
          },
          body: CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: Container(
                  height: 1000,
                  color: Colors.green,
                ),
              )
            ],
          ),
        ),
      ),
    ),
  );
}
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/kristian/Documents/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
```

</details>

**Comment by maheshmnj** [comment]
Hi, @KristianBalaj Thanks for filing the issue, This one looks more of a proposal to me than a bug. Since we have nested scrollables here it makes sense to have only one scrollbar for the entire screen.But if the child widget is itself scrollable a default scrollbar is applied and as a result the scrollbars are overlapping.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}


class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool toggleOff = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.light().copyWith(
          scrollbarTheme: ScrollbarThemeData().copyWith(
        thumbColor: MaterialStateProperty.all(Colors.black),
      )),
      title: 'Flutter Demo',
      home: Scrollbar(
        thickness: 20,
        child: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) {
            return [
              SliverToBoxAdapter(
                child: Container(
                  height: 300,
                  color: Colors.red,
                ),
              ),
            ];
          },
          body: CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: Container(
                  height: 1000,
                  color: Colors.green,
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>



https://user-images.githubusercontent.com/31410839/129739981-cb0c6040-e225-4de2-9e7e-44db5bed3472.mov

**Comment by KristianBalaj** [comment]
Okay so when this is not possible to solve currently, then it is a proposal for sure!

**Comment by maheshmnj** [comment]
@KristianBalaj  You can disable the scrollbar using 
```
ScrollConfiguration.of(context).copyWith(scrollbars: false),
```

You can read more about using [the ScrollConfiguration here](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars)

**Comment by gspencergoog** [comment]
cc @Piinks

**Comment by Piinks** [comment]
Hey @KristianBalaj thanks for reporting! 

On desktop (as well as web running on desktop), scrollbars are automatically applied by the `ScrollBehavior`. The `Scrollbar` you have added in your code appears to be overlapping with these automatically applied ones. You can disable the auto-desktop-scrollbars a few ways, [this migration guide](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars) goes into detail on the options for configuring this feature as you like.

Also, for your case with `NestedScrollView`s and `CustomScrollView`s, we anticipated these widgets in particular might like more specific control here (as it relates to the `ScrollBehavior). So for these widgets, you can actually directly supply a `ScrollBehavior` using `NestedScrollView.scrollBehavior` and `CustomScrollView.scrollBehavior`.

Let me know if this helps to resolve your issue, otherwise I believe this is working as intended. Thank you!

**Comment by KristianBalaj** [comment]
Hey! Thanks for the responses.

The `ScrollConfiguration` actually solves the problem, so I'm closing this 🥇
