### ISSUE TITLE
Error in Code in Documentation For 'Migrating Buttons With Custom Overlay Colors'

### ISSUE THREAD

**Issue by Swayam221** [flutter/flutter#88593]
How to reproduce: 
1. Create a new flutter project.
2. Add copy the code for the `TextButton` widget from https://flutter.dev/docs/release/breaking-changes/buttons#migrating-buttons-with-custom-overlay-colors , and it to the body of the default starting application for a new flutter project.

The error: The line `return null` is responsible for the error as the expected return type is a 'Color' .  Shown in line number 31 in the following code snapshot.
![WhatsApp Image 2021-08-20 at 11 16 23 PM](https://user-images.githubusercontent.com/68892315/130277324-f2b1afd1-2b64-4e3b-91b2-6b2ad2666fd2.jpeg)

Proposed Fix: We can change `return null` to `return Colors.transparent`. 
I would like to work on this issue.

**Comment by darshankawar** [comment]
<img width="679" alt="Screenshot 2021-08-23 at 4 17 08 PM" src="https://user-images.githubusercontent.com/67046386/130435378-af29b2b0-30b9-41b7-b1a6-1bf4f9447dd3.png">

Feel free to send the PR with the fix.

**Comment by danagbemava-nc** [comment]
@Swayam221 I would suggest that in your fix, you make the return type null safe, that way it respects whatever styling that the user has put in place instead of setting it to be `Colors.transparent`. See Image below, making it null safe removes the error

<img width="491" alt="Screenshot 2021-08-23 at 11 02 29" src="https://user-images.githubusercontent.com/88313112/130436982-aa2b4d01-dc0d-43a2-8a22-f7ca9697c3c8.png">
