### ISSUE TITLE
Hot reload doesn't complete when android screen is off

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8861]
When I perform a hot reload while the screen of my phone is turned off, hot reload doesn't complete and just sits there spinning. As soon as I turn on my screen and swipe up on the lock screen, hot reload completes.

**Comment by Hixie** [comment]
This is because the reassemble schedules a frame, and the tool waits for the frame to be complete before saying it's done, but frames are deferred if the screen is off. We could be more intelligent about this, though I think on the short term https://github.com/flutter/flutter/issues/8856 might be a simpler fix.

**Comment by goderbauer** [comment]
Makes sense. Would be nice to also tell the user that a turned-off screen might be the reason for the timeout.
