### ISSUE TITLE
Generate and publish API docs for our iOS platform integration

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8867]
Similar to https://docs.flutter.io/javadoc/ but for our iOS platform integration APIs.

Thanks!

**Comment by vlidholt** [comment]
Who needs docs when there is great example code. ;)

<img width="615" alt="screen shot 2017-03-18 at 1 37 41 am" src="https://cloud.githubusercontent.com/assets/1539812/24080698/d61744de-0ca4-11e7-9950-ce7a137b24d9.png">

...but seriously, may be good to add some comments and white space into the example code because it's pretty, um, dense.

**Comment by eseidelGoogle** [comment]
FYI @mit-mit in case this touches anywhere near the current plugin work.  Otherwise I suspect @xster or @cbracken will look eventually. :)

**Comment by sethladd** [comment]
Duped by https://github.com/flutter/flutter/issues/2100

**Comment by sethladd** [comment]
Assigning to @mit-mit to help drive this to completion.

**Comment by eseidelGoogle** [comment]
Is this still on target for M2 (this Friday)?

**Comment by mit-mit** [comment]
It is not. But I also don't think this is crucial. We have documented the APIs on flutter.io.

Punting to milestone 3.

**Comment by szakarias** [comment]
Done in #10905
