### ISSUE TITLE
[windows] Pressing Right-Shift turns on caps lock and locks in a TextField #75675 reopened

### ISSUE THREAD

**Issue by Dampfwalze** [flutter/flutter#88695]
https://github.com/flutter/flutter/issues/75675
This issue is still not resolved and should not be closed!

I am on stable channel and had I this issue anyway

**Summary:**
When you use right shift once, it will be held by flutter, until you press left shift

**Reproduce:**
Just try it with any TextField

**flutter doctor:**
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale de-DE)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[X] Android toolchain ...
[!] Android Studio ...
[√] Chrome ...

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.1)
    • Visual Studio Enterprise 2019 version 16.11.31613.86
    • Windows 10 SDK version 10.0.19041.0

[√] VS Code (version 1.59.1)
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • ...
```
Please just fix it!

**Comment by TahaTesser** [comment]
Hi @Dampfwalze 
This has been fixed, you're on stable, the fix is currently in the beta channel, you can either upgrade to beta or wait for the new stable release 


Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`


Closing as duplicate. If you disagree, please write in the comments and I will reopen it.
Thank you
