### ISSUE TITLE
SelectableText doesn't show `selectAll` on popup menu on iOS

### ISSUE THREAD

**Issue by lroige** [flutter/flutter#88710]
This issue is a duplicate of #83700. 

When using SelectableText in mobile apps, the default options for the tooltip when selecting part of the text according to documentation are `copy` and `select all`. When using this widget in Android devices this is correct, but when using it on iOS devices only the 'copy' option appears even when setting it explicitly with tooltipOptions. The desired behaviour would be that the `select all` option appeared along with `copy` when long tapping a section of the text (as happens in native apps such as Notes in an iPhone 11 with iOS 14.6).

Here is a minimal code example with this behaviour:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: SelectableTest(),
    );
  }
}

class SelectableTest extends StatelessWidget {
  const SelectableTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        alignment: Alignment.center,
        child: SelectableText(
          'This is a selectable text',
        ),
      ),
    );
  }
}
```
This is the selected text in an Android device:

![image](https://user-images.githubusercontent.com/25765708/130469894-a1adf2f3-3588-477d-a8e3-1d4e2811df48.png)

And in an iOS device:

![image](https://user-images.githubusercontent.com/25765708/130469747-80921058-a2da-40fd-8188-e2fc2ed1e1c5.png)

Here is my flutter doctor result:
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)
```

**Comment by TahaTesser** [comment]
Hi @lroige 
You're comparing the behavior with Android when the behavior for iOS

As commented [here](https://github.com/flutter/flutter/issues/83700#issuecomment-867200582), in order to get `selectAll` in native iOS, you need to have collapse tool selection, selecting a word won't provide this option

### Native Notes App


https://user-images.githubusercontent.com/48603081/130598187-140c800d-8701-43c2-93ee-3ac64a23bc65.MP4


When it comes to Flutter, you can't have collapsed text selection on `SelectableText`, it will only select a word that gives the `selectAll` (matches native behavior). You observe this behavior where it is possible to have collapsed text selection such as `TextField` 


https://user-images.githubusercontent.com/48603081/130598432-d62c5ae7-9da8-4c3a-ae1d-0bc77cb22131.MP4



Hope this clears it 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
