### ISSUE TITLE
Request: disable 'used by' in github.com/flutter/flutter

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#88809]
People are starting to abuse that so their repo is promoted on Flutter main page:
![image](https://user-images.githubusercontent.com/351125/130677098-08f8867c-5c31-4cf3-ad97-5e5cafba61d2.png)

Since GitHub doesn't support Dart dependencies (yet), they are making a fake go dependency. I would also personally probably re-enable the Releases section, I miss that.

**Comment by stuartmorgan** [comment]
Can you link to documentation describing how to disable that section? I don't see any, and while I'm not an admin for this repo the only relevant-sounding setting I can find in a repo that I am an admin for is disabled for public repositories.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan I might have bad news here. The relevant setting **should** be here:

![image](https://user-images.githubusercontent.com/19204050/132610213-60037293-92a2-4dc2-b3b5-acc3d1dcccf3.png)

However, I only see options to disable:

![image](https://user-images.githubusercontent.com/19204050/132610259-ca489ae6-e6ba-46d4-b461-cdca2c3c0634.png)

* Releases
* Packages
* Environments

---

It might be because I am checking the fork but it might be that there is no toggle for "Used by" yet. We might want to reach out to GitHub for this abuse.

**Comment by bernaferrari** [comment]
Lol, you were fast. I took the screenshot and it was already here.

**Comment by stuartmorgan** [comment]
Closing as infeasible.
