### ISSUE TITLE
(potentially) inconsistent Android emulator setup instructions

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8893]
From an email: "Trying to create an emulator with Android Studio. Your instructions say to use Tools > Android > AVD Manager. But, there is no Android sub-menu in the Tools menu. (Actually, the only way I could get a Tools menu was by creating a vestigial Android project.) The Tools sub-menu items are, 1) Tasks & Contexts, 2) New Scratch File..., 3) IDE Scripting Console and 4) Create Command-line Launcher...."

(I haven't confirmed this yet, but wanted to track it)

**Comment by LarkAscending** [comment]
![image](https://cloud.githubusercontent.com/assets/23464935/24278139/2944e492-0fff-11e7-995a-a44254c010bc.png)


Everything has been tested :-) 

There's apparently a delay after installing before users can see the Tools option in the Android Studio menu. This is documented in a comment on an in-progress PR. 
@mit-mit 

In the first pass at setup.md, we also gave instructions for how to access AVD Manager from SDK Manager. After PR feedback we removed them because it seemed like duplicate info. Also, the most recent version of SDK Manager doesn't have this option. Finally, the AVD manager tool itself looks completely different (field names and options are different, etc.) when accessed this way vs. from the Tools menu.

Seems like Android Studio is in flux here. This workflow looks like the new workflow. Maybe we should sync up w/our Android Studio friends?

**Comment by mit-mit** [comment]
The `Tools->Android->AVD Manager` has been, and is, the main flow.

BUT: The super confusing thing -- which we should document -- is that this menu item does not appear in Android Studio unless you either open an existing android project or create a new one, and then wait until gradle is done building it.

**Comment by LarkAscending** [comment]
Instead of documenting (which is problematic b/c 1. users won't read it and 2. the Android Studio behavior might change), have we looked at filing an issue w/Android Studio?

**Comment by eseidelGoogle** [comment]
I'm not sure how to triage this bug.  I suspect getting Android Studio fixed in any short amount of time is not going to happen.

We can also launch avdmanager from the command line:
`~/Library/Android/sdk/tools/android avd`

Supposedly the fancy new AVD manager is built into Android Studio and can't be launched directly from the command line:
http://stackoverflow.com/questions/36739658/possible-to-open-the-newer-slicker-avd-manager-window-from-the-command-line

**Comment by LarkAscending** [comment]
Checking in w/the PM for Android Studio:

> We don't encourage running the Android Emulator standalone without Android Studio, and typically Android Studio needs to open a project, so this is WAI. Now if we want to run the AVD Manager like we do the SDK Manager from the Welcome Screen...it is technically possible but it would be a new feature for us to work on. 

The way Flutter uses the Emulator isn't viewed as a primary use case. There seems to be a way forward if we make a new feature request for AVD Manager to be an option from the Welcome Screen. This seems simple, and it would definitely solve the documentation conundrum.

Who would like to file the feature request?

**Comment by LarkAscending** [comment]
Update - a search for existing issues in the AOSP turned up this:
[AVD manager can't be started from the welcome screen](https://code.google.com/p/android/issues/detail?id=192756)

It's been open for ~18 months...FWIW I upvoted it. Someone else can probably find a more effective approach, though.

**Comment by mit-mit** [comment]
@pq is investigating improvements to Android emulator setup.

**Comment by Hixie** [comment]
What was the conclusion? Do we still need to update the docs? Are we happy as-is?

**Comment by LarkAscending** [comment]
We standardized on the Tools menu workflow over the Welcome screen flow. There was some AS churn during this time with SDK Manager, and the Tools workflow was preferred (it opened the newer SDK Manager). Since then, the command line avdmanager and sdkmanager tools have been added.

The AS documentation only mentions the Welcome screen as a workaround "if you don't have a project open, you can create one from here". It does not say (or hint) that you need to go through creating a project in order to get the Tools menu to populate. We do know that there's a delay in populating this menu, as Gradle needs to build stuff...including (as it turns out) maybe AVD Manager. 

AVD Manager can't be started from the Welcome screen and this is starting to look like it might be a functional limitation of AS. AVD Manager is an (installed) Android Support Plugin but the only way to access it without creating a project looks to be [the command line](https://developer.android.com/studio/command-line/avdmanager.html). 

Question -  is it always necessary to create an AS project in order to get the Tools menu? Or is this issue about the known delay?

Doc recommendation:
* Use Tools menu workflow for accessing SDK Manager and AVD Manager, and be consistent everywhere with it.
* Tell IntelliJ users if they don't have an AS project anywhere, they can use the command line to configure an AVD. Just link to the AS documentation, once. Don't replicate the instructions. 
* Tell AS users If you're developing a Flutter app in AS, install the Flutter plugin from the Welcome screen in studio, then create a new Flutter app from the Welcome screen. This starts AS and there's no need to `flutter create` at the command line.

From the above, it looks like it's time to fork the Getting Started steps for command line vs. IntelliJ vs. AS.

Any feedback, positive or negative, on this?

**Comment by pq** [comment]
cc @stevemessick @devoncarew

**Comment by mit-mit** [comment]
Overall looks good. 

I suspect lots of users in the middle bullet will struggle with creating AVD from the terminal, but I think there is no good docs fix for that, but rather we would need a product fix to actually automate the step of creating the emulator.

**Comment by stevemessick** [comment]
I think the suggestion to fork Getting Started is sound. However, it IS possible for the Flutter plugin to modify the Welcome screen (such as adding the option to create a Flutter project in Android Studio). I have no idea how much work would be involved but if it would significantly improve the UX we could look into it. Configuring an emulator with AVD is perhaps not what we want new users to focus on, though. (Hopefully they can just plug their phone into the computer instead -- that's what I did until today.)

**Comment by mit-mit** [comment]
I logged https://github.com/flutter/flutter/issues/13379 to track product support for creating the AVD

**Comment by Sfshaza** [comment]
In PR https://github.com/flutter/website/pull/1062, I added a note to the getting started page for Android Studio, that the submenu is only present when inside an Android project. Is this sufficient? Can I close this?

**Comment by Sfshaza** [comment]
Forgot to include @mit-mit, please weigh in.

**Comment by mit-mit** [comment]
Yup, I believe so

**Comment by Sfshaza** [comment]
Thanks, Mit. Closing.
