### ISSUE TITLE
Document opinions for customizing our widgets

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8898]
A big value-add of Flutter is our customization options for existing widgets. We believe designers should be able to envision beyond stock design languages, and our developers should be able to implement the vision without too much trouble.

As such, we could help our developers by authoring opinionated options for customized widgets. When developers want to go beyond the stock widgets, what do they do? What do we think will work best? What are the options?

This initial document doesn't have to be exhaustive or even a cookbook, but we want to point our developers in the right direction.

**Comment by sethladd** [comment]
I'm a fan of "something rather than nothing" here, so don't feel like you need to go super deep or super wide for this initial article. If you're interested in taking a crack at this, consider something 1-2 pages, with general advice, justifications, and a few examples, with a tone of "but we're still learning here. discussion welcome!"

So, with that, if you're interested in writing a bit here to guide our early developers, we'll help edit.

Thanks in advance!

**Comment by abarth** [comment]
# Customizing widgets

Rather than having each widget provide a large number of parameters, Flutter embraces composition.  Widgets are built out of smaller widgets that you can reuse and combine in novel ways to make custom widgets.  For example, rather than subclassing a generic button widget, `RaisedButton` combines a `Material` widget with a `GestureDetector` widget.  The `Material` widget provides the visual design and the `GestureDetector` widget provides the interaction design.

To create a button with a custom visual design, you can combine widgets that implement your visual design with a `GestureDetector`, which provides the interaction design.  For example, `CupertinoButton` follows this approach and combines a `GestureDetector` with several other widgets that implement its visual design.

Composition gives you maximum control over the visual and interaction design of your widgets while also allowing a large amount of code reuse.  In the framework, we've decomposed complex widgets to pieces that separately implement the visual, interaction, and motion design.  You can remix these widgets however you like to make your own custom widgets that have full range of expression.

**Comment by sethladd** [comment]
Thanks! Added to the FAQ
