### ISSUE TITLE
Don't include the observatory UI in skyshell's binary

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#890]
Right now a big chunk (multiple megabytes) of Flutter's binary is the debugger UI. We should take that out of the binary, and provide a separate way to connect to a Flutter app (e.g. have observatory hosted somewhere, maybe https://debugger.flutter.io/ or something).

**Comment by abarth** [comment]
The steps here are roughly:
- [ ] Instead of linking the observatory assets into the binary, include the observatory_assets.tar file in the APK and mmap it at runtime.  We already get a callback from DartVM when it needs the resources.  We just need to wire in the path and use mmap instead of getting the data from a linker symbol.
- [ ] For end-developer APKs (e.g., produced with `flutter apk`), make the observatory_assets.tar file optional.
- [ ] As part of the previous step, we'll have to include observatory_assets.tar in the artifacts.zip file we upload to Google storage.  Make it possible to use observatory using that observatory_assets.tar even if the APK doesn't include observatory_assets.tar.

**Comment by Hixie** [comment]
That's a reasonable set of steps. I think we should also consider just hosting the assets elsewhere, and making the observatory protocol stable. Then you would launch the debugger by just going to the observatory Web site (or launching an app on your favorite platform).

**Comment by Hixie** [comment]
In particular, we need that if we want to enable debugging deployed release builds (since they wouldn't have the assets).

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/76

**Comment by eseidelGoogle** [comment]
We now only include the observatory in --debug and --profile builds.  Is that sufficient for this bug or do we also need to remove the UI from debug/profile?

**Comment by abarth** [comment]
This bug is only about removing it from production builds.
