### ISSUE TITLE
No-response bot isn't closing issues

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#89057]
The new incarnation of the no-response bot is doing the remove-label-on-response part correctly, but is never closing stale bugs that have the label despite the config saying that it should be doing so after 21 days. (At the time of writing, there are bugs that are 30 days stale, and the triagers have reported that they've been having to do manual sweeps regularly because it never works.)

I see recent scheduled jobs for the bot on the Actions tab, which is the run that is supposed to do this step, and it claims to have run successfully, but there's no useful output about what it did (which seems to be nothing).

/cc @godofredoc

**Comment by godofredoc** [comment]
This is actually a bug in the action:

This is the query it is executing: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22waiting+for+customer+response%22+sort%3Aupdated-desc+

And it is processing the first 30 bugs from the list only, which are the most recently updated and the oldest ones are never processed.

Seems like the fix is to just use `order: updated-asc` which will process the bugs with the oldest updates first. This is the line of code to change:

https://github.com/lee-dohm/no-response/blob/1ae4f8bbc8a4607bb904abc1f5f7556ea2ace95b/src/no-response.ts#L136

**Comment by stuartmorgan** [comment]
I sent a PR since the issue hasn't gotten a response. If that doesn't work, we could consider making a flutter-org fork of the action's repo and using that.

**Comment by godofredoc** [comment]
Thanks @stuartmorgan

**Comment by godofredoc** [comment]
@stuartmorgan did you PR got reviewed?

**Comment by stuartmorgan** [comment]
No; I pinged again a few days ago, but still no response. There's very little activity in the repo, so it's unclear if it will eventually get noticed or not. We should probably move forward with forking.

**Comment by stuartmorgan** [comment]
🎉 It landed upstream!

@godofredoc Can we get the latest version (currently caff5e7de24d19659c31dda1ff2520a3f6a88370) whitelisted and rolled out?

**Comment by godofredoc** [comment]
This is great, news. Added the new version to the allow list!

**Comment by stuartmorgan** [comment]
Currently blocked on https://github.com/lee-dohm/no-response/issues/211

**Comment by stuartmorgan** [comment]
@godofredoc Should we close this, or leave it open to track moving off the fork once upstream publishes?

**Comment by godofredoc** [comment]
Let's close this one and keep the one with the fork request open.
