### ISSUE TITLE
Leave issues unlocked by default

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#89141]
Users often find closed issues via search engines.  Therefore closed issues are useful places to consult with other users on errors and workarounds.

Workarounds and error messages change over time. When issues are unlocked, users will add comments like:
- "The error message now looks like: ..."
- "The fix now requires change X"
- "This new command worked for me ..."
- "X is a better version of this thing that avoids these problems."

Locking prevents this sharing.  Automatic locking prevents this sharing on all issues.

Automatic locking also generates spam for everyone who contributes or subscribes to issues.

What is the main reason for automatically locking closed issues?  Is it because Google Flutter Team spends time reviewing comments on closed issues to see if issues need to be re-opened and wishes to reduce this work?  If that is the main reason, please consider some alternatives:
- Whenever someone closes an issue, have a bot automatically post a message saying "The maintainers ignore closed issues.  If you need to re-open this issue, please file a new issue asking to re-open it."
- Allow users to re-open issues themselves
- Add a `please-re-open` label and allow users to add it to closed issues to flag them for review

**Comment by adamhill** [comment]
Yes! Please quit auto-locking issues to juice the metrics.

**Comment by Hixie** [comment]
Nobody is watching closed issues. That's why we lock them. Just file a new issue.

There's no "juicing of metrics" (what metric would we even be juicing? total bugs? that seems like the opposite of what we'd want lol), and the locking process is [documented on our wiki](https://github.com/flutter/flutter/wiki/Issue%20Hygiene#locking-an-issue).

@adamhill Please consider how your comments might be interpreted by contributors. Our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) requires actively welcoming behaviour, accusing people of "juicing metrics" is not that.

**Comment by mleonhard** [comment]
> An issue is generally not closed by adding an error message.

Sorry for not being clear.  I meant that users will update old closed issues with new error messages.

> It would be helpful if you could provide as many specific examples as possible of a comment on a closed issue that would be (or was) useful.

> Nobody is watching closed issues. That's why we lock them. Just file a new issue.

> Hixie closed this 2 hours ago

You closed the issue and now you and other Flutter Team members will not see any replies.   You will not see any specific examples that I add later, which you ask for.  You will not see comments from other Flutter users.  I was hoping we could have a dialog but you cut it off. :(

**Comment by stuartmorgan** [comment]
> Sorry for not being clear. I meant that users will update old closed issues with new error messages.

If the error message is different, the actual issue is probably different as well. My (decades of, across several very large open-source projects) experience with people "updating" old, resolved bugs with new error message is that it is essentially always actually a different issue that they have conflated with one that they found. As I said above, people are generally not good at making these determinations.

> You closed the issue and now you and other Flutter Team members will not see any replies. You will not see any specific examples that I add later, which you ask for.

Hixie and I are not the same person.

I asked for examples because I thought they might be helpful and there was no chance that this request would go anywhere without specifics. It's ultimately Hixie's decision, however, and he clearly has a different opinion of whether they could potentially be persuasive.

If you want to post specific examples (I generally see notifications for issues I'm subscribed to, so should notice comments here), I'm happy to ensure that our docs about issues provide guidance on alternate approaches for the use cases you describe (along the lines of https://github.com/flutter/flutter/wiki/Issue-hygiene#comments-providing-workarounds which I suspect would apply to several of the general category of comment you referred to in your list).

**Comment by stuartmorgan** [comment]
> I was hoping we could have a dialog but you cut it off. :(

Also, see https://github.com/flutter/flutter/wiki/Issue-hygiene#issues-are-not-a-venue-for-discussions

We explicitly document that this is not a good place for discussions.

**Comment by Hixie** [comment]
> You will not see comments from other Flutter users.

I will, since I'm still subscribed to this (for now, anyway). But as Stuart says, if what you're after here is a discussion of our processes, then the Discord server is a better place for that. Please see our contributing guide for the invite link. I'd be more than happy to talk with you at length about our processes and how we can improve them!
