### ISSUE TITLE
Report an error about flutter startup failure

### ISSUE THREAD

**Issue by luchuqiang** [flutter/flutter#89200]
I recently took over a project. The original project was created and developed on the mac, but now it is developed on the window system. The flutter environment is well configured, and an error will be reported when starting the project. Ask the expert to help you see what's going on. My flutter.bat program crashes as soon as it runs, I don’t know if it’s the reason.
![cmd](https://user-images.githubusercontent.com/58058283/131438533-0aeca00b-d80f-4550-924e-0da3ad0b8569.png)
![err](https://user-images.githubusercontent.com/58058283/131438534-0f0833be-8eff-482d-beb1-c34d5df3c33f.png)

**Comment by darshankawar** [comment]
@luchuqiang 
Looking at the console log, it seems to indicate that issue is with the code implementation, example `GeneratedInt` isn't a type, so there's name and type mismatch going on and also seems to be pointing to 3rd party plugin, https://pub.dev/packages/dio_cache_interceptor

I suggest you to ask this question in dedicated plugin's repo or in support channels like StackOverflow.
Closing from here as this isn't a Flutter issue.
