### ISSUE TITLE
macOS desktop application TextField does not respond to the delete button of the physical keyboard

### ISSUE THREAD

**Issue by a02683418** [flutter/flutter#89222]
</details>
flutter version is  2.2.3
my mac application Suddenly does not respond to the delete button of the physical keyboard, what wrong

**Comment by darshankawar** [comment]
@a02683418 
I tried below code sample using stable 2.2.3 on macOS desktop and didn't see any issue deleting:

```
body: Center(
          child: TextField(
            decoration: InputDecoration(
                hintText: 'enter here'
            ),
          ),
```
https://user-images.githubusercontent.com/67046386/131627791-495d65e3-4ea4-43fe-b795-bab02932de93.mov


If above doesn't represent your use case and issue, please provide a complete code sample so that we can properly address this issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
