### ISSUE TITLE
[desktop] Multiline TextFields should be submittable with the keyboard

### ISSUE THREAD

**Issue by jaysephjw** [flutter/flutter#89446]
**When `maxLines` is specified, there seems to be no way to trigger `onSubmitted` with the keyboard (or at all?).**

It is common throughout the web to provide a way to submit a multiline text field: 
* `ctrl+enter` submits multiline posts and comments on sites such as Github (creating this issue), Reddit, and Gmail
* `enter` submits chat messages on Slack by default, with ctrl or shift modifiers creating newlines 

Based on my cursory research I would recommend making `ctrl+enter` submit multiline fields, as this seems to be the dominant pattern. 

```void main() {
  runApp(MaterialApp(
    home: Material(child: TextField(
      maxLines: 2,
      onSubmitted: (_) => debugPrint('Submitted!'),
    ))
  ));
}
```

**Comment by jaysephjw** [comment]
@TahaTesser sorry I did not see your question in https://github.com/flutter/flutter/issues/86838` ; I have recreated the issue and added more information!

**Comment by TahaTesser** [comment]
Hi @jaysephjw 
Thanks for the details, Indeed, some platforms allow such shortcuts to trigger submission. 
I can see on Flutter desktop or web, it doesn't work

**Comment by jaysephjw** [comment]
I think this also applies to Web.

To work around for now, I'll look into wrapping with a RawKeyboardListener.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
@jaysephjw To work around this you can use a Shortcuts widget similar to [this example](https://master-api.flutter.dev/flutter/widgets/DefaultTextEditingShortcuts-class.html) in the docs.

I'm leaning towards saying that text fields should not submit with ctrl+enter by default, and users should implement this behavior themselves using Shortcuts.  I tried out a `textarea` on the web, and it doesn't submit its `form` by default with ctrl+enter.  Maybe we can add an example of how to do this with Shortcuts somewhere.

The current behavior actually comes from the engine, via [performActions in EditableText](https://github.com/flutter/flutter/blob/24207183899d546983873dd6d6e3b80a2825a982/packages/flutter/lib/src/widgets/editable_text.dart#L1855).  For GLFW for example, we receive the enter key and send a newline action [here](https://github.com/flutter/engine/blob/f8389fc18745dd9098a9862195e024fcf26270ea/shell/platform/glfw/text_input_plugin.cc#L91).  We could send a submit action instead of cmd/ctrl is down if we wanted to, but I don't think this is the default behavior on native, and users that don't want this behavior may have a harder time.

@stuartmorgan Do you have an opinion on this?

**Comment by stuartmorgan** [comment]
I would expect the default to match whatever the native app default is for each platform.

**Comment by jaysephjw** [comment]
@justinmc perfect- tried and Shortcuts is working excellently.

I did a re-test of current behavior for me on Chrome:

Multiline TextField 
- shift+enter: adds a newline.
- enter: plays inksplash, does not call onSubmitted.

Multiline TextFormField
- shift+enter: adds a newline.
- enter: add a new line, does not call onFieldSubmitted.

**Comment by justinmc** [comment]
Sounds good. I also checked on a native SwiftUI app on Mac and it seems like a multiline text field (`TextEditor` in SwiftUI) doesn't handle cmd+enter by default.

**Comment by justinmc** [comment]
I'll go ahead and close this with the recommendation that users achieve this using Shortcuts as mentioned [above](https://github.com/flutter/flutter/issues/89446#issuecomment-920230183).  If anyone has firsthand experience with Linux/Windows and thinks they should support ctrl+enter by default, please chime in or open a new issue.

**Comment by jaysephjw** [comment]
@justinmc Perhaps it should be at least an error to include onSubmit with a multiline input on these platforms, if the code is not reachable?

**Comment by justinmc** [comment]
@jaysephjw Good point, at least maybe we should document it.

Are we sure that it's not reachable though?  [Here](https://github.com/flutter/flutter/blob/a921c1cf3d2616704bcbb83ab13d89e39be0c97c/packages/flutter/lib/src/widgets/editable_text.dart#L2011) is where it's called.  I'm not sure how to hit that in a multiline field but maybe there is a way...
