### ISSUE TITLE
How can I force start  the Flutter application when has a red error in the IDEA compiler?

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#89506]
What I mean is that under normal circumstances, when starting the flutter application, the compiler will first check whether there is an error in the file (the red wavy line). If there is an error, the flutter application cannot be started. But the wrong code is not quoted in the code. How to force the flutter application to start?

**Comment by maheshmnj** [comment]
@ddxl123 I am not sure why would you want to run a project which has syntax errors. But you could force the IDE to run the application as long as your `main.dart` does not reference the file which has syntax errors.

e.g let's say your project has three files 
```
lib/
    - main.dart
    - hello.dart
    - world.dart
```
There is a syntax error in `hello.dart` then your main.dart should not reference `hello.dart` that means it should not be depending on `hello.dart` in anyway .

 Since this issue does not seem to describe a bug or a feature request, Closing this issue as invalid if you disagree feel free to write in the comments and I will reopen it.
 
 
 Thank you.
