### ISSUE TITLE
Linux flutter_plugins broken on unrelated commit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89517]
The "Linux flutter_plugins" job is red on the commit https://github.com/flutter/flutter/commit/33755f203dfeae491f586a73abdf4e400749f32a, which appears unrelated.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_plugins/3301/overview

The commit from the plugins repo here looks related: https://github.com/flutter/plugins/pull/4288

But my revert PR is failing on the same analysis errors as seen in the framework tree: https://github.com/flutter/plugins/pull/4314

Additionally the `flutter/plugins` repo should be configured to allow reverts to be landed TBR.

@cyanglaz @stuartmorgan @godofredoc

**Comment by stuartmorgan** [comment]
Yes, that commit is seriously broken. It'll be a mess because that was published as well :(

**Comment by zanderso** [comment]
@stuartmorgan You seem to know what needs to be done for this, so I'm assigning you, but that is not intended to communicate that there's any expectation of working on it over the long weekend.

**Comment by stuartmorgan** [comment]
Re-running flutter/flutter tests *should* pass now.

Athough now that I think about it, we may have to force a plugins roll into flutter/flutter for the same reason that I had to force-land the revert.

**Comment by stuartmorgan** [comment]
For posterity, the issue here was:
- The original PR made a breaking change to the platform interface—adding params to existing methods breaks subclasses, whether there is a default value or not—but did not change the version accordingly.
  - This was caught by CI it seems, but there was a misunderstanding about what was happening by the reviewer, AFAICT from the conversation there.
  - That CI failure was, incorrectly, bypassed by changing another package in the the same PR.
    - This change *did not include a version change*, so would not be published, which will become important later.
  - That was supposed to be reverted according to review discussion (which would, correctly, have failed CI again) but wasn't. The reviewer apparently didn't notice that that part wasn't reverted, and landed it.
- Because the breakage happens when someone uses an old implementation (`..._web` in this case) with the new interface, but that doesn't happen in CI, it passed post-submit and was auto-published.
- At this point, anything that uses the latest versions of all of the `image_picker_*` packages will fail to build, because `_web` wasn't published.
  - If the PR had changed the version of `_web`, this would still have been pretty bad, but we wouldn't have noticed as quickly (and it wouldn't have broken flutter/flutter); an older version of the interface and newer version of web, or vice versa, would have been broken (which pub can't prevent because there was no breaking change indication in the versioning), but having the newest version of both would have worked.

I have filed https://github.com/flutter/flutter/issues/89518 to try to prevent this from happening again.
