### ISSUE TITLE
Till when should we provide support for Embedding V1 using deprecated registerWith function?

### ISSUE THREAD

**Issue by juliansteenbakker** [flutter/flutter#89730]
It has been a while since Embedding v2 has been released. Right now my production application gets bombarded with deprecation warnings because a lot of plugins still have the registerWith class which has the deprecated `io.flutter.plugin.common.PluginRegistry.Registrar` parameter.

I'm a plugin developer and migrated all my plugins to null-safety. Does it even make sense to have the registerWith class when the plugin is null-safety?

**Comment by TahaTesser** [comment]
Hi @juliansteenbakker 
Since this is a question for the team, rather than a bug, I would suggest to join Flutter [Discord](https://github.com/flutter/flutter/wiki/Chat) and ask this question there

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
