### ISSUE TITLE
Cocoon and milo dashboards show framework tree is green, but PRs are blocked

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89758]
The check on PRs is blocking things from landing even though everywhere I can check it looks like the trees are green.

**Comment by keyonghan** [comment]
Switched cocoon to an earlier version.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/17400 removed the `staging` suffix from builders in `staging` pool, which means both `staging` and `prod` are sharing the same builder name.

This results in `staging` and `prod` key words appended in `scheduler_job_id` (flutter/prod-Mac_android drive_perf_debug_warning, or flutter/staging-Mac_android drive_perf_debug_warning), which we use to search buildbucket APIs for GitHub PR status. On the other hand, if a rerun is triggered, [cocoon](https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/service/luci_build_service.dart#L471) is not appending `prod`, so that we are using both  `flutter/prod-Mac_android drive_perf_debug_warning` and `flutter/Mac_android drive_perf_debug_warning` to calculate the status. This causes the issue here: `flutter/prod-Mac_android drive_perf_debug_warning` ones return green whereas `flutter/Mac_android drive_perf_debug_warning` return red, so the overall status is `red`. 

Frontend build dashboard status is based on datastore top tasks, which here reflects the correct status with `green`.
However status in GitHub is based on real-time LUCI buildbucket API search, which hit the issue above.

**Comment by keyonghan** [comment]
Switching cocoon back to the earlier version is using `flutter/Mac_android drive_perf_debug_warning` only. However, some tests on the earlier commit retry failed.

@zanderso is there any PR ready to submit to green the tree?

**Comment by keyonghan** [comment]
Manually submit https://github.com/flutter/flutter/pull/89700 to unblock.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/17941 to restore staging suffix back.
From backend log, cocoon is refreshing GitHub with correct status. Will keep this open for a couple of commits.

**Comment by keyonghan** [comment]
Verified the problem is solved.
