### ISSUE TITLE
flutter_plugins analyze fails with ProcessException: fatal: Not a valid object name FETCH_HEAD

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#89805]
```
$ SHARD=flutter_plugins SUBSHARD=analyze  dart dev/bots/test.dart
Fetching dependencies...
--packages-for-branch: running on changed packages
Unhandled exception:
ProcessException: fatal: Not a valid object name FETCH_HEAD
  Command: git merge-base FETCH_HEAD HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
#2      GitVersionFinder.getBaseSha (package:flutter_plugin_tools/src/common/git_version_finder.dart:77:30)
<asynchronous suspension>
#3      PluginCommand._getAllPackages (package:flutter_plugin_tools/src/common/plugin_command.dart:317:30)
<asynchronous suspension>
#4      Stream.toList.<anonymous closure> (dart:async/stream.dart)
<asynchronous suspension>
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836524695632600385/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

**Comment by jmagman** [comment]
Turned the test off, reducing priority.

**Comment by stuartmorgan** [comment]
I suspect this was an infrastructure change since I don't think we've changed anything about how we are using FETCH_HEAD recently (I thought this might be due to my recent refactoring, but I don't think that should have changed this). But it's probably better to just always do the full analysis re-run when rolling into flutter/flutter rather than doing the PR-style incremental run anyway, so I'll re-write the test.

**Comment by stuartmorgan** [comment]
(Although my refactor is in that delta, so maybe I'm missing a side-effect.)

**Comment by stuartmorgan** [comment]
Oh, it was me. I missed that
`BRANCH_NAME="${BRANCH_NAME:-"$(git rev-parse --abbrev-ref HEAD)"}"`
(which I removed) was using an existing `BRANCH_NAME` if it was already set. Which our CI never does, but flutter/flutter did.

I still think moving off of tool_runner.sh is the better option though, since having external uses of tool_runner,sh that don't match the repo uses is, as demonstrated by my mistake, fragile.
