### ISSUE TITLE
flutter_lints > Are comments being stripped from the docs?

### ISSUE THREAD

**Issue by oodavid** [flutter/flutter#89873]
In this rule, the **BAD** and **GOOD** examples are identical. Looking at the initial statement, it appears that the rule is related to comments. Are they being stripped from the sources?

https://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html

**Comment by oodavid** [comment]
It appears not. Looks like incomplete docs:

https://github.com/dart-lang/linter/blob/05c3b01d9cbb336dba0c928a202fd6815b3c4ce2/lib/src/rules/avoid_renaming_method_parameters.dart

**Comment by stuartmorgan** [comment]
> In this rule, the **BAD** and **GOOD** examples are identical.

They aren't identical; in the BAD example, `B` is changing the name of the parameter of `m(...)` from `a` to `b`. Which is exactly the thing that the lint is saying not to do.

> Looking at the initial statement, it appears that the rule is related to comments.

The *motivation* for the rule is about the effect on comments. The rule is about method parameters.

**Comment by stuartmorgan** [comment]
Issues with specific lints (rather than their inclusion in the Flutter defaults) need to be reported to https://github.com/dart-lang/linter/issues

(In this case, renaming the example variables to something other than single letters so that the difference is not so hard to see seems like a good request to file there.)
