### ISSUE TITLE
GC threads should be lower priority than the UI/rasterizing threads

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#89884]
Based on discussions in https://github.com/flutter/flutter/issues/74668, https://github.com/flutter/flutter/issues/72387, and https://github.com/flutter/flutter/issues/70636 it seems like we should consider the following design:

GC threads should be lower priority that the UI and rasterization threads while those threads are pushing a frame.
The UI and rasterization threads should be lower priority than the GC threads while they are not pushing a frame.

Maybe after a second or two of the UI and rasterization threads being continually higher priority than the GC threads (i.e. when the rendering is just using up all the CPU) then we can give up and just let them have the same priority.

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by a-siva** [comment]
I presume this needs https://github.com/dart-lang/sdk/issues/44209 to be fixed so the Flutter side can use the flag.

**Comment by zanderso** [comment]
There is also relevant discussion of this problem at https://github.com/flutter/engine/pull/22512 and https://github.com/dart-lang/sdk/issues/44228.

**Comment by chinmaygarde** [comment]
I could find no cohesive direction in the various threads linked here.

Currently, we cannot modify the priorities of threads after they have launched (which is what the [issue Siva linked](https://github.com/dart-lang/sdk/issues/44209) gives us). We could also make the VM give the engine a change to run (or defer) certain tasks based on its own heuristics. I don't think this is being tracked anywhere though. Another way approach is just to leave the priorities be. Deferring GC is going to put memory pressure on these devices anyway and we already try to accomodate GCs around frame rendering workloads by using the idle notification callbacks.

I think we should revisit the original performance problem that caused this issue to be filed. Has a benchmark been written for this yet perhaps?

**Comment by Hixie** [comment]
This specific bug wasn't filed for any one performance issue, it was coalescing discussions from various issues.

We have on various occasions seen traces where we believe what's happening is that GC is causing the various rendering threads to get descheduled, and where it's possible we would have not missed a frame if that had not happened. Delaying GC by one second, or even 100ms, seems like an acceptable compromise if it causes us to not miss frames. As noted in the original comment, we'd need some mechanism to make sure we bail out of doing this (and allow GC to win) if it's going on for multiple frames in a row.

**Comment by zanderso** [comment]
A good framework for reasoning about these concerns could be the event loop task prioritization that @iskakaushik landed a while back. That would require the Dart VM to notify the Engine that it has work to do so that the Engine could schedule it at the right task priority on the thread with the right thread priority. (That is, if it's even advantageous to adjust thread priorities after the task priorities are in good shape).

**Comment by a-siva** [comment]
> A good framework for reasoning about these concerns could be the event loop task prioritization that @iskakaushik landed a while back. That would require the Dart VM to notify the Engine that it has work to do so that the Engine could schedule it at the right task priority on the thread with the right thread priority. (That is, if it's even advantageous to adjust thread priorities after the task priorities are in good shape).

I believe we had requested this in the context of idle tasks, see https://github.com/flutter/flutter/issues/12567

**Comment by zanderso** [comment]
Thanks @a-siva, I was trying to find that issue, but lost track of it =)

**Comment by zanderso** [comment]
@mkustermann Rather than thinking about this problem from the perspective of the Dart VM being as efficient as possible, and implementing new features for Isolates, I would encourage thinking about this problem primarily from the perspective of:
1. What is the right way for the Engine to do its main job of getting frames on the screen without jank? How do we make the lowest level of scheduling aware of frame workloads, so that we have a very high level of assurance they do not contend for resources with anything under the control of the VM and Engine?
2. What capabilities will we have on *every* platform we target. Can we set thread CPU affinity on iOS? Windows? Fuchsia? Can we detect high CPU load (with low-latency) on every platform? We can't use a solution that will only work on Linux and/or Android.

For example, it might be relatively easier to expand the capabilities of the Engine task queues (for example allowing an arbitrary number of threads) than it is to teach the VM about frames, or to work around a missing capability on some platform.

**Comment by a-siva** [comment]
Considering that https://github.com/flutter/engine/pull/30605 has landed with some good results is there still a need to pursue this issue ?

**Comment by zanderso** [comment]
As stated, this issue can be closed. The change increases priority of the UI and raster threads. Overall, I'd like to see the results of the investigation of the `customer: money` app from @iskakaushik before we declare victory. I'm also still wary that this approach will introduce jank due to thread priority inversions.

**Comment by a-siva** [comment]
we can discuss the issue of priority inversions in https://github.com/dart-lang/sdk/issues/44228 as that issue is still open and based on the results of the investigation by @iskakaushik we can pursue other options.
