### ISSUE TITLE
google_sign_in  version 5.0.1

### ISSUE THREAD

**Issue by manipoint** [flutter/flutter#89907]
Resolving dependencies...
Because google_sign_in >=5.0.1 depends on google_sign_in_platform_interface ^2.0.1 which depends on quiver ^3.0.0, google_sign_in >=5.0.1 requires quiver ^3.0.0.
And because every version of dependencies depends on quiver ^2.0.1, google_sign_in >=5.0.1 is incompatible with dependencies.
So, because our_app depends on both dependencies any and google_sign_in ^5.1.0, version solving failed.

**Comment by navaronbracke** [comment]
Your dependencies cannot resolve a version for `quiver` as two (or more) depend on different versions that exclude each other.
Could you provide the contents of your `pubspec.yaml`?

Regardless, I believe this is not a Flutter issue, but a mere dependency conflict.

If you use `quiver` directly, try bumping it to `quiver: ^3.0.0`

If you don't use it directly, but one of your package dependencies requires it,
try bumping the affected package dependency so that it requires `quiver: ^3.0.0`.

**Comment by darshankawar** [comment]
> Because google_sign_in >=5.0.1 depends on google_sign_in_platform_interface ^2.0.1 which depends on quiver ^3.0.0, google_sign_in >=5.0.1 requires quiver ^3.0.0.
> And because every version of dependencies depends on quiver ^2.0.1, google_sign_in >=5.0.1 is incompatible with dependencies.

The error message indicates, you'll need to use `quiver ^3.0.0` to resolve it.  Please upgrade to mentioned version which hopefully should resolve your issue.
Closing from here.
