### ISSUE TITLE
MethodChannel does not define checkMethodCallHandler？

### ISSUE THREAD

**Issue by arcticfox1919** [flutter/flutter#90048]
```
Error: The method 'checkMethodCallHandler' isn't defined for the class 'MethodChannel'.
 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' 
 ('../../Android/Flutter/packages/flutter/lib/src/services/platform_channel.dart').
```

After upgrading to version 2.5 I get a reported error. It looks like the new version of `MethodChannel` has removed the `checkMethodCallHandler` method. I checked the `MethodChannel` history and the method was not marked as deprecated before it was removed, and it was suddenly removed, causing my plugin library to not work, which is very confusing to me.

I haven't found an alternative, maybe someone can tell me?

**Comment by darshankawar** [comment]
@arcticfox1919 
The method `checkMethodCallHandler` has been deprecated. See this breaking change documentation for your reference along with replacements that you need to use instead of it. https://flutter.dev/docs/release/breaking-changes/mock-platform-channels
Hope it helps. I am going ahead and closing this as not an issue.
