### ISSUE TITLE
Flutter 2.5 web issue

### ISSUE THREAD

**Issue by arshkinana** [flutter/flutter#90132]
I am facing a weird problem since I upgraded to flutter 2.5. When I make the changes in the code and when the app reloads, I have to hover my mouse onto the browser to see the changes. This was not an issue before 2.5. I'm using Microsoft Edge to run my web projects.

**Comment by HeyAvi** [comment]
is that happens on chrome too?

**Comment by arshkinana** [comment]
Yes, it happens on chrome tabs too

**Comment by maheshmnj** [comment]
Hi @HeyAvi, Thanks for filing the issue. This is a known issue and can be reproduced on stable version 2.5  easily because the hot restart is taking longer to finish. This issue is being tracked here https://github.com/flutter/flutter/issues/89874. 
You may follow up there for further updates closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it.

Thank you.
