### ISSUE TITLE
Ratio of Andrew : API docs needs slight tweaking

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#90302]
## Use case

Having embedded videos (tutorials, widget of the week) is _awesome_. But on large screens, the video size increases to match the full width with no maximum constraint. This leads to scenarios like the following, where the video dominates the entire window, pushing other content off the screen.
![image](https://user-images.githubusercontent.com/2319867/133865857-e244b114-f68c-42d1-a3c1-8bbf8ef02768.png)

While we all need more @RedBrogdon in our lives, his sloth t-shirt might scare any small pet insects who are also in the room. Since Flutter aspires to be welcoming to all, we should make sure that the video is appropriately sized to avoid undue offense to all creatures.

## Proposal

The Flutter team should offer [cardboard cutouts](https://buildahead.com/product/custom-life-size-standup/) of our developer relations team so our community can keep a life-sized representation of their favorite devrel advocate or tech writer close by.

In **addition** to that, we should set a maximum size for the generated video embed. Per @devoncarew, "I believe these are injected into the `dartdoc` via a CLI tool during doc creation for the Flutter API docs. if you create an issue, I'd cc @gspencergoog - he'd know where this is happening."

**Comment by gspencergoog** [comment]
LOL!  Yes, I fully support the cardboard cutout idea!

This isn't as straightforward as you might expect: it appears to be codified by the `@youtube` directive in Dartdoc, which does have size arguments that seem to be ignored.

It looks like it happens [here](https://github.com/dart-lang/dartdoc/blob/6a25cd29bbb2ad411ee6a605dc5bb2ffc0452d64/lib/src/render/model_element_renderer.dart#L47).

If that's right, it looks like the size arguments are just used to [calculate the aspect ratio desired](https://github.com/dart-lang/dartdoc/blob/6a25cd29bbb2ad411ee6a605dc5bb2ffc0452d64/lib/src/model/documentation_comment.dart#L431), and are otherwise ignored.

We'd probably have to add a arguments to the youtube directive to add max size constraints.

cc @jcollins-g

**Comment by RedBrogdon** [comment]
Alternate proposal: make my image even bigger, and I'll just wear T-shirts with the docs printed on them?

**Comment by adityataps** [comment]
Ha! LGTM.

**Comment by gspencergoog** [comment]
> Alternate proposal: make my image even bigger, and I'll just wear T-shirts with the docs printed on them?

We must go deeper...

**Comment by goderbauer** [comment]
This* is getting fixed upstream in dartdoc with https://github.com/dart-lang/dartdoc/pull/3030, which we will need to pull into Flutter when it is released.

*) This being the oversized videos. As for the life-sized cardboard cutouts requested in the issue: I'll leave that for another day.

**Comment by goderbauer** [comment]
Shrinkage completed.

<img width="2672" alt="Screen Shot 2022-05-19 at 9 25 53 AM" src="https://user-images.githubusercontent.com/1227763/169350590-6890cb36-3f8a-43b1-9838-d059610b6256.png">

(This is currently only active on the master API docs. Will come to the stable docs with the next stable, so enjoy life-sized Andrew there while you still can!)
