### ISSUE TITLE
Dead package flutter_gifimage

### ISSUE THREAD

**Issue by JonasKuschel** [flutter/flutter#90336]
Hey,
I am not sure where to file this issue. I am using the [flutter_gifimage](https://pub.dev/packages/flutter_gifimage) package. Unfortunately it is not maintained anymore since 2019, because pull requests are not accepted by the owner anymore. Is it possible to revive that package in some way?

Thanks a lot!

**Comment by stuartmorgan** [comment]
> I am not sure where to file this issue.

Not here, since Flutter has no control over any packages other than those published by the Flutter team, but really there's nowhere to file such an issue; pub.dev is just a distribution system, and doesn't take over people's packages.

> Is it possible to revive that package in some way?

What happens to that particular package is entirely up to its owner. However, it's open source, so anyone is welcome to fork it, change the name, and publish a new package for people to use instead. (Ideally with multiple owners, to prevent the same thing from happening again with the new package.)
