### ISSUE TITLE
flutter_gallery_ios__transition_perf benchmark runs out of memory on iOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#9034]
## Steps to Reproduce

The `flutter_gallery_ios__transition_perf` benchmark is frequently running out of memory.

## Logs

[Sample devicelab log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci8yMzk4MWY1OTk2NmU3MDc0YmYyYTc2MTkwYzYzYjUzMjUxYWNlNWFmDAsSBFRhc2sYgICAgICA8AoM)

/cc @chinmaygarde @cbracken

**Comment by cbracken** [comment]
Looks like this is specifically related to our use of `--trace-startup` in the flutter driver test, which sets the VM's `--timeline_recorder` to write to an endless buffer rather than a ring buffer.

Without `--trace-startup`, we see allocated heap floating between 14-21MB in the gallery example. With `--trace-startup` I see heap hitting well over 250MB by the end of the test. Serialising the timeline data to JSON close-to doubles this, at which point the app is terminated.

Couple things we can do:
* Limit timeline collection to a fixed representative subset of the tests, so this doesn't grow arbitrarily over time. If the end goal is a representative histogram, then a subset seems reasonable.
* Collect a sparser event dataset (not sure what we collect today)

**Comment by eseidelGoogle** [comment]
I think --trace-startup currently implies turning the tracing collector into "unlimited" mode instead of the default "ring buffer".  We could consider changing that, certainly to a limited-but-large-enough-for-testing size?

**Comment by cbracken** [comment]
Yep, it implies `--timeline_recorder=endless`. Endless seems right if we're unwilling to lose data. I suspect we're collecting a whole whack more data than we need right now. The two streams we collect right now are `Dart` and `Embedder`. Not sure what subset of the `Dart` events we're using, but if we can enable/disable what's buffered at a fine-grained level, that seems like the way to go.

**Comment by cbracken** [comment]
@johnmccutchan

**Comment by yjbanov** [comment]
It seems the solution is to flush the timeline data occasionally and reset the buffer. I don't think a ring buffer is acceptable for the purposes we're using the timeline for. Perhaps the VM services could have a streaming version of the timeline API, which delivers events in coarse-grained chunks?

**Comment by johnmccutchan** [comment]
@yjbanov The service protocol has long had a "Timeline" event stream. When subscribed, the client will receive batches of 64 timeline events.

**Comment by yjbanov** [comment]
It's been pretty stable. Closing.
