### ISSUE TITLE
Accessing Flutter Skia apis

### ISSUE THREAD

**Issue by SivaramSS** [flutter/flutter#90343]
## Use case
We've written C++ libraries using Skia that we would like to reuse in our flutter application. Currently there is no provision.

## Proposal
Requesting provision to access Skia lib embedded in flutter (through Dart FFI?).

**Comment by TahaTesser** [comment]
Hi @SivaramSS 
Can you please be more descriptive? Also provide some use cases and examples of where and how these APIs would be useful

**Comment by SivaramSS** [comment]
Hi @TahaTesser Apologies. I've added more information below. Please check.

Use Case
1. We render a grid of data (spreadsheet) using Skia. We wish to reuse the drawing logic (written in C++) across platforms and in our flutter application. The drawing logic calls following Skia apis. 

`SkSurface::MakeRenderTarget(skCanvas->recordingContext(), SkBudgeted::kYes, imgInfo);
SkSurface::MakeRaster(imgInfo)
skCanvas->drawImage(fourthImage, x, y);
skCanvas->drawTextBlob(textBlob, x, y, paint);
skCanvas->drawLine(x, y+rowHt-6, x+colWidth, y+rowHt-6, paint);`

Uses
1. Code Reuse - If such apis are exposed, we can reuse our C++ code and call them through Dart FFI.  
2. Currently Dart:ui cannot be used in non-main isolates. If Skia apis are exposed, we will be able use Raster backend to render offscreen in multiple threads.
 
Below is a sample of our C++ drawing logic.

`static void drawInCanvas(SkCanvas* canvas, int xOffset, int yOffset, int width, int height, int scale) {
    SkPaint paint = SkPaint();
    paint.setColor(SkColorSetRGB(0, 0, 25));
    paint.setStyle(SkPaint::kFill_Style);

    SkFontStyle fontstyle = SkFontStyle::BoldItalic();
    sk_sp<SkTypeface> typeface = SkTypeface::MakeFromName("Arial", fontstyle);
    SkFont font = SkFont();
    font.setSize(15*scale);
    font.setTypeface(typeface);
    int y = 0, colWidth = 80, rowHt = 18;
    int startRow = yOffset/rowHt, startCol = xOffset/colWidth, endRow = (yOffset+height)/rowHt+1, endCol = (xOffset+width)/colWidth+1;
    y = ((startRow*rowHt)-yOffset)*scale;
    colWidth *= scale;
    rowHt *= scale;
    for(int i=startRow; i<=endRow; i++) {
        int x = (((colWidth/scale)*startCol)-xOffset)*scale;
        for(int j=startCol; j<=endCol; j++) {
            std::string str = "R"+std::to_string(i)+"C"+std::to_string(j);
            sk_sp<SkTextBlob> textBlob = SkTextBlob::MakeFromText(str.c_str(), str.size(), font);
            canvas->drawTextBlob(textBlob, x, y, paint);
            canvas->drawLine(x, y+rowHt-6, x+colWidth, y+rowHt-6, paint);
            canvas->drawLine(x, y, x+colWidth, y, paint);
            canvas->drawLine(x+colWidth, y, x+colWidth, y+rowHt, paint);
            x += colWidth;
        }
        y += rowHt;
    }
}`

**Comment by chinmaygarde** [comment]
Skia is an implementation detail in Flutter with no stable interface or version guarantees. If the application needs to use Skia, it must package its own as necessary and interop with the engine either using texture interop (see the [Texture](https://api.flutter.dev/flutter/widgets/Texture-class.html) widget), FFI, or platform channels (probably not recommended for byte data). Or, you could render the contents of the spreadsheet into a platform view and use that inline. Depends on the use-case.

I am also not sure why dart:ui on the UI isolate is a no go. Because the UI isolate doesn't actually perform rendering. Only the rendering intent is specified there. The engine renders using the appropriate backend on its own threads. So I wouldn't dismiss using dart:ui directly as an option without actually measuring the performance of such a scheme.

Closing this as a wont-fix.
