### ISSUE TITLE
Either fix or delete the Android emulator scenario app tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#90401]
All of the non-firebase tests in the Scenario app (see instruction removal in linked PR below) are broken. This happened over the course of time, where the target was incorrectly set up on CI so that failures were not reported, and now failures are just ignored. I have never successfully run these tests locally, and it's not clear to me when they last passed.

@blasten was looking at whether it would be better to just port these to the framework side, where we have better options for taking screenshots.

**Comment by blasten** [comment]
We should set up some time to chat about how to unlock this. cc @zanderso.

One issue that we need to address is where/when to run this test. Some thoughts:

**Engine (pre or post submits or both)** 
I tried to use a dependency created by Facebook to pull screenshots. Unfortunately, the screenshots aren't deterministic due to Skia rolls. Moreover, using that tool means that we lose the ability to integrate with Skia Gold, since the fb tool doesn't provide a proper API for that kind of integration.

I worked on adding support for pulling screenshots through Flutter drive (https://github.com/flutter/flutter/issues/83856), which can be integrated with Skia Gold. However, this reopens the question of circular dependencies since Flutter drive needs the Flutter tool and other packages.

**Framework (pre or post submits or both)**
The main issue is that these are scenarios meant to test the engine. Pushing real issues or even flakiness to the engine roll is not ideal.

**Firebase testlab**
I'm not aware of any mechanism that allows code running on a Firebase testlab device that can also talk to Skia gold. 

**Build a custom tool**
Maybe, we should just build a test framework for the engine that works with Skia gold. The main problem I see is that this is more expensive to maintained over the long run. Take a look at the [Facebook tool ](https://github.com/facebook/screenshot-tests-for-android)to get an idea of all the pieces one needs to implement the ability to pull screenshots.  

cc @godofredoc @zanderso  @dnfield

**Comment by zanderso** [comment]
Is the ability of these tests to provide value dependent on our ability to take screenshots when running them out of the Engine repo? Or do they test any functionality that is unrelated to the precise pixels on the screen?

**Comment by blasten** [comment]
There are a few scenarios that don't need take screenshots, but the majority of the tests do require screenshots.

**Comment by chinmaygarde** [comment]
Based on https://github.com/flutter/engine/pull/33360. It seems like this is fixed but @dnfield thinks there are still ongoing work items.

**Comment by dnfield** [comment]
That commit made it possible to run the tests again, but they're not running on CI yet.
