### ISSUE TITLE
App UI Stalled when frequently sending messages through platform channels

### ISSUE THREAD

**Issue by SivaramSS** [flutter/flutter#90405]
## Details
My App is a cloud based spreadsheet app and at a time there can be multiple collaborators working on a document in web and mobile.

Edits made by collaborator are delivered to the mobile as responses to our inhouse messaging framework library (written in java/swift). Currently i've to use Platform Channels to send these responses to Dart for updating data model and subsequently the ui.

Problem:
1. The number of messages received in the messaging framework are huge in number, in cases where a collaborator performs actions repeatedly or multiple collaborators perform actions in short amount of time. In both these cases, the platform channel gets overloaded with messages. While these messages are delivered if the user performs gestures (like scrolling the grid), it burdens the ui isolate further.
2. Parsing some responses (like image) delivered and decoded on the ui isolate takes lot of ms and stalls the App Ui.

**Target Platform: Android**
**Target OS version/browser: Android 11**
**Devices:Pixel 3**

cc: @gaaclarke

**Comment by gaaclarke** [comment]
Is this lagginess on the sending device or just the receiving device?  Or both?

I once created a multiplayer protocol.  In my case I opted to send the whole state of the game in compressed format repeatedly over UDP.  That way I didn't have to worry about dropped delta information and massive amounts of deltas didn't overload the game.  Video formats also have the concept of a frame made of delta data, or an "iframe" that contains the whole state of the world.  That's just some food for thought that maybe in certain circumstances you can use absolute data packages instead of delta data if you get spammed with deltas.

I think for the sending side this may be a good candidate for [FFI Platform Channels](https://github.com/flutter/flutter/issues/90407) since it would allow you to send your data without hitting the `platform` thread.  You could potentially do processing on a background isolate before sending the data.  The design doc doesn't however have a solution to help with the receiver unless you created a background isolate that synchronously polled the host platform for new messages which isn't the best.  I'll think about that one.

**Comment by chinmaygarde** [comment]
Can you post a reduced test case and/or a timeline trace of the issue please? The issue performance template has the instructions on how to achieve this.

Specifically, I am not sure if its the parsing, platform channel overheads, or just the copies. Processing platform channel messages should not stall UI after the recent work on event loop task prioritization. So I don't think we have enough information just yet to devise solutions.

Can you also elaborate on what you mean by parsing of images on the UI isolate? Byte data can be sent directly to the engine for decompression into image handles without any processing on the UI isolates. If the UI isolate is doing this, there might need to be a reconsideration of the application architecture.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by gaaclarke** [comment]
FYI this issue may be ameliorated by Background Platform Channels (https://github.com/flutter/flutter/issues/91635).  That will remove work from the platform thread, but won't change ui thread usage, so it depends on where the bottleneck is.
