### ISSUE TITLE
[image_picker] add image limit

### ISSUE THREAD

**Issue by Kizat** [flutter/flutter#90499]
for example:

```
picker.pickMultiImage(
 limit:20
)
```

**Comment by danagbemava-nc** [comment]
Hi @Kizat, See 

https://github.com/flutter/flutter/issues/85772#issuecomment-884137114
&
https://github.com/flutter/flutter/issues/85772#issuecomment-887614127

Due to platform limitations this feature cannot be implemented atm. 

Closing as this is not an issue with `image_picker` plugin but a limitation of other underlying platforms. 

Thank you
