### ISSUE TITLE
Firebase codelab example minor security issue

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#90588]
In this codelab: https://firebase.google.com/codelabs/firebase-get-to-know-flutter#7

This security rule
```
allow write: if request.auth.uid == request.resource.data.userId;
```

would allow me to write entries if I am not signed in (`request.auth.uid == null`) and I am sending `null` as `request.resource.data.userId`.

I haven't tried it though. If I am wrong, there should be a comment on why this is still safe.

Not sure why I was directed to Flutter main repo when clicked "Report a mistake".

**Comment by puf** [comment]
When I try to access `request.auth.uid` in the playground I get an error , since `request.auth` is a Null value.

<img width="675" alt="Screen Shot 2021-09-23 at 10 08 30" src="https://user-images.githubusercontent.com/913631/134552702-a73053f1-591a-4dbe-8f39-4c15c1e1ce93.png">

So while it would be more explicit to check `request.auth != null` before doing `request.auth.uid`, I am not able to reproduce the security problem you mention.

Can you show how you tested this, so that I can try to reproduce again?

**Comment by domesticmouse** [comment]
For what it's worth, I took these firebase rules from the JavaScript version of this codelab - https://firebase.google.com/codelabs/firebase-get-to-know-web#8

I'm happy to change the rules, provided the JS codelab is updated in sync.

/cc @kroikie

**Comment by puf** [comment]
👍
