### ISSUE TITLE
ci_yaml json configs need to be created manually for new branches

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#90890]
When adding a new branch the code generation fails because it is looking for a existent valid which already contains valid json.

E.g. when main branch was added to engine the config generation failed because it could not find engine_main_config.json. Adding the file to the generated folder with `{}` as content made the config generation succeed.

**Comment by CaseyHillers** [comment]
@godofredoc it would be simpler if we could converge master+main to be the default builders. Otherwise, we need to upstream patches in Cocoon before continuing to support branches in the builder name

Would it be sufficient to land https://flutter-review.googlesource.com/c/infra/+/18602 to support this, then we can migrate engine_config.star to point to the main branch when we're ready to migrate (as well as the other repos).

The downside with this approach is we're exclusively triggering builds from master and main, instead of doing a staged rollout.

**Comment by godofredoc** [comment]
Putting two builds from different branches in the same bucket may cause undeterministic behavior. Would it be possible to manually add a minimal configuration to the json file containing only the configs roller? that way the next commit will generate all the remaining builds.

**Comment by CaseyHillers** [comment]
I updated https://flutter-review.googlesource.com/c/infra/+/18602 to migrate Cocoon to main as an example.

If master->main is a mirror, and main->master is a mirror, these branches should be in sync and not have unique builders. However, if we plan for these to not be in sync I can separate the infra logic.

**Comment by godofredoc** [comment]
How would this impact post-submit?

**Comment by CaseyHillers** [comment]
From the LUCI config side, there should be no visible impact to post-submit. Once you have the mirror setup for master->main, and ci.yaml also has main as an enabled_branch, you can switch the LUCI configs to point to refs/heads/main instead of master.

Future ci.yaml changes will be rolled from main instead of master.

The only side effect is when this migration is switched, it may retrigger all the CI builds once as the master build trigger is now the main trigger.l

**Comment by CaseyHillers** [comment]
Closing as the related CL landed with an example on how to do the migration.

Feel free to reopen if we'd like deeper ci.yaml integration for the master->main migration
