### ISSUE TITLE
not executing code on catch without Future.delayed

### ISSUE THREAD

**Issue by cindRoberta** [flutter/flutter#90929]
```dart
// auth_controller.dart
enum Status { start, success, loading, error }

class AuthException implements Exception {
    String title;
    String content;

    AuthException({required this.title, required this.content});
}

class AuthController {
    late final ValueNotifier<bool> state;
    late final ValueNotifier<Status> _status = ValueNotifier<Status>(Status.start);
    late AuthException _error;

    ValueNotifier<Status> get status => _status;
    AuthException get error => _error;

    Future<void> login() async {
        _status.value = Status.loading;

        try {
            UserModel? user =
                await _authenticationRepository.signInWithEmailAndPassword(
                    emailTextController.text, passwordTextController.text);

            if (user != null) {
                box.write("auth", user);
            }

          _status.value = Status.success;
        }  on AuthException catch (e) {
                _error = e;
                _status.value = Status.error;
        } finally {
            //await Future.delayed(const Duration(microseconds: 1));
            status.value = Status.success;
        }
    }
}
```

```dart
// login_page.dart
ValueListenableBuilder(
    valueListenable: _authController.status,
    builder: (_, Status value, __) {
        print(value);
        switch (value) {
            case Status.error:
                print('ERROR');
                //SchedulerBinding
                WidgetsBinding.instance!.addPostFrameCallback((_) {
                    ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                            content: Text(_authController.error.content)));
                });

                return const Text('Acessar');

            case Status.loading:
                return const Padding(
                    padding: EdgeInsets.all(12),
                    child: CircularProgressIndicator(color: Colors.white)
                );

            case Status.start:
            case Status.success:
                return const Text('Acessar', style: TextStyle(
                    fontSize: 20,
                    color: Colors.white));
        }
})
```

when I run the code above, the `print('ERROR')` on `switch` on `builder` of `ValueListenableBuilder` doesn't show up and the `print(value)` on `switch` just show `Status.start`, `Status.loading` and `Status.success`

if I uncomment the `await Future.delayed(const Duration(microseconds: 1));` above of `status.value = Status.success;` on `finally`, the code works normally

why it occurs and how to solve it without `await Future.delayed(const Duration(microseconds: 1));` ?

**Comment by danagbemava-nc** [comment]
Hi @cindRoberta, 

The `finally` block will execute regardless of whether or not there is an exception thrown. And in your case, since you're setting the value of `status.value` to `Status.Success` in the finally block, that line of code will be executed, updating the value that was supposed to be the error value. 

My guess as to why it would be showing the error when you use the Future.delayed, is that the delay prevents the value from being updated before the error case is executed. 

In your case however, since you aren't really doing anything other than setting a value you've already set in your finally block, I believe removing the `finally` block should make it work as it is intended. 

See https://dart.dev/guides/language/language-tour#finally for more information on finally

**Comment by cindRoberta** [comment]
@danagbemava-nc
I change to: and continues with the same behavior as using `finally`
```dart
    Future<void> login() async {
        _status.value = Status.loading;

        try {
            UserModel? user =
                await _authenticationRepository.signInWithEmailAndPassword(
                    emailTextController.text, passwordTextController.text);

            if (user != null) {
                box.write("auth", user);
            }

          _status.value = Status.success;
        }  on AuthException catch (e) {
                _error = e;
                _status.value = Status.error;
        }
            status.value = Status.success;
    }
```

**Comment by danagbemava-nc** [comment]
Hi @cindRoberta, 

You don't need this line `status.value = Status.success;` after the `try/catch`.

```dart
    Future<void> login() async {
        _status.value = Status.loading;

        try {
            UserModel? user =
                await _authenticationRepository.signInWithEmailAndPassword(
                    emailTextController.text, passwordTextController.text);

            if (user != null) {
                box.write("auth", user);
            }

          _status.value = Status.success;
        }  on AuthException catch (e) {
                _error = e;
                _status.value = Status.error;
        }
    }

```

Just the above should be enough.

**Comment by cindRoberta** [comment]
@danagbemava-nc if I remove this line I get other bug

**Comment by danagbemava-nc** [comment]
@cindRoberta What bug?

**Comment by cindRoberta** [comment]
@cindRoberta I have a `ValueListenableBuilder` wrapping my `Form` that listen an `_enableBtn`, this `_enableBtn` controls if the button is disabled or enabled depending on the validators of `TextFormField`s, when the text of `TextFormField`s are valids and I click on button, later if I delete text of a `TextFormField` so that it stays invalid, if I digite text to validate again, the status variable is changed to Status.error without to click on button

**Comment by danagbemava-nc** [comment]
The issue seems to be how you are doing your implementation then. 
This is not an issue with flutter itself as such I'm going to have to close this issue. 

Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by cindRoberta** [comment]
@danagbemava-nc https://stackoverflow.com/questions/69371306/code-not-executing-on-catch-without-future-delayed
