### ISSUE TITLE
Flutter Network Image loads very very slowly

### ISSUE THREAD

**Issue by victorhez** [flutter/flutter#90940]
On my app, I have so many screens using network images, but they all take time to load

**Comment by Mayank-9018** [comment]
Hi @victorhez 

This might me be due to slow network speeds. You should try lazy loading them or maybe caching them for future use.

These links might help you: [1](https://stackoverflow.com/questions/56434003/very-simple-image-loaded-pretty-slow-with-flutter),[2](https://stackoverflow.com/questions/52212087/fastest-way-to-display-100-or-more-images-in-flutter),[3](https://educity.app/flutter/the-right-way-to-preload-or-precache-images-in-flutter-for-extreme-fast-rendering).

If not, you can ask a new question on SO with your specific details.

**Comment by victorhez** [comment]
If I cache them, if the user updates her profile picture, it means it won't update

**Comment by Mayank-9018** [comment]
That's for you to figure out and as I said SO would be a better place to ask about this.

**Comment by TahaTesser** [comment]
Hi @victorhez 
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
