### ISSUE TITLE
error Navigator

### ISSUE THREAD

**Issue by ShaimaaFakhraldin** [flutter/flutter#91022]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ShaimaaFakhraldin, 

When filing an issue, it is important that you provide all the required information in the template. 

Simply stating your error doesn't tell us anything other than "my app doesn't work properly/correctly", which we're already aware of since you're filing the issue. 

As such I'm going to close this issue. 

If you have an actual issue, kindly file a new one and fill in all the requisite information. 

Thank you

**Comment by ShaimaaFakhraldin** [comment]
Tanks i solve it
