### ISSUE TITLE
no null-safety in setStingList in SharedPreferences

### ISSUE THREAD

**Issue by mUmarBaloch** [flutter/flutter#91102]
the **setStringList** hv an argument **List<String>**. it makes issues or _returns exceptions_ when we have to use nullable list of strings in a StringList. so it should be **List<String?>?**  as we know that setString wants String?. i hope it will fixed as soon as possilbe.

**Comment by stuartmorgan** [comment]
> it makes issues or _returns exceptions_ when we have to use nullable list of strings in a StringList.

That is the expected behavior if you bypass type checking and pass the wrong types.

> so it should be **List<String?>?**

It certainly shouldn't be `List<String?>?` because storing nothing isn't supported.

It could potentially be `List<String?>`, but that would be a breaking change; more likely if we were to support it, it would be via a new method. What is the use case for storing null values in the list?

> as we know that setString wants String?.

That [is not the case](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L138). `setString` takes a `String`, not a `String?`, by design. That will not be changing.

> i hope it will fixed as soon as possilbe.

This isn't a bug; support for `List<String?>` would be a feature request. That will need a use case, and evaluation of the value vs the extra API complexity.

**Comment by mUmarBaloch** [comment]
I really appreciate your efforts.
