### ISSUE TITLE
Flutter causes Mac OS Crash 2

### ISSUE THREAD

**Issue by buyildir** [flutter/flutter#91251]
Hi,

I'm using flutter now for the last 2years on my machine. A few weeks ago I had the same problem like i have it again - but i do not have any clue why and how to resolve it. 

When I run the "flutter run" command, the XCode Build is working and for some seconds i can see the next task "compiling, signing and...." and then sudden it causes my Mac OS reboot. It happens now every time which makes me impossible to work on flutter. Same like few weeks ago.

Specs from my machine: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) - System Version: macOS 11.6 (20G165) - Kernel Version: Darwin 20.6.0
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)

I've already created an issue for this problem here but after it was resolved magically the issue was closed.
This is the issue i have created:[here](https://github.com/flutter/flutter/issues/85950)
I read some posts that some applications may cause a "kernel panic" but I'm not sure which app this is. And why does this happen now? ([like here](https://github.com/flutter/flutter/issues/56288) )

Any idea? Any help from your side? @darshankawar any further points were i can look at?

i have added some text files from the crash report - i hope this helps. if you see some sensitive data please be so kind and delete it.
[crash_01.txt](https://github.com/flutter/flutter/files/7280830/crash_01.txt)
[crash_02.txt](https://github.com/flutter/flutter/files/7280831/crash_02.txt)
[crash_03.txt](https://github.com/flutter/flutter/files/7280832/crash_03.txt)

Hopefully we can fix this quickly.

Thank you!

**Comment by stuartmorgan** [comment]
These are coming from the iOS simulator runtime; you'll need to report this to Apple, as it's not something Flutter has any control over.

**Comment by buyildir** [comment]
hi @stuartmorgan. i just had a conversation with apple support guys and they're telling me that this is not something simulator related. in fact i've tried to open the xcode project and build the app there. i did not face any issue there. any idea why? why is crashing when i'm running the "flutter run" command in vscode and not when I'm building the via xcode with the respective simulated device?

**Comment by stuartmorgan** [comment]
> i just had a conversation with apple support guys and they're telling me that this is not something simulator related.

They are incorrect. From your logs:

```
Process:               chronod [941]
Path:                  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ChronoCore.framework/Support/chronod
Identifier:            chronod
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [776]
Responsible:           SimulatorTrampoline [713]
```

Look at the path of the crashing process; it's part of the simulator.

What's more, if an entirely user-space process (like Flutter) causes a kernel panic, that is by definition a system bug, because that's not supposed to be possible.

And lastly, you can see that the crashing thread:
```
Thread 7 Crashed:: Dispatch queue: com.apple.RBDevice
0   libsystem_kernel.dylib        	0x00007fff6bf9e92e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6bfee5bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20107684 abort + 123
3   com.apple.RenderBox           	0x00007fff55db664e RB::precondition_failure(char const*, ...) + 291
```

This is crashing in Apple code, on a private thread created by Apple code. It's common for kernel panics to have a specific trigger for a given person, but the thing that triggers the kernel panic and the **cause** of the kernel panic are not the same thing. (In exactly the same way that if you wrote a Flutter application that triggered a specific rare bug in Flutter, your application would not be the **cause** of the bug.)

I'm not sure exactly who you talked to, but since you say you had a conversation I'm assuming it was front-line support. You need to actually [report a bug](https://developer.apple.com/bug-reporting/) so that it goes to the appropriate Apple engineering team.

For context: I worked for several years as a software engineer at Apple, in the macOS division, in a role whose responsibilities including reproducing kernel panics and routing them to the appropriate engineering teams, so my comments above are made based on extremely relevant experience.

> in fact i've tried to open the xcode project and build the app there. i did not face any issue there. any idea why? why is crashing when i'm running the "flutter run" command in vscode and not when I'm building the via xcode with the respective simulated device?

The people who can determine why this happens in only certain circumstances are the engineers at Apple who have access to the source for the crashing process.

**Comment by buyildir** [comment]
hey @stuartmorgan thanks a lot for response! in fact, it was a front-line support to whom i had to explain first of all a bit of the flutter world.
i just reported a bug and gave the same description like here and also attached the log files. hopefully they can find a solution.
