### ISSUE TITLE
when i try to make Navigator.push in external file to can reuse it i get this error ======== Exception caught by widgets library ======================================================= The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#69995](dirty, dependencies: [UnmanagedRestorationScope, HeroControllerScope], state: NavigatorState#3641e(tickers: tracking 3 tickers)): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5307 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by bellaismail** [flutter/flutter#91286]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @bellaismail, 

When filing an issue, it is important that you provide all the required information in the template. 

Simply stating your error doesn't tell us anything other than "my app doesn't work properly/correctly", which we're already aware of since you're filing the issue. 

As such I'm going to close this issue. 

If you have an actual issue, kindly file a new one and fill in all the requisite information. 

Thank you
