### ISSUE TITLE
Form validation in default tab controller

### ISSUE THREAD

**Issue by BhavyaGovind** [flutter/flutter#91293]
Hi Team, 
I am using a form in the default tab bar controller. When the user press save/update button I tried to call form validation by formKey.currentState!.validate(). It does the validation but only for the active tab fields. 
I tried to create different forms for each tab but since the current state for the non-active tab returns null, it is not getting validated. Please help me with how to proceed in this situation. I am stuck on this issue for a long time and did not find much info on this issue. 
Thanks in advance.

**Comment by maheshmnj** [comment]
Hi @BhavyaGovind,

> I tried to create different forms for each tab but since the current state for the non-active tab returns null, it is not getting validated.

This seems to be expected behavior.

It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow with enough sample code and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/. Please note that the goal of the issue tracker is to track the issues in the flutter framework. 
       
   Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.

Thank you
