### ISSUE TITLE
Add scrollbar option to `AlertDialog` widget

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#91329]
There is currently an option to make the dialog scrollable with the `scrollable` param, but the user cannot control whether the scroll view has a scrollbar visible. We should either add this by default, or add a `includeScrollbar` param so the user can control this.

**Comment by Piinks** [comment]
Hey @kenzieschmoll! I have a couple of questions to clarify the expected behavior

- Would it make sense to use the inherited ScrollBehavior to apply the scrollbar? (`ScrollBehavior.buildScrollbar`) This is something the user can already do.
- Or should this happen automatically: if AlertDialog is scrollable, add scrollbar?
- We currently apply Scrollbars automatically to Scrollables using the ScrollBehavior on desktop platforms, so this should already be happening in that case. Would you expect different handling on desktop vs mobile or web behavior?

**Comment by kenzieschmoll** [comment]
> Would it make sense to use the inherited ScrollBehavior to apply the scrollbar? (ScrollBehavior.buildScrollbar) This is something the user can already do.

I'm not sure what you mean by this. What would this look like in the context of using an AlertDialog widget in a build method?

I would expect a scrollbar to appear automatically if the AlertDialog is scrollable on both desktop and web. I'm not sure what the expected behavior should be for mobile. I can confirm though, that the scrollbar is not automatically showing up if that is what should be happening on desktop.

**Comment by Piinks** [comment]
Hey @kenzieschmoll I have confirmed this is already working. 🎉 

Is this happening somewhere in Devtools? I learned recently that sometimes DevTools is intentionally configured to override the platform with fuchsia. Or sometimes there are classes copied from the framework that don't have the latest changes and features.

On desktop and web-running-on-desktop, the ScrollBehavior automatically applies the scrollbar [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_configuration.dart#L157), or for MaterialApps [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app.dart#L727). 

ScrollBehavior is inherited, and we designed it this way so that we would not have to add something like `addScrollbar` on every widget that scrolls. :) 
There is a [migration guide here](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars) that explains the various ways this can be used, there are a lot of options based on what you would like to see. You may also like ScrollbarTheme, which is also inherited and controls the appearance of the scrollbar. 

Here is the reproduction I used on desktop to verify the current behavior, as well as a screen redording.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Dialog Demo')),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            _showMaterialDialog(context);
          },
          child: const Text('Show AlertDialog'),
        ),
      )
    );
  }

  void _showMaterialDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          scrollable: true,
          title: const Text('Material Dialog'),
          content: Column(
            children: List.generate(50, (index) {
              return Container(
                height: 30,
                color: index.isEven ? Colors.red : Colors.blue
              );
            })
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: const Text('Close')
              ),
          ],
        );
      }
    );
  }
}
```

https://user-images.githubusercontent.com/16964204/136865819-596ab5e0-65f2-421d-b8b8-8e30b8c87f2e.mov

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
