### ISSUE TITLE
Export a base class for Objective C method channel plugins

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#9161]
Basically every plugin we've written thus far (internally in Google) looks like the following:

Seems like there's an opportunity to remove a lot of boilerplate by providing a base class to do this basic wiring.

@mravn-google 

```
@interface FLTExamplePlugin : NSObject
@property(strong, nonatomic, readonly) FlutterViewController *controller;
- (instancetype)init NS_UNAVAILABLE;
- (instancetype)initWithController:(FlutterViewController *)controller NS_DESIGNATED_INITIALIZER;
@end

@implementation FLTExamplePlugin {
  FlutterMethodChannel *_channel;
}

- (instancetype)initWithController:(FlutterViewController *)controller {
  if (self = [super init]) {
    _controller = controller;

    _channel =
        [FlutterMethodChannel methodChannelNamed:CHANNEL_NAME
                                 binaryMessenger:controller
                                           codec:[FlutterStandardMethodCodec sharedInstance]];

    __unsafe_unretained typeof(self) weakSelf = self;
    [_channel setMethodCallHandler:^(FlutterMethodCall *call, FlutterResultReceiver result) {
      [weakSelf handleMethod:call sendResultTo:result];
    }];
  }
  return self;
}

- (void)dealloc {
  [_channel setMethodCallHandler:nil];
  _channel = nil;
}

@end
```

**Comment by tvolkert** [comment]
Actually, it's better to have the method be:

```
- (void)handleMethodCall:(NSString *)method
               arguments:(NSDictionary *)arguments
                  result:(FlutterResultReceiver)result;
```

And the base class implementation can just respond with a method not found error.

**Comment by mravn-google** [comment]
Things to consider:

- Maybe it would be easier for ObjC plugins to use a MethodCallHandler protocol rather than a typedef'd callback?
- A Swift sub-class should look... swifty. Might be enough to add some _Nullable and _Nonnull annotations.
- Consistency with corresponding Android and Dart APIs. For instance, the Android side uses interfaces, not abstract base classes.

**Comment by tvolkert** [comment]
Yeah, maybe introducing a `FlutterMethodCallHandlerDelegate` protocol and having the interface be something the following would make sense:

```
- (void)setMethodCallHandlerDelegate:(FlutterMethodCallHandlerDelegate)handler;
```

**Comment by mravn-google** [comment]
The delegate could be a property of `FlutterMethodChannel`, I guess, as an alternative to having the `FlutterPlugin` base class at all. That would mean we have at least three options:

- A channel concept using callback blocks (current solution; this issue indicates that is not good enough for many situations, typically because plugins need state in addition to the channel).
- A plugin base class with a channel property and a method to be overridden to handle incoming method calls on that channel (as suggested here and implemented in https://github.com/flutter/engine/pull/3561).
- A method call handler delegate protocol to be implemented by plugins, and a corresponding `delegate` property on `FlutterMethodChannel`.

I have way too little experience with ObjC to know what developers would expect or prefer. Same goes for Swift by the way. @chinmaygarde, do you have an opinion?

**Comment by gavindoughtie** [comment]
Oh, I *wish* I were an affluent iOS developer... :-P

I'd definitely lean towards defining a couple of delegate protocols (one for the plugin, one for whatever Flutter hands the plugin) as the actual binding contract.

Then I'd do a BasePlugin that implements the protocol, and then most plugins would just extend that by overriding a couple of methods (like "createViewController" or "handleMethod").

This way you keep the requirements minimal while still making it easy for more trivial plugins.

**Comment by tvolkert** [comment]
+1 to a base class that implements one or more protocols.

**Comment by mravn-google** [comment]
Fixed by https://github.com/flutter/flutter/pull/3645.

**Comment by tvolkert** [comment]
https://github.com/flutter/engine/pull/3645 rather?

**Comment by mravn-google** [comment]
Yes, thanks.
