### ISSUE TITLE
Engine crashes loading JPEG images

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#918]
Engine crashes loading JPEG images.

```dart
import 'package:flutter/widgets.dart';
void main() => runApp(new NetworkImage(src:'http://stylonica.com/wp-content/uploads/2014/04/Cat-Wallpaper.jpg'));
```

**Comment by jason-simmons** [comment]
There are a couple of problems here:

* we switched from libjpeg_turbo to libjpeg.  libjpeg is failing to decode this image because our build doesn't define DCT_IFAST_SUPPORTED

* DecodeImage in painting.cc determines whether the decode succeeded by checking (decoder->failed() || decoder->frameCount() == 0)
However, the JPEG decoder always says that the frameCount is 1, and it actually decodes the image during the later call to decoder->frameBufferAtIndex(0).  So at the time of the check we don't yet know that the decode failed.

**Comment by Hixie** [comment]
Should we file bugs about the two issues here?

**Comment by jason-simmons** [comment]
Closing this.  The DecodeImage issue has been fixed, and we've moved back to using libjpeg_turbo.
