### ISSUE TITLE
Multi Image Picker Previous Selected Images in Gallery/Photos

### ISSUE THREAD

**Issue by Limvunhoy** [flutter/flutter#91905]

**Comment by darshankawar** [comment]
@Limvunhoy 
There's not enough details / description of the use case you are proposing. Please use the new issue template for feature request and provide atleast some of the details requested there, so that we can use it to properly address it.
 https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=

Closing from here as not enough information is provided.
