### ISSUE TITLE
flutter/flutter-intellij management issues

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#92020]
We've recently run into a couple issues in the Flutter plugin repo.

- Cannot move issues to dart-lang/sdk anymore. Used to add a comment "/move dart-lang sdk" but that's not working now. Also used to use a similar comment to move to flutter/fluter but now have to use the Transfer menu.
- All commits need to be signed. I'm set up to do so, but others are not, and I notice flutter/flutter does not require signing.

**Comment by Hixie** [comment]
The signed commits thing should be resolved.

Moving issues is expected to be done using the Transfer issue feature on GitHub now, I believe. I don't think it supports transferring between orgs though. I'm not sure what implemented `/move` before. If anyone wants to run a bot to support that, in general we're not opposed.

I'm going to close this since it seems we've lived with the current situation for a while without it being escalated. Let me know if the `/move` thing needs anything from me.
