### ISSUE TITLE
Remove unnecessary asserts

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#92191]
Upgrading the framework to null safety made a lot of the asserts unnecessary. For example, the [ThemeData.raw()](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L723l) constructor asserts that it's parameters are non-null, even though they are required and non-null types:

```dart
class ThemeData with Diagnosticable {
  // ...
  final VisualDensity visualDensity;

  const ThemeData.raw({
    required this.visualDensity,
    // ...
  }) : assert(visualDensity != null),
```

**Comment by pedr0luiz** [comment]
Hi! I'd like to work on this. Can we make a tasklist of the files that need to be refactored?

**Comment by nt4f04uNd** [comment]
Hi @johnpryan. Null-safe code can be called from non null-safe mode. I remember that there were a few PRs that tried to address similar things, for instance https://github.com/flutter/flutter/pull/88359, https://github.com/flutter/flutter/pull/81438 and https://github.com/flutter/flutter/pull/85309, but as far as I know, the plan is too keep them until non-nnbd code support will be dropped entirely, which will happen eventually, but not yet.

Also, this issue seems similar to https://github.com/flutter/flutter/issues/85308.

**Comment by johnpryan** [comment]
Closing as a dupe of https://github.com/flutter/flutter/issues/85308
