### ISSUE TITLE
Background tasks in IOS not running frequently

### ISSUE THREAD

**Issue by Musie-ebuy** [flutter/flutter#92259]
Hi Flutter community, 
I have implemented a periodic background tasks(using the WorkManger plugin) which should run daily (or nearly daily) using flutter for an IOS device.
I have tested the background task in Android device and they work correctly. But in IOS they are not running even close to the frequency they are supposed to. In the flutter documentation I see that, in IOS, the WorkManger for background tasks still does not support implementation of periodic tasks. 
Do you know any alternative solution(or possible workaround) for this issue? or do you think Flutter will make this this feature available soon?

thank you,
Musie Ebuy

**Comment by danagbemava-nc** [comment]
Hi @Musie-ebuy, the `workmanager` plugin is not maintained by the `flutter` team but rather the `fluttercommunity`. 

Kindly file this issue [here](https://github.com/fluttercommunity/flutter_workmanager/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) so that it can be properly addressed. 

Thank you
