### ISSUE TITLE
Create a version of the analyzer benchmark that does not require devices

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92299]
This test usually catches linter errors only after the changes have landed forcing to patch forward.

**Comment by godofredoc** [comment]
Here is one example with failures:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20analyzer_benchmark/1253/overview

**Comment by christopherfujino** [comment]
I believe that our already existing `//flutter/dev/bots/analyze.dart` test already effectively verifies the analysis that is run in the benchmark: https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L162

In the example of https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20analyzer_benchmark/1253/overview, the actual problem was that the PR's branch point was too old, and there had been upstream changes which were incompatible with the PR changes: https://github.com/flutter/flutter/pull/95686

**Comment by christopherfujino** [comment]
I suggest we close this feature request @godofredoc

**Comment by godofredoc** [comment]
Thanks for the checking the root cause of the problem. Closing this issue.
