### ISSUE TITLE
Errors in new project created in VS Code

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#92437]
STEPS TO REPRODUCE:
1. I clean-installed VS Code on Linux and ran it.
2. I added the Flutter extension.
3. I chose to create a new project using the "skeleton" template in a new directory.
4. A prompt told me to press F5 to run it, so I did.

EXPECTED RESULTS
App runs, either on my attached Android device, or using Linux, or as a web app.

ACTUAL RESULTS
It immediately complained about build errors.

**Comment by Hixie** [comment]
@DanTup If you could post an update when you have a chance that'd be great. Thanks!

**Comment by DanTup** [comment]
No significant progress yet - I have [a CL](https://dart-review.googlesource.com/c/sdk/+/208401) that refactors things a little so the watcher is set up more reliably, but it doesn't yet handle what's happening here. Hoping to make some more progress this week though (although it may mean making some sync code async and I'm not certain if that will be straight-forward yet).

**Comment by DanTup** [comment]
Actually, I think this is a different issue. While trying to repro this I noticed something strange..

- run `flutter create -t skeleton my_project`
- note that the output contains `Running "flutter pub get" in my_project...`
- look in `.dart_tool/` and notice there is no `flutter_gen` folder (this is why the analysis errors occur)

But note if you manually run `flutter pub get` the `.dart_tool/flutter_gen` folder is created. Also, if you run `flutter analyze` the folder gets created.

So I think the issue here is that when `flutter create` fetches packages, it's not doing the same thing as when it's run manually or when it's (presumably implicitly) run by `flutter analyze`. I'll have a look and see if I can understand why.

**Comment by DanTup** [comment]
Ok, figured out what's happening...

When you manually run `flutter pub get` it triggers creation of `.dart_tool/flutter_gen` by calling `generateLocalizationsSyntheticPackage` inside `_runPubGet` here:

https://github.com/flutter/flutter/blob/9e88fe328efcf42d3037a965b39269f0805cd4ce/packages/flutter_tools/lib/src/commands/packages.dart#L134

When you run `flutter analyze`, it triggers the same code inside `FlutterCommand.verifyThenRunCommand` here:

https://github.com/flutter/flutter/blob/9e88fe328efcf42d3037a965b39269f0805cd4ce/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1265

However, when running `flutter create`, this code is never run. It goes `pub get` from here, but never calls the code to generate the localisations:

https://github.com/flutter/flutter/blob/9e88fe328efcf42d3037a965b39269f0805cd4ce/packages/flutter_tools/lib/src/commands/create_base.dart#L458

It does pass `generateSyntheticPackage: true,` to the call to `pub get` but that controls only _injecting_ the package into _package_config.json` and not the actual creation of the project that it references.

I think the fix is to call `generateLocalizationsSyntheticPackage` around line 458 above so I'll do some testing and file a PR.

**Comment by DanTup** [comment]
PR at https://github.com/flutter/flutter/pull/92975.

**Comment by Hixie** [comment]
Is it bad that I've never heard of `.dart_tool/flutter_gen` before...

**Comment by DanTup** [comment]
Nor had I until the race condition came up 😄

It's also slightly unfortunate that there's an unrelated published Pub package of the same name https://pub.dev/packages/flutter_gen (and I don't know what happens if you need/try to have both).
