### ISSUE TITLE
[Cupertino] Add new iOS 15 button styles for `CupertinoButton`

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#92525]
Currently, there are only two styles aka button [configurations](URLhttps://developer.apple.com/documentation/uikit/uibutton/configuration)  for `CupertinoButton`
Plain [CupertinoButton](https://master-api.flutter.dev/flutter/cupertino/CupertinoButton/CupertinoButton.html) & [CupertinoButton.filled](https://master-api.flutter.dev/flutter/cupertino/CupertinoButton/CupertinoButton.filled.html)

Add following new button configurations  
[Gray](https://developer.apple.com/documentation/uikit/uibutton/configuration/3750787-gray)
[Tinted](https://developer.apple.com/documentation/uikit/uibutton/configuration/3750798-tinted)

**Comment by jmagman** [comment]
> Do you think adding more constructors is the way to go or create separate buttons since there are more for them (similar to material buttons)?

I'm not very familiar with the framework patterns. @goderbauer do you have an opinion on this?

**Comment by tmaihoff** [comment]
Is there an update?

**Comment by kerberjg** [comment]
I was working on them recently and just happened to stumble on this issue just now, I'm happy to contribute my implementation 😊 

I made sure to follow the iOS guidelines on this, plus added the "extra large" style for legacy reasons (it's the current default style in Flutter)

<img width="915" alt="image" src="https://github.com/user-attachments/assets/8858ffbe-b611-4637-b8e1-21088a501d31">

I need to tweak the spacing a little, but they're basically done

**Comment by kerberjg** [comment]
Comparing with iOS guidelines (overlay image) I arrived to this:

<img width="595" alt="image" src="https://github.com/user-attachments/assets/750c3f33-985e-444b-beea-8e156e2d2bf3">

The sizes/rounding are correct, there's a bit of an issue with the internal spacing, but it's marginal and I sank enough hours into trying to fix it (fruitlessly).
I'll be cleaning up the code now and opening a PR.

@jmagman I'll be going with the "separate constructors" approach for plain/tinted/filled (and gray will simply be tinted + `color: CupertinoColors.systemGray`) to avoid breaking existing code.

I'll define a new enum for size, because otherwise I'd have 9-12 constructors, which is crazy.

Personally I'd prefer if both size and style were enums, but this is the best I can do at the moment.

**Comment by TahaTesser** [comment]
cc: @MitchellGoodwin @victorsanni

**Comment by bernaferrari** [comment]
Maybe CupertinoButton could support spacing from @TahaTesser so user has freedom? Just an idea.
