### ISSUE TITLE
[Proposal] Allow possibility to maintain focus on TextField

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#92541]
## Use case

See #92079.

## Proposal

Allow the possibility to maintain focus on a TextField.
It should be disabled by default according to the material design specification but can be enabled through a property.

#### Note: 
If this is already possible, kindly point me to the documentation or a working example. 
Thank you

------
/cc @danagbemava-nc

**Comment by YowFung** [comment]
@HansMuller @darshankawar 
I found that the `TextField` widget can keep its focus status now. Has this proposal been passed? If so, can you tell me which parameter can control this status?

**Comment by HansMuller** [comment]
@justinmc, @gspencergoog - was the regression reported in #92079 fixed?

**Comment by gspencergoog** [comment]
@HansMuller Do you mean the cursor height regression? 

> I found that the TextField widget can keep its focus status now.

Unless I missed something that has changed, this is probably a regression: the focus should be removed from the text field when clicking outside of it. @justinmc has anything changed with `FocusTrap`?

**Comment by justinmc** [comment]
This is a valid issue (kind of overlapping with https://github.com/flutter/flutter/issues/86972, but I think it's ok to keep this open).  Here's the current situation.

### Desired behavior

  * On web, tapping on a blank area outside of a text field should remove the focus.  Tabbing from there should resume the tab order at the beginning.
  * On all non-web platforms, tapping on a blank area should not remove focus.
  * On all platforms, it should be possible to build a button that does not steal the focus from a text field when tapped.

### Current Flutter behavior

  * On all platforms except mobile, tapping on a blank area removes focus from a text field.
    - This includes mobile web, incorrectly.
  * It's not possible to build a button that doesn't steal focus due to how FocusTrap works.

### How can we fix this?

We need to refactor [FocusTrap](https://github.com/flutter/flutter/blob/9cfaabaed09e1c6606c9148b0f716a78146ec4e6/packages/flutter/lib/src/widgets/routes.dart#L2092).  I made an attempt at that (https://github.com/flutter/flutter/pull/99434), but I ran into test failures due to overlapping gesture detectors, and I haven't been able to figure out a way to fix it.  I hope to come back to it, but if anyone else has a solution it would be most welcome!

**Comment by YowFung** [comment]
> **Current Flutter behavior**
> - On all platforms except mobile, tapping on a blank area removes focus from a text field.
>   - This includes mobile web, incorrectly.
> - It's not possible to build a button that doesn't steal focus due to how FocusTrap works.

**My current situation:**
- Using flutter version `2.10.3 stable`.
- On the `macOS` platform.
- Tapping on a blank area doesn't remove focus from a `TextField`.

**My desired behavior:**
- The `TextField` has a parameter that can control the focus behavior(keep or remove focus when clicking outside of it).

**Comment by gspencergoog** [comment]
This should now be possible using the `TextFieldTapRegion` widget to indicate that a control is considered part of the same tap region group as the text field. See the PR: https://github.com/flutter/flutter/pull/107262
