### ISSUE TITLE
[webview_flutter]  JavascriptChannel does not work in release apk

### ISSUE THREAD

**Issue by fg2q1q3q** [flutter/flutter#92548]
I'm using `webview_flutter: ^ 2.1.2`. I discovered  the `JavascriptChannel` can be used normally in debug mode (can show toast), but it is doesn't work after packaging with the `flutter build apk` command ( can not show toast in release apk )

My working environment：
> Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (11 days ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

My Flutter code

```dart
WebView(
        initialUrl: 'file:///android_asset/flutter_assets/assets/file/test.html',
        javascriptMode: JavascriptMode.unrestricted,
        javascriptChannels: <JavascriptChannel>{
          JavascriptChannel(
              name: 'testClick',
              onMessageReceived: (JavascriptMessage message) {
                String msg=message.message;
                Fluttertoast.showToast(msg: msg);
              }),
        }.toSet(),
      )
```

My Html code

```html
<html>
   <head>
        <title>测试页面</title>
   </head>
   <body>
        <p><button onclick="testClick.postMessage('1,2,3')">测试按钮</button></p>
   </body>
</html>
```

**Comment by weifucheng1102** [comment]
I also encountered this problem, but when I planned to change the plug-in, after introducing the 'flutter_inappwebview' plug-in in pubspec.yaml, the problem was solved. After deleting the 'flutter_inappwebview' plug-in, the problem appeared again. I don't know why. Maybe 'flutter_inappwebview' plug-in has some configuration files that affect this problem

**Comment by fg2q1q3q** [comment]
@danagbemava-nc @weifucheng1102 

After repeated testing, I finally found that this problem is caused by android_intent_plus. Once `android_intent_plus` is introduced into the project, the release version of `javascriptChannels` will fail

The reproduction method is also very simple, just add `webview_flutter: ^2.3.1`and `android_intent_plus: ^3.0.1`to the `pubspec.yaml` file, and then `pub get`.

This error is bound to appear

**Comment by wsmPanda** [comment]
> I also encountered this problem, but when I planned to change the plug-in, after introducing the 'flutter_inappwebview' plug-in in pubspec.yaml, the problem was solved. After deleting the 'flutter_inappwebview' plug-in, the problem appeared again. I don't know why. Maybe 'flutter_inappwebview' plug-in has some configuration files that affect this problem

that's useful,but flutter_inappwebview case some other trouble on ios.

**Comment by danagbemava-nc** [comment]
Hi @fg2q1q3q, if the introduction of `android_intent_plus` is what causes the issue then you may need to file an issue with 
the `android_intent_plus` repo so they're aware and can take the necessary action.

**Comment by alexbatalov** [comment]
Hey guys, I’ve made some research in response to fluttercommunity/plus_plugins#630. This issue has nothing to do with plugins mentioned, but instead a part of a deeper problem within build system, I’m not sure if that’s Flutter, agp, or gradle.

First things first, this problem surfaced in `webview_flutter` when used together with `android_intent_plus`. For some reason build system setup incorrect build path, which prevents inclusion of default `proguard-android.txt`. This file contains many useful things, one of them is an exception for `JavascriptInterface`. This annotation is used in `webview_flutter` to prevent obfuscation of `JavaScriptChannel.postMessage` method, which is exposed to JavaScript and should be available through reflection. Because you don’t have this exception in the final app, this method will be obfuscated and therefore it cannot be called from JavaScript.

Run this command with `android_intent_plus` included in `pubspec.yaml` and then without it.
```console
$ flutter build apk --release
```

Open `build/app/outputs/mapping/release/configuration.txt`, which is a final R8 configuration. In good builds you’ll find contents of `proguard-android.txt` (together with Flutter-specific rules), which keeps `JavascriptInterface`-annotated methods. The other interesting file is 
`build/app/outputs/mapping/release/mapping.txt`, which contains a map of obfuscated identifiers. In good builds this file will contain special handling for `postMessage` method.

Luckily, Flutter also includes app-specific R8 rules when they are provided. Create `android/app/proguard-rules.pro`. At minimum you need to have a rule for `JavascriptInterface`, but I recommend to copy entire `proguard-android.txt`, given the fact that you don’t have these rules.

```
# Preserve annotated Javascript interface methods.
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
```

---

Now let’s get back to the problem itself. Something bad happens in the build system when you have a plugin who’s name appears before `app` (alphabetically-wise). Sounds crazy, huh? Here is how you can check it. Setup a new app with a couple of plugins. One of the plugin must be above `app`, the other one below.

```console
$ flutter create --platforms android --android-language java sample
$ cd sample
$ mkdir packages
$ cd packages
$ flutter create --platforms android --android-language java --template plugin aaa
$ flutter create --platforms android --android-language java --template plugin zzz
```

Open up `android/app/build.gradle`, add the following line to the top:

```groovy
println "buildDir: " + project.buildDir
```

Now, build a reference app without plugins:

```console
$ flutter build apk --release
buildDir: sample/build/app
```
Everything’s good so far, `buildDir` is exactly what was expected.

Now, let’s first add `zzz` plugin to app, in your `pubspec.yaml`:

```yaml
dependencies:
  flutter:
    sdk: flutter
  zzz:
    path: packages/zzz
```

Then:
```console
$ flutter clean
$ flutter build apk --release
buildDir: sample/build/app
```

The `buildDir` is correct again.

Now replace `zzz` plugin with `aaa`:

```yaml
dependencies:
  flutter:
    sdk: flutter
  aaa:
    path: packages/aaa
```

The commands are the same:

```console
$ flutter clean
$ flutter build apk --release
buildDir: sample/android/app/build
```

What the hell happened? The `buildDir` suddenly changed to `sample/android/app/build` instead of `sample/build/app`. Some build artifacts of `app` went into this unusual directory, but not all of them. This bad path is not canonical, you cannot get rid of it with `flutter clean`, it’s not gitignored by default as `build/` is.

Now let’s get back to the original problem with `webview_flutter` and `android_intent_plus`. As I’ve already explained this is a problem with R8 rules. In the same sample app add the following line to `android/app/build.gradle` just after applying plugin:

```groovy
apply plugin: 'com.android.application'
println "proguardRules: " + project.android.getDefaultProguardFile("proguard-android.txt")
```

And build:
```console
$ flutter clean
$ flutter build apk --release
buildDir: sample/android/app/build
proguardRules: sample/android/app/build/intermediates/proguard-files/proguard-android.txt-4.1.0
```

Looks good, but it’s not, because for some reason this artifact is placed in canonical path `sample/build/app/intermediates/proguard-files/proguard-android.txt-4.1.0`, but gradle says it should be in that bad dir.

After some further research I’ve found that you don’t need a plugin at all to encounter this problem. Remove dependencies from `pubspec.yaml`, and this time open `android/settings.gradle`, add the following line:

```groovy
include ':app'
include ':zzz'
```

Then build - your `buildDir` is good. Now try the same with:

```groovy
include ':app'
include ‘:aaa’
```

Your `buildDir` is bad.

That leads me to the conclusion, that the problem is with agp or gradle file resolver, I didn’t investigate further. Hope this helps.

**Comment by alexbatalov** [comment]
@danagbemava-nc @fg2q1q3q @weifucheng1102 
I've also checked why `flutter_inappwebview` works. It contains their own R8 configuration [proguard-rules.pro](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/android/proguard-rules.pro), which has a rule for `JavascriptInterface`. When used together with `android_intent_plus` (or any other above `app` plugin), you still don't have default R8 rules, but at least there is an exception for `JavascriptInterface`, which is needed for Java/JavaScript interop.

**Comment by fg2q1q3q** [comment]
Thanks for the answer, it's very clear

**Comment by fg2q1q3q** [comment]
@danagbemava-nc Considering the universality of js interaction, I think the priority of this bug should be increased, and it exists on all devices

**Comment by danagbemava-nc** [comment]
Hi @fg2q1q3q, I am curious as to what happens when you add the rule for `JavascriptInterface` in your own `proguard-rules.pro`. 

Can you try that out and let me know if you still experience this issue?

**Comment by fg2q1q3q** [comment]
@danagbemava-nc Yes, when I added the `proguard-rules.pro` file and inserted the following code in it, 
```java
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
```

and then run the release app, everything was normal.

![Details](https://gitee.com/yue7/ZxlPub/raw/master/img/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20211208185406.png)

**Comment by stuartmorgan** [comment]
@blasten Can someone on your team investigate the [build directory issue described above](https://github.com/flutter/flutter/issues/92548#issuecomment-984148512)?

**Comment by A5H1Q** [comment]
Any updates on this? Does this issue still exist in current `webview_flutter` Implementations?

**Comment by mossmana** [comment]
This seems to be fixed with the latest version of Flutter and webview_flutter.  I modified the sample code to use the latest:

`import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

const html = '''
<html>
   <head>
        <title>测试页面</title>
   </head>
   <body>
        <p><button onclick="testClick.postMessage('1,2,3')">测试按钮</button></p>
   </body>
</html>
''';
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const WebViewPage('Some Title'),
    );
  }
}

class WebViewPage extends StatefulWidget {
  final String title;

  const WebViewPage(this.title, {super.key});

  @override
  WebViewPageState createState() => WebViewPageState();
}

class WebViewPageState extends State<WebViewPage> {
  late String title;
  late WebViewController controller;

  @override
  void initState() {
    super.initState();
    title = widget.title;
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.dataFromString(html,
          mimeType: 'text/html', encoding: Encoding.getByName('utf-8')));
    controller.addJavaScriptChannel('testClick',
        onMessageReceived: (JavaScriptMessage message) {
      String msg = message.message;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg)));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        // backgroundColor: Colors.white,
        title: Text(title),
      ),
      body: WebViewWidget(controller: controller),
    );
  }
}
`

and updated the `settings.gradle` per https://github.com/flutter/flutter/issues/92548#issuecomment-984148512

then ran
`flutter run --release`

**Comment by mossmana** [comment]
I'm closing this issue for now as it appears to be unreproducible with the latest Flutter and webview_flutter. If you find that this  issue is still reproducible, please provide exact reproduction steps.
