### ISSUE TITLE
Presubmit hook takes a long time in clang-tidy

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#92584]
The presubmit hooks for the engine repo are taking minutes to execute on my machine even with small diffs.  In Activity Monitor you can see `clang-tidy` taking up all the CPU.  Executing `./ci/format.sh` takes a couple of seconds on the same diff however.

Probably the logic to decide what to format is incorrect.

platform: macOS

cc @zanderso

**Comment by chinmaygarde** [comment]
Is there a way to get verbose logs on the number of files passed to `clang-tidy` to ... tidy-fy. 

A data point, I have defaulted to using --no-verify always since my editor has clang-tidy and clang-format on save and the CI will perform these checks anyway. So, if you are editing a large number of files on a regular basis, the same workflow might make sense. But, in this case, we should definitely verify that we are not running checks on unecessary file.

**Comment by jmagman** [comment]
I'm pretty sure this will be fixed by https://github.com/flutter/engine/pull/29640, which skips expensive path equivalency checks for `third_party` files that aren't linted anyway.  That change reduced `--lint-all` on my machine from 11:54 minutes to 2:28.

**Comment by jmagman** [comment]
https://github.com/flutter/engine/pull/29640 has merged, I'll close for now.  Please reopen if you're still seeing excessive slowness.
