### ISSUE TITLE
Focus changed after screen state changes

### ISSUE THREAD

**Issue by HectorUgo** [flutter/flutter#92667]
Screen refreshes when state changes, disrupting talkback users workflow.

**Comment by nokia6290** [comment]
A guess,
have you perhaps written any functions inside the build? I.e. below build line? Because every time the state changes which rebuilds the whole UI it automatically invokes the function call again and again because the state rebuilds everything.
Functions should be outisde build scope.

Just a guess but yes include more context your problem

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
