### ISSUE TITLE
[macOS] Flutter process appears to hang

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#92673]
### Steps to reproduce

1. Run the following app:

   ```dart
   import 'package:flutter/widgets.dart';

   void main() async {
     runApp(const ColoredBox(color: Color(0xffff0000)));
     runApp(const LimitedBox());
   }
   ```
2. Then once the app has launched, try to resize the window.

### Expected behavior

You expect:
1. The red box to immediately be replaced with nothing (a grey background)
2. Upon resize, the window to be able to be resized, still just showing a grey background.

### Actual behavior

1. The red box remains in the window and is _not_ replaced with nothing (a grey background)
2. When you try to resize the window, the Flutter process seems to hang.  When you move the cursor over the window, it gives the MacOS spinning beach ball.

### Other info

1. This setup has been created in https://github.com/tvolkert/flutter_desktop_bug, so you can clone that repo to reproduce this bug.
2. Flutter version info:
   ```
   [✓] Flutter (Channel master, 2.6.0-12.0.pre.435, on macOS 11.6 20G165 darwin-x64, locale en-US)
       • Flutter version 2.6.0-12.0.pre.435 at /Users/tvolkert/project/flutter/flutter
       • Upstream repository git@github.com:tvolkert/flutter.git
       • Framework revision d62f75dde1 (7 days ago), 2021-10-21 01:41:33 -0400
       • Engine revision ce74cbc3ce
       • Dart version 2.15.0 (build 2.15.0-233.0.dev)
   ```
3. The app works as expected if you replace the second line with a different color.  e.g.
   ```dart
     runApp(const ColoredBox(color: Color(0xff00ff00)));
   ```

**Comment by cbracken** [comment]
We discussed this a bit over chat and this seems likely to be an issue in the macos embedder integration with the compositor where we're incorrectly handling the case where we post a frame where we haven't pushed any layers. 

I distinctly remember the case a couple years ago where we had a bug in flow caused by the same assumption -- that we will never have an empty list of layers, so I can very much imagine us having made a similar assumption here. There are a couple places where behaviour differs when no layers have been pushed -- e.g. `FlutterMetalCompositor::Present` and those seem like a good place to start digging into this.

If this does turn out to be so specific that it only occurs when `runApp` has been invoked twice in a row, I believe this could be removed from the stable blockers list.

**Comment by tvolkert** [comment]
The runApp twice in a row was just to get a minimal repro case.  The original repro was a case where I had an animation, and the last frame in the animation didn't paint anything.

**Comment by knopp** [comment]
Sorry, missed this.

Indeed the issue here is that `FlutterResizeSynchronizer` assumes that once it gets a frame it will keep getting it until application terminates. Definitely an oversight. `FlutterEngine` gets notifies when there is no flutter content, it needs to pass it to through renderer and view to `FlutterResizeSynchronizer` which should unblock and not block until there is content.
