### ISSUE TITLE
Do not attempt to raster cache leafs if OpacityLayer is already raster caching

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#92725]
Since the OpacityLayer is unconditionally raster caching, its descendent leaves should just never attempt to raster cache.

could be done by nulling out the `raster_cache` property of `context` here: https://github.com/flutter/engine/blob/48345578393bae7f386fc7cfcc407a1359bcda33/flow/layers/opacity_layer.cc#L53

**Comment by chinmaygarde** [comment]
cc @flar

**Comment by dnfield** [comment]
In traces on lo end devices, we can see the time spent in constructing the CTM, creating and storing the key, and updating it take non-trivial amounts of time.

I agree that it'd be great to keep statistics for this, but even in the case where the opacity cache fails due to surface size we'd still have wasted time on doing cache checking logic during the opacity preroll which would just have to be repeated again in the preroll of the picture once we get back to it, right?

**Comment by flar** [comment]
I'd like to see those traces. If a device was so low end to really notice those operations then I would find it hard to believe that it could actually maintain a decent frame rate. These are operations that occur many times over in every frame. They are the bread and butter of rendering.

**Comment by dnfield** [comment]
It is really bad at maintaining a decent frame rate. 

This optimization would likely not help a lot, but could help some.  @goderbauer may still have traces

**Comment by flar** [comment]
The children actually populating their caches would cause a huge issue.

What I'm saying is that if we prevent them from populating, then it would be nice if they still did the bookkeeping of "I'm still here" anyway. The cost of that shouldn't show up on any traces because that situation doesn't exist. The current code not only does the bookkeeping, it also allocates a cache image and renders to it. That latter part definitely would interfere with frame rates.

**Comment by dnfield** [comment]
My recollection is the frame that caused us to think about this had something like 15 DisplayLists in total. Something like 11 or 12 of them were nested under an `OpacityLayer`.

Each DisplayList needed somewhere around .1-.2ms to check for whether it should be cached. That adds up to 1-2+ms for the whole frame. This frame was _badly_ over budget anyway (100s of ms), but even if we tame it down to something more reasonable, that 1-2ms is a significant portion of budget. The children were definitely not trying to rasterize, but they did have to go through a walk down the `RasterCache::Prepare`.

**Comment by flar** [comment]
I just saw we use MatrixDecomposition which seems like an amazing amount of computation for something that I'm not sure what value it adds. Would that overhead go away if we just skipped that step?

**Comment by flar** [comment]
It looks like the only results that we care about are whether it is singular which is a fast computation on SkMatrix, but requires a full 4x4 decomposition and analysis if run through MatrixDecomposition.

**Comment by flar** [comment]
I filed https://github.com/flutter/flutter/issues/92962

**Comment by dnfield** [comment]
Some more details:the bad frame looks like this:

![image](https://user-images.githubusercontent.com/8620741/140262508-fe2eeffc-a5d2-489a-9864-0609343d4b31.png)

The whole frame is taking forever and a day to rasterize (>200ms). We can improve that substantially (to closer to 100ms), but even when we improve it it will still be left with creating/updating cache keys for 23 display lists under the OpacityLayer that will definitely never be raster cacheable. On the device under test, it's taking just over 2ms to do the prerolling for all the child layers.

**Comment by flar** [comment]
See also: https://github.com/flutter/flutter/issues/93047

**Comment by dnfield** [comment]
I'm going to close this in favor of that issue. Once that rolls through we can re-evaluate the internal customer traces and see if any further action is warranted.
