### ISSUE TITLE
Issue with renaming files to/from capital letters in AS2020.3.1 (in a Flutter project) 

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#92759]
When renaming a project directory from `Services` to `services`, the importing referencing to that file, did not change the capital letter inside the code. Causing "Lint" to mark fail with redliners.

![image](https://user-images.githubusercontent.com/11217296/139538730-fef89a98-338e-4ec1-94cd-498508df75fa.png)

(PS! The incident may be connected to Android Studio renaming directories, but I have only experienced theese incidents in Flutter projects).

**Comment by or-adar** [comment]
AFAIK, renaming a folder in a Flutter project using IntelliJ/Android Studio (which is actually based on IntelliJ)
doesn't affect imports.
But until it'll be supported, you can create a new directory, giving it the name you wanted, and than move all relevant files.
Since there is support for moving files on IntelliJ/Android Studio, all relevant imports will get changed.
But pleas note, that It'll work only for moving files! 
If you need to refactor a directory containing other directories you'll need to reflect all relevant paths under the old directory over to the new directory and move files as necessary.
For example:
```
Reflect all paths (if exists) under the new directory "services" on the new directory "Services".
.
├── services
│   ├── nested_directory
│   │   └── file_to_move.dart
│   └── file_to_move.dart
└── Services
    └── nested_directory
```

```
Move any necessary file from "services" to the new directory "Services" under the corresponding path.
.
├── services
│   └── nested_directory
└── Services
│   └── nested_directory
│   │   └── file_to_move.dart
│   └── file_to_move.dart
```

This is a bit tedious, but until renaming folders on IntelliJ/Android Studio will be supported, moving files is not that bad of an option.

**Comment by RoarGronmo** [comment]
Thanx for answer, I have experienced in older versions (3yrs, then in a java project) trouble if you move directories (directory trees) or multiselecting several files and move them.

**Comment by maheshmnj** [comment]
Hi @RoarGronmo, This doesn't look like flutter specific issue but rather the flutter plugin for Android Studio, I would advise you to please file the issue in the dedicated repo https://github.com/flutter/flutter-intellij.
Closing, as this isn't an issue with flutter. If you disagree feel free to write in the comments and I will reopen it. 

Thank you.
