### ISSUE TITLE
Flutter upgrade

### ISSUE THREAD

**Issue by walidalyosef** [flutter/flutter#92790]
I am trying to upgrade from Syria...  but getting this, can you please help?
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/walid/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/walid/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/walid/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by darshankawar** [comment]
@walidalyosef 
It could be due to the network you are using and could be a regional issue. I think you'll need to use another IP or switch to VPN or other settings and see if it helps.

Also, it seems you are using `snap` to install flutter which is 3rd party. Can you directly try to install without it as mentioned in the document and try again ?

**Comment by walidalyosef** [comment]
Thanks, you are right. It is working now without any change. It considered connection speed too.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darshankawar** [comment]
Closing as resolved based on above comment.
