### ISSUE TITLE
Mac_staging plugin_test_ios not passing $flutter/devicelab_osx_sdk property

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92838]
Example:
https://ci.chromium.org/p/flutter/builders/staging/Mac_staging%20plugin_test_ios/685

**Comment by keyonghan** [comment]
This test is supposed to run on Host only test bed without devices.
However Mac/ios testbeds share same `device_type:none`.
We need to use `device_os:none` as the dimension to enforce testbeds.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/19684 adds `device_os:none` for the builder config, but we are missing the dimension in bots config: https://chromium-swarm.appspot.com/task?id=56ff8c0d100c0910&o=true&w=true

We need to add the dimension to bot config so that the builder config can be recognized.

**Comment by keyonghan** [comment]
The [bot config support](https://chrome-internal-review.googlesource.com/c/infradata/config/+/4230245) was submitted, and test is passing: https://ci.chromium.org/p/flutter/builders/staging/Mac_staging%20plugin_test_ios
