### ISSUE TITLE
[add-to-app] iOS 14+ bluetooth keyboard cannot input text

### ISSUE THREAD

**Issue by pdsliuzhen** [flutter/flutter#92891]
iOS 15 or iOS 14.7 flutter 2.5  bluetooth keyboard can not input text in TextField；But flutter 1.22.6 is ok;

**Comment by pdsliuzhen** [comment]
not only on ipad but ios simulator or device still has this issue. flutter2.5 and ios system <14 is ok;

**Comment by mamuseferha** [comment]
Hi @pdsliuzhen 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/76497.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pdsliuzhen** [comment]
hi @mamuseferha  i use flutter module , and embed to ios project ; flutter run is ok; ios project run is not ok; is not same at  #76497.

**Comment by pdsliuzhen** [comment]
this is a flutter module which embed in ios native project ,flutter run is ok, but run ios native project bluetooth keyboard input is not ok;

**Comment by mamuseferha** [comment]
@pdsliuzhen I’m unable to reproduce the issue to pinpoint the cause, I'll be labelling it for further investigation.

**Comment by pdsliuzhen** [comment]
@mamuseferha thank you. I'm going to compare the ios project files inside the ios folder with the ios project files outside. See if you can find something.

**Comment by red282** [comment]
same issue here. and we use flutter module too.

**Comment by closer27** [comment]
I have met the same issue. This is so serious issue for me.
It doesn't occur under v2.5 of flutter.
It doesn't occur in a flutter app, I'm using flutter as module (the way for adding Flutter to existing app)

**Comment by millie-molly** [comment]
Is it still working?

**Comment by chengliuAres** [comment]
Is there any progress on this?

**Comment by SoolyChristy** [comment]
any update ?

**Comment by hellohuanlin** [comment]
@SoolyChristy Hi, could you post some example code with repro steps and I can look into it?

**Comment by wanjm** [comment]
https://github.com/flutter/flutter/issues/100041 is almost the same problem i come accross,

**Comment by Nikzed** [comment]
is it still under development?

**Comment by gnprice** [comment]
It looks like nobody has yet been able to provide sample code to reproduce this issue. It's unlikely anyone will be able to make progress on the issue without a repro.

For anyone who's running into the issue, a very helpful contribution would be to provide a repro case:
https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases
That will make the issue much more likely to get fixed.

---

Separately, it looks like all the reports of this are in an add-to-app scenario. Adding a label and retitling to help make that clear.

If anyone is seeing a version of this issue where they're *not* adding Flutter to an existing non-Flutter app, please mention it. Better yet, please file a fresh issue with all the information in the issue template, including a reproduction recipe, and then mention that issue here.
