### ISSUE TITLE
Add PodFile.lock be added to the template gitignore

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9299]
I notice a bunch of PodFile.lock and xcconfigs in posse commits:
https://github.com/flutter/posse_gallery/pull/2/files

They're just following from our template.  Presumably our `flutter create` template should include a .gitignore for podfile.lock?  (I highlight this not so we pick on their commit, but rather learn from it.)

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/ios.tmpl/.gitignore

@mit-mit?

**Comment by Hixie** [comment]
we should add a test that verifies that the git status is clean after "flutter create && flutter run"

**Comment by jason-simmons** [comment]
flutter_tools is also generating some source files that show up as untracked files in git:
    examples/flutter_gallery/android/app/src/main/java/
    examples/flutter_gallery/ios/Runner/PluginRegistry.h
    examples/flutter_gallery/ios/Runner/PluginRegistry.m

@jakobr-google should these files be gitignored?  or can they be moved outside the app's source tree and into a build output directory?

**Comment by mit-mit** [comment]
@jason-simmons we'll answer your question over in https://github.com/flutter/flutter/issues/9085, and let this bug track just the PodFile.lock question.

**Comment by mit-mit** [comment]
Closing

**Comment by eseidelGoogle** [comment]
@mit-mit I'm not sure I believe that guide.  The PodFile.lock has absolute paths in it:
https://github.com/flutter/posse_gallery/pull/2/files#diff-cf4077ccb416bea5c1b3056a5a7c5299

Are we doing something wrong?  Clearly we don't want to check in absolute paths?

**Comment by mit-mit** [comment]
That guide is the official cocoapods guide...

Here is another one:
http://stackoverflow.com/questions/9446644/what-goes-into-your-gitignore-if-youre-using-cocoapods

_"The Podfile.lock **must** always be under source control."_
_"source: I’m a member of the CocoaPods core team, like @alloy"_


However, the same stackoverflow posts also says that pods with a path dependency should be kept in source control.

I suspect the issue here is our path dependency on engine? cc @jakobr-google

**Comment by alloy** [comment]
Indeed, CocoaPods will write relative paths to [the lockfile](https://github.com/artsy/emission/blob/06af588a19be96863eb9aa2a9f19d6f258c985f9/Example/Podfile.lock#L85-L86) if relative paths are used in [your Podfile](https://github.com/artsy/emission/blob/06af588a19be96863eb9aa2a9f19d6f258c985f9/Example/Podfile#L8-L9), so if you check in the code with your project (or otherwise guarantee the code to always be in the same relative location) this should work.

**Comment by mit-mit** [comment]
Thanks for the quick reply @alloy :-)

**Comment by mit-mit** [comment]
Closing issue

**Comment by jmagman** [comment]
The Podfile.lock no longer has absolute paths in it as of https://github.com/flutter/flutter/pull/42029.  Reopening.

**Comment by jmagman** [comment]
Not sure when this happened, but Podfile.lock is no longer excluded from the gitignore.  I just created a new app, `git init`ed a new project, ran `flutter build ios` and `flutter build macos` and now I see a `ios/Podfile.lock` and `macos/Podfile.lock` as an untracked (not ignored) file.
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	ios/Podfile
	ios/Podfile.lock
	macos/Podfile
	macos/Podfile.lock
```
Closing.

**Comment by tapizquent** [comment]
I have noticed that this files along with `ios/Runner.xcodeproj/project.pbxproj` get updated/changed when multiple people are working in the same project. 

If I understand right, should this not be included in `.gitignore`? How do we handle the changes that happen in those files?

**Comment by jmagman** [comment]
> I have noticed that this files along with ios/Runner.xcodeproj/project.pbxproj get updated/changed when multiple people are working in the same project.

`ios/Runner.xcodeproj/project.pbxproj` is periodically changed by Flutter to fix various behavior changes in Xcode.  You should check in those changes.

`Podfile.lock` should not changes between different user runs any more than `pubspec.lock`.  Avoid running `pod update ` in the `ios` directory (unless you are trying to update your dependencies).  Also all your contributors should be on the same version of CocoaPods and Flutter.
