### ISSUE TITLE
Cache metric regressions on engine roll

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#93067]
Regressions: https://flutter-flutter-perf.skia.org/t/?begin=1635946753&end=1635946755&subset=all
Affected roll: https://github.com/flutter/flutter/pull/92977

The picture cache count/memory metrics [increased](https://flutter-flutter-perf.skia.org/e/?begin=1635879121&end=1635970684&keys=X6767fa4dc08a3f0feb4594194292c5d9&num_commits=50&request_type=1&xbaroffset=26425) on 4 tests and [decreased](https://flutter-flutter-perf.skia.org/e/?begin=1635879121&end=1635970684&keys=X9ec5b83dc706748c8dc9b64eb9c47d81&num_commits=50&request_type=1&xbaroffset=26425) on 12.

This is likely due to raster cache logic changes in the [partial repaint](https://github.com/flutter/flutter/pull/92977) change, but I'm unsure if these metric changes are expected/reasonable or not.

**Comment by iskakaushik** [comment]
On further debugging, i've identified an issue with the raster cache behavior, specifically the computation of the cache key for picture and display list layer. During the prepare phase, we don't take into account `SUPPORT_FRACTIONAL_TRANSLATION` when computing the translation matrix, which results in us not using the cached image when Drawing. See: https://github.com/flutter/engine/blob/master/flow/layers/picture_layer.cc#L138 and https://github.com/flutter/engine/blob/master/flow/raster_cache.cc#L345. This means that all the Images would be evicted as they wouldn't be used due to cache misses.

After https://github.com/flutter/engine/commit/4dbdc084442519992673917df3474a3220226c13, we have a new `Touch` method which would mark the image as used, this means that we wouldn't evict the image after the frame is rendered. Hence we see the increment in usage of cache. There are two things that need to be addressed:

1. Fix the cache key computation during prepare and touch phase to account for fractional translation.
2. Touch needs to take into account offset for cache-key computation.


@flar and @knopp for thoughts.

**Comment by iskakaushik** [comment]
Update: looks like the raster cache key doesn't take into account the translation components of the matrix, so please ignore the previous comment. Continuing investigation.

**Comment by flar** [comment]
I had the same reaction when I was diagnosing cache failures on perspective issues for https://github.com/flutter/flutter/issues/92993 until I realized that the cache doesn't use the translation components.

Should this be tracked in https://github.com/flutter/flutter/issues/91855 ?
