### ISSUE TITLE
TextField Glitch - autofillHints

### ISSUE THREAD

**Issue by Aristidios** [flutter/flutter#93072]
I'm trying to use a  Flutter `TextField()`  with autofillHints on my Flutter Web App but when running it inside an iOS Browsers :

- It keeps on popping up even if i click **outside of TextField** :  *image bellow shows TextFormField but issue concerns TextField*

[![GIF iOS WEB KEYBOARD ISSUE][1]][1]

*Here is a stripped to its minimum code sample to reproduce the issue that only happens with TextField - issue has been fixed for `TextFromField`*

```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: ThemeMode.system,
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: TextField(
              autofocus: false,
              keyboardType: TextInputType.emailAddress,
              autofillHints: [AutofillHints.email],
            ),
          ),
        ),
      ),
      title: 'Flutter Test',
    );
  }
}
```

Removing autofillHints fixes the issue

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.418, on macOS 12.0.1 21A559 darwin-arm, locale
    fr-FR)
    • Flutter version 2.3.0-17.0.pre.418 at /Users/user/FlutterSDK/flutter
    • Upstream repository https://github.com/Aristidios/flutter.git
    • Framework revision a1a360bf13 (5 months ago), 2021-06-21 16:24:02 -0500
    • Engine revision 9520bb15b3
    • Dart version 2.14.0 (build 2.14.0-228.0.dev)
```
  [1]: https://i.stack.imgur.com/3Ny59.gif

**Comment by mdebbar** [comment]
Could you also add the output of `flutter doctor -v` ?

**Comment by Aristidios** [comment]
@mdebbar Done : )

**Comment by ditman** [comment]
`Framework revision a1a360bf13 (5 months ago)`

@Aristidios you definitely need an update to that master channel, make sure you keep your [fork](https://github.com/Aristidios/flutter) updated with flutter/flutter! Right now, your master branch is `1817 commits behind flutter:master.`

(Flutter `master` gets updated several times a day, normally, so if you see anything older than 1 week, be suspicious!)

**Comment by Aristidios** [comment]
```
 flutter upgrade  
Flutter is already up to date on channel master
```
why do i get this?

**Comment by ditman** [comment]
> why do i get this?

That is because the flutter tool is comparing against the "master" of your fork. You have two options, but first you need to upgrade your fork with the latest from flutter/flutter. Github has added a button to make that super easy:

<img width="908" alt="Screen Shot 2021-11-04 at 12 20 00 PM" src="https://user-images.githubusercontent.com/1255594/140405936-dc302dc8-8064-4bcd-a8b3-83dbafee3abd.png">

Once Aristidios/flutter is synced with flutter/flutter, on your local flutter checkout you can do a `git pull --rebase` (the easiest way to update flutter from git), or you can `git fetch` and then `flutter upgrade`.

The tool is not good at informing users that it's working off of a fork, and it's somewhat confusing, but in general, if you use a Git workflow for flutter, you need to keep your fork up to date. You can also download flutter [from zip](https://flutter.dev/docs/get-started/install/macos) and not worry about that too much, the flutter will use flutter/flutter as its remote.

You only need flutter from git, if you're going to actually push code to flutter/flutter (in that case: thanks! ;) )

**Comment by Aristidios** [comment]
@ditman thks so much for your reply i'm not sure why my Flutter SDK became a fork - i'll try deleting it and downloading it back from zip file as you suggest 🙏

I indeed use Git with my workflow maybe when init a project did it fork the branch ? Anyway thanks a lot i'll get back to you if use regarding TextField still happening on new version

**Comment by ditman** [comment]
> maybe when init a project did it fork the branch?

Maybe? I know some of the instructions tell people to create a fork of flutter to contribute, so maybe you followed some of those instructions months ago! I hope you get to install an up-to-date version of flutter, you're missing out on fixes! :D

>  i'll get back to you if use regarding TextField if still happening on new version

@Aristidios please, also let us know if your update is successful, and maybe close this ticket if it is, so we save some resources when triaging!

**Comment by ditman** [comment]
> should i be using channel master or beta on M1 Mac for optimal performance

With `master` you're going to have daily updates and bugfixes (and the occasional breakage). With `beta`, the fixes are going to come at a slower pace, but it will also be more stable than `master`. More info about that topic here: [Flutter build release channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).
