### ISSUE TITLE
Dart roller stopped

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93206]
Following the Dart roll here: https://dart.googlesource.com/sdk.git/+log/38e7078fa2b7..d464cd3f2dc8

The Engine started to fail to roll to the framework due to test failures:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_misc/9738/overview

It looks like the failures are in a test of `dart fix`:

```
RUNNING: cd packages/flutter/test_fixes; ../../../bin/cache/dart-sdk/bin/dart fix --compare-to-golden
Computing fixes in test_fixes...
Failed when applying fixes to /b/s/w/ir/x/w/flutter/packages/flutter/test_fixes/material.dart
```

Maybe https://dart.googlesource.com/sdk.git/+/6732808c4061531dab3b0620a1a3c9849147bd2a

**Comment by bwilkerson** [comment]
The more likely candidate is https://dart-review.googlesource.com/c/sdk/+/219285. You'll need to revert it in order to revert https://dart-review.googlesource.com/c/sdk/+/219126 because one is built on the other.

Can we prioritize getting failures like this to be detected by one of the bots? Or perhaps someone can explain to me how to test this manually in the meantime. These changes to `dart fix` are a P1 OKR for me this quarter, and I'd prefer to not stop the roller because of not having any way to test a change before landing it.

**Comment by zanderso** [comment]
@bwilkerson The test command appears to be:
```
$ ../../../bin/cache/dart-sdk/bin/dart fix --compare-to-golden
```

run in a flutter/flutter checkout under the `packages/flutter/test_fixes` directory (https://github.com/flutter/flutter/tree/master/packages/flutter/test_fixes).

Instead of the Dart SDK under `../../../bin/cache/dart-sdk`, you should be able to use a Dart SDK you have built that contains the changes.

**Comment by a-siva** [comment]
> Can we prioritize getting failures like this to be detected by one of the bots? Or perhaps someone can explain to me how to test this manually in the meantime. These changes to `dart fix` are a P1 OKR for me this quarter, and I'd prefer to not stop the roller because of not having any way to test a change before landing it.

You would have to work with the analyzer team on getting these tests added to https://ci.chromium.org/p/dart/g/flutter/console (//cc @srawlins).

I am going to revert the changes mentioned in https://github.com/flutter/flutter/issues/93206#issuecomment-962733388 to get the roller back on.

**Comment by bwilkerson** [comment]
You probably only need to revert https://dart-review.googlesource.com/c/sdk/+/219285.

I would appreciate it if you would only revert https://dart-review.googlesource.com/c/sdk/+/219126 if it's proven to be necessary. That way I'll know whether there's any work that needs to be done before relanding it.

@devoncarew for visibility of the need to update the bots.

**Comment by devoncarew** [comment]
Brian, you'll likely have to tackle fixing the `dart fix` pre-submit check yourself. I'm happy to point you to where the script is. It does very little more than just clone flutter and run the dart fix golden check.

> These changes to dart fix are a P1 OKR for me this quarter

Keeping the dart => engine roller going is a much higher priority - it'll effect the productivity of everyone on the team. I would definitely prioritize fixing the presubmit check over any feature work in this are.

**Comment by bwilkerson** [comment]
> ... you'll likely have to tackle fixing the `dart fix` pre-submit check yourself.

I hope you mean the tests run on the try bots rather than the pre-submit check that's run before uploading a CL for review.

But yes, if I need to fix it myself, then please send me any information you can about the work that needs to be done. I have no experience in this area and I don't have any idea how to start. Please include information about who to ask for a review and how to test that these changes do what they're intended to do.

> Keeping the dart => engine roller going is a much higher priority ...

I am not, and was not, questioning that. I understand the importance of keeping the roller going. I'm just saying that the inability to verify that changes to `dart fix` aren't breaking the roller is impeding my progress. And I was _really_ hoping that someone who knew what they were doing could take on this task so that it could happen in a more timely manner.

**Comment by bwilkerson** [comment]
Do you have any reason to believe that https://dart-review.googlesource.com/c/sdk/+/219126 is causing problems? As I understand it, it should not have impacted the behavior of the failing test.

**Comment by a-siva** [comment]
> Do you have any reason to believe that https://dart-review.googlesource.com/c/sdk/+/219126 is causing problems? As I understand it, it should not have impacted the behavior of the failing test.

I haven't reverted that yet. I will try a roll into flutter with the revert of https://dart-review.googlesource.com/c/sdk/+/219285 and if that succeeds then that should be sufficient.

**Comment by bwilkerson** [comment]
Thanks!

**Comment by devoncarew** [comment]
@bwilkerson - the script which the flutter-analyze bot runs is https://github.com/dart-lang/sdk/blob/main/tools/bots/flutter/analyze_flutter_flutter.sh. You can run that locally - from a dart sdk checkout - via `.tools/bots/flutter/analyze_flutter_flutter.sh`. You might want to just replicate what it's doing at the end of the script however - the `dart fix --compare-to-golden` step - in the flutter repo, using the dart sdk build from the dart checkout - in order to try and reproduce the failure however.

In order to test this - once you've got a potential fix - you'd just upload a CL as normal. You can then run the `flutter-analyze` bot from there. I'd try once - reproing the failure - and a 2nd time, with a fix for the above CL - to validate that things are working end-to-end.

You might want to capture all this in a separate bug as these roll bugs only live long enough to unblock the roll.

Some things to validate initially might be things like is the script running the correct dart sdk for the fix check? Is dart fix picking up the right analysis server impl - w/ the latest dart fix changes? It does seem like there might be some version mis-match issue. You may also validate that dart fix is returning a correct exit code on failures, ...

**Comment by Hixie** [comment]
Is there some way we could run the flutter engine tests, and then the flutter engine+framework tests, as precommit dart tests? maybe some subset of them if that is too many?

**Comment by a-siva** [comment]
@bwilkerson Just reverting  https://dart-review.googlesource.com/c/sdk/+/219285  does not seem to fix the issue, see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830934716691035585/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout for a sample of the error encountered.
I am going to revert https://dart-review.googlesource.com/c/sdk/+/219126 also.
It is unclear to me if that would be sufficient, were you able to figure out the root cause of the problem

**Comment by a-siva** [comment]
> Is there some way we could run the flutter engine tests, and then the flutter engine+framework tests, as precommit dart tests? maybe some subset of them if that is too many?

We have a Flutter HHH bot which runs a subset of the flutter tests on every Dart change. It has been red for a while now

**Comment by a-siva** [comment]
The Flutter HHH bot is showing this error, see https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8830962308454432529/+/u/flutter_test_framework_tests/stdout.

**Comment by aam** [comment]
With both reverts landed can we restart the roller?

**Comment by bwilkerson** [comment]
> ... were you able to figure out the root cause of the problem ...

No, I haven't had time to look into it yet.

**Comment by a-siva** [comment]
> With both reverts landed can we restart the roller?

I am waiting for the Dart bots to catch up and the Flutter HHH bot to catch up to the revert to see if it turns green. At this point I will do a manual roll to a hash that includes the revert, wait for it to roll into the framework and then turn on the roller.

**Comment by aam** [comment]
> Flutter HHH bot to catch up to the revert

This could take many hours to happen.
I verified that the revert fixed the original issue locally, so as soon as the revert lands into 'dev' branch we should be able to start rolling.

**Comment by a-siva** [comment]
> > Flutter HHH bot to catch up to the revert
> 
> This could take many hours to happen. I verified that the revert fixed the original issue locally, so as soon as the revert lands into 'dev' branch we should be able to start rolling.

Ok, once a dev branch with the revert is available, I will do a manual roll. But we still should wait for it to get into the framework I feel.

**Comment by aam** [comment]
2.16.0-1.0.dev should have the revert.

**Comment by a-siva** [comment]
I have scheduled a manual merge of 2.16.0-2.0.dev which has the revert

**Comment by a-siva** [comment]
PR https://github.com/flutter/engine/pull/29659

**Comment by aam** [comment]
> PR [flutter/engine#29659](https://github.com/flutter/engine/pull/29659)

ready to roll

**Comment by a-siva** [comment]
The flutter engine bot has cycled green, there is an engine roll into Flutter in progress, once that finishes, the next roll should pick up the Dart roll change.

**Comment by a-siva** [comment]
The engine roll is not landing because the Flutter tree is broken

**Comment by a-siva** [comment]
The engine roll with the latest Dart changes here https://github.com/flutter/flutter/pull/93455 seems to have some failures, not sure if these are Flutter related or due to the Dart roll, could somebody from the Flutter team clarify.

**Comment by zanderso** [comment]
It looks like `pub` got more strict about parsing version constraints in a way that breaks the `customer_testing` shard:
```
| ERR : Error on line 1, column 1 of https://pub.dartlang.org/api/packages/built_collection: Invalid version constraint: Expected version number after ">=" in ">=2-0-0-dev <3.0.0", got "2-0-0-dev <3.0.0".
| FINE: Exception type: PubspecException
| FINE: package:pub/src/pubspec.dart 629:5                               Pubspec._error
|     | package:pub/src/pubspec.dart 623:7                               Pubspec._wrapFormatException
|     | package:pub/src/pubspec.dart 523:12                              Pubspec._parseVersionConstraint
|     | package:pub/src/pubspec.dart 253:15                              Pubspec._parseEnvironment
|     | package:pub/src/pubspec.dart 187:26                              Pubspec._ensureEnvironment
|     | package:pub/src/pubspec.dart 156:5                               Pubspec.sdkConstraints
|     | package:pub/src/solver/package_lister.dart 427:30                PackageLister._matchesSdkConstraint
|     | package:pub/src/solver/package_lister.dart 218:14                PackageLister.incompatibilitiesFor
|     | ===== asynchronous gap ===========================
|     | dart:async                                                       Future.catchError
|     | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
|     | package:stack_trace                                              Chain.capture
|     | package:pub/src/utils.dart 122:11                                captureErrors
|     | package:pub/src/command.dart 180:13                              PubCommand.run
|     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
|     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
|     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
|     | package:dartdev/dartdev.dart 46:56                               runDartdev
|     | ../../../../cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
| ---- End log transcript ----
| pub get failed (65; ---- End log transcript ----)
```

**Comment by zanderso** [comment]
https://github.com/dart-lang/pub_semver/pull/63

@gspencergoog @natebosch @kevmoo

**Comment by zanderso** [comment]
Revert here https://dart-review.googlesource.com/c/sdk/+/220040

**Comment by a-siva** [comment]
Looks like the engine roll with the Dart SDK rolls has landed here https://github.com/flutter/flutter/pull/93487
I am going to restart the Dart auto roller and close this isse.

**Comment by a-siva** [comment]
> It looks like `pub` got more strict about parsing version constraints in a way that breaks the `customer_testing` shard:

I don't remember seeing any breaking change or comms around this stricter version constraints.

**Comment by kevmoo** [comment]
> > It looks like `pub` got more strict about parsing version constraints in a way that breaks the `customer_testing` shard:
> 
> I don't remember seeing any breaking change or comms around this stricter version constraints.

@natebosch @gspencergoog and I were of the opinion this was unlikely to break things.

The regression is because a package was published with a nonsensical SDK constraint that used to just be a noop – but now crashes.

**Comment by aam** [comment]
#93487 had dart sdk roll reverted

```
2021-11-11 zanderso@users.noreply.github.com Revert "Roll Dart SDK from 38e7078fa2b7 to e1a475a40934 (19 revisions) (#29659)" (flutter/engine#29677)
```

**Comment by a-siva** [comment]
> #93487 had dart sdk roll reverted
> 
> ```
> 2021-11-11 zanderso@users.noreply.github.com Revert "Roll Dart SDK from 38e7078fa2b7 to e1a475a40934 (19 revisions) (#29659)" (flutter/engine#29677)
> ```

Oh didn't realize that, looks like we have to another manual Dart SDK roll with the revert.

**Comment by a-siva** [comment]
Next attedmpt at rolling Dart to the engine https://github.com/flutter/engine/pull/29699 (the HHH bot has done the plugin tests and they appear to pass in that run).

**Comment by a-siva** [comment]
Engine bot has cycled through this change.

**Comment by a-siva** [comment]
The previous engine roll into the framework seems to be stalled, see flutter/pull/93510

**Comment by zanderso** [comment]
We may have been hammering on Skia Gold a little too hard recently: https://discord.com/channels/608014603317936148/608018585025118217/908547544366321714

**Comment by aam** [comment]
> Next attedmpt at rolling Dart to the engine [flutter/engine#29699](https://github.com/flutter/engine/pull/29699) (the HHH bot has done the plugin tests and they appear to pass in that run).

This landed into engine, but [broke flutter roller](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/24652/overview) again in similar fashion:
```
| FINE: Resolving dependencies finished (1.2s).
| ERR : Error on line 1, column 1 of https://pub.dartlang.org/api/packages/built_collection: Invalid version constraint: Expected version number after ">=" in ">=2-0-0-dev <3.0.0", got "2-0-0-dev <3.0.0".
| FINE: Exception type: PubspecException
```

I believe that is because revert from https://github.com/flutter/flutter/issues/93206#issuecomment-966317366 only landed in 2.16.0-7.0.dev, but the roll only went up to 2.16.0-6.0.dev

**Comment by a-siva** [comment]
@aam started a roll till 2.16.0-10.dev here https://github.com/flutter/engine/pull/29712 which does include the revert and it is almost done.

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/pull/93563 seems to have merged the Dart rolls into the framework

**Comment by aam** [comment]
perhaps now the roller https://autoroll.skia.org/r/dart-sdk-flutter-engine can be resumed

**Comment by a-siva** [comment]
> perhaps now the roller https://autoroll.skia.org/r/dart-sdk-flutter-engine can be resumed

Yes, I will restart it now, the framework bot seems to have cycled green

**Comment by a-siva** [comment]
Will close this issue.
