### ISSUE TITLE
MaterialApp is transparent on Android and opaque on iOS

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9321]
MaterialApp is transparent on Android and opaque on iOS. This seems like a bad inconsistency to have.

I think MaterialApp should be transparent, otherwise there are many effects that you can't achieve.

I believe the opaqueness on iOS is coming from the route having a default background color because it has a default shadow. I'm not really sure how to square this with what I'm saying here.

cc @abarth who may have ideas.
cc @xster who worked on this previously.

**Comment by xster** [comment]
#9166 will remove at least the background part of it. 

We can remove all shadows during the resting state as well from the routes. 

Will add a test if transparency on the app is a desired property.

**Comment by xster** [comment]
@Hixie would like to bounce an idea off of you. What do you think about adding a thing in the build for all page transition classes:
```
if primary and secondary animations.status == complete
  don't add any of the intermediate AnimatedWidgets, just return the child directly
```

**Comment by Hixie** [comment]
That's quite expensive (it would result in the entire subtree being rebuilt at the start and end of each transition).

What would the purpose be?

**Comment by xster** [comment]
Can I generalize it to 'reparenting is expensive' for my understanding? 

It's to remove the shadows during the resting state.

I'll just have a custom tween with an overridable beginning/end separate from the beginning/end used for lerp'ing otherwise

**Comment by Hixie** [comment]
Reparenting isn't so bad (when using GlobalKeys, that is). Changing the shape of the tree in general is not free, though. You have to rebuild all the render objects, all the elements, etc. It's much cheaper to keep the tree the same shape all the time.

I'm concerned that removing the shadows implies that they are conceptually there but just not being drawn. This would be a problem e.g. if the Navigator is not covering the whole screen (as I believe is the intent in the https://github.com/flutter/posse_gallery/ demo). You'd see the shadow until you got to t=0 and then they would disappear suddenly.

**Comment by xster** [comment]
Thanks for the example. Maybe I'm having trouble visualizing the scenario to know what's the best fix. There's no code at https://github.com/flutter/posse_gallery/ though :S

**Comment by Hixie** [comment]
Eric has some mocks he can show you.

Imagine that instead of the Navigator being full-screen, it was instead inset by 20px on all sides (with a title above it -- basically, the app nested inside another).

**Comment by xster** [comment]
Ah, I see the mockups now. Based on it, I think we really want a clipping mechanism (either for the entire MaterialApp or for the route widget) rather than some special edge conditions for the shadow.  WDYT? 

Sounds like we need to address not having the shadow leak into unexpected places than the transparency

**Comment by Hixie** [comment]
I don't remember seeing any mockups showing how the animation should work on iOS, so it's not clear to me what is desired.

**Comment by xster** [comment]
Ok, so somewhat following Posse's doc in a sample

![flutter_01](https://cloud.githubusercontent.com/assets/156888/25246060/5456917c-25bb-11e7-9b0d-5dccf0d9cffa.png)

It's definitely wrong / not modular. The solution is to only show shadow from the transition within the confines of the transition widget itself.

**Comment by Hixie** [comment]
Why is it wrong? It looks right to me?

**Comment by xster** [comment]
I think we probably want the user to decide themselves whether they want the shadow around the inner app like on Android

**Comment by xster** [comment]
Somewhat unrelated but we should be consistent about clipping inside the material app globally (for instance the app bar's shadow in the inner app leaks too)

**Comment by Hixie** [comment]
If the developer wants to clip they can easily add a ClipRect.

**Comment by xster** [comment]
Umm that's a good point too. 

I think the only edge case is if the user decides to randomly make a MaterialPageRoute out of the blue and put it in the app without it being fullscreen. But it's pretty edgy. 

Do you want to close this then?

**Comment by Hixie** [comment]
Well the initial bug is still there, right? We have an inconsistency about the default background colour for MaterialApp (or rather, MaterialPageRoute, I guess?).

**Comment by Hixie** [comment]
I'm just not sure what to do about it.

**Comment by xster** [comment]
You're worried about users adding MaterialPageRoute with a transparent child?

Wonder how costly it is to try to detect the opacity of the child and add shadow if it isn't (it would look weird even with just an edge shadow anyway). But I guess the child can change so the detection would be per frame which kinda sucks. 

Otherwise we can add some new API to BoxShadow to have some form of a shadow paint clipping rect.

**Comment by eseidelGoogle** [comment]
Not to stick my nose in this bug, but the only usage I've heard proposed for transparency so far is about putting a FlutterView over an OEM view (such as a MapView or Video, etc.) so you could have Flutter drawing over the top of some OEM view).  I suspect this is only marked as M2 for the api-stability aspect. :)  Posse's gallery designs are possible to change and as far as I can tell nothing in this bug is currently blocking any customers, etc. :)

**Comment by Hixie** [comment]
Mostly my concern is that we be consistent between Android and iOS because otherwise people will build on one, assuming it's going to look vaguely that way on the other, then find it's completely different on the other. For example if they want to have a 3D scene behind a Flutter app, it'll work fine on Android but not on iOS. On the other hand if they assume the background is whitish (as it is on iOS), then put black text on their app, then on Android it'll be black-on-black.

**Comment by xster** [comment]
I agree. We shouldn't expose any of this to users either way I think. Things should just work in some sensible fashion. 

The other approach is to create a Cupertino equivalent of the material ink splash mechanism and paint it via the parent which is a lot easier to fine tune graphically but I'm not sure yet whether it's worth the investment. 

I'll mess a bit with the canvas painting API to see if it's accomplishable first. Either way, there should be no user visible API change.

**Comment by Hixie** [comment]
I guess I don't really understand what the iOS requirements here are. Can you elaborate on what we're trying to model on the Cupertino side?

**Comment by xster** [comment]
Calling showViewController slides in the view controller with a shadow on the left side of the new view controller's edge.

**Comment by xster** [comment]
On more thoughts, we would want to solve this more generally. It's not necessarily just an iOS problem but could manifest in all transparent contents or anywhere we use a Material with elevation. 

Things will look blended if the user tries to use anything with transparency in the app bar or in the bottom navigation bar etc which are all sensible design choices. 

BoxDecoration is a bit more agnostic about what it's meant to model so we can do anything we want to solve it like a bool BoxShadow.drawOutside or something (which might be difficult since Canvas.drawRect takes a single rect) or an edgeShadow sibling to BoxDecoration.boxShadow. This is appropriate for Cupertino since we're not trying to represent physics so it would make sense to never migrate it to PhysicalModels.

But we'll have to answer this more fundamentally with PhysicalModels where the shadow casting looks independent from the caster's opacity. There's a transparentOccluder it uses in Skia but it looks like just a performance optimization.

**Comment by Hixie** [comment]
Having a shadow if the content is transparent makes no sense to me. What is casting the shadow?

**Comment by xster** [comment]
Discussed offline. 

We'll keep this problem separate from the general transparent objects casting shadows in physical models problem. 

Will create a custom painter for cupertino transitions.

**Comment by Hixie** [comment]
@xster Are you still on track for doing this by next week?

**Comment by xster** [comment]
@Hixie sure
