### ISSUE TITLE
Document the workflow to create archives

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93410]
The new engine recipes are separating build, test and archives. As part of this process the archives are going to be created using gn + ninja rather than selecting files and moving them around to create the zip files.

@dnfield has been creating some of the archives but we may need to crowdsource the creation of the archives and some guidance on where to start and how to test the archives will be really helpful.

**Comment by dnfield** [comment]
In the GN rules, there's a template called https://github.com/flutter/engine/blob/master/build/zip_bundle.gni

This template is already used by the Android embedding to create its outputs. It dumps them into `$root_out_dir/zip_archives`.

We want to apply this to the other build targets as well. Basically, this involves reading the recipes to enumerate what files are created, and reproducing the exact same zip archive structure under the `zip_archives` directory. Once those are identical, you can remove the zipping logic from the recipe and just upload the archives directly from the out dir. Ideally, the structure of the outdir would match the expected directory structure in the GCS bucket, so that everything is driven by GN rather than the recipes (and it's all testable in the engine repo and tied to engine revisions).

/cc @christopherfujino for further feedback.

**Comment by godofredoc** [comment]
Thanks for the information.
