### ISSUE TITLE
[Windows] Japanese IME input mode switch shortcut (Alt-`) doesn't work

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#93422]
When a Japanese keyboard layout is used, Alt-` is used to switch between romaji (latin) input and hiragana (Japanese) input. This keyboard shortcut appears to have stopped working at some point; as such the only way to switch input modes is using the mouse and selecting "A" (for romaji) or "あ" for hiragana from the taskbar icon.

Repro steps:
1. Set keyboard mode to romaji ("A" in taskbar)
2. Launch a flutter app with a text field
3. Focus the text field
4. Type Alt-&#96;

**Expected behaviour:** IME briefly flashes "あ" to indicate input mode switch. Task bar icon switches from A to あ. Subsequent typing happens in composing mode.

**Actual behaviour:** IME briefly flashes "A" (current input mode, unchanged). Task bar icon does not switch from A to あ. Subsequent typing remains in romaji (latin) input mode.

**Comment by cbracken** [comment]
Tangential to this issue, but I've verified that some of the other mechanisms for interacting with the IME via physical keys (as opposed to IME shortcuts) _do_ work. 

Specifically:
* 半角・全角
* 無変換
* 変換
* カタカナ・ひらがな

are all verified to work with the MS Japanese input and Google Japanese input IMEs.

**Comment by justinmc** [comment]
Just chiming in to say that I don't think the framework is consuming this shortcut.  All of the shortcuts are [here](https://github.com/flutter/flutter/blob/4f8d11b41e9487ba536d88507fb6e65a1798a0ab/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L162), and there are a few that use alt, but none that use the tilde ~.

**Comment by gspencergoog** [comment]
Actually, the shortcut appears to be Alt-`, not Alt-~, which would require a shift on a US keyboard. Or maybe it's based on key location, not actually keycap. In any case, we don't appear to have shortcuts with Alt-` either.

**Comment by gspencergoog** [comment]
Here's what I think is happening:

We get a WM_SYSKEYDOWN, and we send it to the framework, and immediately tell Windows that we handled it.  Since the framework doesn't handle it (typically), we then send it to `SendInput` when we get the framework response to synthesize a new (identical) event. _But_, sending a system key to `SendInput` doesn't get handled as a system key, because you're not allowed to synthesize system keys (e.g. you can't synthesize Ctrl-Alt-Delete).

My first inclination is to just not send system keys to the framework, and always send them to the default window proc, but I'm not sure what that would disable in Flutter apps.

Alternatively, and this is what I'm going to pursue, we could still send them to the Framework, but just ignore whether or not they were handled (and not call SendInput if they aren't), and also send them to the default window proc when we first get the event.

Then Flutter would still see them, but couldn't override them, and so the Kanji switch would work, even if someone handled the key event for it. They'd still get notified that it happened, though.

I verified that if I don't call `SendInput` for sys keys, and I do call the `Win32DefWindowProc` at the time the event is initially handled, then the Kanji switch works.

PR in the works.
