### ISSUE TITLE
Harfbuzz warning loop variable '_' is always a copy

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93432]
Seeing this failure on presubmit on an [unrelated PR](https://github.com/flutter/engine/pull/29654):
```
In file included from ../../third_party/harfbuzz/src/hb-subset.cc:35:
../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:110:40: warning: loop variable '_' is always a copy because the range of type 'hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, (lambda at ../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:126:15), hb_function_sortedness_t::NOT_SORTED, nullptr>' does not return a reference [-Wrange-loop-analysis]
    for (const hb_item_type<Iterator>& _ : +it)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830924246644624817/+/u/build_ios_debug_sim_arm64/stdout

I'm not sure what changed on the builder, do we need to disable range-loop-analysis warning in the GN build rules? Or cherry pick in harfbuzz/harfbuzz@86993c0?

**Comment by chinmaygarde** [comment]
I know there was a harfbuzz roll but [that was weeks ago](https://github.com/flutter/engine/pull/29263). You're right that we need to disable loop range analysis but I can't tell why you are running into this issue now. Perhaps a ToT rebase is in order?

**Comment by chinmaygarde** [comment]
Nevermind, that PR is pretty close to ToT today :/

**Comment by jmagman** [comment]
Very weird, none of the other PRs from today are hitting this error.  Maybe it's a cache error?  Rebasing and running again.

**Comment by chinmaygarde** [comment]
cc @godofredoc may have thoughts on this perhaps.

**Comment by jmagman** [comment]
The test succeeded on a re-run.

**Comment by chinmaygarde** [comment]
We looked at this code in detail in triage and we can't tell how a unary add to an iterator would even be legal. It is templated so, perhaps thats how the compiler is letting go of it? But it seems like a bug. Seems like a special iterator type that is specific to HB. Per @jason-simmons reading of the code, it seems intentional on the code authors part but it is certainly weird.

Since this was a weird LUCI one-of and since it is not actionable, I am closing this. We can reopen if this keeps happening.
