### ISSUE TITLE
How does Flutter achieve the Toast shown in the video?

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#93446]
How does Flutter achieve the Toast shown in the video?
https://user-images.githubusercontent.com/91245043/141218551-d2b8db83-6531-43c9-83bc-cf1e7321d280.mp4

**Comment by stuartmorgan** [comment]
We have explained repeatedly that questions like this are not appropriate here, and have pointed you to relevant resources for asking questions. Please do not continue to deliberately file off-topic issues.

**Comment by Hixie** [comment]
@gionlime I have blocked you for 30 days because you have been filing an excessive number of issues without following our guidelines. Please see https://github.com/flutter/flutter/issues/new/choose for guidelines on how to file issues, noting in particular that Q&A is best directed to user forums like r/FlutterDev on reddit.com.
