### ISSUE TITLE
Wanna manage pickImages count

### ISSUE THREAD

**Issue by ssorrychoi** [flutter/flutter#93472]
Hey guys, I wanna manage pick images count in image_picker plugin.
It should be essential feature in pick multiple images, becuz if every users upload images infinity in their app, the company managing the app should be pay a lot.

So it is necessary feature to me.

**Comment by danagbemava-nc** [comment]
Check https://github.com/flutter/flutter/issues/85772 for more information. 

Because of how `pickMultiImage` is implemented, this is not possible on `android`, if you want this feature to be implemented for `iOS` only, thumbs up [this comment](https://github.com/flutter/flutter/issues/85772#issuecomment-887614127) so it can get more traction and be implemented for `iOS` only. 

Closing as a duplicate from here.
