### ISSUE TITLE
2.8 beta release blocked on ios app crash

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93517]
module_test_ios is failing consistently on the release 2.8 beta release branch with the application crashing on startup. The changes included are in the dart sdk are:

dart-lang/sdk/issues/47654
dart-lang/sdk/issues/47644
dart-lang/sdk/issues/47641
dart-lang/sdk/issues/47640
dart-lang/sdk/issues/47639
dart-lang/sdk/issues/47657
dart-lang/sdk/issues/47661

This is a link to a build failure: https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios/10765

**Comment by jmagman** [comment]
Beta PR with the failing test is https://github.com/flutter/flutter/pull/93448.

Branch point is https://github.com/flutter/flutter/pull/92855 where the [test passed](https://github.com/flutter/flutter/pull/92855/checks?check_run_id=4071597627).  
Then https://github.com/flutter/flutter/pull/93175 was applied, and it also passed (I made a PR with just this change to validate: https://github.com/flutter/flutter/pull/93519, here's the [test passing](https://github.com/flutter/flutter/pull/93519/checks?check_run_id=4184710347)).
Then the engine was rolled to https://github.com/flutter/engine/pull/29662, which only rolled dart.  [The test failed.](https://github.com/flutter/flutter/pull/93448/checks?check_run_id=4173679069)

I was able to reproducible it on my machine:
```
$ cd dev/devicelab
$ flutter pub get
$ dart bin/run.dart -t module_test_ios
```

This add-to-app test creates a Flutter module, and then injects it into a [non-Flutter host app](https://github.com/flutter/flutter/tree/master/dev/integration_tests/ios_host_app).  The tests fail running simulator UI tests on the resulting host+Flutter app.  The tests are crashing on launch with `EXC_BAD_ACCESS (Code Signature Invalid)`.  The app and tests are not codesigned, but they shouldn't need to be since it's running on a simulator.  When I run the same tests and codesign them, the tests pass.

[module_test_ios_crash.txt](https://github.com/flutter/flutter/files/7524098/module_test_ios_crash.txt)

**Comment by jmagman** [comment]
Simplified repro steps from the UI tests in `flutter_gallery` (the issue is not related to modules, that's just the test that had the perfect test setup to fail):

```
$ cd dev/integration_tests/flutter_gallery/
$ flutter build ios --config-only
$ xcodebuild -configuration Debug -workspace ios/Runner.xcworkspace -scheme Runner -destination 'platform=iOS Simulator,name=iPhone 11' test  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=- EXPANDED_CODE_SIGN_IDENTITY=-
```

**Comment by a-siva** [comment]
> This add-to-app test creates a Flutter module, and then injects it into a [non-Flutter host app](https://github.com/flutter/flutter/tree/master/dev/integration_tests/ios_host_app). The tests fail running simulator UI tests on the resulting host+Flutter app. The tests are crashing on launch with `EXC_BAD_ACCESS (Code Signature Invalid)`. The app and tests are not codesigned, but they shouldn't need to be since it's running on a simulator. When I run the same tests and codesign them, the tests pass.

I am not too familiar with how code signing works on mac, IO looked through all the Dart cherry picks that went into this release and the only one that could potentially have any effect is dart-lang/sdk/issues/47641, though per that CL the change was meant to only effect ARM64 builds.
//cc @athomas do you think that could have some effect on code signing?

**Comment by jmagman** [comment]
I just tried testing with a local engine `flutter build ios --config-only --local-engine ios_debug_sim_unopt` on [09f1520e8](https://github.com/flutter/engine/commit/09f1520e8b9585d133faf1eccced9357670c6d11) and the tests pass, so this doesn't seem to be a problem with that dart roll.

I just found https://github.com/flutter/flutter/pull/80459#issuecomment-820627649 which was the same crash on a dev cherry pick.  @godofredoc could there be an environment difference in the dev/beta engine builders?

**Comment by godofredoc** [comment]
The builders are exactly the same. I also re-built+signed the engine binaries and they keep failing the test.

The only difference I can think of is that engine artifacts are signed before starting the framework builds

**Comment by godofredoc** [comment]
Also confirmed that this is not caused by the dart sdk. I have a cherrypick process for 2.7-candidate-5 running on parallel and the test is failing in the same way https://github.com/flutter/flutter/pull/93522.

**Comment by jmagman** [comment]
Ad-hoc codesign the framework instead of skipping signing: https://github.com/flutter/flutter/pull/93556
Tried on top of the codesigned framework, `module_test_ios` passed: https://github.com/flutter/flutter/pull/93519
https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios/10802
