### ISSUE TITLE
test/canvaskit/embedded_views_test.dart test failure on Linux Web Engine buildbot

### ISSUE THREAD

**Issue by aam** [flutter/flutter#93558]
From lwe flutter engine buildbot https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830747313448611665/+/u/felt_test:_chrome-unit-linux/stdout

```
00:24 [32m+566[0m[33m ~6[0m[31m -1[0m: test/canvaskit/embedded_views_test.dart: HtmlViewEmbedder renders overlays on top of platform views [1m[31m[E][0m[0m                                                                              
  Assertion failed: "Attempting to use the canvas of a disposed surface"
```

cc @yjbanov

**Comment by chinmaygarde** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
I'm not able to reproduce locally, and looking at the past 200 engine builds, this happened once (although it coincided with an infra failure, which muddies the water a bit). Is it possible to hook the flake bot to this issue so it reports the flakiness rate for this test?

**Comment by chinmaygarde** [comment]
I don't now how to answer that. cc @CaseyHillers @godofredoc

**Comment by CaseyHillers** [comment]
go/flutter-infra-metrics -> flutter flakiness [link](https://data.corp.google.com/sites/flutter_infra_metrics_datasite/flutter_luci_build_flakiness_15day_dashboard/?p=REPO:%22engine%22&p=BUILDER_LIKE:%22Linux%25%22)

Since this is work done in a web drone, it's not extractable in the dashboards beyond looking at all web drone stats (\cc @keyonghan)

**Comment by yjbanov** [comment]
This happened only once in the last 200 runs. Assuming this is fixed. Let's open if it happens again.
