### ISSUE TITLE
flutter_gallery app load twice items.dart

### ISSUE THREAD

**Issue by welldone217** [flutter/flutter#9364]
app.dart and home.dart both import items.dart cause contacts_demo.dart load twice。

I think load once much better

**Comment by eseidelGoogle** [comment]
I'm not sure I understand.  Dart's imports are unique, if libraries are loaded via the same URLs they are only imported once.

Can you help me understand how to reproduce the bug? or how to see the effects of this bug?

**Comment by welldone217** [comment]
i made a gif
<img src='http://img1.ph.126.net/nkkMMmaQyyw5Za_0wibZzg==/6632177172934227340.gif' />

**Comment by welldone217** [comment]
by the way , how to init a  initalvalue in textFormFiled ,you tell me not use 
`
                controller:new TextEditingController(text:'your name'),
`
then i have no idea

**Comment by eseidelGoogle** [comment]
Sorry my point before was that you didn't want to pass a *new* TextEditingController every time you build but rather you wanted to hold onto the TextEditingController and pass the same one each time build() is called.  The TextEditingController holds onto valuable state (including the initial value) that you don't want to reset back to defaults every time your application draws a frame.

Note in this example how the TextEditingController is retained and not made new every frame:
https://github.com/flutter/flutter/blob/3eb87830e91379c4c0b3d3b88eeae45dee7243e0/examples/flutter_gallery/lib/demo/material/expansion_panels_demo.dart#L151
Similarly here:
https://github.com/flutter/flutter/blob/89a7fdfc56121b1abb8d4743e9cd0f5c328e8367/examples/stocks/lib/stock_home.dart#L68

Widgets live for a single Frame (just long enough to explain to the Flutter system what you want the next frame to look like). State objects typically live longer, between frames, and thus can hold longer-lived objects like TextEditingController.

**Comment by eseidelGoogle** [comment]
https://docs.flutter.io/flutter/widgets/State-class.html and linked classes have much more information about the lifecyles of these various objects in the system.
https://flutter.io/tutorials/interactive/#managing-state also has more information about State vs. Widgets.
TextEditingController is the "internal state" of the text box, and by providing one, you're being asked to maintain its lifetime instead of the TextInput creating one itself and managing its lifetime.  By providing a new TextEditingController every time you build you're essentially asking the TextInput to reset back to default values (including cursor position, etc) every time it builds.  Hopefully that makes sense?

**Comment by welldone217** [comment]
@eseidelGoogle  thanks for explain，I think i am clear about that. 
 
i hope Describe clearly about every demo load twice in flutter_gallery app

**Comment by Hixie** [comment]
Build functions get called lots of times in general, we do not consider that an issue unless it can be traced to a specific performance problem.

The imports are not the cause of this.
