### ISSUE TITLE
Popup menu items remain on screen after dismissing

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93758]
Internal b/205909074

When a popup menu is long enough to be scrollable, the item text remains on screen after the menu is dismissed.
<img width="300" alt="Screen Shot 2021-11-16 at 7 00 54 PM" src="https://user-images.githubusercontent.com/682784/142126773-eb7f7370-ec59-491f-9349-4e6fe68c2900.png">

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hello'),
        actions: [
          PopupMenuButton(
            itemBuilder: (BuildContext context) => List<PopupMenuEntry>.filled(
              30,
              const PopupMenuItem(
                child: Text('PopupMenuItem'),
              ),
            ),
          )
        ],
      ),
      body: const Center(
        child: Text('Hello World'),
      ),
    );
  }
}


```
https://user-images.githubusercontent.com/682784/142126735-31b1def9-5d9f-464e-a657-25531b9aeeae.mov

```
$ flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.737, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.737 at /Users/magder/Projects/flutter
    • Upstream repository git@github.com:jmagman/flutter.git
    • Framework revision ee87f6113e (28 minutes ago), 2021-11-17 05:43:05 +0300
    • Engine revision 2962099077
    • Dart version 2.16.0 (build 2.16.0-14.0.dev)
    • DevTools version 2.8.0
```

**Comment by jmagman** [comment]
Does not reproduce in an Android emulator.

https://user-images.githubusercontent.com/682784/142127447-e4a5ff0e-48d6-4991-bc57-553bdf011ec4.mov

**Comment by jmagman** [comment]
Bisected to #92977, maybe https://github.com/flutter/engine/pull/28801? @iskakaushik

**Comment by jmagman** [comment]
Confirmed, this is a regression from https://github.com/flutter/engine/pull/28801 /cc @zanderso @knopp

**Comment by knopp** [comment]
I'll look into this. There seems to be a clipping issue though - If you look at this frame from the Android video (without partial repaint), you'll see that the menu items are not clipped while dismissing the menu. Not sure if that's intentional.

<img width="333" alt="Screen Shot 2021-11-17 at 9 56 26 AM" src="https://user-images.githubusercontent.com/96958/142169103-6c9dc55d-9e7d-46a0-acea-1710cbd72939.png">
.

**Comment by knopp** [comment]
Okay, upon further investigation - `PhysicalShapeLayer` containing the menu doesn't have clip set, and the `ClipRect` layer does not resize with `PhysicalShapeLayer` during animation (it stays full size). That explains the lack of clipping on android.

As for iOS, the problem is caused by `PhysicalShapeLayer` diff code, which always assumes clipping, which is not the case here. The fix should be rather straightforward.

**Comment by jmagman** [comment]
Thanks for the quick fix, @knopp!  Confirmed this no longer reproduces in the framework post https://github.com/flutter/flutter/pull/93789.
