### ISSUE TITLE
Add support for SPIR-V operations necessary for community use-cases

### ISSUE THREAD

**Issue by chriscraws** [flutter/flutter#93800]
This is a higher-level issue to triage needs from the community for the SPIR-V transpiler to support additional operations. We'd like to keep the implementation as minimal as possible, so some operations will be left unsupported if there are reasonable workarounds. The API is not intended (or able) to support arbitrary SPIR-V modules.

**Comment by oktinaut** [comment]
I was experimenting with the current feature set and was able to implement a basic Phong-shader with normal maps. The result was displaying a texture with dynamic lighting like traditional bump mapping. 

Though already a nice effect, I strive for something more. I want to craft a UI component that reacts to the devices physical orientation (and maybe detected light sources through the camera) using a physically-based rendering workflow. Reflections for such shaders are implemented using cube maps for the most part. So I would ideally use a samplerCube instead of a sampler2D, which is currently missing.

Another issue is the lack of texture LODs. To calculate roughness per pixel, you would usually use LODs to make the reflection more blurry. As far as I am aware, it is not possible right now to generate Mipmaps, and the functions `textureLod`, `textureCubeLod` and `textureQueryLod` are not implemented.

I know this is probably a very niche use-case, and I guess it would be possible to work around these issues in the shader code, but I suspect a noticeable performance impact.

**Comment by jaween** [comment]
I would like support for uniform arrays in Fragment shaders (this would also rely on control flow).

Based on my comment on [#58361](https://github.com/flutter/flutter/issues/58361#issuecomment-763259552) last year, I am looking to have my fragment shader accept an array of coordinates created by the user (from a source such as pointer events), and then running something such as Bresenham's line algorithm per pixel to check if a pixel is to be shaded or not. I plan to extend this to curves of varying thickness, anti-aliasing curves, custom brushes, etc.

My understanding is that supporting arrays is purely for convenience, because we can already submit arrays to the shader on the Dart side, but on the shader side we don't have the syntax to declare something as an array, so we have to declare each element of the array manually (which is tedious if you need an array of say 256 elements). You'd also have to also manually unroll your loops to address each element.

(Most of my use-case can be done in real time without shaders, but getting that buffer to the GPU to display on the screen can get pretty slow. Images larger than 512x512 can take tens to hundreds of milliseconds to get to the GPU, even on higher end phones.)

**Comment by doctor-kicks** [comment]
+1 for arrays and control flow. Similar to @jaween I'm looking to pass in a list of 2D triangles and render them using a point-in-triangle test.

**Comment by matthew-carroll** [comment]
@chriscraws can you elaborate on why "The API is not intended (or able) to support arbitrary SPIR-V modules"? And does this statement apply to all custom shader functionality, or is it a statement that's specifically about SPIR-V support?

**Comment by chriscraws** [comment]
> @chriscraws can you elaborate on why "The API is not intended (or able) to support arbitrary SPIR-V modules"? And does this statement apply to all custom shader functionality, or is it a statement that's specifically about SPIR-V support?

Sure. This is specifically about this implementation and SPIR-V. Things may change when Flutter moves to Impeller, but for now the engine relies on Skia and its shading language SkSL to allow for custom shaders. The feature set of SkSL is much smaller than the feature-set of SPIR-V. In addition, the engine has it's own transpiler to convert SPIR-V into SkSL. The features available from SPIR-V here are therefore limited both to what SkSL supports and to what we are able to correctly transpile. 

In the future, I think Impeller will use modern GLSL, which supports a much broader set of features from SPIR-V, but there are still features in both SPIR-V and GLSL that are not present in the other, and both even have differences when used in Vulkan versus OpenGL, so "arbitrary" SPIR-V modules will probably never be possible.

**Comment by jonahwilliams** [comment]
This is obsolete now as we've moved to precompiled shaders directly to a host language (SkSL, MSL for Impeller on iOS, et cetera). There may be missing features from this implementation but we can track those in individual issues.
