### ISSUE TITLE
InAppPurchase.instance requires calling enablePendingPurchases()

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#93837]
This assert fails if `InAppPurchaseAndroidPlatformAddition.enablePendingPurchases()` isn't called. 
https://github.com/flutter/plugins/blob/730129a45b52bca567cc5cc0263743ff1bc047a3/packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform_addition.dart#L18-L21

This isn't documented either.

cc @stuartmorgan

**Comment by nt4f04uNd** [comment]
This requirement comes from the google play billing library. It seems like it's documented with a reference to the library documentation

https://github.com/flutter/plugins/blob/730129a45b52bca567cc5cc0263743ff1bc047a3/packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform_addition.dart#L34

Also noted in README

https://github.com/flutter/plugins/blob/349a858048db6c4d74610e228b2772ba9b2b73c2/packages/in_app_purchase/in_app_purchase/README.md#initializing-the-plugin

**Comment by stuartmorgan** [comment]
@mvanbeusekom @cyanglaz Why are we forcing everyone to call a method whose sole purpose is just to assert that they've called it? Especially since the README just tells people that they have to do so without any real context (meaning people are almost certainly just going to blindly copy that code, so if the goal is to ensure that people have made substantive changes to their usage of the library it's almost certainly not going to actually do that.)

Can we just make this a no-op, and deprecated it?

**Comment by cyanglaz** [comment]
@stuartmorgan PBL introduced this method `enablePendingPurchases ` in version 2.0.0. PBL wants people to call this method starting from v2 so that the developers are aware of a new "pending purchase" feature.  When we were migrating to v2, we had a discussion back then that decided to follow the same pattern (which makes it a breaking change) so that developers won't blindly get this feature and break their user experience without knowing.
Now, all the apps should be migrated to thew new PBL (otherwise, play store will reject the app), meaning that they should aware of this feature. I don't see a reason to not removing this (with a deprecation).

**Comment by cyanglaz** [comment]
Let's deprecate this and update README.

**Comment by mvanbeusekom** [comment]
I can create a PR tomorrow if that helps
