### ISSUE TITLE
Where can I find flutter help?

### ISSUE THREAD

**Issue by goodmanworld** [flutter/flutter#93902]
I have a problem that I asked several times here and all got closed. Also no one answered my question on Stackoverflow. I like to know if there is any other community I can ask my question and get help?

**Comment by stuartmorgan** [comment]
Almost every response you received answered this question.

Again, the issue tracker **is not a Q&A resource**.

**Comment by Hixie** [comment]
@goodmanworld This was the seventh time in the last month that you've filed an issue asking for advice. There's a list of more appropriate places for getting feedback here: https://flutter.dev/community#community-grid

I have temporarily applied a ban to discourage you from filing help requests in this issue database, since that's not what this database is for.
