### ISSUE TITLE
Comments or strings with Material Colors.[any color here] show the color next to line number

### ISSUE THREAD

**Issue by 2231puppy** [flutter/flutter#93932]
## Steps to Reproduce

1. Import Material design 
2. Make a new comment containing the exact string Colors.red _or_ make a new string containing Colors.red
3. Look next to line numbers where breakpoints are and see color 

**Expected results:**  Color not shown next to line numbers

**Actual results:**  Color is shown next to line numbers

<details>
<summary>Code sample</summary>

```dart
import 'dart:developer';
import 'package:flutter/material.dart';


void main() {
  log('Colors.red');
  // Colors.red

}
```

</details>
<img width="467" alt="flutter_bug" src="https://user-images.githubusercontent.com/18540892/142678751-cb8c1b62-7bf1-4e63-96b9-8c59877793b8.png">

**Comment by 2231puppy** [comment]
Forgot to mention that this is in VSCode with the Flutter extension and Flutter version 2.6.0-11.0.pre on MacOS.

**Comment by danagbemava-nc** [comment]
Issues with the `flutter vscode extension` are to be filed in its dedicated repo. 

Kindly file this issue here https://github.com/Dart-Code/Dart-Code/issues/new/choose 

Closing as this isn't an issue with `flutter` itself. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
