### ISSUE TITLE
Native iOS screen shows keyboard, underlying Flutter view moves text up for keyboard, doesn't reset when keyboard/native screen dismissed

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93944]
Internal b/206667860

When Flutter launches a native iOS view controller with textfield as the first responder, the Flutter view moves up to accommodate the keyboard.  When the keyboard and native view controller are dismissed, the view does not reset, and still looks like a keyboard is present at the bottom. 

Note "Launch external screen" is centered at the beginning, and higher after the view controller is dismissed:

https://user-images.githubusercontent.com/682784/142705925-2e1ef42d-b13a-49a0-80fa-8a2b137d8311.mov

From internal bug report: 
> I guess this is what happened:
> 1. When launching the iOS screen with textField as the first repsonder, keyboard started to show during transition
> 2. Flutter view captured the event and corresponded to it (move the view up)
> 3. When the screen is dismissed, Flutter view never capture any "keyboard dismissed" event and hence the view is not reset.

### Steps to reproduce:
```
$ flutter create -t plugin --platforms ios test_plugin
```

<details>
  <summary>ios/Classes/SwiftTestPlugin.swift</summary>

```swift
import Flutter
import UIKit

public class SwiftTestPlugin: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "test_plugin", binaryMessenger: registrar.messenger())
    let instance = SwiftTestPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)
  }

  public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    let vc = TextFieldViewController()
    vc.modalPresentationStyle = .fullScreen
    UIApplication.shared.keyWindow?.rootViewController?.present(vc, animated: true, completion: nil);
  }
}

class TextFieldViewController: UIViewController{
  override func viewDidLoad() {
    super.viewDidLoad()
    let sampleTextField =  UITextField(frame: CGRect(x: 20, y: 100, width: 300, height: 40))
    sampleTextField.placeholder = "Enter text here"
    sampleTextField.font = UIFont.systemFont(ofSize: 15)
    sampleTextField.borderStyle = UITextField.BorderStyle.roundedRect
    sampleTextField.autocorrectionType = UITextAutocorrectionType.no
    sampleTextField.keyboardType = UIKeyboardType.default
    sampleTextField.returnKeyType = UIReturnKeyType.done
    sampleTextField.clearButtonMode = UITextField.ViewMode.whileEditing
    sampleTextField.contentVerticalAlignment = UIControl.ContentVerticalAlignment.center
    sampleTextField.becomeFirstResponder()
    self.view.addSubview(sampleTextField)

    let button = UIButton(frame: CGRect(x: 20, y: 300, width: 300, height: 40))
    button.setTitle("Cancel", for: UIControl.State.normal)
    button.addTarget(self, action: #selector(didButtonClick), for: .touchUpInside)
    self.view.addSubview(button)
  }

  @objc
  func didButtonClick(sender: UIButton!) {
    self.dismiss(animated: true)
  }
}
```
</details>

<details>
  <summary>example/lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            MethodChannel('test_plugin').invokeMethod('fullScreen');
          },
          child: Text('Launch external screen'),
        ),
      ),
    );
  }
}
```
</details>

Run the example app on a physical device or simulator:
```
$ cd test_plugin/example
$ flutter run
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.758, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.758 at /Users/m/Projects/flutter
    • Upstream repository git@github.com:jmagman/flutter.git
    • Framework revision 570e39d38b (30 hours ago), 2021-11-19 03:03:04 +0900
    • Engine revision a3ef1d5351
    • Dart version 2.16.0 (build 2.16.0-20.0.dev)
    • DevTools version 2.8.0
```

**Comment by jmagman** [comment]
Bisected to https://github.com/flutter/engine/pull/29281 @luckysmg @gaaclarke

**Comment by jmagman** [comment]
When the keyboard is dismissed the `finished` BOOL passed to the completion block `-[UIView animateWithDuration:animations: completion:]` is `NO`, so `-[FlutterViewController ensureViewportMetricsIsCorrect]` isn't called before the `FlutterViewController` view reappears.

Calling `-ensureViewportMetricsIsCorrect` when `finished` is `NO` seems to resolve this.
https://github.com/flutter/engine/blob/485b37cda2b25a92bf6db5dc2fe9407fcb2fa3d4/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L1207-L1208
```diff
-          [self ensureViewportMetricsIsCorrect];
         }
+        [self ensureViewportMetricsIsCorrect];
```

I will work on a test for this on Monday.

**Comment by luckysmg** [comment]
When the keyboard dismiss ，the BOOL should be true&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Jenn Magder ***@***.***&gt;
Date: Sat,Nov 20,2021 10:48 AM
To: flutter/flutter ***@***.***&gt;
Cc: WenJingRui ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [flutter/flutter] Native iOS screen shows keyboard, underlyingFlutter view moves text up for keyboard, doesn't reset when keyboard/nativescreen dismissed (Issue #93944)





 
When the keyboard is dismissed the finished BOOL passed to the completion block -[UIView animateWithDuration:animations: completion:] is NO, so -[FlutterViewController ensureViewportMetricsIsCorrect] isn't called before the FlutterViewController view reappears.
 
Calling -ensureViewportMetricsIsCorrect when finished is NO seems to resolve this.
 https://github.com/flutter/engine/blob/485b37cda2b25a92bf6db5dc2fe9407fcb2fa3d4/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L1207-L1208
 -          [self ensureViewportMetricsIsCorrect];          } +        [self ensureViewportMetricsIsCorrect];
 
I will work on a test for this on Monday.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jmagman** [comment]
> When the keyboard dismiss ，the BOOL should be true

I stepped through it, in this scenario when the keyboard dismisses, it's `NO`.

**Comment by luckysmg** [comment]
Got it，I will take a look

**Comment by luckysmg** [comment]
I have tried your code and move the `ensureViewportMetricsIsCorrect`  outside the condition judgement like below:
```objective-c
completion:^(BOOL finished) {
        if (self.displayLink == currentDisplayLink) {
          [self invalidateDisplayLink];
        }
      [self removeKeyboardAnimationView];
      [self ensureViewportMetricsIsCorrect];
      }];
```
The problem seems to resolve.

https://user-images.githubusercontent.com/49340347/142716018-030a9260-e4f5-406c-bba3-3a76c663b8c9.MP4



But when I switch the keyboard very quickly,it will quickly jump one frame.The reason I wrote  `ensureViewportMetricsIsCorrect`  in the `finshed` condition is that: **When user switch keyboard very quickly,The open animation is not finshed and the close animation is about to start,if we still call `ensureViewportMetricsIsCorrect` this time, it will jump to the end position**,and move with `CADisplayLink` callback later.It will leads a jump...Here is the video...

https://user-images.githubusercontent.com/49340347/142716025-b975a953-e032-414f-a320-b3edab98a5c2.MOV

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/engine/pull/29862
