### ISSUE TITLE
Hello world takes too long to start on iPhone 12 Pro

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#94008]
## Steps to Reproduce

1. Create the usual 'pushed this many times' app
2. flutter run with iPhone 12 Pro

**Expected results:** 
App starts in reasonable time

**Actual results:** 
Splash screen showing for two minutes, console errors

![image](https://user-images.githubusercontent.com/1481807/142815899-848dee07-d084-4c70-9d12-dd3e5f2897f8.png)
[console.txt](https://github.com/flutter/flutter/files/7578727/console.txt)

My previous ticket #93906 was closed I believe by mistake, because it does not have to do with pubspec dependencies

**Comment by danagbemava-nc** [comment]
Hi @duzenko, if you went through [the issue I linked ](https://github.com/flutter/flutter/issues/72161) you would see that other users also reported the same issue with the `flutter create` project. Kindly see screenshot below

![Screenshot 2021-11-22 at 11 03 50](https://user-images.githubusercontent.com/88313112/142850708-a24ace2d-d89b-45d2-ada8-6e4511ca67da.png)
 
As I said earlier, because the issue doesn't always reproduce, that's why a concrete fix hasn't been provided. See this comment here https://github.com/flutter/flutter/issues/79987#issuecomment-816847272

**Comment by duzenko** [comment]
There are all kinds of comments but I don't think that technically qualifies as duplicate 
Unless I can see a response from Flutter that acknowledged the problem with all apps on this iPhone, including hello world, and does not have anything to do with dependencies, size, etc

**Comment by duzenko** [comment]
Anyway, what helped me was https://docs.flutter.dev/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Thanks for nothing
