### ISSUE TITLE
Autocomplete example on Flutter API webpage is not working as expected

### ISSUE THREAD

**Issue by thumbert** [flutter/flutter#94057]
## Steps to Reproduce

Navigate to https://api.flutter.dev/flutter/material/Autocomplete-class.html
look at the second example (This example shows how to create an Autocomplete widget with a custom type. Try searching with text from the name or email field.)

For example if I type 'x', the autocomplete suggests Alice and Bob.  Not OK. 

![Screenshot from 2021-11-22 14-33-07](https://user-images.githubusercontent.com/392827/142924332-2cb1b8bc-52e6-426a-835d-e9c09357ec34.png)

Thanks,
Tony

**Comment by danagbemava-nc** [comment]
Hi @thumbert, the code is actually working as it should. 

If you take a look at the definition of `toString()` on the `User` object, you find 

```dart
@override
  String toString() {
    return '$name, $email';
  }
```

and the code that does the pattern matching is defined as below

```dart
return option
              .toString()
              .contains(textEditingValue.text.toLowerCase())
```

So what happens is, during pattern matching, it converts the user to a string to see if it contains the text entered. 

Alice and Bob have emails set as `alice@example.com` & `bob@example.com` respectively, so typing `x` will return Alice and Bob because their emails contain `x` 

If you want to search by `name` only, you can change it to 

```dart
return option
			.name.toLowerCase()
			.contains(textEditingValue.text.toLowerCase())
``` 

The same can be done for email. 

The current code as it is makes it easier for you to search by either of them, which can be useful under certain circumstances. 

Does this sufficiently explain the behaviour to you?

**Comment by thumbert** [comment]
Yes, apologize for the noise.  I should have read the code!
