### ISSUE TITLE
Hot Restart fails for apps using packages with conditional imports

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#9413]
Hot Reload works fine.  Hot Restart crashes the app.  Hot Restart works fine in the `flutter create` template example on the same machine.

How do I go about getting more debug information for you?

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Stuff/Projects/flutter
    • Framework revision ecdfe65828 (2 days ago), 2017-04-12 23:13:32 -0700
    • Engine revision bcc8779cb8
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/eseidel/Library/Android/sdk/
    • Platform android-N, build-tools 22.0.1
    • ANDROID_HOME = /Users/eseidel/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.1)
    • Dart plugin version 171.4073.40
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 6 • EE230D8B-B327-4B27-9008-0290BC320663 • ios • iOS 10.3 (simulator)
```

**Comment by eseidel** [comment]
```
🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
The Observatory debugger and profiler is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Performing full restart...                                
error: Unable to read Dart source 'package:resource/src/io_io.dart'.
Application finished.
```

**Comment by eseidel** [comment]
package:resource appears to use a conditional import:

```
import "io_none.dart"
    if (dart.library.html) "io_html.dart"
    if (dart.library.io) "io_io.dart"
    as io;
```

Maybe that breaks Hot Restart?

**Comment by mit-mit** [comment]
This repros for me easily:

1. `flutter create testapp`
1. Replace all of `lib/main.dart` with:
```
import 'package:resource/resource.dart';

void main() {
  Resource r;
}
```
3. `flutter run`
4.  Hit `R` (restart)

**Comment by mit-mit** [comment]
cc @a-siva

**Comment by sivachandra** [comment]
I think @eseidelGoogle is correct in his conclusion that the conditional import is causing the problem. What I notice is that the file io_io.dart is not copied over to the device where as the VM is trying to import io_io.dart as part of the reload. I am still trying to figure out if io_io.dart should be copied over to the device, or if the VM is wrong in expecting io_io.dart to be available.

**Comment by sivachandra** [comment]
To be precise, `io_none.dart` is being copied over to the device and not `io_io.dart` or `io_html.dart`.

**Comment by sivachandra** [comment]
I think flutter uses analyzer to determine the list of files (of the dependencies) to send over to the device. While a dependencies file is generated by `gen_snapshot` as well, it seems to me that this file is ignored when determining the files to send over to the device.

The list of files of the dependencies as generated by `gen_snapshot` is correct (for this example, it includes `io_io.dart` and not `io_none.dart`). But, the list of dependencies generated by the analyzer is not correct! However, I am not sure that the analyzer is to blame. The [conditional import proposal](https://github.com/munificent/dep-interface-libraries/blob/master/Proposal.md#examples) states that tools like analyzers only care about the _default_ import:

_The first URI is always the interface or default library. It's the library that things like IDEs and static analyzers see. It's where you go to if you "Go to Definition" on a member declared in the configured library._

Consequently, for the example used in this issue, the default import file `io_none.dart` is being pushed to the device, and not the file (`io_io.dart`) that will actually be imported by the VM.

One way to solve this problem is to use the dependencies file generated by `gen_snapshot` to push files over to the device the first time an app is pushed to the device. Subsequent hot reload related pushes can depend on the list of files generated by the analyzer (the analyzer is required at his point at least to determine the change in dependencies).

**Comment by sivachandra** [comment]
I have a demo [change](https://github.com/flutter/flutter/commit/1494aa16c4e82c9bba5a3ab8a236b5622e5e48b5) which fixes this issue.

As explained in a previous comment, flutter gets the dart dependencies from analyzer. However, analyzer does not deal with conditional imports correctly. So, the above change uses the union of, i) the dependencies as reported by the analyzer, and ii) the dependencies generated by gen_snapshot.

I am calling my above change a demo because I would like to get feedback on the trade offs involved here (the change also needs some cleanup). Is running gen_snapshot during hot-reload OK? Though the above change takes the union of the analyzer + gen_snapshot outputs, we can do away with the analyzer output completely. However, does it mean that compilation errors in the _dirty_ code get detected after getting pushed to the device? Is that acceptable?

I discussed this with @rmacnak-google offline, but feel free to add others relevant. Adding @a-siva for suggestions.
