### ISSUE TITLE
Flutter doesn't run after changing app name

### ISSUE THREAD

**Issue by wiradikusuma** [flutter/flutter#94155]
## Steps to Reproduce

1. Clone a popular Flutter library https://github.com/jhomlala/betterplayer
2. Run the example app in iOS Simulator using `flutter run` — it will run
3. In `pubspec.yaml`, change `name: better_player_example` to `name: app`
4. Repeat step 2, it will fail.

Or, just watch the screencast: https://p120.p4.n0.cdn.getcloudapp.com/items/yAu0ejPk/5ef68faf-45c4-4c2e-8433-c0e3bc396042.mp4

**Expected results:**

The app can run.

**Actual results:**

The app doesn't run.

**Comment by maheshmnj** [comment]
I believe This is the expected behavior, If you change the name of the app the path references to some of the dependent files will change and hence the app would fail to build the error in your video clearly explains this  

> couldn't resolve the package 'better_player_example` ...

Closing as this isn't an issue with flutter, If you disagree feel free to write in the comments and I will reopen it.

Thank you.
