### ISSUE TITLE
flutter web is so painful to work with hot restart crash all the time 

### ISSUE THREAD

**Issue by anasssanba1** [flutter/flutter#94161]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by anasssanba1** [comment]
i need to kill my app and rebuild every time to see changes :(

**Comment by anasssanba1** [comment]
something really weird happening the images can not load correctly as well is there a bug??????????

**Comment by anasssanba1** [comment]
![DSDSDSDS](https://user-images.githubusercontent.com/83970851/143282670-c035dcd5-1b5d-439d-91f4-e1a26becefa0.PNG)

**Comment by anasssanba1** [comment]
WTF IS THIS

**Comment by stuartmorgan** [comment]
The issue template is there because the information it asks for is necessary for us to be able to investigate an issue. A crash on hot restart is definitely a bug, so please file a new issue and fill out all of the information requested in the template so that we can investigate. Without that information, there's nothing we can do.

> WTF IS THIS

Please review our code of conduct before engaging further here.
