### ISSUE TITLE
podhelper.rb preventing Flutter POD from updating 

### ISSUE THREAD

**Issue by cefitzger** [flutter/flutter#94230]
The 'fake' podspec generated by the podhelper.rb script overwrites the Flutter.podspec file, effectively hard-coding the 1.0.0 POD version into the Podfile.

Lines 155 - 190 need to be adapted for iOS apps.
Lines 193 - 228 need to be adapted for macOS apps.

**Comment by stuartmorgan** [comment]
The Flutter dependency is coming from the local filesystem; its actual version is whatever version of Flutter you have installed. There is no updating to be done.

The podspec is just a placeholder to resolve dependencies to the local version, and the version there is irrelevant.

**Comment by cefitzger** [comment]
I have had various versions of Flutter installed up to and including 2.5.1 but pod update never managed to update the flutter POD, so something is not working correctly.

**Comment by stuartmorgan** [comment]
> but pod update never managed to update the flutter POD

Again, there is no updating to be done by `pod`.

**Comment by cefitzger** [comment]
So it should just stay on 1.0.0 forever?
```
pod outdated output:

The following pod updates are available:
- abseil 0.20200225.0 -> (unused) (latest version 1.20210324.0)
- BoringSSL-GRPC 0.0.7 -> 0.0.7 (latest version 0.0.19)
- Firebase 8.6.0 -> (unused) (latest version 8.7.0)
- FirebaseAnalytics 8.6.0 -> 8.6.0 (latest version 8.7.0)
- FirebaseAuth 8.6.0 -> 8.6.0 (latest version 8.7.0)
- FirebaseCore 8.6.0 -> 8.6.0 (latest version 8.7.0)
- FirebaseFirestore 8.6.0 -> 8.6.0 (latest version 8.7.0)
- FirebaseMessaging 8.6.0 -> 8.6.0 (latest version 8.7.0)
- Flutter 1.0.0 -> 1.0.0 (latest version 2.5)
- GoogleAppMeasurement 8.6.0 -> 8.6.0 (latest version 8.7.0)
- GoogleSignIn 5.0.2 -> 5.0.2 (latest version 6.0.2)
- gRPC-C++ 1.28.2 -> 1.28.2 (latest version 1.40.0)
- gRPC-Core 1.28.2 -> 1.28.2 (latest version 1.40.0)
```

**Comment by stuartmorgan** [comment]
That output will always report 1.0.0, yes.

**Comment by cefitzger** [comment]
OK, can you point to some documentation that explains why because I couldn't find anything? It would be useful if the project explained that because I've had a number of instances where I needed to update other pod in my flutter project to support other functionality. It's not clear why the flutter pod should be different where there are different podspec files on the CocoaPods repo.

**Comment by stuartmorgan** [comment]
> OK, can you point to some documentation that explains why because I couldn't find anything?

I'm not aware of any documentation on this topic (we don't generally document internal build details), but I explained why above: because the version of Flutter you are using is local, and comes from your Flutter installation. It's not actually a pod. There's just a shim to allow plugins to reference it so they can build.

> It's not clear why the flutter pod should be different

Because the Flutter SDK that you are using to build your application includes the Flutter framework. It's the same reason that you specify versions of all of the Dart packages you depend on in pubspec.yaml, but don't specify a Flutter version there.

>where there are different podspec files on the CocoaPods repo.

The Flutter pod in the CocoaPods repository is not used when building a Flutter application. IIRC it's there for some very niche use cases where people make standard pods that include Flutter content as an implementation detail.

**Comment by cefitzger** [comment]
Thank you, that's a very clear explanation. I appreciate you taking the time.
I still wonder why:
a) this can't be indicated on the Flutter docs under the [Platform Setup](https://docs.flutter.dev/get-started/install/macos#deploy-to-ios-devices);
b) put a version like 99.99.99 in podhelper.rb so it's obvious it not relevant/obsolete.
