### ISSUE TITLE
[web] Release app creates nested assets folders causing images to not load when web site is deployed

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/flutter#94469]
## Steps to Reproduce
1. Create a Flutter app
2. Add assets folder
3. Update pubspec.yaml
```
  assets:
    - assets/
```
4. Copy an image into the assets folder
5. Replace _HomeState with the below code.  You'll need to change the name of the image to match your image and also the height and width to match your image.
```
class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Image.asset(
        'carriedaway.jpg',
        width: 750,
        height: 1000,
      ),
    );
  }
}
```
6.  Using Chrome, run the app without debugging, the app will display the image correctly.
7. Build web app  `flutter build web --release`

**Expected results:**
No nested assets folders.

**Actual results:** 

Nested assets folders

![2021-12-01_11-03-57](https://user-images.githubusercontent.com/79998776/144269395-386f4a98-5c0d-4184-8103-b65d3764ba94.jpg)

##Running the app locally
When running the app locally the image URL is:  `http://localhost:50788/assets/carriedaway.jpg`

##Final Result
After deploying the above web app, the image will not display in the browser.  The browser developer tools show a 404 error when attempting to get the image.  

When running the app deployed the image URL is `http://mydomainname/assets/carriedaway.jpg` which causes a 404 because the `flutter build web --release` built the app with nested assets folders.

**Comment by maheshmnj** [comment]
HI @longtimedeveloper, Thanks for filing the issue. You should provide the complete assets path 

> Image.asset(
        'carriedaway.jpg',

should be ` assets/carriedaway.jpg`

You can read more about using local assets in a flutter app here https://docs.flutter.dev/development/ui/assets-and-images
The reason it works locally I believe is due to this issue https://github.com/flutter/flutter/issues/86833

**Comment by longtimedeveloper** [comment]
@maheshmnj your comment does not address the issue of the nested assets folded created when the web app is built.  When built, adding `assets `does not  fix the problem, a 404 error is returned.  

FYI:  If you add assets to `Image.asset `code the image won't display.

Karl

**Comment by maheshmnj** [comment]
> @maheshmnj your comment does not address the issue of the nested assets folded created when the web app is built. When built and deployed, adding assets does not fix the problem, a 404 error is returned.

I do see a nested `assets` folder under  `build/web/assets`, but I believe this is intended and the reason you are seeing 404 is mainly because of an incorrect asset path in your code. Can you please share the exact error that you see in chrome dev tools. 

> FYI: If you add assets to Image.asset code the image won't display.

`Image.asset` does work locally as well as with deployed app, if you provide the correct path referencing the `assets/` folder. here's a demo app deployed for your reference https://flutter-routes.netlify.app/ (visit screen2)

> I'm hoping that the actual error of the build creating nested assets folders can get addressed and be the focus of this issue.

It would be great if you can share the exact error.

Thanks

**Comment by longtimedeveloper** [comment]
@maheshmnj I solved the problem.  I think it was the browser cache.  When I ran the **DEPLOYED** app the first time, the previous files must have been in the cache which caused it to use those files.  When I did a force-reload, the app run and the images were displayed correctly.

The 404 error was caused because the image URL from the previous run was different than the image URL for the recently deployed app.

Unfortunately, when the Flutter web app is built, all of the critical files are not given unique version numbers which would solve this problem.

Closing the issue, thank you.
