### ISSUE TITLE
luci-engine check was green when the tree was red

### ISSUE THREAD

**Issue by aam** [flutter/flutter#94483]
https://github.com/flutter/engine/pull/30005 and https://github.com/flutter/engine/pull/30004 had green 
luci-engine check even though the tree has been red(for ~7 hours) when they landed.

![image](https://user-images.githubusercontent.com/381137/144294440-2a2a6f21-1b4d-4cc6-a9fd-12a968de6c2d.png)

**Comment by CaseyHillers** [comment]
There was a 5 hour delay of Linux Web Engine closing the tree. The linked PRs were manually merged instead of using the waiting for tree to go green bot, which looks like they did have red tree status checks on them.

@dkwingsmt can you confirm this?

**Comment by aam** [comment]
> There was a 5 hour delay of Linux Web Engine closing the tree. The linked PRs were manually merged instead of using the waiting for tree to go green bot, which looks like they did have red tree status checks on them.

Where do you see red tree status checks?
Here is where I see green luci tree check(https://github.com/flutter/engine/pull/30005):

![image](https://user-images.githubusercontent.com/381137/144300147-0c39d785-88a2-4d35-b854-d2113a8bb9fc.png)

**Comment by dkwingsmt** [comment]
Ok, should I revert them?

**Comment by CaseyHillers** [comment]
> Ok, should I revert them?

No need

@aam thanks! I missed those. I'm digging into the BigQuery to debug what happened here.

**Comment by CaseyHillers** [comment]
This is blocked on https://github.com/flutter/flutter/issues/94487 as our metrics have been recording green for the engine since 11/23, which isn't the case.

**Comment by keyonghan** [comment]
The culprit is: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/push_build_status_to_github.dart#L63,

it uses default `master` as commit branch if not specified. This causes the API to use only these three builders (`Linux Benchmarks`, `Linux Framework Smoke Tests`, `Linux Web Framework tests`) data to calculate tree status.

We need to specify the branch explicitly before all repos are migrated to main.
