### ISSUE TITLE
Update iOS Templates to Automatically Create dSYMs for Debug Builds

### ISSUE THREAD

**Issue by eacrh** [flutter/flutter#94607]
## Use case
When building an app in debug mode, modifications to the generated Xcode project are needed in order to generate the necessary debug symbol files. Debug builds are used for configuration and testings, so having these symbol files is useful during the development process.

## Proposal
The templates located in the following paths need to have the DEBUG_INFORMATION_FORMAT property set to "dwarf-with-dsym" instead of "dwarf".

iOS Objc: flutter/packages/flutter_tools/templates/app_shared/ios-objc.tmpl/Runner.xcodeproj/project.pbxproj.tmpl
iOS Swift: flutter/packages/flutter_tools/templates/app_shared/ios-swift.tmpl/Runner.xcodeproj/project.pbxproj.tmpl
MacOS: packages/flutter_tools/templates/app_shared/macos.tmpl/Runner.xcodeproj/project.pbxproj.tmpl

**Comment by jmagman** [comment]
This was a request from Crashlytics: "The reason for this is that when customers are initially onboarding Crashlytics, they tend to test their set up in debug mode. We've seen a fairly high number of customer support tickets related to onboarding not working as expected because the dsyms aren't generated by default for debug builds. Making this change will enable customers to get up and running with minimal confusion."

This change would increase build times in debug mode for all users since it will need to build and link in the dSYM, though I'm not sure by how much for a nontrivial project.  Do we really need to support users onboarding Crashlytics in debug mode?  It seems like it could be solved with documentation.

**Comment by jmagman** [comment]
You could also consider setting this yourself in the plugin `.podspec`
```ruby
s.user_target_xcconfig = { 'DEBUG_INFORMATION_FORMAT' => 'dwarf-with-dsym' }
```

[CocoaPods says](https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig) "This attribute is not recommended as Pods should not pollute the build settings of the user project and this can cause conflicts." however this build setting doesn't seem like one that would be in danger of conflicts, like, say, framework search paths.  And Flutter is already "polluting" the generated Xcode project with various build settings to get the dart code compiled.

If that doesn't work for some reason, this seems like an okay thing to change if a clean build for a relatively complicated app is only trivially slower.

**Comment by jmagman** [comment]
> You could also consider setting this yourself in the plugin `.podspec`

An additional advantage to this is that you would control it, and it would apply for all plugin consumers, not just ones with a freshly-created Flutter app.

**Comment by jmagman** [comment]
@eacrh closing this since https://github.com/firebase/flutterfire/pull/7872 is done.  I don't think we want to do this generically for all Flutter apps.  Let me know if you need anything else from our side.
