### ISSUE TITLE
Selectively disable dirty region management and re-paint the whole scene

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#94622]
One thing that was notices when benchmarking damage rect computation and rendering on lower end Android devices was that this can increase the worst-case raster time and potentially lead to additional frame drops due to the added computation. This is particularly apparent when considering transitions and changes that result in repainting majority of the scene.

This issue is to explore mechanisms in which we can fast-path ignore and repaint the whole scene in some scenarios. For example whole screen transitions and animations that change a rather large percent of scene frame over frame.

cc: @dnfield

**Comment by dnfield** [comment]
@goderbauer

**Comment by dnfield** [comment]
@iskakaushik Can you explain a bit more about why we can't detect this in the rasterization process?

Is the idea that we need something to help the layer tree diffing algorithm short circuit more quickly, or something else?

**Comment by iskakaushik** [comment]
The current rasterization process is:
1. Compute damage rect
2. Preroll
3. Paint

I'm hoping to avoid doing step 1 with a little help from framework. This is a short circuit for cases where we know the whole scene or a majority will change.

**Comment by dnfield** [comment]
Can we use any of the layer tree diffing logic that already exists to bail out early in step 1 if some layer that covers a large portion of the scene is different? Perhaps you could point out the implementation for step 1?

**Comment by knopp** [comment]
That is quite weird. Calculating the diff should be a fairly cheap process. Most expensive part would be comparing PictureLayers (because of Skia limitation we serialize pictures and compare serialized data). This should disappear though once DisplayLists are being used everywhere (not sure what is that status of that).

Another thing to consider is that there might be penalty if clip is not aligned to certain number, and also I could imagine something like repainting 90% of frame might be more expensive (due to clip and reusing surface) than repainting whole frame. 

It would be great to know what exactly causes the slowdown. Diffing itself is a fairly contained process, it shouldn't be too difficult to time it to see if it takes too long.

**Comment by jonahwilliams** [comment]
Many years later, but even with display list picture comparison is quite slow on Android. We could re-evaluate at some point, but given that we disabled partial repaint on android due to bugs this particular issue is obsolete
