### ISSUE TITLE
ci.yaml validation fails with "generateGitHubToken failed"

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#94635]
I saw one instance of this error when pushing a change to https://github.com/flutter/flutter/pull/94616 (doesn't include ci.yaml changes).  I can't repro it.

![ci_yaml_fail](https://user-images.githubusercontent.com/8867023/144679037-45bcac49-8fac-42de-9007-b4ca8f469ac6.png)
 
cc @CaseyHillers

**Comment by CaseyHillers** [comment]
https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/config.dart;l=287-313;drc=c9a5c6d022f2067cd9d8bce52372e729d2901cbb somewhere here is failing to generate a string. I'm not sure it's the datastore related fields, and it may be due to the JwtBuilder timing out. I'll look into adding some debug logs to better understand where we're getting to.

**Comment by CaseyHillers** [comment]
Another instance - https://github.com/flutter/flutter/pull/89451/checks?check_run_id=4461162168

Based on the logs, this seems to happen a few times a day

**Comment by CaseyHillers** [comment]
The issue is we're being rate limited (so you'll see this in short bursts)

```
{
  "documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."
}
```

**Comment by gspencergoog** [comment]
Ahh, that makes sense.

**Comment by CaseyHillers** [comment]
I'm deploying a new release now. Should be fixed in ~10 minutes.
