### ISSUE TITLE
github bot doesn't recognize XCTests in integration tests as tests in flutter/flutter repo

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#94882]
See https://github.com/flutter/flutter/pull/94878

The PR edited an XCUITests but the bot says there's no test.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by cyanglaz** [comment]
I'm not sure if this is fixed. We should reopen this and evaluate. 
To repro, create a PR similar to https://github.com/flutter/flutter/pull/94878 and see if the bot picks up the test change.

**Comment by godofredoc** [comment]
Actually this may be related to a different item we were planning to work on for the fix it.

**Comment by darshankawar** [comment]
Adding `team` label for now. @godofredoc please update the label as applicable since `team-infra` also seemed to be removed earlier.

**Comment by Hixie** [comment]
@cyanglaz To fix this we just need to update https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/github/webhook_subscription.dart to have the new logic.

Since anyone can do that (it's not something that the infra team owns), I'm going to close this issue. Please don't hesitate to add more logic for detecting what PRs don't need tests!
