### ISSUE TITLE
[cocoon] Auto submit bot failing on Null is not a subtype of String

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#95023]
_checkPRs error in flutter/cocoon: type 'Null' is not a subtype of type 'String' in type cast

This may be similar to https://github.com/flutter/flutter/issues/94635 however we're seeing this 100% of the time.

The GitHub tokens may be expired

**Comment by CaseyHillers** [comment]
\cc @godofredoc can you check the admin settings of flutter/cocoon to see if we need to refresh the flutter dashboard token?

**Comment by godofredoc** [comment]
Flutter Dashboard use app certificates, let me check if the certificate has expired. Is the flutter-dashboard completely broken?

**Comment by keyonghan** [comment]
This is due to a github graphql query result mis-reference: https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart;l=214;drc=3dbbe41f8ee41143c98f01b907850085fd633195;bpv=0;bpt=0

The `authorAssociation` doesn't belong to pullRequest, but the sub [reviews][nodes].

**Comment by keyonghan** [comment]
Adjust priority per https://github.com/flutter/flutter/issues/95024

**Comment by keyonghan** [comment]
The bot is working now: https://github.com/flutter/flutter/pull/94012
