### ISSUE TITLE
bot not landing changes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#95024]
The 'waiting for tree to go green' bot doesn't appear to be landing things. The framework tree has been green overnight, and this Engine -> Framework roll (https://github.com/flutter/flutter/pull/94964) was ready to land 18+ hours ago, but the bot hasn't landed it. (I am going to land it manually now.)

**Comment by zanderso** [comment]
Also happening for the Engine repo. For example for the Dart -> Engine roll: xhttps://github.com/flutter/engine/pull/30259

**Comment by CaseyHillers** [comment]
Weird, Cocoon is seeing an explicit issue 100% of the time in https://github.com/flutter/flutter/issues/95023

I wonder if we need to refresh our GitHub tokens for all the repos

**Comment by keyonghan** [comment]
This is due to a github graphql query result mis-reference: https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart;l=214;drc=3dbbe41f8ee41143c98f01b907850085fd633195;bpv=0;bpt=0

The `authorAssociation` doesn't belong to pullRequest, but the sub [reviews][nodes].

**Comment by keyonghan** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/95024.
