### ISSUE TITLE
Package READMEs should include scoped link to issues

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#95020]
## Use case

Developers find it difficult to see open issues for a given plugin, because they don't know that we use the main repo with an issue tag, or they are unfamiliar with how to scope a search to a specific tag, or they do not know the name of the tag corresponding to the given package.

## Proposed Solution

The README in each package should include a link to issues database with query scoped to that package’s issue tag. That will help developers see existing issues, avoid duplicates, and even give package developers a quick shortcut.

**Comment by stuartmorgan** [comment]
This is exactly what the "View/report issues" link on pub.dev does. What's the advantage of duplicating that?

**Comment by esDotDev** [comment]
It seems this was fixed last may, which I didn't realize so that's awesome!
https://github.com/flutter/plugins/pull/3927

It's probably not necessary to callout a link in the readme anymore, but one thing you might consider: Developers for the last 3+ yrs have learned that clicking _Issues_ in any of the official plugins dumps you in the general issues tracker, a callout might be worthwhile, just due to that reality, and the mental muscle memory that might be built up there (developers assume they know where that link is going to go)

I did notice that some of the deprecated packages to not have this change, like: https://pub.dev/packages/battery. Even if these are discontinued, it's helpful for developers to be able to quickly see existing issues.

**Comment by darshankawar** [comment]
@timsneath Hi,
Per @stuartmorgan's comment, we do see a list of open issues filtered to the said plugin currently by accessing `view/report issues` from the readMe page. For ex: I opened flutter `camera` plugin and clicked on `View/report issues` which showed list of open issues for that plugin.
For many of the third party plugins, `View/report issues` directs to dedicated repo. Can you please let us know if this helps ?
