### ISSUE TITLE
Migrate the flutter/flutter repository to use main as the primary development branch/channel

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#95041]
This is an umbrella tracking issue.

**Comment by Hixie** [comment]
cc @godofredoc

**Comment by mit-mit** [comment]
@godofredoc @Hixie currently `master` is part of our public "API" in the `flutter` tool in the `channel` command. Would it make sense to start by introducing `master` as an "alias" for `main` in `flutter channel` so that both `flutter channel main` and `flutter channel master` would be valid commands for getting primary development channel? That would allow folks to start to use the proper "main" channel verbiage immediately, and would later make it a non-breaking change to update the underlying git branch name.

**Comment by christopherfujino** [comment]
> @godofredoc @Hixie currently `master` is part of our public "API" in the `flutter` tool in the `channel` command. Would it make sense to start by introducing `master` as an "alias" for `main` in `flutter channel` so that both `flutter channel main` and `flutter channel master` would be valid commands for getting primary development channel? That would allow folks to start to use the proper "main" channel verbiage immediately, and would later make it a non-breaking change to update the underlying git branch name.

This makes sense. Then we can have a migration phase where we, for example, update documentation.

**Comment by godofredoc** [comment]
We are already mirroring master to main adding the alias may be straightforward. @christopherfujino can you please point to the place where we can make the change?

**Comment by christopherfujino** [comment]
> We are already mirroring master to main adding the alias may be straightforward. @christopherfujino can you please point to the place where we can make the change?

This is the source for the `flutter channel` command: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/channel.dart

It looks like that command does one of two things (depending on whether or not there is a trailing argument): list available channels (with the `_listChannels()` method) or change the current channel (with the `_switchChannel()` method).

It looks like _listChannels() depends on https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/version.dart#L42 `kOfficialChannels`, which then depends on https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/globals.dart#L280 `kDefaultFrameworkChannel`

**Comment by Hixie** [comment]
Making `main` an alias for `master` SGTM.

**Comment by mit-mit** [comment]
@godofredoc @gspencergoog @christopherfujino what is the status of the `master` to `main` renaming?

**Comment by gspencergoog** [comment]
In https://github.com/flutter/flutter/pull/115388 Godofredo added an alias for master called main, and the two branches are always in sync (the have all the same commits, with all the same hashes, etc). Users can use the two branches interchangeably in git operations (pull, fetch, etc.), and they can switch to the "main" channel instead of the "master" channel with `flutter channel`.  We still have master-api.flutter.dev as a site, but not main-api.flutter.dev for the API docs on that channel.

AFAIK, We do still use master in some of the CI scripts, but @godofredoc  and @christopherfujino know more about progress there than I do.

**Comment by mit-mit** [comment]
Cool, I think we can go ahead with changing the website then? https://github.com/flutter/website/pull/7856/files

@timsneath you asked that we waited until after Flutter Forward; is now OK?
