### ISSUE TITLE
Circular dependency Error

### ISSUE THREAD

**Issue by sonu161** [flutter/flutter#95162]
Circular dependency between the following tasks:
:firebase_messaging:generateDebugRFile
\--- :firebase_messaging:generateDebugRFile (*)

**Comment by danagbemava-nc** [comment]
The `firebase_messaging` plugin is not maintained by the `flutter` team. You may want to file this issue over [here](https://github.com/FirebaseExtended/flutterfire/issues/new/choose) so that it can be properly addressed. 

Please fill out the issue template completely the next time you file an issue. 

Closing as this is out of the scope of this issue tracker. 

Thank you
