### ISSUE TITLE
[web] cherrypick opt-in for new image decoders

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#95285]
Cherrypick https://github.com/flutter/engine/pull/30324.

The new image decoding approach does not yet meet the quality bar:

- https://github.com/flutter/flutter/issues/94318 - let's fix this before making them generally available.
- https://github.com/flutter/flutter/issues/94500 - this is partially addressed, but let's wait to see if the fix is effective enough.

**Comment by devoncarew** [comment]
@yjbanov - a few questions:

- this is a cherry pick request for about to be released beta (2.9), not the recently released stable (2.8)?
- this was for work that was just added in beta - this wasn't an issue in recent stable release (2.8)?

**Comment by yjbanov** [comment]
> * this is a cherry pick request for about to be released beta (2.9), not the recently released stable (2.8)?

Correct, this is for 2.9

> * this was for work that was just added in beta - this wasn't an issue in recent stable release (2.8)?

Correct, this issue appeared in 2.9. 2.8 is not affected.

**Comment by devoncarew** [comment]
Gotcha, thanks for the clarifications.

We don't have hotfixes windows planned for the next two weeks due to the holiday schedule. Our next one is the first week of Jan, but that's also when we're branching for the next beta (and stable). Unless we think this is serious enough to warrant its own release, it's likely that we'll just wait to get this with the next beta cycle.

**Comment by yjbanov** [comment]
Closing. The bug will not reach stable, and the beta cut for the stable candidate hasn't been cut yet. So we're good.
