### ISSUE TITLE
Share Plugin does not share text on Facebook!!!

### ISSUE THREAD

**Issue by Maham-1** [flutter/flutter#95312]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mamuseferha** [comment]
@Maham-1 
`share` plugin has been deprecated in favor of `share_plus` plugin. See this official documentation regarding the same, https://pub.dev/packages/share#deprecation-notice

Please report this issue here: https://github.com/fluttercommunity/plus_plugins/issues

I'll go ahead and close this now.
