### ISSUE TITLE
Document breaking change in LayerLink class

### ISSUE THREAD

**Issue by selcukguvel** [flutter/flutter#95464]
We were using `leader` getter of `LayerLink` class from `rendering/layer.dart`, but it seems it is removed with Flutter version `2.8.0` with this https://github.com/flutter/flutter/pull/92598.
I couldn't find this change in the list of breaking changes listed [here](https://medium.com/flutter/whats-new-in-flutter-2-8-d085b763d181) and any related migration guide [here](https://docs.flutter.dev/release/breaking-changes/2-5-deprecations).

Example usage we have:
```dart
final LayerLink _layerLink = LayerLink();
Offset(-(_layerLink?.leader?.offset?.dx ?? 0), -128)
```

**Comment by maheshmnj** [comment]
Hi @selcukguvel, Thanks for filing the issue. But it is mentioned in the [release notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.8.0)

> 92598 Leader not always dirty (a: text input, framework, f: material design, cla: yes, waiting for tree to go green)

**Comment by selcukguvel** [comment]
Hi @maheshmnj, yes it is in the release notes. 
Yet, since with this PR, a `getter` method that can be used by anyone for any purpose, is removed, it is a breaking change. 
I think it should be specified in the list of breaking changes and a migration guide should be specified for that.

**Comment by maheshmnj** [comment]
thanks for the clarification.

cc: @goderbauer

**Comment by goderbauer** [comment]
For Flutter a change is only breaking if it breaks one of the contributed tests (see also https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change). Since this change didn't require any changes to those tests it isn't considered breaking and no migration guide has been published. Please read the link above to learn how you can contribute tests to avoid being broken in the future.
