### ISSUE TITLE
cannot install webview_flutter, conflict with flutter_html

### ISSUE THREAD

**Issue by eggysudianto** [flutter/flutter#95608]
## pubspec.yaml
- flutter_html: ^2.2.1
- webview_flutter: ^3.0.0

## ERROR LOG

Because flutter_html 2.2.1 depends on webview_flutter ^2.0.4 and no versions of flutter_html match >2.2.1 <3.0.0, flutter_html ^2.2.1 requires webview_flutter ^2.0.4.
So, because otlink depends on both flutter_html ^2.2.1 and webview_flutter ^3.0.0, version solving failed.
pub get failed (1; So, because otlink depends on both flutter_html ^2.2.1 and webview_flutter ^3.0.0, version solving failed.)

**Comment by maheshmnj** [comment]
HI @eggysudianto, Thanks for filing the issue. From the error I can understand that 
- flutter_html 2.2.1 depends on `webview_flutter ^2.0.4`
- And your application depends on `webview_flutter: ^3.0.0`

So, Inorder to solve this conflict your application must depend on either `webview_flutter ^2.0.4` or `flutter_html` should upgrade its webview plugin to `webview_flutter: ^3.0.0`.

Because `flutter_html` is a third-party plugin we can really track this issue here. I would suggest you to please file the issue with the maintainer.

 Closing as this isn't an issue with flutter.
