### ISSUE TITLE
A Widget cannot be drawn partially on one page and the remaining on another page: It's insecable.

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#95626]
Please see this issue: 

https://stackoverflow.com/questions/70434570/an-inner-widget-tree-cannot-be-bigger-than-a-page-a-widget-cannot-be-drawn-part

**Comment by darshankawar** [comment]
@jazzbpn 
The link you shared does have a code but contains third party plugin and custom code, so in order to properly address the issue you are reporting, please provide a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party plugins along with `flutter doctor -v` .
