### ISSUE TITLE
[flutter-web] Allow developers to add id to html elements

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#95624]
## Use case

I would like to be able to find some element via id which I assigned to a widget in a flutter web app.

It's very hard / impossible to use solutions like usetiful (https://www.usetiful.com/) because they need to hook to some html element via id. Currently we have no way of adding id's to the widgets, and at best it looks something like in the screenshot:

<img width="1343" alt="Screenshot 2021-12-21 at 11 57 40" src="https://user-images.githubusercontent.com/6430214/146919050-b3ca4dd2-64a5-4bc5-a574-0d6374a6b068.png">

## Proposal

Use key property from widgets and add them to html element id, or provide another way of adding element ids.

**Comment by yjbanov** [comment]
We cannot support adding stable IDs to HTML nodes generated by the engine because the DOM structure is not stable. There's no 1-to-1 correspondence between widgets and DOM nodes. However, you can use platform views where you can create your own DOM nodes and assign arbitrary attributes, including `id`.
