### ISSUE TITLE
Same  issue while using location > > Same issue. Will try the `android.enableDexingArtifactTransform=false` fix

### ISSUE THREAD

**Issue by Sumanmali019** [flutter/flutter#95668]
> > Same issue. Will try the `android.enableDexingArtifactTransform=false` fix
> > It worked!
> 
> it does not work for me

It also does not work for me. I think this is a problem that emerged again recently.

_Originally posted by @arjinakgul in https://github.com/flutter/flutter/issues/72185#issuecomment-828040905_

**Comment by darshankawar** [comment]
@Sumanmali019 
Please don't open issues by using an issue comment. There's a new issue template you should use and fill out the requested detail so that we can address it properly. Always provide sufficient details regarding the issue so that we can work with it.
Closing from here. Please use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=).
