### ISSUE TITLE
Provide structured Widget & Render tree diagnostics data for tools

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#9568]
## Problem
The debug strings printed for flutter trees provide useful information but the quantity of data can be overwhelming for novice users. Provide a way for IntelliJ and other tools to display the data as interactive tree.

Imagine the Chrome Developer Tools Elements pane but without the ability to make edits as hot reload handles that case well enough as is.

## Proposed implementation
Refactor most of the toString code for the widget tree and other flutter trees to use an intermediate 
representation that is both appropriate for use to generate to toString output and for tools like IntelliJ. Refactor can be incremental as toString() and existing Dart object debug view display can just be used for classes without structured diagnostic data.  

Change [TreeDiagnosticsMixin](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/tree_diagnostics_mixin.dart) ```debugFillDescription```
and ```debugDescribeChildren``` members to 
return structured diagnostic data instead of strings.

## Related work 
JsonML output used by [Chrome DevTools custom formatters ](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview)
supports similar functionality. The main difference is individual flutter widgets have deep knowledge about what properties are relevant so it is better to embed formatting code within the individual flutter classes rather than keep it off to the side.

[Example](https://twitter.com/thespite/status/656499298230734849) using chrome devtools custom formatters to display vectors and matrices nicely when using threejs.

**Comment by Hixie** [comment]
SGTM. Make it so.

**Comment by sethladd** [comment]
Thanks @jacob314 !

**Comment by abarth** [comment]
Bonus points for unifying this code among our various trees.  Currently, we have a few different patterns because they grew up organically.

**Comment by Hixie** [comment]
Some things that we have to be able to represent:

* Labeled children. Different classes with multiple children label their children in subtly different ways. For examples, see RenderTable et al and RenderViewport/RenderSliverList.
* The _Theatre's dashed-line children, which are distinct from normal children.
* The RenderParagraph's children, which are very distinct from normal children.
* Properties sometimes have labels and sometimes do not, in the plain-text version. For example, sometimes if the property's value is an enum, we omit the name since it's redundant with the enum class name which is in the enum's toString representation. Presumably in an inspector names would always be present. See for example BorderRadius, BorderSide, Border, LinearGradient, etc.
* Sometimes some properties are omitted entirely in the toString version but would be included in an inspector. SliverGeometry for example omits anything redundant. The omitted values may want to be grayed out in a GUI.
* Sometimes specific values are called out. For example, RenderBox's toString, if it doesn't have a size, doesn't say "size: null", it says "size: MISSING" to draw attention to the problem. Another example is RenderConstrainedOverflowBox, where null is explained.
* Most objects have a toString of the form `ClassName#hashCode(property1, property2, property3)`. Some objects (in particular RenderObjects) use the form `ClassName#hashCode TAG1 TAG2` on the first line, and then have the properties on the next lines, indented.
* It should be possible for a property's value to itself have a structured data form.
* Some properties need to be describable even though getting them may throw an exception. See, for instance, RenderSliverPersistentHeader.
* It should be possible for properties to have somewhat elaborate text representations. In particular, see FlutterLogo, RenderSliverMultiBoxAdaptor, RenderTable, RenderView.

It's important that we don't regress the plain text experience because it's used in exception messages, terminal-based debugging, etc.
