### ISSUE TITLE
Flutter In App Purchase Android Error (in_app_purchase 2.0.1)

### ISSUE THREAD

**Issue by Cengizcpr** [flutter/flutter#95768]
`E/AndroidRuntime(18292): java.lang.NoSuchMethodError: No virtual method setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/~~u2jXq14JakaIgDRjUb7wsA==/com.osicrew.drunkbottle-e11S1q4Dt31t71wnWFn9hw==/base.apk)`

**Comment by darshankawar** [comment]
@Cengizcpr 
If you have `implementation 'com.android.billingclient:billing` as a dependency, try removing it and see if it helps.

**Comment by AdamBCo** [comment]
@darshankawar I'm experiencing this same error and do not have implementation 'com.android.billingclient:billing as a dependency anywhere in my code. Any idea what could be causing this? Thanks for the help. @Cengizcpr were you able to figure this out?

**Comment by dgilperez** [comment]
I just got hit by this. 

In my case, it appears to be caused by adding both `in_app_purchase` and `purchases_flutter` packages (which apparently adds this transitive dependency `com.android.billingclient:billing`.

If possible, I'd like to use both. And I don't think a hard crash without previous notice is intended ... would it be enough to reopen this? Is this due to a version conflicts with that library? Or is `in_app_purchase` totally unable to be added to the same project as `purchases_flutter`? 

@Cengizcpr @AdamBCo did you find a solution?
