### ISSUE TITLE
pop'ing and pushing the first route leads to black screen when back is pressed

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#9577]
When you have two routes, A and B, and you pop and push to Route B, pressing back on Route B should close the app, rather it takes you to a black screen, and then it doesn't respond to the back button anymore and I have to kill the app.

`Navigator.of(context)..pop()..pushNamed("/home");`

Video here https://www.dropbox.com/s/7vv90ddge9panrk/overflow2.mp4?dl=0

**Comment by Hixie** [comment]
I don't understand why the app wouldn't close when you do the first pop.

**Comment by FaisalAbid** [comment]
Not sure, I'm just trying to make sure the SplashPage route is poped from the back stack

**Comment by Hixie** [comment]
You probably actually want to be using pushReplacement or pushReplacementNamed.

**Comment by FaisalAbid** [comment]
Yes! thats what I was looking for!

**Comment by collinjackson** [comment]
The workaround for this bug is calling `SystemNavigator.pop()` if `Navigator.pop()` returns false.

**Comment by collinjackson** [comment]
One issue might be that `SystemNavigator.pop()` does nothing on iOS, because the human interface guidelines prohibit exiting the app. There shouldn't be a hardware back button on iOS, so this would only happen when pressing on screen buttons that pop the navigator. I think this is an argument for why on iOS putting a `/` route onto the stack below the deep-link if there's already is a good idea.

**Comment by Hixie** [comment]
The specific action we want to take on this bug is that calling `Navigator.pop()` should imply a `SystemNavigator.pop()` (via a callback installed by the WidgetsApp maybe) when appropriate (when there's only one route). On iOS this may need to assert or otherwise fail in some way, maybe just not popping the route at all.

**Comment by Hixie** [comment]
Specifically, this is to handle the case where the app was launched as a "subactivity" of another, and so there's a BackButton on the screen (or equivalent), and tapping that should pop the app off entirely (quitting it). On iOS this can't happen as I understand it.

**Comment by Hixie** [comment]
This will probably be addressed via https://github.com/flutter/flutter/issues/11490.

**Comment by Hixie** [comment]
My current ETA on this is that I expect to work on it in a couple of months, I'm working on RTL first. Please let us know if that time-frame isn't sufficient; we can work on more narrowly-scoped work sooner if it is urgent.

**Comment by Hixie** [comment]
Leaving in current milestone as it is a current priority (deep linking improvements).

**Comment by deepak-gehlot** [comment]
facing same issue.

**Comment by branflake2267** [comment]
I'm noticing when my route is '/' home, I can't observe the system back button navigation. I'm assuming you're already aware, but figured I'd add a note. 

1. route to '/'
2. click on android system back button
3. navigates to black screen, and it doesn't call didPop

```
class MyObserver extends RouteObserver<PageRoute<dynamic>> {
  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    super.didPush(route, previousRoute);
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic> previousRoute) {
    super.didPop(route, previousRoute);

    // I can't catch the system back button navigation here, when route is '/'. 
    print("didPop route=" + route.toString());
  }

  @override
  void didRemove(Route<dynamic> route, Route<dynamic> previousRoute) {
    super.didRemove(route, previousRoute);
  }
}
```

**Comment by branflake2267** [comment]
I've found the issue. Instead of calling _history.last.didPopNext(route) it should be calling SystemNavigator.pop() to exit. It's not able to determine that it's at the end of the stack and should exit. 

In this screenshot, both the last element in the _history stack, and the route it's trying to pop are both the same route. This seems odd, and could be used to determine it's at the end of the line and should exit.  
![screen shot 2018-01-04 at 10 14 42 pm](https://user-images.githubusercontent.com/1326504/34597665-f878e0a4-f19c-11e7-8feb-819b3044c45d.png)

**Comment by Hixie** [comment]
I'm going to close this in favour of https://github.com/flutter/flutter/issues/11490 which is basically the same thing. That bug itself will probably get closed as part of my Router work.

**Comment by 2015-lizaiyang** [comment]
Now it's all 2019, so how do we fix this, urgently?

**Comment by magician20** [comment]
Is there any solution for this problem ?

**Comment by jamesncl** [comment]
> Now it's all 2019, so how do we fix this, urgently?

FYI see the comment above about this issue being closed in favour of [#11490](https://github.com/flutter/flutter/issues/11490).  Thumbs up and comments on this issue probably aren't being followed by the flutter team, so won't help - go to issue [#11490](https://github.com/flutter/flutter/issues/11490) instead and **add a thumbs up to the first post**, the more reactions there are the higher up an issue gets prioritised by the flutter devs.

PS I managed to work around the issue by using `Navigator.pushReplacement` instead of `Navigator.popAndPush` - it might help in your case too?

**Comment by idileepd** [comment]
any solution ?

**Comment by AlexShniperson-INO** [comment]
my workaround with `WillPopScope` widget
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class SomeScreen extends StatefulWidget {
  final Widget child;

  SomeScreen({
    @required this.child,
  });

  @override
  State<StatefulWidget> createState() => _SomeScreenState();
}

class _SomeScreenState extends State<SomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: WillPopScope(
        onWillPop: () {
          if (Navigator.of(context).canPop()) {
            Navigator.of(context).pop();
          } else {
            // Android back button hack
            SystemNavigator.pop();
          }
          return Future.value(true);
        },
        child: widget.child,
      ),
    );
  }
}
```

**Comment by hiddenfloret** [comment]
`WillPopScope` worked for me also:

`return WillPopScope(
      onWillPop: () async => false,
      child: Scaffold(
        body: Container(
            child: TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text('Go back'),
                ),
              ),
      ),
    );`
