### ISSUE TITLE
when using texteditiputformatter with textformfield The following assertion was thrown during a platform message callback: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#b75bd(physicalKey: PhysicalKeyboardKey#00000(usbHidUsage: "0x1100000000", debugName: "Key with ID 0x1100000000"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: " ", timeStamp: 55:18:26.243770) 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 437 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'

### ISSUE THREAD

**Issue by AhkamKhalaaf** [flutter/flutter#95787]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@AhkamKhalaaf 
Please don't put the entire error message as issue title. Follow new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and provide the requested details in it so that we'll have enough details to work with. 
Closing as empty issue and no code or logs provided.
