### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-location:16.+.

### ISSUE THREAD

**Issue by shah000** [flutter/flutter#95822]
![image](https://user-images.githubusercontent.com/48676720/147410827-19994972-76b8-4e6f-8296-4444f2df2b48.png)

**Comment by darshankawar** [comment]
@shah000 
Please don't post screenshots of the error without providing any details about it. Whenever you open an issue, there's a new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) you should use and provide requested details so that we'll have enough info to work with.

Also, coming to your issue, it might occur due to conflict between packages you are using from `pubspec.yaml`, see [this](https://github.com/flutter/flutter/issues/95021#issuecomment-994836338) similar issue for your reference and check if it helps.
Also, your issue should be asked on support channels like StackOverflow.
Closing from here.
