### ISSUE TITLE
App gets freeze while recording

### ISSUE THREAD

**Issue by aditya-mahajan96** [flutter/flutter#95827]
I was recording video using   CameraController? _cameraController;
  _cameraController!.startVideoRecording();

 and after few seconds it got stuck on the screen 
Screenshot 1--------------
<img width="1246" alt="Screenshot 2021-12-26 at 11 53 44 PM" src="https://user-images.githubusercontent.com/84502466/147416883-09c1fdc0-f79f-4673-868d-46990bc1caea.png">
Screenshot 2---------
<img width="1187" alt="Screenshot 2021-12-26 at 11 54 01 PM" src="https://user-images.githubusercontent.com/84502466/147416897-a309b12a-d23f-4f45-97a2-08eb61499499.png">
Screenshot 3-------
<img width="1211" alt="Screenshot 2021-12-26 at 11 54 07 PM" src="https://user-images.githubusercontent.com/84502466/147416905-788be156-83be-4356-9bdd-38425511e125.png">

@darshankawar

**Comment by darshankawar** [comment]
@aditya-mahajan96 
Can you provide `flutter doctor -v`, camera plugin version, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate so that we can properly address this ?
Also provide the crash log in text format instead of in screenshots.
Thanks.
