### ISSUE TITLE
Android Add to App: Single Engine going from FlutterFragment->FlutterActivity and back

### ISSUE THREAD

**Issue by ryanneuroflow** [flutter/flutter#95877]
- I'm using a single FlutterEngine in an Add to App architecture.
- In the app, I have a FlutterFragment embedded in a tab bar. 
- I then open up a new full screen FlutterActivity.
- When I navigate back to the tab bar screen, the FlutterFragment is no longer associated with the FlutterEngine, and so won't draw itself or respond to events. 
- How can I re-associate the FlutterEngine with my FlutterFragment, without recreating the FlutterFragment? Or would recreating it be the best practice? On iOS I can set the FlutterEngine's viewController property, and everything works nicely. Can't find an equivalent in Android that is publicly accessible.

I believe this may be related to: https://github.com/flutter/flutter/issues/93905

Thank you!

**Comment by willlockwood** [comment]
I believe you're running into the same problem as detailed here: https://github.com/flutter/flutter/issues/49950

Essentially, I believe it's an intentional decision to discourage the association of multiple flutter view components with a single cached engine on Android. It seems like the direction they're going in is to encourage the [creation of multiple lightweight flutter engines](https://github.com/flutter/flutter/issues/72009) if you need multiple instances of flutter in an add-to-app use case. Here's the original design doc: https://docs.google.com/document/d/1fdKRufqUzQvERcqNIUSq-GdabXc4k8VIsClzRElJ6KY/edit#

I ran into this at my job where we were migrating a native app to Flutter and we had some hybrid navigation, and since we were expecting it to be a temporary situation for us, we ended up essentially forking the embedding library and following the customizations that were used to solve this problem in the thaw library: https://github.com/littleGnAl/thaw (this was suggested in a comment in the issue linked above). We then just have to run a diff whenever each time we upgrade flutter to resolve conflicts and make sure that our custom implementation is going to continue to work with the new embeddings.

There are other things you can do that help but aren't as thorough. For example, you technically could override `detachFromFlutterEngine` on `FlutterActivity` or `FlutterFragment` with an empty function—this will prevent the activity or fragment from calling `release` internally, which will keep your flutter experience alive when navigating. 

The downside there is that you currently can't prevent the engine from detaching from the plugins your flutter app is using (which can be an easy bug to overlook). Going with the solutions in the thaw library above will help you with that.

**Comment by willlockwood** [comment]
Ooh actually just saw this on that issue—looks like something was merged in the past month that might help make this not a problem in an upcoming flutter release: https://github.com/flutter/engine/pull/30202.

Doesn't solve your problem immediately, but from what I can tell on an initial read of that code, it seems to be aiming to fix this particular problem, which is phenomenal because it's a huge pain to work around this

**Comment by 0xZOne** [comment]
> * I'm using a single FlutterEngine in an Add to App architecture.
> * In the app, I have a FlutterFragment embedded in a tab bar.
> * I then open up a new full screen FlutterActivity.
> * When I navigate back to the tab bar screen, the FlutterFragment is no longer associated with the FlutterEngine, and so won't draw itself or respond to events.
> * How can I re-associate the FlutterEngine with my FlutterFragment, without recreating the FlutterFragment? Or would recreating it be the best practice? On iOS I can set the FlutterEngine's viewController property, and everything works nicely. Can't find an equivalent in Android that is publicly accessible.
> 
> I believe this may be related to: #93905
> 
> Thank you!

You can refer to the implementation of [FlutterBoostFragment](https://github.com/alibaba/flutter_boost/blob/master/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java).

**Comment by darshankawar** [comment]
@ryanneuroflow 
Along with above linked issues and explaination, I think you are hitting [this](https://github.com/flutter/flutter/issues/67011) issue. Check the same and see if it helps to answer your question.

**Comment by ryanneuroflow** [comment]
> "intentional decision to discourage the association of multiple flutter view components with a single cached engine on Android"

@willlockwood 
Thank you very much for the response! Curious on your take: Our eventual goal is to migrate the entire app to Flutter, and my current understanding of one of the downsides of using multiple engines, is they don't talk to each other. For example, if I were to use one Engine per Activity/Fragment, and I make a network request in Flutter to my server, but I want that response model object to be accessible between all the different Engines, the only current way to do that would be to use native ios/android code as an intermediary and share the model object using method channels by going FlutterEngine1->Native->FlutterEngine2. Does that sound correct?

**Comment by ryanneuroflow** [comment]
> You can refer to the implementation of [FlutterBoostFragment](https://github.com/alibaba/flutter_boost/blob/master/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java).

Thank you very much! I see that FlutterBoostFragment uses the following line, which now appears to not be possible:
 ` getFlutterEngine().getActivityControlSurface().attachToActivity(getActivity(), getLifecycle());`

`Type mismatch.
Required: ExclusiveAppComponent<Activity!>
Found: FragmentActivity?`

**Comment by 0xZOne** [comment]
@ryanneuroflow 

Before the official accepts this [PR](https://github.com/flutter/engine/pull/30126) or proposes a new solution, the following temporary solutions can be considered: 

```git
diff --git a/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java b/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
index ab28533..1608eb5 100644
--- a/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
+++ b/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
@@ -152,7 +152,7 @@ public class FlutterBoostActivity extends FlutterActivity implements FlutterView
     private void performAttach() {
         if (!isAttached) {
             // Attach plugins to the activity.
-            getFlutterEngine().getActivityControlSurface().attachToActivity(getActivity(), getLifecycle());
+            getFlutterEngine().getActivityControlSurface().attachToActivity(delegate, getLifecycle());
 
             if (platformPlugin == null) {
                 platformPlugin = new PlatformPlugin(getActivity(), getFlutterEngine().getPlatformChannel());
diff --git a/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java b/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
index b4ead66..5f954e6 100644
--- a/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
+++ b/android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
@@ -43,6 +43,17 @@ public class FlutterBoostFragment extends FlutterFragment implements FlutterView
     private boolean isAttached = false;
     private boolean isFinishing = false;
 
+    class FakeExclusiveAppComponent implements io.flutter.embedding.android.ExclusiveAppComponent<Activity> {
+        public void detachFromFlutterEngine() {
+            // do nothing.
+        }
+
+        public Activity getAppComponent() {
+            return getActivity();
+        }
+    }
+    private FakeExclusiveAppComponent fakeAppComponent = new FakeExclusiveAppComponent();
+
     // @Override
     public void detachFromFlutterEngine() {
         /**
@@ -303,7 +314,7 @@ public class FlutterBoostFragment extends FlutterFragment implements FlutterView
     private void performAttach() {
         if (!isAttached) {
             // Attach plugins to the activity.
-            getFlutterEngine().getActivityControlSurface().attachToActivity(getActivity(), getLifecycle());
+            getFlutterEngine().getActivityControlSurface().attachToActivity(fakeAppComponent, getLifecycle());
 
             if (platformPlugin == null) {
                 platformPlugin = new PlatformPlugin(getActivity(), getFlutterEngine().getPlatformChannel());
```

**Comment by darshankawar** [comment]
@ryanneuroflow 
Please follow-up in https://github.com/flutter/flutter/issues/93905, https://github.com/flutter/flutter/issues/49950 and https://github.com/flutter/flutter/issues/67011 for further updates on your use case.
Closing from here in favor of above linked issues.
If anyone disagrees, write in comments and I'll reopen it.

**Comment by willlockwood** [comment]
> Thank you very much for the response! Curious on your take: Our eventual goal is to migrate the entire app to Flutter, and my current understanding of one of the downsides of using multiple engines, is they don't talk to each other. For example, if I were to use one Engine per Activity/Fragment, and I make a network request in Flutter to my server, but I want that response model object to be accessible between all the different Engines, the only current way to do that would be to use native ios/android code as an intermediary and share the model object using method channels by going FlutterEngine1->Native->FlutterEngine2. Does that sound correct?

@ryanneuroflow Yes that sounds correct to me. That's pretty much the same position we were in. In my opinion, multiple engines isn't a good solution there because once you migrate that middle part of your flow to Flutter, you're going to have to rewrite/refactor a lot of stuff to merge those two separate engine experiences into one Flutter app. It was really a non-starter option for us, and I'd suggest that you find a way to work around the single-engine limitation as well, especially given that it looks like they're in progress on a fix.
