### ISSUE TITLE
[flutter_tools] StateError at RemoteDebuggerExecutionContext.id at package:dwds/src/debugging/execution_context.dart

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#95916]
Crash on stable/2.8.0 with command `flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart`

```
Thread 0 main threadStateError: Bad state: No context with the running Dart application.
at RemoteDebuggerExecutionContext.id(execution_context.dart:55)
at <asynchronous gap>(async)
at AppInspector._getExtensionRpcs(inspector.dart:538)
at <asynchronous gap>(async)
at AppInspector._initialize(inspector.dart:97)
at <asynchronous gap>(async)
at AppInspector.initialize(inspector.dart:160)
at <asynchronous gap>(async)
at ChromeProxyService.createIsolate(chrome_proxy_service.dart:217)
at <asynchronous gap>(async)
```

cc @annagrin

**Comment by christopherfujino** [comment]
This is currently the top crasher on the 2.8 stable

**Comment by annagrin** [comment]
@christopherfujino could you please give more details so I could repro?

- I've never seen this command before, what runs it and what is expected to happen? 
- What is the lib\main.dart in that case?

Thanks!

**Comment by annagrin** [comment]
@christopherfujino @yjbanov @zanderso appreciate any information on this - do you know where it is coming from, and how I can repro?

**Comment by christopherfujino** [comment]
> @christopherfujino @yjbanov @zanderso appreciate any information on this - do you know where it is coming from, and how I can repro?

This is coming from editor plugins. `--machine` just means generate machine-readable output that the plugins can parse, I doubt it's related to the crash. And `--target lib/main.dart` means that the entrypoint is `lib/main.dart`, which is the default if you don't provide this flag anyway (I assume the editor plugins are just always explicit). I doubt either of those flags are the cause of the crash.

**Comment by christopherfujino** [comment]
In what package are the stacktrace files coming from?

**Comment by christopherfujino** [comment]
Oh never mind, I can see the path from the description

**Comment by annagrin** [comment]
I cannot repro this on my command line. Let's see if fixing the second issue helps: https://github.com/flutter/flutter/issues/96548

If not, we would need more information to help us repro the crash:
- what is starting the command
- browser version
-  'flutter doctor -v' output

**Comment by zanderso** [comment]
@jacob314 IDE users are likely encountering this error. How would it be surfaced to them? How can we learn repro steps from them?

**Comment by yjbanov** [comment]
A couple of options:

- Since this has a workaround (run `flutter run -d chrome` from the command-line) we could drop the priority to P3.
- If we decide that this should be a P2, then @christopherfujino could you please reduce the repro such that it can be fixed in `package:dwds`?

Assigning to @christopherfujino to pick from one of the options, or offer guidance/other ideas.

**Comment by christopherfujino** [comment]
I lowered the priority to p3. Also, in https://github.com/flutter/flutter/issues/83056#issuecomment-845493193, Jonah points out:

> IIRC something similar was happening before when there was a page refresh, and the fix was perhaps to poll for the application to re-initialize?

> It would be great if these bad state errors didn't crash the tool and instead were resilient to what might be transient issues. i.e. polling/retry/et cetera

> At the very least, crashing with more info would be good

I couldn't reproduce this by refreshing, but that sounds like a logical way this could happen. Would it be feasible to poll/retry with the assumption that the app may re-initialize? @annagrin

**Comment by annagrin** [comment]
@annagirn I could not repro this at all, my flutter run just gets stuck in a flutter daemon call during uri encoding. Maybe fixing that bug will help move things along? As I mentioned before, here is the bug: https://github.com/flutter/flutter/issues/96548.

**Comment by christopherfujino** [comment]
@MubaHdev as you just filed another issue of this, can you share any further context about what you were doing at the time you hit this error that might help us with reproducing it?

**Comment by christopherfujino** [comment]
Potentially this could be a crash that the IDE plugins are re-trying over. It would be good if we localized where it was occurring in the tool and then either did a retry if it made sense, or potentially tool exit.

**Comment by christopherfujino** [comment]
2.10.1 stacktrace on https://github.com/flutter/flutter/issues/101856

**Comment by annagrin** [comment]
One thing I noticed that all reports come from windows. For folks experiencing this issue - could you please share more details? For example, did it happen on start or during hot restart? If it is easily reproducible, could you please run with `flutter run -d chrome --verbose` and share the output?

**Comment by elliette** [comment]
I'm unable to reproduce this but have some idea of what might be happening based on the stack trace. 

DWDS tries to locate the execution context of the running Dart application in [`execution_context.dart`](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/debugging/execution_context.dart#L29-L58). We try to search through all execution contexts in a given tab to try to find the correct one to attach to (this handles the case where the Dart application is embedded in an IFRAME). I'm guessing there is something wrong with how we are trying to find the execution context, which is why we are seeing this error, but it will be quite hard to debug without a working repro. 

@mrmukto - since you most recently encountered this with https://github.com/flutter/flutter/issues/104732, do you mind providing detailed steps on how to repro?

* For example, what app are you using (if you are able to reproduce this with a brand new app using `flutter create newapp` that would be good to know!) 
* How are you running your app? Are you using the command line or running from an IDE?

**Comment by elliette** [comment]
I think there should be a way to handle this gracefully on DWDS's side so that we don't crash flutter tools when we hit this. I will investigate / open a PR.

When we get repro steps from a customer it would be good to fix the underlying issue (the execution context not being found).

**Comment by christopherfujino** [comment]
Re-opening this pending https://github.com/dart-lang/webdev/pull/1642 rolling to flutter_tools

**Comment by christopherfujino** [comment]
This was rolled in https://github.com/flutter/flutter/pull/106887 dwds from 14.0.3 -> 15.0.0
