### ISSUE TITLE
Flutter pauses for minor GC every 90s

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9594]
@abarth says we could do a lot better here by providing the VM some hints as to when to GC (i.e. not when you're scrolling).

This is theoretically an easy fix we should consider trying in May?

**Comment by chinmaygarde** [comment]
Is the mechanism to provide these hints already in place? I could not find anything in `dart_api.h` or `dart_tools_api.h`.

**Comment by abarth** [comment]
> Is the mechanism to provide these hints already in place?

Nope.

**Comment by abarth** [comment]
I was imagining two signals we could give the VM:

1. "This thread is probably going to be idle for X microseconds."  We'd be able to call this after an animation frame with the number of microseconds delay we predict for the next animation frame.  The VM could use this information to decide whether it makes sense to trigger a GC or other deferred work in these gaps between frames.

2. "This thread is going to be idle for a long period of time."  We'd be able to call this function when there are no animation callbacks scheduled and when there are no pointers that are currently down.  The VM could do work on the order of ~100ms at these times without too much impact to the user experience.

**Comment by abarth** [comment]
See also https://blog.chromium.org/2015/12/smarter-garbage-collection-for-smoother.html

**Comment by sethladd** [comment]
Just want to say that this sounds very cool, and the kind of thing we can do because we work closely with each other. Love it!

**Comment by mraleph** [comment]
fyi @rmacnak-google @chinmaygarde 

I have spent some time reading through V8 source and the [paper they published](https://research.google.com/pubs/archive/45361.pdf) and found that they have moved away from using `IdleNotificationDeadline` style API.

According to Chromium CodeSearch the only remaining use of that in Blink is in `src/third_party/WebKit/Source/bindings/core/v8/V8GCForContextDispose.cpp`:

```cpp
void V8GCForContextDispose::PseudoIdleTimerFired(TimerBase*) {
  V8PerIsolateData::MainThreadIsolate()->IdleNotificationDeadline(
      MonotonicallyIncreasingTime());
  Reset();
}
``` 

Instead of using this API from the embedder side, they inverted the relationship between embedder and VM - instead of pushing signal from the embedder down to the VM they push **idle tasks** up to the embedder. Embedder's scheduler (having the whole overview of the system) then decides when it is the best time to execute the idle task. See [heap/scavenge-job.h](https://chromium.googlesource.com/v8/v8/+/refs/heads/master/src/heap/scavenge-job.h) in V8 sources.

**Comment by abarth** [comment]
Interesting.  We could use that approach too.

**Comment by sethladd** [comment]
Thanks for the comments, @mraleph !

**Comment by eseidelGoogle** [comment]
Looking through unassigned bugs. :) I believe @rmacnak-google is still working on this.

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/commit/86f602d0201afbfddd545d003edea0634c371352
https://github.com/dart-lang/sdk/commit/637a9f873bcaece96e35b94b89ede31470b617b1
https://github.com/dart-lang/sdk/issues/31094
