### ISSUE TITLE
Snap package version is lagging behind (regression?)

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter#95989]
In #93497 it was discovered that Snap builds weren't triggered, supposedly related to some bucket changes (#75363). This was fixed and a package was deployed to snap on November 15th. Since then - looking at the stable channel - SDK 2.8.0 came out on 12/8/2021 and then 2.8.1 came out on 12/16/2021, but https://snapcraft.io/flutter shows a November 15th date. I wonder if there's some regression in the CI/CD pipeline.
(On another note brew seems to have 2.8.1 (https://formulae.brew.sh/cask/flutter) although my developer friend said he was not able to update it yet.)

**Comment by danagbemava-nc** [comment]
Hi @MrCsabaToth, I think this may need to be reported over at the dedicated [flutter-snap](https://github.com/canonical/flutter-snap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repo. 

In #93497 the fix was done by one of the maintainers of flutter-snap. If it is not working, their attention may need to be drawn to this so it can be properly investigated.

With regards to brew, the current one isn't official, so whoever is in charge of that may have to be contacted to investigate the issue. 

I'm going to close this issue for now. If it is determined to be an issue on the flutter side, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by MrCsabaToth** [comment]
Thanks, I remember you mentioning that in the other package, I wanted to be sure the CI/CD is good.
