### ISSUE TITLE
Image picker not working when using video_trimmer package in app

### ISSUE THREAD

**Issue by raju8000** [flutter/flutter#95994]
## Steps to Reproduce

1. add [image picker](https://pub.dev/packages/image_picker) package with [video_trimmer](https://pub.dev/packages/video_trimmer) package in pubspec.yaml
2. Run the app in iOS simulator 
3. Now add all permission for file storage in Info.plist file
4. Now try to pick image from gallery 

**Expected results:** We should get image as XFile output from gallery

**Actual results:**  No response from image_picker , Code stops execution an no exception was generated and no log in console

<details>
<summary>Code sample:  </summary>

 [git_code](https://github.com/raju8000/image_picker_demo.git)

</details>

<details>
  <summary>Logs</summary>

No log after performing above actions.

</details>

**Comment by darshankawar** [comment]
@raju8000 
Since `video_trimmer` is a 3rd party plugin, please check it's compatibility with `image_picker` and you may need to open this issue in dedicated repo. https://pub.dev/packages/video_trimmer

Please try the steps to replicate without using the third party plugin and see if you get expected behavior or not.
