### ISSUE TITLE
The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.       todo = jsonDecode(storage.getString('todo'));

### ISSUE THREAD

**Issue by DanielRck** [flutter/flutter#96035]
### Hey, i made a todo application.

But I get this error in the Console when I try to run the app. 
Please help me.

### The Error:

```
31:33: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
      todo = jsonDecode(storage.getString('todo'));
                                ^
Failed to compile application
```

### The code:

```dart
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:green_todos_app/navbar.dart';
import 'package:green_todos_app/todo.dart';
import 'package:shared_preferences/shared_preferences.dart';

class _HomePageState extends State<HomePage> {

  Map<String, dynamic> todo = {};
  TextEditingController _controller = new TextEditingController();


  @override
  void initState() {
    _loadData();
  }

  _loadData() async {
    SharedPreferences storage = await SharedPreferences.getInstance();

    if (storage.getString('todo') != null) {
      todo = jsonDecode(storage.getString('todo'));
    }
  }
```

**Comment by willlockwood** [comment]
`jsonDecode` takes in a `String`(non-nullable), but the return type for `storage.getString('todo`) is `String?` (nullable), so the compiler senses a type mismatch. To get around that, you'll just have to make sure you're providing a `String` to `jsonDecode`. There are a lot of ways you can do that, but the two simplest examples would be:
1. Provide a default string value, like `jsonDecode(storage.getString('todo') ?? '{}')` (defaulting to an empty map when the method returns `null`)
2. You can also forcefully cast the result of `storage.getString('todo')` to a non-nullable string by adding a `!` to the end of the method: `jsonDecode(storage.getString('todo')!)`

Just depends on how you want to handle the case where the value is null, because if that's the return type of the method, you'll probably have to deal with that case in some way

**Comment by danagbemava-nc** [comment]
Hi @DanielRck, as pointed out above, you need to handle the null check in some way, since `storage.getString('todo')` can return a null value. 
Any of the above suggestions should help resolve your issue. 

For future reference do bear in mind that the issue tracker is for issues with flutter and its associated plugins/tools. 

If you need help with your personal code, consider visiting any of the community channels in https://flutter.dev/community#community-grid. 

Closing as this is not actually an issue with flutter. 

Thank you

**Comment by DanielRck** [comment]
All right, I'm sorry.
But thank you very much, I'll do that tonight.

**Comment by DanielRck** [comment]
The ! was missing at the end after the bracket because I want to output it with zero.

That was the problem. Many thanks for the quick help!
