### ISSUE TITLE
Is it possible to have integration tests and app run on 2 different repositories

### ISSUE THREAD

**Issue by akramcshive** [flutter/flutter#96054]
Hello,

I have 2 repositories, one with all my app code written and another one with my end to end integration tests to automate my mobile application. I want to maintain 2 repositories because i plan to outsource my testing to another company in the future. 

Is this something can be achieved in flutter using integration tests library. 

PS: I'm using integration tests library to automate my mobile application.

**Comment by danagbemava-nc** [comment]
Hi, @akramcshive

This issue seems like a discussion for either `StackOverflow` or one of the other flutter communities in https://flutter.dev/community#community-grid. 

If you have tried something already and are running into issues, kindly update the issue to reflect the issues you are experiencing. 

Closing from here as this is neither an issue with flutter nor a feature request. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
