### ISSUE TITLE
Website infra: Document our use of lavish bootstrap and how to re-generate it

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9610]
Specifically:

* what is the file
* where did it come from
* what color scheme did we use
* what version of bootstrap is it based on ?
* how do we regenerate it?

**Comment by sethladd** [comment]
Better yet, eliminate the need for lavish-bootstrap

**Comment by LarkAscending** [comment]
It seems to be a [customized, unmaintained version of bootstrap CSS](http://www.lavishbootstrap.com/). It says "compatible with 3.3.4" but that doesn't mean that's the version it's based on. The original goal was to help you generate a theme based on the colors in a (hero) image.

We added it to flutter/website in [this commit](https://github.com/flutter/website/commit/48cff44fd56f7bba36122ef47b94b6e28d34725b). 

* Known dependencies (partial list):
   * size of the banner at the top of every page (the app bar)
   * margin for the left nav panel
   * font size
   * some icons (github?)
   * the dropdown button for setup.md

If we can refactor so we don't need it, we can link to the CDN for vanilla bootstrap in _includes/head.html.

Having one up-to-date version of bootstrap classes would help the Sample Catalog effort. [These classes in particular](https://getbootstrap.com/components/#media) aren't behaving as documented, since they're out of date.

**Comment by sethladd** [comment]
> Having one up-to-date version of bootstrap classes would help the Sample Catalog effort

Sounds great. I fully support going to vanilla bootstrap. Thanks for looking into this!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1836](https://github.com/flutter/website/issues/1836) via [**ZenHub**](https://www.zenhub.com/)
