### ISSUE TITLE
Use kRGB_565_SkColorType to decode jpg to save memory

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#96106]
Hi 
When using a jpg, I discovered the flutter engine uses `kRGBA_8888_SkColorType` to decode the image. I noticed that it consumes about twice the memory as using `kRGB_565_SkColorType`.

Why not use `kRGB_565_SkColorType`  to decode images when the image has no alpha?
this is my patch 

SkImageInfo.h
![image](https://user-images.githubusercontent.com/9412601/148039835-8f54bcdf-3897-41e5-83fa-01e703925522.png)

**Comment by danagbemava-nc** [comment]
Hi @cj3479, can you provide any metrics that show that your suggested approach consumes less memory than the current approach being used? Also, what version of flutter are you using?

Thank you

**Comment by cj3479** [comment]
This is   current  approach
![image](https://user-images.githubusercontent.com/9412601/148078330-8857169e-4c04-44b3-b630-fe59b77a963b.png)


This is   my suggested approach
![image](https://user-images.githubusercontent.com/9412601/148078507-a4aa4b7a-56bc-415b-884b-0da7533a0eb3.png)

Flutter engine version  is Flutter 2.8.0 • channel stable

My suggested approach modify Flutter engine source 
This is my diff file
[patch.diff.zip](https://github.com/flutter/flutter/files/7808446/patch.diff.zip)

This is my  build flutter product 
[Flutter.framework.zip](https://github.com/flutter/flutter/files/7808456/Flutter.framework.zip)

**Comment by cj3479** [comment]
> Hi @cj3479, can you provide any metrics that show that your suggested approach consumes less memory than the current approach being used? Also, what version of flutter are you using?
> 
> Thank you

Hi @danagbemava-nc 

This is   current  approach
![image](https://user-images.githubusercontent.com/9412601/148078330-8857169e-4c04-44b3-b630-fe59b77a963b.png)

</br></br>
This is   my suggested approach
![1331641308330_ pic](https://user-images.githubusercontent.com/9412601/148079607-124f57e7-7894-4a2a-91c3-2600d20f821c.jpg)



Flutter engine version  is Flutter 2.8.0 • channel stable

My suggested approach  is modify Flutter engine source 
This is my diff file
[patch.diff.zip](https://github.com/flutter/flutter/files/7808446/patch.diff.zip)

This is my  build flutter product 
[Flutter.framework.zip](https://github.com/flutter/flutter/files/7808456/Flutter.framework.zip)

**Comment by danagbemava-nc** [comment]
Please provide the output of `flutter doctor -v`.

Thank you

**Comment by cj3479** [comment]
> 

![image](https://user-images.githubusercontent.com/9412601/148176806-59d56a50-ed6e-4856-88fd-9d92998e4ab6.png)

**Comment by cj3479** [comment]
hi @danagbemava-nc 
![image](https://user-images.githubusercontent.com/9412601/148176871-c1908de0-af36-452b-90b4-3cd25a4b9326.png)

**Comment by danagbemava-nc** [comment]
Hi @cj3479, I do have one more question, on which platform(s) did you notice the memory saving?

**Comment by cj3479** [comment]
Hi @danagbemava-nc  I try it  on iOS platform,  not try it Android yet

**Comment by danagbemava-nc** [comment]
Labeling for further insight from the team, as I'm not particularly familiar with this.

**Comment by cj3479** [comment]
@chinmaygarde please help  to handle the issue

**Comment by chinmaygarde** [comment]
I'm on the fence on this one. You're absolutely right that using a 16 instead of 32 bpp pixel format will yield memory savings (50% per texture). But, there is now some loss of fidelity. Earlier, you were using 8 bits per RGB component with 8 bits of wastage on the alpha channel for a 32 bit word. Now, you are using 5 for Red, 6 for Green, and 5 for Blue. So this will introduce artifacts and banding in those JPEG decompressed images.

Moreover, I'd want to verify a native 565 pixel format is always available on all client rendering APIs. Since you are on iOS with the Metal backend, the `MTLPixelFormatB5G6R5Unorm` is likely being used. I'll have to check if there is an equivalent in OpenGL and Vulkan and on all devices. There probably are but I'd need to verify. If there aren't though, you see artifacts only on devices that support those pixel formats.

The engine avoids making implicit compromises to fidelity for performance reasons. That just births further issues down the line. For instance, if we were to "fix" this issue, a new issue titled "Banding is observed in Flutter when decompressing JPEG images." is sure to be filed. This insistence on maintaining fidelity is also why Flutter cannot implement other optimizations like creating offscreen render targets with more memory conscious pixel formats, or, use the hardware scaler for memory and fill rate wins.

But, Flutter should not be averse to allowing to user to specify the decompressed pixel format (if supported by the GPU)  of an image handled by the decoder. That way, the user is in control of this the fidelity vs performance tradeoff. Happy to review a proposal for such a feature. But, I think doing this implicitly is a wont-fix.

**Comment by flar** [comment]
What app were you running for those memory usage graphs?

**Comment by cj3479** [comment]
@chinmaygarde  Thank for  your answer, and by the way, I want to Ask a question
Can you give me Sample to verify the fidelity  compromises and Banding When using 565 pixel format

I  want to check it whether existing an solution to match the reduce of memory and the fidelity is ok

**Comment by chinmaygarde** [comment]
No. I don't have one off-hand right now. You will have to construct one. IIRC, images with gradients with multiple stops show these fairly easily. If you can build your own engine, you can also change the default framebuffer to use a 16 bit pixel format. Then, everything will be rendered at reduced fidelity. This should give you some idea of what that it might look like.

As I said, I am not averse to giving users the ability to to control this themselves. But hacking off precision for all images would definitely be an issue.
