### ISSUE TITLE
I am getting error when I am not supposed to any hel with this error

### ISSUE THREAD

**Issue by austinevitalis** [flutter/flutter#96146]
```
Future<void> _takePicture() async {
    final imageFile = await ImagePicker.pickImage(
      source: ImageSource.camera,
      maxWidth: 600,
    );
    if (imageFile == null) {
      return;
    }
    setState(() {
      _storedImage = imageFile;
    });
    final appDir = await syspaths.getApplicationDocumentsDirectory();
    final fileName = path.basename(imageFile.path);
    final savedImage = await imageFile.copy('${appDir.path}/$fileName');
    widget.onSelectImage(savedImage);
  }

```
This is my code and I am getting error but dont know why the .copy method is throwing error. I will add the screenshot from my IDE and also a screenshot of my pubspec.yaml file. If the path is set to 1.8.0 package is not installed but if I downfrade to 1.6.2 it works fine. Please I need help on resolving this thank you.
<img width="675" alt="Flutter error" src="https://user-images.githubusercontent.com/29200276/148144197-3e3bc8f9-d1dc-4f31-93ba-dad4f9d90574.PNG">
<img width="686" alt="Flutter error2" src="https://user-images.githubusercontent.com/29200276/148144203-e896f7c3-87be-4d3c-a926-7c64928e9ee0.PNG">

**Comment by darshankawar** [comment]
@austinevitalis 
In order to properly address this issue, can you provide `flutter doctor -v`, `image_picker` plugin version you are using alongwith [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in text format that shows the error ? Also post the error in text format instead of in screenshots.
Thanks.

**Comment by darshankawar** [comment]
@austinevitalis 
From your output log, it says below:

`Because every version of flutter_test from sdk depends on path 1.8.0 and flutter_complete_guide depends on path ^1.8.1, flutter_test from sdk is forbidden.
So, because flutter_complete_guide depends on flutter_test from sdk, version solving failed.
pub get failed (1; So, because flutter_complete_guide depends on flutter_test from sdk, version solving failed.)
exit code 1`

As it shows, `flutter_test` depends on path 1.8.0, and your project is using 1.8.1 and hence the conflict and can't run `flutter pub get` successfully. 
Either update per the log shows and also update the sdk version `sdk: ">=2.1.0 <3.0.0"` to latest and try again.

**Comment by austinevitalis** [comment]
Okay but that didnt solve the error I was able to update the sdk and ran pub get on the terminal. But the problem of .copy method not working is the problem I will upload a new copy of my code.

https://drive.google.com/file/d/1r2ck6Kd10Qj6lKm_8RVh5Upwv7AAVROQ/view?usp=sharing

**Comment by austinevitalis** [comment]
How do I correct this the .copy method is throwing error  what do I do to correct it


Future<void> _takePicture() async {
    final picker = ImagePicker();
    final imageFile = await picker.getImage(
      source: ImageSource.camera,
      maxWidth: 600,
    );
    if (imageFile == null) {
      return;
    }
    setState(() {
      _storedImage = File(imageFile.path);
    });
    final appDir = await syspaths.getApplicationDocumentsDirectory();
    final fileName = path.basename(imageFile.path);
    final savedImage = await imageFile.copy('${appDir.path}/$fileName');
    widget.onSelectImage(savedImage);
  }
