### ISSUE TITLE
[integration_test] Add real example

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter#96180]
The existing example  for the `integration_test` package is too simple and does not help to understand how to do with real apps when there are external dependencies such as http service, .... And the use-case versus a widget test.

I guest we could inject mock objects in the `main` method but I don't see the interest of writing a integration test which need to be executed on real device instead of writing a simple and faster widget test of the root widget

**Comment by darshankawar** [comment]
@woprandi 
Please check if the samples/testing_app [examples](https://github.com/flutter/samples/tree/master/testing_app/integration_test) related to integration_test helps to answer your case.

Also, your issue is similar to https://github.com/flutter/flutter/issues/90885 and https://github.com/flutter/flutter/issues/87437, so please follow-up in the linked issues and the earlier one above I shared and see if it helps.
