### ISSUE TITLE
2-step text layout

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#96235]
Laying out text is expensive. Even when warmed up it can take ~0.5ms to lay out a single RenderParagraph on a low-end Android device. This means a simple text-based layout can quickly blow through its frame build budget. Even on a faster phone, laying out a single RenderParagraph can take over 0.2ms.

Currently, laying out the text is blocking the UI thread. However, there may be an opportunity for parallelism here if we could kick off the text layout asynchronously when we configure the RenderParagraph object. At this point, the RenderParagraph knows all relevant layout information except for its width. This means it should be able to pre-compute all relevant layout information except for line breaks (since for those it needs to know its width). Then, during layout when the width is known we only need to compute those line breaks. Since that should be faster and most of the text layout work is done in parallel the overall UI time for the frame should go down.

Open Questions:
- How much time passes between configuring a RenderParagraph and laying it out? Is that enough time for the complete precomputing the text layout information?
- How do we asynchronously kick of a task during build and synchronously await it during layout?

/cc @jason-simmons @dnfield @Rusino

**Comment by goderbauer** [comment]
Before the holidays I did some experimentation to answer the first question. I tested two scenarios: In the first one, the build and layout step were completely separated creating a large gap between configuring the RenderParagraphs and laying them out. This was done by rendering a column of list tiles, where all list tiles would be build first (during which the RenderParagraphs got configured) before they all would all be laid out in one go. In the second scenario, build and layout were intertwined. This was done by rendering a ListView of list tile, where each list tile would be laid out right after it was build. This only creates a small gap between configuring the RenderParagraph and laying it out. In both cases each list tile contained three RenderParagraphs.

Next I looked at the data collected from these two experiments to figure out if there's any potential for speed-up by breaking text layout into two steps.

In the first scenario there was an average effective* delay of 8ms between configuring the RenderParagraph and laying it out on a low-end Android device. That's enough time to complete the pre-computations in parallel. According to the experiment this would shave about 1.5ms off the UI time spend building/laying out each ListTile (assuming no overhead for the parallelization).

In the second scenario the effective* delay between configuring and laying out the first RenderParagraph of a ListTile wasn't quite enough to finish the pre-computations. On average, the first RenderParagraph of the ListTile would have to wait 0.2ms in its layout before the pre-computations were available. This delay, however, was enough to ensure that the other two RenderParagraphs had enough time to finish their parallel pre-computations. On average, this would still shave about 1ms off the UI time spend building/laying out each ListTile (again assuming the paralyzation doesn't add any overhead).

*) effective delay = time between configuring a RenderParagraph and laying it out minus the time spend for laying out any previous RenderParagraphs (because that time wouldn't be there if those would have pre-computed their layout information in parallel).

**Comment by goderbauer** [comment]
The problem is defining an API where we could kick of the pre-computations asynchronously during build when we configure the RenderParagraph, but then synchronously await the result during layout. 

Some random thoughts on that:

Right now, layout is synchronously on the framework side. So we can't use async/await here. When the RenderParagraph's layout method calls into the engine to do the last step of the text layout (line breaking), the engine would have to block that call until the pre-computation is done.

If we use the same general thread pool for the text pre-computations that we use for other tasks it would be possible, that text layout is now stuck behind other multi-frame operations like decoding an image, which means layout performance would be even worse than without the parallelization. We could potentially have a dedicated thread pool for text computations to avoid this.

We want to synchronously await the results because text layout overall should still appear to be synchronous. It needs to finish in the frame the text is supposed to show on screen. Otherwise, it would awkwardly pop in a few frames later shifting other content around. While completely asynchronous text layout like that may have its use cases (https://github.com/flutter/flutter/issues/41707) it seems undesirable in the general case.

**Comment by goderbauer** [comment]
With `PrecomputedText` Android has a similar concept of a two step text layout system. According to their medium article at https://medium.com/androiddevelopers/prefetch-text-layout-in-recyclerview-4acf9103f438 about 90% of the layout work can be done ahead of time without knowing the width/height of the text box yet.

They appear to use this concept mainly in recycler views where they precompute layout information for ListTiles that are about to come into view between frames.

**Comment by Hixie** [comment]
Re the API, we don't actually need to await the results, because we don't actually need the results, we just need the cache to be warm when we do the sync layout later. The engine itself can notice that it's already computing the data for a particular layout and block until that's finished and use the data directly, and it will still be faster than today.

**Comment by dnfield** [comment]
Part of the problem is that we'd risk being slower if we try to warm the cache during build and it doesn't finish warming by paint time, in the current model. 

E.g. today we do all layout during paint. Tomorrow, we could try to kick off some of it during build and finish during paint, but we might actually make paint _slower_ if it regularly can't warm the cache between build and paint.

**Comment by goderbauer** [comment]
> Re the API, we don't actually need to await the results, because we don't actually need the results, we just need the cache to be warm when we do the sync layout later.

True, we could just fire & forget the initial asynchronous layout call during build.

> The engine itself can notice that it's already computing the data for a particular layout and block until that's finished and use the data directly, and it will still be faster than today.

This would have the same problem outlined above that the asynchronous text layout task may be stuck behind some other multi-frame operation (like decoding an image) and the engine shouldn't really block waiting on that. Unless we solve this in other ways (e.g. with a dedicated text layout thread pool?).

**Comment by goderbauer** [comment]
> E.g. today we do all layout during paint. Tomorrow, we could try to kick off some of it during build and finish during paint, but we might actually make paint slower if it regularly can't warm the cache between build and paint.

Why would layout (I believe you mean that instead of paint?) be slower than it is today? If the async work doesn't finish in time, layout would have to do the same work it does today?

(We of course wasted some CPU cycles on the thread that runs the asynchronous text layout in this case since we never used its result... Do you mean things would be slower because without the async step that thread could have done some other useful work?)

**Comment by dnfield** [comment]
Yes, I did mean layout.

And yes, we're busying a thread (and really, a CPU core) that could be doing other useful work with work that won't be used. If that thread is running at the same priority as UI, it may interrupt the UI thread. If it's not, it's even more likely to not finish in time. It'd still be worth measuring this in real world scenarios though and see whether it actually causes problems.

**Comment by JsouLiang** [comment]
Do we have this scheme design wiki?

**Comment by Hixie** [comment]
@dnfield Why would the work not be used?

I'm imagining a world where we take this:

```
    TOP OF FRAME                                               END OF FRAME
UI: |  ...[build]...                 ...[measure][layout][paint]...       |
```

...and turn it into this:

```
    TOP OF FRAME                                       END OF FRAME
UI: |  ...[build]...                 ...[layout][paint]...        |
BG:          [measure]                                                  
```


Worst case it takes this:

```
    TOP OF FRAME                        END OF FRAME
UI: |  ...[build][measure][layout][paint]...       |
```

...and turns it into this:

```
 TOP OF FRAME                        END OF FRAME
 UI: |  ...[build]         [layout][paint]...       |
 BG:              [measure]
```

Having a separate thread for this specifically makes sense to me, it would make the synchronization with the layout thread really simple (any time you try to do text rendering but find there's still measuring happening, just join the measuring thread and wait for it to be done, no need to do any coordination beyond that).

**Comment by JsouLiang** [comment]
RenderParagraph.dart
```
void _layoutText({ double minWidth = 0.0, double maxWidth = double.infinity }){
    _textPainter.layout(
          minWidth: minWidth,
          maxWidth: widthMatters ? maxWidth : double.infinity,
          asyncLayout: true,
          layoutFinished: (bool isAsync) {
             if (isAsync) {
               markNeedsLayout();
             }
          });
     )
}
```
```
lib/ui/text/paragraph.cc
```cpp
void Paragraph::layout(double maxWidth,
                       double minWidth,
                       bool async,
                       Dart_Handle callback_handle) {
  tonic::DartPersistentValue* callback = new tonic::DartPersistentValue(
      tonic::DartState::Current(), callback_handle);
  const auto& task_runners = UIDartState::Current()->GetTaskRunners();
  m_paragraph->SetAsyncMode(async);

  auto closure = [weak_paragraph = std::weak_ptr<txt::Paragraph>(m_paragraph),
                  ui_task_runner = task_runners.GetUITaskRunner(), maxWidth,
                  minWidth, callback]() {
    if (auto paragraph = weak_paragraph.lock()) {
      paragraph->Layout(maxWidth);
    }

    fml::TaskRunner::RunNowOrPostTask(ui_task_runner, [callback]() {
      tonic::DartInvoke(callback->value(), {});
      delete callback;
    });
  };

  if (async) {
      textMeasureThreadTasks->PostTask(closure);
  } else {
   // run current thread
    closure();
  }
}
```
@Hixie hey, do you mean this? In engine paragraph we use another thread to layout text, and when layout finish we invoke the callBack to make `RenderParagraph` to need layout?

**Comment by jason-simmons** [comment]
The engine generally maintains the invariant that the Dart UI thread does not block waiting on other threads.  If the real text layout is going to execute after the cache is prewarmed, then it would be more consistent to make this explicit and have the prewarm API return a Dart future.  The framework can then do the layout after the prewarm future completes.

There is a concern about potentially unused work because Libtxt and SkParagraph do not currently have a dedicated API that performs the proposed "measure" operation.  Without that, the engine would be doing a full layout on the background thread and hoping that it has the side effect of populating some caches that would be useful for the real layout.  This might be wasteful.

Another engine API proposal that would be simpler to reason about is an async version of `ParagraphBuilder.build`.  `ParagraphBuilder.build` could return a `Future<Paragraph>` that is completed after the text is measured on a background thread.  This has the advantage of ensuring that the `Paragraph` does not need to be usable concurrently on multiple threads or copied for use on a background thread - after the future is completed the paragraph will only be used on the Dart UI thread.  However, my understanding is that the framework's design would not be able to easily make use of this API.

**Comment by dnfield** [comment]
Trying to join a thread during layout will be bad. Our measurement task might be queued behind any number of other tasks that we can't block frame workloads on, e.g. image decode tasks. If we end up with a dedicated text measurement thread that's one more thread when we already have too many.

**Comment by Hixie** [comment]
@jason-simmons As you say, making the APIs asynchronous in the sense of returning a future isn't practical because the build and layout phases happen in one synchronous task.

I agree that a strategy here that works on hope isn't going to work. What I was envisaging is doing all the work that doesn't require the actual constraints ahead of time, and then continuing the work once we have the constraints. It wouldn't be hope-based, it's just starting the current work earlier on a background thread.

@dnfield We certainly shouldn't queue this work behind work that isn't absolutely critical for this frame (and any image decode tasks are clearly not critical for this frame since they won't processed during this frame regardless of when they complete).

While I agree that we have too many threads in general, I don't know that means this thread proposal is less valuable than all the other threads we have already and thus should be dismissed. If we already had this thread, and were looking at all our threads and deciding what to do, I suspect this would be one of the last ones we would remove.

FWIW, early on in the project we did look at doing build and layout asynchronously, but the result was that the overhead of unwinding the stack and restarting layout was too high to be worth it. We could try a new version of this now that we have more tools like SynchronousFuture and so on and a more nuanced understanding of the needs of our layout engine. It certainly would be a really invasive change though, and I'm not sure it would really solve any of the issues with what we're talking about above, because to make the layout actually faster we'd still need to make sure we can actually execute these tasks promptly and get results back without overhead and not be scheduled behind lower-priority work and so on.

**Comment by dnfield** [comment]
I think for this to work we would need:

1. A dedicated thread for text layout
2. Running at the same priority as the UI thread
3. Some level of confidence that it will actually be scheduled concurrently with other work on the UI thread

That third part is the most hazy for me - I think we could clear it up with some benchmarks on a proof of concept on some representative devices though.

**Comment by JsouLiang** [comment]
@dnfield hey i have a question: How the UI thread use the text layout result that calculated in the text layout thread? Call the callback to tell TextRenderObject needsLayout when the text is calculated finished?

**Comment by dnfield** [comment]
I'm imaging an API that looks like this:

```dart
class CancellationToken {
  /// Attempt to cancel asynchronous work represented by this token.
  void cancel();
}

class Paragraph { 
  /// Prepares information needed to layout this paragraph.
  ///
  /// Calling this before [layout] may make subsequent calls to layout take less time
  /// by doing all work except line breaking in parallel to other work being done in
  /// current isolate.
  CancellationToken measure();
}
```

And then in the C++ implementation of `layout`, we'd wait for the task spawned by `measure` to complete, as long as the cancellation token had not been cancelled.

**Comment by dnfield** [comment]
I should have added - the dangerous part of all of this is `wait for the task spawned`, becuase there's no way to guarnatee that task has been scheduled the way we really want - to run in parallel with other work on the UI thread. And there is a real risk that when the UI thread yields to that task, some other task will grab the open core and we'll be delayed more than we otherwise would have been just synchronously doing the work on a single thread.

**Comment by JsouLiang** [comment]
Any new development?

**Comment by dnfield** [comment]
I posted a _very_ rough patch at https://github.com/dnfield/engine/tree/paragraph_measure. @goderbauer and I are looking to see if we can get benchmarks out of that with some changes to the framework.

An alternative approach would be some kind of incremental building, which @Hixie is helping look at.

**Comment by goderbauer** [comment]
I combined dan's engine path with the framework patch at https://github.com/goderbauer/flutter/tree/measureParagraph and ran the `complex_layout_scroll_perf__timeline_summary` on a Pixel 4. Sadly, the frame numbers are worse with the patch in all three iterations I ran. Below is a data point for comparison.

Baseline (no patch applied):
```
    "average_frame_build_time_millis": 1.3382045454545461,
    "90th_percentile_frame_build_time_millis": 2.693,
    "99th_percentile_frame_build_time_millis": 10.77,
    "worst_frame_build_time_millis": 11.81,
```

With the two patches:
```
    "average_frame_build_time_millis": 1.4815590909090914,
    "90th_percentile_frame_build_time_millis": 3.046,
    "99th_percentile_frame_build_time_millis": 13.008,
    "worst_frame_build_time_millis": 14.284,
```

The other two runs looked similar.

When thing I noticed in the trace was that executing the newly introduced `measure` method on dart:ui's Paragraph actually takes a surprising amount of time. Maybe that's because we are creating a new thread every time instead of just posting tasks to a worker thread?

**Comment by goderbauer** [comment]
Here's a trace taken on a low-end Android phone for brining a bunch of ListTiles in a ListView on screen. The actual Paragraph layout time is nice and fast. But calling `Paragraph::measure` during build seems surprisingly expensive as stated above.

[dart-timeline-2022-1-14.json.zip](https://github.com/flutter/flutter/files/7872973/dart-timeline-2022-1-14.json.zip)

**Comment by dnfield** [comment]
It'd be slightly interesting to see what happens if you comment out the trace evnets from the engine code. I'll see if I can wire this up to the concurrent worker pool in case that makes any differnce too.

**Comment by goderbauer** [comment]
> It'd be slightly interesting to see what happens if you comment out the trace evnets from the engine code.

Will do a few runs to see.

**Comment by dnfield** [comment]
@goderbauer I pushed up some new commits to my `paragraph_measure` branch. Can you try again with those?

**Comment by goderbauer** [comment]
Running the patched version without the extra trace events is also mostly slower (the 90th percentile does improve, though):

```
    "average_frame_build_time_millis": 1.4041711711711717,
    "90th_percentile_frame_build_time_millis": 1.457,
    "99th_percentile_frame_build_time_millis": 15.196,
    "worst_frame_build_time_millis": 19.664,
```

**Comment by goderbauer** [comment]
@dnfield Here are the numbers from a Pixel 4 with the latest patch you posted (I removed the trace events from it again):

```
    "average_frame_build_time_millis": 1.5507031963470324,
    "90th_percentile_frame_build_time_millis": 3.08,
    "99th_percentile_frame_build_time_millis": 11.496,
    "worst_frame_build_time_millis": 12.135,
```

```
    "average_frame_build_time_millis": 1.761193693693694,
    "90th_percentile_frame_build_time_millis": 3.275,
    "99th_percentile_frame_build_time_millis": 9.675,
    "worst_frame_build_time_millis": 15.035,
```

```
    "average_frame_build_time_millis": 1.5585090909090913,
    "90th_percentile_frame_build_time_millis": 3.045,
    "99th_percentile_frame_build_time_millis": 11.132,
    "worst_frame_build_time_millis": 12.552,
```

It still appears to be slower than the baseline.

**Comment by goderbauer** [comment]
Side-note: instantiating the ParagraphBuilder and building the InlineSpan is also surprisingly expensive, both take around 0.16ms each on average on a low-end Android. And both of these are currently still done blockingly on the UI thread (used to be done during layout, with the patched version now during build). Doing the ParagraphBuilder.build takes just 0.05ms. Doing the text measurements takes 0.13ms on average. Scheduling to take the measurements asynchronously takes 0.22ms.

One thought I had was: Can we do more of this asynchronously (especially the first two items mentioned above), but not sure how.

**Comment by goderbauer** [comment]
Traces taken on low-end android of repeadedly showing and hiding 21 pieces of text organized in a ListView:

Baseline: 
[baseline.json.zip](https://github.com/flutter/flutter/files/7873867/baseline.json.zip)

With the latest patch applied:
[with-patch.json.zip](https://github.com/flutter/flutter/files/7873859/with-patch.json.zip)

Some quick analysis on CPU Duration of Engine::BeginFrame for the frames in the trace that show the text:

|      |   baseline  | w/ patch | change |
| ----------- | ----------- | ---- | -- |
| Average | 27.141 | 24.833 | -9% |
| median | 27.768 | 26.607 | -4% |
| P90 | 28.249 | 27.397 | -3% |
| P99 | 29.922 | 29.127 | -3% |
| worst | 30.314 | 29.271 | -3% |

So overall a (small) improvement.

**Comment by goderbauer** [comment]
From talking to Skia: The benchmark numbers given above may not have been super-accurate because they were measuring warm runs. SkParagraph caches the last 5000 strings, so the strings in the benchmarks were always in the cache. I wonder how this benchmark would perform if all the strings were always unique and there wouldn't be any cache hits.

**Comment by Rusino** [comment]
You can always reset cache after each paragraph to make sure nothing is reused. But what would you be measuring then? 
The real time scenario always reuses strings. 5000 different paragraph is really hard to imagine.
I actually have benchmarks in libtxt that do cold case measurement (to compare two different tools - libtxt and skparagraph). You can take a look but it's really hard to do something like that in Flutter.

**Comment by goderbauer** [comment]
I am wondering what the times will look like the first time a new string is encountered. E.g. you push a new route in Flutter for the first time which shows a list of your contacts (or some other dynamic data). Those strings will not be in the cache at that point. Sure, if you go back and forth, you will then hit the cache, but I am wondering if this will do anything to reduce the cost of that very expensive first frame.

**Comment by Rusino** [comment]
The first time always is going to be expensive. You probably can format some text ahead of time but I am not sure you have some time to do that (it only can happen after you load all the fonts in the collection - by the way, it's also very expensive operation unrelated to paragraph; I don't know if you measure it separately in Flutter).

**Comment by dnfield** [comment]
The font collection shows up the first time we render text, which is in this benchmark's case happening to render the initial screen. It's not impacting the part we've been measuring.

However, we do want to optimize for the initial presentation of the new screen with lots of text. It's good that we can be fast showing it a second time, but it's taking too long the first time.

**Comment by goderbauer** [comment]
Re-did the experiment, but this time looking at cold numbers. Below are the CPU Duration of Engine::BeginFrame measured on a low-end Android for...

baseline: 48.129ms, 51.450ms, 50.066ms
w/ patch: 27.377ms, 35.477ms, 36.686ms

This looked pretty promising (average is down by 33.5%). **However**, we are spending a decent amount of time waiting for the asynchronous measurements to finish during layout, as can be seen when comparing wall durations (with the patch the UI thread is idling more):

baseline: 48.196ms, 51.550ms, 50.065ms
w/ patch: 38.779ms, 46.689, 41.676ms

It's still about 15% faster on average, though.

**Comment by Hixie** [comment]
Scrolling infinite lists is the canonical example of when you'll miss the cache consistently.

> The first time always is going to be expensive.

Unfortunately what we've been learning is that the first time is the most important.

**Comment by dnfield** [comment]
Scrolling an infinite list is actually not our worst case here - the worst case is happening when a new route is pushed that has lots of small unique pieces of text. Once that's all laid out, "normal" user scrolling works out ok because only a small number of new paragraphs get laid out as the user scrolls. But as soon as the user moves to a new route they're back to jank city and it's pretty painful. It's definitely less painful once they return (in the application under consideration, they're not hitting the cache limits), but it's still not great.

**Comment by dnfield** [comment]
The more I think about this, the more I think that two step layout won't really work. 

The two biggest problems are:

- There isn't enough time between build and layout to get enough work done
- There's serious risk of getting wedged if synchronous work on the UI thread has to wait on thread scheduling concerns on some thread or threads for text layout.

The only thing I can see working is if a user wants to draw pre-shaped and pre-laid out text. The main blocker to this today is that the `ParagraphBuilder` API must be used on the UI isolate, and/or that we have no API for something like `drawGlyphs`.

I'm partial to the idea of opening up an API like `drawGlyphs`, since there would be plenty of FFI based opportunities to shape and layout text appropriately, and would allow for use cases that want to do shaping off-device (i.e. for a font you _know_ is shipped with your app).

I also wonder how close we could get to accurate dimensions of text without doing a full layout - i.e. if we could have more asynchronicity without pop-in.

**Comment by goderbauer** [comment]
Should we close this issue and file more specific ones with your suggestions, if we don't have any on file for those yet?

**Comment by dnfield** [comment]
The drawGlyphs suggestion is https://github.com/flutter/flutter/issues/96617

The paragraph builder in the background is https://github.com/flutter/flutter/issues/53985
