### ISSUE TITLE
Engine roll caused failures in "Linux framework_tests_misc"

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#96260]
The Engine roll here https://github.com/flutter/flutter/pull/96244 caused failures in `Linux framework_tests_misc` with logs here:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8825733661309369041/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout

Engine roll reverted here: https://github.com/flutter/flutter/pull/96259

Speculative revert of the Dart roll in the Engine roll: https://github.com/flutter/engine/pull/30729

**Comment by zanderso** [comment]
The commits in the Dart roll are here https://dart.googlesource.com/sdk.git/+log/f59531cc2973..5f2c54513b7d

**Comment by zanderso** [comment]
The Engine roll is green on the Framework tree following the Dart SDK revert.

**Comment by jason-simmons** [comment]
The failing tests are in the `dev/devicelab` suite in the framework tree.  I tried running these tests on a LUCI bot and noticed that they failed repeatedly due to a race in the tests and the devicelab framework.

The devicelab framework has a `runProcessCleanup` flow that queries for Dart processes on the system before and after running the devicelab test.  If a process exists after the task completes but not before it started, then it is assumed to be a leak and is then killed:
https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/framework.dart#L182

However, multiple tests may be running concurrently in the test harness, and some the `dev/devicelab` tests spawn tasks that do `runProcessCleanup`.  If one test checks for leaked processes it may see Dart processes that were spawned by another test and kill them, causing the other test to fail.

I did not notice any correlation between these failures and the version of the Dart SDK.  But it's possible that a Dart roll altered the timing of test execution and made this race more likely to fail.

It might make sense to disable the process leak detector by default and enable it only in scenarios where the user knows that only one devicelab process will be running.

@CaseyHillers @jonahwilliams

**Comment by zanderso** [comment]
Also @dnfield (from https://github.com/flutter/flutter/pull/29196)

**Comment by dnfield** [comment]
runProcessCleanup was never intended to be used when concurrent tests are running on the same hardware - it's meant to be a generic check that a test does not leave running dart processes spawned. However, IIRC it never quite did everything we really needed and we still ended up configuring LUCI to just kill stray processes on test exit.

**Comment by zanderso** [comment]
Related: https://github.com/flutter/flutter/pull/96320 /cc @Hixie

**Comment by christopherfujino** [comment]
I'm trying to verify a fix locally

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/96320 fixes run_test.dart which used to terminate dart processes even during unit tests (the other unit tests already disabled this).

**Comment by christopherfujino** [comment]
yup, https://github.com/flutter/flutter/pull/96320 looks like it will resolve this

**Comment by Hixie** [comment]
#96320 has landed.

**Comment by zanderso** [comment]
Thanks! I'm going to start bringing in small manual Dart rolls.

**Comment by zanderso** [comment]
The rolls are moving again.
