### ISSUE TITLE
Plugin with id 'com.android.application' not found

### ISSUE THREAD

**Issue by tariqgamerplays** [flutter/flutter#96300]
when i run `flutter run`, it says:
```
A problem occurred evaluating project ':app'.
> Plugin with id 'com.android.application' not found.

```
when i remove 
```
apply plugin: 'com.android.application'
```
 from my build.gradle file i get 
```
A problem occurred evaluating script.
Could not find method android() for arguments [flutter_7axc8bv5alpjnq4u0vge47we8$_run_closure1@1cbc104c] on project ':app' of 
type org.gradle.api.Project
```

it worked perfectly before but now this keeps on happening.

**Comment by darshankawar** [comment]
@tariqgamerplays 

The error `com.android.application` usually occurs due to lack of a `build.gradle`. It comes from com.android.tools.build:gradle (check latest version) which is defined in `build.gradle file. so check that file and make sure `com.android.tools` is present and is on latest version.
Also, make sure your gradle version is compatible with your Android Gradle Plugin.
You can search for similarly logged / asked issues on support channels like StackOverflow. 
Closing from here as this is more of a setup / config issue.

**Comment by tariqgamerplays** [comment]
>@darshankawar
Thank you for helping me, i will try it.
