### ISSUE TITLE
bin/flutter says running as root is not recommended, yet disallows it

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9634]
If you try to run flutter as root, you get a message saying (my emphasis) "We strongly _recommend_ running the flutter tool without superuser privileges."
https://github.com/flutter/flutter/blob/master/bin/flutter#L52

However, despite saying this is not _recommended_ the script simply terminates. We should either allow this, or change the terminology to say it's not supported.

**Comment by mit-mit** [comment]
This came up in context of https://github.com/flutter/flutter/issues/9547

**Comment by mit-mit** [comment]
This came up in context of https://github.com/flutter/flutter/issues/9547

**Comment by Hixie** [comment]
It doesn't disallow it, it just doesn't make it easy. This is intentional, it raises the bar so that you at least have to be comfortable enough editing code and figuring out how to recompile the tool before you can do it. If you can't figure that out, you almost certainly aren't going to understand the implications of running as root.

There's really no reason to run as root. It's a terrible thing to do.

I like the current terminology because it's not overly paternalistic (it's even a bit tongue-in-cheek), but it's still completely accurate (we really don't recommend it).

I'm open to changing the text but I think it's important that we strike this same tone while remaining as accurate.

**Comment by mit-mit** [comment]
https://github.com/flutter/flutter/pull/10129
