### ISSUE TITLE
[image_picker][iOS13] When select HEIC photos, return rotated photo but exif orientation is not removed.

### ISSUE THREAD

**Issue by heebaek** [flutter/flutter#96353]
I am using image_picker 0.8.4+4
I test it with ios13.7(iPhone 7plus), ios15.0.2(iPad Air 4th) real devices with jpg and heic photos.

in ios13 when select heic photo, 
var pickedFile = await picker.pickImage(source: ImageSource.gallery); (with full size or resized, both occur)

pickedFile is already rotated by exif orientation information. but it has still exif orientation info.

when normal situation, pickImage return original image with original exif orientation data.

When I selecting heic image in ios13,  pickImage return jpg not heic with  warning message (image_picker: compressing is not supported for type (null). Returning the image with original quality)

I think when convert original heic image to jpg image, rotation is occurred by bug.(or exif orientation data not remove by bug)

I tried to workaround(reverse rotate), but it is not easy because we can't detect selected image type is heic or jpeg.
library logging about 'not supported type', but is is not saved in returned XFile.

please let me know any workaround or information.

thank you.

**Comment by darshankawar** [comment]
> in ios13 when select heic photo, var pickedFile = await picker.pickImage(source: ImageSource.gallery); (with full size or resized, both occur)
> 
> pickedFile is already rotated by exif orientation information. but it has still exif orientation info.

@heebaek  Are you saying that if we pick HEIC image from gallery on iOS 13, it return / shows the image in inverted form ?


> but it has still exif orientation info.

Can you give us an example for this ?


> When I selecting heic image in ios13, pickImage return jpg not heic with warning message (image_picker: compressing is not supported for type (null). Returning the image with original quality)

Are you saying that the selected HEIC image is returned or saved as jpg ?
Please read below from plugin's readMe regarding HEIC image:
```

iOS 

This plugin requires iOS 9.0 or higher.

Starting with version 0.8.1 the iOS implementation uses PHPicker to pick (multiple) images on iOS 14 or higher. As a result of implementing PHPicker it becomes impossible to pick HEIC images on the iOS simulator in iOS 14+. This is a known issue. Please test this on a real device, or test with non-HEIC images until Apple solves this issue. 63426347 - Apple known issue
```
https://pub.dev/packages/image_picker

Also, regarding the behavior you are facing, it would be good to provide expected vs actual result on iOS 13 related to HEIC images, so that'll be helpful for us to address it properly along with your `flutter doctor -v` and a [complete minimal reproducible code sample.](https://stackoverflow.com/help/minimal-reproducible-example)

Thanks.
