### ISSUE TITLE
In my application, failed to use video_player to play local videos

### ISSUE THREAD

**Issue by big-zZ** [flutter/flutter#96386]
In my company application, i have imported many other libs, now i need to play local videos, and find video
_player, after i imported  it, and get the same code from video_play_master to my app, 
![image](https://user-images.githubusercontent.com/75821787/148745272-2a2be45f-b5a4-4297-9a28-736589d36383.png)

when i run, it shows the flowing issues:
![image](https://user-images.githubusercontent.com/75821787/148744800-c61d229e-84b1-4cd1-b329-78a06eca1a95.png)

![IMG_3DB3C92F5E28-1](https://user-images.githubusercontent.com/75821787/148745412-02123df0-3c10-4f14-a5d4-c9e38e581525.jpeg)

if i create a new flutter project, and copy the same code, and run it, it is ok, can display my local videos, anyone have seen this? have any idea to fix it? thanks a lot!!!

**Comment by darshankawar** [comment]
@big-zZ 
Since you said it works properly in a new flutter project and local video file plays properly, this indicates, it could be something related to your company app' config / setting that might be leading to the error. You can ask about the same on support channels like StackOverflow, since the new Flutter project, video_player plugin and it's usage seems to be working properly.
Closing from here.
