### ISSUE TITLE
Document how to test native plugin code

### ISSUE THREAD

**Issue by blelump** [flutter/flutter#96421]
Hi,

what we're trying to achieve is to run tests against platform (Android) native code (Kotlin in this case) from within Flutter plugin. It seems the whole community either don't write the native code tests or we're unable to find "the right" plugin to take a look at. Most of the plugins around if includes the native code, doesn't include any test. Perhaps we haven't searched deep or long enough and in such case please guide us.

Our problem is more or less similar to: https://stackoverflow.com/questions/69407522/flutter-how-to-run-unit-tests-over-a-plugin-native-code-for-android

The wiki page https://github.com/flutter/flutter/wiki/Plugin-Tests encourages devs to write tests, but doesn't really help of how to write them and run them. 

Would appreciate any help in this matter.

**Comment by stuartmorgan** [comment]
I thought I had an issue filed for this already, but it looks like I only filed https://github.com/flutter/flutter/issues/95970 (which is related, but definitely not the same thing).

We should substantially expand https://docs.flutter.dev/development/packages-and-plugins/developing-packages#testing-your-plugin to cover native unit tests, as well as all kinds of native tests on platforms other than Android. Ideally this should be done in conjunction with https://github.com/flutter/flutter/issues/82458.

> The wiki page https://github.com/flutter/flutter/wiki/Plugin-Tests encourages devs to write tests

Note that this page is specifically about plugins in the flutter/plugins repository.

> but doesn't really help of how to write them 

It doesn't cover writing them because the assumption is that people will look at the existing tests in the repository when adding new ones (although we have holes there currently, which is ).

> and run them.

It has explicit instruction on running them: https://github.com/flutter/flutter/wiki/Plugin-Tests#running-tests in the context that page is intended for, which is the flutter/plugins repository. Instructions intended for the broader plugin development audience would have different instructions of course.

**Comment by stuartmorgan** [comment]
> Most of the plugins around if includes the native code, doesn't include any test. Perhaps we haven't searched deep or long enough and in such case please guide us.

In the short term, I recommend looking at plugins in flutter/plugins—webview_flutter for instance—using the descriptions of test layout on https://github.com/flutter/flutter/wiki/Plugin-Tests#running-tests to find the relevant files.

**Comment by blelump** [comment]
@stuartmorgan , thanks for replying! Among plenty of other issues somehow I haven't expected any answer...

The plugin you're pointing out, so a `webview_flutter` seems not having Android-platform related tests. This is important to point out as it is also related to the environment, where the tests are executed, how it is configured and so on.

We're struggling currently with Kotlin unit tests, already with multiple approaches behind. None so far was successful. The easiest way to recreate is simply bootstrap a new Flutter plugin from within Android Studio, along with some Kotlin native code. Then create a test for this code, may be simple hello world case and finally try to run it. Somehow it seems during the tests execution, none is found, ending with `no tasks to execute`.

If you'd like to take a look, we can upload the codebase for sharing it.

**Comment by stuartmorgan** [comment]
> The plugin you're pointing out, so a `webview_flutter` seems not having Android-platform related tests.

[Yes it does](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter_android/android/src/test/java/io/flutter/plugins/webviewflutter).

> We're struggling currently with Kotlin unit tests

I don't have any Kotlin examples to point to, since the Flutter team's plugins don't use Kotlin. That will be covered in docs though.

**Comment by stuartmorgan** [comment]
Now that the plugin template contains test scaffolding, I'll document it once it gets to stable. (The documentation will be along the lines of https://github.com/flutter/flutter/wiki/Plugin-Tests, but adapted for general use rather than repo tooling, and using example code from the template.)

**Comment by stuartmorgan** [comment]
The new docs are now live at https://docs.flutter.dev/testing/testing-plugins. (Some parts are currently only applicable to the template as created from the `master` channel, but that will change at the next major stable release.)
