### ISSUE TITLE
Reduce ceremony with small samples

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#96492]
Some of our examples have quite a lot of ceremony / boilerplate associated with them (relative to the actual example code). For example:
https://github.com/flutter/flutter/blob/master/examples/api/lib/rendering/sliver_grid/sliver_grid_delegate_with_fixed_cross_axis_count.0.dart

We don't need so much ceremony around declaring a new `StatelessWidget`, passing a `_title`, etc., do we? I get that we want to show best practices, but I worry that in situ examples like this make it hard for a learner to see the wood from the trees. @hixie mentions that there's some things we should keep like putting the example in a widget and `runApp()`ing that widget, so that hot reload works, but that the current boilerplate is mostly a historical accident.

Can we trim our basic template a little?

**Comment by gspencergoog** [comment]
Sure, we can totally trim that down.  It's a leftover from expanding out the templates that those examples used when they were embedded samples in the API docs.

It's a non-trivial effort though: there's 258 files that need to be looked at, probably mostly individually and by hand, and cut them down to size.

**Comment by gspencergoog** [comment]
There are probably a number of rote changes we could make, though, that would mainly be search and replace (e.g. removing the app titles). We'd have to make sure to not remove the title from an example about titles, though.

**Comment by maheshmnj** [comment]
Hi @timsneath, Thanks for filing the issue. 
Labeling it as a valid proposal to reduce boilerplate from the examples.

**Comment by timsneath** [comment]
Maybe as a starting point, @gspencergoog -- could we create a `_template.dart` file or something that I and others can use for new samples? We can easily go back and gradually fix up the old examples, but right now I'm not sure what we _must_ have. What is the absolute baseline?

**Comment by gspencergoog** [comment]
Sure, I can do that.

**Comment by gspencergoog** [comment]
It does depend a bit on what kind of example you want to make, basically boiling down to which level of library support you need: if it's a Material example, you need certain things, if it's fine as a widgets-only example, you don't. I'll try and put together a couple of templates that cover most cases.

**Comment by gspencergoog** [comment]
Actually, to give you an idea of the variety of conditions that can prompt different templates, take a look at the old templates we used to use: https://github.com/flutter/flutter/tree/master/dev/snippets/config/templates They're not "minimal" in the sense that they still include some really repetitive comments (which I already removed from the existing examples), and some things they don't strictly need to have, but it does show the variety that might be necessary in a set of templates.

(they're not deleted yet, because some dart:ui (engine-side dart) examples still use them. I'm in the process of eliminating those).
