### ISSUE TITLE
[CI] ci.yaml validation failed with 404 frequently

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#96503]
Multiple failures happened with "ci.yaml validation". This doesn't occur 100% but in a high frequency.

- https://github.com/flutter/flutter/pull/96375/checks?check_run_id=4784057148

**Comment by godofredoc** [comment]
There were a couple of PRs in the backend that changed graphql. Some of those queries were missing parameters causing exceptions to get the list of PRs from GitHub. Those PRs have been reverted but no new version of the backend has been released yet.

**Comment by akbiggs** [comment]
It looks like the ci.yaml validation might be timing out now, at least in Engine. Example failure: https://github.com/flutter/engine/pull/30817

**Comment by CaseyHillers** [comment]
The GraphQL issue was orthogonal to this. This appears to be a race condition in the GitHub CDN and their events system.

The logs show

```
Making HTTP GET request for https://raw.githubusercontent.com/flutter/plugins/56949bd47b857d49ed3f37e72775e9ee9204f697/.ci.yaml
```

which is failing, then it falls back to git-on-borg (which only works on postsubmit).

A secondary fallback we could try is using the GitHub API instead of CDN to get the content. As a first measure, I'll work on implementing https://github.com/flutter/flutter/issues/86299.
