### ISSUE TITLE
Camera shooting video direction inversion problem

### ISSUE THREAD

**Issue by 972706477** [flutter/flutter#96504]
When I fixed the screen orientation to landscape deviceorientation When landscaperight, then set the cameracontroller
. lockcaptureorientation (deviceorientation. Landscapeleft), click start recording, stop after a period of time, and then use fijkplayer to play the video. It is found that the video direction is inverted. How do you solve this problem

**Comment by darshankawar** [comment]
> and then use fijkplayer to play the video

that's a 3rd party plugin, so you probably need to raise this issue in dedicated repo, since you said, recorded video when played using that player, the video direction is inverted.

Does using the `camera` flutter plugin and use the landscape make the video recording inverted ? If so, please provide all requested details from the new issue template. If not, you can raise the issue in third party plugin you mentioned.
Closing from here. If you disagree, write in comments and I'll reopen it.
