### ISSUE TITLE
[web] Size regression basic_material_app_dart2js_size app size increased

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#96601]
https://flutter-flutter-perf.skia.org/t/?begin=1642043715&end=1642043716&subset=all
Commit: https://github.com/flutter/flutter/commit/2ab2ca2bc620e3e99711b3d2a11d08f3c94b73ba

**Comment by yjbanov** [comment]
The gzip size of the basic material app increased from 392kb to 396kb. Not a huge increase, but it's just one widget. If we migrate 50 more widgets to material 3, will we add 200kb? Or does this change introduce some shared libraries that we can amortize across multiple widgets?

I'll leave it to @darrenaustin to make the final call whether 4kb increase is acceptable.

**Comment by darrenaustin** [comment]
@yjbanov thanks for the detective work on this.

Unfortunately these changes really aren't shared across the widgets, so there will be no amortization when we migrate more widgets. That said, it may not be that bad due to: 

- Half of that cost will go away once the Material 3 migration is complete and we can remove the Material 2 defaults.
- The number of widgets affected (at least right now) doesn't appear that big (~10 - 20)

That said, this is a little troubling. I wouldn't have thought that just adding a couple of theme subsclasses would have increased the size by that much. I will look into reducing the number of methods we use on these to see if I can bring it down. I'll update this when I have any details.
