### ISSUE TITLE
Test `test\integration.shard\background_isolate_test.dart: Hot restart kills background isolates` caused Windows tool_integration_tests_1_5 flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#96677]
Four out of top 10 builds have hit the test flake, and is blocking the tree now.
<img width="324" alt="Screen Shot 2022-01-14 at 1 26 13 PM" src="https://user-images.githubusercontent.com/54558023/149587376-69ae1875-910c-47b5-b363-b23c884a3621.png">

[Example build](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_1_5/2695/overview).

```
12:39 +18 ~2 -1: test\integration.shard\background_isolate_test.dart: Hot restart kills background isolates [E]                                                                                        
  Bad state: Future already completed
  dart:async                                                 _SyncCompleter.complete
  test\integration.shard\background_isolate_test.dart 40:32  main.<fn>.<fn>
```

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/pull/96678 to skip the unit test.

**Comment by keyonghan** [comment]
assigning to test owner @zanderso for further triage.

**Comment by zanderso** [comment]
It looks like on Windows the write to the file isn't visible before the hot restart is triggered.

**Comment by christopherfujino** [comment]
breadcrumb for myself: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/background_isolate_test.dart#L25

**Comment by christopherfujino** [comment]
I bisected this to https://github.com/flutter/engine/pull/30839

**Comment by christopherfujino** [comment]
> It looks like on Windows the write to the file isn't visible before the hot restart is triggered.

I can confirm that this is not the case; I was able to reproduce the failure while verifying the contents of the file were updated first. Interestingly, I can reproduce the failure ~80% of the time (more than 40% on CI) on a faster Windows computer.

**Comment by aam** [comment]
I believe the test has typo: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/background_isolate_test.dart#L53 should say `await sawNewBackgroundMessage.future;`.
The way it's written the test will race to completion with more prints showing up on stdout because that `await` is no-op since the future has already been completed.

It doesn't explain why we are seeing message from the original worker isolate on the stdout after hot restart, but it explains flakiness.

**Comment by christopherfujino** [comment]
> 

Good point, that looks like it should be `sawNewBackgroundMessage.complete()`

**Comment by zanderso** [comment]
@aam I think we need help determining why this test was (perhaps accidentally) passing before your change in https://github.com/flutter/engine/pull/30839. In what cases was that branch being taken when it shouldn't have been before you removed the `||` clause with the flag check that would have affected background isolates?

**Comment by aam** [comment]
Before https://github.com/flutter/engine/pull/30839 when spawning child isolate, engine would always reload kernel file even if child isolate was part of the same isolate group as parent isolate . After https://github.com/flutter/engine/pull/30839 child isolate would reuse already loaded kernel file, speeding up how long the spawning of the child would take.
There is a race in the test, which before the change was normally won by the test getting to the end(through already completed future). After the change, child isolate would get up and running before the test completes resulting in Future already completed error.
I believe the root cause is that the engine restarts the test app from the original dill/kernel file, not sure where the step that updates kernel file after source file is updated would belong in this test setup.

**Comment by aam** [comment]
One thing that seems to be broken is that flutter code that looks for updated sources https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L1436 does not take into account the fact that `modified` property on a file on Windows returns `DateTime` with seconds-granularity, while that is being compared to `lastCompiled` `DateTime` which has microsecond-granularity. This leads to reload/restart tests to miss file updates. (when last compilation is completed at xx.001, file is updated at xx.500, it gets recorded as xx.000, which will be less than xx.001).
There is a crutch for that in a form of optional `writeFutureModifiedDate` parameter to `writeFile` test method https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_utils.dart#L33 - that can be used in this background_isolate_test as well(https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_data/background_project.dart#L54).
