### ISSUE TITLE
Document requirements around containment and ownership for material widgets

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#967]
From @sethladd per email thread:

"I've been very confused about when I need to wrap my thing in a Material."

From @jason-simmons per chat conversation:

"In general, is essentially every app supposed to use MaterialApp?  or is the rule that if you use material widgets, then you must wrap them in a MaterialApp?"

We should have documentation to answer these kinds of questions.  (We might also want analyzer warnings, but I'll leave that for a separate issue.)

**Comment by Hixie** [comment]
I think the two questions in the OP here are somewhat separate things, and the second one in particular was because of a (now-fixed) bug.

For the first, I see several things we could do, but the simplest, if anyone reads documentation, is probably to just be explicit in the docs for each class that needs a Material ancestor that it needs a Material ancestor.

But then again, nobody reads the documentation.

Not sure what more we can do. Widgets that need Material all assert when they're not in Material these days, so it's not like you'll have subtle bugs, it'll be a simple assert with a simple message.

**Comment by krisgiesing** [comment]
Yeah, the second question isn't related, but I thought it might be due to the discussion around the previous discussion. I just wasn't sure how many rules there were, or whether Material containment was the only one.

No one reads the docs right now because they're woefully incomplete, but we should fix that :)

Anyway, I logged the issue so it didn't get completely lost, but this could wait until a general documentation pass, if we're planning one.

**Comment by Hixie** [comment]
Nobody reads docs even when they're complete. Documentation has to exist for people to respect you, but few people ever read it. That's just the reality of our industry, unfortunately.

The general documentation pass is now. Everyone should do their part to document everything. :-) If you come across something underdocumented, document it right there and then and file a PR for it. :-)

**Comment by krisgiesing** [comment]
FWIW, I read documentation constantly, for things that are documented.
