### ISSUE TITLE
[url_launcher] Flutter web app : open url in the default smartphone browser 

### ISSUE THREAD

**Issue by azazadev** [flutter/flutter#96751]
I have a firebase dynamic link that can be share in social media like facebook

in some cases when user click on the dynamic link from Facebook app ( example the link is my flutter web app : https://mydomain.app ) this link will be open inside the Facebook browser ( default behavior ) so it's ok

now inside the Facebook browser I have the home page of my flutter web app with button 'start' to navigate to page1 for example ( https://mydomain.app/page1 ) . So what I want to do is :

- when user click on 'start' button the new page ( page1 ) should be open in the default browser ( safari or chrome ) rather then the current facebook browser

Note : I have try all options of url_launcher and also html.window.open('https://mydomain.app/page1', '_self') but still new page ( page1 ) is open in Facebook browser, any idea how I can launch page1 url in the default smartphone browser rather then the current Facebook browser ?

**Comment by darshankawar** [comment]
@azazadev 
It seems like your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of finding a solution on how to launch url in default browser, rather than reporting a bug.
If you disagree and think this is a bug, write in comments and I'll reopen.
