### ISSUE TITLE
Reconsider profiler off-by-default

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#9677]
The profiler is off by default because LLDB does not play well with SIGPROF, causing the process being debugged to be dramatically slower. John has since added logic in the VM that stops the profiler from starting if the process is connected to a debugger.

**Comment by eseidelGoogle** [comment]
@chinmaygarde did this work iirc.  I suspect this mostly affects Mac/iOS dev?

**Comment by chinmaygarde** [comment]
I will turn on the profiler. @rmacnak-google: Have we rolled Dart to include John's patch to detect if the debugger is connected? If you point me to the SHA, I can check myself.

**Comment by rmacnak-google** [comment]
It's from February dart-lang/sdk@95a816652385f55c796328026ac144e5a9390861.

I noticed this because I was trying to turn on part of the profiler on Fuchsia, but the VM's default value was being overruled by the engine.

**Comment by chinmaygarde** [comment]
Patching now.

**Comment by chinmaygarde** [comment]
Turns out toggling the profiler could already be controlled by command line flags.

After speaking to @rmacnak-google, I now better understand the issue. There is no ability to pass command line flags on Fuchsia to the shell on initialization (to enable profiling). So the suggestion was to flip the defaults.

I think it is a better idea to figure out how to control `blink::Settings` on Fuchsia without resorting to command line arguments as there are definitely going to be more options that may need to be toggled in the future. cc @abarth.

**Comment by abarth** [comment]
The way Chrome works around this problem on Android is to read a file at a known path and interpret that as the command line options.  Hopefully we can come up with a better solution...

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by chinmaygarde** [comment]
I believe so.

**Comment by jonahwilliams** [comment]
FYI @johnmccutchan , since he's back.

I think we're not going to do this, but just checking.

**Comment by rmacnak-google** [comment]
The Mac/iOS profiler is no longer based on SIGPROF, instead using the Mach suspend/get_state/resume functions.

**Comment by johnmccutchan** [comment]
Just documenting some state from ~7 years ago:

1) The Mach-based suspend/get_state/resume functions have been used by the Dart VM for a _long_ time (definitely more than 7 years ago).
2) The Mach-based approach has much worse performance the SIGPROF and we can't sample at the same rate because of it.
3) Having the profiler on by default for profile and debug builds seems like a good thing but probably not high priority.
