### ISSUE TITLE
error: cannot find symbol import io.flutter.plugins.firebase.core.FirebaseCorePlugin;

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#96821]
The app should run, but it is not. 

  cupertino_icons: ^1.0.4
  google_sign_in:
  firebase_auth: ^3.3.5
  cloud_firestore: ^2.5.3
  rxdart:
  image_picker: ^0.8.4+4
  file_picker: ^4.3.2
  firebase_storage: ^10.2.5
  location: ^4.3.0
  geocode: ^1.0.1
  font_awesome_flutter:
  shared_preferences:
  cached_network_image: ^3.2.0
  image: ^3.1.1
  path_provider: ^2.0.8

**Comment by darshankawar** [comment]
@andesappal 
You haven't provided enough details to address this issue properly. Please provide the complete error log you are getting along with your `flutter doctor -v`.
As a note, when filing an issue, please use the new issue template and fill out details so that we'll have enough details to analyze the issue.

**Comment by andesappal** [comment]
Hi @darshankawar, here's the doctor -v:
![image](https://user-images.githubusercontent.com/54340176/150148646-39fedd40-f621-4652-93f2-b6c5138242d4.png)

Let me fill out the new issue template next, sorry.

**Comment by darshankawar** [comment]
@andesappal 
You seem to be using `firebase_auth` which is third party plugin, so can you remove that plugin and related code and try again to see if you still get the same behavior ?

**Comment by andesappal** [comment]
Hi @darshankawar I am no longer trying to run this sample app, so therefore closing this issue. Thank you.
