### ISSUE TITLE
Unable to find modules in ios.

### ISSUE THREAD

**Issue by ArmdStrong** [flutter/flutter#96834]
Hello to fellow flutter developers.
I am having trouble building an flutter application that i have created. The application works just fine. But the problem lies in building the app. In the last step, i have come across an 'parse issue' error module not found. I would appreciate the help. Please and Thank you.
![2584681B-D5A8-4B3F-A72F-92DCF10DD7F0](https://user-images.githubusercontent.com/98003595/150061086-0b6d33f6-85a0-4530-b94e-ded8cf48bbf9.jpg)
 The error  shows the following text.
fatal error: module 'barcode_scan2' not found
    @import barcode_scan2;
     ~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

**Comment by darshankawar** [comment]
@ArmdStrong 
`fatal error: module 'barcode_scan2' not found
@import barcode_scan2;`. This may happen due to version incompatibility. Check what version `barcode_scan2` plugin is on and you may need to update it to support minimum deployment target as required by iOS.

Also, this doesn't seem to be a flutter issue. You can ask this question on support channels like StackOverflow.
Closing from here.
