### ISSUE TITLE
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by ShradhaMaheshwari-VVDN** [flutter/flutter#96979]
Repeatedly facing this issue in iOS. Getting error logs-
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:156:7)
<asynchronous suspension>
2022-01-21 11:54:56.730517+0530 XIQ[9111:101130] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.setMixWithOthers (package:video_player_platform_interface/messages.dart:408:7)
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:video_player/video_player.dart:338:7)
<asynchronous suspension>

```

**Comment by darshankawar** [comment]
@ShradhaMaheshwari-VVDN 
Just providing the error log isn't enough to properly address the issue. Whenever you open an issue, please use new issue template and fill out requested details so that we'll have enough details to analyze the issue.

For now, can you provide `flutter doctor -v`, `pubspec.yaml`, a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugin that we can directly run and also the complete error log in properly formatted text.
