### ISSUE TITLE
plugin/video_player How to create two timestamps on the live video from network

### ISSUE THREAD

**Issue by aedthuill** [flutter/flutter#97001]
I was thinking about to create two timestamps in video from network and get the exact part of video between these two tomestamps. How can i achive this with video_player plugin? I saw in doc it has the `controller.seekTo` . Can this work? Am I on the right path with my research?

**Comment by danagbemava-nc** [comment]
Hi @aedthuill, this seems like a discussion for either StackOverflow or any of the communities in https://flutter.dev/community#community-grid. 

The flutter issue tracker is for reporting bug reports or feature requests for flutter. 

Seeing as this issue is neither of those, I'm going to close this issue. 

Thank you
