### ISSUE TITLE
[file_selector] Improve API docs and examples

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#97011]
The API docs for `file_selector` are extremely thin right now; they are pretty much just the one-sentence summary, with no explanation of parameters or edge cases (e.g., what a `null` return means). We also don't show examples of most of the parameters in the example app.

(/cc @ditman)

**Comment by TowaYamashita** [comment]
Hello. @ditman 
I am interested in this issue because I have some experience using file_selector in my work.
So, I would like to work on this issue.
If at all possible, could you please assign this issue to me?
I'm not very good at English, so I'm worried if I'm expressing myself in a way that might offend you.
However, I will work diligently on the issue and I hope you will consider it.

**Comment by stuartmorgan** [comment]
You don't need to have the issue assigned to you to work on it; feel free to submit a PR with improvements.

**Comment by TowaYamashita** [comment]
@stuartmorgan 
thanks, I will try it;

**Comment by ditman** [comment]
Thank you very much for your contribution @TowaYamashita! Looking forward to it!

**Comment by TowaYamashita** [comment]
Hi, @ditman 
Could you please do code review?
I've added some comments about `file_selector`, but it would be nice if you could take a look at it to see if it's worded in a confusing way.

**Comment by ditman** [comment]
Thanks @TowaYamashita! I hadn't noticed your PR! @stuartmorgan has already assigned himself there, so he's probably going to review it soon! I'll take a quick look too!

Thanks for the contribution!

**Comment by TowaYamashita** [comment]
@ditman @stuartmorgan 

Sorry for the delay in responding to your comment. 🙇
I planning on updating this PR .
I am currently modifying the code.

I do apologize for any inconvenience caused. 🙇
