### ISSUE TITLE
Upgrade test_api dependency

### ISSUE THREAD

**Issue by nielsenko** [flutter/flutter#97131]
On the current beta channel, the `flutter_test` and `flutter_driver` sdk dependency pins `test_api` to **0.4.8**. There is a never version **0.4.9** that is a requirement for `test` **1.20.0+**. Some packages already depends on this, especially `analyzer` **3.0.0+**. I'm working on a builder that is hitting a bug in the `analyzer` package that is fixed in **3.0.0**. 

I would like to urge you to update the pinned version of `test_api` in beta before the next release. Otherwise users will need to do a _dependecy_override_ on `test_api`, which is not ideal

**Comment by stuartmorgan** [comment]
It has [already been updated](https://github.com/flutter/flutter/blob/3e6e996f9eff50d77214d37c1c5f8b71bcc0d559/packages/flutter_test/pubspec.yaml#L15)

It's general best to check master before filling issues about dependency versions; they are updated regularly.

**Comment by mit-mit** [comment]
@stuartmorgan this was not a request for master; it was a request to get this updated in beta (i.e. essentially a cherry-pick request).

**Comment by devoncarew** [comment]
@nielsenko - thanks for the report! A few questions:

> test 1.20.0+. Some packages already depends on this, especially analyzer 3.0.0+

How is the analyzer dep on test visible to people who depend on analyzer? Analyzer depends on test via a dev dependency.

> I'm working on a builder that is hitting a bug in the analyzer package that is fixed in 3.0.0.

Do you have a link to the bug? I'm wondering how widespread the issue is - how many people would be impacted by this analyzer bug. In addition, when you say builder, do you mean you're doing some code gen?

Thanks!

**Comment by nielsenko** [comment]
No, I don't have a link to an issue on `analyzer`. I just tried updating to version `3.0.0` (from `2.8.0`) and noticed it was resolved. 

Yes, I'm doing codegen. I have this somewhat unusual requirement that makes the builder a normal _dependency_, not a _dev_dependency_. Hence, it drags in the `analyzer` as a transitive dependency for our users. Since `analyzer 3.0.0` depends on `test ^1.20.0` which depends on `test_api ^0.4.9` we end up forcing the user to use a never `test_api` than currently supported by flutter. It is true, it works on `master`, but I wondered if it could be cherry-picked to `beta` as well, as it is closer to be released.

Anyway, I'm also investigating what it will take to work around the issue we see with `analyzer 2.8.0`.

**Comment by stuartmorgan** [comment]
> @stuartmorgan this was not a request for master; it was a request to get this updated in beta (i.e. essentially a cherry-pick request).

Many (most?) Flutter bugs are filed against stable or beta; this isn't distinguishable from them. And in particular we have bugs like this (please update pinned dependency X) filed on a regular basis. We've never treated them any differently from other bugs filed against non-master channels--which is to consider them fixed once they are fixed on master.

Cherry pick requests should be clearly identified as such in order to be triaged correctly.

**Comment by nielsenko** [comment]
Hi @stuartmorgan 

I'm sorry if I made a mistake raising the issue. I should have mentioned that I was aware of the fix on master. You are of course entitled to close as you did - I was just hoping that it would be a minor thing on your end.

Br, Kasper

**Comment by nielsenko** [comment]
We have found a work-around. Sorry for the inconvenience.
