### ISSUE TITLE
Flutter web App extremely slow to load first Time

### ISSUE THREAD

**Issue by afzl-wtu** [flutter/flutter#97228]
I saw previous issue on github. But none of them is helpful.
Here are two examples: one is flutter template app and other is build with php. Compare speed of loading both apps:

[App build with PHP](https://pi.afzl.me/#/)
[Flutter template app flutter build web](https://afzl.me/#/)

First one only take 2 seconds to fully load but flutter app takes atleast 15 second to load first time (after that it cache itself but still slow). 
Do Flutter or Google expects people to use flutter for their websites lol.

**Comment by maheshmnj** [comment]
Hi @afzl-wtu, Thanks for filing the issue, I ran your sample flutter app and it seems to load under 5 seconds for the first time and almost instantly later. Is this app built with canvaskit or auto renderer?  If yes then this is a known issue, To improve this further there is an open issue tracking this request https://github.com/flutter/flutter/issues/76009

**Comment by afzl-wtu** [comment]
> Hi @afzl-wtu, Thanks for filing the issue, I ran your sample flutter app and it seems to load under 5 seconds for the first time and almost instantly later. Is this app built with canvaskit or auto renderer? If yes then this is a known issue, To improve this further there is an open issue tracking this request #76009

Thanks for reply . it is just build with "Flutter build web" I am using Flutter 2.8.2.

But you can compare it with above complex php app there is a difference of  sky and earth. 

No one will allow to use flutter on his web server.

**Comment by maheshmnj** [comment]
> it is just build with "Flutter build web"

That means you built with auto renderer which uses canvaskit on desktop and html on mobile devices. You can read more about it here https://docs.flutter.dev/development/tools/web-renderers

> I am using Flutter 2.8.2.

The latest stable version is  `2.8.1`, To get the latest fixes and features use the master branch. Closing this issue in favor of the linked issue above, since there is already an issue tracking this request.

> No one will allow to use flutter on his web server.

ps: You are comparing flutter web with a native technology that has been there for a decade now. software takes time to stabilize especially when its something complex like flutter which runs same thing on multiple platforms. (This is just a personal thought)
