### ISSUE TITLE
Mac tool_integration_tests_3_4 flakes on `flutter_adapter_test`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97238]
(part of https://github.com/flutter/flutter/issues/97036)
These data is based Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flutter_adapter_test.dart flake ([2634](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_3_4/2634/overview))

```
05:58 +26 -1: test/integration.shard/debug_adapter/flutter_adapter_test.dart: can hot restart [E]                                                                                                      
  Expected: [<a string starting with 'Restarted application'>, 'topLevelFunction']
    Actual: [
              'Restarted application in 342ms.',
              '[Sentinel kind: Collected, valueAsString: <collected>] from ext.flutter.connectedVmServiceUri()',
              'Failed to set vm service URI: [Sentinel kind: Collected, valueAsString: <collected>] from ext.flutter.connectedVmServiceUri(). Deep links to DevTools will not show in Flutter errors.'
            ]
     Which: at location [1] is '[Sentinel kind: Collected, valueAsString: <collected>] from ext.flutter.connectedVmServiceUri()' instead of 'topLevelFunction'
  
  package:test_api                                                      expect
  test/integration.shard/debug_adapter/test_support.dart 43:5           expectLines
  test/integration.shard/debug_adapter/flutter_adapter_test.dart 180:5  main.<fn>
```

**Comment by christopherfujino** [comment]
@DanTup you have any insight on this test flake?

**Comment by keyonghan** [comment]
> Do you have any idea of how often it's failing like this?

Scanning through flakes over the past quarter (from oct. 2021 to early jan. 2022), and seemed to hit only this one.

**Comment by DanTup** [comment]
I believe this failure was caused by some unrelated output written to stderr as the restart was happening from here:

https://github.com/flutter/flutter/blob/cd239599e7d40e5ddf28cd977db912535a9bed01/packages/flutter_tools/lib/src/resident_devtools_handler.dart#L215-L221

The test is looking for specific output events sent to stdout to ensure the app restarted, but wasn't filtered to stdout (so this interleaved stderr output failed the check).

I've got a PR here that tweaks the test to only look at stdout so unrelated output to stderr won't affect its check that the application restarted and is running correctly:

https://github.com/flutter/flutter/pull/97291

(Although, I'm not certain that the stderr output is indicative of another issue unrelated to the DAP functionality)
