### ISSUE TITLE
ToggleButtons with  MaterialTapTargetSize.padded and height constrained to 32

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#97302]
This issue corresponds to Google internal issue b/204226713. **It does not need additional triage.**

The ToggleButtons height has been constrained to 32 but the input area has been padded, per MaterialTapTargetSIze.padded, to 48.  The Toggle button has been wrapped in a green Container to highlight the input padding.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  const Home({ Key? key }) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int selectedTabIndex = 0;

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    return Scaffold(
      body: Center(
        child: Container(
          color: Colors.green.withOpacity(0.15),
          child: ToggleButtons(
            tapTargetSize: MaterialTapTargetSize.padded,
            isSelected: [
              selectedTabIndex == 0,
              selectedTabIndex == 1,
            ],
            onPressed: (int index) {
              setState(() { selectedTabIndex = index; });
            },
            borderRadius: const BorderRadius.all(Radius.circular(8)),
            selectedBorderColor: colorScheme.primary,
            selectedColor: colorScheme.primary,
            constraints: const BoxConstraints.tightFor(
              width: 86,
              height: 32,
            ),
            children: [
              Text('Locks'),
              Text('Unlocks'),
            ],
          ),
        ),
      ),
    );
  }
}
void main() {
  runApp(const MaterialApp(home: Home()));
}
```
</details>

**Comment by math1man** [comment]
I think I've figure out the problem. In https://github.com/flutter/flutter/pull/93259 you're padding around each button, but you're not creating a new `SemanticsNode` for the padding. In contrast, [`ButtonStyleButton`](https://github.com/flutter/flutter/blob/77d935af4d/packages/flutter/lib/src/material/button_style_button.dart#L29) wraps its `_InputPadding` widget in a `Semantics` widget so that the `SemanticsNode` has the larger size. In the case of `ToggleButtons`, this should in theory be solvable by wrapping the `_InputPadding` widget in a `MergedSemantics`. Unfortunately, it looks like `ToggleButtons` wraps the whole group of individual buttons in `_InputPadding` as opposed to each individual button, so adding `MergedSemantics` is not trivial.

**Comment by Piinks** [comment]
Reopening as the change is being reverted
