### ISSUE TITLE
Dart -> Engine roll failing due to removal of dart-sdk/bin/pub

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97471]
Starting with the roll attempt here: https://github.com/flutter/engine/pull/31140, the Dart roll into the Engine is failing due to the removal of the `pub` entry in `dart-sdk/bin`: https://dart.googlesource.com/sdk.git/+/872ffa85c2a5946eecc99236f9e952888a28b74f.

@sigurdm

**Comment by dcharkes** [comment]
I've filed two PRs:

* https://github.com/flutter/engine/pull/31181
* https://github.com/flutter/flutter/pull/97575

These two PRs only cover the subset in the Dart HHH bot, there might be more uses of `pub` in the Flutter codebase.

And requested the removal of `pub` to be reverted so that we can get things green. https://dart-review.googlesource.com/c/sdk/+/231081

**Comment by zanderso** [comment]
@dcharkes please take a look at the full set of failures on the Dart -> Engine roll listed above to make sure they are covered. https://github.com/flutter/engine/pull/31140 /cc @a-siva

**Comment by dcharkes** [comment]
> @dcharkes please take a look at the full set of failures on the Dart -> Engine roll listed above to make sure they are covered. flutter/engine#31140 

6 failing bots, with 9 red steps, and 3 purple steps

All 9 red steps are due to `run_tests.py`:
* https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Host%20Engine/31676/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/8449/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/8451/overview

The other ones are recipe issues:
* https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Web%20Engine/22864/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/22540/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Web%20Engine/20366/overview

I've created a recipe CL to address these: https://flutter-review.googlesource.com/c/recipes/+/26120

**Comment by a-siva** [comment]
The CL that removed pub has been reverted and rolls are progressing again. I presume we can use this bug to track the issues that need fixing before the CL to remove pub can land again.
Can the prioritity of this be dropped as it is not blocking Dart rolls.

**Comment by dcharkes** [comment]
All the issues that surfaced in Dart HHH and the failed roll have been addressed by the 3 CLs. 

@sigurdm I think it's safe to reland the removal of pub. Please add the Flutter bots to the CL before doing so.

**Comment by sigurdm** [comment]
@dcharkes Thanks!

> Please add the Flutter bots to the CL before doing so.

Will do!

**Comment by zanderso** [comment]
Dropping priority since this is no longer blocking rolls.

**Comment by dcharkes** [comment]
Relanded today: https://dart-review.googlesource.com/c/sdk/+/231943

If the roll succeeds this can be closed.
