### ISSUE TITLE
DraggableScrollableSheet leaves traces when scrolling

### ISSUE THREAD

**Issue by kamami** [flutter/flutter#97482]
## Steps to Reproduce

1. Switch to `master` channel of flutter
2. Execute `flutter run` on the code sample 

**Expected results:**
Draggable Sheet should work as expected without those red lines.

**Actual results:** 
Draggable Sheet shows red lines on the background.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

Future main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final DraggableScrollableController _sheetController =
      DraggableScrollableController();

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
          backgroundColor: Colors.green,
          body: DraggableScrollableSheet(
            controller: _sheetController,
            snap: true,
            minChildSize: 0,
            maxChildSize: 1,
            initialChildSize: 0.2,
            snapSizes: const [0.0, 0.2, 1],
            builder: (context, controller) {
              return ListView(controller: controller, children: [
                Container(
                  height: 400,
                  color: Colors.red,
                )
              ]);
            },
          ),
        ));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.281, on macOS 12.1 21C52 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

</details>

This video was recorded on my real Pixel 2 XL

<details>
<summary>video </summary>

https://user-images.githubusercontent.com/43880037/151663354-bfa602f4-d017-4e6f-af8d-0c02a45ca895.mp4
</details>

@caseycrogers

**Comment by danagbemava-nc** [comment]
Hi @kamami, can you upgrade to the latest version of `master` to see whether or not this is an issue? 
I tested on `Poco X3 NFC` but I didn't see any visual issues. See video below

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/151770044-f1446c0e-96c4-47ef-bb79-2d8f6e117062.mp4

</details>

**Comment by kamami** [comment]
I upgraded to the lates version of `master` and the bug still persists on my Pixel 2 device. However on emulator (Pixel 5) it works fine.

**Comment by danagbemava-nc** [comment]
Can you share the specs of the Pixel 2 device?

**Comment by kamami** [comment]
Sure! It is a Pixel 2 XL running Android 11

**Comment by danagbemava-nc** [comment]
Hi @kamami, let me trouble you just a bit. 

- Do you have any other devices that you can verify this behavior on? (I tested on a pixel 2xl emulator, it didn't reproduce)
- Lastly, since master is updated almost daily, there's a new version out, can you check if it still reproduces on the latest master? 

Thank you

**Comment by kamami** [comment]
I tested it on my OnePlus Nord (Android 11) and the issue does not appear there - Only on my Pixel 2 XL (Android 11). 
I upgraded to the latest master @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @kamami, can you confirm whether or not this reproduces in either `release` or `profile` mode as well?

**Comment by kamami** [comment]
@danagbemava-nc here are my observations:
- I tested in `release` and `profile` mode on `master`, both times I get those red lines.
- After that I switched back to stable and without the controller it is working fine, no red lines!

**Comment by danagbemava-nc** [comment]
@kamami, thanks for your effort. 

Please provide screen recordings of stable and master so we can do a side-by-side. I'll also need the outputs of `flutter doctor -v`

Thank you

**Comment by kamami** [comment]
@danagbemava-nc here are the requests information

**Tested on real Pixel 2XL running Android 11.**

Channel `master` (with controller & red lines):

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.423, on macOS 12.1 21C52 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

https://user-images.githubusercontent.com/43880037/152520645-74507ebc-ed59-4589-9483-a1f6e0a6d8e9.mp4

Channel `stable` (without controller & no red lines):

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

```
https://user-images.githubusercontent.com/43880037/152520692-bc057873-2699-40d0-91e1-64478dce0719.mp4

**Comment by danagbemava-nc** [comment]
Hi @kamami, I'm curious, do the redlines appear when you take out the controller on master as well?

**Comment by kamami** [comment]
It is also showing the red lines on `master` without the controller. Just tested it. Seems to be a general problem with Draggable Sheet on `master`... Will switch back to `stable` so long, even if I really need the controller.

**Comment by caseycrogers** [comment]
> 

As of a day or two (latest flutter release) the controller is now available on stable!!

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation. 
I'm not able to reproduce this locally, as it seems to be device-specific. See https://github.com/flutter/flutter/issues/97482#issuecomment-1028010104.

There's a chance that this could be a regression since OP says it reproduces on `master` but not on `stable` on their physical device. See https://github.com/flutter/flutter/issues/97482#issuecomment-1029902550 for a side-by-side.

It doesn't seem to be related to the addition of the controller based on https://github.com/flutter/flutter/issues/97482#issuecomment-1030373393

**Comment by chinmaygarde** [comment]
cc @iskakaushik in case this is related to dirty region management. We did an extensions check in triage and couldn't rationalize this as a bug in the DRM subsystem. It could be device specific but we should figure out how to trace DRM rects in traces.

**Comment by kamami** [comment]
I switched back too `stable 2.10` and it seems that the `DraggableScrollableController` is not a `listenable` anymore? Back on master it still was. Any plans to make it a `listenable` again on `stable`?

**Comment by Hixie** [comment]
Looking at the view it looks like it's something being left on our buffers, which definitely points to the dirty rect logic. Notice how it flips back and forth between two images with the red lines in different places, and how the red lines are right at the edge of the last thing that changed.

**Comment by iskakaushik** [comment]
As a data point, I wasn't able to reproduce this on my Pixel 4 and another lower end device as well. I am suspecting that this might be a device specific issue, I will add additional logging to help debug this issue further.

**Comment by knopp** [comment]
This definitely looks like a problem with partial repaint. I should have access to a Pixel 2 Xl device later today so I'll try to reproduce this.

**Comment by knopp** [comment]
I got a Pixel 2 device and I was able to reproduce the problem. I have currently Android 8 on it, and the glitches are even more severe.

After some experimentation I found out that the problem seems to be that the area passed into `EGL_KHR_partial_update` must be aligned to 4 pixels. Otherwise the surface gets corrupted resulting in wild artifacts (on Android 8).

It seems that on Pixel 2 with Android 11, the call to `EGL_KHR_partial_update` already aligns the area to 4 pixels. However DiffContext doesn't know about it, so it draws slightly smaller area than necessary, causing the lines in video. I can get exact same behavior on Android 8 if I adjust area passed to `EGL_KHR_partial_update` but leave diff context unchanged.

If the alignment is enforced directly in DiffContext, then the correct area gets repainted and the rect that `EGL_KHR_partial_update` gets is already aligned so there are no glitches and everything works as expected.

This should be rather straightforward to fix (GLContext needs to communicate necessary alignment) and I should have PR for this soon. The question is what should the alignment be. This is not mentioned in `EGL_KHR_partial_update` specification and seems to be device dependent (most Android devices don't seem to need any specific alignment here). 

@dreveman, we had a discussion about this a while ago, where you suggested that some GPU architectures might benefit from aligned clip rect, I'm not sure if this is the same thing though. The necessary alignment here is 4 pixels (i.e. much less than tile size on Mali). Any thoughts on this?

**Comment by iskakaushik** [comment]
@knopp given that the spec for `EGL_KHR_partial_update` doesn't detail any alignment, it makes me think that this is an issue with the driver or implementation specific to the device. I'm wondering if it would make sense to disable partial repaint on specific SOCs.

**Comment by knopp** [comment]
Eventually we might need to disable this for some SOCs, but I don't think this is quite it. I was expecting having to implement the alignment regardless, because of tile based GPUs that compress the framebuffer (i.e. Mali). For these having clip that doesn't align on individual tiles can cause performance degradation because the tile needs to be read back and decompressed. I think the usual tile sizes are 16x16 and 32x32 pixels, so for now I'd just go with aligning the clip on android to 32x32, and then see if there are still some devices that have issues with this.

**Comment by knopp** [comment]
PR that should fix this: https://github.com/flutter/engine/pull/31359 (needs some tests)
