### ISSUE TITLE
The element type 'Timer' / Future<Widget> can't be assigned to the list type 'Widget'.

### ISSUE THREAD

**Issue by Farial-mahmod** [flutter/flutter#97562]
I am trying to insert a Timer (a Future<> will work instead) into a Widget list so that a string can be printed after a delay using the Timer (or, Future delayed) . 
There is no solution or workaround to this issue in StackOverflow or Reddit as far as I can see. I appreciate any workaround in advance.

I am getting the following error: _The element type 'Timer' / Future<Widget> can't be assigned to the list type 'Widget'._

Here is the code inside ListView:

 ```
Container(
                    child: Row(
                      children: <Widget>[
                        Text('Re-Send Code in ',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            //fontWeight: FontWeight.bold,
                              color: Colors.black,
                              fontWeight: FontWeight.w500,
                              fontSize: 17),),

                        TweenAnimationBuilder<Duration>(
                            duration: Duration(seconds: 31),
                            tween: Tween(begin: Duration(seconds: 31), end: Duration.zero),
                            onEnd: () {
                              Timer(Duration(seconds: 5), () {
                                print("Rokomari.com");
                              });
                            },
                            builder: (BuildContext context, Duration value, Widget child) {
                              final minutes = value.inMinutes;
                              final seconds = value.inSeconds % 60;
                              return Padding(
                                  padding: const EdgeInsets.symmetric(vertical: 5),
                                  child: Text('$minutes:$seconds',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          color: Colors.black,
                                          fontWeight: FontWeight.bold,
                                          fontSize: 17)));
                            }),       

### // adding a Timer or Future fails here  

                      ],
                      mainAxisAlignment: MainAxisAlignment.center,
                    )
                )
```

**Comment by darshankawar** [comment]
@Farial-mahmod 
If you are trying to use a `Future`, you'll need to use `FutureBuilder`. See [this](https://stackoverflow.com/questions/66242242/futurewidget-cant-be-assigned-to-the-list-type-widget) similar link and check if it helps to resolve your issue. 

Also, your question / issue is better suited for support channels like StackOverflow, as this is more of a code implementation issue rather than a bug, so closing from here.

Similar links for your reference: 

https://stackoverflow.com/questions/50392607/the-element-type-listwidget-cant-be-assigned-to-the-list-type-widget

https://fluttercorner.com/the-element-type-listwidget-cant-be-assigned-to-the-list-type-widget/
