### ISSUE TITLE
Would like to be able to change ios/Runner.xcodeproj to ios/MyName.xcodeproj

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9767]
@lukef brought up the question this morning if it would be possible to change ios/Runner.xcodeproj to ios/MyName.xcodeproj.  My understanding from @cbracken is that there are several places in our code which currently look for the word "Runner" or assume that path which would break if that was done.

We could certainly support this, but my understanding is changing the name is not "supported" out of the box.  I don't know what the situation is on the Android side (if there are any path naming issues there).

**Comment by cbracken** [comment]
There are a few places in `flutter_tools` where we make the assumption around the name `Runner`. The biggest issue that springs to mind is that iOS logging relies on it (in `src/ios/devices.dart`) as a heuristic for filtering all device logs down to just those associated with the app.

For future ref, other than the templates themselves:
```
git grep '\WRunner\W' packages/flutter_tools/lib
```
should return the bulk of them.

**Comment by eseidelGoogle** [comment]
Let me know if this is blocking you @lukef, otherwise I'm inclined to mark this for a distant milestone. ;)

**Comment by lukef** [comment]
Not blocking. Feel free to de-prioritize.

**Comment by Hixie** [comment]
We agree that we should support this, but we don't plan on doing this any time soon. Please do let us know if this is a priority for you.

**Comment by zontarian** [comment]
If you really want to promote Flutter as a real alternative to native dev, or serious multiplatform dev, this issue should not postponed to a distant milestone, I think. 
On Android the dev process is well oiled and tested, on iOS at first, with a real app and non trivial settings and configurations, seems a nightmare.

It's real that is a nightmare that is well repeatable and defined. And which can be overcome with a great deal of experience with XCode (see my other post #14648 ) but I think that a command line tool, or two, with just a few more switches, and a good guide could make this a much pelasant experience even for iOS beginners.

For example, if I can manage to compile flutter without building for iOS, and then just run a Xcode command line command to compile my target, this would make compiling for my target just a click on the keyboard..

**Comment by yauri-io** [comment]
+1
I tried to rename the "Runner" then "flutter build ios" crashed

**Comment by zontarian** [comment]
Yes, this is a known bug. What I do is to leave the Runner target alone, and create another target with the name I like. Then we can manage to run everything from command line specifying the flavor (target in XCode parlance) or build via GUI in 2 steps:

1. Compile in AndroidStudio for iOS and any flavor
1. wait until it fails, or until it starts building XCode. Then stop AndroidStudio
2. Open XCode, check your `xconfig` file to use the correct `dart` file, and compile from there.

Please see a more detailed answer here https://github.com/flutter/flutter/issues/14648

**Comment by zontarian** [comment]
You can see a full report of how we managed to use Flavors/Targets/Schema here

https://www.iakta.org/progetti/flavoring_flutter/

With a bit of configuration, in works straight from Flutter!

**Comment by davidair** [comment]
It feels like using flavors with multiple targets is more powerful than multiple schemas, and the only blocker from cloning the Runner target is the fact that flutter expects the binary output to be called Runner.app.

**Comment by MoacirSchmidt** [comment]
> 
> 
> It feels like using flavors with multiple targets is more powerful than multiple schemas, and the only blocker from cloning the Runner target is the fact that flutter expects the binary output to be called Runner.app.

It is quite IMPOSSIBLE to have different Launch Screens using schemas! The only solution is  to use TARGETS!

**Comment by mono0926** [comment]
@MoacirSchmidt 

> It is quite IMPOSSIBLE to have different Launch Screens using schemas! 

It is possible to do that.

## Info.plist

```xml
<key>UILaunchStoryboardName</key>
<string>$(LAUNCH_SCREEN_NAME)</string>
```

## xcconfig file

```
LAUNCH_SCREEN_NAME=SomeScreen
```

I don't feel any limitations about that. It is necessary to understand iOS build settings especially xcconfig.

**Comment by MoacirSchmidt** [comment]
@mono0926 

Could you please tell me how can I reference that xcconfig file to a specific schema?

**Comment by BohdanNikoletti** [comment]
@eseidelGoogle, @Hixie, @lukef . I think this issue should be high priority. I have a reject after reject connected with this issue. I can't publish my app on App Store since February. Just take a look on rejected from Apple.
### First reject in February
<img width="1439" alt="Screen Shot 2019-04-30 at 10 11 56" src="https://user-images.githubusercontent.com/16256553/56947308-701e8d80-6b35-11e9-89eb-319cc83d207c.png">

### They agreed that app name is correct

<img width="942" alt="Screen Shot 2019-04-30 at 10 21 14" src="https://user-images.githubusercontent.com/16256553/56947309-701e8d80-6b35-11e9-9457-9a1b204a3848.png">

### And again I'm getting the same reject.

<img width="1417" alt="Screen Shot 2019-04-30 at 10 11 36" src="https://user-images.githubusercontent.com/16256553/56947306-701e8d80-6b35-11e9-8b14-47eacc356245.png">

🤷‍♂️

**Comment by MoacirSchmidt** [comment]
@BohdanNikoletti,

> @eseidelGoogle, @Hixie, @lukef . I think this issue should be high priority. I have a reject after reject connected with this issue. I can't publish my app on App Store since February. Just take a look on rejected from Apple.

You can change display name on "Bundle display name" key of info.plist.

**Comment by BohdanNikoletti** [comment]
@MoacirSchmidt hmm. Thanks but its already done. 
### Screen-shot of commit with date when I've changed Bundle display name
<img width="1407" alt="Screen Shot 2019-04-30 at 14 03 51" src="https://user-images.githubusercontent.com/16256553/56957751-d06ef880-6b50-11e9-8adf-dd9a288c258e.png">

### Current state of localized InfoPlist.string 

<img width="276" alt="info-plist" src="https://user-images.githubusercontent.com/16256553/56957803-f3011180-6b50-11e9-82f7-19be9b7748e1.png">

### Current state of info InfoPlist.string in ua locale

<img width="1123" alt="info-plist-content" src="https://user-images.githubusercontent.com/16256553/56957824-057b4b00-6b51-11e9-9e7b-1207a041046e.png">

### Current state of Info.plist

<img width="370" alt="project-general" src="https://user-images.githubusercontent.com/16256553/56957844-17f58480-6b51-11e9-945d-e0a64023a4b0.png">

Am I wrong? All that you see on screenshot are from first submission in February.
Also I want to ask you to pay more attention and read screen from conversation with apple. Where they are agreed that app name is write. But on next submission they told me that app name is wrong again. But I haven't made any changes to this files since first submission in February.

**Comment by MoacirSchmidt** [comment]
@BohdanNikoletti,
> You can change display name on "Bundle display name" key of info.plist.

I have never worked with localizations before in iOS, but follows some little things I know:
1) $(PRODUCT_NAME) is always replaced by "Runner" or something similar to your project name

2) What I have done to change my Bundle display name is:
- create a variable on .xcconfig file, like FLUTTER_APP_NAME=My Bundle Name
- use that variable in Info.plist: Bundle display name: $(FLUTTER_APP_NAME)
- Target -> General -> Identity -> Display Name:  $(FLUTTER_APP_NAME)

**Comment by BohdanNikoletti** [comment]
@MoacirSchmidt 
1. The weirdest thing in this rejects. That app name is actually correct. And you can see that apple agreed in this screen. 
<img width="942" alt="review" src="https://user-images.githubusercontent.com/16256553/57013667-46d52e80-6c15-11e9-9c38-2d4a935a833c.png">
But on next submission they said that I have a wrong name again. And they telling that when I haven't change anything from last submission where they said that issues is solved.
2. Also to prove you and that name is correct I have an evidence.

![ezgif com-optimize-3](https://user-images.githubusercontent.com/16256553/57044151-3c954d80-6c72-11e9-9a5a-9397305faadc.gif)

3. From all of this I've made a conclusion that only place where listed 'Runner' is project name.

**Comment by PandaGeek1024** [comment]
I came across this problem with creating a product flavor and run the command line:
flutter run --flavor production
And it reports this: 
`Could not find the built application bundle at build/ios/iphoneos/Runner.app.`

Obviously it hard coded Runner.app as the default binary to look for. If this can not be fixed, flavor is really lamb.

**Comment by MoacirSchmidt** [comment]
Flavors works well if you use "schemas" instead of "targets". Target "Runner" is hard coded but that is not a big problem.

**Comment by mars3142** [comment]
I want to use different Firebase projects for development / qa / production and now I have to write a custom build script to copy the correct GoogleService-Info.plist. That's my main issue with schemas vs. targets. Maybe we can combine both - We have to name schema and target the same - or it will be the default Runner.

**Comment by vysotsky** [comment]
Any solution for this issue? I'm having some libraries that cannot be built for simulator (which blocks me from running automation tests, for instance). So I created another target which excludes those libraries. And now I cannot run this target because it says that `Could not find the built application bundle at build/ios/iphonesimulator/Runner.app`. I understand that `Runner.app` is a sort of hardcoded thing but is there any way to avoid having issues with it? Thanks!

**Comment by vysotsky** [comment]
Ok, for anyone that's interested. It seems I resolved the issue by setting `EXCLUDED_SOURCE_FILE_NAMES` and `OTHER_SWIFT_FLAGS` for different configurations. I just moved all unneeded code and even frameworks to a directory which won't by used while compiling. 
`$(PROJECT_DIR)/Runner/FolderToExclude/*.* // all the files inside this folder shouldn't be in any subfolders. Seems to be an iOS limitation`.
To remove all references from other pieces of code I have declared a swift preprocessor variable and wrapped that code into a directive like the following:
```
#if !HAS_SIMULATOR_SUPPORT
// some code that won't be compiled when building the app for devices only 
#endif  
```
This allowed me to leave only one target called `Runner` and to have simulator support by removing all the libraries which doesn't support x86_64 without having to create lots of targets. 
I think it might be useful for others.

**Comment by gang018** [comment]
@BohdanNikoletti I hope, this will help you. https://medium.com/swift2go/different-app-display-name-based-on-xcode-scheme-d709307d0c01

**Comment by elmariocarlos** [comment]
> @BohdanNikoletti,
> 
> > You can change display name on "Bundle display name" key of info.plist.
> 
> I have never worked with localizations before in iOS, but follows some little things I know:
> 
> 1. $(PRODUCT_NAME) is always replaced by "Runner" or something similar to your project name
> 2. What I have done to change my Bundle display name is:
> 
> * create a variable on .xcconfig file, like FLUTTER_APP_NAME=My Bundle Name
> * use that variable in Info.plist: Bundle display name: $(FLUTTER_APP_NAME)
> * Target -> General -> Identity -> Display Name:  $(FLUTTER_APP_NAME)

THIS WORKS

> @BohdanNikoletti I hope, this will help you. https://medium.com/swift2go/different-app-display-name-based-on-xcode-scheme-d709307d0c01

ALSO THIS FROM STEPS 4 AND 5.

Basically both are same approach, but using a different name for variable.

This makes the change easy to implemented in the Flutter Create init structure files @Hixie @lukef

**Comment by git-xbits** [comment]
Any chance to rename Runner.xcodeproj to NAMEPROJECT.xcodeproj?

**Comment by git-xbits** [comment]
Sorry, but I facing this same problem again today. I think this problem is not for build with another flavor or schema, but Flutter team work to change the way it is created. We developers have to work with a lot of problems to archive the file (Pods not found or objectc not found). So, please, consider work in this item because every single build in XCode allways have a problem. This is another one to deal with (unnecessary one);

I love work with Flutter in Android, but in IOS is painful.

**Comment by jmagman** [comment]
This bug is tracking a few distinct rename requests:
1. Runner.xcodeproj/Runner.xcworkspace @lukef @git-xbits 
    I'm curious--what's the pain-point here?

1. Runner target @zontarian @davidair @mars3142
More details about this in https://github.com/flutter/flutter/issues/14648 than this issue.

1. Runner scheme @zontarian  @davidair @mars3142 
Pretty much the same "flavor" reasoning for targets, though people have different preferences and Flutter should support both (I always use schemes for script phases instead of aggregate targets, for example).

1. Built Runner.app and display name issues/App Store rejections @davidair @PandaGeek1024 @vysotsky @yauri-io @BohdanNikoletti @MoacirSchmidt @elmariocarlos 

I'm about to put out a PR for the last one, though I'm a bit concerned people who have hacked around this problem by hard-coding things into their Info.plist will hit migration issues when PRODUCT_NAME (and therefore FULL_PRODUCT_NAME) no longer matches CFBundleName. https://github.com/flutter/flutter/issues/41793#issuecomment-564817193

**Comment by Schoonology** [comment]
To add a little color to the conversation, the primary issue I run into here is organizing my work. I am actively working on _five_ different Flutter applications, and it has become cumbersome to differentiate between the different `Runner.app` binaries and `Runner.xcworkspace` projects.

The amount that the current tooling does to improve my workflow as a mobile developer is commendable, but being able to rename "Runner" to "AppImWorkingOnToday" would be _huge_ to restoring my ability to more easily switch contexts between projects.

**Comment by Schoonology** [comment]
@jmagman This is particularly about no. 1, and I hope it helps explain the pain point. No. 4, above, is related.

**Comment by shamilovtim** [comment]
The Runner thing is super weird. It's not a thing in Cordova or React Native why does it have to be in Flutter?

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/9767#issuecomment-564819538 oh, this is indeed pretty confusing. @jmagman, thanks for breaking it down. Can we close this issue and split them into concrete actionable issues like you listed?

**Comment by jmagman** [comment]
I think it's already broken down.

> 1. Runner.xcodeproj/Runner.xcworkspace @lukef @git-xbits
>    I'm curious--what's the pain-point here?

Let's use this issue for the Runner.xcodeproj/Runner.xcworkspace name.

> 2. Runner target @zontarian @davidair @mars3142
>    More details about this in #14648 than this issue.

Tracked in https://github.com/flutter/flutter/issues/14648.

> 3. Runner scheme @zontarian  @davidair @mars3142
>    Pretty much the same "flavor" reasoning for targets, though people have different preferences and Flutter should support both (I always use schemes for script phases instead of aggregate targets, for example).

Also tracked in https://github.com/flutter/flutter/issues/14648.

> 4. Built Runner.app and display name issues/App Store rejections @davidair @PandaGeek1024 @vysotsky @yauri-io @BohdanNikoletti @MoacirSchmidt @elmariocarlos

Tracked in https://github.com/flutter/flutter/issues/41793.

**Comment by pvegh** [comment]
"As a developer who is already forced to use Flutter, I'd like to have less pain by being able to distinguish between projects."

My pain point here is when you have more than one Flutter project and all the iOS archives on the CI and your machine are called Runner, you have no idea which is which, what you can delete as a clean up step etc.
Also I have no idea which project I have open in Xcode window (at a quick glance), because they are ALL called the same Runner.

**Comment by jmagman** [comment]
The Flutter archives on CI all called Runner will be fixed in https://github.com/flutter/flutter/issues/41793.  The Xcode window issue is this one though.

**Comment by nifrasismail** [comment]
I answered on here https://stackoverflow.com/a/60558110/2672566

**Comment by allanlavell** [comment]
+1 for prioritizing this

The beauty of flutter is its incredible iteration speed - coming from native iOS, I just want to prototype every idea I have all of a sudden. 

But then I keep getting confused when switching contexts, seeing every Xcode project as "Runner". It's hard to differentiate between projects.

That app rejection situation is also a serious issue. An app already faces enough possible sources of rejection than to add something buggy like that.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/41793#issuecomment-624894279
> This should be fixed in [1.18.0-10.0.pre](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos) or later.
> 
> You can now set your Info.plist `CFBundleName` to `$(PRODUCT_NAME)` (the default in a vanilla Xcode Project) and then set the display name in General > Identity > Display Name. The produced app bundle will be `My App.app` and any archives will be named `My App.xcarchive`.

To [recap again](https://github.com/flutter/flutter/issues/9767#issuecomment-564819538), we're using this GitHub issue to track being unable to rename Runner.xcodeproj and Runner.xcworkspace (Xcode window confusion).

Runner scheme and target name issues are tracked in https://github.com/flutter/flutter/issues/14648.

**Comment by RareScrap** [comment]
Has anyone found a way to rename the `Runner`? I replaced `Runner` with `MyCustomRunner` in all the files I found, but I still can't launch the app

**Comment by jmagman** [comment]
@RareScrap this issue is tracking being unable to rename Runner.xcodeproj and Runner.xcworkspace, which currently isn't possible.  If you are referring to something else named "Runner" please file a new issue.

**Comment by rafaelmaeuer** [comment]
Any news on this???

**Comment by cyberpwnn** [comment]
Let me open up project xyz.....

<img width="657" alt="Screenshot 2022-12-24 at 8 52 00 AM" src="https://user-images.githubusercontent.com/10619135/209438845-f134f037-efd6-4d1a-b447-cb74a1149258.png">

**Comment by Heidi0039** [comment]
This should be unacceptable... How is that still a thing?!
<img width="299" alt="Bildschirm­foto 2023-03-21 um 07 47 15" src="https://user-images.githubusercontent.com/8172336/226535473-a8c98a31-0cc6-4548-86e9-f64746a02fea.png">

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/blob/d9da7c5faadcc2e92f80a76db1f838b975f6e331/packages/flutter_tools/lib/src/xcode_project.dart#L55-L61
Instead would return the discovered workspace directory:
```dart
    for (final Directory entity in contents.whereType<Directory>()) {
      // On certain volume types, there is sometimes a stray `._Runner.xcworkspace` file.
      // Find the first non-hidden xcworkspace and return the directory.
      if (globals.fs.path.extension(entity.path) == '.xcworkspace' && !globals.fs.path.basename(entity.path).startsWith('.')) {
        return entity;
      }
    }
```
And do something similar for the `xcodeProject` where it finds the `xcodeproj` extension, regardless of name.  It may be performant to check if the hard-coded version exists before walking the directory.
https://github.com/flutter/flutter/blob/d9da7c5faadcc2e92f80a76db1f838b975f6e331/packages/flutter_tools/lib/src/xcode_project.dart#L35

There may be more spots `Runner.xcodeproj` and `Runner.xcworkspace` are hardcoded.  Tests need to be updated and added.  This should also be validated for macOS projects.

**Comment by LouiseHsu** [comment]
To rename a project:
1. Open Runner.xcodeproj in Xcode
2. In the left panel, left click "Show File Inspector" 
<img width="441" alt="Screenshot 2023-04-17 at 11 41 07 PM" src="https://user-images.githubusercontent.com/36148254/232692957-8743742d-c3ef-42e5-833f-dff31aeb2b6a.png">
3. In the right panel, the name of the project, "Runner", should be visible under "Identity and Type". Change the name and press enter.
<img width="299" alt="Screenshot 2023-04-17 at 11 40 43 PM" src="https://user-images.githubusercontent.com/36148254/232693315-b6a71165-f5e3-4a0f-8954-2f3eee5b67cf.png">
4. A wizard should pop up. Click Rename.
<img width="573" alt="Screenshot 2023-04-17 at 11 44 01 PM" src="https://user-images.githubusercontent.com/36148254/232693381-bb9cf026-2a75-4844-b42d-ae0036ae9fdd.png">
To rename the workspace:

1. Make sure Xcode is closed.
2. Rename the .xcworkspace to your new name.

If you also renamed the project

&nbsp; 3. Reopen the .xcworkspace in Xcode. If the selected project is the old name and in red, update it to match the new project name.
