### ISSUE TITLE
Please release an official encryption library

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#97783]
such as [this](https://pub.flutter-io.cn/packages/encrypt)

**Comment by darshankawar** [comment]
@2372281891 
Your issue doesn't say what current limitation you are facing and what are you proposing exactly.
The community plugins are implemented because not each and every functionality / feature can be implemented in the framework. If you are facing any issue with the library, open the issue in dedicated repo. 
Also, there are various plugins on `pub.dev` related to encryption you can check.

I am going ahead and closing this as issue isn't complete. If you disagree, use applicable new issue template and fill out requested details in it so that we can properly address the issue.
