### ISSUE TITLE
[Semantics] Add support for setting the heading level

### ISSUE THREAD

**Issue by vsomayaji** [flutter/flutter#97894]
## Use case

Using [`SemanticsProperties.header`](https://api.flutter.dev/flutter/semantics/SemanticsProperties/header.html), we can configure an element with the [`heading`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role) role. However, because there isn't a way to set the level of the heading, all headings on the page default to level 2.

## Proposal

Allow setting the heading level through something like `SemanticsProperties.headerLevel`. This could map to [`aria-level`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level) on web and [`AccessibilityHeadingLevel`](https://developer.apple.com/documentation/swiftui/accessibilityheadinglevel) on iOS. I'm not sure if there's an equivalent on Android.

**Comment by goderbauer** [comment]
Is that information used for anything by a11y tools?

For iOS looks like this was recently added in iOS 15.

**Comment by ryan-bishop** [comment]
@goderbauer  yes, headings especially when it relates to web, are used for navigation. Screen reader users can either press 1 through 6 to navigate to various heading levels, or use the H key to jump between all headings on a page. You  can find more information in WCAG guideline 2.4.6 (Headings and labels)
https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html

**Comment by fideldonson** [comment]
aria-level is a required attribute of the heading role and as such heading is not valid if aria-level is not present.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level

**Comment by localpcguy** [comment]
The [PR that says it fixes this issue]( https://github.com/flutter/engine/pull/41435 ) is explicitly only for Web Semantics, and does not appear to address setting the iOS [AccessibilityHeadingLevel](https://developer.apple.com/documentation/swiftui/accessibilityheadinglevel) property at all. I didn't see mention of that in the PR comments, but I hesitate to comment there as it's already merged. 

Did I miss it or was it handled elsewhere? If not, is this something we can make sure is also addressed either before this issue is considered closed or by making sure there is an issue specific to the iOS AccessibilityHeadingLevel so it is set properly?
