### ISSUE TITLE
Add `scrollBehaviour` to `ListView` and `BoxScrollView`

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#98003]
[`ScrollView.scrollBehavior`](https://github.com/flutter/flutter/blob/e8393757c72cb561b71a65fb3b6d30ee1600c01d/packages/flutter/lib/src/widgets/scroll_view.dart#L223) cannot be provided to `ListView` and `BoxScrollView`, which disables users to customize it.

**Comment by goderbauer** [comment]
Looks like we forgot to expose it in the constructor.

/cc @Piinks

**Comment by Piinks** [comment]
I think this was intentional. We only exposed scroll behavior in widgets where there is hard-coded behavior due to scrollbars and overscroll indicators, or widget-specific ScrollPhysics.

> which disables users to customize it.

ScrollBehavior is inherited, so you can place it anywhere in the tree, or affect it on the app level using the scrollBehavior property of the *App widgets.


I am concerned enumerating it on all scrolling widgets would cause undue complexity

**Comment by werainkhatri** [comment]
makes sense. maybe this can be documented somewhere? (most probably it already is and i missed it 😅)

**Comment by Piinks** [comment]
More documentation is always better! @werainkhatri where were you looking for docs on this? Usually wherever you instinctively looked and it was missing, is right where it should be. :)

**Comment by werainkhatri** [comment]
instinctively, it should be present in the documentation of `ListView` (and `BoxScrollView`) itself.
