### ISSUE TITLE
Linux tool_integration_tests_4_4  flakes on `cache_test`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98141]
(part of https://github.com/flutter/flutter/issues/97036)

Hit one flake today (02/09/2022):
- [ ] [cache_test.dart](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/3252/overview)
```
02:05 +20 ~20 -1: test/integration.shard/cache_test.dart: Cache.lock should log a message to stderr when lock is not acquired [E]                                                                      
  Expected: 'Waiting for another flutter command to release the startup lock...\n'
              ''
    Actual: ''
     Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: Waiting fo ...
  
  package:test_api                             expect
  test/integration.shard/cache_test.dart 78:7  main.<fn>.<fn>
  
  ```

**Comment by gspencergoog** [comment]
I'm assuming this is happening because it took longer than 500ms to lock the file, which is pretty long for a Unix machine.

The docs for `Process` say: 
```
Returns a Future<Process> that completes with a Process instance when the process has been successfully
started.
```

So, either the docs are wrong, or it's taking longer than 500ms to lock a file, or I'm wrong about why the race is happening.

Both the child script and the parent have timed delays and the child delay is twice as long as the parent delay, so as long as the child is launched and locks the file within the parent's 500ms file locking delay, this shouldn't incorrectly fail.

I don't see a good way to test this other than with an external process that locks the same file: it's not possible to hold separate locks to the same file within the same process.

I suppose I could write a tight loop that checks the locking status of the file, and only tries to lock the cache once it's locked.  I'll pursue that.

**Comment by zanderso** [comment]
You can always expect VMs/bots to introduce delays of arbitrary duration at the worst possible time...

**Comment by keyonghan** [comment]
Another flake: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/3450/overview

**Comment by zanderso** [comment]
Marking P1 to match the priority of other flakes. Though if this one is only happening once every two weeks, that is probably below the 2% threshold. Maybe @keyonghan can supply that data.

**Comment by keyonghan** [comment]
> Marking P1 to match the priority of other flakes. Though if this one is only happening once every two weeks, that is probably below the 2% threshold. Maybe @keyonghan can supply that data.

We hit the above flake (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/3450/overview) since the bug was filed (02/09), namely 1 over the past 200 commits.

**Comment by zanderso** [comment]
Since this is below the 2% threshold, I'll drop this back down to P3.
