### ISSUE TITLE
error: The operator '[]' isn't defined for the type 'Object'. of flutter

### ISSUE THREAD

**Issue by youyou-him** [flutter/flutter#98167]
[](https://stackoverflow.com/posts/71059171/timeline)0

I'm going to update the data related to Comant in the post documentary, and if there are too many Comant, I'm going to implement writing down how many Comant there are, but there is an error.

`int numOfComments = postSnapshot.data[KEY_NUMOFCOMMENTS];
         tx.update(postRef, {
           KEY_NUMOFCOMMENTS: numOfComments+1,
           KEY_LASTCOMMENT: commentData[KEY_LASTCOMMENT],
           KEY_LASTCOMMENTTIME: commentData[KEY_COMMENTTIME],
           KEY_LASTCOMMENTOR: commentData[KEY_USERKEY],`

I wrote it like this, but there's an error. I looked it up, and I was told to write () next to the data, but there's an error.

There's an error like this. 

`error: The operator '[]' isn't defined for the type 'Object'. (undefined_operator at [instagram] lib/repo/comment_network_repository.dart:21)[enter image description here](https://i.stack.imgur.com/zz13R.png)`
Is there a problem with KEY_NUMOFCOMENTS?

`const KEY_NUMOFCOMMENTS='num_of_last_comments';`

**Comment by darshankawar** [comment]
@youyou-him 
Its not clear as what exactly are you trying to implement, using which flutter feature / widget or plugin and what exactly is the error you are getting.
Please use the new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we will have proper understanding of the issue you are facing.
Closing this for now, as looking at the description, it's not clear to me as what issue are you facing. There are not enough details.
