### ISSUE TITLE
Running flutter on a non-login non-interactive shell gives "0.0.0-unknown" version

### ISSUE THREAD

**Issue by henriquelalves** [flutter/flutter#98231]
I'm currently trying to automate some steps on building and deploying a local application of flutter, but I can't get it to work on the following setup:

-> Local project pushes to remote repository (origin).
-> origin launches a post-receive hook that triggers application makefile
-> Application makefile deploys flutter

The post-receive hook is already sourcing "/etc/profile" and "~/.bashrc", and it is using the same flutter binary as if I connected to origin with SSH on an interactive shell (I could confirm this with `which flutter` on both interactive and non-interactive cases). The only thing I suspect is some misconfigured environment variable, but I'm stuck figuring out why this would happen when I'm using the exact same binary as the interactive shell case.

EDIT: Flutter doctor on the non-interactive shell gives the following result:

```
remote: fatal: not a git repository: '.'
remote: Doctor summary (to see all details, run flutter doctor -v):
remote: Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
remote: Standard out: 
remote: Standard error: fatal: not a git repository: '.'
remote: 
remote: Returning 1969-12-31 21:00:00.000 instead.
remote: [✓] Flutter (Channel unknown, 0.0.0-unknown, on EndeavourOS 5.16.3-arch1-1, locale en_US.UTF-8)
remote: [✗] Android toolchain - develop for Android devices
remote:     ✗ Unable to locate Android SDK.
remote:       Install Android Studio from: https://developer.android.com/studio/index.html
remote:       On first launch it will assist you in installing the Android SDK components.
remote:       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
remote:       If the Android SDK has been installed to a custom location, please use
remote:       `flutter config --android-sdk` to update to that location.
remote: 
remote: [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
remote:     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
remote: [!] Android Studio (not installed)
remote: [!] Connected device
remote:     ! No devices available
remote: [✓] HTTP Host Availability
remote: 
remote: ! Doctor found issues in 4 categories.
```

No Android Toolchain and Chrome is absolutely fine because I'm only deploying it as `-d web-server`, but I'm not sure why it's giving me `remote: Standard error: fatal: not a git repository: '.'`.

**Comment by darshankawar** [comment]
Although I am not much aware about non-login non-interactive shell you mentioned, but looking at the flutter doctor log:

`remote: fatal: not a git repository: '.'
remote: Doctor summary (to see all details, run flutter doctor -v):
remote: Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
remote: Standard out: 
remote: Standard error: fatal: not a git repository: '.'`

It seems to indicate that the non-interactive shell is unable to find the flutter sdk and hence the error. Maybe try to see if there's any config or PATH you are missing because it can't detect the path from where you are running the command as a git repo.  Try to do a `git init` or see if there's any misconfiguration while local project you are pushing to remote repo.

**Comment by darshankawar** [comment]
@henriquelalves 
Thanks for the update. I can't tell for sure as which environment variable might have been misconfigured, but I suggest you to open / ask this issue in support channels like StackOverflow so that you can get solution or more info on this use case. I'll close this issue for now from here. If you disagree and think that this is a bug in the framework itself, write in comments and I'll reopen it.
