### ISSUE TITLE
flutter support arm architecture arm64 arm32 

### ISSUE THREAD

**Issue by ExtinctDrift19** [flutter/flutter#98518]

**Comment by ExtinctDrift19** [comment]
I can port flutter it to termux android phone tablet

**Comment by ExtinctDrift19** [comment]
it will be possible to develop on an android phone and a tablet flutter

**Comment by darshankawar** [comment]
@ExtinctDrift19 
Not sure if I fully understand the proposal because you didn't provide enough details. Currently Flutter supports `[armeabi-v7a](https://developer.android.com/ndk/guides/abis#v7a) (ARM 32-bit), [arm64-v8a](https://developer.android.com/ndk/guides/abis#arm64-v8a) (ARM 64-bit), and [x86-64](https://developer.android.com/ndk/guides/abis#86-64)[](https://docs.flutter.dev/deployment/android#test-the-app-bundle) (x86 64-bit)`.

So what exactly is your proposal here ? Are you looking to have arm support for specific Android phone and tablet ?
Please elaborate.

**Comment by ExtinctDrift19** [comment]
add installation instructions for termux site flutter.dev

**Comment by darshankawar** [comment]
If I understand correctly, you are looking to have Flutter installation steps for termux.com. If so, you'll need to report this issue in flutter/website repo: https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Install%27&page-url=https://docs.flutter.dev/get-started/install/&page-source=https://github.com/flutter/website/tree/main/src/get-started/install/index.md

Closing from here. If you disagree or think this is incorrect, write in comments and I'll reopen it.
