### ISSUE TITLE
Make DraggableScrollableController a listenable again

### ISSUE THREAD

**Issue by kamami** [flutter/flutter#98598]
## Use case

Use `DraggableScrollableController` as a `listenable` in `AnimatedBuilder`.

## Proposal

It already has been a `listenable` on channel `master`, but after the merge to `stable` it is not anymore.

**Comment by maheshmnj** [comment]
Hi @kamami, Thanks for filing the issue. I can see that `DraggableScrollableController` is listenable on master and beta channel but not on stable. I would recommend to please wait until it lands on stable in the future release, Since this is available on beta which will be the future stable channel. 

### master
https://github.com/flutter/flutter/blob/525c62071821738356e54ecae6ef06afa7e3c403/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L54

### beta
https://github.com/flutter/flutter/blob/b101bfe32f634566e7cb2791a9efe19cf8828b15/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L54

### stable
https://github.com/flutter/flutter/blob/db747aa1331bd95bc9b3874c842261ca2d302cd5/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L47

Closing as we wouldn't need an issue to keep track when a feature lands on stable unless something is very critical.
