### ISSUE TITLE
[Proposal] Spacer Widget should extends from Flexible

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#98787]
Now in Flutter framework ，Spacer is extends StatelessWidget , and use Expanded Widget when build. Is unnecessary. just like Expanded Widget, extends Flexible is fine.   

now, `spacer.dart` file in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/spacer.dart

<img width="639" alt="image" src="https://user-images.githubusercontent.com/26687012/154791128-04c76696-1828-4d48-a5ee-a5c02d536235.png">

**Comment by maheshmnj** [comment]
Hi @toly1994328, Thanks for filing the issue. labeling this issue as a valid proposal to make spacer extend from Flexible 

https://github.com/flutter/flutter/blob/54a9d652828941dbebbe8de32cf667e89578b13d/packages/flutter/lib/src/widgets/spacer.dart#L41

Since Expanded extends from Flexible 

https://github.com/flutter/flutter/blob/54a9d652828941dbebbe8de32cf667e89578b13d/packages/flutter/lib/src/widgets/basic.dart#L5057-L5066

**Comment by luhenchang** [comment]
@toly1994328  特烈牛皮。真牛

**Comment by goderbauer** [comment]
We do prefer composition over inheritance in the framework. So the current implementation is fine.
