### ISSUE TITLE
How Flutter framework optimize the app if build method can be called many times?

### ISSUE THREAD

**Issue by gorkemunuvar** [flutter/flutter#98799]
I have a simple question. In Flutter docs it is explained `build` method can be called many times by framework and it is recomended that we should only return widgets through the `build` method. But even we return only widgets, isn't it causing some performance issues? If `build` method is called 20 times in a second, does not it mean widgets will be rendered 20 times? If Flutter framework optimizes it, how?

Can you please reference some detailed docs or answers for that?

**Comment by xeinebiu** [comment]
The build method is called every time the state of your application changes.

Assuming you have a `boolean` flag on your `StatefulWidget`. The `build` will be called only when you use `setState`. This will trigger the build of all children Widgets also (excluding const widgets).

I am also learning Flutter, so far this is what I know.

**Comment by darshankawar** [comment]
@gorkemunuvar 
Please check below documents on Flutter's app optimization and best practices involving `build` method rendering:

https://docs.flutter.dev/perf/rendering
https://docs.flutter.dev/perf/rendering/best-practices#controlling-build-cost
https://docs.flutter.dev/perf/rendering/best-practices#resources

The last link also has further resources for your reference on app optimization.

With this, I am going ahead and closing this, as this is more of a `how to` question rather than a bug or feature requests for which this repo is for. For any further questions, you can see [Flutter community support channels](https://flutter.dev/community) and ask your questions there. Flutter's discord is a great support channel for such questions.
