### ISSUE TITLE
Private vimeo video is not working in Flutter Application

### ISSUE THREAD

**Issue by Mr-MahendraGurjar** [flutter/flutter#98801]
Hi Vimeo Team,
I'm Unable to Load Private Vimeo video in my Flutter Application, Please help me for same, or please provide me support also

Thanks.

 <iframe 
                src="https://player.vimeo.com/video/$videoId?loop=0&autoplay=0" 
                width="100%" height="100%" frameborder="0" allow="fullscreen" 
                class="embed-responsive-item"
                referrerpolicy="strict-origin"
                allowfullscreen></iframe>

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Mr-MahendraGurjar 
Since you seem to be using `iFrame` and trying to allow full screen, I am assuming you are using webview for it, if so, there's similar open issue currently describing same case, https://github.com/flutter/flutter/issues/27101
Please follow-up in it for further updates.
Closing this as a duplicate.
