### ISSUE TITLE
Map Controller -Ve Zoom button can make device restart (Bug)

### ISSUE THREAD

**Issue by Manishmg3994** [flutter/flutter#98920]
Map Controller -Ve Zoom button can make device restart (Bug)
As during loading of map if you press/click zoom out button rapidly ,you will find the biggest  issue

**Comment by darshankawar** [comment]
@Manishmg3994 
When you open an issue, please provide all requested details mentioned in the new issue template so that we'll have enough details to work with. Currently you didn't provide any such details so we won't know what exactly is the issue you are reporting.

Please provide `flutter doctor -v`, [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins and exact steps to replicate the behavior you are reporting.
