### ISSUE TITLE
[dashboard] go/cocoon-build shows two "open log for build tab"

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#98939]
![Screen Shot 2022-02-22 at 10 46 52 AM](https://user-images.githubusercontent.com/38773539/155200839-67a3e507-49ed-434d-bb1c-18cb22d36144.png)
Just a minor issue of two open logs tabs. By the way this is only happening at go/cocoon-build (I guess it's an internal dashboard?) and not at https://flutter-dashboard.appspot.com/#/build.

**Comment by CaseyHillers** [comment]
The reason this occurs on the cocoon build dashboard and not the framework or engines is because we're in the middle of migrating the infra. We're rewriting the scheduler and results processing to be done by Cocoon instead of LUCI, so we're working the issues on the smaller repos before switching everything over.

**Comment by XilaiZhang** [comment]
cool, shall we close this issue? (sorry just got back from a very late lunch)
