### ISSUE TITLE
Image Picker plugin images are rotated 90 degrees on iOS when picking portrait selfies from media gallery

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9894]
## Steps to Reproduce

Run the image_picker plugin's example app. Choose a selfie taken with the device's camera. It comes out rotated 90 degrees.

Note that the simulator gallery's photos don't exhibit this problem. We probably need to get the rotation data off the image and use it.

**Comment by goderbauer** [comment]
The problem is that we currently throw away all EXIF data on iOS. With that, the orientation property is also lost. I'll send out a quick fix that at least sends the image data over to the dart-side in the correct orientation.

Having said that, at a later point in time we probably want to investigate how we can keep the EXIF data. Those also contain gps information and other camera information that might be useful for applcaitions.

**Comment by acidjazz** [comment]
@goderbauer @collinjackson I don't understand why this issue is closed? it's a pretty severe bug.

**Comment by zoechi** [comment]
There is already #19458

**Comment by acidjazz** [comment]
yes @goderbauer it's #19458 ,  thanks @zoechi it seems as if this is the same issue maybe though?, you may be showing the right orientation w/in the flutter app by passing the exif through, but the image actually stored isn't rotated and/or has its exif data stripped maybe?
