### ISSUE TITLE
Events through in iOS

### ISSUE THREAD

**Issue by yinjinshi** [flutter/flutter#99058]
My  current version of Flutter is 2.10.2, I jumped to an iOS page in the Flutter project. Clicking on the area of the iOS page that did not respond to the event would be responded by the Flutter framework. This made me confused. Found I was met with a similar problem before (#https://github.com/flutter/flutter/issues/35784), flutter officials so far have not fix this problem, the following is my repetition steps。
<img width="1414" alt="1" src="https://user-images.githubusercontent.com/15263021/155504339-b956266d-93bb-48cd-8f1e-a8701c03629e.png">
<img width="1421" alt="2" src="https://user-images.githubusercontent.com/15263021/155504365-c6d099ed-063f-4968-b367-5a0f0fcfd812.png">

**Comment by maheshmnj** [comment]
Hi @yinjinshi, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the steps to reproduce the issue. The other issue that you linked got closed because it was not actionable in its current state due to [lack of information.](https://github.com/flutter/flutter/issues/35784#issuecomment-509758607)
