### ISSUE TITLE
GPU utilization regression

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99250]
SkiaPerf is reporting a ~2x regression in GPU utilization on iOS on the Engine roll here https://github.com/flutter/flutter/pull/98940

https://flutter-flutter-perf.skia.org/e/?begin=1645459452&end=1645601952&keys=X75d7cc60f01618d7aa594587dbe82c4c&num_commits=50&request_type=1&xbaroffset=27665

That Engine roll contains mainly Dart and Skia rolls, so I'm guessing the cause is in one of the Skia rolls, but this will likely need a bisect since there are so many.

**Comment by chinmaygarde** [comment]
This should be fixed by https://github.com/flutter/engine/pull/31710 which is a revert of a commit that was expected to regress on this metric. But we have since decided that the regression is too severe.

Holding on closing this so we can revisit this next week to ensure that the regression has been addressed.

**Comment by zanderso** [comment]
The benchmark recovered.
