### ISSUE TITLE
[Stable 2.10.2] build fails for iOS after upgrade from 2.8

### ISSUE THREAD

**Issue by chrisvidal** [flutter/flutter#99317]
after upgrading from 1flutter 2.81 to 1flutter 2.10.1` Error Log with flutter 2.10.2 built for iPhone11 with iOS 15.2. Simulator 

```
Launching lib[/main.dart]() on iPhone 11 in debug mode...
lib/main.dart:1
Xcode build done.                                           20.0s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[49192]: Class AMSupportURLConnectionDelegate is implemented in both [/usr/lib/libamsupport.dylib]() (0x1f8edf130) and [/Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice]() (0x1047282c8). One of the two will be used. Which one is undefined.
    objc[49192]: Class AMSupportURLSession is implemented in both [/usr/lib/libamsupport.dylib]() (0x1f8edf180) and [/Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice]() (0x104728318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	[/var/folders/vr/81pvs8w52m55zkrjqhrbtwhc0000gn/T/flutter_tools.XZySVJ/flutter_ios_build_temp_dirOCouBV/temporary_xcresult_bundle]()
: Error: A value of type 'Color?' can't be assigned to a variable of type 'Color' because 'Color?' is nullable and 'Color' isn't.
../…/src/chip_theme.dart:61
     - 'Color' is from 'dart:ui'.
        final Color primaryColor = color ??
                                         ^
: Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
../…/src/chip_theme.dart:85
- 'TextStyle' is from 'package:flutter[/src/painting/text_style.dart]()' ('.[./../../../Development/flutter/packages/flutter/lib/src/painting/text_style.dart]()').
package:flutter/…/painting/text_style.dart:1
        final TextStyle defaultLabelStyle = ChipTheme.of(context).labelStyle;
                                                                  ^
    Failed to package [/Users/christophevidal/Mobiles/NUS/hope2/nus_hope.]()
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    [/Users/christophevidal/Mobiles/NUS/hope2/nus_hope/ios/Pods/Pods.xcodeproj](): warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')
    Result bundle written to path:
    	[/var/folders/vr/81pvs8w52m55zkrjqhrbtwhc0000gn/T/flutter_tools.XZySVJ/flutter_ios_build_temp_dirOCouBV/temporary_xcresult_bundle]()
Could not build the application for the simulator.
```

`Pubspec.yaml`

```yaml

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Our NUS HOPE UI
  hope_ui:
    path: ../hope_ui

  #stacked State architecture
  stacked: ^2.2.8
  stacked_services: ^0.8.17

  flutter_lints: ^1.0.4

  # data models
  freezed_annotation: ^1.1.0
  json_annotation: ^4.0.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2

  #health
  health: 3.4.3

  #utils
  confetti: ^0.6.0
  keyboard_actions: ^3.4.7
  settings_ui: ^2.0.2
  uuid: ^3.0.5
  recase: ^4.0.0
  flutter_slidable: ^1.0.0
  flutter_awesome_select: ^6.0.0
  flutter_staggered_grid_view: ^0.6.1
  animated_check: ^1.0.5

  #connection
  http: ^0.13.3

  # charts
  syncfusion_flutter_charts: ^19.3.48

  # calendar
  syncfusion_flutter_calendar: ^19.3.48

  # rendering
  flutter_markdown: ^0.6.8
  flutter_html: ^2.2.1


  # images related
  path_provider: ^2.0.7
  path: ^1.8.0
  image_picker: ^0.8.4+4
  swipe_cards: ^1.0.0

  animations:
  intl: ^0.17.0
  dart_date: ^1.1.0
  collection: ^1.15.0
  supercharged: ^2.1.1
  grouped_list: ^4.1.0
  cached_network_image: ^3.0.0
  logger:

  flutter_hooks: ^0.18.0
  lpinyin: ^2.0.3
  azlistview: ^2.0.0-nullsafety.0
  date_picker_timeline: ^1.2.3
  sorted_list: ^1.0.0
  timeline_tile:
    git:
      url: https://github.com/JHBitencourt/timeline_tile.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^3.3.1
  build_runner: ^2.1.4
  stacked_generator: ^0.5.7
  # data models
  freezed: ^1.1.1
  json_serializable: ^6.0.1
```

**Comment by EArminjon** [comment]
Share your profile please :).
And maybe fix this error : A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
../…/src/chip_theme.dart:85

**Comment by danagbemava-nc** [comment]
Hi @chrisvidal, please provide the full log of `flutter run -v`. The output may be huge so please put it into a .txt file and attach it here. 
You may also want to check if any of your dependencies are out of date and update them. 

You can do so by using `flutter pub outdated`.

**Comment by chrisvidal** [comment]
> Share your profile please :). And maybe fix this error : A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't. ../…/src/chip_theme.dart:85

apparently it is coming from a flutter package, cant be edited manually I suppose

**Comment by chrisvidal** [comment]
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-arm, locale en-SG)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

```
flutter run -v
```
couldn't grab the beginning of the log...

[flutter_v_2.10.2.pdf](https://github.com/flutter/flutter/files/8160668/flutter_v_2.10.2.pdf)

and now, I just noticed that the `build_runner` is not working anymore under flutter 2.10.2

**Comment by chrisvidal** [comment]
```
 flutter pub run build_runner build --delete-conflicting-outputs
Could not find package "build_runner". Did you forget to add a dependency?
pub finished with exit code 65
christophevidal@MacBook-Pro-3 hope2 % 
christophevidal@MacBook-Pro-3 hope2 % 
christophevidal@MacBook-Pro-3 hope2 % 
christophevidal@MacBook-Pro-3 hope2 % flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current  Upgradable  Resolvable  Latest  

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies: 
material_color_utilities  *0.1.3   *0.1.3      *0.1.3      0.1.4   
vector_math               *2.1.1   *2.1.1      *2.1.1      2.1.2   

transitive dev_dependencies:
path                      *1.8.0   *1.8.0      *1.8.0      1.8.1   
source_span               *1.8.1   *1.8.1      *1.8.1      1.8.2   
test_api                  *0.4.8   *0.4.8      *0.4.8      0.4.9   
all dependencies are up-to-date.
```

**Comment by chrisvidal** [comment]
ok, I found the culprit, thanks @danagbemava-nc and @EArminjon 

```yaml
flutter_awesome_select: ^6.1.2-beta
```

**Comment by lhphanto** [comment]
Hi All,

May I know more specifically how you solved the problem? I think I got similar error when I try to build my apk
`flutter build apk -t lib/main-edge-prod.dart --flavor edgeProd --target-platform android-arm,android-arm64 --release`

`Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.
../../../../flutter/.pub-cache/git/flutter_smart_select-5bdaaf216fe32d6c8f51506a6158801b969d9e0b/lib/src/chip_theme.dart:61:38: Error: A value of type 'Color?' can't be assigned to a variable of type 'Color' because 'Color?' is nullable and 'Color' isn't.
 - 'Color' is from 'dart:ui'.
    final Color primaryColor = color ??
                                     ^
../../../../flutter/.pub-cache/git/flutter_smart_select-5bdaaf216fe32d6c8f51506a6158801b969d9e0b/lib/src/chip_theme.dart:85:63: Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
 - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('../../../../flutter/packages/flutter/lib/src/painting/text_style.dart').
    final TextStyle defaultLabelStyle = ChipTheme.of(context).labelStyle;
                                                              ^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:94:37](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:94:37): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.amberAccent.shade50;
                                    ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:126:36](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:126:36): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.blueAccent.shade50;
                                   ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:198:36](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:198:36): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.cyanAccent.shade50;
                                   ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:230:42](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:230:42): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.deepOrangeAccent.shade50;
                                         ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:262:42](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:262:42): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.deepPurpleAccent.shade50;
                                         ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:294:37](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:294:37): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.greenAccent.shade50;
                                    ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:346:38](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:346:38): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.indigoAccent.shade50;
                                     ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:378:41](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:378:41): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.lightBlueAccent.shade50;
                                        ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:410:42](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:410:42): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.lightGreenAccent.shade50;
                                         ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:442:36](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:442:36): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.limeAccent.shade50;
                                   ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:474:38](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:474:38): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.orangeAccent.shade50;
                                     ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:506:36](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:506:36): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.pinkAccent.shade50;
                                   ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:538:38](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:538:38): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.purpleAccent.shade50;
                                     ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:570:35](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:570:35): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.redAccent.shade50;
                                  ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:602:36](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:602:36): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.tealAccent.shade50;
                                   ^^^^^^^
../../../../flutter/.pub-cache/hosted/[pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:634:38](http://pub.dartlang.org/flutter_treeview-1.0.6+1/lib/src/utilities.dart:634:38): Error: The getter 'shade50' isn't defined for the class 'MaterialAccentColor'.
 - 'MaterialAccentColor' is from 'package:flutter/src/material/colors.dart' ('../../../../flutter/packages/flutter/lib/src/material/colors.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shade50'.
          return Colors.yellowAccent.shade50;
                                     ^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/google/home/huiliukeith/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildEdgeProdRelease'.
> Process 'command '/usr/local/google/home/huiliukeith/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 2m 12s
Running Gradle task 'assembleEdgeProdRelease'...                  133.1s
Gradle task assembleEdgeProdRelease failed with exit code 1`


I installed linux 2.10.3 and with Dart 2.16.1

Thanks!

**Comment by lhphanto** [comment]
Ok, 

I see there is a coming fix for flutter_awesome_select.dart
https://github.com/artflutter/flutter_awesome_select/commit/4be93c4a845b1023166e9f1bd79107b07f9865e3

but wondering when it would become available so that I could refer it in my pubspec.yaml

**Comment by danagbemava-nc** [comment]
Hi @lhphanto, you'll need to contact the authors of the package for that information
