### ISSUE TITLE
[iOS][add2app] can't compile the project with [google_maps_flutter] dependency 

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#99392]
Logs: 

[Build target ADAC iOS_2022-03-02T12-52-26.txt](https://github.com/flutter/flutter/files/8169346/Build.target.ADAC.iOS_2022-03-02T12-52-26.txt)
 
Reproduction steps: 
1. Add latest (2.1.2) Google maps dependency to Flutter project
2. Follow method B from https://docs.flutter.dev/development/add-to-app/ios/project-setup
3. Run project from Xcode  

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.633, on macOS 12.0.1 21A559
    darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
    ! Device 52007e785ffc85c7 is not authorized.
      You might need to check your device for an authorization dialog.
[✓] HTTP Host Availability

• No issues found!
```

**Comment by darshankawar** [comment]
From the Xcode log: its failing with:

```
Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_GMSTileLayer", referenced from:
      _OBJC_METACLASS_$_FLTTileProviderController in google_maps_flutter(FLTGoogleMapTileOverlayController.o)
  "_OBJC_CLASS_$_GMSPolyline", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapPolylineController.o)
  "_kGMSTileLayerNoTile", referenced from:
      ___61-[FLTTileProviderController requestTileForX:y:zoom:receiver:]_block_invoke in google_maps_flutter(FLTGoogleMapTileOverlayController.o)
  "_OBJC_CLASS_$_GMSCameraPosition", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapController.o)
  "_OBJC_CLASS_$_GMSMutablePath", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapPolygonController.o)
      objc-class-ref in google_maps_flutter(GoogleMapPolylineController.o)
  "_OBJC_CLASS_$_GMSPolygon", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapPolygonController.o)
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapMarkerController.o)
  "_OBJC_CLASS_$_GMSTileLayer", referenced from:
      _OBJC_CLASS_$_FLTTileProviderController in google_maps_flutter(FLTGoogleMapTileOverlayController.o)
  "_OBJC_CLASS_$_GMSCameraUpdate", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapController.o)
  "_OBJC_CLASS_$_GMSCircle", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapCircleController.o)
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapController.o)
  "_OBJC_CLASS_$_GMSMapView", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapController.o)
  "_kGMSMinZoomLevel", referenced from:
      _InterpretMapOptions in google_maps_flutter(GoogleMapController.o)
  "_OBJC_CLASS_$_GMSMapStyle", referenced from:
      objc-class-ref in google_maps_flutter(GoogleMapController.o)
  "_kGMSMaxZoomLevel", referenced from:
      _InterpretMapOptions in google_maps_flutter(GoogleMapController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In latest plugin version's podspec https://github.com/flutter/plugins/blob/google_maps_flutter-v2.1.2/packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec 

```
s.dependency 'Flutter'
s.dependency 'GoogleMaps'
s.static_framework = true
s.platform = :ios, '9.0'
```

specially, `s.dependency 'GoogleMaps'` indicating it doesn't point to a specific pod version which seems to be fine also `s.static_framework = true` is true by default which was added as part of this PR https://github.com/flutter/flutter/pull/40401/files that had fixed the then issue, but here using latest stable and plugin version, the issue seems to have come back. Here's another old but similar issue reported https://github.com/flutter/flutter/issues/59683 which was [solved](https://github.com/flutter/flutter/issues/59683#issuecomment-692395249) after adding `pod 'GoogleMaps', '< 3.10'` but that seemed to be a workaround.

Another note:

The latest cocoapod [specs](https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/d/GoogleMaps/6.0.1/GoogleMaps.podspec.json) for the plugin (6.0.1) has:

```
"platforms": {
    "ios": "12.0"
  },
```

But the plugin's latest podspec has it: `s.platform = :ios, '9.0'`.  Could this be the reason for this error ?

/cc @jmagman for further insights.

I'll try to replicate this a bit later, since I upgraded macOS and now it needs latest Xcode version which I'll install.

**Comment by stuartmorgan** [comment]
What version of `GoogleMaps` do you have in your `Podfile.lock`?

**Comment by ljmatan** [comment]
@stuartmorgan sorry, we've switched to Mapbox due to time constraints and I can't test this further. 

@jmagman these are logs from running for the actual / physical device.

**Comment by stuartmorgan** [comment]
> @stuartmorgan sorry, we've switched to Mapbox due to time constraints and I can't test this further.

Without knowing what version of the underlying SDK you were using, or any way of getting more information about what your setup was, we can't make any progress; given that, closing.

Feel free to file a new issue if you revisit using this plugin and can provide us enough information to allow investigating.
