### ISSUE TITLE
AndroidManifest.xml not resolving android:icon and android:roundIcon

### ISSUE THREAD

**Issue by tombirmingham** [flutter/flutter#9944]
## Steps to Reproduce

Created a new Flutter project using master and it doesn't resolve these icons.

  <application android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"

With the Flutter alpha release this worked.  It is not finding the res/mipmap folders with these icons.

## Logs

-flutter analyze found no errors.

## Flutter Doctor

C:\Users\Tom\AndroidStudioProjects\MMusicRecorder>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at C:\Users\Tom\GitHub\flutter
    • Framework revision 9cb12086bb (4 hours ago), 2017-05-09 14:03:16 -0700
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.4)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Connected devices
    • None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
This seems like a question of how the gradle project is configured.  `flutter create` generates a basic gradle project, but after that it's completely under the control of the developer.  We perhaps should change our template to have better defaults:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/create/android.tmpl

That said, it's also possible I'm mis-understanding and there is a bug in `flutter build` itself.  But I suspect that all mipmap stuff is handled by the Android toolchain which we just call into?  @jakobr-google

**Comment by jakobr-google** [comment]
This is all taken care of by the Android toolchain, and should work just like any other Android app.

We don't ship a `ic_launcher_round` icon (or reference it), so I assume that's something you've added? The mipmap folders are in `android/app/src/main/res/`, so that's where the icons should go. If that doesn't work, can you share your project (or a simplified version of it) with us?

**Comment by tombirmingham** [comment]
Ok, will get to it this afternoon.

**Comment by tombirmingham** [comment]
test_case_1:
1.
Created with "flutter create" with cmdline.
2.
Launch it with Android Studio.
- Dialog pops up as follows:
    - Unknown Module Type
          - Cannot determine module type  ("FLUTTER_MODULE_TYPE") for the following module "test_case_1".  The module will be treated as a Unknown module.
          - (leave as is, not sure what to do here)
          - Android frameworks is detected in the project
                - I click on "Configure" and select "AndroidManifest.xml".  All seems ok.
- Open AndroidManifest.xml and it shows @mipmap/ic_launcher in red (can't resolve).
    - I check the mipmap folders, the flutter ic_launcher png's exist.
3.
Try to Build project now (Make Modules 'android', 'test_case_1' and get Error:
    - Cannot start compilation: the output path is not specified for module "android".  Specify the output path in the Configure Project.
    - Project Structure dialog comes up (not sure what to do here, so leave as is)
4.
 - flutter run
    (all is ok, runs app in Emulator)
5.
 - flutter build apk
    (all is ok, builds apk with success)

- Now the Project says "Migrate Project to Gradle?".  So it is now not building with Gradle but the cmd line works fine for build and run in Emulator.

- Also; I updated the mipmap folders with my own icons and when I build it for the Emulator and Play Store, it has my icons.  So all seems to be ok except it still shows red and now not building with Gradle.

- See attached project...
[test_case_1.zip](https://github.com/flutter/flutter/files/991076/test_case_1.zip)

**Comment by jakobr-google** [comment]
These all look like issues with Android Studio. It doesn't have the Flutter plugin, so it doesn't know what FLUTTER_MODULE_TYPE is, and when you "configure" the Android framework by pointing at the manifest, it apparently completely ignores that we already have a complete Android project (with Gradle build files) in the `android/` folder.

I would recommend using Intellij IDEA as the IDE for developing Flutter apps (https://flutter.io/intellij-setup/). You can definitely use Android Studio, but I would open the project by importing android/build.gradle instead of pointing it at the AndroidManifest.xml file (should happen automatically if you open the `android/` folder instead of the main project folder). If you import it as a Gradle project, the icons resolve fine. You won't get all the Fluttery goodness (like hot reload) without the Flutter plugin, though.

`flutter run` and `flutter build apk` build the app using Gradle.

cc @mit-mit to see what we can do to improve the Studio experience.

**Comment by tombirmingham** [comment]
Looking at the IntelliJ IDEA Install setup, it only has macOS and Linux.  I
assume it also works with Windows?

**Comment by mit-mit** [comment]
Yes, you can definitely use IntelliJ IDEA on Windows also. I'll get that page updated!

**Comment by tombirmingham** [comment]
Another place where it only refers to Mac and Linux, not Windows:

"Getting Started with Flutter"
    "Before you begin"

**Comment by mit-mit** [comment]
Good catch! Addressing in https://github.com/flutter/website/pull/556

**Comment by mit-mit** [comment]
Going to close this bug as it sounds like the original issue was resolved.

The request to support more Flutter development in Android Studio is tracked in https://github.com/flutter/flutter-intellij/issues/384, feel free to "up vote" that bug.

**Comment by selva8006black** [comment]
for me this  happen when i placed generated icon from appicon.com to res directory.  generated file  name mismatch  with androidManifest.xml. renaming file  name solved the  issue.
