### ISSUE TITLE
Widget inspector is not working

### ISSUE THREAD

**Issue by mgesmundo** [flutter/flutter#99487]
Hi there,

I noticed that the Widget inspector is not working using CupertinoPageScaffold. I've opened an issue here: https://github.com/flutter/samples/issues/1034, but I think that this is the right place.
There is some workaround to make Widget inspector work using the Cupertino widgets?
Thank you.

**Comment by darshankawar** [comment]
@mgesmundo 
Since Widget Inspector is part of devtools, issues related to it should be reported in dedicated repo: https://github.com/flutter/devtools/issues
Per [this](https://github.com/flutter/samples/issues/1034#issuecomment-1058415046) comment, there seems to be already a similar issue that you can follow-up in.
Closing from here.
