### ISSUE TITLE
The camera plugin can not get started.

### ISSUE THREAD

**Issue by Kakukaho** [flutter/flutter#99544]
camera 0.9.4+14
camera_web 0.2.1+3

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

```
% flutter run
Launching lib/main.dart on Chrome in debug mode...
/usr/local/Cellar/flutter/.pub-cache/hosted/pub.dartlang.org/camera_web-0.2.1+3/lib/src/shims/dart_js_util.dart:14:7: Error:
Expected 0 type arguments.
      js_util.getProperty<dynamic>(o, name);
      ^
Waiting for connection from debug service on Chrome...             15.8s
Failed to compile application.
rex@rex-de-MacBook example % flutter run
Launching lib/main.dart on Chrome in debug mode...
/usr/local/Cellar/flutter/.pub-cache/hosted/pub.dartlang.org/camera_web-0.2.1+3/lib/src/shims/dart_js_util.dart:14:7: Error:
Expected 0 type arguments.
      js_util.getProperty<dynamic>(o, name);
      ^
Waiting for connection from debug service on Chrome...             15.5s
Failed to compile application.
```

**Comment by darshankawar** [comment]
@Kakukaho 
I added both plugins in a sample app and ran it on web using latest master version which compiled and built properly without any issues:

```
dhs@Dhss-MacBook-Pro testdemo % flutter run -d chrome
Running "flutter pub get" in testdemo...                         2,198ms
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.7s
This app is linked to the debug service: ws://127.0.0.1:52774/70rCkO7x6ig=/ws
Debug service listening on ws://127.0.0.1:52774/70rCkO7x6ig=/ws

💪 Running with sound null safety 💪

```

```
 camera: ^0.9.4+14
  camera_web: ^0.2.1+3
```

Can you upgrade to latest stable and try again to see if it helps ?

**Comment by stuartmorgan** [comment]
Apparently the changes in `camera_web` 0.2.1+3 accidentally broke compatibility with Flutter 2.5; since we weren't aware of that when making the change, the minimum Flutter version wasn't updated.

In general we only commit to supporting the current stable release and newer with flutter/plugins. If we'd learned about this sooner we could easily retract that version, but we're passed the retraction window now. Since this is an experimental, unendorsed plugin, and this only affects a version of Flutter that is two stable releases behind, it's not something we would do two more plugin releases to fix.

Given that, your options are to update to at least Flutter 2.8, or to pin to 0.2.1+2 until you are ready to update.
