### ISSUE TITLE
Buffering flag in not working 

### ISSUE THREAD

**Issue by pratapvikram** [flutter/flutter#99561]
controller.isBuffering is false when video is still buffering.
Functionality is stopped due to this things.Please help asap.

**Comment by darshankawar** [comment]
@pratapvikram 
Can you provide `flutter doctor -v` , video_player plugin version you are using along with a minimal code sample that shows the issue you are reporting ?

Also as a note, when you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.

`Please help asap.`  we can't help if there's not enough details provided, so please be patient.
