### ISSUE TITLE
Is there anyway to disable default splash screen for android 12

### ISSUE THREAD

**Issue by umersaddiq** [flutter/flutter#99585]
I want to add custom splash screen but before that the default splash screen displayed which looks too weird

**Comment by MartimTSilva** [comment]
Go to `android/app/src/main/res/values/styles.xml`

Add `<item name="android:windowIsTranslucent">true</item>` to your style

```
<style name="YourThemeName" parent="Theme.AppCompat.Light.NoActionBar"> 
    <item name="android:windowIsTranslucent">true</item>
</style>
```

**Comment by danagbemava-nc** [comment]
Hi @umersaddiq, 

The flutter issue tracker is for reporting bugs in flutter or for feature requests. 

This issue seems like neither of those. Kindly visit any of the communities in https://flutter.dev/community#community-grid for asking these types of support questions. 

Closing as this is neither a bug report nor a feature request. 

Thank you

**Comment by umersaddiq** [comment]
> Go to `android/app/src/main/res/values/styles.xml`
> 
> Add `<item name="android:windowIsTranslucent">true</item>` to your style
> 
> ```
> <style name="YourThemeName" parent="Theme.AppCompat.Light.NoActionBar"> 
>     <item name="android:windowIsTranslucent">true</item>
> </style>
> ```

When I add this line it holds the status bar space from top, I want to display the content on full screen

![Screenshot_20220308_095645](https://user-images.githubusercontent.com/54848395/157169237-c10fec44-f5c0-4c6b-9b28-09a870e04771.jpg)
![Screenshot_20220308_095629](https://user-images.githubusercontent.com/54848395/157169248-58f6f8c4-4822-47d8-97cb-98ccbbe11496.jpg)
