### ISSUE TITLE
Draggable is not Tappable

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#996]
My scenario is that I want a card to have the option of being dragged or tapped. This is pretty common in card games. Unfortunately, I could not manage to get both drag and tap enabled at the same time.

I tried:
* GestureDetector -> Draggable<MyCard> -> MyCard
* Draggable<MyCard> -> MyCard (with MyCard wrapping its build output with a top-level GestureDetector)

In both cases, the taps were completely ignored.

However, it is and should be possible to have both tap-enabled and drag-enabled. If I remove line 163 (`    _activePointers[pointer].resolve(GestureDisposition.accepted);`), then I can make items both Draggable and Tappable. I think this resolve step is preventing potentially useful gestures from being received. Can the offending line be removed without harming other apps?

https://github.com/flutter/flutter/blob/5b42f83ff3d53d8ac6e6b8cdf87898457983a604/packages/flutter/lib/src/widgets/drag_target.dart#L163

**Comment by Hixie** [comment]
Draggable starts the drag on pointer-down. What you want is a ShortPressDraggable, something similar to LongPressDraggable but that starts the dragging gesture after a short timeout. Or maybe "DragDraggable" that starts the dragging gesture after the finger has exit the slop area.

**Comment by Hixie** [comment]
(You can tell the difference between one of those and what we have now by making the drag avatar be bigger or offset or something visible -- with Draggable, the avatar appears immediately, whereas with a delayed draggable, it'd only appear once you're past the condition.)

We can maybe make the default Draggable less aggressive and only win by default if there's no other gesture going on. That would give the current behaviour if there's no competing tap, and the behaviour you describe otherwise. That might require a bit of rejigging how it's built, though.

**Comment by afandria** [comment]
Delayed Draggable would work if it starts setting the disposition only after the timeout.

That said, would it be good to have Draggable expose all the GestureDetector stuff? (Or the reverse? Have a GestureDetector that also has onDrag?)
