### ISSUE TITLE
Stop automatically locking issues

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#99605]
I need to comment on #98151 but cannot because it is locked.

**Comment by jonahwilliams** [comment]
Before we locked issues, folks would regularly comment things like "Having this issue" on long closed dormant bugs, without providing any additional details that could be reasonably used to diagnose their problem. This happened so frequently that it became a significant drag on triaging issues - and was often misleading as different bugs can have similar looking effects.

Closing and locking old issues is meant to encourage users to file new bugs with the issue templates correctly filled out so that members of the team can adequately diagnose the issue. (And you are certainly free to link old issues in your new issue).

**Comment by mleonhard** [comment]
#89141
