### ISSUE TITLE
[Material] [InkSparkle] Change SPIR-V byte code from static const to a file to prepare for Impeller

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#99783]
Binary is currently here: https://github.com/material-components/material-components-flutter-experimental/tree/fragment-shader-manager/fragment_shader_manager/shaders

**Comment by zanderso** [comment]
Is there any update on this? My understanding from the discussion on the PR was that that this would be a quick follow-up.

@chriscraws @HansMuller @goderbauer

**Comment by HansMuller** [comment]
We've discussed this (@clocksmith). A PR that uses a precompiled asset is forthcoming.

**Comment by clocksmith** [comment]
May need some quick help on setting this up, but I can take a look

**Comment by zanderso** [comment]
An example of an asset needed for material is the material fonts. The data for the shader can be handled in a similar way. Here's the code in the tool where the fonts are bundled as assets whenever `uses-material-design` is in the pubspec:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/asset.dart#L493

With that wired up, the shader data can be loaded like any other asset. Fetching the data and making a bytebuffer out of it would probably have to be made async: https://github.com/flutter/flutter/blob/bb2cca5f59a1f559a5d686e68fb89dfffe7a05e0/packages/flutter/lib/src/material/ink_sparkle.dart#L683

But the shader transpiling is already async, so that should not cause any difficulties.

**Comment by clocksmith** [comment]
Ok this looks relatively straight forward. I will try to send something out by tomorrow. Thanks!

**Comment by clocksmith** [comment]
https://github.com/flutter/flutter/pull/101699

Question: what folder should ink_sparkle.spv be placed in? For this WIP, I placed it in a sibling directory of material_fonts, but that is under the root directory bin/cache, which seems wrong.

**Comment by dnfield** [comment]
Alternatively, can we check in the source code here and compile it at build time?

**Comment by zanderso** [comment]
@dnfield SPIR-V bytecode is more like source than like a binary file. To support Impeller this is also likely to be replaced in the near future with the GLSL source, so I'd like to avoid the churn of putting it into a gcs bucket, only to remove it again soon.

**Comment by goderbauer** [comment]
> Maybe in packages/flutter/lib/src/material/shaders or packages/flutter/data/shaders

This is just an implementation detail that's not exposed in our API's right? Since it belongs to the material library, I would put it into `packages/flutter/lib/src/material/shaders`. 

From https://github.com/flutter/flutter/pull/101699/files the asset does look pretty binary, though. How soon will the replacement with GLSL source happen? It's a bit odd that we are just moving from one temporary solution to another temporary one here...

**Comment by clocksmith** [comment]
I was unaware that impeller was using GLSL shaders. Are those being transpiled to SPIR-V at build time? I might have pasted the wrong file, but now that I have a better idea of where it should live. I can test the SPV binary. But ultimately the source is the GLSL? That can be moved to shaders as well if there is an existing mechanism to transpile to SPIR-V?

**Comment by clocksmith** [comment]
edit: the spv is not yet in the PR, it is a binary

**Comment by clocksmith** [comment]
OK this is the piece I was missing:

```
Shaders are authored once in GLSL 4.60. This choice of shading language is consistent across all backends. Shader code resides in the Impeller source tree like any other source file.
At build time, the Impeller Shader Compiler (impellerc) converts the GLSL into SPIRV. No optimizations are performed on the generated SPIRV at this stage. This is to preserve all debugging and instrumentation information.
Using the SPIRV, a backend specific transpiler converts the SPIRV to the appropriate high-level shading language. This is controlled using flags to the impellerc.
```

I understand now

**Comment by clocksmith** [comment]
Once it is replaced with GLSL, and it gets converted to SPIRV at build time, will it be consumed the same way it is in this PR? If not, I don't think there is any action required here other than adding the GLSL to material/shaders. WDYT?

**Comment by zanderso** [comment]
It will get consumed in the same way, as a file asset.

**Comment by clocksmith** [comment]
will the impellerc compiled SPV have the same path as the source GLSL?

**Comment by zanderso** [comment]
The path of the asset from the perspective of the framework will be roughly similar, but it will need to be pulled from somewhere different by the tool build.

**Comment by dnfield** [comment]
I believe there's a script that will flag this if we try to add it as a binary asset. We've intentionally made it challenging to add new binary assets to avoid things like this.

We'd never have to remove the asset from the GCS bucket. Maybe there's an argument to make that this should get an exception because it was already in the repo as a binary asset embedded in source code and embedded there in a less efficient manner...

**Comment by clocksmith** [comment]
Pending question in https://github.com/flutter/flutter/pull/101699

**Comment by clocksmith** [comment]
https://github.com/flutter/flutter/pull/102674

**Comment by zanderso** [comment]
This is done.
