### ISSUE TITLE
[Flutter plugins] [Video Player] Updated video player crashes when reading messages

### ISSUE THREAD

**Issue by robert-j-webb** [flutter/flutter#99946]
Recently the video player plugin has been updated. I have been trying to integrate it into the company I work for's code but I found an issue where it was crashing in `Messages.java` due to a type mismatch. 

I managed to fix the issue by updating the pigeon version for the video_player_platform_interface - I could generate an error message if I need to, but I believe my PR will pretty clearly illustrate the problem.

**Comment by darshankawar** [comment]
Thanks for the report and potential fix for it. Is it possible to provide the error message you were getting along with steps to replicate ?

**Comment by stuartmorgan** [comment]
The issue you are having is that the tooling you are using doesn't support Dart plugin autoregistration, which means that you are using the default method channel implementation on the Dart side (which is no longer correct) with the native side of the in-implementation-package method channel implementation, and they don't match.

You should have gotten a message about no handlers being registered on that method channel instead of a crash, but I forgot to change the Pigeon class name (and thus the method channel name) when moving them in-package the way we have been doing for non-Pigeon channels. (Which I'll fix so the failure mode is a little less confusing.)

The workaround until your tooling supports Dart plugin registration is to register it manually when your app starts up. E.g.:

```
import 'package:video_player_android/video_player_android.dart';
import 'package:video_player_avfoundation/video_player_avfoundation.dart';

void main() {
  if (Platform.isAndroid) AndroidVideoPlayer.registerWith();
  if (Platform.isIOS) AVFoundationVideoPlayer.registerWith();
  ...
}
```

**Comment by robert-j-webb** [comment]
Thanks Stuart, I really appreciate the punctual response. I'll make sure to update the internal documentation for video player to reflect this necessary import
