### ISSUE TITLE
[Android][Production]: java.lang.IllegalArgumentException sectionName is too long

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#99980]
Hi,

A user reported an issue that the app is not opening. Every time he clicks on the launcher icon, the app crashes.
When I checked the Crashlytics for that user_id, it showed the below crash.

```
Fatal Exception: java.lang.IllegalArgumentException
sectionName is too long

Fatal Exception: java.lang.IllegalArgumentException: sectionName is too long
       at android.os.Trace.beginSection(Trace.java:287)
       at androidx.tracing.TraceApi18Impl.beginSection(TraceApi18Impl.java)
       at androidx.tracing.Trace.beginSection(Trace.java:6)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java:17)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$6ZD1MYkhaLxyPjtoFDxe45u43DI(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$75ebfcfd53b0b0a884b1e22267a97587635cd2630d2f814c3024af8922adcf72$0.run(DartMessenger.java:12)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

```
Device
Brand:Xiaomi
Model:M2101K6R
Orientation: Portrait
RAM free: 2.4 GB
Disk free: 64.14 GB

Operating System
Version:Android 12
Orientation: Portrait
Rooted:No
```

![Screen Shot 2022-03-11 at 9 06 07 PM](https://user-images.githubusercontent.com/14223997/157898600-fe7e2601-8750-4a37-a2ed-0ba8160f6282.png)

**Comment by darshankawar** [comment]
> Fatal Exception: java.lang.IllegalArgumentException
> sectionName is too long

This seems to be coming from native:

https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-12.1.0_r1/core/java/android/os/Trace.java#284

The `sectionName` max need to be 127 unitcode long and in your case / app, it seems to be exceeding the limit and hence the error.



> very time he clicks on the launcher icon, the app crashes.

Are you able to replicate this locally ?

**Comment by deepak786** [comment]
no

**Comment by darshankawar** [comment]
With no concrete reproducible use case to verify, I'll label it for further insights from the team.

For team's reference: https://github.com/flutter/flutter/issues/99980#issuecomment-1066443358

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
This seems to be caused by the trace event names being too long. Specifically it is [this call here](https://github.com/flutter/engine/blob/67594ec725b7979987f81d57864b0ac58b18a914/shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java#L318). Depending on how long the channel name is, it is totally possible to make the trace size go over some internal limit.

As @darshankawar pointed out, documentation for tracing says the section name [must be 127 unicode code units long](https://developer.android.com/reference/android/os/Trace#beginSection(java.lang.String)).

The easiest quick fix would be to remove the trace. Though ideally, we should make sure trace names are manually truncated or const strings.

These traces were added [approximately 5 months ago](https://github.com/flutter/engine/pull/29230) by @jiahaog and reviewed by @blasten @xster @dnfield with a cross reference to an internal issue. Just a heads up that this could lead to runtime instability.

**Comment by dnfield** [comment]
The goal of adding the channel name into the trace was to assist with reading traces and knowing which channel the trace was happening on. 

We should update all those call sites to make sure we don't exceed 127 code units when using any kind of dynamic string.

**Comment by dnfield** [comment]
Starting with a revert to get this resolved ASAP.

**Comment by dnfield** [comment]
Argh. This is not easily revert-able because of conflicts. I'll see if I can manually fix first.

**Comment by dnfield** [comment]
I have a fix forward ready.

**Comment by dnfield** [comment]
Should this be considered a CP candidate? 

Alternative question: is there anything we can do to guarantee this ends up in the next beta?  @zanderso

**Comment by zanderso** [comment]
@dnfield We can request a cherry-pick to 2.12. Since there's no tag for it, that would happen directly in the release chat. Does the PR apply cleanly to the 2.12 branch?

It is very late in the cycle for a 2.10 cherry-pick. A few questions:
1. @darshankawar have you seen any other reports like this? Trying to understand how widespread this issue is.
2. @dnfield Does https://github.com/flutter/engine/pull/32042 apply cleanly to 2.10?
3. @dnfield How risky is https://github.com/flutter/engine/pull/32042? If there's any chance that the forward fix could introduce a new problem, then I think I'd say no to a cp. A straight revert would be easier to approve at this stage, but the issue would still need to be quite severe and widespread.

**Comment by darshankawar** [comment]
> 1. @darshankawar have you seen any other reports like this? Trying to understand how widespread this issue is.

@zanderso No. This was the first report I saw throwing such error. Didn't find any similar reports before.

**Comment by dnfield** [comment]
flutter/engine@c5e958ebde36887f2954c5df5ad3b3dfaf790474 cleanly cherry-picks on to flutter-2.12-candidate.5.

I'm not sure what the right branch or tag to check for 2.10 is.

I avoided doing a revert because a revert would not cleanly apply to main and the conflicts were not super trivial to resolve.
